### PR TITLE
[IMP] core: filtering through o2m

### PR DESCRIPTION
**Pull request by xmo-odoo**
Replaces the natural join scheme which is pretty fast but doesn't
quite work (it's *completely* broken for read_group) by a subquery
which is slower but should have the same semantics as the ORM version.

Ideally we'd use `EXISTS (select 1 from ...)` but that has no support
inside the SQL compiler right now, so use `id in (select inverse_field
from ...)`.

We might even want to consider deprecating auto_join on o2ms and
replacing the ORM-based version of the filter by this, doing some
synthetic tests, a read_group on a simple object with lines filtered
on line values (similar to `read_group([('order_line.product_uom',
'=', xxx)], ['total_amount'], ['user_id'])`:

|     |ORM  |join |subquery|
|-|-|-|-|
|large|160  |10   |20      |
|many |36000|50   |180     |

* values of data fields (filtering, grouping and aggregating) randomly
picked between 10 different values
* "large" is 1000 objects with 1000~15000 lines each
* "many" is 1000000 objects with 1~40 lines each

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@rco-odoo @odony this is a bit of a touchy one but it seems to have potential for significant improvements on queries filtering through an o2m, and might even be backportable?

* it fixes read_group being completely broken when doing a read_group filtered through an o2m with auto_join true (though it's slower)
* it's way faster than potentially loading thousands or millions of line ids from the db

**Comment by xmo-odoo** [comment]
@rco-odoo @odony note: for testing, I changed the code to have both "normal" and "auto_join" filters go through this change, we could keep this in all cases *but* for the normal case it means we'd now be bypassing the `search` on the comodel https://github.com/odoo/odoo/blob/cea532e3764f9a2c746b1be31f26ce163f597520/odoo/osv/expression.py#L908-L911
which I guess might be an issue sometimes?

**Comment by rco-odoo** [comment]
@xmo-odoo I just added a test that documents the wrong behavior of `read_group` in the presence of auto-joined one2many fields in domains.  Your patch correctly fixes the behavior.

I also removed the deduplication of results in `search`, which was necessary for exactly the same wrong behavior.

**Comment by rco-odoo** [comment]
@robodoo rebase-ff r+

**Comment by xmo-odoo** [comment]
TODO: try to find old tickets & github issues linked to this issue

**Pull request closed without merging**
