### PR TITLE
Patch for control mrp line creation

### PR DESCRIPTION
**Pull request by Viggor**
This patch extract the control of mrp line creation for easier inheritance.

Original author: Sebastien Beau

### CODE REVIEW

**Comment by bealdav** [comment]
:+1: for me. Only move code. Inherit is now possible without breaking code

**Comment by chafique-delli** [comment]
It's ok for me :+1:

**Comment by sylvainc** [comment]
:+1:

**Comment by clonedagain** [comment]
Can you add a docstring please?

**Comment by nim-odoo** [comment]
@Viggor : it seems ok to me. However, could you:
- add a docstring
- make your commit message more explicit (explain what and especially why you are doing so)
- make the diff as short as possible. I guess your editor automatically removes trailing whitespaces: this is correct following PEP8, however it makes the blame more difficult.
Thanks!

**Comment by Viggor** [comment]
I'v done your demand, tell me if the commit message is good or not.
Thanks.

**Comment by nim-odoo** [comment]
The commit is still a bit short/unclear: I understand that you want to extract this piece of code in order to override the behavior, but do you have a use case where this could be useful?

**Comment by bealdav** [comment]
Here is an example of override

mrp

We want to have a generic bom and make it dynamic according to the attributes of the parent product of our bom head product.

With this method, you can get customized behavior but keep it consistent with classic MRP behavior. And it is for this kind of method than Odoo is an Microsoft / Sage killer for large customer (~ 100 users)
You'll see that on your next increase entreprise contracts. 

Thanks a lot for time on this PR.

I hope

**Comment by nim-odoo** [comment]
Thanks for the clarification. Merged with b60d41984832774f4aefc7fe45e66542c63ed0b5

**Pull request closed without merging**
