### PR TITLE
[FIX] l10n_be: missing mappings of accounts to financial repoorts

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Hello Stéphane, 

Could you explain the point of this proposal ?
This is obvious that it adds some accounts to two financial reports. However, for the report "Fournisseurs" (`account_financial_report_fournisseurs4`), I see that the view account 440 is already within the accounts of this report, and it seems therefore useless to me to add the children account. See below screenshot for illustration.
financial reports openerp

Why do you want to add the children accounts ? Does it change something to the amounts computed ? Isn't the amount of the children contained in the view ?

**Comment by sbidoul** [comment]
Well, the accounts I add (444, 446, ...) are *not* children of 440.

**Comment by beledouxdenis** [comment]
Indeed ! Sorry for my misunderstanding. I guess I can trust you on the fact these accounts should be added to this "Fournisseurs" report.

One more thing, where can I print this report ? I am not able to find the right menu.

**Comment by sbidoul** [comment]
@beledouxdenis accounts 444 definitively go into the "Supplier" section of the balance sheet.

Its reasonable to put 446 and 448 in that same section although these accounts are not part of the official belgian PCMN they might as well be dropped completely.

To print the report go to Account > Financial Reports > Legal Reports > Belgium > Balance Sheet.

**Comment by beledouxdenis** [comment]
Closed with 63aed836379107068a9afe8dd586e5962121bb9c.

Thanks for your contribution !

**Pull request closed without merging**
