### PR TITLE
Don't copy analytic lines of sub-accounts when copying an analytic view

### PR DESCRIPTION
**Pull request by ccomb**
- Take time to lovingly create your ideal analytic chart of account with 3 sublevels of account
- Work for a few months and enter a lot of analytic lines in the leaf accounts
- One day, decide to rearrange your chart of account and duplicate one of the view account

→ The whole hierarchy is duplicated (which is ok) but **all the analytic lines are duplicated as well !**

There is a similar and old report here: https://bugs.launchpad.net/openobject-addons/+bug/1149676

Analysis:

When duplicating an analytic account, in the copy() method, the line_ids is emptied through the `default` argument to avoid duplicating its analytic lines. _BUT_, when you duplicate an analytic view higher in the hierarchy, the copy() method then use the copy_data() method during recursion, which is not protected against the copy of analytic lines.  So I've moved a part of the code in the copy_data() method. However I kept the new name computation in the copy() method so that _only_ the explicitely copied account is renamed `foobar (copy)`, but the accounts below have the same name, to avoid renaming them all manually (imagine you're copying a big hierarchy with tenth of accounts).

And I've created a yml unittest to enforce this behaviour.

### CODE REVIEW

**Comment by ccomb** [comment]
In version 8 the recursive copy of the analytic accounts is disabled by the new default copy=False behaviour on the one2many fields,  which is a total pain to duplicate account hierarchies. By forward-porting this fix to v8 it would allow to have the best of both world as well in v8.

**Comment by mdietrichc2c** [comment]
Hello,
it's a shame I missed this PR when I made https://github.com/odoo/odoo/pull/6617 ; yours has the unit test + still copies children.
Is it possible for your code to be based on the most recent version of 7.0? I'd prefer to approve this one.

**Comment by yvaucher** [comment]
:+1:

**Comment by ccomb** [comment]
I rebased on latest

**Comment by mdietrichc2c** [comment]
Sorry, mixed my PRs. This one is all good, :+1:

**Comment by lmignon** [comment]
@ccomb Once again with tests! :+1:

**Comment by lmignon** [comment]
@ccomb your test fails on runbot :-(

```
015-05-22 14:49:36,413 25818 TEST 71741-6368-e2eb12-all openerp.tools.yaml_import: We create a simple hierarchy like this Toplevel view account â”œ Real analytic account 1 â”” Real analytic account 2
2015-05-22 14:49:36,454 25818 TEST 71741-6368-e2eb12-all openerp.tools.yaml_import: Creating !record {model: account.analytic.account, id: analytic_account1}:
 with {'parent_id': 'analytic_account_view1', 'type': 'normal', 'name': 'Real analytic account 1'}
2015-05-22 14:49:36,495 25818 TEST 71741-6368-e2eb12-all openerp.tools.yaml_import: Creating !record {model: account.analytic.account, id: analytic_account2}:
 with {'parent_id': 'analytic_account_view1', 'type': 'normal', 'name': 'Real analytic account 2'}
2015-05-22 14:49:36,533 25818 TEST 71741-6368-e2eb12-all openerp.tools.yaml_import: We add analytic lines in real accounts and journal
2015-05-22 14:49:36,539 25818 TEST 71741-6368-e2eb12-all openerp.tools.yaml_import: Creating !record {model: account.analytic.line, id: analytic_line1}:
 with {'journal_id': 'analytic_journal1', 'account_id': 'analytic_account1', 'name': 'Analytic line 1'}
2015-05-22 14:49:36,550 25818 ERROR 71741-6368-e2eb12-all openerp.tools.yaml_import: null value in column "general_account_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 2015-05-22 14:49:29.210438, 2015-05-22 14:49:29.210438, 1, 0.00, null, Analytic line 1, null, 2015-05-22, 1, 50, null, null, null, null, null, null, 5, null, null).
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/71741-6368-e2eb12/openerp/tools/yaml_import.py", line 867, in process
    self._process_node(node)
  File "/home/odoo/runbot/extra/runbot/static/build/71741-6368-e2eb12/openerp/tools/yaml_import.py", line 878, in _process_node
    self.process_record(node)
  File "/home/odoo/runbot/extra/runbot/static/build/71741-6368-e2eb12/openerp/tools/yaml_import.py", line 328, in process_record
    self.module, record_dict, record.id, noupdate=self.isnoupdate(record), mode=self.mode, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/71741-6368-e2eb12/openerp/addons/base/ir/ir_model.py", line 983, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/71741-6368-e2eb12/openerp/osv/orm.py", line 4560, in create
    cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
  File "/home/odoo/runbot/extra/runbot/static/build/71741-6368-e2eb12/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/71741-6368-e2eb12/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "general_account_id" violates not-null constraint
```

**Comment by ccomb** [comment]
Oddly I couldn't reproduce in local, but I added the general account, let's see if it's better.

**Comment by lmignon** [comment]
@ccomb  runbot fixed :+1:

**Comment by mart-e** [comment]
Thanks for the patch. It looks good to me.
It was merged at 2c37f834351090210ac57c29b974a636e9fea3a8

For the issue with copy=False in 8.0 on child accounts, don't hesitate to submit a patch to put the field to copy=True, that seems like an error to me (but should be discussed on an appropriate PR)

**Pull request closed without merging**
