### PR TITLE
[MERGE][ADD] product,(website_)sale: product documents

### PR DESCRIPTION
**Pull request by Feyensv**
Introduce new model of "Product Documents" to hold documents linked
to a given product template/variant, displayed on:

* quotations
* confirmed sale orders
* e-commerce product page

This will also replace the previous "Digital Files" (website_sale_digital)
logic & module, which allowed to specify product documents available
to customers after the SO invoice was paid.

This exact feature will be lost after upgrade, since we only keep the
choice to link documents on quotations/orders, but:

1) on e-commerce, carts are supposed paid when confirmed
2) on portal, the "Online Payment" settings makes sure the users
have to pay to confirm their quotation.

therefore we consider new configuration sufficient, without needing
a "paid order" choice as well.

task-3249201

See also:
* https://github.com/odoo/enterprise/pull/46106
* https://github.com/odoo/upgrade/pull/5069

### CODE REVIEW

**Review by xmo-odoo — COMMENTED** [review]
The ACL situation seems dubious, especially with the attachments being only linked to product documents (the model not even individual records), which are readable by any user, with no explicit `check()` or rules.

Also feature can only be used (written) by system users?

**Comment by Feyensv** [comment]
@xmo-odoo It wasn't linked to `product.product` or `product.template` records because at first we thought it was better to not have those attachments in the chatter.  But finally, we want documents added to the chatter to create `product.document` automatically and vice versa, so we went back to attachments linked to the template/variant record.

For the ACL, indeed, I fixed it (also added a multi-company rule).
By the way, is it expected that `ir.attachment` records are accessible to internal users, regardless of their `company_id` or am I missing something ?

**Comment by Feyensv** [comment]
@robodoo r+ rebase-merge

**Comment by Feyensv** [comment]
What's the point of the `company_id` field then ? :thinking:

**Comment by Feyensv** [comment]
feedback for @bouvyd then, it could make sense to correctly manage multi-company on attachments ;)

**Pull request closed without merging**
