### PR TITLE
[REF] payment_transfer: rename to `payment_custom` and distinguish modes

### PR DESCRIPTION
**Pull request by Feyensv**
See the individual commits for more details.

task-2853489

See also:
- https://github.com/odoo/enterprise/pull/30966
- https://github.com/odoo/upgrade/pull/3847

### CODE REVIEW

**Comment by Feyensv** [comment]
@Williambraecky sorry for the late ping on this PR.
We're going to merge this soon and we think it's fixing some problems in the payment flows, especially with the behavior of onsite/COD acquirers.

Now that `payment_transfer` is not auto installed anymore, we skip some website_sale tests when it's not installed, to make sure tests are as green as before, even when running them in local.  Ideally, those tests should be adapted to not rely on the Transfer acquirer or moved in a test module with `payment_custom` as dependency.

**Comment by AntoineVDV** [comment]
@robodoo rebase-ff

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
