### PR TITLE
[FIX] account: action_invoice_paid never called on invoices

### PR DESCRIPTION
**Pull request by qdp-odoo**
This function used to be called on invoices rights after they get paid, but since the refactoring of account.invoices and account.move, it wasn't the case anymore, resulting in broken workflow/use cases (sale, event_sale...).

Failing use case: confirm a SO, create its invoice, register the payment, look back at the SO: there's no message logged to say the invoice has been paid although the code of action_invoice_paid() is doing it and should have been called at some point.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@nim-odoo the patch proposed by @smetl works. Does it suit you better?

**Comment by smetl** [comment]
Note: Take care about the `invoice_payment_state` field has been renamed in `master`.

**Comment by qdp-odoo** [comment]
@smetl good job dude, I was about to lose my nerves on that PR -_-

**Comment by nim-odoo** [comment]
review in progress :smile:

**Comment by nim-odoo** [comment]
Long story short, what we need here is the old workflow engine that was removed a couple of versions ago :rofl: 

I am not a fan of this solution either, but I fear our options are limited. The only other possibility I see is an automated action (a new module would be needed since `base_automation` is not in the dependencies of `account`). So far, this seems working:

Screenshot_2020-01-28 invoice - Odoo

I'll check with some wise people if another solution can be considered.

**Comment by qdp-odoo** [comment]
jesus

**Comment by smetl** [comment]
@robodoo r+

**Comment by nim-odoo** [comment]
robodoo r-

**Comment by nim-odoo** [comment]
After discussion with the wise (DLE and RCO), the override of `_write` is not a good option:
- `_write` not supposed to initiate the computation of new fields, which would be the case in `event_sale` for example (and potentially in third-party modules)
- it only works if `flush` is not called before `write`, which you can never be sure of.

Therefore, the risk is high for this override to fail at some point.

The base automation seems to be the safest way, although I agree it may look overkill since a new module is required in stable. I can have a look to do it, no problem.

**Comment by qdp-odoo** [comment]
@nim-odoo ok dude, do so... We leave the case to you

**Comment by rco-odoo** [comment]
As @nim-odoo wrote, this is not a good solution.

**Pull request closed without merging**
