### PR TITLE
[FIX] point_of_sale: push invoice and print it

### PR DESCRIPTION
**Pull request by kebeclibre**
[FIX] point_of_sale: offline invoicing => backend printing

In a pos session:
OFFLINE
make an order with invoicing , try to validate
    The order stays there because it needs to be validated by the server
make another non invoiced order, validate

ONLINE
make another order
    At validation, all orders will be pushed to the server

Before this commit, when trying to validate the invoiced order
the report download couldn't find the order id, and crashed
This was because the order in question was already pushed
but treated as a non invoiced order

After this commit, an "warning" message is displayed to the customer
saying he/she has to print the invoice from the backend.
In most cases it is enough and acceptable, since a customer would actually leave the premises
and come back later for the invoice
It is also safer in terms of data consistency to keep pushing all orders once the connection is back

OPW 1918044

### CODE REVIEW

**Comment by jorenvo** [comment]
Do we even want to allow offline invoicing? The point of invoicing in the POS is to be able to give an invoice to the customer in your shop. We can't do that if there's no connection to the server because we can't create an invoice.

**Comment by kebeclibre** [comment]
@jorenvo 
I spoke with @lap-odoo . It is acceptable to force invoice printing from the backend. My new fix unblocks the user.
I'll add the .pot file once the concept of the PR is approved

**Comment by kebeclibre** [comment]
Fyi it will look like this:
screenshot from 2019-01-24 11-00-58

**Comment by kebeclibre** [comment]
robodoo r+

**Comment by kebeclibre** [comment]
robodoo r+

**Comment by kebeclibre** [comment]
robodoo r+ retry pretty please

**Comment by kebeclibre** [comment]
robodoo retry please discard the errors in 10.0 !!

**Comment by kebeclibre** [comment]
robodoo retry please discard the errors in 10.0 !!

**Comment by KangOl** [comment]
@robodoo As I known you will fail, r- r+

**Comment by KangOl** [comment]
@robodoo As you don't like r- and r\+ in the same command...

**Comment by KangOl** [comment]
@robodoo ... I do the r+ afterward..

**Comment by KangOl** [comment]
@robodoo retry and retry and retry

**Pull request closed without merging**
