### PR TITLE
[FIX] sale: fix test_pricelist_dates

### PR DESCRIPTION
**Pull request by Demesmaeker**
This time, for good

### CODE REVIEW

**Comment by Xavier-Do** [comment]
@robodoo r+

We should create a test_pricelist t-shirt

**Comment by Demesmaeker** [comment]
@Xavier-Do To go with ours Amazon t-shirt, makes sens too :laughing:

**Comment by Feyensv** [comment]
@robodoo r-
(to retarget the branch to 16.0)

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
