### PR TITLE
[IMP] mrp: add float_time widget on durations fields

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ryv-odoo** [comment]
Hello @sswapnesh ,
There is a conflict with the current version in master. There is a new fields in the view `duration_unit` which should have also the widget "float_time".
Thank you

**Comment by sswapnesh** [comment]
@ryv-odoo  Updated

**Comment by ryv-odoo** [comment]
Thank you @sswapnesh ,
LGTM
@robodoo r+

**Comment by ryv-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
