### PR TITLE
On module update or init always update module list

### PR DESCRIPTION
**Pull request by dreispt**
Follow up of #9133

### CODE REVIEW

**Comment by Yenthe666** [comment]
:+1: good idea!

**Comment by dreispt** [comment]
@xmo-odoo @odony Here is the PR for master, to update module list on CLI module install or upgrade.

**Comment by dreispt** [comment]
Ping!

**Comment by jholze** [comment]
:+1:

**Comment by dreispt** [comment]
Ping @odony @xmo-odoo 
I'm using this patch for so long, that I forgot it's not available in the official branches...

**Comment by dreispt** [comment]
Ping!

**Comment by dreispt** [comment]
Any chance we can get this, or equivalent feature (update module list from cmd without upgrading the world), landing on v11?

**Comment by pedrobaeza** [comment]
Yes, please!

**Comment by guewen** [comment]
> Any chance we can get this, or equivalent feature (update module list from cmd without upgrading the world), landing on v11?

That's the primary reason we use OCB for 10.0 which includes this patch.

**Comment by Yenthe666** [comment]
@xmo-odoo any love please?

**Comment by tde-banana-odoo** [comment]
@xmo-odoo share the love !

**Comment by mart-e** [comment]
This was old but actually still relevant for v11
Merged in saas-18 at 94e8d1072539cc8b200d4dcf70fb124f326bee18
Thanks

**Comment by dreispt** [comment]
@mart-e Had you merged it exactly one week ago, and it would be on the PRs birthday 😉

**Pull request closed without merging**
