### PR TITLE
Log SQL queries before executing them

### PR DESCRIPTION
**Pull request by clonedagain**
Description of the issue/feature this PR addresses:
The log of SQL queries have the wrong time (visible for particularly long-running queries, for example valuation with millions of stock moves).
When following the log (i.e. tail -f), if the server blocks on a querry we can only know the reason when the query is done.
If the query fails it's never logged.

Current behavior before PR:
Log query after executing

Desired behavior after PR is merged:
Log before executing
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by clonedagain** [comment]
@odony would you agree with this?

**Comment by odony** [comment]
Sounds good, thanks! We did not log the query execution time anyway, so there was no advantage in logging it after the fact.
However you'll want to fix your patch to log `query` instead of `self._obj.query`, otherwise you'll be logging the *previous* query (or `None`), which will certainly cause *more* confusion ;-)

**Comment by clonedagain** [comment]
OK I was wondering what the difference is, so now I know :)

**Comment by odony** [comment]
Thanks for the patch, just merged in master at 1a58e1085edfddde0c0be2b6d76cbf674b61fa4f :-)

**Pull request closed without merging**
