### PR TITLE
only run postinstall tests for updated modules

### LINKED ISSUE #9768: 9.0 unittests decorated with postinstall are run even if the module was not updated
case at hand:

I have a module for a customer which changes the ACL for sale.order. It also has some unittests.

if I run `odoo.py -i customer_module --stop-after-init && odoo.py -u customer_module --test-enable --stop-after-init` the tests of sale which are decorated with postinstall are run too, even if the sale module is not updated. And of course they fail which breaks my CI.

### PR DESCRIPTION
**Pull request by gurneyalex**
closes #9768

### CODE REVIEW

**Comment by gurneyalex** [comment]
@sle-odoo your opinion on this one would be welcome.

**Comment by komsas** [comment]
@sle-odoo, @mart-e would be nice if this be merged, it's always a pain to run tests for a specific addon.

**Comment by simahawk** [comment]
it works here. Any chance to get this merged? :)

**Comment by pedrobaeza** [comment]
:+1:

**Comment by gurneyalex** [comment]
8.0 version of this patch: #11378

**Comment by pedrobaeza** [comment]
@gurneyalex, as stated you should close this one.

**Pull request closed without merging**
