### PR TITLE
[IMP] l10n_in_pos: error on order from POS

### PR DESCRIPTION
**Pull request by khva-odoo**
Before PR:
---
If state is not set in the company,it gives error on order confirmation.

After PR:
---
If state is not set in the company, now it gives error when opening POS session.

task id: 3360161

### CODE REVIEW

**Review by jva-odoo — APPROVED** [review]

**Review by caburj — APPROVED** [review]
robodoo r+

**Comment by khva-odoo** [comment]
@caburj

**Comment by caburj** [comment]
robodoo r+

**Comment by caburj** [comment]
Kindly rebase so we can try again.

**Comment by khva-odoo** [comment]
> Kindly rebase so we can try again.

@caburj done, can you please retry.

**Comment by caburj** [comment]
robodoo r+

**Pull request closed without merging**
