### PR TITLE
Fix URL

### PR DESCRIPTION
**Pull request by Yenthe666**
URL from eitherpad to etherpad, was the wrong URL.

### CODE REVIEW

**Comment by Yenthe666** [comment]
@xmo-odoo can you quickly add this to Odoo? Just cosmetic and very easy to do for you. :)

**Comment by xmo-odoo** [comment]
Yeah but annoyingly this string is translated, I may need to fix all translations and get them imported back

/cc @odony

**Comment by odony** [comment]
@xmo-odoo I should do a translation re-sync anyway (to include new `l10n_eu_service` module), so I could do a quick in-place substitution of ietherpad.com in the PO[T] files.

**Comment by Yenthe666** [comment]
@odony why are those syncs done by hand and not automaticly? Sounds like an annoying work and I assume you need to do this pretty often to keep translations working when things change..

**Comment by xmo-odoo** [comment]
@odony I'll merge this and sed -i the PO/POT then

**Pull request closed without merging**
