### PR TITLE
[IMP] test_lint, *: eslint remove caughtErrorsIgnorePattern to no-unused-vars

### PR DESCRIPTION
**Pull request by jpp-odoo**
We removed the option that allowed the non-used argument on the catch
block (they musted have its name begining with '_').

Now, if the argument on the catch block is not needed, we can simply use
the optional catch binding.

### CODE REVIEW

**Comment by jpp-odoo** [comment]
@robodoo rebase-ff

**Review by aab-odoo — APPROVED** [review]
robodoo rebase-ff r+

**Comment by xmo-odoo** [comment]
Also this seems to include updates from an other PR?

**Comment by xmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
