### PR TITLE
[MERGE] hr_timesheet: fix employees in project overview

### PR DESCRIPTION
**Pull request by IT-Ideas**
This PR purpose is to improve the previous fix made [here](https://github.com/odoo/odoo/pull/67726) as its drawback is that it prevents using the filters.

This fix rather focus on only returning the expected employee_ids from _plan_get_employee_ids rather than using the context.

Related PR #67726

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
LGTM, thanks ! 🙂

**Review by simongoffin — APPROVED** [review]

**Comment by simongoffin** [comment]
robodoo delegate+

**Comment by IT-Ideas** [comment]
@robodoo merge r+

**Comment by IT-Ideas** [comment]
@robodoo rebase-ff

**Comment by simongoffin** [comment]
robodoo r+

**Pull request closed without merging**
