### PR TITLE
[ADD] web_tour: running tour through an url

### PR DESCRIPTION
**Pull request by bastien-ipb**
Now, a tour will be run if the parameter "tour" is
in the url's parameters. You can copy the url of a tour
in the tour modal by clicking on the fa-link, next to
the tour's name.

Task-ID: 4072309

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
@odoo/rd-security Hello, a line in a test does location.href = "....", Can we get an override ?

**Comment by kebeclibre** [comment]
robodoo delegate+

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: test

**Comment by bastien-ipb** [comment]
robodoo r+

**Pull request closed without merging**
