### PR TITLE
[FIX] web: re-introduce w-0 and h-0 utility classes

### PR DESCRIPTION
**Pull request by younn-o**
When updating bootstrap to bootstrap 5 with [1], the h-0 and w-0
extended utility classes were lost.

This commit adds them back, using the Utility API of Bootstrap described
here [2], and the $utilities-sizes from [3]. Therefore, the code
introduced in [4] is not needed anymore.

This commit fixes the footer "scroll to top" option of the website
builder.

[1]: https://github.com/odoo/odoo/commit/971e5a91aab9
[2]: https://getbootstrap.com/docs/5.0/utilities/api/
[3]: https://github.com/odoo/odoo/commit/e377a084174d
[4]: https://github.com/odoo/odoo/commit/da55072a6935

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
I guess we have to remove the `$sizes` variable definition I linked earlier + the code that uses it coming from `https://github.com/odoo/odoo/commit/da55072a693527de58cedb5357d8bff84ab5d99a` I guess (I see `responsive: true` I guess it means, the responsive version of those classes are generated without the need of the extra code I made?) ?

**Comment by younn-o** [comment]
@qsm-odoo As bootstrap is now exended via an Utility API described here: https://getbootstrap.com/docs/5.0/utilities/api/#enable-responsive, `responsive: true` generates the `w-xl-50, ....` variations, so it looks like this code is not needed anymore, I will remove it.

**Comment by younn-o** [comment]
@qsm-odoo This PR is ready for review

**Review by qsm-odoo — APPROVED** [review]
Push-forced to:
- Mention portal in apps list
- Indicate the h-0 and w-0 classes will now be available everywhere instead of just the frontend

@robodoo r+

**Pull request closed without merging**
