### PR TITLE
[FIX] hr_calendar: prevent error when opening calendar without timezone

### PR DESCRIPTION
**Pull request by reka-odoo**
When customer tries to open ```calendar``` without timezone,
a traceback will appear.

Steps to reproduce the error:
- Go to My profile > In timezone, Select empty timezone
- Install ```hr_calendar```
- Open ```Calendar```

Traceback:
```
AttributeError: 'bool' object has no attribute 'upper'
  File "odoo/http.py", line 2373, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1903, in _serve_db
    return self._transactioning(
  File "odoo/http.py", line 1966, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1933, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 2177, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 223, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 35, in call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 459, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
  File "addons/hr_calendar/models/res_partner.py", line 99, in get_working_hours_for_all_attendees
    return self._interval_to_business_hours(reduce(Intervals.__and__, schedule_by_partner.values()))
  File "addons/hr_calendar/models/res_partner.py", line 105, in _interval_to_business_hours
    "startTime":  interval[0].astimezone(timezone(self.env.user.tz)).strftime("%H:%M"),
  File "odoo/tools/_monkeypatches_pytz.py", line 129, in timezone
    return original_pytz_timezone(name)
  File "__init__.py", line 183, in timezone
    if zone.upper() == 'UTC':
```

https://github.com/odoo/odoo/blob/3345a0b61630ee1ac11045b09717167744265a24/addons/hr_calendar/models/res_partner.py#L105
When user has an empty timezone and tries to open the ```calendar``` app,
It will give the traceback at the above line.

sentry-5707574801

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by reka-odoo** [comment]
Hello @odoo/sentry_reviewers :wave: 
Please review this PR.
Thanks!

**Comment by Bertrand2** [comment]
Hello, is that issue still up to date?
I cannot manage to empty the timezone field on my profile, is there steps I can reproduce to remove the user's timezone?
Thanks!

**Comment by reka-odoo** [comment]
Hello @Bertrand2 :wave: 
here is the screencast: https://tinyurl.com/2bt77jo3
Thanks! :slightly_smiling_face:

**Review by Bertrand2 — COMMENTED** [review]
Ok thanks! Somehow on my system I don't have the opportunity to empty the field :thinking: I have no clue what could be causing that difference.
In any case LGTM, if possible could you add a small test?

**Review by Bertrand2 — APPROVED** [review]
Perfect! Thanks :)

**Comment by Bertrand2** [comment]
robodoo r+

**Pull request closed without merging**
