### PR TITLE
[doc] Add Odooexperts CLA

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Change the old CLA (Bas Solutions) to the new CLA (Odoo experts) & add myself into it.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hey @mart-e,

Would this be the good change? Changed the `.md` filename, changed the e-mails and added myself.
CC @ploegvde

**Comment by Yenthe666** [comment]
As requested by @ploegvde - removed Ruchir & updated the Github user for Erwin.

**Comment by ploegvde** [comment]
Is ok for me.

@Yenthe666 Welcome on board!!!!

**Comment by Yenthe666** [comment]
Thanks a lot @ploegvde 😄 🎉 
@mart-e perhaps I shouldn't remove Rugier but add an up to date?

**Comment by mart-e** [comment]
Rugier has never made a commit so not an issue to remove him.
Thanks, merged at 40998a4dedc !

**Comment by ploegvde** [comment]
@Yenthe666 There is stilll 1 time my old github account

Erwin van der Ploeg erwin@bas-solutions.nl https://github.com/erwin-bas-solutions

Can you change that also?

**Comment by Yenthe666** [comment]
@ploegvde the initial CLA is signed by that account though so I don't think it is fine to remove that.
@mart-e can you confirm if it is allowed or not?

**Pull request closed without merging**
