### PR TITLE
[IMP] Conditionally return nil/null from XML/JSON-RPC endpoints.

### PR DESCRIPTION
**Pull request by amh-mw**
**Description of the issue/feature this PR addresses:**

XML/JSON-RPC calls return False/false instead of None/null. This is a problem for statically typed languages, notably Swift (for iOS).

**Current behavior before PR:**

False is returned instead of None.

**Desired behavior after PR is merged:**

The developer can choose to:
- Receive nil instead of false by setting XML-RPC-Accept-Nil=1 in the HTTP headers.
- Receive null instead of false by calling /jsonrpc/2 instead of /jsonrpc.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amh-mw** [comment]
@rco-odoo Thank you for taking a look at my incorrect pull request https://github.com/odoo/odoo/pull/49901 against 13; I have recreated the patch against master.

**Comment by amh-mw** [comment]
It looks like this PR partially overlaps the "allow none" concept in #3989.

**Comment by Yenthe666** [comment]
Euh, I thought that the general idea was to enable `allow_none=True` in the Odoo config file if you wanted to manage this?

**Comment by amh-mw** [comment]
I totally agree! Unfortunately, Odoo.sh has no mechanism for me to manage the conf files and I had hoped not to add an additional configuration management tool like Ansible to our deployment chain.

**Comment by amh-mw** [comment]
After giving this some more thought, I don't think it is appropriate to push the allow_none setting down into configuration. It could put you in an untenable position where a legacy caller requires no nulls, but a new caller requires nulls. A better option would be to version the /jsonrpc and /xmlrpc endpoints again?

**Comment by amh-mw** [comment]
Per https://docs.python.org/3/library/xmlrpc.client.html

> If allow_none is true, the Python constant None will be translated into XML; the default behaviour is for None to raise a TypeError. This is a commonly-used extension to the XML-RPC specification, but isn’t supported by all clients and servers; see [http://ontosys.com/xml-rpc/extensions.php](https://web.archive.org/web/20130120074804/http://ontosys.com/xml-rpc/extensions.php) for a description.

This suggests that we must allow the client to specify whether they would like to use the allow_none extension.

**Comment by amh-mw** [comment]
Per https://www.jsonrpc.org/specification

> Since JSON-RPC utilizes JSON, it has the same type system (see http://www.json.org or RFC 4627). JSON can represent four primitive types (Strings, Numbers, Booleans, and Null) and two structured types (Objects and Arrays).

Since JSON-RPC expects nulls, I will break out a new /jsonrpc/2 endpoint that always returns nulls where appropriate.

**Comment by amh-mw** [comment]
I've reworked it a bit, adding a new `/jsonrpc/2` endpoint for the JSON-RPC behavior, and an `XML-RPC-Accept-Nil` header to enable the XML-RPC behavior.

**Comment by amh-mw** [comment]
My current approach of modifying context on the request environment is invalid; execute_cr instantiates a fresh environment:
https://github.com/odoo/odoo/blob/master/odoo/service/model.py#L154-L156

Any suggestions on where I should hang the allow_none switch instead?

**Comment by amh-mw** [comment]
Finally had a chance to circle back around to this. I've merged the context provided by the request into a copy of the api.Environment context and that seems to have gotten things working!

**Pull request closed without merging**
