### PR TITLE
[MERGE] forward port branch saas-11.4 up to 26da2e183bc

### PR DESCRIPTION
**Pull request by KangOl**

### CODE REVIEW

**Comment by KangOl** [comment]
robodoo rebase- review+ priority=0

**Comment by mreficent** [comment]
but runbot is super red :S

**Comment by KangOl** [comment]
That's why I created a PR and don't push directly.

**Comment by KangOl** [comment]
Sorry, @robodoo, you didn't do your job. I pushed directly.

**Pull request merged**
