### PR TITLE
[IMP] l10n_co: update latam identification type

### PR DESCRIPTION
**Pull request by nla-odoo**
- Update latam identification types

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@nla-odoo I am afraid we need to wait until the anexo is active @ren-odoo

**Comment by nla-odoo** [comment]
Hello @jco-odoo 

Yes, but we are heading towards the new improvements. so, in the final time, we don't need to do much work.
These are the improvement we will need in Anexo 1.8.

Thanks

**Comment by jco-odoo** [comment]
@nla-odoo I mean for merging, it is good we have it.

**Comment by nla-odoo** [comment]
@jco-odoo 

Okay got it.
Initially, the PR is created for previous deadlines.

**Pull request closed without merging**
