### PR TITLE
[FIX] core: compute editable field with a default should not recompute

### PR DESCRIPTION
**Pull request by rco-odoo**
Consider a model with a field F and a computed editable field G that
depends on F.  Assume we open a form view, and both F and G have a
default value.  The first onchange should return F and G with their
respective default values.  In other words, the field G should not be
recomputed even if its dependency F was assigned a default value.

The use-case that showed the issue is batch payments.  When adding a new
payment in the one2many field of a batch, the new payment should use the
batch's payment method by default.  The default value for the payment's
method is assigned by context on the one2many field in the view.  Before
this patch, the new payment's method was given by the computation of the
field, and its default value was ignored.

Side note: another test was fixed, but that's because the test was not
consistent with the way Odoo 14.0 manages defaults and onchanges.

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
We had to do an hack in _get_default_mailing_domain methods to support default keys in compute as it was not working as expected at that time (hence the test update). Maybe this code could be updated accordingly.

**Comment by rco-odoo** [comment]
@tde-banana-odoo should I completely remove the changes made in `_get_default_mailing_domain` in 1ec887b773581b6316902997fec94176bbae1ac0 ?

**Comment by tde-banana-odoo** [comment]
> @tde-banana-odoo should I completely remove the changes made in `_get_default_mailing_domain` in [1ec887b](https://github.com/odoo/odoo/commit/1ec887b773581b6316902997fec94176bbae1ac0) ?

I think what you did is correct. If I give a default domain, it should not be updated with blacklist part. If I want a blacklist based domain I have to give it myself. Moreover blacklist is already managed in sending process using SQL to optimize performances. This domain part is not necessarily useful. In short: LGTM.

**Review by Elkasitu — APPROVED** [review]
👍🏽

**Review by kbapt — APPROVED** [review]
LGTM

**Comment by rco-odoo** [comment]
Thanks for the reviews, guys! :+1:

**Comment by rco-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
