### PR TITLE
[FIX] l10n_de_*: datev codes

### PR DESCRIPTION
**Pull request by malb-odoo**
Change datev codes in l10n_de_skr03 and 04 for some lines and allow 4 digit codes.
Doc: https://apps.datev.de/help-center/documents/0907043

task-id: 2977383

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by malb-odoo** [comment]
Enterprise PR : https://github.com/odoo/enterprise/pull/31388

@tsb-odoo @tv-openbig @Yenthe666 

here is the fix for the issue  "https://github.com/odoo/odoo/issues/99426" is that ok for you ?

**Comment by tsb-odoo** [comment]
Hi @tv-openbig, can you please test the fix and provide feedback ? Have a great day.

**Review by epictete — APPROVED** [review]
LGTM :ok_hand:

**Comment by tv-openbig** [comment]
> Change datev codes in l10n_de_skr03 and 04 for some lines and allow 4 digit codes.
> 
OK, thanks.
> * Export: when a data code has a length less than 4, we add 0's to fulfill the 4 digit requirement.
> 

@malb-odoo @tsb-odoo @tv-openbig @Yenthe666
Is it possible to avoid filling up with "0" ? 
If the value in l10n_de_datev_code is for example "9" the exported value should be "9" instead of "0009".
In fact we may have codes with 1,2,3 or 4 digits. None of these values should be filled up.

@malb-odoo @tsb-odoo @tv-openbig @Yenthe666

Would you also allow to edit this field ?
It seems that v13, v14 hides that field from the tax view even if l10n_de_skr03 or l10n_de_skr04 is installed.
Obviously it is not the case in v15, however it is really a blocker in v13, v14 
it is important to be able to edit further taxes, beneath the four taxes with a pre-defined tax code.

**Comment by mncoon** [comment]
@malb-odoo @tsb-odoo @tv-openbig @Yenthe666 @tv-openbig 
As @tv-openbig said, it must be possible to have the field empty or filled with 1 - 4 digits. It does not happen to fill up with zeros to 4 digits. Everything else looks fine from my site.

**Comment by tsb-odoo** [comment]
@malb-odoo no useless zeros then. 

We misundertood the following sentence of the original issue [https://github.com/odoo/odoo/issues/99426] : 
_If you check that document you would see that in the meantime the field l10n_de_datev_code
should be 4-digits instead of 2-digits, f.e. to cover the One Stop Shop taxes (OSS)
for B2C business in the EU._

@tv-openbig I tested and in all stable versions, the field is editable. 
In V13, it's visible no matter the country, so it could bother users checking their taxes in non-german companies when one of the German CoA is installed. But that's it. I guess there's nothing to ddo about the views.

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
