### PR TITLE
[IMP] l10n_fi: Adding account + translation

### PR DESCRIPTION
**Pull request by malb-odoo**
Before this PR, a lot of account were missing from the finnish COA. The goal of this PR was to add those missing account following this spreadsheet: https://docs.google.com/spreadsheets/d/1hpQndK24UJ9efvl_Vyp5p-UczonIm_FxPnakf_Ugm68/edit#gid=1134177820

Also adding the according translations

Task: 3241121

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Levizar — APPROVED** [review]
@robodoo r+

**Comment by Levizar** [comment]
sounds like a csv comma issue

**Comment by malb-odoo** [comment]
> sounds like a csv comma issue

@Levizar Yes i didn't had time to correct it but it shouldn't take too much time

**Review by Levizar — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
