### PR TITLE
[FIX] iap_tools: allow odoo domain for enrichment

### PR DESCRIPTION
**Pull request by jmak-odoo**
Removed odoo domain from blacklist, so that emails from odoo.com can be used for enrichment for demo/testing purposes.

Task-3939876

### CODE REVIEW

**Review by lobaudoux — COMMENTED** [review]
It looks like this list was also used in the CRM app to detect duplicated leads (see [crm_lead.py](https://github.com/odoo/odoo/blob/15.0/addons/crm/models/crm_lead.py#L551)).
The related [failing test](https://github.com/odoo/odoo/blob/15.0/addons/crm/tests/test_crm_lead_duplicates.py) seem to be incorrect and will need to be fixed.

**Comment by tde-banana-odoo** [comment]
It was added to be sure we don't make useless requests each time someone encodes something from odoo.com . Maybe use example.com address, or check with IAP team to have a real demo endpoint so that we don't populate useless things.

**Comment by lobaudoux** [comment]
Hello @tde-banana-odoo

What kind of requests do you want to avoid with this? If it's only about the enrichment of the lead based on the email address, I don't think it is an issue to have a few requests for that.

Hello @cth-odoo , could we have your opinion on this?

**Comment by cth-odoo** [comment]
Hello @tde-banana-odoo 

Agree with @lobaudoux , we don't think it will explode the number of requests. On the opposite, during a demo, when you use your @odoo.com address, it is embarrassing when you did not get any results 😅

CC: @jmak-odoo

**Comment by tde-banana-odoo** [comment]
It is also used in CRM, notably to avoid considering all addresses from odoo as coming from the same provider (as gmail or stuff like that).

Concerning the IAP stuff, I am quite sure it was an internal request at that time, but actually I don't really care. To be honest I think demo should not depend on actual IAP calls and be completely mocked so that it is fast, reliable and independent from your internet connection but that's more an IAP thingy to do someday. We did that in social (see social_demo) that way you can always have deterministic demo. Probably something to do instead of adding calls to IAP in my opinion.

**Comment by tde-banana-odoo** [comment]
Also pay attention that "info@fleuriste.odoo.com" should not be populated with "odoo.com" information (don't remember all details of how it works), that's an important point to keep in mind.

**Comment by lobaudoux** [comment]
> It is also used in CRM, notably to avoid considering all addresses from odoo as coming from the same company (as gmail or stuff like that).

Then, I think we could do this instead:

```py
_MAIL_PROVIDERS = ['gmail.com', 'hotmail.com', ...]  # same as before, but without odoo.com
_MAIL_DOMAIN_BLACKLIST = _MAIL_PROVIDERS + ['odoo.com']
```
And we use `_MAIL_PROVIDERS` instead of `_MAIL_DOMAIN_BLACKLIST` in lead enrichment based on email.

> Also pay attention that "info@fleuriste.odoo.com" should not be populated with "odoo.com" information (don't remember all details of how it works), that's an important point to keep in mind.

I've just made a commit on IAP to make sure that this doesn't happen :+1:.

**Review by lobaudoux — APPROVED** [review]
LGTM, thanks

@robodoo r+

**Pull request closed without merging**
