### PR TITLE
[IMP] l10n_es: switch account.account.template creation in csv  …

### PR DESCRIPTION
**Pull request by hch-odoo**
task: https://www.odoo.com/web?debug#id=1909961&action=327&model=project.task&view_type=form&menu_id=4720
pad: https://pad.odoo.com/p/r.3bb795404d1e38ccc7cde9c4f6f3c9cd

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@hch-odoo we are going to propose some changes in "Spanish Chart of Accounts", so maybe you prefer that they are proposed directly to this PR. Is this going to be merged soon or is something to be outstanding for a while?

cc @oco-odoo

**Comment by tivisse** [comment]
@robodoo r+

**Comment by pedrobaeza** [comment]
@tivisse I asked something here that got unanswered. Now should I make the PR for both stable and master branches?

**Comment by tivisse** [comment]
Hi @pedrobaeza 

Sorry I didn't see that. This performance improvement is gonna be forwardported. 

So you still may target the 12.0 and adapt your code.

Thanks,

Yannick.

**Comment by pedrobaeza** [comment]
OK, I'll wait for that forward-port then to add the changes. Is it going to be done on v11 too (it's the first branch I have to target).

**Comment by tivisse** [comment]
It won't target the 11.0.

The goal was to speed up the trial base creation.

So I imagine that you have to make 2 PRs. Sorry about that.

**Comment by pedrobaeza** [comment]
OK, no problem while both will be accepted :wink: 

Who to ping on them?

**Comment by tivisse** [comment]
The accounting team, with qdp. ;)

**Pull request closed without merging**
