### PR TITLE
Use async connections for --log-db (ir_logging) to avoid deadlocks

### PR DESCRIPTION
**Pull request by xmo-odoo**
When using log-db, especially to the same database being worked on, it's possible to get dealocked: the logging call is synchronous but creates a new transaction, which might be waiting for some alteration of the ir_logging table to complete, alteration which won't complete because it's not waiting on the logging call.

Work around this issue by dispatching the ir_logging insert asynchronously and not waiting for its completion. This should avoid the extra waiting & some of the loss (as a timeout would cancel the
insertion).

### CODE REVIEW

**Comment by xmo-odoo** [comment]
Well damn, according to some person on IRC if the connection is closed the server can abort the transaction at any time, nothing is completely guaranteed until the first successful result.

**Comment by odony** [comment]
Hmm, can we confirm that with some testing evidence? What if we include a dummy `pg_sleep(1000)` with each INSERT, and we check if the INSERT really takes place if we close the connection immediately without waiting 1s?

**Comment by xmo-odoo** [comment]
I'll check it. Either way we can still use the same async method with a wait / timeout (on the python side) and bail if the timeout is hit, that way worst case it's similar to having a lock/statement timeout, but if postgres ends up executing the query anyway we avoid losing it (unlike the pg-level timeout which should blow up the query itself as soon as the timeout is hit).

**Comment by amigrave** [comment]
@odony  By the way, I was expecting this to be a fix rather than improvement. If a working solution is found and considering it "only touches" the postgresql logging handler, will it be backported ?

**Comment by xmo-odoo** [comment]
According to pgjdbc/pgjdbc#1461 even if the server can notice the connection was dropped and cancel the execution, there's a very high chance it'll keep going if there's no postgres-level timeout.

Also doing some testing things seem to work fine:
```
> python test.py; for i in 0 10 20 60 60; do sleep $i; date '+%Y-%m-%d %H:%M:%S'; psql odoo -c 'select * from foo'; done                                                                 ~/projects/tiny/odoo
2019-05-31 09:30:13
 id |            instant            | value |           submitted           
----+-------------------------------+-------+-------------------------------
 71 | 2019-05-31 09:29:02.273216+02 |     2 | 2019-05-31 09:29:02.273067+02
(1 row)

Time: 1.833 ms
2019-05-31 09:30:23
 id |            instant            | value |           submitted           
----+-------------------------------+-------+-------------------------------
 71 | 2019-05-31 09:29:02.273216+02 |     2 | 2019-05-31 09:29:02.273067+02
(1 row)

Time: 1.411 ms
2019-05-31 09:30:43
 id |            instant            | value |           submitted           
----+-------------------------------+-------+-------------------------------
 71 | 2019-05-31 09:29:02.273216+02 |     2 | 2019-05-31 09:29:02.273067+02
(1 row)

Time: 1.542 ms
2019-05-31 09:31:43
 id |            instant            | value |           submitted           
----+-------------------------------+-------+-------------------------------
 71 | 2019-05-31 09:29:02.273216+02 |     2 | 2019-05-31 09:29:02.273067+02
 72 | 2019-05-31 09:30:02.285638+02 |     1 | 2019-05-31 09:30:02.2855+02
 73 | 2019-05-31 09:30:12.298052+02 |     0 | 2019-05-31 09:30:12.297941+02
 74 | 2019-05-31 09:30:13.310805+02 |    -1 | 2019-05-31 09:30:13.310671+02
 75 | 2019-05-31 09:30:13.418292+02 |    -2 | 2019-05-31 09:30:13.418136+02
 76 | 2019-05-31 09:30:13.434773+02 |    -3 | 2019-05-31 09:30:13.434643+02
 77 | 2019-05-31 09:30:13.441981+02 |    -4 | 2019-05-31 09:30:13.441878+02
(7 rows)

Time: 1.361 ms
2019-05-31 09:32:43
 id |            instant            | value |           submitted           
----+-------------------------------+-------+-------------------------------
 71 | 2019-05-31 09:29:02.273216+02 |     2 | 2019-05-31 09:29:02.273067+02
 72 | 2019-05-31 09:30:02.285638+02 |     1 | 2019-05-31 09:30:02.2855+02
 73 | 2019-05-31 09:30:12.298052+02 |     0 | 2019-05-31 09:30:12.297941+02
 74 | 2019-05-31 09:30:13.310805+02 |    -1 | 2019-05-31 09:30:13.310671+02
 75 | 2019-05-31 09:30:13.418292+02 |    -2 | 2019-05-31 09:30:13.418136+02
 76 | 2019-05-31 09:30:13.434773+02 |    -3 | 2019-05-31 09:30:13.434643+02
 77 | 2019-05-31 09:30:13.441981+02 |    -4 | 2019-05-31 09:30:13.441878+02
(7 rows)

Time: 1.434 ms
```
The script opens a connection (async), executes an insert with a `pg_sleep(60)`, waits for 10**value for the completion notification then closes the connection: https://gist.github.com/xmo-odoo/b09661f2cc9a46eccadba30a1200205d

It still works fine (though with significantly increased wait obviously) using `pg_sleep(1000)` instead.

**Comment by xmo-odoo** [comment]
Still looking into how to run the test script using psycopg2 2.5~2.6 (given I can't run it using the postgres on my machine), but there's already an issue with 2.7:
```
py27-psycopg27 runtests: PYTHONHASHSEED='1193872952'
py27-psycopg27 runtests: commands[0] | python test.py
running script
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    wait(cr.connection, 10**-i)
psycopg2.ProgrammingError: close cannot be used while an asynchronous query is underway

```

**Comment by odony** [comment]
Could we check why it actually deadlocks during creation/update if we move ir_logging creation in base.sql? (Possibly commit after base.sql)

**Pull request closed without merging**
