### PR TITLE
[IMP] account: forbid making a 'bank & cash' account reconcilable

### PR DESCRIPTION
**Pull request by oco-odoo**
Making a bank account reconcilable is a very common mistake, and leads to confusing and useless data (the move lines made on this account) to be displayed in the reconciliation widget. With this, we make sure the user cannot make this mistake anymore.

Task: https://www.odoo.com/web#id=1884366&action=333&active_id=967&model=project.task&view_type=form&menu_id=4720

### CODE REVIEW

**Comment by gustavovalverde** [comment]
@oco-odoo @qdp-odoo is this documented somewhere? I actually thought this accounts should have been set to reconcile = True. If not, then which ones should and why?

Also, if this is the case then all l10n_XX CoA with a wrong reconcilable account based on their `internal_type ` should be fixed before v12.

**Comment by oco-odoo** [comment]
@gustavovalverde Actually, we decided to do this because several customers had made this configuration mistake in their db, and were hence facing weird behavior in the reconciliation widget. Indeed, having a bank & cash account reconcilable means that when you make a payment on this account, both the account.move.line generated by this payment will appear in the reconciliation widget, instead of the just the one made on the receivable or payable account, which would be the expected behavior. Do we agree on this ? If not, why ?

Also, thanks for mentioning the l10n_* modules, I checked, and indeed l10n_cr and l10n_co needed some fix on that side. I made another commit with that.

**Comment by gustavovalverde** [comment]
Yes, we do agree on that. That's even happening to me with the reconciliation widget, I was going to make an issue for that.

Just to be clear then. Aside from accounts payable and accounts receivable, which account types should be reconcilable?

**Comment by qdp-odoo** [comment]
clearing accounts, mostly ... and I think that's all

**Comment by gustavovalverde** [comment]
I think it would be helpful to just allow that functionality to clearing accounts then. If that's the right use-case, why allow others?

**Comment by qdp-odoo** [comment]
well there's no 'clearing' account type. it's just account with type 'other' that have the reconcile flag to True

**Pull request merged**
