### PR TITLE
[FIX] web: avoid traceback on pivot view

### PR DESCRIPTION
**Pull request by agr-odoo**
Accounting->Reporting->Invoice Analysis
Open Pivot view
Click on 'Flip Axis'
Remove field from rows. Add field 'Sales Team'
Add filter Invoice Date>Q2
Remove field from rows.

Traceback will occur

opw-2511057

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@nle-odoo

**Review by nle-odoo — COMMENTED** [review]
the case seems very complicated

at the step "Add filter Invoice Date>Q2" the search view is reapplied and automatically the column group by become the original one (group by invoice date) which is expected (because the group by of the search view/action, override those selected manually in the pivot view).

 It seems to me that there must be an inconsistency somewhere (something not updated or not cleared) and so that this inconsistency should be fixed instead of ignoring it, but I'm not sure where or how =/



ps: not too long ago I did this change: https://github.com/odoo/odoo/commit/7cf8f6f40e5769d2f22620ac425208c4ad9ae80b#diff-2926b04bd3df778f8a213d46036a34213cbc0915d68330d343f648bb313f207e  since it is touching closing of groups, it might be worth to check with or without the fix

**Comment by agr-odoo** [comment]
After looking into this a bit more in depth it seems there is a reference issue between `this.data.groupedBy` ,`this.data.rowGroupBys` and `this.data.colGroupBys`

At step 6 *Remove field from rows*, just before the traceback, the removal of the group is issued
https://github.com/odoo/odoo/blob/387c7abd2b4e82ba6078b867cc36b2b865302f7b/addons/web/static/src/js/views/pivot/pivot_model.js#L331-L343
variable `groupBys` is used to select the correct group to close
https://github.com/odoo/odoo/blob/387c7abd2b4e82ba6078b867cc36b2b865302f7b/addons/web/static/src/js/views/pivot/pivot_model.js#L370
but it will remove the grouping field for both `this.data.rowGroupBys` and `this.data.colGroupBys`

Unfortunately I've not been able to pin point the exact spot in which the reference issue occur but I guess it's partially due to the flip operations
https://github.com/odoo/odoo/blob/387c7abd2b4e82ba6078b867cc36b2b865302f7b/addons/web/static/src/js/views/pivot/pivot_model.js#L492-L498

I've updated the PR by adding a `splice` when loading the widget to avoid using the same reference and it seems to be working at least for this use case

**Comment by agr-odoo** [comment]
@nle-odoo

**Comment by nle-odoo** [comment]
your fix reminds me of https://github.com/odoo/odoo/commit/b8d4fe6d386768a9b1b638358bc95a4a7575e3f9 but that doesn't seem related

so if I understand the issue in the flip we will exchange row and columns, and so we will have the same reference for both. in this case your fix looks good (or the same `slice()` at the right location  in `flip`) but I'm a little lost in reference and what happen to them (in b8d4fe6d386768a9b1b638358bc95a4a7575e3f9 I had an issue with reference that now were different)

**Comment by Polymorphe57** [comment]
I haved checked your fix and the change in __load is not enough. The same sort of problem can happen in different ways.

Actually what happens is this (in your situation):

- No groupby is active in the control panel so the same actionContext.group_by is found in the search query each time we select/unselect a filter (see line 1269 in control_panel_model_extension).
- Both __load and __reload equalize  this.data.rowGroupBys to  actionContext.group_by: in __load and __reload, one finds
```js
this.data.rowGroupBys = !_.isEmpty(this.data.groupedBy) ? this.data.groupedBy: this.initialRowGroupBys; (*)
```
where this.data.groupedBy is set to be actionContext.group_by before (*).

- Normaly we should have this.data.rowGroupBys !== this.data.colGroupBys
but after a flip and a update we find this.data.rowGroupBys ===  (this.data.groupedBy  === ) actionContext.group_by === this.data.colGroupBys. So that  when we close a group we remove a group by from both this.data.rowGroupBys and this.data.colGroupBys. That brings a problem when the table is generated.

The problem can happen with this.initialRowGroupBys for a similar reason.

So there are at least three situations where the problem can happen:

1) (with an actionContext.group_by) Flip --> select a filter for which the pivot has content (let us say Invoices) --> close row header --> traceback

2) (with an actionContext.group_by) Select Invoices --> flip --> unselect Invoices --> close row header --> traceback

3) (without an actionContext.group_by) Close col header --> flip --> select Invoices --> close row header --> traceback

Your fix solve the first problem but not the others.

I would suggest

- keep the equality this.data.groupedBy === this.data.rowGroupBys (we might need it)
- avoid to equalize this.data.rowGroupBys with arrays that can stay the same in time.
- add three tests for the three situations above.

**Comment by agr-odoo** [comment]
@Polymorphe57 
Hi, sorry for the delay
Thank you for the thoughtful analysis. I've applied the same fix on a different line following your suggestions (not sure if that's what you meant) and I added 3 tests for the different cases

**Comment by Polymorphe57** [comment]
@agr-odoo I have reworked your commit. Is it good for you?

**Review by nle-odoo — APPROVED** [review]
looks good to me and nice to have it test

**Comment by agr-odoo** [comment]
@Polymorphe57 
Looks good also for me, thank you for the extended tests

**Comment by Polymorphe57** [comment]
robodoo r+

**Comment by Polymorphe57** [comment]
@agr-odoo The forward port is done. This closes the story.

**Comment by agr-odoo** [comment]
> @agr-odoo The forward port is done. This closes the story.

I see, thank you for the help

**Pull request closed without merging**
