### PR TITLE
[IMP] extend minimal chart of account on l10n_ch

### PR DESCRIPTION
**Pull request by vrenaville**
Hello,
One of our customer report that some account are missing on the minimal chart of account.

Kind regards,

Vincent
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fclementic2c** [comment]
:+1:

**Comment by fclementic2c** [comment]
@qdp-odoo Hello Quentin, we realized that the minimal swiss chart of account is ...well too 'minimal)'. So we want to extend it a bit. Does this kind of PR has any chance in Odoo9 ? otherwise, let's not loosing time and we do a module.  
What about master branch ?
Thanks

**Comment by fclementic2c** [comment]
any chance to have this merged ?
Please tell us otherwise we do an module 
thanks

**Comment by Yenthe666** [comment]
@qdp-odoo can you give some feedback / input?

**Comment by qdp-odoo** [comment]
yep, done at 	c9b270c

thanks for the contribution dudes

**Comment by treviser** [comment]
@vrenaville @fclementic2c @qdp-odoo 
I'm not sure about the procedure here. The biggest association for accounting in Switzerland (www.veb.ch) does publish 2 official versions of a standard chart of accounts for SME's: the official school version and the official standard version. The school version is a good base for small enterprises, the standard version is quite comprehensive and too big for small enterprises. The changes committed here are a mixture between those versions and are according to my understanding somehow biased. 
IMHO we should stick with the offical versions, in this case with the school version because it is easier to amend the chart of accounts than to delete accounts or otherwise we should offer both official versions separately.
However because of the importance of this matter I would prefer a broader discussion before committing it to the core.

**Pull request closed without merging**
