### PR TITLE
[IMP] project: migrate project_calendar to wowl2

### PR DESCRIPTION
**Pull request by Williambraecky**

### CODE REVIEW

**Comment by Williambraecky** [comment]
NOTE: this PR depends on https://github.com/odoo/odoo/pull/101203

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work! 🤩

**Review by aab-odoo — APPROVED** [review]
ok for the web part.

Thanks for your contribution :-)

**Comment by xavierbol** [comment]
Great, thanks again for your work! 😘 

robodoo r+

**Comment by xavierbol** [comment]
robodoo rebase-ff

**Pull request closed without merging**
