### PR TITLE
[FIX] web: Make datetimepicker configurable in datetime fields

### PR DESCRIPTION
**Pull request by yajo**
This completes https://github.com/odoo/odoo/pull/25044, I wrongly assumed the method was being inherited as used as is by the child class.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa @ged-odoo @tde-banana-odoo

### CODE REVIEW

**Comment by luisg123v** [comment]
What do you think about replacing datefield by datetimefield [here](https://github.com/odoo/odoo/commit/71334b13bd31c7f5a0c1704584b28274785f95e3#diff-2f7fd465e73813c2f78c1cddbc12aff8R1351)?

**Comment by Yajo** [comment]
Good idea, done.

**Comment by pedrobaeza** [comment]
@tde-banana-odoo can you please check this complementary PR to the one already merged?

**Comment by pedrobaeza** [comment]
@tde-banana-odoo can you please check so that we can complete the option?

**Comment by thomaspaulb** [comment]
@ged-odoo

**Comment by ged-odoo** [comment]
@adr-odoo @Polymorphe57 hey guys. Just in case, if you have a minute (unlikely I know), could you have a look at this one? You can ask Steve to add a test, and squash the 2 commits.

**Comment by Yajo** [comment]
Fixed in https://github.com/odoo/odoo/pull/27541

**Pull request closed without merging**
