### PR TITLE
[FIX] stock: recompute state independently from removed stock move lines

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
In case there was no move line deleted we should recompute anyway the state in case it went inconsistent for any other reason.

If a ```stock.move``` has a wrong state it will have consequences for the whole process, so we must guarantee consistency which we do by doing recomputation on the move itself after unreserving.

**Current behavior before PR:**
Dead lock for moves which were assigned but had no ```stock.move.line``` aligned.

**Desired behavior after PR is merged:**
Make it impossible that such a dead lock is blocking

@sle-odoo
Please take this also into consideration as it does not harm anyone...it just is removing the possibilities Murphy is ready to jump on...be sure there will be a use case in Odoo standard at some point as Murphy is never sleeping and no code for entry points can be water-proof and guard enough to stop the beast ;-)

OPW-802056

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@amoyaux
Actually this can be for you as you did the last change based on my feedback and this is more or less a follow up for consistency.

**Comment by sle-odoo** [comment]
hi,

i don't like it because in a normal situation _compute_state will be called twice on every unreservation (it is called during the move line's unlink). isn't the real bug that you have an assigned or partially assigned move without any move line?

**Comment by wtaferner** [comment]
@sle-odoo 
We can blame each other for producing inconsistencies or try to close the possibilities to actually happen at all. I think we could filter out the moves where we actually have ```stock.move.line``` to unlink which will trigger it correctly...but still if there is a wrong state for whatever reason you are stuck.

Actually I like the idea of filtering out the ones from mapped move lines which will call correctly the recompute...

**Comment by sle-odoo** [comment]
I'm really not sure this is the right way to deal with this issue. If there are inconsistencies in a move (partially assigned/assigned without any move line), reseting its state in the do_unreserve is just shoving stuff under the carpet, furthermore it'll break in another usecases. I believe we have to fix the root cause.

> We can blame each other for producing inconsistencies

i don't blame you :) there are bugs in the stock module. let's fix the one causing the inconsistencies.

**Comment by wtaferner** [comment]
Well, you want to search for a root cause which is maybe not there yet as it might be happening for customization reasons...

I think that you should deal with different point of views and consistency to make little methods water proof. This is why I am doing this effort at all. And out of experience I am pretty sure that you guys are stumbling across such a situation anyway in the future, so better keep this clean and safe even if the inconsistency can not be nailed to a yet found Odoo standard use case. 

And if you want to find a situation later to not shove it under the carpet, we can write a logger warning (I miss them a lot in Odoo Standard Business Parts) to find the root cause any time later if finding such warnings in the log, but it is important to cover all possibilities to not get stuck in a standard use case which is limited by default. 
And you guys are having a lot of SaaS customers and logs where you can analyze the logs easily in your standard instances and I will see the warnings too at any point in the future and I can fix eventually a root cause in my customization...anyway, it is better both of us have the information and a always consistent state instead of discussions based on incomplete covered ways a flow can take and produce inconsistencies.

Let me know if we should take the warning messages way to get these little fixes into place or just merge them if there is no contradiction based on the official flows and use cases.

Example:
```python

        if missed_moves:
            _logger.warning('Reserved moves without move lines found -> Recompute state...')
            missed_moves._recompute_state()
```

**Comment by wtaferner** [comment]
@sle-odoo 
Uhh, it seems to happen somehow even in core as suddenly a state is incorrect and I was only recomputing states of missed moves and a state should be secure all the time ;-) Maybe it is the way to go and leaking different type of flaws hidden yet.

**Comment by sle-odoo** [comment]
> Well, you want to search for a root cause which is maybe not there yet as it might be happening for customization reasons...

> Uhh, it seems to happen somehow even in core as suddenly a state is incorrect and I was only recomputing states of missed moves

so let's wait, maybe there's a real issue in the standard code :) but if you find one, this patch is wrong: the root cause has to be fixed and that's not what your patch is doing. Here you have a reserved move without move line, which is clearly against one of the concept of the standard addon, so standard method should not "fix them". In my opinion it won't bring anything to standard code, make it more complex and could hide real standard bugs. Same comment with the other pr.

**Comment by sle-odoo** [comment]
also, maybe your patch should check that missed moves are partially_available or assigned? if i unreserve an unreserved move, it should stay in confirmed/waiting and it is expected

**Comment by wtaferner** [comment]
Well, I guess we have two different opinions on how to secure code :-)

Anyway, the first question is...why does anyone try to unreserve an unreserved move in the first place?
And the second thought would be: why does the recompute state does not always compute the correct state independently? :-)

**Comment by sle-odoo** [comment]
> why does anyone try to unreserve an unreserved move in the first place

maybe a picking with one reserved move and one not, then the user clicks on unreserve on the picking and _do_unreserve is called on every move

>  does the recompute state does not always compute the correct state independently

in which case is it wrongly recomputed?

**Comment by wtaferner** [comment]
So, the picking should filter for the correct state first and even if it is not the recompute state should make sure it does not give a wrong state anyway :-)

Of course again we can discuss if we need the missed moves in the ```_do_unreserve``` but honestly these little checks are making the difference IMHO between easily destroy-able and resistant code and we are far from complexity ;-)

**Comment by sle-odoo** [comment]
> the picking should filter for the correct state first

yeah why not, it won't make a significant difference anyway since no work is done on unassigned move

> the recompute state should make sure it does not give a wrong state

of course, which case is failing?

**Comment by wtaferner** [comment]
> of course, which case is failing?

http://runbot.odoo.com/runbot/build/289368

**Comment by sle-odoo** [comment]
you did not read my comment though

> also, maybe your patch should check that missed moves are partially_available or assigned? if i unreserve an unreserved move, it should stay in confirmed/waiting and it is expected

here it's all red because in self you have unreserved move without any move lines, because picking does not filter out unreserved move before calling do_unreserve

i ran it locally with missed_moves.filtered(lambda m: m.state in ['assigned', 'partially_available']) and nothing raised

**Comment by wtaferner** [comment]
Ok, won't change anything b/c it won't be merged and the vectors are very small to inherit and change things for own customization. 
As said, IMHO this should be checked inside of the method which is producing the issue later...like the missed moves should be recomputed and so on...
Also the pickings should do the filtering before entering the ```_do_unreserve```, but this is all not happening as the code is written like it is and I do not work against concepts to be clear as you raised it...

I am just testing it from every angle and fix these angles you guys did not take a look at which is ok, but ignoring the other angles after opening the point of view is a bit selfish and foolish to express my disappointment for the mini changes you argue about instead of just merging them...they do not harm but help to improve the standard code or fix issues and possible inconsistencies others have in the end.

**Comment by wtaferner** [comment]
I did your filter as it is again more precise which I do prefer even if it is maybe not merged in the end ;-)
Failed test should be fixed with https://github.com/odoo/odoo/pull/21946/commits/3ffd3db012cdc7252b798d0bb4cf193a01facd32

**Pull request closed without merging**
