### PR TITLE
[IMP] *: app icons

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Since the introduction of Milk, the app icons have been updated.
But some of these icons were not replaced in the list of apps in Community.
The first commit fixes this issue.

Also, using the svg format creates a lack of anti-aliasing on the edges of the
shapes, which makes the new icons look bad.
Since the png size has been reduced, we can afford to use the png format
to have the best possible quality without having a lack of performance.
The second commit replaces svg icon with png.

task-3326633
Part of task-3326263

Requires: 
- https://github.com/odoo/enterprise/pull/41117

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It's a pity to not use SVG by default... Do you have some screenshots of how such aliasing effect was using SVG?

**Comment by Brieuc-brd** [comment]
Hi @pedrobaeza,
This issue is associated with certain browsers and operating systems.
As you can see, the png format offers a better rendering and since we have to add the png version of icons to the bundle anyway, we can seize this opportunity to achieve optimal quality.

Frame 1

**Comment by pedrobaeza** [comment]
Yeah, I see... Thanks for answering. Which browsers are affected? The main advantages of using SVG that I see are:

- Unique source. You don't have to maintain both SVG and PNG. Not sure why you say you need to include it anyway.
- Take advantage of GPU accelerated render pipelines. Browsers are incorporating this option. Rasterizing a bitmap, although is very optimized nowadays, at the end requires to process whole image.
- Scalability. You can modify icons size in your layout without worrying about resizing your images.

So that's why I would prefer to keep SVGs. Maybe is a browser configuration that renders them so ugly for any reason?

**Comment by Brieuc-brd** [comment]
Most browsers are affected by this issue. We sincerely appreciate your feedback as we seek the optimal solution to get the best possible rendering without compromising performance. Please be assured that we will take your feedback into account :).

**Comment by pedrobaeza** [comment]
Thank you very much for your kindness :)

Just adding my 2 cents, as I have been one of the promoters of SVG since the beginning: #26635 

Let me know any advance.

**Comment by Brieuc-brd** [comment]
Hello @stefanorigano 👋 
Could you check this PR and tell me what you think ?

**Comment by stefanorigano** [comment]
@Brieuc-brd , LGTM... both community and enterprise.
You can ping [@]pparidans when runbot is confirmed green ;)

**Comment by Brieuc-brd** [comment]
Hello @pparidans 👋 
These PRs (Community & Enterprise)  are ready for review, could you take a look ? :)
Thanks !

**Pull request closed without merging**
