### PR TITLE
[FIX] hr: Fix wrong super call

### PR DESCRIPTION
**Pull request by LucasLefevre**
super.message_post in _message_log is wrong.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by LucasLefevre** [comment]
@tivisse

**Comment by tivisse** [comment]
@robodoo r+

**Comment by LucasLefevre** [comment]
Still not merged.
@tivisse can you @robodoo retry ? Thanks

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo retry

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
