### PR TITLE
[IMP] Perf issue when 50k opportunities are assigned to the same user.

### PR DESCRIPTION
**Pull request by nseinlet**
Even if it's not a standard case, this query make the dashboard displayed in less than 1 second instead of 50.

Description of the issue/feature this PR addresses:
the sales dashboard takes more than 50s to display when 50k issues are assigned to the same user.

Current behavior before PR:

Desired behavior after PR is merged:
Sale dashboard is faster to display

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hooray, vert nice. It would be nice if those tests where done on other models with 50K records too. I can give you plenty of these cases.

**Comment by nseinlet** [comment]
@Yenthe666 It's not for the case the model contains 50k records. It's for the case when you assign 50k leads to the same user, which is not common. 50k leads is a far more common use case.

**Comment by Yenthe666** [comment]
@nseinlet agreed. There are more cases like these though, such as making many recurring Google calendar items (which become virtual records). In this case loading the forms also takes 30 - 60 seconds. Anyway, sorry for me going off topic!

**Review by odony — APPROVED** [review]
Thanks for fixing the typo and the NULL cases.
I only have minor remarks left (forgot to mention them earlier, sorry), and the rest looks good to me ;-)
I don't mind the direct SQL, it's kind of customary for statistics/reports.

**Comment by Yenthe666** [comment]
@nseinlet what happend to this PR? Will it still be handled before V11?

**Comment by rdeodoo** [comment]
> Will it still be handled before V11?

I don't think so :yum:

**Comment by Yenthe666** [comment]
😂 Correct it to V13 and then just maybe.

**Comment by yelizariev** [comment]
Could be closed
It's v10 and updated method is deleted in newer versions https://github.com/odoo/odoo/pull/42015/commits/877711b357c5de9c9c4827e92fdbbc94cae673fe

**Pull request closed without merging**
