### PR TITLE
[IMP] l10n_pe: Add List of Peruvian Banks

### PR DESCRIPTION
**Pull request by desdelinux**
Provides data on Peruvian Banks extracted from the Central Reserve Bank of Peru https://www.bcrp.gob.pe/sitios-de-interes/entidades-financieras.html

Enterprise PR: https://github.com/odoo/enterprise/pull/38293

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by desdelinux** [comment]
Hello @vbe-odoo @jco-odoo 

We move this to master, as indicated here https://github.com/odoo/odoo/pull/74586

**Comment by ren-odoo** [comment]
Thank you @desdelinux 

I tested and it's working correctly. 

cc. @vbe-odoo @fvz-odoo

**Comment by jco-odoo** [comment]
rebase + could be done in csv

**Comment by Levizar** [comment]
@robodoo r+

**Review by Levizar — APPROVED** [review]

**Comment by desdelinux** [comment]
> @desdelinux @Levizar linked pull request(s) [odoo/enterprise#38293](https://github.com/odoo/enterprise/pull/38293) not ready. Linked PRs are not staged until all of them are ready.

done @Levizar

**Comment by Levizar** [comment]
@robodoo r+

**Pull request closed without merging**
