### PR TITLE
[Fix]hw_proxy:P3 encoding issues

### LINKED ISSUE #24105: [11.0] Internal Server Error on /hw_proxy/status page
Impacted versions: 11.0

Steps to reproduce: Install Hardware Proxy module --> open  `host/hw_proxy/status`

Current behavior: Internal Server Error

```
File "/home/swapnesh/Workspace/11_odoo/addons/hw_proxy/controllers/main.py", line 103, in status_http
    devices = subprocess.check_output("lsusb").split('\n')
TypeError: a bytes-like object is required, not 'str'

```
Expected behavior:

Video/Screenshot link (optional):

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses:  See Issue #24105 for More detail

Current behavior before PR:

Desired behavior after PR is merged:

Closes #24105

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e can you check this one please?

**Comment by mart-e** [comment]
@sswapnesh please do not open an issue and a pull request. If you are going to make a patch, just make a pull request, easier to actually track the bug.

> Steps to reproduce: Install Hardware Proxy module

Well, actually that is the first problem. This module is not intended to be installed on an odoo server.
I believe it is still the code done for 8.0 database-less server that will run on a posbox, build using the posbox tools:
https://github.com/odoo/odoo/tree/8.0/addons/point_of_sale/tools/posbox

Due to stable policy, c71ce46b0eb3509b6805421915a8652bafd3bbbc was made in master but is valid, already in 9.0.
I leave this one open as we will migrate it one day and it may be useful but we do not consider it a priority as a 11 PoS can communicate with a 8.0 posbox without any issue.

Also, it seems you are doing more than changing the encoding of the code.
Please detail all your changes or, even better, make one commit per fix to keep it clean.

**Comment by sswapnesh** [comment]
@mart-e I was not sure about PR at the time of Posting Issue, You can close the Issue.
I would suggest to forward port from 10 to 11 and do changes/Improvement in that one if needed.

**Comment by sswapnesh** [comment]
Will be managed in #25711

**Pull request closed without merging**
