### PR TITLE
[FIX] web_editor: save document layout with tabs in different browsers

### PR DESCRIPTION
**Pull request by Mtaylorr**
Issue:
======
If you have some tabs in a html_field, opening  with a different browser
may cause an issue when saving the document layout.

Steps to reproduce the issue:
=============================
- Open with firefox
- Go to settings , document layout
- Added some `tab` in the footer or any html field
- save
- Open with chrome
- Go to settings , document layout
- click save without doing anything
- error

Origin of the issue:
====================
When calling sanitize in the constructor, the tabs size doesn't change
because we didn't add the class `odoo-editor-editable` which doesn't
make the `editable` dirty since no changes has been made. When calling
save, `cleanForSave` will be called with a clone of the `editable` so in
sanitize it won't matter since the element is not connected to the dom
so again no changes and the edtior still no dirty, after that ,
`onWillUpdateProps` of  `Wysiwyg` will be called and we will set the
value of the editor by the new value which will call `resetContent` of
`odooEditor` and it will sanitize the editable but this time it has the
class `odoo-editor-editable` so the finally the sizes of the tabs will
be changed and the editable will become dirty. Now `onWillUnmount` in
`html_field` will be called and since the field is dirty it will commit
changes as a normal save , but a traceback will occur since the
component is already destroyed.

Solution:
=========
Add the class `odoo-edtior-editable` before the call to sanitize to mark
the field as dirty from the start and will be updated with the new sizes
of tabs on the first commit and not in the commit of `onWillUnmount`.

opw-3742423

### CODE REVIEW

**Comment by Mtaylorr** [comment]
@dmo-odoo can you take a look at this when you have time ? Thanks

**Comment by dmo-odoo** [comment]
Isn't that the issue for which we said we should round the values so that there is no difference between browsers anymore?

**Comment by Mtaylorr** [comment]
> Isn't that the issue for which we said we should round the values so that there is no difference between browsers anymore?

Indeed, but even with that the problem still persists if some of the saved fields already have `tab` in them, when we open them and save again it will use another size of tab (the rounded one).

**Comment by Mtaylorr** [comment]
@dmo-odoo  , I updated the fix with a simpler one here and it solves the problem, let me know what you think

**Comment by dmo-odoo** [comment]
The fix is awesome, thanks! However, while you updated the PR message, it seems you forgot to update the commit message... ^^'

**Comment by Mtaylorr** [comment]
@dmo-odoo , I changed the commit message, let me know if it's okay like this

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
