### PR TITLE
[CLA] corporate/factorlibre - Add contributor

### PR DESCRIPTION
**Pull request by xAdrianCif**
This PR is created in order to sing the odoo CLA and contribute to Odoo.

needed for 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xAdrianCif** [comment]
Needed in https://github.com/odoo/odoo/pull/173718

**Comment by mart-e** [comment]
@xAdrianCif why not add your CLA direclty in #173718 then?

**Comment by xAdrianCif** [comment]
> @xAdrianCif why not add your CLA direclty in #173718 then?

Hi! The initial idea was to include it in the same one, but I plan to open another/other PR(s) and didn't want the merging of the first one to hold back the others from getting the CLA.

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by pedrobaeza** [comment]
And being honest, maybe the PRs with the fixes are never merged...

**Pull request closed without merging**
