### PR TITLE
Cash basis taxes fixes when reconciling an invoice with a refund

### PR DESCRIPTION
**Pull request by oco-odoo**
[FIX] account: make tax audit computation work with more complex CABA uses
Before this, it was impossible to reconcile an invoice with a credit note, as the tax_audit field's computation found two invoice lines while it expected only one, and crashed.

Note that our current tax report does still not handle all the cases properly:

- Invoices with negative lines using cash basis taxes won't work well, as we can't differentiate a credit note from an invoice using only debit and credit.

- Misc entries reconciled together with cash basis taxes on them ("faking" the invoice and payment) won't work well either, as both of them have the 'entry' type.

>> This commit is a temporary fix, essentially made to unlock customers blocked byt this issue. Another, more complete, fix is coming soon.

[FIX] account: cash basis taxes: Apply correct repartition to all base lines when reconciling an invoice with a credit note

Before that, when using cash basis taxes and reconciling an invoice with a credit note, both base lines within the cash basis entry applied the invoice repartition of the tax, while one should have had the refund one.

### CODE REVIEW

**Comment by oco-odoo** [comment]
@fw-bot up to saas-12.3

**Comment by oco-odoo** [comment]
@hbto Might be good for you to know about the second commit, as the bug was introduced by this https://github.com/odoo/odoo/commit/f2a473df38b534a429bb561a3009977196a214df ;)

**Comment by hbto** [comment]
@oco-odoo thanks for the follow up.
Regards

**Comment by hbto** [comment]
@oco-odoo 

Actually it seems that this [f2a473d](https://github.com/odoo/odoo/commit/f2a473df38b534a429bb561a3009977196a214df)  might be helping me to resolve a roadblocking point I was having to do my MR to stable, I have to take a deeper look at it. 

As per my comment at https://github.com/odoo/odoo/pull/46393#issuecomment-601006033

Regards.

**Pull request closed without merging**
