### PR TITLE
[IMP]website_slide: Make method private

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

@odony 
Another conflict for @Elkasitu 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Ping @tde-banana-odoo  @jem-odoo  As you are actively working on this

**Comment by sswapnesh** [comment]
Hopefully, This will be removed in V13

**Comment by mreficent** [comment]
Instead of removing, just put a warning for each api.one used 😈

**Comment by Yenthe666** [comment]
Not the biggest PR but a neat little improvement. Somebody should remove that `@api.one` too to be honest 🌵

**Comment by sswapnesh** [comment]
Will done from all place in https://github.com/odoo/odoo/pull/29511

**Comment by tde-banana-odoo** [comment]
Indeed, like say Teal'c.

**Comment by tde-banana-odoo** [comment]
Integrated in https://github.com/odoo/odoo/pull/31233 .

**Pull request closed without merging**
