### PR TITLE
[13.0] fix inverse of x2many fields

### PR DESCRIPTION
**Pull request by rco-odoo**
Writing a list of commands on a non-stored inversible x2many field does not work as expected: the list of commands is applied to an empty recordset, instead of its computed value.  For instance, after writing `[(0, 0, vals)]` on such a field, the final value of the field is the new line only; existing lines have been lost.

### CODE REVIEW

**Comment by rco-odoo** [comment]
@Whenrow

**Comment by Whenrow** [comment]
@rco-odoo The fix works for my use case. Thanks

**Comment by rco-odoo** [comment]
@beledouxdenis thanks for the feedback, I will look for what goes wrong.

**Comment by rco-odoo** [comment]
@beledouxdenis that was a really crappy one: when writing "create" commands on an inherited one2many field, one has to add new records to the field's current value, then inverse the field (this creates a real record), and finally discard the inherited field's value from the cache.

It was not possible to create the new line directly on the inherited field, because the latter is not stored and has no inverse field.  In the test, creating the new line crashes because the field `unit_id` is required.  It is possible to set the inverse field in the case of inherited fields, but this does not fix the more general issue on inversible x2many fields.

**Comment by rco-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
