### PR TITLE
[FIX] typo: field non existent now

### PR DESCRIPTION
**Pull request by cubells**
This field is now attachment_ids in model.

### CODE REVIEW

**Comment by mart-e** [comment]
Thanks for the proposal but I am not convinced of the bug and I would not remov the `attachments` key in the result in 9.0.

- `attachments` contains the generated attachment (base64).
- `attachment_ids` contains the ids of the `ir.attachment` records

[In send mail](https://github.com/odoo/odoo/blob/13a3e76a48be833a681863e3982c11a47fd40863/addons/mail/models/mail_template.py#L539), you can see more clearly how to handle each one.

cc @tde-banana-odoo am I right?

So what is your use case? 
When you create a new PR, we give [a PR template](https://github.com/odoo/odoo/blob/13a3e76a48be833a681863e3982c11a47fd40863/.github/PULL_REQUEST_TEMPLATE.md). Please use it.

**Comment by tde-banana-odoo** [comment]
Yes you are. attachments and attachment_ids are two different things. Effectively attachments is not a field but its content are managed by sub methods.

**Comment by cubells** [comment]
@mart-e 

Ok. It does not make sense to me to create a mail with an incorrect key here:

https://github.com/odoo/odoo/blob/13a3e76a48be833a681863e3982c11a47fd40863/addons/mail/models/mail_template.py#L544

to process later here:
https://github.com/odoo/odoo/blob/13a3e76a48be833a681863e3982c11a47fd40863/addons/mail/models/mail_template.py#L547

But It's only a strange way to do things for me. :)

**Comment by mart-e** [comment]
But we don't create it with an incorrect key as it is removed

```python
attachments = values.pop('attachments', [])
```

**Comment by cubells** [comment]
ok. I'm wrong. Sorry for the noise.

**Pull request closed without merging**
