### PR TITLE
[MERGE] sale_rental: new renting application

### PR DESCRIPTION
**Pull request by Feyensv**
New Rental App (sale_rental) : community side.

1. Product configurator:
Refactoring to ease product configurator extension (e.g. rental configurator)
Closes #33371 

2. Event_sale
Fix tests of event configurator s.t. they still work when sale_rental is installed (with its extension of the product configurator).

3. Sale
XML names for XPath in rental extension
Minor UI changes

[Enterprise PR](https://github.com/odoo/enterprise/pull/3939)

Related to #30855
Task 1909410

### CODE REVIEW

**Comment by dbo-odoo** [comment]
@Feyensv 
We'll need to rework some commit msgs and the pr msg for the merge commit tomorrow morning

**Comment by dbo-odoo** [comment]
@robodoo r+ rebase-merge

**Comment by d-fence** [comment]
@robodoo retry

**Comment by d-fence** [comment]
@robodoo r+ rebase-merge

**Comment by dbo-odoo** [comment]
Listen carefully
For I am on the verge,
As shown in this [chart](https://i.imgflip.com/ooebh.png),
Of losing my patience:
@robodoo r+ rebase-merge
Or I shall start
Petitioning for your obsolescence

**Comment by dbo-odoo** [comment]
Here I am
Trying your tests
None of them failed
After a db purge

Are you a scam?
Please do your best
Or go get nailed
@robodoo r+ rebase-merge

**Comment by Yenthe666** [comment]
Seems to go like a charm @dbo-odoo - I think you two need a talk!

**Comment by dbo-odoo** [comment]
Seems like threats don't go well, my next attempt might be more of the seducing kind

**Comment by Feyensv** [comment]
Here i was checking why this fucking test went wrong, 
but my gooroo's already fighting strong :+1: ,
dunno when and where the fight human-machine will stop :D

**Comment by dbo-odoo** [comment]
runbot is red
lilies are blue

our fate was set
but rebuild=true

**Comment by dbo-odoo** [comment]
@robodoo r+ rebase-merge ?

**Comment by dbo-odoo** [comment]
\o/

**Pull request closed without merging**
