### PR TITLE
[FIX] web, models: issues in onchange o2m

### PR DESCRIPTION
**Pull request by Gorash**
[FIX] web, models: issues in onchange m2m in o2m

view and widget objects send all sub-field to receive complete server information from onchange (including sub-field for any level)
add guardrails to find errors and improve the code in the future
fix the rendering in list editable to display change and m2m tags
remove some unless change trigger

### CODE REVIEW

**Comment by Gorash** [comment]
@odony : splitted branch with _get_onchange_fields

**Comment by auyeung112002** [comment]
Any updates on this issue? Are the above commits work in version 9?

**Comment by Gorash** [comment]
I have not yet been able to merge this fix for several internal reasons (complexity, lack of reviewers...)

**Comment by auyeung112002** [comment]
I tested the code and find that the editable list view does not work.
@Gorash Would you please advice?

Here is the code base used since the base code changed since the pull request opened:
https://github.com/auyeung112002/odoo/tree/9.0

**Comment by pedrobaeza** [comment]
I confirm that this branch solves the hack we need to do here: 

https://github.com/OCA/product-variant/pull/49/files#diff-f194b515e11db9b5f1384afb6c3db651R21

to avoid the problem commented here: 

https://github.com/OCA/server-tools/pull/492#issuecomment-237594285

**Comment by Yajo** [comment]
This conflicts

**Comment by NobodyIII** [comment]
I need the fix provided here. Will this be merged soon? If not, what is the best way to get this fix into my odoo installation, considering the merge conflicts?

**Comment by mart-e** [comment]
@NobodyIII sorry but it is not something we are going to merge in 9.0, too risky for a stable version

**Pull request closed without merging**
