### PR TITLE
[CLA] add goliveirab to Vauxoo's CLA

### PR DESCRIPTION
**Pull request by goliveirab**
Name: Germana Oliveira
E-mail: germana@vauxoo.com
GitHub user: https://github.com/goliveirab

### CODE REVIEW

**Comment by luistorresm** [comment]
FYI @qdp-odoo

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `g...@gmail.com`
- you are signing for the address `g...@vauxoo.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by goliveirab** [comment]
email changed for CLA signature

**Comment by mart-e** [comment]
Thanks, merged at 8ee9cec4d5da60f15dff0cbf354b637e4c6d337b

**Pull request closed without merging**
