### PR TITLE
[FIX] website: use correct endpoint in get_canonical_url

### PR DESCRIPTION
**Pull request by madprog**
`router` is a routing map which might be different than the request's. In this case, `request.endpoint` won't be found as a key of this routing map, and it will lead to a werkzeug.routing.Builderror.

By re-matching the current path on this specific router, we make sure that the endpoint will be found in this routing map.

### CODE REVIEW

**Comment by madprog** [comment]
To reproduce the exception on a runbot, you can edit the view `website.website_info` by adding this line before the `<t t-call="website.layout">`:
```xml
    <t t-set="toto" t-value="request.env['ir.http']._clear_routing_map()"/>
```
It will cause a clearance of the routing map, that could also be triggered by the invalidation of an asset: the attachment is unlinked, and `clear_caches` is called, which causes a `_clear_routing_map`.

This change will break the route `/website/info` and cause the quite obscure traceback:
```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/qweb.py", line 334, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_frontend_layout_255
  File "/data/build/odoo/addons/website/models/website.py", line 471, in _get_alternate_languages
    if not self._is_canonical_url(canonical_params=canonical_params):
  File "/data/build/odoo/addons/website/models/website.py", line 907, in _is_canonical_url
    canonical_url = self._get_canonical_url_localized(lang=request.lang, canonical_params=None)
  File "/data/build/odoo/addons/website/models/website.py", line 881, in _get_canonical_url_localized
    path = router.build(request.endpoint, arguments)
  File "/usr/lib/python3/dist-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: <unprintable BuildError object>
```

**Comment by JKE-be** [comment]
@fw-bot up to 14.0

**Review by JKE-be — APPROVED** [review]
LGTM in v13/v14

from v14.1 need to optimize the cache with url_rewrite

**Review by rdeodoo — APPROVED** [review]
LGTM.

While I don't see any drawback with the second commit, that seems quite of a change for 13.0. The risk/reward is not something I would take personally if I was to merge this.
It looks like a pretty cool perf imp tho !

I'll let you decide, but please add perf tests in 15.0 (not worth spending time < 15.0 IMHO, as long as that perf improvement is checked in 15.0 so we are sure it won't be reverted later its cool).

~~(Surely I tested wrongly but it always takes 47 requests for /blog/xx/post/xx and 52 for /fr/blog/xx/post/xx regardless if I have one or 30 langs, I guess something else is involved on Odoo.com? Other module or something?)~~ Indeed, wrongly tested

**Comment by JKE-be** [comment]
@robodoo r+ rebase-ff

**Comment by rdeodoo** [comment]
> To reproduce the exception on a runbot, you can edit the view website.website_info by adding this line before the <t t-call="website.layout">:

Note that it also seems like, whenever you installed a new module through the `+ New` button in the frontend, it crashed with that same error after having installed the module and reloading the page.

image

**Pull request closed without merging**
