### PR TITLE
[FIX] sale: make sure to define a fallback for multi company products

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
In case a product template does not have a company assigned it will assert in ```_convert``` which is producing a Internal Server Error for the user trying to access the shop page.

**Current behavior before PR:**
Internal Server Error (HTTP 500)
**Product Trigger**: Deposit

**Desired behavior after PR is merged:**
Use the company of the current user as a fallback for products without a dedicated company.

@JKE-be @nim-odoo 
May I ask you to merge this for me? Thank you :smile: 

Info: @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think you should go for the company of the pricelist instead, and if also not present, then the user one.

**Comment by wtaferner** [comment]
@pedrobaeza 
Not 100% sure if this is what we want, but I can somehow identify with your thought...it is anyway just a matter of retrieving currency rates which should be more or less the same most of the times between companies. I made a second commit which can be squashed easily by @robodoo I hope :wink:

**Comment by pedrobaeza** [comment]
Yeah, this is a corner case, but following the most specific data (pricelist company) can avoid future problems, so it's not a big deal to put it, and that's why I told you.

**Comment by wtaferner** [comment]
Hehe, and this is why I added the second commit ^^

**Comment by JKE-be** [comment]
Hi,

Should be already handled by https://github.com/odoo/odoo/pull/29946/files ;)

Is it ok for you?

thx

**Comment by pedrobaeza** [comment]
What about the pricelist detail (or maybe take website company)?

**Comment by seb-odoo** [comment]
Thank you for the PR and the interesting discussion. This is similar to #29946 

I think the correct fallback order should be: product website company, pricelist company, current user company

I will update my PR to add those additional fallbacks.

**Comment by wtaferner** [comment]
Hmm, what took you soo long? It was breaking the shop :smile:  I am fine if Odoo core is working as expected, but I agree with Pedro and honestly I like my solution more, so maybe @seb-odoo  can cherry pick and squash them into his PR and keep me as an author :wink:

**Comment by wtaferner** [comment]
And, what is wrong with runbot? Chrome is the new PhantomJS (probably to keep the signature I guess) :confused:

**Comment by JKE-be** [comment]
@pedrobaeza @wtaferner 

Is the #29946  Ok for you and I close this one ?

**Comment by pedrobaeza** [comment]
@JKE-be and @seb-odoo thanks for the changes. I have put a little comment in the other PR. For me, this one can be closed.

**Comment by wtaferner** [comment]
@JKE-be @seb-odoo 
Thank you a lot and I like how the fix was done in the end and also appreciate the respect in terms of co-authorship.

**Pull request closed without merging**
