### PR TITLE
[FIX] l10n_cn: clean taxes name

### PR DESCRIPTION
**Pull request by hpr-odoo**
Description of the issue/feature this PR addresses:

task-2157487

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@hpr-odoo Would you be so kind to rebase the branch?  (and check if it turns green?)

**Comment by hpr-odoo** [comment]
@jco-odoo , branch is rebased and also green on runbot. Thank you :)

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
