### PR TITLE
[IMP] Hr phone validation

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
Add employee phone validation :-)

image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Hello,

Seems nice. I forward it to our beloved product owner team.

**Comment by tde-banana-odoo** [comment]
Hi,

Our feedback team decided not to accept the proposal. It is considered as not necessary and not linked to "a real use case or a feature we need" (citing the feedback). Sorry for the negative answer.

Best regards,

**Comment by fmdl** [comment]
Hi @tde-banana-odoo, I understand your point.

I have forget to tell some things: if you need to use to send SMS to employee by sms module, it is better to send with international format.

Regards

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for the update! I send it back to our feedback team.

**Comment by mart-e** [comment]
The update of the feedback was that the phone number of the employee is something private and we do not wish to use validation. Sorry but still have to reject.

**Pull request closed without merging**
