### PR TITLE
[FIX] product: create a variant from the variant list adds to the template

### PR DESCRIPTION
**Pull request by kebeclibre**
Before this fix when you:
    On a product template, clicked on the variant smart button
    Create a variant
    
    You ended up with two problems:
    1. None of the info of the template were present in the form, where obvisously you wanted to.
    2. Upon saving, a whole new product.template and product.product were created, which is confusing
    
    After this fix, values of the template are prefteched into the variant's form
    Upon saving, the new variant is associated with the current template
    
    OPW 771647
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But what are the attribute values assigned to this variant?

**Comment by kebeclibre** [comment]
The attributes values of this variant are the ones you give it during its creation
This mechanism by-passes the normal mechanism of variant creation from the template, namely the creation of all combination of attributes values

**Comment by pedrobaeza** [comment]
Uhm, I see that the field is editable, but there's no constraint for avoiding 2 variants with the same attribute values. Even more, there's no constraint that makes you to fill all the needed attribute values. We worked on this module for a correct variant creation from template: https://github.com/OCA/product-variant/tree/10.0/product_variant_configurator

**Comment by nim-odoo** [comment]
Unfortunately, this cannot be accepted. The manual creation of variants is simply not supported: variants should only be generated automatically from the attributes.

**Comment by pedrobaeza** [comment]
@nim-odoo maybe as UI helper the create button can be disabled when you click on that smartbutton? (not sure if technically possible)

**Pull request closed without merging**
