### PR TITLE
[CLA] Add agarzaarvizu to Vauxoo's contributors

### PR DESCRIPTION
**Pull request by agarzaarvizu**
## Incorporate Alejandro Garza (agarzaarvizu) as Vauxoo's contributor

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agarzaarvizu** [comment]
@luisg123v Done

**Comment by luisg123v** [comment]
Add what user is being added in the title.

I know it was missing on some previous commits

Something like

`[CLA] add agarzaarvizu to Vauxoo's contributors`

**Comment by agarzaarvizu** [comment]
@luisg123v Done

**Review by luisg123v — APPROVED** [review]
LGTM :+1: 

@mart-e could you review, please?

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by mart-e** [comment]
robodoo retry

**Comment by mart-e** [comment]
robodoo retry :roll_eyes:

**Pull request closed without merging**
