### PR TITLE
[FIX] website_forum: fix typo

### PR DESCRIPTION
**Pull request by niyasraphy**
Insteadeither is added without space, adding spacing between the words.

Insteadeither  --> Instead either

Screenshot from 2023-03-15 16-49-21

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
hi @flch-odoo ,
if you have time, can you review this.
thanks

**Comment by flch-odoo** [comment]
@tde-banana-odoo  since you're in `website_forum`... LGTM, unless we want to add the missing commas after all the `"instead"` as well?

**Comment by tde-banana-odoo** [comment]
Isn't it a french thing to add commas everywhere ?

**Comment by flch-odoo** [comment]
Not in this case, see the adverb case: https://www.englishgrammar.org/adverb-preposition/.
Sames applies to `However, `, `Therefore, `, etc.

**Comment by tde-banana-odoo** [comment]
Feel free then :D

**Comment by niyasraphy** [comment]
hi @tde-banana-odoo @flch-odoo ,
updated the pr

**Comment by tde-banana-odoo** [comment]
But I would just do it on the line we are already fixing, to avoid breaking translations and having to translate everything again :D

**Comment by tde-banana-odoo** [comment]
Then maybe if we want something coherent, just fix the typo here and add the commas in master.

**Comment by niyasraphy** [comment]
hi @tde-banana-odoo ,
updated the pr

**Pull request closed without merging**
