### PR TITLE
[fix] sales_team : type 'date' is not JSON serializable

### PR DESCRIPTION
**Pull request by pja-odoo**
Description of the issue/feature this PR addresses:
I have tested this issue on runbot
If the sales team configure with  Content = Sales, Scale = Last Month and Group by = null and 
try to open the sales team at that time getting the error like
return json_encoder_default(self, o)
File "/usr/lib/python3.6/json/encoder.py", line 180, in default
o.class.name)
TypeError: Object of type 'date' is not JSON serializable

For more refer see the attached video 
[https://drive.google.com/file/d/1Yq_eIx94SDW1wuxhPGQek6UEEZ_afD9K/view](url)
Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pja-odoo** [comment]
@KangOl 
Can you please review it. 
Thanks

**Comment by KangOl** [comment]
My questions from #39300 still stand!

And your patch is wrong. This is not the place to fix it. The `date` objects should be formatted at the source.

**Comment by pja-odoo** [comment]
@KangOl 
Why does it happen suddenly?
- >  It does not happen suddenly, this error does not raise directly, you need to change the dashboard configuration of the sales team.

Where does the date object come from?
-> The date object comes from the 'sale.report', which is the 'confirmation_date' of the sale_report.

As per your suggestion, I have fixed the issue from the source.
If I am wrong please correct me.

> My questions from #39300 still stand!
> 
> And your patch is wrong. This is not the place to fix it. The `date` objects should be formatted at the source.

**Comment by pja-odoo** [comment]
@KangOl 
As per your suggestion, I have fixed the issue from the source.
If I am wrong please correct me.
Can you please review it.
thanks

**Comment by pja-odoo** [comment]
@KangOl 
As per your suggestion, I have fixed the issue from the source.
If I am wrong please correct me.
Can you please review it.
thanks

**Comment by C3POdoo** [comment]
Dear @pja-odoo,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
