### PR TITLE
crashmanager wrong syntax of arrow function

### PR DESCRIPTION
**Pull request by msh-odoo**
Task:https://www.odoo.com/web#id=2052484&action=333&active_id=133&model=project.task&view_type=form&menu_id=4720

Pad: https://pad.odoo.com/p/r.ea7f7f46354da00b4fd13af97cfa31bb

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by msh-odoo** [comment]
ping @aab-odoo

**Comment by fja-odoo** [comment]
@alexkuhn looks like this function is not working as we taught. I should have tested it more... 
I looked into it and the this is in fact undefined, the arguments are also not referencing the error.

**Comment by alexkuhn** [comment]
@fja-odoo Indeed, `arguments` makes sense in the scope of a `function`, but with arrow functions it doesn't work...

**Comment by fja-odoo** [comment]
@msh-odoo Looks good to me, can you reference the PR where the bug was introduce in your commit: https://github.com/odoo/odoo/pull/35209

**Comment by msh-odoo** [comment]
@fja-odoo I added commit reference from where it is produced in my commit message

**Comment by pimodoo** [comment]
@VincentSchippefilt Does it looks good to you? Are you sure we shouldn't keep the same syntax guidelines inside a file and avoid shortcut like arrow functions in a file where there are not any, as it doesn't change anything.

**Comment by VincentSchippefilt** [comment]
@pimodoo Yep I am good with it: arrow functions instead of anonymous function (inside named ones) makes good sense. 
I don't think we will go through a conversion phase for it, so using it little by little in new and modified code is good.

**Comment by pimodoo** [comment]
@VincentSchippefilt so can you merge it please?

**Comment by pimodoo** [comment]
robodoo r+ rebase-ff

**Comment by pimodoo** [comment]
robodoo r-

**Comment by pimodoo** [comment]
@msh-odoo Hello,

@aab-odoo requested some test for this fix in the enterprise PR

**Comment by msh-odoo** [comment]
@aab-odoo Thanks for the test case, I added it, would you please check it now?

**Comment by msh-odoo** [comment]
@pimodoo test added

**Comment by pimodoo** [comment]
@aab-odoo ca n we merge it?

**Comment by pimodoo** [comment]
robodoo r+ rebase-ff

**Pull request closed without merging**
