### PR TITLE
[IMP] payment_authorize: make it possible to customize AcceptJS params

### PR DESCRIPTION
**Pull request by jorenvo**
Without this you have to overwrite the entire function.

PR note: necessary to overload this in an internal module.

### CODE REVIEW

**Review by nim-odoo — APPROVED** [review]
robodoo delegate+

**Comment by jorenvo** [comment]
@robodoo r+

**Comment by jorenvo** [comment]
@robodoo r-

**Comment by jorenvo** [comment]
@robodoo r+

**Pull request closed without merging**
