### PR TITLE
[FIX] account_payment: handle error while computing suitable payment token

### PR DESCRIPTION
**Pull request by alsh-odoo**
This traceback may arise while computing suitable payment tokens,
when a user clicks register payment in the invoice.

Because in `_compute_suitable_payment_token_ids` method,
instead of `paymet.token` `payment.tokeb` is used. 
Which is an invalid model name. It leads to keyerror.

Error:
```
KeyError: 'payment.tokeb'
  File "odoo/http.py", line 2134, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1710, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1737, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1938, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 191, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 717, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 30, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 26, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "odoo/models.py", line 6744, in onchange
    todo = [
  File "odoo/models.py", line 6747, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "odoo/models.py", line 6546, in has_changed
    len(self[name]) != len(record[name])
  File "odoo/models.py", line 6171, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/fields.py", line 2835, in __get__
    return super().__get__(records, owner)
  File "odoo/fields.py", line 1210, in __get__
    self.compute_value(recs)
  File "odoo/fields.py", line 1388, in compute_value
    records._compute_field_value(self)
  File "odoo/models.py", line 4524, in _compute_field_value
    fields.determine(field.compute, self)
  File "odoo/fields.py", line 100, in determineKeyError: 'payment.tokeb'
  File "odoo/http.py", line 2134, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1710, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1737, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1938, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 191, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 717, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 30, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 26, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "odoo/models.py", line 6744, in onchange
    todo = [
  File "odoo/models.py", line 6747, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "odoo/models.py", line 6546, in has_changed
    len(self[name]) != len(record[name])
  File "odoo/models.py", line 6171, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/fields.py", line 2835, in __get__
    return super().__get__(records, owner)
  File "odoo/fields.py", line 1210, in __get__
    self.compute_value(recs)
  File "odoo/fields.py", line 1388, in compute_value
    records._compute_field_value(self)
  File "odoo/models.py", line 4524, in _compute_field_value
    fields.determine(field.compute, self)
  File "odoo/fields.py", line 100, in determine
    return needle(*args)
  File "addons/account_payment/wizards/account_payment_register.py", line 40, in _compute_suitable_payment_token_ids
    *self.env['payment.tokeb']._check_company_domain(wizard.company_id),
  File "odoo/api.py", line 521, in __getitem__
    return self.registry[model_name](self, (), ())
  File "odoo/modules/registry.py", line 208, in __getitem__
    return self.models[model_name]
    return needle(*args)
  File "addons/account_payment/wizards/account_payment_register.py", line 40, in _compute_suitable_payment_token_ids
    *self.env['payment.tokeb']._check_company_domain(wizard.company_id),
  File "odoo/api.py", line 521, in __getitem__
    return self.registry[model_name](self, (), ())
  File "odoo/modules/registry.py", line 208, in __getitem__
    return self.models[model_name]
```

See:
https://github.com/odoo/odoo/blob/60598dff9d8482bcea2f32fea6df1b1b71c760d6/addons/account_payment/wizards/account_payment_register.py#L36-L41

In the above usecase, while computing `payment.tokeb` it leads to the above traceback.

sentry-4380761438

### CODE REVIEW

**Comment by alsh-odoo** [comment]
Hello @odoo/sentry_reviewers 

Please review this PR

Thank You!!

**Comment by bit-odoo** [comment]
Hello @qdp-odoo small PR for you :smile:

**Comment by adwid** [comment]
robodoo delegate=abz-odoo

**Comment by abz-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
