### PR TITLE
brands3

### PR DESCRIPTION
**Pull request by chapital**
Feature request

BRANDS.

Hi

I propose to add a field to put the BRAND, when you add a product.

Your team Says I can add this like a product category but I already use this field for other things.

This will have a lot of uses, I make a customization with a developer, and works very good to add as default feature an add more range of feature to add.

Advantages:
1.-Can recognice the brand of a product, and use filters.
2.-For business like clothings store will be very helpful for sell in ecommerce shopping by brand.
3.-In purchase if you establish a specific vendors and when you are creating a request quotation an select a wrong vendor it will notify maybe this mistake.
4.-In sales you can have easy access to view what vendor sell that brand to verify stock maybe is I don't have this in my warehouse.
5.-For reports will help to identify the sales and purchase by brand.

I attach a video how does this module works and I can share if you wanna to put like default in Odoo.

Video:

https://www.refatodo.com/img/brands.mov

*The sample use in ecommerce its only for reference.

refererences:

https://amasty.com/shop-by-brand-for-magento-2.html
https://apps.shopify.com/shop-my-brand
https://woocommerce.com/products/brands/

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

I am not sure what is the context of this PR but we usually do not add new features from external contributors.
I am not saying this is a bad feature but no something we want to support.
Best,

**Comment by mart-e** [comment]
@chapital [we hire developers](https://www.odoo.com/jobs) :wink: 
More seriously, you are welcome to submit bugfixes here but new modules with new features will not be accepted (with the exception of localisation modules).
The odoo/odoo codebase is opensource, but is not steered by the community but by Odoo S.A.; a completely open-source steered list of addons is done by the [Odoo Community Association](https://odoo-community.org/) in @OCA repositories if you wish for your contributions to be widely available without the need for Odoo S.A's approval.
You may want to try to submit your module there.

**Comment by pedrobaeza** [comment]
There's already a brand module suite in OCA. Check modules product_brand and website_product_brand.

**Comment by chapital** [comment]
@pedrobaeza @mart-e Thanks for the info, I have a module that make also a notifications for purchase, you can check the video, I validate the OCA addons, also I wanna highlight that this modules that pedro says, its the most downloaded in OCA(normally an OCA addon have 1-5 downloads but this have 200-400 downloads), that mean it's probably a funtion missed by default in odoo,this is only a recomendation, Regards

**Pull request closed without merging**
