### PR TITLE
9.0: fix memory issue when restoring a large db dump

### PR DESCRIPTION
**Pull request by CGenie**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by CGenie** [comment]
This should fix the issue from https://github.com/odoo/odoo/pull/12376

**Comment by Yenthe666** [comment]
Same thing that you're trying to fix as https://github.com/odoo/odoo/pull/17663 but there has been feedback on the PR already.

**Comment by Gorash** [comment]
Hi,
Thank you for your contribution. However, we can not add library / dependency in a stable version, moreover, only some critical bug applied on this version 9.0.
Regards

**Comment by CGenie** [comment]
Yeah, the `six` depedency for 9.0 can easily be fixed by replacing `six.string_types` with `basestring` since we're using Python 2 there actually. I thought `six` was part of the official distribution but I might be mistaken since I haven't used it in a long time :)

Funny that #17663 is not fixed for such a long time especially that it affects 10.0 and 11.0 as well from what I see in the code. I mean the bigger the customer and the bigger his DB the more we should care about him and the more pressure it puts on the issue? :)

**Comment by Yenthe666** [comment]
Agreed on the bad response rate of https://github.com/odoo/odoo/pull/17663 and that it should get a lot more attention.. /myfivecents

**Pull request closed without merging**
