### PR TITLE
[stock] REM: duplicated description for stock module

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: The description is twice in the stock module, both in the `readme.md` and in `manifest.py`

Current behavior before PR: The description is twice in the stock module, both in the `readme.md` and in `manifest.py`

Desired behavior after PR is merged: The description is only in the `readme.md` (used on the app store) and no longer in the `manifest.py`, which both had slightly different info.
This handles / fixes https://github.com/odoo/odoo/issues/3846

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hi @mart-e this is the PR that you where talking about that it would be accepted (https://github.com/odoo/odoo/issues/3846)

Regards,
Yenthe

**Comment by mart-e** [comment]
Have you tested it? Because it is not the description of the readme that is taken but the one from [index.html](https://github.com/odoo/odoo/blob/10.0/addons/stock/static/description/index.html) that is taken (yeah, a third one 👍 )

**Comment by Yenthe666** [comment]
You're correct. It doesn't use the description from `manifest.py` and neither does it use the `readme.md`, so the `readme.md` is only viewed on Github I guess.
Double checked & tested, we can remove both files (see above commit to remove the second file).
This is cleaner as there is only one place for information.

**Comment by mart-e** [comment]
Merged at fe346fa021d, thanks

**Pull request closed without merging**
