### PR TITLE
[FIX] l10n_es_edi_facturae: use list instead of tuple for selection

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@william-andre Somehow the list/tuple does play a role.

**Comment by jco-odoo** [comment]
@william-andre I tested and with this branch, you can see the selection options and without not: 

image

**Review by william-andre — APPROVED** [review]
@robodoo r+

@ryv-odoo I already approved to avoid wasting time on this issue, but shouldn't we also include tuples though? Or would that be an issue because of immutability (or something else)?
https://github.com/odoo/odoo/blob/cf3f9224a5252a0d666611028e9b7ab83817fa8d/odoo/fields.py#L2713

**Comment by ryv-odoo** [comment]
Hello,

> @ryv-odoo I already approved to avoid wasting time on this issue, but shouldn't we also include tuples though? Or would that be an issue because of immutability (or something else)?

Indeed, we should also accept tuple or at least making a warning.

**Comment by jco-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
