### PR TITLE
[11.0] Invoices should limit the computation of residual to the move lines that have the same partner.

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Description of the issue/feature this PR addresses:
This PR improves the calculation of field 'residual' of account.invoice, restricting the the amount pending o the account move lines where the partner matches with the commercial partner of the invoice.

Current behavior before PR:
The amount residual is computed based on the move lines where the account matches with that on the invoice. This is a problem in customizations where you might include in an invoice lines that refer to account payable/receivable, but for another partner.

This is typical, for instance, in the process of managing third party expenses (see https://github.com/etobella/account-invoicing/blob/11.0-add-account_invoice_reimbursable)

Desired behavior after PR is merged:
The residual amount in an invoice is computed as the amount due to this partner, for the account indicated in the invoice. 

Any move lines that match with the invoice's account (receivable/payable) but that do not match partner-wise are ignored for the computation of the residual amount.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jbeficent** [comment]
@qdp-odoo what do you think about this?

cc @etobella

**Comment by jbeficent** [comment]
@qdp-odoo What do you think about this one?

**Comment by qdp-odoo** [comment]
well, I'm not really keen to do it: 

On the fond: I suppose that, if I have a customization allowing to change the partner on the journal items created from an invoice (like something involving a "debt buy"), I still want to see my invoice unpaid until the debt buyer paid me the money.

Also, on the form, adding special code to deal with use cases that aren't possible in the main core module isn't really clean. I'd prefer to see a PR splitting the existing code in methods without any behavior change, but that will ease the overwriting by custom dedicated modules.

For these reasons, I'm closing the PR but thanks for the proposal

**Comment by jbeficent** [comment]
@mreficent can you propose a PR as @qdp-odoo suggests?

**Pull request closed without merging**
