### PR TITLE
[IMP] web: update owl to 1.4.9

### PR DESCRIPTION
**Pull request by sdegueldre**
Release notes: https://github.com/odoo/owl/releases/tag/v1.4.9

### CODE REVIEW

**Review by aab-odoo — COMMENTED** [review]
commit message to 1.4.9 :D

**Comment by sdegueldre** [comment]
@aab-odoo done

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by sdegueldre** [comment]
@aab-odoo apparently I wasn't up to date on 14.0 when I created this commit and it was breaking the upgrade CI. I've rebased now so we'll need to r+ again

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
