### PR TITLE
[IGNORE] Test if runbot actually run unit tests

### PR DESCRIPTION
**Pull request by obayit**
Ignore this
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
It does.

**Comment by tivisse** [comment]
It definatly does.

**Comment by tde-banana-odoo** [comment]
@obayit  You know you can test locally right ?

**Comment by obayit** [comment]
Sorry @tde-banana-odoo co I am too lazy, I will stop wasting your precious resources.

**Comment by obayit** [comment]
@tivisse I had a doubt because there was _a test_ that shouldn't have passed, but somehow the code ended up in the `15.0` branch.

**Pull request closed without merging**
