### PR TITLE
[FIX] l10n_es: Fix equity account types

### PR DESCRIPTION
**Pull request by antoine162**
Accounts 10x -> 13x should be of 'equity' type.
(In the Balance Sheet, they are referenced under the Equity section.)

Enterprise PR: https://github.com/odoo/enterprise/pull/57117

opw-3743637

### CODE REVIEW

**Review by JulienVR — APPROVED** [review]
Looks good technically :)

**Comment by h4818** [comment]
@fw-bot ignore

**Comment by h4818** [comment]
@fw-bot up to master

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@HaraldPanten

**Pull request closed without merging**
