### PR TITLE
CLA signature Blanco Martin y Asociados - Jose Moreno Hanshing

### PR DESCRIPTION
**Pull request by Danisan**
Description of the issue/feature this PR addresses:
CLA signature: new collab: Jose Moreno Hanshing

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Danisan** [comment]
@jco-odoo @ren-odoo CLA signature for Jose Moreno Hanshing.

**Comment by mart-e** [comment]
@Danisan could you amend your commit message to follow the [commit message guidelines](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#commit-message-structure) and use the `[CLA]` tag? Something like:

```
[CLA] update signature Blanco Martin y Asociados

Add Jose Moreno Hanshing
```

**Comment by Danisan** [comment]
@mart-e this is ready. Thanks!

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
