### PR TITLE
[FIX] requirements.txt: Fix maximum recursion in gevent

### PR DESCRIPTION
**Pull request by moylop260**
Using py3.6 and gevent==1.1.2 the following error could be reproduced
in corner cases:

    File "/usr/lib/python3.6/ssl.py", line 485, in verify_mode
        super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    File "/usr/lib/python3.6/ssl.py", line 485, in verify_mode
        super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    File "/usr/lib/python3.6/ssl.py", line 485, in verify_mode
        super(SSLContext, SSLContext).verify_mode.__set__(self, value)
    [Previous line repeated 281 more times]
    RecursionError: maximum recursion depth exceeded

But using any version gevent>1.1.2 the issue is not reproduced
even gevent==1.2.0

The corner case to reproduced is the following:
 - Use py3.6
 - install gevent==1.1.2
 - Configure the reverse proxy
   - Use proxy e.g. nginx
   - `--longpolling-port`
   - `--workers>2`
 - Use Odoo>=12.0
 - Install and configure [sentry module of the OCA](https://github.com/OCA/server-tools/tree/12.0/sentry)
 - Reload the /web page 2 times
 - See the logger error of maximum recursion
 - Now, install gevent==1.2.0 or gevent==1.5.0
 - Restart odoo-bin service
 - Reload the /web page 2 times again
 - See the logger and now it is not reproduced

The gevent 1.1.2 version was assigned to be used in python3.5
But maybe for python3.6 we need bump it like python3.7

Issues related:
 - https://github.com/OCA/server-tools/issues/1499
 - https://github.com/gevent/gevent/issues/1016
 - https://github.com/getsentry/sentry/issues/3384
 - https://github.com/odoo/odoo/pull/50861
   - It was another corner case using py3.7 but they rolling backed
      to python 3.5 but maybe it could be reproduced in py3.6 too

### CODE REVIEW

**Comment by moylop260** [comment]
Hi @d-fence 
Could you check it, please?

Regards!

**Comment by moylop260** [comment]
@nim-odoo Hello my friend

Could you check this one, please?

**Comment by thomaspaulb** [comment]
I can confirm this bug when running Odoo with the [NewRelic Python Agent](https://github.com/newrelic/newrelic-python-agent).

Apparently the `gevent` (relevant for Odoo) and `eventlet` (not relevant to Odoo) packages monkey-patch the 'options' parameter in SSLcontext, but this monkey-patch leads to errors when calling `urllib` from within the gevent worker thread.

Related link:

https://bugs.python.org/issue29149

**Comment by thomaspaulb** [comment]
@pedrobaeza What is the right way to report something like this to Odoo so that they respond?

**Comment by pedrobaeza** [comment]
Well, I'm pinging @mart-e and @d-fence to see if they can tell us.

**Comment by d-fence** [comment]
I'll check that.
Sorry the mail notif got lost among others.

**Review by d-fence — CHANGES_REQUESTED** [review]
Even though I was not able to reproduce with standard Odoo modules, your PR looks good as only those who will run Odoo with python 3.6 will encounter the change.
e.g. when installing Odoo from source on Ubuntu Bionic.

But when I read gevent issues

- gevent/gevent#941
- gevent/gevent#1016

I didn't see any reference of the incompatibility, they pointed programming errors like monkey patch order: [here](https://github.com/gevent/gevent/issues/941#issuecomment-281497659) and [here](https://github.com/gevent/gevent/issues/1016#issuecomment-328529454).
Did you double check the sentry module or even the raven package ?
But I could be wrong, do you have any reference ?

Finally, the two commits should be squashed into one.

**Comment by thomaspaulb** [comment]
@d-fence Actually you're right, it's because of the order of importing. If `create_urllib3_context` is called in code that was imported before the monkey-patch was done, the infinite loop can result. In case of the New Relic Agent that is obviously the case because:

- The agent is called as a wrapper for the Odoo startup script, so before `import odoo` which does the [monkey patching](https://github.com/odoo/odoo/blob/12.0/odoo/__init__.py#L27)
- The agent indeed [calls create_urllib3_context](https://github.com/newrelic/newrelic-python-agent/blob/main/newrelic/packages/urllib3/util/ssl_.py#L346).

About the OCA sentry module, this puzzles me still because that one should be loaded by `load_server_wide_modules`, which is well after `import odoo` gets called. Unless @moylop260 is using some non-standard WSGI script to start his Odoo service or `gevent` thread?

**Comment by hoangtrann** [comment]
Pinging @moylop260 @thomaspaulb @d-fence to see if we could merge this

**Comment by moylop260** [comment]
@hoangtrann 

I confirm

The project where we are using odoo 12.0 with python3.6 the issue is not reproduced anymore using this PR and Odoo is working properly.

**Comment by C3POdoo** [comment]
Dear @moylop260,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
