### PR TITLE
[FIX] prettify_html doesn't check 'em' tags from MS IExplorer

### PR DESCRIPTION
**Pull request by zeroheure**
remove one of two `strong` tag

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@qsm-odoo this seems safe to be merged on stable.

**Comment by zeroheure** [comment]
@pedrobaeza should I PR in OCB ? from time to time I report glitches and little errors, but acconding to Odoo policy, they are only fix in 11.

**Comment by pedrobaeza** [comment]
What would be the benefit of that apart from a bit of code cleaning?

**Comment by zeroheure** [comment]
nothing :-) Or may be there is a little bug because the second strong shourd be an em tag ?

**Comment by JKE-be** [comment]
Merged in v10 https://github.com/odoo/odoo/commit/b10e34ed1a037595a29d6952bd7cbcb55d8aba8c

Thanks for PR

**Pull request closed without merging**
