### PR TITLE
[FIX] website_forum: force image size in css to handle gifs

### PR DESCRIPTION
**Pull request by jvnm-dev**
### Issue

	- Preferences > Change your avatar with a big .gif
	- Install Forum
	- Go on a question

	The gif is not resized in the nav and in the post
	answer box

### Cause

	In fact, all gifs are not really resized. They just
	look fine because there is CSS to handle the case
	where the server resize does not work.

### Solution

	Do as it is done everywhere else, add CSS rules

**OPW-2223260**

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
@nle-odoo

**Comment by nle-odoo** [comment]
also for the sake of completeness, in website_forum if you go to:

http://localhost:8069/forum/help-1?my=mine

you also see a 16x16 avatar that is not resized:

https://github.com/odoo/odoo/blob/5145ded3037980a431e12ce1da9a5ed3d6998146/addons/website_forum/views/website_forum.xml#L583

**Comment by jvm-odoo** [comment]
Should be good!

**Comment by jvm-odoo** [comment]
Indeed!

**Comment by jvm-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
