### PR TITLE
[FIX] account: avoid traceabck when generating CABA entries

### PR DESCRIPTION
**Pull request by agr-odoo**
fine tuning of 2a8f777c04bdbdce77dc44d92e099612f158cbef
The original conditional flow was altered, adding the possibility of
using n unitialized value

opw-2571629

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@oco-odoo

**Comment by oco-odoo** [comment]
That's not it. 

_create_tax_cash_basis_moves() gets the lines to consider to generate the cash basis entry from a call to _collect_tax_cash_basis_values() (https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_partial_reconcile.py#L136 ), which in turn calls a function with the same name on account.move (https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L1972). As you can see in the docstring of that function, it's only supposed to return lines that are not tax_exigible. The only legit use case for that is when the line is the base of a cash basis tax (so, tax_ids at least contains 1 tax) or a tax line from a cash basis tax (so, tax_line_id is set). So, it shouldn't be possible for any line treated in that function to be non-exigible without having tax_ids nor tax_line_id, and it's exactly what is crashing here. 

I had a look into their db. The problem is that some lines have tax_exigible = NULL. This is both weird and wrong. It seems those lines are all notes added to the invoice, so there is probably something to fix in the way notes are created. I'll keep on digging, but I'm already closing this PR.

**Comment by agr-odoo** [comment]
Actually I knew about the underlying issue but still the flow of the function may lead to a traceback so imho we could at least change to something more meaningful for the end user.
In the current state there will be a User error message about the empty move posted, but to make more explicit we could have something like

```
                    if line.tax_repartition_line_id:
                        # Tax line.

                        cb_line_vals = self._prepare_cash_basis_tax_line_vals(line, balance, amount_currency)
                        grouping_key = self._get_cash_basis_tax_line_grouping_key_from_vals(cb_line_vals)
                    elif line.tax_ids:
                        # Base line.
                        cb_line_vals = self._prepare_cash_basis_base_line_vals(line, balance, amount_currency)
                        grouping_key = self._get_cash_basis_base_line_grouping_key_from_vals(cb_line_vals)
                    else:
                        raise UserError("There is something wrong in your accounting")

```

**Comment by oco-odoo** [comment]
@agr-odoo But what would be the added value of such a message? The traceback would do the same, they'll contact support anyway. I agree it's arguable, but we usually don't add exceptions for this kind of issues. Plus, this bug has been there since 13.0, and we only notice it now, so I don't think it concerns a lot of people (and this field is bound to disappear in v15 anyway; it'll be replaced by direct SQL computation).

**Pull request closed without merging**
