### PR TITLE
[REF] mail: split @mail/model into files

### PR DESCRIPTION
**Pull request by alexkuhn**
Split `@mail/record` file into many files.
There were many cyclic dependencies, notably by storing
global state on `Record` class. To fix this issue:
- many static methods are turned into misc standalone functions,
  e.g. `isRelation`, `isRecord`, `isField`, etc.
- internal state on Record is moved to StoreInternal

Also added 3 PRs that makes some performance improvements:
- reduce reactive accesors thanks to `markRaw` internal attribute `_`.
- metadata of record fields and model fields have been turned into `Map`, to reduce amount of object allocated.

Both changes improve performance of models by around 15%: medium size populate with contacts opens messaging menu in 575ms, down from 700ms. `@mail` unit tests take 1m42s, down from 1m55s.

### CODE REVIEW

**Review by seb-odoo — APPROVED** [review]
I didn't check everything in details but ok for the ideas.

**Review by seb-odoo — APPROVED** [review]
@robodoo delegate+

Hard to review split of file line by line to ensure full correctness.
But I also prefer the result of having smaller files.
If tests pass it should be good enough to trust them.

Follow up commits are good improvements/fixes.

**Comment by alexkuhn** [comment]
@robodoo override=ci/security r+
markup for automatically markuping field with `html` option. Used for `mail.message` body which is sanitized.

**Comment by alexkuhn** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
