### PR TITLE
[FIX] website: prevent default submit

### PR DESCRIPTION
**Pull request by thle-odoo**
Steps to reproduce:
-------------------
- on ecommerce, activate "Extra Info" feature;
- go to the extra info form;
- write something for "Your Reference";
- press Enter.

Issue:
------
The Bad Request message is displayed.

Cause:
------
Pressing Enter triggers the form's default submit. To use the controller of the `/website/form/shop.sale.order` route, we need to apply the JS logic of the `s_website_form` widget (the `send` function).

Solution:
---------
Add an event for the `submit` which will prevent
the default behaviour and send the form data.

opw-3591135

### CODE REVIEW

**Comment by thle-odoo** [comment]
@rdeodoo
Thanks for your comment and your investigation.

After research, here is what could explain this behaviour:

From documentation: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission

The form on the `/shop/extra_info` page does not have an explicit submit button.
The implicit submission mechanism should therefore be taken into account:

> If the form has more than one field that blocks implicit submission, we don't submit it.

A text input is a field that blocks implicit submission.
Consequently, if there is more than one in the same form, it will be not sent.
If there is only one, we send.

Examples:
--------

When we press ENTER in the first text input of the form.

```html
<form>
    <input type="text">
</form>
```
no button --> maybe implicit submission --> less than two blocking fields --> implicit submission --> sent

```html
<form>
    <input type="text">
    <input type="text">
</form>
```
no button --> maybe implicit submission --> more than one blocking field --> no implicit submission --> not sent


```html
<form>
    <input type="text">
    <button onclick="alert('Click')">Submit</button>
</form>
```
button --> Submission explicit --> submit form via the submit button --> submission explicit via the button --> sent

```html
<form>
    <input type="text">
    <input type="text">
    <button onclick="alert('Click')">Submit</button>
</form>
```
button --> Submission explicit --> submit form via the submit button --> submission explicit via the button --> sent

**Comment by qsm-odoo** [comment]
Did not read everything here but the bug fix seems right @rdeodoo 
The real "bug" however, is that our send buttons should be of type "submit" instead of "button", in that case we would not have had that issue I think as one input or not, the browser "submit" would have simulated a submit button "click" first. In any case, even it it was, I would also listen the "submit" event, weird it's not the case already. Just need to carefully double test to be sure it's fine :grimacing:

**Comment by qsm-odoo** [comment]
Note: "s_websiote_form" in the commit message :wink:

**Review by rdeodoo — APPROVED** [review]
@robodoo r+

Thanks a lot for the investigation and link.
That was one of the missing pieces:

> For the purpose of the previous paragraph, an element is a field that blocks implicit submission of a form element if it is an input element whose form owner is that form element and whose type attribute is in one of the following states: Text, Search, Telephone, URL, Email, Password, Date, Month, Week, Time, Local Date and Time, Number

So indeed, when there is no submit button in the form and more than one blocking element, it won't auto submit on enter.
And a textarea is not considered a blocking element somehow :shrug:

**Pull request closed without merging**
