### PR TITLE
[IMP] portal: adds access_token to pager urls in portal

### PR DESCRIPTION
**Pull request by chienandalu**
A backport of 

- #76673

Done in master but which issue affects prior versions as well.

Within portal, subscriptions/sales orders presented in list view have their URL
containing the access_token as a GET param. However, when clicking on a
subscription and using the pager to navigate between records, the access_token
is not present in the URL. In order to keep consistency between the links and
views, this PR adds the access_token as a GET param in the pager as well.

task-2512070

closes odoo/odoo#76673

Related: odoo/upgrade#2752
Related: odoo/enterprise#20357
Signed-off-by: Arnaud Joset <arj@odoo.com>

TT36920 cc @Tecnativa

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@leonardopavanrocha @arj-odoo can you please check to have this patch also on v13?

**Comment by arj-odoo** [comment]
Hello @pedrobaeza @chienandalu The original PR was needed because we decided that sale.subscription records should inherit from portal.mixin. This PR came with an upgrade script to rename the uuid column into access_token and website_url into access_url. In 13.0, sale.subscription do not depends on the portal mixin. Therefore I don't see why this change would be needed :thinking:  Can you enlighten me ?

**Comment by chienandalu** [comment]
Thanks @arj-odoo Well, there's this bug with the sales portal, that can be avoided with that patch as it uses the tokenized url instead of the direct portal url. You can check it quickly on a runbot:

1. Log in with `portal` user.
2. Go to `/my/orders` (with base demo date there use to be two records for that user).
3. Click on one of them.
4. From that order navigate to the next one with the upper previous/next arrow buttons.
5. From that order, write on the chatter:

    A 403 error raises.

Quick video:
Peek 30-05-2022 16-15

**Comment by arj-odoo** [comment]
> Thanks @arj-odoo Well, there's this bug with the sales portal, that can be avoided with that patch as it uses the tokenized url instead of the direct portal url. You can check it quickly on a runbot:
> 
>     1. Log in with `portal` user.
> 
>     2. Go to `/my/orders` (with base demo date there use to be two records for that user).
> 
>     3. Click on one of them.
> 
>     4. From that order navigate to the next one with the upper previous/next arrow buttons.
> 
>     5. From that order, write on the chatter:
>        A 403 error raise
Wow, nice catch ! Indeed, this fix needs to be merged in 13.0 :-). As the reason is not only to keep consistency but also to fix this 4.3 error, could you update the commit message with your 5 steps explanations ? That will  help people to understand why this commit is needed in old versions. Thanks !

**Comment by arj-odoo** [comment]
@fw-bot up to  saas-15.2

**Comment by arj-odoo** [comment]
@fw-bot up to saas-15.1
the limit is inclusive

**Comment by chienandalu** [comment]
> Wow, nice catch ! Indeed, this fix needs to be merged in 13.0 :-). As the reason is not only to keep consistency but also to fix this 4.3 error, could you update the commit message with your 5 steps explanations ? That will help people to understand why this commit is needed in old versions. Thanks !

Done @arj-odoo :)

**Comment by arj-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
