### PR TITLE
Track cost method changes

### PR DESCRIPTION
**Pull request by ajo-odoo**
Description of the issue/feature this PR addresses:
Task: https://www.odoo.com/web?#id=1886343&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720
PAD: https://pad.odoo.com/p/r.a75c690f92acfb2e7315b6ede8fa4a94
Current behavior before PR:

Desired behavior after PR is merged:
    - Log a note in the chatter when changing the product category of the product
    - Add a chatter on the product category 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jir-odoo** [comment]
LGTM

**Comment by sle-odoo** [comment]
according to #27988 the track_visibility value should be set to True, could you adapt that?

**Comment by sle-odoo** [comment]
also we talked about the valuation propery fields in multi company environments, i guess we should wait for 1903115 to handle that don't you think?

**Comment by rdeodoo** [comment]
> Thank you for your work, unfortunately I'll have to cancel this task. As we will implement inventory valuation a bit differently, those changes will be tracked via an intermediate object.

Reopen if I am wrong

**Pull request closed without merging**
