### PR TITLE
[FIX] Remove buggy calls to `.with_context()`

### PR DESCRIPTION
**Pull request by yajo**
When `.with_context()` is called with a dictionary as 1st positional argument, contrary to what many people think, it will *replace* context instead of modifying just the keys you want.

This is a very easy way to break context in calls and create many buggy behaviors.

I left the calls that made some sense or were in tests. I replaced all others.

This should fix dozens of present & future bugs.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by sswapnesh** [comment]
Not sure If this should land in 12.0 or not  As It can break Customization if one has checked for Particular key in the context (and After this change, context will be replaced there)

**Comment by mart-e** [comment]
It LGTM but just to be sure that it was not intended to fully replace the context, lets have the dev confirms it:
@smetl for the accounting part
@tde-banana-odoo for the mail part
@sle-odoo for the logistic part
@JKE-be for the website part

Thanks all!

**Comment by sle-odoo** [comment]
seems legit but i would prefer this patch to land in in saas-12.5

**Comment by tde-banana-odoo** [comment]
Seems legit for mail part and can land in 12.

**Comment by JKE-be** [comment]
Seems legit for website part and can land in 10 ;)

**Comment by smetl** [comment]
It looks ok for the accounting part whatever the version.

**Comment by Yajo** [comment]
Some of those seem legit, but some seem bugs also. I think the corresponding @odoo members should take a look at those and enable the linter warning in runbot.

**Comment by mreficent** [comment]
It has already been ported to saas-12.5. @Yajo Could you check again in saas-12.5 if all is ok or if some new cases have to be attended?

**Comment by Yajo** [comment]
I see some uses still, but all of them seem legit or inside tests, except for this one:

https://github.com/odoo/odoo/blob/974261f7e9a27fb513e6c44538dddc740c918604/addons/website_sale_product_configurator/controllers/main.py#L31

That one "smells bad".

**Pull request closed without merging**
