### PR TITLE
13.0 dev config ui fixes for chilean loc

### PR DESCRIPTION
**Pull request by Danisan**
Description of the issue/feature this PR addresses:
The div sections are misaligned. Here we add a new div section in res config settings for l10n_cl

Desired behavior after PR is merged:
this will inherit an inside section for l10n_cl_edi in the enterprise edition and will provide a better base for adding a boolean inside this area (for 14) to allow a module_l10n_cl_edi boolean

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Danisan** [comment]
@ren-odoo please test this alone, and merge to stable separately asap, in order to get the new sections correctly.

**Comment by ren-odoo** [comment]
@jco-odoo FYI

**Comment by ren-odoo** [comment]
@Danisan let's use the other Odoo PR

**Comment by Danisan** [comment]
This is closed, replaced and unified in #55596

**Pull request closed without merging**
