### PR TITLE
[FIX] lunch: prevent error when deleting all Location records

### PR DESCRIPTION
**Pull request by vise-odoo**
**Description of the issue/feature this PR addresses:**

When all Lunch location records are deleted, the LunchLocation JS component fails to build, raising an error when accessing the Lunch App.

**Steps to Reproduce:**
- Install the `lunch` module
- Go to Lunch > Configuration > Locations
- Delete all records
- Access the Lunch App again

**Traceback:** OwlError
```
Invalid props for component 'AutoComplete': 'value' is not a string
```
This error occurs at [1], where the given props are empty.

This commit will resolve the above error by displaying a text message instead of trying to build a `Many2XAutocomplete` with empty values.

opw-4104561

[1]- https://github.com/odoo/odoo/blob/503c0d6f8fad09f5de678d8692fc283feac1b061/addons/lunch/static/src/components/lunch_dashboard.xml#L61

**Current behavior before PR:**
Without any record in the `lunch.location` model, the Lunch App cannot be accessed

**Desired behavior after PR is merged:**
Without any record in the `lunch.location` model, the Lunch App can be accessed, but a message "_No lunch locations available._" will be displayed in spite of the location.

**Screenshots**
Behavior without fix, with locations not yet deleted:
lunch locations
Behavior with fix, with all locations deleted:
No locations

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Bertrand2** [comment]
Thanks for the fix :saluting_face: After discussion with our PO @Geoffrey-GMF , the fix doesn't bring a behavior that we would want either; when no `lunch.location` exist, we should consider that food can't be delivered anywhere. The correct behavior should then be that no product is available on the first page, maybe asking to add some locations.
If possible, could you also add a small test as well?
Thanks! :smile:

**Comment by Bertrand2** [comment]
Hello @vise-odoo , any news on this? :)

**Comment by vise-odoo** [comment]
Hi @Bertrand2 , I just added 2 more commits. Here are explanations about each one of them:

**Comment by vise-odoo** [comment]
2nd commit fixes the stretching issue of the NoContent warning that is displayed when no product is available.

* In both the Kanban and List view, the NoContent element is not fully displayed:
wrongly stretched list
wrongly stretched kanban

* In my fixed environment:
fixed stretch

**Comment by vise-odoo** [comment]
The 3rd commit adds a NoContent element that is displayed when the `lunch.location` table is empty, as per your request.

New nocontent

**Review by Bertrand2 — APPROVED** [review]
LGTM! Thanks for the fix :)

**Comment by Bertrand2** [comment]
robodoo r+

**Comment by Bertrand2** [comment]
robodoo rebase-ff

**Pull request closed without merging**
