### PR TITLE
[FIX] base: no need for dynamic allocation of attribute in error

### PR DESCRIPTION
**Pull request by thni-odoo**
Description of the issue/feature this PR addresses:

We restrict the 'attr' value to 'context' in the if condition, so there is no need to dynamically pass the 'attr' value again for the error message since we do not expect a different value other than 'context'.

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by thni-odoo** [comment]
Hello @mart-e ,
A Gentle Reminder for review. If anything has to be done from my side please let me know.

**Comment by mart-e** [comment]
@thni-odoo what are you fixing exactly? Looks like code cleaning so not sure why you do that in saas-14.5

**Comment by thni-odoo** [comment]
> @thni-odoo what are you fixing exactly? Looks like code cleaning so not sure why you do that in saas-14.5 (also, runbot is super red)

It is just code cleaning and there is no specific reason for saas-14.5 changes were implemented from [14.4](https://github.com/odoo/odoo/blob/c4332db24c5070213d7259eedcee6f0bc064eed6/odoo/addons/base/models/ir_ui_view.py#L1319) to [14.5](https://github.com/odoo/odoo/blob/saas-14.5/odoo/addons/base/models/ir_ui_view.py#L1625).

**Comment by mart-e** [comment]
Sorry, I don't understand your point. We only do bugfix in stable versions. Code cleaning is for the master version.
If you are actually fixing a bug, please explain how to reproduce it.

**Comment by thni-odoo** [comment]
> Code cleaning is for the master version.

I didn't knew that thanks for the info.

**Pull request closed without merging**
