### PR TITLE
[FIX] sale: wrong format date when sending a mail for a quotation.

### PR DESCRIPTION
**Pull request by simongoffin**
opw:625594

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Set Europe / Brussels is probably not a good idea, we are not the center of the world : D.

format_tz(object.date_order, object.partner_id.tz) is enough I believe ? If the partner has no tz, the format_tz method will just leave the default timezone.

Besides, I am not even sure if the tz is actually needed: In the case of a sale order, I am not sure if the time should be in the partner timezone, or in the salesman timezone. In other words, I am not sure if the date time should be in the timezone from where the sale order is sent, or in the timezone where the sale order is received.

Nevertheless, if I am not wrong, the context of your fix is only the date time format, and not the date time zone, and this fix doesn't resolve the issue you are trying to solve, I believe. The problem is that, in French (among others), the time format is DD / MM / YYYY, while in English (US), it is MM / DD / YYYY. If the sale order is sent in French, the date time format should be in French as well. This is what you are asked to fix :).

format_tz(object.date_order, context=dict(context, lang=object.partner_id.lang)) is the fix you are looking for, isn't it ?

**Comment by simongoffin** [comment]
Jinja2 doesn't allow to use the function dict(). This is why I must write:
 ${format_tz(object.date_order, tz=user.tz, context={'lang':object.partner_id.lang})} .

**Comment by beledouxdenis** [comment]
Seems fair to me.

Change the commit message to:
[FIX] sale: format date according to partner language in SO emails

And you can merge :).

**Comment by beledouxdenis** [comment]
Closed with 9b3e6065385a7ba5f914c258cd746b028d92801d.

**Pull request closed without merging**
