### PR TITLE
[IMP] calendar: use m2o_reference on calendar.event

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Description of the issue/feature this PR addresses:

Let's make use of Many2oneReference as a better tool to link the model and the id.

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@mart-e I don't know who to ping here, can you help?

**Comment by mart-e** [comment]
> I don't know who to ping here

following the comment, @LucasLefevre can you have a look?

**Review by LucasLefevre — COMMENTED** [review]
probably a good idea indeed.
I let @arj-odoo handle the PR since he is the current responsible for `calendar`
Have a nice day :)

**Comment by arj-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
