### PR TITLE
[FIX] mail: use correct emoji for shortcode

### PR DESCRIPTION
**Pull request by mart-e**
I can't believe we have to fix this.
I am seriously disappointed by our testing team to have missed this.

this is a smiling face https://emojipedia.org/slightly-smiling-face/ 

not this https://emojipedia.org/smiling-face-with-smiling-eyes/
nor this https://emojipedia.org/grinning-face/

you do not :joy: for the emoji `:-)` either (open to dialogue for the shortcode of this one)

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
https://www.odoo.com/web#id=36898&view_type=form&model=project.task&action=333&active_id=965&menu_id=4720

**Comment by Yenthe666** [comment]
The grinning smiley is very relevant here.

**Comment by xmo-odoo** [comment]
You seem to have used U+263A WHITE SMILING FACE rather than U+1F642 SLIGHTLY SMILING FACE for ":)", was that intentional?

**Comment by jem-odoo** [comment]
How is it possible that nobody ever saw that so huge mistake ! Thanks @mart-e for taking this problem seriously ! Bisous

**Comment by mreficent** [comment]
but now the `:-)` disappears?

**Comment by mart-e** [comment]
there is already the `:)` or we could duplicate it?

**Comment by mreficent** [comment]
duplicate

**Comment by Yenthe666** [comment]
+1 for duplicate.

**Comment by mart-e** [comment]
I prefer keeping only one, adding new ones is out of the bug fix scope of this one.
Should be easily customizable with the task Thibault was pointing out (not done yet)

**Pull request merged**
