### PR TITLE
[IMP] l10n_ca: Tax report enhanced to consider Line 90 and 91, added …

### PR DESCRIPTION
**Pull request by ms-oerp**
…Exempt tax for sale and purchase

Description of the issue/feature this PR addresses:

The current GST/HST report tax report (Canada) have a missing lines for 90 and 91 as per the Canada Revenue agency Instructions of tax report

Added Exempt tax which is 0% in the Exempt category:
More info found at: https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4022/general-information-gst-hst-registrants.html#H1_106

More details for lines 90, 91, and 101: https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/complete-file-instructions.html#lines909102

Current behavior before PR:

Current Tax report missing line 90 and 91:

Desired behavior after PR is merged:

The tax report should have lines 90 and 91 and line 101 computed based on lines 90 and 91.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ms-oerp** [comment]
Hi @proose 

I would be grateful if you could review this PR.
Please feel free to reach out if you have any questions.

Thank you.

**Comment by proose** [comment]
Hi @ms-oerp,
Thank you for your contribution! I'll redirect this PR to someone who has more knowledge on Canadian localisation.

**Comment by ms-oerp** [comment]
Hi @clbr-odoo 

I would appreciate it if you could review this PR. This will help to align Odoo tax report with the CRA guidelines.

CC @proose

**Comment by clbr-odoo** [comment]
Hello @ms-oerp ,
It looks good to me from technical perspective but functionally I am unsure: it feels like from your documentation that we have implemented the "regular method" and that **choosing** to fill boxes 90 & 91 is the exception.
So I asked one of our PO to have a look, which is why it's taking a bit more time, but it's not forgotten :)
Of course if you have more insight to share it is very welcome.

**Review by clbr-odoo — APPROVED** [review]
Validated by PO in the meantime, thank you for your contribution ! :+1: 
@robodoo r+

**Comment by ms-oerp** [comment]
Thank you @clbr-odoo and @proose for your quick response and review.

**Pull request closed without merging**
