### PR TITLE
[FIX] service: --dev=reload, exclude temporary python files

### PR DESCRIPTION
**Pull request by yelizariev**
Add another suffix for temporary files.

Related: https://github.com/odoo/odoo/commit/3096d94d9bc903297ae320f3705362aba1885277

### CODE REVIEW

**Comment by yelizariev** [comment]
@odony should be ok to merge this in stable?

**Comment by yelizariev** [comment]
``.#file.py`` is emacs default style

**Comment by odony** [comment]
> @odony should be ok to merge this in stable?

Well, it's difficult to say that it is okay according to our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean). It doesn't fix any bug, it's an improvement to a feature that is only a convenience for developers. So I'd say it really belongs to `master`, or perhaps 14.0, but definitely not 12.0 (also, I hear that `(setq create-lockfiles nil)` is an option).

Also:
- `str.startswith` takes a tuple of prefixes so you can simplify the diff further
- at some point, instead of everyone adding their favorite prefix we should perhaps make this a config option with a sane default (targeting `master` gives you a nice opportunity to do that immediately ;-))
- original commit 3096d94 did not do a good job of documenting why the fix was actually needed to improve developer life (some obscure reference to a missing file error). Can you do better? :p
- any particular reason this branch is not in ~odoo-dev/odoo?

**Comment by yelizariev** [comment]
@odony, I'd make a PR to master then.

It's not odoo-dev/odoo, because I made the PR via github UI and it always use personal fork ([or create new branch in odoo/odoo if I have write access](https://github.com/odoo/odoo/pull/59506#issuecomment-706086913))

**Pull request closed without merging**
