### PR TITLE
[FIX] base: Fix in the states of Uruguay

### PR DESCRIPTION
**Pull request by mem-adhoc**
Description of the issue/feature this PR addresses:
It is not necessary to put the UY- at the beginning because they only appear if the country is Uruguay
Task: 88
Task in adhoc: 6022

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aliyatastemirova** [comment]
hello, thank you for your pr
It seems that these codes conform to the ISO codes for Uruguay states
https://www.iso.org/obp/ui/#iso:code:3166:UY
so in my opinion, it would be better to keep them as they are

**Comment by fvz-odoo** [comment]
Hello @aliyatastemirova 

The problem is that if we leave them like that we would have problems with the shipping integrators. @mial-odoo could you elaborate on whet the problem is if we leave Uruguay states with the UY- at the beginning?

Cheers!

Fernando

@ren-odoo @zaoral

**Comment by mial-odoo** [comment]
> Hello @aliyatastemirova
> 
> The problem is that if we leave them like that we would have problems with the shipping integrators. @mial-odoo could you elaborate on whatt the problem is if we leave Uruguay states with the UY- at the beginning?
> 
> Cheers!
> 
> Fernando
> 
> @ren-odoo @zaoral

Hey, we are trying to use the standarized state codes, but most countries have their local codes, while the idea of using an ISO code is great, no other country has this. For example I checked MX and BR and both have the country prefix on the list given https://www.iso.org/obp/ui/#iso:code:3166:BR
However this makes the standarization of the state codes even worse because each country is following different rules.
About 80% of our res.country.state state codes are in line with the ISO but don't have the prefix.

While we could call this non-important the thing is that we are developing a delivery solution that works across LATAM, the problem is that state codes are not the same on some countries, and we are trying to homogenize them. Some can't be modified because they are used by their localizations but in UY we don't need them so we might as well keep them the same.
Otherwise we would have to code an exception for addresses in UY.

You can see a clear example here https://drive.google.com/file/d/1lNAjrvFA0Q4L9JquC_VOOWNOZ9GdfnNB/view
All state codes in the US and CA are also like this, UY is the only exception.

**Comment by fvz-odoo** [comment]
Hello @aliyatastemirova were you able to check @mial-odoo's comment?

Let us know.

Cheers!

Fernando

@zaoral

**Comment by aliyatastemirova** [comment]
seems that it should be ok to do that indeed :slightly_smiling_face: 
@mem-adhoc could you please rebase?

**Comment by mem-adhoc** [comment]
@aliyatastemirova Hi!!
I did the rebase that you asked me for!
greetings!

**Comment by aliyatastemirova** [comment]
robodoo r+

**Pull request closed without merging**
