### PR TITLE
[FIX] Membership search by name or email

### PR DESCRIPTION
**Pull request by antespi**
Fix for issue https://github.com/odoo/odoo/issues/6703

Adds a search field name for searching by partner display_name, name or email

### CODE REVIEW

**Comment by antespi** [comment]
It's has been fixed by @beleduxdenis at https://github.com/odoo/odoo/commit/d566558a6cec082d4b191e4446741a28ec4b5bfb
Cc @pedrobaeza, maybe this will conflict with ocb

**Comment by StefanRijnhart** [comment]
Hi @antespi, I am currently resolving the conflict. I am taking the Odoo version https://github.com/odoo/odoo/commit/d566558a6cec082d4b191e4446741a28ec4b5bfb, which means that your additional search by email is discarded. If you think the new behaviour is a bug, please propose new PRs to Odoo and OCB.

**Comment by StefanRijnhart** [comment]
https://github.com/OCA/OCB/wiki/8.0-2015-06-17

**Comment by antespi** [comment]
@StefanRijnhart, yes you're rigth, thanks
This behaviour is rigth too. If any user asks for searching by email too, as defined in Sales > Customers, i'll do the PR to Odoo an OCB. By now i'll focus in other issues

**Comment by StefanRijnhart** [comment]
Thanks for confirming @antespi!

**Pull request closed without merging**
