### PR TITLE
[FIX] l10n_{ar,br}_website_sale: cannot edit address

### PR DESCRIPTION
**Pull request by agr-odoo**
- Change the company of the first website to the localized company
- Open web shop as public user
- Make a purchase
- Checkout and fill the address
- Edit the address
- Confirm

Issue: Traceback will raise because of the missing localization fields

opw-4232531

### CODE REVIEW

**Comment by agr-odoo** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
@fvz-odoo It would not be a bad idea to test for PE as well.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by fvz-odoo** [comment]
> @fvz-odoo It would not be a bad idea to test for PE as well.

Hi @jco-odoo 

Indeed, I just tested and once I try to set the ID type, I get this traceback...
Screenshot 2024-10-31 at 9 50 08 AM

If I just cancel, it let's me go through and if I set the country to Peru, the new field are correctly added and I can follow the process without any problems.

So, if we just fix the above mentioned traceback, we're good.

Thanks!

Fernando

**Pull request closed without merging**
