### PR TITLE
[FIX] models: forbid model changes on xmlid

### PR DESCRIPTION
**Pull request by flvr-odoo**
Backport of #83422

### CODE REVIEW

**Comment by flvr-odoo** [comment]
@fw-bot up to saas-15.2

**Comment by flvr-odoo** [comment]
@fw-bot up to saas-15.1

**Comment by flvr-odoo** [comment]
@fw-bot up to saas-15.0

**Comment by odony** [comment]
@robodoo delegate+

**Comment by flvr-odoo** [comment]
robodoo r+

**Pull request closed without merging**
