### PR TITLE
[FIX] l10n_es: fix usage of old(unknown) fields for tax template records

### PR DESCRIPTION
**Pull request by rgo-odoo**
these fields were added by commit 6c22c19086b01b0fc3b20c911408cef5fd8b3cdb

### CODE REVIEW

**Comment by rgo-odoo** [comment]
@jco-odoo

**Comment by rgo-odoo** [comment]
@jco-odoo this small fix targets warnings thrown with nightly l10n builds, should be quick to review. Thanks.

**Comment by jco-odoo** [comment]
@fw-bot ignore

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
Thanks, @rgo-odoo !

**Pull request closed without merging**
