### PR TITLE
[IMP] hr_timesheet,project: refactor 'planned_hours' field

### PR DESCRIPTION
**Pull request by hiroh-odoo**
Before this commit 'project.task' model 'planned_hours' field is inconsistent to the 'allocated_hours' field.

After this commit rename the 'planned_hours' to 'allocated_hours' and related string change to 'Allocated Time'.

task-3231680

### CODE REVIEW

**Review by MissingNoShiny — COMMENTED** [review]
LGTM, thanks for your work :slightly_smiling_face:

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work. 🙂

**Comment by xavierbol** [comment]
It seems you have some conflicts, can you resolve the conflicts? Thanks in advance! 🙂

**Comment by xavierbol** [comment]
The runbot does not seem to be happy, can you check?

**Review by xavierbol — APPROVED** [review]
LGTM, thanks again for your work. 🙂 

robodoo r+

**Comment by xavierbol** [comment]
robodoo r+

**Review by xavierbol — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
