### PR TITLE
[IMP] Documentation: Added note about one2many and many2many limitations in onchange method

### PR DESCRIPTION
**Pull request by ryanc-me**
Currently, it is not possible for a one2many or many2many field to edit it-self from within an onchange method (confirmed by #2693 and #10557). This PR adds a note about this quirk to the ORM documentation page.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MGinshe** [comment]
This is my first PR, and I'm a little new to this side of Git. Should I create additional PRs for each version (10.0, 9.0, and 8.0)?

**Comment by Elkasitu** [comment]
@MGinshe You can target 10.0 (9.0 is in EOL and 8.0 is unsupported) and it will be forwar-ported to 11.0 and subsequent versions.

It seems there is still an issue with the CLA:

* Your CLA is signed for the email `admin@ryanc.me`
* Your commit was signed with the email address `MGinshe@gmail.com`

The email address in the CLA must be the same as for the commit signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by MGinshe** [comment]
Thanks for that @Elkasitu 

Do you have any idea why the CLA is failing (due to invalid encoding?). I've saved the file using UTF8, and I'm definitely not using any non-UTF8 characters...

**Comment by Elkasitu** [comment]
The CLA file is in `US-ASCII` encoding

**Comment by MGinshe** [comment]
@Elkasitu This is (apparently) beyond my understanding of UTF-8. 

So far I've tried:
- Saving the file explicitly as `UTF-8` in both Sublime Text and Atom
- Saving in Sublime Text, with _and_ without BOM
- Disabling Git's `core.autocrlf` so that line endings are predictable
- Saving with `CRLF`, _and_ just `LF` endings
- Copying someone else's CLA, and commiting with _no_ edits

None of these attempts have worked. I'm getting an _Invalid CLA encoding (must be utf-8)_ error every time. I must be missing something obvious here. Sorry for the hassle!

**Comment by Elkasitu** [comment]
@MGinshe Oops sorry, seems like an issue on our end, you'll have to rebase your PR to the latest revision of the 11.0 branch, it was fixed a couple of days ago but since your PR is from way before it still has the bug in it :^)

Sorry for the confusion.

**Comment by MGinshe** [comment]
Hooray! Looks like it's working now :-)

Thanks for the help @Elkasitu.

**Comment by Elkasitu** [comment]
Thank you for your contribution :)

**Pull request merged**
