### PR TITLE
[CLA] Odoo CLA signature check for Reinier Quevedo

### PR DESCRIPTION
**Pull request by rquevedo**

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by vbe-odoo** [comment]
@mart-e thanks for merging, do you know what failed?
I see `ci/upgrade_enterprise` red, but not sure if it is related to this PR.
Thanks.
cc' @rquevedo

**Comment by mart-e** [comment]
@rquevedo your PR was probably too old, I have rebased it and it looks good now

**Comment by rquevedo** [comment]
> @rquevedo your PR was probably too old, I have rebased it and it looks good now

Hi @mart-e,

Is there any particular reason why @robodoo closed this PR without merging?

**Comment by vbe-odoo** [comment]
@rquevedo I think it was merged, here I can see the commit of the temporary delopoyed change:
https://github.com/odoo/odoo/commit/9da3ec8ed663b0fad151ffb1eb4c236656502df6

You may need to rebase the PR https://github.com/odoo/enterprise/pull/68468 to see this change and have the test `legal/cla` green

**Comment by rquevedo** [comment]
> @rquevedo I think it was merged, here I can see the commit of the temporary delopoyed change: [9da3ec8](https://github.com/odoo/odoo/commit/9da3ec8ed663b0fad151ffb1eb4c236656502df6)
> 
> You may need to rebase the PR [odoo/enterprise#68468](https://github.com/odoo/enterprise/pull/68468) to see this change and have the test `legal/cla` green

Okay, I hadn't realized. Thank you.

**Pull request closed without merging**
