### PR TITLE
[FIX] loyalty: add description field to reward form for gift cards

### PR DESCRIPTION
**Pull request by ryce-odoo**
Gift cards would have a description in the original language of the
creator and could never be changed.

Adds the description field to the form view of the loyalty rewards even
for gift cards and ewallet programs.

opw-4177262

### CODE REVIEW

**Review by anko-odoo — DISMISSED** [review]
Hello, please add upgrade script and take care of tour test that is not passing anymore.

**Comment by ryce-odoo** [comment]
Hey @anko-odoo 

I was finally revisiting this PR after being caught up in other things and I found that my old approach would not work in other flows with non gift card and ewallet loyalty rewards. Changing the description field to be editable seems to be a better option that is less intrusive and will still allow translations to be set in other languages. Can you take a look at this for me? I noticed that you were the one that made the change to hide these in gift card and ewallet in the first place, so maybe there is some reason that this should be hidden that I missed.

**Review by anko-odoo — APPROVED** [review]
LGTM, please rebase.

**Comment by ryce-odoo** [comment]
Hey @anko-odoo 

rebased and everything looks good

**Review by Demesmaeker — COMMENTED** [review]
Hello @ryce-odoo 

Is there a reason why the discount product now needs to be visible too? I can understand why for the description, but why not move the invisible to the `discount_line_product_id` instead?

Have a nice day =]

**Comment by anko-odoo** [comment]
@Demesmaeker I am not ryce, but I did some digging, but if user would like to create a different values of gift cards, eg. 50, 100, 150, it needs to have different products AFAIC.

**Review by Demesmaeker — APPROVED** [review]
Ok, fine by me then ^^
@robodoo r+

**Pull request closed without merging**
