### PR TITLE
[FIX] point_of_sale: discount applied twice

### PR DESCRIPTION
**Pull request by mgh-odoo**
Task: https://www.odoo.com/web#id=1978564&model=project.task&menu_id=4720
Pad: https://pad.odoo.com/p/r.a87296c7c2f933c92fde0cb1f8c18645

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by switch87** [comment]
@pimodoo ready for merge

**Comment by KangOl** [comment]
@robodoo r-

saas~12.1 is end of life.
target saas~12.2

**Comment by pimodoo** [comment]
robodoo r+

**Comment by pimodoo** [comment]
robodoo r+ rebase-ff

**Comment by switch87** [comment]
@pimodoo we are with 4 in the team + some people helping us part-time, so lets follow the workflow and always ask someone else from the team to check the changes before self-merging.

**Comment by switch87** [comment]
retargeted on saas-12.2 in pr: https://github.com/odoo/odoo/pull/34054

**Comment by KangOl** [comment]
Can you please rebase on saas-12.2?

**Comment by pimodoo** [comment]
@KangOl it's done, but we have found other bug, so it is not ready to be merged

**Comment by mgh-odoo** [comment]
Merged here https://github.com/odoo/odoo/pull/34278

**Pull request closed without merging**
