### PR TITLE
[FIX] purchase: codesmell on tax onchange compute

### PR DESCRIPTION
**Pull request by blaggacao**
Rebased on master as per: https://github.com/odoo/odoo/issues/21654#issuecomment-369258583
Authorized: https://github.com/odoo/odoo/issues/21654#issuecomment-369258583

**Description of the issue/feature this PR addresses:**
- Code smell made it very complicated to cleanly override respective computation method in custom modules
- Unverified: It smells like both implementations actually diverge.

**Current behavior before PR:**
- No clean inheritance in custom modules
- Code smell, that smells.

**Desired behavior after PR is merged:**
- Fresh air
- Clean inheritance

**Note:** Please do not close, even if not immediately accepted (`wishlist` tag). This PR is meant to be carried along and actively maintained, until this semantic will be completed this way or another.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@xoe-labs

### CODE REVIEW

**Comment by blaggacao** [comment]
@qdp-odoo Could you have a quick look at my argumentation? Indeed, this fix was done to be able to cleanly override, but maybe I'm heading in a completely wrong direction here?
/cc @Deiber

**Comment by blaggacao** [comment]
For reference, current implementation on the line (proxied through the onchange method on the order) is here: 
https://github.com/odoo/odoo/blob/44d11fe7771265ea88b299c722ff4cc00e349394/addons/purchase/models/purchase.py#L497-L502

**Comment by qdp-odoo** [comment]
I agree on the principle, but the good code to keep is probably the one in the product onchange (much more used). So you'd need to move it in the compute_tax_id() function

the commit message should also be more explicit.

**Comment by blaggacao** [comment]
Is the `SUPERUSER_ID` overe there still needed now that we have `__system__`? - I'll clean up in a second commit for you to choose.

**Comment by blaggacao** [comment]
Don't know, but it makes more sense to me to filter by the company, if it's set.

**Comment by blaggacao** [comment]
```python
taxes = line.product_id.supplier_taxes_id.filtered(lambda r: not line.company_id or r.company_id == line.company_id)
            line.taxes_id = fpos.map_tax(taxes, line.product_id, line.order_id.partner_id) if fpos else taxes
```

vs
```python

        if self.env.uid == SUPERUSER_ID:
            company_id = self.env.company.id
            self.taxes_id = fpos.map_tax(self.product_id.supplier_taxes_id.filtered(lambda r: r.company_id.id == company_id))
        else:
            self.taxes_id = fpos.map_tax(self.product_id.supplier_taxes_id)
```


Also:
```python
fpos = line.order_id.fiscal_position_id or line.order_id.partner_id.property_account_position_id
```
vs
```python
fpos = self.order_id.fiscal_position_id
```

The former in each case looks a lot more sensible. Where you checking if I paid attention? :wink:

**Comment by qdp-odoo** [comment]
> ```python
> taxes = line.product_id.supplier_taxes_id.filtered(lambda r: not line.company_id or r.company_id == line.company_id)
> line.taxes_id = fpos.map_tax(taxes, line.product_id, line.order_id.partner_id) if fpos else taxes
> ```
> 
> vs
> 
> ```python
> if self.env.uid == SUPERUSER_ID:
>     company_id = self.env.company.id
>     line.taxes_id = fpos.map_tax(self.product_id.supplier_taxes_id.filtered(lambda r: r.company_id.id == company_id))
> else:
>     line.taxes_id = fpos.map_tax(self.product_id.supplier_taxes_id)
> ```
> 
> Also:
> 
> ```python
> fpos = line.order_id.fiscal_position_id or line.order_id.partner_id.property_account_position_id
> ```
> 
> vs
> 
> ```python
> fpos = line.order_id.fiscal_position_id
> ```
> 
> The former in each case looks a lot more sensible. Where you checking if I paid attention?


probably, the good solution is 

```python
# allow to remove fiscal position set on the partner
fpos = line.order_id.fiscal_position_id
# always filter on the company, but no specific check on the super user
company_id = self.company_id or self.env.company.id
taxes = self.product_id.supplier_taxes_id.filtered(lambda r: r.company_id.id == company_id)
line.taxes_id = fpos.map_tax(taxes) if fpos else taxes
```

**Comment by mart-e** [comment]
The diff is empty now, I guess it is no longer relevant.

**Pull request closed without merging**
