### PR TITLE
[FIX][14.0] calendar: fix can't group events by store fields

### PR DESCRIPTION
**Pull request by tranngocson1996**
This PR
-------
Fix can't group events by store fields

Video report bug:

https://user-images.githubusercontent.com/26604325/157814463-56ca2049-ce89-456a-bf57-20fb768eed89.mp4

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tranngocson1996** [comment]
@arj-odoo plz review !!!

**Comment by arj-odoo** [comment]
Hello, this limitation on group by was created because some events are private and we can't let the user get information on these events through the read_group method. Allowing this would allow user to gather information about events he should not have information. We know that this behavior is quite restrictive and we improved it in v15.0. You can look at the code but basically, if the user uses a private field in the group by, we exclude the private events from the read_group. Your solution is not right because it brings the default behavior and it allows information harvesting by choosing carefully the field. Your solution is also quite complex for the result you expect: allow read_group of any event. We can't merge your PR because it too permissive so I take the liberty to close it but you can adapt the V15.0 code in your instance if you like or migrate to V15.0. Thanks for your proposition and don't hesitate if you have any question :-).

**Comment by tranngocson1996** [comment]
@arj-odoo Thank for reply.
I know you're using the private field read group, but when I add a m2o field to the calendar.event model, it also doesn't group by that field. Despite the fact that it is not a private field. So is that a bug?

**Comment by arj-odoo** [comment]
If you do a customization where you add a m2o fields and if you consider this field to be public, you need to declare it as such. The easiest solution is to override like this:
```py
@api.model
def _get_public_fields(self)
    public_fields = super()._get_public_fields()
    public_fields.add('custom_field_id')
   return public_fields
```
Your solution considers every many2one field as public. It is not acceptable as another person could consider that another m2o field is private. The best solution is to whitelist your custom field.

**Comment by tranngocson1996** [comment]
@arj-odoo I've done that already, but it's really inconvenient to add m2o field. Each time you add a field, you must override the function (If in many modules).
So i want to solve the root of the problem.

**Comment by arj-odoo** [comment]
Your solution don't fix the root of the problem. You consider every m2o field public, which is a solution that works for you but not other implementation. As you already have a customization, just create a small module that implement this change and make all your modules depends on it. That way, you code only once and it works for all your cases ;-).

**Comment by tranngocson1996** [comment]
@arj-odoo OK I think it will still cause that inconvenience. But since you said that, I agree
:D.
Thank for dicuss

**Pull request closed without merging**
