### PR TITLE
[FIX] l10n_ar: AFIP group on invoices

### PR DESCRIPTION
**Pull request by pablohmontenegro**
This commit makes AFIP group invisible in non-Argentinean Companies.

### CODE REVIEW

**Comment by vbe-odoo** [comment]
@pablohmontenegro thanks for the PR.
FUN tests was done and LGTM, ready for tech review @jco-odoo 
cc' @fvz-odoo @ren-odoo

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by vbe-odoo** [comment]
Hi @pablohmontenegro and/or @jco-odoo can you help with the FW-P from this PR:
https://github.com/odoo/odoo/pull/99332
https://github.com/odoo/odoo/pull/99339

Not sure who can make the changes - if needed - to merge this.
Let me know if there's a FUN test needed as well.

Thanks!
cc' @fvz-odoo @ren-odoo @zaoral

**Comment by pablohmontenegro** [comment]
Hi @vbe-odoo I received this comment by robodoo when I want to make @fw-bot r+ (https://github.com/odoo/odoo/pull/99332
https://github.com/odoo/odoo/pull/99339)
"I'm sorry, @pablohmontenegro: I must know your email before you can review PRs. Please contact an administrator."

**Comment by vbe-odoo** [comment]
Hello @pablohmontenegro Oh I see, thanks for the heads up on this.
@jco-odoo do you know if only you can make the r+ here?
Thanks!
BE
cc' @ren-odoo @fvz-odoo @zaoral

**Pull request closed without merging**
