### PR TITLE
[FIX] web: assertion error when save after speed multi delete in o2m

### PR DESCRIPTION
**Pull request by Gorash**
To reproduce use a form view with a one2many editable list and create a lot of lines. Then click a few times quickly on the delete.
If the user click at least two times on delete of a same record, the dataset create a delete command with a virtual id because "to_create" doesn't contains the virtual id of the record deleted previously.

E.g.: create a "Customer Payments" and select a "Customer" and "Payment Method" who generate a lot of "Credits" lines.

### CODE REVIEW

**Comment by spadae22** [comment]
+1

**Comment by beledouxdenis** [comment]
Two little notes: 
 - This patch works, and is even right to me. Nevertheless, I am not sure this is - the best - patch: It looks like this issue happens only because of the multiple calls to the `onchange ` each time you remove a line.  For instance, I wasn't able to have this error when doing the same thing on a sale order line. Therefore, I believe this issue is actually due to either a race condition within the `onchanges`, or because we do not disable this unlink button during the call to the `onchange` method, and therefore the user is able to hit multiple times on the button while it should not be the case.
   Nevertheless, I do not believe this issue worth the time spent on the investigation, and I therefore believe this patch is enough, hoping it won't break anything else.
- This proposal is associated to a ticket in our support system, and to an issue in our Github repository. Therefore, your commit message should contain, at the end of the message:
```
Fixes #8615
opw:651729
``` 
This is only for clarity, in case we need to know more about why this revision was done, if we want more details about the actual issue the user had.

If you want to investigate a little further, please do but do not spent too much time on this, it doesn't worth more than half a day. Once the commit message altered with my above remarks, you can merge ;).

Thanks :).

**Comment by spadae22** [comment]
Ok, we have many returns so we will noticed the change, good or bad. We keep up updated

**Comment by Gorash** [comment]
I can fix this in the list editable with a check if the record exist in the dataset but I prefere fix in low level because the bug appear with the implementation of the unlink because the method add into to_delete only if it's not in to_create.
I'm going to change the method to don't trigger the onchange if the record is already deleted.

**Comment by beledouxdenis** [comment]
Don't feel forced: This fix is enough to me.

**Pull request closed without merging**
