### PR TITLE
[FIX] #15445 - Mass mails not sent when filter applied in different language than user

### PR DESCRIPTION
**Pull request by danimaribeiro**
Apply the lang from the user who confirmed the mass mailing.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We already detected this and propose #15467, but it was blocked by @odony. Maybe this can be a recall for a definitive solution.

**Comment by mart-e** [comment]
Is this still necessary after 6504bce60eb507af82707efa4c495943a5e9bc9a (as #15467 has been closed)?

**Comment by pedrobaeza** [comment]
I don't think so.

**Comment by danimaribeiro** [comment]
@mart-e I don't see the fix in version 11.0.
Will it be forwarded from another version?

**Comment by mart-e** [comment]
@danimaribeiro yes, we do it from time to time, it may take a few days to go all the way from 9.0 to master.

**Pull request closed without merging**
