### PR TITLE
[IMP] point_of_sale: responsive product screen

### PR DESCRIPTION
**Pull request by pimodoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
If it helps, I want to highlight that review screen is not fully responsive, keeping a minimum horizontal scroll bar:

Selección_029

**Comment by pimodoo** [comment]
@pedrobaeza thanks for your feedback, it comes from the numpas which is too large, we'll check if we can reduce some buttons to fit your screen

**Comment by pimodoo** [comment]
@robodoo r+

**Comment by pimodoo** [comment]
@robodoo r-

**Comment by pimodoo** [comment]
@robodoo r+

**Comment by pedrobaeza** [comment]
> it comes from the numpas which is too large, we'll check if we can reduce some buttons to fit your screen

OK, thanks for telling me

**Pull request closed without merging**
