### PR TITLE
11.0 posbox fixes lpe

### PR DESCRIPTION
**Pull request by kebeclibre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
@jco-odoo 
@qle-odoo 
There still might have errors of that type left, would you mind give it yet another round of tests ?

**Comment by jco-odoo** [comment]
I guess these are the most important ones.  Might have wanted to clean too much.  There is another place where this North token is used.  Although it is in bytes over there, it would not be bad to test for sure.

**Comment by jco-odoo** [comment]
It probably works with the newer one.  I just continued to use the old one
because I saw a warning with langid.

**Comment by kebeclibre** [comment]
@jco-odoo 
@qle-odoo 
When printing the status ticket, at posbox launch, 
If I place a print in printers.py@_raw
I get:
<class 'bytes'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'bytes'>
<class 'bytes'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'str'>
<class 'str'>

I think this function should be clearer on what string types it accepts, for code clarity
Eventhough pyusb doesn't have a clear cut recommandation

**Comment by kebeclibre** [comment]
opw fixed at 21064c7de8867c9217d274cb83ff589c8ebcac75

I'm not merging the rest as the support of pyusb > b1 may need more investigation
Which should be done, as v11.0 Odoo standard requires pyusb 1.0.0

**Pull request closed without merging**
