### PR TITLE
[FIX] resource: Rename 'Evening' into 'Afternoon' in default attendances

### PR DESCRIPTION
**Pull request by tivisse**
Evening is not the common way to describe the second shift of the day.

Co-authored-by: Cas Vissers <c.vissers@brahoo.nl>

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo r+

**Comment by seb-odoo** [comment]
robodoo failed here?

**Comment by tivisse** [comment]
@robodoo r+ you son of a bot.

**Pull request closed without merging**
