### PR TITLE
Cla colinliz

### PR DESCRIPTION
**Pull request by Colinliz**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by GoodERPJeff** [comment]
@mart-e please help our developer join our contribution team

**Comment by mart-e** [comment]
Hi,

Could you instead add your email to the existing [inspur CLA](https://raw.githubusercontent.com/odoo/odoo/12.0/doc/cla/corporate/inspur.md)?
Thanks

**Comment by Colinliz** [comment]
Thank you i have added my email to the existing inspur CLA

**Comment by mart-e** [comment]
Thank you, I squashed the commits and added your github account to the signature to be complete.
It looks good now :+1: 

@robodoo r+

**Pull request closed without merging**
