### PR TITLE
[FIX] cloc: fix count of studio field + exclude sa

### PR DESCRIPTION
**Pull request by tfr-odoo**
This commit fix 3 problems

Don't count studio field
------------------------

the commit https://github.com/odoo/odoo/commit/75b8c4eb1ed6e44f427886eea06ad216995e16c8
was supposed to stop counting count field generate by addons a smart
button with studio.

It works fine when base import module is not installed which is never
the case.

When base_import_module the field is counted as a field that belong
to a imported module installed : studio_customization

studio_customization should not be counted as an imported module
installed

Count Field with standard xml_id
--------------------------------

With https://github.com/odoo/odoo/commit/9afce4805fc8bac45fdba817488aa867fddff69b
Each manual can end up with an xml_id from a standard module:
the original module of the model

A standard module should never create a manual field so we can consider
they should be counted unless they match the criteria of the first
problem

If a field has a standard module xml_id and no other the module
should be odoo/studio and not the name of the standard module

Make possible to exclude some db record from cloc
-------------------------------------------------
It's possible to exclude some file in python module
but it's not possible to exclude some field or SA in
the database from the count

Make it possible if they are link to an xml_id
from the module `__cloc_exclude__`

The exclude record will be shown in cloc report with
the verbose mode

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tfr-odoo** [comment]
@robodoo r+

**Comment by tfr-odoo** [comment]
@erl-odoo @sea-odoo @blouk @mva-odoo FYI

**Comment by KangOl** [comment]
I don't see the "Misc" part.

**Comment by KangOl** [comment]
@robodoo override=ci/style
Reason: `print` call in CLI command.

@robodoo r+

**Comment by KangOl** [comment]
@robodoo r+

**Pull request closed without merging**
