### PR TITLE
[REV][FIX] account,web: specify viewID when redirecting …

### PR DESCRIPTION
**Pull request by agr-odoo**
The updated code of the original PR seems to be lost, manually fixing
This reverts commit 03f95d1 and add the correct fix

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@nle-odoo

**Comment by nle-odoo** [comment]
robodoo r-

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by nle-odoo** [comment]
robodoo rebase-ff

**Pull request closed without merging**
