### PR TITLE
[IMP] base: Allow to set private addresses for contacts without company

### PR DESCRIPTION
**Pull request by yajo**
Without this patch, we could not benefit from https://github.com/odoo/odoo/pull/24891 for partners that have no parent company.

Now, it's possible.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa @rafaelbn

### CODE REVIEW

**Comment by rafaelbn** [comment]
OPW #1944234

:+1:

**Comment by mart-e** [comment]
Hi,

Why not adding a private address on a partner without company?
@tivisse stop me if I ma wrong but this is the whole point of the feature at #24891, you can add a private address, even on a contact. This way you have a "public" and "private" part for the partner.

**Comment by tivisse** [comment]
This modification has been introduced at this revision: https://github.com/odoo/odoo/commit/51d8cfae05361cdbcd2edb148836ef323ddd8bac

I think that before it was hidden for companies, now it's hidden for partner without parents.

Modifying the attrs instead of removing it completely seems to be a better solution to me.

Thanks.

**Comment by Yajo** [comment]
> Modifying the attrs instead of removing it completely seems to be a better solution to me.

What modification do you want? I don't get it. :confused:

**Comment by Yajo** [comment]
Any updates please?

**Comment by Yajo** [comment]
With b6193a6b8d569d9d3a9fb4abe1590012782d03c2 in master, now this one is much harder to achieve. :thinking: 

So what should a user do if he has a contact with a private address that doesn't belong to a company?

**Comment by tivisse** [comment]
Could be done in saas-12.5 IMO

**Comment by mart-e** [comment]
Sorry for the late reply. If you rebase, it is ok for me to be merged :+1:

**Comment by pedrobaeza** [comment]
Should we target to saas-12.5 then as well?

**Comment by tivisse** [comment]
Yup, to be sure it's present in 13.0 ;)

**Comment by Yajo** [comment]
Rebased and retargeted. I changed the patch a little bit because I think that if we're making the address type visible always, then the address label has to adapt accordingly always too.

**Comment by pedrobaeza** [comment]
Merged in  #36701

**Pull request closed without merging**
