### PR TITLE
[IMP] mrp: work orders planning

### PR DESCRIPTION
**Pull request by kirti-c**
This PR introduce:
- State on kanban cards
- Do not allow a start date greater then a stop date.

The purpose and details are explain in each specific commit

Task ID -1838642
Pad - https://pad.odoo.com/p/r.68c799c9a80a18157eefebc39452f311

### CODE REVIEW

**Comment by amoyaux** [comment]
Hey @kic-odoo I just modified the color in order to be consistent with stock picking state. I think you could split the condition on write in 2 parts. It does not make sense to write on a done workorder even for something else than the date.

**Comment by amoyaux** [comment]
@sle-odoo rdy to r+

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
robodoo rebase-merge retry

**Pull request closed without merging**
