### PR TITLE
[ADD] new option --test=SPEC to enable a subset of tests

### PR DESCRIPTION
**Pull request by rco-odoo**
The possible values for --test=SPEC are comma-separated lists of:
- yaml: Yaml tests only
- python: server-side unit tests
- web: web client tests
- website: website tests

Special case: --test=full is equivalent to --test=yaml,python,web,website

Add categories 'python', 'web' and 'website' on existing tests.

### CODE REVIEW

**Comment by rco-odoo** [comment]
@KangOl can you review this one?  Thanks!

**Comment by xmo-odoo** [comment]
That (and more) would be covered in a non-adhoc manner by #7759 if anyone cared for it.

**Comment by KangOl** [comment]
So better merge #7759

**Comment by rco-odoo** [comment]
We shall better merge #7759.

**Pull request closed without merging**
