### PR TITLE
[IMP] Update underscore and underscore.string

### PR DESCRIPTION
**Pull request by yajo**
Modern thingies! :tada:

It's been too much time without https://github.com/jashkenas/underscore/pull/2494.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by mart-e** [comment]
@VincentSchippefilt is this ok for you?
- underscore.js: 1.8.2 -> 1.9.1
- underscore.string.js: 2.3.2 -> 3.3.4

**Comment by Yajo** [comment]
Any news on this?

**Comment by VincentSchippefilt** [comment]
It's not a priority for me to make this update, especially if there are breaking changes. Can you make a green build and/or argument about why you want to update to newer version ?
Maybe mentioning the breaking changes and how to adapt them in the PR message would be nice too, so the rest of the community knows how to update their modules.

**Comment by Yajo** [comment]
> Can you [...] argument about why you want to update to newer version ?

One of the ugliest parts of JS is the deep attribute getting system:

```js
>> var a = {}
undefined
>> a.b
undefined
>> a.b.c
TypeError: a.b is undefined
```

If you need to obtain `a.b.c`, you cannot rely on a `if` nor a `try...catch`; only on a combination of both.

This new version of underscore includes https://github.com/jashkenas/underscore/pull/2494, as explained above. It workarounds that part. I guess there must be more new things, but that's the main one I was interested in. Since it's a crucial lib in odoo development, I think that having an updated version is a good thing. We still have a release from 2015 here.


> Can you make a green build [...] ? [...] Maybe mentioning the breaking changes and how to adapt them in the PR message would be nice too, so the rest of the community knows how to update their modules.

Yes, as long as I get your commitment on that it will surely be merged once green.

**Comment by VincentSchippefilt** [comment]
unless there is a very good reason not to merge it, like a measurable performance impact or simply something broken, I will merge it.

**Comment by Yajo** [comment]
Cool, then set this as WIP for now please. Thanks!

**Comment by Yajo** [comment]
This is basically done.

There's only 1 test failing, but I think it's due to some strange practice that was working before for some obscure reason.

It seems that in `notification.js`, when a notification is created, it is shown and then hidden in a fraction of second, and it is done in a way that `toast.js` is not able to later access some internal property.

I think this is a design flaw more than a bug in the upgrade of underscore, but I'm unable to debug more deeply... Could you lend me a hand here please?

Just go to the runbot in `/web/tests?mod=web&failfast&debug=assets` and you'll be able to see and debug the problem.

I'm not sure if modern odoo is compatible with modules the same way as underscore, underscore.string and sprintf are. If so, it would be nice to make them modules and make people add `require("underscore")` and similar stuff. My JS/Odoo level doesn't get that far, so this is how it is now:

- `_` is underscore, as before.
- `s` is underscore.string, as defined upstream now.
- `sprintf` is the replacement to `_.str.sprintf`.
- All source code updated accordingly.

**Comment by VincentSchippefilt** [comment]
@Yajo thanks, my plan is to review and merge in master just after the release of V13.

I also wonder if we should not reintroduce the links between the libs in _, _.str and _.str.sprintf to reduce the diff. I would do it in a dedicated file in /web/static/src/libs 

What do you think ?

**Comment by Yajo** [comment]
> my plan is to review and merge in master just after the release of V13

I'd love to see this in v13, but... OK :roll_eyes: 

> I also wonder if we should not reintroduce the links between the libs in _, _.str and _.str.sprintf to reduce the diff. I would do it in a dedicated file in /web/static/src/libs

Well, the diff is mostly done, and that's something you just do once and forget. However, the backwards-compatibility system must be maintained for a long time and encourages deprecated practices. I vote for the big diff.

OTOH, not sure if some of the ES pros in your team can/want, but what would be actually awesome is to make the newer versions of these 2 packages compatibles with odoo namespacing system. They are already shipped with support for ES modules, so that'd be a good thing. Not a blocker for this PR, of course, just a better improvement over this one.

**Comment by rafaelbn** [comment]
@Yajo please could you rebase? 

[Odoo Merge Sprint Salle Hocaille](https://github.com/odoo/odoo/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+involves%3Atecnativa+)

**Comment by Yajo** [comment]
Ready, thanks.

**Comment by pedrobaeza** [comment]
@Yajo it seems you need again to rebase...

@VincentSchippefilt when do you plan to work on this?

**Comment by Yajo** [comment]
Oh man not again... :man_facepalming: Rebased.

**Comment by VincentSchippefilt** [comment]
@Yajo thanks, I'm looking at it right now

**Comment by VincentSchippefilt** [comment]
So, there we are:
I have fixed all the issues I could find both on community and enterprise but there is still an issue with notification.
You can check on my branch https://github.com/odoo-dev/odoo/tree/master-underscore-update-2-vsc where I took your changes and fixed the issues in the templates (seems that qweb doesn't like when calling `sprintf` or `s.` directly, it needs `window.sprintf` and `window.s`.

After 5 days of work, I still can't make both the build green and make the notification work at the same time. I had a greed build with this commit https://github.com/odoo-dev/odoo/commit/8ce7b9b8d0c084455de9f53ede23127c9f83ec0d but it prevents the autohide to be dismissed when the mouse is hovering the notification (there is no test for that 😢) so I went back to the previous version, with work correctly, but not in the qunit tests.

I'm taking a step back for a few days. If you have some time to take a look again at the notification test, AFASK it is the last issue, both on community and enterprise.

**Comment by Yajo** [comment]
I've been trying, but I'd have to study deeply how JS is done in v13/master. I've not been able to get to any conclusion.

**Pull request closed without merging**
