### PR TITLE
[FIX] survey: ignore action call for buttons with 'button' type

### PR DESCRIPTION
**Pull request by julien-banken**
Description of the issue/feature this PR addresses:
This PR will fix an error that occurs when the user clicks on a button from a list view that is not linked to an action.

Current behavior before PR:
When the user clicks on a button from a list view, the script will call the action linked to the corresponding button. When the user clicks on a button that is not linked to an action, the script will raise an exception.

Desired behavior after PR is merged:
To solve the issue, we will add the 'disabled' property support for the buttons and we will add that property to the buttons that do not have an action. With this property, the script will bind no listener to the button and it will hence not call the listener causing the error.

task-2612033

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
And using a disabled ? We did that kind of fix somewhere, can't remember where ...

**Comment by julien-banken** [comment]
Hello @tde-banana-odoo,

I think that it is necessary to apply this fix on the JavaScript level. That way, we will not have to add a 'disable' attribute on every button that does not trigger an action.

I also assume that the disabled button will have some specific css rules that will allow the user to distinguish them from the other buttons (like a lower opacity, a 'not-allowed' cursor on hover, etc.). With this fix, the button of type "button" will have the same appearance as the other buttons. The developers can then choose whether or not the button should be disable.

**Comment by tde-banana-odoo** [comment]
Seems legit actually. Pinging @aab-odoo for his thoughts on this.

**Comment by aab-odoo** [comment]
Hello @julien-banken 

Is there another handler on your button somewhere? Or clicking on it simply has no effect? Because if it is a "fake" button, I would definitely go for a `disabled` attribute (or even another tag than `button`). If it has another handler, the event should simply be stopPropagated, s.t. we don't get into the other handler.

> That way, we will not have to add a 'disable' attribute on every button that does not trigger an action.

Indeed, but you have to add `type="button"`, so it's basically the same :D And I'm not sure it is a frequent situation.

cc @tde-banana-odoo

**Comment by julien-banken** [comment]
Hello @aab-odoo,

> "Is there another handler on your button somewhere?"

I didn't found any additional listener attached to the button.

> "Or clicking on it simply has no effect?"

For the survey module, clicking on the button should have no effect. The button is considered as a decorator.

> "Because if it is a "fake" button, I would definitely go for a disabled attribute (or even another tag than button)"

The other tags (`span`, `div`, `i`, etc) and the `disabled` attribute on the button do not seem to be supported for the tree view: The xml parser throws a `ValidationError` exception when I install the survey module.

Assuming that the `disabled` attribute on the button is supported, I'm not sure to see how it will prevent the script from propagating a `button_clicked` event that will cause the error.

see:
- https://github.com/odoo/odoo/blob/2b8d7d76adceeca16f97e394a6734bb5be633c3b/addons/web/static/src/js/views/list/list_renderer.js#L466
- https://github.com/odoo/odoo/blob/2b8d7d76adceeca16f97e394a6734bb5be633c3b/addons/web/static/src/js/views/list/list_controller.js#L33
- https://github.com/odoo/odoo/blob/2b8d7d76adceeca16f97e394a6734bb5be633c3b/addons/web/static/src/js/views/list/list_controller.js#L575

So, what would be the new logic with the `disabled` buttons ? Will it be better (shorter, simpler, safer) than that ?

cc @tde-banana-odoo

**Comment by aab-odoo** [comment]
> The other tags (`span`, `div`, `i`, etc) and the `disabled` attribute on the button do not seem to be supported for the tree view: The xml parser throws a `ValidationError` exception when I install the survey module.

It seems reasonable to add the "disabled" attribute to the list of valid attributes on the `button` tag, in common.rng.
 
> Assuming that the `disabled` attribute on the button is supported, I'm not sure to see how it will prevent the script from propagating a `button_clicked` event that will cause the error.

The event isn't fired when you click on a disabled button, so clicking on it will basically open the record in form view (or switch the row to edit mode if the list is editable).

**Comment by julien-banken** [comment]
Hello @aab-odoo,
I added the `disabled` property on the buttons and I updated the commit message. Thank you for you help :)

**Review by aab-odoo — COMMENTED** [review]
:+1: 

Small remark: don't forget to mention web in commit message: [FIX] survey,web: ...

**Review by aab-odoo — APPROVED** [review]

**Pull request closed without merging**
