### PR TITLE
[I18N] l10n_fr_fec: synchronise translations

### PR DESCRIPTION
**Pull request by mart-e**
msgmerge with .pot file

Fixes odoo/odoo#83457

### CODE REVIEW

**Comment by petrus-v** [comment]
Is there a way to improve CI that ensure .po files are valid without deplicate entries ? to prevent such case to come back again ?

**Comment by mart-e** [comment]
Actually it's already the case, we have a [duplication test](https://github.com/odoo/odoo/blob/f629c261cb7cd246f1f850388ce793420de5431a/odoo/addons/test_lint/tests/test_pofile.py#L12).
As I mentionned on the PR, I did not get an error while installing l10n_fr_fec so I suspect there is something else to trigger the bug.
Anyway, merging this one and forward porting to 14.0
@robodoo r+

**Comment by petrus-v** [comment]
@mart-e you didn't reproduce because this has been fixed in the mean time by https://github.com/odoo/odoo/pull/83643

```bash

$ git reset --hard 'odoo/14.0@{2022-01-27}'
Extraction des fichiers: 100% (22174/22174), fait.
HEAD est maintenant à d959dfada11 [FIX] point_of_sale : Variant changing price
$ cat addons/l10n_fr_fec/i18n/fr.po | grep Cancel | wc -l
2
$ git bisect start
$ git bisect good
$ git bisect bad odoo/14.0 
Bissection : 57 révisions à tester après ceci (à peu près 6 étapes)
[07e92ee01915bf99b73804c52915ad263169449c] [FIX] payment_payulatam: backport of webhooks support
$ cat addons/l10n_fr_fec/i18n/fr.po | grep Cancel | wc -l
1
$ git bisect bad
Bissection : 28 révisions à tester après ceci (à peu près 5 étapes)
[825bb5f770f3abccadd3db3c4a57b25c3d9c35ed] [FIX] sale : Show SO with archived customer (reimplementation)
$ cat addons/l10n_fr_fec/i18n/fr.po | grep Cancel | wc -l
2
$ git bisect good
Bissection : 14 révisions à tester après ceci (à peu près 4 étapes)
[31e0ed8c957e8a6af7f6bd5d449b450967206eab] [REF] account_check_printing: Speed-up payment creation
$ cat addons/l10n_fr_fec/i18n/fr.po | grep Cancel | wc -l
1
$ git bisect bad
Bissection : 6 révisions à tester après ceci (à peu près 3 étapes)
[8d1d62a8c0746abb30f97290304b761f74111a89] [IMP] mail: improve test covage of odoo/odoo@003e1395ac8dd25cd1a8971ce45d33368a6b3dde
$ cat addons/l10n_fr_fec/i18n/fr.po | grep Cancel | wc -l
1
$ git bisect bad
Bissection : 3 révisions à tester après ceci (à peu près 2 étapes)
[e2f1f4967a2dd4d730895e924f0c7ca02e23a17b] [FIX] web_editor, website: properly display the redirect old url list
$ cat addons/l10n_fr_fec/i18n/fr.po | grep Cancel | wc -l
1
$ git bisect bad
Bissection : 0 révision à tester après ceci (à peu près 1 étape)
[b6fb13845cfa8bffb3f3952c163adb0f1e8ee598] [FIX] point_of_sale: Fix crash in ClientListScreen
$ cat addons/l10n_fr_fec/i18n/fr.po | grep Cancel | wc -l
1
$ git bisect bad
Bissection : 0 révision à tester après ceci (à peu près 0 étape)
[466327d4e79434d06d37ef5f2db700cafaa66c5b] [FIX] l10n_fr_fec: remove duplicated translations
$ cat addons/l10n_fr_fec/i18n/fr.po | grep Cancel | wc -l
1
$ git show -P
commit 466327d4e79434d06d37ef5f2db700cafaa66c5b (HEAD)
Author: Julien Van Roy <juvr@odoo.com>
Date:   Mon Jan 31 08:16:45 2022 +0000

    [FIX] l10n_fr_fec: remove duplicated translations
    
    closes odoo/odoo#83643
    
    Signed-off-by: Laurent Smet <las@odoo.com>

diff --git a/addons/l10n_fr_fec/i18n/fr.po b/addons/l10n_fr_fec/i18n/fr.po
index 37fbaec2e5b..825e1a774c8 100644
--- a/addons/l10n_fr_fec/i18n/fr.po
+++ b/addons/l10n_fr_fec/i18n/fr.po
@@ -243,11 +243,6 @@ msgstr "Rapport FEC non-officiel (avec à la fois les entrées comptabilisées e
 msgid "Invalid VAT number for company %s"
 msgstr "Numéro de TVA invalide sur la société %s"
 
-#. module: l10n_fr_fec
-#: view:account.fr.fec:0
-msgid "Cancel"
-msgstr "Annuler"
-
 #. module: l10n_fr_fec
 #: model:ir.model.fields.selection,name:l10n_fr_fec.selection__account_fr_fec__export_type__official
 msgid "Official FEC report (posted entries only)"
$ 
```

**Comment by petrus-v** [comment]
@mart-e the duplication was only in po file, I don't really know how you CI is organized, does the `test_pot_duplicate_entries` is running on all `.po` file as well ? does those tests are running on all .po files while back porting fixes to prevent stable branches to bring such errors? does all language are installed ?

**Pull request closed without merging**
