### PR TITLE
[FIX] coupon: printed coupon not properly displayed

### PR DESCRIPTION
**Pull request by agr-odoo**
Generate a coupon code, print it

opw-2444242

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@nle-odoo 

**before**
before

**after**
after

**email view**
email

**Review by nle-odoo — APPROVED** [review]
the issue seems to be that mt32 (margin-top 32 pixels) does not work in current bootstrap version, the way to do that is to use mt-0 .. mt-5 (https://getbootstrap.com/docs/4.4/utilities/spacing/) but it's in `rem` unit so I think this would be enough to just add manually `style="margin-top: 32px" to the h2 in stable

and in master maybe have:

```xml
<h2 class="mt-4">
    <strong class="bg-light p-3" t-esc="o.code"/>
</h2>
```

or just keep the same code and remove `class="mt32"`, there is a lot of other direct use of pixels in this report anyway

robodoo delegate+

**Comment by agr-odoo** [comment]
> the issue seems to be that mt32 (margin-top 32 pixels) does not work in current bootstrap version, the way to do that is to use mt-0 .. mt-5 (https://getbootstrap.com/docs/4.4/utilities/spacing/) but it's in `rem` unit so I think this would be enough to just add manually `style="margin-top: 32px" to the h2 in stable

Thanks for the info, I'll go for the style change, perhaps what we did here would be more easily readable

**Comment by agr-odoo** [comment]
robodoo r+

**Pull request closed without merging**
