### PR TITLE
[FIX] mrp: display total qty on MO form view

### PR DESCRIPTION
**Pull request by malv-odoo**
In the MO form view, the total quantity was broken: it was appearing bellow the line.

**Steps to reproduce:**

1. Go to Manufacturing App
2. Click on some Confirmed MO
3. The quantity field in MO forms is appearing bellow the line and broke the view

This issue was happening because the button was automatically using class "btn" and it was using a padding style that was moving them bellow the expected position.

OPW-3244574

### CODE REVIEW

**Review by adwid — COMMENTED** [review]
It's better! But it still needs some changes
See before [1]:
image
And after your fix:
image
Either [1] should be replaced by another fix, or we keep it and try to improve the situation
Little hint: there are other uses of `d-flex flex-row align-items-center`, maybe it's worth reading some other cases

[1] 212b22fa106b11e23688235da9cb3975363b46f1

**Comment by malv-odoo** [comment]
@adwid Now the view looks like this, wdyt? (I didn't updated the PR yet)
Screenshot 2023-03-29 at 11 04 25

**Comment by ticodoo** [comment]
FYI seems to be related to this PR: https://github.com/odoo/odoo/pull/114820 . Also note that its forward ports weren't merged so you will probably have some conflicts until they are (if they will be?).

**Comment by adwid** [comment]
robodoo r+

**Comment by adwid** [comment]
@malv-odoo Actually there is still an error
If the to-produce qty is huge, it overlaps the UoM
image

**Comment by adwid** [comment]
https://github.com/odoo/odoo/pull/119208

**Pull request closed without merging**
