### PR TITLE
Master viva wallet currency number qle

### PR DESCRIPTION
**Pull request by qle-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by william-andre — APPROVED** [review]
We can do the necessary changes in accounting modules using the ISO numeric codes if needed
Would be nice to do this here though to avoid weird upgrade modules when removing other fields

**Comment by william-andre** [comment]
@robodoo r+

**Comment by h4818** [comment]
shouldn't we display the iso_numeric field somewhere?

**Comment by william-andre** [comment]
I don't think it is useful outside of debug, as it is master data that should not be modified and the value doesn't mean anything to standard users

**Pull request closed without merging**
