### PR TITLE
[FIX] web_editor: update editor value when changing records

### PR DESCRIPTION
**Pull request by Goaman**
Before this commit
1) click on a record in a list view
2) change the html field of a record
3) click on the top right arrow to change the next record
4) click on the top right arrow to change the previous record
5) click on the top right arrow to change the previous record

The value is not updated corretly at step 4, retaining the value from the
previous record. The wrong value is then saved at step 5.

After this commit
Properly reset the HtmlField property `currentEditingValue` when
the update of props value does not comes from the editor.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@Goaman I think the sentence "The value is not update at step 4 and will be saved a step 5." is not clear enough for people who have no knowledge of the original bug. I suggest: "The value is not updated corretly at step 4, retaining the value from the previous record. The wrong value is then saved at step 5."

**Comment by Goaman** [comment]
Updated

**Comment by dmo-odoo** [comment]
The runbot build seem to be red for unrelated reasons but rebuilding it does not seem to fix the issue so I suggest rebasing your branch.

**Comment by dmo-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r-

Reason: most likely breaking staging, see https://runbot.odoo.com/runbot/build/20055118 https://runbot.odoo.com/runbot/build/20053380 https://runbot.odoo.com/runbot/build/20050323

As we need staging to merge important branches, hereby stopping the bissect. A bit abrupt but better recheck this branch and push again.

Cheers !

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
