### PR TITLE
[FIX] website_sale: fix fiscal position update in eCommerce cart

### PR DESCRIPTION
**Pull request by kitan191**
- Install website_sale
- Go to Website > Products > Products and create a Product with "Tax 15.00%" (i.e. Product X)
- Publish the Product on Website
- Go to Invoicing > Configuration > Fiscal Positions
- Create a first Fiscal Position:
  * Fiscal Position (Name): Fiscal Position A
  * Tax Mapping: Tax 15.00% => Tax 15.00%
- Create a second Fiscal Position:
  * Fiscal Position (Name): Fiscal Position B
  * Tax Mapping: Tax 15.00% => Tax 0.00%
- Create a Portal User (i.e. User X)
- Go to Contacts and edit User X to set his Fiscal Position to Fiscal Position A

- Open another session and connect with User X
- Go to online Shop and add Product X in the cart
- Open "My Cart" => Taxes are displayed correctly
- Process checkout and enter an address
- Before paying, Review Order and remove Products from Cart

- In first session, change Fiscal Position of User X to Fiscal Position B

- In User X session, add again Product X in the cart
- Open "My Cart" => Taxes are displayed as if the Fiscal Position has not been changed
The Taxes are correctly displayed if the checkout is proccessed.

It is just that "fiscal_position_id" of SO is not checked and recomputed at this step for this flow.

opw-2300330

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kitan191** [comment]
ping @nim-odoo

**Comment by agr-odoo** [comment]
Maybe it's better to avoid calling directly an onchange and do the update manually
```diff
@@ -331,8 +331,11 @@ class Website(models.Model):
             # when buying a free product with public user and trying to log in, SO state is not draft
             if (flag_pricelist or recent_fiscal_position != fiscal_position) and sale_order.state == 'draft':
                 update_pricelist = True
-        elif sale_order.partner_id.id == partner.id and sale_order.fiscal_position_id != partner.property_account_position_id:
-            sale_order.onchange_partner_shipping_id()
+        elif sale_order.partner_id.id == partner.id:
+            # update fiscal position if changed in the meanwhile
+            fpos_id = partner.property_account_position_id.id or self.env['account.fiscal.position'].with_context(force_company=sale_order.company_id.id).get_fiscal_position(sale_order.partner_id.id, delivery=sale_order.partner_shipping_id.id)
+            if sale_order.fiscal_position_id.id != fpos_id:
+                sale_order.write({'fiscal_position_id': fpos_id})
```

**Comment by kitan191** [comment]
This is how `fiscal_position_id` is updated everywhere else in the file, but it is probably better not to introduced more calls to `onchange_partner_shipping_id`

**Review by agr-odoo — APPROVED** [review]

**Comment by agr-odoo** [comment]
@nim-odoo

**Review by nim-odoo — COMMENTED** [review]
The use case is a bit far-fetched, but I guess it would make sense in case of a cart recovery.

However, IMHO changing the fiscal position is not enough: you should also set `update_pricelist = True`, which allows the recomputation of all lines according to the right taxes. Am I correct? This is what is done just above with `recent_fiscal_position != fiscal_position`.

However, you also need to take into account that `sale_get_order` is called **a lot**, and in this case the condition `sale_order.partner_id.id == partner.id` is almost always `True`. If there is no fiscal position on the partner, it means `get_fiscal_position` will be called very often, for a somewhat edge case.

Maybe we could instead move the fiscal position check around here:
https://github.com/odoo/odoo/blob/ddc8814ce8c66c4b701e82266a24665400370eaa/addons/website_sale/models/website.py#L248

In case the fiscal position has changed when recovering a cart, we create a new SO. IMHO, that sounds more reasonable than checking the FPos every time.

What do you think?

**Comment by kitan191** [comment]
Yes. It is true that `sale_get_order` is called a lot.
It is probably better to do it there.
I will check this solution, and also `update_pricelist = True`.

**Comment by kitan191** [comment]
`update_pricelist = True` is triggering an update of the cart, but taxes don't seem to be recomputed.
I have to recompute them manually with `sale_order._compute_tax_id()`

**Comment by kitan191** [comment]
I've adapted the fix.

By the way, shouldn't we cancel cart (SO) from user's last visit ?
It is not done when previous pricelists is not available anymore, so I'm not sure.

**Review by nim-odoo — APPROVED** [review]
We don't need to cancel the existing SO.

Maybe you can adapt the commit message since now it mostly describes a use case we don't fix. Maybe limit the description to the use case we actually fix.

robodoo delegate+

**Comment by kitan191** [comment]
robodoo r+

**Comment by odony** [comment]
Hmm, this code is quite a sensitive part of website_sale. The fiscal position may not be accessible to the connected user, who may belong to a different company than that of the website. That means an error page for impacted users anywhere `sale_get_order()` is called, which is ... a lot, as you've noted.
The rest of the method uses sudoed environments for that purpose. Could you fix promptly? Thanks!

**Comment by Yenthe666** [comment]
@kitan191 @odony this also introduced a comparing apples and oranges issue. I made a fix at https://github.com/odoo/odoo/pull/62925

**Pull request closed without merging**
