### PR TITLE
[FIX] hr_expense: multi-currency

### PR DESCRIPTION
**Pull request by nim-odoo**
- Set your company to USD
- Create an expense in EUR:
  Amount: 100
  Tax: 15% Excluded
- Validate, post the journal entries

Not a single AML is correct.

opw-1938570

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
Test necessary

**Comment by nim-odoo** [comment]
@kebeclibre would you mind sharing your opinion?

Before the fix: https://screenshots.firefox.com/X91L4ANrHobH3WJX/localhost
After the fix: https://screenshots.firefox.com/DOx6b5wnIJY9AQDQ/localhost

**Comment by kebeclibre** [comment]
Ouch, indeed before the fix doesn't look good.
Fix seems okay, and screenshot after the fix too, provided that:
- the expense report has two entries for the Air Flight
- one of 100 taxed 15% ; in Euros
- the other of 700 taxed 15%; in Euros

I'd also recommend to write some tests

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by nim-odoo** [comment]
robodoo r-

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
