### PR TITLE
[IMP] im_livechat: split public_livechat.js into many files

### PR DESCRIPTION
**Pull request by Nemael**
Follow-up of: https://github.com/odoo/odoo/pull/87597

This is the 2nd and final step of splitting public_livechat.js
into several files.

This is part of refactoring public livechat so that it uses
essentially the same codebase as discuss in the web client.

Splitting in smaller files helps following steps to refactor
the code.

Task-2818675
Part of Task-2212347

### CODE REVIEW

**Comment by alexkuhn** [comment]
PR looks good with split.
Just missing the final touch: remove `public_livechat.js` completely.
So add another commit above that removes this file, and adapt imports to immediately use `livechat_button.js`.

**Comment by seb-odoo** [comment]
@robodoo override=ci/security
Just a code move. The line is ugly old code waiting to be refactored, but the HTML is built safely.

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
Moved to grouped PR: https://github.com/odoo/odoo/pull/88654

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
