### PR TITLE
[CLA] Corporate signature for Entrivis Tech Pvt Ltd.

### PR DESCRIPTION
**Pull request by krutarthbuch**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Thanks for the PR. Could you just rename the ile `doc/cla/corporate/EntrivisTech.md` to be lowercase (`entrivistech.md`)?

**Comment by krutarthbuch** [comment]
> Hi,
> 
> Thanks for the PR. Could you just rename the ile `doc/cla/corporate/EntrivisTech.md` to be lowercase (`entrivistech.md`)?

Requested changes are done and committed. Thanks!

**Comment by mart-e** [comment]
Great but could you keep it in only one commit? The commit message from the first commit was perfect and can be kept.

**Comment by krutarthbuch** [comment]
> Great but could you keep it in only one commit? The commit message from the first commit was perfect and can be kept.

Can you check again?

**Comment by mart-e** [comment]
Hi,
You haven't changed the PR. You need to have only one commit with the message `[CLA] Corporate signature for Entrivis Tech Pvt Ltd`
-CLA-Corporate-signature-for-Entrivis-Tech-Pvt-Ltd-by-krutarthbuch-·-Pull-Request-69631-·-odoo-odoo

**Comment by krutarthbuch** [comment]
> Hi,
> You haven't changed the PR. You need to have only one commit with the message `[CLA] Corporate signature for Entrivis Tech Pvt Ltd`
> -CLA-Corporate-signature-for-Entrivis-Tech-Pvt-Ltd-by-krutarthbuch-·-Pull-Request-69631-·-odoo-odoo

Sent another pull request : https://github.com/odoo/odoo/pull/71516

**Pull request closed without merging**
