### PR TITLE
[11] documentation revamp

### PR DESCRIPTION
**Pull request by mart-e**
The documentation, even prettier

### CODE REVIEW

**Comment by mart-e** [comment]
I was wondering, how about a `bold` on the titles. I still find that `h5` ("Prepare" and "Repository") is lost too much inside the text body

screenshot-2017-11-28 installing odoo odoo 11 0 documentation

**Comment by Yenthe666** [comment]
Hooray, excellent choice. Indeed Martin, the h5 titles really don't stand out. They should be more visible.

**Comment by stefanorigano** [comment]
@mart-e , yes! `bold` will definitely do the trick 👍  
I'll apply the changes

**Comment by stefanorigano** [comment]
@mart-e , `h5 - h6` fix pushed 👍

**Comment by mart-e** [comment]
Thanks !

**Pull request closed without merging**
