### PR TITLE
[IMP] l10n_il: improve CoA, fiscal positions, and taxes.

### PR DESCRIPTION
**Pull request by hedshefer**
…n Israel. This commit include the following changes: taxes, fiscal positions, and chart of accounts

@jco-odoo 
I have created a new PR with one commit according to the feedback.
Kind regards,
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hedshefer** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
@hedshefer Better, but the commit msg is not in the right forward.  But do not worry, this can wait another week.

**Comment by hedshefer** [comment]
> @hedshefer Better, but the commit msg is not in the right forward. But do not worry, this can wait another week.

@jco-odoo 
Done, let me know if something is missing.

**Comment by hedshefer** [comment]
@jco-odoo The commit email has been fixed

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
