### PR TITLE
[FIX]

### PR DESCRIPTION
**Pull request by stefanorigano**
Description of the issue/feature this PR addresses:
Bugfix

Current behavior before PR:

* /shop is broken on Firefox
* Ribbon are broken (on all browsers). 

Desired behavior after PR is merged:

No more bugs

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @tivisse , ready for tech. review

**Comment by stefanorigano** [comment]
@tivisse , just a reminder ;)

**Comment by tivisse** [comment]
@robodoo r+ 

Thanks for the fixes :)

**Comment by tivisse** [comment]
@robodoo retry

**Pull request closed without merging**
