### PR TITLE
[FIX] website: matches icon apps to the app switcher

### PR DESCRIPTION
**Pull request by ThanhDodeurOdoo**
This commit makes it so that the icons of the website new-content
menu are closer to the icon of the app they are related to.

task-2329291

### CODE REVIEW

**Comment by JKE-be** [comment]
@ThanhDodeurOdoo can we have a real name for svg? thx

**Comment by JKE-be** [comment]
Hey

Thanks for this rename.

But can you try to me more conscientious:
    - Name of icon is in a thumbs folder, do we now that it is a thumbs => website_slides_page.svg
    - Name of apps installed is wesbite_slides and not website_slides_page => website_slide.svg lgtm
    - Folder on same level are: snippets_xxx => app**s**_thumbs
    - And last but not least, did you only try your 2 lines of xml locally. Because it doesn't work. If you install website_slide you will see the visual bug with fa-spin.

//cc @qsm-odoo you see other bug possible with filter lighter instead of text-muted ?

**Comment by qsm-odoo** [comment]
@JKE-be I don't think so? Maybe it is worth asking @stefanorigano though. He used `saturate(0) blur(1px)` as filter on uninstalled snippets maybe it would be worth using the same for those uninstalled apps? (did not try)

**Comment by ThanhDodeurOdoo** [comment]
@JKE-be I pushed the changes and spin fix, I missed the bug for the spin on install because I did the mistake of installing the slide app through the odoo command line.

**Comment by JKE-be** [comment]
Thanks @ThanhDodeurOdoo 

Waiting @stefanorigano opinion for text-muted alternative before r+

**Comment by stefanorigano** [comment]
Hello there, thanks for having brought this to my attention.

I agree with @qsm-odoo on keeping visually consistent not-installed components design, but I made some tries and unfortunately the "snippets library design" doesn't work in this scenario.

In my test I had acceptable results with `brightness(70%) contrast(0.6)`.

FYI, I'm experiencing layouts misalignments, probably because the `.fa`class is still there while we're using bg implementation (? - didn't check the details). Btw I solved using `display:block; margin:auto`, just an idea


image

**Comment by qsm-odoo** [comment]
@ThanhDodeurOdoo Let's try SRI's suggestions, could you upgrade the PR? Thanks ;)

**Comment by ThanhDodeurOdoo** [comment]
@qsm-odoo pushed, here is the new appearance
screenshot-localhost_8069-2020 10 05-15_29_28

**Comment by JKE-be** [comment]
Thanks

@robodoo r+

**Pull request closed without merging**
