### PR TITLE
[FIX] core: computed editable one2many field with a domain

### PR DESCRIPTION
**Pull request by rco-odoo**
Manually adding a line should not trigger the computation of the field,
just like modifying the line fields that occur in the field's domain.
In other words, the dependencies of the field should be limited to the
ones declared on field or its compute method.

### CODE REVIEW

**Review by Elkasitu — COMMENTED** [review]
The code itself is ok, but I wonder if this performance improvement won't make the code more error-prone? I don't think many people will realize that if they change the value of the field that appears in a computed x2m's domain, they have to flush and invalidate the cache...

In fact you may not even realize that the field you're modifying appears in the domain of an x2m that you access later on...

**Comment by rco-odoo** [comment]
> The code itself is ok, but I wonder if this performance improvement won't make the code more error-prone? I don't think many people will realize that if they change the value of the field that appears in a computed x2m's domain, they have to flush and invalidate the cache...

Remember that the fix is for a pretty rare case: a *computed editable* x2many field with a domain.  I had some feedback showing that developers are unaware of what's going on.  And they really don't expect the field to be recomputed when you touch something that is not in the compute method's dependencies.  This is the whole point of this fix.

> In fact you may not even realize that the field you're modifying appears in the domain of an x2m that you access later on...

You are totally right.  Assume you modify a field that appears in such a computed editable one2many field's domain.  You have to choose between two bad things: either the one2many field is recomputed, or the one2many field might not be consistent in cache.  The question is: which one is worse?

A use-case was reported by @oco-odoo, who explained me that the unexpected recomputation clearly broke some functionality.  On the other hand, the inconsistent cache is of course not good, but it is much less likely to break things.  IMHO this suggests that the recomputation is worse than the potential cache inconsistency.

**Comment by Elkasitu** [comment]
I'll leave it up to you and/or people who actually write some business code 😄

**Comment by rco-odoo** [comment]
Note also that the patch actually generalizes the special case of related fields to all computed fields: adding domain fields in `self.depends` was done only for non-related fields.

**Comment by xmo-odoo** [comment]
The situations seems a bit unclear to me, does having a compute *and* a domain really make sense? What does it do? 

Amd does `store=True` on an o2m mean the writes are passed through instead of ignored? (or are they always passed through?) Or are they put in the cache then ignored?

**Comment by rco-odoo** [comment]
> The situations seems a bit unclear to me, does having a compute _and_ a domain really make sense? What does it do?

In the use-case that was reported to me, the field is computed stored editable, which means that the compute method is expected to work as an *onchange* only.

> Amd does `store=True` on an o2m mean the writes are passed through instead of ignored? (or are they always passed through?) Or are they put in the cache then ignored?

In this case, the field is editable, which means that you can actually modify it directly.

**Comment by xmo-odoo** [comment]
> > The situations seems a bit unclear to me, does having a compute _and_ a domain really make sense? What does it do?
> 
> In the use-case that was reported to me, the field is computed stored editable, which means that the compute method is expected to work as an _onchange_ only.

That seems like an odd side-effect for a field which is not actually stored in any meaningful way, but oh well.

**Review by xmo-odoo — APPROVED** [review]

**Comment by rco-odoo** [comment]
@xmo-odoo thanks for the feedback!

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
