### PR TITLE
[IMP] sale order line load the analytic default when installed sale analytic plans.

### LINKED ISSUE #6543: [8.0] invoice not load defaults value from analytic defaults settings after install sale analytic plans and purchase analytic plans.
- this should effect all version. *

when installed sale analytic plans and purchase analytic plans, create invoice form  sale order or purchase order should never follow analytic defaults.

as we excepted was that, when create invoice, by default it should populate the default analytic distribution from analytic defaults settings.

how to to, i proposed that should rewrite `invoice_line_create`, to load the default value which calculate with analytic defaults., and add onchange logic to change the default value when changed the product that invoked with the invoice.

### PR DESCRIPTION
**Pull request by jeffery9**
fix  #6543

### CODE REVIEW

**Comment by invitu** [comment]
Dear @jeffery9 
Your fix works
You should sign the CLA and maybe Odoo SA would merge your commits... even if I think they will not because analytic plans are not supported in v9 anymore
Thanks anyway

**Comment by invitu** [comment]
You also might do a PR on https://github.com/OCA/OCB/pulls

**Comment by jeffery9** [comment]
yes, already have signed this file.

https://github.com/odoo/odoo/blob/8.0/doc/cla/individual/jeffery.md

On Mon, May 23, 2016 at 2:07 AM, invitu <notifications@github.com> wrote:

> Dear @jeffery9 <https://github.com/jeffery9>
> Your fix works
> You should sign the CLA and maybe Odoo SA would merge your commits... even
> if I think they will not because analytic plans are not supported in v9
> anymore
> Thanks anyway
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/pull/6544#issuecomment-220846820>
>



-- 
Jeffery        -odoo expert form kunshan, suzhou, china

**Comment by invitu** [comment]
Your CLA file should be "jeffery9.md" instead of "jeffery.md".
Read CLA rules here  :  https://www.odoo.com/sign-cla

**Comment by jeffery9** [comment]
yes, i rename it. and have create a PR for it.

On Tue, May 24, 2016 at 12:23 AM, invitu <notifications@github.com> wrote:

> Your CLA file should be "jeffery9.md" instead of "jeffery.md".
> Read CLA rules here : https://www.odoo.com/sign-cla
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/pull/6544#issuecomment-221022284>
>



-- 
Jeffery        -odoo expert form kunshan, suzhou, china

**Comment by tivisse** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards

**Pull request closed without merging**
