### PR TITLE
res.country.group: Europe -> European Union

### PR DESCRIPTION
**Pull request by alexis-via**
Let's use the right words, to avoid confusion!

### CODE REVIEW

**Comment by alexis-via** [comment]
It's very very important to use the right words. This PR is VERY important !!!

**Comment by Yenthe666** [comment]
Hmm
1. Follow the commit standards please :-D [reason] module_name: what you did. E.g `[IMP] base: better naming country group Europe`
2. Not sure but I presume our Odoo overlords want this in master as an improvement 🤔

**Comment by lathama** [comment]
@alexis-via knowing that 14 is no longer updated, is this PR still needed?

**Comment by Yenthe666** [comment]
Are you really going to comment this on all old PR's that Odoo never handled? 😅

**Comment by lathama** [comment]
This could be rebased on 15 then auto-forwarded to 16. 
17 and master have this corrected.

**Comment by alexis-via** [comment]
I confirm it is fixed in v17. If this PR had been merged in time, it would have been fixed much earlier!

**Pull request closed without merging**
