### PR TITLE
[CLA] signature for sakesun

### PR DESCRIPTION
**Pull request by sakesun**

### CODE REVIEW

**Comment by mart-e** [comment]
@robodoo squash r+

**Comment by sakesun** [comment]
Anything need to be fixed on my side ?

**Comment by mart-e** [comment]
Hi,
It seems we have an issue with our merging tool, nothing wrong on your side :)
Just to be sure, you are making this request against master branch, is that because it's where you want to contribute?
If you want to contribute in stable versions (e.g. 16.0 or 17.0), you have to sign the CLA in the lowest version.

**Comment by sakesun** [comment]
Oh I see. Naively, I thought putting in master will make sure it won't lost afterward.
Just open another PR for branch 16.0, cherry-picking from this commit. Hope that's alright.

Thanks.

**Comment by mart-e** [comment]
Ok perfect, closing this one and merging the other in all branches :)

**Pull request closed without merging**
