### PR TITLE
[IMP] enable codeview in html editor

### PR DESCRIPTION
**Pull request by parthivgls**
enable codeview in html editor for quicker editing for advance users.

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Thanks for the patch but I think it's missing something. Try the following steps to reproduce the issue:

1. open a form with a html field (e.g. the user preference with its signature)
2. go to html mode and add some bold (`<b>`) somewhere
3. save

You will see the html content has not been modified.

**Comment by parthivgls** [comment]
@mart-e Now there is slightly a trick.. not sure from summernote or not.
Follow this steps

1. Go to "CodeView" mode.. change the code, you can add any html code
2. Save directly .. Changes won't reflect.. 

Your scenario is right

**Comment by mart-e** [comment]
@parthivgls yes exactly, the [onChange](https://github.com/odoo/odoo/blob/9c690547f88345db092aa31731ee2a899678d96f/addons/web_editor/static/src/js/backend.js#L44) is not triggered when you only modify the html

**Comment by parthivgls** [comment]
https://github.com/odoo/odoo/pull/9895 seems to be addressing the issue. Closing this PR and waiting for https://github.com/odoo/odoo/pull/9895 to be accepted.

**Pull request closed without merging**
