### PR TITLE
[REF] mail: `rtcCallParticipantCard`, review and simplify scss

### PR DESCRIPTION
**Pull request by xlu-odoo**
Part of the overall v16 SCSS optimization/restyle, task-2704984

task-2842691

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xlu-odoo** [comment]
@Brieuc-brd can you take a look please?

**Comment by alexkuhn** [comment]
Hello, just to let you know that another PR is being merged and also affect some CSS in this file.
https://github.com/odoo/odoo/pull/91297

**Review by Brieuc-brd — COMMENTED** [review]
Thanks for the info @alexkuhn 👍.

@xlu-odoo 👋, some remarks below 👇 
In addition to my comments, you will need to rebase your branch and resolve conflicts, don't hesitate to ask if you have questions 😉

**Comment by xlu-odoo** [comment]
@Brieuc-brd Can you review this one again?

**Review by Brieuc-brd — COMMENTED** [review]
@xlu-odoo 👋 
Some remarks below 😉 

Hey @alexkuhn 👋 ,
when I tested this branch, I found this issue : 

Capture d’écran 2022-05-18 à 11 55 48

It appears when a call is already started and the user has not joined yet. After investigation, I think this issue comes from https://github.com/odoo/odoo/pull/91297.

What do you think ?

**Comment by alexkuhn** [comment]
> Hey @alexkuhn 👋 , when I tested this branch, I found this issue :
> 
> Capture d’écran 2022-05-18 à 11 55 48
> 
> It appears when a call is already started and the user has not joined yet. After investigation, I think this issue comes from #91297.
> 
> What do you think ?

Indeed it's broken since #91297.
The code relies on bounding rect of the UI to determine proper sizing of elements:
https://github.com/odoo/odoo/blob/15.0/addons/mail/static/src/components/rtc_call_viewer/rtc_call_viewer.js#L107

And I think the PR changed bounding rect, which completely messed the resulting `tileHeight`.
cc @ThanhDodeurOdoo

**Comment by xlu-odoo** [comment]
@Brieuc-brd Can you take a look?

**Comment by Brieuc-brd** [comment]
@xlu-odoo LGTM, you can remove the draft state and set your task to « Ready 🟢 ».
@alexkuhn, this PR is ready for tech. review. 👍 This PR also introduces a new BS5 utility class that is needed for this revamp. I think it makes more sens to keep it in this PR rather than create a new one, is that ok for you ?

cc. @stefanorigano @adr-odoo

**Review by alexkuhn — APPROVED** [review]
LGTM, I'm ok to merge with the introduction to `border-X`. Thanks!

**Comment by alexkuhn** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
