### PR TITLE
[IMP] *: add issubmodel method

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

Adds a method to check if a model is a submodel of another model. May be useful for checking mixings.

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-

### CODE REVIEW

**Comment by mreficent** [comment]
@tde-banana-odoo Should I retarget to 13.0?

**Comment by tde-banana-odoo** [comment]
Hello,

As it is only some code rewording, it should target master. There is no need adding it to a (almost) stable version :) .

**Comment by mreficent** [comment]
Ok, then when master gets updated I will do it ;)

**Comment by rco-odoo** [comment]
I don't see the added value.
What is the problem you are trying to solve?

**Comment by mreficent** [comment]
Well, it's not to solve any specific problem now. But I thought it's a way to clean and centralize all the common code in a method. Avoid the appearing of `type` and `pool` everywhere. Thus, if in the future something changes with how to get the `type` of the model, or if the `pool` environment changes, or something like this, then it will be easier to just change the method than rewriting all the files.

Feel free to accept or reject the PR, no problem.

**Comment by tde-banana-odoo** [comment]
Lot of dev don't really know how to do it and copy-paste this code. I am in favor of this small helper method that allows to write code easier to understand when being out of "registry-pool-master" team.

**Comment by pedrobaeza** [comment]
Coming to this through codetriage.com. Is this still relevant?

**Comment by tde-banana-odoo** [comment]
I let @rco-odoo decide :) .

**Comment by mart-e** [comment]
I think we can close, as @rco-odoo as given his opinion ("I don't see the added value.")

**Pull request closed without merging**
