### PR TITLE
[FIX] web_editor: Focus on composer if no anchor selected

### PR DESCRIPTION
**Pull request by nboulif**
Steps to reproduce:

  - Go to any chatter
  - Click on "Send message"
  - Open the Full Composer
  - Click directly on the "Link" button of the composer
  - Add label and url then save

Issue:

  Link not added to composer.

Solution:

  When getting link info, focus on the closest element of the composer.

Related fixes:
https://github.com/odoo/odoo/commit/da14e4449e5e318eb72e1b9f268fb797adb0c6a6
https://github.com/odoo/odoo/commit/d2f3c9e7975188753fa17c06db3fc5c73c773944

opw-2544149

### CODE REVIEW

**Comment by nboulif** [comment]
@fw-bot up-to 14.0

**Review by rdeodoo — CHANGES_REQUESTED** [review]
@xO-Tx Hi could you have a look here?
This commit tries to fix a fix that you made that fixed a fix by adding back part of the first fix.
This is a fixception :smile:

**Review by rdeodoo — APPROVED** [review]
LGTM, working as expected
Thank you @xO-Tx for the complete analysis, I knew you would be the man we needed here.
Hopefully not many people got impacted by this as you have to create the link before clicking inside the html area.

**Review by nle-odoo — COMMENTED** [review]
robodoo delegate+

**Pull request closed without merging**
