### PR TITLE
[FIX] mail: fix activity view

### PR DESCRIPTION
**Pull request by RomainLibert**
This PR fixes two tracebacks

  1) Click on add an activity, in the dialog, choose a record and get the traceback

  2) Click on an empty cell in the view, this opens the activity wizard, then simply try to discard the wizard and enjoy the traceback

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@tivisse is this still a concern?

**Comment by tde-banana-odoo** [comment]
Did you ask Rli ?

**Comment by tivisse** [comment]
@xmo-odoo I dunno. @alexkuhn You may close it if the issue is not valid anymore.

**Comment by alexkuhn** [comment]
Looks fixed, so I'm closing this.

**Pull request closed without merging**
