### PR TITLE
add l10n_tn module

### PR DESCRIPTION
**Pull request by mohamedhabibchallouf**
add new module l10n_tn : Tunisian Account Chart

### CODE REVIEW

**Comment by mohamedhabibchallouf** [comment]
Mohamed Habib Challouf Odoo CLA signature check

**Comment by mohamedhabibchallouf** [comment]
change@mail 2

**Comment by mart-e** [comment]
Hello,

Sorry if we have missed your module.
It is quite outdated and I believe it is better to submit directly for version 9 or 10 as the code has changed quite a lot.
Please let me know if you are still up to add this and I can guide you for the integration.

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards

**Pull request closed without merging**
