### PR TITLE
[FIX] stock: Allow to write on multiple warehouses

### PR DESCRIPTION
**Pull request by rousseldenis**
If we try to write on a multi recordset warehouses, we
get a singleton error

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rousseldenis** [comment]
@amoyaux

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
Merci pour le fix

**Comment by rousseldenis** [comment]
> Merci pour le fix

Avec plaisir !

**Pull request closed without merging**
