### PR TITLE
[10.0] l10n_lu translation

### PR DESCRIPTION
**Pull request by sbidoul**
@mart-e as discussed.

Note a small bug fix in l10n_multilang.

### CODE REVIEW

**Comment by sbidoul** [comment]
All considered, the addition of the dependency on l10n_multilang may be a bit hard wrt the stable policy.

**Comment by mart-e** [comment]
Yes, a bit delicate to change the `depends` in stable. Or making the changes without the `depends`, keeping in mind on your deployments you need to first install `l10n_multilang`. For v12, making the full changes.

cc @odony

**Comment by sbidoul** [comment]
cc @xavieralt @avw-odoo 

cc @Cedric-Pigeon @adrienpeiffer @benwillig

**Comment by mart-e** [comment]
@sbidoul is this still needed? Could we keep only the minimal (no translation) changes for this v10?

**Comment by sbidoul** [comment]
@mart-e yes we need this. If you don't want it on 10, please merge it on 11 or master.

**Comment by mart-e** [comment]
Ok I thought there was some other changes but actually it is only translations.
I tried to apply it in master (as a change of dependencies, not possible in v11) but it conflicts, there was other changes in l10n_lu.
Could you resubmit it there?

**Comment by sbidoul** [comment]
You see Martin, that's where it's exhausting to work with Odoo. We submit a product improvement on the version we work on. It's rejected becaused deemed too dangerous (I can understand that). But then the burden is back on us to port it to master, which is a version we don't use...

At least when we do the work, a tiny fraction of the subscriptions we and our customer pay could be allocated to merging our contributions to make sure they last.

Could you, at the very least, leave the PR open so it's not forgotten?

And consider the bug fix in l10n_multilang?

**Comment by sbidoul** [comment]
@mart-e I notice I did not mention you in my previous comment.

**Comment by mart-e** [comment]
I am sorry we could not integrate your contribution in time. We do are working actively to merge it faster. I hope you have noticed our efforts to qualify and merge faster the issues and PR these last few months but the backlog is still huge.

You are correct for the bug, it was indeed an error. I have merged it at 3bf9cf4f36e036495e3b1e54a77eadf39a1ccee2
Also, be careful, do not use getattr, it is a security risk while you can just use `record[field]`.

**Comment by mart-e** [comment]
@sbidoul the conflict wasn't so big after all. Hopefully, everything should be in master at b9488caa643c59d22f31c8761891c6d294819b9e !

**Comment by sbidoul** [comment]
Great! Thanks a bunch, @mart-e 

Keep up the good work!

**Pull request closed without merging**
