### PR TITLE
[FIX] hr_timesheet, timesheet_grid: adapt relation according to group

### PR DESCRIPTION
**Pull request by thle-odoo**
Steps to reproduce:
-------------------
On the timesheets tab of a task, with a user
who does not have access to employees,
when you click on "Search More...", a traceback appears.

Cause:
------
When we request the view from the backend,
we ask for "hr.employee" and the backend
returns "hr.employee.public".
The latter will be a dictionary key.
As a result, we will get an `undefined`
when we use the `hr.employee` key.

Solution:
---------
Modify the relationship according
to the user's group.

opw-3389733

### CODE REVIEW

**Review by xavierbol — COMMENTED** [review]
LGTM, thanks for your work, however, I am wondering if we don't also have the bug in Timesheet app. May I ask you to check that? 🙂 

Thanks in advance! 🙂

**Comment by thle-odoo** [comment]
Enterprise PR: https://github.com/odoo/enterprise/pull/43856

**Comment by xavierbol** [comment]
can you rebase your branch? 🙂

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work. 

robodoo r+

**Pull request closed without merging**
