### PR TITLE
[MERGE][IMP] website[_slides,event,forum]: avoid unnecessary crawled links

### PR DESCRIPTION
**Pull request by awa-odoo**
Some of our pages have foreach loops that create `<a>` links, notably:
- event.event tags
- event.track tags
- event.sponsor sponsorship levels
- event.sponsor countries
- slide.channel tags
- forum.post tags

As those are based on user-created data, we can end up with a lot of links
elements on the page, which are ALL going to be crawled by bots.

This will quickly turn into a performance drain on the server, that can receive
hundreds of useless route hits, as we don't want those links to be indexed.

To solve this issue, we use the already existing "post_link" frontend Widget,
that allows to easily transform an element into a disguised POST request.
Thus removing the real links from the page but conserving the feature.

Note: simply using rel="nofollow" has proven inefficient as bots will likely
follow these links anyway, but weigh them differently. 

Task-3908389

### CODE REVIEW

**Review by reth-odoo — COMMENTED** [review]
Slightly weird to post a search but seems like the best way indeed. We already do it anyway.

I see most big crawlers support wildcards (including query parameters) in robots.txt so that could be another solution maybe?

Left an unrelated comment, greening already.
Edit: Comment about commit messages, "pounder"? Do you mean "weigh" or "ponder"?

**Review by JKE-be — APPROVED** [review]
Il manque quand meme la partie python je pense pour par exemple que /events ne gere les tag que si en POST... sinon redirect sans tag?
Car google va continuers des annees sur les sites existant à crawler les combinaisons de tags comme precedemment... vu  qu'il le a vu precedemment, et donc faire la partie Dark sur les dbs existantes.


Sinon si on peut targetter la pré-master (named saas-17.3^^ pour l'avoir sur la prod le mois prochain :innocent: :pray::skin-tone-2: ) 

Sidenote:
- a voir si div.post_link devrait pas avoir son curseur en css...
genre `.post_link:not(.nocursor) { cursor: pointer !important; }` :thinking:

- `<div class="post_link cursor-pointer d-inline-block">` vs `<span class="post_link cursor-pointer">` :thinking: 

- le format des urls avec les ids en json reste vraiment bof. On ne pourrait pas avoir les ids concatenés avec des `,` comme discuté précedemment ? (avec redirect pour retrocompatibility?)



Mais rien de bloquant ici, mais a continuer (même/autre pr) au moins pour la partie python imo



- not related but while testing: o_wevent_offcanvas_country is duplicate for level, so both accordion open/close at same time


- not sure if related, but in local I cannot have popover on sponsor with this PR while it works on runbot.

**Comment by awa-odoo** [comment]
Hello @JKE-be 

TD;DR: Python checks are done, swapped everything to span, will format URLs in future task, will fix accordion in stable, keeping this work in master.

Again, thanks for the review, I'll try to address everything one by one, starting with the most important.

> Il manque quand meme la partie python

I've now added checks in the controllers to permanently redirect routes that are hit with "tags" and are not using POST.

There is a catch however, it was a bit annoying as people could then not refresh their page (by going into the URL bar and hitting "enter") or sharing any filtering links (not a huge deal, but still nice).
And more importantly, there were use cases that were just not working anymore, such as filtering tags (which will do a POST request) and then searching using the search bar (which would do a GET but keep the tags filters -> kaboom).

I've wrapped my head around it a bit and decided to use a new parameter (named "prevent_redirect" in lack of better options).
The idea is to prevent the permanent redirect when this param is present (and it's passed around using keep_query).
(I could also have meticulously tried to find every places where tags are specified and change it to POST but it seemed like a lost battle).

That way:
- new URLs still work nicely, can be refreshed and shared
- bots URLs that don't contain this parameter will be permanently redirected, fixing our issues

On a side note, I did not do this work for the exhibitor part (second commit).
As the crawler prevention exists there since 15.0, it seems fair.

> a voir si div.post_link devrait pas avoir son curseur en css...

I see what you mean, maybe a good idea down the road, but I did not do it here because frankly I don't want to be looking at every single existing usage and qualify if it's justified or not. Maybe later?

> div vs span

You're right on that one, "span" is closer to what "a" is, so I swapped everything to span (and cleaned the d-inline-block).

> le format des urls avec les ids en json reste vraiment bof. On ne pourrait pas avoir les ids concatenés avec des , comme discuté précedemment ? (avec redirect pour retrocompatibility?)

That's a good idea yes, I see we have already done this work in several apps, such as e-learning.
Will create a separate task and see with the PO to avoid dragging this one for too long.

> o_wevent_offcanvas_country is duplicate for level

Good catch, I'll fix it in stable in another PR

> not sure if related, but in local I cannot have popover on sponsor with this PR while it works on runbot.

There are conditions for this popup to appear, from what I remember the event has to be upcoming (and not live) and you have to be a public user. I tried in that scenario and it worked on runbot, was probably your issue I'm guessing.

And finally, about targeting 17.3, it seems a little harsh considering there are a LOT of DOM structure changes.
I've heard 17.4 is going to be deployed "soon-ish" on odoo.com, so I'll try to push to have this merged before the next freeze.

That's was quite the pavé, lots of things to answer 😄 

Let me know if you see anything else that needs changing.

Cheers!

**Review by tde-banana-odoo — APPROVED** [review]

**Comment by tde-banana-odoo** [comment]
Rebase to do ^^

**Comment by tde-banana-odoo** [comment]
> Yes, even not sure to have odoo.com in 17.3... so ok!

But they said ``Upgrade odoo.com 17.4 le 27 aout (internal infra) `

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo rebase-merge

**Pull request closed without merging**
