### PR TITLE
[FIX] sale_product_configurator: make it work on mobile

### PR DESCRIPTION
**Pull request by jvnm-dev**
This commit is a fine-tuning of eda451f99fe

It seems that only adding the widget does not the job.

Now, the product configurator pop-up appears and
the search is done on product.template instead of
product.product

OPW-2214095

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
@nle-odoo

**Comment by jvm-odoo** [comment]
Ran all tests locally, product matrix need another config, product variant ok
@robodoo r+

**Comment by Feyensv** [comment]
FYI this was nearly done in a task (dropped since then): https://github.com/odoo/odoo/pull/34439.
The only missing thing at that time was to bridge the barcode and the configurator (since we explicitly didn't want to loose the barcode ability when installing the configurator).

Note that the product configurator is linked to 4 modules (other than its basic definition in sale):
1) event_sale (works fine in your branch)
2) sale_renting (enterprise) (not tested, I believe you only have a community branch)
3) sale_product_configurator (customization of the product works, but not the optional products feature)
4) sale_product_matrix (doesn't work in mobile in stable nor in your branch)

IMHO, I also expect other support tickets for the other features if you open this Pandora Box (and I really don't like the idea of dropping the barcode which works fine in mobile, for the configurator which doesn't work correctly in mobile).

I'll let you decide anyway, at least you know the whole aspect of the matter.

**Comment by jvm-odoo** [comment]
@robodoo r-

**Comment by jvm-odoo** [comment]
@Feyensv Indeed, it doesn't sound ideal. Thank you for this clarification!
If it works on sale_renting, I'll merge only the JS, revert the previous commit and do the XML on the customer's database since he is aware that barcode will not work anymore.

**Comment by jvm-odoo** [comment]
@robodoo r+

**Comment by jvm-odoo** [comment]
@robodoo rebase-ff

**Comment by nle-odoo** [comment]
robodoo rebase-ff r+

**Pull request closed without merging**
