### PR TITLE
[9.0][BUG][test_new_api] Test that show problem with inverse + constrains.

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses:

When you inverse a constrained field, the constraint is evaluated before the inversion:

```
INFO odoo openerp.modules.module: openerp.addons.test_new_api.tests.test_inverse running tests.
INFO odoo openerp.addons.test_new_api.tests.test_inverse: test_constraint_check_after_inverse (openerp.addons.test_new_api.tests.test_inverse.InverseCase)
INFO odoo openerp.addons.test_new_api.tests.test_inverse: ` This should raise nothing.
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: ERROR
INFO odoo openerp.addons.test_new_api.tests.test_inverse: ======================================================================
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: ERROR: test_constraint_check_after_inverse (openerp.addons.test_new_api.tests.test_inverse.InverseCase)
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: ` This should raise nothing.
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: Traceback (most recent call last):
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/addons/test_new_api/tests/test_inverse.py", line 10, in test_constraint_check_after_inverse
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     "required": True,
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     return new_api(self, *args, **kwargs)
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4157, in create
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     record = self.browse(self._create(old_vals))
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     return new_api(self, *args, **kwargs)
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/api.py", line 490, in new_api
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     result = method(self._model, cr, uid, *args, **old_kwargs)
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4354, in _create
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     recs._validate_fields(vals)
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     return new_api(self, *args, **kwargs)
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/models.py", line 1277, in _validate_fields
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     check(self)
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     return new_api(self, *args, **kwargs)
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `   File "/usr/lib/python2.7/site-packages/openerp/addons/test_new_api/models.py", line 337, in _check_required
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: `     raise ValidationError("Reference and sequence are required.")
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: ` ValidationError: ('Reference and sequence are required.', None)
INFO odoo openerp.addons.test_new_api.tests.test_inverse: Ran 1 test in 0.017s
ERROR odoo openerp.addons.test_new_api.tests.test_inverse: FAILED
INFO odoo openerp.addons.test_new_api.tests.test_inverse:  (errors=1)
```

Current behavior before PR:

A record is created without the inversed values, and constraint-checked, then constraints fail and inversion never takes place.

Desired behavior after PR is merged:

This just adds the test that proves this flaw exists, but does not patch it, so the only difference is that runbot will go :x:. I'd appreciate ideas or patches to actually fix this.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Was that already attended?

**Comment by Yajo** [comment]
No

**Comment by pedrobaeza** [comment]
@rco-odoo can you please take a look to this?

**Comment by pedrobaeza** [comment]
@Yajo please rebase to see if the problem is still there.

**Comment by pedrobaeza** [comment]
It seems that you have made the commit with other credentials than the included in the CLA (this is v9). Any way, let's see the result of runbot.

**Comment by Yajo** [comment]
Well the CLA can be ignored because with squash at merge it's fixed.
And the runbot's :x: is expected, after all I'm adding a test that fails just to prove there's a failure, but I'm not pushing any fix for it.

**Comment by pedrobaeza** [comment]
Well, maybe the feature was included and rebasing you get this new code.

@rco-odoo it seems then that this is still not fixed. Has it been fixed is later versions?

**Pull request closed without merging**
