### PR TITLE
[FIX] hr_org_chart: fix data not being reloaded

### PR DESCRIPTION
**Pull request by Williambraecky**
This commit fixes an issue with the org chart since it was converted to
owl, the data would not be reloaded when changing from record to record.
Instead it would always show the data from the first record it ever
loaded.

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

Thanks for the fix :)

**Comment by Williambraecky** [comment]
robodoo r-
Test is failing in enterprise

**Comment by Williambraecky** [comment]
robodoo r+
Issue fixed, it was an infinite loop between onWillRender and render calls

**Comment by Williambraecky** [comment]
robodoo r-

**Comment by Williambraecky** [comment]
robodoo r+

**Pull request closed without merging**
