### PR TITLE
[IMP] im_livechat, *: Refactor JS Public Livechat (step 10)

### PR DESCRIPTION
**Pull request by alexkuhn**
*: website_livechat

This commit is a step towards refactoring the JS of public livechat,
so that it reuses the same architecture as the code of Discuss.
This implies code that uses JS models and OWL components.

Task-2937174

### CODE REVIEW

**Comment by alexkuhn** [comment]
@seb-odoo ci/security fail due to change on this line with `utils.Markup()`:
https://github.com/odoo/odoo/pull/96553/files#diff-9f5ef077990ee56133553ff7a9fdce515ab91300630b68ad6c94b8545da38f79L80

The `utils.Markup()` by itself is unchanged, and the assignation is on same widget.

**Comment by seb-odoo** [comment]
@robodoo override=ci/security
Diff on the line but unchanged markup call.

**Comment by alexkuhn** [comment]
@robodoo r+ squash

**Comment by alexkuhn** [comment]
Hm... well... I think I understand what "squash" option does, and it's not what I thought...
Let's do the usual way and squash my commits by hand then 😅

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
