### PR TITLE
[FIX] stock_account: Wrong average product standard price compute

### PR DESCRIPTION
**Pull request by carlosdauden**
**Description of the issue/feature this PR addresses:**
Wrong average product standard price compute

**Current behavior before PR:**
Sum quantity distinct of total quantity

**Desired behavior after PR is merged:**
Same quantity to right average product standard price compute

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@Tecnativa

### CODE REVIEW

**Comment by sle-odoo** [comment]
@carlosdauden Hi, can you provide a scenario where the AVCO is wrongly computed? We'll be able to complete the tests then. Thanks

**Comment by carlosdauden** [comment]
Any scenario in which forced_qty has value and it is different from qty_done:
https://github.com/odoo/odoo/blob/18ecced716c7c832027db36a1903271230d68f60/addons/stock_account/models/stock.py#L393

**Comment by rafaelbn** [comment]
OPW 1932110

**Comment by nhomar** [comment]
if you add an unit test I supposed this will be gladly accepted.

**Comment by sle-odoo** [comment]
added a test and merged at https://github.com/odoo/odoo/commit/f6c4afe8c317b4cb90080f6388a6c2046e67ff20

thanks

**Comment by pedrobaeza** [comment]
Thanks for the extra test!

**Pull request closed without merging**
