### PR TITLE
[FIX] doc: add parent_of operator

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:

@rco-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
ping @rco-odoo

**Comment by Feyensv** [comment]
@robodoo  r+

**Comment by Feyensv** [comment]
@robodoo retry

**Comment by Feyensv** [comment]
@robodoo retry
:man_facepalming:

**Comment by Feyensv** [comment]
Well, I will rebase and retry tomorrow :'D.
And hope this rte indeterministic bug goes on holidays -_-.

**Comment by Feyensv** [comment]
@robodoo r+
:dango:

**Pull request closed without merging**
