### PR TITLE
[FIX] account: Correctly compute taxes in round_per_line / round_globally behavior

### PR DESCRIPTION
**Pull request by SimoRubi**
Description of the issue/feature this PR addresses:
Link to video in enterprise runbot: https://drive.google.com/file/d/1L2ycDhc6HG3eeto8sudLFFF3phWcGlYJ/view

Here the steps:

0. Activate debug mode;
1. In Accounting > Configuration > Settings, set rounding method "Globally";
2. Create an invoice with unit_price = 348.35, 16 pieces, 4% discount, 22% tax;
3. Check that total is 6527.80.
4. In Accounting > Configuration > Settings, set rounding method "Per line";
5. Create an invoice with unit_price = 348.35, 16 pieces, 4% discount, 22% tax;
6. Check that total is 6527.81.

Current behavior before PR:
Totals in step 3 and 6 are different.

Desired behavior after PR is merged:
Totals in step 3 and 6 are the same (6527.81).

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by SimoRubi** [comment]
@wtaferner Thanks for letting me know that this issue has some history, it seemed very strange to me that this _weird_ implementation of `round_globally` hadn't been noticed yet by someone else.

I'm sure that my proposed solution is too simple but I have verified that it works as expected in my use-case and it seemed that I could contribute a little for moving toward a more complete solution.

**Comment by wtaferner** [comment]
@SimoRubi 
Indeed it has a huge history and is well monitored by some people in the community...my own research is already summarizing the main points what is wrong or should be taken into account by yourself if you want to cover such scenarios...your solution is destroying btw a lot if you take a look at the tests, so really nothing you could fix in the code but more in terms of features...

**Comment by SimoRubi** [comment]
Yes @wtaferner I knew I would've destroyed quite a few tests with this PR..
Actually the 2016 code looks a bit different from what it is now so I have some doubts that your issue is the same as mine, because I have an issue when the precision is increased by `5` (in my case it is not enough) but you have the issue when it is not (at least that is what it seems by the fix in https://github.com/odoo/odoo/pull/8427/files ).

Anway I don't get if you or anyone else is actively working on this or not.

**Comment by wtaferner** [comment]
@SimoRubi 
Sorry I did not come back to you, but I just updated the public repo, so feel free to take a look at [account_tax_b2c](https://github.com/wt-io-it/odoo-addons/tree/11.0/account_tax_b2c) and maybe it will help you to master B2C and B2B in one instance.

**Comment by mart-e** [comment]
Hello,

Thank you for the PR but I will have to reject this, sorry.

The 10.0 is now in end of life cycle and will soon be unsupported. We are only patching critical or security issues. The risk of regressions or introducing side effects is too high.
If this PR still makes sense for upper versions, don't hesitate to resubmit there.

Regards

**Pull request closed without merging**
