### PR TITLE
17.0 base auto fixes lpe

### PR DESCRIPTION
**Pull request by kebeclibre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
robodoo rebase-ff

**Comment by kebeclibre** [comment]
@odoo/rd-security Can I get an override ? I'm just putting the request's parameters inside the eval context of a ir.action.server ?

**Comment by kebeclibre** [comment]
@mart-e 
Th point is to allow a user to access the request's parameters when an action server has been triggered by a base.automation webhook. That way, the action server can do the right operation on the right record, which it can't before this fix.
On the Odoo task, this solution has been preferred security wise to the one putting the whole request in the eval context (as website already does).

Obviously it contains arbitrary things, though in an dict, so I suppose that since safe_eval is not in the eval context, it is not possible to execute someone else's code, at least when the request is a json one.
For http requests, would that be safer to exclude the files and form data to only keep the args (which I understand are the queryParams) ?
Am I totally wrong here or just partially ?

**Comment by kebeclibre** [comment]
@odony @mart-e 
changes made: only query parameters are available in the payload for an http request. For a json request, the full json data is exposed.

**Review by mart-e — APPROVED** [review]
@robodoo override=ci/security
Reason: only args content of the request, using jsonsafe

**Comment by kebeclibre** [comment]
robodoo rebase-ff r+

**Pull request closed without merging**
