### PR TITLE
[FIX] l10n_vn: wrong pos receivable account

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
-According VietNam Circular , Receivable account we should use for POS is 131 account, not 132
see https://thuvienphapluat.vn/van-ban/Doanh-nghiep/Thong-tu-200-2014-TT-BTC-huong-dan-Che-do-ke-toan-Doanh-nghiep-263599.aspx , select English version - Section 'Short-term receivables from customers' to read it and we will see 132 account is not appropriate

image

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Replace the work of https://github.com/odoo/odoo/pull/105085

**Comment by duong77476-viindoo** [comment]
Dear Mr @lordkrandel Can you take a look?

**Comment by duong77476-viindoo** [comment]
Hi Mr @dbkosky Can you review

**Review by dbkosky — CHANGES_REQUESTED** [review]
@duong77476-viindoo 

From the documentation you appear to be correct. :+1: 
Can you adapt this to target V15, and we can then forwardport the changes into V16 from there.

**Comment by duong77476-viindoo** [comment]
> @duong77476-viindoo
> 
> From the documentation you appear to be correct. 👍 Can you adapt this to target V15, and we can then forwardport the changes into V16 from there.

@dbkosky Done sir thank you very much

**Comment by dbkosky** [comment]
@Levizar can we merge?

**Review by dbkosky — APPROVED** [review]

**Review by Levizar — APPROVED** [review]
@robodoo r+

**Comment by Levizar** [comment]
Hello @duong77476-viindoo , thanks for this straight to the point and well documented PR. That's much appreciated!

**Comment by duong77476-viindoo** [comment]
> Hello @duong77476-viindoo , thanks for this straight to the point and well documented PR. That's much appreciated!

You 're welcome, glad that i can help hehe.

**Pull request closed without merging**
