### PR TITLE
14.0 fix snippet preview when scrolling during drag bvr

### PR DESCRIPTION
**Pull request by bvr-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bvr-odoo** [comment]
@qsm-odoo We dont need this fix in master.. It works in master because of the changement in the structure of the editor elements

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
@fw-bot ignore
@bvr-odoo could you add some comments in the code to explain?

**Comment by bvr-odoo** [comment]
> @fw-bot ignore
> @bvr-odoo could you add some comments in the code to explain?

ok done :+1:

**Comment by qsm-odoo** [comment]
This PR don't work for me... maybe related to https://github.com/odoo/odoo/pull/61268 let's wait for its forward-port...

**Comment by bvr-odoo** [comment]
> This PR don't work for me... maybe related to #61268 let's wait for its forward-port...

Yes we need the other fixes, because as long as we use the class 'd-none' and not the class 'invisible' on the drop zones it can't work

**Comment by qsm-odoo** [comment]
Now working nicely after rebase :+1: 
@robodoo r+

**Pull request closed without merging**
