### PR TITLE
[IMP] odoo color classes

### PR DESCRIPTION
**Pull request by stefanorigano**
enterprise:
- https://github.com/odoo/enterprise/pull/25700

Prior to this PR branded UI components were styled exclusively in
raw SCSS using the '$o-brand-odoo' variable.

This leaded to unnecessary code repetitions since, to achieve the same
visual result, each module defined its own classes.
Visual inconsistencies were frequent too since each module defined its
own variations for interactive states (eg :hover).

This commit injects '$o-brand-odoo' into bootstrap's default
'$theme-color' map, allowing the framework to automatically generate
odoo utility/contextual classes.
These classes can be used to handle text, backgrounds, borders and
buttons wherever needed.

Part of the overall v16 SCSS optimization/restyle, task-2704984.

task-2800721

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @pparidans 👋 
"odoo-color" utility classes.
Enterprise: https://github.com/odoo/enterprise/pull/25700

**Comment by stefanorigano** [comment]
hello @pparidans , just a reminder ;)

**Review by pparidans — CHANGES_REQUESTED** [review]
Globally looks :ok_hand:  to me and will help with the color consistency.
Mainly the `map-merge` thing we discussed about to take care about.

**Comment by stefanorigano** [comment]
@pparidans , you can have a look, thanks

**Review by pparidans — APPROVED** [review]
LGTM :sunglasses:

**Comment by pparidans** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
