### PR TITLE
[IMP] web, mail: adapt "Add a Reaction" icon

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Prior to this commit, "Add a Reaction" and "View Reactions" buttons had the same icon, which was confusing.

This PR adapts the "Add a Reaction" icon to make it more recognizable.

task-3577008

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hey @stefanorigano 👋 This PR is ready for review, could you take a look at it ?

**Review by stefanorigano — CHANGES_REQUESTED** [review]
Thanks @Brieuc-brd , good 👍 

For consistency, since this will be the new icon for "Add an emoji", we should use it in the main composer as well 😉

There shouldn't be other occurrences, but it's worth checking 

image

**Comment by Brieuc-brd** [comment]
Hey @stefanorigano I updated the branch + rebase :
The diff : https://github.com/odoo/odoo/compare/100d90575f1e8b914e37ef237d7970d0fb511eb4..5513e0915d8df6fbf6c1b46ceae30c2244442aee

Could you have a look ?

**Review by stefanorigano — CHANGES_REQUESTED** [review]
Thanks @Brieuc-brd 👍 
Result is good, just one little remark about naming.

Even if the `oi` lib currently coexist with the `fa` one, we have to assume that it could be used standalone.
This (+ consistency) suggests me  that we should rename  `oi-add-emoji` to `oi-smile-add`. Beside clarifying what you'll actually render on screen (emojii is a bit vague), it  would simplify toggle classes (eg. t-att)

-  oi-smile
-  oi-smile-add
-  oi-smile-remove
-  oi-smile-star
-  oi-smile-...

**Comment by Brieuc-brd** [comment]
Thanks @stefanorigano 👍 
I updated the branch, (the diffs : https://github.com/odoo/odoo/compare/723c8a27421e662dcf8681eb509e60a469d378b1..0fd6399a5d41fba93fbd7ec2f506b058467a16ea) and rebased it.

**Review by stefanorigano — APPROVED** [review]
Thanks @Brieuc-brd , LGTM 👍 

@odoo/rd-discuss , all yours :)

**Comment by alexkuhn** [comment]
> For consistency, since this will be the new icon for "Add an emoji", we should use it in the main composer as well 😉

I disagree with this part of the change. The "+" icon is relevant on message action to highlight this button contributes to a change on the message. In the composer, all buttons are used to compose the message, so there's no need to make icons heavier with a `+` that makes the icon harder to recognize than the plain emoji icon.

**Comment by alexkuhn** [comment]
Consistency is important, but context also matters: an icon should stay as simple as the context allows. The context of message actions requires a more specific icon for add a reaction and view reactions, thus the 2 versions of emoji icons. In the composer there's only one menu and the simplest icon is the plain emoji, therefore there's no reason to pick the heavier icon.

By the way, other messaging apps keep the plain emoji icon rather than the version with "+" in the composer, so it's consistent with them 😉

**Comment by paju-odoo** [comment]
Hi @alexkuhn @stefanorigano,

I must say I agree with Alex on this one, the + icon doesn't really add value when composing messages. 
There's a difference between typing an emoji in a message and managing reactions (add/see). They're different features, and I'd prefer to keep emojis as they are now. 
I understand the consistency issue, but it seems to be the same behavior in other applications.

**Comment by Brieuc-brd** [comment]
Hey @alexkuhn 👋 
I updated the branch :) (https://github.com/odoo/odoo/compare/9fbc5b370da1f8a14264c979aede28057ce6b036..c2af20fa47c16221ce680c8072541dae521156ab) and rebased

**Review by alexkuhn — APPROVED** [review]
@robodoo r+ delegate+
Hopefully runbot's green (I just rebuilt the problematic build). Probably need rebase if it still fails

**Pull request closed without merging**
