### PR TITLE
fix #4692: propagate owner to backorder move

### LINKED ISSUE #4692: restrict_partner_id (i.e. stock owner) is never propagated to the backorder
The move has a field `restrict_partner_id` that is used when reserving quants. The `owner_id` field on the picking is mostly unused.

When creating a backorder, the `restrict_partner_id` is not copied, because the method `split` at 

https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2439

takes a `restrict_partner_id` parameter that is never passed along, so in the backorder the field is always empty. I think we should just copy it along with the other fields.

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by beledouxdenis** [comment]
Hello Leonardo,

I am not quite sure why this is useful. Is this `restrict_partner_id` set with a default value somewhere ? By overriding `default_get` or with a `default_restrict_partner_id` key within the context ?

Because if this only 'in case of' custom default values, I see other places where this should be done, or even other variables:
 - Why not `restrict_lot_id` ?
https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2581
 - Why not in the `scrap` method ?
https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2521-L2523

Can you please explain a bit your use case ?

Thanks in advance

**Comment by lepistone** [comment]
Hi @beledouxdenis!

My use case is: I have a move where the owner is not empty, and I do a partial delivery. I expect the backorder move to have the same owner as the original.

I guess the other things that you mention should be done, too.

See similar PRs that were merged: #6969 #5824 #5166.

**Comment by beledouxdenis** [comment]
Leonardo, 

Well, I did not pay enough attention, and I have not seen that there was a longer description within the issue #4692, and that we were in the context of a `copy`. Therefore, my thought above regarding default values was just non-sense.

I just merged your proposal in Odoo 8.0, @3349187aab929cda9db320769831532ddd0b10cb.

Thank you for your contribution :).

Regards,

**Comment by lepistone** [comment]
Thank you Denis!

**Pull request closed without merging**
