### PR TITLE
[FIX] l10n_be_invoice_bba: missing translation ability 

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Without this the error message will always be in English, no matter the language of the end-user.
This PR fixes this.

Current behavior before PR: The warning is always in English

Desired behavior after PR is merged: The warning is in the user his language, if there is a translation.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e I'm not sure about this one. In the .pot file there is already this block:
```
#. module: l10n_be_invoice_bba
#: constraint:account.invoice:0
msgid "Invalid BBA Structured Communication !"
msgstr ""
```

It links to the account.invoice though so I added:
```
#. module: l10n_be_invoice_bba
#: code:addons/l10n_be_invoice_bba/models/account_invoice.py:37
#, python-format
msgid "Invalid BBA Structured Communication !"
msgstr ""
```

Not sure if I should/can merge them in one translation or if this is fine?

**Comment by mart-e** [comment]
Hi !

The source entries can not be duplicated (invalid .po format, would be rejected by Transifex).
Instead you have to mix both entries.

```
#. module: l10n_be_invoice_bba
#: constraint:account.invoice:0
#: code:addons/l10n_be_invoice_bba/models/account_invoice.py:37
#, python-format
```

If you are not sure, use the export tool in Settings > Translations > Export translations

**Comment by Yenthe666** [comment]
@mart-e yep I was already thinking this was the case.
In fact, I exported the translations with the export translations tools, Odoo makes two for them too. That is what made me doubt it.
Want me to fix it in this PR?

**Comment by tivisse** [comment]
@Yenthe666 

FIxed in 10.0 at https://github.com/odoo/odoo/commit/054e06e223fd08a6944267fa3c74042828cb051d

Don't forget that we cannot have twice the same label in the pot file.

Thanks for the feedback

Yannick.

**Pull request closed without merging**
