### PR TITLE
[CLA] David Arnold, DevCO

### PR DESCRIPTION
**Pull request by blaggacao**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by blaggacao** [comment]
@mart-e quick and easy merge. We have some PR builds failing because of this.

**Comment by mart-e** [comment]
Hello,

Why do you sign the CLA twice? I have already merged the one for the corporate at 270b2d0a784cccacfd72ceaea9f9aefadd995bc5 which uses the same email

**Comment by blaggacao** [comment]
Out of ignorance :smile:

**Comment by mart-e** [comment]
Ok no problem, some people like to have two signatures when they are working for a company and freelance but then, they usually use different emails to be able to detect which contribution belongs to which :)

**Pull request closed without merging**
