### PR TITLE
[FIX] l10n_ar/cl: starting sequence

### PR DESCRIPTION
**Pull request by zaoral**
Two fixes:

1. Main fix: When getting l10n_ar/l10n_cl starting_squence check with the proper company (self.company_id) and not self.env.company_id
2. Demo data fix: use expo journal on demo expo refund

--
I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

### CODE REVIEW

**Comment by Danisan** [comment]
Good, thanks! +1

**Comment by ren-odoo** [comment]
Thank you for the fix @zaoral 

I checked the sequence on the demo data and it LGTM.  @jco-odoo this PR is readuy for your check. 

cc. @vbe-odoo @fvz-odoo

**Review by epictete — APPROVED** [review]
@jco-odoo LGTM.

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
