### PR TITLE
[FIX] sale: compute analytic defaults based on default rules

### PR DESCRIPTION
**Pull request by william-andre**
Reproduce:
* Create default analytic rules
* Create a quotation/sale order.

Before:
Default analytic rules were not added on sales orders, like they are on
invoices and purchase orders.

After:
Same behavior on all documents.

This behavior was mistakenly removed during a refactoring:
https://github.com/odoo/odoo/commit/3c67bb20feb42f16799b7491411e213b818c4f83

[opw-2800936](https://www.odoo.com/web#id=2800936&cids=1%2C5%2C14&model=project.task&view_type=form)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Feyensv — COMMENTED** [review]
Honestly, I'd find it safer for a stable version if you only modified `_prepare_invoice_line` like it was done before your removal :thinking:.

(Also, I think a test would be useful to cover the usecase, since nobody cared for ~3years)

**Comment by qdp-odoo** [comment]
@william-andre bug report and the commit linked are against v15. Soo I'm confused :nerd_face:

**Comment by william-andre** [comment]
@qdp-odoo I checked and the bug is present in version 14.0 too, what do you mean?


> Honestly, I'd find it safer for a stable version if you only modified `_prepare_invoice_line` like it was done before your removal thinking.

@Feyensv You mean simply ignoring the fields set on the sale's order? But that's just wrong? If there is no value set on the sales order, there shouldn't be any on the invoice; that is expected. The issue is that the default values are not computed correctly.

**Comment by Feyensv** [comment]
What I meant was using the SO/SOL values if set, and otherwise use your computed defaults, but modifying the field logic to a compute seems quite big for a stable change imho.
Also, please add some tests to cover the problem :pray:

**Comment by william-andre** [comment]
> But modifying the field logic to a compute seems quite big for a stable change imho.

It has been done as a bugfix in the past without any issues for Invoices and Purchase orders, people were happy about it and I didn't see any bad feedback.

**Comment by Feyensv** [comment]
> > But modifying the field logic to a compute seems quite big for a stable change imho.
> 
> It has been done as a bugfix in the past without any issues for Invoices and Purchase orders, people were happy about it and I didn't see any bad feedback.

It'll at least break the existing flow where an analytic account is automatically created for expense orders (See `_create_analytic_account` method & logic).

**Comment by william-andre** [comment]
We had a discussion. DALA asked me to ask TSB, who agrees with what I did.

**Comment by tivisse** [comment]
Hello,

Thanks for the fix.

IMO this could break the logic on analytic account create on the order validation.

See:
```py
    def _action_confirm(self):
        """ Implementation of additionnal mecanism of Sales Order confirmation.
            This method should be extended when the confirmation should generated
            other documents. In this method, the SO are in 'sale' state (not yet 'done').
        """
        # create an analytic account if at least an expense product
        for order in self:
            if any(expense_policy not in [False, 'no'] for expense_policy in order.order_line.mapped('product_id.expense_policy')):
                if not order.analytic_account_id:
                    order._create_analytic_account()

        return True
```

But by looking at the original commit: https://github.com/odoo/odoo/commit/04dd0a2dd481ed2f9d134df8fbafb67edb07642e it seems that the only goal of this was to be able reinvoiving on expenses, which would still be achieved with your change. 

Conclusion: We can consider this change ok --> LGTM.

**Review by tivisse — APPROVED** [review]

**Comment by qdp-odoo** [comment]
okay let's go then

@robodoo r+

**Pull request closed without merging**
