### PR TITLE
[FIX] web: Display PDF correctly (broken font)

### PR DESCRIPTION
**Pull request by macadelic80**
What are the steps to reproduce your issue ?

    1. Install eSign
    2. Upload attached PDF (links below) as template

What is currently happening ?

    The font is broken

What are you expecting to happen ?

    Display PDF correctly

Patch: mozilla/pdf.js@977397e
See: https://github.com/mozilla/pdf.js/pull/6270/files

Corrupted pdf: 

https://github.com/mozilla/pdf.js/blob/977397ebfd1757706906694d49c3db9d3266583e/test/pdfs/issue215.pdf
https://github.com/mozilla/pdf.js/blob/977397ebfd1757706906694d49c3db9d3266583e/test/pdfs/bug1186827.pdf

opw-2410011

### CODE REVIEW

**Comment by abz-odoo** [comment]
@fw-bot 13.0

**Comment by abz-odoo** [comment]
fw-bot 13.0

**Comment by yelizariev** [comment]
You can make direct link to pdf in commit description:

https://github.com/mozilla/pdf.js/blob/977397ebfd1757706906694d49c3db9d3266583e/test/pdfs/issue215.pdf

https://github.com/mozilla/pdf.js/blob/977397ebfd1757706906694d49c3db9d3266583e/test/pdfs/bug1186827.pdf

**Comment by abz-odoo** [comment]
Thank you @yelizariev 
I forgot this

**Comment by abz-odoo** [comment]
@simongoffin

**Comment by abz-odoo** [comment]
@fw-bot up to 13.0

**Review by simongoffin — APPROVED** [review]

**Comment by simongoffin** [comment]
robodoo delegate+

**Comment by abz-odoo** [comment]
robodoo r+

**Pull request closed without merging**
