### PR TITLE
[REF] spreadsheet: convert tests to Hoot

### PR DESCRIPTION
**Pull request by LucasLefevre**
These commits convert spreadsheet test to Hoot

### CODE REVIEW

**Comment by LucasLefevre** [comment]
robodoo fw=no

**Comment by pro-odoo** [comment]
@robodoo override=ci/style
Override because the terms which trigger the warnings are used for custom class names or directly in inlined css.

**Comment by pro-odoo** [comment]
This error in ci-style should not be ignored:
```

odoo/addons/spreadsheet/manifest.py:108('remove', 'spreadsheet/static/tests/legacy/**/*'), # to remove when all legacy tests are portedE261 coll 64: Insert at least two spaces before an inline comment
--


[odoo/addons/spreadsheet/manifest.py:108](https://github.com/odoo/odoo/blob/8f453f463173a570ff2de01348b9e7cf00f7081d/addons/spreadsheet/%3Cins%3Emanifest%3C/ins%3E.py#L108)
('remove', 'spreadsheet/static/tests/legacy/**/*'), # to remove when all legacy tests are ported
[E261](https://docs.astral.sh/ruff/rules/too-few-spaces-before-inline-comment) coll 64: Insert at least two spaces before an inline comment
```

**Comment by LucasLefevre** [comment]
robodoo rebase-merge r+

**Comment by LucasLefevre** [comment]
robodoo retry

**Pull request closed without merging**
