### PR TITLE
[FIX] mail: dialog properly manage overflow for long content

### PR DESCRIPTION
**Pull request by alexkuhn**
Before this commit, when content of dialog was long, content
overflow but was not scrollable, which makes bottom unreachable,
which is especially a problem when buttons are at the bottom.

This problem solves the issue by adding classname `modal` to
dialog. This classname puts proper handling of overflow of
dialog and its content.

Also remove `align-items-center` so that top doesn't overflow
in isolation from the rest of content, which made top unreachable.

Task-2973866

### CODE REVIEW

**Comment by seb-odoo** [comment]
Possibly an issue since v14 with follower subtype (on a model with a lot of subtypes)

**Comment by alexkuhn** [comment]
This is the exact same simple fix in 14.0. Will make a PR that targets this version

**Comment by alexkuhn** [comment]
14.0 PR: https://github.com/odoo/odoo/pull/99620

**Comment by seb-odoo** [comment]
done in v14

**Pull request closed without merging**
