### PR TITLE
[FIX] event_crm: improve multi registrations grouping

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
When being order-based, several registrations are used to create a new
lead. In some cases we might end up with several possible langs due
to multiple visitors. We should take the first found one, as lang is
a m2o on lead model.

When running on registrations without linked SO, registrations are
grouped by "event" in case of group-based lead generation. We should
also group by create_date, as same event - same create_date indicates
tickets belong to the same "group".

Task-3940853

Co-Authored-By: Jeremy Hennecart <jeh@odoo.com>

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@tfr-odoo

**Comment by tde-banana-odoo** [comment]
@tfr-odoo

**Review by tfr-odoo — APPROVED** [review]
Tested with the OXP, no more issue with visitor lang and no more grouping random people on the same leads. Works well thank you

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Pull request closed without merging**
