### PR TITLE
[FIX] sale: fix completely broken template

### PR DESCRIPTION
**Pull request by tde-banana-odoo**

### CODE REVIEW

**Comment by mart-e** [comment]
My translations :cry:

**Comment by tde-banana-odoo** [comment]
Strings are the same normally, even fi I suppose html translator does magic things. Should I regenerate something ?

**Comment by mart-e** [comment]
No html translator does not work on jinja, you change one comma in a mail.template, you fuck up the whole translation. This is one of the reason I want that we move everything to QWeb.

**Comment by tde-banana-odoo** [comment]
It is not the only reason note. But ok I will update translations. Still has to be tested.

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
