### PR TITLE
[IMP] *: remove useless keys from manifests

### PR DESCRIPTION
**Pull request by niyasraphy**
Remove most values uselessly specified because giving the same value as
the default one (see _DEFAULT_MANIFEST in odoo/modules/module.py)

    auto_install is Falsy by default
    author is Odoo SA by default
    summary & description are empty strings by default
    application is False by default
    test, demo, depends and data are empty lists by default

This will reduce noise/inconsistencies between manifests specifications,
simplify analysis of manifests content.

Reference to:  https://github.com/odoo/odoo/commit/42bad1a6d21e086e3bb766f9813d65902b3c232a

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
hi @Feyensv ,
if you have time, can you review this.

with similar approach can we remove 'installable': True also ?

thanks

**Review by Feyensv — COMMENTED** [review]
Well, I didn't have the time to make it when i did the commit you referenced, but this is the kind of cleanup that we can do endlessly unless we add a check to make sure no new module adds useless keys.

Could you please avoid doing those kind of global 'cleanup' changes in the future ?
We do them internally when we have the time (quickly, or while avoiding the ping on all teams) but here, when noticing it's not one of us doing the PR, there might be 15+ people going through your diff (and spending time on it) when it doesn't really matter :confused:.

Note: if you copy/paste a commit logic and message, at least do it completely and keep the commit message, not only the title.  You kept it in the PR description, but it should be in the commit as well. A commit should be self-explaining, we shouldn't have to look at the PR to have the detailed explanation.

**Comment by niyasraphy** [comment]
ah sorry @Feyensv ,
i didn't think from the perspective of your side and i understand it now. I will keep these things in mind.
thank you for your time

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
