### PR TITLE
[FIX] l10n_sa_edi : neutralize

### PR DESCRIPTION
**Pull request by mao-odoo**

### CODE REVIEW

**Comment by mao-odoo** [comment]
Hi @jco-odoo 

Can you review this neutralization that was missing in the new l10n_sa_edi module that you merged 2 weeks ago in https://github.com/odoo/odoo/pull/106212 ? 

Thanks in advance!

**Comment by jco-odoo** [comment]
@mao-odoo I am afraid l10n_es_edi_tbai still needs one too.

**Comment by jco-odoo** [comment]
@mebe-odoo Should we clear the certificates or something?

**Comment by mao-odoo** [comment]
> I am afraid l10n_es_edi_tbai still needs one too.

isn't it already handled by   https://github.com/odoo/odoo/blob/7cd967a2f5dec0c967322d23c286e5323f40641a/addons/l10n_es_edi_sii/data/neutralize.sql#L1  ? @jco-odoo 



> Should we clear the certificates or something?

if the sandbox is a "real" sandbox that does its job properly, it may not be strictly necessary  , IMO

**Comment by jco-odoo** [comment]
@mao-odoo You are right.  It is the one from _sii

**Comment by jco-odoo** [comment]
Here, I suppose we need something in v15 as well.

**Comment by mao-odoo** [comment]
> Here, I suppose we need something in v15 as well.

the standard neutralizations don't exist pre-v16 (well technically there is another different system in 15.2 but it was never used anywhere)

I've already written the neutralization script for saas, paas, upgrade and support tools, to handle the v15 and later cases, don't worry ;)
https://github.com/odoo/internal/pull/2304
https://github.com/odoo/support-tools/pull/546
https://github.com/odoo/paas/pull/702
https://github.com/odoo/upgrade-platform/pull/399

**Comment by jco-odoo** [comment]
@mao-odoo @mebe-odoo Let's go with this first.  We can add additional clean ups necessary if they are in handy.

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
