### PR TITLE
[FIX] account: error on tax rounding

### PR DESCRIPTION
**Pull request by nim-odoo**
- Active 'Round Globally'
- Create the tax:
  Amount: 21 %
  Tax Included
- Create the following invoice:
  Line 1: qty 1.0, price 11.90
  Line 2: qty 1.0, price 2.80

The Taxes amount is 2.56 while it should be 2.55. Indeed, it should be:

2.0652893 + 0.4859504 = 2.5512397 => 2.55

This is because the `base` amount used in the tax computation is rounded
to the currency decimal.

opw-2181486

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
PR for 12.3: https://github.com/odoo/odoo/pull/45701

**Comment by smetl** [comment]
@nim-odoo The tax computation is working fine. This is the actual expected behavior.

11.90 / 1.21 ~= 9.83 as price_subtotal, 2.07 as tax amount.
2.80 / 1.21 ~= 2.31 as price_subtotal, 0.49 as tax_amount.

amount_untaxed = 9.83 + 2.31 = 12.14 OK
amount_tax = 2.56
amount_total = 14.7

With your fix:

11.90 / 1.21 = 9.834710744  ~= 9.83 as price_subtotal, 2.065289256 as tax amount.
2.80 / 1.21 = 2.314049587 ~= 2.31 as price_subtotal, 0.485950413 as tax_amount.

amount_untaxed = 9.834710744 +2.314049587 ~= 12.15 != 12.14 = 9.83 + 2.31 NOT OK
amount_tax = 2.55
amount_total = 14.6

For example:
https://github.com/odoo/odoo/issues/14673

**Comment by nim-odoo** [comment]
This is the result in v12:

v12

This is the result in v13:

v13

This is the result in v13 with my fix:

v13 fixed

**Comment by smetl** [comment]
@nim-odoo Because this behavior has been fixed in saas-12.3

**Comment by smetl** [comment]
@nim-odoo After discussions with qdp, the amount total must be 14.7 and we want the amount untaxed remains 12.14. Then, mathematically speaking, the amount tax must be 2.56 in that case.
I'll make the fix that is the missing JS-part of the following PR:
https://github.com/odoo/odoo/pull/40847

**Pull request closed without merging**
