### PR TITLE
[IMP] mail: move code from components to models (PersonaImStatusIcon)

### PR DESCRIPTION
**Pull request by oomsveta**
+ Turn props on component into fields on PersonImStatusIconView model
+ Move handler from component methods to model record methods

Task-3004188.

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]
LGTM, squash then merge
@robodoo delegate+

**Comment by oomsveta** [comment]
robodoo r+

**Comment by alexkuhn** [comment]
@oomsveta `ci/upgrade_enterprise` red. It looks like branch is mistakenly considered as `16.0` somehow.

**Comment by oomsveta** [comment]
> @oomsveta `ci/upgrade_enterprise` red. It looks like branch is mistakenly considered as `16.0` somehow.

I try to rebase, let's see if it can be of any help

**Comment by oomsveta** [comment]
robodoo r+

**Pull request closed without merging**
