### PR TITLE
[IMP][I18N][14.0] l10n_vn: Update name account and translation file

### PR DESCRIPTION
**Pull request by tranngocson1996**
This PR
----------
In comparison to the Chart of Account in Viet Nam, your Vietnamese translation is wrong. So, I want to contributor for you. Plz review !!!
You can refer to here: https://erponline.vn/blog/blog-5/post/vietnam-chart-of-accounts-under-the-vietnamese-accounting-standards-99

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tranngocson1996** [comment]
@FlorianGilbert plz review !!!

**Comment by tranngocson1996** [comment]
> Not sure to understand why you link https://erponline.vn/blog/blog-5/post/vietnam-chart-of-accounts-under-the-vietnamese-accounting-standards-99 ; what they do on that link seem to be exactly what we were doing before, right? So, what are you basing yourself on to change it?

@oco-odoo  Thank you for reply
I mean your Vietnamese translation is wrong. So, in general, the vietnamese accountants got confused.

**Comment by tranngocson1996** [comment]
@oco-odoo do you have any problem? any thing else

**Review by oco-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
