### PR TITLE
[IMP]website_forum: make method private

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

Cc: @odony 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Two birds with one stone, could we take the advantage to remove the `api.one`?

**Comment by sswapnesh** [comment]
Absolutely we can but AFAIK @Elkasitu will do this in one stone across all place in https://github.com/odoo/odoo/pull/29511

**Comment by Elkasitu** [comment]
you can just apply the following patch if you want

```diff
-    @api.one
     def _send_forum_validation_email(self, forum_id=None):
-        if not self.email:
-            return False
-        token = self._generate_forum_token(self.id, self.email)
-        activation_template = self.env.ref('website_forum.validation_email')
-        if activation_template:
-            params = {
-                'token': token,
-                'id': self.id,
-                'email': self.email}
-            if forum_id:
-                params['forum_id'] = forum_id
-            base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
-            token_url = base_url + '/forum/validate_email?%s' % urls.url_encode(params)
-            with self._cr.savepoint():
-                activation_template.sudo().with_context(token_url=token_url).send_mail(
-                    self.id, force_send=True, raise_exception=True)
-        return True
+        values = []
+        for user in self:
+            if not user.email:
+                values.append(False)
+                continue
+            token = user._generate_forum_token(user.id, user.email)
+            activation_template = self.env.ref('website_forum.validation_email')
+            if activation_template:
+                params = {
+                    'token': token,
+                    'id': user.id,
+                    'email': user.email}
+                if forum_id:
+                    params['forum_id'] = forum_id
+                base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
+                token_url = base_url + '/forum/validate_email?%s' % urls.url_encode(params)
+                with user._cr.savepoint():
+                    activation_template.sudo().with_context(token_url=token_url).send_mail(
+                        user.id, force_send=True, raise_exception=True)
+            values.append(True)
+        return values
```

either way it's gonna make a conflict in my branch :stuck_out_tongue:

**Comment by sswapnesh** [comment]
Else you can make this method private in your PR directly (If it is allowed in Same PR) and close this

**Comment by Elkasitu** [comment]
A list is what `api.one` [returns](https://github.com/odoo/odoo/blob/master/odoo/api.py#L372) and some methods that call `api.one` expect a list, so returning anything else is potentially an error.

But you can leave your PR as-is

**Comment by odony** [comment]
Thanks for the PR, I guess we can keep the simple version for now. Rebased, edited and merged at 1971557fdd4087c3856c1c46ecae71e046870042

**Pull request closed without merging**
