### PR TITLE
[FIX] website: need to load payment translation too.

### LINKED ISSUE #40826: [11.0] Payment error not translate in website
**Impacted versions:**
11.0
**Steps to reproduce:**
1. Load a language other than English.
2. Select the downloaded language.
3. Add product to cart
3. Perform payment process, but do not select any payment method.
4. The error is displayed, but it is not translated into the selected language, even if the translation is done.

**Current Behavior:**
The error message is not translate
**Expected Behavior:**
The error message in the client's language

**Video link / screenshot (optional):**
https://youtu.be/cSsxEPEvx4Y

### PR DESCRIPTION
**Pull request by JKE-be**
Closes #40826

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
It was already done in 12.0 at 0eee7c68ff427a1c27cc265d56423 
@nle-odoo any reason not to do it in 11.0 ?

By the way, the 12.0 patch does `=` while this one uses `=ilike` (which is better I think)
In website we had to use `like` because some modules do not respect conventions (e.g. openerp_website)

**Comment by JKE-be** [comment]
btw should be in website_payment and not payment imo ;)

**Comment by mart-e** [comment]
Good question, can't we have frontend payment resources without website? Like paying a quotation that was sent through subscription module?

**Comment by JKE-be** [comment]
mhhh probably ...
go for payment ...

In worst case, it will be not called...

**Comment by nle-odoo** [comment]
yes in 11.0 there is also `account_payment` and `sale_payment` (used by `sale_subscription`) without website requirement

> @nle-odoo any reason not to do it in 11.0 ?

nope, I think it was not necessary in my case since it was just for something added in 12.0 (6ed44181d0).

**Comment by JKE-be** [comment]
@robodoo r+

**Pull request closed without merging**
