### PR TITLE
[FIX] website_sale: fix concurrent update

### PR DESCRIPTION
**Pull request by rdeodoo**

### CODE REVIEW

**Comment by rdeodoo** [comment]
Thanks @seb-odoo & @KangOl for investigating

**Comment by KangOl** [comment]
@robodoo rebase-ff r+ p=0

**Comment by rdeodoo** [comment]
1 day 3 men 2 lines of code :neckbeard:

**Comment by KangOl** [comment]
@robodoo r-

**Comment by KangOl** [comment]
@robodoo r+ p=0

**Comment by KangOl** [comment]
@robodoo retry

**Comment by seb-odoo** [comment]
So probably replace the line with an error by `elif abandoned_order.id != request.session.get('sale_order_id'):`

**Comment by KangOl** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo retry again

**Comment by Yenthe666** [comment]
> 1 day 3 men 2 lines of code :neckbeard:

@rdeodoo you can now make that two days ;) Lovely use of time.

**Comment by rdeodoo** [comment]
@robodoo retry

**Comment by d-fence** [comment]
well done :champagne: guys

**Pull request closed without merging**
