### PR TITLE
[FIX] mass_mailing: text style dropup should be visible

### PR DESCRIPTION
**Pull request by aath-odoo**
**Current behavior before PR:**

Text style and text size drop-up were not fully visible due to overflow.

**Desired behavior after PR is merged:**

Added a scroll property to give accessibility to the items.

Task-3100123

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@aath-odoo Could you squash the commits please ?

**Comment by dmo-odoo** [comment]
@aath-odoo Also, the commit message is missing the id of the task

**Comment by aath-odoo** [comment]
> @aath-odoo Could you squash the commits please ?

Done.

**Comment by dmo-odoo** [comment]
@aath-odoo Thanks !

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
