### PR TITLE
fix keyboard navigation in filter dropdown

### PR DESCRIPTION
**Pull request by msh-odoo**
Task:https://www.odoo.com/web#id=2057012&action=333&active_id=133&model=project.task&view_type=form&menu_id=4720

Pad: https://pad.odoo.com/p/r.ee54e3c3375f4b8c015abf5789d1fd65

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by msh-odoo** [comment]
@aab-odoo Can I have your input on this, it seems issue from bootstrap dropdown that navigation in dropdown stops working if there is any hidden item(filter) in between of dropdown, to fix it, I put all invisible filters at last, I posted bootstrap issue, what do you think should we fix it this way?

**Comment by aab-odoo** [comment]
@msh-odoo What's the point of having invisible items in the DOM? Can they become visible at some point? I don't think so. If not, we can simple filter them out and don't render them.

**Comment by msh-odoo** [comment]
@aab-odoo Previous code was like that, we were filtering out invisible filters but from following commit we considered invisible filter: https://github.com/odoo/odoo/commit/7c95dbf36664988a883f84a8f60026039c0fb664#diff-7ff998e06f9296609425336c5e3aa496

It is done to apply filter from context but keep invisible from dropdown.

**Comment by aab-odoo** [comment]
@msh-odoo Ok then I'll wait for a couple of days to see if they (bootstrap) can fix the issue on their side

**Comment by msh-odoo** [comment]
@aab-odoo here is the issue link of bootstrap: https://github.com/twbs/bootstrap/issues/29405

**Comment by Polymorphe57** [comment]
The fix is not good. The filter menu is broken
when updated.
New PR: https://github.com/odoo/odoo/pull/37567

**Pull request closed without merging**
