### PR TITLE
[IMP] sale: little UX improvement

### PR DESCRIPTION
**Pull request by fdamhaut**
task-3750550

### CODE REVIEW

**Comment by Feyensv** [comment]
@robodoo squash

**Comment by arj-odoo** [comment]
@robodoo r+

**Comment by arj-odoo** [comment]
@robodoo r+

**Comment by arj-odoo** [comment]
@robodoo delegate+

**Comment by arj-odoo** [comment]
@robodoo r+

**Comment by arj-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
