### PR TITLE
[FIX] base: correct phone_code for RDC and Congo

### PR DESCRIPTION
**Pull request by rivo2302**
### [FIX] base: correct phone_code for RDC and Congo
**Description of the issue/feature this PR addresses:**
I've resolved an issue related to the phone codes for RDC and Congo on Odoo. The phone codes were swapped, so I've corrected them to ensure the correct phone codes are used.

**Current behavior before PR:**
The phone codes for RDC and Congo were swapped, causing incorrect assignment.

**Desired behavior after PR is merged:**
After merging this PR, the phone codes for RDC and Congo will be correctly assigned, resolving the issue.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rivo2302** [comment]
@h4818

**Comment by h4818** [comment]
Hi @rivo2302 
Please check the commit message for the signature. it should start with `[CLA]`

**Comment by rivo2302** [comment]
Hi @h4818  , 
I hope it's good now ;) !

**Comment by rivo2302** [comment]
@h4818

**Comment by h4818** [comment]
@robodoo r+

**Comment by dbkosky** [comment]
I had to re-open this as a PR targeting `v15` as it was never merged and we don't support v14 anymore
https://github.com/odoo/odoo/pull/155557

**Pull request closed without merging**
