### PR TITLE
[FIX] survey: show live session ending screen

### PR DESCRIPTION
**Pull request by ushyme**
### Steps to reproduce
- create a survey
- start a live session of your survey
- click the right arrow util you get to the last question
- click the arrow again to finish the live session

You should see that you're stuck on the last question.

This is only a front end problem; in the backend, the live session is being closed as it should be.

Note: this issue is specific to version 15.0

Partial backport of f1b1286393aeb690ac2d8f410d260f8615ebd718

opw-2925628

### CODE REVIEW

**Comment by ushyme** [comment]
@fw-bot ignore

**Review by nle-odoo — APPROVED** [review]
Hi,


This seems to be a partial backport of https://github.com/odoo/odoo/commit/f1b1286393aeb690ac2d8f410d260f8615ebd718 and succeeding https://github.com/odoo/odoo/commit/fdd6b007e174c19aeb45c1530aff987c393e36f70. If it is the case, it is good to reference it in the commit message (`partial backport of [commit hash]` or if not a backport `solved in 15.2 with [commit hash]`)

`Thank you!` is already in translation, but the correct reference needs to be added I think (I'm not sure if this is really necessary, but it's better in any case).

side note: if we are merging this, the nearer we are of 15.2, the best it is (this way future fix will be less of an hassle across versions)

fw-bot ignore

**Comment by ushyme** [comment]
I made the changes.
Thanks for the feedback!

**Comment by ushyme** [comment]
@tde-banana-odoo

**Comment by ushyme** [comment]
@tde-banana-odoo 
> Hello @tde-banana-odoo, hope you're doing well. When you have the time, could you take a look at this?

**Comment by ushyme** [comment]
@tde-banana-odoo

**Comment by ushyme** [comment]
@tde-banana-odoo

**Pull request closed without merging**
