### PR TITLE
[IMP] l10n_do upgrade

### PR DESCRIPTION
**Pull request by eneldoserrata**
Upgrade Dominican Republic localization module:

1- Simple chart of account
2 - Remove tax no need anymore
3 - Add missing Journals

### CODE REVIEW

**Comment by eneldoserrata** [comment]
@mart-e :)

**Comment by mart-e** [comment]
Hi,

Thanks for the PR. Technically it looks good except for the creation of `account.journal`. This is not something that you should do in a localisation module. There is not the template mechanism as there is for the accounts and taxes (will not work in multicompany) and we have some dashboards based on standard reports so I wouldn't recommend it.

**Comment by eneldoserrata** [comment]
@mart-e thanks for your help and recommendation I already made the change

**Comment by mart-e** [comment]
@eneldoserrata Thanks for the upgrade. Are the changes to reflect legal changes or improvement ? I would prefer to avoid removing taxes in stable if not mandatory.

**Pull request closed without merging**
