### PR TITLE
[FIX] l10n_fr_fec: test was still using French instead of English and…

### PR DESCRIPTION
**Pull request by jco-odoo**
… made l10n fail

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@fw-bot ignore

**Comment by jco-odoo** [comment]
I checked that the test pass locally. I will start an l10n build as well.

**Comment by william-andre** [comment]
Why only for 16.1?
Is it deterministic?

**Comment by jco-odoo** [comment]
> Why only for 16.1? Is it deterministic?

Because as now added in the commit msg, in 16.2 it has been fixed already.

**Comment by jco-odoo** [comment]
@william-andre It is weird that in https://runbot.odoo.com/runbot/build/41449277 it does not fail...  (do we need to set the lang in the test manually???)

**Comment by jco-odoo** [comment]
but it does fail in https://runbot.odoo.com/runbot/build/41449413

**Comment by william-andre** [comment]
Fw port disabled, and version deprecated

**Pull request closed without merging**
