### PR TITLE
[FIX] account_edi_ubl: payment_reference not available in efff format

### PR DESCRIPTION
**Pull request by simongoffin**
Inspired from http://www.datypic.com/sc/ubl21/e-cac_PaymentMeans.html

opw:2468492

### CODE REVIEW

**Comment by william-andre** [comment]
I feel like you are supposed to declare a payment with `<cbc:ID t-esc="invoice.payment_reference"/>` then.
Also, it seems to be a one2many field cbc:PaymentID [0..*]`, didn't you want another field?

**Comment by simongoffin** [comment]
@william-andre In http://www.datypic.com/sc/ubl21/e-cac_PaymentMeans.html

We also have

cbc:InstructionNote [0..*]    Free-form text conveying information that is not contained explicitly in other structures. 

where [0..*] is free form text

In the sample we have ```<cbc:PaymentID>Payref1</cbc:PaymentID>```

**Review by bfr-o — APPROVED** [review]

**Comment by simongoffin** [comment]
robodoo r+

**Comment by bfr-o** [comment]
@robodoo r-

**Comment by william-andre** [comment]
@robodoo r-

**Comment by bfr-o** [comment]
@simongoffin Sorry, I was a bit too quick. If you want to add the "communication structurée" it should go in the field `InstructionID` and not `PaymentID`. See http://www.e-fff.be/files/efff_UBL_Belgique_V110_Final.xls

Any reason why you put it in PaymentID ? Let's double-check before merging.

**Comment by simongoffin** [comment]
@bfr-o Ok no problem My only reference was http://www.datypic.com/sc/ubl21/e-cac_PaymentMeans.html where it seems to be the most adapted field. But I let you decide

**Review by bfr-o — APPROVED** [review]

**Comment by william-andre** [comment]
In my understanding, `PaymentID` would be something like our `account.payment` (or rather its `name` field), while `InstructionID` is the payment reference and `InstructionNote` is the free text (often used for terms and conditions in Odoo)

Just a reminder to please not self r+; especially when there are still comments pending. (its not like it was urgent in any way so there is absolutely zero reason to do it)

@robodoo r+

**Comment by d-fence** [comment]
robodoo retry

**Comment by simongoffin** [comment]
@william-andre Which comment was still pending? I got an approval after an answer to your question from the reviewer.

**Comment by william-andre** [comment]
@simongoffin Ok, I'm just going to put all you PRs in red in the future before even starting the review.

Even then. DON'T SELF R+. Period.
How hard is it to understand? If he didn't r+ himself, maybe he wanted to still let me review?

**Pull request closed without merging**
