### PR TITLE
[REF] website: customizable batch/limit on _cron_unlink_old_visitors

### PR DESCRIPTION
**Pull request by antonag32**
In b69917e[1] the cron implementation was changed to unlink old visitors in
batches of 1000 records. This was meant to deal with memory/timeout
errors when dealing with large amounts of records.

However it still searches for records with no limit, which in high
record count scenarios and based on instance resources may still
generate memory/timeout errors.

Technically it could be considered "fine" for the cron to timeout since
every batch is committed, so previously unlinked records are not rolled
back and the cron should eventually delete them all.

However there are some edge cases where memory/time out errors would not
be fine, like the cron failing during the first batch, which means no
unlink operations would be committed to the database.

Errors that are "fine" also generate noise and leave administrators
wondering which errors they should ignore and which they should not. It
also alarms non-technical customers since after all, they are seeing
a reported error.

Therefore the search limit and batch size have been added as arguments
to the cron. This is completely opt-in since they have the previous
values as their defaults. This makes it easy to customize and tune the
performance of the job accordingly if required.

[1] https://github.com/odoo/odoo/commit/b69917ec0e508f8354d831525c5c48ee79b5967a

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fernandahf** [comment]
cc @moylop260

**Comment by moylop260** [comment]
@rdeodoo  @lse-odoo 

It is a memory error fix related to https://github.com/odoo/odoo/pull/119467

**Review by rdeodoo — CHANGES_REQUESTED** [review]
If I got this right, before [1], it would also timeout and fail, but without having done anything.
After commit [1], it still failed/timed out, but all the passed loop occurrences would not be rollbacked since they got committed. Over time, it would eventually finish the job despite the many timeouts.

Your PR would prevent the timeout, but it would just make the feature broken, eg one having million of inactive user to remove would need the CRON to be executed for thousand of years before cleaning those inactive visitors.
This is not something we want.

First, what's the real issue with the cron timeouting, if everything done before timeouting is actually committed and reduced the remaining job?

Second, if that's really an issue, I'd rather add the context key to limit the records in an opt-in way, not the way you did it (opt-out).

[1]: https://github.com/odoo/odoo/commit/b69917ec0e508f8354d831525c5c48ee79b5967a

**Comment by antonag32** [comment]
Thanks for the review. I have made the PR much more less intrusive and opt-in as you requested. 

I see some issues with the cron timing out:

1. If it times out during the first batch, I don't think any records would get deleted.
2. It is an error after all, I don't think they are meant to be ignored. 
     - It creates noise, which timeout/memory errors should we ignore and which not?
     - Alarms customers, after all, they see an error on their screen/logs 

I think this PR could help us deal with these issues by making it easy to tune the cron accordingly, preventing errors like these.

**Comment by rdeodoo** [comment]
Thanks a lot! It's a been busy at the moment but I'll have a look in the incoming days to be sure we don't miss anything with this diff :+1:

**Comment by lse-odoo** [comment]
@antonag32 to check with RDE in term of stability, but I would personally prefer to add the limit and batch_size by arguments of the function to be more flexible. In this case we can modify/adjust the values from the scheduled action directly which would be more convenient

**Comment by antonag32** [comment]
> @antonag32 to check with RDE in term of stability, but I would personally prefer to add the limit and batch_size by arguments of the function to be more flexible. In this case we can modify/adjust the values from the scheduled action directly which would be more convenient

True, I was using `with_context` but does seem better to just use the arguments. I have changed that.

**Review by lse-odoo — APPROVED** [review]

**Review by rdeodoo — CHANGES_REQUESTED** [review]
Thanks for the quick changes.
Quick one before r+: as we changed the implementation since the first version (https://github.com/odoo/odoo/commit/cd0a3639fe91c37f8f4dd0e64558c890bcde871c)

The commit message is not correct anymore:
> Logic has therefore been changed to delete a single batch at a time per
cron execution. This should, in theory, reduce memory usage, however the
frequency of execution may have to increase in certain scenarios.

Could you also just mention https://github.com/odoo/odoo/commit/b69917ec0e508f8354d831525c5c48ee79b5967a in your commit message while you do that change? It will save time when blaming those lines later.

Bonus (ignore if you want, I don't mind):
- Summarize and add in commit message what I said [here](https://github.com/odoo/odoo/pull/150476#pullrequestreview-1860008657):
  > If I got this right, before [1](https://github.com/odoo/odoo/commit/b69917ec0e508f8354d831525c5c48ee79b5967a), it would also timeout and fail, but without having done anything.
After commit [1](https://github.com/odoo/odoo/commit/b69917ec0e508f8354d831525c5c48ee79b5967a), it still failed/timed out, but all the passed loop occurrences would not be rollbacked since they got committed. Over time, it would eventually finish the job despite the many timeouts.
- Summarize and add in commit message what you said [here](https://github.com/odoo/odoo/pull/150476#issuecomment-1930030951):
  > If it times out during the first batch, I don't think any records would get deleted.
It is an error after all, I don't think they are meant to be ignored.
It creates noise, which timeout/memory errors should we ignore and which not?
Alarms customers, after all, they see an error on their screen/logs
I think this PR could help us deal with these issues by making it easy to tune the cron accordingly, preventing errors like these.

**Comment by antonag32** [comment]
Thanks, I changed the title as well since I guess it is no longer a fix and more of a minor refactoring? I also updated the description of the commit as per your suggestions.

**Comment by antonag32** [comment]
For the record, this PR is linked with the ticket 3701805.

**Review by rdeodoo — APPROVED** [review]
Ty for PR & quick changes

@robodoo r+ rebase-ff

**Pull request closed without merging**
