### PR TITLE
[IMP] account: soften the constraint on duplicate vendor bill reference

### PR DESCRIPTION
**Pull request by william-andre**
Task 2002068
Sometimes, your vendor uses a numbering that loops over time (each year it restarts at 0 for example) and in this case you may receive two different bills that legitimely have the same reference. We want a non blocking warning.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gdgellatly** [comment]
I'm not sure this has been fully considered. In enterprise Odoo is promoting automatic vendor bill processing with OCR.  OK it doesn't work very well, but third party solutions do. 

Changing this constraint and moving it to UI removes an important check from unattended vendor bills.

**Comment by qdp-odoo** [comment]
@gdgellatly you have a point.

@avw-odoo maybe we should move that warning at the posting of the bill. Wadaya say?

**Comment by qdp-odoo** [comment]
and what does @antonylesuisse say about it? You were the one that initiated this task....

**Comment by william-andre** [comment]
Handled in 12.4 because it also fixes the way constraints work https://github.com/odoo/odoo/pull/34882

**Pull request closed without merging**
