### PR TITLE
[IMP][15.0] odoo/tools: make convert_xml_import method useful

### PR DESCRIPTION
**Pull request by royle-vietnam**
It is not common, but we sometimes need to call convert_xml_import method with custom rng file. The goal is to have a mechanism to call convert_xml_import method with custom rng file.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by royleviindoo** [comment]
@bso-odoo sorry for bothering you, can you help me review this pr, thank you

**Comment by bso-odoo** [comment]
LGTM, but I am not sure we are allowed to make this kind of signature change in a stable version. (Even though to me it appears to be compatible.)
I will ask to someone from the framework team to have a look.

**Comment by bso-odoo** [comment]
Here is a translation of the feedback I got:
- this is a non-essential API change in 15, so: no.
- the use-case is not explained: `convert_xml_import` is called by `convert_file` which is not modified.
- if there is a need to validate a file with a custom rng, the whole code is visible, no need to use `convert_xml_import` for that.

My understanding of that last point is: you can duplicate that method's implementation in your customization.
Or you can elaborate on your use-case so that what you want to achieve becomes more clear.

**Comment by royleviindoo** [comment]
Thank you for your feedback. I close this pr

**Pull request closed without merging**
