### PR TITLE
[FIX] web_editor: prevent removal of heading element

### PR DESCRIPTION
**Pull request by Zynton**
On a products category page, there is an element ready to host a heading but it's not explicitly marked as unremovable so when the user tries to remove any snippet inside it, the heading host is removed as well. This fixes it by using the `isUnremovable` utility function instead of simply checking for the `oe_unremovable` class.

Steps to reproduce the issue this commit fixes:
1. Go into the website module
2. Click "Shop"
3. Click "Furnitures"
4. Click "Edit"
5. Drop a title block in "Drag building blocks here to customize the header for "Furnitures" category."
6. Click the trash bin on your snippet to remove it.

It doesn't get removed. Well now it does.

task-3383348

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by AntoineVDV — APPROVED** [review]

**Comment by dmo-odoo** [comment]
@AntoineVDV Just making sure. This is an xml change in stable, so people who do not upgrade their views will continue to have the bug. Is this ok for you or do you have some kind of mechanism that we can use to patch those views or so ? I know they have mechanisms to do that for snippets in website for example.

**Comment by AntoineVDV** [comment]
> @AntoineVDV Just making sure. This is an xml change in stable, so people who do not upgrade their views will continue to have the bug. Is this ok for you or do you have some kind of mechanism that you'd like us to use to patch those views in js or so ? I know they have mechanisms to do that for snippets in website for example.

I'm not aware of such a mechanism in website. @qsm-odoo what is that mechanism exactly? Would it be helpful here?

In other applications, we simply fix the template and ask customers who complain about the bug to update their module. Most of the time, it's okay if it benefits only new customers or those who upgrade to 16.0, because no 16.0 customer notices the issue.

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
@AntoineVDV @dmo-odoo When it's about adding (not removing) a class on a random element of a template, I would just do that if the bug is not critical indeed. If there is related JS/snippet etc, it's worth the extra effort of making an existing-customer-friendly fix IMO.

In this case however, this should not be fixed that way. It never make sense to remove a t-field element (at least when not in a t-ignore environment)... we should not start marking all t-field elements with the oe_unremovable class one by one :grimacing: This should be automatic: te element has branding, it is the potential root of an editable area: it cannot be removed.

**Comment by Zinston** [comment]
@qsm-odoo is right, it should be automatically unremovable, and it actually is if we actually use the `isUnremovable` instead of just checking for that class. My bad, I corrected it.
cc @dmo-odoo @AntoineVDV

**Comment by dmo-odoo** [comment]
Good catch ! However, I feel like you might want to replace all the `oe_unremovable` class tests from https://github.com/odoo/odoo/pull/77724/commits/65b67d66de72fab390b8887c12532b840d47c95f by calls to `isUnremovable`, then.

**Comment by Zinston** [comment]
> Good catch ! However, I feel like you might want to replace all the `oe_unremovable` class tests from [65b67d6](https://github.com/odoo/odoo/commit/65b67d66de72fab390b8887c12532b840d47c95f) by calls to `isUnremovable`, then.

Done :-)

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
