### PR TITLE
[MERGE] web: Various graph view improvements

### PR DESCRIPTION
**Pull request by Polymorphe57**
This PR aims to bring several improvements to the graph view.

The main points are:
- custom tooltips in line mode to avoid problems with the Chart.js generic tooltips (those cannot
  go outside of the canvas boundary and information is lost).
- tooltips when legend items hovered in case their texts were cut for reason of space.

See task https://www.odoo.com/web#id=1963306&action=333&active_id=133&model=project.task&view_type=form&menu_id=4720

### CODE REVIEW

**Comment by Polymorphe57** [comment]
@VincentSchippefilt Salut Vincent, pourrais-tu merger cette branche si tout te semble correct? Merci

**Comment by VincentSchippefilt** [comment]
robodoo rebase-merge r+

**Comment by VincentSchippefilt** [comment]
needs a rebase when master (and enterprise) will be green

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Pull request closed without merging**
