### PR TITLE
[FIX] sale_timesheet : Fixed Price invoice accounted for twice in pro…

### PR DESCRIPTION
**Pull request by fdamhaut**
…fitability

Description of the issue/feature this PR addresses:

When using analytical account and invoicing a fixed price sales order item, which is linked to a project task, where timesheet has been recorded, the invoice gets double counted into the project revenues - both as Invoiced and as Other revenues on the project overview profitability.

Current behavior before PR:

The invoice gets double counted into the project revenues - both as Invoiced and as Other revenues on the project overview profitability.

Desired behavior after PR is merged:

The invoice gets counted only in the project revenues as Other revenues on the project overview profitability.

NB : This fix is non-optimal as it would be more interesting to add the revenue to invoiced/to_invoice but the cost/value of having to refactor a bigger part of the query is not worth it for such detail.

opw-2631163

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fdamhaut** [comment]
:wave: @IT-Ideas could you please take a look at this ?

**Comment by IT-Ideas** [comment]
Hello @fdamhaut 
May I ask you to add a test?
@tlibioulle will have a look into it once you pushed your test.

Thanks 🙂

**Comment by fdamhaut** [comment]
Hey @tlibioulle :wave: 

So after implementing the tests, I found out that the bug only happened when the service tracking was no (meaning that they track it but add the project and task and aa manually so the value of service_tracking stay to 'no'). Unfortunatly, i couldn't find a way to change it as it's link to a product template and not a SOL so the fix is not pretty but should work for this specific usecase and not alter others

If you think of any use case i didnt foresee dont hesitate to ping me on discord (flda).

PS : I also added some test as i was asked and slightly alter present one (in overview) as they weren't in accordance with the backend logic (round before addition)

**Comment by fdamhaut** [comment]
Ok @tlibioulle on close cette PR et je redirige le ticket vers ta PR ?

**Comment by tlibioulle** [comment]
@fdamhaut FYI : Your commit is now on our branch and it seems your tests succeed with our fixes only.

So I reverted the change you made in the query and kept your tests :)

Thanks a lot for your time on this query which is a nightmare to maintain/debug and thanks for the tests !

**Comment by tlibioulle** [comment]
@fdamhaut FYI : #78230 has been merged friday 15th.

Have a nice week ! :)

**Pull request closed without merging**
