### PR TITLE
[IMP] *: use get_installed/_lang_get methods

### PR DESCRIPTION
**Pull request by mart-e**
It is ormcached and correctly check the context

~~A lot of code could also be simplified by using `_lang_get` but there is this [weird fallback](https://github.com/odoo/odoo/blob/857c4851754dcddf9e6dc7b39585914beaf89c88/odoo/addons/base/models/res_lang.py#L183) on en_US/first lang that we should probably remove anyway.~~
_Update: Done_

### CODE REVIEW

**Comment by mart-e** [comment]
cc @jva-odoo please test if fixes your issue at #35490

**Comment by jva-odoo** [comment]
@mart-e I can't test because it gives traceback in runbot as well as in local when activating the developer mode
runbot traceback https://pastebin.com/WfYhFyaM
local traceback https://pastebin.com/A7t5Jua0

**Comment by mart-e** [comment]
@jva-odoo the PR is still in dev but I was talking about the l10n_multilang part of odoo-dev/odoo@bcea744054903f31aba5e1c77e1129a2d541b1e1

**Comment by jva-odoo** [comment]
@mart-e Yes, As I see the code it's fixed that issue.

**Comment by jva-odoo** [comment]
@mart-e I also cherry-pick this odoo-dev/odoo@bcea744 commit in local and it's work and solved this https://github.com/odoo/odoo/pull/35490 issue.

**Comment by mart-e** [comment]
Shall we make `_lang_get` public?

**Comment by xmo-odoo** [comment]
> Shall we make `_lang_get` public?

As in "callable over RPC"? Doesn't seem like much of an issue, though I'm not sure there's much gain over calling the existing `get_installed` and checking if the relevant code is present there, it's not like that'll be hundreds of langs.

**Comment by mart-e** [comment]
You may get tricky context issues (cf discussion at #35490) when using search while it is explicit with `get_installed`
Retrieving a method from the code is something that is done very often in odoo so worth a common method. Making it public was more to make it "official" because, indeed, not very useful for xmlrpc

**Comment by mart-e** [comment]
In the enterprise version at odoo/enterprise#5049 you have another example of people trying to use search incorrectly while `get_installed` did the trick.

**Comment by mart-e** [comment]
@robodoo r+ rebase-ff

**Comment by KangOl** [comment]
@robodoo r+

**Comment by mart-e** [comment]
@KangOl I knew you were going to say that :wink:

**Pull request closed without merging**
