### PR TITLE
Correctly display DIV-styled HTML in plaintext

### PR DESCRIPTION
**Pull request by michaelhwalther**
Some Mail-Clients (Apple iMail) use only DIV tags to style their HTML bodies. The html2plaintext method removes any such div tags, creating a mostly unreadable blob of text without any line breaks or paragraphs. Browsers usually insert line-breaks before and after DIV blocks, although this can (and is) often overridden with CSS styling.
This patch treats DIV tags with this default behavior, essentially like paragraph &lt;P> tags.

### CODE REVIEW

**Comment by michaelhwalther** [comment]
CLA is signed in #9013

**Comment by michaelhwalther** [comment]
Rebased to include CLA signature

**Comment by michaelhwalther** [comment]
Rebased to include CLA signature

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
