### PR TITLE
[IMP] account: reconciliation design, layout adjustments

### PR DESCRIPTION
**Pull request by stefanorigano**
Description of the issue/feature this PR addresses:
Some minor overflow and margins issues in the reconciliation screen 

Desired behavior after PR is merged:
Fix the layout

TASK: [1838293](https://www.odoo.com/web#id=1838293&action=333&active_id=587&model=project.task&view_type=form&menu_id=4720)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
@qdp-odoo , reconciliation design, layout adjustments
Thanks :)

**Comment by qdp-odoo** [comment]
landed in master, at revision https://github.com/odoo/odoo/commit/99cdd48dc702be2680674410d51b310fda99df1f

thanks Stefano

**Comment by stefanorigano** [comment]
Great, thanks Quentin! 🎉

**Comment by qdp-odoo** [comment]
oops, actually I have layout issues when buttons are on more than one line, as they would be unaligned and lines would be touching each others. 

Can you check?
reconciliattion_layout_issues

**Comment by stefanorigano** [comment]
Ooops... 😬  
sure, I'm having a look!

**Comment by stefanorigano** [comment]
Ok, seems like the issue is there since V11 (at least), but I totally miss it in my little review...
I'll push a commit on top 👍 
screen shot 2018-06-25 at 16 37 08

**Comment by qdp-odoo** [comment]
thanks, you can directly push to master :-)

**Comment by stefanorigano** [comment]
@qdp-odoo , I pushed a fix here > https://github.com/odoo-dev/odoo/commit/606e455e2437be01d09762465ad517f25d887421

**Comment by stefanorigano** [comment]
@qdp-odoo , I'm not allowed to push in master 🍼 😜

**Comment by qdp-odoo** [comment]
:-) your patch has been merged at https://github.com/odoo/odoo/commit/ee9c1f52c316c83775969a3c9038e7e9f560f7e7

thanks again

**Pull request closed without merging**
