### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by pro-odoo**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/9fe94773d [REL] 17.4.0-alpha.11 Task: 0
https://github.com/odoo/o-spreadsheet/commit/f64a70e80 [FIX] XLSX: Update the list of 'future' functions of Excel Task: 4017114
https://github.com/odoo/o-spreadsheet/commit/a68d9f2d6 [REL] 17.4.0-alpha.10 Task: 0
https://github.com/odoo/o-spreadsheet/commit/f24c95e1b [ADD] pivots: Pivots re-insertion Task: 3947821
https://github.com/odoo/o-spreadsheet/commit/863bae698 [IMP] MenuItemRegistry: Make entries overridable Task: 3947821
https://github.com/odoo/o-spreadsheet/commit/936fe942b [REM] pivots: remove unused time adapter Task: 4019715
https://github.com/odoo/o-spreadsheet/commit/9a0e1ec74 [REM] pivot: remove granularity year_number Task: 3899604
https://github.com/odoo/o-spreadsheet/commit/3aa7ab7ee [FIX] BottomBarSheet: Prevent drag of sheet while editing its name Task: 4010842
https://github.com/odoo/o-spreadsheet/commit/303cfcd05 [FIX] FindAndReplace: styling for the search scope dropdown Task: 3996599
https://github.com/odoo/o-spreadsheet/commit/38b304f9d [IMP] FindAndReplace: default search scope to activeSheet Task: 3996599
https://github.com/odoo/o-spreadsheet/commit/67a0312bf [PERF] coordinates: imp 'toCartesian' perf Task: 4016980
https://github.com/odoo/o-spreadsheet/commit/be12917b0 [PERF] coordinates: imp 'lettersToNUmber' perf Task: 4016980
https://github.com/odoo/o-spreadsheet/commit/691a6605a [ADD] formulas: introduce OFFSET function Task: 2837743
https://github.com/odoo/o-spreadsheet/commit/6ff1708cf [REF] typo: adjust INDEX to INDIRECT Task: 0
https://github.com/odoo/o-spreadsheet/commit/52f552548 [REF] typo: adjust cash to cache Task: 0
https://github.com/odoo/o-spreadsheet/commit/ac12e0f18 [REF] renderer: allow to extend cell icons Task: 4011486
https://github.com/odoo/o-spreadsheet/commit/a66fe3283 [IMP] pivot: improve pivot duplication Task: 3848336
https://github.com/odoo/o-spreadsheet/commit/4ec8f9553 [IMP] charts: add Area chart Task: 3981124

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by pro-odoo** [comment]
robodoo fw=no

**Comment by pro-odoo** [comment]
robodoo rebase-merge

**Comment by rrahir** [comment]
@robodoo r+

**Comment by pro-odoo** [comment]
robodoo r+

**Pull request closed without merging**
