### PR TITLE
[FIX] l10n_cl: unable to issue credit note (vendor bill)

### PR DESCRIPTION
**Pull request by agr-odoo**
Have a CL company setup
Issue a vendor bill
Then generate the credit note via 'Add Credit Note' wizard
Add a reason and confirm
Error will raise “You can not use a invoice document type with a refund
invoice”

As
https://github.com/odoo/odoo/commit/c9ff9d28ab75c02093ca54d9fbd1d2e203c5ee2e
for the invoice case
we need to add specific logic to handle credit notes in l10n_cl

opw-2801576

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@jco-odoo 
My bad, I should have checked also the Vendor Bill case

**Comment by jco-odoo** [comment]
Same case as before, but for vendor bill refunds.

**Comment by fvz-odoo** [comment]
Hi @jco-odoo 

I just tested this and LGTM. Tried all cases for vendor bills (Partial Refund, Full Refund and Full Refund and New Draft Invoice), all worked ok and didn't get an error like “You can not use a invoice document type with a refund invoice”.

Let me know if I should test something else.

Cheers!

@vbe-odoo @ren-odoo @agr-odoo

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
