### PR TITLE
FIX: Account test consider company while selecting accounts from database

### PR DESCRIPTION
**Pull request by t-sq1**
Description of the issue/feature this PR addresses: https://github.com/odoo/odoo/issues/52352

Current behavior before PR: with multiple accounting charts installed/loaded, following lines are selecting the last input only without considering the accounting chart of the company:

https://github.com/odoo/odoo/blob/0e8f86795db74fe21daa8776243415291371fdf6/addons/account/tests/test_payment.py#L29
https://github.com/odoo/odoo/blob/0e8f86795db74fe21daa8776243415291371fdf6/addons/account/tests/test_payment.py#L30
https://github.com/odoo/odoo/blob/0e8f86795db74fe21daa8776243415291371fdf6/addons/account/tests/test_payment.py#L31

This might lead to wrong accounts.

Desired behavior after PR is merged: The accounts are selected considering the current company so it is ensured that the correct ones are selected.

I am not quite sure if merging into odoo/odoo base:13.0 also leads to a change in the odoo.sh version. Can anyone tell me which base repository I have to choose for changing this test also in odoo.sh?

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by t-sq1** [comment]
@pedrobaeza could you possibly help me? Can you tell me why my cla is not accepted? With my old (closed) PR it was accepted without any problems.

**Comment by pedrobaeza** [comment]
Probably the email of the committer is not the same put in the CLA file. Check also commit messages, that are not with the guidelines.

**Comment by t-sq1** [comment]
@pedrobaeza thanks for your quick reply. Unfortunately I cannot find any problems.. The email is correct.

**Comment by t-sq1** [comment]
@pedrobaeza unfortunatley I'm not able to get it to work... Is there a possibility to get to know in detail what is going wrong?

**Comment by pedrobaeza** [comment]
Sorry, I only give a hand on issue tracker and occasionally on linked PRs, but I can't say about that. I would say that the problem is the same: you are putting different information in the file and the mail that is committing.

**Comment by t-sq1** [comment]
@pedrobaeza I switched my email to public and it works! Thanks!!

**Comment by lathama** [comment]
@t-sq1 knowing that 13 is no longer updated, is this PR still needed?

**Comment by t-sq1** [comment]
@lathama no, I will close it.

**Pull request closed without merging**
