### PR TITLE
[FIX] Improve Inventory Report performance when there are many products

### PR DESCRIPTION
**Pull request by TimLai125**
**Description of the issue/feature this PR addresses:**
1. When `Stockable` filter is applied to the `stock.quant` list, Odoo will get all the ids from `product.product` that the type is `product`.
2. The obtained ids will be used and formed the following query (The middle part is omitted).
3. For environment which the spec is low, a heavy loading will be result after the user tries to open the `Inventory Report`
```
** The query is captured by enabling log_statement of PostgreSQL to all
SELECT count(1) 
FROM "stock_location" as "stock_quant__location_id","stock_quant"
WHERE ("stock_quant"."location_id"="stock_quant__location_id"."id") 
AND (("stock_quant"."product_id" in (3534,3539,5295,5296,5297,1545,5294,1554,1546,3535,...,5144,3))  AND  ("stock_quant__location_id"."usage" = 'internal'))
```

**Current behavior before PR:**
When there are many products (`product.product`) in the server, Odoo will issue a huge query to the database. On my customer's situation, 20k products will issue a ~73,000 characters query to the database.

For instance that with high spec. there should not be an issue since the query itself does not involve any complex database operations, therefore the `Inventory Report` will open in like ~5s.
For instance that does not have high spec, this simple operation takes 30 - 60s. 

**Desired behavior after PR is merged:**
The length of query is reduced and the performance is improved, i.e.
```
SELECT count(1) 
FROM "stock_location" as "stock_quant__location_id","product_template" as "stock_quant__product_id__product_tmpl_id","product_product" as "stock_quant__product_id","stock_quant" 
WHERE ("stock_quant__product_id"."product_tmpl_id"="stock_quant__product_id__product_tmpl_id"."id" AND "stock_quant"."location_id"="stock_quant__location_id"."id" 
AND "stock_quant"."product_id"="stock_quant__product_id"."id") 
AND (("stock_quant__location_id"."usage" = 'internal')  
AND  ("stock_quant__product_id__product_tmpl_id"."type" = 'product'))
```

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This kind of change can't be done on a stable branch, as it breaks stability policy. You should target master if you still want to have this, or find an alternative way of getting the same result (maybe `auto_join=True`?)

**Comment by TimLai125** [comment]
@pedrobaeza Thank you for the comment, I will check the `auto_join=True` option.

**Comment by gdgellatly** [comment]
This is one of those times where inversion of the domain usually makes sense.

Just overide the view with `<filter name="stockable" string="Stockable" domain="[('product_id.type', 'not in', ('consu', 'service)]"/>` if nearly all your products are stockable.

**Comment by TimLai125** [comment]
@gdgellatly, Thank you for the workaround! It works in some cases but not all, when all types of products have large quantities and the issue will appear again.

**Comment by TimLai125** [comment]
@pedrobaeza I have checked the `auto_join=True` and it works fine, please check the PR and let me know if there is any other concern. =]

**Comment by pedrobaeza** [comment]
OK, now it's in Odoo team hands, as they have the final word in this.

**Comment by C3POdoo** [comment]
Dear @TimLai125,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
