### PR TITLE
[IMP] test_lint: remove escheck test

### PR DESCRIPTION
**Pull request by SimonGenin**
As of 16.1, the ecmascript version accepted in odoo is 2022. This basically makes escheck almost irrelevant.
Escheck being only able to check up to the version 2021, it can be removed safely.

### CODE REVIEW

**Comment by seb-odoo** [comment]
Is it really safely though? At some point in the future we might start using code from next ES versions that we might not want to support?

But if the tooling doesn't even support 2022 I guess we don't really have the choice for now.

**Comment by seb-odoo** [comment]
Shouldn't the tooling in web be adapted accordingly at the same time?

**Comment by SimonGenin** [comment]
@seb-odoo If escheck were to be updated, then we could keep it that's correct. 
So I'm not against keeping it, but currently disabling it.
And yes, we should do that rather quickly to be in line with the tooling, so I guess it should be done this week whatever the solution we pick.

**Comment by jpp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
