### PR TITLE
[IMP] stock: remove automatic push rules

### PR DESCRIPTION
**Pull request by jco-odoo**
Automatic push rules did not work with pickings
and were only still there for finished products
cases for manufacturing orders.  As putaways
can be applied in manufacturing orders too now,
there is no reason to keep this option which only
leads to piles of confusion.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jco-odoo Managing Push rules is sometimes easier than putaway rules as putaway has limitation that you have to configure product category (or each product  see OCA putaway). That depends on business flows you have.

That's a point we already mentioned.

**Comment by jco-odoo** [comment]
But we might have already merged the putaway by product.

**Comment by rousseldenis** [comment]
Yes, of course (Sorry, I'm focused on v10 for now...)

**Comment by jco-odoo** [comment]
@amoyaux Did someone make a different commit for this or...?

**Comment by amoyaux** [comment]
@sle-odoo @jco-odoo This PR seems correct for me. However what was the purpose to implement automatic push rule? (mrp I guess) Should we implement something instead or everything should be cover by putaway?

**Comment by jco-odoo** [comment]
I think mrp will already apply putaway as move lines are generated from
moves now and not from totals on the picking (as with the pack ops)

**Comment by rousseldenis** [comment]
@jco-odoo My remark was just a general remark about stock flows and should not be taken into account to merge this. So, keep in mind people could have different business flows and limiting push rules to putaways is a little bit tight.

**Comment by C3POdoo** [comment]
Dear @jco-odoo,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
