### PR TITLE
Update psycopg2 version, fix issue #19511. Added CLA.

### PR DESCRIPTION
**Pull request by grzekru**
Description of the issue/feature this PR addresses:
https://github.com/odoo/odoo/issues/19511

Current behavior before PR:
Odoo not working on Arch Linux with current python packages from requirements.txt

Desired behavior after PR is merged:
Odoo working on Arch Linux after installing packages from requirements.txt

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@sle-odoo package updates - this one is for you.

**Comment by mart-e** [comment]
Thanks, merged at e419f395a123040896dbe942ad7f0ce10983d197

**Comment by lmignon** [comment]
@mart-e Sorry but this fix seems to be wrong (at least it doesn't work on ubuntu 17.10). The minimal version to work with glibc 2.66 is psycopg2==2.7.3.**1**

**Comment by mart-e** [comment]
You are right, I did not thought it was making a difference, but after testing, it still
Fixed at 144a5286163

**Comment by lmignon** [comment]
Thank you to you @mart-e !

**Pull request closed without merging**
