### PR TITLE
[WIP] dummy_invoice: Error to render compiling AST issue#18841

### PR DESCRIPTION
**Pull request by goliveirab**
Issue: Executing test, Error to render compiling AST when document in signed, retry.
https://github.com/odoo/odoo/issues/18841

The error:  Error to render compiling AST, is displayed when test is executed and an pdf with  tag, with a QR code is in the document.

Works when functional execution: https://drive.google.com/file/d/0B4jIZfjtBteKUXJxZ3JsM3RXLVE/view

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by goliveirab** [comment]
FYI @luistorresm

**Comment by mart-e** [comment]
Hello,

Is this still needed? I tested the module in both saas-14 and 11 and did not get any error.

**Comment by luistorresm** [comment]
Hello @mart-e 

This only fails when you run the test that print the report, and the report have the QR:

```
<img t-att-src="'/report/barcode/QR/%s' % quote_plus('?') + keep_query(                                            
  re=o.l10n_mx_edi_cfdi_supplier_rfc, rr=o.l10n_mx_edi_cfdi_customer_rfc,
  tt=o.l10n_mx_edi_cfdi_amount, id=o.l10n_mx_edi_cfdi_uuid)"/>
```

Do you run the test?

Regards

**Comment by mart-e** [comment]
Right, I was trying to print an invoice and saw it was generating correctly a QR code.
But indeed, the test is failing, not sure why.

**Comment by mart-e** [comment]
Right, I was trying to print an invoice and saw it was generating correctly a QR code.
But indeed, the test is failing, not sure why.

**Comment by luistorresm** [comment]
@mart-e 

The problem is that `keep_query` cannot be access in the test, here a [video](https://drive.google.com/file/d/0B4jIZfjtBteKZjM4cHFYZ0tVbGs/view), and more information in the [issue related](https://github.com/odoo/odoo/issues/18841).

Regard

**Comment by luistorresm** [comment]
Hello @mart-e 

Do you have news about this topic?

Regards

**Comment by luisg123v** [comment]
Hi @mart-e & @luistorresm 
I've developed a solution for tis issue at https://github.com/odoo/odoo/pull/22942. I applied here in this PR that solution to demonstrate it works as expected.

A detailed explanation of the reason for this failing only when used from unittests may be found at the linked PR. To summarize, the method `keep_query` tries to retrieve parameters from the HTTP request even when not available, as is the case in unittests.

**Comment by luistorresm** [comment]
This PR now is not necessary.

The FIX already was merged with https://github.com/odoo/odoo/commit/79f137f342109c2ef5ca3ebc491607a1ea5de549

**Pull request closed without merging**
