### PR TITLE
[FIX] sale, website_sale: move #buy_now disable

### PR DESCRIPTION
**Pull request by fja-odoo**
Some code was not correctly merged during forward port.

commit introducing the new method
51ef851

commit introducing the issue:
71a50a2

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo delegate=@seb-odoo I guess you will know better than me if this line of code should entirely disappear ;)

**Comment by seb-odoo** [comment]
As seen together, this should be moved into `_toggleDisable` of `website_sale`.

**Comment by seb-odoo** [comment]
I'll test tomorrow, but it should be OK now.

The best for the commit message would be to also include the commit where the buy_now feature was introduced.

**Comment by seb-odoo** [comment]
Ok I tested manually and I ran the corresponding tests locally and this looks good. @qsm-odoo Can you push this directly into master please? This is needed to fix runbot but robodoo won't work because of the other issues.

**Comment by qsm-odoo** [comment]
Would master be red because of this ?

**Comment by seb-odoo** [comment]
Yes in part, there are other errors but all the tests related to sale, ecom, ... are red because of this.

**Comment by qsm-odoo** [comment]
@JKE-be could you merge that in master if it is fine for you then ?

**Comment by JKE-be** [comment]
pushed merged manually in master

**Pull request closed without merging**
