### PR TITLE
Launchpad > Transifex

### PR DESCRIPTION
**Pull request by Yenthe666**
Had the link to the old translation platform.

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e this one is for you :smile: Multiple invalid terms.

**Comment by mart-e** [comment]
Hello,

I am not sure we should change those. The project Odoo is no longer on Launchpad but the localisations team can still use Launchpad to work and discuss on their locations.

**Comment by Yenthe666** [comment]
Hi Martin,

I see. I honestly think the new links should be there for Transifex too. Perhaps we could change it to showing both the urls? something like:
"please go to http://translations.launchpad.net/openerp-costa-rica or https://www.transifex.com/odoo/odoo-9/language/es_CR/"

**Comment by mart-e** [comment]
But Transifex is for the translations, here we are talking about chart of accounts, I don't get why you want to send people there.

**Comment by Yenthe666** [comment]
@mart-e because translations also matter for the modules? :smile: 
Its just an idea/request though if you don't think it has any plus points you can leave it out.

**Comment by mart-e** [comment]
Well sorry but I disagree, I do not want to get discussions about accounting in Transifex. Yes the translations are important but I don't think the chart of account is the place to advertise about translating the rest of Odoo.

The Costa-Rica team has moved to GitHub but no idea for the others. I have updated just this one at 19f9328d0b21b546c724e12efc4ddb3b9fdcb4ed and someone can create a PR to update the others if the localisation teams are recomposed somewhere else.

**Pull request closed without merging**
