### PR TITLE
[FIX] base: set res.country.state codes according to...

### PR DESCRIPTION
**Pull request by randall-vx**
... Costa Rica INEC (Instituto Nacional de Estadística y Censo governmental institution entrusted with the running of censuses and official surveys in the country) and Ministerio de Hacienda (government ministry of Costa Rica in charge of governing the fiscal policy on public resources, according to the principles of economy, efficiency and effectiveness).

##### Topic 3. Codificación detallada de la DTA, calificación de grado de urbanización y región de planificación.

* https://www.inec.cr/sites/default/files/documetos-biblioteca-virtual/meinstitucionalmcgfecr.pdf

### Ministerio de Hacienda reference:

* https://www.hacienda.go.cr/ATV/ComprobanteElectronico/docs/esquemas/2016/v4.1/Codificacion,canton,provincia,distritoybarrio.pdf

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by ruiznorlan — APPROVED** [review]
The adjustment helps to comply with the geographic classification of INEC and Ministerio de Hacienda.

**Comment by EstebanMonge** [comment]
Looks good

**Comment by TheCloneMaster** [comment]
Really helpful, to avoid doing that with another module

**Comment by randall-vx** [comment]
@luistorresm FYI

**Review by luistorresm — APPROVED** [review]
👍

**Comment by randall-vx** [comment]
@jco-odoo could you review please ?

**Comment by jco-odoo** [comment]
@randall-vx Just [master] should be removed from the commit msg, so it follows the general format.  No problem to change it as I don't think the previous codes had any legal value, but I wonder if they would not be just like the first number of the zip code, so we would not really need them.

**Comment by randall-vx** [comment]
@jco-odoo Within the location of Costa Rica, the location must be assigned in the electronic invoices according to the zip code, so it is necessary.

The zip code is formed as follows:

1: Province
02: Canton (not in Odoo now)
03: District (not in Odoo now)

Resulting in zip code 10203

With this change we avoid creating an unnecessary hook for the Costa Rican localization modules (for now they are external modules to Odoo)

cc: @luistorresm

**Comment by jco-odoo** [comment]
@randall-vx So no need to add the canton and the district as the zip says it all.

**Comment by jco-odoo** [comment]
@randall-vx just waiting for the adaptation of the commit msg

**Comment by randall-vx** [comment]
@jco-odoo sorry, I close this MR by mistake.

New PR #87034

**Comment by randall-vx** [comment]
@luistorresm done !

**Pull request closed without merging**
