### PR TITLE
Make update multi-record aware

### PR DESCRIPTION
**Pull request by yajo**
This way we can have a `write()` equivalent in draft and onchange environment status.

### CODE REVIEW

**Comment by Yajo** [comment]
The check is wrong, I have signed both individual and company CLAs

**Comment by Yajo** [comment]
I rebased today and still cannot get the red CLA to green, [but it's signed](https://github.com/odoo/odoo/blob/master/doc/cla/individual/Yajo.md).

BTW I forgot to explain that the motivation of this is because of the deprecation of `@api.one`. It's a shame, but if it is removed, then this alternative becomes very useful.

**Comment by xmo-odoo** [comment]
@Yajo the CLA issue is that you've created the commit via (I assume) the github interface leading to a github address being used according to [the raw patch](https://github.com/Yajo/odoo/commit/cd96e0cc85f6e841ae134c63e0141734890e7ef5.patch) but your CLA-registered address is a personal one. As a result the addresses don't match.

I don't recall how we're supposed to deal with that (ping @odony ?), though I think you could either update the CLA to add the github address or fixup the patch's author with `git commit --amend --reset-author` in the command-line.

**Comment by odony** [comment]
Indeed, to pass the CLA check you should amend the commit author (e.g after fixing your git `user.email` setting), then force-push the branch to update the PR.

**Comment by Yajo** [comment]
Thanks, finally!

**Comment by rco-odoo** [comment]
@Yajo cherry-picked as 528111db69544f9a1c54b7c76f63c76691659fe0.
Thanks for your contribution!

**Comment by dreispt** [comment]
Now we are really missing the documentation 😉 

It's not clear for me: 
For practical purposes, what is the difference between `write()` and `update()`, and when is it appropriate to use each?
Is `update()` helpful to avoid the infinite recursion from naive writes when extending the `write()` method of a Model?

**Pull request closed without merging**
