### PR TITLE
[FIX] [8.0] fetchmail should not set as 'Seen' messages which raised exception

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
:+1:. One-off errors are easily missed, and this way, a queue of errors remains visible in the logs until resolved.

**Comment by pedrobaeza** [comment]
See my comment in https://github.com/OCA/OCB/pull/291#discussion_r35786200

**Comment by eLBati** [comment]
On 29 July 2015 at 19:23, Pedro M. Baeza <notifications@github.com> wrote:

> See my comment in OCA#291 (comment)
> <https://github.com/OCA/OCB/pull/291#discussion_r35786200>
>
>
>
replied

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by eLBati** [comment]
Reporting @beledouxdenis answer (Denis, I hope publishing your answer is ok for you):
> Unfortunately, the current behavior is the behavior expected.

> When an email fails to be fetched, this is very likely that this same email will fail again at the next cron call.

> With that in mind, if you come up with a lot of failing/unread emails, they will be retried at each cron call, and at some point, there will that many emails that the CPU time limit could be reached, and no other emails could then be fetched.

> Even if we change our mind, this cannot be done in a stable release, such as Odoo 8.0, as this lead to a huge change of behavior, that cannot suddenly happen within a stable release

In my experience, when an email fails to be fetched, it is typically a temporary failure (like connection problems). This is why we install this patch on every production server.

We also use https://github.com/OCA/server-tools/tree/8.0/scheduler_error_mailer so, in case the email keeps failing, we get notified and we can go to the mailbox to manually set the message as read

**Comment by pedrobaeza** [comment]
Denis has exposed clearly the problem: repeated times the same email failure. So for me it's clear: enable a counter to dismiss in x repetitions. I know that this is not a solution for stable versions, but it can be for master.

**Comment by Yajo** [comment]
https://github.com/odoo/odoo/pull/5705#issuecomment-181917849 seems legit, but on connection error, the same connection would fail to mark as seen, so that should not be a real case.

**Comment by eLBati** [comment]
Actually, connection problems is a bad example. Because the message is downloaded outside the ```try```.

This change is significant when an exception is raised by ```mail_thread.message_process```.

Typical temporary error is ```could not serialize access due to concurrent update```, like

```
2016-03-07 13:05:33,902 11020 ERROR agilebg openerp.sql_db: bad query: UPDATE "mail_message" SET "message_id"='<1457355901.065392017364502.577158956187929-openerp-2778-project.task@vm4196.cloud.seeweb.it>',"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (214771)
Traceback (most recent call last):
  File "/srv/odoo-8-agilebg-prod/agilebg/parts/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
```

or

```
2016-03-18 15:12:29,457 28233 ERROR agilebg openerp.sql_db: bad query: UPDATE "project_task" SET "active"=true WHERE id = 2705
Traceback (most recent call last):
  File "/srv/odoo-8-agilebg-prod/agilebg/parts/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
```

**Comment by Yajo** [comment]
But that's an error when writing to database. How does that relate to your fix?

**Comment by eLBati** [comment]
@Yajo without my fix, when that error happens, the message is set as 'seen' in server mailbox, but not correctly processed by odoo: thus the message is lost.
With my fix, when that error happens, the message is not set as 'seen', and the next cron cycle will try to read it again. That is, the message is set as 'seen' only if odoo does not raise exceptions

**Comment by Yajo** [comment]
OK I understand now :+1:

**Comment by dreispt** [comment]
I have this fix installed, and found cases of a few inbound emails that were "ignored" by fetchmail.
It probably isn't related to this fix, because I can't even find any "Failed to process mail" message in the log.
I tried to manually mark the ignored email as unread and then forced fetchmail, and this time it was processed correctly!

I can't explain it and it's driving me nuts. Anyone has an idea of what might be going on? Thanks!
(note: the mail server is in the LAN)

**Comment by eLBati** [comment]
@dreispt maybe someone read them by  webmail or other client?

**Comment by dreispt** [comment]
@eLBati I don't bet on that one. Several people have shared access to that mailbox, but the "read" flag is per user, at least in this mail server (IBM Lotus Domino).

**Comment by tde-banana-odoo** [comment]
Hello,

Coming looooong after war but ... if your issue is related to some known use cases, isn't it possible to have them raised correctly in message_process and catched in the fetchmail ? If those "use cases" fail, seen flag is not added, otherwise we keep the seen flag to avoid having a growing list of failing emails.

**Comment by Yenthe666** [comment]
Plus, a rebase would need to be done as it is against 8.0 and that is end of life.

**Pull request closed without merging**
