### PR TITLE
[FIX] website_slides: add style to the side bar container

### PR DESCRIPTION
**Pull request by Jinjiu96**
Reproduction:
1. Install Website and eLearning
2. Add new language Dutch
3. Modify the course responsible’s name as “Gertjan Kleinbloesem” in
eLearning
4. Open the course page in the website app and switch to Dutch, the
responsible name is overflowed

Reason: The background container doesn’t adapt to the length of the text

Fix: Add text break to the responsible's name so it won't break the
style

opw-2862250

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Jinjiu96** [comment]
The first fix is just adding text break to the responsible's name, the second fix is to let the container adapt to the text length. In my opinion maybe only adding the text break is better? It gives a minimum change of the layout, the name is shown in a bit weird way though. I pushed the two possibilities to have a comparison in history, the current one is adapting the container.

Adding text break:



Adapt the container:

**Review by nle-odoo — COMMENTED** [review]
from my test with bigger word, with the fix the sidebar gets bigger but the rest stays the same, so there is not an overflow from text but from the whole sidebar:

2022-07-22-135504_719x507_scrot

so fix with word break seems better

**Comment by Jinjiu96** [comment]
> from my test with bigger word, with the fix the sidebar gets bigger but the rest stays the same, so there is not an overflow from text but from the whole sidebar:
> 
> 2022-07-22-135504_719x507_scrot
> 
> so fix with word break seems better

Yes indeed! I will put it back as `text-break` then. Was just trying to find another way instead of breaking the name :smile: Thanks for reviewing :D

**Review by nle-odoo — APPROVED** [review]
looks good to me

**Comment by Jinjiu96** [comment]
@pko-odoo Could you have a look at the fix, thanks! :pray:

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
