### PR TITLE
Master l10n fr add cash basis vat pka

### PR DESCRIPTION
**Pull request by pka-odoo**
Task :
https://www.odoo.com/web#id=42558&view_type=form&model=project.task&action=327&menu_id=4720
Pad:
https://pad.odoo.com/p/r.a950d3f15f4baaf54d4b0c43fe3a6e49

Description of the issue/feature this PR addresses:
Add some taxes in l10n_fr module

Current behavior before PR:
Add some taxes in l10n_fr module

Desired behavior after PR is merged:
Taxes are Added in l10n_fr module

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rgo-odoo** [comment]
LGTM

**Comment by kebeclibre** [comment]
@jco-odoo 
Seems to be a task ordered by a PO ....

**Comment by jco-odoo** [comment]
@kebeclibre Yes, I trust my PO, but as a general reflection: when other localizations have a lot of taxes, they put some inactive by default.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by kebeclibre** [comment]
robodoo r-
wrong target branch

**Comment by oco-odoo** [comment]
discussed with jco; old PR, needs to be closed (whe finally only did that from 12.3 on)

**Pull request closed without merging**
