### PR TITLE
[FIX][14.0] purchase: dashboard should respect user language

### PR DESCRIPTION
**Pull request by hoangtiendung070797**
Issues
---------
Purchase Dashboard gives wong value for PO in RFQ and RFQ sent when user's language is not English

Current behavior before PR:
-------------------------------------
1. Create some RFQ and RFQ Sent to see its statistic in dashboard
2. Swith user language to another one that is other than English
3. Statistic in the dashboard is wrong now

Solution
-----------
Passing translated RFQ and RFQ Sent into the dashboard query in stead of passing pure text without translation.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hoangtiendung070797** [comment]
@amoyaux plz can you review it !!! Thank

**Comment by amoyaux** [comment]
Okay for me can you just complete the commit message with the PR message and a space between [FIX] and purchase

**Comment by hoangtiendung070797** [comment]
> Okay for me can you just complete the commit message with the PR message and a space between [FIX] and purchase

@amoyaux I apologize for the delay in responding. I have adjusted the commit message. Please review for me

**Comment by amoyaux** [comment]
robodoo r+
Thanks for the fix

**Comment by hoangtiendung070797** [comment]
> robodoo r+ Thanks for the fix

@amoyaux Thank you!

**Comment by hoangtiendung070797** [comment]
@amoyaux Ping. Please, don't forget me !!!

**Comment by ticodoo** [comment]
@robodoo retry

**Pull request closed without merging**
