### PR TITLE
[FIX] auth_ldap: LDAP Authentication error handling

### PR DESCRIPTION
**Pull request by manali-malpani**
The current ldap implementation does not handle correctly all error conditions, this PR attempts to make the behavior well-defined in all situations.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by manali-malpani** [comment]
Hello @odony @Yajo 

I closed the PR  https://github.com/odoo/odoo/pull/71159 as I messed up with the PR while targeting it to branch 12.0
And then I had few challenges while creating a new PR against 12.0 so I had dropped the details in mail to ODOO security.
Meantime, I realized my mistake while creating the PR for branch 12.0 and here is another one.


(a Python client application using python-ldap is only supposed to handle the documented exceptions, and must consider "no exception' as a successful bind. ....)
Regarding the above comment, I agree @odony and thanks for your detailed explanation.


(So I'd also remove the extra logging that was added, because it will create noise in the logs.)
As you suggest, I have removed the extra log as in the previous pull requests. 

@bodedra - FYI

**Review by bodedra — APPROVED** [review]
LG :+1: 

@manali-malpani thanks for your excellent work and being patient.

**Comment by odony** [comment]
Thanks, feedback about this PR was already sent by direct email reply to @manali-malpani.

**Comment by manali-malpani** [comment]
Thank You @odony for your comments. I have replied over mail to security@odoo.com.

**Review by odony — APPROVED** [review]
@manali-malpani excellent, thanks for the update!

The patch will likely conflict during the automatic forward-ports, but don't worry we will handle the minor changes required, you won't need to do it again ;-)

@robodoo r+

**Pull request closed without merging**
