### PR TITLE
Addons website leaflet map 10.0

### PR DESCRIPTION
**Pull request by mmuman**
This PR adds a website_leaflet_map addon (drop-in compatible with the website_google_map addon) which uses the OpenStreetMap tiles and Leaflet.js to build the map.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
(cf. #13875 )

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but we do not accept new features in Odoo (except the one [detailed here](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch))
Regards

**Comment by mmuman** [comment]
Not so much a new feature than an alternative source for an existing one. I noticed there was an external module repository I could contribute to, but still, it's a bit of a shame to have defaults relying on Google everywhere, only a few people would dig and find alternatives if they aren't available by default…
Anyway, thanks for checking.

**Comment by lukebranch** [comment]
@mmuman,

I can see how this might be a useful feature for those who can't access google (e.g. Those behind the GFW - Mainland China).

I'd suggest requesting comments by opening an issue on the following repository here:

https://github.com/oca/website

**Comment by mart-e** [comment]
If you check #6929 there is a request to use openstreetmap by default for the maps localisation and rendering. It is still something we are open to if you are interested.

**Comment by mmuman** [comment]
@mart-e I see you tried using Nominatim, yes that would be nice indeed. I'll try to look into it when I get some time.
Interestingly, the GMaps TOS disallows caching geocoding, but does it allow using results from other geocoding providers on their maps?

**Pull request closed without merging**
