### PR TITLE
[IMP] pos_adyen: handle adyen payment request by push notification

### PR DESCRIPTION
**Pull request by caburj**
Instead of eager polling of payment status of a payment request at
every 5.5 secs for some number of tries, we are now using the longpolling
bus service to receive in the POS UI the payment status in near real-time.

Basically, when adyen server notifies the backend for the payment status,
the payment status will be automatically broadcasted. Open POS UI will
receive the notification and will handle it accordingly.

For robustness, the combinations of the following sets of possibilities are
taken into account:

* UI actions during payment
  - Wait for the payment status at the payment screen.
  - Go back to product screen - pay - then to payment screen.
  - Go back to product screen - then to payment screen - pay.
  - While pending payment, go back to backend ui - pay - open pos - payment
    screen.
  - While pending payment, go back to backend ui - open pos - payment screen -
    pay.
  - While pending payment, open another order and try to make another payment.
    * It shouldn't be allowed.
  - Normal payment but cancel the payment before the status is received.
  - Order with pending payment is deleted.
  - Pending payment is deleted.

* Payment terminal actions
  - Pay immediately
  - Payment error in the terminal
  - Wait long until payment is cancelled in the terminal. This is possible.
    Results to payment error.

Notable payment terminal action that is not considered:
  - Successful in terminal but the server is not notified (or the notification
    took so long.)
    * Workaround: The cashier can just cancel the pending payment.

TASK-ID: 2659918

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
From PIM:
1. No need for the override in bus.py, just add channel thru `addChannel` of the bus service object.
2. Channel should be derived from the `pos.config` record, not the session.

**Comment by caburj** [comment]
From PIM:
1. No need for the override in bus.py, just add channel thru `addChannel` of the bus service object.
2. Channel should be derived from the `pos.config` record, not the session.

**Comment by pimodoo** [comment]
@caburj what tool would you need? testing external services is almost impossible without calling the services, as mocking call won't guarantee that it'll work.

**Comment by caburj** [comment]
@pimodoo Maybe emulation can be our friend here. If we can emulate the payment terminal, we'll be able to write tours which can be enough to protect some important features. Well, refreshing the page might be a different story, but if tours can continue after page refresh, then we can also write automatic tests for page refresh while there is pending payment.

**Comment by caburj** [comment]
> For Adyen you can use a independant server and send your request to a specific route to reproduce each scenario.
But it is complex and need some maintenance

Good to know that there is this option. But I'm thinking more on expanding what ANP started in the tour test he wrote for payment terminals in pos_iot.

But aside from the automatic test, you can now review this PR and do some manual testing. And if you found a situation that needs consideration, don't hesitate to comment.

**Comment by C3POdoo** [comment]
Dear @caburj,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
