### PR TITLE
[IMP] GettextAlias _get_lang and _get_cr from request

### PR DESCRIPTION
**Pull request by kirca**
related [Pull Request](https://github.com/odoo/odoo/pull/5123)

### CODE REVIEW

**Comment by antonylesuisse** [comment]
This one looks ok. You email is .eu instead of .com in the CLA.

**Comment by kirca** [comment]
Is there a requirement for it to be .com? :)

**Comment by antonylesuisse** [comment]
Nope just that it should match the Author: header.

**Comment by kirca** [comment]
Thanks Antony. Made the change and re-based the commits.

**Comment by odony** [comment]
Looks good now, thanks!

**Pull request closed without merging**
