### PR TITLE
[FIX] project: fixed 'parent task' stat button if the 'sub-tasks' fea…

### PR DESCRIPTION
**Pull request by matu-odoo**
…ture is disabled

currently, 'parent task' stat button is visible even if the 'sub-tasks' feature is disabled.

so,this commit fixes the issue.

Task : 2834743

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for the fix. 🙂

**Review by IT-Ideas — COMMENTED** [review]
Thanks for your work 🙂 
Why not fixing it in saas-15.1?

**Comment by mba-odoo** [comment]
@IT-Ideas , done. changed target to 15.0. Thanks

**Review by IT-Ideas — COMMENTED** [review]
Thanks 🙂 
@robodoo r+

**Comment by IT-Ideas** [comment]
@mba-odoo it looks there is something strange with the commits... it is like there is more than one.
Could you repush to try to reset it?
Thanks

**Comment by mba-odoo** [comment]
@IT-Ideas , pushed changes. even doesn't work then we will create a new branch starting with `15.0-` Thanks

**Comment by IT-Ideas** [comment]
Thanks 🙂 
@robodoo r+

**Pull request closed without merging**
