### PR TITLE
[FIX] web_editor: permission issue for colorpicker to read template

### PR DESCRIPTION
**Pull request by dhp-odoo**
**PURPOSE**

Only system and designer users can access ir.ui.view records.
An employee, portal, or public user should not be able to read a view arch.
All operations on views must be done using sudo or using helpers like _render
or fields_view_get.

Now in case of web_editor.colorpicker, the user having no system and designer
group tries to read the template will lead to permission issue as we are not
allowing to access ir.ui.view model directly for external world now.

**SPEC**
So we are accessing the read_template method of ir.ui.view model using sudo by
calling controller resolves the permission issue.

Task :  2322545

### CODE REVIEW

**Comment by mart-e** [comment]
I am not a huge fan of adding controllers for each template but if it's the only one where it's needed in web_editor...

This will need to be adapted as well by the way

https://github.com/odoo/odoo/blob/0e12fa135882cd5095dbf15fe2f64231c6a84336/addons/web_editor/static/tests/test_utils.js#L96-L98

web_studio also makes a call to `read_template`, to investigate if it's problematic too

**Comment by msh-odoo** [comment]
> I am not a huge fan of adding controllers for each template but if it's the only one where it's needed in web_editor...
> 
> This will need to be adapted as well by the way
> 
> https://github.com/odoo/odoo/blob/0e12fa135882cd5095dbf15fe2f64231c6a84336/addons/web_editor/static/tests/test_utils.js#L96-L98
> 
> web_studio also makes a call to `read_template`, to investigate if it's problematic too

@mart-e I traced this and I found this is never called, looks strange but after debugging I found colorPallete has root.widget(in our case webclient instance) as parent and rpc call never intercepted and due to which this code never executes, I checked call in network panel and I found server call done to read template in test mode

**Comment by msh-odoo** [comment]
@mart-e Regarding studio does read_template call, after checking I found studio icon is visible to only "group_system" so I think it should never create issue

**Comment by dmo-odoo** [comment]
@mart-e @qsm-odoo I have a feeling of deja-vu on this. Didn't we already discuss a similar issue months ago ?

**Comment by qsm-odoo** [comment]
Yes, fixed in stable last month with https://github.com/odoo/odoo/commit/8af75e00bdcda3d5ff4facd2f5f146e1d6bf79e4 and the proper way in master with https://github.com/odoo/odoo/commit/834e3f8f9b74da35820fd728006a95c7b7c8dc4f

**Pull request closed without merging**
