### PR TITLE
[FIX] account : correct analytic rule validation message

### PR DESCRIPTION
**Pull request by hamzaislam101**
An analytic rule can be created without any tag so the error message is not correct.

Steps to Reproduce:
In v14 and v15, try adding an analytic defaults rule without an account and without any tag.

Current Behaviour:
The error message says that either an analytic tag or an account is required for the rule to be created.

Expected Behaviour:
We can clearly see that the rule can be created without a tag, but not without an account. So the account is the only required item here.

OPW-3274645

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by kitan191 — CHANGES_REQUESTED** [review]
Thanks for the fix.

But when changing a translatable term, you should also adapt the corresponding `pot` file.

**Review by kitan191 — APPROVED** [review]
LGTM

**Comment by gawa-odoo** [comment]
Hello!
That's wrong, and the error message should be quite explicit about it. 
You can see it here: "An analytic default requires an analytic account or an analytic tag **used for analytic distribution**".
So, create a tag with an analytic distribution, and the analytic account on the default rule is not mandatory. 
We should maybe be more explicit about the fact that you need an analytic account in the tag's distribution, but your fix can't be right. (TBH I'm not even sure it's mandatory, as most people would expect it if we talk about analytic distribution on a tag)

**Comment by gawa-odoo** [comment]
Yes, I think so.

**Pull request closed without merging**
