### PR TITLE
 [FIX] account: import of invoice by csv gave wrong account 

### PR DESCRIPTION
**Pull request by william-andre**
Task 1961719

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@nim-odoo this looks ok to me but it reverts one of your patch (see the commits history) so I'd likt to have your opinion on it

**Comment by qdp-odoo** [comment]
@nim-odoo anything to say?

**Comment by william-andre** [comment]
I think he doesn't want to, see task 1925547...

**Comment by william-andre** [comment]
BTW, funny how some people care about the reasons of a commit while others just revert it almost without a warning. https://github.com/odoo/odoo/pull/33192#issuecomment-492605091

**Comment by nim-odoo** [comment]
> @nim-odoo anything to say?

I don't have much things to say when there is absolutely zero explanation but "You just inversed the bug".

**Comment by william-andre** [comment]
@nim-odoo From _your_ commit message https://github.com/odoo/odoo/commit/0f0ad7d1d4223cbcd5f66c4ffcb1df06016852bf

> We simply inverse the condition, so it creates a consistent object.

What does that even mean ?

**Comment by nim-odoo** [comment]
I'll try to level up the argumentation here, and unfortunately that's not going to be difficult.

The first remark is that the commit messages do not follow our guidelines: https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure There is absolutely no explanation on any of the two commits, although this is necessary to understand the rationale behind any change (revert, fix or improvement).

These considerations set aside, there is something which doesn't seem right: why revert a change while it **looks** like the second commit is the good fix? There is no real point to revert such a modification if the proper fix is elsewhere: it just bloats the history. I'll just assume that the goal was to revert a useless commit, which makes sense... but it does so by introducing another useless commit. Still, it's not a big deal, so no need to focus on this.

In order to assess the correctness of the proposed fix, we can have a look at the default value for the invoice type. It turns out it is based on the context key `type`:

https://github.com/odoo/odoo/blob/c545783b95b15f65a9798003b614f75685dc434e/addons/account/models/account_invoice.py#L264

Since the second commit uses the context key `default_type`, this is something we should be careful about. There are obviously 2 keys with a common purpose, and moreover the field `type` is used in many other object models. This is an unfortunate naming choice and we have to be careful about it. Indeed, it is not uncommon that such context keys are propagated between objects; the `default_type` of an object A could be used in an object B if both have the `type` field.

In order to make sure which key is the correct one, we can quickly check a few actions leading to the `account.invoice` object. We notice that some of them define the `default_type` key, some don't:

https://github.com/odoo/odoo/blob/c545783b95b15f65a9798003b614f75685dc434e/addons/account/views/account_invoice_view.xml#L686

https://github.com/odoo/odoo/blob/c545783b95b15f65a9798003b614f75685dc434e/addons/account/views/account_invoice_view.xml#L780

Therefore, it seems that the correct key to use is `type`, not `default_type`. We can easily check it by going through Account > Customers > Invoices and importing an invoice. By debugging the process, we can see that `default_type` is not in the context.

The thing is, since this PR proposes to revert the original commit, this error means that it re-introduces the bug solved in https://github.com/odoo/odoo/commit/0f0ad7d1d4223cbcd5f66c4ffcb1df06016852bf. When the import is done from Account > Customers > Invoices, the Account Payable is used instead of the Account Receivable.
Here is a video demonstrating the behavior: https://drive.google.com/file/d/1zYew9cQApZUkEpJSB8Z1UzW9_xpzeg6D/view?usp=sharing

On a side note, this PR suggests the use of a context key in the method `_onchange_partner_id` but what about the other onchanges? What about `_onchange_cash_rounding`, which also uses `self.type`?

https://github.com/odoo/odoo/blob/c545783b95b15f65a9798003b614f75685dc434e/addons/account/models/account_invoice.py#L880

If the goal of this PR is to make sure to create a consistent object (sic!), then all onchanges should be covered. However, since there is no description the goal of this PR remains a mystery.

PS: as you can imagine, this kind of analysis takes some time. And to be honest, the issue solved by the original commit was a minor issue. One could simply add the `type` field in the import file to avoid any confusion. It took a couple of years to be discovered, which probably means that people could live with it.

When a commit introduces an error such an unbalanced journal entry which prevents people from closing their POS session (see details in OPW mentioned in https://github.com/odoo/odoo/commit/83b52e3a977bab3759e0c6d4fb6d2e30d1aee245), this is another story. We don't have time to perform a detailed analysis to find the error. We don't have time to make sure no incorrect entry is generated. People have it in production, and we don't know the extent of the issue. If incorrect entries are generated, this is a nightmare to solve afterwards. If people cannot close their POS sessions, timeouts could arise if too many orders are created.

So these extreme cases require an extreme solutions: a plain revert, which gives us time to analyze the issue introduced. This happened previously to pretty much all people working on the stable versions at Odoo, and it will happen again if necessary.

**Comment by william-andre** [comment]
@nim-odoo I guess you had something to say after all...

The problem of 0f0ad7d was that `type` was set to `False` because the onchange was called from the `create` method via 
https://github.com/odoo/odoo/blob/418babf7af7b52ba3aef120de9be49dea9669b74/addons/account/models/account_invoice.py#L1616-L1620
Just switching the logic of the if statement gives the inverse default : always the supplier account when called from create instead of always the customer account when called from the create.

This is why we need to get the type from the context.

Because `_onchange_partner_id` is the only of the called onchange that uses `self.type`, no need to change it elsewhere.

This said, I was careless by thinking that type was set with default_type in that case. I'm fairly certain I tested it but I didn't work anymore when I tested it before today, thanks for pointing that out. I took the same value as in https://github.com/odoo/odoo/blob/418babf7af7b52ba3aef120de9be49dea9669b74/addons/account/models/account_invoice.py#L264 to fix it.

**Comment by qdp-odoo** [comment]
@robodoo R+

**Comment by qdp-odoo** [comment]
@robodoo r+ I said

**Comment by william-andre** [comment]
Guess he doesn't like being yelled at

**Pull request closed without merging**
