### PR TITLE
[REV] purchase, account, sale: add account.order(.line).mixin 

### PR DESCRIPTION
**Pull request by ticodoo**
Original COM PR: https://github.com/odoo/odoo/pull/144608
Original ENT PR: https://github.com/odoo/enterprise/pull/55711

In the end the feature as implemented in the original PR is not desired/correct and the mixin is also not wanted due to it adding more complexity than removing. Additionally, we want to keep the SO and PO functionality/evolution separate so moving their apparently common fields/methods into a mixin was a mistake.

Therefore we revert the mixin and all of the renaming refactorings that also came out of the PR since they depend on the mixin and we do not want to handle the complexity of fixing the conflicts.

ENT PR: https://github.com/odoo/enterprise/pull/66583

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
therockok

**Comment by ticodoo** [comment]
@robodoo rebase-merge

**Comment by MiquelRForgeFlow** [comment]
I don't see why you have the revert the field renames. The field renames are welcome.

**Comment by ticodoo** [comment]
> I don't see why you have to revert the field renames. The field renames are welcome.

Because they were done after the mixin commit, which is the one that needs to be reverted. I prefer a complete revert and then new commits to do the renamings so that the history is clean/simple

**Comment by ticodoo** [comment]
let's do this :see_no_evil: 

@robodoo r+

**Comment by ticodoo** [comment]
Will it work?

@robodoo override=ci/style

**Comment by ticodoo** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
@robodoo override=ci/style

**Pull request closed without merging**
