### PR TITLE
[ADD] OpenCode individual cla

### PR DESCRIPTION
**Pull request by OpenCode**
My individual CLA. I need it for a PR.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `f...@openforce.it`
- you are signing _for_ the address `c...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by OpenCode** [comment]
@mart-e Is it ok now?

**Comment by mart-e** [comment]
@OpenCode it is still the same. You can check the commit content by adding `.patch` at the end of the URL of your PR
https://github.com/odoo/odoo/pull/41829.patch
You can see it is still not the same email address on the content and for the commit

**Comment by OpenCode** [comment]
@mart-e now it's ok

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
