### PR TITLE
[FIX] website, website_mass_mailing: fix parallax in modals

### PR DESCRIPTION
**Pull request by bvr-odoo**
Before this commit "parallax" animation was not working in modals.
This commit adds a parameter to the animation effects to enable
animations (triggered by the scroll) in the modals.

Note that for the "Newsletter" popup we have hidden the "parallax"
options. To make them work, it would be necessary to review the
structure of the "Newsletter" popup so that the vertical scrollbar is in
the same location as the "s_popup" snippet (on the ".modal" element).

task-2971402

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo delegate=@xO-Tx

**Comment by xO-Tx** [comment]
@bvr-odoo code LGTM :+1: but I got a strange behaviour while testing the code, (I can't have parallax animations for some cases like on newsletter popup) :thinking: 


https://user-images.githubusercontent.com/25032876/209699939-6757647d-1e4c-4ac0-b0ce-9c75513c0841.mp4

**Comment by bvr-odoo** [comment]
> @bvr-odoo code LGTM +1 but I got a strange behaviour while testing the code, (I can't have parallax animations for some cases like on newsletter popup) thinking
> 
>  14.0-test-parallax-mou.mp4


Indeed, this is due to the vertical scrollbar which is not on the right element (".modal-body" and not ".modal" as for the "s_popup" snippet). In stable, we will hide the parallax options in this case, but in master it would be necessary to fix that.

**Comment by bvr-odoo** [comment]
@xO-Tx I have made some changes following your last comment. The PR can be reviewed again.

**Review by xO-Tx — CHANGES_REQUESTED** [review]
As discussed on discord, It would be better to avoid the `shown` event to init the scroll on the targeted image :+1:  (to prevent this lag when the modal is shown for the first time) 

https://user-images.githubusercontent.com/25032876/211555475-2a991b36-a422-4686-a6b3-62b92cfd49a7.mp4

**Review by xO-Tx — APPROVED** [review]
@bvr-odoo LGTM Thanks for update :+1:  Just to have a record about what we discussed:
A- There is a lag on image when the parallax element is shown for the first time (caused by triggering the scroll on the element to have image in the right position) otherwise it will be done on scroll :grimacing: 

A solution to this behaviour can be implemented on `show` event :
```javascript
$(this.modalEl).on('show.bs.modal.animation_parallax', () => {
    this.modalEl.classList.add('invisible');
});
$(this.modalEl).on('shown.bs.modal.animation_parallax', () => {
    this._rebuild();
    this.modalEl.dispatchEvent(new Event('scroll'));
    this.modalEl.classList.remove('invisible');
});
```
But this will hide the modal (and modal content) animations "on show"... 
We can improve this after merging the code here since it's not related to parallax on modals (I can add a task for it if it's not already done :+1:).

B- The parallax is disabled on "Newsletter" since the scrollbar is on the "modal-body" and should be moved to the "modal" element for master :+1:

**Comment by xO-Tx** [comment]
@robodoo r+

**Comment by bvr-odoo** [comment]
> B- The parallax is disabled on "Newsletter" since the scrollbar is on the "modal-body" and should be moved to the "modal" element for master

As of version 15.0, the "Newsletter Popup" snippet has been refactored to extend the "Popup" snippet. This means that the parallax effect works on it from V15.0, because the scrollbar is on the ".modal" and no longer on the "modal-body".

**Pull request closed without merging**
