### PR TITLE
[FIX] l10n_cl: translate term in invoice

### PR DESCRIPTION
**Pull request by taqu-odoo**
Issue
-----
A term doesn't have a translation available.
Note: no Transifex project associated.

**opw-3816657**

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

in 17.0 the file is now called addons/l10n_cl/i18n/es_419.po so the fix will probably need to be adapted to this file

side note: in the code we either see Monto or Importe

**Comment by taqu-odoo** [comment]
@robodoo  r+

**Comment by nle-odoo** [comment]
robodoo delegate+

**Comment by taqu-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
