### PR TITLE
[FIX] Only HR Officer should be able to reset to draft an approved Times...

### PR DESCRIPTION
**Pull request by lmignon**
...heet

### CODE REVIEW

**Comment by lmignon** [comment]
No news about this ?

**Comment by sbidoul** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by tivisse** [comment]
Hello @lmignon 

Since the menuitem already has a groups="base.group_hr_user", I don't think it's useful to add a groups on the button. See:
https://github.com/odoo/odoo/blob/8.0/addons/hr_timesheet_sheet/hr_timesheet_sheet_view.xml#L218

**Comment by tivisse** [comment]
I'll close this PR but you can still provide a use case to reopen it. 

Thank you for your feedback,

Yannick.

**Comment by tivisse** [comment]
@lmignon, the menuitem is not visible in standard 8.0, but it is the case in 9.0. So I'll merge your PR, and wait the forward port. 

Thank you,

Yannick.

**Pull request closed without merging**
