### PR TITLE
[IMP] hr_recruitment : Add the possibility to mass sms applicants

### PR DESCRIPTION
**Pull request by jugj-odoo**
task-3354904

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kba-odoo** [comment]
robodoo r+

**Comment by pedrobaeza** [comment]
@jugj-odoo @kbapt this PR has introduced an error in the dependency chain, as `sms.composer` model may not exist if you don't have `sms` module installed (which is the case for some of us which uninstall all `iap` auto-install stuff). Can you please remove it or put it in a glue module?

See also #191635 for a similar report. cc @remi-filament

**Comment by jugj-odoo** [comment]
Hello @pedrobaeza, you're right, we'll fix it

**Comment by pedrobaeza** [comment]
Thanks for your prompt reply!

**Pull request closed without merging**
