### PR TITLE
[IMP] mail: remove search in discuss messages

### PR DESCRIPTION
**Pull request by seb-odoo**
It is a feature we would like to have, but it currently doesn't work well.

- Search is text based, but messages are HTML based, which means a lot of result
  make no sense because they match HTML tags, attributes, ... Inversely when
  searching for multiple words that do exist together but are separated by tags,
  it will fail to find them.
- Content of messages is actually not indexed, which means the search doesn't
  scale in big channel or with long messages. Indexing it is not trivial and has
  a huge cost in terms of storage and dependencies (trigram index for example).
- The search of the control panel is great for business documents but it does
  not fit the kind of searching UI that we would like inside discussions.

It is therefore decided to remove the feature until we are able to do it well.

Part of task-2369636
More information also on task-2359037

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Is it removing the search box in inbox ? Because I use it, not for content but for other fields (like searching on model sometimes).

**Comment by seb-odoo** [comment]
The whole control panel will be removed in a following commit so indeed inbox is concerned too.
It will be replaced by an integrated topbar on which we can add custom controls, so if there is a need to filter inbox by model you 
were right to mention it, because I currently have not seen as part of our specs.

**Comment by seb-odoo** [comment]
Personally I wish we could get Inbox completely out of discuss though. And the end of the day it's just a list view of notifications with a pretty format, not a real thread.

**Review by alexkuhn — APPROVED** [review]
@robodoo r+

**Comment by JJebara** [comment]
Have you considered keeping the search or at a minimum grouping ONLY for fields / attributes of the message.  For example I receive all my notifications in Odoo. It would be great to group them by Module, then type then subtype. Potentially partner or document. 

- Helpdesk --> Discussion
- Helpdesk --> Note --> System Notification
- Helpdesk --> Note --> Ticket created 
Etc.. This enables the user to scroll through the messages by function instead of a stream of continuous messages.

**Comment by alexkuhn** [comment]
Hello @JJebara, unfortunately the whole search feature in Discuss app had a very high chance to corrupt the local state, which results in huge issues like being unable to fetch some messages unless reloading the page completely. This would also happen with searches that are not based on the content of message.

We deemed important to solve the issue immediately, and we couldn't simply fix the search with a few changes to the code, because the implementation was fundamentally flawed with the architecture of Discuss app. So instead we decided to remove it, and reintroduce it back at a later date when it actually works.

I'm sorry that it has been almost 2 years and we still haven't implemented it. Making a search bar like the one in v14 that actually works flawlessly in any situation requires many improvements to the way Discuss works under the hood.

To give some good news: works on the search in Discuss is a top-priority task, and we are doing all our best to have something for version 17.

**Comment by JJebara** [comment]
Thank you for the update. Looking forward to seeing the update in 17. For now we are skipping the upgrade to 16.

**Pull request closed without merging**
