### PR TITLE
[FIX] mail: give additional values for partner creation

### PR DESCRIPTION
**Pull request by nboulif**
Steps to reproduce:

  - Install `crm` module (for test purpose)
  - Create a new lead
  - Set an email address, phone number, company name and contact name
  - Save the lead
  - In the chatter, send a mail (with the default recipient checked)

Issue:

  - The partner has only the email address set (also set as name).
  - The `contact name` on the lead is updated with the partner name
    (who is the email address).

Cause:

  When sending a mail with the default recipient checked, the partner
  is created based only on the email address (therefore, name is same as
  email), and when assigning the new partner on the lead, the
  `contact name` is updated with the partner name (who is the email
  address).

Solution:

  Alter the route `/mail/partner/from_email` and `/mail/message/post`
  so it can take or manage additional values for the creation of the
  partner.

opw-3512045

### CODE REVIEW

**Comment by aab-odoo** [comment]
@nboulif I guess you meant @odoo/rd-discuss

**Comment by nboulif** [comment]
> @nboulif I guess you meant @odoo/rd-discuss

Indeed, thanks :+1:

**Comment by seb-odoo** [comment]
Hello, I've not checked in details, but runbot is red, and at glance it looks like a lot of diff for a fix.

**Comment by nboulif** [comment]
Hello @seb-odoo , thank you the check :pray: 
Regarding the lot of diff, I do agree, but did not find any other way to be able to have the default recipient checked and still work with all the following flows:
- Send message directly (with default recipient checkbox checked)
- Send message after creating the partner in wizard (uncheck and then check the recipient checkbox)
- Send message through full composer (auto create partner before opening full composer wizard)

(sorry, should update the commit message)

Any idea on how to tackle this? Thanks in advance!

ps: I updated the tests to match the 'fix'.

**Review by reth-odoo — COMMENTED** [review]
Hi there
Nice work, indeed maybe a bit much for stable. I wasn't aware of that change, that's an unfortunate bug.

Since the behavior of setting the partner is specific to CRM, in stable I think it may be reasonable to do something in the lines of:
- Check if the new partner from the 'suggested' flow has the same name as email
- If we have a name, and it's different from the name of the partner, update the name of the partner before assigning it to the lead

Thankfully `_message_post_after_hook` already makes the assumption the email will come from the 'suggested' flow so no new assumption with this.

This should fix this particular issue for stable while not adding tons of changes. I think this may be a welcome improvement for master though. Maybe shifting some logic to the back-end instead of grabbing stuff from the js record.

**Review by seb-odoo — APPROVED** [review]
Just noting it here: from what we discussed by PM I think the approach makes sense.

Let me know when it is rebased on the PR with the defaults and I'll check again.

If an easier solution is possible in stable, then it would be nice to consider it.

**Comment by nboulif** [comment]
Hello @reth-odoo @seb-odoo :wave: 
I created a new PR here with the fix only in CRM (for stable after our MP): https://github.com/odoo/odoo/pull/151378
I will rebase this one to `master` for the generic fix in mail.

**Comment by tde-banana-odoo** [comment]
Have to say it feels weird to me to have a 250 lines fix, following a 250 lines fix (https://github.com/odoo/odoo/pull/128292) to propagate few values computed in server through all layers of discuss, redoing computation, calling again some new controllers, ...

Suggested recipients should be a simple thing: server prepare values, we send them to the client, and when choosing to create a recipient, we create a partner with those values and it is included in posted message.

How are we ending with 500+ lines of bugfix code just to try to keep this behavior ?

**Comment by tde-banana-odoo** [comment]
As discussed on discord, approach LGTM, especially fixing it neatly in 16.3 instead of doing a post-posting hook as a local fix. Will be off next week for information.

**Review by seb-odoo — APPROVED** [review]
Thank you for the PR, the code looks cleaner like this.

I tested with both automatic checking box and manually sending the dialog, both worked as intended.

@robodoo r+

**Pull request closed without merging**
