### PR TITLE
[CLA] add Vincent to contributors

### PR DESCRIPTION
**Pull request by Yenthe666**
Adding our missing co-worker to the CLA

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e another CLA update from us :)

**Comment by mart-e** [comment]
Is it intentional to add empty lines between each members? :thinking:

**Comment by Yenthe666** [comment]
Hehe, Ward started with it and it looks like we just followed. I've removed those :)

**Comment by mart-e** [comment]
Thanks !
@robodoo r+

**Comment by Yenthe666** [comment]
Thanks a lot :)

**Pull request closed without merging**
