### PR TITLE
[FIX] coupon: fix onchange method for domain field

### PR DESCRIPTION
**Pull request by yelizariev**
Field `has_partner_email` depends on `partners_domain` field, which uses domain widget. The domain widget may generate broken value. This commit fixes it by checking that value in the onchange method.

STEPS:

1) go to coupon programs
2) click generate coupon
3) select <Number of Selected Customers>
4) click on domain field, and click the arrow back (nothing is in the domain)
5) if you click on the scrollbar, error appears (the same for any other click
that triggers onchange)

Alternative solution could be fixing the domain widget. But this looks as an overkill for v14 for few reasons. First, the js client was heavily updated in v15+. Second, the problem is quite specific for this module and v16 has not such usage examples in standard modules.

opw-3062969

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Williambraecky** [comment]
>Alternative solution could be fixing the domain widget. But this looks as an overkill for v14 for few reasons. First, the js client was heavily updated in v15+. Second, the problem is quite specific for this module and v16 has not such usage examples in standard modules.

Is this fix required in 15? I know it isn't in 16 but it's not clear for v15 from your comment.

**Review by Williambraecky — APPROVED** [review]
A test would be appreciated.

**Comment by yelizariev** [comment]
@fw-bot up to saas-15.2

https://github.com/odoo/odoo/blob/2716ed3ba718974e1078b4055f419097d2ada514/addons/coupon/wizard/coupon_generate.py#L44-L48

@Williambraecky the issue is quite specific and doesn't exists in 16.0
It would make sense for a test if I update the domain widget, but here I update compute method only

**Comment by Williambraecky** [comment]
Alright, thanks for your work.

robodoo r+

**Pull request closed without merging**
