### PR TITLE
[ADD] Added Finnish localization modules

### PR DESCRIPTION
**Pull request by mlaitinen**
Description of the issue/feature this PR addresses: Finnish chart of accounts.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

I let the accounting team review the content but could you describe a bit your change?
I see you are creating two modules, why is that? What is the different between both?

You have also added translations but this is not needed for localisations, the account names are not translatable by default. Except if you wish also to translate it in Swedish (and [enable multilang](https://github.com/odoo/odoo/wiki/Translations#how-to-translate-my-chart-of-account-into-multiple-languages)) but you do not need fi.po anyway.

**Comment by mlaitinen** [comment]
I created two modules because there are two CoAs for Odoo; Raportointikoodisto and Liikekirjuri.

This `l10n_fi_rapko` is Raportointikoodisto, which is more modern and better structured for reporting to the officials, but less known. There's `l10n_fi_liikekirjuri` which is the more traditional and well-known CoA. It's not made by us but it's likely that it will be contributed to the Odoo core as well.

I believe these modules would benefit from a common base module `l10n_fi` although I nearly pulled my hair out when I realized that using common taxes and fiscal positions for both CoAs is quite impossible.

The reason why `l10n_multilang` is a dependency is that the taxes and fiscal positions are both in English and in Finnish. The accounts are only in Finnish and they will remain only in Finnish, because there's no ready translation and translating all of them would be overwhelmingly difficult and would take a long time.

**Comment by mart-e** [comment]
> The reason why l10n_multilang is a dependency is that the taxes and fiscal positions are both in English and in Finnish. The accounts are only in Finnish and they will remain only in Finnish, because there's no ready translation and translating all of them would be overwhelmingly difficult and would take a long time.

But there is some issues:
- l10n_fi depends of l10n_multilang but it is l10n_fi_rapko that has translatable content, shouldn't it be moved?
- to benefit from the l10n_multilang mechanism, you should have a `spoken_language` key with the list of languages the CoA will be translated into ([see l10n_ch](https://github.com/odoo/odoo/blob/bd4b50f75a255155a98949c8c3fe3bd0db3695b6/addons/l10n_ch/data/l10n_ch_chart_data.xml#L21))
- for manual translations, put it in a i18n_extra folder
- keep it to the minimum, the .pot file should only include the terms that will be translated (so the taxes here)

**Comment by mlaitinen** [comment]
1. This dependency thing is my bad. I'll fix it.

1. I never understood the meaning of `spoken_languages`. What does it do?

1. Is `i18n_extra` excluded from Transifex or what's the difference to `i18n` folder?

1. I exported the `.pot` file from Odoo. Should it be edited by hand to include only the terms that will be translated?

**Pull request closed without merging**
