### PR TITLE
update odoo-cla

### PR DESCRIPTION
**Pull request by pablohmontenegro**

### CODE REVIEW

**Comment by pablohmontenegro** [comment]
@zaoral

**Review by zaoral — APPROVED** [review]
+1

**Comment by zaoral** [comment]
@jco-odoo

Hi Jos.
Please could you help us with this PR that adds a new member to the ADHOC's CLA?

Best Regards

**Comment by jco-odoo** [comment]
Please use the standard way for commit msgs: [CLA] ...

**Comment by zaoral** [comment]
@jco-odoo ready the commit message has been changed

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
