### PR TITLE
[ADD] Colombian - Initial setup data

### PR DESCRIPTION
**Pull request by kurkop**
This patchs adds position "before" to COP currency in res_currency_data.xml and address_format to res_country_data.xml.

Reference:
https://en.wikipedia.org/wiki/Colombian_peso

### CODE REVIEW

**Comment by damodaranudas** [comment]
It is a basic Colombian accounting feature, please add it

**Comment by hivam** [comment]
I agree

**Comment by kurkop** [comment]
@qdp-odoo Please consider merging.

**Comment by mart-e** [comment]
Thanks, merged at 799f12c326e4f4a36e072ed0ccb8451e1b78fcda

**Pull request closed without merging**
