### PR TITLE
[REF] point_of_sale, *: convert legacy modules to ES odoo modules 

### PR DESCRIPTION
**Pull request by sdegueldre**
*: l10n_co_pos, l10n_fr_pos_cert, l10n_gcc_pos, l10n_in_pos,
l10n_sa_pos, pos_adyen, pos_discount, pos_epson_printer,
pos_epson_printer_restaurant, pos_hr, pos_loyalty, pos_mercury,
pos_restaurant, pos_restaurant_adyen, pos_restaurant_stripe, pos_sale,
pos_sale_product_configurator, pos_six, pos_stripe

We are about to refactor most of the Javasript code base of the point of
sale and related modules. In doing so, we will move a lot of files and
modernize the entire code-base. In order to avoid diffcult rebases,
their conversion to odoo-modules is done as a first step to avoid
getting lots of conflicts on files that were unindented, which marks the
entire file as being in conflict. Conflicts will occur during forward
ports but they will be easier to manage as the changes will be much
smaller in scope, and the author will have the context of the change
that causes the conflict in mind when dealing with it.

### CODE REVIEW

**Comment by sdegueldre** [comment]
@odoo/rd-security Hello, can you take a look at this security flag? Some markups have had their indentation changed. The markups should probably be changed to interpolate the translated string into the tags rather than using markup on the output of _t, but I'm hoping to do that as a second step. Most of this code will move soon and I'm hoping to drill into where the data that's being fed into $.html is coming from at that point, if that's ok with you.

**Comment by trj-odoo** [comment]
@robodoo r+

**Comment by trj-odoo** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo check

**Pull request closed without merging**
