### PR TITLE
[FIX] requirements: update psycopg2 version

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: `psycopg2 2.7.1` fails on arch linux 

Current behavior before PR: The `psycopg2` version `2.7.1` fails on arch linux

Desired behavior after PR is merged: The newest version of `psycopg2` (version `2.7.3`) works fine and should work fine on the other OS'es too.

Fixes https://github.com/odoo/odoo/issues/19511

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@d-fence could you please check this one?

**Comment by mart-e** [comment]
Hello,

Were you able to reproduce the error?
I doubt the error mentioned is about psycopg version but more an incompatibility between two upgrades.

**Comment by mart-e** [comment]
Duplicate of #19512 + re-adding psycogreen

**Comment by Yenthe666** [comment]
Second commit fixed the re-adding. But, yes, duplicate apparently. Sorry.

**Pull request closed without merging**
