### PR TITLE
Add me to camptocamp.md CLA

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `simahawk@users.noreply.github.com`
- you are signing for the address `s..@camptocamp.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by simahawk** [comment]
@mart-e I update it with my current github email. Is it good now?

**Comment by mart-e** [comment]
Not really, you are still making the commits using the web interface, with your `@users.noreply.github.com` email address (check [here](https://github.com/odoo/odoo/pull/15236.patch))
As this is a corporate CLA, it is probably better to only keep corporate addresses.

Another possibility is to ask an existing c2c member (like @gurneyalex or @guewen ) to add your signature into the corporate one.

**Comment by simahawk** [comment]
@mart-e ops, sorry, I didn't new that web UI does not use you current account :(

**Comment by simahawk** [comment]
closing this in favour of https://github.com/odoo/odoo/issues/15250

**Pull request closed without merging**
