### PR TITLE
[FIX] sale: translate down payment product name

### PR DESCRIPTION
**Pull request by domenicostragapede**
Description of the issue/feature this PR addresses:
Translate the product name "Down payment" when it is created "on the fly" from wizard.

Current behavior before PR: 
The down payment product has a "Down Payment" name, regardless the language used.

Desired behavior after PR is merged:
The name of the product is translated into the correct system language.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Feyensv — CHANGES_REQUESTED** [review]
Please add a commit to [sign the CLA](https://github.com/odoo/odoo/wiki/Sign-CLA) before we can integrate your changes ;)

Could you also follow our [commit guidelines](https://www.odoo.com/documentation/14.0/developer/misc/other/guidelines.html#commit-message-structure) for your commit (and use a title in the format `[FIX] sale: ...`)

Thanks

**Comment by domenicostragapede** [comment]
I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

**Comment by domenicostragapede** [comment]
> **Feyensv ** requested changes

Done!

**Comment by Feyensv** [comment]
@robodoo r+ rebase-ff

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
