### PR TITLE
[FIX] crm: update counter

### PR DESCRIPTION
**Pull request by Xavier-Do**
The test is currently disable on runbot and the test is breaking
every night. Update the counter to check if it is still random.

### CODE REVIEW

**Comment by Xavier-Do** [comment]
@fw-bot ignore

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by tde-banana-odoo** [comment]
@fw-bot ignore

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
