### PR TITLE
[FIX] mail: Allow update calendar event date even if not responsible

### PR DESCRIPTION
**Pull request by nboulif**
Issue

        - Install "Calendar" module
        - In Calendar app and as Mitchell Admin,
          edit any event where Marc Demo is responsible.
        - Change start date and save.

        Access error.

Cause

        Altering the 'start' dates generate a new mail.mail through send_mail.
        Not enough rights to write on mail just after creation.

Solution

        Add check access rights/rule to related document
        Use sudo since have access to related document.

inspired by commit in 14.0 : https://github.com/odoo/odoo/commit/69ccabb212d83bfee60c7dade36ca4b06f9f2f12

opw-2439298

### CODE REVIEW

**Comment by nboulif** [comment]
@tde-banana-odoo

**Comment by nboulif** [comment]
@tde-banana-odoo Good morning! I just noticed this PR https://github.com/odoo/odoo/pull/66166, I guess I can close this one?

**Comment by tde-banana-odoo** [comment]
Hello,

Indeed in 13 I prefer to keep a localized one than adding a wide sudo in template model. Thanks for pointing it out :)

**Comment by nboulif** [comment]
@tde-banana-odoo My pleasure. Thanks to you!

**Pull request closed without merging**
