### PR TITLE
[IMP] improve do_detailed_transfer to avoid executing recompute_remaining_quantities()

### PR DESCRIPTION
**Pull request by apineux**
This pull request is an improvement of the do_detailed_transfer() method:

For every product we 'write' on the pack.operation or we 'create' a new one. For each of these, the method do_recompute_remaining_quantities() is executed on the current picking.
In this pull request I suggest to add the "no_recompute" in the context of the 'write' or 'create' to avoid executing the do_recompute_remaining_quantities() every time on the same picking, and at the end we call the method manually.
When you have a picking with a lot of pack.operation, this improvement will be really significant.

Thanks to review it and give me your feedback if there is one.

Regards,

API

### CODE REVIEW

**Comment by moylop260** [comment]
Hello @apineux 
Thanks for you pr.

I saw a green into runbot:
http://runbot.odoo.com/runbot/repo/git-github-com-odoo-odoo-1?search=6180
Cool!

if you you allow me, I will give my feedback

With a change like that is important has a test to verify result after of this change.
Force use this line of code and check result.
I don't searched if this test is exists.
Do you have it considered?

**Comment by moylop260** [comment]
FYI
runbot log of PR show this:
```log
2015-04-08 15:00:33,344 1708 INFO ? openerp: OpenERP version 8.0
2015-04-08 15:40:31,488 1708 INFO 60503-6180-c9e61a-all openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```
time spent: 39:58

-------------
runbot log of original show this:
```log
2015-04-08 13:48:16,729 26276 INFO ? openerp: OpenERP version 8.0
2015-04-08 14:15:54,027 26276 INFO 60471-8-0-a69691-all openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```
time spent: 27:38

**Comment by apineux** [comment]
Hello @moylop260 

Thanks for your feedback. We should effectively create a test to make sure that the result is the same before the patch and after the patch. The only problem is that we have to create a new pull request with only the Test and merge it before merging this PR. I'll check what I can do about that.
For the time spent on the runbot it is irrelevant so you shouldn't take that into account to check the performance improvement.
The tests we have are usually not big enough to see the difference.
Let me explain:
If you have a picking with only one pack operation then the code I provided or the standard code will do the same (Compute the pack then recompute the picking).
If you have thousand of pack operation the executing the re computation of the picking a thousand time is not necessary and consume time.
I suggest you to check manually the performance improvement by creating example with a lot of pack operation.

Regards,

**Comment by moylop260** [comment]
Hello @apineux 
I got it
Thank you

**Comment by josemoralesp** [comment]
@apineux @moylop260  I used something similar to call the method action_done_from_ui. I reduced considerably the times with big pickings passing the key no_compute and then recompute manually at the end.
e.g.
pick_obj.with_context(no_recompute=True).action_done_from_ui(self.picking_id.id)
self.picking_id.do_recompute_remaining_quantities()

**Pull request closed without merging**
