### PR TITLE
[IMP] mail, web: chatter top design

### PR DESCRIPTION
**Pull request by stefanorigano**
enterprise:
- https://github.com/odoo/enterprise/pull/32209

task-3005130

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @odoo/rd-discuss , ready for tech review 👍 
@aab-odoo , you may want to have a look too, minor changes in CP.

cc @bouvyd

**Review by aab-odoo — APPROVED** [review]

**Comment by alexkuhn** [comment]
Chatter topbar overflows when it's aside the form view (so with screen size XXL, which is 1080p or 1440p IIRC)
Screenshot 2022-10-05 at 11 13 17
Overflow is worse when there's more items, like here in chatter of a documents.document:
Screenshot 2022-10-05 at 11 13 38
All this without considering texts in some languages that are much longer than in English.

So the layout should definitely, at the very least, split the left and right parts, so they can be on 2 different rows. This is essential when texts are local-dependent.

**Comment by stefanorigano** [comment]
@phenix-factory , thanks.
It's the expected behaviour.

--- 

@alexkuhn , thanks

> Chatter topbar overflows when it's aside the form view (so with screen size XXL, which is 1080p or 1440p IIRC)

Weird, I didn't experience that, possibly due to the fact that now we use system-fonts.
It must be addressed anyways, as you correctly pointed out  translations may push things out of control.
The only solution I see is to increase the side-chatter width...

**Comment by alexkuhn** [comment]
> The only solution I see is to increase the side-chatter width...

The current design handles this case by making 2 rows:
Screenshot 2022-10-05 at 13 48 05

Here the decision is left part at the bottom, because style of "Send message" and "Log note" being active only works when they are next to the composer.

You may keep this same behavior, which is one of the best trade-off while keeping text of arbitrary length (and width being constrained)

**Comment by stefanorigano** [comment]
@alexkuhn , 
> The current design handles this case by making 2 rows:

I'm aware but we have to implement the new design that comes with everything in one row.
Consider that the new fomView's CP is in one line now ;)

I managed to keep the current width letting it increase in case is needed.
I think that solves everything.

https://user-images.githubusercontent.com/8558351/194093613-9036dfab-c5a6-43df-93f3-462628a37b6a.mov

**Comment by bouvyd** [comment]
@stefanorigano The one-line design seems pretty sensitive to language choice:
image

Not sure that it can easily be solved without either max-width + ellipsis or with flex-wrapping the 2 button groups

another possibility could be to remove the "follower" label (just the icon + a tooltip)? that could leave enough space for most cases (but i'd still look into having a graceful degradation with ellipsises or wrapping the groups...)

**Comment by stefanorigano** [comment]
> The one-line design seems pretty sensitive to language choice:

weird. @alexkuhn I handled it [here](https://github.com/odoo/odoo/pull/101979/files#diff-eeddc9cf9bcc9fd2549581faf812dc1274ef566372234c02946a0024ee322cd5R8) , could you have a look?

> another possibility could be to remove the "follower" label (just the icon + a tooltip)

It would mean a return to the "bell icon"... I'm not against that but it raised usability concerns for v11 If I'm not wrong.
Truncating is tricky.... actions like `[Enregistrer une...]`  will not be ideal  :/ 

This system seem to work correctly except for the translation bug you spot, let's see if Alex can find issue.

**Comment by seb-odoo** [comment]
- the entire width changes when clicking on follow/unfollow, and all other buttons are moving, this is not really great
- send message is highlighted even when it is closed, which is confusing
- focus outline is badly overlapping between knowledge/attachment/follower/etc buttons
- removing attach files is a revert of a task made 2 month ago (also what's the point to remove the text in that case if it still shows "x files" in full when there is one?)
- consequently, adding new files when there was none is also changing the entire width, which is also not great

Overall the new style is great, but it's really annoying to have elements moving around or changing width when anything in the content changes.

**Review by alexkuhn — APPROVED** [review]
@robodoo r+ rebase-ff

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
