### PR TITLE
[FIX] website: customize logo

### PR DESCRIPTION
**Pull request by simongoffin**
The company logo can't be customized because it's a t-field from the db.

opw:632702

### CODE REVIEW

**Comment by beledouxdenis** [comment]
@Gorash approves ?

**Comment by simongoffin** [comment]
Yes, he told that it's ok for him.

**Comment by beledouxdenis** [comment]
Fine then : )

**Comment by beledouxdenis** [comment]
Closed with 3760b1f0f4ca310f2d136941653397a5c1aeb0a1.

**Pull request closed without merging**
