### PR TITLE
[IMP] web: patch/unpatch: allow to re-apply a patch

### PR DESCRIPTION
**Pull request by aab-odoo**
In tests, we might want to disable a specific patch for a specific
test (e.g. to remove a monkey patch done when another addon is
installed, to test the behavior of the current addon).

Before this commit, it was possible to unpatch at the beginning of
the test, but we couldn't re-patch when the test was over.

Feature required by task~2392303

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r-

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r-

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
