### PR TITLE
Log error messages properly

### PR DESCRIPTION
**Pull request by dek-odoo**
Current behavior before PR:
> Error messages are not logged properly

Desired behavior after PR is merged:
> Better error messages with more details to find the root cause of the problem

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Thanks for the proposal I agree more information could be useful to understand the problem but I can not accept it right now as:

- you have not [signed the CLA](https://www.odoo.com/sign-cla)
- you are modifying translated content (it would break the existing translations), create new strings if you want to add content
- the error message you are showing is too technical (e.g. `<class 'ZeroDivisionError'>: "float division by zero" while evaluating '1.0/0' `), display just the message

**Comment by dek-odoo** [comment]
Signed CLA [here](https://github.com/odoo/odoo/pull/26593)

**Comment by mart-e** [comment]
Thank you for the CLA. However you are still changing the translatable string.
If you do
```python
_('foo' + ' bar')
```
The translated string is still `'foo bar'`.

**Comment by mart-e** [comment]
Merged in master (as an improvement) at 
228225a1eb0 [IMP] hr_payroll: log the error during evaluation
e398e1674a6 [IMP] base: log the name of the group that is failing

As we are in master we can change the translatable content.

**Comment by dek-odoo** [comment]
No problem @mart-e

**Pull request closed without merging**
