### PR TITLE
[FIX][16.0] project_purchase: Project Admin can't access project update when having PO

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
Step to reproduce:

First configure your project to have a `analytic.account` call `Research & Development`
Create PO with `analytic_distribution` to also have that same `analytic.account`
As a Admin Project (with no PO Acess Right - no anything of it) then access error

Video to reproduce on runbot at date 14-09-2023:

https://github.com/odoo/odoo/assets/56789189/442dc653-1c1a-4e33-ba7d-0bd84c5e35aa

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476** [comment]
@pivi-odoo @thle-odoo Could you have a look? thank you

**Comment by duong77476** [comment]
> Hello @duong77476,
> 
> Thank you for your PR.
> 
> The R&D Services team has been pinged about your PR, they will be the one doing the review :)
> 
> In the meantime, consider:
> 
> * update your commit/PR message to specify: Current behaviour, expected behaviour, steps to reproduce (which you've already provided), the cause of the issue and how/why you did said fix implementation.
> * consider adding a little test that reproduces your issue, it would help.
> 
> Know that the review may take a bit of time.
> 
> Thank you for your understanding.

Thank you, i'll update my commit message

**Comment by royleviindoo** [comment]
Hi @xavierbol , can you review this PR, thank

**Comment by auon-odoo** [comment]
robodoo r+

**Pull request closed without merging**
