### PR TITLE
[IMP] sale: Allow partner removal if linked to draft/cancelled SO

### PR DESCRIPTION
**Pull request by tivisse**
TaskID: 3233204

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by chevalierv** [comment]
Hello @tivisse,

Can you explain why this change is needed?

Have a nice day :sun_with_face:

**Comment by tivisse** [comment]
When a user asks to be forgotten, it is now possible to remove his user, but it's still impossible to remove its partner (containing his name, etc).

The goal of this commit is to unlink the draft/cancelled SO to allow the partner deletion. 

Note: Validated with AL/ODO.

**Comment by tivisse** [comment]
@chevalierv Note that at worst if the deletion fails later everything will rollback so the SOs won't be deleted.

**Comment by chevalierv** [comment]
@tivisse Thanks for the explanation. I think it is a great improvement :smiley: 

Why is this change made in 16.2 and not in master or older stable then?

What about canceled sale orders that have invoices or delivery orders linked? It looks like delivery orders (if any) are not removed from the database when unlinking the sale order

**Review by Feyensv — APPROVED** [review]

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
