### PR TITLE
[FIX] *: adapt front-end HTML field sanitization

### PR DESCRIPTION
**Pull request by bso-odoo**
*: account, event_booth, gamification, hr, project,
   website_event_track, website_slides

HTML fields that appear in the front-end can be modified using the
website editor. Some of them are sanitized in a way that breaks the
behavior of snippets that can be dropped within them.

This commit adapts the sanitization of those HTML fields so that the
snippets behave as expected.

opw-3267589

### CODE REVIEW

**Comment by bso-odoo** [comment]
@rdeodoo @qsm-odoo I had to rely on a whitelist in the detection mechanism because I could not find a way to tell whether those `t-field` were editable or not. Maybe that commit should be removed before merge anyway.
For the rest, I think it is ok, except an issue with the `hr.job` description for which I created another task (task-3289134).

**Comment by bso-odoo** [comment]
@rdeodoo The commit with the detection mechanism has been removed.
The handling of `sanitize_attributes=True` HTML fields as text fields is implemented in #120588.

**Review by rdeodoo — COMMENTED** [review]
@odony Hello, I am pinging you since we already discussed a bit this topic the other day and that this PR will need a security check.

As expected, with our growing user base, they start using all possible flows, ultimately finding and reporting more and more issues related to the website builder regarding "restricted" HTML fields.

My first idea was to create a `fields.HtmlFrontend` field that would have all the sanitize attributes set to what we usually set for full edition (sanitize_override=True, sanitize_forms=False, sanitize_attributes=False) but you preferred if we went case by case to add the missing one, like it's done in this PR, for security purpose.

The thing is, it's not just about "the carousel snippet won't work", it's also:
- You won't be able to use some options, even the main ones shown on all snippets like "Conditional visibility", you set it, you save, nothing works, you enter edit mode, your option setting is reset/gone -> Poor UX
- You will face JS traceback breaking your page forever without being able to enter edit mode again, like countdown snippet -> Terrible UX to say the least
- Probably other things to be discovered

As I said here https://github.com/odoo/odoo/pull/120588#pullrequestreview-1453570282
> Finally, this issue is quite critical UX wise since all those sanitize_attributes fields will poorly behaves in the website builder: it won't work if you are lucky, it will crash if you are unlucky, leaving your page broken, you can't even enter edit mode anymore.

If we don't want to add those `sanitize_attributes=False` & co on all HTML field being interfaced on the frontend, we might need to consider the problem another way: maybe keeping the security at maximum level (at cost of edition capability) and then make it so restricted users cannot edit sanitized fields at all :shrug: 

Note that we already made a few things to improve the UX of those restricted fields like:
- `sanitize_override` 
- `data-oe-sanitize` property on editabe nodes which will make it so the builder will prevent some snippets to be used: you can't drop the "Code" snippet in a `sanitize_attributes=True` HTML field and you can't drop the "Form" snippet in a `sanitize_form=True` HTML field, the system will warn (and prevent) you about it during the drag & drop:
image
- the editor team made sure their editor toolbar was sanitize compliant
- ongoing PR to turn `sanitize_attributes` fields into plain text only edition, see https://github.com/odoo/odoo/pull/120588#pullrequestreview-1453570282 but it's really not ideal and a last ressort fallback in the code
- ..

Sorry for the long writing but all of this just:
1. To be sure you still have the same opinion (don't create an util/short cut and probably don't add it everywhere)
2. To have your approval about adding those attributes on the "main" flows in this PR
3. Maybe you will have some inputs to give that we did not think about :shrug: 

cc @pierre-pde

**Review by rdeodoo — APPROVED** [review]
@robodoo r+
@odoo/rd-security Could you approve this one? See my previous message on the PR if needed.

Note that in master, those will be turned into plain text edition if the attributes are sanitized in the field. It will prevent all those traceback and non working snippets/options which user opens ticket all the time about it.

From there, team will add the missing `sanitize_attibutes=False` where needed, is judged needed.

This PR is already a first step adding the missing ones following a quick testing and client feedbacks.

**Review by rdeodoo — APPROVED** [review]
Edit: message was sent twice :thinking:

**Pull request closed without merging**
