### PR TITLE
[FIX] point_of_sale: prevent error when loading PoS in other currency

### PR DESCRIPTION
**Pull request by pedrambiria**
Before this commit, it wasn't possible to open a PoS in a different currency than the company currency.

opw-4378523

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by davidmonnom — COMMENTED** [review]
I'm not sure we should accept to open a PoS with 2 differents currency. isn't managed in the frontend.

What do you think @caburj

**Comment by davidmonnom** [comment]
Yep but in pos_store and other module we have getter `get currency` thats use `models['res.currency'].getFirst()` it can lead  at some error

**Comment by caburj** [comment]
We should prioritize the currency of the journal over the currency of the company. This has been the case.

**Review by caburj — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
