### PR TITLE
saas-12.3: correct issues of forward-port of 03/06

### PR DESCRIPTION
**Pull request by nle-odoo**
In 12.3 when lines are resequenced, the position of the current line
does not take into account that it could have been changed (because of
drag and dropping a line before or after).

opw-1966589

### CODE REVIEW

**Comment by KangOl** [comment]
@robodoo r+ p=0

**Comment by KangOl** [comment]
@robodoo rebase-ff

**Comment by KangOl** [comment]
@robodoo r-

**Comment by KangOl** [comment]
@robodoo rebase-ff r+ p=0

**Comment by KangOl** [comment]
@robodoo retry

**Comment by nle-odoo** [comment]
robodoo r+ p=0

**Comment by KangOl** [comment]
robodoo r+ p=0

**Comment by KangOl** [comment]
robodoo r+ p=0

**Comment by KangOl** [comment]
robodoo r+ p=0

**Pull request closed without merging**
