### PR TITLE
[FIX] Update company and language terms according count conditions

### PR DESCRIPTION
**Pull request by AurelienPillevesse**
Description of the issue/feature this PR addresses: Better wording according to count of languages and companies

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by AurelienPillevesse** [comment]
@mart-e Can you merge it in the master branch instead of the 13.0 ?
Thanks!

**Comment by mart-e** [comment]
@AurelienPillevesse you can do it yourself. You need to modify the target and reapply 33c042dd05e159001c5ce57781907c3062ba7881 on a master source (or create another branch if needed)

**Comment by AurelienPillevesse** [comment]
If I change branch to master, more than 700 commits will be merged...
First time i'm doing this on GitHub, not sure i'm doing it well.
@mart-e

**Comment by mart-e** [comment]
Ok, no worries, I will do it but to explain : 
- having two remotes `odoo` and `AurelienPillevesse`
- the commit you want to preserve is AurelienPillevesse/odoo@33c042dd05e159001c5ce57781907c3062ba7881
- `$ git checkout -b patch-4  AurelienPillevesse/patch-4`
- `$ git reset odoo/master --hard`
- `$ git cherry-pick 33c042dd05e159001c5ce57781907c3062ba7881`
- change the target branch 13.0 -> master
- `$ git push -f AurelienPillevesse patch-4`

**Comment by AurelienPillevesse** [comment]
Thanks, I'm doing it from the GitHub website and i'm pretty sure that I had some commands to execute. Not sure it's possible from here.
@mart-e

**Comment by mart-e** [comment]
No indeed, it is not possible from the github interface (in these cases, it is easier to just remake the PR in another branch).

@robodoo r+

**Pull request closed without merging**
