### PR TITLE
[FIX] base_gengo: private key password field

### PR DESCRIPTION
**Pull request by mgh-odoo**
Task:https://www.odoo.com/web#id=1892058&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720
Pad:https://pad.odoo.com/p/r.66df6a740488a010c60a4c43028c71ac

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
@alexkuhn shouldn't this be fixed by resolving the issue that brok  the password hiding itself instead of changing field types in a stable version? What if I have an inherit on this model and redefine the field while keeping the 'Text' definition? What happens then?

**Comment by alexkuhn** [comment]
@robodoo r-

**Comment by alexkuhn** [comment]
Correct, should be more careful with the fix.

**Pull request closed without merging**
