### PR TITLE
[9.0] add basque language

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Comment by anajuaristi** [comment]
:+1:

**Comment by oihane** [comment]
Already in v8.0 https://github.com/odoo/odoo/blob/8.0/openerp/tools/misc.py#L508

**Comment by agaldona** [comment]
GREAT! :+1:

**Comment by Daniel-CA** [comment]
:+1:

**Comment by mikelarre** [comment]
+1

**Comment by oihane** [comment]
@mart-e it is available in version 8.0 could you add also for version 9.0

**Comment by mart-e** [comment]
It will, we do forward port regularly of all the fixes of stables version into upper version. [No need to create multiple PR](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch)

**Pull request closed without merging**
