### PR TITLE
[FIX] test_mail: make test pass without demo data

### PR DESCRIPTION
**Pull request by seb-odoo**
runbot-70915

### CODE REVIEW

**Review by tsm-odoo — APPROVED** [review]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
You should instead update expected value (email_from, user names, ...) and use user_admin.name, user_admin.email_formatted, ...

**Comment by seb-odoo** [comment]
I don't like doing that generally speaking, as in the end the tests become less and less relevant.
It's eventually just becoming `assert(name, name)` which is pointless.

Now I know the goal of this test is not specifically to test what is the name of admin, but I prefer to keep some tests where we really see what is transiting in network (in terms of raw data, not variables/logical blocks).

So it's case by case but for me this is one of the few tests where I want to see the actual data.

**Comment by pedrobaeza** [comment]
I agree tests should assert fixed data, not the value of an expression. If not, you have the risk of performing a test that is programmatically mimicking the business code. Exceptions may be those where you compare with already stored records in the setup class (example: `self.assertEqual(result, self.partner)`.

**Comment by tde-banana-odoo** [comment]
I don't see how you could have issue in this test. I agree you have to fix critical data, but not demo data like partner name or email, which can completely be set as dynamic. It even allows to see which part is dynamic (user.email_formatted) and which part is static (res.partner as bus channel name).

Anyway as you prefer obviously, but I bet you also have to fix admin email then.

**Comment by tde-banana-odoo** [comment]
Then maybe set admin name at the same place ?

**Comment by tde-banana-odoo** [comment]
At least it will be consistent in all tests that way :)

**Comment by seb-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
