### PR TITLE
{sale,hr}_timesheet: improve timesheet analysis report

### PR DESCRIPTION
**Pull request by xavierbol**
## [IMP] sale_timesheet: consider timesheet as revenues if amount and quantity > 0

Before this commit, when the user made a timesheet with a negative
number set in unit_amount field (Time spent), the billable type of that
timesheet is timesheet revenues instead of a cost since we cancel some
hours/days spent to a timesheet validated for instance.

This commit makes sure the timesheets with negative time spent are not
considered as a revenue.

## [IMP] {hr,sale}_timesheet: allow to open the list in pivot/graph timesheets analysis report

Before this commit, when the user goes to Timesheets > Reporting, and
click on any menus inside Reporting then he will have access to pivot
and graph of Timesheets Analysis report but he cannot click on a cell
inside the pivot or a data displayed in the graph view to show the
records contained in the cell/data.

This commit allows to click on pivot cell and data in graph to show the
records in a list view. The list view is also defined to have a list
view with all the useful information instead of just having the default
list view with only the name field displayed.

## [IMP] {hr,sale}_timesheet: add form view for timesheet analysis report

Before this commit, the form view was the default one that is the one
displaying all the fields defined inside the report, also the list view
cannot avoid opening the form view when the user clicks on a row without
being editable and so if the list view is editable, the save and discard
buttons are displayed even if all fields are not editable.

This commit defined a form view to have the same render than one defined
for timesheets and makes sure the list view is not editable to allow to
open the form view.

task-4053021

### CODE REVIEW

**Review by pkyriakou — COMMENTED** [review]
Thank you @xavierbol for your work :top: LGTM :green_circle: :sunglasses: 
Make sure to add something to the PR message for future references :tipping_hand_man:

**Review by MissingNoShiny — APPROVED** [review]
LGTM, thanks!
@robodoo r+

**Comment by xavierbol** [comment]
robodoo rebase-ff

**Comment by xavierbol** [comment]
robodoo r+

**Pull request closed without merging**
