### PR TITLE
send_file => Stream + ir.binary

### PR DESCRIPTION
**Pull request by Julien00859**
**[IMP] website_sale_digital: use ir.binary to serve attachment**

We introduced `odoo.http.Stream` and its `ir.binary` companion model
to refactor all the "stream data over http" bits into a single unified
API. The API takes care of creating a cache-aware, proxy-accelerated,
headers-rich HTTP response out of any path, attachment or binary-field.

**[IMP] hw_drivers: use clever HTTP cache for logs**

`odoo.http.send_file` is deprecrated, `odoo.http.Stream` using the
`from_path` constructor is a drop-in replacement.

### CODE REVIEW

**Comment by Julien00859** [comment]
up @xmo-odoo (ci/security) I've changed open() => Stream.from_path(), should be as-risky as before. Also I wonder if I should retarget on 16.0?

**Comment by xmo-odoo** [comment]
@robodoo override=ci/security

**Comment by xmo-odoo** [comment]
You may want to check with @odoo/iot if the hw_drivers stuff is supposed to use matching APIs or if it's some sort of weirdo bespoke thing though.

**Comment by Julien00859** [comment]
@robodoo r+

**Comment by Julien00859** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
