### PR TITLE
[ADD] base: indroducing Australian states (Closes: #6402)

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by odony** [comment]
Looks good, thanks! Could you add the CLA signature to your PR, as explained in the details for the `legal/cla` failing test, please? See more details here: https://www.odoo.com/sign-cla
Thanks!

**Comment by onlyjob** [comment]
No, thanks. I'm not interested in signing CLA and I am not comfortable with the idea.
AGPL-3 should be enough and every contribution should comply with terms of the license.

Anyway my contribution is minor hence it is probably not even copyright-able as I'm not changing anything but merely adding data (information) that I do not own. Should be safe to merge even without CLA.

I don't care about pull request so it might be easier if you just commit it yourself. Cheers.

**Comment by mart-e** [comment]
As requested we have applied the diff and merged it at 68621de7dfa4a466dc162e54c68326ec14110726.
Thank you for the patch.

**Comment by onlyjob** [comment]
Thanks, @mart-e. :)

**Pull request closed without merging**
