### PR TITLE
[FIX] account_facturx: Fix facturx xml with discount, group of taxes and multi-currency

### PR DESCRIPTION
**Pull request by smetl**
Manual forwart-port of https://github.com/odoo/odoo/pull/53894

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@robodoo rebase-ff r+

**Comment by qdp-odoo** [comment]
@robodoo retry

**Comment by smetl** [comment]
@robodoo retry

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
