### PR TITLE
[[DONE]] [FIX] tests:  run chrome within containers

### LINKED ISSUE #26455: [ERROR] containered chrome tests (eg travis) not working
It seems that the chrome browser testing is not container compatible..

Output of `ps xaf` on host machine.
```
16624 ?        Sl     0:00  |   \_ docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/ba6c6e364a071b4c938e0451a04416c065a4b4ff9d629
16653 pts/0    Ssl+   0:20  |       \_ python3 /opt/odoo/odoo-bin --addons-path /opt/odoo/addons/090,/opt/odoo/addons/020,/opt/odoo/addons/0110,/opt/odoo/addons/010,/opt/odoo/addons/001,/opt/odoo/ad
17051 pts/0    Z+     0:00  |           \_ [chrome] <defunct>
17057 pts/0    Z+     0:00  |           \_ [cat] <defunct>
17058 pts/0    Z+     0:00  |           \_ [cat] <defunct>
17067 pts/0    Z+     0:00  |           \_ [chrome-sandbox] <defunct>
```

Output of `lsof -i TCP` within the container.
```
odoo@ba6c6e364a07:~/addons/090$ lsof -i TCP
COMMAND PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
python3   1 odoo   11u  IPv4 5463770      0t0  TCP ba6c6e364a07:57920->odoo-xoe_db-node_1.odoo-xoe_default:postgresql (ESTABLISHED)
python3   1 odoo   12u  IPv4 5466182      0t0  TCP *:8069 (LISTEN)
python3   1 odoo   13u  IPv4 5466602      0t0  TCP ba6c6e364a07:57924->odoo-xoe_db-node_1.odoo-xoe_default:postgresql (ESTABLISHED)
python3   1 odoo   14u  IPv4 5465691      0t0  TCP ba6c6e364a07:57938->odoo-xoe_db-node_1.odoo-xoe_default:postgresql (ESTABLISHED)
python3   1 odoo   16u  IPv4 5468387      0t0  TCP ba6c6e364a07:58442->odoo-xoe_wdb_1.odoo-xoe_default:19840 (ESTABLISHED)

```

### PR DESCRIPTION
**Pull request by blaggacao**
Closes #26455
Based on:
https://github.com/SeleniumHQ/docker-selenium/issues/520#issuecomment-384156465

**Description of the issue/feature this PR addresses:**
- Make chrome testing work in containers

**Current behavior before PR:**
- Port `8071` get's never bound (maybe because of not running as root)

**Desired behavior after PR is merged:**
- Port `8071` get's bound.

**Note:** Please merge as soon as convenient to fuel adoption of new chrome js testing in containered environments, such as travis, gitlab, etc.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@xoe-labs

### CODE REVIEW

**Comment by blaggacao** [comment]
@OCA/community-maintainers

**Comment by blaggacao** [comment]
@d-fence This is kind of blocking downstream adoption of the new chrome testing... It would be really nice if it could be validated and merged swiftly.
/cc @yelizariev

**Comment by mart-e** [comment]
I am no expert in docker nor chromeheadless but disabling the sandbox will need a better argument than "can't run in docker".

Moreover, check the config example they give in the documentation:

https://developers.google.com/web/updates/2017/04/headless-chrome

> How do I create a Docker container that runs Headless Chrome?
> ...
> Note: --no-sandbox is not needed if you properly setup a user in the container.

**Comment by Yajo** [comment]
@blaggacao can you test that solution to know if it's a proper fix?

**Comment by yelizariev** [comment]
@blaggacao from @mart-e's link they suggest following:


```
# Add a chrome user and setup home dir.
RUN groupadd --system chrome && \
    useradd --system --create-home --gid chrome --groups audio,video chrome && \
    mkdir --parents /home/chrome/reports && \
    chown --recursive chrome:chrome /home/chrome
```

**Comment by blaggacao** [comment]
Will check that alternative shortly. `--no-sandbox` worked, but let's do it the recommended way. Thanks!

**Comment by blaggacao** [comment]
@mart-e @yelizariev I tried your idea and it seems to require the calling process to run as that `chrome` user, which is somewhat obscure and not documented.
A more approriate way probably would be to run a headless chrome as a service to connect to, which would overthrow part of the design of the original commit.

@mart-e  What is preferable? Leaving Travis/Gitlab-CI/Circle-CI users without browser testing is not a _real_ option...

**Comment by blaggacao** [comment]
> A more approriate way probably would be to run a headless chrome as a service to connect to, which would overthrow part of the design of the original commit.

I think that's the "canonical" solution. @d-fence ?

**Comment by blaggacao** [comment]
Summoning OCA's MQT maintainers...

@dreispt @guewen @gurneyalex @jgrandguillaume @sebastienbeau @StefanRijnhart

While not tested on travis, being based on docker, I assume chrome testing, as it's implemented, won't work in travis neither. - Any idea what to do?

**Comment by blaggacao** [comment]
@nhomar I guess that's something for Ruiz's eyes, too.

**Comment by Yajo** [comment]
> I tried your idea and it seems to require the calling process to run as that chrome user, which is somewhat obscure and not documented.

I think the name of the user doesn't matter. The main point is running the process with a user that has the correct permissions (a.k.a. groups audio & video probably) and has a proper `$HOME` in place with a `reports` subfolder.

Usually odoo requires (or recommends, since v8) running it with a non-root user, so downstream Dockerfiles usually already create such user. My bet is that giving that user those groups, you'll get it running. Have you tried that? Do we have any place to review your Dockerfile?

**Comment by blaggacao** [comment]
@Yajo I'll try again. But I'm skeptical. From https://github.com/odoo/odoo/issues/26455 you can understand the problem: it doesn't bind to a network interface.

No line of thought occurs to me which connects `audio`, `video` groups to the network stack.

This is `Dockerfile`'s current state: https://github.com/xoe-labs/dockery-odoo/blob/master/images/base/v-master/Dockerfile ... meanwhil I [make it work](https://github.com/xoe-labs/odoo-dev/tree/master-fix-chrome-in-container-environment).

**Pull request closed without merging**
