### PR TITLE
Correct werkzeug version.

### PR DESCRIPTION
**Pull request by nhomar**
https://github.com/odoo/odoo/issues/18052#issuecomment-364701939

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e can you check please?

**Comment by Elkasitu** [comment]
Why though? The fix for this particular bug in werkzeug is in every werkzeug version from 0.11 to 0.14 https://github.com/pallets/werkzeug/commit/6dd142d83579a876d964387964e6bf6ae2f21a2f

**Comment by nhomar** [comment]
hello @Elkasitu 

with the current version on the requirements.txt the link_track module can not recognize the original IP address ever (real case into production), and the reason was that the click was recognizing always all with the same IP.

On my side it was fixed only updating werkzeug.

regards.

**Comment by mreficent** [comment]
cc: @d-fence

**Comment by d-fence** [comment]
werkzeug is a core part of Odoo, so we prefer to not change its version in a stable branch.
Also, we try to stick to the Debian packages version (when possible), so changing the requirements could potentially break the packaging.
If one wants to use a newer version of werkzeug, it's still possible to use pip with or without a virtualenv.
I hope that I will not hurt someone but I prefer to close this PR. werkzeug will be updated later.
Thanks for your comprehension.

**Comment by nhomar** [comment]
@d-fence Are you kidding me?.

Did you read the comment? you actually have it changed into odoo.sh and the saas....

Honestly sometimes I think this is intentionally done, our time is not considered as valuable men.

If you are facing problems with the current version, that is better to mention than simply say **stable**. :-s

**Comment by Yenthe666** [comment]
@nhomar don't take it personal, sometimes suggestions/ideas fail, sometimes they don't. I guess we have to keep 'trying' to get things improved but in the end it is not our product so its not really our decision.
Nevertheless, @d-fence, do you really think we can't let it land in 11.0? Have you atleast tried the newest version of `Workzeug` on the latest 11.0 to see what it gives?

**Comment by nhomar** [comment]
>> @nhomar don't take it personal, sometimes suggestions/ideas fail, sometimes they don't. I guess we have to keep 'trying' to get things improved but in the end it is not our product so its not really our decision.
>> Nevertheless, @d-fence, do you really think we can't let it land in 11.0? Have you atleast tried the newest version of Workzeug on the latest 11.0 to see what it gives?

Agreed with your position (it is the same way I think) sorry for my hard words, but the point is that sometimes answers and situations appear like the only time is valuable here is Odoo's team time, they have technically the version I am proposing in odoo.sh and into saas, then on-premise instances left with old version which bring problems.

May be I am wrong and the real reason is a little doc instead the PR, but what's the point of left the installer with notable out-dated elements instead maintain all up-to-date? what's the point of have different proposed environments that make debugging process really complex?.

That's against any good practice and left us as team (odoo and community) very bad in front of proper sysadmins, because IMHO that's unacceptable the same version of a software being tested and used on different environments by definition.

But BTW, as you say... their product their decision... I fixed on my environment and that's it.

**Pull request closed without merging**
