### PR TITLE
[FIX] account: optimize reconciliation query

### PR DESCRIPTION
**Pull request by AdrienHorgnies**
This is a duplicate of https://github.com/odoo/odoo/pull/61056 and will take precedence. It must be fw port up to 14.0 excluded.

The expression
```sql
(CASE WHEN
    condition_1
 THEN (CASE WHEN
    condition_2
THEN 1 END) END) = 1
```
enforces that `condition_1` is evaluated before `condition_2` and is strictly equivalent to `condition_1 AND condition_2`.

It enables me to make the query to evaluate the most advantageous filter earlier.

opw-2362288

Description of the issue/feature this PR addresses:
Slow reconciliation, see opw-2362288

Current behavior before PR:
Slow
7 minutes, tested with ~600k aml and ~150 bank statement lines and reconciliation start date 3 months in the past.

Desired behavior after PR is merged:
Blazing fast
8 seconds, tested with ~600k aml and ~150 bank statement lines and reconciliation start date 3 months in the past.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by william-andre** [comment]
Here is the plan before https://explain.dalibo.com/plan/IUA and after https://explain.dalibo.com/plan/f1h

You told me it had to do with the filter on `account_bank_reconciliation_start`, but in both cases that condition is evaluated at the very last step.

The difference is that before, all the `regexp_split_to_array(substring(REGEXP_REPLACE()))` were done earlier, thus filtering some rows earlier.

On my tests (simply a db with demo data in 12.0), the old query had compute that complicated filter on 24 lines, where it had to be computed on 51 rows in your version. So if there is no `account_bank_reconciliation_start`, it will actually be twice as bad as before.

I think this needs further testing on a big database without the parameter set.

**Comment by AdrienHorgnies** [comment]
@william-andre Indeed my explanation wasn't accurate. This isn't about `account_bank_reconciliation_start` but about the regex conditions. These conditions are slow to evaluate and the later we can evaluate them, the better. I tested on a client database with the following values:
- `account_bank_reconciliation_start` not set
- More than 600 000 rows of `account_move_line`
- About 150 rows of `account_bank_statement_line`

The query took about 7 minutes on the branch **13.0** and 10 seconds on the branch **13.0-fix-account-slow-reconciliation-aho**. Note that I tested on these versions because that's the version the database I'm working on is in but as you could see, the fix is strictly equivalent.

As I understand, there will always be more `account_move_line` records than `account_bank_statement_line` records. Thus, it's always better to filter rows of `account_move_line` first.

**Review by william-andre — APPROVED** [review]
It should indeed be better in virtually all the cases than what we have now

**Comment by AdrienHorgnies** [comment]
@smetl What do you think ?

**Comment by gurneyalex** [comment]
hello this looks nice. On which PostgreSQL version(s) did you test it? Did you get a chance to discuss this with the postgresql maintainers?

**Comment by william-andre** [comment]
The PostgreSQL version I test with is 12.4, but I don't see why we should bother the maintainers. The `EXPLAIN ANALYSE` speak for itself and is quite logical.

It could be an improvement to try and do the logic with some kind of priority related to the weight of the execution of filters, but that is a NP problem in general.
What we did here was give some insight to the query planner based on our knowledge, but it can't deduce it by itself.

Am I missing something?

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
