### PR TITLE
[REM] crm,sale_crm: remove dead fields

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
* These fields no longer use anywhere, it belongs to old feature from a long time ago, it should be delete in
https://github.com/odoo/odoo/commit/877711b357c5de9c9c4827e92fdbbc94cae673fe

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Hello @tde-banana-odoo can you confirm these fields is really dead ? because i can't find it anywhere in CE or EE, then i found your commit so i assum it really dead and useless fields

**Review by reth-odoo — APPROVED** [review]
Seems last (dead code) uses were removed by bfda483d21a035d20711e6d5916dab9df76546a6 and 3e39dcba5289bcaae28788a77254d65b4eb9c56c

(needs an upgrade script though)

**Comment by duong77476-viindoo** [comment]
> Seems last (dead code) uses were removed by [bfda483](https://github.com/odoo/odoo/commit/bfda483d21a035d20711e6d5916dab9df76546a6) and [3e39dcb](https://github.com/odoo/odoo/commit/3e39dcba5289bcaae28788a77254d65b4eb9c56c)
> 
> (needs an upgrade script though)

Unfortunately , i don't have access to upgrade repo :(

**Comment by reth-odoo** [comment]
@duong77476-viindoo yes I know, I'll cherry-pick your commit into a branch on our repo and add an upgrade script, will keep you up to date :)

**Comment by duong77476-viindoo** [comment]
@reth-odoo Nice thank you sir

**Comment by reth-odoo** [comment]
^ moved to the mention above, thanks :)

**Pull request closed without merging**
