### PR TITLE
fleet : small fixes/improvements

### PR DESCRIPTION
**Pull request by alt-odoo**
Description of the issue/feature this PR addresses:

 [FIX] fleet: correct cost date on recurring costs creation

When creating the recurring costs through the cron task, we should set the date
accordingly with the specified recurrence instead of setting it to today.

--------------------------------------------------------------------------------------------------------

 [FIX] fleet: set correct contract on activation cost line creation

When creating a vehicle contract, we are creating automatically a cost line
corresponding to the activation costs. The contract was not correctly set
on that line before this commit.

--------------------------------------------------------------------------------------------------------

 [FIX] fleet: prevent deletion of vehicle contract

When we create a contract information on a vehicle, there is an activation cost
automatically created. Before this fix, if we delete the activation cost line, it
deletes automatically the associated contract. We should prevent this and add a
warning message instead.

To make it easier for the user, we should also show the contract information on
the list and form views of the vehicule cost.

When deleting the vehicle contract, we should also automatically delete the
activation cost line associated.

--------------------------------------------------------------------------------------------------------

opw-2534547

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by simongoffin** [comment]
robodoo delegate+

**Review by simongoffin — APPROVED** [review]

**Comment by alt-odoo** [comment]
@robodoo r+

**Comment by alt-odoo** [comment]
@robodoo rebase-ff r+

**Comment by alt-odoo** [comment]
@robodoo rebase-ff

**Comment by alt-odoo** [comment]
@simongoffin 
Need your delegate power for rebase too, sorry ^^

**Comment by simongoffin** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
