### PR TITLE
[Fix] to allow Odoo to work on Postgres Version 15.0 and above

### PR DESCRIPTION
**Pull request by kwasi-dev**
**Description of the issue/feature this PR addresses:**

From PostgreSQL's point of view, as of version 15.0 and above the default behavior is to constrain ordinary users to user-private schemas.  For every user needing to create non-temporary objects, it's advised that they create a schema with the same name as that user (Recall that the default search path starts with $user, which resolves to the user name. Therefore, if each user has a separate schema, they access their own schemas by default.) This pattern is a secure schema usage pattern.

See Section 5.9.6 https://www.postgresql.org/docs/current/ddl-schemas.html
and 
https://www.postgresql.org/docs/release/15.0/

Databases migrated from previous versions of postgresql will have the default public schema writable, but new odoo instances on postgresql version 15 and above do not work. To fix this We'd create a new schema in the database that's the same name as our database user after we create our empty database

**Current behavior before PR:**

Initializing a new Odoo database on Postgres version 15.0 and above with a user with only the LOGIN and CREATE DATABASE roles would result in an error 
`permission denied for schema public`

Because of this, no database tables are created on new databases using postgres V15.0 and above

Desired behavior after PR is merged:
Full functionality is restored by creating all tables in a schema that matches the database user

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by virenderscideas** [comment]
I got the same issue but I get success to install it on window machine. This error basically related with postgreSQL table creation due to permission issue.

Enviroment
Python **3.11.5**
pip **23.2.1**

odoo branch 16.0 with last commit
_commit 5e7cb75ae975d5fb201a787d3a47b0ebb97da944 (HEAD -> 16.0, origin/HEAD, origin/16.0)_

Here are the steps which I did on **PostgreSQL 16**

Create a user with any name I choose **odoo** (below screenshot are taken on **pgAdmin 4**)

Screenshot 2023-09-17 020655

Then create a db with any name in postgreSQL I choose **odoo**

after that  in db property under security tab given these following permission to **odoo** user.

Screenshot 2023-09-17 020901


and under ***Default Privileges*** tab set these permission

Screenshot 2023-09-17 021206

DB listing through psql

image

and then started odoo server through this

I performed all below command on CMD with administrator privileges 

```bash
>python odoo-bin -r odoo -w admin --addons-path=addons -d odoo
```
it will start installing tables and table sequences, if you get any error during this process then try to execute this

```bash
>python odoo-bin -i base -r odoo -w admin --addons-path=addons -d odoo
```

**Comment by kwasi-dev** [comment]
Thank you very much for that workaround. While that is a valid solution, that is not scalable.

For businesses out there that use the dbfilter option that checks for a client's hostname (%h). If they were to upgrade their PostgreSQL to version 15, it would break the signing up of new users on their platform because someone would have to manually go and adjust the permissions for the database user for the newly created database.

**Review by xmo-odoo — CHANGES_REQUESTED** [review]
How comes the author of the original commit is @sundaebytes but the CLA is an individual CLA for a seemingly unrelated individual?

Also the cla file needs to have a `.md` extension.

Finally I think I'd rather this be done in master for now so we can kick the tyres, and then backport it to older versions. Either that or merge it directly in older versions so *they* can be deployed properly on e.g. debian bookworm (which apparently ships pg15), but I'd rather we merge in master for now.

**Comment by kwasi-dev** [comment]
I've refactored the code based on the comments that @xmo-odoo left.

**Pull request closed without merging**
