### PR TITLE
Fix: Use provided partner_id in crm_lead_to_opportunity wizard and conne...

### LINKED ISSUE #2821: Existing partner_id not taken into account when converting a lead to an opportunity.
When converting a crm.lead into an opportunity, you can use an existing res.partner to connect with the opportunity. This happens in the crm/wizard/crm_lead_to_opportunity.
But during conversion, the partner_id is not taken into account.

What works however is that you add the res.partner to the crm.lead before converting and convert then.

### PR DESCRIPTION
**Pull request by wamdam**
...ct the opportunity to a partner. Fixes #2821

### CODE REVIEW

**Comment by wamdam** [comment]
Any news on this? This is a rather simple bugfix.

**Comment by JKE-be** [comment]
Hello,
Could you accept CLA please and apply this patch with a updated version of Odoo to get your branch green.

Thank you

**Comment by wamdam** [comment]
Thanks, I'll accept the CLA soon. However, I see (git blame) this bug is fixed in

commit 65de6e7f27344be275c5372a4dd76fa4396a2a9d
Author: Denis Ledoux <dle@odoo.com>
Date:   Thu Jan 15 16:08:26 2015 +0100

    [FIX] crm: convert to opp, link to an existing cstomer
    
    When converting a lead to an opportunity, and choosing the option "link to an existing customer", the resulting opp wasn't actually linked to the ccustomer.

So please close this pull request.

**Comment by JKE-be** [comment]
Ok, I close this one ! 
Thank you for your contribution...

**Pull request closed without merging**
