### PR TITLE
[FIX] mail: fix messaging locale update on translation bundle change

### PR DESCRIPTION
**Pull request by seb-odoo**

### CODE REVIEW

**Comment by alexkuhn** [comment]
Just a though with this change, which I'm not sure it does: could be possible that `set_bundle` is called during a test and therefore changes direction inadvertently? Don't think it happens in practice, but it doesn't look like designed to avoid this issue, so just wanted to share this potential consideration.

**Comment by seb-odoo** [comment]
It could be possible some day but this whole thing is totally not used in the tests currently. No way to test the interface from another language than the one of the current webclient, though it's possible to mock fake values into session as seen on PR from DID.

**Comment by seb-odoo** [comment]
@robodoo r-
What is possible though is that the RPC from the webclient will come after tests have started, due to how bad we handle the env currently (overwriting it on Component), it might write the value on the test env instead of the other one...

**Comment by seb-odoo** [comment]
@robodoo r+
ok this is fine, after verification tests are never started before `session.is_bound`, which is waiting on `load_modules` through `session_init`

**Pull request closed without merging**
