### PR TITLE
[FIX] stock_account,sale_mrp,sale_stock: consider consu kit for COGS

### PR DESCRIPTION
**Pull request by adwid**
Suppose a consumable product that has a kit BoM. Since we have:
https://github.com/odoo/odoo/blob/65a3ffb12429e30ef911a981809b0f050f9c924d/addons/stock_account/models/account_move.py#L101-L103
The line will be ignored. However, one of the component could be a
storable product. In such a case, the line should not be skipped.

### CODE REVIEW

**Comment by adwid** [comment]
@svs-odoo Here it is (enfin!)
Still agree with the fix ?

**Comment by svs-odoo** [comment]
Hello @adwid
I'm not really comfortable with this fix. I think it makes sense, but it changes the sale invoice behavior and since there is no clients requests for this change (as far as I know, no open tickets about this case), I'm afraid we could change something nobody complaints about it.

Maybe it could be better to merge it for master only, we will talk to our PO (coucou @mathieu-mgm ) before to decide anything.
Thank you

**Comment by adwid** [comment]
@svs-odoo 
> as far as I know, no open tickets about this case

You're right, this issue has been discovered while fixing another problem.
In fact, you had created the first version of `_eligible_for_cogs` for another PR (because tests failed https://github.com/odoo/odoo/pull/66943#issuecomment-787738110), then Rémy and I had improved it. In the meantime, the PR had to be cancelled (the problem has been solved with another fix). But since the commit was already ready, we thought we could maybe suggest it directly, without a specific link to a ticket.
Let's see what Mathieu thinks about it, but I understand your point of view

cc @ryv-odoo

**Comment by adwid** [comment]
@svs-odoo @mathieu-mgm Actually, an issue already exists about this: #60679

**Comment by AaronHForgeFlow** [comment]
If this fix is applied the stock valuation will be applied for the kit product not the components. Should it be better to do the same thing but applied to the components? that way we could reconcile the interim accounts.

For example, in the customer invoice currently I get no journal items for stock valuation.

For the delivery order I have this thing:

```
Account                 Product              Debit         Credit
Inventory               Component                             X
Stock Output            Component              X
```

This solution here will create the following entries:

```
Account                        Product              Debit         Credit
Stock Output                  Kit product                            X
COGS                         kit Product             X
```

Then, COGS is hit and the interim account is balanced. But the product is not the good one in my opinion. Does anyone here agree with this?

**Comment by MiquelRForgeFlow** [comment]
Well, at least they could merge the hook part and let the people be able to customize in custom modules.

**Comment by MiquelRForgeFlow** [comment]
@adwid @svs-odoo I made a PR just for the hook https://github.com/odoo/odoo/pull/70418 hoping to get it merged soon.

**Pull request closed without merging**
