### PR TITLE
[IMP] point_of_sale,*pos*: minimize loaded assets

### PR DESCRIPTION
**Pull request by caburj**
Prior to this commit, we load every asset added in the
`web.assets_backend` and every template added in `web.assets_qweb`,
which results to loading of many unused js modules when starting
the pos ui. These unused modules include those coming from the
`mail` and other addons.

This commit introduces the following asset bundles:
* `point_of_sale.required_assets` - It contains modules from the
  required addons (web, barcode, etc). In this bundle, we
  manually select the modules that are needed by the pos ui.
* `point_of_sale.assets_qweb` - It contains the owl qweb templates.
  This replaces our old use of `web.assets_qweb`. Doing this, we
  are now only loading pos ui's templates.
* `point_of_sale.required_style_assets` - It contains the style
  sheets that come from the required addons.
* `point_of_sale.entry` - It contains the pos modules needed at the
  startup of the pos ui.

As a consequence, the following asset bundles are not needed anymore:
* `point_of_sale.assets_common` - This is practically replaced by
  the new asset bundle: `point_of_sale.required_assets`.
* `point_of_sale.assets_backend_prod_only` - This is renamed to
  `point_of_sale.entry`.

You can check the comparison of loading information before and after
this commit in the following spreadsheet:

https://docs.google.com/spreadsheets/d/1oFoLGXyGQrt9sDRmnA0JLUqJnNgwIFKoSMZ_IcQ1hYI/edit?usp=sharing

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
> Any idea why debug mode is faster than non debug mode? :o
To be honest, that's what I want to ask your team. I'm also puzzled.

**Comment by caburj** [comment]
@sdegueldre The result started to make sense for successive refresh (when the assets are cached). Maybe at the very first loading of assets, there is some parsing cost? I really don't know.

**Review by trj-odoo — APPROVED** [review]
lgtm, don't forget to rebase your branch resolve the conflict since pos coupon and gift card have been merged to loyalty

**Comment by caburj** [comment]
@pimodoo This is ready for review.

**Comment by brboi** [comment]
inactive pr

**Pull request closed without merging**
