### PR TITLE
[REF] doc: added doc for static templates inheritance

### PR DESCRIPTION
**Pull request by Arcasias**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
@robodoo are you high?
cc @xmo-odoo @d-fence

**Comment by xmo-odoo** [comment]
@aab-odoo apparently github had failed to deliver the branch change information (said it was a request timeout which I'm reasonably certain is a lie), so mergebot wasn't aware of the branch update, and so the last thing it had been told was that the PR had 2718 commits. Hence the reaction.

I forced a redeliver of the webhook, should be fine now.

**Comment by aab-odoo** [comment]
Thanks @xmo-odoo

**Comment by aab-odoo** [comment]
robodoo retry

**Pull request closed without merging**
