### PR TITLE
[FIX] Improve flexibility for inheritance

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
This PR allows to add other args into the rendered values in order to use them into the qweb.
Also use a method to compute all jobs because the entire jobs can be usefull a second time into an override.

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
OPW 665968

**Comment by mart-e** [comment]
Closing as not a bug but an improvement which should not target [a stable branch](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean)

**Comment by JonathanNEMRY** [comment]
I don't think the restriction was so "restrictive" at the beginning of this PR :smile: 
Despite this point of view if you think that this is not a technical bug then give me a solution to restrict the list of the jobs without copy/pasting the `jobs` method?

Thank you in advance!
-jne

**Comment by mart-e** [comment]
Well we have never very enthusiast to merge "hook" methods, especially in old versions. The difference is that we used to leave the requests open with no action but now I am trying to clean the hundreds of open ones and that requires a strict approach...

It is always tricky because we will always find somebody with a slightly different use case and don't want to end up with tons of 3 lines methods and spaghetti code.

Could you work with security rules targeting public user to restrict the jobs?

**Pull request closed without merging**
