### PR TITLE
[FIX] base: h tag separator for pdf printing

### PR DESCRIPTION
**Pull request by kebeclibre**
Before this commit, it was mandatory to have one and only one h tag
in a qweb report template.
wkhtmltopdf uses those to create Destinations (elements of a Table of Contents)
which in turn are used to split the pdf into its parts
-- when printing a many invoices in batch, all invoices are made with a signle wkhtml instance
and then split to form the attachments --

After this commit, the same system is used, of course, but many h tags is supported, as well as no h tag at all

OPW 804685

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
@kebeclibre This logic implies to define css classes to mock each `<hx/>` to your `<span class="o_mock-hx"/>`. Furthermore, it raises a traceback on runbot.

Why don't you consider the option we talked about?

**Comment by smetl** [comment]
Something like : https://github.com/odoo/odoo/compare/11.0...odoo-dev:11.0-opw804685-las

**Comment by kebeclibre** [comment]
@smetl 
indeed, my fix misses the class o_resid-breaker in the template and/or a condition not to add the h1
Your solution is incomplete (there will be multiple h in the tree, and thus assignation to the relevant attachment will fail)
Also, as discussed, if there is a h tag somewhere lower in the document, at the nth page of a single invoice, the break will occur anyway, leading to a wrong attachment assignation

@nim-odoo is not too enthusiast to make the change in stable anyway...

**Comment by smetl** [comment]
@kebeclibre Indeed, my solution doesn't work if you put some `<h/>` in the header/footer or inside the  invoice lines that doesn't make sense for me. But it doesn't need additional CSS to work. So you should consider the way I suggest for stable branches and, in a second step, apply a more complete solution, like yours, for master. What do you think?

**Pull request closed without merging**
