### PR TITLE
[FIX] web: color of tooltip arrow

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Prior to this commit, the color of the tooltip arrow didn't match the popover background when it was a tooltip (white arrow and black popover content).

However, the css adaptation was already present in `tooltip.scss` using the css variable `--popover-arrow-color`, but the selector wasn't correct since the arrow was always BEFORE the content.

This commit fixes the issue by placing the arrow after the popover content.

task-3329927
Part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
@stefanorigano 👋 This PR is ready for review.

**Comment by Brieuc-brd** [comment]
@stefanorigano 👋 rebased on saas-16.3, ready for review 👍

**Review by stefanorigano — APPROVED** [review]
Thanks @Brieuc-brd 👍 

@pparidans ready for tech. review, thanks!

**Review by pparidans — APPROVED** [review]
LGTM
@robodoo r+

**Pull request closed without merging**
