### PR TITLE
[FIX] mail : Hide feedback when activity has calendar event

### PR DESCRIPTION
**Pull request by yoba-odoo**
**Steps to reproduce:**
	1- Create an activity of the Meeting type.
	2- Set it in the calendar.
	3- Go back to the record.
	4- Mark the activity as done and add a feedback.
	5- The feedback appears duplicated.

**Current behavior before PR:**
Feedback is shown twice when the activity has a related calendar event. This happens because in calendar we add the feedback one more time as a description.
https://github.com/odoo/odoo/blob/15.0/addons/calendar/models/mail_activity.py#L32:L38

**Desired behavior after PR is merged:**
One of the feedback is not shown if the activity
has calendar event linked to it.

**Other solutions:**
To delete the override of the '_action_done()' in calendar module so the feedback is not added on emore time as description.

opw-3764648

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

I would prefer to change the python code and only have one feedback (either on the event, or on the activity) but maybe I am missing something functionally  about why the current code is like this

**Comment by tde-banana-odoo** [comment]
calendar_event_id does not exists in base mail, does it ?

**Comment by yoba-odoo** [comment]
@tde-banana-odoo Thank you for this observation. I will check it again and get back with another fix.

**Comment by yoba-odoo** [comment]
Solved by this PR: https://github.com/odoo/odoo/pull/147898

**Pull request closed without merging**
