### PR TITLE
[11.0-account][FIX] in multicompany, report layout should take user's company

### PR DESCRIPTION
**Pull request by cvinh**
Steps to reproduce:
In multicompany environment (let's say company A and company B), set up 'company_share_partner' to True
Setup a partner with company A. The company_id field is then set up to company A
Switch to company B and print an overdue report for this partner
Current behavior:
The external Layout (logo, header and footer) is taken from company A and the account move lines are taken from company B

Expected behavior:
The external Layout should be taken from company B because the user is trying to print the overdue for company B and data in the report are from company B

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The patch is incorrect, as `company_id` in the object should have more priority. The question is that the value is False, then you should go to user's company.

**Comment by cvinh** [comment]
@pedrobaeza thank for your comment.
We have a use case that make us think like that. I described it in the issue

**Comment by pedrobaeza** [comment]
What the use case in mind, my assert is still valid.

**Comment by cvinh** [comment]
I updated the steps to reproduce above for more details on the use case. I don't get your point of view because we have a mixing of data coming from company B and external layout (logo, header and footer) coming from company A

**Comment by pedrobaeza** [comment]
I mean:
```
        <t t-if="o and 'company_id' in o">
            <t t-set="company" t-value="o.company_id.sudo()"/>
            <t t-if="not company">
              <t t-set="company" t-value="user.company_id.sudo()"/>
            </t>
        </t>
        <t t-if="not o or not 'company_id' in o">
            <t t-set="company" t-value="res_company"/>
        </t>
```

**Comment by cvinh** [comment]
Thank you for the suggestion but it does not solve our use case : Account Overdue Report is printed from res_partner so o.company_id is defined.
I try to go further : 
- I understand that in many objects, company_id field is not mandatory, the code tries to manage that.
- I don't see the case where the user do not have any company (required=True)
- I don't see the case where a physical user that belongs to company A works on a object that belongs to company B. So the reports that are printed by a physical user are always for user.company_id
- I can imagine that when the admin user or odoobot user prints reports (I mean automatically because admin is not supposed to be used for in multicompany), there would be some problems.

So for v11, I would suggest that code 
```
        <t t-if="user.company_id and not user.id == 1">
            <t t-set="company" t-value="user.company_id"/>"
        </t>
        <t t-if="not company">
            <t t-if="o and 'company_id' in o">
                <t t-set="company" t-value="o.company_id.sudo()"/>
            </t>
            <t t-if="not o or not 'company_id' in o">
                <t t-set="company" t-value="res_company"/>
            </t>
        </t>
```

@pedrobaeza with all my respect because you are 99,999% always right, could you review our use case  once more ?

**Comment by gdgellatly** [comment]
@cvinh I think you are missing @pedrobaeza which is basically the same as yours.

Take your res_partner example. If there is a company assigned, then it only makes sense to print it for the company with moves, maybe. If there is no company, then the company of the user, maybe.

But actually I think it is more complex than that, I'm not even sure filtering on company is desirable. It is more of a functional question, "Should the overdue report show total exposure across the group for multicompany users/partners?" And if so, is it not the case that then the overdue report requires grouping by company? And if so is it a grouping at the first or second level in the case multiple partners selected.

**Comment by gdgellatly** [comment]
Oops I got that wrong. But you can't change the report like this. A counter example would be printing an invoice. You can't send that with the users company, it must be the objects.

**Comment by cvinh** [comment]
@gdgellatly thanks for joining us :+1: 
Even if the counter does not belong to the company, he has a res_user and a res_user.company_id (required = True) and it is the res_company where he works in indeed
The res_user.company_id is related to res_company not to res_partner
I'm not talking about res_partner.parent_id but res_user.company_id
That's why I'm saying that we could take user.company_id to get the external_layout and internal_layout in all reports that come out from odoo
Do you see what I mean
BTW our use case is real... please test it in runbot or somewhere

**Comment by cvinh** [comment]
there is no overdue report in v12 EE...

**Comment by gdgellatly** [comment]
@cvinh You must take the objects company_id if it is set. In your particular case it is wrong, I accept that, but in every other case it is absolutely the correct thing to do. To expand my example.

User is logged into company A, and is printing invoices of **child** company B. In your PR, the invoice will come from company A which is clearly wrong. Company B is the legal entity invoicing.

This PR would break Sales Orders, Purchase Orders, Invoices, POS, Expenses, Events, Maintenance, CRM, Projects, Inventory, HR. And that is just in standard. It is a really bad idea.

**Comment by cvinh** [comment]
Thank you, I'm gonna overwrite the report, I guess that's a better idea :-)

**Comment by pedrobaeza** [comment]
The error IMO is to set a company in the created partners if you have a shared contact address book. Then, my proposed patch would apply correctly.

**Comment by lathama** [comment]
@cvinh knowing that 11 is no longer updated, is this PR still needed?

**Pull request closed without merging**
