### PR TITLE
[FIX] event: google calendar link ok timezone


### PR DESCRIPTION
**Pull request by nle-odoo**
In the change 6ba81c99 there was an issue with timezone with Google
because we were now sending "20201217T123000+0000" instead of
"20201217T123124Z".

When google received formatted date ending in Z it would treat it as
UTC, but with +0000 ending he treats it as a locale time thus get it
wrong if locale timezone is different than UTC.

opw-2370895

### CODE REVIEW

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by pedrobaeza** [comment]
I would beg you when you do this kind of changes in templates that affect source term in translations, to propagate the changes to all translations, as if not, we lose whole translation in the next update. Example:

https://github.com/odoo/odoo/commit/703d46c651fbe7fd9ee855d7f56e46370cd423fa#diff-8261ccdec713f591ebccd57cf4e5da31628d0acf544068f28e9ed1a866611777L438

Thanks

**Comment by pedrobaeza** [comment]
@mart-e maybe you can have a script for this?

**Comment by nle-odoo** [comment]
Hi @pedrobaeza 


The data is in `noupdate` so for new installation on the module, we could lose the translation until it is copied in transifex. Usually we try to avoid change like this but here it was in noupdate section and the two links were erroneous..

**Comment by pedrobaeza** [comment]
I'm afraid you haven't understood me. I'm talking from the role of translator.

You have modified a very big Jinja mail template with something that is "code", but you haven't propagated this code change to all existing translations. Result: all the translations get erased and we have to retranslate the big string again. Now you get me?

**Comment by mart-e** [comment]
> @mart-e maybe you can have a script for this?

I don't because it's still manual but what needs to be done is quite short

```
$ tx pull -r "odoo-13.event" -f
$ sed ... # change all the po files
$ tx push -r "odoo-13.event"
```
The last command needs to be done by a translation manager on Transifex (so you could imagine to do it by a bot) but the second command is a bit hard to automate because a case by case situation. So not sure what we could do with this...

**Pull request closed without merging**
