### PR TITLE
[17.0][FIX] Portal Chatter: Attachment issue

### PR DESCRIPTION
**Pull request by vivekpabari1894**
Description of the issue/feature this PR addresses:
Prior to this commit, when we attach any attachment from project sharing attachment it was giving error

Current behavior before PR:
Prior to this commit, when we attach any attachment from project sharing attachment it was giving error

Desired behavior after PR is merged:
User can attach the attachment from the Project sharing view

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by reth-odoo — COMMENTED** [review]
Hello @vivekpabari1894 , thanks for your contribution

Can you explain a bit more of why we need to change all these, technically speaking?
And fixup/squash your commits (except CLA)

If you can spare the time to write a test that would be great too

**Comment by vivekpabari1894** [comment]
Here if you see that first of all in the JS it finding the "ufile" from the params. However, from where the method is called its sending the "file" in the params. 
Also on the backend the /portal/attachment/add controller it requires file as parameter so for that I need to update the JS and its relavent test cases as in the test cases it accepts the "uFile"

https://github.com/odoo/odoo/assets/55706708/1ecf8f56-04b4-4170-b21b-424b0fb384be

**Review by reth-odoo — COMMENTED** [review]
@vivekpabari1894 I see, I believe this is fixed here 6e27c43c58dd323c74dfe218f6c6b5a7ee9ddce5

Which I guess should land on odoo.com next monday if it's not already applied there.
Sorry for the inconvenience in the meantime.

Let me know if not, otherwise I think we can close this PR

**Comment by vivekpabari1894** [comment]
Hello @reth-odoo Yes, This fix the issue. We can close this PR

Thanks for your time

**Pull request closed without merging**
