### PR TITLE
[FIX] config: Avoid error when session dir is created just after checked

### PR DESCRIPTION
**Pull request by luisg123v**
Currently, when a web session is created, the following is done:
1. The directory is tested to verify if it exists
2. If it doesn't exist, it's created

However, when that process is done several times concurrently, sometimes
the directory is created between step 1 and 2, causing the following
exception:
`OSError: [Errno 17] File exists: '/home/odoo/data_dir/sessions'`

This patch ensures that, when the above case occurs, that exception is
properly handled.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
In which case do you get a concurrent access so fast that it creates the dir between step 1 and 2?

**Comment by luisg123v** [comment]
@mart-e
It happens when unittests are run and they involve documents printing.

**Comment by mart-e** [comment]
I am not sure to understand in which case it happens but anyway it is true we could get a raise condition,
Actually, the `if not os.path.exists(d):` is not useful, we can just try to create it and skip if the creation fails.

Either we use a try/except, either we use `os.makedirs(path, mode=0700, exist_ok=True)`

**Comment by luisg123v** [comment]
@mart-e 
- `exist_ok=True` is available only for Python >= 3.2
- I considered replacing `if not os.path.exists(d)` by a try-catch, but I wanted to keep changes as smaller as possible. I will do it that way

**Comment by luisg123v** [comment]
@mart-e 
Sorry, I didn't noticed you edited your comment. Could you review again, please?

Note: I'm targeting v10 because, for some reason, this has happened only in that version. so far.

**Comment by mart-e** [comment]
Sorry but to merge it in 10.0, I need to have a way to reproduce it.
As I understand, this kind of error can only happens one (as the dir is already created after). If the only thing that happens is a failing test, not much harm.
Can you reproduce it with a standard test or in your module? Maybe the problem comes from somewhere else.

**Comment by luisg123v** [comment]
@mart-e 
I understand. This is very hard to reproduce, because not always happens. Actually, the only way I've found to reproduce it for sure is to put a breakpoint just after the condition, so I can create the directory manually :).

I guess this still could be merged in master.

**Pull request closed without merging**
