### PR TITLE
[I18N] base: export 12.0 source terms

### PR DESCRIPTION
**Pull request by mart-e**

### CODE REVIEW

**Comment by mart-e** [comment]
@jvm-odoo seems that it prevents the error locally but I haven't investigated why exactly

**Comment by jvm-odoo** [comment]
Thanks for looking at it! I just checked but I can't find why this prevents the error. According to the error message shouldn't we remove lines? Here we are not except for this part, maybe this is the cause of the issue but I'm not sure.
```pot
#. module: base	
#: model:ir.module.category,name:base.module_category_stock	
msgid "stock"	
msgstr ""
```

**Comment by mart-e** [comment]
Ok, I got it! At ec5980f658eec09872294d32eb64d9a751 the term
```po
#. module: base
#: model:ir.module.category,name:base.module_category_stock
msgid "Stock"
msgstr ""
```
was introduced but the 
```
#. module: base	
#: model:ir.module.category,name:base.module_category_stock	
msgid "stock"	
msgstr ""
```
pointing to the same record was still remaining.

During the import it was then trying to import 2 translation for the same record, which obviously crashed...

cc @len-odoo 

@robodoo r+

**Comment by jvm-odoo** [comment]
Nice job!

**Comment by mart-e** [comment]
robodoo retry

**Comment by mart-e** [comment]
Added a test to catch these ones earlier
@robodoo r+ rebase-ff

**Comment by mart-e** [comment]
Good test caught another issue in enterprise, fixed at odoo/enterprise#7200

@robodoo r+

**Comment by mart-e** [comment]
@robodoo retry then !

**Pull request closed without merging**
