### PR TITLE
[FIX] sale: POS orders in sale report

### PR DESCRIPTION
**Pull request by jvnm-dev**
Reproduce this issue

    - Install PoS & Sales
    - Create a PoS order
    - Close & validate the session
    - Go on the product details
    - Click on "x Sold" stat button

    The quantity you bought from the PoS order is not on the graph.
    If you sort by "Order Reference" you will see only SO but not from
    PoS.

Cause

    The action bound to the "x Sold" button is still using the old
    report who uses an old model.

This commit changes the report used for this button by the right one.

OPW-2121333

### CODE REVIEW

**Comment by jasonvanmalder** [comment]
@nim-odoo

**Comment by jasonvanmalder** [comment]
fw-bot up to 12.0

**Comment by nim-odoo** [comment]
robodoo rebase-ff

**Comment by nim-odoo** [comment]
I guess 4bd8b37f59e489d5d120a15c0aea52167abdae42 should be in 12.3, no?

**Comment by jasonvanmalder** [comment]
@nim-odoo Only the first commit is needed in 12.3, will do a PR

**Pull request closed without merging**
