### PR TITLE
[FIX] *: clickall test

### PR DESCRIPTION
**Pull request by Polymorphe57**
The commits https://github.com/odoo/odoo/commit/f1749d3299957e2949e0b78653266a5397bb213c and https://github.com/odoo/odoo/commit/847e5c984a6873954686503886e1874b78c75951 have introduced some bugs detected by the test clickall. We fix those bugs here.

Runbot build: https://runbot.odoo.com/runbot/build/65237075

### CODE REVIEW

**Comment by aj-fuentes** [comment]
It's unclear what bug you are referring to. Anyway I find important to mention `[FIX] *: no gantt in community ` ;)

**Review by aab-odoo — APPROVED** [review]
robodoo rebase-ff r+

**Comment by Polymorphe57** [comment]
robodoo r-

**Comment by Polymorphe57** [comment]
@robodoo retry

**Pull request closed without merging**
