### PR TITLE
[CLA] Alejandro Santana

### PR DESCRIPTION
**Pull request by alejandrosantana**
Added signed CLA as individual.

### CODE REVIEW

**Comment by alejandrosantana** [comment]
One question: What is the use for the email?
I have 2 emails declared in Github, for example.

**Comment by alejandrosantana** [comment]
@mart-e can you review this CLA addition?

**Comment by mart-e** [comment]
@alejandrosantana why do you sign twice the CLA ( #6261) ? No need to create an individual if you have a corporate.
The email is used to verify if the author of a commit has signed the CLA ([runbot_cla module](https://github.com/odoo/odoo-extra/blob/master/runbot_cla/runbot.py). So you should put the email you are using to commit (or put both)

**Comment by alejandrosantana** [comment]
Given a strange legality in Spain I am co-owner of a company, but also a freelancer (not related to my own company) and I might commit/PR as both roles.
But whatever works for you.

**Comment by mart-e** [comment]
Ok I have merged the corporate CLA but if you need to make some actions in a different role (I guess with a different email), you can make one individual CLA signature with the other email.

**Comment by alejandrosantana** [comment]
Perfect, I will update the email on the individual CLA in a minute. Thanks.

**Pull request closed without merging**
