### PR TITLE
[WIP] Refactor to Session Store Class

### PR DESCRIPTION
**Pull request by blaggacao**
This refactoring allows cleaner inheritance and overriding of the session
store by defining a complete interface of necesary methods to implement.

Addresses / Closes https://github.com/odoo/odoo/issues/24267

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
Passwords are not stored in session anymore: https://github.com/odoo/odoo/commit/da1f153d61d747d9357694382fe04f96c0ca886a

So, we can potentially move session store to Postgres or Redis. So, some update like is this PR is needed

**Comment by gustavovalverde** [comment]
Is this in the merge roadmap? cc: @mart-e @KangOl

**Comment by blaggacao** [comment]
hahaha last time i worked on this code, I didn't even remeber this is actually a patch of mine...

**Comment by C3POdoo** [comment]
Dear @blaggacao,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
