### PR TITLE
[IMP] Add icons to the boolean toggle widget

### PR DESCRIPTION
**Pull request by tdecaluwe**
This commit aims to clarify the state of the boolean toggle widgets used in the web editor. To this end, a grayed out cross icon is added in the inactive state and a green check mark icon is added in the active state.

task-2586313

### CODE REVIEW

**Review by rdeodoo — CHANGES_REQUESTED** [review]
image
image

I don't want to be rude but this is ugly.. We can't release that..

Even in the right panel it is not really beautiful..
image


Original mockup from the spec was:
image

Which is very different from what you have done here.
(Event if I know you have a very small sized toggle to works with, and it is not easy)

**Comment by bvr-odoo** [comment]
IMO if we want this new design, I think the toogle must be enlarged. The icons are very small ;)
cc @rdeodoo

**Comment by rdeodoo** [comment]
Indeed, that's what I said right away, it can't work with such a small sized element.
> (Event if I know you have a very small sized toggle to works with, and it is not easy)

It was a bit discussed outside this PR and I was wondering if we could not just apply this style on our "non-right panel toggle" (customize options, published button, page properties dialog etc) and leave the right panel one as such, as enlarging it would break the layout IMHO.

But that's a pure design related question so.. I will let the final decision to a designer ;-)

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
