### PR TITLE
[FIX] point_of_sale,pos_restaurant: ui issues

### PR DESCRIPTION
**Pull request by vlst-odoo**
In this PR we fix a number of small issues related to the pos ui.

In addition to the specific fixes, this PR also simplifies many
of the components, most notably the `category_selector`.

In the interest of providing a cleaner API, this PR introduces
a new folder called `generic_components` whose goal is to contain
stateless components. These stateless components would allow for more
reusability, while simplifying the logic. The `category_selector` is
the first component in this folder.

Descriptions of each of the issues fixed in this PR can be found in the
task: 3457213

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by caburj — APPROVED** [review]
robodoo r+

**Comment by seb-odoo** [comment]
Hello,

This PR is responsible of breaking enterprise in staging: https://runbot.odoo.com/runbot/build/49164213

You might want to create an enterprise branch and adapt the xpath accordingly!

@robodoo r-

**Comment by caburj** [comment]
> Hello,
> 
> This PR is responsible of breaking enterprise in staging: https://runbot.odoo.com/runbot/build/49164213
> 
> You might want to create an enterprise branch and adapt the xpath accordingly!
> 

@vlst-odoo Kindly adapt the xpath as mentioned.

**Comment by caburj** [comment]
robodoo r+

**Comment by caburj** [comment]
robodoo r+

**Pull request closed without merging**
