### PR TITLE
Allow to disable English language

### PR DESCRIPTION
**Pull request by rco-odoo**
Load all languages into the database from a CSV file.
Languages are inactive by default, only the "installed" languages are active.
Activate only the requested language(s).

Installing a database in French will result in:
- only the French language is active,
- the English language is present but inactive.

Do not show the translation icon when only one language is installed.

### CODE REVIEW

**Comment by wtaferner** [comment]
I don't know if it is already solved but I wanted to put it here that duplicating an object always duplicates the English term in database mostly with (Copy) + translation and changing a field in another language does not affect the English source term of the translated object which is kind of confusing for users and will lead to issues as soon English is used and activated and users were not always aligning the English term accordingly and immediately (a lot of (Copy) object names will make data horrible, etc.)

By disabling the English language would mean that the source term somehow is finally completely out of sight although still present in database and not editable on duplication...

Is Odoo aware of this issue? Maybe @mart-e, the translation guru, can say something about the status and if a solution for this is on the road map?

**Comment by mart-e** [comment]
But what would you like to have as a behaviour ? Once you install a second language, you will need to adapt the translations that's true. But it's not linked only to the duplication, applies also for the modification of records (as soon as you modify in one language, you need to modify in another).

As soon as you have multiple languages, you *have to* care about the translations ! You can not just say "well, I guess everything will be fine". The issue is that I don't think there is a perfect scenario.

**Comment by wtaferner** [comment]
Well, based on the changes done here where English (which is always the base language) can be disabled or will not be enabled from the start, I would suggest to accordingly always align the English source term with the translation done on user side's base language. This does guarantee that user content will stay user content and will not messed up with computational content due to the source term which is magically applied without notice.

I agree that it is difficult but users are totally never aware about this issue. Maybe a forceful and visible translation wizard might help on duplication (in case more than one language is installed) to handle such pitfalls best b/c as you said...there is no perfect scenario about how to resolve this.

**Comment by mart-e** [comment]
Let say I have my product translated in 4 languages, when I duplicate a record, it's usually to change a few attributes (e.g. same product but in bigger packaging), so I do not want to retranslate everything all over again. If I have made a long description of my product, I want to keep most of it and only adapts the part that have changed.

However, about duplication @rco-odoo there is one issue that could be raised.
1. create a db in French, no other language activated
2. create a job position with a name, company and department (translatable name with unique constraint)
3. duplicate the job => error constraint violated

This is because my french translation uses "copy" in the name but not the source term.
Until now it was not that big a deal because you could always work around by duplicating in English but with your patch, English is not activated.

**Comment by wtaferner** [comment]
I think the biggest issue is that we do not have a intuitive translation widget which does give the user the power to decide what is actually done to an object or the user at least gets informed about the full impact a modification have to be able to resolve it immediately. The (Copy) of duplication is just a symptom for this issue with unique fields...as long the user is in full control and does know what is going on the rest will and can be handled by the users imho. What do your UX designers say about this issue?

**Comment by treviser** [comment]
I don't know if my observation here (https://www.odoo.com/forum/help-1/question/8-0-website-builder-non-english-only-website-all-kind-of-mysterious-problems-may-arise-92338)
also is related to the issue discussed here, but I was referred to it.

**Comment by rco-odoo** [comment]
@odony @antonylesuisse with this branch, we can have any language installed on a database without English being installed by default. Review and comments are welcome.

**Pull request merged**
