### PR TITLE
[14.0] multi currency patch

### PR DESCRIPTION
**Pull request by luc-demeyer**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by luc-demeyer** [comment]
This PR fixes two multi-currency issues:

1) date used for currency rate conversion

Odoo 14 uses the accounting date for determine the currency rate in stead of the invoice date.
The invoice date should be used, cf. according to cnc/cbn (cf. https://www.cbn-cnc.be):

Le cours de change à utiliser comme cours de conversion est en principe celui du jour de l'opération, c'est-à-dire le jour auquel la créance ou la dette en devise qui en résulte est née. La détermination de ce jour n'est toutefois pas toujours immédiatement évidente. 
Il est dés lors de pratique courante d'adopter comme cours de conversion, le cours de change du jour où l'opération en devise est comptabilisée.
Des motifs de praticabilité et de comparabilité peuvent toutefois justifier l'adoption, par l'organe d'administration, d'autres bases de conversion, pour autant que celles-ci restent proches du cours de conversion défini ci-dessus

2) reconciliation logic

The reconciliation logic does not take into account the following use case:

financial journal in foreign currency, bank statement line with foreign currency == company currency and counterpart move in same currency as bank journal.

The fix is not very clean since imho the code block handling the multi-currency scenarios needs to be refactored for improved readability and maintainability.
But the fix now runs for a couple of weeks in production at a customer site who does multi-currency transactions on a daily basis and it does the job. Hence merging the logic in this fix should be added into refactored code or alternatively merging this is better than keeping the faulty behaviour and refactoring can be done in e.g. the upcoming 16.0 release. 

The use case fixed here is also not supported by the reconciliation widget, cf. https://github.com/odoo/enterprise/pull/27463

**Comment by vin-odoo** [comment]
Hello, could you please let me know if the PR is ready to be reviewed? As I see a todo, the runbot is red and it is in conflict.

**Comment by luc-demeyer** [comment]
@vin-odoo 
As stated in my TODO: I think it's better to add a unit test and refactor the code for better readability and maintainability.
But the code is now running for more than a month in a production environment without any problems hence an alternative is to merge this one for 14.0, forward port to 15.0 and do the code refactoring and unit test in the upcoming 16.0 release.
Up to Odoo to decide.

**Comment by vin-odoo** [comment]
I talked about these with our PO (cc: @tsb-odoo ).

The first point shouldn't be changed in stable, as it is a change in behavior which should be avoided.
As for master, we have someone working on that already, see https://github.com/odoo/odoo/pull/87984

Point 2 is indeed an issue that needs a fix. Could you please provide us with a video of the problematic flow taken from a runbot?
Just to ensure that we are on the same page. Thank you very much!

Few small points about the PR:
-The commit doesn't need the version in its title. On the other hand, it should be prefixed with a [FIX] tag
-Both community and enterprise branches for the reconciliation issue should be named the exact same.
This way, the runbot will be able to match them and run the tests with both commits applied.
-Please add a test, to ensure that the flow won't be broken again in the future.

Thank you very much for coming to us with the issue and a fix :)

**Comment by C3POdoo** [comment]
Dear @luc-demeyer,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
