### PR TITLE
[FIX] web: configuration layout: preview misaligned on mobile

### PR DESCRIPTION
**Pull request by adr-odoo**
Before this commit, the preview was on the rigth and you had to scroll
to see the preview of the document.

Now, the preview is below on mobile.

Task-4377734

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by malb-odoo — COMMENTED** [review]
Seems to be working fine like that thanks ! Will pass it to the next reviewer of our team :smile:  Runbot doesn't seems happy but don't think it's related to your change aha

**Comment by pparidans** [comment]
@adr-odoo Looks OK. But could you rebase the branch (so the runbot is happy again :grin: ) ?

**Review by Iucapad — APPROVED** [review]
@robodoo r+

**Comment by adr-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
