### PR TITLE
[CLA] Update DinamicheAziendali CCLA

### PR DESCRIPTION
**Pull request by Borruso**
Related to odoo/enterprise#73595

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Borruso** [comment]
@lordkrandel ping

**Review by lordkrandel — CHANGES_REQUESTED** [review]
Hello, it looks like the CI is complaining about the commit message starting with an unwanted space character. 
immagine

**Comment by Borruso** [comment]
> unwanted space character

thanks for review (i didn’t really notice)

**Review by lordkrandel — APPROVED** [review]
LGTM 👍🏻

**Comment by lordkrandel** [comment]
@mart-e Can you please have a look?

**Review by mart-e — APPROVED** [review]

**Comment by lordkrandel** [comment]
@epictete 👋🏻 
Let's welcome this new partner developer contributing to `l10n_it`, mainly `l10n_it_pos` at the moment.
i.e. odoo/enterprise#74034

**Review by lordkrandel — APPROVED** [review]

**Comment by epictete** [comment]
@robodoo r+

**Pull request closed without merging**
