### PR TITLE
[FIX] point_of_sale : fiscal position for account is not used

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**

Create fiscal position with account mapping (for product and partner)
Go to POS, use this fiscal position.
--> Issue the account.move generated don't use account of fiscal position.

@oco-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW 2359464

**Comment by fmdl** [comment]
@simongoffin

**Review by oco-odoo — APPROVED** [review]
Looks legit to me. 

@pimodoo Do you agree ? Or is it some choice we made back in the day for reasons I don't know? ^^ If so, what were they?

**Comment by oco-odoo** [comment]
@pimodoo Normally I'd agree with you, but open it and you'll see the problem ;p

**Comment by fmdl** [comment]
ping @oco-odoo @pimodoo

**Pull request closed without merging**
