### PR TITLE
[FIX] portal_rating: catch error when no message submitted

### PR DESCRIPTION
**Pull request by mattismegevand**
Steps to reproduce:
- Install e-Commerce
- Go to your portal into a quotation
- Go to the chatter and send an empty message

Issues:
A traceback is shown

Solution:
Catch the error and discard it as the parent method is already displaying the error message to the user.

opw-3877096

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

**Review by reth-odoo — APPROVED** [review]
Might need a rebase (red runbot)

**Comment by nle-odoo** [comment]
robodoo delegate+

**Comment by tde-banana-odoo** [comment]
@seb-odoo Just in case

@reth-odoo Hawk eyes !

**Comment by seb-odoo** [comment]
I don't know/remember ever seeing this file, but thanks for the heads up just in case!

**Comment by tde-banana-odoo** [comment]
We call that "legacy code" . If it works, it works ^^ .

**Comment by mattismegevand** [comment]
@robodoo r+

**Pull request closed without merging**
