### PR TITLE
[IMP] hr_timesheet: populate

### PR DESCRIPTION
**Pull request by auon-odoo**
task-3030132

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by IT-Ideas** [comment]
Arf, there are some conflicts, could you resolve them?
Thanks 🙂

**Comment by auon-odoo** [comment]
@IT-Ideas done :)

**Review by IT-Ideas — APPROVED** [review]
@robodoo r+

**Comment by IT-Ideas** [comment]
Thanks @auon-odoo 🙂

**Pull request closed without merging**
