### PR TITLE
[REF] module.py: replace deprecated imp by importlib

### PR DESCRIPTION
**Pull request by Julien00859**
[PEP 574] is going to depreciate the `imp` standard module in PY3.8,
the `importlib` module a substitute module.

[PEP 594]: https://www.python.org/dev/peps/pep-0594/#imp

Was #35929

### CODE REVIEW

**Comment by Julien00859** [comment]
@odony @xmo-odoo I had a talk with Antony, he would likes we drop the support for `openerp` imports and bare module imports. What do you think about a deprecation warning in v13 and to remove them (as part of this PR) for v14 ?

**Comment by xmo-odoo** [comment]
@Julien00859 that lines up with what I was thinking.

**Comment by odony** [comment]
@Julien00859 sounds like a plan

**Comment by Julien00859** [comment]
See #36597

**Pull request closed without merging**
