### PR TITLE
[FIX] sale_timesheet: fix the add to cart traceback on portal

### PR DESCRIPTION
**Pull request by ppr-odoo**
Reproduction step:
   - Create Sale Oder(Add optional product)
   - Customer Preview(portal)
   - Add to cart

TaskID: 2431351

### CODE REVIEW

**Comment by xavierbol** [comment]
LGTM ! Thanks

**Comment by IT-Ideas** [comment]
@robodoo r+

**Comment by IT-Ideas** [comment]
Hello @tivisse ,

Can you r+? :)

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
