### PR TITLE
[FIX] calendar: fix t-on-click in form view

### PR DESCRIPTION
**Pull request by jeh-odoo**
Remove the t-on-click used in form view as it crashes when opened with studio.
Instead we use a dedicated `<widget/>`

task-3090960

### CODE REVIEW

**Review by aab-odoo — APPROVED** [review]
The `onConnect` link could probably be replaced by a `<button name="action_calendar_prepare_external_provider_sync" type="object"/>` imo, so that you don't need any js custo at all for this. However, this can be done/tried in another PR. For now, I'm happy to see those directives being removed from the arch, so let's merge this :-)

**Comment by aab-odoo** [comment]
Hello @jeh-odoo Is the work done here? Could we move forward? I can't wait to have those things fixed in master :D

**Comment by aab-odoo** [comment]
ping @jeh-odoo

**Comment by jeh-odoo** [comment]
Hello @aab-odoo 
Sorry for the delay! It should move on in the week

**Comment by aab-odoo** [comment]
Hello @tde-banana-odoo 

Could we move forward with this one?

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
