### PR TITLE
[FIX] website, web_editor: fix overlay options of the timeline snippet

### PR DESCRIPTION
**Pull request by bvr-odoo**
Before this commit, the CSS of the overlay option buttons of the
timeline snippet was broken.

task-2648348

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by bso-odoo — COMMENTED** [review]
On hover, all three buttons (trash, move left, move right) are darkened together.
image

Also, does it make sense to have arrows in both directions while it always sends to the opposite side ?

**Comment by bvr-odoo** [comment]
> On hover, all three buttons (trash, move left, move right) are darkened together.
Not sure to understand what you mean, for me it's the same behavior as everywhere...
> Also, does it make sense to have arrows in both directions while it always sends to the opposite side ?
It is a choice that we made for this option, a double arrow which means that the user can switch the position of the card (right or left)

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
In this case, I would not target 14.0 but 15.0: the bug is non-blocking and the only way to fix it properly seems to be like you did. But doing it like you did is not entirely stable: the structure en the UI DOM changes, the CSS rules changes... so you likely break custo adding stuff in the overlay.

15.0 is very recent so I guess code relying on this structure is still ok to change like you did here. If you still want to target 14.0, then don't change the structure (= keep the div) and *add* css rules (don't remove any).

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
