### PR TITLE
[FIX] mrp: persist expected duration when generating BoM

### PR DESCRIPTION
**Pull request by hado-odoo**
Before this commit
==================
When creating a BOM through a MO (form view), the WO expected duration is reset
to the default value on the source MO as well as the corresponding Operations in
the BOM.

Steps to Produce
=================
- Create a MO with 1+ WOs and set an expected duration for the WOs.
- Generate a BOM through the MO and observe the changed duration after saving
the BOM

After this commit
=================
After this commit the operation/WO duration doesn't reset to default values.

task - 3414446

### CODE REVIEW

**Comment by ticodoo** [comment]
Fix is good for me :+1: 

can you just clean up your commit a little?

The title should say what your commit does WHEN APPLIED, not what your commit is fixing:
`[FIX] mrp: persist expected duration when generating BoM`

the body just has small English grammar/precision mistakes:

Before this commit
==================
When creating a BOM through a MO (form view), the WO expected duration is reset to the default
value on the source MO as well as the corresponding Operations in the BOM.

Steps to Produce
=================
- Create a MO with 1+ WOs and set an expected duration for the WOs.
- Generate a BOM through the MO and observe the changed duration after saving the BOM

After this commit
=================
After this commit the operation/WO duration doesn't reset to default values.

**Comment by ticodoo** [comment]
Sorry @hado-odoo you need to retarget this for saas-16.4

**Comment by hado-odoo** [comment]
Hello @ticodoo retargeted to saas-16.4 is done. Thanks.

**Comment by ticodoo** [comment]
Thanks!

@robodoo r+

**Pull request closed without merging**
