### PR TITLE
[IMP] web,web_editor,point_of_sale: remove jquery.nearest library

### PR DESCRIPTION
**Pull request by pparidans**
This library provided the `nearest()` and `touching()` methods.

This commit replaces them by our own utility methods from `@web/core/utils/ui`: `closest()` and `touching()`.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pparidans** [comment]
I'd really love feedback from @odoo/rd-framework-editor before merging this...

**Comment by dmo-odoo** [comment]
@pparidans I'm flattered but the `addons/web_editor/static/src/js/editor/snippets.editor.js` file is handled by @odoo/rd-website ;-)

**Review by rdeodoo — APPROVED** [review]
Approving the website part.
Gave it a round of test and seems to be working as expected.

**Review by caburj — APPROVED** [review]

**Review by adr-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
