### PR TITLE
[FIX] account: duplicate tax

### PR DESCRIPTION
**Pull request by simongoffin**
the duplication of a tax must duplicate the child_ids.

opw:630510

### CODE REVIEW

**Comment by qdp-odoo** [comment]
mhm copy=True is the default behavior, isn't it? i feel there's something weird here

**Comment by odony** [comment]
@qdp-odoo Well, `copy` defaults to `False` for `one2many` fields as of 8.0, because there are  a lot more models where the `one2many` lines should *not* be duplicated upon copy.

**Comment by qdp-odoo** [comment]
ha very good! i remember we talked about doing it that way. Nice to see someone worked on that

fine for me too, then

**Comment by beledouxdenis** [comment]
:+1:

**Comment by beledouxdenis** [comment]
Closed with 6f679678f638b835e00299fc7aa9903a7688a583.

**Pull request closed without merging**
