### PR TITLE
[REF] untangle send_email to ease custom send methods

### PR DESCRIPTION
**Pull request by blaggacao**
#### Description of the issue/feature this PR addresses:

Untangle send_email method, in an idempotent manner.
Objective: Ease implementing private mail sending methods, which do not adhere to the SMTP protocol. Separation of Concerns.
#### Current behavior before PR:

Idempotent.
#### Desired behavior after PR is merged:

Idempotent.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

This eases hooking into _send_email and detect a custom server attribute.
This is prerequisite for implementing sending mails over a notification api, for example.
Also mailchimps mandrill email sending does not impelment an SMTP interface, but a REST api point.
So this enables implementing mandrill mor easily.

Signed-off-by: David Arnold dar@devco.co

### CODE REVIEW

**Comment by blaggacao** [comment]
Replaced #11751

**Comment by odony** [comment]
Thanks for the PR. I don't think I understand your rationale for trying to implement a pluggable Mail API in Odoo, though. Why not use the [SMTP version of your Mandrill integration](https://mandrill.zendesk.com/hc/en-us/articles/205582137-How-to-Send-via-SMTP-with-Popular-Programming-Languages#python), which works fine (we've used Mandrill SMTP in the past with Odoo). 
SMTP is the universally accepted mail protocol, it's ubiquitous, and `ir.mail_server` is really designed with SMTP in mind.

It's like trying to fit the square plug of your device into a round socket, even though the device also came with a round plug. And then asking the socket to be more flexible ;-)

In addition, It seems you'll end up overriding most of the code, so it would be just as simple to override the `send_mail` method entirely, and copy whatever code you have in common with it. You might even want to use a different model to represent your "REST API endpoints", instead of highjacking the `smtp_*` columns

Now if your other requirement is a way to pass or receive custom headers during the SMTP session, could you please explain your use case with a real example -  perhaps a minimalist solution could be implemented without changing much in our SMTP API?

**Comment by blaggacao** [comment]
I think it was for the subaccounts and the ability to put a daily quota limit in order to prevent abuse through our clients. At least that's what I reconstruct from my memory. Or did I miss that this is possible over the SMTP api as well?

>It's like trying to fit the square plug of your device into a round socket, even though the device also came with a round plug. And then asking the socket to be more flexible ;-)

I'm inclined to spend some more thoughts about what could a flexible socket look like in practices, intriguing idea! ;-)

>In addition, It seems you'll end up overriding most of the code, so it would be just as simple to override the send_mail method entirely, and copy whatever code you have in common with it. You might even want to use a different model to represent your "REST API endpoints", instead of highjacking the smtp_* columns
I see your argument looking at the `send_mail` signature. On the other hand I think hijacking the `ir_mail_server` is still the right thing to do, as the mandrill api does the job of sending email just as good as plain smtp protocol and the `send_email` is well spread around the code base IIRC. Maybe it would be cleaner to out factor the small part with the message handling and validation and otherwise work in our code with a conditional super-call on `send_mail` depending on the detected `ir_mail_server`. Would this be acceptable?

**Comment by blaggacao** [comment]
What about the alternative I've just force-pushed? I hope it is generally "clean" in the design choice and would be a general improvement to the code, and as a side effect would help us just about a little bit with the mandrill implementation with sub accounts.

**Pull request closed without merging**
