### PR TITLE
[IMP] account, l10n_*: add field invoice_label, retrieve field `descr…

### PR DESCRIPTION
**Pull request by clbr-odoo**
…iption` initial purpose

Taxes have a `description` field that has been hijacked to represent tax label on invoices. We want the description field to be used for its original purpose, thus created a dedicated field `invoice_label` in which we transferred `description` content. 
We also make description translatable.
This is part of the Tax Taxonomy 2 rework.

Task: 3052677

### CODE REVIEW

**Comment by qdp-odoo** [comment]
I'm fine with the changes, and with the field names/labels. Whenever these conflicts are solved I can r+ :)

**Comment by clbr-odoo** [comment]
@qdp-odoo Ok, doing that now.
Just a quick note: Christophe asked to make `description` a translatable field, thus we will be able to make columns like `description@fr` but this won't work until #113886 is merged. It doesn't create error without so I guess no need to wait for it.

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by clbr-odoo** [comment]
@robodoo retry

**Comment by qdp-odoo** [comment]
@robodoo r+ agaaaaaiin

**Comment by Feyensv** [comment]
@robodoo r-
Seems really deterministically red on l10n_staging step, please make sure it's green with manually triggered builds before breaking the staging :pray:.

(cf https://runbot.odoo.com/runbot/batch/984311/build/24729865)

**Comment by qdp-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by vin-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
