### PR TITLE
[FW][FIX] fix "datetimeObj.getTime is not a function" error

### PR DESCRIPTION
**Pull request by sakesun**
Description of the issue/feature this PR addresses:

Current behavior before PR:
  This link fail: https://54898231-master-all.runbot133.odoo.com/slides/slide/main-trees-categories-17

Desired behavior after PR is merged:
  It should not fail.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by flch-odoo** [comment]
Hello @saksun,
Thanks for the PR!
This is being fixed in #145573 though.

Cheers!

**Comment by sakesun** [comment]
@flch-odoo #145573 Still leave another problem.

[ DateTime.fromJSDate(...)](https://github.com/odoo/odoo/pull/145573/files#diff-070de290113b51bd773960911b9e8bf1684a89cc2154f28d3557042404fcc342R24)  will expect jsdate as the argument. Putting Luxon DateTime as the argument will give wrong result.

**Comment by tde-banana-odoo** [comment]
Could you fix commit message ? Thanks !

**Comment by flch-odoo** [comment]
@sakesun You are correct that there still is a problem, thank you for insisting. 

However, there is no point in converting a DateTime to JSDate then use fromJSDate, the following lines should rather be simplified as part of the fix, which @lm4649 will do ASAP.

Thank you for your contribution!

**Pull request closed without merging**
