### PR TITLE
stock.quant do not have write permission to any group

### PR DESCRIPTION
**Pull request by bizzappdev**
stock.quant object do not have write access rights for any group and in stock_landed_cost there is a code which write cost value to quant with logged in user uid.

So there are 2 ways to solve this problem,
1. give access right for write to stockmanager/user for stock.quant
2. use speruser uid for writing.

in this PR I am using 2nd option.
also removed print statement

### CODE REVIEW

**Comment by mart-e** [comment]
Thank you for the fix, merged at 61300ee

**Comment by mlaitinen** [comment]
Why is solution 2 better than solution 1? I'm not saying it isn't, I'm just asking.

**Comment by mart-e** [comment]
@mlaitinen the quant is a technical object that should not be modified by users, just under some controlled method from the code.

**Comment by mlaitinen** [comment]
Very good explanation. Thank you.

**Pull request closed without merging**
