### PR TITLE
Create BEN_USAMA.md

### PR DESCRIPTION
**Pull request by usama9211**
@odoo/rd-security

Hi Team
I am a web security researcher and I found a security vulnerability in your website.

ISSUE:
I observe that when I try to reset my password using email "https://www.odoo.com/web/reset_password", I entered my email address and press confirm multiple times to get this internal server error.
I had tested this on chrome, Mozilla & opera, for chrome& opera I had to press more than 12 times on the confirm button but make sure to press the "confirm" button very fast, for Mozilla, I had to press almost 18 or above times but quickly to get this external server error.

Test cases are attached below.
m1Mozzila test 
Opera test
c1Chrome

Steps to reproduce:

1.	First login to https://www.odoo.com
2.	Then logout & go to https://www.odoo.com/web/reset_password
3.	Enter existing email & press confirm multiple times keep in mind for chrome opera press the "confirm button '' more than 
for Mozilla more than 18. and then u will be able to get an internal server error

DESCRIPTION :

The 500 Internal Server Error is a very general HTTP status code that means something has gone wrong on the web site's server but the server could not be more specific on what the exact problem
They indicate that the server failed to complete the request because the server encountered an error. When you try to visit a website and see the error "500 Internal Server Error" message, it means something has gone wrong with the website. This is a "catch-all" status for unexpected errors. The error is particularly frustrating because it gives you no information about what specifically caused the server error. This isn't a problem with the browser, computer, or internet connection. It's a problem with the site server.

IMPACT:

There are two security issues that come to mind.
1.	Leaking information about your system. If a stack trace makes it back to the client-side, then you can end up leaking information that could help an attacker build a more effective attack. You've mentioned that this stack trace is only in your logs, so this point is not an issue.
2.	Denial of service. This is an issue if an attack causes you to leak resources or if it makes the server-side do far more processing per request than must be done on the client-side.

REFERENCES :

https://hackerone.com/reports/819088
https://hackerone.com/reports/157986
https://hackerone.com/reports/55716
https://www.westhost.com/knowledgebase/display/WES/What+Is+A+500+error
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
https://www.interserver.net/tips/kb/troubleshoot-500-internal-server-error/
Looking forward to your positive response.
Regards,
Usama
usamaahmed000@gmail.com
32803513+usama9211@users.noreply.github.com
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by usama9211** [comment]
any update ?

**Comment by mart-e** [comment]
Hi there,

The 11.0 is no longer supported, could you submit for 12.0?
Why is the message of your PR the content of an email you have sent to us?

**Comment by usama9211** [comment]
Thanks for your feedback , sorry for the misunderstand that I had before regarding 11.0 and now I am submitting this request on 12.0 , Look I just need my name to be in your hall of fame nothing else as a contributor , after doing a lot of work for your organization , I am still feeling demotivated and I am not gonna do anything else for your organization unless mark our team name to be in your fame list , thanks again
regards .
demotivated Usama

**Comment by mart-e** [comment]
The CLA signature and hall of fame are not the same thing. The CLA is for contributing for the code of Odoo. The hall of fame is for **valid** security reports.
I am sorry if you feel demotivated but unfortuntaly, as explained by my collegue by email, the report was rejected as invalid.
If you check the _NON Qualifying vulnerabilities_ section on the [Responsible Disclosure](https://www.odoo.com/security-report) page, this falls under the "Disclosure of public information or information that does not carry significant risks" (we are an open source software, displaying a traceback is a bug but not a security issue).

Thank you for your research and report but this is not enough to figure on our hall of fame I am afraid.

Best,

**Pull request closed without merging**
