### PR TITLE
[IMP] point_of_sale: improve ui in close popup for mobile view

### PR DESCRIPTION
**Pull request by nesma-neha**
Changed the buttons in the closing_popup for mobile view to be in two lines with container grid view instead of flex-wrap

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by davidmonnom** [comment]
On runbot I have something like that 
image

Is it the goal of the PR ? 
@mobt-odoo are you aware ?

**Comment by mobt-odoo** [comment]
@davidmonnom  @nesma-neha 

Sorry for the change request but can you make 2 buttons per line. Use same font size for each. 
Thanks

**Comment by nesma-neha** [comment]
@mobt-odoo there are five buttons
One of them appears based on a condition

originally it was three buttons on one line and 2 on the other.

this pr makes them all appear on the same line.
Can you please specify the changes needed?

**Comment by davidmonnom** [comment]
Different buttons may appear under certain conditions, the aim being to maintain the same size on mobile and desktop. On my previous screenshot, we can see that Cash In/Out fontsize is different.

Can you also put them on two line ?

**Review by davidmonnom — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
