### PR TITLE
[FIX] all: grant py39 support

### PR DESCRIPTION
**Pull request by Julien00859**
There are new opcodes with py39 and base64.{en,de}codestring have been
replaced by base64.{en,de}codebytes.

Closes: #71352

### CODE REVIEW

**Comment by Julien00859** [comment]
@fw-bot up to 13.3

**Comment by Julien00859** [comment]
@fw-bot up to 13.0

**Comment by Julien00859** [comment]
@Yenthe666 could you test you can install odoo using py3.9 with the changes made in this branch ?

**Comment by Julien00859** [comment]
See https://github.com/odoo/odoo/issues/59980 v12, v13 and v14 are at most compatible with v3.8. Gonna change the documentation.

**Comment by Yenthe666** [comment]
Ehh, kinda stupid that it would not support v3.9 though. For example: the newest droplets that you generate on DigitalOcean automatically come with Python 3.9. This means that anyone creating a droplet there has automatically P3.9 & no compatibility 🤷

**Comment by Julien00859** [comment]
I've just been updated on our internal policy: each Odoo version works with the debian stable at the time of the release. I totally understand it can be frustrating. I'm not even sure v12 works in py3.8. Sorry :/

**Comment by Yenthe666** [comment]
Okay too bad :( thanks for your efforts!

**Pull request closed without merging**
