### PR TITLE
[FIX] fields: do not serialize more digits than necessary in `monetary._symbol_set()`

### PR DESCRIPTION
**Pull request by rco-odoo**
Add a class for float objects that carry their precision digits, use it for the
value of monetary fields in record cache, and serialize them as expected for
the database.

### CODE REVIEW

**Comment by odony** [comment]
On second thought it looks a bit risky for 9.0, but for master it sounds good.
Perhaps we could use some tests to ensure that the patch does indeed fix an issue? Maybe a check of the cached value, and a test of a float value stored into the database?

Thanks!

**Comment by dreispt** [comment]
What about introducing instead the decimal data type?
Monetary fields would derive from decimal fields.

**Comment by rco-odoo** [comment]
@odony I just added a simple test based on Antony's scenario.

**Comment by rco-odoo** [comment]
@dreispt Indeed, the class `float_precision` looks like a poor man's decimal implementation, but it has almost no performance penalty. Python decimals are really nice, but they are an order of magnitude slower than floats. That's why we are a bit reluctant of using them in Odoo.

**Comment by rco-odoo** [comment]
Rebased on branch `master` in #12549.

**Comment by odony** [comment]
@dreispt The additional problem with Decimal is that you just can't mix them with floats, without losing all the advantages of Decimals. Using Decimal requires rewriting most of the code dealing with floats in Odoo (why would we limit ourselves to Monetary fields in that case?), and requires all developers to master the subtleties of Decimals at every step in the code. Float and Monetary fields work naturally together, and this PR was trivial to implement due to that. It's a nice-to-have improvement for consistency, by the way, as no bug was identified here. The story would be completely different with Decimal.
So we'd have to deal with lots of new bugs (those directly coming from the rewrite, those caused by developers learning Decimals), plus the possible performance penalty and complexity increase in the code.. a very hard trade-off for a nice-to-have patch, in my book. If you're interested in learning more about this dead horse, you'll find plenty of polemic/rants/flamewars in our old Launchpad bugtracker.

**Comment by odony** [comment]
Closed, cfr #12549 then.

**Pull request closed without merging**
