### PR TITLE
[FIX] sale_timesheet: don't count expense as recorded hours on SO 2

### PR DESCRIPTION
**Pull request by pivi-odoo**
## Description
Follow up on #128696, because the fw-port in 15.0 was merged before the additional changes could've been added.

## Affected versions
15.0 -> master

---
opw-3302460

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
robodoo r+ 

Thanks 🙂

**Comment by pivi-odoo** [comment]
@robodoo rebuild

**Comment by pivi-odoo** [comment]
@xavierbol
I've corrected the patch, `is_timesheet` is defined in `timesheet_grid`, but `sale_timesheet` doesn't inherit indirectly from it, so it failed on the runbot.
I just changed the leaf with `project_id` != False, which is basically the same as the implementation of `is_timesheet`.

**Review by xavierbol — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
