### PR TITLE
[Fix] Built vs Builded Grammar

### PR DESCRIPTION
**Pull request by lathama**
Description of the issue/feature this PR addresses: Spelling fix

Current behavior before PR: Incorrect spelling.

Desired behavior after PR is merged: Correct spelling

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lathama** [comment]
Will do the CLA, First contributed when was just called Tiny via Pinky so it has been a while.

**Comment by lathama** [comment]
CLA added and a chicken and egg issue. Will await response.

**Comment by mart-e** [comment]
Hello,

No chicken and egg problem here, it is an issue on the git configuration 😉 

- you are signing using the address `lathama@users.noreply.github.com`
- you are signing for the address `l...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by lathama** [comment]
@mart-e 
ack understood. Github #featurenotabug so I will destroy this and do it from the command line vs the web gui. Hint: """Keep my email address private We'll remove your public profile email and use lathama@users.noreply.github.com"""

@d-fence the extra slash was not intended and good catch, I will blame my fat fingers.

@fpodoo Pinky I did not see your CLA, do old contributors grandfather in?

**Comment by lathama** [comment]
and closing with the correct button and some coffee....

**Comment by fpodoo** [comment]
@fpodoo <https://github.com/fpodoo> Pinky I did not see your CLA, do old
contributors grandfather in?

The CLA is used transfers some rights to odoo. There is no CLA for Odoo
employees we cede the copyright of our work under the employment contract.




—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/odoo/odoo/pull/20251#issuecomment-337892818>, or mute
the thread

**Comment by lathama** [comment]
Thanks, I just had to read some more. My comment was not very constructive.

Created proper Pull Request at https://github.com/odoo/odoo/pull/20321

Spent some time yesterday on Odoo example http://lathama.com/odoo_spelling.diff

**Comment by mart-e** [comment]
@lathama thanks, I will check to merge that!

**Comment by fpodoo** [comment]
Wow, looks like a good contribution. Thanks.

**Comment by lathama** [comment]
I am not done with the linked diff, need to double and triple check the unittesting that validates against the text... aka accountants work...

**Pull request closed without merging**
