### PR TITLE
[FIX] website_event_track_*: use is_view_active to benefit of the cache

### PR DESCRIPTION
**Pull request by JKE-be**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
Vu que pas encore installé sur la prod, ca sera deja ca de gagné (+ a fwdporté)

Si on prevoit un -u de website_event alors mieux vaut aussi merger le backport https://github.com/odoo/odoo/compare/saas-13.3...odoo-dev:saas-13.3-event-isview-active-bckpt-jke?expand=1... avec un fwd-bot ignore

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo en fait non

**Comment by MiquelRForgeFlow** [comment]
to merge this PR, runbot should be reseted

**Comment by tde-banana-odoo** [comment]
Will rebase on 14

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
