### PR TITLE
[FIX] Use digits to round float values on client side

### PR DESCRIPTION
**Pull request by adrienpeiffer**
When the user modifies a record in the web client, only the modified fields are sent to the write() method on the server. However, in some cases, with float fields, fields that are not changed by the user are sent to the write() method on the server.

### CODE REVIEW

**Comment by ged-odoo** [comment]
merged in 37e85a1e3520317e5.  (slightly improved to use the framework rounding function).

Thank you for your contribution.

**Comment by rha-odoo** [comment]
@ged-odoo could you please check again if it works? I just checked and the problem is still there.
I tried this #4385 senaio, however the your last commit works and round_precision() did not round the float value?

**Comment by adrienpeiffer** [comment]
@rha-odoo see on 4f14290

**Comment by mart-e** [comment]
@rha-odoo  there were a side effect on the patch that I fixed in 4f14290.
Now your issue is different
```
> self.openerp.web.round_decimals(74750.80000000001, 2)
74750.8
> self.openerp.web.round_decimals(74750.90000000001, 2)
74750.90000000001
```
or more generally:
```
> 74750.80000000001*100
7475080
> 74750.90000000001*100
7475090.000000001
```
It's an issue with the binary representation of numbers (you have the same issue with python). Not sure how we can fix that one.

**Comment by adrienpeiffer** [comment]
@mart-e @rha-odoo @ged-odoo  I think commits on this PR could fix this kind of float binary representation problems. 
```
> value = 74750.90000000001
> rounding_factor = Math.pow(10, 2)
> value = Math.round(value * rounding_factor)/rounding_factor
> value
74750.9
```

**Comment by adrienpeiffer** [comment]
@ged-odoo  #4564 isn't fix with 4f14290

**Comment by mart-e** [comment]
@adrienpeiffer we need a patch for the `round_precision` method. By the way you get the same issue with `float_round` from the orm:
```
>>> from openerp.tools import float_round
>>> float_round(74750.9, 2)
74750.90000000001
```
The issue is that `7475090.0/100` is different than `7475090.0*0.01` due to the binary representation. A quick patch would something like:
```
diff --git a/addons/web/static/src/js/formats.js b/addons/web/static/src/js/formats.js
index 4766fe3..67944bc 100644
--- a/addons/web/static/src/js/formats.js
+++ b/addons/web/static/src/js/formats.js
@@ -350,12 +350,13 @@ instance.web.round_precision = function(value, precision){
     } else if (!precision || precision < 0) {
         precision = 1;
     }
-    var normalized_value = value / precision;
+    precision = 1/precision;
+    var normalized_value = value * precision;
     var epsilon_magnitude = Math.log(Math.abs(normalized_value))/Math.log(2);
     var epsilon = Math.pow(2, epsilon_magnitude - 53);
     normalized_value += normalized_value >= 0 ? epsilon : -epsilon;
     var rounded_value = Math.round(normalized_value);
-    return rounded_value * precision;
+    return rounded_value / precision;
 };
 
 /**
```
but I wouldn't be surprised it breaks other cases.

**Pull request closed without merging**
