### PR TITLE
[FIX] web: node options for formatting should have priority

### PR DESCRIPTION
**Pull request by kebeclibre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
@aab-odoo 
WIP and linked to an opw
To be continued

**Comment by rdeodoo** [comment]
:boom:

**Comment by aab-odoo** [comment]
@kebeclibre ping

**Comment by rdeodoo** [comment]
> To be continued

Or to be closed :yum: 
please check if still relevant or no

**Comment by pedrobaeza** [comment]
Is this still relevant?

**Pull request closed without merging**
