### PR TITLE
[FIX] web: list: show horizontal scrollbar

### PR DESCRIPTION
**Pull request by aab-odoo**
Have a list view with both vertical and horizontal scrollbars. Before this commit, the horizontal scrollbar was only visible on the very bottom (the user had to scroll vertically to the bottom to see it). With this commit, it is always visible.

opw~3897327

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
@fw-bot ignore

**Comment by aab-odoo** [comment]
robodoo help

**Comment by aab-odoo** [comment]
robodoo fw=no

**Review by rfr-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
