### PR TITLE
[FIX] sale_management: fix double menu entry Sales > Configuration > Products

### PR DESCRIPTION
**Pull request by alexis-via**
BEFORE:
double_products_menu_entry

AFTER:
double_products_menu_entry-FIXED

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@awa-odoo any reason to add a specific submenu? It seems ok for me to merge both

@alexis-via please do not remove the menu `menu_product_settings`. If it is no longer used, it won't be displayed.
However, if somebody used it in his module, he will get an error if you remove it.

**Comment by sswapnesh** [comment]
@mart-e 
Isn't it better to handle this in master only ? (As It is IMP rather than FIX)

**Comment by pedrobaeza** [comment]
Dual menu can be considered as a bug, so I prefer in stable leaving the other menu without children (which hides it).

**Comment by tanghulu0608** [comment]
How about add Product Category menu too ?

**Comment by awa-odoo** [comment]
@mart-e Yes the menus should be both merged.

I guess we should leave the `menu_product_settings` in 12 and make another PR to clean it in master then?

**Comment by mart-e** [comment]
@robodoo r+

**Pull request closed without merging**
