### PR TITLE
[IMP] (account, payment): payment method improvements

### PR DESCRIPTION
**Pull request by vin-odoo**
To improve the payment method system, proceed to a few changes
such as adding a setup button to directly open the acquirer form from the
journal, and changing the style of lines linked to a disabled acquirer.

Task id #2573145

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by AntoineVDV** [comment]
Hello @vin-odoo, is there a task to follow? If so, could you reference it in the commit message? Thanks!

**Comment by vin-odoo** [comment]
Hi @AntoineVDV, these changes are based on feedback given to me directly by @tsb-odoo and AVW.
As far as I know, there is not task for them.

**Comment by tsb-odoo** [comment]
Hi @AntoineVDV, let me know if the absence of task is a blocking point. 
cc : @vin-odoo

**Comment by AntoineVDV** [comment]
@tsb-odoo @vin-odoo This is not blocking but it would still be a good idea to create one, even after the dev is done. To have an entry in the release notes is already a good reason on its own. One might also need to understand and discuss this change in a few months/years.

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
Please find a few review comments below :)

Also, your commit title should start with "[IMP] payment" rather than "[IMP] account" since this is the module that is modified.

**Review by AntoineVDV — APPROVED** [review]

**Comment by vin-odoo** [comment]
It was decided that these fixes were really important and thus should be done in 14.4

**Pull request closed without merging**
