### PR TITLE
[REM] l10n_in: delete dead code

### PR DESCRIPTION
**Pull request by yelizariev**
both methods don't exist anymore and not used

### CODE REVIEW

**Comment by yelizariev** [comment]
@jva-odoo

**Comment by jva-odoo** [comment]
@yelizariev Yes, not needed
because it's replaced by 
_get_tax_key_for_group_add_base
_get_tax_grouping_key_from_tax_line
_get_tax_grouping_key_from_tax_line

**Comment by yelizariev** [comment]
@jco-odoo, kind reminder

**Comment by yelizariev** [comment]
Screw it

**Comment by jco-odoo** [comment]
@yelizariev it was planned to remove idd. (so not sure if we have it already somewhere else)

**Pull request closed without merging**
