### PR TITLE
[REF] point_of_sale, *pos*: renaming cashier, partner and customer

### PR DESCRIPTION
**Pull request by trj-odoo**
Multiple refactors
- The module pos_hr had two attributes `cashier` and `employee` referencing to the same actual person. The `employee` attribute was removed for the sake of `cashier`.
- Refactor of the `useSelectEmployee` which returned functions that where used in two components. Instead, a mixin class was implemented and inherited from both components.
- Renaming of the substring `client` and `customer` to `partner` (css included) when it was referencing to the actual `res.partner` object. This way, developers will always know that the object used in the UI is coming from `res.partner`.
- Renaming of the substring `client` to `customer`(css included) when it was referencing to a real life person. This avoid having ambiguity since the term `client` can refers to multiple things (hardware, browser, person, ...)

### CODE REVIEW

**Comment by caburj** [comment]
I feel like we shifted from having "customer-client" to having "customer-partner". What if we go "customer" all the way. This means we also rename `partner_id` field to `customer_id`. (Or we go "partner" all the way.)

**Comment by trj-odoo** [comment]
> I feel like we shifted from having "customer-client" to having "customer-partner". What if we go "customer" all the way. This means we also rename `partner_id` field to `customer_id`. (Or we go "partner" all the way.)
Yeah but now it's less ambiguous. We now know what refers to what. There are case where `partner` didn't feel right such as `CustomerFacingDisplayOrder` due to the `iface_customer_facing_display` or `_sendReceiptToCustomer()` where we don't send the receipt to the partner's mail but to any mail (that might not be related to a `res.partner` record)

**Comment by caburj** [comment]
@trj-odoo After second scan, I get what you mean. We are now using `partner` mainly. But, can you explain why you decided on renaming these methods: `take_ownership_over_customer_screen`, `test_ownership_of_partner_screen`? Why didn't you use `customer` for both?

**Comment by trj-odoo** [comment]
>  Why didn't you use customer for both?

This right here is a mistake, my brain melted from seeing too much client, customer and partner

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Comment by pimodoo** [comment]
@trj-odoo Hello conflict

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
