### PR TITLE
[FIX] l10n_latam_invoice_document: the gaps message does not make sen…

### PR DESCRIPTION
**Pull request by jco-odoo**
…se for LATAM journals

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@chklop @vbe-odoo @ren-odoo @fvz-odoo I don't understand that such obvious things do not get solved.  The gaps message does not make any sense for latam journals, but it is there on every accounting dashboard.

**Review by william-andre — COMMENTED** [review]
Shouldn't `<account.move>.made_sequence_hole` be disabled too then? (to avoid the red color of the name on the list view)

**Comment by jco-odoo** [comment]
@william-andre made_sequence_hole added and tested by @vbe-odoo

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Comment by oco-odoo** [comment]
@fw-bot up to saas-16.4
(backport from a fix made in 17.0)

**Pull request closed without merging**
