### PR TITLE
15.0 fix fix fix yti

### PR DESCRIPTION
**Pull request by tivisse**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by tde-banana-odoo — COMMENTED** [review]
LGTM
  * removing automatic call in a compute are effectively a good idea. Better have manual updates (user or flow based) than automated calls to an external service;
  * override of _prepare_customer_values is correct and is the right way to do it, good idea;

**Review by odony — APPROVED** [review]
Thanks! C'est tout comme il a dit @tde-banana-odoo

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff

I always thought ``1 + 1 = 3`` but today you proved to me that the answer is ``4``. :kissing_heart:

**Comment by tivisse** [comment]
@fw-bot ignore

**Pull request closed without merging**
