### PR TITLE
[IMP] google_calendar: generate meeting link when creating event

### PR DESCRIPTION
**Pull request by pimodoo**
When we are creating an event in odoo and synchronise it with google, the google meet link is not automatically generated. To ease the use of the meeting, we'll auto generate the google meet link.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pimodoo** [comment]
@LucasLefevre coucou, j'ai fais un petit changement afin de générer un lien google meet lors de la création d'un event. Mais j'ai des tests qui petent et je suis pas sûr de savoir trop pourquoi. T'aurais pas une petite idée?: https://runbot.odoo.com/runbot/build/23111132

**Review by LucasLefevre — COMMENTED** [review]
Hello @pimodoo :slightly_smiling_face: 
Looks like there's two requests sent to Google API instead of one. Don't know why though.
Nothing looks louche to me in the PR.

Summon @arj-odoo who is the rightful code owner now :)

**Comment by pimodoo** [comment]
@arj-odoo Hello, do you think it could be an option to remove the 'assert_called_once' in the insert tests where it raises an error?

**Comment by arj-odoo** [comment]
> @arj-odoo Hello, do you think it could be an option to remove the 'assert_called_once' in the insert tests where it raises an error?

Hi, it is strange, I fetched and rebased your branch et run the tests locally. I had another error. 
The issue I got was that the self.assertGoogleEventInserted values were missing the conferenceData values you are inserting in _google_values.
 `GoogleSync._google_insert.assert_called_once()` is passing for me. But as you are inserting random data with uuid4, we should have a way to allow to make sure that the `'conferenceData': {'createRequest': {'requestId': XXX}},` key is present but not check the requestId value :thinking: We could modify assertGoogleEventInserted to pop the conferenceData values before calling assert Equal.
 
 

```diff
  ({'attendees': [{'email': 'jean-luc@opoo.com',
                   'responseStatus': 'needsAction'}],
-   'conferenceData': {'createRequest': {'requestId': '5ea4a4d3fced4c8eabc2c08c6811a420'}},
    'description': '',

```

**Comment by pimodoo** [comment]
> > @arj-odoo Hello, do you think it could be an option to remove the 'assert_called_once' in the insert tests where it raises an error?
> 
> Hi, it is strange, I fetched and rebased your branch et run the tests locally. I had another error. The issue I got was that the self.assertGoogleEventInserted values were missing the conferenceData values you are inserting in _google_values. `GoogleSync._google_insert.assert_called_once()` is passing for me. But as you are inserting random data with uuid4, we should have a way to allow to make sure that the `'conferenceData': {'createRequest': {'requestId': XXX}},` key is present but not check the requestId value thinking We could modify assertGoogleEventInserted to pop the conferenceData values before calling assert Equal.
> 
> ```diff
>   ({'attendees': [{'email': 'jean-luc@opoo.com',
>                    'responseStatus': 'needsAction'}],
> -   'conferenceData': {'createRequest': {'requestId': '5ea4a4d3fced4c8eabc2c08c6811a420'}},
>     'description': '',
> ```

Thanks it seems to work.

Are you okay with this change? (generate meeting when we have a google sync)

**Comment by pimodoo** [comment]
And do you think I can backport it in 16.1?

**Review by arj-odoo — APPROVED** [review]
I am OK with the change, even in 16 or 16.1 if needed. 
If I understand well, this change force the creation of a conference at event creation. We don't use that data in Odoo but it makes sure that in Google, the conference feature can be used. This external link explain the issue and the solution (same as yours) :-).
https://issuetracker.google.com/issues/167260246?pli=1

**Comment by pimodoo** [comment]
> I am OK with the change, even in 16 or 16.1 if needed. If I understand well, this change force the creation of a conference at event creation. We don't use that data in Odoo but it makes sure that in Google, the conference feature can be used. This external link explain the issue and the solution (same as yours) :-). https://issuetracker.google.com/issues/167260246?pli=1

In Odoo it'll just set the videocall_location with the meeting link, as when events are imported from google the ConferenceData are set in this field.

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
