### PR TITLE
[FIX] lunch: allow order from different location

### PR DESCRIPTION
**Pull request by fdamhaut**
Step to reproduce:
- Have the same menu items in the different locations
- Order one item for Office 1 click " Order now"
- Choose different office
- Select the same item

Current Behaviour:
- There is no 'Order now' and you can see that both orders were made
from Office 1.
- If you select two different items, you can click 'Order now' twice,
but there is no button if items are the same

Behaviour:
- If you change location before adding an item already present
 you create a new line link to the new location and the 'Order now'
 button is present

opw-2769168

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fdamhaut** [comment]
@kba-odoo

**Comment by kba-odoo** [comment]
hey @fdamhaut, is it only occurring in 15.0? I'm wondering if this fix shouldn't be done from 13.0 onwards. Thanks!

**Comment by fdamhaut** [comment]
> hey @fdamhaut, is it only occurring in 15.0? I'm wondering if this fix shouldn't be done from 13.0 onwards. Thanks!

:wave: @kba-odoo 
Before 15.0, the location of the lunch was stored on the user so, changing it between 2 orders would then update the 1st order
(change made here : https://github.com/odoo/odoo/commit/d7ddd5de53a9601be2fdafc7a8751c6119d2a90a)

**Comment by kba-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
