### PR TITLE
[IMP] l10n_il: add new tax rates for 2025

### PR DESCRIPTION
**Pull request by yediel**
Israel is raising VAT rate from 17% to 18% on 1/1/2025.

Changes:
- Added new taxes (17% -> 18%)
- Archived 17% taxes
- Added tax group (VAT 18%)
- Modified fiscal position to match those taxes
- Modified VAT report to include VAT Inputs 18%
- Updated default tax ids for IL res.company

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yediel** [comment]
This should be live as close as possible before 1st of January 2025

**Review by william-andre — COMMENTED** [review]
Hello, I believe it should be simpler as some parts need to be handled manually by the users.

I made a PR giving more details on how the rates should be updated here https://github.com/odoo/odoo/pull/191237  (it might be added to the documentation as well, probably a new section here https://www.odoo.com/documentation/18.0/developer/howtos/accounting_localization.html)
It is not final and up for discussions, but here is what I will probably ask to change:
- update the rates from 17 to 18 in `account.tax-il.csv`, don't keep the old rates. They won't be deleted when updating the Chart of Accounts.
- the `active` flag won't work anyway, we only create new taxes and update the tax tags when updating the chart of accounts
- You can remove the tax group as well. Again, it won't be deleted if it existed before.


In any case, thanks for the contribution!

**Comment by william-andre** [comment]
I also notices that you didn't sign the CLA yet (at least with you committing address)
You can add a new commit in this branch to do that, like explained here https://github.com/odoo/odoo/blob/master/doc/cla/sign-cla.md

**Comment by yediel** [comment]
> I also noticed that you didn't sign the CLA yet (at least with you committing address) You can add a new commit in this branch to do that, like explained here https://github.com/odoo/odoo/blob/master/doc/cla/sign-cla.md

Its here:
https://github.com/odoo/odoo/pull/191212

**Comment by william-andre** [comment]
I approved the CLA PR, you will need to rebase this one once it is merged for the CI to be green

**Comment by nitzanhen-retama** [comment]
@william-andre We need to keep the old set of taxes as part of Israeli localization because in some cases, Invoices and vendor bills will be generated in January 2025 and document deals from December 2024 (which will require the old rates)

If I took your advice and delete the old rates, and set up a new company after this PR is approved & merged, I wont be able to use the old rates because they won't be generated at all.

as a future step later in 2025 I agree with you that the old rates should be removed from the localization

**Comment by william-andre** [comment]
@nitzanhen-retama if you look at my previous comments, that is exactly what I'm asking to do

**Comment by nitzanhen-retama** [comment]
@william-andre I read your previous comment, you mentioned it won't be deleted if it **existed before**.
If we change the rates from 17 to 18 and remove the tax group as you suggest. and then launch a new project on Odoo.sh in the beginning of 2025 (which is a use case we actually face), the old taxes won't be set up in new environments when installing the localization since they no longer exist in the code.

btw we used this tax update as a reference: https://github.com/odoo/odoo/commit/3acaed16a42ed6a9c926db3f644e5a942be4f0be#diff-0543402776e0eb6f40b0424d1964617dcbcc578dc614faf70393fad7a97e223d

**Comment by william-andre** [comment]
If that's the case, just duplicate the 18% tax you need and change it's percentage. This is an exception and should be treated as such.

**Review by william-andre — COMMENTED** [review]
The diff is good for me :+1: 

Could you please squash all your commits, making sure that the commit message reflects the last changes? This the CI detects.

**Comment by william-andre** [comment]
@nitzanhen-retama I won't be able to merge if you don't squash your commits even if I wanted :/

**Review by william-andre — APPROVED** [review]
Thank you for your work and your contribution !
@robodoo r+

**Comment by hedshefer** [comment]
@william-andre 
Tested on both V17-18. Changes seems to be valid.
Backward-port in this PR: https://github.com/odoo/odoo/pull/191749

**Pull request closed without merging**
