### PR TITLE
[IMP] l10n_co: actualizing CoA

### PR DESCRIPTION
**Pull request by blaggacao**
Replaces https://github.com/odoo/odoo/pull/11753

This commit makes available a reviewed and updated chart of accounts. In order not to break existing installations, we make both available, the old and the new one. For the sake of colombian ecosystem and localisation, it is preferable to have the new one published in order to be able to consolidate further efforts on more specific topics.

We also include account tags which can be used to construct fiscal reports.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by blaggacao** [comment]
@mart-e We are really keen on getting this trough to solve our underlying issue: We spent a lot of work because people come to us asking for support, but we do not support any more the ancient CoA as we have noticed it is not complete and cannot be improved. We started from 0 for our internal localisation modules. With this we can leave the choice to the users and can at least say: You must choose the new coa in order to be compatible with our localisation.

**Comment by mart-e** [comment]
Hello,

Thanks for the big refactoring.
If the previous is wrong, we can remove it as you are in master. I don't want to have a module called "old" in the list of addons :)

**Comment by blaggacao** [comment]
I completely agree with the benefits of deprecating/removing the "old" l10n_co. It was constructed that way in order to maintain certain backwards compatibility. But As you say, this is probably the wrong concern when talking about master.

I'll replace it, instead. 

On the other hand, I have some preference for leaving the common structure and present the new CoA as `l10n_co_comerciantes` because financing and government/military institutions have a completely different CoA (requested by law).

Odoo is fairly common in the government/rural sector and is also an interesting alternative for agricultural financing cooperatives. Those all try to start with the community version and see, that here is no CoA for them and then probably might turn away from the product.

It would be in the best interest of the Colombian Overall Product Strategy to give us, DevCO Colombia, the chance to easily provide different CoAs in the future. It is strategically important to get the DIY/community set up right in order to facilitate later migrations towards enterprise, as needs outgrow the CC version.

We are prospecting with government/military and they cannot reuse the "PUC DE COMERCIANTES NIIF" as represented in this PR.

It later on, as we proceed in our knowledge about CoA intricacies in different sectors, we could incorporate the common accounts also in the common structure, but at this point in time, we have no reliable judgment on this, setting up the basic "infrastructure" however is important: strategically and communicational/expectational.

/cc @qdp-odoo

**Comment by tivisse** [comment]
Hello @blaggacao 

So if I'm not wrong, what you propose is to keep the `l10n_co` module as it is and create a new module `l10n_co_comerciantes` with all your new modifications right ? 

Thanks.

**Comment by blaggacao** [comment]
@tivisse Actually, what I propose is tostrip down l10n_co to the bare minimum, in order to be able to chose from different sectoral- or topic- COAs later on.

So:
`l10n_co` would just contain the bare minimum
whereas other modules, like `l10n_niif` would contain the actual relevant COA.

We are evolving our concepts constantly so please have a look at this as well: https://github.com/odoo/enterprise/pull/1011

Combining the ideas together we can have a flexible support for multi-standard reporting.

**Comment by tivisse** [comment]
@blaggacao 

Could you create another PR considering the following points:
- No module `foo_old`
- All modules related to the Colombian localization should begin by `l10n_co`
- How your second module should be installed / configured ? Generally the localization modules are automatically installed. cc @qdp-odoo 

Ok to strip down the original module, could you resolve conflicts and update your branch ? 

I close this PR while waiting you to create a new one. 

Thanks,

Yannick.

**Comment by blaggacao** [comment]
Ok, give me some time... I'm a little busy atm.

**Comment by qdp-odoo** [comment]
FYI: we have already internal PR to review l10n_co

https://github.com/odoo/odoo/pull/17541
https://github.com/odoo/enterprise/pull/1098

I'd suggest to start from those if you wanna improve anything.

**Comment by blaggacao** [comment]
... 6 months later. 👎 
My collaboration experience seems to be the the only thing which might keep me motivated, so let's probably agree on that it's halfway important? @fpodoo

**Pull request closed without merging**
