### PR TITLE
[FIX] account: correct check of BBA before write

### PR DESCRIPTION
**Pull request by nim-odoo**
vals['reference'] only rewritten if provided as input

opw: 629649

### CODE REVIEW

**Comment by beledouxdenis** [comment]
The same code is applied in the above 'create' method: Shouldn't you apply this fix in the create method as well ?

**Comment by nim-odoo** [comment]
Indeed, the same issue can occur for the create method. The fix has been applied.

**Comment by nim-odoo** [comment]
Is it ok to merge?

**Comment by beledouxdenis** [comment]
I am just not sure of the 
if vals.has_key('reference'):
    vals['reference'] = bbacomm

Either explain or lemme re-check if this is actually needed or not :D.

**Comment by nim-odoo** [comment]
I kept that part to be sure that vals['reference'] is updated with the formatted reference, as it is the case now. However, I don't have a particular example in mind where vals['reference'] would be sent not formatted.

**Comment by odony** [comment]
Hi, Could you reconsider this fix from scratch?
- [ ] I don't think any change is needed in `create` as there is no loop, so no bug
- [ ] In `write`, you're kind of missing the big picture. The problem arises because the code **always** checks the BBA reference, even when it was not modified. I suspect it comes from a copy/paste of the `create` code in the original implementation. 
If you simply make sure we only verify the BBA comm **when it changes**, then there won't be any problem. Basically the main test should become `if reference_type == 'bba' and 'reference' in vals:` and the rest can be simplified accordingly. This will save useless checks for every `write` on invoice. If someone ever calls `write` with multiples IDs and a `reference`, the uniqueness check will of course fail, and that's the expected behavior. 

Thanks!

**Comment by nim-odoo** [comment]
Thank you for clearing this up! The code is updated.

**Comment by odony** [comment]
Excellent, thanks!

**Pull request closed without merging**
