### PR TITLE
[FIX] sale_coupon: prevent the addition of reward line on copy

### PR DESCRIPTION
**Pull request by jvnm-dev**
This commit is the fw-port of https://github.com/odoo/enterprise/commit/012bd1cc65752c02e88d07e6b7f830b8fec4b1d2.

OPW-2227968

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
@nim-odoo

**Comment by nim-odoo** [comment]
I would keep the complete commit message. Indeed, people might not have access to the Enterprise repository to read it.

**Comment by nim-odoo** [comment]
robodoo delegate+

**Comment by jvm-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
