### PR TITLE
[FIX] Delaying update quantity in website_sale 

### PR DESCRIPTION
**Pull request by PCatinean**
Impacted versions:
- 8.0

Steps to reproduce:
1. Update quantity by incrementing rapidly

Current behavior:
- When updating quantity in website_sale module it triggers a request per each update, thus when somebody frantically increments/decrements the quantity using mouse clicks it floods the server with as many requests

Expected behavior:
- One request should be sent at "the end" of the quantity update 

This fix adds a half-second delay to quantity updates in order to preserve bandwidth and server load but still updating "real-time"

CC: @mart-e

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Seems like a good idea indeed. It seems your branch is conflicting with current 8.0. Could you rebase it ? (this way you would get CLA check as well)
Thanks

**Comment by PCatinean** [comment]
Hello Martin,

I have updated the PR, it generates a wierd diff because of the indentation but it seems to work okay and runbot passed + manual test did not reveal any errors

Let me know if I can do anything else

**Comment by PCatinean** [comment]
Hi Martin,

I have updated the PR, it seems to generate a wierd diff because of the indentation.

Otherwise it seems to work well and Runbot has passed but it looks like if you are quick enough to change the quantity of a second product in the cart before the first is updated (less than half a second) the overall quantities are not updated

**Comment by nim-odoo** [comment]
Maybe solved by 4d7671a4c355b33aa75a2aa81d3ea84ce164538f ?

**Comment by mart-e** [comment]
At e5602afb6d783ff869daf7e6df3e2bc79b3e86cb I think.
The ugly diff is because this branch is an OCB branch submitted against odoo (which differ a lot)

**Pull request closed without merging**
