### PR TITLE
Master ecommerce design fix sri

### PR DESCRIPTION
**Pull request by stefanorigano**
Description of the issue/feature this PR addresses:

Fix several issues, add some improvements

enterprise pr: https://github.com/odoo/enterprise/pull/22231
task#2667024

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@stefanorigano I can answer specific questions of course but to review new 500LOC-diff PR about the eCommerce, I think it's better to send it to the eCommerce team directly. Again, of course, if they have specific questions about some parts, I can have a look.

Running over the PR at a high-speed scroll rate, I did not see something really scary though :smile:

**Comment by stefanorigano** [comment]
Hello @tivisse , the PR I talked you about.

All tests have been adapted, except one.
`test_01_website_sale_comparison_remove`  reference the `product_add_to_compare` template that has been removed during my refactoring.
I have not proceed further 'cause my gut tells me that this entire test could be removed now, it's probably better if a dev have a look into it ;)
 
https://github.com/odoo-dev/odoo/blob/master-ecommerce-design-fix-sri/addons/website_sale_comparison/tests/test_website_sale_comparison.py#L49

Thanks!

**Comment by tivisse** [comment]
@stefanorigano Thanks for your work ! :)

Actually, the test is still useful, because it ensures that the product page still works after the module website_sale_comparison has been uninstalled.

So I'll adapt it, and also write the migration script, which seems to be missing. 

Have a nice day,

Yannick.

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
