### PR TITLE
[FIX] sale_stock: prevent displaying vendor's info in DO

### PR DESCRIPTION
**Pull request by yosa-odoo**
Steps to reproduce:
- Activate Dropship and multi routes
- Create a SO and select the route Dropship
- Confirm the SO
- Confirm the purchase
- Click on Customer Preview

Issue:
In the customer preview, if the customer click on the do, vendor's info will be displayed.

opw-2961884

### CODE REVIEW

**Comment by yosa-odoo** [comment]
@fw-bot ignore

**Review by nle-odoo — COMMENTED** [review]
intention looks good to me

note: the indentation  seems a little wonky, it should  be 4 space per indentation (it is also causing some more diff because of whitespace)

here we are possibly breaking customization with xpath the two changes elements, but it would be a little more ugly to duplicate the code :thinking:

**Comment by yosa-odoo** [comment]
> here we are possibly breaking customization with xpath the two changes elements, but it would be a little more ugly to duplicate the code thinking

I could minimize the changes. But if I do so, the title "delivery orders" will appear when there are no orders.

**Review by DjamelTouati — APPROVED** [review]
LGTM! Thank you for the fix
Already fixed in V15: https://github.com/odoo/odoo/pull/88464/commits/46f78130fab7e6b670e31f87a8eab7ca922efb21

**Comment by DjamelTouati** [comment]
robodoo delegate+

**Comment by nle-odoo** [comment]
partial backport, but with a little more change in structure to not see the title

robodoo r+

**Pull request closed without merging**
