### PR TITLE
[FIX] project: create task from assigned task

### PR DESCRIPTION
**Pull request by fdamhaut**
Step to reproduce:
- Go to ‘my profile’
- Action "assigned tasks"
- Create task

Current Behaviour:
- Traceback because default assignee is not correclty set up

Behaviour after PR:
- Correct default assignee
- No traceback

opw-2742199

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fdamhaut** [comment]
@IT-Ideas

**Comment by IT-Ideas** [comment]
@robodoo r+

**Comment by IT-Ideas** [comment]
Thanks for the fix @fdamhaut

**Comment by IT-Ideas** [comment]
@robodoo r+

**Pull request closed without merging**
