### PR TITLE
[FIX] barcode : test if int before conversion

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
With some barcode, it takes an error

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

What do you mean "with some barcode"?
If you have a test barcode, giving it in the PR may be a good idea.

**Comment by fmdl** [comment]
The history is  : I am developing an module to create a picking with barcode scanner (create stock.move in Initial Operation). (otherwise, there an bug : the function new() doesn't work correctly :  some field stay empty with stock.move model. I try to find where is the issue and I prepare an PR or issue).

But during the test I have this issue with barcode IGY11849. The trackback is "Y1" cannot be convert in int. Process to do the error : On picking in state available, in edit mode, scan "IGY11849".

`File "server/addons/barcodes/models/barcodes.py", line 148, in parse_barcode
    match = self.match_pattern(cur_barcode, rule['pattern'])
  File "server/addons/barcodes/models/barcodes.py", line 107, in match_pattern
    match['value'] = int(whole_part) + float(decimal_part)
ValueError: invalid literal for int() with base 10: 'Y1'`

**Comment by mart-e** [comment]
And what is the nomenclature you are using? It may be that the barcode nomenclature does not match the given code.

**Comment by fmdl** [comment]
I use the default nomenclature

image

**Comment by mart-e** [comment]
Ok now, I see, the issue comes from the point of sale barcode rule 'Discount Barcodes'. 
As you are now making frequent pull request, please, try to describe properly your issues. It would have save us useless searching and exchanges here.

I think we should make a fix earlier than your patch, when seeing that the given barcode does not match the pattern `22{NN}`
@sle-odoo opinion?

**Pull request closed without merging**
