### PR TITLE
10.0-CLA updating for LevelPrime srl

### PR DESCRIPTION
**Pull request by FilippoIOVINE**
I have signed and updated the CLA for LEVELPRIME srl

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Why do you add two email addresses ? You only need the address you are using to make commits (usually the corporate email address)

**Comment by FilippoIOVINE** [comment]
Hi,
I use both github accounts to work on Odoo projects.

**Comment by mart-e** [comment]
Both github accounts or both email addresses? Because you specified the same account  FilippoIOVINE for both emails (just want to be sure everything is correct before merging)

**Comment by FilippoIOVINE** [comment]
yep, I have both emails tied to the same github account (FilippoIOVINE).

**Comment by mart-e** [comment]
Thanks for the information, ok for me then :+1: 

robodoo r+

**Pull request closed without merging**
