### PR TITLE
[MERGE] Forward port of saas-12.3 to saas-12.4 up to 40421be73c94551b

### PR DESCRIPTION
**Pull request by mart-e**

### CODE REVIEW

**Comment by mart-e** [comment]
Changes that were dropped as in `account/models/account_invoice.py` (which no longer exists in saas-12.4)

674ee035ca954a57341cbaa951d2f6f31b5f8fe2 by @kebeclibre
d0f3e896d4d29e60e818b806599421be557556cc by @simongoffin
0481b06131e870c95fe35e5263f907a117be726d by @mart-e

**Comment by mart-e** [comment]
@robodoo merge review+ priority=0

**Comment by mart-e** [comment]
@robodoo retry

**Comment by mart-e** [comment]
@robodoo retry

**Comment by mart-e** [comment]
@robodoo r+ merge p=0 ? At least, don't let @dbo-odoo merge its PR

**Comment by mart-e** [comment]
@robodoo don't you dare, retry or I will merge it myself

**Comment by dbo-odoo** [comment]
@mart-e lâche

**Pull request merged**
