### PR TITLE
[IMP] account: speedup the COA installation

### PR DESCRIPTION
**Pull request by smetl**
Tested with l10n_es COA (completo):

before:
+- 22000 queries in +- 12 seconds

after:
+- 6000 queries in +- 4 seconds

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@robodoo r-

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@d-fence can you tell me why @robodoo thinks this PR sucks? the failure of the build doesn't seem related to my commit ? Should I order it to retry?

**Comment by d-fence** [comment]
Unfortunately it's a false negative, a non deterministic failure.
And Robodoo is not (yet) able to distinguish if the failure comes from your changes or not.
@robodoo retry and ignore false negative please

**Comment by qdp-odoo** [comment]
@robodoo r- 

actually, a similar work has been done by @rco-odoo (sigh) ... and he eventually go even further in the optimization so we'll probably keep his work.

**Pull request closed without merging**
