### PR TITLE
[IMP] mail: add a simple and secure method for putting messages in th…

### PR DESCRIPTION
**Pull request by jco-odoo**
…e chatter

In a lot of cases e.g. in account and its localizations, we just need
to put a simple message in the chatter to have a history of what happened.

The current methods in mail are complex to understand for no reason as most
people just use the default params.

At the same, there is the danger of forgetting to html_escape strings.

That is why we define 2 easy to use methods _msg_txt and _msg_html.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@odony @xmo-odoo Suggestion for a small addition to the api.  (not tested)  It is that @tde-banana-odoo asked to change message_post into _message_log and it seemed like an opportunity to improve the api a bit.  Maybe you have a better idea for formatting than "%s" % , but dicts seem complicated as well.

**Review by tde-banana-odoo — CHANGES_REQUESTED** [review]
Hello,

Message post and chatter use html. Using text input is only a side-artefact of custom code. You may call _message_log or message_post using html_escape if you feel it is necessary. All content is considered as being html, even simple html like ``<p>This is my note</p>``.

MailThread offers a simple api

  * message_post: a complete html post processing, with notifications, recipients management, subscription of author. Generally used for content that is meant for customers. Kwargs are explained in docstrings
  * _message_log: quickly log a message on a document without notifying people and lessening queries through a simple behavior. Mainly used as self._message_log(body=my_body).
  * _message_notify: notify a user for an action to perform related to a document, without posting something on the document itself. Used for example to remind from activities.

Your added methods just add a new layer on top of this official API. Moreover naming is very poor and leads to confusion. I don't see the point of adding those in mail.

You may use them in your addon if you want obviously.

Cheers,

**Comment by jco-odoo** [comment]
@tde-banana-odoo You see the simplicity of that but we are mere simple accountamatatas and all the options confuse us for no reason, while we have a first param nobody knows why it is optional.  Why not do a _message_log_txt and _message_log_html then?  At the same time, we would incorporate security best practices in the api.  You clearly suppose that people take them into account, but that is not what happens in practice.  If people would just see that in places in the code, they will think about it sooner.

**Comment by tde-banana-odoo** [comment]
@jco-odoo In order to simplify understanding of message_post, even for simple accountamatatas, support of plaintext body has been dropped at https://github.com/odoo/odoo/commit/74d4b3902d51bf805f87bfd853f54407137b0ac3 . Especially ``This commit removes the parameter and consider the content is always html. Code calling message_post should handle the conversion.`` .

Using html_escape or plaintext2html is the responsibility of the caller, not MailThread itself. All content of message body is considered as being HTML. There is no reason to support giving plaintext to message_post, making people think we support plaintext-like posting, messaging or emailing mechanism.

You have to consider that if you have issues understanding the purpose of 3 main posting methods, it won't help you adding a fourth and fiftth one. Other accountamatatas will not understand them and ask for a sixth one with their own use case.

Obviously if there are use cases I did not understand feel free to explain them more in details. Currently I don't see the added value of those new methods.

Cheers,

**Comment by jco-odoo** [comment]
@tde-banana-odoo If you don't want them here, I will add those to account_edi at least.  The idea about text is not to allow people to read the mails in pine, but to avoid special formatting.

**Comment by jco-odoo** [comment]
@tde-banana-odoo Small problem: you cannot do attachments in _message_log...

**Comment by jco-odoo** [comment]
I still think it is good to challenge apis, but better in another way then? @tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
Hello @jco-odoo ,

Actually you can log with attachments, like ``record._message_log(body='pouet', attachment_ids=my_attachment.ids)``. What would do you want on top of that ?

**Comment by tde-banana-odoo** [comment]
About text/html, actually you are right that your content should be valid html (and beware markup / escaping). We are thinking of a possible solution when people want to log formatted text using arbitrary input, as they often forget about markup and escaping. But it will probably not be another API method, still unsure which form it would take.

Cheers !

**Comment by jco-odoo** [comment]
@tde-banana-odoo Maybe there is a way to replace most message_post with _message_log then still?

**Comment by tde-banana-odoo** [comment]
That's the job of functional teams to know if they want to post (and notify people) or log. I will not choose for people that knows functional flows better than me :)

I bet a bunch of posts are actually logs, but I am not the expert of all addons :)

**Pull request closed without merging**
