### PR TITLE
[FIX] account: update website URL

### PR DESCRIPTION
**Pull request by thcl-odoo**
### Current behavior
"Learn More" link redirects to 404 page

### Steps
- Go to Apps
- Search for Invoicing
- Click on "LEARN MORE"

OPW-2743304

### CODE REVIEW

**Comment by agr-odoo** [comment]
there is the same issue in v13 as well, so let's rebase & retarget

**Comment by thcl-odoo** [comment]
this is what I thought but it isn't really the case:
addresses have been updated from v15 with this commit a65f6a58724c23c3ee2ff354d0e80aa9dc4287e7 (mainly replacing `/page/` by `/app/` ).

So for v13, v14 : Link is pointing to https://www.odoo.com/page/billing which redirects to https://www.odoo.com/app/invoicing.

If I change this address from v13, I'd have to change all of them to keep consistency, is this necessary while previous url are working?

**Comment by agr-odoo** [comment]
@thcl-odoo 
you are correct, I misread
robodoo r+

**Comment by agr-odoo** [comment]
robodoo r+

**Pull request closed without merging**
