### PR TITLE
[FIX] pos_hr: Select user promise

### PR DESCRIPTION
**Pull request by switch87**
Since refactor to promise selecting a PoS user would throw a traceback
due to the use of this inside a Promise function.

This fix replaces this by self, resolving the problem.

### CODE REVIEW

**Comment by pha-odoo** [comment]
ok

**Comment by switch87** [comment]
@qle-odoo r+

**Comment by qle-odoo** [comment]
@robodoo r+

**Comment by qle-odoo** [comment]
@robodoo retry

**Comment by qle-odoo** [comment]
@robodoo r+

**Comment by qle-odoo** [comment]
@robodoo retry retry retry

**Comment by qle-odoo** [comment]
@switch87 can you rebase / rebuild this branch.

**Comment by switch87** [comment]
> @switch87 can you rebase / rebuild this branch.

@qle-odoo done :+1:

**Comment by qle-odoo** [comment]
@robodoo r+

**Comment by qle-odoo** [comment]
@switch87 why there 2 commit ?

**Comment by switch87** [comment]
> @switch87 why there 2 commit ?

It's something git did with rebasing. you can do robodoo merge

**Comment by switch87** [comment]
@qle-odoo can you try again to make robodoo listen to you?

**Comment by switch87** [comment]
@qle-odoo You can stop the struggle with robodoo, @jorenvo merged the same change previous week.

closed by  #32860

**Pull request closed without merging**
