### PR TITLE
[FIX] hr_holidays: bring back the out of office panel in threads

### PR DESCRIPTION
**Pull request by xdu-odoo**
task-2277511

### CODE REVIEW

**Comment by xdu-odoo** [comment]
@odoo/rd-discuss

**Comment by seb-odoo** [comment]
It is a fix (for 14.0 then) or just a code clean up?
What issues did you notice while investigating the task?

**Comment by xdu-odoo** [comment]
In fact I'm wondering how it could even work before this PR. I didn't check it was working by the way.
There are lot of new files and assets are changed so if we do a fix that means migration... Maybe we could backport if it's reported ?

**Comment by seb-odoo** [comment]
If we must do in stable we should use bugfix files to avoid adding new files, we can't do a migration now.

**Comment by xdu-odoo** [comment]
I confirm, it does not work in 14.0

**Comment by xdu-odoo** [comment]
image

**Comment by seb-odoo** [comment]
Well then it looks like 14.0 must be the target, try minimal diff without new files, using bugfix files if necessary.

**Comment by xdu-odoo** [comment]
And I cancel this PR or we keep it for master ?

**Comment by seb-odoo** [comment]
Cancel the PR but keep the diff somewhere, we'll need re-apply it at forward port into master.

**Comment by xdu-odoo** [comment]
see https://github.com/odoo/odoo/pull/61586 for the end of the story

**Pull request closed without merging**
