### PR TITLE
 [FIX] website_{profile, forum}: migrate events from forum to profile

### PR DESCRIPTION
**Pull request by mgh-odoo**
**Task**: https://www.odoo.com/web#id=2006045&model=project.task&menu_id=4720
**Pad**: https://pad.odoo.com/p/r.0e30de1dd865263267ca3644768b40b6

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
msg commit "[FIX] website_forum, website_forum: ..." ?

why forum class in website_profile addons ?

**Comment by tde-banana-odoo** [comment]
Typo in commit indeed.

For forum prefix, because minimal diff in stable. In master we will clean it.

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r- as we might have another solution.

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
> For forum prefix, because minimal diff in stable -> simple move. In master we will clean it.

en attendant, sans update de la vue, c quand meme cassé. Donc autant faire l'udpate des classes en même temps

**Pull request closed without merging**
