### PR TITLE
[IMP] sale: hide activity_ids when there are no activities

### PR DESCRIPTION
**Pull request by jeep-odoo**
Before:
The calendar view pop-up displayed an empty activity line when no activities
were scheduled for a rental order, which was not visually appealing.

After:
If no activities are scheduled for a particular rental order, the activity_ids
field is now hidden from the calendar view pop-up.

task-3893588

### CODE REVIEW

**Review by Feyensv — CHANGES_REQUESTED** [review]
PR title & commits should match and explain the changes in the repository you're targeting.

There is no `sale_renting` module here (nor any explanation why the activity_ids widget has to be hidden when there are no activites).

**Comment by jeep-odoo** [comment]
Hey @Feyensv 

Thanks for the feedback! Sorry for the mix-up with the PR title and commit messages—I thought they should be the same across different repos for the same task. I'll fix that and update the PR with the correct details. Also, I'll add an explanation for why the `activity_ids` widget needs to be hidden.

**Review by kmagusiak — APPROVED** [review]

**Comment by Feyensv** [comment]
Hello @mcm-odoo, will you be able to take a look in the near future or can we go forward with this PR ? :pray:

**Comment by Feyensv** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
