### PR TITLE
[FIX] *: adapt for noble

### PR DESCRIPTION
**Pull request by Xavier-Do**
This pr backports some fixed for python3.11 and introduces new fixes for Ubuntu Noble, such as timezones.

### CODE REVIEW

**Comment by Xavier-Do** [comment]
@odoo/rd-security

**Comment by Xavier-Do** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
@robodoo rebase-ff

**Comment by nmarotte** [comment]
Hello, @Xavier-Do , I believe this PR breaks a test here : https://github.com/odoo/odoo/blob/a1b8cfec431fe2393ae19719f886fb03c0a8b5e8/odoo/addons/base/tests/test_tz.py#L31
image

You can view an example on the branch 17.0-run-tests of this DB https://logipren.odoo.com/_odoo/support/

**Comment by Xavier-Do** [comment]
We will check that, you can disable this test  waiting for a fix :)

**Comment by nmarotte** [comment]
Perfect thanks ! I'm not in a hurry so it's fine, I'm happy to know you guys are going to take a look :)

**Comment by Xavier-Do** [comment]
> Perfect thanks ! I'm not in a hurry so it's fine, I'm happy to know you guys are going to take a look :)

We made a fix pr to make the test more robust, we are still investigating to understand why this tz is missing on odoosh but the purpose of this test is mainly to check that the mapping gives the same result if both tz exists. So once #160868 is merged the issue should be solved, tell us if the problem persist after that :)

**Comment by amh-mw** [comment]
> Hello, @Xavier-Do , I believe this PR breaks a test here :

This made it into the most recent [odoo:15](https://hub.docker.com/layers/library/odoo/15.0/images/sha256-7687d0f8f38e3d857ea172bc5b9a3ae4b4e8cfd22ae8d5c75619d09256f7753e?context=explore) docker image, suggesting that the release process does not ensure that only ✅ docker images are published.

**Comment by amh-mw** [comment]
> The official docker images are not made to run tests, a lot of tools are missing on the images to do that.

Right, but if the tests failed, why was the image created?

**Comment by Xavier-Do** [comment]
The test only fails if the os is in a particular state. After our investigation it was more a mistake in the tzdata package. 
The docker image is build automaticaly, the test are not ran, it is not the purpose of this image. The image is valid, even with this failing test.

**Pull request closed without merging**
