### PR TITLE
[FIX] stock: forbids possibility to make inventory of all products when a given product is chosen

### LINKED ISSUE #6512: [8.0] Cancel Inventory in Inventory Adjustments
Hi everyone,

***Impacted versions***

8.0

***Steps to reproduce***
1. Go to a v8 runbot instance
2. Go to Warehouse > Inventory Control > Inventory Adjustments
3. Create a new inventory adjustments and fill the fields as follows
 - Inventory Reference = Test
 - Inventoried Location = WH/Stock
 - Inventory of = One product only ( Select the [A1232] iPad Mini)
 - Click on Save and then Start Inventory ( The Theoretical Quantity and Real Quantity of the [A1232]    iPad Mini are presented)
 - Then click on Cancel Inventory , the status of the inventory adjustment is set to draft
 - Click on Edit and modify the inventory of "One product only" to "All Products"
 - Click on save and start the inventory

***Current Behavior***
The inventory adjustments shows the results only for the [A1232] iPad Mini

***Expected Behavior***
The inventory adjustments should present all the products because we selected the option "All Products"

It seems that when we cancel an inventory to modify the inventory selection, the results are "cached"

Regards, Matthias

### PR DESCRIPTION
**Pull request by nim-odoo**
opw-634388
Fixes #6512

### CODE REVIEW

**Comment by beledouxdenis** [comment]
I do not believe the OPW was about adding a constraint (while adding this constraint could be good), but was about the fact when you save an inventory of only one product, then cancel it, and then set "All Products", only the inventory of the product chosen in the first place is updated.

Probably, when the "Only one product" inventory was saved, the product has been saved within the "product_id" field, which should be emptied, or ignored, when you perform the "All products" inventory afterwards.

**Comment by nim-odoo** [comment]
onchange added

**Comment by beledouxdenis** [comment]
I am afraid you will see me as an annoying guy : (.

The domain for the invisible attrs of the product_id field is:
```
[('filter', 'not in', ('product', 'product_owner'))]
```
Shouldn't the condition in the constraint be:
```
if inventory.filter not in ('product', 'product_owner') and inventory.product_id:```
```
and the condition in the onchange:
```
False if filter not in ('product', 'product_owner') else product_id
```
In addition, to avoid to trigger the change in the `product_id` field, in the onchange, return `False` as value only if the filter is set `not in ('product', 'product_owner')`, it's enough:
```
def onchange_filter(self, cr, uid, ids, filter):
    return {'value': {'product_id': False} if filter not in ('product', 'product_owner') else {}}
```

**Comment by nim-odoo** [comment]
Makes more sense, indeed. Commit modified accordingly.

**Comment by beledouxdenis** [comment]
Perfect :+1:

**Comment by ah-taktik** [comment]
Hello, @beledouxdenis, @nim-odoo, 


:-1: The fix proposed here does not resolve all cases.
The only case solved here is when you select ``One product only `` then you cancel the inventory and  select ``All products``filter.

You should take care of other possibilities such us : 
- ``One Lot/Serial Number``, 
- ``One owner only``
- ``One product for a specific owner``
- ``A Pack``

The easiest way to solve this issue is modifing the action_cancel_draft method without altering view and creating constraints: 
```python
def action_cancel_draft(self, cr, uid, ids, context=None):
        """ Cancels the stock move and change inventory state to draft.
        @return: True
        """
        for inv in self.browse(cr, uid, ids, context=context):
            self.write(cr, uid, [inv.id], {
                'line_ids': [(5,)],
                'partner_id': False,
                'product_id': False,
                'lot_id': False,
                'package_id': False,
            }, context=context)
            self.pool.get('stock.move').action_cancel(cr, uid, [x.id for x in inv.move_ids], context=context)
            self.write(cr, uid, [inv.id], {'state': 'draft'}, context=context)
        return True
```

**Comment by beledouxdenis** [comment]
I do not believe that altering the cancel as you do is the easiest solution.

Indeed, what happens if you create a draft inventory, set one product only, set the product, and set to all products ? You have the exact same issue, without having even confirmed or canceled the inventory.

**Comment by mve-taktik** [comment]
@beledouxdenis 
Your are right, your solution seems better because it does not simply rely on clicking on "cancel inventory".
However you should take in consideration all the possibilities of the "inventory of" as aforementioned by @ah-taktik (One Lot , one owner , a pack , one product for a specific owner).

**Comment by ah-taktik** [comment]
@beledouxdenis, Yeah, you're right !

**Pull request merged**
