### PR TITLE
[FIX] website_forum: fix crash when clicking on the vote button

### PR DESCRIPTION
**Pull request by ngochuy97hp**
**Current behavior before PR:**
Crash when clicking on the vote button
**Steps to reproduce:**
 Vote own post (in case enough karma)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ngochuy97hp** [comment]
@rdeodoo Could you take a look on this PR?

**Review by rdeodoo — CHANGES_REQUESTED** [review]
@ngochuy97hp Thank you for the PR.
This is correct but could you just adapt the commit message to add those info please?

It always eases the review and later git blame.

```
Some call to `displayNotification` were broken by commit [1] as it
replaced `self` by `this`. It was partly fixed with [2].

[1]: https://github.com/odoo/odoo/commit/57ba855b66f2ff1d393f639bbc18dd444e2afa8f
[2]: https://github.com/odoo/odoo/commit/ab65d077b7b4ec04155401902eb65418b4d2f415
```

**Comment by ngochuy97hp** [comment]
> @ngochuy97hp Thank you for the PR. This is correct but could you just adapt the commit message to add those info please?
> 
> It always eases the review and later git blame.
> 
> ```
> Some call to `displayNotification` were broken by commit [1] as it
> replaced `self` by `this`. It was partly fixed with [2].
> 
> [1]: https://github.com/odoo/odoo/commit/57ba855b66f2ff1d393f639bbc18dd444e2afa8f
> [2]: https://github.com/odoo/odoo/commit/ab65d077b7b4ec04155401902eb65418b4d2f415
> ```

Done, please check again :)

**Review by rdeodoo — APPROVED** [review]
@robodoo r+
Thank you for your contribution, appreciated.

**Pull request closed without merging**
