### PR TITLE
[FIX] point_of_sale, pos_epson_printer: Arabic receipts format

### PR DESCRIPTION
**Pull request by aprieels**
The receipts that contained arabic characters were not transformed
correctly into images by the html2canvas library. Some characters were
not rendered correctly (#41893) and words were sometimes overlapping.

We then replace the html2canvas library by dom-to-image, which handles
arabc characters correctly and also seems to process images faster.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qle-odoo** [comment]
@aprieels yeah another library ! :)
@khalidtkl can you try with this library ?

**Comment by khalidtkl** [comment]
> @aprieels yeah another library ! :)
> @khalidtkl can you try with this library ?

Do you still want me to try this library instead of html2canvas??

**Comment by lathama** [comment]
@aprieels knowing that 13 is no longer updated, is this PR still needed?

**Comment by C3POdoo** [comment]
Dear @aprieels,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
