### PR TITLE
[FIX] tools: x_studio image field size

### PR DESCRIPTION
**Pull request by Dj0ulo**
__Current behavior before PR:__
The size of an image field is guessed using the field name. For instance, an image field with `field_name = "XXXX_123"` is resized to 123 pixels when fetched. This is can be an issue if a user creates an image field using studio in a form view. If the user sets the label of the field as "Image 1", the technical name will become `x_studio_image_1`. Therefore, the image field will be resized to 1 pixel width.

__Description of the fix:__
Refactor the `image_guess_size_from_field_name` method to return `(0, 0)` when the field name starts with `x_studio_`.

__Steps to reproduce the issue:__
1. Open a form view (of any model)
2. Open studio
3. Add an image field with label "Image 1" (notice the technical name becomes in `x_studio_image_1` in debug mode)
4. Close studio
5. Upload an image on the created field
6. Save... The image is resized to 1 pixel width

opw-3242084
opw-3249632
opw-3253133

### CODE REVIEW

**Review by mart-e — CHANGES_REQUESTED** [review]
You don't have this issue only with studio, creating a field `image_1`, `image_2` is also something that could happen with standard or custom fields (and all custom fields are not from studio).

Assuming the field name contains the size seems a bit far fetched in the first place, using field attributes would have been cleaner.
For a fix in stable, maybe you can make another more general assumption like suffix should be bigger than 32px.
This way you fix it for everybody, not just studio (hoping nobody did something like putting a year or something...)

**Comment by Dj0ulo** [comment]
> Assuming the field name contains the size seems a bit far fetched in the first place, using field attributes would have been cleaner.

I agree with you on that. This fix just seemed to be the easiest one for a stable version. I was especially targeting the average user which cannot even see the technical name of the field he creates (if not in debug mode). He could put a number in the label and ends up with this weird behavior.
I assumed that if you directly write the technical name you are at least more likely to find why it resizes the image.

> For a fix in stable, maybe you can make another more general assumption like suffix should be bigger than 32px.
This way you fix it for everybody, not just studio (hoping nobody did something like putting a year or something...)

That said I am no convinced that would be a cleaner fix for that exact reason IMHO.

**Comment by mart-e** [comment]
https://github.com/search?q=%22image_2+%3D+fields%22&type=code

**Comment by Dj0ulo** [comment]
@mart-e I have done what you said but for suffix lower than 16 since I found a repo that used 16 as the size https://github.com/Tawasta/website/blob/1bbaa21cf4df5c8af124f647fc29f36b6eb23d42/website_additional_icons/models/res_config_settings.py#L15.
I also kept the `x_studio_` condition so we still have a safeguard for potential user that would put a year in their field.

**Comment by mart-e** [comment]
>  I also kept the `x_studio_` condition so we still have a safeguard for potential user that would put a year in their studio field.

At least make it `x_` then. Studio is an enterprise module and not the only way to make custom fields.

**Comment by Dj0ulo** [comment]
> At least make it `x_` then. Studio is an enterprise module and not the only way to make custom fields.
No problem, done !

**Review by mart-e — APPROVED** [review]

**Comment by Dj0ulo** [comment]
opw-3249632
opw-3253133

**Comment by seb-odoo** [comment]
I feel like this issue exists already in all previous versions as well.

Since v16 the issue is worse because the function is called even when we have an image, whereas before it was only called for placeholder. It's conceptually not good that we "guess" more in v16, where the goal would be to get rid of guessing instead. I'm not sure why more guessing was introduced when we have an actual image at disposition, but it would be nice if we could get rid of that part instead (or as well).

And in master it would be nice to get rid of it completely, I don't remember the history exactly but the guessing might have been introduced before the existence of image field? In that case guessing could be removed in favor of just using max_width and max_height on the field.

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

Ok for the current patch on the current version, but please also consider:

- [ ] backporting the current fix to previous versions to resolve similar issue with placeholder
- [ ] removing the need to guess in v16 when we have an actual image (keep guessing only for placeholder if possible)
- [ ] removing the guess function in master if the image field meta can be used instead

**Comment by Dj0ulo** [comment]
@seb-odoo Alright, I will do those, things. I rebased, it should be good now.

**Comment by Dj0ulo** [comment]
Oups

**Comment by seb-odoo** [comment]
@robodoo r+

**Comment by Dj0ulo** [comment]
> In that case guessing could be removed in favor of just using max_width and max_height on the field.

@Julien00859 @seb-odoo I am working on removing the function on `saas-16.1`. Do you think I should add `max_width` and `max_height` on every `fields.Image` [in odoo](https://github.com/search?q=repo%3Aodoo%2Fodoo+%2F_%28%5Cd%2B%29+*%3D+*fields%5C.Image%2F&type=code) and [in enterprise](https://github.com/search?q=repo%3Aodoo%2Fenterprise+%2F_%28%5Cd%2B%29+*%3D+*fields%5C.Image%2F&type=code) ?

**Comment by seb-odoo** [comment]
Why saas-16.1? Such changes should be done in master only, stable version should only receive the minimal patch.

We should not add `max_width` and `max_height`, there are fields where we specifically want to keep the original image.
In that case, I would say let the placeholder take it's "original" size too, whatever it is (no resize).

**Comment by Dj0ulo** [comment]
> Why saas-16.1? Such changes should be done in master only, stable version should only receive the minimal patch.

@Julien00859 [told me to do that](https://github.com/odoo/odoo/pull/118968#issuecomment-1527335328)

> We should not add `max_width` and `max_height`, there are fields where we specifically want to keep the original image. In that case, I would say let the placeholder take it's "original" size too, whatever it is (no resize).

Sorry, in my previous message I meant every `fields.Image` *that has an `_` followed by a number in their name*. So I **don't** add `max_width` and `max_height` for those too right ?

**Comment by seb-odoo** [comment]
For those that have their size in the name but not the size in the field meta it would be fine to add them yes.

I think those that are computed or related didn't have it to avoid trying to resize them again, as their "source" (result of compute/related) would already have the correct size.
But it's not a big deal, and it should be optimized differently if it's still necessary.

**Comment by Julien00859** [comment]
Don't change models in stable, I agreed we remove the function in stable, I didn't realise we had to add fields on some models (do we really have to?)

**Pull request closed without merging**
