### PR TITLE
[FIX] Use non-beaking space between amount and currency in reports

### LINKED ISSUE #6369: The qweb FieldMonetary widget should use a non-breaking space between currency symbol
Otherwise you obtain such not-so-nice reports where the currency wraps on the next line:

selection_030

### PR DESCRIPTION
**Pull request by nim-odoo**
Fixes #6369
opw-633975

### CODE REVIEW

**Comment by xmo-odoo** [comment]
Why not just use the unicode non-breaking space character instead of the HTML entity? That way you don't have to break HTML escaping

**Comment by beledouxdenis** [comment]
I have the same opinion as @xmo-odoo.

As this is not such easy to print the non-breaking space character with your keyboard, you can use python to print it and replace the space between the two `%s` by a copy of what python replies you:
screenshot from 2015-04-29 11 18 45

**Comment by nim-odoo** [comment]
ok, done

**Comment by xmo-odoo** [comment]
@beledouxdenis 
> As this is not such easy to print the non-breaking space character with your keyboard, you can use python to print it and replace the space between the two 

since it's Python code, we can just use [an escape sequence](https://docs.python.org/2/reference/lexical_analysis.html#string-literals) in the Python code, that way it's visible & clear that there's something other than a regular space. Since this one is a bytestring, you'd have to use the hex escape, but there's the same issue in the QWeb widget for HTML rendering (which probably should also be fixed), and there it's a Unicode string so you can use named character escapes.

**Comment by beledouxdenis** [comment]
@nim-odoo 
Take the opportunity you modify the line to make it respect PEP8 standards
`res=u'%s%s%s'%(currency_obj.symbol,unichr(160),res)`
to
`res = u'%s%s%s' % (currency_obj.symbol, unichr(160), res)`

@xmo-odoo 
The '%s' % unichr(160) is enough meaningful to you ?

**Comment by xmo-odoo** [comment]
> The '%s' % unichr(160) is enough meaningful to you ?

Sure, though if the base string is converted to unicode changing the pattern to `%s\N{NO-BREAK SPACE}%s` or using `unicodedata.lookup('NO-BREAK SPACE')` is also a good option.

**Comment by beledouxdenis** [comment]
@nim-odoo Can you give a shot to `%s\N{NO-BREAK SPACE}%s` as Xavier explained ? It seems even more meaningful that way.

**Comment by nim-odoo** [comment]
@beledouxdenis Seems all good

**Comment by nim-odoo** [comment]
@beledouxdenis Could we apply it there as well : https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/ir/ir_qweb.py#L1008
(remark from @sle-odoo)

**Comment by beledouxdenis** [comment]
Not a bad idea, give it a shot :).

**Comment by nim-odoo** [comment]
It is working, I adapted the appropriate test.

**Comment by beledouxdenis** [comment]
Seems fine to me :+1: 

Thank you :).

**Pull request merged**
