### PR TITLE
[FIX] mrp_landed_costs: validate a landed cost without the need for MRP access

### PR DESCRIPTION
**Pull request by DjamelTouati**
Steps to reproduce the bug:
- Install mrp_landed_costs
- Connect as Admin
- Remove MRP access to Admin and Give him Stock manager access
- Go to inventory settings > Enable “Landed costs”
- Go to inventory > operation > Select any landed cost
- Try to validate

Problem:
An access error is triggered because we check if there are finished moves in the associated pickings and manufacturing orders
before validating the landed cost, but in the "_get_targeted_move_ids" function we access the "mrp_production_ids" field, which is reserved for mrp users.

Solution:
Creating and validating a landed cost is a feature for stock manager users.
We can therefore have users who do not need access to MRP, but who need to  validate and submit landed costs.
So we can give access to all of them even if they are not MRP users.

opw-2800367

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Whenrow** [comment]
robodoo r+

**Comment by DjamelTouati** [comment]
**ci/style** failed

**Comment by DjamelTouati** [comment]
@Whenrow 
Could you restart the r+ please

**Comment by Whenrow** [comment]
> **ci/style** failed

:scream:

**Comment by Whenrow** [comment]
robodoo r+

**Pull request closed without merging**
