### PR TITLE
[REF] purchase_stock: Split _get_quantity_in_progress method in order  to make it more inheritable

### PR DESCRIPTION
**Pull request by hugho-ad**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

### OPW: 2917884

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hugho-ad** [comment]
Hello @amoyaux 

could you review?

**Comment by hugho-ad** [comment]
@mart-e 

could you help me with this?

**Comment by mart-e** [comment]
@hugho-ad no sorry, I let the logistic team handle this (and I am not sure you want me to handle this as IMO, hook methods should only be added in master ;-) )

**Comment by Whenrow** [comment]
@hugho-ad Hello. It's good to me. I've rebuilt the runbot to merge

**Comment by Whenrow** [comment]
robodoo r+

**Comment by hugho-ad** [comment]
Thanks! @Whenrow !

**Pull request closed without merging**
