### PR TITLE
Sign CLA Yenthe666

### PR DESCRIPTION
**Pull request by Yenthe666**
CLA

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thanks but your are removing the file `doc/cla/sign-cla.md` in your commit which probably wasn't the intention :)

**Comment by Yenthe666** [comment]
Oh, nope that was not the intention.. So how should I do this correctly then? Can you not only merge my own file or something?

**Comment by mart-e** [comment]
Ok I applied the diff at 34cd8960fc6dd4324589fa6678e6c8508a30917d (well I missed it was in the wrong folder, fixed at 8c35497c7408c2c1d386c6f895ca0618aa64be5d) but for future contributions, I advise you to check a git tutorial (e.g. [this one](https://www.atlassian.com/git/tutorials/)) as it takes us more time to takes part of the diff only.

**Comment by Yenthe666** [comment]
Alright will follow that tutorial for pull requests. Thanks @mart-e :+1:

**Pull request closed without merging**
