### PR TITLE
[IMP] gamification: remove send email as there is a front-end page fo…

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Task: https://www.odoo.com/web#action=333&active_id=248&id=27346&menu_id=4720&model=project.task&view_type=form

### CODE REVIEW

**Comment by mart-e** [comment]
The point was to remove it from the forum but not to remove the feature from gamification (which is [the most underrated module](http://www.emiprotechnologies.com/blog/odoo-blog-54/post/odoo-gamification-perhaps-the-most-underrated-feature-in-odoo-that-has-been-overlooked-so-far-288)), wasn't it?

**Comment by tde-banana-odoo** [comment]
Is it used somewhere else ?

**Comment by mart-e** [comment]
If we start removing features because we don't use it, should we remove the workflow engine? :wink:

**Comment by tde-banana-odoo** [comment]
Somebody told me it is about to be removed. But do not tell it.

**Comment by JKE-be** [comment]
don't tell what ?  https://github.com/odoo-dev/odoo/commits/master-remove-legacy-code :postal_horn:

**Comment by JKE-be** [comment]
print ' @'.join(['', 'odo', 'kangol', '...'])

**Pull request merged**
