### PR TITLE
l10n_fr: reconcile=True on 511xxx accounts

### PR DESCRIPTION
**Pull request by alexis-via**
This is a small and simple update to the French chart of accounts.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by invitu** [comment]
:+1:

**Comment by fclementic2c** [comment]
:+1:

**Comment by mart-e** [comment]
Thanks, merged at https://github.com/odoo/odoo/commit/ad14be036cd85eddc3e43daf4fae32f762a08ea4

**Comment by chermed** [comment]
For 511xxx accounts, I think that `user_type_id` also should be `data_account_type_current_assets` and not `data_account_type_liquidity`

The probem is on the `internal_type` that will be `liquidity` an so we can't generate a new move on reconciliation with the bank

Can you confirm ?

**Pull request merged**
