### PR TITLE
[FIX] pos_sale: add pos orders count in sale report

### PR DESCRIPTION
**Pull request by MerlinGuillaume**
The number of orders displayed in sale report doesn't show pos orders

Steps to reproduce:
1. Install Sales and Point of Sale
2. Open a session in any point of sale and complete an order
3. Go to Sales > Reporting > Sales
4. The different views contain the order made in the POS

Solution:
Add a field `pos_order_id` on `sale.report` which contains the
`pos.order` linked to the `sale.report` and add up the number of
distinct order_id and pos_order_id to compute the total number of orders

Problem:
There is no way to know which `pos.order` is linked to a `sale.report`

opw-3067700

### CODE REVIEW

**Comment by Feyensv** [comment]
Why ?
We want the data of the pos orders in the Sales report.
If we don't, what's the point of the whole `pos_sale` code adding this data in it ? :thinking:

**Comment by trj-odoo** [comment]
> Why ? We want the data of the pos orders in the Sales report. If we don't, what's the point of the whole `pos_sale` code adding this data in it ? :thinking:

I agree with @Feyensv. That has always been the default behavior since the beginning and I don't think it'll be changed

**Comment by MerlinGuillaume** [comment]
@Feyensv I think adding a new field `pos_order_id` is the only way to fix this issue. What do you think ? I also added a new module in https://github.com/odoo/enterprise/pull/35482 that modifies the dashboard view of sale.report when sale_enterprise and pos_sale is installed

**Comment by Feyensv** [comment]
Honestly, for this level of 'bug', I don't think adding a new field (& module) is worth it (and furthermore, it'd require a module update to replace the SQL view with the new query).

Cc: @dalaOdoo

**Comment by dalaOdoo** [comment]
I don't think we should do such an effort for a problem that is not blocking for the customer once he knows why and also knowing that this dashboard does not exist anymore

**Comment by MerlinGuillaume** [comment]
Issue is not fixable in stable

**Pull request closed without merging**
