### PR TITLE
Master discuss v15

### PR DESCRIPTION
**Pull request by seb-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
Current state: rebase almost ok, but changes in sidebar coming from group dm have been currently ignored

**Comment by Yenthe666** [comment]
This is the one I was waiting for 🤤 Is there any public pad/info/feedback on what is within this PR?
I have a possible project migration depending on these changes :)

**Comment by seb-odoo** [comment]
Still very much WIP, this is just an attempt at merging together the various branches for which we already had other PRs open.
I guess check the commits to have an idea what is inside?

**Comment by Yenthe666** [comment]
@seb-odoo so can we conclude that parts of the discuss changes will not land in V15?

**Comment by seb-odoo** [comment]
Everything that was in this PR is already in, and the last part I linked will be in as well.

**Pull request closed without merging**
