### PR TITLE
[FIX] mail: only show new message separator in the relevant thread

### PR DESCRIPTION
**Pull request by tsm-odoo**
Before this PR, the new message separator could be displayed in threads other than the one the message belongs to (e.g., Inbox, Starred, and History mailboxes).

This PR restricts the new message separator to the thread the message belongs to.

Steps to reproduce the issue:

- Go to the general channel.
- Mark a message as unread and star it.
- Go to the Starred mailbox.
- The separator is shown.

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]
👆renamed the test. The test name could still be a bit hard to understand in case implementation differs, so I but a more specific comment to help quickly understand the context of this test

@robodoo delegate+ r+

**Comment by tsm-odoo** [comment]
@robodoo r+ 

:point_up: rebase

**Comment by tsm-odoo** [comment]
@robodoo r+

:point_up: rebase

**Comment by tsm-odoo** [comment]
@robodoo r+

:point_up: rebase

**Pull request closed without merging**
