### PR TITLE
fixing import translation file

### PR DESCRIPTION
**Pull request by bluemix**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bluemix** [comment]
Technical Details:
write() argument must be str, not bytes

screen shot 2017-11-19 at 09 50 35

**Comment by Elkasitu** [comment]
@alexkuhn I believe your commit 44b3491 tried to fix this?

**Comment by mart-e** [comment]
Hello,

Looks good to me but could you [sign the CLA](https://www.odoo.com/sign-cla) so we can integrate your patch?

**Comment by alexkuhn** [comment]
Seems good for me too.

**Comment by bluemix** [comment]
ok, I have signed the CLA, https://github.com/odoo/odoo/pull/21545,
but how can this pull request merged with this one here

**Comment by mart-e** [comment]
Thansk for the CLA and patch !

**Pull request merged**
