### PR TITLE
[IMP] hr: female as default gender

### PR DESCRIPTION
**Pull request by CasVissers-360ERP**
Description of the issue/feature this PR addresses:
To avoid any discussion ;), let's sort gender alphabetically.

Current behavior before PR:
Male is default gender.

Desired behavior after PR is merged:
In alphabetical order female should be default.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Why on stable version?

**Comment by pedrobaeza** [comment]
It's not for being patriarchal, but the alphabetic order depends on the translations. For me, the best is to leave that field without default.

**Comment by CasVissers** [comment]
Will leave it to Odoo what to decide.

**Comment by mart-e** [comment]
I tend to agree with Pedro, no default to avoid wrong information when creating new contacts.
But on the other hand probably @tivisse wants to comment as he made the change at 7964b81ac8546ebfd495c8f7fcd96cd2f1a7c85f
Should target the master and the demo data should be adapted to indicate the gender everywhere.

**Comment by CasVissers** [comment]
(BTW). I agree with Pedro as well that no default is the best solution.

**Pull request closed without merging**
