### PR TITLE
[master] point_of_sale: Remove MISC product

### PR DESCRIPTION
**Pull request by alexis-via**
This "MISC" product is added to production databases upon installation of the point_of_sale module (it is NOT part of demo data), which is annoying. No need to move it to demo data, there is already a lot of product demo data in the point_of_sale module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1: 
Well, in fact most of the data in this PoS module should be removed too. pos.config, and moved into demo data.

https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/data/point_of_sale_data.xml

**Comment by Yenthe666** [comment]
I vote for honestly.

**Comment by yelizariev** [comment]
👎 sorry

It's used in pos_discount and in tests

https://github.com/odoo/odoo/search?l=Python&q=product_product_consumable&type=&utf8=%E2%9C%93

It shall not be removed, but probably moved to other module. Or some other solution to resolve the inconvenience you described

**Comment by alexis-via** [comment]
@yelizariev Nice catch. In fact, the MISC product is NOT used in odoo v10 (the odoo version I'm working on), but it is used in v11 and master... but I didn't re-check that when I made the PR on master.

**Comment by mart-e** [comment]
Maybe we could put it as `active=False` to avoid to display it to users in production when not needed.

**Comment by alexis-via** [comment]
Another option would be to move it to pos_discount (and replace it by another product in the tests of the point_of_sale product)

**Pull request closed without merging**
