### PR TITLE
[IMP] test_performance: _as_query is linear

### PR DESCRIPTION
**Pull request by kmagusiak**
Given the size of records, nothing is really constant (as at least most methods iterate or copy the record ids). Setting the check to the default 'linear'.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rco-odoo — APPROVED** [review]
@robodoo r+

**Comment by rco-odoo** [comment]
@robodoo r-

**Comment by d-fence** [comment]
Test is now disabled on runbot, wait for the new configured build before rplusing please

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
