### PR TITLE
[FIX] account: handle unsigned with signed tax tags

### PR DESCRIPTION
**Pull request by proose**
When a tax is created using an unsigned tax tags AND a signed tax tag, the mapper in the chart template model was crashing, skipping the needed mapping for the signed tax (the unsigned tax doesn't need to be mapped as it comes from a template).

task-3520182

### CODE REVIEW

**Comment by proose** [comment]
This is a reopen of this PR: https://github.com/odoo/odoo/pull/136460 that targeted the wrong version

**Review by oco-odoo — APPROVED** [review]
@robodoo r+

**Comment by oco-odoo** [comment]
@robodoo r-

@proose Actually, you should also add a test for this ^^

**Review by oco-odoo — APPROVED** [review]
@robodoo r+

**Review by oco-odoo — APPROVED** [review]
@robodoo r+

**Comment by oco-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
