### PR TITLE
CLA and new branch

### PR DESCRIPTION
**Pull request by Gugizm**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@Gugizm you are supposed to create your own CLA file `gugizm.md` instead of changing an existing one :)
Also, can you use the commit message `[CLA] add signature for Gugizm`?
Thanks

**Comment by Gugizm** [comment]
Dear Martin,

Thank you for reaching out and providing clarification regarding the
Contributor License Agreement (CLA) process for Gugizm.

I've taken note of your instructions and have created a new CLA file named
"gugizm.md" as requested. The CLA now contains the necessary information
and signature for Gugizm.

Additionally, I've used the commit message "[CLA] add signature for Gugizm"
to indicate the changes made to the CLA file.

Please let me know if there are any further steps required or if you need
any additional information from my end.

Thank you for your assistance.

Best regards,
Guga Abuladze

**Comment by lathama** [comment]
@Gugizm you should remove the change to @odony CLA from your PR

**Comment by lathama** [comment]
Please git amend to add the `[CLA]` tag back to your commit mesg

**Comment by mart-e** [comment]
Almost, it needed to be in only one commit (also please avoid pinging users in commit messages, it quickly gets spammy).
I have updated your branch so it should be good now.

Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
