### PR TITLE
[11.0] add hook on '_run_buy' method of 'procurement.rule'

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Description of the issue/feature this PR addresses:

This PR adds a hook on '_run_buy' method of 'procurement.rule' in order to allow other modules to add data to existing PO lines. 

Current behavior before PR:
For example, in the proposed OCA module 'stock_request_purchase' (https://github.com/OCA/stock-logistics-warehouse/pull/352) we want to pass to an existing purchase order line the reference to a new stock_request https://github.com/OCA/stock-logistics-warehouse/pull/352/files#diff-1a2cf805907b4d6b58f7cdf460adc90fR15, but unfortunately this won't be possible without this hook.

Desired behavior after PR is merged:
Possibility to pass extra data to existing PO lines when a procurement rule is run.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jbeficent** [comment]
@rousseldenis Looking at the log of the runbot, this error seems to be unrelated.

**Comment by rousseldenis** [comment]
@jbeficent Yes!

**Comment by mreficent** [comment]
the runbot problem is solved. Please rebase to make it green

**Comment by jbeficent** [comment]
rebased

**Comment by Yenthe666** [comment]
@jco-odoo could you have a look and merge this in please? It is preventing some OCA implementations.

**Comment by jbeficent** [comment]
@jco-odoo You might find this PR to OCA interesting. https://github.com/OCA/stock-logistics-warehouse/pull/352. Would be glad to propose it directly to odoo if you find it useful.

**Comment by rousseldenis** [comment]
@jco-odoo

**Comment by mreficent** [comment]
@sle-odoo

**Comment by sle-odoo** [comment]
Hi,
Nothing against the idea but why the awkward line breaks? I know pep8 and stuff but it's less readable in this case IMO. Maybe rename "procurement_uom_po_qty" to "qty_to_add", it'll be more understandable maybe. I don't know, as you wish, but i don't like the line breaks :)

Regards

**Comment by jbeficent** [comment]
@sle-odoo We'll fix that :)

**Comment by amoyaux** [comment]
I guess it can be close since commit 71d5425c83edd212b4acf00f1d55bd5ee5f96761

**Pull request closed without merging**
