### PR TITLE
update pdfjs lib

### PR DESCRIPTION
**Pull request by msh-odoo**
Task:https://www.odoo.com/web#id=2124443&action=333&active_id=1251&model=project.task&view_type=form&menu_id=4720

Pad: https://pad.odoo.com/p/r.a33eaa2cc360a778a439603f92f4c5bf

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r-

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo rebase-ff

**Comment by Yenthe666** [comment]
@msh-odoo and @ged-odoo hi! Could you tell me from which version to which version of pdfjs we're jumping? The diff is so huge that I can't seem to find it easily :)

**Comment by msh-odoo** [comment]
@Yenthe666 I don't know the previous version we used(I think we added pdfjs in Aug 2015) but the updated version is 2.2.228

**Pull request closed without merging**
