### PR TITLE
[FIX] point_of_sale: don't recreate existing products during tests

### PR DESCRIPTION
**Pull request by nilshamerlinck**
(Testing something, please ignore for now)

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
This is done on purpose. You may want to run tests without having demo data.

**Comment by nilshamerlinck** [comment]
hello @MiquelRForgeFlow 
- thanks for your input; is it something that you do? if yes, why?
- I understand it could make sense to run tests on a copy of a production db before deployment but I'm not sure if it's something common
- afaik both odoo and OCA run tests with demo data installed
- in general I find it quite convenient to rely on demo data in tests :)

**Comment by MiquelRForgeFlow** [comment]
> thanks for your input; is it something that you do? if yes, why?

No, I don't 😄. It was a decision from Odoo long time ago (2019): https://github.com/odoo/odoo/pull/37312

**Comment by nilshamerlinck** [comment]
thanks @MiquelRForgeFlow for the link to the PR!
- confirms the target of running tests on a production db
- not sure if they have achieved it yet as part of their automated upgrade process; I remember seeing some tests being run on the migrated db to check views (with the eventual error `At least one menu or view working before upgrade is not working after upgrade`), but not the whole tests suite
- anyway, closing this PR then, will find another way :)

**Pull request closed without merging**
