### PR TITLE
[FIX] account_check_printing: recover correct last check number

### PR DESCRIPTION
**Pull request by agr-odoo**
Go to Accounting > Vendor Bill, pay via check, view the invoice and
click on 'Print Check'. The widget will popup but as the 'next check
number' will always display 1.

This append because the model of account_payment has changed
https://github.com/odoo/odoo/blob/13.0/addons/account_check_printing/models/account_payment.py#L28
and now check_number is a char so it will not sorted correcly by the
database.

Retrieving the values and filtering afterward is a little bit slower but
still acceptable in this case, because ORM still does not accept
functions is ordering parameter

opw-2151242

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@nim-odoo

**Comment by agr-odoo** [comment]
updated

**Comment by nim-odoo** [comment]
fw-bot up to saas-13.1

**Comment by nim-odoo** [comment]
robodoo retry

**Pull request closed without merging**
