### PR TITLE
[FIX] board,mail,project: Remove spaces from external IDs

### PR DESCRIPTION
**Pull request by luisg123v**
This was already performed on 3c568aec0b46, but there still are some
remnants on model access records.

Closes odoo/odoo#25408

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by luisg123v** [comment]
@mart-e 
Could you check this, please?

CC @moylop260 @nhomar

**Comment by moylop260** [comment]
Good catch!

@xmo-odoo 
What about adding a constraint in order to avoid spaces for xml_id?

If it is good idea for you we can open a new PR

**Comment by mart-e** [comment]
For safety reason, I have merged it in master at #37958
As the `ir.model.access` are not translatable, it shouldn't be a problem at least for the translation processing.
We can backport if we realise this is problematic

**Comment by xmo-odoo** [comment]
> @xmo-odoo

> What about adding a constraint in order to avoid spaces for xml_id?

Sure, sounds nice.

**Pull request closed without merging**
