### PR TITLE
[IMP] Avoid test duplicate

### PR DESCRIPTION
**Pull request by Xavier-Do**
A common issue is caused by importing a TestClass containing test methods as an util class in another TestClass, which will cause the tests to be executed at least three times:

- when the TestClass is loaded
- when the TestClass is imported
- once for each class inheriting from the util class

The proposed solution will check the module name of the TestClass and testCases to avoid duplicates.

### CODE REVIEW

**Comment by Xavier-Do** [comment]
Note that the implementation of  `inspect.getmembers` is more complex than needed, explicitly getting the mro in case it is not in the base class, ordering the method by name to make it deterministic because dict iteration where not well defined before 3.6, ... 

And after that we will filter the method to ensure it is defined in the correct class to avoid executing inherited method. 

It could be actually WAY easier to iterate on `__dict__` in this case:

```
def get_module_test_cases(module):
    """Return a suite of all test cases contained in the given module"""
    tests = []
    for _name, obj in sorted(module.__dict__.items(), key=lambda pair: pair[0]):
        if not isinstance(obj, type):
            continue
        if not issubclass(obj, case.TestCase):
            continue
        testCaseClass = obj
        for method_name, method in sorted(testCaseClass.__dict__.items(), key=lambda pair: pair[0]):
            if not callable(method):
                continue
            if not method_name.startswith('test'):
                continue
            yield testCaseClass(method_name)
    return tests
```

Going even further, since the order of iteration on a dict is now defined as the order of insertion, so the order of declaration of the methods, we could do: 

```python
def get_module_test_cases(module):
    """Return a suite of all test cases contained in the given module"""
    tests = []
    for obj in module.__dict__.values():
        if not isinstance(obj, type):
            continue
        if not issubclass(obj, case.TestCase):
            continue
        testCaseClass = obj
        for method_name, method in testCaseClass.__dict__.items():
            if not callable(method):
                continue
            if not method_name.startswith('test'):
                continue
            yield testCaseClass(method_name)
    return tests
```

This would be even mode desirable, since most test case will define the methods with numbers as `test_00_x`, `test_01_b` to keep them ordered by execution. There is no reason to prefer alphabetical order in this case, declaration order is more intuitive.
I had actually the plan to change that at some point.

The only issue is that the `allow_inherited_tests_method` hack does not work at all in this case.

An temporary solution could be to do an hybrid, something like 

``` python
def get_module_test_cases(module):
    """Return a suite of all test cases contained in the given module"""
    tests = []
    for _name, obj in sorted(module.__dict__.items(), key=lambda pair: pair[0]):
        if not isinstance(obj, type):
            continue
        if not issubclass(obj, case.TestCase):
            continue
        testCaseClass = obj
        if getattr(testCaseClass, 'allow_inherited_tests_method', False):
            test_cases = inspect.getmembers(testCaseClass, callable)
        else:
            test_cases = sorted(testCaseClass.__dict__.items(), key=lambda pair: pair[0])
        for method_name, method in test_cases:
            if not callable(method):
                continue
            if not method_name.startswith('test'):
                continue
            test = testCaseClass(method_name)
            yield test
    return tests
 ```

This would allow to easily remove the sorted (in another pr maybe), and the `allow_inherited_tests_method` latter if it isn't widely used (the change could be done in the TestHttpStaticWebServer class since this is the single case where I applied it for the moment)

**Comment by Xavier-Do** [comment]
> I don't think the tests = [] or return tests are necessary if we stop adding test cases to the list and yield them instead. The named test local as well, I don't think it's more helpful than just having th test case name (and inside a debugger you can easily create the test case by hand if absolutely necessary).

Yes I agree I didn't fully cleaned it before copy pasting, i'll fix the example in my code

> One possible issue is that not all test cases which do that also use the corresponding definition order. 

Maybe but it would be a mistake in think in that case. But this is the kind of reason why I would prefer to remove the sorted in another pull request to keep changes isolated. 

> Then again, I think cross-test dependencies are an awful idea since they make running single tests potentially not work, if people want test sequences they can use subtests or extract sub-functions. So I'm fine with changing the order in which tests run anyway.

In this case i'll apply my last proposal and we will be able to cleanup more in followup pr.

**Comment by Xavier-Do** [comment]
So, yes, despite the sorted on test case, the test class are not ordered the same way since it seems not useful

This changed the order of TestPrecompute and TestPrecomputeModel, mainly

`TestPrecompute.test_precompute`
`TestPrecomputeModel.test_precompute_dependencies_base`

After this pr, since class are not ordered by alphabetical order anymore, the `TestPrecomputeModel` is executed before `TestPrecompute`

This is a real bug in the test `test_precompute_dependencies_base`, after it's execution the field `registry['test_new_api.precompute.lowup']` is considered as `precompute=False`

This is because even if lower and upper are patched and rollbacked, the test will result in this stack

```
File "/home/xdo/osrc/master/odoo/odoo/addons/test_new_api/tests/test_new_fields.py", line 4406, in test_precompute_dependencies_base
    self.registry.get_trigger_tree(Model._fields.values())
  File "/home/xdo/osrc/master/odoo/odoo/modules/registry.py", line 401, in get_trigger_tree
    trees = [
  File "/home/xdo/osrc/master/odoo/odoo/modules/registry.py", line 404, in <listcomp>
    if field in self._field_triggers
  File "/home/xdo/osrc/master/odoo/odoo/tools/func.py", line 28, in __get__
    value = self.fget(obj)
  File "/home/xdo/osrc/master/odoo/odoo/modules/registry.py", line 498, in _field_triggers
    dependencies = list(field.resolve_depends(self))
  File "/home/xdo/osrc/master/odoo/odoo/fields.py", line 832, in resolve_depends
    warnings.warn(f"Field {self} cannot be precomputed as it depends on non-precomputed field {field}")
```

Just after this warning, the corresponding field is _hotfixed_ and the precompute value is changed to False. This change is not rollbacked in any way, since the class field is updated in this case.

The fix here is to reset the value.

```python
        def reset():
            Model.lowup.precompute = True
        self.addCleanup(reset)
```

**Comment by Xavier-Do** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
@robodoo rebase-ff

**Review by william-andre — COMMENTED** [review]
Just leaving a note: I know that some tests in web and tours expected to run the tests by inheriting the same class but with a different class attribute for the screen size

**Comment by Xavier-Do** [comment]
> Just leaving a note: I know that some tests in web and tours expected to run the tests by inheriting the same class but with a different class attribute for the screen size

Do you find the test in this list: https://runbot.odoo.com/runbot/build/56158117 ?

**Comment by william-andre** [comment]
@Xavier-Do For instance, `odoo.addons.point_of_sale.tests.test_frontend.MobileTestUi` doesn't seem to run anymore on the lastest runbots, but I can't find it on your list.

**Comment by Xavier-Do** [comment]
Yes this version of the list does not correspond to the last implementation, the last one removes the test even if added in the same file.

We can add the flag on those class to renenable them.

**Pull request closed without merging**
