### PR TITLE
[IMP] mail: make date format translatable

### PR DESCRIPTION
**Pull request by nim-odoo**
This allows to change the format of the date displayed in the chatter.

opw-651625

### CODE REVIEW

**Comment by nim-odoo** [comment]
As suggested, this works. For example, I loaded a French translation and changed the format to 'ddd dd MMM yyyy HH:mm'. It is now displayed as:

this.date.toString(_t('ddd MMM dd yyyy HH:mm'))
"mar. 13 oct. 2015 11:58"

**Comment by beledouxdenis** [comment]
I am just not sure about the change in the .pot, if it's a good thing to do it within this revision or if it's better to do in batch with other changes. We can probably ask @mart-e, our amazing translations expert, what is best :).

**Comment by mart-e** [comment]
Hmm probably not a good idea. If only we had locales or stuff like this to handle date formats ;-)

**Comment by nim-odoo** [comment]
@mart-e : why do you think it is not a good idea?

**Comment by mart-e** [comment]
The format `MMM dd yyyy` is not a string that you translate, it's something quite technical that you can't expect the translators (without the context) to understand that they need to put `dd MMM yyyy` if they want to get the days before the months in French.

The date format is specified on the `res.lang` object (I know, not in the same format) but it's not the purpose of translatable strings to change the format. In 8 we had `datejs` that was handling all the localisations differences. Not sure how for v9.
@csnauwaert didn't you worked on that?

**Comment by beledouxdenis** [comment]
Without that change this is currently not possible to change the format of the date time in the chatter.

Changing it to the format defined in `res.lang` cannot be considered as it will change the defualt date format for everyone.

If we want to be able to customize this format, this is the only option I see, even if this is technical.

This is done in other places, such as the date format in the website events.

**Comment by beledouxdenis** [comment]
See eabf7df5f9793d11b22fa5e9a43caf52822ea649.

**Comment by mart-e** [comment]
How about simply use `toLocaleString()` (e.g. result: "14/10/2015, 11:28:44" in en_UK) ?
Anyway, making the date format in chatter configurable (for instance using a translation) sounds like a new feature, shouldn't target 8.0.

**Comment by beledouxdenis** [comment]
Sounds to me like a feature as well, but considering the size of the patch, I considered it anyway.

**Comment by csnauwaert** [comment]
To answer @mart-e question, since saas-6 we don't use datejs anymore but momentjs, we have specific locale that are loaded with the library and you absolutely don't have to translate manually the date. Which is in my opinion not a correct solution.
When the user change it's language it will load the correct locale for momentjs and in your code if you use the right way to format a date then everything will be done for you. Here is an exemple (in browser terminal) you can try on runbot v9 with user language set in french:

> moment.locale()
< "fr"
> moment().format('ddd dddd DD MMM MMMM MM YYYY')
< "mer. mercredi 14 oct. octobre 10 2015"

for the list of complete format check this link: http://momentjs.com/docs/#/parsing/string-format/

As for what is done on the controller, I believe it would have been better to send the date and use momentjs to correctly display it to the user...

**Comment by beledouxdenis** [comment]
After a quick look, the issue is not solved in saas-6 either:
https://github.com/odoo/odoo/blob/saas-6/addons/mail/static/src/js/mail.js#L221

The format used for the chatter date will always be the same.

**Comment by nim-odoo** [comment]
@csnauwaert : this targets v8.0, therefore I don't think we can add a new JS library.

In 9.0, momentjs is indeed already used: https://github.com/odoo/odoo/blob/9.0/addons/mail/static/src/xml/thread.xml#L24

**Comment by csnauwaert** [comment]
@beledouxdenis 

you can use the format 'llll' instead of 'ddd MMM DD YYYY LT' if you want to print it in the locale format
> moment().format('llll')
"mer. 14 oct. 2015 11:48"

**Comment by beledouxdenis** [comment]
This would change the behavior suddenly (in the middle of a stable release) for everyone.

The solution suggested here as the advantage to not change the format to users that do not want it.

**Comment by csnauwaert** [comment]
Another solution for the 8.0 is to use Date.CultureInfo.formatPatterns
datejs also come with its globalization (check https://github.com/odoo/odoo/blob/8.0/addons/web/static/lib/datejs/globalization/fr-BE.js )

If you want to print a date based on a locale, you can use the formatPatterns defined in those, this is limited and you won't be able to print it exactly like you want but it is still better than translating the format.
In v8 with locale french installed and loaded:

> a = new Date()
Wed Oct 14 2015 12:00:00 GMT+0200 (CEST)
> a.toString(Date.CultureInfo.formatPatterns.fullDateTime)
"mercredi 14 octobre 2015 12:00:00"

**Comment by beledouxdenis** [comment]
This would also change the format for everyone, including for those that do not want the change.

**Comment by mart-e** [comment]
So if we don't want to change for everybody, let's not do anything at all. Sure it's not configurable but using translations is too hackish in my opinion. It's the same debate as creating hook methods everywhere, not for stable.

Then for following version, we can use momentjs or the browser information or a db parameter if we want it to be configurable.

**Comment by csnauwaert** [comment]
Just my opinion but right now we have the problem for every locale and be it in 8 or saas-6, changing the print format in order for the date to be correctly displayed in the current locale is not a problem. It won't change a thing for those that use odoo in US, but it will be correct in all other language, and I doubt that people will complain that the date is now readable in their language.. I agree with @mart-e that this fix is not the best way to do it and if we don't want to change the format to use locale then let's do nothing and fix it in master. After all it's not as if the date is not readable in french.

**Comment by beledouxdenis** [comment]
> Sure it's not configurable but using translations is too hackish in my opinion

 - This is already done elsewhere.

> It's the same debate as creating hook methods everywhere, not for stable.

- Not really. The format date are supposed to be customizable, according to the language, everywhere, this is not the case here.

> Then for following version, we can use momentjs or the browser information or a db parameter if we want it to be configurable.

- This is already the case in 9.0, as it uses the local, as shown by Nicolas (https://github.com/odoo/odoo/pull/9038#issuecomment-147993379)

The discussion here is to give this possibility in 8.0, without impacting all users. This could be seen as a new feature, so we could do nothing, but dates are supposed to be changed according to the language, this is probably one of the only places where the issue still occurs.

**Comment by xmo-odoo** [comment]
> This is already done elsewhere.

eabf7df is a very special case of formatting a date interval, res.lang has no configuration for that and babel doesn't have an API for that either (though LDML defines interval formats since UTS#35 Revision 10). That is not an issue for the situation here, we already have locale-specific datetime formatting.

**Comment by beledouxdenis** [comment]
Yes, except that using the local format:
 - Would change the behavior for everyone, and this is typically the kind of  thing we want to avoid in a stable release.
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean
 - Even if this is not supposed to happen, `datejs` could crash with some local: Nobody tested this librabry with all possibles locales, and a bug could therefore potentially be introduced in a stable release, and this is not acceptable.

**Comment by xmo-odoo** [comment]
> Would change the behavior for everyone, and this is typically the kind of thing we want to avoid in a stable release. https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

It would change the display format of a small UI element, not much difference from changing a button's padding because the current one is unsuitable for some locales.

Meanwhile this proposal adds translation files as part of the openerp configuration API and requires that users 1. somehow discover this one specific format is customised via translation files (rather than use either the in-database locale settings or some library's default for the locale) 2. are able to edit translations and 3. find out it uses datejs patterns. The original fix seems to be for the sake of saying the issue is fixed rather than for the sake of making this actually work.

> Even if this is not supposed to happen, datejs could crash with some locales: Nobody tested this librabry with all possibles locales, and a bug could therefore potentially be introduced in a stable release, and this is not acceptable.

Just do what the client did at the time and format using the relevant database settings? https://github.com/odoo/odoo/blob/8.0.0/addons/web/static/src/js/formats.js#L195

**Pull request merged**
