### PR TITLE
Master base balai tde

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Passons un coup de balai.

Task: https://www.odoo.com/web#id=37709&view_type=form&model=project.task&action=333&active_id=965&menu_id=4720

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
CC @antonylesuisse @rco-odoo

**Comment by antonylesuisse** [comment]
LGTM

**Comment by tde-banana-odoo** [comment]
I had the same question while doing it. I don't know where to put them, probably @antonylesuisse has an idea of how he would like to shape the odoo core.

**Comment by tde-banana-odoo** [comment]
@rco-odoo Just found I did not move base.sql . it is used outside of base but contains data related to base in sql. I think I would move it to base/data/base_data.sql, if you agree with it.

**Pull request merged**
