### PR TITLE
[FIX] website_event_meet: autovacuum method

### PR DESCRIPTION
**Pull request by rco-odoo**
Convert the override of method `power_on()` to an `@autovacuum` method.
This fixes the deprecation warning that apparently nobody cares about.

### CODE REVIEW

**Review by Julien00859 — APPROVED** [review]

**Comment by Julien00859** [comment]
Looks like the branch needs a rebase, there is a random test that is broken, I had the same test broken on another branch yersterday. FTR std has been made aware of the new api.autocuum decorator last week, so the "nobody cares about" is a bit harsh as he just didn't had the time to fix the problem yet.

**Comment by Julien00859** [comment]
rebased on latest v14

**Comment by rco-odoo** [comment]
> FTR std has been made aware of the new api.autocuum decorator last week, so the "nobody cares about" is a bit harsh as he just didn't had the time to fix the problem yet.

I did not mean to be harsh, that's why I wrote "apparently" :wink: 
I was a bit surprised that it took so long for someone to remove this deprecation warning...
Anyway, thanks for the quick review!

**Comment by rco-odoo** [comment]
> I was a bit surprised that it took so long for someone to remove this deprecation warning...

To be completely honest, I noticed the warning last week on some of my branches :smile:

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
