### PR TITLE
[FIX] l10n_in_edi: using sign instead of abs

### PR DESCRIPTION
**Pull request by bat-odoo**
Before this commit
==================
When we post a Customer Invoice by adding 2 products first one has a positive unit value and the second one has a negative unit value than the wrong JSON is generated.
The issue happens because of abs method converts the negative value into a positive.

After this commit
==================
In this commit, we are using the sign amount instead of the abs method.

Effected from this PR https://github.com/odoo/odoo/pull/99401

### CODE REVIEW

**Comment by bat-odoo** [comment]
Hello @jco-odoo 
I did changes, can you please check?
Thanks.

**Comment by jco-odoo** [comment]
@jco-odoo Which changes?  The param is still there.

**Comment by bat-odoo** [comment]
@jco-odoo I added a default argument for the sign so it doesn't affect method signatures.

**Comment by jco-odoo** [comment]
@bat-odoo I think there won't be an important perf impact if we do as @h4818 suggests, by checking the line.move_id.something within the method.  Normally, you only want to pass things you do not already know.

**Comment by bat-odoo** [comment]
@jco-odoo  if it won't be an important perf impact then it's ok for me. I will do changes as suggested.

**Comment by bat-odoo** [comment]
@jco-odoo Done.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@bat-odoo Do not we need it in earlier versions as well?

**Comment by bat-odoo** [comment]
@jco-odoo No need for Back-port. https://github.com/odoo/odoo/pull/99401 This PR is merged in `15.5`.

**Pull request closed without merging**
