### PR TITLE
[FIX] hw_escpos: xmlescpos add cp936(GBK) encoding support [CLA] Sign the Odoo CLA

### PR DESCRIPTION
**Pull request by mrshelly**

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Dear, 

Can you explain what your proposal brings, functionally speaking ?

With this PR, this is now possible to ?

**Comment by mrshelly** [comment]
@beledouxdenis 

1 My CLA commit.

2 hw_escpos modules's support USB Printer can not print chinese font. so just add the cp936(GBK) encoding.

**Comment by beledouxdenis** [comment]
Dear, 

How can we test this does solve your issue ?

What printer do you use ?

What do you configure to print Chinese font  ?

What do you print ?

Regards,

**Comment by mrshelly** [comment]
@beledouxdenis 
Q1: How can we test this does solve your issue ?
Chinese(simplified) OS and P.O.S odoo module and print any order. 

Q2: What printer do you use ?
I PR this just for chinese os end user.  REF: http://shine-it.net/index.php/topic,17116.0.html
and I commit it to py-xml-escpos REF: https://github.com/fvdsn/py-xml-escpos/pull/5/

Q3: What do you configure to print Chinese font ?
Ref: Q2

Q4: What do you print ?
Ref: Q1 

Thk 4u regards,

mrshelly
2015/07/02

**Pull request closed without merging**
