### PR TITLE
[FIX] web_editor: fix mail template toolbar in debug mode

### PR DESCRIPTION
**Pull request by jvnm-dev**
### Issue

- Install Mail template
- Enable debug mode (normal or assets)
- Create or edit a mail template
- Click in the text editor

The toolbar is not showing up (it does when we're not in debug mode)

### Cause

We are doing 
```javascript
options.toolbar.splice(-1, 0, ['view', ['codeview']])
``` 
In this case, toolbar is undefined, the method crashes and the toolbar doesn't render.

### Solution

Checking if the toolbar is defined before doing all that logic.

**OPW-2151675**

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
Hi @nle-odoo ,

Could check this, please? Thanks!

**Comment by nle-odoo** [comment]
also the code feature is rather error prone, so you should test:

- if you edit the message in wysiwyg mode => get in code mode : is the change you did in wysiwyg still there => if you save is the change you did still there

- if you edit the message in code mode => get in wysiwyg mode : is the change you did in wysiwyg still there => if you save is the change you did still there

- if you edit in code mode => is the change when you save still there

**Comment by jvm-odoo** [comment]
Should be good!
robodoo r+

**Comment by jvm-odoo** [comment]
robodoo rebase-ff

**Comment by jvm-odoo** [comment]
@nle-odoo

**Comment by nle-odoo** [comment]
robodoo rebase-ff

robodoo r+

**Pull request closed without merging**
