### PR TITLE
14.0 performance search one2many empty

### PR DESCRIPTION
**Pull request by mt-software-de**
The name_search of product_template was very slow
one problem was the search for product_variant_ids = False
here i changed the expression.py using postgresql "exists" instead of "id in (select ..."

as reference here the amount of data
- 297487 entries in product_template
- 299006 entries in product_product

### CODE REVIEW

**Comment by mt-software-de** [comment]
Yes i have mad an benchmark for it but with my other changes, 
i will fix the failing test benchmark it again. 
what do you guys prefer? should i change the pull request to an draft pull request?

**Comment by mt-software-de** [comment]
the code in the expression.py is a little messy i repeated myself with the exists sql statement
maybe i have time for it tomorrow

**Comment by rco-odoo** [comment]
Oh wait!
Please do not add comparison with `True`, as we never meant such a thing.
We don't add new features on existing versions, unless there is an actual need for it, and that is not the case here.
All we want is testing against `False`.
This does not limit expressivity, as `('a', '=', True)` should be written `('a', '!=', False)`.

**Comment by mt-software-de** [comment]
@rco-odoo Do you know if something's happening here?

**Comment by mt-software-de** [comment]
@rco-odoo as i have seen you implemented https://github.com/odoo/odoo/pull/82091
Could you please also merge or implement this code change

**Comment by rco-odoo** [comment]
@mt-software-de we can convert this case to use EXISTS, but we will not convert the other cases of one2many conditions, since there might be alias clashes between the main query and the subquery.

Can you please squash all your commits on the branch into a single commit?

**Comment by mt-software-de** [comment]
> @mt-software-de we can convert this case to use EXISTS, but we will not convert the other cases of one2many conditions, since there might be alias clashes between the main query and the subquery.
> 
> Can you please squash all your commits on the branch into a single commit?

Its done

**Comment by rco-odoo** [comment]
There should be a single commit.  Can you rebase your branch, please?  (Merging the target branch into yours is not the usual way we do it.)

**Review by rco-odoo — COMMENTED** [review]
Actually, your should have **two** commits:
* one for the CLA, with the commit message `[CLA] <your name>`
* one for the fix, with the commit message `[FIX] core: make one2many empty search use EXISTS`

The second commit message should also include some explanation on why the change was needed, such as performance benchmarks.

**Comment by mt-software-de** [comment]
> Actually, your should have **two** commits:
> 
>     * one for the CLA, with the commit message `[CLA] <your name>`
> 
>     * one for the fix, with the commit message `[FIX] core: make one2many empty search use EXISTS`
> 
> 
> The second commit message should also include some explanation on why the change was needed, such as performance benchmarks.

Ok thanks for your description

**Review by rco-odoo — APPROVED** [review]

**Comment by rco-odoo** [comment]
@robodoo rebase-ff r+

**Comment by odony** [comment]
This change in a stable version had side-effects that do significantly impact users in production, apparently: #88882

In general for each "performance fix" that modifies the core behavior of the ORM we should build a very strong case, including benchmarks and explain plan comparisons for the various code paths and categories of database populations. Depending on the kind of change, we should probably beta-test in real-life databases with realistic data volumes.

I known that's no small task, but the risk of creating performance regressions is not small 🤨

Cfr #81343 or #81344 for similar changes and discussions.

**Pull request closed without merging**
