### PR TITLE
[imp] web: Header of list view should be sticky on top of the view

### PR DESCRIPTION
**Pull request by vas-odoo**
make sticky header for only listview and m2m and m2o selection listview, for o2m which are displayed in form we do not make sticky headers as scroller will be on whole form view
Co-Authored by: Mohammed Shekha <msh@openerp.com>

Task :- https://www.odoo.com/web#id=38262&view_type=form&model=project.task&action=333&active_id=131&menu_id=4720

PAD :- https://pad.odoo.com/p/r.00683421860d31123f96ea4d7eed0142

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yajo** [comment]
I didn't review much deeply, but I'd say the easiest way to go would be:

1. Use [CSS `position: sticky`](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning) in [supporting browsers](https://caniuse.com/#feat=css-sticky).
2. Use a polyfill for non-supporting browsers. [Here's one](https://github.com/wilddeer/stickyfill).

I implemented this in the past (not in backend, though) and that simple CSS property is simply awesome.

Just my 2 cents.

**Comment by msh-odoo** [comment]
@Yajo for backend listview position: sticky is not enough, we want sticky header such a way that if we have horizontal scroll then header should scroll horizontally(while it should remain sticky), what if new record is added(editable listview) and added big description which changes cell width in that case header should respect new cell width

**Comment by msh-odoo** [comment]
LGTM

**Comment by rdeodoo** [comment]
@ged-odoo I don't want to close stuff that is not suppose to but you cancelled the task, can we close?

**Pull request closed without merging**
