### PR TITLE
Some code cleaning in the editor

### PR DESCRIPTION
**Pull request by qsm-odoo**
In preparation of https://github.com/odoo/odoo/pull/98429

### CODE REVIEW

**Comment by qsm-odoo** [comment]
Hello @odoo/rd-framework-editor can someone validate this very small cleaning (and potentially merge) as soon as possible? Thank you :pray:

**Comment by dmo-odoo** [comment]
LGTM for the first one but the second one looks to specifically undo something that @Goaman did on purpose so I'd like to have his opinion on it.

**Comment by Goaman** [comment]
Hello 👋 
`this.$root` is a relic. We can let it go.

**Review by qsm-odoo — COMMENTED** [review]
Thanks :+1: 

@robodoo rebase-ff r+

**Pull request closed without merging**
