### PR TITLE
[IMP] website_sale: auto publish products

### PR DESCRIPTION
**Pull request by vchu-odoo**
users who create products from the website are intended to make it visible immediately for customers 

task-3234684

### CODE REVIEW

**Review by Demesmaeker — CHANGES_REQUESTED** [review]
Hello :duck: 

Wouldn't it be easier to override `_default_is_published` on the products to set it as True when necessary?

**Review by Demesmaeker — CHANGES_REQUESTED** [review]
Hello :duck: 

Better and simpler, but still, wouldn't it be possible to override this directly: https://github.com/odoo/odoo/blob/321d16950ee9dcf4d722ecbfe0a49ca8f7d855a6/addons/website/models/mixins.py#L195-L196
With a check on the website_id in the context to ensure only products created from the website are published by default?

**Comment by vchu-odoo** [comment]
> Hello 🦆
> 
> Better and simpler, but still, wouldn't it be possible to override this directly:
> 
> https://github.com/odoo/odoo/blob/321d16950ee9dcf4d722ecbfe0a49ca8f7d855a6/addons/website/models/mixins.py#L195-L196
> 
> 
> With a check on the website_id in the context to ensure only products created from the website are published by default?

The action triggers from js, not python side. So I can not do it directly or I have not found the way.

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
