### PR TITLE
[IMP] point_of_sale: hide categories on scroll

### PR DESCRIPTION
**Pull request by vlst-odoo**
In this commit we improve the mobile experience for the product
screen in POS.

Previously, products and categories would be shown on 2 different pages
through which the user would have to navigate.

Now, categories are shown at the top of the page, right before the
products. This is similar to what we have in version 17.0, only that now
the products are part of the div on which the user is scrolling. This
means that when scrolling while looking for a specific product, the
categories will also scroll up, leaving more space for the grid of
products.

Task: 3784119
Before ( category page ):
image
Before ( products page ):
image

After (products and categories on the same page):
image

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by caburj — APPROVED** [review]
robodoo r+

**Comment by caburj** [comment]
robodoo retry

**Comment by vlst-odoo** [comment]
robodoo retry

**Comment by caburj** [comment]
manually triggered l10n test and it's green also

robodoo r+

**Pull request closed without merging**
