### PR TITLE
[FIX] Mix of taxes w/ price included/excluded should never be allowed

### PR DESCRIPTION
**Pull request by wtaferner**
Description of the issue/feature this PR addresses:
As the tax computation on a single line in compute all does only have a single price unit as a base it should never be possible to mix brut and net on the same price unit and line.

Current behavior before PR:
Mixture of net and brut taxes is allowed

Desired behavior after PR is merged:
Mixture of net and brut taxes is prohibited and throws an UserError

@nim-odoo 
Here is another one...I guess it is kind of straight forward from a logical point of view, but if you think it should be allowed please give me a valid use case where we actually want to have this and that the calculation based on this would be still correct.

You can also consider this as a starting point if you have a better solution in mind.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
OPW-691684

**Comment by nim-odoo** [comment]
I don't see any good reason to forbid the user to do such a thing since:
- the use case is supported
- it would break the system for users having such a configuration

**Comment by wtaferner** [comment]
Can you please explain in numbers and use cases how this can be supported or if you just don't care about the output? It is impossible to have a price unit which is tax included and excluded at the same time and line

**Comment by wtaferner** [comment]
@nim-odoo 
I am still not convinced that your not yet presented and supported use case is correct...I did another detailed test and saw that if you check the "Included in Price" the "Affect Base of Subsequent Taxes" is checked automatically on change as well and based on this the calculation seems correct (is this the use case which is supported?), but as soon you uncheck the "Affect Base of..." it just gets wrong in the combined calculation.

And the tax included was computed always at the end of the sequences, so the affect checkbox was just for fixing the net total at the end...so imo, we need to tackle this otherwise it is open to support a mix which is mathematically incorrect by what you configure.

What do you think? Should we just improve this PR to fix this issue by informing/blocking the user about this inconsistency or should we improve the generic algorithm that this is supported as well?

**Use Case I talk about**
Unit Price: 100
Tax 1: 10% (percentage) price excluded -> 10
Tax 2: 10% (percentage) price included + affect base -> 9,09
Total: 110 (correct)

Same set with Tax 2 without affect base
Tax 1: 9,09
Tax 2: 9,09
Total: 109,09 (wrong)

**Comment by nim-odoo** [comment]
> Same set with Tax 2 without affect base
Tax 1: 9,09 (supposedly 10 in the calculation, but it does not sum-up like this)
Tax 2: 9,09
Total: 109,09 (wrong)

Obviously here, the tax 2 (included) has been applied before the tax 1, otherwise the results are not what you pretend they are:

```
name           included?  Affect base   base   amount
Tax 10 % incl  True       False         90.91  9.09
Tax 10 % excl  False      True          90.91  9.09
Total included:  109.09


name           included?  Affect base   base   amount
Tax 10 % incl  True       True          90.91  9.09
Tax 10 % excl  False      True          100.0  10.0
Total included:  110.0


name           included?  Affect base   base   amount
Tax 10 % excl  False      True          100.0  10.0
Tax 10 % incl  True       False         100.0  10.0
Total included:  110.0


name           included?  Affect base   base   amount
Tax 10 % excl  False      True          100.0  10.0
Tax 10 % incl  True       True          100.0  10.0
Total included:  110.0
```

**Comment by wtaferner** [comment]
Ok, thank you for doing the numbers and therefore rational...based on this I can finally accept that this is supported on an isolated invoice line level. Sorry, but I really needed this proof...my testing obviously played tricks on me as the local client used the wrong sequences on the invoice line as not updating them while updating the whole tax lines (at least this would explain why I was convinced that the sequence was right as I actually checked them via a second tab twice).

Therefore, I am ready to let it go again...even though I am still very unsatisfied with the mixture of the price (included/excluded) on the product.

I think it would help if someone can indicate whether the price is net or brut on a product level otherwise it is not clearly defined anywhere. And we can not assume that the taxes are always configured correctly. They actually just work as you proofed in relation to the unit price but not in relation to a product.

Do you know what I mean? Probably something for the usability team and master...but I want to have this at some point straight and consistent.

**Pull request closed without merging**
