### PR TITLE
[FIX] lunch: Use extra toppings without problem

### PR DESCRIPTION
**Pull request by macadelic80**
1) Extra Items

    Issue: Adding an extra to one menu item, automatically adds it to the other food items in the same order.

    Expected Behavior: When adding an extra, it should only be associated to
    the food item for which it was selected, and NOT applied to the other ordered items.
    For example, if I select a "Ranch" dressing for the "Chef Salad",
    the ranch should not appear as an extra for the "Cheeseburger" or "Cookie of the Day".

2) Unable to Submit Certain Orders

    Issue: Odoo prevents the user from submitting an order in the following case
    (better illustrated through an example). If you select a "Chef Salad", you will be prompted to select a "Dressing Choice",
    because the configuration is set to select one and only one extra.
    You cannot add the salad to the cart without selecting a dressing,
    nor can you proceed if you have more than one dressing selected;
    this is functioning as expected. The problem, however, comes when you
    select a dressing and add the salad to the cart, and now you try to add a
    dressing as its own order item (separate from any salad). Even though the
    salad has its own dressing selected, and the separate dressing is its own item,
    the error message: "You have to order one and only one Dressing choice" appears and
    prevents the order from being submitted. This issue may be a consequence of the behavior observed in the first issue.

    Expected Behavior: The user should be able to submit the order in
    this case because the salad had only one dressing associated with it,
    and the extra dressing is supposed to be its own item.
    This should not create a conflict with the "only one" extra logic.

Step to reproduce (video: edv)
Reproducible on runbot.
1) Extra Items
https://drive.google.com/file/d/1yos9coFqd55pq8qNbNs1OqGNMNSdgxDX/view

2) Unable to Submit Certain Orders
https://drive.google.com/file/d/1M0ZEElu-hYwU9bmCwEx_tqEZRAPG_UEt/view

opw-2391070

### CODE REVIEW

**Comment by abz-odoo** [comment]
Hello @Feyensv What do you think about this fix ?

**Comment by Feyensv** [comment]
I'm not knowledgeable on the lunch scope, why did you ping me ? :thinking:.

**Comment by abz-odoo** [comment]
I thought I saw that you contributed to this module, sorry !

**Comment by Feyensv** [comment]
No problem, I've modified a lot of files everywhere ^^.
The change LGTM, but since I don't know the scope well, you should ask @tivisse instead ;).

**Comment by abz-odoo** [comment]
@nle-odoo

**Comment by abz-odoo** [comment]
@tivisse

**Review by nle-odoo — APPROVED** [review]
if it's wanted behavior, looks good

the comment:

```py
        # Only write on topping_ids_1 because they all share the same table
        # and we don't want to remove all the records
        # _extract_toppings will pop topping_ids_1, topping_ids_2 and topping_ids_3 from values
        # This also forces us to invalidate the cache for topping_ids_2 and topping_ids_3 that
        # could have changed through topping_ids_1 without the cache knowing about it
```

refer only to the code changed, so this should probably also be moved as well.

when you are happy with it, you can r+ (unless there is other opinions):

robodoo delegate+

**Comment by abz-odoo** [comment]
robodoo r+

**Pull request closed without merging**
