### PR TITLE
Fix bug when convert date

### PR DESCRIPTION
**Pull request by manhg**
Description of the issue/feature this PR addresses:
Broken when accessing calendar

Current behavior before PR:
Broken converting utf8
Desired behavior after PR is merged:
Get it fixed

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
The decodes are probably there for Python 2 (IIRC strftime always returns a native `str` which would cause issues in P2 as it would be encoded bytes rather than text).

The decodes should be replaced by `pycompat.to_text` rather than just removed, they were probably missed during the original conversion.

Alternatively the entire thing could be moved over to babel, but that's a more significant change.

**Comment by manhg** [comment]
That's true, but is Odoo 11+ supposed to be Py3 only?

**Comment by xmo-odoo** [comment]
At this point, we are trying not to break Python 2 compatibility unless we actually have to.

**Comment by xmo-odoo** [comment]
You need to sign the CLA by the way.

**Comment by xmo-odoo** [comment]
Whelp, looks like in the meantime it was fixed separately (along with some other issues) in f5df4fbca1d6dce4f98cdb6b27bee3fb843febf4, sorry about that.

Do you want me to merge your CLA anyway so it's already here if you decide to contribute further?

**Comment by manhg** [comment]
Thanks! I think SLA will be merged in #20278

**Pull request closed without merging**
