### PR TITLE
Respect limits on batch size when processing mail queue.

### PR DESCRIPTION
**Pull request by yajo**
When using the module `crm_mass_mailing`, the parameter `mail.batch_size` is not respected.

This little patch fixes that in any module that uses the mail queue, and as such, it allows the administrator to set up limits that will avoid some SPAM filters.

### CODE REVIEW

**Comment by Yajo** [comment]
Hello, is there anything left to be done with this PR? Thanks.

**Comment by pedrobaeza** [comment]
@beledouxdenis, can you please check this easy one?

**Comment by beledouxdenis** [comment]
Dear, 

This is a feature, it doesn't solve a blocking bug.

Only proposals solving actual blocking issues are allowed in stable release, such as 8.0.
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

Of course, in some cases, when this is no alternative for instance, we can make exceptions.

In this case, there is an alternative: In a multi-worker environment, set the --limit-time-cpu parameter of your server to any value you want, such as 20/30 minutes (as we do), so the email queue scheduled task is killed every 20/30 minutes, and then relaunched later according to your cron configuration. You will say this is quite technical and requires some technical skills, but so does setting the "mail.batch_size" value in System parameters: Without knowing this value, or digging in the code, it's just impossible to know it.

Besides, setting the batch_size to 500, but setting your email queue scheduled time to 1 minute, will just be useless.

You mention "it allows the administrator to set up limits that will avoid some SPAM filters.": Do you have any "official" documentation regarding that ? Explaining how the algorithm to detect SPAM work ?

Regards,

**Comment by Yajo** [comment]
Well, [I'm just implementing an already existing feature](https://github.com/odoo/odoo/blob/8.0/addons/mail/wizard/mail_compose_message.py#L227). It's already undocumented, so that's not my fault, but I'll be glad to modify the README if you wish.

However, if any admin, after discovering that hidden feature, uses it, he will discover that it is ignored in the `crm_mass_mailing` module, where it's most useful. IMHO, if there's a feature that does not work as expected (admin POV), that's a bug.

This happens because the setting is only used in a wizard. But Odoo sends many e-mails from many places.

Setting it to 500 and scheduled time to 1 min can be useless or not, depending on your mail provider rules, but that's admin's job. Anyway, [there's a hard-coded limit of 500 mails per batch when using `mail.compose.message`](https://github.com/odoo/odoo/blob/8.0/addons/mail/wizard/mail_compose_message.py#L50), so in other words that piece of code is useless. Then why not replace it by this patch, which is useful? I could remove it if you wish.

About `--set-limit-cpu`, either the docs are wrong or I'm misunderstanding something, but it sounds to me like you meant `--limit-time-real`, and anyway it applies to HTTP workers. However, when the server processes the mail queue, no HTTP is involved. It's a cron job running in the background.

About SPAM rules, they are very subjective, but I can refer you to [1and1.es mailing rules](http://ayuda.1and1.es/correo-c64733/1y1-correo-electronico-c85123/para-comenzar-c64734/cantidad-de-e-mails-que-puede-enviar-a-la-misma-vez-a694502.html) as a real life example. I'll translate:

> ### Number of e-mails that can be sent at the same time

> By using mail servers of 1 & 1, you will not be able to send e-mails to more than 1,000 recipients in the same shipment and more than 300 recipients every 5 minutes. A waiting period of at least 10 seconds between sending necessary. These restrictions are established to avoid spamming.

> Note that you can send up to 300 e-mails every 5 minutes, which is equivalent to 60 e-mails per minute. To keep your submissions below these limits we recommend you send an e-mail per minute with up to 55 recipients.

> If you are sending your e-mails through a script of your web space using mail servers of 1 & 1, the above limits shall apply. If you use your own mail servers have no restrictions on the issuance by us.

> Remember that if you do send mass e-mail (mailings, newsletters) is required to include a link for recipients to be disenrolled from the mailing list and you remove your e-mail for future shipments.

In such case, the admin sets:

- ir.config_parameter `mail.batch_size`: 55.
- ir.cron `mail.ir_cron_mail_scheduler_action`: interval_number: 1, interval_type: minutes.

And no blocking at all, wherever Odoo sends the e-mail from.

**Comment by beledouxdenis** [comment]
The current `batch_size` feature is not meant for the feature you want, it's entirely dedicated for this specific wizard, to avoid the web client to reach the time out limit and raise this error in the user face when he validates it.

The current `batch_size` is not meant at all to limit the number of emails per minute, for spam control.

**Comment by pedrobaeza** [comment]
But don't you think it can be used also for this purpose? There's no other mechanism to make this restriction as @Yajo said, so we are all struggled by this real problem imposed by our mail providers on all our v8 systems.

**Comment by beledouxdenis** [comment]
It could, but, as I said, this is then a feature. Adding features in stable release is really restricted without further discussions.

In 1and1 case mentioned by Yajo:
> By using mail servers of 1 & 1, you will not be able to send e-mails to more than 1,000 recipients in the same shipment and more than 300 recipients every 5 minutes. A waiting period of at least 10 seconds between sending necessary.

In the case of a mass mailing, the emails are sent one by one, as the language, or even the content, can be different per recipient. There is never 1000 recipients for a same mass mailing email.

So the case `1,000 recipients in the same shipment` is definitely out of the loop for the mass mailing.

Regarding the other limit: `300 recipients every 5 minutes`. As there is a limitation of `10 seconds between sending`, 300 * 10 seconds = 3000 seconds, ten times more than 5 minutes. This second limit is therefore as well excluded.

I therefore see no reason to add such as feature for this case.

**Comment by pedrobaeza** [comment]
OK, can you tell me where's the 10 second delay?

Do you think this is interesting for v9/master?

**Comment by beledouxdenis** [comment]
> OK, can you tell me where's the 10 second delay?
Well, it's not in Odoo, I just read the 1and1 documentation Yajo shared.
> A waiting period of at least 10 seconds between sending necessary.
I guess they do it with a timeout, when you tried to send two emails, I make you wait 10 seconds between the first and the second.

>  Do you think this is interesting for v9/master?
Only if a real use case is found.

**Comment by wtaferner** [comment]
I agree with Pedro. Unrelated to this PR I think it is useful to have the possibility to define the number of mails sent in a certain time frame...I think it would be best to implement this for the outgoing mail server itself (it should be even possible to work with load balancing) and use priorities for queued mails.

**Comment by wtaferner** [comment]
Use case is very common for provider with policies to prevent spam suspicious behavior of a few on shared servers and keep integrity and not being put on anti spam lists due to some users and used client software which does not care how many mails it sends at once.

**Comment by pedrobaeza** [comment]
@wtaferner, we can work in another approach for master to implement as you say in the outgoing mail server, but for v8 and now that the layout freeze is done also for v9, we can think in this as a harmless workaround to work with these limitation.

Although the 1&1 provider itself is contradictory in its own limits (you can overpass one limit having the other), you can't program your Odoo to deal automatically with the limits. If the mail send task is refused because the 10 seconds limit, you'll have a bunch of mails in error state until 10 second pass, and you'll have to re-schedule them.

Don't you think it deserves to put this to allow some kind of control?

**Comment by beledouxdenis** [comment]
> Use case is very common for provider with policies to prevent spam suspicious behavior of a few on shared servers and keep integrity and not being put on anti spam lists due to some users and used client software which does not care how many mails it sends at once.

Find me a case where you indeed reached  the limit using the mass mailing module, and then I could consider it. A said, the 1and1 case is just impossible to reach with the Odoo mass mailing.

**Comment by wtaferner** [comment]
@beledouxdenis 
https://www.hetzner.de/en/hosting/legal/system-policies-ws which is very often used by SME/PME/KMU

@pedrobaeza 
Why not, should not be too hard I guess...although I do not know the details as I was trying to avoid most of the time the social mail implementation of Odoo earlier, but it was getting better lately so this could give more control to the users/admins/system

**Comment by wtaferner** [comment]
Ok guys, I was motivated about this (https://github.com/odoo/odoo/pull/8725)...I targeted v9 although I added some fields. As it is a quite sensible topic I would appreciate your reviews and of course it would be awesome to get such a feature merged before release.

**Comment by Yajo** [comment]
FTR, I was banned by Gmail last week after I opened one new account and configured it in Odoo 8.0 and used it just for 1 user.

**Comment by pedrobaeza** [comment]
Any news about this? @beledouxdenis, what do you think about the use cases?

**Comment by rafaelbn** [comment]
We must care about this issue @Yajo @pedrobaeza @antespi

**Comment by Yajo** [comment]
@Tecnativa

**Comment by rafaelbn** [comment]
What could we make?

**Comment by Yajo** [comment]
@antespi Can a queue be added to https://hub.docker.com/r/tecnativa/postfix-relay/?

**Pull request closed without merging**
