### PR TITLE
[FIX] mail: fix flickering of unread counter of legacy livechat

### PR DESCRIPTION
**Pull request by xdu-odoo**

### CODE REVIEW

**Comment by seb-odoo** [comment]
How do I reproduce the flicker? I'm not having it on the banner branch, but new message on the livechat part isn't updating either.

**Comment by xdu-odoo** [comment]
I don't remember well but send a message from the admin side and wait in the public side, the (1) should not appear, then when you start typing a new message (or send a new one in the public side) the (1) would appear and disappear. In fact, the problem was that the inbox counter is updated after the re-render so the inbox counter is correct when the next re-render is triggered

**Comment by xdu-odoo** [comment]
@seb-odoo In saas-13.4, open two pages :
- A : admin/admin
- B : visitor

With visitor, talk in the livechat to enable a livechat session for admin then fold the chat window.
With admin, send a message in the livechat.
Normally you should have (1) in the chat window title but you don't.

Do it with this branch and you would get it.
Initially the (1) was showing when you unfolded the chat window and hiding rightaway or when you were typing as typing notification were handled as a new message.

**Review by seb-odoo — APPROVED** [review]
Fixed commit (missing task, description how to reproduce, and wrong module name).

@robodoo r+

**Pull request closed without merging**
