### PR TITLE
[IMP] account, website_sale: remove 'remove me' code.

### PR DESCRIPTION
**Pull request by Feyensv**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by MiquelRForgeFlow** [comment]
ci is red

**Comment by Feyensv** [comment]
Yep, have to rebuild it (and do migration scripts for the enterprise PR)

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
