### PR TITLE
[16.0][FIX] account: account type of cash diff gain

### PR DESCRIPTION
**Pull request by ngochung207**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by william-andre** [comment]
Would you mind explaining why this is more correct?

**Comment by william-andre** [comment]
After discussion with the product owners, it looks like you are right.
I would like to see the explanation in the commit message though. Thanks for the contribution!

**Comment by ngochung207** [comment]
> After discussion with the product owners, it looks like you are right. I would like to see the explanation in the commit message though. Thanks for the contribution!

@william-andre I have completed it.

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
