### PR TITLE
12.0 [REF] product: Check Pricelist Rule Method

### PR DESCRIPTION
**Pull request by CarmenMiranda**
Adding the method `_check_pricelist_rule` to check if the item is a suitable one for the quantity that is going to be need it, a certain product, uom, and partner if all the conditions pass we are returning the rule's price for the product.
If the rule isn't suitable we are returning a False value.

This change will help us when we want to add a new validation, so we don't have to overwrite the method `_compute_price_rule` just to add a simple validation.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
Signed-off-by: Carmen Miranda (CarmenMiranda) <carmen@vauxoo.com>

### CODE REVIEW

**Comment by CarmenMiranda** [comment]
Hi, @moylop260 Could you review these changes? Please

**Comment by CarmenMiranda** [comment]
Hi, @JulioSerna Could you review this?? Please :smile:

**Comment by CarmenMiranda** [comment]
Hi, @luisg123v Could you review these changes? Please :smile:

**Comment by JulioSerna** [comment]
@CarmenMiranda 

LGMT 👍 
This change will be really helpful to allow make this method inheritable


@moylop260

**Comment by moylop260** [comment]
@nhomar 

Could you approve please?

**Comment by CarmenMiranda** [comment]
Closing MR because is not needed anymore, since we can make it as the OCA did on the module [`product_pricelist_supplierinfo`](https://github.com/OCA/product-attribute/blob/e9e0aa0b8c3aa019106c653dba1a475847b1687e/product_pricelist_supplierinfo/models/product_pricelist.py#L22)

**Pull request closed without merging**
