### PR TITLE
[FIX] requirements-check: various fixes

### PR DESCRIPTION
**Pull request by Xavier-Do**
The main goal of this pr is to adapt the requirements to make it work in ubuntu Noble (right now, it will only work when using debian packages)

## FIX requirements_check.py
The first step is to adapt and fix the requirements_check in order to have an overview of the current state.

old

This is showing the difference between an installation from pip compared to the official packaged version in the distribution matching the same python version. Red usually means that the package in the corresponding version has a higher version than the pinned one. We expect to have almost the same version as the corresponding minimal supported python version. It is possible that some version are higher (yellow) for historical/security/compatibility reasons.

## Adapt requirements.txc

We don't need to fix all versions, but we want to adapt it to work in most cases, mainly we need to be able to install the requirements on ubuntu Noble. If a change is needed, the version of the requirement for 3.12 is pinned to match the version of the package in ubuntu Noble. 

### greenlet
The first change concern greenlet and gevent, the current version does not install on python 3.12

### Missing wheel
The second changes adapt all packages that did not have a wheel in 3.12. Some of them fail to build, and building them is slow. 

### Non compatible packages
Finally, some package are not compatible, leading to import error or requirements install errors

###  New state after requirements changes

out

Since the requirements versions are the same as the debian package version we  expect the build with requirements to be green similar to the PureNoble builds. 

### Fix win32 wheel

Building wheel on windows is painful because c++ builds tools are quite heavy and not included. 
Most of the version pinned in 3.12 will have a wheel on win32, except got gevent and greenlet. Since they are not required to run odoo, removing them for win32

### CODE REVIEW

**Comment by chapital** [comment]
Hi @Xavier-Do, Im working with 3.12, only have 2 issues detected, 1.- when I try to import a xls file I receive a error because 3.12 have xlrd 2.0 module and odoo only works with xlrd 1.0 (1.2.0), the second error I dont know if it related with 3.12, but when I check the status of odoo in linux (service odoo status), I receive a warning: Can't find .pfb for face 'Courier', I hope this info are useful for your PR, Thanks

**Comment by Xavier-Do** [comment]
Hi @chapital 

Thanks for your feedback


>  when I try to import a xls file I receive a error because 3.12 have xlrd 2.0 module and odoo only works with xlrd 1.0
I guess that we don't have a test for that, but indeed we should adapt odoo to work with xlrd 2.0, thanks for the feedback! 

>  (1.2.0), the second error I don't know if it related with 3.12, but when I check the status of odoo in linux (service odoo status), I receive a warning: Can't find .pfb for face 'Courier', I hope this info are useful for your PR, Thanks

Strange, looks like a font is missing. It is strange that it is in the status, it doesn't appears in the logs? Maybe a missing font but i will ignore this one for now :)

**Comment by Xavier-Do** [comment]
Hi @chapital could you provide a sample xls file?

**Comment by Xavier-Do** [comment]
@robodoo override=ci/security
External script not used in odoo (xmo told he is ok, cc @rd-security)

@robodoo rebase-ff
@robodoo skipci
This will conflict in all version but shouldn't fail in normal tests, this will help to go faster to adapt requirements in each version that conflict.

**Comment by Xavier-Do** [comment]
@robodoo fw=skipci
Is that correct mr bot?

**Comment by d-fence** [comment]
robodoo r+
requirements were carefully reviewed

**Comment by moylop260** [comment]
@Xavier-Do @xmo-odoo 

FYI pycairo is required for reportlab 4.0+

More info about:
 - https://github.com/odoo/odoo/pull/200494


and `libcairo2-dev` apk package is needed:
 - https://github.com/odoo/documentation/pull/12291

I have created the PR to 18.0 because it is where I have detected an issue printing images but let me know if I should use 15.0 branch

Regards!

**Pull request closed without merging**
