### PR TITLE
[FIX] website_event: Prevent block title to be edited

### PR DESCRIPTION
**Pull request by macadelic80**
Issue

    - Install "Website" and "website_event"
    - Try to add Event block

    The title is editable

Cause

    The contentEditable attribut is enabled

Solution

    Disable the contentEditable attribut

opw-2367538

### CODE REVIEW

**Comment by abz-odoo** [comment]
@nboulif

**Comment by nboulif** [comment]
@abz-odoo LGTM. Little note though :
- I think it will be better to target the title `o_wevent_sidebar_title` to be more specific regarding the ticket spec and your commit (like we discussed in MP)
- Also, I think you can set `disabledInEditableMode` to `true` , it will avoid to have an editable widget and mislead customer (the event titles are editable even if not saved) since, for now, there is no editable options for this block: 
https://github.com/odoo/odoo/blob/398ebb02a25a9c0b641298513474732779f16d28/addons/website_event/static/src/js/website_geolocation.js#L8

@nle-odoo maybe a better idea ? :wink:

**Comment by qsm-odoo** [comment]
> Also, I think you can set disabledInEditableMode to true , it will avoid to have an editable widget and mislead customer

No, the goal of our wysiwyg editor is to give a correct preview to the user in edit mode :wink: This should thus not be disabled in edit mode. Just make the entire dynamic content not editable :wink:

**Comment by abz-odoo** [comment]
@nboulif

**Comment by nboulif** [comment]
@qsm-odoo r+ ?

**Review by nle-odoo — APPROVED** [review]
looks good since the content is replaced by the RPC call, but maybe this could be put directly in XML

```diff
diff --git a/addons/website_event/views/event_snippets.xml b/addons/website_event/views/event_snippets.xml
index 15634348006..13412a5e8e3 100644
--- a/addons/website_event/views/event_snippets.xml
+++ b/addons/website_event/views/event_snippets.xml
@@ -3,7 +3,7 @@
 
 <!-- Snippet - Country Events - Placeholder -->
 <template id="s_country_events" name="Events">
-    <div t-attf-class="s_country_events_list oe_country_events #{_classes}">
+    <div t-attf-class="s_country_events_list oe_country_events #{_classes}" contenteditable="false">
         <div class="country_events_list">
             <h6 class="o_wevent_sidebar_title">
                 <i class="fa fa-globe mr-2"/>Upcoming Events
```

since the route `/event/get_country_event_list` should always return content, this should be equivalent

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by nle-odoo** [comment]
robodoo r+

I updated to not have `'False'` in javascript (seemed to work but it's cleaner not to do it):

```diff
-                self._$loadedContent.attr('contentEditable', 'False');
+                self._$loadedContent.attr('contentEditable', false);
```

**Pull request closed without merging**
