### PR TITLE
[FIX] web_editor: Do not prompt when leaving in backend

### PR DESCRIPTION
**Pull request by Arcasias**
Task [2371592](https://www.odoo.com/web#id=2371592&action=333&active_id=133&model=project.task&view_type=form&cids=1&menu_id=4720)

### CODE REVIEW

**Review by aab-odoo — APPROVED** [review]
This seems ok, but I would like someone from the Editor team to double check.

cc @dmo-odoo

**Comment by dmo-odoo** [comment]
cc @Zinston used to keep the previous logic and just adapt it a bit to our case. It is possible that we made a mistake and that we did not handle the backend case properly, but I'm surprised the fix would involve so many changes to be honest. I'll let @Zinston have a look since he's the one who adapted this code to the new editor.

**Comment by Zinston** [comment]
> @Zinston used to keep the previous logic and just adapt it a bit to our case. It is possible that we made a mistake and that we did not handle the backend case properly, but I'm surprised the fix would involve so many changes to be honest. I'll let @Zinston have a look since he's the one who adapted this code to the new editor.

Some context. The decision in concertation with team website had been to always warn, whether there had been a change or not. So I removed the `if` that checked if the editor was dirty. In the meantime we discussed the fact that it was problematic in the backend and @Arcasias started working on this PR.
The general approach seems alright to me here. Now, I get that there are changes that aim to get the value of the editor, so that you can check that before deciding whether you show the dialog or not. But I don't see this actually being used so I expect the dialog would show every time. That's ok if that's the spec but then these changes are irrelevant.

Also, what happens when you change apps without reloading? Eg:
1. Open module `note`
2. Create a new note
3. Write something
4. Click on the button to return to the list of apps (doesn't reload the page)
5. Ctrl+F5
Do you get the dialog then?

**Comment by Zinston** [comment]
What's the status of this PR? @Arcasias ?

**Comment by Arcasias** [comment]
@Zinston actually the wysiwyg value changes are related to another problem. The two problems are:
- prompting the user in any situation, as discussed we only want this in the front-end (changes in `wysiwyg.js`)
- flagging a field HTML as dirty, resulting in the Settings app to show a "_Unsaved changes_" message for example (changes in `field_html.js`).

Although now that I'm writing this I realize it would be clearer if the PR was split in two separate commits since the issues are not really related.

**Comment by Zinston** [comment]
@Arcasias Seems alright to me, thanks for splitting into two commits. I just tested the flow I described above and I indeed don't get a prompt but I notice the prompt is just entirely gone from backend (which matches your PR title ^^). I thought this was supposed to make it so you would always get prompted in website but only if dirty in backend. Just to be sure, who made this spec? I'm just worried people will complain if the feature is just completely gone from the backend.

**Pull request closed without merging**
