### PR TITLE
[FIX] Delete unknown git file

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
It was included in https://github.com/odoo/odoo/commit/9bdf129ac606d672fb33deb972fd4df86d4bc1e7 by some oversight.

Affected versions: only v13.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@mart-e

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Comment by MiquelRForgeFlow** [comment]
avoid forward port

**Comment by william-andre** [comment]
@fw-bot disable

**Comment by william-andre** [comment]
@fw-bot ignore

**Pull request closed without merging**
