### PR TITLE
Name of two spanish states were not correct in res.country.state.csv

### PR DESCRIPTION
**Pull request by js-landoo**
Description of the issue/feature this PR addresses:
Name of two spanish states were not correct in res.country.state.csv
Gipuzkoa and Araba

Current behavior before PR:
In states list, "Gipuzkoa" is shown as "Guipuzkoa"

Desired behavior after PR is merged:
To show "Gipuzkoa (Guipúzcoa)"
And
"Araba (Álava)"

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@js-landoo Thanks for the feedback.

Your issue has been merged in 10.0 at https://github.com/odoo/odoo/commit/366c1e307f0ee5853f1ce244534a93a38bd0b34e

I removed your individual CLA declaration as it was using your corporate address. Don't hesitate to make another individual CLA declaration when you propose a PR for yourself next time. 

Have a nice day,

Yannick.

**Comment by pedrobaeza** [comment]
The official name is Araba/Álava, as it was discussed in https://github.com/odoo/odoo/pull/15166#issuecomment-274495798. The other one is correct.

**Comment by tivisse** [comment]
@pedrobaeza Partly reverted at https://github.com/odoo/odoo/commit/22755463bbadfaaa8c84a2b53c3772289081e207

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request closed without merging**
