### PR TITLE
[11.0][maintenance] - allow CRUD on maintenance team to equipment manager

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This is already in 12.0, added in https://github.com/odoo/odoo/commit/d0e2caee4e046bb38a091320908e9c1ea3e26187#diff-1610655b3da7f9782f5317320298ec59R10

cc @tde-banana-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
cc @sle-odoo

**Comment by mart-e** [comment]
But it was in 12.0 because it was useful in the code you show.
Why do you need it in 11.0 ?

**Comment by jbeficent** [comment]
@mart-e  because the equipment manager cannot create or edit teams. Only the superuser.

**Comment by mart-e** [comment]
Oups sorry, I was confused by the bad naming "mail.activity.type.equipment.manager", it does not apply on mail.activity.type but on maintenance team.

If @sle-odoo agrees to backport it, keep the external id `access_mail_activity_type_equipment_manager`, to make it easier for migration

**Comment by yelizariev** [comment]
To be closed as v11 is not supported anymore

**Pull request closed without merging**
