### PR TITLE
[9.0] Some cleanup of l10n_lu tax tags csv

### PR DESCRIPTION
**Pull request by sbidoul**
Some cleanup of l10n_lu tax tags csv, errors introduced in #19102

Misplaced newlines, mainly.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sbidoul** [comment]
@smetl @qdp-odoo could you consider this one which is prettry obvious IMHO.

**Comment by rim-odoo** [comment]
Ping @d-fence: here is one fix for the warnings on 10.0-nightly build.

```
2017-12-19 14:31:05 | WARNING | server | odoo.addons.base.ir.ir_model:1494 _update Creating the ir.model.data 17/1/b) (5) in module Etat membre non exonérées dans l'Etat membre du preneur redevable (art instead of l10n_lu.
2017-12-19 14:31:05 | WARNING | server | odoo.addons.base.ir.ir_model:1494 _update Creating the ir.model.data 17/1/b) in module Etat membre exonérées dans l'Etat membre du preneur (art instead of l10n_lu.
```

PS: @smetl :ghost: ...

**Comment by sbidoul** [comment]
Yes please, who dares clicking merge?

**Comment by rim-odoo** [comment]
@sbidoul I'm currently runboting the patch since the previous build is 45 days old, but I don't have objections :)

**Pull request merged**
