### PR TITLE
[FIX] Calendar View: overridden unlink id being passed as String

### PR DESCRIPTION
**Pull request by gbaumgartner-callino**
Description of the issue/feature this PR addresses:

https://github.com/odoo/odoo/blob/849d8ffd2193db2001626e455ed86a96bf1cddb7/addons/web_calendar/static/src/js/web_calendar.js#L934

This leads to "Database fetch misses ids ({}) and has extra ids ({}), may be caused by a type incoherence in a previous request" Error in some cases of overriden unlink() because the record is not correctly set. (e.g. model.name(u'1',) insead of model.name(1,))

A simple fix would be to explicitly cast id to int.

`{text: _t("Delete"), close: true, click: function() {
    self.remove_event(parseInt(id));
}},`

Current behavior before PR:

Overridden unlink methods might fail.

Desired behavior after PR is merged:

Unlink from calendar views working as desired.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by danger89** [comment]
Thanks, are you also willing to merge / port your changes to 11.0 branch? Otherwise we get the same problem in v11.

**Comment by gbaumgartner-callino** [comment]
Yes, i'll take another look at 11.0. It seems calendar_view is now directly integrated in web module with the code being generally updated so this might not be an issue in v11 any more.

Changed the title, thanks for pointing it out to me!

**Comment by mart-e** [comment]
Hello,

Could you explain how to reproduce your problem? How do you get a string instead of an int and the error?
I think this is not correct as, on the calendar module, the virtual ids are string on purpose, if you do a parse int, you will delete the parent event.

**Comment by gbaumgartner-callino** [comment]
Hi, sure can.

I've encountered the problem on a model that overrides it's unlink method. 

On the models calendar view, if you open the record it will open in a popup, in the default footer the "Delete" Button will trigger the "Are you sure" Dialog - on confirm it will instantly trigger said error.

image

Related Debug Log lines:
`2018-04-06 11:01:52,081 26196 INFO spg werkzeug: 127.0.0.1 - - [06/Apr/2018 11:01:52] "POST /web/dataset/call_kw/mail.message/message_format HTTP/1.1" 200 -
2018-04-06 11:01:52,159 26196 INFO spg werkzeug: 127.0.0.1 - - [06/Apr/2018 11:01:52] "POST /web/dataset/call_kw/club.training_attendee/read HTTP/1.1" 200 -
2018-04-06 11:01:55,676 26196 DEBUG spg odoo.api: call club.training(u'1378',).unlink()
2018-04-06 11:01:55,682 26196 INFO spg werkzeug: 127.0.0.1 - - [06/Apr/2018 11:01:55] "POST /web/dataset/call_kw/club.training/unlink HTTP/1.1" 200 -
2018-04-06 11:01:55,734 26196 INFO spg werkzeug: 127.0.0.1 - - [06/Apr/2018 11:01:55] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-04-06 11:02:15,458 26196 DEBUG ? odoo.service.server: cron1 polling for jobs`

**Comment by mart-e** [comment]
Thanks for the info, indeed, I have been able to reproduce it.
Your fix would break the virtual ids from the calendar module but I have fixed it another way at eb9f72ba627

**Pull request closed without merging**
