### PR TITLE
[IMP] pos_stripe: Add possibility to refund

### PR DESCRIPTION
**Pull request by qle-odoo**
Actually when we make a payment in the POS with a Stripe terminal it is impossible to reverse a payment.

So with this commit we add this possibility

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by C3POdoo** [comment]
Dear @qle-odoo,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Comment by yp-oerp** [comment]
Hi @qle-odoo 

Can we merge this into 17.0? It seems like this is a major drawback to not having refunds for POS transactions

**Comment by qle-odoo** [comment]
> Hi @qle-odoo
> 
> Can we merge this into 17.0? It seems like this is a major drawback to not having refunds for POS transactions

the integration of refund will be done but as part of a larger project.
because the code here only allows you to make a refund on the last current payment.
ultimately not very useful.
we are working on being able to refund an order even if it was made several days ago for all of our payment systems

**Comment by yp-oerp** [comment]
Hi @qle-odoo 

Thank you, I understand what you are trying to say. Can we expect this in 18?

**Pull request closed without merging**
