### PR TITLE
[FIX] delivery: apply tracking to all pickings in multistep delivery

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
- Install DHL carrier
- Enable multistep routes
- On warehouse config set 3 steps(pick,pack,ship) on outgoing shippments
- Create an SO  and add DHL shipping
- Validate the first picking and send to shipper

Bug:
only the first picking has a tracking ref
this causes an issue because this an in internal picking and only the last is shown to the customer on sales portal so the customer doesn't have acces to the tracking ref

Fix:
set the referrence on all the pickings of the so

opw-3269257

### CODE REVIEW

**Comment by Whenrow** [comment]
robodoo r+

**Comment by floflock** [comment]
@HANNICHE-Walid I think this causes other problems now. If there is only one stock.picking with one tracking, the `carrier_tracking_ref` gets written twice as it is already set in the `related_pickings`, see debugging:

Screenshot-2023-08-21 at 14 35 39


```
2023-08-21 12:34:44,742 8640 DEBUG hanfred_odoo odoo.addons.delivery.models.stock_picking: show related_pickings: 
2023-08-21 12:34:44,742 8640 DEBUG hanfred_odoo odoo.addons.delivery.models.stock_picking: stock.picking(3646,) 
2023-08-21 12:34:44,742 8640 DEBUG hanfred_odoo odoo.addons.delivery.models.stock_picking: show carrier_tracking_ref of related_pickings: 
2023-08-21 12:34:44,742 8640 DEBUG hanfred_odoo odoo.addons.delivery.models.stock_picking: 3646: 06285020453301 
2023-08-21 12:34:44,742 8640 DEBUG hanfred_odoo odoo.addons.delivery.models.stock_picking: show without_tracking: 
2023-08-21 12:34:44,742 8640 DEBUG hanfred_odoo odoo.addons.delivery.models.stock_picking: stock.picking() 
2023-08-21 12:34:44,743 8640 DEBUG hanfred_odoo odoo.addons.delivery.models.stock_picking: show carrier_tracking_ref in loop for stock.picking: 3646 
2023-08-21 12:34:44,743 8640 DEBUG hanfred_odoo odoo.addons.delivery.models.stock_picking: 06285020453301,06285020453301 
```

See database entries, first seen after `2023-08-17 14:20:24.000000`

Screenshot-2023-08-21 at 14 36 42

**Comment by floflock** [comment]
See solution commented in the diff: https://github.com/odoo/odoo/commit/9f94900f5e904661974f722dc5c56e8632bbd38b#r125061813

**Comment by HANNICHE-Walid** [comment]
@floflock thanks for catching that I've opened a PR to solve the issue

**Comment by floflock** [comment]
My please @HANNICHE-Walid, thanks for opening the PR. Looking forward to the fix. :)

**Comment by HANNICHE-Walid** [comment]
hi @floflock which are you using?

**Pull request closed without merging**
