### PR TITLE
[FIX] l10n_cn: fix the traceback

### PR DESCRIPTION
**Pull request by ppr-odoo**
Steps
        1) install l10n_cn
        2) create a company in china
        3)  create invoice and no set Fapiao Number

### CODE REVIEW

**Comment by yvaucher** [comment]
@ppr-odoo you want to rename the title of this PR, this is related to China, not the Confoederatio Helvetica ;)

**Comment by ppr-odoo** [comment]
@yvaucher  This is already fixed in this commit https://github.com/odoo/odoo/commit/915abb533ce70a312dc333bc818a23ad87828cb6
So I cancel this

**Comment by yvaucher** [comment]
@ppr-odoo can you still fix the title for further search in history?

**Comment by ppr-odoo** [comment]
@yvaucher  Thanks

**Pull request closed without merging**
