### PR TITLE
[REF] new implementation for child_of/parent_of

### PR DESCRIPTION
**Pull request by rco-odoo**
This replaces the former modified preorder tree traversal (MPTT) with the
fields `parent_left`/`parent_right`.  Each record is associated to a string
`parent_path`, that represents the path from its root node to itself.  The path
is made of the node ids suffixed with a slash:

              a                 node | id | parent_path
             / \                  a  | 42 | 42/
           ...  b                 b  | 63 | 42/63/
               / \                c  | 84 | 42/63/84/
              c   d               d  | 85 | 42/63/85/

This field provides an efficient implementation for parent_of/child_of queries:
the nodes in the subtree of record are the ones where `parent_path` starts with
the `parent_path` of record.  It is also more efficient to maintain than the
MPTT fields, and less sensitive to concurrent updates, because the value of
`parent_path` does not depend on sibling nodes.

### CODE REVIEW

**Comment by moylop260** [comment]
How you could use a preorder query here?

I mean, using `parent_left` and `parent_right` you can use a faster inner join like as:

```query
SELECT tree.id AS parent_id, sum(child.amount) AS amount_sum
FROM tree
LEFT OUTER JOIN tree as child
   ON child.parent_left
         BETWEEN tree.parent_left AND tree.parent_right
GROUP BY tree.id
```

Will be possible use the same behaviour with path field?

**Comment by gdgellatly** [comment]
@moylop260 I imagine something like (a bit clumsy here, pseudocode)

```sql
SELECT tree.id AS parent_id, sum(child.amount) AS child_amount_sum
FROM tree
LEFT OUTER JOIN tree as child
   ON (child.parent_path like '\' || tree.id || '\') OR (startswith(child.parent_path || '\')
GROUP BY tree.id
```

Big trees might need trigrams though.  I imagine small trees won't benefit or suffer much in read anyway.

@rco-odoo Funnily enough I was looking at this for another project in another SQL dialect where this format is the default key storage format and had a small look at what it would take to improve Odoo's MPTT write performance.  More out of curiosity, but any reason integer arrays were ruled out?

**Comment by rco-odoo** [comment]
@moylop260 @gdgellatly  the children node must have the parent_path of the reference node as prefix. You can thus rewrite your query as
```sql
SELECT tree.id AS parent_id, sum(child.amount) AS child_amount_sum
FROM tree
LEFT OUTER JOIN tree as child
   ON child.parent_path LIKE (tree.parent_path || '%')
GROUP BY tree.id
```
If a node has value `42/84/101/` as `parent_path`, the nodes in the corresponding subtree are the ones such that `parent_path LIKE '42/84/101/%'`.

Matching such prefixes uses the index on column `parent_path`, which gives good performance.

@gdgellatly integer arrays looked nice at first sight, but I have not found how to match *efficiently* a given prefix or check whether some value belongs to it. My inspiration actually came from the PostgreSQL extension `ltree`.

**Comment by gdgellatly** [comment]
@rco-odoo Of course you are right. so used to replacing all the other useless btree indexes on char fields in Odoo I just assumed it was bad but on reflection, it obviously is not.

**Comment by moylop260** [comment]
Ok, I got it.

`SELECT id, parent_path, parent_id, create_uid FROM product_category`

| id | parent_path | parent_id | create_uid |
----|-------------|-----------|------------
|  1 | 1/          |           |          1 |
|  2 | 1/2/        |         1 |          1 |
|  3 | 1/3/        |         1 |          1
|  4 | 1/2/4/      |         2 |          1 |
|  5 | 1/2/5/      |         2 |          1 |
|  6 | 1/2/6/      |         2 |          1 |

`SELECT product_category.id AS parent_id, sum(child.create_uid) AS child_amount_sum FROM product_category LEFT OUTER JOIN product_category as child ON child.parent_path LIKE (product_category.parent_path || '%') GROUP BY product_category.id"`

| parent_id | child_amount_sum |
|----------|------------------|
|        1 |               6 |
|         2 |                4 |
|         3 |                1 |
|         4 |                1 |
|         5 |                1 |
|         6 |                1 |


This works perfectly because you are using the suffix `/` in order to match `1` with `11` because is `1/` vs `11/`

👍  Thanks for reply!

**Comment by moylop260** [comment]
Using the following command:

```bash
grep "parent_id.*fields\.Many2one" . --include=*.py -B1000 --exclude-dir=.git --exclude=*test* | grep " \_name \= \|parent_id.*fields\.Many2one" | grep "parent_id.*fields\.Many2one" -B1 | grep " \_name = " | sort
./addons/account/models/account.py-312-    _name = "account.group"
./addons/account/models/chart_template.py-93-    _name = "account.chart.template"
./addons/account/report/account_financial_report.py-12-    _name = "account.financial.report"
./addons/fleet/models/fleet_vehicle_cost.py-11-    _name = 'fleet.vehicle.cost'
./addons/hr/models/hr.py-277-    _name = "hr.department"
./addons/hr/models/hr.py-95-    _name = "hr.employee"
./addons/hr_holidays/models/hr_leave.py-20-    _name = "hr.leave"
./addons/hr_holidays/models/hr_leave_allocation.py-16-    _name = "hr.leave.allocation"
./addons/hr_payroll/models/hr_salary_rule.py-17-    _name = 'hr.payroll.structure'
./addons/hr_payroll/models/hr_salary_rule.py-76-    _name = 'hr.salary.rule.category'
./addons/mail/models/mail_message.py-20-    _name = 'mail.message'
./addons/mail/models/mail_message_subtype.py-11-    _name = 'mail.message.subtype'
./addons/point_of_sale/models/pos_category.py-6-    _name = "pos.category"
./addons/product/models/product.py-16-    _name = "product.category"
./addons/project/models/project.py-436-    _name = "project.task"
./addons/website/models/website.py-789-    _name = "website.menu"
./addons/website_forum/models/forum.py-191-    _name = 'forum.post'
./addons/website_forum_doc/models/forum_documentation_toc.py-8-    _name = 'forum.documentation.toc'
./addons/website_sale/models/product.py-55-    _name = "product.public.category"
./odoo/addons/base/models/ir_module.py-75-    _name = "ir.module.category"
./odoo/addons/base/models/ir_ui_menu.py-19-    _name = 'ir.ui.menu'
./odoo/addons/base/models/res_company.py-12-    _name = "res.company"
./odoo/addons/base/models/res_partner.py-129-    _name = "res.partner"
./odoo/addons/base/models/res_partner.py-69-    _name = 'res.partner.category'
```

Shouldn't be added `parent_path` to these models?

FYI I have noticed that `project.task` view is so slow vs old version (8 minutes vs 3 seconds) with records using 2 levels because `_parent_store = True` was removed from 10.0 to 11.0 for this model.

**Pull request merged**
