### PR TITLE
[FIX] website_slides: Add fetch timeout

### PR DESCRIPTION
**Pull request by yajo**
This makes you actually able to install the module with demo data and unplugged from network. Otherwise, it's impossible.

This is a forward port of https://github.com/OCA/website/pull/527 and https://github.com/OCA/OCB/pull/808.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I have mixed repos...

**Comment by pedrobaeza** [comment]
@tde-banana-odoo do you think it's possible to review this old one (but still applicable)?

**Comment by tde-banana-odoo** [comment]
Totally ! Could you just update commit message to remove references to OCA forward-port ?

Thanks,

**Comment by Yajo** [comment]
Done, although it hurted... :broken_heart:

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
