### PR TITLE
10.0 ref stock quants meta domains

### PR DESCRIPTION
**Pull request by blaggacao**
### Description of the issue/feature this PR addresses:
A custom module introduces a soft restriction to a partner (similar to the soft restriction on lots, see code)

### Current behavior before PR:
The meta domain construction is deep inside a complex method and difficult to cleanly inherit without overriding the whole method.

### Desired behavior after PR is merged:
The meta_domains can be customly overridden.

--------

**Note:** The second commit is a cleanup commit for what I perceived as itchy code. If you don't agree with the overall change, please don't forget to consider every commit individually.

/cc @jco-odoo It's actually for maquila, I'll elaborate about the detailed use case on the ticket.
Maybe it's not the final PR yet, but I think it's the best way to communicate my idea...

**Task:** https://www.odoo.com/web?#id=1823395&view_type=form&model=project.task

------
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by blaggacao** [comment]
Please regard every commit as a somewhat separate proposal. They are here for the sake of the single target "use case" and to fit the user story...

**Comment by jco-odoo** [comment]
I am not too fond of this.  It is not meant to add methods everywhere.  You can always inherit the method above.  Not sure for the owner.

**Comment by blaggacao** [comment]
Ok @jco-odoo I understand i might be too much of a change and the full extend of the use case can be only understood (with brain _and_ heart) if you are literally standing in the middle of a running factory... :wink:

>It is not meant to add methods everywhere.

I was wondering for a while now, why you guys are not too keen on providing hooks (I observed that in general). I was thinking, observing my own development, that it's probably because it's two fundamentally different perspectives to approach the code from a monkey patching perspective (as module developer) or from upstream with grater leverage on the code base (close to full control).

From a downstream perspective you forgo code updates or even have to deal with undetected regressions when you override more than the absolutely necesary.

Is there anything more abstractable to that bias, like increased maintenance cost or stability concerns? Or is it just a (unconscious) bias? - I'm just trying to understand to adapt my strategy... :wink:

**Comment by blaggacao** [comment]
Ok @jco-odoo I understand i might be too much of a change and the full extend of the use case can be only understood (with brain _and_ heart) if you are literally standing in the middle of a running factory... :wink:

>It is not meant to add methods everywhere.

I was wondering for a while now, why you guys are not too keen on providing hooks (I observed that in general). I was thinking, observing my own development, that it's probably because it's two fundamentally different perspectives to approach the code from a monkey patching perspective (as module developer) or from upstream with grater leverage on the code base (close to full control).

Is there anything more abstractable to that bias, like increased maintenance cost or stability concerns? Or is it just a (unconscious) bias? - I'm just trying to understand to adapt my strategy... :wink:

**Comment by blaggacao** [comment]
With the changes of this commit, I then do:
```python
    def _quants_get_meta_domain(self, move, restrict_lot_id=False, preferred_domain_list=False):
        ''' Overridable method providing meta search domains for the quant search iterations.
            Use `move` object to pass your values.
        '''
        if restrict_lot_id and move.soft_restrict_partner_id:
            meta_domains = [
                [('lot_id', '=', restrict_lot_id), ('owner_id', '=', move.soft_restrict_partner_id.id)],
                [('lot_id', '=', restrict_lot_id), ('owner_id', '=', False)],
                [('lot_id', '=', False), ('owner_id', '=', move.soft_restrict_partner_id.id)],
                [('lot_id', '=', False), ('owner_id', '=', False)]
            ]
        elif restrict_lot_id:
            meta_domains = [[('lot_id', '=', restrict_lot_id)], [('lot_id', '=', False)]]
        elif move.soft_restrict_partner_id:
            meta_domains = [[('owner_id', '=', move.soft_restrict_partner_id.id)], [('owner_id', '=', False)]]
        else:
            meta_domains = [[]]
        return meta_domains
```

For what concerns my use case that works pretty well so far... But I have to analyse possible external effect sin more detail...

**Comment by blaggacao** [comment]
I had caused a little regression around the implicit implicitness of the nested list :fearful: Just fixed it.

> It is not meant to add methods everywhere.

I think in this case it's (strategically) warranted to ease extension:

A domain is constructed well down into the method, while stearing a conceptually well abstractable behaviour.

It seems to me this is the only (and correct!) point to implement a _take this, and if no stock take other_ semantics... (at least lot-wise it's implemented here)

Whats wrong about consuming foreign stock and complement it with own stock, if not enough foreign?
I mean in reality, it does happen and is not even far fetched...

Could you reconsider accepting this? Or probably only parts of it?

**Comment by jco-odoo** [comment]
I prefer to leave this the way it is.  I find it too risky to still change this.

**Comment by blaggacao** [comment]
@jco-odoo Ok, I'll reconsider for master...

**Pull request closed without merging**
