### PR TITLE
[FIX] payment_adyen: set holder name required

### PR DESCRIPTION
**Pull request by vchu-odoo**
As VISA added more mandatory fields to perform payments, the holder's name is required now for the customer to fill when paying with adyen.

opw-4085163

### CODE REVIEW

**Comment by vchu-odoo** [comment]
will be fixed in 17.0 as onError is not working well on Adyen's side for the used dropin version.

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+ fw=no

**Comment by AntoineVDV** [comment]
@vchu-odoo rebase needed
@robodoo delegate+

**Comment by vchu-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
