### PR TITLE
[IMP] base, web_editor, website_event: backport #75205

### PR DESCRIPTION
**Pull request by rdeodoo**
Backport https://github.com/odoo/odoo/pull/75205 from 15.1 to 15.0 (saas-14.5)

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo delegate+

**Comment by JKE-be** [comment]
@fw-bot ignore

**Comment by rdeodoo** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
