### PR TITLE
[FIX] web: update jQuery to 3.6.3

### PR DESCRIPTION
**Pull request by sdegueldre**
This version of jQuery fixes a number of bugs in jQuery compared to
3.3.1

task-2291793

### CODE REVIEW

**Comment by sdegueldre** [comment]
@odoo/rd-security update of the jQuery lib. I've given the diff a quick once-over, haven't seen anything egregious. The assignments to innerHTML that are in the diff use fixed HTML content, one of them is just a move from the previous version.

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: innerhtml on static values inside jquery

**Comment by sdegueldre** [comment]
On hold as we may want to merge this in earlier versions: https://github.com/odoo/odoo/pull/107087

**Comment by sdegueldre** [comment]
@odony  The enterprise build I made was red because of some qunit tests and I've been very busy. Apparently it's an undeterministic error and the runbot is now marking it as "fixed" so it might have been unrelated, it was not initially marked as such so I might've mistakenly believed it was caused byt the jQuery update. I've rebuilt that particular build, if it's green, I'm ok with merging this (or 3.6.3 while we're at it) but I'm on holiday next week. If you have some time and want this to be merged before january feel free to push on this branch and merge it as you see fit, if not I'll pick this up Jan 2nd

**Comment by sdegueldre** [comment]
@odoo/rd-security in the end we decided to target master because it appears some tests are broken by this upgrade. As documented in the commit messages, these tests have been skipped because the code it tests is almost dead and will be removed before version 17, and the behaviour is actually correct in practice, but I'd rather not risk any problems in a stable version considering customizations could rely on this behaviour and I may have missed something.

**Review by aab-odoo — APPROVED** [review]

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
