### PR TITLE
[IMP] l10n_cn: improve translation

### PR DESCRIPTION
**Pull request by hpl-odoo**
Task : https://www.odoo.com/web#id=2181737&action=327&model=project.task&view_type=form&menu_id=4720

### CODE REVIEW

**Comment by jco-odoo** [comment]
@hpl-odoo This looks ok and I want to merge it.  But how is this handled in v13 and the saas-13.1/2? @rgo-odoo

**Comment by rgo-odoo** [comment]
@jco-odoo this issue no longer reproducible thanks to #44508

**Comment by jco-odoo** [comment]
@rgo-odoo Are you sure because I see it adds pos receivable account too?

**Comment by rgo-odoo** [comment]
> @rgo-odoo Are you sure because I see it adds pos receivable account too?

@jco-odoo yes, so does the mentioned PR, https://github.com/odoo/odoo/pull/44508/files#diff-1adfe9c7391fbb65e66e37b2740eb32eR7 Also, I checked with latest master and Chinese localization can successfully be installed when point of sale was already installed.

**Pull request closed without merging**
