### PR TITLE
[FIX] Return the result of super in the method put_in_pack (module de…

### PR DESCRIPTION
**Pull request by leemannd**
Original author is @sylvainvh on https://github.com/OCA/OCB/pull/665

Description of the issue/feature this PR addresses:
Return the result of super in the method put_in_pack (module delivery). Otherwise the method can return False even if the package was created

Current behavior before PR:
The inherited method "def put_in_pack" (stock.picking) in the module delivery call super to retrieve the created package. However if this doesn't find a carrier, it will return False.

Desired behavior after PR is merged:
This method should return the result of super

@tivisse @mart-e Issue opened number: 1912671

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sylvainvh** [comment]
@leemannd , I signed the CLA but the PR is not yet merged (https://github.com/odoo/odoo/pull/28415)

**Comment by leemannd** [comment]
@sylvainvh Yeah cool!

**Comment by sylvainvh** [comment]
Hi @leemannd , you can rebase your branch to reload the CLA check. I signed the CLA

**Comment by leemannd** [comment]
Rebased.
Hello @mart-e , sorry for the inconvenience, but @sylvainvh signed the cla. In the following PR https://github.com/odoo/odoo/pull/28415
The main goal was to have it also for the 10.0 . Is it possible to update the branches and cla check?

**Comment by sylvainvh** [comment]
Hello @leemannd (and @mart-e ), you can rebase your branch on master. I signed (and it is merged) for v10 and v12

**Pull request closed without merging**
