### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by LucasLefevre**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/e1ad985ea [REL] 18.1.0-alpha.4 Task: 0
https://github.com/odoo/o-spreadsheet/commit/92928ad5a [IMP] export: flattent cell object Task: 4295344
https://github.com/odoo/o-spreadsheet/commit/782ca4336 [REF] export: remove ExcelCellData Task: 4295344
https://github.com/odoo/o-spreadsheet/commit/19b2faa92 [REF] export: remove useless property Task: 4295344
https://github.com/odoo/o-spreadsheet/commit/c02873b21 [REF] xlsx: remove some custom values in ExcelCellData Task: 4295344
https://github.com/odoo/o-spreadsheet/commit/65ec7d471 [REF] import: helper to denormalized data Task: 4295344
https://github.com/odoo/o-spreadsheet/commit/a3dfe6d29 [FIX] chart: date line chart Task: 4268977
https://github.com/odoo/o-spreadsheet/commit/3b8935c04 [IMP] charts: allow chart insertion with unbounded zone Task: 3502197
https://github.com/odoo/o-spreadsheet/commit/4c80b4776 [IMP] icons : use fa-clipboard icon for copy-to-clipboard buttons Task: 3181092
https://github.com/odoo/o-spreadsheet/commit/589eee060 [IMP] charts: enable "Show Values" on radar chart Task: 4282824
https://github.com/odoo/o-spreadsheet/commit/7225e7ead [FIX] color_picker: conditionally hide reset button Task: 4102704
https://github.com/odoo/o-spreadsheet/commit/0b1ba7f68 [REF] charts: simplify runtime generation Task: 4286137
https://github.com/odoo/o-spreadsheet/commit/7bda5f911 [REM] charts: remove useless, wrong and misleading test Task: 4286137
https://github.com/odoo/o-spreadsheet/commit/f15003351 [FIX] chart: trend line of area chart Task: 4274294

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by LucasLefevre** [comment]
robodoo fw=no

**Comment by LucasLefevre** [comment]
robodoo rebase-merge

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
