### PR TITLE
[REL] 16.0

### PR DESCRIPTION
**Pull request by d-fence**

### CODE REVIEW

**Comment by Bonainifo** [comment]
Is it means the Odoo16 version is published?

**Comment by xmo-odoo** [comment]
> Is it means the Odoo16 version is published?

No.

**Comment by ray-odoo** [comment]
When someone triumphantly does this:

CLOSE

And scrolls to the top of the page to show the people watching that it looks like this:

CLOSED

Then crowds of people will cry tears of joy as their baby gets to go off into the big world and meet the fans!

**Comment by vvanneri-ia** [comment]
### **Inevitable 16**
thanos-snap

**Comment by ray-odoo** [comment]
https://static1.srcdn.com/wordpress/wp-content/uploads/2022/01/Marvel-Universe.png?q=50&fit=contain&w=1500&h=&dpr=1.5

**Pull request closed without merging**
