### PR TITLE
[IMP] account: super bob

### PR DESCRIPTION
**Pull request by Levizar**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Levizar** [comment]
@robodoo help

**Comment by Levizar** [comment]
@robodoo help

**Comment by tfr-odoo** [comment]
@robodoo help

**Comment by h4818** [comment]
@robodoo help

**Comment by FlorianGilbert** [comment]
@robodoo help

**Pull request closed without merging**
