### PR TITLE
[FIX] fields, web: improve form onchange to x2many

### LINKED ISSUE #11236: [9.0] api.onchange modification One2many field with NewItem does not works
Impacted versions: **v9.x**

Steps to reproduce: 

define models that have One2many and Many2one raltion:

```
class ClassA(models.Model):
    _name = 'module.class_a'
    CYCLE = 'cycle'
    AMOUNT = 'amount'

    Other = (
        (CYCLE, 'Cycle'),
        (AMOUNT, 'Amount')
    )
    name = fields.Char(string='Name', required=True)
    other_influence = fields.Selection(Other, string='Other influence', required=True)
    related = fields.One2many('module.class_b', 'components')

    @api.onchange('other_influence')
    def _other_influence_change(self):
        self.related = None
        if self.other_influence == self.CYCLE:
            b = {
                'name': 'XXX', # Lets say we do generate something here, hardcoded just to show the problem. 
            }
            self.related += self.related.new(b)

class ClassB(models.Model):
    _name = 'module.class_b'

    name = fields.Char(string='Name', required=True)
    components = fields.Many2one('module.class_a', ondelete='no action')
```

Current behavior:

When clicked at _Other influence_ field in view, function __other_influence_change_ is triggered as it should, related field is cleared but when executing `self.related += self.related.new(b)` new row is added in view, but it is empty, eg. **Name field is blank**. And save ends with error:

```
openerp.sql_db: bad query:  SELECT "module_class_b"."components" as "components","module_class_b"."id" as "id" FROM "module_class_b"
                        WHERE "module_class_b".id IN ('one2many_v_id_53')  ORDER BY "module_class_b"."id"
```

However, if I change new to create in line `self.related += self.related.create(b)` and click at _Other influence_ field view works fine and new row is added, eg. **Name field contains XXX**. Save works as well, but **this is obviously bad setup** as each click on _Other influence_ would create and entry in DB (but works, both updated view and also store, but create shouldnt be used here).

Expected behavior:

When clicked at _Other influence_ field in view  function __other_influence_change_ is triggered with  `self.related += self.related.new(b)` and new row is added in view, and it shows data from variable b, eg. **Name field contains XXX**. And save to the DB successfully once user pres the save button.

Video/Screenshot link (optional):

### LINKED ISSUE #15129: Field One2many child propagation on NewId dict
Related to commit:bbdf9605e4c480e1fc19b1faac9cfc4321bcaea2

If non-default form view is used, and that view contain fields which do not exist in default form view, odoo will raise error

### PR DESCRIPTION
**Pull request by nle-odoo**
In a form view, when a field onchange lead to a change on a x2many,
there was two different behavior:

- if the x2many had an embedded view (eg. a tree view inside a form
  view) the onchange would notify that it expected the x2many field in
  this embedded view to be changed and handled the changes correctly.

- if the x2many had a default view, the onchange ORM would not be
  aware the x2many could be modified and would not sent the changes
  back causing blank or not updated x2m lines and error on save.

---

Two solutions were birthed to solve the second point:

=> PR #10557 = solving everything

With this PR the onchange in the ORM is aware of every fields in the
current view (even field in a x2m in a x2m in a x2m in a form view) and
if any of these are change the javascript gets back the value of the
fields present in the view.

This PR has currently not been merged by fear of changing too much and
anyway could only be done in master.

=> PR #12249 = if no field for x2many, send its form view fields

With this change, if the ORM onchange is not aware of the fields in the
x2many widget to returns, all the field in the x2m default form view are
returned.

This was merged in bbdf9605 but introduced a number of other issue:

- in most situation the x2many is represented by a list view, which may
  have fields missing of the form view,  so the original is still present.

- the view used may differ from the default form view in other way
  (depending on value in context or other possibilities).

- the form view could have fields not present in the form view which
  could end up in `write` on fields which should not be written to.

---

This commit reverts bbdf9605 and adapts a small part of #10557 so the
x2many with default view works as an embedded x2many. For more than one
level (eg. a x2many in a x2many) this would still not work but it is
only solvable by a PR such as #10557 which could only be targetted for
master.

fixes #11236, fixes #12249, fixes #15129
opw-705965

__pr note:__

I still need to test with more scenarios (kanban x2m, ...) and make additions to existing tests.

a one2many_list in one2many_list before this had blank values or was not updated which caused an error at `write`. after this everything seems ok while editing it, but once we save it the existing line update can be skipped (or in some scenario the field is invalid preventing to save). 

this is an improvement but I need to check if this could be improved further.

@auyeung112002 I need to check what I could do for test and x2m in x2m but this is the current fix which hopefully should be good to solve #15129.

### CODE REVIEW

**Comment by auyeung112002** [comment]
@nle-odoo I have tested with my database and confirm the following things:
1. x2many in x2many doesn't work as you stated. PR 10557 should be the best way out.
Since the PR is quite outdated, would you please modify the PR to match the current code so I can test further and provide feedback.

2. one2many in form view doesn't work. I have a many2one onchange that populate a one2many list. That many2one is readonly and set by context={'many2one_id': xxx} in button action. The one2many come up empty.

**Comment by nle-odoo** [comment]
@auyeung112002 I don't think PR #10557 could be done before master.

as for:

1. it does not work for every situations now, but works a little more often than before.
2. I don't understand, if you have a button action what happen is "=> the record is updated in backend" => "the form view is reloaded", so to my knowledge there is not any onchange which is expected to be be triggered :thinking:

**Comment by auyeung112002** [comment]
@nle-odoo For the second point, the case is
1. I have a button which returns a window action to the web client.
2. The window action will open a form and a many2one field is set by context default.
3. And that many2one field has onchange method and setting default many2one value will trigger it.
4. In the onchange method, one2many field is populated(have correct number of rows but all field empty)

**Comment by nle-odoo** [comment]
If the windows action was displaying a new record, it should be solved from the last change of this PR 3 hours ago (in 3de0662d5).

As a warning this PR has not already been reviewed by other developers (so there could still be changes before it is merged).

**Comment by auyeung112002** [comment]
[demo_onchange.zip](https://github.com/odoo/odoo/files/760254/demo_onchange.zip)

This module shows the problem I mentioned.
With this commit(https://github.com/odoo/odoo/commit/3de0662d5631869c386222f14783926ae4914408), install the above module.

1. Login as admin
2. Set admin as Sales Manager in order to show the Sales Menu.
3. F5
4. Create a Customer.
5. In the customer form view, click the button "Display Form View" at the bottom.
6. There should be 3 records populated.

Expected Behavior:
Those populated rows have "detail" field filled.

Current Behavior:
Those populated rows have empty "detail" field.

**Comment by nle-odoo** [comment]
I have updated the PR and it should work now.

I only tested that case in 10.0 and there was a difference with 9.0, in the current PR I have corrected the difference and it should work for 9.0 community.

For 9.0 enterprise this patch should be applied (on linux with patch and curl) at the base of enterprise:

```sh
patch -p1 < <(curl "https://gist.githubusercontent.com/nle-odoo/c86ba837a867c476420b0e4cb08abbbf/raw/ae4883b146abf801a6734cf40ae76fa66c78bc1f/o2m_default_views.patch")
```

**Comment by auyeung112002** [comment]
@nle-odoo Confirmed in version 9 it solved the problem shown in the above module.

And in my testing, it can correctly handle populating one2many list in a one2many form(many2one onchange triggered at this level) in one2many form.

**Comment by Yajo** [comment]
Runbot seems broken.

**Comment by auyeung112002** [comment]
@nle-odoo In version 9, if the one2many field has two embedded views, it will crash.

Step to reproduce:
Install this module.(Same file name as previous, but with different content)
[demo_onchange.zip](https://github.com/odoo/odoo/files/823773/demo_onchange.zip)
Login as admin
Set admin as Sales Manager in order to show the Sales Menu.
F5
Create a Customer.
In the customer form view, click the button "Display Form View" at the bottom.

**Comment by nle-odoo** [comment]
@auyeung112002  you are right, I have updated it. I will try to finish tests as soon as possible since there has been several other report of the issue.

**Pull request closed without merging**
