### PR TITLE
[FIX] sale_projet : wrong trigger

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
Update Trigger for perf issue

@nim-odoo

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
cc @IT-Ideas

**Comment by fmdl** [comment]
ping @mart-e

**Comment by mart-e** [comment]
@fmdl thanks for the PR but could you provide more details? You mention a perf issue, is that something you have encountered/measured? The fields are not stored. `service_tracking` is used in the `_compute_visible_project` computation so why do you remove it?

**Comment by tde-banana-odoo** [comment]
Forwarding to service team @tivisse @IT-Ideas

**Pull request closed without merging**
