### PR TITLE
[IMP] spreadsheet: include first row grouping at insertion

### PR DESCRIPTION
**Pull request by pro-odoo**
With this revision, the label of the field of the first row groupby is inserted as the row title.

Task-id 2901960

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rrahir** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
failing stagings seems to be caused by this PR:
https://runbot.odoo.com/runbot/build/24208195

Could you take a look ? :pray:

**Comment by LucasLefevre** [comment]
robodoo r- to remove it from the next split

**Comment by rrahir** [comment]
@robodoo r+

**Pull request closed without merging**
