### PR TITLE
[REM] website_theme_install: remove dead code

### PR DESCRIPTION
**Pull request by rdeodoo**
This code is not useful anymore.

### CODE REVIEW

**Comment by rdeodoo** [comment]
Extracted from https://github.com/odoo/odoo/pull/37142, no point to merge it in 12.0 if no bug, definitely master

**Comment by qsm-odoo** [comment]
12.5 :3 ?

**Comment by rdeodoo** [comment]
You are the one that will r+ and the commit is at your name so anything you want ;-)
But 12.5 is stable, and this is not a bug?

**Comment by rdeodoo** [comment]
:+1: not false

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@d-fence Do you know about that runbot issue?

**Comment by d-fence** [comment]
Commit was not found in git. I'm searching why

**Comment by xmo-odoo** [comment]
@robodoo retry

@qsm-odoo d-fence is looking into it but it looks like a corruption of some sort on runbot17

**Comment by d-fence** [comment]
@xmo-odoo @qsm-odoo I confirm a local repo corruption on runbot17.
runbot17 is now blacklisted and the repo is fs-checked

**Pull request closed without merging**
