### PR TITLE
[FIX] base: recompute view.model_data_id

### PR DESCRIPTION
**Pull request by rco-odoo**
Fix the (re)computation of the field `view.model_data_id`.

### CODE REVIEW

**Comment by rco-odoo** [comment]
@odony what do you think about this one?
The subtle dependency on a dummy field triggers the recomputation of the field on views when their xml_id record is created/modified.

**Comment by odony** [comment]
It's not pretty :worried: 
Is this the official recommended way of implementing a "store=True" field in the new API, i.e. one that depends on all the other fields?  Couldn't we simply use `@depends('write_date')` or something, a less visible/invasive hack, to achieve the same result?

**Comment by rco-odoo** [comment]
@odony `@depends('write_date')` does not fix the issue, unless you explicitly write on each view after you created its xmlid record. It accidentally fixes the 'noupdate' stuff, because you write on the view before flagging its xmlid record as 'noupdate'.

The field `model_data_id` is also used in `ir.ui.view`'s search view (search by xml id). And in this case, the search will not work as expected, until you force the recomputation of the field.

**Comment by rco-odoo** [comment]
@odony see #13871 for an alternative fix.

**Comment by rco-odoo** [comment]
@odony see #13885 for yet another way to fix the issue.

**Comment by rco-odoo** [comment]
Discarded in favor of #13885.

**Pull request closed without merging**
