### PR TITLE
[FIX] ir_model_fields: fix oversight of 5f5bb5e

### LINKED ISSUE #31447: [BUG][11.0] base: error with custom field
Impacted versions: 11.0

Steps to reproduce:
-create a custom selection field related and stored
-upgrade odoo with https://github.com/odoo/odoo/commit/5f5bb5e26b0cf49dc48d00eeac80fa25bca315c5
-starting raise

the issue come from that the field selection on ir.model.fields is set to `False`.

cc @Elkasitu

```
2019-02-27 00:21:10,971 60940 ERROR iguana_master werkzeug: Error on request:
Traceback (most recent call last):
  File "/Users/florentdelabarre/.virtualenvs/iguana/lib/python3.6/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/Users/florentdelabarre/.virtualenvs/iguana/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/service/server.py", line 260, in app
    return self.app(e, s)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/http.py", line 1319, in __call__
    return self.dispatch(environ, start_response)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/Users/florentdelabarre/.virtualenvs/iguana/lib/python3.6/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/http.py", line 1474, in dispatch
    odoo.registry(db).check_signaling()
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/modules/loading.py", line 383, in load_modules
    registry.setup_models(cr)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/modules/registry.py", line 274, in setup_models
    model._setup_base()
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/models.py", line 2401, in _setup_base
    self.env['ir.model.fields']._add_manual_fields(self)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/addons/base/ir/ir_model.py", line 901, in _add_manual_fields
    field = self._instanciate(field_data)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/addons/base/ir/ir_model.py", line 892, in _instanciate
    attrs = self._instanciate_attrs(field_data)
  File "/Users/florentdelabarre/git/iguana-yachts/server/addons/mail/models/ir_model.py", line 70, in _instanciate_attrs
    attrs = super(IrModelField, self)._instanciate_attrs(field_data)
  File "/Users/florentdelabarre/git/iguana-yachts/server/addons/base_sparse_field/models/models.py", line 46, in _instanciate_attrs
    attrs = super(IrModelFields, self)._instanciate_attrs(field_data)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/addons/base/ir/ir_model.py", line 857, in _instanciate_attrs
    attrs['selection'] = safe_eval(field_data['selection'])
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/tools/safe_eval.py", line 348, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/tools/safe_eval.py", line 212, in test_expr
    pycompat.reraise(ValueError, ValueError('"%s" while compiling\n%r' % (ustr(e), expr)), exc_info[2])
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/Users/florentdelabarre/git/iguana-yachts/server/odoo/tools/safe_eval.py", line 206, in test_expr
    expr = expr.strip()
ValueError: "'NoneType' object has no attribute 'strip'" while compiling
None
```

### PR DESCRIPTION
**Pull request by Elkasitu**
safe_eval'ing None is bad, so don't do it

closes #31447

### CODE REVIEW

**Comment by Elkasitu** [comment]
Can you show me how you're creating this field with XML?

**Comment by luisg123v** [comment]
@Elkasitu sure. It may be replicated adding a record as follows:

```
<record id="field_selection_test" model="ir.model.fields">
    <field name="name">x_test</field>
    <field name="field_description">Selection Test</field>
    <field name="ttype">selection</field>
    <field name="model_id" ref="account.model_account_invoice"/>
    <field name="selection">[('option', 'Option')]</field>
</record>
```

**Comment by Elkasitu** [comment]
```XML
<field name="selection" eval="[('option', 'Option')]"/>
```
is the correct way to do it, I will let @rco-odoo decide if we keep this behavior or not

**Comment by fmdl** [comment]
the issue come from that you code erase the value., when it is a custom field.

can you reverse the comit before, then when you are a good solution, comit the final solution.

**Comment by luisg123v** [comment]
@Elkasitu   
I also tested that approach  using eval, but neither works:

```
  File "/home/odoo/odoo-11.0/odoo/addons/base/ir/ir_model.py", line 369, in _check_selection
    raise UserError(_("The Selection Options expression is not a valid Pythonic expression. "
odoo.tools.convert.ParseError: "The Selection Options expression is not a valid Pythonic expression. Please provide an expression in the [('key','Label'), ...] format.
```

When using eval, the result is not a string but a list, so when `safe_eval([...])` is evaluated, it fails.

**Comment by Elkasitu** [comment]
I'll revert this as it's more complex than originally thought, furthermore it was not really a fix as it had never been implemented before, so it will have to be implemented in master instead.

**Comment by odony** [comment]
@robodoo r+ please revert this quickly

**Comment by odony** [comment]
Manually merged at 686e6e10

**Pull request closed without merging**
