### PR TITLE
[FIX] account: fix date when converting amount for reconciliation

### PR DESCRIPTION
**Pull request by agr-odoo**
- Have the main currency in $
- Create a receivable account in €
- Invoice an amount when the exchange rate is x
- Payment of the invoice through a bank statement in $ when the exchange
rate is y
- Reconcile payment and Invoice on another day when the exchange rate is
z (and z > y)

The original invoice amount (in €) is converted in $ with the rate x
(ok)

When reconciling, the payment (in $) is compared to that original
converted amount  and the difference is put on a loss/gain exchange
journal (ok)

When moving that reconciliation to the invoice, the amount of the
payment reconciled to the invoice is converted to € using the exchange
rate z (NOT ok). The rate used should be that of the payment day

opw-2156054

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
> That seems to make sense. Did you find where `context['date']` is set?

https://github.com/odoo/odoo/blob/a7c290d718a965d050d420ccd4dfddfe6e9c17ff/addons/account/models/account_move.py#L1330-L1332

To be more future proof maybe vals['date_maturity'] could be better

**Comment by nim-odoo** [comment]
In 12.0, we do:

https://github.com/odoo/odoo/blob/2298097eb866b786c8e902402bf72bb0521f34c1/addons/account/models/account_move.py#L1224-L1225

Would that work in your use case?

**Comment by agr-odoo** [comment]
> Would that work in your use case?

Yes, even if vals['date'] is unset vals['date_maturity'] should be at least be the move date so it should be fine

**Comment by agr-odoo** [comment]
@fw-bot ignore

**Pull request closed without merging**
