### PR TITLE
[IMP] uom : add area

### PR DESCRIPTION
**Pull request by fmdl**
We have leng (m), volume (m^3), but not area (m²).

@nim-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Thanks for the PR but this should target master, not the stable.
By the way, check the runbot logs, your code fails.

@lap-odoo ok for you?

**Comment by lap-odoo** [comment]
@mart-e That's not really important to me. They can be created manually when needed, right? 
Also, it's maybe weird to create an empty category, if you create the category, uom are needed too. And if you do it for m², it should be done for ft² too. 

Honestly, I don't think it's needed.

**Comment by fmdl** [comment]
In my PR I have forgot to add area here, if not you cannot create a new category :

```python
class UoMCategory(models.Model):
    _name = 'uom.category'
    _description = 'Product UoM Categories'

    name = fields.Char('Unit of Measure Category', required=True, translate=True)
    measure_type = fields.Selection([
        ('unit', 'Units'),
        ('weight', 'Weight'),
        ('time', 'Time'),
        ('length', 'Length'),
        ('area', 'Area'),
        ('volume', 'Volume'),
    ], string="Type of Measure")

    _sql_constraints = [
        ('uom_category_unique_type', 'UNIQUE(measure_type)', 'You can have only one category per measurement type.'),
    ]
```

**Comment by fmdl** [comment]
in master measure type is removed, it is possible to any category

**Pull request closed without merging**
