### PR TITLE
l10n_be translations

### PR DESCRIPTION
**Pull request by nim-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo rebase-ff

**Comment by nim-odoo** [comment]
fw-bot ignore

**Comment by nim-odoo** [comment]
@mart-e I'm a bit confused here. This is a backport of #44022, but an extra commit is necessary (`translate=True`, which is not necessary in 13.0). Do you have any idea what could be the cause? Thanks

**Comment by mart-e** [comment]
@nim-odoo in 13.0 the field is translatable in l10n_multilang

https://github.com/odoo/odoo/blob/3086b2d249f99da7937765ac65631cdeea11c71b/addons/l10n_multilang/models/account.py#L77

cf 9b49f0007896549e0dc71de7bd2de5d29ec08dc1

**Comment by nim-odoo** [comment]
@mart-e Thanks, I missed that!

robodoo r+

**Pull request closed without merging**
