### PR TITLE
[FIX] project,sale_timesheet: fix for v15

### PR DESCRIPTION
**Pull request by xavierbol**
task-2638359

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by IT-Ideas** [comment]
Too bad that we had to retarget to sass but the PR numbers are no more correct in the commits.

**Review by IT-Ideas — APPROVED** [review]
LGTM Thanks 🙂 
Just the commit message change since we retargeted to sass-14.5.

**Comment by xavierbol** [comment]
Done @IT-Ideas 🙂

**Comment by IT-Ideas** [comment]
@robodoo r+

**Comment by IT-Ideas** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
