### PR TITLE
Ignore canceled purchase lines

### PR DESCRIPTION
**Pull request by guewen**
**Ignore canceled purchase lines**

Please read the description of https://github.com/odoo/odoo/pull/6036
This is the same correction but for purchase orders.

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,


I give my full support to this patch as for SO (https://github.com/odoo/odoo/pull/6036).

Thanks in advance for supporting this PR !

Regards,

Joël

**Comment by jgrandguillaume** [comment]
@lepistone See to modify this PR according to the same remark we received here :https://github.com/odoo/odoo/pull/6036#issuecomment-94873446 => The canceled lines should be taken into account in amount_total as requested by Odoo team. Thanks.

**Comment by lepistone** [comment]
Rebased. There was a commit with a commit merged yesterday.

**Comment by jgrandguillaume** [comment]
@odony @jco-odoo First thanks a lot for accepting our work on the sale side. Anything we can do to have this one merged as well so we have something consistent between sale and purchase on this topic ?

**Comment by jco-odoo** [comment]
We would like to merge this, but could you leave out the changes of crossdock?  We saw the test was not correct and are fixing it in another branch.  (#6206)

**Comment by gurneyalex** [comment]
@nim-odoo @jco-odoo the extracte test, with a green build is on https://github.com/odoo/odoo/pull/6080 

Would you like me to remove 40d66d0 from #6038? The net result would be a red build until #6080 is merged.

**Comment by lepistone** [comment]
@jco-odoo I got rid of the commit for the crossdocking test. Thanks a lot!

**Comment by jco-odoo** [comment]
Merged with c315377 and 96b5312

**Comment by gurneyalex** [comment]
@jco-odoo many thanks! :bow:

**Comment by lepistone** [comment]
thanks!

**Pull request closed without merging**
