### PR TITLE
[IMP] doc: SEO stuff

### PR DESCRIPTION
**Pull request by mart-e**
Linked to odoo/documentation-user#487

### CODE REVIEW

**Comment by mart-e** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by mart-e** [comment]
robodoo retry

**Comment by mart-e** [comment]
robodoo retry !

**Comment by xmo-odoo** [comment]
@mart-e maybe wait for #41647 to be merged if that still doesn't work?

**Comment by mart-e** [comment]
It's friday, I have hope !
robodoo retry

**Comment by xmo-odoo** [comment]
:rofl:

**Comment by mart-e** [comment]
@robodoo retry ! help my SEO !

**Comment by mart-e** [comment]
robodoo retry

**Comment by mart-e** [comment]
robodoo retry

**Comment by nim-odoo** [comment]
robodoo retry 
?

**Comment by mart-e** [comment]
robodoo retry

**Pull request closed without merging**
