### PR TITLE
[IMP] Austrian States (ISO 3166-2:AT)

### PR DESCRIPTION
**Pull request by wtaferner**
Description of the issue/feature this PR addresses:

Current behavior before PR:
No Austrian States
Desired behavior after PR is merged:
Austrian States

@mart-e 
May I ask you to merge this for me?
I think we should harmonize the codes within this file too as some country codes are original ISO 3166-2 and others use the abstraction without the country prefix which makes sense in this context. If you agree, I am happy to do this and add even more country states based on ISO 3166-2.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Thanks for the PR but are the state in Austria required in the address?
We do not want to add all the state of all the countries (that would make a lot of states and a lot of updates). We add only the states where it is required in the country (e.g. United States requires that but we did not add the states from Belgium).

About renaming, we try to avoid if not necessary. Changing external ids can break quite a lot of customisation or community modules, not sure @KangOl would approve the migration :wink:

**Comment by wtaferner** [comment]
Well, I doubt it is required as we have zip codes but it certainly helps as zip codes are just numbers and not everyone knows the numbers and they are not straight forward in Austria related to the states (and they have official state status due to the norm. And it is very useful to have it out of the box.

I am talking about the codes char fields (i.e.: JP-23) not the external_ids and I think most of the states are new in master...please use the ISO 3166-2 norm to see what I mean.

Thank you for explaining why you add states in core..it is your decision if you think if Austria is worth it...I think it is.

**Comment by mart-e** [comment]
Oh sorry, yes the code can be changed to meet a standard, no problem for that.

For Austria, when I am checking [this page](http://www.postadressglobal.com/country/austria/formatting_and_structure_of_austrian_addresses/) it seems that the state never appears in the address so I am not in favour to add it on standard.
If you really need it, maybe add it in l10n_at.

**Comment by wtaferner** [comment]
Ok, then I will propose this fix that it is consistent...

Well, I do not really need it as it is already in my extra [modules](https://github.com/wt-io-it/odoo-addons/tree/9.0/l10n_at_state). You are right it is not needed in the address, so if this is the ultimative criterion, no need at all.

**Pull request closed without merging**
