### PR TITLE
[IMP] mail: create 'RtcSession/isCurrentUserInitiatorOfConnectionOffer

### PR DESCRIPTION
**Pull request by alexkuhn**
This is exactly the field 'RtcSession/isConnected', but it was badly named.

Task-2734101

### CODE REVIEW

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
👆rebase (resolve conflict)

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
