### PR TITLE
Signed CLA

### PR DESCRIPTION
**Pull request by horlich**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `h...@mec.at`
- you are signing _for_ the address `h...@orlich.at`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by mart-e** [comment]
Do you have something you actually want to change? Because here you just modified the readme file in your PR

**Comment by horlich** [comment]
No, I don't want to change anything. That was a mistake.Herbert OrlichAm 28.07.2023 11:47 schrieb Martin Trigaux ***@***.***>:
Do you have something you actually want to change? Because here you just modified the readme file in your PR

**Comment by mart-e** [comment]
Ok, I am then closing this PR. You can reopen one with the CLA when you want to make a contribution then (as it's only needed to contribute to the code).

**Pull request closed without merging**
