### PR TITLE
[FIX] l10n_ch: Fix QR bill according to specs

### PR DESCRIPTION
**Pull request by lordkrandel**
Reworked the structure of the HTML and the SCSS to adhere to the official specs:

- 5mm padding inside the two main sections
- Correct font sizes
- Bold headers
- Increased the Swiss Cross inside the logo (7mm x 7mm)
- Scissors pictogram on the outline
- Dashed borders

Sizes now take the wkhtmltopdf (1/1.25 factor) shrinking into consideration.

Ticket link: https://www.odoo.com/web#id=2584899&model=project.task
Specs: https://www.paymentstandards.ch/dam/downloads/style-guide-en.pdf

opw-2584899

### CODE REVIEW

**Review by william-andre — COMMENTED** [review]
This is going to break the report for those who were happy with its current state because the CSS and the global variable will be updated without the xml when restarting the server.

Or was it impossible to be happy with it all all the Swiss customers will have to update the module no matter what?

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Review by d-fence — CHANGES_REQUESTED** [review]
May I ask to put font license files alogside with the fonts (just like in this commit: bc1a017bb8751e)

**Comment by lordkrandel** [comment]
> May I ask to put font license files alogside with the fonts (just like in this commit: [bc1a017](https://github.com/odoo/odoo/commit/bc1a017bb8751ecb86e579ddb60d8833cf5bbbdc))

Sure! Added. you can find it here:
https://github.com/odoo/odoo/pull/80009/files#diff-b6e0dedca0b4ef19bae2ff8f31b0955ddefb132840ac907d2e8082d36b4d94f3R1

**Review by d-fence — APPROVED** [review]
Thx for the license

**Comment by william-andre** [comment]
@robodoo r+

Still needs an override?

**Comment by Xavier-Do** [comment]
@robodoo override=ci/style

**Pull request closed without merging**
