### PR TITLE
[IMP] base: report_render() to render PDF using API

### PR DESCRIPTION
**Pull request by kmagusiak**
Description of the issue/feature this PR addresses:
Add a method to be able to render ir.actions.report using the RPC API.

Current behavior before PR:
The existing methods to render the reports are private.

Desired behavior after PR is merged:
Have a public method that can be called via RPC.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kmagusiak** [comment]
Can this be reviewed by the security team? How can I tag them?

**Comment by kmagusiak** [comment]
@rco-odoo Do you know who can approve the ci/security job check?

**Comment by ryv-odoo** [comment]
Hi @kmagusiak , it looks like a duplicate of the controller called [report_download] (https://github.com/odoo/odoo/blob/16.0/addons/web/controllers/report.py#L87) in the web module.

**Comment by kmagusiak** [comment]
> Hi @kmagusiak , it looks like a duplicate of the controller called [report_download] (https://github.com/odoo/odoo/blob/16.0/addons/web/controllers/report.py#L87) in the web module.

I wanted to add this because I did not find a way to call and http route using the [RPC API](https://www.odoo.com/documentation/17.0/developer/reference/external_api.html#logging-in) as the http routes use a different way to authenticate than the RPC.

**Pull request closed without merging**
