### PR TITLE
[IMP] doc: specify the minimum version of PostgreSQL

### PR DESCRIPTION
**Pull request by mart-e**
Fixes odoo/odoo#34226

### CODE REVIEW

**Comment by mart-e** [comment]
@robodoo r+

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
You forgot the Windows section!

Don't you find it weird to say "download the **latest** version (**\<not the lastest\>** or later)"?
This sentence was formulated this way (not mentioning the exact version but encouraging to use the latest one) because of our policy regarding the supported versions (Debian's latest and stuff like that). Shouldn't we figure that out before changing the doc ?

**Comment by AntoineVDV** [comment]
@Feyensv r-

**Comment by mart-e** [comment]
> Don't you find it weird to say "download the latest version (<not the lastest> or later)"?

Yeah a bit, is "10.0 or later supported" better ?
Actually it should be fine even in 9.5 but we don't want to be stuck in supporting a very old version if we want to use a fancy new psql feature.
As mentionned by @KangOl good to have a look at the [end-of-life dates](https://www.postgresql.org/support/versioning/) of postgresql too (postgresql 10.0 supported until nov 2022, odoo 13.0 supported until sep 2022!)

**Comment by Yenthe666** [comment]
Maybe it's also nice to mention the newest supported (and tested) version?

**Comment by mart-e** [comment]
> Maybe it's also nice to mention the newest supported (and tested) version?

No, same as for python versions, the goal is to always support the new versions (except major incompatible changes like python 2 vs 3). If it doesn't work with a new version, it's a bug and it should be fixed.

**Comment by mart-e** [comment]
Thanks for the rebase
@robodoo r+

**Comment by mart-e** [comment]
Posted "Thanks for the rebase" in wrong tab, but I guess I deserved it too :thinking:

**Comment by Yenthe666** [comment]
Self-love is important too 😆

**Pull request closed without merging**
