### PR TITLE
[IMP] project: change share to share task

### PR DESCRIPTION
**Pull request by dhrs-odoo**
Before this PR when we share task then in action menu only share was shown

In this PR to make it user friendly we have made share task for task in action menu

task-3328065

### CODE REVIEW

**Review by auon-odoo — APPROVED** [review]
lgtm :zap:

**Review by MissingNoShiny — APPROVED** [review]
LGTM, thanks! :slightly_smiling_face:

**Comment by xavierbol** [comment]
LGTM, thanks for your work. 🙂 

robodoo r+

**Review by xavierbol — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
