### PR TITLE
[FIX] website_slides: fix upload without category

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
This commits fixes 6d9b367a79d09d3d7a9dde890ca651aa09b93987 that fixed 0a980d4be6300fbc888dcc9daf760a48c1b0ec32 that fixed dc9fa6e2166ad803c91ca4f3e3e17b8065eeee82 .
Amazing.

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by sswapnesh** [comment]
2 same PRs for the same Fix  :smile: 
https://github.com/odoo/odoo/pull/49663 and https://github.com/odoo/odoo/pull/49623

**Comment by tde-banana-odoo** [comment]
:D

**Comment by Yenthe666** [comment]
Fixception!

**Pull request closed without merging**
