### PR TITLE
[FIX] web: fix calendar mobile view creation record on monthly scale

### PR DESCRIPTION
**Pull request by bastvdn**
issue:
- calendar mobile view (month) > pressing on a day or timeframe to create a task doesn't do anything
if the view does not have the "day" calendar scale set up

Fix:
- We are removing the condition preventing the renderer to use the createRecord callback when
the view is Mobile and in monthly scale

So now a record will be directly created when a user clicks on a timeframe in monthly view even
if he's in mobile view

Task-3677216

15.0 PR: https://github.com/odoo/enterprise/pull/54386

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by MissingNoShiny — APPROVED** [review]
LGTM, thanks! :slightly_smiling_face:

**Comment by xavierbol** [comment]
Coucou @bastvdn 

I discussed with the framework JS team about that annoying issue and we concluded to fix it in the generic code instead of doing custom classes to avoid that issue.

The idea is to completely remove [the code to load the calendar view in day scale when we are in mobile and the scale is month](https://github.com/odoo/odoo/blob/faccc71d6614582128968ab86785e230eddcbad0/addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js#L204-L210) since the day is correctly set when we click on a day and if the user would like to set the time then he can do it in the form view of the new record to create. 🙂 

Can you do it in that PR instead of your changes? 🙂 

Thanks in advance! 🙂

**Comment by xavierbol** [comment]
Also it seems the task id mentioned in your commit message points to the wrong task. 🤔

**Comment by bastvdn** [comment]
@xavierbol Done
Thanks for checking this up

**Comment by xavierbol** [comment]
@bastvdn it seems some tests have to be updated. 🙂

**Comment by bastvdn** [comment]
@xavierbol 
Should be good, thanks for checking with Framework :)

**Review by xavierbol — COMMENTED** [review]
LGTM, thanks again for your work. 🙂 

I just change the commit title since we changed the code in web module instead of calendar one. 🙂

**Comment by xavierbol** [comment]
Coucou @aab-odoo ,

Here is the PR to remove the special behavior when we are in mobile and the scale is in month [as discussed on discord](https://discord.com/channels/678381219515465750/687338039717920792/1196487823767908393). 🙂 

We also remove that behavior in 15 but [in another PR](https://github.com/odoo/enterprise/pull/54386) since the changes were in enterprise before 16. 🙂

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
