### PR TITLE
[IMP] web: Deactivate swipe between form view in mobile

### PR DESCRIPTION
**Pull request by pparidans**
The swipe between the form view is taking too long to load, and the pager is a
more clean option to switch between form view.
Moreover, the swipe on tabs is not clear anymore.

- Deactivate swipe between form view
- Swipe should only be available on tabs when tabs are too long to fit in one screen.

Related task: 1924764

### CODE REVIEW

**Comment by adr-odoo** [comment]
@robodoo r+

**Comment by adr-odoo** [comment]
@robodoo r-

**Comment by adr-odoo** [comment]
@robodoo r+

**Comment by adr-odoo** [comment]
@robodoo r-

**Comment by adr-odoo** [comment]
@robodoo r+

**Comment by mart-e** [comment]
@adr-odoo but the build is still failing

**Comment by adr-odoo** [comment]
@robodoo retry

**Comment by adr-odoo** [comment]
@robodoo r-

**Comment by adr-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
