### PR TITLE
[CLA] ACSONE signature of Corporate CLA 1.0

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
cc/ @adrienpeiffer @anthony-muschang @Cedric-Pigeon @chrisdec @JonathanNEMRY @laetitia-gangloff @lmignon @Olivier-LAURENT @phschmidt

**Comment by odony** [comment]
Thanks!

**Comment by sbidoul** [comment]
Oops, there were 2 errors in e-mail addresses. I rebased the change on the same branch. Shall I do another PR?

**Comment by odony** [comment]
@sbidoul Don't bother with a new PR, amended it at 9d167ea, thanks!

**Pull request closed without merging**
