### PR TITLE
[FIX] mail, activity view: filter out unrelevant activity types

### PR DESCRIPTION
**Pull request by qdp-odoo**
There're chances that the activity types are not relevant for the displayed objects, filtering out those never used avoid displaying empty columns in the activity view.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
just in case this needs to be argued: this small change is hardly needed to make the activity view usable on tasks, in our prod

image

**Comment by tde-banana-odoo** [comment]
You should probably check with Lna or Cpe (not sure who handles this).

**Comment by qdp-odoo** [comment]
one of those @LNAodoo @Cecile-CPE ?

**Comment by qdp-odoo** [comment]
:cry: please, someone, approve this PR and help me manage my fistful of developers efficiently!!

**Comment by tde-banana-odoo** [comment]
Hello,

Still thinking this should go through either Discuss either SM pipe and validated by functional people. Do you have a task with a discussion with our beloved POs ?

I did not test the activity view recently but wasn't it possible to schedule / send emails directly from this view ? In which case, hiding types could be annoying for that matter maybe ?

Cheers,

**Comment by LNAodoo** [comment]
Hello @qdp-odoo ,

Thanks for the feedback & PR and sorry for the delay.
I indeed answer more rapidly on tasks as there I can set reminders, ... (activities).

Not sure the solution you offer here is the best way to handle the issue.
AFAIK, It is intended to show activity types that are not yet "used" because then you can create new activities on the fly.
https://tinyurl.com/yeszlxfq

Looks like the issue here is rather that the activity type configuration has been done "anarchically".
There are a lot of activity types that should either not exist (they're redundant and thus not very useful) or that should be linked with other models and thus not shown on tasks.

If this clean up is done, I believe you should be able to use this view more easily already.

Available in PMs in case you wish to discuss this further.
Cheers!

**Comment by tde-banana-odoo** [comment]
@LNAodoo which leads me to thinking we should somehow allow activity types to be used for a group of users (something like "displayed only for those users"). A bit like filters (own filters), but shared with some people. Could allow to remove some of the noise @qdp-odoo has, because I suppose someone uses those activity types (hopefully).

**Comment by LNAodoo** [comment]
I do not have access rights to check this but I'm pretty sure many of those are never used and are either things done by a single user "because" or leftovers of previous processes of other teams.
As a side note, not sure "Exceptions" should appear here as it is normally a technical type we use for errors, ...

@tde-banana-odoo Not sure user groups are the answer for this because I tend to think it's rather related to the context.
Maybe turning res_model into a m2m could already be an improvement? https://tinyurl.com/yzmts76c
Because what happens in those case is that people prefer to keep it open "just in case", even though it clutters the other apps.

Like: I schedule whatsapp calls on both contacts & leads and I do not want to create 2 activity types so let's just keep it open to all models.

So here, as I myself have basic sales access, I would still see those activity types used by the sales group.

(Then there is also the fact that it depends on the project because there are customer implementations, upgrades & migrations, RD imps, ... all with their different "To-DOs")

Cheers!

**Comment by qdp-odoo** [comment]
> AFAIK, It is intended to show activity types that are not yet "used" because then you can create new activities on the fly.
> https://tinyurl.com/yeszlxfq

you can also do it even if you don't see the column 
image



That being said, my first intuition was to propose to be able to select a list of activity type per project, to filter out all crap from other project than mine... but that wouldn't solve the issue I have, right now, on our prod. And I'm not planning on cleaning the activity types on odoo.com neither. I don't even have the rights to create a new one for myself.

**Comment by qdp-odoo** [comment]
> ut that wouldn't solve the issue I have, right now, on our prod. And I'm not planning on cleaning the activity types on odoo.com neither. I don't even have the rights to create a new one for myself.

@LNAodoo What I mean is: the issue exists now, in v15 (before?) and I'd like it to have an applicable solution that doesn't wait for the next saas, or the eventual cleanup of years of activity history. Mine doesn't.

**Comment by tde-banana-odoo** [comment]
@qdp-odoo Seems we should first cleanup odoo.com then see if the feedback still applies. For the odoo.com cleanup, normally project managers have access to activity types. It means that if you are project manager you can effectively organize your daily work through activity types. This seems a valid behavior.

Cheers,

**Comment by qdp-odoo** [comment]
@LNAodoo cleanup attempt of our production DB shown that only 3 activity types would be cleaned up. :roll_eyes: 

Could you reconsider?

**Comment by tde-banana-odoo** [comment]
Related to https://www.odoo.com/web#id=2697722&menu_id=4720&cids=1&action=333&active_id=965&model=project.task&view_type=form

**Comment by qdp-odoo** [comment]
@LNAodoo @tde-banana-odoo I changed my PR in order to keep always the current behavior, except when a context key is passed to rip off the unused activity types.

Hopefully, everyone should be happy with this version?

**Comment by qdp-odoo** [comment]
@LNAodoo @tde-banana-odoo what happened to the task related to this PR? the link is broken, and I still have my usability problem

**Comment by LNAodoo** [comment]
Hello @qdp-odoo ,

Funny you ask now, we discussed this during the roadmap meetings (I had kept it in the backlog) and an improvement has been launched in the JS pipe.
See: https://www.odoo.com/web#id=3039919&cids=1&model=project.task&view_type=form

Available on Discord if you wish to discuss that further.

Hope it helps,
Cheers!

**Comment by qdp-odoo** [comment]
closing this PR, since a task started to improve that.

Thanks @LNAodoo

**Pull request closed without merging**
