### PR TITLE
[FIX][14.0]website_forum: fix shallow copy obj

### PR DESCRIPTION
**Pull request by hieu1211**
Fix shallow copy obj that cause wrong value in forum model
Screenshot from 2022-03-15 14-21-14

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hieu1211** [comment]
@tde-banana-odoo Can u spend few second to see, i think it surely a bug.

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by MiquelRForgeFlow** [comment]
runbot is red

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
