### PR TITLE
[IMP] odoo.py: time to be python2 explicit

### PR DESCRIPTION
**Pull request by rim-odoo**
- Some distros link `python` to python3, some others stay on python2: an
  explicit call to python2 would be nice
- See line 22
- See PEP394 https://www.python.org/dev/peps/pep-0394/
- ArchLinux rules!

### CODE REVIEW

**Comment by xmo-odoo** [comment]
```zsh
> python2 --version
zsh: command not found: python2
```

**Comment by rim-odoo** [comment]
@xmo-odoo Time to move to a compliant distro? ;-)

**Comment by bwrsandman** [comment]
I am on arch linux and this is especially important for us
```
 ls -l $(which python)
lrwxrwxrwx 1 root root 7 25 mar 13:30 /usr/bin/python -> python3
```
Arch is usually first to implement these types of changes but other distributions will eventually follow this convention.

**Comment by antonylesuisse** [comment]
Not sure, why is it backward incompatible ? It's stupid ipv6-style.

Can we confirm that every system has the python2 executable in path.

debian derivatives seems to have it.

What about RHEL, OSX, windows ?

**Comment by nhomar** [comment]
You should start is the migration to python3 not to other distro.... :-)

**Comment by bwrsandman** [comment]
@antonylesuisse related PEPs on the subject:
* http://legacy.python.org/dev/peps/pep-0397/ (Windows)
* https://www.python.org/dev/peps/pep-0394/ (Unix-like)

**Comment by antonylesuisse** [comment]
My question was, can macosx users can confirm that it works (which version of maccos) same for RHEL users.

**Comment by nhomar** [comment]
I simply made:

```shell
$ sudo ln -s /usr/bin/python /usr/bin/python2
```
On MacOSx and it works.

But IMHO it is fairly tricky and you should document it, if that pass it is Ok for me follow the PEP.

**Comment by sle-odoo** [comment]
on centos7

[root@nightly-tests] # ls -l $(which python)
lrwxrwxrwx 1 root root 7 Jul 14 14:02 /usr/bin/python -> python2
[root@nightly-tests] # ls -l $(which python2)
lrwxrwxrwx 1 root root 9 Jul 14 14:02 /usr/bin/python2 -> python2.7
[root@nightly-tests] # ls -l $(which python2.7)
-rwxr-xr-x 1 root root 7136 Jun 24 00:42 /usr/bin/python2.7

**Comment by antonylesuisse** [comment]
@nhomar are you running ysoemite ? If yosemite ins't compliant is it planned that El captain will be ?

**Comment by antonylesuisse** [comment]
The latest version of Mac OS X, El Capitan, comes with Python 2.7 out of the box. So no we continue to use env python.

**Pull request closed without merging**
