### PR TITLE
[PERF] spreadsheet: fetch all records with one RPC

### PR DESCRIPTION
**Pull request by LucasLefevre**
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rrahir** [comment]
@robodoo r+

**Comment by LucasLefevre** [comment]
robodoo rebase-ff
please

**Comment by LucasLefevre** [comment]
rododoo r-
likely breaking staging: https://runbot.odoo.com/runbot/build/67359598

**Comment by LucasLefevre** [comment]
or maybe it's the recent list sorting feature

**Comment by LucasLefevre** [comment]
robodoo r-
b no d :grimacing:

**Comment by rrahir** [comment]
@robodoo r+

**Comment by pro-odoo** [comment]
robodoo r+

**Pull request closed without merging**
