### PR TITLE
[FIX] account: restrict product deletion if used

### LINKED ISSUE #65445: >13.0 Invoice line doesn't restrict linked product deletion
Impacted versions: >13.0

Steps to reproduce:

- Create a new product
- Make an invoice with such product in the line
- Validate the invoice
- Delete the product

Current behavior:

- The product record gets deleted and all the `account.move.line` records lose that info.

Expected behavior:

- Up to 12.0, `product_id` field in `account.invoice.line` had an `ondelete="restrict"` to avoid such inconsitencies. With the merge with `account.move.line`, such restriction has been removed.

### PR DESCRIPTION
**Pull request by william-andre**
Fixes #65445

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by william-andre** [comment]
Shouldn't we also restrict for UoM, Analytic values, and maybe other fields?

**Comment by smetl** [comment]
@william-andre I think we can... to check with @qdp-odoo

**Comment by Yenthe666** [comment]
@qdp-odoo @smetl any update? :)

**Review by smetl — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
