### PR TITLE
[CLA] JorgeJuarezCasai

### PR DESCRIPTION
**Pull request by JorgeJuarezCasai**
[CLA] JorgeJuarezCasai

### CODE REVIEW

**Comment by mart-e** [comment]
Is this one still needed as we are merging #54016 ?

**Comment by JorgeJuarezCasai** [comment]
hello @mart-e this is my work email, can you merge please?

**Comment by JorgeJuarezCasai** [comment]
> Is this one still needed as we are merging #54016 ?

hello @mart-e  this CLA is for my work email, can you merge please?

**Comment by JorgeJuarezM** [comment]
@mart-e any update?

**Comment by JorgeJuarezCasai** [comment]
@mart-e any update?

**Comment by mart-e** [comment]
Hi,
Yes we can merge it too but not if the PR is closed. Do you still need it?

**Comment by JorgeJuarezCasai** [comment]
sorry @mart-e, is reopen now. Thank you!!

**Comment by mart-e** [comment]
If it is a corporate CLA, you could also sign the coporate CLA
https://github.com/odoo/odoo/blob/12.0/doc/cla/sign-cla.md#if-you-work-for-a-company
which one do you prefer?

**Pull request closed without merging**
