### PR TITLE
Master responsive close popup pim

### PR DESCRIPTION
**Pull request by pimodoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pimodoo** [comment]
@elkr-odoo we've merged the @caburj PR that allow to have multiple popups open, could you adapt this PR to use it instead of the stuff made with "state.displayPaymentsDifferencePopup"

**Comment by elkr-odoo** [comment]
Hi @pimodoo, I just pushed the refactored task (with JCB's changes) this morning. Isn't it visible to this PR? I pushed it at the main simplify task PR (#81226) What do I need to do? Thanks!

**Comment by pimodoo** [comment]
@elkr-odoo ok, but could you do it in this PR (or another) with juste the part on the closing popup.

**Comment by elkr-odoo** [comment]
@pimodoo ok sure, I'll ping you when it's done :)

**Comment by pimodoo** [comment]
thank you, not problem

**Pull request closed without merging**
