### PR TITLE
 [FIX] account: reconcile payments against min date_maturity journal item

### PR DESCRIPTION
**Pull request by jorenvo**
1. Create a payment term with:
   - 50% due now
   - balance due in 14 days
2. Validate an invoice with this payment term and partner Agrolait
3. Create a payment from Agrolait with the 50% due
4. Add this outstanding credit to the invoice

It is reconciled with the balance due in 14 days instead of what is
due now. Because of this e.g. the Aged Receivable report will show the
customer being overdue with a payment.

This issue was first fixed in 9.0 at
adad192. It was then reintroduced in
saas-11.4 at d3d2612. This commit
adds a test to avoid regressions like this.

To fix the issue this sorts journal items by their Due Date if there
is one. Otherwise we use the date from the journal entry as before.

Note that before this commit journal items were not sorted at all by
the two 'sorted' statements. sorted returns a sorted recordset, it
doesn't modify the recordset it's called on.

opw-1906665

### CODE REVIEW

**Comment by jorenvo** [comment]
@nim-odoo this is for our internal instance. Do you think for something like this I should target v11 or is saas-11.4 ok?

**Comment by qdp-odoo** [comment]
I'd target the oldest supported stable version where the issue is present, otherwise we take the risk of having to backport it upon someone's complaint. v9 or v10?

**Comment by jorenvo** [comment]
Can the both of you re-review?

When trying to port this fix to 10.0 I noticed it actually worked there. I traced the issue to https://github.com/odoo/odoo/commit/d3d26120614139fd7d7e888bd66d21de5158a034, which was in fact introduced in saas-11.4. So I changed my fix. See commit message for more details.

**Comment by qdp-odoo** [comment]
@robodoo r+

thanks Joren! :+1:

**Comment by jorenvo** [comment]
Thank you both for the reviews and merge!

**Pull request merged**
