### PR TITLE
[IMP] mail: Return a browse record in _track_subtype instead of xmlid

### PR DESCRIPTION
**Pull request by tivisse**
Purpose
=======

- A manager could want to follow only home working of its own department
- A HR officer could want to follow only sick leaves of all dpts.

We have to improve what people follow and how they follow it in the leaves module

Specifications
==============

Subtype on department
---------------------

In department form view, right now, people can follow approvals

Instead we should have some generic and specific subtypes depending on the leave type

For instance, a HR Officer wants to follow only sick leaves and a manager only home working

Following mechanism
-------------------

Remove first / second approval subtype differences
if a leave type is not linked to a specific subtype, consider only classic
people follow it (employee and assigned HR people / manager)

Link leave type to subtypes, with some by default (i.e. home working, ...), not mandatory

When creating a leave type, link it to the department to be able to
activate the subtype for only one department.

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo If @tivisse says r+ please do an r+. What do you want, that @mart-e puts things in a place that is not designed to accept it ?

**Comment by tde-banana-odoo** [comment]
Ok, you want to fight.

**Comment by xmo-odoo** [comment]
@tde-banana-odoo I need to fix the message (missed that variant when I implemented feedback), what it's really saying is that the PR is already r+'d so r+-ing it makes no sense.

Also this PR has (most likely) been linked to the pr in enterprise which has the same label (2810), and that one does not pass runbot, and both are supposed to before they're going to get staged. Though robodoo is supposed to [send a helpful message](https://github.com/odoo/odoo/pull/27929#issuecomment-430981708), I need to check why it hasn't done that.

**Comment by tivisse** [comment]
@robodoo retry

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo Your answers are much smarter than those from odoobot. I think I am in love with you.

**Pull request closed without merging**
