### PR TITLE
[FIX] calendar: hide 'sync' options from users

### PR DESCRIPTION
**Pull request by reth-odoo**
## Issues

- When the google and outlook sync plugins are not installed the admin user should see an option to install them from the calendar but other users should not see anything.

- The 'groups' guard would have prevented regular users from syncing their calendar at all if it had worked

- Users can get an obtuse error message if the administrator has not configured the installed sync modules

## Fix

- Replaces the 'groups' attribute in the calendar controller template with a t-if and a dynamic check as OWL doesn't process 'groups'.

- Update the structure of the calendar sync template to facilitate overriding the display conditions
- Update the inherits to override the display conditions and allow anyone to see the sync button once a module is installed

- Update the code that handles clicking 'sync' to throw the same error as it would have for other misconfigurations

task - 3056311

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@arj-odoo Zboing !

**Review by arj-odoo — CHANGES_REQUESTED** [review]
I am Ok with the technical change but I don't like the `showToUser` naming because it is not self-explanatory. We don't know on what it relies and what it does (the controller can be used to show a lot of things). I would prefer `isSystemUser` or something similar. What do you think ?

**Comment by thiryr** [comment]
Yeah, it makes more sense to name it based on what it is, not what it does. I'll change that, thanks for having a look :)

**Review by arj-odoo — APPROVED** [review]

**Comment by thiryr** [comment]
Couple of changes:

- Fix 'authorization error' when the calendar API key isn't properly configured and a user tries to sync.
 -> add a condition around the things that handle 'errors' on sync and check user rights.
- Users should be able to see the 'sync' button once the app is installed.
 -> add a wrapper div with a condition that is overriden to ``true`` whenever one of the modules is installed.

**Comment by arj-odoo** [comment]
> Couple of changes:
> 
>     * Fix 'authorization error' when the calendar API key isn't properly configured and a user tries to sync.
>       -> add a condition around the things that handle 'errors' on sync and check user rights.
> 
>     * Users should be able to see the 'sync' button once the app is installed.
>       -> add a wrapper div with a condition that is overriden to `true` whenever one of the modules is installed.

Those additions are legit but don't hesitate to split your commit to help review. IMHO the fix of `isSystemUser` should be in a separate commit. These two additions could be in separate commits too. Thanks :-).

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Pull request closed without merging**
