### PR TITLE
[FIX] snailmail: Fix a CSS selector

### PR DESCRIPTION
**Pull request by delvsola**
This PR fixes a malfunctioning selector. The padding fix has been removed because it is already handled by the invoice fix.

### CODE REVIEW

**Comment by lobaudoux** [comment]
@robodoo r+

**Comment by delvsola** [comment]
@robodoo retry

**Comment by delvsola** [comment]
@robodoo retry

**Comment by d-fence** [comment]
robodoo retry

**Comment by d-fence** [comment]
oopd didn't see the force push :-)

**Comment by lobaudoux** [comment]
@robodoo r+

**Pull request closed without merging**
