### PR TITLE
[IMP] website_sale: notify user when email is already registered

### PR DESCRIPTION
**Pull request by elierwclik**
Description of the issue/feature this PR addresses:
During the checkout process, when a public user enters an email that is 
already associated with an existing account, Odoo creates a new contact 
rather than associating the order with the existing user. This leads to 
the creation of duplicate contacts and issues when users attempt to register 
later with the same email address.

Current behavior before PR:
- Odoo creates a new contact even if the email entered in the checkout 
  is already linked to a registered user.
- This can result in multiple accounts for the same user, causing confusion 
  and a poor user experience.

Desired behavior after PR is merged:
- If the email entered during checkout is associated with an existing user, 
  the system will notify the public user and prompt them to log in.
- This will prevent the creation of duplicate contacts and ensure the 
  order is properly linked to the existing user account.

This enhancement improves the overall user experience by guiding users 
to log in when their email is already registered, maintaining consistency 
and preventing account duplication.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
Hi @elierwclik, you included many cosmetic changes (e.g., extra spaces, line breaks, etc.) in your commit, probably due to automatic reformatting. Could you please remove the cosmetic changes so we can take a look at the functional changes? Thanks

**Review by elierwclik — COMMENTED** [review]
Completed

**Comment by Feyensv** [comment]
This is a security issue, we cannot leak whether an account already exists or not, it's the customer responsibility to login if he has an account, we won't tell him that he already has an account.

If there are multiple partners that are the same person, you can merge those safely with the dedicated wizard, but we won't tell a public customer whether accounts exist with the email address he gave.
It's not an issue if multiple customers want to use the same email address to buy stuff on the shop in my opinion.

**Comment by elierwclik** [comment]
> This is a security issue, we cannot leak whether an account already exists or not, it's the customer responsibility to login if he has an account, we won't tell him that he already has an account.
> 
> If there are multiple partners that are the same person, you can merge those safely with the dedicated wizard, but we won't tell a public customer whether accounts exist with the email address he gave. It's not an issue if multiple customers want to use the same email address to buy stuff on the shop in my opinion.


In user registration, when trying to register an account with an email that is already registered, we get the following message: "Another user is already registered using this email address."

So is this a security issue?

**Comment by Feyensv** [comment]
Well, it's a bad practice, and not a good idea to do it in another place :D.
But the main login logic is not managed by our team.

**Comment by elierwclik** [comment]
> Well, it's a bad practice, and not a good idea to do it in another place :D. But the main login logic is not managed by our team.

Captura de pantalla 2024-09-26 a las 12 54 04 p  m

Captura de pantalla 2024-09-26 a las 12 56 26 p  m

**Comment by Feyensv** [comment]
Still doesn't explain how it's a problem if two customers use the same email address.

**Comment by elierwclik** [comment]
> Still doesn't explain how it's a problem if two customers use the same email address.

This results in duplicate contacts and creates inconsistencies in the system, leading to problems such  as confusion over which account holds the correct order history, loyalty points, 
or other customer-specific information.

- This leads to the creation of duplicate accounts with the same email, 
  which can result in confusion for both the customer and the business. 
- Problems arise when two contacts share the same email, such as difficulties 
  managing order history, account security, or customer communications. 
  In some cases, the same customer may have orders scattered across multiple accounts.

**Comment by Feyensv** [comment]
Well, if you don't want this to happen, you can force users to sign in during checkout with the dedicated ecommerce setting.
I don't believe it's safe to change this in a stable version right now, we'll try to improve this logic in future versions.

**Pull request closed without merging**
