### PR TITLE
[FIX] web: fix SelectMenu object shallowEqual

### PR DESCRIPTION
**Pull request by Iucapad**
Since commit (1), the clear button is only displayed when a selected value is found from the available choices. But since we used shallowEqual to find the corresponding choice, we couldn't use objects containing objects in its values, since a simple comparison was made in the utility function.

As the SelectMenu can support any kind of value, and to avoid spending too much resource for each option to determine if a choice can be associated with the current value, we created a quickShallowEqual function in the file of the component, to only verify that values of the object are equal if they are not object themselves. In that case, we simply compare the length of the objects.

The test using object as values has been improved to use an object for one of its values, and an assertion for the presence of the clear button has been added as well.

(1): d760b812714f317476c0af0424ae330e7d89a0fd

### CODE REVIEW

**Comment by Iucapad** [comment]
@ged-odoo To be sure: so we should also prevent the caller to use arrays as the choice value?
For example, choices like 
```
[
   { label: "Small size", value: [0, 10],
   { label: "Medium size", value: [0, 100],
   { label: "Large size", value: [0, 1000],
]
```

**Comment by ged-odoo** [comment]
hmm, right. It's never so simple indeed. But yes, I don't think it is the SelectMenu job to do that. The caller can choose any system to make it work. He can give any string/number as value, for ex `"OPTION_0_TO_10", "OPTION_0_TO_100", ...` and when he needs the array, convert the option into an array.

But here is another idea: what about removing the "value" prop, and instead add a `selected` optional key in each choice?

**Comment by Iucapad** [comment]
> But here is another idea: what about removing the "value" prop, and instead add a `selected` optional key in each choice?

I would prefer the first option, with the props. This is more similar to the way a native select works, by giving it a value

I'll change the way it was used in studio (with arrays) and make a PR for that, so we only handle strings as values

**Comment by Iucapad** [comment]
Hello @ged-odoo The PR is ready to re-review. I removed the ability to use arrays/objects for SelectMenu and adapted the code where needed:
- base_import here
- web_studio in PR https://github.com/odoo/enterprise/pull/40177

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
