### PR TITLE
[CLA] Signed CLA for JorgeJuarezM

### PR DESCRIPTION
**Pull request by JorgeJuarezM**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JorgeJuarezM** [comment]
@C3POdoo r+

**Comment by JorgeJuarezM** [comment]
@mart-e can you help me please?

**Comment by JorgeJuarezM** [comment]
@mart-e any update?

**Comment by mart-e** [comment]
Thanks for the new PR, don't worry, we are going to merge it.
@robodoo r+

**Pull request closed without merging**
