### PR TITLE
[FIX] web,*_*: fix the html content in notification

### PR DESCRIPTION
**Pull request by mba-odoo**
Currently, markup-ification of the legacy notifications system display the html content in notification layout for some of the
notification of document and planning since commit: https://github.com/odoo/enterprise/commit/ba44461fea337ed2e5adbdfa1e8eede00b036def

So here in this commit, we make the method `makeLegacyNotificationService` always `_.escape(message)` and pass `messageIsHtml: true` to the owl notifications system so notification with html content will be displayed properly.

Task-2657391

### CODE REVIEW

**Comment by IT-Ideas** [comment]
Hello @mba-odoo , it might be a good idea to ping `xmo-odoo` when you are done in order to ask him to review 🙂 
Thanks!

**Comment by mba-odoo** [comment]
@xmo-odoo , Could you please validate the changes regarding the comment: https://github.com/odoo/enterprise/pull/21206#discussion_r725855049

Thanks

**Review by xmo-odoo — CHANGES_REQUESTED** [review]
A few fixes necessary to the bridge between legacy and new notifications, and some uses of `_.str.sprintf` could be improved by using the version from `web.utils` instead as that one is Markup-compatible.

**Review by xmo-odoo — APPROVED** [review]

**Review by aab-odoo — APPROVED** [review]
Seems fine. Not sure I would have converted those legacy calls as we'll drop that code anyway.

**Review by tde-banana-odoo — COMMENTED** [review]
LGTM globally, thanks for your PR !

I just have to warn that you mix old and new ES6 styling (var / const). I would use the current file's coding style (use var when file uses var, use const when file uses const). Could be great to cleanup those files, but as we target stable I would keep a minimal diff in order to keep only what is relevant to the feature itself.

I let @IT-Ideas give the final word on that point anyway :) .

Cheers,

**Review by IT-Ideas — COMMENTED** [review]
Thanks for the fix 🙂

**Review by qsm-odoo — COMMENTED** [review]
@IT-Ideas Nothing more to say than you :wink:

**Comment by mba-odoo** [comment]
@IT-Ideas , @tde-banana-odoo , Done the changes. Thanks

**Pull request closed without merging**
