### PR TITLE
Master latammerge2 jco

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
supersedes #35729

**Comment by jco-odoo** [comment]
@qdp-odoo  (delegate+ normally)

**Comment by qdp-odoo** [comment]
@robodoo delegate

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@d-fence If you can give it a go before the freeze, it would make my life a lot easier.

**Comment by nhomar** [comment]
@d-fence

**Comment by d-fence** [comment]
sorry, I didn't see the message before the freeze

**Pull request closed without merging**
