### PR TITLE
[FIX] Production Lot On Hand api.depends

### LINKED ISSUE #59929: [14.0] Production Lot quantities do not update mid transaction.
Impacted versions:

14, 13, 12, 11

Steps to reproduce:

In a routine - check the "product_qty' of a lot, validate a transaction, and retrieve the value of product_qty again.

Current behavior:

product_qty does not change

Expected behavior:

product_qty should change to reflect the validated move

Video/Screenshot link (optional):

### PR DESCRIPTION
**Pull request by richard-willdooit**
Fixes #59929

Production Lot quantities are not recalculating
mid transaction without depends.

Description of the issue/feature this PR addresses:

In a routine - check the "product_qty' of a lot, validate a transaction, and retrieve the value of product_qty again.

Current behavior before PR:

product_qty does not change

Desired behavior after PR is merged:

product_qty changes to reflect the validated move.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
Just rename the header of commit message with:
[FIX] stock: Production Lot On Hand api.depends

**Comment by richard-willdooit** [comment]
@amoyaux Any chance this can go through, now?

**Comment by amoyaux** [comment]
Could you rename the commit header by
[FIX] stock: Production Lot On Hand api.depends

**Comment by richard-willdooit** [comment]
@amoyaux Renamed - cheers.

**Comment by amoyaux** [comment]
robodoo r+ rebase-ff

**Pull request closed without merging**
