### PR TITLE
Make exp_report() signature correspond to the one in web_services

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to make the method signature in `base_calendar` correspond to its base in https://github.com/odoo/odoo/blob/7.0/openerp/service/web_services.py#L701 .

### CODE REVIEW

**Comment by yvaucher** [comment]
Signature is clearly wrong and forbid to use this method by naming datas args if base_calendar is installed.

:+1: 

The error is due to https://github.com/odoo/odoo/commit/474e665fcc4b0434e67d0b9ea8db62d7bc22623b

**Comment by gurneyalex** [comment]
'datas' is really ugly. Can't we fix this the other way round?

**Comment by pedrobaeza** [comment]
I also think that the name is incorrect, but there are a lot of ocurrences, so :+1: for this

**Comment by nim-odoo** [comment]
@gurneyalex : yeah, 'datas' is ugly, but we cannot change the signature of the method in the stable version. Still, I will apply this fix.

**Comment by nim-odoo** [comment]
Merged with d0e39720e3aaa5a1cf67bd9fa5470ceaeaf97cac

**Comment by mdietrichc2c** [comment]
Thanks @nim-odoo !

**Comment by gurneyalex** [comment]
thanks

**Pull request closed without merging**
