### PR TITLE
[FIX] sms: save the record before opening the sms wizard

### PR DESCRIPTION
**Pull request by caburj**
**Issue:**

- Open crm.
- Open a lead.
- Input a number in the phone field.
- Click everywhere for the input to be recognized.
- Click the sms button that appears when hovering over the phone
  field.
- BUG1: The shown dialog doesn't have the inputted phone number.
- BUG2: When closing the dialog, any changes made in the form
  before clicking the sms button are lost.

**Solution:**

Make sure the changes are saved before calling the action that
shows the wizard.

After this fix:
- The phone number input in the form is now used in the
  wizard.
- When closing the wizard, the "unsaved" changes are kept.

**Illustrations:**

Before: https://www.awesomescreenshot.com/video/12226501?key=0eb0433bb59589ebe1aa8a10c10ef8d9
After: https://youtu.be/w96dMZDNZ7Q

TASK-ID: 3056454

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
Hello @odoo/rd-discuss. I have this PR which is linked to a task. It would be nice to write a test for it but I failed to find a way to do it.

I'm think of writing a fix similar to the steps shown in the youtube video I linked in the description. However, the problem is the step when the "sms" button is clicked. I have no way of showing the "form" view of the "sms.composer". Maybe I can do it by mocking the view, but in my opinion, mocking it is not correct because future changes will render the test "correct" when in fact it's outdated.

Or do you have a better way of testing it, can you teach me?

**Comment by alexkuhn** [comment]
Hello!

At a glance this fix is hardly testable with QUnit tests.

Similar tests that do some coverage with `doAction()` usually just mock it to assert that it's intercepted, but it usually doesn't test result of `doAction()`. I think it's because `doAction()` like this one rely quite a lot on server, and `MockServer` lacks too many features to simulate behaviour of opening dialog with form view.

So at best, if you really want some test coverage from this fix, it's more a tour that you are looking for.

**Comment by caburj** [comment]
Thank you so much @alexkuhn for a complete response. I learned something new.
In my opinion, writing a tour test for this fix is too much, so if you can approve this PR without any test or you don't have extra comments, then we can proceed.

**Review by alexkuhn — APPROVED** [review]
LGTM. Thanks!

@robodoo r+

**Pull request closed without merging**
