### PR TITLE
[IMP] account: export `AccountMoveFormRenderer` to allow the OCR to e…

### PR DESCRIPTION
**Pull request by lobaudoux**
…xtend it

Enterprise PR: odoo/enterprise#30931
Related task: #2858695

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by h4818 — APPROVED** [review]

**Comment by lobaudoux** [comment]
@robodoo r+

**Comment by h4818** [comment]
@robodoo r+

**Comment by h4818** [comment]
@william-andre please

**Comment by william-andre** [comment]
@robodoo r+

**Comment by FrancoisGe** [comment]
robodoo r+

**Pull request closed without merging**
