### PR TITLE
[CLA] Signature for cunivca

### PR DESCRIPTION
**Pull request by cunivca**
New CLA signature with updated email address

### CODE REVIEW

**Comment by cunivca** [comment]
@mart-e I created a new one.

**Comment by mart-e** [comment]
@cunivca I am afraid you have the same issue. You can see the "legal/cla" failing and you can check your commits by addind `.patch` at the end of the URL
https://github.com/odoo/odoo/pull/114750.patch

**Comment by mart-e** [comment]
If you are not sure how to change your git configuration, it's also fine to sign the CLA with your noreply address. Just put `65897790+cunivca@users.noreply.github.com` instead of your `@edoo.is` address.

**Comment by cunivca** [comment]
Hi Martin,

thank you. I did another PR with the anonymized email. Hope it goes through
now!

**Pull request closed without merging**
