### PR TITLE
[FIX] event: access right for admins of event app

### PR DESCRIPTION
**Pull request by joanna350**
1. Install [Events]

2. On [Settings], create an admin for Events (uncheck all other rights)

3. Click on Events, enter an event

3. Click on [Communication] tab, and try adding a line

Issue: accessing ir.model is blocked from commit 5dc4cff60a557e14b08440c227423291c407899b

Solution: partial revert

Impacted versions: 15 - master

opw-3163138

### CODE REVIEW

**Comment by nle-odoo** [comment]
I think for security team, they didn't want this solution. So currently the previous solution (https://github.com/odoo/odoo/pull/112527) would be better.

If this solution was preferred (and the security team changed opinion, which there is no indication of), there would be solution that would that would allow to add access to the ir.model().name without giving access to the whole model.

**Comment by mart-e** [comment]
> Currently I think the solutions preferred by security team are:

Yes exactly, we don't want to re-add the rights on ir.model, especially for something minor like this.

**Comment by tde-banana-odoo** [comment]
This makes me very very sad.

**Comment by tde-banana-odoo** [comment]
> Don't be sad! [5dc4cff](https://github.com/odoo/odoo/commit/5dc4cff60a557e14b08440c227423291c407899b) if this was a measured decision, seems reasonable we take the previous solution. If requests accumulate to allow read access, decisions could be made with POs and other DMs?

Sometimes we have to admit we cannot win all fights !

**Pull request closed without merging**
