### PR TITLE
Deprecate returning domains from onchange

### PR DESCRIPTION
**Pull request by xmo-odoo**
Cap of task 2115872 in order to prevent re-addition of dynamic domains, and warn third-parties at runtime.

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodo rebase-ff

**Comment by xmo-odoo** [comment]
@robodoo rebase-ff

**Comment by len-foss** [comment]
Hello @xmo-odoo 
It seems you have deprecated dynamic onchanges, but the deprecation message does not give any hint to what to use instead. 
From 6c4ac28f332eb5c382512585641865ace3f563ea, I gather that they should be replaced by setting the fields domain parameter. 
However I see two issues with it. Suppose with have a class A in module M, and M1, M2 that both inherit depend directly on M. 
- if in M we have `f = fields(..., domain=d)` with d a string, then we have no way to extend d in a safe way in both M1 and M2. That problem would be sidestepped by having the domain key extend the list, or deprecate the domain as a string and require to pass a callable, so that inheritance can be properly done. Pretty easy to do as a somewhat stable fix.
- now we have a much bigger issue: if domain is of the form `[(fff, "=?", fff)]`, then the framework requires the field to be in the view. This means we can't do proper inheritance at all: in our example, if M1 adds such a domain, if M2 adds a new view on model A, it should be inherited to add field `fff` in the view, however `fff` does not exist at all in M.

It seems that the second issue would require to be solved to deprecate dynamic onchanges. 
I haven't seen any discussion of the subject, not documentation about it, so it's very possible that I'm missing something here.

**Comment by len-foss** [comment]
Hello @mart-e 
Could you have a look at this issue? I believe it may have a real impact on how some models can be overriden.

**Comment by mart-e** [comment]
@len-foss this task is linked to onchange so doesn't really change your inheritance questions (I guess you were using the onchange as a workaround to the same issue). Making complexe dynamic domains on fields is ... complexe I am afraid. There are no easy solution on that.

**Comment by len-foss** [comment]
Hey @mart-e :-)
I'm a bit confused. There's an issue for which dynamic onchanges were a workaround (although not a perfect one, I'm with you on that). If the workaround is removed, then I believe the issue should be addressed.
Without this workaround it will be necessary to do unsafe unheritance, and so the situation will be worse for the community. 
(I can also send you another issue that was dismissed on the basis that dynamic onchanges are the Odoo recommended way to do things.)

**Comment by pedrobaeza** [comment]
The idea behind this is to have a field for determining the allowed values:

```python
allowed_value_ids = fields.Many2many(
    comodel_name="x",
   _compute="_compute_allowed_value_ids"
)

def _compute_allowed_value_ids(self):
    for record in self:
        record.allowed_value_ids = self.env["x"].search(...)
```
and the inheritance will come through the override of method `_compute_allowed_value_ids`, adding or removing values.

Then the field with the domain will be defined as:

```python
value_id = fields.Many2one(
    comodel_name="x",
    domain="[('id', 'in', allowed_value_ids)]",
)
```
and inserting both fields in view will be enough. You play also with the depends of the compute to trigger the recomputation of allowed values.

**Comment by len-foss** [comment]
Hello @pedrobaeza . What you suggest is completely orthogonal to the problem I describe. 
I did not even talk about "complex" domain. In fact the problem I had is with very simple domains. 
Just say that with have M, M1, M2, with Mi depending on M, but not on each other. Also consider that M has domain="[t]".
I want M1 to add triple t1, M2 to add t2, so that if things compose well, installing the 3 modules result in [t, t1, t2], independently of the installation order.
That's how it works generally for functions, and what you expect for modules to compose well. 
What you suggest work only if Odoo decides to rewrite all standard model to only use functions, so that they can be properly overriden (which I mentioned in my first comment).

**Comment by pedrobaeza** [comment]
That's a similar problem to compute writable fields, and my proposal for making them compatible when the module where the field is defined is not under your control (i. e. and Odoo core module):

https://github.com/OCA/odoo-community.org/pull/50/files

You need to be rigid with the naming convention and the way to do it.

For this case, you should:

- On module M1 depending only on M, define the `allowed_value_ids` computed field, and its compute method with the super trick I depict in the link.
- Redefine the original field, and add the domain.
- Add the field as invisible in the view.
- On module M2, do exactly the same for the 3 previous points.

**Comment by len-foss** [comment]
The workaround you suggest would only works if everybody decides to use the convention, would actually not really be strictly enforced, and it relies on another workaround that suffers from the same issues. This workaround is going to require quite some work and energy. 
But furthermore, Odoo has an app store, so you should ideally convince all other (non-OCA) Odoo developers. They do promote the app-store in conjunction with Odoo.sh as a great way for companies to get customize their Odoo. So if users install add-ons that break other ones silently because inheritance cannot be done properly, that's really a loss for everybody.
So, I think it would be more productive to rather solve the issue, which I don't think is too hard to begin with.

**Comment by pedrobaeza** [comment]
The compatibility breakage has been always in any modular/inheritable system, and it depends on the quality of the involved code. If your solution is to keep a "breakable" mechanism (returned domains on onchanges), and not use the new "breakable" system (everything is computed), then you get a most complex system with more options to fail and to maintain.

**Comment by sbidoul** [comment]
`domain="[('id', 'in', allowed_value_ids)]"` has significant performance implications when allowed_value_ids is large.

IMO, the "domain field" approach of https://github.com/odoo/odoo/pull/17328 has a lot of potential. It would be cool if you could look at it again (@xmo-odoo?).

**Pull request closed without merging**
