### PR TITLE
[FIX] calendar: make get_next_potential_limit_alarm private

### PR DESCRIPTION
**Pull request by JKE-be**
Even if data is not really sensitive, there are no reason to let it public.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Comment by sswapnesh** [comment]
It seems @robodoo  don't want to make `get_next_potential_limit_alarm`  private :stuck_out_tongue_winking_eye: 


@JKE-be  I have made this method private few days ago but was willing to make single PR with few more Fixes/IMPs as mentioned in https://github.com/odoo/odoo/pull/32932#issuecomment-488366641  https://github.com/odoo/odoo/pull/32932#issuecomment-488624266

**Pull request closed without merging**
