### PR TITLE
[FIX] hr_holidays: multi-period accrual reset at year start

### PR DESCRIPTION
**Pull request by fdamhaut**
Step to reproduce:
- Create an accrual plan with the option "at the end of the year,
 unused accruals will be lost" and that can be allocated every year
(in this example, 3 days)
- Create an allocation for Marc Demo based on that accrual plan
 and starting in 2020.
- Run scheduled action
 "Accrual Time Off: updates the number of time off"
- Connect as Marc Demo

Current behaviour:
- Marc Demo has receive a 6 day allocation
- While loop over the elapsed period doesn't take lost time into account

Behaviour after PR:
- Marc Demo receive 3 day allocation

opw-2769066

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fdamhaut** [comment]
@kba-odoo

**Comment by fdamhaut** [comment]
@Williambraecky Mind seeing if everything is good now ?

**Comment by Williambraecky** [comment]
Hello @fdamhaut LGTM, thanks 😄 

@kba-odoo ping

**Comment by kba-odoo** [comment]
robodoo r+

**Pull request closed without merging**
