### PR TITLE
[REV] web: reverts update to fontawesome 5.11.2

### PR DESCRIPTION
**Pull request by kbapt**
This reverts commit ff1c35513aecef5fbc30f7c2f3834450e719714e.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo delegate kba-odoo

**Comment by seb-odoo** [comment]
Shouldn't this target 13.1 where it was introduced?

**Comment by tivisse** [comment]
Yes, indeed. 

@robodoo r-

**Comment by kba-odoo** [comment]
@robodoo r+

**Comment by kba-odoo** [comment]
@tde-banana-odoo can you please r+ this PR? Looks like the delegate didn't work

**Comment by tde-banana-odoo** [comment]
@robodoo r+

So long little fontawesome.

**Comment by tde-banana-odoo** [comment]
@robodoo r+ p=0

**Pull request closed without merging**
