### PR TITLE
[8.0][IMP] Force threaded mode for unit testing.

### LINKED ISSUE #14802: HTTP tests not working with PreforkServer
Impacted versions: 8, 9, 10

Steps to reproduce:

1. Try to run PhantomJS tests setting some workers: `odoo.py --database demo --init website --test-enable --update website --workers 4 --config /etc/odoo/openerp-server.conf` [to make Odoo use `PreforkServer`](https://github.com/odoo/odoo/blob/8245c1d1d87b443701b161d8d4a42df2b4d13aec/openerp/service/server.py#L961-L962).
2. Now do it [setting `--workers 0` to use the `ThreadedServer`](https://github.com/odoo/odoo/blob/8245c1d1d87b443701b161d8d4a42df2b4d13aec/openerp/service/server.py#L963-L964), which [includes support for HTTP tests](https://github.com/odoo/odoo/blob/8245c1d1d87b443701b161d8d4a42df2b4d13aec/openerp/service/server.py#L314-L317).

Current behavior:

On step 1, you'll get `phantomjs: <phantomLog>error Timeout`.

Expected behavior:

Test should get executed correctly, like on step 2.

@Tecnativa @odony

### PR DESCRIPTION
**Pull request by yajo**
Fixes #14802 and gives a hint in the logs to know what's happening.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa @odony

### CODE REVIEW

**Comment by Yajo** [comment]
Before you tell me, I know 8.0 is old version of odoo with only fixes, but I consider this one a fix (developer-side POV), and includes no changes in models, signatures or currently-working testing environments.

**Comment by Yenthe666** [comment]
Warning is better, info is really easy to miss.

**Comment by Yajo** [comment]
I think I forgot to say this is a warning now.

**Comment by tivisse** [comment]
@antonylesuisse @odony 

This might be interesting. Probably not for 8.0 (except if you think it's a good idea) but it could be cool :)

Waiting your input.

**Comment by odony** [comment]
It looks like a safe change, but it's not, unfortunately. We've been bitten by similar changes to the handling of server config and startup parameters before, and we know better now ;-)

People are running Odoo with all kinds of exotic configs and setups, sometimes broken in various ways, but those systems are *in production* and you never know how they will be affected by the new behavior. We should never change the startup behavior in any manner unless we're fixing a critical security problem, where the risk of breaking production systems is worth taking. "Developer convenience" does not sound like a strong reason for breaking this policy ;-)

In fact, even for `master`, I'm not sure overruling the `workers` parameter is a good idea. The warning should be quite enough, shouldn't it?

**Comment by Yajo** [comment]
True, done 😉

**Comment by tivisse** [comment]
@odony 

I'm not sure it's really useful to log a warning if you launch the tests with workers. It's a very common use case isn't it ? 

By the way if you're ok with the PR I can merge it in master. 

Thanks.

**Comment by Yajo** [comment]
Yes, very common, that's exactly the problem. See https://github.com/odoo/odoo/issues/14802

**Comment by antonylesuisse** [comment]
Approved

**Comment by tivisse** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `commit`
- you are signing for the address `signature`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by Yajo** [comment]
Thanks, fixed. There was still my last company's CLA, where I work no more.

**Comment by tivisse** [comment]
@Yajo Thanks for the update.

Your improvement has been merged in master at https://github.com/odoo/odoo/commit/a567cd796e75a5f019b35237de8304f0e771bf43

Have a nice day,

Yannick.

**Pull request closed without merging**
