### PR TITLE
Rename kab_DZ.js to kab-DZ.js

### PR DESCRIPTION
**Pull request by MohammedBelkacem**
Bug when trying to load Kabyle translation. File name error.

### CODE REVIEW

**Comment by belkacem77** [comment]
Bug fixed with new file name

**Comment by belkacem77** [comment]
Hello mart-e,
The globalization js filename syntax should be "kab-DZ.js" not "kab_DZ.js". There is an error when loading Kabyle translation.

**Comment by rsi-odoo** [comment]
Merge in this commit 916525fbf3cec60f3bb8e365d58fe09850c5ab34

**Comment by nim-odoo** [comment]
Merged with 916525fbf3cec60f3bb8e365d58fe09850c5ab34

**Pull request closed without merging**
