### PR TITLE
[FIX] stock: Replenishment allowed warehouses

### PR DESCRIPTION
**Pull request by BT-anieto**
Apart from the wrong domain, the performance issues are also huge.

Description of the issue/feature this PR addresses:
Wrong code. Wrong domain, affecting also performance

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Nice fix :+1: 

But see [guidelines](https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html#tag-and-module-name).

**Comment by BT-anieto** [comment]
@MiquelRForgeFlow Thx! I hope I did it properly now.

**Comment by MiquelRForgeFlow** [comment]
I think the CLA thing goes in a separate commit, but not sure. I would say we should wait for Odoo people's review.

**Comment by BT-anieto** [comment]
What do I need to do here?

**Comment by BT-anieto** [comment]
Hello. Can this be merged?

**Comment by pfertyk** [comment]
Hi @BT-anieto and thank you for your contribution :+1: Could you please separate the CLA commit from the rest of your PR?

**Comment by BT-anieto** [comment]
@pfertyk Done!

**Comment by pfertyk** [comment]
Thank you! But I think that something went wrong with the rebase ... 338 commits doesn't sound right :sweat_smile: Could you please fix this? :wink:

**Comment by BT-anieto** [comment]
Hello @pfertyk Can I do anything else here? Why is ci not working?

**Comment by pfertyk** [comment]
My guess is that another rebase could solve this issue :shrug: But if it doesn't, I will investigate further. The changes in your PR are very small and should not result in failed upgrade checks :thinking:

**Comment by clesgow** [comment]
Thank you!
@robodoo r+

**Comment by clesgow** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
