### PR TITLE
[FIX] l10n_do: Adapt CoA to local and legal requirements needed for Norma 07-2018

### PR DESCRIPTION
**Pull request by gustavovalverde**
Description of the issue/feature this PR addresses:
The CoA is missing terms and accounts needed in the new legislation which starts on May 1st in Dominican Republic.

Current behavior before PR:
CoA does not comply with the legislation

Desired behavior after PR is merged:
CoA complies with the legislation

**P.D.:** I tried to reduce the changelog on the account change from 5 to 6 as it's not as much as it seems.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nhomar** [comment]
Hello @gustavovalverde 

The changes make sense.

Can yout share a video with all intalling properlly please?

**Comment by gustavovalverde** [comment]
Well somehow I managed to broke it after the test and before the last commit. Now it does install; thanks for the heads ups 😉

**Comment by gustavovalverde** [comment]
@mart-e this can be merge as it is, well be later making some tiny adjustments, but in the meanwhile this is the minimal required so we can keep up working with the legislation.

**Comment by mart-e** [comment]
@qdp-odoo could somebody in the accounting team check that as it is kind of urgent? Thanks!

**Comment by qdp-odoo** [comment]
landed in v11 at revision https://github.com/odoo/odoo/commit/080094207888f4514f6a0a8f0263166d7998bbf5

Thanks Gustavo

**Pull request closed without merging**
