### PR TITLE
[CLA] Update Vauxoo's Contributor CLA

### PR DESCRIPTION
**Pull request by payen000**
Incorporate Agustín Payen (payen000) as Vauxoo's contributor.

I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

### CODE REVIEW

**Comment by payen000** [comment]
Hello @luisg123v,

Could you review this, please?

**Review by luisg123v — APPROVED** [review]
LGTM :+1: 

@fw-bot up to saas-14.5

**Comment by luisg123v** [comment]
FYI @mart-e ,

This one is up to saas-14.5, because this is a backport from 15.0 (#110355).

Regards,

**Comment by mart-e** [comment]
@robodoo r+
@fw-bot ignore
(saas-14.5 is no longer supported)

**Pull request closed without merging**
