### PR TITLE
[IMP] mail: add and update sound effects of rtc call interactions

### PR DESCRIPTION
**Pull request by ThanhDodeurOdoo**
task-2692600

### CODE REVIEW

**Comment by ThanhDodeurOdoo** [comment]
Draft until the final sound effect(s) are added from task-2699653

**Comment by ThanhDodeurOdoo** [comment]
Master equivalent of https://github.com/odoo/odoo/pull/79941

**Comment by alexkuhn** [comment]
Just reduced and adjust volume level of all sound effects, so it's nicer overall.
The audio stop-to-non-zero issue is significantly reduced as a consequence, so could be a future improvement if this level of quality is desired. It'd feel slightly over-engineering at the moment.

**Review by alexkuhn — APPROVED** [review]
@robodoo r+ rebase-ff

**Pull request closed without merging**
