### PR TITLE
[ADD] Welcome l10n_pe_website_sale

### PR DESCRIPTION
**Pull request by desdelinux**
New module that adds peruvian requirements to the website ecommerce

 * Add fields to the checkout form
   * Identification type
   * City
   * District
 * Add logic to validate the new fields
 * Take into account the identification type when validating the VAT in the checkout form
 * Change label name for the vat field, to show "Number" instead of "VAT number".
 * Add demo data to display a peruvian website and show products with taxes
 * Add module translations
 * Hide default city

Task Latam: https://latam-localizations.odoo.com/web#id=916&menu_id=88&cids=1&action=188&model=project.task&view_type=form

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by desdelinux** [comment]
@luisg123v @luistorresm 

Can you review?, please

**Comment by yoanymora** [comment]
@desdelinux  review finished, after those suggestions, LGTM

**Comment by fvz-odoo** [comment]
Hello @desdelinux 

I tested this but it is asking me for an empty field, but all fields are filled up... Not sure if it has to have real info or why is it not letting me go through this to the payment step. Still, tried with our testing info, and didn't work also. Could you please check? By the way, is it expected to be showing the other fields once I fill up the previous one? For example, I did not see the city field until I filled up the state field, I did not see the district field until I filled up the city field... Just checking because when you choose Peru, it only shows the default value for the state, and if you do not wanna change the default value, it does not show you the city field until you want to continue (if you change the default state value, then the system open the city field as expected).

Here's a pic of the error about required fields.
Screenshot 2023-05-01 at 11 51 00 AM



Thanks!

Fernando

@ren-odoo @vbe-odoo

**Comment by desdelinux** [comment]
> Hello @desdelinux
> 
> I tested this but it is asking me for an empty field, but all fields are filled up... Not sure if it has to have real info or why is it not letting me go through this to the payment step. Still, tried with our testing info, and didn't work also. Could you please check? By the way, is it expected to be showing the other fields once I fill up the previous one? For example, I did not see the city field until I filled up the state field, I did not see the district field until I filled up the city field... Just checking because when you choose Peru, it only shows the default value for the state, and if you do not wanna change the default value, it does not show you the city field until you want to continue (if you change the default state value, then the system open the city field as expected).
> 
> Here's a pic of the error about required fields. Screenshot 2023-05-01 at 11 51 00 AM
> 
> Thanks!
> 
> Fernando
> 
> @ren-odoo @vbe-odoo

This is solved @fvz-odoo

**Pull request closed without merging**
