### PR TITLE
[Wishlist] point_of_sale: facilite inheritance to create invoice

### PR DESCRIPTION
**Pull request by celm1990**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by celm1990** [comment]
@mart-e @pimodoo can anybody help me with this PR please

**Comment by celm1990** [comment]
Please guys is very import this change, on V13 is working fine, see https://github.com/odoo/odoo/blob/13.0/addons/point_of_sale/models/pos_order.py#L362

change are losses in commit https://github.com/odoo/odoo/commit/beaa30a3d1843de43a45f419bfbc1bfa7613a920 
but is back on commit https://github.com/odoo/odoo/commit/b93232475689adf6d2d6953ba7804a9ef2934f08 for V13, but master not reflect changes

**Comment by pimodoo** [comment]
@celm1990 I've merged it in saas-13.3, it'll be forward ported to master: https://github.com/odoo/odoo/pull/56993

**Comment by celm1990** [comment]
thank you so much

**Pull request closed without merging**
