### PR TITLE
WIP: 11.0 unhide eprpeek returned error when unicode message

### PR DESCRIPTION
**Pull request by geekobi**
Description of the issue/feature this PR addresses:
Unhide error from erppeek call when exception is except_orm, Warning or AccessError and message is unicode and not simple string :
When calling a odoo object methode through erppeek, if an error is raised with an unicode error message (for instance a french language message with some accents), if error is an instance of openerp.osv.orm.except_orm, openerp.exceptions.Warning or openerp.exceptions.AccessError, then wsgi_server.py:wmlrpc_handle_exception() calls xmlrpclib.Fault() with parameters faultCode and faultSring in reverse order, and as faultCode doesn't support unicode strings it raises an error. If the error message is a simple string, there is no error and as code is '', the permutation of code and string is not visible.
The issue impacts all versions from 7.0 to 11.0 at least (not checked others)

Current behavior before PR:
Raise an unicode string error when managing the error and loose the initial error message

Desired behavior after PR is merged:
Get the original error in the erppeek caller to help the caller to fix his error

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by geekobi** [comment]
I tried several change in my cla and nothing works.
If anybody has an idea of want is wrong with my cla I'd be thankfull !
(I check, my login, my email, my country, the date, etc ...)

**Comment by mart-e** [comment]
Hello,

Please rebase your branch to remove the OCA merge commits and remove the `.travis` file.
For the CLA, this is also link to the mulitple commits. you use several different email addresses.
Please keep one commit (or 2 if you want to keep one for the CLA) only using the email address present in the CLA.

Could you also give a way to reproduce the error you mention?

**Comment by geekobi** [comment]
ok, I will do this. Right now I've just succeded to validate my cla, so cleanup my commits was not my immediate objective.
If I could save the reproduce in v11, I'd appreciate because in fact I got the error with Odoo v8.0 and as the error is clear in the code and the code is the same in all versions >= 8.0 I declared it first with odoo v11 but I intend to make also the same PR in odoo v10, 9, 8 as it is a bug.
In this condition, is it ok to not reproduce the bug in odoo 11 ? (otherwize, I will try to reproduce but it will take some time).
(and because of all those delays, I temporarily added a "WIP:" prefix to the title of my PR.)
Regards, Herve

**Comment by mart-e** [comment]
Is there still something here?
Could you detail how to reproduce it and on which version?

**Pull request closed without merging**
