### PR TITLE
Master hotkey add Tab & Delete navkeys

### PR DESCRIPTION
**Pull request by SplashS**
Description of the issue/feature this PR addresses:
This PR adds ability to track Tab & Delete shortcuts via hotkey_service.

Current behavior before PR:
Developers can't use hooks `useHotkey("Tab", ...)` or `useHotkey("Delete", ...)`

Desired behavior after PR is merged:
Developers can use hooks `useHotkey("Tab", ...)` or `useHotkey("Delete", ...)`

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by SplashS** [comment]
@FrancoisGe Could this PR be helpful?

**Comment by brboi** [comment]
Hello @SplashS 
Can you share usage examples ?
Thanks

**Comment by SplashS** [comment]
> Edit: OK for Delete this is obvious, but I am wondering why you would want to use Tab for ?

I'm worried about future migration of the `web_responsive` module.

`Tab`, `Shift+Tab` are used for navigating Search results in Apps Menu in 14.0 version of `web_responsive`.
image
https://github.com/OCA/web/blob/cef972152c969d0347232048e1e13ccf74516441/web_responsive/static/src/js/web_responsive.js#L272

Also I can suggest that `Tab` will be useful for the same reason in `web_enterprise`. According to master enterprise runbot search results in AppsMenu are navigated by `Tab`, `Shift+Tab`. But handling code doesn't migrated to hotkey_service yet.

**Comment by ged-odoo** [comment]
looks good to me
robodoo r+

**Comment by ged-odoo** [comment]
robodoo: rebase-ff

**Pull request closed without merging**
