### PR TITLE
[IMP] mrp: Provide hook methods in _bom_explode

### PR DESCRIPTION
**Pull request by pedrobaeza**
With these 2 simple hooks, more data can be attached to each workcenter/consume line.

@beledouxdenis, please help me for having this merged so that we can avoid nasty workarounds in mrp extensions.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@rafaelbn, this is needed for avoiding errors on mrp_operations_extension. Please check.

**Comment by pedrobaeza** [comment]
@anajuaristi, please check this one for improving the modules.

**Comment by Daniel-CA** [comment]
:+1:

**Comment by qtheuret** [comment]
:+1:

**Comment by rafaelbn** [comment]
:+1:

**Comment by rafaelbn** [comment]
@mart-e @beledouxdenis any comment?

**Comment by antespi** [comment]
:+1:

**Comment by mart-e** [comment]
Sorry but these are not bug fixes (making it harder to maintain), so should target master version, not version 8.
It was integrated at ed57bb90a7e1a7ff37a1b448f3eebd041acd0dd0
Regards

**Comment by pedrobaeza** [comment]
Thank you very much for put this on master, but that means that until version 10, we can't use this possibility, which makes our modules for v8/v9 very hard to avoid problems. I know that this is not a bug fixing, but it isn't also a feature, it's a code reordering, so I beg you to reconsider to include on v8/v9.

**Comment by mart-e** [comment]
Sorry but this kind of patch makes it harder to maintain odoo. For instance there was a conflict while merging due to the changes in v9. Merging code reordering in 8 means introducing a risk of creating (or reintroducing) bugs during forward ports (which are already complicated enough).

**Comment by pedrobaeza** [comment]
Sorry for insisting, but there isn't any way to get this merged on v8? We really need it. I can help you in whatever you tell me to do to assure compatibility merging.

**Comment by wtaferner** [comment]
@mart-e 
You are right, but the downside is that these hooks should always be there in the first place (quality control during master dev)...now you have put it in master which is completely out of sight...so you force us to fork and maintain our own core which is kind of inevitable in certain use cases anyway...almost nobody is using v9 in production yet and it is not so far away from master, I guess...can't we just find a way to allow such changes...forward porting is for sure not always easy and at a certain stage risky but this can be immediately and individually tested when considering where to merge it...can't we just find a way how to make these contributions work for all stakeholders?

**Comment by odony** [comment]
I guess it would still make sense to backport this small refactoring to Odoo 9 - in master the whole MRP stack will be rewritten anyway.

**Comment by pedrobaeza** [comment]
And in v8, please? :angel:

**Comment by odony** [comment]
Odoo 8 has been out for more than a year now and has lots of users running in production, it's really too late for nice-to-have changes, sorry.

**Comment by pedrobaeza** [comment]
OK, thank you very much anyway for at least having on v9. My bad for not proposing before...

**Comment by spadae22** [comment]
@pedrobaeza Nice work. I am going to merge it with v8. As I know from experience, v9 stable is a long way away....

**Comment by mart-e** [comment]
Ok cherry-picked in 9.0 at fbc66b29e347e0856215fdd39e33b96ed1a1b79f

**Comment by duanyp1991** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Thanks again!

**Pull request closed without merging**
