### PR TITLE
[CLA] Sign CLA for p-tombez

### PR DESCRIPTION
**Pull request by p-tombez**

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hmm, sure you guys don't want to do this against 11.0 or so instead of master? Master will be the upcoming V12.

**Comment by yvaucher** [comment]
@Yenthe666 ok just figured out you asked for one CLA change per version in another PR.

@p-tombez you might want to target at least 9.0, 10.0 and 11.0 then.

**Comment by p-tombez** [comment]
@yvaucher Will do

**Comment by mart-e** [comment]
Merged in 9.0 at https://github.com/odoo/odoo/commit/f435bc4fe9f4da40116a249ee498a02f09f83d54, will be ported to master soon (can take a few days/weeks to go all way to the top)

**Comment by Yenthe666** [comment]
@yvaucher I think I was not clear enough, sorry for that. The idea is to make the CLA against the lowest version you wish to contribute too. In your example this is 9.0. Odoo will then forward port it to 10.0, 11.0, master for you.

**Pull request closed without merging**
