### PR TITLE
[FIX] l10n_tw: translation cannot be applied on account data

### PR DESCRIPTION
**Pull request by tong-odoo**
Issue:

  - Translation cannot be applied on account data.
  - Replace icon with the one existing in the base module

Cause:

 Missing spoken_languages

Solution:

 Add back spoken_lanugages

X-original-commit: 9521f7e

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by fja-odoo — COMMENTED** [review]
Can you mention the commit introducing the issue as well as explain that you also replace the icon with one existing in the codebase instead of adding a new one.

**Review by william-andre — COMMENTED** [review]
Could you also add a demo company with the CoA loaded and some information needed for a company (i.e. VAT number and/or whatnot)?
See https://github.com/odoo/odoo/commit/d2851b203924dcb0e56e534751a552e99757971b

Working fine otherwise

**Comment by tong-odoo** [comment]
@william-andre Updated

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
