### PR TITLE
[FIX] core: computed fields can be copied if editable

### PR DESCRIPTION
**Pull request by rco-odoo**
Purpose of this commit is to let computed stored editable fields being
copied if their field class allows it.

Indeed the value of those fields is computed based on some triggers but
can also be updated manually by users.  When copying a record, it makes
sense to consider that this value is what the user expects and allow its
copy, if the original field allows it.  Either it was computed, and
copied value will be correct without having to call computation again
(well, provided all dependencies have been copied, too), or it was
updated and the copied value will be the one the user entered.

Without this fix, an edited field is not copied, and will be recomputed,
which may look like an inconsistent value.

Task ID 2209163

### CODE REVIEW

**Comment by rco-odoo** [comment]
@odony is this okay with you?

**Comment by tde-banana-odoo** [comment]
2many test is back :dancer:

**Comment by tde-banana-odoo** [comment]
>  for me
> @robodoo r+
> 
> @tde-banana-odoo we end up with something really close to your original implementation, thanks for your patience and for bearing with the grumpy grandpas... modifying `fields.py` is not something we do every day

**Comment by Feyensv** [comment]
:fireworks:

**Pull request closed without merging**
