### PR TITLE
[FIX] core: delay constraint application in case of upgrade

### PR DESCRIPTION
**Pull request by Elkasitu**
When upgrading odoo, models and constraints will be setup between pre and post migration script. This can be problematic in some case, mainly for required fields when we want to fill required column in post or end scripts. This pr proposes to postpone constrains at the end of registry loading if it fails the first time when updating a module. 

For install, constraints must be applied the first time, when creating table.

### CODE REVIEW

**Comment by Xavier-Do** [comment]
My previous observation was wrong, it's not working (I should learn to avoid to compare apple and oranges) 
The main problematic constraints is actually set_not_null, so update_db_notnull should be managed to. 
Small remarks: it was already the case before, but it is strange to wait to remove a foreign key, or a constraints. So it is maybe more the add_constraint that we want to add in the _constraint_queue, as well as the set_not_null in the update_db_notnull method.

**Comment by Xavier-Do** [comment]
robodoo r+

**Comment by odony** [comment]
Reminds me of a funny story:

-Commit Message: *[FIX] yadda yadda, did this, can't tell you why*
-Me: *Surely the PR description will help and redeem whoever wrote this. For sure there will be a ticket reference (it's a bugfix in stable), a full rationale and everything that I expected to find here*
-PR: *"No description provided." Then some discussion about fruits.*

**Comment by Xavier-Do** [comment]
Sorry for that, you're right.

**Pull request closed without merging**
