### PR TITLE
[FIX] l10n_fr: broken module installation

### PR DESCRIPTION
**Pull request by rgo-odoo**
culprit commit: 4837a8eeef9bad014bc62f2704868e2464729f4b

Fixed missing 'tag_ids' values for account templates when forward
ported above commit from v11.0 to current version.

### CODE REVIEW

**Comment by rgo-odoo** [comment]
@jco-odoo could you please review this quick fix ? Thanks.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
Thanks @rgo-odoo !

**Comment by jco-odoo** [comment]
@alt-odoo fyi

**Comment by alt-odoo** [comment]
Thank you for this @jco-odoo and sorry about the mistake

**Comment by jco-odoo** [comment]
@alt-odoo I would easily have made the same one.  Runbot single builds are going to make sense.

**Pull request closed without merging**
