### PR TITLE
Master web tour fix process mutation jcb

### PR DESCRIPTION
**Pull request by caburj**
1. correct the childList logic in solving hasTrackedMutation.
2. include characterData in the observed list of the mutation observer in tour service.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
ping @d-fence fyi :-)

**Comment by d-fence** [comment]
nice ++++

**Pull request closed without merging**
