### PR TITLE
[FIX] stock: display packaging on delivery slip

### PR DESCRIPTION
**Pull request by taqu-odoo**
Issue
-----
The packing is not displayed on the delivery slip when:
- the product is tracked by lot/SN
- the stock.move state = "Done"
- "Display Lots & Serial Numbers on Delivery Slips" is activated
According to https://github.com/odoo/odoo/commit/c07258c3f27790eea424cee745b2036a3ef0e8c2, packaging information
should always be present.

Fix
-----
We add packaging information to the delivery slip. Also, packaging
quantity needs to be rounded up, for example if we have 2.3 packagings,
it will in reality be 3 packagings.

opw-3820304

### CODE REVIEW

**Comment by HANNICHE-Walid** [comment]
Before:
image

After:
image

note that package qty is actually rounded down 
other than that LGTM

**Review by HANNICHE-Walid — APPROVED** [review]

**Comment by amoyaux** [comment]
You should add the groups group_stock_packaging

**Comment by amoyaux** [comment]
and use t-field instead of t-out when possible

**Comment by taqu-odoo** [comment]
Thanks for the feedback @amoyaux, changes made.

**Comment by amoyaux** [comment]
robodoo r+

**Pull request closed without merging**
