### PR TITLE
[FIX] Quants in a pack added to a parent pack remain in their child pack

### PR DESCRIPTION
**Pull request by npiganeau**
Fixes a bug in current implementation of WMS pack in pack feature

**Current behaviour:**
When a pack A is put inside a pack B:
- Pack A becomes a child of pack B
- The quants of pack A are removed from pack A and put into pack B bulk content

When pack B is unpacked, we get an empty pack A and the quants initially in pack A completely unpacked

**Expected behaviour (fixed by PR):**
When a pack A is put inside a pack B
- Pack A becomes a child of pack B
- The quants of pack A remain inside pack A

When pack B is unpacked, we get pack A back with its quants inside

### CODE REVIEW

**Comment by jco-odoo** [comment]
You are absolutely right about this being an issue and the fix seems correct.  I will check and merge asap.

**Comment by jco-odoo** [comment]
This is still wrong.  Actually when a box is in a box and you move the surrounding box, you should not modify the quants in it at all.

**Comment by npiganeau** [comment]
@jco-odoo We've still got an issue here:
- When we put a pack inside another pack during a transfer => Ok the fix works
- When we just move a pack with another pack inside from one location to another without changing the packing, the child pack is moved to the new location, but the parent pack remains in the original location and is not moved => We get an inconsistency between the location of the parent pack and the location of the child pack. (The quants are moved with the child pack, so this is ok)

**Comment by jco-odoo** [comment]
I could reproduce it.  There has to be a problem somewhere with the stores, because if the quants of some subpackage changes location, the location of the parent package should change also.

**Comment by jco-odoo** [comment]
Made a development branch for this:  8.0-wmspackstore-jco

**Pull request closed without merging**
