### PR TITLE
[FIX] #3670 Don't override previous value if no journal is found

### PR DESCRIPTION
**Pull request by ccomb**
Simple fix to avoid losing the previous value of the journal if nothing is found in the onchange

### CODE REVIEW

**Comment by beledouxdenis** [comment]
I am not sure this is correct.

If you have several journals matching the domain
```
[('type','=','purchase'), ('currency','=',currency_id), ('company_id', '=', company_id)]
```
Including the one that was set before the call to this on change, I can understand this can be problematic.

However, if you had a journal set, in `EUR` for example, and then change the currency to `USD`, and there is no journal matching the domain with the USD currency, I do not think that wrong to remove the journal, otherwise you will have your expense in a EUR journal: This is not forbidden, but this is not necessarily desirable insofar.

What do you think ?

**Comment by ccomb** [comment]
I believe this is a different problem that should be treated separately, and has probably more to do with the journal selection field in the model or in the view.
Currently in the view the field has a very limited domain :

```<field name="journal_id" widget="selection" domain="[('type', '=', 'purchase')]"/>```

another obvious problem is the ```[0]```, but again, this is a different topic.

For now I've fixed the one problem of being unable to define a default journal.

**Comment by beledouxdenis** [comment]
So, what about this request ?

**Comment by ccomb** [comment]
I think it should be first merged (it's already in OCB for a long time), then open another issue or PR for the subject you were talking about, with a reference to this one

**Comment by beledouxdenis** [comment]
I do not agree: You are consciously adding a new issue in order to solve your own issue. This is typically the kind of thing we want to avoid.

A solution that solves your issue, while not introducing a new issue that is not yet there, should be proposed.

**Comment by ccomb** [comment]
I'm not adding a bug, the bug was already there :

- enable multi currency
- create a new expense
- select a USD currency
- select a journal in EUR
- save

capture d ecran de 2015-09-03 11 21 56

However I agree that there is probably a way to fix both bugs at the same time.

**Comment by ccomb** [comment]
Or maybe it's a valid configuration and I should expect the expense in USD to be converted automatically to EUR in the journal? I must admit I've not checked that.

**Comment by beledouxdenis** [comment]
What you mention isn't a bug.

As said, 
> This is not forbidden, but this is not necessarily desirable insofar.

Thus, if the user choose a journal in EUR after changing the currency to USD, it's his problem.

The problem here, with this pull request, is that, at the moment, if the journal is within the EUR currency, and you change the currency to USD, it automatically removes the journal previously selected. It will be no longer the case with this pull request.

If you re-select the journal in EUR currency afterward, then it's ok.

**Comment by ccomb** [comment]
If you select a USD currency, it will *silently* unselect the previous configured journal, which is in another tab. The result is that the chosen journal will be a journal in EUR anyway, because of a ```[0]``` somewhere else.  I consider it a much worse situation we encountered in real HR/Expense projects we've been involved in.  And since you are unable to configure a default journal, you have no easy way to configure or use the Expense module for real.

**Comment by beledouxdenis** [comment]
Still, this pull request should not change the current behavior, it should still remove the journal if there is no journal within the currency that was just set.

**Comment by ccomb** [comment]
The current behaviour is wrong and what you propose is even worse, which is silently and implicitely choosing a wrong journal in almost all cases by disabling the explicit choice of the user.
So I'm sorry I won't have more time to debate on this topic, I prefer letting you find and commit the solution that suits more to you, and hopefuly fix other related issues such as the inconsistency between the currency and the journal, and the wrong default journal selection.

**Pull request closed without merging**
