### PR TITLE
[FIX] translate: export all fields translations

### LINKED ISSUE #3673: Translation terms for new API related fields are not exported
When I have related fields in a custom module, and export translations for it, I don't get any of the strings of these fields (string nor help attributes).

Can you check it, @odony?

### PR DESCRIPTION
**Pull request by nle-odoo**
Take all the field to translate from the registry rather than taking only the
fields present in the database (which correspond to only the stored fields).

fixes #3673

opw-628958

### CODE REVIEW

**Comment by odony** [comment]
Shouldn't we instead fix the fact that new API fields are not properly included in ir.model.fields? Old API fields were, including function fields, so that makes a rather inconsistent result...

**Comment by lmignon** [comment]
see https://github.com/odoo/odoo/pull/5618

**Comment by odony** [comment]
Thanks @lmignon, #5618 looks exactly like what I had in mind. What do you think @rco-odoo @nle-odoo?

**Comment by lmignon** [comment]
@odony I agree with your comment. The API fields should be properly included in the ir.model.fields even if they aren't stored. An other inconsistency introduced by this different behavior between new and old API is that if these non stored fields are no more included in the ir.model.fields, they are no more  referenceable through a relation (One2Many, ...) as pointed by the link previously provided. I really appreciates the new clear separation between field and column. The new api provides a more consistent model and I want to thank you for this great improvement.

**Comment by beledouxdenis** [comment]
Closed by #5618

**Pull request closed without merging**
