### PR TITLE
[IMP] tests: add test_sequence order for tests

### PR DESCRIPTION
**Pull request by aj-fuentes**
Backport of 8aa4f42

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by KangOl** [comment]
@fw-bot disable

**Review by Xavier-Do — APPROVED** [review]
I didn't check in details but LGTM

**Comment by Xavier-Do** [comment]
@robodoo delegate+

**Review by Julien00859 — APPROVED** [review]

**Comment by aj-fuentes** [comment]
@robodoo r+

**Pull request closed without merging**
