### PR TITLE
14.0 ksa arabic english invoice baa

### PR DESCRIPTION
**Pull request by bakboka**
Description of the issue/feature this PR addresses: 
On 4 December 2021, a new law is enacted in Saudi Arabia mandating the invoices to be in English and Arabic as well as adding some new fields and a QR code

This is a copy paste of #78373, except the report is only activated for saudi

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bakboka** [comment]
@odoo/rd-security t-raw="0" is unavoidable in v14 as t-out has been introduced only in v15

**Comment by bakboka** [comment]
@odoo/rd-security can you bypass/ignore the test that is failing? It is failing because i am introducing a t-raw (t-raw="0" at line 545 of addons/l10n_gcc_invoice/views/report_invoice.xml). However, it is not possible to do without it because there is no alternative in v14. I am using it in an external layout template meaning that other templates are going to be injected into it. Using t-esc doesn't work as it show the html code instead of interpreting it.

**Comment by xmo-odoo** [comment]
@robodoo override=ci/security

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
