### PR TITLE
[IMP] web: move back the frontend scrolling out of the #wrapwrap

### PR DESCRIPTION
**Pull request by qsm-odoo**
*: project, survey, web_editor, website, website_event_track

This finally reverts the most annoying part of [1]: the main scrolling
is now back to be the natural browser behavior instead of being moved to
the #wrapwrap element.

As a reminder, this was done for the 14.0 version and above since we did
not want a double scrollbar on the right of the website builder (and
some other advantages at the time). With the relatively recent work of
"website-in-backend" done at [2], the website is now displayed inside an
iframe, and the editor is outside of it. There is thus no reason to have
the scrollbar moved out its natural position.

Having it at its natural position fixes some behaviors we were not able
to fix in stable (= 14.0, 15.0, 16.0, 17.0 now), notably:

- Many mobile browsers (including Chrome on Android) were not able to
  understand that the #wrapwrap had the main scrollbar. We were able to
  scroll of course, but some mobile behaviors were lost:

    - Reaching the top again (by scrolling to the top) and continuing
      scrolling with your finger was not reloading the page.

    - The mobile browser UI was not being hidden when scrolling down.

- The keyboard 'up/down' 'pgup/pgdown' did not work (at least not until
  you focused the right elements).

- Hotjar (analytic heatmap tool) did not work.

- Some browser extensions were not working as were based on scrolling
  the natural scrollbar. For example, even some browser dev tools were
  broken, like the "full page screenshot" feature.

- Pages were not scrollable when viewed through google cache (using
  cache:XXX in your browser).

- Being a scrollable element, the `#wrapwrap` element would sometimes
  (= by some browsers) be considered focusable. Meaning that the first
  "tab" would not focus the first focusable element as wanted but the
  invisible `#wrapwrap` container.

- ...

This could also result in simplifying the code (many things were made
generic so the features would work wherever the main scrollbar is). This
commit although keeps that generic code for now. It will make sense to
get rid of it in the future though as we are always bug-fixing one mode
without bug-fixing the other. And given the fact that supporting having
the scrollbar elsewhere would be bad as advertised by the list of issues
explained above.

Note 1: this also fixes some code that relied on the fact #wrapwrap was
the one scrolling instead of using Odoo utils. As PR like [3], [4] and
[5] (and probably others that were forgotten) did, this is done in a
generic way but as explained above: we will simplify even more later.

Note 2: in a future update, we will also remove the `#wrapwrap` element
entirely. Indeed, now that the website UI is mostly outside of the
website itself (in an iframe when needed) since [2], there is no reason
for that extra div which often worsens the code to be considered. Some
UI remains in the website DOM itself though, to see.

[1]: https://github.com/odoo/odoo/commit/4e7be69825163c0a0ff41c882a196fc7f3158fb3
[2]: https://github.com/odoo/odoo/commit/31cc10b91dc7762e23b4bde9b945be0c4ce3fe3b
[3]: https://github.com/odoo/odoo/pull/98514
[4]: https://github.com/odoo/odoo/pull/102779
[5]: https://github.com/odoo/odoo/pull/159748

task-3586754

### CODE REVIEW

**Comment by qsm-odoo** [comment]
Still need review and testing and waiting for another PR's merge (that I included in this one temporarily), but if somebody want to already have look... let's undraft :) Hopefully I'll sleep better with this 2-years-old PR merged :)

**Comment by qsm-odoo** [comment]
Sorry @odoo/rd-accounting @odoo/rd-account-js the change I made in your app was a mistake, I am removing it, you should not have been pinged, shame on me :grimacing:

**Comment by bvr-odoo** [comment]
@qsm-odoo 
I see an issue with the snippets modal, it doesn't have a vertical scrollbar anymore and it's no longer possible to reach the bottom when scrolling with the mouse wheel.
image

**Review by qsm-odoo — COMMENTED** [review]
It's time to go ahead and let go of a 2-years-long regret of not having merged this in 16.0 when it was a possibility.

We'll investigate the test I shamelessly tweaked to pass via task-4185877, along with its previously existing issues and patches :grimacing: 

@robodoo rebase-ff r+

**Pull request closed without merging**
