### PR TITLE
[FIX] web_editor : fix parallax during edition

### PR DESCRIPTION
**Pull request by sebgeelen**
Bug report :

[JKE]  Drop block / parallax / block
    ╰─[JKE] parralax effect is not visible in edit mode - make it difficult to have what you want if you don't have the preview
    ╰─[JKE] https://drive.google.com/file/d/1VBhJu3xSZ-nZwkMbbHmz36AbsOgjzOfy/view

### CODE REVIEW

**Comment by sebgeelen** [comment]
This seems to work both in normal and edit mode.

However I'm not 100% confident my solution is safe, regarding forcing `#wrapwrap` to be the scrolling element.
Maybe @JKE-be has a better overview on this.

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
`$().getScrollingElement()` should return... the scrolling element of the page which is the wrapwrap element. If something worked in 14.0 and not in master anymore, it is of course something that changed between the two versions: so not this code :wink:

**Comment by sebgeelen** [comment]
I see we have other issue related to this `#wrapwrap` stuff
> 11. [QSM] Header effects don't work in edit mode even though they are started (so: add blocks in the page, scroll, the header does not reappears as it would in non edit mode)
>     ╰─[DMO] Note: you have to drop enough blocks to be able to scroll down obviously
>     ╰─[BVR] related to an issue with getScrollingElement(). It should return #wrapwrap and not html
>     related:
>     [QSM] The editor overlay on top of snippets does not disappear during scroll anymore
>     ╰─[BVR] related to an issue with getScrollingElement(). It should return #wrapwrap and not html

So maybe @bvr-odoo might want to check this too ?

**Comment by bvr-odoo** [comment]
> I see we have other issue related to this `#wrapwrap` stuff
> 
> > 1. [QSM] Header effects don't work in edit mode even though they are started (so: add blocks in the page, scroll, the header does not reappears as it would in non edit mode)
> >    ╰─[DMO] Note: you have to drop enough blocks to be able to scroll down obviously
> >    ╰─[BVR] related to an issue with getScrollingElement(). It should return #wrapwrap and not html
> >    related:
> >    [QSM] The editor overlay on top of snippets does not disappear during scroll anymore
> >    ╰─[BVR] related to an issue with getScrollingElement(). It should return #wrapwrap and not html
> 
> So maybe @bvr-odoo might want to check this too ?

Hi @sebgeelen I have nothing to say different from what @qsm-odoo  said ;)
$().getScrollingElement() should return the scrolling element of the page ...

**Comment by sebgeelen** [comment]
> `$().getScrollingElement()` should return... the scrolling element of the page which is the wrapwrap element. If something worked in 14.0 and not in master anymore, it is of course something that changed between the two versions: so not this code wink

Yeah I agree. 

The problem here is that the `getScrollingElement()` from `/home/odoo/Repositories/odoo/community/addons/web/static/src/js/libs/jquery.js` doesn't return the actual scrolling element ( `#wrapwrap`) in edit mode. 

I think it's because the method only check `document.scrollingElement` and the direct children of this element.
The `#wrapwrap` element is encapsulated in more element in edit mode and so the method can't find it.

I was reluctant to change the `getScrollingElement()` directly because is much more low level, and I am not sure of the implications of such a change.

**Comment by qsm-odoo** [comment]
@sebgeelen 

> The #wrapwrap element is encapsulated in more element in edit mode and so the method can't find it.

This is already a very dangerous change. Of course ideally I'd like to say that it should magically work (and we try to make it work on its own)... but it is a huge guess to rely on the fact the wrapwrap element and its design can all work if not a direct child of the body element. Maybe the safer and easiest fix would be the enable the iframe edition we spoke about with @Gorash, is it possible ? I would not be surprised if this fixed many other bugs at the same time.

**Comment by sebgeelen** [comment]
@qsm-odoo what do you think about my this change of the `getScrollingElement()` method ?

**Comment by qsm-odoo** [comment]
> what do you think about my this change of the `getScrollingElement()` method ?

@sebgeelen I really would not search recursively, the goal was to be generic enough to find the wrapwrap element or the body depending on which scrolls... but without analyzing the whole DOM. If we are doomed to have a hierarchy above the wrapwrap element, I would then prefer for the method to not be generic at all and purely return the wrapwrap element when there is one. Also, I checked the hierarchy and I am surprised that the wrapwrap element as an ancestor with overflow: auto... so should there be anything else in that ancestor, your method would not find the wrapwrap but that ancestor :|

But I really think we should just get rid of that hierarchy, maybe by using the iframe edition as suggested in my previous message. We always faced "the website does not look the same in edit mode" issues before, let's not increase those problems and solve them all once and for all with iframe edition if possible?

**Comment by sebgeelen** [comment]
> But I really think we should just get rid of that hierarchy, maybe by using the iframe edition as suggested in my previous message. We always faced "the website does not look the same in edit mode" issues before, let's not increase those problems and solve them all once and for all with iframe edition if possible

@Gorash @Goaman , do you think this approach is doable without a huge headache ?
I personally don't think I have a good enough overview on the subject to know.

**Comment by Gorash** [comment]
> @sebgeelen
> 
> > The #wrapwrap element is encapsulated in more element in edit mode and so the method can't find it.
> 
> This is already a very dangerous change. Of course ideally I'd like to say that it should magically work (and we try to make it work on its own)... but it is a huge guess to rely on the fact the wrapwrap element and its design can all work if not a direct child of the body element. Maybe the safer and easiest fix would be the enable the iframe edition we spoke about with @Gorash, is it possible ? I would not be surprised if this fixed many other bugs at the same time.

@qsm-odoo 
the use of the iframe is functional, moreover we know how to edit in the mobile (drag & drop, edit... nb: the iframe does not contain any js). But I don't see how this fixes the fact that the scroll can be in different places. There will be the scroll on the body, but will it be the only scroll (snippet can contain other snippets with a scroll, or a side bar ...)? Did the js for your animation snippets work from outside the iframe?

**Comment by qsm-odoo** [comment]
@Gorash The main point here is the position of the wrapwrap element. Its behavior and its design may depend on the fact it is a direct child of the body element, even if we try it does not. So when edited, it would be better it is too, which an iframe edition would solve (loading the page exactly as it is loaded in non edit mode... but if you say there would be no JS in it maybe it's not what I think it is). We also wanted the iframe edition for the mobile edition to give an exact preview (the current mobile preview you made is cool but not entirely correct: it still does not have all the correct interaction and the same structure as there would be for a "normal" iframe rendering the page).

If the editor layout is 100% customizable and can be without edge, why was the idea abandoned? Maybe this would the easiest solution to quickly fix all of this: starting the edit mode without wrapping the wrapwrap element ~(or rename it wrappedwrapwrap at least :wink:)~.

**Comment by Gorash** [comment]
@qsm-odoo

> why was the idea abandoned?

Ask to @Goaman  ;)

**Comment by sebgeelen** [comment]
The layout will be adapted to be compatible with the current `getScrollingElement` capabilities.

@Goaman is on it

**Comment by Goaman** [comment]
Will be fixed with https://github.com/odoo/odoo/pull/61802

**Pull request closed without merging**
