### PR TITLE
Add i18n section to command line reference

### PR DESCRIPTION
**Pull request by antespi**
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bealdav** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@odony, can you please check this one?

**Comment by Yenthe666** [comment]
@mart-e this one has been open for quite a while and it is a nice little addition. Can you add it in?

**Comment by Yenthe666** [comment]
@mart-e I see you self assigned this quite a while ago and it is a nice addition to the docs. Can you find some time to handle this one please?

**Comment by mart-e** [comment]
@antespi @pedrobaeza finally merged ! a8dd1de5c466b64351d54536ac0529d2a744cf4d

**Comment by pedrobaeza** [comment]
Great, thanks!

**Pull request closed without merging**
