### PR TITLE
[FIX] point_of_sale: adapt logo for multi companies customer display

### PR DESCRIPTION
**Pull request by lade-odoo**
Customer display does not show the appropriate logo when multi-company is
enabled. The logo shown is always the logo of the default company.

Step to reproduce the issue:
1) Install Point of Sale and set up a second company
2) Put a logo on both companies (different ones)
3) Create a POS session on the newest company (not the default one)
4) In this session, activate Customer Display
5) Launch the session and open the Customer Display
The logo shown is the logo of the default company.

Solution: The issue is that when fetching the logo, we don't include
information about the current company. Thus, we include the logo of the default
company (at url /logo). We can easily specifiy which logo we need via the url
/logo?company={company_id}. As dynamic information cannot be included into a
CSS, we include this into the XML as it is done with other images rendered.
In our case, we don't need to retrieve the logo and map it to base 64 (for
ressources requiring to be logged in) because the logo is a resource available
to anyone.

opw-2745014

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

for stable we should probably keep the CSS, otherwise the logo will not be shown at all for people that do not do "-u point_of_sale".

CSS in style sheet is overridden by inline CSS so this should not cause an issue to keep it.

**Comment by lade-odoo** [comment]
@pimodoo Can you review this ? I saw from the commit history that you used to R+ some fixes. Thanks !

**Comment by lade-odoo** [comment]
@nle-odoo Can this PR be R+ or to whom can I ask for a R+, @pimodoo did not responded.

**Comment by trj-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
