### PR TITLE
[I18N] *: remove nl_BE files

### PR DESCRIPTION
**Pull request by mart-e**
They dates from < 2027 and are quite outdated. Favour the nl translation instead.
n_BE is not on Transifex so it was not possible to correct bad translations.

### CODE REVIEW

**Comment by mart-e** [comment]
robodoo r+

**Comment by Feyensv** [comment]
from < 2027 ? We all do :D

**Comment by Yenthe666** [comment]
> from < 2027 ? We all do :D

I noticed the same haha!
It is good that we finally bundle to `nl` itself though, less hassle.

**Comment by mart-e** [comment]
I live in the future ! Are you guys still using Odoo 19 or so ?

**Comment by Yenthe666** [comment]
> I live in the future ! Are you guys still using Odoo 19 or so ?

Sorry I'm still waiting for the upgrade scripts 😏 😂

**Pull request closed without merging**
