### PR TITLE
[FIX]web_editor: commitChanges

### PR DESCRIPTION
**Pull request by mgh-odoo**
Task:https://www.odoo.com/web#id=1950784&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720
Pad:https://pad.odoo.com/p/r.60b7430cf6fbf05a3551172fd4852e5b

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Zinston** [comment]
Seems good to me. Is it possible to add a test in `field_html_tests.js`? I believe this should probably be testable.

**Comment by mgh-odoo** [comment]
Hello @Zinston 
I have added an option to existing test-case to cover this case.
can you please have a look? Thanks!

**Comment by Zinston** [comment]
All good to me. @pparidans could you please merge?

**Comment by pparidans** [comment]
@robodoo r+

**Comment by pparidans** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
