### PR TITLE
[FIX] sale: Convert prince unit line down payment

### PR DESCRIPTION
**Pull request by ngochung207**
Setp:
1. Create SO with currency USD $100
2. Create invoice down payment 50%
3. At invoice change currency EUR 

Current: down payment so line price unit: 50

After commit: down payment so line price unit: 50 * rate(EUR/USD(

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
why would you change the currency on the invoice ?
I don't think we want to support that use case :thinking:

**Comment by ngochung207** [comment]
> why would you change the currency on the invoice ?
> I don't think we want to support that use case :thinking: 

If the system does not support this situation, then a warning is required. Do you agree?

**Comment by Feyensv** [comment]
We cannot raise warnings for every idea customers find to break their own database.
If we had 100 complaining customers, maybe, but since it's the first feedback about that in years, I don't believe a warning is necessary.

cc: @dalaOdoo

**Comment by ngochung207** [comment]
If you rate this unnecessary, you can close this pr, thanks

**Pull request closed without merging**
