### PR TITLE
[FIX] account: fix a failing test about digest

### PR DESCRIPTION
**Pull request by std-odoo**
Bug
===
The tagged had only `post_install`, so it wasn't run on the runbot.

In the meantime, the account team removed `user_type_id` and so the test is failing (and I could have been merged because of the tag).

### CODE REVIEW

**Comment by Xavier-Do** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
@robodoo r-

**Comment by Xavier-Do** [comment]
It looks like it is breaking in enterprise 

https://runbot.odoo.com/runbot/build/28234321

**Comment by std-odoo** [comment]
@Xavier-Do Oops sorry, it should be fine now

**Comment by Xavier-Do** [comment]
@robodoo r+

**Pull request closed without merging**
