### PR TITLE
[CLA] Update Vauxoo's CLA adding maneandrea

### PR DESCRIPTION
**Pull request by maneandrea**
Incorporate Andrea Manenti (maneandrea) as Vauxoo's contributor.

I confirm I have signed the CLA and read the PR guidelines at http://www.odoo.com/submit-pr

### CODE REVIEW

**Comment by maneandrea** [comment]
@luisg123v  @moylop260

**Review by luisg123v — COMMENTED** [review]
Please target 15.0, which is the oldest supported version. Once merged, it will be forward-ported automatically.

**Comment by maneandrea** [comment]
> Please target 15.0, which is the oldest supported version. Once merged, it will be forward-ported automatically.

I rebased from 15.0

**Review by luisg123v — COMMENTED** [review]
LGTM :+1: 

CC @mart-e

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by mart-e** [comment]
@luisg123v btw, if you want, you can just include the cla update in the first pr made by the new team member instead

**Comment by luisg123v** [comment]
@mart-e thanks for the suggestion, I'll keep it in mind. In this case, it wouldn't have been possible because the desired change is targeting a different version.

**Pull request closed without merging**
