### PR TITLE
[IMP] mail: Use correct name for Schedule Activity wizard

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: Mail module

Current behavior before PR:
screenshot

Desired behavior after PR is merged:

screenshot

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Already Improved in https://github.com/odoo/odoo/commit/0db0e66e96a8f6b393565da6fbb8dce25ec960b7

IMO still it should be changed to **Schedule an Activity** instead of  **Schedule Activity** (https://github.com/odoo/odoo/blob/master/addons/mail/static/src/js/activity.js#L221)

**Comment by Yenthe666** [comment]
The difference is minimal now though, we can live with "Schedule activity", no? It has no typo or wrong usage now

**Comment by sswapnesh** [comment]
Yes We can but Its better to keep it aligned with Older version (v12)
screenshot

Now It will Display **Schedule an Activity** (v12 too)
screenshot11

**Comment by mart-e** [comment]
As already done at 0db0e66e96a8f6b393565da6fbb8dce25ec960b7, I close this one. The remaining change is minimal (by the way, you got two `name` in the params after the rebase)

**Comment by sswapnesh** [comment]
Yes, I didn't updated PR as I was waiting for update on this.(Maybe you can Improve it now or May I propose PR for that chnage? If its going to be accepted)

**Comment by mart-e** [comment]
"Schedule Activity" is fine IMHO, don't you think?

**Comment by sswapnesh** [comment]
Its Fine but Idea was to make it Align with other place.

**Pull request closed without merging**
