### PR TITLE
[FIX] point_of_sale: Remove wrong decorator

### PR DESCRIPTION
**Pull request by sswapnesh**
Follow-up on 118190f

Remove the wrong decorator from the write method.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
@pimodoo  This is a Manual Backport of https://github.com/odoo/odoo/pull/45878 and seems as `FIX` if called over RPC.

**Comment by pimodoo** [comment]
@sswapnesh Why did you backport it? @mart-e said in previous PR that it was not really a fix. What bug are you fixing?

**Comment by sswapnesh** [comment]
> What bug are you fixing?

Without this fix you cannot call this method over RPC

**Comment by sswapnesh** [comment]
@pimodoo

**Comment by sswapnesh** [comment]
> @sswapnesh Why did you backport it? @mart-e said in previous PR that it was not really a fix. What bug are you fixing?


Without this patch, call write over RPC

Screenshot from 2020-03-25 22-46-38

It will fail due to this

```
  File "/home/sswapnesh/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
TypeError: write() takes 2 positional arguments but 3 were given
```

**Comment by pimodoo** [comment]
you are not supposed to call write on pos order through rpc, as everything pass through create from ui.

**Comment by sswapnesh** [comment]
But what's the point to block it by using wrong decorator.
Atleast allow people to use it on their own.
Cc @mart-e @odony

**Pull request closed without merging**
