### PR TITLE
[FIX] web: add twitter X font-awesome icon

### PR DESCRIPTION
**Pull request by IT-Ideas**
Prior to this commit the new twitter X icon is not available. This commit adds the icon under the `fa-x-twitter` class.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by IT-Ideas** [comment]
Hello @ged-odoo could you have a look at this PR?
Something similar has been done in the past for tiktok.
I know that odoo is no more supporting 14.0 but this is really a little thing.

By the way, an override of `export_icon_to_png` should be done in order for mass mailing to work with it. But I am limiting this PR tu just add the fontaweson icon.
```suggestion
    @http.route([
        '/web_editor/font_to_img/<icon>',
        '/web_editor/font_to_img/<icon>/<color>',
        '/web_editor/font_to_img/<icon>/<color>/<int:size>',
        '/web_editor/font_to_img/<icon>/<color>/<int:size>/<int:alpha>',
        ], type='http', auth="none")
    def export_icon_to_png(self, icon, color='#000', size=100, alpha=255, font='/web/static/lib/fontawesome/fonts/fontawesome-webfont.ttf'):
        if icon.isdigit():
            if int(icon) == 57467:
                font = "/web/static/src/fonts/tiktok_only.woff"
            elif int(icon) == 58907:
                font = "/web/static/src/fonts/twitter_x_only.woff"
        return super().export_icon_to_png(icon, color, size, alpha, font)

```

@tde-banana-odoo maybe this is also interesting for you... Bisous!

Hope you are well!

LTU 😉

**Comment by IT-Ideas** [comment]
Hey @rdeodoo 😁

**Review by rdeodoo — COMMENTED** [review]
Do you really need that in Odoo 14?
It would be better to target Odoo 15 but for this kind of change, why not..

> By the way, an override of export_icon_to_png should be done in order for mass mailing to work with it. But I am limiting this PR to just add the fontaweson icon.

Indeed :grimacing: 
Do you want to (quickly) provide a fix for that? Otherwise I'll create a task so we can fix that

**Comment by IT-Ideas** [comment]
Well the fix is in our repo for our customer but I thought this would be interesting for others.

I can take care of the fix for mass_mailing. I aleeady did it in our repo.

Hope all goes well for you! Say hi to the teams 😉

**Comment by IT-Ideas** [comment]
Here it is @rdeodoo!

**Comment by rdeodoo** [comment]
> Hope all goes well for you! Say hi to the teams 😉

Everything's fine I believe for me and the team :)

About the `fa-x-twitter`, I believe I'll merge the PR mentioned by GDI which will directly replaced all `fa-twitter` by the new icon.
It's not exactly fitting the stable policy but at the same time, it's really a corner case where a brand changed its logo. So it kind of is stable compliant at the same time: it's weird to force user to still show old icon on their website visitors.
Forcing them to upgrade to 17 or 18 for new icons is not a possibility, and adding a new `fa-x-twitter` is not ideal as they would need to patch all the views & js code etc to use the new icon.

I was really hesitating a lot to merge it in odoo 15 but SRI remark here https://github.com/odoo/enterprise/pull/53644#issuecomment-1973164756 is on point, the icon used in the backend in old versions is not really a problem, backend users will manage, but for visitors, it's really important to show them the new icon and not have our users stuck with an outdated frontend.

I guess I will merge those 2 PRs from our R&D and then your fix about the  `export_icon_to_png`

**Comment by IT-Ideas** [comment]
> I guess I will merge those 2 PRs from our R&D and then your fix about the `export_icon_to_png`

Ok thanks 🙂.

I don't know why but I chose the direction where people would not have their twitter logo automatically changed... You might be right doing the opposite though.

May I just ask you to also take the cla part 👼🏼 ?

Thanks and all the best!

**Comment by rdeodoo** [comment]
Moved the font_to_img fix to https://github.com/odoo/odoo/pull/157919
The new twitter icon will be done at https://github.com/odoo/odoo/pull/148126

>  You might be right doing the opposite though.

Hopefully.. It's really hard to decide, but after all Twitter rebranded, regardless if people like it or not, we will change the icon in stable (not the name to not break translation)

**Comment by IT-Ideas** [comment]
> Moved the font_to_img fix to https://github.com/odoo/odoo/pull/157919
> 
> The new twitter icon will be done at https://github.com/odoo/odoo/pull/148126
> 
> 
> 
> >  You might be right doing the opposite though.
> 
> 
> 
> Hopefully.. It's really hard to decide, but after all Twitter rebranded, regardless if people like it or not, we will change the icon in stable (not the name to not break translation)
> 
> 

Ok thanks a lot! I'll try to say hello at the farm soon.
Take care!

**Pull request closed without merging**
