### PR TITLE
[FIX] account_edi_ubl_cii,*: rouding issue in the tax in case of EPD

### PR DESCRIPTION
**Pull request by clbr-odoo**
*: l10n_account_edi_ubl_cii_tests

Fix rounding issue with the early payment discount. I used the client's setup in the test to replicate the exact problem.

opw-4245127

### CODE REVIEW

**Review by smetl — APPROVED** [review]
@robodoo r+

**Comment by clbr-odoo** [comment]
@robodoo r-

**Comment by smetl** [comment]
@robodoo r+

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
