### PR TITLE
[13.0 stock_account] FIX: access for read on stock.valuation.layer

### PR DESCRIPTION
**Pull request by celm1990**
**Description of the issue/feature this PR addresses:**

Create 1 user only with Groups: purchase user, inventory user, sale user

image

Create 1 product with Internal category as Valuation automatic and Cost method AVG

image

Create a purchase order and receive product

Create a Sale order with new product and confirm

To Validate picking get following error
image

**Current behavior before PR:**

**Desired behavior after PR is merged:**

@sle-odoo can you help me with this PR please??

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Whenrow** [comment]
Hello, We don't want to give access to stock valuation layer. to keep them only accessible through code. You should maybe add a sudo when calling _action_done somewhere

**Comment by pedrobaeza** [comment]
@celm1990 is that permission error reproducible on runbot without extra third-party/custom code?

**Comment by celm1990** [comment]
> @celm1990 is that permission error reproducible on runbot without extra third-party/custom code?

@pedrobaeza check URL, I tested on runbot

**Comment by celm1990** [comment]
> Hello, We don't want to give access to stock valuation layer. to keep them only accessible through code. You should maybe add a sudo when calling _action_done somewhere

Your commit https://github.com/odoo/odoo/commit/ad5ac19218b4c529c651da951acdb93e1ac1227d was only for 14, can backport to V13??

**Comment by celm1990** [comment]
solved  for V13 into commit https://github.com/odoo/odoo/commit/b0c5bd414ff8f23e3437cbbbe2a1307343a9764f#diff-ad6229e976ce0bd1592e805b88e9813ac4e3f6fb989d3dfb8dfb8b70af03cd58

**Pull request closed without merging**
