### PR TITLE
[FIX] delivery: delivery price uses pricelist currency

### PR DESCRIPTION
**Pull request by nim-odoo**
opw: 632574

### CODE REVIEW

**Comment by beledouxdenis** [comment]
The currency model has a `compute` method that you should probably use, as just multiplying the amount by the currency rate is not enough, you need to round the result by the currency decimal precision, and the `compute` method of `res.currency` does that for you. 

Besides, there is also a concept of dates, you can have several rates for a same currency for different dates, and you should therefore probably pass the order date to the `compute ` method, so it returns he amount according to the rates at a specific date.

**Comment by nim-odoo** [comment]
OK, updated. According to the date, I'm not 100 % sure if it is relevant. Several cases could be considered:
- today's date (which is the default)
- order date (what I chose)
- confirm date, but then, more global question: should we recalculate the complete order according to the applicable rate when we confirm? --> out of scope, IMHO

On the other hand, get_price takes the date as argument, but doesn't use it...

**Comment by beledouxdenis** [comment]
To me, it's the order date that matters, since you can create sale order with a date in the past (maybe you sold something and write the transaction on a napkin, and then the customer ask you to make a cleaner sale order, afterwards), and, in such a case, the currency rates to apply are the currency rates at that date in the past.

Regarding your patch, just a little remark for performances:
You are making a `browse` call while you already have it:
`currency_pricelist = currency_obj.browse(cr, uid, order.pricelist_id.currency_id.id)`
to
`currency_pricelist = order.pricelist_id.currency_id`

**Comment by nim-odoo** [comment]
Indeed, silly mistake. I also made the diff slightly shorter

**Comment by beledouxdenis** [comment]
Fine for me, except that your editor removed the last line of the file :p. Just revert this change and then it's fine :+1:

**Pull request merged**
