### PR TITLE
[FIX] In some cases, the half hours are not considered in intervals computation

### PR DESCRIPTION
**Pull request by adrienpeiffer**
This one seems to fix #10929

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
OPW 669569

**Comment by adrienpeiffer** [comment]
@mart-e it's done (and green now :smile: )

**Comment by simongoffin** [comment]
Closed with 5e940643a51a617b80845a7b6e17475348a32db1 and https://github.com/odoo/odoo/commit/b21773456c973c9dce8e2bae50892ff2059b684f

**Comment by simongoffin** [comment]
Thanks @adrienpeiffer

**Pull request closed without merging**
