### PR TITLE
[IMP] hr_expense: Team approver should not have full access to journal

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
Currently Team Expense Approver have full access to journal, we shouldn't do that

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Hi @lordkrandel Could you please take a look ?

**Comment by lordkrandel** [comment]
@JulienAlardot Thx ^^'

**Review by JulienAlardot — APPROVED** [review]
@jbw-odoo LGTM
Thanks for that fix :)

**Comment by duong77476-viindoo** [comment]
Hi @jbw-odoo please merge for forward chain to avoid spamming

**Pull request closed without merging**
