### PR TITLE
add new 16% rate and correct the '%' character in previous xml file

### PR DESCRIPTION
**Pull request by jlzhou**
Description of the issue/feature this PR addresses:
The China government announced new tax rate 16%.
Current behavior before PR:
No 16% rate ready.
Desired behavior after PR is merged:
Add 16% rate.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by GoodERPJeff** [comment]
I act as l10n_cn maintainer, Fully support this PR from Mr Zhou,
The change in china will start from next month, please do merge it as soon as possible.

**Comment by sum1201** [comment]
@Yenthe666 From May 1, the General Administration of Taxation adjusts the tax rate.

**Comment by sum1201** [comment]
@Yenthe666 http://www.chinatax.gov.cn/n810341/n810755/c3377945/content.html

**Comment by keecome** [comment]
@Yenthe666 From May 1, the General Administration of Taxation adjusts the tax rate.

**Comment by mart-e** [comment]
Thanks for the proposal and thank you @GoodERPJeff and @jeffery9 for the review !

**Comment by KangOl** [comment]
I ignored this change during forward-port to saas~11.2.
Can you adapt your patch to this version?

/cc @qdp-odoo

**Comment by leangjia** [comment]
香烟瓜子矿泉水

**Pull request merged**
