### PR TITLE
[IMP] web: align and resize html/field tags in form view

### PR DESCRIPTION
**Pull request by omra-odoo**
Current Behaviour:
- In some modules (subscriptions, rental, etc.), the HTML and field tags in the form view are misaligned and improperly sized, with no space between them.

Expected Behaviour:
- Ensure proper alignment and sizing of HTML and field tags in the form view, with appropriate spacing between them.

task-3903783

Related enterprise PR : https://github.com/odoo/enterprise/pull/68435

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Polymorphe57** [comment]
@omra-odoo don't forget CTH/AAB's remarks in the task conversation

**Comment by omra-odoo** [comment]
Hello @Polymorphe57  I have addressed the remarks from aab/cth in the related enterprise PR. i have make the some tags are no longer nested in the `<button/>` can you please verify  the changes?

Thank you.

**Comment by Polymorphe57** [comment]
> Hello @Polymorphe57 I have addressed the remarks from aab/cth in the related enterprise PR. i have make the some tags are no longer nested in the `<button/>` can you please verify the changes?
> 
> Thank you.

Have you done that in another PR? I don't see anything here.

**Comment by Polymorphe57** [comment]
If Aaron is right, there is no need to modify the scss files

**Comment by omra-odoo** [comment]
yes i have done it in enterprise, here is the [PR](https://github.com/odoo/enterprise/pull/68435).
we need to modify scss file, because which tags are mis-aligned or mis-sized that is not nested in the `<button/>`. you can see here 
image
these tags are not nested in the `<button/>` so we need to fix their style.

**Comment by aab-odoo** [comment]
Hello @omra-odoo

I think we should standardize the style of badges in the webclient. It doesn't make sense to have custom style for the badge field only. Here's what I suggest: odoo/odoo@7d6c5bca8ab5d542cf0daa4586e36036a36dc98d

You'll also need to remove fs-6 classname on the usecases: odoo/enterprise@15af9238a0737eae920ee947827259a547c40533

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Comment by mano-odoo** [comment]
Hello @aab-odoo @omra-odoo this seems to have introduced a weird visual result (bg-300) in the settings badges. 

image

**Comment by mano-odoo** [comment]
@aab-odoo 

Bootstrap's default behavior would be to not set a background color with the `badge` class
and rather set it with a contextual `bg-x` class used in association, thus having a transparent badge if no bg utility are associated. 

It's not bad per say to define a bg-color on the `badge` because most of the badges in our codebase do use a background-color utility class, thus overriding it anyway. 

It's going against bootstrap default but this is another approach, yet if we do so, we have to adapt the badges impacted by this new rule. Eg. the ones in the settings should then have a `bg-transparent` to override the default background value and keep their initial desired styling. Since we are now setting this value on the generic `badge` selector we should probably check all the impacted badges.

**Comment by aab-odoo** [comment]
@mano-odoo I was suggesting to remove the default color, in webclient.scss.

**Comment by mano-odoo** [comment]
> @mano-odoo I was suggesting to remove the default color, in webclient.scss.

IMO it's the solution yes. Mind that we should probably re-apply the bg-color on the `.o_field_badge span` (or apply a background color on the existing badges that were previously relying on this styling)

**Pull request closed without merging**
