### PR TITLE
[FIX]web: Fixed the issue of widget=selection does not work in editable list view

### PR DESCRIPTION
**Pull request by msh-odoo**
Task ID:https://www.odoo.com/web?#id=1871698&action=327&model=project.task&view_type=form&menu_id=4720
Pad: https://pad.odoo.com/p/r.e9a827ef3eb6c5997c6fe672f7181417

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this going to be finished?

**Comment by sswapnesh** [comment]
Fixes https://github.com/odoo/odoo/issues/21547
Cc @mge-odoo

**Comment by msh-odoo** [comment]
After discussion with @aab-odoo it is not easy to solve it 11.0 as it requires a lot of changes to make it work properly, for workaround use m2o with no_create_edit, no_quick_creation, no_open option

**Comment by pedrobaeza** [comment]
OK, is this working in latter versions?

**Comment by sswapnesh** [comment]
> OK, is this working in latter versions?

Seems this one https://github.com/odoo/odoo/pull/33485

**Comment by sswapnesh** [comment]
@msh-odoo  Workarounds are also not working as expected
Eg, https://github.com/odoo/odoo/pull/33156

**Pull request closed without merging**
