### PR TITLE
[IMP] doc: add t-name t-extend to QWeb JS

### PR DESCRIPTION
**Pull request by seb-odoo**
task-2040835

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
@qsm-odoo doc update for t-name t-extend as discussed weeks ago

**Comment by qsm-odoo** [comment]
Cool, but won't you target 11.0 at least ? ;)

**Comment by seb-odoo** [comment]
I don't know when it was introduced, but if you are sure it was working already in v11 then ok to change the target of the PR.

**Comment by seb-odoo** [comment]
Changed target to 11.

_Sorry to all of you who are now subscribed to this PR..._

**Comment by qsm-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
