### PR TITLE
Master account edi helpers bfr

### PR DESCRIPTION
**Pull request by bfr-o**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
Typo in first commit: retreive*
Add account_edi_facturx in second commit title

**Comment by bfr-o** [comment]
I think you meant add account_edi_ubl in second commit title.
I also mentioned all the edited modules in the second commit title (+fixed the typo).

**Comment by smetl** [comment]
@robodoo r+

**Comment by bfr-o** [comment]
@robodoo rebase-ff

**Comment by oco-odoo** [comment]
@robodoo rebase-ff

**Comment by bfr-o** [comment]
@robodoo retry

**Comment by bfr-o** [comment]
@robodoo retry

**Comment by bfr-o** [comment]
@robodoo retry

**Comment by smetl** [comment]
@robodoo r+

**Review by smetl — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
