### PR TITLE
[FIX] l10_fr_fec : init line with zero balance should be not include

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
Before this PR initial balance include line with a null balance. In database with lot of partner (e-commerce), the initial balance balance are huge.

- Create e-commerce
- Sale and invoice to 100 000 different customer in 2023, all invoice are paid
- In 2024 extract a FEC
--> Issue : in the initial balance there are 100 000 lines with a zero balance. This lines don't need to be included in the FEC.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
ping @alexis-via @oco-odoo

**Comment by fmdl** [comment]
ping @oco-odoo

**Comment by fmdl** [comment]
#OPW #3757175

**Comment by dbkosky** [comment]
@fmdl  Thanks for the contribution, and apologies for my delay in looking at it.

I wanted to ask you about your description of the issue.

When you say "initial balance include line with a null balance", do you know where these lines originate / are there many of them? Is it something like differences from exchange rates?

Also, please could you ensure that your branch passes the tests / builds successfully. You can get the branch to build again by rebasing and pushing.

Thanks :)

**Comment by fmdl** [comment]
Hi @dbkosky,
The issue is not come from exchange rates.

- Create e-commerce
- Sale and invoice to 100 000 different customer in 2023, all invoice are paid
- In 2024 extract a FEC
--> Issue : in the initial balance there are 100 000 lines with a zero balance. This lines don't need to be included in the FEC.

it is more clear ?

**Comment by dbkosky** [comment]
Hi @fmdl 

It is more clear, I just want to make sure I understand.

The problem is something like:
- The FEC report contains initial balances. These representing balances on accounts from the previous period.
-  When calculating the initial balances, there is no requirement to include balances from the previous period for an account if they are at zero. 
- Right now, these zero valued initial balances are included.

On top of this: 
- balances from the previous period on payable/receivable accounts are split by partner
- when there are settled transactions for many thousands of partners from the previous period, this results in many thousands of initial balance lines in the FEC report that all have a balance of zero

Is this correct?

**Comment by fmdl** [comment]
Yes it is correct (except `balances from the previous period on payable/receivable accounts are split by partner`, it is normal)

**Review by dbkosky — COMMENTED** [review]
Alright, then your changes make good sense :+1: 

Considering the discussion we've had, please can you update the commit message to be more descriptive. Thanks!

**Review by dbkosky — APPROVED** [review]
This is good by me, thanks!
 I'm forwarding it to a colleague who can merge it.

**Review by FlorianGilbert — COMMENTED** [review]
Hello

Sorry for my late review, I forgot it.
I just want to make sure, the commit message is the good one? The one in the pull request is not included in the commit message :sweat_smile: 
Thank you :)

**Comment by fmdl** [comment]
Can you give me the good commit message (we will win time), thanks.

**Comment by FlorianGilbert** [comment]
> Can you give me the good commit message (we will win time), thanks.

To be honest, I'm just trying to understand :sweat_smile: 

Your commit title says: 
> [...] init line with zero balance are include

But a the end of your commit, we say that:
> [...]
> This PR remove initial line with zero balance.

I'm not sure to understand, I understand what you're doing but I have the feeling that the commit message isn't clear enough.

Could you please explain in few words why we don't want to import them (in the commit message) and make sure that the title is consistent with the commit message?
If I am wrong, I'm sorry, feel free to explain me :sweat_smile:

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
