### PR TITLE
[FIX] l10n_es: fix tags on IVA 0%

### PR DESCRIPTION
**Pull request by guva-odoo**
Some tags were not correct on taxes
IVA 0%.

### CODE REVIEW

**Comment by guva-odoo** [comment]
@chklop

**Comment by chklop** [comment]
Yep, this is fixing this (it's better for a 0% tax to appear in the ... 0% section) 
image

**Review by oco-odoo — APPROVED** [review]
@robodoo r+

**Comment by oco-odoo** [comment]
> Oooooops ! @robodoo r-
> 
> Actually, we should inscrease the module's version number and use clbr's script to convert existing taxes when they upgrade the module :)

P

**Pull request closed without merging**
