### PR TITLE
[FIX] sale_management: Pricelist singleton error while choosing optio…

### PR DESCRIPTION
**Pull request by hubvd**
…nal product

Cherry picked a commit b6ced2e13e328539b086067a836d1e0fba3990b7 that was only applied starting from 13.0

opw-2517635

### CODE REVIEW

**Comment by kitan191** [comment]
@fw-bot up to saas-12.3

**Review by Feyensv — COMMENTED** [review]
CLA is red, your github account/git config is wrongly configured :eyes:.
Also, please do not place a # before the commit ref, github doesn't recognize it and it's not clickable then.

About the changes, it can indeed be backported :+1:

**Comment by Feyensv** [comment]
Please remove the [PATCH] part of your commit title (it doesn't add anything, and should follow the [guidelines](https://www.odoo.com/documentation/14.0/developer/misc/other/guidelines.html#commit-message-structure) )

Also, keep the commit message simple. "Backport of #commit ref" should be enough to imply the rest of the sentence ;).
The commit message should explain the issue when needed, but in this case, the title is enough so it can be kept short & clean :).

**Comment by hubvd** [comment]
@Feyensv I fixed the commit title and message. Is it ok to merge now ?

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
