### PR TITLE
[REF] tests: delete duplicated arg for headless browser

### PR DESCRIPTION
**Pull request by yelizariev**
It was added here: https://github.com/odoo/odoo/commit/253d5341a4e2d19d2cb9bad6bb1b1986f52dd66f

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
@d-fence

**Comment by d-fence** [comment]
Nice catch but it would be better to target the 13.0 branch as the duplicated switch is already there.

**Comment by yelizariev** [comment]
Yes, but doesn't fix anything

**Comment by yelizariev** [comment]
@d-fence :wink:

**Comment by d-fence** [comment]
Was fixed in c9c7198b537b3b6426c791b5f9581e4fdcc88ea8

**Pull request closed without merging**
