### PR TITLE
[IMP] account_fr_fec: fix SQL Memory error when FEC too big

### PR DESCRIPTION
**Pull request by jbw-odoo**
Set fec_data to attachment True to avoid storing data ion DB

Task: 2453453

### CODE REVIEW

**Review by william-andre — CHANGES_REQUESTED** [review]
This is changing the database schema in stable

**Comment by jbw-odoo** [comment]
> This is changing the database schema in stable

On a transient model. Not possible ?

**Comment by qdp-odoo** [comment]
transient are stored in DB as well, so yeah... not possible

**Comment by jbw-odoo** [comment]
> transient are stored in DB as well, so yeah... not possible

Ok, but this field is referenced nowhere but one time at it's generation in the wizard. I don't understand what problem this may cause.

**Comment by Yenthe666** [comment]
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean 🤷

**Comment by william-andre** [comment]
The fact that it is not used in the standard code doesn't mean that it is not used in any customization.

However, this should not break anything. The only difference in the db is that we don't use the column `fec_data` on the table `account_fr_fec` anymore. Since we are in a transient model, we don't care about the data currently in the table either.
The only minor issue is that wizards open before and closed after the server restart will crash, but I don't think that it is an issue. Users will just have to close it and fill the 4 files again if that happens.

So we will just have a useless, empty column. Not that big of a deal IMO.
If we add a migration script for next freeze (as of today 15.2), it shouldn't be a big issue to merge this.

See:
https://github.com/odoo/odoo/pull/65170
https://github.com/odoo/odoo/pull/65671
CC: @qdp-odoo @jco-odoo @oco-odoo @jbw-odoo

**Comment by oco-odoo** [comment]
> The fact that it is not used in the standard code doesn't mean that it is not used in any customization.
> 
> However, this should not break anything. The only difference in the db is that we don't use the column `fec_data` on the table `account_fr_fec` anymore. Since we are in a transient model, we don't care about the data currently in the table either. The only minor issue is that wizards open before and closed after the server restart will crash, but I don't think that it is an issue. Users will just have to close it and fill the 4 files again if that happens.
> 
> So we will just have a useless, empty column. Not that big of a deal IMO. If we add a migration script for next freeze (as of today 15.2), it shouldn't be a big issue to merge this.
> 
> See: #65170 #65671 CC: @qdp-odoo @jco-odoo @oco-odoo @jbw-odoo

Indeed, you're right. I thought it'd change the DB scheme in some way, but it wouldn't make sense; the attachment table stores everything. 

To me, we can do this change. The only difference with the previous behavior will be the content of the table, where, indeed, the fec_data column will be empty. But I guess it's ok to assume that nobody is relying on sql queries to manipulate data from transient models. 

@qdp-odoo Do we agree?

**Comment by william-andre** [comment]
@robodoo r+

**Pull request closed without merging**
