### PR TITLE
[FIX] mail: catchall bounced could contain b64 quoted address

### PR DESCRIPTION
**Pull request by Julien00859**
Setup a catchall address in Odoo, send an email to that address but
change the recipient so the name contains non-ascii character (i.e To:
"Joé" <catchall@example.com>). The email bounces but the response body
contains the unfriendly b64-ed email address.

opw-2222791

### CODE REVIEW

**Comment by Julien00859** [comment]
@fw-bot up to 13.0

**Comment by Julien00859** [comment]
Hello @odony tde's opinion is we should only fix master and don't bother with v12/v13, he said he would be ok to merge this one only if you are ok too.

The problem here is when people send a message directly to the catchall address, there is a chance the bounced email contains ugly looking base64 in place of the email recipient in the email body.

**Comment by Julien00859** [comment]
@tde-banana-odoo @odony I have a customer waiting

**Comment by Julien00859** [comment]
Avec le recul, ceux qui mettent de l'unicode dans leur adresse catchall cherchent juste des problèmes...

**Comment by tde-banana-odoo** [comment]
:open_mouth:

**Pull request closed without merging**
