### PR TITLE
[IMP] custom title in error modal

### PR DESCRIPTION
**Pull request by Julien00859**
[IMP] base, web: custom title in error modal

In a ancient age were the sole exception were `except_osv` and
`except_orm`, every exception needed two arguments, an error title and
an error message. With the introduction of dedicated exceptions in  only
the error message remained as the title was given by the exception type.

It turns out most of the time the generic `UserError` exception is
raised for missuses that don't fall in any other category and that the
error modal the user see is entitled "Something went wrong" which is too
much generic and unnecessary scary.

We introduced a way to customize the modal title by providing a `title`
argument when raising a odoo custom exception.

--

[FIX] crash_manager: use given title on modal

Via the browser, try to access a resource you don't have access to, an
Access Error modal is open but the title was saying "Something went
wrong" instead of "Access error".

--

Task: 2206851

### CODE REVIEW

**Comment by Feyensv** [comment]
Conflicting files :D

**Comment by Julien00859** [comment]
The conflict is minimal and wouldn't affect your review, would you mind review it as-it ? I'm taking care of the conflict in a few minutes...

**Review by Feyensv — COMMENTED** [review]
I tried to reproduce the problem solved by your first commit but everything works fine on master runbot now :thinking: 
image

We don't get the "Something went wrong" but a clean Access Error title.  I think your fix is probably still useful, but only to ensure that the error title is translated, not to ensure that "Somethiing went wrong" isn't shown anymore for an AccessError.

**Comment by Feyensv** [comment]
Regarding the "new" feature, it seems to work fine :+1:.

**Pull request closed without merging**
