### PR TITLE
[FIX] point_of_sale: reduce memory when loading products and partners

### PR DESCRIPTION
**Pull request by jorenvo**
The search_read ends up using large amounts of memory if the amount of
records you're loading is large enough. In one observed case ~70,000
products end up using around ~2 GB of resident memory.

It is partly due to some optimistic prefetching of certain fields, but
even if that was fixed you would still run into this same issue with
more records.

A better, scalable solution is to load models that we know may have a
lot of records in batches. This implements this by adding a new option
`load_in_batches` to the POS model loader. It will keep loading
batches of 10,000 records until all records have been loaded and it
loads an empty batch.

10,000 was chosen as a batch size because it's large enough to not
have to do too many calls and small enough to minimize the risk of
exceeding the default memory limits. In this case loading products in
batches of 10,000 ends up using only ~400 MB of resident memory.

opw-1913872

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by nim-odoo — APPROVED** [review]
Very nice, moreover the approach of sorting by id makes the diff pretty small. It looks clean and safe.

About merging it though, I'm not sure this is the best time of the year. We'll have many people on holidays as of next week, and Xmas - New Year is the busiest period for retail. That would be a shame is any issue would arise in the coming days after an update. Although it is thoroughly tested, better be safe than sorry. Therefore I would wait until beginning 2019.

EDIT: by the way, a nice extension would be to use a parallel approach, depending on the quantity of workers available. On the other hand, the sequential approach is simpler to configure: 1 POS client to load = 1 worker needed. If one needs to load several clients at the same time... things starts to be tricky. Anyway, that would be for `master`.

**Comment by jorenvo** [comment]
Thanks for the review. I agree with waiting to merge it. I'll do it somewhere the second week of January.

**Comment by jorenvo** [comment]
I noticed two issues with the previous approach:

- `loaded` is called multiple times, one time for each batch. I don't think this is a huge issue.
- models loaded in batch were always sorted on `id`. This is a huge issue because apparently it messes up the product and partner order in the POS interface.

The new commit solves both issues by only calling `loaded` once after all batches are loaded. Right before it does that it sorts client-side. It's not as simple as the previous commit, but I don't think there's a way around it.

**Review by nim-odoo — COMMENTED** [review]
That's indeed more complex than the first solution. At the moment, you rely on an empty result to detect the end of the loop, which indeed breaks the result order. Don't you think it would be possible to perform a `search_count` beforehand, so you would know the number of `search` calls that need to be done? This way, you wouldn't have to re-sort everything.

**Comment by nseinlet** [comment]
This commit : https://github.com/odoo/odoo/commit/189cc4405cbf4a745989dec6c0b2c41d07e42789 address the same issue (memory consumption) by tuning the ORM. Backporting this should solve the issue and avoid this complex commit, no?

**Comment by nim-odoo** [comment]
@nseinlet From a scalability point of view, this commit still makes sense. It might be needed to test 189cc4405cbf4a745989dec6c0b2c41d07e42789 on the given DB to estimate the real memory gain. From the tests mentioned the gain is from a factor 2 to 7. This is of course a non-negligible improvement, but we might still hit the limit quite easily.

The idea of being able to split the data loading in several requests adds scalability to the POS. So even if it is not necessary anymore in the problematic use case reported, I'm convinced it can still be useful. However, 189cc4405cbf4a745989dec6c0b2c41d07e42789 could be backported, and this PR could target master instead.

cc @switch87

**Comment by jorenvo** [comment]
This particular customer is in v12. So backporting is not necessary in this case.

I retested with the latest code and resident memory now stays at around ~300 MB without my patch. Although loading product.product is quite a bit slower now (from 1.5 minutes to load 70k products at ea301bef933b06995696a50c8f25aa022736321c to 13 minutes at d0d8b7b4de78aa2c38c91257af2a07caf1107d1c).

Because of this I think we should drop this or perhaps retarget master instead. The only advantage of this PR I see right now is that the search_read's of the POS will be much less unusual from the rest Odoo which could reduce future issues.

> Don't you think it would be possible to perform a search_count beforehand, so you would know the number of search calls that need to be done?

Until 30 seconds ago I didn't know how to achieve that. But out of some dark corner of my brain I just remembered the `offset` parameter for `search_read`. We can use that to start a batch at the correct position. I agree it's better. It would result in simpler code because we can avoid sorting client-side like you mention. If we continue with this PR I'll update it to do this.

**Comment by jorenvo** [comment]
Ok, I'll retarget master and use `offset`.

> Could you determine the commit that causes this? 

Sure!

It's due to a07a076c45f. Here are my results before reverting (I did the same benchmark twice each time to be certain):

run 1: 12m30.423s
run 2: 12m51.522s

After reverting a07a076c45f:

run 1: 1m4.474s
run 2: 0m59.500s

Memory usage remains ok after the revert. The tests were done in v12 by piping the following into the Odoo shell:

```python
self.env['product.product'].search_read(domain=[['sale_ok', '=', True], ['available_in_pos', '=', True]], fields=['display_name', 'list_price', 'lst_price', 'standard_price', 'categ_id', 'pos_categ_id', 'taxes_id', 'barcode', 'default_code', 'to_weight', 'uom_id', 'description_sale', 'description', 'product_tmpl_id', 'tracking'], order='sequence ASC, default_code ASC, name ASC')
```

This is the RPC call the POS does when loading products.

The tests were done on the db of opw-1913872.

Perhaps @rco-odoo could take a look. We briefly got to a point where the POS could load massive amounts of products with little issue (>100k in <2 minutes), but this performance regression undoes that a bit (although it's still much better than it was ~1 year ago of course).

**Comment by nim-odoo** [comment]
OK, thanks, we'll check

**Comment by nim-odoo** [comment]
Seems fixing the problem: https://github.com/odoo/odoo/pull/30133
Still testing

**Comment by pedrobaeza** [comment]
This got stuck... Is this still needed in v13/master? Should this be closed?

**Comment by jorenvo** [comment]
I never got around to porting this to master. Since there is no urgent need for it I'll close it for now.

**Comment by pedrobaeza** [comment]
Thanks for the follow up

**Pull request closed without merging**
