### PR TITLE
[FIX] l10n_it_edi: autodetect TipoDocumento

### PR DESCRIPTION
**Pull request by agr-odoo**
Create an invoice
Add on a line a Service product
Confirm & Send Invoice
Check Electronic Invoice tab (or generated xml)

Issue: Field 'TipoDocumento' will be TD03 ('advance/down payment on fee') while
it should be TD06 ('fee')
This occurs because after https://github.com/odoo/odoo/commit/8e8923b5656622e4c5ad13d129aacd91e5662849 the system will
recognize every invoice where sum(service lines) > sum(goods/consu lines)
as downpayment

opw-4175871
opw-4184646
opw-4203547

### CODE REVIEW

**Comment by agr-odoo** [comment]
@epictete

**Review by malb-odoo — COMMENTED** [review]
Thanks for the fix ! 
Technically speaking it LGTM, but i want to make sure it's also the case functionally. I have sent a message to have the confirmation on that matter :smile:

**Comment by malb-odoo** [comment]
Just received a response. For the use case where it's not a downpayment and we have just a service product it should be a TD01 and not a TD03 or TD06 :thinking:. From what i read on the ticket, that what the people are saying ? 
image
image

Maybe when we have made the fix you can contact Matthieu Weyemberg (mwe) to test the solution, he can also help to know which document is what :smile:

**Comment by malb-odoo** [comment]
Additional information given by brb ==> 
TD01 = Normal invoice
TD04 = Credti note for normal invoice
TD06 = It is only for professional fees to self employed customer, like lawyers, doctors ecc.. 
TO03 = Credit notes for professional fees
here documentation that explain all those https://www.agenziaentrate.gov.it/portale/documents/20143/451259/Guida_compilazione-FE-Esterometro-V1.8.pdf/c0aca469-4c4a-9b8d-048c-398412435c26

**Comment by agr-odoo** [comment]
@malb-odoo 
Thanks for the info, as you noted TD01 is a normal generic invoice, while TD06 seems to be intended for professionals invoicing a service, so we could add another feature in the mapping to detect if the current company is individual, in order to correctly assign TD03 (downpayment)/TD06

**Comment by epictete** [comment]
Indeed, I think this issue requires a deeper functional analysis/rework that goes beyond the scope of a bugfix.
I also think it will deserve a round a testing by our PO and/or BA.
So I would recommend having a dedicated task in our pipe for that :nerd_face:

**Comment by agr-odoo** [comment]
Fixed in https://github.com/odoo/odoo/commit/2f2f5f63e8d0ab9729bffa25192a7ef9a2da5fb9

**Pull request closed without merging**
