### PR TITLE
Introducing a throttle for animation hook

### PR DESCRIPTION
**Pull request by brboi**
**Description of the issue/feature this PR addresses:**
- The `throttle` function from `@web/core/utils/timing` is deprecated.
- The `throttleForAnimation` function from `@web/core/utils/timing` has some unsafe usages in the code base.

**Current behavior before PR:**
Many of the usages of the `throttleForAnimation` util did not
cancel the call to the throttled function when the using
component is unmounted.

**Desired behavior after PR is merged:**
The `throttle` function is removed.
A `useThrottleForAnimation` hook:
- is introduced
- is tested (as of the prior `useDebounced` hook which was not)
- replace the `throttleForAnimation` usages.

### CODE REVIEW

**Comment by brboi** [comment]
@odoo/rd-sm-customer please review the small change in `mass_mailing`
@odoo/rd-framework-editor please review the small change in `web_editor`

**Review by aab-odoo — APPROVED** [review]
robodoo rebase-ff r+

**Comment by tde-banana-odoo** [comment]
> robodoo rebase-ff r+

If you ask for a check or review, please don't r+ 40 minutes later ... this is a bit "we asked just to please people but we actually don't care". Not saying this is the case, but that's hurting our feelings. We are such small fragile things you know ...

Sad Tde is sad.

**Comment by tde-banana-odoo** [comment]
Also, note that there is no link to task, so it is hard for us to check the specifications, understand what has to be checked, were there any discussions or PO intervention, ... we can't just retro engineer what is on your mind based on a short commit message and content.

Next time if you ping us, please add those information, just to ease the check on our side :) .

Cheers !

**Pull request closed without merging**
