### PR TITLE
13.0 l10n at update wt

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Some fixes on the Austrian Localization

Info: @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@jco-odoo @oco-odoo 
May I ask you to merge this?

**Comment by jco-odoo** [comment]
@wtaferner Sure, but for the moment the why still escapes me.

**Comment by wtaferner** [comment]
@jco-odoo 
Is it not given by the commit messages?
The fix is clear as it is missing to have the proper tags for the report and the improvement is to be specific instead of using the wrong standard behavior (sum on non-related hierarchies as far as I remember). 

Not sure how to better describe the why to you. I just can say, that for me the why is glass clear 😉

**Comment by william-andre** [comment]
> Not sure how to better describe the why to you. I just can say, that for me the why is glass clear wink

It isn't to me either.

_________

> [IMP] l10n_at: replace with specific formula to not confuse users
>
> As it was confusing to have some autogenerated sum on the parent model we show the proper tax value of the report

> be specific instead of using the wrong standard behavior (sum on non-related hierarchies as far as I remember)

These are very different. The commit message implies that it is just because you think it is better and should only bring more clarity. The later explanation you gave afterwards implies that the current behavior is wrong without telling what is wrong.

__________

> [FIX] l10n_at: add missing report line to related taxes

Do you have some documentation? Is there some reason why it is missing? Has the law changed? Something?
Because otherwise, I could open a PR putting random tags everywhere with the exact same commit message and telling you "it's obvious, just merge it".

**Comment by jco-odoo** [comment]
@william-andre But maybe we are missing something...

**Comment by wtaferner** [comment]
- KZ 000 is wrong without the changes if you use the taxes changed as it needs to be accumulated in this figure.
- The sum is wrong being displayed based on non related hierarchies.

Read the tax report U30 and U1 and the by-law and understand the why or maybe trust me that I did all that and use it on a daily basis or realized that it is not yet perfect which I never said when I originally contributed.

Feel free to close the PR, if this is not enough for you but do not expect that I appreciate being harassed for trying to help and contribute.

**Comment by jco-odoo** [comment]
@wtaferner Did not we mean to have no amount at all in 4 or is this amount useful?  Is there no shorter way to calculate that formula, because it is quite long and some sums have already been made below it.  KZ 000 seems ok for me.

**Comment by jco-odoo** [comment]
@wtaferner What do you think about <field name="formula" eval="None"/> ?

**Comment by wtaferner** [comment]
@jco-odoo 
Would be an option and I agree that the redundant formula is not optimal for maintenance. Ideally we could reference the other sum with the same formula, but I think this was not possible with the current magic implemented and this is why I ended up as it is.

And I do not think that ```eval="None"``` does help as it would then use the fallback which was in place before (tested it via UI right now).

So, maybe we fix this later when the framework allows to deactivate useless hierarchy accumulations in 16.0?

**Comment by wtaferner** [comment]
@jco-odoo 
Alright, I rethought on the formula and made it more consistent...

Now you can accumulate 4, 5, 6 to get finally 7 (which is the VAT amount to pay or to refund) which should help the user to be not confused about the sums as in 4 there is a mix of base and tax amounts underneath which are incompatible to accumulate.

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by jco-odoo** [comment]
@oco-odoo Somehow, I could not get this formula None working either.

**Comment by oco-odoo** [comment]
> @oco-odoo Somehow, I could not get this formula None working either.

https://github.com/odoo/odoo/blob/13.0/addons/l10n_it/data/account_tax_report_data.xml#L60

Not with "eval" ;)

**Pull request closed without merging**
