### PR TITLE
[account] IMP: Allow cleaner xpath expressions

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Before this PR it is quite ugly / hard to xpath in some elements of the invoice report.
If I would want to xpath to the `<p>` element for `o.reference` for example I would have to make a dirty xpath. For example something along the lines off:
`<xpath expr="//p[3]">` 
This however tends to break quite easily. For example when one of those `<p>` elements is ever removed

Desired behavior after PR is merged: I can easily xpath on the name of the elements. In the example of the `o.reference` HTML field `<p>` I could now directly xpath on the name of the `<p>` element.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@qdp-odoo could you please have a look and merge this in? It is annoying to xpath here at the moment..

**Comment by StefanRijnhart** [comment]
Would `expr="//p[@t-field='o.date_invoice']"` work?

**Comment by Yenthe666** [comment]
@StefanRijnhart in theory it should. I'm more of a fan of the `@field` element though as everybody knows it, it is clean and it never breaks. In theory the //p could break if the element would be changed (although this is very unlikely ofcourse).

**Comment by mart-e** [comment]
As you may have seen, your build is red because of name reuse.
For these kind of reasons, these convenience PR should target master branch.
Thanks

**Pull request closed without merging**
