### PR TITLE
[IMP] Adding keys to hook from when performing post processing on

### PR DESCRIPTION
**Pull request by hbto**
Anglo_saxon module records

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Hello Humberto, 

Can you please describe what you improve with this pull request. We do not understand what is the added value of this contribution from your pull request description or from your commit message.

Is it possible to ask you a description of what your pull request solved:
 - The steps needed to reproduce the current issue
 - The current, wrong, behavior
 - The expected behavior that your pull request solves.

Regards,

**Comment by hbto** [comment]
Hello @beledouxdenis,

This pull request allows to other developers leverages from this module by taking into account
where the line from account_anglo_saxon were coming,

if those keys are not added, it can not be easily allow to track them,

as you can see they do not pose any threat to existing behavior because they are (the keys)
taken away at def line_get_convert

https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L935

by not providing this keys it will be come cumbersome for developers to 
get the most of this module.

So far,
There is no wrong behavior, so there is no expected behavior in Odoo core to fix.

So those three line will not make odoo worst or better, 
but will make developer's lives on account_anglo_saxon easier.

Best Regards.

**Comment by beledouxdenis** [comment]
Hello Humberto, 

Since the keys you add in the returned dict of these methods are passed to the method parameters, we do not understand the point to add these keys in the returned dict. You know, in advance, for which invoice line the returned dicts will be for.

Even if you need it, you can do so by overriding the method:
```
def _anglo_saxon_sale_move_lines(self, cr, uid, i_line, res, context=None):
    res = super(account_invoice_line, self)._anglo_saxon_sale_move_lines(self, cr, uid, i_line, res, context=None)
    if res:
        res[0]['invl_id'] = res[1]['invl_id'] = i_line.id
    return res
```
Regards,

**Comment by hbto** [comment]
Hello @beledouxdenis 

What I want to achieve is the same concept that 
you have achieved by marking the dicts with the same key in 
method move_line_get() on account.invoice
https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L1408

that has allowed odoo to be able to track which line to pick in
account_anglo_saxon in method _anglo_saxon_purchase_move_lines()
https://github.com/odoo/odoo/blob/8.0/addons/account_anglo_saxon/invoice.py#L156

With your statement:
def _anglo_saxon_sale_move_lines(self, cr, uid, i_line, res, context=None):
    res = super(account_invoice_line, self)._anglo_saxon_sale_move_lines(self, cr, uid, i_line, res, context=None)
    if res:
        res[0]['invl_id'] = res[1]['invl_id'] = i_line.id
    return res

I will not be able to modify or apply post-processing on lines that were created 
by _anglo_saxon_sale_move_lines

because the lines created by that method are not marked by invl_id key as
can be seen here:

https://github.com/odoo/odoo/blob/8.0/addons/account_anglo_saxon/invoice.py#L96-L120

your statement will only be true if you apply my PR otherwise it is invalid.

Best Regards.

**Comment by beledouxdenis** [comment]
>With your statement:
```
def _anglo_saxon_sale_move_lines(self, cr, uid, i_line, res, context=None):
res = super(account_invoice_line, self)._anglo_saxon_sale_move_lines(cr, uid, i_line, res, context=context)
if res:
res[0]['invl_id'] = res[1]['invl_id'] = i_line.id
return res
```
>I will not be able to modify or apply post-processing on lines that were created 
>by _anglo_saxon_sale_move_lines

Why not ? I do not follow. Since this add the 'invl_id' key within the dicts returned by the method `_anglo_saxon_sale_move_lines`, I do not understand why you couldn't apply post-processing on the lines returned by this method.

**Comment by hbto** [comment]
Though even if your solution works why not to put in core module where anybody can easily deploy it

Is there any risk which could prevent this PR from landing on stable?

Is it not better to have directly to grab that having everybody to deploy it by their own?

Noneless, I will try to check your approach.

Thanks.

**Comment by beledouxdenis** [comment]
Humberto, 

Adding code lines that doesn't add any added value or doesn't solve any issue in standard Odoo is not in our stable policy:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

We allow pull requests that make life easier for developers / custom modules / inheritance purposes, in case there is indeed no way to solve the problem within the custom module. Since you can solve the issue in a custom module, with the piece of code I mention above, we cannot consider merging this pull request in a stable release such as 8.0.

Regards,

**Comment by hbto** [comment]
Thanks for your help @beledouxdenis 

Best Regards.

**Pull request closed without merging**
