### PR TITLE
[PERF] sale: download smaller avatars in portal view

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
Inspired by 8eba16db6fdf26b5a1e0a10d7f03863eb0d40632

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Hello @xavierbol @pivi-odoo Can you take a look ? Thanks

**Comment by pivi-odoo** [comment]
Hello @duong77476-viindoo 👋🏼 
The change you've made is in the `sale` module, so the sale's dev team will take a look :) 
They've already been pinged for review.

**Comment by xavierbol** [comment]
Hello @duong77476-viindoo 

FYI, we are currently busy for the new subversion (17.3). You should normally have a review at the end of this week. 🙂

Thanks again for your contribution! 💪🏼

**Comment by duong77476-viindoo** [comment]
> Hello @duong77476-viindoo
> 
> FYI, we are currently busy for the new subversion (17.3). You should normally have a review at the end of this week. 🙂
> 
> Thanks again for your contribution! 💪🏼

Got it, thank you :heart:

**Review by Feyensv — APPROVED** [review]
@robodoo r+ squash

Indeed, it can be harmonized with the changes done in project :+1:
Thanks for the contribution !

**Pull request closed without merging**
