### PR TITLE
[IMP] mail: quick reactions navigation using tab/arrow keys

### PR DESCRIPTION
**Pull request by tsm-odoo**
This PR enables keyboard navigation in the quick reaction menu. It's makes the selection of frequent emojis event faster which is the intent of this menu.

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]
LGTM

Note that with dropdown, navigation also works with ArrowUp/ArrowDown. This is strange for horizontal menu here. Probably could make navigation use ArrowLeft/ArrowRight eventually

@robodoo delegate+ r+

**Comment by tsm-odoo** [comment]
@robodoo r+

@alexkuhn updated to use arrow right/left as well :+1:

**Comment by tsm-odoo** [comment]
@robodoo r+

**Review by tsm-odoo — COMMENTED** [review]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
