### PR TITLE
[IMP] Fix urls pointing to Odoo.com website

### PR DESCRIPTION
**Pull request by fpodoo**
Some URLs in the software were still pointing to the old pages on Odoo's website.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fpodoo** [comment]
@robodoo r+

**Comment by fpodoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
Could you rebase properly (merge commit left) ?

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
