### PR TITLE
[FIX] pos_restaurant: refunded_orderline_id array type instead of int

### PR DESCRIPTION
**Pull request by lse-odoo**
To reproduce (16.1 and >):
 1. install pos_restaurant
 2. open the bar PoS (NOT a shop)
 3. choose a table
 4. sell a product & make the payment & new order
 5. choose a table (can be the same as before, it does not matter)
 6. refund
 7. select the previous order > refund
 (already a bug, it is not proposed it is empty. But we can force its selection by going again in the refund tab. Will create a dedicated task for this issue)
 8. go back to the main floor (to force sync the order)
 9. go back to the table with the hanging refund order
 10. try to pay it

=> server error:
```
bad query: INSERT INTO "pos_order_line" (..., "refunded_orderline_id", ...) VALUES (..., ARRAY[1,'Coca-Cola'], ...) RETURNING "id"
ERROR: invalid input syntax for type integer: "Coca-Cola"
LINE 1: ..., ARRAY[1,'Coca-Cola'],...
```

This happens due to this recent fix:
https://github.com/odoo/odoo/pull/116271
Adding this field in the `search_read` yield the product ID and the name
 (ORM default behavior on Many2one fields). As the PoS needs only the ID
  we take it from the tuple.
Note: the fix does target originally version 15, but the forward port code was changed only on version 16.1 and > creating this issue.

After this commit:
Able to refund order without an errors

opw-3292121

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lse-odoo** [comment]
@robinengels FYI (as you are the author of the original fix)

**Comment by caburj** [comment]
I don't disagree with the fix. However, can we write a test tour for this fix? I know it's too much to ask but the listed steps involve several aspects so the test will be valuable.

**Comment by lse-odoo** [comment]
@caburj I'll see what I can do, it's JS tours so I'm not really used to and it looks like the refund flow have not been tested yet so it will take me some time :/ 
If I take too long, would you mind r+ it before the end of the day so that we make sure that the fix is on next week server codes and I'll add the tests next week (I promise!). What do you think ?

**Comment by caburj** [comment]
I understand. I don't mind approving this today.

**Review by caburj — APPROVED** [review]
Thank you so much for this fix.

@robodoo r+

**Pull request closed without merging**
