### PR TITLE
[FIX]web: state auto reload issue after raising usererror

### PR DESCRIPTION
**Pull request by tsh-odoo**
Issue-Link: https://www.odoo.com/web#id=1852715&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720

Pad-Link: https://pad.odoo.com/p/r.907d9f40eed20a4cfb075332d66f1082

Before this commit:
state can not auto reload first time after raising usererror.

After this commit:
state will be reloaded if anything fails in _callButtonAction method of basic_controller.

Issue-ID: 1852715

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by msh-odoo** [comment]
@aab-odoo Regarding your comment:

>>> Sorry but the test is too artificial. I'd prefer a test that reproduce the issue (so with an onchange triggering a warning -> simplest test that reproduce the issue). Here if we look at the test, we don't understand why it's so important that update is called in these cases.

I don't think we can reproduce this issue with onchange warning, update is called on button action fail, so that is why the test case is created with button click, I do agree that test case too artificial, if you want the we can remove unnecessary data fill up and only verifyStep that update is called on button fail or do you have any other suggestion?

**Comment by aab-odoo** [comment]
@msh-odoo I would try to reproduce the exact same (but simplest as possible) situation as in the bug report (as in the video). As far as i can see, you need a form view with a one2many containing at least a many2one, and an action button. The scenario is the following: you add a row in the one2many, but you don't set the many2one inside that row. Then, you click on your button and as you already did, you intercept the click and make it fail. Then you try to edit the many2one and you should observe that it can't be set anymore, whereas the good behavior would be that the many2one can be set, and then clicking on the button works, and the correct data should be saved. You might need onchanges in the process, i don't know.

Do you see any issue with this?

**Comment by msh-odoo** [comment]
@aab-odoo goal of the test it check update should be called even after button action failed, the steps you wrote in your previous comment are same as given in video, but for simplicity of test what we can do, we can open existing record, click on button and check update is called or not? I guess that is enough? what do you think? why do I need onchanges in the process, would you please elaborate?

**Comment by aab-odoo** [comment]
@msh-odoo The call of update function is an implementation detail. The test should not depend on that. On the other hand, we have a perfectly valid scenario that doesn't work before your fix, so my opinion is that we should reproduce this scenario in a test to ensure that it works (and by doing so, it will implicitly check that update is called when it should). I don't know if you will need onchanges or not.

**Pull request merged**
