### PR TITLE
[MERGE] web: `ListRenderer` review and optimise scss  

### PR DESCRIPTION
**Pull request by stefanorigano**
This merge simplifies and uniformize the ListView's styling.

Part of the overall v16 SCSS optimization/restyle, task-2704984.

task-2946835

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @adr-odoo and @pparidans , `ListRenderer` ready for tech review 👍

**Review by pparidans — APPROVED** [review]
@robodoo r+ rebase-merge

**Comment by bouvyd** [comment]
@stefanorigano @pparidans not sure, but i think this redesign introduced a small UI bug:

https://user-images.githubusercontent.com/9530767/192362205-34faa84d-2a87-4dd3-86f3-bba51879a7d7.mp4

Do you want me to report it somewhere specific? Does either of you have the time/resources to fix that?

**Comment by pparidans** [comment]
@bouvyd Weird... I don't have the scroll bars on the runbot (all) using Chrome... :thinking: 
Which modules do you have installed (beside Expenses) ? Which browser ?

**Comment by bouvyd** [comment]
@pparidans firefox, nothing else than expense at the time (but difficult to be sure)

I think it happens because of the "tip" of the expense tour, which is on a button in the empty content helper (you need a db without demo data)

**Comment by pparidans** [comment]
> @pparidans firefox, nothing else than expense at the time (but difficult to be sure)
> 
> I think it happens because of the "tip" of the expense tour, which is on a button in the empty content helper (you need a db without demo data)
> 
> Without the tip, it looks ok

Ok. I will check that :+1:

**Pull request closed without merging**
