### PR TITLE
[FIX] don't unlink several times the same id

### PR DESCRIPTION
**Pull request by ccomb**
Fix on ORM side for issue #4885

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't just better to ignore non existing records?

**Comment by ccomb** [comment]
If you want to ignore non existing records, it means you have to check whether they exist or not, it's much heavier.

**Comment by pedrobaeza** [comment]
But it's also more general...

**Comment by ccomb** [comment]
I tried to use a conservative approach while not introducing a performance issue

**Comment by pedrobaeza** [comment]
OK, you're right. Let's go for this approach for now :+1:

**Comment by petrus-v** [comment]
:+1:

**Pull request closed without merging**
