### PR TITLE
Allow third party addons to use the context to change mail sending.

### PR DESCRIPTION
**Pull request by mvaled**
Should any third-party addon uses the context to somehow change the behavior of mail.mail ``send()``, we should keep the context.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mvaled** [comment]
I don't think the failure in [runbot](http://runbot.odoo.com/runbot/build/225981) is related to this change.

**Comment by tde-banana-odoo** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `mva.led@gmail.com`
- you are signing for the address `oraldo@merchise.org`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks !

**Comment by mvaled** [comment]
Hi @tde-banana-odoo,

Sorry.  Previously I used my personal email to contribute to Odoo (which is still there: https://github.com/odoo/odoo/blob/10.0/doc/cla/individual/mvaled.md).  I've redone the commits to match my corp email address.

Best regards,
Manuel.

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks! It has been merged.

**Pull request closed without merging**
