### PR TITLE
[FIX] web, *: multi-db /web/session/authenticate

### PR DESCRIPTION
**Pull request by Julien00859**
*: base_setup, hr_timesheet, mail, partner_autocomplete, web_tour

Start odoo without -d and with a --dbfilter that allows multiple databases. Via JSON-RPC access the /web/session/authenticate route providing a non-filtered database and valid credentials. Traceback, `request.env` is None.

Since httpocalypse the initialization of the ORM (cursor, registry, environment) is greedy. It means that the connection to the database is established very early during the request routing or skip altogether in case no dbname was known at that time. This contrast with prepocalypse where the various ORM thingies were lazily setup the first time they were accessed.

This changement has an important implication regarding authentication.

In prepocalypse, thanks to the lazy approache, a cursor/registry/env would be setup on the database you just login upon using the `request.env` for the first time. This was very nice in this regard but had other problems.

Since httpocalypse such operation is no more possible. Devs must initialize and use their own cursor/registry/env in case they authenticate on another database than the one `request.cr` is (maybe) connected to.

The `/web/session/authenticate` controller is an example of such case. It crates its own cr/registry/environment after authentication. The problem the controller uses `ir.http.session_info` and that not all overrides were updated to use `self.env` (=the env created in the web controller) instead of `request.env` (=the missing env of the request).

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Julien00859** [comment]
@pparidans shall we merge?

**Comment by pparidans** [comment]
> @pparidans shall we merge?

Still broken in the apps... I try to give you a reproducible example.

In a nutshell: the auth in itself works. But after that when the webview tries to load `/web` with the `session_id` from the auth's response, it's redirected to `web/database/selector`...

**Comment by pparidans** [comment]
@Julien00859 Here are the information I collected so far... But I'll be honest: I'm stuck :sob: 

Steps to reproduce:
- Odoo server (enterprise) with at least 2 databases
- In the mobile app (Android or iOS)
- Try to add the first database as account in the app: fill the host, username, password
- Database list should popup, select one
=> login should work but, once the webview tries to load /web, the server returns a redirection to web/database/selector

Information so far:
- version info, database list and auth JSONRPC requests are OK
- the session_id returned by the auth request is properly used as session cookie in the web view
- only guess: the server doesn't recognize the session's database ?
- trying to add assert in the MobileRoutesTest to check that the session's database match the requested database works in both single and multi db mode (should fail in multi)
- trying to add assert in the MobileRoutesTest to check that loading the /web with the returned session_id returns a 200 works in both case (should fail in multi)

**Comment by pparidans** [comment]
It works :+1: 
gg @Julien00859  :muscle:

**Review by pparidans — APPROVED** [review]
LGTM (with my mobile app's hat on :tophat: )

**Comment by Julien00859** [comment]
@robodoo r+

**Comment by Julien00859** [comment]
@robodoo r+

**Pull request closed without merging**
