### PR TITLE
ORM fixes

### PR DESCRIPTION
**Pull request by rco-odoo**
These commit solve the following problems:
- Processing recomputation triggers sometimes fails because of access errors; this is due to fields being inverted on records that cannot be read by the current user.
- Unexpected recomputations may occur if a field is protected in one environment, but triggered in another environment.
- Python constraints are not checked on computed fields.

### CODE REVIEW

**Comment by rco-odoo** [comment]
ping @tivisse @jem-odoo

**Comment by tivisse** [comment]
Great ! Thanks ;)

**Comment by tivisse** [comment]
@rco-odoo FYI, tested on my simple use case, and it's working ;)

**Comment by rco-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
