### PR TITLE
[FIX] website_crm_partner_assign: align priority on portal view

### PR DESCRIPTION
**Pull request by mrsr-odoo**
Steps to reproduce 
==================
Make sure your resolution is around '1368 x 768'.
1. Open/create an opportunity and assign a partner (Joel wills).
2. Go to Joel's portal view.
3. Click on the Opportunity and go to the priority.

The priority's alignment is distorted.

After this PR
=================
Align priority correctly on the portal view of opportunities.

Task-3607070

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Comment by tde-banana-odoo** [comment]
Hello,

There have been issues with templates recently. Could you rebase and push again ?

**Comment by mrsr-odoo** [comment]
Hello @tde-banana-odoo ,
Rebased the branch 
And After BS5 in 16.0, the class name is changed -  pr-0 => pe-0
So what should we do ? :blush:

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@mrsr-odoo well we will modify the forward ports :)

**Pull request closed without merging**
