### PR TITLE
[MERGE] website_slides: review elearning widgets and templates

### PR DESCRIPTION
**Pull request by awa-odoo**
Main purpose of this merge is to lint and clean front-end templates and
widgets in eLearning.

Including
 * lint and clean JS and CSS for fullscreen widgets;
 * refactor reordering of slides and categories, handle void categories;
 * refactor category addition and slide archive widgets;
 * simplify progressbar;
 * lint slide like and crouse join widget;
 * improve course main page, restore review tab;
 * various fixes, improvements and lintings;

See sub commits for more details. Thanks to everyone involved in this
branch. So much people to tag, I have a bit la flemme.

Incoming in a near future: improved main slide page, cleaned fullscreen
widget, design-linted profile page, and probably more fixes.

Merge related to task ID 1941250 (basically, "fix eLearning post-merge").

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge try

**Comment by tde-banana-odoo** [comment]
@robodoo r-

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Comment by tde-banana-odoo** [comment]
Et ta mère elle a failé gros débile de bot ?

**Comment by d-fence** [comment]
@robodoo retry

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Comment by tde-banana-odoo** [comment]
@d-fence promised an Orval if it is merged. And two if it is not.

cc @jem-odoo

**Comment by awa-odoo** [comment]
> @d-fence promised an Orval if it is merged. And two if it is not.
> 
> cc @jem-odoo

You mean for every person involved in this PR right?

**Comment by tde-banana-odoo** [comment]
@d-fence agrees.

**Comment by d-fence** [comment]
I'm running everywhere for this PR, I deserve the Orval instead offering one

**Comment by dbeguin** [comment]
Maybe @robodoo Orval+ should be implemented

**Comment by tde-banana-odoo** [comment]
Go fuck yourself with a flamethrower.

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge flamethrowerplug+

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Comment by awa-odoo** [comment]
Stop being sorry for once and merge the damn PR

**Comment by dbeguin** [comment]
Good boy

**Comment by dbeguin** [comment]
Bad boy !

**Comment by d-fence** [comment]
@robodoo retry

**Comment by tde-banana-odoo** [comment]
Orval !

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Comment by d-fence** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEESSSS

**Comment by tde-banana-odoo** [comment]
:heart:

**Pull request closed without merging**
