### PR TITLE
[FIX] point_of_sale: small fix to make sure the error is thrown

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
Merged in https://github.com/odoo/odoo/commit/9e8f70e4849b0eeaca8b5cf51372ecfa23dc561b

**Comment by mreficent** [comment]
Will it be ported to v9?

**Comment by jco-odoo** [comment]
The posbox was maintained in v8 basically, so not entirely sure (as version
is independent of Odoo version) Ideally it would be ported to v11 as we are
putting a beta image there for python3/stretch.

**Comment by mart-e** [comment]
@jco-odoo this should probably be done manually as we no longer make forward ports of 8.0

**Comment by KangOl** [comment]
I just made the forward-port to 9.0 (the rest will follow)

**Pull request closed without merging**
