### PR TITLE
[FIX] mail: error handling when no route is found

### PR DESCRIPTION
**Pull request by sauc-odoo**
Currently, when no route is found for an incoming message the error is
generated which will be caught by the sentry and generates unnecessary traffic. 

So we stop catching errors where no route is found for incoming messages in 
sentry.

See this traceback: 
```
ValueError: No possible route found for incoming message from "Alaa Marie" <alaamohd100@yahoo.com> to notifications@nutexperts.odoo.com,"Nutrition Experts" <notifications@nutexperts.odoo.com> (Message-Id <be8d8d7b-5104-45b2-8ac5-c02597338f14@email.android.com>:). Create an appropriate mail.alias or force the destination model.
  File "odoo/http.py", line 2117, in __call__
    response = request._serve_nodb()
  File "odoo/http.py", line 1667, in _serve_nodb
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1924, in dispatch
    result = endpoint(**self.request.params)
  File "odoo/http.py", line 715, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "home/odoo/src/custom/default/saas_worker/controllers/main.py", line 2239, in smtp
    proxy.message_process(None, message)
  File "addons/mail/models/mail_thread.py", line 1242, in message_process
    routes = self.message_route(message, msg_dict, model, thread_id, custom_values)
  File "home/odoo/src/custom/trial/saas_trial/models/mail.py", line 159, in message_route
    return super(MailThread, self).message_route(message, message_dict, model=model, thread_id=thread_id,
  File "addons/mail/models/mail_thread.py", line 1109, in message_route
    raise ValueError(
```

Applying this commit will fix this issue.

sentry-4156972615

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fpodoo** [comment]
@robodoo r+

**Comment by sauc-odoo** [comment]
Hello @fpodoo 
I have opened this PR.

**Comment by tde-banana-odoo** [comment]
What is this 'sentry_ignored' attribute ? Is it a hack, because I see there are solutions to filter exceptions in sentry that do not involve modifying the source code ?

**Comment by tde-banana-odoo** [comment]
``ValueError`` is maybe not the best one, but better than a generic UserError ... I see in https://stackoverflow.com/questions/57828717/how-to-ignore-certain-python-errors-from-sentry-capture that you can try to configure your sentry to ignore errors based on message, but the message itself is varying due to gateway parameters (although not translated so always beginning with the same sentence). Maybe something like this could work ?
```
def before_send(event, hint):
    if 'exc_info' in hint:
        exc_type, exc_value, tb = hint['exc_info']
        message = exc_value.args[0]
        if 'No possible route found for incoming message' in message:
            return None
    return event
```

**Comment by fpodoo** [comment]
> Maybe something like this could work ?
This is basically what we do with `sentry_ignore`; we tag the exception to filter out before sending to sentry.
But we can not do it based on the text as you propose as those exception messages are usually translated.

**Comment by fpodoo** [comment]
> you can try to configure your sentry to ignore errors based on message, but the message itself is varying due to gateway parameters

This is basically what we do with sentry_ignore; we tag the exception to filter out before sending to sentry. It's better than trying to do it based on the message as; "the message is dynamic" and the message if often translated.

**Pull request closed without merging**
