### PR TITLE
[FIX] website_sale: Sort product by website sequence in website sale.

### PR DESCRIPTION
**Pull request by tanghulu0608**
Description of the issue/feature this PR addresses:

When sorting product sequence in product list view in web sale. User can not see the correct sorting result .
This pr fix it.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
Thank for fix.
Could you amend your message to follow our guidelines. Thanks...

`[FIX] website_sale: sort by website seq...
`
@robodoo delegate=rdeodoo

**Comment by tanghulu0608** [comment]
Done. I have changed the pr title and the git commit message.

**Review by rdeodoo — APPROVED** [review]
@robodoo r+
Indeed, without this defaut order the website_sequence in that tree view wasn't really making sense.

Thanks for the PR, note that in commit message we prefer to not have uppercase or trailing `.` but don't change it now, this is going to be merged.

**Comment by tanghulu0608** [comment]
Got it.

**Pull request closed without merging**
