### PR TITLE
[IMP] stock: automatically recompute quantities on UOM change

### PR DESCRIPTION
**Pull request by jorenvo**
Task:
https://www.odoo.com/web#id=27269&view_type=form&model=project.task&action=333&active_id=248&menu_id=4720
Pad:
https://pad.odoo.com/p/r.690bcb270aea39eadb92752230689402

### CODE REVIEW

**Comment by pimodoo** [comment]
Hi @jorenvo ,

I'm reviewing your code, and I'm not sure that the field 'previous_product_uom_id' is usefull in this case because it's only used in the onchange and it's not stored.

If I've well understand what the code is suppose to do, this field is present to get the old uom in the onchange and so compute the new quantity. I've asked to other developers if there is an other way to get the old value, and apparently there is an '_origin' to call on record to get the old one.

So do you think we can replace the field by a call to something like 'self._origin.product_uom_id', or there is  another reason for this field?

I can make the changes if you want.

Best regards

**Comment by jorenvo** [comment]
Yes I know but If I remember correctly there are cases where `_origin` is not available. It either depends on whether or not you're in an onchange or whether or not the record is a `NewId`. I don't remember the specifics anymore however. Of course this was done a while ago, so maybe since then the ORM has changed.

**Comment by wtaferner** [comment]
@jorenvo 
Is there a solution for that? I think it is a very valuable attribute during an onchange unfortunately it only works for the top triggering object...as soon as you go into the secondary you have no idea if the current object is related to an already stored object or if it is just a new one.

@rco-odoo 
Do you have any hints and thoughts about the onchange an how to find out if a field was changed on a secondary level like ```sale.order.line```?

**Comment by bst-odoo** [comment]
hello @wtaferner , we will still do it. We have move the content into another task.

**Pull request closed without merging**
