### PR TITLE
[FIX] account: fixed typo on docstring

### PR DESCRIPTION
**Pull request by ADVALAKI**
Description of the issue/feature this PR addresses: fix typo on docstring of _get_last_sequence method

Current behavior before PR: Typo on docstring

Desired behavior after PR is merged: fixed typo on docstring

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for you patch but there is still some issues:
- Your patch is not a bug fix but a code cleaning. We usually do not merge patches that have no impact on the user but as a first contribution we can accept it if it targets the master branch. Could you rebase and retarget (reopen a new one if not sure how to rebase) ?
- it seems you have not [signed the CLA](https://www.odoo.com/sign-cla). Could you add it so we can integrate your patch?
 
Regards

**Comment by 333will** [comment]
?

**Comment by mart-e** [comment]
@333will ? Have you received a notification or something ? My message was intended to @ADVALAKI

**Comment by ADVALAKI** [comment]
@mart-e i have created new pull request here:

https://github.com/odoo/odoo/pull/63619

I also included CLA, let me know if i need to correct any details. 
As this is my first commit and i am not sure how to work with it.

Thanks.

**Pull request closed without merging**
