### PR TITLE
[12.0][IMP] l10n_es: Unfold account 746 into 2

### PR DESCRIPTION
**Pull request by pedrobaeza**
According to what has been discussed in OCA/l10n-spain#1434, there's a problem with this account, that can be put in 2 places in the balance sheet, depending on its nature.

Unfolding it into 2 using same prefix, we can indicate users in which account they should book their balances according the nature, and define reports according these accounts without the need of modifying them each time.

Closes OCA/l10n-spain#1434

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And another one for you before the weekend @jco-odoo :innocent:

**Comment by jco-odoo** [comment]
@pedrobaeza @anajuaristi Does it need to be with 6 digits?  The max I see is 5 and then I also wonder if it would not be better to categorize them at the same height then: 74601 financiero 74602 no financiero por ejemplo

**Comment by pedrobaeza** [comment]
Well, the idea is that using the standard 6 code digits (that you can't change since v12), you get an account 746001 as well as 746000 (obtained from 746 prefix + 000 auto-filled). Using 746100 or 746010 will be weird according regular Spanish habits (and the first one not sure even if valid).

Take into account that after merging this, `l10n_es_reports` enterprise module should be adapted as well for benefiting the change.

**Comment by jco-odoo** [comment]
Let me do a quick verify with @oco-odoo on Monday on how we tackle this.

**Comment by jco-odoo** [comment]
@pedrobaeza The changes are for the P&L, I suppose.  The problem is a bit that we use the account codes for constructing that report and as we are not putting tags on the accounts for this, the question arises: what happens when the account is 746002?

**Comment by pedrobaeza** [comment]
Good question! I have been thinking about this the weekend, as indeed someone creating manually more subaccounts will find that these accounts are included nowhere. Let me check the account group and also query in the Spanish localization repo to see if we can put a prefix with less than 6 digits.

**Comment by pedrobaeza** [comment]
@jco-odoo @oco-odoo changed accounts for being 746000 and 746100, so it's not a problem to extend them with the 2 remaining digits. It's not something normalized, but NECA denormalized this before having the same account for 2 things.

**Comment by pedrobaeza** [comment]
@jco-odoo @oco-odoo is it OK now?

**Comment by oco-odoo** [comment]
@pedrobaeza 
I cherry-picked the commit on this branch https://github.com/odoo/odoo/pull/55522 , so that the mergebot can synchronize it with enterprise properly. Enterprise part is here: https://github.com/odoo/enterprise/pull/12248

I'm closing this PR. Thanks for reporting the issue :)

**Comment by pedrobaeza** [comment]
Great, thanks!

**Pull request closed without merging**
