### PR TITLE
[IMP] hr_contract: rename 'Advantage' to 'Benefit'

### PR DESCRIPTION
**Pull request by vive-odoo**
In this commit, I have made changes from 'Advantage' to 'Benefit' because I made modifications in the 'hr_contract_module'. This group is being utilized in 'hr_contract', so I updated the file accordingly.

task-3374616

### CODE REVIEW

**Comment by sofiagvaladze** [comment]
@odoo/rd-security would you mind giving an exception?  
PR rewrites the lines which already had getattr.. does not add any new

cc: @ppr-odoo @vive-odoo I pinged upgrade on upgrade PR. Please follow up and ask for a review from them :)

**Comment by sofiagvaladze** [comment]
robodoo r+

**Comment by ppr-odoo** [comment]
@sofiagvaladze Is needed to rebase the branch?

**Comment by ppr-odoo** [comment]
@sofiagvaladze  I solved the confilit so we need r+ again.

Thanks

**Comment by sofiagvaladze** [comment]
robodoo r+

**Pull request closed without merging**
