### PR TITLE
[FIX] l10n_fr_pos_cert: log hash string for better error investigation

### PR DESCRIPTION
**Pull request by pedrambiria**
This commit add the logging of hash string data. By printing the string to hash, it becomes easier to investigate issues.

opw-3839287

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by adgu-odoo — COMMENTED** [review]
All of the information displayed here are visible in the db or can be computed from the db, why should it be logged ? Maybe to make it easier to retrieve, a button can be made somewhere shown in debug mode to display those information don't you think ?

**Comment by pedrambiria** [comment]
@adgu-odoo While it's true that all the information displayed can be retrieved or computed from the database, logging this data simplifies the process of issue investigation. Specifically, when there's a mismatch between the order hashes and the computed hash, it's crucial to understand the cause. The 'l10n_fr_string_to_hash' is a computed field that changes if the order is modified. Although many details can be extracted from the database, logging them provides a more straightforward approach to troubleshooting potential issues.

**Comment by caburj** [comment]
robodoo rebase-ff

@adgu-odoo I think you can merge this

**Comment by adgu-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
