### PR TITLE
[I18N] project_timesheet_holidays: improve ValidationError term

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Improve the warning for the user.

Current behavior before PR: Vague warning, not very nice English.

Desired behavior after PR is merged: A better English sentence.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e found one other term in another module that could use an improvement.

**Comment by mart-e** [comment]
Good catch, thanks :+1: 
Could you integrate this into #35227 as it is very similar?
Also, as you are modifying this error string, could you also fix the extra spaces in the message?
You can see in the .pot why it is not ideal (even if it does not make any difference for the end user)

https://github.com/odoo/odoo/blob/78565b1dc933692abba46a73f2298b7ea8e03c88/addons/project_timesheet_holidays/i18n/project_timesheet_holidays.pot#L28-L32

**Comment by Yenthe666** [comment]
@mart-e yeah sure I can combine both PR's into one. How should I fix the extra spaces though? I'm not sure of that one as it is just a multiline Python string?

**Comment by mart-e** [comment]
There is several ways to do so:

```python
                    raise ValidationError(_('Both the internal project and task are required to\
generate a timesheet for the time off. If you don\'t want a timesheet, you should\
leave the internal project and task empty.'))
```

```python
                    raise ValidationError(_("""Both the internal project and task are required to
generate a timesheet for the time off. If you don't want a timesheet, you should
leave the internal project and task empty."""))
```

```python
                    raise ValidationError(_("Both the internal project and task are required to "
                                            "generate a timesheet for the time off. If you don't want a timesheet, you should "
                                            "leave the internal project and task empty."))
```

You can try some and see, when exporting the translations is the result is good (watch out for end of line spaces too)

**Comment by Yenthe666** [comment]
Closing in favour of https://github.com/odoo/odoo/pull/35227

**Pull request closed without merging**
