### PR TITLE
[ADD] Add hr_attendance_contract module

### PR DESCRIPTION
**Pull request by fkantelberg**
Add `_get_employee_calendar` to hr_attendance function to allow overwrite in later modules to overwrite it with a bridge module to hr_contract. `_get_employee_calendar` is overwritten because this function will be used in `master` to get the resource calendar of an employee while the changed function interface would have to be adapted while porting.

**Description of the issue/feature this PR addresses:**
If `hr_attendance` and `hr_contract` are installed the defined resource calendars of the contracts are used to calculate the overtime of the employee.

**Reproduction:**
- Install hr_attendance and hr_contract
- Enable "Count Extra Hours" in the Attendances settings menu
- Set "Start from" to a date in the past (e.g. 01.01.2023)
- Create a contract C1 for Administrator starting April 1st, ending April 30th, with a 40 hours week
- Create a contract C2 for Administrator starting May 1st, open-ended, with a 35 hours week
- Create an attendance for Administrator on a Monday in April, from 8:00 AM to 4:00 PM
- Create an attendance for Administrator on a Monday in May, from 8:00 AM to 5:00 PM
- Go to Attendances, Reporting, select Pivot view and remove the filter

**Current behavior before PR:**
- Attendance Analysis shows 1 hour overtime in April, it does not take hr_contract into account

**Desired behavior after PR is merged:**
- Attendance Analysis shows no overtime in April (8 hours worked because C1)
- Attendance Analysis shows no overtime in May (7 hours worked because C2)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sofiagvaladze** [comment]
Hello @fkantelberg, thanks for your contribution :)

So, the issue is that we don't want to fix something like this in stable as it involves adding a module.

What we could do instead is target master, something like this should rather be done in master.

**Comment by fkantelberg** [comment]
Hello @sofiagvaladze,

this fix would require additional code for `master` because `_compute_worked_hours` of `hr.attendance` must be adjusted aswell. Sure we could prepare a fix for master but am I reading it correctly that you don't want to fix the fauly behaviour in your stable releases because the additional module is required? If that's the case would it be an option to only push the changes in `hr_attendance` towards the stable branches?

I'm asking because the faulty behaviour is already causing problems in 15.0 for us and I want to evaluate the next steps for us. Either way fixing the Odoo core is prefered.

**Comment by leemannd** [comment]
Hello @sofiagvaladze , this kind of contribution is welcome and could land into the OCA. You're welcome to make any contribution into https://github.com/OCA/hr

**Comment by shochstoeger** [comment]
It's quite common for employees at our company to update their contracts. However, this often leads to issues with overtime calculations because Odoo continues to use the wrong contracts.
Are there any plans to address this issue in Odoo 18?

**Comment by jugj-odoo** [comment]
> It's quite common for employees at our company to update their contracts. However, this often leads to issues with overtime calculations because Odoo continues to use the wrong contracts. Are there any plans to address this issue in Odoo 18?

Hello @shochstoeger , actually it is planned to be fixed in stable 17.0 and will not require a bridge module, here is the PR addressing the issue (still work in progress) https://github.com/odoo/odoo/pull/159477

**Comment by shochstoeger** [comment]
Hello @jugj-odoo, thank you for the update. Looking forward to seeing the fix implemented!

**Comment by Bertrand2** [comment]
Hello @fkantelberg ,

Thanks a lot for your contribution!
As mentionned above, we will implement the solution mentioned by @jugj-odoo as it is bringing the same behaviour in a more generic manner. :slightly_smiling_face:
FYI, we decided to implement those changes in 17.0 rather than 15.0 because the logic behind attendances changed a lot since then and porting the changes to the newest versions would be quite tedious.
Considering this, I don't know if keeping both PRs make sense, what do you think?
If you agree, we can then close this PR.

Have a nice day!

cc @sofiagvaladze

**Comment by fkantelberg** [comment]
@Bertrand2 
Sure a more generic solution is favorable but I also read that you don't care about the bug in (still stable) versions like 15.0 and 16.0 because it only works for 17.0+. For me this just means that there is no need to forward port this to 17.0 and beyond.

As far as I see you avoid the extra module in your solution by defining functions in `hr` and overloading/using them in `hr_contract` and `hr_attendance`. Sounds reasonable and also possible here if the biggest issue is the bridge module.

**Comment by Bertrand2** [comment]
Hello @fkantelberg ,
I think indeed that it's best to have a more generic solution and have the method on the employee model in `hr` and `hr_contract` :slightly_smiling_face:
If you don't mind doing that change, I'll gladly review this and have it in parallel of the other one mentionned before.
Thanks and have a nice day!

**Comment by ortlam** [comment]
Hi @Bertrand2 ,
we have moved the functionality from the bridge module into `hr`, and `hr_contract`.

**Comment by Bertrand2** [comment]
Hello @fkantelberg @ortlam, after discussion we decided not to merge this PR. The described situation is more a limitation than a bug as the issue only appear upon modifying attendances in the future or in the past while attendances incoding as intended works correctly, making this more of a logic change rather than a bug fix.
Thanks for your understanding and have a nice day :)

**Comment by OSevangelist** [comment]
@Bertrand2 (@mart-e @jugj-odoo @jni-odoo) as they can maybe help out herel). This really is a pity. First we discuss that "limitation / bug" with quite some explanatory / discussion effort, than my team asks me to allow them to spent time on doing a PR against Odoo core for something that has been solved in all our projects by moving our generic bridge code into the appropriate upstream modules (as per your request) and than finally you "discuss" and conclude that improvements (that aren't considered bugfixes) aren't merged. I am sure you understand that this is a quite dissapointing experience. Maybe that is due to your role inside Odoo (probably only responsible for bug fixing), but i am sure you understand that wasting time is nothing that we should keep going (neither at your end nor at ours). So i would really appreciate if you (or the appropriate feature team, based on a dispositive request from @fpodoo or any other executive at Odoo) reconsiders your decision as an improvement to existing functionality (which you deemed valuable in the first place and asked us to to PR for). I am pretty sure the ecosystem will benefit as a whole as even limitations are to be eliminated for good UX. Therefore please don't take it as an offense but on behalf of my team i would really appreciate if you could reconsider your decision with the responsible PO for HR at Odoo. Thanks for reconsidering.

**Comment by tivisse** [comment]
@OSevangelist Thank you for your feedback. We understand the effort and dedication your team has put into addressing the limitation and proposing a PR to the Odoo core. After careful consideration, we have decided to address the issue properly within our development team. While we appreciate your initiative, we found that the proposed fix was not as clean as we require for integration into the core system, so we have chosen to develop our own solution.

For your information, the following fix has been merged and forward ported from the version 17.0 to the master branch:
https://github.com/odoo/odoo/pull/159477
https://github.com/odoo/enterprise/pull/59539

On the other hand, we will deploy this fix from version 15.0 to the version 17.0 (not included):
https://github.com/odoo/odoo/pull/168839

We also want to address the tone of your message. We value open and constructive communication, and your message was not well taken by our team. We do not make any difference between members of bugfix team or development team, and actually @Bertrand2 is the responsible technical person for all the HR applications. We believe that maintaining a respectful and collaborative tone is essential for productive interactions. We kindly ask that future communications remain considerate and professional.

Thank you for your understanding and cooperation.

**Pull request closed without merging**
