### PR TITLE
[FIX][8.0] Fix check_xml when inheriting from views created in the same module

### PR DESCRIPTION
**Pull request by Garamotte**
When inheriting from a view in extension mode created in the same module, this view was not loaded during check_xml of the last view.
This caused an error when the last view wants to modify elements added by its direct parent view.

Example :
- View1, created in module "account"
- View2, mode extension, created in module "customer", inherits View1
- View3, created in module "customer", inherits View2

During update of module "customer", when loading View3, the check_xml call didn't load View2, because it's defined in the same module (and, obviously, this module has not be totally loaded at this point)

This is fixed by adding direct parent of each loaded view in the check_view_ids list in context, to force them to be loaded.

cc @rco-odoo

### CODE REVIEW

**Comment by sylvain-garancher** [comment]
ping @odony

**Comment by sylvain-garancher** [comment]
@odony : Could you review this trivial PR ?

**Comment by sylvain-garancher** [comment]
OPW opened : 658457

**Comment by gurneyalex** [comment]
:+1:

**Comment by antespi** [comment]
:+1:

**Comment by sylvain-garancher** [comment]
Just updated the commit, following @gurneyalex 's remark on IRC (using dict.setdefault outside the loop).

**Comment by beledouxdenis** [comment]
Dear,

I just merged the first commit of your proposal in Odoo 8.0 from the below revision:
https://github.com/odoo/odoo/commit/11cd22711c6a31d0f98628ebbbb01ab3ef5c23e8

The tests added in the second commit is welcome as well, but `base_demo.xml` is not an appropriate place. But I cannot think about a better place at the moment.

I will discuss this internally to know where is the best place to add this test.

In the mean time, the fix is merged. Thank you for your contribution !

Regards,

**Comment by sylvain-garancher** [comment]
I agree for the second commit, it wasn't intended to be merged, but just here to show you an example of data which causes the crash (as I said [here](https://github.com/OCA/OCB/pull/405#issuecomment-165737428), but forgot in this PR).

Thanks for having merged the fix ;)

**Pull request closed without merging**
