### PR TITLE
Create bfotop.md

### PR DESCRIPTION
**Pull request by bfotop**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by odony** [comment]
Hi @bfotop,

Would you mind adding the reference to your github login in your CLA signature line, like this:
```
Basilis Fotopoulos bfotop@tax-solutions.gr https://github.com/bfotop
```
I know this may sound redundant, but it helps with identification in case the CLA signature is viewed outside of github. We prefer to keep CLA signature commits untouched by the staff, so it would be great if you could add it yourself.
Thanks!

PS: You can also use your github anonymized email (bfotop@users.noreply.github.com) instead in the CLA if you want to avoid publishing your email in the repository, but then you'll have to change your git config `user.email` accordingly.

**Comment by bfotop** [comment]
Thank you I believe now it is ok

**Comment by odony** [comment]
@bfotop thanks for the update, although you still need to update your `user.email` in your git config, as your commits are still signed with your real email address, so they do not pass the CLA check anymore. See `git config user.email`.
You can then rebase your commit and push force it on your branch.

**Comment by bfotop** [comment]
can i revert my signature to 
Basilis Fotopoulos bfotop@tax-solutions.gr https://github.com/bfotop
and not have to go to git config?

**Comment by odony** [comment]
@bfotop Thanks, it's all good like that! :+1:
Just merged your commit in 9.0 at revision f9881b23bb88bf53aaceaef7eac2854806755fed.

**Pull request closed without merging**
