### PR TITLE
[FIX] website: duplicate setting element id on setting page

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
-Before this commit there are 2 setting with same id call 'robots_setting'
-After this commit, rename the second one to 'sitemap_setting'

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Hello @tivisse can you take a look please? Actually the problem still exist in other version like 15.0, if you are ok this the change please tell me which version i need to fix

**Comment by MiquelRForgeFlow** [comment]
dulpicate -> duplicate

**Comment by duong77476-viindoo** [comment]
> dulpicate -> duplicate

:face_with_diagonal_mouth:

**Comment by tivisse** [comment]
Hi @duong77476-viindoo 

Thanks for the fix ! 

Indeed, as pointed by @niyasraphy there is a risk to break other people's customizations. Could you please target the master branch instead ?

Have a nice day !

**Comment by duong77476-viindoo** [comment]
@tivisse Oh i've checked on master, the sitemap setting has been removed so i'll close this PR

**Pull request closed without merging**
