### PR TITLE
Master imp qweb chm

### PR DESCRIPTION
**Pull request by Gorash**

### CODE REVIEW

**Comment by Gorash** [comment]
@ged-odoo ping ping

**Comment by odony** [comment]
- Could we stop this true/True silliness and provide the proper backwards-compatibility, as discussed?
- What is the rationale for this new change? Neither the nice PR description, nor the commits, nor the code explain *why* we want to have 2 different modes of evaluation strict/non strict and how this will be the path of Least Surprise for the developers?

**Comment by Gorash** [comment]
When everything is in order then backward without a module we can do that makes the backward log with a warning (I must see with ged to the idea that he has about the backward module).
To use the dict, the message explains why. We want, if the person is mistaken, there raise an exception. This was discussed with rco, XMO, sle, ged. This change allows you to find the last place that had not been corrected.

**Comment by odony** [comment]
Still does not explain why we would want to have 2 different modes of evaluation depending on the case/attribute? Why not *always* use strict mode, for example?

**Comment by ged-odoo** [comment]
As far as I can tell, we did not take any decision yesterday. I agree that it should always be strict, otherwise we can't tell if there is a problem in a template. Failing silently is never good.

Anyway, since chm is not here today or tomorrow, let's have a meeting about this next week with al. This PR should not be merged before we have an official stance.

**Comment by Gorash** [comment]
I jabber on, I can get on Skype.
In the view strict is not required because when someone does a t-if="optional value" the option is absent (but we can use strict and fix all template/controller). Visually the user sees that there is more since the tag is removed (falsy). In the case of options, there is no indication to the user error. Example: an option in the contact field will just change the layout (change padding) which is difficult to understand and therefore to fix.

**Comment by xmo-odoo** [comment]
> Why not always use strict mode, for example?

Because interpreted qweb [uses lenient lookups](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_qweb.py#L99).

And that's likely because it's both more widespread (all of Django, Jinja and Mako default to lenient lookup, though Genshi apparently switched from lenient to strict with version 0.5) and easier to implement cross-platform.

**Comment by odony** [comment]
On 06/16/2016 11:43 AM, xmo-odoo wrote:
>>   Why not always use strict mode, for example?
> 
> Because interpreted qweb uses lenient lookups
> <https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_qweb.py#L99>.
> 
> And that's likely because it's both more widespread (all of Django, Jinja and
> Mako default to lenient lookup, though Genshi apparently switched from lenient
> to strict with version 0.5) and easier to implement cross-platform.

Sounds fair enough. So my point in that case is: why not keep lenient mode
everywhere? ;-)

The visibility argument seems pretty weak. If mistakes are globally silent (to
mirror other frameworks), why would field options be special-cased?
Devs are likely to be bitten/surprised that "optional" template parameters are
suddenly not optional when it comes to field options.

**Comment by xmo-odoo** [comment]
> Sounds fair enough. So my point in that case is: why not keep lenient mode
everywhere? ;-)

Lenient mode is conserved everywhere it was previously used.

> If mistakes are globally silent (to mirror other frameworks), why would field options be special-cased?

> Devs are likely to be bitten/surprised that "optional" template parameters are suddenly not optional when it comes to field options.

Field options previously didn't use the template context at all, they have to be special-cased either way.

**Comment by Gorash** [comment]
In the end we merge?

**Comment by Gorash** [comment]
@odony Ready, it's good for you ?

**Comment by Gorash** [comment]
Merged, thanks

**Pull request closed without merging**
