### PR TITLE
[FIX] sale: online quotation

### PR DESCRIPTION
**Pull request by simongoffin**
The field state in the model "sale.order" must be translatable.

opw:632349

### CODE REVIEW

**Comment by beledouxdenis** [comment]
I believe the change in ir_qweb is too drastic or even too dangerous.

Isn't the problem located in the browse as the current user here (or event SUPERUSER_ID in case there is a token given in the route) ?
https://github.com/odoo/odoo/blob/8.0/addons/website_quote/controllers/main.py#L39

Regarding the `translate=True` on the state field: Well, while I believe this is correct, I am pretty sure that this field is already, somehow, translatable / translated, as the state is well translated when reading the sale order in the back-end: Have you searched why ?

**Comment by beledouxdenis** [comment]
Looks like a selection field is always translatable:
https://github.com/odoo/odoo/blob/8.0/openerp/tools/translate.py#L770

The translate=True is therefore useless, I believe.

**Comment by simongoffin** [comment]
Alright!

**Comment by beledouxdenis** [comment]
Much better :+1:

**Comment by beledouxdenis** [comment]
Closed with bd82569d512c37db6ff3a870e31d05ad7e8fb3a5.

**Pull request closed without merging**
