### PR TITLE
Prevent signal handlers being blocked

### PR DESCRIPTION
**Pull request by xmo-odoo**
Since Python only allows signal handlers on the main thread and has a big lock, some events (e.g. IO, accept(2), ...) can defer the execution of signal handlers. If the event in question gets stuck, it makes e.g. dumpstack (kill -3) unresponsive which is inconvenient to diagnose stuck processes.

By moving the potentially blocking work to a sub-thread and idling the main thread, the event handlers should always run.

Task 1913129

### CODE REVIEW

**Comment by xmo-odoo** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
robodoo retry

**Comment by antonylesuisse** [comment]
Nice and Minimal. Next time try to respect ordering, runloop is ordered top down among bottom up, .

**Pull request closed without merging**
