### PR TITLE
[FIX] mail: impossible to black list an email

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
Go to Blacklist
Click create
--> Impossible to save

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
seems we have the same in  black listed phone numbers also.
https://github.com/odoo/odoo/issues/121337

**Comment by fmdl** [comment]
OPW #3422127

**Comment by tde-banana-odoo** [comment]
I suppose it is linked to auto-save ?

**Comment by niyasraphy** [comment]
@tde-banana-odoo 
in this case, it will get saved automatically, but if user needs to discard the creation, there is no option as of now
https://github.com/odoo/odoo/issues/121337

**Comment by tde-banana-odoo** [comment]
That's something to discuss with JS team and PO actually, as it is a flow that is broken due to auto-save globally. I think it still makes sense to keep the edit=false, as you should use the tools to add / remove blacklist emails.

**Comment by fmdl** [comment]
@tde-banana-odoo where is the tool to remove or add ?

**Comment by fmdl** [comment]
ping @tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
@robodoo r+

In the end better let people do what they want with their data :)

**Pull request closed without merging**
