### PR TITLE
[FIX] web, base: redirect to index if no menu can be loaded in the backend

### PR DESCRIPTION
**Pull request by nim-odoo**
If no menu can be loaded in the backend (for example, if the user has no access
to the backend), redirect to index. This prevents a 500 error when the user
connects.

opw-642831

### CODE REVIEW

**Comment by nim-odoo** [comment]
That should also solve runbot connection error

**Comment by beledouxdenis** [comment]
I am not fan of the `except Exception:`
Could you not catch a more specific Exception ? The exact exception which is raised ?

**Comment by nim-odoo** [comment]
It's an AccessError :dancers:

**Comment by beledouxdenis** [comment]
Maybe return `[]` instead of `False`, so you keep the same return value type.

But I just saw that you did this in module `web`: What happens if website is not installed ? Infinite loop ?

**Comment by nim-odoo** [comment]
Now redirects to the original page

**Comment by Yenthe666** [comment]
@nim-odoo would this also catch the problem where a view is corrupt/has an error? Would it then automatically open the index? Looks like a neat improvement :+1:

**Comment by beledouxdenis** [comment]
Won't be merged in 8.0 because this is a huge change of behavior, that cannot be performed in a stable release such as 8.0.

But, as this is a simple change of view, this can still be done for users really wanting this behavior, by altering the appropriate view.

**Pull request closed without merging**
