### PR TITLE
[FIX] account: test typo forward-port 3e4b9d4d66c


### PR DESCRIPTION
**Pull request by nle-odoo**

### CODE REVIEW

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by nle-odoo** [comment]
robodoo priority=0

**Comment by KangOl** [comment]
I plead guilty.

**Comment by KangOl** [comment]
@robodoo priority=0 r+

**Comment by KangOl** [comment]
@robodoo retry

**Comment by nle-odoo** [comment]
robodoo p=0

there was a warning I didn't see when running test locally, it should be alright now.

**Comment by mreficent** [comment]
The warning shall be fixed  :)

**Comment by KangOl** [comment]
@robodoo ~~f you~~ retry

**Comment by KangOl** [comment]
@robodoo p=0 retry

**Pull request closed without merging**
