### PR TITLE
[FIX] website_links: fix remaining bugs and restore skipped test

### PR DESCRIPTION
**Pull request by rdeodoo**
This commit is following c78da8a80 that fixed website_links module.

We had to merge it with a skipped test as there was an error only appearing
with Docker (on runbot or on local with Docker).

This commit fix that test error and some other remaining bugs not found during
the first fix:
1. Fix the test error by adding a step to show recently used links. Indeed the
   bug was that newest links would return inconsistent order as both 2 links
   created during the steps have the same creation date.
   On runbot it would click on the wrong link, the one which has 0 clicks.
   Then JS would crash (see error bellow).
2. `websiteLinksCharts` JS animation class would execute all the `start`
   method code even if there was no `_totalClicks`. JS would then crash as
   `beginDate` would not be set correctly. Before the refactoring all that code
   would be skipped as surrounded by an if/else condition.
3. BS3 to BS4 broke the nav-tabs layout to switch between 'Newest, Most Clicked
   and Recently Used. `mt16` needed to be removed.

### CODE REVIEW

**Comment by rdeodoo** [comment]
@d-fence Holy moly, I finally found the issue that was actually hidden behind a JS error in `website_links` module..

On Docker (apparently, since only on runbot and on local with your Docker instance), `search_read` is returning records in another order.
In `website_links` case, there is a call to 
```python
self.search_read([], order='create_date DESC', limit=limit)
```
In local, if the 2 `link.tracker` have the same `create_date`, it will then sort by `ID desc`, while on runbot it will sort them by `ID asc`.

That was difficult to detect as every records created during a tour/test have the same `create_date` (both created in python before the test is launched or during the tests seconds later).
And that same `create_date` is in the past, at the exact time the python test method was called.

In this case:
1. Test method `test_01_test_ui` is called at **18:09:40,444**
2. First `link.tracker` is created in python before the tour at **18:09:42,154**
3. During the tour, a step is creating another `link.tracker` at **18:09:45,493**, so 3 seconds later
4. At the end, when doing the `search_read()`, both records have **datetime.datetime(2019, 3, 13, 18, 9, 40, 445969)** as `created_date`, which is the exact time from step 1.

Finally, the tour was then clicking on the wrong `link.tracker` on runbot (the first, but since in the reverse order it would not be the one expected) which has no 'clicks' counts.

That's where the `website_links` JS would fail, independantly of this test, accessing a `link.tracker` with no 'clicks' counts crash.

I guess everything is fine, this commit fixes the JS error and avoid that random order by adding a step to filter/sort recently used links..

**Comment by JKE-be** [comment]
```diff
    @api.model
    def recent_links(self, filter, limit):
        if filter == 'newest':
-            return self.search_read([], order='create_date DESC', limit=limit)
+            return self.search_read([], order='create_date DESC, id DESC', limit=limit)
```
maybe you could force the determinism in the code too no?

**Comment by JKE-be** [comment]
Mais merci d'avoir fixer toute la ville y compris le lampadaire qui se trouvait à l'entrée du village du coté des chtis

**Comment by rdeodoo** [comment]
Yes that was the other solution once I found the source of the error.

I prefered to adapt my test and add a step (that actually test one more stuff now) rather than change standard code.

Anyway this is good to be merged now.

And I still find it surprising that runbot fallback on different SQL order (psql version, OS?)

About the fact that every records created during the test got the `create_date` set to the time the test was called, I was not aware of it but `now()` in PSQL is supposed to [return the timestamp of the transaction start](https://stackoverflow.com/a/24169018/3974585).

**Comment by rdeodoo** [comment]
I added the `id DESC` to avoid undeterminism.
This is good to be merged

**Comment by JKE-be** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
