### PR TITLE
[FIX] account: sync invoice values currency rounding

### PR DESCRIPTION
**Pull request by william-andre**
When syncing the values of the invoice, the balance might need to be recomputed if some business fields changed.
The detection of the changed fields was flawed because of a missing rounding, leading to a false positive detection.

Reproduce:
* Using demo data
* Create an invoice in EUR (company USD)
* Add a line for `[E-COM07] Large Cabinet` (price 209.30)
* Select the partner
* Validate the invoice

task-padfeedback

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dylankiss** [comment]
@william-andre While working on this issue I also discovered another small bug in the error message shown. It uses the invoice currency formatter, while it should use the company's currency formatter on the move lines.

Change: https://github.com/odoo-dev/odoo/commit/5ea01951b95682dc092fb6fa1fa108cf17d3ed75

**Comment by william-andre** [comment]
@dylankiss Nice catch, you can add the commit to this PR if you want to, or create a new PR

**Comment by epictete** [comment]
@robodoo r+

**Comment by epictete** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
