### PR TITLE
[FIX] mail: prepare mail header References to avoid line breaks

### PR DESCRIPTION
**Pull request by ventor-dev**
When Odoo routes incoming emails it is looking for existing messages in database using Message Ids which are coming from e-mail header References.
In Odoo the message id looks pretty long like <743570479975566.1584086032.522504091262817-openerp-message-notify@ip-172-31-45-160>
As it declared in RFC https://tools.ietf.org/html/rfc2822#section-2.2.3 long header bodies can be "folded" using CRLF+WSP. 
And some mail clients do that very thing. They split References header body which contains Message Ids by "\n ". The example of mail client where it can be reproduced is apps.rackspace.com
We created Sales Order in Odoo, sent this quotation to the client email. He replied with e-mail, and this email can't be matched with any existing message id and as result it's not attached to the Sales Order.

### CODE REVIEW

**Comment by okuryan** [comment]
@antonylesuisse , @odony  can you check this? I know that you are expeets in mail functionality.
And that is gap on Odoo because it is not fully comply with some RFC2822 standards. And that is causing missing of emails.

We already did deep investigation for our Enterpise Customer regarding this and had to do changes in our own Odoo repo. So he can use mailing with his rackspace mail provider. But it is better if it will go into official Odoo repo

**Comment by tde-banana-odoo** [comment]
@Julien00859 as I think you dig in this subject deep enough to know a lot of use cases ... what do you think of this one ?

**Comment by Julien00859** [comment]
Thank you for your contribution, indeed it seems that the reference can be split on several lines due to the automatic header folding.

From the RFC (thank you for the link !)

> Unfolding is accomplished by simply removing any CRLF that is immediately followed by WSP.

So email unfolding can be rather simple has shown by your contribution.

Beware that SMTP'S CRLF *must* be `\r` immediately followed by `\n`. Single `\r` or `\n` is not CRLF. 

> Messages are divided into lines of characters.  A line is a series of characters that is delimited with the two characters carriage-return and line-feed; that is, the carriage return (CR) character (ASCII value 13) followed immediately by the line feed (LF) character (ASCII value 10).  (The carriage-return/line-feed pair is usually written in this document as "CRLF".)

Also beware that SMTP's WSP is the space *and* the horizontal tab.

> Many of these tokens are allowed (according to their syntax) to be introduced or end with comments (as described in section 3.2.3) as well as the space (SP, ASCII value 32) and horizontal tab (HTAB, ASCII value 9) characters (together known as the white space characters, WSP), and those WSP characters are subject to header "folding" and "unfolding" as described in section 2.2.3.  Semantic analysis of structured field bodies is given along with their syntax.

Were you able to reproduce the problem on an earlier odoo version ? Say in v12 or in v11 ? We try to fix bugs at their root (or at least on the earliest supported version, here v11) and to forward-port the fix till the master branch so everyone profits from the fix.

Can you update your code to match CRLF and WSP ? Also don't forget to sign the [CLA](https://github.com/odoo/odoo/blob/13.0/doc/cla/sign-cla.md) :slightly_smiling_face:

**Comment by veryberry** [comment]
@Julien00859

> Can you update your code to match CRLF and WSP ? Also don't forget to sign the [CLA]

done

**Comment by Julien00859** [comment]
Hello @veryberry, thank you for the little changes and the CLA :)

We have some strict guidelines when it comes to commit messages. As it is mostly boring administrative stuff, I did it for you but as I couldn't push to your branch I duplicated it in our own organisation. No worry you're still the author and everything, I only did some boring git cleaning. There is a new pull request there #67991 that I'll merge as soon as our CI is green (tomorrow as it is right now 3 AM in Belgium).

Again, thank you for your contribution and the changes you made :)

**Comment by yelizariev** [comment]
To close as merged in https://github.com/odoo/odoo/pull/67991

**Pull request closed without merging**
