### PR TITLE
[FIX] mail: restore close of other menus on click of messaging menu

### PR DESCRIPTION
**Pull request by seb-odoo**
task-2278830

### CODE REVIEW

**Comment by seb-odoo** [comment]
Extracted from https://github.com/odoo/odoo/pull/53143

**Comment by seb-odoo** [comment]
@alexkuhn you see any way to test the interaction between different systray widgets without a tour?

**Comment by alexkuhn** [comment]
> @alexkuhn you see any way to test the interaction between different systray widgets without a tour?

I think you could add tests with `web.SystrayMenu`, which contains a registry `Items` with all systray menu items.

**Comment by seb-odoo** [comment]
Added test

**Comment by seb-odoo** [comment]
@alexkuhn runbot green, PR is done for me

**Pull request closed without merging**
