### PR TITLE
Master attributes tag luve

### PR DESCRIPTION
**Pull request by Williambraecky**

### CODE REVIEW

**Comment by esakarya** [comment]
when will be merge ? i am really need this.

**Comment by AntoineVDV** [comment]
Hello, I'm removing the assigned codeowner teams since the PR is still clearly in draft. They will get re-assigned when the PR is actually ready for review.

**Comment by esakarya** [comment]
when  will be merge ???

**Comment by esakarya** [comment]
Past 2 week still no action why?

**Comment by AntoineVDV** [comment]
Hello @esakarya

The follow-up of development tasks is done internally, not on PRs. Many reasons can explain why a PR is not updated over the span of a few weeks. We cannot make any promises for ongoing tasks, particularly those whose PR is in draft.

**Comment by esakarya** [comment]
Odoo e-commerce is a complete fiasco.

**Comment by esakarya** [comment]
I'm leaving Odoo, I think it no longer meets the needs of the industry.
Months past, odoo still didnt reaction about thoose big e-commerce problems.

**Comment by paju-odoo** [comment]
> I'm leaving Odoo, I think it no longer meets the needs of the industry. Months past, odoo still didnt reaction about thoose big e-commerce problems.

Hi @esakarya, I'm really sorry to hear that... 
We are working on this new feature in another PR for Odoo 16.4 (because we slightly changed the functionality in order to use the existing product tags) and hope it will be ready soon. It will definitely be part of v 17!

**Comment by esakarya** [comment]
Glad to hear that, 
but will you also deal with the performance issue in categories with too many products? 
Will you fix the seo addresses on the front side? 
Product and category seo addresses must be manageable, and the "shop" tag is really unnecessary.

**Comment by vava-odoo** [comment]
> but will you also deal with the performance issue in categories with too many products?

@esakarya https://github.com/odoo/odoo/pull/125187

**Comment by crazyshark2** [comment]
Hi yes seo url must change it should be updated as soon as possible, for example, the shop url makes it difficult for any site to switch to odoo. Most of the sites do not link to the shop link.

**Comment by esakarya** [comment]
Any news about multi info attributes ? and seo url improvements ?

**Comment by paju-odoo** [comment]
Hi @esakarya,
Product tags are will be available in the next version of Odoo. Regarding SEO improvements, this is also something that we which to do but not a priority at the moment, so I can't really give any timeline :)

**Comment by esakarya** [comment]
you cant done this with 17.
i have added another critical bugs to issu tracker
Odoo's ecommerce really really soo bad and need a lot of enchantments.
I dont Understant no one use this addon ?

**Comment by esakarya** [comment]
@paju-odoo @vava-odoo, can you tell me where this feature is?

**Comment by vava-odoo** [comment]
Hi @esakarya 
Maybe you're talking about this one: https://github.com/odoo/odoo/pull/124299
Cheers

**Comment by esakarya** [comment]
are you sure ? This is really bad, very difficult to manage. It does not appear in product filters. It is necessary to produce both the attribute and the label. I couldn't even figure out what it does in runbot. You've messed up something again.

**Comment by paju-odoo** [comment]
Hi @esakarya 

The new product tags are available in 16.4,  maybe you're not using that version of Odoo yet?

**Comment by esakarya** [comment]
man check my comments on pr  its not what we need. this is a bad feature.

**Comment by esakarya** [comment]
We simply asked you for a filterable information attribute field. You have done something terrible.

**Comment by esakarya** [comment]
I'm actually quitting odoo. I have been waiting for months for you to do as you first said. Nothing happens from Odoo. In all my tweets and wherever I can, I will always mention what a terrible e-commerce plugin you have.

**Comment by AntoineVDV** [comment]
Didn't you leave in June already?

**Pull request closed without merging**
