### PR TITLE
[ADD] BoM price report

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Check lap.  @KangOl @beledouxdenis Can we add the report like this in stable v9?  @qdp-odoo 

Current behavior before PR:

No report of cost price

Desired behavior after PR is merged:

In v8, we had a BoM price report in xsl format which was removed in v9.

As it is still needed, we added a report in the new qweb format, but this
time it is on the BoM instead of the product variant.

It also makes sense to have a similar report for v10 as the cost structure report
on the mo is for the real cost and not the standard cost.

### CODE REVIEW

**Comment by beledouxdenis** [comment]
It looks like a new feature, so to me no.

**Comment by KangOl** [comment]
Not really a new feature: 
> In v8, we had a BoM price report in xsl format which was removed in v9.

**Comment by beledouxdenis** [comment]
So this is a new feature for v9

**Comment by qdp-odoo** [comment]
because customers complained it is missing... so I guess, yes, it has to be added back in v9

**Comment by beledouxdenis** [comment]
"regressions" are allowed between major releases.

Customers complained about the fact we audit trail, we nevertheless did not restore it.

See with @antonylesuisse, but to me no feature should be added in stable releases, even more when we know the release has been released 9 months ago. No exception.

**Comment by wtaferner** [comment]
@beledouxdenis 
I am a customer and have several customers who are customer with Odoo and I actually would see it like @KangOl @qdp-odoo and @jco-odoo.

I guess regressions are somehow acceptable between major releases if a better solution is implemented and available...but MRP was not even part of the major refactoring of v9, so not a big issue to bring it back and imho it is not risky to add this report in stable again this way. 

Looking forward for an even better solution/implementation in v10 ;-) If this is not added again, it might vanish and then Odoo might argue for v10 it was not part of the product in v9 (therefore no regression), right? ^^

But honestly, if you really do not want to bring it back against all odds and do phase out certain functionalities you could actually contribute to OCA this extra report as a module in case you do not bring it back for the customer valid regression call.

For me this particular issue does actually not even matter now as it would be only for new customers who are not used to it yet...due to the big changes in accounting I mostly upgrade my customers for v10 only and directly, but at the latest then them and therefore I would call it a regression and shout out loud :-)

Just to give you another perspective for this internal decision ;-)

**Comment by beledouxdenis** [comment]
You wanted my opinion, you have it.

We shouldn't add a feature for ONE customer having a regression, especially 9 months after the release.

If only one customer complained in 9 months, it means that almost no one requires this feature, and we should therefore not re-add a feature that we will have to maintain on the long-term for only one customer, or just a few.

Instead, it should be done with customization on the customer database itself.

**Comment by wtaferner** [comment]
@beledouxdenis 
I see your point and it is valid imho, but maybe you are missing that a lot of customers might just skip v9 and even for migration it is normal to wait quite some time...anyway, I like that a feature like this exists in v8 and would like to see it in v9 and v10 as well ;-)

**Comment by jco-odoo** [comment]
Ok, but I made it in that way that it will be relevant for v10 also.

**Pull request closed without merging**
