### PR TITLE
[ADD] CodeSource CLA Agreement

### PR DESCRIPTION
**Pull request by PieterPaulussen**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by PieterPaulussen** [comment]
Company switch

**Comment by mart-e** [comment]
Hi,

As you have already made commits with this email (e.g. 50ee1c964b5), could you, instead, add a "up do ..." next to your name but keep it in dynapps CLA?
Thanks

**Comment by PieterPaulussen** [comment]
@mart-e Like so?

**Comment by mart-e** [comment]
Sorry, I made a typo  :wink: I meant write "up to" followed by the date or "until <date>", just to indicate that this signature is not valid anymore for _new_ commits but was still for previous ones

**Comment by PieterPaulussen** [comment]
@mart-e That clarifies it a bit! Thanks, I'll update it.

**Comment by mart-e** [comment]
Hello,

Thank you for the update, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

PS: seeing 99b4d9bf1d9e on the web interface, it seems github can not associate your new email with your account, check you have added your new email [in your settings](https://github.com/settings/emails)

**Pull request closed without merging**
