### PR TITLE
Full keyboard support

### PR DESCRIPTION
**Pull request by msh-odoo**
Task: https://www.odoo.com/web#id=29653&view_type=form&model=project.task&action=333&active_id=131&menu_id=4720
Pad: https://pad.odoo.com/p/r.0c5ba6366f795bcbcc1492db22bdffbb

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gdgellatly** [comment]
Hi,

I was testing for something else but noticed this bug.

Go to Sales Orders - tree view (runbot)

Issue 1: In the search box, I hit the down arrow, expecting a dropdown or something for search, instead it highlighted and scrolled first record.

Issue 2: Happy to have discovered this feature, I then hit down a few time and noticed it selected the next record.  About 8 down I decided to try Shift - Up arrow.  Again surprised it worked - nice.  Then while holding shift I hit down arrow - it left the last record (i.e. the top record as I scrolled back down) selected.  Then up again to try and fix, but now it deselected, even as records above and below were detected.

Issue 3: That black border box / tooltip is really ugly (ENTER to edit ESC to cancel) (although maybe thats debug mode)

Now the thing I was really excited to test that didn't work.  I changed the sales order view to make the order_line tree not editable (so it pops a form).  I couldn't find any shortcut for the Save and Close or Save and New Buttons - tried the obvious like ctrl-shift-enter, shift-enter, ctrl-shift-s etc.  Please, please these buttons need shortcuts.

**Comment by celm1990** [comment]
This PR are merge into V11 or only master branch????.

**Comment by fmdl** [comment]
When it is merged ?

**Comment by fmdl** [comment]
@msh-odoo do you think that that is possible to add an option user preference to remove pop_up. (after a few days you know how it's works).

in some case the popup is on some button:
image

**Comment by msh-odoo** [comment]
Work continues here:
https://github.com/odoo-dev/odoo/tree/master-keyboard-navigation-vsc

**Pull request closed without merging**
