### PR TITLE
[FIX] Typos including a parameter name

### PR DESCRIPTION
**Pull request by raf-odoo**
The report parameter `web_base_url` was written as `wen_base_url` at https://www.odoo.com/documentation/master/reference/reports.html.

### CODE REVIEW

**Comment by mart-e** [comment]
Thanks, good catch
@robodoo r+

BTW: for this kind of patch, you shoud use the odoo-dev remote

**Comment by raf-odoo** [comment]
@mart-e Alright, so it's best not to use the "Edit on Github" buttons for doc fixes when internal? What's the impact of doing that vs going through odoo-dev?

**Comment by mart-e** [comment]
> What's the impact of doing that vs going through odoo-dev

The other devs have access to your branch. I changed your commit message (to follow the [commit message guidelines](https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure)) so had to checkout locally your branch. As you were using your own remote, I had to add it locally. It's not super complicated but it's an unnecessary step. Also odoo-dev branches are available on the runbot.

**Comment by raf-odoo** [comment]
Roger. Thanks for the pointers!

**Pull request closed without merging**
