### PR TITLE
[FIX]Disabled CSRF protection for login and upload route.

### PR DESCRIPTION
**Pull request by rpi-odoo**
Disabled CSRF due to invalid CSRF Token in login and upload routes.

### CODE REVIEW

**Comment by odony** [comment]
Disabling the CSRF validation for these routes kind of defeats the purpose of the CSRF prevention mechanism, at least for the `/upload` route which does not take any other secret.

Possible options:
 - have the `/login` route return the CSRF token and reuse it for the `/upload` route
 - switch `/upload` and possibly `/login` to JSON instead of HTTP

Both options require changes to the `odoo.py deploy` command.

Actually I'm not sure why the `/base_import_module/upload` route itself is needed at all, and why the standard `/web/login` HTTP route does not work for this purpose...

@xmo-odoo what do you think?

**Comment by odony** [comment]
After investigating more with @xmo-odoo, switching the `/upload` route to JSON would make the file upload difficult, and the reason for the specific `/base_import_module/login` is explained in e49b8f5ae32b072c7a22763ad9472fcce9265f04: it makes error handling easier than if we have to parse the login page result for possible authentication errors.

@rpi-odoo The simplest solution seems to be:

  1. Disable CSRF for the `/base_import_module/login` route, as it's protected by the password anyway (as you did)
  2. Modify the `/base_import_module/login` route to return the CSRF token upon successful authentication, instead of "ok".
  3. Modify the `odoo deploy` command to grab the result of the `/base_import_module/login` call (the token) and pass it to the `base_import_module/upload` route. Do **not** remove the CSRF validation from the `/upload` route.

Thanks!

**Comment by msh-odoo** [comment]
@odony +1

**Comment by antonylesuisse** [comment]
@xmo-odoo can you take care of that one ?

**Comment by WHPODOO** [comment]
@rpi-odoo 20 character changes :laughing:  combine some work :laughing: 
shame

**Comment by xmo-odoo** [comment]
@odony base_import_module login now returns the request's CSRF token, which is used by the deploy command. The deploy command does not require the CSRF token, so that an updated local odoo can be compatible with a non-updated server (other way around is obviously unworkable)

**Comment by odony** [comment]
@xmo-odoo excellent, that looks good to me now, thanks!

**Pull request closed without merging**
