### PR TITLE
[ADD] l10n_jp

### PR DESCRIPTION
**Pull request by yostashiro**
The first attempt to add a template of Japanese chart of accounts!

@odony could you please check if there is any problem?

@qrtl

### CODE REVIEW

**Comment by odony** [comment]
Hi @yostashiro,

Thanks for the PR and the CLA signature! It looks quite good technically, but of course I can't say much about the Japanese-specific accounting data. Is it in use in production anywhere yet?

One question: I'm not too sure about using fiscal positions to map between tax included/tax excluded customers. Which kind of tax do you intend to set on the products by default, and how do you plan to assign the fiscal positions to customers? Doesn't the tax included/excluded choice depend on the manner in which the sale is conducted (SO/POS/...), rather than the customer?

I'll ask a quick review from @qdp-odoo too, and then we can merge your PR :-)

Thanks!

**Comment by yostashiro** [comment]
Thanks, @odony !

> Is it in use in production anywhere yet?

Yes, it has been used by some of our clients even though contents need to be adjusted according to each company's needs.

> One question: I'm not too sure about using fiscal positions to map between tax included/tax excluded customers. Which kind of tax do you intend to set on the products by default, and how do you plan to assign the fiscal positions to customers? Doesn't the tax included/excluded choice depend on the manner in which the sale is conducted (SO/POS/...), rather than the customer?

This is a good point.  We had to implement these fiscal positions in a project as sort of a workaround to achieve wanted results in POS sales and normal sales (from SO and invoice).

Wanted results:
- In POS sales, prices have to be tax inclusive.
- In normal sales, prices should be tax exclusive.
- In both cases, 8% consumption tax should be applied for each product sold.

And here are the given behaviors of Odoo:

Points | POS | Normal Sales
--- | --- | ---
Tax | Fiscal position **CANNOT** be used to adjust tax. | Fiscal position can be used to adjust tax.
Price | Pricelist assigned to POS is used, while **pricelist of the customer does not affect**. | Pricelist assigned to the customer is used.


So what we decided to do were as follows:
- Set **Consumption Tax (Inclusive)** to customer taxes of all products.
- Set **tax-exclusive** price to sale price of all products.
- Prepare a pricelist which does **sale price x 108%**, and assign it to POS.
- Assign **Tax Exclusive** fiscal position to all the customers.


I am not sure if there could have been a better way to handle this situation, but we did need those fiscal positions for above scenario, and it is up to each implementation case whether or not to use these fiscal positions.  We could remove them if they are rather confusing, although in my opinion we can leave them there since they do not do any harm by themselves.

**Comment by qdp-odoo** [comment]
seems fair enough to me :-)

thanks for the contribution

**Comment by odony** [comment]
@yostashiro Thanks for the detailed explanation. I guess the special fiscal positions do no harm indeed, although users who don't use a combination of POS + Sales might never need them, and might wonder about that. Do you think this deserves a small mention in the module description, or perhaps a link to this PR with your explanation?
(Note: You can also add a README.rst file inside your module and remove the `description` from the module manifest, and it will be directly taken in RST format from the README.rst file)

With Odoo 9 (actually as of saas-6: 22c8db7fcb5bd85e1e78d52466bfcb126e499c2f) the POS comes with an option to add taxes inside the prices (as if the prices were tax-included) so you will be able to simplify your setup.
pos_saas6_tax_incl

Everything looks good and ready to be merged, otherwise, thanks!

**Comment by yostashiro** [comment]
Hi @odony , thanks for your advice.  I just updated __openerp__.py with comments on fiscal positions.  Didn't create a README.rst file this time.  Thanks!

**Comment by odony** [comment]
@yostashiro Thanks a lot for the update and for your patience! I've just rebased and merged your PR in Odoo 8.0 at revision 9eeb5deab7b9a7f089cc6dc9a6c404ee9ddd2f70 (+ CLA sig at 6e2d6109089177be01b5f2d5718923a41e828663), so we can close the PR :-)

**Comment by yostashiro** [comment]
Great, thanks!

**Pull request closed without merging**
