### PR TITLE
[9.0][FIX] sale: vendor bill with a SO reference

### PR DESCRIPTION
**Pull request by rven**
Description of the issue/feature this PR addresses:

If the PO and SO have the same sequence, the source document of vendor bills and customer invoices could be the same.

Current behavior before PR:

The vendor bills are showing up on the sale order linked invoices.

Desired behavior after PR is merged:

The vendor bills should NOT be showing up on the sale order linked invoices.

OEA: M110725239-mvvpxyyt
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@qdp-odoo This small fix seems legit. Could you take a look ? 

Thanks.

**Comment by xmo-odoo** [comment]
Why not just add the type filtering directly in the `search`?

**Comment by tivisse** [comment]
@xmo-odoo Yes indeed. I ping @qdp-odoo to have an approval about the feature, not the code :)

**Comment by tivisse** [comment]
@rven 

Thanks for the feedback. It has already been fixed at 8c22c8b62578aedb6e639f107361df1bad69eae5

Have a nice day,

Yannick.

**Pull request closed without merging**
