### PR TITLE
[FIX] base: remove duplicated translations during import

### PR DESCRIPTION
**Pull request by mart-e**
Before this patch, importing a po file containing rows such as:
```
    #. modules: calendar, calendar_sms
    #: model:ir.model,name:calendar.model_calendar_event
    #: model:ir.model,name:calendar_sms.model_calendar_event
    msgid "Event"
    msgstr "Évènement"
```
Was failing with "ON CONFLICT DO UPDATE command cannot affect row a second time"

Both external ids `calendar.model_calendar_event` and `calendar_sms.model_calendar_event` target the same records (i.e. calendar_sms inherit from calendar.event model.

After external id resolution, two entries in the temporary translation table are duplicated.
In case of import with self._overwrite option, two update were done on the same row

Apply the duplication removal on type model (to target ir.model and ir.model.fields) and selection (if the 2 modules modify the selections of the same column)

Fixes odoo/odoo#32801

### CODE REVIEW

**Review by ghost — APPROVED** [review]
I was having the same issue when trying to install the sales module with the language set to pt_BR.
This fix worked flawlessly for me, thanks!

**Comment by JosDeGraeve** [comment]
Any update on this ??

I have also filed an OPW support ticket: #1998159

Tnx

**Comment by mart-e** [comment]
@JosDeGraeve this PR is for a specific case of manually importing a custom file. It is a bit tricky o I would like to have a second opinion before merging,
Your ticket seems a different problem (updating a single module), same symptom but probably different cause.

**Comment by JosDeGraeve** [comment]
Thank you for the update.  fwiw, the patch here in this PR did fix the issue i described in my ticket.
We do get lots of errors with this symptom, that's why we're eager for a fix.  If there is something we can do, please tell.

**Comment by mart-e** [comment]
The problem of this PR is that it hides an issue in the .po(t) file without actually solving it.
For your ticket with sale_subscription, is it possible you were using a package older than 0201d896d877c ?

**Comment by JosDeGraeve** [comment]
yes, that is exactly the case.  Our Dockerfile did remove all *.pot files and unused po files to save space.  I built an image with the pot files intact and that has fixed my issue.  My earlier test with the patch here, did include the pot files, because I bind-mounted the odoo source in my container.

**Comment by mart-e** [comment]
Ok that explains the issue. When reading a .po file, we try to find a matching .pot file

https://github.com/odoo/odoo/blob/43295c2a3741fb98f9c5d1a506652442efed0a82/odoo/tools/translate.py#L1058-L1068

We assume that the .po file may get outdated (this is often the case with regional versions of a language like nl_BE that are not on Transifex) but the .pot file is used as the reference and must be up to date.

**Comment by ahukkanen** [comment]
Same issue here. Applying this patch to the core fixes the issue.

**Comment by anedisi** [comment]
is there a reason why is this limited to only type 'model', 'selection',
when i have conflicts also on model_terms

**Comment by pedrobaeza** [comment]
Is this still applicable?

**Comment by obayit** [comment]
This is affecting me too. The patch works :)

**Comment by obayit** [comment]
I think this introduces other problems.
For example, when translating states there is a necessary duplication that gets deleted:

```
#. module: module_x
#: selection:model_x,state:0
#: selection:model_y,state:0
msgid "Canceled"
msgstr "تم الإلغاء"

#. module: module_x
#: selection:model_x,state:0
#: selection:model_y,state:0
msgid "Confirmed"
msgstr "تمت الموافقة"
```

Only the first state - canceled - gets translated.

**Comment by lathama** [comment]
@mart-e knowing that 12 is no longer updated, is this PR still needed?

**Comment by C3POdoo** [comment]
Dear @mart-e,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
