### PR TITLE
saas-14.3-toolbar-update-nby

### PR DESCRIPTION
**Pull request by Goaman**

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by rdeodoo** [comment]
`web_editor: update odoo-editor lib to commit b02537d` is a weird commit message no?

**Comment by dmo-odoo** [comment]
@rdeodoo I'm open to suggestions.

**Comment by Goaman** [comment]
I close this pr to merge the commits it with: https://github.com/odoo/odoo/pull/69159

**Comment by rdeodoo** [comment]
> @rdeodoo I'm open to suggestions.

Hope it didn't sound rude or anything, I was just surprised by the look of the commit message which is uncommon, looks like a forgotten wip commit message without the `[IMP]` or `[LIB]` 
It was more to triple check you noticed it if it was a mistake.

> I close this pr to merge the commits it with: #69159

PR-ception :D

**Comment by dmo-odoo** [comment]
@rdeodoo Well you were right, in fact. But it took me @JKE-be to understand that you actually meant the [TAG] was missing. Thanks for pointing it out, though, it had indeed slipped my attention. 👍

**Comment by rdeodoo** [comment]
You are welcome :+1: 

> But it took me @JKE-be to understand that you actually meant the [TAG] was missing
@JKE-be and I are the same person, but this is a secret so :shushing_face:

**Pull request closed without merging**
