### PR TITLE
[FIX] account: fix a division by zero in automatic entries

### PR DESCRIPTION
**Pull request by vin-odoo**
When opening automatic entries on a group of entries which sum equals to
zero, a division by zero occurs which cause a traceback.

This commit will fix the issue.

task id #2334872

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
@william-andre this is for you
@robodoo delegate=william-andre

**Comment by william-andre** [comment]
@robodoo rebase-ff
@robodoo r+

**Comment by william-andre** [comment]
@robodoo Well I don't like you either.

**Comment by smetl** [comment]
@robodoo rebase-ff r+

**Comment by d-fence** [comment]
robodoo r-
sorry, freeze time

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
