### PR TITLE
PATCH mayor valor on stock moves and assets

### PR DESCRIPTION
**Pull request by blaggacao**
@smetl While your big tax refactoring is still fresh... :wink: 
@nim-odoo You where also working on this, I guess...

Could you please consider adding this as well?

It fixes a bad behavior when a tax has no account set (meaning that it is included into the product destination account). In this case the quant was valued at the tax_excluded, while the very same invoice would charge the amount to the intermediary account. This way there will be always a tax difference on the intermediate account, while legally those taxes should be included into the inventory valuation.

This commit just adds a third value which sums all taxes that don't have an account set and therefore takes the correct value for inventory valuation...

This has been a true and long standing issue.

### CODE REVIEW

**Comment by blaggacao** [comment]
@kurkop Finally, maybe.... :wink:

**Comment by smetl** [comment]
It's ok to me but can you add this key in the documentation (under the compute_all signature) plz?

**Comment by kurkop** [comment]
Great! :+1:

**Comment by blaggacao** [comment]
@smetl Done, thanks!

**Comment by blaggacao** [comment]
@smetl I wonder, if there is anything missing to be mergable?

**Comment by smetl** [comment]
I'm waiting @qdp-odoo that will be back to the office on Monday

**Comment by smetl** [comment]
@blaggacao In fact, I think you should do the same behavior with the compute_all in point_of_sale

**Comment by blaggacao** [comment]
True, thanks!

**Comment by blaggacao** [comment]
Done, I left it as a stump, because there is no real use case at the moment.

**Comment by blaggacao** [comment]
@smetl Im waiting long time now for this to get merged, could you be kind?

**Comment by qdp-odoo** [comment]
wait a min, can you provide a detailed use case where this problem occurs? I'm not sure you're fixing it at the right place... Instead, maybe the value to book on the intermediate account should be fixed to exclude the tax amounts of taxes without an account set.

**Comment by blaggacao** [comment]
Actually, it's relatively simple:

A VAT which is not deductible (for any given product)*, does indeed augment the product's cost, and therefore must go into inventory valuation accounts ("at cost policy").

* that is, has no account for special registration.

Why is a VAT not deductible, some examples:
 - industry is close to the end of the value chain and the end customer is largely informal
 - Raw material for certain products which are not VAT-taxable and therefore do not give rise to the right of deduction.

I think, therefore, this solution is correct. Without this, the TAX as cost constituent would get stuck in the intermediate account and my inventory values would be incorrect / misleading.

**Comment by blaggacao** [comment]
@qdo-odoo A friendly reminder. This has been a long standing patch we carry for 3 years now... ;-)

**Comment by Yenthe666** [comment]
@blaggacao you actually messed up the ping. 😉 @qdp-odoo could you have a look at this one again too please?

**Comment by blaggacao** [comment]
Ticket Nr: 817014

**Comment by blaggacao** [comment]
The suggested work around in the ticket is hilarious (without offence, that's a proven fact)...

This is not only unsatisfying but a sensible topic, as tax calculation is involved which is under tight fiscal control down to the transaction level.

**Comment by Yenthe666** [comment]
@blaggacao now you made me curious about the response.

**Comment by blaggacao** [comment]
@Yenthe666 Out of respect of the support operator: He did not make his statement with the consideration of becoming public. But I might be able to share in a respectful manner by mail...

**Comment by Yenthe666** [comment]
😕 Hmmm.. that is not a very detailed/constructive answer. Anyway, you can keep that ticket going and respond that it is not an option with the reasons why. Keep it going untill the other person notices why you really can't do it.

**Comment by blaggacao** [comment]
Hm.. cannot post to the issue any more (403 forbidden)...
So dear Operator, I had some nice words for you to help you understand the problem, I'll have to share it here:
>Hi NAME,
no offense for publishing in the PR (anonymously). You feel my frustration. I know your side, I'm a support agent as well from time to time. Efficient communication is not always easy.
Down to the facts again:
Our beloved country (Colombia) requires us to report transaction level granularity for VAT and other taxes, so therefore neither
>- including it into the price (without a tax)
>- nor doing a periodical tax adjustment
is a viable option.
>I feel you overlooked the claim about "transaction granularity" in my first response to your work around.
>BR, David

**Comment by Yenthe666** [comment]
Hmm, I get 403 forbiddens throughout the whole Odoo forum too. See https://github.com/odoo/odoo/issues/23289

**Comment by blaggacao** [comment]
Wow, repeatedly I get answers supplanting the problem. This provokes anger and bad feeling. I'm not sure if it is mere incapacity, but to me it rather seems like conscientious supplanting, because I cannot imagine being more clear about the probelm. I cannot imagine someone would be able to state not having understood it after 3 times pointing out the critical part...

**Comment by blaggacao** [comment]
> you need to set the purchase price is being tax-included, at least when validating the purchase order. That way all the valuation will work as expected. You can still manually set the tax amount in the tax report manually at the closing date if it is required by tax authorities.

Well let's see what the response is of how this could possible satisfy the (authority's) requirement of granularity...

**Comment by qdp-odoo** [comment]
@sle-odoo this is a nice bug, although it -sadly- doesn't include any notion of anglo saxon or multi-currency....

**Comment by qdp-odoo** [comment]
I'd say: we don't need to consider the given PR. 

What we want, instead is to make sure the quant value doesn't include the taxes (this should solve the problem)
@lap-odoo is aware of this

**Comment by blaggacao** [comment]
> What we want, instead is to make sure the quant value doesn't include the taxes (this should solve the problem)

Doe you mean DOES include the taxes? Else, I fear we are not really on the same page. My (best of efforts) writing skill to express myself and the problem has come to an end, is there no chance whatsoever to do a short hangout about?

**Comment by qdp-odoo** [comment]
yes sorry about that... it was just a test to see if you were paying attention... :grin:

**Comment by blaggacao** [comment]
I'm on spot :wink: - Great to hear, though!

**Comment by blaggacao** [comment]
I'll delete this branch and prepare a refactor to master shortly...

**Comment by blaggacao** [comment]
This is replaced by (a hopefully cleaner) https://github.com/odoo/odoo/pull/26367

**Pull request closed without merging**
