### PR TITLE
[REF] web: update control panel doc

### PR DESCRIPTION
**Pull request by Arcasias**
Class documentation for the control panel component has been updated
to reflect the changes on the comparison menu.

Enterprise: https://github.com/odoo/enterprise/pull/11022

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo delegate=Polymorphe57

**Comment by Polymorphe57** [comment]
robodoo r+

**Comment by Polymorphe57** [comment]
robodoo r-

**Comment by Polymorphe57** [comment]
robodoo r+

**Pull request closed without merging**
