### PR TITLE
[ADD] Eric Lembregts to Dynapps NV CLA and Personal CLA

### PR DESCRIPTION
**Pull request by lembregtse**
Description of the issue/feature this PR addresses: Adding Eric Lembregts to DynApps NV CLA in master.

Current behavior before PR: Eric Lembregts is missing from DynApps NV CLA in master.

Desired behavior after PR is merged: Added Eric Lembregts to DynApps NV CLA in master.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `e...@lembregts.eu`
- you are signing the CLA _for_ the address `e...@dynapps.be`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by Yenthe666** [comment]
@lembregtse ohi there! Nice to see you around. How are you doing?
P.S: Don't forget to contribute. 😉

**Comment by mart-e** [comment]
@lembregtse both commits with the right email address, perfect!
Just one last thing: you have made the PR against master. Don't you want in earlier versions too?
The idea is to merge it in the lowest version you will contribute to (e.g. 10.0) and it will be forward-ported to upper versions (11.0, master and all the saas-X versions in between).
If you only wish to contribute to master (and future v12), this is fine.

**Comment by mart-e** [comment]
Forgot to close but was merged in master :)

**Pull request closed without merging**
