### PR TITLE
[FIX] project, sale_timesheet: common field between non-dependent mod…

### PR DESCRIPTION
**Pull request by bouvyd**
…ules workaround

The project and sale_timesheet modules both define a project_time_mode_id field on res.company but they are not dependent on each other. This causes problem because the first module that creates the field "wins" the xmlid and will delete the field on uninstall, regardless of the other module (which will then stop working until you do an update that will recreate the field).

To work around this in a stable version, we manually create xmlids for the field in each module; on uninstall the field will not be deleted if an xmlid still refers it (which will be the case if the other module is installed).

Inheriting fields from modules that are not dependent in a direct way (ancestor-child) is not supported, so normally you should use modularity to define the field in a parent module. Since 9.0 is a stable version, we need a small workaround.

### CODE REVIEW

**Comment by dbo-odoo** [comment]
@beledouxdenis si toi ou @odony ou @KangOl veut/veulent jeter un oeil

**Comment by odony** [comment]
LGTM, if you've verified that it actually works when uninstalling :-)

**Comment by dbo-odoo** [comment]
I wouldn't do a PR if it didn't :-) (but I guess asking never hurts)

**Comment by KangOl** [comment]
Seal Of Approval

**Comment by beledouxdenis** [comment]
Damien, are you still waiting something for this PR ?

**Comment by dbo-odoo** [comment]
nope, it flew under the radar

**Pull request merged**
