### PR TITLE
[REF] `o-autogrow` scss refactoring

### PR DESCRIPTION
**Pull request by karlosvalverde**
This commit deletes the class `o-autogrow` and replaces each instance of
it with a global Bootstrap class.

Task-2833725

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by karlosvalverde** [comment]
@stefanorigano @Brieuc-brd @xlu-odoo Could you please have a look into this PR? 😉

**Review by alexkuhn — APPROVED** [review]

**Comment by stefanorigano** [comment]
Ok, my only remark is that utility classes should be placed  after the component class(es) 👍

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
