### PR TITLE
[FIX] landed cost move price unit calculation

### PR DESCRIPTION
**Pull request by osoul-dev**
**Description of the issue/feature this PR addresses:**
Incorrect price_unit calculation of stock moves when there multiple landed costs (not landed cost lines) for the shipment.

**Steps to reproduce:**

- Create purchase order for Product A, with 100 qty and $100 unit price
- Receive the shipment
- Create landed cost with one cost of $100, and validate it.
- The current stock move unit price is $101, value $10100, landed_cost_value $100
- Create a new landed cost with one cost of $200, and validate it
- Now the stock move unit price is $104, value $10300, landed_cost_value $300

**Desired behavior after PR is merged:**
Following the example above, the end state should be unit price is $103, value $10300, landed_cost_value $300

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@sle-odoo We update the value in the same way as the remaining_value, so with what is left in stock.  Would not is be logical to do the same as with the price_unit and use the entire landed stock value on both price_unit/value?

**Comment by sle-odoo** [comment]
I guess it would be more logical, yes, though we don't really use the price unit field (see [here](https://github.com/odoo/odoo/blob/11.0/addons/stock_account/models/stock.py#L248)).

@osoul can you confirm the next operations do have the right valuation, even if the price unit field is wrong?

**Comment by osoul** [comment]
The main problem is when calculating corrections after modifying a done move (see [here](https://github.com/odoo/odoo/blob/11.0/addons/stock_account/models/stock.py#L103))

I also found out that value calculation is incorrect after adding additional landed costs on partially sold shipment. For example:

- Create a PO with 10 quantities and $100 price unit, and receive the shipment
- Here the value will be $1000, and remaining value is also $1000
- Create a SO with 5 quantities, and deliver the shipment
- Here the value will still be $1000 and remaining value will be $500
- Add landed cost of $100 and confirm it.
- Here the value will be $1050 and remaining value is $550. However, the value should be $1100 instead. The remaining value is correct.

I update the PR with the proposed fix for this issue as well.

**Comment by pedrobaeza** [comment]
Is this still applicable?

**Comment by C3POdoo** [comment]
Dear @osoul,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
