### PR TITLE
[FIX]: reports

### PR DESCRIPTION
**Pull request by lbellier**
- Company data was reset when you perform a update of base module (launch server with -u base option).

### CODE REVIEW

**Comment by clonedagain** [comment]
:+1:

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by clonedagain** [comment]
@mart-e would you agree?

**Comment by mart-e** [comment]
Hello,

Not really. Isn't it the same as what we do for all the views? They are not in noupdate so that in case of mess-up, you update the module and get everything back. If you wish to modify these you should make an inheritance, not modify the original.
I don't see why you would like a noupdate specifically here and not on all other templates.

**Comment by sle-odoo** [comment]
I agree with @mart-e

**Pull request closed without merging**
