### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by LucasLefevre**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/816e346fc [REL] 17.2.0-alpha.3
https://github.com/odoo/o-spreadsheet/commit/da3fd36ca [FIX] link: use updated secondary color
https://github.com/odoo/o-spreadsheet/commit/8f233b349 [REF] model: rename drawGrid method
https://github.com/odoo/o-spreadsheet/commit/cf1af1799 [MOV] composer: rename store test file
https://github.com/odoo/o-spreadsheet/commit/34c244576 [REF] composer: rewrite plugin with stores
https://github.com/odoo/o-spreadsheet/commit/f851c3cdb [REF] notification: rewrite with stores
https://github.com/odoo/o-spreadsheet/commit/78c973722 [REF] Popover: rewrite plugin with store
https://github.com/odoo/o-spreadsheet/commit/7e5469736 [MOV] find & replace: rename test file
https://github.com/odoo/o-spreadsheet/commit/471fd6c7b [REF] find & replace: rewrite with a store
https://github.com/odoo/o-spreadsheet/commit/74d6c4c44 [MOV] SelectionInput: rename test file
https://github.com/odoo/o-spreadsheet/commit/25d50701d [REF] SelectionInput: rewrite plugin with store
https://github.com/odoo/o-spreadsheet/commit/69f4397b6 [IMP] highlight: add highlight on CF/DV hover Task: 3571796
https://github.com/odoo/o-spreadsheet/commit/8d2ae4d21 [IMP] stores: add a way for store to draw on the canvas Task: 3571796
https://github.com/odoo/o-spreadsheet/commit/f0486f503 [IMP] highlight: draw highlight over cell borders Task: 3571796
https://github.com/odoo/o-spreadsheet/commit/0ea6a277f [REF] conditional_format: split list panel and cf preview Task: 3571796
https://github.com/odoo/o-spreadsheet/commit/1f29a5831 [ADD] store engine: a state management system for components
https://github.com/odoo/o-spreadsheet/commit/4f478b584 [IMP] formulas: allow lookup formulas to perform wildcard search Task: 3703048
https://github.com/odoo/o-spreadsheet/commit/81577bfa4 [IMP] build: add odoo-module ignore annotation Task: 3439583
https://github.com/odoo/o-spreadsheet/commit/1402030d4 [REF] clipboard: Rename handlers files
https://github.com/odoo/o-spreadsheet/commit/d7b90d4ef [REF] model: preserve default currency format
https://github.com/odoo/o-spreadsheet/commit/3c3d312f1 [REF] clipboard: refactor copy-paste handling Task: 3637334
https://github.com/odoo/o-spreadsheet/commit/76ce136d0 [FIX] export: transform unbound references Task: 3618912
https://github.com/odoo/o-spreadsheet/commit/fb47aa22f [FIX] export: transform unbound references Task: 3618912
https://github.com/odoo/o-spreadsheet/commit/05e1e1d4d [FIX] export: remove line returns in formula Task: 3618912
https://github.com/odoo/o-spreadsheet/commit/97c88097c [FIX] Grid: Support Mac shortcuts in `Grid` Task: 3707416

### CODE REVIEW

**Comment by LucasLefevre** [comment]
fw-bot ignore

**Comment by VincentSchippefilt** [comment]
robodoo override=ci/style

**Comment by rrahir** [comment]
robodoo override=ci/style

**Comment by rrahir** [comment]
@robodoo r+

**Pull request closed without merging**
