### PR TITLE
[FIX] mrp: prevent bom cycle

### PR DESCRIPTION
**Pull request by adwid**
To reproduce the issue:
1. Create two products A, B
2. Create two BoMs:
   - Product: A
     - Component: B
   - Product: B
     - Component: A
3. On one BoM, open the report "Structure & Cost"

Error: an Odoo Server Error is raised: "[...] maximum recursion 
depth exceeded while calling a Python object"

The error occurs because of the cycle between both BoMs. There is 
already a check for that in `:MrpBom.explode`:
https://github.com/odoo/odoo/blob/2a73890d304476833d76bac9a36ef92f12f267a3/addons/mrp/models/mrp_bom.py#L329
But it's too late in the flow. We should not be able to configure 
such BoMs.

OPW-3200969

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
FYI: some time ago I made a PR to avoid recursions in all ways: https://github.com/odoo/odoo/pull/53884

**Comment by adwid** [comment]
robodoo rebase-merge

**Comment by Whenrow** [comment]
robodoo delegate=adwid

**Comment by adwid** [comment]
robodoo r+

**Pull request closed without merging**
