### PR TITLE
[REF] sale: Faster product.sales_count

### PR DESCRIPTION
**Pull request by moylop260**
Versions: 10.0, 11.0, master (I don't know if <10.0)

# Description of the issue/feature this PR addresses:

Run `EXPLAIN (ANALYZE, VERBOSE, BUFFERS)  SELECT "sale_report"."product_id" as "product_id","sale_report"."id" as "id" FROM "sale_report" WHERE "sale_report".id IN (23324)  ORDER BY "sale_report"."date" DESC;`
Result:
  - [Execution time: 8205.306 ms](https://gist.github.com/moylop260/82c0e6bf3cd2ea8880e26593fc78e2ee#file-gistfile1-txt)

This query is called from [product._sales_count method](https://github.com/Vauxoo/odoo/blob/1aacc962620982528a3dfc90d2c1dd0027359375/addons/sale/models/product_product.py#L19)

This method is called from view [product.sales_count field from view](https://github.com/Vauxoo/odoo/blob/e29206a19e1eb93b92679de9c7fdc7ec58bcbbae/addons/sale/views/sale_views.xml#L593)

But the [action related to open the records](https://github.com/Vauxoo/odoo/blob/e29206a19e1eb93b92679de9c7fdc7ec58bcbbae/addons/sale/views/sale_views.xml#L577-L582) is opening `sale.order.line` table instead of `sale.report` view.

# Current behavior before PR:
`sale.report` is so slow spending 8 seconds to switch next product in the view form for our case.
`sale.report` combine too many tables and they are unneeded (to get a quantity counter of `sale_order_line`) like as:
 - currency rates
 - company
 - sale order
 - partner
 - pricelist
 - product template

Purchase uses `product.purchase_count` with the number of purchase orders
https://github.com/odoo/odoo/blob/9f847076530cf83d7198c16a341b4f5d29392ceb/addons/purchase/models/product.py#L36-L45

Sale uses product.sales_count with the quantity of products sold

It fix the product.sales_count ti number of sales order to be consistent

# Desired behavior after PR is merged:
Now is faster because is using directly `sale.order.line` and it's consistent with purchase orders count.

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
(y) @moylop260

**Comment by moylop260** [comment]
@pedrobaeza 
I know `read_group`, in fact, you can see my first commit using it to getting the sum of the `sale_order_line.product_uom_qty`

But like as my main description comment has or second commit message:
 - The purchase order is using the total order records (it not based on product_uom_qty).

Then I just copied and paste the same code from purchase for `product.purchase_count` method.

In this case that I'm not using a number to sum is not good to use `read_group`.
I mean, I need a combination of a `search_count()` combined with `read_group` that is not supported for the API.

We need `len(sale_order_lines.mapped('order_id'))`
And the read group using `product_id_count` uses `len(sale_order_lines)` instead
And we can't use `read_group(['product_id', 'order_id'], ['product_id'])` because `order_id` is not a `numeric` field (it is a FK)

Of course, I can use a query directly but it breaks the [do-not-bypass-the-orm](https://www.odoo.com/documentation/11.0/reference/guidelines.html#do-not-bypass-the-orm) guideline.

But currently this fix is faster than the original code and it is consistent with both methods. (purchase and sale).

NOTE: If we change this counter to `len(sale_order_lines)` instead of `len(sale_order_lines.mapped('order_id'))` we could use the faster `read_group` method, but it change the current logic and I don't know if it is a good idea for odoo team, but if the button is opening N sale_order_line records maybe is not a crazy idea show N in the counter.

**Comment by pedrobaeza** [comment]
@moylop260 I haven't dug enough, but I'm pretty sure that there's a way to do it with `read_group`. Any way, I let you to continue the way you think is more suitable.

**Comment by moylop260** [comment]
It is not. Without change the current logic (like as my last NOTE comment).

You are using a wrong example for this case, because you are using:
 - `read_group(domain, ['account_id', 'amount'], ['account_id'])`
where `amount` is a `numeric` field and here `order_id` is a FK field.

 - screen shot 2018-06-18 at 11 25 39

For a numeric column the api is using a sum, that is as well for your example.

But for this case it is precisely I want to avoid. (Compute a sum of quantities, because then we will need consider the uom_factor).

**Comment by moylop260** [comment]
For the record, the translation using sql code of my comment is that:

Using the following table `sale_order_line`:

| id | order_id | product_id |
|---------------|--------------------|------------|
| 1             | 10                 | 20          |
| 2             | 10                 | 20          |
| 3             | 10                 | 21          |
| 4             | 10                 | 22          |


Currently the logic is:
 - `SELECT product_id, count(DISTINCT order_id) FROM sale_order_line GROUP BY product_id`
(It is not supported directly from the API)

Result: 

| product_id | sale_count |
|------------|------------|
| 20          | 1 |
| 21          |  1 |
| 22          |  1 |


The logic supported without re-compute values is:
 - `SELECT product_id, count(*) FROM sale_order_line GROUP BY product_id`

| product_id | sale_count |
|------------|------------|
| 20          | 2 |
| 21          |  1 |
| 22          |  1 |

The difference is if you uses the same `product_id` too many times for the same `sale_order`.

Odoo team question:
Is valid for you If I change the logic like as the second one?
In order to get faster values and to be consistent with the result of the button opening the same N quanity of records.

**Comment by moylop260** [comment]
@odony What do you think about?

**Comment by max3903** [comment]
I backported the fix to version 8 for a customer with 360k products. The difference is significant. No more spinning wheel while opening the product templates and variants lists. The lists open in ~2 sec instead of 7.

:+1:

**Comment by pedrobaeza** [comment]
That's why I said of using the `read_group`, but over the `sale.order.line`, and avoiding the overhead of the `sale.report` SQL view.

**Comment by moylop260** [comment]
@max3903

Yes, the summary is that purchase has this way, and I’m using a standard for both because of it is master. (You can see the full thread to see the full reason)

But if you need the current bevavior you can use the first commit of this PR.

**Comment by pedrobaeza** [comment]
But do you think it's more relevant to count the number of purchase/sales orders than the quantity sold?

**Comment by moylop260** [comment]
@pedrobaeza 
Did you read my https://github.com/odoo/odoo/pull/25280#issuecomment-398110928
I’m using read_group for my first commit...
But there are other points about.

The matter is:
Purchase uses len(purchase_orders)
Sales uses sum(sale_orders.sale_order_lines.product_qty)

We should use the same bahavior for both cases.
IMHO Sales should use the same behavior like purchase: len(sale_orders)

Then I just copied the current code of purchase to sale.
It improves the performance as well.

And I’m following your last recommendation:
“””
Programmers waste enormous amounts of time thinking about, or worrying about, the 
speed of noncritical parts of their programs, and these attempts at efficiency
actually have a strong negative impact when debugging and maintenance are considered.

We should forget about small efficiencies, say about 97% of the time: premature optimization
is the root of all evil. Yet we should not pass up our opportunities in that critical 3%.
“””

**Comment by pedrobaeza** [comment]
The recommendation about checking performance things does nothing about this, as this is something about what is requirement. Homogeneity is good, but should we homogenize to the purchase approach, or to the sales one (getting a more performant option of course)? That's what I'm asking. What do you think?

**Comment by max3903** [comment]
@moylop260 Well my issue is about **how** we compute the total quantity sold, because my customer is live and is expecting the behavior to remain.

Since you made the pull request against master, I understand you challenge the consistency. To me, the total quantity sold/purchased is more important than the number of sales/purchase orders.

**Comment by moylop260** [comment]
I’m expecting the answer of an odoo member.

Currently, the sale button has a domain and a string like len(sale_orders) IMHO the button that open records should show the same number of records to open (like purchase)

But the point here is that odoo should decide it.

If they decide to use sale way then I’ll change purchase applying my first commit.

If they decide to use purchase way then this PR is well as it.

**Comment by moylop260** [comment]
@max3903
Yes, you are right
Could you review if the first commit works for you?

**Comment by pedrobaeza** [comment]
@moylop260 thanks for your answer. Yes, it's reasonable what you propose.

I have tagged the PR to see if someone can see it.

**Comment by max3903** [comment]
@moylop260 Here is my patch for version 8:
```
@@ -1285,12 +1285,17 @@ class product_product(osv.Model):
     _inherit = 'product.product'
 
     def _sales_count(self, cr, uid, ids, field_name, arg, context=None):
-        r = dict.fromkeys(ids, 0)
+        if not self.user_has_groups(cr, uid, 'base.group_sale_salesman',
+                                    context=context):
+            return
         domain = [
             ('state', 'in', ['confirmed', 'done']),
             ('product_id', 'in', ids),
         ]
-        for group in self.pool['sale.report'].read_group(cr, uid, domain, ['product_id', 'product_uom_qty'], ['product_id'], context=context):
+        r = dict.fromkeys(ids, 0)
+        for group in self.pool['sale.order.line'].read_group(cr, uid, domain, ['product_id', 'product_uom_qty'], ['product_id'], context=context):
             r[group['product_id'][0]] = group['product_uom_qty']
         return r

```

**Comment by moylop260** [comment]
@odony @mart-e What do you think about?

**Comment by gdgellatly** [comment]
@moylop260 I strongly disagree with your logic.  To me the number is the total number sold.  The number of orders is meaningless.  I don't care if the customer ordered 1 x 10 or 10 x 1.  It is still 10.

**Comment by gdgellatly** [comment]
@moylop260 Well semantics really. You are the one wanting to change behaviour using the argument that because purchases is one way, sales should be. I disagree. To me purchase and sales are different and the current, as implemented behaviour by Odoo makes sense.

**Comment by moylop260** [comment]
You agree using `len(purchases)` and using `sum(sales.product_qty)` like current odoo is it.
Right?

**Comment by moylop260** [comment]
FYI I just reverted the last commit since that the majority of people is using the current way.

**Comment by moylop260** [comment]
> @max3903 
@moylop260 Here is my patch for version 8:

FYI your patch is not considering different UoM.
If you are using the same UoM for all sale_order_lines then It will work as well!
But for other people using multiple UoMs won't work as well.

**Comment by jem-odoo** [comment]
The `sales_count` change in 12.0 (and so in master). Can you readapt your changes, or close this PR ?
Thanks

**Comment by mart-e** [comment]
@moylop260 does this one still makes sense? The code has changed a bit since and probably needs a bit of cleaning too (still leftovers from old-old api dcit magic).
@dbo-odoo could you have a look please? Is it something we can accept in master if the conflict is resolved or do you want to keep using the sale report?

**Comment by dbo-odoo** [comment]
Hi,

Unfortunately can't accept this, since we need to include POS sales in the count field (since 12.0) - these are included through an extension of the `sale.report` model in `pos_sale`. Basing the count on `sale.order.line` will miss these sales that should still be counted.

I will close this PR now, if you find a way around that problem, don't hesitate to get back to me through here.

KR

**Pull request closed without merging**
