### PR TITLE
Master choose lang url pla

### PR DESCRIPTION
**Pull request by pla-odoo**
Description of the issue/feature this PR addresses:
Task link: https://www.odoo.com/web?debug#id=32838&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
I just take a quick look on your branch.

But seems like you still have some mixte between code/request_lang.

Eg: the preferred langage will return the code, while you will check if it match a request_lang
https://github.com/odoo/odoo/pull/32552/files#diff-1098b36b5b4beaccedda81a4b67e22e1R299

url for seems also bugged:
image

How can you change the website_lang_code actually in the UI ?

Please can you add test that cover these case.
You can cherry-pick the commit 8557bcfa302de7aca4b5dadb35841cd52f9ebfff into your branch.
With this commit, you can easily check the url_for and use the Mock done in the test to add your own test.

thank you

**Comment by pedrobaeza** [comment]
Coming to this through codetriage.com. This has conflicts and seems very old. Is this still interesting?

**Comment by JKE-be** [comment]
@rdeodoo 
Can you check ? Can ne closed imo with thé refactoring done in v13

**Comment by rdeodoo** [comment]
Yep it was merged in saas-12.5

**Pull request closed without merging**
