### PR TITLE
[FIX] typo: field non existent now

### PR DESCRIPTION
**Pull request by cubells**
This field is now attachment_ids.

### CODE REVIEW

**Comment by cubells** [comment]
Related: #18101

**Comment by pedrobaeza** [comment]
They point to different Odoo versions (9.0 and 10.0). Isn't the problem also in Odoo 9.0?

**Comment by pedrobaeza** [comment]
OK, I see that this you have opened another PR for 9.0. You need to know that you only need to make the PR to the lower Odoo supported version (in this moment, 8.0 if it also applies), and then they put it on higher versions with their "merge upstream" mechanisms.

**Comment by pedrobaeza** [comment]
You can close this one then.

**Comment by cubells** [comment]
Ok, thanks @pedrobaeza for information

**Pull request closed without merging**
