### PR TITLE
[ADD] l10n_ch : add updated texes for 2018.

### PR DESCRIPTION
**Pull request by jao-odoo**
Task : https://www.odoo.com/web#id=39082&view_type=form&model=project.task&action=333&active_id=131&menu_id=4720 

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fclementic2c** [comment]
Please close this PR : 
- The rate is 3.7% (not 3.6%)
- tags, fiscal positions and purchases vat are missing.
- another PR (reviewd by community) is in progress: https://github.com/odoo/odoo/pull/21115

cc @open-net-sarl

**Comment by fclementic2c** [comment]
LGTM 
Thanks
+1

**Comment by fclementic2c** [comment]
@jao-odoo can you merge ?

**Comment by fclementic2c** [comment]
@jao-odoo @qdp-odoo Could you merge please. it is getting urgent. 
thanks

**Comment by qdp-odoo** [comment]
Note to myself: looks good so far. Should target the stable version, though

**Comment by qdp-odoo** [comment]
landed on all stable versions from 9.0 at revisions
https://github.com/odoo/odoo/commit/9bba7fea42be534fd100d809dfd1dc632ee9ace4

**Comment by fclementic2c** [comment]
la classe ! merci @qdp-odoo

**Pull request closed without merging**
