### PR TITLE
[REF] point_of_sale: remove custom `fuzzyLookup`

### PR DESCRIPTION
**Pull request by vlst-odoo**
In the `point_of_sale` there is a custom implementation of `fuzzyLookup`. In this commit we replace all it's instances with the version from `web`

Task: 3861712

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
Is it okay to close this?

**Comment by vlst-odoo** [comment]
> Is it okay to close this?

I am not keen on keeping this if we really think that the pos version is better, but it would be nice to at least know for which cases it is better. We could maybe add a unit test for it that tests the scenarios where the pos version is better than the web one. This way we would have a clear way to compare the versions

**Comment by caburj** [comment]
Okay. I'll leave that to you.

**Comment by vlst-odoo** [comment]
> > Is it okay to close this?
> 
> I am not keen on keeping this if we really think that the pos version is better, but it would be nice to at least know for which cases it is better. We could maybe add a unit test for it that tests the scenarios where the pos version is better than the web one. This way we would have a clear way to compare the versions

@pedrambiria Do you have some suggestions of strings for which one version is better than the other?
[This](https://github.com/odoo/odoo/blob/master/addons/web/static/tests/core/utils/search.test.js#L7-L28) is the kind of thing that I am thinking of

**Comment by pedrambiria** [comment]
@vlst-odoo I think we can proceed with removing it. The results are nearly identical, and the primary issue of sorting and fuzzy searching the barcodes has been resolved.

**Comment by caburj** [comment]
robodoo r+

**Pull request closed without merging**
