### PR TITLE
[CLA] signature for crece365

### PR DESCRIPTION
**Pull request by desdelinux**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by crece365** [comment]
Hi @mart-e your revision, please

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `50924836+crece365@users.noreply.github.com`
- you are signing _for_ the address `l...@peruswfactory.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by crece365** [comment]
> Hello,
> 
> Thank you for the CLA signature but it seems there is still an issue.
> 
> * you are signing _using_ the address `50924836+crece365@users.noreply.github.com`
> * you are signing _for_ the address `l...@peruswfactory.com`
> 
> The email address in the CLA must be the same as for the signature for the verification to succeed.
> You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.
> 
> Thanks

Thanks, I have properly configured my github again and made a new commit

**Comment by mart-e** [comment]
Thanks, looks good now, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
