### PR TITLE
[IMP] crm: add color picker widget

### PR DESCRIPTION
**Pull request by edil3ra**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by edil3ra** [comment]
test username change

**Comment by edil3ra** [comment]
test name

**Comment by edil3ra** [comment]
I cannot change my username because it's my github personal account, should I create a new one?
I can  only change the public name but my username still appears on comment

**Comment by awa-odoo** [comment]
@edil3ra You can keep your username, it's fine, as long as it's correctly showing when you commit (I just checked and it seems to work).

**Comment by awa-odoo** [comment]
@edil3ra "[IMP] crm: UX improvement" is a little too generic.

Maybe `[IMP] crm: add color picker widget on crm lead tags` ?

**Comment by awa-odoo** [comment]
@edil3ra Referenced task ID in commit message looks incorrect?

I have 2214268

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
