### PR TITLE
[CLA] Add/Remove: team member

### PR DESCRIPTION
**Pull request by atchuthan**
Add and remove team member in Corporate CLA

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
PR has no CI, merging didn't start.

**Comment by mart-e** [comment]
robodoo retry ?

**Comment by Xavier-Do** [comment]
robodoo retry

**Comment by mart-e** [comment]
robodoo retry again !

**Comment by Xavier-Do** [comment]
Look like a deterministic error in 11.0. I rebuild 11.0 to check if there is the same error.

**Comment by mart-e** [comment]
So will
@robodoo retry
succeed this time?

**Pull request closed without merging**
