### PR TITLE
[FIX] mail: mail_followers: add selected column in SQL query GROUP BY

### PR DESCRIPTION
**Pull request by partho222**
### ISSUE:
When executing the SQL query 

        SELECT fol.id, fol.res_id, fol.partner_id, fol.channel_id, array_agg(subtype.id)%s
        FROM mail_followers fol
        %s
        LEFT JOIN mail_followers_mail_message_subtype_rel fol_rel ON fol_rel.mail_followers_id = fol.id
        LEFT JOIN mail_message_subtype subtype ON subtype.id = fol_rel.mail_message_subtype_id
        WHERE %s
        GROUP BY fol.id%s ...

in `_get_subscription_data` method of the `mail.followers` model

**Found:**
`psycopg2.ProgrammingError: column "fol.res_id" must appear in the GROUP BY clause or be used in an aggregate function`

_Tested with: postgres (PostgreSQL) 11.14 on Ubuntu 18.04 LTS_

### CAUSE:
If we look at the logic of the query, we can see why this error occurs:

`SELECT fol.id, fol.res_id, fol.partner_id, fol.channel_id ...`
This says that for each row, we want the `id, res_id, partner_id, channel_id` from `mail_followers` table

but in
`GROUP BY fol.id ...`
This says we want one row for each unique `id` of `mail_followers`, no matter what else is different.

So, if there is more than `res_id, partner_id or channel_id` for the same `id` from `mail_followers` table (which won't happen as each row id is unique) BUT database would have no way of knowing which of those values to give us. So Postgres tells us to change the query.

### SOLUTION:
In this case, we know that every `id` corresponds to a single value of `res_id, partner_id & channel_id`, so we can just add them all to the GROUP BY clause

--------------------------------------------------------------------------------------------
Closes previous one
Re-created PR after merging of my CLA

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for your PR ! As usual with fixes in mail, could you write an unit test ? That failed without the fix and passes with it, in order to better understand what we are fixing. Strange that this issue did not raise previously, how is that happening ?

Side note: seems you have a rebase issue ... not sure why so much changes in restaurant.

Cheers,

**Comment by partho222** [comment]
@tde-banana-odoo sure I will try to describe a scenario where I found this issue & worked with the proposed solution.

BTW, I rebased using `git rebase --onto origin/13.0` and then pull the changes of my branch. As a result, changes committed to the origin after my commit comes to my branch, too

**Comment by C3POdoo** [comment]
Dear @partho222,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
