### PR TITLE
[FIX] website: separate colors of scrolled and overlay nav bars

### PR DESCRIPTION
**Pull request by Guillaume-gdi**
This commit allows to have really transparent navabars. Before this
commit when the user put transparency on his header, it did not become
transparent and the color was just mixed with white. Moreover, this
commit also allows to fix a bug a bit tricky:

To simplify the explanation below, note that option "C" means the Colors
option of the header (just below the Template option) and the option
"BHP" means the background option below Header Position.
By following these steps:
- Drop some block in a the page (to be able to scroll)
- Set a very transparent red as the value of C.
- The navbar is now in a pinkish color.
- Set the navbar position to "Over the content"
- With the option BHP, set the background color to a dark color.

=> When you are at the top of the page, the color is the one of the
option BHP. So far so good. Now when we scroll, the color of the navbar
is dark red. This is not what the user expects. In this configuration,
the C option should set the color of the navbar once the user has
scrolled. The colors should not be mixed.

Technical explanation of the problem:
Option BHP applies the color on the header element and option C sets the
color on the nav element. `NAV` element is a child of `HEADER` element.
So when `HEADER` has a color set by BHP and nav has a color set by C
which has transparency, the color of the `HEADER` influences the color
of the navbar when scolling. This commit allows to correct this.

task-2904507

### CODE REVIEW

**Comment by Guillaume-gdi** [comment]
In fact this PR should be for master because we will not change the color of header in stable versions.

**Comment by Guillaume-gdi** [comment]
This will probably need an upgrade script to prevent header style changes. I will do it when the idea of this PR will be validated.

**Comment by rdeodoo** [comment]
@robodoo delegate=@detrouxdev

**Comment by detrouxdev** [comment]
@robodoo r+

**Pull request closed without merging**
