### PR TITLE
[WIP][FIX] base: report generation error

### PR DESCRIPTION
**Pull request by nim-odoo**
In very specific cases, a segfault arises in wkhtmltopdf, when it is
computing the number of pages. It is trying to know ahead of render how
many pages are needed but the computation uses a default viewport-size
that is very small, making the computation wrong. It can either foresee
more pages than it needs and the report looks good or not enough pages
and there is a segfault when rendering the data without pages to render
on.

To fix this, we fallback by adding a `--viewport-size` argument so that
it will more likely compute more pages than it needs.

Closes #24895
opw-1850777
opw-1850289

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@nim-odoo does this something to do with https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2711, and in concrete with the reproducible case we get in https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2711#issuecomment-389429960?

**Comment by pedrobaeza** [comment]
Yeah, I know it's not the ideal, but I don't think you will get this working in current version. The history of reverts says that you fix something for breaking another thing. Maybe you just can recommend the newer version when this problem happens. It's not mandatory, but if you don't want the problem, then use the new one. There's another big issue floating around that old version that is the dpi resolution parameter, which is going to be fixed homogeneously in this coming version, so another reason for switching to the new one, but again, this upgrade will have some impact on pixel perfect reports.

**Comment by gdgellatly** [comment]
@nim-odoo what I do rather than viewport size is increase the bottom margin
args by 2mm until it works.  Usually only one retry.

**Comment by gdgellatly** [comment]
@nim-odoo ignore, I thought pedro said the viewport thing wasn't working.

**Comment by nim-odoo** [comment]
Won't fix at the moment, we'll see if the issue occurs on a regular basis. In that case, we'll consider the best workaround.

**Pull request closed without merging**
