### PR TITLE
Introducing the Swiss VAT taxes and fiscal positions for 2018

### PR DESCRIPTION
**Pull request by open-net-sarl**
This PR adds the new Swiss VAT taxes and fiscal positions to the current Swiss chart template, to allow any new chart of account to include the new elements.

Before PR: any new chart of account will include the taxes that are valid till the end of 2017.
Desired behavior after PR is merged: any new chart of account will also include the taxes and fiscal positions that are planned for 2018.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

I let the localization team review for the content (cf #20416) but, in the mean time, it seems there is still an issue with the CLA.

- you are signing _using_ the address `jae@o...ch`
- you are signing _for_ the address `cyp@o...ch`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by open-net-sarl** [comment]
@mart-e Thanks for your feedback.
But now that the ci/runbot has failed, I need to know if there's something I can do.

Thanks.

**Comment by mart-e** [comment]
@open-net-sarl false positive, now it's green ;-)

**Comment by fclementic2c** [comment]
LGTM
Thanks

**Comment by fclementic2c** [comment]
can you merge it ?

**Comment by treviser** [comment]
This is getting urgent, I believe. Is there any chance to get this merged and also to get a description on how to apply the new taxes?
Thanks very much for a feedback.

**Comment by mart-e** [comment]
Hello,

Have you checked the following announcement?
https://www.odoo.com/blog/odoo-news-5/post/switzerland-updated-vat-for-january-2018-466

I believe it was already done at 9bba7fea42be534fd100d809dfd1dc632ee9ace4 or do you need something else?

**Pull request closed without merging**
