### PR TITLE
[FIX] mass_mailing: precompute email_from based on alias domain

### LINKED ISSUE #151310: [17.0] Email Marketing Send From Not Automatically Updating
Impacted versions:
17.0 16.0 15.0

'Send From' email address (email_from) does not automatically update according to the dedicated mail server settings. We have set up a dedicated outgoing mail server specifically for email marketing purposes. 
We want all marketing emails to be sent from a fixed email address (e.g., notification@example.com). However, the system currently requires manual intervention to trigger the 'Send From' address update.

Steps to reproduce:
1, Create a dedicated out going mail server for email marketing. Then `From Filtering` value is set. (eg. example.com)
2024-01-26_18h44_21

2, Set `Default From` to the company.(eg. notification@example.com)
2024-01-26_18h51_20

3, Enable `Dedicated Server` from Settings and set the mail server created in Step 1.
2024-01-26_18h53_42

4, Create a new record for Email marketing, user's email address is set as the Send From.
2024-01-26_18h56_35

5, Once you set it up on another mail server and put it back again, the Send From will be updated as notification@example.com.
2024-01-26_18h57_01

`email_from` is computed by `_compute_email_from`. however, this occurs because only calculated when the `mail_server_id` is updated
https://github.com/odoo/odoo/blob/16251091dcc5693c801d6e34325daef43c2c7e1f/addons/mass_mailing/models/mailing.py#L255-L271
The `email_from` is updated when the `From Filtering` value set in the out going mail server and the `Default From` domain of the company are the same.
https://github.com/odoo/odoo/blob/16251091dcc5693c801d6e34325daef43c2c7e1f/addons/mass_mailing/models/mailing.py#L268-L269

Current behavior:
The 'email_from' is only computed when 'mail_server_id' is updated, which requires manual intervention to change the mail server settings temporarily for the update to take effect.

Expected behavior:
If you have a dedicated mail server set up and also have `_compute_email_from` set up to update the value, it should also have the updated value when it is created.
This means that right from the creation of a new marketing email, the 'Send From' should be set to the configured email address (e.g., notification@example.com),

Support ticket number submitted via odoo.com/help (optional):
OPW  #3704715

@qrtl

### PR DESCRIPTION
**Pull request by jorv-odoo**
Backport of original PR
https://github.com/odoo/odoo/pull/152655 in 17.0+

opw-3704715
Fixes #151310

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jorv-odoo** [comment]
@tde-banana-odoo here's the backport to 16.0+. Checks are green. So if everything looks fine r+ and tell the forward bot to stop at 17.0 [excluded) ;)

**Comment by tde-banana-odoo** [comment]
@fw-bot up to 17.0

**Comment by tde-banana-odoo** [comment]
@fw-bot up to saas-16.4

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
