### PR TITLE
[MERGE] project: include web_editor.assets_wysiwyg in project.webclient

### PR DESCRIPTION
**Pull request by dmo-odoo**
Since [#118966](https://github.com/odoo/odoo/pull/118966), the `web_editor.assets_wysiwyg` assets are not lazy loaded anymore and therefore need to be included in `project.webclient`.

However, doing so without additional changes would have meant loading the legacy bundles in web when website is installed because website has utils that have not been converted to owl yet and thus require legacy stuff.

To prevent that, this PR first moves the `prompt` util out of website utils and into its own file because it is the only website util that still actively requires legacy stuff. This move was made in multiple commits with special merges so that the change history is kept in both files.

task-3434068

### CODE REVIEW

**Comment by dmo-odoo** [comment]
Somehow the order in which the commits are displayed in `tig` in case of merges is different than in GitHub, hence why the (2/5) appears before (1/5) as I tailored it locally for the `tig` order, not knowing GitHub would behave differently.

**Comment by dmo-odoo** [comment]
@robodoo rebase-merge

**Comment by xavierbol** [comment]
Hello @dmo-odoo ,

It does not seem to work in that PR, unfortunately. 🙁 

I have the following error:
image

**Comment by xavierbol** [comment]
You can reproduce the issue by doing the steps mentioned in that [comment](https://github.com/odoo/odoo/pull/129785#issuecomment-1651851852) 🙂

**Pull request closed without merging**
