### PR TITLE
Adding BYN to currenciest list

### PR DESCRIPTION
**Pull request by sergeiruzkiicode**
From 2016-07-01 BYN is new currency sign for Belarus
See https://en.wikipedia.org/wiki/Belarusian_ruble

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sergeiruzkiicode** [comment]
Runbot error:

i have on line 174 in odoo/addons/purchase/tests/test_stockvaluation.py

self.assertAlmostEqual(move1.price_unit, price_unit_usd) 

not 

self.assertEqual(move1.price_unit, price_unit_usd) like runbot has

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `s...@icode.by`
- you are signing _for_ the address `s...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by sergeiruzkiicode** [comment]
@mart-e oh, sorry for that.

**Comment by mart-e** [comment]
Thanks, merged in 10.0, will be forward ported to 11 soon.

I have kept the previous currency as people that were using Odoo before 2016 need to keep the accounting in the old currency

53e221fc169 [FIX] base: adding BYN to currenciest list
1ac7257dd24 [CLA] signature for sergeiruzkiicode

**Pull request closed without merging**
