### PR TITLE
[FIX] l10n_it_edi: handle negative unit price

### PR DESCRIPTION
**Pull request by jbw-odoo**
Before this fix negative aml unit prices were systematically set to positive in the edi xml generating inconsistencies.
Task: opw-2963947

### CODE REVIEW

**Review by dbkosky — APPROVED** [review]
Looks good to me

**Comment by jco-odoo** [comment]
@jbw-odoo By quickly checking if the tests still pass, I came across this Depreciationwarning: (also the tests do not pass in the DDT, because you would need to register, but that has nothing to do with this PR)
2022-09-21 08:42:27,304 456849 WARNING 14it py.warnings: /home/odoo/source/odoo/addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py:337: DeprecationWarning: RedirectWarning method 'post()' is a deprecated alias to 'action_post()' or _post()
  cls.negative_price_invoice.post()

**Comment by dbkosky** [comment]
@jco-odoo can we merge this?

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
