### PR TITLE
[IMP] web,*: Upgrade Bootstrap to version 5.3

### PR DESCRIPTION
**Pull request by pparidans**
*: hr_attendance, http_routing, im_livechat, mail, mass_mailing,
mrp_subcontracting, point_of_sale, pos_self_order, project, snailmail,
spreadsheet, survey, web_editor, website, website_slides

This commit upgrades Bootstrap library from versison 5.1.3 to 5.3.3.

In a nutshell, the big changes are :
- A lot more CSS custom properties all over the place
- ScrollSpy has been completely rewritten (moving from onscroll listener
  to IntersectionObserver)
- Support for color modes (aka. light/dark modes ; but currently
  disabled as we don't take advantage of it yet).

Note: even though the new color modes have a lot of potential, as we
don't take advantage of it yet, the built-in dark mode is currently
disabled. It should be enabled once actually implemented.

This commit also removes the `.bg-text-*` helpers backported from
Bootstrap 5.2 (and now built-in) and an override of the
`Tooltip.prototype.setElementContent()` function as the Tooltip
component now delegates the its content assignation to the
`TemplateFactory` class.

References:
- https://getbootstrap.com/docs/5.3/migration

task-3600468

Related PR: https://github.com/odoo/enterprise/pull/59122

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pparidans** [comment]
@odoo/rd-security kindly requesting an override here :wave: 

In a nutshell, this PR upgrades Bootstrap from version 5.1 to 5.3.
In Bootstrap 5.2, they introduced the `TemplateFactory` helper (cf. commit [1]) for the templating needs of the tooltip/popover, which itself uses it's own sanitization before assigning HTML content. It should be then pretty safe to use as is.

[1]: https://github.com/twbs/bootstrap/commit/94a596fbcb1011ba990da2078ba7e20b39dba2d9

**Review by rfr-odoo — APPROVED** [review]

**Review by aab-odoo — APPROVED** [review]

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by rfr-odoo** [comment]
> @pparidans are we using it? The sanitation of this, not at all suspiciously named, method seems optional
> 
> ```js
>     _maybeSanitize(arg) {
>       return this._config.sanitize ? sanitizer_js.sanitizeHtml(arg, this._config.allowList, this._config.sanitizeFn) : arg;
>     }
> ```

The configuration of the sanitation for Bootstrap is in the file `addons/web/static/src/legacy/js/libs/bootstrap.js`
We have added some rules upon the default one.
c.f.: https://getbootstrap.com/docs/5.3/getting-started/javascript/#sanitizer

**Comment by pparidans** [comment]
> > We have added some rules upon the default one.
> 
> I see you allow `style` attribute which seems fishy. I also see we can use a custom sanitizer like DOMPurify, would that work?

About the `style` attribute, yes it's part of the whitelisted ones. It was done so in https://github.com/odoo/odoo/commit/6991f300cd0fb35564e1249e4b407463162c689e .

About using a custom sanitizer, although not the case currently, yes the Bootstrap documentation describes it (cf. link pointed out above) and I guess it should work... but not tested so fare.

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: innerhtml set to sanitized content

**Comment by Xavier-Do** [comment]
Hello, it looks like it broke most single module build https://runbot.odoo.com/runbot/build/61548082. Can you take a look asap? :)

**Comment by pparidans** [comment]
> Hello, it looks like it broke most single module build https://runbot.odoo.com/runbot/build/61548082. Can you take a look asap? :)

:sob: 
Looking at it :ok_hand:

**Pull request closed without merging**
