### PR TITLE
[CLA] JorgeJuarezM

### PR DESCRIPTION
**Pull request by JorgeJuarezM**
[CLA] JorgeJuarezM

### CODE REVIEW

**Comment by JorgeJuarezM** [comment]
@robodoo +1

**Comment by JorgeJuarezCasai** [comment]
@robodoo any update?

**Comment by JorgeJuarezM** [comment]
@robodoo any update?

**Comment by JorgeJuarezM** [comment]
@C3POdoo any update for this CLA?

**Comment by JorgeJuarezM** [comment]
@mart-e hello i don't know how to make to contribute to odoo, this PR have several weeks and is just a CLA, you can help me?

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by JorgeJuarezM** [comment]
@mart-e I have seen that this "PR" has failed some checks, what can I do to solve it? I don't understand what the fault is.

**Comment by JorgeJuarezM** [comment]
is impossible!!

**Pull request closed without merging**
