### PR TITLE
[FIX] sale_stock : S/N are wrongly show

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**

The current code have some issue:
- the qty in S/N tab can be upper than the quantity on invoice
- the field `write_date` of aml is used, but it is not relevante to use
- the UoM used is the main product UoM and not the UoM of SML
- if there are different UoM used for the same product (two different SOL with two UoM), the S/N table show only one
- if the invoice have an invoice_date before the delivery, no S/N are show (case when the invoice policy is on quantity ordered)

image

https://user-images.githubusercontent.com/16716992/148085227-493bc554-139b-435b-8226-80a316a5c703.mov

@simongoffin @amoyaux 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@thcl-odoo

**Comment by fmdl** [comment]
@adwid @wtaferner @Whenrow I have rewrite the function, because lot of cases doesn't work (and use the field write_date to sort invoice is really wrong).

**Comment by wtaferner** [comment]
@fmdl 
As written before, the black magic needs some cleanup, so I hope you have fixed it in the end 😉 in my opinion as long as there is no persistent and dedicated connection between a sml and invl it will always just try to connect information based on black magic. There are just too many use cases to cover to indirectly retrieve this information accurately...it is even impossible I would say.

Count me in for every improvement based on black magic winning over the other magic introduced before 😝

**Comment by fmdl** [comment]
@wtaferner my fix match all as possible. Try it and tell me if the black magic works better :-)

**Comment by wtaferner** [comment]
@fmdl 
I can imagine and I agree that the write date is very unreliable and your approach looks from a quick review better, but I am not the one to "judge", review or even merge. Keeping fingers crossed that the best black magic will prevail 😉

**Comment by adwid** [comment]
@fmdl Before reviewing the fix, can you change the target of the PR to 13.0 and update the branch, please ?

**Comment by fmdl** [comment]
@adwid move in 13.0

**Comment by wtaferner** [comment]
@adwid 
Awesome to see that you are pushing forward on this. Any idea when it will be ready to be merged?

**Comment by adwid** [comment]
Work is in progress on #85115
I think the fix is now ready, so I'm waiting for few reviews and then we should merge it

**Pull request closed without merging**
