### PR TITLE
[I18N][FIX] base: fix Lithuania translation to Slovak

### PR DESCRIPTION
**Pull request by Rad0van**
Description of the issue/feature this PR addresses: current translation is bastardized (missing one letter) translation of Latvia (sk: Lotyšsko).

Current behavior before PR:

Desired behavior after PR is merged: Correct translation of Lithuania

This has gone unnoticed from 10.0 to current...

### CODE REVIEW

**Comment by Rad0van** [comment]
@jbw-odoo please have a look. This affects all versions from 10.0 to current

**Comment by mart-e** [comment]
Hello @Rad0van,

Thank you for your contribution but the version 10.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch (15, 16 and 17.0 at the moment).
Moreover, the translations are handled on Transifex, not Github.

Best,

**Comment by Rad0van** [comment]
> Hello @Rad0van,
> 
> Thank you for your contribution but the version 10.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch (15, 16 and 17.0 at the moment). Moreover, the translations are handled on Transifex, not Github.
> 
> Best,

Hello @mart-e ,

as noted in the description the wrong translation is still present in all following versions and should be fixed. Can you advice on how to do this properly? Should I use Transifex on oldest supported version and expect the fix to bubble up to all the following? Or should each one be fixed individually? Thanks a lot.

**Comment by mart-e** [comment]
@Rad0van the process is to go on each version on Transifex and correct it.
I have done it but for the record, you can go to the first occurrence at https://app.transifex.com/odoo/odoo-15/translate/#sk/base/333306455?q=text%3ALithuania
and you can check on the “Suggestion” tab to access all other occurrences.

**Pull request closed without merging**
