### PR TITLE
[FIX] website_event: fix end date weekday on event registration page

### LINKED ISSUE #39698: Event: end weekday shown on event page is wrong
Impacted versions:
Odoo 13

Steps to reproduce:
1. create event that spans mulitple days
2. visit event page on website

Current behavior:
weekday of end date is wrong, same as weekday of start date

Expected behavior:
weekday is accurate, matching the end date

Screenshot link:
http://674841-13-0-12a2d1.runbot19.odoo.com/event/hockey-tournament-2020-11-05-2020-11-06-6/register

odoo

### PR DESCRIPTION
**Pull request by fr3aker**
fixes #39698

### CODE REVIEW

**Comment by Feyensv** [comment]
@tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for your input. Could you update your commit message according to our guidelines https://www.odoo.com/documentation/13.0/reference/guidelines.html#git ? You may ping me once done :) .

Thanks,

**Comment by fr3aker** [comment]
@tde-banana-odoo commit messages updated

**Comment by tde-banana-odoo** [comment]
Thanks for your input !

@robodoo r+ rebase-ff

**Pull request closed without merging**
