### PR TITLE
[FIX] web_editor: align image to the right

### PR DESCRIPTION
**Pull request by bso-odoo**
Align images to the right by using an auto left margin.

Steps to reproduce:
- Drop a "Columns" block.
- Select an image.
- Resize image to 50%.
- Align image to the right.
=> Image did not get aligned to the right.

This PR also makes it possible for icons to be aligned.

task-2841127

### CODE REVIEW

**Comment by bso-odoo** [comment]
@odoo/rd-framework-editor Is there any chance this fix on 13.0 which even touches summernote might pass ? Or should I find a solution for a futher version instead ?

**Comment by dmo-odoo** [comment]
@bso-odoo I'm not sure what you mean by "might pass" ?

- If you mean "would we r+ this fix": No I would not because I think it is too dangerous to fix editor bugs in 13.0 since it has almost no test coverage. It would be way too easy to break another behavior without knowing it. Also, 13.0 is not supported anymore.
- If you mean "will it be possible to foward port this fix to 15.0 onward": Since all the files related to summernote have been removed and the underlying editor is completely different, there is now way a fix in any of these files can be forward ported to 15.0 onward. If the bug can be reproduced on 15.0, I would advise to directly fix the bug in 15.0 as it is the first version with acceptable test coverage.

**Comment by rdeodoo** [comment]
@bso-odoo Based on last message from DMO, I guess find something else than fixing the lib
Also, this need to retarget 14.0
We can discuss it if this seems to difficult to fix in 14.0 (to fix it only in 15.0)

**Comment by qsm-odoo** [comment]
> I guess find something else than fixing the lib

I don't think @bso-odoo is tweaking the lib :wink: 

@bso-odoo For editor problem before 15.0, I guess we are on our own :wink: We'll take the risk if we judge the fix is worth it. In this case, the fix seems safe enough (did not check deeply yet) so let's try and keep it: just retarget to 14.0 and test over there then I'll eventually have a look :+1:

**Comment by dmo-odoo** [comment]
> For editor problem before 15.0, I guess we are on our own

Note that this is not

**Comment by qsm-odoo** [comment]
@dmo-odoo 

> Note that this is not

So you are fixing bugs in 14.0? I did not mean that in a bad way, just honestly though that for 14.0 editor problems, we had to decide if we fix them in the website team and you worked only in 15.0 and above (like you seemed to say in your previous message too actually)?

Why are you closing this in the end? You really don't think it is worth merging? Or is there more discussions with @bso-odoo that I don't know about? :thinking:

Personally, with proper reviewing (which I did not do yet), I think the value/risk ratio is way higher than I would allow myself to merge here: it does not seem to be about a change in behavior, just a very specific fix to make a non-working use case work and leave other use cases untouched (and at worst breaking them but those are non critical things).

**Comment by dmo-odoo** [comment]
Ouch @qsm-odoo, looks like Github really messed up ! My comment has been truncated and the PR has been closed as if I clicked on the "Close and comment" button, which I didn't. Weird. Sorry for the misunderstanding.

We are indeed not fixing bugs in versions prior to 15.0. The original content of my comment was pointing the fact that sometimes the best thing to do for editor bugs in versions prior to 15.0 is _not_ to fix the bug. Because editor versions prior to verision 15.0 are so poorly tested, the risk/gain ratio of fixing bugs in those versions is not very permissive IMO. It's not because we're lazy or that we don't care about the users or whatever, but because you can very easily break another behavior by trying to fix the wrong one. It is very hard to reach a proper level of certainty that you're not breaking anything else in the absence of a strong test suite. Basically, I think it's sometimes better to let down one customer than taking the risk of potentially letting down much more customers, especially if those customers were previously happy since the system used to work for them, as you might never know what behavior you'll risk breaking. 

Note that I'm not talking about the fix in this PR specifically. What triggered my original comment (savagely truncated by Github) was the phrasing of "we're on our own", like if we were doing something bad because we _should_ be fixing those, so I wanted to explain a bit more our position, give some insights basically, about the technical reasons _why_ we advise against fixing editor bugs in versions prior to 15.0 unless they traceback or freeze the entire edition.

**Comment by qsm-odoo** [comment]
@dmo-odoo I know all of that. I just think that, considering we normally should support 14.0, it's still worth checking the value/risk ratio case by case rather than automatically discarding what is not a freeze or a traceback. And I probably think the value/risk ratio in this case is higher than you think it is (even with a not as strong testing suite) :shrug: Feels like small value (but still a bug without it), very small risk (but again, not sure, not tested nor reviewed properly yet, I am focusing on tickets and other criticical things right now).

> the phrasing of "we're on our own"

There is really nothing bad about it in my mind. It was merely stating a fact: we handle 14.0 fixes :wink:

**Comment by bso-odoo** [comment]
@qsm-odoo Rebased on 14.0 - only kept the image and icon alignment commits.

**Review by qsm-odoo — APPROVED** [review]
Sorry for the delay on this one :cry: 

@robodoo rebase-ff r+

**Pull request closed without merging**
