### PR TITLE
allow return pickings to reconcile negative quants

### LINKED ISSUE #9906: 8.0 stock return does not reconcile negative quants
Steps to reproduce:
1. install stock, configure Track Lots or Serial Numbers in Stteings / Warehouse
2. Create an outgoing picking for 1 A2323 manually
3. Force availability on picking
4. Transfer the picking, creating a Serial Number 0001 on the way. 
5. Create a return for the picking, and transfer it specifying the same Serial Number 0001
6. Go to Warehouse / Serial Numbers, open 0001

Expected : the negative quant created in step 3 was reconciled when the return picking was transfered. 

Actual: in the Stock location, I have 1 quant qty -1 and another quant with qty +1 for serial 0001

### PR DESCRIPTION
**Pull request by gurneyalex**
fixes #9906

### CODE REVIEW

**Comment by gurneyalex** [comment]
ping @jco-odoo

**Comment by clonedagain** [comment]
@lbellier I think this is also the question you asked OPW, can you explain the rational maybe?

**Comment by lbellier** [comment]
Yes, i have opened an OPW two month ago for this case, and Odoo answer to me that this is not an issue, but a normal comportment. They added a protection for one quant don't reconcile with a negative one generated by himself.
To correct your data, you need to make an inventory to remove the negative quant.

**Comment by gurneyalex** [comment]
@lbellier @clonedagain thanks. Indeed here's the answer I received:
"""
This is normal behaviour of Odoo when you transfer product with the serial number and return that same serial number into the stock.
As of now there is no any configuration or functionality available to reconcile the stock quantity (like accounting function and as you say in your description) in to the Stock module.
"""

I have mixed feelings on this...

**Comment by jco-odoo** [comment]
The basic idea is that when you return things, those things don't disappear suddenly.  Also, it gave problems with the Stock > Stock moves of production  to just kill the history and if you apply it like this, it might still do weird things (it eats itself, but it want to link the history with itself).  It is good to think about better solutions (e.g. putting something in the context which makes a difference between reversing something or returning something or correcting it easily with inventories), but honestly, I would like to avoid still changing such mechanisms in standard 8.

**Comment by gurneyalex** [comment]
@jco-odoo Thanks for checking back on this. I was not sure of the patch (and did not propose it to OCB as is). 

There is a need though, if only to cleanup mistakes from users. 

Do you think that an adaptation of the patch in #9908 with a specific context, set only if the user checks a box in the return picking wizard would be ok?

**Comment by gurneyalex** [comment]
@jco-odoo consider the following scenario, which can be run on runbot with sale_stock installed

1. create and validate a SO for Luc Maurer with 1  Blank CD (no stock for this)
2. force availability of the outgoing picking, and ship
3. return the erroneous picking

The stock level of Blank CD is 0, with a quant of +1 and a quant of -1

If I create a new SO for Luc Maurer with 1 Blank CD, I get a warning that there is no stock during edition. Yet if I confirm the SO, and Check availability of the picking, it gets Ready to Transfer. 

For me this is a bug.

**Comment by jgrandguillaume** [comment]
Hi there,

That's a clear bug that need to be fixed. I prefer to make a hack for stock->stock moves rather than letting this happen for other cases. The quants should be reconciled in the situation described by @gurneyalex, the fix #9906 works fine.

Regards,

Joël

**Comment by gurneyalex** [comment]
related OPW #658436

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
