### PR TITLE
[FIX] mail: prevent crash when switching mailbox in discuss mobile

### PR DESCRIPTION
**Pull request by seb-odoo**
task-2327203

### CODE REVIEW

**Comment by seb-odoo** [comment]
This test doesn't work locally because I'm getting this. No idea what is that session expired about.

`Body still contains undesirable elements:`
```html
<div role="dialog" class="modal o_legacy_dialog o_technical_modal show" tabindex="-1" data-backdrop="static" id="modal_1089" open="open" aria-modal="true" style="display: block;">
        <div class="modal-dialog">
            <div class="modal-content">
                <header class="modal-header">
                    <h4 class="modal-title">Odoo Session Expired<span class="o_subtitle text-muted small"></span></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" tabindex="-1">×</button>
                </header>
                <div class="o_dialog_warning modal-body" role="alert">
    <p style="white-space: pre-wrap;">Your Odoo session expired. The current page is about to be refreshed.</p>
</div>
                <footer class="modal-footer"><button type="button" class="btn btn-primary"><span>Ok</span></button></footer>
            </div>
        </div>
    </div>
```

**Comment by alexkuhn** [comment]
> This test doesn't work locally because I'm getting this. No idea what is that session expired about.
> 
> `Body still contains undesirable elements:`
> 
> ```
> <div role="dialog" class="modal o_legacy_dialog o_technical_modal show" tabindex="-1" data-backdrop="static" id="modal_1089" open="open" aria-modal="true" style="display: block;">
>         <div class="modal-dialog">
>             <div class="modal-content">
>                 <header class="modal-header">
>                     <h4 class="modal-title">Odoo Session Expired<span class="o_subtitle text-muted small"></span></h4>
>                     <button type="button" class="close" data-dismiss="modal" aria-label="Close" tabindex="-1">×</button>
>                 </header>
>                 <div class="o_dialog_warning modal-body" role="alert">
>     <p style="white-space: pre-wrap;">Your Odoo session expired. The current page is about to be refreshed.</p>
> </div>
>                 <footer class="modal-footer"><button type="button" class="btn btn-primary"><span>Ok</span></button></footer>
>             </div>
>         </div>
>     </div>
> ```

No issue for me to run locally (and it passes). Did you run tests with mobile toolbar (phone icon on top-left corner of Chrome dev tools)?

**Comment by seb-odoo** [comment]
Yes that's what I'm doing. Usually this issue happens when a tab is still opened on a previous database, but I'm pretty sure I closed all of them.

It that works for you feel free to review/merge.

**Comment by seb-odoo** [comment]
Note: will need runbot exception for new test asset in stable.

**Review by alexkuhn — APPROVED** [review]
@robodoo r+

**Comment by alexkuhn** [comment]
> Note: will need runbot exception for new test asset in stable.

Ah... yes...

**Pull request closed without merging**
