### PR TITLE
[FIX] payment_alipay: Remove wrong decorator

### PR DESCRIPTION
**Pull request by sswapnesh**
Remove the wrong decorator from the write method.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dbo-odoo** [comment]
Oh my, yes! Absolutely.

@robodoo r+

**Comment by dbo-odoo** [comment]
actually we need it in 13.0 as well; I didn't notice you targeted master. Gonna do it now.

**Comment by sswapnesh** [comment]
> actually we need it in 13.0 as well; I didn't notice you targeted master. 

Because this was not a Real FIX (https://github.com/odoo/odoo/pull/45878#issuecomment-589569425)

**Comment by dbo-odoo** [comment]
Too late, I merged it in 13.0 anyway at #46033 . Ah well... @mart-e is more strict than me.

@sswapnesh sorry for the inconsistent communication... We're only human ^^

**Pull request closed without merging**
