### PR TITLE
[FIX] only close connections that we opened during database check

### PR DESCRIPTION
**Pull request by ap-wtioit**
Description of the issue/feature this PR addresses:
In https://github.com/odoo/odoo/commit/610036756ac25796d035e4a702416fd9fddc58da all database connections get closed if on of the URLs /web/database/selector or /web/database/manage are called by anybody. When odoo runs without workers this causes http status code 500 in weird places. With the fix we only close connections to databases where no connection was open.

Current behavior before PR:
A call to /web/database/selector or /web/database/manage closes all open connections. This leads to errors in odoo:
```
2018-04-27 12:37:32,503 9783 ERROR odoo11 odoo.sql_db: bad query: b'SELECT "ir_ui_view"."id" as "id","ir_ui_view"."model" as "model" FROM "ir_ui_view" WHERE "ir_ui_view".id IN (199)'
ERROR: cursor already closed
```
This affects odoo running without workers. When running with workers only connections in the main thread are closed and workers stay unaffected.

Desired behavior after PR is merged:
Connections to databases are only closed if they are opened by the current call to /web/databse/selector or /web/database/manage. Other requests (like a login happening at the same time) stay unaffected.

Info: @wt-io-it
Initial commit (deprecated): https://github.com/ap-wtioit/odoo/commit/89e47001cecc5ae2cde0221178871b45999504e5

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@mart-e @nim-odoo 
May I ask you to review and merge this?

**Comment by KangOl** [comment]
Actually, you still have a race condition if a connection is done during the version check.

The solution is to simply `close_db()` on only `incompatible_databases`.
The other ones are legit and may be kept in connection pool.

**Comment by ap-wtioit** [comment]
@KangOl i see your point, and yes there are still race conditions after this patch. However i would not only close the incompatible databases as the original bug fixed by @mart-e in https://github.com/odoo/odoo/commit/610036756ac25796d035e4a702416fd9fddc58da would then reoccur for compatible databases. (The user no longer can drop or rename compatible databases then)

We could solve this by creating our own connection pool in this method and only closing those connections.

**Comment by wtaferner** [comment]
@KangOl 
Hmm, so, basically we should just revert the fix of @mart-e, but what was the need back then?

It seems that the code back then does have the explicit close_db like in https://github.com/odoo/odoo/blame/610036756ac25796d035e4a702416fd9fddc58da/odoo/service/db.py#L98 and https://github.com/odoo/odoo/blame/610036756ac25796d035e4a702416fd9fddc58da/odoo/service/db.py#L98 - it was actually added by @rco-odoo 2 years ago.

Could it be possible that the close_db is not working as expected with workers and threading?

**Comment by ap-wtioit** [comment]
In the pull request now a seperate pool is opened to be able close all connections we opened in the check side effect free.

The external `drop myuselessdb` command this way also works for compatible databases (if no one else is connected to this database)

**Comment by KangOl** [comment]
No.
Using it's own pool is completely useless (you won't reuse connections, and only use one connection at a time)

As I said, you should only `close_db()` on incompatible databases.

In `master` we can add an option to create a temp cursor that wont be kept in pool after close.

**Comment by ap-wtioit** [comment]
From my understanding calling close_db() only on incompatible databases would reintroduce the issue that @mart-e tried to fix in https://github.com/odoo/odoo/commit/610036756ac25796d035e4a702416fd9fddc58da for cases where "myuselessdb" is technically compatible with the current Odoo version.

**Comment by KangOl** [comment]
But, as I said [4 hours ago](https://github.com/odoo/odoo/pull/24479#issuecomment-386535495), commit 610036756ac25796d035e4a702416fd9fddc58da was apparently made to close connections on invalid databases as [we close correctly all connections](https://github.com/odoo/odoo/blob/7202205688d9c75377925011e07938e50030b617/odoo/service/db.py#L158) before dropping/renaming databases.

**Comment by wtaferner** [comment]
Hmm, I think you have a point, but have to admit I like the idea more with handling this in an own pool or find another way.

The only downside of your way is that a just duplicated database which is compatible won't be possible to be dropped until the connection is recycled, the server is restarted or you try to delete the database via the interface which will also close all connections before the deletion.

**Comment by ap-wtioit** [comment]
@KangOl commit https://github.com/odoo/odoo/commit/610036756ac25796d035e4a702416fd9fddc58da states "When listing compatible and incompatible db" i do not see that it apparently only is considered dropping incompatible databases.

In this usecase the fix with only closing compatible databases would not work:
* start odoo without workers
* call http://127.0.0.1:8069/web/database/manager
* duplicate your database or have other databases (e.g. for other customers) that are compatible
* call http://127.0.0.1:8069/web/database/selector
* try to drop the database in an external tool (e.g. pgAdmin or command line)
* You get an error like "ERROR: database odoo_compatible is being accessed by other users, DETAIL: There is 1 other session using the database"
image

If those issues are not as important i added a second commit that only closes connections with incompatible databases (However there is this bug described above, now)

**Comment by KangOl** [comment]
Blocking command line calls to `dropdb` is actually a non-issue as:
 - you are in production and 
    - You should not create other databases accessible to odoo
    - You should have [disable access to database manager](https://www.odoo.com/documentation/11.0/setup/deploy.html#security)
 - You are in staging/dev: just restart odoo in this case.

**Comment by wtaferner** [comment]
All true, but the official Odoo app is the downer here and no, Odoo mobile is not accessing the database manager but `list_db` to be able to login, so you need to turn on list_db feature in config and the same way everyone could call it and leave connections open even if not a single user is really online.

Anyway, your way is also helping to resolve the major part of our issue, it just feels a bit incomplete to us :-)

Thank you for taking the time.

**Comment by wtaferner** [comment]
@KangOl 
The PR was adapted as you requested. Thank you for merging the minimal common ground if you do not reconsider the own connection pool for this side location :-)

**Pull request closed without merging**
