### PR TITLE
[16.0][FIX] js: create several records through orm.create

### PR DESCRIPTION
**Pull request by benwillig**
Simple backport of https://github.com/odoo/odoo/commit/75434804a58e8bc0924723ce5299575d9e18c88b

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
Hello. This change is breaking and thus not acceptable for a stable version. In 17.0, orm.create can be used to create several records. In 16.0, you can use orm.call("create", ...). I'm thus closing this PR.

Regards.

**Comment by benwillig** [comment]
Hello, I don't understand how it can be a breaking change, as api.model_create_multi already exists in 16.0.
The JS method already check that given records are objects. Giving more than one record results in a python error as the list of values are passed as arguments to the create method, instead of passing a list of values, so the problem is here and the backport is correct.
But you can give an example on how it can break the stable version.

**Comment by benwillig** [comment]
I'm agree with this, but giving more than one record doesn't work. With the backport, creating one record or more than one record works. So if the backport breaks anything, it must be caused by something else that is not in this method.

**Comment by aab-odoo** [comment]
In 16.0, creating more than one record with orm.create doesn't work. We know it, it's a limitation. As of 17.0, it's working.

In every versions, in the orm object, there's a `call` function that can be used to call any python (public) method of the model, including create. With call, you can provide the arguments the way you want, so you can provide a list of records to create. It's working just fine.

So indeed, in 16.0, you can't use orm.create to create a batch or records, but you can use orm.call("create", ...), which is almost the same thing.

So it isn't required to make a change to orm.create. Especially if the change is breaking, which is the case here:

Before your PR, calling `orm.create("crm.tag", [{ name: "tag1" }])` returns a promise that resolves with **the id of the created record**.
After your PR, the same call returns a promise that resolves with **the list of ids of the created records**.
It's due to the way call_kw handles create requests: it behaves differently if it is given a record or a list of records to create. 

This explains why the runbot wasn't happy with your change: https://runbot.odoo.com/runbot/batch/1296935/build/56852964

**Comment by benwillig** [comment]
Ok I understand now how it breaks the stable version, thank you for your time and feedback.

**Pull request closed without merging**
