### PR TITLE
[FIX] mail: be retro compatible with postgresql < 9.6

### PR DESCRIPTION
**Pull request by tde-banana-odoo**

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@tfr-odoo

**Comment by tde-banana-odoo** [comment]
@odony

**Comment by tfr-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo delegate @tfr-odoo

**Comment by tfr-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo delegate=tfr-odoo

**Comment by tfr-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
