### PR TITLE
[FIX] website_form: metadata recording

### PR DESCRIPTION
**Pull request by chienandalu**
Description of the issue/feature this PR addresses:

`website` model has this hidden field wich isn't being used at all but wich implementation becomes handy to fullfil GDPR requirement acquiring website forms metadata.

Current behavior before PR:

If we set the field to True a key error raises

Desired behavior after PR is merged:

This hidden feature can be use by further extensions

cc @Tecnativa

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by chienandalu** [comment]
Ok, I updated the description

**Comment by JKE-be** [comment]
Hi 

Can you explain the real purpose ?

Like that, I don’t see ...

**Comment by pedrobaeza** [comment]
The idea is to store there metadata like express consent (checkboxes and so on). It requires extra development in community modules, but this can't be done if we don't perform this change. On the enterprise module website_form_editor, you can then add also a field type for this kind of consent.

**Comment by JKE-be** [comment]
> website model has this hidden field wich isn't being used at all but wich implementation becomes handy to fullfil GDPR requirement acquiring website forms metadata.

But this fields is used (to store IP and co... if option enabled)
https://github.com/odoo/odoo/blob/d67b410dfcd67d2540628d4f6be0daf8861c4a46/addons/website_form/controllers/main.py#L149

As you say, it is not a real risk to change it (except if an existing module do 'meta' in data), but I don't understand how it could block a custom dev...

**Comment by chienandalu** [comment]
Hi, @JKE-be. There's no view to set that field in the website so that check is allways `False`. Indeed this PR fixes the case that the field was `True` ending in a key error here: https://github.com/odoo/odoo/blob/d67b410dfcd67d2540628d4f6be0daf8861c4a46/addons/website_form/controllers/main.py#L150

My first commit completed the lacking views and fields to have this fully working (https://github.com/odoo/odoo/pull/24848/commits/728b637b28df7ea6a6a31dcd2a70fb531134d141) but, as @pedrobaeza pointed, it's not appropiate for this branch.

**Comment by JKE-be** [comment]
oups, my bad... I didn't see the +=

**Comment by pedrobaeza** [comment]
Thanks for the explanation, @chienandalu and thanks for the merge, @JKE-be 

This will be auto-closed when the commit will be forward-ported to 11.0

**Comment by mreficent** [comment]
It was already merged. It can be closed.

**Comment by pedrobaeza** [comment]
I was waiting for the forward port, but OK, let's keep the clean house.

**Pull request closed without merging**
