### PR TITLE
[10.0][FIX] l10n_do: update CoA (for IFRS), taxes, fiscal positions and journals

### PR DESCRIPTION
**Pull request by gustavovalverde**
Description of the issue/feature this PR addresses:
- CoA non-compliant with Dominican Republic regulations
- CoA not standardized for most companies "real-life" use
- Uncomplete Taxes
- Wrongly configured Fiscal Positions
- Wrongly configured sequences and journals for regulator's needs

Current behavior before PR:
- Everything can be done, but it is not a production ready localization

Desired behavior after PR is merged:
- Easier implementation for most of the people
- Minor customization to be fully compliant with local regulations
- Standardized configuration to help other Odoo consultants and implementers

To comply with local and tax regulations:
- The whole Charts of Accounts was changed
- All the regulatory taxes were added and configured with group taxes

To standardize the Dominican implementations:
- An IFRS compatible CoA that does not need major changes for most companies
- A well structured CoA with a codification logic.
- Use of the Odoo original flow for creating tax compliant invoice sequences
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gustavovalverde** [comment]
Hi @qdp-odoo.

Also doing the same PR as https://github.com/odoo/odoo/pull/13787

**Comment by eneldoserrata** [comment]
@mart-e This is one of the best updates for the Dominican localization, I would like to accept it since it greatly simplifies the configuration and the catalog of accounts is super elegant.

Thanks @gustavovalverde good job!

**Comment by mart-e** [comment]
Hello,

Thank you for the substitution but this PR the same as #13787 right?
If the requests are the same, please [only submit for 9.0](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch) and it will be forward ported. Create two pull requests only if the code is different.

@qdp-odoo has started a review of the #13787 and will merge it in the appropriate version once the review is completed.

**Comment by RafosRD** [comment]
Thanks @gustavovalverde  good job!!

**Pull request closed without merging**
