### PR TITLE
[REM] social_media, *: remove google plus from everywhere

### PR DESCRIPTION
**Pull request by kig-odoo**
* website, website_blog, website_mass_mailing

Google+ was shut down for business use and consumers.
see: https://en.wikipedia.org/wiki/Google%2B

### CODE REVIEW

**Comment by kig-odoo** [comment]
@JKE-be as Google+ was shut down I think we can remove it from everywhere.

**Comment by JKE-be** [comment]
we keep it in the past, because it was an easy way to link your google business account.
But is is still needed, don't see anything about it  ? 

//cc @sbuhl 

And maybe you can point to https://plus.google.com/ instead of a wiki

**Comment by sbuhl** [comment]
@kic-odoo @JKE-be 
For me we can remove it completely.
Also, don't forget to update the block image: https://nimb.ws/s4ukhS

**Comment by kig-odoo** [comment]
@sbuhl Thanks for noticing snippet thumb image.
I've updated the image :smile_cat: 

@JKE-be i've changed link as you said :tada:

**Comment by mart-e** [comment]
@kig-odoo please configure your git to use your odoo email address (to avoid the CLA warning). Also, no need to use your fork, you can use odoo-dev/odoo repository

**Comment by kig-odoo** [comment]
@mart-e  Actually I have left the Odoo India last month so I do not have access to that email or repo. I have used my personal email address for this. 

I have added CLA in separate commit with this PR.

**Comment by mart-e** [comment]
My bad, sorry to hear that. I was confused as you were still registered as a member of the organisation. To fully avoid confusion, could you please rename your [github account](https://github.com/settings/admin)?
Thanks for the CLA signature !

**Comment by mart-e** [comment]
Thanks !

@robodoo r+ rebase-ff

**Comment by mart-e** [comment]
robodoo r- change of models

**Comment by JKE-be** [comment]
@mart-e 

Because we are all agree, let's go...

@robodoo r+


jke & mart-e

**Comment by kig-odoo** [comment]
Thanks, @mart-e @JKE-be for merge :smiley: 

@mart-e sorry I didn't notice your last message. but I will rename github account soon.

**Pull request closed without merging**
