### PR TITLE
[IMP] fields.py: New Secret field

### PR DESCRIPTION
**Pull request by Julien00859**
Passwords, tokens, pins and other secret values have always been stored
in Char fields with limited accesses usually restricted to the
superuser. Such values are sensitive yet there was no standard easy way
to prevent unauthorized access.

We introduce a new `Secret` field type behaving just like the standard
`Char` field it inherits from. The notable difference is that the secret
field value is empty to all users except the super user. On other words,
for regular users, it behaves like a write-only field.

--

There are some fields that are quite expensive to group by or to order
by, such field include relational fields (Many2many and One2many) and
binary fields (both large blob of data and filesystem-stored
attachments).

In order to prevent non-efficient operations on those fields, we
introduce a new `groupby` field attribute. This attribute is a boolean
value controlling whether the field can be grouped by or ordered by.

### CODE REVIEW

**Comment by Julien00859** [comment]
What do you think we add a warning when you try to read a secret as a regular user ?

**Comment by Julien00859** [comment]
Hello everyone, I've tried to split the changes on the code base in several commits in order to ease your review. You should only have one specific commit to review. I may be mistaken on who is the gourou of what commit so don't hesitate to ask the correct person.

If you have any other field in mind that could benefit to become a Secret, let me know.

Last but not least, I just tested the new field on base and on the email related models. I did pay attention not to break anything but there are quite a lot of files, there sure is a mistake somewhere.

**Comment by JKE-be** [comment]
Seems like branch is red

and just try to open a setting view to check will raise:

  File "/data/build/odoo/odoo/addons/base/models/res_config.py", line 487, in default_get
    classified = self._get_classified_fields()
  File "/data/build/odoo/odoo/addons/base/models/res_config.py", line 470, in _get_classified_fields
    raise Exception("Field %s must have type 'boolean', 'integer', 'float', 'char', 'selection' or 'many2one'" % field)
Exception

**Comment by hparfr** [comment]
Hi, thanks to improve this security design issue.

But please, take inspiration for prior art https://github.com/odoo/odoo/issues/21520#issuecomment-361896559

Keychain modules (v8, v9, v10) has been replaced by data_encryption (v12) : https://github.com/OCA/server-env/tree/12.0/data_encryption

It does mainly 2 things:

A) - manage encrypted data (like passwords) in a safe manner
B) - provide environment specific value (ie: it returns productions credentials (R/W) or test credentails (Read only) upon context).


While B has no reason to be in odoo core, it could be good to have the functionality to store password in "not too easy recoverable" way and disallow read from users.

We implemented it using symmetrical encryption: the key is not stored in the db but provided in the config. In that way, passwords can't be extracted from a database dump.

Having a good and reliable secret field is a nice improvement, I hope you will implement it in a secure manner like we did in data_encryption.

About UI/UX: never display clear text password to anyone.

The change user password wizard is following a good practice: never display user's pasword, only asks for a new one. I hope you will follow this instead of showing password to some users like admin.

**Comment by JKE-be** [comment]
@Julien00859 

Seems like all yours changes in websites has been dropped, Is it by design?

**Comment by Julien00859** [comment]
Too much problem with `res.config.settings`, I'll figure it out later, first I change the fields not requiring an entry in the the settings

**Pull request closed without merging**
