### PR TITLE
add trilab's agreement

### PR DESCRIPTION
**Pull request by jerzyk**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `j...@blueice.pl`
- you are signing _for_ the address `j...@trilab.pl`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by jerzyk** [comment]
updated github's default email address

**Comment by mart-e** [comment]
@jerzyk but this did not change anything in this PR. You can amend your last commit to change the author.
https://help.github.com/en/articles/setting-your-commit-email-address
https://www.git-tower.com/learn/git/faq/change-author-name-email#chapter_using+--amend+for+the+very+last+commit

**Comment by jerzyk** [comment]
commit amended, I hope this time it is ok...

**Comment by mart-e** [comment]
Thanks for the modification, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

@robodoo review+

**Pull request closed without merging**
