### PR TITLE
[CLA][14.0] signature for hoangtiendung070797

### PR DESCRIPTION
**Pull request by hoangtiendung070797**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hoangtiendung070797** [comment]
@mart-e Please review it. Thank you so much

**Review by niyasraphy — COMMENTED** [review]
hi @hoangtiendung070797 ,
seems the runbot test is getting failed and the reason is: https://github.com/odoo/odoo/pull/114721#issuecomment-1461576559

please see the comment added by Martin in the above link.
thanks

**Comment by hoangtiendung070797** [comment]
> hi @hoangtiendung070797 , seems the runbot test is getting failed and the reason is: [#114721 (comment)](https://github.com/odoo/odoo/pull/114721#issuecomment-1461576559)
> 
> please see the comment added by Martin in the above link. thanks

Oh, thank you :100:

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
