### PR TITLE
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### PR DESCRIPTION
**Pull request by JorayOpen**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thanks for the contribution but please check the [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://transifex.com/odoo/public), not Github.

Please submit your changes there and let me know if you have issues.

Thanks

**Comment by joray** [comment]
> Hello,
> 
> Thanks for the contribution but please check the [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://transifex.com/odoo/public), not Github.
> 
> Please submit your changes there and let me know if you have issues.
> 
> Thanks

It is a financial account, not a translation. I read ODOO's documentation that this part of content directly submits pull request

**Comment by mart-e** [comment]
Oups, sorry my bad, read too fast

**Review by niyasraphy — COMMENTED** [review]
hi @joray , you may have to update the commit message as per the guidelines and squash the multiple commits to 2, one for cla and one for the translation.

see: https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html

**Review by joray — COMMENTED** [review]
ok

**Pull request closed without merging**
