### PR TITLE
[FIX] calendar: fix access rights of calendar attendee for portal user

### PR DESCRIPTION
**Pull request by kitan191**
Removing default read/write access rights on Calendar Attendee Information for Portal User.

opw-2325322

### CODE REVIEW

**Comment by kitan191** [comment]
ping @nim-odoo @mart-e

**Comment by mart-e** [comment]
@kitan191 LGTM  :+1: , we can also remove the record rules in master for cleaning

**Review by nim-odoo — APPROVED** [review]
robodoo delegate+

**Comment by kitan191** [comment]
robodoo r+

**Comment by kitan191** [comment]
robodoo retry

**Pull request closed without merging**
