### PR TITLE
[FIX] purchase: format dashbord

### PR DESCRIPTION
**Pull request by fmdl**
Before this PR float are not format in the current lang.

**Before**
image

**After**
image

@amoyaux

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW #2715088

**Comment by fmdl** [comment]
cc @ticodoo

**Comment by amoyaux** [comment]
I would use correct widget in the view instead

**Comment by ticodoo** [comment]
PR needs to be updated to take into account https://github.com/odoo/odoo/pull/80938 being merged, i.e. the currency values don't need to be formatted anymore.

**Comment by fmdl** [comment]
@ticodoo it is done

**Comment by amoyaux** [comment]
Still don't do that and use the correct widget in the view

**Pull request closed without merging**
