### PR TITLE
[FIX] sale_management: maintain template lines order on Confirm

### PR DESCRIPTION
**Pull request by AH-Yussef**
### Steps to reproduce:
- Install **Sales** app
- Open Sales app, Go to **Configuration** > **Quotation Templates**
- Open a template, or create an new one
- Add sections with product(s) under each, so we have a structure like: 
    - Section 1 
    - Product 1 
    - Section 2 
    - Product 2
- Go to **Orders** > **Quotations**
- Create a **New** Quotation
- Select the recently created/updated template in the **Quotation Template** field
- Click on **Confirm**
- U can notice how the sections are moved to the top, missing up the structure

### Investigation:
- Each sale order order_line has a `sequence` property associated to it which defaults to **10** _if not explicitly specified_ https://github.com/odoo/odoo/blob/55b452ac0056c7075097fa1324ef53fc5090fb7a/addons/sale/models/sale_order_line.py#L41
- On Choosing a template, the `_prepare_order_line_values()` method returns the needed properties for each template line https://github.com/odoo/odoo/blob/55b452ac0056c7075097fa1324ef53fc5090fb7a/addons/sale_management/models/sale_order.py#L108
- The returned object for each template is missing the `sequence` property, resulting in it falling back to **10** when assigning it to the sale order `order_line` https://github.com/odoo/odoo/blob/55b452ac0056c7075097fa1324ef53fc5090fb7a/addons/sale_management/models/sale_order.py#L117
- Now all order_line(s) has the same `sequence` -except for the first one which has a sequence value of -99- https://github.com/odoo/odoo/blob/55b452ac0056c7075097fa1324ef53fc5090fb7a/addons/sale_management/models/sale_order.py#L114-L115

opw-3602781

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
Hi,

There is a history with the sequence and quotation template:

- in this april 2022 commit 6f11060d6afd9edce904dd34a2d415a2a2461108 it was added to fix an issue similar to yours

- in this may 2023 commit 994ee129b7c954111e3238af2d7d3c226a2f1312 it was reverted because the issue of the fix I think outweighed the original issue

There was also a test of a solution https://github.com/odoo/odoo/pull/91542 keeping the sequence but it was not merged (and I think I had discussed it with JS team before closing it).

I think your current solution would bring back the issue that caused the may 2023 revert. 

For the scenario of your issue, the line are created in the right order (the `_order` of sale.order.line is `order_id, sequence, id`) as seen in the db:

```
select name, id, sequence from sale_order_line where order_id=26 order by order_id, sequence, id;
      name       | id | sequence 
-----------------+----+----------
 section1        | 55 |      -99
 productSection1 | 56 |       10
 section2        | 57 |       10
 productSection2 | 58 |       10
```
The issue comes from the fact that order_line are ordered only by "sequence" and not by "sequence, id" because of this line:

https://github.com/odoo/odoo/blob/bf2b1b1347a73b491556cf85e85cb51659dc04a1/addons/web/static/src/views/list/list_arch_parser.js#L221

I'm not sure if that could be improved in the JS framework, a solution that seems to work (but a little hacky) is to set the `default_order` of the embedded view to 'sequence, id`:

https://github.com/odoo/odoo/blob/17.0/addons/sale/views/sale_order_views.xml#L458

with this change, the lines are ordered by "sequence, id" and the issue of the scenario doesn't happen.

**Comment by nle-odoo** [comment]
note: I've tested in 17.0 with your commit, and I can't reproduce the scenario of 994ee129b7c954111e3238af2d7d3c226a2f1312

If I do it, I have 4 lines with sequence:

- the 3 lines from the quotation template: 10, 11, 12 
- and 1 line: 14 that is added on the sale.order

so it seems that the current fix in this PR seems ok for 17.0 at least :+1:

**Review by vava-odoo — APPROVED** [review]
Thanks @AH-Yussef, it looks good to me.

**Review by Feyensv — APPROVED** [review]
minor linting comment, otherwise lgtm :ok_hand: 

@robodoo delegate+

**Comment by AH-Yussef** [comment]
@robodoo r+

**Pull request closed without merging**
