### PR TITLE
[FIX] payment_sips: Wrong test and production URLs

### PR DESCRIPTION
**Pull request by simongoffin**
The production/test urls were inverted.

opw:2061123

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by simongoffin** [comment]
robodoo r- 

(because we are waiting the fw-bot)

**Comment by JKE-be** [comment]
oups ;) 

LGTM in all cases ;)

**Comment by JKE-be** [comment]
ps in v12 ? not before ? 
Don't remember of recent change in this module

**Comment by nim-odoo** [comment]
robodoo r+

(we'll try on a earlier branch to see how the bot behaves if it finds a conflict / empty diff)

**Pull request closed without merging**
