### PR TITLE
[FIX] purchase: avoid set a purchase order as invoiced when all the l…

### PR DESCRIPTION
**Pull request by kaerdsar**
Avoid set a purchase order as invoiced when all the lines are cancelled.

### CODE REVIEW

**Comment by jholze** [comment]
@Yenthe666 @odony maybe you both guys can have a look.

**Comment by Yenthe666** [comment]
@mart-e this might be something for you!

**Comment by odony** [comment]
@kaerdsar the patch makes sense, we just need to double-check that there is no unexpected side-effect.
BTW your CLA signature does not pass the check because your commits are signed with a default local address `cesar@Cesars-MacBook-Pro.local`, not your email. Could you set your git config's `user.email` parameter and rebase the commits? Thanks!

**Comment by kaerdsar** [comment]
@odony email in commits fixed. Thanks

**Comment by odony** [comment]
@kaerdsar thanks!

**Comment by mart-e** [comment]
Sorry for the lack of reply but the 8.0 is no longer supported.
The good news is that this problem does not seem to be in upper versions.

**Pull request closed without merging**
