### PR TITLE
Fix search visibility in control panel

### PR DESCRIPTION
**Pull request by leorochael**
Description of the issue/feature this PR addresses
===

The ControlPane.nodes.$searchview `<div>` currently
reveals itself in situations where it was supposed to be hidden, when navigating between
records while in form view (as opposed to tree/list/kanban view), if the next record has a different "name"
(i.e. a different `action.title`).

This happens because a change in name causes a change in the breadcrumbs, which causes an update of the `ControlPanel` (the header that contains the breadcrumbs, the search widget and the navigation pager)

Most of the time, the $searchview element would be an empty div, so the reveal would be a barely perceptible change of height in the form header while navigating between records.

The effect is a lot more pronounced on Enterprise, in mobile screens,
and can be easily seen as the green magnifying glass showing up while
navigating between `res.users` in form view.

Current behavior before PR
===

 * Go to the [Enterprise section of the runbot](http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7)
 * Pick a 10.0 runbot for a spin (say, like [this one](http://189126-10-0-c755d7.runbot8.odoo.com/web/login))
 * Log in as admin
 * Open the `Settings` app
 * Switch your browser to mobile/responsive design mode 
   * In Chrome, it's inside the developer tools (F12), the second icon from the left in the top left corner
   * In Firefox, it's under Menu > Developer > Responsive Design Mode
   * (or do this whole process with a mobile browser to begin with)
 * Access the link `Manage access rights` under the `2 Active Users` label
 * Notice a green magnifying glass near the top right corner that gives access to the search widget.
 * Notice the two users present in the list, and click on one of them
 * Notice that the green magnifying glass has disappeared
   * So far, this is all as it should be, as there is no point in searching while in "form mode" as opposed to "list/tree/kanban mode".
 * Use the page arrows near the top right corner to navigate to the other user
 * Notice that the green magnifying glass has now appeared.
  * Also notice that it is quite useless, since all it does when clicked is to make the record name disappear.

Desired behavior after PR is merged
===

The `$searchview` node of the control panel only shows up when intended.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by leorochael** [comment]
@aab-odoo, what do you think of this PR?

I tried to keep with the theme of the control panel only updating the things that are asked of it, and trying to keep the other control panel components untouched. In this case, updating only breadcrumbs shouldn't touch the search view.

**Comment by leorochael** [comment]
@ged-odoo, since you've been so kind to pay attention my other recent PRs, would you mind taking a look at this one as well?

**Comment by leorochael** [comment]
@ged-odoo @aab-odoo, I've rebased to the latest 10.0, which includes the qunit fixes in my other PR, and reduces this PR to three small commits, which I recommend reviewing one by one.

The test in the second commit will fail unless the third commit is added, as expected. If you prefer, I can merge the two last commits combining the change with the test.

**Comment by tivisse** [comment]
@ged-odoo 

This improvement is worth a review I my opinion :)

Thanks/

**Comment by ged-odoo** [comment]
@tivisse we have a brand new RD Framework tag. I'll try to keep up more with the PR tagged Framework, and I'll be joined by the rest of the team :).

**Comment by leorochael** [comment]
@ged-odoo what does `RD` mean in `RD Framework`?

**Comment by Yenthe666** [comment]
@leorochael Research & Development.

**Comment by ged-odoo** [comment]
@leorochael Yenthe666 is right.  RD Framework is actually the 'complete' name of my team, which is a subteam of the Research & Development department

**Comment by C3POdoo** [comment]
Dear @leorochael,

Thank you for your contribution but the version 10.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
