### PR TITLE
[FIX] mail: reduce vertical spacing for tracking messages

### PR DESCRIPTION
**Pull request by phenix-factory**
task-2282385

----

#

### CODE REVIEW

**Comment by seb-odoo** [comment]
commit: typo tra**c**king, and missing `mail:`

**Comment by phenix-factory** [comment]
@seb-odoo Oups, updated ç

**Review by alexkuhn — APPROVED** [review]
@robodoo r+

(force-pushed with slight change in commit message: _"remove extra spacing"_ => _"reduce vertical spacing"_)

**Comment by seb-odoo** [comment]
Runbot red, might need rebase? or rebuild at least

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
