### PR TITLE
[IMP] Added on what bruto price a taxe is applying in Sale details

### PR DESCRIPTION
**Pull request by kebeclibre**
Adding the bruto total on which a tax is applied in Sale details report (pos)

Current behavior before PR:
The taxes global amounts where not verifiable.

Desired behavior after PR is merged:
We know on how much each tax apply

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
Same as https://github.com/odoo/odoo/pull/14349

**Comment by danger89** [comment]
Pull to the latest master branch? If you still relevant? It looks good actually if it is still relevant.

**Comment by xmo-odoo** [comment]
@kebeclibre is this PR still relevant?

**Comment by rdeodoo** [comment]
https://github.com/odoo/odoo/commit/cdcdebc6cb1158902d955444c47696ab53171642

**Pull request closed without merging**
