### PR TITLE
[FIX] web_tour: Give correct access when reading modules

### PR DESCRIPTION
**Pull request by Arcasias**
In response to https://github.com/odoo/odoo/pull/60632#issuecomment-917924686

### CODE REVIEW

**Comment by Arcasias** [comment]
cc @mart-e @ged-odoo @rrahir

**Review by mart-e — APPROVED** [review]

**Comment by xmo-odoo** [comment]
The commit message (and PR description) is misleadingly worded: 

> Before this commit, this check was only performed if the user had the
`is_admin` flag

That doesn't change, it's still the case afterwards.

**Comment by rrahir** [comment]
@xmo-odoo any objection to merge it now ?

**Comment by rrahir** [comment]
@robodoo  r+

**Pull request closed without merging**
