### PR TITLE
[IMP] website: handle text options in translation mode

### PR DESCRIPTION
**Pull request by xO-Tx**
The goal of this PR is to simply disable the "Text Animation" button from the editor's
toolbar in translate mode. An adaptation of code in stable `17.0` will be added to
allow the use of text options (text animations & text highlights) in the translation mode,
mainly by allowing the creation of snippet editors if the target is a text option snippet.

opw-3686777

### CODE REVIEW

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
> Steps to reproduce:
>
> - Go to the website translation mode with some animated text in page
> content > The text won't be animated and only remains invisible.

@xO-Tx I tested in 15.0, this does not seem to be true, the text is animated and can be edited.

**Comment by xO-Tx** [comment]
> I tested in 15.0, this does not seem to be true, the text is animated and can be edited.

@qsm-odoo Are you sure about the steps to follow? I can still see the issue on runbot `15.0`:

https://github.com/odoo/odoo/assets/25032876/18ffd6fa-3155-48fb-b78a-be066d735e80

**Comment by xO-Tx** [comment]
@qsm-odoo Indeed, it's caused by the modal (see commit message for explanation) :+1::
> In translation mode, the "Translation Info" modal will just break this check, since it will be mounted outside the targeted DOM.

**Comment by qsm-odoo** [comment]
Mention that in the steps to reproduce please :+1: @xO-Tx

**Review by qsm-odoo — APPROVED** [review]
Let's go with that for now, translate mode should be improved in master. Don't forget to adapt during forward-port to include your diff about making it possible to use the text options in translate mode :+1: 

@robodoo rebase-ff r+

**Pull request closed without merging**
