### PR TITLE
12.0 fix incl. archived string

### PR DESCRIPTION
**Pull request by anandkansagra**
Description of the issue/feature this PR addresses:
https://github.com/odoo/odoo/issues/29090

Current behavior before PR:
String:- Count (incl. archived)

Desired behavior after PR is merged:
String:- Count (Incl. Archived)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Moved to master. rebased and merged with  #29010
Thanks !

@robodoo r+

**Comment by mart-e** [comment]
Changed the email to match the CLA

@robodoo r+

**Comment by mart-e** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
robodoo retry

**Pull request closed without merging**
