### PR TITLE
[FIX] account: speed up account.invoice.report

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses:
Very slow account.invoice.report

Current behavior before PR:
Before this patch, [this unoptimized filter][1] forced the subplan from `currency_rate` to be executed twice. And that's not a very optimized plan that, when joined with the `sub` table, slowed down the report *a lot*.

Desired behavior after PR is merged:
Now the `currency_rate` plan is forced to be materialized, which on one hand makes the plan execute just once, and on the other hand it is done outside of the join, which results in less records being used.

On a production database with big amount of records, [the old report took 2 minutes][2] to return, while [the new one takes "only" 19 seconds][3].

@Tecnativa TT31898

[1]: https://github.com/odoo/odoo/blob/8f6430359b347d3669a536eca0a297c66ce99163/addons/account/report/account_invoice_report.py#L179-L180
[2]: https://explain.dalibo.com/plan/3s1b
[3]: https://explain.dalibo.com/plan/A37

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Doing it materialized means that data won't be live, but stored, so that changes the requirements and can't be accepted AFAIK.

**Comment by Yajo** [comment]
Not this time. This is not a materialized view, but a materialized with. According to [the docs](https://www.postgresql.org/docs/13/sql-select.html#SQL-WITH):

> By default, a side-effect-free WITH query is folded into the primary query if it is used exactly once in the primary query's FROM clause. This allows joint optimization of the two query levels in situations where that should be semantically invisible. However, such **folding can be prevented by marking the WITH query as MATERIALIZED. That might be useful, for example, if the WITH query is being used as an optimization fence to prevent the planner from choosing a bad plan**. 


However, now that I read it closer, I can see it also says:

> PostgreSQL versions before v12 never did such folding, so queries written for older versions might rely on WITH to act as an optimization fence.

So this will only work on Postgres 12 or later. What's the lowest postgres supported version? It's lower, right? I guess I'll have to add this conditionally.

**Comment by Yajo** [comment]
Now the `MATERIALIZED` extension is added only for postgres >= 12. It should be ready to merge.

**Comment by pedrobaeza** [comment]
OK, let's see what Odoo thinks about this. cc @oco-odoo @qdp-odoo

**Comment by nseinlet** [comment]
@Yajo To get an idea, how many currency rates do you have in database? are the statistics up to date when performing the query? On the optimised version, I See on the sort of currencies:
`Rows: 77,821,570 (Planned: 909) `
 I'll check your new version of the query with few and many currencies/rates.

**Comment by Yajo** [comment]
> To get an idea, how many currency rates do you have in database?

965 records

**Comment by C3POdoo** [comment]
Dear @yajo,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
