### PR TITLE
[IMP] l10n_hn: Honduras country state data

### PR DESCRIPTION
**Pull request by jose-pcg**
**Description of the issue/feature this PR addresses:**

Adds Honduras states data

**Current behavior before PR:**

No states for Honduras

**Desired behavior after PR is merged:**

Have all Honduras states loaded after new database create

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by d2isolutions** [comment]
@jco-odoo could you please help with the review process of this PR

**Comment by jco-odoo** [comment]
@jlopezg If the states are required, then it is best for them to be in base ( https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/data/res.country.state.csv ) because if someone sends something to Honduras they also need to specify the correct one even if he is not based in Honduras.  And best in master to not brake any things in existing dbs.  If they are not required, then better not to add them.  Would be really nice if you could verify further.

**Comment by jlopezg** [comment]
> @jlopezg If the states are required, then it is best for them to be in base ( https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/data/res.country.state.csv ) because if someone sends something to Honduras they also need to specify the correct one even if he is not based in Honduras. And best in master to not brake any things in existing dbs. If they are not required, then better not to add them. Would be really nice if you could verify further.

@jco-odoo roger that.
I'll make the changes.

**Comment by jlopezg** [comment]
Moved to new PR: https://github.com/odoo/odoo/pull/72250

**Pull request closed without merging**
