### PR TITLE
[FIX] account: add missed sudo for get_param

### PR DESCRIPTION
**Pull request by yelizariev**
The problem comes from #65789

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Thanks for the quick reaction!

**Review by nle-odoo — APPROVED** [review]
robodoo r+

since it is already in 14.0 foward-port (https://github.com/odoo/enterprise/pull/16491):

fw-bot ignore

**Comment by wtaferner** [comment]
Thx

**Comment by wtaferner** [comment]
@pedrobaeza 
There you see who is updating the customers quite often 😉

**Pull request closed without merging**
