### PR TITLE
[FIX] mrp: kits and PO based on reordering rules

### PR DESCRIPTION
**Pull request by adwid**
If a product is a kit and has a storable component, if this component is
already ordered (with sufficient quantity), when running the scheduler,
the ordered quantity of this component will still be increased.

To reproduce the error:
1. Create two products P_kit and P_compo
	- Both are storable products
	- P_compo must have at least one vendor
2. Create a BoM for P_kit:
	- Must be a kit
	- Add P_compo to components
3. Set a reordering rule for P_kit
4. Inventory > Operations > Run Scheduler
5. Go to Purchase and find the generated RfQ
	- The ordered quantity is correct
6. Repeat 4-5

Error: This time, the ordered quantity is incorrect. While you don't
have any P_kit on hand, each time the scheduler is run, the ordered
quantity will increase.

A similar issue has already been fixed: #63891. The original commit
targets the version 13, but the fix has also been applied to v14 (#64277).
However, here the case is slightly different: the user run the scheduler
twice while the first RfQ is not yet confirmed and received. In such a
case, the scheduler must also check the "quantity in progress". In version
14, it seems nothing computes this quantity for the kits.

OPW-2421841

### CODE REVIEW

**Comment by adwid** [comment]
@nle-odoo

**Review by nle-odoo — COMMENTED** [review]
seems rather similar to https://github.com/odoo/odoo/pull/63891 so should make sense

what do you think about this @amoyaux ? (or someone else with expertise of orderpoint/bom)

**Review by amoyaux — DISMISSED** [review]

**Comment by amoyaux** [comment]
Or maybe we should not allow kit in orderpoint. Should be checked with our PO (mgm)

**Comment by amoyaux** [comment]
This way you will have twice the quantity in other usecase https://github.com/odoo/odoo/blob/14.0/addons/stock/models/stock_orderpoint.py#L243
It's the quantity from a RFQ that is missing.

**Comment by adwid** [comment]
I'm not sure about the variable `ratios_total` because it only considers the quantity on hand and in progress.
Suppose we have a Kit composed of components C1 and C2. Suppose this situation:
|Product|On Hand|In Progress|Virtual|Total|
|---|:---:|:---:|:---:|:---:|
|C1|3|5|0|3 + 5 = 8|
|C2|5|0|6|5 + 0 = 5|
|Kit|3|5 - 3 = 2||5|

The current code ignores the virtual quantity. Is that correct ? Shouldn't I use `component.virtual_available` instead of `component.qty_available` in the following lines ?
```python
                qty_available = component.qty_available / qty_per_kit
                ratios_qty_available.append(qty_available)
                ratios_total.append(qty_available + (qty_in_progress / qty_per_kit))
```
(from https://github.com/odoo/odoo/pull/64699/files#diff-43541c3159046c998238ca68f4678f0a46190d91f2d8e5f49fea93533d1aa52aR70-R72)

**Comment by nle-odoo** [comment]
Looks ok

@amoyaux your alternative was to have a constraint (python constraint in stable because there could already be existing records) so you can't put orderpoint on kits (or change a product to it that has orderpoint) and the user for that would need if the kit is 1 apple, 2 sugar to have orderpoint of 10 apples 20 sugars (instead of orderpoint of 10 kit)

seems workable, just that if there is lot of components or kits (or components of kits change then you need to change each orderpoint) it's not very friendly

**Comment by amoyaux** [comment]
Ok for me

**Review by nle-odoo — APPROVED** [review]
ok then, I think it's ok to merge nearly

just a last point I'm not sure about:

```py
qty_per_kit = bom_line.product_uom_id._compute_quantity(uom_qty_per_kit, bom_line.product_id.uom_id, raise_if_failure=False)
```

qty_per_kit is the number of product (in the `component.uom_id`) needed for a kit

in:

```
qty_in_progress = orderpoint.product_id.uom_id._compute_quantity(product_qty, orderpoint.product_uom, round=False)
```

`product_qty` is in `component.uom_id` unit of measure so it's already correct and should not be transformed from kit product uom to orderpoint uom

On the other hand, the orderpoint quantity should be in the orderpoint.product_uom so this should end by something like this:

```diff
- res[orderpoint.id] = min(ratios_total or [0]) - min(ratios_qty_available or [0])
+ product_qty = min(ratios_total or [0]) - min(ratios_qty_available or [0])
+ res[orderpoint.id] = orderpoint.product_id.uom_id._compute_quantity(product_qty, orderpoint.product_uom, round=False)
```

when it is ready unless there is other report, you can r+:

robodoo delegate+

**Comment by adwid** [comment]
robodoo r+

**Pull request closed without merging**
