### PR TITLE
[IMP] sale_stock: improve the error message

### PR DESCRIPTION
**Pull request by mba-odoo**
Currently, User/validation errors are sometimes not correct in English and/or quite obscure and don't help the user understand/solve the issue.

So in this commit, do some copywriting to make the experience better.

task-2615469

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
LGTM, thanks. 🙂

**Review by xavierbol — APPROVED** [review]
LGTM, thanks. 🙂

**Review by IT-Ideas — APPROVED** [review]
Thanks 🙂

**Comment by IT-Ideas** [comment]
@robodoo r+

**Pull request closed without merging**
