### PR TITLE
[MERGE] *: remove a lot of legacy code (mainly basic views)

### PR DESCRIPTION
**Pull request by aab-odoo**
This PR removes the legacy implementation of the form, kanban and
list views and view dialogs. It also removes the legacy view widget
registry, and all legacy widgets it contained. The legacy field registry
couldn't be removed yet as some fields are still used (e.g. in client
actions: FieldMany2One, FieldMany2ManyTags...), and sometimes
accessed from that registry (e.g. uom service). More clean up will
come later. Note that all tests using legacy views have thus been
removed, even though the tested feature might still remain (e.g.
FieldMany2One tests have been removed, but that field is still there).
However, those features are deprecated and unlikely to evolve. They
should be removed in the next saas, or the one after.

This PR also removes the legacy data export dialog (and the data.js
file which was deprecated since v11).

Finally, this PR removes the basic views benchmark page, alongside
the benchmark library which was no longer used.

Task 3168640

### CODE REVIEW

**Review by Julien00859 — APPROVED** [review]
ok for the framework scope:

* odoo/tests/common.py
* debian/copyright

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by bouvyd** [comment]
holy macaroni!
genie jaw drop

**Comment by aab-odoo** [comment]
robodoo r+ (rebased + fix bug in many2one)

**Pull request closed without merging**
