### PR TITLE
 [REF] l10n_at: complete refactoring

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Austrian Localization completely refactored

@jco-odoo 
Let's do it :wink: 

Info: @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by oco-odoo** [comment]
@wtaferner We got a ticket about people migrating to v13 and getting nothing anymore in their tax report because of this refactoring, which is pretty usual with such heavy changes, as we don't keep any mapping between old and new report lines, and so can't apply the right tags on the move line :/ We need such a mapping. Could you help us with that? Basically, we "simply" need to know how the content of each line of the v12 (or 12.3) report can be translated into the new one. In essence: in what line does each amount go? 

Thanks in advance for your help, and I hope everything is as fine as possible for you in the current context :)

**Comment by oco-odoo** [comment]
@wtaferner Any help on this?

**Comment by wtaferner** [comment]
> @wtaferner Any help on this?

Are the migration scripts open source and is it possible to contribute publicly yet?

So, yes, I could probably help (besides none of my customers would have any benefit for providing Odoo S.A. the help for this additionally to the contribution itself which was intended to enable also others to contribute on a much better base for Austria).

On Github I expect only communication about the open source part of Odoo which is certainly not true for the migration scripts, right? It is not even Enterprise where I could see any code...it is within a black hole of the money machine of Odoo S.A. which is certainly not depending anymore on migration code 😉 

Would you be happy to contribute in such a setting?

So, please keep in mind that it is probably better to contact me for such inquiries on other (private) channels to see if we can arrange a quick win together as normally I do want to help  in case it is reasonable and beneficial for the greater good.

**Comment by oco-odoo** [comment]
@wtaferner Alright, I'm sending you a mail then. My aim is simply to make it work, and avoid people facing this kind of weird issue when migrating. I pinged you here because I found it easier to keep track of all this.
Just to be clear: we just need a bit of functional guidance here, we'll take care of the technical part of it.

**Pull request closed without merging**
