### PR TITLE
[FIX] l10n_be: CoA fix (accounts 446000 => 460000 and 461000)

### PR DESCRIPTION
**Pull request by qdp-odoo**
- Remove the deprecated 446000 Acomptes reçus account
 - Create a new account 461000 Acomptes reçus (Current Liabilities)
 - Create a new acompte 460000 Acomptes à recevoir (Current Liabilities)

Was task 2205560.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
please note that I don't see the point fixing older stable versions since fixing the templates would only help new installations, so the latest stable version _is_ enough

**Comment by nim-odoo** [comment]
Thanks a lot! We usually apply such fixes in old stable so we can simply suggest the customers to upgrade the module. By the way, we can't delete an account, even in master: we would have past entries not linked to any account, so not good :smile: 

I backported in v12 and added the deprecated flag in https://github.com/odoo/odoo/pull/46694
In v11: https://github.com/odoo/odoo/pull/46691

Since the commit will reach v13 by forward-port, I am closing this one.

Thanks again!

**Comment by qdp-odoo** [comment]
@nim-odoo they'll upgrade the module to get the coa template upgraded and then? their non-template CoA will still be wrong... 

And I don't get your point about removing accounts, I bet you're still refering to the non-template account which is irrelevant. I propose you to r- your PR and r+ this one insteand, imfao

**Comment by nim-odoo** [comment]
Indeed, my bad, since it is for templates it doesn't matter. Still, it can be useful to have the CoA up-to-date in all stable versions since people might still create new DB in v12 (not on our SaaS, though). Moreover, that also applies in the creation of a new company.

robodoo r+

**Pull request closed without merging**
