### PR TITLE
[ADD] account: Invoice residual shall not change with FX differences

### PR DESCRIPTION
**Pull request by hbto**
Main
-
Mexican Law requieres to Enterprises make realization entries for the Payables/Receivable in the invoices, and their taxes, and their realization, must be done in separate ways, without mixing them, gains & loss, because according to Income Tax Act the must be treated as interest.

Justification
-
In the following Slides we have the legal justification for having done a separate FX difference Journal Entry and why they are being reconciled in the way we have depicted in this PR.

Slides in Spanish: https://docs.google.com/presentation/d/15E-xUNEIiQ2pWOfJsQ-uEglxhOqgGd1G6LBY_BmqQ2E/edit#slide=id.p5
Slides in English: https://docs.google.com/presentation/d/1ltjcJ1cYmhgXU8YaQCu2rRFg2ZJl95zcy7jk3sJdO68/edit#slide=id.p1

Explanation
-

        Company's Currency EUR

        Having issued an invoice at date Nov-21-2018 as:

        Accounts         Amount Currency         Debit(EUR)       Credit(EUR)
        ---------------------------------------------------------------------
        Expenses            5,301.00 USD         106,841.65              0.00
        Taxes                 848.16 USD          17,094.66              0.00
            Payables       -6,149.16 USD               0.00        123,936.31

        On Nov-30-2018 user issues an FX Journal Entry as required by law:

        Accounts         Amount Currency         Debit(EUR)       Credit(EUR)
        ---------------------------------------------------------------------
        FX Losses               0.00 USD           1,572.96             0.00
            Payables            0.00 USD               0.00         1,572.96

        On Dec-31-2018 user issues an FX Journal Entry as required by law:

        Accounts         Amount Currency         Debit(EUR)       Credit(EUR)
        ---------------------------------------------------------------------
        Payables                0.00 USD           4,475.97             0.00
            FX Gains            0.00 USD               0.00         4,475.97

        This can continue for several months so far the invoice remain unpaid.
        Leading to payments to the Tax Statutory Authority because of the Gains, 
        in the realization, and thus complying with the law.

Issue
-
Having the need to comply with the law in the detailed way we have depicted above. We have encountered with the following issue:
As of now when reconciling a FX Journal item (debit) to Payable (credit) -- conversely for Receivable -- it is regarded as a payment, hence reducing the amount residual in the Invoice Currency, in this case Invoice currency != Company's currency. In this case FX Difference shall not be regarded as Payment, the debt must be kept the same to be realized when the transaction is closed, fully paid or collected.

**Update:** A video has been added to this description for better explanation of the issue.

External Documentation
-
https://coem.mx/tratamiento-la-fluctuacion-cambiaria/

This procedure has been verified by a third party consultant and has been deemed abiding to law.

Video
-

https://youtu.be/Oq9Zyu1WyRk

Opw & Issue
-
OPW 1943518 / https://github.com/odoo/odoo/issues/31294

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hugho-ad** [comment]
OPW 1943518

**Comment by qdp-odoo** [comment]
I"m sorry dudes, I'm reading carefully and I just don't get what's the issue and what's the failing use case. :sob:

**Comment by hbto** [comment]
@qdp-odoo I have update description with Issue and Video


https://youtu.be/Oq9Zyu1WyRk

**Comment by qdp-odoo** [comment]
thanks for the video, the use case is effectively much clearer.

Nevertheless, I don't agree with how you deal with your currency provisioning.
1°) the provision of November should be reversed on the 1st of December, and the provision of December should be computed based on the new rate only
2°) the provisioning entry should not be reconciled with anything. The fact the foreign currency rate changed doesn't affect how much your customer owns you at all and shouldn't be reflected at all on the invoice or in partner reports.

This is at least how we deal with it here (I believe it's True for Belgium, France, Switzerland... maybe the whole Europe?). We have currently a WIP branch to implement this feature, feel free to test and give your feedback on it: https://github.com/odoo/enterprise/pull/3334

To conclude, I don't see any reason to apply such risky changes in the residual amounts computation. Let me know your thoughts

**Comment by nhomar** [comment]
@qdp-odoo Falling appart with what @hbto think.

The revaluation is **not** a report **only** you must/need affect accounting.

**Comment by qdp-odoo** [comment]
@nhomar That's also what I mean. Please test the branch: we're making, based on the report, a journal entry which will be auto-reversed at the end of the month so that we can start the next month with fresh new provision based on what real risks remain

**Comment by jpp-odoo** [comment]
After discussion with @qdp-odoo, I'm closing this PR, the proposed modifications are too important to be done in a stable branch. Please test the branch odoo/enterprise#3334 and give your feedback on it.

Regards,

Jorge

**Comment by hbto** [comment]
@jpp-odoo 

Has you read the legal justification of the PR?

https://docs.google.com/presentation/d/15E-xUNEIiQ2pWOfJsQ-uEglxhOqgGd1G6LBY_BmqQ2E/edit#slide=id.p5

**Comment by hbto** [comment]
@jpp-odoo 

http://imcp.org.mx/wp-content/uploads/2014/03/ANEXO-NOTICIAS-FISCALES-79.pdf

Look for VII-P-1aS-791  in page 8.

**Pull request closed without merging**
