### PR TITLE
[FIX] Partner form view supplier invoice smartbutton incorrect amount

### PR DESCRIPTION
**Pull request by CasVissers-360ERP**
[FIX] Partner form view supplier invoice smartbutton shows incorrect amount of invoices since it doesn't show supplier credit invoices.

Description of the issue/feature this PR addresses:
Smartbutton on partner shows incorrect amount of supplier invoices.

Current behavior before PR:
Supplier credit invoices are not shown.

Desired behavior after PR is merged:
All invoices are shown.

Issue also present in new version.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@nim-odoo what do you think about it?
If accepted, should change the action too to display the supplier refunds too.

https://github.com/odoo/odoo/blob/8e63bcb47c72240f5d520f157b0ae5ffa291a714/addons/purchase/views/res_partner_views.xml#L50-L55

**Comment by nim-odoo** [comment]
@mart-e that makes sense, but since it implies upgrading the module to a have consistent count, I wouldn't do it in stable.

**Comment by mart-e** [comment]
Indeed, somebody only updating the source code would get an inconsistent result between the number and the result.
@CasVissers could you retarget the master please?

**Comment by CasVissers** [comment]
@mart-e Retargeted to the master branch.

**Comment by CasVissers** [comment]
@mart-e  Created PR #28161

**Pull request closed without merging**
