### PR TITLE
[MERGE] (test_)(mass_)mail(_full): reorganize test classes and helpers

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
PURPOSE

Improve marketing automation tests: improve their reading, add more tests
and notably SMS tests. For that purpose clean helpers and tools.

SPECIFICATIONS

Add some helpers to improve marketing tests (click on SMS, find sms / mail
based on data available in tests, ...).

Modules holding tests and helpers

  * link_tracker: mainly mock, asserts and tools for link tracker tests
    (MockLinkTracker);
  * mail: mainly gateway mock and base for mail tests
    * MockEmail -> mocks for mail gateway;
    * MailCase -> tools and asserts for mail tests;
    * MailCommon ->     base for mail functional tests);

  * sms: mainly SMS gateway mock and base for sms tests
    * MockSMS -> mocks for SMS gateway;
    * SMS Case -> tools and asserts for mail / SMS tests;
    * SMSCommon -> update of MailCommon with SMS capabilities);

  * mass_mailing: mainly asserts and tools for mass mailing tests
    * MassMailCase -> update of MailCase for mass mailing tools and asserts;
    * MassMailCommon -> update of MailCommon with mass mailing);

  * mass_mailing_sms: mainly asserts and tools for mass SMS tests
    * MockMassSMS -> update of MockSMS for mass SMS tools and asserts;
    * MassSMSCommon -> update of MassMailCommon with SMS capabilities);

Modules for tests

  * test_mail: module for mail app tests (TestMailCommon);
  * test_mass_mailing: module for mass mailing app tests (TestMassMailCommon);
  * test_mail_full: tests integrating all discuss features, currently mainly
    mail and SMS (TestMailFullCommon);

Enterprise: update test_mail_enterprise and test_marketing_automation

LINKS

Task ID 2247037
Community PR odoo/odoo#50384
Enterprise PR odoo/enterprise#10266
Upgrade PR odoo/upgrade#1122

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@seb-odoo just trying to dépatouiller a bit the bordel in various test modules ... if you want to have a look. Globally I try to have asserts and helpers available in some common / mock classes, and have functionnal data separated from those tools. It is a bit complicated because we have

  * mail
  * sms
  * mass_mail
  * mass_sms
  * combination of everything
  * marketing automation in enteprise that uses a bit of all

Bloup !

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by seb-odoo** [comment]
Noted, thanks for the heads up. I won't really have time to check it if the r+ is that fast, but at first glance it seems reasonable, so I don't really mind not having to check in details.

**Comment by tde-banana-odoo** [comment]
> Noted, thanks for the heads up. I won't really have time to check it if the r+ is that fast, but at first glance it seems reasonable, so I don't really mind not having to check in details.

It was a mistake actually ^^ .

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Pull request closed without merging**
