### PR TITLE
[FIX] project_issue: Stages disappearing in  kanban view of project issues

### PR DESCRIPTION
**Pull request by danidee10**
Description of the issue/feature this PR addresses:
This PR aims to fix the problem where stages in the kanban view of project issues weren't visible if they had no issue(s) attached to them.

Current behavior before PR:
Stages in the kanban view weren't visible if they had no issue(s) attached to them, this prevented users from easily moving issues between stages (this is a major advantage of the kanban view) without going back to the form to change the stage from the status bar at the top of the form.

Desired behavior after PR is merged:
Stages without issues are now visible, and stages which have their 'fold' value set to true are also folded by default in the kanban view.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by danidee10** [comment]
@odony please you or someone else should review, i feel my PR has been abandoned. thanks

**Comment by dreispt** [comment]
I'm not aware that this is an Issue.
Can you provide a sequence of steps to reproduce the problem on RunBot?

**Comment by danidee10** [comment]
when you open the odoo 8 branch on runbot
Under project click on issues (this will open a kanban view showing all stages and the associated issues below them as cards)
Click on 'Add a new column' beside the create button and create a new stage (i created Test Stage) after saving it it appears on the kanban view, but once you refresh the page and check again, the new column (Test stage) is gone because there is no issue in that stage.

The only way the issue will become visible again is to edit an issue from the form view and change the stage to the new stage you created (Test stage). or at the time of creation drag any issue from another stage to it.

**Comment by danidee10** [comment]
Good day @dreispt ....were you able to reproduce the behaviour?

**Comment by danidee10** [comment]
@dreispt and @odony it's almost 30 days and this PR hasn't gotten much attention. 

Am i missing something in my PR?

Sorry to mention the two of you directly. but i didn't know of any other way to communicate.

**Comment by danidee10** [comment]
Closed due to lack of attention :(   (i also want to open another PR )

**Pull request closed without merging**
