### PR TITLE
[FIX] base_import: Get error with right name of the line

### PR DESCRIPTION
**Pull request by jbm-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@jbm-odoo please don't forget to give meaningful names to your PR

**Comment by jbm-odoo** [comment]
@tivisse

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
