### PR TITLE
Replaced account_invoice workflow with blinker signals

### PR DESCRIPTION
**Pull request by agb80**
Odoo workflow framework have some limitations like context propagation
they are very slow, and others, you can read follow links:

https://www.odoo.com/nl_NL/groups/community-59/community-9313683?mode=date
https://code.launchpad.net/~openerp-community/openobject-server/context-in-workflows/+merge/85518
https://www.odoo.com/fr_FR/forum/help-1/question/big-issue-untraceable-workflow-stucked-73306
We have been facing a problem with several of our customers where
invoices where stuck at Open state even Remain Balance is zero,
the origin was always a missing workflow instance on database.

So instead of mess with the Odoo workflow engine we decided to replace
the invoice workflow with blinker signals, that solves the 3 problems
mentioned above for us.

I'm pretty sure this commit has no chande to be merged on master neither
v7.0 branch but don't found any way to implement this change on a module
neither could figure on how to apply a monkey patch to account addon,
the intention is to get some retroalimentation and know if will be a
better aproach for make this change.

### CODE REVIEW

**Comment by nhomar** [comment]
We fully use workflow on v7.0 even mixed with our localization version (which have workflows embeded also) exactly what are the issues you are facing, if you share issues one by one, it can be better the help and feedback given.

**Comment by agb80** [comment]
@nhomar the problem that force us to make this patch was invoices that were not set into Paid state even when the remaining balance were zero. And the invoices were not take into the correct state even if you make the reconciliation again, neither when you break reconciliation and make it again and even when you totally delete all payments and try to capture the payment again.

After further investigation we found that the problem were the register in workflow table related to the invoice were vanished, I mean, there is no register for that invoice.

¿How do you solve it?

**Comment by nhomar** [comment]
There is an old patch which solve this issue in v7.0 I do not remember
speficifically (it was solved through our enterprise license and applied I
remember )

But by far make a 2000 patch because of such error is a huge mistake in my
opinion.

Let me look for the exact commit and I come back

On Friday, September 4, 2015, agb80 <notifications@github.com> wrote:

> @nhomar <https://github.com/nhomar> the problem that force us to make
> this patch was invoices that were not set into Paid state even when the
> remaining balance were zero. And the invoices were not take into the
> correct state even if you make the reconciliation again, neither when you
> break reconciliation and make it again and even when you totally delete all
> payments and try to capture the payment again.
>
> After further investigation we found that the problem were the register in
> workflow table related to the invoice were vanished, I mean, there is no
> register for that invoice.
>
> ¿How do you solve it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/pull/6855#issuecomment-137810750>.
>


-- 
--------------------
Saludos Cordiales

CEO at Vauxoo <https://www.vauxoo.com> Odoo's Gold Partner.

[image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
<http://about.me/nhomar?promo=email_sig>

**Comment by agb80** [comment]
Made the patch on top of OCB branch instead of vanilla Odoo 7.0 that's where the big amount of changes comes from. Didn't care to change because nobody seems to care about it.

If you are really interested the actual patch is this: https://github.com/OpenPymeMx/OCB/commit/fb28f8c0a552067aaa593a80128ed44a6ba3ab78

we are working on production with several customers now and works really well

**Pull request closed without merging**
