### PR TITLE
[FIX] crm: probability is always show

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
In the tree view probality is always show, but not in the view form.
--> hide probality in the tree form too

This PR apply the behavoir of the form view : https://github.com/odoo/odoo/blob/11.0/addons/crm/views/crm_stage_views.xml#L43

cc @tde-banana-odoo

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
cc @tivisse

**Comment by fmdl** [comment]
OPW : #1913902

**Comment by fmdl** [comment]
This PR apply the behavoir of the form view : https://github.com/odoo/odoo/blob/11.0/addons/crm/views/crm_stage_views.xml#L43

**Comment by fmdl** [comment]
cc @nim-odoo

**Comment by fmdl** [comment]
ping @tde-banana-odoo

**Comment by pedrobaeza** [comment]
I have come to this through codetriage.com. Is this still relevant?

**Comment by tde-banana-odoo** [comment]
With PLS and automatic computation of probability I think it does not apply anymore.

**Comment by pedrobaeza** [comment]
@fmdl would you mind closing this then?

**Pull request closed without merging**
