### PR TITLE
[FIX] web: fix user name overflowing

### PR DESCRIPTION
**Pull request by dhrs-odoo**
In this PR, we have fixed if user name overflowing. 

task-3248965

### CODE REVIEW

**Review by auon-odoo — CHANGES_REQUESTED** [review]
Why is the class needed on 2 elements? That is why a commit message is useful :angel:

**Comment by dhrs-odoo** [comment]
Hello @auon-odoo 
To apply the text-truncate class to text within a span element, you can wrap the span element within a div element and apply the text-truncate class to the div. but as it is stable  version so we have achieved that behavour by applying text-truncate in both tags.

**Comment by auon-odoo** [comment]
@dhrs-odoo But why not on the div?

**Comment by dhrs-odoo** [comment]
Hello @auon-odoo 
div will only truncate the text if the parent element (span) has a fixed width
if we give span fixed width than also text-truncate in div will work

**Comment by auon-odoo** [comment]
So, you added the class `text-truncate` on the span so that it can't expand beyond its container's width, and so the `text-trucate` of the div can apply. `mw-100` accomplishes that + it says what it does :slightly_smiling_face:

**Comment by dhrs-odoo** [comment]
Hello @auon-odoo I will add mw-100 in span and will add text-truncate in div element
Will it be okay ?

**Comment by dhrs-odoo** [comment]
Hello @auon-odoo I will add mw-100 in span and text-truncate in div element
will it be okay ?

**Comment by auon-odoo** [comment]
@dhrs-odoo perfect, thank you! :ok_hand:

**Comment by dhrs-odoo** [comment]
Hello @auon-odoo Changes has been implemented
Thank You !

**Review by auon-odoo — APPROVED** [review]
Looks good to me, thanks! :fire:

**Comment by auon-odoo** [comment]
Sorry to insist, but it would be great to put a little more information in your commit message :pray:

**Comment by dhrs-odoo** [comment]
Hello @auon-odoo Sure !!
Thank You!!

**Comment by xavierbol** [comment]
I will let @odoo/rd-framework-js team doing the final review. 🙂

**Pull request closed without merging**
