### PR TITLE
[IMP] mail: add model for message reactions

### PR DESCRIPTION
**Pull request by seb-odoo**
Add the model in the freeze for next version, the interface is not fully ready
to merge yet but it will be added in https://github.com/odoo/odoo/pull/75630

Part of task-2361194

### CODE REVIEW

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo retry

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by sdegueldre** [comment]
@robodoo  r+

**Comment by tde-banana-odoo** [comment]
> Add the model in the freeze for next version, the interface is not fully ready
> to merge yet but it will be added in #75630

Wow.

**Pull request closed without merging**
