### PR TITLE
[IMP] point_of_sale: Repair error in POS Sales with two journals in different currencies

### PR DESCRIPTION
**Pull request by ysantiago**
**Description of the issue/feature this PR addresses:**

The issue this PR try to solved was reported in [odoo/issues/26641](https://github.com/odoo/odoo/issues/26641)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ysantiago** [comment]
Hello @rda-odoo 

I found this solution and it is fairly simple. Even if it is a strange feature, in Tourist sites in México this is a common practice (receive Dollars in cash and set a fixed currency rate on them).

Can you consider this solution or did you find something wrong there?

**Comment by ysantiago** [comment]
@nhomar

**Comment by gustavovalverde** [comment]
This seems like an interesting feature, is there any roadmap on this one? Restaurants commonly have this situation with tourists.

**Comment by ysantiago** [comment]
Hello @switch87 

.

**Comment by ysantiago** [comment]
Hello @switch87

Do you have any information about this PR?

**Comment by nirojdyola** [comment]
I tested in my machine and it gives me error "module_account" key error.

**Comment by switch87** [comment]
@ysantiago the value of Euro and Dollar should not be the same. In your code this is not checked. If I pay €2 for a $1.20 product a return of €0.8 is wrong.

**Pull request closed without merging**
