### PR TITLE
[IMP] mail: prevent creation of activities to users that have no acce…

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
…ss to document

This commit is related to task ID 58968 .

Task: https://www.odoo.com/web#id=58968&view_type=form&model=project.task&action=333&active_id=965&menu_id=4720

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@tde-banana-odoo 
I was wondering if it was on purpose that there is no domain set or why it is even possible. Isn't it more like a bugfix for v11? :wink:

**Comment by tde-banana-odoo** [comment]
"I was wondering if it was on purpose that there is no domain set or why it is even possible" Not sure to understand. What domain are you talking about ? A domain on user_id field ? As it is based on access rights it is complicated to do in a domain ... it would mean reading all existing users, checking their access rights and then returning a domain like [('id', 'in', [a_lot_of_ids])]. Not sure it is better :) .

**Comment by wtaferner** [comment]
Well, I mean that all users (including the portal users) can be assigned to activities, but it seems that it is/was intended. Still, as it is the normal use case to have internal users to be assigned there should be some dynamic filters (like only internal_users) to avoid mistakes. This could maybe be an option and configuration? 

Anyway, just my 5 cents and it seems that it is wanted that portal users are part of this and I agree with the intention.

**Comment by tde-banana-odoo** [comment]
Well actually your first remark is correct. Portal users don't have access to activities, as it could be a leak of internal information and they don't have any interface to handle them. We could add a domain to already remove non employee users.

In addition to that keeping the check for access right check is interesting for employee users. In most cases it will be ok as normally you assign activities to people working in the same environment as you. We had issues for example when assigning an activity on a lead to a salesman that have no access to the opportunity (own documents only access right).

**Pull request merged**
