### PR TITLE
[IMP] l10n_my: add tax report

### PR DESCRIPTION
**Pull request by vin-odoo**
Adds the SST-02 tax report to the Malaysian
localization

Task id # 2868179

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vin-odoo** [comment]
Would be best to do it at least in 17 I guess.

I'll let the reviewer decide if it's fine to do so :)

**Review by JulienAlardot — CHANGES_REQUESTED** [review]
Please do the report in english and add the local translation in .po files (and add the .pot)
IMO, we can move that to 17 
@jbw-odoo do you agree?

**Comment by vin-odoo** [comment]
@JulienAlardot @jbw-odoo The changes have been done :)

**Comment by JulienAlardot** [comment]
@jbw-odoo LGTM

**Review by JulienAlardot — APPROVED** [review]

**Pull request closed without merging**
