### PR TITLE
[FIX] Internal Server Error when accessing wishlish

### PR DESCRIPTION
**Pull request by TimLai125**
**Description of the issue/feature this PR addresses:**
1. Portal user adds product to the wishlist
2. An Internal user change the product to "unpublished"
3. Portal user accesses the wishlist page, i.e. /shop/wishlist

**Current behavior before PR:**
Since portal user are not allowed to access "unpublished" products, ref: https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/addons/website_sale/security/website_sale.xml#L4-L13
Currently, portal user will get "Internal Server Error" when accessing the wishlist page.

**Desired behavior after PR is merged:**
- The wishlist becomes accessible even there are unpublished products in the list.

**Related Github Issue**
https://github.com/odoo/odoo/issues/24618

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by TimLai125** [comment]
@JKE-be I think the current design has a limitation. Once the product is unpublished, it will be abandoned that kept in the wishlist table. I think we should have a way to delete those records.

**Comment by yostashiro** [comment]
I prefer the approach of making `wishes` `wishes.sudo()` as described in the first commit https://github.com/odoo/odoo/pull/24857/commits/7458b028bfb2776305ab2ceba4a82b2a69f028d3 so that the portal user is not confused when a product in their wishlist is unpublished - with the current code of this PR, the portal user will be suddenly deprived of visibility for products they have added to wishlist but were later unpublished without any notification.  I'm afraid some users will be confused.

**Comment by yostashiro** [comment]
> filter on published instead of add condition on each line

@JKE-be I talked with @TimLai125 and we think we should apply this commit https://github.com/odoo/odoo/pull/24857/commits/3170c32aabf5380004d239565edcc1ee976316b9 instead of going with your suggestion because of the reasons we mentioned (i.e. portal user may be confused if some products suddenly disappears from wishlist, and these unpublished wishlist products cannot be removed through user interface - it will I guess be an issue if you want to delete such product, for example).  While I understand not showing unpublished records would also make sense, I still think we provide the visibility of the full list including unpublished ones. Would you please check again and advise which approach we should take?

**Comment by JKE-be** [comment]
This way allow to be fixed without an update of the module/views.

Imo, if you unpublish a product, it is because you don't want that the end user see it again.
If it was just a problem of stock , stop seller, or anything else, you should use other warning based on qty e.g. and so the product will be always visible.

**Pull request closed without merging**
