### PR TITLE
Master  load jco

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@qdp-odoo Can you have a first look before I squash the commits?

**Comment by qdp-odoo** [comment]
ok for me but you'll need to clean the history

**Comment by jco-odoo** [comment]
@qdp-odoo updated

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
