### PR TITLE
[FIX] sale: product change should not be done in a wrong state.

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Possible solution for https://github.com/odoo/odoo/issues/20217

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
OPW-776921

**Comment by amoyaux** [comment]
Seems a good draft. I will complete it for timesheet. @wtaferner Wh did you also put the check in write? I hope there is no code that change the product_id on sale_order_line.

**Comment by gdgellatly** [comment]
@wtaferner weird thing is I reported it because I think in certain situations it is desirable to change product (like customer wants different colour).  I'm ok with the fix, as I can override it and no way the logic for changing a product hits core stable if its not already intended.  While I expect it to be less code than in v7, it was 700 lines to handle everything and one function had 13 logic branches. I was mostly excited because I hoped it was an intended but not working function to save me days of work.

**Comment by wtaferner** [comment]
@amoyaux 
Explained it somehow in your PR...it is just to have guaranteed that it won't happen independent from the UI.

@gdgellatly 
You are right, I think this is what is now accomplished I guess, but the sale order flexibility is now really good IMHO.

**Pull request closed without merging**
