### PR TITLE
[FIX] calendar view `write_model` + `write_field` mechanism doesn't w…

### PR DESCRIPTION
**Pull request by iledarn**
…ork as expected since we always have hardcoded 'partner_id' instead of value of `write_field`

Description of the issue/feature this PR addresses: this fix is related to user's filter mechanism in calendar views

Current behavior before PR: No matter what is in `write_field` the `partner_id` is used when creating a record in `write_model`

Desired behavior after PR is merged: the field defined in `write_field` should be used instead of using hard coded `partner_id`

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by iledarn** [comment]
It seems that nobody ever used this sidebar filter feature of a calendar view. The only place in Odoo that facilitates it - is in the standard calendar addon. But there is `write_field="partner_id"` and no error occurs

**Comment by iledarn** [comment]
It was fixed in the master branch, here
https://github.com/odoo/odoo/pull/30110

**Comment by mreficent** [comment]
Then, shouldn't be better if you adapt this PR with the changes in `master`? Maybe by doing a pure backport of https://github.com/odoo/odoo/pull/30110/commits/70c6d3b04c43a36446052c4ab8976c3d50ed4666?

**Comment by iledarn** [comment]
Yes, I'd better cherry-pick this - https://github.com/odoo/odoo/commit/70c6d3b04c43a36446052c4ab8976c3d50ed4666

**Comment by iledarn** [comment]
Ok, I've cherry-picked. Do I need Lucas Lefèvre's Odoo CLA signature now?

**Comment by mreficent** [comment]
I don't think so, because @LucasLefevre is an Odoo worker, right @tivisse? cc: @mart-e

**Comment by mart-e** [comment]
No he is but he did not configured correctly his git :wink: 
I amended the commit to use the correct email address.

**Comment by LucasLefevre** [comment]
@mart-e  My git settings have been fixed since. Thanks

**Comment by mart-e** [comment]
@LucasLefevre thanks, any objection to backport this commit in 12.0 ?

**Comment by LucasLefevre** [comment]
@mart-e No objection :wink:

**Comment by mart-e** [comment]
Thanks

@robodoo rebase-ff r+

**Pull request closed without merging**
