### PR TITLE
[CLA] Update iterativo SRL, adding Jose

### PR DESCRIPTION
**Pull request by gustavovalverde**
Description of the issue/feature this PR addresses:
Update CLA

Current behavior before PR:
Outdated CLA

Desired behavior after PR is merged:
Beautiful CLA

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Congratz on the new employee @gustavovalverde 😄

**Comment by mart-e** [comment]
What's the `iterativo.do` file?

**Comment by gustavovalverde** [comment]
Something that shouldn't be there 😅

**Comment by mart-e** [comment]
Thanks, merged at https://github.com/odoo/odoo/commit/3d653a2c029a218750ae80383d38784b3efb20d3

**Pull request closed without merging**
