### PR TITLE
[FIX] hr_payroll_account: respect partner payment term date for maturity

### PR DESCRIPTION
**Pull request by wtaferner**
### Description of the issue/feature this PR addresses:
The intention behind this PR is to make it possible to correctly retrieve the date maturity of an account which can be reconciled and skip the partner for all the other accounts as it is of no interest afaik.

### Current behavior before PR:
It is not possible to have a correct date maturity directly from a payroll slip but is badly needed to have correct due dates for payables.

### Desired behavior after PR is merged:
In case a partner is defined the date maturity is calculated from the partner supplier payment term

@nim-odoo 
May I ask you to review and merge asap. 
About the partner on the other side...is there a use case and specific reason why we normally have both sides related to a partner even though it is normally just used for reconciliation?

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
OPW-693288

**Comment by nim-odoo** [comment]
Hi,

Definitely not a bug, since it was not intended to work this way. Although, I agree that it is a nice workaround to use the existing fields to compute the maturity date. It will be transferred for feedback.

**Comment by pedrobaeza** [comment]
@wtaferner, do an OCA (or not) module that includes this behavior.

**Comment by wtaferner** [comment]
Hmm, expecting that the contribution partner is having a due date by LAW I would say it is even a critical bug. And as the posted move is not editable anymore, it is even more a wrong due date and therefore wrong. Of course we could also add a field if you want to ;-)

**Comment by wtaferner** [comment]
@pedrobaeza 
It should be fixed in the core. A module is a pain as if you take a look at the method...it is again quite doing a lot in order to inherit without completely overriding it.

**Comment by nim-odoo** [comment]
This has been working without proper maturity date from the beginning (bbbf3a272ca0d9250f88dfd71663bf2ec8191729, in 2010). I don't deny that the maturity date can be legally required in some countries, or that the method cannot be easily overridden. However, the field "Vendor Payment Term" is obviously not intended to be used in this way:

> This payment term will be used instead of the default one for purchase orders and vendor bills

cc @beledouxdenis

**Comment by wtaferner** [comment]
Well, in reality you have different payment terms based on each tax, so it would be a possibility to add on the rule a payment term which would overrule the payment term of the supplier payment term (and the partner is definitely our supplier in this use case). And if no payment term can be retrieved the standard date would be applied.

As we are on stable there is no way to add new fields so I think my solution would at least give the possibility to make it happen as needed...it needs to be corrected and improved in master anyway.

**Pull request closed without merging**
