### PR TITLE
8.0 no portal no chat

### LINKED ISSUE #5299: [8.0] im_chat should not be auto_install=True
Why was im_chat made auto_installable? It is not useful to everyone, requires some specific setup to work correctly, and as far as I can tell is not a dependency of anything which gets installed by default. 

The current situation means that people who don't want that module need to uninstall it by hand after creating a new instance, which I feel is a hassle.

### LINKED ISSUE #5303: portal module should not be autoinstalled
Odoo works fine without the Portal (most of our instances run without it). Having the invitation to inspect records online under every outgoing chatter message is embarrassing for instances that run behind a firewall.

Please set autoinstall to False for this module.

### PR DESCRIPTION
**Pull request by gurneyalex**
disable auto_install for im_chat (closes #5299) and portal (closes #5303)

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
:+1: We run Odoo without these modules and it works fine.

**Comment by Yenthe666** [comment]
Great improvement. This shouldn't be installed by default and everything works fine without them. :+1:

**Comment by yvaucher** [comment]
:+1: It should be set as optional

**Comment by antonylesuisse** [comment]
I close this PR mail and chat have now been merged in v9.

**Comment by nhomar** [comment]
But this is for v8 no v9. why this modules are necesary by default on v8?

**Comment by antonylesuisse** [comment]
If you dont want to use those modules just uninstall them. It's too late now to change that in an old stable serie.

**Pull request closed without merging**
