### PR TITLE
[REF] add hook to ease overriding the merge of automatic po

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
Complete #6205 to set get_available_draft_po_ids private

@florian-dacosta @yvaucher @nim-odoo

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by sebastienbeau** [comment]
Hi I have propose an additionnal change to this branch here that integrate my need : https://github.com/acsone/odoo/pull/5

**Comment by sebastienbeau** [comment]
:+1: tested, worked perfectly

**Comment by florian-dacosta** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1: 

@jco-odoo that's the very useful hook that we discussed in the Odoo SA kitchen in Brussels quite some months ago. 'Hope this can be merged.

**Comment by laetitia-gangloff** [comment]
@nim-odoo @jco-odoo I rebased the branch, can you have a look ?

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
