### PR TITLE
[IMP] models: warn if constraint key len exceed 63

### PR DESCRIPTION
**Pull request by Xavier-Do**
Warn when constrains name combine with table name will be more than 63 characters.
This is to avoid case like the one fixed in #103148

Unlike index, since constrains name are defined in the code, we prefer to avoid automatic truncate and add a warning since devs can chose an appropriate short-enough name.

The linked fixes will just truncate the name to the max length to match the name in existing databases. Renaming could be done in other pull requests with upgrade scripts to avoid constrains re-computation.

Linked to odoo/enterprise#35424

### CODE REVIEW

**Comment by Xavier-Do** [comment]
@robodoo rebase-ff

**Review by ryv-odoo — APPROVED** [review]
LGTM

**Comment by Xavier-Do** [comment]
Just to test a new runbot feature

**Comment by Xavier-Do** [comment]
@robodoo r+

**Pull request closed without merging**
