### PR TITLE
[MERGE] mail: task-2579306 (step 1)

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2579306

### CODE REVIEW

**Review by phenix-factory — APPROVED** [review]
LGTM :+1:

**Comment by alexkuhn** [comment]
@robodoo r+ rebase-ff

**Comment by alexkuhn** [comment]
Hello @tde-banana-odoo 

We will squash commits before merge, so it doesn't bloat git history.

We don't provide much explanation because this is just code cleaning.
Not a change of architecture, not a bug to fix, nor a new feature being implemented, etc: just moving parts to where it should, so it follows the architecture we have in place in discuss (here, to be specific: move code from `components/` to `models/`).

There are lots of reasons as to why it's bad to have code in `components/`, and it's much more beneficial to have them in `models/`. But if we have to provide this explanation in each commit and task, then it's a big waste of time of writing it, at the huge cost of being very slow to merge the changes.

And I'm pretty sure most people outside Discuss team don't care on why there's this change.
If you care, then you understand. And vice-versa.
And if you don't understand and want to understand, we are happy to have a talk with a better mean of communication that commit message for such a big topic. _(our code needs cleaning and it takes time, so it's far more time efficient that way, for us and for you too)_

**Comment by tde-banana-odoo** [comment]
"But if we have to provide this explanation in each commit, then it's a big waste of time of writing it, at the huge cost of being very slow to merge the changes."

Well seems those can be squashed, then you write it once. Moreover you can also use the PR message (and simply put "see PR message for details"). And in the end you should also have a task with a pad with explanations and testing instructions, so I bet you already wrote this explanation. Or if it is not done and only present in some people's mind, that's a bad habit to do so. You are increasing the truck factor :) .

"And I'm pretty sure most people outside Discuss team don't care on why there's this change.
If you care, then you understand. And vice-versa."

That's could be valid for every commit. Why would I write an explanation on some CRM change ? Well, because other people may work in that module. You seem to think that only Discuss work in discuss, but somehow your code will end up notably in bugfix team, doing forward port of bugfixes, and trying to figure out why everything is conflicting / broken / moved / different, without any clue of "why / how / what should I do". Or maybe someone has a dev based on discuss code, sees everything is desynchronized / conflicting, tries to find the commit, and endup on a void commit linking to a void task, and has to ping people to have an explanation that could have been done in a commit message.

If you spend time doing a feature, you should also take some more time to write a commit message. In the end that's the first interface people will have when trying to figure out things when grepping / getting back in code history.

Cheers !

**Pull request closed without merging**
