### PR TITLE
[IMP] base: Clean language usability

### PR DESCRIPTION
**Pull request by LucasLefevre**
1. base: Load translation when language is activated

	Purpose
	------
	Settings > Translations > Languages > I find the language I want
	and I click on stat button to activate it.
	Now I set it up on my user, it still doesn't work > the langage has not been loaded !!!

	Specification
	-------
	When activating a language load the translation (and open the load translation wizard)

2. base: Add shortcut button to load language

	Pupose
	-------
	On the res.partner and res.user form view if you want to change
	the language, it's not easy to know where I can activate more
	langages.

	Specification
	-----------
	Add a small icon next to the language field to activate more
	languages (similar interface than to send an SMS).

3. base: Clean res.lang tree view

	1. Set limit to 200 to display all current 82 languages
	in one page (current limit is 80/82).

	2. Move some fields to debug mode.

	3. Add a button to directly load a language.

4. base: Remove Load a Translation menu

	Activating a language automatically load the translation,
	hence the menu is no longer necessary.

5. base: Don't show language if only one active

	If only one language is active, don't show in the contact
	form view (`res.partner`) the language field. Changing the language is
	not possible since there is only one language.
	Hence the field is useless and therefore hidden.

TaskID: 2026150

### CODE REVIEW

**Comment by fmdl** [comment]
Idea : Only admin user can show the globe icon, to prevent wrong language installation by a normal user.

**Comment by LucasLefevre** [comment]
> Idea : Only admin user can show the globe icon, to prevent wrong language installation by a normal user.

This exactly what `groups="base.group_system"` does.

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo merge

**Comment by mart-e** [comment]
@tivisse and how about my review ? :disappointed:

**Comment by tivisse** [comment]
Nothing seemed strange functionally. 

Is there something unclear for you ?

**Comment by mart-e** [comment]
Not unclear, just incomplete or I don't agree with all the changes. I am creating a branch to change some things. Please ask opinion before merging.

**Pull request merged**
