### PR TITLE
[IMP] web: highlighting and scrolling to a specific setting

### PR DESCRIPTION
**Pull request by jpp-odoo**
This commit, allows highlighting and scrolling to a specific setting,
from the URL anchor. This commit also allow opening a specific
application from the URL anchor.

opw-3794940

### CODE REVIEW

**Comment by jpp-odoo** [comment]
@robodoo rebase-ff

**Review by casp-odoo — APPROVED** [review]
Accounting aspect LGTM

**Comment by SimonGenin** [comment]
@robodoo r+

**Comment by SimonGenin** [comment]
@robodoo r+

**Pull request closed without merging**
