### PR TITLE
[IMP] stock: read product uom through template

### PR DESCRIPTION
**Pull request by nseinlet**
Reading the uom through the template improve
the reading speed.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nseinlet** [comment]
@rco-odoo Could you look here why this improve speed? In an ideal world, this shouldn't

@sle-odoo Could you review it?

**Comment by sle-odoo** [comment]
@nseinlet I already reported to @rco-odoo that a lot of time is spent int compute_related and could be improved by going up the relations like you did but i don't know if a patch made it to 12.0 or master. But  this kind of patch could be made all over the place in the stock code base :(

**Comment by nseinlet** [comment]
Thanks @sle-odoo  We should definitely let @rco-odoo handling this then.

**Comment by fmdl** [comment]
@nseinlet I have work on this issue of related field, https://github.com/odoo/odoo/issues/24119#issuecomment-380591547

it is the same commit of : https://github.com/odoo/odoo/commit/1ece9412be6ce30c46757a1a6a5025db62d9af85

**Pull request closed without merging**
