### PR TITLE
Fix resource.calendar backward days scheduling issue

### PR DESCRIPTION
**Pull request by npiganeau**
Fix to #4029

### CODE REVIEW

**Comment by npiganeau** [comment]
@jco-odoo Anything more I can do for this PR ?

**Comment by jco-odoo** [comment]
This looks all right.  I should merge this.

**Comment by pedrobaeza** [comment]
This patch is not correct, and tests prove it: self.date1 is 2013-02-12, that is tuesday, and 2 days more means friday (2013-02-08), because the working calendar is from monday to friday, and not 2013-02-05 like the test is asserting. See https://github.com/odoo/odoo/pull/8208 for the correct patch.

**Comment by pedrobaeza** [comment]
:-1:

**Comment by npiganeau** [comment]
@pedrobaeza The patch is correct: the working calendar defined by self.calendar_id in the tests only has attendances only on Tuesdays and Fridays and not Monday to Friday (see  odoo/addons/resource/tests/common.py lines 56 to 87) that is why Tuesday 2015-02-12 minus 2 days gives Tuesday 2015-02-05.

**Comment by pedrobaeza** [comment]
Attendances are not taken into account in this method, because you don't have attendances in the future. The problem in your patch is that you're calling `get_previous_day` 2 times, one in https://github.com/odoo/odoo/pull/4030/files#diff-3541dc176711b6cdcb21bb634c3d86d4R533 and the other in https://github.com/odoo/odoo/pull/4030/files#diff-3541dc176711b6cdcb21bb634c3d86d4R546. That's why you get to tuesday.

**Comment by npiganeau** [comment]
Actually the question is whether we have to count the starting day as the first day when day scheduling backwards or not. 

When day scheduling forward, we count the starting day as the first day because we first do a replace(hour=0, minute=0, second=0), that is before the starting day attendances. IMO, this is odd (when I count today + 2 days, I think it should give me the day after tomorrow and not tomorrow), but that's the way it is in Odoo.

When day scheduling backwards, I considered that we must also start before the attendances of the starting day and thus not count the starting day. So Tuesday 2013-02-12 00:00:00 minus 1 day gives Friday 2013-02-08 00:00:00 (We counted the attendance(s) of Friday) and minus another day gives Tuesday 2013-02-05 00:00:00 (We counted the attendance(s) of Tuesday). That is why I need an extra get_previous_day.

Now if we consider that we must count the starting day as the first day when day scheduling backwards, then that would give us 2013-02-08 indeed.

**Comment by pedrobaeza** [comment]
I think Odoo's behaviour is the correct and the same must be applied to backwards, again without taking attendances into account (you can have leaves into account, but not attendance). In your reasoning, there's also an error: the previous day to tuesday is monday, not friday.

**Comment by npiganeau** [comment]
I'm afraid you are mistaken in your understanding of resource day scheduling: it only counts days where there is at least one attendance, not Monday to Friday (Which is BTW the working week in most countries, but not all, most arabic countries have weeks from sunday to thursday or some even from saturday to wednesday).

You can see it in addons/resource/tests/test_resource.py Lines 431 & 432: date1=2013-02-12 + 5 days gives 2013-02-26 because it only counts days with attendances, that is: 02-12, 02-15, 02-19, 02-22 and 02-26.

Backwards day scheduling should, the same way, only count days with at least one attendance (which is also the case in #8208 actually, only the issue of the starting day differs).

**Comment by pedrobaeza** [comment]
Well, first of all, we are not understanding each other due to the nomenclature, that it's not the most appropiate. The model `resource.calendar.attendance` is badly named, because it's not an attendance in the classical meaning of it (someone goes to work certain date at certain time), but a slice of the working time.

Said that, then I agree that these kind of "attendances" should be taken into account for the calculation. That's what you intend to tell me I think, and both agrees, but with different terminology.

Anyway, I still think that calling twice the method `get_previous_day` is not the appropriated way of doing that, but I'm going to go deeper to tell you with data and more test cases.

**Comment by antespi** [comment]
@npiganeau, Odoo has merge this PR https://github.com/odoo/odoo/pull/8208, but it only differ from yours in test case. Fix has been merge in Odoo, that's the good new! Thanks for your contribution, anyway.

**Comment by pedrobaeza** [comment]
Well, he was calling twice the get_previous_day, so it's not exactly the same. I have a pending analysis of what @npiganeau said, but he should be wrong if the other PR has been merged...

**Comment by npiganeau** [comment]
After double thinking, considering that at any time the following should be true whatever n :

    start_date + n days - n days = start_date

then it is logical that Odoo merged #8208, so I close this PR which is wrong.

However, I will open a new one to address the issue of counting the first day (see above). In the current implementation : 

    start_date + 0 days = start_date
    start_date + 1 day = start_date
    start_date + 2 days = the day after start_date
    etc.

The same logic when counting backwards

I think that it should be : 
 
    start_date + 0 days = start_date
    start_date + 1 day = the day after start_date
    start_date + 2 days = 2 days after start_date
    etc.

**Pull request closed without merging**
