### PR TITLE
[IMP] web: Add advanced search option

### PR DESCRIPTION
**Pull request by yajo**
It allows advanced users to filter current view depending on values from related fields:

peek 2018-07-23 12-39

**Feel the power!**

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa @ged-odoo

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@ged-odoo other one waiting to know your feedback.

**Comment by mart-e** [comment]
Hi,

This is quite nice but unfortunately I have to reject this.
I have discussed this internally but this is not the direction we want to go.
Instead, we would like to clarify the existing search to make it less confusing the use of AND and OR. We do not think adding one more way to search is a good idea but instead we should improve the existing search.

**Comment by Yajo** [comment]
Well the main point is to be able to search in subfields when using related fields. It would be great if your alternative refactor on the matter includes such extra. Thanks for your time!

**Comment by pedrobaeza** [comment]
Yes, Martin, the main point to propose this is to have the ability to search through relational fields, and the simpler way to do it was through domain widget. If you have a better way, cool, but please don't lose this needed feature.

**Comment by mart-e** [comment]
I hear you and I liked this feature but not my call :-/ 
The idea is that if you have the need to make more advanced search or need to access subfields, you can use the domain widget in the "manage filters" option in debug mode.

**Comment by pedrobaeza** [comment]
@mart-e the problems with using that with "manage filters" are:

* You have to create a filter for doing it, so needing a lot of more extra steps.
* You can't combine several "advanced filters" and use the memo option, which is annoying and counter-productive.
* You can't apply "advanced filters" over existing domains: when you click on one filter, it overwrites existing domain and change it by the filter one.

So for me it's far from ideal using it there. Maybe you can rethink about this again? What about having this extra option only on debug mode?

**Pull request closed without merging**
