### PR TITLE
[FIX] account_edi_ubl_cii: remove country code from Australian ABN in

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Australian Business Number should not have country code when used in the endpoint (see https://docs.peppol.eu/poacc/billing/3.0/rules/ubl-peppol/PEPPOL-COMMON-R050/)

based on: https://github.com/odoo/odoo/pull/164945

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
CC @JulienVR

**Comment by JulienVR** [comment]
@fw-bot up to 16.0

**Comment by JulienVR** [comment]
Hello ! Could you write a commit message ? "Australian Business Number should not have country code when used in the endpoint (see https://docs.peppol.eu/poacc/billing/3.0/rules/ubl-peppol/PEPPOL-COMMON-R050/)" is enough :)

**Comment by JordiMForgeFlow** [comment]
@JulienVR commit message updated, thank you :)

**Pull request closed without merging**
