### PR TITLE
Fix 'report_webkit' module support real mako again.

### PR DESCRIPTION
**Pull request by codingforfun**
Port parts of the original 7.0 code to 8.0 to let the module support real Mako again. 
Mapping jinja2 to mako is way to limited to support all Mako features used previously. 
Fix some minor bugs too. 

From discussions among the community it seams this module will be deprecated and unsupported in the future anyway so it's mostly useful to support old reports previously written for v7 during a transition period. 
Therefore we think the current state of the module in core is not very useful because it breaks this support without making any noticeable improvements. 

This is our proposal to make things work again. 

Note: We also made this PR against the [OCA/OCB](https://github.com/OCA/OCB) fork in the first place.
https://github.com/OCA/OCB/pull/277

### CODE REVIEW

**Comment by codingforfun** [comment]
Changed the PR against upstream as well: https://github.com/odoo/odoo/issues/8782

**Comment by mart-e** [comment]
Hello,

Sorry but we used jinja for security reason. Mako has no sandboxing (cf the comment) and we do not want to allow evaluating arbitrary python code in a template.

**Comment by codingforfun** [comment]
Ok, but If I need to rewrite my reports anyway when switching from v7 to v8, why should I use mako at all and not write new reports in QWeb? So this module basically is of no use anymore if it doesn't support the old style mako reports.

**Comment by mart-e** [comment]
It support most of the mako syntax and should probably be ok with a few minor adaptations.
Of course if you can migrate your reports to QWeb, go for it.

**Pull request closed without merging**
