### PR TITLE
[IMP] web_editor, website: perf for color preview update

### PR DESCRIPTION
**Pull request by qsm-odoo**
Follow-up of https://github.com/odoo-dev/odoo/pull/1149#discussion_r900120846

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@detrouxdev Follow-up of https://github.com/odoo-dev/odoo/pull/1149#discussion_r900120846

We'll have to look into this, both updating the CSS variables on the panel and computing the o_cc presets with the hack "switch in iframe to get right colors" are actually perf consuming (to double check but a perf test on: "adding a snippet in the page -> click on the snippet", the most the two most time-consuming operation (> 200ms) are: call to `setProperty` in `setCSSVariables` and call to `node.remove()` in `_onColorPreviewsUpdate`). I made this PR (incomplete of course, the cc previews are not well styled) so we do not forget to check it.

If we decide the keep the "switch in iframe" hack, maybe there is a better way to write it (maybe just not do them one by one and retrieving the style one at a time would do the trick). We can also try not to do it at each colorpicker creation but only when they are opened.

**Review by qsm-odoo — COMMENTED** [review]
You can squash both commits (make you the author and me the co-author) and make a proper commit message (I'll probably merge this after OXP to not rush merging and potentially breaking something with a non critical fix).

**Comment by detrouxdev** [comment]
@qsm-odoo This PR is ready 👍🏻

**Review by qsm-odoo — COMMENTED** [review]
- Retargeted to 16.0, seems safe enough and the perf improvement is more about restoring the efficiency of previous versions.
- Made it a bit more stable friendly with https://github.com/odoo/odoo/compare/c60054520103e470cc7a8eb60a74c701705f8c68..148da332a9cc8e212553f3f4f45819adac498c7b
- But then I think you probably forgot to push your last version @detrouxdev because the code you made could not work properly without this: https://github.com/odoo/odoo/compare/148da332a9cc8e212553f3f4f45819adac498c7b..3c1bc843b8eeca86e6fd568b20452876a593206e
    - Outline buttons did not work at all (the CSS rules you created had no effect because of the missing `&` in the SCSS selectors)
    - With that `&` added, outline buttons work on activation... but not when disabling (`add` class only, no `remove` => changed to `toggle`)
    - Typo in the outline button's border-color value, so always forced to the text color by mistake

Anyways, seems good now :grimacing: 

@robodoo r+

**Pull request closed without merging**
