### PR TITLE
[IMP] account: improve Journal Items reconciliation view

### PR DESCRIPTION
**Pull request by proose**
Clean the action for reconciliation view for the correct handling of it.

Removes the group by Matching in the Journal Items reconciliation
list.

Moves a reconciliation scss file to enterprise.

task-2959808

### CODE REVIEW

**Review by aab-odoo — COMMENTED** [review]
I don't know where the action is coming from, but did you considerer using `clean_action` python-side before sending it to the client? The client should not receive actions with the `tree` view type.

**Comment by proose** [comment]
Thank you @aab-odoo, I wasn't aware of this tool.

**Comment by smetl** [comment]
@robodoo r+

**Review by smetl — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
