### PR TITLE
[FIX] web: fix performance issue with read_progress_bar

### PR DESCRIPTION
**Pull request by ged-odoo**
This PR fixes some miscellaneous issues:
- performance issue in read_progress_bar
- performance issue in activity view
- crash in ungrouped kanban view with progress bar

### CODE REVIEW

**Comment by aab-odoo** [comment]
:+1:

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by rco-odoo** [comment]
robodoo r-

**Comment by rco-odoo** [comment]
robodoo r+

**Pull request closed without merging**
