### PR TITLE
modif the China small business tax

### PR DESCRIPTION
**Pull request by JackSunI**
Hello,
 In this PR:
- Modify the Small and Medium-sized Tax Template 
- Modify the translation files 

--
Please review the code. @lap-odoo @mart-e 
Thanks.
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@lap-odoo technically, it looks good to me

**Comment by lap-odoo** [comment]
@mart-e Can be merged then :) Thanks

**Comment by JackSunI** [comment]
Thanks. :)

**Comment by mart-e** [comment]
Thanks for the change !
@robodoo r+
For future changes, could you elaborate a bit more on the changes? Explaining why it was wrong before etc. It is useful for the history in case somebody complains later :)

**Comment by lap-odoo** [comment]
@mart-e Thanks for your help. If the commit message is not clear enough for the future PR, I may be able to help. With the language difference, it's not always easy :) 

thanks

**Pull request closed without merging**
