### PR TITLE
[FIX] website_sale_comparison: keep attributes order consistent

### PR DESCRIPTION
**Pull request by lem8r**
Related issue #29980

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lem8r** [comment]
Tests are passing however there is separate issue that gives server error when opening compare page

```bash
File "/data/build/odoo/addons/website_sale_comparison/controllers/main.py", line 33, in product_compare
    values['compute_currency'] = self._get_compute_currency_and_context(products[:1])[0]
  File "/data/build/odoo/addons/website_sale/controllers/main.py", line 138, in _get_compute_currency_and_context
    compute_currency = self._get_compute_currency(pricelist, product)
  File "/data/build/odoo/addons/website_sale/controllers/main.py", line 153, in _get_compute_currency
    company = product and product._get_current_company(pricelist=pricelist, website=request.website) or pricelist.company_id or request.website.company_id
AttributeError: 'product.product' object has no attribute '_get_current_company'
```
Here https://github.com/odoo/odoo/blob/12.0/addons/website_sale/controllers/main.py#L153

```python
company = product and product._get_current_company(pricelist=pricelist, website=request.website) or pricelist.company_id or request.website.company_id
```
could be fixed by adding `product_tmpl_id`

```python
ompany = product and product.product_tmpl_id._get_current_company(pricelist=pricelist, website=request.website) or pricelist.company_id or request.website.company_id
```

**Comment by JKE-be** [comment]
can you just rewrite your commit msg please following the guideline

```
[FIX] website_sale_comparison: keep attributes order consistent

Before this commit, using python < 3.6, the comparison was random etc, etc...

Now we use OrderDict etc, etc, ...

```

thks

**Comment by lem8r** [comment]
Sure, sorry.

**Comment by JKE-be** [comment]
mhmhmhhh, was speaking about commit msg and not pr title ;)

**Comment by lem8r** [comment]
:sweat: 
-----

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by KangOl** [comment]
@robodoo retry

**Pull request closed without merging**
