### PR TITLE
[8.0] [FIX] stock: let resupply from warehouse work

### PR DESCRIPTION
**Pull request by gurneyalex**
If you set WH B to be resupplied from WH A, then the scheduler will generate a procurement with `warehouse_id = B` and `location_id = B.stock`. Running the procurement will find the resupply rule, and this will create another procurement with `warehouse_id = A` and `location_id = transit location`. 

However, without this patch, the resupply route is not part of the `route_ids` of warehouse A, and so the 2nd procurement goes in exception because if cannot find a rule (the search will force a rule linked to a route which is part of `A.route_ids`)

### CODE REVIEW

**Comment by gurneyalex** [comment]
@jco-odoo your opinion on this PR is welcome :smile_cat:

**Comment by clonedagain** [comment]
@lbellier I think it's important for us too, can you watch/test this PR please?

**Comment by gurneyalex** [comment]
@clonedagain @lbellier the PR is red on OCB's travis, but this is not caused by the PR itself.

**Comment by jco-odoo** [comment]
I confirm...  I guess we used to use the routes on the product form instead of just this one.

**Comment by gurneyalex** [comment]
At home, when running with odoo.py --stop-after-init -i stock --test-enable, the tests are green. Probably another module installed in the runbot which changes the behavior of the procurement (maybe procurement_jit). Will update the test.

**Comment by gurneyalex** [comment]
@jco-odoo with routes on the product it works without the patch, but with no route on the product it is not possible to get a global resupply from WH to WH (the 2nd procurement goes in exception for lack of rule).

**Comment by pedrobaeza** [comment]
Squash all commits in one and for me is :+1:

**Pull request closed without merging**
