### PR TITLE
[ADD] Add the possibility to add some fields on website recruitment form

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Define lists of recruitment form fields to allow inheriance to add some fields.

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
OPW 648553

**Comment by beledouxdenis** [comment]
Hello Adrien, 

Could you explain how works your inheritance ? How do you alter these `CHAR_FIELDS` and `RELATIONAL_FIELDS` lists ? 

The only way I see you could alter these lists you would be to import them in python: This doesn't really follow the Odoo guidelines.

Instead, why don't you create two methods, returning these lists ? So you can override the methods when inheriting from the controller ?

Regards,

**Comment by adrienpeiffer** [comment]
Hi Denis,

Indeed, I amend the lists by importing them into another file.

I can create two methods that returns the fields list. What do you think is the best place to do that ? In hr_applicant class or on the controller ?

**Comment by beledouxdenis** [comment]
Adrien, 

Normally, following the guidelines, it should be done within the hr_applicant class, but so should be the rest of the logic, and this is currently not the case.

Therefore, I would say within the controller :).

Thank you.

**Comment by adrienpeiffer** [comment]
It's done !

**Comment by adrienpeiffer** [comment]
Thanks @beledouxdenis :smile:

**Pull request closed without merging**
