### PR TITLE
[13.0] [RM] l10n_ch - find_number and tests artefacts

### PR DESCRIPTION
**Pull request by yvaucher**
This feature was introduced for the first version of the QR-bill.

In the first version it was intended to split the addresses in street
and number in a structured way (code S).
However, in current version instead of spliting the QR-Bill allows to
use directly address lines street and street2 in the same format as
Odoo (code K).

**There are no calls to `find_number`.**

Thus, the function is some dead code and those tests test nothing.
Plus, the test file name is misleading as it test nothing about the
QR-bill.

### Description of the issue/feature this PR addresses:

Just a leftover to remove.

The key point is this line : https://github.com/odoo/odoo/pull/53257/files#diff-b6235a49c5949673bb213f3f712026cbR125

```
            'K',                                                  # Creditor Address Type
```

Which means we don't split the address.

QR-bill doc is there: https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf

Page 28, AdrTp

> **Address type**
> The address type is specified using a code.
> The following codes are defined:
> "S" -structured address
> "K" -combined address elements (2 lines)

### Current behavior before PR:

Presence of test artifacts

### Desired behavior after PR is merged:

Useless tests gone

New tests were proposed here:
https://github.com/odoo-dev/odoo/pull/275

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yvaucher** [comment]
@oco-odoo @jco-odoo 

Don't bother keeping those tests, those are misleading making us think QR-bill has unit tests whereas it tests nothing. It would be better to integrate those tests:

odoo-dev#275

**Comment by Yenthe666** [comment]
Indeed shouldn't be done in stable :)

**Comment by yvaucher** [comment]
@oco-odoo ok right, I'll let `find_number` and but a deprecated comment.

**Comment by yvaucher** [comment]
@oco-odoo Updated being conservative with the function and added a comment

**Comment by oco-odoo** [comment]
@robodoo r+
@fw-bot up to 13.0

**Pull request closed without merging**
