### PR TITLE
[FIX] get login_number in the same transaction as update it

### PR DESCRIPTION
**Pull request by yelizariev**
Description of the issue/feature this PR addresses:

if you have two POS stations, that use same user, same ` pos.config`,
i.e. create two sessions AND if you have bad luck, then those sessions will get
same login_number, which leads to losing half of the orders, because of POS stations
will generate the same `pos_reference` and only first order from the POSes is saved,
while another order is lost without let know to the cashier.

Current behavior before PR:

**orders are lost**

Desired behavior after PR is merged:

Be sure that login_number is not shared with another POS

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@it-projects-llc

### CODE REVIEW

**Comment by yelizariev** [comment]
@pimodoo it's related to POS

**Comment by yelizariev** [comment]
cc @blaggacao

**Comment by pimodoo** [comment]
Hello, we were able to reproduce the issue, by connecting the session at exact same time, we then tried to apply you PR, and face an issue, showing undefined value in the POS order number, cf: attached imaged
odoo pos pr login number

**Comment by yelizariev** [comment]
@pimodoo are you sure that you restarted odoo after applying the update?

**Comment by pimodoo** [comment]
@yelizariev I'll recheck, I think I didn't update the module so the template didn't have the login value.

**Comment by mart-e** [comment]
I think I already saw this happen when two people used the PoS with the same account on different computers (which is a bad idea, let's be clear !).
We discussed this with @nim-odoo and did not accepted it in stable but I have no issue for master.

**Comment by yelizariev** [comment]
@mart-e it's master branch. Do we need some else approvement?

**Comment by yelizariev** [comment]
Can this be merged?

**Comment by vedler** [comment]
Status?

**Pull request closed without merging**
