### PR TITLE
[FIX] mrp:  All Users real duration display in WO on the current logg…

### PR DESCRIPTION
**Pull request by npm-odoo**
In the WO real duration is updated for all users who logged in.

opw-2541695

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
You should just modify the python and the definition of is_user_working remove the check on current user on time_ids

**Comment by amoyaux** [comment]
Oups sorry didn't checked that other fields exists. You could let the python like before and use working_user_ids instead of is_user_working in the js.

**Comment by ryv-odoo** [comment]
There isn't any diff, can we close this one ?

**Comment by npm-odoo** [comment]
> There isn't any diff, can we close this one ?

Yes there is an difference,
In the first commit we use of is_user_working field but @amoyaux give me a suggestion, use working_user_ids instead of is_user_working.

**Comment by C3POdoo** [comment]
Dear @npm-odoo,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
