### PR TITLE
[FIX] crm: Smart button for meetings not working

### PR DESCRIPTION
**Pull request by simongoffin**
Steps to reproduce the bug:

- Let's consider a company contact C with two children CH1 and CH2
- Create a meeting for CH1 and a meeting for CH2

Bug:

The count of meetings in C was displaying 0 instead of 2

PS: set() is used to avoid to count several times the same event for a partner.

If for example CH1 and CH2 attend to the same event, only one event must be counted for the parent C

opw:2360155

### CODE REVIEW

**Review by nim-odoo — COMMENTED** [review]
Looks ok, maybe make the `active_test` consistent in other places.
(generalize https://github.com/odoo/odoo/commit/6afb4bb4e25cfb242ce16cd75a509b50a4b56e3f)

**Comment by simongoffin** [comment]
robodoo rebase-ff

**Comment by simongoffin** [comment]
robodoo r+

**Comment by simongoffin** [comment]
robodoo r-

**Comment by simongoffin** [comment]
robodoo r+

**Pull request closed without merging**
