### PR TITLE
[FIX] account: send invoice mail in partner language

### PR DESCRIPTION
**Pull request by mattismegevand**
Forward-port of #133744.

opw-3476315

### CODE REVIEW

**Comment by mattismegevand** [comment]
@fw-bot ignore

This issue was fixed in saas-16.2, thanks to: [#70291](https://github.com/odoo/odoo/commit/9887bd0c7b5208214e2aafe5aadbcb2d70e96c4f)

**Review by nle-odoo — APPROVED** [review]
looks good to me

it would probably be good to have it approved by bon tomorrow before merging, so:

robodoo delegate=nboulif

**Review by nboulif — APPROVED** [review]
Hello @mattismegevand , thanks for the fix! (and my bad, I went directly to saas-16.2 :sweat_smile: )

LGTM, just a little question, why not fix also the `default_lang` as in my commit? Am I missing something...?
It's a corner case, but better be safe :wink: https://github.com/odoo/odoo/pull/133744#issuecomment-1713656266

PS: it's a forward-port, not backport :smile:

**Comment by nboulif** [comment]
@mattismegevand Thanks for the updates!
@robodoo  r+

**Pull request closed without merging**
