### PR TITLE
[FIX] web: fix logo colors

### PR DESCRIPTION
**Pull request by anso-odoo**
Before this commit, most of the logos used in Odoo were using the old purple color.

This commit updates all these old logos with the latest version that can be found on the Odoo brand-asset page

https://www.odoo.com/page/brand-assets

Note that the new logo is a corrected version of the one that this PR replaces, so there might be some differences in the letters postition. For example, the postion of the "d" was changed for a better alignment.

Also, for "addons/web/static/img/logo.png" and "addons/web/static/img/nologo.png", this is not the regular PNG logo that you can simply download in the brand assets, there is actually a specific padding that has been added in the past around the logo and since we don't have the source file, this padding was replicated.

task-3328677
Documentation related PR : https://github.com/odoo/documentation/pull/5540

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by jcs-odoo — CHANGES_REQUESTED** [review]
This PR fills my heart with joy. I... I mean.... Sorry, these are tears of joy.

Test, to the best of my knowledge ^^

Websote footer ok
image

Customer portal ok
image

Favicon ok 
image

Knowledge public shared article not okay
Please update also this file 
https://github.com/odoo/odoo/blob/a6df8abb4e7f5590b06666ec9d3af99e15e439f2/addons/mail/static/src/img/odoo_o.png
image


Can you edit the IAP database as well? Or follow-up the update? Not ok
image

Documentation favicon and logos are not okay
I thought they were sharing that with the product, though... 
And then, according to the files used, I think these two files are useless. To follow-up too, then
https://github.com/odoo/documentation/tree/16.0/static/img
image

Weird "o" in the "login with odoo.com" option (login page) (font awesome custom, with the old color code too)
image
image



Another repo, but the login page needs an update too
/openerp_website/static/src/img/2016/logos/odoo_logo.svg
image

Cheers

**Review by jcs-odoo — COMMENTED** [review]
Also @anso-odoo , considering these logo are often downloaded, could you compress them more, at least to match the previous files' weight? 

I see logo2.png is now heavier than the original one (210% according to GitHub), same for logo_tiny and nologo. Considering that every kb is important in SEO, this could be significant.

**Comment by anso-odoo** [comment]
Hello @jcs-odoo 
I changed the logo for public knowledge pages and reduced the sizes of the other images
I also created a PR for documentation https://github.com/odoo/documentation/pull/5540

Concerning IAP, @edi-odoo will get in touch with the team to give them the correct logo

About the openerp_website, it's on the PS Design side, I will get in touch with them 

Thanks !

**Review by jcs-odoo — APPROVED** [review]
Looks good to me, @anso-odoo thanks!

As for the login page, I think it is specific to runbot when we use the "login with odoo.com"  button. It opens accounts.odoo.com . The issue is that the image URL points to that /2016/ folder which should be deleted if it isn't used anymore, and the URL should use the default odoo logo's URL instead. wdyt?

**Comment by anso-odoo** [comment]
Hello @jcs-odoo I changed the base of both PR to 14.0

@stefanorigano Hello, can you have a look please ? Thanks !

**Comment by anso-odoo** [comment]
@odony Hello 👋, here are some clarifications 

The new logo is a corrected version of the one that this PR replaces, so there might be some differences in the letters postition. For example, the postion of the "d" was indeed changed for a better alignment.

Also, for "addons/web/static/img/logo.png" and "addons/web/static/img/nologo.png", this is not the regular PNG logo that you can simply download in the brand assets, there is actually a specific padding that has been added in the past around the logo and we don't have the source file, so I had to replicate it. That could have caused some letters misplacement but I tried to keep it as close as possible. I actually improved it a bit thanks to your comment 👍 

Thanks for your feedback, I'll add those explanations in the PR message !

**Review by edi-odoo — APPROVED** [review]
LGTM!

**Comment by anso-odoo** [comment]
Hello @odony 
Do you think you can review this PR and potentially R+ if all good ? 

The documentation check fails because there was initially a documentation branch with the same name as this one. But I temporarily closed the PR and will reopen it after this one is merged because the base is not the same for community and documentation anymore (https://github.com/odoo/documentation/pull/5540#issuecomment-1687829994)

**Pull request closed without merging**
