### PR TITLE
CLA

### PR DESCRIPTION
**Pull request by halgandd**
CLA

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using an address `@auguria.net`
- you are signing for the address `@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Also, in this case of a corporate CLA, it is probably better if you could sign using your `@techlib` email address or ask @eldy to make the corporate CLA update.

Thanks

**Comment by halgandd** [comment]
Hi,
I have changed my email.

Regards,

**Comment by mart-e** [comment]
Sorry but it still incorrect.
You are signing for a `@teclib.com` email address (which is good for the corporate signature) but signing it from the `halgandd@users.noreply.github.com` email address.
You must sign with the same email address that the one you are using for your commits.

**Comment by mart-e** [comment]
Thanks for the update @halgandd it verifies now.
I see you sign for both corporate and individual CLA with the same email address. Is this wanted or should I just merge the corporate CLA?

Usually people signing both will use a different email address so they can differentiate the contributions made within the company and outside.
Let me know

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it has been integrated into Odoo at revision https://github.com/odoo/odoo/commit/e366ee354285571efc8b4e76ce4be0572d566199.
Future pull requests made on odoo will be validated by the runbot.
Regards

**Pull request merged**
