### PR TITLE
[FIX] google_calendar: prevent google meet links when location is set

### PR DESCRIPTION
**Pull request by kawkb**
Issue
    When a location is set on an event, the google meet link is also
    generated, leading to confusion about the meeting format.

Steps to reproduce
    - Create an event with a location
    - Sync the Calendar with Google.
    - Observe that a Google Meet link is sent with the email.

Solution
    check if the loacation is set before generating a google meet link.

opw-3589379

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kawkb** [comment]
@geflx Thank you for your time,  I'm uncertain about the fix behavior in hybrid meeting scenarios. The client mentioned it worked previously, indeed it was working because no google meet links were generated ( neither when the location is set or not), leading me to think that this is not a bug in the first place. What do you think?

**Comment by leonardopavanrocha** [comment]
@robodoo r+

**Review by leonardopavanrocha — APPROVED** [review]
Thanks for your work and patience @kawkb !

**Comment by d-fence** [comment]
robodoo retry

**Pull request closed without merging**
