### PR TITLE
[FIX] analytics: remove partner_id from the name_search

### PR DESCRIPTION
**Pull request by moylop260**
original commit message backported from https://github.com/odoo/odoo/pull/162951

```txt
Before this commit, our distribution analytics process included searching the table res.partner for potential matches, 
which negatively impacted performance. However, this is no longer necessary as the default name of the account 
matches the name of the partner. This change removes the unnecessary performance overhead.
```

We have reproduced a query that never ends only opening the following report:

```python
report = self.env.ref("account_reports.profit_and_loss")
infos = report.get_report_informations({})
```

Checking the configuration of this report it has domains similar to:
 - `("analytic_line_ids.account_id", "ilike", "VALUE")`

<details>
  <summary>generating a big query running for hours in production</summary>

```sql
-- with partner
SELECT 
  COALESCE(
    SUM(
      ROUND(
        account_move_line.balance * currency_table.rate, 
        currency_table.precision
      )
    ), 
    0.0
  ) AS sum, 
  COUNT(DISTINCT account_move_line.id) AS count_rows 
FROM 
  "account_move_line" 
  LEFT JOIN "account_account" AS "account_move_line__account_id" ON (
    "account_move_line"."account_id" = "account_move_line__account_id"."id"
  ) 
  JOIN (
    VALUES 
      (1, 1.0, 2)
  ) AS currency_table(company_id, rate, precision) ON currency_table.company_id = account_move_line.company_id 
WHERE 
  (
    (
      (
        (
          (
            (
              (
                "account_move_line"."display_type" not in ('line_section', 'line_note')
              ) 
              OR "account_move_line"."display_type" IS NULL
            ) 
            AND (
              "account_move_line"."company_id" in (1)
            )
          ) 
          AND (
            "account_move_line"."date" <= '2024-12-31'
          )
        ) 
        AND (
          "account_move_line"."date" >= '2024-01-01'
        )
      ) 
      AND(
        "account_move_line"."parent_state" = 'posted'
      )
    ) 
    AND (
      (
        (
          "account_move_line__account_id"."account_type" = 'expense'
        ) 
        OR (
          "account_move_line__account_id"."account_type" = 'expense_depreciation'
        )
      ) 
      AND (
        (
          (
            (
              (
                (
                  "account_move_line"."id" IN (
                    SELECT 
                      "account_analytic_line"."move_line_id" 
                    FROM 
                      "account_analytic_line" 
                    WHERE 
                      (
                        "account_analytic_line"."account_id" in (
                          SELECT 
                            "account_analytic_account".id 
                          FROM 
                            "account_analytic_account" 
                            LEFT JOIN "account_analytic_plan" AS "account_analytic_account__plan_id" ON (
                              "account_analytic_account"."plan_id" = "account_analytic_account__plan_id"."id"
                            ) 
                          WHERE 
                            (
                              (
                                (
                                  unaccent(
                                    "account_analytic_account"."name" :: text
                                  ) ilike unaccent('%Consejo%')
                                ) 
                                OR (
                                  unaccent(
                                    "account_analytic_account"."code" :: text
                                  ) ilike unaccent('%Consejo%')
                                )
                              ) 
                              OR (
                                "account_analytic_account"."partner_id" in (
                                  SELECT 
                                    "res_partner".id 
                                  FROM 
                                    "res_partner" 
                                  WHERE 
                                    (
                                      (
                                        (
                                          (
                                            (
                                              unaccent(
                                                "res_partner"."display_name" :: text
                                              ) ilike unaccent('%Consejo%')
                                            ) 
                                            OR (
                                              unaccent("res_partner"."email" :: text) ilike unaccent('%Consejo%')
                                            )
                                          ) 
                                          OR (
                                            unaccent("res_partner"."ref" :: text) ilike unaccent('%Consejo%')
                                          )
                                        ) 
                                        OR (
                                          unaccent("res_partner"."vat" :: text) ilike unaccent('%Consejo%')
                                        )
                                      ) 
                                      OR (
                                        unaccent(
                                          "res_partner"."company_registry" :: text
                                        ) ilike unaccent('%Consejo%')
                                      )
                                    ) 
                                    AND (
                                      (
                                        (
                                          (
                                            "res_partner"."type" != 'private'
                                          ) 
                                          OR "res_partner"."type" IS NULL
                                        ) 
                                        OR "res_partner"."type" IS NULL
                                      ) 
                                      OR ("res_partner"."type" = 'private')
                                    )
                                )
                              )
                            ) 
                            AND (
                              (
                                "account_analytic_account"."company_id" in (1)
                              ) 
                              OR "account_analytic_account"."company_id" IS NULL
                            )
                        )
                      ) 
                      AND (
                        "account_analytic_line"."company_id" in (1)
                      ) 
                      AND "account_analytic_line"."move_line_id" IS NOT NULL
                  )
                ) 
                OR (
                  "account_move_line"."id" IN (
                    SELECT 
                      "account_analytic_line"."move_line_id" 
                    FROM 
                      "account_analytic_line" 
                    WHERE 
                      (
                        "account_analytic_line"."account_id" in (
                          SELECT 
                            "account_analytic_account".id 
                          FROM 
                            "account_analytic_account" 
                            LEFT JOIN "account_analytic_plan" AS "account_analytic_account__plan_id" ON (
                              "account_analytic_account"."plan_id" = "account_analytic_account__plan_id"."id"
                            ) 
                          WHERE 
                            (
                              (
                                (
                                  unaccent(
                                    "account_analytic_account"."name" :: text
                                  ) ilike unaccent('%Finan%')
                                ) 
                                OR (
                                  unaccent(
                                    "account_analytic_account"."code" :: text
                                  ) ilike unaccent('%Finan%')
                                )
                              ) 
                              OR (
                                "account_analytic_account"."partner_id" in (
                                  SELECT 
                                    "res_partner".id 
                                  FROM 
                                    "res_partner" 
                                  WHERE 
                                    (
                                      (
                                        (
                                          (
                                            (
                                              unaccent(
                                                "res_partner"."display_name" :: text
                                              ) ilike unaccent('%Finan%')
                                            ) 
                                            OR (
                                              unaccent("res_partner"."email" :: text) ilike unaccent('%Finan%')
                                            )
                                          ) 
                                          OR (
                                            unaccent("res_partner"."ref" :: text) ilike unaccent('%Finan%')
                                          )
                                        ) 
                                        OR (
                                          unaccent("res_partner"."vat" :: text) ilike unaccent('%Finan%')
                                        )
                                      ) 
                                      OR (
                                        unaccent(
                                          "res_partner"."company_registry" :: text
                                        ) ilike unaccent('%Finan%')
                                      )
                                    ) 
                                    AND (
                                      (
                                        (
                                          (
                                            "res_partner"."type" != 'private'
                                          ) 
                                          OR "res_partner"."type" IS NULL
                                        ) 
                                        OR "res_partner"."type" IS NULL
                                      ) 
                                      OR ("res_partner"."type" = 'private')
                                    )
                                )
                              )
                            ) 
                            AND (
                              (
                                "account_analytic_account"."company_id" in (1)
                              ) 
                              OR "account_analytic_account"."company_id" IS NULL
                            )
                        )
                      ) 
                      AND (
                        "account_analytic_line"."company_id" in (1)
                      ) 
                      AND "account_analytic_line"."move_line_id" IS NOT NULL
                  )
                )
              ) 
              OR (
                "account_move_line"."id" IN (
                  SELECT 
                    "account_analytic_line"."move_line_id" 
                  FROM 
                    "account_analytic_line" 
                  WHERE 
                    (
                      "account_analytic_line"."account_id" in (
                        SELECT 
                          "account_analytic_account".id 
                        FROM 
                          "account_analytic_account" 
                          LEFT JOIN "account_analytic_plan" AS "account_analytic_account__plan_id" ON (
                            "account_analytic_account"."plan_id" = "account_analytic_account__plan_id"."id"
                          ) 
                        WHERE 
                          (
                            (
                              (
                                unaccent(
                                  "account_analytic_account"."name" :: text
                                ) ilike unaccent('%Logis%')
                              ) 
                              OR (
                                unaccent(
                                  "account_analytic_account"."code" :: text
                                ) ilike unaccent('%Logis%')
                              )
                            ) 
                            OR (
                              "account_analytic_account"."partner_id" in (
                                SELECT 
                                  "res_partner".id 
                                FROM 
                                  "res_partner" 
                                WHERE 
                                  (
                                    (
                                      (
                                        (
                                          (
                                            unaccent(
                                              "res_partner"."display_name" :: text
                                            ) ilike unaccent('%Logis%')
                                          ) 
                                          OR (
                                            unaccent("res_partner"."email" :: text) ilike unaccent('%Logis%')
                                          )
                                        ) 
                                        OR (
                                          unaccent("res_partner"."ref" :: text) ilike unaccent('%Logis%')
                                        )
                                      ) 
                                      OR (
                                        unaccent("res_partner"."vat" :: text) ilike unaccent('%Logis%')
                                      )
                                    ) 
                                    OR (
                                      unaccent(
                                        "res_partner"."company_registry" :: text
                                      ) ilike unaccent('%Logis%')
                                    )
                                  ) 
                                  AND (
                                    (
                                      (
                                        (
                                          "res_partner"."type" != 'private'
                                        ) 
                                        OR "res_partner"."type" IS NULL
                                      ) 
                                      OR "res_partner"."type" IS NULL
                                    ) 
                                    OR ("res_partner"."type" = 'private')
                                  )
                              )
                            )
                          ) 
                          AND (
                            (
                              "account_analytic_account"."company_id" in (1)
                            ) 
                            OR "account_analytic_account"."company_id" IS NULL
                          )
                      )
                    ) 
                    AND (
                      "account_analytic_line"."company_id" in (1)
                    ) 
                    AND "account_analytic_line"."move_line_id" IS NOT NULL
                )
              )
            ) 
            OR (
              "account_move_line"."id" IN (
                SELECT 
                  "account_analytic_line"."move_line_id" 
                FROM 
                  "account_analytic_line" 
                WHERE 
                  (
                    "account_analytic_line"."account_id" in (
                      SELECT 
                        "account_analytic_account".id 
                      FROM 
                        "account_analytic_account" 
                        LEFT JOIN "account_analytic_plan" AS "account_analytic_account__plan_id" ON (
                          "account_analytic_account"."plan_id" = "account_analytic_account__plan_id"."id"
                        ) 
                      WHERE 
                        (
                          (
                            (
                              unaccent(
                                "account_analytic_account"."name" :: text
                              ) ilike unaccent('%Recur%')
                            ) 
                            OR (
                              unaccent(
                                "account_analytic_account"."code" :: text
                              ) ilike unaccent('%Recur%')
                            )
                          ) 
                          OR (
                            "account_analytic_account"."partner_id" in (
                              SELECT 
                                "res_partner".id 
                              FROM 
                                "res_partner" 
                              WHERE 
                                (
                                  (
                                    (
                                      (
                                        (
                                          unaccent(
                                            "res_partner"."display_name" :: text
                                          ) ilike unaccent('%Recur%')
                                        ) 
                                        OR (
                                          unaccent("res_partner"."email" :: text) ilike unaccent('%Recur%')
                                        )
                                      ) 
                                      OR (
                                        unaccent("res_partner"."ref" :: text) ilike unaccent('%Recur%')
                                      )
                                    ) 
                                    OR (
                                      unaccent("res_partner"."vat" :: text) ilike unaccent('%Recur%')
                                    )
                                  ) 
                                  OR (
                                    unaccent(
                                      "res_partner"."company_registry" :: text
                                    ) ilike unaccent('%Recur%')
                                  )
                                ) 
                                AND (
                                  (
                                    (
                                      (
                                        "res_partner"."type" != 'private'
                                      ) 
                                      OR "res_partner"."type" IS NULL
                                    ) 
                                    OR "res_partner"."type" IS NULL
                                  ) 
                                  OR ("res_partner"."type" = 'private')
                                )
                            )
                          )
                        ) 
                        AND (
                          (
                            "account_analytic_account"."company_id" in (1)
                          ) 
                          OR "account_analytic_account"."company_id" IS NULL
                        )
                    )
                  ) 
                  AND (
                    "account_analytic_line"."company_id" in (1)
                  ) 
                  AND "account_analytic_line"."move_line_id" IS NOT NULL
              )
            )
          ) 
          OR (
            "account_move_line"."id" IN (
              SELECT 
                "account_analytic_line"."move_line_id" 
              FROM 
                "account_analytic_line" 
              WHERE 
                (
                  "account_analytic_line"."account_id" in (
                    SELECT 
                      "account_analytic_account".id 
                    FROM 
                      "account_analytic_account" 
                      LEFT JOIN "account_analytic_plan" AS "account_analytic_account__plan_id" ON (
                        "account_analytic_account"."plan_id" = "account_analytic_account__plan_id"."id"
                      ) 
                    WHERE 
                      (
                        (
                          (
                            unaccent(
                              "account_analytic_account"."name" :: text
                            ) ilike unaccent('%Tecnol%')
                          ) 
                          OR (
                            unaccent(
                              "account_analytic_account"."code" :: text
                            ) ilike unaccent('%Tecnol%')
                          )
                        ) 
                        OR (
                          "account_analytic_account"."partner_id" in (
                            SELECT 
                              "res_partner".id 
                            FROM 
                              "res_partner" 
                            WHERE 
                              (
                                (
                                  (
                                    (
                                      (
                                        unaccent(
                                          "res_partner"."display_name" :: text
                                        ) ilike unaccent('%Tecnol%')
                                      ) 
                                      OR (
                                        unaccent("res_partner"."email" :: text) ilike unaccent('%Tecnol%')
                                      )
                                    ) 
                                    OR (
                                      unaccent("res_partner"."ref" :: text) ilike unaccent('%Tecnol%')
                                    )
                                  ) 
                                  OR (
                                    unaccent("res_partner"."vat" :: text) ilike unaccent('%Tecnol%')
                                  )
                                ) 
                                OR (
                                  unaccent(
                                    "res_partner"."company_registry" :: text
                                  ) ilike unaccent('%Tecnol%')
                                )
                              ) 
                              AND (
                                (
                                  (
                                    (
                                      "res_partner"."type" != 'private'
                                    ) 
                                    OR "res_partner"."type" IS NULL
                                  ) 
                                  OR "res_partner"."type" IS NULL
                                ) 
                                OR ("res_partner"."type" = 'private')
                              )
                          )
                        )
                      ) 
                      AND (
                        (
                          "account_analytic_account"."company_id" in (1)
                        ) 
                        OR "account_analytic_account"."company_id" IS NULL
                      )
                  )
                ) 
                AND (
                  "account_analytic_line"."company_id" in (1)
                ) 
                AND "account_analytic_line"."move_line_id" IS NOT NULL
            )
          )
        ) 
        OR (
          "account_move_line"."id" IN (
            SELECT 
              "account_analytic_line"."move_line_id" 
            FROM 
              "account_analytic_line" 
            WHERE 
              (
                "account_analytic_line"."account_id" in (
                  SELECT 
                    "account_analytic_account".id 
                  FROM 
                    "account_analytic_account" 
                    LEFT JOIN "account_analytic_plan" AS "account_analytic_account__plan_id" ON (
                      "account_analytic_account"."plan_id" = "account_analytic_account__plan_id"."id"
                    ) 
                  WHERE 
                    (
                      (
                        (
                          unaccent(
                            "account_analytic_account"."name" :: text
                          ) ilike unaccent('%Vigil%')
                        ) 
                        OR (
                          unaccent(
                            "account_analytic_account"."code" :: text
                          ) ilike unaccent('%Vigil%')
                        )
                      ) 
                      OR (
                        "account_analytic_account"."partner_id" in (
                          SELECT 
                            "res_partner".id 
                          FROM 
                            "res_partner" 
                          WHERE 
                            (
                              (
                                (
                                  (
                                    (
                                      unaccent(
                                        "res_partner"."display_name" :: text
                                      ) ilike unaccent('%Vigil%')
                                    ) 
                                    OR (
                                      unaccent("res_partner"."email" :: text) ilike unaccent('%Vigil%')
                                    )
                                  ) 
                                  OR (
                                    unaccent("res_partner"."ref" :: text) ilike unaccent('%Vigil%')
                                  )
                                ) 
                                OR (
                                  unaccent("res_partner"."vat" :: text) ilike unaccent('%Vigil%')
                                )
                              ) 
                              OR (
                                unaccent(
                                  "res_partner"."company_registry" :: text
                                ) ilike unaccent('%Vigil%')
                              )
                            ) 
                            AND (
                              (
                                (
                                  (
                                    "res_partner"."type" != 'private'
                                  ) 
                                  OR "res_partner"."type" IS NULL
                                ) 
                                OR "res_partner"."type" IS NULL
                              ) 
                              OR ("res_partner"."type" = 'private')
                            )
                        )
                      )
                    ) 
                    AND (
                      (
                        "account_analytic_account"."company_id" in (1)
                      ) 
                      OR "account_analytic_account"."company_id" IS NULL
                    )
                )
              ) 
              AND (
                "account_analytic_line"."company_id" in (1)
              ) 
              AND "account_analytic_line"."move_line_id" IS NOT NULL
          )
        )
      )
    )
  ) 
  AND (
    (
      "account_move_line"."company_id" in (1)
    ) 
    OR "account_move_line"."company_id" IS NULL
  )
```

</details>

Notice the following example running for 1h45m in production:
 - Screenshot 2024-11-25 at 1 02 49 p m

<details>
  <summary>After this commit the query generated is shorter and the query spends only a few seconds</summary>

```sql
--w/o partner
SELECT 
  COALESCE(
    SUM(
      ROUND(
        account_move_line.balance * currency_table.rate, 
        currency_table.precision
      )
    ), 
    0.0
  ) AS sum, 
  COUNT(DISTINCT account_move_line.id) AS count_rows 
FROM 
  "account_move_line" 
  LEFT JOIN "account_account" AS "account_move_line__account_id" ON (
    "account_move_line"."account_id" = "account_move_line__account_id"."id"
  ) 
  JOIN (
    VALUES 
      (1, 1.0, 2)
  ) AS currency_table(company_id, rate, precision) ON currency_table.company_id = account_move_line.company_id 
WHERE 
  (
    (
      (
        (
          (
            (
              (
                "account_move_line"."display_type" not in ('line_section', 'line_note')
              ) 
              OR "account_move_line"."display_type" IS NULL
            ) 
            AND (
              "account_move_line"."company_id" in (1)
            )
          ) 
          AND (
            "account_move_line"."date" <= '2024-12-31'
          )
        ) 
        AND (
          "account_move_line"."date" >= '2024-01-01'
        )
      ) 
      AND (
        "account_move_line"."parent_state" = 'posted'
      )
    ) 
    AND (
      (
        (
          "account_move_line__account_id"."account_type" = 'expense'
        ) 
        OR (
          "account_move_line__account_id"."account_type" = 'expense_depreciation'
        )
      ) 
      AND (
        (
          "account_move_line"."id" IN (
            SELECT 
              "account_analytic_line"."move_line_id" 
            FROM 
              "account_analytic_line" 
            WHERE 
              (
                "account_analytic_line"."account_id" in (
                  SELECT 
                    "account_analytic_account".id 
                  FROM 
                    "account_analytic_account" 
                    LEFT JOIN "account_analytic_plan" AS "account_analytic_account__plan_id" ON (
                      "account_analytic_account"."plan_id" = "account_analytic_account__plan_id"."id"
                    ) 
                  WHERE 
                    (
                      (
                        unaccent(
                          "account_analytic_account"."name" :: text
                        ) ilike unaccent('%Venta%')
                      ) 
                      OR (
                        unaccent(
                          "account_analytic_account"."code" :: text
                        ) ilike unaccent('%Venta%')
                      )
                    ) 
                    AND (
                      (
                        "account_analytic_account"."company_id" in (1)
                      ) 
                      OR "account_analytic_account"."company_id" IS NULL
                    )
                )
              ) 
              AND (
                "account_analytic_line"."company_id" in (1)
              ) 
              AND "account_analytic_line"."move_line_id" IS NOT NULL
          )
        ) 
        OR (
          "account_move_line"."id" IN (
            SELECT 
              "account_analytic_line"."move_line_id" 
            FROM 
              "account_analytic_line" 
            WHERE 
              (
                "account_analytic_line"."account_id" in (
                  SELECT 
                    "account_analytic_account".id 
                  FROM 
                    "account_analytic_account" 
                    LEFT JOIN "account_analytic_plan" AS "account_analytic_account__plan_id" ON (
                      "account_analytic_account"."plan_id" = "account_analytic_account__plan_id"."id"
                    ) 
                  WHERE 
                    (
                      (
                        unaccent(
                          "account_analytic_account"."name" :: text
                        ) ilike unaccent('%Merca%')
                      ) 
                      OR (
                        unaccent(
                          "account_analytic_account"."code" :: text
                        ) ilike unaccent('%Merca%')
                      )
                    ) 
                    AND (
                      (
                        "account_analytic_account"."company_id" in (1)
                      ) 
                      OR "account_analytic_account"."company_id" IS NULL
                    )
                )
              ) 
              AND (
                "account_analytic_line"."company_id" in (1)
              ) 
              AND "account_analytic_line"."move_line_id" IS NOT NULL
          )
        )
      )
    )
  ) 
  AND (
    (
      "account_move_line"."company_id" in (1)
    ) 
    OR "account_move_line"."company_id" IS NULL
  )
```

</details>

<details>

  <summary>Notice the following `explain` for this query in the same production server spending 5.6s</summary>

```txt
Aggregate  (cost=1683649.32..1683649.33 rows=1 width=40) (actual time=5652.888..5652.895 rows=1 loops=1)
  ->  Hash Join  (cost=337869.04..1667706.61 rows=1594271 width=10) (actual time=529.984..5643.571 rows=29132 loops=1)
        Hash Cond: (account_move_line.account_id = account_move_line__account_id.id)
        ->  Index Scan using account_move_line_date_index on account_move_line  (cost=337840.33..1655725.50 rows=4514011 width=14) (actual time=91.853..5201.350 rows=29133 loops=1)
              Index Cond: ((date <= '2024-12-31'::date) AND (date >= '2024-01-01'::date))
              Filter: ((((display_type)::text <> ALL ('{line_section,line_note}'::text[])) OR (display_type IS NULL)) AND ((company_id = 1) OR (company_id IS NULL)) AND (company_id = 1) AND ((parent_state)::text = 'posted'::text) AND ((hashed SubPlan 1) OR (hashed SubPlan 2)))
              Rows Removed by Filter: 5850974
              SubPlan 1
                ->  Nested Loop  (cost=2089.23..168484.14 rows=174323 width=4) (actual time=11.543..56.162 rows=101136 loops=1)
                      ->  Seq Scan on account_analytic_account  (cost=0.00..2.40 rows=1 width=8) (actual time=8.528..8.570 rows=1 loops=1)
                            Filter: (((company_id = 1) OR (company_id IS NULL)) AND ((unaccent((name)::text) ~~* unaccent('%Venta%'::text)) OR (unaccent((code)::text) ~~* unaccent('%Venta%'::text))))
                            Rows Removed by Filter: 50
                      ->  Bitmap Heap Scan on account_analytic_line  (cost=2089.23..166078.90 rows=240283 width=8) (actual time=3.006..42.727 rows=101136 loops=1)
                            Recheck Cond: (account_id = account_analytic_account.id)
                            Filter: ((move_line_id IS NOT NULL) AND (company_id = 1))
                            Heap Blocks: exact=10050
                            ->  Bitmap Index Scan on account_analytic_line_account_id_index  (cost=0.00..2029.16 rows=240283 width=0) (actual time=2.014..2.014 rows=101228 loops=1)
                                  Index Cond: (account_id = account_analytic_account.id)
              SubPlan 2
                ->  Nested Loop  (cost=2089.23..168484.14 rows=174323 width=4) (actual time=8.721..10.210 rows=2232 loops=1)
                      ->  Seq Scan on account_analytic_account account_analytic_account_1  (cost=0.00..2.40 rows=1 width=8) (actual time=8.566..8.582 rows=1 loops=1)
                            Filter: (((company_id = 1) OR (company_id IS NULL)) AND ((unaccent((name)::text) ~~* unaccent('%Merca%'::text)) OR (unaccent((code)::text) ~~* unaccent('%Merca%'::text))))
                            Rows Removed by Filter: 50
                      ->  Bitmap Heap Scan on account_analytic_line account_analytic_line_1  (cost=2089.23..166078.90 rows=240283 width=8) (actual time=0.150..1.513 rows=2232 loops=1)
                            Recheck Cond: (account_id = account_analytic_account_1.id)
                            Filter: ((move_line_id IS NOT NULL) AND (company_id = 1))
                            Heap Blocks: exact=733
                            ->  Bitmap Index Scan on account_analytic_line_account_id_index  (cost=0.00..2029.16 rows=240283 width=0) (actual time=0.083..0.083 rows=2232 loops=1)
                                  Index Cond: (account_id = account_analytic_account_1.id)
        ->  Hash  (cost=26.56..26.56 rows=172 width=4) (actual time=438.121..438.123 rows=177 loops=1)
              Buckets: 1024  Batches: 1  Memory Usage: 15kB
              ->  Bitmap Heap Scan on account_account account_move_line__account_id  (cost=3.91..26.56 rows=172 width=4) (actual time=438.047..438.089 rows=177 loops=1)
                    Recheck Cond: (((account_type)::text = 'expense'::text) OR ((account_type)::text = 'expense_depreciation'::text))
                    Heap Blocks: exact=12
                    ->  BitmapOr  (cost=3.91..3.91 rows=177 width=0) (actual time=0.010..0.011 rows=0 loops=1)
                          ->  Bitmap Index Scan on account_account_account_type_index  (cost=0.00..2.46 rows=162 width=0) (actual time=0.008..0.008 rows=162 loops=1)
                                Index Cond: ((account_type)::text = 'expense'::text)
                          ->  Bitmap Index Scan on account_account_account_type_index  (cost=0.00..1.36 rows=15 width=0) (actual time=0.001..0.002 rows=15 loops=1)
                                Index Cond: ((account_type)::text = 'expense_depreciation'::text)
Planning Time: 0.712 ms
JIT:
  Functions: 56
  Options: Inlining true, Optimization true, Expressions true, Deforming true
  Timing: Generation 2.761 ms, Inlining 13.991 ms, Optimization 278.567 ms, Emission 162.561 ms, Total 457.880 ms
Execution Time: 5655.563 ms
```

</details>

It was fixed for 17.0 but IMHO it should be fixed also for 16.0

WDYT?

### CODE REVIEW

**Comment by moylop260** [comment]
@JKE-be @jbw-odoo @casp-odoo 

What do you think about?

**Comment by hupo-odoo** [comment]
Thanks for the PR. @h4818 as discussed, this PR looks fine

**Comment by h4818** [comment]
@robodoo ignore

**Review by h4818 — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
