### PR TITLE
[FIX] website_theme_install: Not able to crop images created from theme.

### PR DESCRIPTION
**Pull request by kig-odoo**

### CODE REVIEW

**Comment by kig-odoo** [comment]
Hello @JKE-be , @qsm-odoo 

Can you check this one?
Currently, we're not able to crop images created from a theme.

**Comment by JKE-be** [comment]
.copy_ids can be empty
new field cannot be added in stable policy

But thanks for the reporting :/
We need to find another way to fix it

**Comment by qsm-odoo** [comment]
How do you reproduce the bug @kig-odoo ? it seems to work on my side...

**Comment by qsm-odoo** [comment]
Here is the fix: https://github.com/odoo-dev/odoo/commit/3f762f050ad98080fb6892bf057901b77b98fba7 I will create the PR.

**Comment by kig-odoo** [comment]
@qsm-odoo I think you've fixed other issue 😄 

Crop feature works fine for website images but it is not working with theme image. 
see: https://www.youtube.com/watch?v=oE1EoiOrPHM 

In crop controller we using mimetype of image, now xml id of theme's images are recordset of `theme.ir.attachement` which don't having mime type field.
cmd

**Comment by qsm-odoo** [comment]
Thanks @kig-odoo 
I have made the fix, I will create another PR with all attachment-related issues that I am fixing.

**Pull request closed without merging**
