### PR TITLE
[IMP] better default values for digits and taxes of l10n_de

### PR DESCRIPTION
**Pull request by tv-openbig**
The current default values leads to standard proposals of 6 digits
account numbers and in many cases wrong default tax settings. The fix
prevents most users to have to adopt custom settings for digits and
default taxes.

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

No problem with the patch but one question regarding your CLA: you are signing the individual CLA but you have already signed the [corporate CLA for openbig](https://github.com/odoo/odoo/blob/446d59fd4484d0314745bf270bc5e3fd7adbdc8e/doc/cla/corporate/openbig.md). Is there a reason to sign it twice ?

**Comment by tv-openbig** [comment]
No there is no reason. I have just done it the same way as most other partners.
It would be great if you could merge it. The same "problem" is relevant for V9 too.
I will prepare a separate PR.

**Comment by mart-e** [comment]
No problem, just wanted to be sure it wasn't mistake. I have merged both in 8.0.
Thanks for the patch

We will forward port it to 9.0, you can create a PR only if the patch needs to be adapted for v9

1423cef [IMP] l10n_de: better defaults values for digits and taxes of l10n_de
57bd14a [CLA] signature for Thorsten Vocks

**Comment by pniederlag** [comment]
awesome, thx @tv-openbig for fixing it and thx for @mart-e for merging the proper parts in!

**Pull request closed without merging**
