### PR TITLE
[IMP] mail: support sub thread in group chat

### PR DESCRIPTION
**Pull request by zel-odoo**
This commit adds the support for sub thread in group chat. It allows to create a sub thread in the action list or create from a specific message in the group chat.

https://github.com/odoo/upgrade/pull/6638

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
ACL also need to be changed, as we currently check the access of the parent only for type channel.

**Comment by phenix-factory** [comment]
We should just make this work for all the channel types, it will be less code and more features.

**Comment by seb-odoo** [comment]
For livechat and whatsapp it's not a good idea because we don't have UI for them so the target user will never see it nor receive the messages.

For chat we can debate it.

**Comment by phenix-factory** [comment]
> For livechat and whatsapp it's not a good idea because we don't have UI for them so the target user will never see it nor receive the messages.

Should we still actively block it? We don't need to build the UI, but it could be "technically possible" but the UI doesn't support it.

> For chat we can debate it.

I see a win here: fewer codes to "block" the feature and more features for the user.

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

In a follow up PR, it would be nice to add ACL check in regards to parent channels in `TestDiscussChannelAccess`.

**Comment by zel-odoo** [comment]
> @robodoo r+
> 
> In a follow up PR, it would be nice to add ACL check in regards to parent channels in `TestDiscussChannelAccess`.

https://github.com/odoo/odoo/pull/186405 Hey, I found it might be a better idea or even a bug that we should only allow a sub thread of a group chat being a group chat rather than a channel. So I made this PR and in this case, the ACL checks in the TestDiscussChannelAccess still work and I don't think we need to update that part. What do you think?

**Pull request closed without merging**
