### PR TITLE
[IMP] website: resize `s_image_wall` images

### PR DESCRIPTION
**Pull request by anso-odoo**
This PR diversifies the ratios of default images for `s_image_wall`
snippet. The old ones were all the same sizes and therefore the snippet
was looking like a simple image grid, regardless by the options applied.

It also adapts the spacing between the images to make it fit the grid.

Requires:
- https://github.com/odoo/design-themes/pull/843

task-3654301
part of task-3619705

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by stefanorigano — APPROVED** [review]
Hello @anso-odoo 👋
Branch rebased, images replaced, and now 🟢 on runbot.
All the rest was LGTM already. The CSS adaptations introduced are an improvement and don't really  justify the creation of a new `vcss` IMO.

Since @chgo-odoo didn't work on this and it was almost ready anyway... it's all yours again 🙂

Ready for tech. review, good luck 💪

edit: enterprise is 🔴 , I spoke too soon 😅

**Comment by anso-odoo** [comment]
@robinlej This is finally ready for tech review :) Thanks !

**Comment by sobo-odoo** [comment]
@robodoo delegate=robinlej

**Comment by robinlej** [comment]
@robodoo r+

**Pull request closed without merging**
