### PR TITLE
[FIX] account: multi-currencies fixes

### PR DESCRIPTION
**Pull request by nim-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
@qdp-odoo Ideally, this should be merged in v11. However, my main concern is that d3d26120614139fd7d7e888bd66d21de5158a034 by @csnauwaert rewrote a major part of the code modified here... So we don't really have any stress testing of this code in various situations. Do you think it worth the risk?

**Comment by qdp-odoo** [comment]
only if the non-forward port of these commits is seriously taken care of. 

I mean: I don't mind the v11 being buggy, I'd rather avoid all regressions in further versions.

**Comment by nim-odoo** [comment]
> only if the non-forward port of these commits is seriously taken care of.
> 
> I mean: I don't mind the v11 being buggy, I'd rather avoid all regressions in further versions.

Well, they shouldn't be forward-ported at all, actually.

**Comment by nim-odoo** [comment]
By the way, I'd rather avoid all regressions in a stable release :smile:

**Comment by MohsenWaleed** [comment]
We are facing the same issue which fixed here in V11 and it cause a big issue in our accounting

 Is this fix will be applied to V11?

**Comment by MohsenWaleed** [comment]
@nim-odoo Actually this fix need to be merged to V11    

> By the way, I'd rather avoid all regressions in a stable release 😄

For us which are using multi currency, it's not a stable and our journal entries show wrong data and wrong accounting figures.

Please let us know if you will push this to V11 or there is another way to fix this in V11.

**Comment by MohsenWaleed** [comment]
@nim-odoo Thanks to know the update on this if it's the time to applied V11

**Comment by nim-odoo** [comment]
merged in https://github.com/odoo/odoo/pull/38252

**Pull request closed without merging**
