### PR TITLE
[FIX] google_gmail, microsoft_outlook: wrong documentation version

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
@AntoineVDV Hello, can you check when you have free time please ? thank you

**Review by AntoineVDV — APPROVED** [review]
Hello, LGTM! :)

I'll let the responsible team merge the PR as there are adaptations to make in 17.3 to use the `documentation_link` widget instead.

**Comment by duong77476-viindoo** [comment]
> Hello, LGTM! :)
> 
> I'll let the responsible team merge the PR as there are adaptations to make in 17.3 to use the `documentation_link` widget instead.

Oh okay, thank you. Love the `documentation_link` widget

**Comment by reth-odoo** [comment]
widget is already used in 17.3+ so we can just stop the forward port there :)

@tde-banana-odoo :wave:  got an easy one here
(already checked that 16.x have the right version)

**Comment by tde-banana-odoo** [comment]
@robodoo up to saas-17.2

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
