### PR TITLE
show total amount in report.pos.order tree and rec name

### PR DESCRIPTION
**Pull request by niyasraphy**
before this commit, the total amount of the order
is not displayed in pos.order.report tree view.

* point of sale -> Reporting -> Orders

* switch to pivot view

* click on any pivot cells

* in the tree view, no information about the order amount

after this commit, the total will be shown to
the user in tree view.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
hi @caburj ,
if you have time, can you review this PR.
thanks in advance

**Comment by niyasraphy** [comment]
hi @caburj ,
if you have time, can you review this.
thanks

**Comment by caburj** [comment]
> hi @caburj ,
> if you have time, can you review this.
> thanks

Will do.

**Comment by caburj** [comment]
robodoo r+

**Comment by caburj** [comment]
robodoo rebase-ff

**Pull request closed without merging**
