### PR TITLE
[IMP] repair: convert repair uom and location onchanges to compute

### PR DESCRIPTION
**Pull request by beledouxdenis**
This allows to create a repair.order record without
the need to call the onchanges to set the uom and locations
or to set them manually during the `create` call.

For instance, this makes easier to create repair orders
using XMLRPC when you do not use multiple UOMs or multiple locations.

### CODE REVIEW

**Comment by beledouxdenis** [comment]
@Feyensv I would like your opinion regarding the change in `_prepare_create_values` for the `precompute` feature.

Without this change, it's not possible to convert the onchange `_onchange_company_id` to a compute method to set the `location_id`.

`location_id` is set with
`required=True`
and with
`states={'draft': [('readonly', False)], 'confirmed': [('readonly', True)]}`

Meaning the `location_id` field is readonly if it's not in the `draft` state.

Without a change, it's not possible to set manually a value for the `location_id` field, because the field gets recomputed automatically because it's `readonly=True`.
https://github.com/odoo/odoo/pull/95321/files#diff-7144f88ea32f36feb17ce1b8dda7dee1631f5ada34075414587df3948c6b3d1bL4236

It would be more accurate to prevent the re-computation of the field when the record is within the according state only,
but it's not so easy because `state` is not always available at that point, for instance when `state` is itself a computed field.
Besides, it would be a lot of overhead while this feature of `readonly=True` and `states` is supposed to be visual only.
For instance, it was possible to set `location_id` for repair orders manually when they were no longer draft using XMLRPC.

**Comment by Feyensv** [comment]
I don't think we want to make such a change, because it makes 'strictly computed fields' potentially set through the create call, opening a gap for potential inconsistencies.
At some point, I had a version fully considering the states content (w.r.t the create values).  
I think we dropped it to avoid mixing even more the UX and backend logic.
The `readonly` attribute already became a mix between the two and if we consider the `states` as well, it shouldn't be considered only in the `create`, but probably in the `write` (and other places?).

Can't you simply invert the states logic to make the field only `readonly` in some states for now ?

cc: @rco-odoo

**Comment by beledouxdenis** [comment]
> Can't you simply invert the states logic to make the field only `readonly` in some states for now ?

I could but this means the list would become way longer, and each time a value is added for the state selection, you have to think about that `states` in other field attributes. It's also harder when you had a possible state value through an inherit.
It makes the life more painful for developers.

Considering the downsides to simply add this `not field.states` versus the complexity it would bring not to, I would still consider this change.

**Comment by Feyensv** [comment]
Well, after more thoughts, it's true that `states` being set mostly means the record is not strictly readonly, which is what we wanted to consider here :thinking:

Looking at the code, I see a `states={'draft': [('invisible', True)]}` in some test code, does it even work ? (If it does, it might be better to check the states content really targets the `readonly` attribute and not other one(s) before considering it's editable).

**Comment by beledouxdenis** [comment]
> Looking at the code, I see a `states={'draft': [('invisible', True)]}` in some test code, does it even work ? (If it does, it might be better to check the states content really targets the `readonly` attribute and not other one(s) before considering it's editable).

Though it's not used anywhere, it indeed works

```diff
diff --git a/addons/repair/models/repair.py b/addons/repair/models/repair.py
index 17e188352e1..85c0fcc29e2 100644
--- a/addons/repair/models/repair.py
+++ b/addons/repair/models/repair.py
@@ -31,7 +31,7 @@ class Repair(models.Model):
     product_id = fields.Many2one(
         'product.product', string='Product to Repair',
         domain="[('type', 'in', ['product', 'consu']), '|', ('company_id', '=', company_id), ('company_id', '=', False)]",
-        readonly=True, required=True, states={'draft': [('readonly', False)]}, check_company=True)
+        readonly=True, required=True, states={'draft': [('readonly', False), ('invisible', True)]}, check_company=True)
     product_qty = fields.Float(
         'Product Quantity',
         default=1.0, digits='Product Unit of Measure',
```

```py
In [1]: from lxml import etree
In [2]: product = self.env['product.product'].search([], limit=1)
In [3]: repair = self.env['repair.order'].create({'product_id': product.id})
In [4]: etree.fromstring(repair.get_view()['arch']).xpath('//field[@name="product_id"]')[0].attrib
Out[4]: {'name': 'product_id', 'on_change': '1', 'can_create': 'true', 'can_write': 'true', 'modifiers': '{"invisible": [["state", "in", ["draft"]]], "readonly": [["state", "not in", ["draft"]]], "required": true}'}
```

**Comment by Feyensv** [comment]
LGTM :ok_hand: 
Ideally, the orm change could be in a split commit, with a dedicated test in `test_new_api`.

**Comment by beledouxdenis** [comment]
Unit test written, branch green :). A last look ? :D

**Review by rco-odoo — APPROVED** [review]
Thanks for the test!
I personally don't like `states` at all, but the proposed patch is reasonable.

**Pull request closed without merging**
