### PR TITLE
[REM] stock: remove unecessary assets

### PR DESCRIPTION
**Pull request by Whenrow**
Since 94a3919, the report_location_barcode.scss asset is never loaded.
The report_stock_rule has the same template id than the report_location_barcode
one. This later is so always overridden.
This commit delete the barcode location css as it was not really usefull

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sle-odoo** [comment]
i don't know if we should get rid or restore this stylesheet

if we restore:
isn't it related to https://github.com/odoo/odoo/pull/42913 ?
@agr-odoo you were talking about rotation on your pr, maybe this was the issue and this css should be restored / your patch partially removed?

if we get rid of it:
to do in master

**Comment by agr-odoo** [comment]
Well, this is unexpected...
Indeed the overridden css was causing the issue, by restoring it (without my patch) I see the expected behavior, however after discussing with PO the conclusion was to change the behavior of the report so I guess it can be removed.
@nim-odoo thoughts?

**Comment by nim-odoo** [comment]
What happens if the user simply restart the server with doing `-u stock`? I'd say the file will be deleted, but the `xpath` will still be there.

**Comment by Whenrow** [comment]
code removed in saas13.2 version with https://github.com/odoo/odoo/pull/45311

**Pull request closed without merging**
