### PR TITLE
[FIX] account_anglo_saxon: price computation with different uom

### PR DESCRIPTION
**Pull request by mart-e**
When recording the cost of good sold, fetch the price based on the stock.move
Revision fb57514c used the standard_price fixing a UoM issues

alternative fix for #8098

### CODE REVIEW

**Comment by mart-e** [comment]
@mohamedhagag could you check this one ? I believe it fixes your issue

**Comment by mohamedhagag** [comment]
@mart-e I'm invoicing a Sale Order not a Delivery/stock move - so normally this patch generates the below error:
```
ValueError: ""'account.invoice.line' object has no attribute 'product_tmpl_id'" 
while evaluating u'action_move_create()'" while evaluating u'action_invoice_create()'
```

**Comment by mart-e** [comment]
Yes I forgot to push a part of the patch, should be ok now

**Comment by mohamedhagag** [comment]
Also my patch working on the invoice level whatever its source is a stock move or Sale order it works fine as the invoice generated from the stock move also have the same price unit of the stock move.

**Comment by mohamedhagag** [comment]
ok I will check your update

**Comment by mohamedhagag** [comment]
do we have wrong indentation in the else clause that will cancel price_unit value from the if clause ?

**Comment by mohamedhagag** [comment]
in line 98

**Comment by mart-e** [comment]
But if I have stock.move linked to my invoice, I *do* want to use the price on the move, not the standard price. When you are using real or average price valuation, both may be different.
Not sure what you mean with indentation (you can put inline comments in the PR)

**Comment by mohamedhagag** [comment]
here at 
https://github.com/odoo-dev/odoo/commit/4fe660d6da0dfa8c9bba1806c3e842acfa2a04d8#L98

**Comment by mohamedhagag** [comment]
Also my patch always returns the price on the invoice of the move or the invoice of the sale order not the standard_price - did you test it ?
I did test it in 3 scenarios as I mentioned it 1- invoicing a stock move 2- invoicing a sale order 3- invoicing on demand ( any of both methods 1 or 2 ).
And the results was accurate.

**Comment by mohamedhagag** [comment]
Ok, in your code - if you mean the indentation in #L98 then the result will be a standard price also in case of sale order invoicing.

In #L97 why not use ```i_line.price_unit``` instead of ```i_line.product_id.standard_price``` ?!
The price_unit will be more accurate than the standard_price in many cases.

**Comment by mohamedhagag** [comment]
Thanks @mart-e your code also working fine after testing and reading it again.
Sorry for the long discussion - I was confused with the modifications you made - specially changing line 100  argument from price to price_unit .

And regarding line 98 indentation it's Ok also :) .

I tested it with both invoicing methods 1- SO invoicing 2- stock move invoicing and it's Ok .

please can you merge it with the main branch ?!

**Comment by mart-e** [comment]
@mohamedhagag please avoid commenting on the commit as you loose discussion during rebase (like I just did), instead directly comment [in PR code](https://github.com/odoo/odoo/pull/8457/files).

So I understand you agree with the change in the end, merged at a9757d99c3d74e4cf9e239386b41c712ff641ecc
Thanks for the review

**Pull request merged**
