### PR TITLE
17.0 webhook payload automated action fja

### PR DESCRIPTION
**Pull request by fja-odoo**
Adds the payload to the eval_context of the triggered
automated action so that it can be used in the python code.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
this is obviously an imp, for master eventually

**Comment by fja-odoo** [comment]
> this is obviously an imp, for master eventually

Isn't it possible to put it in 17 ?
The risk looks quite low and the reward very high.

**Comment by kebeclibre** [comment]
counter offer https://github.com/odoo/odoo/pull/142710

**Comment by fja-odoo** [comment]
@kebeclibre Thanks !

**Pull request closed without merging**
