### PR TITLE
[ADD] point_of_sale : add pos_image on account.journal to display in POS UI;

### PR DESCRIPTION
**Pull request by legalsylvain**
- Add a new field 'pos_image' on account.journal;
- Display Image on Front End :   

pos-image-payment-front-end
- Allow to manage image in Front End account.journal form view : 

pos-image-payment-back-end

### CODE REVIEW

**Comment by legalsylvain** [comment]
CC : @fvdsn.

**Comment by legalsylvain** [comment]
Hi @fvdsn, @mart-e. I see this message on github : "This branch has conflicts that must be resolved". 
Should I resolve it ? 
This PR didn't received any review, please comment or reject this PR.
Kind regards.

**Comment by mart-e** [comment]
Hello Sylvain,

Let me check with usability team if it's a feature we wish to integrate and I get back to it (but the conflict seems easy to fix).

**Comment by legalsylvain** [comment]
Hi, 
any news ?
Regards.

**Comment by mart-e** [comment]
Hello,

We discussed that but sorry, it is not a feature we want to integrate. We prefer to keep that the configuration of the POS simple and not sure it will really make the life of POS users easier.

**Comment by legalsylvain** [comment]
Hi @mart-e,
> We prefer to keep that the configuration of the POS simple.

-> It's an extra-feature. If user don't set image, there is no bug, just the default display without image... I don't see how this PR could make PoS configuration more complex.

> and not sure it will really make the life of POS users easier.

-> really ?

Anyway, thanks for taking time to review my PR.

Kind regards.

**Comment by pedrobaeza** [comment]
@legalsylvain, please propose it as new add-on pos_journal_image in OCA.

**Comment by legalsylvain** [comment]
Finally, 8 years later, in odoo V17 ... ;-)

image

Thanks !

**Pull request closed without merging**
