### PR TITLE
[FIX] membership : Members module is not visible without Accounting

### PR DESCRIPTION
**Pull request by yoba-odoo**
[FIX] membership : Members module is not visible without Accounting
Steps to reproduce:
	1- Install Members module while Accounting is uninstalled
	
Current behavior before PR:
When you install Members module without having Accounting module you will not be able to access Members module as it will be hidden on the dashboard. This happens because of the access rights that the Member module has as it is having the access right group of the Accounting module `group_account_user`.

Desired behavior after PR is merged:
Now the Members module has the access right group of Invoicing module `group_account_invoice` which is the only dependency module that Members need. So it will be visible and accessible from the dashboard once installed

opw-3627010

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
So before the removal of association (f6c60e497520d7916937f4a2a57ed3f8c2e1049b):

1. if you installed membership without association, you had access to it => but if you used "Buy Membership" you got an error ([screenshot in 15.0](https://github.com/odoo/odoo/assets/9977887/0995354e-e8e8-40b7-bc97-e05369f617d9))
2. if you installed association (or website_membership), in addition to the error, you didn't have access to membership menu unless you installed account_accountant and got the group "account.group_account_user".

Since saas-16.1 removal of association, we now have the second issue when installing just membership.

So the menu change seems ok to me. And the access right also seems ok but functionally I don't know if there was a reason to prevent membership buying to non accountant.

Note: the menu hiding in association dates from 2016: 9e57185449a0bd958ad38eddc280d146e2d60e1e, and the access right restriction from 2020 65530dfd6a0486f44134917f5cc42a2c30b95762

**Review by dbkosky — APPROVED** [review]
I don't know the membership module too well so maybe I'm missing something, but this change makes sense to me.  :+1:

**Review by FlorianGilbert — COMMENTED** [review]
Hello

Why are we making this change in 16.1 and not in 15.0?
Thank you

**Comment by yoba-odoo** [comment]
Hello @FlorianGilbert 

Because the issue was not there until 16.1 :sweat_smile: 
You can check this commit which led to the issue https://github.com/odoo/odoo/commit/f6c60e497520d7916937f4a2a57ed3f8c2e1049b#diff-65a587634b23c60ecc8eea20881920a50eddbc569aa5d0381705b7405e918e2e

**Comment by FlorianGilbert** [comment]
> Hello @FlorianGilbert
> 
> Because the issue was not there until 16.1 😅 You can check this commit which led to the issue [f6c60e4](https://github.com/odoo/odoo/commit/f6c60e497520d7916937f4a2a57ed3f8c2e1049b)

Indeed, could you please reference it in your commit message, thank you :sun_with_face:

**Comment by yoba-odoo** [comment]
Done, @FlorianGilbert :slightly_smiling_face:

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
