### PR TITLE
Document proper usage of env and cr in HttpCase.

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses: Increase documentation on test cases.

Current behavior before PR: `SavepointCase` was almost unknown, although it is a great tool; and [`HttpCase`'s special behavior of not sharing the cursor between the `env` and the HTTP calls](https://github.com/odoo/odoo/issues/12237#issuecomment-235923596) is not documented.

Desired behavior after PR is merged: This documents the required workflow that was discovered in https://github.com/odoo/odoo/issues/12237#issuecomment-254781169, to make it available for everybody. It also documents `SavepointCase`.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by Yajo** [comment]
Bot's :x: is wrong. This is just doc PR, please someone review :blush:

**Comment by Yajo** [comment]
@Yenthe666 friend, could you ping here too? It's just docs...

**Comment by Yenthe666** [comment]
Ahh yes ofcourse! Documentation is for @mart-e and this looks like a neat little improvement to me. 👍

**Comment by Yenthe666** [comment]
@mart-e gentle nudge / reminder.

**Comment by rafaelbn** [comment]
@mart-e please could you review this PR as @Yenthe666 suggest? cc @Yajo

**Comment by Yajo** [comment]
This is just a doc PR, and I think it should get merged and forward-ported before 8.0 goes out of maintenance... 😕

**Comment by Yajo** [comment]
@mart-e I don't understand why you removed the most important part.

The problem of "hey, I added some records to my test and then my http request can't find'em" comes to me constantly, because I seem to be the one that found it out. I'd prefer to share a link to the docs than a link to [a random closed issue comment](https://github.com/odoo/odoo/issues/12237#issuecomment-254781169).

This isn't a too specific case. If you are writing an `HttpCase` test, chances that you need to add a record or check its modification/creation/deletion are very high.

If the problem is that I said "you", tell me how should I spell it, but add the docs please. 🙏

**Pull request closed without merging**
