### PR TITLE
[FIX] mail: notify auto subscribers after message creation.

### PR DESCRIPTION
**Pull request by bartekwojcicki**
Notifications sent to partners automatically subscribed to the thread were sent before message causing subscription was saved. As a result notification for previous message was sent.

### CODE REVIEW

**Comment by nim-odoo** [comment]
Hello,
Thank you for your PR. In order to contribute, please make sure to first sign the CLA: https://github.com/odoo/odoo/blob/8.0/doc/cla/sign-cla.md
Concerning your PR, I understand you sent the notifications at the end of the process, but I'm not sure to understand the original problem. Could you please be more explicit and use such a template to describe what your fix solves?

```
Steps to reproduce:
 1. create a new sale order
 2. add a line with product 'Service', quantity 2, unit price 10.0
 3. validate the sale order

Current behavior:

 - Total price of 10.0

Expected behavior:

 - Total price of 20.0 (2 * 10 = 20)
```

**Comment by bartekwojcicki** [comment]
Steps to reproduce:
    create a new lead, save it
    change salesperson (salesperson should have email notifications enabled), save it
    validate email content in Settings -> Technical -> Email -> Emails

Current behavior:
    'Lead created' in email content

Expected behavior:
    'Salesperson: -> <Salesperon name>' in email content

Lead and salesperon field is just one example, similar problem occurs with every auto subscribe field, e.g. Task (from Project Management app) and Reviewier field.

**Comment by nim-odoo** [comment]
Thanks you for the clarification. Could you please add the CLA to your PR?

Thanks!

**Comment by bartekwojcicki** [comment]
Done.

**Comment by nim-odoo** [comment]
Merged with 78939477ff065ed28e13151c19a4d95aa6f414b2 and 43915a872176fd7b8f75fccb73230ea6ad9e1016
Thanks!

**Pull request closed without merging**
