### PR TITLE
[FIX] : Fix crm_lead domain in order to have ability to won or lose...

### PR DESCRIPTION
**Pull request by AdilHoumadi**
... an opportunity.

The error message mentioned in the code does not respect the domain which is used in the query.
"Change Probability Automatically"  this description refers to on_change field.
normally the domain should be like that :
To won an opportunity => You should configure the stage like that : probability = 100 % and select "Change Probability Automatically"
To lose it => the stage needs to be like follow : probability = 0 %, select "Change Probability Automatically"
#5485

### CODE REVIEW

**Comment by jsh-odoo** [comment]
It is already improved in master.

**Comment by ah-taktik** [comment]
@jsh-odoo, the PR is for 8.0 branch

**Comment by mv-taktik** [comment]
@jsh-odoo Any news about this PR?

**Comment by beledouxdenis** [comment]
Hello @ah-taktik ,

Sadly, even we can understand that this can be misleading, this would introduce a change of behaviour, and you pull request cannot be considered to be merged in Odoo 8.0: Probably, company are relying on the current behaviour.

In a general matter, this pull request is against our stable policy: 
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

This change may be applied in master, but I believe this is already the case.

We hope you will understand.

**Comment by ah-taktik** [comment]
No problem, I understand that this PR is againt the policy rules.
it's understandable for companies already relying on this feature(Bug), but it will cause trouble for futur users.
It will be better if you improve the product.

Thanks it's OK for me :)

**Pull request closed without merging**
