### PR TITLE
[IMP] delivery: ease to inherit delivery currency computation

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Hook up the currency computation which is embedded in essential methods which makes it hard to inherit without rewriting the methods completely which is never a great idea.

**Background**: having a module to define the `delivery.carrier` currency, so calculate based on the carrier currency instead of the company currency in relation to the sale order currency, needed this extraction and as it is uniting the currency conversion, I think it is a good addition to core to create more flexibility here. Actually, this hack is already in use since 11.0, but is still valid in 15.0, so it should be also easy and painless to forward-port which we did in our fork.

Info: @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@tivisse @mart-e 
May I ask you to review and merge this for us? Unfortunately the code owner does not work anymore for Odoo S.A., so I guess there is no one to really review. As written, this is really helpful and will not break anything on its way into core 😉

**Review by Yenthe666 — APPROVED** [review]

**Comment by wtaferner** [comment]
@mart-e 
May I ask you to assign a specific person? It seems that the team assignment does not work or is ignored by the teams 😉

**Comment by Yenthe666** [comment]
@mart-e can you make this happen? :)

**Comment by tivisse** [comment]
@Yenthe666 @wtaferner Sorry for the delay.

Actually this falls under the responsibility of the Logistic team.

@amoyaux could you please give a look at this ? 

Have a nice day,

Yannick.

**Comment by wtaferner** [comment]
@amoyaux 
May I ask you to merge this?

**Pull request closed without merging**
