### PR TITLE
FIX: change id_xml of groups, use uom.group_uom  instead of product.group_uom 

### PR DESCRIPTION
**Pull request by celm1990**
Complementary to 6a378e383910ab597359f95c38028b229fc82cc7

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Xavier-Do** [comment]
We should apply this fix from saas-11.3 and check enterprise too

**Comment by Xavier-Do** [comment]
We will merge this change in saas-11.3 and eventually add validation on groups. Thanks for your feedback.

**Comment by celm1990** [comment]
Following to:
b2b9545cf38855fdb97e992aa2883cdab6909e96
eaba05b9ae631cb907406996b3e4a79232965c22

**Comment by mart-e** [comment]
Thank you for the change, it was integrated in saas-11.3 at fc411ceb191dd1cf789f199814d12eb32479632c

**Pull request closed without merging**
