### PR TITLE
[IMP] base: change in child's company_id to have same company as parent

### PR DESCRIPTION
**Pull request by smo-odoo**
Task : https://www.odoo.com/web?debug=true#id=1934813&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720

Pad : https://pad.odoo.com/p/r.f3fd084c47d4f33cf0e31f9edbcda630

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tivisse** [comment]
Did you check the consistency with website_sale ?

For example if your partner is in the company A and you buy something on an ecommerce from the company B, when setting a new delivery address, the partner will be created in the company B and thus leading to a traceback.

Could you check ?

**Comment by tde-banana-odoo** [comment]
@robodoo r-

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo nice try retry otherwise I call @d-fence

**Pull request closed without merging**
