### PR TITLE
[FIX] point_of_sale: remove "willstart" for a performance issue

### PR DESCRIPTION
**Pull request by pedrambiria**
Before this commit: if the number of contacts is enormous, and the
"Limited Partners Loading" with "Load all remaining partners in the
background" is enabled, clicking on the product information button would
take lots of time to reload. Also, it would cause the same issue for the
"ClosePoSPopup".

The problem is that when "willstart" takes time more than the background
process it would call it again, and for every call.

The solution is to prepare the "willstart" function's data and pass it to the
constructor.

opw-2956104

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
@pedrambiria Is this not an issue in 15.0?

**Comment by pedrambiria** [comment]
@caburj I didn't reproduce the issue on V15.
But it has the same code, so theoretically, it should be an issue on V15.
Do you think I have to start the fix from V15?

**Comment by caburj** [comment]
Yeah, I think it will be the same for v15.0. Let's start this fix there.

**Comment by pedrambiria** [comment]
I created a PR in 15.0:
https://github.com/odoo/odoo/pull/99933

**Comment by caburj** [comment]
Thanks a lot. I'll continue processing this on Monday.

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
