### PR TITLE
[FIX] Typo in sale_stock/wizard/stock_rules_report.py

### PR DESCRIPTION
**Pull request by alexbclay**
Description of the issue/feature this PR addresses:
Fix the spelling of a single word in a single wizard.

Current behavior before PR:
The word 'routes' is spelled 'rotues'

Desired behavior after PR is merged:
The word 'routes' is spelled 'routes'

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Thanks the PR but we can not accept it in stable version. If we merge this, we would break the existing translations of the label. Could you instead target the master branch?

**Comment by alexbclay** [comment]
> Hi,
> 
> Thanks the PR but we can not accept it in stable version. If we merge this, we would break the existing translations of the label. Could you instead target the master branch?

I have changed the target of the PR, and I will rebase my change and push soon to fix the merge conflicts.

**Comment by mart-e** [comment]
@alexbclay don't worry, I have rebased your branch, should be good now

@robodoo r+ rebase-ff

**Comment by alexbclay** [comment]
@mart-e Thanks!

**Pull request closed without merging**
