### PR TITLE
[IMP] account{,_sequence}: merge

### PR DESCRIPTION
**Pull request by william-andre**
This module was added in stable but was never intended as a separate module.

### CODE REVIEW

**Comment by william-andre** [comment]
@qdp-odoo Can you have a look at this?

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r-

**Comment by jco-odoo** [comment]
@william-andre There is some kind of conflict with https://github.com/odoo/odoo/pull/114109/files with the rebase  (and maybe in the upgrade script, the same logic for duplicates in l10n_latam_sequence should be put for duplicates then)

**Review by smetl — APPROVED** [review]
@robodoo r+

**Comment by smetl** [comment]
@william-andre Unfortunatelly, you need to rebase :/

**Comment by jco-odoo** [comment]
@smetl I think I did

**Comment by jco-odoo** [comment]
@william-andre Probably just the upgrade branch then

**Comment by smetl** [comment]
@robodoo r+

**Comment by william-andre** [comment]
@robodoo r-

Failing staging

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
