### PR TITLE
Polish states

### PR DESCRIPTION
**Pull request by KarolRk**
Description of the issue/feature this PR addresses: Polish states

Current behavior before PR: Polish states are not available 

Desired behavior after PR is merged: The possibility of choosing Polish states in address

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e for your interest.
@karol1985 you might want to rebase this on `saas-12.5` so that it lands in the upcoming V13.

**Comment by mart-e** [comment]
Hello,

Thanks for the PR but we prefer not to add new states in base.
Instead, could you move them to l10n_pl module?

**Comment by Yenthe666** [comment]
@mart-e do you mean a new `.csv` file in https://github.com/odoo/odoo/tree/13.0/addons/l10n_pl/data then?

**Comment by mart-e** [comment]
@Yenthe666 indeed, this would work

**Comment by Yenthe666** [comment]
@mart-e I was checking this out and I found conflicting results. Look how I've added the states in `l10n_nl` at https://github.com/odoo/odoo/commit/101e0a7ef792c5b1af95a08931647fb485af2ec6#diff-bed8c2902807fcd9c1b290b4cc2689e4
These states, along with the one from Poland have moved in the commit https://github.com/odoo/odoo/commit/6fc4c53404a0171dd528ba7981dcca1564999b33#diff-bed8c2902807fcd9c1b290b4cc2689e4 

The data has actually been moved into `res.country.state.csv` in the `base` module later on (just like this PR was going)

**Pull request closed without merging**
