### PR TITLE
[FIX] website_slides: fix wrong HTML attribute

### PR DESCRIPTION
**Pull request by yajo**
Fix a clash between clas and class that makes the layout crash.

@Tecnativa TT25547

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Well, this is obvious :sweat_smile: @pedrobaeza can you ping somebody?

**Comment by pedrobaeza** [comment]
Maybe a good soul like @tivisse can help :pray:

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
:kissing_heart:

**Pull request closed without merging**
