### PR TITLE
[FIX] web_editor: convert color opacity to be compatible with PIL Image color

### PR DESCRIPTION
**Pull request by prec-odoo**
ValueError 'unknown colour specifier' occurs when we access export_icon_to_png(). This error occurs when we change the colour of an icon in the mailing template, because the value of alpha (opacity) in 'rgba' is in the range of 0 to 1, but PIL Image support colour opacity range 0 to 255.

This commit converts the opacity value range (0 to 1) to a range (0 to 255) compatible with the PIL image library when the colour specifier is 'rgba'.

sentry - 3933353285

see - https://tinyurl.com/2e4ry4jt

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by prec-odoo** [comment]
Hello @odoo/sentry_reviewers Can you please look into this PR?

Thank you!

**Comment by abz-odoo** [comment]
Hello @odoo/rd-framework-editor what do you think about this ?

**Comment by dmo-odoo** [comment]
@abz-odoo If the string `opacity` is also present in the first part of `color`, that is before the `split` delimiter, it will replace this occurence rather than the correct one. You should retrieve both ends of the split string and concatenate the first with the converted second.

**Comment by abz-odoo** [comment]
@prec-odoo up

**Comment by prec-odoo** [comment]
@dmo-odoo , Please look into the changes.

**Comment by dmo-odoo** [comment]
@prec-odoo Well this looks overly contrived now. I meant something like this:
```py
*rgb, a = color.strip(')').split(',')
opacity = floor(float(a) * 255)
color = ','.join([*rgb, opacity, ')'])
```

I didn't test it so maybe there is some details that I might be missing ? Let me know.

**Comment by prec-odoo** [comment]
> @prec-odoo Well this looks overly contrived now. I meant something like this:
> 
> ```python
> *rgb, a = color.strip(')').split(',')
> opacity = floor(float(a) * 255)
> color = ','.join([*rgb, opacity, ')'])
> ```
> 
> I didn't test it so maybe there is some details that I might be missing ? Let me know.

Hello @dmo-odoo ,

In above code, we need opacity in string and when we use join it concatenates ',' after the opacity and we get color like "rgba(0,0,0,63,)"

My suggested changes is below:
``` python
*rgb, a = color.strip(')').split(',')
 opacity = str(floor(float(a) * 255)) + ')'
 color = ','.join([*rgb, opacity]) 
```
if need improve let me know

Thanks!

**Comment by dmo-odoo** [comment]
@prec-odoo Works for me, thanks !

**Comment by dmo-odoo** [comment]
@prec-odoo Sorry, I just realized it would be better to have the `+ ')'` on the last line after the call to `join` because it is not technically part of the opacity itself.

**Comment by dmo-odoo** [comment]
@abz-odoo Don't you ever, in any circumstances, receive an rgba color value which already has the opacity in the right format ? Because if you ever do, the new code _will_ break it since it will multiply it by 255 regardless.

**Comment by prec-odoo** [comment]
> @prec-odoo Sorry, I just realized it would be better to have the `+ ')'` on the last line after the call to `join` because it is not technically part of the opacity itself. So this:
> 
> ```python
> *rgb, a = color.strip(')').split(',')
> opacity = str(floor(float(a) * 255))
> color = ','.join([*rgb, opacity]) + ')'
> ```

@dmo-odoo , changes has been done.

**Comment by abz-odoo** [comment]
Do you think we can merge it @dmo-odoo ?

**Pull request closed without merging**
