### PR TITLE
[IMP] website_payment: convert all jQuery code to use Vanilla JS

### PR DESCRIPTION
**Pull request by msh-odoo**
Description of the issue/feature this PR addresses:

This PR aim to convert all jQuery code into Vanilla JS in website_payment, this way we will reduce the dependency of jQuery in Odoo codebase.

task-3770362

### CODE REVIEW

**Comment by bso-odoo** [comment]
FYI - the module name is missing in the commit title.

**Comment by bso-odoo** [comment]
Do we want to wait for https://github.com/odoo/odoo/pull/174019 to be merged before merging this one ? (In order to be able to properly test it)

**Comment by prra-odoo** [comment]
> Do we want to wait for #174019 to be merged before merging this one ? (In order to be able to properly test it)

Hello @bso-odoo 

We can cherry-pick the commit if needed over here!
Because the Fix PR is ready but the task it is in, contains an improvement point as well which needs to be finished.

Thanks!

**Comment by bso-odoo** [comment]
> > Do we want to wait for #174019 to be merged before merging this one ? (In order to be able to properly test it)
> 
> Hello @bso-odoo
> 
> We can cherry-pick the commit if needed over here! Because the Fix PR is ready but the task it is in, contains an improvement point as well which needs to be finished.
> 
> Thanks!

Sure, why not. Let's cherry-pick the fix. Thanks !

**Comment by prra-odoo** [comment]
Hello @bso-odoo 😃 

I have cherry-picked the fix and also made a small change in porover code!
Can you please have a look at it?

Thanks!

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

**Comment by AntoineVDV** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
