### PR TITLE
[FIX] account: fix tax_totals changes on posted invoice when editing tax

### PR DESCRIPTION
**Pull request by kitan191**
**Steps to reproduce:**
- Install Invoicing
- Create a tax:
  * Tax Name: Tax 10%
  * Amount: 10
  * Included in Price: [checked]
- Create an invoice with an invoice line using the created tax:
  * Price: 100.00
  * Taxes: Tax 10%
- Confirm the invoice
- Check the totals:
  * Untaxed Amount: 90.91
  * Taxes: 9.09
  * Total: 100.00
- Edit the tax by unchecking "Included in Price"
- Check the totals of the posted invoice:
  * Untaxed Amount: 100.00
  * Taxes: 9.09
  * Total: 109.09

**Issue:**
The untaxed amount is recomputed based on the new configuration of the tax, even if the invoice has been posted or cancelled.
The total values should not changed for posted invoices. The line_ids are unchanged though.

**Cause:**
"tax_totals" is a computed field, its computation is based on the existing base lines, tax lines and taxes.

**Solution:**
When the invoice is posted or cancelled, the computation of "tax_totals" should only depend on the existing base lines and tax lines.
"_get_tax_totals_from_base_and_tax_lines" method has been added to handle the computation when the invoice is posted or cancelled.
This method follows the same logic than "_prepare_tax_totals" method, but only gets the necessary values from the base lines and tax lines.

opw-3802336

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by william-andre — COMMENTED** [review]
Shouldn't you just change the condition on line 1177?

**Comment by kitan191** [comment]
> Shouldn't you just change the condition on line 1177?

Do you mean this line?
https://github.com/odoo/odoo/pull/158001/files#diff-1e3bd6be3bfb83a37ec9fb800ce8b1c95afe0be90ff792874ae7299c320a2f6eL1177

Either we are entering the `if` or the `else`, it gets recomputed incorrectly.

**Comment by william-andre** [comment]
Weird, the values should be computed from only the move lines and nothing else :think

**Comment by kitan191** [comment]
Closing this PR as it is introducing ugly complex code to handle a corner case that should not be done from a functional point of view.
Also, this may fix the issue in Accounting, however, it is not possible to prevent it in Sales and Purchase.

**Pull request closed without merging**
