### PR TITLE
[FIX] web_editor: convert link to send by email

### PR DESCRIPTION
**Pull request by Gorash**
Don't convert in table btn-link, and center the button

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nle-odoo** [comment]
hi,


could the button not be also right or left aligned? if I use the editor I can do it.

in a alternative PR I tested (but that is less compatible to mail client from what you told me) I used:

```js
$target.parent().css('text-align')
```

**Comment by Gorash** [comment]
@nle-odoo changes made ;)

**Comment by pga-odoo** [comment]
Hello @nle-odoo @Gorash 

we have been working on same issues https://github.com/odoo/odoo/pull/24572 ,here is few more issues with buttons
* We need to whitelist `display` property from mail sanitiser otherwise it will remove display properties form mail body and need to put vertical-align in case there is text between two buttons https://github.com/odoo/odoo/commit/99171c28e554a2d6d4515c7db0b1b10e5553c265
* Two or more consecutive buttons are not getting converted in inline because we moved anchor in table and after that anchor don't have nextSibling   https://github.com/odoo/odoo/commit/f7aeb5ccbc558fae61cb9c449b149096115a17e7

can you apply these 2 fixes in your branch because our PR is targeting master

Thanks

**Comment by Gorash** [comment]
@pga-odoo It's an other bug, and 'display': 'inline-block' for a table ? it's not inline-table ?

**Pull request merged**
