### PR TITLE
[I18N] *: export source terms

### PR DESCRIPTION
**Pull request by mart-e**

### CODE REVIEW

**Comment by mart-e** [comment]
@nim-odoo could you check if it includes the ribbon terms you were looking for? (enterprise at odoo/enterprise#7058 )

**Comment by nim-odoo** [comment]
hum no, there are a lot missing

**Comment by mart-e** [comment]
Hmm thanks indeed. I have changed a bit the script, should be good now

@robodoo r+

**Comment by mart-e** [comment]
@fw-bot ignore I will regenerate it for saas-13.1 soon

**Pull request closed without merging**
