### PR TITLE
[FIX] crm : update customer info even if null

### PR DESCRIPTION
**Pull request by hamzaislam101**
The compute methods for customer contact information in crm lead would only update the value if the customer has that. This way if a customer is changed which has not value against such field, it won't be updated and the previous value would stay there. Another scenario would be where a lead is duplicated and customer is updated with no such information. Here, the previous set values would stay and user would have to clear them on their own.

Steps to reproduce:
1. Create a contact with no company or address details.
2. Create a crm lead and assign a customer withe company information.
3. Change the customer to newly created customer with no information.

Current Behaviour:
The already set values would stay there.

Expected Behaviour:
The company and address values should be updated as the new customer does not have those valeus.

OPW-3429764

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
ok if it's what we want, but it could not be what we want since the fields are readonly=False (allowing to set the value different than the related field)

an example of a current behavior:

- set the website to "http://google.com" manually
- set a partner_id that doesn't have a website
=> the website set manually is kept (with the fix, the website set manually would be removed)

- set the partner id that has no website
- modify the website manually to http://google.com

save => the website is kept, with the change the website would be removed.

So I believed that with the change, the given scenario would no longer happen, but the behavior previously seemed to be intended.

**Comment by groe-odoo** [comment]
I agree what @nle-odoo explains is a valid scenario, and I am not sure how to balance the two. If you fill out the customer field last it would be annoying for that to reset all other fields. But if you want to change the contact on an opportunity you don't want incorrect fields to stay.

**Comment by thiryr** [comment]
@hamzaislam101 hi

Indeed looking at the task that introduced this the point is that if a user entered the value, we should not change it.

It seems to make sense as naively I would assume there are more instances of people filling out the form, then picking a partner than there are of people picking a partner and changing their mind (though miss-clicks happen, of course).

--------------------------

Ideally we could try comparing the value of the computed fields against the values for the partner (using `self._origin.partner_id` in the compute should work for this). If they match, we can overwrite even if there is already a value, otherwise we keep the current value.

**Comment by tde-banana-odoo** [comment]
Hello,

I confirm @thiryr 's message, this is the wanted behavior. Indeed people generally starts with a lead form with some information that is completed afterwards with partner information if necessary. Alternatively, it is created directly with partner information (e.g. incoming email linked to a recognized partner). So I would not change the code.

Using _origin would be possible, but not sure the added code complexity is really something we want...

Cheers,

**Pull request closed without merging**
