### PR TITLE
FIX/IMP QR-bill for l10n_ch

### PR DESCRIPTION
**Pull request by oco-odoo**
[FIX] l10n_ch: fix QR-bill pdf report so that it matches the spec
Using it as a parf of the regular invoice pdf report was wrong, as this report is subject to the margins defined in its paper format; causing issues as for the rendering of the QR report, which must be displayed at a precise location (just like ISR). wkhtmltopdf doesn't allow having different margin values in the same file, so we did just as for ISR, and now generate QR-bill in a distinct pdf.

[IMP] l10n_ch: add receipt part to QR-bill pdf report

### CODE REVIEW

**Comment by oco-odoo** [comment]
@yvaucher in case you want to give an opinion on that :)

**Comment by smetl** [comment]
@nim-odoo Hello. Can you have a look to this PR plz? This is a necessary fix to fit the legal requirements for l10n_ch. There is some constraints about the paperformat to be used, the precise location of the QR-code and so on making this diff quite huge for a stable version. Also, some translatable terms has been updated inside the report, how are we supposed to handle it in the .po file? Thanks

**Comment by nim-odoo** [comment]
You should not remove the `.css` file, otherwise at server restart it will probably cause errors (file not found). Maybe make it empty instead.

The translations must be updated manually in i18n_extra.

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
