### PR TITLE
[FIX] *: retarget documentation links to saas-15.1

### PR DESCRIPTION
**Pull request by AntoineVDV**
See also:
- https://github.com/odoo/enterprise/pull/24271

### CODE REVIEW

**Comment by seb-odoo** [comment]
Hello, just a side remark as I don't understand why should every code-owners be notified of such changes, shouldn't we have a single variable to store the base URL `https://www.odoo.com/documentation/saas-15.1/` instead of having to update it in multiple places?

**Comment by mart-e** [comment]
> shouldn't we have a single variable to store the base URL https://www.odoo.com/documentation/saas-15.1/ instead of having to update it in multiple places?

That would be a good idea but how? Having to make one commit with -78/+78 seemed acceptable in comparison of the other solutions (JS widget, override views,...). But if you have a simple and global solution, sure.

**Review by mart-e — APPROVED** [review]

**Comment by seb-odoo** [comment]
It's just a matter of passing the variable around (or having it globally somewhere if we want to avoid explicit passing).

For static/JS code other such values are currently put in `session_info`. `session` can be imported from anywhere and if we want the value could also be part of `env` or `service` to be accessed from anywhere without import. Then we can either `t-attf-` the URL in, or create an `env`/`service` method to generate the URL (if we want to abstract the string manipulation part).

For pythons templates I guess the easiest (if we don't want to have to pass the param explicitly) is the `qweb` rendering context?

And actual python code same as in JS, either store the variable in a specific file and import it, or store it in `env` or another globally available object.

The only place where I'm not sure is the few occurrences inside the manifest files, maybe those can't be dynamically crafted from an import (?), and they definitely don't have access to `env`.

**Comment by mart-e** [comment]
It's in the form views, not qweb, mostly in the `res.config.settings` (but not exclusively).

**Comment by seb-odoo** [comment]
In legacy views I suppose we would need a widget for that as you suggested initially. Considering the amount of repetition in current code (not only the base URL, but also the `class`, `title`, `target` and every other attribute), it would seem like a reasonable thing to do generally speaking.

By the way do we plan to translate the documentation some day? Because that would imply having a dynamic URL with the correct language depending on the user language, and maybe a default if the current language is not available. Then this code should definitely be factorized.

But as we are getting close to converting these views to Owl, it's probably better to delay this change until they are converted (or to introduce it at the same time), to avoid having to adapt this potentially new widget just few months after its creation.

That being said it doesn't have to be all or nothing, if this is something we want to reach eventually, we could already introduce the variable and use it where possible, in particular deciding how it could be defined in python, and take it from there.

**Comment by AntoineVDV** [comment]
@seb-odoo That's indeed a good task idea since the documentation is already translated. Do you want to handle it?

**Comment by seb-odoo** [comment]
@AntoineVDV I don't want to specifically do it myself, I was mainly suggesting it but it should probably be a framework task instead, so feel free to take it from there. Also the suggestion doesn't invalidate the current PR as it would target master instead.

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
