### PR TITLE
[FIX] stock: remove incorrect placeholder + default search

### PR DESCRIPTION
**Pull request by amoyaux**
It's not possible to copy paste in the lot_name directly. It has been remove since the import button.

Also add by default a search on hand in the quant view from the stock.move.line. We don't want to show quant already send to customer location or without quantity

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Whenrow** [comment]
robodoo r+

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
robodoo rebase-ff

**Comment by amoyaux** [comment]
robodoo r+

**Pull request closed without merging**
