### PR TITLE
[FIX] website_sale_delivery: use RPC data for fixed_price

### PR DESCRIPTION
**Pull request by backspac**
Steps:
- Install eCommerce
- Go to Website > Configuration > Settings
- Select Pricing > Product Prices > Tax-Included
- Check Shipping > Shipping Costs
- Go to Configuration > eCommerce/Shipping Methods
- Publish Normal Delivery Charges
- Go to the eCommerce
- Add a product to the cart (here, Customizable Desk)
- Click My Cart > Process Checkout
- Select Normal Delivery Charges

Bug:
The delivery price of the Normal Delivery Charges line isn't tax-included.

Explanation:
When we arrive on the delivery selection, prices are computed with an RPC. But delivery methods with a fixed price don't use the RPC results and display the fixed price straight away.
This is a relic of 12.0 where you would have to click on a delivery to see its price. At that time, we tried to display as much info as early as possible (the fixed price was already known).

### CODE REVIEW

**Comment by backspac** [comment]
Ping @nim-odoo

**Review by nim-odoo — COMMENTED** [review]
You should export the translation, otherwise it looks good.

**Comment by rdeodoo** [comment]
Hi
`This is a relic of 12.0 where you would have to click on a delivery to see its price. At that time, we tried to display as much info as early as possible (the fixed price was already known).`

When the automatic RPC calls was developped, it was really for a more convenient UX, on top of the default behavior to show the amount on click.
And it was only useful for delivery that needed to query the provider, which might take 20 seconds for some.

But for delivery that we know the price without having to ask the provider, we still want to show that price instantly IMHO.
Why waiting to show free delivery if we already now it will be free ?

**Comment by backspac** [comment]
@rdeodoo IMHO, sticking to the RPC is safer as taxes can be applied to deliveries. Theoretically, there could be fixed ones applied to free deliveries (e.g. customs duties). I don't think it's worth taking the risk of displaying incorrect data.

**Comment by rdeodoo** [comment]
In that case the fix should be to display the prices with the taxes directly, for fixed prices & free prices. It makes no sense to async load that.
The async loading is **ONLY** there to show to the user the prices once we have a reply from the third party service.
Historically, the user had to wait a long time before the page was rendered, because the business code was querying the third party services and waited for the replies before rendering the view, might take up to 20 seconds. Then it changed to onclick for that reason, but if you had 10 delivery options, the user had to click on all of them to 'discover' the cheapest one, not convenient.
So the async calls were introduced to fetch those data automatically.

But I am convinced we shouldn't get rid of the data being displayed instantly at rendering level, it wouldn't make more sense that getting the price of an item on /shop with an async rpc. The taxes should be applied on the template or in business code for it to be displayed once the page is being rendered.

**Comment by rdeodoo** [comment]
Never went further than my previous reply.
Not sure if still relevant and there is no opw/task.
You can reopen if needed.

**Pull request closed without merging**
