### PR TITLE
[FIX] test_module_operations: nightly errors

### PR DESCRIPTION
**Pull request by Feyensv**
Enable the test for payment modules, as we want to test their install/uninstall. But disable the test for the deprecated payment modules, which can only be installed through command line since 16.0.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@Xavier-Do can i have a custom config to test the module operations (maybe only the payment ones) ?

**Comment by Xavier-Do** [comment]
> @Xavier-Do can i have a custom config to test the module operations (maybe only the payment ones) ?

I can do that but it is always easier to give a link to the build you want to reproduce ;)

**Comment by Feyensv** [comment]
https://runbot.odoo.com/runbot/build/20232703
& other uninstall tests on payment_alipay, payment_payumoney, payment_payulatam, payment_ogone

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
