### PR TITLE
[FIX] models, test_impex: export relational field,if no record set,em…

### LINKED ISSUE #35338: Excel export many2x adds False in cell if no referenced Record is set. Import not possible
Impacted versions:
10, 11,12
Steps to reproduce:
export Excel-File from odoo with import compatibility and selected many2x fields
Current behavior:
if no Record is Set value is =False()
Expected behavior:
should be empty
Video/Screenshot link (optional):

### PR DESCRIPTION
**Pull request by ppr-odoo**
Pad:https://pad.odoo.com/p/r.f4f1badf24dca20b849399b40ae7ddd5
Task:https://www.odoo.com/web#id=2059498&action=333&active_id=1364&model=project.task&view_type=form&menu_id=4720
Fixes #35338

### CODE REVIEW

**Comment by Julien00859** [comment]
LGTM, thank you :)

sudo -u {@xmo-odoo,@rco-odoo} robodo r+ please

**Comment by Julien00859** [comment]
force-pushed to rebase on last 11.0 @rco-odoo @xmo-odoo don't forget this one

**Comment by xmo-odoo** [comment]
@rco-odoo yes I rather expect that it thoroughly breaks export_data.

**Comment by yelizariev** [comment]
Canceled and superseded by https://github.com/odoo/odoo/pull/61948

**Comment by C3POdoo** [comment]
Dear @ppr-odoo,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
