### PR TITLE
[FIX] account: forbid making refunds on incompatible journals

### PR DESCRIPTION
**Pull request by oco-odoo**
It shouldn't be possible to create refunds on misc journals, as the tax report would compute the wrong multiplicator sign, and hence end up being entirely wrong.

### CODE REVIEW

**Comment by smetl** [comment]
@robodoo r+

**Comment by smetl** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
@oco-odoo @smetl Ugh this change is really not cool. If you now have any connector or cron job that generates credit notes and if the journal type is wrong (e.g `bank` instead of `sales`) this will break your connector/cron in the backend without you really noticing directly. This can really jam up or kill systems.
I'd say this is a breaking change in stable which probably shouldn't be done.
Why was there not chosen to do a `_logger.critical` in the stable versions for V13/V14 and then making this breaking change in master?

**Comment by fclementic2c** [comment]
On accounting side, this is wrong if I understand correctly what you do here.
You cannot ignore any entry with vat whatever the journal. 
Why don't you correct the tax report as I already asked for? 
Think about migration of old customers also.

**Comment by oco-odoo** [comment]
> @oco-odoo @smetl Ugh this change is really not cool. If you now have any connector or cron job that generates credit notes and if the journal type is wrong (e.g `bank` instead of `sales`) this will break your connector/cron in the backend without you really noticing directly. This can really jam up or kill systems.
> I'd say this is a breaking change in stable which probably shouldn't be done.
> Why was there not chosen to do a `_logger.critical` in the stable versions for V13/V14 and then making this breaking change in master?

You told it yourself: the journal type is wrong. If you're doing things that are not correct from the start, we can't guarantee any behavior. This is just a stronger safeguard, because we faced this issue with one customer and don't want to allow it. Since it's functionally not sound doing this (if you want to post something in a misc journal, it should be a misc operation, by definition), we judged it the best way to avoid troubles.

**Comment by oco-odoo** [comment]
> On accounting side, this is wrong if I understand correctly what you do here.
Misc journals are for misc operations, that's just it. Nothing wrong here.

> You cannot ignore any entry with vat whatever the journal.
That's not what we do. You can still make misc operations impacting the tax report (like cash basis taxes do). 

> Why don't you correct the tax report as I already asked for?
Because we can't do something that big in stable, as we already told you. Changing that without any additional scripting is the *guarantee* that a lot of customers are going to see their tax report suddenly change (even in the past). Though, we did it in saas-14.1, by introducing a new field on move lines  https://github.com/odoo/enterprise/commit/c4177ed96e9ef57e3d82bf740cc2beeab723bcdf  

> Think about migration of old customers also.
That's precisely why it would be too risky to change the tax report in stable: whats was patched to work from weird/incorrect data from an old version should not be broken again. Existing invoices on misc journals are not impacted by this fix. I still need to check the migration script for this use case; we'll probably end out adding something in it as well.

**Comment by Yenthe666** [comment]
> You told it yourself: the journal type is wrong. If you're doing things that are not correct from the start, we can't guarantee any behavior. This is just a stronger safeguard, because we faced this issue with one customer and don't want to allow it. Since it's functionally not sound doing this (if you want to post something in a misc journal, it should be a misc operation, by definition), we judged it the best way to avoid troubles.

@oco-odoo I'd consider this a stable breakage though? A `ValidationError` triggers a rollback. This has been introduced over 1.5 year after the release and means any cron job or background process which has any journal 'misconfigured' would break due to this. Plus it might be debatable if you'd consider it wrong I guess.
I think these type of changes should be added as a stable guideline at https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean, no? CC @mart-e

**Comment by mart-e** [comment]
Hi,

Regarding the stability guidelines, the main idea is "only fix, no changes of behaviour or improvements". Any change is obviously [a change of behaviour](https://xkcd.com/1172/) for somebody so it's always a tradeoff between what we prevent and what we may break (the value vs risk ratio).
The more we go in the past, the more the value must be important as there are many people running the system for a long time and are satisfied with the way it is (e.g. in 12.0, don't touch it if there is no traceback).

In this case, is it worse to let user register refunds on misconfigured journals or to raise an error and make him reconfigure correctly its journals? Break things now or letting accounting entries to be generated on the wrong journal? Which one is more frequent? Is there other alternatives with a better value/risk ratio ? Changing the report is apparently more risky but was there less risky alternatives like changing views or onchange warning?
I let my accounting colleagues decide.

**Comment by Yenthe666** [comment]
Well I still believe a `_logger.critical` in old versions & `ValidationError` in V14/master would've been a securer and better trade-off.

**Comment by pedrobaeza** [comment]
We needed to do a lot of amends on OCA tests that don't care about the type of the linked journal due to this change:

* https://github.com/OCA/account-payment/commit/c5e925896cd2fb553e713c7a454552d605d7f103
* https://github.com/OCA/account-payment/commit/e8000c70f56b08e746198b656fad9b7945b06506
* https://github.com/OCA/l10n-spain/commit/749f171f315753e8d2ee2aac60497b0426aa66a6
* https://github.com/OCA/l10n-spain/commit/a1e6414655300bb65066c37e7296ee22168e7628
* https://github.com/OCA/bank-payment/commit/eb84bae097ce5b890532adc395dec78b87a535f5
* https://github.com/OCA/bank-payment/commit/05badcddc6efa1472285cfeb852b091b274f614a
* etc

But it's because we didn't care about that aspect as Odoo allows it, but that doesn't mean that is strictly correct, so I'm OK to put the constraint, but from the rest of the feedback, it's very bad if enterprise reports don't take into account other journals except sale/purchase one. What happen with imported accounting entries that want to be computed in VAT reports in the middle of a period?

**Comment by oco-odoo** [comment]
> We needed to do a lot of amends on OCA tests that don't care about the type of the linked journal due to this change:
> 
> * [OCA/account-payment@c5e9258](https://github.com/OCA/account-payment/commit/c5e925896cd2fb553e713c7a454552d605d7f103)
> * [OCA/account-payment@e8000c7](https://github.com/OCA/account-payment/commit/e8000c70f56b08e746198b656fad9b7945b06506)
> * [OCA/l10n-spain@749f171](https://github.com/OCA/l10n-spain/commit/749f171f315753e8d2ee2aac60497b0426aa66a6)
> * [OCA/l10n-spain@a1e6414](https://github.com/OCA/l10n-spain/commit/a1e6414655300bb65066c37e7296ee22168e7628)
> * [OCA/bank-payment@eb84bae](https://github.com/OCA/bank-payment/commit/eb84bae097ce5b890532adc395dec78b87a535f5)
> * [OCA/bank-payment@05badcd](https://github.com/OCA/bank-payment/commit/05badcddc6efa1472285cfeb852b091b274f614a)
> * etc
> 
> But it's because we didn't care about that aspect as Odoo allows it, but that doesn't mean that is strictly correct, so I'm OK to put the constraint, but from the rest of the feedback, it's very bad if enterprise reports don't take into account other journals except sale/purchase one. What happen with imported accounting entries that want to be computed in VAT reports in the middle of a period?

You misunderstood :) We do take other journals into account as well, just not exactly in the same way (it's a matter of computing a *-1 multiplicator on the balance depending on the journal type to get the result to be shown in the report; not the best design choice, I agree, and that's why is was slighlty changed in 14.1 to be more intuitive). So, of course, we do support import through regular 'misc' entries if needed, even for tax operations.

**Pull request closed without merging**
