### PR TITLE
[FIX] wrong error string handling in xmlrpc e handling

### LINKED ISSUE #13111: xmlrpclib.Fault with empty FaultString for opnerp.exceptions.UserError
Impacted versions: Version 9.0c (Community Edition)

Steps to reproduce:

```
class DemoModule:
    __name = "demo.module"
    def  demo_method(self):
        raise UserError("Error message")
        return True

```

From web service api:
`models.execute_kw(db, uid, password,'demo.module', 'demo_method', [[1]])`

Current behavior: xmlrpclib.Fault object with empty FaultStirng

`xmlrpclib.Fault: <Fault 2: 'None'>`

Expected behavior: xmlrpclib.Fault object with FaultStirng "Error message"

Video/Screenshot link (optional):

### PR DESCRIPTION
**Pull request by blaggacao**
Fixes #13111

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by blaggacao** [comment]
Could you eventually merge it in 10.0, also?

**Comment by Yenthe666** [comment]
@blaggacao why don't you make it against 10.0 right away? It will then be forward ported to 11.0 by Odoo itself.
Thanks for the PR too!

**Comment by blaggacao** [comment]
@Yenthe666 I thought and did, but there was no online rebase function in github. Do you happen to know how to fetch pull requests locally?

**Comment by blaggacao** [comment]
@odony You already confirmed this solution, could you merge it?

**Comment by Yenthe666** [comment]
Alternatively @xmo-odoo could have a look.

**Comment by Yenthe666** [comment]
@blaggacao I made a PR for V9 to handle it in ALL versions at once 😉 See https://github.com/odoo/odoo/pull/22276

**Comment by odony** [comment]
Thanks for the backport, merged in 9.0 at 5d086cea9b97cec4fe8d07bf6cb06b3d7ee28af7, via #22276.
It will be forward-ported soon to later versions.

**Pull request closed without merging**
