### PR TITLE
[FIX] hr_skills, hr_skills_{}: fix typo

### PR DESCRIPTION
**Pull request by niyasraphy**
fix typo for resume in hr_skills, hr_skills_slides, hr_skills_survey

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
hi @tivisse ,
if you have time, can you review this.
thanks

**Comment by tivisse** [comment]
Hi @niyasraphy 

Thanks for the feedback.

Unfortunately, the runbot is red, and the error seems to be linked to your development.

Could you have a look ? 

Thanks.

**Comment by tivisse** [comment]
@robodoo r+

**Comment by niyasraphy** [comment]
@tivisse staging seems failed for this, should we trigger something or..

**Comment by tivisse** [comment]
@robodoo retry

**Pull request closed without merging**
