### PR TITLE
[IMP] l10n_pt: Set default tax closing accounts

### PR DESCRIPTION
**Pull request by antoine162**
Set the default accounts for tax closing entries to: 
- "2436 VAT - Payable" (liability_current, Portuguese: "IVA - A pagar") and 
- "2437 VAT - Recovering" (asset_current, Portuguese: "IVA - A recuperar").

taskid: 3524378

### CODE REVIEW

**Comment by tsb-odoo** [comment]
LGTM

**Review by epictete — CHANGES_REQUESTED** [review]
LGTM for `l10n_pt`, but there are still many other l10n that are still using `property_tax_{payable,receivable}_account_id`. Could you please fix them as well?

Also, please remove the unused keys from `_get_*_template_data()` :wink:

**Comment by oco-odoo** [comment]
> LGTM for `l10n_pt`, but there are still many other l10n that are still using `property_tax_{payable,receivable}_account_id`. Could you please fix them as well?
> 
> Also, please remove the unused keys from `_get_*_template_data()` 😉

+1

Declaring the tax closing accounts is often done like here https://github.com/odoo/odoo/blob/17.0/addons/l10n_ch/models/template_ch.py#L17 ; this does not work. Everything should be done on the tax groups directly. Perhaps we should add some kind of tests for that ? Or raising when a key in the template dict is wrong? Not too sure, but it's too permissive as it is IMO :thinking: 

Also, this should be done in stable, as a fix, as we already discussed :)

**Comment by oco-odoo** [comment]
In the meantime, we should fix the accounts used for the closing where it's useful: none of the tax payable, tax receivable or advance payment accounts should be used on invoices/payments/taxes/whatever in the default configuration, as it would break the tax closing. This happens currently on l10n_nl.

**Comment by antoine162** [comment]
Will be done in 16.2+ for all locs that were still setting tax closing accounts using the property_ fields on the chart templates
https://github.com/odoo/odoo/pull/155074

**Pull request closed without merging**
