### PR TITLE
add ppreeper cla

### PR DESCRIPTION
**Pull request by ppreeper**
Description of the issue/feature this PR addresses: add cla signature

Current behavior before PR: normal

Desired behavior after PR is merged: normal

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by ppreeper** [comment]
Did I do something wrong. It is not merging correctly.

**Comment by mart-e** [comment]
Hi,

There was an issue during the testing so it failed. I just rebased again to keep a clean commit history.
@robodoo +

**Comment by ppreeper** [comment]
going to retry in 13.0 branch

**Comment by mart-e** [comment]
@ppreeper ok for the new PR but if you push in the branch after my "r+", it will break the review and not merge it.

**Pull request closed without merging**
