### PR TITLE
[Fix] change Oauth2 Access Token placement from URI Query String to Bearer Authorization header

### PR DESCRIPTION
**Pull request by ghost**
Description of the issue/feature this PR addresses:

- This patch fixes issue #63963, where the main concerns are:
  - Security considerations: Access Tokens end up in our logs (Odoo server logs) and potentially in the provider's logs as well.
  - Upcoming deprecation of the _URI query-string parameter_ as an option for placing _Access Tokens_ by at least some providers (for example Google has scheduled it for _June 1st, 2021_).

Current behavior before PR:

- The "OAuth2 Authentication" (technical name: `auth_oauth`) module uses _URI query-string parameter_ for sending _Access Tokens_ to Oauth2 provider's endpoints
- There is no configuration option to change this behavior, as Access Token placement is hardcoded into the source code
- As a result of such placement Access Tokens end up in the logs here and there.

Desired behavior after PR is merged:

- Configurable Access Token Placement per Oauth2 provider
- In order to allow existing deployments more smooth transformation, new selection field  is added to the Oauth2 providers model&view, with the default value of "bearer", which will ensure correct placement of Access Tokens in most cases and Access Tokens will NOT be logged anymore.
- Just in case,  the "URI query-string parameter (deprecated)" option is also included into the new field's selection options, which will allow users to switch back to the old behavior if necessary, depending on the provider. However, the "URI query-string parameter (deprecated)" option is a temporary solution for old Odoo users (but only some of them might need it), and it should be removed from the selection options in the future, because if it is chosen, then exactly the old behavior takes place and Access Tokens will be logged again, so choosing this option should be discouraged, this is why the "(deprecated)" warning is added to the field's label.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
An stable version can't change DB layout, so this should target master branch, not 14.0.

**Comment by tvibliani** [comment]
Additionally this PR is blocked due to CLA, but my CLA update is pending merge, see the #63969. When the CLA will be merged, then I will make the same PR to the `master` branch to avoid the same block from the CLA bot what I got here.

**Comment by pedrobaeza** [comment]
Maybe you can find in stable to check the type of auth without adding additional fields, but first I would wait for confirmation from Odoo stuff if they are keen to add these things in stable.

**Comment by tvibliani** [comment]
If we redirect this PR to master, then I do not see need for the selection field, my best guess is that any good Oauth2 provider must have support for the "Bearer" option in the first place and the new selection field here was introduced in order to allow users of old/existing deployments to get back the old behavior or choose alternative option in case if the new placement would not work for them for any reason.

As a workaround solution I made separate community module `auth_oauth_access_token_placement`, which will add the selection field exactly the same way as it was proposed in this PR in the first commit. 

Now, as the alternative solution exists (via the community module) for anyone who might need to get back the old/alternative behavior or switch early to the new behavior, it is less of a problem to change access token placement directly in the `_auth_oauth_rpc()` method's code without any DB layout change, and only support the single *Bearer* option in the core `auth_oauth` module. This will be exactly the change that I will introduce in the next commit, i.e. changing the old query-string parameter placement of Access Token to the new Bearer Authorization header placement, which must work with any good Oauth2 provider. Thus, the issue will be resolved without DB layout change and no PR redirect will be needed.

**Comment by tvibliani** [comment]
As per **OpenID Connect**[_(1)_][1] specification:
> Servers SHOULD support the Bearer Token Type; use of other Token Types is outside the scope of this specification. 

So, my guess that any good Oauth2 provider must have support for the "Bearer" option turns out to be very exact in this case.

[1]:https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse

**Comment by tvibliani** [comment]
Rebased

**Pull request closed without merging**
