### PR TITLE
[11.0][stock_account] change the logic to determine the unit price to be applied for valuation

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
The logic to determine the unit price to be used to calculate the valuation of a stock move is currently applying a rounding based on the company currency.

It makes no sense to use the rounding based on the company currency for a unit price. Because the price unit is afterwards multiplied by the quantity. 

It seems more correct that the unit price should be rounded by the product price.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jbeficent** [comment]
@jco-odoo do you think that this is right?

**Comment by jco-odoo** [comment]
I would not take the Decimal Precision for that.  They are already doing their work in the interface.  I think we wanted to base ourselves more on the value of the stock move (and the total quantity as such) than on that price_unit.

**Comment by jbeficent** [comment]
@jco-odoo In my case I wanted to make 40 units of a plastic component. The unit cost was 0,049, and was rounding to 0 considering the EUR rounding. But then the total cost is 40*0,049 = 1,96€.

Due to the rounding I was not able to produce the 40 units of the plastic component.

In that case no rounding should be applied at all then.

**Comment by jbeficent** [comment]
@jco-odoo haloens when you want to allocate costs to finished products fron raw materials, where the unit cost of the raw material is 0.0045.

**Comment by mreficent** [comment]
@sle-odoo could you check?

**Comment by sle-odoo** [comment]
> It makes no sense to use the rounding based on the company currency for a unit price

> unit cost of the raw material is 0.0045

it's always a tricky question since in some cases an accounting entry will be created for this value, and an accounting entry not fitting the currency's rounding doesn't make sense, that's why we use the currency rounding here.

**Comment by pedrobaeza** [comment]
coming to this through codetriage.com. @JordiBForgeFlow is this still interesting for you?

**Comment by C3POdoo** [comment]
Dear @JordiBForgeFlow,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
