### PR TITLE
[CLA] create ivyshnevska.md

### PR DESCRIPTION
**Pull request by i-vyshnevska**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Why do you backport your CLA signature in version 10? Do you plan to make a patch in that version too?
If needed, you can always add your CLA in the same pull request as the fix you submit.

As you are submitting for version 10, please keep in mind that 10.0 is in end of life, meaning we only accept critical bug fixes, not improvement (cf our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean)).
I wanted to be sure you are aware of that before submitting a contribution through a PR.

**Comment by i-vyshnevska** [comment]
Hi,
 Yes, need for v10, and seems to port cla to latest version is simpler

**Comment by i-vyshnevska** [comment]
@mart-e could PR be merged it's blocks my https://github.com/odoo/enterprise/pull/3395

**Comment by mart-e** [comment]
robodoo r+ :+1:

**Pull request closed without merging**
