### PR TITLE
[FIX] stock: Block edits to locked stock move line

### PR DESCRIPTION
**Pull request by richard-willdooit**
Description of the issue/feature this PR addresses:

Transactions which are "locked" should not be edited through the UI

Current behavior before PR:

Locking a picking allowed you to change details via the smart button

Desired behavior after PR is merged:

Locked down more.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by richard-willdooit** [comment]
@AhmedAmirK 

Some oversights here.

cc @amoyaux

**Comment by amoyaux** [comment]
Hey, thanks for the fix. Could you just add it on the package, result package and owner. So everything is done at once

**Comment by richard-willdooit** [comment]
> Hey, thanks for the fix. Could you just add it on the package, result package and owner. So everything is done at once

Done

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
Thanks

**Pull request closed without merging**
