### PR TITLE
[FIX] stock: fine tuning of 1adfee2

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
Before this commit, in large database the request can be very very long. or an memory error can appear. (the search([]) is not a good idea)

[FIX] stock: fine tuning of https://github.com/odoo/odoo/pull/134974/commits/1adfee2e0fde7944316f1e8b55e61f12f020b1ac

@mamatch
@Whenrow 
@ticodoo

https://github.com/odoo/odoo/pull/134974

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW #3529528

**Comment by fmdl** [comment]
ping @ticodoo

**Comment by fmdl** [comment]
ping @simongoffin

**Comment by ticodoo** [comment]
Is the performance of doing 1 giant sql query that much better than doing the 2 searches? (i.e. some performance numbers would help justify the change)

Also you would need to add in a check that `value` is an int/float to prevent SQL injection attacks (one of the reasons why I prefer to avoid a direct SQL query).

Alternatively, can we compromise by making the search([]) have a reasonable limit value (e.g. `name_search` does this)? This is just a search method that wasn't even available until now after all.

**Comment by fmdl** [comment]
it is not possible to make sql injection with execute, because psycopg2 format params to prevent injection.

It is not a giant SQL query. Because it is inselect.

But with your dev if you have 1 million lot with quantity is zero, and make a search, postgres with execute some think like this : `select id from stock_lot where id in [array with 1 million of element]`.

@odony @rco-odoo

**Pull request closed without merging**
