### PR TITLE
[i18n] calendar: missing term

### LINKED ISSUE #26017: [11.0] Calendar : +n more button is'nt translatable
Impacted versions:
11
Steps to reproduce:
Choose a language other than english and create 4  events on same day
Current behavior:
Button "+2 more"
Expected behavior:
Something in the language
(the more button isn't in translation files)
Video/Screenshot link (optional):
capture du 2018-07-27 11-27-42

### PR DESCRIPTION
**Pull request by Julien00859**
Closes #26017

### CODE REVIEW

**Comment by Julien00859** [comment]
The word is translated already, no need to regenerate the PO file

**Comment by mart-e** [comment]
Is it? I see `More` but the `_t()` is case sensitive

**Comment by Julien00859** [comment]
had lowercased "plus" in french, maybe a type in the terms ?

**Comment by mart-e** [comment]
```diff
 
+#. module: web
+#. openerp-web
+#: code:addons/web/static/src/js/views/calendar/calendar_model.js:447
+#, python-format
+msgid "more"
+msgstr ""
+
```
it's because you were exporting `calendar` and not `web` ;-)
it's probably  that another module installed on your db already translate this term

**Pull request closed without merging**
