### PR TITLE
[IMP] hr_timesheet_invoice: Declare explicitely the field in the view

### PR DESCRIPTION
**Pull request by oihane**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is needed to about problems when product.product or product.template contains a field named product_id, which seems improbable, but with certain abstract models that needs this field happens (see https://github.com/odoomrp/odoomrp-wip/blob/1423c4801b80aa79b93ee32b0569c0d6223dfa6e/product_variants_no_automatic_creation/models/product_product.py#L10, which inherits from https://github.com/odoomrp/odoomrp-wip/blob/1423c4801b80aa79b93ee32b0569c0d6223dfa6e/product_variants_no_automatic_creation/models/product_configurator.py#L26).

:+1:

**Comment by Daniel-CA** [comment]
LGTM: :+1:

**Comment by agaldona** [comment]
We really need these change to be merged, please
cc @odony @sle-odoo
:+1:

**Comment by odony** [comment]
Looks good to me, the fields should have been fully-qualified from the start. Thanks @oihane!
Cherry-picked in 8.0 at 630f3d566f4d8bdec55f05345b8b79f4089490df

**Pull request closed without merging**
