### PR TITLE
[FIX] account_fleet: Field vehicle_id unavailable on vendor refund

### PR DESCRIPTION
**Pull request by simongoffin**
The fleet vehicle_id must be visible on vendor refund

opw:2471784

### CODE REVIEW

**Comment by jco-odoo** [comment]
But not required then?

**Comment by jco-odoo** [comment]
(William indeed better)

**Review by william-andre — COMMENTED** [review]
This field is used to create a fleet service when posting the invoice. I don't see a use case to create a service on refunds that makes sense.
Why does the client want to add it on refunds?

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
