### PR TITLE
[IMP] mail: change smiley

### PR DESCRIPTION
**Pull request by mart-e**

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Seems like a critical improvement. I am not sure I am ready for this.

**Comment by wtaferner** [comment]
I think we need a test for this, right @tde-banana-odoo? ;-)

**Comment by tde-banana-odoo** [comment]
@wtaferner Sounds like a good idea. Do you want to write it ^^ ?

**Comment by wtaferner** [comment]
Hehe, sure, it already failed on your comment above twice ;-)

But, yeah, I will do that for you...

PASS 

PASSED all tests, ready to merge.

**Comment by tde-banana-odoo** [comment]
LGTM then.

**Pull request merged**
