### PR TITLE
[IMP] hr_recruitment: improve meeting smart button 

### PR DESCRIPTION
**Pull request by Williambraecky**
Change the text of the meeting smart button to be similar to the one
found in appraisals, it now also shows the date.

Closes odoo#72649

Task ID: 2578165

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo rebase-ff

**Comment by Williambraecky** [comment]
Forgot upgrade PR

**Comment by Williambraecky** [comment]
@tivisse this will need a retry I believe once the upgrade pr is r+ed

**Comment by Williambraecky** [comment]
Removed the fix commit since it was forward ported here: https://github.com/odoo/odoo/pull/73635

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
