### PR TITLE
[FIX] Change date deprecated checking due to 3rd October 2022. 

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
Description of the issue/feature this PR addresses: The condition of this module being depecrated is the oposite. When today is bigger than the last date. 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@cesar-tecnativa Please change commit message to `[FIX] google_drive: Correct deprecation date comparison`

**Review by nicomacr — APPROVED** [review]
LGTM

**Comment by cesar-tecnativa** [comment]
> @cesar-tecnativa Please change commit message to `[FIX] google_drive: Correct deprecation date comparison`

done

**Comment by pedrobaeza** [comment]
@kba-odoo @tivisse can you please check?

**Comment by kba-odoo** [comment]
fw-bot up to 15.0

robodoo r+

**Comment by kba-odoo** [comment]
@cesar-tecnativa could you please sign the CLA as per [this doc]? :-)

[this doc]: https://github.com/odoo/odoo/blob/15.0/doc/cla/sign-cla.md

**Comment by pedrobaeza** [comment]
@cesar-tecnativa you have to include your name and github login in this file:

https://github.com/odoo/odoo/blob/13.0/doc/cla/corporate/tecnativa.md

Put it as a new commit here with the commit message `[CLA] Add cesar-tecnativa to Tecnativa corporate`

**Comment by jjscarafia** [comment]
@pedrobaeza @cesar-tecnativa 
do you have any plans to improove/keep this functionality on OCAafter the 3rd of october?

**Comment by pedrobaeza** [comment]
I'm afraid not. It's not simple to comply with the newer rules for accessing the API.

**Comment by jjscarafia** [comment]
Great, thanks for the quick response @pedrobaeza !

**Comment by pedrobaeza** [comment]
Closing in favor of #97163

@kba-odoo thanks for handling it.

**Pull request closed without merging**
