### PR TITLE
saas-14.3-toolbar-clean-nby

### PR DESCRIPTION
**Pull request by Goaman**

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by dmo-odoo** [comment]
@robodoo r-

**Comment by dmo-odoo** [comment]
@robodoo *You* make no sense.

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by dmo-odoo** [comment]
@mart-e This is moved code again. This code is fine because a test is explicitely made to know whether it is text content or html content and innerHTML is called only if it is not text:
```js
const fakeEl = document.createElement('fake-element');
    if (isText) {
        fakeEl.innerText = data;
    } else {
        fakeEl.innerHTML = data;
    }
```

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: moving existing code. A followup task (id 2506229) was created for cleaning existing code.

**Comment by dmo-odoo** [comment]
@robodoo r+

**Comment by dmo-odoo** [comment]
@robodoo When I `r-`, you complain. When I `r+`, you complain. Just shut up already and merge the damn PR, thanks.

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff

**Comment by dmo-odoo** [comment]
@robodoo I'll watch you burn. 🔥

**Pull request closed without merging**
