### PR TITLE
[FIX] account: credit card card charged multiple times

### PR DESCRIPTION
**Pull request by jvh83**
Video 1 (Issue): https://drive.google.com/file/d/1oXYcDJgaT9gmhkjE08yJlXwIL1qPwS1Y/view?usp=sharing
Video 2 (Behaviour after PR): https://drive.google.com/file/d/1cr53H5tIzT6RDDGnEV74DnJAeNzizEcq/view?usp=sharing

Issue:
When using the register payment with a token with any of the payment acquirers,
if there is a concurrent access error during the reconciliation process,
the payment intent is sent multiple times to the acquirer, making the card charged multiple times.

Steps:
- Have a V14 database (only tested this version) with sale_mmanagement, payment_stripe and invoicing
- Configure Stripe with your public and secret key (2FA is now enforced for Stripe accounts, therefore, we don't have a generic test account anymore. You have to create your own. It is quite fast and easy to do)
- Have a portal user PU with an already registered payment token PT
- Go to Invoicing
- Create a new invoice I:
	- Customer PU
	- Add anything in invoice lines
- Confirm I
- Register a payment for I:
	- Journal: Stripe
	- Saved Payment token: PT
AT THIS STEP, YOU MUST ENSURE A CONCURRENT ACCESS ERROR WILL RAISE DURING THE RECONCILIATION
- Create Payment

Log analysis:
A first payment intent is sent to Stripe. The card is charged and Stripe answers that all went as expected.
We try to process the payment, but a concurrent access error occurs.
A retry is done.
A payment intent is sent again to Stripe, The card is charged AGAIN and Stripe answers that all went as expected.
We try to process the payment, but a concurrent access error occurs.

For each retry, the intent is sent and the card is charged.

If the first retry succeeds, then Odoo can finish the process. There will be only 1 payment transaction on Odoo's side (others have been rollbacked)
but there will be 3 on Stripe's side and the card will be charged 3 times.

This PR mitigate this behaviour.
It doesn't address the root cause (what is causing the concurrent error) but avoids sending the payment intent multiple times.

New Behaviour:
If the process triggers a concurrent access update, the retry doesn't trigger and the payment is not reconciled with the invoice.
Instead, an outstanding balance is shown and the user has the ability to add it manually to the invoice.
A log is posted on the concerned invoice(s)

OPW-2662964

### CODE REVIEW

**Review by AntoineVDV — APPROVED** [review]
LGTM regarding the problem resolution.

**Comment by csnauwaert** [comment]
@jev-odoo 
Have you checked if we use idempotency-key on stripe request? Most API support this kind of key for safely retrying requests without accidentally performing the same operation twice. We were not in charge of the stripe integration but I found this after a quick search:
https://stripe.com/docs/api/idempotent_requests
Obviously you would need a unique ID as key for the idempotency key but perhaps you can use the payment id?

**Comment by jev-odoo** [comment]
@csnauwaert Hello,

As Antoine said, the example was given with Stripe, but as also said in the issue description, it will have the same behaviour with any of the actual and future payment acquirers.

**Comment by csnauwaert** [comment]
@AntoineVDV @jev-odoo I get what you're saying, but anyway, this doesn't seems to be the place to fix this kind of issue. You are changing entirely the behavior by choosing to arbitrarily don't reconcile entries in case of concurrent access update even if the customer does not use any payment acquirer. Also if we start having custom code everywhere we could get a concurrent access update because some module overwrite the method to call external API, we're not done with..
As a matter of fact, the way it is actually written in payment module probably needs some rethinking, we should probably commit after sending the call to an external API because a lot of things can happen after that and we need to know that we already sent the call. In this case we have a concurrent access update during reconciliation, but it could also be some error when trying to reconcile which would in turn rollback the entire transaction but that won't rollback the fact that we already sent the payment to the external provider. Another solution would be to work asynchronously entirely by creating a record that "needs to be sent to the provider" and let a cron sent those and then reconcile with the invoice (I saw that we already have some similar stuff in payment module) that way if the transaction is reverted, nothing is actually sent

IMO this fix is rather incomplete and while I'm not a huge fan of this solution you could probably do something like this:

In payment module, overwrite the `def _reconcile_payments(self, to_process, edit_mode=False)` which is in the `account/wizard/account_payment_register.py` file and wrap the entire super call within a try except Exception and in case of exception, if this is a concurrent access error, time.sleep a bit and call the method again (you can add a count in context to know how many times you retried so that it does not hang forever) and in case of any other exception (or too many retry for concurrent update) you should call the method to cancel sent payment to the provider (if any transaction linked to the payment) before reraising the error.
This solution only mitigates the problem and does not solves it entirely but I guess a correct solution needs to be done in master.

Note: I suppose that the concurrent error happen because someone else modified information on the invoices before we called the reconciliation method. Another way to avoid that would be to write some "state" or information on the invoice before sending the call to Stripe (or other API) that way we would lock the entry in database for us first.

**Comment by csnauwaert** [comment]
Closing to cleanup PR and as version is not supported anymore

**Pull request closed without merging**
