### PR TITLE
[FIX] l10n_cn_small_business: needs pos receivable account

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@lap-odoo @mart-e I just used Google Translate to translate pos in Chinese (damn, we could check the pos module), so maybe you can ping Jack on this?

**Comment by mart-e** [comment]
Technically ok but need to check the translation.
Maybe @jeffery9 can confirm this is ok?

**Comment by jco-odoo** [comment]
@JackSunI

**Comment by jco-odoo** [comment]
It is there in master somehow

**Pull request closed without merging**
