### PR TITLE
[IMP] purchase_requisition: Add archived in purchase agreement types

### PR DESCRIPTION
**Pull request by newtratip**
This pr is add archive button for hide the Purchase Agreement Types without removing it.
Peek 2021-05-25 16-44

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
@thomasdeleval

**Comment by amoyaux** [comment]
Hello, thanks for the suggestion. However it will only be possible for master if it's accepted

**Comment by thomasdeleval** [comment]
sounds ok to me

**Comment by amoyaux** [comment]
@newtratip could you re-target for master please

**Comment by newtratip** [comment]
@amoyaux 
ok, done in https://github.com/odoo/odoo/pull/71254

**Pull request closed without merging**
