### PR TITLE
[FIX] l10n_es_edi_tbai: in the newer versions of Ticketbai we can hav…

### PR DESCRIPTION
**Pull request by jco-odoo**
…e 8 decimals

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
testing

**Comment by jco-odoo** [comment]
@oco-odoo @Levizar Could someone review this today?

**Review by Levizar — APPROVED** [review]
@robodoo r+ rebase-ff

Discussed on discord: we can send it with 8 decimals, let's do it.

**Comment by Levizar** [comment]
@robodoo r-

**Comment by Levizar** [comment]
@robodoo r+

**Pull request closed without merging**
