### PR TITLE
[FIX] purchase: allow manual ref when selecting purchases

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
In V12 when you select a purchase order in vendor bill, the onchange add purchase ref after the existing ref (generally the bill number).

In V13 this behaviour have removed.

@qdp-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@qdp-odoo @nim-odoo 

This code doesn't work for this case:
- create 2 purchase with `REF A` and `REF B`
- create a new vendor bill, add manual ref 'INV A'
- select purchase A
--> ref is now INV A, REF A
- remove all lines
- select purchase B
--> ref is now INV A, REF A, REF B

Do you have an idea to solve this ?

**Comment by qdp-odoo** [comment]
> @qdp-odoo @nim-odoo
> 
> This code doesn't work for this case:
> 
> * create 2 purchase with `REF A` and `REF B`
> * create a new vendor bill, add manual ref 'INV A'
> * select purchase A
>   --> ref is now INV A, REF A
> * remove all lines
> * select purchase B
>   --> ref is now INV A, REF A, REF B
> 
> Do you have an idea to solve this ?

ref is editable so people can change it manually, that's good enough for me.

can you please squash your commits, Florent?

**Comment by fmdl** [comment]
@qdp-odoo done

**Comment by fmdl** [comment]
ping @qdp-odoo

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
