### PR TITLE
Update owl to v1.0.5

### PR DESCRIPTION
**Pull request by mcm-odoo**
This PR updates owl to its last version and fixes an issue in ComponentAdapter due to a change in this last version.

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by seb-odoo** [comment]
Any news on this owl update?

cc @alexkuhn

**Comment by aab-odoo** [comment]
@mcm-odoo Is it ready to be r+ed?

**Comment by aab-odoo** [comment]
robodoo r+ rebase-ff

**Pull request closed without merging**
