### PR TITLE
[CLA] signature for Pablocce

### PR DESCRIPTION
**Pull request by Pablocce**
This PR is created in order to sing the odoo CLA and contribute to Odoo.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
(needed for https://github.com/odoo/odoo/pull/167776)

**Comment by mart-e** [comment]
Hi,

Could you please rebase your PR and resolve the conflict?
Thanks

**Comment by Pablocce** [comment]
Done, thanks @mart-e

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
