### PR TITLE
[13.0][IMP] Product configurator should be made for lists

### PR DESCRIPTION
**Pull request by Daemo00**
The product configurator widget is only actually used in lists, does it make sense to let it extend from bare `FieldMany2One`?

**Description of the issue/feature this PR addresses**
Product configurator widget does not inherit specific behaviors from the widget `ListFieldMany2One`, so changes to `ListFieldMany2One` widget do not affect product configurator,
see for instance https://github.com/OCA/web/pull/1438#issuecomment-555636435.

**Current behavior before PR**
Overriding `ListFieldMany2One` widget does not affect product configurator widget.

**Desired behavior after PR is merged**
Overriding `ListFieldMany2One` widget does affect product configurator widget.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Feyensv GitHub says you were the one touching this. Can you please review?

Another side topic: why putting no_open in product_id in sale.order.line view?

**Comment by Feyensv** [comment]
@Daemo00 I do not see any problems on this change indeed.
Could you update your commits message according to our guidelines http://www.odoo.com/documentation/master/reference/guidelines.html#commit-message-structure ? Thanks :).

@pedrobaeza 
When a field has a defined widget, it is rendered even in readonly mode (which isn't the case by default for inline lists).  This means that by adding the product_configurator widget, the product_id field becomes clickable and redirects to the product form.  But this is a problem because when editing the Sales Order, you don't want to be redirected on the product form when you click on the product of a line (you want to edit this line, not to open the product form).  

Thus the no_open was added, and a little "hack" in the widget itself brings back the arrow (`fa-external-link` button) to access the product form, even if the field is `no_open`.

I'm not sure this explanation is clear :thinking:.

**Comment by pedrobaeza** [comment]
@Feyensv thanks for the explanation. I understand it more or less. Have you checked the referred OCA module? I think it's a good feedback for having it integrated on core.

@Daemo00 then maybe we need to take that into account in `web_tree_many2one_clickable` for enabling the button when having that button as well.

**Comment by Feyensv** [comment]
Indeed, I didn't take a look at the OCA module.

After consideration, if the many2one_clickable... extension you're doing replaces the generic clickable behavior (green text + on click opens the form view), you should be able to remove the no_open in the sales view, and to extend the product_configurator widget, disabling its _addProductLink (or I think two external links will be shown in line edit mode :D ).

**Comment by pedrobaeza** [comment]
Thanks for the tips!

@Daemo00 all yours then

**Comment by Daemo00** [comment]
Thanks @Feyensv for the prompt feedback!
I've edited the commit messages, I hope now they're ok.


> @Daemo00 all yours then

@pedrobaeza lucky me :stuck_out_tongue: 
Anyway I've read the conversation a few times but I'm not sure about which are the next steps..
Are we talking about editing the core modules in order to have the behavior of `web_tree_many2one_clickable` by default?
If I'm right, I would proceed to:
1. edit the ListFieldMany2one so that it behaves as if `web_tree_many2one_clickable` were installed
2. remove the no_open flag on `product_id` and `product_template_id` fields in the sale form view
3. check if the product configurator widget needs any fixing (like the one suggested in https://github.com/odoo/odoo/pull/40536#issuecomment-555974337)

But if this is not what you intended please stop me :)

**Comment by pedrobaeza** [comment]
Well, that can't be done on a stable version, but you can propose that improvement for master for sure if @Feyensv thinks that can be accepted.

I was talking about using the button trick with the `fa-external-link` class to be replaced for the clickable thing, but appearing only in edit mode, it won't work the same for the sales order tree in view mode. Other thing we can do is to ignore no_open command for this accelerator and present it always. Not the ideal thing either... Let's just annotate in the roadmap that this doesn't work for sales order tree and an explanation and it's good to go.

**Comment by Feyensv** [comment]
Two things to clarify:
* The current PR LGTM, it could be merged in master :+1: 
* What I wanted to say, is that if you want to make your widget work fine in the Sales Order View, you would need 2 things (but I don't expect to change Odoo codebase for it, unless it's a clean change without impact like this current PR):
  * A bridge module between your widget module and `sale`, removing the no_open and removing the custom `fa-external-link` added by the widget
  * Make your widget override the generic `web` behavior on many2one to replace the existing behavior of opening the record form view when clicking on the field, by your behavior of opening only when clicking on your custom `>>` button.  Otherwise, when removing the `no_open` on product_id / product_template_id, you would trigger the problem explained above (explaining why the `no_open` was necessary).

Functionally, I find it strange that your widget doesn't replace the generic behavior, as you would have a different behavior when clicking on the record and when clicking on the `>>` button.  But this is only a personal opinion ;).

**Comment by Daemo00** [comment]
Thanks for the clarification to everyone :) I've finally wound up by adding a line in the module's roadmap.

**Comment by Feyensv** [comment]
After more thoughts on this, I've a little problem with this change (I said it was fine earlier, but I didn't think enough about it).
In another work in progress PR, we are enabling the product configurator for mobile, which means that the widget has to be available for form views also :-/.  Thus we cannot inherit the ListFieldMany2One instead of the FieldMany2One.

**Pull request closed without merging**
