### PR TITLE
[FIX] fields: check if the inverse must change

### PR DESCRIPTION
**Pull request by jpp-odoo**
When adding a new record to a Many2one, after the record is created the
inverse is calculated and written.

Before this commit, the inverse is set to be modified in all the
elements of the Many2one, this means that, the “write” method is called
for other lines that the one that is added.

Now, the inverse is set to be modified only if it's different from the
current value.

opw-2091842

Co-authored-by: Raphaël Collet <rco@odoo.com>

### CODE REVIEW

**Comment by nim-odoo** [comment]
I'd say a test would be nice for framework issues

**Comment by nim-odoo** [comment]
add access rules to the model to avoid warning

**Comment by jpp-odoo** [comment]
robodoo r+

**Comment by jpp-odoo** [comment]
robodoo r+

**Pull request closed without merging**
