### PR TITLE
Master demovolution tde

### PR DESCRIPTION
**Pull request by tde-banana-odoo**

### CODE REVIEW

**Comment by mreficent** [comment]
What's about the funny .jpgs? :rofl:

**Comment by nhomar** [comment]
the world ask fo Vauxoo to come back as a data demo ;-) cc @fpodoo 

well not the world but me :-)

**Comment by Yenthe666** [comment]
Odoo Experts would love a spot too @nhomar 😉 
CC @ploegvde

**Comment by tde-banana-odoo** [comment]
You will have to bribe me. I have to warn you it will be costly.

**Comment by Yenthe666** [comment]
Correction: @ploegvde has to bribe you! How much do you like loads of bug reports about mail issues though? 😆

**Pull request closed without merging**
