### PR TITLE
[FIX] core: do not try to translate empty html attributes

### PR DESCRIPTION
**Pull request by KangOl**
Error revealed by 1fe4b0cc1981382cc3d944ec44276f0aee90945d

### CODE REVIEW

**Comment by KangOl** [comment]
It's related to the other commit, `html.fromstring("")` raise an exception `lxml.etree.ParserError: Document is empty`

It happened during the update of the view `event.view_event_form`

**Comment by KangOl** [comment]
`string=" "`
https://github.com/odoo/odoo/blob/b3a91899cd7e6772a241badfc0bd9699bb6e0e74/addons/event/views/event_views.xml#L242

**Review by rco-odoo — APPROVED** [review]

**Comment by rco-odoo** [comment]
FYI I improved the description of the issue in the commit message.

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
