### PR TITLE
Add an advanced options category including auto-reload.

### PR DESCRIPTION
**Pull request by NicolasWebDev**
So far there is no info about the "Advanced Options" category of the --help in the documentation.
Added only the --auto-reload within it, others can be added later.

### CODE REVIEW

**Comment by xmo-odoo** [comment]
* you need to [include a contributor license agreement](https://github.com/odoo/odoo/blob/8.0/doc/cla/sign-cla.md) to the proposal
* the section needs to be moved above the reference (at line 310), otherwise existing links to the configuration file section will now link to the "advanced options" section

**Comment by Sathors** [comment]
@xmo-odoo , thanks for the help, I didn't know about neither of these two.

**Comment by xmo-odoo** [comment]
Thanks for the contribution. I moved the bit as a subsection to the "server" command as that seemed more fitting.

**Comment by Sathors** [comment]
Thanks @xmo-odoo , just another question out of curiosity, when are the changes applied?

**Comment by xmo-odoo** [comment]
I know the documentation is rebuilt once a day from source, IIRC it's around 05:00 or 06:00 UTC.

**Pull request closed without merging**
