### PR TITLE
[IMP] *: add path shortcuts to useful actions

### PR DESCRIPTION
**Pull request by bouvyd**
Follow-up to c63d14a0485a553b74a8457aee158384e9ae6d3f for oft-used actions.

### CODE REVIEW

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by awa-odoo** [comment]
(love me some "shorctus")

**Comment by bouvyd** [comment]
@robodoo r+

**Comment by awa-odoo** [comment]
shorctuts is much better indeed!

**Comment by bouvyd** [comment]
🤦

**Comment by bouvyd** [comment]
@robodoo r+ yet again
[TABOURET - T A B O U R E T](https://www.youtube.com/watch?v=O-HjLSUuTc4)

**Pull request closed without merging**
