### PR TITLE
[FIX] Error message not concatenated properly in Payment methods

### PR DESCRIPTION
**Pull request by atchuthan**
Description of the issue/feature this PR addresses:
Error message not properly concatenated.

Current behavior before PR:
Odoo's error message is not shown in error pop-up

Desired behavior after PR is merged:
show error message in it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by atchuthan** [comment]
Odoo Ticket ID: 785951

**Comment by xmo-odoo** [comment]
This change is definitely invalid (only string literals in `_`), it should use string formatting rather than concatenation, and it also needs to fix up existing translations.

/cc @mart-e

**Comment by mart-e** [comment]
Indeed, please do not modify the error message

**Comment by mart-e** [comment]
Merged at f03437ae001

**Pull request closed without merging**
