### PR TITLE
[MERGE][FIX] knowledge: correctly handle members when moving / archiving / privatizing

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
PURPOSE

Fix flows involving moving articles (with or without parent) as well as setting
articles as private or archiving articles. Members are not always correctly
synchronized, detached or managed.

SPECIFICATIONS

1/ Fix move to private section

The issue can be reproduced by doing the following:
  * Create an article in the workspace section
  * Invite an internal user with write access (e.g: "Marc Demo")
  * Drag and drop it to the private section
  * Stack trace

Two separate issues:
  * the _check method in the article model should not be based on a SQL request
  * the move to an private section should check member integrity after all members
    are updated;

2/ Fix archive mechanism

The issue can be reproduced by doing the following:
  * login as "admin"
  * Create an article in the workspace section
  * Invite an external user on this main article (does not matter, e.g: Azure Interior)
  * Create a child article to this article
  * On this child article, set Marc Demo as permission "none"
  * login as "demo"
  * Archive the main article
  * login as "admin" again
  * The child article should be moved as root
  * The child article should have the invited external customer copied onto it

3/ Fix private propagation

The issue can be reproduced by doing the following:
  * Create an article in the workspace section
  * Create a child article to this article
  * Invite any user on this child article (does not matter, e.g: Marc Demo)
  * Move the main article to the private section
    -> The child article still has its internal permission set to "write"
       instead of inheriting from its parent ("No access")
    -> The child article should not have "Marc Demo" as member anymore

In addition, the same logic as the archiving on point 2 applies. If you don't
have access to a child article, it should NOT be moved to private (and instead
made root).

4/ Various fixes spotted when working on previous fixes

See commits of this PR for more details about fixes and code improvements.

Task-2859616 (members permissions management)
Task-2901990 (sorting)

Co-Authored-By: Aurélien Warnon <awa@odoo.com>

### CODE REVIEW

**Review by awa-odoo — COMMENTED** [review]
Bloups review :chicken: 

Don't forget to update commit messages when squashing.

Cheers!

**Review by dbeguin — COMMENTED** [review]
Here is my little contribution, many bisous and thanks for your work !
You are super colleagues !
xoxoxo

**Review by tde-banana-odoo — COMMENTED** [review]
Answers

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Pull request closed without merging**
