### PR TITLE
[FIX] mail: modify url redirection to doc (mail servers)

### PR DESCRIPTION
**Pull request by Abridbus**
Documentation structure was modified to point out to a new subtree:
    content/applications/general/email_communication/email_server

Related task:2619564
Documentation PR:1092

### CODE REVIEW

**Comment by seb-odoo** [comment]
cc @AntoineVDV

**Review by AntoineVDV — APPROVED** [review]
@robodoo delegate=Abridbus

Take care to update the version for each forward-port ;)

**Comment by william-andre** [comment]
> Take care to update the version for each forward-port ;)

Shouldn't there be an alias for a `<a/>` that points to the right version of the docs?

```xml
<documentation ref="applications/general/email_communication/email_servers.html"/>
```

**Comment by Abridbus** [comment]
> > Take care to update the version for each forward-port ;)
> 
> Shouldn't there be an alias for a `<a/>` that points to the right version of the docs? (removing the need for the `class`, `target`, `title`, and version)
> 
> ```
> <documentation ref="applications/general/email_communication/email_servers.html"/>
> ```

I'm not aware of something like that, neither did I find it in our codebase v14.
Feel like it would be an interesting feedback.

Maybe @AntoineVDV has a opinion on that :)

**Comment by seb-odoo** [comment]
That suggestion is currently under discussion (or already approved, at least on principle) in https://github.com/odoo/odoo/pull/84445

**Pull request closed without merging**
