### PR TITLE
[FIX] web_editor: Broken behaviour of options in media dialog.

### PR DESCRIPTION
**Pull request by ras-odoo**
Previously, options were not visible in the video tab of media dialog.

In this commit, we have changed classes names to fix the broken behavior
of options in the video tab of media dialog.

task-2154812

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo r+

thks for the fix

**Comment by JKE-be** [comment]
@robodoo r-

Can you rebase on 13.3 ?

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by jpr-odoo** [comment]
> @robodoo r-
> 
> Can you rebase on 13.3 ?

Okey, I will rebase with saas-13.3

**Comment by jpr-odoo** [comment]
> > @robodoo r-
> > Can you rebase on 13.3 ?
> 
> Okey, I will rebase with saas-13.3

@JKE-be I have rebased the branch with saas-13.3

**Comment by JKE-be** [comment]
Thanks it was already done ;)  https://github.com/odoo/odoo/compare/212676c5d918af7b3784213791f68145d08d818c..2cfe605c8394b3f33412aaa44c499d16df95be00

@robodoo r+

**Pull request closed without merging**
