### PR TITLE
[FIX] core: correct imports from `odoo.addons.base.maintenance.migrations`

### PR DESCRIPTION
**Pull request by KangOl**
This legacy package was supposed to be an alias to `odoo.upgrade`.
However, depending on how your import its sub-packages (and in which
order), we were ending with the module being loaded multiple times,
breaking the expectation of a singleton.

```python
In [1]: from odoo.addons.base.maintenance.migrations import util as m1

In [2]: import odoo.addons.base.maintenance.migrations.util as m2

In [3]: m1
Out[3]: <module 'odoo.upgrade.util' from '/Users/chs/devel/odoo/odoo/stable/odoo/addons/base/maintenance/migrations/util.py'>

In [4]: m2
Out[4]: <module 'odoo.addons.base.maintenance.migrations.util' from '/Users/chs/devel/odoo/odoo/stable/odoo/addons/base/maintenance/migrations/util.py'>

In [5]: from odoo.addons.base.maintenance.migrations import util as m3

In [6]: m3
Out[6]: <module 'odoo.addons.base.maintenance.migrations.util' from '/Users/chs/devel/odoo/odoo/stable/odoo/addons/base/maintenance/migrations/util.py'>

In [7]: m2 == m3
Out[7]: True

In [8]: m1 == m3
Out[8]: False

In [9]:
```

Now, with this import hook, we ensure that the modules imported from
`odoo.addons.base.maintenance.migrations` are aliases to ones imported
from `odoo.upgrade`.

```python
In [1]: import odoo.addons.base.maintenance.migrations.util as m2

In [2]: m2.__name__
Out[2]: 'odoo.upgrade.util'
```

### CODE REVIEW

**Comment by Julien00859** [comment]
Is

```py
    # create decrecated module alias from odoo.addons.base.maintenance.migrations to odoo.upgrade
    spec = importlib.machinery.ModuleSpec("odoo.addons.base.maintenance", None, is_package=True)
    maintenance_pkg = importlib.util.module_from_spec(spec)
    maintenance_pkg.migrations = upgrade
    sys.modules["odoo.addons.base.maintenance"] = maintenance_pkg
    sys.modules["odoo.addons.base.maintenance.migrations"] = upgrade
```

still needed ?

**Comment by KangOl** [comment]
> Is
> 
> ```python
>     # create decrecated module alias from odoo.addons.base.maintenance.migrations to odoo.upgrade
>     spec = importlib.machinery.ModuleSpec("odoo.addons.base.maintenance", None, is_package=True)
>     maintenance_pkg = importlib.util.module_from_spec(spec)
>     maintenance_pkg.migrations = upgrade
>     sys.modules["odoo.addons.base.maintenance"] = maintenance_pkg
>     sys.modules["odoo.addons.base.maintenance.migrations"] = upgrade
> ```
> 
> still needed ?

Yes, at least the `maintenance_pkg`. And prefill `sys.modules["odoo.addons.base.maintenance.migrations"]` is ok.

**Review by aj-fuentes — APPROVED** [review]

**Review by Julien00859 — APPROVED** [review]

**Comment by KangOl** [comment]
Can somebody of @odoo/rd-security validate this change?

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: requires sysadmin priviledge

**Comment by KangOl** [comment]
@robodoo r+

**Pull request closed without merging**
