### PR TITLE
pep8 cleanup for inter_company_rules module

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Comment by nim-odoo** [comment]
Hello,
Thanks for the PR. However, we don't accept purely cosmetic changes in a stable version: https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean
Regards

**Comment by sebastienbeau** [comment]
Hi I agree that we should not do cosmetic change on stable version, but the master is not a stable version. The stable version is the 8, what do you think?

**Comment by nim-odoo** [comment]
Whooops, my bad, I should have looked more closely. Anyway, there are a couple of PEP8 rules that we ignore: https://www.odoo.com/documentation/8.0/reference/guidelines.html#pep8-options
Amongst these rules, the rule "E501: line too long" is usually ignored. However, it seems that most of your changes are related to this rule.

**Comment by antonylesuisse** [comment]
Yes please avoid useless PR with only cosmetic changes (it's blame bloat). Only when we convert modules from the old to the new api we apply the new guidelines https://www.odoo.com/documentation/8.0/reference/guidelines.html

**Comment by sebastienbeau** [comment]
Note : this module do not exist in v8 but only in v9 and it already use the new api.... So we can clean it now or never. As you want, we just propose it because we are backporting in 8 and we want a clean version for our customer.

**Comment by antonylesuisse** [comment]
I think it's compliant with the guidelines. If you want to discuss the guidelines themselves please check https://github.com/odoo/odoo/pull/6342

**Pull request closed without merging**
