### PR TITLE
stock_change_product_qty : add hook to complete inventory line data

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
This hook allows some other modules to extend value to set on inventory line.

### CODE REVIEW

**Comment by sbidoul** [comment]
@odony @jco-odoo would you consider such a small refactoring, or perhaps a variant such as _prepare_something?

cc/ @gurneyalex @Cedric-Pigeon @rousseldenis

**Comment by odony** [comment]
@sbidoul if you change this into a refactoring that makes sense on its own (i.e. a properly designed _prepare method), then I would be ok to merge it. Although strictly speaking this is very much against the stable rules.

**Comment by jco-odoo** [comment]
Yes, indeed _prepare_inventory line with the dictionary constructed before
would make sense instead of updating with an empty dictionary.

**Comment by sbidoul** [comment]
The CCLA for Denis Roussel is in #12563 

:+1:

**Comment by Cedric-Pigeon** [comment]
:+1:

**Pull request closed without merging**
