### PR TITLE
[FIX] payment: correctly trigger the constraints

### PR DESCRIPTION
**Pull request by mart-e**
The third parameter expects a list of field, not some random string.
This made the constraints to be never checked for the fields with `required_if_provider` set.

cc @beledouxdenis @odony wondering if not too risky as it may prevent to modify (badly configured) acquirers when modifying something else on the record.

_edit: the fact that it is red with payment_sips is maybe an indicator of the problem_

### CODE REVIEW

**Comment by beledouxdenis** [comment]
As you say, this could break things that worked before.

Is this for a support ticket or a customer or an issue ?

**Comment by mart-e** [comment]
Nope, personal discovery during the review of another PR adding a `required_if_provider` field

**Comment by beledouxdenis** [comment]
I wouldn't take the chances then

**Comment by mart-e** [comment]
On the other, you acquirer is not going to work anyway if you don't have these fields set but can merge in master only to be sure.

**Comment by mart-e** [comment]
To be sure, merged in master, will backport if needed

43f619e [FIX] payment: correctly trigger the constraints
1cd356c [FIX] payment_sips: missing required value

**Pull request closed without merging**
