### PR TITLE
[FIX] stock: Avoid ambiguous colum reference error

### PR DESCRIPTION
**Pull request by pedrobaeza**
Current SQL, not being fully qualified, can lead to an error if you have any of the referenced columns also on product_product table.

For solving the problem, we are doing whole query fully qualified.

Alternative patch to #30307

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@amoyaux would you mind checking this that is failing on certain conditions exposed in the main comment?

**Comment by amoyaux** [comment]
@pedrobaeza I agree with the concept and I would add it in master. However we don't use the same field between product and quant in stable and it break due to a customisation. It goes against our stable policy so I would let @nim-odoo decide about it. Anyway if it's refuse I will do the patch for master.

**Comment by pedrobaeza** [comment]
Thanks for the review, @amoyaux. I know that this is not impacting directly on core, but it's a bug as it opens a door in Odoo to fail under certain third party modules, and the guilty is not that third party module, but this code, so this should be qualified as bug fixing. If you check the code, it's only doing that, and tests assure its correctness.

Please reconsider it.

P.S.: For master, I would go for a `read_group` call instead of this plain SQL query. I can do the PR if you want.

**Comment by nim-odoo** [comment]
I agree with @amoyaux . This query was added back in 2013 in 99234f4cb3ae54a570c137468f5308429d4bd6f4. It doesn't cause any issue in Odoo standard, therefore to me it falls under a refactoring and not a fix. As you mention, it only causes a problem in cases of name collisions with third-party modules. [1]

Of course that would totally make sense to solve it for master.

[1] In another life and another software, any third-party module field was prefixed with a specific letter (similar to the `x_`). I am still convinced this is the way to go for any third-party module that would extend an existing object model, whatever the software.

**Comment by pedrobaeza** [comment]
Sorry to insist in this, but denying this fix will provoke incompatible third party modules that are not aware that adding a column in `product.product` model with the same name as another in model `stock.quant` will collapse inventory adjustment feature.

The facts are:

* This is happening because the ORM is being bypassed. With ORM, this problem wouldn't exist (as it generates fully qualified SQLs under the hook).
* Odoo framework doesn't prevent to extend models with whatever field name you want.
* I'm not changing the SQL, just fully-qualifying it.

Please reconsider this.

**Comment by pedrobaeza** [comment]
@nim-odoo @amoyaux please reconsider this.

**Comment by jpp-odoo** [comment]
Closed by https://github.com/odoo/odoo/pull/34427

**Pull request closed without merging**
