### PR TITLE
Add typography and button theme options

### PR DESCRIPTION
**Pull request by qsm-odoo**

### CODE REVIEW

**Comment by stefanorigano** [comment]
@qsm-odoo , some questions:

1] I see that the `px` value in the **_Options_** tab directly affects the `border-radius` for the default button size only; the system will automatically compute the values for `btn-sm` & `btn-lg` (make sense 👍).
I'm wondering how this will match theme's customisations, eg:

In theme X we set `$btn-border-radius-lg: 40px;` (we keep small & medium default).
The user change the option value in the sidebar, what will be the new value for **`btn-lg`**? 

- Scenario 1: the value will become the **computed** one. A minor difference (eg. from 4px to 5px), will cause an huge difference for btn-lg that from 40px (theme's default) will become ~8px (computed value). Depending by the implementation, setting back the value to 4px may not "restore" the original theme value, because it will be a new computed one, eg. ~6px. The original theme value will be lost forever (?).
- Scenario 2: the value is still the **theme** one. The user will not see any difference on the big buttons. Not critical, but not ideal neither IMO.  btn-lg may be widely used in a website (landing pages. product pages, CTAs).. the user should be able to customize these design elements, especially if there is already an option to change the medium-size one.

I got your point about simplify the UI, but maybe we should find another solution?

2] What about the "correlations" with inputs? I just finished migrate odoo.sh to BTS4 and we had a lot of issues caused by discrepancies in border-radius, line-height, padding(...) between btns & inputs... should we act on the general `$border-radius` variable instead?

3] In terms of UI; when these options will be in the sidebar,  it would be possible to add a link pointing the the btn's value in the **_Options_** tab?

**Comment by Cocographique** [comment]
@qsm-odoo 

I know you didn't request my opinion on that but I don't understand why to promote the outline style over any other style? 

Also, I don't see the point to have a border-radius value input on one side and a shape selector on the other side. Personally, I prefer pre-made choices for the user. Why is it useful to be able to choose between 7px or 8px ? You can indeed have rounded buttons but without the proper padding the result is ugly.

We should not act on the general $border-radius variable. It's not because you want rounded buttons that you also want rounded text inputs.

**Comment by stefanorigano** [comment]
>We should not act on the general $border-radius variable. It's not because you want rounded buttons that you also want rounded text inputs.

How you'll deal with input-groups? forcing which value? the button or the input one?
It would be inconsistent having inputs/buttons with different border radius depending if they are inside an input-group or not.
Screenshot 2020-04-21 at 15 57 52
It's more likely than you want to use the same value for both, rather than the opposite.
Fo more complex needs there is still the editor IMO.

**Comment by Cocographique** [comment]
If the global $border-radius variable is used, here is some examples of what will happens.
Quite confusing for a button radius option, no?

Screenshot 2020-04-21 at 16 38 05

Screenshot 2020-04-21 at 16 47 00

Screenshot 2020-04-21 at 16 41 26

**Comment by qsm-odoo** [comment]
Wow, yet another debate about this ^^ cc @sbuhl

> In theme X we set `$btn-border-radius-lg: 40px;` (we keep small & medium default). I got your point about simplify the UI, but maybe we should find another solution?

There is no problem here, the theme is still free to adapt the `$btn-border-radius-lg` variable as it wishes. It just have to considerer the value `o-website-value('btn-border-radius')` in its expression. I'll see if this case occurs a lot when working on themes tomorrow. For your case, I guess I can just do `40 / defaultMDValue * userValueForMD`. Emptying the input of the left panel is supposed to go back to the theme value (may be broken recently, I have to check, but this will be the behavior).

> 2] What about the "correlations" with inputs? I just finished migrate odoo.sh to BTS4 and we had a lot of issues caused by discrepancies in border-radius, line-height, padding(...) between btns & inputs... should we act on the general `$border-radius` variable instead?

As proven by @Cocographique, no. I considerered it but no ;) We can always give the control on the input radius or whatever other radius in the future. As a first step, being able to control the button radius independtly is... a first step. This is something you would want on its own: controlling the button radius and nothing else (this is why the bootstrap variable exists). If we want to implement a "master" radius in the future, we can do it... but we would not remove the possibility to control the radius of buttons independently :wink:

> 3] In terms of UI; when these options will be in the sidebar, it would be possible to add a link pointing the the btn's value in the **_Options_** tab?

Yes, Thanh is developing that.

> I know you didn't request my opinion on that but I don't understand why to promote the outline style over any other style?

@Cocographique I always want your opinion. I only asked SRI because we disagreed a lot about all this weeks ago and I wanted to have his opinion as I was happy I though I found a compromise between our two visions. I was against promoting the outline option over any other style at first. In the mean time, I checked many websites (and wix, squarespace, etc) and I saw a outline/fill mix way more often than the rounded/square mix. So it convinced me. The other points was the outline/fill variants will be both customized by color presets while rounded will not. SRI wanted to remove all the styles but outline, I slightly compromised by keeping them in an "alternate" style area.

Anyways, @sbuhl is considering removing them all (outline + rounded + flat), so... ^^

> Also, I don't see the point to have a border-radius value input on one side and a shape selector on the other side.

I don't understand, so in fact you are against the ability to control the option at the theme level / you want to remove all the shapes as SBU? Strange I thought you were the only one agreeing with me that it was necessary weeks ago :/

> Personally, I prefer pre-made choices for the user. Why is it useful to be able to choose between 7px or 8px ? You can indeed have rounded buttons but without the proper padding the result is ugly.

Agreed for the padding linked to radius. I thought we would control the padding in the future, so again: this was a first step. I try to sleep at nights, so I cannot do everything at once :wink: For the ability to choose the value exactly, this was the direction we took when introducing inputs in the editor. I think SRI agrees with you here so maybe it would be good to have everyone on the same page with what FP wants here, @sbuhl?

I won't fight any future idea @sbuhl, I am tired coming up as the bad guy just trying to find solutions :fearful: I'll implement without asking. To me, any choice is an improvement of what we have now and the final choice is a detail. So:
- What happens to outline option per button?
- What happens to shape option per button?
- What happens to outline option per button type (theme level)?
- What happens to radius sm/md/lg option (theme level)?
- Should we replace the border radius input by a select with presets controlling both the radius and and the padding (see the circle option on buttons: when you choose it, the padding increases so it looks good).

**Comment by Cocographique** [comment]
**It looks like a "tartine" but it's not. Just a lot of quotes.**
 
> I was against promoting the outline option over any other style at first.

And I'm against too. Buttons are rounded on the Invision website, the Adobe website, the Apple website, the Spotify website... But this not a reason for this style to prevail on another one.

> The outline/fill variants will be both customized by color presets while rounded will not.

Sorry, I don't understand why you can't apply a color to it. For me, it's just a fill button with enough border-radius. No need to waste your time now explain me why. Maybe I will understand it when using the new color system.

> Anyways, @sbuhl is considering removing them all (outline + rounded + flat), so... ^^

😭Aled... 

> I don't understand, so in fact you are against the ability to control the option at the theme level / you want to remove all the shapes as SBU? Strange I thought you were the only one agreeing with me that it was necessary weeks ago :/

No. I still agree with you. What I wanted to say is: either it's 2 shapes selectors, either it's 2 inputs (one at the button level, one at the theme level). But not both.

> Agreed for the padding linked to radius. I thought we would control the padding in the future.

So maybe, it could influence the decision about which system to use: shapes selectors or inputs. 🤔 

> I won't fight any future idea, I am tired coming up as the bad guy just trying to find solutions. 
I'll implement without asking.

Honestly, you should not. I'm sorry you feel that way. Your input is very valuable.
I don't want to feed endless debates to convince you to promote what I want to make me happy...
but wait... it is what I'm doing here? 🙃 

At least, you all have my POV on this. Hope, it helps.

See you in another debate 🤦

**Comment by qsm-odoo** [comment]
> **It looks like a "tartine" but it's not. Just a lot of quotes.**

You should sleep at nights :')

> And I'm against too. Buttons are rounded on the Invision website, the Adobe website, the Apple website, the Spotify website... But this not a reason for this style to prevail on another one.

Yes, at the theme level. Not button by button. Hence still providing the possibility button by button but not encouraring it.


> > The outline/fill variants will be both customized by color presets while rounded will not.
> 
> Sorry, I don't understand why you can't apply a color to it.

There is no point changing the color of a button in a specific context because it is rounded. The necessity was there for outline because they do not contrast well because they are outline. But maybe we give that up anyway I don't remember.

> What I wanted to say is: either it's 2 shapes selectors, either it's 2 inputs (one at the button level, one at the theme level). But not both.

The point was to have full control at the theme-level but still be able to use full-circle and full-square button case by case. But maybe you are right, just depends what kind of people we target. For my website, I would want full control. For a website builder targeting everybody, I don't know, maybe square/rounded/circle choices is enough... but then why giving full control over card and column border-radius :/

> So maybe, it could influence the decision about which system to use: shapes selectors or inputs. thinking

Not at all to me, the only point is "full control or not?" = "targeting who?". Could influence @sbuhl's decision though: would you rather have this PR + an input controlling the padding in the future or a single select controlling both?

> I don't want to feed endless debates to convince you to promote what I want in order to make me happy... but wait... is it what I'm doing here? upside_down_face

Not at all, my comment was again not targeting anybody. It was meant to say that, for this specific debate, everybody disagrees and I have given my opinion several times in details and I will now stop fighting for it, I just want this done and merged :wink: Again, any decision will be a good one to me here as long as "giving some kind of control over outline/rounded at theme level" (select or input) remains.

**Comment by stefanorigano** [comment]
Hey, I had 3 questions, no intention to debate ;)

1] **Conflicts with theme's settings**
>There is no problem here [...]It just have to considerer the value o-website-value('btn-border-radius') in its expression. [...]For your case, I guess I can just do 40 / defaultMDValue * userValueForMD.

Cool, thanks 👍 . It leads to another question. For simplicity and consistency (we never use these expressions to define theme's settings) do you think that it would be possible to "invert the equation" and let the editor taking in account potential theme value? 
eg. ` [eventual theme value or default] / defaultMDValue * userValueForMD` or whatever ?

2] **Discrepancies between inputs and buttons (input-groups)**
> As proven by @Cocographique, no. I considerered it but no ;) [...]

Sorry, but it doesn't answer my question. I think you were focused on my raw suggestion (more on that later), rather than on the question itself 😋:  how do we handle `input-groups` discrepancies? We don't care/we'll see later are options too ;)

3] **Links between UI tabs** > 👍 cool, thanks!

---
### The inglorious "generic border radius proposal" (part 7, act 19 🤣) 
The idea was simply to use the same border radius since elements share the same context (eg. btn-groups) and avoid issues (question2).
We could limit this value (eg. 1rem max) or provide predefined choose (eg. tiny, medium...).
For extreme "border-radius needs" (eg. what @Cocographique posted in his examples) I thought you wanted to use specific classes to be applied on specific btns (rounded-pill, rounded-circle..), am I wrong? That said, I'm not "emotional attached" to this proposal, and there is not need to comment it... I want just to clarify my proposal to solve question 2, but any other solutions for me it's ok.

---
Some considerations:

>SRI wanted to remove all the styles but outline, I slightly compromised by keeping them in an "alternate" style area.

Just to be clear, I love buttons' styles 😊. I'd like to get crazy providing @sbuhl 200 custom btns style. The issue with outline is only related to the color-system only, and this lead to my next consideration.

> Maybe I will understand it when using the new color system -> But this not a reason for this style to prevail on another one.

@Cocographique , it's has been months that you have to try it. We invited you to meetings, tasks... you have the branches, what are we waiting for to be everyone on the same page?
Half of the stuffs qsm did in in this PR are to "save" your themes design when will be ported to the new color-system.. qsm had to fight me for these changes..
I didn't wanted compromise, do a fresh start and improve themes later but I agree that he was right on preserve as much as possible the current themes design... 
The paradox is that now me and qsm have to defend these choices against you? Because you didn't check it yet?
Could you please **check and test deeply** the new color-system **please**????

**Comment by qsm-odoo** [comment]
> do you think that it would be possible to "invert the equation" and let the editor taking in account potential theme value?
> eg. ` [eventual theme value or default] / defaultMDValue * userValueForMD` or whatever ?

Yes, of course, that is what I will basically be doing for font-sizes as well, I can already do it here. Just need to be sure of the specs first ;) With still the possibility for a theme to come with its own equation if it does not like the standard one.

> the question itself yum: how do we handle `input-groups` discrepancies? We don't care/we'll see later are options too ;) _*edit: but these options will lead to a real debate, QuakeArena is ok for you ? rofl_

Basically, Bootstrap is broken about input-groups (just try to change a unique variable about padding and see the result) :worried: And you know why? Because they use `calc` :1st_place_medal: You are right about the problem, but again as a first step, I will just have to adapt the input group variables accordingly so that it is not broken. Or maybe that @sbuhl will decide to have a select with presets about everything (button radius + padding + effect on input-group + etc), which would not be a bad solution, just a solution with less control for the user (which I repeat is good to me too). Actually the best for **me using the builder** would be to have presets in a select whose individual parts (padding, radius, etc) would still be in the UI with inputs as well (but I get why we won't do that)... (altough this is what we did for alerts: you choose the "type", which is a preset of icon and color, but then you can still change the color and icon individually).

___

Peace everyone :worried: Everyone is busy trying to improve the website, I am sure we'll come up with something good whatever the choices we make :+1:

**Comment by stefanorigano** [comment]
1] theme's conflicts
> Yes, of course, that is what I will basically be doing for font-sizes as well [...]

Ok, thanks 👍

2] input groups
So we'll see later according to new @sbuhl  specs, ok.

---
Notes:
> Actually the best for me using the builder would be to have presets in a select whose individual parts [...]

I agree. IMO we should avoid to create an UI for coders or "people that already know which variable to tickle to get a specific effect". These people can use the SCSS editor, it's the reason why we provide this tool.

Eg. a dropdown "Website spacing: [`tiny, medium,large`]" that will affect $spacer, line-height, padding... for me is a good option rather than provide granular edition on any of these values (or just some of them). Then, we can still replace this dropdown with real input fields on `?debug`,  or do some other black magic.

---

Super-peace 🤗❤️
I didn't wanted to sound like a jerk... I'm not criticising, I'm actually **begging** to join and share opinions, since a while.

**Comment by Cocographique** [comment]
> @Cocographique , it's has been months that you have to try it. 

Just for the record, I did it. Not in details, indeed. Because I have my own tasks to work on too, and I was told to wait for the new color system to be ready before starting to work with it.
Maybe, I'm not looking at the right place. Usually, I use this branch: master-new-bg-color-system-qsm. 
I had another look this morning. When I played with buttons styles and colors, it seems fine. I probably missed something. 
Anyway, I won't interfere anymore. I am sure you'll come up with something good.

**Comment by stefanorigano** [comment]
@Cocographique , nobody accused you to "interfere", you can't say that 🤦‍♂️.

We invited you in physical meetings, tasks... we sent emails but you never bored neither to **reply**.
We discussed personally about this multiple times, you know that... so please don't talk about "interference", it doesn't help.

You have been busy, ok... but it's not the first time that you said "_I don't know **X** but we should do **Y**_" or "_I don't know **Y** but I decided to to **Z** anyway_".

For me it's frustrating because I know that there are flaws in the system and your contribute would be valuable, **especially because when merged this stuff will impact everything your are doing at the moment**.

As qsm said your opinion is always welcome... I will add  that's actually **needed**.

As a sign of peace,  each morning I'll post a gif of lovely bears in this tormented PR (sorry @qsm-odoo ). The only way to stop me is to confess that you love me too.

tenor

**Comment by qsm-odoo** [comment]
I love you both
...
...
...
~~(would that be enough to stop the bears?)~~

**Comment by Cocographique** [comment]
> nobody accused you to "interfere", you can't say that.

This is not what I said.

> We invited you in physical meetings, tasks... we sent emails but you never bored neither to **reply**.
> We discussed personally about this multiple times, you know that... so please don't talk about "interference", it doesn't help.
> 
> You have been busy, ok... but it's not the first time that you said "_I don't know **X** but we should do **Y**_" or "_I don't know **Y** but I decided to to **Z** anyway_".
> 

I do not agree but this is not the place to discuss about that.

**Comment by qsm-odoo** [comment]
Most commits of this PR were merged a while ago, remaining work will be done at https://github.com/odoo/odoo/pull/52332

**Pull request closed without merging**
