### PR TITLE
[FIX] stock_account: total quantity can be zero

### PR DESCRIPTION
**Pull request by backspac**
Follow-up of https://github.com/odoo/odoo/pull/64942

Explanation:
When computing the total quantity, summing negative and positive values
can sometimes lead to zero even if the scoped quantity is not zero.
E.g.: Warehouse 1 has 10 items and Warehouse 2 has -10 items.
Scoping on Warehouse 1 results in 10 items but the total quantity is 0.

This commit also takes into account float precision.
Inspired by:
https://github.com/odoo/odoo/blob/d9b409247303c6b165a7df381169f2480a19900f/addons/stock_account/models/stock_quant.py#L36-L38

### CODE REVIEW

**Comment by backspac** [comment]
Ping @agr-odoo

**Comment by agr-odoo** [comment]
Ok, the inverted condition is not as easy to read, maybe a comment on why you did that would be nice for future refactoring
@robodoo delegate +

**Comment by agr-odoo** [comment]
@robodoo delegate+

**Comment by backspac** [comment]
@robodoo r+

**Pull request closed without merging**
