### PR TITLE
[FIX] server: always consume wakeup bytes from signals

### PR DESCRIPTION
**Pull request by odony**
Due to the implementation of [PEP-475]( https://www.python.org/dev/peps/pep-0475) in Python 3.5, revision e98e8e9b1bdf8c3a3bcf74b7648b0829c21d356a used the recommended technique of wakeup file descriptors in order to detect interruption of sleep() and select() by signals, when running in multi-process mode (workers > 0).

The technique works well, however the initial patch never bothered to read the byte that is written to the wakeup pipe when a signal is processed. This does not matter when the signal is meant to shut down
the server, but it matters when the signal is SIGQUIT: it simply prints thread dumps, and continues operating normally. As a consequence, that byte remains in the wakeup pipe forever, causing
all the subsequent select/sleep calls to return immediately because the wakeup fd *is* already ready. The symptom was that worker processes would start cycling their main run loop very fast after receiving a SIGQUIT signal, eating 100% CPU.

This patch ensures we always empty the wakeup pipe after an interruptible call, to avoid this effect. It also refactors another occurrence of the "empty pipe" pattern, in the PreforkServer, and incidentally uses more readable aliases for the file descriptors bound to the ends of the wakeup pipe (wakeup_fd_r / wakeup_fd_w).

### CODE REVIEW

**Comment by odony** [comment]
@nseinlet @tbe-odoo FYI ;-)

**Comment by KangOl** [comment]
@robodoo r+

**Comment by KangOl** [comment]
@robodoo r-

**Comment by KangOl** [comment]
@robodoo r+

**Pull request closed without merging**
