### PR TITLE
[FIX] l10n_*: no spaces in xml_ids checks #38139

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:
fix no spaces in xml ids
Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@xmo-odoo @mart-e If you would be so friendly to review/merge this, so you could be forgiven to forget about spaces in localizations?

**Comment by mart-e** [comment]
Please change your commit message to explain why this is needed

**Comment by jco-odoo** [comment]
@mart-e for translations?

**Comment by xmo-odoo** [comment]
@mart-e because of #38139 which is mentioned in the commit message (though not in the PR body so it's a bit unclear).

**Comment by mart-e** [comment]
@jco-odoo your commit message is "[FIX] l10n_*: no spaces in xml_ids checks #38139" which does not really explain what is the issue (by the way, making reference in enterprise to community PRs should be prefixed with `odoo/odoo#`).

As explained on the [commit message guidelines](https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure), just reading the commit should be enough to understand the issue. Something like:

```
[FIX] l10n_*: remove spaces in external ids

Since commit <insert hash commit>, the external ids can no longer have a space it the name.
This commit adapt the remaining ones in localization modules.
```

**Comment by jco-odoo** [comment]
@oco-odoo @william-andre Could one of you make sure this thing gets merged? I oversaw this.  (there is an enterprise part somewhere too)  It should solve the red nightly.

**Comment by mreficent** [comment]
@jco-odoo there are conflicts due to https://github.com/odoo/odoo/commit/2bc4dccfdd3cb6b07345e0082dac4eb8987bcf63 commit done by @Xavier-Do

**Comment by Xavier-Do** [comment]
Did the same fix in #39663, #39664 and odoo/enterprise#6525

**Pull request closed without merging**
