### PR TITLE
[REVERT] account: 0% tax not in tax report due

### PR DESCRIPTION
**Pull request by smetl**
This reverts commit 65b5ec4ad65f798b1d647978b5b42a49e760139a.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by oco-odoo** [comment]
@robodoo r+

**Comment by oco-odoo** [comment]
Reverted for usability reasons, after discussion with al and fp.

**Comment by chadt63** [comment]
Due to reverting the original commit, the original problem is now an issue in my v15.0 database. Invoice lines with 0% tax rates are still required to be reported to taxing authorities in some US states. It's now impossible to generate an accurate tax report, accounting for all sales (including the 0% tax sales). Is there a new way to solve this issue now that the original fix was removed? What is the use case for a 0% tax rate if it doesn't appear on the tax report?

**Comment by smetl** [comment]
@chadt63 This is supposed to be handled by https://github.com/odoo/enterprise/pull/28887 . However, nobody merged it during my vacation.

**Pull request closed without merging**
