### PR TITLE
[FIX] ir.attachment: Catch & Release the cursor on every GC cycle

### PR DESCRIPTION
**Pull request by hbto**
Main
-

Catch the cursor for the vacuum process and then release it on every cleaning
process.

Explanation
-

And yes :X There are cases where a Garbage Collection is to be done on a huge
amount of files. And while doing so other services/cron jobs could be hit by
this GC process and could get stuck with a with a locked transaction. One
example of this process is fetchmail.

In the Next Graph we can see a real case scenario of DB Locks because of the GC. While cycling through thousands of records other transactions got stucked waiting for the GC to be finished. After the GC finished/got killed then the remaining locked transactions were able to perform their job.

Screen Shot 2022-01-17 at 23 53 28

By playing Catch & Release cursor approach. GC on File-system attachments plays
nicer with other transactions. When catching and locking on the cursor it tries
to hold on it if possible. But instead on holding tight to it for whole process
of GC'ing it releases the cursor on every successful GC'ing. Allowing another
process to Insert, Update or Delete attachments records while it waits 10s for
the next window to be open and begin again.

If GC fails to catch on the cursor then it nicely fails by breaking the process
of cleaning and properly logging what was done.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hbto** [comment]
ping @odoo/rd-security

**Comment by hbto** [comment]
Hello @odoo/rd-security any news regarding this PR?

Regards.

**Comment by odony** [comment]
I've seen the GC run on dozens of thousands of files (because it was blocked and never ran for a while), and it never takes more than a few seconds. Even with the filestore on a reasonably fast network filesystem.

Have you tried breaking down the reasons for the slowness? It seems it would be beneficial for all operations if the root cause was found and fixed.

For example:
- how many files to GC are we talking about here?
- how long does it take to run a single loop of GC (up to 1000 unlinks)?
- what sort of filesystem is this? what is the network latency, if it's a networked FS?

Even with a slow network filesystem with 10ms latency (ouch!), you could unlink 1000 files in 10s, so you'd need 360k files to reach 1 hour of GC (assuming linear time). And that's with both an enormous list of attachments and a worryingly slow FS. Either are significant risks for a deployment, and will definitely cause other issues. :thinking:

**Comment by hbto** [comment]
Hello @odony 

Thanks for your thorough reply:

I will try to provide the best of mine to give you an explanation.

> I've seen the GC run on dozens of thousands of files (because it was blocked and never ran for a while), and it never takes more than a few seconds. Even with the filestore on a reasonably fast network filesystem.
> 

This is the case of a GC that got disable because after several times it became to expensive to run a for that reason it was disable.

Having past several most from its disabling We became aware of it because of the exponencial grow in Size both in DB and FS.

In testing Instance we have tried to run but it took more that 6 hours to run (no other Schedule actions running).
To which we resolved to check how the power_on() method was made of.

On checking it we realized that the GC for the transient model was a big hit too. it took 4 hours to complete a full cycle.
And though for each model there is a commit, there is no commit when deleting the records in the table, let us say there 5k records to be deleted in mail.compose.message the GC method commands to delete the whole thing in a single shot. I think there is room for improvement at this point. I would be better to delete the records in small chunks.

The same applies for the GC in mail.thread (outside of the transient) there attachments records in the DB are asked to be deleted, but because the ir.attachment records need to be deleted need several validations to be complied it takes too long to delete several records leading to several locks in the DBs.

> Have you tried breaking down the reasons for the slowness? It seems it would be beneficial for all operations if the root cause was found and fixed.
> 
> For example:
> 
>     * how many files to GC are we talking about here?

of 3Millions records in the FS, about 600K were set to be deleted

>     * how long does it take to run a single loop of GC (up to 1000 unlinks)?
for the GC on FS it only takes no more than 3 secs

> 
>     * what sort of filesystem is this? what is the network latency, if it's a networked FS?
>
BTRS
> 
> Even with a slow network filesystem with 10ms latency (ouch!), you could unlink 1000 files in 10s, so you'd need 360k files to reach 1 hour of GC (assuming linear time). And that's with both an enormous list of attachments and a worryingly slow FS. Either are significant risks for a deployment, and will definitely cause other issues. 🤔

That is the issue there are more than 600k to be deleted

Regarding this PR the timeout from my point of view could be of no need as the GC is a must have, it hasn't to be that touchy when not able to grab the lock, I think that it must wait as much as it has to perform the GC (in the case of the FS) I didn't want to take it away in this PR. Because at the end of the day it is a task that can wait while others are working.

On our side what we have come out to solve our issue has been dividing all the pieces and executing them one by one.
Making commits wherever possible. After all this actions are meant to be done. and not snap back in case of failure.
Even as a fail safe we have come out with the idea of including kill_switches that allow DevOps people to kill one of the process, that is killing a scheduled actions that we now is taking too long.

An exhibit on how the power_on() method was divided:

Screen Shot 2022-01-24 at 14 26 06


An exibit of the code that is playing better with other processes:

```
date_until = datetime.datetime.now() - datetime.timedelta(days=1)
domain = [
  ('res_model', '=', 'mail.compose.message'),
  ('res_id', '=', 0),
  ('create_date', '<', date_until),
  ('write_date', '<', date_until)
]
log('Begun')
while True:
  ######################################################
  if kill_switch():
    break
  ######################################################
  records = env['ir.attachment'].sudo().search(domain, limit=LIMIT, order='create_date')
  
  if not records:
    break
  
  try:
    records.unlink()
    env.cr.commit()
  except Exception as e:
    env.cr.rollback()

log('Finished')


```

Conclusion: this is a issue of several edges. each one with room for improvement.


Hope this could provide an insightful view of the problem.

Regards.

**Comment by hbto** [comment]
PD:

Now everything runs under ten minutes. Though not using the original power_on() schedule actions because it does not do commits on all the process. We don't want to risk again to reach this point.

Regards.

**Comment by C3POdoo** [comment]
Dear @hbto,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
