### PR TITLE
[IMP] sale_project: hide SOL field

### PR DESCRIPTION
**Pull request by kcv-odoo**
Before this commit SOL field on task visible when user no sale access and field is set but SOL field is readonly when user has no sale access there is not point showing readonly empty field.

This commit hide SOL field when user has no sale access and field is not set.

task-3186438

### CODE REVIEW

**Review by pkyriakou — COMMENTED** [review]
Thank you for your work Kartik :muscle: 
LGTM :100:

**Review by pkyriakou — COMMENTED** [review]
Thank you for the changes, LGTM :100:

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work. 🙂 

robodoo r+

**Comment by xavierbol** [comment]
oh it seems you have a conflict. 😢 

Can you resolve it when you have time? Thanks in advance! 🙂

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work. 🙂 

robodoo r+

**Comment by xavierbol** [comment]
Hum, the runbot does not want, we merge your fix. 🤔 😢

**Comment by kcv-odoo** [comment]
Runbot is happy now :star_struck:

**Comment by xavierbol** [comment]
Youhou 🤩

**Comment by xavierbol** [comment]
robodoo r+

**Pull request closed without merging**
