### PR TITLE
[IMP] various: update query counters

### PR DESCRIPTION
**Pull request by tde-banana-odoo**

### CODE REVIEW

**Comment by Yenthe666** [comment]
Serious question, what's up with those? 🤔

**Comment by tde-banana-odoo** [comment]
Not sure to understand question; here I just update them as sometimes we have ORM / framework optimizations that allow to gain a few queries and counters are not always updated. We also have counters higher than expected due to some randomness that sometimes we achieve to remove. Doing some maintenance allow to post future changes worsening counters.

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
@tde-banana-odoo so are they used to check if some functions/calls execute the expected amount of queries or? I never saw the purpose of this but maybe I miss something stupid 😄

**Comment by tde-banana-odoo** [comment]
Purpose (in stable) is more to raise when we add queries. Like "improving a feature" or "adding a small fix" that breaks counters. It is also used when trying to optimize something. For example it was used to see effect on payroll flow when it was optimized. Sometimes you think you optimize a counter but actually due to cache / prefetching / something else it actually has no effect on queries.

**Comment by Yenthe666** [comment]
Ahh I see! Thanks a lot for explaining it

**Pull request closed without merging**
