### PR TITLE
[FIX] Balanced currency amount in accounting

### PR DESCRIPTION
**Pull request by ghost**
- Take in account a currency amount when checking whether
  journal entry is balanced or not.
  
  Changes to be committed:
  
    modified:   account/account.py

### CODE REVIEW

**Comment by tvibliani** [comment]
In multicurrency setting, in accounting, it's very common error to fill in correctly amount in company currency, while entering unbalanced amount of foreign currency (even some automatically generated Journal Entries are unbalanced in part of currency amount), but for now, Journal Entry is considered as balanced anyway. this patch is fix for this error and Journal entry is considered as balanced only when both, company amount and currency amount are balanced and filled in correctly.

**Comment by mart-e** [comment]
Hello,

You patch breaks [runbot tests](http://runbot6.odoo.com/runbot/static/build/40559-4749-76275d/logs/job_20_test_all.txt), check `case2_usd_eur_debtor_in_eur.yml`

**Comment by tvibliani** [comment]
selection_007

**Comment by tvibliani** [comment]
Hello,

I referred to case2_usd_eur_debtor_in_eur.yml as you suggested. I reproduced error locally and I've got Journal Entry generated by the failed test case, that you can see in above picture, posted by me.

**The reason why test fails to pass:**
after applying my patch, as you can see, status of this journal entry is considered as "Unbalanced" (see "Status" column in the picture above). So it can't be posted (Because it's unbalanced) and it's the reason of failure of this test case.

**And how the test were passed before applying my patch:**
simply status of Journal Entry above were "Balanced" (with all the same numbers in "Debit", "Credit" and "Amount Currency" columns, as my patch changes only the status) and it were posted normally, as balanced Journal Entry.

**Question is:**
 why $200 (in "debit" column, in the picture) equals to 0.00 € (in "Amount Currency" column) ? Should it be 0.00 € or 222.22 € ?

**Comment by tvibliani** [comment]
What is a currency rate that makes $200 equal to 0.00 €? Of course this is a bug, so in this case it's good that runbot test were broken, as it reveals this bug.

**Comment by beledouxdenis** [comment]
Dear,

This is actually expected to not make the balance check depending on the `amount_currency`, as this `amount_currency` will be equal to 0.0 in case the journal item is within the company currency.

Regards,

**Comment by tvibliani** [comment]
@beledouxdenis 

It was regarded as a bug by customer and I was required to fix it as a bug, and I've fixed it in my deployment, but I'm convinced as well that it's a bug, that's why I provided this PR. it is NOT about checking balance only depending  on the amount_currency and the separated journal_item. Please investigate once again the picture I've posted above and the case in general. in the red circle there should be amount 222.22, NOT 0.0. Investigate Journal Entry as a whole, do not focus on the separate journal entry. This journal item can not be in company currency, regarding the rest of the Journal Entry. You have done here only credit entries in foreign currency, and there should be present 222.22 in debit as well, which will balance credit entries in foreign currency, not 0.0 as it is now. As the journal entry is not balanced (in terms of foreign currency) and it's possible to post this entry, then It is a **bug**. It's very inconvenient for users especially when they want to check balance or investigate separately foreign currency transactions. If you mean Whole journal entry is in company currency, then balance check provided in this PR will pass anyway, so you see the problem with different perspective I think. Please reconsider it.

**Comment by tvibliani** [comment]
@beledouxdenis 
I think you mix Journal Item and Journal Entry in your answer. but anyway, Journal Entry in Company Currency, legitimately containing 0.0 in Amount Currency is far away to be a problem for this PR, so...

**Comment by tvibliani** [comment]
@beledouxdenis 
You can't solve problems with the same thinking as you created them. So, once again, what you note as a reason for closing the PR is wrong, legitimate 0.0 entries in Amount Currency is not a problem for balance check on this field. So, if you mean something different, please provide some clarification or an example?

**Comment by tvibliani** [comment]
Dear @beledouxdenis,
1. If there is a case, when it's not desirable to check balance on Amount Currency field, and we intentionally allow unbalanced Amount Currency in the Journal Entry, please provide an example of such Journal Entry.
2. If there is such a case, then it should be uncommon case(?) and in general it should be desirable to check balance on this field. Should we include at least warning message for unbalanced Amount Currency?

**Pull request closed without merging**
