### PR TITLE
[IMP] website_forum: enhance layout consistency

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Since the redesign of the default theme ([odoo/120302]), `website_forum` needed to be fine-tuned in order to fit with the other website modules (eg. `website_sale`).

This commit adapts the sidebar to maintain consistency with the other website modules.

[odoo/120302]: https://github.com/odoo/odoo/pull/120302

task-3559011
Part of task-3097005

| Before | After |
|--------|--------|
| Capture d’écran 2023-10-18 à 09 54 13 | Capture d’écran 2023-10-18 à 09 55 06 | 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hello @odoo/rd-sm  👋
Here's a layout improvement for Forum, could you take a look at it ?

cc. @stefanorigano @qsm-odoo

**Review by flch-odoo — COMMENTED** [review]
Looks good! 

I did notice this though: 
image

**Review by flch-odoo — APPROVED** [review]
OK then, thanks for the check!

edit: BTW, I wasn't implying that this caused it, but that perhaps it could fix it :)

**Comment by Brieuc-brd** [comment]
Hey @flch-odoo 👋 , if this PR is ok for you, could you r+ ? 🙂 

FYI @edi-odoo is working on the button overflow in another PR 😉  : https://github.com/odoo/odoo/pull/139206

**Comment by flch-odoo** [comment]
Thanks @Brieuc-brd (and @edi-odoo)!

It is OK for me but I do not have r+...

Maybe @stefanorigano can finalize ? ;)

**Comment by stefanorigano** [comment]
Me neither @flch-odoo ... someone from your team?

**Comment by flch-odoo** [comment]
@tde-banana-odoo Can you please save us one more time :D ?

**Comment by Brieuc-brd** [comment]
Rebase + retarget to `17.0`

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
