### PR TITLE
[I18N] l10n_{fr,mz,mx,cz}: remove unnecessary whitespace

### PR DESCRIPTION
**Pull request by LouisGobert**
This commit removes unnecessary whitespace in the localization files.

No functional changes have been introduced, only whitespace adjustments.

#169577

### CODE REVIEW

**Review by FlorianGilbert — CHANGES_REQUESTED** [review]
I'm not against the fix, but we're breaking the whole history for white spaces. Shouldn't we instead trim what we receive to avoid this situation?

Because let's say, now we have fixed all the accounts, tomorrow someone add a new white space, the problem will be the same. So it could be great to trim it when we load the file :)

**Comment by LouisGobert** [comment]
Yes, good idea. But shouldn't we also modify the CSV files to have a clean code?

**Comment by FlorianGilbert** [comment]
> Yes, good idea. But shouldn't we also modify the CSV files to have a clean code?

Hello, yes if you want, we can clean it as well. My point was mainly on having something more robust, please do it it another commit :)

**Comment by LouisGobert** [comment]
> > Yes, good idea. But shouldn't we also modify the CSV files to have a clean code?
> 
> Hello, yes if you want, we can clean it as well. My point was mainly on having something more robust, please do it it another commit :)

Hello, if you think it's more robust this way (and since you have more experience with it), we can leave it as is 😊

**Comment by FlorianGilbert** [comment]
Ok, could you please fix the runbot @LouisGobert ?
Thank you!

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
