### PR TITLE
[FIX] tests: make sure screencasts dir exists before writing to it

### PR DESCRIPTION
**Pull request by yajo**
Without this patch, running this command on an environment where the tour will fail, will create massive and useless logs:

    odoo --stop-after-init -i auth_totp --test-enable --test-tags /auth_totp

[Excerpts of those massive useless logs](https://github.com/odoo/odoo/files/14065596/odoo.log.txt)

This is because this method is a callback that can come in a different thread, creating a race condition.

There's no problem on checking wether the directory exists before creating the file, and then safeguarding from the problem.

@moduon MT-1075

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Xavier-Do** [comment]
Hello yajo

Thanks for your contribution.

The screencast dir should actually be created in the `ChromeBrowser.__init__`
If it doen't exist, I would expect that a `_save_screencast` or `clear` was called, moving or removing the directory.

I think that in this case we should just drop the frame, ignore it. This will avoid to leave unused frame there.

So the fix would be to return if the directory does not exist, what do you think?

**Comment by yajo** [comment]
I was actually wondering how in the world could we ever get to this state where the directory doesn't exist. Now it makes sense! Thanks for your explanation. Let me update the fix.

**Comment by yajo** [comment]
Updated.

**Comment by Xavier-Do** [comment]
LGTM
@robodoo override=ci/security
The open was already existing, indentation changed to wrap it in a try except.

@robodoo r+

**Pull request closed without merging**
