### PR TITLE
[I18N] l10n_ch

### PR DESCRIPTION
**Pull request by i-vyshnevska**
Description of the issue/feature this PR addresses:

Current behavior before PR:

swiss QR invoice is not translated

Desired behavior after PR is merged:

report is translated

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Highcooley** [comment]
This PR relates to Odoo OPW Nr 2760866

**Comment by mart-e** [comment]
Hello,

Could you modify the files in `l10n_ch/i18n_extra/` instead?
Regarding the CLA, you need to add your email to the camptocamp CLA file.

**Comment by i-vyshnevska** [comment]
@mart-e  thanks, updated

**Comment by mart-e** [comment]
Thanks for the update, it looks good now. Could you amend your commits to follow the [commit message guidelines](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#commit-message-structure)?
Either keep two commits and use something like
```
[I18N] l10n_ch: update translations

The translations were outdated and the QR invoice was not translated
```
```
[CLA] add i-vyshnevska to c2c CLA
```
(squashing both commits is also acceptable)

**Comment by C3POdoo** [comment]
Dear @i-vyshnevska,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
