### PR TITLE
[FIX|CLA] auth_signup: fix password reset for multi-website

### PR DESCRIPTION
**Pull request by fabian-lange**
Description of the issue/feature this PR addresses:
https://github.com/odoo/odoo/issues/126030

Current behavior before PR:
When more than one websites are existing and "specific user account" is enabled, password-reset is not possible.

Desired behavior after PR is merged:
Enabling password-reset by adding the current website to the searchdomain if "specific user account" is enabled.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Thanks for the patch but you are modifying the àuth_signup`module that does _not_ depend of ẁebsite`, you can't assume there are website models here.

**Comment by fabian-lange** [comment]
Thanks for the awesome feedback.

I will update the solution in the coming days.

**Comment by fabian-lange** [comment]
> This is _definitely_ not correct: `auth_signup` doesn't depend on `website`, so it's very much possible to have `auth_signup` installed with no `website`, in which case this change will immediately blow up.
> 
> On the other hand, `website` does have a dependency on `auth_signup`, and already overrides auth_signup methods (e.g. `_signup_create_user`).
> 
> Also not sure the domain is correct, that users can be bound to a website doesn't mean they _must_ be, so I think the website filter should be current_website.id or False?

While working on your feedback I found another other (more generell) issue in the password-reset-prozess of portal users.

This is the part which filters the users to send the reset-link:
image

Following this logic there can be two users with a different loginname but same email address, since the mailadress is a related field of res.partner which is not unique.
If I want to reset a users password i get asked for the mailadress. In the stated case, this leads to the exception triggered, because there are more than one users with the same mailadress even if both are valid users.
Furthermore we checked our odoo instances running and found out, that loginnames are always emails except for the admin-user which is used by odoo.sh.

This information lead to believing that `if not users: users = self.search([('email', '=', login)])` is not necessary and causes way more issues than it solves.
In my opinion said lines of code should be removed and `self.search([('login', '=', login)])` should be the only domain used.
At the same time `login` should always be an email.
This should solve the issue described and also make the error `raise Exception(_('Reset password: invalid username or email'))` much more valid.

Is there anything I'm missing?
Why was the check for the email ever added?

Generally I have to admit, that these discoveries got me quite confused.

**Comment by fabian-lange** [comment]
@xmo-odoo have you already had time to talk to the product owner about this issue?

**Comment by bouvyd** [comment]
Hi there

I will make the following assumptions:
- we do not, at this time, want to enforce valid email addresses as login (mainly for historical reasons, but also because I think having the possibility to have custom logins which are not always email is ok and useful for external modules as well)
- we should not _enforce_ having a match between the partner email and the user login (same reasons as above)

From these, we can already make a decision or reach a partial conclusion:
- > In my opinion said lines of code should be removed and `self.search([('login', '=', login)])` should be the only domain used.
  - not something we want to do, explained above. Also I believe it's useful to process both, e.g. I may not remember my login on a platform but I for sure do know my email
- > because there are more than one users with the same mailadress even if both are valid users
  - indeed, though usually if you end up with a mismatch of email address vs login, it's a somewhat explicit choice (normal signup flows from the website or portal do not make this possible and use the email provided as login, for the sake of simplicity)

Having a check for both email and password for the search can seem a bit weird from the tech PoV, but for users I think it all seem natural. I certainly don't think it's *wrong* per so (e.g. we could simply relabel the input to 'Login or email' in the reset flow to make it clear that it will search on both, but since most users will have an email<>login match, it does not bring much value and could instead bring confusion).

@xmo-odoo asked me if sending on the partner email made sense if the login was a valid email - i think so, all the communication for user management goes through that email (including follow up communication like 2FA etc.), I honestly believe it should stay the same.

You also asked me if we should change the behaviour when 2 users have the same partner email - i think we have more wiggle room here, as indeed perhaps it makes more sense to reset the password of any users with the mentioned email rather than blocking the flow (the result is a bit annoying, since the email owner has to reset 2 accounts, but at least they're not stuck and can go through the whole process without and admin's assistance).

**Comment by fabian-lange** [comment]
@bouvyd i get your points

From my point of view, resetting all users instead of none is definitely better.
It still doesn't seem like a perfekt solution to me. But at this point haven't got any better idea myself.

Yet I think as long as the website-module is installed. it would be even better to take the website context into consideration when searching for the accounts to be resetted.
In this way the probability that multiple accounts have to be reset might be lessened quite considerably.
Especially if the option "specific_user_account" is enabled for the website in question.

**Comment by C3POdoo** [comment]
Dear @fabian-lange,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
