### PR TITLE
[FIX][mass_mailing] Forced types in token.

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses:
This is a failure that I just discovered from #12040. If we get a `res_id` or `email` parameter of wrong type, the token would be different (`repr(1) != repr("1") != repr(u"1")`). As such, types must be forced, and let `ValueError` be raised if wrong arguments come in.

Current behavior before PR:
`res_id` comes in as a string in controllers, so token never validates.

Desired behavior after PR is merged:
token always validates, or an exception is raised in case parameters have wrong format.

Additional note:
Please check this @odony (maybe you have new security best practices suggestions for this that I ignore). Also, I'm using `str` for casting because I assume that Odoo 11.0 will be in Python 3. I need confirmation for that because:

1. If it is not the case, we should use `unicode` or expect emails such as `ñoño@domaín.com`.
2. If it is the case, then I must adapt the algorithm in https://github.com/OCA/social/pull/129 to be forward-compatible, because `repr` is different for python 2 and 3. Not really a problem for @odoo, because you are losing backwards compatibility anyway, and have the luck to implement this directly in Py3k, but it's important for us (to not break backwards compatibility yet again in a year).

Thanks, sorry for disturbing you again with this.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by odony** [comment]
@Yajo In light of this, maybe the simplest fix would be to remove the email from the token, as it is not strictly necessary (no risk of token collision)? This way you only need the `int(res_id)` part of your patch, and it stays compatible by default, right?

**Comment by Yajo** [comment]
Yes, you're right. I used id + email as a combination of things that should be "impossible" to guess, but id + database.secret seems impossible enough.

I think the check must be added in another controller BTW, let me update this.

**Comment by Yajo** [comment]
It should be OK now, @odony.

Also this token was not being used in the JSON controller, so actually it was disabled when `website_mass_mailing` was installed. I added it to the :hankey: ajax JS unsubscriber.

I'll fix conflicts with #14386 when merged.

**Comment by Yajo** [comment]
@odony Am I right thinking you fixed this already in https://github.com/odoo/odoo/commit/31e81e7b8f8803abf0496e10ce0c25c4921030f7?

**Comment by mart-e** [comment]
Looks like it 😉 
Closing, thanks for the report

**Pull request closed without merging**
