### PR TITLE
[FIX] sale: display right quantity in sales by channel report

### PR DESCRIPTION
**Pull request by chienandalu**
Backport of https://github.com/odoo/odoo/commit/c13298fdacf52aedb2d2fee4db98203247c5e523 that solves issue https://github.com/odoo/odoo/issues/27643 in v11 as well

cc @Tecnativa TT24341

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@dbo-odoo can you check?

**Comment by dbo-odoo** [comment]
Hello!

Seems alright, could you just edit the commit message:
- remove the 'signed off by' portion (it will be added back by our mergebot)
- remove the "closes #28948" mention
- specify the hash of the original commit of which this is a backport: 'Backport of #########'

Thx!

**Comment by chienandalu** [comment]
Thanks @dbo-odoo Changes done :)

**Comment by dbo-odoo** [comment]
@fw-bot ignore

**Comment by dbo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
