### PR TITLE
[IMP] l10n_co: update latam identification type

### PR DESCRIPTION
**Pull request by nla-odoo**
Task: https://www.odoo.com/web#id=2486484&action=4043&model=project.task&view_type=form&cids=2&menu_id=4720

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by jco-odoo — APPROVED** [review]

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo r-
Wait for freeze please
@Xavier-Do ping retarget

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
