### PR TITLE
[CLA] Signature for hari4274

### PR DESCRIPTION
**Pull request by Florimond**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Florimond** [comment]
@mart-e @kebeclibre

**Comment by mart-e** [comment]
@Florimond where does this signature comes from? If you have a ticket number or something, please add it in the commit message. Otherwise it looks like forging signature.
PS: please update your github profile to reflect your new employment ;-)

**Comment by Florimond** [comment]
@mart-e I did amend the commit message to add the ticket id. Thanks.

**Comment by mart-e** [comment]
Thanks !

@robodoo r+

**Pull request closed without merging**
