### PR TITLE
[IMP] website: redesign `s_text_image` and `s_image_text` snippets

### PR DESCRIPTION
**Pull request by chgo-odoo**
- Requires : https://github.com/odoo/design-themes/pull/830

task-3665301
part of task-3619705

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by chgo-odoo** [comment]
Hello @stefanorigano, this PR is ready for review, same goes for its design-themes counterpart, could you have a look at it please?

**Review by stefanorigano — APPROVED** [review]
Well done, thanks @chgo-odoo 💪

**Comment by robinlej** [comment]
Seems all good :muscle: 

@robodoo r+

**Comment by bso-odoo** [comment]
@robodoo delegate=robinlej

**Comment by robinlej** [comment]
@robodoo r+

**Pull request closed without merging**
