### PR TITLE
[CLA] makinacorpus / kiorky: sign cla

### PR DESCRIPTION
**Pull request by kiorky**
needed for #6131 #6128

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Why do you sign it twice ? It should be enough with only the corporate (the check is based on the email)

**Comment by kiorky** [comment]
To sign both a personal, and corporate ;)
The makinacorpus signature is for me, but any other makinacorpus folk.

**Comment by mart-e** [comment]
@kiorky well the [CLA check](https://github.com/odoo/odoo-extra/blob/master/runbot_cla/runbot.py#L26) is based on the email address. So signing it twice with the same address has no effect. I don't think it has legal effect as there is no way to determine which signature applies to which commit.

If you wish to contribute to odoo using two different profile (corporate and personal), I think the best is to have two different email addresses. Sing the corporate with a `@makina-corpus.com` email address (if you have) and the personal with this one. A bit like what @alejandrosantana did to sign his [corporate](https://github.com/odoo/odoo/commit/5cfa96abc1f67e488629688cbdc45ea1d8a6aaf1.patch) and [personal](https://github.com/odoo/odoo/commit/0c039ce5f581cad5e55d8ca04d378be3948b838e.patch) CLA

**Comment by kiorky** [comment]
Ok, ill edit the commit.

**Comment by mart-e** [comment]
Thank you for the update, I have merged both CLA at 1593c5c482246353b3744107db99935b3ec4e4bb

**Pull request closed without merging**
