### PR TITLE
[FIX|CLA] base: add fallback mail to res.partner

### PR DESCRIPTION
**Pull request by fabian-lange**
Description of the issue/feature this PR addresses:
Solves the following issue:
https://github.com/odoo/odoo/issues/119610

Current behavior before PR:
Childaddresses might be created without email, which leads to no mails sent in some situations.
For example when a delivery-address is created without email, delivery notifications are not sent to the customer.

Desired behavior after PR is merged:
Childaddresses are always created with email if parent has an email.
If there is no email given on creation of the contact, the parent mail is used as fallback.

This way mails sent by the system reach the client even if for example a delivery-address is used instead of the base address.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by paju-odoo** [comment]
Hi Fabian, 
The issue has been fixed already, you can check it in runbot :)

**Comment by fabian-lange** [comment]
> Hi Fabian, The issue has been fixed already, you can check it in runbot :)

I just checked the Runbot of odoo-14 enterprise.
It still doesn't work for me:
image

On which version was the fix made?

**Comment by paju-odoo** [comment]
> > Hi Fabian, The issue has been fixed already, you can check it in runbot :)
> 
> I just checked the Runbot of odoo-14 enterprise. It still doesn't work for me: image
> 
> On which version was the fix made?

Hi Fabian, 
From my understanding, you would like the child address to use the parent's mail address in the partner's form. However, I think that in some cases this isn't the best solution, and that it's better to leave it blank, and leave the possibility of adding it later. 
That being said, a fix has been made so that there is a fallback on the parent's main address for delivery emails when the child partner doesn't have one, so that the delivery email is sent correctly. I've checked every version since v14 and it works fine for me: https://nimb.ws/G5Zhm4

**Comment by fabian-lange** [comment]
@paju-odoo have you already got any information about the fix in odoo 14?

**Comment by paju-odoo** [comment]
> @paju-odoo have you already got any information about the fix in odoo 14?

@fabian-lange yes indeed. The fix will be made in v14.0
We will also improve the fix made in v15 by specifying in the chatter that the mail has been delivered  (no red icon). 
Note: we are pretty loaded at the moment and this is not our highest priority. I'll inform you when it's available

**Comment by C3POdoo** [comment]
Dear @fabian-lange,

    Thank you for your contribution but the version 14.0 is no longer supported.
    We only support the last 3 stable versions so no longer accepts patches into this branch.

    We apology if we could not look at your request in time.
    If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

    _This is an automated message._

**Pull request closed without merging**
