### PR TITLE
[FIX] point_of_sale: it is possible to use an account from an other company

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
Before this commit it is possible to set a account for an other company.

@nimi-odoo 
@oco-odoo

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW #3493627

**Comment by robinengels** [comment]
@rhe-odoo @caburj

**Comment by fmdl** [comment]
ping @rhe-odoo @caburj

**Comment by robinengels** [comment]
@caburj @rhe-odoo

**Comment by robinengels** [comment]
Hello @fmdl could you rebase your PR to target 15.0 ? Thanks

**Comment by fmdl** [comment]
@robinengels targeted in 15.0

**Comment by fmdl** [comment]
ping @rhe-odoo @caburj

**Comment by fmdl** [comment]
ping @robinengels

**Comment by caburj** [comment]
The changes look good. Could you add a statement or two in the commit description summarizing the problem if a payment method used an account that doesn't belong to the company?

**Comment by fmdl** [comment]
@caburj message updated.

**Review by caburj — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
