### PR TITLE
[MERGE] web: update bootstrap from 4.2.1 to 4.3.1

### PR DESCRIPTION
**Pull request by qsm-odoo**
See https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0/
and https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

Again, some fixes were added in this version and not in a 4.2.x version
so there is no clean way to backport them in 12.0 / saas-12.2.
If needed, the file bootstrap_review.scss is there for that.

Among the new features, two notable ones:
- The '.modal-dialog-scrollable' class which does what odoo already
  implemented for all its modals. So we could remove our custom code in
  a next update.
- Responsive font sizes ! Plan was to develop something similar for the
  website, so this comes at the right time. The behavior is opt-in, we
  will enable it in a next update.

task-1944790

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@robodoo rebase-merge

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@robodoo retry

**Comment by qsm-odoo** [comment]
@d-fence This one too... :)

**Comment by d-fence** [comment]
Same answer. Non deterministic fails. This bug affects other branches too

**Comment by xmo-odoo** [comment]
@qsm-odoo was it really a good idea to suppress the deprecation messages for the `size` builtin instead of surfacing it as a warning & fixing the existing one?

**Comment by qsm-odoo** [comment]
@xmo-odoo If I remember well, if you wanted to keep deprecation messages, you were stuck with warnings because bootstrap itself uses deprecated methods :shrug:. So it was this or patching the lib. Any specific problem with this?

**Comment by xmo-odoo** [comment]
> @xmo-odoo If I remember well, if you wanted to keep deprecation messages, you were stuck with warnings because bootstrap itself uses deprecated methods shrug. 

Gah, makes sense then

> So it was this or patching the lib. Any specific problem with this?

No specific problem, only fear of what'll happen if we ever get to 5.0 without dropping bootstrap (I'm not quite sure how but I got the message to trigger somehow and went looking for what that was about).

**Pull request closed without merging**
