### PR TITLE
[8.0][Fix]: 'reply_to' is missing in Message Dictionary

### PR DESCRIPTION
**Pull request by andreinl**
Description of the issue/feature this PR addresses:
'reply_to' is missing in Message Dictionary. It should be in the dictionary if an email has reply-to field.

Current behavior before PR:
Message dictionary has no 'reply_to' key

Desired behavior after PR is merged:
'reply_to' should be in the dictionary
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by odony** [comment]
Hi,
I suppose you have a special use case where you need the `Reply-to:` header? We don't use it in the official code, because it's irrelevant for mail routing, so we did not have any reason to extract it.

Could you retarget your PR to `master`, as this is [a change request, not a bugfix](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch)?
You should also probably update the docstring of the `message_parse` method.

For stable branches, like 8.0, it should be simple for you to inherit the `message_parse()` method and add the Reply-To info, in your custom code.

Thanks,

PS: this should be validated with @tde-banana-odoo

**Comment by andreinl** [comment]
Use case is quite simple. Many automatic systems send emails from 'noreply' or similar address and put a real email address in 'reply-to' field. When creating a new lead from email this is the field to use as 'email_from' address. I understand that this is a substantial fix that can be never accepted for the stable branch even if I meet other people that suffer from this problem. On the other hand adding a new field to a dictionary can't compromise current code.

**Comment by odony** [comment]
@andreinl Thanks for the explanation.

As for the target branch, I understand that this may seem surprising on the first look.

The thing is, our [rules](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch) about where a patch should land are not solely based on the potential side-effects of a patch. Even if the tiniest changes can sometimes come with unexpected effects.
Our rules are based on our experience and past cases where similar tiny changes backfired in different ways. Because the benefit/risk ratio is just too low for a stable branch.

And there is more:
 - if we start accepting small "nice-to-have" changes left and right, the line gets harder to draw as to which changes should be rejected, because "this other change was accepted, right?".
 - Isolated "nice-to-have" changes with no direct use (not a bugfix) often call for more changes, in order to improve consistency. So other tiny change requests arrive, and they need to land in the same "stable" branch, and so on.

So we tend to follow the rule strictly: improvements/change requests are not for stable branches.

I hope you can understand our position.

**Comment by tde-banana-odoo** [comment]
Hello,

Sorry for the delay. Indeed we can accept it for master as we avoid changes that are not bugfixes in stable version. We will not use this key in our officiel code base but I think we can safely add it in master. Ping me when you make a new PR !

Thanks,

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
