### PR TITLE
[FIX] e-commerce : pricefilter activated only when needed

### PR DESCRIPTION
**Pull request by luve-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Williambraecky — CHANGES_REQUESTED** [review]
This just need a nice commit message :)
Thanks

**Comment by luve-odoo** [comment]
Commit message written :)

**Review by Williambraecky — APPROVED** [review]
Thanks for your work!
robodoo r+

**Comment by Williambraecky** [comment]
@robodoo r+

**Pull request closed without merging**
