### PR TITLE
[REF] mail: `discuss_container` scss refactoring

### PR DESCRIPTION
**Pull request by karlosvalverde**
Current SCSS is replaced with global Bootstrap classes, in
order to reduce code lines and to increase performance.

Task-2821258

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by alexkuhn — CHANGES_REQUESTED** [review]
`min-height: 0;` `!==` `height: 100%` strictly speaking.

- `min-height: 0;` in flex is to let item shrink lower than its content, when container is smaller.
- `height: 100%` enforces height of item to whole available size in container, regardless of content.

I get that it produces the same result in practice with `DiscussContainer`, with current specs of code. But I think `min-height: 0` represents more what we really want rather than `height: 100%`.

For me, `min-height: 0` is appropriate because it feels like intrinsic styling of the component.
On the other hand, `height: 100%` is extrinsic as it's contextual.

**Comment by karlosvalverde** [comment]
> `min-height: 0;` `!==` `height: 100%` strictly speaking.
> 
>     * `min-height: 0;` in flex is to let item shrink lower than its content, when container is smaller.
> 
>     * `height: 100%` enforces height of item to whole available size in container, regardless of content.
> 
> 
> I get that it produces the same result in practice with `DiscussContainer`, with current specs of code. But I think `min-height: 0` represents more what we really want rather than `height: 100%`.
> 
> For me, `min-height: 0` is appropriate because it feels like intrinsic styling of the component. On the other hand, `height: 100%` is extrinsic as it's contextual.

This remark is also related to a similar conversation, seen in https://github.com/odoo/odoo/pull/87915 , which I hope to clarify in order to be both resolved. 😉 

According to the `W3C`, `for [scroll containers](https://www.w3.org/TR/css-overflow-3/#scroll-container) the [automatic minimum size](https://www.w3.org/TR/css-sizing-3/#automatic-minimum-size) is zero`. --> https://www.w3.org/TR/css-flexbox-1/#min-size-auto

For this reason, `o_DiscussContainer` is here a `scroll container`, and, since this node is set to be a flex element by using a `d-flex` class, it is not appropriate to set a minimum size set to 0, which is already using automatically by default. 

However, I notice that the previous container also uses a `flex-grow-1` class, which would force the container to use either a `min-size: 0` or a `h-100` in order to adapt properly its content to the height of the container.

I would consequently propose to remove the aforementioned `flex-grow-1` class, remove all the additional CSS of the component and keep the `h-100` class. Otherwise we would be keeping unnecessary and redundant lines of code , which is the opposite to the goal of this PR.

Thanks! 😉

**Comment by alexkuhn** [comment]
I disagree with replacing `min-height: 0;` and `flex-grow-1` to `h-100`. This gives the same result right now because `DiscussContainer` is the sole sibling of `o_widget_Discuss`. But if we want to introduce another sibling (change of specs), you'll see that rule need to be changed, because it's an oversight of current specs.

I get that `o_widget_Discuss` is legacy code and we won't keep it. Also there's no reason to have a sibling of `DiscussContainer`. But please understand that `h-100` introduces an assumption in how it's being used. It doesn't scale well, especially when you want to add a sibling.

The code is far from being perfect. `flex-grow-1` is contextual styling, so ideally it should not have been an intrinsic class on this component. Unfortunately, code above `DiscussContainer` is not in our scope, so we cannot adapt this correct correctly.

It's appreciable to have less LOCs, but it's far more important to have code that defines precisely the wanted behaviour. And a desirable behaviour is not just same visual with current use-case: it's also having rules that make sense for code maintenance.

**Comment by alexkuhn** [comment]
If there is no equivalent classname(s) for semantically have `min-height: 0`, then yes we can close this PR. Thanks!

**Comment by karlosvalverde** [comment]
> If there is no equivalent classname(s) for semantically have `min-height: 0`, then yes we can close this PR. Thanks!

Sadly, Bootstrap doesn't provide any class semantically similar to `min-height-0`, apart from the solutions seen above. For this reason, I'm closing this PR right now.  👍

**Comment by karlosvalverde** [comment]
Hey @alexkuhn , I just noticed that yesterday this little guy was merged: https://github.com/odoo/odoo/blob/3573a7fef497d7a2d3efd27da91adb5a7f9af27f/addons/mail/static/src/components/discuss_container/discuss_container.xml#L5

With the `min-height: 0` plus the conversations seen above, is `h-100` still needed?

**Comment by alexkuhn** [comment]
Hello, yes this was added with this big commit yesterday:
https://github.com/odoo/odoo/commit/3573a7fef497d7a2d3efd27da91adb5a7f9af27f

This was a final commit of a technical change that took almost a full year, with frequent stuffs merged here and there.
For the final commit, we decided to just merge it, even without as deep review, so that it's ready for the `saas-15.4` freeze and we can fully focus on the big functional changes that are still planned for v16. If there are any things to adjust, it'd be to do after merging it, so that we can finally enjoy the big technical improvement.

I'm pretty sure the `h-100` is wrong here. I didn't ask the precise motivation for adding it, but I wouldn't be surprised this was the easiest way to make tests with discuss app work with the many changes in the test environment, although conceptually wrong.

So we keep `min-height: 0`, and I'll see how to properly tackle the underlying issues that motivated the `h-100` as to not needing `h-100` at all.

Thanks for pointing it out!

cc @tsm-odoo

**Comment by alexkuhn** [comment]
@karlosvalverde 
The widget `Discuss` was removed, and it had `height: 100%`, hence why the `h-100` was put in `DiscussContainer`.

Conceptually `h-100` is contextual styling, so in theory this should not be an intrinsic style on `DiscussContainer`, because this depends on the fact that `DiscussContainer` is used inside action manager and it's "fullscreen" there (minus systray, but it's designed outside of the "content" part of action manager somehow).

So we'll keep `h-100` on `DiscussContainer` in the end, and consider `DiscussContainer` as a component that is very specific to its use as a "fullscreen" client action. So this means that if in the future we'd like to have different `Discuss` app views and they differ with more or less siblings, then we should define different **_containers_** in both cases.

Note that the `Container` components in Discuss exist just for integration with the code of Odoo that is not discuss code.
So it's fine to define one per specific use.

-----------

So in the end, we just keep `h-100` for `DiscussContainer`. I'll make a PR to remove `min-height: 0`, because this becomes useless with `h-100`.

**Comment by alexkuhn** [comment]
Here's the PR: https://github.com/odoo/odoo/pull/92613

**Comment by karlosvalverde** [comment]
> @karlosvalverde The widget `Discuss` was removed, and it had `height: 100%`, hence why the `h-100` was put in `DiscussContainer`.
> 
> Conceptually `h-100` is contextual styling, so in theory this should not be an intrinsic style on `DiscussContainer`, because this depends on the fact that `DiscussContainer` is used inside action manager and it's "fullscreen" there (minus systray, but it's designed outside of the "content" part of action manager somehow).
> 
> So we'll keep `h-100` on `DiscussContainer` in the end, and consider `DiscussContainer` as a component that is very specific to its use as a "fullscreen" client action. So this means that if in the future we'd like to have different `Discuss` app views and they differ with more or less siblings, then we should define different **_containers_** in both cases.
> 
> Note that the `Container` components in Discuss exist just for integration with the code of Odoo that is not discuss code. So it's fine to define one per specific use.
> 
> So in the end, we just keep `h-100` for `DiscussContainer`. I'll make a PR to remove `min-height: 0`, because this becomes useless with `h-100`.

In this case, this logic could also be extended to `o_Discuss`, as we have seen here https://github.com/odoo/odoo/pull/87915#issuecomment-1142121357

What do you think?

**Comment by alexkuhn** [comment]
> In this case, this logic could also be extended to `o_Discuss`, as we have seen here [#87915 (comment)](https://github.com/odoo/odoo/pull/87915#issuecomment-1142121357)

No, the problem with `Discuss` is different from `DiscussContainer`.
The `min-height: 0` is semantically very different from `h-100`, and it's definitely `min-height: 0` we want in `Discuss`, not `DiscussContainer`.

The sole reason we put `h-100` in `DiscussContainer` is for integration with client action and specific usage of it. We definitely don't want that for the `Discuss` component.

**Pull request closed without merging**
