### PR TITLE
[FIX] typo - loglevels.py

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**
typo fix in loglevels.py

### CODE REVIEW

**Comment by Yenthe666** [comment]
@Abdur-rahmaanJ thanks for the PR but typo's and small fixes should be done against master, not a stable version (12.0 in your case). Can you please do this against master?

**Comment by Abdur-rahmaanJ** [comment]
@Yenthe666 should i close the PR?

**Comment by Abdur-rahmaanJ** [comment]
and reopen another?

**Comment by Yenthe666** [comment]
You can choose. Either close this one and create a new one against master or rebase your PR. :)

**Pull request closed without merging**
