### PR TITLE
[FIX] web: basic_model: save a paged nested o2m

### PR DESCRIPTION
**Pull request by kebeclibre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fdamhaut** [comment]
@kebeclibre I forgot about this PR as it was not in my list but thought of it last week and finally did the test :/

**Review by aab-odoo — COMMENTED** [review]
I don't see how the test is related to the fix. In the code, you mention the case of a record creation. In the test, you edit an existing record. Also, you don't assert what is sent to server for the save/create rpc. As it stands, I'm wondering whether the test isn't simply testing the mock server. I only looked at the diff, I didn't try to run the test to fully understand, so I may be wrong. Anyway, the rule is simple: the test must pass with the fix, and fail without.

**Comment by fdamhaut** [comment]
> I don't see how the test is related to the fix. In the code, you mention the case of a record creation. In the test, you edit an existing record. Also, you don't assert what is sent to server for the save/create rpc. As it stands, I'm wondering whether the test isn't simply testing the mock server. I only looked at the diff, I didn't try to run the test to fully understand, so I may be wrong. Anyway, the rule is simple: the test must pass with the fix, and fail without.

- The test fail without the fix and pass with it

As for the comment in the code it was written by LPE so i'll let him answer as I'm not entirely sure what he meant but the test was made according to the commit description : 
> In a form view, have a o2m field (A), with a nested o2m field (B).
> The A field should have multiple pages, with each record having at least one record in their B field.
> Have a (C) field that will modify a record in the nested o2m when changed.
> Change the B field, and save.

**Comment by adwid** [comment]
@kebeclibre @fdamhaut @aab-odoo 

Hi guys, sorry for the spam but could you give us an update ? 
We have received yet another ticket related to this problem.

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
