### PR TITLE
[fix] saas-16 : relational field will not prompt for create record  i…

### PR DESCRIPTION
**Pull request by pam-odoo**
…f user does not have  the access rigths to do so

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pam-odoo** [comment]
After `create`  prompt in many2one field if user have no access right to do so , it displays error on create so this is the fix not to display the create prompt if  have not sufficient rights to do so

**Comment by ged-odoo** [comment]
@pam-odoo this PR is good, but there should be a small test...

**Comment by pam-odoo** [comment]
Test case added for the same

**Comment by mge-odoo** [comment]
@pam-odoo I was working on the exact same thing when Gery told me about your PR, what a coïncidence :-) merged in saas-16 (see https://github.com/odoo/odoo/commit/74c27d81ed299441d3ba07c2181d0e9830b1fec0 )

Thanks !

**Comment by pam-odoo** [comment]
@mge-odoo  Oh Great !

**Pull request closed without merging**
