### PR TITLE
[FIX] account_payment: fix portal pay button

### PR DESCRIPTION
**Pull request by kitan191**
Steps to reproduce:
- Install Accounting
- Activate a payment provider (e.g. Stripe)
- Configure payment provider with "Capture Amount Manually" option activated
- Invoice Online Payment in Accounting settings
- Create an invoice
- Go to invoice portal preview
- Pay it via "Pay Now" button
- Go back to invoice portal preview

=> The "Pay Now" button is still there (not expected)

- Uninstall "account_payment_invoice_online_payment_patch" module
- Go back to invoice portal preview

=> The "Pay Now" button does not appear anymore (expected)

Cause:
"account_payment_invoice_online_payment_patch" module has been created to allow to disable invoice online payment without uninstalling "account_payment" module.

However, it overrides 2 different `t-if` conditions:

1)
```
(invoice.amount_residual or not tx_ids) and
invoice.state == 'posted' and
invoice.payment_state in ('not_paid', 'partial') and
invoice.amount_total
```

2)
```
invoice.state == 'posted' and
invoice.payment_state in ('not_paid', 'partial') and
invoice.amount_total and
invoice.move_type == 'out_invoice' and
(pending_manual_txs or not tx_ids or invoice.amount_paid < invoice.amount_total)
```

with the same condition `invoice._has_to_be_paid()` that corresponds to:
```
(self.amount_residual or not transactions) and
self.state == 'posted' and
self.payment_state in ('not_paid', 'partial') and
self.amount_total and
self.move_type == 'out_invoice'
```

One part of the second `t-if` condition is removed by the override:
`(pending_manual_txs or not tx_ids or invoice.amount_paid < invoice.amount_total)`

The second condition is used and is overridden 2 times.

Solution:
Add `(pending_manual_txs or not tx_ids or invoice.amount_paid < invoice.amount_total)`
in the `_has_to_be_paid` method.

opw-3378400

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gawa-odoo** [comment]
Hello! 
I'm sorry, I don't have the identifiers for Stripe, so I can't test.
Do you know why the conditions are different? Is there a reason the second part of the condition (that you add) is not in the other use (The case 1. that you gave)? (And so, could it not be in the Python function?)
Because the third use of `_has_to_be_paid` does seem to override a code with the `(pending_manual_txs or not tx_ids or invoice.amount_paid < invoice.amount_total)` (and so, case 1 seems to be the outlier)

**Comment by kitan191** [comment]
@gawa-odoo Thanks for the review! :)

I've moved the fix in the python function.

**Review by gawa-odoo — APPROVED** [review]
LGTM!

**Review by nle-odoo — COMMENTED** [review]
robodoo delegate+

(with what we discussed done, looks good to me)

**Comment by kitan191** [comment]
@robodoo r+

**Pull request closed without merging**
