### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by FedericoLaTorre**
Fix server error when trying to install module

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

What is the error you get?
If the test failed, we would have noticed on our [CI](http://runbot.odoo.com/runbot)

**Comment by mart-e** [comment]
This is very odd, it looks like odoo is considering "tests" as a module.
You are installing the stock_zebra module through the interface, right? Or is it another module?
Could you share your configuration ? What is your addons path? Are you up to date?

**Comment by lmignon** [comment]
IMO, whatever the cause of the problem, this change is perfectly valid. It is better to use a relative import in this case to avoid collisions with any other package with the same name.

**Comment by FedericoLaTorre** [comment]
Hi, yes, I'm installing stock_zebra module from the interface. I have Argentina AdHoc Localization. Here is my config with addons path:

[options]
addons_path = /opt/odoo/account-financial-tools,/opt/odoo/account-payment,/opt/odoo/aeroo_reports,/opt/odoo/argentina-reporting,/opt/odoo/argentina-sale,/opt/odoo/miscellaneous,/opt/odoo/odoo-argentina,/opt/odoo/partner-contact,/opt/odo$
admin_passwd = *****
csv_internal_sep = ,
data_dir = /var/lib/odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = False
db_port = False
db_sslmode = prefer
db_template = template0
db_user = odoo
dbfilter = 
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
limit_time_real_cron = -1
list_db = False
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo/odoo-server.log
logrotate = False
longpolling_port = 8072
max_cron_threads = 1
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = True
reportgz = False
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file = False
test_tags = None
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 2
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1

**Comment by C3POdoo** [comment]
Dear @FedericoLaTorre,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
