### PR TITLE
[FIX] mail: no crash on adding a new old activity

### PR DESCRIPTION
**Pull request by datonefaridze**
Before this commit, when adding an outdated activity
from kanban activity widget, it crashed with the following error:

TypeError: cannot read property of undefined (reading `mail_template_ids`)

Steps to reproduce:
- on crm lead schedule call activity and make sure that activity is at
  least 1 month old
- add activity to the Call Queue
- try to access/edit activity

This happens because of adding an outdated activity, this is
automatically considered as an old activity, which leads to its
deletion immediately after creation. OWL is rendering the template of
`ActivityListPopover` while the activity is deleted, which is a problem
because activity doesn't exist therefore its fields have been cleared,
such as mail_template_ids that is undefined instead of a list.

task-3945492

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Not sure why you speak about dates ? Seems to be about templates ?

**Comment by alexkuhn** [comment]
Also could be worth explaining how to reproduce the issue, because at a glance when there's an activity, the `mail_template_ids` is set thanks to `activity_format` and this is a list.

**Comment by datonefaridze** [comment]
> Not sure why you speak about dates ? Seems to be about templates ?

initially it was about dates and I recently changed it. dates have no problem in v17.0, but in master dates become undefined too so adding `?` becomes necessary (I checked it here and it's not necessary to do it because `luxon.DateTime.fromISO` can still works on undefined dates, so I removed it).

**Comment by datonefaridze** [comment]
> Also could be worth explaining how to reproduce the issue, because at a glance when there's an activity, the `mail_template_ids` is set thanks to `activity_format` and this is a list.

I was planing to notify discuss team about that today, the issue is strange indeed, [This](https://www.awesomescreenshot.com/video/27954611?key=7b79d1342790b374b21659257981235e) is the way you can reproduce the issue (I will also edit the commit message).
I initially investigated (deeper level) about `date_deadline`, it used to be undefined despite the fact that frontend fetched those dates successfully from the server. Strange behaviour occurs and for some reason dates become unavailable.
I didn't go deeper on `mail_template_ids` since I assumed that this had to have similar behaviour. 
p.s I felt like it was similar issue as [here](https://github.com/odoo/odoo/pull/115689/files#r1343983527) so I added `?`

**Comment by datonefaridze** [comment]
@alexkuhn @tde-banana-odoo done, also please not that i made new pr here: https://github.com/odoo/odoo/pull/167319
I had to add optional chaining, because in previous versions `luxon.DateTime.fromISO` can deal with undefined types, but in 17.2 we removed casting and directly did `this.date_deadline.toLocaleString` which raises an issue if `this.date_deadline` is undefined.
please note that those have the same branch name, and I am not sure if that supposed to be that way or not.

**Pull request closed without merging**
