### PR TITLE
[FIX] mail: improve contrast inside arrow buttons

### PR DESCRIPTION
**Pull request by chgo-odoo**
This commit improves the readability of the label inside an arrow button.

Prior to this commit, the label of an arrow button was styled with a `opacity-50` class. This would render well visually, but does not provide sufficient contrast. This becomes especially true in dark mode.

To improve the readability of this label, we simply set a `text-muted` class to it, which will still apply an opacity, but more subtle, making our label readable.

task-3575154

| 17.0 (Lightmode)  | 17-0-fix-contrast-issue-in-arrow-btn-chgo |
| ------------- | ------------- |
| image | image |

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hey @chgo-odoo 👋 
Just wondering, shouldn't it be done in `16.4` instead of `17.0`?

**Comment by chgo-odoo** [comment]
> Hey @chgo-odoo 👋 Just wondering, shouldn't it be done in `16.4` instead of `17.0`?

Thanks for noticing it, @Brieuc-brd ^^ It's in fact introduced in 16.4. I retargeted the PR and rebased with the right base.

**Comment by chgo-odoo** [comment]
Hi @stefanorigano 👋

Could you have a look at the changes introduced in this PR please ? Thanks !

**Review by stefanorigano — APPROVED** [review]
Thanks @chgo-odoo 👍
Besides the contrast improvement, I find `text-muted` semantically more correct, good.

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
