### PR TITLE
[FIX] wrong translation

### PR DESCRIPTION
**Pull request by blaggacao**
Just a small translation fix
@mart-e 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be done on Transifex. And it's "conciliación", not "reconciliación". I will change it directly on Transifex, so please close this.

**Comment by mart-e** [comment]
Hello,

Thanks for the contribution but, as said Pedro, please check [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://transifex.com/odoo), not Github.

Please submit your changes there and let me know if you have issues.

Thanks

**Comment by pedrobaeza** [comment]
FYI, I have already properly translated the sentence.

**Comment by blaggacao** [comment]
@mart-e I understand, but for my case that's too much of a overhead... 😢 I thought this would be also possible over here... 

@pedrobaeza Are there any quick alternatives or any feasible workflow, which would work for me "on the go and between jumping from one train onto another"?
If so, this would be great, you could count on me for further correction (also I'm not native, as you recognized 😄 ) Let e know... thanks.

**Comment by pedrobaeza** [comment]
Transifex is very easy and quick to work with, so I don't see special problems with that flow.

**Comment by blaggacao** [comment]
OK, great, I'm giving it a try. Sorry if I keep you asking here... For example, if I know that some words related to "backorder" are translated wrongly in my code copy, how can I find all occurrences of backorder in transfiex (first definition and possible overrides in other modules) to verify if it has been fixed? Or is this not possible? I tried the search bar but it doesn't result anything useful as it seams:
image

**Comment by mart-e** [comment]
The Transifex translations are divided by module. So if you want to search backorder in the `stock` module, you will go to
https://www.transifex.com/odoo/odoo-10/translate/#es/stock/96755472?q=backorder

there is a hack, if you want to access the translations of all modules, you can replace the name of the module with `$` (after applying your filter) to see all results in the different modules
https://www.transifex.com/odoo/odoo-10/translate/#es/$/96755472?q=backorder

**Comment by Yenthe666** [comment]
@mart-e or you simply click on "All resources"? 😉

**Comment by mart-e** [comment]
@Yenthe666 using buttons is so _passé_ 😉

**Comment by blaggacao** [comment]
Thanks 😄 Understood.
According to the linked docs, I would then submit a suggestion. Understood as well. But how does the workflow go on from then? What "guarantees" do I have in terms of reviewer notification or timely revision, if those garanties fail, how should I notify and whom?
Is there any list of my pending suggestions, or do they just disappear in the jungle handed over to it's own fate?

**Comment by blaggacao** [comment]
And lastly, if I would like to start a (global) discussion on weather "backorder" is "entrega parcial" (literally: partial delivery) or "entrega pendiente" (literally: pending delivery / backorder), where should/should I do that?
Assuming there that both things aren't strictly the same, a discussion would be interesting.

**Comment by blaggacao** [comment]
@mart-e btw, have you had a look at https://docs.transifex.com/live/translating-in-context - translating out of context is so passé :wink:

**Comment by Yenthe666** [comment]
That looks very interesting!

**Pull request closed without merging**
