### PR TITLE
[WIP] [8.0] Recomputes are not triggered for cascading removals.

### PR DESCRIPTION
**Pull request by mvaled**
When having a computable field 'X' that depends on a One2many 'children' field, it does not get recomputed when any of the child items is removed via a cascade unlink.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mvaled** [comment]
Hi @odony 

We're working on this PR for some weeks now.  I'd like to have some outside review.  

We're still adding the tests that show what we deem are bugs.  

The test added in 7f5e97d2f7c703f9c7b8e453ef67e9a993bad6d2 shows the issue we found first, but my colleagues are writing others that we've fixed in this PR as well.

I have confirmed the same bug (no recomputation via cascade removal) in Odoo 10. We have another fix for Odoo 10, but I would like to make it a proper forward-port (git merge) solution.

**Comment by odony** [comment]
Hmm, I don't think the main issue you report is a bug, it's the expected behavior, to me. Or at least a caveat that developers need to be aware of. `ondelete=cascade` is handled directly by the database backend, and should be used sparingly, and carefully. It happens magically without the ORM knowing about it, and only fits very specific cases.
We recommend it only for dependent items that need to be destroyed along with their parent (typically, lines/children of a parent document), and when we don't need any specific "cleanup" step upon deletion (e.g. no files or mail messages attached to the items, etc.).
Your use case has the `ondelete=cascade` on a m2o to a different model than the parent. That's not supposed to work, you should instead override the `unlink()` method of the target model to do the cleanup using the ORM.

Trying to fix this in the ORM while preserving the current behavior of "ondelete=cascade" does not make a lot of sense. It's as if you wanted the ORM to detect manual SQL queries and update the cache/recompute when needed. That's not the ORM's job, and it will never work properly. Developers need to be careful when using anything that does raw SQL, like `cr.execute` or `ondelete=cascade`.
In addition, we're very unlikely to consider [such changes in a stable series](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch), especially 8.0 that will soon be end-of-life.

PS: when you make a PR, please keep it minimal. Adding tests is great, but adding scripts to run them is not necessary ;-)

**Comment by mvaled** [comment]
Hi @odony,

Thanks for your insight. 

I came up with this issue while creating an extension for the analytic account.  The analytic account (the parent) has several analytic lines (the children), but each child it's owned by an `account.move.line`. When the move line is removed, the computable fields I introduced in the analytic account are not recomputed. 

So, the structure about the children having another non-parental m2o with `ondelete=cascade`, actually exists in Odoo 8 ;). However, the issue only manifests itself because of the computable-stored fields I introduced.   I think this is why the fields `balance`, `debit` and `credit` of the analytic account are not stored.  The branch 'master' has the same structure.

Before trying to "fix"  the ORM, I did what you recommended: overwrite the `unlink` of account move lines.  We can always do it that way, but I thought that if the ORM knows about the cascade, it could handle that case.  

I know the ORM must has some limits, and that if you intentionally break the abstraction provided by it (for instance you execute some SQL directly), the ORM has no responsibility over that.  In the example, however, the developer does not attempt to by-pass the ORM, he/she is just trying to "combine" two features of the ORM: the computable-stored fields, and the `ondelete=cascade`.  

I think that should be noted on the documentation somehow.  Or we could try to fix it (in the master branch), if you think the ratio of (probable) added complexity against the number of possible usages proofs such an effort worthy. 

Nevertheless (as the test shows) we haven't succeeded to make this work.  Also, I you don't mind, I would like to add the other "issues" we've found but not documented yet.

PS: The `runtests.sh` script slipped into the commit (Oops!).  I have it just to ease the whole testing cycle without going up to runbot :|

**Comment by mvaled** [comment]
BTW, we managed to "fix" the main issue in 2666f572824 ;)

**Pull request closed without merging**
