### PR TITLE
[ADD] l10n_my

### PR DESCRIPTION
**Pull request by tong-odoo**
- Create Malaysia Accounting localisation

task-2870449

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by vin-odoo — CHANGES_REQUESTED** [review]
A few comments, thank you for the work :)

Note: for the language, it will require an exception so that we can merge (either from upgrade or runbot team)

**Review by vin-odoo — CHANGES_REQUESTED** [review]

**Review by vin-odoo — APPROVED** [review]
LGTM now :)

**Comment by d-fence** [comment]
Upgrade exception [#161](https://runbot.odoo.com/web/#id=161&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
xmlid:base.lang_ms
```
cc @KangOl @nseinlet

**Comment by tong-odoo** [comment]
@vin-odoo Since we don't have permission to call mergebot, could you help to call `r+`? I will update the forward-port on 16.0 for the user_type_id/id update on account.account.template.csv.

Thanks!

**Comment by vin-odoo** [comment]
@tong-odoo I was told to wait for the green light from @KangOl or @nseinlet before r+ :)
But they were not available yesterday and today is a public holiday in Belgium, so it will have to for tomorrow.
Have a good day

**Comment by tong-odoo** [comment]
> @tong-odoo I was told to wait for the green light from @KangOl or @nseinlet before r+ :) But they were not available yesterday and today is a public holiday in Belgium, so it will have to for tomorrow. Have a good day

@vin-odoo Sure no problem. Thanks for your help again. Have fun in your holiday!

**Comment by KangOl** [comment]
> @tong-odoo I was told to wait for the green light from @KangOl or @nseinlet before r+ :) But they were not available yesterday and today is a public holiday in Belgium, so it will have to for tomorrow. Have a good day

Fake News™️!
We were present on Monday.
However, you don't need our approval for the `r+`.
The `cc` was just to allow us to use a veto if the need for an upgrade exception could be avoided [^1]. This is not the case here, so you can go with the `r+`.

[^1]: like in https://github.com/odoo/odoo/pull/94654#issuecomment-1173526371

**Comment by vin-odoo** [comment]
@KangOl Woops, my bad.
Oh well, I was told on Discord to wait for the green light from either of you :smile: 
Thanks for the info!

**Comment by vin-odoo** [comment]
@robodoo r+

**Comment by vin-odoo** [comment]
@robodoo rebase-ff

**Comment by Sehnde** [comment]
@tong-odoo could you r+ your forward-ports, please? It is blocking tests on the upgrade repository as @d-fence said.

**Comment by vin-odoo** [comment]
@Sehnde Everything has been r+ this morning, most of it is being staged at the moment.
Sorry for the derangement :pray:

**Pull request closed without merging**
