### PR TITLE
[CLA] signature for rigo1985 

### PR DESCRIPTION
**Pull request by rigo1985**
[CLA] Rigoberto Martínez

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for your signature but to be sure, do you plan to make a contribution to Odoo on github? We usually merge the CLA at the same time of the first contribution

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it has been integrated into Odoo at revision https://github.com/odoo/odoo/commit/c0889a076326d74663fa6c975b86de5df15706ec.
Future pull requests made on odoo will be validated by the runbot.
Regards

**Comment by rigo1985** [comment]
Hello, I am trying to contribute to the community in locating canada but
they ask me to sign CLA before. Please, I just updated today and I still do
not see my CLA in the github/odoo. Would you be so kind as to tell me what
to do?

my push https://github.com/OCA/l10n-canada/pull/92

2016-12-08 9:51 GMT-05:00 Martin Trigaux <notifications@github.com>:

**Comment by Yenthe666** [comment]
Hi @rigo1985,

It has been integrated here https://github.com/odoo/odoo/commit/c0889a076326d74663fa6c975b86de5df15706ec and it is located here https://github.com/odoo/odoo/blob/8.0/doc/cla/individual/rigo1985.md

Regards,
Yenthe

**Comment by mart-e** [comment]
@rigo1985 the CLA for Odoo is not the same as the one for the OCA. Different organisation, different rules :)

**Pull request merged**
