### PR TITLE
[FIX] account: aged partner report

### PR DESCRIPTION
**Pull request by nim-odoo**
Let's consider an aged partner balance with a period of 30 days as of
2019-02-08. The specific dates used in the report are:

``` python
bisou = datetime.strptime('2019-02-08', "%Y-%m-%d").date()
for x in [0, 30, 31, 60, 61, 90, 91, 120, 121]:
    print(x, bisou + relativedelta(days=-x))

0   2019-02-08
30  2019-01-09
31  2019-01-08
60  2018-12-10
61  2018-12-09
90  2018-11-10
91  2018-11-09
120 2018-10-11
121 2018-10-10
```

However, the current periods generated are incorrect:

```
{'name': '0-30', 'stop': '2019-02-08', 'start': '2019-01-09'}
{'name': '30-60', 'stop': '2019-01-08', 'start': '2018-12-09'}
{'name': '60-90', 'stop': '2018-12-08', 'start': '2018-11-08'}
{'name': '90-120', 'stop': '2018-11-07', 'start': '2018-10-08'}
{'name': '+120', 'stop': '2018-10-07', 'start': False}
```

There is a clear inconsistency between the name of the period and the
date used. Moreover, the name is misleading: 0-30 includes the -0 date,
while 30-60 doesn't include the -30 date.

After the fix, the name and the periods are consistent:

```
{'name': '0-30', 'stop': '2019-02-08', 'start': '2019-01-09'}
{'name': '31-60', 'stop': '2019-01-08', 'start': '2018-12-10'}
{'name': '61-90', 'stop': '2018-12-09', 'start': '2018-11-10'}
{'name': '91-120', 'stop': '2018-11-09', 'start': '2018-10-11'}
{'name': '+120', 'stop': '2018-10-10', 'start': False}
```

opw-1886633

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
@qdp-odoo I'm surprised this wasn't reported before since the report dates are clearly incorrect. However, not sure we should change the period names, although IMHO, the corrected ones are more consistent.

**Comment by nim-odoo** [comment]
ping @qdp-odoo

**Comment by qdp-odoo** [comment]
foutre?

**Comment by nim-odoo** [comment]
j'achète un "a"

**Comment by qdp-odoo** [comment]
Image of jacheteuna

**Comment by qdp-odoo** [comment]
praline

diff looks ok to me.

**Comment by nim-odoo** [comment]
no, it's not ok :-) I noticed that the commit  e095733 is not using the appropriate dates. I will go back to my original solution.

**Comment by qdp-odoo** [comment]
wait... what?

**Comment by nim-odoo** [comment]
So the dates:
```
0   2019-02-08
1   2019-02-07
30  2019-01-09
31  2019-01-08
60  2018-12-10
61  2018-12-09
90  2018-11-10
91  2018-11-09
120 2018-10-11
121 2018-10-10
```

My commit uses the dates:

```
{'name': '1-30', 'stop': '2019-02-07', 'start': '2019-01-09'}
{'name': '31-60', 'stop': '2019-01-08', 'start': '2018-12-10'}
{'name': '61-90', 'stop': '2018-12-09', 'start': '2018-11-10'}
{'name': '91-120', 'stop': '2018-11-09', 'start': '2018-10-11'}
{'name': '+120', 'stop': '2018-10-10', 'start': False}
```

The commit e095733a3a31cb77cd062e12ab39c1095403d38c uses:

```
{'name': '1-30', 'stop': '2019-02-06', 'start': '2019-01-08'}
{'name': '31-60', 'stop': '2019-01-07', 'start': '2018-12-09'}
{'name': '61-90', 'stop': '2018-12-08', 'start': '2018-11-09'}
{'name': '91-120', 'stop': '2018-11-08', 'start': '2018-10-10'}
{'name': '+120', 'stop': '2018-10-09', 'start': False}
```

Since the query uses `BETWEEN`: https://github.com/odoo/odoo/blob/d211ea5f7c93f91c4d90748894529f063d490bcb/addons/account/report/account_aged_partner_balance.py#L116

which is inclusive (https://www.postgresql.org/docs/10/static/functions-comparison.html), I think my solution is the right one.

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
