### PR TITLE
[FIX] website: allow to update cron

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
Before this commit, it is not possible to archive or modify this commit.

@JKE-be 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by JKE-be — COMMENTED** [review]
While the idea is OK.
Change in stable will have impact on next migration.
If we update the method called in this code, we need to add a script of migration one record is in no_update.
I already see some tasks about this cron/feature so, let see the @tde-banana-odoo opinion

**Comment by fmdl** [comment]
@JKE-be last two week we have merge this PR on an other cron : https://github.com/odoo/odoo/pull/69234

**Comment by JKE-be** [comment]
yes, I see... But the situation is not the same.
Function name is generic and probability to be renamed low and no task at this moment about it.

Since website_visitor is in new and some refactoring are currently specified on it, we need to take this in consideration before to r+ this kind of changes.

So wait and see reply of @tde-banana-odoo ...

**Comment by fmdl** [comment]
@JKE-be thanks for you return.

**Comment by tde-banana-odoo** [comment]
Hello,

"Before this commit, it is not possible to archive or modify this commit". (cron I supppose) ? Why ? You mean that at upgrade it comes back ? Indeed we think this cron is important to clean database from visitors as we have plenty of them that add no real value.

Setting is as noupdate="1" is feasible. It seems it did not change since it was added so it's ok. It is likely to change before v15 but we will force its update at migration if necessary.

However I don't see the point of removing "active=True"; if there is no update it should not be necessary anymore. Could you explain a bit more ?

Finally, it seems commit message lacks an explanation of why you do the change (see https://www.odoo.com/documentation/14.0/reference/guidelines.html#commit-message-structure ) .

Cheers !

**Pull request closed without merging**
