### PR TITLE
[FIX] Inheritance of purchase_order_change by preparing data dictionary

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
**Description of the issue/feature this PR addresses:**
In order to add fields into order lines and invoice lines and allow the new field's values to be passed from purchase order lines to invoice lines, `purchase_order_change` need to be overridden. It cannot be done with the current behavior, unless by rewriting the whole function.

**Current behavior before PR:**
Data dictionary filled inside the function `purchase_order_change` with no possibility of inheritance.

**Desired behavior after PR is merged:**
A function `_prepare_invoice_line_from_po_line` that fills the data dictionary and returns it. So it can be easily inherited to add value(s). 
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ThomasBinsfeld** [comment]
@sbidoul

**Comment by ThomasBinsfeld** [comment]
@adrienpeiffer

**Comment by sbidoul** [comment]
:+1: 

CCLA is here: https://github.com/odoo/odoo/pull/12810

@odony I hope this simple refactoring can be accepted in stable.

The use case is adding additional analytic dimensions (eg a department field) that we want to propagate from the purchase order down to the account move line.

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by odony** [comment]
@sbidoul Yes, the idea looks ok to me in 9.0 :-)
@ThomasBinsfeld Any particular reason you left out the [`account_id` part](https://github.com/acsone/odoo/blob/2909e5f4aa3b030352b4a347bdee0b66fdf631d5/addons/purchase/invoice.py#L71-L73) out of the _prepare method?

**Comment by odony** [comment]
Additional note for the merge: after merging this PR we should also refactor the code introduced by commit 564fda4d8f557734109520128061f05cbeec6897 : there is already an appropriate `onchange` on ` product_id`  in account_asset to copy the asset category, so instead of introducing an extra method `set_additional_fields()` we should make the `purchase_order_change` method in purchase explicitly trigger the various onchange methods bound to the `product_id` field (Probably *before* setting the other field values, to avoid side effects). This should be doable with the `onchange()` method of the ORM, perhaps combined with `_onchange_spec()` .
This should allow us to drop the `set_additional_fields()` stuff.

**Comment by ThomasBinsfeld** [comment]
@odony Sorry for the delay, I integrated the account_id part.

**Comment by adrienpeiffer** [comment]
@odony Any other feedback about this one ?

**Comment by adrienpeiffer** [comment]
OPW 690733

**Comment by simongoffin** [comment]
Closed with d0bfcfd41dd4549f401be8b75ec49e800aa47fa7

**Pull request closed without merging**
