### PR TITLE
[IMP] website: Save one sql for all images on published record

### PR DESCRIPTION
**Pull request by Gorash**
The record is read directly in sudo, the prefetch is in the sudo
environment. When reading the other information there is no longer any
need to make a request.

### CODE REVIEW

**Comment by rdeodoo** [comment]
Sent the message a bit too quickly.
Is there a task about this perf improvement or is it just one you found while working on something else?

**Comment by Gorash** [comment]
@rdeodoo No, I don't know why it's always green. (I had not seen this performance test). Do I have to do a specific build?
There is no associated task, it is generic to performance, as soon as there is a possible optimization.

**Comment by Gorash** [comment]
@rdeodoo In fact in the tests, the image is not published, so it shows the 404 there is no obstruction.
I will add a test where it is published.

**Comment by rdeodoo** [comment]
Cool thank you for the explanation and the test, appreciated.
@robodoo r+

**Pull request closed without merging**
