### PR TITLE
[IMP] core: read_group: allow grouping by non-stored related fields

### PR DESCRIPTION
**Pull request by yelizariev**
In most cases, the only reason to mark a related field as stored is a need to group records by such field. With this commit we can make grouping without making column copy. It allows to save database size as well as resources needed to create and keep such duplicate up-to-date.

In fact, read_group supported non-stored related fields for ages, but it was limited to automatic related fields (inherits/delegate=True). So we only need to weaken constrain for groupby argument and add some extra joinings in _inherits_join_calc to give new feature to the world.

---

task-2155109

See also discussion in https://github.com/odoo/odoo/pull/66947

### CODE REVIEW

**Comment by yelizariev** [comment]
[In previous series](https://github.com/odoo/odoo/pull/66947):

image

**Comment by psevertson** [comment]
Awesome!
Is it possible to do something similar with sorting?
Currently it seems if you pass in a related field in the `order` parameter Odoo won't throw an error, but just ignores it

**Comment by psevertson** [comment]
> Awesome! Is it possible to do something similar with sorting? Currently it seems if you pass in a related field in the `order` parameter Odoo won't throw an error, but just ignores it

Actually, I was able to figure this one out now. Just had to override `_generate_order_by_inner()` using similar logic as was used in `_read_group_raw()`:
`field.store or field.related and field.related_field.store and field.column_type`

**Comment by ryv-odoo** [comment]
I am currently working on a complete refactor of read_group and this feature will be on it.

**Comment by kmagusiak** [comment]
> I am currently working on a complete refactor of read_group and this feature will be on it.

@ryv-odoo Do you think it will be available in Odoo 18?

**Comment by ryv-odoo** [comment]
> > I am currently working on a complete refactor of read_group and this feature will be on it.
> 
> @ryv-odoo Do you think it will be available in Odoo 18?

It is my highest priority feature right at the moment. I couldn't include it in the refactor, it wasn't possible at that time (API didn't cover the case properly). Then yes, it should be in the Odoo 18 after all.

**Pull request closed without merging**
