### PR TITLE
[FIX] calendar: fix duplicate feedback in the chatter activity done note

### PR DESCRIPTION
**Pull request by pyduf**
How to reproduce:
- install crm
- open a lead
- create an activity call or meeting (and schedule it in the calendar)
- mark it as done with a feedback

The activity log in the chatter contains the feedback twice and shouldn't.

The problem was caused by the synchronization of the event description with the related activities. When marking an activity as done, the event description is updated with the feedback which in turn update the activity note with the feedback. When logging the activity done in the chatter, the note and the feedback are logged leading to a duplicate feedback. We solve this by first logging the activity done in the chatter before updating the event description.

Task-3653088

### CODE REVIEW

**Comment by Odoonan** [comment]
Hello @pyduf

So to summarize, when there is feedback, when updating the description on the calendar.event , _sync_activities() will write it on the 'note' of the activity as well.

In the template message_activity_done, called in the super after the update, we have for the activity:
Summary
Feedback
Note

Which means we get:
Summary
Feedback
Note now including feedback

-> double feedback. Plus `<br>` in the formatting leading to the different display issues noted in the task pad.

So I think the solution of moving the super before the description update makes sense. However, it reverses a change done one month ago here https://github.com/odoo/odoo/pull/145781 Have you had a look?

Thanks for explanations and Cheers!

**Comment by pyduf** [comment]
> Hello @pyduf
> 
> So to summarize, when there is feedback, when updating the description on the calendar.event , _sync_activities() will write it on the 'note' of the activity as well.
> 
> In the template message_activity_done, called in the super after the update, we have for the activity: Summary Feedback Note
> 
> Which means we get: Summary Feedback Note now including feedback
> 
> -> double feedback. Plus `<br>` in the formatting leading to the different display issues noted in the task pad.
> 
> So I think the solution of moving the super before the description update makes sense. However, it reverses a change done one month ago here #145781 Have you had a look?
> 
> Thanks for explanations and Cheers!

Hello @Odoonan ,

Thanks for the review and having noticed that it was actually a revert of a previous PR.

@macr-odoo author of the PR you have mentioned has kindly explain me the reason. Thanks for that.

Explanation: This PR will revert the code of odoo#145781 (reversing the order of the call of super and the event description update in _action_done) that was introduced to solve the problem caused by odoo#144526 (introduced to delete the calendar event when its related activity is deleted which happens when marking as done an activity). As the PR odoo#144526 is now reverted by odoo#146288, the problem solved by odoo#145781 is not present any more and can then be reverted (by this PR). 
That’s why we weren’t able to reproduce the problem solved by odoo#145781 on the runbot of the PR while it was reverting odoo#145781.

So beside reverting some changes, this PR only add a comment explaining the order between the call of super and the update of the description event in _action_done.

**Comment by Odoonan** [comment]
@pyduf Ok I see it now, thanks for the explanation :p Greened

**Comment by tde-banana-odoo** [comment]
@robodoo r+

@pyduf you really deserve the title of ``Master Odoo Blame Archivist``, being able to link so much PRs reverting each other while not becoming mad is impressive :D .

**Pull request closed without merging**
