### PR TITLE
[IMP] purchase: inherit reference computation

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
This PR allow to modify the behavior of the computation of the invoice ref.

For my accountant the current behavior doesn't make sens :
- Create a new invoice
- Set the vendor Invoice ref (ex : FR20191012)
- Add a PO with vendor ref `PO209191`
--> the new invoice ref is `FR20191012, PO209191`
After that my accountant remove `, PO209191` ...

@qdp-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
ping @mart-e 
maybe for master ?

**Comment by mart-e** [comment]
@fmdl yes please, for this kind of purely code improvement patch, master is better
Thanks

**Comment by fmdl** [comment]
@mart-e in V13 there is this issue:
- create a new bill, select a partner, set `reference`
- now select a purchase_id (Auto_complete)
--> the reference is removed (see here : https://github.com/odoo/odoo/blob/13.0/addons/purchase/models/account_invoice.py#L62)

**Solution 1** (for V13 and master): re-introduce : https://github.com/odoo/odoo/blob/12.0/addons/purchase/models/account_invoice.py#L98

**Solution 2** (for master): create `partner_ref` and `reference` is a computed field `', '.joint([self.manual_reference] + self.mapped('purchase_order_line.order_id.partner_ref)`

What do you think ?

**Comment by qdp-odoo** [comment]
well, I think we can consider that the current behavior wasn't intended, and is a side effect of the big refactoring we made in 12.4. Therefore, I'm in favor of changing that in 13.0 to get back the behavior we had in 12.0.

@nim-odoo Any veto?

**Comment by fmdl** [comment]
https://github.com/odoo/odoo/pull/52222

**Pull request closed without merging**
