### PR TITLE
[IMP] sale_timesheet: improve generic UX

### PR DESCRIPTION
**Pull request by kcv-odoo**
Purpose of this PR is to do generic improvement in timesheet app.

So, in this PR:
- add new filters for different invoice types in the timesheet search view.
- add demo data for different invoice types in the timesheet.

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work. 🙂

**Review by IT-Ideas — APPROVED** [review]
Thanks 🙂
It seems that there is a conflict to solve.

**Comment by IT-Ideas** [comment]
@robodoo rebase-ff

**Review by IT-Ideas — APPROVED** [review]
Thanks 🙂 
@robodoo r+

**Pull request closed without merging**
