### PR TITLE
[FIX] rating: Wrong template style

### PR DESCRIPTION
**Pull request by abz-odoo**
What are the steps to reproduce your issue ?

    1. Go to helpdesk/configuration/stages
    2. Add rating email template to Solved
    3. Change state of a ticket to Solved
    4. Go to Technical/messages and open the sent message

What is currently happening ?

    The template is not displayed correctly

opw-2476485

### CODE REVIEW

**Comment by abz-odoo** [comment]
@nle-odoo

**Review by nle-odoo — APPROVED** [review]
since there doesn't seem to be a SCSS file in the module it seems alright if this is necessary

but I am not sure `!important` is necessary, it would only be necessary if we have !important in the SCSS which doesn't seem to be the case.

you can merge after removing it (or checking why this would be necessary):

robodoo delegate+

**Comment by abz-odoo** [comment]
robodoo r+

**Comment by nle-odoo** [comment]
fw-bot up to 13.0

**Pull request closed without merging**
