### PR TITLE
[13.0]test case for the inherits losing value if invalidate_cache cal…

### PR DESCRIPTION
**Pull request by bizzappdev**
Proof and test case for issue #76946

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@rco-odoo bug

**Comment by yelizariev** [comment]
Thank you for the PR. 
It now looks more as misusing of the method `invalidate_cache`. Maybe I didn't check #76946 carefully

Built-in modules has `flush` before calling it, e.g.
https://github.com/odoo/odoo/blob/d0d9c0a8f8e35fbd9624d934a8ca6152677fbd3e/addons/product/models/product_pricelist.py#L587-L588


The issue #76946 may be still valid, though. Let's discuss there

**Comment by yelizariev** [comment]
Maybe write a test closer to the problem described in #76946  ?  I.e. without direct using of `invalidate_cache` ?

**Comment by bizzappdev** [comment]
> Maybe write a test closer to the problem described in #76946 ? I.e. without using `invalidate_cache` directly?

the main problem is from multiple write method of odoo it has been already used.
E.g 
https://github.com/odoo/odoo/blob/13.0/addons/product/models/product.py#L338
https://github.com/odoo/odoo/blob/13.0/addons/product/models/product_pricelist.py#L578

that is causing the problem. so if we have an inverse method which is updating product.pricelist.item then it will be calling invalidate_cache indirectly.
in test case, I do not have dependencies so I will have to call invalidate_cache directly. that is the main cause of the problem.

**Comment by bizzappdev** [comment]
> self.flush()

added self.flush()

**Comment by yelizariev** [comment]
WIth `flush()` it looks as a bug. Let's wait for ORM team comment

**Comment by bizzappdev** [comment]
> WIth `flush()` it looks as a bug. Let's wait for ORM team comment

No update? can any one check.

**Comment by rco-odoo** [comment]
@bizzappdev sorry, it fell under the radar...
I am having a look at it right now.

**Comment by rco-odoo** [comment]
See my proposed fix above.
I have chosen to not make the ORM robust to those inadequate cache invalidations, because this makes the code slow and much more complex.  I instead chose to fix the cache invalidations themselves.

**Comment by rco-odoo** [comment]
Fixed by #82901.

**Pull request closed without merging**
