### PR TITLE
[IMP] account: expanding the range of integer for sequence_number

### PR DESCRIPTION
**Pull request by hapa-odoo**
Before this commit
==================
If continue sequence is more than 10 digits then we had an error if below regex is applied on sequence_override_regex for journal . so converting column_type for sequence number from int4 to int8 inorder to support sequence_number of max 19 digits which was previously 10 digits only.

error: https://justpaste.it/aikhq
Regex :` ^(?P<prefix1>.*?)(?P<seq>\d*)(?P<suffix>\D*?)$`

### CODE REVIEW

**Comment by jva-odoo** [comment]
@odoo/rd-accounting when the max sequence is more than the int4 limit then we have an error.

this is possible that the value is more than 2147483647 when the sequence is never reset.

**Review by william-andre — COMMENTED** [review]
It doesn't make sense to have a number that big.
Can you give the opw in the commit message as well as some examples for the sequence being used?

Note that the ci/template is red

**Comment by jva-odoo** [comment]
> It doesn't make sense to have a number that big. Can you give the opw in the commit message as well as some examples for the sequence being used?
> 
> Note that the ci/template is red

use this regular expression ` ^(?P<prefix1>.*?)(?P<seq>\d*)(?P<suffix>\D*?)$`
and sequence `D1234567890123456`
where D is the prefix and 1234567890123456 is a sequence number

If you use sequence without giving regular expression then it's a trim sequence number!!!!

**Comment by william-andre** [comment]
This is purely theoretical, show me the ticket number

**Comment by william-andre** [comment]
Anyway, just change the regex to take a maximum of 10 digits in the `seq`

**Comment by william-andre** [comment]
Why are you using a feature that you are **not supposed to use** on a demo :facepalm:

**Comment by william-andre** [comment]
> if we set the max to 10 digits then the next number is wrong when its last 10 digits are 9

How many documents in a journal per second do you need to achieve that after 10 years?
`10^11÷(10×365×24×60×60) ≃ 317,0979`
Which business in the world creates that many documents **per second** in one single journal? Also add the fact that you can still change the journal.

Your solution is breaking the stable policy, adding hacks for absolutely no reason.

**Comment by jva-odoo** [comment]
I think it's 10^10÷(10×365×24×60×60) ≃ 31,70979
and 31 invoices per second.
there is any possibility that customers start using odoo after 10 years of its business start :wink: 

No issue we will fix this in V25 :stuck_out_tongue_closed_eyes:

**Comment by william-andre** [comment]
It is `((10^11)-1)÷(10×365.25×24×60×60)`, and if you have that amount of documents, you will have performance issues elsewhere way before having an issue here.

> there is any possibility that customers start using odoo after 10 years of its business start 

We almost never import all the accounting of the previous soft, only the balances. It would take ~~days~~~months to import that amount of `account.move`...

**Comment by jva-odoo** [comment]
not for importing data but starting sequence where it's left from old software

**Pull request closed without merging**
