### PR TITLE
[FIX] Prevent duplicate record id in moves to be assigned

### PR DESCRIPTION
**Pull request by wtaferner**
@jco-odoo @beledouxdenis 
Thank you for a quick merge as it is obvious from the code that this should have been done in the first place...

OPW-649296

### CODE REVIEW

**Comment by jco-odoo** [comment]
Ok to merge for me, but I wonder if it is not easier to do ids =
list(set(ids)) instead and whether the check could not have been done
before already.

**Comment by xmo-odoo** [comment]
Why not just make `to_assign_moves` a set? Is order important?

**Comment by wtaferner** [comment]
Well, this could be another way to resolve this but as I like speaking code and to fix it where the issue has its origin and not where we want to prevent a foggy implementation to be fixed later, I decided to do it like that but it is up to you guys...I can also put a  ```ids = list(set(ids))``` in https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L907 or as @xmo-odoo suggested to use a set right from the start and make sure it will be translated later to a list again...

**Comment by jco-odoo** [comment]
The order can be important...

**Comment by wtaferner** [comment]
Anything to do on my side before it can be merged?

**Comment by wtaferner** [comment]
@jco-odoo 
OPW Ticket was closed/cancelled (still don't understand why a valid ticket is cancelled instead of assigned and marked as done after completion) as Denis said it will be reviewed (this should be done), and potentially merged directly on Github (to be done)...thank you :-)

**Comment by wtaferner** [comment]
@jco-odoo 
ping, this little fix wants to be merged ;-)

**Comment by jco-odoo** [comment]
I checked again and there seems to be no reason not to use a set.  But is there any other reason we do this besides performance reasons?  If it sets the state twice to assigned, that does not change much?

**Comment by wtaferner** [comment]
I guess a set will not change the performance much in this case...it is just another way to handle duplicate assignments.

@jco-odoo 
I would not mind to author the change to a set myself if you want to have a set...I feel a little bit high-checked for my contribution and bugfix if you commit and author (https://github.com/odoo-dev/odoo/commit/d5e45668ecb8067c1e17ad17af339978b106ec6e) yourself after one month without progress and guidance. Anyway, as long it is fixed finally, I will not whine if you do it like that without courtesy reference. Ask Denis how he would handle such a bugfix and PR.

**Pull request closed without merging**
