### PR TITLE
Optimization of settings atrs to current thread.

### PR DESCRIPTION
**Pull request by heckad**
No needed call slow threading.current_thread() on evry arg setting.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for you patch but it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by Xavier-Do** [comment]
Hello

As far as I remember we took a quick look at the current_thread() implementation and it was quite light, but I may be wrong about that. 
Could you explain why you consider it as slow?
After a quick testing, I have not more than twice the time of an access to a stored current_thread compared to the threading.current_thread() method:

``` python
import time
import threading 

ct = threading.current_thread()
def perfs(func, iter = 10000000):
    init = time.time()
    for i in range(0, iter):
        func()
    print('Finished %s in %s s' % (iter, (time.time()-init)))

def current_thread():
    return ct
    
perfs(threading.current_thread)
perfs(current_thread)

```
Results:
```

Finished 10000000 in 1.65838980675 s
Finished 10000000 in 0.879067182541 s



```
I don't mean that your suggestion is wrong but I'd like to understand why you consider that current_thread() is "slow" and if you have an example use case.

**Comment by heckad** [comment]
Function `threading.current_thread` gets value from the dict. Good practice to get ref to the value and use this ref for manipulating them, not to get it from dict for manipulation. It`s just faster.

**Comment by mart-e** [comment]
Thanks for the clarification. It makes no noticable difference for the performance but is a nice code cleaning.

@robodoo r+

**Comment by mart-e** [comment]
robodoo rebase-ff

**Pull request closed without merging**
