### PR TITLE
[FIX] website: correctly check write rights of website.page

### PR DESCRIPTION
**Pull request by rdeodoo**
Commit [1] allowed restricted editor to use the optimize seo dialog:
- When they have write access on the record, they can fill the form and save changes
- when they don't have the write access, the form is in readonly and a warning is shown to explain it.

But a mistake was made: the restricted editor, when opening the SEO
dialog on a website.page, would receive an access error directly,
instead of the expected readonly SEO dialog without a save button.

Step to reproduce:
- Login with a restricted editor with no extra rights
- Go to / homepage
- Open the optimize seo dialog
- An access right error is shown

[1]: https://github.com/odoo/odoo/commit/891162574eead15cf64a4f934e5f12346cbcfbbf

### CODE REVIEW

**Comment by rdeodoo** [comment]
@qsm-odoo This should fix the weird case (which was just wrong) you mentioned about website.page access error.
cc @JKE-be 

Imo, the check access method should consider the inherits models when calling those method on a model. If model A inherits model B, modela A **is** also model B, it does not make sense to consider that you model B is editable if model A is not IMO.

**Comment by JKE-be** [comment]
Pas sur... Typiquement ici, ma next step et d'ecrire en sudo sur l'ir ui view si tu as les droits sur la website.page car on ne veut pas donner justement des droits sur ir.ui.view.
Donc je dirais que ceci va a l'opposer de ce qu'on voudrait au final :fearful: 

mtnt ca sera surement de la custo ou pas en 17... donc si tu veux le bloquer en standard :thinking: ... mais a terme ce code sera surement a retirer...

**Comment by rdeodoo** [comment]
The issue is that then, the SEO dialog form view is fully editable, and when you save it raises an access error. This is not an acceptable behavior, it would be like being able to edit a page, and once you are done and try to save, it just tells you you can't edit the page.

I guess it does not fit the needs of internal where you would like to go with a custom access rights policy regarding pages and views but.. That's imo the way to go.

Note that apart from this (which is not really related in the end), I am still waiting for feedback from the framework-py about 
> If model A inherits model B, modela A is also model B, it does not make sense to consider that you model B is editable if model A is not IMO.

Imo, `check_access_rights/rules` should just fail here, without the diff of this PR (maybe not in stable).

**Comment by rdeodoo** [comment]
Finally, the debate about `inherits` can just be avoided: it's not needed here.
Somehow, my `Web Page Manager` ACL was corrupted in my local DB
image
It should have the designer group, not restricted :thinking: 

Code has been updated: it sudo the infos when no rights. The controller is protected, the sudo is just to read the seo data, which can't be modified later in the seo dialog anyway (will be shown as readonly, and write would fail)

**Comment by JKE-be** [comment]
@robodoo r+

**Pull request closed without merging**
