### PR TITLE
[REF] web,*: remove legacy NameAndSignature

### PR DESCRIPTION
**Pull request by aab-odoo**
This PR converts the portal SignatureForm widget into a Component.
This allows to remove the last usage of the legacy NameAndSignature
widget, which we thus remove.

As the jSignature lib is now only used by the NameAndSignature component
(the owl version), which is not accessible on a many screens. This commit thus
removes the lib and its extension from the bundles, and makes the
NameAndSignature component load it on demand.

Part of task~3439226

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by aab-odoo** [comment]
Hello @odoo/rd-security Is the location assignment here ok? The next url comes from the server.

**Comment by aab-odoo** [comment]
@xmo-odoo I introduced a redirect function. Could you check again?

**Comment by sdegueldre** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
