### PR TITLE
[FIX] POS : traceback for pos user want access session.

### PR DESCRIPTION
**Pull request by mep-odoo**
Task : https://www.odoo.com/web#id=710186&view_type=form&model=project.issue&action=609&menu_id=4720

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Have you found where the error comes from? What is the line failing? Do we need full access right or is a `sudo` enough to see the required company data ?
master or saas-14 ?

**Comment by mep-odoo** [comment]
Hi

it's a master bug.
when demo user has a manager or user want to access the pos session that time we face traceback of session. and only give write permission to access the required data.

**Comment by mart-e** [comment]
I know there is an access right issue, I asked where does it comes from. Have you investigate which call crash?

**Comment by mart-e** [comment]
After a bit of searching, I think it is due to a patch I merged at 99f365523bcdfb10e48d87d4f047c2504fb25872
The fix must be there, not in point of sale

**Pull request closed without merging**
