### PR TITLE
[FIX] Allow sorting tree view by ID field

### LINKED ISSUE #7459: Field ID can not be ordered in view tree
Impacted Version:
* 8.0

Steps to reproduce:
* To edit any tree view
* To add field ```id```
* Click in column ```ID``` in tree view

Current Behavior:
* It can not ordered by ``` ID ``` 

Expected Behavior:

* To be able order by ``` ID ```

I made video,
https://youtu.be/CupGv3nEEH8

### PR DESCRIPTION
**Pull request by andreparames**
Fixes #7459

### CODE REVIEW

**Comment by andreparames** [comment]
It seems the runbot failed with an unrelated problem (Timeout?), can anyone restart the test?

**Comment by xmo-odoo** [comment]
@andreparames you should be able to do it by going to the list, clicking the gear dropdown then Rebuild. I've launched a rebuild.

OTOH @rco-odoo I think this bit of code could be removed entirely with the new API (maybe implicitly adding id to the list of fields fetched if necessary) given id is now a real field automatically added to all models no?

**Comment by andreparames** [comment]
Thanks @xmo-odoo

**Comment by nle-odoo** [comment]
Hello, 


It should be solved in 8.0 with commit 0920c2fae06. At first your fix seemed the best but after xmo comment I applied his suggestion.

Still, thanks for your contribution.

**Comment by andreparames** [comment]
Oh, I'm fully in favour of any solution that reduces complexity. Thanks for the rapid response,

**Pull request closed without merging**
