### PR TITLE
[FIX] web: typo in bugfixes

### PR DESCRIPTION
**Pull request by niyasraphy**
typo in bugfixes in web module

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
or should we change it to "Guaranteed bug fixing", looking for guidance.
thanks

**Comment by niyasraphy** [comment]
hi @Feyensv ,
if you have time, can you review this.
thanks

**Comment by Feyensv** [comment]
Not for me, and not really convinced by the change tbh.

**Comment by brboi** [comment]
cc @bouvyd ?

**Comment by niyasraphy** [comment]
hi @bouvyd ,
if you have time, can you review this.
thanks

**Comment by niyasraphy** [comment]
ping @bouvyd

**Pull request closed without merging**
