### PR TITLE
Update l10n_ro master series, with the modifications from V8.

### PR DESCRIPTION
**Pull request by feketemihai**
I've updated the cart of accounts, chart of taxes, account.tag for taxes, fiscal position just like V8 merge...i used the same id's in case of migration to be easier.

@mart-e

### CODE REVIEW

**Comment by mart-e** [comment]
@qdp-odoo could you confirm it's fine for new localisation formats.
@feketemihai no need for CLA or `partner_view.xml` patch as it was done in 8.0 and will be forward ported to master.

**Comment by feketemihai** [comment]
I will leave like that for the moment and modify if @qdp-odoo has some comments, if not i wil lremove the partner_view modifications.

**Comment by qdp-odoo** [comment]
i didn't test, but i suppose you did... it seems correct so far as the diff is concerned.

**Comment by feketemihai** [comment]
@qdp-odoo I tested and so far it's ok with the new requirements in legislation and accounting, but i have one qustion about the account.account.tag model, i didn't create yet any tags for accounts, only for taxes...is it ok to create tags for the previous view accounts, and to assign the account tot the corresponding tag, to have kind of the same structure as in V8, since the legislation requires to print the trial balance with parent accounts and sum the results?

**Comment by feketemihai** [comment]
@qdp-odoo And one more thing, in master i never saw the a condition to view the default sale tax and default purchase tax in the wizard of installing the chart of account, only after to go in configuration, is it something that i miss?

**Comment by qdp-odoo** [comment]
@feketemihai :
"is it ok to create tags for the previous view accounts,"
=>  well, actually you might better create a report named 'Trial Balance' and define the account.financial.report.line to reflect the previous parent-children structure.
"i never saw the a condition to view the default sale tax and default purchase tax in the wizard of installing the chart of account"
=> that's because the localization modules since v9 will always generate directly the objects from the templates without asking any option (but you're able to change in the settings after the installation). The idea is to speed up the installation process by removing that often-useless-extra-step.

**Comment by feketemihai** [comment]
@qdp-odoo Ok...for the default sale tax and purchase tax i already set up the lowest sequence to the most common ones...for the chart of accounts i will have a look how to configure better the report, directly from the financial reports...so if it's for you, you can merge this one and i will make another pr for this "problem".

Thanks.

**Comment by qdp-odoo** [comment]
yes it's fine for me.  @mart-e can you process this PR when you have time?

thanks

**Comment by mart-e** [comment]
always ! merged at 6113b6364c0dc3ad849505b00104dea3b4ac775f
Thank you

**Pull request closed without merging**
