### PR TITLE
Master alipay payment integration nla

### PR DESCRIPTION
**Pull request by nla-odoo**
Added new payment acquirer - Alipay

Task: https://www.odoo.com/web#id=40221&view_type=form&model=project.task&action=333&active_id=131&menu_id=4720

Pad: https://pad.odoo.com/p/r.78a5569fb2b013f8c39d91e388adb23f

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jeffery9** [comment]
nice

**Comment by mba-odoo** [comment]
LGTM

**Comment by dbo-odoo** [comment]
@robodoo r+

**Comment by mreficent** [comment]
@nla-odoo 
Could any of you check please https://github.com/odoo/odoo/pull/33152? If it is wrong, then close it, obviously.

**Pull request closed without merging**
