### PR TITLE
[FIX] l10n_es_edi_sii: remove call to _post_invoice_edi

### PR DESCRIPTION
**Pull request by Arnaud-Sibille**
https://github.com/odoo/odoo/commit/a66ac063e01afbcc5bec2e6f56da81340b28aaa7 introduced the use of `_post_invoice_edi` method on `account.edi.format`, as it is a forward port of a fix in v15, where this method still existed.
But it doesn't exist anymore in v16, due to https://github.com/odoo/odoo/commit/0e5626ca5126e6fea7fb95b694229948540764d7.

The fix is to use the method specific to the spain edi: `_l10n_es_edi_sii_post_invoices`

opw-3604907

### CODE REVIEW

**Comment by Arnaud-Sibille** [comment]
So this method is defined in `l10n_ec_edi` and `l10n_it_edi`, but I found 2 other reference to that method where I don't think it is defined:

This is weird as it was pushed like that (maybe he began writing the PR before the refactor):
https://github.com/odoo/odoo/blob/16.0/addons/l10n_es_edi_tbai/models/account_edi_format.py#L104
it also uses `_cancel_invoice_edi` that I also think is deprecated

This one, not sure what it does, it isn't a call:
https://github.com/odoo/odoo/blob/16.0/addons/account_edi/tests/common.py#L19


Should I  make the changes?  Pretty sure I should for `l10n_es_edi_tbai` but for the test in `account_edi`, I don't know

**Comment by JulienAlardot** [comment]
Could you link the commit instead of the PRs?

**Comment by Arnaud-Sibille** [comment]
> Could you link the final commits instead of the PRs?

done!

**Review by JulienAlardot — APPROVED** [review]
LGTM @jbw-odoo

**Pull request closed without merging**
