### PR TITLE
[FIX] web_kanban: results concatenated when fast search

### PR DESCRIPTION
**Pull request by nle-odoo**
Since commit ffb8bf3 when doing fast succeeding kanban view searches,
several results could be concatenated together (if the next searches are
started before results are displayed).

This fix clears the kanban zone before the new received search results
are displayed.

opw-632525
##### _Note :_

at first I fixed it with : 

``` patch
diff --git a/addons/web_kanban/static/src/js/kanban.js b/addons/web_kanban/static/src/js/kanban.js
index b04f8d7..6643256 100644
--- a/addons/web_kanban/static/src/js/kanban.js
+++ b/addons/web_kanban/static/src/js/kanban.js
@@ -360,6 +360,7 @@ instance.web_kanban.KanbanView = instance.web.View.extend({
             }).done(null, function() {
                 def.reject();
             });
+            return def;
         });
         return def;
     },
```

with this `add_group_mutex.exec` did its thing and only one request was done at a time, but it goes back to the behavior done previous to commit ffb8bf3 which seems to say this can cause issues : 

> #### [[FIX] fixes many issues with the various views](https://github.com/odoo/odoo/commit/ffb8bf31af57cf845796acc90fa0f8b8b7d14de3)
> 
> the views don't always return a proper promise, or were
> somewhat fragile and broke with the changes in the view
> manager.

so the fix in this pull request only clears the kanban groups a second time when data are received.

``` patch
@@ -344,6 +344,7 @@ instance.web_kanban.KanbanView = instance.web.View.extend({
         this.add_group_mutex.exec(function() {
             self.do_clear_groups();
             self.dataset.read_slice(self.fields_keys.concat(['__last_update']), { 'limit': self.limit }).done(function(records) {
+                self.do_clear_groups();
                 var kgroup = new instance.web_kanban.KanbanGroup(self, records, null, self.dataset);
                 if (!_.isEmpty(self.dataset.ids) && (self.dataset.index === null || self.dataset.index >= self.dataset.ids.length)) {
                     self.dataset.index = 0;
```

@ged-odoo is it alright?

### CODE REVIEW

**Comment by beledouxdenis** [comment]
I would have preferred your first fix actually, since this is clearly a race condition (as the issue appears if you make a new search too quickly, but not if you wait a bit), that should be corrected with a change in the deferred rather than a change to add the clear thing in a new place.

Besides, I believe you do not break what @ged-odoo achieved in commit ffb8bf31af57cf845796acc90fa0f8b8b7d14de3, since you do not remove the `return def` two lines below yours, introduced by him within this specific commit.

@ged-odoo, am I right ?

**Comment by ged-odoo** [comment]
totally correct Denis. this is a case where you should fix the cause, not the symptom.  I broke the mutex, and your first fix corrects that mistake.

**Comment by nle-odoo** [comment]
Thanks.

I updated the pull request with the first fix.

**Comment by beledouxdenis** [comment]
Fine for me :+1:

**Comment by nle-odoo** [comment]
should be fixed in saas-6 since commit odoo@203508e551bc4

**Pull request closed without merging**
