### PR TITLE
[9.0][IMP] pos_restaurant: Make the widgets in the floors.js file extendable.

### PR DESCRIPTION
**Pull request by AyoubZahid**
**Description of the issue/feature this PR addresses**: 
- The tableWidget and the floorscreenwidget in the module pos_restaurant can't be extended .

**Current behavior before PR**: 
- the TableWidget  and the FloorScreenWidget can't be accessed for future extention

**Desired behavior after PR is merged**: 
- made a return of the widgets of the floors.js file
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by AyoubZahid** [comment]
Thank you @ged-odoo .
is this pull request still not approuved to be merged?

**Comment by ged-odoo** [comment]
@AyoubZahid it is almost ok, except the indentation. please use spaces instead of tabs to align your exports (just copy the indentation of most other files), ping me, and i will merge it

**Comment by AyoubZahid** [comment]
@ged-odoo , ok alignement fixed.

Thank you .

**Comment by ged-odoo** [comment]
merged in 9.0 (commit https://github.com/odoo/odoo/commit/5da86716be9772226297026f9892bfbd14a4ccf1)

**Pull request closed without merging**
