### PR TITLE
[IMP] tests: add the possibility to not check required field in Form …

### PR DESCRIPTION
**Pull request by lobaudoux**
…emulator

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
why

**Comment by lobaudoux** [comment]
Hello @xmo-odoo , this is intended to be used by `account_invoice_extract` : https://github.com/odoo/enterprise/pull/20039 as in this module we do not care if the fields are required or not, we're only using the `Form` emulator to activate the different `onchange`'s.
If one of the required fields is left blank by the OCR, it will prevent it from saving the `Form`, that's annoying.

I was going to ask your opinion on it, but you already found the PR !

**Comment by xmo-odoo** [comment]
> Hello @xmo-odoo , this is intended to be used by `account_invoice_extract` : [odoo/enterprise#20039](https://github.com/odoo/enterprise/pull/20039) as in this module we do not care if the fields are required or not, we're only using the `Form` emulator to activate the different `onchange`'s.
> If one of the required fields is left blank by the OCR, it will prevent it from saving the `Form`, that's annoying.

Wouldn't it be better to define a view for that process which doesn't flag the fields as required in the UI? Surely the OCR knows what fields it *can* provide so it'd make more sense than to grab a random view, and nowadays the onchange bindings are defined server-side (by default) so it's not like the setup of the view should be too important.

Because I would think actual ORM-side required fields should block the saving of the form no?

> I was going to ask your opinion on it, but you already found the PR !

Blame @Xavier-Do

**Comment by lobaudoux** [comment]
> Wouldn't it be better to define a view for that process which doesn't flag the fields as required in the UI? Surely the OCR knows what fields it _can_ provide so it'd make more sense than to grab a random view, and nowadays the onchange bindings are defined server-side (by default) so it's not like the setup of the view should be too important.

We went for that solution at first, but it has some maintainability issue. Other modules that are extending the `account.move` model will need to be aware that our view exists and update it. Otherwise, we might run into `_field_ was not found in the view` errors when saving the `Form`.

> Because I would think actual ORM-side required fields should block the saving of the form no?

If I'm not mistaken, this commit should only prevent checks on required fields defined in the view. If a field is required on the ORM level, it should still crash ?

We fixed this in a different way for v14 (not merged yet though), you might find it interesting : 
https://github.com/odoo/enterprise/pull/20005

**Comment by xmo-odoo** [comment]
> > Because I would think actual ORM-side required fields should block the saving of the form no?
> 
> If I'm not mistaken, this commit should only prevent checks on required fields defined in the view. If a field is required on the ORM level, it should still crash ?

Well yes and no, it will still crash but it'll crash after having hit the ORM (and possibly only for schema-level required fields aka `NOT NULL`). The modifiers are the merge of the ORM and view data, so an ORM-level flag is reflected in the modifiers and thus currently checked by the `Form` and triggering an `AssertionError`.

> We fixed this in a different way for v14 (not merged yet though), you might find it interesting : odoo/enterprise#20005

Though it's more code, I do prefer that version using dedicated subclasses.

Note that there are alternative implementations of the idea as well:

* override `get_modifiers` to statically return `False` when queried for `required`
* override `_process_fvg` to set the modifier to `False` after processing (or pop it), this one is nice because you don't have to extend the subclass: O2M subviews are processed eagerly at the toplevel.

**Comment by lobaudoux** [comment]
Ok, thank you very much for your help, we'll stick to the subclasses solution then.
Have a nice day !

**Comment by lobaudoux** [comment]
Closed as an alternative solution  will be used, see discussion above and odoo/enterprise#20005.

**Pull request closed without merging**
