### PR TITLE
[FIX] stock_account: use stock input account in vendor bill lin…

### PR DESCRIPTION
**Pull request by MihranThalhath**
…es only if valuation method is real_time

When the company is using anglo-saxon accounting, stock input account is being used as default account
im vendor bill lines. This should not be the case if the valuation method is not real time since
the stock input account selection will be hidden in product category view and user will get confused
in such cases.

fixes #83049

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gdgellatly** [comment]
Please can we have someone functional really look at this. I've done Odoo for a long time, have presented at Odoo XP on advanced anglo saxon issues and have written a popular module for handling the corner cases of anglosaxon accounting in vendor bills and financial situations https://github.com/odoonz/odoonz-addons/tree/14.0/account_anglosaxon_financial. 

The correct fix IMO is not to change the vendor bill lines, you will just play whack-a-mole. I'm not familiar with 15.0, maybe all the moles got whacked already. 

Anglo saxon accounting (which is a misnomer, it should really be called realtime stock accounting) only makes sense if realtime stock accounting is used. 

It is essentially the implementation of IAS2 for real time.  For me the fix is only (and arguably always, most of world has IAS2 now) enable AS when real time is enabled.

**Comment by Whenrow** [comment]
@MihranThalhath Hello. The anglo-saxon valuation is available only for real time valuation product. Your check should not solve anything unless we forget to filter realtime product sooner in the process of stock move validation.

**Comment by MihranThalhath** [comment]
> @MihranThalhath Hello. The anglo-saxon valuation is available only for real time valuation product. Your check should not solve anything unless we forget to filter realtime product sooner in the process of stock move validation.

Hi @Whenrow . The issue is that if you create a new product category once and change the valuation method to real time, select the stock input, output accounts etc and then again revert back to manual valuation. The stock input/output accounts gets hidden when valuation method is back to manual valuation. But the vendor bill will still use the stock input account from the product category, which in this case is hidden. The user will be confused in such scenarios. You can see [#83049](https://github.com/odoo/odoo/issues/83049) for exact steps to reproduce the same

**Comment by gdgellatly** [comment]
@Whenrow - he is right, you can do that setting and it will happen on the supplier invoice. In fact there are many other ways to trigger this incorrect account.

@MihranThalhath you are focusing on one wrong behaviour of a bad configuration and in fact the easiest one to fix. It just gets worse from there. Your PR only kicks the can to the next issue, I've had 10 years at it.  There is just no way to 100% get manual valuation and anglosaxon to work. 

However you can 'almost' make it work for mixed valuation if you set the input/output the same as expense/income on the category on non realtime. But for the same reason your fix is flawed, so is that configuration.

I would love for Odoo to hold a session with qualified stock accountants to go through Anglosaxon for either v16 or 17. The entire module is unnecessarily complex with the pace of modern trading businesses and the way they implement ERP. Even when it was initially proposed, while it made sense in theory, it missed opportunities for what really happens in practice and was really just a bolt on to prevent other issues in the existing stock accounting way back in v5.0.14 AFAICR. Don't get me wrong, it does OK, but it could be so much simpler and better, since EU has adopted IAS 2.  Especially on the sales side. 

But even on the purchase side, the gap is closing and 1 small change could make it nearly perfect from a reporting perspective.

**Comment by Whenrow** [comment]
I would rather change `_get_product_account()` to return stock valuation account only in case of `real_time` product. Adding `if product.valuation == ...` everywhere is too complex and could miss some places like 
https://github.com/odoo/odoo/blob/4b3d1b0a9f39b57e83323116f13f1d29f26175cf/addons/stock_landed_costs/models/stock_landed_cost.py#L181-L186

**Pull request closed without merging**
