### PR TITLE
[FIX][16.0] account: wrong field name on button_open_statement_lines

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
This is just a typo XD

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476** [comment]
@smetl Hi, could you have a look ?

**Comment by duong77476** [comment]
@william-andre Hi sir, could you take a look, just a wrong typo, i think i will be quick for you to look at

**Comment by duong77476** [comment]
Hi @RicGR98 Could you take a look please ?

**Comment by RicGR98** [comment]
> Hi @RicGR98 Could you take a look please ?

Hi, I've already forwarded it to the reviewers, it's up to @william-andre or @smetl to r+ (I don't have the rights)

**Comment by duong77476** [comment]
> > Hi @RicGR98 Could you take a look please ?
> 
> Hi, I've already forwarded it to the reviewers, it's up to @william-andre or @smetl to r+ (I don't have the rights)

Oh i see
@smetl @william-andre Hi , can you review, it doesn't take too much time because just a wrong field name

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
