### PR TITLE
[FIX] l10n_latam_invoice_document: manual taxes widget

### PR DESCRIPTION
**Pull request by zaoral**
### Description of the issue/feature this PR addresses:

Manual taxes widget in the invoice form view is broken.

### Current behavior before PR:

We notice this when testing Argentinian localization. [video](https://drive.google.com/file/d/1ThBsQJCMPOw0ho4UP60fAkyWJnsUAC9b/view)

### Desired behavior after PR is merged:

Now the widget is properly working, and the taxes are properly show taking into account the Argentinian rules for which taxes should be discriminate or not taking into account the issuer/receptor responsibility and type of document

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by zaoral** [comment]
Hi @jco-odoo @ren-odoo @jjscarafia 

This PR solves the problem with the manual taxes on the invoice.
Please Rubi, review can you make the functional test and let us know.

Best Regards!

**Comment by jjscarafia** [comment]
I've try it on runbot but I get the error:
`  File "/data/build/odoo/addons/l10n_ar/models/account_fiscal_position.py", line 16, in get_fiscal_position
    company = self.env['res.company'].browse(self._context.get('force_company', self.env.company_id.id))
AttributeError: 'Environment' object has no attribute 'company_id'`

Not sure what's going wrong, I see odoo use "self.env.company_id.id" on many places on odoo v13..

**Comment by ren-odoo** [comment]
> "/data/build/odoo/addons/l10n_ar/models/account_fiscal_position.py", line 16, in get_fiscal_position company = self.env['res.company'].browse(self._context.get('force_company', self.env.company_id.id)) AttributeError: 'Environment' object has no attribute 'company_id'

@zaoral I'm getting the same error than @jjscarafia here Is how you can reproduce it:

https://drive.google.com/file/d/1olJmpeW8WyLXP5kLwbOOdx_etZLpI65Y/view

Note: I was able to test the manual tax duplicating one of the existing vendor bills as you can see in the video.

**Comment by zaoral** [comment]
Hi @ren-odoo @jjscarafia  

Thank you for the review.

About the `AttributeError: 'Environment' object has no attribute 'company_id'` error, yes it was a misspelling error! is not `company_id` is just `company`. Here is the PR with the fix! https://github.com/odoo/odoo/pull/39292. Please can you go to that PR and test it?

About the manual taxes, @ren-odoo I see in the video that the manual taxes are working properly. Please could you give the Approve in order to merge this PR?

Best Regards!

**Comment by ren-odoo** [comment]
Hi @zaoral  
I just realized that in the video I shared before the amount on the manual tax wasn't not updated so I tested again an unfortunately when the amount is updated I keep getting the error:
 
https://drive.google.com/file/d/1oWARfjM6EvyJtPDU2Y0GusmFmfF7JFvr/view

Can you help me to take a look, please?

**Comment by zaoral** [comment]
ping @jco-odoo @ren-odoo

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
