### PR TITLE
[FIX] website: fix input default value translation

### PR DESCRIPTION
**Pull request by xO-Tx**
Issue:

- Go to website > edit mode > add a form
- On one of the form fields, add a default value > save
- Change language > translate > the input has html code shown as value.

On translation editor, the default html values we get from translation mapping
(see 'ir.translation' > _get_terms_mapping()) are used on the editor's JS code
(beforeEditorActive()) to set the right translatable attributes values on DOM
elements, and since the use of jQuery "attr()" won't update the "value" property
on inputs, we force it to replace the default translation html.

Remark: the same issue will prevent updating the "value" property on the input
when "AttributeTranslateDialog" is used for translation.

task-3042522

### CODE REVIEW

**Comment by rdeodoo** [comment]
One of this commit is done in 14.0 at https://github.com/odoo/odoo/pull/106198 and can be removed here, no?
We will just need to merge the 14.0 one before this one if I did not miss anything?

**Comment by xO-Tx** [comment]
@rdeodoo sorry for the delay! I had to check other stuff before coming back to this one:

**On the PR on [14.0]** we have (Remark: we only translate inputs placeholders!):

A- The fix linked to the task (To be able to interact with elements with translatable attributes in the "translate" mode...).

B- A fix I added while checking the main issue: The translation terms (`<span...>term</span>`) are added as values of the placeholder (for a moment) until the JS code from the editor adapt them... so the goal was to hide them using CSS.

**On the PR here on [15.0]** (on 15.0 we can translate input `value=""` attributes & textarea's content too):

C- We get the translation `<span/>` as input value too... but jQuery `attr()` won't update the "value" property on `beforeEditorActive()` (Fixed in this PR).

D- The same `attr()` issue prevents setting the value on inputs from the `AttributeTranslateDialog` (Fixed in this PR).

E- I added the same thing as **[B]** for input values, but we can't do that for text content in `<textarea/>`s (since we can't select a `textarea` on CSS based on content...). The best idea IMHO is to do something similar to what we did for `autoMoreMenu`: once the document is ready, we check if we are in translate mode, and we hide text on `textarea`s until the editor fixes the content... I added this code in a temporary commit here (@qsm-odoo let me know if it's OK for you, so I can add it to the 15.0 fw-port of **[B]**. Thanks :+1:).

@rdeodoo To answer your question: Yes I kept the code from 14.0 for testing (It makes attributes translation possible...) but also added on it [a small diff to take in consideration values translation...](https://github.com/odoo/odoo/commit/ae0f08c8e75700e3dc4fdf03ab7c687448a34ea0#diff-f338780f594d6b1f46eda5d3fb9fed86f3c3c8f65522fb93e639534e9d92cdb2R1612-R1614). Now I moved this diff to the temporary commit from **[E]** (https://github.com/odoo/odoo/pull/106458/commits/6f5741b65967a22ac8722d4be6f44855f592eb6d) which should be a part of the forward-port of https://github.com/odoo/odoo/pull/106198 on 15.0 :+1:

**Comment by qsm-odoo** [comment]
@robodoo delegate=bso-odoo

**Comment by xO-Tx** [comment]
Closing this since it made more sense to fix the default values translation on the fw-port
of the main PR (in a separate commit) :+1:
cc @bso-odoo

**Pull request closed without merging**
