### PR TITLE
[FIX] models: reflect inherited (by `_inherits`) custom fields

### PR DESCRIPTION
**Pull request by rco-odoo**
When a custom field is added on a given model, it appears in `ir.model.fields`
on the model's children models (by `_inherits`).  This makes the reflection
more accurate (inherited custom fields are visible), although not perfect (they
appear as "base" fields and thus cannot be overridden).

The reflection of fields in `ir.model.fields` has been improved to deal with
custom field creation, modification and suppression.

Custom fields are still not inherited through `_inherit` relations.

### CODE REVIEW

**Comment by rco-odoo** [comment]
@nim-odoo @odony @KangOl I welcome you to review this pull request.

**Comment by nim-odoo** [comment]
I cannot judge the technical side of the PR, but on the functional PoV, it now works as expected.

**Comment by nim-odoo** [comment]
Ping @odony and @KangOl 
opw 687626 and 645065

**Comment by odony** [comment]
The patch looks good, thanks. Tested and working for creation, modification and deletion (having unit tests to verify the intended behavior and make it explicit would be better but can be done later)

@nim-odoo It will be important to explain the new logic to the bug reporters, as they complained about having inherited fields appear as "base fields". It will still be the case now, but in a predictable and dynamic manner (related fields to the inherited custom fields, kept in sync)
:+1:

**Comment by nim-odoo** [comment]
Thanks guys!
Merged in https://github.com/odoo/odoo/commit/5c5d0865b9248cf01a125240704d2c6b49d1a125

**Pull request closed without merging**
