### PR TITLE
[FIX] sale_stock,stock_account: avoid COGS generation if owned

### PR DESCRIPTION
**Pull request by adwid**
When a delivered product was owned by an external partner, we should not
generate any COGS line

OPW-2884211

### CODE REVIEW

**Comment by Whenrow** [comment]
robodoo r+ rebase-ff

**Comment by suniagajose** [comment]
@Whenrow could you backport this feature to 15.0?

cc @JulioSerna 
cc @hbto

**Comment by Whenrow** [comment]
@suniagajose We don't want to merge this one in 15.0 because of the change of behaviour that is implied before and after the patch. 
Imagine you buy some quantities with owner (the cogs are created). Then the patch is applied on your database. Then you sell the quantities (the cogs are not balanced because of the owner quants) 
This lead to a difference that is really difficult to understand compare to the actual issue. That's why we decided to only merge this in 16.0

**Comment by suniagajose** [comment]
@Whenrow  i understand, but i think, that at least should be optional in the configuration, since that 15.0 still is a supportable version and i have a client that need this fix, i create a ticket for this (opw-3164944)

cc @JulioSerna 
cc @hbto

**Pull request closed without merging**
