### PR TITLE
mail reinstall issues

### PR DESCRIPTION
**Pull request by Elkasitu**

### CODE REVIEW

**Comment by Elkasitu** [comment]
robodoo rebase-ff

**Comment by Elkasitu** [comment]
@tde-banana-odoo any comments?

**Comment by Elkasitu** [comment]
robodoo r+

**Comment by tde-banana-odoo** [comment]
> @tde-banana-odoo any comments?

I knew this "external id" stuff from Chs was a bad idea and I told it.

Grumpy dev is happy and sad at the same time.

**Comment by Elkasitu** [comment]
no problem, the brol is now fixed

**Comment by tde-banana-odoo** [comment]
Actually the brol will disappear completely soon in master :) .

**Pull request closed without merging**
