### PR TITLE
created l10n_tr_states addon to seed provinces of Turkey

### PR DESCRIPTION
**Pull request by cantecim**
Description of the issue/feature this PR addresses:

Current behavior before PR:
There are no data provinces of Turkey

Desired behavior after PR is merged:
Added an auto-installing localization addon to seed them

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Could you add them in the existing l10n_tr module instead?

**Comment by cantecim** [comment]
I think someone might need the data without installing l10n_tr. It is an auto-installing addon to make them ready on fresh database initialization

**Comment by mart-e** [comment]
Good point and actually we are working on a proper solution for per-country data at
https://github.com/odoo-dev/odoo/tree/master-country-specific-data-l10n_be-pla
It is not ready yet but hopefully, we will get that for v13.
So you can either wait for that to be ready to be included in the future version of Odoo or add  them in l10n_tr.

**Comment by cantecim** [comment]
Hello @mart-e, I've done them

**Comment by mart-e** [comment]
Thanks for the update. I have squashed the commits.

@robodoo r+

**Pull request closed without merging**
