### PR TITLE
[FIX] web: load font.scss for Roboto font

### PR DESCRIPTION
**Pull request by atp-odoo**
due to language condition on parent view could not able to find last element. so correct xpath and set if condition directly on link tag

opw- 1938001

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
LGTM but to double check as strange we can only reproduce it in migration...

@robodoo delegate=rdeodoo

**Comment by atp-odoo** [comment]
@mart-e , @rdeodoo 
reason why it has been reproduced only in migration :
in customer original v11 database  `tours assets` view registered first( lower id, first priority )then `web enterprise asset view`.
`tour assets` load this two scss file too. last link element also changed and based on xpath in web enterprise view it's try to check on this too. 

> link rel="stylesheet" type="text/scss" href="/web_tour/static/src/scss/tip.scss"/>
> link rel="stylesheet" type="text/scss" href="/web_tour/static/src/scss/keyframes.scss"/>

see image : 

Odoo

we can reproduce same error if we just change priority of `tour asset ` then `web enterprise asset view` like above view 

so better we can change it.

thanks

**Comment by rdeodoo** [comment]
@robodoo r+

**Comment by rdeodoo** [comment]
@robodoo retry

**Comment by d-fence** [comment]
It seems that there was a PR in enterprise linked to this and the enterprise branch does not exists anymore (+ the linked PR is now closed).
I think that a force push in the present branch should solve the problem.

**Comment by Yenthe666** [comment]
@atp-odoo @mart-e and @rdeodoo you might actually want to check the PR from https://github.com/odoo/enterprise/pull/3809 - you both seem to be fixing the same thing but the one from @wtaferner looks way more flexible/dynamic

**Comment by rdeodoo** [comment]
@Yenthe666 This PR is fixing the cause of the bug while the PR you mentionned is fixing (one of*) the consequence(s) of the bug.
\* There is only one occurence in Odoo standard code but we might add another one anytime, and community modules might also have `//link[last()]`.

**Comment by JKE-be** [comment]
btw in the future we should **maybe** change

` <xpath expr="//script[last()]" position="after">`
by
`<xpath expr="." position="inside">`

But I agree with @rdeodoo, this fix is better than PR https://github.com/odoo/enterprise/pull/3809. 
It will fix all future //link[last()] done. And not only the first one after the t-if (font.scss).
If tomorrow you add a new xpath before font.scss it will works with this fix too.


@robodoo r+ retry ...

**Comment by odony** [comment]
@robodoo r-  because this PR is not ready

**Comment by odony** [comment]
Moving the `<link>` outside of the `<t>` element will avoid the bug with the `//link[last()]` expression causing the inherited element to end up inside the `<t t-if` instead of below, yes.

**But** having a `t-if` inside an asset source code is still an error. It means the asset contents will change according to a context condition (in this case the user lang), so the cached version will constantly be recompiled depending on the visitor activity and their language, and cause performance problems and resource waste.

One can **never** use `t-if`, `@groups` or any conditional sections inside assets! Instead we have to use proper CSS selectors or conditional loading code in the JS to activate the features only when they are needed. Incidentally, this will also avoid similar inheritance bugs.

In the case of `fontawesome_overriden.scss`, the easiest solution is to include it all the time, but wrap its contents in an extra selector to ensure it is only applied when RTL is enabled for the current page. i.e.
```css
.o_rtl {
    .fa {
        &.fa-align-right,
        &.fa-align-left,
        // (...)
    }
}
```

In fact, this technique was already used for other bits of CSS in PR #23831, so I'm not sure why it wasn't done for this particular case, @mart-e  (see f7130556bbcbc0a0b93ba07ef1da9c9d11b68b54).

Either way, please fix it properly.

**Comment by rdeodoo** [comment]
As this is an issue for migration and is priority, can't we merge this PR like this and someone will then refactor the RTL if needed? It has already been 7 days since first PR was open (https://github.com/odoo/enterprise/pull/3755) and I don't know how long it would take to fix it properly.

**Comment by odony** [comment]
@rdeodoo I think this bug is present since the release of 12.0, and it's trivial to fix it cleanly.

And irregardless of how we fix it, there is a second occurrence [in POS](https://github.com/odoo/odoo/blob/2f932e3a46c6005870e4130b3c3f7151cd521f2d/addons/point_of_sale/views/point_of_sale.xml#L9-L11).

**Comment by odony** [comment]
Additionally, the dual assets compilation (rtl/ltr) introduced in f7130556 is not sufficient to workaround this variation in assets contents - it still causes spurious invalidation all the time when you have a multi-language website with rtl and non-rtl languages installed.

It could have something to do with the difference in the method used to find the current language:
- The [assets generation code](https://github.com/odoo/odoo/blob/2f932e3a46c6005870e4130b3c3f7151cd521f2d/odoo/addons/base/models/assetsbundle.py#L98-L99) uses the context/current user language: `self.env.context.get('lang') or self.env.user.lang`
- The [conditional fontawesome override](https://github.com/odoo/odoo/blob/2f932e3a46c6005870e4130b3c3f7151cd521f2d/addons/web/views/webclient_templates.xml#L66-L68) uses the current website language:  `request.env.lang`

The two values could easily be different, e.g. as soon as the user logs in and select their own preferred language. Either way, it shows how brittle it is to have conditions inside asset templates.

**Comment by odony** [comment]
Superseded by #31782

**Comment by msh-odoo** [comment]
> Moving the `<link>` outside of the `<t>` element will avoid the bug with the `//link[last()]` expression causing the inherited element to end up inside the `<t t-if` instead of below, yes.
> 
> **But** having a `t-if` inside an asset source code is still an error. It means the asset contents will change according to a context condition (in this case the user lang), so the cached version will constantly be recompiled depending on the visitor activity and their language, and cause performance problems and resource waste.
> 
> One can **never** use `t-if`, `@groups` or any conditional sections inside assets! Instead we have to use proper CSS selectors or conditional loading code in the JS to activate the features only when they are needed. Incidentally, this will also avoid similar inheritance bugs.
> 
> In the case of `fontawesome_overriden.scss`, the easiest solution is to include it all the time, but wrap its contents in an extra selector to ensure it is only applied when RTL is enabled for the current page. i.e.
> 
> ```css
> .o_rtl {
>     .fa {
>         &.fa-align-right,
>         &.fa-align-left,
>         // (...)
>     }
> }
> ```
> 
> In fact, this technique was already used for other bits of CSS in PR #23831, so I'm not sure why it wasn't done for this particular case, @mart-e (see [f713055](https://github.com/odoo/odoo/commit/f7130556bbcbc0a0b93ba07ef1da9c9d11b68b54)).
> 
> Either way, please fix it properly.

@odony Solution you gave is perfect to wrap fontawesome overridden css inside o_rtl, just to inform you that we maintain two version of assets 1 for ltr and rtl language, so I am not sure it is compiled each time based on user language.

Well I have no objection with wrapping css content in o_rtl

**Pull request closed without merging**
