### PR TITLE
[UPD] website_mass_mailing: Update submit button to enable translation

### PR DESCRIPTION
**Pull request by cristinamartinrod**
Description of the issue/feature this PR addresses:
"Update my subscriptions" is not a translatable term.

Current behavior before PR:
Can not translate from input value.

Desired behavior after PR is merged:
"Update my subscriptions" is now a translatable term.

cc @Tecnativa

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's still problems with the CLA. And you have touched es.po and de.po without need.

**Comment by mart-e** [comment]
Hi,

Thanks for the PR, for the CLA, it is because you are signing with your gmail address.
I guess you want to do it with your Technativa email address? (and sign the CLA)

**Comment by cristinamartinrod** [comment]
Hi @mart-e , I'm authorized in v11, could you add me in v10?https://github.com/odoo/odoo/blob/11.0/doc/cla/corporate/tecnativa.md
Thanks

**Comment by mart-e** [comment]
I have backported e78af353fc71e3e4866e8798c549038631edc2e4 to 10.0 inside your branch.

@robodoo it looks good now :+1: would you mind r+ in rebase-ff mode?
That would be lovely

**Pull request closed without merging**
