### PR TITLE
[FIX] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by LucasLefevre**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/2eb3f1cf2 [REL] 17.4.11 Task: 0
https://github.com/odoo/o-spreadsheet/commit/26a46e9c1 [FIX] charts: do not show zero values in pie charts Task: 4277144
https://github.com/odoo/o-spreadsheet/commit/360550579 [FIX] pivot: skip cells on manipulated pivot array formulas Task: 4292134
https://github.com/odoo/o-spreadsheet/commit/595963de3 [FIX] xlsx: convert #REF at export to xlsx Task: 4207052
https://github.com/odoo/o-spreadsheet/commit/c6a75e60c [FIX] parser: inconsistent handling of #REF Task: 4207052
https://github.com/odoo/o-spreadsheet/commit/1aa1b2c99 [FIX] charts: correct stacked checkbox label Task: 4251670

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by LucasLefevre** [comment]
robodoo fw=no

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
@robodoo retry

**Comment by LucasLefevre** [comment]
@robodoo retry

**Pull request closed without merging**
