### PR TITLE
[IMP] mrp: add hook to prepare workorder values on MO planning

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
We need a hook to be able to personalize the workorder values
which will be used on workorder creation when planning an MO

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@sle-odoo any chance this is accepted?

**Comment by LoisRForgeFlow** [comment]
Hi @sle-odoo 

I know we must be a pain in the ass all the day pinging you (sorry :pray:) but this kind of small things are really blocking while we are waiting a call. Can you have a look or point me the right person to take the decision here? From my POV, hooks are always a good extensibility improvement, is there any downside we cannot see?

Thanks!

**Comment by AaronHForgeFlow** [comment]
The code have been updated to be like a helper code should be. Please let me know if I missed anything here.

Thanks for your time @sle-odoo

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by AaronHForgeFlow** [comment]
Apologies @sle-odoo  I screwed this up by pushing wrong code here. Shame on me.

Now it is fixed again. Could you retry the merge again?

**Comment by sle-odoo** [comment]
no worries
robodoo r+

**Pull request closed without merging**
