### PR TITLE
[IMP] base: add Swiss states

### PR DESCRIPTION
**Pull request by danibaumann**
Added Swiss states to base

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
@danibaumann Can you change your commit message by `[IMP] base: add Swiss states`

**Review by william-andre — APPROVED** [review]
Thanks for the contribution!

This is only basic data in a file that is not going to change a lot, so I'm gonna approve it, but here are some possible improvements that could have been nice
* try to order by country code, to avoid conflicts
* end your file with a EOL char, again: to avoid conflict

Since it is for Switzerland, it is also a bit sad that this is not translatable in 16.0 (anymore) but nothing to do on your side...
https://github.com/odoo/odoo/pull/97692/files#r965680072

@robodoo r+

**Comment by evko-odoo** [comment]
Hello! Can we please backport the same for v14 and v15? I have a ticket about this TN #3180676 
Thank you!

**Comment by william-andre** [comment]
@grindtildeath 
That is unfortunate. Note that any fix, as simple as it might seem can break someone's database. If we do not fix these, the software would never be fixed, and would move very slowly (users would only get the fixes in `master`, after sometimes a few years before the migration)

A way of solving this would be to create the xml ids manually in the database.

**Comment by ivantodorovich** [comment]
@william-andre that requires prior knowledge of the issue, and a manual step for each database. I'm pretty sure you'll have this very same issue in many databases in odoo online or odoo.sh. 😓 

How about adding a pre-migration script, to try and create the xml ids automatically if the states already exist?

**Comment by grindtildeath** [comment]
@william-andre Thanks for your answer.

I do agree with fixing the software in stable versions. However, this PR does not look like a fix but an improvement (as reflected in the commit message), and looking at [What does "Stable" mean?](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean), I see some issues with the following points:

> - No "improvement" (technical or functional) should be done in stable, they typically have a very low value/risk ratio. Often, the functional coverage is voluntarily limited.
> - No change to the XML IDs of existing module data, and no deletion of module data records that may be referenced by user data in existing databases, unless the changes are absolutely essential and the records were in noupdate mode initially.
> - XML files (views, menus, default data, etc.) should only be changed if inevitable. When changed, the change must not be mandatory, i.e. the Python code must not depend on the change.

As an alternative to a migration script, these records could also be moved to an XML file with `forcecreate="0"` attribute, so that they don't get created through a module update. I see no issues in having it in the CSV for future versions, but having such changes in stable is not nice for existing customers that did create or import the such records in their DB.

**Comment by william-andre** [comment]
@grindtildeath @ivantodorovich @leemannd @adekock11 
Here is a fix proposition: https://github.com/odoo/odoo/pull/114066

**Pull request closed without merging**
