### PR TITLE
Update mail_followers.py 

### PR DESCRIPTION
**Pull request by Jerezano**
Followers that reply to inbox with copy in to,cc or bcc to other followers , the followers add it in to,cc or bcc will not get a duplicated emai!!

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
I find it weird, as email_to, email_cc and email_bcc do not exist on the mail_message model. What are you trying to do exactly ?

**Comment by Jerezano** [comment]
Well it is working on my instance!, It does this ;
1.-If you send an replay to de email related to a message from another client (Mobil or Desktop) and that replay has in to or cc or bcc any of the email address of the followers they will not get double messages as normally they will do get the replay from (Mobil or Desktop) and another individual from odoo each destination email address (followers) , creating confusion for the customers.

**Comment by tde-banana-odoo** [comment]
Well either you have custom code, either there is something I do not understand. As those fields (email_to, email_cc and email_bcc) do not exist on the message record, I cannot see how this could work. mail_message only has an email_from field; recipients are computed using partner_ids and notified_partner_ids that are res.partner records.

**Comment by Jerezano** [comment]
They do exist on the ir_mail_server.py as base !

**Comment by tde-banana-odoo** [comment]
What is the link between ir_mail_server and a mail_message record ? I think you are mixing several concepts here. Basically a message is a mail_message record. It does not handle email addresses, only partners. When sending an email, a mail_mail record is created. It is based on the mail_message record, using inheritance. This model has email_to and email_cc fields; however those are not set by the chatter mechanism. It is used when sending custom emails, or using email templates. When the mail is sent, it is done using the ir_mail_server build_email method that effectively accepts email_cc, email_bcc parameters.

However here you are trying to read fields that do not exist. Maybe it does not crash but it probably does not work, unless you have some custom code elsewhere.

**Comment by Jerezano** [comment]
I do not have any other code ; I can asure you that cause when a I did a git pull I had to re-put that code again for it to work and it is working!
I think when ever there is an incoming email that it is related to an object that has followers mail_follower well check that code and if it finds any email address on those fields that are already a follower it will not resend the message.
you could try it your self!

**Comment by tde-banana-odoo** [comment]
Then I will ask you to provide a test case that fails without that code, and correctly works with. Thanks !

**Comment by Jerezano** [comment]
Well I was trying to contribute ! not sure how to do that your asking for.!

**Comment by tde-banana-odoo** [comment]
You simply have to add a test case in the unittests of the mail module. See for example mail/tests/test_mail_features.py .

**Pull request closed without merging**
