### PR TITLE
[FIX] base: error handling of automated actions 

### PR DESCRIPTION
**Pull request by rash-odoo**
If Automation Actions's configuration is done wrong it will
cause Error at runtime which will be caught in sentry and
causes unnecessary traffic.

```
KeyError: 'move_id'
  File "odoo/http.py", line 2115, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1698, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 134, in retrying
    result = func()
  File "odoo/http.py", line 1725, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1922, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 715, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/web/controllers/dataset.py", line 28, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/dataset.py", line 24, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 459, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "odoo/api.py", line 439, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-500>", line 2, in create
  File "odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "addons/base_automation/models/base_automation.py", line 390, in create
    action._process(action._filter_post(records))
  File "addons/base_automation/models/base_automation.py", line 340, in _process
    raise e
  File "addons/base_automation/models/base_automation.py", line 337, in _process
    action_server.sudo().with_context(**ctx).run()
  File "odoo/addons/base/models/ir_actions.py", line 706, in run
    res = runner(run_self, eval_context=eval_context)
  File "odoo/addons/base/models/ir_actions.py", line 593, in _run_action_object_create
    res = self.env[self.crud_model_id.model].create(res)
  File "<decorator-gen-150>", line 2, in create
  File "odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "addons/account/models/account_move_line.py", line 1400, in create
    moves = self.env['account.move'].browse({vals['move_id'] for vals in vals_list})
  File "addons/account/models/account_move_line.py", line 1400, in <setcomp>
    moves = self.env['account.move'].browse({vals['move_id'] for vals in vals_list})
```
So, we stop catching exceptions from Automated Actions.

sentry-4200700020

### CODE REVIEW

**Comment by rash-odoo** [comment]
@odoo/sentry_reviewers 
can you please review this PR.

**Comment by rash-odoo** [comment]
> I guess we should apply similar ideas from https://github.com/odoo/odoo/pull/121432/files
> 
> i.e. check that action is manually created and doesn't come from modules, because in later case we do want to catch such errors

If i am not wrong `_run_action_object_{write/create}` methods are run for `base_automation` actions which are always supposed to be created by user as we don't have any `base_automation` in standard code ??

Then there is no need to check this. ??

**Review by yelizariev — APPROVED** [review]
You are right, we don't create `base.automation` records in standard code. I confused it with custom community modules

**Comment by yelizariev** [comment]
@Julien00859 maybe?

**Comment by Julien00859** [comment]
lgtm

**Comment by yelizariev** [comment]
@abz-odoo r+ ?

**Comment by abz-odoo** [comment]
robodoo r+

**Pull request closed without merging**
