### PR TITLE
[CLA] Sign CLA for tisho99

### PR DESCRIPTION
**Pull request by Tisho99**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Tisho99** [comment]
@HaraldPanten

**Comment by pedrobaeza** [comment]
@mart-e too late, hehe, but it avoids to resubmit in case he submits any pull request to lower versions.

**Review by HaraldPanten — COMMENTED** [review]
I can confirm that Alberto is a member of our Company.

**Comment by jco-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
