### PR TITLE
[FIX] event: Allow to override default method

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses:
Without this patch, you have to redefine the field to be able to override this field.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@tde-banana-odoo can you check this easy one?

**Comment by sswapnesh** [comment]
Not a stable Change
Have a look at  https://github.com/odoo/odoo/pull/29588#issuecomment-448556126 and https://github.com/odoo/odoo/pull/29646#issuecomment-448655464

**Comment by pedrobaeza** [comment]
Oh, I see. Then this should be re-target to master and continue doing the field override in each module.

@Yajo please change the target.

**Comment by Yajo** [comment]
Rebased and retargeted for master. Please review.

**Comment by tde-banana-odoo** [comment]
Seems right, thanks !

@robodoo r+

**Pull request closed without merging**
