### PR TITLE
[CLA] BHanq Signature

### PR DESCRIPTION
**Pull request by BHanq**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by BHanq** [comment]
> Could you rename your file to lowercase? 

Yup doing it rn, though it is not really clear in [here](https://github.com/odoo/odoo/blob/18.0/doc/cla/sign-cla.md) (it is in the company part but didn't read it before now). You should probably change for  `<lowercase-github-login>.md` and or change the example `If your GitHub login is ODony, the file would be doc/cla/individual/odony.md` in order to get things clearer. As there is a bunch of cla file with capital letters :cry: 

> Miss us already? :)

Not really, wanted to take care of https://github.com/odoo/odoo/pull/180400#issuecomment-2454117066, as I have some free time to heavy rain :umbrella: 

>  really? 🤨

I am officially still a Belgian resident but I can brag if you want me to :saluting_face:

**Comment by mart-e** [comment]
> Yup doing it rn, though it is not really clear in [here](https://github.com/odoo/odoo/blob/18.0/doc/cla/sign-cla.md) (it is in the company part but didn't read it before now).

Good idea. Do you want to add it in this PR?

**Comment by BHanq** [comment]
@mart-e Done, though it is not master and not really a fix I don't know if it is fine having a IMP in stable version for such PR ?

**Comment by mart-e** [comment]
No that’s fine, it’s doc, thank you :+1: 
@robodoo r+

**Pull request closed without merging**
