### PR TITLE
[IMP] hr_holidays: improve mail quality

### PR DESCRIPTION
**Pull request by arpi-odoo**
This will make emails after a time-off has been confirmed and/or approved more useful with more information about the time-off and buttons to directly approve the time-off.

Task: 3672291

### CODE REVIEW

**Review by Flotchet — COMMENTED** [review]
Hello hello

I just think that you can except a more precise exception than the bare one
(I know that all other method of this are using the bare one tho)
Otherwise LGTM

More generally I think that this code is almost duplicated 6 times so maybe it could be worth it to merge all those in one just using the route to know how to do but to be discussed

**Comment by arpi-odoo** [comment]
> I just think that you can except a more precise exception than the bare one

I am not sure which exception could be raised and when. I am not sure it is worth looking for all the sub calls to other functions to know which exceptions could be raised.

**Comment by Flotchet** [comment]
> > I just think that you can except a more precise exception than the bare one
> 
> I am not sure which exception could be raised and when. I am not sure it is worth looking for all the sub calls to other functions to know which exceptions could be raised.
> 
> > More generally I think that this code is almost duplicated 6 times so maybe it could be worth it to merge all those in one just using the route to know how to do but to be discussed
> 
> Maybe something like this ?
> 
> ```python
> from odoo.http import request
> 
> 
> class HrHolidaysController(http.Controller):
> 
>     def perform_or_redirect(self, res_id, token, model, action):
>         comparison, record, redirect = MailController._check_token_and_record_or_redirect(model, int(res_id), token)
>         if comparison and record:
>             try:
>                 action(record)
>             except Exception:
>                 return MailController._redirect_to_messaging()
>         return redirect
> 
>     @http.route('/leave/validate', type='http', auth='user', methods=['GET'])
>     def hr_holidays_request_validate(self, res_id, token):
>         return self.perform_or_redirect(res_id, token, 'hr.leave', request.env['hr.leave'].action_validate)
> 
>     @http.route('/leave/refuse', type='http', auth='user', methods=['GET'])
>     def hr_holidays_request_refuse(self, res_id, token):
>         return self.perform_or_redirect(res_id, token, 'hr.leave', request.env['hr.leave'].action_refuse)
> 
>     @http.route('/allocation/validate', type='http', auth='user', methods=['GET'])
>     def hr_holidays_allocation_validate(self, res_id, token):
>         return self.perform_or_redirect(res_id, token, 'hr.leave.allocation', request.env['hr.leave.allocation'].action_validate)
> 
>     @http.route('/allocation/refuse', type='http', auth='user', methods=['GET'])
>     def hr_holidays_allocation_refuse(self, res_id, token):
>         return self.perform_or_redirect(res_id, token, 'hr.leave.allocation', request.env['hr.leave.allocation'].action_refuse)
> ```

Yup I was maybe seeing more something like this but it was more of a general comment about the controller itself because by discussing with mepe and bedo we were not sure about it. it's why I put the comment a bit appart because it's not really necessary to do it per say and I'm not actually completly sure if it's a good idea or not tbh but your idea is great too because you don't parse the url to dispach

```py
from odoo.addons.mail.controllers.mail import MailController
from odoo import http

key_to_actions={
	'validate': lambda r: r.action_validate(),
	'refuse': lambda r: r.action_refuse(),
	'approve': lambda r: r.action_approve(),
}

key_to_model={
	'leave': 'hr.leave',
	'allocation': 'hr.leave.allocation'
}

class HrHolidaysController(http.Controller):
	@http.route([
		'/leave/validate', '/leave/refuse', '/leave/approve',
		'/allocation/validate', '/allocation/refuse', '/allocation/approve',
	], type='http', auth='user', methods=['GET'])
	def hr_holidays_action(self, res_id, token):
		path_segments = http.request.path.split('/')
		comparison, record, redirect = MailController._check_token_and_record_or_redirect(
			key_to_model[path_segments[0]], int(res_id), token)
        if comparison and record:
            try:
                key_to_actions[path_segments[1]](record)
            except Exception:
                return MailController._redirect_to_messaging()
        return redirect
```

For the exception thinguy I think that actually the only exception that you can get are access, user or validation for me it's better to catch them explicitly so like this if an unintended thing append at some point we'll get an actual traceback and not a silent error (but it will be harder to do if we actually merge everything)

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo override=ci/style

**Pull request closed without merging**
