### PR TITLE
[MERGE] web: update bootstrap from 4.1.3 to 4.2.1

### PR DESCRIPTION
**Pull request by qsm-odoo**
Bootstrap just released a brand new version with new components and new possibilities, which are great to integrate in master.

Note: Unfortunately, this also comes with some bug fixes they did not add in a 4.1.4 version, so there is no clean way to backport them in Odoo 12.0 (so if any is required at some point, we will have to use bootstrap_review.scss or anything else to bug fix).

task-1924233

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo r+ rebase-merge

**Comment by JKE-be** [comment]
@robodoo can you retry please

Jeremy Kersten

**Comment by qsm-odoo** [comment]
@robodoo retry please, the enterprise fix will soon be reviewed

**Comment by qsm-odoo** [comment]
@robodoo retry

**Comment by qsm-odoo** [comment]
Damn you robodoo (@d-fence second time I failed to respect the 72 characters conventions because of him :cry:)

**Pull request closed without merging**
