### PR TITLE
[IMP] expose basic model info through the api

### PR DESCRIPTION
**Pull request by blaggacao**
With this an external ETL session can infer the necessity of conducting
a toposort of some kind on a candidate dataframe and do so in order
to ensure the loading success rate and optimize for loading speed
on big loading tables.

@rco-odoo Pretty please (my ETL engineers have to focus on more important stuff) 
@tfr-odoo  might also be interested...

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by blaggacao** [comment]
Here is my fun code depending on this PR... https://gist.github.com/blaggacao/4afb8f96a639ffad6653bd5ba99e06b4

**Comment by blaggacao** [comment]
@odony It's somewhat basic, but it makes integrated online ETL workflws (for example in dataiku) possible.
It's a great quality gain for ETL teams if they do not need to care about the uploading order because a toposort algorithm queries this data...

Pretty please!

**Comment by blaggacao** [comment]
@xmo-odoo Subsidiary ping...

**Comment by odony** [comment]
This should definitely be targeted at master, or possibly done in a custom module. Also, considering that the fields info is already exposed through other API method, you might want to discuss extending the info provided by these methods with @rco-odoo, rather than adding yet another redundant entry point for this ;-)

**Pull request closed without merging**
