### PR TITLE
[FIX] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by LucasLefevre**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/d27e9984 [REL] 16.0.11
https://github.com/odoo/o-spreadsheet/commit/7ae88427 [FIX] Chart Pannel: fixes updateChart process
https://github.com/odoo/o-spreadsheet/commit/57caf629 [FIX] ColorPicker: modified add custom color icon Task: 3258627

### CODE REVIEW

**Comment by LucasLefevre** [comment]
fw-bot ignore

**Comment by rrahir** [comment]
@robodoo  enterprise is rouuuche

**Comment by rrahir** [comment]
@robodoo r- du coup

**Comment by LucasLefevre** [comment]
@robodoo r+

**Pull request closed without merging**
