### PR TITLE
[Imp]Project: Added copy=False in task_ids

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses:  Added copy=False in task_ids

Current behavior before PR:  During duplicating Project it also copy all the task which should not.

Desired behavior after PR is merged: Duplicating Project will not Copy tasks.

Should be forwarded to 11.0

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Both features are desired depending use cases. For lot of cases, I want to copy project with its tasks. There are even modules built on top of that functionality (using projects as templates), so it shouldn't been changed, at least in stable.

**Comment by sswapnesh** [comment]
I do agree with you in the case when Projects are used as templates, Better to add Configuration for Same. (May be in master)

**Comment by mart-e** [comment]
Hello,

Sorry, but as said Pedro, it is on purpose with templates and we do not change that on stable version.

While I agree it will not match some use-cases, adding an option for something as specific as this is rarely a good idea. We need to keep the configuration simple and tries to make a decision on the behaviour.
I have reported the feedback nevertheless, so maybe it will be reconsidered in master but nothing at the moment.

**Comment by sswapnesh** [comment]
Thanks for the Feedback.

**Comment by sswapnesh** [comment]
> I have reported the feedback nevertheless, so maybe it will be reconsidered in master but nothing at the moment.

@mart-e  Any Feedback?

**Comment by mart-e** [comment]
Sorry, if nothing has changed, it means it was not accepted

**Pull request closed without merging**
