### PR TITLE
[FIX] product : UI product.product form was broken

### PR DESCRIPTION
**Pull request by luve-odoo**
UI improvments for the form of product.product model.

task-3043184

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ticodoo** [comment]
Hello @luve-odoo, please convert your PR to draft if it is not ready for review yet so that other teams aren't auto-pinged for review too early (and so we're not spammed with an email every time you force push). Ideally you would open your PR in draft from the start next time and then mark it as ready for review when you are ready for other teams to review your changes.

**Review by Williambraecky — CHANGES_REQUESTED** [review]
Thanks for your work :)

**Review by Williambraecky — APPROVED** [review]
Thanks :)

**Review by Williambraecky — APPROVED** [review]
robodoo r+
Thanks :)

**Pull request closed without merging**
