### PR TITLE
[FIX] stock: do not force commit when validating a delivery

### PR DESCRIPTION
**Pull request by sebalix**
**Description of the issue/feature this PR addresses:**

OPW 2348526

When validating a delivery, the `action_done` method calls the `_send_confirmation_email` method which is charged (if delivery email is configured) to send an email with the delivery slip as attachment.

It happens that when the delivery slip is generated, QWeb assets are also generated (if they were not available) and the current transaction is force-committed due to these parts of code:

- `ir.actions.report.render_qweb_pdf`: https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/models/ir_actions_report.py#L675-L685
- `AssetsBundle.save_attachment`: https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/models/assetsbundle.py#L304-L305

To fix/circumvent this situation, this commit proposes to put all the logic sending the delivery slip by email in a `after` commit hook.

To reproduce the issue on a demo database with an Odoo shell:

```python
>>> import types
>>> def fake_commit(self):
...     print("==== FAKE COMMIT! ====")
...     __import__("traceback").print_stack()
... 
>>> env.cr.commit = types.MethodType(fake_commit, env.cr)
>>> picking = env["stock.picking"].browse(21)
>>> picking.state
'assigned'
>>> for move_line in picking.move_line_ids:
...     move_line.qty_done = move_line.product_uom_qty
... 
>>> picking.action_done()
==== FAKE COMMIT! ====
  File "/usr/local/bin/odoo", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/odoo/src/setup/odoo", line 8, in <module>
    odoo.cli.main()
  File "/odoo/src/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/odoo/src/odoo/cli/shell.py", line 125, in run
    self.shell(config['db_name'])
  File "/odoo/src/odoo/cli/shell.py", line 118, in shell
    self.console(local_vars)
  File "/odoo/src/odoo/cli/shell.py", line 82, in console
    return getattr(self, shell)(local_vars)
  File "/odoo/src/odoo/cli/shell.py", line 102, in python
    Console(locals=local_vars).interact()
  File "/usr/lib/python3.7/code.py", line 232, in interact
    more = self.push(line)
  File "/usr/lib/python3.7/code.py", line 258, in push
    more = self.runsource(source, self.filename)
  File "/usr/lib/python3.7/code.py", line 74, in runsource
    self.runcode(code)
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/odoo/src/addons/stock/models/stock_picking.py", line 729, in action_done
    self._send_confirmation_email()
  File "/odoo/src/addons/stock_sms/models/stock_picking.py", line 41, in _send_confirmation_email
    super(Picking, self)._send_confirmation_email()
  File "/odoo/src/addons/stock/models/stock_picking.py", line 735, in _send_confirmation_email
    stock_pick.with_context(force_send=True).message_post_with_template(delivery_template_id, email_layout_xmlid='mail.mail_notification_light')
  File "/odoo/src/addons/mail/models/mail_thread.py", line 1978, in message_post_with_template
    update_values = composer.onchange_template_id(template_id, kwargs['composition_mode'], self._name, res_id)['value']
  File "/odoo/src/addons/mail/wizard/mail_compose_message.py", line 405, in onchange_template_id
    values = self.generate_email_for_composer(template_id, [res_id])[res_id]
  File "/odoo/src/addons/mail/wizard/mail_compose_message.py", line 538, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields=fields)
  File "/odoo/src/addons/mail/models/mail_template.py", line 437, in generate_email
    result, format = report.render_qweb_pdf([res_id])
  File "/odoo/src/odoo/addons/base/models/ir_actions_report.py", line 734, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/odoo/src/odoo/addons/base/models/ir_actions_report.py", line 774, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/odoo/src/odoo/addons/base/models/ir_actions_report.py", line 548, in render_template
    return view_obj.render_template(template, values)
  File "/odoo/src/odoo/addons/base/models/ir_ui_view.py", line 1177, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo/src/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/src/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/src/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/src/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/src/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_stock_report_deliveryslip_5
  File "<template>", line 2, in foreach_4
  File "/odoo/src/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_stock_report_delivery_document_34
  File "/odoo/src/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_html_container_87
  File "/odoo/src/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_report_layout_90
  File "<decorator-gen-54>", line 2, in _get_asset_nodes
  File "/odoo/src/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/src/odoo/addons/base/models/ir_qweb.py", line 299, in _get_asset_nodes
    return remains + asset.to_node(css=css, js=js, debug=debug, async_load=async_load, defer_load=defer_load, lazy_load=lazy_load)
  File "/odoo/src/odoo/addons/base/models/assetsbundle.py", line 151, in to_node
    css_attachments = self.css() or []
  File "/odoo/src/odoo/addons/base/models/assetsbundle.py", line 332, in css
    self.save_attachment("css", css)
  File "/odoo/src/odoo/addons/base/models/assetsbundle.py", line 305, in save_attachment
    self.env.cr.commit()
```

**Current behavior before PR:**

The SQL transaction is committed as soon as we validate a picking, leaving data in a broken state if an error occurs later on in the workflow.

**Desired behavior after PR is merged:**

The SQL transaction does not have to be force-committed.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sebalix** [comment]
Another way would be to put all the assetsbundle thingy in its own transaction?

**Comment by yelizariev** [comment]
@sebalix a tip for you: you can click "Y" key at github commit page to convert the link to a static one:

https://github.com/odoo/odoo/blob/341639521ff916afa23abd2b10bbb1e9ce72ed58/odoo/addons/base/models/ir_actions_report.py#L675-L685
https://github.com/odoo/odoo/blob/341639521ff916afa23abd2b10bbb1e9ce72ed58/odoo/addons/base/models/assetsbundle.py#L304-L305

**Review by yelizariev — CHANGES_REQUESTED** [review]
Can be refactored to use a single transaction to send email for all pickings


`    def _send_confirmation_email_after_commit(dbname, context, picking_ids):
`

I also noticed, that in other cases of usage ``cr.after`` it's inline functions, rather than class method. E.g. https://github.com/odoo/odoo/blob/341639521ff916afa23abd2b10bbb1e9ce72ed58/addons/mail/models/mail_thread.py#L2326-L2331
Is there any benefits to use static class method? It seems it cannot be inherited anyway.

More general approach can be done in master. I'll make an issue about it

**Comment by yelizariev** [comment]
@sebalix I'm going to make a new PR with the suggested changes

**Review by mmequignon — APPROVED** [review]
LG !

**Comment by sebalix** [comment]
@yelizariev sorry I wasn't available the last two weeks. You prefer to keep your PR or I could update mine?

**Comment by yelizariev** [comment]
I'd keep mine

**Pull request closed without merging**
