### PR TITLE
[REF] l10n_**: Demo Data Cleanup

### PR DESCRIPTION
**Pull request by vin-odoo**
Auto Install
============

By having only one root module per country, containing minimal data and model changes, we can use that module to auto-install all localization for other modules.
For instance, installing `l10n_xx`, `account` and `hr_payroll` will automatically install all the bridges required for the country `xx`.

Demo Data
=========

Up until now, we did not have any common demo data package for localization. This is an issue for localization having both accounting and hr packages, because these do not depend on each others.
It means that to have complete demo data individually, they need to define demo company in both cases.

This leads to duplication in demo companies for a single country when both packages are installed, which is not ideal for testing as it also means that demo data is split between multiple companies.

This commit will rename things a bit to bring a common demo data package for multiple localization.

`l10n_xx` as it is known today becomes `l10n_xx_account` (as it was all along an invoicing module).
`l10n_xx` is instead a new module containing the demo company data.

task-3555251

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by william-andre — APPROVED** [review]

**Comment by william-andre** [comment]
@odoo/packaging Do you have an issue with this?
I think it should actually make your work easier (see the first part of the PR description)

**Comment by jco-odoo** [comment]
It seems super overkill to me.  There is  an active field on company and as we have a logic in account to install localization modules, the same could be done for payroll.

**Comment by vin-odoo** [comment]
@william-andre should I close this pr and the related one? I believe if we do something similar we'll use another solution?

**Comment by william-andre** [comment]
Not sure, creating the companies as inactive in `base` adds quite a bit of time on the installation of `base`

**Comment by jco-odoo** [comment]
@william-andre It is not the logos that take a lot of time to compute?  (We might create logos with flags)

**Comment by william-andre** [comment]
Yes it is, and the resizing in all different resolutions

**Comment by jco-odoo** [comment]
@william-andre create_multi could help (and making sure the same icon gets only calculated once)

**Comment by vin-odoo** [comment]
What about computing the image only when you activate a company

**Comment by william-andre** [comment]
That's what I wanted to do also, but I wanted to get rid of this first to not make the ORM team afraid of my PRs
https://github.com/odoo/odoo/pull/144586

One step at a time.

I guess you can close this and we can reopen if needed :shrug:

**Pull request closed without merging**
