### PR TITLE
[IMP] account,*: Technical cleaning

### PR DESCRIPTION
**Pull request by jva-odoo**
Rename field 'type' to  'move_type' in a model account.move

Rename field 'tag_ids' to 'tax_tag_ids' in module account.move.line

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
rebase needed in here, otherwise everything looks good

**Comment by jva-odoo** [comment]
ok, I will do it.

**Comment by jva-odoo** [comment]
@qdp-odoo rebase done 👍

**Comment by jva-odoo** [comment]
@qdp-odoo runbot is green now

**Comment by qdp-odoo** [comment]
you need to rework the history to have only the first 2 commits.

**Comment by jva-odoo** [comment]
@qdp-odoo  Done

**Comment by qdp-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by qdp-odoo** [comment]
@jva-odoo Thanks Jigar

**Comment by jva-odoo** [comment]
@qdp-odoo also merge this PR https://github.com/odoo/upgrade/pull/745 because Migration test is failed

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by jco-odoo** [comment]
@jva-odoo @anr-odoo You could have guessed that you break the localizations here...

**Comment by jva-odoo** [comment]
@jco-odoo where?

**Pull request closed without merging**
