### PR TITLE
[FIX] hr_holidays: fix "There is no valid allocation to cover that request" when create a new time-off

### PR DESCRIPTION
**Pull request by MBSALDarwish**
The issue shows when the user creates a new time-off request

image

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MBSALDarwish** [comment]
@robodoo retry

**Comment by MBSALDarwish** [comment]
@robodoo retry

**Comment by MBSALDarwish** [comment]
@robodoo review+

**Comment by mart-e** [comment]
@MBSALDarwish somebody from @odoo/rd-hr will review your PR and merge it if accepted :)

Regarding the CLA, you are making commits with `z...@hotmail.com` while signing for `m...@gmail.com` this is why the CLA test is still failing.
Also, can you keep your filename in lowercase?
Thanks

**Review by Bertrand2 — COMMENTED** [review]
Hello, thanks for the contribution!
However, I'm a bit troubled by the PR and I think the fix is not correct.
- What's the process that you followed to get the error?
- Your fix removes every kind of warning for leave type without allowed negative, meaning that anyone can create a leave outside of his allocation validity.
- In case of discrepancies between leaves and  allocations, meaning that a leave cannot be linked to an allocation, an error should be raised before the discrepancy is fixed, at least that's the behaviour we intend for now because the current code shouldn't bring those kind of issues.

As there weren't any way to identify the issuing leaves, fix odoo/odoo#151288 will give a warning on the dashboard linking to those leaves, allowing HR employees to decide on what to do with those leaves.

Have a nice day!

**Comment by Bertrand2** [comment]
Since there was no further details brought and since the recent commit merged with odoo/odoo#152311 already removed some check errors, I'm closing this PR.

Have a nice day!

**Pull request closed without merging**
