### PR TITLE
Master web domain selector sri

### PR DESCRIPTION
**Pull request by stefanorigano**
**Description of the issue/feature this PR addresses:**
Improve domain selector widget UX

**Current behavior before PR:**
It was not clear which element will be affected clicking on the remove/add buttons.
Some fields where unnecessary large.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
@qsm-odoo

Hello Quentin, could you have a look on this please?
Thanks!

**Comment by qsm-odoo** [comment]
Hey,
I find this really really great. I would speed the animations at least by a factor 2 but the idea is great ;)
I did not look at the code and this will probably have many conflict with the modifications I already made on my branch, but I will add your work, thanks :)

**Comment by stefanorigano** [comment]
Good!
No objections to refine the animation timing ( actually I made a try from 0.3s to 0.15s, it's better, you're right), but keep the animation delay.
We added it to avoid that moving the mouse 'everything will move' ^^.

**Comment by qsm-odoo** [comment]
The other guys on the team are not as enthusiastic as I am, so I suppose it will be worth discussing with usability team

**Comment by qsm-odoo** [comment]
Forgot to close this one... :)

**Pull request closed without merging**
