### PR TITLE
 [FIX] pos_restaurant: make config items inheritable 

### PR DESCRIPTION
**Pull request by primes2h**
Description of the issue/feature this PR addresses:

- point_of_sale config items have each an id attribute to be easily intercepted by other modules based on it. (eg. pos_restaurant)
- pos_restaurant extend point_of_sale config items without setting an id for new items added.
- So, for a new module depending upon pos_restaurant, it's not possible to intercept pos_restaurant config_items.

Current behavior before PR:

- pos_restaurant config items can't be intercepted to extend functionality.

Desired behavior after PR is merged:

- pos_restaurant config items are interceptable, so you can add features.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by primes2h** [comment]
Why did CLA check fail?

I carefully followed this:

https://github.com/odoo/odoo/blob/11.0/doc/cla/sign-cla.md

**Comment by primes2h** [comment]
Could someone check (and, in case, approve) my CLA please?
Thanks in advance.

**Comment by mart-e** [comment]
Hello,

_Did not checked yet, the content of the request_
Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `primes2h@users.noreply.github.com`
- you are signing _for_ the address `p...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by primes2h** [comment]
You are right, I forgot to untick the private email setting.

Do I have to make another pull request now and close this one?

**Comment by mart-e** [comment]
You can just make a new commit (like empty line) with the correct email

**Comment by mart-e** [comment]
Merged in master at

9e418ccaf94 [IMP] pos_restaurant: make config items inheritable
49b93a08f5b [CLA] Signature for primes2h

Thanks !

**Pull request closed without merging**
