### PR TITLE
[FIX] l10n_ma: Fixed CoA

### PR DESCRIPTION
**Pull request by rgo-odoo**
- fixed account types for few accounts
- set reconcile field for few accounts
- added new 'Achats des prestations de service'(code: 61263) account
- reflected accounts in chart template configuration

was task: 1913323
diff taken from PR #30772

CC: @jco-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by KARIZMA-CONSEIL** [comment]
Hello @rgo-odoo, why is the merger still blocked ?

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo rebase-ff

**Comment by nim-odoo** [comment]
robodoo r-

**Comment by nim-odoo** [comment]
sorry,n no merge today :smile:

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
