### PR TITLE
[FIX] hr_expense: a dependent field must be placed *after* its depend…

### PR DESCRIPTION
**Pull request by kebeclibre**
…encies

Select 2 hr.expense then go to action > submit report

Before this commit, the company currency amount of the first expense line of the report
was equal to zero, always
This is because, when evaluating onchanges, a tree is constructed in the order of the model._fields
which is an orderedDict, filled up when the class is the read
So in python and in the Odoo ORM, the order of field declaration does matter
i.e. a @api.depend fields must come *after* the fields it depends on

After this commit, everything computes as expected

OPW 2008868

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
@rco-odoo 
Should the explanation be considered as a bug in onchange > PrefixTree / Snapshot ??

**Comment by nim-odoo** [comment]
If this is indeed the case, I think it is worth either fix for good in master or raise a warning if it can be detected. This is quite a nasty issue to debug.

**Comment by kebeclibre** [comment]
@nim-odoo 
I checked with @rco-odoo who confirmed the issue has global.
He should handle the bugfix in v11.0
by applying the patch below, and writing a test
`diff --git a/odoo/models.py b/odoo/models.py
index ab958f62644..55e19adba72 100644
--- a/odoo/models.py
+++ b/odoo/models.py
@@ -5082,9 +5082,10 @@ class BaseModel(MetaModel('DummyModel', (object,), {'_register': False})):
                 names = dotname.split('.', 1)
                 name = names.pop(0)
                 suffixes[name].extend(names)
-            # fill in prefix tree in fields order
+            # fill in prefix tree in fields dependency order
             tree = OrderedDict()
-            for name, field in model._fields.items():
+            for field in sorted(model._fields.values(), key=self.pool.field_sequence):
+                name = field.name
                 if name in suffixes:
                     tree[name] = subtree = PrefixTree(model[name], suffixes[name])
                     if subtree and field.type == 'one2many':
`

**Comment by kebeclibre** [comment]
merging as the "right" fix changes some behavior
robodoo r+

**Pull request closed without merging**
