### PR TITLE
[FIX] web: focus html field

### PR DESCRIPTION
**Pull request by abla001**
cf commits

### CODE REVIEW

**Review by hubvd — APPROVED** [review]
Nice find. It also fixes another issue for me (opw-3235853):

If you try to edit a text field (Product description in a quotation) in Firefox, all the content is selected. When trying to click again to get the cursor, it reselects everything, meaning it is impossible to edit the current text without using the arrow keys.

**Review by hubvd — COMMENTED** [review]
Ok, so the reason the test "editable list view, should refocus date field" fails in 16.0 and not in 16.3 with https://github.com/odoo/odoo/commit/437edce3135c86f7361af1c5d1fa21b017ba00c9 is because with the new datepicker, the onPatched is only called once from the test and not twice https://github.com/odoo/odoo/blob/6a92ef1104244aa6b4b5d5673f0cd46b6f33129f/addons/web/static/src/views/list/list_renderer.js#L114-L122

But since https://github.com/odoo/odoo/commit/437edce3135c86f7361af1c5d1fa21b017ba00c9, it doesn't actually work anymore.

You can try it with this setup 
image
After using the datepicker, the description field is focused again.

So what we can do is
```diff
diff --git a/addons/web/static/src/views/list/list_renderer.js b/addons/web/static/src/views/list/list_renderer.js
index 6d7dd0a00401..d7dd46ff3cc0 100644
--- a/addons/web/static/src/views/list/list_renderer.js
+++ b/addons/web/static/src/views/list/list_renderer.js
@@ -937,6 +937,7 @@ export class ListRenderer extends Component {
                     `.o_selected_row td[name='${column.name}']`
                 );
                 if (containsActiveElement(cell)) {
+                    this.lastEditedCell = { column, record };
                     // Cell is already focused.
                     return;
                 }
```

This part should be forwarded until master. And the test should be fixed too from 16.3

**Review by Arcasias — APPROVED** [review]
@robodoo r+

**Comment by eltantillo** [comment]
Does anybody knows if this can be applied on 15.0?

**Pull request closed without merging**
