### PR TITLE
[FIX] fixed wrong version check for pylint in test_pylink

### PR DESCRIPTION
**Pull request by ap-wtioit**
Description of the issue/feature this PR addresses:
The pylint_test currently checks for version 1.6.4 with which the test cannot be run.

Current behavior before PR:
The pylint_test checked for a pylint version that was not compatible to the test.

Desired behavior after PR is merged:
The pylint_test now checks for version 1.7.0 (the first version i got the pylint_test to run)

I tested the following pylint versions (because i couldn't find a description / reference of which version to use):
* 1.7.0, 1.8.0, 1.8.4 (working, i tested those after 1.9.1 and 1.6.4)
* 1.6.4, 1.6.5 (not working)
<details><summary>Click to show test output for 1.6.4 and 1.6.5</summary>

```
2018-05-17 11:09:39,964 32601 INFO testdb odoo.addons.test_pylint.tests.test_pylint: test_pylint (odoo.addons.test_pylint.tests.test_pylint.TestPyLint)
2018-05-17 11:09:44,363 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAIL
2018-05-17 11:09:44,363 32601 INFO testdb odoo.addons.test_pylint.tests.test_pylint: ======================================================================
2018-05-17 11:09:44,363 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAIL: test_pylint (odoo.addons.test_pylint.tests.test_pylint.TestPyLint)
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: Traceback (most recent call last):
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/Documents/odoo/odoo/addons/test_pylint/tests/test_pylint.py", line 152, in test_pylint
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.fail("pylint test failed:\n" + (b"\n" + out + b"\n" + err).decode('utf-8').strip())
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` AssertionError: pylint test failed:
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` Traceback (most recent call last):
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/bin/pylint", line 11, in <module>
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     sys.exit(run_pylint())
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/__init__.py", line 17, in run_pylint
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     Run(sys.argv[1:])
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 1333, in __init__
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     linter.check(args)
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 755, in check
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self._do_check(files_or_modules)
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 886, in _do_check
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 967, in check_astroid_module
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     walker.walk(ast_node)
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 959, in walk
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.walk(child)
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 956, in walk
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     cb(astroid)
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/checkers/imports.py", line 368, in visit_import
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     importedmodnode = self._get_imported_module(node, name)
2018-05-17 11:09:44,364 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/checkers/imports.py", line 582, in _get_imported_module
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return importnode.do_import_module(modname)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/mixins.py", line 129, in do_import_module
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     relative_only=level and level >= 1)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 492, in import_module
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return MANAGER.ast_from_module_name(absmodname)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/manager.py", line 136, in ast_from_module_name
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return self.ast_from_file(filepath, modname, fallback=False)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/manager.py", line 86, in ast_from_file
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return AstroidBuilder(self).file_build(filepath, modname)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/builder.py", line 141, in file_build
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     module = self._data_build(data, modname, path)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/builder.py", line 185, in _data_build
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     module = builder.visit_module(node, modname, node_file, package)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 154, in visit_module
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     newnode.body = [self.visit(child, newnode) for child in node.body]
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 154, in <listcomp>
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     newnode.body = [self.visit(child, newnode) for child in node.body]
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return visit_method(node, parent, assign_ctx)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 957, in visit_classdef
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     newnode = super(TreeRebuilder3k, self).visit_classdef(node, parent, assign_ctx)
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 357, in visit_classdef
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     for child in node.body]
2018-05-17 11:09:44,365 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 357, in <listcomp>
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     for child in node.body]
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return visit_method(node, parent, assign_ctx)
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 543, in visit_functiondef
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     assign_ctx=assign_ctx)
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 528, in _visit_functiondef
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     for child in node.body]
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 528, in <listcomp>
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     for child in node.body]
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return visit_method(node, parent, assign_ctx)
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 447, in visit_expr
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     newnode.value = self.visit(node.value, newnode, assign_ctx)
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return visit_method(node, parent, assign_ctx)
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 315, in visit_call
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     for child in node.args]
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 315, in <listcomp>
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     for child in node.args]
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 167, in visit
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return visit_method(node, parent, assign_ctx)
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 549, in visit_generatorexp
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     newnode.elt = self.visit(node.elt, newnode, assign_ctx)
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/rebuilder.py", line 165, in visit
2018-05-17 11:09:44,366 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     visit_method = getattr(self, visit_name)
2018-05-17 11:09:44,367 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_joinedstr'
2018-05-17 11:09:44,367 32601 INFO testdb odoo.addons.test_pylint.tests.test_pylint: Ran 1 test in 4.399s
2018-05-17 11:09:44,367 32601 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAILED
2018-05-17 11:09:44,367 32601 INFO testdb odoo.addons.test_pylint.tests.test_pylint:  (failures=1)
2018-05-17 11:09:44,367 32601 ERROR testdb odoo.modules.module: Module test_pylint: 1 failures, 0 errors
2018-05-17 11:09:44,445 32601 INFO testdb odoo.modules.loading: 16 modules loaded in 4.59s, 2 queries
2018-05-17 11:09:44,729 32601 ERROR testdb odoo.modules.loading: At least one test failed when loading the modules.
2018-05-17 11:09:44,730 32601 INFO testdb odoo.service.server: All post-tested in 0.00s, 0 queries
```

</details>
<br />

* 1.9.0 (not working)
<details><summary>Click to show test output for 1.9.0</summary>

```
2018-05-17 11:12:01,070 4853 INFO testdb odoo.addons.test_pylint.tests.test_pylint: test_pylint (odoo.addons.test_pylint.tests.test_pylint.TestPyLint)
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAIL
2018-05-17 11:12:03,016 4853 INFO testdb odoo.addons.test_pylint.tests.test_pylint: ======================================================================
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAIL: test_pylint (odoo.addons.test_pylint.tests.test_pylint.TestPyLint)
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: Traceback (most recent call last):
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/Documents/odoo/odoo/addons/test_pylint/tests/test_pylint.py", line 152, in test_pylint
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.fail("pylint test failed:\n" + (b"\n" + out + b"\n" + err).decode('utf-8').strip())
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` AssertionError: pylint test failed:
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` Using config file /dev/null
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` Traceback (most recent call last):
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/bin/pylint", line 11, in <module>
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     sys.exit(run_pylint())
2018-05-17 11:12:03,016 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     Run(sys.argv[1:])
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     linter.check(args)
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self._do_check(files_or_modules)
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     walker.walk(ast_node)
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.walk(child)
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.walk(child)
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.walk(child)
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   [Previous line repeated 3 more times]
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 1011, in walk
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     cb(astroid)
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/checkers/python3.py", line 921, in visit_raise
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     node.inst is not None):
2018-05-17 11:12:03,017 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` AttributeError: 'Raise' object has no attribute 'inst'
2018-05-17 11:12:03,017 4853 INFO testdb odoo.addons.test_pylint.tests.test_pylint: Ran 1 test in 1.946s
2018-05-17 11:12:03,018 4853 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAILED
2018-05-17 11:12:03,018 4853 INFO testdb odoo.addons.test_pylint.tests.test_pylint:  (failures=1)
2018-05-17 11:12:03,018 4853 ERROR testdb odoo.modules.module: Module test_pylint: 1 failures, 0 errors
2018-05-17 11:12:03,096 4853 INFO testdb odoo.modules.loading: 16 modules loaded in 2.16s, 2 queries
2018-05-17 11:12:03,368 4853 ERROR testdb odoo.modules.loading: At least one test failed when loading the modules.
2018-05-17 11:12:03,370 4853 INFO testdb odoo.service.server: All post-tested in 0.00s, 0 queries
```

</details>
<br />

* 1.9.1 (not working)

<details><summary>Click to show test output for 1.9.1</summary>

```
2018-05-17 11:12:57,930 6943 INFO testdb odoo.addons.test_pylint.tests.test_pylint: test_pylint (odoo.addons.test_pylint.tests.test_pylint.TestPyLint)
2018-05-17 11:13:10,261 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAIL
2018-05-17 11:13:10,262 6943 INFO testdb odoo.addons.test_pylint.tests.test_pylint: ======================================================================
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAIL: test_pylint (odoo.addons.test_pylint.tests.test_pylint.TestPyLint)
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: Traceback (most recent call last):
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/Documents/odoo/odoo/addons/test_pylint/tests/test_pylint.py", line 152, in test_pylint
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.fail("pylint test failed:\n" + (b"\n" + out + b"\n" + err).decode('utf-8').strip())
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` AssertionError: pylint test failed:
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` Using config file /dev/null
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` Traceback (most recent call last):
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/bin/pylint", line 11, in <module>
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     sys.exit(run_pylint())
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     Run(sys.argv[1:])
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     linter.check(args)
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self._do_check(files_or_modules)
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     walker.walk(ast_node)
2018-05-17 11:13:10,262 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.walk(child)
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.walk(child)
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     self.walk(child)
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   [Previous line repeated 4 more times]
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/utils.py", line 1011, in walk
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     cb(astroid)
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/checkers/python3.py", line 797, in visit_call
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     if (_inferred_value_is_dict(inferred_receiver)
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/pylint/checkers/python3.py", line 58, in _inferred_value_is_dict
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return isinstance(value, astroid.Instance) and 'dict' in value.basenames
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `   File "/home/bigbear3001/.virtualenvs/venv/lib/python3.6/site-packages/astroid/bases.py", line 71, in __getattr__
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: `     return getattr(self._proxied, name)
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: ` AttributeError: 'FunctionDef' object has no attribute 'basenames'
2018-05-17 11:13:10,263 6943 INFO testdb odoo.addons.test_pylint.tests.test_pylint: Ran 1 test in 12.331s
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.addons.test_pylint.tests.test_pylint: FAILED
2018-05-17 11:13:10,263 6943 INFO testdb odoo.addons.test_pylint.tests.test_pylint:  (failures=1)
2018-05-17 11:13:10,263 6943 INFO testdb odoo.modules.module: odoo.addons.test_pylint.tests.test_pylint tested in 12.33s, 2 queries
2018-05-17 11:13:10,263 6943 ERROR testdb odoo.modules.module: Module test_pylint: 1 failures, 0 errors
2018-05-17 11:13:10,339 6943 INFO testdb odoo.modules.loading: 16 modules loaded in 12.54s, 2 queries
2018-05-17 11:13:10,618 6943 ERROR testdb odoo.modules.loading: At least one test failed when loading the modules.
2018-05-17 11:13:10,621 6943 INFO testdb odoo.service.server: All post-tested in 0.00s, 0 queries
```

<details>

Info
@wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
This seems to be an incompatibility specifically between Pylint 1.6 and Python 3.6: https://github.com/PyCQA/pylint/issues/1349

So maybe check with Pylint 1.6 & Python 3.5, and augment the check with a python-version check rather than just bump pylint?

**Comment by ap-wtioit** [comment]
@xmo-odoo thanks for the info, i updated the pull request to only require pylint 1.7.0 (or higher) in case the system is running on python 3.6.0 (or higher)

**Comment by wtaferner** [comment]
@xmo-odoo 
Anything missing to merge this?

**Comment by xmo-odoo** [comment]
@wtaferner nah I just forgot to merge it, thanks for the reminder

**Comment by wtaferner** [comment]
Thank you and you are welcome ;-)

**Pull request merged**
