### PR TITLE
[IMP] sale_stock: improve coverage of sale performance tests

### PR DESCRIPTION
**Pull request by Feyensv**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
@Feyensv since these seem to have quite some perf testing.. Can we expect performance improvements/changes for V16 on orders? 🤔

**Comment by Feyensv** [comment]
@Yenthe666 Hopefully yes, a big work on cleanup & perf is in progress.
* Base cleanup work and first pass landed earlier this month with https://github.com/odoo/odoo/pull/79093
* Next target (and work in progress) is cleaning the pricelist mess (I'm working on it and that's why I added those perf tests first) : https://github.com/odoo/odoo/pull/79605

Next steps in mind (no guarantees, but it might be nice to have for v16 as perf/cleanup is the target ^^)
* big cuts in e-commerce to rely on the cleaner core `sale` code (and probably perf improvements as well)
* More cleanups now that the core logic is cleaner.
* Other advanced performance investigations (and improvements :crossed_fingers:)

**Comment by Yenthe666** [comment]
Oooh nice! Those flame graphs on https://github.com/odoo/odoo/pull/79093 already look pretty promising actually!
Thanks for the detailed answer and links to PR's Feyens, this is really awesome 🥳

**Pull request closed without merging**
