### PR TITLE
[FIX][account] - aged_balance reconcile fix

### PR DESCRIPTION
**Pull request by ougc27**
Description of the issue/feature this PR addresses:
-------------------------------------------------------------------
Wrong journal entries in the Aged Payable / Receivable Report

Current behavior before PR:
------------------------------------

 Enviroment
-----------------
Runbot Enterprise  V10.0 [Runbot](http://269604-10-0-8d4155.runbot8.odoo.com/web/login)

## Configuration ##

- **Default Company Currency:** USD
- **Basic Accounting Configuration**

### Customer Invoice

- **Date of Invoice:** 2016-07-26
- **Amount With Taxes:** 115 USD

### Payment

- **Date of Payment:** 2016-10-28
- **Amount:** 115 USD

### Aged Receivable Report
**Max Date: 2016-10-31**

The report shows the invoice and the payment journal entries.
captura realizada el 2017-10-09 18 00 02

Desired behavior after PR is merged
------------------------------------------------ 
The report wouldn't shows this journal entries because that journal entries are posted and reconciled.
That balance only would show when I filter the report a date lower or equal at 2017-10-27 because the open balance was paid at 2017-10-28.

## Something like this:
**With date filter at 2017-10-31**
captura realizada el 2017-10-09 18 07 20

In this case the balance is zero, so there are not moves with open balances.

**With date filter at 2017-10-27**
captura realizada el 2017-10-09 18 09 47

In this case the balance is higher than zero and the invoice move is showed.

The main error is the partial reconcile's date validation because the picked date is the create date and not the payment date.

In [This video](https://youtu.be/1bkelgMHfew) i reproduce this bug.

Thank's and Regards!

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ougc27** [comment]
I already sign the CLA in #19983

**Comment by danger89** [comment]
Also merge to 11.0 branch?

**Comment by ougc27** [comment]
@danger89 thank you for your response.

This bug only impact version 9 and 10, in version 11 Odoo fix this issue so merge in 11 is not necessary.

Regards.

**Comment by mart-e** [comment]
@smetl I believe this is what you wanted to do in 11.0 with a8994b40754834b62038fcc0540cad766ac9e278 ?
According to your commit message, I believe this is an improvement, so should not be backported.
Could you confirm?

**Comment by smetl** [comment]
@mart-e This is an improvement but the standard behaviour in 10.0 is a bit shitty... I think It's not a bad idea to improve this in older versions.

**Comment by mart-e** [comment]
@smetl thanks! If you believe this one will not decrease the performances (stored field in your patch), ok for me to backport in v10

**Comment by qdp-odoo** [comment]
@nim-odoo what do you think? I'm not really in favor of backporting this since we were really reluctant to admit it was a bug before... but I let you the final word

**Comment by luistriana28** [comment]
@nim-odoo 
@qdp-odoo I'm not agree with you... if we are trying to make the older versions better even tho Odoo is working in v11, most people still working in older versions, if some guys agree with the PR & and it resolved important bugs, you should consider that.

**Comment by nim-odoo** [comment]
@qdp-odoo That's a change in behavior, so I wouldn't change this.

**Comment by mart-e** [comment]
Thank you for the update. Rejecting for [stability](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) reasons.

**Pull request closed without merging**
