### PR TITLE
[IMP] hr_payroll: Order salary rules by sequence, not by ID.

### PR DESCRIPTION
**Pull request by gustavovalverde**
The most important part of building salary rules is having them in the right sequence. If the salary rules are not order by this field, it's very hard to debug or realize that a salary is not working because is not before (or after) another.

This also makes it easier to know how the payslip will show the order of the salary rules.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't see any `sequence` field in the model definition in this file.

**Comment by gustavovalverde** [comment]
Thanks @pedrobaeza, my bad. Went a bit hasty there.

**Comment by pedrobaeza** [comment]
I'm not sure if this can be performed on stable. The field is indexed, so that's an extra point for accepting it.

**Comment by gustavovalverde** [comment]
If not, I'd just change it to master.

**Comment by mart-e** [comment]
Indeed, we can not change the `_order` in a stable version, it is a big change of behaviour (imagine a default using `self.search(domain, limit=1)`.
For master however, I guess it could make sense to add a sequence field.
@tivisse what do you think?

**Comment by mart-e** [comment]
Merged in master at 89273f8d72, thanks

**Pull request closed without merging**
