### PR TITLE
[FIX] website_slides: Traceback when no link provided for video

### PR DESCRIPTION
**Pull request by nboulif**
Issue

	Traceback raised in case no link provided when content type
	is a video.

Solution

	Format url only if provided.

Related fix : https://github.com/odoo/odoo/pull/54536
opw-2294344

### CODE REVIEW

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by nboulif** [comment]
@nle-odoo  Thanks for the review and updates:+1:

**Pull request closed without merging**
