### PR TITLE
Fix the default tax bug lp:796570.

### PR DESCRIPTION
**Pull request by anthony-muschang**
Fix the default tax bug https://code.launchpad.net/bugs/796570

As requested by Fabien (https://bugs.launchpad.net/openobject-addons/+bug/796570/comments/5) the bug have been corrected on all the modules where the default tax is ignored.

Some functions have been added on the module 'product_product' (get_supplier_taxes_ids and get_taxes_ids). Those functions are now used in the corrected modules and in account, hr_expense and hr_timesheet_invoice in order to have the same logic everywhere.

### CODE REVIEW

**Comment by antonylesuisse** [comment]
Better late than never, it still applies to v9 could you retarget it to v9 ? Please only implement the new api get_taxes (recordsset) not the get_taxes_ids (ids) versions.

**Comment by antonylesuisse** [comment]
I close this one as you need to target master.

**Comment by sbidoul** [comment]
@antonylesuisse would merge it on 9.0?

**Comment by antonylesuisse** [comment]
Possibly as it should not break any api, it will depends on the size/complexity of the diff, if not it will be master.

**Comment by blaggacao** [comment]
@anthony-muschang last made any public contributions some 8 month ago. I suggest, he is no longer avialable for maintenance :cry:   /cc @antonylesuisse

**Pull request closed without merging**
