### PR TITLE
[FIX] web_editor: allow dropdown in toolbar to move up

### PR DESCRIPTION
**Pull request by hubvd**
Steps to reproduce
==================

- Use the devtools to select a tablet layout
- Go to the Knowledge app
- Open a long article so that the text goes to the bottom
- Select some text on the last line
- Try to change the font size/style -> The dropdown goes outside the page

Cause of the issue
==================

The dynamic placement is disabled on the toolbar dropdowns with `data-bs-display="static"`

This was done to prevent an issue which shouldn't be present with bootstrap 5

Solution
========

Revert the following commit
https://github.com/odoo/odoo/pull/69644/commits/48bdd192550afd842cef76c2e218564d1c72621d)

opw-3142353

### CODE REVIEW

**Comment by bouvyd** [comment]
fiy this would break the editor in mass mailing (check that scrollbar ^^)
https://www.awesomescreenshot.com/video/14897029?key=c0f87bed71eff376e1d00a269c8c61fa

**Comment by dmo-odoo** [comment]
I was told that this PR would solve the issue: https://github.com/odoo/odoo/pull/110161

**Comment by dmo-odoo** [comment]
@hubvd Woops sorry I spoke too fast because that PR is in fact for master. :/

**Comment by hubvd** [comment]
My bad, I didn't see that either

**Comment by dmo-odoo** [comment]
@hubvd You might want to try backporting https://github.com/odoo/odoo/pull/110161/commits/0961698aca7e7711327de1fc7b9dc4620d55155a

I think that is a valid use case of `!important` because the mass_mailing widget is a custom widget which is not going to be reused elsewhere and the bug occurs because of the particular context of this widget, that it the fact that it uses a resizable iframe which seems to confuse the dropdown library.

**Comment by hubvd** [comment]
@dmo-odoo @bouvyd Indeed that commit fixes the issue in mass mailing. Note that I could only reproduce the issue with Chrome, not Firefox

**Comment by dmo-odoo** [comment]
@hubvd I'm confused. Is the first commit still needed then ?

**Comment by hubvd** [comment]
@dmo-odoo Yes, the first commit is to allow the dropdown to go up when there is no more place at the bottom such as in knowledge once the viewport is narrow enough.
image

And the second one is to fix what the dynamic position does to the mass_mailing sidebar. Note that the other PR also removes the `data-bs-display` attribute

**Comment by Zinston** [comment]
@hubvd @dmo-odoo I tested in @morm-odoo 's PR and it seems to do what you say it doesn't. Am I missing something?

image

**Comment by hubvd** [comment]
What I meant is that the PR also fixes the issue but also does other things. In this case, we only need the removal of `data-bs-display="static"` from the commit https://github.com/odoo/odoo/pull/110161/commits/9542591e3ba071a2a689aa0259ec86af98bfcbdd . That's why I didn't cherry pick that one.

**Comment by dmo-odoo** [comment]
@hubvd It is not clear to me who is expected to merge this PR. Is it me ? If yes then I'd like you to reuse the latest version of Morgane's commit if you don't mind, as it has useful comments about the change: https://github.com/odoo/odoo/pull/110161/commits/cfeddc6de76324447355c2464757dd2b4637d93c

**Comment by hubvd** [comment]
@dmo-odoo If you can then yes :)

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
