### PR TITLE
[FIX] l10n_ch: Add padding in qr report title (for bigger headers that hide it)

### PR DESCRIPTION
**Pull request by SimoneVagile**
Description of the issue/feature this PR addresses:
Add padding in qr report title (for bigger headers that hide it)

Current behavior before PR:
Some headers may hide Qr-bill title.

Desired behavior after PR is merged:
Qr-bill title is visible with any headers

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by SimoneVagile** [comment]
For CLA signing [https://github.com/odoo/odoo/pull/69490](https://github.com/odoo/odoo/pull/69490)

**Comment by bfr-o** [comment]
@SimoneVagile Can you show examples with screenshots ? How will the title be visible for even bigger headers ? 175px is an arbitraty choice, so why is it better than 150px ?

**Comment by SimoneVagile** [comment]
@bfr-o with 150px padding:
immagine
with 175px:
immagine

**Comment by bfr-o** [comment]
@SimoneVagile I still think that the fix is not very good because for even longer text we will have the same problem. Maybe @nle-odoo can give us his opinion ?

**Review by nle-odoo — COMMENTED** [review]
Hello,


In normal report I think the content is moved depending on paperformat field values (like header_spacing).

Here I think the paperformat is custom to no have any border and so we are not able to change header size (I have not tested).

So it seems ok to me to do this, the alternative would be to have a configuration somewhere in the interface that would be applied in the CSS.

As a side note, there were report about header margin, so I added the europeran paperformat default ones in XML:

https://github.com/odoo/odoo/blob/4cad0ab17ae1917b7acc71cfb0fe2255845cdc94/addons/l10n_ch/report/swissqr_report.xml#L27-L28

And if we want other value, the expectation is that you need to edit the view.

**Review by bfr-o — APPROVED** [review]

**Comment by bfr-o** [comment]
@SimoneVagile Can you change the commit message to follow the guidelines : https://www.odoo.com/documentation/master/reference/guidelines.html#git

**Comment by SimoneVagile** [comment]
> @SimoneVagile Can you change the commit message to follow the guidelines : https://www.odoo.com/documentation/master/reference/guidelines.html#git

@bfr-o thanks

**Comment by C3POdoo** [comment]
Dear @SimoneVagile,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
