### PR TITLE
[CLA] add Stephane Mangin to Camptocamp CLA

### PR DESCRIPTION
**Pull request by StephaneMangin**
Please add me has member of camptocamp organization.

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Review by yvaucher — APPROVED** [review]

**Comment by StephaneMangin** [comment]
Cc @mart-e 
Can you have a look and validate this PR please.
Thanx !

**Comment by mart-e** [comment]
Hi,

I see you have made two PR in 12 and 14.0 while this PR is in master. If you want the CLA signature to be present everywhere, you can submit it in the lowest supported version (12.0) and we will forward it to upper versions

**Comment by StephaneMangin** [comment]
> Hi,
> 
> I see you have made two PR in 12 and 14.0 while this PR is in master. If you want the CLA signature to be present everywhere, you can submit it in the lowest supported version (12.0) and we will forward it to upper versions

Oh ok, fine thanx. Done !

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
