### PR TITLE
[FIX] web_editor: fix switch direction on collapsed text

### PR DESCRIPTION
**Pull request by Goaman**
The command switch direction would not work in a collapsed text.

task-2983960

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Goaman** [comment]
@dmo-odoo updated.

**Comment by dmo-odoo** [comment]
@robodoo r+

**Comment by Goaman** [comment]
Conflict resolved.

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
