### PR TITLE
[FIX] analytic: applicability not changed when product/account change

### PR DESCRIPTION
**Pull request by h4818**
Avoid fetching plans when forced applicability

### CODE REVIEW

**Review by vin-odoo — APPROVED** [review]
Done in live on discord

**Comment by william-andre** [comment]
Care to detail the commit message a little bit more?

**Comment by h4818** [comment]
The plans are not retrieved again because the record is already changed in both props and nextProps.
This "fix" solves the above problem but causes another issue: it fetches the plans after the widget is opened leading to an empty widget.

**Comment by h4818** [comment]
@william-andre I have improved this fix here, it only calls `get_relevant_plans` when it is required.
https://github.com/odoo/odoo/pull/101400

**Comment by h4818** [comment]
https://github.com/odoo/odoo/pull/101400

**Pull request closed without merging**
