### PR TITLE
[CLA] Add IBM CLA signature agreement

### PR DESCRIPTION
**Pull request by ludovic-gasc**
Hi,

As discussed on #135526, could you merge this pull request in the 14.0 branch, and then port it into all the upper versions?

Thanks

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by Yenthe666** [comment]
Welcome to the Odoo world! 🙌 Let me know if you ever need help, I've been contributing my fair share in the Odoo world. ☺️

**Comment by dek-odoo** [comment]
Hey @ludovic-gasc 

Community is very happy 🎉 to see IBM contributing to Odoo, probably you also already know but you can also check out https:/github.com/oca.

Can you please share for community what are your interests ? What you would like to contribute ?

There is also an Odoo community mailing list in case you have any questions or any anything.

You can also engage with OCA community directly via email from here: 

Odoo Community Association (OCA)
Contributors <contributors@odoo-community.org>

https://odoo-community.org/groups

Kudos! 🎉🚀

**Comment by ludovic-gasc** [comment]
hi @Yenthe666 and @dek-odoo ,

Thanks for your warm welcome.

For now, our interest is that Odoo runs correctly on RedHat Podman and RedHat OpenShift, on the IBM Power hardware.
If you don't know IBM Power hardware, you can check our website: https://www.ibm.com/power

I have made a pull request for that: https://github.com/odoo/docker/pull/466
I have also added the support of ARM, but not been tested.

Have a nice weekend!

**Pull request closed without merging**
