### PR TITLE
[FIX] stock: fix default route

### PR DESCRIPTION
**Pull request by yosa-odoo**
Issue:
The call `_set_default_route_id` returns None. Whenever the iterator finds nothing, the route would be set to None.

### CODE REVIEW

**Comment by adwid** [comment]
Improve #89538
robodoo r+
For next versions, it will be fixed during the FW (see #89739)
fw-bot ignore

Good catch @MiquelRForgeFlow, thx
(Actually we realized that the problem is already present in 15.0)

**Comment by amoyaux** [comment]
I don't get why you didn't fix _set_default_route_id directly?

**Comment by adwid** [comment]
robodoo r-

@amoyaux Seeing the code before the fix, I though the logic was: take the first route, else call `_set_default`
And clearly the "take the first route" part had a problem, so we fixed it without calling into question the initial logic (maybe here is our mistake ?) 
We could ask to the commit author (fc692354b60aaa5e4331051056c758d21bc5b201) why did he do that ? haha
More seriously: I guess it's to avoid doing some `search` and `read_group` if we can already get a route thanks to the product ?

**Comment by adwid** [comment]
robodoo r+

@yosa-odoo You can apply the same correction for next versions. In master, just use `_set_default_route_id`

**Pull request closed without merging**
