### PR TITLE
[FIX] pos_adyen: Add logger for Adyen

### PR DESCRIPTION
**Pull request by qle-odoo**
To fix problems with lost payments in Adyen we add loggers

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qle-odoo** [comment]
@robodoo r+
@fw-bot up-to 14.0

**Comment by lse-odoo** [comment]
@qle-odoo would it be possible to merge it in 15 too ? it could be useful for me for one other ticket that I have on a similar issue.
OPW-2860153

**Comment by qle-odoo** [comment]
@fw-bot up-to 15.0
cc @lse-odoo

**Comment by pimodoo** [comment]
@fw-bot up to 15.0

**Pull request closed without merging**
