### PR TITLE
[REF] doc: backend - Use README.rst instead of description and use models/models.py

### PR DESCRIPTION
**Pull request by moylop260**
- [REF] doc: backend - Use README.rst instead of description
 - [REF] doc: backend - Use models/models.py standard
   - Because documentation uses "models/models.py" but the patch uses "models.py"
     - screen shot 2017-07-17 at 00 49 58
   - Because [odoo guidelines](https://www.odoo.com/documentation/10.0/reference/guidelines.html) explain `models/` folder.

### CODE REVIEW

**Comment by mart-e** [comment]
@nhomar this is the one I was talking about. Ok, not a couple of month ago but more 14 months ago :smile: 
After further analysis, it looks like the (first) problem is spaces instead of tabs inside the diff. Try with

```diff
diff --git a/doc/howtos/backend/exercise-creation b/doc/howtos/backend/exercise-creation
index 5004d08dc72..b48cbc71383 100644
--- a/doc/howtos/backend/exercise-creation
+++ b/doc/howtos/backend/exercise-creation
@@ -98,7 +98,7 @@ Index: addons/openacademy/demo.xml
 +</odoo>
 Index: addons/openacademy/models/__init__.py
 ===================================================================
---- /dev/null   1970-01-01 00:00:00.000000000 +0000
+--- /dev/null  1970-01-01 00:00:00.000000000 +0000
 +++ addons/openacademy/models/__init__.py  2014-08-26 17:25:49.791783523 +0200
 @@ -0,0 +1,2 @@
 +# -*- coding: utf-8 -*-
```

**Comment by moylop260** [comment]
@mart-e 
I just rebase the branch and fix conflicts
And I ran
`make html`
`sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html`
And it is working fine!

**Comment by mart-e** [comment]
@Feyensv have fun with patchqueue

**Comment by Feyensv** [comment]
The change from `module/models/models.py` to `module/models.py` should be trivial for patchqueue. 
But why is there a need to replace the description by a rst :thinking: ?

@mart-e

**Comment by mart-e** [comment]
Indeed, we do not use much of rst files for the descriptions in standard. We can keep it simple and keep in the manifest for the documentation.

**Pull request closed without merging**
