### PR TITLE
[FIX] name_search doesn't work in bom

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:

Current behavior before PR:
When you search in mrp.bom, and if you have lot of product (product with and without bom) with a same keyword, the return of search is not complete (some bom doesn't appear).

Desired behavior after PR is merged:
All bom appear

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Are you sure the problem is there? The `while True` seems very suspicious...
cc @tde-banana-odoo

**Comment by fmdl** [comment]
I don't know where is exactly the problem. But
1- lot of time name_search in called inside name_search, the parameter limit=limit is add. (it is the way I have found the fix)
2- when you search a bom, odoo search inside product_template, if the return of name search is limited at 100 (because there are not limit=limit), some product_template with a bom doesn't appear, if you have lot of product_template with the same keyword.
3- on my database it is works.

**Comment by gdgellatly** [comment]
It can't be the fix.

The while True is fine.

The algorithm is just saying,
keep searching products and getting their template ids until I'm over the
template limit, or I find no more products, excluding products from the
already found templates in each iteration.

Because if limit=limit is added, and limit is a default value of 100 in the
signature it makes no difference.  In any case the limit for a
product.template name_search call is unrelated to the product.product
call.  Hence why a limit clause here doesn't make sense (but does no
harm).  e.g. I have 3 templates, 1 with 1000 products, 1 with 10000, 1 with
5000 products.  Setting limit=1 or 1000 or 10000 or 100000 or not at all
should all yield the same list of templates.

The issue if there is one must be elsewhere and not the limit keyword.

**Comment by fmdl** [comment]
The issue is the name_search not return all result, because if it found some things : `if (not products) or (len(templates) > limit):
                break` it stop to search.

**Demonstration**
In my database I have lot of product with the keywords "bras" (102 elements)
image

**Without the fix**
Search "bras" in bom -> only one result
image

Search "fix" in bom -> more result and there some result with "bras" wich are not appear in the 1rt search. (strange)
image

**With the fix**
Search "bras" in bom -> show all result
image


Regards

**Comment by gdgellatly** [comment]
I  see the issue. It isn't the limit on products. It's the limit on
templates which is the issue. In first search you return 100 products which
is not greater than limit. So a second search occurs. It is just fluke it
worked.  It is the line len (templates) > limit which causes the problem.
That part of the condition should be removed or search views need no limit
where operator is ilike. Indeed the issue won't be confined to just boms
but any search view where product template is a relation.

**Comment by mart-e** [comment]
Yes, the `while True` works but it is not "fine".
As you say, the issue comes from the `len(templates) > limit` as `1 > None ` is `True`.

Why do we use the `name_search` of `product.product` anyway? They have different fields. If I am searching on the templates, why should I search on the barcode anyway?

As we are in master, I am in favor or making a proper name_search without this loop.

**Comment by gdgellatly** [comment]
I kind of disagree on the while true part.  I also think it is right to
search product.product.  they have the same fields via inherit.  In
refactor please consider the situation of 1 template with 20000 variants.
I know many people with exactly that use case. product name search could
use a refactor.  It is essentially unchanged since v5. multiple search
behavior means it is a lot slower than regular name search.

**Comment by gdgellatly** [comment]
In the meantime this relatively minor fix will fix it.

```python
if (not products) or (limit and (len(templates) > limit)):
```

**Comment by fmdl** [comment]
It's work.

**Comment by mart-e** [comment]
Thanks for the update, merged at 942d8a2c3f15cf3b4fa902c686d5a4a97685a41b as a quick fix but I still believe the whole method should be refactored.

**Comment by fmdl** [comment]
Dear I search in V9 how the function is build and I found limit=limit. And there the while True in other form. I hope the fix is correct.

`while (results and len(template_ids) < limit):
            domain = [('product_tmpl_id', 'not in', list(template_ids))]
            args = args if args is not None else []
            results = product_product.name_search(
                cr, user, name, args+domain, operator=operator, context=context, limit=limit)
            product_ids = [p[0] for p in results]
            for p in product_product.browse(cr, user, product_ids, context=context):
                template_ids.add(p.product_tmpl_id.id)`

Regards

**Pull request closed without merging**
