### PR TITLE
[FIX] web: add ar-sy to arab numbering system

### PR DESCRIPTION
**Pull request by yelizariev**
Backport of #107810

### CODE REVIEW

**Comment by yelizariev** [comment]
@fw-bot up to saas-15.3

**Comment by yelizariev** [comment]
v14 [has no](https://search.odooism.com/?q=NUMBERING_SYSTEMS&i=nope&files=&excludeFiles=po%24%7Cpot%24%7Cyml%24%7Cyaml%24%7Ccss%24%7C%2Fstatic%2Flib%2F%7C%2Ftests%2F&repos=14 
) `NUMBERING_SYSTEMS`, [no the file](https://github.com/odoo/odoo/blob/14.0/addons/web/static/src/core/l10n/localization_service.js)

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo retry

**Pull request closed without merging**
