### PR TITLE
[FIX] html_editor: load records consistently

### PR DESCRIPTION
**Pull request by thjo-odoo**
This commit fixes an issue with the new html_editor which doesn't consistently load records in the 'mail.composer.message' wizard.

Inside this wizard, you can load mail templates and save new ones. The issue occurs when a user creates a brand new template, then loads another template and come back to the newly created one.

The subject is correctly changed when changing records but the body, linked to the editor, doesn't change value.
This is caused by the lastValue not being refreshed when switching records so when the newly created record is loaded, the body doesn't update.

task-4116599

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dmo-odoo** [comment]
It's the right fix, thanks! Could you add a test please so I can r+ it?

**Comment by thjo-odoo** [comment]
@dmo-odoo 
Hello, here's the test for this fix if you want to have a look.

**Comment by dmo-odoo** [comment]
Thanks @thjo-odoo, I wanted to r+ this one but it has no task id.

**Comment by thjo-odoo** [comment]
There you go, my bad I was so focused on the test I forgot to check the commit message.

**Comment by dmo-odoo** [comment]
@thjo-odoo Runbot looks to be red :/

**Comment by thjo-odoo** [comment]
@dmo-odoo Looks like I finally fixed it.

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
