### PR TITLE
Remove eval from stock/models/product

### PR DESCRIPTION
**Pull request by hparfr**
**Description of the issue/feature this PR addresses:**
Improves code quality and performance

**Current behavior before PR:**
eval + 2 explicit casts

**Desired behavior after PR is merged:**
code clean and good perfs
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

Because in this file eval is unnecessary.

### CODE REVIEW

**Comment by mourad-ehm** [comment]
:+1:

**Comment by legalsylvain** [comment]
thanks LGTM. :+1:

**Comment by rvalyi** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by mart-e** [comment]
Hello,

Thank you for the patch, I have merged it in saas-11 at a989680b60c7b12a21fd60a132e923b40c67bd6c
It will soon be in master

**Comment by mart-e** [comment]
Hello @yucer ,

Actually this code was already broken before, I think it was introduced at b9853db8 but it is true, it should be fixed, thanks for the report.

**Comment by mart-e** [comment]
Fixed at 365d6a888dbb0b6b7829f6ea1f7dc70adf724ecf, thanks for the report.

**Pull request closed without merging**
