### PR TITLE
Change ldap_password to password type

### PR DESCRIPTION
**Pull request by Ppamungkas**
Description of the issue/feature this PR addresses:
LDAP password is show as text in the ldap authentication view
Current behavior before PR:
Password is shown as plaintext
Desired behavior after PR is merged:
Password is shown as stars (not visible)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e can you please review? I find it a good idea.

**Comment by mart-e** [comment]
Thanks for the modifications. I agree for master (as it is a view improvement)

@robodoo r+

**Comment by mart-e** [comment]
robodoo rebase-ff

**Comment by mart-e** [comment]
robodoo retry

**Pull request closed without merging**
