### PR TITLE
[FIX] account: fix tour that is checking css value

### PR DESCRIPTION
**Pull request by gawa-odoo**
This tour creates an indeterministic error, which is most probably 
due to the fact that the css is sometimes not loaded when we check it.
But we shouldn't check that the right css values are put, but check that the right class is put.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gawa-odoo** [comment]
Did a multi-build that passed, linked to runbot error https://runbot.odoo.com/web/#id=11769&view_type=form&model=runbot.build.error&menu_id=405&cids=1

**Comment by gawa-odoo** [comment]
> Is there any other test anywhere else that checks that the class matches the color?

I don't think there is any test that is testing that (but I'm not sure a tour would be a good place to check that).

> What is causing the CSS to not be loaded?

I don't know why (if not I would fix it directly :D ). What I can see is that the element with the right class exists, but it does not have any css color (rgb(0, 0, 0)).
I also guess that the tour began to break at https://github.com/odoo/odoo/commit/a1e7e3ef7e764062a3e5bf9840c55fe1bb4da578, as it matches the date and reverting it cause the issue to not appear anymore (More specifically, not the part about color or other modules, but the part about missing dependencies). But I don't see how it could relate to the fact that sometimes the color is not put

**Comment by gawa-odoo** [comment]
Well seems like the error does not happen anymore. Seems like https://github.com/odoo/odoo/pull/121633 fixed it without having any direct link afaik. (reverting the commit causes the error to happen again).
I will close this PR in the meantime

**Review by antoine162 — APPROVED** [review]
I guess, if there's no way of fixing the tour, then it makes sense to delete it. :+1:

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
