### PR TITLE
[IMP] models: new implementation of prefetching

### PR DESCRIPTION
**Pull request by rco-odoo**
Records come with a simpler data structure for prefetching, namely `record._prefetch_ids`, which is an iterable of record ids to prefetch.

### CODE REVIEW

**Comment by odony** [comment]
Would be interesting to check the result of [this test script](https://github.com/odoo/odoo/issues/18511#issue-246277667) after this patch too.

**Comment by odony** [comment]
@xmo-odoo Do you think you could verify the use case from #31804 and maybe revert that `with_prefetch()` if unnecessary after this PR?

**Comment by xmo-odoo** [comment]
@odony can probably be removed as part of the PR. I don't have the exact original repro case anymore, but installing the relevant-ish modules (contacts & base address extended), importing 1000 partners with partner_id set (all to the same parent) takes about the same time to import with or without the `with_prefetch()` on my machine (~1:35, ~35s SQL, ~60s Python, and 47040 queries).

**Comment by rco-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
