### PR TITLE
[FIX] Update the keyboard in French and shift in simple view

### PR DESCRIPTION
**Pull request by gregory-moka**
Description of the issue/feature this PR addresses: Upgrade and fix of the Point of sale app.
Current behavior before PR: The virtual keyboard on POS only have an English version, and it is hard to complete the customer sheet with it.
Desired behavior after PR is merged: We add a french version of the keyboard. The language of the virtual keyboard will be selected automatically. We also add the shift feature on the simple keyboard, to complete easily the customer sheet.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Thanks for the PR. I let the point of sale team decide but it is probably not a good idea to make a special case for French (why French and not another one?). Instead, we should look for a more modular approach.

As a side note, you have [signed the CLA](https://github.com/odoo/odoo/pull/34803) with a `@mokatourisme.fr` email address but this PR is made with a `@etu.univ-tours.fr` address, so the verification is failing.

**Comment by gregory-moka** [comment]
Hello @mart-e 
The fact is that the azerty keybord is used only in France. Sorry for that. 
Worst of it, at the end of 2018, they talked about changing the keys disposition : https://www.numerama.com/tech/477769-clavier-azerty-ameliore-quest-ce-qui-va-changer.html
(but not mandatory).

But, have a look on general feature (not only added french keboard) but : 
- Shift key = to add uppercase when you add new customer
- feature to type more than 1 letter as you want to edit the middle of the text

Thank for review

**Comment by mart-e** [comment]
The idea of having a different keyboard is good but I don't think it should be implemented this way.
- it should be possible to set many different locales
- to be set on the pos.config configuration, not based on the language of the user (let's say I want to use a Bépo layout)
- it could be good if we use a lib instead of hardcoding it ourself (and not having to watch out for all the layout changes like the one you showed)

**Comment by gregory-moka** [comment]
Ok, it's seems to be a bigger work than expected.
I'm waiting for POS Team
@Yenthe666 = Maybe an answer to this question https://github.com/odoo/odoo/issues/33331

**Comment by Yenthe666** [comment]
@switch87 this is for your interest too :)

**Comment by switch87** [comment]
@Yenthe666 I was already following in silence ;)

@gregory-moka There is a internal task on this issue but it is not on high priority at the moment. The specs of the tasks are not yet completely set but probably there will be a bigger priority for languages with a completely different alphabet then for azerty - qwerty. I will put this pr as a reference in the task. Thank you for your help :+1:

**Pull request closed without merging**
