### PR TITLE
[FIX] crm: use right domain in crm forecast

### PR DESCRIPTION
**Pull request by reth-odoo**
When converting to the new relational model the crm forecast model [1] the crm forecast model was modified to set the config domain before doing a readgroup call to the backend.

However that change should not affect the config directly as it will then stack the modified domain over and over leading to a domain that does not behave as expected.

Particularly, because of this change expanding the forecast to a new month does not show the leads
forecast for these months as the domain
already enforces the lead should be from before a certain date.

To 'forget' the change we just make webReadGroup use a shallow copy to invoke super. We do not need the config domain to match this readgroup domain for the feature to work.

Though it would be ideal, using a proxied config is impractical as many methods of RelationalModel make copies of the config when building a new one. Requiring many overrides to disable and reenable proxying making proxying almost pointless.

[1]: 218ad8456a06503dd508e7216edcffdc90b35cac

runbot-24491

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by thiryr** [comment]
Not sure how this got closed

**Comment by thiryr** [comment]
The logic for the issue with the test is layed out in `fill_tempora_service.js`, in `_computeEnd`

**Comment by thiryr** [comment]
Seems like 6b74a84e44a44119ca9b0945cd5abe71f1b1ef2d fixes the issue, not sure I agree with the way it's done but it seems to work.

I'll just fix the test so it can fail for this use case.

**Comment by thiryr** [comment]
@tde-banana-odoo I have a fresh runbot test fix here :pie: 

The issue itself is fixed in another commit listed above but I update the tour to be consistent across time (it could only have failed in september as it stands)

**Comment by tde-banana-odoo** [comment]
@abd-msyukyu-odoo

**Comment by abd-msyukyu-odoo** [comment]
@tde-banana-odoo I discussed with @thiryr and we thought of using/modifying a filter instead of crafting a magic domain that is prone to breaking with the new relational model API

The filter will be more robust than the fix I merged, because the final domain is reconstructed correctly from scratch by the SearchModel depending on the active filters, and we won't end up with the issue we had here that the leaves stacked on top of each other, and we won't have to "recognize that a domain has the forecast filter leaf" like I did in my commit

**Comment by reth-odoo** [comment]
@abd-msyukyu-odoo it's been a hot minute but if you want to check this one out for sanity some time before I consider moving it forward (low priority, of course)

Cheers

**Review by abd-msyukyu-odoo — COMMENTED** [review]
Hello @reth-odoo I did a small pass on your PR, I added some comments and I noted some things:


(not your PR), it seems that somewhere between 16.0 and master, we lost:
- the ability to keep expanded months when switching from a view to another (kanban -> pivot -> kanban) (we should have kept the opened months until a full reload)
- the ability to display filler empty months also in the graph view

(new with your PR):
- removing the `Upcoming Closings` filter conjointly disable the opening time bound AND the empty filling months, maybe we'd want 2 independent filters ? (not very important imo, it's fine if we loose this, but maybe to check with Luc)
- The filter `Upcoming Closings` is re-enabling itself at each view switch if it was disabled

Open for discussion if needed, cheers!

**Comment by reth-odoo** [comment]
Closing for now as it's just more complex in the end, will come back to it if ever relevant or if massive down time ^^

**Pull request closed without merging**
