### PR TITLE
[FIX] stock, purchase_stock: add product to PO if orderpoint

### PR DESCRIPTION
**Pull request by adwid**
Suppose a PO that has been generated thanks to reordering rule. When
changing the product of a line, if the user runs the scheduler, the old
product won't be added to the PO

To reproduce the error
1. Create a product P:
    - Product Type: Storable
    - Purchase: Add a vendor
    - Reordering rule:
        - Min = Max = 1
2. Run the scheduler
3. Update the generated PO:
    - Change the product of the line
4. Run the scheduler again
5. Open the PO

Error: The PO only contains one line (the one with the other product).
The PO should now contains a second line for P

OPW-2538707

### CODE REVIEW

**Comment by adwid** [comment]
@fw-bot up to 13.0

**Comment by amoyaux** [comment]
Why not only add a check on product_id in the current domain?

**Comment by adwid** [comment]
Because each time I try to inject some code in `/purchase_stock:Orderpoint._quantity_in_progress`, I always find a flow that still doesn't work. Eventually, I would need to perform a `read_group` and pay attention to the locations and UoMs, which is already done with the current code

**Comment by amoyaux** [comment]
Ok but there you add a tons of useless code for 12.0, it's not clean for example all the part for warehouse is for the replenish report that not exist in 12.0. Also it's a separate function because it's call at multiple places which is not the case here. Try to clean the existing code with the new one and fix the missing part instead of copy/paste

**Comment by adwid** [comment]
I removed the useless part and added a test
I know this code the function is only called once, but I find it cleaner, don't you ?

**Comment by amoyaux** [comment]
robodoo r+

**Pull request closed without merging**
