### PR TITLE
[IMP] l10n_es: add new taxes and associated tax tags

### PR DESCRIPTION
**Pull request by Shawcker**
Two taxes are not available in Odoo, and are currently supposed to be filled manually in the tax report. This commit adds those two taxes, with their associated tax tags. odoo/enterprise#34607 modifies the tax report in order to take them into account.

Task id=3085288

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rafaelbn** [comment]
This PR I think is the same than https://github.com/odoo/odoo/pull/107094

Commented in https://github.com/OCA/l10n-spain/issues/2527

https://github.com/moduon MT-1341 OPW-3007149

cc  @yajo @Shide

**Comment by yajo** [comment]
It seems to me like this code was copied from mine at https://github.com/odoo/odoo/pull/107094. It's not a problem, but it would be nice if at least you put me as a co-author of the commit. 😄 

If you didn't copy it, don't worry. I can see both aren't exactly the same.

**Comment by Shawcker** [comment]
Well, what a coincidence, because indeed I wasn't aware of your PR! @yajo 
That being said, it's really easy to have very similar code for this kind of stuff, as tax templates basically always follow the same pattern, so yeah this can happen :smile:

**Comment by chklop** [comment]
@yajo I got pinged some days ago by @rafaelbn, by the time I wrote the spec (November 29th) @Shawcker worked on it today. There was no intended copy/paste from our part, and as he said there wasn't 2000 solutions to this.
FYI we also have a PR on Enterprise to update our reports, of course.

**Review by rafaelbn — APPROVED** [review]
👍 Thank you!

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by yajo** [comment]
@Shawcker such a coincidence! Don't worry, thanks for the work!

**Pull request closed without merging**
