### PR TITLE
[FIX] l10n_in, l10n_in_xx: mistakenly product demo file load as real data

### PR DESCRIPTION
**Pull request by sza-odoo**
bug introduced by this commit #8226b6d5c4b23f28e9f050b81ecdc2d26b9b6e6b

task-2046174
pad link- https://pad.odoo.com/p/r.229b77de71c21fe5e37fa235a0bb622b

### CODE REVIEW

**Comment by jva-odoo** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by sswapnesh** [comment]
@sza-odoo  I know its already merged but It confuses others as file with suffix ` _demo.xml` is placed inside `data` on manifest. (https://github.com/odoo/odoo/pull/34874/files#diff-2c949ae89733e8e1a7f0d4c19301da8dR50)

Can we please rename this file at least?
Cc @jco-odoo 


Related to https://github.com/odoo/odoo/issues/35684

**Comment by jco-odoo** [comment]
@sswapnesh That makes sense.  @jva-odoo

**Comment by jva-odoo** [comment]
@sswapnesh By mistake this demo file load as the data file so in this commit we fix it.
No need to rename because of this file contains demo data, not real data.
So no confusion here. and don't create confusion. 😄 
CC @jco-odoo

**Comment by jco-odoo** [comment]
Ok @jva-odoo

**Pull request closed without merging**
