### PR TITLE
[CLA] signature for byuanit

### PR DESCRIPTION
**Pull request by byuanit**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by niyasraphy — COMMENTED** [review]
hi @byuanit ,
seems the runbot test is getting failed. one of the reason is: https://github.com/odoo/odoo/pull/114721#issuecomment-1461576559

please see the comment added by Martin in the above link.

also commit message should be in this format:  [CLA] signature for byuanit

thanks

**Comment by byuanit** [comment]
[CLA] signature for byuanit

**Comment by niyasraphy** [comment]
@byuanit ,
couldn't see any change in your commit message: https://github.com/odoo/odoo/pull/122456/commits/29dd6df6871f16a60b7b202d0dcd192b5142bc86

**Comment by byuanit** [comment]
I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

**Pull request closed without merging**
