### PR TITLE
[REF] crm: there is an extra closing curly brace for context field value which is a wrong syntax

### PR DESCRIPTION
**Pull request by kobros-tech**
WHY: 
There is one extra "}" curly brace which is not needed to close the opening one. I think it is a syntax error.

WHAT:
I removed the curly brace, it also needs testing to make sure, but it is very obvious to observe.

This is my first commit in the code, forgive me for not following the required instructions, but I was happy to commit in the documentation repository and I hope you help me with that in this repository too.

Thanks,

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by kobros-tech — COMMENTED** [review]
reviewed

**Comment by MiquelRForgeFlow** [comment]
You should adapt your commit too like explained in https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html#tag-and-module-name.

Also you should add a CLA commit like is it done in https://github.com/odoo/odoo/pull/164120.

**Comment by kobros-tech** [comment]
> You should adapt your commit too like explained in https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html#tag-and-module-name.
> 
> Also you should add a CLA commit like is it done in #164120.

Thanks for correcting me, I tried to improve the commit syntax and I hope it is OK.

**Comment by MiquelRForgeFlow** [comment]
You only changed the PR title, not the commit.

**Comment by kobros-tech** [comment]
> You only changed the PR title, not the commit.

Thanks for notifying me, I have just changed the commit header, please check it and forgive my mistakes.

**Comment by kobros-tech** [comment]
> You only changed the PR title, not the commit.

I added myself on CLA, but may be it still not proceeded.

**Comment by kobros-tech** [comment]
> > You only changed the PR title, not the commit.
> 
> I added myself on CLA, but may be it still not proceeded.

I am afraid if force push that I made to modify the commit name be not approved.

**Pull request closed without merging**
