### PR TITLE
[FIX] Removing image doesn't reflect on Kanban View

### PR DESCRIPTION
**Pull request by webkul**
Description of the issue/feature this PR addresses:

Issue in Products, Customers, Employees, Users and Vehicles.
Current behavior before PR:
After removing Image it still reflects on kanban view.

Desired behavior after PR is merged:
Image should not be visible on kanban view.

Also, it is related to #20046 
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by webkul** [comment]
@Yenthe666 could you check and let me know if this can be merged in? it is related to #20046

**Comment by Yenthe666** [comment]
Hi @webkul,

Thanks for the PR! Accepting it and merging it in is something that somebody from Odoo S.A itself needs to do. I guess this is something for @xmo-odoo or @mart-e to decide! 😉

**Comment by webkul** [comment]
:+1: ok, No problem will wait then.

**Comment by mart-e** [comment]
Sorry but this is the opposite of e5ef1c59172b7b8ebb1912e015fd41003ffc275d.
I agree it introduced a regression but this is not the proper fix as you are reintroducing what we were trying to fix.

**Pull request closed without merging**
