### PR TITLE
[FIX] tools: detect XML files as application/xml, not SVG

### PR DESCRIPTION
**Pull request by odony**
When support for SVG files was added at 1be50fdeafcd2b94f7b2f47d6e5bc4b6ebaceadd, `guess_mimetype()` was enhanced to detect SVG files.

The SVG detection entry uses a discriminant for accurate detection, but the fallback for regular XML was not correct, causing all XML files to be detected as SVG files.

The result is that non-admin users are unable to upload regular XML files, including via modules that generate XML documents for interchange purposes (example: SEPA files)

-------
**WIP**: the current behavior may actually be correct - so we need to determine whether arbitrary binary fields could be abused to serve malicious content. That is, will some browsers accept to execute scripting elements included in such a file, if directed to it.
If that is the case, the test on binary fields should be modified to block any XML-like file: like it does now, but with proper mime types and error messages. And any modules that generates XML files will have to use `sudo()` to save the field, when the content is known to be safe. 

-------

See also #26635

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Why not adding also a `test_mimetype_xml` method in odoo/addons/base/tests/test_mimetypes.py for testing also that part?

**Comment by pedrobaeza** [comment]
@odony in #30565, the need has arisen again. Is there anything that blocks this?

**Comment by pedrobaeza** [comment]
Included in #31849 with the mentioned test + comments from https://github.com/odoo/odoo/commit/1be50fdeafcd2b94f7b2f47d6e5bc4b6ebaceadd#r32741201

**Comment by nim-odoo** [comment]
Kind reminder about this since this is reported on a regular basis (as well as https://github.com/odoo/odoo/pull/36081). Maybe our new security expert @mart-e can move forward on it?

**Comment by nim-odoo** [comment]
@odony Since the merge of #47382, this PR is necessary. Could you please take some time on this one? Thanks

**Comment by fractalf** [comment]
I want to add that this code right here

```py
        # Detect if the binary content is an SVG for restricting its upload
        # only to system users.
        if value[:1] == b'P':  # Fast detection of first 6 bits of '<' (0x3C)
            decoded_value = base64.b64decode(value)
            # Full mimetype detection
            if (guess_mimetype(decoded_value).startswith('image/svg') and
                    not record.env.user._is_system()):
                raise UserError(_("Only admins can upload SVG files."))
```

will throw an exception for a **binary** that accidentally starts with these 6 bits. 

In our case, we are using a module that stores binary hashes as `fields.Binary`. This randomly fails every so often because of the hash being triggered by this "fast detection".

**Fix:** move this logic to **after** the check for binary or improve the check.

```py
        if isinstance(value, bytes):
            return psycopg2.Binary(value)

        # Do the funky svg check here
```

**Comment by enricostano** [comment]
Hi! Any news about this? Thanks!

**Comment by digitalsatori** [comment]
encounter the same issue here when importing an xlsx file.

**Comment by nle-odoo** [comment]
As noted in https://github.com/odoo/odoo/pull/65873 another issue is that currently, firefox will rewrite file extension if the mime type is an image. So for example downloading some .xml from odoo are transformed in .svg (but in my opinion this is more a firefox problem).

**Comment by C3POdoo** [comment]
Dear @odony,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
