### PR TITLE
[FIX]account: Close statement and go to bank statemen(s) button are made to work

### PR DESCRIPTION
**Pull request by mba-odoo**
Description of the issue/feature this PR addresses:
Issue: https://www.odoo.com/web#id=752732&view_type=form&model=project.issue&action=963&active_id=681&menu_id=4720
Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
doesn't work: the 'go to bank statement' button tries to close the bank statement ?

**Comment by mba-odoo** [comment]
@qsm-odoo , It's Works. 'go to bank statement' will redirect to bank statement view from rainbow man. see https://youtu.be/MTpHnWaQcWs  Thanks

**Comment by hmo-odoo** [comment]
merged at https://github.com/odoo/odoo/commit/93a1a0e2fdd029abfc772646010017bb6d6f9015

**Comment by qsm-odoo** [comment]
@mba-odoo I suppose you meant @qdp-odoo not me... :smile:

**Pull request closed without merging**
