### PR TITLE
[FIX] Inneficient domain for Up/Down Traceability button

### LINKED ISSUE #30977: Lot/Serial Number Traceability - memory error when having a very large number of moves
### Impacted versions:
Odoo 11
See also Enterprise contract Ticket #1937027

### Steps to reproduce:

Using a database where Products are moved with Serial numbers, and there are millions of stock moves.
Menu Inventory -> Master Data -> Lots/Serial Numbers
Choose a Serial Number, and on the from click on the "Up/Down Traceability"

### Current behavior:

Out of memory error.
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo11/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo11/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo11/odoo/addons/stock/models/stock_traceability.py", line 374, in get_html
    return self.create({}).with_context(given_context)._get_html()
  File "/opt/odoo11/odoo/addons/stock/models/stock_traceability.py", line 366, in _get_html
    rcontext['lines'] = self.with_context(context).get_lines()
  File "/opt/odoo11/odoo/addons/stock/models/stock_traceability.py", line 111, in get_lines
    ('move_id.returned_move_ids', '=', False),
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 3791, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo11/env/lib/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: invalid memory alloc request size 1073741824
```

### Expected behavior:

No error, and serial number move history shown.

### Video/Screenshot link (optional):

Initial investigation reveals that an inefficient search operation is being done, and on databases with a large number of stock moves it returns millions of records, and runs out od memory while trying to process them.

The offending code is probably this: https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_traceability.py#L107

### PR DESCRIPTION
**Pull request by dreispt**
Fixes #30977 

Removes the problematic condition in the domain, replacing it by a later filter on the search results. 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sle-odoo** [comment]
Nice, can you just update the commit message?

Something similar to
```
[FIX] stock: traceability report: performance

We replace an inefficient domain by a filtered.
```

Thanks in advance

**Comment by pedrobaeza** [comment]
For me this should lead to an improvement in the ORM with dot subfields in domains, as this is going to happen in more situations in other parts of code. Doing this alleviates this specific situation, but not the root problem, as ironically `filtered` option, which is done through Python, is usually slower. In this case it serves, as the set of data is already reduced to less than the other set.

We did some analysis on the ORM part in #30350 that can be interesting.

**Comment by sle-odoo** [comment]
cc @rco-odoo but i suppose these kind of things will be fixed on a case by case basis

**Comment by Yenthe666** [comment]
I agree with Pedro though, this will fix a symptom but not the core issue. If we can resolve it on ORM level it will be more efficient.

**Comment by dreispt** [comment]
@sle-odoo Thank. Will do that. I'll still to confirm the fix work in the database where it was found.

**Comment by dreispt** [comment]
@sle-odoo Changed the commit message, and did a successful the test on problematic database.
So it's ready to roll!

**Comment by pedrobaeza** [comment]
I would say that for our future us, it's better to put a comment in the code saying something similar to:
```
We use filtered instead of doing part of the domain, as it works better for the smaller set of data returned from the search than the currently SQL generated by the ORM with the subfield.
```

**Comment by lmignon** [comment]
FYI this problem has already been reported a long time ago and the core issue is described in https://github.com/odoo/odoo/issues/26702

**Comment by sle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
