### PR TITLE
Master product new API ppa

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rim-odoo** [comment]
@WHPODOO https://github.com/odoo/odoo/wiki/Contributing

**Comment by mart-e** [comment]
@WHPODOO all help is of course very welcome and we appreciate external reviews but these are development tasks following an internal process (with several level of reviews by different teams) at Odoo, they are not close to be ready yet so of course there is still much to say. Don't worry, we are not going to merge it yet.

If you wish to help us in the review process, I believe it would be more useful to check existing [pull request to review](https://github.com/odoo/odoo/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+-label%3ARD+-label%3Ablocked+-label%3AOE) where we definitely lack of manpower to review it.

Regards

**Comment by WHPODOO** [comment]
Good Morning @mart-e
Thank you so much for understanding me  and for the PR never do repeat,
I just want odoo code have some Quality.

**Comment by mart-e** [comment]
@WHPODOO I don't doubt it. Just saying it may be more efficient to concentrate on PR that are ready to merge. At Odoo, we sometimes create the pull request early, for the first level of code review (better to comment on the PR than on the commit), but that doesn't mean we are going to merge it like this. Some of our RD pull requests can be open [long before the merge](https://github.com/odoo/odoo/pulls?q=is%3Aopen+is%3Apr+label%3ARD+sort%3Acreated-asc).

We try to keep the development public and publish the pad with the specifications but the state of the development is not published (maybe it will one day) so it can be hard to understand at which state of the development an opened pull request is. Keep in mind that some developers are less experienced and of course, the code that they will first publish has a lot to be criticized about.
On the other hand external PR are supposed to be "ready to merge" so reviews from all parts are very welcomed.

This is why I advised you to avoid RD pull request as some Odoo developers may be surprised by the external review during an ongoing development (the code was going to change anyway) and may reply aggressively (sorry for that).
But all input welcome of course, open project :)

Also, if somehow, we merge some bad code (that was missed during the reviews), don't hesitate to submit a pull request to correct it.

**Comment by WHPODOO** [comment]
@mart-e  :+1:  sure keep it in my mind, I don't wanna to criticized any developer because i'm also developer.

**Comment by WHPODOO** [comment]
Hello @mart-e  ,
tag
This type of Lable i saw in PR so that PR reviewable or not ?

**Comment by mart-e** [comment]
@WHPODOO no, RD just means it's an internal PR  so I can easily [filter out](https://github.com/odoo/odoo/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+-label%3ARD+-label%3Ablocked+-label%3AOE) the external ones to review.

**Comment by WHPODOO** [comment]
Thank you That means when this both Lable is there i review. :+1:

**Pull request closed without merging**
