### PR TITLE
[FIX] payment_stripe_checkout_webhook: Json request not available

### PR DESCRIPTION
**Pull request by simongoffin**
Json request was not availalble since it's not a json rpc request from Odoo
but a request from Stripe

opw:2449738

### CODE REVIEW

**Comment by simongoffin** [comment]
@fw-bot up to 13.0

**Review by nle-odoo — APPROVED** [review]
looks good to me, it was already like this in the first original version

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
The diff is ok but the PR title and description, and the commit title and body are totally unrelated to the diff. You may also want to check if the opw is still correct!

**Review by AntoineVDV — APPROVED** [review]

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
