### PR TITLE
[FIX] base: Update res.country.state.csv for Turkey cities [CLA] Sign for ramazansubasi

### PR DESCRIPTION
**Pull request by ramazansubasi**
Edited the names cities of in Turkey:
Afyon: Afyonkarahisar
İçel: Mersin
K.maraş: Kahramanmaraş

Description of the issue/feature this PR addresses:
Turkey has 81 cities, at the Odoo 78 cities' names are correct but 3 cities' names are incorrect.

Current behaviour before PR:
When you search Mersin you can't see because it's name is İçel (İçel is the centre of Mersin) and other two cities: Afyon (Afyonkarahisar), K.maraş (Kahramanmaraş)

Desired behaviour after PR is merged:
All of the name cities of Turkey will be correct.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
@ramazansubasi Hello. Your commit messages are wrong. It should be:

[FIX] base: Update res.country.state.csv for Turkey cities
(no need content, it's self explanatory)

[CLA] Sign for ramazansubasi

**Comment by ramazansubasi** [comment]
Should I cancel this PR and make a new one or do you have any other suggestions?

**Comment by smetl** [comment]
@ramazansubasi You should not update the title of the PR but the commit messages

**Comment by smetl** [comment]
@ramazansubasi why? 😢

**Comment by ramazansubasi** [comment]
I opened a new PR: https://github.com/odoo/odoo/pull/126122

**Pull request closed without merging**
