### PR TITLE
[FIX] stock_account: add hook for eligible for COGS

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Let people be able to customize how to filter the condition.

**Description of the issue/feature this PR addresses:**

This comes from https://github.com/odoo/odoo/pull/66943 and https://github.com/odoo/odoo/pull/68511, but as those PRs seem that won't be merged, let's at least merge the hook they provide.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by svs-odoo** [comment]
Hello @MiquelRForgeFlow
I don't think we will merge it. I think it can be an useful change but it isn't a fix, more like a little refactoring, and we don't do refactor in stable unless it applies better performances, fixes something in the same time or addresses to an actual demand.

**Comment by MiquelRForgeFlow** [comment]
Hello @svs-odoo 

Adding a hook is more a fix than a refactor IMO

A refactor implies the code changes in a way that any module that depends on this one might be affected, by methods that call super or anything, a change of functionality code-wise or similar. But adding a hook for a long method don't fall on this category.

Instead, it's more of a fix, because it's in odoo guidelines to have methods short to be able to customize them by inheriting. As in this case, where there is a long method with bad inheritance, and we add a hook to improve the inheritance.

Furthermore, I have seen several times in other PRs hooks like this one being accepted in stable. What I am proposing here is a useful hook that people will like and am sure it has some demand, which is enough. In fact, we already need this one to avoid doing a very ugly monkey patch. And if you want, I can give you an enough long list of hooks that were added in stable to support my point and show you that adding hooks really makes people happy.

**Comment by svs-odoo** [comment]
That said, your commit is welcome in `master` anyway.

**Comment by MiquelRForgeFlow** [comment]
@svs-odoo done, branch points to `master` now

**Comment by svs-odoo** [comment]
robodoo r+

**Pull request closed without merging**
