### PR TITLE
[FIX] website: remove jQuery usage in page dependencies

### PR DESCRIPTION
**Pull request by agau-odoo**
task-4193605

- [x] Merge https://github.com/odoo/odoo/pull/179462
- [x] rebase this PR (drop commit 1)

### CODE REVIEW

**Review by aab-odoo — COMMENTED** [review]
Hello @agau-odoo 

Thanks for handling this, this was on my todo-list! While you're at it, there's another occurrence in view_hook.js `$(target).trigger("click.bs.collapse.data-api");`. I think that once can simply be removed now.

**Comment by agau-odoo** [comment]
@aab-odoo 
> Thanks for handling this, this was on my todo-list!
My pleasure :)

> While you're at it, there's another occurrence in view_hook.js `$(target).trigger("click.bs.collapse.data-api");`. I think that once can simply be removed now.
I'm not sure I understand how this works, neither do I see how it's related to the scope of my PR beyond being a jQuery usage in bootstrap stuff. Shouldn't it be in its own PR?

**Comment by aab-odoo** [comment]
It's related in the sense that jquery is used in a place where it's no longer available, so if this code was executed it would crash. The difference is that this one doesn't need to be adapted, as (I think) it's obsolete. It can thus simply be removed. No need for another PR/commit.

**Comment by aab-odoo** [comment]
Fun fact: https://github.com/odoo/odoo/pull/179462/files

**Comment by agau-odoo** [comment]
> No need for another PR/commit.

I disagree, if I'm going to add your requested change, then I'm actually gonna split my commit first to separate the fix in website and the fix in web (and remove the bootstrap jQuery usages first).

However, my PR's primary intention is to fix the bug in website, therefore:

> Fun fact: https://github.com/odoo/odoo/pull/179462/files

-> This PR should be merged first and I can rebase my own PR on it.

**Comment by aab-odoo** [comment]
Wow so much process. Let's try to be efficient, what do you think? Nevermind, I'll do the removal myself for the view hook.

**Review by qsm-odoo — APPROVED** [review]
> Wow so much process. Let's try to be efficient, what do you think? Nevermind, I'll do the removal myself for the view hook.

@aab-odoo A bit much, don't you think? Alice is quite new at Odoo, and upon request of fixing a website bug, she went ahead and tried to fix all related bugs that were created in all apps. And then she was trying to make things the proper way. I don't even think it was inefficient to merge two separate issues the way she wanted, on the contrary, I would have done the same (in the same PR if one did not already exist). Anyways, right or not, there was really no need to mock... I am being criticized if I do half of that, and I never do it without reason like here (and please don't say that "Wow so much process" was not mockery, you are better than that).

Anyways, she also found that the issue is invisible when enterprise is installed:
> I found that installing the iot app is what makes jQuery load. The `iot_longpolling` service uses `ensureJQuery()` to load jQuery at `start()`.

Might be relevant for you to know.

@agau-odoo I'll go ahead and merge but I found 2-3 independent issues, can you create a task and/or handle them:
- Click on the page dependencies link, the tooltop opens -> close the dialog, the tooltip stays and impossible to remove. It was already the case with the jQuery implementation (tested in 17.4).
- Strange I did not see it while deeply testing your work but for some reason, it was very annoying to me today: before your page properties work, upon page URL change, the "redirection" checkbox showed up immediately (no need to unfocus/press enter in the URL input). Seems important to keep that I think. You can probably implement that using `@api.onchange`, although not sure how that works. Can you check? :pray: 
- Not sure (flemme de retester): Is it possible that upon url change, the homepage checkbox unchecks itself? Not sure we discussed that flow, not sure that's what we want?)

@robodoo r+

**Pull request closed without merging**
