### PR TITLE
[FIX] sale_margin: sale margin accuracy

### PR DESCRIPTION
**Pull request by simongoffin**
Unit Price, Cost Price and Margin must have the same accuracy.

opw:632511

### CODE REVIEW

**Comment by beledouxdenis** [comment]
I do not understand the replace of `round(..., 2)` by `+ 0.005`. Can you explain ?

**Comment by simongoffin** [comment]
Alright!

**Comment by beledouxdenis** [comment]
Ok for the three `digits_compute`

Regarding the remove of `round` in `_product_margin`, I believe you should apply the currency rounding, as this is a price, even if the digits of product_price are greater. Just check how it's done in the regular `price_subtotal` of `sale.order` and apply the currency rounding accordingly :).

**Comment by beledouxdenis** [comment]
Closed with 0d74dce709fc237a26f8e194f546f0c61be60a33.

**Pull request closed without merging**
