### PR TITLE
[REF] base: Check user permission to write res.partner just if user

### PR DESCRIPTION
**Pull request by moylop260**
# Before this PR
If I change `res.partner` fields that doesn't affect `res.user` ones raise ACL error:
 - acl partner

# After this PR
If I change `res.partner` fields that doesn't affect `res.user` ones then allow it, but if a change affects users then raise ACL error:
 - partner ACL 2

### CODE REVIEW

**Comment by moylop260** [comment]
@nim-odoo 
What do you think in order to avoid assign `Access Right` to users that manage just partners?

**Comment by pedrobaeza** [comment]
What about image?

**Comment by mart-e** [comment]
Are you sure this is a good idea?
If I am not mistaken, the idea was that if a partner is linked to a user that is an employee, it requires more advanced access rights.
If you mange the CRM, you can modify the name of a portal user but probably not the one of your boss. You see my point :wink: ?

**Comment by moylop260** [comment]
Yes, you are right.

But that is another layer of ACL then another issue
currently, it is requesting you “Access Rigths” for fill a address or a VAT.
Then the user of hr_expense manager requires this special permission or a boss needs fill these fields.
Both are not practical.

What solution do you propose with my point and your point?

**Comment by odony** [comment]
For expenses you should use the partner that is linked to the employee via `address_home_id`. You will note that it's also where the bank account of the employee is taken, as you can see [here](https://github.com/odoo/odoo/blob/7ef65579028dff4220f7f0ce8dd6c4707fb2dd0a/addons/hr/models/hr.py#L139-L143).

**Comment by moylop260** [comment]
Thanks for complete answer @odony 
We will duplicate the partner then.

Note:
I don't like duplicate records since that we have enough duplicated:
1) User: `Joe Smith`
1.1) User -> Partner: `Joe Smith`
2) Partner without user: `Joe Smith`
3) Employee: `Joe Smith`

But it is the unique possible solution for odoo it is fine, at least I tried.

**Pull request closed without merging**
