### PR TITLE
[FIX] delivery: add test for delivery w/carrier when no linked sale order flow

### PR DESCRIPTION
**Pull request by mamatch**
This commit adds a test to a fix done in https://github.com/odoo/odoo/commit/afed7db30042e2ea91cdae292dadb7b6f742e33d

bug introduced during: https://github.com/odoo/odoo/pull/109298
opw-3162826

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
so the issue is that self.sale_id is an empty recordset and the compute method use ensure_one

looks good to me then, this or equivalent things (eg. having two if)

**Review by ticodoo — APPROVED** [review]
Fix looks fine to me. Commit could be cleaned up with the following: 
- It would be ideal if you reference the original PR that added in this bug  (https://github.com/odoo/odoo/pull/109298) so there's a record of this commit being needed in the original PR conversation (and so people know they need both commits for the fix to work properly)
- cleaned up English: 
```
[FIX] delivery: allow delivery w/carrier when no linked sale order
Steps to reproduce:
1. Create a delivery order (without link to a SO)
2. Add a carrier, like "DHL US"
3. Set some Done lines
4. Validate the picking

Expected result:
Delivery is validated with its info sent to the carrier 

Actual result:
Traceback due to `_compute_amount_total_without_delivery` running `ensure_one` on empty `sale.order` recordset

Solution:
Move the operation in the conditional statement which checks that.

bug introduced during: odoo/odoo#109298
opw-3162826
```
The solution part isn't necessary since we can see the solution in your code changes, but it doesn't hurt to have it in there. Remember that commit messages are for _Why_ you are making the code change (and clarifying anything not obvious in the code change such as limitations, the expected work flow if not obvious, etc.) not _What_ you are changing in the code (since we can see that in code) unless it's not straightforward changes. Also for bugfixes, you should write the expected result so people know behavior they should expect when they follow your steps if things were working correctly (so they can avoid breaking the expected behavior again later on.)

**Comment by DjamelTouati** [comment]
Fixed in: https://github.com/odoo/odoo/pull/112069
sorry for this PR, I had not seen it...

**Review by DjamelTouati — APPROVED** [review]
LGTM, could you r+ it @ticodoo, please ? Thanks

**Comment by DjamelTouati** [comment]
@mamatch could add the fix commit link and adapt your commit-msg to indicate that you are only adding a test to protects the use case please ?

**Comment by ticodoo** [comment]
@mamatch No need to add the [TEST] to your commit message.  Title can be something like:

`add test for delivery w/carrier when no linked sale order flow`

Rest looks good, thanks!

**Comment by ticodoo** [comment]
@mamatch oops didn't see that the runbot failed, needs to be rebased as well.

**Comment by mamatch** [comment]
@ticodoo done, thanks for the follow-up and the review :slightly_smiling_face:

**Comment by ticodoo** [comment]
Thanks!

@robodoo r+

**Pull request closed without merging**
