### PR TITLE
[IMP] hw_posbox_homepage: remove reboot button

### PR DESCRIPTION
**Pull request by loouis-t**
LNE Certification (scales certification) requires not to be able to reboot the IoT Box with a simple button.  
We removed it from the homepage.

Enterprise PR: [https://github.com/odoo/enterprise/pull/75074](https://github.com/odoo/enterprise/pull/75074)
Task: 4345731

### CODE REVIEW

**Review by Ysoroko — APPROVED** [review]

**Comment by lse-odoo** [comment]
@loouis-t what does "LNE" stands for ?

**Comment by loouis-t** [comment]
> @loouis-t what does "LNE" stands for ?

It's for **L**aboratoire **N**ational de métrologie et d'**E**ssais.

**Comment by Ysoroko** [comment]
@robodoo r+

**Comment by Ysoroko** [comment]
@robodoo retry

**Pull request closed without merging**
