### PR TITLE
[10.0][FIX] Product view: filter on warehouse/location

### PR DESCRIPTION
**Pull request by alexis-via**
See bug #28856 for full description.

I found the fix by looking at the code of v11.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
This won't be accepted in stable version as this is against stable policy. (affects Database scheme)

**Comment by alexis-via** [comment]
@sswapnesh if you know another way of fixing the bug, please propose it!

**Comment by sswapnesh** [comment]
There is no way to fix it in existing code, You have to add this fields in custom module.

**Comment by alexis-via** [comment]
So the bug will never be fixed in v10 ? @mart-e What's your opinion on this ?

**Comment by pedrobaeza** [comment]
Martin is on holidays, so you won't receive an answer in a while.

**Comment by Yenthe666** [comment]
Yep, Martin will be back on the 19'th. I actually don't see a way to fix this cleanly in stable. You could already make the same PR against master though, field changes are fine there.

**Comment by sswapnesh** [comment]
As said by Martin in https://github.com/odoo/odoo/pull/26477#issuecomment-414563705

**Comment by mart-e** [comment]
Hi,

Sorry but we can't accept this in a stable version. If I merged your patch, it would change the database structure, which is not allowed, please check our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean)

**Comment by alexis-via** [comment]
@pedrobaeza Do you think I should propose this to OCB ?

**Comment by pedrobaeza** [comment]
Well, this specific case can fit in OCB only if there's an smooth upgrade of the module (aka, there's no error when you update `stock` module). I don't know anything in OCA relying on these fields being stored. It would be a problem if they disappear, but it's not the case.

**Pull request closed without merging**
