### PR TITLE
[FW][15][LOC] l10n_ch: allow to use Creditor Reference in swiss payment QR-Bill

### PR DESCRIPTION
**Pull request by TeoGoddet**
Forward-Port-Of: https://github.com/odoo/odoo/pull/81269
It needed manual cherry pick to resolve some conflicts, see the diff
@lordkrandel as i cannot push on odoo-dev, i made a new PR

### CODE REVIEW

**Comment by TeoGoddet** [comment]
I added my cla commit on 14, do i need to add it again here ?

**Review by AntoineVDV — DISMISSED** [review]
Hello @TeoGoddet, for some reason you have changes in the file `payment_mollie/controllers/__init__.py`. Could you discard them? Thanks!

**Comment by lordkrandel** [comment]
> Forward-Port-Of: #81269 It needed manual cherry pick to resolve some conflicts, see the diff @lordkrandel as i cannot push on odoo-dev, i made a new PR

Very good :D I see the diff's not changed much, apart from that empty `__init__.py` to be removed.
But I still see some unrelated CI tests failing, probably not directly because of your code... I'd try rebasing to the latest to see if it went away.

```
AssertionError: Some js test failed
QUnit test failed: LunchKanbanView Mobile > basic rendering [message: "shouldn't have a visible 'lunch kanban' banner", actual: "false", expected: "true"]
1 / 71 tests failed.
```

**Comment by lordkrandel** [comment]
Unfortunately, there's an (or multiple) error(s) in the base of your branch.
Posting more commits won't be enough to get rid of them, you have to rebase. 

To rebase your commit:
```sh
cd <path/to/odoo>
git checkout 15.0
git pull
git checkout <your branch>
git rebase -i 15.0
git push -ff
```

Also, please drop the test commit :)

**Comment by lordkrandel** [comment]
Looks Good To Me!
@oco-odoo can you review and `r+` this "fw-port"?

**Comment by TeoGoddet** [comment]
Hello @lordkrandel ! 
Seems my first rebase was not on the right target
[9885447+teogoddet@users.noreply.github.com](mailto:9885447+teogoddet@users.noreply.github.com) regarding this it's because of the test commit i made from the github web interface, sorry for the noise

**Review by oco-odoo — APPROVED** [review]
@robodoo r+ rebase-ff

**Pull request closed without merging**
