### PR TITLE
[IMP] 8.0 Fontloader integration for odoo core to improve website loading speed

### PR DESCRIPTION
**Pull request by Benniphx**
### Short description

_Integrated a Fontloader to speedup the page loading process._
_After images, fonts are normally the largest assets in your web page. The Ubuntu font for example adds almost 250Kb to the page weight which is noticeable on slower mobile connections. Chrome, IE, Safari and Opera leave a blank space while the font is loaded so the page is unusable. Firefox and older versions of Opera show text in a fallback font then switch — known as a Flash of Unstyled Text (FOUT). Neither option is ideal._
#### Old behavior:
- fonts needs to be loaded and there is no good fall back while waiting
- this is noticeable on slower mobile connections
#### Current/Expected behavior:
- Improve Page Performance with a Fontloader
- Text is always shown to the user and if the font is loaded it switches.
- faster loading time
#### Goal:

My goal was it to integrate a Fontloader in the odoo core to speed up loading times of themes from odoo. It can easily adapted to new themes with bigger fonts.
It can be turned of in the backend if you do not like it.
###### Sidenodes:

There was an issue that the website object was not available in all templates (caused by the odoo custom Qweb integration "t-call-assets"). Therefore I updated the render function in the view class of the ir_ui_view.py file. It checks if the website object is in the values dictionary. If it is not in the values dictionary it calls the current website object and stores it in the values dictionary.

_here is a picture from testing I made:_

Image of Yaktocat

### CODE REVIEW

**Comment by jholze** [comment]
@odony would be a great feature for v8

**Comment by michaelkarrer81** [comment]
Great idea! Would be really nice in v8

**Comment by jholze** [comment]
We are using it on our website. Thanks for the compliments @michaelkarrer81 .

**Comment by beledouxdenis** [comment]
Dear, 

This proposal is very interesting, and looks very promising.

Nevertheless, this proposal has been done against a stable release, 8.0, for which we do not accept new features, at least not in the standard product.
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

I would therefore recommend to do this pull request against the branch currently in development, master, if you want this feature to be added in the standard product.

Or

Convert this to a separate module, using the inheritance mechanism, adding the needed column where you need it and altering the methods that you need, and push it on our apps platform.

We thank you for your contribution to make Odoo a better product.

Regards,

**Pull request closed without merging**
