### PR TITLE
[FIX] l10n_lu: fix reconcile flag in accounts template csv

### PR DESCRIPTION
**Pull request by sbidoul**
Description of the issue/feature this PR addresses:

In the l10n_lu account templates csv, correctly define the boolean reconcile column (f -> FALSE, t -> TRUE). This was fixed in v8 in https://github.com/odoo/odoo/commit/1d5651de5da533139d5a24a5aa6852b765cd73ca

Current behavior before PR:

When instantiating the l10n_lu COA, the reconcile flag is wrong.

Desired behavior after PR is merged:

Correct reconcile flag, as in v8.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sbidoul** [comment]
cc/ @adrienpeiffer 

@mart-e is a fast merge possible for this one?

**Comment by adrienpeiffer** [comment]
:+1: Thanks !

**Comment by adrienpeiffer** [comment]
OPW 688957

**Comment by adrienpeiffer** [comment]
Thanks @nim-odoo !

**Pull request closed without merging**
