### PR TITLE
[FIX] payment_authorize: make transaction request parameters extendable

### PR DESCRIPTION
**Pull request by jorenvo**
This makes it possible to patch only _prepare_transaction_request in
case parameters need to be added.

### CODE REVIEW

**Comment by jorenvo** [comment]
@AntoineVDV this is the authorize change we talked about.

**Review by AntoineVDV — APPROVED** [review]
LGTM and works on runbot :+1:

**Comment by AntoineVDV** [comment]
@robodoo r+

**Comment by odony** [comment]
Seeing that there are other cases where the `createTransactionRequest` API is called, I thought maybe the new helper would be expected to be used in all cases (i.e. also `capture()`, `void()`, `refund()`).

But maybe the tx params are too different to come up with an abstraction that works well enough without being totally overkill. If that's the case, perhaps the method name should be slightly more specific, e.g. `_prepare_authorization_transaction_request()`, to disambiguate its use?
I know I suggested the current name ;-)

**Comment by jorenvo** [comment]
@odony indeed, I didn't want to make it too complex and we don't use the others internally. I agree your name is less ambiguous: https://github.com/odoo/odoo/pull/73334.

**Pull request closed without merging**
