### PR TITLE
[FIX] date widget icon hides the end of the date in Firefox on OSX

### PR DESCRIPTION
**Pull request by ovnicraft**
Include sign Odoo CLA

### CODE REVIEW

**Comment by ovnicraft** [comment]
IDK wuhy runbot dont see CLA

**Comment by ovnicraft** [comment]
@odony why CLA doesnt check? i commited

**Comment by odony** [comment]
@ovnicraft Because you signed the CLA with ovnicraft@g... and your github config uses cristian.salamea@g... so there is no match. You can add the second email in your CLA signature or change the `user.email` in your git config.

**Comment by ovnicraft** [comment]
@odony well looks green now

**Comment by odony** [comment]
@ovnicraft thanks for fixing the CLA, now when you're updating a `sass` file you need to update the corresponding `css` file too (`base.css` here). Maybe you could also post a screenshot of the glitch you're trying to fix, so we understand better your issue?

@sle-odoo you love reviewing CSS changes, right? ;-)

**Comment by ovnicraft** [comment]
In OSX firefox looks like this, but works fine on linux.

date field error

looks like i am in the wrong way.
@sle-odoo any feedback ?

**Comment by ovnicraft** [comment]
I can confirm this on OSX:
Firefox: 40.0.3
Safari: Versión 8.0.8 (10600.8.9)

**Comment by ovnicraft** [comment]
@sle-odoo any news around ?

**Comment by ovnicraft** [comment]
@odony @sle-odoo there any news about this ?

**Comment by tivisse** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards

**Comment by dreispt** [comment]
@ovnicraft You can propose this for [OCB](https://github.com/OCA/OCB) if you like. The unsupported versions are still open for fixes there.

**Comment by ovnicraft** [comment]
@tivisse i know that so fix was proposed 3 years ago.

@dreispt Yes, i will create a PR on OCA, thanks !

**Pull request closed without merging**
