### PR TITLE
[IMP] point_of_sale,hw_escpos: print arabic tickets

### PR DESCRIPTION
**Pull request by switch87**
Make it possible to print Arabic tickets by printing images instead of text.

Because escpos cannot print in Arabic the pos should send images instead of text to solve this problem.

task: https://www.odoo.com/web#id=1872569&action=333&active_id=1428&model=project.task&view_type=form&menu_id=

img_20181115_171142

### CODE REVIEW

**Comment by mart-e** [comment]
Clever hack.
Is the Arabic correctly formatted? While the body looks correct, the first line seems to be split char-by-char without ligatures (which is important in Arabic). 

Also, could be nice if we can really flip the ticket, not just the text but the layout too.

pos-ar

**Comment by jorenvo** [comment]
I like this approach. I didn't look very deeply but what is the reason you have to resize in `hw_escpos`? Can't we immediately render the bitmap with the correct size client-side? Apart from perhaps performance benefits it should also avoid the messy aliasing artifacts that are visible in your photo.

**Comment by switch87** [comment]
@jorenvo the artefacts have nothing to do with the resizing, this is the best I could get out of these printers, and I tried a lot of ways. including not resizing but the later did not influence the result. Changing the font a little made the print a little better, like I did on this pr. 

Since the html for the image has to be shown on the screen of the client it is also not possible to make a ticket of 550px only for this purpose and on screen this would be much to big, especially for mobile browsers.

**Comment by switch87** [comment]
@mart-e The strange thing is that my local db did not mirror my interface and ticket layout like in runbot and your screenshot for right to left languages. I did not investigate further on this. What is done for making the Arabic ticket is actually nothing more than making a screenshot of the ticket div shown in your screenshot. Or with other words, if you would have printed the ticket in your screenshot the layout would be flipped and look exactly like on your screen. :+1:

**Comment by mart-e** [comment]
> my local db did not mirror my interface

Install [rtlcss](https://rtlcss.com/) ;-)

**Comment by rdeodoo** [comment]
Hi, as this task was cancelled, should this one be left open?

**Pull request closed without merging**
