### PR TITLE
[MERGE] tests: refactor tests and particulary ChromeBrowser class

### PR DESCRIPTION
**Pull request by d-fence**
* Refactor ChromeBrowser to use a main loop instead of 3 different loops
* Enable screenshot on failure by default (screenshot goes in data_dir/tests)
* Remove deprecated at_install and post_install functions
* Rename phantom_js calls to browser_js
* Merge TreeCase and BaseCase classes

### CODE REVIEW

**Comment by antonylesuisse** [comment]
Looks ok, do we need the different exceptions ?

**Comment by d-fence** [comment]
> Looks ok, do we need the different exceptions ?

Yep, I think it's clearer when you read the logs instead of "AssertionError: False is not true ..."

**Comment by d-fence** [comment]
@robodoo rebase-merge

**Review by Xavier-Do — COMMENTED** [review]
Nice one, just some small comments about code readability.

**Comment by d-fence** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
> @robodoo r+

@d-fence Need a small rebase then ok for the freeze.

**Pull request closed without merging**
