### PR TITLE
[FIX] website_sale: correct misspelling in website settings

### PR DESCRIPTION
**Pull request by pivi-odoo**
Corrects misspelling of "abandonned" -> "abandoned" and incorrect word "authentified" -> "authenticated" in website+e-commerce settings.

Steps:
- Install E-commerce module
- Navigate to Website -> Configuration -> Settings
- Search for "Abandoned Cart" section

Problem was introduced in commit: 73483c8e5ab53a2ea3fb678f40e04e2cfc2e7ef0

opw-2949403

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
Hi,


Since there is customers instances in saas-15.3, it might be better to target it instead.

Usually we try not to break translations in stable by changing the source (so master would be better), but saas-15.3 is relatively recent and the translations you are changing have not been translated on [transifex](https://www.transifex.com/odoo/odoo-s15-3/dashboard/), so it seems ok to fix it from saas-15.3.

To rebase the branch on 15.3, you can change the target in github:

> 2022-08-23-111445_574x264_scrot

> 2022-08-23-111501_913x263_scrot

and cherry-pick your commit in saas-15.3 and push that on this branch, for example:

```sh
git fetch origin saas-15.3
git checkout origin/saas-15.3
git branch -d master-opw-2949403-pivi # might need D instead of d to force suppression)
git checkout -b master-opw-2949403-pivi
git cherry-pick 0a93b2ce78c13209974add1fbcba0b1be1d4236e
git push dev master-opw-2949403-pivi --force-with-lease # dev may need to be replaced by local odoo-dev repo name
```

**Review by nle-odoo — APPROVED** [review]
robodoo r+

**Review by nle-odoo — APPROVED** [review]
robodoo r+

**Comment by Williambraecky** [comment]
Thanks!

**Pull request closed without merging**
