### PR TITLE
[IMP] mail: show older messages by scrolling

### PR DESCRIPTION
**Pull request by pka-odoo**
Task : 
https://www.odoo.com/web?#id=33958&view_type=form&model=project.task&action=327&menu_id=4720
Pad:
https://pad.odoo.com/p/r.c93f2456e4a2f6953c0012e794f9e832

Description of the issue/feature this PR addresses:
Instead of showing « show older message » at the bottom of the chatter, when scrolling to the bottom of the page, it should load the older messages automatically.

Current behavior before PR:
By clicking on « show older message », it should load the older messages automatically.

Desired behavior after PR is merged:
It loads the older messages automatically when scrolling.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mba-odoo** [comment]
LGTM

**Comment by aab-odoo** [comment]
Hello,

Could you add a Discuss test case?

Thanks

**Comment by dbh-odoo** [comment]
@aab-odoo qunit for discuss is added can you please review?

**Comment by rdeodoo** [comment]
Merged instead with https://github.com/odoo/odoo/commit/ea97fa3ac6f51eb982d97812a6082616fff6e167

**Pull request closed without merging**
