### PR TITLE
[FIX] website_portal_sale: Order list indicates "Invoiced" state when…

### PR DESCRIPTION
**Pull request by eantones**
… order is "In progress" and not necessarily invoiced yet

**Description of the issue/feature this PR addresses:** Order list indicates "Invoiced" state when order is "In progress" and not necessarily invoiced yet.

**Current behavior before PR:** Order line shows "Invoiced" when order has just been created and it's in "progress" state.

**Desired behavior after PR is merged:** Order shows "In preparation" to inform the user his/her order has been received and it's being taken care.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

Eric

### CODE REVIEW

**Comment by sergio-incaser** [comment]
:+1

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (57/50 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:52072 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aarmG-0008BI-It
	for fred@ventureacceleration.com; Tue, 01 Mar 2016 16:24:20 -0500
Date: Tue, 01 Mar 2016 09:35:39 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1456853739;
	bh=LdUEv1XX7oAw+QWotqQqh9Gw8vj0T/GTeUyTtY23sLc=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=xRqyh4RBgB2+XuGarpjmvXvBDym3ExkKxtDp/yHR0HLhGLAhXag1sE+A8sprCybTD
	 0BbEXX58RUYBebPmswwVlRhNdAgdo8lB+5bfzmMpRhyW/kOFFONa7BZ4xmSufvOJoz
	 o6QXfTEDfFX29/i7YiJj6uzwMnTR/m53fmUh1oZA=

**Comment by antonylesuisse** [comment]
The portal template is buggy but it seems the fix is wrong too as:

- state in ('draft', 'sent', 'sale', 'done','cancel'),
- invoice_status in ('upselling', 'invoiced', 'to invoice', 'no',)

Or am i missing something ?

**Comment by dbo-odoo** [comment]
@eantones 
@antonylesuisse is indeed correct, this module has not been adapted to reflect the SO states in v9.
The states that matter in the frontend are 'sale' (Confirmed i guess?) and 'done' (Done?).

I would not necessarily take the invoice_status into account to avoid unnecessary complexity imho (since the invoices are listed visibly just below the sales; and even if the SO is fully invoiced, it does not mean that the invoice has been validated or sent to the customer)

**Comment by eantones** [comment]
@antonylesuisse @dbo-odoo ok, then I agree, "Confirmed" status is better than "In preparation" in that context but never "invoiced" status. As you said, taking the invoice_status into account is not necessary at all.

**Comment by rdeodoo** [comment]
@dbo-odoo If I understand correctly, the order.state value `progress`, `shipping_except`, `invoice_except` got removed from v8 to v9 (with [this commit](https://github.com/odoo/odoo/commit/94716a3f14d929574c46ef165e4364d12a5903ed)?)
Can't we just removed theses 2 `<t-if>`:
```
<t t-if="order.state == 'progress'">
...
<t t-if="order.state in ['shipping_except','invoice_except']">
```
Note that they are also still present in v11

**Pull request closed without merging**
