### PR TITLE
[FIX] core: upgrading module should not add XML id for custom fields

### PR DESCRIPTION
**Pull request by rco-odoo**
This happens when upgrading the module that introduces a model: the
custom fields on the model are given an XML id for the module.

Because of the issue, some existing databases may have XML ids for
custom fields.  For those cases, the code must mark those XML ids as
"loaded", otherwise those custom fields could be deleted at the next
module upgrade (records with XML ids corresponding to a module are
deleted if their XML id hasn't been "loaded" during the module upgrade.)

### CODE REVIEW

**Comment by rco-odoo** [comment]
The review should be the same as https://github.com/odoo/odoo/pull/94538.

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by beledouxdenis** [comment]
@robodoo r-

This is way too dangerous in stable.

If the external identifiers have already been created in production databases, they already did the `-u` which already created the external identifier for manual fields (`x_` fields), and this patch is deployed, and they re-do a `-u`, the fields, along their column in the database, will be deleted.

e.g. I added a `x_test` fields on fleet.
The first `-u` without the patch adds the xmlid
The second `-u` without the patch deletes the field along it's column in the database.

```
2022-06-24 14:56:55,640 22 INFO 14.0 odoo.addons.base.models.ir_model: Deleting 2959@ir.model.fields (fleet.field_fleet_vehicle__x_test)
2022-06-24 14:56:55,642 22 INFO 14.0 odoo.addons.base.models.ir_model: Deleting field fleet.vehicle.x_test (hint: fields should be explicitly removed by an upgrade script)
```

**Comment by rco-odoo** [comment]
@beledouxdenis ouch!  Thanks for pointing that out!
I will probably reintroduce a trick that is present in former versions: pretend the xml id was "updated" on custom fields to prevent the module upgrade from deleting it...

**Comment by rco-odoo** [comment]
@tfr-odoo @beledouxdenis this should do the job without the issue mentioned by Denis.  I have tested upgrading a module with a module having two custom fields: one with an XML id and one without.  Both fields are still present after the module upgrade.

**Comment by tfr-odoo** [comment]
Scenario Tested

Create a field on crm.lead
Update the module
Go an xml_id 

Apply the patch
Update the module
-> Field is still there

Create a new field on crm.lead
update crm
-> New field has no xml_id
-> both field remains


So it seems good to me

**Comment by rco-odoo** [comment]
@beledouxdenis what do you think?
The patch essentially reproduces the same fix as https://github.com/odoo/odoo/pull/34563.

**Comment by beledouxdenis** [comment]
Though this will prevent new xmlid record to be created, this won't correct the past and remove the wrong xmlid records.
So, Thibault will still have to adapt his CLOC algorithm anyway to make an exception for manual fields having an xml id linked to a standard module.

I believe the initial goal was to not have to adapt the CLOC algorithm. If we still have to, I don't believe this is worth to attempt correcting this in stable. If there is no other issue than the CLOC algorithm having xmlid records for manual fields, I wouldn't take the risk to solve this in stable, as this doesn't seem to solve anything in stable. 

If I quote the stable policy:

> stable patches must have a good value/risk ratio. If risk is too high or value too low, it must not be merged at all in stable (rather in the development series)

In this case, the risk is higher than the added value of the patch, as we still have to adapt the CLOC algorithm despite this patch.

However, I have to take into account the case of @aj-fuentes and @jjmaksoud 
https://github.com/odoo/upgrade-specific/pull/3834

I am not sure if this patch would solve the case either. @jjmaksoud Can you test if this patch against the upgrade request you wrote odoo/upgrade-specific#3834 for would solve the issue without the need of this specific upgrade script ?

To me, what should be done:
 - Merge the former patch, with the simple `if field.manual`, in master,
 - Write an upgrade script alongside the above PR, to remove all xmlid records linked to manual fields.
 - Potentially, apply the above script in the upgrade to 15.0 as well, to overcome the issue `odoo/upgrade-specific#3834`. The xmlid records will be created again when upgrading to 15.0, but the issue of odoo/upgrade-specific#3834 will be mitigated.

My whole opinion is based on the fact having these xmlid records for manual fields doesn't lead to any issue in stable. If this isn't the case, my opinion would be totally different :D

**Comment by jjmaksoud** [comment]
> I am not sure if this patch would solve the case either. @jjmaksoud Can you test if this patch against the upgrade request you wrote https://github.com/odoo/upgrade-specific/pull/3834 for would solve the issue without the need of this specific upgrade script ?

I applied this patch on 15 and 15.2 (request target), no xml ids were created for manual fields, the upgrade finished successfully and all manual fields remained.

**Comment by rco-odoo** [comment]
> Write an upgrade script alongside the above PR, to remove all xmlid records linked to manual fields.

Be careful with this one: a custom field may have a valid XML id in the case where the custom field is part of a module's data.  This is the case for module `studio_customization`, for instance.

**Comment by rco-odoo** [comment]
> In this case, the risk is higher than the added value of the patch, as we still have to adapt the CLOC algorithm despite this patch.

I pretty much agree with the argument.  I will not insist for merging this patch.
@tfr-odoo what's your take on this?

**Comment by tfr-odoo** [comment]
My plan was to not support the use case in the cloc since we can fix it. Indeed there will be some legacy DB with those xml_id. If the issue has been unnotice for 2 years it means there is not a lot of problematic database. The few can be easily spotted and fixed during the upgrade by the custom upgrade team. 

But it can live with this behavior, it just make the cloc code more complex and a bit weird because I cannot count those field in the standard module but I have to count them has having no module or an importable one.

**Comment by jjmaksoud** [comment]
Tried again with the request related to https://github.com/odoo/upgrade-specific/pull/3834, I applied the patch this time only on the last target version (15.2) to see what happens if the xmlids existed in the db:
- source v14 has no xmlids for manual fields
- v15 created them
- upgrade failed on v15.2: the manual field was being removed

Other manual fields no not have a problem, they have xmlids and are not being deleted after the module loads (with and without the patch)

**Comment by C3POdoo** [comment]
Dear @rco-odoo,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
