### PR TITLE
[FIX] website_sale: properly set session variable

### PR DESCRIPTION
**Pull request by Abdessamad-z**
To reproduce the bug:
- Add extra step during checkout
- Make Sign in/up at check out Mandatory
- Add a non-service product to the cart without being logged in and proceed to checkout
- Create an account and once logged in continue the checkout process normally until payment is done

When the process is done, a request is sent to /shop/payment/validate, and we get a server error message since we try to fetch `sale_last_order_id` from the session but it's not set.

To simplify, the buying process goes like this: cart > [sign in/up] > [delivery] > checkout > extra_step or confirm_order > payment. The issue is that `sale_last_order_id` is set in confirm_order, which we don't pass through if we have
extra_step enabled. To fix that, I moved the set operation a step earlier.

opw-3988807

### CODE REVIEW

**Review by abla001 — COMMENTED** [review]
I tested locally on fresh database with only `website_sale` installed, and I'm not able to reproduce the bug, but I also tested on runbot and I got the error which probably means that the error is not coming from `website_sale` but there is a model that makes us loose this info while overriding !

**Comment by Abdessamad-z** [comment]
Thanks for the review. I will check and get back to you.

**Comment by Abdessamad-z** [comment]
I have rechecked and it seems to me that the reason behind our different result is the type of product added to the cart. When adding only service product the routes taken change
https://github.com/odoo/odoo/blob/1db47a80dfd51f1b5c1463bf7891b7e0bc84a727/addons/website_sale/controllers/main.py#L1334-L1335
so that we pass through `/shop/confirm_order`. Thanks for the remark.

**Review by abla001 — APPROVED** [review]
LGTM then !

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
