### PR TITLE
[FIX] account: rounding error

### PR DESCRIPTION
**Pull request by nim-odoo**
opw-728606

### CODE REVIEW

**Comment by nim-odoo** [comment]
@beledouxdenis : technical review needed to make sure I won't break any override of `compute_all`. Thanks

**Comment by beledouxdenis** [comment]
This is not stable.
If a custom module override the method `_compute` with the former signature:
```
def _compute(self, cr, uid, taxes, price_unit, quantity, product=None, partner=None, precision=None):
```
The parameter you just added will be dropped because of this override, and the call to `_compute` with the parameter `precision_rounding` will crash.

You have no other choice than completely add a new method name, with all the former logic + the changes you would like, and make the former one calls the new one without any other logic than just calling the new method with one less parameter.

Besides, this is a hell of a change for a stable 8.0. I would imply @odony here, as he is the the rounding master, and he will probably discuss the fact this is kinda adding a feature in a stable release.

**Comment by nim-odoo** [comment]
Thanks for the feedback.

> You have no other choice than completely add a new method name, with all the former logic + the changes you would like, and make the former one calls the new one without any other logic than just calling the new method with one less parameter.

That what I did for `compute_inv`, but our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) states:

> No change in the signature of public methods on model (methods not starting with an underscore)

I am changing the signature of a private method (`_compute`). So technically, that fits the requirement (but yeah, I could make another method, that doesn't cost much).

> Besides, this is a hell of a change for a stable 8.0. I would imply @odony here, as he is the the rounding master, and he will probably discuss the fact this is kinda adding a feature in a stable release in a very sensitive method.

Not sure that correcting a rounding error on tax calculation can be considered as a new feature. However, I understand the sensitivity of this method, hence my review request.

**Comment by nim-odoo** [comment]
Too risky for v8

**Pull request closed without merging**
