### PR TITLE
[FIX] partner_autocomplete: autocomplete not working in odoo 15

### PR DESCRIPTION
**Pull request by Starkhurst**
Description of the issue/feature this PR addresses:
https://www.odoo.com/web#id=2638570&model=project.task&view_type=form&cids=1&menu_id=
Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Kryx-Ikyr** [comment]
@robodoo r+

**Comment by fda-odoo** [comment]
@robodoo r+

**Comment by fda-odoo** [comment]
@robodoo r+

**Comment by fda-odoo** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
Shouldn't the PR target `saas14.5` instead of `15.1` ?

**Comment by fda-odoo** [comment]
@robodoo r+

**Comment by lobaudoux** [comment]
Hello @fda-odoo , could you retry to merge this ?

**Comment by fda-odoo** [comment]
@robodoo r+

**Comment by fda-odoo** [comment]
@robodoo r+

**Comment by lobaudoux** [comment]
@fda-odoo It's yet another error, this PR is cursed !

**Comment by fda-odoo** [comment]
@robodoo r+

**Comment by fda-odoo** [comment]
:pray:

**Comment by fda-odoo** [comment]
@robodoo retry

**Comment by d-fence** [comment]
It seems that your PR breaks the `test_01_main_flow_tour_mobile` you should check it with enterprise too before rplusing.
There is a button on the runbot batch page to create a build with enterprise.
I just started [one](https://runbot.odoo.com/runbot/build/10345681) for you right now.

**Pull request closed without merging**
