### PR TITLE
[IMP] core: save one query when reading one2many on a single record

### PR DESCRIPTION
**Pull request by ryv-odoo**
For reading one2many fields, we make 2 queries (in batch):
 - One to search "id" the comodel
 - One to read <inverse_field> in the comodel to group lines by record (sometimes, this one is bypass because the cache already contains the information).

In many cases (> 80% of cases in our tests) we read a one2many field on a single record.  In that case, we can avoid the second query completely (grouping all lines on a single record is trivial).

This reduces SQL queries by about 0.8% on all-install runbot builds.

### CODE REVIEW

**Review by rco-odoo — APPROVED** [review]
That's good to me.
@robodoo delegate+

**Comment by ryv-odoo** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
Probably worth going through the query counters to adapt them as well ;)
```
Query count less than expected for user __system__: 4 < 5 in test_write_base_one2many at test_performance/tests/test_performance.py:138 
Query count less than expected for user __system__: 5 < 6 in test_write_base_one2many at test_performance/tests/test_performance.py:146 
Query count less than expected for user __system__: 25 < 26 in test_write_base_one2many at test_performance/tests/test_performance.py:151 
Query count less than expected for user __system__: 12 < 14 in test_write_base_one2many at test_performance/tests/test_performance.py:157 
Query count less than expected for user __system__: 11 < 12 in test_write_base_one2many at test_performance/tests/test_performance.py:162 
Query count less than expected for user __system__: 12 < 14 in test_write_base_one2many at test_performance/tests/test_performance.py:172 
Query count less than expected for user __system__: 11 < 12 in test_write_base_one2many at test_performance/tests/test_performance.py:177 
Query count less than expected for user __system__: 7 < 8 in test_write_base_one2many at test_performance/tests/test_performance.py:188 
Query count less than expected for user __system__: 7 < 8 in test_write_base_one2many at test_performance/tests/test_performance.py:194 
Query count less than expected for user __system__: 3 < 4 in test_write_base_one2many at test_performance/tests/test_performance.py:200 
Query count less than expected for user __system__: 3 < 4 in test_write_base_one2many at test_performance/tests/test_performance.py:205 
Query count less than expected for user __system__: 12 < 13 in test_write_base_one2many at test_performance/tests/test_performance.py:211 
Query count less than expected for user demo: 4 < 5 in test_write_base_one2many at test_performance/tests/test_performance.py:138 
Query count less than expected for user demo: 5 < 6 in test_write_base_one2many at test_performance/tests/test_performance.py:146 
Query count less than expected for user demo: 25 < 26 in test_write_base_one2many at test_performance/tests/test_performance.py:151 
Query count less than expected for user demo: 12 < 14 in test_write_base_one2many at test_performance/tests/test_performance.py:157 
Query count less than expected for user demo: 11 < 12 in test_write_base_one2many at test_performance/tests/test_performance.py:162 
Query count less than expected for user demo: 12 < 14 in test_write_base_one2many at test_performance/tests/test_performance.py:172 
Query count less than expected for user demo: 11 < 12 in test_write_base_one2many at test_performance/tests/test_performance.py:177 
Query count less than expected for user demo: 7 < 8 in test_write_base_one2many at test_performance/tests/test_performance.py:188 
Query count less than expected for user demo: 7 < 8 in test_write_base_one2many at test_performance/tests/test_performance.py:194 
Query count less than expected for user demo: 3 < 4 in test_write_base_one2many at test_performance/tests/test_performance.py:200 
Query count less than expected for user demo: 3 < 4 in test_write_base_one2many at test_performance/tests/test_performance.py:205 
Query count less than expected for user demo: 12 < 13 in test_write_base_one2many at test_performance/tests/test_performance.py:211
```

**Comment by ryv-odoo** [comment]
@Feyensv Yep, I forgot this point. The PR is here : https://github.com/odoo/odoo/pull/103714

**Pull request closed without merging**
