### PR TITLE
[FIX] account: fix default_get of account move lines

### PR DESCRIPTION
**Pull request by len-foss**
Obvious typo of 67d82b875cd.

opw 2046137

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by len-odoo** [comment]
robodoo r+ p=0

**Comment by len-odoo** [comment]
robodoo retry

**Comment by len-odoo** [comment]
robodoo retry p=0

**Comment by len-odoo** [comment]
robodoo r-
robodoo r+ p=0

**Comment by KangOl** [comment]
I will make the forward-port.
No need to duplicate the commit.

**Comment by len-odoo** [comment]
Ok great. Sorry about this mess.

**Comment by KangOl** [comment]
For the records, done at 46d3d06f04da47ec6e59377a0e90adb7d82df504

**Pull request closed without merging**
