### PR TITLE
[FIX] settings

### PR DESCRIPTION
**Pull request by nim-odoo**
Multiple issues on settings, see commit messages.

### CODE REVIEW

**Comment by KangOl** [comment]
These commits should be made in version 11.0

**Comment by nim-odoo** [comment]
@KangOl I'm not convinced this is necessary, although that would make sense.

The issue arises because of the attribute `config_parameter` set on `google_drive_authorization_code`. In v11, the attribute `config_parameter` (and consequently the part `# config fields: store ir.config_parameters`) does not exist.

Merging this in v11 would mean solving an issue that doesn't appear, and it would actually be more a refactoring than any kind of fix. I agree that would be better to do so, but in standard that would not fix anything.

The only commit which can be backported in v11 is the one on 'website'. The two others are not necessary.

**Comment by KangOl** [comment]
Ok. Then split the PR and only do the `website` fix in v11

**Comment by nim-odoo** [comment]
@KangOl split in https://github.com/odoo/odoo/pull/26991

**Pull request merged**
