### PR TITLE
[IMP] l10n_pe: class 60 accounts should be of type expense

### PR DESCRIPTION
**Pull request by desdelinux**
The PCGE classifies 60 accounts as Expense Accounts by nature

https://www.mef.gob.pe/contenidos/conta_publ/documentac/VERSION_MODIFICADA_PCG_EMPRESARIAL.pdf https://www.mef.gob.pe/contenidos/conta_publ/documentac/PCGE_2019.pdf

This change impact in the Profit and Loss Report

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hbto** [comment]
👍

**Comment by vbe-odoo** [comment]
@jco-odoo ping - @vbe-odoo do a FUN test

**Comment by vbe-odoo** [comment]
@jco-odoo can you help me creating an enterprise branch, I can not, and I can not check the CoA in the community one to see the changes, thanks
image

**Comment by vbe-odoo** [comment]
Hi, @jco-odoo can you help me creating the enterprise branch of this PR? So I can test it.
Thanks.

**Comment by jco-odoo** [comment]
@vbe-odoo done

**Comment by vbe-odoo** [comment]
@jco-odoo FUN test done, everything LGTM. Ready for technical review > merge.
Best.
cc' @desdelinux

**Comment by jco-odoo** [comment]
@desdelinux Can you put a standard commit msg: [IMP] l10n_pe: class 60 accounts should be of type expense     (or something)

**Comment by desdelinux** [comment]
> @desdelinux Can you put a standard commit msg: [IMP] l10n_pe: class 60 accounts should be of type expense     (or something)

Done

**Comment by jco-odoo** [comment]
@desdelinux commit msg, not pr msg

**Comment by desdelinux** [comment]
@jco-odoo done

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
