### PR TITLE
[IMP] Add flexibility to bus model "notify" and "listen" commands.

### PR DESCRIPTION
**Pull request by m-al-zain**
target branch 15.0

the purpose is to make Odoo deployable to heroku platform

why those changes and additional files:

the changes of the addons/bus/models/bus.py due to Heroku Postgres won't allow us to connect to postgres database, so we need to be informed when the platform is heroku througt the new configuration parameter "heroku_platform", which then be checked in the bus model to determine if we should use the "notify" command through postgres database or use the database in the configuration(config["db_name"]).

runtime.txt: is the heroku way of choosing specific python version. heroku current default version is 3.10, which causes some problems, so we need to tell it to use 3.8.

Procfile: is to tell heroku to run the web container(dyno) using gunicorn web server (added to requirements.txt).

heroku_wsgi.py: is to expose the wsgi app, and to read the environment variables, DATABASE_URL in our case. Here also where we set the addons path and the new configuration parameter "heroku_platform".

db_initializer.py: for database initialization, will be executed from heroku bash.

there are other heroku-platform concerns that I've not touched, like how to run the cron tasks. My intention was not to add those heroku configuration files(there are many different platforms people may use), it was just to make a pull request to change the addons/bus/models/bus.py, but I thought such change need to be justifiable, so I decided to put it into it's context.

### CODE REVIEW

**Comment by Julien00859** [comment]
Can you verify you are not a duplicate of #38926 ?

**Comment by Xavier-Do** [comment]
Hello, thanks for your contribution! 

>runtime.txt: is the heroku way of choosing specific python version. heroku current default version is 3.10, which causes some problems, so we need to tell it to use 3.8.

This is not longer needed, 15.0 should be compatible with python 3.10 since it was adapted for ubuntu Jammy ;)

> My intention was not to add those heroku configuration files(there are many different platforms people may use), it was just to make a pull request to change the addons/bus/models/bus.py, but I thought such change need to be justifiable, so I decided to put it into it's context.

This is good to know: thanks for the context but this may not help to merge the pr since it makes the diff noisy and the purpose of the pr difficult to understand ;)

-> Adding files to deploy on a specific plateform won't be accepted (security, compatibility, noise...) 
-> We also try to avoid new requirements has much as possible. (This is why runbot team was pinged on this one)

We are usually reticent to add new command line options too, even generic one as proposed in #38926. Adding a specific one for heroku will be a no go for sure ;) But there is still hope for a generic one I would suggest you to follow @Julien00859 suggestions and try to get this one merged since it looks like the only real blocking point to deploy this on heroku if I understand well.

Small note even if it won't be merged: I would use regex (or similar) to parse the database parameters:
```python
db_user, db_password, db_host, db_port, db_name = re.match(r'postgres:\/\/(.+):(.+)@(.+):(\d+)\/(.+)', DATABASE_URL).groups()
```

**Comment by Julien00859** [comment]
Hello @m-azzain,

We had an internal discussion at Odoo whether we wish to make Odoo compatible with Heroku or not. I'm sorry but the ultimate decision is that there still are too many burdens to make it works correctly.

The deployment model of Odoo as long been on dedicated hardware, PaaS solutions such as Heroku are nice but they are too limited when they come to running our software.

You noticed that the crons are not working, actually there is much more that wouldn't work the way it should, e.g. the chat. Odoo ships its own WSGI server, trying to replace it by another is not supported.

On your contribution itself, the targeted branch of your fix is a stable branch, stables branches are fix-only, when you suggest a new feature you have to target master. I'm pretty sure you wanted it in v15 because you are using v15 at work, I fully understand it but we are quite careful not to merge new features in stable branches. Pay attention that your many commits don't comply with our [git guidelines](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#git), there should be only two commits:

* [IMP] core: Added heroku platform configuration files
* [CLA] Sudan

Also pay attention that the CI/Style runbot is red, asking you change your code.

Still, thank you for your contribution :) I'm sorry the crons/chat makes it impossible to merge :(

**Comment by Xavier-Do** [comment]
Feel free to reopen if we missed something

**Pull request closed without merging**
