### PR TITLE
[IMP] http: avoid saving sessions for auth='none' routes

### PR DESCRIPTION
**Pull request by KangOl**

### CODE REVIEW

**Comment by xmo-odoo** [comment]
I've 2 issues with this:
* adding this meaning to all auth=none controllers seems risky
* https://github.com/odoo/odoo/blob/285ead28e31ca54e9629d5153d0d03d7b4951535/addons/http_routing/models/ir_http.py#L277-L283 is called in _dispatch so it will modify the session on every call and fundamentally that means this change is not really future-proof and we've no real way to notice when a change breaks it all (except finding out that we've got millions of dummy sessions)

It might be smarter/more future-proof to flag the specific endpoints we want to un-session (similar to cors= or type= or csrf=) and skip saving & cookie-ing in these specific case.

**Comment by KangOl** [comment]
Maybe this should be the case for *all* `auth=none` routes.
If you route is session dependent, use `auth=user` or `auth=public`.

**Comment by xmo-odoo** [comment]
> Maybe this should be the case for all auth=none routes. If you route is session dependent, use auth=user or auth=public.

1. that's *never* been the contract for this attribute and makes very little sense
2. if auth=none routes can't access the session they shouldn't have one set up at all

**Comment by antonylesuisse** [comment]
Lest add session=False in route

**Comment by xmo-odoo** [comment]
Updated the PR to just use a flag, and flagged the RPC endpoints.

**Comment by antonylesuisse** [comment]
ok KISS

**Comment by KangOl** [comment]
I love you too 💋

**Pull request merged**
