### PR TITLE
[IMP] l10n_nl: switch account templates to csv from xml

### PR DESCRIPTION
**Pull request by hch-odoo**
task: https://www.odoo.com/web?debug#id=1909961&action=327&model=project.task&view_type=form&menu_id=4720

pad: https://pad.odoo.com/p/r.3bb795404d1e38ccc7cde9c4f6f3c9cd

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@jco-odoo why is this going into stable (12.0)?! It is an improvement.

**Comment by jco-odoo** [comment]
Has to do with perf (import in batch) and it won't break anything.

**Comment by Yenthe666** [comment]
Okay, just wanted to be sure there is no harm & that it was on purpose going into 12.0. Thanks.

**Comment by sswapnesh** [comment]
@jco-odoo 
> Has to do with perf (import in batch) and it won't break anything.

What is someone has extended record and added `noupdate=1` for purpose.
I will prefer to add this in master. (or even keep this in xml so one can extended it in better way)

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
