### PR TITLE
[FIX] l10n_do: Add account groups & correct tax names for N07-2018

### PR DESCRIPTION
**Pull request by gustavovalverde**
### Description of the issue/feature this PR addresses:
- Add Account Groups for future deprecation of tags
- Improve Taxes names and descriptions
- Standardized taxes groups with Norma 07-2018

### Current behavior before PR:
- There's no account groups for hierarchical and enterprise reporting purposes 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gustavovalverde** [comment]
Hi @qdp-odoo. We did this changes in the Odoo Hackaton held in DR. The local community would like to have this changes merge as soon as you guys can have a look at it, as we'll also be changing a few things in master before it hits 12.0

Thanks in advance.

**Comment by gustavovalverde** [comment]
cc: @oco-odoo

**Comment by gustavovalverde** [comment]
@qdp-odoo Just a kind reminder

**Comment by gustavovalverde** [comment]
@qdp-odoo this is more than ready to be merged. Already using in on production with no issues so far (except that last commit)

**Comment by nim-odoo** [comment]
Is it possible to squash in a single commit? For example: 2dcdfe108bc0436828fa3ce84e67af77de7821e0  This one could be squashed

**Comment by gustavovalverde** [comment]
Is it that (a) you want to squash the whole PR? If that's what you need, no problem. Or (b) you want me to squash it from 7f6fc1b to 2dcdfe1; and bc095b1 with 064dace?

**Pull request closed without merging**
