### PR TITLE
Exception raises when adding field to search panel of ir.module.module

### PR DESCRIPTION
**Pull request by Kenevist-admin**
**Description of the issue/feature this PR addresses:**
adding any field other than `category_id` to ir.module search panel causes an exception.

**Current behavior before PR:**
Adding any field to search panel of ir module module causes this exception;

```
Odoo Server Error

Traceback (most recent call last):
  File "/mnt/base/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/mnt/base/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/base/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/base/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/base/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/base/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/mnt/base/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/mnt/base/addons/web/controllers/main.py", line 1377, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/mnt/base/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/base/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/mnt/base/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/mnt/base/odoo/addons/base/models/ir_module.py", line 980, in search_panel_select_range
    return super(Module, self).search_panel_select_range(field_name, **kwargs)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/base/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/base/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
UnboundLocalError: local variable 'Module' referenced before assignment
```
The reason is that a locally defined variable shadows the class name, even when the variable declaration is not executed, the interpreter assume it is a local variable.

using self instead of Module or ModuleModel is possible and IMHO it is better, but to keep consistency, I used ModuleModel

**Desired behavior after PR is merged:**
Works as excepted in any model.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@rco-odoo this is an easy one

**Review by yelizariev — APPROVED** [review]
You should make ``git rebase -i`` and keep only two commits ``[FIX] base: eliminate variable overlapping`` and ``[CLA] ...``

**Comment by Kenevist-admin** [comment]
@yelizariev 
> You should make `git rebase -i` and keep only two commits `[FIX] base: eliminate variable overlapping` and `[CLA] ...`

Done!

**Comment by yelizariev** [comment]
FIX commit still has changes related to CLA
https://github.com/odoo/odoo/pull/68396/commits/26cf72f785944f3c370fa59aa19ac51279c89d5b
image

**Comment by C3POdoo** [comment]
Dear @Kenevist-admin,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
