### PR TITLE
[FIX] website_blog: disallow multi-tag for bot indexation

### PR DESCRIPTION
**Pull request by nim-odoo**
Partial backport of 0f2cada32319b3910d6ace6d412cfa94a646c9c7

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
fw-bot ignore

**Comment by JKE-be** [comment]
Not really for a stable version imo, and already done in latest version if i'm not wrong :fearful: 

While I'm ok that indexation should be not done, Share this kind of link is not rare :/  E.g.: /blog/sante-nutrition-1/tag/alimentation-2,energie-13 in newsletter and co :/

**Comment by nim-odoo** [comment]
It actually causes an issue on a 13.0 SaaS server with Google crawlers literally doing a DDoS because of a single database with ~200 tags. Although I agree your use case is totally legit, this causes a combinatorial explosion with hundreds of tags.

**Comment by rdeodoo** [comment]
I think @JKE-be was talking about the python part (which is a behavior change), not about the nofollow (which already existed in 11.0
https://github.com/odoo/odoo/commit/d39856dbe88b4492a6bf2d9b30923e58a945d692 et https://github.com/odoo/odoo/commit/27162b0e73a1887fc7178d6b79553c2301e1bac4

Aren't the `nofollow` enough here? That should prevent the crawler to navigate to a tag if already on a tag, so no more combination/nesting

**Comment by nim-odoo** [comment]
Well, to be honest I'm not 100% sure about what `nofollow` does for internal links. Quoting the [documentation](https://developers.google.com/search/docs/advanced/guidelines/qualify-outbound-links?hl=en):
> Use the nofollow value when other values don't apply, and you'd rather Google not associate your site with, or crawl the linked page from, your site. (For links within your own site, use robots.txt, as described below.)

And:
> If you need to prevent Google from following a link to a page on your own site, use the robots.txt Disallow rule.

As I understand it, `nofollow` is more dedicated to external links.

**Comment by rdeodoo** [comment]
> Well, to be honest I'm not 100% sure about what nofollow does for internal links. 

It practice, it prevents google to actually crawl/navigate to those links, even if this is not the way Google prefer us to tell its crawler how to not navigate to an internal link.
See https://www.searchlaboratory.com/us/2015/08/does-google-crawl-relnofollow-links-experiment/
Also https://www.searchenginejournal.com/nofollowed-internal-links-seo/304445/ is helpful and actually links to the [official documentation](http://microformats.org/wiki/rel-nofollow), not the Google one. It is not especially for external links.

So I think it is safe to assume `nofollow` is enough as it actually do what we want, Google will not reaches the nofollow URLs and should stop spending too much time on our server.

More importantly, it will not be a behavior change in stable for enduser so I think this is win-win.

And we can still discuss it later if it seems not enough to fix the issue, but I think it is.

**Comment by nim-odoo** [comment]
I'm not convinced about the reliability of the 2 articles you quote in comparison to the Google documentation. Anyway, I'm not going to argue about something none of us can verify (i.e. the implementation of the Google crawler). I'll just merge the view part, and if the problem appears in the future we'll reconsider the whole patch. Thanks a lot.

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
