### PR TITLE
Add --update-list CLI option

### PR DESCRIPTION
**Pull request by dreispt**
CLI option to update the module list.
Using it allows to directly install newly added modules without going to the web GUI or updating the base module.

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

This option will only work if you are in update mode (e.g. update another module).
Either it is explicitly specified in the command line, either we activate update_mode with the `-U` (but I am afraid activating the update mode would have more side effects).

Otherwise looks good for master

**Comment by dreispt** [comment]
Should the help text mention it should be used with -d and -i?
Should I make a PR for master then?

**Comment by xmo-odoo** [comment]
Alternatively, wouldn't it make sense to update the modules list any time we're trying to install a new module? /cc @odony

**Comment by odony** [comment]
Yes, we already have so many CLI parameters, it'd be much more in favor of merging this feature with the update/init mode itself. The likely reason why we didn't do that yet is the (small) extra cost of the addons_path scanning. But I think it would be ok to do it at the beginning of every install and/or update, not just for `base` (and in master, not a in stable version).

**Comment by xmo-odoo** [comment]
I went hunting for the origin of this (expecting a revision 1 introduction) but it turns out to be 00098e75: the module list update used to be performed on any registry loading (which was definitely problematic) but the restriction to "only when installing or updating base" seems somewhat arbitrary and is not explained.

**Comment by dreispt** [comment]
That's even simpler. I can do that PR if you like.

**Comment by dreispt** [comment]
PR made here: https://github.com/odoo/odoo/pull/9140

**Pull request closed without merging**
