### PR TITLE
[REF] test_main_flows: Remove the creation of a manual bank account.

### PR DESCRIPTION
**Pull request by FlorianGilbert**
This part of the tour can't work with the new online synchronization
because we can't be confident about what the proxy will display.
Remove account_plaid & account_yodlee from _auto_install_l10n.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by FlorianGilbert** [comment]
@csnauwaert

**Comment by csnauwaert** [comment]
@robodoo r+

**Comment by csnauwaert** [comment]
@robodoo r+

**Comment by csnauwaert** [comment]
@robodoo retry

**Comment by mart-e** [comment]
@robodoo override=ci/security

**Pull request closed without merging**
