### PR TITLE
[FIX] mail: correct test

### PR DESCRIPTION
**Pull request by taqu-odoo**
Modifies and improves existing test by removing typo introduced by
https://github.com/odoo/odoo/commit/f02de5ab90f4bce98da1e38f11af4b7ed73e01a4.

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
so if I understand the issue (and intention of the patch) is that we don't want to do the query for real

then looks good to me

robodoo delegate+

**Comment by taqu-odoo** [comment]
@odoo/rd-security this commit fixes a typo in a test related to mocking sessions.

**Comment by nle-odoo** [comment]
you should edit the commit to have a reference to the commit that adds the test (`f02de5ab90f4bce98da1e38f11af4b7ed73e01a4`)

for example:

```diff
- [FIX] mail: correct test typo of f02de5ab90f
+ [FIX] mail: correct test

- Fixes a typo, even though the test still passes.
+ Fixes a typo in test added by f02de5ab90f4bce98da1e38f11af4b7ed73e01a4, even though the test still passes.
```

**Comment by taqu-odoo** [comment]
Indeed it seems better to patch Session.request, thanks for the suggestion @xmo-odoo

**Comment by nle-odoo** [comment]
fw-bot up to saas-16.3

(the original test was not forward-ported past saas-16.3)

**Review by tde-banana-odoo — APPROVED** [review]

**Pull request closed without merging**
