### PR TITLE
[FIX] base_import_module: adapt ormcache for industries

### PR DESCRIPTION
**Pull request by pimodoo**
Instead of makchanging the type of lists to make an ormcache that works,
we'v extracted the function that call the server apps.odoo.com to pass
it the payload in json (as it will be sent to the server), and use the
payload value as ormcache

### CODE REVIEW

**Comment by pimodoo** [comment]
@ryv-odoo as discussed

**Comment by pimodoo** [comment]
@odoo/rd-security Hello, we are just moving a post already done

**Comment by mart-e** [comment]
@robodoo override=ci/security

**Comment by pimodoo** [comment]
@robodoo r+

@ryv-odoo as discussed at the machine à café

**Pull request closed without merging**
