### PR TITLE
Move dbname in function for tests

### PR DESCRIPTION
**Pull request by damiansoriano**
@odony this is what we discuss on the Odoo Experience.

When a command is provided to odoo.py, the subcommand discovery is launched and a lot of modules are loaded at this time (this happens in openerp/cli/**init**.py, inside main). As part of this initialization, the module openerp/tests/common.py is imported and the line

`DB = openerp.tools.config['db_name']`

is executed. At this time the parsing of the parameters didn't happened and then the DB variable will be initialized with False. This is a problem if the command is using this variable for some reason, like lunching tests, since this DB variable is used in several subclases of openerp.test.common.BaseCase.

This is not a problem when launching tests with --test-enable since the subcommand discovery is not executed and the module openerp/test/common.py is loaded after the parsing of the parameters is completed.

@xmo-odoo this PR replace #6981, I already modify the things that you suggest.

### CODE REVIEW

**Comment by damiansoriano** [comment]
@odony any news regarding this PR?

**Comment by odony** [comment]
@damiansoriano Just merged it, thanks!

**Comment by sbidoul** [comment]
@odony @damiansoriano what about all tests relying on openerp.tests.common.DB? This commit breaks them all!

**Comment by damiansoriano** [comment]
@sbidoul good call, haven't realize that outside Odoo other modules where using that variable. Probably those modules should start using the `get_db_name()` function.

Anyway, I just create this PR [7054](https://github.com/odoo/odoo/pull/7054), to solve that issue.

**Pull request closed without merging**
