### PR TITLE
[ADD] l10n_pt_certification: Portugal - Invoicing Certification (Order No. 8632/2014)

### PR DESCRIPTION
**Pull request by reinaldojpramos**
This add-on brings the technical requirements of the Portuguese order No. 8632/2014 that requires software to abide by certain criteria concerning the inalterability, security and storage of data related to customer invoicing.

We're starting with the numbers 3.3.3, 3.3.4 and 3.3.5, that regulate the inalterability of product name and partner name and VAT.

Order No.8632/2014:
http://info.portaldasfinancas.gov.pt/pt/docs/Portug_tax_system/Documents/Order_No_8632_2014_of_the_3rd_July.pdf

Current behavior before PR: Software not in accordance with Portuguese order No. 8632/2014

Desired behavior after PR is merged: Software in accordance with numbers 3.3.3, 3.3.4 and 3.3.5 of the Portuguese order No. 8632/2014

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by reinaldoramosarxi** [comment]
Is the company CLA signature not enough? 

Does each contributor need an individual one, even if they're on the company CLA?

**Comment by reinaldoramosarxi** [comment]
@mart-e Ok, all contributors now have a CLA signature.

**Comment by mart-e** [comment]
@reinaldoramosarxi you have to rebase your code after the CLA validation. I have done it so it should be fine now.
I let @jco-odoo check for the content of the PR itself.

**Comment by reinaldoramosarxi** [comment]
Hello @mart-e , are there any news regarding this PR? Do we need to do something on our end?
Thank you.

**Comment by mart-e** [comment]
@jco-odoo please don't forget this PR

**Comment by jco-odoo** [comment]
@mart-e @reinaldoramosarxi This is really restrictive and probably only a distinct part of the many things we should do for the Portugese localization.  I am even wondering if that is really the law or if there is no other way to do it.  So, we should not put this as such. @jcr-odoo

**Comment by aluaji** [comment]
@jcr-odoo We have included in the original PR message the link to Order No. 8632/2014 from the Portuguese Tax Authority, describing the exact requirements that we have implemented in this PR.

We have been told by @jcr-odoo that for legal localization implementations, we should only do small increments, which is why this is only a small distinct part.

**Comment by reinaldoramosarxi** [comment]
Sorry, forgot to tag you by mistake @jco-odoo

**Comment by reinaldoramosarxi** [comment]
@mart-e Are there any news regarding this PR?

Thank you.

**Comment by reinaldoramosarxi** [comment]
Hello,

@mart-e Leaving another bump regarding this PR.

Thank you.

**Comment by avw-odoo** [comment]
Hello @reinaldoramosarxi 

We want to move forward with l10n_pt.
Could you explain to me, regarding this spec http://info.portaldasfinancas.gov.pt/pt/docs/Portug_tax_system/Documents/Order_No_8632_2014_of_the_3rd_July.pdf why you focalize you this 3 points ? What about the other points regarding the compliancy ?

How are you dealing with the "certified invoicing software program" with Odoo ?

Thank you,

**Comment by jco-odoo** [comment]
@reinaldoramosarxi Can we have a meeting together to see who has what and how we can move forward?

**Comment by C3POdoo** [comment]
Dear @reinaldoramosarxi,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
