### PR TITLE
[IMP] mail: create model view for activity popover

### PR DESCRIPTION
**Pull request by phenix-factory**
task-2579306

### CODE REVIEW

**Comment by phenix-factory** [comment]
@seb-odoo @alexkuhn An other green PR :partying_face:

**Review by seb-odoo — COMMENTED** [review]
quick first check

**Comment by phenix-factory** [comment]
@seb-odoo Review is done !

**Review by seb-odoo — APPROVED** [review]
I've made slight changes but overall ok if runbot green

@robodoo r+

**Pull request closed without merging**
