### PR TITLE
[FIX] mail, *: odooBot onboarding crashes on canned response

### PR DESCRIPTION
**Pull request by maki-odoo**
*: im_livechat, im_livechat_mail_bot

Since odoo/odoo#110188 `canned_response_ids` is not being passed to `mail_message_post` and since odoo/odoo#127382 canned response is enabled in only non-channel threads so odooBot onboarding crashes on the canned response step. This commit allows using `canned responses` in `chat with odooBot` and makes sure that we send them with the message post data.

Related to odoo/odoo#157997

### CODE REVIEW

**Comment by alexkuhn** [comment]
This is not a tour, but the onboarding feature with odoobot that doesn't work. We could actually have a tour for that, because there's no test coverage of this feature at all as shown by a step not working for quite a while

**Comment by seb-odoo** [comment]
If it's possible to add a tour to cover it it would be nice indeed, if possible with the PR in v15 as it will have to be tested/adapted on a lot of versions.

**Comment by maki-odoo** [comment]
> If it's possible to add a tour to cover it it would be nice indeed, if possible with the PR in v15 as it will have to be tested/adapted on a lot of versions.

Unfortunately I couldn't provide a tour test because I need to receive bus notifications in chat with odooBot and it's not possible for now.

**Comment by seb-odoo** [comment]
I got a crash when testing this PR in 16.3

image

```
UncaughtPromiseError > OwlError
Uncaught Promise > Got duplicate key in t-foreach: 67.01
OwlError: Got duplicate key in t-foreach: 67.01
    OwlError@http://127.0.0.2:8069/web/assets/debug/web.assets_common.js:16506:5 (/web/static/lib/owl/owl.js:87)
    template@http://127.0.0.2:8069/web/assets/debug/web.assets_common.js line 21951 > Function:81:47 (/web/static/lib/owl/owl.js:5532)
    _render@http://127.0.0.2:8069/web/assets/debug/web.assets_common.js:18141:38 (/web/static/lib/owl/owl.js:1722)
    render@http://127.0.0.2:8069/web/assets/debug/web.assets_common.js:18133:18 (/web/static/lib/owl/owl.js:1714)
    render@http://127.0.0.2:8069/web/assets/debug/web.assets_common.js:18845:23 (/web/static/lib/owl/owl.js:2426)
    ```
    
    I'm not sure how to reproduce, but you can see the step in the screenshot.

**Comment by seb-odoo** [comment]
Note: if you cannot reproduce it, it might be an existing bug.

The fix itself looks ok apart from that

@robodoo delegate+

**Comment by maki-odoo** [comment]
> Note: if you cannot reproduce it, it might be an existing bug.
> 
> The fix itself looks ok apart from that.
> 
> @robodoo delegate+

I remember I saw it once before on 16.3 but I couldn't reproduce it either. I tried to reproduce it again after your comment and got nothing. I think we can let this fix goes forward for now.

**Comment by maki-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
