### PR TITLE
[FIX] account: Missing label for partner VAT in invoice report

### PR DESCRIPTION
**Pull request by sve-odoo**
Missing label for partner VAT field in invoice report

### CODE REVIEW

**Comment by mart-e** [comment]
@sle-odoo shouldn't we add a `t-if` to avoid displaying VAT if not specified on the partner ?

**Comment by sle-odoo** [comment]
something like ``<span t-if="o.partner_id.vat">VAT: <span t-field="o.partner_id.vat"/></span>`` would be nice yes

**Comment by Olivier-LAURENT** [comment]
Hi @sve-odoo @sle-odoo @mart-e 
When proposing/merging such modifications, it would be nice to adapt accordingly the `pot` file too to give a chance to translators to translate them.

**Comment by mart-e** [comment]
@Olivier-LAURENT agreed. Adding `VAT:` is ok as already present in other .pot file (anyway should be in `account.pot` too) but the `TIN:` was more an issue. Fixed at 6d882973f7ac9449098f5fa506f2d1bf4ce307e3

**Pull request closed without merging**
