### PR TITLE
Saas 11 fix compute stocklandedcost lpe

### PR DESCRIPTION
**Pull request by kebeclibre**
OPW 725897

For 500+ stock_valuation lines, computation of account_move undergoes something like a n squared complexity. It take ages to compute that much lines

After this commit, since recompute has been set to false, objects are created, but not computed (in particular the account_move)

Testing shows it takes 4 minutes all included to compute 1400+ account_move_lines (compared to probably 20+ minutes before)
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
I am not sure this "recompute" ORM feature is safe @rco-odoo

**Comment by jco-odoo** [comment]
Putting it in a list, ... is not that much work.

**Comment by kebeclibre** [comment]
Nope it is not that much work, but it doesn't work though @jco-odoo (I tested it). Moreover, putting it in a list would change returns of 2 methods

**Comment by jco-odoo** [comment]
you mean it does not go faster and with the recompute it does?

**Comment by kebeclibre** [comment]
Yep, that is what I meant

**Comment by jco-odoo** [comment]
It should be the same normally...

**Comment by kebeclibre** [comment]
To check with @rco-odoo, but he told me that doing a [(0, False, vals) for
vals in dict] would also trigger recomputation at odoo-object creation
(that the orm wasn't smart enough to do it in batch at this point)

**Pull request closed without merging**
