### PR TITLE
[FIX] l10n_cl: change account in COA and assignation 

### PR DESCRIPTION
**Pull request by Danisan**
Fix of the COA:
There was a bad assignation in the account rate difference profit/loss.

As these are minor changes, we make this together with changes in the F29 report VAT base

https://github.com/odoo/enterprise/pull/55365

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Danisan** [comment]
@fvz-odoo this is ready. I also removed the tags from the account.account (not removed yet: account.account.tag since I am not yet sure if it should be removed from 16.0)

**Comment by fvz-odoo** [comment]
Hello @Danisan 

I get a traceback error on this PR when I try to install the Chilean modules. This is the database if you want to check...
https://58929777-16-0-all.runbot206.odoo.com/

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "<decorator-gen-8>", line 2, in __getitem__
  File "/data/build/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/data/build/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7f254e3e04c0>, 'account.data_account_type_revenue')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/data/build/odoo/odoo/tools/convert.py", line 568, in _tag_record
    f_val = self.id_get(f_ref, raise_if_not_found=nodeattr2bool(rec, 'forcecreate', True))
  File "/data/build/odoo/odoo/tools/convert.py", line 681, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/data/build/odoo/odoo/tools/convert.py", line 687, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/data/build/odoo/odoo/addons/base/models/ir_model.py", line 2045, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-43>", line 2, in _xmlid_lookup
  File "/data/build/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/data/build/odoo/odoo/addons/base/models/ir_model.py", line 2038, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: account.data_account_type_revenue

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 1864, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 599, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/data/build/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/data/build/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/build/odoo/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/data/build/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/data/build/odoo/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/data/build/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/data/build/odoo/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/data/build/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/data/build/odoo/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/data/build/odoo/odoo/tools/convert.py", line 711, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /data/build/odoo/addons/l10n_cl/data/l10n_cl_chart_data.xml:1189, somewhere inside
<record id="account_310122" model="account.account.template">
        <field name="code">310122</field>
        <field name="name">Ventas de Pasajes Nacionales/Internacionales y/o Comisiones No Afectas</field>
        <field ref="account.data_account_type_revenue" name="user_type_id"/>
        <field name="reconcile" eval="False"/>
        <field name="chart_template_id" ref="cl_chart_template"/>
     </record>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://58929777-16-0-all.runbot206.odoo.com/web/assets/2267-f667be8/web.assets_backend.min.js:1000:163)
    at XMLHttpRequest.<anonymous> (https://58929777-16-0-all.runbot206.odoo.com/web/assets/2267-f667be8/web.assets_backend.min.js:1008:13)

Let me know!

Cheers!

Fernando

**Comment by fvz-odoo** [comment]
Hello @Danisan 

Were you able to check this error? It happens right when I try to install l10n_cl_edi

Let me know please.

Fernando

**Comment by h4818** [comment]
@Danisan ping

**Comment by Danisan** [comment]
> @Danisan ping

Thank you! this is fixed

**Comment by fvz-odoo** [comment]
ping @jco-odoo

**Comment by fvz-odoo** [comment]
Hey @jco-odoo remember to merge this one as well and https://github.com/odoo/enterprise/pull/55365, it is the same as in https://github.com/odoo/odoo/pull/152628 and https://github.com/odoo/enterprise/pull/55806. Actually, we can close the automatic FW-Ps of those (https://github.com/odoo/odoo/pull/161383 and https://github.com/odoo/enterprise/pull/60475), since it is handled here.

Let me know if anything.

Cheers!

Fernando

@Danisan @ren-odoo @masi-odoo

**Comment by fvz-odoo** [comment]
> Hey @jco-odoo remember to merge this one as well and [odoo/enterprise#55365](https://github.com/odoo/enterprise/pull/55365), it is the same as in #152628 and [odoo/enterprise#55806](https://github.com/odoo/enterprise/pull/55806). Actually, we can close the automatic FW-Ps of those (#161383 and [odoo/enterprise#60475](https://github.com/odoo/enterprise/pull/60475)), since it is handled here.
> 
> Let me know if anything.
> 
> Cheers!
> 
> Fernando
> 
> @Danisan @ren-odoo @masi-odoo

Hey @jco-odoo did you have a chance to check this one?

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
