### PR TITLE
[ADD] payment_asiapay: add an integration to AsiaPay

### PR DESCRIPTION
**Pull request by tong-odoo**
task-2845428

Continuation of https://github.com/odoo/odoo/pull/90951.

See also:
- https://github.com/odoo/documentation/pull/2628

### CODE REVIEW

**Comment by tong-odoo** [comment]
@AntoineVDV Only two issues haven't resolved from the previous PR. 
- First one is should I include all payment method inside Asiapay.
- Second one is how to handle return url datafeed.

**Comment by AntoineVDV** [comment]
> - First one is should I include all payment method inside Asiapay.

Yes, ideally, the newly supported payment methods should each have a `payment.icon` record assigned to the AsiaPay `payment.acquirer` record. However, you don't need to select which payment method should be used for the payment; leave that to AsiaPay ;)

> - Second one is how to handle return url datafeed.

It depends on what AsiaPay permits. For example:
- Stripes includes the full payment data in the redirection data with a signature to validate them.
- Flutterwave only includes the transaction reference in the redirection data but has an API endpoint to fetch the full payment data based on the transaction reference. We can trust these data because they come from a secure HTTP call made directly to the provider's API.
- IDon'tRemeberWhichOne (PayPal maybe?) includes no useful payment data or doesn't expose a `/payment_data` endpoint. Only the webhook data can be trusted.

Please check if AsiaPay exposes an endpoint that allows verifying/fetching the payment data. If not, keep the controller like this.

**Comment by tong-odoo** [comment]
@AntoineVDV 
> Yes, ideally, the newly supported payment methods should each have a payment.icon record assigned to the AsiaPay payment.acquirer record. However, you don't need to select which payment method should be used for the payment; leave that to AsiaPay ;)

Currently is all payment method. So it should be fine. I added master card, visa and union pay for payment.icon. See if we needed to add more. 

> Please check if AsiaPay exposes an endpoint that allows verifying/fetching the payment data. If not, keep the controller like this.

In their documentation, this is what they mentioned `(For display purpose only. DO NOT use this URL to update your system. Please use DataFeed for this purpose.)`, where the DataFeed is the web hook for Asiapay to called. Therefore I guess we should not use the data from return URL? 

Data from return URL
```
received AsiaPay return data:
{'Ref': 'S00038-20220819064057'} 
```

**Review by AntoineVDV — COMMENTED** [review]
As discussed, they are some other changes, but I already noted the following ones.

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

**Comment by AntoineVDV** [comment]
@robodoo override=ci/security
Reason:
- hmac: Legitimately imported and used to compare signatures.
- hashlib: Legitimately imported and used to generate signatures.
- sha1: False positives in strings.

Link to ci/security build (master): https://runbot.odoo.com/runbot/build/18721369

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
