### PR TITLE
[IMP] test_discuss_full, im_livechat: fix write on computed field

### PR DESCRIPTION
**Pull request by tsm-odoo**
This commit fixes tests that write on the `im_status` computed field of `res.users`. This leads to incoherent data being asserted. This will ease the diff of the PR introducing the guests for livechat visitors.

part of task-3332628

### CODE REVIEW

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

**Comment by seb-odoo** [comment]
@robodoo delegate+

**Comment by seb-odoo** [comment]
@robodoo r+

**Comment by tsm-odoo** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo retry

**Pull request closed without merging**
