### PR TITLE
Master auth ldap encode name

### PR DESCRIPTION
**Pull request by hbrunn**
Description of the issue/feature this PR addresses: Non-ascii characters in LDAP don't cause a python unicode string in returned ldap entries, this PR is meant to fix this.

Current behavior before PR: Further string operations on ldap values with non-ascii characters fail.

Desired behavior after PR is merged: Also non-ascii-characters work.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash the commits, but :+1:

**Comment by NL66278** [comment]
:+1:  LGTM

**Comment by xmo-odoo** [comment]
* should probably be merged in 11.0 if it's a generalised Python 3 issue?
* what is the reason for using `ustr` (which attempts decoding from various types) rather than just decoding bytes as utf8 via `bytes.decode()`?

**Comment by mart-e** [comment]
@xmo-odoo this is a 4 years old PR so if good, we can adapt and merge directly ;-)

**Comment by xmo-odoo** [comment]
@mart-e maintainers update is not enabled on the PR (probably because it predates that feature) so I can't squash and update.

**Comment by mart-e** [comment]
Done at #40761

**Pull request closed without merging**
