### PR TITLE
[RFC][WIP] [DISCUSS] account_edi: What is the best way to go from account_edi -> edi

### PR DESCRIPTION
**Pull request by jco-odoo**
DO NOT MERGE THIS PR, it is dangerous WIP and serves as an RFC.  (not that runbot would agree)

Current behavior before PR:
account_edi is only applicable to invoices (do not try receipts) and payments

Desired behavior after PR is merged:
account_edi depends on edi. edi has the basic functionality that can be applied to other models => we can have:
- stock_edi: for sending pickings  (could work for receiving as well e.g. if your client tells you that Monday 5 pallets will arrive of line 2 or PO X, you can already split the picking according to the freight) but this is already needed for CL, PE, EC, AR
- sale_edi: sending sale orders to customers
- purchase_edi: receiving purchase orders
- product_edi: sharing product catalogs
- ... 

The main challenge is if there would be a way to make a relation with the parent object through res_id/res_model e.g. of the attachment_id instead of having a different field for every object and as such needing to redefine several methods for little reason. (move_id on the edi_document)

Ideally also, an edi_document should have a many2many with edi.mixins objects. (e.g. if you have one file cancelling many invoices)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@tde-banana-odoo How could I not ping you as mixin problem specialist.

**Comment by nhomar** [comment]
@jco-odoo 

I just want to say:

Thank U


Perfect

**Comment by smetl** [comment]
This was in the pipe since the beginning. The original idea was to replace `move_id` from `account.edi.document` by `res_id` (`Many2oneReference` field) and `res_model`.

**Comment by tde-banana-odoo** [comment]
> @tde-banana-odoo How could I not ping you as mixin problem specialist.

Repairing mixin since 2011 :toolbox: :hammer:  !

Any question or was it just for the ping ?

**Comment by jco-odoo** [comment]
@tde-banana-odoo I think smetl kind of answered with the Many2oneReference.  That way we can do code on parent objects (polymorphism stuff)

**Comment by pedrobaeza** [comment]
Yes, thank you! Having EDI only in account was very limited, and at OCA we started an effort to generalize the EDI to any document in https://github.com/oca/edi/tree/13.0 through all the `edi_*` modules. Of course this doesn't serve to you for being integrated here, as it's coupled with other OCA technologies like `component` that are too huge to be included in core, but it can serve as inspiration. 

@etobella @simahawk you may be interested in this refactoring.

And a problem arises now: the conflict on the names. We already took `edi`, and it should be published in Odoo Apps Store with such name, but if you now hijack such name, our modules will be shadowed. How do we deal with this?

**Comment by jco-odoo** [comment]
@pedrobaeza This is only for master.  By that time, OCA can think about a way to make them live in harmony.

**Comment by pedrobaeza** [comment]
Yeah, but the problem is that Odoo Apss unpublish and shadow the modules with the same name that are in other versions if one of them are from Odoo (unless this has change since last time it happens). An example is `quality_control`, that we had it since v8 in https://github.com/OCA/manufacture/tree/8.0/quality_control, and then it appears the enterprise module, and ours disappeared for each version, and we needed to rename it (https://apps.odoo.com/apps/modules/13.0/quality_control_oca/), but at the cost of not having 8.0 and past versions in the store.

**Comment by jco-odoo** [comment]
@dmo-odoo

**Comment by dmo-odoo** [comment]
@jco-odoo I do not handle Odoo Apps anymore. Though clearly the obvious answer would be to prefix all modules by `oca_` to avoid any conflict. The problem is not only with modules released odoo, actually. Without prefixing, you might conflict with anyone else on the store.

**Comment by pedrobaeza** [comment]
@dmo-odoo the problem is that we can't rename the module for all versions, and that will break all existing installations. I would appreciate if current Odoo Apps maintainer can give us any solution.

**Comment by pedrobaeza** [comment]
@simahawk @dreispt can you please check if all OCA branches for OCA/edi are published in Odoo Apps and which status they have?

**Comment by simahawk** [comment]
> @simahawk @dreispt can you please check if all OCA branches for OCA/edi are published in Odoo Apps and which status they have?

Just had a quick look. For 13.0 some modules are registered (eg: base_edi) some are not because of missing dependencies.
I guess because other modules from other repos are not registered/updated for 13.0.
Funny thing is that there's no `edi` module yet but it complains like "Module edi already exists for another serie.".

```
Module edi already exists for another serie. Please select a free module name or use the right user account.
edi_storage: unmet dependency edi for series 13.0. Dependency might be invalid.
edi_voxel_secondary_unit: unmet dependency product_secondary_unit for series 13.0. Dependency might be invalid.
edi_xml: unmet dependency edi for series 13.0. Dependency might be invalid.
sale_order_import: unmet dependency onchange_helper for series 13.0. Dependency might be invalid.
edi_account: unmet dependency edi for series 13.0. Dependency might be invalid.
edi_webservice: unmet dependency edi for series 13.0. Dependency might be invalid.
sale_order_import_ubl: unmet dependency sale_order_import for series 13.0. Dependency might be invalid.
sale_order_import_ubl_http: unmet dependency auth_api_key for series 13.0. Dependency might be invalid.
edi_voxel_sale_order_import: unmet dependency onchange_helper for series 13.0. Dependency might be invalid.
edi_exchange_template: unmet dependency edi for series 13.0. Dependency might be invalid.
```

For other branches same story but for different modules.

**Comment by simahawk** [comment]
> > @simahawk @dreispt can you please check if all OCA branches for OCA/edi are published in Odoo Apps and which status they have?
> 
> Just had a quick look. For 13.0 some modules are registered (eg: base_edi) some are not because of missing dependencies.
> I guess because other modules from other repos are not registered/updated for 13.0.
> Funny thing is that there's no `edi` module yet but it complains like "Module edi already exists for another serie.".
> 
> ```
> Module edi already exists for another serie. Please select a free module name or use the right user account.
> edi_storage: unmet dependency edi for series 13.0. Dependency might be invalid.
> edi_voxel_secondary_unit: unmet dependency product_secondary_unit for series 13.0. Dependency might be invalid.
> edi_xml: unmet dependency edi for series 13.0. Dependency might be invalid.
> sale_order_import: unmet dependency onchange_helper for series 13.0. Dependency might be invalid.
> edi_account: unmet dependency edi for series 13.0. Dependency might be invalid.
> edi_webservice: unmet dependency edi for series 13.0. Dependency might be invalid.
> sale_order_import_ubl: unmet dependency sale_order_import for series 13.0. Dependency might be invalid.
> sale_order_import_ubl_http: unmet dependency auth_api_key for series 13.0. Dependency might be invalid.
> edi_voxel_sale_order_import: unmet dependency onchange_helper for series 13.0. Dependency might be invalid.
> edi_exchange_template: unmet dependency edi for series 13.0. Dependency might be invalid.
> ```
> 
> For other branches same story but for different modules.

Checking one of those dependencies: `Module onchange_helper already exists for another serie. Please select a free module name or use the right user account.` (from server-tools).

Seems broken to me, no?

**Comment by dmo-odoo** [comment]
@rrahir Coud you please ping the current manager of Odoo Apps ? I think the position has changed a few times. #DefenseAgainstTheDarkArts

**Comment by rrahir** [comment]
@ndeodoo Could you have a look at the last messages in this conversation and explain the situation ? :)

**Comment by ndeodoo** [comment]
> > @simahawk @dreispt can you please check if all OCA branches for OCA/edi are published in Odoo Apps and which status they have?
> 
> Just had a quick look. For 13.0 some modules are registered (eg: base_edi) some are not because of missing dependencies.
> I guess because other modules from other repos are not registered/updated for 13.0.
> Funny thing is that there's no `edi` module yet but it complains like "Module edi already exists for another serie.".
> 
> ```
> Module edi already exists for another serie. Please select a free module name or use the right user account.
> edi_storage: unmet dependency edi for series 13.0. Dependency might be invalid.
> edi_voxel_secondary_unit: unmet dependency product_secondary_unit for series 13.0. Dependency might be invalid.
> edi_xml: unmet dependency edi for series 13.0. Dependency might be invalid.
> sale_order_import: unmet dependency onchange_helper for series 13.0. Dependency might be invalid.
> edi_account: unmet dependency edi for series 13.0. Dependency might be invalid.
> edi_webservice: unmet dependency edi for series 13.0. Dependency might be invalid.
> sale_order_import_ubl: unmet dependency sale_order_import for series 13.0. Dependency might be invalid.
> sale_order_import_ubl_http: unmet dependency auth_api_key for series 13.0. Dependency might be invalid.
> edi_voxel_sale_order_import: unmet dependency onchange_helper for series 13.0. Dependency might be invalid.
> edi_exchange_template: unmet dependency edi for series 13.0. Dependency might be invalid.
> ```
> 
> For other branches same story but for different modules.

Actually, there is a module named edi in Odoo v8.0 (from 5.0 to 8.0 actually). As this name is already reserved, you cannot add a module named `edi` because you are not the last maintainer having reserved this namespace (N.B.: Odoo modules bypass the names reservation). Moreover, Odoo modules are not visible on the portal, this is the reason you don't find any `edi` module on the Apps Store.

Moreover, As I can see in the `scan_log` of the repository: https://github.com/oca/edi/tree/13.0 . Your `edi` module was never created for 13.0 because you don't own the name. It also results that the module `edi_storage` for e.g. is not created because one of its dependencies is missing (no `edi` module for  v13.0). 

N.B.: If Odoo had a module named `edi` for the v13.0, your modules would probably depends on the `edi` module of Odoo and not the one you created.

**Comment by jco-odoo** [comment]
@ndeodoo Conclusion: we can call it edi again

**Comment by ndeodoo** [comment]
For me it's ok as the namespacing is already reserved by Odoo on apps Store :)

**Comment by pedrobaeza** [comment]
AFAIK, last `edi` module from Odoo S. A. was in 6.1 (where the apps didn't even exist), but OK, your store, your rules, and that's why I prefer https://odoo-community.org/shop

**Comment by ndeodoo** [comment]
> AFAIK, last `edi` module from Odoo S. A. was in 6.1 (where the apps didn't even exist), but OK, your store, your rules, and that's why I prefer https://odoo-community.org/shop

You can check, the last version is in Odoo 8.0, but the issue is not when the module has been published. The problem is that when a name is reserved, it's reserved forever. 

B.t.w the namespace is associated to a maintainer in order to avoid another maintainer to steal your module. The Odoo module is also necessary on the store to manage the dependencies and I totally agree with you that Odoo should avoid stealing name of third party apps.  In this case, switching back to `edi` won't change anything for you as your module didn't even exist on the store because the module name is reserved since v5.0 .

**Comment by jco-odoo** [comment]
The latest fashion is that probably in the future we won't need an edi module anyways.  But maybe an edi is just one or more files linked to business objects anyways. Anyways, this is not current anymore.  (but it might become fashion again)

**Pull request closed without merging**
