### PR TITLE
Master product publication seb

### PR DESCRIPTION
**Pull request by seb-odoo**
rebase-ff

### CODE REVIEW

**Comment by seb-odoo** [comment]
@rdeodoo for the publication `track_visibility`, on which field is it better? `website_published`, `is_published` or even something else?

**Comment by rdeodoo** [comment]
on `is_published` as `website_published` end up writing on `is_published` and is overrided in  `WebsitePublishedMultiMixin`.
I guess every `website_published` without the mixin should also get that track property

**Comment by seb-odoo** [comment]
On `is_published` made it consistent when doing it manually vs demo data, but now it's always adding the log in the chatter 2 times.

**Comment by seb-odoo** [comment]
The duplicate log is because there is a `write` inside `write` due to `_inverse_website_published`. This is a general issue with all inverse fields, and all other potential recursive calls to`write`.

The code for field tracking just does not take that into account... For every `write` in the stack, it checks the values of tracked fields before and after, no matter if it was already done.

There should probably be a contextual variable "already in write for the current record" to disable additional calls to the tracking code on the same record.

There is already the context `tracking_disable` but I think it is too generic to pass (it would disable tracking on other records or records from other models too).

**Comment by seb-odoo** [comment]
@JKE-be due to above issue that is too hard to fix/out of scope, I dropped the tracking commit, so we can merge the default value at least.

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by d-fence** [comment]
@robodoo retry

**Comment by JKE-be** [comment]
@robodoo retry

**Pull request closed without merging**
