### PR TITLE
[REF] Credit limit added to partner view form

### PR DESCRIPTION
**Pull request by hugho-ad**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

OPW 1911768

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by moylop260** [comment]
@mart-e 
FYI There is a field defined in the model but is not used from view or another site.

Do you know why is not added to the view or if this field could be included?

**Comment by moylop260** [comment]
I got it
Thank you Pedro

**Comment by mart-e** [comment]
This field is present since the beginning of time (aka 004a0b996ff8f269451e07346f71a129a1f3fbaf ) and it was in a view at that time.
Now this field is only used in l10n_nl_reports (enterprise).

How about removing it from base (and keeping it in l10n_nl_reports) in master?

**Comment by fclementic2c** [comment]
Not having a standard functionality to block SO validation based on open amounts + amount of SO not invoiced is unbelievable. 
This is not the job of the community to fill such an obvious gap.

**Comment by mart-e** [comment]
Yo uare right, I have reported the feedback to see if we wish to make the field actually have the expected effect as in the OCA module (if not, remove it).
In the meantime, I do not think it is a good idea to display a field that has no effect, it would be misleading.

**Pull request closed without merging**
