### PR TITLE
[REF] base: Change city name

### PR DESCRIPTION
**Pull request by moylop260**
English news:
- https://www.theguardian.com/world/2016/jan/29/mexico-city-name-change-federal-district-df

Official reference (spanish):
- http://www.dof.gob.mx/nota_detalle.php?codigo=5424565&fecha=05/02/2016

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e quick and easy merge. LGTM.

**Comment by mart-e** [comment]
You are changing the name of the state in Brzail, isn't it the one from Mexico your article is referring to?
No so quick and easy :wink:

**Comment by pedrobaeza** [comment]
Wow, I didn't even notice that! Sorry for my lead answer.

**Comment by moylop260** [comment]
Thanks @mart-e  and sorry. Fixed!

**Pull request closed without merging**
