### PR TITLE
[REF] mail: `MailTemplate`, review and simplify scss

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Part of the overall v16 SCSS optimization/restyle, task-2704984

task-2818801

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hello @seb-odoo @alexkuhn 👋
This PR is ready for review 👍

cc. @stefanorigano

**Comment by alexkuhn** [comment]
@Brieuc-brd don't forget to change kanban status in our project, it's easier to let us know we have this to do during busy times. Especially when we receive many notifications and we have to discard some to be on pace with the things we have to do. ;)

**Comment by Brieuc-brd** [comment]
> @Brieuc-brd don't forget to change kanban status in our project, it's easier to let us know we have this to do during busy times. Especially when we receive many notifications and we have to discard some to be on pace with the things we have to do. ;)

Hey @alexkuhn 👋 
Sorry I didn't know, I will for the next PRs 👍 .

**Review by alexkuhn — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
