### PR TITLE
[FIX] website, web_editor: dropzone transparency and read-only handles

### PR DESCRIPTION
**Pull request by Brieuc-brd**
=== ISSUE 1 ===
Since the introduction of the new dropzone design, the dropzones weren't
transparent enough and the inline content behind them wasn't readable.

This PR adapts the layout of dropzones to make the content behind
them more readable.

=== ISSUE 2 ===
Prior to this PR, read-only handles were hidden, which created a
layout issue (eg. the header was no longer highlighted when we clicked
on it).

This PR adapts read-only handles to make them visible by using a
border around the selected element.

task-3537616

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bvr-odoo** [comment]
Thanks @Brieuc-brd 
I just have a small comment regarding the overlay
Capture d’écran du 2023-10-04 15-05-04
Before the border was inside the element, I think... Now it seems cut off and thinner when it touches the edge of the screen... I'll let you see if it's ok or not... cc @qsm-odoo

**Review by qsm-odoo — APPROVED** [review]
I made this change: https://github.com/odoo/odoo/compare/9bf910e776fe3e97f09c54221b795e3aab33e842..b602ed2b1c7b4c2f1ad48e1f013aca73b09c3d76 (you wanted 0.75, @bvr-odoo preferred 0.35, I compromised and chose 0.5), also set up some new variables.

Thanks for the fixes :+1: 

@robodoo rebase-ff r+

**Comment by Brieuc-brd** [comment]
Hey @qsm-odoo 👋 
Using `0.75` was the best compromise I found to keep the dropzone text readable regardless of the background page.
With`0.5` it makes the dropzone text hard to read on dark background :/ 

| 0.75 | 0.5 |
|--------|--------|
| Capture d’écran 2023-10-05 à 13 02 04 |Capture d’écran 2023-10-05 à 12 56 20
 |

**Comment by qsm-odoo** [comment]
@Brieuc-brd Maybe this should be about restoring that then https://github.com/odoo/odoo/pull/111515#issue-1564565958 no? I don't think we will find a color which works when being set to transparent enough :grimacing: 

@robodoo r-

**Comment by qsm-odoo** [comment]
> I've made these small changes, what do you think ?

I preferred the lightened color over a white website... but I guess it is a matter of taste :+1: For now, this fixes all issues. Not lightening the color also makes it feel less transparent but transparent enough I think :+1: Let's go with that for now.

@robodoo r+

**Pull request closed without merging**
