### PR TITLE
[FIX] website: fix translate in dev xml mode

### PR DESCRIPTION
**Pull request by HydrionBurst**
[FIX] website: fix translate in dev xml mode
Before this commit:
in the --dev=xml mode, terms in ir_ui_view.arch cannot be correctly wrapped with translation tags in the edit_translation=True context

After this commit:
The logic of get_trans_func is moved to _compute_arch of model ir.ui.view, since ir_ui_view is its only use case and the hack
  with_context (edit_translation=None)
makes the logic very confusing as a method for Fields.

[FIX] website: skip view's copy-on-write when updating translations
Since [1] when the translations were converted to jsonb, when
translations are saved, the actual `ir.ui.view` is saved (instead of a
translation record like before). Because of this, the copy-on-write
mechanism of `website` kicks in and unneeded website-specific views are
created.

This commit disables the copy-on-write mechanism during the update of
translations in views.

Steps to reproduce:
- Install `website_sale`.
- Install a second language (e.g. French).
- Go to a single product's website page in the second language.
- Translate the "ADD TO CART" button.

=> Many website-specific views were created.

[1]: https://github.com/odoo/odoo/commit/4e82c45abdb0b420edead2bd1d0ba9ff4bb4a224

task-3225622

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rco-odoo — APPROVED** [review]
The first commit is fine by me.
I cannot tell anything about the second one.

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
Tested the second commit, seems to work :+1: @bso-odoo Do you think that you could add a test about this? It's a very critical issue and we only find it now... scary :grimacing: 

Also, I tested an extended flow that this happens to solve as well, and I am not sure why:
- Install `website_sale`.
- Install a second language (e.g. French).
- Go to a single product's website page in the second language.
- Translate the "ADD TO CART" button.
- Now change the XML repo code of the "Product" view (e.g. I tested by adding ` style="border: 5px solid red !important;"` on the "All Products" breadcrumb item.
- Restart your server with eCommerce update (`-u website_sale`)

=> After this PR, the content of the ADD TO CART button stays translated and I also receive the view update I made (both in english and french).
=> Before this PR, the content of the ADD TO CART button stays translated but I don't receive the view update (neither in english nor french)

The fact that before this PR the views were COWed by mistake should not change anything: we update COWed view if their arch is exactly the same, which is supposed to be since it was only translated (and that we apparently can receive update without losing translations, as described above) => Could you have a look at this too @bso-odoo (this can be in another task / other PR).
The sooner we fix this the better, I have enough migration nightmares as it is :grimacing:

**Comment by bso-odoo** [comment]
@qsm-odoo I have added a test that replicates the steps to reproduce of the commit. It then checks if no additional website-specific view was created, and if the new translation is taken into account. It fails if the fix is removed.

**Comment by bso-odoo** [comment]
@qsm-odoo Moved test together with the other cow-related tests.

**Review by qsm-odoo — APPROVED** [review]
Looks good :+1: I would be worried about removing a python function in stable but since RCO approved, I'll not worry about it :+1: 

@robodoo rebase-ff r+

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: compute hash of content

**Pull request closed without merging**
