### PR TITLE
[V12.0] - Throw error while applying js_class in calendar view.

### PR DESCRIPTION
**Pull request by RishabhJadia**
Description of the issue/feature this PR addresses:
In version 12.0-
When inherit calendar view and try to apply js_class inside calendar tag it throw an error but when applying from addons it works correctly.
 
Current behavior before PR:

Throw an error while applying js_class in calendar view on inherit.
odoo_bug

Desired behavior after PR is merged:

It should work when inhert the calendar view bacause it works correctly with addons but not during inherit.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by RishabhJadia** [comment]
@hmo-odoo  @JKE-be  

This bug is still not solved. Please solve this on priority.
Its v12.0 bug.

**Comment by JKE-be** [comment]
@RishabhJadia 

Please, start to fix your PR target.
And provide example to illustrate your bug.

Thanks

**Comment by RishabhJadia** [comment]
> @RishabhJadia
> 
> Please, start to fix your PR target.
> And provide example to illustrate your bug.
> 
> Thanks

**Comment by RishabhJadia** [comment]
Thanks, @JKE-be bug is solved.

Basically, This is is from the calendar_view.rng file. Here, js_class is not there now it is fixed.

**Comment by RishabhJadia** [comment]
Now, I am closing this. it is resolved.

**Pull request closed without merging**
