### PR TITLE
[FIX] doc: backend, internationalization, renamed menus

### PR DESCRIPTION
**Pull request by beledouxdenis**

### CODE REVIEW

**Comment by beledouxdenis** [comment]
@mart-e Can you just confirm "Generate Missing Terms" is well the new "Synchronize Translations". That's the only point I am not 100% sure : D

**Comment by mart-e** [comment]
@beledouxdenis yes, "Synchronize" was confusing and people thought it meant "Update"
Don't forget the translation menus changed later (in 13.0 I think).
Also some menus are visible only in debug (but this changed also at like each version)
:cake:

**Comment by beledouxdenis** [comment]
> Don't forget the translation menus changed later (in 13.0 I think).
This was actually the thing I was solving, when I realized some parts were already wrong since the 8.0 documentation :D. But 11.0 being the last supported stable, I correct this starting from 11.0.

**Comment by beledouxdenis** [comment]
@robodoo r+

**Pull request closed without merging**
