### PR TITLE
8.0 invoice shipping address

### PR DESCRIPTION
**Pull request by scosist**
When a different delivery address exists for a sales order it does not show on the invoice.

Impacted versions: 8.0

Steps to reproduce:
1. create a new sale order
2. specify a different delivery address
3. confirm the sale (when you print the sales order, shipping address is shown)
4. create invoice
5. print invoice

Current behavior:
Delivery/shipping address does not show on the invoice.

Expected behavior:
Show different delivery/shipping address on an invoice when specified on a sales order and allow it to show on invoice_form when 'group_sale_delivery_address' is True.

### CODE REVIEW

**Comment by scosist** [comment]
So if I submit this PR as a custom module for 8.0, will it be accepted?

**Comment by mart-e** [comment]
@scosist adding it as a custom module is a way to make it work without breaking [stability guidelines](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) but it still a new feature so it won't be accepted in core, sorry.

**Comment by bodi000** [comment]
Incoicing address is different than the delivery address. If you set a
invoicing address different than the default one it should be printed on
the invoice. So you need nothing to be changed.

At least it used to be this way in good old days of openerp. No time to
check for v8 though.

And it should be this way.

Regards
B

**Comment by scosist** [comment]
@mart-e would it be accepted in master? Can you suggest a community repository that we can submit this to so that we and others can benefit from this feature in v8 in the meantime?

@bodi000 if you're saying an invoice address set on a sale order that is different from the customer address is printed on the invoice then that is the current behavior in v8 which is allowed by enabling the `sale.group_delivery_invoice_address` config setting. However, if you're saying a delivery address set on a sale order that is different from the customer address and invoice address is being printed on the invoice in versions of openerp prior to v8 then I would consider this issue a regression.

**Pull request closed without merging**
