### PR TITLE
[FIX] website_links: fix UI for big data

### PR DESCRIPTION
**Pull request by jvnm-dev**
This commit increase the containers sizes in linktracker
because at the moment it's not adapted for big data.

It also add title attributes on truncated link to
preview the full link on hover.

OPW-2203428

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
@qsm-odoo Could you check this please?

**Comment by jvm-odoo** [comment]
@qsm-odoo I retargeted master and reviewed the commit message

**Comment by jvm-odoo** [comment]
Indeed! I will remove them.

**Comment by jvm-odoo** [comment]
Should be good!

**Comment by jvm-odoo** [comment]
I think runbot is red because of the branch's name. I will make another PR.

**Comment by jvm-odoo** [comment]
#47071

**Comment by qsm-odoo** [comment]
... why would it be red because of the branch name? It was just because master was red at that time

**Pull request closed without merging**
