### PR TITLE
[FIX] config: update publisher warranty url

### PR DESCRIPTION
**Pull request by rim-odoo**

### CODE REVIEW

**Review by nim-odoo — APPROVED** [review]
robodoo r+

**Comment by tbe-odoo** [comment]
@robodoo r- sorry but I don't think this is a stable change.

**Comment by rim-odoo** [comment]
@tbe-odoo Naive question: why?

When people ask which ports/hosts they have to allow in their firewall to be able to ping, it sounds a bit odd that we have to tell them "allow services.openerp.com", don't you think?

**Comment by tbe-odoo** [comment]
Hello @rim-odoo , sure I can explain.

The domain change isn't the issue here since services.openerp.com is a CNAME pointing to services.odoo.com.
The real issue is the switch from a HTTP request to a HTTPS one.

Some people may have blocked all communications to internet but have authorized the communications to _services.openerp.com_ port _80_, where after this commit it will contact the port 443.

And in some countries, they are not allowed to use American made crypto (like SSL) and may not have the necessary packages to make HTTPS requests.

For a stable branch I am not sure this is a good idea to change this URL, but on master I don't see any issue.

**Comment by rim-odoo** [comment]
@tbe-odoo Ok thanks for the explanation, I didn't know about the American-made crypto ban in some countries :)

I'll retarget this for master

**Pull request closed without merging**
