### PR TITLE
[IMP] Replace self.env.uid by self.env.user.id

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Description of the issue/feature this PR addresses:

This PR simply replace `self.env.uid` by `self.env.user.id` in sales_team module.

Current behavior before PR:

We have a crash with OCA module https://github.com/OCA/server-tools/issues/708

Desired behavior after PR is merged:

No crash :smile: 

https://www.odoo.com/web/#id=706295&view_type=form&model=project.issue&action=609&menu_id=4720

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
OPW 706295

**Comment by mart-e** [comment]
@adrienpeiffer a bit of context is always appreciated, we are not very familiar with OCA's module...

```python
@property
def user(self):
    """ return the current user (as an instance) """
    return self(user=SUPERUSER_ID)['res.users'].browse(self.uid)
```
`self.env.uid` is the same than `self.env.user.id` (+ the cost of a new browse)

**Comment by adrienpeiffer** [comment]
Hi Martin,

Thanks for your answer, Sorry for the not complete description :smile: 

This problem occurs when using `base_suspend_security` module. Briefly, this module allows to do a ```sudo()```  while preserving the context of the user using a new pytho object defined in this module (`class BaseSuspendSecurityUid(int)`). So in the browse method of user model, we cast this new type in integer. 

Regardless of this, I find that it's cleaner like this. Considering this, and taking into account the low risks of regression, I hope that this can be merged in version 10.0.

Thanks,

Adrien

**Comment by mart-e** [comment]
Thanks for the info.

I think I understand +/- what you are doing but let's face it, we do not really have much reason to change it in standard (on the contrary, `user.id` has an higher footprint).
```shell
$ grep -r "self.env.uid" addons/ | wc -l
103
```
Are the 102 others going to be an issue too?

Don't you think it is more logical to handle this scenario in your module? Or even do something like
```python
def _get_default_team_id(self, user_id=None):
    if not user_id:
        user_id = self.env.user.id
    return super(CrmTeam, self)._get_default_team_id(user_id=user_id)
```

**Comment by adrienpeiffer** [comment]
> Are the 102 others going to be an issue too?

No because in this case, the user id which is an instance of BaseSuspendSecurityUid (Not integer) is put in a domain. So the final exception is raised in where_calc method. But in fact, there could be other cases. 

> Don't you think it is more logical to handle this scenario in your module? Or even do something like

Yes, this could fix the problem for my project. Thanks for the idea !
Otherwise, it's a shame for the OCA module :cry:

**Comment by mart-e** [comment]
Well sorry but as there is a workaround and the issue occurs in a very specific conditions with manipulated environment, I will reject it.
Thanks for your understanding.

**Comment by adrienpeiffer** [comment]
Ok. No problem.
Thanks for your answer :smile:

**Pull request closed without merging**
