### PR TITLE
[FIX] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by pro-odoo**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/b167b3e6 [FIX] selection: Altering selection should scroll the viewport

### CODE REVIEW

**Comment by pro-odoo** [comment]
fw-bot ignore

**Comment by rrahir** [comment]
@¶obodoo r+

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
sister in community https://github.com/odoo/enterprise/pull/34336

**Comment by rrahir** [comment]
@robodoo retry

**Pull request closed without merging**
