### PR TITLE
[Master][IMP][l10n_de] account number cleanup, switch account user-type to standard

### PR DESCRIPTION
**Pull request by mncoon**
In this pull-reqest I changed the `user-type` field in the `account_chart` files from the separate defined ones in `account_types_skr03.xml` and `account_types_skr04.xml` to the standard in odoo and deleted the both files. 

There was only one user-type left. Therefor I created a new file called `account_types.xml`.

I also deleted some account numbers which are not realy needed, because it's something like "created twice" with the next higher account number eg (in the old file):

```
    <record id="chart_skr04_1100" model="account.account.template">
      <field name="code">1100</field>
      <field name="name">Fertige Erzeugnisse und Waren (Bestand)</field>
      <field name="parent_id" ref="chart_skr04_K1BA15"/>
      <field name="reconcile" eval="False"/>
      <field name="type">other</field>
      <field name="user_type" ref="account_type_asset_de"/>
    </record>

    <record id="chart_skr04_1101" model="account.account.template">
      <field name="code">1101</field>
      <field name="name">Fertige Erzeugnisse und Waren (Bestand)</field>
      <field name="parent_id" ref="chart_skr04_K1BA15"/>
      <field name="reconcile" eval="False"/>
      <field name="type">other</field>
      <field name="user_type" ref="account_type_asset_de"/>
    </record>

    <record id="chart_skr04_1102" model="account.account.template">
      <field name="code">1102</field>
      <field name="name">Fertige Erzeugnisse und Waren (Bestand)</field>
      <field name="parent_id" ref="chart_skr04_K1BA15"/>
      <field name="reconcile" eval="False"/>
      <field name="type">other</field>
      <field name="user_type" ref="account_type_asset_de"/>
    </record>
```

This is something the user should do, if he needs it, but nomally it is not needed in germany.

It's a first step, to bring up some improvements to the german-accounting.

@tv-openbig can you please check and give me a feedback if everything is fine.

### CODE REVIEW

**Comment by copmn** [comment]
@odony can someon give me a status or a information about merging this. 3 month are over and there is no anwer from tv-openbig.

**Comment by tv-openbig** [comment]
Hello Matthias,
unfortunately i have not recognized it before. Sorry for that. 
The type cleaning makes for sure sense and i also agree to the cleaning of the accounts you mentioned.
Are you waiting for other open pull requests towards l10n_de?

Thorsten Vocks

**Comment by copmn** [comment]
Hello Torsten,
thank you very much for your quick answer. At the moment I don't have other open pull requests.
If I have some, I will inform you, so we can discuss / check them together.

**Comment by qdp-odoo** [comment]
i finally got some time to have a look at it, but our indian workforce already ported this module to the new accounting... and it seems it would be more easy to keep what we've done as a basis for further improvements: indeed, i checked and your PR is, now, conflicting a lot and refering to unexisting xml ids...

Sorry for that, if i looked at it months ago this would have been accepted.

Please check https://github.com/odoo-dev/odoo/tree/master-l10n_de-back-rsi and let me know what are the accounts you wanted to remove (i think that's the only thing missing from your original PR) or the modifications you'd like to see.

Thanks, anyway, for the contribution

**Pull request closed without merging**
