### PR TITLE
[FIX] purchase: invoice state for delivery partially cancelled

### PR DESCRIPTION
**Pull request by nim-odoo**
This applies only if invoice_method = 'picking'.

If you transfer less than planned and cancel the remaining quantity, it is not
possible to set the PO in:
- 'done': all lines are not invoiced
- 'cancel': some products are already transferred

With this fix, the lines are considered as invoiced if all pickings are
'invoiced' or 'cancel'.

opw-644399

### CODE REVIEW

**Comment by nim-odoo** [comment]
cc: @sve-odoo

**Comment by beledouxdenis** [comment]
1. Shouldn't that be a `or` statement instead of a `and` ?

**Comment by nim-odoo** [comment]
indeed :+1:

**Comment by nim-odoo** [comment]
Arf no, actually. I will rewrite this to have a condition which is more clear.

**Comment by nim-odoo** [comment]
OK, corrected. It was working on the first try by chance, but the proper fix is more complex. 

Common steps to reproduce:
- Create a purchase order for 40 products
- In "additional info", choose invoicing control: based on incoming shipments
- Confirm the PO
- Go to the incoming shipment
- Click "Transfer", in the wizard, only receive 37

Case 1:
- Click on "Create Invoice", "Create"
- Validate the invoice
- Go back to the list of picking, and cancel the remaining picking (backorder)
- Go back to the PO, click on "Manually Corrected" ==> we go through "picking_done"

Case 2:
- Cancel the remaining picking (backorder)
- In the PO, see that it is in "shipping exception" and click "Manually corrected"
- Click on "Create Invoice" for the picking which is done, then "Create"
- Validate the invoice ==> we go through "invoice_validate"

**Comment by beledouxdenis** [comment]
- Not sure about your 
```
self.pool['purchase.order.line'].write(cr, uid, po_lines_by_id, {'invoiced': True})
```

That would mean cancelled lines could be flagged as `invoiced`, while they actually were cancelled, and therefore do not have an invoice.

- Besides, for clarity, you should probably avoid to change
```
shipped = True
```
to
```
shipped = True if order.invoice_method != 'picking' else False
```

- And I am not sure that checking
```
all(picking.invoice_state == 'invoiced' for picking in order.picking_ids if picking.state == 'done')):
```
is useful to know if the PO is - shipped - . The fact all pickings are done or cancelled, and there is not only cancelled, is enough to me.

I believe you can change:

```
    shipped = True if order.invoice_method != 'picking' else False
    if (order.invoice_method == 'picking' and
               all(picking.state in ('done', 'cancel') for picking in order.picking_ids) and
               not all(picking.state in ('cancel') for picking in order.picking_ids) and
               all(picking.invoice_state == 'invoiced' for picking in order.picking_ids if picking.state == 'done')):
               shipped = True
```
to
```
    shipped = True
    if (order.invoice_method == 'picking' and
               any(picking.state not in ('done', 'cancel') for picking in order.picking_ids) or
               all(picking.state in ('cancel') for picking in order.picking_ids):
               shipped = False
```

**Comment by nim-odoo** [comment]
> That would mean cancelled lines could be flagged as invoiced, while they actually were cancelled, and therefore do not have an invoice.

That is fine, because:
```python
po_lines_by_id = [x.id for x in po.order_line if x.state != 'cancel']
```

> And I am not sure that checking
```
all(picking.invoice_state == 'invoiced' for picking in order.picking_ids if picking.state == 'done')):
```
is useful to know if the PO is - shipped - . The fact all pickings are done or cancelled, and there is not only cancelled, is enough to me.

Hum, I think this might still be necessary, and actually that was the condition which was used in a first place. The reason is the following lines:
```python
for po_line in order.order_line:
    if (po_line.invoice_lines and 
            all(line.invoice_id.state not in ['draft', 'cancel'] for line in po_line.invoice_lines)):
        invoiced.append(po_line.id)
```
A PO line can be split in many pickings. You have to make sure that all related pickings are invoiced before setting the PO lines to 'invoiced' state.

> Besides, for clarity, you should probably avoid to change
```
shipped = True
```
to
```
shipped = True if order.invoice_method != 'picking' else False
```

Yes, I agree. The thing is that the following condition is much simpler to write if we do so.

**Comment by beledouxdenis** [comment]
For the 
```
all(picking.invoice_state == 'invoiced' for picking in order.picking_ids if picking.state == 'done')):
```
Indeed, I saw it was the previous condition. I still believe this is unnecessary, but well, to make sure we do not mess up everything, we can keep it :).

For 
> That is fine, because:
```
po_lines_by_id = [x.id for x in po.order_line if x.state != 'cancel']
```

Well, is it ensured that the PO line is cancelled as soon as its picking line is cancelled ?

**Comment by nim-odoo** [comment]
I took a different approach: the invoiced state of PO line is based on invoiced state of corresponding moves. I think it is more coherent, and provides a simpler solution.

cc: @odony

**Pull request merged**
