### PR TITLE
[FIX 8902] Add reconcile column to char of account in l10n_br

### PR DESCRIPTION
**Pull request by cmsalmeida**
In order for the payment wizard to work, the accounts in invoice header, account_id, should have reconcile=True.
In l10n_br the accounts are, amongst others, "Clientes" and "Fornecedores", a the chart of account should make them by default as reconciliable.

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thanks for the PR.
The diff I quite unreadable but it seems (I trust you did) only modified the last command.
Before merging it, could you [sign the CLA](https://odoo.com/sign-cla)?

By the way no need to create an issue and a pull request. Just create the pull request with the bug report is enough

**Comment by cmsalmeida** [comment]
Done :+1:  TKS

**Comment by danimaribeiro** [comment]
:+1: I checked the diff, and tested.

**Comment by mart-e** [comment]
@cmsalmeida thanks but you signed the CLA for your email `@tkobr.com` but made your commit with the `@thinkopensolutions.com.br` address. To be validated, it needs to be both the same.

**Comment by cmsalmeida** [comment]
I think now it's ok :)

**Comment by mart-e** [comment]
Thanks for the update, I have merged both

48eb1f6 [FIX] l10n_br: specify accounts that can be used to reconcile
78b1083 [CLA] signature for cmsalmeida

**Comment by cmsalmeida** [comment]
tks :+1:

**Comment by mart-e** [comment]
@cmsalmeida I believe this PR needs to be adapted for 9.0 as the CoA has been modified. Could you please have a look ?

Thanks

**Comment by danimaribeiro** [comment]
In 9.0 this column is correctly, if I'm not mistake there are only two account that have different values in reconcile column from 8.0 to 9.0, but they are not so important.

**Comment by mart-e** [comment]
Ok great, thanks

**Comment by cmsalmeida** [comment]
To do that we will have to rebuild the Brazilian localization, and to do that a huge amount of changes and time will be required. We where already struggling to complete it in v8.0.
I think we will get stucked in v8.0 for a long long time.

**Pull request closed without merging**
