### PR TITLE
[IMP] mail: change the description field label in mail.template

### PR DESCRIPTION
**Pull request by dise-odoo**
Changed the description field label in mail.template so it suits the current labeling policies.

task-3251693

### CODE REVIEW

**Review by auon-odoo — APPROVED** [review]
thanks :)

**Review by MissingNoShiny — APPROVED** [review]
robodoo r+

**Review by MissingNoShiny — APPROVED** [review]
@robodoo r+

**Comment by MissingNoShiny** [comment]
@robodoo r+

**Pull request closed without merging**
