### PR TITLE
[IMP] crm: added a hook to be sure the website is correctly formated.

### PR DESCRIPTION
**Pull request by nboulif**
Step to reproduce:
- Go to CRM app
- Create a new opportunity and edit it
- Alter the website field under "Contact Information" tab
  with "www.anywebsite.com"
- Save and click on the website field value.

Without this fix, the field redirect as it's local:
"http://www.myodoo.com/www.anywebsite.com"

porting 726fad8

opw-2247853

### CODE REVIEW

**Comment by agr-odoo** [comment]
since it is almost a static function why don't we move it into some common place like odoo/tools/misc.py?

**Comment by nboulif** [comment]
@nim-odoo 
> You should this instead of duplicating

Sorry, I did not understood...

@agr-odoo 
> since it is pratically a static function why don't we move it into some common place like odoo/tools/misc.py?

Good idea :+1:

**Comment by nim-odoo** [comment]
You could call directly: `self.env['res.partner']._clean_website(website)`

> since it is pratically a static function why don't we move it into some common place like odoo/tools/misc.py?

That's an option, although there doesn't seem to be other `website` fields likely to use it. I think at the moment, we can leave there and see later if it is worth moving it in tools.

**Comment by nboulif** [comment]
@nim Done :+1:

**Pull request closed without merging**
