### PR TITLE
[FIX] iot_box_image: image build cleanup

### PR DESCRIPTION
**Pull request by loouis-t**
After an image build, residual mappers where kept in `/dev`. We then added a better cleanup logic, along with a dedicated cleanup CLI tool.

Task: 4430598

### CODE REVIEW

**Review by Ysoroko — APPROVED** [review]
@robodoo r+

**Comment by qle-odoo** [comment]
@loouis-t maybe you can remove kpartx virtual folder for iotbox and debian ?

**Review by qle-odoo — APPROVED** [review]
@robodoo +

**Comment by qle-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
