### PR TITLE
[FIX] calendar: add default data and signature to event mail template

### PR DESCRIPTION
**Pull request by mafo-odoo**
Issue:
When visualizing the calendar event update mail template there is few
or no default data. Unlike the other calendar mail template there is
no signature.

opw-2968890

### CODE REVIEW

**Comment by mafo-odoo** [comment]
@arj-odoo I don't know what you think about it but I have mixed fillings about these changes, is it worth breaking the translation of the email in stable to add default data and a signature?

**Comment by arj-odoo** [comment]
> @arj-odoo I don't know what you think about it but I have mixed fillings about these changes, is it worth breaking the translation of the email in stable to add default data and a signature?

No, people will be pissed if the mail is not in their language anymore. You can retarget your PR on master and we will merge it. It is not broken, it is an IMP.

**Comment by mafo-odoo** [comment]
@arj-odoo

**Comment by mafo-odoo** [comment]
@arj

**Comment by pivi-odoo** [comment]
@arj-odoo I am pretty this needs just a little r+ :)

**Comment by pivi-odoo** [comment]
@arj-odoo a grim reminder that this PR needs an r+ :)

**Comment by arj-odoo** [comment]
@robodoo r+ thanks :-)

**Pull request closed without merging**
