### PR TITLE
[IMP] *: avoid calling CRUD methods to empty records

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
The CRUD methods are inherited in many models through many modules. When they are called, they form a chain of super() calls through module dependencies until the core is reached (where the CRUD methods are defined). If the CRUD methods are called on empty records/value_lists, forming this chain is inefficient.

Thus, this commit aims to avoid calling this chain of super() in several cases. The aim is not to be exhaustive, just only correcting the most relevant (found) cases.

Moreover, besides obtaining slightly better performance, less spiky flamegraphs and less error-prone code, it will help with manual debugging and cron interruptions.

**Current behavior before PR:**
Selection_2727
Selection_2730

**Desired behavior after PR is merged:**
Selection_2732
Selection_2733

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
IMHO, this is the wrong approach.
CRUD methods are expected to work with empty self/`vals_list` (as the base methods in `models.p`y do).
We should instead fix the overrides not handling the situation perfectly and doing things when they shouldn't be doing anything.

**Comment by Xavier-Do** [comment]
Hello, thanks for trying to speedup odoo.

Anyway the diff is not minimal for a small improvement IMHO

As an example, it look like the improvement made in one of the unlink of account_payment_term

```python
def unlink(self):
        for terms in self:
            self.env['ir.property'].sudo().search(
                [('value_reference', 'in', ['account.payment.term,%s'%payment_term.id for payment_term in terms])]
            ).unlink()
```
will result in a domain 
```
[('value_reference', 'in', [])]
```

A false leaf, the search won't even reach the database since a16c44210ad143af5328a11ee198176f08ab664c

It's faster to check if the record has ids, that's right, but it doesn't look like it would have a huge impact on execution time. 

Looking at the screenshots, what I can see is 51 less queries overs 200k, this is not hudge (and could be linked to randomness, see those two exact same builds from the nightly multi [59046522](https://runbot.odoo.com/runbot/build/59046522) and [59046516](https://runbot.odoo.com/runbot/build/59046516)) 

I think that the time difference is mainly noise linked to the fact that build are slower when there is more load (usually between 10 and 13) 

Here is an example of a master build just a few hours before the one you used as reference https://runbot.odoo.com/runbot/batch/1362002/build/58969683

image

image

As you can see the time are not the same for a strange reason, the loading of base was way slower, maybe because of temporary load on postgresql server. Other values are lower than you branch. This is why we don't use the build time as an absolute metric, it's not precise enough. We usually prefer to focus on a small part, using a profiling to show the effect or an average of multiple builds when comparing effects on a more global scale.

There are maybe some part of your pr that are more useful than other, could be interesting to focus on those one :) But for now the effect does not look visible enough to review 600 lines.

**Review by william-andre — COMMENTED** [review]
Just an idea: should we not add a decorator to those methods (used by `MetaModel` to propagate and avoid having to define it everywhere) to return directly if `self` is empty?

**Comment by kmagusiak** [comment]
Hello,

CRUD methods support empty sets just fine and, in cases where there is a performance difference, we can add a test to skip running the method. It's already the case where needed, here's an [example in create()](https://github.com/odoo/odoo/blob/17.0/odoo/models.py#L4542).
By the way, decorators add overhead, so it's a bad solution. In my opinion, adding ifs leads to less readable code.

If you have more minimal examples where there is a performance difference, we can review and merge them.
Can this PR be closed?

Best regards,
Krzysztof

**Pull request closed without merging**
