### PR TITLE
M2m on o2m field, recursive call must send value asigned for field

### PR DESCRIPTION
**Pull request by cormaza**
Description of the issue/feature this PR addresses:
Error on domain of m2m field, get error because domain get strings values, on first call do right, but if default process two or more records on o2m field, next records fail

Current behavior before PR:

You have m2m field inside o2m field of principal class on wizard, defaults get assign value, and recursive call to set values, but process call to a string value not correct command on recursive serach

Desired behavior after PR is merged:

Assign value correctly on recursive call

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Could you explain clearly how to reproduce your problem?
You mention you have an error but at least giving the traceback could be helpful.

**Comment by cormaza** [comment]
For example you have a wizard in account.invoice in this wizard exist o2m relation that simulate invoice_lines, general idea is this lines get info of invoice_lines, product, analytic account, analytic tags, taxes, last of us with m2m relation, in default get set data in lines, and get current data of account.invoice, when you have one line in wizard can't reproduce issue, but if you have 2 or more lines, m2m field on next lines show empty, and when you try to set value, get issue showed in video that domain can't be parse with string values, in line where i find issue you get value of variable comands that is itering into algorithm, but correct is that you get value of variable 'value' to pass in recursive call, you get data only get first line, but next lines is skipped, and get error on domain

**Comment by cormaza** [comment]
Please can you say me something about this pull request?

**Comment by mart-e** [comment]
@cormaza please be patient, somebody of the framework team will review it but it can take some time.

**Comment by mge-odoo** [comment]
Hi @cormaza 

Thanks for the PR. I have merged it in 11.0 with a test case.

Regards,

Martin

**Pull request closed without merging**
