### PR TITLE
[FIX] l10n_no: fix wrong tax accounts & terms

### LINKED ISSUE #161396: l10n_no: wrong tax accounts
I just started a free accounting subscription for Norway, and I found errors in the taxes.
I downloaded [account.tax-no.csv from master](https://github.com/odoo/odoo/blob/master/addons/l10n_no/data/template/account.tax-no.csv) and did 5 corrections in the first 30 lines.

Here is the file with the corrections: [account.tax-no.csv](https://github.com/odoo/odoo/files/14936231/account.tax-no.csv)

Impacted versions: saas-17.2, master (17.0 is ok)

@mega-odoo @sovi-odoo I see that you have made PRs for accounting. Would you like to follow up this issue?

### PR DESCRIPTION
**Pull request by sovi-odoo**
- Replace "middle rate" & "average rate" by "medium rate"
- Fix misusage of accounts in taxes

See: https://github.com/Skatteetaten/saf-t

fixes odoo/odoo#161396
task-3864178

Co-Authored-By: Henrik Norlin <henrik.norl@gmail.com>

**Enterprise PR:** odoo/enterprise#64363

### CODE REVIEW

**Review by malb-odoo — APPROVED** [review]
LGTM Thanks ! :smile: Possible that the runbot will be red and you will need to rebase

**Comment by qdp-odoo** [comment]
@robodoo r+
@sovi-odoo thanks!

**Comment by malb-odoo** [comment]
Either need a retry or a rebase and r+ again :grimacing:

**Comment by sovi-odoo** [comment]
@robodoo retry

**Comment by sovi-odoo** [comment]
I've made a PR in enterprise to fix this test. Should be good now :)

**Pull request closed without merging**
