### PR TITLE
Master fix mail traceback dbh

### PR DESCRIPTION
**Pull request by dbh-odoo**
Description of the issue/feature this PR addresses:
Issue: https://www.odoo.com/web#id=814222&view_type=form&model=project.issue&action=963&active_id=681&menu_id=4720

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Hello @alexkuhn @ged-odoo 

Could you have a quick look at those fixes ? Indeed we have several tasks blocked since several features related to discuss are broken in saas 11.2 . Many thanks !

**Comment by alexkuhn** [comment]
@tde-banana-odoo 

Those fixes are correct, but since discuss is now testable, we should write some tests.
I am currently writing these tests, as they are none for the moment.

**Comment by tde-banana-odoo** [comment]
Please merge the fixes if those are correct and write tests afterwards.

**Comment by alexkuhn** [comment]
Merged: https://github.com/odoo/odoo/commit/a0a6811ff9efef9e4fc46a5e84ddc71db2a68b1c

**Pull request closed without merging**
