### PR TITLE
[ADD] payment_stripe_sca: Stripe API changes following PSD2

### PR DESCRIPTION
**Pull request by nim-odoo**
With the PSD2 directive coming into effect on September 14th,
was had no choice but to switch our Stripe integration to use
newer APIs that support Strong Customer Authentication (SCA for short).

This meant switching from the old stripe.js implementation for
'redirection' flow to the Stripe Checkout API and from the
Charge API to the newer SetupIntent & PaymentIntent APIs
for s2s flows.

This new modules introduce these changes in a non-intrusive way,
this means that installing this module is *not* required for
all customers (e.g. instances only accepting payment to and
from countries that are not part of the EU), that installing it
will support SCA flows and that uninstallation leaves you with
a working instance as well.

Note that for the case were the payment uses a token that requires
authentication in the frontend, new routes had to be added to allow
starting the transaction processing in the backend but finishing it in
the frontend.

Task 2039100

### CODE REVIEW

**Comment by nim-odoo** [comment]
Forward-port of #35848

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by wpichler** [comment]
Any plans when this will be ready for odoo v10 ?

**Comment by KangOl** [comment]
@robodoo rebase-merge

**Pull request closed without merging**
