### PR TITLE
[FIX] l10n_uy: We have adapted the demo data module to enhance data privacy.

### PR DESCRIPTION
**Pull request by mem-adhoc**
Ticket: 1239
Adhoc-task: 41734

Description of the issue/feature this PR addresses:
This task was created to modify the demo data for Uruguay, to avoid using real partner information.
Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by antoine162 — APPROVED** [review]
Sure, makes sense :+1: 
@robodoo r+

**Review by antoine162 — CHANGES_REQUESTED** [review]
Uhh, actually, can you please correct your commit message?

It says `l10n_ar` on there.

Also, `[ADD]` should only be used for new modules. Use `[FIX]` instead, please.

Thanks!

@robodoo r-

**Comment by mem-adhoc** [comment]
Hi @fvz-odoo!
Here are the changes for the Uruguayan data demo!

thanks @antoine162 for your review!
Greetings!

**Review by antoine162 — APPROVED** [review]
@robodoo r+

**Comment by antoine162** [comment]
@mem-adhoc Looks like there is an issue loading the new data.

**Comment by fvz-odoo** [comment]
Hello @mem-adhoc 

Yeah I actually checked and this is the error I think 

Screenshot 2024-08-20 at 9 44 37 AM

Actually I tried to use it for to create a company in Uruware and it also gave me an error, can you confirm it is the correct RUT we're using?

Let us know.

Cheers!

Fernando

@zaoral @ren-odoo

**Comment by mem-adhoc** [comment]
Hi @fvz-odoo!
Fer, I made a little change, can you test it?

**Comment by fvz-odoo** [comment]
Hello @mem-adhoc 

Thanks for the changes! Just to be sure, these contacts are fake correct? If yes, it now LGTM. This is ready @antoine162, let us know if anything (all checks passed, by the way).

Cheers!

Fernando

@zaoral @ren-odoo

**Review by antoine162 — APPROVED** [review]
LGTM :+1: 
@robodoo r+

**Pull request closed without merging**
