### PR TITLE
WIP: formatted code with black

### PR DESCRIPTION
**Pull request by ovnicraft**
applied to odoo core module

Formatted code for core module 

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@ovnicraft, thanks for these changes, but I doubt this kind of massive refactoring over all code should be ever merged, as it implies a great risk with not too much added value. You only have to see the runbot result that is not correct.

Sometimes, we see others' code that doesn't fit our style or it's even a bit ugly, but we have to focus and follow the principle that "if it's not broken, don't fix it". If you touch a method, class, model for other thing, then you can consider to refactor it, but it's not the case.

I don't close this any way to let Odoo people to decide.

**Comment by Yenthe666** [comment]
Agreed, risk benefit profit doesn't look like it is worth it to me. I'm sure @mart-e can make the final (official) call.

**Comment by Elkasitu** [comment]
I concur with @pedrobaeza, furthermore runbot is red.

The best anyone can do is try to be as close to PEP8 compliance and common sense as possible for every submitted patch, while staying within the scope of the modified/added code.

**Comment by ovnicraft** [comment]
Thanks for all comments, i created this PR to see results after reformatted code (thats why i marked as WIP).

Absolutely agree, mass refactor put at risk and break things.

**Pull request closed without merging**
