### PR TITLE
[IMP] *: fine-tune app icons 

### PR DESCRIPTION
**Pull request by Brieuc-brd**
### 1. Flat colors
The aim of this PR is to improve the impact and rendering of app
icons in bright and dark mode. It also reduces the size of svg files.

To achieve that, this commit updates the colors to flat colors. This
change will make the icons stand out and improve their readability.

### 2. Fix dropdown dashboard icon
Prior to this PR the Knowledge icon from the same dropdown was turned into an inline-svg
but the dashboard one was not.

This PR aims to use an inline-svg for that icon and ensure it renders
correctly.

--- 
**Requires :**
- https://github.com/odoo/enterprise/pull/48064

Other icons that should be merged after :
- [16.4] Shop Floor : https://github.com/odoo/enterprise/pull/48071
- [16.4] WhatsApp : https://github.com/odoo/enterprise/pull/48082
- [16.3] pos_restaurant : https://github.com/odoo/odoo/pull/137976
- [16.3] payment methods icons : https://github.com/odoo/odoo/pull/137235
and https://github.com/odoo/enterprise/pull/48212

task-3072562

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hey @odoo/rd-design 👋 
Could you take a look at this ? Thanks !

**Comment by Brieuc-brd** [comment]
@stefanorigano branch updated 👍

**Comment by stefanorigano** [comment]
Hello @Brieuc-brd , thanks.
You should update the PR's description according to 87de73416a5c678fbb96cbaf424a8097595336f9 😉
Checking the rest 👀....

**Review by stefanorigano — APPROVED** [review]
Thanks @Brieuc-brd 👍 

Hello @pparidans, could you have a look and eventually merge? Thanks!

**Review by pparidans — APPROVED** [review]
LGTM :+1: 

Even though some changes are not that visible at first glance, I love the tweaks here and there like avoiding transparency in the middle of an icon (cf. contacts) which will make it more legible in dark mode (at least) or the simplification in some SVG.

@robodoo rebase-ff r+

**Pull request closed without merging**
