### PR TITLE
Automatic subqueries

### PR DESCRIPTION
**Pull request by rco-odoo**
Introduce a lazy sequence of record ids that is determined by an SQL query. The query is executed when the sequence is accessed for the first time. Such a lazy sequence may be used inside domains, and automatically generate subqueries instead of tuples.

The method `_search` has been modified to return a lazy sequence by default (it may return a tuple instead). When evaluating domains like `[('X.Y.Z', op, val)]`, sub-searches are made with method `_search` instead of `search`, and their result is injected inside the domain. If the result is a lazy sequence, this automatically generates a sub-select in the final query.

One may generate subqueries by modifying code like
```python
    partners = partners.search(domain)
    records = model.search([('partner_id', 'in', partners.ids)])
```
to
```python
    partner_ids = partners._search(domain)
    records = model.search([('partner_id', 'in', partner_ids)])
```

The behavior of method `search` has not changed at all: it performs the query to return the corresponding recordset.

### CODE REVIEW

**Comment by rvalyi** [comment]
annexing a remark from the Tryton fork creator on Twitter in case it may help: https://twitter.com/cedrickrier/status/887597395374166016

**Comment by rco-odoo** [comment]
@odony the branch is now retargetted to saas-17

**Comment by odony** [comment]
Some unsorted remarks for the record, after a surface review with @rco-odoo :
- I like this new iteration better, although it's still very magical, and will still cause unexpected surprises for developers. Might still be OK if it brings significant improvements in terms of speed (not just raw query numbers). To be confirmed.
- Also, as discussed, I'm not convinced we will get any measurable improvement in request handling speed by simply bundling all intermediary queries into lazy subqueries. I do not clearly see how PG can optimize those (i.e. there aren't any join conditions that allow criterions to filter a common set of matching rows)
- Note: this PR also does not optimize domains based on `name_search` resolutions (very common for interactive use), so it would mainly change the behavior for record rules and similar technical domains. Still, that could be a useful global optimization.
- Just did a quick mini-benchmark with @rco-odoo on the odoo.com database (1M partners, 800K users, 550K move lines), running on saas-16 *with* and *without* this PR applied. The confirmation of a 10-line invoice took on average **2.05s** on saas-16 (bbc009597401f155d475769b62dfa99d7b9c970c), and **2.50s** with this patch applied. This gives a counter-intuitive performance *hit* of about 20-25%. We would have expected a small gain, or no change. This still need to be verified and analyzed.

**Comment by rco-odoo** [comment]
Resurrected in #52403.

**Pull request closed without merging**
