### PR TITLE
[FIX] website_sale: Remove pricelist on Sitemap.XML

### PR DESCRIPTION
**Pull request by cristinamartinrod**
**Description of the issue/feature this PR addresses:**
The sitemap shows the pricelist url's

**Current behavior before PR:**
if you create a sales rate, this is shown on the sitemap, so it is tracked and positioned by search engines.

**Desired behavior after PR is merged:**
Remove pricelist url's from the sitemap

 cc @Tecnativa

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@JKE-be can you take a look on this?

**Comment by JKE-be** [comment]
LGTM but CLA is wrong :/

Thx for the patch btw.

**Comment by pedrobaeza** [comment]
OK, thanks for the quick check.

I'll fix the CLA part. Has @mart-e come back from holidays or who is handling this now?

**Comment by JKE-be** [comment]
make the pr with 2 commit,s one for cla, and one for feature and I will merge it ;)

**Comment by pedrobaeza** [comment]
Hi, @JKE-be done the CLA stuff!

**Comment by JKE-be** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
