### PR TITLE
[FIX] event: fix spelling mistake

### PR DESCRIPTION
**Pull request by fbarbe00**
Purpose
=======
Fix "Intructions" to "Instructions"

Task-2657588

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Hello,

Actually we don't update po files, only pot. Globally, we update pot files and those are used as template to translate strings. No need to update specific po files as they will be erased by new translations. So keep only the change in ``.pot`` file concerning translations.

Could you also add a link to the task ? Even if not really critical, always a good idea to link the source of a change. We give the task ID in odoo, here ``task-2657588`` (using the task-XYZ formatting to avoid git automatically linking an ID to an existing commit hash).

Thanks !

**Comment by fbarbe00** [comment]
Done, and changed target branch to 15.0

**Comment by tde-banana-odoo** [comment]
Thanks for updating !

@robodoo r+

**Comment by mart-e** [comment]
Hi there !

FYI, this introduced a duplicated source terms in the .pot which break the ~~universe~~ Transifex

**Comment by tde-banana-odoo** [comment]
Please fix transifex.

**Pull request closed without merging**
