### PR TITLE
[IMP] POS-Change in model.js for pos ticket

### PR DESCRIPTION
**Pull request by luistriana28**
Modifying the model.js you can call new fields for the POS report

### CODE REVIEW

**Comment by jorenvo** [comment]
Hi,

How are you planning on modifying the POS receipts?

**Comment by xluiisx** [comment]
Hi, 
This improvement is because in Mexico all the point of sale receipts must show the full company address.

**Comment by jorenvo** [comment]
Okay, but you're going to have to modify the source code locally to actually put those fields on the receipt right? I don't think there's another way to do it. If you're going to modify the source code anyway, can you not make this change locally as well?

**Comment by jorenvo** [comment]
By the way, if you're writing a small module for this (might be the cleanest solution). You can add the fields like this:

```javascript
var models = require('point_of_sale.models');
...
models.load_fields("res.company", "street");
models.load_fields("res.company", "street2");
...
```

**Comment by xluiisx** [comment]
Thank you very much for your answer, I will test it.

**Comment by jorenvo** [comment]
Alright, no problem. I'll close this PR for now.

**Pull request closed without merging**
