### PR TITLE
[IMP] sale: allow override sale_order_discount product

### PR DESCRIPTION
**Pull request by JKE-be**
Add method '_get_discount_product' to allow to override the product used by the sale_order_discount wizard.

### CODE REVIEW

**Comment by Feyensv** [comment]
Why ? Which use case do you need that hook for ? :thinking:

**Comment by JKE-be** [comment]
In case of subscription, we would like to use another product/recurring discount e.g.

So be able to override this helper to have distinct discount depending of the plan on our plan.

**Comment by Feyensv** [comment]
Ok then, lgtm :ok_hand:

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo retry

**Pull request closed without merging**
