### PR TITLE
[FIX] mail: impossible to update image of user on large database

### PR DESCRIPTION
**Pull request by fmdl**
Backport of https://github.com/odoo/odoo/pull/70436

@Yenthe666 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@xmo-odoo :)

**Comment by Yenthe666** [comment]
Why close?

**Comment by fmdl** [comment]
Because it is not merge ...

**Comment by Yenthe666** [comment]
Make an OPW or ping @xmo-odoo again 😄

**Comment by tde-banana-odoo** [comment]
Note that you have 2 commits, could be rebased accordingly.

**Comment by fmdl** [comment]
@tde-banana-odoo I have made 1 commit and rebase.

**Comment by tde-banana-odoo** [comment]
Could you update a bit commit message, notably adding link to commit you backport ? Don't hesitate to be a bit verbose sometimes :D .

Cheers,

**Comment by fmdl** [comment]
Message updated.

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
Thanks a lot @tde-banana-odoo ❤️

**Comment by tde-banana-odoo** [comment]
Well that was just a backport ^^ just had to ensure depends was effectively working in 13 (turns out it was introduced with "new" compute fields in 13, time flies).

**Pull request closed without merging**
