### PR TITLE
CLA Eska

### PR DESCRIPTION
**Pull request by levkar**
CLA for Eska Yazılım ve Danışmanlık A.Ş.

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you to sign the CLA but your commits are made with a @mektup.at email address so the CLA check still fails for your commits.
Could you either update your CLA either change the email you are using on git ?

**Comment by levkar** [comment]
I added my company e-mail and verified it. Thanks.

**Comment by beledouxdenis** [comment]
- This CLA commit is still done as Levent Karakas <levent@mektup.at>, while you signed the CLA as Levent Karakaş leventk@eskayazilim.com.tr 
- I believe "and Camptocamp SaS" is wrong (copy/paste error, probably)

**Comment by levkar** [comment]
I fixed the copy paste error and commited again. I hope the commit is with the updated e-mail. Otherwise I will create a new branch/pullr request...

Thanks for your patience

**Comment by mart-e** [comment]
The email used by your user was still not correct but I amended the commit to change it.
Merged at b2a23ee94adee121a9072d5e9f82ba3764be7338
However, for your future pull request, double check that you are committing with the @eskayazilim.com.tr email.

**Pull request closed without merging**
