### PR TITLE
[14.0][I18N] stock: Incorrect POT

### PR DESCRIPTION
**Pull request by pedrobaeza**
It seems manually edited in 9500dc0c72a390ebe21bb8db704674e70107ddd5

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@mart-e

**Comment by mart-e** [comment]
@sami-odoo @ticodoo how was generated the .pot file?

**Comment by ticodoo** [comment]
Hello @pedrobaeza @mart-e I also originally though it was a mistake to duplicate the file name, but when you export the .pot file via the standard flow of: Settings > Translations > Export Translation, it does indeed duplicate it in the export. There are also several other strings in different pot files that have `code: {filename} code: {filename}` where filename is the same filename :thinking:

**Comment by pedrobaeza** [comment]
And have you checked if the translation is still working with the comment duplicated?

**Comment by ticodoo** [comment]
In v16, the duplication exists for "Warning!" (an onchange warning title used twice) https://github.com/odoo/odoo/blob/92c232cca15517bd9a33a5100e7cdc42c3c25397/addons/stock/i18n/stock.pot#L9007-L9012

and it looks like it is correctly translating:
1st warning:
FR
image
SP
image

2nd warning
FR
image
SP
image

**Comment by pedrobaeza** [comment]
@ticodoo thanks for the test. Great that in v16 the duplication is not a problem, except aesthetics.

In v14, the translation engine is different, so it's worth to also check if it's working correctly.

I let @mart-e and others in charge of translations (@HydrionBurst?) to value if the aesthetics thing should be fixed.

**Comment by HydrionBurst** [comment]
`: code:addons/stock/models/product.py:0 code:addons/stock/models/product.py:0`
is becasue the code translation appears twice in different lines of the same file. The translation exporter ignores the line, so they become the same.
I think we don't need to fix it because it does't help the business, because code translation is not for one file or one line
1. before 16.0 the code translation is shared by all modules
2. after 16.0 the code translation is used for specific module
`: code:addons/stock/models/product.py:0 code:addons/stock/models/product.py:0` is just a reference and we never use it when import

**Comment by pedrobaeza** [comment]
OK, but my initial issue was for 14.0, so this double appearance is not a problem there? I detected reviewing the es.po files after Transifex sync, which I use to do every Sunday/Monday, because it was the first time I see it. If you confirm it's not a problem, then let's close this.

**Comment by HydrionBurst** [comment]
I think it won't cause any unexpected behavior in 14.0

**Comment by ticodoo** [comment]
@pedrobaeza looks like it's ok in v14:

https://github.com/odoo/odoo/blob/38ba033c319f8b55d4a744f152e2d9acb35396d5/addons/mrp/i18n/mrp.pot#L2729-L2735

image

image

So we may as well leave it as is to avoid unnecessary changes when the .pot files are re-exported (since the filename will eventually be duplicated no matter what)

**Comment by pedrobaeza** [comment]
Thanks for the confirmation, Tiffany and Chong, and sorry for the noise.

**Comment by ticodoo** [comment]
> Thanks for the confirmation, Tiffany and Chong, and sorry for the noise.

no worries, I was wondering about it too :smiley:

**Pull request closed without merging**
