### PR TITLE
[FIX] auth_oauth: fix KeyError 'interactive'

### PR DESCRIPTION
**Pull request by haumenphai**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by haumenphai** [comment]
@trinhanhngoc

**Comment by mart-e** [comment]
Hi,

Could you detail how to reproduce your issue? A traceback?
It would probably be better to fix at the root cause.

**Comment by haumenphai** [comment]
@mart-e this is traceback:
```
 File "/opt/odoo/14.0/addons/website/models/res_users.py", line 76, in authenticate
    uid = super(ResUsers, cls).authenticate(db, login, password, user_agent_env)
  File "/opt/odoo/14.0/odoo/addons/base/models/res_users.py", line 714, in authenticate
    uid = cls._login(db, login, password, user_agent_env=user_agent_env)
  File "/opt/odoo/14.0/odoo/addons/base/models/res_users.py", line 689, in _login
    user._check_credentials(password, user_agent_env)
  File "/opt/odoo/14.0/addons/website_sale_wishlist/models/res_users.py", line 10, in _check_credentials
    result = super(ResUsers, self)._check_credentials(password, env)
  File "/opt/odoo/14.0/addons/auth_oauth/models/res_users.py", line 116, in _check_credentials
    passwd_allowed = env['interactive'] or not self.env.user._rpc_api_keys_only()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/14.0/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/14.0/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'interactive'
```

**Comment by mart-e** [comment]
Thank you but could you explain your login process?
The `interactive` flag is set here so it should not fail
https://github.com/odoo/odoo/blob/2b4e4e1f099b8aa9efab3786810df78d7a401693/odoo/http.py#L999
I have just tested making a login with oauth and it worked fine.

**Comment by haumenphai** [comment]
@mart-e I use my login process and I reuse login process of Odoo. 
I get an error in the `_check_credentials` method. I think it's better to use `get()` method there.

**Comment by mart-e** [comment]
But does it work when you use the login interface ? That is what really matter.

**Pull request closed without merging**
