### PR TITLE
[FIX] doc: correct link for runbot

### PR DESCRIPTION
**Pull request by sswapnesh**
Correct URL for Runbot

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
@mart-e  I think It is broken since last Runbot Upgrades.
Not sure if this needs to be fixed from v13.

**Comment by mart-e** [comment]
@sswapnesh the runbot URL has changed since the last update. You can start from the 12.0 to change all versions

**Comment by sswapnesh** [comment]
@mart-e  Updated

**Comment by mart-e** [comment]
Thanks !
@robodoo r+

**Pull request closed without merging**
