### PR TITLE
Master base restrict export rights mpa

### PR DESCRIPTION
**Pull request by mitali-willdooit**
Purpose this task is to restrict export rights for a malicious user
Task-2170900

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by msh-odoo** [comment]
@xmo-odoo Goal was to not do explicit rpc call to just check whether user has export rights as it is going to call on each listview? so we tried to make same as we add create="0/1" delete="0/1" in view processing itself.

**Comment by xmo-odoo** [comment]
> @xmo-odoo Goal was to not do explicit rpc call to just check whether user has export rights as it is going to call on each listview? so we tried to make same as we add create="0/1" delete="0/1" in view processing itself.

That seems debatable, but in that case why half-ass it, why not actually replicate the behaviour of the ACL flags? Also might be a good opportunity to check for better API with the web client (e.g. return an ACL map as part of load_views or something).

And that only answers the first half of the comment.

**Comment by mpa-odoo** [comment]
> * the attribute seems completely useless, unless there's a strong and specific use case for explicitly setting it in the view, which the specification doesn't provide even less so as the implementation ignores any possibility of the attribute being manually set and always overwrites it
> * therefore the list view should be checking groups (client-side)
> * and that group should also be used to allow or remove access to the export object / wizard
> * as well as gate the core ORM export method(s)

Changes are done. Thanks

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
