### PR TITLE
[FIX] hr_holidays: apply timezone to leave statistics

### PR DESCRIPTION
**Pull request by thle-odoo**
Context:
    In some companies, we want to give employees a day off.
    Unfortunately, their working hours do not correspond to those of the company.
    To remedy this, we set the work hours at: 00:00 until 23:59.

Steps to reproduce:
    - set work hours to 00:00 until 23h59;
    - give one day off to a department;
    - view statistics on a employee (who belongs to the department).

Issue:
    We notice that in the statistics, the dates are wrong.
   Indeed, it is indicated that the leave is over two days.

Cause:
    When we receive the dates via the rpc call to display them, they are character strings.
    The browser interprets them with the computer's timezone (even if it is UTC).
    The hours of work being at the limit of the day, we overflow on a second day.

Solution:
    As we know that the timezone used to store dates in the database is UTC, we can calculate an offset and apply it before displaying the result.
    This can be achieved with `fieldUtils.parse.datetime`.

opw-3063177

### CODE REVIEW

**Comment by thle-odoo** [comment]
Is there a more elegant solution with a library ?

**Review by nle-odoo — APPROVED** [review]
looks good to me

as we discussed, we should probably rather use `session.getTZOffset` or directly `fieldUtils.parse.datetime`

**Comment by kba-odoo** [comment]
@thle-odoo unfortunately one test doesn't pass with your change: https://runbot.odoo.com/runbot/build/21657691

**Comment by thle-odoo** [comment]
Remark: I modified the test because the UTC format still has four digits for year, two digits for month and two digit for day.

**Comment by kba-odoo** [comment]
robodoo r+

**Pull request closed without merging**
