### PR TITLE
[FIX] account

### PR DESCRIPTION
**Pull request by nim-odoo**
opw-743628

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
will land in master in https://github.com/odoo/odoo/pull/17290

**Comment by guanhuan** [comment]
Hi @nim-odoo,

Thanks for fixing this. I am just wondering the reason of the closure of this PR.

Is Odoo 9 end of life? What's the general policy of bug fixing for older versions?

Thanks

**Comment by nim-odoo** [comment]
Hello,

The reason is that it introduces a change in behavior.

**Comment by guanhuan** [comment]
@nim-odoo 
I don't have a complete view of how Odoo analytics is designed to work, sorry if any question below has an obvious answer.

Is there any other way you the partner info for analytic entry can be filled in automatically when you post them? Unless there is any reason the partner for analytic entry should be different from the journal entry, it seems a be difficult to people to have to edit all analytic entries and put in partner info manually?

**Pull request closed without merging**
