### PR TITLE
[FIX] website_sale: Update the delivery amount in the order's summary when changing the shipping method

### PR DESCRIPTION
**Pull request by mamatch**
Steps:
- Create and publish two shipping methods with different amount
- Go to the /shop, add a product to cart and go to checkout
- There will two delivery methods with one selected by default
- Select the other one

Issue:
The delivery amount on order summary is not updated.

Cause:
The feature works well on version 16.1 and was in the website_sale_delivery. On saas-16.2 website_sale_delivery was merged in website_sale so some features may have been missed.

opw-3297239

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — COMMENTED** [review]
unless I'm missing something, the route that is added is already present in this module:

https://github.com/odoo/odoo/blob/174cbf6fb7de2e6a32f125d84e98305f14785561/addons/website_sale/controllers/delivery.py#L15-L16

so I think the route that exist should be fixed if there is something that doesn't work with it, but we should not add a new one

**Comment by vava-odoo** [comment]
Hi @mamatch 
I just tested the flow, following the steps to reproduce, and everything looks fine.
Could you provide more information or investigate further?
FYI: there was a recent fix in `website_sale_loyalty` that fixed the override of these methods: https://github.com/odoo/odoo/commit/460f90a59218202c1f77405609fadfc2640b2f9c
Maybe related to your bug?
Thanks

**Comment by mamatch** [comment]
Hi @vava-odoo , I've tested again of a 16.2 runbot and it doesn't work. There is no additional configuration I think. Here is a video: https://drive.google.com/file/d/1rvOexjzwavz3zy5gNa_utJiwZdmfM3XP/view?usp=share_link 

After investigating the network it seems that the ```.o_delivery_carrier_select``` doesn't send the call to /shop/update_carrier route. I'm looking into it.

Thanks for the follow-up :)

**Comment by mamatch** [comment]
Hi @vava-odoo @nle-odoo, I've notice something else about the issue. When get in the checkout page everything works fine but after a period of inactivity on the page( Don't know exactly but maybe 3min), it doesn't work anymore. You have the video: https://drive.google.com/file/d/1PQS2mBsNAtoOL2IWEsb5gcVvvwL5wtHW/view?usp=share_link

On the network side and after the period of inactivity there is no more request sent.

After 1:10, you can go straight to 4:45

**Comment by nle-odoo** [comment]
I can't reproduce either on runbot 16.2

I've tested also waiting some time, and no issue either. It should probably be debuggable if the request are not sent (checking why they are not sent, and if we go inside the code, or if there has been an error before that prevent the sending of further requests).

**Comment by mamatch** [comment]
Solved

**Pull request closed without merging**
