### PR TITLE
[WIP] stock, sale_stock: inverse control flow of decreasing quantity

### PR DESCRIPTION
**Pull request by amoyaux**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi there,

Nice to see this, don't forget we have the same behavior to fix in PO as well to be consistent ;)

Cheers,

Joël

**Comment by amoyaux** [comment]
Hi @jgrandguillaume It will probably remain an activity in a first time for RFQ and MO

**Comment by jjscarafia** [comment]
Just in case it helps.
We've a simple approach for this functionality.
We block decreasing and we add a button (when there is remaining quantity to be delivered/received) to "cancel remaining". With that button we have:
* better control of the flow (is not a change on a field)
* a confirm message

I haven't check the functionality, but I just share it in case it helps. We've been using this since v9 and it's working great since then.

sales: https://github.com/ingadhoc/sale/blob/13.0/sale_stock_ux/views/sale_order_views.xml#L22
purchases: https://github.com/ingadhoc/purchase/blob/13.0/purchase_stock_ux/views/purchase_order_views.xml#L19

**Comment by wtaferner** [comment]
@amoyaux 
Still a WIP? sooo sad that this won't happen in 15.0 or is it?

**Comment by amoyaux** [comment]
It will, however I won't add the part on removing the links between so lines and stock.move. Adding a negative line on the SO will just create a return and not decrease a stock.move with the same product (however decrease an existing line will). I'm working on another branch and I'm just cleaning the MO/PO activities/messages (+ decrease RFQ if possible)

**Comment by wtaferner** [comment]
Cool, if you can link the other PR as soon as available I would be grateful to actually see the improvement in the upcoming release 😉

**Comment by wtaferner** [comment]
@amoyaux 
Any progress in this direction? This is hard for a lot of users to handle, so it would great to have a consistent and reliable system in place as soon as possible.

**Comment by amoyaux** [comment]
@wtaferner There is already a lighter version of it in master

**Comment by C3POdoo** [comment]
Dear @amoyaux,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
