### PR TITLE
[FIX][8.0]Allow override copy on survey.user_input and survey_user_input_…

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
…line

As noticed into #7983

cc @rim-odoo

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
@rim-odoo do you think it could be ok with this?

**Comment by mart-e** [comment]
Hello,

Sorry but I am not in favour of such context hack. As said Richard, it's a hidden behaviour.
Either we remove the restriction fully (with some clean `copy=False` where needed) or we prevent the copy completely (as for now), but not a mix a both with something in the context.

**Comment by rim-odoo** [comment]
+1 @mart-e I'd rather not change anything.

**Comment by JonathanNEMRY** [comment]
Hello @mart-e 
What do you mean by some clean `copy`? As I explained into #7983 what I want is to make a copy of `survey.user_input`. For the moment it is not possible because of this restriction with the `raise exception` into the `copy_data`. It will be great to have a `_copy` on the model because  this flag could be `false` into your native code but easily overridable into other modules (but this flag does not exist on a model level, only on field level that has no interest on my case) --> that's why I propose it with the context, quick fix and efficient. @rim-odoo when you said that you'd rather not change anything; but this is a very bloking situation because we have no others solution to copy this model. (and I already explain you why I have to copy it). Moreover when you don't allow user to create a new `record` you don't override `create` of `orm` to set a `raise` into. So to keep consitency, we shouldn't block this feature into the code but definitively find an other proper solution. (removing this override should be the solution as there are no others forbidden override of `copy_data` in the all-entire addons of odoo...)

**Comment by JonathanNEMRY** [comment]
Close via #8009

**Pull request closed without merging**
