### PR TITLE
[FIX] stock_picking_batch: wrong sanity check on picking creation.

### PR DESCRIPTION
**Pull request by Feyensv**
Wrong use of self.batch_id in an api.model method.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@svs-odoo The sanity check on pickings creation was wrongly checking the `batch_id` on `self` when self was supposed empty.
As the fix breaks the demo data, could you please take a look (and fix/remove the demo data if possible) ?  Thanks !

**Comment by svs-odoo** [comment]
> @svs-odoo The sanity check on pickings creation was wrongly checking the `batch_id` on `self` when self was supposed empty.
> As the fix breaks the demo data, could you please take a look (and fix/remove the demo data if possible) ? Thanks !

Hello @Feyensv , it's done. Can I push the commit directly on your branch here ?

**Comment by Feyensv** [comment]
Yes :+1:
You can even squash the commits :).

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
