### PR TITLE
[FIX] project_timesheet_holidays: remove timesheets when time off is canceled

### PR DESCRIPTION
**Pull request by xavierbol**
Before this commit, when the user cancels his validated time off planned
in the future, the timesheets generated for this time off are not
deleted. The problem is since the timesheets are not removed we could
have duplicated timesheets if the user adds a new time off in the same days
for instance, because the newest timesheets are generated and thus we have
duplicated timesheets generated instead of having only timesheets generated
for the newest time off.

This commit removes the timesheets generated for the time off when this
time off is canceled (=archived). Also, if the user unarchives the time
off then the timehseets will be regenerated for this time off.

Related PR: #76722

Part of task-2791386

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Williambraecky** [comment]
Hello 👋 

I would also add this change:
```diff
diff --git a/addons/hr_holidays/models/hr_leave.py b/addons/hr_holidays/models/hr_leave.py
index 8a39ac48e14..897b0d3182a 100644
--- a/addons/hr_holidays/models/hr_leave.py
+++ b/addons/hr_holidays/models/hr_leave.py
@@ -964,8 +964,8 @@ class HolidaysRequest(models.Model):
         return holidays
 
     def write(self, values):
-        if 'active' in values and not values['active'] and not self.env.context.get('from_cancel_wizard'):
-            raise UserError(_("You can't manually archive a time off."))
+        if 'active' in values and not self.env.context.get('from_cancel_wizard'):
+            raise UserError(_("You can't manually archive/unarchive a time off."))
 
         is_officer = self.env.user.has_group('hr_holidays.group_hr_holidays_user') or self.env.is_superuser()
         if not is_officer and values.keys() - {'supported_attachment_ids', 'message_main_attachment_id'}:
```

I am not sure whether being able to unarchive was meant to be possible, however I am quite sure it introduced a lot of problems that we did not realise yet. (c.f. recent bug report)
At least until we find a proper solution in master.

@kba-odoo pong 🐻

**Comment by tivisse** [comment]
@xavierbol Thanks for the fix. LGTM. 

And indeed, @Williambraecky 's comment makes sense ! 

Have a nice day.

**Review by IT-Ideas — COMMENTED** [review]
Thanks for the fix 🙂 LGTM

**Comment by kba-odoo** [comment]
LGTM too! and I side with @Williambraecky's comment too :-)

**Comment by xavierbol** [comment]
Thanks everyone for the review, I will apply the @Williambraecky's comment. 🙂

**Comment by xavierbol** [comment]
I applied the @Williambraecky's suggestion and also added some unit tests in `hr_holidays` module. I hope it will be good for you. 🙂 🤞🏽 

Have a nice day too!

**Comment by kba-odoo** [comment]
robodoo r+

Thanks @xavierbol !

**Pull request closed without merging**
