### PR TITLE
Server side form view (test support)

### PR DESCRIPTION
**Pull request by xmo-odoo**
Adds a Form view object intended to be used in test, which *should* (barring bugs) properly:

* perform default_get and subsequent onchanges when creating a new record
* properly call onchanges when altering fields
* reject changes to readonly fields
* not save unchanged & readonly fields
* require view-required fields
* correctly handle modifiers
* support o2m fields including `*_view_ref` hooks
* should correctly handle the "edition reference" (editable list v form)

M2M support limited to adding & removing (pre-existing) records, I think the developer can just use a separate Form if they want to create/edit those via specific views?

TODO: nice docstring?

Unresoved questions:

* should `invisible` modifiers have an effect? Possibly a variant of readonly (can't edit but properly sent to the server)?
* should buttons be supported directly via the form view? Unclear how they'd be invoked since the button name can be e.g. an action id.

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@sts-odoo could be of interest

**Comment by xmo-odoo** [comment]
ping @odony can that be merged in 11 or is it necessarily for master

**Comment by nhomar** [comment]
11.0 PLEASE! ;-)

**Comment by xmo-odoo** [comment]
@nhomar sorry mate, the hammer has come down, this will be for master (i'll create a new correctly-named branch so I'm closing this PR)

**Comment by Yenthe666** [comment]
To be honest, it is a good call that this lands in master. It introduces new features and the rule of thumb is that this lands in the upcoming version. Good call.

**Pull request closed without merging**
