### PR TITLE
[FIX] website_event: Top menu on top events menu

### PR DESCRIPTION
**Pull request by nboulif**
Top menu on top events menu (especially Anelusia Theme).

opw-2326144

### CODE REVIEW

**Comment by nboulif** [comment]
@odoo/rd-website can you review please? Thank you

**Comment by nboulif** [comment]
ping @odoo/rd-website

**Review by qsm-odoo — COMMENTED** [review]
Seems really strange, I can't think of a case where `display: inherit;` would make sense... and as it is strange the commit message should really explain the issue and why this fixes it. Could you explain? Thanks.

**Comment by nboulif** [comment]
Sorry for the half work :sweat_smile:  I will update the commit after your confirmation :wink: 

I could also use `display: block` ( I used `display: inherit` since the parent already have `block`), who make the block start at a new line instead of on top the main menu.
I'm not so good in css, do you have any advice on it?

**Comment by qsm-odoo** [comment]
Well, `display: block` would probably be more explicit than `inherit` but I don't think this is a good solution, the problem seems related the 80px margin-top which is put on first ::before element in #wrap to compensate the menu size... but as this menu size may vary this seems bad as well (and unstable anyway, this bug is the proof). There is nothing wrong with this website_event code so you should not modify it to solve an external bug :wink:  The fix should be done in Anelusia to compensate for the menu size a different way, with a more robust css rule... maybe a border-top on the wrap element? :|

**Pull request closed without merging**
