### PR TITLE
[FIX] website, website_payment: correctly add frontend template

### PR DESCRIPTION
**Pull request by detrouxdev**
Commit [1] changed the way QWeb templates are loaded for public widgets, removing the xmlDependencies attribute.

Most of the public widgets' templates were therefore defined in assets_wysiwyg. This is wrong however, as those assets are only loaded in specific situations.

This commit removes the templates definitions from the assets_wysiwyg into specific records defined alongside the snippet templates.

Steps to reproduce:
- Drop the "Image Wall" snippet
- Save
- Visit as a public user (logged out)
- Click on an image from the image wall
- TB

[1]: https://github.com/odoo/odoo/commit/f05adbc8b59c67cbec4847687a1ee07e620c2a7a

task-2984724

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by detrouxdev** [comment]
@rdeodoo 👋🏻  Might I have a quick review please? 🙏🏻

**Review by rdeodoo — APPROVED** [review]
@robodoo r+

**Comment by rdeodoo** [comment]
Runbot doc is red

**Comment by detrouxdev** [comment]
@rdeodoo It's green again! 😄

**Comment by rdeodoo** [comment]
@robodoo r+

**Pull request closed without merging**
