### PR TITLE
[ADD] web_editor: Add ability to set custom background for snippet

### PR DESCRIPTION
**Pull request by kig-odoo**
https://www.odoo.com/web#id=1965847&action=333&active_id=974&model=project.task&view_type=form&menu_id=4720

### CODE REVIEW

**Comment by rdeodoo** [comment]
What's the status of this one? Any task?

**Comment by kig-odoo** [comment]
@rdeodoo Yes, there is a task for this one probably in the RD website project if I remember well. I've created this PR just after V12 release :smile: . When you guys in India I've discussed this feature with Sebastien and decide to create the task. When I was working at Odoo this task was blocked because we were waiting for the new editor.

**Comment by rdeodoo** [comment]
Indeed thank you, I found [the task](https://www.odoo.com/web#id=1965847&action=333&active_id=974&model=project.task&view_type=form&menu_id=4720). It was cancelled until @qsm-odoo refactoring of the customize is done.

Closing this one in the meantime. Might be reopened once the task is reborn.

**Comment by sbuhl** [comment]
Task cancelled for now
https://www.odoo.com/web#id=1965847&action=333&active_id=974&model=project.task&view_type=form&menu_id=4720

**Pull request closed without merging**
