### PR TITLE
[IMP] bus: add state property and statechange event

### PR DESCRIPTION
**Pull request by abichinger**
I would like to display a warning, if the websocket of the shared worker is disconnected,
but I have not found a straight forward way to get the state of the websocket.

Adding listeners for all emits (`connect`, `disconnect`, `reconnect`, `reconnecting`) is not sufficient, because If you open a second tab, no event may be sent at all.

If this PR is merged the state of the websocket can be accessed like this:
```js
let state = bus.state;
bus_service.addEventListener("statechange", ({detail: newState}) => {
  state = newState;
  if (state !== bus.CONNECTED) {
    console.warn("WebSocket is not connected")
  } 
});
```

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
The commit with the changes should be named `[IMP] bus: ....`

**Comment by tsm-odoo** [comment]
I don't think we should bloat the bus service API with such technical details, especially since they can easily be deduced from the application. For instance, you could store a boolean in local storage and retrieve it when the tab starts. This would reduce lines of code and keep the bus service/worker clean of this implementation detail. Additionally, note that some disconnections, such as 4002 (keep-alive close code, received periodically), are natural; these codes shouldn't trigger a notification. Your solution doesn't allow for fine-grained control, such as excluding certain close codes. In contrast, handling this as I suggested would.

**Comment by abichinger** [comment]
Using the local storage would also be an option. To be honest I have not thought about using the local storage for this.
Is that something we could add to the odoo codebase?

I think a service with the following interface would be practical
```ts
interface WebSocketStateService {
  isConnected(): boolean
  addConnectionListener(listener: (connected: boolean) => void): void
  removeConnectionListener(listener: (connected: boolean) => void): void
}
```

**Comment by tsm-odoo** [comment]
How are the two event listeners you're suggesting different from the `connect`/`disconnect` events? Most of the time, we don't care if the socket is connected. You start the bus by calling `busService.start` and use the `send` method to transmit data to the server. Whether the WebSocket is connected or not is irrelevant, as messages sent while the socket is down will be queued and delivered after reconnection anyway.

**Comment by tsm-odoo** [comment]
I agree that we could expose the state of the bus service, but not as the ready state of the WebSocket. Instead, it should match the format of the bus service events. There's no need for a dedicated service. Essentially, it's as simple as:
- Retrieving the initial state when initializing the connection to the worker.
- Keeping it up to date based on events received from the worker.

**Comment by abichinger** [comment]
> There's no need for a dedicated service

I agree. I suggested it, because you said "I don't think we should bloat the bus service API".

> Retrieving the initial state when initializing the connection to the worker.
> Keeping it up to date based on events received from the worker.
> Exposing it as part of the bus service API (e.g. "busService.state")

I like this approach. I'm going to adapt this PR.

It would also be nice to trigger an event (e.g. "state") on the bus everytime `busService.state` is changed. This way you only have to listen on one event instead of three (`connect`, `reconnect`, `disconnect`)

**Comment by tsm-odoo** [comment]
> I agree. I suggested it because you said, "I don't think we should bloat the bus service API."

The actual state seems reasonable to me. I didn't want something as technical as the WebSocket `readyState`, deferred states, and the road trip to the worker.

> It would also be nice to trigger an event (e.g., "state") on the bus every time `busService.state` changes. This way, you only have to listen to one event instead of three (`connect`, `reconnect`, `disconnect`).

Looks good, thank you! Also, don't forget to update `websocket.py@WebsocketConnectionHandler._version` for the new worker version to take over.

**Comment by tsm-odoo** [comment]
Actually, now that I think about it more, I'm not so fond of the "stateChange" event. If we keep the old lifecycle events, it will be redundant. If we don’t, each call site will have to check the new state, which is cumbersome. I’d prefer to stick with the "state" property in the bus service and keep the current lifecycle events.

For example, implementing your use case:
```js
// current lifecycle events
busService.addEventListener("connect", () => removeNotification());
busService.addEventListener("disconnect", () => displayNotification());

// with stateChange
busService.addEventListener("stateChanged", (newState) => {
    if (newState === "disconnected") {
        displayNotification();
    }
    if (newState === "connected") {
        removeNotification();
    }
});
```
It's just less straightforward and harder to read.

**Comment by abichinger** [comment]
I think even if there is no `stateChange` event, you would still need to check the `state` property at the initialization.

For example:
```javascript
function updateNotification(state) {
  if (state === "disconnected") {
        displayNotification();
    }
    if (state === "connected") {
        removeNotification();
    }
}

// initialize notification
updateNotification(bus.state);

// current lifecycle events
busService.addEventListener("connect", removeNotification);
busService.addEventListener("disconnect", displayNotification);

// with stateChange
busService.addEventListener("stateChanged", updateNotification);
```

In my use case I would use a reactive variable (e.g. `wsState`) to toggle the visibility of an element. The implementation would look similar to this:
```javascript
wsState = bus.state;
busService.addEventListener("stateChanged", (newState) => {
  wsState = newState
});
```
```html
<div t-if="wsState !== 'connected'">Websocket is disconnected</div>
```

At the end I think it comes down to personal preference, but you are right that the `stateChange` event would introduce some redundancy.

**Comment by abichinger** [comment]
I updated the PR. 
What should the next `WebsocketConnectionHandler._VERSION` be?

**Comment by abichinger** [comment]
> We'll likely merge this today so I'll close this PR. Thank you for your work!

Thanks! Your solution looks great!

> The bus service requests the initial state from the worker and then guesses the state. Instead, we should send the state from the worker anytime it changes. (Since events aren't captured, the state is not up to date within the life-cycle callbacks).

I hope I don't bother you but I would like to understand why my solution guesses the state? Shouldn't these [lines of code](https://github.com/odoo/odoo/pull/180822/files#diff-f3307c7432bfa87b1ab1ecbab1994e911c92abac66f8017dce61f4ded3998520) keep the bus state in sync with the worker state?

```javascript
bus.addEventListener("connect", updateState.bind(null, busStates.CONNECTED));
bus.addEventListener("reconnect", updateState.bind(null, busStates.CONNECTED));
bus.addEventListener("reconnecting", updateState.bind(null, busStates.CONNECTING));
bus.addEventListener("disconnect", updateState.bind(null, busStates.DISCONNECTED));
```

**Comment by tsm-odoo** [comment]
I apologize for the poorly chosen wording. My solution provides a single source of truth for the state. The worker knows best; when its state changes, it notifies its client instead of having to ask the worker initially then deduce the state from life-cycle events. Additionally, your solution does not guarantee that the state will be updated when the life-cycle callbacks are invoked. With the worker, you can send the state update before the life-cycle event, ensuring the state is current when invoking the callbacks. That't not a big deal but since there is a way for the worker to send the state directly, why not relying on it 100% :)

**Comment by abichinger** [comment]
Thank you for the detailed explanation, now I understand. 

> My solution provides a single source of truth

Putting the state inside the worker is a smart move :+1:

**Pull request closed without merging**
