### PR TITLE
[FIX] base: Navarre official name

### PR DESCRIPTION
**Pull request by acysos**
Description of the issue/feature this PR addresses: the official name of Navarra is not Nafarroa, is Navarra. Nafarroa is a co-official language. So Navarra has to be the first name, and Nafarroa the secondary.

Current behavior before PR: Nafarroa (Navarra)

Desired behavior after PR is merged: Navarra (Nafarroa)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This was discussed in #15166 and decided the homogeneous form for all. Do you have the BOE reference about what you assert?

**Comment by acysos** [comment]
Navarra is not Pais Vasco, this article only apply in Pais Vasco. There isn't any BOE article that change the name. Only exist the original article of 1982: https://www.boe.es/buscar/act.php?id=BOE-A-1982-20824

You can read that the Official Language is spanish and the euskera only in the zones that speak this language. Also if you read the article you can see that the full name is Comunidad Foral de Navarra, but it to large, so it's normal use Navarra (Nafarroa).

**Comment by pedrobaeza** [comment]
OK, thanks for the explanations.

**Comment by acysos** [comment]
This PR will be merge?

Thank you

**Comment by pedrobaeza** [comment]
@mart-e can you please review?

**Comment by mart-e** [comment]
@pedrobaeza I assigned myself on some of PR and issues lately to have work to do in Sevilla :wink:

**Comment by pedrobaeza** [comment]
Great, I will tell you about another also :angel:

**Comment by mart-e** [comment]
Thanks for the PR and explanations !

**Pull request merged**
