### PR TITLE
[IMP] mass_mailing,mass_mailing_themes: snippets adjustments

### PR DESCRIPTION
**Pull request by edi-odoo**
In order for all snippets to be better supported by the builder and its new design-tab, some changes were needed.
A lot of snippets used bootstrap classes (ex: for text alignment), these have been replaced by inline styles so they can be overridden by the editor.
The templates have also been adapted so as to use the newest versions of these snippets.

task-2835454

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by KangOl** [comment]
35 commits? It should be better to use a merge commit with a correct message.

**Comment by dmo-odoo** [comment]
@robodoo rebase-merge

**Comment by dmo-odoo** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@edi-odoo 
Seems like it reintroduces bs4 :fearful: like no-gutters that should be g-0 e.g. now.

**Comment by dmo-odoo** [comment]
@JKE-be Thank you for notifying us ! I have fixed the bs4 classes in https://github.com/odoo/odoo/pull/98247.

**Pull request closed without merging**
