### PR TITLE
[FIX] website_sale_stock: prevent buying consumable

### PR DESCRIPTION
**Pull request by nim-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by wtaferner** [comment]
@nim-odoo 
Why not just merge https://github.com/odoo/odoo/pull/47504 I opened weeks ago and you approved?

**Comment by Yenthe666** [comment]
Written by Odoo itself. Much wow, such good.

**Comment by nim-odoo** [comment]
> @nim-odoo
> Why not just merge #47504 I opened weeks ago and you approved?

Sorry, forgot about it.

> Written by Odoo itself. Much wow, such good.

Thanks for this constructive comment.

**Pull request closed without merging**
