### PR TITLE
[IMP] fields: speedup of `convert_to_cache` for x2many fields

### PR DESCRIPTION
**Pull request by rco-odoo**
The algorithm's complexity changed from O(n²) to O(n).

### CODE REVIEW

**Comment by rco-odoo** [comment]
This proposal generalizes #7347 by applying the optimization to the *whole* loop.

**Comment by Yenthe666** [comment]
:+1: will be a great speed improvement, especially on big lists!  :smile:

**Comment by rco-odoo** [comment]
@odony @KangOl can you have a look at this one?
I would like to have some extra review before merging it to 8.0.

**Comment by KangOl** [comment]
Seems correct (and easier to read)

**Comment by odony** [comment]
Looks good to me too. Using a set should also get rid of the *O(n)* list lookups that were still used in the partial improvement of #7347. I don't suppose we have any unit test for `_convert_to_cache` yet?

**Comment by hbrunn** [comment]
:+1:

**Comment by wtaferner** [comment]
Yay, just did a simple direct comparison of local request loading time test and the read of about 4000 one2many records was taking only 16s instead of 18s which is quite an improvement :+1:

**Comment by Yenthe666** [comment]
Any improvement on such a basic function is good to be honest, its used a lot in Odoo. :+1:

**Pull request merged**
