### PR TITLE
[FIX][sale_stock]Added validation in get_partner_to_invoice, to only check sale.orders when the picking that call this method coming from a sale.order

### PR DESCRIPTION
**Pull request by luistorresm**

### CODE REVIEW

**Comment by luistorresm** [comment]
To fix the next Issue #6325

**Comment by luistorresm** [comment]
to fix the next issue #6323.

**Comment by nim-odoo** [comment]
Hello,
Thanks for the PR, however that doesn't solve the issue. Therefore, I close it. Do not forget to reopen if I'm wrong.
Regards

**Comment by nim-odoo** [comment]
Woops, my bad, it indeed solves the issue :)

**Comment by nim-odoo** [comment]
Merged with 01e4b76f656df1ef88b57af511ea28f3e9b6dc1d
Thanks!

**Pull request closed without merging**
