### PR TITLE
[IMP] point_of_sale: subtotal w/o tax and subtotal fields got blank value

### PR DESCRIPTION
**Pull request by jipr-odoo**
Before this commit:
===================
`Subtotal w/o Tax` and `Subtotal` fields in the backend (pos_order) were
 displaying blank values.

After this commit:
===============
- Fixed the blank values in the `Subtotal w/o Tax` and `Subtotal` fields in pos_order in the backend.
- Rename fields `Subtotal w/o Tax`  to `Tax Excl.` and `Subtotal` to `Tax Incl.`

Task - 3842883

### CODE REVIEW

**Review by adgu-odoo — CHANGES_REQUESTED** [review]
I think `price_subtotal` and `price_subtotal_incl` are not used in the frontend. Maybe it could be a good idea to change those fields to stored computed fields so that it is recomputed when the quantity change or when the unit price changes. Tell me what you think about it ?

**Comment by jipr-odoo** [comment]
> I think `price_subtotal` and `price_subtotal_incl` are not used in the frontend. Maybe it could be a good idea to change those fields to stored computed fields so that it is recomputed when the quantity change or when the unit price changes. Tell me what you think about it ?

@adgu-odoo Agreed with your point. we already have a method `_compute_amount_line_all`, we can make this method compute for both `price_subtotal` and `price_subtotal_incl`.

**Comment by jipr-odoo** [comment]
Could you please check again @adgu-odoo 
Thank you!

**Review by adgu-odoo — APPROVED** [review]

**Comment by adgu-odoo** [comment]
@robodoo r+

**Comment by adgu-odoo** [comment]
> > I think `price_subtotal` and `price_subtotal_incl` are not used in the frontend. Maybe it could be a good idea to change those fields to stored computed fields so that it is recomputed when the quantity change or when the unit price changes. Tell me what you think about it ?
> 
> @adgu-odoo Agreed with your point. we already have a method `_compute_amount_line_all`, we can make this method compute for both `price_subtotal` and `price_subtotal_incl`.

Sorry I did not see your comment but what you did is good for me. Thank you

**Pull request closed without merging**
