### PR TITLE
[REM] web_planner: Remove the module

### PR DESCRIPTION
**Pull request by tivisse**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@tivisse may I ask why it is being removed or what the idea is behind it?

**Comment by nhomar** [comment]
@tivisse What will replace this feature?

We had "Process View (With auto link to doc)" then this was removed in favor of "Help button" and then came "web_planner" I honestly think the Idea behind this was really really good but bad marketed....

Can you enlight us what will be the next approach or this will simple be replace bey a "Go to documentation" Link?

**Comment by tivisse** [comment]
Hello @Yenthe666 and @nhomar 

I understand your concern. I ping @fgi-odoo @bst-odoo @lap-odoo @apr-odoo from the Product Owners team. 

They know the v12 road map and what they intend to do to replace the planners.

Have a nice day,

Yannick.

**Comment by bst-odoo** [comment]
Hello all,

We noticed during the user tests that the planner were not used at all. People didn't read it and were confused about it's meaning. It was even a waste of time. For example, in CRM, you have to fill your pipeline stages in the planner, then do the same in the app.

We will fill the gap for all the app with a better onboarding, a better design (e.g. make it obvious how to add stages in a kanban view), better tour tips and cleaner screens.

In accounting, we have developed a brand new configuration bar which is way better than a planner.

Have a nice day,

Benjamin 

http://isitfriday.org/

**Comment by nhomar** [comment]
@bst-odoo As I said "nice Idea bad marketed" IF you put a simple Popover as the first step "Open and plan your implementation" AND link the filling elements on the fly (2 or 3 controllers calling the current settings) making it more inheritable, should be enough.

BUT yes, just a bar green that does not say anything and anybody click on it is a waste of time.

BTW: Wee need a place were to put "In app" documentation. (Not pure tool tips they are annoying BTW).

**Comment by Yenthe666** [comment]
Thanks a lot for the feedback @tivisse and @bst-odoo!
Will the new onboarding and functionalities still land in the community version or can we expect a migration to enterprise?

**Comment by bst-odoo** [comment]
@nhomar You are right but actually it's not that easy to change. Indeed we should fin a right way to redirect people to the doc.
We have some ideas but it is still in debate.

@Yenthe666 The new onboarding + design improvements are expected to be merged in community, it impacts the views directly.

**Pull request merged**
