### PR TITLE
add city dongguan

### PR DESCRIPTION
**Pull request by lonelyleaves**

### CODE REVIEW

**Review by william-andre — COMMENTED** [review]
Hello, thanks for the contribution!

Can you please respect the guidelines for the commit message? https://www.odoo.com/documentation/14.0/developer/misc/other/guidelines.html#commit-message-structure
Also sign the CLA? https://github.com/odoo/odoo/blob/15.0/doc/cla/sign-cla.md

Maybe some source would be nice too, I have tried searching for it on Google (without speaking the language) and I must admit that I couldn't find anything that matched your commit.


______
@jco-odoo On a side note, wouldn't it make sense to convert this in CSV to make it more readable and possibly load faster? And also sort the data while we are at it? Because what the *?

**Comment by jco-odoo** [comment]
@tsb-odoo @william-andre I suggest deleting this module.  It has no legal requirement stated.  If we add it here, we should be coherent and add all the cities of the world. @mart-e

**Comment by mart-e** [comment]
>  If we add it here, we should be coherent and add all the cities of the world.

That doesn't seem like a good justification (we shouldn't start developping Belgium payroll because we don't have it in every countries ?). We should be coherent within the country but not necesarily for the rest of the world.
Removing it because we don't want to _maintain_ a list of every city of China could be a good justification though.

**Comment by C3POdoo** [comment]
Dear @lonelyleaves,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
