### PR TITLE
[IMP] l10n_fr: add account groups

### PR DESCRIPTION
**Pull request by AdrienHorgnies**
Description of the issue/feature this PR addresses:
account groups
Current behavior before PR:
no account groups
Desired behavior after PR is merged:
account groups

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by AdrienHorgnies** [comment]
@jco-odoo I rebased that branch, can you merge it if it's alright ? It's part of https://www.odoo.com/web#id=2217509&action=333&active_id=1691&model=project.task&view_type=form&cids=1&menu_id=4720

**Comment by AdrienHorgnies** [comment]
closed by mistake...

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
Thanks @AdrienHorgnies

**Pull request closed without merging**
