### PR TITLE
FIX Summernote editor not displaying in forum for portal user

### PR DESCRIPTION
**Pull request by eLBati**
(for admin it works)

See https://github.com/odoo/odoo/issues/9402

### CODE REVIEW

**Comment by mart-e** [comment]
@eLBati I don't link the idea to import summernote for every website user. @nle-odoo is working on a fix to import it only in website_forum

**Comment by nle-odoo** [comment]
Hello. It should be solved with 09411a4 which takes into account `mart-e` suggestion, and another better fix has been added to master (so for saas-9 and over): de5a00a

Thanks for solution which was also working.

**Comment by eLBati** [comment]
@nle-odoo just tested with latest revision of 9.0 and the problem is not solved.

If I apply this patch, it works

**Comment by nle-odoo** [comment]
Hello, I have just tried on last runbot saas-6 with demo, portal and admin user and I see the editor on the forum in the scenario described in the issue.

In master another solution is used (a little more clean in my opinion but not good for a stable version), and I also tested and it was working.

**Comment by eLBati** [comment]
@nle-odoo didn't you test with 9.0?

**Comment by nle-odoo** [comment]
yes, in 9.0 with portal:

2016-01-20-172018_1920x1080_scrot

in 9.0 with admin:

2016-01-20-171957_1920x1080_scrot

logically with this fix if the user:

* is in the `base.group_website_designer` group he should have the editor script on the whole website,
* is not in the `base.group_website_designer` group he should have the editor on the forum

so I don't understand why it would not work, do you have the javascript assets `web_editor.summernote` on your forum page and is there no error in the javascript console?

thanks.

**Pull request closed without merging**
