### PR TITLE
[REM] all: Remove es_MX.po files

### PR DESCRIPTION
**Pull request by moylop260**
- Previous information:
  - `es_MX` language is not published to [transifex](https://www.transifex.com/odoo/odoo-10/languages/) this is a official announce from thread [Regional languages and Spanish (Latin America) translations](https://www.odoo.com/es_ES/groups/community-translators-63/community-translators-20325962?mode=thread&date_begin=&date_end=) by @mart-e 
  - Currently we have the files `es_MX.po` with terms translations outdated or wrong translation.
    - [Example wrong translation es_MX.po](https://github.com/odoo/odoo/blob/8de795291/addons/account/i18n/es_MX.po#L7788) should be [es.po correct translation](https://github.com/odoo/odoo/blob/8de795291/addons/account/i18n/es.po#L7975)
  - Now to change a `es_MX.po` a PR is required.
  - `es.po` terms translations and the most terms are fine for México too. (Not regional translation is required for most cases)

Then our regional translation process should be:

| step | If is accepted | If is not accepted |
|------|-----|-------|
|   Create a proposal to original language `es.po` from transifex    |   good and finish!  |   Create a new PR to odoo/odoo adding just that special term to `es_MX.PO` |

This PR reset the `es_MX.po` terms in order to fix many wrong terms using the good `es.po`.

FYI for the record, script used:
<s>  - [reset po file gist](https://gist.github.com/moylop260/9439b6c969b473a7cc951352bf00ffe2)
 -  Run the command  `find ~/odoo -not -path ./git  -name "es_MX.po" -exec python ~/clean_po.py {} \;`</s>

  - `find . -not -path ./git -name "es_MX.po" -exec git rm -rf {} \;`

### CODE REVIEW

**Comment by mart-e** [comment]
Thanks for the patch. Why do you want to keep the header of each file? If it's empty wouldn't it be easier to just remove it?

**Comment by moylop260** [comment]
> If it's empty wouldn't it be easier to just remove it?

I deleted all `es_MX.po`

**Comment by mart-e** [comment]
Ok, I was just wondering if there was any reason.
Good for me, will merge it on Monday and I hope I will have a better solution that "make a PR" for regional languages soon...

**Comment by moylop260** [comment]
@mart-e 
Could you foward-porting this PR to master?
Or Do you prefer that I create a new PR?

**Comment by mart-e** [comment]
@moylop260 done at 19fce206ac420e03465316b8d8db1bd54ea4c013
The po are ignored during forward ports, that is why it wasn't present

**Comment by moylop260** [comment]
I got it
Thank you man

**Pull request closed without merging**
