### PR TITLE
[FIX] sale_project: widget call from missing dependency

### PR DESCRIPTION
**Pull request by yosa-odoo**
Steps to reproduce:

- install only sale_project
- go to Project > Configuration > Projects
-> Warning in the JS console

OPW-2717655
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

sale_order_many2one is added by `sale_expense` which is not a dependency of `sale_project`

as far as I can tell, widget `sale_order_many2one` just remove the "Search More" when there is more results than the current suggestion, so I'm not sure what would be the best:

- just removing the widget (this PR)

- just ignore the JS warning (but it may cause tests to make it seems like something doesn't work)

- doing a bigger change that will instantiate the widget "sale_order_many2one" in sale instead of sale_project => this would add a file to do it cleanly, so only work with -u (and we would need to keep the duplicated widget in sale_expense or we would have an error for someone that doesn't `-u`)

in my opinion it's alright enough like it is now

@tivisse what do you think?

**Review by IT-Ideas — APPROVED** [review]
Thanks for the fix.
The issue has been introduced [here](https://github.com/odoo/odoo/pull/39441) from what I found out.

**Comment by IT-Ideas** [comment]
Shouldn't it be fixed in earlier version then?

**Comment by nle-odoo** [comment]
Thanks.

You are right, I rebased this branch on 14.0 (the code is not present in 13.0 since the referenced commit is not in it.

robodoo r+

**Comment by nle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
