### PR TITLE
CI for doc

### PR DESCRIPTION
**Pull request by xmo-odoo**
The doc fails to build semi-regularly:

* JS docstrings are incorrectly formatted or written in a way which breaks the parser
* new versions of Sphinx remove APIs we're still using
* doc fixes don't take older Sphinx versions in account

This attempts to automatically build the doc using travis (for a multi-version text matrix, also because that's convenient).

travis seems on the wane (apparently acquired & fired a bunch of folks). Apparent alternatives would be:

* circleci, haven't managed to get it working yet & I don't understand how to get it working on non-master branch (other branches, PRs, …) (nb: [this might be useful](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories))
* azure pipelines, haven't looked at it yet

### CODE REVIEW

**Comment by xmo-odoo** [comment]
TODO: only build across the entire matrix if the branch is master, on prs & al only check on one python x sphinx combination.

**Comment by xmo-odoo** [comment]
ping @mart-e 

Alternatively we could split out the sphinx extensions in an other repo (so we can test them more easily across an entire matrix) and then only check the actual doc-building on a single "blessed" version of (python, sphinx)

**Comment by mart-e** [comment]
The main advantage to do so would be to share the extensions between functional and technical doc but then introduce submodules.
Do we really want to open that door?

**Comment by xmo-odoo** [comment]
That's the question innit?

**Comment by mart-e** [comment]
Soooo, no ?

**Comment by xmo-odoo** [comment]
We'll probably add that to runbot eventually (and maybe have a full automation suite for the user doc)

**Pull request closed without merging**
