### PR TITLE
[FIX] hr_fleet: no duplicate contract renewal activity reminder

### PR DESCRIPTION
**Pull request by fdamhaut**
Step to reproduce:
- Have a fleet contract that need renewal

Current Behaviour:
- A new activity is created everytime the scheduler is called

Behaviour after PR:
- A new activity is only created if there is no current renewal activity present when the scheduler is called

opw-2713537

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — COMMENTED** [review]
so If I understand this happen because before 82df1dfccc6b4e3031b1434c7ec1bec2bf7aeb2d we would do in this part:

```py
nearly_expired_contracts.write({'state': 'diesoon'})
```

so the contract would not be state==open the next day.

Then your fix makes sense to me, some small points.

The fallback seems incorrect:

```py
False in self.env['mail.activity.type']
TypeError: Mixing apples and oranges: False in mail.activity.type()
```

to match activity_schedule, it should probably rather be:

```py
or self._default_activity_type()
```

besides that, the line is a little long, you could do something like:

```py
        nearly_expired_contracts = self.search(
            [
                ("state", "=", "open"),
                ("expiration_date", "<", outdated_days),
                ("user_id", "!=", False),
            ]
        ).filtered(
            lambda c: reminder_activity_type not in c.activity_ids.activity_type_id
        )

        for contract in nearly_expired_contracts:
```

**Review by nle-odoo — APPROVED** [review]
looks good to me, with that there should not a new expiration activity until the previous one is handled

but to be sure functionally @tivisse what do you think about this?

**Comment by tivisse** [comment]
@nle-odoo LGTM too, thanks.

**Comment by nle-odoo** [comment]
thanks

robodoo r+

**Comment by nle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
