### PR TITLE
13.0 sms webhook provider feedback thc

### PR DESCRIPTION
**Pull request by Explicitapps**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
sms status can be updated when we receive feedback from the provider on the sms service

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Hello @Explicitapps 

Please don't remove automatic reviewers based on code owners. Indeed this indicates you are modifying files we monitor. By the way, is it intended to target 13.0 ? As you are modifying DB schemes, either target master, either work with additional modules if you feel this is completely required. I am not sure this is required for stable as this is an improvement and not really fixing a bug.

Many thanks,


cc @seb-odoo

**Comment by mart-e** [comment]
This kind of changes should definitly not target a stable version. No change of db structure, no new feature.

**Comment by Explicitapps** [comment]
> . I am not sure this is required for stable as this is an improvement and not really fixing a b

The idea is to update all versions (including 12.0 but I don't know if this'll be possible because sms_sms model does not exist in 12 ) the goal is to add a real status from the provider because of some people complaining about sms marked as sent but not received. Until now sms was marked as "sent" if we correctly sent them to the provider without errors but it was never mean to be really sent to the contact. Now that we got a real feedback  from the providers we want to change that.

**Comment by tde-banana-odoo** [comment]
Hello @Explicitapps ,

As all new features, it should target master. Having some people complaining about missing status is not a reason to develop new features in stable. New features are always done in master. This is an incentive to migrate to master as new features are available for them.

Adding code in stable breaks flows, introduce new bugs and lead to complicated code due to existing data and frozen database scheme. Unless really required (legal issue, broken flow leading to work being impossible), it should target master.

Could you also point out the task in the commit message so that we find it back in Odoo ?

Many thanks,

**Comment by Explicitapps** [comment]
@tde-banana-odoo 

Yes I know that. You should ask/talk about that task with @fda-odoo as he asked me to work on that and this PR was for now only a suggestion on how it'll look.

**Comment by tde-banana-odoo** [comment]
Do you have a task so that we discuss on it instead of github :D ?

**Pull request closed without merging**
