### PR TITLE
[IMP] stock: add hook to get virtual location

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

This hook makes extensible `_generate_moves` method by being able to change the virtual location.

I know that by norm the improvements go to master, and only fixes can land on stable. But... can yo do an exception for this kind of simple hook, please? 🙏🙏🙏🙇‍♂️

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
ping: @sle-odoo

**Comment by mreficent** [comment]
@sle-odoo could you check, please?

**Comment by sle-odoo** [comment]
i think the patch is not complete since the property will be read on the company in the environment. you should set a force_company with the company of the inventory adjustment like we did in 13.0

also we won't merge it in 11.0 i'm sorry, maybe 13.0 but what's the use really? can't you work directly with the property?

**Comment by mreficent** [comment]
@sle-odoo updated the PR following your comment! Please, can you check again?

Accounting-wise, you might want to expense certain inventory adjustments to a different account. Having a single virtual location proposed for inventory adjustments means that you have to stick to a single account. You can see the usefulness in https://github.com/OCA/stock-logistics-warehouse/pull/715.

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
