### PR TITLE
Saas 12.1 crm track type jke

### PR DESCRIPTION
**Pull request by JKE-be**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo r+ rebase-ff

**Comment by JKE-be** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
robodoo retry

**Comment by JKE-be** [comment]
robodoo please retry and be kind plz

**Comment by JKE-be** [comment]
thank you !

**Pull request closed without merging**
