### PR TITLE
[FIX] l10n_it_edi: fix it vat change

### PR DESCRIPTION
**Pull request by jbw-odoo**
Manual forward port of https://github.com/odoo/odoo/pull/74064.

Task: opw-2965529

### CODE REVIEW

**Comment by jbw-odoo** [comment]
> @jbw-odoo I don't think it solves the issue because it is called from the qweb. (_l10n_it_normalize_codice)

Qweb is not calling _l10n_it_normalize_codice directly, is it ? Isn't it triggered by the onchange ?

**Comment by jco-odoo** [comment]
https://github.com/odoo/odoo/blob/1b8b1633cc04d11343ee69f4b687c8fd35ab460a/addons/l10n_it_edi/data/invoice_it_template.xml#L47

**Comment by jbw-odoo** [comment]
> https://github.com/odoo/odoo/blob/1b8b1633cc04d11343ee69f4b687c8fd35ab460a/addons/l10n_it_edi/data/invoice_it_template.xml#L47

Gotcha. Made change

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
