### PR TITLE
[IMP] mail: introduce CallView/calculateTessellation

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2871867

### CODE REVIEW

**Review by phenix-factory — COMMENTED** [review]
There is some confusion that could be avoided: 

- Having a component named `call_view` and a model also named `call_view`. We should rename this component.
- `computeTessellation` is not related to a compute field, witch confused me. We should rename this and reserve the compute term to actual computed field. (suggestions: `calculateTessellation`, `generateTessellationValue`?)

**Comment by alexkuhn** [comment]
I don't get why it's a problem the same name with component and model. It's a 1:1 map, so make sense having same name.
If you really want difference, then let's just put suffix `Component` to all our components.

Ok for rename of `computeTessellation`.

**Comment by phenix-factory** [comment]
> I don't get why it's a problem the same name with component and model. It's a 1:1 map, so make sense having same name.

I see a few:

- Isn't every component a view ?
- Unique name make it easier to find the file you are searching for.
- Trying to review this was really confusing, It make it harder to understand where the diff come from.

Can we just name this component `call` ?

**Comment by alexkuhn** [comment]
Change done (rename method to `calculateTessellation`)

**Review by phenix-factory — APPROVED** [review]
LGTM

**Comment by alexkuhn** [comment]
Moved to grouped PR: https://github.com/odoo/odoo/pull/93330

**Pull request closed without merging**
