### PR TITLE
CorTex-IT-Solutions-Ltd cla

### PR DESCRIPTION
**Pull request by MohsenWaleed**
CorTex-IT-Solutions-Ltd cla

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `24973578+MohsenWaleed@users.noreply.github.com`
- you are signing _for_ the address `m...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by MohsenWaleed** [comment]
Thanks @mart-e, I have changed it.

**Comment by mart-e** [comment]
@MohsenWaleed thanks for the change but you have to make a commit in the branch to update the CLA check

**Comment by mart-e** [comment]
Hi,

Is this still needed? Don't hesitate to make changes or create a new PR with the right email if you want us to integrate the CLA.

**Pull request closed without merging**
