### PR TITLE
replace simplejson with stdlib json

### PR DESCRIPTION
**Pull request by leorochael**
The stdlib version of the json library is more recent than the 3.5.3 version we are pinning in `requirements.txt`.

Is there a reason to use it instead of the standard one?

### CODE REVIEW

**Comment by antonylesuisse** [comment]
@mart-e  ok for v9.

**Comment by mart-e** [comment]
Thanks for the patch, merged in 9.0:
bf4b47c [IMP] JSONDecodeError > ValueError
60af7ca [IMP] replace simplejson with stdlib json

**Comment by leorochael** [comment]
@mart-e,

Since I couldn't check this patch myself against v9, please make sure no `simplejson` reference was introduced between v8 and v9 with:

```bash
git grep simplejson
```

Thanks for the merge!

**Comment by mart-e** [comment]
@leorochael why can't you check the v9? The [9.0 branch](https://github.com/odoo/odoo/tree/9.0/) is published. But anyway, don't worry I did a grep to add the few remaining ones :-)

**Comment by leorochael** [comment]
@mart-e, I couldn't check v9 because I was on vacation with very limited net access but I wanted to make sure this got merged before v9 was officially released ;)

**Comment by mart-e** [comment]
@leorochael yes, that's what I said at https://github.com/odoo/odoo/pull/6940#issuecomment-143682794, merged in 9.0 at bf4b47c :-)

**Pull request closed without merging**
