### PR TITLE
[IMP] avoid excessive filestore sizes

### PR DESCRIPTION
**Pull request by Xavier-Do**
During the tests, many attachment can be created and unlink.
They will be eventually cleaned up if the cron is ran but this is
usually not the case during tests. The disk usage can increase to reach
more than one 1 Go when design theme is installed.

This can lead to unnecessary big database dumps.
This is also a problem on odoosh where the filestore max size is limited
to 1Go during automated testing.

The gc should be quite fast if nothing was changed since it will just
check the content of an empty directory.

The method is made accessible in the test case in order to be able to gc
on demand. This may be useful in the test_01_crawl_every_themes that
can generate around 600~ Mo of attachment in the loop.

We can also remove the bundle name from assets name
The bundle name is irrelevant in the bundle content and will prevent
attachment to store the same file if the bundles are exactly the same.

### CODE REVIEW

**Review by sts-odoo — APPROVED** [review]
LGTM

**Review by Julien00859 — APPROVED** [review]

**Comment by sts-odoo** [comment]
robodoo r+

**Comment by Xavier-Do** [comment]
robodoo r+

**Comment by Xavier-Do** [comment]
robodoo rebase-ff

**Pull request closed without merging**
