### PR TITLE
[FIX] purchase: do not apply archived taxes

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
- Create a new purchase tax and archive it
- Create a new PO

Bug:
the archived tax is still sugested on the PO Line

Fix:
apply same logic as for sales

opw-3701429

### CODE REVIEW

**Review by DjamelTouati — COMMENTED** [review]
Hello,
the archived tax is still sugested on the PO Line, becuase we have " context={'active_test': False}",  this means that searching or selecting related records will not take the activity condition into account.

**Comment by HANNICHE-Walid** [comment]
> Hello, the archived tax is still sugested on the PO Line, becuase we have " context={'active_test': False}", this means that searching or selecting related records will not take the activity condition into account.

`active_test` will prevent the tax from being unlinked from existing POlines but by removing the domain the archived taxes won't be suggested on the UI

**Review by DjamelTouati — APPROVED** [review]
Perfect, Thanks for your fix !

**Comment by clesgow** [comment]
What an odd domain too. :thinking:
@robodoo r+

**Pull request closed without merging**
