### PR TITLE
[CLA] Update Vauxoo's CLA

### PR DESCRIPTION
**Pull request by carralc**
Incorporate Carlos Carral (carralc) as Vauxoo's contributor.
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hugho-ad** [comment]
Hi @mart-e,

Could you review/merge, please?

Regards,

**Comment by mart-e** [comment]
@hugho-ad the CLA is still failing because there is no email (and name) in the commit
https://github.com/odoo/odoo/pull/117426.patch

**Comment by carralc** [comment]
Hello @mart-e , I ammended the commit

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
