### PR TITLE
Demo is not installed sometimes

### PR DESCRIPTION
**Pull request by etobella**
Description of the issue/feature this PR addresses:
Fix the issue shown in https://github.com/odoo/odoo/pull/29779#issuecomment-524346268

Current behavior before PR: 
Sometimes, the demo data is not automatically installed.
The problem arises when all the related modules to a module are already checked.

Desired behavior after PR is merged:
The demo data should work as expected

@Elkasitu 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Elkasitu** [comment]
>The problem arises when all the related modules to a module are already checked

Can you explain *why* this is a problem and add it to your commit message?

Also please reformat your commit header like so: `[FIX] base: install demo data if all dependencies are already met`

Thanks

**Comment by etobella** [comment]
@Elkasitu Change applied

**Comment by etobella** [comment]
runbot is failing, but I think it is related to a previous commit, as master was failing http://runbot.odoo.com/runbot/branch/1

**Comment by seb-odoo** [comment]
This needs to be fixed where the bug was introduced (12.4 or 12.5? Need to verify). Definitely not master.

**Comment by etobella** [comment]
According to @mart-e It was attached to master on 26 July I think it could affect 12.5 and master
https://github.com/odoo/odoo/commit/2486259ef99ec85cf1c0a8200e31d350c582fd4c#issuecomment-515328471

**Comment by mart-e** [comment]
See comment at https://github.com/odoo/odoo/pull/36143#issuecomment-525352819
Sorry but we are reverting the patch for now

**Comment by Elkasitu** [comment]
FWIW, the reason we did not merge this patch is that, while it fixes the previous example on website and website_blog, we found another issue with mrp_maintenance (maintenance demo data is not installed, and mrp_maintenance demo data depends on the former to work) in enterprise.

The code itself is touchy and poorly documented (as with a lot of things in the ORM), so we came to the conclusion that the benefit of the patch was too low compared to the risk and thus not worth risking it, especially so close to v13.

**Comment by etobella** [comment]
Do not worry. It is totally understable. I think a refactoring is needed in order to solve the original issue but it will be on 14 :wink:

**Pull request closed without merging**
