### PR TITLE
[CLA] Alejandro Santana

### PR DESCRIPTION
**Pull request by alejandrosantana**
Updated individual CLA with email as freelancer. Replaces https://github.com/odoo/odoo/pull/6231

### CODE REVIEW

**Comment by alejandrosantana** [comment]
@mart-e Here it is the updated individual CLA with my freelancer email.

**Comment by mart-e** [comment]
well except that you have commited it with the `@anubia.es` email address. As you are signing for `@alejandrosantana.eu`, I need you to actually do the commit with this one :)

**Comment by alejandrosantana** [comment]
OK, I go for it. Hope I do it well now.

**Comment by mart-e** [comment]
@alejandrosantana you don't need to recreate the PR, you can amend your commit

**Comment by alejandrosantana** [comment]
I am editing this minor changes directly on Github, so I really do not know how to amend it here. Anyway. I already did a new one. Sorry for the inconvenience.

**Pull request closed without merging**
