### PR TITLE
[REF][ADD] *: improve app icons, add SVG version

### PR DESCRIPTION
**Pull request by stefanorigano**
- Uniform colours and design
- Replace duplicated icons (eg. sale / sale_management)
- Improve misleading icons (eg. POS)
- Add icons for new apps

Add SVG version to lossless future editing and print/marketing use

Task 54681.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the SVG versions!

**Comment by stefanorigano** [comment]
@qsm-odoo , the PR I was talking you about (community)

**Comment by stefanorigano** [comment]
@pedrobaeza  :) 
Please note that these icons are for v12

**Comment by pedrobaeza** [comment]
Better later than never, hehe.

We are investigating for adding SVG support in image widget + website, so maybe the PNG rasterized files would be removable soon :smiley: 

Discussion about the feature in https://github.com/odoo/odoo/pull/24763#discussion_r188858733

**Comment by qsm-odoo** [comment]
Merged https://github.com/odoo/odoo/commit/1d9208c4fa92d00090b37b8e5dbed48087a7f52f, https://github.com/odoo/odoo/commit/97fc6c0b5a64d7ce754de9ae1faa887e67d9cdf0 and https://github.com/odoo/odoo/commit/1934780fc374667018d60e635ab79318573507c6

**Pull request closed without merging**
