### PR TITLE
16.0 fix unaccent cause slow query in btree type index

### PR DESCRIPTION
**Pull request by paimonchan**
Improve the performances when searching by name.

Steps to reproduce:

Accounting > Accounting > Journal Entry
Use a name search by journal entry. Do not select the exact number, but keep the name search.
On large databases (in my case is around 6 million datas), this can take more than a minute, while using operator equals it would take only a few seconds. This is because when using a domain like, for example [('name', 'like', name)]

The reason its not using the index when using unaccent on btree index. unaccent is active by default, but the index still using btree because the database not installing extension pg_trgm for trigram index.

later i found that unaccent should be only used when the function is present and indexable.

### CODE REVIEW

**Comment by ryv-odoo** [comment]
Hello @paimonchan , thank you for proposal.
It is not possible to change this semantic in stable, it is far too dangerous (it can change the behavior of lot of database). Also, normally a warning should have appear to explain the issue: https://github.com/odoo/odoo/blob/04e35d7bf3ca98dc722795c75033747697d70d30/odoo/modules/registry.py#L593

**Comment by paimonchan** [comment]
> Hello @paimonchan , thank you for proposal. It is not possible to change this semantic in stable, it is far too dangerous (it can change the behavior of lot of database). Also, normally a warning should have appear to explain the issue:
> 
> https://github.com/odoo/odoo/blob/04e35d7bf3ca98dc722795c75033747697d70d30/odoo/modules/registry.py#L593

hello, thankyou for your reply.

currently in our company using odoo 16 saas version, so we didn't get this form of message.

from our investigation, we found that after upgrade  from v14 to v16, our database still using `btree` type index for all table, but when doing any searching using operator `like`, odoo using function `unaccent`.  this function cause SQL searching not using index when the index is `btree`.

for the example in Journal Entry, When searching using `column` name and operator `ilike`, it take more than a minute to completed. but when seraching using operator `=`, it take less than 2 second to complete.

later we found, in our database is not yet installed extension `pg_trgm` which cause  the database is created, it failed to create index using type trigram.

so i think, if in the database not yet installed that extension, we should not use function `unaccent`

**Comment by ryv-odoo** [comment]
> from our investigation, we found that after upgrade from v14 to v16, our database still using `btree` type index for all table, but when doing any searching using operator `like`, odoo using function `unaccent`. this function cause SQL searching not using index when the index is `btree`.

In fact, Odoo's `'like'` operator uses unaccent. IMO, it was a mistake in Odoo v16 et lesser, so I changed this behavior for the v17: https://github.com/odoo/odoo/pull/136007 (ilike/=ilike are still use it, of course) - and I don't want to backport it, because we avoid changing semantics in stable anyway.
Also, even if unaccent is INDEXABLE, we never use it to create btree indexes, we only use it for trigram indexes

> later we found, in our database is not yet installed extension `pg_trgm` which cause when the database is loaded, it failed to create index using trigram type.

Thanks you for the report, we are modifying the migration script to automatically install `pg_trgm` and make `unaccent` immutable to avoid this case again.

> so i think, if in the database not yet installed that extension, we should not use function `unaccent`

We don't use unaccent() if you don't have the `unaccent` extension, and we don't create an index with unaccent if `pg_trgm` is not installed. But we still want to use unaccent even if `pg_trgm` is not installed, it just means that full-text search won't be able to use any index (this was the case before the trigram index was implemented in Odoo).

Does it help ?

**Comment by paimonchan** [comment]
> Thanks you for the report, we are modifying the migration script to automatically install `pg_trgm` and make `unaccent` immutable to avoid this case again.
> 
does this action will apply for the running Odoo 16 that not yet installed this extension?

**Comment by ryv-odoo** [comment]
> does this action will apply for the running Odoo 16 saas that not yet installed this extension?

Unfortunately, no. If you are still experiencing performance issues, please don't hesitate to open a [support ticket](https://www.odoo.com/fr_FR/help).

Anyway, IMO, it is not a problem in the code, then I close this PR. Thank you.

**Comment by txcom2003** [comment]
Hi @ryv-odoo, do you have any suggestion for odoo technical team regarding to this issue that already affecting a lot of customers that upgrade their database from v14 to v16 ? i think they should install pg_trgm extension and replace btree index with trigram index for the affected columns so that the query won't run slowly in a big database.

**Pull request closed without merging**
