### PR TITLE
[IMP] web: add `showSearchInput` option on ModelFieldSelector

### PR DESCRIPTION
**Pull request by mgeubelle**
The option `showSearchInput` has been added on the ModelFieldSelector to allow
the user to easily filter the displayed fields. An input is displayed in the
popover title.

The search method is fuzzy for optimal results.

### CODE REVIEW

**Comment by qsm-odoo** [comment]
Did not you merge this in 12.0 ?

**Comment by mge-odoo** [comment]
Nop, I didn't want to [IMP] on stable branch.
al took it on a local branch during its demo.

**Comment by mge-odoo** [comment]
@ged-odoo please consider to command robodoo to merge this PR. I have used fuzzy!

**Comment by mge-odoo** [comment]
@qsm-odoo can you please robodoo r+ please ? :)

**Comment by mge-odoo** [comment]
Was task 1891904

**Pull request closed without merging**
