### PR TITLE
[FIX] web: correct type of defaultPage prop

### PR DESCRIPTION
**Pull request by thle-odoo**
Steps to reproduce:
- go to "Link Tracker" app;
- go to "Campaigns" tab (UTMs);
- create a new campaign;
- leave and return in this record.

Issue:
A traceback appears.
Error message:
`Invalid props for component 'Notebook': 'defaultPage' is not a string`

Cause:
The `defaultPage` prop must be a string.
When the record is new, it will be `undefined`,
so it will pass props validation because this prop is optional. But when we try to calculate it and it does not return a value, the `defaultPage` is null.
The variable is therefore declared but it is empty (and therefore not a string).
`null` value does not pass the props validation test. The problem appears in the "Campaigns" tab
because there is a notebook without content.

Solution:
Test if it is possible to have a value.
If not, set the `defaultPage` prop to be `undefined`.

opw-3109327

### CODE REVIEW

**Review by hubvd — CHANGES_REQUESTED** [review]
The prop does not pass the validation because of https://github.com/odoo/odoo/blob/1a46ce2409d64ec52d27795e1ec77d3db1297921/addons/web/static/src/core/notebook/notebook.js#L137-L139

What I would do is simply 
```diff
diff --git a/addons/web/static/src/views/form/form_controller.js b/addons/web/static/src/views/form/form_controller.js
index 338e34abdf92..2a9ae1562b1c 100644
--- a/addons/web/static/src/views/form/form_controller.js
+++ b/addons/web/static/src/views/form/form_controller.js
@@ -180,7 +180,9 @@ export class FormController extends Component {
         this.fieldsToTranslate = useState(fieldsToTranslate || {});
         const activeNotebookPages = { ...state.activeNotebookPages };
         this.onNotebookPageChange = (notebookId, page) => {
-            activeNotebookPages[notebookId] = page;
+            if (page) {
+                activeNotebookPages[notebookId] = page;
+            }
         };
 
         useSetupView({
```

Also, I'm guessing this needs a test :stuck_out_tongue_winking_eye:

**Review by hubvd — APPROVED** [review]
We don't actually need to create a record to trigger the issue, we only need to open it.
I simplified the test case to reflect that

**Comment by fdardenne** [comment]
Hello, 
I can't reproduce the traceback. Is it possible to guide me on how to reproduce it ?
chrome-capture-2023-0-10 (1)

**Comment by thle-odoo** [comment]
Note: the social module must not be installed (add page on the notebook)

**Review by fdardenne — APPROVED** [review]
Looks good to me! Thanks for the fix

**Comment by aab-odoo** [comment]
robodoo delegate=fdardenne

**Comment by fdardenne** [comment]
@robodoo r+

**Pull request closed without merging**
