### PR TITLE
[IMP][FIX] UoM: prevent inconsistent data by changing UoM definition

### PR DESCRIPTION
**Pull request by fmdl**
It is the following of https://github.com/odoo/odoo/pull/34060 (ex https://github.com/odoo/odoo/pull/33768)

It is possible to modify the factor, type or categoriy of UoM even if it is used in a sale order, purchase order, BoM,  invoice or accounting entry. It can result inconsistent data on report (mixing orange and apple).

On this PR a generic methode is create in uom module, to check if UoM is already use or not.

Exemple for stock, just add this file to check.
```python
class UoM(models.Model):
    _inherit = 'uom.uom'

    def _get_model_to_check(self):
        res = super(UoM, self)._get_model_to_check()
        res.append({
            'model': 'stock.move.line',
            'field': 'product_uom_id',
            'domain': [('state', '!=', 'cancel')],
            'msg': _("Some products have already been moved or are currently reserved.")})
        return res
```

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@nim-odoo @mart-e

**Comment by fmdl** [comment]
cc @sla-subteno-it

**Comment by fmdl** [comment]
@amoyaux any news ?

**Comment by pedrobaeza** [comment]
This is conflicting. Maybe it's better to close it...

**Comment by fmdl** [comment]
@amoyaux any news ?

**Pull request closed without merging**
