### PR TITLE
[FIX] sale: keep price_reduce_taxinc and price_reduce_taxexcl stable

### PR DESCRIPTION
**Pull request by tdecaluwe**
The `price_reduce_taxinc` computes the unit price of an order line including all taxes, even when some taxes are configured not to be included in the unit price of the product. Generally speaking the price_reduce_taxinc will be equal to or higher than the price_unit field.

Before this commit, as the `price_reduce_taxinc` gets rounded to the same precision, the `price_reduce_taxinc` price would sometimes be different for the first few even and odd quantities. With an example, we can see that this stems from the intermediate rounding on the total price. Let's assume a product with a unit price 126.13 and an 11% tax:

```
qty  subtotal     total  price_reduce_taxinc
--------------------------------------------
  1    126.13    140.00   140.0000 -> 140.00
  2    252.26    280.01   140.0050 -> 140.01
  3    378.39    420.01   140.0033 -> 140.00
  4    504.52    560.02   140.0050 -> 140.01
  5    630.65    700.02   140.0040 -> 140.00
  6    756.78    840.03   140.0050 -> 140.01
  7    882.91    980.03   140.0042 -> 140.00
  8   1001.04   1120.03   140.0037 -> 140.00
  9   1127.17   1260.04   140.0044 -> 140.00
 10   1261.30   1400.04   140.0040 -> 140.00
```

For the first few even quantities, the computed `price_reduce_taxinc` is exactly halfway to the next discrete rounded value. With another example though, it is also clear that changing the tie-breaking method would not resolve the issue:

```
qty  subtotal     total  price_reduce_taxinc
--------------------------------------------
  1    144.14    160.00   160.0000 -> 160.00
  2    288.28    259.99   159.9950 -> 159.99
  3    432.42    479.99   159.9967 -> 160.00
  4    576.56    639.98   159.9950 -> 159.99
  5    720.70    799.98   159.9960 -> 160.00
  6    864.84    959.97   159.9950 -> 159.99
```

A similar issue arises when computing `price_reduce_taxecl` for products using taxes that are included in the base price.

To resolve the issue, the computed totals before rounding need to be taken into account. This commit optionally propagates the rounding errors of the taxes computation through the `_compute_taxes` method. As such, these can be used in the computation of the unit prices before and after taxes, ensuring stable outcomes even when taxes included and excluded in the base price are mixed together.

Note: this behavior can be observed in the shopping cart if the shop is configured to show prices with the taxes included.

opw-3443180

### CODE REVIEW

**Comment by smetl** [comment]
You are probably trying to do weird things for bad reasons. Just stick on the existing taxes computations instead and don't try to reinvent the wheel. That's already enough messy in all modules currently. Taxes computation is not easy...

Each business models should follow this logic: price_subtotal/price_total are computed for each line separately. However, the total of the business model is not a sum of taxes for each line, it's a brand new taxes computation. Why? Because you need to:
- handle correctly the "round globally" feature (not well managed currently but we plan to refactor the whole taxes engine after v17).
- Take care of round taxes as the same way of the accounting side (because in accounting, we have to create tax lines in between so we have an extra complexity for the computation of taxes).

Also, you cannot infer the taxes engine. Whatever you are trying to do with `price_reduce_taxinc`, it's pointless. `price_subtotal` and `price_total` are monetary fields and are always rounded and it has to be rounded. At this point, you already lost some precision. What is the purpose of `price_reduce_taxinc`?

**Comment by tdecaluwe** [comment]
@smetl As you will see, looking at the code, the taxes computation remains entirely unchanged. I'm not trying to reinvent anything, the only thing I'm being able to accomplish is accessing the computed totals before rounding. This does not in the slightest affect the taxes computation however. The extra lines of code keep track of the unrounded counterparts of the totals.

The point of the `price_reduce_taxinc` and `price_reduce_taxexcl` is keeping track of the unit price after and before taxes respectively. As you can see from the commit message, the rounding errors stem from the intermediate rounding in the totals. Returning the rounding errors allows me to recover the unrounded values in the computation of these fields. Alternatively, I could also return the unrounded totals themselves or even simply compute the unit prices before and after taxes directly in the `_compute_taxes` method (for an arguably more comprehensible return value?).

**Comment by tdecaluwe** [comment]
> * Showing this float value for the end user doesn't make sense. He don't want to know he has to pay 32.123456789 USD.

I agree, however the field in question is never used in this way as it is a rounded monetary field.

> * Showing this float value as a monetary doesn't make sense. If you say he has to pay 32.12 per unit but at the end, the total becomes 64.15, he will think there is a bug somewhere. In that case, the correct amount is given by price_total.

Well, this is of course what the bug is about, the screenshot below uses a product with a tax excluded, however the website is configured to show prices with taxes included. Currently, the unit price toggles between 140.00 and 140.01 depending on quantity like described in the commit.
image
The tax computation currently supports the `handle_include` option which would allow us to fix the rounding issue in the inverse usecase: let's say a product is configured with taxes included and the webshop is configured to show prices before taxes. We could simply calculate the taxes for `quantity=1` first then recompute the taxes with `handle_include=false`. This does not apply in the example from the screenshot however, but I'll explore this option.

> * I see on the code things like price_reduce_taxinc * quantity... Just use price_total then. No need to risk rounding errors for no reason here.

No such occurrences are present in this PR, so I guess this out of scope here? Also not that there are two other fields with the same name.

**Comment by smetl** [comment]
@tdecaluwe I understand you point and the whole problem is the root taxes computation. I discussed this issue with the product owners and we have a plan post-v17 to fix such issues. I added this case to the refactoring of taxes task (3444101).
In stable, let's keep the code as it is for now. I'm refactoring the `compute_all` method in master to prepare for the post-v17 refactoring. Depending the remaining time before the release and the priorities, I'll try to fix it as well for v17.

**Pull request closed without merging**
