### PR TITLE
[REF/FIX] spreadsheet: various fix/refs

### PR DESCRIPTION
**Pull request by pro-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pro-odoo** [comment]
robodoo rebase-ff

**Comment by KangOl** [comment]
@odoo/rd-runbot The code-owner rule for the upgrade team should match these `migration.js` files.

**Comment by Xavier-Do** [comment]
> @odoo/rd-runbot The code-owner rule for the upgrade team should match these `migration.js` files.

You mean, if any */migration.js is modified you want to be notified?

**Review by LucasLefevre — APPROVED** [review]
robodoo r+ rebase-ff

**Comment by KangOl** [comment]
> > @odoo/rd-runbot The code-owner rule for the upgrade team should match these `migration.js` files.
> 
> You mean, if any */migration.js is modified you want to be notified?

No, the other way around. We don't care about the js part (most of the time)

**Comment by Xavier-Do** [comment]
> upgrade team should match these `migration.js` files.

Ok so shouldn't match! I've limited to the .py file it it suits you

**Pull request closed without merging**
