### PR TITLE
[CLA] Clean-up of the CLA for brain-tec AG

### PR DESCRIPTION
**Pull request by BT-fgarbely**
[CLA] Clean-up of the CLA for brain-tec AG.
- Renamed brain-tec.md to braintec-group.md and removed the contributors who never contributed.
- Created a new file braintec.md and added the currently needed contributors there.
- Due to our rebranding and the associated change of the domain, this adjustment was necessary.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the update but could you:
- use your email address to make the commit and not the github noreply
- keep the emals of the users that have already made commits (pascal.zenklusen and kumar.aberer)
- elaborate a bit your commit messages to explain the changes

Thanks

**Comment by BT-fgarbely** [comment]
> Hello,
> 
> Thank you for the update but could you:
> 
> * use your email address to make the commit and not the github noreply
> * keep the emals of the users that have already made commits (pascal.zenklusen and kumar.aberer)
> * elaborate a bit your commit messages to explain the changes
> 
> Thanks

Hello @mart-e 

Thanks for your feedback

1) That means I have to configure my email address in GitHub as public. Right? Actually I wanted it to be private, but ok.
2) Our plan was to add employees as soon as they start in our company and remove them as soon as they leave. Is this wrong? I ask this because the two users you mentioned are no longer working in our company. And their email addresses are no longer valid. Does it make sense to keep this information? Then this file will become huge in future if we only add but never remove contributors.
3) I will create a new commit with a more detailed commit message.

**Comment by mart-e** [comment]
1. The email that makes the commit has to be the same as the one in the CLA. If you want to keep it private, you can write `BT-fgarbely@users.noreply.github.com` in the CLA file instead, it's fine with me, it does not need to be a working email.

2. The CLA is only needed when somebody makes a contribution on the Odoo source code. The easiest is to keep it minimal and, when somebody needs to contribute, update the CLA file in the same PR as the wanted change. For the employee that have left the company, you could move them at the end of the file and add a mention like `(up to 2023-02-23)` but this way we keep the history for the merged commits

3. ok but be sure to have only one commit in your PR to be merged.

**Comment by BT-fgarbely** [comment]
> 1. The email that makes the commit has to be the same as the one in the CLA. If you want to keep it private, you can write `BT-fgarbely@users.noreply.github.com` in the CLA file instead, it's fine with me, it does not need to be a working email.
> 2. The CLA is only needed when somebody makes a contribution on the Odoo source code. The easiest is to keep it minimal and, when somebody needs to contribute, update the CLA file in the same PR as the wanted change. For the employee that have left the company, you could move them at the end of the file and add a mention like `(up to 2023-02-23)` but this way we keep the history for the merged commits
> 3. ok but be sure to have only one commit in your PR to be merged.

Hello @mart-e 

Thanks for your answer.
Almost everything is clear to me now.

1) So I will try to re-add my old no longer valid `@braintec-group.com` e-mail address and make it as primary public e-mail address (even though it can't be varified from GitHub) 

But one last question:
2) We made a rebranding and our `@braintec-group.com` e-mail addresses are no longer valid. So I need to keep the current contributors with that old mail address, and start a new block with the same contributors but with the new valid address (`@braintec.com`). Right?

**Comment by mart-e** [comment]
If you have changed the name of your company, a solution could be to move the old one to `braintec-group.md` and create a new CLA called `braintec.md` will the new emails.
It is not an issue for us to have the old one lying around and you can remove old emails from that file if you wish. Just make sure to keep at least:
- frederic.garbely@braintec-group.com
- kumar.aberer@braintec-group.com
- nadal.francisco@braintec-group.com
- pascal.zenklusen@braintec-group.com

as they already have made at least one contribution to odoo

**Comment by BT-fgarbely** [comment]
Hello @mart-e 

I worked on this CLA change. I hope now is all fine so far.
Can you have a look again?

As soon as all is fine and merged, I will do the same changes for the branches `16.0` and `master`, so we are clean for the future. Is that ok or is there another process?

I would like to thank you for your support.

**Comment by mart-e** [comment]
Thank you for the update, it will soon be integrated into Odoo and forward ported to upper versions as well.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
