### PR TITLE
[FIX] website: prevent animation of anchor links with invalid fragment

### PR DESCRIPTION
**Pull request by qsm-odoo**
Also secure the anchor creation to only allow valid names, that is
letters, digits, underscores and hyphens.

task-1913458

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@robodoo r+ retry

**Comment by qsm-odoo** [comment]
I know @robodoo just trying to make you CI that branch :disappointed:

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
robodoo retry

**Pull request closed without merging**
