### PR TITLE
[IMP] product: create product.template.attribute.line in batch

### PR DESCRIPTION
**Pull request by seb-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
did you check the benefice of this create_multi?
Did you test your change ?
And are you sure that other inherit will still support it ?

**Comment by seb-odoo** [comment]
Good questions:

- Inherit: there are none as far as I know
- In practice for 3000 lines (3 for 1000 products): before: 35s, after: 22s, so around 30% again

I updated the commit message to reflect that.

**Comment by seb-odoo** [comment]
@JKE-be friendly reminder

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by seb-odoo** [comment]
@robodoo retry ?

**Comment by JKE-be** [comment]
@robodoo retry

**Pull request closed without merging**
