### PR TITLE
[FIX] stock: orderpoint qty_to_order shouldn't surpass maximum qty

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

The Max Quantity has a meaning of storing capacity too. When the reordering rule generates a procurement, a picking will be generated to increase the stored quantity for that product. But if the Max Quantity is surpassed, then it generates an overcapacity problem. In that location, you will have more product quantity that the one allowed (Max Quantity), and we should avoid that happens.

**Current behavior before PR:** Overcapacity issue.

**Desired behavior after PR is merged:** No more overcapacity issue.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@Whenrow I can do it in a previous version if you prefer

**Comment by MiquelRForgeFlow** [comment]
> which is the `qty_to_order` is no more guaranteed to be a multiple of `qty_multiple`

Why do you thing so? Show me a case. I am sure this patch assures `qty_to_order` is multiple of `qty_multiple`.

> Another idea would be to order one 'multiple quantity' less to be sure the max quantity is not reached.

That's exactly what this patch does! 🤔

**Comment by Whenrow** [comment]
You are right I did not understand your patch correctly. 
After discussing with the logistic product owner, we will leave the behaviour as it is because it's a config issue rather than a "code" issue. Also you can see `test_so_reordering_rule_02` is not really good any more after your change

**Comment by MiquelRForgeFlow** [comment]
Hello @Whenrow I have fixed it. Now `test_so_reordering_rule_02` works as expected.

The issue was as follows:

510 % 10 = 0
51% 1 = 0
5.1 % 0.1 = 0.09999999999999937 which is rounded to 0.1 > 0
0.51 % 0.01 = 0.009999999999999998 which is rounded to 0.01 > 0

Thus, by adding `remainder = float_round(remainder, precision_rounding=rounding) % orderpoint.qty_multiple`, the issue is solved.

Could you reconsider?

**Comment by Whenrow** [comment]
robodoo r+
thank you and sorry for the delay

**Pull request closed without merging**
