### PR TITLE
[IMP] stock: product search by location or warehouse

### PR DESCRIPTION
**Pull request by ppr-odoo**
Issue:https://www.odoo.com/web#id=1816798&view_type=form&model=project.task&action=333&active_id=1278&menu_id=4720

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
This commit makes it useless. Why not just removing the field?
cc @lap-odoo

**Comment by lap-odoo** [comment]
@mart-e The commit doesn't make it useless. I've tested it on the branch and it still does what it was doing before. However, as discussed yesterday, if the commit cannot be done in stable, then we can just remove the field in master.

**Comment by mart-e** [comment]
:+1: let's just remove the field in master instead

**Comment by hmo-odoo** [comment]
continue work on PR: https://github.com/odoo/odoo/pull/23262

**Pull request closed without merging**
