### PR TITLE
[FIX] web: avatar picture object fit

### PR DESCRIPTION
**Pull request by anso-odoo**
Prior this commit, non perfectly squared `.o_avatar` images were not correctly fitted in their boxes

task-3419159
part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by anso-odoo** [comment]
@Brieuc-brd can you check please

**Comment by Brieuc-brd** [comment]
Hey @anso-odoo LGTM 👍  thanks
But before asking for a tech review, can you rebase your branch and make sure this is 🟢 ?

**Comment by anso-odoo** [comment]
Hello @pparidans this PR is 🟢 for tech review

**Review by pparidans — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
