### PR TITLE
12.0 typo in account invoice and stock picking

### PR DESCRIPTION
**Pull request by anandkansagra**
Description of the issue/feature this PR addresses:
I have found some typo issues

Current behavior before PR:

    1) stricly
    2) Unknow stream

Desired behavior after PR is merged:

    1) strictly
    2) Unknown stream

### CODE REVIEW

**Comment by Yenthe666** [comment]
@anandkansagra thanks for the PR! You should also update the source terms (the `.pot` file) to reflect those source string changes.

**Comment by anandkansagra** [comment]
@Yenthe666 ,
I have changed `POT` file. Could you please look it out?

**Comment by Yenthe666** [comment]
Looks good, thanks! Now somebody from Odoo S.A. itself needs to review & merge it in :)

**Comment by sswapnesh** [comment]
@mart-e  Here is another one for v12.

**Comment by mart-e** [comment]
Merged with #29092

**Pull request closed without merging**
