### PR TITLE
[FIX] V14 URL's

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Map to right URL's

Current behavior before PR: Some URL's point to 13.0

Desired behavior after PR is merged: The URL's point to 14.0

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e quick & easy merge/fix. Would love the first outsider PR on V14 😆

**Comment by mart-e** [comment]
Technically, we should merge this on Wednesday as 11.0 is still supported and 14.0 not yet :wink: 
Well I guess nobody is going to complain for two days...
@robodoo r+

**Comment by AntoineVDV** [comment]
@Yenthe666 It looks like this PR introduces a mismatch in the version label of 14.0 in the version selector of the dev doc:

Screenshot_20200929_113240

**Comment by Yenthe666** [comment]
I guess that's because there are still other 13.0 references in the 14.0 code? 🤔

**Comment by AntoineVDV** [comment]
> I guess that's because there are still other 13.0 references in the 14.0 code?

Erratum, we already had this issue in 13.0 apparently: <https://web.archive.org/web/20200426185341/https://www.odoo.com/documentation/master/>

Sorry for the useless ping, we'll handle this cosmetic issue later on ;)

**Pull request closed without merging**
