### PR TITLE
[IMP] stock: add user right to apply

### PR DESCRIPTION
**Pull request by kasp-odoo**
Before this commit
==================
You need to be an admin to have the right to apply inventory adjustments.

After this commit
=================
With this commit, a user can also apply inventory adjustments.

TaskId: 3651040

### CODE REVIEW

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
@pedrobaeza I agree we will remove this part. As you want, if you have something ready you can share it. Otherwise we will manage it ourself

**Comment by pedrobaeza** [comment]
@amoyaux we don't have it yet, but if that can boost the patch, we can develop it.

**Pull request closed without merging**
