### PR TITLE
[FIX] l10n_be: readd 140,141 to the chart of accounts

### PR DESCRIPTION
**Pull request by agr-odoo**
After 95b74f4 reworked the BE CoA, the accounts "140000-Bénéfice
reporté" and "141000-Perte reportée" are missing in the chart of account.
Tose accounts are part of the minimal legal accounts needed and are also used
in the Belgian Balance sheet in the section "14 - Bénéfice (Perte) reporté(e)".

opw-2871547

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@william-andre

**Comment by agr-odoo** [comment]
@qdp-odoo

**Comment by agr-odoo** [comment]
@smetl

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
