### PR TITLE
[FIX] website_event: fix snippet sorting

### PR DESCRIPTION
**Pull request by switch87**
Description of the issue/feature this PR addresses:
Wrong sorting of event widget on website

Current behavior before PR:
Before this commit the dynamic event snippet sorts the events from further in the future to current, making it so that events in the near future are not in the spotlight.

Desired behavior after PR is merged:
After this commit the events are sorted as expected, with the earliest events first.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by switch87** [comment]
@pko-odoo can you please look at this fix? It's on your code from 2 years ago.

**Comment by switch87** [comment]
@seppedl

**Comment by thiryr** [comment]
Do you have any actual example of this?  ``order asc`` means earliest first for dates, and it seems to behave correctly on my side.

**Comment by switch87** [comment]
@thiryr as you say yourself asc is what should be expected. But as you can seet it's not ascending now.

The example is straight forward. Go to run it, latest 16, goto edit mode on website, put the events widget.

Result:
First event January 2024, then may 18 2023, then April 18 2023, ...
Expected result:
First the event that's nearest in the future, which would be at the moment January 13 2023

**Comment by thiryr** [comment]
Oh yeah my bad @switch87 , I'm dumb. This indeed seems like an issue and your fix works well :) 

Could you make sure to sign the cla, and rebase to the current head while you're at it?

@tde-banana-odoo I don't think a test makes too much sense here since it's a typo in static data, but maybe? Otherwise I don't think this needs much tweaking, seems straight-forward

**Comment by tde-banana-odoo** [comment]
Rephrased and rebased at https://github.com/odoo/odoo/pull/110268

**Comment by tde-banana-odoo** [comment]
Done at https://github.com/odoo/odoo/commit/de1dc9e888f3ffc59589f1fdd4e518638c35bca6

Thanks !

**Pull request closed without merging**
