### PR TITLE
[IMP] resource, hr: improve employees creation performance

### PR DESCRIPTION
**Pull request by Feyensv**
image
image
image

Enterprise PR: https://github.com/odoo/enterprise/pull/25664

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff

Nice :+1:

**Comment by Feyensv** [comment]
robodoo r+

**Comment by tivisse** [comment]
@robodoo retry

**Comment by tivisse** [comment]
@robodoo retry

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
