### PR TITLE
[IMP] logging: Add a log error if there is a 404 code in the message of werkzeug logger

### PR DESCRIPTION
**Pull request by moylop260**
Description of the issue/feature this PR addresses:
We have HTTP-404 error in the log but is not easy to identify because is a logger.info

Current behaviour before PR:
If you have a HTTP 404 error in your instance you see a `INFO` logger.

Desired behaviour after PR is merged:
If you have a HTTP 404 error in your instance you see a `ERROR` logger.

### CODE REVIEW

**Comment by moylop260** [comment]
Well, the result of this build is red because we have few errors of HTTP-404 in master branch:
```bash
2016-08-25 05:41:40,584 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:41:40] "GET /blog/our-blog-1/post/none HTTP/1.1" 404 -
2016-08-25 05:41:58,544 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:41:58] "GET /web_editor/static/src/img/drag_here.png HTTP/1.1" 404 -
2016-08-25 05:41:58,636 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:41:58] "GET /web_editor/static/src/img/drag_here.png HTTP/1.1" 404 -
2016-08-25 05:41:58,802 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:41:58] "GET /web_editor/static/src/img/drag_here.png HTTP/1.1" 404 -
2016-08-25 05:42:01,319 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:01] "GET /web_editor/static/src/img/drag_here.png HTTP/1.1" 404 -
2016-08-25 05:42:01,569 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:01] "GET /web_editor/static/src/img/drag_here.png HTTP/1.1" 404 -
2016-08-25 05:42:01,690 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:01] "GET /web_editor/static/src/img/drag_here.png HTTP/1.1" 404 -
2016-08-25 05:42:01,854 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:01] "GET /web_editor/static/src/img/drag_here.png HTTP/1.1" 404 -
2016-08-25 05:42:34,545 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:34] "GET /web/image?model=res.users&field=image_small&id=&unique=20160825053341 HTTP/1.1" 404 -
2016-08-25 05:42:36,438 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:36] "GET /web/image?model=res.users&field=image_small&id=&unique=20160825053341 HTTP/1.1" 404 -
2016-08-25 05:42:36,586 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:36] "GET /web/image?model=res.users&field=image_small&id=&unique=20160825054222 HTTP/1.1" 404 -
2016-08-25 05:42:36,840 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:36] "GET /web/image?model=res.users&field=image_small&id=&unique=20160825054222 HTTP/1.1" 404 -
2016-08-25 05:42:43,683 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:43] "GET /web/image?model=res.users&field=image_small&id=&unique=20160825053341 HTTP/1.1" 404 -
2016-08-25 05:42:43,687 21211 ERROR 167763-13289-e428a2-all openerp.netsvc: werzeurg has error 404: 127.0.0.1 - - [25/Aug/2016 05:42:43] "GET /web/image?model=res.users&field=image_small&id=&unique=20160825054222 HTTP/1.1" 404 -
```

Opening a url to test it: http://167731-master-b56979.runbot9.odoo.com/web_editor/static/src/img/drag_here.png the result is:
not found


Conclusion: This PR works and could help us to avoid the error above.

**Comment by moylop260** [comment]
FYI I found the following behaviour :
[IMAGE ALT TEXT](http://www.youtube.com/watch?v=L0PEhXLfZUI "Video Title")

I don't understand why the first time show error running `wkhtmltopdf` command and the second time works fine!

Using  `wget http://localhost:8069/website/static/src/css/website.css` and `wget http://localhost:8069/web/static/lib/bootstrap/css/bootstrap.css` directly work fine from first time (and second time too).

I saw the following log after webkit execution:
`2016-08-26 03:16:46,873 6131 INFO None openerp.http: Generating nondb routing`

Somebody knows if I need to add a parameter or configuration extra in order to avoid this error.

**Comment by moylop260** [comment]
Forget my last comment.
It's because I don't using `--db-filter=MY_DATABASE` to run tests, then the WSGI don't know how to get the information of database and fix it the first time calling [_dispatch_nodb()](https://github.com/odoo/odoo/blob/c578fb792c8fc48ebf1d0a5689d9201813e1004e/openerp/http.py#L1662)

NOTE: IMHO we should send the database parameter from `wkhtmltopdf` parameters but It's offtopic here.

**Comment by odony** [comment]
I'm not sure I agree with you that 404 responses deserve an ERROR log message in Odoo. 404 is a status code, not an error, and there are many normal reasons for seeing some in your logs:
 - browsers automatically trying well-known URLs that may not exist (/robots.txt, /favicon.ico, ...)
 - loading a resource that does not exist (e.g. the avatar field of an Odoo partner/user that has no value set returns a generic image with a 404 status, which is fine)
 - visitors mistyping an URL
 - links broken by whitespace or inside emails that end up only partial when clicked
 - crawlers trying to find well-known resources (php forums, etc.) to scan your website
 - etc.

These events do not necessarily deserve special handling. Typically in a web server log (think apache/nginx) they would end up in the "access" log, not in the "error" log.
And btw in the runbot results some of the errors should probably not be fixed.

Now if you're specifically looking into detecting 404 errors during tests, I suggest looking into runbot itself to change the test output post-processing using a module. But even then, a 404 does not necessarily indicate an error, and now you will find yourself having to use a `@mute_logger` decorator for the cases where a 404 *is* expected.
Not sure this is an improvement in the end... if a 404 is a symptom of a real test failure, there should be another test that fails, otherwise you're just not sure.

Thanks for the idea, though!

**Comment by moylop260** [comment]
Thanks for reply

**Pull request closed without merging**
