### PR TITLE
[FIX] control panel mobile

### PR DESCRIPTION
**Pull request by Arcasias**
This PR and its enterprise counterpart add back some missing DOM
attributes and CSS rules that made the mobile ControlPanel work.

Enterprise: https://github.com/odoo/enterprise/pull/28994

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Comment by Iucapad** [comment]
Any update on that PR? It has been approved but not yet merged @Arcasias

**Comment by aab-odoo** [comment]
@pparidans is working/will work on it, I think

**Comment by Xavier-Do** [comment]
should this be retargeted to 16.0  ?

**Comment by pparidans** [comment]
> should this be retargeted to 16.0 ?

No. Not currently. This PR need to be reevaluated first (one of my todos) as most issue should be already fixed in 16.0.

**Pull request closed without merging**
