### PR TITLE
Master l10n ro jao

### PR DESCRIPTION
**Pull request by jao-odoo**
Task : https://www.odoo.com/web#id=48668&view_type=form&model=project.task&action=333&active_id=131&menu_id=4720

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
@PCatinean This task is based on the work of @feketemihai in https://github.com/odoo/odoo/pull/22105.  Would be cool if you could ping someone who knows the Romanian accounting.

**Comment by feketemihai** [comment]
@jco-odoo I hope i will have some time in the next month to update it. Could be done also on version 13?

**Comment by jco-odoo** [comment]
@feketemihai We will be glad to update it for v13.

**Comment by PCatinean** [comment]
Nice that @feketemihai offers to handle it. If he does not get the chance to do it though I can find someone sure, just ping me.

**Comment by rgo-odoo** [comment]
work continues in #43095

**Pull request closed without merging**
