### PR TITLE
[FIX] account: matched move lines should be marked as reconciled

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fine-tuning of https://github.com/odoo/odoo/commit/c8c3aa96e18827c3c032540b92e95b27bbed0fc3.

**Description of the issue/feature this PR addresses:**

(I have a client that want to work with draft moves maintaining reconciled items). Thus, I hope this fine-tuning is accepted. In fact, this was what @william-andre said in https://github.com/odoo/odoo/pull/91306:

> The issue is that there a account.partial.reconcile records for it. So the fix is not the right one.

**Current behavior before PR:** The move state is checked instead of if there are matched lines.

**Desired behavior after PR is merged:** Don't check for the move state, but only check if the lines have matched lines.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Comment by MiquelRForgeFlow** [comment]
> This needs more investigation

Yeah, that test is weird.

**Comment by MiquelRForgeFlow** [comment]
@william-andre here is my investigation and a proper full fix.

Analysis of the problematic `test_orders_with_zero_valued_invoiced` test of point of_sale:

To have matched lines (partial reconciles records), a previous `reconcile()` has to be done. And to be able to do that, the pos order needs a pos payment. The key of the problematic test was that the `product0` has a lst_price = 0.0. Due to this price, no payment was created (fixed in `_process_payment_lines()` of `pos_order.py`). But also, once this fix is applied, another issue arises, which is having 2 move lines with 0 balance and 0 amount currency and thus unable to reconcile them. So another tricky fix is applied in `auto_reconcile_lines()` of `account_move.py`. I duplicated the test in order to show that these two fixes are not needed if we simply change the product by one with a non zero price.

But hey, can we say that is incorrect to have a product with 0€ price in the shop? I think no. For example, you may have a product template with a `list_price` = 5€ and then you may have a variant with `price_extra` = -5€ , thus this variant having `lst_price` = 0€. I don't don't know if this variant should be able to be paid by cash or bank or both. But just saying.

If you don't want those many fixes and only maintain the original one (the `_amount_residual()` one), then we should just have the test with the product with non zero price and delete the other one. Before this fix, the matched lines were not checked, only the state of the move which was "posted" and thus, those move lines were marked as reconciled although not having matched lines which is wrong.

**Comment by MiquelRForgeFlow** [comment]
@william-andre I separated this thing in different commits. Tell me which ones you accept and I delete the others.

**Comment by caburj** [comment]
Hi @MiquelRForgeFlow. May I ask you to include the test written in this https://github.com/odoo/odoo/pull/93189? In case it passes here, perhaps we can abandon the said PR.

cc @yelizariev

**Comment by MiquelRForgeFlow** [comment]
@caburj the test passed  🎉  :)

I will rebase and rewrite that commit.

**Comment by caburj** [comment]
@MiquelRForgeFlow Awesome! Let's keep the other PR open until this PR reaches v14. Thanks so much for this contribution. :)

@pedrambiria I guess this PR solves the customers' issues.

**Comment by MiquelRForgeFlow** [comment]
Hello! sorry to disturb you, but... is someone reviewing this? I remind you that I can modify the commits as you like.

**Comment by MiquelRForgeFlow** [comment]
@william-andre your suggestions helped to reduce the commits. Thanks, now it became simpler.

**Comment by william-andre** [comment]
@robodoo r+

**Comment by william-andre** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
