### PR TITLE
[10.0]Fix key error 'pricelist' on price_compute method.

### PR DESCRIPTION
**Pull request by javierjcf**
Because of the related issue: #24752

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't you better change the calls to this function to the correct argument?

**Comment by javierjcf** [comment]
Yes, maybe better to change in file parts/odoo/addons/product/models/product_pricelist.py the method _compute_price_rule(), changing the line:
**product.price_compute(rule.base)[product.id]**

For:
**price_type = rule.base if rule.base != 'pricelist' else 'pricelist_id'**
**product.price_compute(price_type)[product.id]**

But, if in other part of the code this function is called the same way, using rule.base, we'll get the error again.

If you think doing this way is better i change the PR.

**Comment by pedrobaeza** [comment]
Well, I let Odoo stuff to decide on this.

**Comment by tde-banana-odoo** [comment]
Hello,

I just tested in 10.0 with a pricelist based on another pricelist and used a POS. I had no traceback and prices seems correctly computed. Could you give me more details on how to reproduce the issue ?

Thanks,

**Comment by C3POdoo** [comment]
Dear @javierjcf,

Thank you for your contribution but the version 10.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
