### PR TITLE
[FIX] workaround setuptools >= 31 creating the odoo package before import odoo

### PR DESCRIPTION
**Pull request by sbidoul**
Description of the issue/feature this PR addresses:

```
$ odoo
Traceback (most recent call last):
  File "/home/sbi-local/.virtualenvs/odoo-10c/bin/odoo", line 17, in <module>
    odoo.cli.main()
AttributeError: 'module' object has no attribute 'cli'
```

The behaviour of `*-nspkg.pth` has changed slightly in `setuptools >= 31`.

The error is due to the `*-nspkg.pth` files creating a dummy odoo package before the python program starts, therefore making import odoo do nothing and preventing `odoo/__init__.py` from being properly executed.

This fixes https://github.com/acsone/setuptools-odoo/issues/10.

A more robust solution for version 11 would need to remove all code from `odoo/__init__.py`, possibly populating the `odoo` module during the startup sequence for backward compatibility.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sbidoul** [comment]
@sle-odoo @KangOl could you have a look at this one?

**Comment by mart-e** [comment]
LGTM but @sle-odoo could you confirm it is safe?

**Comment by Fenkiou** [comment]
@sle-odoo, any news/feedback on this ?

**Comment by sbidoul** [comment]
Closing as it apparently won't be merged...

People impacted by this issue can `pip install "odoo-autodiscover>=2.0.0b1"` which automatically applies the necessary work around.

**Comment by sle-odoo** [comment]
@d-fence

**Pull request closed without merging**
