### PR TITLE
fix name_search for multilang CoA

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Dear, 

`code`, `name` and `shortcut` are not translatable. I therefore do not see the point of this.

Regards,

**Comment by luc-demeyer** [comment]
@beledouxdenis 
Denis,
you cannot simply close this PR since your analysis is wrong.
The account.account,name field can be turned into a multilang field and this is the done e.g. the l10n_multilang module (part of the official addons !) as well as in several community modules.
Please reopen and merge.

**Comment by beledouxdenis** [comment]
Well, no description was provided. As no explanation was given, indeed, my analysis was wrong.

That said, I can now consider your pull request.

However, I do not understand why you do not simply pass the context directly.

Why:
```
context=context.get('lang') and {'lang':context['lang']}
```
instead of
```
context=context
```
Is there a specific reason ? Can you explain it ?

**Comment by luc-demeyer** [comment]
context=context is probably better but since Odoo dropped the context I was not sure about some (inherited) modules expecting an empty context, hence I made a fix that with less risk.

**Comment by beledouxdenis** [comment]
Well, there should no risk about that.

Any modules that potentially overrides `search` of `account.account` must take into account the fact sometimes the context is passed (as a `dict`), sometimes not (`None`). Anyway, `search` on `account.account` is done in a bunch of places (the web client, among others), with the context passed. If an override do not handle the context passed, it then already crashes in other places.

I therefore believe you can simply pass the context as it is :).

**Comment by luc-demeyer** [comment]
@beledouxdenis 
context now passed as is hence this one is ready for merge.

**Comment by beledouxdenis** [comment]
Thank you for your contribution :)

**Pull request closed without merging**
