### PR TITLE
11.0 improving requirements

### PR DESCRIPTION
**Pull request by dennybiasiolli**
#### Description of the issue/feature this PR addresses:

Improving requirements.txt in order to work when platform is 'win32' and python version is 3.7.x

#### Current behavior before PR:

Executing `pip install -r requirements.txt` the command line (git bash, but also cmd) returns a lot of errors, especially on `Pillow` package.
When we execute `odoo-bin` command, we receive other errors due to missing `psycopg2` and other packages.

#### Desired behavior after PR is merged:

With this PR we have a stable environment, allowing other win32+python3.7 users to setup their environment without headache 😄 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Ping @d-fence

**Comment by dennybiasiolli** [comment]
@d-fence I would suggest a `rebase-merge` in order to have a clean history of commits at the end of the current commit history, but feel free to pick the one you prefer

**Comment by d-fence** [comment]
I'm sorry, I only reviewed the diff but there are still problems with the commit messages.
May I ask you to squash the commits that modify requirements.txt into a single commit.
Also, the commit messages should follow the [guidelines ](https://www.odoo.com/documentation/13.0/reference/guidelines.html#tag-and-module-name)

For example:
[FIX] requirements: add compatibility with win32/python-3.7

In a ideal world, the CLA sign should be kept in a separated commit with a this kind of message:
[CLA] signature for Denny Biasiolli

When done, I will ask the robot for a rebase-ff

**Comment by dennybiasiolli** [comment]
@d-fence commits squashed, sorry for the commit messages, i fixed them too

**Comment by d-fence** [comment]
Nice, thanks

**Pull request closed without merging**
