### PR TITLE
[imp] account: add prepare method for invoice tax lines

### PR DESCRIPTION
**Pull request by adrienpeiffer**
See #12739 
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

This is needed by custom modules that add analytic dimensions.

### CODE REVIEW

**Comment by wtaferner** [comment]
@adrienpeiffer 
I guess it is forward-ported very soon, so no reason to submit it again imo.

**Comment by adrienpeiffer** [comment]
@wtaferner I need this one for my project so it was the occasion to submit this PR.

**Comment by wtaferner** [comment]
Sure, but it was already accepted in v9, so just merge it for your v10 branch and rebase when it was forward ported. But maybe I don't get your reason :-)

**Comment by adrienpeiffer** [comment]
Forward ported

**Pull request closed without merging**
