### PR TITLE
[FIX] base, l10n_at: address format and country states

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Follow-up of latest PR related to this topic #50652

**Current behavior before PR:**
Address format is not properly set for Austria and country states are missing for localized needs

**Desired behavior after PR is merged:**
Address format correctly defined and having the country states of Austria based on ISO 3166-2:AT

Info: @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@mart-e 
Here we go :-) Some more localization stuff from Austria.

**Comment by wtaferner** [comment]
@mart-e 
After successful runbot I will extract the pot and po file for German on runbot and add them afterwards, ok?

**Comment by nikiwaibel** [comment]
* i'd recommend to use the official german names, as it seems to be the standard in odoo/addons/base/data/res.country.state.csv and as it is the only offical way in ISO 3166-2:AT. if someone needs to translate them to english, fine, but the official and standard names are german.
* VAT should be changed to USt in odoo/addons/base/data/res_country_data.xml 

further notes:
* there are still many changes required, as the term "Mehrwertsteuer" is officially used in switzerland only. austria and germany use the term "Umsatzsteuer". see note on top of https://de.wikipedia.org/wiki/Umsatzsteuer
* in addition austria has more the just 10% and 20%. 13% is very well used for many things since 2016, 19% and 7% only in rare cases/regions.

**Comment by wtaferner** [comment]
@mart-e 
Ready to go, I missed that the state names are not translateable anymore and I additonaly fixed the VAT label.

@nikiwaibel 
One step at a time ;-) I fixed the vat label too, the rest is already there starting from 13.0.

**Comment by nikiwaibel** [comment]
another minor thing: https://definition-online.de/abkuerzung-umsatzsteuer/
--> no . (dot) after USt

**Comment by wtaferner** [comment]
@nikiwaibel 
Du bist ein ganz schöner i-Tüpfelreiter, aber da es im Kontext gut passt, kriegst Du deine USt ohne Punkt unabhängig von der Quelle, weil da könnten wir jetzt eine Diskussion lostreten :smiley: 

I am looking for your contributions on code level :wink:

**Comment by MiquelRForgeFlow** [comment]
why not put the country states on base module?

**Comment by mart-e** [comment]
@wtaferner thanks, could you just elaborate a bit the commit message? You give some info in the PR description that is worth being in the commit message too.

**Comment by wtaferner** [comment]
@mart-e 
Of course. Just elaborated the commit message to give more info about the why.
I hope I understood and did what you asked for :smiley: 

Let's merge it :wink:

**Comment by mart-e** [comment]
Thanks for the update !
@robodoo r+

**Pull request closed without merging**
