### PR TITLE
[REF] mail: `NotificationListItem`, review and simplify mixins 

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Part of the overall v16 SCSS optimization/restyle, task-2704984

This PR simplifies the mixins defined in `notification_list/notification_list_item.scss` and used in `ThreadPreview`, `ThreadNeedactionPreview`, `NotificationGroup` and `NotificationRequest`.

task-2838625

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hello @alexkuhn 👋 ,

I'm waiting for the merge of [PR#88073](https://github.com/odoo/odoo/pull/88073), which is needed for this one.
Otherwise, this PR is ready for review. As discussed, I have divided the review into four commits : [TMP]: 1 to 4.
After the review, we can combine them into one.
I have also added commits for other changes related to this revamp.

Can you take a look at this PR? Thanks 👍 

cc. @stefanorigano

**Review by alexkuhn — APPROVED** [review]
LGTM

**Comment by alexkuhn** [comment]
Don't forget to rebase for resolving conflicts

**Comment by Brieuc-brd** [comment]
> Don't forget to rebase for resolving conflicts

@alexkuhn, I did it ... but a few minutes too soon 😅 .
I'm waiting for 🟢  on runbot, then I'll make some last tests and I'll ping you for tech. review 👍

**Review by alexkuhn — APPROVED** [review]
@robodoo r+ rebase-ff

**Pull request closed without merging**
