### PR TITLE
[IMP] social_media, *: add TikTok to the social networks stored in DB

### PR DESCRIPTION
**Pull request by Guillaume-gdi**
*: website, website_blog, website_event, mass_mailing, mass_mailing_themes, website_mass_mailing

This PR adds the TikTok social network to the other social networks
stored in DB. Thus, users of the Website application will be able to
reference their TikTok page on their websites. This commit also updates
the different templates and the social media block to integrate this new
social network (in website and email marketing).

---

This commit adds TikTok to the already existing social networks in all
email marketing templates (droppable blocks and default mail templates).

task-3235451

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
venicemercury-china

**Comment by Guillaume-gdi** [comment]
@thiryr In the website application, the social networks presented by default are Facebook, Twitter, Linkedin, Youtube, Instagram and github. I see that on Email Marketing, only Facebook, Twitter, Linkedin and Instagram are presented, not Youtube or Github. I don't know the reason for this. If it's because we want to limit the default social networks in email marketing to 4, this needs to be discussed with the email marketing PO.

So @LNAodoo do you want me to add the TikTok icon to the email marketing templates ?

**Comment by Guillaume-gdi** [comment]
Response from LNA: Yes lets add TikTok to email marketing too :+1:

**Review by detrouxdev — COMMENTED** [review]
Overall good code and good changes 👍🏻 just two things:
- Is there any reason to leave TikTok out of the `supportedSocialMedia` regex done in `_findRelevantSocialMedia` ? I know the it ends up being found regardless, but seeing GitHub and LinkedIn being supported explicitly while it seems to me that they're in the same case as TikTok got me intrigued.
- I noticed a bug when updating Tiktok as a social link on Website and then trying to use one of the templates in mass_mailing. The TikTok link was never updated. Does this work on your side ? (To be fair, the other link would only update after I stopped and restarted the server, I don't know if it's an issue with template caching or on my side)

**Comment by Guillaume-gdi** [comment]
> Is there any reason to leave TikTok out of the supportedSocialMedia regex done in _findRelevantSocialMedia ?

I understand your point here. the function `_findRelevantSocialMedia` checks if the url match a DB social media, if not it checks if the URL matches an icon name. By thinking about it, we could remove of twitter, linkedin and github from `supportedSocialMedia` because the url is juste www.socialMediaName.com/something so the second part is capable to handle that already. So what do you prefer ? I add tiktok to `supportedSocialMedia` (but it's useless) or I remove twitter, linkedin and github from it as it is useless ? I suppose the second solution is the best one.

---
About your second point, indeed there is something strange... I did the following test on the runbot of this PR:
- Go to website and update the url of social media facebook an tiktok
- Go to email marketing, create a new mail template
- Drop a block with social medias
- Facebook and Tiktok have the old values
- Refresh the page and drop again a block with social medias
- Facebook has the updated url but not Tiktok

I will check what is going on here :thinking:

**Review by detrouxdev — CHANGES_REQUESTED** [review]
@Guillaume-gdi while testing one last time, I realised that `@odoo.official` is not the current Odoo account, so the links lead to a 404.

Could you update the links to the current Tiktok handle for the demo data? Thanks!

**Comment by Guillaume-gdi** [comment]
@detrouxdev Indeed it has been recently changed. It's now adapted :+1:

**Review by detrouxdev — APPROVED** [review]
@robodoo r+

**Comment by detrouxdev** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
