### PR TITLE
CLA signing

### PR DESCRIPTION
**Pull request by mymage**
CLA signing

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by seb-odoo** [comment]
@mart-e You might want to check this again, still open with r+/no ci.

**Comment by rdeodoo** [comment]
> @mart-e You might want to check this again, still open with r+/no ci.

**Comment by mart-e** [comment]
rebased, let's try again
@robodoo r+

**Pull request closed without merging**
