### PR TITLE
[IMP] sale_stock: Routes readonly after confirmation

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
**Description of the issue/feature this PR addresses:**
Routes in sale order line can be changed anytime. However if the Sales Order is already confirmed, the delivery will not be updated. This could cause confusion because:
-  Users expect changes when updating this value in confirmed sales orders
- It is confusing when reviewing past sales orders because the delivery order makes not sense to the route.

**Current behavior before PR:**
Users can change the route in sales order at anytime

**Desired behavior after PR is merged:**
The route can only bet set in draft and sent  status, because after that the deliveries are already created.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Ping  @sle-odoo, @dbo-odoo y @nim-odoo

**Comment by pedrobaeza** [comment]
@sle-odoo I think this one is important for avoiding false expectations. I would even say for current stable versions.

**Comment by MiquelRForgeFlow** [comment]
conflicts

**Comment by AaronHForgeFlow** [comment]
solved in 16.0

**Pull request closed without merging**
