### PR TITLE
[ADD] l10n_cl: add chilean company demo data

### PR DESCRIPTION
**Pull request by suv-bmya**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by suv-bmya** [comment]
@jco-odoo , here the PR to add the company demo data.

**Comment by ren-odoo** [comment]
HI @suv-bmya 

I did installed the module but no company was created for Chile: 
https://www.dropbox.com/s/wf3ag9oqgcyaf6h/chile_company.png?dl=0

Can you help me to take a look please?

@jco-odoo here is the PR in case you want to take a look.

**Comment by suv-bmya** [comment]
@ren-odoo , is it possible you don't use the last runbot? I've noticed the url is different and themodule is not installed in the last runbot ->

https://4879419-14-0.runbot50.odoo.com/web#action=35&model=ir.module.module&view_type=kanban&cids=&menu_id=5

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@ren-odoo I tested and it seems to work fine

**Pull request closed without merging**
