### PR TITLE
[FIX] account: wrong company for footer via anonymous portal

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**

As an invoice might be accessed via an access token and sudo is in place it was
wrongly displayed in multi company depending on which company OdooBot was
currently configured.

Make sure the company fits the invoice being displayed and reset after
rendering/creating the content. Very akward in case an invoice PDF is
downloaded/printed the first time as it will be mostly loaded from the
attachment the next time

**Current behavior before PR:**
Wrong footer might be rendered for an invoice depending of the OdooBot company set

**Desired behavior after PR is merged:**
Working as expected and using the correct footer based on the invoice (`company_id`)

Info: @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@mart-e @oco-odoo 
May I ask you to confirm/review and merge this or assign to someone who would do so?

Reproduction should be clear from the commit message and the code, but for the record

- Create an invoice for company B (multi company) and get the portal access url (access_token has no company set)
- Open the access url with an incognito session whereas OdooBot should be configured in company A
- Take a look into the footer where company A is displayed instead of company B to which the invoice belongs

**Comment by wtaferner** [comment]
@oco-odoo @mart-e @qdp-odoo @nle-odoo 
No one?

**Comment by oco-odoo** [comment]
Hi @wtaferner 

I just came back from holiday, that's why I'm replying so late. 

Though I understand your explanation of the issue I can't manage to reproduce it, neither locally or on runbot, so I must be missing something (or it has coincidentally been fixed, but it's unlikely). 

So, here is what I do:

- I have company 1 and company 2. Company 1 is the one with id 1. I define a distinct footer for each of them. 
- Logged on company 2, I create an invoice, validate it, and go to action -> share to get the portal link
- In a private window, I open the portal link

From your explanation, I get that I should see company 1's footer (as it's the bot user's company_id) instead of 2's, but I get the right one. Am I disregarding something ?

**Comment by wtaferner** [comment]
@oco-odoo 
Can you share with me the runbot instance you are/were trying to reproduce? 
I will take a look what you describe and try to reproduce with the prepared data myself accordingly and try to find the way how I was biten by this. At least I am pretty sure it is real and not just my imagination 😉

**Comment by oco-odoo** [comment]
@wtaferner Latest 12.0. Just re-did it now on https://9480768-12-0-all.runbot60.odoo.com/ . My shared invoice link ( https://9480768-12-0-all.runbot60.odoo.com/mail/view?model=account.invoice&res_id=9&access_token=731a7d3b-554a-4b2b-8508-f08a22b71c90 ) shows the value I defined for the second company, as expected.

**Comment by wtaferner** [comment]
@oco-odoo 
Thank you, much appreciated.
And finally sorry, but it was my bad...there is this multi company magic in the external/internal layout and I had for some reason used the `res_company` instead of `company` in my layout template.

https://github.com/odoo/odoo/blob/a1f4cc03bc4df556f9a832a91d47f1c3727ab115/addons/web/views/report_templates.xml#L364-L378

Not sure why we do so much logic in those stupid templates whereas it should orientate based on the document which is printed based on code instead of template logic, but yeah, let's call it errors of the past...

But as I am curious, it is obviously still an issue and potential pitfall in the future 😉 

https://github.com/odoo/odoo/blob/4628812ec9f2e60e9ef4d214b59ce0408d924544/addons/web/views/report_templates.xml#L492-L506

**Pull request closed without merging**
