### PR TITLE
[FIX] stock: if you run scheduler for one company must only assign moves linked to this company

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
If you run scheduler for one company must only assign moves linked to this company

@jco-odoo can you check this PR ?

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
With the security rules, I suspect this case will not happen too often, but it is better to be consistent of course.  But then we should do the same for the exception_moves?  @amoyaux @sle-odoo

**Comment by fmdl** [comment]
@jco-odoo but if it is made by the admin, there are no security rules.

**Comment by fmdl** [comment]
@jco-odoo ping

**Comment by jco-odoo** [comment]
@sle-odoo while you are checking prs...

**Comment by fmdl** [comment]
Close by https://github.com/odoo/odoo/pull/58537

**Pull request closed without merging**
