### PR TITLE
[IMP] project: support for archive column

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Task: https://www.odoo.com/web#id=22007&view_type=form&model=project.task&action=333&active_id=248&menu_id=4720

### CODE REVIEW

**Comment by dreispt** [comment]
@tde-banana-odoo Is this PR still valid?

**Comment by tde-banana-odoo** [comment]
Yes. Not a priority, but still valid.

**Comment by rdeodoo** [comment]
Hello @tde-banana-odoo I have seen the task being canceled 5 months ago, is this still valid?

**Comment by tde-banana-odoo** [comment]
It's not canceled, it is a wishlist. The great life cycle of Odoo will make it raise again one day, I promise it.

**Comment by hmo-odoo** [comment]
@tde-banana-odoo , web_kanban module is a dead. so this PR need renovation. 

can we close PR and delete branch ? We can restore branch after task become live.

**Comment by msh-odoo** [comment]
Archive/Unarchive column feature will be added again in Kanban with this PR: #23616

**Comment by dreispt** [comment]
@tde-banana-odoo should this be closed, then?

**Pull request closed without merging**
