### PR TITLE
[FIX] website_sale: all /shop URLs should't listed in sitemap when it restricted

### PR DESCRIPTION
**Pull request by kig-odoo**
Commit [1] introduced functionality to control the visibility of products for public users.

This commit ensures that sitemap.xml will not have categories and products URLs when shop restriction is activated.

[1]: 5bde2e42c8ec5e943a779ad4b3e1b7142f2d2fcf

### CODE REVIEW

**Comment by kig-odoo** [comment]
@chevalierv @Feyensv  let me know if you need any further information from my side.

**Comment by kig-odoo** [comment]
@chevalierv @Feyensv Any update on this PR?

**Comment by kig-odoo** [comment]
Hello @chevalierv @Feyensv ,

I understand you're working on something urgent, but can we review and merge this before the freeze? I'm confident this fix will be needed later.

**Comment by kig-odoo** [comment]
@chevalierv @Feyensv any news?

**Comment by kig-odoo** [comment]
Odoo 18 is out, yet the bug this PR fixes is still not merged. I'm honestly frustrated because this bug has serious consequences, and it's been unresolved for months. No one has even responded to my follow-up notes in the last 4 months. I've spent hours fixing this, and Odoo isn't going to paying me for it—but my goal is simply to help make Odoo a better product. It feels like my efforts are just hanging in the air. If you're too tied up, at least assign it to someone who can take a proper look. This can't just be left sitting any longer.

**Comment by chevalierv** [comment]
Hello @kig-odoo 

I'm sorry for not getting back to you sooner. I understand your frustration and assure you we did not forget your PR. As you highlight, we are focused on making Odoo 18 a great version, and we still have some bugs to fix before our great event - Odoo Experience. 

We decided to fix this bug in stable, considering it an important problem. Therefore, and as we didn't receive any tickets from clients for this bug, we focused on developing as many features as possible for Odoo 18. We created a PR ready to be merged in 17.4, which will be applied to 18 and master. You can follow the activity here: https://github.com/odoo/odoo/pull/176391

Thanks again for your help on this matter, and for making Odoo a better product every day!

Have a great day

**Comment by chevalierv** [comment]
Merged in https://github.com/odoo/odoo/pull/176391

**Comment by kig-odoo** [comment]
Thanks for the update. Looking forward to explore new odoo 18.0 :smile:

**Pull request closed without merging**
