### PR TITLE
Backport client command discovery optimization

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by dreispt** [comment]
Found a case where this fix is required in order for CLI commands to work: in a setup without `python-ldap` installed (common in sudo-less environments) trying to use a CLI command fails when the command discovery tries to import `auth_ldap`!

**Comment by antonylesuisse** [comment]
I did not finish this part, i was not sure about hardcoding the path '<module>/cli'. But the other solutions would require opening files instead of just a stat(). So i guess it's the way to go.

@mart-e @odony @KangOl ok with that ?

**Comment by dreispt** [comment]
@antonylesuisse Note that  for the we side you already have a [similar convention](https://github.com/odoo/odoo/blob/8.0/openerp/http.py#L1302) for `static`. So adding this one sounds reasonable for me.

**Comment by odony** [comment]
@dreispt @antonylesuisse looks fine to me as a convention. What about importing directly the <module>.cli package instead of the whole module?

**Comment by dreispt** [comment]
@odony I would rather not. 
This is meant to be a direct backport of the code in master (commit https://github.com/odoo/odoo/commit/4b387e73cb9cd051bd549e626b9255cf3bb5ea17).
And it could be that the cli commands depends on other components in the modules, so I think it's safer and less surprising to import  full module.

**Comment by antonylesuisse** [comment]
I already merged it a few days ago https://github.com/odoo/odoo/commit/e20cf77ce0546ac37dbfabd8c71a0ab33cedc3d7

**Comment by dreispt** [comment]
Thanks!

**Pull request closed without merging**
