### PR TITLE
[15.0][FIX] purchase_requisition: create RFQ from smart button don't send default currency from purchase agreement

### PR DESCRIPTION
**Pull request by Saran440**
**Description of the issue/feature this PR addresses:**

1. Create Purchase Agreement with multi currency (Example: Main currency is EUR)
2. Click smart button RFQs/Orders
Selection_019
3. Create > It will default currency in RFQ is main currency (EUR)
Selection_020

**Desired behavior after PR is merged:**

Default currency in RFQ will change following Purchase Agreement

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by niyasraphy — APPROVED** [review]
seems missed to update the smart button with this pr: https://github.com/odoo/odoo/pull/114117

**Comment by ticodoo** [comment]
Hello@Saran440 fix looks good to me, thanks! Before I r+ it, can you write your PR description in the commit message itself? Also the title of the commit can be improved:

[FIX] purchase_requisition: pass default currency for list created rfq

Please review https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#commit-message-header for how commit headers should ideally be written (can be more than 50 characters, but should ideally be less than the standard auto-wrap limit ~72 characters). It should be explaining what your commit does when applied, not it is fixing

**Comment by Saran440** [comment]
@niyasraphy  @ticodoo Thanks for guidelines and review. :)

**Comment by ticodoo** [comment]
Thanks for updating your commit :smiley: 

@robodoo r+

**Pull request closed without merging**
