### PR TITLE
[IMP] web: add icons to `odoo_ui_icons` font for text-wrapping styles

### PR DESCRIPTION
**Pull request by edi-odoo**
Add new icons allowing editor to choose how text should wrap around the 
image when adding a picture inside a paragraph.

task-3235798
Required by task-2909320

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Thanks @edi-odoo 👍 
I did a fast test and the proposed icons looks 2px shorter than the current ones (1px up, 1px down).
Is it a rendering issue or the icons are effectively smaller?
image

**Comment by edi-odoo** [comment]
> Thanks @edi-odoo 👍 I did a fast test and the proposed icons looks 2px shorter than the current ones (1px up, 1px down). Is it a rendering issue or the icons are effectively smaller? image

The icons are effectively slightly smaller to keep equal distance between the lines. I think if you compare with the view-list icon you'll see that they are ever so slightly bigger than that one. I initially based these on that icon which doesn't meet the top/bottom of the icons' height either.

**Comment by stefanorigano** [comment]
Test rendering with a 14px font-size too (=milk).

**Comment by edi-odoo** [comment]
> Test rendering with a 14px font-size too (=milk).

I couldn't find a solution for the icons to look crisp with 5 lines so I've reduced it to 4 which is much better.
On my Retina display, all the icons look crisp in both 13px and 14px. But on my non-Retina display, all the icons look blurry in 14px. See screenshot : 
Screenshot 2023-03-17 at 11 02 37

We may need to change something when we move to milk ? 
For now I'll push these changes to this repo and the design-assets repo.

**Review by stefanorigano — APPROVED** [review]
Thanks @edi-odoo 👍

**Comment by bouvyd** [comment]
@robodoo r+

**Pull request closed without merging**
