### PR TITLE
[IMP] pos_restaurant: floating orders in table selector

### PR DESCRIPTION
**Pull request by vlst-odoo**
In this commit we move the floating orders selector from the navbar to
the table selector in pos_restaurant.
In retail pos it remains in the navbar.
image

Task: 4091946

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by caburj — APPROVED** [review]
robodoo r+

**Comment by caburj** [comment]
robodoo r-

**Comment by caburj** [comment]
there is conflict.

**Comment by vlst-odoo** [comment]
> there is conflict.

i rebased

**Comment by caburj** [comment]
robodoo r+

**Comment by caburj** [comment]
robodoo rebase-ff

**Pull request closed without merging**
