### PR TITLE
[FIX] l10n_cn: Fixed traditional Chinese to Simplified Chinese

### PR DESCRIPTION
**Pull request by joray**
Description of the issue/feature this PR addresses:

Current behavior before PR:
The translation text is traditional Chinese
Desired behavior after PR is merged:
The translation text should be simplified Chinese

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by joray** [comment]
@oomsveta 
@epictete

**Comment by oomsveta** [comment]
Hello @joray, I'll forward-port changes from [your previous PR](https://github.com/odoo/odoo/pull/123402) to master soon, I just need to make sure of something first. Hopefully I'll do it tomorrow 🙂

**Comment by joray** [comment]
> Hello @joray, I'll forward-port changes from [your previous PR](https://github.com/odoo/odoo/pull/123402) to master soon, I just need to make sure of something first. Hopefully I'll do it tomorrow 🙂

@oomsveta Hi, it is different, now the corrected translation is a CSV file

**Comment by oomsveta** [comment]
robodoo r+

**Comment by oomsveta** [comment]
robodoo r-

**Comment by oomsveta** [comment]
@joray Thanks for the PR! The changes have been validated by the Chinese localisation product owner. I'll merge them, but first could you please write a proper commit message? thanks 🙂

**Comment by oomsveta** [comment]
Never mind; this will be updated with the forward-port of your previous changes. I close the PR, thank you for your involvement 🙂

**Pull request closed without merging**
