### PR TITLE
12.0 misc37 jke

### PR DESCRIPTION
**Pull request by JKE-be**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
robodoo r+ rebase-ff

thx

**Comment by JKE-be** [comment]
@robodoo  r+ rebase-ff

be kind for one time plz

**Comment by KangOl** [comment]
@robodoo retry

**Comment by d-fence** [comment]
@JKE-be I just checked the runbot logs and the status was sent to github, as expected.
On the other hand there was a timeout when github tried to notify the mergebot.
It happens from time to time, and we will try to fix that. Sorry for the inconvenience.
PS: I removed the "state = 'fail' if commiter == 'JKE-be' else 'success' " line

**Pull request closed without merging**
