### PR TITLE
[FIX] website_profile: responsive edit profile page

### PR DESCRIPTION
**Pull request by nd-dew**
- install website_profile
- open /profile/edit
- BUG: see content overflow in mobile

opw-4123897

### CODE REVIEW

**Comment by nd-dew** [comment]
https://github.com/user-attachments/assets/95d90977-c1f3-4b91-a01f-c56dde198ca2

**Review by nle-odoo — APPROVED** [review]
seems ok to me

I've never heard of max-content but it seems already used in odoo. If I understand correctly, we will set the min-width to the max intrinsic width of the content, so for example I get this with the current fix:

> 2024-09-05-145601_1873x322_scrot

but if the text or picture was larger, I get another size:

> 2024-09-05-145901_1874x628_scrot

I guess it could make sense, but it might be odd that the interface depends on length of text eg. in chinese the picture will probably be smaller than it is with the current fix, and the current fix is already a lot smaller than the original value (of 25% of width with col-3 (col12 is 100%)) that is this:

> 2024-09-05-145615_1877x457_scrot

Usually for mobile we would just uses separate classes and have things taking 100% in mobile. Eg replacing "col-3" by "col-12 col-sm-3" (or col-md-3) and "col-9" by "col-12 col-sm-3". But your way seems that it is ok too but is resizing the desktop avatar column to intrinsic size which was not the case before.

**Comment by nd-dew** [comment]
@nle-odoo thanks for having a look 

> Usually for mobile we would just uses separate classes and have things taking 100% in mobile.

Yeah that's soo much simpler ;)

**Comment by awa-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
