### PR TITLE
[FIX] base: allow reports header/footer RTL with LTR user

### PR DESCRIPTION
**Pull request by lade-odoo**
When selecting at least 10 SO with RTL language on the customer, the printing behavior
(the PDF produced) is inconsistent. By inconsistent, we mean some pages are completely
filled with buggy headers making the whole PDF corrupted (on a business point of view).

Step to reproduce the issue:
1. The customer/vendor on the PO, SO, RFQ has language set to Arabic
2. The user creating the document has language set to English (US)
3. Printing out 10+ documents
The resulting PDF document is inconsistent and contains headers issues (as previously stated).

Solution: The problem is that the headers/footers doesn't take into account the language
of the company (RTL or not). In fact, all the headers/footers of a batch print are contained into
a single HTML file (apparently, at the time, `wkhtmltopdf` did not support multiple headers/footers).
A Javascript script is used to select the appropriate header/footer for each page of the PDF. The issue
is that the CSS file used for these headers/footers is always a LTR CSS file. Moreover, with this design, it
is impossible to combine headers/footers in RTL and LTR into a single PDF file with multiple pages. The complete
solution would be to create a single header/footer file per page in the PDF report (`wkhtmltopdf` now supports this),
that way we can specify the language (RTL or LTR) for each of the page and have the perfect behavior. However,
this change cannot be applied into a stable version (requires changes in signature of methods, etc.), consequently,
the full solution will only be kept for `master`. A partial fix would be to use one language on the footer/header, this
would solve the issues when we only print headers/footers in RTL or LTR languages. The fix would not render a perfect
PDF if there is a mix between LTR and RTL in the PDF (only the layout of the header/footer would be non-perfect).
E.G.: in a mix PDF, the logo image would always be to the left side while it should be to the right side for RTL documents.
Nonetheless, this partial fix solve the inconsistent behavior described in the bug which is already an improvement and solve the issue on a business point of view.

opw-2734671

### CODE REVIEW

**Comment by MiniLau** [comment]
@fw-bot up to saas-15.3

**Review by nle-odoo — COMMENTED** [review]
looks good to me

so instead of the lang of the current user, we would use the lang of the last printed report (that could be for example the customer of the last report). in most use case we only print one report so in that case at least it would be an improvement.

b

**Review by nle-odoo — COMMENTED** [review]
looks good to me

As far as I understand, this should just change RTL/LTR direction of header/footer to the one of the last report that is being printed.

The lang on the body was added for a similar issue: dd94d06727911ad6a180ad965acee4c4f08e181a.

note: the commit title "[FIX] base: Error in print SO" is not very useful, if possible it would be better to speak about "report header/footer RTL with LTR user".

as noted: this could probably still fail when there is a mix of RTL and LTR records, but I have found no way to make it fail .

**Review by nle-odoo — APPROVED** [review]
robodoo r+

looks good to me, in the case of mixed document lang where there might still be an issue, we could still do something like printing records by batch of eg. in this case partners with same lang

in master this should be solved differently in https://github.com/odoo/odoo/pull/88913:
fw-bot up to saas-15.3

**Comment by nle-odoo** [comment]
@MiniLau there is a conflict with current 13.0 version (because of this new commit: 6055cb94a551b1515c00819d157137715dabd36c), the branch needs to be rebased and the conflict fixed by hand.

robodoo delegate+

**Comment by MiniLau** [comment]
@robodoo r+

**Pull request closed without merging**
