### PR TITLE
[FIX] account: bring back cumulated balance

### PR DESCRIPTION
**Pull request by william-andre**
The cumulated balance has been removed from the standard view [^1]
Since then it has been broken by a series of refactors of the ORM, making it impossible to add the field back to the view. [^2]
This commit is fixing this, keeping the field hidden by default, but can still be added via Studio or other means.

[task-3703749](https://www.odoo.com/web#id=3703749&model=project.task)

[^1]: https://github.com/odoo/odoo/commit/652292a4788f6aca978ed97682577024ba53d7d0

[^2]: https://github.com/odoo/odoo/commit/7d2baaa0c726a7b0dd4fe7226862f960c9c59b73 
https://github.com/odoo/odoo/commit/2a121a32a2c7a20163daba94ca7b621a6877a23e

### CODE REVIEW

**Review by Levizar — APPROVED** [review]
@robodoo r+

**Comment by william-andre** [comment]
@robodoo retry

**Comment by Levizar** [comment]
@william-andre `test_amls_order_with_matching_amount` is failing because of the PR.
@robodoo r-

**Comment by william-andre** [comment]
@Levizar had to rebase :pray:

**Comment by Levizar** [comment]
À TOI DE JOUER @robodoo r+ !

**Comment by Levizar** [comment]
@robodoo r+

**Pull request closed without merging**
