### PR TITLE
[CLA] Florian Bruhin

### PR DESCRIPTION
**Pull request by The-Compiler**

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

You are signing for the `git@` email address but making your commits with a `me@` email address so the verification still fails.
[Setting your email in Git](https://help.github.com/articles/setting-your-email-in-git/)

**Comment by The-Compiler** [comment]
Oh, fun. Actually my commit address is `git@` but I signed the CLA via the git web interface which used `me@`. I'll come back to this, I just have to check how I want to solve this, i.e. what implications it'd have if I started to commit with `me@` too.

**Comment by mart-e** [comment]
You can also sign for both email addresses :)

**Comment by The-Compiler** [comment]
Oh, that'd be nice - how do I do that? Do I just add a second `<name> <git_email> https://github.com/<login>` line?

**Comment by mart-e** [comment]
yes

**Comment by The-Compiler** [comment]
Thanks for the help - amended and pushed, seems to look good now!

**Comment by mart-e** [comment]
Thanks, merged at ccc2684

**Pull request closed without merging**
