### PR TITLE
[ADD] CLA Agreement

### PR DESCRIPTION
**Pull request by etobella**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
Regards

@robodoo r+

**Comment by seb-odoo** [comment]
@mart-e robodoo error here too, but the PR only has one commit?!

**Comment by mart-e** [comment]
@seb-odoo yep, we noticed, problem with @robodoo . @xmo-odoo is on it (probably)

**Comment by mart-e** [comment]
robodoo r+

**Pull request closed without merging**
