### PR TITLE
[IMP] web_editor: Update tooltips for save and discard buttons

### PR DESCRIPTION
**Pull request by visp-odoo**
This commit enhances the user experience by refining the tooltips for the "Discard" button and removes tooltip of "Save" button as it is not displayed correctly in the website. Moreover, it introduces a previously overlooked feature on the website: pressing "ESC" during website edit mode triggers a full-screen preview mode. To increase awareness and accessibility of this feature, the tooltip for the "Discard" button has been updated to "Tip: Esc to preview."

task-3624344

### CODE REVIEW

**Comment by bso-odoo** [comment]
@visp-odoo Hi, there is a conflict with the current master. Could you rebase this PR ?

**Comment by visp-odoo** [comment]
@bso-odoo the conflicts have been successfully addressed. :+1:

**Comment by bso-odoo** [comment]
@qsm-odoo LGTM

**Comment by qsm-odoo** [comment]
@robodoo delegate=bso-odoo 
@bso-odoo

**Comment by bso-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
