### PR TITLE
[IMP] l10n_pe: Clean the manifest, remove to-dos

### PR DESCRIPTION
**Pull request by fvz-odoo**
At present, the manifest for the base module in Peru contains two pending tasks that need further clarification. These to-dos have remained unresolved since the module's inception four years ago. However, with this recent commit, we have provided a clearer explanation of what the module offers and have addressed and resolved the pending to-dos.

Task id=3337432

### CODE REVIEW

**Comment by ren-odoo** [comment]
@fvz-odoo the name of the commit must follow this format: https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#commit-message-structure, can you take a look and update it pls. 

Thank you.

**Comment by fvz-odoo** [comment]
@ren-odoo done!

**Comment by Levizar** [comment]
Should I close this pr?

**Comment by fvz-odoo** [comment]
Hello @Levizar 

How about merging it? Or should I do something differently?

Cheers!

Fernando

**Review by Levizar — APPROVED** [review]
You're right, I didn't take the time to check if it was still like that in master but it seems that it is.

@robodoo r+

**Pull request closed without merging**
