### PR TITLE
[FIX] website_forum: show correct title on hover over accept answer

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Fix wrong title on hover

Current behavior before PR: When hovering over the icon to accept an answer on the forum it will show the text "Send answer":
image

Desired behavior after PR is merged:
The text says "Accept answer" as you're accepting an answer, not sending one.
image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@JKE-be for you 😉

**Comment by JKE-be** [comment]
robodoo r+

**Comment by nim-odoo** [comment]
@Yenthe666 in the future, I think it's better to keep a single commit for such modifications. There is no real need for a specific commit when exporting a single new translation term. Adding to that the merge commit from robodoo, that's 3 commits for a translation term... 

And by the way, I just noticed that what you did is likely to cause an issue when exporting the translation terms for `website_forum`. The terms are supposed to be in alphabetical order in the .pot file. If one exports the terms for `website_forum` and uses a proper tool to merge the translations (e.g. meld), he will likely not notice that "Accept answer" is already in the file, and add it again. If the same term is present twice in the pot file, that causes issues with Transifex.

Thanks.

**Comment by Yenthe666** [comment]
Hi @nim-odoo,

Yeah I've noticed so too yesterday, I was already planning on moving to one single commit for a PR in the future to prevent this. Thanks for notifying me.
As for the source term.. I didn't think about the order indeed, I guess I was a bit too fast with this PR. I never thought about the order for merging tools such as meld though.

Thanks for the headsup and pointers, I'll keep an eye out for them.

**Comment by JKE-be** [comment]
@nim-odoo 
I didn't see the 2 commits, just checked the diff that seems minimal, so I don't imagine 2 commit for it.

About meld, not sure that it is due to the coder, but more due to the tool ;)
But yes, if we can make it easy for all... next time...

**Comment by Yenthe666** [comment]
Yeah I'll keep an eye out for it, sorry guys.

**Comment by nim-odoo** [comment]
@JKE-be Here is what happens when you export the translations and compare to the existing ones:
```
~ $ diff Downloads/website_forum.pot src/odoo/addons/website_forum/i18n/website_forum.pot 
7c7
< "Project-Id-Version: Odoo Server 12.0\n"
---
> "Project-Id-Version: Odoo Server saas~11.5\n"
9,10c9,10
< "POT-Creation-Date: 2018-11-29 09:51+0000\n"
< "PO-Revision-Date: 2018-11-29 09:51+0000\n"
---
> "POT-Creation-Date: 2018-10-02 10:06+0000\n"
> "PO-Revision-Date: 2018-10-02 10:06+0000\n"
416,420d415
< #: model_terms:ir.ui.view,arch_db:website_forum.post_answers
< msgid "Accept answer"
< msgstr ""
< 
< #. module: website_forum
2479c2474
< msgid "Send answer"
---
> msgid "Accept answer"
```

In such a case, that's easy to see that there is a duplicate, so it's not a big deal. When you do the same in `account`, `website` or `mail`, it is a totally different story :) You'll see plenty of differences, so what one usually does in that case is to simply add the missing term in the pot file, and don't touch all other differences. If the term already exists, that can easily be missed.

I guess it's a matter of good practice:
- always export the translated terms along with any modification requiring it (so you don't get so many differences - spoiler: nobody does that when a string is removed)
- always compare the exported pot file with the existing one, do not modify by hand (so you add the term at the correct place)

But that's true that there is not easy way to do it at the moment... except overwrite completely the .pot file :)

**Comment by Yenthe666** [comment]
@nim-odoo thanks for the extra feedback. I've noticed that when I compare a newly generated `.pot` file with an existing one that the differences can be quite big (strings to remove, new strings, ...), all changes that are not related to my specific PR.
Should I then update all of them or? I guess the `.pot` files are just not cleaned up often.
Usually I do compare a new export with the original file and then manually place them in the right place - also looking at the order of the file - I basically was too fast with this one.
I guess this proves you should never make a 'quick' PR. 😉

**Pull request closed without merging**
