### PR TITLE
[IMP] mail: failure_reason should not be copied

### PR DESCRIPTION
**Pull request by sswapnesh**
The Failure Reason should not be copied for obvious reasons.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for the PR! What is this "obvious" reason :D ? Just to be annoying, but probably we could explain a bit more in commit message that copied mail will not be a sent one, and therefore not failed yet and without failure reason.

Once updated ping me !

Thanks,

**Comment by sswapnesh** [comment]
@tde-banana-odoo  Okay now ?
I could not add more clear message. 😉

**Comment by tde-banana-odoo** [comment]
Thanks @sswapnesh for updating !

@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
