### PR TITLE
[FIX] server.py: cron trigger in recovery

### PR DESCRIPTION
**Pull request by nim-odoo**
When setting up the PG replication, the slave is considered in recovery
mode. However, `LISTEN / NOTIFY` is not supported in this mode, leading
to an endless loop of crashes.

In recovery mode, we simply deactivate the feature.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
@Julien00859 Your input is welcome :)

**Review by Julien00859 — APPROVED** [review]
It's interesting that we can use Odoo when the cluster is in recovery mode, except for LISTEN/NOTIFY. I thought we were using LISTEN/NOTIFY for the long-polling but uses another mechanism.

LGTM but I don't know how to test your changes.

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by julienlegros** [comment]
> It's interesting that we can use Odoo when the cluster is in recovery mode, except for LISTEN/NOTIFY

Running Odoo in recovery mode is indeed not supported in any reasonable sense of the word. However it wasn't actively crashing on server start before the introduction of the cron trigger feature. We had workarounds in place since the 15.0 release, but it's much better if Odoo can at least start while Postgres is in recovery. That's the reason of this patch.

robodoo r+

**Pull request closed without merging**
