### PR TITLE
Hook to alter each newly-generated stock move line while exploding a phantom BoM

### PR DESCRIPTION
**Pull request by Nick-OpusVL**
This is to provide a way of recording the original product that was purchased and is triggering each line being on the delivery orders, so that detail can be printed on our customer's custom export documentation.

### CODE REVIEW

**Comment by jco-odoo** [comment]
It feels weird to use the same method for the service procurements and the stock moves and it seems a little bit 'overkill'.  The original product should still be on the related procurement, so maybe you can use that instead?  Also in case of purchases, the purchase_line_id should have the original product on it.

**Comment by Nick-OpusVL** [comment]
Thankyou @jco-odoo your suggestion to use `self.procurement_id.product_id` did the trick, so at least for now this patch probably isn't necessary.

I did however notice that the `self.procurement_id.bom_id` is not set on `stock.move`s that come from a phantom BoM, so I wasn't able to check definitively if the item came from a phantom BoM or not (I wanted to use `self.procurement_id.bom_id.type == 'phantom'`).   I ended up using a best-guess algorithm of `self.procurement_id and self.procurement_id.product_id != self.product_id`.

I'm not sure whether `self.procurement_id.bom_id` being null in this case constitutes a bug and therefore I should raise a new issue about it.

Thanks again,

Nick

**Comment by jco-odoo** [comment]
The bom_id was meant for real production orders as far as I know.  Maybe
you could check if self.procurement_id.product_id has a phantom bom.

**Comment by Nick-OpusVL** [comment]
@jco-odoo I was a little worried about doing that product_id has 0-* bills of material (and I'm still not sure why that is the case) - do you anticipate there being any problem if there are more than one BoM for that product but there's a mismatch between them on whether they're phantom or not?

**Comment by Nick-OpusVL** [comment]
@jco-odoo   We've had a discussion and don't see multiple bills of materials being a problem in our scenario, so I'm happy to use your suggestion 'check if self.procurement_id.product_id has a phantom bom'.

So this pull request isn't needed by us any more.

Thank you for your help.

**Pull request closed without merging**
