### PR TITLE
[IMP] event: Store located dates

### PR DESCRIPTION
**Pull request by yajo**
With this patch, we are able now to search by the located date field,
and recomputation is only done when actually needed.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Sorry but the computation is done based on the context. The result will be different from one user to another. It can not be stored then.

https://github.com/odoo/odoo/blob/9cc39b77fcb3e5d292f037226417e1155d17edf2/addons/event/models/event.py#L208-L211

**Comment by pedrobaeza** [comment]
@mart-e I don't see any context based computation (there's only an extra context passed to the function call). Are you sure?

**Comment by Yajo** [comment]
No, he's right. The user-dependant formatting is here: https://github.com/odoo/odoo/blob/9cc39b77fcb3e5d292f037226417e1155d17edf2/addons/mail/models/mail_template.py#L45

**Comment by pedrobaeza** [comment]
OK, I see.

**Pull request closed without merging**
