### PR TITLE
[FIX] project: fix various issues

### PR DESCRIPTION
**Pull request by ppr-odoo**
- Rename the 'assigned to' into 'assignees'
 - Disable opening form view from the list view

task-2645891

### CODE REVIEW

**Review by tlibioulle — CHANGES_REQUESTED** [review]
LGTM but we can also go further and reword 'Assigned to' to 'Assignees', here :

https://github.com/odoo/odoo/blob/saas-14.5/addons%2Fproject%2Fviews%2Fproject_portal_templates.xml#L212

and there :

https://github.com/odoo/odoo/blob/saas-14.5/addons%2Fproject%2Fviews%2Fproject_sharing_views.xml#L226

Also, you should use [FIX] rather than [IMP] in the commit message, many thanks :)

**Comment by ppr-odoo** [comment]
@tlibioulle changes done
Thanks

**Review by tlibioulle — CHANGES_REQUESTED** [review]
Thanks for the changes.

May I also ask you to add disable_linking in the graph and pivot view or the Tasks Analysis report ? As discussed here : #76639 

Thanks in advance !

**Review by tlibioulle — APPROVED** [review]

**Review by IT-Ideas — COMMENTED** [review]
Can you please ensure that PR numbers are mentioned into the commits when there is more than 1 commit in a PR?
Also the PR message should be filed with a summary (not all the detail) explaining the purpose of the PR.

Thanks for your work! 🙂

**Comment by IT-Ideas** [comment]
@ppr-odoo I just updated the PR and commit messages so that you know next time exactly what we would like to get 🙂 
Thanks again for your work and availability, we really appreciate.

**Comment by IT-Ideas** [comment]
@robodoo rebase-ff r+

**Comment by IT-Ideas** [comment]
@robodoo r+

**Pull request closed without merging**
