### PR TITLE
[8.0] HR Recruitment

### PR DESCRIPTION
**Pull request by adrienpeiffer**
- [FIX] Hr Job : Set name field translatable
- [IMP] Hr job: Add a notebook with description and requirements fields and remove invisible attrs on these fields
- [FIX] Hr Job: Show address doesn't work without always_reload option

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
OPW 648623

**Comment by beledouxdenis** [comment]
Regarding the change in `addons/hr/hr_view.xml`:
As you said, this is an improvement, and we do not do view improvements within stable release.

Regarding `[FIX] Hr Job: Show address doesn't work without always_reload option`, I will check, but it should be OK.

Regarding `[FIX] Hr Job : Set name field translatable`, it looks like a feature to me, but It should be acceptable.

Remove the changes in `addons/hr/hr_view.xml`, and I will then consider merging this pull request in stable 8.0.

Regards,

**Comment by adrienpeiffer** [comment]
Hi Denis,

I understand for ```addons/hr/hr_view.xml```. But can you tell me why description and requirement fields are hidden in open state. I think it's important to fill them before publishing the offer. What do you think ?

For the translatable field, I think it's important to propose multilang offer.

Thanks !

**Comment by beledouxdenis** [comment]
> I think it's important to fill them before publishing the offer. What do you think ?

The recruitment state and publishing on the website are two separated thing.

The job description is meant to be visible only when the recruitment is going on. Once in state `recruit`, the job description input is available and you can fill it. Once filled in, you can then hit the publish button to make it visible on the website.

> For the translatable field, I think it's important to propose multilang offer.
Well, you may think so, but it's like that since the release of 8.0, a year ago, and nobody complained: That makes think nobody needed it so far, and therefore we can consider it's not that asked by users.

This is why I qualified this as acceptable: We could do so, but this isn't that needed.

**Comment by adrienpeiffer** [comment]
>The recruitment state and publishing on the website are two separated thing.

>The job description is meant to be visible only when the recruitment is going on. Once in state recruit, >the job description input is available and you can fill it. Once filled in, you can then hit the publish button >to make it visible on the website.

Yes ok, but i don't understand why it's not allow before recruit state

**Comment by beledouxdenis** [comment]
Well, these kind of things are designed by the usability team, and they definitely did it for a reason.

Why we do not accept these kind of behavior changes in stable release.
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

**Comment by beledouxdenis** [comment]
If you really want it in your use case, just do this in an custom inherited view.

**Comment by adrienpeiffer** [comment]
Ok, I removed the commit

Thanks !

**Comment by adrienpeiffer** [comment]
Thanks !

**Pull request closed without merging**
