### PR TITLE
[12.0][FIX] account: Show full name in vendor_display_name

### PR DESCRIPTION
**Pull request by pedrobaeza**
Steps to reproduce:

- Create a partner called "Company X".
- Create a partner contact "Child" inside "Company X", with full name "Company X, Child".
- Create a vendor bill for "Company X, Child".

Current behavior:

On vendor list, you see as vendor "Child".

Expected behavior:

On vendor list, you see as vendor "Company X, Child".

cc @Tecnativa TT23010

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi @oco-odoo @qdp-odoo. I hope all of you are well on that side. Can you please check this easy one?

**Comment by oco-odoo** [comment]
@nim-odoo This computed field is stored, so changing it in stable will create inconsistencies between the data displayed on different invoices. Also, even though it's super small, there is a way of looking at it as a change of behavior. Or we can also consider it's nearly nothing, and it's more correct anyway. What do you think? Stable or ot stable? ^^

@pedrobaeza For now, we survive ! Hope all is well for you too :)

**Comment by pedrobaeza** [comment]
Yes, although there's the risk of different vendor names on old ones, I think it's good that from now, the name is correct.

**Comment by pedrobaeza** [comment]
@nim-odoo @oco-odoo any final call to this?

**Comment by pedrobaeza** [comment]
@nim-odoo @oco-odoo please tell me anything

**Comment by oco-odoo** [comment]
@pedrobaeza I discussed it with nim. As I suspected, this is still to be considered as a change of behavior, and should hence be done in master rather than in a stable version. Could you retarget the PR ? :)

**Comment by pedrobaeza** [comment]
I can retarget the PR due to the fwbot divergences, so I need to apply it directly over a master rebase. I'll do it later. It's a pity to have 2 versions with this annoying behavior though...

**Comment by pedrobaeza** [comment]
I see this fixed in master, so closing.

**Pull request closed without merging**
