### PR TITLE
[FIX] purchase: incorrect quote character in ES translation

### PR DESCRIPTION
**Pull request by nim-odoo**
opw-2394994

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by nim-odoo** [comment]
@pedrobaeza @mart-e Would any of you could validate my correction on Transifex? Thanks.

**Review by pedrobaeza — APPROVED** [review]
Yes, thanks. I reviewed this due to an issue in the issue tracker and I didn't see in Transifex such character. It's weird...

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
