### PR TITLE
Update initos.md

### PR DESCRIPTION
**Pull request by OSevangelist**
Added Florian Kantelberg to our team of contributors

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by OSevangelist** [comment]
I don't know why the checks are complaining but this file is definitely formatted utf-8

**Comment by mart-e** [comment]
Hi,

It is failing because the code in your master branch is quite outdated. Your CLA may be in UTF8 but other ones in your master are not, making the test fail.
If you rebase your master to be up to date with the current odoo one, it should work fine.

**Comment by OSevangelist** [comment]
Ok i kind of was already thinking about that but thanks for clarifying, i will check back with the team how we can fix that fast. Thanks for the hint @mart-e

**Comment by mart-e** [comment]
Now the test succeeds :+1: 
where do you want this to be merged by the way?
You have made the PR for master, but we can accept it in the lowest branch you want to contribute to. So if @fkantelberg wish to make a contribution in a stable version, I can merge it there. If nothing planned, this is fine :)

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it has been integrated into Odoo at revision 5a53e5b8e9aed48d579471fd64ca6d7eb378bb73.
Future pull requests made on odoo will be validated by the runbot.
Regards

**Comment by OSevangelist** [comment]
@mart-e hi Marti unfortunately this has been added to master now but could you please pull the change for v8.0 and all later versions as we plan to contribute to all newer versions including 8.0

**Comment by OSevangelist** [comment]
yes that would be great. Thanks

**Pull request closed without merging**
