### PR TITLE
[IMP] l10n_it_edi: added payment information in electronic invoice.

### PR DESCRIPTION
**Pull request by hpr-odoo**
task: 1948158

Description of the issue/feature this PR addresses:

Current behavior before PR: payment detail is not in electronic invoice

Desired behavior after PR is merged: payment detail is added

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by rdeodoo** [comment]
Hi @jco-odoo  this one is stucked (red runbot)

**Comment by jco-odoo** [comment]
Thank @rdeodoo   It is quite an important one.

**Comment by jco-odoo** [comment]
@robodoo retry

**Comment by jco-odoo** [comment]
@Xavier-Do @d-fence Could you give me an idea about why I don't get the CI label even when the rebuild is green?

**Comment by Xavier-Do** [comment]
This could be linked to the new split config but I don't think so, maybe a lost message between github and mergebot I just tried to rebuild to test that.

Anyway, your pr is quite old, you should rebase your branch.

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
