### PR TITLE
[FIX] Invalid escape character in some modules

### PR DESCRIPTION
**Pull request by kmagusiak**
Description of the issue/feature this PR addresses:
Strings written in python as '\w' should have a raw (r) prefix so that python does not try to interpret the backslash.

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by william-andre — COMMENTED** [review]
Hello, thanks for the PR!

As these are only warnings, and changing it might break something (like other escaped sequences) I think it would be safer to only do it in `master`, unless you saw a real bug?
So please retarget the PR to be safe in stable versions

In any case, please follow our guidelines for the commit title and message format:
https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#commit-message-structure

**Comment by kmagusiak** [comment]
> Hello, thanks for the PR!
> 
> As these are only warnings, and changing it might break something (like other escaped sequences) I think it would be safer to only do it in `master`, unless you saw a real bug? So please retarget the PR to be safe in stable versions
> 
> In any case, please follow our guidelines for the commit title and message format: https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#commit-message-structure

Hello,

It may not break anything because the strings are interpreted exactly the same, just python and other tools stop complain about escaping.
As it was in multiple addons, I did not know what module to put in the title of the commit.

Best regards

**Comment by kmagusiak** [comment]
I've updated the commit message.
I've added the r prefix only in regexes where it was missing, there was some code like '\s' which should have either been r's' or '\\s'.

**Comment by william-andre** [comment]
It looks like you need to rebase because of a new CI added for compatibility: https://runbot.odoo.com/runbot/build/57273585
It has been fixed in the meantime

**Comment by kmagusiak** [comment]
Rebased and the build passes.

**Review by william-andre — APPROVED** [review]
Let's move with this, but it would really be better to target master in the future :wink:
@robodoo r+

**Pull request closed without merging**
