### PR TITLE
[IMP] survey stages states

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@tde-banana-odoo and @Feyensv I just saw the PR about the survey stage too. Does this mean ALL states on ALL models will become predefined in selections again? Same for subscriptions etc?

**Comment by tde-banana-odoo** [comment]
Nope, only surveys. We consider a survey to be draft (under building), live or done (cannot be answered anymore). Stages are more confusing than really helping for surveys. Other models are untouched.

**Comment by Yenthe666** [comment]
Phew, okay thanks for clarifying.

**Comment by tde-banana-odoo** [comment]
Maybe someday we will revert to pre saas-2, but it is still not planned :smiling_imp:

**Pull request closed without merging**
