### PR TITLE
[I18N] *: re-export pots

### PR DESCRIPTION
**Pull request by ticodoo**
Some pot files were out of date, at least 1 had a duplicate msgid in it

Some modules weren't translated

Note that dead pot files (and their associated .po files) were not removed in this PR because :sloth: and removing them doesn't add any value

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ticodoo** [comment]
@robodoo rebase-ff

**Comment by ticodoo** [comment]
@robodoo fw=no

**Review by oomsveta — APPROVED** [review]
@ticodoo need rebase; LGTM otherwise 👍

**Comment by ticodoo** [comment]
@robodoo r+

**Pull request closed without merging**
