### PR TITLE
8.0 sale demo with taxe

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't this going to change the values expected in tests (total amount, total with taxes...)?

**Comment by damdam-s** [comment]
Here, I only modify records coming from sale_demo.xml
No impacts on tests

**Comment by pedrobaeza** [comment]
I'm not sure about that, because tests use demo data, but let's wait for the runbot result.

**Comment by nim-odoo** [comment]
Hello,

Thanks you for your contribution. However, we try to keep the changes in a stable version as limited as possible. We accept fixes, and on an exceptional basis some improvements or refactoring if we think they can bring an added value to the product. Changing demo data, although interesting, doesn't really bring any added value. Moreover, tests from custom modules might rely on these demo data. Therefore, we cannot accept your PR.

Regards,

**Comment by lepistone** [comment]
Thanks for the review @nim-odoo. There is a specific reason to do that: we have a little OCA module that  puts a condition on the validation of invoices (the presence of taxes, specifically).

However, the demo data of `sale` creates **and validates** an invoice without taxes. That makes our module not installable with `sale` and demo data, and we do that in our CI. Do you see another way around this problem?

Thanks!

**Comment by pedrobaeza** [comment]
What about by-passing the constraint on that specific data?

**Pull request closed without merging**
