### PR TITLE
[master] ignore canceled order lines

### PR DESCRIPTION
**Pull request by gurneyalex**
port #6036 to master

### CODE REVIEW

**Comment by odony** [comment]
Thanks, but is there any difference in this patch vs #6036, or is it just a retarget/cherry-pick?
As a general rule we prefer to avoid any kind of PR duplication, since we always forward-port or cherry-pick the commits depending on the outcome of the main PR ;-)

**Comment by antonylesuisse** [comment]
Duplicate of  #6036

**Comment by gurneyalex** [comment]
@odony I know PR merged in 8.0 end up in master. It was not clear to me that you were doing the porting work for PRs not accepted in 8.0. 

I'm closing #6087 as it is in a similar fashion a forward port of #6038 to master.

**Comment by odony** [comment]
@gurneyalex When "porting" means "cherry-picking", we'll do it directly. If there's more work we might ask the author to redo a proper PR on master indeed.

**Comment by gurneyalex** [comment]
@odony: in this specific case the rebase had conflicts and required (trivial) manual fixing.

**Pull request closed without merging**
