### PR TITLE
[FIX] sale: protect SO if done

### PR DESCRIPTION
**Pull request by nim-odoo**
Prevent the modification of the SO line if the SO is locked.

opw-803439

### CODE REVIEW

**Comment by gdgellatly** [comment]
@nim-odoo Introducing a behaviour change in stable that has existed for at least 8 years is a bit of a surprise.  Lucky I read these reports and can work around it, however this behaviour has been present since v5 and never been an issue, so was surprised it needs doing now.  

There are good reasons (at least for some) to modify a locked, but not yet invoiced sales order price.

Create draft invoice, see the price is wrong, or want to change the price for any reason, now you want invoice price and sale to match (much cleaner for reporting) is one example.

Any business with really complex/contract pricing generally needs to modify pricing on some orders, often long after they are shipped/manufactured etc and usually on the invoice (which we then write back to the sale).

I'm assuming this is forward ported to v11.  I have a couple of popular public modules for years that depend on existing functionality.

**Comment by wtaferner** [comment]
@gdgellatly 
I think @nim-odoo might have missed that the **unlock order as a user is only available in v11 again** and I agree with you that there are reasons to change some of the fields, but basically I think the fix is not that bad as there is an inheritable method you can easily adapt to. So, it can be indeed a bit problematic in terms of changed behavior in v10 b/c of the little miss in user possibilities as it is now.

**Suggestion**: How about checking for the ```invoice_status``` as well to really protect the fields? This would help Graeme and it would be finally very clean, right?

What do you both think?

**As a side note:**
Blaming Nicolas to break some behavior (actually every fix is a change in behavior) **without a suggestion how to improve or doing better (and I know you are capable of this)** is the salt which is making life hard to fix anything in stable IMHO and it is already difficult to fix bugs or wrong assumptions or even worse debugging blockers in (even) very young stable versions. 

As always your reaction is understandable, but I believe it is better to get the core right instead of having millions of workarounds and forked "bugfixes" or modules fixing some stuff which you need to think of in the next version you are going to use...easy if you are a single company (in case you are not a maniac customizing almost everything b/c someone is asking for it without a strong focus to stay close to the core), but if you have multiple instances and needs it is getting nasty and very work intensive (but yeah, that's the way it works in terms of policies I guess)

**Disclaimer:** it was not my issue, so I am kind of neutral versus the change itself here :-)

**Comment by gdgellatly** [comment]
@wtaferner 

> Lucky I read these reports and can work around it.

My point was more about quietly making such a change in stable to such longstanding behavior (even if you believe it is a bug, I think after 8 years, thats called a feature) and working out what versions of my modules needed updating.  I wasn't asking for it to be changed.

**Comment by wtaferner** [comment]
@gdgellatly 
Not sure if it does make a difference as it is critics anyway and will only make the wall bigger behind bug fixing or change is trapped and Odoo SA is hiding, but anyway, you have a point and it should be handled a bit better that it is finally no change in behavior at all (which is possible in this case I think).

The versions should be normally clear as all fixes are forward-ported except it is documented in the code inline afaik, but maybe you did not know that so far. 

Have a great day and please ask for a change if something seems wrong or at least for a proper explanation as it will save time and money for a lot of people in the end, especially if you have a valid point and maybe even a good suggestion to build on :-)

**Comment by nim-odoo** [comment]
> P.S.: I just saw that a locked order line in v10 is not editable at all via the UI, so it is really just to protect against modules trying to write the order line in a locked state...

Yeah, that's kind of the whole point of this PR: make the UI and the business logic consistent. There is no change in behavior _per se_ since the modification of a locked SO is anyway prevented in the UI (at least since v7). However yes, that does impact third-party modules that would use this "feature". Therefore I added the possibility to override the list of fields, so it's easy to deactivate.

> My point was more about quietly making such a change in stable to such longstanding behavior

If I wanted to do it silently, I wouldn't create a PR for every fix I make.

> There are good reasons (at least for some) to modify a locked, but not yet invoiced sales order price.

There are good reasons to prevent the modification of a locked SO: the edition by several users at the same time (which is a global issue on many objects, but this is another topic of discussion). In a company with numerous users, this is a major problem. At this point, there is no mechanism to let the user know that the object has been modified during his editing process. In the past, workflows could mitigate this problem. Now, we often rely solely on the UI as a safeguard, which a complete non-sense IMHO.

**Comment by wtaferner** [comment]
> Now, we often rely solely on the UI as a safeguard, which a complete non-sense IMHO.

Word as long as you give the needed methods to inherit which you did ;-)

By the way, as you put a blocker which is never reaching a user in stable, so most likely will only block third party modules user/devs, it would be good to be more precise which fields were blocking by communicating in the ```UserError``` and maybe also give some technical information like the introduced method in order to fix it in case unwanted (which should be clear in the code but still the precision I sometimes miss almost everywhere) and of course having a test would be great (as here it is easy to add one I guess). So much about my good intentions to get the best out of this PR ;-) 

Have a great start into the week.

**Comment by gdgellatly** [comment]
@nim-odoo OK I see your point now, if a user locks the SO while another user is editing this fix nearly makes sense.  

I agree on all the fields except the selection of price_unit seems strange.

Why is it in there when for example discount is not?  They both do essentially the same thing, which is modify price_subtotal.

There are also other uses of this "feature" that Odoo promotes as the way to modify otherwise unmodifiable data (e.g. Export then import to change chart codes as an example) which can have far worse consequences (e.g. a validated and paid invoice can have its total changed just via import) so hence my surprise that a relatively benign use of it was the target for a fix in a stable release.

**Pull request merged**
