### PR TITLE
[FIX] mail, im_livechat: crash when uploading file to temporary thread 

### PR DESCRIPTION
**Pull request by tsm-odoo**
Before this PR, uploading a file to a temporary thread would lead to
errors because the thread only exists locally. This PR ensures the
thread is saved on the server before uploading like it's done when a
message is posted.

This PR adapts the attachment upload service to rely on models instead
of components:
- Service should not be coupled to views
- Thread is updated when calling `uploadFile` so the hook passed to this
function is outdated and we cannot access the new thread hook (it's
not even mounted yet).

Steps to reproduce the issue:
- Log in as admin
- Go to the live chat support page
- Open a chat
- Click on upload file and upload one
- Crash occurs

https://github.com/odoo/enterprise/pull/60165

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]

**Review by alexkuhn — APPROVED** [review]
@robodoo delegate+

**Comment by tsm-odoo** [comment]
@robodoo r+

**Comment by tsm-odoo** [comment]
@robodoo r- 

Should duplicate overrides as well

**Comment by tsm-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
