### PR TITLE
[FIX] mail: normalized when formatting email_to / email_cc

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
When preparing final outgoing email, partner email is normalized. We take their formatted email, which is their name and their normalized email. However email_to and email_cc are taken from input using 'email_split(_and_format)', which finds emails but do not format them.

This leads to incoherent behavior as most emails are normalized as we generally always use partners, but not all. In this commit we now split, normalize and format email_to and email_cc in outgoing emails.

This fixes a first issue where name are lost if a formatted email was entered in email_cc field. Only address was kept, now the name is correctly found and put back.

This also fixes an issue for validated email detection, in order to compare normalized emails. This was introduced at odoo/odoo#185793 and may skip valid emails entered in email_to or email_cc.

This commit backports a tool introduced at odoo/odoo@dd4709e579841672b0c2a57d5f2941f3ce770801 which aims at allowing a quick convert from a string holding emails to a list of nicely formatted emails, using normalize version of email addresses. This is the standard we use in most flows.

Task-4376876
Followup of task-3704658

### CODE REVIEW

**Comment by Abridbus** [comment]
Hello!

For now, I can confirm it work for the totp issue reported here: 4356871

Steps to reproduce w/o fix:
1/ Fresh db 16.0 with CRM and totp apps installed 
2/ Add 1 MAD and ICP for 2FA: ('auth_totp.policy' : 'all_required' )
3/ Create user jo@jo.com (don't modify email add of the linked partner)
4/ Invit him to activate 2FA authentication, log in with jo@jo.com and receive one of the 2FA authentication code 
  -> `Mail with ID 5 and Message-Id '<391219144461602.1733217289.180823087692261-openerp-6-res.users@localhost>' successfully sent`
5/ Modify the email add of the linked partner to JO@jo.com
6/ Try to log in with jo@jo.com. Following error is logged:
  -> `Ignoring invalid recipients for mail.mail <344397096834636.1733217323.221683263778687-openerp-6-res.users@localhost>`

With the fix:
5/ Keep partner email to JO@jo.com
6/ Try to log in with jo@jo.com. Following error is logged:
  -> `Mail with ID 10 and Message-Id '<195317695095636.1733218386.831401586532593-openerp-6-res.users@localhost>' successfully sent`   (and successfully received)

I'm searching for another way to reproduce the issue and will confirm that it properly works :) 

Thanks for the reactivity!

**Comment by Abridbus** [comment]
Hi :) 

Reported Issue 3:
1/ Fresh db 16.0
2/ Add a MAD
3/ Go in General Settings > Invite New Users: Thom@as.com.
   Account will remain in pending and not email is sent:
   `Ignoring invalid recipients for mail.mail <981598023188328.1733403363.577264070510864-openerp-private@localhost>: ['Thom@as.com']`
   
5/ Inviting thom@as.com do work:
  `call res.users().web_create_users(['thom@as.com'])`
  `Mail with ID 6 and Message-Id '<882001089188689.1733403460.602158308029175-openerp-private@localhost>' successfully sent`

With the second fix:
6/ Inviting Thom@as.com do work. Email is lower cased:
  `call res.users().web_create_users(['Thom@as.com'])` 
  (log is stating Thom as local-part but it's indeed thom in the email sent and for the user login)
  `Mail with ID 7 and Message-Id '<724727907979815.1733403922.078825950622559-openerp-private@localhost>' successfully sent`

centralized opw-4377533
opw-4379777

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
