### PR TITLE
[FIX][WIP] base: delete cascade by ORM, some attachment not unlinked, some computed field no recomputed

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
When you unlink a purchase, the lines are unlink by the `SQL CASCADE` fonction. It is more quicker but the ORM `unlink()` of lines is not applied. It is an issue, indead the attachments of lines are not unlink, and computed field liked to the lines are not re-computed (computed field in an other model).

This PR propose to unlink cascade records by ORM.

I think there is no case in the Odoo code where this situation exist.

FIX:
- delete attachment of cascade deleted records
- on cascade modified field modified is not apply

IMP:
- full logger of what is delete in database (if you delete a purchase order, you see also log about the purchase line)
- don't clear all the cache

**Exemple**
```python
Order()
    _name='order'
    lines_ids = fields.One2many('order.line','order_id')

OrderLine():
    _name='order.line'
    order_id = fields.Many2one('order', ondelete='cascade')
    value = fields.Integer(default=10)
    file = fields.Binary(attchment=True)

Truc()
   _name='truc'
   order_line_ids = fields.Many2many('order.line', store=True)
   total = fields.Integer(compute='_get_total', store=True, readonly=True)

   @api.depends('order_line_ids.value')
   def _get_total(self):
         for rec in self:
               rec.total = sum(rec.order_line_ids.mapped('value')

```

Excecute
`order = self.env['order'].create({'line_ids':[(0,0,{'file': 'dscsd'})]})`

note the id of attachment with SQL request (don't use web UI, it don't show).
`SELECT * FROM ir_attachment`

`order.unlink()`

**Current behavior before PR:**
- make in postgre `SELECT * FROM ir_attachment WHERE id = x`, you can see the attachment (and it still present in the file store.
- `truc.total` is not recomputed

**Desired behavior after PR is merged:**
- file as been deleted.
- `truc.total` is recomputed

**Todo :** 
- [x] fix recursion issue
- [x] save cascade field in the registry (remove the `env['ir.module.fields'].search()`)
- [ ] update test
- [x] fix company depend field
- [x] clear more cache (ondelete = 'set nul'

@odony @rco-odoo @nim-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rco-odoo** [comment]
> I think there is no case in the Odoo code where this situation exist.

Don't try to solve a problem that does not exist.  This will add a lot of queries and slow down the `unlink` operation in all cases, with little benefit for the added cost.

I have already thought a lot about this feature, and IMHO it is not worth the effort.

**Comment by fmdl** [comment]
On Odoo I think there are no issue, but I have lost time to unterstand why on a personal module, I have an issue with computed field.

I understand that add more query (I have work to reduce at maximun the number of query), the soft cache invalidation include in this PR may reduce the number of query after unlink. 

It is more an issue of integrity than number of query.
Integrity issues with `SQL CASCADE` :
- `ir.model.data`, `ir.default`, `ir.attachment` and `ir.translation` are not unlink for the record delete by cascade.
- in a second plan, deletation of record delete by cascade is not log (bad for audit)
- **`modified()` is not apply on record delete by cascade**

The last one is the most tricky, computed field is used a lot, some error can appear because developpers don't know this behavior.

**Exemple of bug, can be made from UI**
On Studio:
- Create a new apps
- Create a new model A with:
```python
purchase_line_ids = fields.Many2many('purchase.order.line', store=True)
total = fields.Integer(compute='_get_total', store=True, readonly=True)

@depends('purchase_line_ids.quantity')
def _get_total(self):
     for rec in self:
           rec.total = rec.purchase_line_ids.mapped('quantity')
```
- Create a new record A, add some purchase line from purchase A, the total is computed.
- Delete a purchase A
--> `total` is not recomputed

I don't know what is the best solution, but I think we need to make some thing 
Other Ideas :
- add information in documentation about cascade and computed field (`unlink()` is not apply of record delete by `cascade`)
- deprecated cascade and prefere to use unlink():
```
Class PurchaseOrder()
      def unlink():
            self.purchase_order_line_ids.unlink()
            super().unlink()
```
- keep `cascade` but apply logique of unlink without `SQL DELETE` of `cascade` records

**Comment by fmdl** [comment]
cc @sla-subteno-it @alexis-via @Yenthe666

**Comment by Yenthe666** [comment]
Hmm to me this feels like possible technical debt. I agree with @rco-odoo - it doesn't look like it is worth the effort and the possible backlashes.

**Comment by pedrobaeza** [comment]
I think this should be closed as it has been stated.

**Pull request closed without merging**
