### PR TITLE
[IMP] base_vat: remove simple check vat for co

### PR DESCRIPTION
**Pull request by nla-odoo**
Task: https://www.odoo.com/web#active_id=2190843&cids=2&id=2190843&model=project.task

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@nla-odoo Can you make sure the commit message reflects the entire commit?  Is the removal of the function in base_vat handled by the stdnum library then or why do we remove it?

**Comment by nla-odoo** [comment]
Hello @jco-odoo 
it will call the stdnum func only when there is no function  like check_vat_co
and in this method, we have expected the int only for the vat
I have tested almost 4k vat shared by Rubi

Thanks

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
