### PR TITLE
Fix asset conversion

### PR DESCRIPTION
**Pull request by Arcasias**
Enterprise: https://github.com/odoo/enterprise/pull/17616
Upgrade: https://github.com/odoo/upgrade/pull/2377

### CODE REVIEW

**Review by aab-odoo — COMMENTED** [review]
Shouldn't this PR be re-targetted to saas-14.3 ?

**Comment by Arcasias** [comment]
> Shouldn't this PR be re-targetted to saas-14.3 ?

@aab-odoo I'll have to make a backport PR to remove the `im_livechat.external_libs` view in stable anyway, so I thought I might as well backport the whole thing instead of splitting the PR (odoo/upgrade doesn't allow to fix it in 14.3). If you prefer having it split I'm ok with it too.

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by KangOl** [comment]
> > Shouldn't this PR be re-targetted to saas-14.3 ?
> 
> @aab-odoo I'll have to make a backport PR to remove the `im_livechat.external_libs` view in stable anyway, so I thought I might as well backport the whole thing instead of splitting the PR (odoo/upgrade doesn't allow to fix it in 14.3). If you prefer having it split I'm ok with it too.

Yes, you can make fixes in the upgrade scripts of previous versions. You don't need to have the patch to be linked to the PR. It will just have to be merged before this PR (retargeted) will be mergeable.

It will work for this case because the upgrade script is simple and won't break without the corresponding changes in odoo

**Comment by KangOl** [comment]
@robodoo rebase-ff r+

**Comment by Xavier-Do** [comment]
> > Shouldn't this PR be re-targetted to saas-14.3 ?
> 
> @aab-odoo I'll have to make a backport PR to remove the `im_livechat.external_libs` view in stable anyway, so I thought I might as well backport the whole thing instead of splitting the PR (odoo/upgrade doesn't allow to fix it in 14.3). If you prefer having it split I'm ok with it too.

Next time come in the runbot chan and check that with us ;)

**Pull request closed without merging**
