### PR TITLE
[FIX] purchase: fix the issue of vendor reference getting duplicated

### PR DESCRIPTION
**Pull request by QaidjoharBarbhaya**
Before this fix, if vendor bill is created from purchase order, then
reference got duplicated on bill if vendor reference had comma (, ) in
it.

Description of the issue/feature this PR addresses:
Please watch this video in which the issue is demonstrated:
https://drive.google.com/file/d/1gGlnNogO6B2gkjPiwdzEtYaUcOrjaGRc/view?usp=sharing

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Whenrow** [comment]
@QaidjoharBarbhaya Hello, thank you for this work but as this is not really blocking could you please retarget in master ? 
Also, regarding the methodology, I would rather making a `set()` with self.ref and vendor_refs, both after calling split on them.
Thanks

**Comment by QaidjoharBarbhaya** [comment]
@Whenrow This issue is in v13 only. There is no issue in v14 and master, to my knowledge, probably due to this refactoring.

https://github.com/odoo/odoo/commit/488e334fc8fd6601e304635fa577c98b9bfd18e6

**Comment by QaidjoharBarbhaya** [comment]
@Whenrow Can you please review the implementation done using the set operation? Thank you.

**Comment by C3POdoo** [comment]
Dear @QaidjoharBarbhaya,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
