### PR TITLE
fix odoo/odoo#4792 signature mismatch on price_get

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by rdeheele** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by antonylesuisse** [comment]
I close this PR in v9 we dont use pricelist anymore for purchase order, only supplierinfo.

**Comment by gurneyalex** [comment]
@antonylesuisse you'll note that the PR is against v8, not v9...

**Comment by antonylesuisse** [comment]
Ok it's a bugfix for v8 @mart-e can you check merge it ?

**Comment by gurneyalex** [comment]
thanks @antonylesuisse

2015-12-30 3:33 GMT+01:00 antonylesuisse <notifications@github.com>:

> Reopened #4793 <https://github.com/odoo/odoo/pull/4793>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/pull/4793#event-502535787>.
>



-- 
Alexandre Fayolle
Chef de Projet
Tel : + 33 (0)4 58 48 20 30

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac Cedex
http://www.camptocamp.com

**Comment by mart-e** [comment]
It was already merged at ed6d9afecc7f48ba126034d627076f90c1e0f512 actually.
Thanks

**Pull request closed without merging**
