### PR TITLE
Fix several missing security rules in stock and mrp

### PR DESCRIPTION
**Pull request by davidtranhp**
Fix security issues regarding to mrp.message, scrap, mrp.unbuild which prevent daily normal operations

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Could you detail the steps to get security issues?
Please note that one is already fixed at 03bc8c5f9ac53a3349c1caac222f7619a632ccd8
Could you rebase your branch?

**Comment by davidtranhp** [comment]
@mart-e Thanks! I have rebased the branch. Steps to reproduce is simple:
1. Do not use admin account (superuser ID 1)
2. Try on creating new records for mrp message, scrap, unbuild order, then you will find no way to do it. The reason for that is security rules are missing.

At the time of creating the pull request, I took a try on your online version and found the same issue.

Thanks for your time looking at this.

**Comment by mart-e** [comment]
@tde-banana-odoo what do you think? The mrp.message are created in enterprise using a button "Create Production Message". Shouldn't this be restricted too?

**Comment by davidtranhp** [comment]
@mart-e @tde-banana-odoo Would you please review this PR? Tks!

**Comment by mart-e** [comment]
mrp merged at bfb2771d633
the stock part was already fixed at #15955, given the create access to users

**Pull request closed without merging**
