### PR TITLE
[8.0][ADD] Add test_fields_inherit

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Add a module in order to test inheritance of fields

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
Issue related to this PR #4724

**Comment by adrienpeiffer** [comment]
@rco-odoo What do you think about this PR .

**Comment by adrienpeiffer** [comment]
@rco-odoo A little more explanation : Currently, many fields are still written in old API in standard sources. We just want to overload these fields by old or new API. This PR test a case of a company dependent field wrote on old API and we want to overload this field to make a function field. one on old API and one new API.

**Comment by adrienpeiffer** [comment]
list of tested inheritance of field that currently does not work:
1) property many2one on old api -> function many2one old api : KO
2) property many2one on old api -> function many2one new api : KO
3) property float on old api -> function float new api : KO

**Comment by sbidoul** [comment]
This test show that it is not possible to override a property field with a computed field.

PR #5014 seems to fix it.

**Comment by adrienpeiffer** [comment]
Ping @rco-odoo

**Comment by rco-odoo** [comment]
Taken in #9214 and merged.
Thanks for the test cases.

**Pull request closed without merging**
