### PR TITLE
[FIX] event_sale: unit price changes with the qty

### PR DESCRIPTION
**Pull request by jpp-odoo**
[FIX] event_sale: on change of events product in SO

Have a product that is an event, with the price of 1500.
Create a ticket for this product in an event, with the price of 600.
In a SO, add a line with this ticket.

Before this commit, when you change the tickets qty in the SO the price
change from 600 to 1500.

Now, the unit price stays the one of the ticket.

---

[FIX] event_sale: on change of events product in SO 

Have a product that is an event, with the price of 1500.
Create a ticket for this product in an event, with the price of 600.
In a SO, add a line with this ticket.

Before this commit, when you change the product, to another product that
is also an event, the event, the ticket and the price stayed the ones of
the first product.

Now, the event, the ticket and the price are updated when the product is
modified.

----

[FIX] website_event_sale: pricelist discount product qty

Before this commit, a pricelist discount based on the product qty could
be created and the user may believe that it will work also for event
tickets.

Now: when configuring a pricelist discount based on the product qty a
warning message is show to alert that this kind of discount don't work
in event tickets.

### CODE REVIEW

**Comment by jpp-odoo** [comment]
@kebeclibre please review.

**Comment by kebeclibre** [comment]
robodoo rebase-ff

**Comment by kebeclibre** [comment]
I'm okay with it in principle. I guess commits 0 and 1 should be squashed together (the ones adding the onchanges on SaleOrderLine)
I'd like to have @rdeodoo or @JKE-be input

**Comment by rdeodoo** [comment]
LGTM

As discussed it currently seems to be a known/wanted limitation that pricelists and event tickets are not working as expected (a26a84f9c0f6).

**Comment by kebeclibre** [comment]
robodoo r+

**Pull request closed without merging**
