### PR TITLE
[IMP] l10n_uy: DGI code for generic doc types

### PR DESCRIPTION
**Pull request by zaoral**
Related to https://github.com/odoo/enterprise/pull/51266

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@zaoral [ADD] is normally only for new modules, could you change to 
 [IMP] ? https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html

**Comment by jco-odoo** [comment]
@zaoral

**Comment by zaoral** [comment]
@jco-odoo 
Thank you for the review Jos
I have changed the commit and PR message and rebase the branch
I think is ready for merge.

Best Regards

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
