### PR TITLE
[CI] log error message on warning

### PR DESCRIPTION
**Pull request by yelizariev**
Description of the issue/feature this PR addresses:

It helps easily catch an error on phantom tests

Current behavior before PR:

js tours failed without clear explanation what happens. The next step just doesn't work 

Desired behavior after PR is merged:

We get exact reason in the logs

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@it-projects-llc

### CODE REVIEW

**Comment by yelizariev** [comment]
Example of the error, that is not caught by phantom tests
 
screenshot-16628-425-01b909-base runbot it-projects info-2018 05 17-19-05-03

**Comment by yelizariev** [comment]
I am not sure does phantomjs support ``console.warn``

**Comment by mart-e** [comment]
> I am not sure does phantomjs support `console.warn`

Looks like no
https://github.com/ariya/phantomjs/issues/10150#issuecomment-318118567

**Comment by aab-odoo** [comment]
Can you re-target this to 13 (where phantomjs has been dropped) and replace the console.log by console.warn? Thanks

**Comment by yelizariev** [comment]
Done. I'm not quite sure is it enough to have ``console.warn`` to stop js tests or it should be ``console.warnt('error', ...)``

**Comment by aab-odoo** [comment]
@yelizariev We don't want the test to stop when do_warn is executed, because it could be part of the flow.

Also, could you rewrite your commit message s.t. if follows our [guidelines](https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure)?

**Comment by yelizariev** [comment]
@aab-odoo I have reworded the commit message. It should be better now

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
