### PR TITLE
Master products page continuation bvr

### PR DESCRIPTION
**Pull request by bvr-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Feyensv — APPROVED** [review]

**Comment by JKE-be** [comment]
todo compress warranty.png -> -64%
category search vs BSO task fuzzysearch... to discuss

else lgtm

**Review by JKE-be — COMMENTED** [review]
todo compress warranty.png -> -64%
category search vs BSO task fuzzysearch... to discuss

else lgtm

**Comment by bvr-odoo** [comment]
> todo compress warranty.png -> -64%
If the image is compressed, quality is lost on the "all products" page (the image is displayed smaller than its size on this page)
https://i.imgur.com/q6RFjlF.jpg

**Comment by bvr-odoo** [comment]
> todo compress warranty.png -> -64%
> category search vs BSO task fuzzysearch... to discuss
> 
> else lgtm

If the image is compressed, quality is lost on the "all products" page (the image is displayed smaller than its size on this page)
https://i.imgur.com/q6RFjlF.jpg

**Comment by bvr-odoo** [comment]
> todo compress warranty.png -> -64%
> category search vs BSO task fuzzysearch... to discuss
> 
> else lgtm

As long as I compress the image (even just a little bit) .. The quality is not good enough
So i have to leave it like that :/

**Comment by JKE-be** [comment]
@robodoo r+ rebase-ff

Thank you

I rebased, compressed warranty form 9%, and removed categ commit (-> task-2613843).

**Comment by rdeodoo** [comment]
@robodoo retry

**Comment by JKE-be** [comment]
@robodoo retry

**Comment by JKE-be** [comment]
@robodoo r+

**Pull request closed without merging**
