### PR TITLE
[REF] mail, *: tests: rename test() + indent

### PR DESCRIPTION
**Pull request by seb-odoo**
* = im_livechat, test_mail, website_livechat

Prep for hoot, `QUnit.test` becomes `test`, indent is changed to always one tab.

`// QUnit.test()` is necessary to trick the assert bundler to know there are QUnit tests in the file.

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]
@robodoo r+ delegate+

**Comment by alexkuhn** [comment]
@robodoo override=ci/security
don't worry robodoo, it's just "html" in the name of test

**Comment by tde-banana-odoo** [comment]
That is why people complain about forward ports: useless reindent of 5K lines breaking all forward ports.

**Comment by alexkuhn** [comment]
> That is why people complain about forward ports: useless reindent of 5K lines breaking all forward ports.

FYI this is a preparation step to move from QUnit to HOOT, and tests in HOOT uses new syntax `test()` rather than `QUnit()`. Prettier has apparently a special rule for `test()` to not wrap to newline. This reindent is there to ease diff in the follow-up PR.

I know very well your stance on not changing the code too much to not make forward-port more difficult. I would argue that if you need to forward-port so much, this shows a much bigger issue in the quality of code that requires a lot of bug fixes in stable version.

**Comment by tde-banana-odoo** [comment]
> I would argue that if you need to forward-port so much, this shows a much bigger issue in the quality of code that requires a lot of bug fixes in stable version.

Actually our main problems arise every time we have to fix something in JS, and especially discuss. SM frequently has to fix / repair broken flows due to discuss changes, and/or work on side dishes like improving performances or improving activities flows in various applications. So I completely agree with you: there are a regressions each version (notably because you tend to rewrite your own code each version and because tests are too much decoupled from real testing due to heavy mock), and we have to adapt patches in each major version because of: linting, file renaming, file move, file change, method renaming, ...

I don't have major issues forwarding patches in standard python code because code is much more stable.

**Comment by alexkuhn** [comment]
> Actually our main problems arise every time we have to fix something in JS, and especially discuss. SM frequently has to fix / repair broken flows due to discuss changes, and/or work on side dishes like improving performances or improving activities flows in various applications.

I can't remember the last time I saw a PR from your team that change discuss JS code. Don't invent a world where you say most of the bugs you deal with come from our team when it's genuinely not. As for activities, this is in a weird spot where no official team is really responsible of that scope as this is not really Discuss nor SM.

> So I completely agree with you: there are a regressions each version (notably because you tend to rewrite your own code each version and because tests are too much decoupled from real testing due to heavy mock), and we have to adapt patches in each major version because of: linting, file renaming, file move, file change, method renaming, ...

This shows you really don't get the point of these changes:
- We (re)write our code frequently to improve it, because we know that if the code is improved then it solves issues of today and tomorrow.
- Linter helps reducing programming errors & mistakes.
- The heavy mock you refer to is most likely the JS mock server from a recent comment I saw from you. This is currently the best tradeoff we have to write, run, and debug tests fast. Sure, there are many problems with this approach and we are fully aware of that and are actively working to solve these problems. No, rewriting discuss tests with tours is NOT a good alternative, because they are extremely slow to write, run & debug. And that's also without considering other technical problems with websocket that is not running in tours, which is a crucial component of Discuss codebase.

> I don't have major issues forwarding patches in standard python code because code is much more stable.

That's because we are not working in changing the python code of discuss (yet), our focus has been and is on JS. It is still plastered of many bugs, mostly caused by the weak architecture of code that hasn't changed for ages. Of course you don't have issue forwarding patches when the code has barely changed...

----

It's easy to criticise the work of others, but it's another matter to understand them. If you took a few seconds to read the 1st PR message of commit message, you would have understood the motivation of this change, that it's not a whim.

**Comment by tde-banana-odoo** [comment]
>  can't remember the last time I saw a PR from your team that change discuss JS code

That's sad, maybe you should read other team's work then. Just as an example  we spend several hours debugging suggested recipients just a week ago or two. It was suggested not to fix in stable because "code changes too much", according to someone from your team. Trust me, I know what I review. I never said most bugs come from discuss. I said most bugs we have to fix in discuss are painful to forward-port. I work within 10 apps from technical to functional so again trust me, I know what I review.

Anyway, you still did not answer to my main review: don't reindent 5K line of code when there is no reason. Hoot is not a reason. I don't debate whether the new test framework is better or not as I don't have any clue; I debate that reindenting files is a useless PITA.

Have a great weekend,

**Pull request closed without merging**
