### PR TITLE
[IMP] account: adding a function to check the structure validity of a reference

### PR DESCRIPTION
**Pull request by SaddemAmine**
This function checks if a reference is valid in regards to the countries currently supported in account/tools/structured_reference.py

Task ID: 2982194

### CODE REVIEW

**Review by FlorianGilbert — CHANGES_REQUESTED** [review]
Hello,

You have a typo in your commit title :hand_over_mouth: 
> [...] **strucuture** [...]

I'm not against a test :)
Thank you!

**Comment by SaddemAmine** [comment]
Strucuture 🤦‍♂️

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+

**Comment by FlorianGilbert** [comment]
@robodoo check

**Comment by FlorianGilbert** [comment]
@robodoo r+

**Pull request closed without merging**
