### PR TITLE
[FIX] base: allow removal of selection fields during dev

### PR DESCRIPTION
**Pull request by Elkasitu**
Let field F of model M be a Selection field.

Before this commit, creating a database with field F, removing/renaming
field F by changing its definition within the code then upgrading the
database to reflect the changes would result in a registry crash because
the field would still exist in the database but not in the ORM (memory),
thus trying to fetch the field in DB from the memory would result in a
KeyError.

This is due to the fact that field renames / removals are not stable
operations and should be handled with a migration script when upgrading
an existing database, nevertheless this can be quite an annoying
behavior while developing which is why this commit simply skips the
processing of the field if it does not exist in memory.

The ORM already foresees these cases and logs a warning to the developer
saying that the field was deleted anyway but that it was only a
partial delete and that it should be handled in a migration script in
order for the change to be production ready.

PS: Couldn't add a regression test as it requires a database upgrade and standalone tests are only available in master

### CODE REVIEW

**Comment by Elkasitu** [comment]
cc @tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
:love_hotel:

**Comment by rco-odoo** [comment]
@Elkasitu I let you take care of forward-ports.

**Comment by tde-banana-odoo** [comment]
Thanks for quick PR @Elkasitu and @rco-odoo !

**Pull request closed without merging**
