### PR TITLE
17.0 website scrollbar fix res

### PR DESCRIPTION
**Pull request by res-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by detrouxdev — APPROVED** [review]
Did not look at the code, but seems to fix the issue with autocomplete on Safari 👍🏻

**Review by rdeodoo — APPROVED** [review]
And the whitebar is gone :+1:

**Review by adr-odoo — APPROVED** [review]
@rebase-ff r+

**Review by adr-odoo — APPROVED** [review]
@robodoo rebase-ff r+

**Pull request closed without merging**
