### PR TITLE
[FIX] account: allow overriding portal domain

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Before this commit the only way to modify the domain is to completely override portal_my_invoices.

Current behavior before PR: Since this function is so big this is not clean/easy to do now.

Desired behavior after PR is merged:
By creating a separate function we can simply override it and we can reuse the function on two places.

<b>Note:</b> This is the forward for https://github.com/odoo/odoo/pull/77271 since behaviour slightly changed between V13/V14.

CC @wardm95 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by FlorianGilbert — CHANGES_REQUESTED** [review]
Could you please squash your commits into one?

**Comment by Yenthe666** [comment]
@FlorianGilbert done! :)

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+

**Comment by Yenthe666** [comment]
@FlorianGilbert can you manage the forwards please? :)

**Pull request closed without merging**
