### PR TITLE
[FIX] base: field condition of ir.default is not show

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
The field condition is used but it is not show in any view.

@xmo-odoo @rco-odoo 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
opw #3992037

**Comment by fmdl** [comment]
ping

**Comment by ryv-odoo** [comment]
Hello @fmdl , IMO, it is rather an improvements than a fix, do you think? 

(FYI, we were planning to remove the `condition` feature (in 18/19?) (along with the change_default attribute on Field). It can easily be replaced with a simple base automation).

**Comment by fmdl** [comment]
I think it is a fix, because if you have different defaults with different condition, it is not easy to know witch one you should remove or update.

**Comment by ryv-odoo** [comment]
Anyway, the change is safe and it is indeed very confusing to not see this information in the view, we can merge it.
@robodoo r+
Thanks @fmdl

**Pull request closed without merging**
