### PR TITLE
[IMP] l10n_it_edi_proxy: ack does not make sense and only risks delet…

### PR DESCRIPTION
**Pull request by jco-odoo**
…ing newer messages on the server

Actually, the risk is almost nothing to not send acks of received messages.

Doing the ack is a bigger risk if right before the ack a newer
message would arrive.  This state is the default state
that does not need to be acked at all as there is no file
associated with it.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@dbkosky It would be nice if you could verify this one.

**Review by dbkosky — CHANGES_REQUESTED** [review]
I agree with the logic, preferably we should not send acknowledgements if the state could change whilst the processing is occurring. In which case maybe 
```state='notificaMancataConsegna'```
might need to be treated this way too (at least when it's to the government).
Maybe it's as simple as a `continue` at line 253?

**Comment by william-andre** [comment]
Why would the state change? Isn't there a concurrency lock to prevent that?

**Comment by jco-odoo** [comment]
@william-andre Because we get a new message from the gov on the proxy for that transaction.  (we could also send the current state we think it is in then, but this fix is simpler)  Locking itself on the proxy would not prevent that.

**Comment by william-andre** [comment]
Shouldn't the ack be done by the proxy? And then the proxy needs to have some kind of sync mechanism with the database too?
You say
> Actually, the risk is almost nothing to not send acks of received messages.

What is "almost nothing"?

**Comment by jco-odoo** [comment]
@william-andre That files would remain on the server.  (in this case, there is not even a file)

**Comment by william-andre** [comment]
From what I'm reading, it seems that the sync mechanism with the proxy is not well implemented.
Why would you get a new message from the government if you didn't do anything on your side? Why is the record not locked while you are waiting for a response from the government?

**Comment by jco-odoo** [comment]
@william-andre It is because it is server to server communication: we do not wait for the Italian gov, they call us.

**Comment by william-andre** [comment]
But you know when you need to wait for something, right?

**Comment by jco-odoo** [comment]
@william-andre yes

**Comment by william-andre** [comment]
Then why is the record not locked in the meantime?

**Comment by jco-odoo** [comment]
@william-andre For that, the client would need to send the state it thought it was in or something and it was not implemented that way.  (or we could keep a field there with the last sent state or something, but this is like the simplest solution for now)

**Comment by william-andre** [comment]
> > Actually, the risk is almost nothing to not send acks of received messages.
> 
> What is "almost nothing"?

But did you answer that :point_up: ?

**Comment by jco-odoo** [comment]
@william-andre I thought so.

**Comment by william-andre** [comment]
Would you mind explaining what happened before and what happens now, maybe with a connection graph between the server and the client?

**Comment by jco-odoo** [comment]
@william-andre  Not sure if a connection graph will make it easier to understand. There are 3 players: Odoo instance, proxy and the gov.  

Normal flow: 
- Odoo instance sends invoice to proxy, proxy to gov, which sends back transaction_id
- On the proxy, the state of the transaction_id is awaiting_outcome
- The gov sends a message back to the proxy that the invoice is approved (directly to the server), so the state becomes "approved"
- The odoo instance asks for the status, receives the "approved" message and then tells the proxy he received it
- The proxy deletes the "approved" message

What I want to avoid: 
- Odoo instance sends the invoice
- Proxy: awaiting_outcome
- Odoo instance checks the status and the server returns "awaiting_outcome"
- The gov sends a new message
- The Odoo instance acks and says he received the msg (there is actually no message associated)
- The new message from the government gets deleted.  

@dbkosky

**Comment by william-andre** [comment]
Ok, it's a lot clearer now :+1: Can you include that in the commit message?
Shouldn't the proxy be keeping the state of everything though?

Also, is there a way to get access to the code of the IAP server? (or to an API, but I have doubts about it's existence...)

**Comment by jco-odoo** [comment]
I also think it is a good idea to keep the last fetched state instead of a fetched/not state on the proxy.  Actually, we could change that on the proxy side already @dbkosky

**Comment by jco-odoo** [comment]
@william-andre Commit msg updated

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
