### PR TITLE
Master project ux improvement pat

### PR DESCRIPTION
**Pull request by pat-odoo**
Task : https://www.odoo.com/web?#id=54027&view_type=form&model=project.task&action=333&active_id=131&menu_id=4720

Pad : https://pad.odoo.com/p/r.394011d9fd84ee9ca8fb5f7418bcf9c8

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mba-odoo** [comment]
LGTM

**Comment by rdeodoo** [comment]
@JKE-be This one can be merged, it had some conflicts since it was 8500 commits behind, hopefully runbot will be green.

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo r+ rebase-ff

**Comment by JKE-be** [comment]
@robodoo r-

**Comment by JKE-be** [comment]
@robodoo r-

**Comment by rdeodoo** [comment]
Runbot should be green now, after rebase Qunit tests needed to be adapted to async/await

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo retry r+ rebase-ff

**Comment by JKE-be** [comment]
@robodoo what are you waiting ?

**Pull request closed without merging**
