### PR TITLE
[FIX] website_links: keep text-box open in select2 no matches

### PR DESCRIPTION
**Pull request by nihp-odoo**
**Before this PR:**
In link tracker form, if there is no campaign/medium/source, 'No matches found' message is directly displayed and the text-box for input disappears quickly.

**Specifications:**
We need to keep the input text-box open to be able to create new records on the fly.

**Technical Reason:**
defined 'formatNoMatches' as false to keep text-box open.

**After this PR:**
Text-box for input will remain open and will not disappear.

Task-4065969

### CODE REVIEW

**Comment by amdi-odoo** [comment]
Hello @nihp-odoo :slightly_smiling_face: 
LGTM ! :smile:
Could you just add in the commit message (and update PR description) that we need to keep the input open **to be able to create records on-the-fly**? 
Thanks! :slightly_smiling_face:

**Comment by nihp-odoo** [comment]
Helloo @amdi-odoo 
Requested changes are done. Can you please take a look at it.
Please let me know if I have missed something.
Thanks.. :smile:

**Comment by tde-banana-odoo** [comment]
@robodoo r+

Zboing zboing !

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
