### PR TITLE
[FIX] stock: make it possible to inherit distinct fields in _merge_moves

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
It is not easily possible to add another distinct field for avoiding merging of moves, so we add a common prepare method to be inheritable easily by other modules.

**Current behavior before PR:**
Static definition of distinct fields

**Desired behavior after PR is merged:**
Dynamic definition of distinct fields possible

@amoyaux @pimodoo @jco-odoo @nim-odoo @sle-odoo 
Please be so kind and take care of this minimal and valuable change. Thank you :-)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sle-odoo** [comment]
hi Wolfgang,
why not, but i guess you need to adapt `_keys_sorted` too, so the groupby will work correctly

**Comment by wtaferner** [comment]
Ups, I missed that :-D no worry, will be delivered in a few minutes ;-)

**Comment by wtaferner** [comment]
@sle-odoo 
Should be ok, I guess.

**Comment by wtaferner** [comment]
@jco-odoo 
By playing around and testing with the ```_merge_moves``` method I found out that merged moves are not respected for the increase of the quantity mechanism. So let's say we have two ```stock.move``` with the same product and they will be merged after the sale order is confirmed (i.e. by adding a new sale order line with the same product) and later if you increase the qty of one sale order line the diff is incorrectly calculated as it only takes care of the qty of the changed sale order line which is wrong due to the merged stock moves.

**Comment by wtaferner** [comment]
Ok, no opportunity but I fix the issue above by the inheritance introduced ;-)

**Comment by sle-odoo** [comment]
@wtaferner sorry, i don't get the issue with the different sale order lines, could you point out the use case where the calculated diff is wrong?

**Comment by wtaferner** [comment]
Imagine that you have a sale order line in state ```sale``` for product x of a qty 7
It has produced a ```stock.move``` for a product x and is not yet done with a qty of 7

Now add a new sale order line with product x and a qty of 4
It will merge the new procurement with the first ```stock.move``` with a total of qty 11

Now change the first sale order line to a qty of 10
It will increase (actually) decrease the qty of the related ```stock.move``` to  10 instead of 14 

I hope this sample helps to understand...and it is clear...as the ```stock.move``` has only one sale_order_line_id it will loose one connection...if we do not merge different sale order lines or purchase order lines in a stock move we should be fine...

**Comment by wtaferner** [comment]
@jco-odoo 
Not sure if you agree with the solution but I guess so :-) still need to find a better way than the general blocker of decreasing not propagated qty changes ;-)

**Comment by sle-odoo** [comment]
@wtaferner Ok, i can reproduce your issue. I guess we did not think of this use case :) The one we wanted to manage is to merge the moves in the pick state of the pick pack ship, where the pick has a fixed procurement group. This usecase is working as sale_line_id is not propagated beyond the first created move.

Also, when you have multiple sale order lines for the same product, if the linked stock moves are merged, the "qty delivered" field is wrongly computed.

So your patch is right and does not break the usecase we wanted to support, we'll merge it. Thanks for your report.

**Comment by sle-odoo** [comment]
i guess the _keys_sorted is useless now as we could directly use _prepare_keys_sorted in the call to groupby

**Comment by wtaferner** [comment]
@sle-odoo 
Can you elaborate what you mean by a code snippet? but yeah, I did not question the part of sorting a lot

**Comment by sle-odoo** [comment]
merged at c30f8c50a3f4492c68f7cc4c2c1ce6cb5bf5350b
thank you!

**Comment by sle-odoo** [comment]
@wtaferner In [this branch](https://github.com/odoo-dev/odoo/commits/11.0-wt-sle) i made fixups 599b245cbc54a8468a6d33825f8660dd5f274da0 and a071c205a9a2c26a4d8710cc51490f901ae81813 where i get rid of the `_keys_sorted` inner method. If you agree with the changes i'll push them.

Regards

**Comment by wtaferner** [comment]
@sle-odoo 
I'll review and push them afterwards here in the afternoon. Thank you in the meantime.

**Comment by wtaferner** [comment]
@sle-odoo 
Hmm, I was deciding for the other way as I thought it is cumbersome to not use the multi mechanism instead of a parameter, but yeah, as it is so specific there is no re-usage anyway.
I have tested it and it works like expected.

I've pushed your fixed-up commits. Ready to merge from my point of view.

**Comment by sle-odoo** [comment]
@wtaferner i chose not to use the multi mechanism in order to get rid of the _keys_sorted inner method, as a method used in `sorted` receives an argument

let's way for a green runbot, i already have my share of red 11.0 today

thanks

**Comment by wtaferner** [comment]
Jep, I know and I am fine with that...I actually was having it like this before but decided the other way...anyway, let's wait for runbot and I doubt it will be red ;-) Crossing fingers :-)

**Comment by sle-odoo** [comment]
merged in ef592ffa3d1bbeab910cc66fca4028c978d9446e and faff276e9292d9f7534bbfddd6d2c4b726164645

thanks a lot!

**Pull request closed without merging**
