### PR TITLE
[IMP][8.0]store session in redis server

### PR DESCRIPTION
**Pull request by jeffery9**
Description of the issue/feature this PR addresses:

add option to store session in redis server

Current behavior before PR:

store session in file system

Desired behavior after PR is merged:

should be better performance, and share session between multi-instance should be more easier.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kler** [comment]
Instead of providing a `--redis-server` option for the user, wouldn't it be possible to implement a generic session handling where the user can provide a class, like
`--session-handler=redis_session.RedisSessionStore` _or_
`--session-handler=werkzeug.contrib.sessions.FilesystemSessionStore `
and a generic configuration string which is parsed and passed to the session store, like
`--session-configuration="host=abc;port=123"`

In this way it would be easy to provide additional session storage backends.

And I couldn't help by notice that it seems like you copied the code from Carlo Pires (https://gist.github.com/carlopires/1451947). Is this alright by @carlopires ?
And if it is ok with him, perhaps remove the created and author tag from the code.

**Comment by dreispt** [comment]
Is this useful? I thought that Odoo sessions were stateless.

**Comment by kler** [comment]
I don't understand your question or what you mean by "Odoo session are stateless"  :/

However, the reason this modification is useful is to be able to run multiple Odoo instances to be able to load balance or fail-over. I would say it's best practice to have web services not being tied to the server executing the application to allow horizontal scaling.

**Comment by guewen** [comment]
This is right, currently we can't run Odoo on several hosts because they would not share their session files (unless relying on a shared filesystem which is a single point of failure). So the Odoo server is not good at horizontal scaling.

This is indeed needed and I concur with @kler in that we should be able to customize the session handler. It has been proposed here https://github.com/odoo/odoo/pull/7937 so if you are interested in that, maybe see what could be done there.

**Comment by dreispt** [comment]
@kler I may be missing something, but AFAIK you can already scale horizontally.
The web session data stored in the filesystem has no state information.
State is either carried in he request or stored centrally in the database.

**Comment by dreispt** [comment]
@guewen This is surprising, I was not aware of it.
My information was that no session state data was stored on the server.
The only reason why you would need a shared file server would be the case where you store attachments in the file system.
Was this limitation introduced in v9?

**Comment by guewen** [comment]
@dreispt the session are werkzeug session files stored in `.local/share/<db-name>/sessions` (by default). As a user of the web-service (so the web interface or any other client), when you call `authenticate` for the first time, you get a session_id that should be passed as a cookie or as a header to every further calls, this session id is checked against the werkzeug session file.

This is easy to check; start a server, log with a user, delete the content of the server-side sessions directory, on the web interface you will get a session expired error.

It was already like that in v8, I don't know for the versions before.

**Comment by dreispt** [comment]
@guewen Thanks, I guess I overlooked that. Disappointed 😞

**Comment by jeffery9** [comment]
yes, the core is copy form him.

On Wed, Jun 22, 2016 at 4:09 PM, Patrik Lermon <notifications@github.com>
wrote:

> Instead of providing a --redis-server option for the user, wouldn't it be
> possible to implement a generic session handling where the user can provide
> a class, like
> --session-handler=redis_session.RedisSessionStore *or*
> --session-handler=werkzeug.contrib.sessions.FilesystemSessionStore
> and a generic configuration string which is parsed and passed to the
> session store, like
> --session-configuration="host=abc;port=123"
>
> In this way it would be easy to provide additional session storage
> backends.
>
> And I couldn't help by notice that it seems like you copied the code from
> Carlo Pires (https://gist.github.com/carlopires/1451947). Is this alright
> by @carlopires <https://github.com/carlopires> ?
> And if it is ok with him, perhaps remove the created and author tag from
> the code.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/odoo/odoo/pull/12515#issuecomment-227672694>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABVuLOGOTRTG_Wwu2CnVv_hgcyKEasZFks5qOO2zgaJpZM4I6o6Z>
> .
>



-- 
Jeffery        -odoo expert form kunshan, suzhou, china

**Comment by kler** [comment]
And he is ok with this?

**Comment by jeffery9** [comment]
Keep the author information in the code, i think he would agree to.
otherwise, should rewrite those code.

On Wed, Jun 22, 2016 at 8:23 PM, Patrik Lermon <notifications@github.com>
wrote:

> And he is ok with this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/odoo/odoo/pull/12515#issuecomment-227726495>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABVuLDGkkduq2P9mDJCJMILcP855VyBFks5qOSkogaJpZM4I6o6Z>
> .
>



-- 
Jeffery        -odoo expert form kunshan, suzhou, china

**Comment by kler** [comment]
I'm not representing Odoo, but I assume it's not expected that you push other peoples code without their consent. I suggest you ask @carlopires if it's ok to commit his code to the repository, even though he kindly put it out in the open as a gist.

I believe it's not common practice in this project to add author information, so optimally it should be removed.

**Comment by dreispt** [comment]
@kler On the contrary, the correct practice in OSS is to properly credit authors.

**Comment by kler** [comment]
What do you mean? "The correct practice". I don't even understand what part of my comment you're responding to, and where you acquired that knowledge.

I don't know if you bothered to read the submitted code, but it contains attribution of a developer who (AFAIK) haven't consented to pushing code to the repo. Hopefully and most likely he will once he is asked, preferably by the developer who copied the code without asking.

To put it even more clearly:
1) original developer should consent
2) OSS software best practices differs
3) this commit concerns odoo, not OSS in general, and as I wrote I believe that it's not best practice in this project to attribute developers in the code. If you know better, please go ahead and post links to code proving otherwise instead of making random comments based on opinions.

**Comment by jeffery9** [comment]
what's the opinions of you @mart-e

**Comment by mart-e** [comment]
The idea is nice and indeed, having alternative to filestore could be nice to make the load balancing easier (FYI, odoo.com does it with NFS). :+1: 

Regarding the code authoring, when taking the code from a gist with no license mentioned, you have to assume this code is proprietary, we can not relicense it in LGPL without @carlopires's approval. As the code is quite succinct, it shouldn't be too hard to rewrite it (and anyway there isn't an infinite number of ways to write a werkzeug session handler in redis).

Regarding the request itself. There is several issues:
- it's a new feature, it should target master
- `import redis` in `http.py` is not a good idea, should be imported only when I use this option  (I don't want to add a dependency for people using the filestore)

Could definitely take some ideas from #7937 as well (when people will ask for memcached ;-))

**Comment by dreispt** [comment]
@jeffery9 Finishing a PR for 8.0 is still useful:
Even if if can't be merged into Odoo, it can be proposed for [OCA/OCB](https://github.com/OCA/OCB/), the community bug fixing project.

**Comment by pedrobaeza** [comment]
This option shouldn't be merged on OCB, because derivative works will only work on this branch and not on vanilla Odoo. The option is to extract the functionality to a module.

**Comment by dreispt** [comment]
@pedrobaeza It's a grey area: it's affects the server installation, but not any in app feature/behaviour. Is `openerp/http.py` extendable? 
If so, isolating the feature in a module is an option.

**Comment by lasley** [comment]
@mart-e - I am about to pick this up. Just to confirm - if I were to rewrite the session handler to move us away from the questionable licensing, this feature would be accepted to master?

**Comment by mart-e** [comment]
@lasley the final call will be for @antonylesuisse or @odony but I still think it is a nice idea.
On #7937 Antony made some suggestions at that time on the architecture.

Closing this one as the 8.0 is no longer supported.

**Comment by lasley** [comment]
Thanks @mart-e 

@antonylesuisse or @odony can you please confirm that if I were to rewrite the session handler here to move us away from the questionable licensing, this feature would be accepted to master? I'm sure you understand that I do not want to spend effort on something that will be ultimately rejected.

**Pull request closed without merging**
