### PR TITLE
Fix bug dupplicate for loop when print repair orders

### PR DESCRIPTION
**Pull request by hoanglong87**
Description of the issue/feature this PR addresses: When print repair orders to pdf, contents in pdf file were dupplicated.

Current behavior before PR: When print repair orders to pdf, contents in pdf file were dupplicated.

Desired behavior after PR is merged: Contents in pdf file will be matched with selected records.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@hoanglong87 thanks for the PR. Several things to comment:

* This can't be integrated on v11 due to stability policy. Only on master.
* I see that this is a code optimization, but as is, there's no issue. Can you confirm it?

**Comment by hoanglong87** [comment]
@pedrobaeza It is a fix, not optimization. I have amended the commit to show the real change instead of the whole file change (due to indentation change)

**Comment by pedrobaeza** [comment]
As said, this should go to master.

**Comment by davidtranhp** [comment]
That's should be a bug since it has two `t-foreach="docs" t-as` for the same report.

**Comment by pedrobaeza** [comment]
No, as it's working without problem. You are iterating over a recordset with one element, so no problem at all.

**Comment by davidtranhp** [comment]
My bad. I thought that it could duplicate the content. I agree that this PR should go to the master.

**Comment by davidtranhp** [comment]
I have made a test on printing two repair orders from the list view (by select two row then print). The result was 4 pages while I expected to see two only.
@pedrobaeza would you mind doing such the test?

**Comment by pedrobaeza** [comment]
@davidtranhp Sorry, you're totally right. I looked bad to the variables involved, and indeed it loops n times per record when there are more than 1 record selected.

@jco-odoo can you please check this PR?

**Comment by tde-banana-odoo** [comment]
For information: comes from https://github.com/odoo/odoo/commit/a4bc731f041559283afd5a1d11f34e7547c11bb5 tat introduced the double loop.

**Comment by tde-banana-odoo** [comment]
Fix landed in 11.0 at https://github.com/odoo/odoo/commit/869b833618f727710f75ee61eca508bd3128e181 . Thanks !

**Pull request closed without merging**
