### PR TITLE
[CLA] ngquang: sign Odoo CLA for ngquang

### PR DESCRIPTION
**Pull request by Ngquang**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Ngquang** [comment]
> Hello,
> 
> Thank you for the signature but do you need this CLA for a specific contribution? You can add your CLA directly in the PR when you make your first contribution instead.

Oh, i didn't know that. If so, please execute for your convenience. Thanks.

**Comment by mart-e** [comment]
Also, it seems there is an issue with your configuration of your git client. You are making commits with `<“nguyen[…]@gmail.com”>` while it should be `<nguyen[…]gmail.com>`.

**Comment by Ngquang** [comment]
Hi @mart-e, could you review it ? Thanks

**Comment by mart-e** [comment]
You can check the commit used by going to https://github.com/odoo/odoo/pull/164514.patch
As you can see, it’s still the same. The email in the commit must be the same as the one in the CLA file

**Comment by Ngquang** [comment]
@mart-e Done. Thanks for notice

**Comment by Ngquang** [comment]
ping @mart-e

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
