### PR TITLE
[FIX] base: clear template cache when unlinking view

### PR DESCRIPTION
**Pull request by hubvd**
Steps to reproduce
==================

- Enable debug mode
- Go to studio
- Add a new field
- Switch to the view tab
- Restore the default view

=> The old view is displayed

Cause of the issue
==================

The studio view is unlinked [0] but the template cache is not cleared

---

[0]: https://github.com/odoo/enterprise/blob/b97f4c440d020141940a3d9e05aa25c9847ae5b9/web_studio/controllers/main.py#L448

### CODE REVIEW

**Comment by hubvd** [comment]
Enterprise PR: https://github.com/odoo/enterprise/pull/61236

**Review by ryv-odoo — APPROVED** [review]
Nice catch! It sounds good, thanks!

(The runbot is red, not sure if it is related.)

**Comment by kebeclibre** [comment]
@robodoo delegate=hubvd,ryv-odoo

**Comment by hubvd** [comment]
@robodoo r+

**Pull request closed without merging**
