### PR TITLE
Feature/expose env2

### PR DESCRIPTION
**Pull request by aricaldeira**
Description of the issue/feature this PR addresses:
It exposes env to context and domain evaluation, allowing xml_ids to be used in domain filters and default context declations

Current behavior before PR:
One cannot use xml_ids, eg, defined in res_country_data.xml on the base module, as default (in context) or domain in views

Desired behavior after PR is merged:
It will be possible to, in a view, use the following:

`<context>{'default_ref_country_id': 'base.br'}</context>`

or

`<field name="country_id" />
<field name="some_country_or_localization_specific_field" 
attrs={'required': [('country_id', '=', env.ref('base.br').id)], 'invisible': [('country_id', '!=', env.ref('base.br').id)]}" />`

We can't get the same behavior using
'country_id.name', '=', 'Brazil'
because 'country.name' will return the name of the country using the language of the user, not allways English of course.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mileo** [comment]
@fpodoo This is a important PR for v10 of l10n-brazil

**Comment by aricaldeira** [comment]
Odoo CLA signed here: #15210

**Comment by mart-e** [comment]
Hello,

Why not use `eval`? For instance, [in account](https://github.com/odoo/odoo/blob/cedb87165d255e6fe2581dbd5966b55eda4f9647/addons/account/views/res_config_view.xml#L8)
```xml
<field name="context" eval="{'search_default_category_id': ref('base.module_category_localization')}"/>
```

**Comment by aricaldeira** [comment]
Martin,

Thanks, for the default_ref in context, eval would do the trick, because I'm actually setting the value of that field when installing/upgrading the module (evaluations being performed in tools/convert.py, line 177..., 'ref' being passed to the globals_dict to safe_eval) and the modification introduced in models.py wouldn't be needed.

But for the domain part, and just now I realised I didn't put an example of that up above, would still not be possible:

<field name="some_field" attrs="{'invisible': [('country_id', '!=', ref('base.br'))]}" />

The above 'invisible' statement in the view doesn't work, because in here:

https://github.com/odoo/odoo/pull/15208/files#diff-20eb2df58491a79e8988063827170c7f

neither env nor ref are exposed to the global_dict or local_dict passed to the safe_eval function.

The feature will enable #15211 to function properly, among other uses in uses in the Brazilian localisation.

**Comment by aricaldeira** [comment]
My, just now I realised, where are all my xml examples?

Testing as text: "<field name="some_field" />"
Testing as code: `<field name="some_field" />`

**Comment by aricaldeira** [comment]
Ok, sorry Martin, I didn't know github would eat out all my xml examples...
I'll repost them now.

**Comment by mart-e** [comment]
Ok I see what you are trying to achieve but I am still not convinced about it, you can always find a workaround.
For the example of the country, you can use 
`attrs="{'invisible': [('country_code', '!=', 'BR')]}"` with `country_code = fields.Char(related='country_id.code')`
Often you will be able to work with related field.

In the views, you can also have some evaluation with `%(external.identifier)d` that will be evaluated at install. It is also possible to put the full view in an `eval` attribute.

Another solution is also to use `onchange` to compute values server side to change the static field you wish.

Anyway I do not think it is a good idea to specify too much logic in the view, it tends to make people encode the business logic in the views and trust it as acquired. The logic must be implemented at the system level.

**Comment by aricaldeira** [comment]
Martin, thanks, even though the PR was not accepted, I confirm that the alternate solution, using 
%(xml_id)d works fine.

As for the logic, it is realy a presentation matter, not functional; we could simply present the user a One2many list of more than 700 records in it, is it was done before, but it's just too cumbersome for them, and for us, to quickly find anything in there.

As for the branch, I'll take care next time.

Thanks!

**Pull request closed without merging**
