### PR TITLE
[FIX] sale: force an xmlid for template

### PR DESCRIPTION
**Pull request by KangOl**

### CODE REVIEW

**Review by nim-odoo — APPROVED** [review]

**Comment by mart-e** [comment]
What is the bug? Why moving it out of the noupdate?

**Comment by KangOl** [comment]
Not really a bug (until we need to update this view).
And this view has no reason to be noupdate.

**Comment by nim-odoo** [comment]
Parent view is actually on noupdate="0", so it makes sense to have the same config in the inherited view

**Comment by tde-banana-odoo** [comment]
Oooh, my "oezirhgoi" :D

**Pull request closed without merging**
