### PR TITLE
[IMP] account: improve tax name search

### PR DESCRIPTION
**Pull request by RodrigoBM**
Description of the issue/feature this PR addresses:

This commit allows the exact search of a text that is searched between dashes.
Examples:   0EUM      => VAT 0% EU M.
            21M       => 21% M , 21% EU M, 21% M.Cocont and 21% EX M.
            21 M-    => 21% M and 21% M.Cocont.
            21- M-co  => 21% M.Cocont.

Current behavior before PR:

With the Spanish chart of accounts, if you search for tax with the word "intra", you get more unwanted taxes.
e.g. "IVA 4% Adquisición de servicios extracomunitarios" tax is obtained, but the string intra is not in the name tax.

Selección_329

Desired behavior after PR is merged:

if we allow searching for "intra" between hyphens (-intra-), we will get only taxes whose name contains the full "intra" value.

Selección_330

CC: @rigr-odoo @william-andre @qdp-odoo 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by william-andre — COMMENTED** [review]
I understand the issue, but the solution is very technical and hidden.

Also missing test cases; this is getting really a touchy code...

**Comment by william-andre** [comment]
Note that you also need to [sign the CLA](https://github.com/odoo/odoo/blob/16.0/doc/cla/sign-cla.md) in order to get your Pull Request merged.

Thanks for your first contribution!

**Comment by RodrigoBM** [comment]
> I understand the issue, but the solution is very technical and hidden.
> 
> Also missing test cases; this is getting really a touchy code...

Hi @william-andre, I will try to explain the problem with another example.

- Operation without my fix:

If I have implemented the Spanish taxes. why I get 66 tax, when OSS taxes I only have 2. Because the _parse_name_search function searches for tax with ilike with the modified name as o%o%s and you get false positives of what you are really looking for e.g. Retenci**o**nes a cuenta 21% (Arrendamient**os**). This is correct?, I understand that it does not.

Selección_333


- Operation with my fix:

If this is indeed correct, I propose to have the opportunity to be able to indicate a fixed text, if we indicate it between dashes. e.g. No sujeto y acogidas a la **OSS** (Servicios). This option is in line with what has already been developed, it is possible that there is a better option that I can't think of right now.

Selección_334

Regards

**Comment by RodrigoBM** [comment]
> Note that you also need to [sign the CLA](https://github.com/odoo/odoo/blob/16.0/doc/cla/sign-cla.md) in order to get your Pull Request merged.
> 
> Thanks for your first contribution!

Add CLA commit

**Comment by william-andre** [comment]
After some consideration, we would like to add this feature, but using `"` instead of `-` :+1: 

Could you also add some tests?

**Comment by RodrigoBM** [comment]
> After some consideration, we would like to add this feature, but using `"` instead of `-` +1
> 
> Could you also add some tests?

I have added the required changes

Regards

**Review by william-andre — APPROVED** [review]
Nice work, thanks!

@robodoo r+

**Pull request closed without merging**
