### PR TITLE
[IMP] [9.0] Add financial reports l10n_ch

### PR DESCRIPTION
**Pull request by leemannd**
Description of the issue/feature this PR addresses:
Missing some base financial reports

Current behavior before PR:
Add two new reports 

Desired behavior after PR is merged:
Have the missing reports

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fclementic2c** [comment]
@qdp-odoo 
Hello Quentin,

We eventually managed to do a proper PR to add the l10n_ch P&L and B/S XML for the enterprise version.
(see my email sent to you on the 16/06/2016 'CH financial reports v9 enterprise'
[KMU-Kontenplan-Französisch.pdf](https://github.com/odoo/odoo/files/605807/KMU-Kontenplan-Franzosisch.pdf)

Would could you consider to merge it please ?

(We are preparing the v10 PR too)

Thanks

**Comment by fclementic2c** [comment]
:+1:

**Comment by qdp-odoo** [comment]
cool! 

I'm gonna have a look at it :-)

**Comment by leemannd** [comment]
@qsm-odoo Hello, I just figured that these charts are intended for the enterprise version. Shall I move to odoo/enterprise ?

**Comment by leemannd** [comment]
Hello,
As the reports were intended for the enterprise version, I did a PR in it https://github.com/odoo/enterprise/pull/590

**Comment by leemannd** [comment]
@qdp-odoo Hello,
As the reports were intended for the enterprise version, I did a PR in it https://github.com/odoo/enterprise/pull/590

**Comment by qdp-odoo** [comment]
indeed, i'm closing this one

**Pull request closed without merging**
