### PR TITLE
[IMP] account: correct term for supplier

### PR DESCRIPTION
**Pull request by sswapnesh**
We are using term "Vendor" on all views.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
@qdp-odoo  Not that much Important but still

**Comment by qdp-odoo** [comment]
@robodoo r+

Thanks @sswapnesh

**Comment by sswapnesh** [comment]
@qdp-odoo  This one needs r+ again

**Comment by JayVora-SerpentCS** [comment]
you too made a typo ;) supplier has 3 Ps :)

**Comment by sswapnesh** [comment]
@JayVora-SerpentCS 👍🏾  Commit updated.

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
