### PR TITLE
[FIX] l10n_ar, l10n_latam_invoice_document: Multiple fixes

### PR DESCRIPTION
**Pull request by zaoral**
* [FIX] l10n_ar: Fix compute for l10n_ar_vat field
* [REM] l10n_latam_invoice_document: remove l10n_latam_amount_tax field: This one is not really neccesary since was used for CITI reports and this ones were deprecated.
* [REF] l10n_latam_invoice_document: improve invoice report view inherit: Improve way to make inherit for report invoice using position attribute instead of position replace.
* [FIX] l10n_latam_invoice_document: Report amounts
    * for excluded reports get price unit computing (and not price_unit) to get the untaxed price if the line has taxes with price included (as in sales)
    * fix l10n_latam_price_subtotal for report with taxes included and tax included on the price

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by zaoral** [comment]
Hi @jco-odoo @ren-odoo @jjscarafia

This new PR was created to add some fixes and improves we found when updating our community version 11.0. Please take a look.

Best Regards

**Comment by jco-odoo** [comment]
@zaoral Indeed better if we can reuse the generic methods.  Looks ok to me.

**Comment by zaoral** [comment]
@jco-odoo the commits has been squashed

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
