### PR TITLE
[IMP] extract method _get_module_name

### PR DESCRIPTION
**Pull request by bealdav**
Description of the issue/feature this PR addresses:

```
Make an existing feature available as function "Extract module name"
```

Current behavior before PR:

```
We have to copy code from Odooo SA like here
```

https://github.com/OCA/connector/blob/9.0/connector/connector.py#L31-L47

Desired behavior after PR is merged:

```
Make available this feature without copy/paste in all community modules.
```
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by guewen** [comment]
Nice! This can be much useful for other addons and it avoid to repeat code :)

Thanks :+1:

**Comment by hparfr** [comment]
It will improve our code quality by removing duplicate code.
:+1:

**Comment by alexis-via** [comment]
:+1: 
To make the code easier to read, I would have used 2 different variable names (instead of always using "module_name") : one for input and one for the return of the method.

**Comment by guewen** [comment]
> To make the code easier to read, I would have used 2 different variable names (instead of always using "module_name") : one for input and one for the return of the method.

BTW on the naming, calling the function `_get_addon_name` could be more clear to avoid the confusion with the Python module.

**Comment by bealdav** [comment]
@odony please only 1 minute to review 10 lines tell us if it's possible to merge. 
It remove duplicate code.

**Comment by odony** [comment]
Thanks! Looks good to me, but [for master](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean).

**Comment by bealdav** [comment]
@odony Done here https://github.com/odoo/odoo/pull/11223
Thanks for merge, then

**Comment by odony** [comment]
Closed in master via #11223

**Pull request closed without merging**
