### PR TITLE
[FIX] board: action list

### PR DESCRIPTION
**Pull request by nim-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
labeled as WIP, but honestly I don't have any other idea without having to refactor the 'board' module.

**Review by nle-odoo — COMMENTED** [review]
in the normal use case we create the list of dict in _executeWindowAction:

https://github.com/odoo/odoo/blob/1bdd0cc247d36c869ffdee7d501cb65d36be47a6/addons/web/static/src/js/chrome/action_manager_act_window.js#L282-L307

that calls _generateActionViews that will return a list of dictionaries

maybe it would be enough to  just transform views in dashboard with something like:

```js
action._views = action.views;
action.views = $.map(action.views, function (view) { return {viewId: view[0], type: view[1]}});
```

after we have received the object:

https://github.com/odoo/odoo/blob/1bdd0cc247d36c869ffdee7d501cb65d36be47a6/addons/board/static/src/js/board_view.js#L241-L244

this way the fix for the particular case of dashboard, is in dashboard

**Comment by nim-odoo** [comment]
Indeed, you are right. Moreover, the assumption that a list of dicts is received is used is several
places:
https://github.com/odoo/odoo/blob/7a35515e495d4fb8edbaf252988c8c3c144f4442/addons/web/static/src/js/views/calendar/calendar_view.js#L131
https://github.com/odoo/odoo/blob/7a35515e495d4fb8edbaf252988c8c3c144f4442/addons/web/static/src/js/views/pivot/pivot_view.js#L131
https://github.com/odoo/enterprise/blob/05a78e94073aea88b2314918cadc478a367afef0/web_cohort/static/src/js/cohort_view.js#L93
https://github.com/odoo/enterprise/blob/05a78e94073aea88b2314918cadc478a367afef0/web_grid/static/src/js/grid_view.js#L79-L84

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
