### PR TITLE
[IMP] stock: update badge decoration for `stock.move` views

### PR DESCRIPTION
**Pull request by boan-odoo**
task: 2654703-4

### CODE REVIEW

**Comment by boan-odoo** [comment]
@thomasdeleval I suggest applying the same logic to `stock.picking` (not sure it makes sense):
```patch
diff --git a/addons/stock/views/stock_picking_views.xml b/addons/stock/views/stock_picking_views.xml
--- a/addons/stock/views/stock_picking_views.xml	(revision 30fcfcc6c6ebb6fe9620d29475e1a7b6f1a46923)
+++ b/addons/stock/views/stock_picking_views.xml	(date 1643373326652)
@@ -206,7 +206,12 @@
                     <field name="backorder_id" optional="hide"/>
                     <field name="picking_type_id" optional="hide"/>
                     <field name="company_id" groups="base.group_multi_company" optional="show"/>
-                    <field name="state" optional="show" widget="badge" decoration-success="state == 'done'" decoration-info="state not in ('done', 'cancel', 'draft')" decoration-muted="state == 'draft'"/>
+                    <field name="state" widget='badge' optional="show"
+                           decoration-danger="state=='cancel'"
+                           decoration-info="state== 'assigned'"
+                           decoration-muted="state == 'draft'"
+                           decoration-success="state == 'done'"
+                           decoration-warning="state not in ('draft','cancel','done','assigned')"/>
                     <field name="activity_exception_decoration" widget="activity_exception"/>
                     <field name="json_popover" nolabel="1" widget="stock_rescheduling_popover" attrs="{'invisible': [('json_popover', '=', False)]}"/>
                 </tree>
```

**Comment by boan-odoo** [comment]
@thomasdeleval I also suggest using `muted` for the "draft" state of `stock.scrap` for consistency:
```patch
diff --git a/addons/stock/views/stock_scrap_views.xml b/addons/stock/views/stock_scrap_views.xml
--- a/addons/stock/views/stock_scrap_views.xml	(revision 30fcfcc6c6ebb6fe9620d29475e1a7b6f1a46923)
+++ b/addons/stock/views/stock_scrap_views.xml	(date 1643372848565)
@@ -128,7 +128,7 @@
                     <field name="location_id" options="{'no_create': True}" groups="stock.group_stock_multi_locations"/>
                     <field name="scrap_location_id" options="{'no_create': True}" groups="stock.group_stock_multi_locations"/>
                     <field name="company_id" readonly="1" groups="base.group_multi_company"/>
-                    <field name="state" widget="badge" decoration-success="state == 'done'" decoration-info="state == 'draft'"/>
+                    <field name="state" widget="badge" decoration-success="state == 'done'" decoration-muted="state == 'draft'"/>
                 </tree>
             </field>
         </record>
```

**Comment by thomasdeleval** [comment]
@boan-odoo great idea, thanks!

**Comment by boan-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
