### PR TITLE
[FIX] account: Prevent master account tags removal

### PR DESCRIPTION
**Pull request by tivisse**
This data is used in the chart of account definition and could put the end user into a bad situation.

Related ticket: 3790614

### CODE REVIEW

**Comment by lordkrandel** [comment]
I have some questions:
- There are several things a user can do to destroy his database, we don't impede them all.
  Can you provide some support ticket numbers or task that justifies restricting this?
- What is the code that relies on these tags always to be present?
- Why not `RESTRICT` deletion for all tags if they're currently used in accounts? Or `SET NULL` on delete?
- If these tags are always to be present, maybe they should be a selection field on the account rather than a tag.

**Comment by tivisse** [comment]
Hello @lordkrandel 

> There are several things a user can do to destroy his database, we don't impede them all.

Actually the support team is now sending me the most frequent tickets about data deletion issues. So you're right, we won't impede them all, but we will address all the most frequent ones.

> Can you provide some support ticket numbers or task that justifies restricting this?

I forgot to push the last version with a support ticket on the commit message, my bad.

> What is the code that relies on these tags always to be present?

I don't get your point.

> Why not RESTRICT deletion for all tags if they're currently used in accounts? Or SET NULL on delete?

The issue is not that we cannot delete them when they are used, it's that we can delete them before needing them, as they are declared in ``account`` and referenced by their xmlids in most of the accounting localizations.

> If these tags are always to be present, maybe they should be a selection field on the account rather than a tag.

Maybe, I focus on reducing the simple tickets amount for stable release, I let you start this discussion with your product owner.

Please note that this as been discussed with consultants and Antony, and that's the strategy we decided to adapt for most of the data. See task 3802440 for more details.

Have a nice day,

Yannick.

**Comment by tivisse** [comment]
@robodoo r+

**Comment by lordkrandel** [comment]
Sorry to be late here, but thanks for the info. 👍🏻

**Pull request closed without merging**
