### PR TITLE
[FIX] l10n_cl: Replacing partner demo data

### PR DESCRIPTION
**Pull request by masi-odoo**
Description of the issue/feature this PR addresses: Real information was used as a demo data partner, which caused complaints from the company which was the owner of this information

Current behavior before PR: Data of the affected company available for demo databases

Desired behavior after PR is merged: Data replaced for a fake demo company

Task: [4071645](https://www.odoo.com/odoo/project/1625/tasks/4071645?cids=3)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lordkrandel** [comment]
Change looks good, but it looks like we have some unrelated test that's breaking.
Can you try rebase and see if the CI goes green, please?
Thank you in advance.

**Comment by lordkrandel** [comment]
As you are at it, can you please squash the two commits?
There's no need for a commit just to remove the logo.

**Comment by masi-odoo** [comment]
Hello @lordkrandel I have squashed the commits and now all tests have passed.

Let me know if you need anything else. Thanks!

@ren-odoo @vbe-odoo

**Review by lordkrandel — APPROVED** [review]
LGTM 👍🏻 

@smetl for final review.

**Comment by smetl** [comment]
@robodoo r+

**Comment by masi-odoo** [comment]
Thank you both for the support @lordkrandel @smetl !

I will let you know if there is any problem with FW-Ports.

CC @ren-odoo

**Pull request closed without merging**
