### PR TITLE
Update Romanian Localisation - chart of accounts, taxes, account groups.

### PR DESCRIPTION
**Pull request by feketemihai**
Update datas of Romanian Localisation, please mark it as "work on progress" untill i finish with the taxes review, taxes tags and tax groups.

Probably is ok to superseed #19065 with this one.
@rop-odoo @lap-odoo 

The PR is the base of the https://github.com/odoo/odoo/issues/20497.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lap-odoo** [comment]
@feketemihai Hi, have you been able to progress on this PR (update taxes, taxes tags and tax groups)?

As you suggested, #19065 will be cancelled as it will be managed through your PR. 

Thanks !

**Comment by feketemihai** [comment]
@lap-odoo Hi, i added the taxes tags according to the VAT report that needs to be send to Fiscal Authorities, but still i have to add in taxes the Not Eligible taxes for Cash Basis, i will add them next week..

**Comment by feketemihai** [comment]
@lap-odoo I still have to review them again, retest and update some of the fiscal position mapping...

**Comment by feketemihai** [comment]
@lap-odoo I will add today the reconciliation templates...

**Comment by feketemihai** [comment]
@lap-odoo o saw a commit, https://github.com/odoo-dev/odoo/commit/26a624c17e2e35a784f51fdcefe15a33b9212658, can this pr be a base of that pr...

**Comment by feketemihai** [comment]
@lap-odoo @jao-odoo I made some updates for Not deductible VAT, regarding name, tax group, tags associated. I tested on http://298739-master-l10n-ro-jao-00a3ff.runbot12.odoo.com before this modifications and it was ok, the only issue that i have is for Not Deductible VAT, it's the part that is not deductible and it's put on expenses, that should not be visible in tax report, and i don't see any field that i can restrict it .
I've print also the Decont TVA from l10n_ro_reports module, but since i don't have access to enterprise code, i don't know how it is computed, but as comparition i think it's totally wrong.
 
@jao-odoo Can you pull PR with latest modifications and to recheck...

Thanks.

**Comment by lap-odoo** [comment]
@feketemihai Thank you. 

Regarding the Not Deductible VAT, you can maybe have a look at l10n_be, there is a tax called "50% Non Déductible - Frais de voiture (Prix Excl.)". It's a 21% tax, 10,5% is deductible and 10,5% is not deductible. You can check its configuration to understand how we make that work. 

For the VAT Report, I'll compare what you've done with what is in enterprise and we will correct it accordingly.

**Comment by feketemihai** [comment]
@lap-odoo I've checked before adding them, but that's not correct, 50% deductible, means that 50% from deductible vat you move it to recuperable vat, balanced on an expense account. You can check BILL/2018/0009 from  http://298739-master-l10n-ro-jao-00a3ff.runbot12.odoo.com, the account moves are generated correctly, but the line on
635200 Cheltuieli cu alte impozite, taxe şi vărsăminte asimilate nedeductibile
should not be printed on tax report.

You can check http://298739-master-l10n-ro-jao-00a3ff.runbot12.odoo.com also, i made a invoice per each fiscal position to check all the mappings are done correctly.

**Comment by lap-odoo** [comment]
@feketemihai Are you talking about the generic tax report ? If yes, it's normal. Even the part that is not deductible will appear but in the tax report but we can add it in a specific section. I'll check it when I'll review the branch. Except for this, is everything ready for review ? 

Thanks

**Comment by feketemihai** [comment]
@lap-odoo I know it's normal since it has a tax assigned, but on the "Decont TVA" from l10n_ro_reports should not be printed. The rest is ok for review, i will squash commits after review.

Thanks.

**Comment by feketemihai** [comment]
@lap-odoo Any news on this?

**Comment by lap-odoo** [comment]
@feketemihai I'm testing it (functional testing) right now. There are still issues that we will correct. 

Some questions : 
- The default taxes are 0% taxes, it is well expected ? 
- Can you give me the name of the taxes (50% deductibility) you had issues with ? (that were wrongly displayed in the Romanian tax report)

**Comment by feketemihai** [comment]
@lap-odoo 
Default tax rates are 19%, "TVA colectat 19%" for sale tax, "TVA deductibil 19%" for purchase tax, i can adjust the sequence of this 2 to be taken first.
For 50% deductibility issue, the name is "TVA 19% Nedeductibil 50%" and "TVA 19% Nedeductibil 100%" for 100% not deductible.

Some issues that i found are account pcg_1411 and pcg_1412, this 2 i think it should be of type "data_account_type_non_current_assets", and account pcg_1171 should be "data_unaffected_earnings".

**Comment by lap-odoo** [comment]
@feketemihai We will make the changes for the default taxes. 

For deductibility issues, could you make a screenshot or current behaviour and then explain the expected behaviour (expected data in the romanian tax report) ? 

I see you've created a new account type, we do not create new account types in localization. If I understand it correctly, this is for temporary accounts that should be empty when closing the year, is it correct ? Then why don't you use an account type from the balance sheet and clearly state that's only a temporary account that will be at 0 at the end of the year ?

**Comment by feketemihai** [comment]
@lap-odoo The new type of account is for the account from 8 and 9 classes, their are useful for some accounting operations, but those accounts have no implication into balance sheet, should not be presented into trial balance, and they can have balance at the end of the year, that's why i added a new account type. 

I will make screenshot and upload it here.

**Comment by feketemihai** [comment]
@lap-odoo I tried to launch the "Decont TVA" report from http://303424-master-l10n-ro-jao-2a9f3b.runbot9.odoo.com, but it is complaining about options["analytic_account"], strange is that the option is available in General Ledger...

**Comment by lap-odoo** [comment]
@feketemihai I already noticed the issue and asked a developer to have a look at this and fix it. We'll let you know when it's fixed.

**Comment by feketemihai** [comment]
@lap-odoo Ok, untill then i made a small module how i think it should be, please see https://github.com/feketemihai/d300_enterprise_example, because the report if you grab it from tax tags and then go to taxes will be ok, that's why i added the tax tags for easier reporting...I haven't tested it, but i think @jao-odoo or somebody from https://github.com/ERPsysRO, since they are the owners of the module can adapt it...Thanks.

**Comment by feketemihai** [comment]
@lap-odoo Any news about the runbot?

**Comment by lap-odoo** [comment]
@feketemihai I've just launched a rebuild to verify if traceback is well solved. Branch should be ready in +/- 40 min.

**Comment by lap-odoo** [comment]
@feketemihai We have an issue with the new account type you've created. Can you give an example of an operation you do with this kind of accounts ? Are you sure you shouldn't rather use analytic accounting ? Such kind of account is problematic as it can create unbalanced statements. We do not create new account types with the localization, this has to be corrected in the PR.

**Comment by feketemihai** [comment]
@lap-odoo You have here the Translation of Romanian Chart of Accounts , https://assets.kpmg.com/content/dam/kpmg/ro/pdf/plan-de-conturi-2016-web.pdf,
in most of the cases these accounts are useful to keep track of something that desn't appea anymore in the balance of normal accounts, and by default, account moves generated on this accounts are done on debit and on credit in the same move, to balance the statement.

Example:
- You have a small inventory, bought from a supplier: 
Debit      =  Credit  
pcg_303 =   pcg_401
100         =  100
- You give the product to a employee for use (usage giving): 
Debit        = Credit
pcg_603 = pcg_303
100         =  100
And in the same move we are creating 2 new lines, for tracking purpose
_**pcg_8035 = pcg_8035
100         =  100**_

**Comment by lap-odoo** [comment]
@feketemihai Thanks for the answer ! Ok to keep these specific accounts. Can you please test the branch and let us know your feedback ?

**Comment by feketemihai** [comment]
@lap-odoo I tested my branch and master-l10n_ro-jao from odoo-dev, even that the master-l10n_ro-jao branch doesn't have all the modifications, last commit where i updated default taxes sequences, and unnafected year earnings accounts. I already said at the begining that the l10_ro_reports need to be updated, i don't know if you already have a PR for it or not.

i tested 1993 from enterprise PR,  there i don't have all the modifications as well, new cash basis taxes, new fiscal position for cash basis, cash basis fiscal position mapping. "Decont TVA" from l10n_ro_reports is by far the one that didn't fetches a lot of info for base and vat, i made some remarks on the pdf file, but i have to go until the end for each block in the report. 

[Decont Tva - from l10n_ro_reports (no cash basis taxes).pdf](https://github.com/odoo/odoo/files/1822465/Decont.Tva.-.from.l10n_ro_reports.no.cash.basis.taxes.pdf)
[Tax Report - Enterprise (no cash basis taxes).pdf](https://github.com/odoo/odoo/files/1822466/Tax.Report.-.Enterprise.no.cash.basis.taxes.pdf)
[Tax Report - Community.pdf](https://github.com/odoo/odoo/files/1822467/Tax.Report.-.Community.pdf)

I will add a report from https://github.com/OCA/l10n-romania/tree/11.0/l10n_ro_report_D300, to review how it should look Decont Tva from the l10n_ro_reports, in a few minutes.

**Comment by feketemihai** [comment]
D300 report from  https://github.com/OCA/l10n-romania/tree/11.0/l10n_ro_report_D300 
[D300.pdf](https://github.com/odoo/odoo/files/1822534/D300.pdf)

**Comment by feketemihai** [comment]
@lap-odoo Tested again on http://315899-master-l10n-ro-jao-9524ae.runbot8.odoo.com and it has all the modifications and working fine., The odoo-enterprise 1993 http://315925-1993-d01c16.runbot13.odoo.com is the same, not all the modifications grabbed probably just for the same reason, l10n_ro_reports not updated.

**Comment by feketemihai** [comment]
@lap-odoo Any news about the l10n_ro_reports?

**Comment by lap-odoo** [comment]
@feketemihai The work is still ongoing for the reports

**Comment by rgo-odoo** [comment]
Hello @feketemihai 

I reworked on your code and created new branches(<a href="https://github.com/odoo/odoo/compare/master...odoo-dev:master-l10n_ro-jao3">community</a>, <a href='https://github.com/odoo/enterprise/compare/master...odoo-dev:master-l10n_ro-jao3'>enterprise</a>) that has minimal diff. I also adapted existing enterprise report `Decont TVA` to the community changes. Can you please check it <a href="http://runbot.odoo.com/runbot/repo/git-github-com-odoo-dev-enterprise-8?search=-jao3">here</a> if the report now hold all the information you wanted and if it fetches correct information ?

Also, is it necessary to have Decont report in the the format you shown in D300 report or if the existing enterprise report is enough ?

Thanks

**Comment by feketemihai** [comment]
@rga-odoo I will test it today or tomorrow, and let you know. By default, the Decont 300 is the official declaration that you have to supply to the fiscal authorities (https://static.anaf.ro/static/10/Anaf/Declaratii_R/AplicatiiDec/D300_XML_310117.pdf), but if the Enterprise report holds the right data (the base and vat amount), an account should just map the values to the right position in the official report.

**Comment by rgo-odoo** [comment]
@feketemihai did you get a chance to test the PR ?

**Comment by feketemihai** [comment]
@rgo-odoo i test it only for sales but there are some discrepancies.. I will test it again in 2or3 of January for both, sales and purchases and will make comments on the code.

**Comment by rgo-odoo** [comment]
@feketemihai can you please test the PR and share your inputs on the same ?
Thanks.

**Comment by jigalojack** [comment]
Thank you so much for your time and consideration in this matter is greatly appreciated thank you

**Comment by jcr-odoo** [comment]
@feketemihai Hello, do you have the time to test the development? Your input would be highly appreciated.

**Comment by jco-odoo** [comment]
Hi @feketemihai ,  I see there is quite a history on this PR.  I see that a lot of tags are added, while maybe in the meantime we changed the philosophy to have only one tag per line in the vat report.  Do you see a problem to change it to one tag per grid?  

Also tax deductibil 19% nedeductibil 100% seems to go in the same line in the report as the regular 19%.  Is this correct?

**Comment by jcr-odoo** [comment]
@feketemihai Hey, could you give your input on the recent comments? I am willing to push this task to an end but we would need your help and input.

**Comment by jcr-odoo** [comment]
@feketemihai Hello, can you please check my latest comment?

**Comment by feketemihai** [comment]
@jcr-odoo I will take a look tomorrow, and try to update it .

**Comment by pedrobaeza** [comment]
Coming to this through codetriage.com. Is this still relevant?

**Comment by feketemihai** [comment]
@pedrobaeza You can close it since it's superseeded by #39577. Thnaks

**Comment by feketemihai** [comment]
@pedrobaeza Also #39577 can be closed since from it @rgo-odoo created https://github.com/odoo/odoo/pull/41003 for 13.0 and https://github.com/odoo/odoo/pull/43095 for master

**Comment by pedrobaeza** [comment]
Great, let's clean a bit, thanks.

**Pull request closed without merging**
