### PR TITLE
[FIX] project: fix sub-tasks notebook shadow issue

### PR DESCRIPTION
**Pull request by ravb-odoo**
[FIX] project: fix sub-tasks notebook shadow issue

Description of the issue/feature this PR addresses:
In the website when task of project is open, sub tasks notebook has dark shadow
below the list. Shadow should be same as sub tasks list in backend.

Current behavior before PR:
Sub tasks notebook has dark shadow below the list in website.

Desired behavior after PR is merged:
Sub tasks notebook has same shadow as in backend project module.

causes:
in project sharing, gradient of 0.4 opacity is apply on shadow for dark mode in 
list_controller.dark.scss file so that shadow effect is shown in dark mode 
which is also apply on light mode therefore shadow is dark in light mode

Fix:
As all the list view in project sharing have same issue, so we create file in 
project and override the  css for shadow for light mode.

task-3217427

### CODE REVIEW

**Review by auon-odoo — CHANGES_REQUESTED** [review]
But why was this shadow so strong in the first place?

**Comment by ravb-odoo** [comment]
related: https://github.com/odoo/enterprise/pull/35981

gradient of 0.4 opacity is apply on shadow for dark mode in list_controller.dark.scss file which is also apply on light mode therefore shadow is dark in light mode

**Comment by auon-odoo** [comment]
So it is a generic issue?

**Comment by ravb-odoo** [comment]
yes it is generic

**Comment by auon-odoo** [comment]
So the fix shouldn't be specific to project, right?

**Comment by auon-odoo** [comment]
Ok, but does it only happen in project?
Here's how your commit message should be structured when your commit is a fix :
- Steps: how to reproduce the bug (already in your commit message :ok_hand:)
- Issue: what is expected vs what is happening (already in your commit message :ok_hand:)
- Cause: (most important!) technical explanation of the issue (missing)
- Fix: why your fix is the best solution to the cause (missing)

This structure is specific to Services team, but it is generally good. (You might want to skip some points or even all of them if super obvious.)
It will allow your reviewer to quickly get what you're doing, or even help you rethink your fix.
Please apply it to this commit :slightly_smiling_face:

**Comment by ravb-odoo** [comment]
commit message edited!!

**Comment by auon-odoo** [comment]
Thank you, but it is still not obvious. Why is dark mode apply to light mode?

**Comment by ravb-odoo** [comment]
basically this happen due to dark mode. As in website(front-end), dark mode is not apply. website is always open in light mode due to which shadow we apply on dark mode is visible in light mode so that shadow is dark and to overcome this issue we create new file to apply CSS for website.

**Comment by auon-odoo** [comment]
So the issue is that dark mode is active and its style applies to this shadow, even though the front-end still looks in light mode?
If true, the fix should be generic and aim to disable dark mode when in front end.

**Comment by ravb-odoo** [comment]
Hello @auon-odoo 

I have fix this issue in enterprise so no longer need of this PR. So should I close this PR?
could you check it when you have a time?

Ref: https://github.com/odoo/enterprise/pull/40668

**Comment by auon-odoo** [comment]
Perfect, thank you!

**Pull request closed without merging**
