### PR TITLE
[FIX] account: Fix indian taxes computation.

### PR DESCRIPTION
**Pull request by smetl**
For the indian case, when facing two percent price-included taxes having the same percentage, both need to produce the same tax amounts.

task_id: 3410529

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
/!\ WE NEED TO ADAPT THE POS TAXES COMPUTATION ACCORDINGLY AFTER THE REVIEW BUT BEFORE MERGING!!!!!!!!!!

**Comment by tsb-odoo** [comment]
LGTM functionally speaking

**Comment by jva-odoo** [comment]
FYI: This is not needed in the master because we plan to add an HSN summary in POS and Invoice which fulfils what we need as instructed by Government.
after that, we remove a group of tax and replace it with one tax with 50%-50% on repartition line

**Comment by smetl** [comment]
@jva-odoo No way. Don't convert your double taxes to a 50-50 rep lines -_- Just wait for https://github.com/odoo/odoo/pull/148164 and everything will be perfect in POS too

**Pull request closed without merging**
