### PR TITLE
[FIX] mail: model manager is debug during tests

### PR DESCRIPTION
**Pull request by tsm-odoo**
Since the PR introducing the wowl environment in the discuss app, the
model manager is not set in debug mode during tests. The debug mode
is usefull since it adds integrity checks and more verbose error
messages. This commit restores it.

enterprise: https://github.com/odoo/enterprise/pull/31086

### CODE REVIEW

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

**Review by seb-odoo — APPROVED** [review]
@robodoo r+ rebase-ff

**Comment by alexkuhn** [comment]
Another problematic manual `.update()` in a computed field of Emoji Picker, keeping this PR red.
Here is the fix: https://github.com/odoo/odoo/pull/99782

**Comment by alexkuhn** [comment]
(push-forced with prepend commit of https://github.com/odoo/odoo/pull/99782)

**Comment by alexkuhn** [comment]
@robodoo r+ rebase-ff

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
