### PR TITLE
[IMP] account: test the introduction of new tax rates

### PR DESCRIPTION
**Pull request by william-andre**
This commit aims at better defining how to handle tax rates being updated for some taxes, and test the procedure.

### CODE REVIEW

**Review by clbr-odoo — APPROVED** [review]
Very cool, we can use this "doc" and complete it whenever we stumble on a frequently asked question. Then transform it into an official documentation page/knowledge.
Thanks,
@robodoo r+

**Comment by william-andre** [comment]
@robodoo r-
TSB just asked me to remove something :sweat_smile:

**Comment by william-andre** [comment]
@clbr-odoo Sorry about that, should be good now!

**Comment by clbr-odoo** [comment]
:see_no_evil: 
@robodoo r+

**Pull request closed without merging**
