### PR TITLE
[CLA] update for grap (v16)

### PR DESCRIPTION
**Pull request by quentinDupont**
Add myself for CLA

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@quentinDupont you are a member of grap.coop? You don’t have a corporate email address?
cc @legalsylvain

**Comment by quentinDupont** [comment]
> @quentinDupont you are a member of grap.coop? You don’t have a corporate email address? cc @legalsylvain

Yep i'm a member of grap.coop and i have a corporate email adress but my github account is set with my personnal adress so I taught it was better to set this one ??

**Comment by legalsylvain** [comment]
The GRAP CLA is here : 

https://github.com/odoo/odoo/blob/17.0/doc/cla/corporate/grap.md

**Comment by mart-e** [comment]
> my github account is set with my personnal adress so I taught it was better to set this one ?

While not technically forbidden, it’s clearer if all members of an organisation uses the same domain.
In https://github.com/settings/emails you can configure multiple email addresses and specily which one use by default. Then, use `git config user.email` to specify which to use inside a git repository.

**Comment by quentinDupont** [comment]
> > my github account is set with my personnal adress so I taught it was better to set this one ?
> 
> While not forbidden, it’s clearer if all members of an organisation uses the same domain. In https://github.com/settings/emails you can configure multiple email addresses and specily which one use by default. Then, use `git config user.email` to specify which to use inside a git repository.

that's ok for me ! i make the changes

**Comment by mart-e** [comment]
If you amend an existing commit, don’t forget to amend the author email address as well :
```
$ git commit --amend --author="Name <email>"
```
for the CLA check to be valid, the email used [in your commit](https://github.com/odoo/odoo/pull/171169.patch) must be present in the CLA file

**Comment by quentinDupont** [comment]
> If you amend an existing commit, don’t forget to amend the author email address as well :
> 
> ```
> $ git commit --amend --author="Name <email>"
> ```
> 
> for the CLA check to be valid, the email used [in your commit](https://github.com/odoo/odoo/pull/171169.patch) must be present in the CLA file

Thank you for your advice, i amend my commit :)

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by mart-e** [comment]
@robodoo r+

**Pull request closed without merging**
