### PR TITLE
[IMP] sms: add index for sms_uuid to improve performance

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
-We might performing search a lot so adding index would be very nice

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Hello @awa-odoo @flch-odoo can you take a look sir ?

**Comment by tde-banana-odoo** [comment]
sms_uuid has an unique constraint, which means it has an index as far as I know.

**Comment by duong77476-viindoo** [comment]
> sms_uuid has an unique constraint, which means it has an index as far as I know.

Are you sure Mr Banana, when i check on pgAdmin, it is doesn't
image
Or i miss something maybe ?

**Comment by duong77476-viindoo** [comment]
@tde-banana-odoo Oh yes, you 're right
image

**Pull request closed without merging**
