### PR TITLE
[FIX] web: support oe_read_only and oe_edit_only in x2m list

### PR DESCRIPTION
**Pull request by svs-odoo**
Back-port of this : https://github.com/odoo/odoo/pull/36117

### CODE REVIEW

**Comment by svs-odoo** [comment]
@aab-odoo The backport of the fix of the last friday, if you remember

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo retry

**Comment by d-fence** [comment]
robodoo retry

**Pull request closed without merging**
