### PR TITLE
[FIX] delivery: use tracking number only once

### PR DESCRIPTION
**Pull request by adwid**
When having a shipper for a DO, if the user creates a backorder, the
information won't be sent to him.

To reproduce the issue:
(Use demo data)
1. Create a sale order SO with 2 products
2. Add Shipping: UPS US
3. Confirm SO
4. In the associated picking, deliver one of the products and create a
backorder
5. Process the backorder

Error: In the chatter, there is a label for the first picking but there
isn't any label for the backorder

When confirming the sale order, the backorder is first created and then
the initial picking is sent to UPS. As a result, considering the current
body of `send_to_shipper`, the field `carrier_tracking_ref` of both the
initial picking and the backorder is defined with the same value (i.e.,
the tracking number of the initial picking)

Therefore, when processing the backorder:
https://github.com/odoo/odoo/blob/f29da79ef64a8166e54544d1787912be5665076a/addons/delivery/models/stock_picking.py#L126-L129
`carrier_tracking_ref` is already defined, so `send_to_shipper` won't be
called

The tracking number should be related to only one picking.

OPW-2678549

### CODE REVIEW

**Comment by adwid** [comment]
Hi @odoo/rd-logistics could one of your review this ?

**Comment by adwid** [comment]
Linked to https://github.com/odoo/enterprise/pull/22619

**Comment by Whenrow** [comment]
The idea of putting the ref tracking number on every pickings is to have the number available at each step of a pick - pack - ship chain. I think this feature won't work anymore with your patch :worried:

**Comment by adwid** [comment]
What would you think about something like:
```diff
diff --git a/addons/delivery/models/stock_picking.py b/addons/delivery/models/stock_picking.py
index d4297558f33..acee66f83cc 100644
--- a/addons/delivery/models/stock_picking.py
+++ b/addons/delivery/models/stock_picking.py
@@ -173,8 +173,15 @@ class StockPicking(models.Model):
             res['exact_price'] = 0.0
         self.carrier_price = res['exact_price'] * (1.0 + (self.carrier_id.margin / 100.0))
         if res['tracking_number']:
-            pickings = self.sale_id.picking_ids or self
-            pickings.carrier_tracking_ref = res['tracking_number']
+            previous_pickings = self.env['stock.picking']
+            previous_moves = self.move_lines.move_orig_ids
+            while previous_moves:
+                previous_pickings |= previous_moves.picking_id
+                previous_moves = previous_moves.move_orig_ids
+            without_tracking = previous_pickings.filtered(lambda p: not p.carrier_tracking_ref)
+            (self + without_tracking).carrier_tracking_ref = res['tracking_number']
+            for p in previous_pickings - without_tracking:
+                p.carrier_tracking_ref += ";" + res['tracking_number']
         order_currency = self.sale_id.currency_id or self.company_id.currency_id
         msg = _(
             "Shipment sent to carrier %(carrier_name)s for shipping with tracking number %(ref)s<br/>Cost: %(price).2f %(currency)s",
```
(So, in multi-step, the previous pickings accumulate the tracking reference with `;` as separator)

**Comment by Whenrow** [comment]
robodoo r+

**Pull request closed without merging**
