### PR TITLE
[FIX] BOM structure Report: component prouct quantity zero

### PR DESCRIPTION
**Pull request by hajajroshan**
Description of the issue/feature this PR addresses:
#68125

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You need to sign CLA.

@amoyaux maybe you can check this.

**Comment by lathama** [comment]
@hajajroshan knowing that 14 is no longer updated, is this PR still needed?

**Comment by hajajroshan** [comment]
> @hajajroshan knowing that 14 is no longer updated, is this PR still needed?

Not needed

**Comment by lathama** [comment]
@hajajroshan please close this PR if it is not needed.

**Comment by C3POdoo** [comment]
Dear @hajajroshan,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
