### PR TITLE
[IMP] website_sale, payment: create payment button widget

### PR DESCRIPTION
**Pull request by vchu-odoo**
Before this commit, the payment button was part of the checkout/manage form widgets, which caused conflicts when other modules needed to enable/disable the button depending on custom conditions.

After this commit, the payment button logic is extracted in a separate widget that handles its enabling after checking if all conditions are satisfied. Other modules can extend the widget and override `isButtonReady` to add custom logic.

task-3568861

Related: odoo/enterprise#51250

### CODE REVIEW

**Review by vchu-odoo — COMMENTED** [review]
Hello,
thank you for adapting your changes of fixing the bug here!

However, I should have explained the changes that I backported first, sorry for that. So we extracted the payment button in the separate widget and when you need to enable it you trigger the bus.
The payment button widget will call isReady() before enabling the button that checks that all conditions are satisfied. 
I believe that what you want to do is to add the condition isDeliverable() to check if the payment button should be enabled. That you can do by adapting an override of isReady() in website_sale/static/src/js/payment_button.js.
Let me know if I miss something.

**Comment by mama-odoo** [comment]
> Hello, thank you for adapting your changes of fixing the bug here!
> 
> However, I should have explained the changes that I backported first, sorry for that. So we extracted the payment button in the separate widget and when you need to enable it you trigger the bus. The payment button widget will call isReady() before enabling the button that checks that all conditions are satisfied. I believe that what you want to do is to add the condition isDeliverable() to check if the payment button should be enabled. That you can do by adapting an override of isReady() in website_sale/static/src/js/payment_button.js. Let me know if I miss something.

Hello vchu,
Thanks for the information,
I've well understood that all the checks are done in the `isReady()` function of the `paymentButton` widget that has 2 listeners designed to enable/disable the button.
What restrain me actually is not how the code works but the design choices behind it, more specifically the share of responsibilities between the widgets.
I'm not really fan of the fact that the paymentButton widget has a _isCarrierReady() method that do DOM checks on the websiteSaleDelivery widget, while on the other side, the websiteSaleDelivery widget must explicitely trigger enable or disable on the paymentButton widget, it's from my point of view a mixup in responsibilities and consistencies of each widget, which lead to an over binding in-between them.
I think thaht each widget should be responsible of its own scope and thus, of it's own state.
By implementing a bus, we implement a publisher/subscriber pattern. In which ideally, publisher should not care about who listen.
In that case, WebsiteSaleDelivery should be the one who compute its state of "readiness" and publish it whenever it changes to whoever listen, without caring about the behavior it will trigger, while paymentButton on its side should decides of which behavior it applies on itself based on the dataflow it has subscribed to.
Going this way would simplify future maintenance of the codebase as reponsibilities of each widget are minimzed and centralized in their own methods.
It would also avoid to overload the developper with intricated dataflow, thus minimizing risk of errors.
So it takes some time as I'm actually trying to find the best compromise to keep your modification as it while decoupling as mush as possible the websiteSaleDelivery widget and its inheritance.

**Comment by AntoineVDV** [comment]
Hi @mama-odoo, I get your point, and I'd actually go for it if we had several widgets (the payment button + others) that depended on the states of the payment, delivery and terms&conditions widgets, but, in this case, I think the design implemented in https://github.com/odoo/odoo/pull/142980/commits/70ca1565a00603fbba3b61847c46906a5423437f is simpler and better suits our needs. Here, the only role of the `paymentButton` widget is to define a single protocol for enabling/disabling the button if all module-specific requirements for enabling are met. So, it doesn't shock me that the logic for these requirements is defined directly on the `paymentButton` widget.

Switching from this design to the one you suggest would require creating an interface to allow widgets to register as observables, and keeping and managing in memory the state of all widgets, i.e., more logic to implement. I don't think that it would be simpler to understand and easier to maintain. It would certainly be cleaner from a theoretical point of view, and easier to port to other flows, but I prefer to stick to the less abstract, direct implementation of the simple requirements we have for this eCommerce flow.

Also, keep in mind that `websiteSaleDelivery.js` is an utter mess, and we plan to refactor the crap out of it in master while keeping it on life support in stable.

**Comment by vchu-odoo** [comment]
We decided to merge PR without last commit in order to prevent other bugs in 16.2.
Dropped commit: 
- https://github.com/odoo/odoo/pull/142980/commits/4df7f4143c33a4f88ee705a7e333fb802a3f09e4

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+
@fw-bot ignore

**Comment by AntoineVDV** [comment]
@robodoo rebase-ff

@robodoo override=ci/security
Reason: `innerHTML`: receives a string literal free of user input
Link to ci/security build (saas-16.2): https://runbot.odoo.com/runbot/batch/1282373/build/56225454

**Pull request closed without merging**
