### PR TITLE
[CLEANUP] DOC

### PR DESCRIPTION
**Pull request by blaggacao**
Those params are documented, but don't exists as documented.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by blaggacao** [comment]
It would be also a good idea to document the difference between `fields` and `fieldsInfo` and, specifically where they come from, each.

**Comment by blaggacao** [comment]
I guess, this was replaced by a more dynamic `_getFieldNames` so document that better, instead.

**Comment by blaggacao** [comment]
```js
     * @param {Object} params.fieldsInfo contains the fieldInfo of each view,
     *   for each field
     * @param {Object} params.fields contains the description of each field
```

I think it doesn't document well the behavior or at least it's not verbose enough.
Especially misleading: "description"

**Comment by blaggacao** [comment]
Another overlook: 
`If not given, fetch all the fields in record.fieldNames`
should be:
`If not given, fetch all the fields returned by record.getFieldNames()`

**Comment by blaggacao** [comment]
Not touching code and runbot fails. lol :hushed:

**Comment by KangOl** [comment]
You were based on red revision. Can you rebase?

**Comment by pedrobaeza** [comment]
Coming to this from codetriage.com. Is this still relevant?

**Comment by blaggacao** [comment]
I'm not maintining this PR actively.

**Comment by C3POdoo** [comment]
Dear @blaggacao,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
