### PR TITLE
[FIX] Correct html in POS ticket

### PR DESCRIPTION
**Pull request by pfranck**
Description of the issue/feature this PR addresses:
after depreciation of t-raw - the fields to add footer and header in html used are now t-out that escape the HTML given. Therefore we need to use the Markup to transform the HTML so it can be processed correctly in the Qweb template.
fields used in Template: 
 - https://github.com/odoo/odoo/blob/92aa004694f62ac979e9bf962f44d6f7f166a7ce/addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml#L33C15-L33C15
- https://github.com/odoo/odoo/blob/92aa004694f62ac979e9bf962f44d6f7f166a7ce/addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml#L135

Current behavior before PR:
HTML content in POS ticket is treated as string

Desired behavior after PR is merged:
HTML content in POS ticket is treated as HTML

Issue: https://github.com/odoo/odoo/issues/136123

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pfranck** [comment]
@caburj Anything I can do to help to process this MR?
This is a regression as it's working on Odoo 15.0 but not in 16.0 - let me know if you need any other context for the security team

**Comment by caburj** [comment]
> @caburj Anything I can do to help to process this MR? This is a regression as it's working on Odoo 15.0 but not in 16.0 - let me know if you need any other context for the security team

I think before the security team approves, we need to make sure that the values of `receipt_header` and `receipt_footer` fields are sanitized.

Hi @odoo/rd-security, can you help us safely restore the feature where the header and footer fields can be rendered as html when their values are prefixed with `<!DOCTYPE QWEB`? Do you think we can do something like this:

```
@ at server when loading of pos data
receipt_header := pos_config.receipt_header
if receipt_header is html:
    sanitize(receipt_header)

@ pos ui during loading of app
markup(rendered receipt_header) <- Just as proposed in this PR.
```

Maybe we can also do something like this:
```
@ write of pos.config
if receipt_header is supposed to be html:
    sanitize before saving to database
```

The problem is when the database already has malicious field values.

**Comment by caburj** [comment]
@pfranck As per the response from the security team, we need to sanitize the value of receipt_header/footer during the loading of data, such that when it reaches the browser, wrapping it in `Markup`, as you proposed, is safe. Can you apply that change in this PR?

In the `_pos_data_process` method, there is `loaded_data` with key `'pos.config'` pointing to the search_read result of the pos.config model. Reassign the header and footer values with the sanitized versions.

**Comment by pfranck** [comment]
@caburj I made sure to sanitize only the text if it's considered as HTML text and deport part of the logic from JS to Python

**Review by xmo-odoo — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
