### PR TITLE
[FIX] account: Fix compute_all of taxes when dealing with refunds

### PR DESCRIPTION
**Pull request by smetl**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
@KangOl This PR should fix the saas-12.4 after forward-port. I'm waiting the runbot to make sure I can merge it

**Comment by KangOl** [comment]
Why are you rounding twice?

**Comment by smetl** [comment]
@KangOl The cumulated sum is done unsigned but we need to sign at the end. Then, we round one time for each multiplication

**Comment by smetl** [comment]
@KangOl The second round could be removed I think...

**Comment by jco-odoo** [comment]
@robodoo delegate+

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
