### PR TITLE
[FIX] base: change default Norwegian date format

### PR DESCRIPTION
**Pull request by MerlinGuillaume**
The date format set on the Norwegian language is not kept when we click on date fields

Steps to reproduce:
1. Install Sales
2. Install and switch to Norwegian language
3. Open Sales and create a new quotation
4. Click on the 'Quotation Date' field
5. The date format is changed from '%d. %b %Y' to '%Y/%m/%d'

Solution:
Change the default Norwegian date format to a valid static format
The format used comes from babbel[^babbel], double checked with the Norwegian locale[^nb.js]
[^nb.js]: https://github.com/odoo/odoo/blob/16.0/addons/web/static/lib/moment/locale/nb.js#L25
[^babbel]: https://www.babbel.com/en/magazine/how-to-write-the-date-in-norwegian

Problem:
The old date format didn't pass the `isValidStaticFormat` test of the date picker, so the default format 'yyyy/MM/dd' was used instead

opw-3191605

### CODE REVIEW

**Review by rco-odoo — APPROVED** [review]
Looks fine to me.

**Review by rco-odoo — CHANGES_REQUESTED** [review]
Oh wait, the change and commit message are inconsistent.
* in the diff: `"%d/%m/%Y"`
* in the commit message: `"%Y/%m/%d"`

Please fix the inconsistency.

**Comment by MerlinGuillaume** [comment]
@rco-odoo The step
> 5. The date format is changed from '%d. %b %Y' to '%Y/%m/%d'

in the commit message is just to explain the issue: for example the date `28. feb. 2023` switches to `2023/02/28` when we click on it

**Comment by rco-odoo** [comment]
> > 5. The date format is changed from '%d. %b %Y' to '%Y/%m/%d'
> 
> in the commit message is just to explain the issue: for example the date `28. feb. 2023` switches to `2023/02/28` when we click on it

Oops, my bad.  I read that sentence too quickly and misinterpreted it as _your_ change.  So it's all good, then.

**Comment by kitan191** [comment]
@robodoo delegate+

**Comment by MerlinGuillaume** [comment]
@robodoo r+

**Pull request closed without merging**
