### PR TITLE
[9.0] [FIX] env/bin/openerp-gevent: [Errno 2] No such file or directory

### PR DESCRIPTION
**Pull request by max3903**
Superseeds #8551

### CODE REVIEW

**Comment by flotho** [comment]
Have a look there : https://github.com/odoo/odoo/pull/10150
Your PR probably won't be merged because another strategy will be implemented https://github.com/odoo/odoo/pull/10207

**Comment by max3903** [comment]
@flotho #10207 is a pull request against the master branch. It is too late to apply this new strategy on 9.0 as it has been released.

**Comment by flotho** [comment]
Hi @max3903, you're right I didn't check this.
Maybe @sle-odoo could tell us if it will be simple to backport  #10207 to th e9.0 branch.
regards

**Comment by flotho** [comment]
Hi @sle-odoo, any chance this PR to be validated? The proposed #10207 is for master and not for the main 9.0 branch

regards

**Comment by tivisse** [comment]
Hello,

Thank you for the report but I will have to reject this, sorry.

The 9.0 is now in end of life cycle and will soon be unsupported. We are only patching critical or security issues. The risk of regressions or introducing side effects is too high.

Regards

**Pull request closed without merging**
