### PR TITLE
[FIX] web: speed up tests by parsing OWL templates only once

### PR DESCRIPTION
**Pull request by seb-odoo**

### CODE REVIEW

**Comment by seb-odoo** [comment]
To get an idea of the expected result `test_js` on runbot went from 199.49s to 176.43s with this PR.

**Comment by aab-odoo** [comment]
@seb-odoo You may have been a bit too quick to draw conclusions, see the last saas-13.3 builds: 

https://runbot.odoo.com/runbot/build/3723088 : 609 run_unit_tests odoo.addons.web.tests.test_js ran 3 tests in **179.58s**, 2089 queries
https://runbot.odoo.com/runbot/build/3722473 : 609 run_unit_tests odoo.addons.web.tests.test_js ran 3 tests in **184.57s**, 2073 queries

It could be interesting to make several builds of your code to get a more accurate idea of its impact.

Not that in the master, the suite takes ~240s to execute, so something significant occurred after saas-13.3, but I don't know what. If you want to speedup the test suite, it could be interesting to investigate. 

About this specific commit, I don't like the fact that you store the qweb instance on the session. Did you consider creating a single instance in the scope of 'web.testEnv'?

**Comment by seb-odoo** [comment]
For the timing, you need to see it in relation to `test_click_everywhere` above, in both of your examples it was faster (2s and 3s out of 30s as compared to by reference build). That would explain `test_js` being 10% faster too. It would be expected that with such timing the results of this PR would be in the 160s if not even below.

As for master, it's worse because there are a lot more templates to parse so it's much slower. I originally noticed the issue in 13.4 because it is really bad there, and it's only going to get worse. There might also be more tests calling that helper altogether as well.

I tried to create a single instance but it would require to wait on session.is_bound or similar at the top of `web.testEnv`. If that's fine then I can do it.

**Comment by aab-odoo** [comment]
> I tried to create a single instance but it would require to wait on `session.is_bound` or similar at the top of `web.testEnv`

Not if you instantiate it in a lazy way:
```js
let qweb;
function makeTestEnv() {
     if (!qweb) {
        qweb = new QWeb(...);
     }
     env = {
         qweb,
     };
} 
```

**Comment by seb-odoo** [comment]
Adapted accordingly

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by seb-odoo** [comment]
On 13.4: from more than 260s to less than 200s

**Pull request closed without merging**
