### PR TITLE
[FIX]Reserve is not available in partially state

### PR DESCRIPTION
**Pull request by flotho**
CLOSE https://github.com/odoo/odoo/issues/11019

### CODE REVIEW

**Comment by flotho** [comment]
Hi @odony 

Don't know what's wrong with my CLA: https://github.com/odoo/odoo/blob/9.0/doc/cla/individual/flotho.md
Didi I miss something?

**Comment by odony** [comment]
@flotho The problem with your CLA signature is that your commits are done with a git `user.email` that is different (`mailinglist@...`). Easiest fix is to correct your git config, rebase and `push -f` your branch.

**Comment by flotho** [comment]
@odony ,
here you are!

**Comment by odony** [comment]
@flotho Looks good, thanks for the update! BTW you can put the reference "Closes #11019" in the commit message as well, so that the issue gets automatically closed when the PR is merged :-) Don't worry though, we'll usually do it for you if you forget.

@jco-odoo LGTM, but perhaps this belongs to 8.0? I'll let you merge it :-)

**Comment by flotho** [comment]
Any chance to be merged?

**Comment by tivisse** [comment]
Hello,

Thank you for the report but I will have to reject this, sorry.

The 9.0 is now in end of life cycle and will soon be unsupported. We are only patching critical or security issues. The risk of regressions or introducing side effects is too high.

Regards

**Pull request closed without merging**
