### PR TITLE
[FIX] l10n_ch: add _auto_init for l10n_ch_isr_number of account.move

### PR DESCRIPTION
**Pull request by Arnaud-Sibille**
Problem:
Large database of more than 300.000 moves cannot install the l10n_ch module, due to memory limit.

Cause:
The field 'l10n_ch_isr_number' of the inherited 'account.move' model is computed and stored.  So when installing the module, it will compute this field for all existing moves, which takes a lot of memory.

Solution:
Overwrite the _auto_init method to create and update the field's column through sql instead.

opw-3060951

### CODE REVIEW

**Comment by Arnaud-Sibille** [comment]
inspired by:
github.com/odoo/enterprise/pull/31654

**Comment by Levizar** [comment]
On hold until checking if the value are created correctly when accessing the record's value.
---> I don't think so and it will probably requires one more script to fill the values.

**Comment by Arnaud-Sibille** [comment]
@Levizar 
So if before installing the modules, you have some `account.move` whose `partner_bank_id` has an `acc_number` who is a valid Switzerland QR IBAN (for example `CH44 3199 9123 0008 8901 2`) , then the computed field will have a non NULL value when installing the module.  So we cannot set everything to NULL.
As the computation is not easily translated into SQL, I asked AVD and he said it was not worth writing a long and not easy to read query.
We have solution for the customer (create the column -> install the module -> call the compute method per batch), so unless if you say there's functionally no problem in setting the field to NULL anyway, we can give up this PR.

**Comment by Levizar** [comment]
I think an good solution could be to add a post init function and to filter on the first criteria of the method:
```py
            has_qriban = record.partner_bank_id and record.partner_bank_id._is_qr_iban() or False 
             isr_subscription = record.l10n_ch_isr_subscription
```

You only search for the move that match those and call the compute method on them.
I think there might be less results.

**Pull request closed without merging**
