### PR TITLE
[IMP] web: update pdfjs to 2.16.105

### PR DESCRIPTION
**Pull request by xmo-odoo**
Our current version is getting rather outdated. Replace by the *legacy* bundle: pdfjs now provides a non-polyfilled version of the library, which is probably faster though it doesn't save overly much (for the entire bundle anyway). Use polyfilled version for safety, though it's unclear whether non-chromium Edge is still supported by Odoo. If not, we could just use the non-polyfilled version.

The difference is quite large for pdf.js (+32.5%), however it is much less consequential for the sandbox (+1%) or for the much larger worker (+5.6%). The biggest difference is likely performances but... who knows?

Notes:

- The main reason for this change is that automated vulnerability scanner have apparently started scanning for `postMessage(..., '*')` and the previous bundles includes a version of corejs polyfills without zloirock/core-js#542), therefore triggering those scans. As the PR notes this is almost certainly not a concern because of the innocuous payload, but there is no reason to waste time on those reports if we don't *have* to.
- The bundle now includes "standard fonts", those were removed as they're heavy and may not be necessary for our usage (?).
- All the bitmap images were dropped and replaced by svgs, which is nice.
- Previously local / bespoke changes:

  - 32c8922432fd21ea01468ea05aa76fa1bb4c9890 DOM dispatching has been removed, hook into pdfjs's event system
  - 2d5dd1448fcb86b5977ac10bf672698a065d18b9 seems to be the default now
  - 74fa91e0b381d1eaee188a95620d3ea84ffb5fe3, re-apply change in default configuration
- pdfjs has migrated from lots of its objects / operations being / returning promises, to the result objects containing promises, this has required quite a few adaptations in website_slides

### CODE REVIEW

**Comment by xmo-odoo** [comment]
- lint fails because the debugger itself (and the hook to open it) use `import` calls, which are an es11 / ES2020 feature.

**Comment by xmo-odoo** [comment]
Problems for 32c8922432fd21ea01468ea05aa76fa1bb4c9890:
- `eventBusDispatchToDOM` has been removed, needs to use the eventBus
- reader now shows up with multiple pages and renders everything upfront

**Comment by xmo-odoo** [comment]
2d5dd1448fcb86b5977ac10bf672698a065d18b9: behaviour we want *seems* to be the default now?

**Comment by xmo-odoo** [comment]
74fa91e0b381d1eaee188a95620d3ea84ffb5fe3: probably reimplement the same: looks like ideally we'd want to hook into the initialisation of the viewer and update the config there, but there are multiple sources from which the viewer can be included / set up which makes that a difficult proposition.

There should probably be a single owl component for embedding a PDF viewer, which we could more reliably / uniformly set up, and from which we could expose methods and events working cross-frame without the user of the viewer being concerned.

**Comment by xmo-odoo** [comment]
@fda-odoo @tivisse I think your teams have pretty involved uses of the PDF viewer, could someone check if this update does work correctly?

Also I guess @odoo/rd-sm for knowledge and stuff? But that might be a "baser" and less involved use e.g. just view PDFs not manipulate or overlay them?

**Comment by fda-odoo** [comment]
@lobaudoux Can I ask you to check this PR? Thank you :)

**Comment by lobaudoux** [comment]
Hello @xmo-odoo ,

It looks like there is an issue with the `pagerendered` PDF.js event which prevents the OCR boxes display to work properly.
If the pages are re-rendered, the boxes won't re-appear after a field is focused.

This happens because our component tries to re-use the previously rendered box layers (see https://github.com/odoo/enterprise/blob/16.0/account_invoice_extract/static/src/js/invoice_extract_form_renderer.js#L121)
After a PDF.js re-render, the box layer will still exist but will be detached from the DOM, so it can't be re-used.
That's why we are listening to the `pagerendered` event, when it is triggered, the box layers are discarded (see https://github.com/odoo/enterprise/blob/16.0/account_invoice_extract/static/src/js/invoice_extract_form_renderer.js#L206)

There is an easy fix though. I think we can simplify the code by destroying the box layers when the field is blurred and never re-use them. The cost of re-rendering them is pretty much negligible from the testing I've just made.
If you agree with that, I'll push a commit that does just that.

cc: @fda-odoo

**Comment by awa-odoo** [comment]
Hello @xmo-odoo 

This library update apparently breaks the website_slides implementation.

It's supposed to give you a nice preview like this when uploading a PDF file:
image

And on your branch it shows like this:
image

Maybe I missed something though.

Cheers!

**Comment by xmo-odoo** [comment]
> There is an easy fix though. I think we can simplify the code by destroying the box layers when the field is blurred and never re-use them. The cost of re-rendering them is pretty much negligible from the testing I've just made. If you agree with that, I'll push a commit that does just that.

See enterprise PR, I've tried fixing it using pdfjs's actual API (as the OCR things were actually the bit I tested, though I tested a while ago so it's possible it doesn't work anymore). That the DOM events are gone was one of the major non-recoverable patches.

Feel free to mess about.

> Maybe I missed something though.

Maybe. How do you get there, create content from the frontend?

Because I don't see a preview in the backend of elearning. Incidentally it seems to have really enjoyed the owl form migration:
Screenshot 2022-10-20 at 16-24-02 Odoo - New
Screenshot 2022-10-20 at 16-24-13 Odoo - New

**Comment by awa-odoo** [comment]
@xmo-odoo Yes you can get there through the frontend.

- Login as admin
- Homepage of the website
- "Courses" menu
- Pick a course (e.g: "Taking care of Trees")
- Click on the "Add Content" button
- Click on "Document"
- Select a PDF file to upload
-> After uploading you should see the preview from my screenshot

>  Incidentally it seems to have really enjoyed the owl form migration

Yes Luc noticed that too, we're on it :smile:

**Comment by lobaudoux** [comment]
> See enterprise PR, I've tried fixing it using pdfjs's actual API (as the OCR things were actually the bit I tested, though I tested a while ago so it's possible it doesn't work anymore). That the DOM events are gone was one of the major non-recoverable patches.

Sorry, I didn't realize there was already an enterprise PR.
I still prefer the simpler solution that I proposed, I've made it a commit : 
https://github.com/odoo-dev/enterprise/commit/7e051f168dee31ac1516b451035c5c0cf21dce06

**Comment by xmo-odoo** [comment]
@awa-odoo 
> Yes you can get there through the frontend.

Thanks for the repro case, finally managed to pin down the issue: I'd missed that `page.render()` is (also) not a promise anymore, instead it *has* a promise. And since javascript is awesome you can `await` random garbage and it won't tell you anything, it'll just go "sure here's what you just gave me :shrug:, so the updated code was retrieving the content of the canvas before the rendering had completed, which obviously did us no good.

@lobaudoux sure :shrug: replaced the enterprise commit by yours

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo rebase-merge

**Pull request closed without merging**
