### PR TITLE
[FIX] mass_mailing: inline image not supported

### PR DESCRIPTION
**Pull request by Julien00859**
Inline (base64) embedded images are not supported by most mail
clients (gmail on top of them), this fix save those images as
attachments and replace the src tag with the url of the
generated image so the image correctly renders.

opw-1929940

### CODE REVIEW

**Comment by nle-odoo** [comment]
robodoo delegate+

**Comment by Julien00859** [comment]
Thank you :)

**Comment by nle-odoo** [comment]
just some side notes, have your code in:

```
    #------------------------------------------------------
    # Technical stuff
    #------------------------------------------------------
```

...

if there is no reason to have xmlrpc call to the method, have it private with prefix `_`

...

from the code this is non trivial to understand why this is done so commenting `_inline_img_to_attachements` to explain why might be helpful at one time.

**Comment by Julien00859** [comment]
robodoo r+

**Pull request closed without merging**
