### PR TITLE
[FIX] stock: Allocate access rights manager model stock.fixed.putaway.st...

### PR DESCRIPTION
**Pull request by aba-odoo**
...rat all rights and users model stock.fixed.putaway.strat gives only read rights.

Manager : Object [Put Away Strategy] - Read,Write,Create, and Delete Access 
User : Object [stock.fixed.putaway.strat] - Read Access

### CODE REVIEW

**Comment by mart-e** [comment]
No objection on the patch but what bug are you fixing ?

**Comment by sve-odoo** [comment]
opw 619774

"You need to be warehouse manager to see the model 
stock.fixed.putaway.strat

Therefore it's not possible for a Warehouse/user to receive goods."

**Comment by mart-e** [comment]
Not exactly, only if you have created a put away strategy linked to that location.
The second rule is because only admin was able to create putaway strategy on a location.
That is the kind of info that should be present in the PR to avoid losing time to reproduce.

**Comment by mart-e** [comment]
Merged at 88ace35

**Pull request closed without merging**
