### PR TITLE
Manual forward port of #63162

### PR DESCRIPTION
**Pull request by dmo-odoo**

### CODE REVIEW

**Comment by dmo-odoo** [comment]
GitHub says: "dmo-odoo requested review from odoo/rd-code-owners, odoo/rd-discuss, odoo/rd-images, odoo/rd-security, odoo/rd-sm and odoo/rd-website as code owners 6 minutes ago" ... lolwut ?

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by seb-odoo** [comment]
> GitHub says: "dmo-odoo requested review from odoo/rd-code-owners, odoo/rd-discuss, odoo/rd-images, odoo/rd-security, odoo/rd-sm and odoo/rd-website as code owners 6 minutes ago" ... lolwut ?

That happens whenever we change the target of a PR. This is annoying noise from github.

**Comment by dmo-odoo** [comment]
> > GitHub says: "dmo-odoo requested review from odoo/rd-code-owners, odoo/rd-discuss, odoo/rd-images, odoo/rd-security, odoo/rd-sm and odoo/rd-website as code owners 6 minutes ago" ... lolwut ?
> 
> That happens whenever we change the target of a PR. This is annoying noise from github.

You are always helpful when I'm fighting with bots, thank you ! ❤️

**Pull request closed without merging**
