### PR TITLE
[FIX] base_import : show meaningful error message on import fail

### PR DESCRIPTION
**Pull request by Mtaylorr**
Issue :
When you try to import a big file it will display a blank error.

Steps to reproduce the error :
1-install inventory and e-commerce
2-go to products and import records
3-upload the file attached the ticket

Reason :
Before, there was a type included in the `reason` but now it seems that the error has no type neither a message.

Fix:
I tried to just output a general error.

opw-3410954

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
seems good to me if we now don't have the information we had before

**Comment by Mtaylorr** [comment]
@xmo-odoo , @aab-odoo can you take a look at this FIX ?

**Comment by Mtaylorr** [comment]
> I think it would be nice to investigate when the server-provided information got lost and why, but that aside 🤷 that we don't care too much about informing the user is mostly a business decision.

The problem is that before the error has `errorData` , but now we use `ConnectionLostError` which doesn't , I changed it a bit t keep everything as it is and just added the default message at the end if there is no message. let me know what you think

**Comment by Mtaylorr** [comment]
@xmo-odoo can you take a look ? thanks

**Comment by Mtaylorr** [comment]
@xmo-odoo updated it , thanks

**Pull request closed without merging**
