### PR TITLE
[IMP] cli: save PID also when starting odoo shell

### PR DESCRIPTION
**Pull request by seb-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
@KangOl what do you think about this? 

I need the PID to be set correctly to use pyflame from odoo shell without having to grep the result of ps.

**Comment by KangOl** [comment]
No, that's not a good idea.

You sometimes need to open `odoo shell` along with a running odoo instance. This will overwrite the existing pidfile, which can cause trouble.

**Comment by seb-odoo** [comment]
Do you see a clean way I could resolve this? If not this can be closed.

I'll just hack it locally for now.

**Comment by KangOl** [comment]
You can simply call `os.getpid()` yourself in `odoo shell`

**Comment by seb-odoo** [comment]
Ok thank you for the tips, I finally just added `odoo.cli.server.setup_pid_file()` on my odoo shell script.

**Pull request closed without merging**
