### PR TITLE
[CLA] Signature for Troizky

### PR DESCRIPTION
**Pull request by troizky**
Added troizky.md
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by troizky** [comment]
I just added my CLA signature, but a build failed. What was wrong?

**Comment by mart-e** [comment]
Hi,

Thank you for your CLA signature, don't worry, the failure was on the CI, not on the CLA test.
It was most likely a false positive as you did not changed part of the code but only your CLA file.

@robodoo r+

**Comment by troizky** [comment]
Now I see that all checks passed, but merging is still blocked. What I have to do?

**Comment by Yenthe666** [comment]
@troizky nothing, the system is currently processing PR's that are being merged. Yours will be merged within a few hours.

**Pull request closed without merging**
