### PR TITLE
[IMP] point_of_sale: pricelists

### PR DESCRIPTION
**Pull request by jorenvo**
Task: https://www.odoo.com/web#id=30732&view_type=form&model=project.task&action=327&menu_id=4720
Pad: https://pad.odoo.com/p/r.87acfbcaa3198f7cdc4f5f5360df6a9a

There's multiple commits. Each has a descriptive commit message. This POS PR is so awesome it even comes with an ORM change. The reason for it is that product.pricelist.item records were ordered in a SQL query as follows [1]:

```sql
'ORDER BY item.applied_on, item.min_quantity desc, categ.parent_left desc',
```

The ```_order``` of product.pricelist.item however was:

```python
_order = "applied_on, min_quantity desc, categ_id desc"
```

This causes an issue because it means that the POS will load the items in an incorrect order. So I just wanted to add a stored related field on product.pricelist.item pointing to categ_id.parent_left and that did not work. The related field did not get updated. Hence the change in models.py. I also wrote a test. I'm not 100% sure of that part of my PR though, so it would be a good idea to maybe ask rco.

[1] https://github.com/odoo/odoo/blob/master/addons/product/models/product_pricelist.py#L142

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi @jorenvo, spectacular feature you are adding. Seeing a quick look on the code, I only miss the possibility to show all the possible prices when you set a proportional price according quantity in the price tag. Something like `1: 100 €; 3: 70 €; 5: 50 €`. We have that in the OCA module pos_pricelist that can inspire you (although it's for 8.0): https://github.com/OCA/pos/tree/8.0/pos_pricelist.

Great work!

**Comment by jorenvo** [comment]
@pedrobaeza thank you for your feedback. Indeed, this feature is not part of the PR or the task. It's not that easy to do well considering we cannot implement something that does not work on touchscreens. So we cannot use tooltips like the OCA module. Also, the way it's displayed should ideally keep working for large amounts of min_quantity rules for a given product.

For now people will have to check the unit price per quantity by creating an orderline with that quantity. Another possibility is having another tab open with the backend showing the pricelist items.

**Comment by pedrobaeza** [comment]
Thanks for the explanation, @jorenvo. Indeed, on touchscreen tooltips are useless. We can have a button for showing prices by quantity that appear in a popup, but I also understand that it's not the usual user case with prices by quantity, so it's good for a first version to have it without this.

Continue your great work!

**Comment by jorenvo** [comment]
> Small comment after a first check, the pricelist field is not present in the ClientDetailsEdit view.

@mart-e Good point. I originally left it out because modifying a pricelist on a customer is not really a common use case. So that could be done through the backend. However, after reading your comment I realized it would be useful to have when creating a new customer in the POS interface. So I have added it in a separate commit.

**Comment by rco-odoo** [comment]
@jorenvo I don't understand your argument for adding a related field above. The attribute `_order` on `product.pricelist.item` is defined as
```python
    _order = "applied_on, min_quantity desc, categ_id desc"
```
while the `_order` on `product.category` is defined as
```python
    _order = "parent_left"
```
That implies that for reading pricelist items with `read()` or `seach()`, the ORM should automatically generate some SQL query like:
```sql
    SELECT ...
    FROM product_pricelist_item item
    LEFT JOIN product_category categ ON item.categ_id=categ.id
    WHERE ...
    ORDER BY item.applied_on, item.min_quantity DESC, categ.parent_left DESC
```
Isn't it the case? I know that the ORM has some code to generate the ordering clause above (see https://github.com/odoo/odoo/blob/master/odoo/models.py#L3578). Is it broken?

Besides, I confirm that fields depending on `parent_left` fields are not recomputed as expected. Your proposal is an attempt at fixing this, but it is not complete: not all rows where `parent_left` or `parent_right` are modified will see their dependent fields recomputed. I have an idea on how to fix it, but that is way more tricky, I think...

**Comment by jorenvo** [comment]
> I know that the ORM has some code to generate the ordering clause above (see https://github.com/odoo/odoo/blob/master/odoo/models.py#L3578).

I see, I had no idea it already did that. I assumed it would just sort on categ_id. I guess I should have tested. In that case no change is necessary. Thank you for taking a look at it :).

@mart-e I've removed both commits related to the order of product.pricelist.item from the branch.

**Comment by rco-odoo** [comment]
@jorenvo :+1: I am glad it just works as is :smile:

**Pull request merged**
