### PR TITLE
[IMP] website: mockify test

### PR DESCRIPTION
**Pull request by xmo-odoo**
Instead of using weird ad-hoc mock-like things.

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good, I missed that these mock things were available

in 12.0 this was a little refactored and using DotDict class for a part (6ebcb1db80)

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
@robodoo r+

let's try again

**Pull request closed without merging**
