### PR TITLE
replaced minified "reset.min.css" with its uncompressed version (Closes: #6376)

### PR DESCRIPTION
**Pull request by onlyjob**
Added "reset.url" to document origin of the "reset.css".

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

I have no issue for this change (as long as it's for master) but wouldn't it be better to move it to a `lib` folder?
Also could you [sign the CLA](https://github.com/odoo/odoo/blob/8.0/doc/cla/sign-cla.md) ?
Thanks

**Comment by onlyjob** [comment]
No I won't sign CLA, thanks. Nevertheless this should be safe to merge as my change is minor and therefore not copyrightable.
I prefer to avoid making more intrusive changes like moving files into different folder.
Please feel free to do so if you like.

Besides, I've opened an issue because I wasn't sure if my pull request will be merged...
Somebody has to do it, you know...

**Comment by mart-e** [comment]
Ok, no problem.
If we keep the changes in the same file, we can even merge it in 8.0. When proting to master, we will move it to another file and folder. Done at cff65f5.
Thanks for the report.

**Comment by onlyjob** [comment]
Thanks, Martin. :)

**Pull request closed without merging**
