### PR TITLE
[IMP] pipfile with requirements

### PR DESCRIPTION
**Pull request by ovnicraft**
Description of the issue/feature this PR addresses:

Pipenv is recommended in Python 3 documentation, so this PR add the Pipfile 

Current behavior before PR:

Pipfile not exists

Desired behavior after PR is merged:

Easy dependency management using pipenv

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Elkasitu** [comment]
> Pipenv is recommended in Python 3 documentation
Please link to a source when you make such statements.

**Comment by amkarthik** [comment]
+1

**Comment by Elkasitu** [comment]
@KangOl 
> requirement.txt is now useless.

I disagree, most if not all linux distros come with pip installed by default, this is not the case for pipenv and pip does not *yet* handle pipfiles, not to mention pipfile is still a WIP (literally the second line of their GitHub repo's readme).

I'm not against having both `requirements.txt` and `pipfile` though.

**Comment by KangOl** [comment]
@ovnicraft `requirement.txt` contains transitive list of packages, generated from `pip freeze`. `Pipfile` should only contains direct dependencies.

@Elkasitu having both files will lead to problems with files being out of sync. Doing `pip install pipenv` is not really an issue.

**Comment by gdgellatly** [comment]
I found pipfile and pipenv don't support platform specific dependencies. Eg
pywin32.

**Comment by ovnicraft** [comment]
@gdgellatly You can check L45

**Comment by ovnicraft** [comment]
rebased from master

**Comment by ovnicraft** [comment]
@KangOl updated in order to your review

**Comment by d-fence** [comment]
as
- like @Elkasitu said pipenv does not come by default with most distro
- it's still a work in progress
- seems to not handle different platform
- solves problems that we don't have
- adds a lot of files to maintain for packaging

I would prefer to close this PR ... unless a really good reason arises ?

**Pull request closed without merging**
