### PR TITLE
[FIX] point_of_sale: Correctly delete linked pos_printer to iot_box

### PR DESCRIPTION
**Pull request by robinengels**
Current behavior:
You couldn't delete an iot_box if a pos_printer was linked to it. You always get a validation error saying that "Proxy IP cannot be empty" To fix this we first want to check that the device_id linked to the printer still exists. To do this we need to move the constraint to the pos_iot module (because the device_id field is defined there)

Steps to reproduce:
- Install pos_iot
- Activate preparation printer in POS
- Create a printer and link it to an iot_box device
- Try to delete the iot_box

opw-3597370
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rhe-odoo** [comment]
@caburj @robinengels Shouldn't we at least warm that a printer was connected before? Constraint might be over kill but what if the user forgot about the link in the pos printer?

**Comment by robinengels** [comment]
@rhe-odoo @caburj As @qle-odoo said if the IoT-Box doesn't exist anymore the printer are kind of "headless" and are not usable anymore. So it makes sense to just delete them aswell.

**Comment by nle-odoo** [comment]
robodoo delegate+

**Comment by robinengels** [comment]
@robodoo r+

**Pull request closed without merging**
