### PR TITLE
8.0 pos child taxes fva

### PR DESCRIPTION
**Pull request by jnbrunet**
This is based on the [8.0 pos child taxes fva](https://github.com/odoo/odoo/pull/1835) pull request from the odoo-dev repository. Unfortunately, the change was creating a bug when the POS was creating an invoice of an order containing child taxes. Since the 1835 pull request is almost 8 month old, I'm creating this one that should work correctly.

This pull request contains the odoo-dev commit and a fix for the invoice bug. Normally, you could checkout the odoo.git 8.0 branch and cherry-pick the last two commit of my branch if you want the child taxes to work in the point of sale module.

### CODE REVIEW

**Comment by lapagept** [comment]
Check this! Thanks a lot!

**Comment by mathben** [comment]
:+1:

**Comment by mart-e** [comment]
@jnbrunet thanks to take the old branch and rebase it on current branch.

I would like to merge that but the branch needs some cleaning first (e.g. the python code is not good). I have created a branch at #6330 to do so.
However I am not sure to see what bug you are trying to fix with 6c79b0cc68189752f07c12ba5a1224e61920e334. Could you give me a way to reproduce ?

**Comment by jnbrunet** [comment]
@mart-e The old branch was adding the support of sub taxes in pos, but when rebasing with the current 8.0 branch, the generation of an invoice (when you print the invoice after passing the order) introduced two bug:

First the reference to sub taxes was lost -  taxes_by_id[id] was null (it was only keeping reference to parent taxes, hence my new function get_all_taxes_by_id). 

Second, the template of the printed invoice was using the "name" attribute of taxes that wasn't passed to the template. 

To reproduce the bug, rebase the old branch and add sub taxes. When you start the POS and add items to the order, normally the taxes should show correctly...until you try to print the invoice.

**Comment by mart-e** [comment]
Ok thank you for the precision. I have tested these scenario and they are not problematic in my new branch. I have merged it at 58a4813.
I have also merged your CLA signature at a6ef1a7.
Thank you for your help and let us know if there is issues with that.

**Pull request closed without merging**
