### PR TITLE
[FIX] base: set nodes invisible instead of removing in studio

### PR DESCRIPTION
**Pull request by pivi-odoo**
# Current behaviour
Editing names of form tabs in studio doesn't apply the changes to the correct tab. Sometimes you can't even add fields to a form sheet, or it adds to the incorrect ones. Sometimes you get stackstraces from xpath that couldn't be found.

# Expected behaviour
Adding/Editing elements in studio shouldn't produce any errors, or change other elements in proximity.

# Steps to reproduce
- Install Inventory and Studio
- Disable Variants in Settings
- Select a Product and go in Studio
- Add a new Tab, try editing it's name
- Observe that not the New Tab name changed, but the one on it's left.

# Reason for the problem
There is incoherency between the view that Studio is getting from the server (nodes to which the user doesn't have access are not present in the view), and the view that the server is applying Studio's changes. (there is no permission checking on the view used to apply the patches onto). This leads to WOWL generating incorrect xpaths of elements, because it is basing itself on the view sent from the server (with some nodes missing), and then the server is trying to apply the changes with that xpath on a view that is not the same.

# Fix
In the context of studio, instead of removing the nodes we don't have access to, we set them invisible. This is more inline with behaviour in saas-15.3 and before.

# Affected versions
- 16.0
- master

# Related Enterprise PR
odoo/enterprise#33088 
---
opw-3018490
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
usually it would be better to have the studio code only in studio (so override the method on studio, or move the code you want to change in a method, and override that method in studio)

side note:

in version 15.0 having "groups" would remove attrs on the node:

```py
                node.set('invisible', '1')
                node_info['modifiers']['invisible'] = True
                if 'attrs' in node.attrib:
                    del node.attrib['attrs']    # avoid making field visible later
            del node.attrib['groups']

```
I guess we would need to do that here too for same concern.

**Comment by pivi-odoo** [comment]
I've refactored base a little bit to move the code to the web_studio override. I've split the function to reduce code duplication to a maximum. Let me know what you think about it. I've added the related enterprise PR in the PR message.

**Comment by nle-odoo** [comment]
the override seems complicated, partially to keep:

```py
            elif node.tag == 't' and not node.attrib:
                # Move content of <t> blocks with no other instructions than just "groups=" to the parent
                # and remove the <t> node.
                # This is to keep the structure
                # <group>
                #   <field name="foo"/>
                #   <field name="bar"/>
                # <group>
                # so the web client adds the label as expected.
                for child in reversed(node):
                    node.addnext(child)
                node.getparent().remove(node)
```
but this seems:

-  to be another possible cause of issue that will change the structure we don't want on studio
- to be dead code(node.attrib will always be truthy since the element has `groups` attribute) so this could maybe just be removed if not necessary.

I think without that part, you could just override `_postprocess_access_rights_groups` which may be simpler.

Side note:

With the solution given by `beledouxdenis`, I'm not sure you would need to do any change in base, if we remove the "groups" attribute in the override of `_postprocess_access_rights` it will not be touched when we do the call to `super`.

**Comment by pivi-odoo** [comment]
I've followed Nicolas' advice and pushed the changed to the enterprise PR. Now this PR is not needed, since base isn't touched.

**Pull request closed without merging**
