### PR TITLE
FIX debian: fix debian package

### PR DESCRIPTION
**Pull request by Grokafar**

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the patch, I let @sle-odoo check the content but it seems there is still an issue with the CLA signature.

- you are signing using the address `Grokafar@users.noreply.github.com`
- you are signing for the address `@arbomou.ovh`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by mart-e** [comment]
removing the update-python-module was done at efe37469e9d6741403829e9d64fd67a2d8bb2e66 we will backport it to v8, thanks
why changing the path? it matches the debian guidelines.

**Comment by Grokafar** [comment]
During the installation there's an error like /var/lib/odoo not found. Actually the package doesn't contain any file to install to /var/lib/odoo. All the odoo's modules are installed to /usr/lib/python2.7/dist-packages/openerp.

**Comment by sle-odoo** [comment]
@Grokafar this kind of issues happen if you already have a user named odoo before installing the package. we create the user and assign its home [here](https://github.com/odoo/odoo/blob/9.0/debian/postinst#L14)

**Comment by Grokafar** [comment]
Ok you're right, my bad I didn't think about that ! Thanks a lot! Maybe we could move the chown for DATA_DIR into the if ?

**Pull request closed without merging**
