### PR TITLE
Master sale onboarding tour imp pka

### PR DESCRIPTION
**Pull request by pka-odoo**
Description of the issue/feature this PR addresses:
onboarding tour improvements.

Current behavior before PR:

Desired behavior after PR is merged:
onboarding tour improvements.

Task: 
https://www.odoo.com/web#id=1920454&action=327&model=project.task&view_type=form&menu_id=4720

Pad: 
https://pad.odoo.com/p/r.191cdd23115b0d560e21518795bbb3c8
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo rebase-ff

**Comment by qsm-odoo** [comment]
@aab-odoo @tivisse I end up here after searching why the rainbow man does not appear anymore at the end of tours (because let's face it, this is a key website feature).
- In master, the added `setTimeout` changes nothing for me (setting a delay does though)
- Should not the fix be in 12.0 at least ?
Thank you :)

**Comment by aab-odoo** [comment]
@qsm-odoo If the fix doesn't work for you, it means that i didn't correctly understand the issue. Maybe we could have a look together tomorrow? I agree that the correct fix should be applied in 12 (maybe even 11?) as well.

**Comment by qsm-odoo** [comment]
@aab-odoo :+1: Ok for tomorrow

**Pull request closed without merging**
