### PR TITLE
12.0 misc36 jke

### PR DESCRIPTION
**Pull request by JKE-be**
rebase-ff

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo delegate=seb-odoo

@seb-odoo

**Comment by seb-odoo** [comment]
Delegate user can't use rebase-ff so feel free to merge when you are ready.

**Comment by JKE-be** [comment]
task created for comparison test

Title limit is only for qsm xD

**Comment by seb-odoo** [comment]
@JKE-be reminder your PR, very priority

**Pull request closed without merging**
