### PR TITLE
[FIX] hr_recruitment_survey: Start survey, create answers

### LINKED ISSUE #38690: [13.0] Interview form not working in recruitment & interview survey results cannot be viewed from the survey results page
Impacted versions:
13

Steps to reproduce:
[A] Can't view survey form:
1. Create a interview survey form
2. Set the created interview form to a job position.
3. Start the recruitment for the newly created position. [Make sure the survey is in progress state]
4. Click on start interview
5. Click on the start survey button.

[B] Can't see submitted survey results:
1. Having submitted at least one filled interview survey form from recruitment, Go to the survey Module and select the survey and click on the See Result Button. 

Current behavior:
[A] The system does not display the interview survey form for the first time.
[B] The system does not display the result
Expected behavior:
[A] The system should display the survey form so that the interview panel could fill in the questions
[B] The system should display the result.
 
Video/Screenshot link (optional):
[A]  Survey form after clicking on start survey button for the first time.
image

[B]  Survey results can not be displayed (after having submitted 3 filled survey forms):
image

### PR DESCRIPTION
**Pull request by jbm-odoo**
Description of the issue/feature this PR addresses:
Use the correct function to create answers before starting the
survey.

Current behavior before PR:
We can't start survey as the answers were not created
(empty answers)

Desired behavior after PR is merged:
We can use survey in recruitment process.

close #38690 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jbm-odoo** [comment]
@awa-odoo Can you have a look a this PR? 
Thanks!

**Comment by awa-odoo** [comment]
Hello @jbm-odoo 

Fix looks good to me, but it should be backported in saas-12.3

To check/test

**Comment by jbm-odoo** [comment]
@tivisse

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
