### PR TITLE
[IMP] website: enable livechat button in website preview

### PR DESCRIPTION
**Pull request by alexkuhn**
The livechat button was disabled in website preview because its implementation could not properly handle being in an iframe inside the backend [1].

With the public livechat code being refactored to use discuss code, this is no longer a problem, so the livechat button can be present again. This also makes previewing the website more correct: the livechat button is actual present on the website, so hiding it was a lie.

By re-enabling the livechat button, this also allow to remove the test coverage by a tour, which was sometimes failing on runbot due to tour being small and doing `im_livechat/init` rpc after the end of the tour.

[1]: https://github.com/odoo/odoo/commit/e86c1ce94a148745d58ac38e408e1bc947978670

runbot-24631

### CODE REVIEW

**Review by rdeodoo — CHANGES_REQUESTED** [review]
Hello, we are functionally ok to re-introduce it, checked with @pierre-pde 

But:
- Wrong commit title: `[IMP] mail:` -> `[IMP] website:`
- Please always mention related commit in your commit msg, in this case it's https://github.com/odoo/odoo/commit/e86c1ce94a148745d58ac38e408e1bc947978670 I believe
- No task?

**Comment by alexkuhn** [comment]
@rdeodoo no task. There was a runbot issue from the tour, and we felt we could solve the issue by simply re-enabling the livechat button. I added related runbot-id in commit message

**Review by rdeodoo — APPROVED** [review]
Nice, ty :+1: 

Just note that your markdown link won't work without `:` after `[1]`
image

**Review by seb-odoo — APPROVED** [review]
@robodoo delegate+

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
