### PR TITLE
[IMP] mail: move files to ir_actions_client

### PR DESCRIPTION
**Pull request by zel-odoo**
"views" generally contains model-related views + template for frontend, not "stuff used in views". Purpose is to be able to find low-level data records in data, like ir_cron, ir_actions_server..

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
I remember someone saying things like that :disguised_face:

**Comment by tde-banana-odoo** [comment]
Note that it was a :socks: remark (aka linting), not really important :) but now that you made the PR ...

**Comment by zel-odoo** [comment]
it was not painful yet to make the move before it get more messed up

**Review by alexkuhn — APPROVED** [review]
@robodoo r+

**Comment by zel-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
