### PR TITLE
[FIX] partner_autocomplete: fix quick creation issue

### PR DESCRIPTION
**Pull request by kcv-odoo**
Before this commit auto complete suggestion were showing on partner field even though there is no_create attribute on partner field and because of that user can create partner record from that field even though user is not allow to create record from it and also it gives trackback in partner portal field because of access_token.

This commit prevent auto complete suggestion when partner field has no_create attribute set on them to avoid unnecessary partner creation from that field.

task-3690532

### CODE REVIEW

**Review by lobaudoux — COMMENTED** [review]
Thanks for the fix @kcv-odoo .

LGTM codewise, but shouldn't this be fixed starting from Odoo 16.0?
Also, isn't there a ticket ID that you could reference in the commit message?

**Comment by kcv-odoo** [comment]
Hello @lobaudoux,

Yes It should
Also added task ID

Also [Test case](https://github.com/odoo/odoo/blob/16.0/addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js#L202-L207) assertion are not correct they are not falling even though code is wrong
Because `companyInput` and other input in other test cases never contains `.o-autocomplete--dropdown-menu` class so test cases are passes every time
And checking it parent always contains `.o-autocomplete--dropdown-menu` either from auto complete, matching results or from `No Records` menu

So we have to check `.o-autocomplete--dropdown-item.partner_autocomplete_dropdown_many2one` in parent in other test cases to correctly check all the widget or not :slightly_smiling_face: 
[see build](https://runbot.odoo.com/runbot/batch/1295254) where I completely remove a feature still no test case is falling

I added commit to fix those test cases could you check? :innocent:

**Review by lobaudoux — COMMENTED** [review]
Good catch, thanks for fixing the tests as well :slightly_smiling_face:.

I've just noticed a small typo in the module name in the commit header:
partner_autocompl<ins>a</ins>te -> partner_autocompl<ins>e</ins>te.

**Review by lobaudoux — APPROVED** [review]
LGTM
@robodoo r+

**Comment by lobaudoux** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
