### PR TITLE
[IMP] pos : chatter is broken in pos session

### PR DESCRIPTION
**Pull request by anr-odoo**
task : https://www.odoo.com/web#id=2030754&action=327&model=project.task&view_type=form&menu_id=4720

Pad : https://pad.odoo.com/p/r.57d6467db51c9200b0e2bc3c82b819db

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by switch87** [comment]
@nim-odoo this fix is tested and can be merged if ok for you.

**Comment by pimodoo** [comment]
robodoo r+

**Comment by nim-odoo** [comment]
robodoo r-

First line of the commit should be:

`[FIX] point_of_sale : chatter is broken in pos session`

**Comment by pimodoo** [comment]
@nim-odoo sorry

**Comment by pimodoo** [comment]
robodoo r+

**Comment by pimodoo** [comment]
robodoo retry

**Pull request closed without merging**
