### PR TITLE
Update eskatr.md

### PR DESCRIPTION
**Pull request by levkar**
Description of the issue/feature this PR addresses:

Current behavior before PR:
team cannot send PR

Desired behavior after PR is merged:
team will be able to send PR

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by levkar** [comment]
@Whenrow would you help for this PR? I need it to get other one accepted.

https://github.com/odoo/odoo/pull/92476

**Comment by Whenrow** [comment]
robodoo r+
thank you

**Comment by mart-e** [comment]
@robodoo r-

Thank you for the CLA but there are several issues with this PR:
-  squash your commits into only one with a commit message like `[CLA] update eskatr CCLA`
- you do not need to resign the CLA, you have to use your `@eskayazilim.com.tr` email address for your commits
- the PR #92476 uses a `@users.noreply.github.com` email address and not one that is listed in this CLA, so it won't work
The email address in the CLA must be the same as for the signature for the verification to succeed.

Best,

**Comment by C3POdoo** [comment]
Dear @levkar,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
