### PR TITLE
Speed up of translations import

### PR DESCRIPTION
**Pull request by pimodoo**
Translations import in 11.0 is quite slow: importing or updating a language on a database with a few apps usually takes more than 30 seconds. On a runbot database with all modules installed, it takes more than 1 minute.

The main bottleneck in this process was [the deduplication check](https://github.com/odoo/odoo/blob/6ce265b8152d96f8dd49b8ceeac736b8143c4f3c/odoo/addons/base/ir/ir_translation.py#L135-L145) that needs to be done in a type-dependent way, based on complicated rules, such as:
 - there can be only 1 translation for each language for a given record field
 - except when that field is of type XML (e.g. view arch)
 - "code" translations are unique per language without being record specific
 - etc.

To remove the bottleneck, this check is replaced with several unique constraints implemented as partial indexes. Doing this required a minor change of model: using a different translation type for XML fields: `model_terms`.

Thanks to this change, the time needed to import/sync translations has been roughly divided by 10.

### CODE REVIEW

**Comment by sbidoul** [comment]
@mart-e Can you confirm msgmerge -U is sufficient to update the .po files, after the .pot is updated for model_terms instead of model.

**Comment by mart-e** [comment]
@sbidoul yes, you can use something like

```shell
$ msgmerge --no-wrap --no-fuzzy-matching -q fr.po test.pot | msgattrib --no-fuzzy --no-obsolete -o fr.po
```

To clean out of date translations. The above command works well in scenario like:

test.pot
```
# Translation of Odoo Server.
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~11.5\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"

#. module: test
#: model_terms:ir.ui.view,arch_db:foo.bar
#, python-format
msgid "Foo EN"
msgstr ""
```

fr.po (before)
```
# Translation of Odoo Server.
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~11.5\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"

#. module: test
#: model:ir.ui.view,arch_db:foo.bar
#, python-format
msgid "Foo EN"
msgstr "Foo FR"

#. module: test
#: model:ir.ui.view,arch_db:foo.bar
#, python-format
msgid "Bar EN"
msgstr "Bar FR"
```

fr.po (after)
```
# Translation of Odoo Server.
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~11.5\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"

#. module: test
#: model_terms:ir.ui.view,arch_db:foo.bar
#, python-format
msgid "Foo EN"
msgstr "Foo FR"
```

which has correctly replaced "model:ir.ui.view,arch_db:foo.bar" by "model_term:ir.ui.view,arch_db:foo.bar" and dropping the old translation

**Comment by sbidoul** [comment]
Hm, the weblate addon we use for that does a simple `msgmerge -U`. That should work too, so in principle it will be automatic for OCA. We'll need to check with one project first @pedrobaeza.

**Comment by mart-e** [comment]
Without the msgattrib and only `msgmerge -U`, with the .po and .pot I gave above, you would get this:
```
# Translation of Odoo Server.
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~11.5\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"

#. module: test
#: model_terms:ir.ui.view,arch_db:foo.bar
#, python-format
msgid "Foo EN"
msgstr "Foo FR"

#~ msgid "Bar EN"
#~ msgstr "Bar FR"
```

**Comment by pedrobaeza** [comment]
Yes, I'm thinking in 2 "side effects" of this:

* Change existing `ir.translation` records when migrating a DB from v11 to v12.
* The one you mentioned, that is updating correctly PO files of v11 OCA modules migrated to v12 without losing previous terms.

**Comment by pedrobaeza** [comment]
> Without the msgattrib and only msgmerge -U, ...

It's a bit more dirty, but it works IMO.

**Comment by pedrobaeza** [comment]
> By the way, I just tested, since this commit, we went from 85 seconds to 8.4 seconds to load all translations on a runbot tada

That are great news!

**Comment by sbidoul** [comment]
Thanks @mart-e !

**Pull request merged**
