### PR TITLE
[IMP] tests: autoretry and cursor commit

### PR DESCRIPTION
**Pull request by Xavier-Do**
This should improve autoretry mecanism overall, and also avoid chain error, even without autoretry, when commiting/rollbacking/closing the cursor opened from a TransactionCase.

### CODE REVIEW

**Review by xmo-odoo — CHANGES_REQUESTED** [review]
@robodoo override=ci/security

**Comment by Xavier-Do** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
@robodoo rebase-ff

**Comment by Xavier-Do** [comment]
@robodoo r+

**Pull request closed without merging**
