### PR TITLE
[ADD] Signature of new resource and change in type of partnership BMyA

### PR DESCRIPTION
**Pull request by Danisan**
[FIX] Modification of the type of partnership in Blanco Martin y Asociados

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Danisan** [comment]
@vbe-odoo Change in CLA signature for our company

**Comment by vbe-odoo** [comment]
@Danisan thanks for the heads up.
@jco-odoo I don't know if you can check this or if you need to check with @mart-e 
Thanks.

**Comment by jco-odoo** [comment]
@Danisan Might be better to do it in an earlier version and then fw-port (in case someone does a fix for v13/v14 e.g.)  Otherwise, it looks fine to me. @mart-e

**Comment by mart-e** [comment]
I agree with @jco-odoo, it's always good to make the changes in lower version and then port up to master.
Also could you change your commit message to something like `[CLA] add hea-bmya to Blanco Martin y Asociados CCLA` ?
Thanks

**Comment by vbe-odoo** [comment]
> I agree with @jco-odoo, it's always good to make the changes in lower version and then port up to master. Also could you change your commit message to something like `[CLA] add hea-bmya to Blanco Martin y Asociados CCLA` ? Thanks

@Danisan changes requested in the commit message and target V13 instead.
Thanks

**Pull request closed without merging**
