### PR TITLE
[FIX] calendar: invalid accept link in reminder email

### PR DESCRIPTION
**Pull request by nicocrm**
Behavior prior to the commit:

- the accept link in the reminder email for a meeting has a parameter
`event_id`, instead of `id`, which causes an error 500 when the user
tries to accept the meeting

Behavior after the commit:

- the accept link uses the correct `id` parameter

opw-2366173

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ngaller** [comment]
@nim-odoo this seems straightforward, but I worry about the translation for this email, because it looks like the entire text is used as the key.  It looks like there were translations committed in just 2 languages: zh_CN and da.  So we should do a simultaneous fix on transifex, right?

**Review by nim-odoo — APPROVED** [review]
OK, but you need to export the translations as well.

**Comment by ngaller** [comment]
OK, updated the pot (and the po for the languages that had a translation)

**Comment by nim-odoo** [comment]
robodoo delegate+

**Comment by ngaller** [comment]
@robodoo r+

**Pull request closed without merging**
