### PR TITLE
14.0 itbackport jco

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@lordkrandel Do you think of any possible problems with this backport?

**Comment by lordkrandel** [comment]
No, it's only parametrizing the server value.
I guess the `get_param` hasn't changed in the last version.

**Comment by jco-odoo** [comment]
@fw-bot ignore

**Review by william-andre — APPROVED** [review]
It would be nice to have tests (external with a sandbox if possible, but it is definitely possible to have a patched version) for at least (both would be nice) modules...

I hope the encode/decode things are right because I have no way to test it myself.

@robodoo r+

**Comment by jco-odoo** [comment]
@william-andre A first in a list of fixes for Italy.  This one is separate because it does not need forward-porting as it is a backport.  (which needed some fixing)

**Pull request closed without merging**
