### PR TITLE
[16.0][FIX] web - Proper locale is not loaded for Serbian languages

### PR DESCRIPTION
**Pull request by pnajman-modoolar**
Description of the issue/feature this PR addresses:
This PR solves an issue with loading locale for Serbian  lang

Current behavior before PR:
System does not load locale for Serbian lang due to the mismatch between Serbian language code and momentjs  locale file name for Serbian langs

Desired behavior after PR is merged:
System should load locale for both Serbian langs

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Julien00859** [comment]
Hello @pnajman-modoolar we are not fluent in Serbian, could you provide us a few screenshots of the situation before/after your changes? Also don't worry about our CI/CD being red, it is a bug in another branch, we'll simply rebase your branch on the latest 16.0 and that should do :)

**Comment by pnajman-modoolar** [comment]
> Hello @pnajman-modoolar we are not fluent in Serbian, could you provide us a few screenshots of the situation before/after your changes? Also don't worry about our CI/CD being red, it is a bug in another branch, we'll simply rebase your branch on the latest 16.0 and that should do :)

Hi  Julian,

Thank you very much for your prompt feedback.
Actually, when I read PR description I see I didn't describe the problem correctly, so please bare with me :)

In Serbia we have to language codes and those are the main one _sr_RS_ which is Cyrillic and _sr@latin_ which is Latin, ok ...

Now, when those two codes are provided to the _/web/webclient/locale/<string:lang>_  route and processed on the line 43 [here](https://github.com/odoo/odoo/pull/113328/files#diff-1cf7739ea6b6a1084d4f725884d6375c90d84d7f33130ab8d8b9c12a4a59d762R43) those codes will be transformed into following string values respectfully: **sr** and **sr@latin**.
Then on the line 49 [here](https://github.com/odoo/odoo/pull/113328/files#diff-1cf7739ea6b6a1084d4f725884d6375c90d84d7f33130ab8d8b9c12a4a59d762R49) the system will try to load moment locale files from the file system with following file paths respectfully: 

1. web/static/lib/moment/locale/sr.js

    Even though this file do exist on the file system, it is settings for **sr@latin** instead of **sr_RS**
    The correct moment locale settings file for **sr_RS** is: _web/static/lib/moment/locale/sr-cyrl.js_

2. web/static/lib/moment/locale/sr@latin.js

    Unfortunately file with this name does not exist on the file system, but it exists under different name: _web/static/lib/moment/locale/sr.js_

So, in this PR I'm solving this crazy mismatch issue between Odoo and Moment library by introducing a simple map to provide proper code values, so the system can read and return appropriate moment locale settings files.

I hope I managed to describe the problems and the solution that this PR brings.

Kind Regards,
Petar

**Review by Julien00859 — APPROVED** [review]
Ok I see, can you [*allow edits from maintainers*](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) please? I'll rebase on the latest 16.0 and change the commit message as follow:

    [FIX] web: Locale not loaded for Serbian lang
    
    In Serbia there are two language codes and those are `sr_RS` (Cyrillic)
    and `sr@latin` (Latin). Inside of the `web/static/lib/moment/locale`
    folder, the two langs are registered as `sr-cyrl.js` and `sr.js`
    respectively. The `load_locale` controller wasn't loading the right
    langs for neither case.

**Comment by pnajman-modoolar** [comment]
> Ok I see, can you [_allow edits from maintainers_](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) please? I'll rebase on the latest 16.0 and change the commit message as follow:
> 
> ```
> [FIX] web: Locale not loaded for Serbian lang
> 
> In Serbia there are two language codes and those are `sr_RS` (Cyrillic)
> and `sr@latin` (Latin). Inside of the `web/static/lib/moment/locale`
> folder, the two langs are registered as `sr-cyrl.js` and `sr.js`
> respectively. The `load_locale` controller wasn't loading the right
> langs for neither case.
> ```

Unfortunately I don't have that option, but I've rebased my branch and updated commit message as per your instructions.
I hope this is good enough.

I hope I'm not asking to much if I leave here a related PR's which in combination fixes all issue with Serbian langs and webpage translation, but it's related to the parsing of cookies on JS side: https://github.com/odoo/odoo/pull/113330 and display of Serbian country flag in the language chooser: https://github.com/odoo/odoo/pull/113329

**Comment by pnajman-modoolar** [comment]
Hi @Julien00859 ,

How do you suggest we proceed having in mind that the fork is registered with the Organization and thus I don't have an option to allow edits from maintainers?

I've rebased PR again this morning and the commit message is adjusted.

Thanks,
Petar

**Comment by Julien00859** [comment]
I'm really sorry, I only see your messages now. We usually ask for external maintainers to allow us to push their branch because they don't know how to rebase or amend their commit to write a message that comply with our guidelines. You were able to do all that so we could had merged this branch right away, it's really too bad that I only see your messages now.

But... Now I see that you have three PRs for a single issue (namely, serbian localization), I'm sorry to bother you again but could you do a single PR with all your commits? It is so that when we'll ask ourself "why is that map is for again?" in 5 years, we can easily get the full picture about all the bugs you are fixing because they'll be all tracked on a single PR.

So what I'm suggesting you is to cherry-pick 7f0d76b653379fb72edcaffa40df3aba858c4337 and 9b63716aaffa53583de78ea8fe20c0ac84e36c9c into your `fix/16.0/web/local_locale` branch at #113490 and to close the two other PRs. Doing this would also benefit you because the same people will review your three commits and they'll have the full picture :) A concrete example is that I didn't know about `[16.0][FIX] web: Quoted cookie values are not handled by cookie_utils.js` and I think the bug should be fixed backend-side, when we assign the lang to the `frontend_lang` cookie, but the people who are assigned on that PR (js-framework people) don't know much about that cookie.

**Comment by pnajman-modoolar** [comment]
> [16.0][FIX] web: Quoted cookie values are not handled by cookie_utils.js

Thanks for the feedback and it's no problem at all as I really want these PR's to be accepted ASAP and in the best way possible.  So, yes, it's no problem at all.

Regarding PR **[16.0][FIX] web: Quoted cookie values are not handled by cookie_utils.js** https://github.com/odoo/odoo/pull/113497 actually it's not an issue on the back-end where the mentioned cookie is set, it's just how underlying python library **werkzeug** works when they detect "invalid" characters in cookie values. I've spent some time investigating this issue and it's not a bug on their end or Odoo back-end. It's just that cookies parsing should be properly handled on front-end by taking into consideration possibility of double-quoted cookie values. But, yes, sure, you gotta do your due diligence on this matter. Perfectly fine.

Once I merge all those commits here and close other PR's I'll ping you again on the new PR: https://github.com/odoo/odoo/pull/113490

Cheers,
Petar

**Pull request closed without merging**
