### PR TITLE
[IMP] hw_posbox_homepage: remove jinja

### PR DESCRIPTION
**Pull request by MaxTheWhale**
After the rewrite of the IoT homepage to
use OWL, Jinja was still being used to render
the initial HTML even though none of it's
templating features were being used.

After this PR, Jinja is removed from
the controller and Odoo's `http` module
is used to serve the HTML file directly.

There are also two smaller commits in this PR
which add a favicon and fix the logs page.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MaxTheWhale** [comment]
Hello @odoo/rd-security, a small review for you

**Context**
Historically the IoT box homepage used the Jinja templating language, but for v18 it was rewritten using OWL. However, the Jinja infrastructure remained, even though it's templating features weren't being used. This PR removes Jinja from the homepage and instead serves the HTML file directly.

**Flagged code**
In `controllers/homepage.py`:
- `http.Stream.from_path("hw_posbox_homepage/views/index.html").get_response(content_security_policy=None)`
- `http.Stream.from_path("hw_posbox_homepage/views/logs.html").get_response(content_security_policy=None)`

The paths provided are hardcoded and so pose no risk returning unintended files. We do have to set the `content_security_policy` to `None`, as otherwise no JS can run. We could also define a custom CSP if that is preferred.

Thanks in advance!

**Review by loouis-t — APPROVED** [review]
Looks good to me.

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: load static file

**Review by lse-odoo — APPROVED** [review]
LGTM, might be worth to also remove jinja from other IoT code (in DisplayDriver):
https://github.com/odoo/odoo/blob/master/addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py#L25

**Comment by MaxTheWhale** [comment]
> LGTM, might be worth to also remove jinja from other IoT code (in DisplayDriver): https://github.com/odoo/odoo/blob/master/addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py#L25

Yep I've got another PR on the way for this after this one is merged

**Comment by Ysoroko** [comment]
Everything works and it's nice to have that IoT favicon
image

**Comment by Ysoroko** [comment]
@robodoo r+

**Comment by Ysoroko** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
