### PR TITLE
[FIX] delivery: handle multiple references in delivery email

### PR DESCRIPTION
**Pull request by jhk-odoo**
Steps to reproduce:
-duplicate resonanceinc.odoo.com
-look for the order with the ref SQInv/OUT/00983
-click "send confirmation email"

previous behavior:
the template does not handle multiple package references
and the associated link is wrong

current behavior:
each reference is set in a separated link

opw-2167037

### CODE REVIEW

**Comment by jhk-odoo** [comment]
@nle-odoo

**Comment by jhk-odoo** [comment]
https://github.com/odoo/enterprise/pull/8064
changed that file to get an array instead of a string

**Comment by nle-odoo** [comment]
in python, string is `str`, being of a class is written `isinstance(ma_variable, str)`

for testing rendering the mail when you know which value you should have, you can do things like:

```diff
diff --cc addons/delivery/models/stock_picking.py
@@@ -84,17 -84,17 +84,22 @@@ class StockPicking(models.Model)
      carrier_id = fields.Many2one("delivery.carrier", string="Carrier")
      volume = fields.Float(copy=False)
      weight = fields.Float(compute='_cal_weight', digits=dp.get_precision('Stock Weight'), store=True, compute_sudo=True)
--    carrier_tracking_ref = fields.Char(string='Tracking Reference', copy=False)
++    carrier_tracking_ref = fields.Char(string='Tracking Reference', compute='_compute_carrier_tracking_ref')
      carrier_tracking_url = fields.Char(string='Tracking URL', compute='_compute_carrier_tracking_url')
      weight_uom_id = fields.Many2one('uom.uom', string='Unit of Measure', compute='_compute_weight_uom_id', help="Unit of measurement for Weight")
      package_ids = fields.Many2many('stock.quant.package', compute='_compute_packages', string='Packages')
      weight_bulk = fields.Float('Bulk Weight', compute='_compute_bulk_weight')
      shipping_weight = fields.Float("Weight for Shipping", compute='_compute_shipping_weight')
  
++    def _compute_carrier_tracking_ref(self):
++        for picking in self:
++            picking.carrier_tracking_ref = '778992607070 + 778992608444 + 778992608569 + 778992609988 + 778992610190'
++
      @api.depends('carrier_id', 'carrier_tracking_ref')
      def _compute_carrier_tracking_url(self):
          for picking in self:
--            picking.carrier_tracking_url = picking.carrier_id.get_tracking_link(picking) if picking.carrier_id and picking.carrier_tracking_ref else False
++            picking.carrier_tracking_url = '[["778992607070", "https://track.easypost.com/djE6dHJrXzc1NDEyMmVmM2MwYTRlMGU5ZDA4ZjExYmVhOGVmNWNh"], ["778992608444", "https://track.easypost.com/djE6dHJrXzkyNDU1MmUzZjcwYjRmNzY4Mjc1OTAxOTA2OTIwYzBi"], ["778992608569", "https://track.easypost.com/djE6dHJrXzA0Mzg4NGI1OTg4YzRjOWZhMTJkOTQ3MDUwYzY3MDAz"], ["778992609988", "https://track.easypost.com/djE6dHJrX2RlNDg2Zjk5MDY4MTRhZGI4MjFkZjRkNmMyZTk4MTQ4"], ["778992610190", "https://track.easypost.com/djE6dHJrXzJhNjQ3YTlmMjhmYjQ4ODI5NjNhMWY2NWI5MzA0Nzk5"]]'
  
      def _compute_weight_uom_id(self):
          weight_uom_id = self.env['product.template']._get_weight_uom_id_from_ir_config_parameter()
```

**Comment by nle-odoo** [comment]
the two fixes I would think of is either having a new method:

```py
def _get_multiple_carrier_tracking(self):
    ...
    return
```

that do something similar to:

https://github.com/odoo/odoo/blob/37e3fe908ed3e87bdc8bfa33f411672e51e43e1a/addons/delivery/models/stock_picking.py#L195-L199

but just give back an array (or `return False` in except) then you can use `._get_multiple_carrier_trakcking()` in template

**Comment by jhk-odoo** [comment]
@nle-odoo like this?

**Comment by jhk-odoo** [comment]
i removed the _ prefix of the function (it was triggering jinja for security errors)
tested and it works

**Comment by nim-odoo** [comment]
@nle-odoo ok for r+?

**Comment by nle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
