### PR TITLE
[I18N] remove es_DO translations

### PR DESCRIPTION
**Pull request by gustavovalverde**
**Description of the issue/feature this PR addresses:**
Actual es_DO.po has multiple issues on the website because of damaged tags, and also a lot of translations wrongly done.

**Current behavior before PR:**
All modules have a es_DO.po with reviewed sentences that were wrongly reviewed.

**Desired behavior after PR is merged:**
Dominican team is focused on Transifex translations using es.po. From now on
Dominican Republic will inherit es.po and just make specific changes
on github just in the needed words or sentences that change base on
region.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gustavovalverde** [comment]
I'll appreciate your help here @mart-e, we already started with the translation of es.po in Transifex, doing it with es_DO.po

I'll  also do the same on Enterprise, the major problem is there right now.

**Comment by gustavovalverde** [comment]
@mart-e, I was expecting that after doing this, when loading es_DO when installing Odoo it would practically be the same as es.po, but it's not. It even has a bunch of untranslated terms or that don't match with es.po.

How could I make es_DO.po to inherit directly from es.po?

**Comment by mart-e** [comment]
es_DO should inherit from es automatically. Make sure you don't have leftover translations in your database.
It is a bit hard to debug translations without an access to the database.

**Comment by gustavovalverde** [comment]
Actually it was all the leftover translations. Is there a way to remove all those leftovers in a safe and smart way? As i did it with the _caveman method_: Select all records from the view, action, delete 😅

**Pull request closed without merging**
