### PR TITLE
[FIX] base: test should not break unofficial backward compatibility

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Unofficial backward compatibility

**Current behavior before PR:**
Import Error

**Desired behavior after PR is merged:**
Importing from the related library

@nim-odoo 
Not sure if you still merge such fixes, but as it does not hurt I guess it is not a bad idea

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
Unrelated test fail...

**Comment by xmo-odoo** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
@fw-bot up to 11.0

**Comment by xmo-odoo** [comment]
robodoo retry

**Pull request closed without merging**
