### PR TITLE
[website_certification] Migrated to new api.

### PR DESCRIPTION
**Pull request by rgo-odoo**
Task: https://www.odoo.com/web?#id=12025&view_type=form&model=project.task&menu_id=3942&action=327
Pad: https://pad.odoo.com/p/r.VGakKFc8cSzrV7v3

### CODE REVIEW

**Comment by atp-odoo** [comment]
LGTM

**Comment by ubic135** [comment]
Acil

Le lundi 23 février 2015, Atul Patel <notifications@github.com> a écrit :

> LGTM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/pull/5223#issuecomment-75494552>.
>


--

**Comment by hmo-odoo** [comment]
rename views/website_certification_*.xml ==> views/certification_*.xml

**Comment by rgo-odoo** [comment]
Files renamed.

**Pull request closed without merging**
