### PR TITLE
[IMP] fields: copy editable stored fields

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Purpose of this commit is to let computed stored editable fields being copied
if their field class allows it.

Indeed those fields are fields whose value is computed based on some triggers
but can also be updated manually by users. When copying a record it makes
sense to consider this value has been updated and allow its copy if original
field allows it. Either it was computed, and copied value will be correct
without having to call computation again. Either it was updated and copied
value will be the one the user entered.

Without this fix, an edited field is not copied. Its value will be computed
again, leading to an incoherent copy behavior.

Task ID 2209163
PR #46777

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@rco-odoo What do you think about this one ?

**Comment by tde-banana-odoo** [comment]
cc @tivisse @LucasLefevre

**Comment by tde-banana-odoo** [comment]
13.0 version: https://github.com/odoo/odoo/pull/46858

**Comment by rco-odoo** [comment]
Backported to 13.2 in #47286.

**Pull request closed without merging**
