### PR TITLE
[IMP] point_of_sale, pos_*: overall improvements and fixes

### PR DESCRIPTION
**Pull request by davidmonnom**
List of improvements:
- Add `Is a Kiosk` field when creating a new POS config
- Add category and change the image of the combo demo product
- Hide useless settings when kiosk mode is enabled

List of fixes:
- Fix bootstrap carousel traceback when no image is set
- Changed the warning sentence concerning adyen payments
- Fix start category in kiosk
- Fix sync between Self Order mobile and PoS restaurant, now new Lines from restaurant are added to the mobile order
- Fix product reminder when adding something in PoS mobile

### CODE REVIEW

**Comment by davidmonnom** [comment]
@odoo/rd-security 

Hello is it possible to have an override ?

Its about bus, I added this:
```

self.env['bus.bus']._sendone(f'self_order-{order.access_token}', 'ORDER_CHANGED', {
        'order': order._export_for_self_order()
})
```

**Review by rhe-odoo — APPROVED** [review]
@robodoo r+

**Comment by rhe-odoo** [comment]
@robodoo r- wait security check

**Review by xmo-odoo — COMMENTED** [review]
@robodoo override=ci/security

**Comment by rhe-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
