### PR TITLE
[FIX] odoo,base: new Python 3.11 opcodes

### PR DESCRIPTION
**Pull request by pimodoo**
When python expression is evaluated in odoo form an action or qweb, we
are checking the opcodes generated by the evaluation of this code. We do
such a verification, because the code from actions and templates can be
written by someone having not access to the server and we don't want to
let them perform actions out of the scope of their database.

In python 3.11, some opcodes from previous versions of Python have been
renamed, grouped or sepcified. There are also new ones that have been
introduce.

In this PR, we are whitelisting the new ones that are needed by odoo to
properly work in this version of Python.

### CODE REVIEW

**Comment by pimodoo** [comment]
@odoo/rd-security Hello, could you have a look at this and tell me if it seems good for you?

I haven't done the requirements.txt changes because some (greenlet and gevent) are not yet available in python 3.11 in a working version.

requirements that are not working in the specified versions in requirements.txt:
- gevent
- greenlet
- libsass
- lxml
- Pillow
- psycopg2
- python-ldap
- reportlab
(only gevent and greenlet are not working, the others are working in their latest versions)

@d-fence FYI (if you have the possibility to put a runbot instance in Python 3.11RC2 :) )

**Review by flvr-odoo — APPROVED** [review]
Pre-check, 
All opcode checked, no new behaviors - mostly renaming of opcodes

**Comment by o-app-coder** [comment]
Hi!
I have just installed Odoo 16.0 on a Python 3.11.0 venv under Ubuntu 22.0. Using the latest version of the packages mentioned above, it looks like everything works just super well. Of course i needed to apply this opcode adjustments from this PR.

Because Python 3.11.0 is officially out, and the above mentionen packages are now compatible with Python 3.11, please fix this PR and merge.

**Comment by pimodoo** [comment]
@o-app-coder Hello, thanks for your feedback, I also noticed it few days ago. I didn't find that those one were missing at the first time because I just tested to install all modules with demo data. But the mail templates are built after the init of the database so those ones were not triggered.

Do you know with which modules installed it triggered those ones?

**Comment by o-app-coder** [comment]
@pimodoo 
I installed the website module.

**Comment by d-fence** [comment]
> @d-fence FYI (if you have the possibility to put a runbot instance in Python 3.11RC2 :) )

I gave it a try this morning but it would take to much time and no certainty about the result.
I used the official Python Docker image and once you try to install a Debian python dependency, the 3.9 version comes back by the backdoor...

**Comment by pimodoo** [comment]
> > @d-fence FYI (if you have the possibility to put a runbot instance in Python 3.11RC2 :) )
> 
> I gave it a try this morning but it would take to much time and no certainty about the result. I used the official Python Docker image and once you try to install a Debian python dependency, the 3.9 version comes back by the backdoor...

Fedora 37 should come out next week with 3.11 shipped in it, we'll see to run a docker when a distro will contains 3.11 natively

**Pull request closed without merging**
