### PR TITLE
kanban progress bar widget filter on grey color

### PR DESCRIPTION
**Pull request by msh-odoo**
Task:https://www.odoo.com/web?#id=1952430&action=333&active_id=1251&model=project.task&view_type=form&menu_id=4720

Pad: https://pad.odoo.com/p/r.b3f5c136e22ae7d0a465fb4aae823c59

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo retry

**Comment by d-fence** [comment]
robodoo retry

**Pull request closed without merging**
