### PR TITLE
[FIX] tools: remove nondeterminism in pot files

### PR DESCRIPTION
**Pull request by HydrionBurst**
backport of #143918

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by oomsveta — APPROVED** [review]
robodoo r+

**Comment by pedrobaeza** [comment]
Shouldn't you disable the fw-port for 17.0+?

**Comment by oomsveta** [comment]
ROBODOO FW=NO

**Comment by oomsveta** [comment]
robodoo fw=no

**Pull request closed without merging**
