### PR TITLE
[FIX] web_editor: encourage to use snippets in empty oe_structure (wizz)

### PR DESCRIPTION
**Pull request by qsm-odoo**
Make the draggable snippets "wizz" when the user clicks on an empty
oe_structure and the other way around.

Related to task-2363616

### CODE REVIEW

**Review by qsm-odoo — COMMENTED** [review]
@robodoo rebase-ff delegate=sbuhl
@sbuhl I let you test and the honor to r+ (so now the snippets wizz if click on drop area and the drop area wizz if click on the snippets)

**Comment by rdeodoo** [comment]
:zzz:

**Comment by qsm-odoo** [comment]
cc @sbuhl :point_up:

**Review by qsm-odoo — COMMENTED** [review]
@robodoo rebase-ff r+

**Pull request closed without merging**
