### PR TITLE
[FIX] stock: warehouse selectable should be respected

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
User configuration and interface pitfall. The user is having a relation defined on a route for a warehouse and vice versa and is removing the checkbox (`warehouse_selectable`) about applicability.
If you do not actively delete the `route_ids` it is still there and invisible in the route and also applied.

**Current behavior before PR:**
A route is chosen based on the warehouse although the `warehouse_selectable` was deactivated b/c it does not care.

**Desired behavior after PR is merged:**
A route is automatically cleaned up based on `warehouse_selectable` and also we ignore now `route_ids` directly on application based on route configuration.

@jco-odoo @sle-odoo @amoyaux @pimodoo  
May I ask you to review and merge one or both of the commits? I guess it should be clear how I fixed the underlying issue. IMO, both should be safe for stable but it is your call @nim-odoo .

Info: @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
@wtaferner Ok for the usecase. We fixed it in 12.0 with a simple onchange on stock.location.route https://github.com/odoo/odoo/commit/a35df8d37170790257876a54aa54f2c3ab596c44#diff-c53152871da95bc774ee60ad559ba0c9R166 I would rather backport this fix.

**Comment by wtaferner** [comment]
@amoyaux 
Hmm, backporting would help for a new deselection but not for an existing non-working configurations, but true, it is more beautiful than the write hack. So voting for backport + fixing application of a route anyway and it would be smart even for 12.0 to check that in case someone is not using the UI and logically it is clear...

Ok, last call is on @nim-odoo I guess.

**Comment by amoyaux** [comment]
@wtaferner We can't apply the fix on _search_rule for a simple reason. Another mistake in stock_warehouse.py, it does not create the new route (for pick pack ship, ...) with the warehouse_selectable as True, it just set warehouse_ids on it. If we apply the fix all existing databases using multistep reception or delivery will not find the rules anymore.

**Comment by amoyaux** [comment]
@nim-odoo I will do the fix, I will not bother you with that

**Comment by wtaferner** [comment]
@amoyaux 
Ok, got it, thank you for your quick reaction and taking care of. And it would be great if you could take care of the inconsistencies evolved out of this as well.

**Comment by amoyaux** [comment]
https://github.com/odoo/odoo/pull/30844

**Pull request closed without merging**
