### PR TITLE
[IMP][13.0] crm: improvements in settings

### PR DESCRIPTION
**Pull request by sang250399**
- [x] Bug: when creating a user with settings permissions and not granting sales. When that user accesses the settings, it will give an error

- [x] Fix bug

Screenshot from 2022-01-14 08-29-10

Screenshot from 2022-01-14 08-30-14

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by tranngocson1996 — APPROVED** [review]

**Comment by sang250399** [comment]
@C3POdoo please review this PR for me !

**Comment by sang250399** [comment]
@mub-odoo please review this PR for me !

**Comment by sang250399** [comment]
@tde-banana-odoo Thank for reply.
Yes bro, that's exactly what i wanted to report.
I think it rarely happens, but it is crashing my system.
This pr will solve that problem.

**Comment by tranngocson1996** [comment]
@tde-banana-odoo Do you have any ideas for the above problem? Our system is having this problem.

**Comment by sang250399** [comment]
@tde-banana-odoo please reply me !

**Comment by tde-banana-odoo** [comment]
Hello,

I just tried a fresh db in 13, did not manage to reproduce. A user with settings and not any crm rights do not have any crm related tab, and I have no crash. Could you give a minimal steps to reproduce ?

Thanks !

**Comment by sang250399** [comment]
Dear @tde-banana-odoo !
this is the case i encountered. Please take a look and consider my solution to this error. Thanks sir!

https://user-images.githubusercontent.com/85299950/149733111-c91727a2-2d53-4aea-8abc-8879ba540387.MP4

**Comment by sang250399** [comment]
@tde-banana-odoo don't forget me !!!

**Comment by tranngocson1996** [comment]
@tde-banana-odoo ping ping !!! Can you spend a little time for it?
cc: @Yenthe666

**Pull request closed without merging**
