### PR TITLE
Master base add l10n to field 4402874 mafl arpi

### PR DESCRIPTION
**Pull request by arpi-odoo**

### CODE REVIEW

**Comment by rco-odoo** [comment]
See https://github.com/odoo/odoo/pull/190218.
It enables to do what you want without messing up with the ORM itself.

**Comment by arpi-odoo** [comment]
> See #190218. It enables to do what you want without messing up with the ORM itself.

I mean, that PR allows us to use the company selected without having a related field on the model to have the country code but our goal is to make our views more readable by removing the invisible when possible. The context with the company selected is just a side effect of what we really want.

**Review by aab-odoo — CHANGES_REQUESTED** [review]
You should not do that. Having a brand new attribute (which is only supported in hr addons) only brings confusion, whereas the `invisible` attribute is already well-known and used everywhere. It doesn't bring any clarity, it's just syntactic sugar over the `invisible` feature. You'll have an `invisible` attribute instead of your `l10n` attribute, it's almost exactly the same. Moreover, your attribute won't be supported in Studio.

**Comment by arpi-odoo** [comment]
We understand, we were just trying stuff to see if it could work and also to learn a bit about the framework

**Pull request closed without merging**
