### PR TITLE
[FIX] website_forum: hide posts by access rules for multiwebsite

### PR DESCRIPTION
**Pull request by royle-vietnam**
Description of the issue/feature this PR addresses:

**Current behavior before PR:**

eg: post 1 on website 1, post 2 on website 2
    access blog 1 from website 1 => can access -> normal
    access blog 1 from website 2 => can access -> normal

**Desired behavior after PR is merged:**

eg: post 1 on website 1, post 2 on website 2
    access blog 1 from website 1 => can access -> normal
    access blog 1 from website 2 => can access -> should crash because (ir rule)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo delegate=rdeodoo

//cc @rdeodoo and maybe check others main controllers...

**Review by rdeodoo — COMMENTED** [review]
1. To restrict in this PR:

**Forum**
```python3
@http.route(['/forum/<model("forum.forum"):forum>/tag', '/forum/<model("forum.forum"):forum>/tag/<string:tag_char>'], type='http', auth="public", website=True, sitemap=False)
```
**Blog**
```python3
@http.route(['''/blog/<model("blog.blog", "[('website_id', 'in', (False, current_website_id))]"):blog>/feed'''], type='http', auth="public", website=True)
```
**Slides**
```python3
@http.route('''/slides/slide/<model("slide.slide"):slide>/pdf_content''',
            type='http', auth="public", website=True, sitemap=False)
```

2. Do we want to hide those kind of routes?

**Forum**
```python3
@http.route('/forum/<model("forum.forum"):forum>/post/<model("forum.post"):post>/edit', type='http', auth="user", website=True)
```
```python3
@http.route('/forum/<model("forum.forum"):forum>/post/<model("forum.post"):post>/save', type='http', auth="user", methods=['POST'], website=True)
```
**Slides**
```python3
@http.route('/slides/slide/<int:slide_id>/get_image', type='http', auth="public", website=True, sitemap=False)
```
```python3
@http.route('/slides/slide/<model("slide.slide"):slide>/set_completed', website=True, type="http", auth="user")
```

3. About those ones, I am pretty sure we don't want to add that check:

**Forum**
```python3
@http.route('/forum/<model("forum.forum"):forum>/post/<model("forum.post"):post>/upvote', type='json', auth="public", website=True)
```
/validation_queue
/flagged_queue
/offensive_posts
/ask_for_mark_as_offensive
```python3
@http.route(['/forum/<model("forum.forum"):forum>/partner/<int:partner_id>'], type='http', auth="public", website=True)
```
etc..
**Slides**
```python3
@http.route('/slides/slide/get_html_content', type="json", auth="public", website=True)
```

4. Note that `website_slides` routes do not use same formating as we do, they use route without model converter as pass the model id as param, but we could still want to check those.
eg
```python
@http.route('/slides/channel/enroll', type='http', auth='public', website=True)
def slide_channel_join_http(self, channel_id):
    [...]
    channel = request.env['slide.channel'].browse(int(channel_id))
```

**Comment by JKE-be** [comment]
imo all routes availables in GET should try (not critical) respects multi website...


But be aware in stable with this kind of route: @http.route('''/slides/slide/<model("slide.slide"):slide>/pdf_content'') that is probably embeded in wrong website. Unfortuanlety most of code use still old ir.config_parameter web.base.url instead of model.get_base_url(). I have a task to shift them.

But can't we handle it in modelconverter directly ? or in postprocess_args ?

**Comment by rdeodoo** [comment]
> But can't we handle it in modelconverter directly ?

That's what I wanted to do but since `slides` do not use model converter no sadly

> or in postprocess_args ?

I will check

**Comment by JKE-be** [comment]
thanks for the fix.

As detected by @rdeodoo, we have a lot of controller that have the same.
We don't plan to change it in stable, because we are scared to break existing db that works with this side effect. Eg. a link with wrong domain (web.base.url) 

But we take your issue in consideration and will try to improve it in master version with a more global fix: #64313 if extra cost is not too much. Else we will apply your fix and on all others missing controllers that we will find.

**Pull request closed without merging**
