### PR TITLE
[FIX] fleet: specified the right view_type for vehicle contracts

### PR DESCRIPTION
**Pull request by pgu-odoo**
This commit is related to the issue: https://github.com/odoo/odoo/issues/26834

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@pgu-odoo what is the state of this PR?

**Comment by sswapnesh** [comment]
Closes: https://github.com/odoo/odoo/issues/26834 (If it will be merged ever :wink:)

**Comment by rdeodoo** [comment]
@qsm-odoo Looks like this is fixing a 'typo', but I can't r+.
I did not check further.

**Comment by yelizariev** [comment]
It's obsolete since v14 https://github.com/odoo/odoo/commit/82df1dfccc6b4e3031b1434c7ec1bec2bf7aeb2d
You could try retarget it to v12/v13 or close it

**Comment by lathama** [comment]
@pgu-odoo knowing that 11 is no longer updated, is this PR still needed?

**Comment by Yenthe666** [comment]
Are you really going to comment this on all old PR's that Odoo never handled? 😅

**Comment by C3POdoo** [comment]
Dear @pgu-odoo,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
