### PR TITLE
 Make The name field in Country State translatable

### PR DESCRIPTION
**Pull request by rami-wafaie**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rami-wafaie** [comment]
I'm already signed
https://github.com/odoo/odoo/blob/10.0/doc/cla/corporate/initos.md

**Comment by pedrobaeza** [comment]
Did you do the commit with the same email address as the CLA?

**Comment by rami-wafaie** [comment]
No I usually do the commits from my private email

**Comment by pedrobaeza** [comment]
That's the problem then

**Comment by xmo-odoo** [comment]
@pedrobaeza @rami-wafaie not exactly, the CLA is registered to the initos.*com* address but [the commit was created under an initos.*de* address](https://github.com/odoo/odoo/commit/572925ecdbd855a5c760c89cb03c0fa8a0b1bda1.patch). That's why the CLA check fails.

Either rewrite the commit using the .com address recorded in the CLA or add .de addresses in the CLA.

**Comment by rami-wafaie** [comment]
I fixed the email address (to .com) and rewrited the commit

**Comment by xmo-odoo** [comment]
Doesn't seem to have taken, [committer address is still .de](https://github.com/odoo/odoo/commit/dfbb8cf21ef8330b4e07fd7d9cb7f0865c9079c9.patch)

**Comment by rami-wafaie** [comment]
I think it is better to close this PR and open a new one, it should work in the new PR, should I do it like this??

**Comment by pedrobaeza** [comment]
No, that's not the solution. You have to make:
```
git commit --amend --author "Name <your_correct_email>"
git push -f
```

**Comment by xmo-odoo** [comment]
@pedrobaeza that only changes the *author* not the *committer*. To change the committer you need to configure the `user.email` then amend (possibly with `--reset-author`). Note that you can override `user.email` on the command line so e.g. `git -c user.email="<correct address>" commit --amend --reset-author` should work

**Comment by rami-wafaie** [comment]
this worked .. thanks

**Comment by pedrobaeza** [comment]
@xmo-odoo I thought your CLA control was by author, not by committer, as we do in OCA. Thanks for clarifying.

**Comment by mart-e** [comment]
Hello,

I have an issue with this change.
While I understand the names of the states can be translated in several languages (same as for the countries name), I do not want to "pollute" the list of translations with [hundreds](https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/res/res.country.state.csv) of different states. There is not much interest to translate a Russian state name into Spanish.

Instead, what makes more sense IMHO is to translate the states in countries speaking multiple languages (Belgium, Canada, Switzerland...).
This is what @Ehtaga explained at https://github.com/odoo/odoo/pull/20259#issue-266283385

So instead, we could set the translatable flag in the [l10n_multilang](https://github.com/odoo/odoo/tree/11.0/addons/l10n_multilang) module which is used by the chart of accounts of such countries.

What do you think?

**Comment by pedrobaeza** [comment]
This need starts from Germany in module https://github.com/OCA/l10n-germany/pull/21, and I see that `l10n_de` doesn't depend on the module you mention, so the problem will still be there for that country unless it manually install the other module.

**Comment by pedrobaeza** [comment]
I'm seeing that core still doesn't include German states, so a solution for this is to make the module `l10n_de_country_states` dependent of `l10n_multilang`, but it can be the case for other countries with regional variations (well, Spain is the case, but we have an official agreement on names at country level, remember #15166).

**Comment by mart-e** [comment]
Sorry but I lack a bit of the context of OCA/l10n-germany#21 
It is a legal binding to have different state names in different languages?

**Comment by pedrobaeza** [comment]
Yeah, that's not the start of the conversation I'm afraid.

Let me search for it.

**Comment by pedrobaeza** [comment]
It was... but on a hidden comment, please check this:

https://github.com/OCA/l10n-germany/pull/21#discussion_r122594675

On summary, they are saying that the name of the states in German are not the same than the names in English. It's not a regionalism requirement, but a general problem, because if we provided a local name (for example, `上海`), for an international audience I don't want to search that, but instead `Shanghai`, which is the English correspondence.

So I agree that we don't want to translate `Shanghai` to Spanish or any other language, but to have it on English, and translate it to Chinese.

What do you think?

**Comment by mart-e** [comment]
In most of the cases, this change will only be for multi-lang countries so it made sense to add it there.
As a compromise, we can, case by case, accept PR adding it in l10n_* modules to allow the translation in countries as China where it also makes sense.
Thanks for the feedback !

**Comment by pedrobaeza** [comment]
OK, let's go that way for now, but this means that you can't have a community translation if the states are on the base module. Please take that into account if you add more states to this list.

**Comment by mart-e** [comment]
I believe we should move the states out of this list to add them in their proper l10n_ module (but for a later dev).

**Comment by pedrobaeza** [comment]
Well, that can be a solution. Also not ideal, due to 3 reasons:

* This forces you to install `account` although you only want to use CRM and have states on your customers.
* Although your account is from one country, you would need states from another countries if you work a lot with that country commercially speaking.
* Uninstalling l10n module will remove (or throw an error) on partners with that states assigned.

I think a possibility is that you adopt something like https://github.com/OCA/partner-contact/tree/10.0/base_location_geonames_import module, and let users to import the states they want, only having the precaution of assigning well know XML-IDs on the import (`base.state...` for example). Then, localizations that needs the states for any legal reason (I think Mexico is one of them), can re-add as XML data with the same XML-IDs the same states for being sure they are in the DB and that they can be assigned via `ref`. Using `base` as module for the XML-ID, uninstalling l10n_mx won't remove states.

**Pull request closed without merging**
