### PR TITLE
[FIX] website_crm_partner_assign - Fixed error on rendering template of email_template_lead_forward_mail upon Forward to partner

### LINKED ISSUE #79492: CRM : Issue while forwarding a lead to partner.
Impacted versions: V15

Steps to reproduce: 
1. Goto CRM module.
2. Open pipeline and any lead.
3. Click on Action, and hit "Forward to partner" 
4. Submit the Wizard

Current behavior: Getting a traceback.

Expected behavior: Should assign that lead to partner.

Video/Screenshot link (optional): 
PR_79510

Support ticket number submitted via odoo.com/help (optional):

### PR DESCRIPTION
**Pull request by odooaktiv**
Description of the issue/feature this PR addresses:
Upon submitting the Forward to partner wizard an error is raised to the user.

Current behavior before PR:
Found issue.
'dict' object has no attribute 'lead_id'.

This was because in Odoo v14, lead_id was available in ctx['partner_leads']. In Odoo v15, it now gets a dictionary.

Desired behavior after PR is merged:
This commmit accesses the lead_id from the dictionary and the wizard is submitted successfully and email is sent.

Fixes #79492

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by odooaktiv** [comment]
@tde-banana-odoo Can you please review this PR?

**Comment by tde-banana-odoo** [comment]
Thanks ! LGTM, I rephrased a bit the commit message and added a link to an internal tracking task. Did it myself to speedup the merge :) .

@robodoo r+

**Comment by burhan-aktivsoftware** [comment]
Thanks @tde-banana-odoo :smiley:

**Comment by odooaktiv** [comment]
Thanks @tde-banana-odoo :smiley:

**Pull request closed without merging**
