### PR TITLE
[FIX] test_website: remove demo dependency

### PR DESCRIPTION
**Pull request by Williambraecky**
[Runbot Error 107975](https://runbot.odoo.com/web#id=107975&model=runbot.build.error)

### CODE REVIEW

**Comment by Williambraecky** [comment]
@robodoo up to saas-17.4

**Comment by Williambraecky** [comment]
> @robodoo up to saas-17.4

Will be handled in https://github.com/odoo/odoo/pull/187964

**Review by madprog — APPROVED** [review]
I have checked that the test still reproduces the error with user `admin`. In fact, we just need a session in order to put in it a language code that is not installed in the database; the user itself doesn't really matter.
The other error tested by this test, the permission error, was due to the `auth='none'` vs `auth='public'` on the `/web/session/logout` route, and it is not influenced by the permissions of the authenticated user either.
These are the two things fixed by odoo/odoo#187313 which introduces this test.

**Comment by Williambraecky** [comment]
robodoo r+

**Pull request closed without merging**
