### PR TITLE
[CLA] Add cla for Andrea Cattalani and  Emilio Pascual

### PR DESCRIPTION
**Pull request by anddago78**
add cla for Andrea Cattalani and  Emilio Pascual

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@moduon @rafaelbn

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Could you squash your commits to keep only one with the message  `[CLA] add cla for...` ? and it should be green :)

**Comment by anddago78** [comment]
Hi @mart-e i have modified the title! thank you!

**Comment by anddago78** [comment]
Hi @mart-e , ok, now I think that everything is correct.. thanks!

**Comment by mart-e** [comment]
@anddago78 the second line in the commit message was a bit redundant but not a big deal, thanks for the update :)

It will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
