### PR TITLE
[FIX] website_forum_doc: Not possible to change ToC order

### PR DESCRIPTION
**Pull request by Julien00859**
opw-1913300
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo retry

**Comment by nim-odoo** [comment]
robodoo retry

**Comment by Julien00859** [comment]
robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Comment by Julien00859** [comment]
robodoo retry

**Pull request closed without merging**
