### PR TITLE
[IMP] hr: make Complete Name of department translatable

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Hello @sofiagvaladze i have proposal that we should make `complete_name` of `hr.department` translatable, can i do it in master then

**Comment by tivisse** [comment]
Computed stored translated fields doesn't work IIRC. 

+ the different chunks inside complete_name are already translated right ?

**Comment by duong77476-viindoo** [comment]
> IIRC

Hello, i think i should work. FYI, i found one module does that at https://github.com/odoo/odoo/blob/17.0/addons/loyalty/models/loyalty_reward.py#L53

**Comment by duong77476-viindoo** [comment]
> Computed stored translated fields doesn't work IIRC.
> 
> * the different chunks inside complete_name are already translated right ?

Hello, i think it should work. FYI, i found one module does that at https://github.com/odoo/odoo/blob/17.0/addons/loyalty/models/loyalty_reward.py#L53

**Comment by sofiagvaladze** [comment]
@duong77476-viindoo the `complete_name` is basically consists of parent `department.name` -s, concatenated with `/`.. and `department.name` is translated.. I am wondering if we need to add translate=True, will it already not be a case that it looks as we want? 

and if not it's already a case, have you checked that your fix does a trick? Have you checked it? If so, would be great if you could provide screenshots

**Comment by duong77476-viindoo** [comment]
Hi @sofiagvaladze after a quick test, adding translate=True won't help, but dont you think it is really bad behaviour when all of my department have translated value but when i go to employee profile in different language, the `department_id` still in english no matter what language i use ?

**Comment by duong77476-viindoo** [comment]
> Computed stored translated fields doesn't work IIRC.
> 
> * the different chunks inside complete_name are already translated right ?

You are correct on this one, so what is your suggestion about this https://github.com/odoo/odoo/pull/170245#issuecomment-2202209095

**Comment by sofiagvaladze** [comment]
@duong77476-viindoo  Hum hum, Indeed, the name is translated, but display_name is not :thinking: 

It's beyond HR scope, so I asked/gave feedback about it to framework team. I will keep you updated

**Comment by sofiagvaladze** [comment]
So @duong77476-viindoo  , in this case `display_name` is basically the same as `complete_name`, and as `complete_name` is store recursive field, it won't be translated :/ adding translate won't do a trick

**Comment by sofiagvaladze** [comment]
Not much we can do about it, thus I will close the PR

**Comment by duong77476-viindoo** [comment]
@sofiagvaladze Thank you very much

**Pull request closed without merging**
