### PR TITLE
[FIX] web: fix pager in formView's notebook-listView

### PR DESCRIPTION
**Pull request by edi-odoo**
[FIX] web: fix pager in formView's notebook-listView

The negative `margin-top` of the listview inside the formView overlaps
the pager, cutting the bottom. By setting the `margin-top` only when 
the listView is the `:first-child`, the `margin-top` no longer exists
when a pager is in the view.
image

task-3430375
part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by edi-odoo** [comment]
@chgo-odoo @xlu-odoo could you review this please? Thanks !

**Review by chgo-odoo — APPROVED** [review]
Hi @edi-odoo LGTM thanks for your work !

**Review by xlu-odoo — APPROVED** [review]
LGTM! Thanks

**Comment by edi-odoo** [comment]
@pparidans 👋 ready for tech review! Thank you !

**Review by pparidans — COMMENTED** [review]
Is this fix still needed ?

I think there was a fix already merged last week (or something like that)...

:thinking: 

Update: found the PR https://github.com/odoo/odoo/pull/128235

**Comment by edi-odoo** [comment]
@pparidans Darn it! Sorry for the double trouble

**Pull request closed without merging**
