### PR TITLE
[MERGE] website_slides(_*): improve profile, lesson list display and demo data

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
This merge contains various improvements and fixes related to the new
eLearning application. Sub commits will give you more details on this
merge content as everything is not completely related.

Containing mainly
 * improve demo data to have more links and quizzes;
 * redesign the profile page, make it responsive and use bs4 when possible;
 * fix lesson list in training channels not displaying all slides;
 * improve lesson list design;

Merge linked to task ID 1941250 and PR #31453 about post-merge
cleaning and review.

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Comment by rrahir** [comment]
@tde-banana-odoo @stefanorigano  Hi guys, I've been investigating a bug on the forum and turns out taht this PR, espectially commit https://github.com/odoo/odoo/commit/5eeaa384c02b3686bfe7eab45315c219b2591fd5 has removed the badges classes from our css. It had previously been moved by @qsm-odoo  from website_forum to website_profile to make it available to other modules (e.g. slides) Is that a mistake or was it the purpose to drop those?

**Comment by stefanorigano** [comment]
Hello @rrahir ,
weird, probably it's just a class name change... could give me more context on the forum's issue and point me to the code generating the bug?

**Comment by rrahir** [comment]
@stefanorigano Hi  ;)
So the issue can be seen here : https://user-images.githubusercontent.com/6352350/74923019-60c44580-53d0-11ea-8f43-4d9185ca91d2.png (related open issue - https://github.com/odoo/odoo/issues/45579#issuecomment-627370888 )
the classes (badge-X) are only used here : https://github.com/odoo/odoo/blob/13.0/addons/website_forum/views/ir_qweb.xml#L17 
The issue is multiple, but the only relevant part here is that all icons are black while they should ha ve a gold-silver-bronze color.

The history is the following:  the classes were moved in website_profile to be ued more widely even if it wasn't used at the time (commit 0a8006b2f3c846cac8b09bb99991311353e47477 ) and it was then removed by your hand in commit 5eeaa384c02b3686bfe7eab45315c219b2591fd5   I guess it was removed since it wasn't used be cause I can't find any new class adding the same kind of color but I'm pretty sure it was useful to have it ;-)

**Comment by stefanorigano** [comment]
Hello @rrahir , sorry for the delay, quite busy here :)

So, initially I had difficulties getting "why" we show that information in the first place.
I thought badges were specific (eg. "Stellar question") or used to show the current rank only... while, as you showed up, these can be groped for group type  (gold, silver, bronze) and counted.

Not sure if this is still the desired behaviour, indeed it conflicts with the ranking system that it's (what a coincidence ^^) bronze, silver and gold. I find it confusing.
Eg. you may have 20 "gold badges", but your "ranking badge" is bronze... 🤷‍♂️ Even if we want to keep both, there's nothing in UI explaining the difference.
Btw, I can't find another place where this counted badges are shown.

Technically, my opinion is that the missing classes can be reintroduced (color variables are defined here
https://github.com/odoo/odoo/blob/13.0/addons/website_forum/static/src/scss/website_forum.scss#L1), but I think @sbuhl should have a look on this and eventually check if there is already something ongoing to address the problem (@JKE-be ?).

ps. digging around, I found this note. Not at all a python expert here, but maybe it's related?
https://github.com/odoo/odoo/blob/13.0/addons/gamification/models/res_users.py#L26

**Comment by rrahir** [comment]
@stefanorigano Hi, thanks for looking into it !
I agree that the redundancy of badge count and ranking badge is quie confusing. Hopefully, @sbuhl will be able to shed some light on the situation, we might want to get rid of those badge counts maybe? 
Anyway I already have a commit to fix it up  here: https://github.com/odoo-dev/odoo/commit/40e19b83ee0130f00d9764cca6fdc5abfae688fd that 'solves' the issue without being too invasive (like a view change to display the ranking badge would). @JKE-be if you have the opportunity to look at it ;)

**Comment by sbuhl** [comment]
Hello @rrahir and @stefanorigano 
The "Forum Badge Level" gives a deeper level on Badges. They don't have the same value. 
Ranks are "Newbie, Student, Bachelor, Master and Doctor". 
This may not be the easiest thing to understand, but I don't think it's advisable to change anything at this level.
I think your fix does the job, so if @JKE-be is ok to r+ it...
cheers

**Pull request closed without merging**
