### PR TITLE
[FIX] mrp_account: don't duplication analytic_account_line_id

### PR DESCRIPTION
**Pull request by yhu-odoo**
Both mo_analytic_account_line_id and wc_analytic_account_line_id are
copied when duplicate the workorder. This is not correct.

Task-2638896

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
robodoo rebase-ff

**Comment by d-fence** [comment]
robodoo retry

**Comment by Whenrow** [comment]
robodoo retry

**Pull request closed without merging**
