### PR TITLE
[11.0][FIX] base adapted for multicompany environment

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**
This PR fixes three bugs in `base` for a multicompany environment.

**Current behavior before PR:**
`res_company.py`: When creating a company from scratch, it creates a partner with the default company.
`res_partner.py`: When writing the company in a partner, it doesn't write the company in the partner children.
`models.py`: When creating a parent record for a record, it doesn't pass the company of the record.

**Desired behavior after PR is merged:**
`res_company.py`: When creating a company from scratch, it creates a partner without any company.
`res_partner.py`: When writing the company in a partner, it writes the company in the partner and all its children at the same time.
`models.py`: When creating a parent record for a record, it pass the company of the record if possible.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
cc: @rco-odoo

**Comment by mreficent** [comment]
ping: @rco-odoo @odony

**Comment by gdgellatly** [comment]
@mreficent I'm not entirely sure if I'm reading you right.  But here is our common setup and tell me if it breaks with this PR.

National Suppliers - no company_id visible to all
Local Ordering contacts, 1 for each company.
Local Delivery Addresses, 1 for each company.
A central invoicing contact - no company_id
Then usually there is a load of contacts with or without companies, depending on their scope.

The same for customers.

That way we get  sales, purchase and rebate information consolidated at the national level, but for ordering and delivery purposes, only local companies have local partner records as orders need to be placed in different places depending on location.

But the PR seems to want to force a company and contacts to all have the same company_id?

**Comment by mreficent** [comment]
@gdgellatly oh, thank you for your comment. I will fix that. I don't want to force the company, just in case they have one.

**Comment by mreficent** [comment]
@gdgellatly fixed

**Comment by gdgellatly** [comment]
@mreficent Reading rather than testing is hard but its after midnight so I'll leave to another day.  Part of me says its right, part is not so sure.  For me the logic should be.

If there is a company set on a parent partner then for all practical purposes it usually has to be set on all children.  Otherwise we get a lot of AccessErrors.
If there is no company_id on parent then all children can have different companies or no company.

The good part about that is you can then nest a hierarchy as deep as you like (not that I have) and never have an AccessError.

If you want to do any automated intercompany transactions, then usually the company partners must be created with no company.

I've reread a few times, I'm tending towards that this is what you have done.

**Comment by mreficent** [comment]
@gdgellatly  ok. I now understand what you say. I fixed it. Now only the company is passed to the children partners in case the parent partner will have a company.

About the fix in `res.company.py`, what the fix is ensuring is that when creating company X from partner X, then the partner should has the company X. It doesn't make sense to let the partner X without company when you have created the company X from that partner.

**Comment by mreficent** [comment]
@gdgellatly fixed, now the partner is created without company.

**Comment by mreficent** [comment]
ping: @rco-odoo @xmo-odoo @odony 

Any feedback?

**Comment by C3POdoo** [comment]
Dear @MiquelRForgeFlow,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
