### PR TITLE
[FIX] mail: handle traceback on need_moderation=false filter in discuss

### PR DESCRIPTION
**Pull request by xdu-odoo**
task-2352688

### CODE REVIEW

**Comment by xdu-odoo** [comment]
@seb-odoo

**Comment by seb-odoo** [comment]
Commit title a bit too long, and I would add a small description of fix: why change return to raise, and why change error type.

**Review by seb-odoo — APPROVED** [review]
typo

**Comment by seb-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
