### PR TITLE
[CLA] manish bohra

### PR DESCRIPTION
**Pull request by manishkumarbohra**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Do you still want to sign the CLA ? This PR changes nothing as you are deleting the file in the last commit.

**Comment by manishkumarbohra** [comment]
Hello All,

Yes I want to sign CLA.

In the last commit I've related to change my users.

Like i found last time issue with mention CLA email id and commit user id are different.

So, I've change the git users and commit the same file.

Let me know if anything is required.

________________________________

**Comment by mart-e** [comment]
I advise you to start fresh from a new branch only containing the CLA file, it will be easier (here you have multiple commits).

You will need to sign the CLA with the same email address as the one used to make your commits. In your case, you are currently making commits with the email address `m...@sunarctechnologies.com`. This is the email that must be in the CLA file. If you want another, don't forget to change your git(hub) configuration.

Best,

**Comment by manishkumarbohra** [comment]
Ok, Noted

Thanks for the prompt response.
________________________________

**Comment by mart-e** [comment]
Closing in favour of  #75124

**Pull request closed without merging**
