### PR TITLE
[FIX] mrp: resolve can't adapte type error

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses:
Closes https://github.com/odoo/odoo/issues/27556
Co-author: zyyang

Current behavior before PR: Traceback because it links to a record, not the id

Desired behavior after PR is merged: No more traceback

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e there you go, neatly fixed and all working 🎉

**Comment by Yenthe666** [comment]
Thanks! Why is robodoo linking to another commit in the message it posted though?

**Comment by mreficent** [comment]
Because when robodoo merges two or more commits from different PRs at the same time, it puts the link of last commit in all the PRs. I am not sure if this is intended or something unfixable. @xmo-odoo

**Comment by xmo-odoo** [comment]
@mreficent it's intended though definitely confuses people, I'll probably remove the link entirely since github already backrefs the commit to the  PR through the closes annotation.

**Comment by Yenthe666** [comment]
@xmo-odoo yeah that is probably cleaner. The backref already shows the commit and closes the PR and issue if there is one. Another message with another commit link is just confusing.

**Pull request closed without merging**
