### PR TITLE
[MERGE][FIX] im_livechat: correct configuration path and improved sentence

### PR DESCRIPTION
**Pull request by Yenthe666**
In the form view of a livechat, the instructions to configure with Odoo
website CMS was still referring to "Website Admin", instead of
"Website".

In addition to fixing this error, the sentence has been slightly improved,
as we have to regenerate the term anyway.

### CODE REVIEW

**Comment by Yenthe666** [comment]
@alexkuhn is this something you could look at maybe?

**Comment by alexkuhn** [comment]
Looks good, could you please rename title as the merge commit “[MERGE][FIX] ... “, and the 1st message of this PR as the commit message? Thanks!

**Comment by Yenthe666** [comment]
@alexkuhn if I understand you correctly you're asking to squash both commits into one which is named "[FIX] im_livechat: show correct path for configuration and improve sentence", is that correct?
Ahem, I guess I'll have to brush up on my squash skills if you confirm this.

**Comment by alexkuhn** [comment]
You can keep the PR with 2 commits. When you have severa commits in one PR, robodoo will make a merge commit which the title as the title of the PR, and the commit message as the 1st message of this PR.

So you can simply rename the title of this PR and the 1st message of this PR. I can do it for you if you don’t mind :)

**Comment by Yenthe666** [comment]
@alexkuhn please do :) I tend to run into issues when I start renaming or squashing for some reason. I still need to master more git commands for those cases hehe. /noob

**Comment by alexkuhn** [comment]
robodoo r+

@Yenthe666 Thanks for spotting this mistake!

**Comment by Yenthe666** [comment]
Thanks a lot for the very fast responses and help @alexkuhn!

**Pull request closed without merging**
