### PR TITLE
[IMP] html_editor: AI as alias to ChatGPT command

### PR DESCRIPTION
**Pull request by cammarosano**
[IMP] html_editor: search keywords for powerbox commands
[IMP] html_editor: AI as alias to ChatGPT command

task-4207516

### CODE REVIEW

**Review by fdardenne — APPROVED** [review]
@robodoo r+

**Comment by fdardenne** [comment]
@robodoo rebase-ff

**Comment by cammarosano** [comment]
@fdardenne I have just rebased. Can I get a new r+ ?

**Comment by fdardenne** [comment]
@robodoo r+

**Pull request closed without merging**
