### PR TITLE
[REF] sign: refactor get_pdf_number_of_pages

### PR DESCRIPTION
**Pull request by HydrionBurst**
task id: 2659342

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
I fail to see what's a refactoring about this. If sign wants a utility function for this it can have one.

**Comment by HydrionBurst** [comment]
> I fail to see what's a refactoring about this. If sign wants a utility function for this it can have one of its own.

Thanks for the review. The corresponding commit in PR [`[REF] sign,hr_contract_sign: refactor sign backend`](https://github.com/odoo/enterprise/pull/22813) is
[`[REF] sign, base: refactor _get_pdf_number_of_pages`](https://github.com/odoo/enterprise/pull/22813/commits/df7bedb6ff464f575e9670549abfa61d1ef66ded)

I refactor and put `get_pdf_number_of_pages` here because it is only for PDF data, not customized for the business logic of Sign. And `rotate_pdf` as another function only used in sign is also in this file. I think it would be better to put them together.

`get_pdf_number_of_pages` is mainly used to count the page number for all pdfs related to sign.
The result in a report claims how much green savings we did. So maybe this function can be reused in other Addons' related pdfs in the future.

Another usage: we try to get the page number to check if it is a valid unencrypted pdf. It seems to be the simplest and fastest way for PyPDF2 to check. Maybe other models can reuse it.

But if you prefer not touching files in `tools`, I can put it back to Sign:)

**Comment by HydrionBurst** [comment]
@xmo-odoo Do you still think the function should be in the Sign?
Further question, when should we put some functions in tools?

**Comment by xmo-odoo** [comment]
> Do you still think the function should be in the Sign? Further question, when should we put some functions in tools?

Unless there are demonstrable use cases outside of sign then yes. Iff there are uses for this elsewhere, the helper can be moved out.

**Comment by HydrionBurst** [comment]
@xmo-odoo  Thanks for your explanation.
I just thought other developers will only check if the similar code exists in `tools` but not in `Sign` when they need the to get the pdf page number or check if the pdf is valid.
But I get your idea, I will move this helper back into `Sign`, because now it is only used in `Sign`

**Comment by HydrionBurst** [comment]
This PR is closed because the diff is moved back to eSign.

**Pull request closed without merging**
