### PR TITLE
[FIX] point_of_sale: correctly assign product in move

### PR DESCRIPTION
**Pull request by agr-odoo**
1. Have a [DEMO] product in stock with an owner
2. Make a PoS order with [DEMO]

The system will use the stock without owner.

opw-2480341

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@pimodoo 
Hello, this seems a regression from v13 where the owner was correctly taken into account
https://github.com/odoo/odoo/blob/0a92706cd0d38d33a399bec7b5b5fbe7ab7f8576/addons/point_of_sale/models/pos_order.py#L539-L545
but I would really like a double check as I'm not expert in stock operations

**Comment by pimodoo** [comment]
you cannot apply your fix, like this as it won't respect the way lots selected.

**Comment by pimodoo** [comment]
What you should probably do is having the same behavior in the last else "move.quantity_done = move.product_uom_qty" than what is done in the one at line 140.

I've also just seen that variable "sum_of_lots" is useless in those "else" cases

**Comment by agr-odoo** [comment]
@pimodoo

**Comment by pimodoo** [comment]
@agr-odoo you have to add this:
for move_line in move.move_line_ids:
  move_line.qty_done = move_line.product_uom_qty
  if float_compare(move.product_uom_qty, move.quantity_done, precision_rounding=move.product_uom.rounding) > 0:
      remaining_qty = move.product_uom_qty - move.quantity_done
      ml_vals = move._prepare_move_line_vals()
      ml_vals.update({'qty_done':remaining_qty})
      self.env['stock.move.line'].create(ml_vals)
      
      
Because the implementation of the inverse function set on move.quantity_done, you won't be able to validate a move if you have more quantities to process than what you have in stock

**Comment by agr-odoo** [comment]
@pimodoo

**Comment by agr-odoo** [comment]
@pimodoo

**Comment by pimodoo** [comment]
@robodoo r+

**Pull request closed without merging**
