### PR TITLE
get correct .pot file when `module_name` parameter is set

### PR DESCRIPTION
**Pull request by charbeljc**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you explain the use case for this?

**Comment by charbeljc** [comment]
Ok @pedrobaeza, use case:

For a customer we are reusing `sale.order` objects and workflow with different terminology and various other customizations (we don't ever generate an invoice, for instance).

We want to overwrite some translated terms coming from the base 'sale' module, and we don't want to copy the specific terms in another .pot file. Instead, we want to reuse the existing one as a driver for our specific translations.

Maybe there is better way to do this ?

Regards

**Comment by pedrobaeza** [comment]
But at the end, are you providing a .po with `sale` put in the module line?

**Comment by lepistone** [comment]
@charbeljc ping

**Comment by charbeljc** [comment]
@pedrobaeza Yes, we have a po file in our module's i18n_extra having `sale` in the module line for our translations overwrites. But again, I'm not certain this is the right way to achieve what we want ...

**Comment by pedrobaeza** [comment]
OK, as marked by @mart-e, this is a wishlist, so maybe this can be for master. Anyway, I'm not an expert of translations, so it's need to be judged by one.

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
