### PR TITLE
[FIX] web_editor: banner drag and drop issue

### PR DESCRIPTION
**Pull request by shsa-odoo**
Current behavior before PR:

-Banner on drag and drop only drops content.
-Content inside banner were draggable.

Desired behavior after PR is merged:

-Now we can drop banner as well.
 -Prevented content inside banner to be draggable.

task-3512199

### CODE REVIEW

**Comment by dmo-odoo** [comment]
I don't like the proposed fix because it is ad hoc for banners. Maybe we don't have another choice but I'd like to think about it first. @Goaman What do you think we target here ? The banner is not editable and protected.

**Comment by Goaman** [comment]
@dmo-odoo I agree that it is ad-hoc and we should have an option to configure which element is movable.
However there is already `o_knowledge_behavior_anchor` that is hard coded in `ALLOWED_ELEMENTS`.
So either we add the configuration commit in this PR or we create another task to add the option.

If we add the code ad-hoc without adding the option, `&& !node.parentElement.closest('.o_editor_banner')` should not be repeated twice and should be in `inNodeMovable` as it is the purpose of this method, to return if a node is movable.

**Comment by dmo-odoo** [comment]
I hadn't realized we had `o_knowledge_behavior_anchor` hardcoded in `ALLOWED_ELEMENTS`. The banner class is not that bad then because the knowledge class is not even part of `web_editor`.

@shsa-odoo You can add it in `isNodeMovable`.

**Comment by shsa-odoo** [comment]
@dmo-odoo i have made the changes

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
