### PR TITLE
[FIX] web: disable prefetch in ir_http get_currencies method

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

This method already does a read for the specific fields, so there isn't need to fetch all the other unneeded fields.

**Current behavior before PR:**

This method, in the search, fetches unneeded fields.

**Desired behavior after PR is merged:**

This method only fetch the used fields.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
I think ci runbot error is unrelated.

**Comment by mart-e** [comment]
Or : why do we need the `read` call anyway? Seems unnecessary.
Why do you need to disable prefetch? Do you get performance issues on this method?

**Comment by mreficent** [comment]
No, it's just I saw the read. So or we disable prefetch and maintain the read or we delete the read, but having both prefetch and read it's silly. Thus I just went with the disable prefetch option, it seems better to me.

**Comment by mart-e** [comment]
It seems it was introduced at fdb250942f987e6e6c3748378b98a3f508761e16, moving from a read from js to a read server side.
Removing the `read` simplifies the code and will have almost no impact. No need for premature optimisation ;-)
But it should target the master branch if not fixing a bug.

**Comment by mreficent** [comment]
It's not simply removing the read. The read gives a list. If I remove the read, then I will need to rewrite the posterior dictionary.

**Comment by mart-e** [comment]
> If I remove the read, then I will need to rewrite the posterior dictionary

Why? It gives the exact same result

```
>>> currencies = Currency.search([])                                                                                                                                                                           
>>> {c['id']: {'symbol': c['symbol'], 'position': c['position'], 'digits': [69,c['decimal_places']]} for c in currencies}                                                                                      
{1: {'symbol': '€', 'position': 'after', 'digits': [69, 2]},
 2: {'symbol': '$', 'position': 'before', 'digits': [69, 2]}}
>>> currencies = Currency.search([]).read(['symbol', 'position', 'decimal_places'])                                                                                                                            
>>> {c['id']: {'symbol': c['symbol'], 'position': c['position'], 'digits': [69,c['decimal_places']]} for c in currencies}                                                                                      
{1: {'symbol': '€', 'position': 'after', 'digits': [69, 2]},
 2: {'symbol': '$', 'position': 'before', 'digits': [69, 2]}}
```

**Comment by mreficent** [comment]
ok...

**Comment by mreficent** [comment]
Closing it as it should target master...

**Pull request closed without merging**
