### PR TITLE
[8.0][CHG] Add the possibility to add some fields for the ir.attachment...

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
…creation on website recruitment form

It should be possible to add a second `<input type="file">` allowing the user to add more than one file into the hr_recruitment form. For exemple a motivation letter.

The current PR export the creation of the ir.attachment into a other method that allows more flexibility of inheritance.

-jne

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
OPW 654365

**Comment by JonathanNEMRY** [comment]
Any news about this issue?

**Comment by antonylesuisse** [comment]
@dmo-odoo or @JKE-be in v9 can you confirm me that it is possible with website.form ?

**Comment by JKE-be** [comment]
Yes, it is possible ! 

image

And you will have all docs in the applicant 
image

:+1:

**Comment by JKE-be** [comment]
PS: this PR make sense, but ufile should be returned by a function to allow more flexibility.

```Eg:
    def _get_applicant_files_fields(self):
       return ['ufile']
```

**Comment by JonathanNEMRY** [comment]
@JKE-be  Is it OK to merge it?

**Comment by dmo-odoo** [comment]
I don't understand any of what is going on here. @antonylesuisse I assume you assigned this to me because it looked like a form builder issue ? @JKE-be your answer is the right one, but this is not v9.0. @JonathanNEMRY is complaining about 8.0, which doesn't use the form builder.

**Comment by JKE-be** [comment]
Hi Jonathan,
I will merge a similar patch.
Based on 67b1be7f579d8e500bf05fc8ba35e21dc6f4e402

Your branch is not rebased, and the patch not really working since if you don't have a ufile, you will not create others attachments. Anyway, we would like to keep the create attachment code in the jobs_thankyou controller. I try to do it asap.

Thank for your pr

**Comment by JonathanNEMRY** [comment]
Hi @JKE-be 
I'll wait your solution.
Many thanks in advance!

Jonathan

**Comment by JKE-be** [comment]
Merged in 8.0 e9fc7353d2962f0e71bbf8d1fc69e9666e74b33a

**Pull request closed without merging**
