### PR TITLE
[FIX] stock: wrong text in the help : the price wasn't store in the quants

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
From V11 the price was not save in quants.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
@simongoffin Would be good to do this in order not to confuse people.

**Comment by fmdl** [comment]
ping @simongoffin

**Comment by fmdl** [comment]
@jco-odoo if you think it is not a good PR can you close it ?

**Comment by fmdl** [comment]
@nim-odoo it is a simple PR

**Pull request closed without merging**
