### PR TITLE
[IMP] base: allow archive res.partner.title

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
- Delete a res.partner.title, exemple "Docteur"
- Upgrade base
--> Issue Docteur re appear

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW 2378144

cc @mart-e

**Comment by fmdl** [comment]
cc @Yenthe666

**Comment by Yenthe666** [comment]
I'm a fan of making it archivable :)

**Comment by fmdl** [comment]
ping @simongoffin

**Comment by fmdl** [comment]
@tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
Seems we already discussed about a similar one ... isn't it more linked to data being back again while it should not ?

**Pull request closed without merging**
