### PR TITLE
[IMP] 10.0 improvement of german account charts

### PR DESCRIPTION
**Pull request by tv-openbig**
I. modification and extension of SKR03 account chart
========================================

* improvment and mapping of Odoo standard account types (usage of all
available account types and fixing of wrong mapping)
* fixing of reconcile setting on several accounts
* update of account chart (to SKR03 2017)
* fixing of account chart by ascending order of accounts for easier
maintenance in the future and probably easier preparation of accounting reports
* backport of new account tags from V11 for better reporting
* shorter tags
* introduction of new taxes for all theoretically possible tax cases
needed to declare the VAT
* automatic mapping of taxes to accounts to auto detect the right tax
by selection of income / expense account on invoice lines
* assignation of tax groups to taxes
* introduction of reconcile templates (to allow booking of cash discount
cases)

II. modification and extension of SKR04 account chart
=========================================

* improved mapping of Odoo standard account types (usage of all
available account types and fixing of wrong mapping)
* fixed reconcile settings for all accounts
* update of account chart (to latest SKR04 2017)
* better source code by ascending order of accounts. Finally it will be
easier to maintain the chart in the future and also it will be easier
to identify and group records to to develop missing or new accounting
reports.
* backport of new account tags from V11 for better reporting
* shorter tags
* assignation of tax groups to taxes
* introduction of further taxes to cover most possible tax
cases needed to declare the german VAT
* automatic mapping of taxes to accounts to auto detect the right tax
by selection of income / expense account on invoice lines
* introduction of reconcile templates for cash discount deduction on
payments or low payment variances.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sbidoul** [comment]
@lap-odoo  @qdp-odoo @tv-openbig what is the status of this PR? Will it be merged in 10? Or is there something equivalent in 11/12/master?

**Comment by qdp-odoo** [comment]
@csnauwaert Didn't we already merged that, in someway?

**Comment by csnauwaert** [comment]
@qdp-odoo It was merged in v11 at a3bc08d9d8aa40e8d41f99e5b102997c6990396a

**Comment by sbidoul** [comment]
@csnauwaert Thanks for the pointer.

**Comment by qdp-odoo** [comment]
ha yes, correct.

As the PR was kinda conflicting with the modifications we already did in v11, we just cherry-picked the improvements for the v11 as well. 

So I suppose we can now close this PR as well

thanks for the contribution

**Pull request closed without merging**
