### PR TITLE
[FIX] website: make get_http_domain more smart

### PR DESCRIPTION
**Pull request by JKE-be**
Autocorrect self.domain if wrong

website.domain should contains scheme and not trialing /

Else a several bugs like urls:
   //my/ => homepage
   wrong canonical url
   wrong hreflang
   ...

opw-2486918

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
@fw-bot up to master

**Comment by JKE-be** [comment]
@fw-bot up to saas-14.3

**Review by rdeodoo — APPROVED** [review]
:+1:

**Comment by rdeodoo** [comment]
Le'ts add a test and fix the typo in commit message `trialing` and LGTM

**Comment by JKE-be** [comment]
test added in master: https://github.com/odoo/odoo/pull/71161

@robodoo r+

**Pull request closed without merging**
