### PR TITLE
[IMP] mail: remove ComposerSuggestionComponent/modelName 

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2793280

### CODE REVIEW

**Review by phenix-factory — APPROVED** [review]
Need rebase for the this.root.el
Otherwise LGTM

**Comment by alexkuhn** [comment]
What do you mean exactly about the `root.el` that needs rebase of this PR? I don't see any diff that is related about recent guard of `root.el`?

**Comment by phenix-factory** [comment]
This still crash when you try to mention someone by @+typing the name.

**Comment by alexkuhn** [comment]
Ok, just rebased and will try again. If all works good, will r-plus later in a grouped PR of the day

**Pull request closed without merging**
