### PR TITLE
[FIX] crm: use the right view when clicking on activities systray

### PR DESCRIPTION
**Pull request by kebeclibre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
@ged-odoo 
There is this one: #21976 with a supplementary RPC
Maybe we can mix both solutions....
@tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
Hello,

If I understand well you are trying to fix the issue of displaying the right for view in the activity systray widget. It is a known limitation that some models have different views depending on their state or some other parameters.

We choose not to add queries, RPC calls or complex context-based key propagation. I think we should probably someday find a smarter solution to detect the form view that trying to propagate it everywhere. Moreover this solution does not apply once more than one record can be displayed. For example if you have a mix of lead and opportunities, or sale orders in various states.

According to me this is currently a technical limitation and we should not hack the system to find a suboptimal solution.

Regards,

**Comment by nim-odoo** [comment]
@tde-banana-odoo I agree none of these hacks is really good and the issue could be considered as a technical limitation. However, this has already been reported several times, obviously because the activities are of major importance in CRM (where the issue occurs because of opportunities/leads). So that would be great to have someone improving it in master on a short notice.

Thanks

**Comment by tde-banana-odoo** [comment]
Hello,

Ok, I create a feedback for that issue. Thanks for reporting !

**Pull request closed without merging**
