### PR TITLE
[8.0] Fix workflow loading workflows that depends on modules that aren't yet loaded

### PR DESCRIPTION
**Pull request by llacroix**
Prevent workflows from being used, if they depends on python modules that aren't yet loaded in sys.modules.

If the workflows are created without any reference to ir_model_data, they are loaded anyway as we do not have any idea if they depend on anything. Those are usually user created workflows... so the user should know.

### CODE REVIEW

**Comment by llacroix** [comment]
Problems related to this bug:

https://github.com/OCA/knowledge/pull/30
https://github.com/OCA/knowledge/pull/25

**Comment by hbrunn** [comment]
:-1: see https://github.com/OCA/OCB/pull/175#issuecomment-81565499

**Comment by antonylesuisse** [comment]
I close this pull request for various reasons

- We never encountered the use case
- Many workflows have been removed in v9
- It's more a deployment integration issue (might be faced by our migration team but they will handle it)

**Comment by llacroix** [comment]
@antonylesuisse It's not because you don't see it that it's not there. The issue might not happen for you or even the migration team as long as you don't add a module that extends a model and at the same time creates a workflow that call a new method that isn't present on the base model. Since Odoo can easily modify any modules, this issue can be easily fixed on your side. But for people that customize modules without touching to the odoo core, it can create unexpected behaviours.

In all honesty, it doesn't make any sense to call a workflow of a module that hasn't been yet loaded. Because the workflow might depend on things added by the module that created the workflow. Otherwise, you could call the workflow without having any errors but the code that is expected to run wouldn't run as expected...

This could create hidden bugs that might be hard to debug as migration, updating doesn't happen everyday and even if you never faced that issue, it doesn't mean it's not there... You could be feeling this wrong behaviour for years for existing workflows and you wouldn't know as long as there is no plain errors like we faced. Keep in mind that even if it's not raising an exception, it doesn't mean that it's working fine.

**Pull request closed without merging**
