### PR TITLE
[MERGE] Forward port of saas-11.3 to 12.0 up to d8072d54acf8

### PR DESCRIPTION
**Pull request by mart-e**

### CODE REVIEW

**Comment by mart-e** [comment]
A few remarks:

@jpp-odoo 3125a943d5f7ef50341c805484902606e1c3523e in account_voucher was conflicting with 8aaab680a9db7437c5a076a5d59a19e44e84a06d from @kebeclibre . Do you confirm it was fixing the same bug and I can keep the 12.0 version.

@kebeclibre 06d149a3b1c59594d776e418658e7b5db043a7d2 in l10n_be_intrastat(_2019) was skipped as no longer exists in 12.0 (enterprise?)

**Comment by mart-e** [comment]
@robodoo merge review+ priority=0

**Comment by kebeclibre** [comment]
@mart-e 
Nope, @jpp-odoo and I fixed different bugs. Although very similar.
Mine involved a tax price included.

**Comment by d-fence** [comment]
@robodoo r+

**Comment by d-fence** [comment]
@robodoo retry

**Comment by d-fence** [comment]
@robodoo p=0

**Pull request merged**
