### PR TITLE
Update base country data for ecuador.

### PR DESCRIPTION
**Pull request by Stentor**
Description of the issue/feature this PR addresses:

Current behavior before PR:
Country Ecuador doesn't have correct document identifier (RUC)
Countyr Ecuador has no states.

Desired behavior after PR is merged:
Country Ecuador has correct document identifier (RUC)
Countyr Ecuador has states.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Stentor** [comment]
@ren-odoo @jco-odoo This is the pr for base, it gives the same error as discussed earlier.

**Comment by jco-odoo** [comment]
@Xavier-Do Is there a way to avoid/bypass these migration tests failing or is backporting from master the only way?

**Comment by Xavier-Do** [comment]
This will need some upgrade script tweeking. Working on it.

**Comment by Xavier-Do** [comment]
Should be ok. Please once merged forward port it as soon as possible without making any changes.

**Comment by jco-odoo** [comment]
@Stentor @marpocho Can you update the commit message to [IMP] base: add res.country.state for EC  (or something according to the standard format)  

I see that in the name of the states, we put a letter as their abbreviation.  Sure it is not that that we want to use as code?

**Comment by ren-odoo** [comment]
> @Stentor @marpocho Can you update the commit message to [IMP] base: add res.country.state for EC (or something according to the standard format)
> 
> I see that in the name of the states, we put a letter as their abbreviation. Sure it is not that that we want to use as code?

Hi @Stentor @marpocho  I have the same concern than @jco-odoo, it seems the  text in parentheses is not part of the ofical state name so we souldn't add it in the description.

**Comment by Stentor** [comment]
Hi, Those letters are not the official codes, which are numerical, but represent an alternate code in some cases (car plates for example). They are there for the sake of completeness, but can be removed.

Tell me if you prefer them removed, and i'll make the commit without them.

**Comment by ren-odoo** [comment]
> Hi, Those letters are not the official codes, which are numerical, but represent an alternate code in some cases (car plates for example). They are there for the sake of completeness, but can be removed.
> 
> Tell me if you prefer them removed, and i'll make the commit without them.

@Stentor in that case I think the best is to remove them so we can keep as standard as possible and as well to be more homogeneous with the other contries.  @jco-odoo do you agree?

cc. @vbe-odoo

**Comment by jco-odoo** [comment]
@Stentor Could you squash it as well so we have just one commit?

**Comment by Xavier-Do** [comment]
@jco could you merge this yourself since upgrade exceptions are active for this pr?

**Comment by jco-odoo** [comment]
@Stentor Could we please just have one commit here without the merge commit, so we can merge this?  (It should be a small thing to do, so this does not stay open)

**Comment by jco-odoo** [comment]
@ren-odoo

**Comment by vbe-odoo** [comment]
Hi @Stentor can you help up with the comment that @jco-odoo made, so we can merge this and close it.
Comment:
> @Stentor Could we please just have one commit here without the merge commit, so we can merge this? (It should be a small thing to do, so this does not stay open)

Many thanks!
cc' @ren-odoo

**Comment by Stentor** [comment]
Hi @jco-odoo @ren-odoo @vbe-odoo 

I tried to squash the commits but it looks like i failed.
Maybe it is better to close this PR and another clean one?

**Comment by jco-odoo** [comment]
@Stentor Can not you do a new branch and then force push to this one?

**Comment by Stentor** [comment]
@jco-odoo I made the force-push, is it ok?

**Comment by jco-odoo** [comment]
@Stentor We lost the CLA changes, I think.  You can put them in the same commit if you want.

**Comment by jco-odoo** [comment]
https://runbot.odoo.com/runbot/build/7440513

**Comment by jco-odoo** [comment]
@Stentor Could you just squash the 3 commits?  Sorry for the many pings.

**Comment by vbe-odoo** [comment]
Hi @Stentor 
Thanks for the squash.
I did a test in runbot from this PR (https://7441254-14-0-all.runbot55.odoo.com/), and I found that there are some repeated states but with a different State Code (all the ones that have this State Code are repeated, i.e. Azuay > 01 & EC-A. See pic attached:
image

Thanks!
cc' @ren-odoo @jco-odoo

**Comment by jco-odoo** [comment]
Nice catch @vbe-odoo   I don't know what to do with it however as apparently they were already present in the system.  We could update the codes...

**Comment by jco-odoo** [comment]
Also, these states were added last year into the l10n_ec module itself...  So, better to change it there and add it in master in base.  Sorry...

**Comment by vbe-odoo** [comment]
@jco-odoo yes, maybe instead of creating new ones, we can updates the codes.
And there are also some states that are not repeated, as you can see below, and those are the ones with the code not being numbers:
image

cc' @ren-odoo @Stentor

**Pull request closed without merging**
