### PR TITLE
Fixed spelling mistake

### PR DESCRIPTION
**Pull request by Protoneer**
Description of the issue/feature this PR addresses:
Spelling mistake:
You cannot change the ratio of this unit of mesure as some

Current behavior before PR:

Desired behavior after PR is merged:
Fixed spelling:
You cannot change the ratio of this unit of measure as some

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by KangOl** [comment]
The CLA check doesn't pass because the author of your commits doesn't match the email you specified in the CLA.

**Comment by Protoneer** [comment]
> The CLA check doesn't pass because the author of your commits doesn't match the email you specified in the CLA.

Thanks. Fixed the issue with the CLA email.

**Comment by MiquelRForgeFlow** [comment]
The .pot file should be updated accordingly.

**Comment by Protoneer** [comment]
> The .pot file should be updated accordingly.

I have updated the pot file.

**Comment by mart-e** [comment]
Hi,

Thanks but this kind of changes can not target the stable version, it would break the translations.
As the saas-13.1 is not yet deployed, it is still safe to do it there.
I have rebased and moved your PR to target this one.
Thanks for the patch and the CLA signature.

@robodoo r+

**Comment by KangOl** [comment]
>  it would break the translations.
Are you sure? Doesn't the Levenstein distance search [1] will match the translated terms?

[1] https://github.com/odoo/odoo/blob/967777793cf2a7591ef3d9325497b105eb86577c/odoo/addons/base/models/ir_translation.py#L433

**Comment by mart-e** [comment]
@KangOl the `_sync_terms_translations` is only for `xml_translate` fields. In this case you use the `_` method that will make an exact match.

https://github.com/odoo/odoo/blob/967777793cf2a7591ef3d9325497b105eb86577c/odoo/tools/translate.py#L470
https://github.com/odoo/odoo/blob/967777793cf2a7591ef3d9325497b105eb86577c/odoo/addons/base/models/ir_translation.py#L300-L301

**Comment by KangOl** [comment]
Then, not for the stable version.

**Pull request closed without merging**
