### PR TITLE
[FIX] hr_holidays: correct date format on leave name

### PR DESCRIPTION
**Pull request by sswapnesh**
Before this Commit, dates was not formatted based on user's language.

With this commit, we use format_date to correctly format dates.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
@tivisse

**Comment by sswapnesh** [comment]
OPW 2559216 and In Big Fixes state since 26 Days 🍕

**Comment by simongoffin** [comment]
robodoo r+

**Review by simongoffin — APPROVED** [review]

**Comment by simongoffin** [comment]
robodoo retry

**Comment by sswapnesh** [comment]
@simongoffin This needs r+ again

**Comment by simongoffin** [comment]
robodoo r+

**Comment by sswapnesh** [comment]
@simongoffin  Ping

**Comment by sswapnesh** [comment]
@simongoffin Can you r+ again ?
Or At least Keep Ticket open so you can have a followup on it

**Comment by rdeodoo** [comment]
> @simongoffin Can you r+ again ?

This doesn't need to be r+ again but just retry, nothing was pushed since last r+.

Not sure why are PRs waiting open over a year :shrug: 

I am not confident retrying the PR given the long time since it's r+..

**Comment by rdeodoo** [comment]
@robodoo retry

Tested and still seems to fix the issue.

Having a step to reproduce would really help (as always).
Here (surely there is an easier one, didn't check the opw):
- Login as admin
- Install french
- Switch admin lang to french
- Login as demo
- Create a leave
- Leave is assigned to admin, he receives a mail in french, the lang is formatted in english not in french

Note that on runbot, you can easily see that through the mailhog of the build.

**Comment by sswapnesh** [comment]
How regular is it to close the OPW without looking if PR is merged or not ?
(and even after multiple pings on Task/PR)

**Comment by rdeodoo** [comment]
Well, to be fair the bugfix workload was a bit out of control at some point. They did and do their best.

Such situations should be less frequent and shouldn't even happen anymore, as we made some internal change like involving the teams in the bugfix. Depending of the team, they are more or less involved. For instance the website team is now fully handling the bugfix issues themselves.
It should (and does actually) help the bugfix process.

Here, maybe @simongoffin could r+ again?
I had a quick test and this still indeed fix the issue. And the issue is there also in master, so quite cool as a fix IMHO.

**Comment by d-fence** [comment]
@simongoffin can you take a look at this fw-port ?
It needs to be fixed I think. Maybe the fix is adding some query.
Anyway, you should take care of it

**Comment by Xavier-Do** [comment]
Hello.
robodoo send a friendly message saying that the staging failed here: https://runbot.odoo.com/runbot/build/19188482

This message can be boring, yes, random errors and everything, but the initial purpose is to notify that something failed during the staging.
It can be rebase related, or maybe because not all tests are run everytime. Enterprise is not ran when you push community only to avoid load increase.

What is the error? Some query count increased in enterprise related to leave stuff.
Please push an enterprise branch to test and fix this ;).

**Comment by rdeodoo** [comment]
@robodoo r-

This is pointless keeping this one stuck in r+ for multiple years.
This is sad because the fix seems to be fine and fix something [important](https://github.com/odoo/odoo/pull/70061#issuecomment-1242535656) (showing wrong date format/lang is never great).

@sswapnesh Maybe if you can adapt the PR so the runbot is green I can see with the relevant team.

**Comment by sswapnesh** [comment]
Hi @rdeodoo 

It has nothing to with this PR but it needs changes on testvase of 'hr_work_entry_holidays' module.
(also there was no response on OPW which was clsoed already)

```

odoo.addons.hr_work_entry_holidays.tests.test_performance:91                                    FAIL: Subtest TestWorkEntryHolidaysPerformance.test_performance_leave_confirm (login='__system__') Traceback (most recent call last):   File "/data/build/odoo/odoo/tests/common.py", line 454, in assertQueryCount     self.fail(msg % (login, count, expected, funcname, filename, linenum)) AssertionError: Query count more than expected for user __system__: 23 > 21 in test_performance_leave_confirm at /data/build/enterprise/hr_work_entry_holidays/tests/test_performance.py:62
--
odoo.addons.hr_work_entry_holidays.tests.test_performance:91                                    FAIL: Subtest TestWorkEntryHolidaysPerformance.test_performance_leave_confirm (login='admin') Traceback (most recent call last):   File "/data/build/odoo/odoo/tests/common.py", line 454, in assertQueryCount     self.fail(msg % (login, count, expected, funcname, filename, linenum)) AssertionError: Query count more than expected for user admin: 32 > 30 in test_performance_leave_confirm at /data/build/enterprise/hr_work_entry_holidays/tests/test_performance.py:62
odoo.addons.hr_work_entry_holidays.tests.test_performance:91                                    FAIL: Subtest TestWorkEntryHolidaysPerformance.test_performance_leave_create (login='__system__') Traceback (most recent call last):   File "/data/build/odoo/odoo/tests/common.py", line 454, in assertQueryCount     self.fail(msg % (login, count, expected, funcname, filename, linenum)) AssertionError: Query count more than expected for user __system__: 27 > 25 in test_performance_leave_create at /data/build/enterprise/hr_work_entry_holidays/tests/test_performance.py:53
odoo.addons.hr_work_entry_holidays.tests.test_performance:91                                    FAIL: Subtest TestWorkEntryHolidaysPerformance.test_performance_leave_create (login='admin') Traceback (most recent call last):   File "/data/build/odoo/odoo/tests/common.py", line 454, in assertQueryCount     self.fail(msg % (login, count, expected, funcname, filename, linenum)) AssertionError: Query count more than expected for user admin: 36 > 34 in test_performance_leave_create at /data/build/enterprise/hr_work_entry_holidays/tests/test_performance.py:53


```

I can change the query count on these testcase if you think that is the only solution.

**Comment by tivisse** [comment]
Please note that this is not a random bug, this is a deterministic issue as this commit adds new requests on query counters tests that are defined in the enterprise repository.

As this branch is only targeting the community remote, the tests are not executed on runbot, but are really crashing once executed by mergebot.

**Comment by sswapnesh** [comment]
@rdeodoo @tivisse Made a PR https://github.com/odoo/enterprise/pull/34472 to update query count

**Comment by rdeodoo** [comment]
Great, thanks, I'll leave that up to the relevant team to take it over from here.

**Comment by tivisse** [comment]
The related enterprise PR https://github.com/odoo/enterprise/pull/34472 does not have the same branch name, and therefore is not taken into account to make the build. 

Could you update this ? 

Thanks :)

**Comment by sswapnesh** [comment]
Hello @tivisse 
New PR: https://github.com/odoo/enterprise/pull/34564

**Pull request closed without merging**
