### PR TITLE
[FIX] Add name_search to be consistent with name_get for bank model

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Currently, isn't possible to search a bank based on its BIC code.
For instance, on a bank account, it is possible to select a bank. At this point, the user sees BIC_CODE - BANK_NAME. Therefore, the user tries to encode first a bic code.

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
OPW 657414

**Comment by beledouxdenis** [comment]
Hello Adrien,

Unfortunately, we consider this as a feature: The possibility to search banks on their BIC code.

Proposal adding features are not accepted in stable releases, such as Odoo 8.0. For more information about our stable policy, you can read:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

Regards,

**Comment by adrienpeiffer** [comment]
Hi Denis,
Currently, a user (who has no knowledge about name_get name_search) can not search information with what he sees of this information. This is not a bug?

**Comment by adrienpeiffer** [comment]
bank_account2

bank_account3

**Comment by adrienpeiffer** [comment]
@beledouxdenis Have you considered these comments ?

**Comment by adrienpeiffer** [comment]
OPW 660613

**Comment by adrienpeiffer** [comment]
@beledouxdenis Can you reopen this one ?

**Comment by beledouxdenis** [comment]
After having discussed this with Antony, we still do not consider this as an issue, but rather as a feature.

At least, this is not a blocking bug.

For more information about our stable policy, you can read the following documentation:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

**Comment by adrienpeiffer** [comment]
Thanks for your answer.
However, this is really disturbing for end users ...

**Comment by beledouxdenis** [comment]
We have no problem to change this in master, but not within a stable release such as 8.0.

This is a usability improvement, not a blocking bug.

I hope you will understand.

**Pull request closed without merging**
