### PR TITLE
[IMP] web_editor: different numbered list marker at each level

### PR DESCRIPTION
**Pull request by deso-odoo**
Purpose:

To make the marker of a ordered list different at each level.
- Numbers for first level.
- Alphabets for second level.
- Roman numbers for the third level.
- looping back to numbers if nested further.

To make the marker of a unordered list different at each level.
- Disc for first level.
- Circle for second level.
- Square for the third level.
- looping back to disc if nested further.

task-3412826

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
@robodoo r-

**Comment by dmo-odoo** [comment]
@Xavier-Do What was the deal here ? Care to explain ? ^^' Can I r+ it back now ?

**Comment by Xavier-Do** [comment]
Sorry I was trying to understand why the mergebot was stuck and forgot to come back to explain. Yes you can r+ again ;)

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
