### PR TITLE
[FIX] web_kanban: hide kanban_groups when there's no record.

### PR DESCRIPTION
**Pull request by shingonoide**
Hide  kanban_groups or columns when there's no record to show.
I know this create a problem in time to create a new column, but I think
this is better.

The PR try to fixes the #2884

### CODE REVIEW

**Comment by shingonoide** [comment]
I wrongly delete my original branch, reopen the issue now.
Can anyone help me with this pull request? 
Am I doing anything wrong?
Thanks

**Comment by mart-e** [comment]
Hello,

As you say, this will not work in case of adding a new column.
Instead of hiding the `oe_kanban_groups`, wouldn't it be better to hide the `oe_view_nocontent` (the help message) in case of grouped view ? This is the behaviour of the kanban view in master (where the bug is not present).
What do you think ?

**Comment by shingonoide** [comment]
Hello,

Thanks for reply, yeah you are right. thanks to points me a direction.
I see the master branch and works fine for me but would like to show the help message when there's no record to show.
I don't know yet how to do that and guess is not so important, the master branch behavior seems ok for now.
So, how can I proceed to fix that error? create a new pr or edit this one?

**Comment by mart-e** [comment]
You can update this PR, no problem, we will squash the commits when merging.

**Comment by shingonoide** [comment]
@mart-e Have done as that you suggests.
Hope the changes can close the issue #2884, thanks.

**Comment by tivisse** [comment]
Hello @shingonoide 

The ``web_kanban`` module doesn't exist anymore. I close this PR, but if it's still relevant to you, plase make another PR for master.

Have a nice day,

Yannick Tivisse.

**Pull request closed without merging**
