### PR TITLE
[CLA] sign CLA for Inspired Software

### PR DESCRIPTION
**Pull request by inspiredbusiness**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `c...@inspiredbusiness.com.au`
- you are signing _for_ the address `c...@inspiredsoftware.com.au`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by inspiredbusiness** [comment]
Hi,

I updated my git settings and changed them in github to add the email address and make it the primary email address to the account. Do I need to do anything to re-test the CLA? Or should I push a new commit to a new PR?

**Comment by mart-e** [comment]
@inspiredbusiness yes please, just push a new commit with the correct email and it should be fine

**Comment by mart-e** [comment]
Hello,

Do you still wish to sign the CLA?

**Pull request closed without merging**
