### PR TITLE
[FIX] stock: Allows to transfer partially with cancel

### PR DESCRIPTION
**Pull request by rousseldenis**
Do a transfer in two steps (Vendors > Input > Stock)
with propagate_cancel moves == True.

On the first picking, do a partial transfer in terms of quantities
(e.g.: 8 instead of 10) and do not request a backorder.

The remaining quantities are cancelled either on the first picking
either on the second one.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rousseldenis** [comment]
@amoyaux @ryv-odoo

**Comment by rousseldenis** [comment]
On runbot (standard process):

Create a PO with buy rule allowing cancel propagation (default):

image

image

Added propagate_cancel field in picking view to check value: 

image


Fill in partial value for one line:

image

Validate and don't create backorder:

image

Internal transfer :

image


This behaviour is dangerous because if quantities are never received, this picking never be processed.

**Comment by rousseldenis** [comment]
After this modification, reception and internal transfer are aligned !

image


image

**Comment by rousseldenis** [comment]
@chrisdec @ThomasBinsfeld

**Review by carlosdauden — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Comment by rousseldenis** [comment]
Don't hesitate to comment if you don't like some parts I did

**Comment by rousseldenis** [comment]
If we merge this, this PR is mandatory to avoid wizard launch in cancel cases : https://github.com/odoo/odoo/pull/66122

**Comment by amoyaux** [comment]
@rousseldenis I'm okay with the feature. However we prefer to add it in master

**Comment by randall-vx** [comment]
@JulioSerna

**Comment by rousseldenis** [comment]
> @rousseldenis I'm okay with the feature. However we prefer to add it in master

Ok, I'll do the PR

**Pull request closed without merging**
