### PR TITLE
[FIX] mail: missing notif in systray / incorrect inbox notif

### PR DESCRIPTION
**Pull request by seb-odoo**
When handling notifications in Odoo and tagging the user on a SO / task / whatever, the messaging counter is increased by 1 and the notification appears in the inbox, but not in the systray.

This is because the needaction is wrongly set with the value of the current user, which is the user that is doing the action, not the user that should be notified. This happens since the introduction of `for_current_user` param and the removal of broadcasting too much stuff.

This commit fixes the issue by correctly setting user when it comes to the personalized notify.

Replaces https://github.com/odoo/odoo/pull/168855

Backport of https://github.com/odoo/odoo/pull/171863 and https://github.com/odoo/odoo/pull/171869 to fix the issue.
It's still unclear whether 17.3 will ever be put in production, but it's still sticky on runbot so we have to support it.
Stable policy is stretched a little bit here as nobody should be using the removed methods at this point.

### CODE REVIEW

**Comment by seb-odoo** [comment]
@robodoo help

**Comment by seb-odoo** [comment]
@robodoo fw=no

**Comment by seb-odoo** [comment]
@robodoo rebase-ff

**Review by alexkuhn — APPROVED** [review]
@robodoo r+ rebase-ff override=ci/security
`sendmany` on safe partners of targeted followers of a message

**Comment by seb-odoo** [comment]
@robodoo retry

**Comment by seb-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
