### PR TITLE
[CLA] Corporate signature for Wiserby OÜ

### PR DESCRIPTION
**Pull request by DenisZhadan**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `DenisZhadan@users.noreply.github.com`
- you are signing _for_ the address `..@wiserby.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by DenisZhadan** [comment]
Hi.
Is email now visible?

**Comment by mart-e** [comment]
If you changed your privacy settings, this will only have an effect on new commits, not retroactively. So if you push something in the branch (even like adding an empty line), the CLA check will pass.

**Comment by mart-e** [comment]
Looks good now. Should I include this one instead of #49809 or do you want to update it too ?
By the way, the CLA are ported to upper version (so merging this in 13.0 will end up in master too)

**Comment by DenisZhadan** [comment]
#49809  updated.

**Comment by mart-e** [comment]
> #49809 updated.

Yes but which one do you want me to include? One is enough

**Comment by DenisZhadan** [comment]
Can include this file? It was before, but they are the same, the difference in date.

**Comment by mart-e** [comment]
Sure ! Thanks for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by DenisZhadan** [comment]
Thanks

**Pull request closed without merging**
