### PR TITLE
[FIX] stock: Fixed typo

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: Fixed Typo

Current behavior before PR:

Desired behavior after PR is merged:

Followup on e3b8fe202401e7a11938329373d94d7b60794088
https://github.com/odoo/odoo/blob/e3b8fe202401e7a11938329373d94d7b60794088/addons/stock/wizard/stock_change_product_qty.py#L13

Cc: @tde-banana-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Well either we fix the TODO, either we remove this comment if it does not make sense anymore but lets not start fixing typos in comments that should be removed anyway

**Comment by sle-odoo** [comment]
i don't even see the default method the comment is talking about

**Comment by Yenthe666** [comment]
Indeed, I think this comment is actually outdated and that it can be removed completely.

**Comment by mart-e** [comment]
This one ?

https://github.com/odoo/odoo/blob/c02d04a2966ea6c88c522d73d81c9e7a64437fa5/addons/stock/wizard/stock_change_product_qty.py#L28-L34

**Comment by sle-odoo** [comment]
So i double checked and, hopefully before saas-12.4, this wizard will be removed in in favour of another way to do quick inventory adjustment. Therefore i think we can cancel this PR.

Thanks for your contribution.

**Pull request closed without merging**
