### PR TITLE
[I18N] Improve es_MX translation for VAT name, change from IVA/NIF to RFC

### PR DESCRIPTION
**Pull request by alan196**
Description of the issue/feature this PR addresses:

This PR translate the correct term for VAT in Mexico that is RFC

@mart-e Could you help me to review this PR 🙏 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
We use the vat_label as a way to differentiate between the names given for the VAT (number) in different countries.  It is not the best idea to change all the translations for that, because they could appear in totally independent situations.

**Comment by alan196** [comment]
> We use the vat_label as a way to differentiate between the names given for the VAT (number) in different countries. It is not the best idea to change all the translations for that, because they could appear in totally independent situations.

@jco-odoo I understand your point, but this field is not shown in customer form view, the view was ok the last week, now I receive complains from all my customers that are on Odoo.sh that the label was changed from RFC to IVA

In Mexican Spanish IVA is the name of a tax, the correct term is RFC not VAT or NIF (I understand that NIF is for Spain) If the term changes from the country  of the partner, or even the company I'm ok but that is not the current behaviour.

**Comment by mart-e** [comment]
Hey @alan196 

Good news, es_MX is now on Transifex 
https://www.transifex.com/odoo/odoo-14/language/es_MX/

You can submit your changes there then

**Comment by jco-odoo** [comment]
Indeed, better to pass through Transifex here, but the RFC is referred to as a Mexican VAT number, while it is perfectly possible that a Mexican would see an error message about e.g. a Spanish VAT number where the term RFC does not make sense, but NIF would.  It could be a good idea to talk about the more generic term VAT number wherever possible.  If it really gets confusing for clients, RFC is better then.

**Pull request closed without merging**
