### PR TITLE
stock add is_signed boolean computed field

### PR DESCRIPTION
**Pull request by msh-odoo**
PURPOSE
Show signed field in stock.picking listview as boolean widget.

SPEC
Add is_signed computed boolean field and add it into stock.picking listview.

TASK 2580117

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
robodoo r+

**Comment by tanghulu0608** [comment]
@msh-odoo  I have a question about this commit. Why not store the field is_signed to db? Every time the tree view is displayed, the field is compute again and again. I think this is will be a performance issue.

**Comment by msh-odoo** [comment]
@tanghulu0608 I don't think so, compute method is not complex as well as it has dependency of signature field, also storing it doesn't make sense as just added compute field just for display purpose, what do you think @amoyaux

**Comment by tanghulu0608** [comment]
@amoyaux  hello

**Comment by amoyaux** [comment]
It won't be an issue

**Pull request closed without merging**
