### PR TITLE
[FIX] mail: channel duplication

### PR DESCRIPTION
**Pull request by MerlinGuillaume**
Messages are copied when duplicating a channel

Steps to reproduce:
1. Install Discuss
2. Write a message in the general channel in Discuss
3. Duplicate the general channel (user demo should be a member of this
channel) and give it another name
4. Connect as demo
5. The new message notification is on the general channel (and it should
be the duplicate channel
6. Mark the notification as read
7. Refresh the page
8. The notification is still there even though it has been marked as
read

Solution:
Do not copy the message of the original channel

Problem:
`channel_message_ids` is copied when duplicating a channel

opw-2731842

### CODE REVIEW

**Review by rco-odoo — COMMENTED** [review]
I am no specialist of this code, but it simply looks incorrect to me.  It compares `mail_channel_partner.channel_id` to `self.ids`, where `self` is not necessarily a `mail.channel.partner`!  This code is generic to all models that inherit from `mail.thread`.

@seb-odoo maybe you should have a look at this.

**Comment by seb-odoo** [comment]
Hello, indeed we are in the process of cleaning it in master https://github.com/odoo/odoo/pull/83765/

The code is currently generic but it is not called for anything else than a channel since a long time.

I'll have to check in more details the bug that we try to fix here (in the next days).

**Comment by rco-odoo** [comment]
> The code is currently generic but it is not called for anything else than a channel since a long time.

If you make that change, then please add some comment explaining why the new query is correct.  Without knowing that information, you simply have no chance to understand why the query is correct...

**Comment by seb-odoo** [comment]
> msg.res_id is the original channel in which the message was created so
duplicating a channel would make a notification on the original channel

Isn't this the problem then? `res_id` of the message must be the new channel, otherwise it makes no sense.

Note that duplicating a channel is not really a common/wanted use case. If anything I would say at best that duplicating a channel should duplicate its configuration, maybe its members, but not its message or anything else.

Also I'm not really fan of fixing this in v13, when the issue is probably no longer here in v15/master due to design changes preventing such inconsistencies. (messages are no longer linked to channels through `channel_ids` field but only through `res_id`)

So I would either:
- do nothing, it's not a breaking issue and it's fine in master (messages are not duplicated)
- ensure that when channels are copied, `res_id` of copied messages are properly changed (if we want to reduce the "functional change" in stable but still fix the issue)
- prevent from duplicating messages ("functionally change" in stable, but it makes the most sense and goes towards what is done in master)

We should however clearly not change the query to support this broken use case.

**Comment by MerlinGuillaume** [comment]
Hello @seb-odoo,

> `res_id` of the message must be the new channel, otherwise it makes no sense.

The message is not duplicated in the `mail_message` table (this table only contains the original messages) when duplicating a channel, but there is a new entry in the `mail_message_mail_channel_rel` table, which tells which message is in which channel (with possibly the same message in multiple channels if a channel was duplicated).

> ensure that when channels are copied, `res_id` of copied messages are properly changed (if we want to reduce the "functional change" in stable but still fix the issue)

So I don't think this solution is good because it will change the `res_id` of the original message.

> prevent from duplicating messages ("functional change" in stable, but it makes the most sense and goes towards what is done in master)

I think this should be the way to go. Do you agree ?

**Comment by MerlinGuillaume** [comment]
@seb-odoo Should be okay now :)

**Review by seb-odoo — APPROVED** [review]
Thank you for the update

@robodoo r+

**Pull request closed without merging**
