### PR TITLE
[FIX] odoo_referral: remove referral

### PR DESCRIPTION
**Pull request by tfr-odoo**
Remove referral feature.
    
Keep empty JS and asset template so there is no need to update or uninstall
the module to disable the feature.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
To check with @odony if we remove the notification counter route in internal. I would keep it in case someone changes his mind, and wants to put it back. (Also known as the **Salary Configurator Syndrom** or **SCS**)

Apart from that, LGTM.

**Comment by tfr-odoo** [comment]
@odony @tivisse deprecated code has been removed

**Comment by tfr-odoo** [comment]
@odony @tivisse deprecated code has been removed

**Comment by tfr-odoo** [comment]
@odony @tivisse Now that we want to remove completely this feature, I have updated the PR. I just keep a empty JS asset so there is no need to upgrade or uninstall the module to deploy this PR on existing database.

**Comment by tivisse** [comment]
Well I'm ok then :)

**Comment by tfr-odoo** [comment]
@odony @tivisse Who take care of the r+

**Comment by tivisse** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo retry
sorry, for the failure. A small mistake on runbot.

**Pull request closed without merging**
