### PR TITLE
[IMP] chart template, tax val generation fix

### PR DESCRIPTION
**Pull request by blaggacao**
Same motivation as #14980 just for the tax case

This change is not fully api compliant.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
hum, this shouldn't be done in stable version, for the breaking-tha-API-reason-you-know-about.

I'll re-target that to saas-14 if you don't mind

**Comment by qdp-odoo** [comment]
err... I didn't notice it was closed... I'm confused now, I suppose you still need that, right?

**Comment by qdp-odoo** [comment]
landed on saas-14 at revision 155e74a

thanks for the contribution

**Comment by blaggacao** [comment]
Great, no problem to keep that pending in a patch on our side until 14... 😄  Thanks!

**Pull request closed without merging**
