### PR TITLE
[11.0][FIX] hr_holidays: extra space in state check

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Typo fix that causes incorrect decoration

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please make the PR only in the lowest branch that applies.

**Comment by alexey-pelykh** [comment]
@pedro 11.0 (and 10.0) PR differs from 12.0, thus not sure how to proceed. Yet there's full selection of PRs thus can be processed in the most proper way possible

**Comment by pedrobaeza** [comment]
I think forward port team will handle the little differences.

**Comment by mart-e** [comment]
Duplicates of #29898

**Pull request closed without merging**
