### PR TITLE
[FIX] website_sale: prevents the modification of a SO line if SO is not 'draft'

### PR DESCRIPTION
**Pull request by nim-odoo**
opw-634681

### CODE REVIEW

**Comment by beledouxdenis** [comment]
With this, if a user try to modify a non-draft sale order in the website, won't this lead to a 500 internal server error on the website ?

**Comment by nim-odoo** [comment]
No, it does not lead to a 500 internal error, but for the user:
- the value entered by the user remains changed
- the total amount is unchanged.
This is not coherent.

I changed the commit, so that it does not raise an error. This way, the JS layer will simply set back the original values.

**Comment by beledouxdenis** [comment]
I do not believe is the right solution: As a visitor, I would wonder myself why every changes I do is not applied, and would believe it's a bug.

Is it not possible to somehow display the error in the cart ? Or to unblock the situation somehow ?

When does this happen ? When the Ogone/Paypal is cancelled ? Refused ? Done ? 
For the two first cases, you could simply duplicate the SO when it happens, I guess, or something like that.

**Comment by nim-odoo** [comment]
Code update:
- raise an error in _cart_update: not necessary here, but to be sure it will not happen
- reset the cart
- redirect to '/shop'

The redirection is done in the JS because the route '/shop/cart/update_json' is of type json, which does not allow request.redirect('/shop').

**Comment by beledouxdenis** [comment]
Just saw that there is
```
if (!data.quantity) {
    location.reload();
```
You can therefore probably do:
```
+        if order.state != 'draft':
+            request.website.sale_reset()
+            return {'quantity': False}
+
```
then drop the 
```
+                if (data.sale_reset) {
+                    $(location).attr('href', '/shop');
+                    return;
+                }
```
The page will be reloaded (on the cart, I guess), and the user will see that his cart is empty, which seems to me as good as redirecting the user to the `/shop`

**Comment by nim-odoo** [comment]
Indeed, it shows 'your cart is empty'. I drop it then.

**Pull request merged**
