### PR TITLE
[FIX] use the column._symbol-c as placeholder for the column value

### PR DESCRIPTION
**Pull request by lmignon**
When generating the SQL query in  the low level '_create' method from
BaseModel, column._synbol-c must be used as placeholder as for the
method 'set' of the column itself. Otherwise it's no more possible to define specialized column.

### CODE REVIEW

**Comment by lmignon** [comment]
ping @rco-odoo

**Comment by guewen** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by lmignon** [comment]
ping @rco-odoo

**Comment by lmignon** [comment]
@rco-odoo @odony Can you take care of this one?

**Comment by yvaucher** [comment]
@rco-odoo bump

Here is the same for 9.0 #10639 (we need it anyway to make sure our build are ok on OCA/geospatial/pull/60 )

**Comment by rco-odoo** [comment]
@lmignon your commits have been cherry-picked as d82e489add442f0bef52b58620c8d7988919872d onto branch 8.0. Note that I fixed an extra case in the same commit. It will be forward-ported soon on branch 9.0.
Thanks a lot for your contribution, and sorry for the delay!

**Comment by lmignon** [comment]
@rco-odoo thank you!

**Pull request closed without merging**
