### PR TITLE
[CLA] Add new contributors to C2C CLA

### PR DESCRIPTION
**Pull request by JuMiSanAr**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@JuMiSanAr you have to use your C2C email address not gmail. Also you can squash your commits into one if you wish.

**Comment by JuMiSanAr** [comment]
> @JuMiSanAr you have to use your C2C email address not gmail. Also you can squash your commits into one if you wish.

Thanks for the comment @mart-e !

I'm already using my c2c email address: `juan.sanchez@camptocamp.com`. I currently have two different email addresses linked to my account, and the c2c one is selected as the "primary" one. That should be ok right?

Regarding the commits, is it ok to leave them like this? In the past, most of these lines have been added one by one in each own commit, I think it's more consistent like this.

**Comment by mart-e** [comment]
Check https://github.com/odoo/odoo/pull/137603.patch you will see that you are using your gmail address in your commits.

> Regarding the commits, is it ok to leave them like this? 

Yes if you prefer, I don't mind.

**Comment by JuMiSanAr** [comment]
> Check https://github.com/odoo/odoo/pull/137603.patch you will see that you are using your gmail address in your commits.
> 
> > Regarding the commits, is it ok to leave them like this?
> 
> Yes if you prefer, I don't mind.

It should be ok now, thanks!

**Comment by mart-e** [comment]
Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+ rebase-ff

**Pull request closed without merging**
