### PR TITLE
[FIX] microsoft_calendar: prevent parallel JS calls to sync_data

### PR DESCRIPTION
**Pull request by lse-odoo**
Before this commit:
A call to `sync_data` was made each time an event happen in the calendar
( changing the day, switching to day/week/month/year ).
This can easily saturate the server and spam the Microsoft API.

After this commit:
One call is made at a time per tab.

This PR is an adaptation of the same fix which was done only for
Google calendar at:
https://github.com/odoo/odoo/pull/69619/files#diff-8457ad89f2f7a1847af533828b40994bfc6d80e1e9d45ee7707b534bda2b0f06
and partially solve another PR that I was planning (but a bit too "overkilled"):
https://github.com/odoo/odoo/pull/85465

OPW-2749791 & OPW-2741728

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by remybar** [comment]
Looks good to me :+1:

**Comment by lse-odoo** [comment]
> Looks good to me +1

can you r+ it or should I ask the review of someone else in particular ?

**Comment by remybar** [comment]
> > Looks good to me +1
> 
> can you r+ it or should I ask the review of someone else in particular ?

I haven't this power ;-) So you have to ask to ARJ or someone else for the r+

**Comment by arj-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
