### PR TITLE
[FIX] l10n_il: fix default purchase tax

### PR DESCRIPTION
**Pull request by yediel**
### Steps to Reproduce

1. Install i10n_il module
2. Go to Settings->Invoicing

**Expected behavior:**
Tax il_vat_inputs_17 (VAT inputs) is selected as default Purchase tax

**Actual behavior:**
Tax il_vat_self_inv_purchase (Self Invoice) is selected as default Purchase tax.
This causes new Vendor Bills to be created without VAT

### CODE REVIEW

**Review by proose — APPROVED** [review]
Looks good to me, someone else will come look at this and merge :+1:

**Review by FlorianGilbert — COMMENTED** [review]
Hello

May I ask you to add the PR message in your second commit message?
Thank you

**Comment by FlorianGilbert** [comment]
> > Hello
> > May I ask you to add the PR message in your second commit message? Thank you
> 
> Instead of the CLA message?

No, keep both commits in the same order.
On your second commit (the one where you're doing the fix, may I ask you to copy/paste the PR message into the commit message)?

**Comment by yediel** [comment]
> > > Hello
> > > May I ask you to add the PR message in your second commit message? Thank you
> > 
> > 
> > Instead of the CLA message?
> 
> No, keep both commits in the same order. On your second commit (the one where you're doing the fix, may I ask you to copy/paste the PR message into the commit message)?

done

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+

**Comment by FlorianGilbert** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
