### PR TITLE
[FIX] stock_account: Current inventory valuation

### PR DESCRIPTION
**Pull request by simongoffin**
The "Current inventory valuation" report should only take the negative quants into account
to compute the inventory value.

opw:632358

### CODE REVIEW

**Comment by beledouxdenis** [comment]
I would like @jco-odoo review for this one :).

**Comment by jco-odoo** [comment]
No, this is not it.  It is the opposite and the easiest and most performant (as it is already a slow report) is to change it in the sql (where quant.qty > 0)

**Comment by simongoffin** [comment]
I think that if you change the sql like you said, the quantity for each line will be modify and the quantity displays for each line seems to be correct. This is just the way to compute inventory value which is wrong.

**Comment by beledouxdenis** [comment]
Closed with c884be3be9bf6aeb11e4191bc3f77517635f24d0.

**Pull request closed without merging**
