### PR TITLE
[IMP] stock: apply preferred route on push rules either

### LINKED ISSUE #20213: [IMP] apply preferred route also on push rules
@sle-odoo @amoyaux having you been committing the changes to stock recently, I wanted to know if it is a deliberate decision to not support preferred routes on push rules?

**Background:** I'm working on a import module and want to send pre-configured push rules from the PO, as preferred route, according to the entry harbor. I'll do a quick PR, and like to ask you would consider it a harmful operation, what I'm pretending to suggest...

### PR DESCRIPTION
**Pull request by blaggacao**
Before this commit, an eventual preferred route recordset was not taken into
account on push rules.

This inhibited on a fundamental level downstream routing deliberations/flexibility.

As an example the PO-Line does indeed construct a preferred route Set and passes
it on to the Move. While it is constructed, it is actually never used (stub).
This, however, is indicating, that POs originally where thought to be able to determine
downstream routing.

This commit, makes preferred routes been taken into account on push rules either.
This enables the use case, that a PO would determine a certain routing, eg. import
operations through harbor X.

**Closes #20213** 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by blaggacao** [comment]
@sle-odoo @amoyaux What do you guys think of this? Best Regards

**Comment by amoyaux** [comment]
@blaggacao It makes sense for me. @lap-odoo Gonna also check and provide you a greater answer and maybe create a new task in our backlog.

**Comment by lap-odoo** [comment]
@blaggacao I agree it makes sense. I've created a task in our backlog, we will have a look at your PR. Thanks for the feedback.

**Comment by blaggacao** [comment]
Great to hear that, you're welcome... I was long thinking if this will break things, but in the end, it's just a **preferred** route, usually set manually and therefor intentionally no matter what. However, You might have a look on why the PO is constructing a preferred route list based on the warehouse, it puzzled me when investigating this.

**Comment by lap-odoo** [comment]
@blaggacao : I find it too risky to do such a change on a stable version. Ok it's only for preferred routes, but let's imagine that your preferred includes a push rule and a pull rule. When you apply it, the pull rule works but not the push rule. If we apply a fix, suddenly the push rule will work changing the behavior while the user didn't change the configuration.

**Comment by blaggacao** [comment]
Absolutely agree, should be master, I have no trouble in backporting until we'll migrate.. Thanks!

**Comment by blaggacao** [comment]
@lap-odoo Can you marge this in master, so that I can close this PR for good?

**Comment by lap-odoo** [comment]
@blaggacao Hi, sorry but I'm not able to merge it by myself, I need developers to do it and they've been busy with priority tasks. I confirm you it is well in our backlog and this should normally be merged before the next saas release.

**Comment by Yenthe666** [comment]
It has been confirmed in october (18th) that this would be a neat fix. It is now 29 january. You can't tell me all of those developers have been on priority tasks all the time right? 😞

**Comment by sle-odoo** [comment]
@Yenthe666 Laura just told you it's in the pipe and is targeted to saas-11.2, what more do you want to hear?

**Comment by lap-odoo** [comment]
@Yenthe666 : Yes, I can tell you that all the developers of the logistics team have been working on more important tasks since then. This behavior is present since at least version 9 and this doesn't seem to be very annoying since we didn't receive many complaints from customers (via the support) or feedback (from consultants, salespeople, ...) about it. 

We prefer to treat first the tasks that are blocking our customers or that are often requested by them.

You have also to understand that the priorities are very flexible, they can change at any moment if a task which is more important than another one arrives in the pipe. 

Note also that we are always quite busy after the release a new version. Especially since this new version (V11) brings a lot of changes in Stock due to the refactoring.

**Comment by Yenthe666** [comment]
@sle-odoo apoligies, didn't want to offend you or Laura. Am I correct that saas-11.2 is the new master or? I'm curious where the number change all of a sudden came from (changing from saas-x to saas-x.x)

Just to be clear: I'm very happy for the work you guys are doing and I know you all do the best you can. I just try to find good PR's and get more attention/love for them.
Sorry guys - don't take it personal.

**Comment by sle-odoo** [comment]
@Yenthe666 the name change is to quickly get between which major version the saas release is. We kind of lost track with saas-18. We make saas releases every two months (kind of) from master and these versions are published on the saas service two months (kind of) later after testing and using the release on our instance. So we'll merge this feature soon, after reviewing and testing.

**Comment by blaggacao** [comment]
@lap-odoo I consider myself one of your hidden champions in your reference to "consultants". Although not directly on Odoo's payroll, I have learned to align interests as much as possible... 😉

**Comment by sle-odoo** [comment]
@blaggacao Hello, any comments on PR #22141? Slight refactoring of your work and an added test. Thanks in advance

**Pull request closed without merging**
