### PR TITLE
[FIX] Sale : clean ACL for acces to account 

### PR DESCRIPTION
**Pull request by fmdl**
Impacted version : master,11,10

Description of the issue/feature this PR addresses:
Some ACL are usefull. The issue is by the UI some model are blocked, but by xml_rpc the acces is possible.

This PR clean ACL for the module account (the most critical)

saleman has acces : 
- account.move.line. (and can download all the accounting).
- purchase invoice
- account.account

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
If you don't put any description, this will be hardly reviewed nor accepted.

**Comment by fmdl** [comment]
Don’t worry Pedro, when I will finish I will make the description.

I have put like that to perform the runbot test. 

Florent de Labarre

**Comment by pedrobaeza** [comment]
But you should know also that stability policy forbids this kind of changes in an already published version, so this won't be accepted.

**Comment by Yenthe666** [comment]
As Pedro mentioned this won't be accepted in a stable. It breaks the stable policy rules (and on a pretty big scale). Plus, you might want to add info and details from the start or prepare the PR local before adding it here.
Anyways I'll keep it open for an official statement, I'm quite sure it won't be accepted.

**Comment by mart-e** [comment]
Indeed, to change the security in stable, we need to have a clear bug and no other choice. If your patch is cleaning, it should target the master.
Also, please explain exactly what was blocking (and what is possible now).

**Pull request closed without merging**
