### PR TITLE
[FIX] sale_loyalty: discounts applied on reward lines

### PR DESCRIPTION
**Pull request by suker**
Introduced by 09f31597163a3251e58bb7b08939301574e1f65a

Steps to reproduce:
1. Activate user's permission **"Discount on line"**

2. Configure a pricelist with _discount_policy_ as **"Show public price & discount to the customer"** and set _selectable_ `True`.

3. Configure a price rule for a given product (e.g. Storage Box)

Storage box _Sales Price_ is set on 10$ and I set a price rule in 5$ so its like a 50% of discount in that product

4. Go to website shop + select configured pricelist + add to cart "Storage box" + Go to cart page

5. Apply a loyalty program (ie: discount code program type) configure as its reward's applicability on "Order".

6. Claim that discount code on cart page.

Reward product price is 1$ when it should be 2$

### CODE REVIEW

**Review by Pablocce — COMMENTED** [review]
LGTM! Great job finding that.

**Review by Demesmaeker — APPROVED** [review]
Hello

This makes sense to me, indeed. *(If you need to push again, you could maybe change L181 to also use the new variable `discounted_price_unit`, so that it's visually clear we use the same basis for both)*
@Feyensv as you worked on combined reward in 16d72eb8906a8713f7d70002e66b586c8a00e5da you are far more knowledgeable on the subject, can you make the final review? :pray:

**Review by Feyensv — APPROVED** [review]
@robodoo r+ squash

Thanks for the fix :+1:

**Comment by suker** [comment]
> Merge method set to squash.



> @robodoo r+ squash
> 
> Thanks for the fix 👍

Your welcome!

Thanks guys.

**Pull request closed without merging**
