### PR TITLE
[FIX] hr_expense: Markup no content helper

### PR DESCRIPTION
**Pull request by abz-odoo**
Steps:
 - Go to Expenses
 - Reporting/Expenses Analysis
 - List View
 - Remove every records
 - The no content help text is broken

To fix this we have to Markup the second part of the noContentHelp

opw-2862056

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

ping @odoo/rd-security could this be approved for security?

justification for new markup is: we return hard-coded Html that will be concatenated to other Markup html content, we still want to escape the mail alias so it is not included in markup

**Review by xmo-odoo — COMMENTED** [review]
Seems fine, though why not `Markup` the literal itself, why the extraction of an intermediate variable?

@robodoo override=ci/security

**Review by nle-odoo — APPROVED** [review]
robodoo delegate+

**Review by nle-odoo — COMMENTED** [review]
robodoo r+

**Pull request closed without merging**
