### PR TITLE
[FIX] sale: wrong date field since 0cc30bf

### PR DESCRIPTION
**Pull request by bouvyd**
Second occurrence after 1699be05. Hopefully the last.

### CODE REVIEW

**Comment by dbo-odoo** [comment]
@d-fence should fix the clickall

**Comment by d-fence** [comment]
Thanks @dbo-odoo

**Comment by dbo-odoo** [comment]
@d-fence looks okay when i test, i leave you do the r+ following your own testing

**Comment by d-fence** [comment]
My own test is ok too, probably the same small test as yours :-)
roboo r+

**Comment by d-fence** [comment]
oops whois roboo 
robodoo r+

**Comment by dbo-odoo** [comment]
@robodoo retry
my runbot was green damnit

**Comment by d-fence** [comment]
Non deterministic bug. @rco-odoo is working on a fix (Just in case, I have my own fix :smiling_imp: fix here: https://github.com/odoo/odoo/pull/36056)

**Pull request closed without merging**
