### PR TITLE
[FIX] account: Fix forward-port of ec25b9d01b27b33339d64c4833563c4f1c…

### PR DESCRIPTION
**Pull request by smetl**
…987dc8

For details, see:
https://github.com/odoo/odoo/commit/ec25b9d01b27b33339d64c4833563c4f1c987dc8

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by alt-odoo** [comment]
@KangOl  Can you merge this one and deploy it on server hosting the database 'dmacadar22-odoo' ?

Thanks !

**Comment by smetl** [comment]
@KangOl Since this PR has been merged, can you update the server hosting 'dmacadar22-odoo'  plz? Thanks :)

**Comment by alt-odoo** [comment]
@KangOl 
Done by @beledouxdenis  Thanks :)

**Pull request closed without merging**
