### PR TITLE
[MERGE] *: reduce shift in form view when switching mode

### PR DESCRIPTION
**Pull request by mcm-odoo**
Reduce shift in form view when switching mode
---

This PR reduces the shift between edit and readonly mode in the form view.
Reducing the shift means that both modes should be identical:
* Fields should be at the same place
* Fields have the same render in both modes
* Labels shouldn't show only in one mode, whether they appear in both or they does not

Task 2330101
Enterprise PR: https://github.com/odoo/enterprise/pull/15191

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo rebase-merge r+

**Comment by aab-odoo** [comment]
robodoo r-

**Comment by d-fence** [comment]
@robodoo r-

**Comment by seb-odoo** [comment]
Was this meant to be merged or not? Is the PR still relevant?

**Comment by mcm-odoo** [comment]
Hello @seb-odoo this PR is not relevant anymore, the commits was merged with that PR https://github.com/odoo/odoo/pull/60693
I close this one

**Pull request closed without merging**
