### PR TITLE
[IMP] l10n_in: update `l10n_in_code` in UOM

### PR DESCRIPTION
**Pull request by bat-odoo**
Purpose
=======
The Indian government updated its UOM code
https://einvoice1.gst.gov.in/Others/MasterCodes (select UQC Codes)

So In this commit, I have updated `l10n_in_code` in UOM Millimeter, Square Meter,
Litre, Cubic Meter, Yard, Square Foot, Cubic Inch and Cubic Foot.

PR: #93182

### CODE REVIEW

**Comment by vin-odoo** [comment]
If updating these is a legal requirement, or needed for edi's and such, it should be done at least in v14+

**Comment by bat-odoo** [comment]
@vin-odoo I have also created PRs for #93184 (13.0), #93186 (14.0) and #93183 (15.0).

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by bat-odoo** [comment]
@qdp-odoo Above 3 forward-port PRs waiting for action, can you merge that?

**Pull request closed without merging**
