### PR TITLE
[IMP] hr_attendance: review and simplify scss

### PR DESCRIPTION
**Pull request by stefanorigano**
Part of the overall v16 SCSS optimization/restyle, task-2704984.

task-2852148

enterprise:
- https://github.com/odoo/enterprise/pull/27333

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
@pparidans , ready for tech. review 👍 

cc. @adr-odoo

**Comment by stefanorigano** [comment]
Hello @kba-odoo 👋
could you have a look? Thanks!

@pparidans , JAR

**Review by kbapt — APPROVED** [review]
LGTM!

**Review by pparidans — CHANGES_REQUESTED** [review]
Looks good overall, but some remarks in mobile:
- as the layout has quite changed, I feel like a everything is a bit cramped to the top (cf. portrait mode) and/or is not consistent depending on the content (see before/after). Same for the "kiosk mode"
15970878-master-all runbot65 odoo com_web(Runbot Mobile)
15801773-master-all runbot64 odoo com_web(Runbot Mobile)
 
- the confirmation buttons have a weird `padding-top` on mobile (fine on desktop)
15801773-master-all runbot64 odoo com_web(Runbot Mobile) (1)

**Comment by stefanorigano** [comment]
@pparidans , thanks for your review.
Agreed, I'll fix these issues 👍

**Comment by pparidans** [comment]
@robodoo r+

**Comment by pparidans** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
