### PR TITLE
[MOD] Add my name i3 Rendszerház Kft.

### PR DESCRIPTION
**Pull request by nurefexc**
Add my name i3 Rendszerház Kft.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tsabi** [comment]
Please @odony merge my collegue's signature. Thanks!

**Comment by odony** [comment]
> Please @odony merge my collegue's signature. Thanks!

Sure, however the PR doesn't pass the CLA check, because there is a mismatch between the CLA signature and the actual email used in the commit. You can click on the "Details" link on the legal/cla check to view the error.
The commit was made with the "anonymized" github username (...@users.noreply.github.com) rather than the email used in the CLA signature, probably because it was done on the web UI.

There are 2 simple options to fix this:
- amend the commit locally with a properly configured github user email that matches the email used in the CLA signature (...@online-erp.hu), then force-push the branch
- alternatively, modify the CLA signature and add the "anonymized email" in it too. You can add multiple space-separated emails on each line

**Comment by nurefexc** [comment]
Fixed the email problem.
Please @odony merge my collegue's signature. Thanks!

**Comment by odony** [comment]
> Fixed the email problem.

Thanks, it's green now, but there are still a few issues, sorry ;-)

1. The last commit was done with the non-anonymized email, so if you can do that, you didn't need to add the anonymized one to the CLA file (..@users.noreply.github.com)
2. From what I can see the anonymized email you added to the CLA does not actually match the exact email assigned by github (in the first commit it was `65736397+nurefexc@users.noreply.github.com` and the part that matters is actually the number). But anyway, perhaps you don't even need it, cfr 1.
3. You need to squash the commits and force-push, so there is only 1 commit to merge
4. The commit message should be fixed to match our guidelines, ideally something like: `[CLA] Add signature for i3 Rendszerház Kft`

Thanks! :-)

**Pull request closed without merging**
