### PR TITLE
[FIX] res_lang: Fix decimal point and thousands separator for es_PE and es_CR

### PR DESCRIPTION
**Pull request by moylop260**
# Description of the issue/feature this PR addresses:

## `es_PE` official documentation:
 - http://www2.sunat.gob.pe/pdt/requerimientos.htm
   - `II) Configuración manual`
       - image

It means, decimal `.` and thousands `,`

## `es_CR` official documentation:
 - https://www.hacienda.go.cr/ATV/ComprobanteElectronico/docs/esquemas/2016/v4.3/ANEXOS%20Y%20ESTRUCTURAS_V4.3.pdf
   - `II. ESPECIFICACIONES TÉCNICAS Y FORMATO DE LOS COMPROBANTES ELECTRÓNICOS `
      - image

It means, decimal `.`

Even if I don't find a official documentation to justify thousands `,`
All our customers are using the following format `6,789.10`

For the position of the currency Colon it is `before`:
 - https://es.wikipedia.org/wiki/Col%C3%B3n_(moneda_de_Costa_Rica)
    - Screen Shot 2020-03-26 at 13 28 42

### CODE REVIEW

**Comment by crece365** [comment]
👍 In Perú it is used decimal . and thousands ,

**Comment by carlosrve** [comment]
Thank you @moylop260 for taking the time to do this PR!

I can attest that in Costa Rica, we use dot as decimal separator and comma as thousands separator. Also the correct symbol for colones is ₡ and it is used before the amount.

Thanks!

**Comment by moylop260** [comment]
@mart-e 
could you check it, please?

**Comment by mart-e** [comment]
Thanks, changed the commit message (the first part must the module name, not the model) and rebased !
Thank you all for the review
@robodoo r+

**Pull request closed without merging**
