### PR TITLE
[IMP] Make hotkey_service overlay modifier configurable

### PR DESCRIPTION
**Pull request by SplashS**
Description of the issue/feature this PR addresses:
To support certain hotkey overlay replacement in the `web_responsive` module with current implementation of hotkey_service we will have to override hotkey_service altogether. This doesn't seem like the correct way to extend odoo.
This PR makes hotkey_service patchable.
Also this PR introduce method `isAlted` what accumulates logic for determining hotkey overlay modifier. This logic was in 2 different methods of this service. It is the best case for patching this service in the future to replace overlay modifier from `Alt` to `Alt+Shift` in `web_responsive` v15.0.

Current behavior before PR:
There is no way to patch hotkey_service.
Prooflink why there is no way: https://stackoverflow.com/questions/59647878/how-to-monkey-patch-a-function-declared-inside-another-function

Desired behavior after PR is merged:
hotkey_service is patchable via "web.utils" patch method.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@ged-odoo @aab-odoo is it possible for you to check?

**Comment by FrancoisGe** [comment]
> Description of the issue/feature this PR addresses:
> To support certain hotkey overlay replacement in the `web_responsive` module with current implementation of hotkey_service we will have to override hotkey_service altogether. This doesn't seem like the correct way to extend odoo.
> This PR makes hotkey_service patchable.
> Also this PR introduce method `isAlted` what accumulates logic for determining hotkey overlay modifier. This logic was in 2 different methods of this service. It is the best case for patching this service in the future to replace overlay modifier from `Alt` to `Alt+Shift` in `web_responsive` v15.0.
> 
> Current behavior before PR:
> There is no way to patch hotkey_service.
> Prooflink why there is no way: https://stackoverflow.com/questions/59647878/how-to-monkey-patch-a-function-declared-inside-another-function
> 
> Desired behavior after PR is merged:
> hotkey_service is patchable via "web.utils" patch method.
> 
> --
> I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

Are you sure you want to replace 'Alt' with 'Alt-Shift' ? Since the new hotkeys service, it is possible to have a shortcut using Shit.
For example, you could have two different shortcuts Alt-Shift-A and Alt-A.
This would cause the loss of some shortcuts.

Could you please explain to me why you want to replace Alt with Alt-Shift ?

**Comment by pedrobaeza** [comment]
I can help with the question, as it was a decision made sometime ago in the OCA responsive module: Alt+accesskey was collapsing with a lot of system/OS shortcuts, so we decided to switch to Alt+Shit+accesskey for that. I conversations with one of you (don't remember if it was @seb-odoo or @aab-odoo), you told me that in the future the accelerator prefix is going to be configurable, but @SplashS, seeing that this is not happening, wants to make sure we will be able to hook into the mechanism.

I understand that you are expanding the hotkey mechanism for using both `Alt` and `Shift+Alt`, but it still collapses for the `Alt` combinations AFAIK.

Thanks anyways for answering so quick :smiley:

**Comment by SplashS** [comment]
> Could you please explain to me why you want to replace Alt with Alt-Shift ?

There are many reasons for this:
1. Chrome has some accesskey combinations reserved: Alt + E and Alt + D didn't work. Now with new data-hotkey mechanism fortunately it works! So this reason now is not really matter.
2. Firefox on Linux uses combinations Alt + 1,2,etc for switching to some Tab.
3. `web_responsive` module provides more intuitive combinations for some operations: Alt+Shift+E instead of Alt + A for edit record, Alt + Shift + D instead of Alt + J for discard editing. It uses Alt + Shift for it because of point 1.
4. `web_responsive` module provided Alt + Shift combination for overlays from version 12.0 so it is necessary for backward compatibility.

So there are 2 actual important reasons: switching tabs Firefox on Linux and backward compatibility.

> For example, you could have two different shortcuts Alt-Shift-A and Alt-A.

On current master Alt + Shift + Key doesn't work for overlays, only Alt + Key. But it can be fixed with two lines from my PR.

**Comment by ged-odoo** [comment]
@SplashS @pedrobaeza This is one of the first PR contributing to the new js framework :). I hope you enjoyed working with it.

I believe that reducing the need for patching stuff is good for the odoo javascript ecosystem. This will make it easier to migrate/maintain. With the new framework, I am trying to avoid exposing too much of the internals, so we can modify our own internal code without fear of breaking anything. So, before exposing anything, I try to find a way to make our code more generic. In this case, I didn't find a nice way to make it configurable, so  I propose to only expose the `isAlted` function.  What do you think about this?

**Comment by SplashS** [comment]
> I am trying to avoid exposing too much of the internals, so we can modify our own internal code without fear of breaking anything.

Ok. I've catch it. So I will upgrade this PR to expose only `isAlted` method that `web_responsive` actually need. HotkeyService provides really simple and cool interface with only `add` method, but to override key modifier that shows shortcut overlays it is not enough.

> I hope you enjoyed working with it.

It's really more intuitive than Widget system. But there is lack of information and samples. Community codebase contains not so many cases of patching or extending JavaScript part of Odoo (comparing to qweb or models). So the good collection of examples is still debug=assets on enterprise runbot :)

**Comment by SplashS** [comment]
@ged-odoo `isAlted` method is used in two different logics:
1. It manages displaying of hotkey overlays.
2. In pair with options.altIsOptional manages alternativity for `Alt+Key` and `Key` shortcuts.

For `web_responsive` we need to expose only first logic case.
In this upgraded PR I propose more intuitive configuration option `overlayModifier: "alt"`.

Current interface for hotkeyService stays unchanged and in `web_responsive` we can do our patch with one line:
`hotkeyService.overlayModifier = "alt+shift";`

I would appreciate feedback.

**Comment by SplashS** [comment]
Missed MacOS overlay modifier difference.
Now configuration option looks like: `overlayModifier: () => isMacOS() ? "alt+control" : "alt".`

**Comment by SplashS** [comment]
Since https://github.com/odoo/odoo/commit/7f10ca0d7c58918ae2fe60988ed40a3eee1dd037 overlayModifier is customizable.
This PR is outdated. Closing it.

**Pull request closed without merging**
