### PR TITLE
[IMP] payment: Make inheritable code to get allowed acquirers by user

### PR DESCRIPTION
**Pull request by luisg123v**
Current approach is:
- In case it's a public user, show only acquirers with flow
  "Redirection to the acquirer website"
- In case it's not a public user, show also the flow "Payment from Odoo"

The above may not be the case for all acquirers and there may be custom flows, so that
that code is made inheritable, so custom payment acquirers may change that behavior.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by luisg123v** [comment]
@moylop260 could you review, please?

CC @fernandahf

**Review by moylop260 — APPROVED** [review]
@tbe-odoo @nim-odoo @mart-e 

What do you think?

**Comment by moylop260** [comment]
@nim-odoo @mart-e 

what do you think?

**Comment by AntoineVDV** [comment]
Hello, @luisg123v could you give an example of such a custom flow that allows the public user to make S2S payments without token?

**Comment by luisg123v** [comment]
Hi @AntoineVDV,

We're working on an acquirer that allows internal users to register tokens on behalf of customers. We managed to make the partner to don't get overwriten, but now the acquirer is not bein shown. That's why it would be helpful this was inheritable.

**Comment by moylop260** [comment]
We have the following case of use:
1. The customer calls us on the phone and tells us what products he likes to buy
2. The user select the products and request the payment card info
3. The user needs to pay the sale behalf of the customer since that the payment card info is not of the user but customer

So, we have added the following button in the backend using a custom module in order to request the payment info and follow the normal odoo flow:
 - Screen Shot 2021-07-26 at 19 01 47

We don't want you to support this case but be able to inherit the method

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
Ok, I see. Indeed, we don't want to support this use case in standard but I don't see a problem with adding a small hook. Note that this change will *not* be forward-ported since the `payment` module was heavily refactored in 14.3.

However, there is a problem with the hook as it is now: It adds a "filter method" on `payment.acquirer` but only the `payment` module is making use of it, while many other modules should rely on that method if it is added. Instead, I suggest extracting the method in `payment/controllers/portal.py` only and override it in the custom acquirer module. Also, the returned value of the method should be a recordset if it is added to the model's class.

```py
@staticmethod
def _get_acquirers_compatible_with_current_user(acquirers):
    # s2s mode will always generate a token, which we don't want for public users
    valid_flows = ['form'] if request.env.user._is_public() else ['form', 's2s']
    return [acq for acq in acquirers if acq.payment_flow in valid_flows]
```

**Comment by AntoineVDV** [comment]
@fw-bot ignore

**Comment by luisg123v** [comment]
@AntoineVDV thanks for the suggestion, I've applied it.

Could you review again, please?

**Review by AntoineVDV — APPROVED** [review]
LGTM!

@robodoo r+

**Pull request closed without merging**
