### PR TITLE
[FIX] hr_fleet: switch cars from employee's partner to user's partner

### PR DESCRIPTION
**Pull request by pimodoo**
When we link a user on an existing employee, we look at the vehicle linked to the existing employee's partner, to re-assign it to the linked user's partner that will become the new work_contact_id.

The main issues are the following:
- When we create an employee and assign a user on it, it will set the user's partner on all vehicle without driver or futur driver
- When we select the user in the form, it will save the changes on the car, even if the form is not saved, because the function is called in an onchange.

Side issue:
- Whatever is the company of the employee, it'll search through all vehicles if you have activated multiple companies.

Bugs introduced in https://github.com/odoo/odoo/pull/157057

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pimodoo** [comment]
@sofiagvaladze Hello, we had small issue this morning, an employee has been assigned on all cars without driver/future drivers.

Can you check this fix please?

**Comment by adwid** [comment]
robodoo delegate=@thle-odoo

**Review by thle-odoo — APPROVED** [review]
Keeping this logic in the `_sync_user` method is complicated.
We have to be careful not to work on the "real" records during an `onchange`.
We have to take into account the `future_driver_id` field in the condition, which makes using the `car_ids` field unusable for this use case.

In addtion, this logic is not necessary during the creation of an employee.
In fact, the case where the employee has no work contact is useless.

Therefore, I agree with the fix.

**Comment by pimodoo** [comment]
@robodoo r+

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Comment by d-fence** [comment]
robodoo rebase-ff

**Pull request closed without merging**
