### PR TITLE
Fix state name typo

### PR DESCRIPTION
**Pull request by r-sierra**
Change Chobut for [Chubut](https://es.wikipedia.org/wiki/Provincia_del_Chubut)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e for your interest.

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `r-sierra@users.noreply.github.com`
- you are signing _for_ the address `b...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+ rebase-ff

**Comment by r-sierra** [comment]
@mart-e thanks for your help!

**Pull request closed without merging**
