### PR TITLE
[IMP] multiprint.js: allow more complex URL schemes

### PR DESCRIPTION
**Pull request by nilshamerlinck**
Improve multiprint.js to allow more complex URL schemes for printers

### CODE REVIEW

**Comment by jorenvo** [comment]
Hi,

Could you tell what issue you are trying to solve? Could you give me some examples of what you mean by complex URL schemes that aren't supported now?


Kind regards,
Joren

**Comment by nilshamerlinck** [comment]
Hi Joren,

https://192.168.1.12:443 for example

**Comment by jorenvo** [comment]
Alright, great. I think that would be something worth supporting. I don't think your code works for https://abc.def though. It should add the port in that case.

**Comment by nilshamerlinck** [comment]
@jorenvo Any remaining blocking point?

**Comment by jorenvo** [comment]
Don't worry, I haven't forgotten about this. Although this would work, I've been thinking that we might as well support it for the normal posbox as well then. Because with this patch you'd be able to to define restaurant printers with a custom port, but the regular posbox (with the receipt printer, barcode scanner, ...) is still hardcoded to use 8069. And I don't like that inconsistency. So I think we should add a function to the point_of_sale module that transforms a url the way your patch does. That way we can use it for the regular posbox and we can also use it for restaurant printers.

**Comment by antonylesuisse** [comment]
We could store the full url instead of just the ip on pos.config

**Comment by jorenvo** [comment]
I'm closing this for now. If we do add this in the future it will be added to master. If this behavior is something you want in 9.0, you can write a small custom module for that. You can look at the `pos_restaurant` module for an example of how best to add JS to the POS.

**Pull request closed without merging**
