### PR TITLE
[IMP] hr_recruitment: fix typo's and improve source terms

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Fix some typo's/improve terms

Current behavior before PR: There are some weird sentences and a typo in the email templates.

Desired behavior after PR is merged: Better sentences and no more typo.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e could you get this in before V13? :)

**Comment by mreficent** [comment]
point to saas12.5

**Comment by mart-e** [comment]
As @mreficent said, if you want it for 13.0, it should be in saas-12.5 and please update the .pot file too

**Comment by Yenthe666** [comment]
Done!

**Comment by mart-e** [comment]
Thanks, rebased for failing test.
@robodoo r+

**Comment by Yenthe666** [comment]
Thank you again :)

**Pull request closed without merging**
