### PR TITLE
[FIX] purchase: analytic account clears

### PR DESCRIPTION
**Pull request by ande-odoo**
To reproduce the issue:
1. In Accounting, settings, activate Analytic Accounting
2. Head over to the purchase module, create an RFQ
3. Add a POL to the RFQ, with an analytic account specified
4. Save the RFQ
5. Edit the RFQ, and change the Order Deadline
6. The analytic account in the POL has disappeared

Error: The analytic account should not disappear

When modifying the deadline, the analytic account was always being replaced, even if the replacement was empty.

In the same version (14.0), the same fix can be found in AML: https://github.com/odoo/odoo/blob/1dcd071b27779e7d6d8f536c7dce7002d27212ba/addons/account/models/account_move.py#L3583-L3584

In 16.0, the issue doesn't need to be fixed, as it has already been fixed, by a similar fix, as seen in POL:
https://github.com/odoo/odoo/blob/c677f45dcb050ce7e6f755b71e56c9b9120bf613/addons/purchase/models/purchase.py#L1153

OPW-3159905

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ande-odoo** [comment]
fw-bot up to saas-15.2

**Review by yosa-odoo — COMMENTED** [review]
Thanks for the PR :)

It is mostly a functional issue, maybe you could check with the PO

(for this kind of situations, a test is always welcome!)

The fix will change the following situations:
```
[CONFIG]
Two products: Product A and Product B

Default analytic rule: 
        - Analytic Account (AA) `default account` 
	- on product A
	- for this month

(1) Line set with product A; manual AA "new account":

	case 2: change line product to product B:
		Before Fix: AA "new Account" is unset
		After Fix: "new account" is still the AA

(3) Line set with product B; manual AA "new account" is set:

	case 1: change order date for tomorrow: -> Issue described by the commit
		Before Fix: AA "new Account" is unset
		After Fix: AA "new account" is still set

	case 3: change line product to product B:
		Before Fix: AA "new account" is unset
		After Fix: AA "new account" is still set	

(4) Line set with product A; automatic "default account" AA is set:

	case 3: change line product to product B:
		Before Fix: no AA is set
		After Fix: "default account" AA is still set		
```



<details>
  <summary>Detail Situations</summary>

 ```

(1) Line set with product A; manual AA "new account":

	case 1: change order date for tomorrow:
		Before Fix: "new account" is overriden by "default account"
		After Fix: No change

	case 2: change line product to product B:
		Before Fix: No AA is set
		After Fix: "new account" is still the AA

	case 3: change line product to product A:
		Before Fix:"new account" is overriden by "default account"
		After Fix: No change

(2) Line set with product A; delete the AA:

	case 1: change order date for tomorrow:
		Before Fix: AA "default account" is set 
		After Fix: No change

	case 2: change line product to product B:
		Before Fix: No AA is set
		After Fix: No change

	case 3: change line product to product A:
		Before Fix: AA "default account" is set
		After Fix: No change

(3) Line set with product B; manual AA "new account" is set:

	case 1: change order date for tomorrow:
		Before Fix: AA "new Account" is unset
		After Fix: AA "new account" is still set

	case 2: change line product to product A:
		Before Fix: AA "Default Account" is set
		After Fix: No change

	case 3: change line product to product B:
		Before Fix: AA "new account" is unset
		After Fix: AA "new account" is still set

(4) Line set with product A; automatic "default account" AA is set:

	case 1: change order date for tomorrow:
		Before Fix: "default account" AA is still set
		After Fix: No change

	case 2: change line product to product A:
		Before Fix: "default account" AA is still set
		After Fix: No change

	case 3: change line product to product B:
		Before Fix: no AA is set
		After Fix: "default account" AA is still set	
```		
</details>

**Review by adwid — APPROVED** [review]
Despite Yolann's comment (with which I agree), lgtm

The diff make the purchase's behavior consistent with accounting one's: 
https://github.com/odoo/odoo/blob/1dcd071b27779e7d6d8f536c7dce7002d27212ba/addons/account/models/account_move.py#L3571-L3584

Moreover, it also makes it consistent with behavior in 16.0:
https://github.com/odoo/odoo/blob/c677f45dcb050ce7e6f755b71e56c9b9120bf613/addons/purchase/models/purchase.py#L1142-L1153

So, either we apply this diff, or we have to change all these methods.

**Comment by adwid** [comment]
robodoo r+

**Pull request closed without merging**
