### PR TITLE
Master remove com yti

### PR DESCRIPTION
**Pull request by tivisse**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by mart-e — APPROVED** [review]
Error while formatting the error, classic...

**Comment by xmo-odoo** [comment]
@mart-e looks like the "translate" error [was introduced a while ago](https://github.com/odoo-dev/odoo/commit/95ed21795d1618c0144f50d5265cee6c21c332d4#diff-9f9f8f7fdb4edf151cf1ba03efc0e5dd7ea6857d431d5a6f80fe769977ac7161R944), wouldn't it be a good idea to move it out of this PR and fix it in 14.0?

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
