### PR TITLE
[FIX] base: Change state_id DIF to CMX for Mexico City

### PR DESCRIPTION
**Pull request by lade-odoo**
There has been a change in the code for the state_id for Mexico City. Since the beginning of 2022, the new code is CMX instead of DIF.

opw-2801208

### CODE REVIEW

**Comment by MiniLau** [comment]
@jco-odoo can you review this ?

**Comment by MiniLau** [comment]
@jco-odoo, you can check in the official doc: https://www.iso.org/obp/ui/#iso:code:3166:MX (we see "Ciudad de México" is now MX-CMX).

**Comment by vbe-odoo** [comment]
Hi @jco-odoo this LGTM.
Here are some other legal references:
1. http://omawww.sat.gob.mx/tramitesyservicios/Paginas/anexo_20_version3-3.htm
2. http://omawww.sat.gob.mx/tramitesyservicios/Paginas/catalogos_emision_cfdi_complemento_ce.htm

And also here's a dataset that @fvz-odoo added into the internal task: http://omawww.sat.gob.mx/tramitesyservicios/Paginas/catalogos_emision_cfdi_complemento_ce.htm

opw-id: 2788728

Thanks for the PR!
cc' @ren-odoo @MiniLau

**Comment by jco-odoo** [comment]
@vbe-odoo Should not this be tested?  (or was this tested on an existing db?)

**Comment by vbe-odoo** [comment]
@jco-odoo both, I tested this PR and also tested on an existing DB).
In both cases is working OK.
I don't know if @fvz-odoo wants to make a double-check. But from my side LGTM.

Cheers!
cc' @ren-odoo

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
