### PR TITLE
[15.0][FIX] event: badge report dates in event's tz

### PR DESCRIPTION
**Pull request by ivantodorovich**
**Steps to reproduce:**

1. Create an event with a remote TZ (e.g: 'Japan').
2. Create and confirm an attendee for this event.
3. Check the registration confirmation email and report.

image
image

**Current behaviour:**

* The dates in the email are in the event's tz.
* The dates in the report are in the user's tz.

image
image

**Expected behaviour:**

* Both dates should be consistent and be in the event's tz.

image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ivantodorovich** [comment]
ping @tde-banana-odoo

**Review by petrus-v — APPROVED** [review]

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for the PR. As we target stable, we try to have a minimal diff ... I see you reorganized some attributes (new lines, ...) making difficult to see the actual diff. Could you try to have a version that changes as few as possible the original code ? That way it is easier to see it everything is ok with stable policy, ... 

Cheers !

**Comment by ivantodorovich** [comment]
Hello @tde-banana-odoo 

Sorry for taking so long to reply.

I've split the commits in two: one containing only the fix with minimal diff, and a second one that improves code readability
I can remove the second one if you prefer.

About the fix: to summarize, it accomplish two things:

- Use `t-field` over `t-esc`
- To render the date, use a datetime with formatting instead of `.date()`, as the latter would ignore timezones.

**Comment by jeh-odoo** [comment]
Hello @ivantodorovich 

Sorry for the delay.
Got a look and the changes look good to me.

To respect the guidelines it would be better to get rid of the readability commit.
Indeed when targeting a stable version we don't allow code cleaning or cosmetic changes and try to keep the diff as minimal as possible.

Cheers!

**Comment by ivantodorovich** [comment]
Understood @jeh-odoo 
Thanks a lot for the reviews and patience :)

I've removed the readability commit, should be good now

**Review by gregory-moka — APPROVED** [review]

**Comment by ivantodorovich** [comment]
gentle ping @jeh-odoo

**Comment by ivantodorovich** [comment]
Hey @tde-banana-odoo , @jeh-odoo 

Is there something I can do on my side to speed this up?
Is the bug description clear for you? is the issue easy to understand?

Please let me know 🙏🏻

**Review by jeh-odoo — APPROVED** [review]

**Comment by tde-banana-odoo** [comment]
Hello,

We will try to speedup the internal testing so that we can close it :) 

Cheers !

**Comment by ivantodorovich** [comment]
Yay, thanks! 🎉

**Pull request closed without merging**
