### PR TITLE
[FIX] l10n_at: specific tax scopes and ec sales tax report tags

### PR DESCRIPTION
**Pull request by wtaferner**
Improving tax scopes and EC sales tax report tags for `l10n_at`

Old PR: odoo/odoo#171606
Info: @wt-io-it

Ticket link: https://www.odoo.com/odoo/project.task/3916300
opw-3916300

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@agr-odoo 
This should do what you intended to do in the other PR. Let me know what you think and if I am missing something.

**Comment by lordkrandel** [comment]
@agr-odoo @wtaferner 

I'm asking the PO @Olivier-olma to have a functional check about this.

**Comment by wtaferner** [comment]
@lordkrandel 
Jep, just as a side note. 

- Issue: Invoice is not reported in tax amount

There is nothing to report in the normal local tax report, but now it is listed as I added the base amounts of the so called "`Zusammenfassende Meldung`" above in the tax report (for having everything in one spot and in an localization overview) which do also have the base amount of `IGL` which has to be reported indeed in the local tax report (`U30`/`U1`), but is already properly configured. So, it is basically all about the EC Sales Report in this PR IMO.

**Comment by agr-odoo** [comment]
@wtaferner 
Thanks for the PR and for the clarifications
It seems there was a misunderstanding from my side, I thought that services Sales with tax `UST_EU Dienstleistung (Sonstige Leistungen) 0%` should be reported in the domestic Tax Report

**Comment by wtaferner** [comment]
@tsb-odoo 
May I ask you to take a look as it was put on your shoulders to review functionally. I know it is what it is needed, but I guess the others need your review to merge.

**Comment by wtaferner** [comment]
@lordkrandel 
May I ask you to assign someone who can "review" and merge this? I think @tsb-odoo will not take a look until 2025 and this is not acceptable and not even needed IMO.

**Pull request closed without merging**
