### PR TITLE
[FIX] web_editor: block only the form's buttons

### PR DESCRIPTION
**Pull request by kebeclibre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
@alexkuhn 
I tried what you did in 11.0 with deferred, but in 10.0 in doesn't seem to work that way, what do you think about this one ?

**Comment by smurf-U** [comment]
image

**Issue commit while create or edit `Mailing Lists` using Many2one field**

**Because :-**
`this.$formButtons = this.getParent().$buttons;`
[https://github.com/odoo/odoo/blame/10.0/addons/web_editor/static/src/js/backend.js#L302](url)
Give `undefined`  in `this.$formButtons`

**Comment by kebeclibre** [comment]
@smurf-U 
Can you be more precise, like describing the flow ?
Like with a video...

**Comment by smurf-U** [comment]
First give access `Use subscription pop up on the website` group to user


nimbus-record-video-2018-04-26-14-15-48

**Pull request merged**
