### PR TITLE
[FIX] bad states in decoration-info of purchase.order tree view

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial patch.

Set correct ``decoration-info`` attribute on ``purchase.order`` tree view, replacing unexisting states ``('wait','confirmed')`` by existing ones ``('draft','sent')``

See list of valid states : https://github.com/odoo/odoo/blob/master/addons/purchase/models/purchase.py#L97

Note : this bug is present since at least V12.0

CC : @Yenthe666, @quentindupont

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by quentinDupont — APPROVED** [review]

**Review by PierrickBrun — APPROVED** [review]

**Review by houssine78 — APPROVED** [review]

**Comment by amoyaux** [comment]
Okay, can you please rewrite the commut message following the guidelines https://www.odoo.com/documentation/14.0/reference/guidelines.html#git

**Comment by legalsylvain** [comment]
Hi @amoyaux. Thanks for your review and your answer. 

- I rewrote the short sentence, adding the module name.
- I didn't added references at the end of the message, because there are no related bug / task / opw related. (AFAIK)

Let me know if it's OK.

One question : 

The bug is present since many versions. (present at least in V12). What is the best for odoo team ? do a PR against 12.0 branch ? master branch ? all the branches ? I don't understand how robodoo works, to find the branches into merge the PR.

kind regards.

**Comment by amoyaux** [comment]
@legalsylvain Don't worry for the references, not needed in your case. 

For your question, it depends, when you create a PR for a specific version, we have an automated tools call forward-port bot that will try apply the fix for all the version between the PR branch up to master. https://github.com/odoo/odoo/wiki/Mergebot#forward-port

For example if you do a PR in 12.0, the bot will create a PR for branch:
saas-12.3 -> 13.0 -> saas-13.3 -> 14.0 -> saas-14.3 -> master
If you do the PR in 14.0:
saas-14.3 -> master
For master there will be no forward port since you are already on the latest version

Usually, we prefer that people propose the fix on the version they need it rather than bellow because we are never safe from a bug and if other people need it, they can always suggest a back port.

**Comment by amoyaux** [comment]
@legalsylvain What do you think of moving it on the name instead of the complete line. It's a big less aggressive.

image
image

**Comment by legalsylvain** [comment]
> @legalsylvain What do you think of moving it on the name instead of the complete line. It's a big less aggressive.

Hi @amoyaux. 

I'm currently working on 12.0 and proposed that PR only to avoid to have a new patch, after the next migration ;-)

- In V12, it seems that the "standard" is to to have the full line in a given color
- In more recent version (I don't use for the time being), indeed, odoo introduced color per column (for exemple, on [sale](https://github.com/odoo/odoo/blob/master/addons/sale/views/sale_views.xml#L239) module)

At the moment, I don't see your proposal consistent with the current ``decoration-muted="state=='cancel'"`` present in the line level. 
The scope of this PR is just a bug fix, because the current decoration-info is related to unexisting state.
Maybe we could merge this bug fix, and then think about deeper changes on purchase tree view in another task.

Don't you think ?

**Review by rvalyi — APPROVED** [review]

**Comment by amoyaux** [comment]
Hello,

Since the PR is for master and the decoration exists for one field instead of the line, I would use it. Maybe it's not consistent with cancel but decoration-muted is less visible and often filter out of views by default.

**Comment by amoyaux** [comment]
@legalsylvain Yep, good that way. Thanks for the contribution.

robodoo r+

**Comment by legalsylvain** [comment]
Hi @amoyaux. Thanks for your reactivity, and for merging this PR. 
If purchase module is in your scope, could you take a look on this other PR ? 
https://github.com/odoo/odoo/pull/70462 

I am available to discuss if needed.

**Pull request closed without merging**
