### PR TITLE
FIX: no read all records, poor performance on big database

### PR DESCRIPTION
**Pull request by celm1990**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by celm1990** [comment]
CC @zaoral

**Comment by zaoral** [comment]
+1 :clap: 

Hi @jco-odoo  I think this is a good improve for peformance.
Please review if we can merge it.

Best Regards

cc @jjscarafia

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by celm1990** [comment]
thanks, can us review other PR #39218  with a error at create receipts

**Pull request closed without merging**
