### PR TITLE
[FIX] payment: float consistency enforcement in access_token generation

### PR DESCRIPTION
**Pull request by jhk-odoo**
Steps to reproduce:
- install sales, ecommerce and payment_authorize
- setup authorize.net (test mode)
- go to sales and select the quotation S00007 (demo data) or create a quotation
with multiple items that add up to a float
- select action > generate a payment link > go to the link > select pay with authorize
- you are redirected to authorize.net use 4111 1111 1111 1111 as card number and 1223
as expiration date > pay
- you are redirected to the odoo payment process page
- wait for the result

Previous behavior:
the user is returned to a 404 error page but the payment went trough

Current behavior:
access_token generation is consistent and will not fail because of
float representation
the user is returned to the "payment confirmed" page

WARNINGS:
- watching the values in vscode prevents bug reproduction
- when setting up authorize.net, do not forget to add your test url to
the account's allowed return urls
- use https for authorize.net connection

opw-2223135

### CODE REVIEW

**Comment by jhk-odoo** [comment]
@nle-odoo

**Comment by jhk-odoo** [comment]
why would 17.00 trigger an error if it is used to generate a token (since it is used on both sides)?

**Comment by nle-odoo** [comment]
I just mean, if at one side it is `17.0` then at the other side (because we updated the instance inbetween) it's `17.00`

**Comment by jhk-odoo** [comment]
ah right, it would be non-blocking (payment still goes trough)
robodoo r+

**Pull request closed without merging**
