### PR TITLE
14.0 check demo wan

### PR DESCRIPTION
**Pull request by william-andre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@william-andre I don't think we always a company for every CoA.  For every country, yes.

**Comment by william-andre** [comment]
@jco-odoo I tested locally with AR and DE as these are a bit more exotic but we can launch a full l10n build on this branch before merging if you want

**Comment by william-andre** [comment]
@jco-odoo up?
Or should I drop this?

**Comment by jco-odoo** [comment]
@william-andre Demo data for l10n_at is there.  It seems still a nice way to see if every chart template's country has a demo company at least...  (but I think people will mostly not forget about doing one)

**Comment by william-andre** [comment]
> but I think people will mostly not forget about doing one

We did multiple times already, even if some got fixed

**Comment by william-andre** [comment]
> but I think people will mostly not forget about doing one
 
We did multiple times already, even if some got fixed

 > Demo data for l10n_at is there

Not in 14.0 at least

**Comment by antoine162** [comment]
Hi @william-andre thanks so much for coming up with this, @jco-odoo says to close this as people won't forget to add demo companies if locs are reviewed :smile:

**Comment by william-andre** [comment]
> people won't forget to add demo companies if locs are reviewed smile

It's not like I had to had 4 demo companies last week? :roll_eyes: (I did)

**Pull request closed without merging**
