### PR TITLE
[FIX] stock: correctly translate route name

### PR DESCRIPTION
**Pull request by mart-e**
Translating a variable does not work, the call must be translated

### CODE REVIEW

**Comment by mart-e** [comment]
@robodoo do your thing ! r+

**Comment by xmo-odoo** [comment]
???

Staging was cancelled, with the note "PR 28099 was updated by robodoo"???

**Comment by xmo-odoo** [comment]
But it's @mart-e who updated the PR!

**Comment by mart-e** [comment]
> But it's @mart-e who updated the PR!

No I did not. I only pushed once, with bdd258e2433f5e5dabb8b772f62d4e8db36e4f95

**Comment by xmo-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
