### PR TITLE
[FIX] core: don't crash on manual_field

### PR DESCRIPTION
**Pull request by aj-fuentes**
Manual backport of #42011 see also #41407

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by KangOl** [comment]
@fw-bot ignore

**Comment by beledouxdenis** [comment]
@odony @rco-odoo 
Do you think it would be acceptable to merge this in no longer supported 10.0? This is a backport of an existing fix in Odoo 11.0.

This would solve a dozens upgrade requests that would normally require a specific upgrade script without this fix.
The goal to drop the support on old odoo versions is so we don't have to make bug fixes in too many versions in parallel and to encourage / force users to upgrade to newer version.

However, the goal of this revision is to allow users to actually upgrade more easily, so to me this is acceptable. Besides the fix is not really risky, as it already exist in Odoo 11.0.

The added value/risk ratio is pretty good, as it allows more database to upgrade without manual intervention, and the risk is pretty minimal.

**Comment by odony** [comment]
> The added value/risk ratio is pretty good, as it allows more database to upgrade without manual intervention, and the risk is pretty minimal.

Sounds ok to me, if the patch is considered safe enough by @rco-odoo :+1:

**Comment by aj-fuentes** [comment]
@rco-odoo Could you check this PR please? Thanks.

**Review by rco-odoo — APPROVED** [review]
@robodoo r+

**Comment by KangOl** [comment]
It seems that robodoo ignore commands in review messages
@robodoo r+

**Comment by KangOl** [comment]
Actually, he's not. He just doesn't care about version 10.

**Comment by aj-fuentes** [comment]
Do we need to merge it manually?

**Pull request merged**
