### PR TITLE
[FIX] website: replace notification.notify

### PR DESCRIPTION
**Pull request by juliusc2066**
This commit replaces notification.notify with notification.add so that
it works without the legacy notification service.

Steps to reproduce:
- go to website settings
- add a new website with any name
- follow the steps and upload an invalid file as the logo

fix for https://github.com/odoo/odoo/commit/caefcb8590301a0ebbe947a875003b33ce7d537a

task-3338012

### CODE REVIEW

**Comment by rdeodoo** [comment]
To have a better understanding, when was this broken? Was it a refactoring in 16.3 of the notification which forgot to adapt this code?

**Comment by juliusc2066** [comment]
It comes from way before: https://github.com/odoo/odoo/pull/89223/commits/caefcb8590301a0ebbe947a875003b33ce7d537a so i will retarget to 16.0

**Comment by rdeodoo** [comment]
Great :+1: 
- Make sure to retarget this PR, don't create a new one
- It's task-xxx, not opw-xxx, opw is for our client bugfix
- Always blame commit when fixing something, a fix can't be written without that, as you can't fix something without understanding fully how and when it was broken. And always add/mention the "problematic" commit in your commit message. It's always really important for 2 more reasons:
  - Reviewers: they will have to do it themselves otherwise, you can't review a fix without having the full history of why it broke
  - Fixers: your code will have to be fix later, at which point the cycle loops again -> Fix + Review -> Need history/blame

**Comment by mcm-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
