### PR TITLE
[FIX] mail: send message in chatter should respect user/customer language

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
* STEP TO REPRODUCE: user 1 use English, user 2 use Vietnamese -> Go to any record like a Partner record, add follow for both user 1 and user 2 -> Send message in English environment -> Go to mail box of user 1, mail body and button url display English which is correct but mail body and button url in mail box of user 2 are also display in English which is not
correct while it should be in Vietnamese
* REASON: the system currently always use language in self.env.context
* SOLUTION: use language of partner instead

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Hello @tde-banana-odoo can you have a feedback on this, if this really a bug then can i make a fix here in v15 ?

**Comment by tde-banana-odoo** [comment]
It is a limitation of old versions ... it has been improved notably for 16 or 17. We won't fix in 15 anyway as its EOL is coming and it is not critical.

**Comment by duong77476-viindoo** [comment]
> It is a limitation of old versions ... it has been improved notably for 16 or 17. We won't fix in 15 anyway as its EOL is coming and it is not critical.

I can confirm it is meet my demand in v17 not in v16 (v16 still has issue like this pr), so i'll close this pr. Thanks Mr Banana

**Comment by duong77476-viindoo** [comment]
> It is a limitation of old versions ... it has been improved notably for 16 or 17. We won't fix in 15 anyway as its EOL is coming and it is not critical.

@tde-banana-odoo
I have an idea about improvement, currently when send message (email) via chatter to many user (include portal user as well), odoo 17 already classify by lang in user type which is really good, but we should append to mail_body the `carbon copy` to let user know this email is also send to other peopel. I've tried to do it but the list of `carbon copy` is always duplicate with user who receive email because odoo is sending mail in group (1 mail body per group recipient). Hope you understand what i trying to say.
Thanks in advance

**Pull request closed without merging**
