### PR TITLE
13.0 explode batch whe

### PR DESCRIPTION
**Pull request by Whenrow**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Whenrow** [comment]
**Test case** 
Confirm a picking made of 50 stock moves. Each move has a kit of 10 elements (so 500 moves to confirm)
Before the patch : _8.7_ sec
After the patch : _4.2_ sec

**Comment by Whenrow** [comment]
[flamegraphs.zip](https://github.com/odoo/odoo/files/4139627/flamegraphs.zip)

**Comment by Whenrow** [comment]
@nim-odoo It would be nice to have your approval on this. Thanks

**Comment by nim-odoo** [comment]
> Before the patch : _8.7_ sec
> After the patch : _4.2_ sec

Well, that's not really impressive :smiley: 

Sure, it's always better to have it work in batch, but a factor 2 is not going to change the game that much. Maybe it would be nice to cache `_bom_find` somehow, although that would impact only if you receive the same product. Note sure that would make sense in that context.

**Comment by sle-odoo** [comment]
@nim-odoo we also plan to improve _bom_find, you can have a look at task 2191356

> but a factor 2 is not going to change the game that much

i agree but applying this patch made more visible another performance bottleneck leading to PR #44660, this one finally solving the performance degradation on the specific server we followed for a week. it's worth it in my opinion.

**Comment by nim-odoo** [comment]
I'm ok with the patch, no worry. It's just that usually a factor of 2 is not that great since it only takes twice the lines to face the same performance. My point was that there is probably some more work to do on this use case.

**Comment by sle-odoo** [comment]
robodoo + rebase-ff

**Comment by sle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
