### PR TITLE
[FIX] account_edi: also lock account_move for sending

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by william-andre — APPROVED** [review]
Please link https://github.com/odoo/odoo/commit/cc67b5ac9514e7e139c3e0263728dcf8e9f8a7d8 in the commit message as the fix had been done before.

Also link https://github.com/odoo/odoo/commit/5319b71b66499be2abb79b5f337530e229193534, it doesn't explain why the filtering on the state was added there. It looks like a rebase issue (very similar commit dates)

And give some insight about how you detected this error (opw?), how to reproduce, something.
Future readers will thank you :)

**Comment by jco-odoo** [comment]
@william-andre I did some basic tests with PE and MX and it behaves nicely, so this can be r+

**Comment by william-andre** [comment]
There is a typo in the second hash now, you inserted `5319b71b66499be2abb79b5f337530e229193534` without erasing `5319b71`

**Comment by jco-odoo** [comment]
@william-andre commit msg updated

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
