### PR TITLE
7.0 [FIX] This fixes #2854 always round floor in _product_reserve

### LINKED ISSUE #2854: Float rounding problem in _product_reserve when selling a product in a different UOM
Selling a product in a different UOM than the one defined on the product doesn't work at all.

steps to reproduce (runbot 7.0):
-create a new unit of measure (pack8) in category unit with rounding 1 and ratio 8 (bigger)
-check rounding of unit is 1
-on a stockable product (ex Computer Case), in the inventory tab, update stock quantity to get 15 units in stock (the product must be configured in the 'information' tab with 'unit of mesure' set to 'Unit')
- create a SO for 2 pack8 of this product -> the system doesn't complain!
- confirm the SO -> in the inventory tab you have -16 in the outgoing quantity
- View delivery and ckeck availability -> the system doesn't complain!
- deliver the product -> the system doesn't complain! and your stock is now - 1

### PR DESCRIPTION
**Pull request by lmignon**
By default, the rounding method in product_uom round amount with ceiling.
Using a ceiling rounding method in product reserve can let the
user reserve more than what is available in location. Using floor
rounding in that situation is safe and will prevent negative stocks

### CODE REVIEW

**Comment by lmignon** [comment]
Linked to opw-615036

**Comment by clonedagain** [comment]
@odony perheps you could have a look at this, having already tackled several rounding issues recently?

**Comment by gurneyalex** [comment]
@lmignon no update from support on this? 

Maybe @beledouxdenis could share some insight?

**Comment by lmignon** [comment]
@gurneyalex unfortunately no news from @beledouxdenis and @odony The discussion is on https://github.com/odoo/odoo/issues/2854

**Comment by Yenthe666** [comment]
Hi @lmignon,

Odoo 7.0 is no longer supported so this PR won't be merged in anymore.
If you still face this issue you can make a PR against V8, V9 or V10 and we'll look into it as soon as possible.
Sorry!

Regards,
Yenthe

**Pull request closed without merging**
