### PR TITLE
[IMP] fields: allow reuse of the m2m relation if explicitly given

### PR DESCRIPTION
**Pull request by rco-odoo**
This allows a model to have several fields using the same relation on purpose,
for instance to show the related items filtered by domains.

Also adapt the code to handle multiple many2many inverses.

### CODE REVIEW

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo r-

**Comment by tivisse** [comment]
Sorry ;:)

**Comment by rco-odoo** [comment]
@Yenthe666 thanks for the suggestion. I added documentation to explain the rule and its exceptions.

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
Awesome, thanks a lot!

**Pull request closed without merging**
