### PR TITLE
[FIX]stock: Use correct filter on action

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: Fixes: https://github.com/odoo/odoo/issues/29777

Current behavior before PR: Incorrect Number of Records on Dashboard and Action

Desired behavior after PR is merged: Current number of records on Dashboard and Action

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@sswapnesh don't forget to squash them 👍

**Comment by sswapnesh** [comment]
I think @robodoo  can do that during merging (If it is approved)

**Comment by Yenthe666** [comment]
Yeah but some of the devs miss it and then it creates two or three commits :/

**Comment by sswapnesh** [comment]
Closing this and following up on Related Issue https://github.com/odoo/odoo/issues/29777#issuecomment-450399247.

**Pull request closed without merging**
