### PR TITLE
[FIX] google_calendar: not sending emails to existing event attendees

### PR DESCRIPTION
**Pull request by pedrambiria**
Before this commit: syncing with google led to sending emails to
attendees of existing future events on Odoo.

Steps to reproduce the first issue:

- Install 'google_calendar' module
- Integrate with Google Calendar in setting
- Add an event to the Odoo calendar for future date
- Add one external attendee to the event
- Sync with Google

Invitation emails would be sent to the attendees of the events.
Solution

It's possible to not send emails to the attendees in api calls. So
the solution is to not send emails to the attendees for the syncing
time.
opw-2819046

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@arj-odoo Are you ok with this fix ? 

This needs a test suite too to avoid FW issues as it has been the case the first time :)

Thanks :)

**Comment by arj-odoo** [comment]
> @arj-odoo Are you ok with this fix ?
> 
> This needs a test suite too to avoid FW issues as it has been the case the first time :)
> 
> Thanks :)

I agree on the principle but indeed it needs a test and if possible to have somebod to test it manually to make sure it works. Maybe @kbr-odoo if she is available :-).

**Comment by arj-odoo** [comment]
@tivisse This PR is updated. The behavior of `call_post_commit_hooks` had to be updated differently than in microsoft calendar.
I don't know why exactly it did not worked well with the function copy or why the method needs to be copied in microsoft calendar. 

```diff
@@ -74,9 +74,7 @@ class TestSyncGoogle(SavepointCase):
         manually calls postcommit hooks defined with the decorator @after_commit
         """
 
-        # need to manually handle post-commit hooks calls as `self.env.cr.postcommit.run()` clean
-        # the queue at the end of the first post-commit hook call ...
-        funcs = self.env.cr.postcommit._funcs.copy()
+        funcs = self.env.cr.postcommit._funcs
         while funcs:
             func = funcs.popleft()
             func()

```
Without this change, the following error occured:
```


File "/data/build/odoo/addons/google_calendar/tests/test_sync_common.py", line 67, in assertGoogleEventSendUpdates     
GoogleService._do_request.assert_called_once()   
File "/usr/lib/python3.8/unittest/mock.py", line 892, in assert_called_once     
raise AssertionError(msg) AssertionError: Expected '_do_request' to have been called once. Called 2 times. 
Calls: [call('/calendar/v3/calendars/primary/events?sendUpdates=none', ...
call('/calendar/v3/calendars/primary/events?sendUpdates=all', ...
--
2022-08-23 07:23:32 | ERROR | server |  
```

Don't hesitate to contact me or @pedrambiria if you have any question :-). I also tested it locally and I did not encountered issues beside the one my commit fixes.

**Comment by arj-odoo** [comment]
@robodoo delegate+

**Comment by pedrambiria** [comment]
@robodoo r+

**Comment by pedrambiria** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
