### PR TITLE
website_forum add image to the text editor

### PR DESCRIPTION
**Pull request by jpp-odoo**
[FIX] website_forum: remove forum's text editor mediaPlugin
    
    This commit remove the mediaPlugin from the forum's text editor.
    Now, to add a picture into a question or an answer into the forum, the
    user can drag and drop the image directly into the text editor. This new
    behaviour is the same as the behaviour in version 13.
    
    opw-2127345

------------------------------------------------------------------------------------------------
    [FIX] web_editor, website_forum: image drag and drop into forum's text editor
    
    Since 62c9dedafda0cbdc618641eaa80c49535ab0b5f6, if a portal user drag
    and drop a picture into the forum's text editor, the image is never
    loaded and an error is shown in the logs (right access error).
    
    Now, the portal user is allowed to create attachments for the forum.
    
    opw-2127345

### CODE REVIEW

**Comment by nle-odoo** [comment]
fw-bot up to saas-12.3

in 13.0 the image is directly in the text in base64

**Comment by nim-odoo** [comment]
robodoo rebase-ff

**Comment by nle-odoo** [comment]
(sorry still an addendum, to be more correct in the code over it should be:

```js
image.src = '/web/content/' + attachment.id + '/' + encodeURIComponent(attachment.name) + '?access_token=' + (attachment.access_token || '');
```

because `attachment.name` is not protected at all (so code would not work if there was a `?` in file name), and if we ever had not an access_token (should not be the case currently) we fallback on normal access right (with `?access_token=` equals empty string)

**Comment by jpp-odoo** [comment]
@nle-odoo just changed !

**Comment by jpp-odoo** [comment]
@odony  I made the changes we discussed today. Could you check it please ?

**Comment by nle-odoo** [comment]
robodoo r+ delegate+

**Pull request closed without merging**
