### PR TITLE
[IMP] web: replace unnecessary t-raw by t-esc

### PR DESCRIPTION
**Pull request by aab-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Iucapad** [comment]
@robodoo r+

**Comment by aab-odoo** [comment]
robodoo delegate=lucapad

**Comment by Iucapad** [comment]
@robodoo r+

**Comment by Iucapad** [comment]
Haha actually, it's iucapad i -> I

**Comment by aab-odoo** [comment]
robodoo delegate=Iucapad

**Comment by Iucapad** [comment]
@robodoo r+ !

**Comment by Iucapad** [comment]
@robodoo r+

**Comment by Polymorphe57** [comment]
robodoo r+

**Pull request closed without merging**
