### PR TITLE
[CLA] Add Arxilead CLA

### PR DESCRIPTION
**Pull request by Arxilead**
Description of the issue/feature this PR addresses: Add CLA corporate signature for Arxilead Tecnologia e Gestão Lda.

Current behavior before PR: CLA not signed

Desired behavior after PR is merged: CLA signed

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Arxilead** [comment]
@mart-e Is there any way this could be pushed? Runbot seems to be failing for some reason. 

Thank you.

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.
You have a l10n_pt_certification module in your PR. Could you move it to another branch and keep this PR only for CLA?

**Comment by reinaldoramosarxi** [comment]
Hello,

We cherry-picked the commit and force-updated it.

**Comment by mart-e** [comment]
Thanks for the update, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by KangOl** [comment]
@robodoo p=1

**Comment by KangOl** [comment]
@robodoo p=0

**Pull request closed without merging**
