### PR TITLE
[CLA] Antonio Espinosa antespi@gmail.com https://github.com/antespi

### PR DESCRIPTION
**Pull request by antespi**

### CODE REVIEW

**Comment by antespi** [comment]
Hi, is there any problem with my CLA?
I've two PR depending on it:
- https://github.com/odoo/odoo/pull/6704
- https://github.com/odoo/odoo/pull/6387

Thanks

**Comment by antespi** [comment]
Hi, is there any problem with my CLA?
Thanks for reply

**Comment by beledouxdenis** [comment]
Hello Antonio, 

Indeed, there is a problem with your CLA:
 - You signed your CLA as `Antonio Espinosa antespi@gmail.com`
 - But, as you can see by adding `.patch` to your PR, you commit it under `Antonio Espinosa <antonioea@antiun.com>`
https://github.com/odoo/odoo/pull/6393.patch
You have to, according to your wish
 - commit your PR as antespi@gmail.com
 - sign your CLA as antonioea@antiun.com

Regards,

**Comment by mart-e** [comment]
Sorry we missed your CLA request.
Yes there is an issue: you are committing with `@antiun.com` email address but are signing for a `@gmail.com` address.

**Comment by antespi** [comment]
@beledouxdenis @mart-e I've just fixed. Thank you

**Comment by mart-e** [comment]
Thanks for the update, merged at 0b886a70500d0c9ac780e6e468b5303cf656576f

**Pull request closed without merging**
