### PR TITLE
[FIX] doc: requirements.txt - Fix sphinx version to avoid errors

### PR DESCRIPTION
**Pull request by moylop260**
with the new parameter introduced from https://github.com/odoo/odoo/commit/9a07a4599ce08bd1e3a74579a982fa3a58dc6cb2#commitcomment-23092180
`add_node(..., override=True)`

The 2nd commit supports old versions too

### CODE REVIEW

**Comment by Yenthe666** [comment]
Apoligies for the initial mislabeling. Martin will see this soon enough 😉

**Comment by xmo-odoo** [comment]
@moylop260 should probably also update the needs_sphinx version in conf.py if we decide Sphinx 1.4 is a baseline requirement (/cc @mart-e @odony ?)

Alternatively, we can fix the add_node call by trying it with override=True, catching the error and retrying it withhout.

**Comment by moylop260** [comment]
@xmo-odoo I have created 2 commits with your 2 solutions, please choose one and merge it if you consider it good.

Note: Maybe both commits are valid

**Comment by xmo-odoo** [comment]
Since the current Ubuntu LTS only has Sphinx 1.3 (😢) I merged the compatibility version in 0819d3f116848276ec6d35bcd5ede0fc60f41633. Thanks!

**Pull request closed without merging**
