### PR TITLE
[FIX] website_sale: Instruct crawlers to not sort

### PR DESCRIPTION
**Pull request by yajo**
Follows https://github.com/odoo/odoo/pull/35852. More useless crawls saved.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa TT19920

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@JKE-be for your team, please. I haven't seen you today to say goodbye in person. I hope to see you again soon in Spain!

**Comment by JKE-be** [comment]
Should target v13 an not v11 imo since there are no réal bug/traceback without it.
See you soon... maybe in Spain ...  I was in Website booth.

@robodoo r+

**Comment by zeroheure** [comment]
@Yajo IMHO you'd better use javascript (onclick or document.location) than no follow.

**Comment by Yajo** [comment]
> IMHO you'd better use javascript (onclick or document.location) than no follow

I'm curious... why?

**Comment by zeroheure** [comment]
Because Google allways follow href links (see [Google's I/O developer conference, May 2018](https://www.youtube.com/watch?time_continue=610&v=PFwUbgvpdaQ) (video).
The `nofollow` attribute works for filters but doesn't work for normal pages. And here you can't be sure that Google understand that this "sort by" link is a filter.

This comes from discussions with SEO expert.

**Pull request closed without merging**
