### PR TITLE
[FIX] l10n_fi: CoA rework

### PR DESCRIPTION
**Pull request by malb-odoo**
During this commit: https://github.com/odoo/odoo/pull/126718/commits/00af576ec77e90b6e2e4b398e61b6b5a17f01067 We changed the CoA but when doing it, we added some subtitle as accounts which was wrong and can be misleading for the users.
Also adding some missing accounts.

We don't remove the accounts from the reports in case a user used those account, and we don't want them to be impacted by this change.

task: 4210069

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by yosuanicolaus — APPROVED** [review]
LGTM :+1:

final review by @gawa-odoo

**Comment by malb-odoo** [comment]
Maybe a tryloading in an upgrade script is needed now that it think about it :thinking:

**Review by gawa-odoo — COMMENTED** [review]
@robodoo r+

**Comment by gawa-odoo** [comment]
For the try_loading, as discussed, I don't think it brings real value for accounts. 
It's important for taxes, but for deleting the accounts, I would say we should try to avoid adding accounts by force.

**Pull request closed without merging**
