### PR TITLE
[8.0][WIP][IMP] make openerp.addons a namespace package

### PR DESCRIPTION
**Pull request by sbidoul**
Automatically add all eggs providing an `openerp.addons` package to Odoo's addons-path.

This is one possible way to make odoo compatible with addons packaged with setuptools with a [setup.py like this](https://gist.github.com/sbidoul/fb3d75de4ac0d44c04ed#file-setup-py).

**Caveat**: according to documentation, mixing `declare_namespace` with other code in `openerp/__init__.py` must not be done. This works for me but will probably have undesirable side effects in some situations.

### CODE REVIEW

**Comment by sbidoul** [comment]
For the record, this cannot work while there is code in `openerp/__init__.py`. 

I hope in the next Odoo version, openerp and openerp.addons can become true namespace packages. This is probably quite easy to do and opens a lot of possibilities.

In the meantime, we are using a workaround with a thin wrapper around odoo startup scripts: https://pypi.python.org/pypi/odoo-autodiscover.

**Comment by Yenthe666** [comment]
@sle-odoo any update on this one?

**Comment by sbidoul** [comment]
In https://github.com/odoo/odoo/commit/9b83dd5894fda3b8fb6a81bd20dd8ea8d6a5b1a4 @xmo-odoo made it so that `import odoo.addons` is now thing. That's nice.

Unfortunately it is not done in a way that `odoo.addons` is considered a namespace package by python.

If it was a namespace package, it would be possible to package and pip install addons using this technique: http://setuptools.readthedocs.io/en/latest/setuptools.html#namespace-packages

It would also enable automatic discovery of addons by looking at odoo.addons.__path__ in addition to the regular odoo addons_path.

@sle-odoo @xmo-odoo @odony are you interested in working on this for v10? 

I'd be happy to help. At first glance it should be relatively easy.

**Comment by sbidoul** [comment]
It turns out make odoo.addons a namespace package is not very difficult: https://github.com/odoo/odoo/pull/13237

**Comment by sbidoul** [comment]
Closing this one as this is being worked on for v10 in #13237.

**Pull request closed without merging**
