### PR TITLE
revert commit a0eb172cab590982168492ad16ad90c2228c6424

### PR DESCRIPTION
**Pull request by flotho**
Purpose : readd openrp-gevent dependencies in rpm packaging

### CODE REVIEW

**Comment by flotho** [comment]
Hi @nim-odoo, @sle-odoo ,

This PR is supposed to close :
* https://github.com/odoo/odoo/issues/9056
* https://github.com/odoo/odoo/issues/9673
* https://github.com/odoo/odoo/pull/8551

Any chance to be reviewed?

Regards

**Comment by sle-odoo** [comment]
Hello @flotho, i just discussed with @antonylesuisse and we think that it'll be cleaner if we could use odoo.py with a special argument to start gevevent instead of re-adding the openerp-gevent file, this way we could completely remove openerp-gevent from the repository.

**Comment by flotho** [comment]
Hi @sle-odoo and @antonylesuisse 

I totally agree with your position, yet what ill be the deployment scenario? 
* run 2 instances with different options
* .../...
Any advice on this would be appreciate because from now, messaging couldn't been delivered to customer in rpm based installations!

Regards

**Comment by sle-odoo** [comment]
@flotho could you test #10207 ? building the rpm should be as easy as

        python setup/package.py --no-testing --no-debian --no-tarball --no-windows

however i can build it for you if it doesn't work on your side.

**Comment by sle-odoo** [comment]
i'm closing this PR as it is not the preferred strategy but we can of course continue the discussion on the new pr

**Comment by flotho** [comment]
Hi @sle-odoo,

I had a problem with your command : 
```
['mv', '/home/florent/DEV/Serveurs/odoo/odoo_9-20151229/dist/odoo-9.0rc0-1.noarch.rpm', '/home/florent/DEV/Serveurs/odoo/odoo_9-20151229/odoo_9.0c.20151229.noarch.rpm']
Won't publish the rpm release.
 Exception: 'NoneType' object has no attribute 'endswith'
```
Could it come from my side?

regards

**Comment by flotho** [comment]
Hi @sle-odoo 

tested with odoo-dev branch and main stream, this command fialed for the same reason.
Any advice?

**Comment by gurneyalex** [comment]
#10502 is a similar (identical?) issue with Debian packaging...

**Pull request closed without merging**
