### PR TITLE
[FIX] web: rename special_fields to special_fields_tests

### PR DESCRIPTION
**Pull request by svs-odoo**
It's a tests file, like all tests file, its name must be finished by '_tests'.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rdeodoo** [comment]
what's the status of this one?

**Comment by svs-odoo** [comment]
@rdeodoo I forgot the existence of this PR :open_mouth:
As it's a "fix" but not really (just a rename), not sure it's better be merged it into master or before ?

**Comment by rdeodoo** [comment]
You should definitely check with someone from the framework team :)

**Comment by rdeodoo** [comment]
@aab-odoo Sorry to bother you, but not sure what should happen with this one.
I feel sorry every time I see 1 year work still in standby.
Can you close this one if not needed or dispatch to someone to handle it if needed?

**Comment by aab-odoo** [comment]
robodoo +

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by svs-odoo** [comment]
@aab-odoo I rebased the branch to resolve the conflict.

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
