### PR TITLE
[FIX] pos: render header and footer of a receipt

### PR DESCRIPTION
**Pull request by adwid**
To reproduce the error:
1. In the settings of a POS, enable "Header & Footer"
2. Add:
    - a header (with at least one line break)
    - this footer: "0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5"
3. Start a session
4. Validate an order
    - Error: The header of the receipt is incorrect, line breaks are not
applied
    - Note that in the footer, there is a line break after the third '3'
6. Print Receipt
    - Error: in footer, the line break is after the third '5'. In header, 
    still not any line breaks
7. Send the receipt by email
    - Error: in the receipt of the mail, the line break is after the
third '2' (footer). In header, still not any line breaks

For the header:
A style is missing

For the footer:
The appearance should be the same in the three cases. On step 5, here
are the values used to display the receipt:
https://github.com/odoo/odoo/blob/6c1172922505cd955d278bc80d327423fc6867a6/addons/point_of_sale/static/src/css/pos.css#L1680-L1692
This fix applies the same ratio `width/font-size = 18.75` on values used
to print the receipt (`266 / 18.75 = +-14`) and the ones used to
generate the receipt in the mail (`512 / 18.75 = +-27`). That way, the
appearance of the receipts remains similar.

OPW-2528558

### CODE REVIEW

**Comment by adwid** [comment]
@nle-odoo

**Review by nle-odoo — APPROVED** [review]
looks good to me, but be sure to test in safari that `white-space:pre-line` works because there is a lot of fixes we had to do because of \n and safari.

robodoo delegate+

**Comment by adwid** [comment]
Working on safari too :)
@robodoo r+

**Comment by adwid** [comment]
@robodoo r+ rebase-ff

**Comment by adwid** [comment]
@robodoo rebase-ff

**Comment by adwid** [comment]
@robodoo r-

**Comment by adwid** [comment]
@robodoo r+ rebase-ff

**Comment by nle-odoo** [comment]
robodoo rebase-ff

**Pull request closed without merging**
