### PR TITLE
Fix sale.order onchange issue #23276

### PR DESCRIPTION
**Pull request by rmmr**
See issue #23276

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e or @nim-odoo could one of you two have a look at this? I believe this is an important one in a common flow of Odoo.

**Comment by mart-e** [comment]
Hello,

Thank you for the pull request.  Could you [sign the CLA](https://www.odoo.com/sign-cla) to be able to merge your contribution?

After testing, it does not look you patch is changing the behaviour.
Could you explain why you think it is related?

**Comment by adaptivdesign** [comment]
@mart-e 

It should change the behaviour. In the issue i found 2 different situations.

- This patch should fix situation #2 where a combination of sale_management and stock modules always causes the reset.

- Situation #1 in which a order line is clicked in non-edit mode, thus showing the popup. After which editing causes a reset. is still NOT fixed by this. 

I will sign the CLA

**Comment by celm1990** [comment]
Please take into account commit f51d24d613f2bf125e54f0f87fd00e3e68688d93 can be contradictory on performance of fields related.

**Comment by tde-banana-odoo** [comment]
Ping @jem-odoo

**Comment by jem-odoo** [comment]
The fix was done in the `onchange` method of the ORM.
Since your PR does not solve and and that we do not merge code improvement in stable version, we might consider it for master.
Regards

**Pull request closed without merging**
