### PR TITLE
[IMP] Introducing zoom level for wkhtmltopdf in paper formats

### PR DESCRIPTION
**Pull request by melroy89**
Description of the issue/feature this PR addresses: wkhtmltopdf has several issues in the past and in the current future, which caused a lot of frustration. Due to misbehavior of wkhtmltopdf `--dpi` parameter. However, wkhtmltopdf also support a zoom parameter which can also be used to fine tune your documents. This PR will add support for this zoom feature in wkhtmltopdf. And therefor makes it easier to manipulate (PDF) reports in Odoo.

See related issues:
 - https://github.com/odoo/odoo/wiki/Wkhtmltopdf
 - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2156
 - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3741
 - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3651
 - And more...

Changes are *test & verified within Runbot*, and it seems to work fine!

Testing: You can test your changes yourself, by changing the current paper format settings. And increasing /decreasing the zoom field. Try to export a pdf (eg invoice), and compare the pdf file with an original (1.0 zoom factor). 

Current behavior before PR: Unable to use the `--zoom` parameter from wkhtmltopdf in Odoo. [Read more](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt).

Desired behavior after PR is merged: You can set *besides the already* DPI setting also set the zoom factor (default `1.0` float number), the same default value wkhtmltopdf uses. The zoom factor can be set in the paper format section, below the DPI setting.

*Question to the developers:* I'm adding a new field to the paper format model, do I need to write some upgrader? Or will Odoo take case of this automatically?

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by danger89** [comment]
Could somebody also please take a look to my CLA, since I just [signed it in the past](https://github.com/odoo/odoo/blob/11.0/doc/cla/individual/danger89.md). Why is the CLA check failing.

**Comment by danger89** [comment]
@mart-e bonsoir, would you mind to help me reviewing my pr? Thanks! I appreciate it very much.

**Comment by gdgellatly** [comment]
@danger89 personally I prefer the approach taken here which allows any arbitrary parameter - lest paper format just becomes a replica of all the different wkhtmltopdf options.  

For example if tuning zoom, often you will be disabling smart shrinking as well.  In fact usually when people start putting zoom of 1.04 what they really want is just a straight disable of smart shrinking.

https://github.com/OCA/reporting-engine/tree/11.0/report_wkhtmltopdf_param

**Comment by danger89** [comment]
@gdgellatly thanks. If you agree with the sames, and accept them. Could you please approve the pr changes?

Thanks for the link to this addon. I think it would be nice to also add this smart shrinking boolean (true /false) to the settings by default in odoo,in the future.

**Comment by sle-odoo** [comment]
@danger89 Hi, thanks for the PR. Wouldn't it make more sense to use the zoom argument if the --dpi one is ignored? So, according to the wkhtmltopdf version (starting from 0.12.2 if i'm not wrong). It's not straightforward as, against if i'm not wrong, internally wkhtmltopdf uses the default dpi to compute the effect of the zoom (so for instance 0.75 wouldn't have he same effect on windows and linux). So the idea would be to keep the --dpi argument but instead apply it with the --zoom one, only if the result looks the same on both windows and linux, and even if on linux you changed the default dpi. Would this be possible? If so, we could start supporting more recent wkhtmltopdf versiosn on master (if no other issues appear).

cc @smetl

**Comment by danger89** [comment]
@sle-odoo well I tested both different dpi and zoom factors with success. In fact I'm using the latest wkhtmltopdf version 0.12.4 locally under linux (Debian stretch), with success. By defining different dpi and zoom factors. So no, I think it should be possible to define both values separately from each other. Just like the cli command interface of wkhtmltopdf.

**Comment by danger89** [comment]
@sga-odoo @sle-odoo could somebody merge it?

**Comment by pedrobaeza** [comment]
I understand that this can be closed with the patch for adapting to newest version 0.12.5, isn't it?

**Comment by yelizariev** [comment]
> I understand that this can be closed with the patch for adapting to newest version 0.12.5, isn't it?

It seems so. 

Anyway, adding new field is against stable policy https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

**Comment by MiquelRForgeFlow** [comment]
Cherry-pick and do it in master then :S

**Comment by C3POdoo** [comment]
Dear @danger89,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
