### PR TITLE
[IMP] l10n_in: remove unused field `l10n_in_hsn_description`

### PR DESCRIPTION
**Pull request by hamo-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

see https://github.com/odoo/upgrade/pull/6451

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by hamo-odoo** [comment]
@robodoo r-

@jco-odoo staging is failing, I might have missed to remove demo data from `l10n_in_stock`

**Comment by hamo-odoo** [comment]
Well it's weird to see we don't have minimal check on the PR dashboard. We can still run the mandatory ci checks manually without requiring to rebase the upgrade PR 🧠

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
