### PR TITLE
[FIX] web_editor: restore broken VideoDialog options

### PR DESCRIPTION
**Pull request by kig-odoo**
To loop a single video,
set the only `loop` parameter value to 1 will not work anymore.
we also need to set the `playlist` parameter value to the same video ID

### CODE REVIEW

**Comment by kig-odoo** [comment]
Hello @qsm-odoo ,

I've found a small bug during the development of Background video task.
The bug is because of the Youtube API [changes](https://developers.google.com/youtube/player_parameters#loop).
Could you please look at this PR? 

Thanks

**Comment by qsm-odoo** [comment]
@kig-odoo On save, the autoplay feature does not work either... could you check and fix it with this PR too if you have the time? Thank you !

**Comment by kig-odoo** [comment]
I've already checked this issue. And found that [Autoplay policy is changed](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#new-behaviors) for most browser. Autoplay with sound is no longer allowed. Muted autoplay is always allowed. I didn't fix this issue in this PR because autoplay feature is introduced in V10.

should I fix this issue in the current branch?

**Comment by qsm-odoo** [comment]
Yes, you can fix it in 11.0 in this PR :) This is a non-blocking bug and 10.0 will be deprecated in 3 months anyway :wink: Thanks !

**Comment by kig-odoo** [comment]
Done :+1:

**Comment by qsm-odoo** [comment]
@robodoo r+
@kig-odoo Thanks! I've reviewed the commit message and added a small text to warn users about the fact autoplay will mute the video.

**Pull request closed without merging**
