### PR TITLE
[IMP] account,mail : Use job queue to send by mail invoices

### PR DESCRIPTION
**Pull request by ZedarkMoon**
This commit uses the mail queue when the user uses the "Send & Print"
functionality. The behavior before this commit is a synchronous send,
meaning that the app wait for EDI validation before sending the mail and
closing the wizard.

It creates a new model, mail_message_pending, that
represents a mail_message that is yet to be send and store all values
that will be used to send it.

We have used this approach because we wanted to put the message in the
chatter at the right time, i.e. when the mail is send (and not when the
message is created). Since the order of messages in the chatter is
linked to id (in js) it is the easiest way of doing it.

task-2764998

### CODE REVIEW

**Comment by csnauwaert** [comment]
as discussed, it is usually bad practice to write code in other module and especially if those module don't have any dependencies to account.

Also there is probably don't have any need for a new model. Just overloading the message_post to delay the call to the super method if the message is an account move and has an IDE that is not send is probably sufficient.

**Review by csnauwaert — CHANGES_REQUESTED** [review]
see general comment

**Comment by tde-banana-odoo** [comment]
:eye: Not sure what you are trying to do, but indeed it should be correctly integrated into mail.

**Review by csnauwaert — CHANGES_REQUESTED** [review]

**Comment by ZedarkMoon** [comment]
Closed because the task is cancelled and supported by task-3117238 (New Send & Print wizard)

**Pull request closed without merging**
