### PR TITLE
[IMP] qweb: add 'digits' and 'field_digits' options to monetary widgets

### PR DESCRIPTION
**Pull request by fvdsn**
This commit adds two options that are useful to correctly format
monetary values in QWeb Reports.

The 'digits' integer option to the monetary widget, allow to override
the number of decimals that will be displayed, when they would other-
wise be taken on the currency instead.

Ex:

```
<div t-field="foobar" t-field-options="{
                            'widget': 'monetary',
                            'display_currency': 'foobar_currency_id',
                            'digits': 3,
                            }" />
```

NOTE: This options only changes the way the value is displayed, if
the field is of type monetary, its value has already been rounded in
the database, and increading the digits will just add zeroes.

The 'digits' option is also available to t-esc-options.

Ex:

```
<div t-esc="foobar" t-esc-options="{
                            'widget': 'monetary',
                            'display_currency': 'foobar_currency_id',
                            'digits': 3,
                            }" />
```

The 'field_digits' boolean option for the field monetary widget allows
to override the currency decimal precision with the field's own decimal
precision (that has been set on the field with digits_compute).

Ex: `<div t-field="foobar" t-field-options="{ 'field_digits': 'True' } />`

NOTE: This is not available to t-esc-options, since t-esc has no
information on the value's intended precision.

### CODE REVIEW

**Comment by fvdsn** [comment]
Github's markdown parser seems to have removed parts of the original commit message ...

**Comment by odony** [comment]
The patch looks good to me, thanks (apart from minor PEP8 details). However, is there a point in adding the `field_digits` option? It is not consistent with either the client-side QWeb options nor with the `t-esc` options, so it will be an obscure and hard-to-locate feature.
Isn't a hardcoded `digits` option quite sufficient in most cases?

PS: could you also set your `git config user.email` correctly in order to pass the CLA checks?

Thanks!

**Comment by odony** [comment]
On second thought the `field_digits` option is OK, as long as we have some unit tests for all these options. It would be rather trivial to extend the existing `test_qweb_float` in the `decimal_precision` module to add a `test_qweb_monetary` that will check the various options for specifying and overriding the digits. It would also serve to test the basic monetary display features. (Probably requires adding a couple of fields in the `decimal.precision.test` model) Thanks!

**Comment by pedrobaeza** [comment]
I think this can be closed, isn't it?

**Comment by C3POdoo** [comment]
Dear @fvdsn,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
