### PR TITLE
9.0 Branch l10n Ecuador - Taxes ATS Anexo Transaccional Simplificado SRI

### PR DESCRIPTION
**Pull request by odoo-group-ecuador**
Description of the issue/feature this PR addresses:
ATS Tax Declaration in Ecuador ( http://www.sri.gob.ec/de/172 )

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by odoo-group-ecuador** [comment]
Included Individual and Corporate signed CLA for Odoo Group Ecuador

**Comment by mart-e** [comment]
Hello,

What is the goal of this module? It looks to be more than a localisation.

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `odoo-group-ecuador@users.noreply.github.com`
- you are signing for the address `@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by odoo-group-ecuador** [comment]
Hello mart-e I'm glad what you help me.

I already fixed my email issue, it was just what I forget set my email address as "public" on Github settings; I use snowblow07@gmail.com.

The goal of my project is to provide Odoo with a complementary module of localization for Ecuador named "l10n_ec_ats" adding some simple fields according to the ecuadorian tax law as explain the official document attached to this comment.

My wish and personal goal is to take responsibility and complete support to keep updated this localization module.

I am very happy what you answer.
thanks!

[FICHA_TECNICA_ATS_JULIO2016.pdf](https://github.com/odoo/odoo/files/452149/FICHA_TECNICA_ATS_JULIO2016.pdf)

**Comment by damendieta** [comment]
Looks like it's a duplicate PR from #13590 and may be closed.

**Pull request closed without merging**
