### PR TITLE
[10.0][IMP] Improvements of VAT report and implementation TVA return …

### PR DESCRIPTION
**Pull request by ghost**
…charge

Description of the issue/feature this PR addresses:

fix some VAT issues for Swiss localisation

Current behaviour before PR:

some VAT tags and templates are missed.

The desired behaviour after PR is merged:

add new vat tags and templates. fix indentation

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by leemannd** [comment]
@fclementic2c Needs review/testing

**Comment by fclementic2c** [comment]
:+1: 
review ok

**Comment by fclementic2c** [comment]
@qdp-odoo as discussed on 'Task - 2 erreurs dans Rapport TVA suisse (#1852829)'
thanks

**Comment by leemannd** [comment]
Hello @qdp-odoo Do you know when it is planned to merge it?

**Comment by qdp-odoo** [comment]
landed in v10 at revision https://github.com/odoo/odoo/commit/aab2fc0e33b0836f01a1a160c295fe192d148078

thanks for the contribution

**Pull request closed without merging**
