### PR TITLE
[ADD] l10n_pl: add Polish states to localization

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Add the Polish states into the Polish module

Current behavior before PR: The states aren't in Odoo

Desired behavior after PR is merged: The states are in Odoo

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e and @sht-odoo we'd need to discuss this based on the commit https://github.com/odoo/odoo/commit/6fc4c53404a0171dd528ba7981dcca1564999b33#diff-833dc83700e747ddbbf5840cb49009bb
See also https://github.com/odoo/odoo/pull/37429#issuecomment-568260161 for extra details.

**Comment by sht-odoo** [comment]
Hii,
@Yenthe666 
I think you should add Polish states in 'base' module instead of localization module.

**Comment by mart-e** [comment]
@sht-odoo this is a disagreement I have with JCO about this.
Poland does not require states in the address format so it is really not necessary to bloath the list of states in base with it.
https://www.bitboost.com/ref/international-address-formats/poland/

@Yenthe666 could you please keep the information, at least a "courtesy of" with reference to the original PR in the commit.
Thanks

**Comment by Yenthe666** [comment]
@mart-e do you mean in the commit description?

**Comment by mart-e** [comment]
@Yenthe666 yes, the only place where the information about the patch is really necessary

**Comment by Yenthe666** [comment]
@mart-e done, I've added some extra info (pointing back to the original PR & author)

**Comment by mart-e** [comment]
Great, thanks, I have just changed a bit: 
- make an empty line between title and content (otherwise it makes one long title)
- avoid @ the author, it tends to be spammy as you receive one notification per commit, including each rebase/retry/cherry-pick/forward-port

**Comment by mart-e** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo retry

**Comment by Yenthe666** [comment]
Thanks guys :)

**Pull request closed without merging**
