### PR TITLE
[IMP] hr_timesheet: remove the unused code from hr_timesheet

### PR DESCRIPTION
**Pull request by mba-odoo**
Currently, the timer does not exist in hr_timesheet so project.task.create.timesheet wizard is useless in hr_timesheet and not used anywhere in hr_timesheet.

so in this commit removed project.task.create.timesheet wizard from hr_timesheet.

task-2710154

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work! 🙂

**Review by IT-Ideas — APPROVED** [review]
LGTM Thanks 🙂

**Comment by IT-Ideas** [comment]
@robodoo r+

**Comment by IT-Ideas** [comment]
@robodoo r+

**Pull request closed without merging**
