### PR TITLE
17.0 odoo 171924 backport xdo

### PR DESCRIPTION
**Pull request by Xavier-Do**
Backport of #171924

`git cherry-pick ccacc9031548ba95b8e65b7f1d8e23fb22aaedf8..7d43ad05b15afbbe1c9ca0668a0308cb514195e7`

Conflict notes: 
- requirements.txt conflicted on Babel and chardet, kept as the target
- 0414da47d3548270380c9d577f84fbbcd0d5967e was adapted manually since the file was moved in some version

### CODE REVIEW

**Comment by Xavier-Do** [comment]
@robodoo up-to saas-17.2
@robodoo rebase-ff
@robodoo r+

**Comment by Cedric-Pigeon** [comment]
Since this commit, I get:

The conflict is caused by:
    odoo 17.0 depends on chardet
    requests 2.25.1 depends on chardet<5 and >=3.0.2
    The user requested (constraint) chardet==5.2.0

while installing...

Any ideas ?

**Comment by Xavier-Do** [comment]
Strange, can you give more informations about your system? Python version, operating system, ...

**Comment by Cedric-Pigeon** [comment]
sure: 
ubuntu 24.04 LTS
Python 3.11.9

**Comment by Xavier-Do** [comment]
> sure: ubuntu 24.04 LTS Python 3.11.9

How, this doesn't really make sense since in ubuntu 24.04 the default version of python should be 3.12

Did you install the python version manually of did you install a pre-release of the 24.04? 

Odoo should be able to run on 3.11 to but we are mainly targeting debian bookworm with this version and it's not the most maintained and we may still have some tweek to do.

**Comment by Cedric-Pigeon** [comment]
I installed python3.11 manually

**Comment by Xavier-Do** [comment]
I would suggest you to go back to python 3.12.

I would also suggest you to avoid to use the requirements and prefer the debian packages version

`sudo ./setup/debinstall.sh`

This will install the best version of the packages for your operating system and python 3.12, and you will benefit from security upgrades.

**Comment by Cedric-Pigeon** [comment]
well I am working with virtualenv so should not be a problem, is it ?

**Comment by Xavier-Do** [comment]
It shouldn't if it isn't a production environment ;) 

Anyway, I noticed that we have the same error with the distro builds and it wasn't indeed the case before. The same error was present in master but was hidden by another error. 

https://runbot233.odoo.com/runbot/static/build/65757791-17-0/logs/install_all.txt

I will take a look to fix it asap :)

**Comment by Cedric-Pigeon** [comment]
No it is only my laptop. Production is running on 22.04 :-)

Ok thanks,

**Comment by Xavier-Do** [comment]
I think that #173913 should to the trick, can you confirm?

**Comment by Cedric-Pigeon** [comment]
@Xavier-Do Yes it does, thanks.

**Pull request closed without merging**
