### PR TITLE
[FIX] l10n_ch: Print QR-bill button should be only on customer invoices

### PR DESCRIPTION
**Pull request by agr-odoo**
opw-2320456

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@simongoffin

**Comment by agr-odoo** [comment]
@simongoffin

**Review by simongoffin — COMMENTED** [review]
Hello @agr-odoo 
A little thing, just improve the commit message by saying "Print QR-bill button should be only on customer invoices" I know we used to say vendor bill but in this way there is no confusion

**Comment by simongoffin** [comment]
robodoo delegate+

**Comment by agr-odoo** [comment]
@robodoo r+

**Review by simongoffin — APPROVED** [review]

**Pull request closed without merging**
