### PR TITLE
[FIX] web_editor: block zws changes on the field mutation observers

### PR DESCRIPTION
**Pull request by xO-Tx**
Steps to reproduce [17.0]:

- Go to website (in "Edit" mode) > Switch to mobile view (mobile icon).
- Open the navbar and click on the "Contact Us" button.
- The `linkTools` are displayed in the toolbar > Try to change the link
label > Only the first input character is applied. After that, every
update will be simply ignored and not applied to the target.

Some context:

Starting from [1], a "zero-width space" mechanism was implemented to
handle collapsed selections at the edges of links (mainly to make
difference between the selections inside the link (start/end) and
outside of it).

After that, a fix was backported to `15.0` (see: [2]) to prevent history
steps that include the link ZWS adaptations by disabling the observer
when the ZWS is added or removed.

Also on `17.0`, and after the website headers refactoring from [3], two
header navbars were added (for the desktop view and mobile). Which means
that the "Contact Us" field is also duplicated in the DOM.

Technical details:

Now, if the label was edited for the first time using `linkTools`, this
will trigger the following actions:

[A]- "Contact Us" label edited on "Desktop" view (the first in the DOM):

1- An update is detected on desktop link (see `_updateLinkContent`).

2- The field observer will copy the changes on the mobile link to ensure
the field has the same value throughout the page.

3- The `historyStep` is updating the ZWS on the desktop and mobile links
(see: `_resetLinkZws`, `_insertLinkZws`).

4- The field observer will adapt the mobile link to match the HTML of
the desktop one.

5- The field observer detects the mutations from [A.3] on the mobile
link too but won't update the desktop one again since they have the same
HTML.

[B]- "Contact Us" label edited on "Mobile" view (the second in the DOM):

1- Change is detected on mobile link > The field observer will copy the
changes on the desktop DOM.

2- Same as [A.3].

3- The field observer will adapt the mobile link to the same HTML as the
desktop one. And as a consequence, the reference to the link
(`this.$link`) will be lost in the `linkTools`, and the next input
update won't be applied.

Actually, the comparison between [A] and [B] explains why the issue
occurs only if the last copy of the field in the DOM was targeted.

The goal of this PR is to prevent this behaviour by simply not taking
the ZWS mutations in consideration in the field update system..

Remark: The issue was detected on 17.0 with duplicated DOM for header
action, but we target 15.0 here to prevent any similar issue linked to
the ZWS changes on fields.

[1]: https://github.com/benandfrank/odoo/commit/367ee3e516ee01168ca2cfb1cac5ac5530088875
[2]: https://github.com/odoo/odoo/commit/33ef91cc577d8b397a948c430b77c2e038013d2d
[3]: https://github.com/odoo/odoo/pull/119650

opw-3706902

### CODE REVIEW

**Comment by rdeodoo** [comment]
@odoo/rd-framework-editor (maybe more specifically @Zynton ) would you be down having a look at this one?

**Comment by Zynton** [comment]
@rdeodoo Looks good to me! Note that there's work in progress to improve this link zws system so that this kind of stuff might not be needed anymore if it works as expected. If so I'll keep this PR in mind. cc @sebgeelen

**Comment by rdeodoo** [comment]
@Zynton Do you have an ETA for this zws change? Will it target 15?
If I got this right, you prefer to keep the current PR on hold while you see with the zws change?

**Comment by Zynton** [comment]
> If I got this right, you prefer to keep the current PR on hold while you see with the zws change?
Yes.

It will indeed target 15.0. There's no clear ETA at this point because the approach has yet to be validated and we're working on it when we can find some time in between more urgent things.

**Comment by xO-Tx** [comment]
Hello @odoo/rd-framework-editor! Since the PR is linked to an OPW ticket, I think we can merge this FIX in stable while waiting for the full system refactoring :+1:

**Comment by dmo-odoo** [comment]
Hello @xO-Tx, well actually the PR about the refactoring of link zws is done. It is currently in testing phase and I will personally make sure to review it in priority. This means it should be merged during next week. In this regard, I don't think it is advisable or particularly useful to merge a specicialized fix in the meantime. Therefore, I'm closing this PR but feel free to reopen it if you disagree about my assessment of the situation.

**Comment by xO-Tx** [comment]
Hello @dmo-odoo OK for me! Thanks :+1: Can you just ping me on the new PR, so I can update the OPW when it's merged :+1:

**Comment by dmo-odoo** [comment]
@xO-Tx Sure, it's this one: https://github.com/odoo/odoo/pull/157200

**Pull request closed without merging**
