### PR TITLE
Suggest participation in code triage

### PR DESCRIPTION
**Pull request by blaggacao**
This pull requests is result of an initiative triggered by this discussion on the mailing list:
https://www.odoo.com/groups/community-59/community-13404259?mode=date&date_begin=2015-07-01&date_end=2015-08-01

It is about to help contributers sort out the issue.

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

I have checked CodeTriage but I am not sure to understand how it will help the project. If I understand correctly, it will only give you an digest email containing all the new issues activity, right?
While this may be helpful for the people following the issues and wanting to answer on reported issues (big thanks to these people), I unfortunately don't think it will really help making a difference in the global problem.

What we would really need to allow contributors for make a difference is to allow these people to qualify, tag and close issues. This is a lack in the github permission system (not something that Odoo should fix).
All the tool you have pointed (waffle.io, overv.io, gitter.im, codetriage...) just either reuse existing github permission system or move the discussion to another channel. The solution of moving the issues to another repository is not ideal either (loosing interaction with commit hash, magic keywords "Fix #42", etc.).
When you see that many issues lack of details to be useful (just "I get a 500 error when connecting" or not even the version information), adding complex interaction with external tools or splitting the discussion will be useful only for a small minority of people, and not the people not reading the `CONTRIBUTING.md` file in the first place.

**Comment by blaggacao** [comment]
I agree mostly.
You're right on CodeTriage. Look here a case of success: https://github.com/odoo/odoo/issues/6574
Officially encouraging such behavior could make a marginal difference at little cost, while fostering community involvement.

**Comment by blaggacao** [comment]
What do you think of the idea of writing a small server hook script, that analyzes an issue comment for tags, checks against authorized users (similar to the cla mech) and adapts labeling or even closing of issue by an authorized Bot Account. This could make a difference as well, meanwhile...

**Comment by mart-e** [comment]
So you mean inventing some kind of markup language so that if some authorized users leave a comment containing "[close]", it would close the issue by a bot ?
I can't believe such tool (or one to redefine permissions) does not already exists on a platform like github (I have been searching for, no luck so far).

I am not against such tool if you find/write a good one but again I believe this is something that should be fixed on Github side, not us needing to hack our way around.

**Comment by blaggacao** [comment]
This was my idea. I've been looking around as well quite a lot and did not find anything. It is true that this should not be a Odoo task. It's very strange indeed, that nothing is changing in this respect in the ecosystem... However, if you like the idea of CodeTriage in order to educate "issue reportes" this could be an effective soft measure, else I would suggest to close this PR in order to cleanup.. :)

**Comment by blaggacao** [comment]
@mart-e Look how others do: https://github.com/docker/docker/issues/16265#issuecomment-139890903

It's very similar to my idea, maybe we can ask them for their script? @GordonTheTurtle would you be willing to share your automated script?

**Comment by max3903** [comment]
@blaggacao I don't think triaging issues is the main thing OCA should focus on. To me, reviewing is the main bottleneck today.

**Comment by mart-e** [comment]
@blaggacao but again, what they do docker is not what CodeTriage is about as I understood it (explaining contributing guidelines vs mailing list about issues).
We could start implementing bots (for instance I am a fan of the CLA Googlebot https://github.com/google/oauth2client/pull/200 ) if that helps though. But for CodeTriage, sorry I don't think would be very helpful.

**Comment by blaggacao** [comment]
Yes, Martin, you're right! Bot's would even be a hell lot more helpful, than this CodeTriage... Anything that promotes the quality of issues is a real gain to the community as a whole... It's great to hear, that you are in favor of bots! I'll ping @GordonTheTurtle again, to see if he might be willing to share his code... Or any other bot would do just great! Closing this is fine with me.
Another thing which sadly does not catch momentum yet is http://gitter.im/odoo - It's so convenient for community meta discussion on some issues with all it's hooks and integrations... (as a friendly side note)

**Pull request closed without merging**
