### PR TITLE
[FIX] core, web: Pillow 9.1 deprecations

### PR DESCRIPTION
**Pull request by xmo-odoo**
Pillow 9.1 deprecates most if not all toplevel Image constants: https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#constants

These constants have been moved to thematic enum classes (e.g. all the resampling constants in `PIL.Image.Resampling`).

This triggers warnings in Odoo, and the removal delay is quite short (slated for Pillow 10, release planned mid 2023). Pillow 9.1 is also already in Debian Bookworm (current testing).

Fix by shimming at the import level: if the enums are available import them into the local namespace, otherwise alias `PIL.Image` itself as to the enum.

### CODE REVIEW

**Comment by xmo-odoo** [comment]
Q: should these compatibility shims be implemented in older versions and forward-ported? Assuming bookworm becomes the new stable circa 2023, will we be wanting / expecting that 14.0 be compatible with it?

**Comment by d-fence** [comment]
> Q: should these compatibility shims be implemented in older versions and forward-ported? Assuming bookworm becomes the new stable circa 2023, will we be wanting / expecting that 14.0 be compatible with it?

Yes, it would be better to backport but nothing urgent as Debian will release when ready.

**Comment by xmo-odoo** [comment]
> Yes, it would be better to backport but nothing urgent as Debian will release when ready.

Sure but there's no reason not to do it properly the first time around if we know we'll have to do it anyway.

**Comment by xmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
