### PR TITLE
[IMP] sale_timesheet: hooks in project_create_sale_order

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Description of the issue/feature this PR addresses:
Refactor code a bit to split it by methods that can be overriden. These changes would allow to introduce additional billable types.

Current behavior before PR:
Impossible to define additional billable configuration for Sale Order

Desired behavior after PR is merged:
Possible to define additional billable configuration for Sale Order

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@jem-odoo this one breaks large method into pieces

**Comment by jem-odoo** [comment]
Hello, can you rebase and add a proper commit message to explain *why* you want to do that changes. Otherwise, code looks okay.
Thanks .

**Comment by alexey-pelykh** [comment]
@jem-odoo I've updated the PR description. This change would allow to extend Odoo with module that introduces additional billing type, e.g. employee_job_rate or similar.

**Comment by alexey-pelykh** [comment]
@jem-odoo what are next steps with this PR?

**Comment by alexey-pelykh** [comment]
@jem-odoo and this one?

**Pull request closed without merging**
