### PR TITLE
[FIX] repair,product: pricelists multi company

### PR DESCRIPTION
**Pull request by Feyensv**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@fw-bot up to saas-13.1

**Comment by Feyensv** [comment]
@fw-bot up to master

**Comment by Feyensv** [comment]
Ping @dbo-odoo :crying_cat_face:

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
