### PR TITLE
[IMP] core: bump master release to 16.1 alpha

### PR DESCRIPTION
**Pull request by d-fence**

### CODE REVIEW

**Comment by d-fence** [comment]
robodoo r+ p=0

**Comment by d-fence** [comment]
robodoo retry

**Comment by d-fence** [comment]
robodoo retry
it should be good, templates are ok

**Comment by d-fence** [comment]
robodoo p=0

**Comment by d-fence** [comment]
robodoo retry p=0
🦐

**Comment by d-fence** [comment]
robodoo p=0
As I said already

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
