### PR TITLE
fix crash introduced in 675357b

### PR DESCRIPTION
**Pull request by gurneyalex**
and add an automated test.

### CODE REVIEW

**Comment by gurneyalex** [comment]
@odony :gift:

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by lepistone** [comment]
:+1:, thanks. The camptocamp CLA is #5190.

**Comment by odony** [comment]
@gurneyalex Thanks a lot for the super fast reaction and for providing the test!

**Comment by odony** [comment]
and thanks @lepistone for writing the test in the first place, of course!

**Comment by lepistone** [comment]
:smile_cat:

**Pull request closed without merging**
