### PR TITLE
[FIX] web: avoid multiple displays of the "same" discard warning

### PR DESCRIPTION
**Pull request by Polymorphe57**
Before this commit, editing a record e.g. in a form
view and toggling the home menu would cause the discard
warning to be displayed twice when going to the home
menu (in enterprise) and then once again when going to
an other app. This is now fixed.

Task ID: 2043027

Co-authored-by: Mohammed Shekha <msh@odoo.com>
Co-authored-by: aab-odoo <aab@odoo.com>

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Polymorphe57** [comment]
@msh-odoo I have reviewed your PRs in the task https://www.odoo.com/web#action=333&active_id=133&id=2043027&menu_id=4720&model=project.task&view_type=form
The problem was introduced in https://github.com/odoo/odoo/pull/33172.
So in the end we don't have to modify the web_client itself.
The idea was that the noAbandon option used to prevent the record from being cleaned, leading to the warning being repeatedly displayed:
    canBeDiscarded: function (recordID) {
        var self = this;
        if (!this.isDirty(recordID)) {
            return Promise.resolve(false);
        }
        var message = _t("The record has been modified, your changes will be discarded. Do you want to proceed?");
        var def;
        def = new Promise(function (resolve, reject) {
            var dialog = Dialog.confirm(self, message, {
                title: _t("Warning"),
                confirm_callback: resolve.bind(self, true),
                cancel_callback: reject,
            });
            dialog.on('closed', def, reject);
        });
        return def;
    },

**Comment by msh-odoo** [comment]
@Polymorphe57 I know issue arise from #33172, did you try scenario which is given in commit message after your fix? would you please check scenario given in this commit: https://github.com/odoo/odoo/pull/33172/commits/6b3bc9f08d9b96f6dd7f95f8256c345921a523d4

**Comment by Polymorphe57** [comment]
@msh-odoo I just did it manually to be sure but there was a test for that in https://github.com/odoo/odoo/commit/6b3bc9f08d9b96f6dd7f95f8256c345921a523d4
Do you think I missed something?

**Comment by msh-odoo** [comment]
@Polymorphe57 If tests gets green signal then it should be OK 👍

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Pull request closed without merging**
