### PR TITLE
[REM] base,web: delete menu Apps Store, Updates

### LINKED ISSUE #72902: [14.0] server error when trying to update module from the updates menu.
Impacted versions: 14.0

Steps to reproduce: enter apps, updates and try to update any module

Current behavior: system error

Expected behavior: module update

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: button_immediate_upgrade() takes 1 positional argument but 2 were given

### PR DESCRIPTION
**Pull request by yelizariev**
Those menus are supposed to be integrations with apps.odoo.com, but it doens't work and not maintained.

Existing menus that open apps store links should be enough:

* Apps >> Apps >> Theme Store --> https://apps.odoo.com/apps/themes
* Apps >> Apps >> Third-Part Apps --> https://apps.odoo.com/apps/modules

---

close #72902
close #74602

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
# Before

image

# After

image

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Comment by niyasraphy** [comment]
hi @yelizariev ,
similar can we remove the "Apply Schedule Upgrade" menu also ?
seems this is also not used/maintained(correct me if am wrong) any more. if the menu is not necessary, i can create the pr for the same.

looking for your thought.
thanks

**Comment by CasVissers-360ERP** [comment]
@yelizariev @aab-odoo 
What is the alternative Odoo offers to check for App updates?

**Comment by CasVissers-360ERP** [comment]
@aab-odoo @yelizariev 
Can you please provide an alternative method to do this?

**Pull request closed without merging**
