### PR TITLE
[FIX] website_sale_loyalty: match correct coupon code on checkout

### PR DESCRIPTION
**Pull request by lvsz**
Versions:
---------
- saas-16.3+

Steps to Reproduce:
-------------------
1. go to Sales / Products / Discount & Loyalty;
2. go to 10% Discount Coupons;
3. click on Generate Coupons;
4. generate for Selected Customers (yourself);
5. repeat to get a second coupon;
6. go to webshop and try to buy something;
7. at checkout, try to apply the first coupon.

Issue:
------
Clicking the coupon's "Use" button doesn't seem to do anything.

Cause:
------
The `claim_reward` method iterates over all potential coupons, always
selecting the last, most recent one, only to reject it if the code
doesn't match the coupon selected by the user.

Solution:
---------
Return as soon as a matching coupon is found.

opw-3562615

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks better to me

maybe the part:

```py
        if code == coupon.code and (
            program_sudo.trigger == 'with_code'
            or (program_sudo.trigger == 'auto' and program_sudo.applies_on == 'future')
        ):
            return self.pricelist(code)
```
should just be inside the loop (in case we select a coupon  with the right code but that is not available)

**Comment by lvsz** [comment]
@nle-odoo Good point, managed to shorten it a bit that way as well. Also added a second commit making a small change in the same method to prevent a potential `TypeError`. Not sure if I can squash it in the same commit instead, or if should be done in a separate PR.

**Review by anko-odoo — APPROVED** [review]
Hello, LGTM :)

**Comment by nle-odoo** [comment]
robodoo delegate+

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

**Comment by lvsz** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
