### PR TITLE
Saas 11.5 customer display snippets nje

### PR DESCRIPTION
**Pull request by nje-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR: https://drive.google.com/file/d/194FxqlvkU8ufgWP6ZLL2GYR2hy8_yR7K/view

Desired behavior after PR is merged: https://www.awesomescreenshot.com/image/3632599/1d003efbbe540752bd3200fbe6fdae3b

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rdeodoo** [comment]
Is someone supposed to handle this one? Any task? Still needed?

**Comment by nje-odoo** [comment]
Hello @rdeodoo 
issue is still reproduce in current v(12) : http://tinyurl.com/y5qyv8rn

**Comment by rdeodoo** [comment]
@lap-odoo Could you please have a look at the screenshots here and confirm the wrong behavior? I don't know how to switch to edit mode in POS
So we can find someone to review/merge this one :)

**Comment by rdeodoo** [comment]
@nje-odoo In any case this PR should now target 12.0, if you could change base target of this PR and rebase on it if needed

**Comment by nje-odoo** [comment]
Re-target in  v12 at PR : https://github.com/odoo/odoo/pull/34854

**Pull request closed without merging**
