### PR TITLE
Master wowl rebased dam

### PR DESCRIPTION
**Pull request by Polymorphe57**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tanghulu0608** [comment]
hello, every one , I have a question. What does the 'dam' means? 😳

**Comment by mart-e** [comment]
@tanghulu0608 it's the trigram for the developer who created the branch ;-)
@Polymorphe57 could you give a name and a description to your PR? Or create it in draft if it's still an ongoing development.

**Comment by tanghulu0608** [comment]
@mart-e  Will all the javascript components in web module be converted to owl in V15?

**Comment by aab-odoo** [comment]
@tanghulu0608 Not all of them, the conversion is in progress. Hopefully, everything will be converted for v16.

**Comment by tanghulu0608** [comment]
@aab-odoo  Thanks. 🤓

**Comment by tanghulu0608** [comment]
@aab-odoo  Another question: Will the javascript components in website and relate modules be converted to owl ? Thanks.

**Comment by sdegueldre** [comment]
@tanghulu0608 in short: not much in the website/frontend modules has been converted to owl. I've done some work so that these modules can use as much of the new infrastructure as possible (that is, access to the new services and the new environment that goes with it), but the work on this end started quite late and making sure that we didn't have to keep using old webclient code in those modules was challenging as it was, so basically on the topmost layer (the public root) has been "converted". I say "converted" because basically all I've had time to do was stick the original public root in an adapter that lets it use the new services so that we don't need to keep maintaining a separate version of the services for the frontend, the full conversion of the public root is a project of its own as it's kind of a "god" widget that coordinates a lot of things.

As far as non-infrastructure code, not much has been converted, this will be something I'll be working on quite heavily for v16. Bottom line is: if you need to write custom code that needs the new environment and services, they will be available, but with almost no support from the website/frontend "framework", most likely until v16 is out.

**Comment by tanghulu0608** [comment]
@sdegueldre  Thank you very much. We will wait until V16 to do some development base on odoo website modules.

**Pull request closed without merging**
