### PR TITLE
[FIX] account: move analytic items menu

### PR DESCRIPTION
**Pull request by vin-odoo**
Move the analytic items menu under the management section of the Accounting menu.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@vin-odoo It does appear first despite the 50 sequence.  But it seems fine that way.

**Comment by vin-odoo** [comment]
@jco-odoo it shouldn't :thinking: and I tried when I did that change 
image

**Comment by jco-odoo** [comment]
@vin-odoo 
Screenshot from 2022-09-26 10-11-43

https://19575876-16-0-all.runbot110.odoo.com/web#action=592&model=account.journal&view_type=kanban&cids=1&menu_id=632

(Maybe I am testing in an older runbot)

**Comment by vin-odoo** [comment]
@jco-odoo Yes this runbot is the oldest one, the sequence was added based on Benj feedback so it has to be tested on the latest build :)

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
