### PR TITLE
[CLA] signature for suker

### PR DESCRIPTION
**Pull request by suker**
This PR is created in order to sing the odoo CLA and contribute to Odoo.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by suker** [comment]
needed for https://github.com/odoo/odoo/pull/168142

**Comment by mart-e** [comment]
@suker you can integrate it in #168142 directly. Just wait that #167808 is merged to 17.0 and rebase your pr (which needs to be rebased anyway)

**Comment by suker** [comment]
> @suker you can integrate it in #168142 directly. Just wait that #167808 is merged to 17.0 and rebase your pr (which needs to be rebased anyway)

Hi, I already rebased,

**Comment by mart-e** [comment]
@suker not in this pr, my comment was to rebase and add your cla in #168142. This way everything is at the right place.
Closing to avoid confusion.

**Comment by suker** [comment]
> @suker not in this pr, my comment was to rebase and add your cla in #168142. This way everything is at the right place. Closing to avoid confusion.

Ok thanks, done.

**Pull request closed without merging**
