### PR TITLE
[IMP] Adding the concept of memo accounts in the CoA.

### PR DESCRIPTION
**Pull request by hbto**
Memorandum accounts are tools that Accounting people uses to classify
the elements or operations carried out by a company that do not modify
its financial structure. They are generally used to record a movement of
securities when this does not affect the financial statements of the
entity.

That is, memorandum accounts are used to reflect contingent rights and
obligations and act as memorandums, reflecting events or circumstances
that do not have a direct impact on the balance sheet, but it is
advisable to reflect on their possible future effects.

Among the most common transactions included in the memorandum accounts
are the guarantees, the tax depreciation, the securities received in
custody, the granting of bonds or guarantees, the obligations for
discounting documents and, in general, any other type of contract. that,
although it does not affect the financial and accounting structure of
the company, it is convenient to reflect for whatever reason.

Like the rest of the accounts, the order accounts are kept within a
double entry system, they must always be opened in groups of two, the
one being correlative of the other and they must necessarily have
movements and balances offset at all times.

The memorandum accounts are classified into three types:

- Quotas, such as guarantees, litigation, bonds or financial
derivatives.
- Reminders and administrative controls, such as the goods in
consignment or the issuance of stock obligations.
- Fiscal/Taxatable, such as depreciation of amortization, non-deductible
expenses, fully depreciated assets or tax losses.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hbto** [comment]
@nhomar I have rebased because it was a non-related error.

**Comment by hbto** [comment]
Hi @gdgellatly thanks for you valuable input in this subject.

We have been using the memo accounts - the name, by using the same infrastructure of regular accounts too- alongside regular accounts in case of the Tax Cash Basis Journal Entries. 

Tax Cash Basis Journal Entries do not provide a sustancial value to the accounting process - the debit and credit entries with same amount related to the `cash_basis_base_account_id  - Base Tax Received Account` in tax - but as a technical workaround of reporting taxes properly and all the related process.

By your suggestion of making restrictions on the use of them in separated Journals we could be losing the opportunity of having their use alongside regular accounts. Yet your concern is quite valid.

Another exceptional use of them - memo accounts - has been when trying to initialize for example - inventory, receivables, payables and all the sorts of entries that are needed when migrating from another accounting system. I use them to counterpart their debits and credits. At the end of initialization memo accounts are balanced and so the Trial Balance.

So in this first approach it would be wonderful to have the concept of them at least which in Odoo is currently lacked - because right now the are forming part of the Trail Balance in Odoo core reports.

The first approach could be:
-  to add their type, and 
- do not include memorandum in the Trail Balance at least.

Regards.

**Comment by gdgellatly** [comment]
@hbto 

IRT the cash basis entries - I think this is more a case of an accrual or provision rather than a memo account, as your financial statements would want to reflect the actual tax liability in the correct period. There is no reason for that amount to be off balance sheet.

IRT to initial balances, again there is no good reason to use a memo account. You simply need to make the counterpart itself so as to have a net zero effect on your account balances and then set opening balances. In the alternative, a common procedure would be to use a suspense account which is indirectly a balance sheet account for this purpose.

By way of example
DR Debtors - Partner A 100
DR Debtors  - Partner B 200
CR Debtors - 300

Opening Balance entry
DR Debtors 300
...(other entries)

Reconcile off the 2 entries with no partners if you wish. You are left with balances of 100 and 200 respectively for the partners and a correct opening balance and aging.

A true memo account can never be a counterpart to a regular account.  In addition, if you look at major systems that support this, memo accounts are allowed single sided entries. This must be, take a simple scenario, a company has accrued 100,000 of imputation credits. Those credits have no counterpart, at least within the entity, as they are for allocation and passthrough to shareholders.

Contingent assets would be another good example, where you could arguably have a counterpart, but it doesn't make much sense (as it would be reserves)

Or an asset valuation for PPE when testing for impairment. You may wish to maintain a record of both FVLCOD and VIU even if not impaired. There is no logical counterpart to that entry.

**Comment by luistorresm** [comment]
Hello @nim-odoo 

What do you think about this PR?

Regards

**Comment by smetl** [comment]
@avw-odoo PR about `Memorandum` account type. Can you have a look plz?

**Comment by nhomar** [comment]
ping @avw-odoo @nim-odoo 

this closes opw-2008712

**Comment by smetl** [comment]
@jco-odoo

**Comment by qdp-odoo** [comment]
we have now the off-balance accounts, so I believe this is no longer a problem

**Pull request closed without merging**
