### PR TITLE
[REF] base: add _is_public on partner

### PR DESCRIPTION
**Pull request by fmdl**
To be use in mail, ... and prevent issue with archived partner

@seb-odoo an idea for master

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
Could you maybe use it in code where it makes sense so that we can see why it would be useful?

**Review by seb-odoo — CHANGES_REQUESTED** [review]

**Review by seb-odoo — APPROVED** [review]
Thanks for the updates, looks ok to me now.
@tde-banana-odoo did you want to have a final check here?

**Comment by seb-odoo** [comment]
@tde-banana-odoo friendly reminder for this small change

Also side question: shouldn't we make this a computed field instead of a method to call?

**Comment by tde-banana-odoo** [comment]
We could probably make it a field, and benefits from the cache probably.

**Review by seb-odoo — APPROVED** [review]
Thank you

@robodoo r+

**Pull request closed without merging**
