### PR TITLE
[FIX] models: in `recompute`, guard against recursive recomputations

### PR DESCRIPTION
**Pull request by rco-odoo**
The issue occurs when a compute method explicitly writes on records other than
the ones to be computed.  The scenario goes as follows:
- some update invokes method `recompute`;
- the method `recompute` selects `f` to be recomputed on `recs`;
- the compute method of `f` explicitly writes on other records;
- the latter update invokes method `recompute`;
- the method `recompute` selects `f` to be recomputed on `recs`;
- ...

This leads to an infinite recursion, because the field `f` is marked as done on
`recs` after being computed and stored in database.  The fix simply avoids
recursive calls to `recompute` in compute methods; all the recomputations are
done by the outer call to `recompute`.

### CODE REVIEW

**Comment by rco-odoo** [comment]
@odony @KangOl you are welcome to review this one.

**Comment by KangOl** [comment]
Maybe add a testcase?
(admitting it was raising a `RuntimeError` and not looping indefinitely)

**Comment by rco-odoo** [comment]
This patch looks a bit risky on a stable version.
Moreover, it makes the ORM more tolerant about bad practice.

**Comment by C3POdoo** [comment]
Dear @rco-odoo,

Thank you for your contribution but the version 9.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
