### PR TITLE
[IMP] web,*: removes jQuery.browser

### PR DESCRIPTION
**Pull request by pparidans**
Enterprise PR: https://github.com/odoo/enterprise/pull/46736

task-3439226

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pparidans** [comment]
@odoo/rd-website It's me again...
Love to have your feedback on this PR (specially the commit about the `data-browser` attribute).

Note: this may seem "ballsy" but I honestly think we don't need this kind of user agent sniffing in 2023 (or have other tools based on feature detection to handle edge cases).

**Comment by pparidans** [comment]
@rdeodoo Found out the commit introducing the code removed and added to the commit message :+1:

**Review by adr-odoo — APPROVED** [review]
@robodoo rebase-ff r+

**Comment by rdeodoo** [comment]
I guess you don't need our feedback anymore :shrug:

**Pull request closed without merging**
