### PR TITLE
[FIX] sale_timesheet: prevent deleting service on timesheet

### PR DESCRIPTION
**Pull request by tivisse**
This commit prevents a user from deleting or archiving the default
"Service on Timesheet" product.

Before this commit, the users were receiving a constraint violation
error.

TaskID: 2221046

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@SimonGenin @kba-odoo FYI it looks like is_test_mode is not handled for TransactionCase, but only for HttpCase.

This seems to work
``` python3
test_mode = getattr(threading.currentThread(), 'testing', False) or self.env.registry.in_test_mode() 
```

**Comment by tivisse** [comment]
@robodoo r+

**Comment by SimonGenin** [comment]
> @SimonGenin @kba-odoo FYI it looks like is_test_mode is not handled for TransactionCase, but only for HttpCase.
> 
> This seems to work
> 
> ```python
> test_mode = getattr(threading.currentThread(), 'testing', False) or self.env.registry.in_test_mode() 
> ```

Good to know, thanks !

**Pull request closed without merging**
