### PR TITLE
[IMP] mail: introduce ChannelMemberView

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2864119

### CODE REVIEW

**Comment by phenix-factory** [comment]
There is a traceback on runbot: 

```
TypeError: ctx.member is undefined
    template@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js line 1583 > Function:13:17
    onWillRender/node.renderFn@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1176:210
    onRendered/node.renderFn@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1177:207
    _render@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1092:96
    render@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1091:6
    initiateRender@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1132:47
```

**Comment by alexkuhn** [comment]
> There is a traceback on runbot:
> 
> ```
> TypeError: ctx.member is undefined
>     template@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js line 1583 > Function:13:17
>     onWillRender/node.renderFn@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1176:210
>     onRendered/node.renderFn@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1177:207
>     _render@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1092:96
>     render@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1091:6
>     initiateRender@https://16347803-master-all.runbot77.odoo.com/web/assets/1691-9c7c03a/web.assets_common.min.js:1132:47
> ```

Should be good now.

I removed `member` as prop passed to `ChannelMember` component, but the component itself was still relying on it.
`ctx.member` was due to getter `member` being on `props.member`, which was no longer used.

Now it uses `record.partner` instead, record being `ChannelMemberView`. So `ChannelMemberView/partner` is equivalent to `member`.

**Review by phenix-factory — APPROVED** [review]
LGTM

**Comment by alexkuhn** [comment]
Moved to grouped PR: https://github.com/odoo/odoo/pull/93330

**Pull request closed without merging**
