### PR TITLE
[FIX] web,  mail:  `dropdown` and `popover` design

### PR DESCRIPTION
**Pull request by stefanorigano**
This PR enhances visual contrast by making adjustments to various components
and utility classes.

`o-mail-ActivityGroup` and `o-mail-NotificationItem` templates have undergone
revisions to utilize default Bootstrap (BS) components and, consequently,
 automatically inheriting the fixed design.

image

task-3338419
part-of: task-3326263

required-by:
- https://github.com/odoo/enterprise/pull/41542

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @brboi could you have a look at [eb3aa5d](https://github.com/odoo/odoo/pull/122615/commits/eb3aa5dde741515b64ddf4c1c1321cbb32925bee)?
Thanks!

**Comment by brboi** [comment]
> Hello @brboi could you have a look at [eb3aa5d](https://github.com/odoo/odoo/pull/122615/commits/eb3aa5dde741515b64ddf4c1c1321cbb32925bee)? Thanks!

Hello @stefanorigano !

We are refactoring the dropdown component in order to reduce the number of props it has.

Could you explain or show a screenshot of what you are trying to solve here ?

Do you want in most of simple cases a margin of 4px between the toggler and the menu ?

If not maybe you could solve this through some styling of the togglers ?

I simply checked the user menu and it seems than the toggler's does not fit its content
image


Maybe a `height: fit-content;` or something like that (you are the CSS professionnal, not me :-D ) could solve this ?

If I misunderstood the problem here, maybe we should try to use the onPositioned callback instead and with some heuristic we could be able to keep the logic internally instead of exposing another prop.

**Comment by brboi** [comment]
@stefanorigano yes of course ! Glad it works out for you ;-)

**Review by alexkuhn — APPROVED** [review]
LGTM for `mail/` part :)

**Comment by stefanorigano** [comment]
@brboi , green on runbot 👍

**Comment by stefanorigano** [comment]
Hello @brboi 👋
Rebased and green on runbot, thanks!

**Pull request closed without merging**
