### PR TITLE
[REF] server: remove the openerp-gevent file

### PR DESCRIPTION
**Pull request by sle-odoo**
- use a special arg in odoo.py
- note that the previous implementation was relying on the fact that
  the openerp-gevent file was located in the same directory than the
  odoo.py file. This was no longer true since rev a0eb172cab590982168492ad16ad90c2228c6424
  This commit brings back this behavior.

### CODE REVIEW

**Comment by antonylesuisse** [comment]
Cool

**Comment by flotho** [comment]
Hi @sle-odoo , I tried to build a rpm from your PR without success : https://github.com/odoo/odoo/pull/10150#issuecomment-167799282
Any advice?

**Comment by lepistone** [comment]
Hi @sle-odoo @antonylesuisse. This is for master, and still unmerged. Could you consider proposing that for v9, or even better, reverting a0eb172cab590982168492 ?

Docker, debian and redhat builds are broken because of this.

Thanks!

**Comment by mlaitinen** [comment]
Can't really run Odoo v9 Enteprise with `workers > 0` without this. Or is there a workaround?

**Comment by yelizariev** [comment]
Workaround:

    cd /usr/bin/
    wget https://raw.githubusercontent.com/odoo/odoo/9.0/openerp-gevent
    chmod +x openerp-gevent

https://odoo-development.readthedocs.io/en/latest/admin/longpolling.html

**Comment by mlaitinen** [comment]
Merged to `saas-13`? Not `9.0`? Not even `master`?

Multiprocess mode is recommended by Odoo S.A. to be used in production environments. It's beyond me why we have to use hacky workarounds with all of our 9.0 production enviroments. Is the official Odoo Docker image intended for development purposes only?

**Comment by sle-odoo** [comment]
@mlaitinen saas-13 commits will be forward-ported to master, but you're not talking about the same issue: since c12c097655a4f770281dfdf5bb35657080abcd7b openerp-gevent that was wrongly removed from the scripts has been added again, so the issues concerning the availability of a script in the path to execute an evented process were all fixed.

You're talking about the fact that the python dependencies needed to run an evented process are not in the hard requirements of the debian package, so is not present in the docker image. We plan to make python-gevent an hard dependency for v10 and we'll patch the odoo 9 docker image installation to install it.

**Pull request merged**
