### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by LucasLefevre**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/296f467b9 [REL] 17.2.0-alpha.1
https://github.com/odoo/o-spreadsheet/commit/d0814d602 [FW][IMP] evaluation: functions can handle errors Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/9c1500fbc [IMP] test: fail if console.error Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/884bbbfd6 [REF] evaluation: change error objects to string errors Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/d429396c6 [REF] formulas: remove computeValueAndFormat and computeFormat Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/18d224c57 [REF] formulas: modify typing name Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/e09d6b881 [IMP] functions: accept/throw errors on specific function Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/f8bfea155 [REF] evaluation: remove lazy args in formulas Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/94f681691 [IMP] evaluation: allow formulas to handle error Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/fbe30cf34 [REF] cell evaluation: some cleaning Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/a28bf5e5a [REL] 17.2.0-alpha.0
https://github.com/odoo/o-spreadsheet/commit/02d578cc9 [FIX] Datavalidation: fix checkbox style Task: 3650740
https://github.com/odoo/o-spreadsheet/commit/93fdaae4e [REF] commands: change evaluation invalidation management Task: 3607272
https://github.com/odoo/o-spreadsheet/commit/ab7f509a2 [FIX] Cell: Fix detection of markdown links Task: 3628780

### CODE REVIEW

**Comment by LucasLefevre** [comment]
fw-bot ignore

**Comment by rrahir** [comment]
@robodoo r+

**Comment by LucasLefevre** [comment]
robodoo rebase-merge

**Comment by LucasLefevre** [comment]
robodoo r- missing enterprise PR

**Comment by rrahir** [comment]
@robodoo r+

**Pull request closed without merging**
