### PR TITLE
[IMP] mail: introduce ChatWindowManager/chatWindowWidth

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2871957

### CODE REVIEW

**Review by phenix-factory — COMMENTED** [review]
Conflict :)

**Comment by alexkuhn** [comment]
Rebased

**Review by phenix-factory — APPROVED** [review]
LGTM

**Comment by alexkuhn** [comment]
Moved to grouped PR: https://github.com/odoo/odoo/pull/93330

**Pull request closed without merging**
