### PR TITLE
[FIX] base: no back-end view caching in --dev xml mode

### PR DESCRIPTION
**Pull request by beledouxdenis**
[FIX] base: no back-end view caching in --dev xml mode

In `--dev xml` mode,
you would like the views to be loaded from their definition
in the XML file directly.

The view caching introduced in https://github.com/odoo/odoo/pull/99417 prevents that feature,
as once the view has been loaded a first time, the views are returned
directly from the cache, therefore not taking into account changes
directly done in the XML file views.

Setting a conditional decorator,
disabling the caching when in `--dev xml` mode,
solves this issue.

Solves https://github.com/odoo/odoo/pull/99417#issuecomment-1241977197

[IMP] base: move view related methods out of odoo/models.py

By definition, views are useless without the web client.
The web client is in the module `web`.
Therefore, in a perfect world, the `get_views` model method
and any related method should be within the `web` module,
as without it they are useless.

Let's imagine you would like to use fully in command-line,
without web client, all those view related methods are useless.

Maybe excepted for reports, as you might still like to be
able to print reports while using odoo fully in command line.

Views related method therefore shouldn't be in `odoo/models.py`.

Also, when you think about it, `get_views` related methods do not
make sense without the model `ir.ui.view`, which is loaded after
the `get_views` related methods, which also doesn't make sense.

However, moving these methods fully in the `web` module is an harder
work. For instance, there are base models, such as res.partner,
already overriding `get_view` in the `base` module,
and therefore relying on these view related methods.

As a first step, we move view related methods direcly in the
`odoo/addons/base/models/ir_ui_view.py` file, where
the `ir.ui.view` model is loaded.

This is not only a design / cleaning change,
but a required change to be able to use content of
`odoo.tools.config`, which is loaded after `odoo/models.py`.
For instance, if you want to configure a conditional decorator based on
the config `odoo.tools.config['dev_mode']`, it is not possible
to do so in `odoo/models.py` because the config is parsed/loaded
after `odoo/models.py`.
The config is loaded here:
https://github.com/odoo/odoo/blob/31de2b0a7a0921cab3c6c54045d15da46c8e6d8a/odoo/cli/server.py#L127
While, within the same file, `odoo/models.py` gets loaded through the
`import odoo`
https://github.com/odoo/odoo/blob/31de2b0a7a0921cab3c6c54045d15da46c8e6d8a/odoo/cli/server.py#L26

And we would like to put such a decorator based on `odoo.tools.config['dev_mode']`
on `_get_view_cache`, to not cache the back-end views when `--dev xml` is
passed in the server arguments.

### CODE REVIEW

**Comment by beledouxdenis** [comment]
@rco-odoo Do you think this could be considerable or it's a very bad idea ?

**Comment by Xavier-Do** [comment]
ir_ui_view file is already quite large

I would move the _inherit = 'base' stuff in another file since it not immediately ir_ui_view related. 

base.py?

**Comment by beledouxdenis** [comment]
> ir_ui_view file is already quite large
> 
> I would move the _inherit = 'base' stuff in another file since it not immediately ir_ui_view related.
> 
> base.py?
> 
> It will also help if we decide to move this logic elsewhere later.

Could be, I thought about it, even `models.py`, but then I considered the below:
- I would like to group model view-related methods in one file only, so for the future it will be easier/quicker/cleaner when we want to move out these methods into the `web` module.
- As these methods are directly related to views, to me it can be added along `ir.ui.view`. Besides, I still believe it makes much more sense to "load" these methods only once the model `ir.ui.view` is loaded, as these methods does not make sense without the `ir.ui.view` model, it even depends on it (not at loading but at running it does).

So, put them in a file `base.py` would mean we would again load these methods before the `ir.ui.view` model is loaded, or if we put it lower in the `__init__.py` list, after `import ir_ui_view`, then it means it doesn't really make sense to add other model related methods which are not views related in this file, hence it shouldn't be called `base.py` or `models.py`.

**Comment by Xavier-Do** [comment]
> - As these methods are directly related to views, to me it can be added along `ir.ui.view`. Besides, I still believe it makes much more sense to "load" these methods only once the model `ir.ui.view` is loaded, as these methods do not make sense without the `ir.ui.view` model, they even depend on it (not at loading but at running they do).

Since they don't depend on loading they can technically be before the import of ir_ui_view. Since they are in the same module they would be loaded together anyway. Following this logic `ir.actions.act_window` should be defined in the same file too because it's using the views ;). 

Having this in a separate file and adding all the base stuff with one '_inherit' should simplify the mro of all models, this is mainly why I think it would be better. In this case it could be also combined with the O2MIdMapper

Anyway this is just a suggestion.

**Comment by beledouxdenis** [comment]
Well I will wait for a 3rd opinion, and it doesn't arrive soon enough I will put everything in `base.py`, I just want to move on as quick as possible.

**Review by rco-odoo — APPROVED** [review]
Looks good to me.
Moving the "view-related stuff" right next to `ir.ui.view` makes sense to me.
Moving it to a file like base.py instead will be more confusing IMHO.
Grouping by feature looks more sensible to me than grouping by model name.

**Comment by rco-odoo** [comment]
> Could be, I thought about it, even `models.py`, but then I considered the below:
> 
> * I would like to group model view-related methods in one file only, so for the future it will be easier/quicker/cleaner when we want to move out these methods into the web module.
> * As these methods are directly related to views, to me it can be added along ir.ui.view. Besides, I still believe it makes much more sense to "load" these methods only once the model `ir.ui.view` is loaded, as these methods do not make sense without the ir.ui.view model, they even depend on it (not at loading but at running they do).
> 
> So, put them in a file `base.py` would mean we would again load these methods before the `ir.ui.view model`, or if we put it lower in the `` __init__.py`` list, after ``import ir_ui_view`, then it means it doesn't really make sense to add other model related methods which are not views related in this file, hence it shouldn't be called `base.py`or`models.py`.

The "loading order" argument is ridiculous to me, since none of these methods is invoked before all models in the module are build.  This argument would prevent any definition of mutually recursive functions/methods, which the framework is plenty of.  The _only_ exception to the loading order is that the _very first_ model being defined must be model `base`, because it is implicitly inherited by all other models.  But the only thing that is required at that point is its _class_, not business/feature-related methods.

My opinion is: grouping code by feature (views) is a good idea in terms of readability.

**Comment by beledouxdenis** [comment]
robodoo override=ci/security
The sensitive code is just moved from one file to another without any change.

**Comment by beledouxdenis** [comment]
robodoo rebase-ff

**Comment by beledouxdenis** [comment]
robodoo r+

**Pull request closed without merging**
