### PR TITLE
[FIX][IMP] l10n_ar: account groups

### PR DESCRIPTION
**Pull request by bruno-zanotti**
**Description of the issue/feature this PR addresses:**
- Fix: Create again the removed account group "Otros créditos"
- Imp: move account groups data to a CSV template

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vbe-odoo** [comment]
Ready for technical review @jco-odoo 
Thanks!
cc' @Bruno-Zanotti @ren-odoo

**Comment by jco-odoo** [comment]
@Bruno-Zanotti lgtm, but can you do a rebase with 14.0 (to make the checks pass) ?

**Comment by Bruno-Zanotti** [comment]
@jco-odoo done the rebase

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
