### PR TITLE
[FIX] mrp: is_kits Multicompany

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
ammending https://github.com/odoo/odoo/pull/174006/commits/50c9c3d55a5ab2a023f6ff7fdbafa6b39cec5e4f to take into account env.company instead of companies

### CODE REVIEW

**Comment by HANNICHE-Walid** [comment]
@robodoo disable

**Comment by HANNICHE-Walid** [comment]
@robodoo fw=no

**Comment by adwid** [comment]
robodoo r+

**Comment by adwid** [comment]
Note: FW disabled, initial patch improved during its own FW (see https://github.com/odoo/odoo/pull/174233)

**Pull request closed without merging**
