### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by pro-odoo**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/15fd5a88f [REL] 17.5.0-alpha.2 Task: 0
https://github.com/odoo/o-spreadsheet/commit/0a070fc9e [IMP] pivot: support multiple measures Task: 4001750
https://github.com/odoo/o-spreadsheet/commit/33c82be44 [FIX] composer: remove now useless try/catch Task: 4045550
https://github.com/odoo/o-spreadsheet/commit/3e7bc74a1 [IMP] cf panel: improve layout on panel resize Task: 4045550
https://github.com/odoo/o-spreadsheet/commit/b6be223af [REF] composer: rename ComposerStore to CellComposerStore Task: 4045550
https://github.com/odoo/o-spreadsheet/commit/d528a2801 [IMP] composer: add standalone composer Task: 4045550
https://github.com/odoo/o-spreadsheet/commit/66e523f45 [IMP] composer: stop composition on blur Task: 4045550
https://github.com/odoo/o-spreadsheet/commit/88827233b [IMP] pivot: allow to rename measure dimension Task: 4061062
https://github.com/odoo/o-spreadsheet/commit/6c093f890 [FIX] types: export type MigrationStep Task: 0
https://github.com/odoo/o-spreadsheet/commit/446b767c6 [FIX] pivot: preserve sorting on dimension reorder Task: 4050440
https://github.com/odoo/o-spreadsheet/commit/de4632ae8 [IMP] icons: add unhide col/row icons Task: 3863473
https://github.com/odoo/o-spreadsheet/commit/8c9a139c2 [REF] compiler: compile no longer throws any errors Task: 4049824
https://github.com/odoo/o-spreadsheet/commit/190765b89 [FIX] pivot: change `measureName` to `measureId` Task: 0
https://github.com/odoo/o-spreadsheet/commit/94546f24a [FIX] grid_overlay: A1 is hovered by default Task: 4042621

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by pro-odoo** [comment]
robodoo fw=no

**Comment by pro-odoo** [comment]
robodoo rebase-merge

**Comment by pro-odoo** [comment]
@robodoo override=ci/style
Override because the terms which trigger the warnings are used for custom class names or directly in inlined css.

**Review by LucasLefevre — COMMENTED** [review]
robodoo r+

**Pull request closed without merging**
