### PR TITLE
[FIX] core: always evaluate field.depends upon setup

### PR DESCRIPTION
**Pull request by rco-odoo**
This is necessary when field dependencies are given by a callable.  This
functionality was broken with the support for an explicit parameter
`depends` in the fields' definition, because the implementation could
not distinguish between the field parameter `depends` and the `depends`
evaluated from compute functions.

The fix consists in storing the field parameter `depends` into
`field._depends`, and the result of the setup into `field.depends`.

### CODE REVIEW

**Comment by xmo-odoo** [comment]
I don't think I get what the original issue was, or how this fixes it.

Before an explicit depends would be stored in `self.depends`, and if that was missing then it would be fetched from the computation function instead. Now... it's the same except we store the explicit depend in `_depends` instead?

**Comment by rco-odoo** [comment]
@xmo-odoo does the test make it clearer?

**Comment by xmo-odoo** [comment]
@rco-odoo your explanation was sufficient, dunno if you saw my question though: why not leave the depends parameter on `self.depends` and move the "resolved" internal one to `_depends`, would require more edition sites?

**Comment by rco-odoo** [comment]
> why not leave the depends parameter on `self.depends` and move the "resolved" internal one to `_depends`, would require more edition sites?

Your guess is correct.  I also found it more intuitive to use `field.depends` for the "resolved" dependencies, which are the ones you generally care about, while `field._depends` is only used to determine `field.depends`.  I was using a similar trick for `digits` in float fields, but the `digits` property eventually became the explicit method `get_digits()`.

**Review by xmo-odoo — APPROVED** [review]
WFM then

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
