### PR TITLE
Remove deprecated functions, methods, and features from 15.0 and earlier

### PR DESCRIPTION
**Pull request by xmo-odoo**

### CODE REVIEW

**Review by rco-odoo — APPROVED** [review]
@robodoo rebase-ff r+

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by Julien00859** [comment]
When I tried to remove `except_orm`, `except_osv` and the `osv` module two years ago I had to restore it due to `saas_worker`. Did the situation changed since then? cf #49603

**Comment by xmo-odoo** [comment]
> When I tried to remove `except_orm`, `except_osv` and the `osv` module two years ago I had to restore it due to `saas_worker`. Did the situation changed since then? cf #49603

`saas_worker` doesn't seem to have any mention of `except_orm`, though other internal modules do. I can submit a fix for that tho.

**Pull request closed without merging**
