### PR TITLE
Rename field name "user"

### PR DESCRIPTION
**Pull request by rop-odoo**
Task: https://www.odoo.com/web#id=1911988&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
https://github.com/odoo/odoo/pull/27905

**Comment by mart-e** [comment]
@rop-odoo could you check if this task was moved or cancelled? The task-id 1911988 is about another issue.

**Comment by pedrobaeza** [comment]
@mart-e this PR has appeared to me from codetriage.com, and seeing that no answer and the other linked PR, I would bet for closing it.

**Comment by mart-e** [comment]
Yes, I agree, as this kind of renaming tends to bring bugs without solving any real issues, let's close it.

**Pull request closed without merging**
