### PR TITLE
Add contribution section to the README

### PR DESCRIPTION
**Pull request by melroy89**
Add a link to the contributing file.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by danger89** [comment]
I did sign the CLA? https://github.com/odoo/odoo/blob/11.0/doc/cla/individual/danger89.md

Why does the CLA check fails... 😢

**Comment by Yenthe666** [comment]
@danger89 you're using the CLA from OCA, not from Odoo.
Please use the template at https://github.com/odoo/odoo/blob/11.0/.github/ISSUE_TEMPLATE.md

**Comment by danger89** [comment]
@Yenthe666 Nope, I was using the correct one. But somehow I'm now using a different e-mail address.

**Comment by mart-e** [comment]
When you create a new pull request you see this warning

screenshot-2018-1-11 odoo odoo

There is a CONTIBUTING.md file at the root of the repository
If you open the wiki, it is the first link you see.

At one point, if people don't read it, I don't think adding more link will help 😉 

For the CLA, indeed you need to check you are making commits with the same email address than the one you used to sign.

**Pull request closed without merging**
