### PR TITLE
[UPD] crm: fill lead title & function on onchange

### PR DESCRIPTION
**Pull request by rdeheele**
fill crm.lead title & function fields on onchange_partner_id

### CODE REVIEW

**Comment by rdeheele** [comment]
opw 629375

**Comment by rdeheele** [comment]
@beledouxdenis Is this change will go up in 8.0? thanks.

**Comment by beledouxdenis** [comment]
Yes indeed, 7.0 fixes are regularly ported to Odoo 8.0.

Did I forget to mention that in my reply in the opw ticket ?

**Comment by rdeheele** [comment]
thanks @beledouxdenis you've mentioned it in the opw ticket, sorry for the noise.

**Pull request closed without merging**
