### PR TITLE
getting updates 

### PR DESCRIPTION
**Pull request by MjAbuz**
Description of the issue/feature this PR addresses: 
getting updates, singed cla @MjAbuz <azmikbal@gmail.com> 

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MjAbuz** [comment]
check the fix here  [FIX] auth_signup, website, base: identical logins https://github.com/odoo/odoo/commit/210098ecaf15dec7d6b1f4fb85d6838329be8a30 
#5bf911f

**Comment by MjAbuz** [comment]
Bump lxml from 4.3.2 to 4.6.2

1 lxml vulnerability found in requirements.txt 11 minutes ago
Remediation

Upgrade lxml to version 4.6.2 or later. For example:

lxml>=4.6.2

**Review by MjAbuz — COMMENTED** [review]
removed

**Comment by seb-odoo** [comment]
> Bump lxml from 4.3.2 to 4.6.2
> 
> 1 lxml vulnerability found in requirements.txt 11 minutes ago
> Remediation
> 
> Upgrade lxml to version 4.6.2 or later. For example:
> 
> lxml>=4.6.2

Hello,

I think you messed up your rebase, but if there is a security report to make, please see guidelines on https://www.odoo.com/security-report

cc @odoo/rd-security

**Pull request closed without merging**
