### PR TITLE
[IMP] fields: remove support for non-string selections

### PR DESCRIPTION
**Pull request by xmo-odoo**
Task https://www.odoo.com/web#id=1911598&model=project.task&menu_id=4720

### CODE REVIEW

**Comment by rco-odoo** [comment]
@KangOl thanks for pointing that out, I haven't checked it.

**Comment by rco-odoo** [comment]
@KangOl I don't understand. IMHO, there is not point using the **boolean** widget with a **selection** field. The boolean widgets are aimed a boolean fields only.

We have used selection fields in place of boolean fields in the configuration wizard. The point was to use the radio button widget. This one works as expected.

**Comment by pedrobaeza** [comment]
@gurneyalex you had several reasons for using selection with integers instead of strings, do you?

**Comment by gurneyalex** [comment]
@pedrobaeza yes, interfacing with external systems which use enums. There are lots of these in the wild. The support was badly broken with "0" being not usable (displayed as unset, in Odoo), we ended up using stringified integers and adding int(val) and str(val) all over the place to parse / generate  the expected values.

**Comment by rco-odoo** [comment]
@pedrobaeza @gurneyalex the purpose of this task is definitively to simplify things, and remove a feature that is both fragile and error-prone. See #28877 and #28891 for fixing such a terrible programming error.

**Comment by rco-odoo** [comment]
@KangOl are you okay with merging this?

**Comment by KangOl** [comment]
Yes.

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
