### PR TITLE
Forward Port of #37719 to 13.0

### PR DESCRIPTION
**Pull request by len-foss**
[FIX] account_facturx: handle attachment both as records and as named tuples

The attachment of a mail can be either a named tuple or an Odoo record.
In the second case, it has more attributes such as a mimetype.
In the first case, the mimetype should be guessed from the content.
We clean up to use the helper functions in all cases.

opw 2075933

Forward-Port-Of: #37719

### CODE REVIEW

**Comment by len-odoo** [comment]
Hello @smetl 
When we discussed about this module last time you told me that the helpers to handle attachments as named tuples weren't needed anymore in v13.
However I can see that the helpers are still there in v13. And the named tuples still exist in v13, so they are certainly still necessary.
I see that the part about the mimetype helper db8eef5484ed3c173c7fc603d5ba97a9d8588a76 was not put in v13, so I have you clarified in which cases it is necessary or not?

**Comment by Elkasitu** [comment]
Nice try, you're not @fw-bot, this is an illegal forward-port :police_car:

**Comment by smetl** [comment]
@len-odoo I had something going in that way in my mind ... 
It seems the attachment is always an instance of ir.attachment since https://github.com/odoo/odoo/commit/5cf9d55bbce2e7e8b593e2c9cd178b6fc9d32c29

**Comment by smetl** [comment]
@len-odoo It seems there was no proper cleaning about nametuple stuff...

**Comment by len-odoo** [comment]
@smetl 
Great, thank you very much. With this there's only some cleanup left in the PR.

**Comment by len-odoo** [comment]
robodoo rebase-ff r+

**Pull request closed without merging**
