### PR TITLE
[FIX] stock: vendor exception on run scheduler

### PR DESCRIPTION
**Pull request by mgh-odoo**
**Task**: https://www.odoo.com/web#id=2007559&model=project.task&menu_id=4720
**Pad**: https://pad.odoo.com/p/r.ef6283c26aa78fbb34fe338ed5824b65

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
robodoo r+

**Comment by rdeodoo** [comment]
@amoyaux Task is set as merged but this PR is stuck in error

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
robodoo retry

**Pull request closed without merging**
