### PR TITLE
[FIX] l10n_dk: fix some accounts' type

### PR DESCRIPTION
**Pull request by MuhamedAbdallaMuhamed**
[FIX] l10n_dk: fix some accounts' type

Some accounts are set as "Expense" but it should be "Cost of revenue"

Change them to 'expense_direct_cost' type

task-id#3983710

enterprise-pr#[66202](https://github.com/odoo/enterprise/pull/66202)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by RicGR98 — APPROVED** [review]
Thanks for the PR :sun_with_face: 

@robodoo r+

**Comment by muab-odoo** [comment]
@robodoo retry

**Comment by muab-odoo** [comment]
@robodoo retry

**Comment by muab-odoo** [comment]
@RicGR98 Please, Can you take another look and r+ (odoo-pr & enterprise-pr)?
The merge was throwing error because of l10n tests that isn't running when when having an odoo-pr only. So, I had to create an enterprise-pr and fix the test.

**Comment by RicGR98** [comment]
@robodoo r+

**Pull request closed without merging**
