### PR TITLE
[IMP] stock: clean useless field

### PR DESCRIPTION
**Pull request by amoyaux**
clean commit bef1765b197a9e9d510a7d20d0364333402473b0

### CODE REVIEW

**Comment by amoyaux** [comment]
robodoo r+

**Comment by smetl** [comment]
@robodoo r-
@amoyaux This has been made for a reason. If you remove this key, provide a workaround for `l10n_mx_edi_stock`.

**Comment by william-andre** [comment]
I added a commit that ensures that the mergebot doesn't let this happen in the future

FYI @d-fence

**Comment by william-andre** [comment]
@antonylesuisse Again another case: https://github.com/odoo/odoo/pull/80988#issuecomment-988738201

**Comment by amoyaux** [comment]
@william-andre @smetl We already discuss it with @hpr-odoo on discord and he was doing the PR for l10n. Also I asked for a clean in the forward port and you should have handle it at that time.

**Comment by william-andre** [comment]
> We already discuss it with ayh on discord and he was doing the PR for l10n

Why would you not do it together? This is just prone to forgetting to merge the other PR. It also makes it harder to read the history and review.
Try merging now :slightly_smiling_face: https://runbot.odoo.com/runbot/batch/688470/build/12011116

**Comment by william-andre** [comment]
@d-fence @Xavier-Do Is the second commit https://github.com/odoo/odoo/pull/82312/commits/92a66e62af8aa192e0366c02b1c8f89092a9f6a7 good for you?

**Review by william-andre — APPROVED** [review]

**Comment by william-andre** [comment]
Thanks @amoyaux :slightly_smiling_face:

**Comment by william-andre** [comment]
Nice touch @pimodoo 
image

I'm going to fight for that twice as hard now :)

**Review by Xavier-Do — APPROVED** [review]
LGTM for the test reports part.

**Comment by william-andre** [comment]
@robodoo r+

**Comment by william-andre** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
