### PR TITLE
[FIX] web: allow custom filters by ID interval

### PR DESCRIPTION
**Pull request by yelizariev**
Infinite number of records cannot be exported, so after some limit we will get a
timeout error. If you need to export more records than that limit, you should be
able to filter records into batchehs. The easiest way to do it is making a
filter by ID:

```
[Y| ID Greater than 100000] [Y| ID less than or equal to 200000]
```

---

opw-2517946

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by aab-odoo — APPROVED** [review]
No need to change for this one, but next time please try to use `const` everywhere and `let` where you can't (instead of `var`). Also, we encourage the notation `this.fields.id_field` over `this.fields['id_field']`

**Comment by yelizariev** [comment]
> No need to change for this one, but next time please try to use `const` everywhere and `let` where you can't (instead of `var`). Also, we encourage the notation `this.fields.id_field` over `this.fields['id_field']`

Noted. It was modified copy-paste from nearby test

**Comment by yelizariev** [comment]
r+ ?

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
