### PR TITLE
[FIX] sale: Wrong argument in untaxed_amount_to_invoice computation

### PR DESCRIPTION
**Pull request by rousseldenis**
@nim-odoo We did it too fast :-(

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nim-odoo — APPROVED** [review]
robodoo r+

**Comment by rousseldenis** [comment]
> robodoo r+

@nim-odoo I put a task for me to write a test for that.

**Comment by nim-odoo** [comment]
BTW I closed all the forward-ports of the first PR, I will handle the conflict in 12.3.

**Comment by nim-odoo** [comment]
robodoo p=0

**Pull request closed without merging**
