### PR TITLE
[IMP] Improve stock valuation view performance by 4

### PR DESCRIPTION
**Pull request by nseinlet**
[IMP] Improve stock valuation view performance by 4 on my use case (huge dataset)
- Using INNER JOIN instead of left join for required fields
- Using BIGINT id instead of Text
- Remove unused field

The main performance improvement comes from the BIGINT id

### CODE REVIEW

**Comment by odony** [comment]
What about the UNION -> UNION ALL change, in terms of perf impact?

**Comment by nseinlet** [comment]
small, on my use case, from 20 to 19,5 minutes .

**Comment by beledouxdenis** [comment]
Besides, even if they are correct, does have the changes:
 - `LEFT JOIN` to `INNER JOIN`
 - The replace of implicits joins 
   ```
   stock_quant_move_rel.quant_id = quant.id AND stock_quant_move_rel.move_id = stock_move.id
   ```
   to INNER JOIN
real impacts on the performance ?

If not, they should probably be done in a separate commit, as they do not really solve the issue in the first place.

**Comment by nseinlet** [comment]
on this use case, as the fields are required it seems correct,and time goes from 5 to 4.5 min with inner join 's.

**Comment by beledouxdenis** [comment]
Closed with 29bd62252158803cdad351a2966af6eeac4cca74 & https://github.com/odoo/odoo/commit/5c9897a83f79834b5c54a79b944262556e3f87ee.

**Pull request closed without merging**
