### PR TITLE
[FIX] web_editor: hide trash button on snippet move

### PR DESCRIPTION
**Pull request by IT-Ideas**
task-2312878

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ThanhDodeurOdoo** [comment]
@IT-Ideas I think you can also hide the arrow buttons:
https://github.com/odoo/odoo/blob/saas-13.2/addons/website/views/snippets/snippets.xml#L234-L244

**Comment by IT-Ideas** [comment]
Hey @ThanhDodeurOdoo ,
Good point, I made the proposed change.

**Comment by IT-Ideas** [comment]
Also rebased in saas-13.5

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
