### PR TITLE
Basic spelling and grammar corrections.

### PR DESCRIPTION
**Pull request by lathama**
Description of the issue/feature this PR addresses: Basic spelling and grammar corrections.

Current behavior before PR: Comments and output with spelling errors

Desired behavior after PR is merged: Correct majority of spelling and grammar issues. Ignoring large amount of software development and international spelling issues.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lathama** [comment]
The CLA was committed to the 11.0 branch in #20321 and I could be wrong in understanding if I should create PRs for Master or the current stable version. In other OSS work I will always work against master unless it is a regression or bug fix.

**Comment by Yenthe666** [comment]
@lathama against master is perfect for these kind of changes / fixes. 😉 
@mart-e why is the CLA failing though?

**Comment by mart-e** [comment]
The CLA is failling because your signature is not present in your branch
https://github.com/lathama/odoo/tree/spelling-odootools/doc/cla/individual/lathama.md (not found)

As always, we forward port the patches to upper branch.
The signature is now present in 11.0 main branch
https://github.com/odoo/odoo/blob/11.0/doc/cla/individual/lathama.md

soon, it will be ported to master branch
https://github.com/odoo/odoo/blob/master/doc/cla/individual/lathama.md (not yet)

Then you can rebase your branch to fetch the CLA you proposed at #20321

Regarding the target branch, it depends a bit the content.
As explained in the [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean), we merge bug fixes in stable and improvement in master.

The correction of the English content is a bit tricky as we have to take care of the translations too. If you change the source string (even for a typo), you lose the existing translations.

I would sum up as:
- 10.0 or below : no correction of translatable content (as breaking the translations), ok for untranslated (e.g. command line arguments, technical documentation,...)
- 11.0 : ok to correct the English content _now_ as a new version (still not perfectly stable)
- master: for less important changes like docstrings

I hope it is clear.
I will review your PR accordingly soon :)

**Comment by Yenthe666** [comment]
@mart-e I thought that changing comments etc in an older stable version (read 10.0) was rather not allowed for line changes etc?

**Comment by mart-e** [comment]
@Yenthe666 indeed changing comments is for master (and even, if it never appears to anyone but the developer, I prefer to pack it in bigger changes to avoid noise), that wasn't clear in my message? For v10 we can accept fixes of text that do appear to the user but is not translatable.

**Comment by Yenthe666** [comment]
@mart-e yep - all clear. I actually missed the 'no', that made me doubt it. Sorry my mistake 😉

**Comment by mart-e** [comment]
merged at b67e18bc, thanks

**Pull request closed without merging**
