### PR TITLE
[FIX] doc: explanation for pg_path

### PR DESCRIPTION
**Pull request by rim-odoo**
opw-[2060249](https://www.odoo.com/web?debug#id=2060249&model=project.task&view_type=form&menu_id=5200)

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@rim-odoo might be a good idea to note that this is only used when dumping or restoring DBs?

**Comment by rim-odoo** [comment]
@xmo-odoo Done

**Comment by xmo-odoo** [comment]
It's bioutifoulle

@robodoo r+

**Comment by rim-odoo** [comment]
@robodoo retry

**Comment by rim-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
