### PR TITLE
[FIX] stock: traceback when trying to update quantity on hand

### PR DESCRIPTION
**Pull request by Feyensv**
When accessing the quantities on hand of a product, `_get_quants_action` 
is called to specify the action returned.  

In some cases, the action context may be updated.  This led to a 
traceback because the context of the action isn't a copy of the current 
context but a link to the current context frozendict, which cannot be 
updated.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo r-

**Comment by Feyensv** [comment]
@robodoo rebase-ff

**Comment by sle-odoo** [comment]
robodoo r+

thanks

**Pull request closed without merging**
