### PR TITLE
purchase: issue a write call on warehouses at install

### LINKED ISSUE #4853: [8.0] buy rules not created for a new warehouse
To reproduce:
- start with a base 8.0 instance from runbot
- install the module **stock**
- create a new warehouse
- install the module **purchase**
- now the new warehouse has the field **Purchase to resupply this warehouse** already selected by default.

However, the "buy" procurements do not work for the new warehouse, because no procurement rules have been created for it.

Workaround: in the new warehouse, deselect and select again the **Purchase to resupply this warehouse** checkbox and save.

This does not happen with the original warehouse on a demo instance because the issue has been worked around in `addons/purchase/purchase_demo.yml`, but clearly this does not seem like a good solution.

Thanks!

### PR DESCRIPTION
**Pull request by gurneyalex**
this will force the creation of the Buy rule
closes #4853

### CODE REVIEW

**Comment by lepistone** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I don't get it: are you forcing any kind of background process rewriting again the same value in the records? Isn't better to launch directly the process implied? If ORM cache gets better and detect that there is no change in the data (you write again True value), triggers will be no raised, so this won't work.

**Comment by gurneyalex** [comment]
@pedrobaeza no, I'm just forcing at module install time a call to the write method of stock.warehouse, to trigger the specific code in there. I have to do this becase the True value is set at module installation through the _defaults mechanism for the new column which bypasses the ORM. As a result the specific code is not called. Check the related issue description for a symptom of this.

**Comment by pedrobaeza** [comment]
OK, I see the stock.warehouse write code and it makes sense.

:+1:

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards

**Pull request closed without merging**
