### PR TITLE
[IMP] mail: Improve Emoji Picker (step 2) 

### PR DESCRIPTION
**Pull request by Nemael**
Improvements:

- Much more emojis in the emoji picker (more than 1800 emojis, up from 81)
- Fuzzy search bar to find emoji in the emoji picker

Known limitations:

- Emoji visual is based on browser/OS, so some emojis may not be visible on some devices

Task-2957928

### CODE REVIEW

**Comment by Yenthe666** [comment]
That amount of code 😰

**Comment by alexkuhn** [comment]
> That amount of code 😰

The big amount of LOCs come from modelling data of all emojis in file `emoji_data.js`.
All the data is essential for good working of emoji picker with that amount of emojis (around 1800): global ordering, category, keywords for search, etc.

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
