### PR TITLE
[FIX] payment: show the state in the ribbon

### PR DESCRIPTION
**Pull request by Feyensv**
[Task ID - 2180226](https://www.odoo.com/web?#id=2180226&action=333&active_id=1725&model=project.task&view_type=form&menu_id=4720)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@jev-odoo tu n'aurais pas une classe css en tête pour déplacer l'image du payment acquirer sur la vue form? :smile:

**Comment by jev-odoo** [comment]
@Feyensv Met le ribbon pour disabled et test, n'en mets pas pour enabled.
Comme ça, en enabled on voit l'image, en disabled et test, on s'en fout non?

**Comment by Feyensv** [comment]
Seems the web_ribbon is done to be purposefully on top of the image :D.
But yes, we do not care much of the image when the acquirer is disabled/in test mode anyway, and it's shown on the kanban.

**Comment by dbo-odoo** [comment]
@robodoo r+ rebase-merge

**Comment by dbo-odoo** [comment]
@robodoo r-

**Comment by dbo-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
