### PR TITLE
[IMP] Transient: do not log message 'Cannot execute name_search, no _rec_name ...

### PR DESCRIPTION
**Pull request by bealdav**
defined on' for transient model.
Name field for transient model have not the same interest than for standard model

Then it avoids to display unuseful message

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

I am not sure in which scenario a name_search is done on a transient model but if it fails, the user should be warned.
Could you give a way to reproduce ?

**Comment by bealdav** [comment]
How to reproduce:
1/ define a new transient model
2/ put fields but no char column nor  _rec_name class attribute

=> You have the log message
Cannot execute name_search, no _rec_name ...

**Comment by mart-e** [comment]
Ok after further research, I see the issue.
1. in CRM select two partners
2. run Automatic Merge wizard and validate
-> closing/saving the wizard will make a [search_read call](https://github.com/odoo/odoo/blob/9351415/addons/web/static/src/js/data.js#L501) containing `display_name`. To resolve the display_name, the server will make a [name_search call](https://github.com/odoo/odoo/blob/935141582f5245f7cf5512285d3d91dfe58cb570/addons/web/controllers/main.py#L930) (and fail because of no `_rec_name`).
Adding display_name is ok because it allows us for instance to properly render the breadcrumb (e.g. after validating an invoice, should get the invoice number in breadcrumb).

So the issue is that making the name_search in this particular scenario makes no sense (closing the wizard, no display_name rendered,...). Instead of hiding the error, the fix should be not to make the call here.
Not sure if should be done server or client side though.

Let me know if you have other scenario or idea to solve it.

side note: before merging a fix, we will also need that Akretion [sign the CLA](https://www.odoo.com/sign-cla)

**Comment by antonylesuisse** [comment]
To resolve the display_name, the server will make a name_search call, i dont understand why. Can you please provide more details. Reading display_name should not trigger name_search that's probably the issue. Anyway the fix doesnt make sense. I close this PR, reopen it if you disagree but thn provide extensive information.

**Pull request closed without merging**
