### PR TITLE
[REF] html_editor: allow inheritance in toolbar buttons & support colors buttons in icon/table

### PR DESCRIPTION
**Pull request by fdardenne**
[[REF] html_editor: allow inheritence in toolbar buttons](https://github.com/odoo/odoo/pull/174640/commits/f7101d32f27b362b558372de6471ac85be3bbad3) 

This commit enables plugins to create toolbar buttons inherited from
those defined in other plugins.

This is essential for plugins that need to use existing buttons
in different groups or with modified properties.

For instance, the `icon_plugin`may need to use the color selector
buttons, which aren't defined for the icon toolbar namespace.
With this commit, `icon_plugin`can now define a new group under the icon
namespace and include the color buttons.

[[FIX] html_editor: allow to color table cells](https://github.com/odoo/odoo/pull/174640/commits/7416607dfcca4504b3939b332713e99af286f085) 

Before, when selecting a cell it was not possible to color its
background color because of a typo used in the `APPLY_COLOR` command
option.

This commit fix it to allow users to color cells background.
This commit also introduce the `color_apply` resource, this resource
allows other plugin to take the hand on how certain element
can be colored. Instead of supporting creating an if each time
in the `colorApply` method from the `color_plugin`.

[[IMP] html_editor: implement color selector for icons](https://github.com/odoo/odoo/pull/174640/commits/37d77e79d54b8b538b488afe6d35150dc7eeb95e) 

This commit adds the color selector buttons in the toolbar
when clicking on an icon.

### CODE REVIEW

**Comment by fdardenne** [comment]
@robodoo rebase-ff

**Comment by FrancoisGe** [comment]
@robodoo r+

**Comment by fdardenne** [comment]
@robodoo rebase-ff

**Comment by FrancoisGe** [comment]
rebase-ff

**Comment by FrancoisGe** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
