### PR TITLE
[FIX] config: expand logfile argument

### PR DESCRIPTION
**Pull request by Icallhimtest**
Previously, the argument

--logfile=~/logs/odoo.log

Would create the <cwd>/~/log/ directories with the odoo.log file in it,
which is typically not the behaviour one would expect.

### CODE REVIEW

**Comment by Icallhimtest** [comment]
@xmo-odoo So do you want me to do the helper & handle other paths here or can I merge like this? (I don't have r+ rights :p)

If someone from your team wants to handle the other options, here's the full list of options that use paths.

--addons-path
--upgrades-paths
--load  (server_wide_modules)
--pg_path
--geoip-db
--screencasts
--screenshots
--i18n-export
--i18n-import
--test-file
--pidfile
-c, --config

**Comment by xmo-odoo** [comment]
I guess I'll take it up. Some of these (e.g. -c) are already normalised upstream.

**Comment by Icallhimtest** [comment]
@xmo-odoo Could we retarget to v13.0 and merge this?

While its nature is a fix, it does change the (unexpected) behaviour a bit so it should be done asap.

**Comment by xmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
