### PR TITLE
[FIX] pos_self_order: prevent error when opening mobile view

### PR DESCRIPTION
**Pull request by aamo-odoo**
This error usually occurs when there are no active orders present, and we've closed the register and then tried to access the ``Mobile View`` feature.

Steps to reproduce:

- Install the ``pos_restaurant`` and ``point_of_sale`` modules
- Make sure there are no active orders in the restaurant
- Dashboard > Open Register > Open session > Close Register
- Dashboard > Restaurant > Dropdown Menu > Mobile View
- An Error will be generated in the terminal

Traceback : 
``ValueError: bus.Bus only string channels are allowed.``

This situation arises because we have two self-ordering modes: i) ``Mobile`` and ii) ``kiosk``. When the condition at [1] is evaluated, it will become false because the session has been closed, causing ``pos_config.has_active_session`` to be false. Additionally, since the mode is ``Mobile``, the condition in the ``elif`` statement at [1] also evaluates to false. As a result, we will get the value of ``config_access_token`` as a boolean value from line [2] because the value of ``config_access_token`` will not be set from both of the above conditions. Due to ``config_access_token`` being a boolean value, the value of ``channels`` ends up being a boolean value.

This commit will fix the above error by providing an empty string within ``config_access_token``, rather than boolean values. So, the value of ``channels`` will consistently be a string.

[1]: https://github.com/odoo/odoo/blob/16120774d6e7b16b44f771ca8224426e78676295/addons/pos_self_order/controllers/self_entry.py#L35-L47
[2]: https://github.com/odoo/odoo/blob/16120774d6e7b16b44f771ca8224426e78676295/addons/pos_self_order/controllers/self_entry.py#L16C8-L23C50

sentry-5136273134

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by maan-odoo** [comment]
The code is present from 17.0, and we got boolean when not any condition was satisfied, but it was converted into a string before the bus subbscribe called here: https://github.com/odoo/odoo/blob/f6abf2d3b70ed021465676848f3b0b8d9157d61b/addons/pos_self_order/static/src/app/self_order_bus_service.js#L30

After code refactoring with https://github.com/odoo/odoo/commit/3836aad466c6c111f0f0d33c357a1c7a5150f3fd in saas-17.2, we got a boolean value, and it passed to the service.
___
In my opinion, you should apply the access token or an empty string instead of a of a bollean in config_access_token here https://github.com/odoo/odoo/blob/beee34f86f2cb0e3492b6f250d7cbb8a01f6cac1/addons/pos_self_order/controllers/self_entry.py#L16-L23.

**Comment by aamo-odoo** [comment]
Hello @maan-odoo 
Requested changes have been made 🙂

**Comment by aamo-odoo** [comment]
Hello @odoo/sentry_reviewers 
Please review this PR 🙂

**Comment by robinengels** [comment]
@aamo-odoo I'm not sure the behavior would be the same. In your case if the session is closed and mobile mode, the config_access_token would still be set. But it was not the case before.

So maybe add an `else` that would set the `config_access_token` to an empty string here https://github.com/odoo/odoo/blob/16120774d6e7b16b44f771ca8224426e78676295/addons/pos_self_order/controllers/self_entry.py#L47

**Comment by aamo-odoo** [comment]
Hello @robinengels 
The requested changes have been made 🙂

**Review by robinengels — APPROVED** [review]
LGTM. @davidmonnom can you have look ?

**Review by adgu-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
