### PR TITLE
[ADD] l10n_ar: rename module

### PR DESCRIPTION
**Pull request by zaoral**
task 350
---

### Description of the issue/feature this PR addresses:

To make the match with the new name standard for localization modules

### Current behavior before PR:

Module name: Argentinean Accounting

### Desired behavior after PR is merged:

Module name: Argentina -  Accoubting

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ren-odoo** [comment]
Hi @jco-odoo can you help me to take a look at this PR, which is  updating the module description in order to have the same format in the localizations:  "Country - Accounting"

Thank you.

**Comment by jco-odoo** [comment]
@ren-odoo We could have asked someone to do them all at once then.    @zaoral Can you change ADD in IMP?  (It does not really add something (add is mostly used when we add an entire module))

**Comment by zaoral** [comment]
HI @jco-odoo 
I have updated the commit message.
Is ready for your review.

Best Regards

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by seb-odoo** [comment]
Merging not starting, PR does not have CI.

**Comment by zaoral** [comment]
@seb-odoo  thank you for the review!

I have rebased the PR to see if now the CI will work.
Best Regards

**Comment by zaoral** [comment]
HI @jco-odoo good day.

This PR is now green. Please could you try again to do the merge?

Best Regards

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
