### PR TITLE
Saas 13.4 popover again seb

### PR DESCRIPTION
**Pull request by seb-odoo**
task-2270731

### CODE REVIEW

**Comment by seb-odoo** [comment]
Wait a sec I actually squashed stuff that I didn't intent on the last commit.

**Comment by seb-odoo** [comment]
Re-added last commit, should hopefully be good now, but please test every case if possible.

**Comment by alexkuhn** [comment]
@robodoo r+ rebase-ff

**Comment by seb-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
