### PR TITLE
Fix to handle REST API requests with json arrays

### PR DESCRIPTION
**Pull request by ndsurendra**
We need to handle REST API requests with input payloads of type json array. Currently, only json objects are supported and for json arrays, it throws an error.

Description of the issue/feature this PR addresses:

Current behavior before PR:
```py
@http.route(['/test_api/json_array'], auth="none", type='json', methods=['POST'], csrf=False)
def test_json_array(self, **kw):
    _logger.info("Log input payload: " + request.httprequest.data.decode("utf-8") )
```
If I pass an json array, like the one below, as input to the above api, it throws an error.
```
[{
"id": "xyz"
}]
```
```
curl -X POST
http://localhost:8069/test_api/json_array/
-H 'cache-control: no-cache'
-H 'content-type: application/json'
-d '[{
"id": "xyz"
}]'
```
```
Traceback (most recent call last):
File "/home/surendra/isha/sushumna/odoo/odoo/service/wsgi_server.py", line 142, in application
return application_unproxied(environ, start_response)
File "/home/surendra/isha/sushumna/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
result = odoo.http.root(environ, start_response)
File "/home/surendra/isha/sushumna/odoo/odoo/http.py", line 1281, in call
return self.dispatch(environ, start_response)
File "/home/surendra/isha/sushumna/odoo/odoo/http.py", line 1251, in call
return self.app(environ, start_wrapped)
File "/home/surendra/isha/sushumna/env/lib/python3.7/site-packages/werkzeug/middleware/shared_data.py", line 227, in call
return self.app(environ, start_response)
File "/home/surendra/isha/sushumna/odoo/odoo/http.py", line 1418, in dispatch
request = self.get_request(httprequest)
File "/home/surendra/isha/sushumna/odoo/odoo/http.py", line 1356, in get_request
return JsonRequest(httprequest)
File "/home/surendra/isha/sushumna/odoo/odoo/http.py", line 592, in init
self.params = dict(self.jsonrequest.get("params", {}))
AttributeError: 'list' object has no attribute 'get'
```
Desired behavior after PR is merged:

The http Controller need to handle apis with payloads of json array successfully.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ndsurendra** [comment]
Hi @nim-odoo, could you please review this PR?

**Comment by ndsurendra** [comment]
Hi @alexkuhn, could you please review this PR or mention someone who could take a look into it?

**Comment by alexkuhn** [comment]
Hello @mart-e, could you please have a look at this PR? Thanks!

**Comment by ndsurendra** [comment]
Hi @mcm-odoo , could you please review this PR?

**Comment by ndsurendra** [comment]
Hi @mart-e , could you please review this PR? Thanks.

**Comment by mart-e** [comment]
Hi,

Sorry but we are only supporting the [jsonrpc 2](https://www.jsonrpc.org/specification) syntax, not REST.
Your example call is not jsonrpc, so it fails.

**Comment by ndsurendra** [comment]
I understood that using type='json' will apply the Json RPC protocol.
The other option is to use type='http' which seems to accept the array of json objects in the payload.

**Pull request closed without merging**
