### PR TITLE
[16.0] website_sale: avoid accesory products render

### PR DESCRIPTION
**Pull request by Pablocce**
In large orders, loading accessory products takes a long time, this is an improvement to avoid unnecesary loads.

When the user hover over the cart icon, the "cart" method is called, which performs loading and rendering of elements and other checks.

There is no reason to render the accessory products if the post is "popover" and that view is rendered, since it only involves the order lines.

image

With this PR, we seek to optimize the order navigation and the checkout  since in orders with large products there may be many accessory products.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by danielduqma — COMMENTED** [review]
LGTM, thanks!

**Comment by danielduqma** [comment]
Hello @JKE-be,

We saw that you added popover functionality in https://github.com/odoo/odoo/commit/a2b7678f10a9dd7c3c3a15ff1e444a6514e72252. Could you take a look at this PR? Is there any reason you put popover return right after suggested products instead of before? Those products are not shown on popup.

Thanks, regards

**Comment by JKE-be** [comment]
Thanks for the PR. No good reason to compute useless things in standard. You are right...
But since it is now in stable version since a long time, we cannot warranty that nobody use it or the express checkout button in his popover via a customization. And we cannot break these websites at next pull of the code.


So imho, it is safer to only change it in master... what is useless since already removed by commit <odoo/odoo@a9f9316b22449a60bb3095655886b14438697daa>.


For the stable version, if it is important performance issue, I will suggest to only pass in the request a new params based on a view update. From this way, only new user, or people that update the view to have the fix will have this improvement; without break existing databases.

E.g.: 

in Dom
`add a new att on My-cart
`
in JS
`if new att on My-cart => /my/cart?type=popover&accessories=no&express=no
`

in controller,
```py
if order: 
   if accessories != no:
       values = _cart_accessories
   if express != no:
       values = _get_express_shop_payment_values

if type == popover
    return xxx
```

**Comment by Feyensv** [comment]
As explained by Jeremy, it's not safe to simply remove this data from the rendering values as it might break custom overrides or modifications of the template, even if it's not used in the standard logic.

Since it has already been removed in 17+, I don't believe we should add more complexity to the code in 17 to support custom requests where those values are not generated (like the solution proposed by Jeremy).

**Pull request closed without merging**
