### PR TITLE
[FIX] web: avoid double write in the form view

### PR DESCRIPTION
**Pull request by Gorash**
issue: opw-669323

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Well, I will first wait for a green runbot :).

**Comment by Gorash** [comment]
It's green :-p

**Comment by Gorash** [comment]
Shit, fail... the very quick double click trigger two write

**Comment by Gorash** [comment]
:+1:

**Comment by beledouxdenis** [comment]
Technically, it seems correct,
functionnally, as well.

However, when enabling some throttling in the debugger, there is another issue preventing to quickly save, and display a warning telling your changes will be discarded (and this is wrong). See below:
https://drive.google.com/file/d/0B5GVjjwUC-ygak1nemZuZ1duN2s/view?usp=sharing

Could you not try to save this as well, as this is kind of related ?

Once done, do not merge directly. We will beta-test your patch on a server, to make sure there is no unexpected second behavior.

**Comment by Gorash** [comment]
:+1:

**Comment by Gorash** [comment]
I found an other bug linked in an other task

**Comment by Gorash** [comment]
@ged-odoo Can you check (and don't forget this change for the next version)

**Comment by beledouxdenis** [comment]
I can still reproduce the issue I mention above
https://drive.google.com/file/d/0B5GVjjwUC-ygcEhBNXZXWUlZS2M/view?usp=sharing

**Comment by Gorash** [comment]
@beledouxdenis It's fixed in community, some fixes are side-ported in enterprise

**Comment by beledouxdenis** [comment]
Silly, I am.

Let met retry.

**Comment by Gorash** [comment]
?

**Comment by beledouxdenis** [comment]
I am doing my best but I have simply too much in my hands.

**Comment by beledouxdenis** [comment]
Looks like there are still issues, when creating new product within the invoice lines at least. See the below video:
https://drive.google.com/file/d/0B5GVjjwUC-ygQXNCZXVMbThIUGc/view?usp=sharing
- For the first line, the tax was not computed.
- For the last, it was not at all saved.

**Comment by Gorash** [comment]
Youpie !

**Comment by ged-odoo** [comment]
merged in 9.0 (slightly altered)

**Pull request closed without merging**
