### PR TITLE
[IMP] crm: improve naming of main crm lead action

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Task 2070287

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+ retry @d-fence pizzas stock quant

**Comment by d-fence** [comment]
I'm sorry @tde-banana-odoo , no more pizza's in stock. retry makes no sense when the oven is off.
Et puis ton build est en train de builder

**Comment by tde-banana-odoo** [comment]
Oui j'ai killé / rebuildé.

I am sorry @d-fence have an oven off makes no sense when developers faces multi-requests for OdooDays.

**Comment by tde-banana-odoo** [comment]
Any news on this ? @d-fence more than 3 hours after the r+ / CI ...

**Pull request closed without merging**
