### PR TITLE
[FIX] mass_mailing: remove unsupported color picker on mailing lists

### PR DESCRIPTION
**Pull request by smo-odoo**
Task : https://www.odoo.com/web#id=2042384&action=327&model=project.task&view_type=form&menu_id=4720

Pad : https://pad.odoo.com/p/r.5d6ede17853f84eff18dbb47908a6313

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by KangOl** [comment]
@robodoo r-

saas-12.2 is EOL. Please target saas-12.3

**Comment by KangOl** [comment]
forward-port pending; will fix conflicts

**Comment by KangOl** [comment]
@robodoo r+

**Comment by KangOl** [comment]
@xmo-odoo Why did the mergebot decided to unsee this PR?

**Comment by xmo-odoo** [comment]
@KangOl you changed the target, it might have gotten somewhat lost. Either that or there was an error during tags update but mergebot doesn't sync labels back from github so if they get out of step tags might get gone.

**Comment by xmo-odoo** [comment]
yeah good stuff the retargeting back and forth has led to two PRs with the same number. And the edition webhook handler currently has no logging, so I can't really trace what happened, all I can see is that it first decided to completely untag the PR, then to create a brand new version of it:
```
2019-08-06 17:13:21,891 16653 DEBUG mergebot odoo.addons.runbot_merge.github: change_tags(odoo/odoo, 35494, remove={'CI 🤖', 'seen 🙂'}, add=set())
2019-08-06 17:13:22,377 16643 INFO mergebot odoo.addons.runbot_merge.controllers: opened: odoo/odoo:35494 ([FIX] mass_mailing: remove unsupported color picker on mailing lists) (smo-odoo)
```
And now it's completely broken because it really doesn't expect finding the same PR twice in a repo:
```
ValueError: Expected singleton: runbot_merge.pull_requests(17874, 17902)
```

**Comment by xmo-odoo** [comment]
…

did you deactivate saas-12.2?

**Comment by KangOl** [comment]
> …
> 
> did you deactivate saas-12.2?

yes, I did.

**Comment by xmo-odoo** [comment]
> > …
> > did you deactivate saas-12.2?
> yes, I did.

When you did that *then* retargeted the PR, mergebot failed to find the source branch, so assumed the PR had been retargeted from a branch it was not handling (at all) and therefore it had to create a brand new PR. Which it did.

And I put a constraint on (number, target, repository) rather than (number, repository) so the creation of a second PR with the same number in the same repo worked fine.

**Comment by xmo-odoo** [comment]
Deleted the old PR, you may want to be careful about retargeting until odoo/runbot#169 is fixed.

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
