### PR TITLE
[FIX] phone_validation: put filename on init file

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

Fixes https://github.com/odoo/odoo/commit/d2809cbd941b20928cd1e48c50c1339888853d98, by adding the name of the new file into the `__init__` file.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
ping: @rrahir @tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
:octopus:

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
Oh the famous MRO bug.

**Comment by mreficent** [comment]
Should I do something?

**Comment by tde-banana-odoo** [comment]
It is a known bug / limitation ... Trying to fix at https://github.com/odoo/odoo/pull/36580 .

**Comment by mreficent** [comment]
ok, good luck

**Comment by mreficent** [comment]
the famous MRO bug if fixed with https://github.com/odoo/odoo/pull/36427? If so, then you can revert https://github.com/odoo/odoo/pull/36580 😏

**Pull request closed without merging**
