### PR TITLE
[FIX] account: fix 'upload bill tour' bill layout

### PR DESCRIPTION
**Pull request by jbw-odoo**
- add outer shadow to bill in wizard preview
- move address block to right in generated pdf, same as in wizard preview
- set invoice date & due date on one line in pdf, same as in wizard preview

task: 2581377

### CODE REVIEW

**Comment by jbw-odoo** [comment]
@qdp-odoo

**Comment by qdp-odoo** [comment]
> move address block to left in generated pdf (same as bill in wizard preview)

@jbw-odoo you meant **right**, right?

**Comment by jbw-odoo** [comment]
> > move address block to left in generated pdf (same as bill in wizard preview)
> 
> @jbw-odoo you meant **right**, right?

Yes. I meant right.

**Comment by william-andre** [comment]
> > > move address block to left in generated pdf (same as bill in wizard preview)
> > 
> > 
> > @jbw-odoo you meant **right**, right?
> 
> Yes. I meant right.

You're right, he meant right.

**Comment by jbw-odoo** [comment]
@qdp-odoo as discussed, this still needs to be merged

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
