### PR TITLE
[FIX] Fix uom factor computation

### PR DESCRIPTION
**Pull request by ghost**
Description of the issue/feature this PR addresses:
Fixes the discount computation on sale order line when product uom is different from line uom

Current behavior before PR:
In runbot, go to Sales > Configuration > Settings
Under sales price, select Advanced pricing based on formula
Under Discount, select Allow discounts on sales order lines

Go to Sales > Configuration > Pricelists and create a pricelist with Discount Policy = Show discount in the sale order
Change the default rule and set Compute Price to Percentage (discount), set the discount to 10%

Go to Sales > Sales > Products and create a product with Units of measure = Dozens and Sale Price = 1
Go to Sales > Sales > Quotations and create a quotation. Select the pricelist you created and create an order line with the product you created. The discount on the order line is 10% as mentioned on the pricelist. Now change the unit of measure to Units. The Unit price is now 12 and the discount is 99.33 % , instead of 1/12 and 10 %

Desired behavior after PR is merged:
^fixed
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tgr-odoo** [comment]
Ok, got it. However, because there's a uom in the context, the computed price is not correct. I'll see wat I can do to fix that

**Comment by tgr-odoo** [comment]
@simongoffin What do you think about this?

**Comment by simongoffin** [comment]
@tgr-odoo No in fact you forget to set Min. Quantity to 0 in the Pricelist Items because 1/12 is lower than 1.
 I will merge this pull-request with your first commit. https://github.com/odoo/odoo/pull/11277 because it is enough.

**Comment by tgr-odoo** [comment]
@simongoffin I know of the minimal quantity of 1 problem, but it doesn't come from there.
The problem is that the first commit fixes the uom onchange but not the product onchange.
Try to create 2 products with different uoms, and switch from one to the other in the so line. The line uom doesn't change along with the product and the discount is computed wrongly.

**Comment by simongoffin** [comment]
@tgr-odoo  Alright I will check and fix the other bug but I will merge your first commit(07dd720cf6a98d6e20b580fefd62ef249c66a54b) because it fixes the problem you described in your pull request. I will keep you in touch for the other bug.

**Pull request closed without merging**
