### PR TITLE
[11.0] [FIX] stock: Fix product template compute quantities depends

### PR DESCRIPTION
**Pull request by FFernandez-PlanetaTIC**
**Description of the issue/feature this PR addresses:**

The absence of `@api.depends` in method `_compute_quantities` of model `product.template` is causing a glitch:

https://github.com/OCA/connector-prestashop/pull/101#issuecomment-448229084

**Current behavior before PR:**

The `qty_available` of a `product.template` is **not** recomputed when it is done for one of its `product.product`:

```
(virtualenv-11.0) paco@coloma:~/workspace/PlanetaTIC/odoo$ python odoo-bin shell -d 11.0-fix-stock-product_template_compute_quantities_depends
...
>>> product = env['product.product'].create({'name': 'Test', 'type': 'product'})
>>> product.qty_available
0.0
>>> product.product_tmpl_id.qty_available
0.0
>>> 
>>> warehouse = env['stock.warehouse'].search([], limit=1)
>>> 
>>> qty_change = env['stock.change.product.qty'].create({'location_id': warehouse.lot_stock_id.id, 'product_id': product.id, 'new_quantity': 10})
>>> qty_change.change_product_qty()
{'type': 'ir.actions.act_window_close'}
>>> 
>>> product.qty_available
10.0
>>> product.product_tmpl_id.qty_available
0.0
>>> 
>>> env.clear()
>>> product.product_tmpl_id.qty_available
10.0
```

**Desired behavior after PR is merged:**

The `qty_available` of a `product.template` is recomputed when it is done for one of its `product.product`:

```
(virtualenv-11.0) paco@coloma:~/workspace/PlanetaTIC/odoo$ python odoo-bin shell -d 11.0-fix-stock-product_template_compute_quantities_depends
...
>>> product = env['product.product'].create({'name': 'Test', 'type': 'product'})
>>> product.qty_available
0.0
>>> product.product_tmpl_id.qty_available
0.0
>>> 
>>> warehouse = env['stock.warehouse'].search([], limit=1)
>>> 
>>> qty_change = env['stock.change.product.qty'].create({'location_id': warehouse.lot_stock_id.id, 'product_id': product.id, 'new_quantity': 10})
>>> qty_change.change_product_qty()
{'type': 'ir.actions.act_window_close'}
>>> 
>>> product.qty_available
10.0
>>> product.product_tmpl_id.qty_available
10.0
```

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Duplicate of #30024 
No need to create one PR for each version, just submit in the lowest and we will forward port it to upper versions.

**Comment by FFernandez-PlanetaTIC** [comment]
We created two PRs because the solution is slightly different for v10.0 and v11.0

**Comment by mart-e** [comment]
oh sorry, I checked too fast, my bad

**Comment by pedrobaeza** [comment]
@jco-odoo can you check this one?

**Comment by FFernandez-PlanetaTIC** [comment]
v10.0 fix 48e93a10a1d1dbb0c6301eb33cf433db6d59f02b has been forward ported to v11.0 but it is not valid, as I said before, the solution is slightly different for v10.0 and v11.0

I have rebased and resolved conflicts

Thanks!

**Comment by mart-e** [comment]
Thanks you for the rebase and the patch

@robodoo r+

**Pull request closed without merging**
