### PR TITLE
Sign CLA Ajroo - Kasper Declercq

### PR DESCRIPTION
**Pull request by Ajroo**
Sign cla

### CODE REVIEW

**Review by Ajroo — COMMENTED** [review]
CLA document added

**Comment by odony** [comment]
Hello, and welcome as a new contributor :)

Could you squash your commits and force-push your branch, so the final result of merging your branch will be a single new commit with this message:  `[CLA] Add individual signature for Ajroo`?
Thanks!

**Comment by Ajroo** [comment]
> Hello, and welcome as a new contributor :)
> 
> Could you squash your commits and force-push your branch, so the final result of merging your branch will be a single new commit with this message: `[CLA] Add individual signature for Ajroo`?
> Thanks!

Done

**Review by odony — APPROVED** [review]
@Ajroo thanks!

@robodoo r+

**Pull request closed without merging**
