### PR TITLE
Master l10n latam invoice document remove sequence nla

### PR DESCRIPTION
**Pull request by nla-odoo**
- Removed  unused l10n_latam_document_type_id from sequence

Task: https://www.odoo.com/web#id=2427849&action=4043&model=project.task&view_type=form&cids=2&menu_id=4720

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by KangOl** [comment]
runbot does not fail because it doesn't install `l10n_` modules ¯\\_(ツ)_/¯

**Comment by jco-odoo** [comment]
@KangOl So it would fail otherwise?

**Comment by KangOl** [comment]
Yes, it will.

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
