### PR TITLE
[FIX] website_sale : Fix disabled reason on submit

### PR DESCRIPTION
**Pull request by pipu-odoo**
With Jquery.data, you can set everything as value (array, object,
string, etc) wich is confusing. This commit fix the function that check
if the button is ready. It didn't work because the data declared in 
this.$submitButton is not a boolean but an object.

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
@pipu-odoo there are cases where this fails when we have an empty object apparently

**Comment by AntoineVDV** [comment]
Hello @pipu-odoo, if you know which commit introduced this bug, could you please reference it in this PR's commit message? Thanks :)

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
