### PR TITLE
[IMP] mail: improve mail.followers._get_recipient_data SQL performance

### PR DESCRIPTION
**Pull request by grindtildeath**
The added OR clause on partner.id in case pids is defines triggers a
costly seq scan on res_partner table. By using another subquery in
case pids is defined we can avoid the seq scan and decrease the
execution time of the SQL query.

Description of the issue/feature this PR addresses:

Improve performance of SQL query

Current behavior before PR:

cf query plan before: https://gist.github.com/grindtildeath/cad3b1f863d10f9aca9df603a4d28248

Desired behavior after PR is merged:

cf query plan after: https://gist.github.com/grindtildeath/cad3b1f863d10f9aca9df603a4d28248

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by grindtildeath** [comment]
Looks like I'm breaking Odoo tests with the OR clause not behaving the same way with the extra parenthesis I did add. So I guess I'll have to look at it again :disappointed:

**Comment by tde-banana-odoo** [comment]
Indeed, "some" tests are broken :D

**Comment by grindtildeath** [comment]
@tde-banana-odoo @seb-odoo Can you guys please have a look now that tests are fixed? :pray:

**Review by ivantodorovich — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Comment by C3POdoo** [comment]
Dear @grindtildeath,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
