### PR TITLE
[FIX] l10n_in: set id instead of record set

### PR DESCRIPTION
**Pull request by rop-odoo**
on product_uom_id used in grouping key

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rop-odoo** [comment]
@odoo/rd-accounting Can you check and fix this issue ASAP in priority bases.

**Comment by jco-odoo** [comment]
@jva-odoo can you test again as well?  (I want to avoid still another fix on the same thing)

**Comment by william-andre** [comment]
> @jva-odoo can you test again as well? (I want to avoid still another fix on the same thing)

Are there tests that use these methods? If there aren't any (especially for saas-14.5 and up), please add some so that they can be run on the l10n staging tests.

@rop-odoo Also, the message could be a little bit more explicit. Why is it needed to have the id and not the recordset? When was it broken? Why?

**Comment by rop-odoo** [comment]
@william-andre ,
In On Premise customer we are taking bulk return of multiple delivery from single view. At that time we are creating automatically debit note based delivery and related invoice document.

 error for your reference:

  File "/home/odoo/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/odoo/addons/account/models/account_move.py", line 3529, in create
    lines = super(AccountMoveLine, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/odoo/odoo/models.py", line 3812, in create
    records = self._create(data_list)
  File "/home/odoo/odoo/odoo/models.py", line 3918, in _create
    cr.execute(query, params)
  File "/home/odoo/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: can't adapt type 'uom.uom'

**Comment by jva-odoo** [comment]
@william-andre this method is already called from demo data.

and it's already failed in saas-14.5 l10n staging tests so you fix it here https://github.com/odoo/odoo/commit/514f640cd1824f728ec56d3fb51d467643bad924

**Comment by jva-odoo** [comment]
> @jva-odoo can you test again as well? (I want to avoid still another fix on the same thing)

I already test this with @rop-odoo

**Comment by jva-odoo** [comment]
I think this is brake when the create_method is create() https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L676

because create using new() is call convert_to_cache so recordset is converted to id.

**Review by jva-odoo — APPROVED** [review]
It's looking good.

@rop-odoo add in commit-msg that
Introduced in https://github.com/odoo/odoo/commit/18a823e379ba023c176299c4034b3b28d09c2336
and backport of https://github.com/odoo/odoo/commit/514f640cd1824f728ec56d3fb51d467643bad924

**Comment by rop-odoo** [comment]
Thanks @jva-odoo Commit message changed as per your suggestion.

**Comment by jco-odoo** [comment]
@jva-odoo @rop-odoo  Why is this not going to break as every other key we added had problems before?  And what about the idea of writing a test for it?

**Comment by jva-odoo** [comment]
> @jva-odoo @rop-odoo Why is this not going to break as every other key we added had problems before? And what about the idea of writing a test for it?

In other keys, if recordset then .id is there
I think no need test case because of demo data is there and it's already broken one time in master so it's fixed.

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
