### PR TITLE
l10n_uk: update tax and report line names

### PR DESCRIPTION
**Pull request by dbkosky**
Update some minor l10n_uk details:
***Update tax names***
Tax names are changed to be in accordance with the new "taxonomy" format as described in the task with task-id 3052677
By default, the taxes from the tax template would be instantiated as per the below screenshot:
image

***Update UK report lines***
Report lines are updated to match those described in the UK government documentation (see below) 
https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012

### CODE REVIEW

**Review by vin-odoo — COMMENTED** [review]
There is no need to put the old names in the new description field?
Otherwise LGTM

**Comment by dbkosky** [comment]
@vin-odoo Thanks for looking! The contents of the description field were made as short as possible since they appear on the invoice (@Laura-labe recommended this). 

I just rebased and it turns out there's "invoice_label" field now, so the content of the "description" field has been moved there.

**Comment by vin-odoo** [comment]
@dbkosky invoice_label is the label used only when printing an invoice so it won't impact the invoice form view.
I can't say for sure (I don't know UK tax laws) but maybe the old invoice labels were already correct?

> The contents of the description field were made as short as possible since they appear on the invoice

Do they? On the invoice, we can see the name and the tax group (in the tax total). I don't remember seeing the tax description (although I may be wrong).

**Comment by dbkosky** [comment]
@vin-odoo Ah sorry, I wasn't so clear. I was mostly talking about the printed invoice.

The `description` field was appearing on the printed invoice under the taxes column (in the report_invoice template in version 16.0) 
`<span t-esc="', '.join(map(lambda x: (x.description or x.name), line.tax_ids))" id="line_tax_ids"/>`, 
in master it has just now changed to `x.invoice_label` instead of `x.description` 
I think Laura wanted the these tax labels on the printed invoice to be as concise as possible.

The existing labels were ok (it was using the names, as there was not description defined), but there's no specific legal requirements about the names, just that the VAT amount is reported:
https://www.gov.uk/invoicing-and-taking-payment-from-customers/invoices-what-they-must-include

In a way the existing names were wrong anyway, for instance it's not "lower rate".. it's actually "reduced rate", but as in the doc above, the VAT amount should be enough.

**Comment by vin-odoo** [comment]
@robodoo r+

**Comment by vin-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
