### PR TITLE
[FIX] calendar : Groupby {start,end}_date for non-allday meetings

### PR DESCRIPTION
**Pull request by yoba-odoo**
### Steps to reproduce:
	- Install Calendar module
	- Create some all-day meetings and some non-all-day
	- Navigate to the list view of the meetings
	- Groupby start_date or end_date
	- Non-all-day meetings will be grouped under None

### Current behavior before PR:
Grouping meetings with start_date or end_date will just group all-day meetings and non-all-day will be grouped under null. This is happening because start_date and end_date are null for non-all-day meetings and will just have a value if the meeting is an all-day one. So when it is grouping with those fields each non-all-day meeting will just be grouped under None.

### Desired behavior after PR is merged:
By doing a hack to read_group override in calendar_event now when we are grouping by start or end date we get the grouping result of the other datetime fields that all events already have values for and then merge the result of those two grouping to put every event to its own time group either using start_date and end_date for all-day meetings or using start and stop fields for the normal events

### Other Solution:
We could have just check if the user wants to group by start_date or end_date and return the results of the grouping of start or stop datetime but it will require modifying so many things in the result's data.

opw-2995693

### CODE REVIEW

**Review by nle-odoo — COMMENTED** [review]
> Grouping meetings with start_date or end_date will just group allday meetings
and non-allday will be grouped under null. This is happening because start_date
and end_date are null for non-allday meetings and will just have a value if the meeting
is an allday one. So when it is grouping with those fields each non-allday meeting
will just be grouped under None.

the behavior seems to makes sense to me. start_date and end_date seems to be technical field only filled for all day event. If we want a date it seems that start and stop should be what we want to use.

It seems that the issue is a slight non-user friendliness that it's not very clear that the start_date and end_date are only filled for all day event (technically when you see None for non-whole day event, you would be able to know that it's the case), but I'm not sure adding 30 lines of code to have a different behavior than normal is worth it.

In my opinion we should probably:

- do nothing
- change field label or help so it's clear that it's only for all day event

**Comment by yoba-odoo** [comment]
@nle-odoo 100% I agree with you that we should do nothing regarding this. But the R&D team told me to try to fix this and the PO already approved the ticket.

**Comment by arj-odoo** [comment]
> @nle-odoo 100% I agree with you that we should do nothing regarding this. But the R&D team told me to try to fix this and the PO already approved the ticket.

Hello, what @geflx said is that you could not follow the first idea: updating the start_date and end_date value because it would cause massive issues with synchronization. He suggested to have a look at `read_group` override. As there is no easy fix, indeed we should not do this change. There is a huge risk of regression and I don't think we should do these kind of override in an already complex model.

**Comment by yoba-odoo** [comment]
> > @nle-odoo 100% I agree with you that we should do nothing regarding this. But the R&D team told me to try to fix this and the PO already approved the ticket.
> 
> Hello, what @geflx said is that you could not follow the first idea: updating the start_date and end_date value because it would cause massive issues with synchronization. He suggested to have a look at `read_group` override. As there is no easy fix, indeed we should not do this change. There is a huge risk of regression and I don't think we should do these kind of override in an already complex model.

Hello @arj-odoo Thanks for your reply. Yes I understood what Gabriel said and I told him that it would be very unclean fix so I was only trying the fix and it was your team's final call of course. Anyways I will close the PR and the ticket since we agreed that we shouldn't do anything regarding this.

**Pull request closed without merging**
