### PR TITLE
Fix email inline attachments

### PR DESCRIPTION
**Pull request by michaelhwalther**
The three commits in this pull request together enable real-world use of emails with embedded images, which are (unfortunately) widely used now particularly for little logos (coporate logo in footer) or marketing gimmicks (like facebook icon, "like"-button etc.).
Currently, these images create separate attachments e.g. in Projects, and lead to tens and hundreds of little useless attachments. Additionally, the images are not shown (rather, the  tag is shown literally!).

This pull request solves both issues:
- inline images (identified by their Content-ID in the correponding img tag) are embedded into the HTML as "data:" URLs. This avoids saving them as separate attachments. "Actual" attachments are still saved as such.
- html_sanitize is modified to allow such URLs in img tags (src attribute)
- Cleaner is modified to handle content-IDs which typically contain an AT (@) sign, generated by the email clients.

### CODE REVIEW

**Comment by michaelhwalther** [comment]
Signed the CLA in #9013

**Comment by antonylesuisse** [comment]
@tde-banana-odoo mayve we should limit the size, if the image is too big we keep it in attachement.

**Comment by michaelhwalther** [comment]
I have successfully tested this fix with an email thread containing around 59 images (both icons as well as screenshots) totaling almost 500MB - without any noticeable performance issues.

I would rely on the sanity of the sending email client and not impose a size limit per se. Note that the images could be screenshots, so 100kb PNG files are thinkable.

The main benefit of this patch is to separate "real" attachments from "embedded" images. With the 59-images-email, the associated project would be rendered unusable. Even with only 5 or 10 of the images treated as an attachment.

**Comment by michaelhwalther** [comment]
Rebased to include CLA signature

**Comment by tde-banana-odoo** [comment]
Hello,

Your proposal is interesting. Indeed parsing cids is a missing feature in the mail gateway. However converting them into base64 can lead to storing lot of data. The mail_message table is already a critical table, I don't think we should allow storing huge blob of data inside it.

We decided to keep the cids in attachments and to replace the cid links into links to the image controller. Indeed signature images (social networks, ...) will create unnecessary attachments. However real attachments inline in the email will also be present on the document. There is no way to differentiate an inline image that is an attachments and an inline image that is noise.

Work continues on https://github.com/odoo/odoo/pull/10115 that also contains other improvements. Please note that we currently target 9.0 and not 8.0.

**Comment by antonylesuisse** [comment]
When parsing incoming mails we will replace src="cid:xxx" by src="/web/image/<id-of-attachment>" so that they will be correctly displayed inline. We also improve on filtering nasty inline css by whitelisting the css properties we will allow. We will also remove all the postprocessing in fecth_message.

I close this pull request. Please check #10115

**Comment by michaelhwalther** [comment]
> We decided to keep the cids in attachments and to replace the cid links into links to the image controller. 

That's ok - as long as these attachments do not interfere with the 'actual' attachments.

> Indeed signature images (social networks, ...) will create unnecessary attachments. 

These unnecessary attachments are the issue addressed by this pull request. With your fix in #10115, this problem becomes even worse because previously inlined cid-attachments are now separated into even more 'noise' attachments.

> However real attachments inline in the email will also be present on the document. 

Yes, that's why we need to separate them from the 'noise' attachments. It is simply impossible to find 'real' attachments if there are 5 or 10 'noise' attachments named "attachment (1)" ...  

> There is no way to differentiate an inline image that is an attachments and an inline image that is noise.

Yes, there is. This pull request implements one that works very well. It uses the same logic as regular mail clients do:  Any "inline" image (with a 'cid' url) is a indeed a "noise" attachment; all others are "real" attachments.  These are exactly the attachments that email clients offer to "download".  Email clients to not offer to download twitter icons, or linkedin icons either. 

PLEASE consider to address the issue of noise attachments!!!

Compromise suggestion: mark "extracted" attachments as "noise" attachments and don't include them in the attachment's list of the document. This way, the storage is still separate, and the document's attachment list remains usable.

**Comment by michaelhwalther** [comment]
We decided to keep the cids in attachments and to replace the cid links
into links to the image controller.

That's ok - as long as these cid-attachments do not interfere with the
'actual' attachments.

Indeed signature images (social networks, ...) will create unnecessary
attachments.

These unnecessary attachments are the issue addressed by this pull request.
With your fix in #10115 <https://github.com/odoo/odoo/pull/10115>, this
problem becomes even worse because previously inlined cid-attachments are
now separated into even more 'noise' attachments.

However real attachments inline in the email will also be present on the
document.

Yes, that's why we need to separate them from the 'noise' attachments. It
is simply impossible to find 'real' attachments if there are 5 or 10
'noise' attachments named "attachment (1)" ...

There is no way to differentiate an inline image that is an attachments and
an inline image that is noise.

Yes, there is. This pull request implements one that works very well. It
uses the same logic as regular mail clients do: Any "inline" image (with a
'cid' url) is a indeed a "noise" attachment; all others are "real"
attachments. These are exactly the attachments that email clients offer to
"download". Email clients to not offer to download twitter icons, or
linkedin icons either.

PLEASE consider to address the issue of noise attachments!!!

Compromise suggestion: mark "extracted" attachments as "noise" attachments
and don't include them in the attachment's list of the document. This way,
the storage is still separate, and the document's attachment list remains
usable.

**Comment by antonylesuisse** [comment]
Attachments are not noise what's the problem with them?

It's cleaner to store blobs in the filestore instead of beas64 encoded strings in TEXT sql field (Ok, We might argue about blob less than 1kB but not above).

Also attachments are deduplicated it means that if you receive 10 email with the same image (common for signature) you will only store it once.

@tde-banana-odoo in your patch attachement used inline should not be displayed at the bottom (this can be done in step2 client side with the removal of read more in python, in js you grep fo /web/image/<id> and hide thoses).

**Comment by michaelhwalther** [comment]
Am 24.12.2015 11:38 schrieb "antonylesuisse" <notifications@github.com>:
>
> Attachments are not noise what's the problem with them?

This pull request was triggered by the issue that some "attachments" are
indeed noise, obstructing the view to the "actual" attachments, which are
of course not noise, but valuable pieces of information.

The difference is in the user's intention.

"actual" (read: valuable or intentional) attachments are those that a user
perceives as "additions" to the message, i.e. some extra file (e.g.a log
file) or a document (word file, or PDF) attached to the message. The users
attach these files specifically as "additions" to the message text and
think of them as separate, finite pieces of information.

"noise" attachments come from files attached to messages as part of the
message text itself. These are usually graphical elements to be displayed
in the context of the text (inline), like a figure or a screenshot, or
nowadays little logos (corporate logo) or social network symbols (Twitter,
LinkedIn,...) Users do not add them as "additions" to the message, but as
part of the message text itself (often by DnD) or as part of the corporate
signature.  Users do not think of these elements as attachments (although
the mail clients make them such); they also usually don't have a meaningful
filename, but maybe a generated id at best.

In Odoo, both types of attachments are stored the same (which is ok), but
also displayed in the same (linear) lists of attachments, which creates a
problem.
In our case, we use emails with projects and tasks and issues. The "noise"
attachments made it impossible to work with the issues, e.g. to find a log
file attached to the issue. At first, I thought, the users will just have
to live with the (rather long) list of attachments, but it turns out that
the marketing departments use these corporate logos and social logos
(like-buttons...) so much that it is not reasonable to use anymore.

I started thinking how email clients work, and it turns out that the
distinction between "actual" attachments and "noise" attachments is simple:
all cid (content ID) attachments are inline, therefore not "real", but
noise attachments. All other mime parts are "actual" attachments, i.e. the
valuable kind that should be in the attachment lists odd projects and tasks
and issues etc.

> It's cleaner to store blobs in the filestore instead of beas64 encoded
strings in TEXT sql field (Ok, We might argue about blob less than 1kB but
not above).

Yes, that's reasonable, I'm not arguing about the storage technology.  I'm
pointing out the usability of attachment lists of p projects, tasks, issues
etc.

> Also attachments are deduplicated it means that if you receive 10 email
with the same image (common for signature) you will only store it once.

Also a valid technical consideration, which I'm not arguing. As far as I
saw in your code this is done by cid, so it will work probably only within
one email.

My issue is to present the two different kinds of attachments separately to
the user:
cid-attachments ("noise") could be displayed inline only, and not be shown
in the attachment lists of projects, tasks etc. where only "actual"
attachments are listed. This is a simple, yet very practical approach.
Or, cid-attachments are shown in a separate list of attachments.
Or with a clear marker, and only at the end of attachment lists.
Or something else to make sure that "valuable", "actual" attachments are
easy to access from the business object.
The only thing that doesn't work is to present them as one long flat list.

So I'm not questioning your technical considerations, they are ask valid
and agreed.
I'm asking you to consider how the attachments are presented to the user on
the business object level. My hypothesis is that "noise" attachments simply
don't need to be listed there at all.

Thanks for your patience with me on this issue! If there were a way to
schedule a call, I would have preferred that to explain everything.

Joyeux noël á tous!

Michael

(I would have filed a support ticket via our maintenance contract, but
instead I came up with this solution myself, which I wanted to give back)

**Comment by antonylesuisse** [comment]
I agree with you that we should handle those to kind of attachments differently. My proposal is to hide attachments that are referenced in email body wth cid:url. So you would see them inline but not below the message.

In the database all attachments would be considered equal but client side by the message widget would grep the message for /web/image/<id> links (that are generated from cid: uri) and hide the <id> matching at the bottom of the message.

Would that be ok for you ?

**Comment by antonylesuisse** [comment]
I agree with you that we should handle those to kind of attachments differently. My proposal is to hide attachments that are referenced in email body wth cid:url. So you would see them inline but not below the message.

In the database all attachments would be considered equal but client side by the message widget would grep the message for /web/image/<id> links (that are generated from cid: uri) and hide the <id> matching at the bottom of the message.

Would that be ok for you ?

**Comment by michaelhwalther** [comment]
>
> I agree with you that we should handle those to kind of attachments
> differently. My proposal is to hide attachments that are referenced in
> email body wth cid:url. So you would see them inline but not below the
> message.
>
Yes, I think that's how the cid-urls are intended to be used.

> In the database all attachments would be considered equal but client side
> by the message widget would grep the message for /web/image/ links (that
> are generated from cid: uri) and hide the matching at the bottom of the
> message.
>
> Would that be ok for you ?
>
Yes, that would solve the problem in the message display itself, thank you.

There is one more thing, though: the same problem applies to the
"attachment" drop-down in the form views of the business objects (e.g.
project/task/issue etc.), and the lists when clicking the "documents"
button in the button-box for each of these.
The solution here would be some sort of "flag" to enable filtering them,
either on the client side or the server side.
This applies to the "attachment" drop-down, as well as the "attachments
list" that opens upon clicking the "XX documents" button.

Here's a screenshot (inline :-) ) of the situation that triggered this
whole pull request. There are 87 attachments, with 64 "noise" attachments
and only 23 "real" attachments:


Another project turned out like below with 40 attachments, but only 5 of
them were "real".
note that there are many different filenames of the "noise" attachments;
some of them not really obvious:

​

​

**Comment by antonylesuisse** [comment]
This would require a new field on ir.attachment, possible in v10 but probably not in v9.

**Comment by Yajo** [comment]
So no luck on having inline images in v9?

**Pull request closed without merging**
