### PR TITLE
[FIX] website_slides: fix internal user comment will cause error

### PR DESCRIPTION
**Pull request by newlifeoftu**
Current behavior before PR:
https://user-images.githubusercontent.com/104961549/198220315-d25eedb2-eb44-4fd9-b133-fc9d3c78450d.mp4

Desired behavior after PR is merged:
https://user-images.githubusercontent.com/104961549/198220238-00dd9a98-fe2c-4740-b8cd-fee3b34789a4.mp4

I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

### CODE REVIEW

**Comment by newlifeoftu** [comment]
@tde-banana-odoo ping!
@tde-banana-odoo Could u please take a few moments to look over it? Thanks u!

**Comment by hoangtrann** [comment]
I believe you shouldn't ping a maintainer like that, unless it is a severe bug. Odoo team will split the workload to different responsible maintainers to review and merge PR.

Nonetheless, you must have posted the videos with incorrect order (video under desired behavior is giving `404 Not Found`).

Besides, I don't think this is a bug at all, as you are using an user with corresponding access rights, to comment, hide and then edit it. If it was a real user in the portal, he/she should not be able to see the comment made hidden.

**Comment by newlifeoftu** [comment]
Thanks so much because @hoangtrann replied. I have given permission to user, can be admin or employee. all 404 not found error.
I think it's better to change the error message to make it easier for users to see

**Comment by newlifeoftu** [comment]
@gdrius Could u please take a few moments to look over it? Thanks u!

**Comment by qsm-odoo** [comment]
Hello @newlifeoftu, thank you for you suggested PR.

I am really not the one in charge of checking that part of Odoo and even less so for odony, especially when it is not a critical bug from what I understand but rather an IMP.  Like @hoangtrann said, it's best to let us split the workload by ourselves. Here you can see that your PR was automatically flagged for the @odoo/rd-sm team, they will handle this when they find the time (each team works with community PR on GitHub differently). Unfortunately, especially with the recent release of Odoo 16.0, you might have to wait a while before getting an answer.

Thank you for your patience.

**Comment by newlifeoftu** [comment]
Hi  @qsm-odoo, thanks you  for your reply. 
Yes, i know you mean. This happend is not important,only change a little issue ( may be IMP ). 
Thank you for your support.

**Comment by tde-banana-odoo** [comment]
Hello,

Could you clearly explain the issue ? Posting links to videos is not really something that is viable in the long term ^^ .

Cheers !

**Comment by newlifeoftu** [comment]
Hello @tde-banana-odoo ,thanks you for your reply.
When I create a comment, after I change the status button I keep changing the comment, that throws an error. 
And it message on interface user an error : RPC Error  404 Not found. 
I only want change messages error .I think it's better to change the error message to make it easier for users to see.
Hihi. Thanks so much . ^.^

**Pull request closed without merging**
