### PR TITLE
[FIX] website_form: allow inheritance on attachment creation

### PR DESCRIPTION
**Pull request by benwillig**
**Description of the issue/feature this PR addresses:**
When a website form allows file upload and stores thoses files in attachment, it's not possible to change attachment values.

**Current behavior before PR:**
Unable to inherit properly from ```insert_attachment``` attachment method.

**Desired behavior after PR is merged:**
Can inherit from get_attachment_values method.

**OPW 779938**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
Could you describe your use case? We usually accept such changes when one needs to modify the logic inside a method. In this case, it seems that you could simply override the `create` method and alter the values in a custom module.

**Comment by benwillig** [comment]
Our customer wants the filename as the attachment name when there is an application for a job position. I dislike to inherit from ```create``` or ```write``` and I do it only when there is no other solution. Inheriting from ```create``` in this case could have side effects because in some cases, the attachment name must not be the filename. I think that adding a hook is the cleanest solution.

**Comment by nim-odoo** [comment]
@mart-e what do you think?

**Comment by mart-e** [comment]
I try to apply the "non-bug goes to master" policy, also for hooks methods. I have already seen regressions introduced when doing such hooks...
In this method, it is possible to work around with overrides (even if not the cleanest), so sorry but I am not in favour for v10.

**Comment by nim-odoo** [comment]
Same goes for me, so unfortunately we won't accept it.

**Pull request closed without merging**
