### PR TITLE
[FIX] delivery : return None

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
Litle fix
@mart-e 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@fmdl out of curiosity, does it break anything ?

**Comment by fmdl** [comment]
It break nothing (I have find just by reading, :-) ).

**Comment by Yenthe666** [comment]
Then it is not a fix and should be done in master as improvement at best :)

**Comment by fmdl** [comment]
@mart-e moved in master

**Comment by mart-e** [comment]
Thanks, looks good
@robodoo r+

**Pull request closed without merging**
