### PR TITLE
[FIX] mail_plugin: fix underministic test_get_partner_blacklisted_domain

### PR DESCRIPTION
**Pull request by lobaudoux**
This test was underministically failing due to a combination of two factors:
- The domain chosen for the test is selected by
```py
domain = list(iap_tools._MAIL_DOMAIN_BLACKLIST)[0]
```
  which was undeterministic since `iap_tools._MAIL_DOMAIN_BLACKLIST` is a set.
- Since commit 02b5d47, a distinction was made between email providers `_MAIL_PROVIDERS` and the domain blacklist `_MAIL_DOMAIN_BLACKLIST`. The test used `_MAIL_DOMAIN_BLACKLIST` instead of `_MAIL_PROVIDERS`, it should have been adapted. The only difference between the two, at the moment, is the addition of "odoo.com" in the domain blacklist. When that domain is selected, the test crashes.
There is approximately a 1/124 chance of that happening.

### CODE REVIEW

**Comment by lobaudoux** [comment]
Hello @tde-banana-odoo , could I ask you to give this a quick look :eyes: ?

**Review by tde-banana-odoo — APPROVED** [review]
Indeed, making it deterministic is a good idea ^^ Thanks for the fix :)

**Comment by lobaudoux** [comment]
@tde-banana-odoo Thanks for checking :slightly_smiling_face:. Could you r+ it ? :pray:

**Comment by tde-banana-odoo** [comment]
@robodoo r+

Zboing !

**Pull request closed without merging**
