### PR TITLE
[FIX] web_editor: fix attributes missing from cleanForSave

### PR DESCRIPTION
**Pull request by visp-odoo**
**Current behavior before PR:**

When we try to add html data in translated email templates then it does not remove those extra classes from the html code.

**Desired behavior after PR is merged:**

Now when we add html data in translated email template then it removes those extra classes from the html code.

Task-2985072

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dmo-odoo** [comment]
Please change the commit title to `[FIX] web_editor: fix attributes missing from cleanForSave`.

**Comment by hbh-odoo** [comment]
@dmo-odoo Done!

**Comment by dmo-odoo** [comment]
@hbh-odoo Thanks !

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
