### PR TITLE
[FIX] account_move : check acces right to cancel

### PR DESCRIPTION
**Pull request by fmdl**
Impacted version : 11,10,9

Description of the issue/feature this PR addresses:
Buttons was hide by the interface but with RPC you can cancel some Journal Entries.

@qdp-odoo 

OPW : 800611

Regards

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
wait.. what?

what is exactly the use case? it seems to me that the problem are that
* the user may have the write access on account.move where he maybe shouldn't
* the post() and cancel() methods of account.move should maybe be private to avoid direct RPC calls.

So what groups your user has exactly, in your use case?

**Comment by fmdl** [comment]
Today: 
- anyone with access to `write` can `post` by XML-RPC (but by UI you need in this group : `account.group_account_invoice`)
- anyone with access to `read` can `button_cancel` by XML-RPC (but by UI you need in this group : `account.group_account_invoice`)

I think you can not use private function for `<button name="post" states="draft" string="Post" type="object" class="oe_highlight" groups="account.group_account_invoice"/>`

Regards

**Comment by qdp-odoo** [comment]
the button_cancel definitively needs a check of access rights, since it is querying directly the DB and bypassing the ORM. 

For the post(), I think it's okay to rely on the write access rights: adding a group on a button is not a real security measure (and shouldn't).

> I think you can not use private function for <button name="post" states="draft" string="Post" type="object" class="oe_highlight" groups="account.group_account_invoice"/>

Indeed. So we assume it's fine like this with only the check of the write access right upon cancellation.  Do you agree ?

**Comment by fmdl** [comment]
You are right, we don't need to check the groups, because the ACL is in accordance with the user groups in UI:
image

**Comment by qdp-odoo** [comment]
nice :)

fix landed on v9 at revision https://github.com/odoo/odoo/commit/06ccccdb7535a21933457761aa59547614de492b

thanks for the contribution, feedback and fix !

**Comment by fmdl** [comment]
by the way, in `master` we can use `self.write({'state':'draft'})`, because there nothing in the `def write()` to block that.

**Comment by qdp-odoo** [comment]
ha, that's why I was wondering on the reason it was done through a direct DB query... 

I'll check that

**Comment by fmdl** [comment]
Maybe come from a very old version.

Other stuff with `button_cancel` :
It is possible to cancel a move without the module `account_cancel`

Steps to reproduce:
- install account, without account_cancel
- use `import`, `RPC`, `server action` to modify the field `update_posted` to `True` in `account.journal`
- you can use `button_cancel`  by `RPC`, `server action` or by the modification of the view

**Comment by qdp-odoo** [comment]
yes, it's the way it's intended to be. 

Again, hiding fields is not a real security measure, but the write access right of account.journal should prevent anyone to do anything fancy with that update_posted setting.

So, in summary(*): if someone has enough rights on the model to directly call methods through RPC, or modify the UI to let him do something that wasn't planned on the "view level", it's not a problem. That would be a problem if the user could do it without being in a group granting that ACL.

**Comment by fmdl** [comment]
It is not an issue of security, it is just a remark that if `account_cancel` is not install, you can still `cancel`.

**Pull request closed without merging**
