### PR TITLE
[IMP] account: put country_code field in debit note and reversal wizard

### PR DESCRIPTION
**Pull request by jco-odoo**
Community-PR: https://github.com/odoo/odoo/pull/83752
Enterprise-PR: https://github.com/odoo/enterprise/pull/23891

task-id: 2751825

### CODE REVIEW

**Review by Levizar — CHANGES_REQUESTED** [review]
I forgot to ask you to put the task id in commit. :/

**Review by Levizar — APPROVED** [review]
Seems ok to me.

**Comment by jco-odoo** [comment]
@william-andre

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
