### PR TITLE
[FIX] mrp: revert issue introduced by

### PR DESCRIPTION
**Pull request by nim-odoo**
commit message to write properly

### CODE REVIEW

**Comment by jco-odoo** [comment]
I think it is ok, but please make sure you test before merging (push rule for finished products + scrap of raw material/finished products) + producing partially

**Comment by jco-odoo** [comment]
Hm, I think there is still an issue when you do action_consume.  It should copy the production_id there then.  Another way is to inherit the prepare method from the push_apply

**Comment by nim-odoo** [comment]
You mean set the production_id on a new move created by split?

**Comment by jco-odoo** [comment]
indeed

**Comment by nim-odoo** [comment]
Seems ok now. Tested:
- produce all at once
- produce partially
- scrap on raw materials / produced products
- with or without push rule

**Comment by jco-odoo** [comment]
Ok, he does a write manually in the action_consume.  Ok for me.

**Pull request merged**
