### PR TITLE
[FIX] account: prevent update vat with no account user

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
- Create an invoice with partner A
- Connect with no accounting user
- Update VAT --> no raise appear

@oco-odoo 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW #3778177

**Comment by h4818** [comment]
@fw-bot up to saas-15.2
already solve in 16.0 https://github.com/odoo/odoo/pull/136234

**Comment by h4818** [comment]
@fmdl thanks for the fix
could you also apply the same for sale?
don't forget to update the commit message :)

**Comment by h4818** [comment]
@fmdl ping

**Comment by fmdl** [comment]
@h4818 it is updated

**Comment by h4818** [comment]
@robodoo r+

**Pull request closed without merging**
