### PR TITLE
[9.0] fix creation of custom models

### PR DESCRIPTION
**Pull request by rco-odoo**
This is for OPW-657017.

When updating table `ir_model`, use the right value for `state`.
Also fix the instantiation of the model in the registry, to get all parameters consistent.

### CODE REVIEW

**Comment by rco-odoo** [comment]
@KangOl @odony can you review this one? Thanks!

**Comment by KangOl** [comment]
:+1:

**Comment by odony** [comment]
Is there a reference to a bug report?

Apart from the specific fix for the `state` field, shouldn't the rest of the patch, including the signature change, SQL prettifying, etc. be done in `master` or `saas-7` as an improvement? 
Spotting the fix in the patch is not trivial at the moment.

Thanks!

**Comment by rco-odoo** [comment]
@odony sorry, I added a mention to the opw.

This is actually fixing 4d9e36a4590c6d41c88f06d28e6bfe38ec9e4570, which when creating a custom fields, does reset their `state` (critical bug), `name` and `info` (small bug).

**Comment by odony** [comment]
Thanks, that makes a lot of sense now, especially in light of 4d9e36a :-) And #9670 is even smaller than I expected, excellent!
The rest of this patch can be rebased/cherry-picked in saas-7, thanks :+1:

**Comment by rco-odoo** [comment]
Moved to #9770.

**Pull request closed without merging**
