### PR TITLE
[FIX] web: ImageField style

### PR DESCRIPTION
**Pull request by Iucapad**
This commit fixes the style of the field broken
since the introduction of the "display: contents"
rule in css.

### CODE REVIEW

**Comment by sdegueldre** [comment]
I would hold off on this until we can talk about it with AAB. The point of the `display: contents` rule is that fields *can* style themselves (and control their own display property) directly on their elements without having to write any css (eg with bootstrap classes), and this kind of goes against that idea. If we do want to do it in css though, I'd rather increase the specificity of the selector than add `!important`

**Comment by Iucapad** [comment]
@sdegueldre display: contents is fine and solves a lot of issues with fields. I can totally do some of the style fix with bootstrap classes but I would need to add an extra div in the template. Is it better to add this extra div instead of a line of css?
But I'm okay to wait for the return of aab

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by sdegueldre** [comment]
@robodoo r+

**Pull request closed without merging**
