### PR TITLE
[FIX] website_livechat: load im_livechat i18n

### PR DESCRIPTION
**Pull request by Julien00859**
As authenticated user, join the website livechat. As a portal user,
start a livechat. Close it, it asks you to review the chat but all
messages are displayed in english.

opw-1958819

### CODE REVIEW

**Comment by Julien00859** [comment]
@alexkuhn au final ça n'avait rien à voir

**Comment by Julien00859** [comment]
> not having a newline character at the end of a file is a grave sin (in `__init__.py`)

Indeed, I should have added my change as first line so it just changed one line instead of two (I will change)

**Comment by nle-odoo** [comment]
the last newline is not shown, so the only thing this change is that:

`wc -l addons/website_livechat/models/__init__.py`

will report 6 instead of 5

**Comment by Julien00859** [comment]
robodoo r+

**Pull request closed without merging**
