### PR TITLE
[Fix]  Location/Putway Rule to include location_out_id in the domain.

### PR DESCRIPTION
**Pull request by guimarc-br**
[FIX] stock: add location_out_id field domain into the Putaway Rules menu
[REF] models: use `stock` to implement location_out_id into the Putway Rules Menu

Description of the issue/feature this PR addresses:

On the Location/Location-ID/PutwayRule    we have the  fields:

location_in_id = **_When Product Arrives_**

locatio_out_id =  **_Store To_**

As the products arrives in the WH/STOCK location  and due the putaway rules goes to  other location then we have the fields populated like:

location_in_id = WH/Stock

location_out_id = location opened in the view.

 Due this domain setup the list is returning empty, and then the solution that I applied is  to check if we have the location selected in the location_in_id or location_out_id and show  the entries.

Current behavior before PR:

Only looking for the from  into the location_in_id

After PR merged :

Looking  for the values from the location_in_id or location_out_id.

--

TaskID: N/A
Fixes :  PR 67198
Closes : PR 67198

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
I have tested this functionality and works well.

Before PR:
------------

- Created Pullaway Rules
Screenshot_2021-04-30 Putaways Rules - Odoo

- Go to Inventory > Configuration > Warehouse Management > Locations. Find "Store To" location and open a form view. And click on "Putaway Rules" smart button
Screenshot_2021-04-30 WH Stock Shelf 2 - Odoo

- Currently, record can found from the "When product arrives in" location but found 0 records from the "Store To" location
Screenshot_2021-04-30 Putaway Rules - Odoo

After PR:
------------

- Found Putaway Rules form the "Store To" location
Screenshot_2021-04-30 Putaway Rules - Odoo(1)

**Comment by bodedra** [comment]
@mart-e @pedrobaeza @rousseldenis @dreispt @AaronHForgeFlow @LoisRForgeFlow @sbejaoui @brian10048 @marcelsavegnago Hello team, your valuable feedback will be appreciate!

Thanks in advance for your time.

**Comment by Whenrow** [comment]
@bodedra Looks good to me. Could you please reword your commit by following those [guidelines](https://www.odoo.com/documentation/14.0/reference/guidelines.html#commit-message-structure) so I could merge it. 
Thanks

**Comment by bodedra** [comment]
@mart-e @Whenrow Thanks for your review and accept. I will work with PR author @guimarc-br and reword commit notes. Thank you.

**Comment by guimarc-br** [comment]
Hello @Whenrow  @bodedra  I have updated the description  using the guidelines, Please  take a look

**Comment by bodedra** [comment]
@guimarc-br We need to improve this commit message. LMK if you need any help.

Screenshot_2021-05-05  Fix  Location Putway Rule to include location_out_id in the domain by guimarc-br · Pull Request #671

**Comment by guimarc-br** [comment]
Hello @bodedra  I tried to edit the commit message but I push more commits on that then I think I messed-up. Could u please help me to fix that in removing the commits/edit the commit message ?

thank u so much

**Comment by bodedra** [comment]
Yes. I show that. Would you please connect via email at bodedra@opensourceintegrators.com

**Comment by bodedra** [comment]
@guimarc-br Looks good now. Thanks for your time.

@Whenrow @mart-e would you please review it again and let us know if you need any correction. Thank you.

**Review by rousseldenis — APPROVED** [review]

**Comment by Whenrow** [comment]
robodoo r+

**Comment by Whenrow** [comment]
Thank you

**Comment by Whenrow** [comment]
robodoo rebase-ff

**Comment by bodedra** [comment]
Thank you @Whenrow for ff. I have reviewed linked PR and haven't found in v13.0 which we have originally submitted for. Would you please help me to find it out or am I missing here? Thanks again.

**Comment by Whenrow** [comment]
I just have launch the command to merge in other branches. It should be done in the following minutes

**Comment by bodedra** [comment]
Thank you @Whenrow

**Pull request closed without merging**
