### PR TITLE
[IMP] More help text about FEFO

### PR DESCRIPTION
**Pull request by clonedagain**
This readily answers the FAQ "which date is FEFO based on?"

### CODE REVIEW

**Comment by clonedagain** [comment]
Rebased on current upstream. @jco-odoo would you be kind enough to review this please?

**Comment by clonedagain** [comment]
Rebased on latest master.
Can you please tell me if this years-old proposal can finally be merged, or if you're just refusing it?

**Comment by mart-e** [comment]
Ok that was kind of old but we changed the label (and meaning at 5bd4514c6fec80cfc3d7e5353d4e54c8a7b2ed31)

**Comment by clonedagain** [comment]
hehe better late than never :)

**Pull request closed without merging**
