### PR TITLE
[FIX] hr_recruitment: notify interviewers followers

### PR DESCRIPTION
**Pull request by abla001**
Backport of https://github.com/odoo/odoo/commit/6e8795cf5a7d51c4682941a253fb158e8e7e874e

opw-3826768
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sofiagvaladze** [comment]
@abla001 did you check the commit message of the PR? and if so, what you think of it? :thinking:

**Comment by abla001** [comment]
@sofiagvaladze honestly I didn't read all of it, I just checked between version what changed that we don't have the same behavior and from title of commit I thought it was same ! that's my bad :sweat_smile: 
So  for versions < 16.4 it's the expected behavior ?

**Comment by sofiagvaladze** [comment]
@abla001 it's allright ^^

So, you can explain to costumer that prior to 16.4 we logged sensitive info in chatter - like contract info.
Interviewer should not know these stuff.. thus, not to accidentally share this info with interviewer, we just remove him from chatter notifications alltogether.

Since 16.4, it's not a case. 

you can tell customer bad news and good news 
bad news - unfortunately in 16, that's technical limitation for security reason
good news - as soon as they migrate to 16.4+ versions, this won't be a case anylonger

**Comment by abla001** [comment]
@sofiagvaladze thank you so much :pray:

**Pull request closed without merging**
