### PR TITLE
[IMP] models: Support bypassing "order by" on `search` method 

### PR DESCRIPTION
**Pull request by moylop260**
Adds a parameter to be able to run queries without forcing an "order by"
clause. It is useful if you don't need any specific order and you'd like
a faster query.

Currently, it is not possible to remove the 'order by' clause, unless you
run the following ugly code:

    self._order = None
    self.search(...)

This commit supports passing `False` to "order by"
as the `order` argument of the method `search`:

    self.search(..., order=False)

Since it doesn't fetch results in any specific order and without an extra
processing step for queries, it should be faster.

cc @rco-odoo @odony @xmo-odoo

If it is approved
- [x] Apply the same for `read_group()`

### CODE REVIEW

**Comment by xmo-odoo** [comment]
I guess the concept makes sense, though I'm a bit wary of changing the meaning of an existing "valid" value. And you should probably change the _flush_search behaviour to match (it flushes the fields used for ordering in case there are pending writes affecting those).

**Comment by moylop260** [comment]
@xmo-odoo 
Good catch!
Thanks for reply

Fixed

**Comment by moylop260** [comment]
@xmo-odoo 
Sorry for delay
The changes were applied

Thanks @luisg123v

**Comment by xmo-odoo** [comment]
@moylop260 after discussion with @rco-odoo the choice to not allow removing order seems to have been very much intentional and at the prompting of odo: the non-determinism was considered more problematic / risky, and explicitly ordering by `id` (or possibly whatever index you're using if you know you're reliably hitting one) sufficient.

Do you have cases where doing this is still an outsized cost even if you pass in a simpler explicit sort criteria, which gets resolved if you just drop the order spec entirely?

**Comment by moylop260** [comment]
Hi @xmo-odoo 

You have a good point using `order='id'` will be faster than non-indexed default `name`
and it could be enough in the most of cases.

The difference using `order='id'` and `order=''` is ~2.5x faster
But if it is so risky for odoo so maybe it is not a good deal.

<details>
  <summary>~2.5x faster without `ORDER BY`</summary>
  

Running following queries:
 - `EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT field FROM mail_tracking_value ORDER BY id`
 - `EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT field FROM mail_tracking_value`

The result was:
 - Screen Shot 2020-09-04 at 10 18 13

2x faster without `ORDER BY`

And the following queries:
 - `EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT "product_product".id FROM "product_product" WHERE ("product_product"."active" = true) ORDER BY "product_product"."id"`
 - `EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT "product_product".id FROM "product_product" WHERE ("product_product"."active" = true)`

The result was:
 - Screen Shot 2020-09-04 at 10 24 17

</details>

Thanks for reply Xavier

**Comment by xmo-odoo** [comment]
@moylop260 2.5x difference is pretty significant, I'll at least forward your comment to @rco-odoo as that's a useful data point.

**Comment by rco-odoo** [comment]
@moylop260 at first sight, the measures you did look interesting.
But I have to question the relevance of the queries you chose...

#### `SELECT field FROM mail_tracking_value ORDER BY id`

This query should not be considered IMHO, simply because the ORM *never* generates such queries:
* `search` always SELECT the `id` field of the model's table;
* sub-searches through one2many fields may generate such queries, but as `{table}.id IN (SELECT ...)`, and PostgreSQL already ignores the ORDER BY from the sub-select (as there is no LIMIT or OFFSET).

The only place where it would pay off is in a *raw* `read_group` used for computing fields, for instance.
But `read_group`'s API is currently not suited for such use-case.

#### `SELECT "product_product".id FROM "product_product" WHERE ("product_product"."active" = true) ORDER BY "product_product"."id"`

This query could have been generated by the ORM.
But what is the point of getting *all* active products from a *large* database (say 100K products) ?
This clearly does not scale, and nobody would expect this to be efficient, with or without ordering.
No decent developer would do this in business code.
And by the way, we have mostly ruled out those queries from the conversion of domains to SQL thanks to #52403.

So, a realistic search would use a more restrictive domain to get a smaller result (say 1K products).
And the performance of the corresponding query would mostly depend on the WHERE clause, wouldn't it?

That being said, we are now more aware of the impact of the order on queries.
We will always pay attention to that clause in future works on the ORM.

Kind regards,
Raphael

**Comment by moylop260** [comment]
@rco-odoo 
Thanks for reply

> This query should not be considered IMHO, simply because the ORM never generates such queries
...
sub-searches through one2many fields may generate such queries, but as {table}.id IN (SELECT ...), and PostgreSQL already ignores the ORDER BY from the sub-select (as there is no LIMIT or OFFSET).
...
But what is the point of getting all active products from a large database (say 100K products) ?
This clearly does not scale, and nobody would expect this to be efficient, with or without ordering.
No decent developer would do this in business code.

Did you consider many2one.column in the domain?

The worse case is:
 - `self.env['stock.move'].search([('product_id.active', '=', True)], order='id', limit 1)`

It will run a query getting all active products.

```sql
SELECT "product_product".id 
FROM   "product_product" 
       LEFT JOIN "product_template" AS "product_product__product_tmpl_id" 
              ON ( "product_product"."product_tmpl_id" = "product_product__product_tmpl_id"."id" ) 
       LEFT JOIN (SELECT res_id, value 
                  FROM   "ir_translation" 
                  WHERE  type = 'model' 
                         AND name = 'product.template,name' 
                         AND lang = 'en_US' 
                         AND value != '') AS "product_product__product_tmpl_id__name" 
              ON ( "product_product__product_tmpl_id"."id" = "product_product__product_tmpl_id__name"."res_id" ) 
WHERE  ( "product_product"."active" = true )
ORDER  BY "product_product"."default_code", 
          Coalesce("product_product__product_tmpl_id__name"."value", 
          "product_product__product_tmpl_id"."name"), 
          "product_product"."id"
```

After that another query is called:
```sql
SELECT "stock_move".id
FROM "stock_move" 
LEFT JOIN "stock_picking" as "stock_move__picking_id" 
    ON ("stock_move"."picking_id" = "stock_move__picking_id"."id")
WHERE ("stock_move"."product_id" in (1,2,3, ..., 100k_ids)
ORDER BY "stock_move"."id"
LIMIT 1
```

The product query is so complex since that it is combining variant table and language.

I will analyze with partner.
 - `self.env['stock.move'].search([('partner_id.active', '=', True)], order='id', limit=1)`

```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT "res_partner".id FROM "res_partner" WHERE ("res_partner"."active" = true) ORDER BY "res_partner"."display_name"
```

Result
```txt
+--------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                     |
|--------------------------------------------------------------------------------------------------------------------------------|
| Sort  (cost=4009.55..4060.81 rows=20504 width=36) (actual time=707.691..1024.250 rows=40691 loops=1)                           |
|   Output: id, display_name                                                                                                     |
|   Sort Key: res_partner.display_name                                                                                           |
|   Sort Method: quicksort  Memory: 5869kB                                                                                       |
|   Buffers: shared hit=2131                                                                                                     |
|   ->  Seq Scan on public.res_partner  (cost=0.00..2541.09 rows=20504 width=36) (actual time=0.020..338.500 rows=40691 loops=1) |
|         Output: id, display_name                                                                                               |
|         Filter: res_partner.active                                                                                             |
|         Rows Removed by Filter: 318                                                                                            |
|         Buffers: shared hit=2131                                                                                               |
| Planning time: 0.166 ms                                                                                                        |
| Execution time: 1341.939 ms                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------------------+
```

Removing the `order by`
 - `EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT "res_partner".id FROM "res_partner" WHERE ("res_partner"."active" = true)`

```txt
+-------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                              |
|-------------------------------------------------------------------------------------------------------------------------|
| Seq Scan on public.res_partner  (cost=0.00..2541.09 rows=20504 width=4) (actual time=0.020..341.803 rows=40691 loops=1) |
|   Output: id                                                                                                            |
|   Filter: res_partner.active                                                                                            |
|   Rows Removed by Filter: 318                                                                                           |
|   Buffers: shared hit=2131                                                                                              |
| Planning time: 0.077 ms                                                                                                 |
| Execution time: 659.561 ms                                                                                              |
+-------------------------------------------------------------------------------------------------------------------------+
```

2x faster query generated from ORM.

I know, it is the worse case and developers should avoid these kind of domain but let's to check official odoo modules:
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/website_slides/controllers/main.py#L317
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/account/wizard/account_invoice_send.py#L74
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/account_fleet/models/fleet_vehicle.py#L20
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/hr/models/models.py#L16
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/maintenance/models/maintenance.py#L153
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/maintenance/models/maintenance.py#L148
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/payment/models/account_payment.py#L46-L47
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/point_of_sale/models/pos_session.py#L465-L466
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/product_expiry/models/production_lot.py#L92
 - https://github.com/odoo/odoo/blob/ebfd6d4ac26db91a690d48e66ab05dd4373fdb8c/addons/project/models/project.py#L1323
...

But you have a good point nobody would expect this to be efficient, with or without ordering.
So, the issue is more depth than only ordering

Thank you Raphael

**Comment by moylop260** [comment]
For record, 
I just realized that the following query fixes this issue:
 - https://github.com/odoo/odoo/pull/52403

Running the following domain:
 - `env['sale.order.line'].search([('product_id.active', '=', True)])`

The queries of odoo ORM <14.0 vs 14.0 are:
 - https://gist.github.com/moylop260/33c82e29acff3e8bfd338414de694470

It means,

# Queries odoo <14.0
1. Retrieve product_product
2. + product_template
3. + translations
4. order by translated column
5. Filter sale_order_line running 1 query for each 1k products

# Queries odoo >=14.0
1. Retrieve sale_order_line filtering in subquery product_product domain
No product_template
No translation
No order by translated column
No queries for each 1k products

It is amazing!

Kudos @rco-odoo

**Pull request closed without merging**
