### PR TITLE
[FIX] mondialrelay: brand is not a secret, it is public in url

### PR DESCRIPTION
**Pull request by JKE-be**
Allow non system user to get the mondial relay url for tracking parcel.

### CODE REVIEW

**Comment by JKE-be** [comment]
no task, own feedback

**Comment by rdeodoo** [comment]
Out of curiosity, how can I reproduce the issue?
You wrote that code initially so I know it is correct but I'd like to fully figure.
I tried making an order and on the SO link as public user (with token) the link is correctly generated (the field can be read): 
https://18179011-15-0-all.runbot81.odoo.com/my/orders/47?access_token=1f7bffb8-5bcc-4065-8a06-333fca53b1a3
-> https://www.mondialrelay.com/public/permanent/tracking.aspx?ens=BDTEST%20%20&exp=WH/OUT/00030&language=en

**Comment by JKE-be** [comment]
To reproduce:
- Create a Transfert with Carrier Mondial Relay.
- Add tracking reference 
- Send Email -> Use Template -> 'Delivery: send by mail'

My own case, is that I show this link on the view form  ;)
So worst case, since employee cannot open anymore the form view in this case.

**Review by rdeodoo — APPROVED** [review]
@robodoo r+
The brand is already public on the tracking link.

**Pull request closed without merging**
