### PR TITLE
[9.0] FIX ir_sequence - create correct date range for non calendar year

### PR DESCRIPTION
**Pull request by ddico**
Sequences when a non calendar year is required.

**Configuration**
Accounting configuration - Fiscal Year: set a month and/or date different then Dec 31. (Ex: June 30)
Create any document which uses sequences

**Existing situation**
Date range created for subsequences are based on the calendar year, which is not what a user would want:
screen shot 2015-10-03 at 6 44 38 pm

**With this PR**
The proper calendar years are created as per the fiscalyear_last_month and fiscalyear_last_day defined in accounting configuration.
screen shot 2015-10-03 at 6 34 21 pm

### CODE REVIEW

**Comment by ddico** [comment]
@qdp-odoo Can you please provide feedback for this PR? Please see #8877 as well. Thank you.

**Comment by qdp-odoo** [comment]
Wait.. are you sure that's what users may want? because, i can understand you'd need such behavior for your invoices/bills numbering... but here you're touching code that is generically used by potentially all the apps.

With that PR, the sequences of stock moves, procurements, mrp orders, sale orders... will also restart on the new fiscal year. Seems weird to me to send on the 1st of July 2015 the SO/2016/001.

What do you think?

**Comment by wtaferner** [comment]
Actually, as I was pro for the other PR (https://github.com/odoo/odoo/pull/8877), I think ddico is right as the numbering is only very important for accounting (which indicates to act as leading default)...for the rest it is just a numbering, so Quentin the solution can be to introduce a checkbox to make special sequences...now, this would be again an additional feature which is against Odoo's simplifying intentions. For out of the box you are doomed anyway as the fiscal year was removed...any suggestion how to resolve this out of the box? There are some more questions which will arise from the removal of the period and fiscal year but I guess I have to investigate first the new accounting thoroughly and hope to be heard later.

**Comment by wtaferner** [comment]
> When subsequences per date range are used, you can prefix variables with 'range_' to use the beginning of the range instead of the current date, e.g. %(range_year)s instead of %(year)s

Hmm, so there was some considering...what about %(range_from_year)s and %(range_to_year)s

**Comment by ddico** [comment]
@qdp-odoo for a non calendar fiscal year you need to have a clear indication on what **year** the document belongs to.  The fiscal year is assumed to be numbered by the year in which the fiscal year ends (in most places - see footnote). Looking at your example, that is correct, a sales order issued July 1st 2015 has to be SO/**2016**/0001 how else would you know where to file the document in 2015 or 2016? 

And this applies to all the documents (accounting and non accounting) for a company using a non calendar fiscal year.

Again please keep in mind that if accounting is not installed (so... no fiscal year) then numbering goes according with the calendar year and this PR does not interfere with it.

I hope this explains it...  if it doesn't, maybe we can ask other Odoo users from countries where non calendar fiscal year are allowed, to comment on this!?

[footnote]
In [SAP](http://help.sap.com/saphelp_46c/helpdata/en/96/8b2fc843ce11d189ee0000e81ddfac/content.htm) i've seen more flexibility to allow year shift (+1/-1) and fiscal year is either **one** of them (start year or end year)  - but i've never seen a **mix** of the years. Even this extra functionality could be easily implemented by what @wtaferner is suggesting %(range_from_year)s, %(range_to_year)s

**Comment by stephane-mtl** [comment]
Personally, I prefer the sequence to use fiscal year as suggested by ddico when set with range_ for a company that use non calendar fiscal year.  

I implemented both changes #8877 and #8880 on my test server and it’s working exactly as I was expecting. 

I can’t speak for other users but I personally think that having a solution built into Odoo allowing to use fiscal year range as done with the changes suggested by ddico should be offered out of the box by Odoo. 

Thanks ddico for these changes.

**Comment by ddico** [comment]
@qdp-odoo: Can you please review the other comments on this PR? Also #8877?

In regards with your concern with changing the sequence for all the apps please note **nothing** is changed if accounting is not installed or a regular calendar year is used!

If a non calendar year is set by the user then with this two PRs #8877 and #8880 we get Odoo usable. We avoid possible document # duplication (as explained in #8877) and we avoid confusion with calendar date ranges in a non calendar fiscal year.

Unless you can suggest an alternative I don't see how a non calendar fiscal year can be handled in 9.0

Thank you

**Comment by max3903** [comment]
:+1:

**Comment by ddico** [comment]
@qdp-odoo Please review and advise.

**Comment by wtaferner** [comment]
Jep, it would be nice to have a solution for this issue...

If you agree to merge the solution suggested ```%(range_from_year)s``` and ```%(range_to_year)s``` I would be happy to contribute it as it is not a big deal and imho it would resolve the whole issue.

**Comment by antonylesuisse** [comment]
Fixed in https://github.com/odoo/odoo/commit/a2d3d4d449acbd1c07d2a2ec1935193eabaaefcb

**Comment by wtaferner** [comment]
@antonylesuisse 
Same as https://github.com/odoo/odoo/pull/8877

**Pull request closed without merging**
