### PR TITLE
[FIX] web_editor: update image gallery miniatures

### PR DESCRIPTION
**Pull request by younn-o**
When changing an image in the image gallery snippet, its miniature was not updated.

task-2438556

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by sdegueldre — APPROVED** [review]
Same comment as [here](https://github.com/odoo/odoo/pull/65467#pullrequestreview-583439736), code is good but the way the fix works is not obvious and the commit message doesn't agree with the code.

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
Same comment for the commit message guidelines (check all your other commits as well)

**Comment by qsm-odoo** [comment]
Mmh...  I see we already merged https://github.com/odoo/odoo/pull/65249/commits/b3c281b8110d8a2e7668ccaf3bafbf846e3c317f, should we not forward-port this one as well then?

**Comment by sdegueldre** [comment]
@qsm-odoo correct. The fix was different as well so I asked @younn-o to make separate PRs for each version where the fix was different. I wasn't aware you'd usually do that during fw-port even when there are no conflicts.

**Comment by qsm-odoo** [comment]
It's ok, I don't think one way is faster than the other. Just feels more normal to let the forward-port PR automatically references each other via X-original-commit and co. For next time :wink:

**Comment by qsm-odoo** [comment]
@fw-bot ignore

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
