### PR TITLE
[FIX] portal: internal server error if name is boolean

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Internal Server Error for authenticated user in case the name is a boolean (for whatever reason)

**Current behavior before PR:**
Internal Server Error

**Desired behavior after PR is merged:**
Working as expected

@nim-odoo @tde-banana-odoo 
May I ask one of you to review and merge this for me? Thank you in advance.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Hi,

I would prefer a more pythonic writing, like user_id.name[:23] if user_id.name else 'Roberto Carlos' .

**Comment by wtaferner** [comment]
@tde-banana-odoo 
Here we go. Flavoured as you like it...sorry, but the tests are currently out of stock ;-)

**Comment by wtaferner** [comment]
OPW-783507

**Comment by tde-banana-odoo** [comment]
Damned, nim was too fast. Or I was too slow.

**Comment by wtaferner** [comment]
Haha, you had your opportunity and missed it, but maybe next time ;-)

**Pull request merged**
