### PR TITLE
[FIX] website: avoid making the page title separator translatable

### PR DESCRIPTION
**Pull request by bso-odoo**
This commit prevents the "|" between the additional title and the website or company name from being turned into a translatable `span`.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bso-odoo** [comment]
@JKE-be This PR addresses the following problem you raised in the website-in-backend pad:
> Browser tab title is wrong in translation mode (enter "Translate"), it shows html tags: "Odoo - Home &lt;span data-oe-model="ir.ui.view" data-oe-translation-id="68300" data-oe-translation-state="to_translate">|&lt;/span> My Website"

Given that the problem is not blocking I believe the template update is acceptable.
I tried to instead prevent QWeb from generating `translatable` `<span>`s while rendering `<head>` - but unfortunately it cannot work in this case because this `t-set` is done before `<head>`, and at that point there is no way to know whether the value will be used within `<head>` and/or `<body>`.

**Comment by JKE-be** [comment]
or use `t-translate='off'` on the `<title>` tag :thinking:

**Review by JKE-be — COMMENTED** [review]
or use `t-translate='off'` on the `<title>` tag :thinking:

**Comment by bso-odoo** [comment]
> or use `t-translate='off'` on the `<title>` tag thinking

On the `<title>` it is too late, because it is just recovering a value from a `<t t-set>`, but on the `<t t-set>` that does the concatenation, yes. :+1:

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
Maybe remove task-XXX here? I don't think it is related to frontend backend? ^^

**Comment by bso-odoo** [comment]
> Maybe remove task-XXX here? I don't think it is related to frontend backend? ^^

@qsm-odoo Removed.

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Comment by bso-odoo** [comment]
@qsm-odoo Strange, it seems fwbot did not notice this PR...

**Comment by qsm-odoo** [comment]
@bso-odoo Yes, I already added it in my list "what is going on?" and was waiting to see if something happened, I'll ask the runbot team :grimacing:

**Pull request closed without merging**
