### PR TITLE
[IMP] refactor _compute_price_rule method

### PR DESCRIPTION
**Pull request by chafique-delli**
Extract in a method the check of pricelist rules with a given product for easier inherit.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@chafique-delli please fix your refactor test are broken

**Comment by sebastienbeau** [comment]
@rco-odoo @mart-e @tde-banana-odoo can you check this, it's will give new opportunity to add more advanced rule (based on product attribute for example, like discount on all red product).

Thanks

**Comment by tde-banana-odoo** [comment]
More for @Feyensv @tivisse

**Comment by sebastienbeau** [comment]
@tde-banana-odoo thanks for the right notification !

**Review by rco-odoo — COMMENTED** [review]
Looks like a very good idea :clap:

**Comment by sebastienbeau** [comment]
Thanks @rco-odoo

**Comment by tivisse** [comment]
@chafique-delli @sebastienbeau Thanks for your feedback. 

FYI it has been integrated into: https://github.com/odoo/odoo/pull/79605

**Comment by sebastienbeau** [comment]
@tivisse Thanks ! you can close this PR

**Comment by celm1990** [comment]
> @chafique-delli @sebastienbeau Thanks for your feedback.
> 
> FYI it has been integrated into: #79605

For V13, 14, 15 is possible create a PR and is accepted??

**Pull request closed without merging**
