### PR TITLE
[FIX] website_blog: make twitter share string translatable

### PR DESCRIPTION
**Pull request by sdegueldre**
Previously the default message when sharing a blog article was
hardcoded, meaning it was always in English and not translatable, this
commit fixes that.

closes 31173
task-2369420

### CODE REVIEW

**Comment by sdegueldre** [comment]
@qsm-odoo since this adds a translatable string, is there anything specific I need to do here?

**Comment by qsm-odoo** [comment]
@sdegueldre https://github.com/odoo/odoo/wiki/Translations#adding-new-terms-when-suggesting-fixes-in-stable-versions :wink:

**Comment by qsm-odoo** [comment]
Donc juste le fichier .pot à changer :+1:

**Comment by sdegueldre** [comment]
@qsm-odoo should be good now :+1:

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
