### PR TITLE
IoT homepage refactor

### PR DESCRIPTION
**Pull request by lse-odoo**
Overall improvement of the IoT box homepage.

- All "technical" related features have been moved away from the main homepage to a dedicated "Technical" page (accessible from the homepage)
- Icons were added to better represent the homepage information
- (?) with documentation link have been added to more easily find relevant documentation
- Technical menu navigation to the different technical sub-menus
- Improvement security fix by allowing some sensible URL only if some conditions are met. E.g: avoid running subprocess meant for IoT-box on the windows virtual IoT

Visuals are provided in the PR message

Visuals:

<details><summary>Homepage</summary>

</details>

[IoT homepage refactoring preview](https://github.com/user-attachments/assets/48f64acd-6e51-4f43-8ba8-27f2ec9511da)

### CODE REVIEW

**Comment by lse-odoo** [comment]
(waiting for https://github.com/odoo/odoo/pull/161004 to be merged as it is what introduced the Technical Menu )

**Comment by qle-odoo** [comment]
For https it would perhaps be better to be more verbose to indicate that the certificate is not loaded.
And not to use the word "ERROR" because it is not an error.
The idea is not to scare customers

**Comment by lse-odoo** [comment]
TODO: modify the SSH page, put the "ssh" command and make more clear regarding remote debugging

**Comment by lse-odoo** [comment]
> For https it would perhaps be better to be more verbose to indicate that the certificate is not loaded. And not to use the word "ERROR" because it is not an error. The idea is not to scare customers

It will cause an issue in 90% of the case as it will prevent users interacting with their IoT box. It is now in the "technical" menu anyway so people will not really have a look unlike before where it was in plain view. I think verbose information would be more relevant on the documentation where it would make sense with pictures and translations and easier update than needing to upgrade the image if we notice a bad information

**Comment by lse-odoo** [comment]
@odoo/rd-security
There was a ton of security warnings due to the heavy refactoring (splitting big python scripts in different smaller python files). This PR should in fact improve security by removing certain routes that were not making sense on some contexts (like linux subprocess calls on windows computers). Feel free to review it overall, but I didn't added anything new in term of security features (in theory).
Cheers!

**Comment by lse-odoo** [comment]
@qle-odoo ready for your review when you have some time :pray:

**Comment by lse-odoo** [comment]
! some files have been refactored in 17.0 by:
https://github.com/odoo/odoo/pull/169633/files#diff-21f59bbe6fac0e42172ecb752d1da8f3c5bb1d2f364eba0888288d5178d8e14a

might need to re-target in 17.0 to make sure of the compatibility

**Comment by lse-odoo** [comment]
closed in favor of the 17 version:
https://github.com/odoo/odoo/pull/176851

**Pull request closed without merging**
