### PR TITLE
[FIX] web,calendar: don't set static CSS properties in loop

### PR DESCRIPTION
**Pull request by pparidans**
tl;dr : it may be smaller in the SCSS file, but definitely not in the
generated CSS file. Do'nt repeat want can be set once.

These changes result in roughly 130KB gain in the backend bundle.

Follow-up of https://github.com/odoo/odoo/pull/138670

task-3546717

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pparidans** [comment]
@stefanorigano @edi-odoo Watch out with the loops in SCSS as it can generate **a lot** of CSS in the end.

In a nutshell, this PR should keep everything from the calendar's revamp *but* with less CSS generated... 
But I'd love your feedback (and your designer's eagle eye) to be sure I didn't break your recent work in the process... :pray:

**Review by edi-odoo — APPROVED** [review]
Thanks @pparidans ! 
Visual result LGTM, I'll let @stefanorigano check the code

**Review by stefanorigano — COMMENTED** [review]
Thanks so much @pparidans  👍 
I'm pushing 2 fixup on top:
- a6730fe067f3aedf84e9d77d392cf46291e17b30 : reduce code inside loops

- f6e8d8ed1b81eca214694d8f76e72a0f6bc4c0f7 : CSS conventions

@edi-odoo , you'll have to re-check the final result on screen, thanks!

**Comment by edi-odoo** [comment]
> Thanks so much @pparidans 👍 I'm pushing 2 fixup on top:
> 
> * [a6730fe](https://github.com/odoo/odoo/commit/a6730fe067f3aedf84e9d77d392cf46291e17b30) : reduce code inside loops
> * [f6e8d8e](https://github.com/odoo/odoo/commit/f6e8d8ed1b81eca214694d8f76e72a0f6bc4c0f7) : CSS conventions
> 
> @edi-odoo , you'll have to re-check the final result on screen, thanks!

Thanks a bunch @pparidans and @stefanorigano ,
It all looks good to me

**Comment by pparidans** [comment]
@adr-odoo ready for review :+1:

**Review by adr-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
