### PR TITLE
[FIX] website mass_mailing: correctly display popup with footer content

### PR DESCRIPTION
**Pull request by dmo-odoo**
Issue: display the footer tag from snippet in the modal and replace the
save and cancel button.
Steps to see: Email marketing -> mailing lists -> option icon of a
kanban -> Edit -> Website popups -> add a line

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@aab-odoo I have rewritten the test from https://github.com/odoo/odoo/pull/61327. The ball is now in your court... ;-)

**Review by aab-odoo — APPROVED** [review]
Nice test :+1:

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by dmo-odoo** [comment]
@qsm-odoo FYI, you said you were interested to see the fix. This is the bug where you got a snippet inside the footer of the modal rather than the Save and Discard buttons.

This happened because the code used to search for a `<footer>` tag and parse it as the modal custom buttons. However, it was not careful enough to avoid looking *inside* rendered field widgets. So if a field widget happened to have a `<footer>` tag in its rendered html, the system would think it had found custom modal buttons and move them in the modal footer zone instead, potentially creating very random modals like the one you got. The fix is to reject `footer` tags that are children of `.o_field_widget`.

**Pull request closed without merging**
