### PR TITLE
[FIX] base: check that the state matches the country at partner create

### PR DESCRIPTION
**Pull request by len-foss**
Import a list of partners with their addresses.
The state_id field is usually filled with the state codes.
E.g. 'CA' is used for California, but also for Cádiz (Spain), etc.
The import function (db_id_for) uses a name_search on the res.country.state,
and takes the first matching result.
It follows that the state does not necessarily match the country.

Therefore we override the create to check that the country matches the state's
country, try to find a correct match, and if we can't we put the state to False.
Note that if the country is not set both fields will end up set to False:
this is because only a state would mean using a code could give an abitrary
country.

opw 1943904

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by len-odoo** [comment]
Thanks, removed the exists and updated the comment.

**Comment by len-odoo** [comment]
@nim-odoo Now optimized for batch create.

**Comment by Yenthe666** [comment]
I've got a feeling this seriously slows down performance on big imports honestly. Has this been tested with imports that have a few thousand lines?
I honestly think it should go in master too.

**Comment by len-odoo** [comment]
For F1, F2, two files with 1024 contacts, 
where in F1 all state/country matchings are correct, 
and they are all incorrect in the case of F2.

Then we have that the following import timings:
Without fix:
    F1: '0:01:19.282454'
    F2: '0:01:17.768148'
With fix:
    F1: '0:01:24.449568'
    F2: '0:01:20.593547'
On a standard Odoo toaster. 
The performance impact seems extremely marginal. 
I haven't tested the fix for a file with 10000 contacts, 
since it took '0:08:45.139335' without the fix already. 

So in any case the fix is not going to change the whole story there.

Note that XMO is already working on improving the import performance 
where it really matters (not here).

**Comment by Yenthe666** [comment]
Okay that is good to hear. Less impact than I assumed.
Thanks @len-odoo 👍

**Comment by len-odoo** [comment]
robodoo r+

**Pull request closed without merging**
