### PR TITLE
[FIX] mail: return str instead of bytes when post processing attachment

### PR DESCRIPTION
**Pull request by nboulif**
Steps to reproduce:

  On Odoo:
  - Install `Documents` module
  - Go to `Settings` and set a Custom Email Server(ex. `mydomain.com`)
  - Ensure an alias exist for the model `document.document` with
    `inbox-financial` as alias name

  In mail client:
  - Send a mail with an image in the body to the following email:
    inbox-financial@mydomain.com

Issue:

  Mail not received (traceback in logs)

Cause:

  Since we use the email alias `inbox-financial`, we process the mail
  through the `document.document` model where we have an override of the
  `_message_post_after_hook` method that is called after that the
  `msg_values` values are post-processed and where we do another
  message_post() for the new document create for the attachment (in
  this case, an image).

  https://github.com/odoo/enterprise/blob/2c3596e4e18c201809558d3ea878b141e366a027/documents/models/document.py#L305

  During the parsing, the mail values are updated through the
  `_process_attachments_for_post` method:

  https://github.com/odoo/odoo/blob/6c0d2d7a9d44459f3e09a38bd80ef9b018e8c946/addons/mail/models/mail_thread.py#L1881-L1904

  On posting the first time, the original type of the `body` value is a
  `str`, but the post-processed value (because there is some CIDS in the
  body) is of type `bytes` (because using `encoding='UTF-8'` with
  `lxml.html.tostring`).

  https://github.com/odoo/odoo/blob/510a997017a9cbe14522a0013a578f6d1d9b257a/addons/mail/models/mail_thread.py#L2209

  Then in the `_message_post_after_hook` we call post again on the
  newly created document record by using post-processed value of body
  who is of type `bytes`.

  On posting the second time (for the document record), the `body`
  value is of type `bytes` and when checking if the body is empty with
  `is_html_empty` that received a string as param, an error is
  raised.

Solution:

  Use `encoding='unicode'` to return a string instead of bytes.

  https://lxml.de/api/lxml.etree-module.html#tostring

opw-3273583

### CODE REVIEW

**Comment by nboulif** [comment]
Hello @tde-banana-odoo , may I ask you some insight on this one? Thanks in advance!

Other possible fixes:
- in _message_post_after_hook, ensure msg_vals.get('body', '')  is a string by wrapping it with tools.ustr
- in _process_attachments_for_post, either at the beginning (since tools.ustr done further on the body) or when doing is_html_empty(message_values['body']), convert it to a string with tools.ustr
- in _process_attachments_for_post, when post processing the cids, update the body value with 'unicode' as encoding instead of 'UTF-8' (to return a string instead of a byte object; https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.tostring )

Regarding the last solution, I would think that it's the best fix, but wasn't sure of the reason for the 'UTF-8'.
By looking a bit in the code, most often we use `ustr` on the update body value and therefore have no issue when it's a byte object.

cc @flch-odoo

**Comment by nboulif** [comment]
Hello @tde-banana-odoo :slightly_smiling_face: 
After checking with @xmo-odoo , fixing the encoding of the update body value (to return `str` instead of `bytes`) make more sense since the input body is of type `str` at first.

**Comment by nboulif** [comment]
> Shouldn't we fix in earlier versions also ?
Indeed, forget to do it (since issue triggered in this version), my bad.

> Side note: can't we have a small unit test, e.g. https://github.com/odoo/enterprise/pull/44857 which seems related ?
Already did but for the document side since did not find another flow that trigger a message_post a second time...

**Comment by nboulif** [comment]
@tde-banana-odoo 
> Shouldn't we fix in earlier versions also ?

Indeed, forget to do it (since issue triggered in this version), my bad.

> Side note: can't we have a small unit test, e.g. https://github.com/odoo/enterprise/pull/44857 which seems related ?

Already did but for the document side since did not find another flow that trigger a message_post a second time...

**Comment by yelizariev** [comment]
This PR looks similar to https://github.com/odoo/enterprise/pull/44857/files

It's for saas-16.1 and has tests. Maybe you could adjust those tests for v14 ?

**Comment by nboulif** [comment]
Closing this PR to create a new one ( https://github.com/odoo/odoo/pull/133339 ) since the related ENT PR is based on another Odoo version (and breaks the ci checks).

**Pull request closed without merging**
