### PR TITLE
8.0 fix packops quant assignement

### PR DESCRIPTION
**Pull request by clonedagain**
When quants are assigned for a move, and we use pack operations to do the move, the pack-move link is created without taking the location of the quant into account.
As a consequence, even when users accept the proposal of the scheduler, quants may be split instead of just being moved, because the wrong quant gets assigned to the wrong operation.
To fix this, add an extra condition on the quant search during pack-move reconciliation.

This proposal contains a test to prove the corner case is not currently handled correctly, and a fix.

### CODE REVIEW

**Comment by clonedagain** [comment]
@jco-odoo would you be kind enough to take a look at this please? I think I found a corner case where quants are wrongly split because they're linked to the wrong pack operations.

**Comment by clonedagain** [comment]
@lbellier for your information

**Comment by clonedagain** [comment]
@jco-odoo have you had time to consider this change please?

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
