### PR TITLE
[FIX] base_import: dark mode file import

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
- Enable dark mode
- import a file :
 -- CRM > favorites > import records
-- upload a file

Bug:
Background is white

Fix:
remove CSS property (Background is already white in light mode and shouldn't be in dark mode)

opw-3029509

### CODE REVIEW

**Comment by HANNICHE-Walid** [comment]
select field color:

https://github.com/odoo/enterprise/pull/35552

**Review by nle-odoo — APPROVED** [review]
looks good to me but I'm not familiar with this

**Comment by HANNICHE-Walid** [comment]
https://github.com/odoo/odoo/pull/109735 similar issue

**Review by anso-odoo — COMMENTED** [review]
Hello, looks good to me. For a better result you could also use `$border` instead of the hard coded color values at lines 28, 113 and 145. 

Thanks !

**Comment by morm-odoo** [comment]
Ok for me

**Comment by HANNICHE-Walid** [comment]
thanks a lot for the review
r+ please?

**Review by nle-odoo — COMMENTED** [review]
robodoo delegate+

**Comment by HANNICHE-Walid** [comment]
thanks Nicolas
@robodoo r+

**Pull request closed without merging**
