### PR TITLE
[FIX] fields: write correct related value when target override

### PR DESCRIPTION
**Pull request by seb-odoo**
To reproduce the issue:
- define 2 models, one which has an _inherits to the other
- the parent models should override write to alter the given value
- write on the child model

Before the commit the value written on the child would be the given value before
override, desynchronized from the value actually written on the parent.

---

Introduce failing tests to highlight the issue.

These problems where highlighted by failing runbot on PR https://github.com/odoo/odoo/pull/37363 after an apparently inoffensive change.

### CODE REVIEW

**Comment by rco-odoo** [comment]
The pull request #37426 already handles the case of inherited fields.
Are the other cases really necessary?

**Comment by seb-odoo** [comment]
I didn't know about the other PR. After it is merged, I will check again and let you know about this.

**Comment by seb-odoo** [comment]
I cherry-picked the other commit (and removed my diff) and it appears to fix the issue highlighted here.

Do we want to also keep the tests I wrote here or not? Otherwise this can be closed.

**Comment by rco-odoo** [comment]
The other PR has a test that reproduces the issue.
I think we don't need to add more to the PR.

**Comment by seb-odoo** [comment]
I'm reopening this in https://github.com/odoo/odoo/pull/38181 with target at v13, because since the approach on the other PR was changed, the issue is not fixed by it.

**Pull request closed without merging**
