### PR TITLE
[FIX] Recognition on Inventory Values for products in foreign currenc…

### PR DESCRIPTION
**Pull request by hbto**
[FIX] Recognition on Inventory Values for products in foreign currency shall be
done based on rate Transaction Date

According to IFRS
Reporting foreign currency transacti ons in the functional currency [1]
Pages 12 - 14
http://www.ifrs.org/Documents/Module30_Version_2011_09.pdf

### CODE REVIEW

**Comment by nim-odoo** [comment]
Hello,
Thank you for your PR. 
Indeed, the document states: 
> An entity shall record a foreign currency transaction, on initial recognition in the functional currency, by applying to the foreign currency amount the spot exchange rate between the functional currency and the foreign currency at the date of the transaction. 

However, we assume that the order date is the transaction date. This allows you to settle your transaction, and encode it later in your system. With your fix, you assume the transaction date is today, which might not be the case.

Therefore, we cannot accept your PR.
Regards

**Comment by hbto** [comment]
Though you are assuming that the Purchase Order Date is the date when you accrued your inventory, and under IFRS that is misleading because you are using and old date which could be quite wrong,
by using today, which _the_ only date that Odoo uses for posting we are using a more rightful value to compute inventory value.

I do not share your point of view.

**Comment by nhomar** [comment]
@nim-odoo 

I think your interpretation is incorrect of the statement you mentioned.

One thing is the " initial recognition in the functional currency " which can be interpreted as the "Exchange rate" is in the "Order date" (it is not true in our contries BTW, the rate is when operation is effectivally done well in the reception or in the invoicing with even difference between them, order date is absollutly out of scope to decide such dates).

BUT the "transaction" MUST to be done in the date of the operation itself, not in the date of the order.

Let me give you some "normal example":

1. Purchase to China.
2. It takes 4 month to arrive your element to your warehouse.
3. Receive elements BUM! you already closed fiscally your periods you statement fails. and this is the point which is solving @hbto here, because you are valuation your inventories in a past date and increasing them incorrectly.

With the solution proposed to hbto.

3. Receive elements aml will be done today (which is absolutly correct), the date where Landing costs, Fiscal affectation for imports where "recognized". the recognition of an amount is not ever a not legal document (the PO) is the "Fiscal Document" either the aml or the invoice.

The block of text you mentioned (which I do not know the origin it should be cool to read other interpretations)  is incorrectly interpreted on your side, or simply such date should be "configurable" or ar least inheritable.

We can make the inheritable PR for such block of text.

Regards.

**Comment by nim-odoo** [comment]
Thank you for the clarification. Originally, it was decided to do the valuation at the date of the purchase. This is indeed different from the IFRS reporting standards, but still makes sense.

However, we cannot merge your PR since it introduces a change in the behavior of the method. Other people might rely on the fact that the valuation is done on the purchase order date.

Regards

**Comment by nim-odoo** [comment]
Note that we would be glad to consider another PR which would allow to keep the current behavior.

**Comment by nhomar** [comment]
@hbto 
can you refactor your PR to convert such value in a inheritable method please?.

Regards.

**Pull request closed without merging**
