### PR TITLE
[FIX] crm: get pls probabilities with sudo

### PR DESCRIPTION
**Pull request by tfr-odoo**
Portal user that have opportunities in their portal
may change the stage of the opportunity
Changing the stage on the portal trigger
direcly the method write.

With the pls, write on the stage
trigger the recompute of the probabilities
that read on crm.lead.scoring.frequency
which portal user don't have acess

Solution: compute probabilities in sudo mode

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
> Portal user that have opportunities in their portal
> may change the stage of the opportunity

Really? Not sure why we want to allow this but that's not the point...

> Solution: compute probabilities in sudo mode

LGTM :+1:

**Comment by tfr-odoo** [comment]
@robodoo r+

**Comment by tfr-odoo** [comment]
@mart-e can you r+ this pr ?

**Comment by mart-e** [comment]
@robodoo r+ :tada:

**Pull request closed without merging**
