### PR TITLE
[IMP] mail: correctly fetch custome data when sending invite

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
https://www.odoo.com/web?debug#id=1967234&model=project.task&view_type=form&menu_id=5200

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Ping @Xavier-Do

**Comment by CasVissers** [comment]
@tde-banana-odoo 
Is there a replacing PR for this commit?

**Comment by rafaelbn** [comment]
OPW 2063423

**Comment by rim-odoo** [comment]
Still working on it.

**Comment by tde-banana-odoo** [comment]
Deleted by mistake actually.

**Comment by Yajo** [comment]
So, any news on this one? :thinking:

**Comment by CasVissers** [comment]
Bump

**Comment by rim-odoo** [comment]
This PR is still ongoing in our internal review process and is not forgotten in the limbo. Thank you for your patience.

**Comment by CasVissers** [comment]
Closed again?

**Comment by tde-banana-odoo** [comment]
Sorry I cleaned various staging branches, deleted that one by mistake.

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
