### PR TITLE
[FIX] doc: clarify "supported browsers"

### PR DESCRIPTION
**Pull request by rim-odoo**
Because the current doc does not mean anything clear :D

### CODE REVIEW

**Comment by Feyensv** [comment]
Are we sure we want to reduce browser support on old versions ? :thinking:.
NB: a kinda similar update was done in https://github.com/odoo/odoo/pull/40602 for 13.0.

**Comment by rim-odoo** [comment]
> Are we sure we want to reduce browser support on old versions ? .

We don't, we *always* supported browsers that are supported by their publishers. We simply state this fact explicitly ;)

**Review by Feyensv — APPROVED** [review]

**Comment by rim-odoo** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
robodoo retry

**Pull request closed without merging**
