### PR TITLE
[l10n_cn] Fix language

### PR DESCRIPTION
**Pull request by jeffery9**
Description of the issue/feature this PR addresses:

correct lanage for l10n_cn_small_business

Current behavior before PR:

Desired behavior after PR is merged:

fix #21169 and #18512

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Thank for the correction !
I have moved it to apply on the saas-11.3 instead of master. Could you confirm it is ok before I merge it?

**Comment by jeffery9** [comment]
yes, it is ok.

**Comment by pedrobaeza** [comment]
@elicoidal can you confirm too?

**Comment by mart-e** [comment]
Merged at 123b7138c2d, thanks

**Pull request closed without merging**
