### PR TITLE
[FIX] sale_stock : Reconfirming a canceled SO with kit create delivery

### PR DESCRIPTION
**Pull request by nmarotte**
Issue: In a SO, when canceling a confirmed SO with a validated delivery,
when we re-confirm that SO, a new delivery order is generated

Steps to reproduce :
1) Install sale_management, sale_mrp
2) Create a quotation for a product :
  - with BoM which is a KIT with component : any product (storable)
3) Confirm, Cancel, Set to Quotation
4) Reconfirm -> Bug

Why is that a bug:
 When the product is not a kit, for the same use case, no delivery order
 is generated

opw-2647856

### CODE REVIEW

**Comment by nmarotte** [comment]
The failing test is because `_compute_quantity` doesn't take kits into consideration. at all .
If we try to convert 3 Liters of quantity to Unit (Number of kits) of a kit that needs 1 Liter per Kit, the _compute quantity could return 3, but instead it raises an error

It wasn't raised before because the kits never passed the .filtered I changed, but maybe it should ? i don't really see why kits should be discriminated against and simply ignored in that for loop

**Comment by nmarotte** [comment]
In case anyone read this, I am still waiting to have a discussion on the test, IMO the test should not fail but was designed at a time where that specific use case was not registered as wrong

**Comment by DjamelTouati** [comment]
Done on: https://github.com/odoo/odoo/pull/79387

**Comment by nle-odoo** [comment]
fw-bot close

**Pull request closed without merging**
