### PR TITLE
[IMP] website_hr_recruitment,google_recaptcha: auto install online job

### PR DESCRIPTION
**Pull request by mba-odoo**
Currently, website_hr_recruitment(online job) is not auto installed when hr_recruitment and website is installed.

So in this commit, auto install the online job(website_hr_recruitment) when only website and hr_recruitment is installed.
so removed website_partner dependency from website_hr_recruitment as it's not really needed. also make the website_hr_recruitment and google_recaptcha auto install.

TaskID: 2374617

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@tivisse 

It is a recent spec to force google_repatcha to autoinstall False, so please don't reenable it !

**Comment by tivisse** [comment]
@robodoo r-

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
