### PR TITLE
Master timesheet grid to validate with last period xbo

### PR DESCRIPTION
**Pull request by xavierbol**
## [IMP] {hr,sale}_timesheet: remove grid_range inside the context

This commit removes `grid_range` inside the context because this context
will be no longer used in the grid view and that context should not be
defined in the community version since the grid view is only available
in enterprise.

## [IMP] hr_timesheet: add missing helper in timesheet action

task-3893907

### CODE REVIEW

**Review by auon-odoo — APPROVED** [review]
LGTM! :slightly_smiling_face:

**Comment by xavierbol** [comment]
robodoo rebase-ff r+

**Comment by xavierbol** [comment]
robodoo rebase-ff r+

**Comment by xavierbol** [comment]
robodoo rebase-ff r+

**Pull request closed without merging**
