### PR TITLE
[IMP] web: update ace editor to 1.32.3

### PR DESCRIPTION
**Pull request by SimonGenin**

### CODE REVIEW

**Comment by SimonGenin** [comment]
@robodoo rebase-ff

**Comment by SimonGenin** [comment]
@aab-odoo Review & override false positive boostrap stuff
@odoo/rd-security A bunch of false positive: a local variable called `location` flagged as `window.location`. Could I have the override please ?

**Review by aab-odoo — APPROVED** [review]
robodoo rebase-ff r+

**Comment by rfr-odoo** [comment]
@robodoo override=ci/style
CSS rules inside JS file

**Pull request closed without merging**
