### PR TITLE
[FIX] sale: Force Description field visible in SO

### PR DESCRIPTION
**Pull request by lade-odoo**
When creating an SO, we have the capability to create a Section/Note.
When we filter the Description field, we can no longer view the Sections/Notes content.
Furthermore, when filtering the Description field, we can no longer create a Section/Note.

To reproduce the issue:
1. Create a new SO with one item (for simplicity)
2. Create a note/section
3. Filter out the Description field
We can no longer see the content of the note/section newly created.

Solution: The bug is raised because a Note/Section is basically an `order_line` which its content is stored
in the Description (`name`) field of an `order_line`. A javascript trick is done in the UI to properly display
the Section/Note. However, when we filter the Description field, we obviously also hide the content of the notes/sections. The solution here was to add another trick in javascript by extending some existing classes. The idea is to,
instead of removing the Description columns from the HTML entirely (as it is done when we filter in a normal way).
We simply hides the Description column (using display:none CSS style) expect for the Notes/Sections rows.

opw-2819904

### CODE REVIEW

**Comment by MiniLau** [comment]
An alternative solution would be to make the `Description` field non-mandatory but that would restrict the usage of the SO.

**Comment by kitan191** [comment]
This seems a little overkill for such an use case.

Would it not be simpler to just prevent users from hiding `name` field by removing `optional="show"` here: https://github.com/odoo/odoo/blob/ceeae85d1d99b5b249a9d322806421069fee5bd7/addons/sale/views/sale_views.xml#L479
as it is done for PO lines and invoice lines?

**Comment by MiniLau** [comment]
Yeah ofc we can do that (as I have stated as the alternative solution), but I taught that the description might be useless for some clients (as for the one who raised the issue) so I did not wanted to disable it.

**Comment by MiniLau** [comment]
As discussed above, the change was adapted to make the Description field non optional (commit message updated).

**Pull request closed without merging**
