### PR TITLE
Master slides fixes tde

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by xmo-odoo** [comment]
robodoo r-

Maybe put in a merge message which is not crap?

**Comment by xmo-odoo** [comment]
robodoo r+

sorry hadn't seen this was ff'd

**Comment by tde-banana-odoo** [comment]
Thanks @xmo-odoo :dancer:

**Comment by xmo-odoo** [comment]
tenor

**Pull request closed without merging**
