### PR TITLE
[FIX] core: performance of serializing many2one fields in onchange()

### PR DESCRIPTION
**Pull request by rco-odoo**
The performance issue was found in the reconciliation widget, when trying to reconcile a batch of about 500 payments.  In that case, the computation of field `display_name` for many2one values being returned took most of the time and was making many SQL queries.  We found out that the prefetching of the many2one values wasn't effective, since its implementation relies on the many2one field's values in cache, and the cache is invalidated just before serializing the result of `onchange()`.

We fix this issue by explicitly collecting the ids of the many2one values by model, and reusing those ids as prefetching when serializing many2one values.

In our test case, the time taken by `onchange()` went from 2.75s to 1.00s (-65%), and the number of SQL queries went from 1036 to 32.

task-id 3617517

### CODE REVIEW

**Review by h4818 — APPROVED** [review]
Seems to work for me, drastic reduction in queries

**Comment by rco-odoo** [comment]
@fw-bot ignore

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
