### PR TITLE
[FIX] account_edi_ubl_cii: remove eas 0037, 0215

### PR DESCRIPTION
**Pull request by aliyatastemirova**
EAS codes 0037 and 0215 have been deprecated as of OpenPeppol eDEC codelists v8.9
https://docs.peppol.eu/edelivery/codelists/changelog.html

We are placing a warning in stable and removing the selection options in master.

Upgrade PR: odoo/upgrade#6273

no task

### CODE REVIEW

**Comment by aliyatastemirova** [comment]
Related: https://github.com/odoo/odoo/pull/173316

**Comment by aliyatastemirova** [comment]
@lordkrandel hi! I assigned you here because you were automatically assigned on the related pr in stable, I hope you don't mind :slightly_smiling_face:

**Review by lordkrandel — COMMENTED** [review]
LGTM 👍🏻 

@smetl for final review.

**Comment by lordkrandel** [comment]
@aliyatastemirova does this need an upgrade script to remove the value from old partners?

**Comment by aliyatastemirova** [comment]
@lordkrandel yes: https://github.com/odoo/upgrade/pull/6273 :slightly_smiling_face:

**Comment by lordkrandel** [comment]
Added to PR description for future reference 👍🏻

**Review by smetl — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
