### PR TITLE
[FIX] orm: sort translatable fields

### PR DESCRIPTION
**Pull request by beledouxdenis**
This PR is not yet complete. It needs
- [x] Use case test
- [ ] A performance analysis, with databases having a large amount of records (For instance, a lot of product template and/or product variants, along with their translations set).
- [x] Documentation comments
- [ ] Review

### CODE REVIEW

**Comment by KangOl** [comment]
When I told you to add the `add_condition_args` argument, I thought it will be used in argument of `cr.execute()`
The way it's currently used is useless and make code harder to read.
Use cr.mogrify to generate the query with escaped values (function now have to take the cursor as first parameter)
The `alias` placeholder has to be injected with the `.format()` method

```python
add_condition=cr.mogrify("AND {alias}.name =%s AND {alias}.lang = %s AND {alias}.value != ''", [trans_name, lang])
```
```python
self.add_conditions[(lhs, join_tuple)] = add_condition.format(alias=alias)
```

**Comment by beledouxdenis** [comment]
cr is not available in that place.

**Comment by KangOl** [comment]
For the lack of `cr`, you should have to make the escaping yourself :disappointed: 

For formating, it's simply a matter of readability (it's avoid percent escaping) (and [docs](https://docs.python.org/2.7/library/stdtypes.html#str.format) say "This method of string formatting [...] should be preferred to the `%` formatting").

**Comment by beledouxdenis** [comment]
The python doc says so, no our standard, apparently. 

I would also have preferred to use the format method, but I won't go against our standards :).

**Comment by rco-odoo** [comment]
This feature has been taken over in #7091.

**Pull request closed without merging**
