### PR TITLE
[IMP] collect ids and add them en bloc afterwards

### PR DESCRIPTION
**Pull request by hbrunn**
For big lists, this gives me an order of magnitude speed improvement

### CODE REVIEW

**Comment by Yenthe666** [comment]
@hbrunn this looks like a good addition and makes sense. About how much faster does this make the collecting of ids? I'm curious.

**Comment by hbrunn** [comment]
@Yenthe666 this depends entirely on how long the list is, as the performance penalty grows with the list. In my test case, I had a many2many referring to ~3000 records, which took 2 seconds to load on my machine before, and some hundred ms afterwards.

**Comment by Yenthe666** [comment]
Thats a great improvement! I'm curious how the guys from Odoo will respond to this.
Thanks @hbrunn :+1:

**Comment by rco-odoo** [comment]
@hbrunn this looks like an interesting optimization.
When I wrote this algorithm, I tried to make something elegant, but I did not consider performance to be a problem. I was wrong: the algorithm is quadratic in time, while it should ideally be linear.
I will make an alternative proposal with your optimization applied to the *whole* loop.

**Comment by hbrunn** [comment]
@rco-odoo great to hear, I'm excited about your take on this

**Comment by odony** [comment]
@hbrunn Would you mind closing this PR, as being superseded by #7376? Thanks for identifying this optimization!

**Comment by hbrunn** [comment]
@odony not at all, #7376 looks better

**Pull request closed without merging**
