### PR TITLE
[FIX] l10n_it_stock_ddt: the date should be the date done not creation

### PR DESCRIPTION
**Pull request by jco-odoo**
Ticket link: https://www.odoo.com/web#id=3266332&model=project.task
opw-3266332

### CODE REVIEW

**Review by lordkrandel — APPROVED** [review]
LGTM
image

**Comment by ushyme** [comment]
Hello, any news on this ?

**Comment by william-andre** [comment]
It is conflicting

**Comment by jco-odoo** [comment]
I will see if I can unconflict

**Comment by jco-odoo** [comment]
@lordkrandel @william-andre Conflict resolved.

**Pull request closed without merging**
