### PR TITLE
9.0 website sale fixes nim

### PR DESCRIPTION
**Pull request by nim-odoo**

### CODE REVIEW

**Comment by nim-odoo** [comment]
@antonylesuisse : Finally I didn't include the onchange on the pricelist in sale.py. I would have included a change of behavior in a stable release.

**Comment by beledouxdenis** [comment]
Seems ok to me for the first commit.

Regarding the second : 
 - Well, first, I am not a big fan of having multiple fixes in one commit. It's not easy to know which change is for which issue. But, I can accept it I guess. 
 - Second, I do not believe removing the call to the `onchange_partner_id` is such a good idea: 
   - You repeat the code in two different places
   - It will no longer be possible to customize the order values, while it was the case before by overriding `onchange_partner_id`

  But I indeed see no other way to do it, other than overriding `onchange_partner_id` to allow to not reset the pricelist somehow. We will require Antony's input for this.

The other things seems ok :)

**Comment by antonylesuisse** [comment]
Yes please split the second commit.

**Comment by nim-odoo** [comment]
The commit are now split.

**Comment by antonylesuisse** [comment]
When the partner has a pricelist it should be used

**Comment by nim-odoo** [comment]
> When the partner has a pricelist it should be used

The computed field pricelist_id calls _get_pricelist_id:
https://github.com/odoo-dev/odoo/blob/9.0-website_sale-fixes-nim/addons/website_sale/models/sale_order.py#L126

And _get_pricelist_id calls itself get_current_pricelist:
https://github.com/odoo-dev/odoo/blob/9.0-website_sale-fixes-nim/addons/website_sale/models/sale_order.py#L204

Which uses the pricelist of the partner by default:
https://github.com/odoo-dev/odoo/blob/9.0-website_sale-fixes-nim/addons/website_sale/models/sale_order.py#L212

I'd like to stress that the only place in the code/templates where website.pricelist_id was used before my commit was there: https://github.com/odoo-dev/odoo/commit/4eb2274b4f4500ecbcf41af3b2b32975f1754a58#diff-cf00d16a9ce1440df9ec66a522633604L172
And it was properly replaced by the pricelist of the partner. If I missed another place, let me know.

**Pull request merged**
