### PR TITLE
[FIX] Issue #4424

### PR DESCRIPTION
**Pull request by max3903**
Fix issue #4424

### CODE REVIEW

**Comment by max3903** [comment]
In Odoo:
https://github.com/odoo/odoo/pull/4427

**Comment by foutoucour** [comment]
:+1:

**Comment by xmo-odoo** [comment]
Why the nested function?

Also the behaviour already exists in exp_drop, you may want to extract that part as was done in 8.0, then just call that function from exp_duplicate.

**Comment by odony** [comment]
Indeed, please extract the existing code from `exp_drop()` into a separate function, e.g.  `_close_connections(cr, db_name)` and reuse that.
Thanks!

**Comment by odony** [comment]
Your patch also introduces a possible SQL injection vector through the database name parameter, please always [leave parameter formatting to psycopg](https://doc.odoo.com/contribute/15_guidelines/coding_guidelines_framework/#no-sql-injections-please). The code in `exp_drop` is correct with regard to that.

**Comment by matrixise** [comment]
Just for 9.1 and >= 9.2 ? and 9.0 (September 2015) ? See http://www.postgresql.org/support/versioning/

**Comment by xmo-odoo** [comment]
> Just for 9.1 and >= 9.2 ? and 9.0 (September 2015) ?

The message is a bit iffy, but the 9.1 case really covers up to 9.1, and the 9.2 case covers 9.2 and up.

**Comment by xmo-odoo** [comment]
Welp I merged the patch by mistake, so I'll just fix it up in post.

**Pull request merged**
