### PR TITLE
[FIX] l10n_ch: render QR code and Swiss cross on qr bills

### PR DESCRIPTION
**Pull request by adwid**
When printing several qr bills, some pdf may not contain the QR code
and/or the QR codes do not contain the Swiss cross.

To reproduce the error:
(Debug mode must be enable)
1. Set the company as a Swiss one
        - Set also the street, the city and zip code
2. Set the company's bank account (e.g., CH15 3881 5158 3845 3843 7)
3. Go to Settings > Technical > Reports > QR Bill, click on "Add in the
'Print' menu"
4. Create a Swiss customer
        - Set his street, city, zip code and country
        - Set his bank account (e.g., CH56 0483 5012 3456 7800 9)
5. Create two invoices for this customer, Post them
6. Go to Invoices, select these invoices, Print > QR-bill
7. Repeat step 6 a few times and look at the result each time

ERR: Often, the first page is the only one that contains the QR code and
the next invoices do not have one. Sometimes, the QR codes do not
contain the Swiss cross.

When rendering the invoices, the server first generates the HTML version
of the invoices. It creates the images using their path as source:
- `<img src="/report/barcode/..."` for the QR code
- `<img src="/l10n_ch/static/..."` fot the Swiss cross

Then, the server asks `wkhtmltopdf` to convert the generated HTML files
to a PDF. Here is the issue: it seems `wkhtmltopdf` does not correctly
get and render the images. The issue does not come from the server: all
HTTP requests used to get the images are always done correctly. Moreover,
the `wkhtmltopdf` documentation does not provide anything to force the
images to be correctly rendered. This is the reason why this fix directly
encodes the QR code in the HTML files, so `wkhtmltopdf` does not have to
get any image.

OPW-2426314

### CODE REVIEW

**Comment by adwid** [comment]
@jpp-odoo 
Perhaps I should extract the Swiss cross data to another file ?
I could also delete the image: https://github.com/odoo/odoo/blob/3a883e67287cbf0c93a746bc2080b897f2c87bfa/addons/l10n_ch/static/src/img/CH-Cross_7mm.png I think it will not used anymore after this commit

**Review by oco-odoo — CHANGES_REQUESTED** [review]
It's super hacky, and clearly not a proper way of doing that to me. Can't we rather simply try reporting that to wkhtmltopdf first?
(also, you probably want to do that in v12 instead of v13; I think v14 won't need it, but it needs to be checked) 

This use case is pretty advanced as it requires changing the default configuration of the module to enable the printing action on multiple records, so I think we can wait a little longer and just report the problem.

**Comment by adwid** [comment]
@oco-odoo The solution for the QR code is to render the image directly in the HTML instead of rendering it in the PDF, is it really a problem ?
However, I agree the solution for the Swiss cross rendering is very hard-coded... I could report it to wkhtmltopdf, but since I have no idea if they are responsive or not, we could apply this fix while I try to find another solution with them ? That way, in the meantime, our Swiss customers can continue to print their QR bills, what do you think ?

**Comment by oco-odoo** [comment]
@adwid 
Again, this is non-standard and people need to reconfigure the action to face the error ; so it's unlikely more than one single customer has to wait for a proper fix. I think it's worth reporting it, as if you do it later and they fix it, we won't be able (or at least, it'd be a very bad idea) to go back, and will have to keep crappy code just because we merged it too soon. Plus, saying "I'm not reporting because they won't answer" is probably not very accurate, right ? :p

I quickly discussed it with las (who has some experience in playing with wkhtmltopdf). To him, it could simply be some kind of time out option occuring (which would explain the nondeterminism of your test). He advised to have a look at the code returned here https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/models/ir_actions_report.py#L459 ; did you check that? Maybe we could learn something from it.

**Comment by adwid** [comment]
@oco-odoo 
> Plus, saying "I'm not reporting because they won't answer" is probably not very accurate, right ? :p

Yes, of course ! That's not what I meant :) I'm going to report the issue

I did not check the returned value in the code, I actually made the tests directly from my terminal. Here is a screenshot: 

As you can see, when it correctly renders the invoices (green rectangle), it actually considers that something went wrong (see output in the terminal). However, when the rendering skips at least one image (red rectangles), wkhtmltopdf does not log anything...

Therefore, considering this discussion: I close this PR, I advise the client to print his invoices one by one and wait for wkhtmltopdf to fix the issue. Do you agree with this ?

**Comment by oco-odoo** [comment]
@adwid You can even keep the PR open while we're not sure what wkhtmltopdf says if you want. Indeed, I think we should just tell the customer that *for now*, he has to do it one invoice at a time, and that we reported the issue and will keep him posted when it's okay to print them in batch again. Be clear to him that it probably won't be immediate, though.

**Comment by adwid** [comment]
(Issue created: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4927)

**Comment by yvaucher** [comment]
This is still an issue.

I doubt we can solve this on wkhtmltopdf quickly and users are affected since a while. (2 months have passed and no answer on wkhtmltopdf)

This looks like related to https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3715
Which has been open since Nov 11, 2017

Here is an other attempt to fix it in a more generic way phttps://github.com/odoo/odoo/pull/67292

**Pull request closed without merging**
