### PR TITLE
[FIX] web_editor: fix flickering issue when applying the stretch toggle option

### PR DESCRIPTION
**Pull request by rahg-odoo**
Before this PR:

- An intermediate image was briefly visible when the stretch option
was applied, causing a flickering effect.

After this PR:

- The intermediate image is no longer visible, eliminating
the flickering issue.
- A cloned image element is used during the processing of the
actual image, ensuring that the intermediate image is hidden.

task-4206947
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by divy-odoo** [comment]
LGTM, @rahg-odoo  Just resolve the conflict and we are good to go for next stage.

**Review by bvr-odoo — COMMENTED** [review]
Hi @rahg-odoo 
- This is actually a more general issue; it doesn't only occur when the stretch option is toggled. It also happens when previewing shapes, when previewing the "Filters" for an image (even without a shape), etc ...  So maybe your "clonedImage" fix could be used for all cases, but I'm not sure if it's the right way to fix that and even if a fix is possible. It's due to "preview mode === reset," which is used for all options but which is more visible for images. Maybe it's something we should handle ourselves in Belgium. What do you think, @qsm-odoo ?

**Comment by bvr-odoo** [comment]
> To clarify with Lionel what he had in mind but yes, maybe we should not even do anything.

cc @lebl-odoo 😉

**Comment by rahg-odoo** [comment]
> Hi @rahg-odoo
> 
> * This is actually a more general issue; it doesn't only occur when the stretch option is toggled. It also happens when previewing shapes, when previewing the "Filters" for an image (even without a shape), etc ...  So maybe your "clonedImage" fix could be used for all cases, but I'm not sure if it's the right way to fix that and even if a fix is possible. It's due to "preview mode === reset," which is used for all options but which is more visible for images. Maybe it's something we should handle ourselves in Belgium. What do you think, @qsm-odoo ?

Hi @bvr-odoo you're right. due to preview mode === reset, intermediate state is visible when changing options of either filter or shapes. "clonedImage" fix was suggested by @sobo-odoo  in task-3678061. this PR is just a addon to that task to stop showing intermediate states while processing image by hiding through it's clone. not sure regarding filter right now but I guess this can work for filter previewing with shape on as well.
Thank you!

**Comment by bvr-odoo** [comment]
As explained in this PR and on the task chat, this is actually a more general issue.
Fixing it only for stretch option is not enough. Taht's why we close this PR

**Pull request closed without merging**
