### PR TITLE
[TYPO]

### PR DESCRIPTION
**Pull request by nseinlet**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by KangOl** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@nseinlet does it look like I've not enough PR to review already? :-D

**Comment by nseinlet** [comment]
@qdp-odoo No it's more like you don't review enough.

**Comment by qdp-odoo** [comment]
yes you're right... I was closing my eyes the whole 2 seconds I took to review that small insignificant PR otherwise I would have for sure spotted it.

**Pull request closed without merging**
