### PR TITLE
[ADD] l10n_din5008: isolate din 5008 from l10n_de

### PR DESCRIPTION
**Pull request by epictete**
DIN 5008 is not specific to Germany.
It also applies to Switzerland, Austria (& Lichtenstein).

The goal is to make DIN independent from l10n_de,
for Switzerland and Austria.

Task: 2613993

### CODE REVIEW

**Comment by william-andre** [comment]
You can't manipulate module dependencies and fields like that in stable :boom:

**Comment by epictete** [comment]
That's what I was afraid of :sweat_smile: 
Is there a way to make it work in `14.0` or should we just target `master` instead (I don't think it is crucial to do this in `14.0`) ?

**Comment by william-andre** [comment]
100% only doable in master

**Comment by epictete** [comment]
Closed in favor of odoo/odoo#76227 which targets `master`.

**Pull request closed without merging**
