### PR TITLE
[FIX] mrp: Wrong move destination during production

### PR DESCRIPTION
**Pull request by agr-odoo**
Create a new production location [LOC]
Create a product [PROD] with [LOC] as production location.
Create a manufactured product [MANU] with [LOC] as production location and
[PROD] in bom. The bom consumption type has be flexible.
Create a MO with [MANU], validate and reserve.
When producing add a new component, validate.

The component move created by the wizard does not have as destination the
[LOC] of the product that we are manufacturing, but the default one.

opw-2319675

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@fw-bot ignore

**Comment by agr-odoo** [comment]
@nim-odoo

**Review by nim-odoo — APPROVED** [review]
robodoo delegate+

**Comment by agr-odoo** [comment]
@robodoo r+

**Comment by agr-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
