### PR TITLE
[FIX] point_of_sale: fiscal position map to empty tax

### PR DESCRIPTION
**Pull request by caburj**
This commit fixes the following faulty behaviors:

1. There is a traceback in the pos ui when the selected
customer has fiscal position that maps a tax to nothing.
To prevent this behavior, we avoid to add the undefined
tax destination.

2. When you change the customer in pos ui from someone who
has fiscal position to someone without, the tax in the
order remains to be based on the previous customer. The
tax should change to original tax of the product or
to the tax mapped by the default fiscal position of
the session. To avoid this behavior, we now set the
default fiscal position on the order when a customer has
no fiscal position.

**To reproduce:**

**Issue 1. Error when `product1` is selected for `partner1`**

*Steps:*
1. create fiscal position `fpos` that maps `tax1` to nothing
2. assign `fpos` to `partner1`
3. activate fiscal position per order in pos.config and add `fpos`
4. assign `tax1` to `product1` (should be available in pos)
5. open new pos session
6. select `product1`
7. issue: error when selecting `partner1` as customer

*Reason.* In `_map_tax_fiscal_position`, `tax=undefined` is pushed to `taxes`.

**Issue 2. Tax for `partner1` is active in `partner2` even if
`partner2` has no fiscal position.**

*Steps:*
1. create fiscal position `fpos` that maps `tax1` to `tax2`
2. assign `fpos` to `partner1`
3. activate fiscal position per order in pos.config and add `fpos`
4. assign `tax1` to `product1`
5. open new pos session
6. select `product1` -> tax should be `tax1` since no customer
7. select `partner1` -> tax changed to `tax2` because of `fpos`
in `partner1`
8. issue: select new customer without fiscal position -> tax
should be `product1`'s original tax because no fiscal position,
but tax from previous customer is not changed.

*Reason.* If the newly selected customer has no fiscal position,
order.fiscal_position is not updated so it takes the old fiscal position.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pimodoo** [comment]
could you change the commit tittle from '[FIX] pos: fiscal position map to empty tax' -> '[FIX] point_of_sale: fiscal position map to empty tax'

Can you also remove the steps to reproduce from the commit message, and explaining why there is a problem and how we fix it.

Example: When we change the customer on a pos order, if a fiscal position had been applied for the first one and the second doesn't have any fiscal position. The taxes set on the order remains the one from the first customer. To avoid such a behavior, we now set the default fiscal position on the order when a customer has no fiscal position.

We also fixed the fiscal position mapping, because when a tax mapping had no destination tax, it was raising a traceback. So we don't try to add the destination tax anymore when there is no destination tax

**Comment by caburj** [comment]
@pimodoo Done. Do I also need to remove the steps from the conversation?

**Comment by pimodoo** [comment]
robodoo r+ rebase-ff

**Comment by pimodoo** [comment]
robodoo r+ rebase-ff

**Pull request closed without merging**
