### PR TITLE
[10.0][IMP] purchase: Update date planned on lines

### PR DESCRIPTION
**Pull request by rousseldenis**
Description of the issue/feature this PR addresses:

If Purchase Order remains draft and user change order date,
update lines that don't have been generated through procurements

Current behavior before PR:

Create a purchase order. The order date is today by default.
Add lines. The individual scheduled dates are computed with vendor lead time, product lead time.
Change the purchase order date (e.g. : if you want to order later).
The scheduled date on lines are not recomputed.

Desired behavior after PR is merged:

Create a purchase order. The order date is today by default.
Add lines. The individual scheduled dates are computed with vendor lead time, product lead time.
Change the purchase order date (e.g. : if you want to order later).
The scheduled date on lines are recomputed.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Cedric-Pigeon @lmignon @mreficent

**Comment by rousseldenis** [comment]
@simongoffin @nim-odoo @jco-odoo Your remarks on this would be useful!

**Comment by sbidoul** [comment]
Makes sense to me from a functional point of view.

**Comment by C3POdoo** [comment]
Dear @rousseldenis,

Thank you for your contribution but the version 10.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
