### PR TITLE
[IMP] tests: object wrapper for freezetime

### PR DESCRIPTION
**Pull request by d-fence**
Using freezegun.freeze_time decorator on a test class is discouraged.
This can lean to strange behaviors and faulty results because of the
lack of setUpClass cleanup.

With this commit, a `freeze_time` object is created in odoo test
common utilities to replace the freezegun one. It uses the real
freezegun under the hood but adds a patcher when used on a test class.

Also, it can handle most of the usages in Odoo, like the context manager
and the test method decorator. That way, the `import` from freezegun can
just be replaced by the odoo one when needed.

### CODE REVIEW

**Review by kmagusiak — APPROVED** [review]

**Review by xmo-odoo — APPROVED** [review]
Should remember to update the ci/style warning to mention this wrapper if / when it's merged.

**Review by Megaaaaaa — APPROVED** [review]
LGTM, nothing changed in the accounting tests so if they pass, i'm fine with it and the freeze_time class LGTM (with xmo's remarks ofc) too so consider rd-accounting okay with this :+1:

**Comment by d-fence** [comment]
robodoo r+

**Comment by d-fence** [comment]
robodoo rebase-ff

**Comment by Ysoroko** [comment]
Hey @d-fence since we are missing `freezegun` package on the current IoT image this PR introduced an issue.
I have created a PR to just `try/except` the import of freezegun and avoid calling freezegun if it's not there, could you take a look at it just in case to make sure I don't modify the desired behavior?
https://github.com/odoo/odoo/pull/178089

**Pull request closed without merging**
