### PR TITLE
[IMP] hr: improve employee image placeholder

### PR DESCRIPTION
**Pull request by stefanorigano**
task-3568588

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @odoo/rd-hr , fp request. 
Thanks!

**Comment by stefanorigano** [comment]
Hello @odoo/rd-hr , little reminder ;)

**Comment by sofiagvaladze** [comment]
robodoo r+

**Comment by sofiagvaladze** [comment]
@stefanorigano a very rundom test is failing, but that's being said, it blocks merging  :grimacing: 

I tries to rebuilt it, didn't do the trick. Would you mind rebasing and pushing again? It needs to be green for it to be merged

**Comment by stefanorigano** [comment]
@sofiagvaladze , all green, thanks :)

**Comment by sofiagvaladze** [comment]
robodoo r+

**Pull request closed without merging**
