### PR TITLE
[IMP] mail: remove ComposerTextInputComponent/_getContent 

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2579306

### CODE REVIEW

**Comment by oomsveta** [comment]
ci/upgrade_enterprise angry 👺

**Comment by alexkuhn** [comment]
Hm... This looks out of scope of PR, but there's something close to Discuss team: `mail.channel.is_member`...

Will try just a rebase and 🤞it's green

**Review by oomsveta — APPROVED** [review]

**Comment by oomsveta** [comment]
oops conflicting files

**Comment by alexkuhn** [comment]
Moved in grouped PR: https://github.com/odoo/odoo/pull/88692

**Pull request closed without merging**
