### PR TITLE
[FIX] sale_timesheet: prevent error when adding timesheets w/o sale rights

### PR DESCRIPTION
**Pull request by luisg123v**
Prior to this commit:

    - If a user without access to sales tries to add timesheets on a task that
      comes from a sale order, the following access error is raised:

        Access Error

        You are not allowed to access 'Sales Order Line' (sale.order.line) records.

After this commit:

    - A user without access to sales will be able to add timesheets to a task that
      comes from a sale order without any error.

task-2566750
opw-2525342

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by luisg123v** [comment]
Hi @moylop260 or @nhomar,

Could you review, please?

CC @hugho-ad

**Review by hugho-ad — APPROVED** [review]

**Review by moylop260 — APPROVED** [review]
@nim-odoo 

What do you think?

**Review by IT-Ideas — COMMENTED** [review]
LGTM, thanks for this fix 🙂 

My I just ask you to update the commit message as follow in order to fit with our commit message guidelines? :
```
    [FIX] sale_timesheet: prevent error when adding timesheets w/o sale rights
    
    Prior to this commit:
    
        - If a user without access to sales tries to add timesheets on a task that
          comes from a sale order, the following access error is raised:
    
            Access Error
    
            You are not allowed to access 'Sales Order Line' (sale.order.line) records.
    
    After this commit:
    
        - A user without access to sales will be able to add timesheets to a task that
          comes from a sale order without any error.
    
    task-2566750
    opw-2525342

```

Thanks !

**Comment by luisg123v** [comment]
@IT-Ideas I just updated the commit message as you suggested, thanks!

Could you check again, please?

BTW, I though I was already following the guidelines.

**Comment by IT-Ideas** [comment]
Hello @luisg123v 🙂 

Thanks, yes indeed you did well.

I just added the internal ticket and task ids which you could not know.
And the small nitpicking could also be that the commit message header should start with a verb as it should complete the sentence `if applied, this commit will ...` as described [here](https://www.odoo.com/documentation/14.0/developer/reference/guidelines.html#commit-message-header)

Thanks again 🙂

**Comment by luisg123v** [comment]
@IT-Ideas great! I'm always in favor of nitpicks :smile:

**Comment by IT-Ideas** [comment]
@robodoo r+

**Comment by IT-Ideas** [comment]
@robodoo retry

**Pull request closed without merging**
