### PR TITLE
[FIX] stock : picking.state is already tracked with trackvisiblity

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
- create a picking with 2000 stock.move, confirm
- split 200 stock.move
--> The picking.state was compute each split (=create) for the tracked system. But the time to compute the state with 3000 stock.move is arround 3 secondes.
Time to slip : 200 * 3s = 10 minutes.

Nota : the picking.state is tracked with trackvisibility.

Without this tracking : 1 minute

@jco-odoo 
@odony 
@alnslang 

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@fmdl 
I just did a little check on this and it seems indeed a bit weird and the code was pushed forward almost unquestioned (at least on the surface). @tde-banana-odoo already put a note in the code. 

Did you check the background of commit https://github.com/odoo/odoo/commit/d349584f9d281ea955f4a46235747c9b9866daa6?
Maybe you could use some context to avoid redundant tracking?

Maybe @beledouxdenis can explain why it was forward ported or if it is still needed and if it was a mistake to fix the OPW at all, but I guess the issue should be fixed where it is supposed to be fixed (track_visibility in the low-level implementation [```_write```](https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L3122) which I doubt would be wise for the exact same performance reason if not very smartly implemented by explicitely make it possible to track even computations for needed situations). 

Somehow I guess the rational is still alive (if it was ever valid), but on the other side the impact on performance was the reason for this PR and valid too as it seems to be a hack since 9.0 and it is about computed field change tracking.

**Comment by nhomar** [comment]
**Informative**:

>> Somehow I guess the rational is still alive (if it was ever valid), but on the other side the impact on performance was the reason for this PR and valid too as it seems to be a hack since 9.0 and it is about computed field change tracking.

It is, we are having this performance problems and even worst in odoo.sh it is killing the connection and in testing environments in little implementations (little number of users but big purchases) it is almost unusable on v11.0.

I do not know if the PR is the right solution but the problem is real!

**Comment by beledouxdenis** [comment]
Well, by re-reading my commit message, the revision d349584f9d281ea955f4a46235747c9b9866daa6 was about making work the `track_visibility`, as it was not working at the time on computed fields.

The revision targeted the old API. If the `track_visibility` works in the new API on computed fields, then this block of code could indeed be removed.

Especially, the case I mention in the above revision, with the back orders going back and forths, should be well tested to be sure there is no gap or weird behavior in the discussion thread regarding the state changes notifications.

**Comment by wtaferner** [comment]
Ok, then I guess @rco-odoo is the right person in accordance with @tde-banana-odoo to figure out if the solution provided earlier is still the only way to have the correct result or can be safely removed. The less code in write and create on specific module level for generic features the better.

Probably writing a decent test (performance and integration wise) as mentioned by @beledouxdenis for the exact same issue would be the way to go I guess (I know a PR is welcome, but I am not an expert yet in writing tests properly). 

The computed fields are really great but also sometimes are a bit difficult to grasp, but slowly I learn until they will be refactored for the sake of evolution in order to start over :smiley:

**Comment by jco-odoo** [comment]
I wanted to get rid of track_visibility on the state of the picking all together.  The code of @beledouxdenis was initially done for earlier versions, but if we remove it, not sure if it is still needed and if it will indeed solve the perf issues.  @sle-odoo

**Comment by sle-odoo** [comment]
AFAIK track_visibility doesn't work on computed field, that's why it is done in the create and write. If you're working with large amount of picking/moves and want to bypass this logic, you could always add a `mail_notrack` in the context.

Regards

**Pull request closed without merging**
