### PR TITLE
[IMP] web: update of PDF.js to version 4.7.76

### PR DESCRIPTION
**Pull request by rfr-odoo**
This commit updates the lib PDF.js and restores the custom config made by Odoo in PDF.js.

Changelogs:
* https://github.com/mozilla/pdf.js/releases/tag/v4.4.168
* https://github.com/mozilla/pdf.js/releases/tag/v4.5.136
* https://github.com/mozilla/pdf.js/releases/tag/v4.6.82
* https://github.com/mozilla/pdf.js/releases/tag/v4.7.76

task-4255281

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rfr-odoo** [comment]
Hello @odoo/rd-security

The runbot (ci/security) trigger on
```javascript
    cssStyle.textContent = `${hiddenElements.join(", ")} {
    display: none !important;
}`;
```
where i have some change to to be better to read also to hide new edit buttons in PDF.js.
For me it's safe as `hiddenElements.join(", ")` make a static string and `hiddenElements` is static too.

Can I have a skip ci for this PR. Thx

**Comment by mart-e** [comment]
@rfr-odoo the diff is a bit hard to process but can you check the `isEvalSupported` is always false for us?

**Comment by rfr-odoo** [comment]
> @rfr-odoo the diff is a bit hard to process but can you check the `isEvalSupported` is always false for us?

Yes we disable scripting in PDF.js and i have tested with some PDF files with script in it.
It should be the same patch as the old one.

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: needed commits are still here

**Review by pparidans — APPROVED** [review]
@robodooo r+

**Comment by pparidans** [comment]
@robodoo r+

**Pull request closed without merging**
