### PR TITLE
[FIX] models: restore warning on wrong record

### PR DESCRIPTION
**Pull request by mart-e**
Was lost during d5b687a48ffb

### CODE REVIEW

**Comment by KangOl** [comment]
Not needed if #27659 is merged as it will fail before...

**Comment by mart-e** [comment]
@KangOl ok for your PR but could you catch CSV errors as well?

**Comment by KangOl** [comment]
You'r right, the warning is still useful for csv files.

**Comment by rco-odoo** [comment]
robodoo r+

**Pull request closed without merging**
