### PR TITLE
Master reconciliation split payment csn

### PR DESCRIPTION
**Pull request by csnauwaert**
task: 1870895

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
that's perfect for me.

@csnauwaert Can you squash your commits in 1 with a nice commit message please?

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by moylop260** [comment]
@qdp-odoo
Is there a plan about backporting it to stable versions?

**Comment by qdp-odoo** [comment]
no

do you need a reminder of our stable policy? :grin:

**Comment by moylop260** [comment]
hahaha
no man sorry
I meant, 
Do you have planned an extra auto-install module or another stable way to migrate it to v12.0?

FYI there are tickets asking for this feature for SAAS
E.G. 1903354

I understand that we need to wait v13.0
But I prefered asking you directly in order to know the plan and give a better support.

Thanks for reply.

**Comment by moylop260** [comment]
Got it
Thank you

**Pull request closed without merging**
