### PR TITLE
[FW][FW][ADD] l10n_ar: refunds with liquido docs

### PR DESCRIPTION
**Pull request by zaoral**
Two modifications related to document types of type "liquidación"

Do not allow to use liquido producto on Sales POS, they are mean to be used in purchases
Previously only document 99 was able to be used on invoices and refunds, now we add more documents ('186', '188', '189') and we also fix export to VAT book (if a document for invoices is used for refunds it should be exported with negative amounts)
This PR goes together with https://github.com/odoo/enterprise/pull/21662

--
I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

Forward-Port-Of: https://github.com/odoo/odoo/pull/83226

### CODE REVIEW

**Comment by zaoral** [comment]
Hi @jco-odoo 
Leave here a video with an explanation about why we made this change.
https://drive.google.com/file/d/1jOTuS76_rDa09n7DL6O_kwPE8tX3g-ui/view
If there is any doubt we can review it at today's meeting.

Best Regards

cc @vbe-odoo @jjscarafia @Bruno-Zanotti

**Comment by vbe-odoo** [comment]
@vbe-odoo FUN test

**Comment by vbe-odoo** [comment]
Hi @zaoral I tried this and I have the following comments:
1. Vendor side: I've created a Refund (credit note of a Vendor Bill > Doc Type Code (186) - Credit note for liquidacion de compra and another Credit Note with Doc Type (3) - Nota de Credito A
2. Customer side: Then I created a regular Credit Note for a Customer Invoice ((3) NOTAS DE CREDITO A)
3. In both cases I see in the Sales/Purchase Vat Book report (not the TXT but in the view in Odoo) that in both cases the amounts are negative (sales/purchase vat book for those invoices)
4. But I can't export the TXT as I do have the traceback that you solved in the other PR (so I can't check the TXT to see if the amount are ok)

I don't know if it correct to see the negative amount for the refund in the Purchase VAT Book report in Odoo (as in the TXT needs to be positive as far as I understand > but I couldn't see the TXT)
Screenshots:
image
image
image

Thanks!
cc' @fvz-odoo @ren-odoo @jco-odoo

**Comment by jco-odoo** [comment]
This need to be checked with the pr https://github.com/odoo/enterprise/pull/24255#issuecomment-1035297580 later after merging.

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
