### PR TITLE
[FIX] website: hide optimize seo menu when model is not seo capable

### PR DESCRIPTION
**Pull request by rdeodoo**
When user creates a new 'livechat channel' in website, and click on 'Optimize SEO' a traceback will appear.

Step to reproduce:
- Install 'website' and 'im_livechat' module
- Go to 'website' module
- Click on 'NEW' and then create a new 'Livechat Widget'
- Go to 'Site' and click on 'Optimize SEO'

Error: A traceback appears: Invalid field 'website_meta_title' on model 'im_livechat.channel'

The menu should not be shown for such model which do not inherit the SEO mixin. This commit ensures that.

sentry-4241511888

### CODE REVIEW

**Comment by rdeodoo** [comment]
@qsm-odoo @pierre-pde Thinking about it, I am a bit surprised that we have "+ New Livechat Widget" in the "+ New" screen in 16.0, following this commit from YOL: https://github.com/odoo/odoo/commit/ca2e143d54622d598201826a2cd669bad64b205d
Was it part of the frontend > backend merge task? Why not I guess, it just seems "advanced/weird" compared to the other straightforward "records" you can create from there.

@qsm-odoo @detrouxdev If you want to have a look at the diff, I am a bit unsure about it myself. It's coming from a sentry PR which was fixing the python side (consequence) instead of the js side (root cause), see https://github.com/odoo/odoo/pull/125863#pullrequestreview-1502634557
Note that we need to not remove the "Optimize SEO" in existing database which won't do a `-u` (most of them).

**Review by detrouxdev — APPROVED** [review]
It seems good to me on the technical part 👍🏻 (On a side note, would be nice if there was an until to check if a model inherits another model so that we don't arbitrarily use one of the field's name. But that's probably overkill.)

**Comment by pierre-pde** [comment]
@rdeodoo , to be honest, I don't remember how it was decided to add the "+ new livechat ..."
But, I like that this "+ new" screen act as a list of features that we support.
Even though, I agree with you, that adding a livechat is very different than adding a page, I don't think it hurt us because vast majority of our users should understand what a livechat is :)

**Comment by rdeodoo** [comment]
@robodoo delegate=@loco-odoo I added myself an entry in the reviewer sheet, here is the delegate +1

**Comment by loco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
