### PR TITLE
[FIX] web_editor: correctly display custom filter options

### PR DESCRIPTION
**Pull request by loco-odoo**
Steps to reproduce the bug:
- Add a "Cover" snippet on the website.
- Add a "Custom" filter on the image.
- Put the "Blur" setting to the maximum.
- Save and edit.
-> The "Blur" setting is not on maximum anymore.

Since [1], the dataset of background images is first filtered (by the
elements inside of the `BACKGROUND_IMAGE_ATTRIBUTES` set) before being
copied into the dataset of `this.img`. Because `filterOptions` was
missing in the set, the values of the custom filter were not displayed
correctly (see `_computeWidgetState()`).

[1]: https://github.com/odoo/odoo/commit/31ba9060723f365d16d51d3de0acf42c5e95f63b

task-3358051

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo delegate=Guillaume-gdi

**Review by Guillaume-gdi — COMMENTED** [review]
@loco-odoo Don't forget to make the PR ready for review and the Odoo task RD-green when you finished your work :wink: This way your task will have the chance to go to the BE/IN testings phases and we will reduce the risk to introduce a new bug. In any case I'm going to check out this PR thoroughly :+1:

**Review by Guillaume-gdi — APPROVED** [review]
Just a little nitpick about the commit message:
In markdown, you have to add a blank line after a list. otherwise you end up with this:
image

I will not block the PR just for this so let's merge :rocket: 

@robodoo r+

**Comment by loco-odoo** [comment]
@Guillaume-gdi , note that this commit should only be merged in V14 as V15 and later are already fixed (see https://github.com/odoo/odoo/commit/9b11abda493500cc79ce6f6f8df3f2e3855900b0)

**Comment by Guillaume-gdi** [comment]
I should have done this before r+ but let's see :eyes: 

@fw-bot ignore

**Pull request closed without merging**
