### PR TITLE
[FIX] tools: fix IoT compatibility

### PR DESCRIPTION
**Pull request by Ysoroko**
The recent PR #171722 introduced the use of stdnum and zeep Python libraries in odoo/tools/_monkeypatches.py

Now when connecting an iot box to a database Odoo never starts on it as the IoT Box Image 24_01 doesn't have these libraries.

This PR adds the try/except around the imports of them and adds a check to make sure that the variables defined through these libraries exist

With these try/except the IoT Box works as expected

### CODE REVIEW

**Comment by Ysoroko** [comment]
@odoo/rd-security could I get an override please?
The only thing modified here are the try/except blocks added

@jmak-odoo @lobaudoux
Could you double-check that with this change the code you introduced in the PR https://github.com/odoo/odoo/pull/171722 works as expected? This is a big priority for us as the PR mentionned above broke the IoT Box in all the stable versions

Thank you

**Comment by mart-e** [comment]
@robodoo override=ci/security
Funnily we had the same issue on the doc server. I wasn’t going to patch it only for us but if you have this also on the IoT…

**Comment by jmak-odoo** [comment]
Hello @Ysoroko, I tested the change and the timeout is still working as expected! Sorry for the unexpected side effect :)

**Review by qle-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
