### PR TITLE
[FIX] sale,*: product configurator fixes

### PR DESCRIPTION
**Pull request by Feyensv**
Task-2998514

Enterprise PR: https://github.com/odoo/enterprise/pull/32273

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by AntoineVDV** [comment]
@robodoo override=ci/security
Reason: false positive on 'markup' being triggered because it is re-introduced after having been temporarily removed in https://github.com/odoo/odoo/pull/101304.
Link to ci/security build (16.0): https://runbot.odoo.com/runbot/build/19915349

**Review by Demesmaeker — APPROVED** [review]

**Comment by Feyensv** [comment]
@robodoo r+ rebase-ff

**Comment by d-fence** [comment]
robodoo r-
warnings in staging
https://runbot.odoo.com/runbot/build/19921663

**Comment by Feyensv** [comment]
@robodoo r+

(enterprise branch + PR to fix the warnings have been pushed)

**Pull request closed without merging**
