### PR TITLE
[FIX] product: await the catalog update before reloading records

### PR DESCRIPTION
**Pull request by lase-odoo**
### Issue:

Since 18.0, the catalog is used in certain actions of the shopfloor However, if you leave the catalog fast enough after your last change (something of the order of ~0.5 sec in localhost), you can trigger a reload of the shopfloor records and call a `web_read` prior to the update of these records.

### Note:

This is easily reproducible by hand in localhost and should worsen if you have server delay.In addition, Also, it makes it impossible to write a proper tour involving the catalog in the shopfloor.

### Steps to reproduce:

- Create a product with a bom and an operation op1
- Create and confirm an MO for 1 unit of that product
- Go to the shopfloor > on the operation > wheel > Add component
- Add a component to be consumed in that operation
- Close the catalog fast (using ESC for instance)

### Cause of the issue:

When a product is added from the catalog it triggers an rpc call to update the data's of the MO (notably creating a new raw move): https://github.com/odoo/odoo/blob/193c9a49dfc039ee93fbc8e171819236697b5c50/addons/product/static/src/product_catalog/kanban_record.js#L62-L69 https://github.com/odoo/odoo/blob/193c9a49dfc039ee93fbc8e171819236697b5c50/addons/mrp/models/mrp_production.py#L2898-L2901 On the other hand, closing the product catalog will reload the mrp record that started the action that opened the catalog: https://github.com/odoo/enterprise/blob/c1346dd2279bf3882b47b260b8d03ef9651ffaf1/mrp_workorder/static/src/mrp_display/dialog/mrp_menu_dialog.js#L41-L45 Since this reload is currently not waiting for the update of the record the associated `web_read` might be called prior to the last update of the record and the newly created raw moves might not be displayed.

### Fix:

We use the props option of the action opening the catalog to transfer a callback to reload the records when all the record update promisses are resolved.

Enterprise: https://github.com/odoo/enterprise/pull/72942

opw-4199156
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by lvsz — COMMENTED** [review]
Can you add a link to the enterprise PR in the PR message?

Also, is there a reason why this has to be added in community, and can't be added via inheritance in https://github.com/odoo/enterprise/tree/18.0/mrp_workorder/static/src/components/product_catalog/ ?

**Comment by lase-odoo** [comment]
Hello @lvsz and thanks for your pre-review ! I have added a link to the enterprise PR on the community PR.

The design of the fix is the following:

The catalog needs to be able to send the info that he has finished to update record values. That way, any module using the catalog in their js customization can rely on this info in order to know when to reload the updated records (perform the webread after the records have been updated in DB rather than performing it before the updates get taken into account). Since `mrp_workorder` is not the only module using the kanban catalog records to update unrelated records (for instance in the `sales` app in the sale order form view you can use the catalog to create a sale_order_lines and if you leave the catalog fast enough the newly created sol will not be present in the form view of the sale order) I think that it makes more sense for the catalog it self to contain the info that the records were updated that re-implementing this info transmitter in inheritance of the catalog in each module that uses the catalog to create records.

The purpose of the community PR is to create this info transmitter in the catalog as follows:
The `ProductCatalogKanbanController` component contains a list of promises (initially empty): `catalogKanbanUpdates` aswell as an optional callback props `onCatalogUpdated`. This list is going to be populated each time that a `ProductCatalogKanbanRecord` make a quantity update (used in sales and mrp to create sol and stock moves, respectively). To populate this array of promises a method is defined in the controller: `pushCatalogKanbanUpdate`. This method needs to be called by the `KanbanRecords` an hence is transported using xpath from the `ProductCatalogKanbanController` to the `ProductCatalogKanbanRecord` via the `ProductCatalogKanbanRenderer` .
Once the controller is unmounted (and hence each kanban record made all the update quantity calls) if there a callback was given to the props of the catalog we wait for all the update promises to be resolved and we call the call back.

In the case of `mrp_workorder`, this is used to reload the records of the shopfloor once the records (mrp.productions) have populated by the new moves created via the catalog on quantity updates.

**Comment by chevalierv** [comment]
Hello @lase-odoo 

I've just checked the issue and I'm not convinced by this fix. 

I've tried on runbot using the steps you provided and was able to reproduce the issue but I think it's overkill to implement a job queue for that. It's the only place I know where the catalogue is opened in a modal, this will not solve anything for Sales bc the catalogue is open full screen. 

What's bothers me most is the fact that we have to override the renderer and the record to give the props that communicate with the controller. I'm willing to use a store if other cases would be fixed, otherwise this should be a customization of MRP. Maybe we could use this instead of a debounced button so the back to quotation would wait for the last update before redirecting?
```javascript
function useStore() {
    const env = useEnv();
    return useState(env.store);
}
```

**Comment by lase-odoo** [comment]
Hello @chevalierv, thanks a lot for your review ! 

If you don't think that other modules might benefit from this change then I should definitely move this into a customization of MPR :) In any case if it happens in the future that other modules would like/need to apply such a change we might reconsider the situation then. In the meantime it is definitely cleaner to make the change in MRP and I will do that :)

Concerning the fix, there was indeed a small problem: it did not work if you clicked fast enough (worked in the test but not by hand) because I called the callback during the "onWillUnmount" of the controller rather than during the "onWillDestroy", I did not notice that it failed with the test but if you clicked even faster you were still able to reproduce the issue because you can unmount the controller before the last kanban record has even started the last update. However, it can not happen before the controller is destroyed because the component are destroyed backwards (from children to parents).

Thanks again for your time and review !

**Comment by lase-odoo** [comment]
Done in a custo of "mrp_workorder".

**Pull request closed without merging**
