### PR TITLE
[FIX] point_of_sale: return ProductInfoPopup for extensibility

### PR DESCRIPTION
**Pull request by jrmy17**
[FIX] point_of_sale: ProductInfoPopup.js - Missing return

### CODE REVIEW

**Review by caburj — CHANGES_REQUESTED** [review]
Kindly change the commit title to:

```
[FIX] point_of_sale: return ProductInfoPopup for extensibility
```

**Comment by caburj** [comment]
@jrmy17 The `PR title` won't be used because the merge will be rebase. I'm asking to update the `commit title`.

**Review by caburj — APPROVED** [review]
We can approve this as is. Thank you @jrmy17 for this first contribution.

robodoo rebase-ff r+

**Comment by caburj** [comment]
Hi @jrmy17. I'd like to ask you to create a CLA pull request for saas-16.1, which we will forward port to master. I'm having problem forward-porting this PR because of the CLA. It will become easier if we can separate the merging of your CLA up to master.

**Comment by caburj** [comment]
@jrmy17 Can you link me the PR of your CLA to saas-16.1?

**Comment by jrmy17** [comment]
@caburj #129372

**Pull request closed without merging**
