### PR TITLE
[REM] account: remove "Journal Audits" report from community

### PR DESCRIPTION
**Pull request by smetl**
This report is now dynamic, located in the "account_reports" module in enterprise.

task: https://www.odoo.com/web#id=36590&view_type=form&model=project.task&menu_id=

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rdeodoo** [comment]
@smetl the task was cancelled, not sure if this is still needed?

**Comment by qdp-odoo** [comment]
@rdeodoo me neither. :scream:

**Comment by rdeodoo** [comment]
@qdp-odoo It's okay, I forgive you, there is not a lot of forgotten accounting PRs anyway (dozens of cancelled task by Alain 4 months ago which all have their PR still open tho)

**Comment by rdeodoo** [comment]
Since task cancelled, an no one knows, I think this one can be closed :)

**Pull request closed without merging**
