### PR TITLE
[FIX] stock: unlinking must also change the state of the related move

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
- Go to runbot
- Go for a delivery order and use show detailed operations mode
- Have something reserved on a picking
- Manually delete the ```stock.move.line```
- The move state is not adapted to the new state of the picking / stock move lines

**Current behavior before PR:**
- State is wrong, so you would need to press the button unreserve and check availability then

**Desired behavior after PR is merged:**
- Even if you delete manually ```stock.move.line``` you will have the correct state on the ```stock.move```

@amoyaux @jco-odoo @sle-odoo @pimodoo @nim-odoo 
May I ask one of you to review and merge this? Should be straight forward and obvious I guess.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
OPW-787404

**Comment by wtaferner** [comment]
Wow, the second one even destroyed more tests even though I think the fix should be correct as it is doing exactly the same + watching untracked behavior of the unlink method in ```stock.move.line```.
This behavior feels very inconsistent but I hope the explanation is trivial and maybe the tests need to be fixed.

@Yenthe666 
May I ask you to give some tags?

**Comment by Yenthe666** [comment]
@wtaferner ofcourse you can, as always, you can ask me about anything. 😉 
Thanks for the PR already!

**Comment by amoyaux** [comment]
@wtaferner What do you think of this instead? https://github.com/odoo/odoo/pull/21568

**Comment by mreficent** [comment]
this should be closed...

**Pull request closed without merging**
