### PR TITLE
Session rotation

### PR DESCRIPTION
**Pull request by colinnewell**
Changes made based on feedback on Pull request #6759

### CODE REVIEW

**Comment by odony** [comment]
@colinnewell Thanks for the updated PR and the CLA! Works just fine, clean and simple :+1:

PS: to avoid PR proliferation, it is best to update existing PRs in place by pushing again into the PR branch, rather than making new PRs. It works even if you need to modify the commits with `rebase` + `push -f`, and will keep all related comments in the same place :-)

**Comment by wtaferner** [comment]
@odony 
Can you explain how this is supposed to work/help?
Since this revision I regularly get kicked out and have to login in again. I think this fix does not fulfill all aspects of Odoo sessions even you said it is just fine, clean and simple.

**Comment by colinnewell** [comment]
@wtaferner can you provide more information about your circumstances please?  Are you using the API or is this just from a web browser?  What client are you using?

The intention of the patch is simply to change the session cookie when you login/out.

**Comment by wtaferner** [comment]
@colinnewell 
Ja, sorry, it is the normal usage of Odoo website +  backend.

I am using the latest chrome and I could not backtrace the exact trigger by now...but it seems that some JSON Requests in the backend get back a session expired answer...sometimes it does not harm the overall session and sometimes it forces me to relogin (=session lost)

**Comment by colinnewell** [comment]
@wtaferner 
That does sound strange, the cookies are normally very long lasting (and the underlying session is normally set to a weeks life).  If you could reproduce the issue with the network tab active in the developer tools in Chrome then some of the requests around the logout exported in HAR format (that's a right click option) might allow us to figure out what's going on.  Make sure you check them for anything confidential, but HAR is json so that should be easy enough.

I'm going to try hammer the server to see if it's some sort of timing issue.  The one thing I can think of is that the rotate flag isn't protected by the `inited` flag.

**Comment by colinnewell** [comment]
@wtaferner 
I've been hammering the server with ab and I haven't managed to reproduce the error yet.

My best theory is the rotate flag, so here's a commit you can try, but as I say, at the moment this is just a guess as I can not reproduce the issue.

https://github.com/OpusVL/odoo/commit/92f6d6dee6b1b2ec79417e68c4d6fabf282c86b1

**Comment by wtaferner** [comment]
Thank you for taking a look...I am not yet into the request/session management of Odoo...I pasted a HAR formatted network stream to http://pastebin.com/RvAUBnSV

**Comment by colinnewell** [comment]
@wtaferner excuse me if this seems like a silly question, but in that trace you posted did you experience the problem?

If the patch works then that's cool.  It's the only thing I can think of that could really fail, the patch is so simple it *should* just work.  The fact that there is that protection however does suggest that there may be some sort of timing issue that can be triggered.

If you can confirm that that is still working for you tomorrow I'll send make a pull request to the official repo.

**Comment by wtaferner** [comment]
Jep, I experienced the issue with the trace posted...not a complete session lost scenario but incomplete requests which told me that my session expired...but I guess it is hardly to find/proof on client side as far as I can follow your fix...

I am pretty sure that your patch does solve the issue...so go for it...and if it does not harm something else it is a quick win anyway ;-)

**Comment by odony** [comment]
@wtaferner What do you mean "I am pretty sure that your patch does solve the issue"? You think it does based on the diff, or you confirm that you tested it and the problem has completely disappeared after applying the patch? I'm asking because the link between the patch and your problem is not clear at all ;-)

**Comment by wtaferner** [comment]
@odony Well, I applied the patch locally and saw immediately that my issue was gone ;-) so I was not able to reproduce again...which means for me "pretty sure" as I do not know what my real issue was ;-)

**Pull request closed without merging**
