### PR TITLE
Fix handling of incomming forwarded mails

### PR DESCRIPTION
**Pull request by christophlsa**
## Problem

If you have two mail groups (also called as mailing lists) and want to forward one mail of one group to another group in the same odoo then the mail will be attached to the existing thread in the first group and the second group doesn't get the forwarded mail.
## Steps to reproduce
- Go to Messaging -> My Groups - Join a group
- Click on "Create" and create Group 1 and Group 2 with different email addresses
- setup incomming and outgoing mail servers if not already done
- Let at least two users join both groups (two because you don't get your own mails sent back)
- Write a mail to "Group 1" (to the email address of the group)
- Forward this mail to "Group 2" (to the email address of the group)
## Current behavior

The forwarded email is linked to the first mail in Group 1 (under Messaging -> My Groups -> Group 1).
## Expected behavior (behavior of this pull request)

The forwarded email is shown in Group 2 (under Messaging -> My Groups -> Group 2).
## Limitations

With this pull request we only check the subject of the mail. If you change the title the email is handled normally. Maybe we can add a check for the aliases but then I have to move more code up.

### CODE REVIEW

**Comment by jholze** [comment]
:+1:

**Comment by agb80** [comment]
:+1:

**Comment by jholze** [comment]
@odony maybe someone can have a look here.

**Comment by jbq** [comment]
FYI French Outlook for example does not use `Fwd: ` but `TR: ` in the subject line.  In fact each mail client in every country may use a different prefix, which makes it pretty difficult to have a clean implementation.  Also the problem is not specific to mailing-lists, I noticed it with notifications sent from any model.  The root problem is that Odoo does not consider the message's recipient at all, but only the message id, which embeds the model and object id.  IMO the real solution would be to include the recipient `To:` in the `mail.message` model.  WDYT?

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
