### PR TITLE
[FIX] survey: Fix appraisal feedback deadline

### PR DESCRIPTION
**Pull request by abla001**
in appraisal, the method `_check_validity` is overriden to make different checks in case of `answer_wrong_user`, to make sure that all the checks are OK before handling `answer_wrong_user` case the deadline check should be done before the user check.

opw-4128638

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by abla001** [comment]
ent PR : https://github.com/odoo/enterprise/pull/69502

**Comment by abla001** [comment]
Hello @tde-banana-odoo , can you take a look at this small change please ? :pray:

**Review by tde-banana-odoo — APPROVED** [review]
Seems to be just reodering conditions so lgtm

**Comment by kitan191** [comment]
@robodoo delegate+

**Comment by abla001** [comment]
@robodoo r+

**Pull request closed without merging**
