### PR TITLE
[FIX] website: add correct ID on demo pages container

### PR DESCRIPTION
**Pull request by qsm-odoo**

### CODE REVIEW

**Comment by JKE-be** [comment]
robodoo r+

**Comment by qsm-odoo** [comment]
What are you waiting for @robodoo ? :sob:

**Comment by qsm-odoo** [comment]
@JKE-be rebased, could you re-approve? Thanks.

**Comment by JKE-be** [comment]
robodoo retry 

Please, so many time lost for this small commit ...

**Pull request closed without merging**
