### PR TITLE
[FIX] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by LucasLefevre**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/b62675cea [REL] 17.1.1
https://github.com/odoo/o-spreadsheet/commit/f3fdabed9 [FIX] range: Support ranges with no `Rangeparts` Task: 3608941
https://github.com/odoo/o-spreadsheet/commit/c96d924fa [IMP] evaluation: functions can handle errors Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/55fb8ee37 [IMP] test: fail if console.error Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/a24d294d5 [REF] evaluation: change error objects to string errors Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/4d3821bd0 [REF] formulas: remove computeValueAndFormat and computeFormat Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/c967a6bc2 [REF] formulas: modify typing name Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/0aa596f7e [IMP] functions: accept/throw errors on specific function Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/a056dc099 [REF] evaluation: remove lazy args in formulas Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/78e377f4d [IMP] evaluation: allow formulas to handle error Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/c4953a5fa [REF] cell evaluation: some cleaning Task: 2969401
https://github.com/odoo/o-spreadsheet/commit/87253c7e6 [REL] 17.1.0
https://github.com/odoo/o-spreadsheet/commit/02d578cc9 [FIX] Datavalidation: fix checkbox style Task: 3650740
https://github.com/odoo/o-spreadsheet/commit/93fdaae4e [REF] commands: change evaluation invalidation management Task: 3607272
https://github.com/odoo/o-spreadsheet/commit/ab7f509a2 [FIX] Cell: Fix detection of markdown links Task: 3628780

### CODE REVIEW

**Comment by LucasLefevre** [comment]
fw-bot ignore

**Comment by rrahir** [comment]
@robodoo r+

**Comment by LucasLefevre** [comment]
robodoo rebase-merge

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
@robodoo retry

**Pull request closed without merging**
