### PR TITLE
[FIX]l10n_es: change account types 4009 and 438

### PR DESCRIPTION
**Pull request by manuelregidor**
Description of the issue/feature this PR addresses: wrong account type for accounts 4009 and 438

Current behavior before PR: account type receivable and payable cannot be selected in invoice lines 

Desired behavior after PR is merged: accounts 4009 and 438 can be selected in invoice lines

More info: https://github.com/odoo/odoo/issues/84039

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rafaelbn** [comment]
👍 

https://www.mjusticia.gob.es/es/Ciudadano/Registros/Documents/Normal%20Castellano%20Editable%202020.PDF

imagen

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
Dear @jco-odoo , who is the responsible in Odoo for Spanish localization? Thanks!

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
We have to discuss this in the spanish oca days before merging

**Comment by jco-odoo** [comment]
@rafaelbn This one seems more or less straightforward as it is different from the default payable/receivable account.  @oco-odoo  Maybe @tsb-odoo can check accounting technically as well.

**Comment by HaraldPanten** [comment]
@pedrobaeza We can talk about that whenever you want/you are available.

Having accounts 4009 and 438 as Receivable/payable is not correct. Not only if you want to use the "Down Payment" in Odoo (for 438) but conceptually as well. You can check this information in the official documentation of "Registro Mercantil".

Thanks.

**Comment by HaraldPanten** [comment]
> It is an usual change in database when our customer wants to create pre-payment invoices. LGTM

Thanks Omar. Yes, we've been doing the same as well.

**Comment by rafaelbn** [comment]
Dear @oco-odoo  @tsb-odoo  @jco-odoo  ,

OPW-2861747

This issue was submitted 4 months ago: https://github.com/odoo/odoo/issues/84039

This should be forward-ported to all the versions

**Comment by HaraldPanten** [comment]
@pedrobaeza Could you unblock this?

THX

**Comment by rafaelbn** [comment]
Dear @oco-odoo @tsb-odoo @jco-odoo @acysos 

Como podéis comprobar en la legislación española (LEY):

https://www.boe.es/buscar/act.php?id=BOE-A-2007-19884

Las cuentas 438 y 4009 son "Pasivo Correinte" (Current liability).

Adjunto imagen.

**Comment by jco-odoo** [comment]
@rafaelbn At least in the specific Balance Sheet it is done correctly through the account codes.  And the receivable/payable are also reported there, so I do not see your point.  

But the reasons in https://github.com/odoo/odoo/issues/84039 seem more valid.  I suppose we leave the reconciliable as well to be able to match afterwards?  @HaraldPanten

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by pedrobaeza** [comment]
Well, I haven't been able to analyze this in depth, but the initial problem was that the amounts are not considered in open items reports, that are based on AR/AP. With this change, this amount is not going to be accounted in any place.

**Pull request closed without merging**
