### PR TITLE
[FIX] Website CSS grid bug affecting responsiveness 

### PR DESCRIPTION
**Pull request by jamesbcn**
Website CSS grid bug fix affecting responsiveness to smaller screen resolutions.

**Description of the issue/feature this PR addresses:**
Having `grid-auto-rows` fixed at 50px stops the grid cells from growing in a responsive manner.

**Current behavior before PR:**
Grid cells don't respond to changes in screen resolution or changes caused by the content being translated to a different language.

**Desired behavior after PR is merged:**
Using the `minmax()` CSS function allows the grid cells to expand vertically to accommodate content that exceeds the minimum height of 50px, improving responsiveness on smaller screens.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
To avoid style error, first commit should be `[FIX] web_editor: website CSS grid bug affecting responsiveness`

**Comment by jamesbcn** [comment]
Okay, thanks for letting me know. You're not saying I have to do it all again, are you?

**Comment by MiquelRForgeFlow** [comment]
> Okay, thanks for letting me know. You're not saying I have to do it all again, are you? It looks like it's going to be reviewed regardless...

Sure, they will review it. But in order to get this merged, the CI has to be green. That's their [guidelines](https://www.odoo.com/documentation/18.0/contributing/development/git_guidelines.html#tag-and-module-name).

**Comment by jamesbcn** [comment]
Okay. I've updated the name of the first commit...

**Comment by qsm-odoo** [comment]
Hello :wave: Thank you for your interest. 

Unfortunately, that kind of change is not something to be done in a stable version as 18.0 is, as it would impact every existing website.

This suggestion is also actually something we are working on for the next version of Odoo. But it will be about more than just using the `auto` keyword. We have to consider many other things especially related to edit mode: the way the grid is displayed, impact on images and videos, etc etc. This should be ready for Odoo 19.0, probably sooner in between when using Odoo online :crossed_fingers:

**Comment by jamesbcn** [comment]
Hello! 

Question: `auto` is the default setting which is being overridden by the class fixing the cell height to 50px, right? This is the cause of the issue. Rigidity has been introduced. I don't believe I'm introducing `auto`; I'm just changing the cell height to 50px minimum.

By using `minmax(50px, auto)`, we're striking a balance between ensuring a minimum height and allowing the grid to adapt to different content sizes.

**Comment by jamesbcn** [comment]
Ignored. Very nice. 

And I don't know why you say "Thank you for your interest." What am I interested in? 

I lost time fixing your error and I posted in order to stop others experiencing the same.

**Comment by qsm-odoo** [comment]
I did not ignore you, I am just seeing your message now :shrug: But same answer: what you are considering a bug would change the behavior of the grid mode in existing websites if fixed. To illustrate, here is a website page I made using grid mode as a user: I added an image and copy pasted text:
image

I then enable your fix, the website of that user would suddenly change to:
image

Sure, the user could restore it by properly resizing the text element... but meanwhile his website would be impacted.

And as I said, we also have to consider a few things that would be to be adapted in edit mode. All in all, this is a change we have to in master and we will. Meanwhile, if you want to use that rule as it is on your side, you of course can, for example by using the CSS editor.

**Comment by jamesbcn** [comment]
I understand that you cannot introduce it immediately. My question was regarding your response to using `auto` as a solution. 

You said the eventual solution will require "more than just using the `auto` keyword." I was just curious to know whether you meant: 1) you'll be avoiding the keyword (and, if so, why); or 2) you'll introducing the solution but also having to go further.

**Comment by qsm-odoo** [comment]
I can't know for sure what the final result will be, as the development of that feature is paused while we refactor the editor to use OWL. But the current idea was indeed to use the `auto` keyword, with more to handle it properly especially in edit mode.

**Pull request closed without merging**
