### PR TITLE
[I18N] Add Germany country states

### PR DESCRIPTION
**Pull request by wangyh-c**
Before this commit, the Germany country state is missing in file `addons/base/data/res.country.state.csv`.

Related issue: #66121
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by WongX999** [comment]
@rb3606 report this issue about Germany country state, but no one make PR.
Thus I made it and I get the Germany country state data form Odoo12.

**Comment by WongX999** [comment]
@robodoo @C3POdoo @mart-e 
CI failed in "tempalte" stage.
I'm not clear about contact which person to get any help, how to contact runbot team?

**Comment by mart-e** [comment]
@WongX999 please move them into `l10n_de` instead of `base` (and the ci/template should pass with this)

**Comment by mart-e** [comment]
>  I'm not clear about contact which person to get any help, how to contact runbot team?

For this kind of issues, you can ping the team `@odoo/rd-runbot`

**Comment by william-andre** [comment]
> @WongX999 please move them into `l10n_de` instead of `base` (and the ci/template should pass with this)

It should be done in master instead. Those records belong in `base`.

**Comment by WongX999** [comment]
@mart-e @william-andre 
So where should this part of code belongs to ? `base` or `l10n_de`.

I perfer `base`, but for current commit, I move it into `l10n_de/data/res.country.state.csv`.

If it should change to `base` module in `master` branch, please let me know, I'll make the change.

Appreciate

**Comment by mart-e** [comment]
If the country requires the state in the address (e.g. USA), it's a good place to add it in `base`. In the case of Germany, [it doesn't seem to be the case](http://bitboost.com/ref/international-address-formats/germany/). To avoid bloating the state fields with every state of every country, it's good to add them only in the localisation module.

Now, as it is an improvement and not fixing a bug, master is indeed a better target branch.

Regarding your CLA file, could you keep it lowercase? Thanks

**Comment by WongX999** [comment]
> Regarding your CLA file, could you keep it lowercase? Thanks
You mean change my CLA file name to lowercase ? `WongX999.md` to `wongx999.md`?

> It's good to add them only in the localisation module.
So keep code in `l10n_de` is fine, right?

**Comment by william-andre** [comment]
> If the country requires the state in the address (e.g. USA), it's a good place to add it in `base`. In the case of Germany, [it doesn't seem to be the case](http://bitboost.com/ref/international-address-formats/germany/). To avoid bloating the state fields with every state of every country, it's good to add them only in the localisation module.

You don't want to have to install `l10n_de` when you are not German yourself but have German clients. There is not one single declaration of states in localization specific modules for that reason.
It is something that has been thought and decided, don't try to change it here.

It must be in `base`, in `master`.

**Comment by jco-odoo** [comment]
@william-andre We could have a case where you don't have it in the address but for other purposes, but even then, I am a bit sceptical about the other purposes.  We can think about this one calmly. @mart-e

**Comment by WongX999** [comment]
My NL friends told me, even they have a state/province in Netherlands, but they donot use it, same to Germany, France etc.

Maybe mart-e means the this.

**Comment by jco-odoo** [comment]
But then it might be better not to add it.  Same case in Belgium and we did not add it.

**Comment by wtaferner** [comment]
> @william-andre We could have a case where you don't have it in the address but for other purposes, but even then, I am a bit sceptical about the other purposes. We can think about this one calmly. @mart-e

I think the main reason to add it in base would be to be able to anaylze sales or other stuff based on regions. No idea why normed data like regions should not be inside Odoo Base, but for sure maintaining the data in case of changes (which should be not soo often I guess) is the burden. My humble opinion on this...

**Comment by WongX999** [comment]
I just wanna make those states can work with `base_address_city` module.
Then when I fill the city, Odoo will bring out the state and country.
When the state is necessary for other countries, this works pretty convecience right?

**Pull request closed without merging**
