### PR TITLE
[REF] web_editor, website: use editor helper setClass

### PR DESCRIPTION
**Pull request by Zynton**
This helper is the equivalent of jquery's `toggleClass` with a value for
the `force` attribute. I chose to name it `setClass` instead because
with that attribute it's technically not toggling: it's setting.

Related JW PR: https://github.com/odoo-dev/jabberwock/pull/457

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by dmo-odoo** [comment]
@robodoo retry

**Comment by dmo-odoo** [comment]
@robodoo I meant retry as in like "retry the runbot tests" so that I don't have to open a new page to go to the runbot page and manually ask for a rebuild myself. I'll try something else.

**Comment by dmo-odoo** [comment]
@robodoo rebuild

**Comment by dmo-odoo** [comment]
@xmo-odoo I suggest this feature for robodoo: be able to tell him to rerun the tests for ci/runbot (aka runbot rebuild). I came here initially because I had no news from this PR so I thought somehow my r+ didn't work. I discovered that it did in fact work but the branch was red. SInce I don't think the red status of the runbot is linked to this PR I would have liked to ask robodoo to retry the runbot tests.

I already had to come here manually to understand why I had no news from this PR, and even though I came here, I can't trigger a rebuild from here so the process feels somewhat rocky as I have to go to another tool to unlock the situation here... Since the runbot status can block a PR, it seems logical to me that it would be possible to defer runbot actions to robodoo as well.

Nonetheless, I found a rather easy way: click on "Details" on the ci/runbot line, then on the batch link, then on the bundle link, then you finally have the rebuild the button. Still not as great as like @robotoo runbot-retry or whatever but that will do if you don't like my suggestion... ;-) (I would have used @robodoo rebuild but it seems this is already used as an alias for retry.)

Besides, robodoo could have told me something like "I wanted to merge your PR but I can't merge it because the tests are red" rather than having to realize the issue by myself when I figured this PR still wasn't merged, so take that as another suggestion... ;-)

Thank you for reading, even if you decide not to implement these suggestions.

**Comment by d-fence** [comment]
robodoo retry

**Pull request closed without merging**
