### PR TITLE
[FIX] stock: don't assign immediate transfer in comfirm

### PR DESCRIPTION
**Pull request by yhu-odoo**
Missing part of #44947 of task 2160847

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yhu-odoo** [comment]
@sle-odoo

**Comment by sle-odoo** [comment]
@yhu-odoo target to 13.2

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by sle-odoo** [comment]
thanks!

**Pull request closed without merging**
