### PR TITLE
[IMP] point_of_sale: cash change shouldn't create a payment

### PR DESCRIPTION
**Pull request by mgh-odoo**
Task:https://www.odoo.com/web#id=1944130&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720
Pad:https://pad.odoo.com/p/r.8344dcb7e7fc09da5f682d1e55be4162

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by chienandalu** [comment]
I like this, although maybe it should be configurable as some shops may want to have such control of the detail of the cash operations.

**Comment by gustavovalverde** [comment]
@chienandalu right now this payments are shown as provider payments; so if the payment is going to be created this should also be taken into consideration

**Comment by chienandalu** [comment]
Sure, way better like this, anyway :smile:

**Comment by mgh-odoo** [comment]
merged here https://github.com/odoo/odoo/pull/33578

**Pull request closed without merging**
