### PR TITLE
[FIX] mail: fix various web.push issues

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
A lot of keys are missing compared to standard '_notify_get_recipients'. This is done in two methods that are updated to include keys defined in 'MailFollower._get_recipient_data()' that contains the reference structure to return.

Task-3669738

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Ping @seb-odoo

**Comment by seb-odoo** [comment]
No objection from me, I don't really know/use these methods.

The query looks rather simple, I wonder if we couldn't just use ORM to have easier code + cache?

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
