### PR TITLE
Create bizi-software-srl

### PR DESCRIPTION
**Pull request by erik-bzcl**
Corporate signature for Bizi Software SRL

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by mart-e** [comment]
My bad, there is an issue actually

- you are signing _using_ the address `70377380+erik-bzcl@users.noreply.github.com`
- you are signing _for_ the address `e..@bizicloud.ro`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by erik-bzcl** [comment]
Hello,

thanks, I have set my email erik@bizicloud.ro as public so hopefully it's ok now?

**Comment by mart-e** [comment]
No, you have to make a commit with this email. If you are not sure how to modify your commits, the easiest is to remake a new signature with the correct configuration.

**Comment by erik-bzcl** [comment]
Ok, I have created a new PR #64355.

Thanks

**Pull request closed without merging**
