### PR TITLE
[FIX] registry: avoid dropping indexes

### PR DESCRIPTION
**Pull request by yelizariev**
backport of https://github.com/odoo/odoo/pull/66700

### CODE REVIEW

**Comment by yelizariev** [comment]
@fw-bot up to saas-14.1

**Comment by yelizariev** [comment]
opw-2530258

**Comment by yelizariev** [comment]
@fw-bot up to 14.0

**Review by leemannd — APPROVED** [review]

**Comment by leemannd** [comment]
cc @guewen

**Review by rco-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
