### PR TITLE
[FIX] web: export empty relational field in xlsx as empty string

### PR DESCRIPTION
**Pull request by hubvd**
**Steps to follow**

  - Go to the contact app for example
  - Export some records with a relational field in the import-compatible xlsx format
  - Reimport the downloaded file
  - Odoo can't find matching records with a name False

**Cause of the issue**

  xlsxwriter will write a boolean false value for empty relations

**Solution**

  If a field is relational, write an empty string instead

opw-2643705

### CODE REVIEW

**Comment by mart-e** [comment]
That doesn't seem right, we export falsy values as `=FALSE()` which seems right. Instead isn't the issue in the reimport?
Also your patch seems to be at a weird place. You modify the generic `ExportFormat` while your report only talks about xlsx, what about csv ? Why not modify the `_export_rows` or `convert_to_export` ?
Modifying the export definitly needs new tests.

**Comment by xmo-odoo** [comment]
> That doesn't seem right, we export falsy values as `=FALSE()` which seems semantically right.

Do we? Also I'd agree it's weird in terms of UI, an unset field matches an empty cell better. And that also makes more sense in terms of CSV where `=FALSE()` makes absolutely no sense except in Excel's nonsense.

**Comment by mart-e** [comment]
> And that also makes more sense in terms of CSV where `=FALSE()` makes absolutely no sense except in Excel's nonsense.

I was talking about xlsx export. In CSV, it is exported as `""`. For relation fields, it's true we could leave it empty for both export methods though. Not sure it is a good idea to change it in stable though.

**Comment by hubvd** [comment]
Should I fix the import to allow a False value for relation fields then ?

**Comment by hubvd** [comment]
@mart-e What do you think about the new changes ?

**Comment by mart-e** [comment]
@hubvd much better :+1:

**Comment by rco-odoo** [comment]
@xmo-odoo what do you think?

**Comment by prakashjain** [comment]
Hello all,
The above fix when will update to odoo 14 official github
https://github.com/odoo/odoo/tree/14.0
Export data We are facing same error in odoo 14 official github, please apply the above fix.

**Comment by xmo-odoo** [comment]
Yeah it's probably the change that makes the most sense.

@robodoo r+

**Pull request closed without merging**
