### PR TITLE
[IMP] mail: Allow `_render_lang` to process when it's considered safe

### PR DESCRIPTION
**Pull request by arbaes**
To compute the lang of a template, we call `_render_lang` but it relies on the `_render_template` method.
This means that whenever it's called as is, it will prevent any rendering if the user does not have the group `group_mail_template_editor`, thus making the computation of the lang not possible for the average user using the compose mixin.

To avoid this, the call to `_render_template` will be done as super user if the lang of the current record of the composer mixin  is the same as the one of its template, otherwise the flow is unchanged. This therefore use the template as the source of truth and ensure that we don't evaluate something that shouldn't be evaluated.

### CODE REVIEW

**Comment by reth-odoo** [comment]
Hi there. Not Thibault, but still had a look.

I don't get why the language of the record matching the language of the template matters, feels like maybe it deserves a little more fleshing out in the commit message/docstring

**Comment by arbaes** [comment]
> I don't get why the language of the record matching the language of the template matters.

It's just a precaution, this way we consider the template as the source of truth, and we make sure we don't evaluate something that shouldn't be evaluated.

**Comment by tde-banana-odoo** [comment]
Would say: why 17.2 ?

**Comment by arbaes** [comment]
> Would say: why 17.2 ?

Just the version we had issue with in the first place, I guess I could target 17.0 indeed

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
