### PR TITLE
[REF] various: cleanup alias usage and empty list help overrides

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
PURPOSE

Cleanup alias definitions and usage to have as few invalid or dummy
data as possible. Cleanup empty list helpers override.

SPECIFCIATIONS

hr_expense: cleanup alias management

  * globally avoid crashes if the alias data has been removed;
  * recreate Xml ID record if it has been removed as it is considered as
    being a master data;
  * avoid issues when trying to configure the expense alias in settings if
    alias has been manually removed. Setting a name now creates the alias
    and an XmlID if it has been removed;
  * rename a generic 'use_mail_gateway' field into 'expense_use_mail_gateway'
    in order to avoid conflicts with future changes in generic settings linked
    to email gateway and configuration
  * fix empty list helper: it is now translated and correctly encode parameters
    given to 'mailto';

hr_recruitment, maintenance: remove unused aliases

Those modules hold default aliases to respectively create applicants or
maintenance request. Issue with those generic aliases are

  * they are not bound to any context (container document). For example jobs
    is not linked to any job record. Applicants will not have any job_id set;
  * they are not displayed anywhere. Applicant kanban view displays a helper
    when having no content, with an email address to start populating the
    view. This emails is however based on job in context, aka alias record
    created through the alias mixin on the job.
  * maintenance does not even try to use aliases in any view or code and just
    defines a dummy alias;
  * as default data they can be wrong: taking ``jobs`` and ``helpdesk`` is
    not necessarily a good idea. Indeed it depends on mail server configuration
    (e.g. not always owning all possible emails of a domain when using its own
    address like gmail). This may also conflicts with existing email addresses
    or already-defined aliases without being really configurable;
  * they are not configurable. They are not displayed in any configuration flow
    (setting or container document). Only going into technical menus to find all
    aliases allows to find them;

mail: improve mail alias views to ease usage

mail, various: cleanup empty list help message overrides

Purpose is to cleanup code: stop using help parameter name (use help_message as
help is a keyword), try to call super(), ...

LINKS

Task-2710804 (Mail: Clean MailThread Posting API)
Prepares Task-36879 (Mail: Support MultiCompany Aliases)

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Sub PR of odoo/odoo#99482

**Comment by tde-banana-odoo** [comment]
@robodoo override=ci/security

Reason: usage of Markup where it was not done, when returning html for empty help message. Already checked by @std-odoo on parent PR odoo/odoo#h99482

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Comment by std-odoo** [comment]
@robodoo r- woops sorry

**Comment by tde-banana-odoo** [comment]
@robodoo r+

After check, as it is limited mainly to alias domain to escape, will be done in a future PR to close this small cleaning :) 

Thanks @std-odoo for checking

**Pull request closed without merging**
