### PR TITLE
[15.0] [FIX] mail: respect `mail.activity` ir.rules when reading progress bar

### PR DESCRIPTION
**Pull request by ivantodorovich**
**Description of the issue/feature this PR addresses:**

In order to reproduce this issue, one would need to customize the `ir.rules` of the `mail.activity` model in order to, for example, hide the activities from other users.

In such situation, the `_read_progress_bar` optimization in the mixin was completely ignoring the `ir.rules` of `mail.activity` records.

**Current behavior before PR:**

As the `ir.rules` are ignored, the progress state is inconsistent with what the user sees.

**Desired behavior after PR is merged:**

More often than not, whenever a raw SQL is executed, the `_where_calc` and `_apply_ir_rules` method should be called for all the queries involved.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by reth-odoo — COMMENTED** [review]
Hey, thanks for your submission. Very clean work.

I think it might be worth trying to add a test, it should be possible to some extent and since it's about security to an extent it's probably good to avoid regressions.

Either way, code seems fine to me. It's mostly moving things around in the main query and generating parts of the query with built-in methods so it should be ok.

@tde-banana-odoo missing tests (maybe) aside, I think this is all yours...

**Comment by ivantodorovich** [comment]
Thanks for you review @thiryr !
I've added the unit tests 🙏🏻

**Comment by ivantodorovich** [comment]
Gentle ping @tde-banana-odoo 🙏🏻

**Comment by ivantodorovich** [comment]
Just rebased

**Comment by ivantodorovich** [comment]
Hello @reth-odoo , @tde-banana-odoo 👋🏻 
any chance we can get this merged? 🙏🏻

**Comment by reth-odoo** [comment]
Ouch this is an old one, sorry for leaving you in the dark
tde is the only one who can merge so we'll have to wait for him to get to it

I'll assign this to an internal task so it doesn't get forgotten again. And this way it can be tested functionally, which is a good idea in any case.

**Comment by reth-odoo** [comment]
@ivantodorovich hi, unearthing this old PR to update you

While it seems fine like this, it's the kind of PR we'd want to test extensively on real data to see its effect on performance as activities is famously a very heavy model. So it's difficult to justify merging in stable, even though it's technically better.

In master we now use a regular read_group for this, and override `_read_group_groupby` doing a left-join on the original `_search`, which should already be "safe".

Sorry for the long delay :/
Thanks a lot for the PR anyway

**Pull request closed without merging**
