### PR TITLE
[FIX] website_sale: avoid wrong pricelist on recurring products

### PR DESCRIPTION
**Pull request by yelizariev**
Recurring products may have variants, that have different prices.
On search preview the minimal price is shown.
However, on multi-pricelist setup, the current pricelist was reset to first
pricelist [1].

Fix it by passing pricelist argument to `_get_combination_info`

STEPS

1. Create a subscription product with variants.
2. Create two pricelists ( Time based pricing ) for this product
3. Go to the website > Select one of the pricelist
4. Search product in search bar > You can see price from
another pricelist (if you don't, try another pricelist on the step 3.).

[1]: https://github.com/odoo/enterprise/blob/e9b2ea5c27382f58564f991af501e6a52c6a5193/website_sale_subscription/models/product_template.py#L95-L98

opw-3185013

### CODE REVIEW

**Review by Feyensv — COMMENTED** [review]
AFAIK, the website pricelist is already automatically considered in the override of `_get_combination_info` in `website_sale` :thinking:.
The problem probably lies elsewhere, could you please maybe make a test to cover the problem you're fixing?

**Comment by yelizariev** [comment]
Indeed, `website_sale` sets pricelist

https://github.com/odoo/odoo/blob/cb5382f8fd0bc524c40a08727470b928c3c780ae/addons/website_sale/models/product_template.py#L230-L233

But `pricelist` arg is still empty in `_get_combination_info` extension in  `website_sale_subscription`. That value might be different from current website's pricelist.

https://github.com/odoo/enterprise/blob/e9b2ea5c27382f58564f991af501e6a52c6a5193/website_sale_subscription/models/product_template.py#L95-L98

I'll add the tests soon

**Comment by yelizariev** [comment]
@Feyensv do you know any examples of tests for /autocomplete ?

I'm trying to add a tour, but search preview doesn't show up in the headless browser, even though /autocomplete is successfully processed 

https://github.com/odoo/enterprise/pull/38904

**Comment by Feyensv** [comment]
Never touched autocomplete stuff in the past, so I don't have any in mind :thinking:.

But if needed, another approach would be to fix the `_get_combination_info` override in `website_sale_subscription` to consider the website pricelist (and make a simple python test covering `_get_combination_info´ results, without having to write a tour).  That way, we would be sure that the right pricelist is considered in all the flows related to `_get_combination_info`, not only this one related to `_search_render_results`.

**Pull request closed without merging**
