### PR TITLE
[FIX] l10n_eg_edi_eta: connect ETA server w/openssl 3.0


### PR DESCRIPTION
**Pull request by nle-odoo**
The eta.gov.eg production servers can't be connected using OpenSSL 3.0.

This is happening because of the change in:

https://github.com/openssl/openssl/commit/72d2670bd21becfa6a64bb03fa55ad82d6d0c0f3

that now by default prevent unsafe legacy renegotiation.

To prevent this issue, we add the SSL_OP_LEGACY_SERVER_CONNECT option to
ssl context of queries to the eta.gov.eg servers.

SSL_OP_LEGACY_SERVER_CONNECT is not available before python 3.12, so
the value is hardcoded in Odoo.

opw-3102485

### CODE REVIEW

**Comment by nle-odoo** [comment]
I added the discord discussion on the ticket.

Before the change error was:
```
*** requests.exceptions.SSLError: HTTPSConnectionPool(host='id.eta.gov.eg', port=443):
Max retries exceeded with url: /connect/token (Caused by
SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED]
unsafe legacy renegotiation disabled (_ssl.c:997)')))
```

After the change (on a misconfigured instance):
`<Response [400]> {"error":"invalid_client"}`

**Comment by nle-odoo** [comment]
edit: changing target to 15.0 since it is the l10n_eg_edi_eta was introduced in it (for odoo saas, the issue would only happen from 16.0, but it's possible that customer have the issue for previous versions)

**Comment by nle-odoo** [comment]
@odoo/rd-security this PR should be safe since this is replacing a `requests.request` by a `session.request`. Allowing legacy server connect is necessary to be able to make request to eta.gov.eg server that are necessary for egyption e-invoice.

**Comment by tbe-odoo** [comment]
@robodoo override=ci/security

**Comment by nle-odoo** [comment]
thanks

I tested on older configuration and this seems to work alright too:

os | openssl | urllib3 | requests | result
-|-|-|-|-
ubuntu 14.10 | 1.0.1f | 1.8.3 | 2.3.0 | fix breaks because of method and arguments change (acceptable since expected version for odoo 15.0 is `urllib3==1.26.5` and `requests==2.25.1`)
ubuntu 14.10 + update | 1.0.1f | 1.10 (dec 2014) | 2.12.0 (nov 2016) | work with or without fix
ubuntu 18.10 | 1.1.1 | 1.22 | 2.18.4 | works with or without fix
ubuntu 20.10 | 1.1.1f | 1.25.9 | 2.23.0 | works with or without fix
archlinux | 1.1.1s | 1.24.3 | 2.21.0 | works with or without fix
archlinux | 3.0.7 | 1.26.12 | 2.25.1 | works only with fix

since this is blocking and there is possibly other linked tickets (not sure since linked ticket have screenshots with other errors), I'm merging now so this can be available on next updates.

robodoo r+

**Pull request closed without merging**
