### PR TITLE
[FIX] l10n_cl: update widholding 2nd category tax percentage to -13%

### PR DESCRIPTION
**Pull request by Danisan**
The 2nd category withholding value is in 11.5%, which is the value used in 2020.

There is a gradual table already defined for this tax till the year 2028. In this PR we are updating the value for the master branch, to 13% which is the withholding value for 2023.

### CODE REVIEW

**Comment by fvz-odoo** [comment]
Thanks @Danisan 

Since this is for master we can already merge, as you said clients will not be in v16 until 2023.

Ready for technical review by @jco-odoo 

Cheers!

**Comment by fvz-odoo** [comment]
@Danisan try to add a couple of them as new taxes and you can deprecate the ones not being used anymore.

**Comment by fvz-odoo** [comment]
@Danisan could you please make "inactive" on taxes from previous years and have only for 2020-2024?

**Comment by fvz-odoo** [comment]
Hello @Danisan 

I still see all taxes, could you please make inactive the ones from before and leave the ones until 2026 active, only?

Thanks!

Fernando

@ren-odoo @vbe-odoo @jco-odoo

**Comment by jmo-bmya** [comment]
@fvz-odoo @jco-odoo please check

**Comment by fvz-odoo** [comment]
Hello @jmo-bmya 

Thanks for the changes on this PR, it LGTM. Ready for your technical review @jco-odoo 

Cheers!

Fernando

@Danisan

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
