### PR TITLE
[FIX] point_of_sale: stop creating double picking on pos order refund

### PR DESCRIPTION
**Pull request by robinengels**
Current behavior:
When creating a refund for a PoS order and invoicing the refund two
pickings were created instead of one.

Steps to reproduce:
- Make a PoS order and make the payment
- Go in the PoS orders in the backend
- Return the product
- Make the payment for the return
- Create an invoice for the refund
- There are 2 pickings created when there should only be one

opw-2848356
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by robinengels** [comment]
@trj-odoo could you review this PR ?

**Comment by pimodoo** [comment]
@robinengels it looks good to me, but I don't know if it is needed in 15.0 as the return comes from frontend. Could you confirm? @trj-odoo

**Comment by pimodoo** [comment]
@robinengels Sorry, I re-read the fix, and I think the fix does not really fix the issue, the question is why does a picking already exist if we are in "update_stock_at_closing" ?

**Comment by robinengels** [comment]
> @robinengels Sorry, I re-read the fix, and I think the fix does not really fix the issue, the question is why does a picking already exist if we are in "update_stock_at_closing" ?

We should probably prevent the picking to be created here then https://github.com/odoo/odoo/blob/14.0/addons/point_of_sale/wizard/pos_payment.py#L59 . Adding a condition like `            if not order.session_id.update_stock_at_closing:
                order._create_order_picking()`

**Comment by pimodoo** [comment]
what is weird is that in _create_order_picking, we already have
'if not self.session_id.update_stock_at_closing or (self.company_id.anglo_saxon_accounting and self.to_invoice):' so it should already not be created

**Comment by robinengels** [comment]
@pimodoo @trj-odoo

**Comment by trj-odoo** [comment]
@pimodoo

**Comment by pimodoo** [comment]
@robinengels I finally had time to test it, I found another fix that seems better for me, could you confirm me that it is working as you need and we'll merge it.

**Comment by robinengels** [comment]
@pimodoo I tested it it's working correctly, I also added a test.

**Comment by pimodoo** [comment]
@robinengels thank you very much

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
