### PR TITLE
[FIX] l10n_pe: add district to shown address

### PR DESCRIPTION
**Pull request by agr-odoo**
Have a partner with district filled
Create a Sale Order
Print report

Issue: District is missing

opw-4020494

### CODE REVIEW

**Comment by hupo-odoo** [comment]
It looks good to me, but I have a minor question: when creating a database without the fix, and then adding the fix, I can't see the new field on the invoice despite updating the module. Any idea why ?

**Comment by agr-odoo** [comment]
I would keep it simple and update the country data manually where needed, but to be sure I'll ask the PO =)

**Comment by agr-odoo** [comment]
CHKL approved

**Comment by hupo-odoo** [comment]
@jbw-odoo ready for your review :smiley:

**Review by jbw-odoo — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
