### PR TITLE
[CLA][FIX] prevent to error on editing mass.mailing

### PR DESCRIPTION
**Pull request by grzana12**
Description of the issue/feature this PR addresses:
after made customization where we need in `mailing.contact.subscription` value of `partner_id` Odoo generate internal Server Error.
Please merge it to 13.0 too

Current behavior before PR:
after added field `partner_id` to model `mailing.contact.subscription` which is not storable application generate 500 error

Desired behavior after PR is merged:
`partner_id` is not storable in result first condition is skipped what is fine

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
FYI: https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#tag-and-module-name

**Comment by grzana12** [comment]
Thanks. That's my first PR in Odoo. 
Updated

**Comment by grzana12** [comment]
@MiquelRForgeFlow any progres with accept?

**Comment by MiquelRForgeFlow** [comment]
@grzana12 you updated the title of the PR but I meant that you should update the message of the commits. Also, I am not from odoo, so I am not the person who accepts and merges. The mass_mailing guy is @tde-banana-odoo :)

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for the PR. Looking at the code, I updated the code to check other fields, as this is valid for all fields that we use in the SQL queries, in both mailing and sms marketing apps. I also added a test because always better with tests :) .

**Pull request closed without merging**
