### PR TITLE
[FIX] gamification: fix wrong condition in template

### PR DESCRIPTION
**Pull request by ghost**
How to reproduce
 =================

Give a badge to an employee, when checking the sent mail, The image and
description of the badge is nowhere to be seens.

Those fields don't display because the description contains P html tags.
The presence of the removed `t-if` is the main cause of the issue.
Adding a `not` to the condition solves the issue. This not was lost
during the Jinja -> Qweb translation (#68182ba)

opw-3099419

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
change looks good to me

but isn't the issue that we should check

```py
t-if="not is_html_empty(object.badge_id.description)"
```
the `is_html_empty` method seems a good thing to have (it removes empty tags and check if there is remaining content), but the logic is reversed.

If we wanted to still show the tag, then the current version would look good (but it might be odd to have the empty td and cite tags)

**Comment by joda-odoo** [comment]
It makes more sens to keep it like you say :+1:

**Review by flch-odoo — APPROVED** [review]
Hello @joda-odoo ,
Thanks for the fix. Looks like the not was lost in the jinja=>qweb conversion in 68182baff4bdf4b3bcc1f46b361f5a5b8ac9aa11.
Could you mention this in your message ? And update it's title to reflect you are restoring part of the "badge received" template?
Thanks !

**Review by nle-odoo — COMMENTED** [review]
If we are changing this, we should need we would need to change the POT.

I think usually we try to not do that and only do it in msater (to not break the translation). In this case the record is in `noupdate="1"` so it is a little less severe.

**Comment by tde-banana-odoo** [comment]
"missing field in mail" -> "wrong condition in template" ?

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
