### PR TITLE
9.0 fix blog chm

### PR DESCRIPTION
**Pull request by Gorash**
https://github.com/odoo/odoo/issues/9510

### CODE REVIEW

**Comment by jholze** [comment]
:+1:

**Comment by jholze** [comment]
i am testing on runbot now

**Comment by jholze** [comment]
(/) checked translation to german for existing blog posts - works well
(/) checked on new created blog post, works also as expected 

good job, thanks.

**Comment by jholze** [comment]
@Gorash i'll buy a beer if we would ever meet :) - thanks. This fix will be uses on this project http://supernova-lights.de/

**Comment by Fl0rianFischer** [comment]
@Gorash the blog title and subtitle are not translatable anymore, if you don't have english as the default language.

I tried with your approach, using html_translate, but it renders <p> tags around title and subtitle which are shown in the url as well.

**Comment by Gorash** [comment]
@Fl0rianFischer The language should be removed from the context during editing due to changes in the framework. (There was even a warning from the front when the language was in the context.)
I'm looking for a fix/feature.

**Comment by Gorash** [comment]
@Fl0rianFischer it's the placeholder on the h2 tag who create this error, I'll fix it

**Comment by Fl0rianFischer** [comment]
@Gorash I'm pretty sure I tried without the placeholder as well and it didn't work but could be wrong.
As I noticed the fields don't get the "oe-translation-id-" attribute

I also checked in the eventsmodule with event titles - same behavior

**Comment by Gorash** [comment]
@Fl0rianFischer effectively the placeholder issue is already fixed.
For now, internal directives that are on the website information must be created and edited and translated in en_US. A solution could have been made for publishing in all languages (instead of only in english then translated) but this is unfortunately not the priorities.

**Pull request merged**
