### PR TITLE
[IMP] account, l10n_*: update payment communication

### PR DESCRIPTION
**Pull request by jmak-odoo**
This commit introduces a simple numbers only communication standard, as well the European communication standard was extended to include more useful information.

task-4277844
upgrade PR: odoo/upgrade#6837

### CODE REVIEW

**Review by rugo-odoo — APPROVED** [review]
Nice one !

@robodoo r+

**Comment by rugo-odoo** [comment]
@robodoo r-

**Review by h4818 — COMMENTED** [review]
Thanks @jmak-odoo 
Just some minor nitpicking
checked with @smetl - this shouldn't impact the bank reco matching

**Comment by h4818** [comment]
@robodoo r+

@odoo/upgrade I don't know why matt has a complaint about https://github.com/odoo/upgrade/pull/6905

**Comment by aj-fuentes** [comment]
> @odoo/upgrade I don't know why matt has a complaint about https://github.com/odoo/upgrade/pull/6905

Because this branch needed a rebase after the merge of https://github.com/odoo/odoo/pull/189852

**Comment by h4818** [comment]
> Because this branch needed a rebase after the merge of #189852

ok, thanks
:thinking: I thought this branch was rebased and seems to include that commit :man_shrugging:

**Pull request closed without merging**
