### PR TITLE
[FIX] Add currency rounding in pos.order.line

### PR DESCRIPTION
**Pull request by mncoon**
Add currency rounding in def _amount_line_all to allow rounding in subtotal from pos order line by settings in currency.

### CODE REVIEW

**Comment by jorenvo** [comment]
Interestingly enough, this seems to be the inverse of what happened in 9c30ba7143846b0f9e82140fb33e4ee7dea9435c. @simongoffin, could you tell me what you think of this?

**Comment by copmn** [comment]
@jorenvo thanks for the quick reply. now this issue is getting more clear to me. I was wondering why there is a ```cur_obj``` and a ```cur``` without usage. I am not sure if you asked the right question to @simongoffin. Better is to ask why was this necessary piece removed?

**Comment by simongoffin** [comment]
In fact, this is a fix I did because in 8.0 it was possible to round globally which means that the rounding is made on the sum of each line and not on each line. If we round like you did in your pull request we disabled the global rounding. But it seems that the global rounding disappeared in 9.0
I will asked to @qdp to be sure about that.

**Comment by copmn** [comment]
@simongoffin thank you for your quick answer. As you can see in #9496 without this rounding there is a difference in the rounding between pos-display and the orders in background. 
In most countries over the world there is no impact on this. But in a few (eg. Switzerland) where all amounts were rounded to 0.05, it is a need that the POS works correctly, otherwise some orders don't get paid, even if they are.

In my case I provided a quick fix to the customer. If you think there is no need to fix this for future, we can let it as is, but I do a quick check that it works correctly in V9 with the same settings.

**Comment by Yenthe666** [comment]
Hi @mncoon,

Thank you for your PR.
Odoo 8 is no longer in the officially supported Odoo versions as Odoo only supports up to three versions (9.0, 10.0 and 11.0 at the moment). This means there are no longer PR's merged in for V8. Sorry!

Regards,
Yenthe

**Pull request closed without merging**
