### PR TITLE
[FIX] hw_scale: Adam scale wait time

### PR DESCRIPTION
**Pull request by switch87**
When opening the weight screen in PoS it can take up to 10 seconds
until the weighting starts. This can be resolved by using a
Threading.Event instead to reset the 10 second sleep time.

Using exit_flag.wait(timeout=DELAY) will be more responsive, because
you'll break out of the while loop instantly when exit_flag is set. With
time.sleep(timeout=DELAY), even after the event is set, you're going to wait around in
the time.sleep call until you've slept for DELAY seconds.

as proposed by @odony 
https://github.com/odoo/odoo/pull/27351/files#r271069753

### CODE REVIEW

**Comment by nim-odoo** [comment]
That would be interesting to know why the existing implementation fails, and why the actual works. Usually, when we write a commit message for a fix, we explain:
1. The issue from a functional point of view
2. The technical reason why this happens (optional, might be obvious)
3. How we solve the issue / why it solves the issue (optional, might be obvious)

Your commit message lacks points 2 and 3, and I think the `hw_*` modules are specific enough for some extra comments to be added for future reference.

**Comment by switch87** [comment]
@nim-odoo
This can be resolved by using a
Threading.Event instead to reset the 10 second sleep time.
This is the technical part, no? It is kind of obvious once you know how threading.Event works.

**Comment by nim-odoo** [comment]
Why `sleep` doesn't work?
Why `event.wait` works?

You were obviously not aware at first since you used `sleep`. Now you just say it is obvious, which doesn't explain anything.

**Comment by switch87** [comment]
> You were obviously not aware at first since you used `sleep`. Now you just say it is obvious, which doesn't explain anything.
That is more because my lack of knowledge about threading in Python, but the difference is quite obvious once the functionality was pointed out to me. I will look how to make the commit message better.

**Comment by switch87** [comment]
@nim-odoo I updated the commit message

**Comment by switch87** [comment]
> What were the result of the testing with the Adam scale? Did you notice a faster response time on the POS weighing screen?

It gave immediate measuring results after the change to event in my testing. And as you remarked before it could take some seconds before with the sleep timer.  This is a real improvement! :+1:

**Comment by switch87** [comment]
@nim-odoo can you take another look at this pr?

**Comment by nim-odoo** [comment]
It looks ok, but I don't have enough knowledge to give a clear opinion (and I don't have a way to test it either). If @odony or @qle-odoo is ok, I'm ok with it.

**Comment by odony** [comment]
@robodoo r+

**Pull request closed without merging**
