### PR TITLE
13.0 reconcil jco

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo rebase-ff

**Comment by fclementic2c** [comment]
test ok :)
Great job @jco-odoo

**Comment by jco-odoo** [comment]
@nim-odoo I did a small change for the company_id (supported by oco to better support the yti multi-company) and improved the commit messages.  So, your turn to give the blessing.

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
