### PR TITLE
[FIX][16.0] barcode: In this paragraph, we are trimming the string and then converting it to an int type. But there is no guarantee that value_string can be converted to int

### PR DESCRIPTION
**Pull request by daonamutc1**
In this paragraph, we are trimming the string and then converting it to an int type. But there is no guarantee that value_string can be converted to int

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by daonamutc1** [comment]
@ged-odoo Can you review this PR?

**Comment by Whenrow** [comment]
@daonamutc1 Hello. OK for the fix. You could rewrite your commit to follow the [guidelines](https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#commit-message-structure) ? 
```
[FIX] barcode: short title

description
```
Thank you

**Comment by daonamutc1** [comment]
> @daonamutc1 Hello. OK for the fix. You could rewrite your commit to follow the [guidelines](https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#commit-message-structure) ?
> 
> ```
> [FIX] barcode: short title
> 
> description
> ```
> 
> Thank you

Can you review again? @Whenrow

**Comment by Whenrow** [comment]
@daonamutc1 Thank you
robodoo r+

**Pull request closed without merging**
