### PR TITLE
[FIX] stock: dropshiping delivery slip in client's language

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reprodue:
- Create a dropshipped product
- Sell the product to a client with a different language set
- Print the delivery slip

Bug:
delivery slip is currently being printed in the vendor's language

Fix:
Print the delivery slip in the client language when possible

opw-3193015

### CODE REVIEW

**Review by adwid — COMMENTED** [review]
Thanks to c9b1f1c9329fc9d52b1eebcba07ce3506c82883d we know that the customer is set on the SM
So lgtm, just a little improvement

**Comment by adwid** [comment]
Can you make the method private ? Then I will r+

**Comment by HANNICHE-Walid** [comment]
@adwid done :)

**Comment by ticodoo** [comment]
maybe also fix your commit typo ;)

"dophsiping" hurts my brain

**Comment by adwid** [comment]
robodoo r+

**Pull request closed without merging**
