### PR TITLE
[IMP] pos_online_payment_self_order,pos_self_order: kiosk online payment

### PR DESCRIPTION
**Pull request by davidmonnom**
Online payment method added to kiosk. This works in the same way as in
the mobile SelfOrder, except that the payment page does not open
automatically in the kiosk. A QR code appears and the user is asked to
scan it to make the payment on their phone.

Once the QR code has been scanned, the page on the kiosk updates to show
"payment in progress", and once the payment has been validated, the
validation page appears on the kiosk. These different statuses are sent
via websocket.

### CODE REVIEW

**Comment by davidmonnom** [comment]
@odoo/rd-security Can you add a CI override? I use the websocket with an appropriate access_token from the pos_config to send different statuses on payment to the kiosk :) 

Here is the diff: 
https://github.com/odoo/odoo/pull/138825/files#diff-a843415b00d5a84e604420ec6a19040426294ec9b5deeacf6f12876c12af06ddR29-R33

**Review by xmo-odoo — COMMENTED** [review]
@robodoo override=ci/security

**Review by adgu-odoo — APPROVED** [review]
Good job

**Comment by adgu-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
