### PR TITLE
* update Authorize.net to new gateway URI

### PR DESCRIPTION
**Pull request by lasley**
Authorize.net has updated their payment gateway URI per https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Important-Authorize-Net-Networking-Change/ba-p/51272 

New Gateway is powered by Akamai CDN, thus is more reliable.

### CODE REVIEW

**Comment by lasley** [comment]
Hi Everyone - Just noticed the CLA on this is still failing, but I completed it per the instructions. Is this something that requires manual verification?

**Comment by mart-e** [comment]
Hello,

The CLA is still failing because your made your commits with the `@dlasley.net` email address and signed for the `@laslabs.com` address. I guess you wished to use the second one for the corporate CLA.
You sign for the address of your choice but just make sure to use it when commiting.

I am ok for the change in `payment_authorize`. Actually as it's an update of the official URL, no need to sign the CLA for that but no problem to merge it of course.
I let you amend your commit to either change the author or the CLA before merging

**Comment by lasley** [comment]
Hi @mart-e - Thanks for the breakdown! I squashed my commits under my corporate email, should be good now.

**Comment by mart-e** [comment]
@lasley sorry but still commiting with `@dlasley.net` :) See [Setting your email in Git](https://help.github.com/articles/setting-your-email-in-git/)

**Comment by lasley** [comment]
Hrmmm I did that, but I'm not entirely sure how to remove myself from the history - it's showing my other email as the author still, but my corporate as the committer (rebasing is still pretty voodoo to me). No problem though, I'll just submit for my personal too and call it a day. Thanks for your help @mart-e !

**Comment by mart-e** [comment]
Ok so you signed the corporate CLA with your personal address and the personal CLA with the corporate address :-) So let's say it's globally good, I used the correct email address when merging

3dc5a388 [FIX] payment_authorize: update API URL
16abe18 [CLA] sign corporate CLA for LasLabs
da062e2 [CLA] sign CLA for @lasley

Thanks!

**Pull request closed without merging**
