### PR TITLE
[CLA] manaTec cla

### PR DESCRIPTION
**Pull request by rd-manatec**
* [CLA] added manaTec

* [CLA] Added signature for tobytes

* [CLA] Added signature for TomTietze

* [CLA] Added signature for fploetzlich

* [CLA] Updated manaTec cla

* Update manatec.md

* Create AlexanderHeyber.md

* add  Walter_manaTec.md

* Update manatec.md

Added Contributor

* add Wallter to cal

Co-authored-by: rd-manatec <robert.duckstein@manatec.de>
Co-authored-by: Tom Tietze <tom.tietze@manatec.de>
Co-authored-by: Philipp Köhler <54881845+fploetzlich@users.noreply.github.com>
Co-authored-by: alexander-heyber-manatec <42136930+alexander-heyber-manatec@users.noreply.github.com>
Co-authored-by: ws-manatec <walter.salzmann@manatec.de>

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rd-manatec** [comment]
@mart-e Hello,

thanks for the info and your patience - we removed individual CLAs
cheers,
Robert

**Comment by mart-e** [comment]
Thanks, could you squash your commits into a single one and use a commit message like
```
[CLA] manaTec signs Odoo CCLA
```

**Comment by rd-manatec** [comment]
Hey Chris,

we squashed ;)
cheers
Robert

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
