### PR TITLE
[ADD] spreadsheet_dashboard: introduce spreadsheet based dashboards

### PR DESCRIPTION
**Pull request by LucasLefevre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by sdegueldre — APPROVED** [review]
@robodoo r+

**Comment by sdegueldre** [comment]
@robodoo r- (commit message)

**Comment by LucasLefevre** [comment]
thanks for the review :wink: 
The PR is not ready though (enterprise counter part which is adding all those modules https://github.com/odoo/enterprise/pull/26856)
I meant to create the PR as draft but I missclicked and didn't find how to change its status after it was created

**Comment by sdegueldre** [comment]
It's just under the "reviewers" section (search for "convert to draft" on an existing PR) it's really hidden.

**Comment by pro-odoo** [comment]
@robodoo override=ci/style
Override because the terms which trigger the warnings (custom-select, border-*) are used for custom class names or directly in inlined css.

**Comment by pro-odoo** [comment]
@robodoo override=ci/style
Override because the terms which trigger the warnings (custom-select, border-*) are used for custom class names or directly in inlined css.

**Comment by pro-odoo** [comment]
@robodoo override=ci/style
Override because the terms which trigger the warnings (custom-select, border-*) are used for custom class names or directly in inlined css.

**Review by sdegueldre — APPROVED** [review]
Always nice to see the tooling whitelist growing :+1:

**Comment by rrahir** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
