### PR TITLE
[FIX] *: Don't override HttpCase.base_url() in tests

### PR DESCRIPTION
**Pull request by Julien00859**
Multiple tests were wrongly overriding `base_url` instead of using the
`base_url` method of HttpCase.

### CODE REVIEW

**Review by rdeodoo — COMMENTED** [review]
Cool to use base_url(), and assertEqual for cleaner log on error as you explained :+1:  .

Other than that, it's an `IMP`, not a `FIX`.
It could be useful in the commit message to indicate that `base_url()` was only recently introduced with https://github.com/odoo/odoo/commit/ded278b9c20ddf7b9637d53d9b3f519947fb40ff and that now tour could be **improved** by using it :+1: 

Not a big fan of those f-string diff that are not required, but I am not going to argue again about it ;-)

**Review by rco-odoo — APPROVED** [review]
@robodoo r+

**Comment by Julien00859** [comment]
@robodoo r-

**Comment by Julien00859** [comment]
@robodoo r+

**Pull request closed without merging**
