### PR TITLE
[FIX] website, *: avoid using unescaped query parameters

### PR DESCRIPTION
**Pull request by bso-odoo**
*: google_recaptcha, web_editor, website_blog, website_forum,
   website_sale_comparison, website_slides, website_twitter

This commit fixes improperly escaped query parameters across javascripts of website-related modules.

### CODE REVIEW

**Comment by bso-odoo** [comment]
This PR addresses the following entry in the website-in-backend pad:
> [ODO] https://github.com/odoo/odoo/pull/89223#discussion_r904107340 -> track down URLs created by string concatenation (typically an example exists with access_token (but there are many more)) -> fix in stable and forward-port

Made sure that all such parameters are escaped as URI parameters - for the modules that are related to `website` - did not address similar problems in other modules.
Upon every forward-port, the inventory must be done again to catch new occurrences.
Inventory is obtained through the following command (the second grep gets rid of the minimized js):
```sh
grep -inr --include \*.js "[?&]\S*[a-zA-Z0-9_\-]\+\=[\%\$\"\'\`]" | grep -Ev ".{1000,}"
```
In stable, to minimize impact, `encodeURIComponent()` is used.
In master, string concatenations can be replaced by `URISearchParams` and friends.

**Comment by bso-odoo** [comment]
@qsm-odoo Rebased on https://github.com/odoo/odoo/commit/a5282701fdd650f75b2def44948e2a7071810ea4.

**Comment by qsm-odoo** [comment]
@robodoo delegate=sobo-odoo

**Review by sobo-odoo — COMMENTED** [review]
It looks alright for me :slightly_smiling_face: 
I tested the cases where I had doubts and nothing seems broken. I am not sure if we should escape the things that are surely numbers (like the IDs) but I agree it is better to be more safe (at worst numbers will stay numbers) :wink: 

I just have a comment about an unrelated issue I found when testing :slightly_smiling_face:

**Review by sobo-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
