### PR TITLE
[IMP] website_sale: allow hide attributes in website filter

### PR DESCRIPTION
**Pull request by JKE-be**
task-2466988

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rdeodoo — APPROVED** [review]

**Comment by JKE-be** [comment]
@robodoo r+

thank you @tdecaluwe for this ...

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo retry

**Pull request closed without merging**
