### PR TITLE
[FIX] externalize the compilation of the regexpr

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
Do not compile the regexpr each time that the method is called

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
OPW 666790

**Comment by beledouxdenis** [comment]
Even if I believe this isn't incorrect, I would like to know the reasons that made you did this ?

Is this significantly improving the performances ? Do you have numbers ?

**Comment by JonathanNEMRY** [comment]
Hi @beledouxdenis 
* Effectively compiling a constant regular expression anytime it's needed is certainly improvable, but above all
* The implementation I propose allows monkey patch.
Typically we need it to bypass the "stringnification" of the ```tag when coming from some mail clients like thunderbird and containing an embedded picture (i.e. part of a multipart message of `content-type image/xyz`).

see also: https://github.com/odoo/odoo/issues/10452

**Comment by beledouxdenis** [comment]
So, you are telling me that you would like to use this regex to another purpose than what it's designed for, through a monkey patch, above all ?

This doesn't look like a stable patch to me.
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

In addition, indeed, you reason that the regex is re-compiled doesn't stand: Indeed, this will require more resource in the place where it's compiled at the moment, but not by much, not something that would resolve a blocking issue.

Can't you just override `html_sanitize`, call the super, and then perform what you would like ?

**Comment by JonathanNEMRY** [comment]
@beledouxdenis  I understand your stable policy but here it is a small touch that does not involve risk or something else (small value/**no** risk). Into the mailing processe and as I explained it into #10452 incoming mail are not well read: Embedded picture does not work. Moreover, style and other basic mail feature from mail client does not work too (a too large restriction into sanitize).
Here it is a small improvement into the Odoo code that can help us to make it work for our customers. If you reject this PR, what do you propose to fix #10452 ?
The solution to override `html_sanitize` is not an acceptable solution (too many parse and additional treatment...)

**Comment by beledouxdenis** [comment]
I am sorry but I cannot accept this proposal if the goal is to give the possibility to monkey patch the regex. We cannot consider this as a stable patch, neither as a clean patch.

**Comment by tivisse** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards

**Pull request closed without merging**
