### PR TITLE
[IMP] im_livechat, *: Refactor JS Public Livechat (step 13)

### PR DESCRIPTION
**Pull request by alexkuhn**
*: website_livechat

This commit is a step towards refactoring the JS of public livechat,
so that it reuses the same architecture as the code of Discuss.
This implies code that uses JS models and OWL components.

Task-2943607

### CODE REVIEW

**Comment by alexkuhn** [comment]
@seb-odoo regarding ci/security:
1.
- `this.$header.html(qweb.render('im_livechat.legacy.PublicLivechatWindow.HeaderContent', { widget: this }));`
- From: https://github.com/odoo/odoo/pull/96908/files#diff-c3af45e304f136ff54c356023946900630290dc47f8f0afdae13bd147630c7a6R115
- It's the same `.html()` but with less data provided to template. Actually fully relies on `widget: this`

2.
- `message.body = Markup(message.body);`
- From: https://github.com/odoo/odoo/pull/97082/files#diff-30f566977467c1c9971b17eef52b39acf2e5ba49a7424a5a993a656775c920e1R545
- Exact same usage of `Markup`, just overall method that is being moved to another place in the code (from widgets to models)

3.
- `body: Markup('<p>' + message.content + '</p>'),`
- From: https://github.com/odoo/odoo/pull/97233/files#diff-3f069628ee3a51f9d67cd86c41bff4e1713f1c5d594cdd408fd06a0b773253d6R42
- Exact same `Markup` usage, just overall method that is being moved to another place in the code (from widgets to models)

**Comment by alexkuhn** [comment]
👆squashed

**Comment by seb-odoo** [comment]
@robodoo override=ci/security

See https://github.com/odoo/odoo/pull/97403#issuecomment-1203989488

All code move.

First occurrence is injecting the result of a template which is safe.

Second is unsafe usage of Markup but content is coming from sanitized body in python.

Third is in test file so irrelevant for security purposes anyway.

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
