### PR TITLE
[IMP] lunch: refine user experience

### PR DESCRIPTION
**Pull request by RomainLibert**
Introduces new lunch.location model to replace res.partner on suppliers
New mail template for automatic ordering
Add the concept of new products (mark a product as new until some date)
The toppings are now defined by product category
Lunch.order removed, lunch.order.line renamed into lunch.order
New SQL report to get the wallet content (aggregate of lunch.cashmove and lunch.order)
New setting to allow negative wallet (aka overdraft)
Application now remembers what notes and toppings you last ordered with your product
You can change your location using the widget on the kanban view
Edition of the order can be done until the order is arrived

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by KangOl** [comment]
WTF?
Why model changes in a stable version?

robodoo r-

**Comment by tivisse** [comment]
@KangOl Not my decision. 

We'll work this out tomorrow.

**Comment by antonylesuisse** [comment]
@robodoo r-

**Comment by KangOl** [comment]
@robodoo r-

**Comment by tivisse** [comment]
@robodoo r-

**Comment by RomainLibert** [comment]
Merged in master

**Pull request closed without merging**
