### PR TITLE
[IMP] web: Allow to filter fields on domain widget

### PR DESCRIPTION
**Pull request by yajo**
* Export additional classes, to allow more extensibility downstream.
* Add search field on top of list.
* Automatic field list filtering, with timeout to avoid locking UI.

The result:

peek 2018-07-20 13-24

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by Yajo** [comment]
> I'm not sure if the runbot fail is because the new code that breaks JS QUnit tests.

So it seems.



> my functional review is: ...

Seems legit, although I'm gonna wait for the initial review from @odoo, just to make sure further development is headed in the good direction.

Only one comment about this:

> The search textbox should have the focus when unfolding the field selection.

... and user is using a keyboard.

Autofocus in input fields on touch screens is awful.

**Comment by Yenthe666** [comment]
You guys are on a roll! 👏

**Comment by pedrobaeza** [comment]
> Autofocus in input fields on touch screens is awful.

Well, I prefer it as it's more a residual case, and even that, you can type or tap outside, so no critical problem.

@ged-odoo we are eager to read your initial thoughts about this.

**Comment by Yajo** [comment]
Any chances to get this into v12?

**Comment by rafaelbn** [comment]
Hello, as Odoo is not moving forward here could we put this PR in OCB?

**Comment by pedrobaeza** [comment]
It's better to put this as a module, but we have to check if this can be inheritable. Any way, this was done against master before v12 release, but not for v11.

**Comment by Yajo** [comment]
It seems this landed in master already in #27788, but it is buggy. This PR is thus no more needed, and the fix to the new feature is in #29883.

As such, we can backport to OCB 11 and 12.

**Pull request closed without merging**
