### PR TITLE
[IMP] project: move planning option from project to planning setting

### PR DESCRIPTION
**Pull request by ravb-odoo**
before this commit, planning option is view in project setting.

This commit planning option is replace from project to planning setting with named 'Project Planning'

task-3251687

### CODE REVIEW

**Review by auon-odoo — APPROVED** [review]
Thanks for your work!

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work, however, we need to create a migration script as explained in my comment. 🙂

**Comment by xavierbol** [comment]
Hello @ravb-odoo ,

For next time, can you follow that format when you mention the task id in your commit message? 

`task-<task id>`

Thanks in advance!

**Comment by xavierbol** [comment]
robodoo r+

**Comment by xavierbol** [comment]
robodoo r+

**Comment by xavierbol** [comment]
robodoo r+

**Pull request closed without merging**
