### PR TITLE
[FIX] stock: display full forecast when there is no quant

### PR DESCRIPTION
**Pull request by guba-odoo**
**Quantity field is ignored in a sale order**

Impacted versions:
 
 - 16.0
 
Steps to reproduce:
1.- Create a new storable product
2.- Create an incoming transfer in the past with quantity equal to 1, within the past 3 months.
3.- To simulate the transfer being validated in the past, with the support tools change the date of the stock move to the one chosen for the transfer
4.- Create an outgoing transfer in the past with quantity equal to 1, within the past 3 months.
5.- To simulate the transfer being validated in the past, with the support tools change the date of the stock move to the one chosen for the transfer
6.- Verify the stock quant for the product does not exist, which it should not because it has quantity equal to 0
7.- Go to the forecast graph of the product, it will truncate to the day before the latest of the 2 transfers
 
Current behavior:
 
 - Forecast graph is truncated  to the day before the latest of the 2 transfers
Expected behavior:
- Forecast should show the past 3 months and the next 3 months
 
Notes:
In the table report_stock_quantity, the building process involves, for each product, creating a time series for all the quants that goes from 3 months in the past until 3 months in the future. Also, it involves, for done stock moves, a series that goes from 3 months in the past to 1 day before the move. If the quantity on hand is 0, the quant will momentarily have 0 quantity and then automatically delete. Therefore, the only information we will have if we only have done quantities are the time series for the moves. In the graph of forecasted inventory, we simply aggregate those results by product and date and that is how we obtain the forecast graph. However, if the on hand quantity is 0, and therefore there are no quants, and all the stock moves are done, then the datapoints will go from 3 months in the past to 1 day before the latest stock move. If that stock move is in the past, then we will not be able to see the present forecasted amount in the graph. By adding a time series for each product that goes back 3 months in the past to 3 months in the future, with quantity 0, this bug is fixed. This is because we add the dates we are missing and we do not affect the count for forecasted inventory, since we are only adding 0.

opw-3516127

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by guba-odoo** [comment]
Hello @odoo/rd-logistics,
Could you please take a look into this pull request?
Thank you

**Comment by guba-odoo** [comment]
Hello @Whenrow 
Could you please take a look into this pull request?
Thank you

**Comment by ticodoo** [comment]
Hello @guba-odoo before anyone reviews your PR, can you please update your commit message so it is easier to understand what it is you are fixing?

Your commit title should be shorter so it fits the standard (https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#commit-message-header) and so that it's easier to quickly understand (the char limit is more like 70 than 50, but shorter is better if possible), e.g.: `avoid truncated stock forecast`

Since you're doing a bugfix, it is preferred that your commit body writes out the steps to recreate the bug you are fixing so we know how to reproduce it, e.g. look at https://github.com/odoo/odoo/wiki/Contributing#reporting-issues for a template (only the steps + current/expected behavior). You can optionally include the extra why the bug is occur after the steps/expected result if it is not obvious from your code changes.

Also add the opw-##### at the bottom of your commit message so we know what ticket your bugfix is specific to.

And also for readability, your commit message body shouldn't exceed more than 72 chars per line for readability purposes. If you use vim as your editor for writing commit messages, the default setting already enforces this length automatically.

**Review by DjamelTouati — CHANGES_REQUESTED** [review]
Hello @guba-odoo , Please correct your pull request in accordance with the recommendations mentioned by @ticodoo 
Thank you!

**Comment by guba-odoo** [comment]
Hello @DjamelTouati,
Thanks for the feedback, I have applied the changes.
Thank you

**Comment by HANNICHE-Walid** [comment]
hi @guba-odoo thanks for your work LGTM
@ticodoo can you take look at this PR again please

**Comment by Whenrow** [comment]
@guba-odoo Hello, this PR is not what we consider as a  bugfix and also may impact performance. We can discuss adding a parameter or setting in master branch to display the desired date range.

**Pull request closed without merging**
