### PR TITLE
re-remove survey_crm

### PR DESCRIPTION
**Pull request by xmo-odoo**

### CODE REVIEW

**Comment by xmo-odoo** [comment]
robodoo r+

**Comment by KangOl** [comment]
saas-12.1 is EOL. Please target saas-12.2

**Comment by xmo-odoo** [comment]
robodoo r+

**Comment by KangOl** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
robodoo retry

@d-fence there seems to be something odd about the runbots, multiple stagings have failed in "cls.browser.stop()" with an OSError: [Errno 39] Directory not empty: <some_directory> from within shutil.rmtree(self.user_data_dir): http://runbot.odoo.com/runbot/build/540429 http://runbot.odoo.com/runbot/build/540444

**Comment by xmo-odoo** [comment]
robodoo retry 🙄

**Pull request closed without merging**
