### PR TITLE
[FIX] hr_holidays: make leaves work in non-UTC

### PR DESCRIPTION
**Pull request by jorenvo**
See individual commits for more details.

opw-2169863

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo rebase-ff

**Comment by jorenvo** [comment]
Some great points, thanks.

> I'd tend to think that only case [3] causes a problem, since [1, 2] are just floats

Indeed only `hour_{from,to}` are a problem. I was confused because I never explicitly set `request_unit_custom` but it turns out it's done automatically by `_default_get_request_parameters`. I changed it to adjust the date only in that case.

> Moreover, is taking January 1st as an arbitrary date ok in case of daylight saving?

I didn't think of daylight savings, I now instead take the `leave_date` itself. It's simpler anyway.

**Comment by jorenvo** [comment]
@robodoo rebase-ff

**Comment by jorenvo** [comment]
@robodoo r+

**Pull request closed without merging**
