### PR TITLE
[IMP] point_of_sale: readonly columns in pos models

### PR DESCRIPTION
**Pull request by caburj**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
@pimodoo What do you think about this?

**Comment by pedrobaeza** [comment]
@pimodoo @switch87 can you give your opinion on this?

**Comment by pimodoo** [comment]
@pedrobaeza Why would we need this PR as the behavior of having columns editable by default is not in odoo anymore?

**Comment by pedrobaeza** [comment]
@pimodoo thanks for resolving the situation. I'm not needing that, sorry for not specifying. I'm only triaging things periodically through suggestions given by codetriage.com.

**Comment by pimodoo** [comment]
@pedrobaeza Thank you, no problem

**Pull request closed without merging**
