### PR TITLE
[FIX] doc: make it compile

### PR DESCRIPTION
**Pull request by mart-e**
This PR fixes non-compliant javascript
As a side effect, these errors made the documentation fail.

@jem-odoo @qmo-odoo you're going to burn in a very special level of Hell. A level they reserve for documentation breakers and people who talk at the theater.
_\~ Shepherd Book, Firefly_

Bigs ups to @xmo-odoo who hunted these bugs down.

### CODE REVIEW

**Comment by mart-e** [comment]
@robodoo rebase-ff r+

**Comment by xmo-odoo** [comment]
4jhvivy

**Comment by mart-e** [comment]
@robodoo you better retry if you don't want to end it the special hell either !

**Comment by mart-e** [comment]
@robodoo you didn't really retry did you?

**Comment by xmo-odoo** [comment]
robodoo retry

**Comment by mart-e** [comment]
@robodoo , @d-fence said the bug is not determinist so let's just retry for the win !

**Comment by mart-e** [comment]
Well, it appears @qsm-odoo bypassed the bug and merged this fix already. How rude...

**Comment by qsm-odoo** [comment]
Oh yes, the error which made my linter fail. And once fixed, my linter revealed hundreds of warnings and errors in that file... :cry:

**Pull request closed without merging**
