### PR TITLE
[CLN] sale,*: simplify test commons

### PR DESCRIPTION
**Pull request by Feyensv**
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@robodoo r+ rebase-ff

**Comment by Williambraecky** [comment]
Hey @Feyensv 

This PR seems to have broken some tests without demo data: https://runbot.odoo.com/runbot/build/72871450
Could you take a look please? 
Thanks :)

**Comment by Feyensv** [comment]
@Williambraecky Yup, I'll look at it.
Is there is a custom trigger we can use when we want to run tests without demo data on runbot ?
I'm potentially planning different PRs related to tests and I'd like to make sure it doesn't break the nightly config next time :D.

**Comment by Williambraecky** [comment]
> @Williambraecky Yup, I'll look at it. Is there is a custom trigger we can use when we want to run tests without demo data on runbot ? I'm potentially planning different PRs related to tests and I'd like to make sure it doesn't break the nightly config next time :D.

There is a manual trigger "No demo Manual" just for that, let me know if you do not have access to it :)

**Pull request closed without merging**
