### PR TITLE
[IMP] l10n_in: add sale RCM taxes

### PR DESCRIPTION
**Pull request by hamo-odoo**
task-3681690

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jva-odoo** [comment]
Add in fiscal position

**Comment by hamo-odoo** [comment]
> Add in fiscal position

Done

**Comment by hamo-odoo** [comment]
@JulienVR Can you please review the PR?

**Review by JulienVR — COMMENTED** [review]
I'm kind of lost in all these taxes but I don't get this:
Some taxes (like `cess_sale_1591_rc` and `cess_purchase_1591_rc`) seems duplicated (and they both have `type_tax_use` set to 'none'), but they are referenced by a tax group which has a `type_tax_use`, is it on purpose ?
It seems you mostly duplicate existing taxes in this PR, although you don't set `type_tax_use`, why ?

**Review by JulienVR — COMMENTED** [review]
Ok, I got it thanks to @jco-odoo.
We create taxes with `type_tax_use` to `none`, and link them to a tax group (which has a `type_tax_use` set to `sale` or `purchase`) so the individual taxes cannot be selected on an account.move.line but the tax group can.
Were these new taxes validated functionally ?

**Comment by hamo-odoo** [comment]
> Were these new taxes validated functionally ?

Yes, @JulienVR these were functionally tested by Indian PO team (@shid-odoo, @ajjo-odoo and @shbh-odoo)

You seemed abit confused had to ping @jco-odoo :sweat_smile: on discord, he usually merges the PR for l10n_in

**Review by JulienVR — APPROVED** [review]
Ok then :)
@jco-odoo @h4818, could one of you review this please ? :grimacing:

**Comment by jco-odoo** [comment]
Blocked for the moment: we need to why this is needed and examples of how it works.  @ajjo-odoo

**Comment by hamo-odoo** [comment]
@jco-odoo After a discussion it's been decided to keep only 2 Sale RCM tax for example (IGST, GST 18%), other Sale RCM taxes can be created manually by seeing them if user requires them.

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
