### PR TITLE
[FIX] fields: recompute recursive stored fields

### PR DESCRIPTION
**Pull request by rco-odoo**
Stored computed fields that recursively depend on themselves are not recomputed as expected.
The trigger to recompute them is simply missing.

### CODE REVIEW

**Comment by KangOl** [comment]
In version 10.0?

**Comment by rco-odoo** [comment]
@KangOl the code that adds recomputation triggers has been refactored a bit before 10.0.
I may backport this fix to 8.0 or 9.0, but it will look somewhat different.

**Comment by simahawk** [comment]
I had this same issue on v9 a long time ago and I was forced to define a huge depends to support at least 4 levels of parent/children. Thanks for fixing this! Having this on v9 too would be nice indeed :)

**Comment by rco-odoo** [comment]
@simahawk I backported the fix to 9.0 in rev 4f983116231a69696f253752c1ca3866416be031.

**Comment by simahawk** [comment]
great! thanks :)

**Pull request merged**
