### PR TITLE
[FIX] google_drive: use OAuth2 consent flow

### PR DESCRIPTION
**Pull request by kbapt**
As Google is deprecating the Out-Of-Band flow on 3rd October 2022[1],
here we are adapting to use a more secure authorization method.

[1]: https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob

TaskID: 2867215

### CODE REVIEW

**Comment by bouvyd** [comment]
For the record, i'm not sure the feature can survive the flow change, since our Google Oauth config for the "Odoo Drive" requires to now in advance the domain from where the requests will come, which is simply impossible (wildcards for *.odoo.com urls would not be accepted, so even an "odoo-cloud" only solution would not work).

We may have to drop the feature altogether, since there is no clean way from a User Experience to preserve the feature without adding a ton of friction as to render it not worth it.

I'll update with more info when we reach a decision.

**Comment by bouvyd** [comment]
For the record, i'm not sure the feature can survive the flow change, since our Google Oauth config for the "Odoo Drive" requires to now in advance the domain from where the requests will come, which is simply impossible (wildcards for *.odoo.com urls would not be accepted, so even an "odoo-cloud" only solution would not work).

We may have to drop the feature altogether, since there is no clean way from a User Experience to preserve the feature without adding a ton of friction as to render it not worth it.

I'll update with more info when we reach a decision.

**Comment by bouvyd** [comment]
For the record, i'm not sure the feature can survive the flow change, since our Google Oauth config for the "Odoo Drive" requires to now in advance the domain from where the requests will come, which is simply impossible (wildcards for *.odoo.com urls would not be accepted, so even an "odoo-cloud" only solution would not work).

We may have to drop the feature altogether, since there is no clean way from a User Experience to preserve the feature without adding a ton of friction as to render it not worth it.

I'll update with more info when we reach a decision.

**Comment by bouvyd** [comment]
Update: we have decided to drop the feature, as supporting it would mean either having a proxy setup on a domain we control (and the scope/usefulness of the feature simply does not warrant such resources) or reducing its usefulness by a huge factor (as the user would need to register an app on the google admin console for their google workspace account).

It will be disabled after October 2nd in stable versions (with proper error message for those who have the module installed and no possible new install possible if it was not already installed) and will be removed entirely from v16 and up.

**Comment by Jerther** [comment]
Oh no... :'(

Well thank you very much for the update and the explanation @bouvyd . This should give us enough time to find an alternative.

**Comment by petrus-v** [comment]
I guess as a work arround regarding google_spreadsheet integration odoo provide a [Gsheet template](https://docs.google.com/spreadsheets/d/1KUlSSzZMzkEEzyroyZ2NerRt1RVCspkG9VQIh2V6dnM/edit#gid=0) and a [blog post](https://www.odoo.com/blog/odoo-news-5/changes-to-google-drive-and-google-spreadsheet-integrations-for-existing-odoo-versions-957)

**Pull request closed without merging**
