### PR TITLE
[MERGE] web,*: harmonize layout & responsive

### PR DESCRIPTION
**Pull request by pparidans**
This merge harmonize the layout and styling between community and enterprise edition.

This allows to simplify some templates and avoid overrides in enterprise only.

But the main goal is to make both edition responsive.

Among other things, a few bugs have been also fixed (like the "add column" button contrast in kanban...) 
and Bootstrap configuration/customization files are grouped in `web/static/src/scss`.

### CODE REVIEW

**Review by adr-odoo — APPROVED** [review]
@robodoo rebase-merge r+

**Comment by adr-odoo** [comment]
@robodoo r+

**Comment by legalsylvain** [comment]
CC : @OCA/web-maintainers feel free to review.

**Comment by pedrobaeza** [comment]
Some feedback about unresponsiveness I found in this runbot instance:

Selección_003
Selección_004

**Comment by adr-odoo** [comment]
> Some feedback about unresponsiveness I found in this runbot instance:
> 
> Selección_003 Selección_004

Thanks for this feedback. Fixes will follow.

**Comment by legalsylvain** [comment]
Hi. Thanks @adr-odoo for your quick reply ! 

Could you also integrate the responsive menu in this PR ? the dropdown list for the apps is is not adapted to small screens / touch screens.

Note : if you want functional review, do not hesitate to ping us.

**Comment by adr-odoo** [comment]
> Hi. Thanks @adr-odoo for your quick reply !
> 
> Could you also integrate the responsive menu in this PR ? the dropdown list for the apps is is not adapted to small screens / touch screens.
> 
> Note : if you want functional review, do not hesitate to ping us.

Unfortunately I was not allowed to do this for two reasons:
- We have to keep a difference between our two versions (Community and Enterprise) and this menu is one of them because it's like en entry point.
- Plus we already had some issues with the enterprise menu regarding the App Store guidelines, I didn't want to add it in community.

However, I completely agree with you and we were already busy thinking about this problem.
Thank you for reporting this issue to us. This allows us to realize the importance of this menu.

**Pull request closed without merging**
