### PR TITLE
[IMP] account: preview in accrual wizard

### PR DESCRIPTION
**Pull request by william-andre**
Task [2168064](https://www.odoo.com/web?#id=2168064&action=333&active_id=967&model=project.task&view_type=form&cids=1&menu_id=4720)
[IMP] account: preview in accrual wizard
Show a preview of what will be done when using the accrual wizard

[IMP] account: accrual never change account on the fly
Before this commit, the account on the original line was replaced by the
accrual account. This could be problematic for hashed journals. Instead
of having 2 different behaviors for hashed/non hashed journals, we
decided to always create 2 journal entries, which is also more academic:
* We don't replace something on an entry that has been posted
* We don't end up with taxes on the accrual account
* Accountants are used to do it this way

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@robodoo rebase-ff

**Comment by william-andre** [comment]
@robodoo retry

**Comment by qdp-odoo** [comment]
@robodoo retry

**Comment by qdp-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by william-andre** [comment]
@qdp-odoo Ok, the error was the code of the new accounts in the generic CoA messing with the tests of account_reports, I changed it

**Comment by william-andre** [comment]
@qdp-odoo AVW noticed while testing that this was still not merged. r+ again?

**Comment by william-andre** [comment]
@smetl @oco-odoo or @csnauwaert , is one of you kind enough?

**Comment by csnauwaert** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
