### PR TITLE
[FIX] base: partner demo data should be noupdate = 1

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

Steps to reproduce (1):

- A new production database is created from scratch using demo data, that later is customized.
- Time later, in ir_module_module, you manually set demo = False.
- Do update/migrate.
  => The partners from the demo, already customized, will be deleted.

Steps to reproduce (2):

- A new production database is created from scratch using demo data, that later is customized.
- Do update/migrate.
  => The customized demo partners are reseted to their default.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
> should a tag for 'base' be created? I like get tagged

I have no idea what you mean.

**Comment by MiquelRForgeFlow** [comment]
When I do a PR to core, normally the PR gets a ORM tag. And when I do a PR to sale, a sales tag is put. But I miss in base getting a tag hehe

**Comment by mart-e** [comment]
Hello,

Your whole scenario doesn't sound very good, why would you want to do that on a production database?
Activating the demo data on production is not something I would recommand and setting `demo=False` is thankfully a good way to get rid of it.

**Comment by bouvyd** [comment]
Hello,

I agree with @mart-e - this is not a good scenario. Demo data are meant for demo, and no production database should be set to use them. This might be the way you work, and we don't plan on preventing it actively, but we will not attempt to support it.

We prefer having demo data as updateable, as it makes some dev flows easier (just -u to "reset").

**Comment by MiquelRForgeFlow** [comment]
Ok, thank you for your answer.

**Pull request closed without merging**
