### PR TITLE
[FIX] mail: wrong title for call setting on chat window

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
-Probably the author forgot to change it when copy from 'Show Member List'

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Dear @alexkuhn @ThanhDodeurOdoo  , can you take a look sir, minor typo i suppose

**Comment by duong77476-viindoo** [comment]
> Hello, you'll need to export the translation file with the new terms as you change string value in stable.

Yes done, i only add and remove what is needed, please review thank you

**Comment by duong77476-viindoo** [comment]
@seb-odoo This PR only need in v16 not in v17 sir

**Comment by seb-odoo** [comment]
Ok thank you, I didn't realize the string already existed but it's fine like this.

The title should have FIX tag not IMP.

**Comment by duong77476-viindoo** [comment]
> Ok thank you, I didn't realize the string already existed but it's fine like this.
> 
> The title should have FIX tag not IMP.

Done sir fast and furious

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

**Comment by duong77476-viindoo** [comment]
> @robodoo r+

I thought we need to setup the forward to somewhere between 16 and 17 because like i said v17 is fine

**Comment by seb-odoo** [comment]
@fw-bot ignore

I guess it's fine since 16.3 refactoring, so there's no intermediate version

**Pull request closed without merging**
