### PR TITLE
FIX [9.0] Financial Report not sorted the right way... #10240

### PR DESCRIPTION
**Pull request by letzdoo-js**

### CODE REVIEW

**Comment by be-cloud-js** [comment]
Hello,

Any idea why CLA is rejected ?

**Comment by be-cloud-js** [comment]
Any idea why CLA signature check failed ??

Thanks,

Jerome

**Comment by mart-e** [comment]
Hello,

You are signing the CLA with the wrong email address. You are making commits with `@imply.lu` email address while you are signing with a `@be-cloud.be` address

**Comment by be-cloud-js** [comment]
Make another one to fix CLA issue

**Pull request closed without merging**
