### PR TITLE
[FIX] web: read records up to list limit

### PR DESCRIPTION
**Pull request by len-foss**
Fine-tuning of commit e7fab234201e357da52c3576ad2e8fc9ceee9359
In a one2many with more than one page with a limit of k records, add a line l.
It increments the list limit to k+1. Remove a line above (of index <= k).
It will try to load a line l' to replace it, that it will find on page 2.
However when deciding if it should read missing fields on that record, it will
scan at most u records, skipping virtual ids.
Here u is the mean between the current number of lines and the list limit
without the temporary increase due to the added record.
Since there are at least two pages, u = k.
However since l is in the list at index k, then l' won't be read, and since it
was on page 2 its data hasn't been loaded.
Therefore the js would traceback when trying to evaluate it.

opw 1913361

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by len-odoo** [comment]
@aab-odoo 
If you try to reproduce the bug (as stated in the OPW) it works every time, but for some reason in the test, while we have seemingly the same situation, it doesn't work.
Because in the test, contrarily to what is written in the commit message, the virtual ID is always put at the end of the list instead of in the middle.

**Comment by aab-odoo** [comment]
@len-odoo In commit message: mean -> min (i was confused for a while).
According to your explanation, i think that reading k records is correct. If we correctly omit the removed record and the one we just added, the k-th record is the first one of page 2... So i assume that we are still reading the record that has been removed, which is the source of the problem. What do you think?

**Comment by aab-odoo** [comment]
@len-odoo About your question for the test, the only reason i see why it could be different is the presence of an onchange (in real), and it's absence in the test. The js part is the same to if the same RPCs are done and if they return the same commands, you must get the same result.

**Comment by len-odoo** [comment]
No, you have k+1 records on the first page (the virtual one has been added), so the k first records are still the first page + the virtual one.
As to where the difference in the test comes from, it must be because of a call to _sortList that is done differently. 
What is less clear is if there is a wrong use of currentResIDs instead of orderedResIDs somewhere. 

Anyway it's a bit bottom of the stack now as it is high time investment/ low reward.

**Comment by aab-odoo** [comment]
Ok i understand now. I think that you fix is correct. I check the test

**Comment by len-odoo** [comment]
Actually if we want to keep the clever-ish computation of the upperbound, we could replace the fix by an `else upperbound++`, which would just increase the number of records read iff some virtualID inserted itself in the party.

**Comment by aab-odoo** [comment]
No i think you're right, we don't have to decrease the limit here. This was a mistake.

**Comment by len-odoo** [comment]
It worked perfectly. Thanks for your help.

**Comment by len-odoo** [comment]
@aab-odoo At this point, I think @ged-odoo 's intuition that we should really use list.orderedResIDs 
was the missing piece of the fix.
Otherwise you can check that some tests break:
    'one2many, onchange, edition and multipage...'
    'editing tabbed one2many (editable=bottom)'
    
(Note that the using `else {upperBound = Math.min(upperBound + 1, (list.limit || currentCount));}`
is still a valid bugfix that is basically risk-free.)

**Comment by aab-odoo** [comment]
@len-odoo I pushed an updated version that i checked with ged, waiting for a green runbot hopefully

**Comment by len-odoo** [comment]
It's not, at least `delete a record while adding another one in a multipage` breaks.

**Comment by len-odoo** [comment]
@aab-odoo @ged-odoo 
So what now?

**Comment by aab-odoo** [comment]
@len-odoo We're not really happy with the solution but we can't find something better which doesn't imply a large rewrite of some parts of the basic model. I pushed a slightly modified version of your last commit.

**Comment by len-odoo** [comment]
robodoo r+

**Pull request closed without merging**
