### PR TITLE
[11.0] CLA signature

### PR DESCRIPTION
**Pull request by SilvioGregorini**
Adding both my individual CLA and corporate CLA (for the company I work for)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by matteoopenf — APPROVED** [review]

**Comment by mart-e** [comment]
Hi!
Thanks for the signature but no need to sign it twice, the corporate signature is enough as it is based on the email.

**Comment by SilvioGregorini** [comment]
@mart-e 
Thank you, but we discussed it within our own company and decided to leave each employee free to decide whether he/she/they want to sign it as a company contributor, an individual contributor, or both.
If it's not a problem, I'd like to leave this PR as it is; but if you tell me it might create any kind of trouble (legally, technically, etc), I'll update this PR asap to include only the corporate signature.

**Comment by mart-e** [comment]
@SilvioGregorini what I meant was that the verification is done based on the email used in the commit. If an email is present in the corporate CLA file, we consider this person has agreeded to the CCLA. If someone wants to sign it individually, they should not be present in the corporate file and only in the individual one (this means their contribution would be made on a personal basis).
What is sometime done when you don't want to involve a company for all contribution is to sign twice a CLA but with two different email addresses. One with the corporate address for the CCLA and another commit with their personal email address for the ICLA.

Technically it is not an issue to reuse the email address in two files but this would bring some confusion legally. In case we have trouble with one contribution, it would not be clear if this was a personal or a corporate contribution, hence which responsability is involved.

I hope it clarifies.

**Comment by SilvioGregorini** [comment]
@mart-e 
Thank you so much, that does definitely clarify! 😄 

I will update this PR in a few minutes.

**Review by matteoopenf — APPROVED** [review]

**Comment by mart-e** [comment]
Not sure if @robodoo still merge 11.0 PRs, let's try :crossed_fingers: 
@robodoo r+

**Comment by mart-e** [comment]
robodoo retry ?

**Pull request closed without merging**
