### PR TITLE
[FIX] l10n_it_edi: foreign currencies produce invalid XML

### PR DESCRIPTION
**Pull request by viso-odoo**
Following commit https://github.com/odoo/odoo/pull/171765/files#
multi-currencies are not supported anymore by our edi engine.

Using a currency other than euro leads to an invalid XML file.

Steps to reproduce:

1. install Italian E-invoicing
2. make sure your have access to another currency, along with EUR
3. create a partner outside of Europe (e.g. US-based - using USD)
4. create an invoice for that partner
5. confirm + send and print the invoice (generate XML file)
6. go to https://www.fatturacheck.it/ to verify the XML
7. Error 2.2.2.5 should be returned

opw-4038850
opw-4129380
opw-4123758
opw-4095910

### CODE REVIEW

**Comment by viso-odoo** [comment]
Hello @jco-odoo ,
Putting this one back at the top of the pile as we are having more tickets with the same issue.
Let me know if/how I can help :)

**Comment by jco-odoo** [comment]
@viso-odoo  Everything in the XML should be in EUR.  The error might have slipped in with github.com/odoo/odoo/pull/171765 where we might have taken price_subtotal (which is in currency) instead of the balance (which is in company currency or EUR)

As the regular numbers are in EURO, that error should normally not appear about multi-currency.  (as the multi-currency is in the AltriDatiGestionali and that is like something where you can put anything and as such not checked by messages)

**Comment by jco-odoo** [comment]
https://github.com/odoo/odoo/pull/171765/files#diff-7a314f6fb9514fd24adb9e88e00fe802ff75743c7227d648a65f44ca34de9883R272 to be precise  (it was line.balance before)

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
