### PR TITLE
[FIX] web_editor: only update overlay if manipulator is already present

### PR DESCRIPTION
**Pull request by ap-wtioit**
Description of the issue/feature this PR addresses:
* in addons/website/tests/test_ui.py it can happen that the snippet.editor.js cover function is called before the parent is visible in the DOM, this causes the following error to appear in the firefox console:
```
TypeError: manipulatorOffset is undefined[Learn More] web_editor.assets_editor.js:135:214
```
chrome console:
```
VM707 web_editor.assets_editor.js:135 Uncaught TypeError: Cannot read property 'top' of undefined
```
phantomjs (runbot):
```
2018-07-30 11:36:23 | ERROR | server | odoo.addons.website.tests.test_ui:474 write FAIL: test_02_admin_tour_banner (odoo.addons.website.tests.test_ui.TestUi)
...
2018-07-30 11:36:23 | ERROR | server | odoo.addons.website.tests.test_ui:474 write self.phantom_js("/",  "odoo.__DEBUG__.services['web_tour.tour'].run('banner')",  "odoo.__DEBUG__.services['web_tour.tour'].tours.banner.ready",  login='admin')
...
2018-07-30 11:36:23 | ERROR | server | odoo.addons.website.tests.test_ui:474 write ` AssertionError: ("TypeError:  undefined is not an object (evaluating 'manipulatorOffset.top')\n"
```

Current behavior before PR:
* snippet.editor.js cover function may throw a Type error if the manipulator is not yet visible in the dom

Desired behavior after PR is merged:
* snippet.editor.js cover function checks if manipulatorOffset is defined before using its properties (and calls itself after 10 ms again up to 5 times)

To test (in Firefox, in Chrome it only happens sometimes (on my system every 5th time)):
* log into Odoo 11 on Runbot as admin (e.g. http://354150-11-0-5dc180.runbot13.odoo.com/web)
* open the website (e.g. http://354150-11-0-5dc180.runbot13.odoo.com/)
* make sure its clean (Delete the two sections that may have been added by a previous run until you see the "Drag Building Blocks Here" image, and save)
* open developer tools (CTRL + SHIFT + I)
* activate preserve logs
* run the banner test: 
```
odoo.__DEBUG__.services['web_tour.tour'].run('banner', 'test')
```
* Console Output shows the error:
<details><summary>Click to show firefox console output</summary>

```
odoo.__DEBUG__.services['web_tour.tour'].run('banner', 'test')
Preparing tour banner web.assets_common.js:4198:210
Running tour banner web.assets_common.js:4200:1
Navigated to http://354150-11-0-5dc180.runbot13.odoo.com/
undefined
DOM doesn't contain '.o_payment_form' web.assets_frontend.js:2030:336
Tour Manager is ready.  running_tour=banner web.assets_common.js:4195:575
Tour banner: step a[data-action=edit] succeeded web.assets_common.js:4205:338
Tour banner: step #snippet_structure .oe_snippet:eq(1) .oe_snippet_thumbnail succeeded web.assets_common.js:4205:338
Tour banner: step #wrapwrap .s_text_block_image_fw h2 succeeded web.assets_common.js:4205:338
[Show/hide message details.] TypeError: manipulatorOffset is undefined[Learn More] web_editor.assets_editor.js:135:214
Tour banner: step .oe_overlay_options .oe_options succeeded web.assets_common.js:4205:338
Tour banner: step #snippet_structure .oe_snippet:eq(3) .oe_snippet_thumbnail succeeded web.assets_common.js:4205:338
Tour banner: step button[data-action=save] succeeded web.assets_common.js:4205:338
Navigated to http://354150-11-0-5dc180.runbot13.odoo.com/#scrollTop=0
DOM doesn't contain '.o_payment_form' web.assets_frontend.js:2030:336
Tour Manager is ready.  running_tour=banner web.assets_common.js:4195:575
Tour banner: step a[data-action=show-mobile-preview] succeeded web.assets_common.js:4205:338
Tour banner: step .modal-dialog:has(#mobile-viewport) button[data-dismiss=modal] succeeded web.assets_common.js:4205:338
Tour banner: step #new-content-menu > a succeeded web.assets_common.js:4205:338
Tour banner succeeded web.assets_common.js:4209:444
ok
```
</details>
<details><summary>Click to show chrome console output</summary>

```
odoo.__DEBUG__.services['web_tour.tour'].run('banner', 'test')
VM636 web.assets_common.js:4198 Preparing tour banner
VM636 web.assets_common.js:4200 Running tour banner
undefined
Navigated to http://354150-11-0-5dc180.runbot13.odoo.com/
VM679 web.assets_frontend.js:2030 DOM doesn't contain '.o_payment_form'
VM678 web.assets_common.js:4195 Tour Manager is ready.  running_tour=banner
VM678 web.assets_common.js:4205 Tour banner: step a[data-action=edit] succeeded
VM678 web.assets_common.js:4205 Tour banner: step #snippet_structure .oe_snippet:eq(1) .oe_snippet_thumbnail succeeded
VM707 web_editor.assets_editor.js:135 Uncaught TypeError: Cannot read property 'top' of undefined
    at Class.cover (VM707 web_editor.assets_editor.js:135)
    at Class.toggleFocus (VM707 web_editor.assets_editor.js:136)
    at VM707 web_editor.assets_editor.js:165
    at VM678 web.assets_common.js:802
    at fire (VM678 web.assets_common.js:796)
    at Object.add [as done] (VM678 web.assets_common.js:797)
    at Array.<anonymous> (VM678 web.assets_common.js:802)
    at Function.each (VM678 web.assets_common.js:625)
    at Object.<anonymous> (VM678 web.assets_common.js:802)
    at Function.Deferred (VM678 web.assets_common.js:803)
cover @ VM707 web_editor.assets_editor.js:135
toggleFocus @ VM707 web_editor.assets_editor.js:136
(anonymous) @ VM707 web_editor.assets_editor.js:165
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
add @ VM678 web.assets_common.js:797
(anonymous) @ VM678 web.assets_common.js:802
each @ VM678 web.assets_common.js:625
(anonymous) @ VM678 web.assets_common.js:802
Deferred @ VM678 web.assets_common.js:803
then @ VM678 web.assets_common.js:802
_activateSnippet @ VM707 web_editor.assets_editor.js:165
(anonymous) @ VM707 web_editor.assets_editor.js:153
dispatch @ VM678 web.assets_common.js:892
elemData.handle @ VM678 web.assets_common.js:865
trigger_mouse_event @ VM678 web.assets_common.js:4192
_click @ VM678 web.assets_common.js:4192
_text @ VM678 web.assets_common.js:4192
text @ VM678 web.assets_common.js:4191
(anonymous) @ VM678 web.assets_common.js:4210
(anonymous) @ VM678 web.assets_common.js:44
setTimeout (async)
_.delay @ VM678 web.assets_common.js:44
_to_next_running_step @ VM678 web.assets_common.js:4210
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
add @ VM678 web.assets_common.js:797
(anonymous) @ VM678 web.assets_common.js:802
each @ VM678 web.assets_common.js:625
(anonymous) @ VM678 web.assets_common.js:802
Deferred @ VM678 web.assets_common.js:803
then @ VM678 web.assets_common.js:802
_activate_tip @ VM678 web.assets_common.js:4205
_check_for_tooltip @ VM678 web.assets_common.js:4203
update @ VM678 web.assets_common.js:4201
_consume_tip @ VM678 web.assets_common.js:4207
(anonymous) @ VM678 web.assets_common.js:4190
(anonymous) @ VM678 web.assets_common.js:44
setTimeout (async)
_.delay @ VM678 web.assets_common.js:44
executeBound @ VM678 web.assets_common.js:42
bound @ VM678 web.assets_common.js:43
do_before_unload @ VM678 web.assets_common.js:4190
(anonymous) @ VM678 web.assets_common.js:4210
(anonymous) @ VM678 web.assets_common.js:44
setTimeout (async)
_.delay @ VM678 web.assets_common.js:44
_to_next_running_step @ VM678 web.assets_common.js:4210
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
add @ VM678 web.assets_common.js:797
(anonymous) @ VM678 web.assets_common.js:802
each @ VM678 web.assets_common.js:625
(anonymous) @ VM678 web.assets_common.js:802
Deferred @ VM678 web.assets_common.js:803
then @ VM678 web.assets_common.js:802
_activate_tip @ VM678 web.assets_common.js:4205
_check_for_tooltip @ VM678 web.assets_common.js:4203
update @ VM678 web.assets_common.js:4201
(anonymous) @ VM678 web.assets_common.js:4215
later @ VM678 web.assets_common.js:46
setTimeout (async)
later @ VM678 web.assets_common.js:46
setTimeout (async)
(anonymous) @ VM678 web.assets_common.js:46
childList (async)
(anonymous) @ VM678 web.assets_common.js:971
domManip @ VM678 web.assets_common.js:984
prepend @ VM678 web.assets_common.js:971
jQuery.fn.(anonymous function) @ VM678 web.assets_common.js:987
(anonymous) @ VM678 web.assets_common.js:3949
(anonymous) @ VM678 web.assets_common.js:3949
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
add @ VM678 web.assets_common.js:797
(anonymous) @ VM678 web.assets_common.js:802
each @ VM678 web.assets_common.js:625
(anonymous) @ VM678 web.assets_common.js:802
Deferred @ VM678 web.assets_common.js:803
then @ VM678 web.assets_common.js:802
__widgetRenderAndInsert @ VM678 web.assets_common.js:3949
prependTo @ VM678 web.assets_common.js:3949
_startEditMode @ VM708 website.assets_editor.js:117
handleAction @ VM679 web.assets_frontend.js:98
(anonymous) @ VM679 web.assets_frontend.js:95
_.each._.forEach @ VM678 web.assets_common.js:12
_handleAction @ VM679 web.assets_frontend.js:94
_onActionMenuClick @ VM679 web.assets_frontend.js:97
(anonymous) @ VM678 web.assets_common.js:3923
dispatch @ VM678 web.assets_common.js:892
elemData.handle @ VM678 web.assets_common.js:865
trigger_mouse_event @ VM678 web.assets_common.js:4192
_click @ VM678 web.assets_common.js:4192
auto @ VM678 web.assets_common.js:4191
(anonymous) @ VM678 web.assets_common.js:4210
(anonymous) @ VM678 web.assets_common.js:44
setTimeout (async)
_.delay @ VM678 web.assets_common.js:44
_to_next_running_step @ VM678 web.assets_common.js:4210
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
add @ VM678 web.assets_common.js:797
(anonymous) @ VM678 web.assets_common.js:802
each @ VM678 web.assets_common.js:625
(anonymous) @ VM678 web.assets_common.js:802
Deferred @ VM678 web.assets_common.js:803
then @ VM678 web.assets_common.js:802
_activate_tip @ VM678 web.assets_common.js:4205
_check_for_tooltip @ VM678 web.assets_common.js:4203
update @ VM678 web.assets_common.js:4201
(anonymous) @ VM678 web.assets_common.js:4198
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
add @ VM678 web.assets_common.js:797
(anonymous) @ VM678 web.assets_common.js:802
each @ VM678 web.assets_common.js:625
(anonymous) @ VM678 web.assets_common.js:802
Deferred @ VM678 web.assets_common.js:803
then @ VM678 web.assets_common.js:802
_register @ VM678 web.assets_common.js:4197
_.each._.forEach @ VM678 web.assets_common.js:12
_register_all @ VM678 web.assets_common.js:4197
(anonymous) @ VM678 web.assets_common.js:4216
(anonymous) @ VM678 web.assets_common.js:44
setTimeout (async)
_.delay @ VM678 web.assets_common.js:44
executeBound @ VM678 web.assets_common.js:42
bound @ VM678 web.assets_common.js:43
(anonymous) @ VM678 web.assets_common.js:4216
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
deferred.(anonymous function) @ VM678 web.assets_common.js:803
(anonymous) @ VM678 web.assets_common.js:3865
add_template @ VM678 web.assets_common.js:3709
(anonymous) @ VM678 web.assets_common.js:3705
(anonymous) @ VM678 web.assets_common.js:3719
load (async)
load_xml @ VM678 web.assets_common.js:3719
add_template @ VM678 web.assets_common.js:3704
_load @ VM678 web.assets_common.js:3865
(anonymous) @ VM678 web.assets_common.js:3864
(anonymous) @ VM678 web.assets_common.js:4215
(anonymous) @ VM678 web.assets_common.js:4217
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
done @ VM678 web.assets_common.js:1192
callback @ VM678 web.assets_common.js:1212
XMLHttpRequest.send (async)
send @ VM678 web.assets_common.js:1209
ajax @ VM678 web.assets_common.js:1185
(anonymous) @ VM678 web.assets_common.js:3839
genericJsonRpc @ VM678 web.assets_common.js:3833
jsonRpc @ VM678 web.assets_common.js:3839
rpc @ VM678 web.assets_common.js:3843
query @ VM678 web.assets_common.js:3935
(anonymous) @ VM678 web.assets_common.js:4214
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
deferred.(anonymous function) @ VM678 web.assets_common.js:803
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
deferred.(anonymous function) @ VM678 web.assets_common.js:803
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
fireWith @ VM678 web.assets_common.js:801
done @ VM678 web.assets_common.js:1192
callback @ VM678 web.assets_common.js:1212
XMLHttpRequest.send (async)
send @ VM678 web.assets_common.js:1209
ajax @ VM678 web.assets_common.js:1185
(anonymous) @ VM678 web.assets_common.js:3839
genericJsonRpc @ VM678 web.assets_common.js:3833
jsonRpc @ VM678 web.assets_common.js:3839
(anonymous) @ VM678 web.assets_common.js:3990
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
add @ VM678 web.assets_common.js:797
(anonymous) @ VM678 web.assets_common.js:802
each @ VM678 web.assets_common.js:625
(anonymous) @ VM678 web.assets_common.js:802
Deferred @ VM678 web.assets_common.js:803
then @ VM678 web.assets_common.js:802
rpc @ VM678 web.assets_common.js:3988
load_translations @ VM678 web.assets_common.js:3828
load_translations @ VM678 web.assets_common.js:3978
(anonymous) @ VM678 web.assets_common.js:3968
(anonymous) @ VM678 web.assets_common.js:802
fire @ VM678 web.assets_common.js:796
add @ VM678 web.assets_common.js:797
(anonymous) @ VM678 web.assets_common.js:802
each @ VM678 web.assets_common.js:625
(anonymous) @ VM678 web.assets_common.js:802
Deferred @ VM678 web.assets_common.js:803
then @ VM678 web.assets_common.js:802
session_init @ VM678 web.assets_common.js:3968
session_bind @ VM678 web.assets_common.js:3968
(anonymous) @ VM679 web.assets_frontend.js:3
process_job @ VM678 web.assets_common.js:3782
process_jobs @ VM678 web.assets_common.js:3788
define @ VM678 web.assets_common.js:3771
(anonymous) @ VM679 web.assets_frontend.js:3
VM678 web.assets_common.js:4205 Tour banner: step #wrapwrap .s_text_block_image_fw h2 succeeded
VM678 web.assets_common.js:4205 Tour banner: step .oe_overlay_options .oe_options succeeded
VM678 web.assets_common.js:4205 Tour banner: step #snippet_structure .oe_snippet:eq(3) .oe_snippet_thumbnail succeeded
VM678 web.assets_common.js:4205 Tour banner: step button[data-action=save] succeeded
Navigated to http://354150-11-0-5dc180.runbot13.odoo.com/
web.assets_frontend.js:2030 DOM doesn't contain '.o_payment_form'
web.assets_common.js:4195 Tour Manager is ready.  running_tour=banner
web.assets_common.js:4205 Tour banner: step a[data-action=show-mobile-preview] succeeded
web.assets_common.js:4205 Tour banner: step .modal-dialog:has(#mobile-viewport) button[data-dismiss=modal] succeeded
web.assets_common.js:4205 Tour banner: step #new-content-menu > a succeeded
web.assets_common.js:4209 Tour banner succeeded
web.assets_common.js:4209 ok
```
</details>

Info @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@qsm-odoo @gde-odoo 
May I ask you to review this? The solution is probably not the way you want to resolve it, but the issue is real. A dirty timing issue in a test is not the things you normally want to have :-)

> most likely the parent is still not displayed in the DOM, see http://api.jquery.com/offset/

**Comment by ap-wtioit** [comment]
@qsm-odoo error also happened on official runbot in http://runbot.odoo.com/runbot/build/424661, may i ask you to review and maybe merge this?

**Comment by qsm-odoo** [comment]
@ap-wtioit Sorry, forgot about this. I however cannot merge this as the solution is not the correct one, I will try checking if I can solve the problem today.

**Comment by ap-wtioit** [comment]
The issue was solved by https://github.com/odoo/odoo/pull/31440 395c169db93c0146ea120bd19f16eb1864885a1d instead of this pull request

**Comment by ap-wtioit** [comment]
@qsm-odoo it seems we still get
```
AssertionError: ("TypeError: undefined is not an object (evaluating 'manipulatorOffset.top')\n" 
```
in the tests sometimes (see https://github.com/odoo/odoo/pull/39228, http://runbot.odoo.com/runbot/build/664079)

could you have another look at this? should i reopen this pull request?

**Comment by qsm-odoo** [comment]
@ap-wtioit I will keep it in mind if I once got the time to investigate.

**Pull request closed without merging**
