### PR TITLE
[FIX] sale_management: fix quotation template and pricelist conflict

### PR DESCRIPTION
**Pull request by jvnm-dev**
### Issue

    - Install Sales
    - Create Pricelist with Discount (5%) on a specific product/service
    - Create Quotation Template with standard unit price of the
      product/service
    - Create Sales Order with selecting both Quotation Template and
      Discount Pricelist

### Cause

6b5a1cbe

### Solution

    Applying pricelist rules on the template's price

**OPW-2151431**

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
@nim-odoo

**Comment by nim-odoo** [comment]
Hum, that actually looks more like an improvement than a fix. Maybe something we should consider for master. To me, it is not striking to only support "fixed prices" on template.

**Comment by jvm-odoo** [comment]
Hello @Feyensv ,

What do you think about this?

In #41055, we decide to use the template line's price if the discount policy
is not 'without' discount and if there is a template line's price but now it doesn't take the pricelist rules into account

**Comment by Feyensv** [comment]
I made a feedback asking to remove the prices from templates (which currency is used ? what about changing the product price and forgetting to update the quotation template price?).
About v13.0 (and saas13.1), I'm not sure how we want the functionality to work...

IMO, if we support the pricelists, we should support them totally, not only fixed prices and discount.
But supporting them totally would always overwrite the price from the template, which would make the prices on the templates useless...

This cannot be solved (and changed) consistently and easily thus we maybe should leave it like it is now, unless the PO's have a different opinion on this.

**Pull request closed without merging**
