### PR TITLE
12.0 cla easypme

### PR DESCRIPTION
**Pull request by cvinh**
Add CLA for EasyPME (French Polynesia)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by cvinh** [comment]
cc@luceeasypme

**Comment by mart-e** [comment]
Hi,

Thanks for the signature but there is still something odd. This CLA is signed for easypme.com but the commiter email is invitu.com.
The commiter must be the same as the one present in the CLA.

Could you also update the commit message to something like `[CLA] EasyPME signs Odoo CCLA`

Thanks

**Comment by cvinh** [comment]
@luceeasypme

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
