### PR TITLE
[REM] calendar: delete auto_join=False

### PR DESCRIPTION
**Pull request by yelizariev**
it was made for old implementation that is changed since Odoo 14.0

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
@Xavier-Do

**Comment by Xavier-Do** [comment]
If tests are green LGTM I guess.
Small request, can you add the commit that made this change in the commit message for future references/lazier review?

**Comment by Xavier-Do** [comment]
@robodoo delegate+

**Comment by yelizariev** [comment]
@robodoo r+

**Comment by yelizariev** [comment]
@robodoo r+

Runbot error seems not related

image

**Comment by yelizariev** [comment]
@robodoo retry

**Pull request closed without merging**
