### PR TITLE
[FIX] account, sale: internal user (no accounting permissions) cannot edit their information at /my/account

### PR DESCRIPTION
**Pull request by royle-vietnam**
Description of the issue/feature this PR addresses:

Current behavior before PR:

https://github.com/odoo/odoo/assets/43790414/81bcee85-8a36-4c63-9110-b6e8cb604532

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by royleviindoo** [comment]
Hi @vin-odoo , can you review this PR, thank

**Comment by royleviindoo** [comment]
Hi @aliyatastemirova , can you review this PR, thanks

**Comment by aliyatastemirova** [comment]
Hi @royleviindoo, could you please write a more detailed commit message: what the problem is, and what your commit fixes? Thank you :slightly_smiling_face:

**Comment by royleviindoo** [comment]
> Hi @royleviindoo, could you please write a more detailed commit message: what the problem is, and what your commit fixes? Thank you 🙂

Hi @aliyatastemirova , I have been done

**Comment by aliyatastemirova** [comment]
Thank you, I can't seem to be able to reproduce it though. Tested with an internal user without Accounting rights.

**Comment by royleviindoo** [comment]
> Thank you, I can't seem to be able to reproduce it though. Tested with an internal user without Accounting rights.

@aliyatastemirova please watch the video below, I reproduce it on runbot.odoo.com

https://github.com/odoo/odoo/assets/43790414/7ee34fe8-ca59-44a9-b561-3596fb6321a6

**Comment by aliyatastemirova** [comment]
Thanks, I reproduced it now. It seems to me that the same happens with the Sale module, could you please add a fix for that too if possible?

**Comment by royleviindoo** [comment]
> Thanks, I reproduced it now. It seems to me that the same happens with the Sale module, could you please add a fix for that too if possible?

@aliyatastemirova You were right, I fixed it. Please review again, thanks

**Review by aliyatastemirova — APPROVED** [review]

**Comment by royleviindoo** [comment]
@Feyensv @smetl Hi, can you review this PR? thanks

**Comment by royleviindoo** [comment]
Hi @xavierbol Can you review this PR, thanks

**Review by smetl — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
