### PR TITLE
[FIX] stock: avoid infinite loop in _procure_orderpoint_confirm

### PR DESCRIPTION
**Pull request by yelizariev**
In some scenarios following code infinitely tries to remove the same records and
never reach `break` statement:

```
orderpoints_batch -= failed_orderpoints
```
---

opw-2525893

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — COMMENTED** [review]
looks good but I don't understand why a loop would be happening

with your change failed_orderpoints is smaller than before

```py
orderpoints_batch.__sub__(failed_orderpoints)
```

so the only effect should be that orderpoints_batch may be bigger than before the change, which would not solve a loop

the only loop I would see is in:

```py
                except OperationalError:
                    if use_new_cursor:
                        cr.rollback()
                        continue
```

but I don't see how the fix would solve this change

**Comment by yelizariev** [comment]
@nle-odoo I didn't analyze how to reproduce the loop in runbot, but it's reproducable in customer database.

In original code the loop happens as following:
* before the while-block we have 6 elemens in ``orderpoints_batch``
* then something is added to ``orderpoints_exceptions``
* ``failed_orderpoints`` is not empty
* ``orderpoints_batch`` now has 5 elements
* now we go to next loop (``else`` block is not executed)
* in any next iteration we have ``ProcurementException`` error, but without ``orderpoints_exceptions``
* So have again not empty ``failed_orderpoints`` and  ``orderpoints_batch`` still has 5 elements

**Comment by nle-odoo** [comment]
ok it would make sense

and the fix makes sense then

but I don't see anywhere where we call `raise ProcurementException` and orderpoints_exceptions would not be filled, the code seems to expect that we should receive an error for each procurement that cause ProcurementException, I will check

**Comment by nle-odoo** [comment]
I tried with given database but can't reproduce, maybe the workaround is working and had been applied or to reproduce you need custom modules.

**Comment by amoyaux** [comment]
@yelizariev "in any next iteration we have ProcurementException error, but without orderpoints_exceptions". It should never happens. Do you have an idea from the failure?

**Comment by amoyaux** [comment]
IMO the patch is good because, the part of code with the logger is exactly design for this kind of issue. Could you add the usecase in commit message also?

**Comment by yelizariev** [comment]
I agree with @nle-odoo -- it's not reproducible anymore and probably comes from custom modules. I requested the customer for more information

**Comment by yelizariev** [comment]
No more information from the customer. I close this PR. @amoyaux you may apply the patch in master

**Pull request closed without merging**
