### PR TITLE
[ADD] pokedex: super cool Pokemon management app

### PR DESCRIPTION
**Pull request by rim-odoo**
It's 20 years now that Pokemon masters are hunting Pokemons all over the
world. We thought it would be nice to manage them directly inside Odoo.

With this version 0.1 of Odoo's Pokedex, you can:
- list all your Pokemons, with their types and evolutions
- mark Pokemons as "captured"
- have a nice "Pikachu" icon in your app switcher ;-)

(based on an original idea of @jem-odoo, @bst-odoo, @tivisse and
@rim-odoo)

capture du 2016-04-01 09-57-31
capture du 2016-04-01 09-57-54
capture du 2016-04-01 09-58-53

**All Pokemon-names, pictures, and stuff related to these games still
belong to Nintendo & their original authors.**

### CODE REVIEW

**Comment by xmo-odoo** [comment]
I'm a Master from Snowpoint City on Sinnoh, and this is unusable for me, I have no way to manage my [Mamoswine](http://bulbapedia.bulbagarden.net/wiki/Mamoswine_\(Pokémon\)) or my [Weavile](http://bulbapedia.bulbagarden.net/wiki/Weavile_\(Pokémon\)) through this, not to mention tracking the growth of my [Chingling](http://bulbapedia.bulbagarden.net/wiki/Chingling_\(Pokémon\))

**Comment by mart-e** [comment]
Could you move to odoo-extra ?

**Comment by rim-odoo** [comment]
Time to close the old April Fool's :)

**Comment by jem-odoo** [comment]
Time to make anew one !

**Comment by Yenthe666** [comment]
Oh the nostalgia 😆

**Pull request closed without merging**
