### PR TITLE
[IMP] web_editor: move odoo-editor into odoo

### PR DESCRIPTION
**Pull request by Goaman**
The code of the Odoo editor was on another repository
and that created unnecessary overhead. This commit move
the code inside Odoo and slightly change the folder
structure.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Goaman** [comment]
@odony This pr replace the odoo lib bundle with the actual code of the lib as privately discussed.

**Comment by odony** [comment]
@fw-bot ignore

**Comment by xmo-odoo** [comment]
@robodoo override=ci/security

Uses of innerHTML are sensible or innocuous (clearing elements, assigning static information, putting contents in detached elements to clean them up), or out of scope (tests, demo).

**Comment by Zinston** [comment]
@robodoo rebase-ff r+

**Review by Zynton — APPROVED** [review]

**Comment by Zinston** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
