### PR TITLE
Saas 13.5 keyboardnav browserdetect common lpe

### PR DESCRIPTION
**Pull request by kebeclibre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
robodoo rebase-ff

**Comment by kebeclibre** [comment]
@d-fence 
Hi master, can I get a pass on that one ?
you fw-ported https://github.com/odoo/odoo/pull/56318 without us having a chance to do those changes .....
cheers :D

**Comment by d-fence** [comment]
> @d-fence
> Hi master, can I get a pass on that one ?
> you fw-ported #56318 without us having a chance to do those changes .....
> cheers :D

My bad, I was trying to empty the forward-port queue.
Yes you can as it's a fix and no model change ... blah blah

**Comment by kebeclibre** [comment]
robodoo r+

**Pull request closed without merging**
