### PR TITLE
[FIX] l10n_cl: fix forward port #151657

### PR DESCRIPTION
**Pull request by Danisan**
this is to fix #151657 

Methods from l10n_cl_edi has been moved from l10n_cl_edi (enterprise) as part of https://github.com/odoo/enterprise/pull/46593. This includes
_l10n_cl_get_amounts and _float_repr_float_round on the account move model, as well as the method _l10n_cl_get_line_amounts on the account move line model. They can therefore be removed in this commit.

The VAT section for the electronic ticket document is also being transferred in the same manner, and can thus be removed in the template here.

As part of the same refactor, methods _l10n_cl_get_invoice_totals_for_report and _l10n_cl_prices_and_taxes had been deprecated, and additionally there is a new exclusive qweb totals widget for chilean invoices. This will allow showing in PDF reports, invoices that had been generated in a foreign currencies or in UF index.

X-original-commit: 7d22eaaf135e20b5c94e8419b8b6418483f1a139

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Danisan** [comment]
@fvz-odoo this replaces #151657

**Review by casp-odoo — CHANGES_REQUESTED** [review]
In a general manner, I feel like this PR is touching multiple subjects at once : fw-porting, fixing, refactoring, etc. I think this should be avoided, and at the very least those tasks should be separated in different commits. 
Since this PR will replace the one it mentions (which I saw you demanded was closed), please consider it as autonomous : don't refer to the old one and let it be understandable by itself. So, rename it and mention the PRs this should be a FW port of. 

Also, please adapt the description to the changes : for instance, here you actually add some functions you describe as "removed in this commit" ...

Overall it would be nice to make this a little more readable from an outsider's perspective.

**Comment by fvz-odoo** [comment]
Hello @Danisan other than @casp-odoo's comments, I tested it but I'm getting this error, could you please check? I get it when trying to confirm the invoice (happens both in USD and CLP).

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/tools/cache.py", line 91, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/data/build/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/data/build/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7faacd6dbeb0>, 'l10n_cl.tax_group_ila')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1748, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1775, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 1979, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 236, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 32, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 24, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/enterprise/l10n_be_reports_post_wizard/models/account_move.py", line 36, in action_post
    return super().action_post()
  File "/data/build/odoo/addons/sale/models/account_move.py", line 63, in action_post
    res = super(AccountMove, self).action_post()
  File "/data/build/enterprise/account_accountant/models/account_move.py", line 30, in action_post
    res = super().action_post()
  File "/data/build/odoo/addons/account/models/account_move.py", line 3995, in action_post
    other_moves._post(soft=False)
  File "/data/build/enterprise/l10n_cl_edi/models/account_move.py", line 149, in _post
    move._l10n_cl_create_dte()
  File "/data/build/enterprise/l10n_cl_edi/models/account_move.py", line 517, in _l10n_cl_create_dte
    'withholdings': self._l10n_cl_get_withholdings(),
  File "/data/build/odoo/addons/l10n_cl/models/account_move.py", line 270, in _l10n_cl_get_withholdings
    'tax_amount': self.currency_id.round(abs(line.balance))} for line in self.line_ids.filtered(
  File "/data/build/odoo/odoo/models.py", line 5523, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/data/build/odoo/odoo/models.py", line 5523, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/data/build/odoo/addons/l10n_cl/models/account_move.py", line 272, in <lambda>
    self.env.ref('l10n_cl.tax_group_ila').id, self.env.ref('l10n_cl.tax_group_retenciones').id])]
  File "/data/build/odoo/odoo/api.py", line 579, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "/data/build/odoo/odoo/addons/base/models/ir_model.py", line 2017, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-43>", line 2, in _xmlid_lookup
  File "/data/build/odoo/odoo/tools/cache.py", line 96, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/data/build/odoo/odoo/addons/base/models/ir_model.py", line 2010, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: l10n_cl.tax_group_ila

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://60219354-saas-16-2-all.runbot211.odoo.com/web/assets/2274-b8b803f/web.assets_backend.min.js:986:163)
    at XMLHttpRequest.<anonymous> (https://60219354-saas-16-2-all.runbot211.odoo.com/web/assets/2274-b8b803f/web.assets_backend.min.js:994:13)

Thanks

Fernando

**Comment by Danisan** [comment]
closed because it was retagged to saas-16.4

**Pull request closed without merging**
