### PR TITLE
[FIX] stock: return packages

### PR DESCRIPTION
**Pull request by adwid**
Backport of ca168f7fbcbb8a300a8fa0b46f79a6c116b5aa93
opw-3390615

### CODE REVIEW

**Comment by adwid** [comment]
fw-bot up to saas-15.2

**Comment by HANNICHE-Walid** [comment]
> fw-bot up to saas-15.2

@adwid can you undo this please it's not letting me

**Review by BernatPForgeFlow — APPROVED** [review]
LGTM! Functional and code review!

@adwid Could you backport this to v14?

**Comment by Whenrow** [comment]
robodoo r+

**Comment by ticodoo** [comment]
@fw-bot up to master

**Pull request closed without merging**
