### PR TITLE
[FIX] base_automation: error not correctly show

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
If an error append during an automation made by a standard user, the error is not correctly show. (A standard user have no access to read base.automation).

**Current behavior before PR:**
image

**Desired behavior after PR is merged:**
image

@rco-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW #2726321

**Review by ryihan — APPROVED** [review]

**Comment by fmdl** [comment]
cc @nle-odoo

**Review by rco-odoo — APPROVED** [review]
It looks correct to me.
I don't think it would leak any sensitive data.

**Review by nle-odoo — APPROVED** [review]
ok for me too, read access right was removed in https://github.com/odoo/odoo/commit/de4213b771f641cbc218ebb1f759b09e064100bf

but server actions name (from which base.automation().name is a delegated field) are already shown in contextual action for example

robodoo r+

**Comment by nle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
