### PR TITLE
set default activity_type_id from activity view

### PR DESCRIPTION
**Pull request by msh-odoo**
PURPOSE

When creating scheduled activity from activity cell do not set default activity type, to produce this issue:
CRM -> Activity View -> Click on existing record of activity view which will open popover -> click on Schedule Activity button, this will open scheduled activity form but it will not have default activity type.

SPEC
When clicking on the Schedule Activity button from the activity popover, the default activity type will be passed in context.

TASK 2568793

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by SimonGenin** [comment]
@msh-odoo I'd like to retarget v14 for the fix, to avoid messing up with older users' habits. 
Also, could you check if it is strictly necessary to create the ActivityCell extension point ? Couldn't we just put this logic directly inside KanbanActivity ? (Maybe not, but it's worth a look).

**Comment by msh-odoo** [comment]
@SimonGenin Target changed to 14.0 and fix is also adapted in 14.0

**Comment by SimonGenin** [comment]
@msh-odoo What about my question about the KanbanActivity ?

**Comment by msh-odoo** [comment]
@SimonGenin Well, KanbanActivity is used in kanban view and the code we added here specifically useful incase of Activity view, so I don't think it should be moved to KanbanActivity.

**Pull request closed without merging**
