### PR TITLE
only run postinstall tests for updated modules

### LINKED ISSUE #9768: 9.0 unittests decorated with postinstall are run even if the module was not updated
case at hand:

I have a module for a customer which changes the ACL for sale.order. It also has some unittests.

if I run `odoo.py -i customer_module --stop-after-init && odoo.py -u customer_module --test-enable --stop-after-init` the tests of sale which are decorated with postinstall are run too, even if the sale module is not updated. And of course they fail which breaks my CI.

### PR DESCRIPTION
**Pull request by gurneyalex**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

closes #9768

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by gurneyalex** [comment]
@odony shall I close #9773?

**Comment by odony** [comment]
@gurneyalex sure, the fix will be automatically forward-ported to 9.0.

Also in this case, you might want to use `= ANY(%s)` with `mods` being a list, that way you won't risk any issue in case `mods` is empty.

**Comment by pedrobaeza** [comment]
@gurneyalex, are you going to change this with `ANY` or the OCB version?

**Comment by gurneyalex** [comment]
@pedrobaeza I just did.

**Comment by mart-e** [comment]
With your patch, you won't be running any post-install tests when installing a new module (`-i lunch --test-enable`). Wouldn't `processed_modules` be more appropriate than `mods`?

**Comment by gurneyalex** [comment]
@mart-e I may be wrong but this list seems to include modules to remove. Can it be a problem? If not, I'll be happy to change.

**Comment by mart-e** [comment]
@gurneyalex right but that shouldn't be an issue as we already filter these out with the `WHERE state='installed'` clause

**Comment by gurneyalex** [comment]
@mart-e updated

**Comment by mart-e** [comment]
Thanks, merged at cc60504

**Pull request closed without merging**
