### PR TITLE
[FIX] website: wait for steps to be effective in social media test

### PR DESCRIPTION
**Pull request by bso-odoo**
Could not actually reproduce problem locally.

Looking at the logs, the randomly failing tests seem to be related to
the effects of some previous steps not having been applied even though
the test did proceed further.

This commit introduces intermediary checks to make sure that the effect
of each step is fully applied before proceeding to the next one.

runbot-3171
runbot-3172
runbot-3629
runbot-3630
runbot-3778
runbot-3779
runbot-3859
runbot-3860

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bso-odoo** [comment]
@rdeodoo This is the PR about the randomly failing social media test tour. I just added a bunch of check steps to make sure the next action is not done before the previous step is fully completed.

**Comment by bso-odoo** [comment]
@rdeodoo FYI - Launched 3 multi-builds of 10 instances, all green.

**Review by rdeodoo — APPROVED** [review]
Thanks, seems to be fixing the race conditions, ran the test ~30 times in local without any fail, while it failed ~50% of the time before your fix :+1: 

There is probably some overkill parts but nothing wrong or incorrect in itself, so LGTM.

Also missing from commit message:
runbot-3778
runbot-3779
runbot-3859
runbot-3860

**Comment by rdeodoo** [comment]
@robodoo r+

**Comment by d-fence** [comment]
nice

**Pull request closed without merging**
