### PR TITLE
CLA and spelling fix of builded to built

### PR DESCRIPTION
**Pull request by lathama**
Description of the issue/feature this PR addresses: Spelling Correction and CLA

Current behavior before PR: CLA absent and builded spelling

Desired behavior after PR is merged: CLA present and built spelled correctly

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lathama** [comment]
I went for a grand tour with our friends "find", "xargs", and "aspell" and had some fun.  How should I handle the following?
`
~/git/odoo$ git status | grep modi | wc -l
202
`
202 files with spelling corrections and a surprising amount of them related to user output.

An example for context
`
-    parent_right = fields.Integer('Parent Rigth', index=True)
+    parent_right = fields.Integer('Parent Right', index=True)
`

**Comment by lathama** [comment]
This is good to commit. I am going to do the rest of the spelling and grammar patches via new PRs that limit scope as a drive by of 200+ file changes is too much for one PR.

**Comment by mart-e** [comment]
Thanks, merged at cd5f61df6d16ed377191bf43ec65ca1b01b8f034

**Comment by lathama** [comment]
I guess I don't understand. Why was this merged to 11 instead of Master? I am happy to change my process but read that things like spelling should go to master.

**Pull request closed without merging**
