### PR TITLE
[IMP] mail, *: convert all compute/sort method into inline field function

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2985304

Enterprise: https://github.com/odoo/enterprise/pull/31552

### CODE REVIEW

**Comment by oomsveta** [comment]
You may want to remove support for not inlined compute/sort functions now that the codebase has been cleared of them.

**Comment by alexkuhn** [comment]
> You may want to remove support for not inlined compute/sort functions now that the codebase has been cleared of them.

Done!

**Comment by seb-odoo** [comment]
@robodoo override=ci/security

Code move but Markup is unchanged. Values are coming from sanitized fields in python.

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
