### PR TITLE
[FIX] base: description of write methode for x2x field

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
Of course it is possible to use on One2many field :-)

@odony @nim-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@Yenthe666

**Comment by mart-e** [comment]
@rco-odoo do you recall why we wrote that? It seems that even in old-api style, there operations were implemented
https://github.com/odoo/odoo/blob/7.0/openerp/osv/fields.py#L561

**Comment by fmdl** [comment]
@rco-odoo do you remember ? :-)

**Comment by fmdl** [comment]
ping @rco-odoo

**Comment by fmdl** [comment]
ping @rco-odoo

**Comment by fmdl** [comment]
@rco-odoo it is retarget in 12.0.

**Comment by mart-e** [comment]
Thanks !
@robodoo r+

**Comment by mart-e** [comment]
robodoo retry

**Pull request closed without merging**
