### PR TITLE
[IMP] http_routing: make the 404 image use theme color

### PR DESCRIPTION
**Pull request by rdeodoo**
With this commit, the 404 image is now using the theme color.
Not only it will be displayed in the secondary color, but it will also gets
updated when the theme color is changed.

This one was waiting for the new editor to handle inline svg as regular img
(task-2497786) but in the meantime, the website is now capable of doing that
another way, as does in this commit.

task-2659182

### CODE REVIEW

**Comment by rdeodoo** [comment]
@JKE-be @qsm-odoo If that's something we want.. I think it is cool :+1: 
Maybe color-1 tho..

**Comment by JKE-be** [comment]
image

**Review by JKE-be — APPROVED** [review]

**Comment by JKE-be** [comment]
-WAITNEDEDITOR => -WAITNEWEDITOR
Please follow guideline and end your branch name with your trigram ;)

**Comment by JKE-be** [comment]
Please don't open a new one, to keep the discuss.

**Comment by JKE-be** [comment]
Please don't forget to create a task a link it ;)

**Comment by JKE-be** [comment]
Please don't forget to move the new task in green when you push your pr

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by rdeodoo** [comment]
@JKE-be Everything is gonna be alright, thanks for r+

**Pull request closed without merging**
