### PR TITLE
[FIX] Spanish certificate not been submitted

### PR DESCRIPTION
**Pull request by ghost**
Description of the issue/feature this PR addresses: Fix the error None field by checking the certificates field

Current behavior before PR: Using an spanish certificate in res.company (field -> l10n_es_edi_facturae_certificate_id) returns error none field. When trying to save the changes you get the error:
RPC_ERROR Odoo Server Error Traceback (most recent call last): File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1765, in _serve_db return service_model.retrying(self._serve_ir_http, self.env) File "/home/odoo/src/odoo/17.0/odoo/service/model.py", line 133, in retrying result = func() File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1792, in _serve_ir_http response = self.dispatcher.dispatch(rule.endpoint, args) File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1996, in dispatch result = self.request.registry['ir.http']._dispatch(endpoint) File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_http.py", line 222, in _dispatch result = endpoint(**request.params) File "/home/odoo/src/odoo/17.0/odoo/http.py", line 722, in route_wrapper result = endpoint(self, *args, **params_ok) File "/home/odoo/src/odoo/17.0/addons/web/controllers/dataset.py", line 24, in call_kw return self._call_kw(model, method, args, kwargs) File "/home/odoo/src/odoo/17.0/addons/web/controllers/dataset.py", line 20, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/home/odoo/src/odoo/17.0/odoo/api.py", line 468, in call_kw result = _call_kw_multi(method, model, args, kwargs) File "/home/odoo/src/odoo/17.0/odoo/api.py", line 453, in _call_kw_multi result = method(recs, *args, **kwargs) File "/home/odoo/src/odoo/17.0/addons/web/models/models.py", line 73, in web_save self = self.create(vals) File "", line 2, in create File "/home/odoo/src/odoo/17.0/odoo/api.py", line 414, in _model_create_multi return create(self, [arg]) File "/home/odoo/src/odoo/17.0/addons/l10n_es_edi_facturae/models/l10n_es_edi_facturae_certificate.py", line 54, in create if fields.datetime.now() > certif.not_valid_after: AttributeError: 'NoneType' object has no attribute 'not_valid_after'

Desired behavior after PR is merged: Save the certificate.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by FlorianGilbert — CHANGES_REQUESTED** [review]
Hello

Could you please divide your diff into 2 commits, one for the CLA (the first one) and another one for your change. 
Could you please explain in the second commit the bug, how to reproduce it and how do we fix it. 
And could you please follow the [guidelines](https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html) for your commit.

In the same time, @aboo-odoo could I ask you to take a look at this (or I can ping security if you prefer)? I would like a security opinion on this. 

Thank you

**Comment by avaltierrab** [comment]
Hi Florian, I have already did the changes, if you need any more information tell me.
I can´t give the actual certificate and the key pass since it's confidential.
I could ask for permission on making a video highliting the bug.

**Comment by aboo-odoo** [comment]
Hey @avaltierrab ! 

Before going any further with the change, could you make sure your PKCS12 file has been generated correctly (a private key and the certificate that match to your private key).

Indeed, when reading the documentation of `pkcs12.load_key_and_certificates` ([link](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.pkcs12.load_key_and_certificates)), it states that it returns a tuple of (private_key, certificate, additional_certificates) where private_key is a private key type or None, certificate is either **the Certificate whose public key matches the private key in the PKCS 12 object** or None, and additional_certificates is a list of all other Certificate instances in the PKCS12 object. 

Since certificate is None in your case, it makes us think the certificate you get from the additional certificates does not match the private key returned which will pose an issue when generating the XML signature.

**Comment by FlorianGilbert** [comment]
Hello, no change since @aboo-odoo's review. I'm closing the PR, feel free to reopen it if needed.

**Pull request closed without merging**
