### PR TITLE
[IMP] hr_skills: Add demo data for all employees

### PR DESCRIPTION
**Pull request by LucasLefevre**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo rebase-ff r+

**Comment by xmo-odoo** [comment]
@tivisse could be more readable / shorter to use a CSV for the skills instead of a giant pile of XML

**Comment by tivisse** [comment]
@robodoo r-

**Comment by tivisse** [comment]
@robodoo r/

**Comment by tivisse** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo r\

**Pull request closed without merging**
