### PR TITLE
12.0 impperf progressbar dle

### PR DESCRIPTION
**Pull request by beledouxdenis**
[IMP] web: read_progress_bar, use read group when possible for performance
[IMP] mail: overide activity state progress bar to use custom sql for performance

### CODE REVIEW

**Comment by beledouxdenis** [comment]
@robodoo rebase-ff

**Comment by seb-odoo** [comment]
robodoo failed here?

**Comment by beledouxdenis** [comment]
I didn't put the r + yet, because some additional review has to be done, so no robodo didnt fail

**Comment by nilshamerlinck** [comment]
I believe this improvement would be very useful for the case that @lse-odoo took as an example in his talk here: https://youtu.be/IUyQjwnrpzM?t=782 (`read_progress_bar` taking 20s to load because of 150k leads) 

cc @beledouxdenis or will https://github.com/odoo/odoo/pull/41421 take over?

**Comment by beledouxdenis** [comment]
Given my current workload in the upgrade team, I won't be able to finalize this.

To me, the Python Framework (cc @rco-odoo) team should continue the work suggested here, especially by the fact the code can be shortened by factoring `read_group` a bite more (it's already well factored in multiple sub-methods, but in memory, it could be factored even more to shorten this code)

**Comment by yelizariev** [comment]
https://github.com/odoo/odoo/pull/67004

**Comment by yelizariev** [comment]
Could be closed. It's done here: https://github.com/odoo/odoo/pull/67004

**Pull request closed without merging**
