### PR TITLE
[FIX] web: time dependant tests

### PR DESCRIPTION
**Pull request by jpp-odoo**
[FIX] web: invalid datetime range/domain in mockReadGroup

The mock server's mockReadGroup function would not properly compute the
range and domain of the returned groups for datetime fields with groupby
hour.
The year of the range/domain should be the same as the record.

Consider the following:
- a record with a datetime field of value "2016-12-14 12:34:56".
- a read_group with groupby "['datetime:hour']"

The corresponding group would have had the following metadata:
- value: `"13:00 14 Dec"`
- domain: `[["datetime", ">=", "2022-12-14 12:00:00"], ["datetime", "<", "2022-12-14 13:00:00"]]`
- range: `{ from: "2022-12-14 12:00:00", to: "2022-12-14 13:00:00" }`

It now has the following valid metadata:
- value: `"13:00 14 Dec"`
- domain: `[["datetime", ">=", "2016-12-14 12:00:00"], ["datetime", "<", "2016-12-14 13:00:00"]]`
- range: `{ from: "2016-12-14 12:00:00", to: "2016-12-14 13:00:00" }`

Co-authored-by: Bruno Boi <boi@odoo.com>

----------------------------

[FIX] spreadsheet: time dependant test

Before this commit, the test "field matching is removed when filter is
deleted" failed on 2022 to 2033 year's transition.

Now a patch date is added to avoid the test to be time dependent.

### CODE REVIEW

**Comment by jpp-odoo** [comment]
Hello @rrahir , 
On d970869599a4d971930238cc20e07f342035091d one test of spreadsheet was skiped because was time dependent. I allowed myself to add a patchDate to fix this.
Are you ok with this fix ?

**Review by LucasLefevre — APPROVED** [review]
ok for the spreadsheet fix
Thanks :)

**Review by brboi — APPROVED** [review]
First commit is OK.
It just miss a small thing in the commit message, such as:
`would have had the following metadata (considering current year is 2022)`

**Comment by brboi** [comment]
robodoo r+ method=rebase-ff

**Pull request closed without merging**
