### PR TITLE
[IMP] l10n_cr: standardize state's code

### PR DESCRIPTION
**Pull request by randall-vx**
Description of the issue/feature this PR addresses:

* Standardize state's code for Costa Rica digital invoices.

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rcastro-tyc** [comment]
@mart-e Hi Mr. Martin ! Can you help me checking this PR ?

Regards,

**Comment by mart-e** [comment]
Hi!

Please do not change the external id of records in a stable version.

**Comment by rcastro-tyc** [comment]
@mart-e Hi ! 

It has been fixed !

**Comment by mart-e** [comment]
Thanks for  the changes. Could you explain why it needs to be numbers instead of letters for province code?
For instance, I see references to the iso code but not the number.
https://en.wikipedia.org/wiki/Administrative_divisions_of_Costa_Rica#Provincial_organization

**Comment by rcastro-tyc** [comment]
@mart-e To be used in a new legislation accord to make electronic invoices.
[Codificacionubicacion_V4.2.pdf](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjzh9SIhoDZAhVOdt8KHUMNC7gQFggpMAA&url=https%3A%2F%2Ftribunet.hacienda.go.cr%2Ftribunet%2Fdocs%2Fesquemas%2F2016%2Fv4.2%2FCodificacionubicacion_V4.2.pdf&usg=AOvVaw3ZgD2HvMTDzlJbQjBkdlCO)

**Comment by rcastro-tyc** [comment]
@mart-e I'm gonna make an addon to set a number in Costa Rica states.

Regards,

**Pull request closed without merging**
