### PR TITLE
fix Lucida font name in translation files

### PR DESCRIPTION
**Pull request by gurneyalex**
https://github.com/odoo/odoo/pull/9997 fixed the code string
but not the translation files.

Done with `for f in $(ack -l Lucica) ; do sed -i s/Lucica/Lucida/g $f ; done`

### CODE REVIEW

**Comment by gurneyalex** [comment]
@xmo-odoo @mart-e your help is welcome on this. I expect a transifex sync is required once this is merged.

**Comment by mart-e** [comment]
Thanks for the patch. Revision d8e5cdec7d5f4192fd48c2a74d0ce19cb051f1f9 actually changed the content of some translation parts so indeed another fix is required.
The issue we have is that, if we only change the .pot, we loose all, already translated parts of these views (which kind of sucks), so the proper way would be to.

1. [fetch](https://github.com/mart-e/odoo-scripts/blob/master/transifex/pull-translations.py) the latest translations from Transifex
2. make the changes with your `sed` command
3. push the sources and updated translations to Transifex

Hoping nobody makes a translation between step 1 and 3 that would get lost.

**Comment by gurneyalex** [comment]
@mart-e thanks for your hard work on the translation of Odoo.

**Comment by pedrobaeza** [comment]
The steps you mention seems correct, so :+1:

**Comment by mart-e** [comment]
Taking advantage of the snowing morning for a quick push while nobody is here, merged at 67ab5b776c8cf6eea2e2b95226e915284f47995b

This isn't ideal as we lose the history on the Transifex terms, so hopefully we won't need to do it too often.

**Comment by gurneyalex** [comment]
helpful :snowflake:

**Pull request closed without merging**
