### PR TITLE
[REM] sale: unused use_quotations field

### PR DESCRIPTION
**Pull request by Abridbus**
task-1962182 introduce the field back in 12.5
but did not added any logic with it.

The tooltip suggested the need for it tho:
"Check this box if you send quotations to your customers
  rather than confirming orders straight away."

related to 0d2be38333d8fe5a4cbef4161ac92cac00e47eb1 
opw-3198202

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
I think it was used in some dashboards ... overengineered stuff back those days, said it was unnecessary, and it was. As far as I remember, it came with the "use leads", "use opportunities", ... booleans allowing to tune the dashboard display.

You can remove safely that kind of noise :) . Don't forget to link the upgrade PR .

**Comment by tde-banana-odoo** [comment]
r+ ?

**Comment by Feyensv** [comment]
@robodoo r+ (upgrade still needs validation anyway)

**Comment by Feyensv** [comment]
@robodoo delegate+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
