### PR TITLE
[FIX] account: public user cannot access product with tag

### PR DESCRIPTION
**Pull request by agr-odoo**
Install module l10n_eu_oss_reports and website_sale 
Edit a product (i.e. Acoustic Bloc Screens)
In Accounting tab add an account tag
Try to access the product in webshop as public user

User receive an error message

403: Forbidden
The page you were looking for could not be authorized.

Error message:
You are not allowed to access 'Account Tag' (account.account.tag) records. [...]

This occurs because during tax computation the system try to access account tags but they cannot be read by the public user

opw-3455325

### CODE REVIEW

**Comment by rugo-odoo** [comment]
Why do we need to access account_tag on that view ? I have the feeling that we probably shouldn't and that is the real problem behind this bug.

Even if it is not, this solution is too permissive. We don't want to give that much access. We should find a way to restrain it more.

**Comment by agr-odoo** [comment]
@rugo-odoo 
Thanks for checking, we access product tags during tax computation, the alternative to give read perms is a well placed `sudo`

**Comment by rugo-odoo** [comment]
LGTM (cc @smetl)

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
