### PR TITLE
[CLA] Updating CLA initos.md

### PR DESCRIPTION
**Pull request by OSevangelist**
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Sure !
@robodoo r+
It will be ported to upper versions soon, don't forget to rebase your branches after the merge if you have some waiting.
Merry christmas to you too :santa:

**Comment by OSevangelist** [comment]
Thanks @mart-e but why is this closes w/o merge now? Anything wrong with that ?

**Comment by OSevangelist** [comment]
Sorry ma bad. It was merged before it got closed. So all fine @mart-e and thanks for your personal effort. I owe you a beer for unnecessary mail next year ;-)

**Comment by mart-e** [comment]
@OSevangelist that sounds like a good deal to me ! :beers:

**Pull request closed without merging**
