### PR TITLE
8.0 scheduler error handling

### LINKED ISSUE #6993: Stock minimum rules scheduler not tolerant to failing rules
At least in 8.0, if a problem is encountered during reordering rule processing in the scheduler, the Exception is not caught and interrupts the entire scheduler and leaks the cursor.

Steps to reproduce:
- set up a BoM with a line with an incorrect UoM
- set up a reordering rule for the product
- run the scheduler

### PR DESCRIPTION
**Pull request by mistotebe**
Fixes #6993 and related issues.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
@odony any news on this one?

**Comment by spadae22** [comment]
@StefanRijnhart @odony Yes please, this would explain when "running" procurements (from SO) that do not generate a MO. They should be in exception, but we do see this issue. Please merge

**Comment by Yenthe666** [comment]
@mart-e I summon you! Can you look at this please?

**Comment by Yenthe666** [comment]
Hi @mistotebe ,

Thank you for your PR and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new PR.

Regards,
Yenthe

**Pull request closed without merging**
