### PR TITLE
[IMP] auth_signup: reword welcome message

### PR DESCRIPTION
**Pull request by JKE-be**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo delegate jubodoo

**Comment by jubodoo** [comment]
robodoo r+

**Comment by JKE-be** [comment]
robodoo delegate+ @jubodoo

**Comment by JKE-be** [comment]
robodoo delegate=jubodoo

**Comment by JKE-be** [comment]
Apres je n'ai plus d'autres idées ;)

**Comment by jubodoo** [comment]
@robodoo r+

**Pull request closed without merging**
