### PR TITLE
[PERF] stoc: only one line is enought to raise

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
Create Uom
Create billion and billion of stock.move.line

Try to change the factor of uom, you need to wait before the raise.

Fine tuning of https://github.com/odoo/odoo/commit/d44a4df8638a3f627d15caa5793f72dc9c0a5cdc
@wtaferner 
@KangOl 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is `search_count`, not search, so there's no sense for the `limit=1` argument.

**Comment by fmdl** [comment]
yes I know, with limit=1, it reduce the SQL compute (don't need to count the number of line), no ?

**Comment by pedrobaeza** [comment]
AFAIK, the time is the same for both.

**Comment by moylop260** [comment]
Use just search with limit=1 instead of search_count.
Since that the code is using a boolean result if return a record then it will truely

**Comment by wtaferner** [comment]
Hmm, I did just a "dirty" fix of a missed `Many2one` and therefore wrong comparison in https://github.com/odoo/odoo/pull/25664.

About the discussion...not sure about your comments @moylop260 on the original commit as it is only checking certain changed values on location and uom which is for sure not million of records normally, so no big deal to detect the differences IMO in the first part of the check.

For the search and search count it could indeed maybe of advantage to get a limited search result instead of counting the result records. I guess we need some figures and comparisons...

I guess @KangOl will have the final call to maybe change this in case this for sure costly computation by nature could be improved with your suggestions, but luckily we do not change these records and fields very often but if we do we should be stopped doing so :smile:

**Comment by moylop260** [comment]
@fmdl 
Could you add a reference of PR or commit where this issue was fixed to close it?

**Comment by moylop260** [comment]
In fact, I saw the same code for the latest sha:

https://github.com/odoo/odoo/blob/9903e7ae30927cdfe7e2d2df5d55fa8d4f02dfd5/addons/stock/models/product.py#L591-L601

What is the reason to close it?

**Comment by fmdl** [comment]
https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L3777

**Comment by moylop260** [comment]
@fmdl 
What about “search(domain, limit=1)”?
Since that you are using the result like a boolean.

It is faster than search_count.

Could you check my comments from: https://github.com/odoo/odoo/commit/d44a4df8638a3f627d15caa5793f72dc9c0a5cdc?

I mean, the patch of this PR is wrong but the issue performance is valid.

**Pull request closed without merging**
