### PR TITLE
[FIX] mass_mailing: fix template compressed mode

### PR DESCRIPTION
**Pull request by Mtaylorr**
related commit: [1]

Issue:
======
mass_mailing view is covered by the snippet sidebar

Steps to reproduce the issue:
=============================
- Create a new mass mailing with any template except the basic
- Save it
- Go back
- Enter again to the mailing
- The sidebar covers a part of the editable area

Spec:
=====
This is an application of the mentioned commit in the case when we don't have to select a new theme.

opw-4227663

[1]: https://github.com/odoo/odoo/commit/3aa9a36ed47d0446e51c8dc991d0f7f6f2bacc80

### CODE REVIEW

**Comment by Mtaylorr** [comment]
@abd-msyukyu-odoo can you take a look at this ? thanks

**Comment by Mtaylorr** [comment]
@odoo/rd-sm-customer can you take a look at this ?

**Comment by abd-msyukyu-odoo** [comment]
@Mtaylorr Hello, I'll check this tomorrow, I have a bunch of other tasks trying to handle the same kind of issue, and I'll decide what is the better approach among all of them :)

Thanks for the notification!

**Comment by Mtaylorr** [comment]
@abd-msyukyu-odoo do you have any news about this ? thanks

**Comment by abd-msyukyu-odoo** [comment]
@Mtaylorr Hello! Yes, I've made a PR with multiple fixes including this issue, I'll keep you updated when I send it :) I'll let you know if you should close this one or not when I'm finished with the full testing :)

**Comment by Mtaylorr** [comment]
Solved by https://github.com/odoo/odoo/pull/187134

**Pull request closed without merging**
