### PR TITLE
[REF] web_editor: remove the use of proxies for data-apply-to

### PR DESCRIPTION
**Pull request by sdegueldre**
The data-apply-to attribute allows snippet options to target multiple
sub-elements of a snippet with an option method (eg select-class). When
it was first implemented, a proxy of the current snippet option was
created where the $target property was masked by each sub-element, this
was initially done because the option methods can be asynchronous, and
simply replacing the option's $target by the sub-target for the method's
time of execution and restoring it after meant that any asynchronous
work would potentially have the wrong $target, and result in a problem
similar to _super in the odoo class system (where we need to cache it if
we want to use it in any asynchronous work)

But it turns out that since we execute all snippet option methods inside
of a mutex, they cannot run concurrently and cobble each other's
$target, and so simply replacing the $target before and restoring it
after the method call actually works just fine, and we do not need the
added complexity of using proxies.

This commit thus removes the use of proxies for that use-case as it
makes the code unnecessarily more complicated.

### CODE REVIEW

**Comment by sdegueldre** [comment]
@qsm-odoo Here's the PR. The thing I did not consider previously is that currently, we are using `Array.prototype.map` for `updateUI` and `updateUIVisibility`, which allows them to run in parallel. With this change I've had to make those into iterative for loops. While we probably don't want to allow snippet option methods to run in parallel, so that apply-to behaves as close as possible to a regular option method call, updating the UI shouldn't modify the DOM and as such should be able to run concurrently. On the other hand, there probably shouldn't be any actual async work done in `updateUI` and `updateUIVisibility` so in reality there is probably no benefit to letting them run in parallel anyway. Just something to think about.

In the end, using proxies is slightly more robust in async scenarios, but there is currently no hard requirement for it. I'll let you decide which is preferable.

**Comment by qsm-odoo** [comment]
Mmh, actually we do have `rpc` being made in `computeWidgetState` so making them run in parallel could be good performance-wise... but we should probably avoid rpc being made in there anyway... I'll think about it.

**Comment by sdegueldre** [comment]
@qsm-odoo should we close this? Really not a major code quality issue. We can revisit this if people ever run into weird issues because of the proxies.

**Comment by qsm-odoo** [comment]
Will consider reopening if ever necessary :+1:

**Pull request closed without merging**
