### PR TITLE
[FIX] base: use non-breaking spaces for thousand separators

### PR DESCRIPTION
**Pull request by tdecaluwe**
Avoid line breaks in monetary amounts.

Steps to reproduce:
* Either set the language to Swedish or enter dev mode and set the thousands separator to a space
* Refresh the client
* Create a purchase order
* Create an order line, with taxes (important) for a total amount over a thousand
* The total amount will now be broken up into two lines

opw-3482329

### CODE REVIEW

**Review by Julien00859 — COMMENTED** [review]
Shouldn't the thousand separator be replaced in the xml master data instead?

**Comment by tdecaluwe** [comment]
@Julien00859 Maybe, to me both seem acceptable. What is your preference? Possibly both? Updating the xml master data should be accompanied by an upgrade script though.

**Comment by Julien00859** [comment]
master data in all versions
.replace only in versions that are deployed on the saas (so that users benefit from the fix without updating base)

**Review by Julien00859 — APPROVED** [review]
what do you think @lordkrandel ?

**Comment by lordkrandel** [comment]
There definitely is some literature favoring it:
https://wikis.ec.europa.eu/display/WEBGUIDE/07.+Dates%2C+numbers+and+symbols
image

I don't see it as a problem unless we parse back our own amounts somewhere with a regex like `[\d ,.]` that would break.

**Comment by lordkrandel** [comment]
Someone also tells me that you can also use CSS for that with `white-space: nowrap` on the field.

**Review by lordkrandel — APPROVED** [review]

**Comment by Julien00859** [comment]
please remember to remove that .replace in master please :)
@robodoo r+

**Comment by Julien00859** [comment]
revert! https://github.com/odoo/odoo/issues/137221

**Comment by Julien00859** [comment]
actual error:

```
  File "odoo/addons/base/models/ir_http.py", line 240, in get_translations_for_webclient
    "thousands_sep": langs.thousands_sep.replace(' ', '\xa0'),
AttributeError: 'bool' object has no attribute 'replace'
```

**Comment by lordkrandel** [comment]
We probably didn't consider the case where the `thousands_sep` is not there.

**Pull request closed without merging**
