### PR TITLE
add kanban_attachment_image for kanban view

### PR DESCRIPTION
**Pull request by msh-odoo**
PURPOSE
Clicking on kanban cover image do not open kanban record, clicking on cover image should open record.

SPEC
Clicking on kanban cover image should open record.

TASK 2524022

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by SimonGenin** [comment]
@robodoo r+

**Comment by SimonGenin** [comment]
@msh-odoo Can you update the commit name / message ? It will by the same occasion fix the blocked CI.

**Comment by msh-odoo** [comment]
@SimonGenin I improved commit message, Thanks.

**Comment by SimonGenin** [comment]
@robodoo r+

**Pull request closed without merging**
