### PR TITLE
[FIX] hr_holidays: fix leaves types order

### PR DESCRIPTION
**Pull request by jvnm-dev**
In the leaves app, you can create an allocation request where you can
select a leave type using a m2o field.

Before this commit:

    - The leaves type order is not correct when you have a lot of them.

After this commit:

    - The leaves type order is correct.

Odony's comment: Leave types are reordered after each search(), based on
some context-dependent, non-stored conditions. The problem is that the
initial search() applies the given *limit*, so the "post-sort" will only
sort a limited number of random result from the initial search,
rather than all types matching the domain.

If you have more than 7 leaves types matching the domain, you have a
chance that the m2o auto-completion on the leave request form will not
suggest the correct leave types, because the post-sort will not even
receive them. So you may not see a leave type for which you have
remaining leaves!

Co-authored-by: odony <odo@odoo.com>

OPW-2089593

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jasonvanmalder** [comment]
fw-bot up to saas-12.3

**Comment by jasonvanmalder** [comment]
@jpp-odoo

**Comment by jpp-odoo** [comment]
@nim-odoo The code seems fine, but I'm not sure if this is worthy to be done in 12. The workaround is very simple, click in see more to see the all list of leaves types. What do you think ?

**Comment by jasonvanmalder** [comment]
@nim-odoo I didn't discuss about that with odo but I noticed that his fix put the leaves with 0 remaining on the top of the list. This only happens on v12 (in v13 they are not displayed). So I saw apr and she explained to me the right order to have and apparently, the leaves with 0 remaining should be displayed but at the end of the list

**Pull request closed without merging**
