### PR TITLE
[FIX] models: make read_group() call name_get() on demand only

### PR DESCRIPTION
**Pull request by rco-odoo**
This improves the performance of code using read_group() without actually using
the display names of the result.  It also optimizes name_search().

### CODE REVIEW

**Comment by odony** [comment]
Note: this is an improved version of proposition #23755

**Comment by ypapouin** [comment]
Asking here since I have an issue in 12.0 with `read_group`  and lazy `name_get` across RPC. Is there a way to force lazy resolution somewhere ?

Because `execute` from `odoo/service/model.py` run its method with an enter/exit cursor but then, `RPC._xmlrpc` call `xmlrpc.client.dumps` that try to convert method result to XML_RPC data compliant. 
So an exception is raised when trying to resolve lazy fields value since cursor is already closed:
`psycopg2.OperationalError: Unable to use a closed cursor`.

**Comment by ypapouin** [comment]
Sorry for the buzz, it was fixed in https://github.com/odoo/odoo/commit/ac78a9fab9109f63bcdc149556e1010cdcb6e417

**Comment by vladnfr** [comment]
Hi @rco-odoo, great improvement this one! Can it also be used in v11.0?

**Pull request merged**
