### PR TITLE
[Fix]  No attribute 'NumberConverter'

### PR DESCRIPTION
**Pull request by Medaillek**
On server starting, following error :
odoo.modules.module: module 'werkzeug.routing' has no attribute 'NumberConverter'

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
1. cla is missing
2. since this now extends `IntegerConverter`, `num_convert` is not necessary anymore (as that's the same value as `IntegerConverter.num_convert`

Do you mind if I update the commit message? I'd like to better match our normal message format, and link to pallets/werkzeug@88125beebc6463e571cef3ca84eccfad0c818ae3 by way of explanation, rather than a less-than-clear partial error message.

**Comment by Medaillek** [comment]
I had created a cla file but it obviously did not create.
And I didn't understand the end of the message.

**Comment by xmo-odoo** [comment]
The part of the commit message?

I just mean I think mentioning werkzeug's API change and linking to the corresponding commit message would be much clearer an explanation than just providing an error message which doesn't really say much. But I can do that myself if you don't mind me updating the commit.

**Comment by Medaillek** [comment]
Yes you can

**Review by Julien00859 — APPROVED** [review]
LGTM

Missing CLA thought, also (nitpicking) the colon after `[FIX] base`

**Comment by Julien00859** [comment]
cc @tsm-odoo at one moment we had some converters for websocket too, can you confirm me we don't use them anymore since we greatly simplified the `ir.websocket` model?

**Comment by MiquelRForgeFlow** [comment]
FYI cla is in https://github.com/odoo/odoo/pull/98291

**Comment by tsm-odoo** [comment]
@Julien00859 Indeed, no routes, no converters :+1:

**Pull request closed without merging**
