### PR TITLE
[12.0][FIX] core: ability to run tours in Chrome 111

### PR DESCRIPTION
**Pull request by marcelsavegnago**
ref. https://github.com/odoo/odoo/pull/114930

ping @xmo-odoo

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Odoo is not accepting patches in these old branches. You should propose it to OCB and use that soft fork.

**Comment by rvalyi** [comment]
@pedrobaeza this a bit of a serious issue for us in the OCA, because some tests are broken in the CI for odoo/odoo. It means even if we patch OCA/OCB some tour tests for odoo/odoo will keep failing and cripple some repository CI entirely (example 
https://github.com/OCA/l10n-brazil/pull/2388 )

V12 is still quite popular to leave it with a broken CI entirely... Alternative I see are:

- disable V12 tour tests one by one as in the example I gave. cons: will be very time consuming.
- disable tests for offending modules. cons: may be would loose too much test coverage.
- disable the odoo/odoo tests entirely on offending repos and only keep tests for OCA/OCB. pros: good for the planet.
- patch the odoo clone somewhat in the OCA CI tooling before running the tests.
- any other idea?

**Comment by rvalyi** [comment]
bonus idea: monkey path _open_socket in V12 offending tests.
cc @marcelsavegnago

**Comment by pedrobaeza** [comment]
Well, maybe Odoo people will merge this, but on the same mood, there are others stucked at 11.0, and anothers at 13.0, so they will demand the same.

The best bet is to modify the OCA CI to only use OCB. At the end, there won't be any counterpart, as there are no more Odoo updates, so if right now is green, the only chance to break it is on OCB. And we will gain less energy consumption in the builds.

**Comment by marcelsavegnago** [comment]
@rvalyi @pedrobaeza For now I did a PR for the OCB too

https://github.com/OCA/OCB/pull/1166

**Review by antoniospneto — APPROVED** [review]

**Review by SirTakobi — APPROVED** [review]

**Comment by C3POdoo** [comment]
Dear @marcelsavegnago,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
