### PR TITLE
[FIX] l10n_nl: incorrect tax template

### PR DESCRIPTION
**Pull request by nim-odoo**
Following forward-port.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
@Yenthe666 for the record, this is quite urgent since it's impossible to install l10n_nl in v12

**Comment by Yenthe666** [comment]
@nim-odoo thanks for the ping! We already have a few Odoo's into production on V12 (and we could install `l10n_nl` without any issues) though. 
For those we already have in production: a git pull and update of the module `l10n_nl` should resolve this one, right?

**Comment by nim-odoo** [comment]
Hum no, it refers to `btw_X0` which is defined nowhere.

**Comment by Yenthe666** [comment]
You're right, we didn't have this problematic record in our production db's at that point. I'm testing your fixes locally right now (on a new db)

**Pull request closed without merging**
