### PR TITLE
[IMP] account: improve account.fiscal.position.map_tax() performance

### PR DESCRIPTION
**Pull request by cawo-odoo**
Context: upgrade script calling `recompute_fields(cr, "sale.subscription.line", ["price_subtotal"])`. It was noticed that this update step runs a long time and is not limited by the DB, but CPU-limited in python. Profiling the code showed that 94% of the execution time is spent in the `filtered()` call in `map_tax()` of model `account.fiscal.position` during this upgrade. The profile also shows that this whole code path effectively creates deeply nested loops, leading to 3.6 **billion** calls to the `lambda` passed to `filtered()` with only ~4k rows on model `sale.subscription.line` (upg-1218044).

The idea of this improvement is to - by the grace of `read_group()` - build a dict of ids that maps tax_src_id to dest_ids outside of the loop over `taxes` and then build the result only through lookups from that dict, reducing the loop nesting by two levels.

Using cProfile again, it shows that the average runtime of `map_tax()` is ~6x faster with the patch (16.7ms vs. 2.8ms). For above cited upgrade, the process is no longer CPU limited and the runtime of this step is reduced from ~8h to ~2.5h, which is significant enough to be relevant for upgrades. Considering this code is unchanged on branches up to `master`, this should also reduce response times in normal operation, when recomputations involving multiple calls to `map_tax()` are triggered by user action.

### CODE REVIEW

**Comment by cawo-odoo** [comment]
image

These are the profiles w/ and w/o this patch

**Review by aliyatastemirova — APPROVED** [review]
tested and it should give the same results

**Comment by cawo-odoo** [comment]
@aliyatastemirova @jbw-odoo @aj-fuentes I got a message that apparently this can cause an error in some DBs. We're having a look, but we shouldn't merge the forward-ports right now.

**Comment by odooNextev** [comment]
> @aliyatastemirova @jbw-odoo @aj-fuentes I got a message that apparently this can cause an error in some DBs. We're having a look, but we shouldn't merge the forward-ports right now.

Hi @cawo-odoo, I don't know if the error you're talking about it's the same we encountered in a test of Italian Localization (https://github.com/OCA/l10n-italy/actions/runs/7888976045/job/21527704338#step:8:1384).
But we checked that before this PR if a fiscal position got no `tax_dest_id` set, it returned `account.tax()`, now it returns `account.tax(None, )` and we got the issue I linked above.

**Comment by aj-fuentes** [comment]
@odooNextev does this fix the issue for you https://github.com/odoo/odoo/pull/153879 ?

**Comment by odooNextev** [comment]
@aj-fuentes thank you very much!
Tests passes now

**Comment by aj-fuentes** [comment]
I did a quick test with the failed module [from OCA repo](https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_bill_of_entry/tests/test_bill_of_entry.py) and it works with [new patch](https://github.com/odoo/odoo/pull/153879), it indeed fails with 14.0 [previous patch](https://github.com/odoo/odoo/commit/db922a6ac801d56e63ead4c9125bb586defdd6bc).

**Pull request closed without merging**
