### PR TITLE
[IMP] hr: improve search panel in hr module

### PR DESCRIPTION
**Pull request by ravb-odoo**
This PR improves the left search panel in the HR module by automatically selecting the default company based on the user's selected company.

task-4265695

### CODE REVIEW

**Review by arpi-odoo — APPROVED** [review]
LGTM :+1:

**Review by Bertrand2 — APPROVED** [review]
LGTM! Thanks for the PR
robodoo r+

**Comment by Bertrand2** [comment]
robodoo r+

**Comment by Bertrand2** [comment]
robodoo r+

**Pull request closed without merging**
