### PR TITLE
[IMP] im_livechat: remove LivechatButtonView/isChatbotBatchWelcomeMessages

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2892106

### CODE REVIEW

**Review by oomsveta — COMMENTED** [review]
I think you forgot to remove the "imperative" updates of `isChatbotBatchWelcomeMessages`.
That said, if `isChatbotBatchWelcomeMessages` is just an alias for `this.chatbotState === 'welcome'`, then I find the latter clearer. Maybe we don't need this field at all.

**Comment by alexkuhn** [comment]
> I think you forgot to remove the "imperative" updates of `isChatbotBatchWelcomeMessages`.

Oops, now removed.

> That said, if `isChatbotBatchWelcomeMessages` is just an alias for `this.chatbotState === 'welcome'`, then I find the latter clearer. Maybe we don't need this field at all.

Yes, very likely. If runbot is green, then will kill this field and replace uses by `this.chatbotState === 'welcome'`.

**Review by seb-odoo — APPROVED** [review]
Useless commits but diff ok.

**Comment by alexkuhn** [comment]
Merged in grouped PR: https://github.com/odoo/odoo/pull/94722

**Pull request closed without merging**
