### PR TITLE
[8.0][FIX] onchange trigger one2many, many2many

### PR DESCRIPTION
**Pull request by Benniphx**
pull request for issue #2693

### CODE REVIEW

**Comment by qtheuret** [comment]
Maybe this check has been done to avoid some breaks in web client as @rco-odoo explained in #2693 
But it will be great to have more explanations on why this check has been done as asked in this comment : https://github.com/odoo/odoo/issues/2693#issuecomment-127219385

**Comment by Yenthe666** [comment]
@odony and @antonylesuisse could you guys look at this? onchange on one2many and many2many would be nice.

**Comment by odony** [comment]
That change is not likely to produce the effect you expect - what you did is prevent *any* onchange on field *X* to modify field X itself, instead of doing this only for to-many fields.
In any case the limitation is on the client side, the server-side check is not the problem.

The only patch that might be accepted at this point (especially in a [stable](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) version) is adding a warning when a part of the result of an onchange is dropped. Please take this discussion to #2693. It might also help to discuss a real practical use case of what you want to accomplish. Chances are there are better/cleaner ways to do what you want.

**Comment by app-olivier** [comment]
Hello,
There seems to be a better solution here:
http://stackoverflow.com/questions/32326212/one2many-field-on-change-function-cant-change-its-own-value
This issue remains mysterious...
Regards.

**Pull request closed without merging**
