### PR TITLE
[8.0] Pricelist code improvement 

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
Split method _price_rule_get_multi in 3 other methods:
- search of version(_get_pricelist_current_version)
- search of rules (_get_pricelist_rules)
- price computation based on rules (_price_rule_get_multi)

The standard behavior is unchanged.

The goal is to make override easier.

### CODE REVIEW

**Comment by sbidoul** [comment]
:+1: 

@odony can you consider this small refactoring that is fully backward compatible. This enables the creation of interesting modules such as tiered price lists (https://github.com/acsone/acsone-addons/pull/43).

**Comment by adrienpeiffer** [comment]
Rebased

**Comment by antonylesuisse** [comment]
Version dont exists anymore in v9, i let @odony decide if he accepts the split.

**Comment by Yenthe666** [comment]
@antonylesuisse I believe we can close this one now since 8.0 is no longer supported and it changed in 9.0 and up?

**Pull request closed without merging**
