### PR TITLE
Make an eslint error if a class has duplicate member

### PR DESCRIPTION
**Pull request by SimonGenin**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
@SimonGenin haha, another duplicated key spotted. @VincentSchippefilt see, sorting functions alphabetically can be useful :D

**Comment by SimonGenin** [comment]
@aab-odoo J'avais pas pensé de faire une branche enterprise, pour ça j'aurais du 😄

**Comment by VincentSchippefilt** [comment]
> @SimonGenin haha, another duplicated key spotted. @VincentSchippefilt see, sorting functions alphabetically can be useful :D

So an error once in 2 years for 150 devs... I think it's quite ok not to have to think where you write each function while you code for that price 😄

**Comment by SimonGenin** [comment]
@aab-odoo There is https://github.com/odoo/enterprise/pull/21303 fixing the problem in Bi. It's waiting for staging, so I don't know if we can r+ again or if we should wait it's fully merged.

**Comment by SimonGenin** [comment]
@robodoo retry

**Comment by aab-odoo** [comment]
robodoo retry

**Pull request closed without merging**
