### PR TITLE
[FIX] survey: update cursive font

### PR DESCRIPTION
**Pull request by yelizariev**
New version of the font is downloaded from Google Fonts website:
https://fonts.google.com/specimen/Alex+Brush?preview.text=c%C4%8Dc&preview.text_type=custom#standard-styles

The reason of this update is because old version doesn't support special
characters, e.g. Aleksandar Vučić.

opw-2891706

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
@d-fence

**Comment by yelizariev** [comment]
old font:

image

**Review by d-fence — APPROVED** [review]
LGTM for the license part.

**Review by edi-odoo — APPROVED** [review]
LGTM!

**Comment by yelizariev** [comment]
r+ please :pray:

**Review by nle-odoo — APPROVED** [review]
looks good to me

did you build the font? If I download it from github or fonts.google.com I get a 116KB file with 17 tables, but your file is 64KB for 15 tables (when the original one was 46KB for 15 tables)

**Comment by yelizariev** [comment]
@nle-odoo 
It was downloaded  from  fonts.google.com  without modifications. Do you think I should update it to the latest version?

**Comment by nle-odoo** [comment]
> It was downloaded from fonts.google.com without modifications. Do you think I should update it to the latest version?

odd that it went from 64KB to 116KB

If we don't know if the new version has anything that would improve something for us, I think the current one is alright, it's just that it would be annoying if we needed to do another update since it increases the size of the repository by the size of the new file font each time.

robodoo r+

**Pull request closed without merging**
