### PR TITLE
[FIX] l10n_in_hr_payroll: fix view inheritance after refactor

### PR DESCRIPTION
**Pull request by len-foss**
Commit d7a3f39d refactored hr views.
This broke the inheritance of the view in that module.

opw 1971570

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by len-odoo** [comment]
robodoo r+

**Comment by nle-odoo** [comment]
robodoo r-

**Comment by len-odoo** [comment]
robodoo r-

**Comment by len-odoo** [comment]
robodoo r+

**Pull request closed without merging**
