### PR TITLE
[FIX] website_theme_install,*: redirect to frontend after theme install

### PR DESCRIPTION
**Pull request by rdeodoo**
*: theme_bootswatch, theme_default

Before this commit, the first time a website was loading a theme, it would
not be redirected to the frontend afterward (even if that theme was already
installed on another website).
Any other theme installation on that website would redirect to frontend as it
should.

Indeed, the first time it would use the `act_url` returned by `next()` which
would only be called during the first time installation on the website.

All the `ir.action.todo` related to themes can be removed anyway, as you can't
install directly a theme. It can only be installed through website settings >
load a theme.
In which case we will always want to redirect to frontend.

task-2070463

### CODE REVIEW

**Comment by rdeodoo** [comment]
@JKE-be @qsm-odoo That might be cool to merge this one, hopefully it can hit 12.5 quickly after merge. 

@fja-odoo had a look functionally and confirmed the fix seems good

**Comment by rdeodoo** [comment]
Done
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo be kind with @rdeodoo , and r+ this PR

**Comment by rdeodoo** [comment]
@robodoo :fist_oncoming:

**Pull request closed without merging**
