### PR TITLE
sale: update translation terms

### PR DESCRIPTION
**Pull request by yelizariev**
`fr_BE` and `lb` translation files are created manually.
Some terms are obsolete and lead to an error. For example field `acquirer_id` is
renamed to `provider_id`

-"                        <t t-out=\"transaction.acquirer_id.sudo().name or ''\"/>\n"
+"                        <t t-out=\"transaction.provider_id.sudo().name or "
+"''\"/>\n"

Fix it by removing `fr_BE.po` file (because it has not translations anyway) and
by updating lb file:

```
MODULE=sale; LANG=lb; msgmerge --no-wrap -q $MODULE/i18n/$LANG.po $MODULE/i18n/$MODULE.pot | msgattrib --no-fuzzy --no-obsolete -o $MODULE/i18n/$LANG.po
```

https://online.sentry.io/issues/4021453801

### CODE REVIEW

**Comment by yelizariev** [comment]
PR to EE https://github.com/odoo/enterprise/pull/38806

**Comment by mart-e** [comment]
Same here, `fr_BE.po` does not contain any translation (so could be removed actually) but `lb.po` has one this time

**Comment by yelizariev** [comment]
@mart-e done

**Comment by mart-e** [comment]
@robodoo delegate+

**Comment by yelizariev** [comment]
@robodoo r+

**Pull request closed without merging**
