### PR TITLE
[FIX] mail: deleting attachment with bad internet

### PR DESCRIPTION
**Pull request by zel-odoo**
task-2714158

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
typo in title `;` -> `:`

And it is not reproducible in v14?

**Comment by zel-odoo** [comment]
> 

This bug was reported in 15.0. But I see the code of 14.0 seems problematic as well. Maybe I should retarget this branch into 14.0?

**Comment by seb-odoo** [comment]
If you can reproduce in 14 yes you could retarget.

**Comment by zel-odoo** [comment]
> If you can reproduce in 14 yes you could retarget.
I tried to reproduce it in 14 but it seems it works fine there. From 14 -> 15, the method being called inside the rpc changes and that can be the reason causing the problem. (Mostly because we use the `bus` in js to handle delete) and in 14, rpc deletes the python data and the js record is removed from `async remove()`

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
