### PR TITLE
[IMP] cache: improve stats logging 

### PR DESCRIPTION
**Pull request by Xavier-Do**
The current strategy will only log stats from values currently in the cache. This means that  when the cache just got cleaned, we have stats for recently added values, but not for the ones that were removed even if they are still in available.

This commit also register the time needed to compute the value when not in cache.

### CODE REVIEW

**Review by rco-odoo — COMMENTED** [review]
Overall this looks good to me.
However, for the sake of logging, I think that one log entry for all stats would be better than one log entry per line.  Isn't it better when log entries are self-contained?

**Comment by Xavier-Do** [comment]
> However, for the sake of logging, I think that one log entry for all stats would be better than one log entry per line. Isn't it better when log entries are self-contained?

Its is a good idea, this would also create a single entry in a log_db.

**Review by rco-odoo — APPROVED** [review]
Simply squash both commits before merging.

**Comment by Xavier-Do** [comment]
@robodoo r+

**Pull request closed without merging**
