### PR TITLE
[FIX] l10n_fr_fec: missing rules for transient

### PR DESCRIPTION
**Pull request by william-andre**
The rules were not added for transient models of localizations.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by william-andre** [comment]
@jco-odoo I am cleaning my branches to see if I can delete them and I saw that the conflict with this one could lead to an error.

`1,0,1,0` means you don't have the write access, only create. While this should work in a lot of cases, you will have problems if you have a warning on validation of the wizard. When you try to validate, it is saved in database and if you try to change it afterwards, it is no longer treated as a create but as a write. The user will then be blocked, and he will have to close the wizard, reopen it and fill the all the form again.

It doesn't cost a lot to add the write rights on all transients by default.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@rgo-odoo I don't know if you see others that could be missing for community.

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
