### PR TITLE
[FIX] stock: fix typo in UserError

### PR DESCRIPTION
**Pull request by nouraellm**
Description of the issue/feature this PR addresses:
Typo in the stock module

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nouraellm** [comment]
@rim-odoo

**Comment by rim-odoo** [comment]
@nouraellm Thanks for the fix

:warning: Changing a translatable string in a stable version breaks the existing translations (https://github.com/odoo/odoo/wiki/Translations#is-it-possible-to-modify-master-terms-in-odoo)

I would fix this by adding your fixed version into the "English" translation & fix the source term in `master`
cc @nim-odoo can you confirm you are still proceeding this way?

**Comment by nim-odoo** [comment]
> cc @nim-odoo can you confirm you are still proceeding this way?

Yes.

**Review by rim-odoo — CHANGES_REQUESTED** [review]
Add your fixed version into the "English" translation & fix the source term in master

**Comment by nouraellm** [comment]
@rim-odoo Thank you so much for the clarifications, it was really helpful. 

After checking the history of commits of the master branch it seems that the issue was already fixed in another PR.

Duplicate of #43902

**Pull request closed without merging**
