### PR TITLE
[IMP] calendar, web: rename Create button to New

### PR DESCRIPTION
**Pull request by mcm-odoo**
This commit tries to unify the name of the create buttons in different apps. "New" is used over "Create" to avoid confusion regarding its effect. "Create" could be interpreted as we want the current record to create a new one. But "New" implies that the user will land on an empty page that can be filled.

enterprise part: https://github.com/odoo/enterprise/pull/35139

task id: 3074472

### CODE REVIEW

**Comment by brboi** [comment]
Hello @mcm-odoo 
Ping me when this PR is ready ;-)

**Comment by mcm-odoo** [comment]
Hello @brboi 
Runbot seems happy now :smile:

**Review by brboi — APPROVED** [review]
Please change the commit message and I'll r+:
```diff
apps. "New" is used over "Create" to avoid confusion regarding its effect.
-"Create" could interpreted as we want the current record to create a new one.
+"Create" could be interpreted as we want the current record to create a new one.
But "New" implies that the user will land on an empty page that can be filled.
```

**Comment by brboi** [comment]
robodoo r+

**Pull request closed without merging**
