### PR TITLE
[IMP] remove redundant domains, unused imports

### PR DESCRIPTION
**Pull request by niyasraphy**
Removed account_type redundant domains, removed unused imports from files

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Julien00859 — COMMENTED** [review]
There are multiple reasons why I would be against we merge your proposed changes:

About the blank lines:

1. Everytime you modify a file via git, the two (older and newer) versions of the file must exist in git's objects `.git/`. Modifying a file just to include a pep8-missing line-return uses extra disk-space and is kinda useless.
2. Only a few team enforces respecting pep8, the accounting team is an example of a team who does not enforce pep8, adding once all the missing line-return is kinda useless because you can be sure that they will add code that doesn't respect the 2-blank-lines-between-top-level-class-and-functions thus making the code inconsistant again.
3. Adding those blank lines really has a very low added value.

About the useless imports:

1. Again changing the file just to remove the useless import makes the `.git/` folder bigger.
2. Actually we are enforcing via a linter that any modified file doesn't include any useless import, so basically the next time anyone will change those files, he'll be obliged to remove the useless imports. It's better to let live the code as it is as those imports will be gone in the future.

About the various commits:

1. You need to better structurate the list of commits, there should had been one unique commit for all the missing-blank-lines, one unique commit for all the useless imports, one unique commit for the model descriptions, one unique commit for the 15->16 documentation links, one unique commit for the various modifications in the source code.


Generally I dislike style-only commits, usually they bring very limited value and make people argue on "how should that piece of code looks like" which again is kinda counter-productive.

**Comment by niyasraphy** [comment]
@Julien00859 Thanks for the feedback's and suggestions.
Can you point me what should i do now ? should i recommit the same by removing the pep8 related changes ?
Actually there are few fixes too.

1. Redundant domains with account type field
2. Update app list wizard
3. Button and Field labels
4. Adding knowledge module to data file so that it will show in CE
5. Removing duplicated description from models

**Comment by Julien00859** [comment]
> should i recommit the same by removing the pep8 related changes ?

Yes :)

**Comment by niyasraphy** [comment]
@Julien00859 thanks for the guidance, as we discussed new PR created:  https://github.com/odoo/odoo/pull/103238

**Pull request closed without merging**
