### PR TITLE
[FIX] mass_mailing: fix wrong templates with shape images

### PR DESCRIPTION
**Pull request by sobo-odoo**
Since [1], some mass_mailing snippet templates now have images with shapes by default. However, the shapes were not added correctly:

- for the Blockquote snippet, the files specified are not correct (wrong names and wrong extensions).
- for the Team snippet, the shapes are not present when dropping it.

This commit fixes that by properly adding the shape images as defined in the commit [2]. It also removes the "circle images" files as they are not necessary anymore. The basic shapes were also fixed by removing their width and height, since the dropped snippets looked weird because their images have a default width smaller than the shapes.

[1]: https://github.com/odoo/odoo/commit/f4995f560003c2180ad3cef50e1b172a151e50c8
[2]: https://github.com/odoo/odoo/commit/eb1262960f54fd81424a86ef4d6693a950e76cb4

opw-3137732

### CODE REVIEW

**Review by rdeodoo — APPROVED** [review]
@robodoo r+ ty

**Comment by awa-odoo** [comment]
( @rdeodoo got pinged because of mass mailing, is it ok to delete the old images? Wouldn't that be an issue if the templates are not updated as this targets stable? )

**Comment by rdeodoo** [comment]
For tracking purpose: it's not cristal clear reading the PR but here is how to blockquote snippet looks in mass mailing in 16.0:
image
The image link is a dead link

Fixed by this PR
image

**Comment by rdeodoo** [comment]
@awa-odoo I let you r- if you want us to let those images, but after a second check with @sobo-odoo :

- they are not used anywhere else, it was really just a hack to have rounded images
- it's not an image supposed to be selectable or anything by the user
- if saved template were using those
    - if blockquote snippet, it was broken already 
    - if team snippet, those didn't even really used those images and should not be problematic

**Comment by awa-odoo** [comment]
> @awa-odoo I let you r- if you want us to let those images, but after a second check with @sobo-odoo :
> 
> * they are not used anywhere else, it was really just a hack to have rounded images
> * it's not an image supposed to be selectable or anything by the user
> * if saved template were using those
>   
>   * if blockquote snippet, it was broken already
>   * if team snippet, those didn't even really used those images and should not be problematic

@rdeodoo No that's fine, was just mentioning it to make sure.
It's in v16.0 so I don't think people would have used references to those images in custom modules anyway.

Thanks for the in-depth explanation

**Pull request closed without merging**
