### PR TITLE
 [CLA] include luisg123v as a member of Vauxoo

### PR DESCRIPTION
**Pull request by luisg123v**
Name: Luis González
E-mail: lgonzalez@vauxoo.com
GitHub user: https://github.com/luisg123v

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `l...@gmail.com`
- you are signing for the address `l...@vauxoo.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by luisg123v** [comment]
@mart-e  the problem was caused due to my primary GitHub email, I've already set it up properly.

What should I do now? Do I need to make another pr/commit to update the email signature?

**Comment by mart-e** [comment]
```shell
$ git config user.email 'lgonzalez@vauxoo.com'
$ git amend --author="Luis González <lgonzalez@vauxoo.com>"
$ git push --force
```
should make the test pass

**Comment by luisg123v** [comment]
Thanks, that worked just fine!

Used `git commit --amend` instead of `git amend`

**Pull request merged**
