### PR TITLE
[IMP] hw_drivers: fix code styling regarding {get_,update_}conf

### PR DESCRIPTION
**Pull request by loouis-t**
We used a `ConfigParser` object to read/write the `odoo.conf` file on the IoT Box.  
As we don't use interprolation, it is more relevant to use a `RawConfigParser` instead.
Additionally:
- Fixed methods comments structure not conventionally formatted,
- Removed caching from `get_conf` method to prevent caching each key/value + whole `RawConfigParser` object.
- Reverted `write_file` method changes to write only raw files: now writing `.conf` files directly from `update_conf` method.

### CODE REVIEW

**Comment by loouis-t** [comment]
@odoo/rd-security Hello, could you have a look at this please? 

## Context

After `saas-17.1` deactivation on runbot, we had to ask again for an override again on `saas-17.2` on [this PR](https://github.com/odoo/odoo/pull/178718).

(xmo) gave us the override letting some comments.

### Solution proposed

We are applying this advice here.

## Security issues

- `with open(path_file("odoo.conf"), "w", encoding='utf-8') as f:`
  - **Reason for the use:** As `configparser` has it's own way of writing inside files, we are not using our `write_file` method anymore.
  - **Safe because:** filename is hardcoded.
- `conf = configparser.RawConfigParser()`
  - **Reason for the use:** We don't use interpolation, so we have no need for a classic `ConfigParser`.
  - **Safe because:** We are not changing the behaviour of the code, only the type of `configparser`.

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: https://github.com/odoo/odoo/pull/179800#issuecomment-2342872720

**Review by Ysoroko — CHANGES_REQUESTED** [review]
The PR description is too generic and doesn't explain the "raw config parser" change, you can use before/after guideline in this case

**Review by qle-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
