### PR TITLE
[REV] uom: introduces duration unit of measure

### PR DESCRIPTION
**Pull request by jem-odoo**
This reverts commit 43d51466c858719736c3d2be0c9ef5b4f6244733.
Reasons:
- too complex having 2 UoM "Hours"
- impossible with UoM to modelise month: is that 30 days or 31 ?

Task-1971491

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jem-odoo** [comment]
FP request
@robodoo r+

**Comment by nhomar** [comment]
INFORMATIVE:

By law I use as it is now the UoM and there is a standard from an accounting PoV that says the fixed conversion.

I will need you left the Time UoM please

**Comment by jem-odoo** [comment]
@robodoo retry

**Comment by jem-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
