### PR TITLE
[FIX] tools: fix underline and italic in logged notes

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
- in any app log a note using full composer
- add styles to the text (underline strike through italic)

Bug:
styles except bold are removed

Fix:
added missing styles to the whitlelist

opw-2956374

### CODE REVIEW

**Review by mart-e — APPROVED** [review]
I hope we will whitelist text animation soon

**Comment by xmo-odoo** [comment]
I expect it'd be more complicated but how much more complicated would it be to update whatever editor is used by the composer to use the already whitelisted (and more general) `text-decoration` property?

**Comment by HANNICHE-Walid** [comment]
@xmo-odoo sorry I missed your comment 
I have made the requested change

**Comment by xmo-odoo** [comment]
@HANNICHE-Walid Yeah it's not great is it? I'll leave it to the @odoo/rd-framework-editor team to decide, but looking at the two side by side the original is probably better, especially as a bugfix in stable.

**Comment by dmo-odoo** [comment]
I agree that the original commit was in fact better. We were very conservative in the whitelist on purpose, but sometimes we just missed useful stuff. Those two style rules are such cases. I think simply adding them to the whitelist is the best course of action. Therefore, I suggest to revert back to the original commit. Thanks for your work !

**Comment by HANNICHE-Walid** [comment]
@dmo-odoo thanks for the feedback 
I reverted to only editing the whitelist

**Comment by dmo-odoo** [comment]
@robodoo r+

**Comment by dmo-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
