### PR TITLE
[IMP] Stock: Let "Manual Replenishment" translatable.

### PR DESCRIPTION
**Pull request by tanghulu0608**
Description of the issue/feature this PR addresses:
Let "Manual Replenishment" translatable.

Current behavior before PR:
Use the button **Replenish** on product form view. A new Requests for Quotation is created with Source Document set to "Manual Replenishment".  

Desired behavior after PR is merged:
Use the button **Replenish** on product form view. In China, A new Requests for Quotation is created with Source Document set to "手动补给".  

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tanghulu0608** [comment]
@robodoo  r+

**Comment by tanghulu0608** [comment]
I have  Odoo CLA signature check.Why not pass the check?

**Comment by sle-odoo** [comment]
can you remove the merge commit?

**Comment by tanghulu0608** [comment]
@sle-odoo  Done

**Comment by tanghulu0608** [comment]
@robodoo  r+

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by tanghulu0608** [comment]
robodoo retry

**Comment by sle-odoo** [comment]
robodoo r-

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by sle-odoo** [comment]
robodoo retry

**Comment by sle-odoo** [comment]
then do something

**Comment by Xavier-Do** [comment]
@sle-odoo @tanghulu0608 cla fail ;)

**Comment by tanghulu0608** [comment]
> @sle-odoo @tanghulu0608 cla fail ;)

I have Odoo CLA signature check.Why not pass the check?

**Comment by Xavier-Do** [comment]
It may come from your git configuration.

The mail address I have on build is 39181819@qq.com

**Comment by tanghulu0608** [comment]
> It may come from your git configuration.
> 
> The mail address I have on build is [39181819@qq.com](mailto:39181819@qq.com)

Thanks. I try to fix

**Pull request closed without merging**
