### PR TITLE
[FIX] l10n_eg_edi_eta: Account for negative lines as a global discount

### PR DESCRIPTION
**Pull request by akr-odoo**
Description of the issue/feature this PR addresses:
Global discounts weren't considered when we first developed the l10n_eg_eta; we now aim to include it to enable = loyalty, promotions,downpayments,  and global discount features.
Current behavior before PR:
the NetAmount would be incorrectly calculated since the portal does not accept negative lines.
Desired behavior after PR is merged:
Odoo Global discount, promotions, loyalties, & downpayments to be compatible with ETA

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by akr-odoo** [comment]
hello @jco-odoo, please let me know if you would like to discuss this; I wasn't sure what the best way to accommodate the global discounts/promotions is; let me know if you think it's enough to simply check if the line is negative.

**Comment by jco-odoo** [comment]
@akr-odoo The only other where I think about because of SA, is the downpayment case.

**Review by jco-odoo — COMMENTED** [review]
Checking a bit further: 
- The system parameter seems overkill as we do not really doing something weird here. 
- For the negative lines however: I thought about the downpayment lines, but more importantly, if it is a global discount, the taxes on the line should be empty.  Because it does not seem to .  Because we have some localizations where we match those negative lines with positive lines with the same taxes, because we can only send positive lines.  (but that is normally a different use case than the global discount)

**Comment by akr-odoo** [comment]
@jco-odoo thanks, 
* I am doing this since this was done 2 years ago, therefor i am expecting that people might have had their own workarounds /customizations. I can add this new addition to the docs, but if you think it's still overkill, I'll remove it. 
* as for the downpayment lines, (wasn't working before this PR), it is treated as a global discount

@nadaseder can you give your input on global discount taxes? would it be safe to assume that they will not have taxes?

**Pull request closed without merging**
