### PR TITLE
[11.0] sql constraints cannot be overwritten

### PR DESCRIPTION
**Pull request by etobella**
Description of the issue/feature this PR addresses:
I have detected some issues that the system is dropping, creating and sometime failing creating indexes when I update modules and my system is rewriting the sql constraints.

Current behavior before PR:
When an installed module rewrites an sql constraint, every time you update any module, the index will be dropped, then created with the original definition, dropped again and created with the new definition.

Desired behavior after PR is merged:
When a module rewrites an sql constraint, the index will be dropped and created with the new definition only if the module is affected.

@rco-odoo @jbeficent 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jbeficent** [comment]
@mreficent why would you want to do that? Before putting more efforts let's wait until odoo takes action

**Comment by nhomar** [comment]
what i do is create a migration script when I change an sql contraint, change sql constraints is in geenral a bad practice BTW... but I do not know if you have a use case where it isn't

**Comment by etobella** [comment]
A migration script will not work. When you update any module, the constrain will be rewritten, as the definition is not matched.

You may want to change a constraint because it is too restrictive and you want to add new fields on the constraint.

**Comment by MiquelRForgeFlow** [comment]
I think this has been implemented in v13 with https://github.com/odoo/odoo/commit/f8e37d6a808a302cda973bc0c6f2b275355ef74c. Can you check?

**Comment by etobella** [comment]
Yes, thanks!

**Pull request closed without merging**
