### PR TITLE
[IMP] l10n_ch add accounts and account tags to l10n_ch

### PR DESCRIPTION
**Pull request by mpanarin**
adds accounts and account tags data to l10n_ch

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fclementic2c** [comment]
@qdp-odoo  Hello, any chance to get this merge ? Do you agree on the principle.

What we do here is adding accounts tags that match with 'official' swiss statutory report (P&L and Balance sheet). 
The goal is to give possibility for end user to build report also based on account tags (compares account codes today).
This is usefull when end users have a custom chart of account (different from official Sterchi CoA I mean).

**Comment by yvaucher** [comment]
bump @qdp-odoo

**Comment by qdp-odoo** [comment]
hello,

no, it can't be merged that way: you cannot set a tag via an XML file on an account generated via a template, by forging its potential XML id.
```xml
    <record id="1_ch_coa_6500" model="account.account">
        <field name="code">6500</field>
        <field name="tag_ids" eval="[(4, ref(l10n_ch.account_tag_ch_60).id)]"/>
    </record>
```
this would fail miserably if the main company hasn't a Swiss Chart of Account.

Using tags might be an idea, but maybe you want to keep that in an OCA module for people that needs it as it would complicate things for all the other

**Comment by yvaucher** [comment]
@qdp-odoo ouch you are right writing on account.account won't work. But couldn't we add this on the account.account.template itself?

**Comment by qdp-odoo** [comment]
maybe, on the template but then only in master and we'll to think about migrating existing databases to still have working reports for those who are happy with the existing ones right now.

So, at the end, I'm not sure it's worth the effort. What's the percentage of customers not using a Sterchi CoA ?

**Comment by fclementic2c** [comment]
It has to be a template level of course (I missed that sorry).

About your question @qdp-odoo: A majority among our customer uses the Sterchi but they do not follows it strickly so in the end most of the time we have to work the report formulas
BTW I observe the same for France - even with a standard CoA.
Basically, it never happen to me that P&L and B/S report matches any existing chart of account straight away.

I think the end-user should have the possibility to do this mapping himself from the account form.

I admit there 2 drawbacks:
- the tags widget is very small and difficult to read
- you cannot set manually XML id on report lines (you have to do it using XML file -> And this is the reason behind why I am requesting tags in the ch template).

**Pull request closed without merging**
