### PR TITLE
[FIX]account:made partner readonly for posted AML

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: #24423

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
Hello !

What is your use case ? 

Thanks.

**Comment by sswapnesh** [comment]
Hello @tivisse  partner should be readonly for posted Entries.

**Comment by tivisse** [comment]
Thanks @sswapnesh but that is not a use case.

Furthermore it's a behavior modification, not a bug fix. See our guidelines about what can be done in a stable release: https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

**Comment by sswapnesh** [comment]
@tivisse  I do agree with the stable policy but I think we should consider partner as legal fields too. (Works same way in v11.)
Thanks for the Review.

**Pull request closed without merging**
