### PR TITLE
7.0 [FIX] auth_signup module for user duplication

### PR DESCRIPTION
**Pull request by codingforfun**
Without this patch the auth_signup module sends an invitation link for a new user account created by duplication of an existing user account to the existing users mail address instead of the new one. 
This is due to how copy() calls create() in orm.py. 
The previous version of the module just hooks into create() which isn't just correct for the case of duplicating users. Worst case: An dismissed employee may get access back to the system accidentally if his former account is used as a template to create the account for his successor.

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Why do you want to send an invitation email when we change the email ?
If you do not want to send an email when duplicating a user (I agree, email not set yet so will be the same as the one of the user we duplicate), why not just remove the key `reset_password` in `copy` method?
Also please do not break the lines at 80 characters, it reduce the readability of the code (cf the [PEP8 guidelines we do not follow](https://www.odoo.com/documentation/8.0/reference/guidelines.html#pep8-options))

**Comment by codingforfun** [comment]
@mart-e 
>Why do you want to send an invitation email when we change the email ?

I don't wan't to send an invitation email when the email changes. 
I wan't to send an invitation email when I create a new user, using a previous user as a template.
The point of this PR is to make sure the mail is send to the right user. 
Before it was send to the user used as a template. 
If you look at the code, sending the email isn't triggered by changing the email but when following conditions apply: 
+ New user, never signed in before
+ No token has been generated already
+ The write is not called from copy, but from the 'Save' button
+ A valid email exists. 

If you have specific questions to that, please comment in the diff on the line. 

> why not just remove the key reset_password in copy method? 

Because I don't wan't to disable this feature. I just wan't to send to the right user. Thus I do wan't to send on 'Save' and not on 'Duplicate' and only if one changed the mail from the previous user.

**Comment by mart-e** [comment]
Thanks for the precision. However the fact that will send the email only after changing the email (which can be way later than the duplication) is a bit too much "blackmagic", unexpected for the user.
We have big "Send an invitation email" next to the name you can not miss.
Moreover we are in 7.0 which shouldn't change anymore. I would prefer to keep the changes to the minimum.

So I think that disabling the email when duplicating is enough to fix your bug. The user will click on the invitation button if he wants to afterwards.

**Comment by codingforfun** [comment]
> However the fact that will send the email only after changing the email (which can be way later than the duplication) is a bit too much "blackmagic", unexpected for the user.

I don't see the problem here. Without an email you can not send the link at all, so you have to change it anyway to give the new user access. So it won't happen unexpectedly or ages after the user has been created.
I could also just remove the mail in the copy() function but I was thinking that it's usefull as a template e.g. if your companies domain name is very long. 

> So I think that disabling the email when duplicating is enough to fix your bug. The user will click on the invitation button if he wants to afterwards.

It fixes the bug, but my goal was to have the same process as creating a new user from scratch.
When creating a new user the mail is send automatically on 'Save'. From a user perspective it's not intuitive why this should be different when duplicating users.

**Comment by codingforfun** [comment]
> Moreover we are in 7.0 which shouldn't change anymore.

Is also broken for 8.0 btw. I did this for 7.0 because it was my actual use case but once we agree to a solution it should be ported to 8.0 of course.

**Comment by mart-e** [comment]
My point with 7.0 was that it was a change of behaviour (before: not sending an email when setting an email, after: sending an email when writing the email) so shouldn't [be integrated in stable](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) (7, 8 or 9.0). This kind of change should target the master branch.

Now I don't think the automatic sending at creation is a good idea in the first place as this is typically the kind of action that requires a manual action (can be discussed the change in master). The fact that we require the `reset_password` in the context mitigates the impact but still it's dangerous this kind of operations.

**Comment by codingforfun** [comment]
> My point with 7.0 was that it was a change of behaviour (before: not sending an email when setting an email, after: sending an email when writing the email) so shouldn't be integrated in stable (7, 8 or 9.0). This kind of change should target the master branch.

But the change is necessary anyway, since the current state (sending the mail to the template user) is a security issue. So if changed it could be done in a consistent way. 

> Now I don't think the automatic sending at creation is a good idea in the first place as this is typically the kind of action that requires a manual action

You are right with that. Maybe sending the link should always require a manual interaction. But it should be consistent. Creating new users from scratch or by duplication should make no difference.

**Comment by codingforfun** [comment]
So whats the conclusion? Do you reject this PR?

**Comment by mart-e** [comment]
Indeed, for stable version, we keep the changes to the minimum. I have implemented the copy change at 35b9ff71465b04f8c1a6a1eb26d20c0ff37bdefd

**Pull request closed without merging**
