### PR TITLE
[IMP]web_kanban: Add a new widget named kanban_label_selection.

### PR DESCRIPTION
**Pull request by kme-odoo**
Task: https://www.odoo.com/web?#id=20219&view_type=form&model=project.task&action=333&active_id=131&menu_id=4720
Pad: https://pad.odoo.com/p/r.UY1FNLn7RPuUbZeB

### CODE REVIEW

**Comment by msh-odoo** [comment]
LGTM

**Comment by mge-odoo** [comment]
@kme-odoo I just improved a bit your code. Do you agree with these changes ?

**Comment by kme-odoo** [comment]
yup.. I agree with your changes. :+1:

**Comment by mge-odoo** [comment]
Merged in master 4721dc39b6a649d75c92f919c3077c1ac6458a85 and f1be9dfc7228366d1b3ae995b1a939e5be8eea56

Thanks @kme-odoo

**Pull request closed without merging**
