### PR TITLE
[FIX] module: coupon_program: last use of promotion program coupon fails

### PR DESCRIPTION
**Pull request by momegahed**
Steps to reproduce:

1- install ecommerce - sales
2- sales > settings > enable coupons/promotion program
3- create a promotion program that applies on the first n orders
4- make orders with the promo code applied until order no. n-1
5 order no. n will fail when you add the promo code without giving an error message

Bug:

the currently applied promotion program will not be applied if this is the last order allowed in the program

Fix:

include currently applied promotion program if it was the last order allowed in it

OPW: 2737423

### CODE REVIEW

**Comment by simongoffin** [comment]
Was it impossible to add your code in the function ```_filter_unexpired_programs``` as it seems to be the more appropriate place to manage this logic?

**Review by simongoffin — COMMENTED** [review]
Was it impossible to add your code in the function _filter_unexpired_programs as it seems to be the more appropriate place to manage this logic?

**Comment by agr-odoo** [comment]
> Do you think
> 
> changing return self.filtered(lambda program: program.maximum_use_number == 0 or program.order_count < program.maximum_use_number)
> 
> to return self.filtered(lambda program: program.maximum_use_number == 0 or program.order_count <= program.maximum_use_number)
> 
> (just changed < to <=)

This was recently changed to address another use case

https://github.com/odoo/odoo/pull/80192

But imho here the issue is not the off-by-one, because if you test using the sales app there is no issue on the n-th order
This is something specific to how web shop recompute all promotions validity, so that after successfully adding the promotion (and consequently increasing `program.order_count` to `program.maximum_use_number`, the very next check would fail because `program.order_count == program.maximum_use_number` and thus remove the promotion

A possible solution could be to add an extra check for promotion already applied to the current order (like `or program.order_count == program.maximum_use_number and program == order.code_promo_program_id`) 

**Side note**: to ensure consistency across all versions we usually try to fix the first version having the issue, so it would be best to check the same use case also in v13

**Comment by momegahed** [comment]
> 

What happens is that every load of /store/cart route runs a check on promotions thus when the page is refreshed after adding the promo code, it checks again, and fails.

also yes for the solution the extra check won't hurt

**Pull request closed without merging**
