### PR TITLE
saas-12.5: fix assertRecordValues

### PR DESCRIPTION
**Pull request by KangOl**
@qdp-odoo @smetl @FlorianGilbert Do the numbers in the account tests finally corrects or is the method `action_switch_invoice_into_refund_credit_note` completely bugged?

### CODE REVIEW

**Comment by smetl** [comment]
@KangOl The tests are currently wrong indeed but maybe you should fix them when forward-porting https://github.com/odoo/odoo/commit/c12bd7125a1c64339e02ae0563f667b8de931b3b

**Comment by KangOl** [comment]
> maybe you should fix them when forward-porting

No. Don't hide your bad review in my forward-port.

**Comment by smetl** [comment]
@KangOl What are you talking about? 
1) These tests are new features in saas-12.5, I can't fix them in saas-12.4.
2) This is clearly something to fix during a forward-port.
3) Feel free to add yourself a conflict for your next forward-port.

**Comment by KangOl** [comment]
> @KangOl What are you talking about?
> 
>     1. These tests are new features in saas-12.5, I can't fix them in saas-12.4.
> 
That's why this PR target the saas-12.5 branch.

>     2. This is clearly something to fix during a forward-port.
> 
Never. Forward-port has absolutly nothing to do with this PR. Fixing the conflict during the forward-port of c12bd7125a1c64339e02ae0563f667b8de931b3b show the real bug that needs to be fixed independently of any forward-port.

**Comment by KangOl** [comment]
@robodoo r+

**Comment by KangOl** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
