### PR TITLE
[FIX] ir_mail_server: Use IDNA for smtp_user

### LINKED ISSUE #61972: ir.mail_server doesn't work with username containing non-ascii characters.
Impacted versions:
All

Steps to reproduce:
Create a new config in "outgoing mail servers", with a non-ascii character in the username. (The SMTP server field should be valid).
Then click on "Test connection"

Current behavior:
Odoo server error (see screenshot)

Expected behavior:
SMTP usernames are generally email addresses. The domain part should be translated to ascii with IDNA/punycode encoding.(The test connection works if I translate manually). The other part maybe should be converted to SMTPUTF8, I'm not sure.
@Julien00859 had fixed that but only for email headers: https://github.com/odoo/odoo/pull/47709 

Video/Screenshot link (optional):
Capture d’écran du 2020-11-18 21-49-21

### PR DESCRIPTION
**Pull request by Julien00859**
There is a user whose email login is "joe@examplé.com", notice the
latin "é" in the domain. This domain is a valid IDNA-2008 domain but
the smtplib of python is incompatible with such domain and raises a
UnicodeError because the character is not ascii.

Note the removed comment about bytestring is a leftover of a dark
python2 age and is no more valid.

Closes #61972

### CODE REVIEW

**Comment by Julien00859** [comment]
Hello @Linekio, we fixed the bug by encoding the domain using punycode (see the referenced pull request on the issue for more info on IDNA/punycode). I cannot configure such account on my own mail server so I could only test the login request was correctly sent to the server to fail with a "Account not found" type error.

Could you test this diff on your side ? There will be a runbot attached if you don't want to pull the changes on your computer, just make sure to change the password to be sure nobody access the ir.mail.server configuration.

**Comment by Linekio** [comment]
@Julien00859 It works fine. Thanks !

**Comment by Julien00859** [comment]
sudo -u @rco-odoo robodo r+ :D

**Review by rco-odoo — APPROVED** [review]

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
