### PR TITLE
[FIX] web_editor: fix classes getting lost when changing media-type

### PR DESCRIPTION
**Pull request by sdegueldre**
Previously, when double clicking and image, video, icon, or document in
the web-editor and replacing it with a different media type, it would
lose its custom classes. This means among other things, that it would
lose margins and paddings from bootstrap classes, or in the case of the
three columns snippet, that the new media would not be properly rounded
in its top corner, or not show up at all in the case of the video. The
only exception was when changing any media type to an icon, but in that
case it would also keep some of the media-specific classes that are
supposed to be removed (eg img-fluid or media_iframe_video).

This commit fixes that as well as some _clear behaviour that didn't
remove all classes that had to be removed, eg some fa-classes would
linger depending on their order, and the o_image class from documents
would always remain.

Linked to: #60443 #60450
task-2282542

### CODE REVIEW

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
@sdegueldre When you are working in stable, you cannot just remove functions like that... :wink:  The methods themself have no problem I guess? So people might rely on their behavior, so even if not called in stable, they have to stay (and ideally should still be called if they were before without inducing a bug).

However, I think the fix is wrong too
> but when the the type of media is changed, it is entirely replaced by a new
HTML element so there cannot be any leftover data

Well it should: that was the point of the `_clear` method. If I have `` transformed into an icon, I should get `<span class="my_super_class fa fa-home"/>`

-> `my_super_class` stayed as expected

I actually found in 2 seconds a case in 12.0 where it makes sense: drop the three columns snippet, the images have the "card-img-top" class which should stay if the media changes:
- in case if I come back to image
- fa icon works with it too when I apply a background-color
- video... actually need the card-img-top class to appear


And even if there was no case like that in stable, we cannot change the behavior: the community may rely on the fact their custom class stays when media type is changed (and it actually makes sense to me).

**Comment by sdegueldre** [comment]
> I actually found in 2 seconds a case in 12.0 where it makes sense: drop the three columns snippet, the images have the "card-img-top" class which should stay if the media changes:
> 
>     * in case if I come back to image
> 
>     * fa icon works with it too when I apply a background-color
> 
>     * video... actually need the card-img-top class to appear
> 
> 
> And even if there was no case like that in stable, we cannot change the behavior: the community may rely on the fact their custom class stays when media type is changed (and it actually makes sense to me).

@qsm-odoo Well the thing is, the class only stays when you change from something else to an icon and that's it, because the icon widget is manually copying those classes over, but if you revert back to an image you lose the classes anyway, so the only case where it behaves as you described is when you switch from something else to an icon.

> we cannot change the behavior: the community may rely on the fact their custom class stays when media type is changed (and it actually makes sense to me).

Well now we're in a pickle because the community might rely on the fact that the custom class stays when changing to an icon but they might also rely on the fact that the custom class is removed when changing to any other media-type. This conundrum is not helped by the fact that these behaviours are very inconsistent from version to version:

- in 12.0, _clear is called before save, and it operates on the original media, isn't called for the currently active widget
- in 12.3, _clear is called on start, and it operates on a clone, is called on all widgets and copies over most of the classes (some fa- classes are removed mistakenly) but only if the type did not change
- in 13.0, _clear is called after save and again operates on the original media, isn't called on the currently active widget but uses the code from the 12.3 that assumed it was called on all widgets, but doesn't copy over any of the classes when changing type, and removes some utility classes it shouldn't (rounded, rounded-circle, ...) when not changing type.

I think your explanation of how it should work makes sense, and I'm not opposed to make it work this way in all versions but it is kind of a breaking change for anything that relies on any of those behaviours as you pointed out. Should I go ahead and make it consistently work as you described across all 3 versions? (Keep all classes except some type-specific ones that will be removed in _clear like img, img-fluid, fa- classes and media_iframe_video)

**Comment by qsm-odoo** [comment]
@sdegueldre Yes, let's go with how I said :wink: This is how it is supposed to work and frankly... there is much less chance on people relying that their custom class is removed than the opposite... and you would fix the problem of using a video for the 3 columns at the same time then :+1: 

If too much trouble, forget about 12.3. There is much less chance of people working with it and it is flawed with many more problems.

**Comment by qsm-odoo** [comment]
@sdegueldre Don't forget to close or adapt this one :+1:

**Pull request closed without merging**
