### PR TITLE
[REM] website_twitter, *: remove the twitter snippet app

### PR DESCRIPTION
**Pull request by qsm-odoo**
*: website

The app was barely (if at all) usable since a while. It is time to let it go: we judge it is not worth to adapt this to the new X API. At least not in a close future.

task-4008369

(will need to create an upgrade script)

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@qsm-odoo Could you also remove social_twitter ?

cc @mart-e

**Comment by bso-odoo** [comment]
@robodoo r+

**Comment by bso-odoo** [comment]
@robodoo r+

**Comment by bso-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
