### PR TITLE
[FIX] core: typo in field type check

### PR DESCRIPTION
**Pull request by william-andre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Maybe saas-15.1 ?

**Comment by rco-odoo** [comment]
> Maybe saas-15.1 ?

Yup, that code was introduced in saas-15.1.

**Comment by rco-odoo** [comment]
Besides that, the fix is indeed completely correct :+1:

**Comment by william-andre** [comment]
@mart-e @rco-odoo Yes, we just needed to change the base as this fix was done long before the 15.1 was frozen

**Comment by mart-e** [comment]
@robodoo r+

**Pull request closed without merging**
