### PR TITLE
[FIX] web_editor: UI freeze on RTL languages

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reprodue:
- enable any rtl language (arabic)
- move to the product page for exemple
- the page is frozen (dependecy loop in css)

Bug:
when the CSS gets minified the missing semicolon error spreads and produce an invalid file

Fix:
added the missing semicolon

opw-3019173 
opw-3032064 
opw-3032250 
opw-3035077 
opw-3034712 
opw-3035077 
opw-3023730 
opw-3022962

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

maybe a title more precise about what it solve would be better

**Comment by nle-odoo** [comment]
robodoo r+ delegate+

**Comment by HANNICHE-Walid** [comment]
> looks good to me, we should also check (in another PR) if we can improve the error output of RTLCSS. The reason of the error (CssSyntaxError: Missed semicolon) was not transmitted clearly to the user so pinpointing the issue was harder than it should have been.

I opened a PR on the npm dependency https://github.com/MohammadYounes/rtlcss/pull/302

**Comment by faridfox** [comment]
Thx for fix Walid

**Pull request closed without merging**
