### PR TITLE
[IMP] don't browse when we only want IDs of one field

### PR DESCRIPTION
**Pull request by hbrunn**
`read()` instead of `browse()` gave me quite a performance boost. Then also honoring the prefetch flag for function fields also gave an extra.

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

We usually don't accept performance only patches [in stable version](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) if it is not fixing a blocking situation.

This patch doesn't seem like an obvious improvement (e.g. the change in `_multi` shouldn't have an impact for fields where `_multi` does make sense) so it may be the case in some corner or very specific cases and not in general cases.
When stating things like "gave me quite a performance boost", please specify a specific scenario and dataset where we can observe and measure the boost.

**Comment by hbrunn** [comment]
@mart-e the difference is ~20 percent:

```bash
~/git-workdirs/ocb-8.0$ git checkout 8.0-odoo
Switched to branch '8.0-odoo'
Your branch is up-to-date with 'odoo/8.0'.
~/git-workdirs/ocb-8.0$ /tmp/profile_x2many_read . bin/server.cfg odoo8_demo
2015-12-12 18:56:52,469 31935 INFO odoo8_demo openerp.modules.loading: loading 1 modules...
2015-12-12 18:56:52,536 31935 INFO odoo8_demo openerp.modules.loading: 1 modules loaded in 0.07s, 0 queries
2015-12-12 18:56:52,548 31935 INFO odoo8_demo openerp.modules.loading: loading 14 modules...
2015-12-12 18:56:52,577 31935 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-12-12 18:56:52,585 31935 INFO odoo8_demo openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2015-12-12 18:56:52,604 31935 INFO odoo8_demo openerp.modules.loading: 14 modules loaded in 0.06s, 0 queries
2015-12-12 18:56:52,749 31935 INFO odoo8_demo openerp.modules.loading: Modules loaded.
         1941062 function calls (1769771 primitive calls) in 0.873 seconds

   Ordered by: cumulative time
   List reduced from 196 to 20 due to restriction <0.1>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  20003/1    0.026    0.000    0.873    0.873 ./openerp/fields.py:799(__get__)
     51/1    0.000    0.000    0.873    0.873 ./openerp/fields.py:886(determine_value)
  60623/1    0.026    0.000    0.873    0.873 ./openerp/api.py:251(wrapper)
     51/1    0.001    0.000    0.873    0.873 ./openerp/models.py:3198(_prefetch_field)
     51/1    0.018    0.000    0.873    0.873 ./openerp/models.py:3149(read)
     51/1    0.037    0.001    0.873    0.873 ./openerp/models.py:3257(_read_from_database)
        1    0.015    0.015    0.854    0.854 ./openerp/osv/fields.py:768(get)
20051/10002    0.014    0.000    0.777    0.000 ./openerp/models.py:5625(__getitem__)
    20002    0.020    0.000    0.210    0.000 ./openerp/models.py:5366(_convert_to_cache)
    20002    0.017    0.000    0.148    0.000 ./openerp/models.py:5376(<dictcomp>)
    60207    0.034    0.000    0.137    0.000 ./openerp/fields.py:1865(__get__)
    20002    0.019    0.000    0.136    0.000 ./openerp/models.py:6031(update)
    20003    0.032    0.000    0.113    0.000 /usr/lib/python2.7/_abcoll.py:548(update)
    20000    0.023    0.000    0.112    0.000 ./openerp/fields.py:1548(convert_to_cache)
   100262    0.069    0.000    0.109    0.000 ./openerp/models.py:5249(_browse)
    60208    0.030    0.000    0.103    0.000 ./openerp/models.py:5266(browse)
    20053    0.018    0.000    0.097    0.000 ./openerp/models.py:6017(__getitem__)
    80261    0.061    0.000    0.068    0.000 ./openerp/models.py:5520(__nonzero__)
    80209    0.017    0.000    0.058    0.000 ./openerp/models.py:5299(ensure_one)
   170521    0.035    0.000    0.057    0.000 {isinstance}

~/git-workdirs/ocb-8.0$ git checkout 8.0-one2many_performance-odoo 
Switched to branch '8.0-one2many_performance-odoo'
Your branch is up-to-date with 'hbrunn/8.0-one2many_performance-odoo'.
~/git-workdirs/ocb-8.0$ /tmp/profile_x2many_read . bin/server.cfg odoo8_demo
2015-12-12 18:57:45,292 32047 INFO odoo8_demo openerp.modules.loading: loading 1 modules...
2015-12-12 18:57:45,359 32047 INFO odoo8_demo openerp.modules.loading: 1 modules loaded in 0.07s, 0 queries
2015-12-12 18:57:45,371 32047 INFO odoo8_demo openerp.modules.loading: loading 14 modules...
2015-12-12 18:57:45,400 32047 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-12-12 18:57:45,408 32047 INFO odoo8_demo openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2015-12-12 18:57:45,427 32047 INFO odoo8_demo openerp.modules.loading: 14 modules loaded in 0.06s, 0 queries
2015-12-12 18:57:45,573 32047 INFO odoo8_demo openerp.modules.loading: Modules loaded.
         1511136 function calls (1401081 primitive calls) in 0.690 seconds

   Ordered by: cumulative time
   List reduced from 194 to 19 due to restriction <0.1>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  10003/1    0.012    0.000    0.690    0.690 ./openerp/fields.py:799(__get__)
        1    0.000    0.000    0.690    0.690 ./openerp/fields.py:886(determine_value)
  60032/1    0.025    0.000    0.690    0.690 ./openerp/api.py:251(wrapper)
        1    0.000    0.000    0.690    0.690 ./openerp/models.py:3198(_prefetch_field)
      2/1    0.015    0.008    0.690    0.690 ./openerp/models.py:3149(read)
      2/1    0.038    0.019    0.690    0.690 ./openerp/models.py:3258(_read_from_database)
        1    0.003    0.003    0.671    0.671 ./openerp/osv/fields.py:768(get)
    20002    0.019    0.000    0.244    0.000 ./openerp/models.py:5367(_convert_to_cache)
    20002    0.017    0.000    0.183    0.000 ./openerp/models.py:5377(<dictcomp>)
    20000    0.023    0.000    0.148    0.000 ./openerp/fields.py:1548(convert_to_cache)
    20002    0.019    0.000    0.136    0.000 ./openerp/models.py:6032(update)
    60011    0.030    0.000    0.133    0.000 ./openerp/models.py:5267(browse)
    90016    0.097    0.000    0.129    0.000 ./openerp/models.py:5250(_browse)
    20003    0.032    0.000    0.113    0.000 /usr/lib/python2.7/_abcoll.py:548(update)
    10002    0.006    0.000    0.079    0.000 ./openerp/models.py:5626(__getitem__)
    30007    0.017    0.000    0.051    0.000 ./openerp/fields.py:1865(__get__)
   140085    0.029    0.000    0.050    0.000 {isinstance}
    30002    0.028    0.000    0.049    0.000 ./openerp/models.py:6025(__setitem__)
    20002    0.014    0.000    0.044    0.000 ./openerp/api.py:757(__getitem__)
```

With `/tmp/profile_x2many_read` being
```python
#!/usr/bin/env python2
from argparse import ArgumentParser


parser = ArgumentParser(
    description='Profile loading a model\'s data for a specific view in order '
    'to find bottlenecks')
parser.add_argument('odoo_basedir')
parser.add_argument('odoo_cfg')
parser.add_argument('odoo_db')
args = parser.parse_args()

import sys
sys.path.insert(0, args.odoo_basedir)

from openerp import SUPERUSER_ID, api, tools
from openerp.sql_db import db_connect
tools.config.parse_config(['-c', args.odoo_cfg])
cr = db_connect(args.odoo_db).cursor()
uid = SUPERUSER_ID
with api.Environment.manage():
    env = api.Environment(cr, uid, {})
    group = env['res.groups'].create({
        'name': 'test_group',
        'model_access': [
            (0, 0, {
                'model_id': env.ref('base.model_ir_model').id,
                'name': 'test',
            })
            for i in range(10000)
        ],
    })
    env.invalidate_all()
    import cProfile, pstats, StringIO
    pr = cProfile.Profile()
    pr.enable()
    group.model_access
    pr.disable()
    s = StringIO.StringIO()
    sortby = 'cumulative'
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats(.1)
    print s.getvalue()
cr.close()
```

Im my case, it is a one2many field with tens of thousands of records, there the impact is more visible.

**Comment by rco-odoo** [comment]
Sorry, but a 20% performance gain is not worth the risk on a stable version.

**Comment by dreispt** [comment]
@rco-odoo might it still be valid for master?

**Pull request closed without merging**
