### PR TITLE
Migrate fontawesome. From 4.7 o 5.3.1

### PR DESCRIPTION
**Pull request by etobella**
Description of the issue/feature this PR addresses: Migration of Fontawesome to 5.3.1

Current behavior before PR: Odoo uses fontawesome 4.7

Desired behavior after PR is merged: Fontawesome will be 5.3.1.
It is using the v4-shims (https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims) in order to simplify the migration.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I doubt this change will be accepted for v11, but for master (v13), as v12 is also frozen, although I don't know right now which version is used in that branches.

**Comment by etobella** [comment]
Probably, it will not be accepted, but I think it is a good idea to make the proposal.
Moreover, the change of version is stable through the use of the v4-shims.

**Comment by mart-e** [comment]
Definitely not for 11.0 (cf our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean)), it could be discussed for master though.

@qsm-odoo is there some plans to upgrade FontAwesome in the future?

**Comment by qsm-odoo** [comment]
For info, this is a duplicate of https://github.com/odoo/odoo/issues/21648.
We will talk about it for master (v13) but this is not an easy update. The behavior is different (the prefix is not `fa` anymore for example and the prefix depends on the icon), some icons do not exist anymore (+ some aliases are gone) and worse, last time I checked, some old icon names are bound to other images in v5... but that would be a nice thing to do.

**Comment by etobella** [comment]
If you use the shims, fa is working for all the old icons. And several more.

**Comment by qsm-odoo** [comment]
Using the shims will not produce the exact same icons, they may be different (example: calendar), so we cannot do that in stable. This also is not that simple as we sometimes referenced icons directly in our scss code (by setting the font awesome family on elements). I also doubt our icons dialog will simply work without some adaptations. So we will see that for after v12.

**Comment by Julien00859** [comment]
Hello @etobella sorry I wasn't aware of this pull request. There is an ongoing effort to migrate to FA v5 in https://github.com/odoo/odoo/pull/48094 , we are trying to migrate the entire source code without using the shim.

**Comment by etobella** [comment]
Great for me then :wink:

**Pull request closed without merging**
