### PR TITLE
[FIX] website_slides: missing "title" step in tour

### PR DESCRIPTION
**Pull request by Julien00859**
During the tour, it tries to create a document given a youtube URL, the
form requires the title input to be filled which was not done by the
tour.

Also, running the tours using tests assets was resulting in an error as
the different tours were not accessible under the /static/ route. The
different files have been moved from /tests/tours to /static/tests/tours
and the assets have been updated accordingly.

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Why moving files ? Tests should be in test.

Concerning title should come from youtube auto completion. You may have issues with random issues with youtube connection failing but we cannot do anything about it. Tests may fail. That's why those are put in external.

**Comment by Julien00859** [comment]
Only python tests are under `/tests/`, javascript tests (tours included) must be loadable from the browser (dev mode + test assets) thus are to be under `/static/`. Some modules put them under `/static/tests/tours/`, some other under `/static/js/tours/`.

I agree that external tests produce false positives on a regular basis, but that very test has been broken for the past two weeks. Can you point me where that youtube autocompletion is ?

**Comment by tde-banana-odoo** [comment]
Well changing URL triggers a server call to prepare_preview which in turn tries to find youtube information: name, image, description. Just try to put a youtube video when uploading a new slide, normally you should have its title automatically filled.

**Comment by Julien00859** [comment]
dummy me who tried to fix a master bug on the v13 branch...............

**Pull request closed without merging**
