### PR TITLE
[Imp]PoS: Remove Create option for PoS order

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: Ponit of Sale

Current behavior before PR: User can Create PoS order manually 

Desired behavior after PR is merged: User cannot Create PoS order manually 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Maybe PR should be targeted to master due to stable Policy.

**Comment by mart-e** [comment]
Why do we have a kanban view for pos.order anyway?
@adr-odoo was added at 36a2bfb9cfafc1642b65b783f6a63c0dbda11dd0, isn't is a bit overkill?

> Maybe PR should be targeted to master due to stable Policy.

Better indeed

**Comment by adr-odoo** [comment]
@mart-e list view is not correctly displayed in mobile.
This kanban view is the default in mobile for better UI.

**Comment by mart-e** [comment]
Ok, I just checked again and indeed, there is a create button in 11.0 but not in master.
As it is only an improvement, we won't do anything for the stable version.

**Pull request closed without merging**
