### PR TITLE
[FIX] website: handle language variants in SEO suggestions API request

### PR DESCRIPTION
**Pull request by SergeBayet**
Steps to reproduce:

- Install serbian (latin) language
- Add a keyword in serbian via SEO optimize menu
- Traceback occurs

This fix ensures that language variants, such as "sr@latin", are properly handled when making requests to the Google Autocomplete API for SEO suggestions.
A test has been added.

task-4210707

### CODE REVIEW

**Comment by SergeBayet** [comment]
@odoo/rd-security Can I do something to avoid this alert? I didn't change a lot :)

**Comment by loco-odoo** [comment]
@SergeBayet, here is a small suggestion : in your commit, you considered that `lang` is either of the form `language_territory` or `language@modifier`. It is correct with the current data of our db but theoretically, it could also be of the form `language_territory@modifier` (see [the doc](https://www.gnu.org/software/libc/manual/html_node/Locale-Names.html)). By doing a small change in your code like:
```py
language_territory_and_modifier = lang.split('@')
language_and_territory = language_territory_and_modifier[0].split('_')
language_code = language_and_territory[0]
region_code = language_and_territory[1] if len(language_and_territory) > 1 else None
```
you could handle this case as well as you would first handle the modifier part :+1:  You could also choose to use a regex; maybe something like
```py
pattern = r'^([\w]+)(?:_([\w]+))?(?:@([\w]+))?$'
match = re.match(pattern, lang)
language_code = match.group(1)
region_code = match.group(2)
```

**Comment by SergeBayet** [comment]
@loco-odoo Yes you're right indeed. I didn't see this possibility: "sr_RS@latin"

**Comment by SergeBayet** [comment]
@loco-odoo 
> ```python
> pattern = r'^([\w]+)(?:_([\w]+))?(?:@([\w]+))?$'
> match = re.match(pattern, lang)
> language_code = match.group(1)
> region_code = match.group(2)
> ```

`\w` is equivalent to `[a-zA-Z_]` so the underscore is considered as a word character. It has to be `[a-zA-Z]`

**Comment by bso-odoo** [comment]
@robodoo delegate=loco-odoo

**Review by loco-odoo — APPROVED** [review]
Thanks for the changes and the tests @SergeBayet :pray: 

@robodoo r+

**Pull request closed without merging**
