### PR TITLE
8.0 Fix bug #6696 block cancel of an account move in a closed fiscal year

### PR DESCRIPTION
**Pull request by alexis-via**
See the bug report #6696 for a detailed scenario of the bug

### CODE REVIEW

**Comment by alexis-via** [comment]
Let's merge this one guys, it's really important !

**Comment by alexis-via** [comment]
@qdp-odoo Could you have a look at this ? I think this fix is really important !

**Comment by feketemihai** [comment]
@alexis-via @qdp-odoo Too bad that this kind of good fixes stays a lot of time without reviewing and merges
@Yenthe666

**Comment by Yenthe666** [comment]
@mart-e could you also have a look at this one? It is long overdue.

**Comment by alexis-via** [comment]
Haha, we've just been hit by this bug again at another customer :)

**Comment by pedrobaeza** [comment]
Me too, but I have almost migrated all to v9/v10, so I resigned about this.

**Comment by qdp-odoo** [comment]
yep it's fixed in v9, and v8 is no longer supported so let's forget about it

**Pull request closed without merging**
