### PR TITLE
[FIX] l10n_in: zero rated supplies under lut as wopay

### PR DESCRIPTION
**Pull request by vivp-odoo**
In GSTR spreadsheet the zero-rated supplies under lut are shown as `wopay`  export type, earlier it was showing as `wpay` due to igst tags being applied on zero-rated lut taxes, that are unnecessary and as we don't need this items for gstr calculations hence  igst tags are removed from this taxes.

task-4263013

### CODE REVIEW

**Comment by jva-odoo** [comment]
@vivp-odoo add a screenshot of what is the final effect.
of GSTR-1 report and spreadsheet

**Comment by vivp-odoo** [comment]
### **Before:**
before-gstr
before-spreadsheet

### **After:**
gstr1_optimized
gstr

**Comment by jva-odoo** [comment]
@jco-odoo LGTM

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@jva-odoo @vivp-odoo Should not this be backported?

**Pull request closed without merging**
