### PR TITLE
[IMP] l10n_pe: add document type nota de debito boleta electronica

### PR DESCRIPTION
**Pull request by jco-odoo**
For them, we are going to add the corresponding type of document, as was done in the credit notes

This is a fw-port, but it had to be done in community instead of enterprise
https://github.com/odoo/enterprise/pull/27180/commits

X-original-commit: 1c7f69f

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@odoo/rd-accounting

**Comment by william-andre** [comment]
Forward port of https://github.com/odoo/enterprise/pull/27127
@robodoo r=

**Comment by william-andre** [comment]
@robodoo r+

**Comment by william-andre** [comment]
@jco-odoo This needs a migration script

**Comment by william-andre** [comment]
@robodoo r-

**Comment by vbe-odoo** [comment]
Hi, @jco-odoo @william-andre I can see that this FW-P (coming from https://github.com/odoo/enterprise/pull/27127) is still open.
Can you help me with this, as we have a ticket open related to V15?
Thanks!
cc' @ren-odoo @fvz-odoo

**Comment by william-andre** [comment]
@jco-odoo a migration script is needed to move master data from one module to another

**Comment by vbe-odoo** [comment]
Hi @jco-odoo @william-andre is there anything we can do to help you move forward with this FW-P?
As we have customers waiting for this FIX to be merged and available.
Thanks!
cc' @fvz-odoo @ren-odoo

**Comment by ren-odoo** [comment]
We need a migration script because it needs to be moved from enterprise to community.

**Comment by kbr-odoo** [comment]
Another case on the functional pipe: 2874872

**Comment by jco-odoo** [comment]
@william-andre Migration script in this pr: https://github.com/odoo/upgrade/pull/3664

**Comment by jco-odoo** [comment]
@william-andre It is a different name because it is not the real cause for the upgrade script.  Could we continue with this, because the upgrade script is merging now.

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
