### PR TITLE
[CLA] Signed CLA agreement for user holdenrehg

### PR DESCRIPTION
**Pull request by holdenrehg**
Signed CLA agreement and PR guidelines for user holdenrehg.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by holdenrehg** [comment]
New PR for my CLA @Yenthe666 , sorry about that.

**Comment by Yenthe666** [comment]
#mart-e can you merge this one? This is the clean PR.

**Comment by Yenthe666** [comment]
Damn, again bitten by the mobile autocorrect!
@mart-e for you.

**Comment by mart-e** [comment]
Not sure how you did it but there were some strange unicode symbols in your signature.
I have removed them and merged it at ee71ba392c502e5b9b405564427d77df4df53ec4

Thanks

**Comment by holdenrehg** [comment]
Thanks @mart-e, I copied from here https://github.com/odoo/odoo/blob/8.0/doc/cla/sign-cla.md#if-you-work-for-a-company and directly into Pycharm. I'm not sure how unicode symbols would have got inserted.

**Pull request closed without merging**
