### PR TITLE
[IMP] stock_account: Fixed typo in field's help

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: Fixing typo

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Or Maybe for master ?

**Comment by pedrobaeza** [comment]
Yeah, maybe, as this changes all translations...

Let's see what @mart-e says.

**Comment by Yenthe666** [comment]
You can do it in stable too. Don't forget to update the pot file though.

**Comment by sswapnesh** [comment]
> You can do it in stable too. Don't forget to update the pot file though.

Updated pot file too. 

I hope @robodoo  will merge both commits during r+ (So I don't need to do this manually)

**Comment by mart-e** [comment]
Hi,
Well we are no longer supposed to modify the source terms in stable but lets extend that to end of the month (Christmas spirit and everything :wink: ).
Thanks for the fix.

robodoo r+

**Comment by Yenthe666** [comment]
You're still in the vacation modus from New-Zealand probably 😉

**Comment by mart-e** [comment]
robodoo retry

**Pull request closed without merging**
