### PR TITLE
[FIX] _get_report_values method is api.model

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

Put correct decorator in some calls of `_get_report_values` method.

As commented in https://github.com/odoo/odoo/pull/39527#issuecomment-547525722, the change of decorator cannot be done in stable.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
@mart-e could you check?

**Comment by mart-e** [comment]
Thanks for the port to master! Could you please modify the commit message to match [the guidelines](https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure)? This patch is not really a fix as it does not change anything in the execution (at least on point of sale code).
Something like:
   
    [IMP] point_of_sale: decorate methods with api.model
    
    This method is an api.model, not an api.multi (on a purely ORM
    consideration, it should have no impact on the execution on standard
    code).

Note that we could probably remove the `api.model` in the future. I think there is still some corner cases where it is needed but I hope it will join the `api.one` in the decorator graveyard one day ;-)

**Comment by mreficent** [comment]
@mart-e commit message updated :)

**Comment by mart-e** [comment]
Thanks !
@robodoo r+

**Pull request closed without merging**
