### PR TITLE
[CLA] Oy Tawasta OS Technologies Ltd.

### PR DESCRIPTION
**Pull request by jarmokortetjarvi**
Description of the issue/feature this PR addresses:
Add CCLA signature for Oy Tawasta OS Technologies Ltd.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jarmokortetjarvi** [comment]
Can this be merged by using signature email jarmo.kortetjarvi@tawasta.fi, or is it mandatory to use the one in the ICLA https://github.com/odoo/odoo/blob/10.0/doc/cla/individual/jarmokortetjarvi.md (jarmo.kortetjarvi@gmail.com)?

It would make more sense to sign CCLA with company domain mail instead of gmail, if it is possible.

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `jarmokortetjarvi@users.noreply.github.com`
- you are signing for the address `j...@tawasta.fi`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by jarmokortetjarvi** [comment]
Ok. I didn't remember that the committer address will be @github.com when using Github website UI for a commit. I'll close this and create a new PR.

**Comment by mart-e** [comment]
It will be the case if you hide your email address.

screenshot from 2017-07-18 13-38-11

**Pull request closed without merging**
