### PR TITLE
Calculate parent_left/right using PL/pgSQL

### PR DESCRIPTION
**Pull request by andreparames**
This is a reimplementation of the algorithm for calculating parent_left and parent_right using PL/pgSQL. In my tests, a significant speedup can be achieved, particularly for tables which already have a lot of records when the fields are added.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by andreparames** [comment]
There was a test failure, but seems unrelated to my patch...?

**Comment by kenvac** [comment]
Nice work @andreparames

**Comment by rvalyi** [comment]
does anyone know how does it compare with using a Postrgres WITH RECURSIVE query? is a WITH RECURSIVE implementation possible with the current data model?

**Comment by xmo-odoo** [comment]
@andreparames processing functions should probably be created just once when initialising models with parent_store rather than every time parent_store is recomputed. More importantly, [you can parameterise pgsql functions on table names](https://stackoverflow.com/a/10711349/8182118).

**Comment by andreparames** [comment]
@xmo-odoo thanks for the suggestions! I did consider building the queries using dynamic SQL and the EXECUTE statement, but the [Postgres documentation states](https://www.postgresql.org/docs/current/static/plpgsql-statements.html#plpgsql-statements-executing-dyn):

> there is no plan caching for commands executed via EXECUTE. Instead, the command is always planned each time the statement is run

Since the queries are possibly run multiple times during a single calculation, losing the plan cache means a probable loss of efficiency. I haven't actually run the numbers, though

The creation of the function is another good point; I chose this approach to keep the changes localized to just that function, but you're right that it isn't efficient. A better approach seems to be to create the PL/pgSQL functions from _auto_init ([here](https://github.com/andreparames/odoo/blob/7abf043a4d326da9ec9a4fe057c15850c91b8a44/odoo/models.py#L2132)) and then just call them from _parent_store. I can make that change today.

**Comment by andreparames** [comment]
I've pushed the change suggested by @xmo-odoo about creating the functions only once. The runbot problem seems to have fixed itself :smile:

**Comment by andreparames** [comment]
Hi, any news?

**Comment by Elkasitu** [comment]
Closed by #22558

**Pull request closed without merging**
