### PR TITLE
[FIX] account: tax lock date: don't check tax lock date when printing the invoice

### PR DESCRIPTION
**Pull request by oco-odoo**
It made no sense; forward-port mistake.

### CODE REVIEW

**Comment by oco-odoo** [comment]
@smetl On en a gros !

**Comment by smetl** [comment]
@oco-odoo On commente le test, c'est le Grand qui a dit

**Comment by smetl** [comment]
@robodoo r+

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
