### PR TITLE
Fixed xpath expression for documentation

### PR DESCRIPTION
**Pull request by SubodhDahal**
Description of the issue/feature this PR addresses: There was an error in the xpath code that adds the snippet to the Content tab, instead of in the Structure tab. The text and image below the code refers to the **Structure** tab so fixed the code to be as such.

Current behavior before PR: The snippet would be added to **Content** Tab

Desired behavior after PR is merged: The snippet will be added to **Structure** Tab

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for you patch but it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by SubodhDahal** [comment]
Hey @mart-e , I have already signed the CLA. https://github.com/odoo/odoo/pull/22970

**Comment by mart-e** [comment]
Thanks, if you rebase your branch, the CLA check should be green.
I let @qsm-odoo decide for the content itself.

**Comment by mart-e** [comment]
Hello,

I was talking about a [git rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase), not recreating your CLA.
You need to update your source branch with the latest changes made on the odoo/odoo repository.

If we merge your branch like this, you would have two CLA (`doc/cla/individual/SubodhDahal.md` and doc/cla/individual/subodhdahal.md`).

**Comment by qsm-odoo** [comment]
@mart-e Sorry for the delay. Yes, "structure" makes more sense than "content". But while we are fixing this, I think we could target 9.0 documentation. Anyways, ok to me :+1:

**Comment by mart-e** [comment]
Merged in 9.0

c2f20f12b9b [FIX] doc: recommand to xpath on snippet_structure
3fc6624631e [CLA] SubodhDahal signs Odoo's CLA

**Pull request closed without merging**
