### PR TITLE
[FIX] web_editor: remove duplicated code

### PR DESCRIPTION
**Pull request by Goaman**
Remove duplicated code.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Goaman** [comment]
False alert.

**Comment by dmo-odoo** [comment]
@robodoo r+

**Comment by dmo-odoo** [comment]
Oh I misred the "false alert" haha, I thought the false alert was that you had closed the PR by mistake... ^^'

**Comment by dmo-odoo** [comment]
Right, one has `document` and the other has `this.document`. Looks like I fell for the trap... :p

**Pull request closed without merging**
