### PR TITLE
[CLA] Add ysantiago as new contributor in vauxoo

### PR DESCRIPTION
**Pull request by ysantiago**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Thanks
@robodoo r+

**Comment by mart-e** [comment]
robodoo retry

**Comment by mart-e** [comment]
@robodoo retry you can do it

**Comment by mart-e** [comment]
@d-fence robodoo is mean to me
@robodoo retry

**Comment by mart-e** [comment]
robodoo retry -_-

**Comment by d-fence** [comment]
youpie

**Pull request closed without merging**
