### PR TITLE
[IMP] web: Add new method getElementData

### PR DESCRIPTION
**Pull request by prra-odoo**
Added new method getElementData, this method is specifically created to get data set on HTML Elements, this method will convert data from string to Integer, boolean and object as per need.

task-3770362

### CODE REVIEW

**Comment by bso-odoo** [comment]
@prra-odoo This is a copy-paste of JQuery code. Why can't you simply use `.dataset.whateverName` in `appointment` ?
IMO this PR should be closed, and only the enterprise one should be kept.

**Comment by msh-odoo** [comment]
> @prra-odoo This is a copy-paste of JQuery code. Why can't you simply use `.dataset.whateverName` in `appointment` ? IMO this PR should be closed, and only the enterprise one should be kept.

@bso-odoo Actually we have created ```getElementData``` function to convert/cast dataset into right type, for this case it will work if we don't use ```getElementData``` but in case of web_editor we are storing whole wysiwyg object, please check [here](https://github.com/odoo/odoo/blob/3fad638447b442f91551e3bed4453064dd7c35a3/addons/website/static/src/js/content/auto_hide_menu.js#L115) and while parsing it we were not getting issues so we have created this method to simplify the data.

**Comment by bso-odoo** [comment]
> @bso-odoo Actually we have created `getElementData` function to convert/cast dataset into right type, for this case it will work if we don't use `getElementData` but in case of web_editor we are storing whole wysiwyg object, please check [here](https://github.com/odoo/odoo/blob/3fad638447b442f91551e3bed4453064dd7c35a3/addons/website/static/src/js/content/auto_hide_menu.js#L115) and while parsing it we were not getting issues so we have created this method to simplify the data.

Another path to the `odooEditor` instance should be found for that case. Maybe creating an Owl service or using an Owl registry ?

**Comment by msh-odoo** [comment]
> > @bso-odoo Actually we have created `getElementData` function to convert/cast dataset into right type, for this case it will work if we don't use `getElementData` but in case of web_editor we are storing whole wysiwyg object, please check [here](https://github.com/odoo/odoo/blob/3fad638447b442f91551e3bed4453064dd7c35a3/addons/website/static/src/js/content/auto_hide_menu.js#L115) and while parsing it we were not getting issues so we have created this method to simplify the data.
> 
> Another path to the `odooEditor` instance should be found for that case. Maybe creating an Owl service or using an Owl registry ?

@bso-odoo Let us work on Registry or Service, we will update you once we are done with changes, we just need to type cast everywhere where we have used getElementData, like Booleans, Integer, Float, Object values in dataset needs to cast in right type.

**Pull request closed without merging**
