### PR TITLE
[FIX] purchase_stock: RFQ automatically created with an inactive vendor

### PR DESCRIPTION
**Pull request by simongoffin**
Steps to reproduce the bug:
- Let's consider the storable product P and the vendor V
- Set V as a supplier of P
- Archive V
- Go to product P and click on button "Replenish"

Bug:

A RFQ was created with the vendor V

opw:2066616

### CODE REVIEW

**Comment by simongoffin** [comment]
robodoo r+

**Comment by odony** [comment]
@simongoffin @nim-odoo That was a rather bold change in stable. Could you consider implementing a more specific fix, only related to the actual bug scenario?
The thing is, this patch causes the name_search() of `product.product` on the SO form to jump from a few milliseconds to 10 seconds on a database with 1M partners, because of that related field.
It could be partially worked around by forcing `auto_join` on the `name` field, but it still serves to show the huge impact of this change...

**Comment by nim-odoo** [comment]
OK, we'll look for a more specific field. We had the discussion about the functional aspect, and although that was a bold change it seemed the most logical and consistent from a business perspective. Anyway, we'll for the first solution: fb295be772767386914f3bd3ae0fdc87e8460e7c

**Comment by simongoffin** [comment]
https://github.com/odoo/odoo/pull/37241

**Pull request closed without merging**
