### PR TITLE
[130 PERF] sale_purchase: create sales order lines in batch

### PR DESCRIPTION
**Pull request by celm1990**
backported of https://github.com/odoo/odoo/commit/06e483dd69b13f27b8a9d0e505e78d79db0bf1b1

@Feyensv can you review this PR please?

I hope not to break the stable policies, but is need for performance

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
Do not change the authorship of the commit if you backport an existing commit ;).

**Comment by Feyensv** [comment]
@fw-bot up to saas-13.3

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by celm1990** [comment]
> Do not change the authorship of the commit if you backport an existing commit ;).

sorry i take into account for next contributions ;)

thx for merge

**Pull request closed without merging**
