### PR TITLE
[FIX] point_of_sale: balance pos session move when closing

### PR DESCRIPTION
**Pull request by caburj**
Instances like deleting a tax used in a pos.order before closing a
session is allowed but it renders error when closing the session
because of imbalance move lines. In this commit, we are adding
a 'balancing' line in the move before it is created. This ensures
the closing of pos session. The introduced move line is named
'Difference at closing PoS session' and is a receivable making it
easy to find and can be reconciled.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
Hi @pimodoo. Can you quickly check this? What do you think? I plan to do a similarly-looking fix for v13 so I need your opinion before I proceed.

**Comment by pimodoo** [comment]
it looks good to me for v 12.0 and 12.3, you can make an another PR for 13.0.

@nim-odoo is it ok for you?

FYI@jev-odoo @antonylesuisse

**Comment by caburj** [comment]
@pimodoo Okay. I'll prepare the one for v13. BTW, I changed the name from 'imbalance_line' to 'balancing_line'. I think the later is more appropriate.

@jev-odoo The ping made by pim didn't work, so I'm pinging you here.

**Comment by nim-odoo** [comment]
Just to be sure: this will clear out any unbalancing?

**Comment by caburj** [comment]
@nim-odoo yes, any.

**Comment by pimodoo** [comment]
@nim-odoo exactly. That's what has been asked by Le support, Anthony and Fabien

**Comment by pimodoo** [comment]
we were thinking of having a warning in a wizard in master, with the unbalanced amount. And in master (or 14.0 I have to ask to accounting) it'll be to a "suspense" account which is there for that.

And in 13.0 it'll be to the cash difference account (what we cannot do here as account are not always set by default in 12.0.

**Comment by nim-odoo** [comment]
Ah. ok.

**Comment by pimodoo** [comment]
@fw-bot up to saas-12.3

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
