### PR TITLE
[FIX] website, website_mass_mailing: add/remove snippets keywords

### PR DESCRIPTION
**Pull request by stefanorigano**
This PR updatsd snippets keywords ensuring they accurately reflect the associated content.
It also removes inline-snippets' keywords' because, following the removal of the sidebar's search, these are no longer necessary.

task-4063510

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
@odoo/rd-website , snippets keywords,  ready for review, thanks!

**Review by qsm-odoo — APPROVED** [review]
Applied typo fixes: https://github.com/odoo/odoo/compare/7e6a9fa42cc9af52bda30a0d5fb08aa0f00af9cb..77c18c88bd8c3601d1aa512c13806e13c7e8c995

This system still sucks with translations by the way as the whole "keywords" entry is being translated instead of each individual word, forcing translation to be duplicated multiple times for each word... and might get translated differently in different keywords by different persons. But we'll improve that one day... there was a task... which was rejected for no good reason :wink: 

@robodoo rebase-ff r+

**Comment by lebl-odoo** [comment]
Huge thanks @qsm-odoo

**Comment by lebl-odoo** [comment]
> there was a task... which was rejected for no good reason

If you found it, feel free to open it again :)

**Pull request closed without merging**
