### PR TITLE
[13.0][FIX] purchase_stock: Use hook method

### PR DESCRIPTION
**Pull request by chienandalu**
Trying again as in

- https://github.com/odoo/odoo/pull/29983

Summary:

- This uses the hook method introduced in ce1f1b6 for consistency when used on modules
that modify this behavior.

TT36816 cc @Tecnativa

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@ryv-odoo not sure if you are the one working in this? My wildcard also for this is @amoyaux . Please :pray:

**Comment by chienandalu** [comment]
> I'm not against it. However not in stable. 

What about the more innocuous  first commit https://github.com/odoo/odoo/pull/92933/commits/d69ff98b1f3bd1d3fd440ae64c2804f32be306f4

> Also a slight change is that product=line.product_id, partner=line.order_id.partner_id are in the compute_all of _get_stock_move_price_unit but not in _get_price_unit (but I don't thing it's an issue)

I don't get this

**Comment by pedrobaeza** [comment]
@amoyaux can you please answer what my colleague stated about only merging in this version the commit https://github.com/odoo/odoo/commit/d69ff98b1f3bd1d3fd440ae64c2804f32be306f4, which can be considered a bug?

**Comment by amoyaux** [comment]
I'm a bit afraid of the behavior change for some of other customer with the first commit. Since their overwrite will apply also now in their inventory valuation (while they could have additional overwrite)

**Comment by chienandalu** [comment]
>Since their overwrite will apply also now in their inventory valuation

And why shouldn't it? :thinking:

**Comment by pedrobaeza** [comment]
@amoyaux @Whenrow desperate friendly reminder!

**Comment by chienandalu** [comment]
Consistency is even more important after this recent change: https://github.com/odoo/odoo/pull/96611/files

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by C3POdoo** [comment]
Dear @chienandalu,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Comment by pedrobaeza** [comment]
@chienandalu this seems to be unsolved in 14.0. Can you please propose it and pass the patch of 13.0 (or even 14.0) to OCB as well?

**Pull request closed without merging**
