### PR TITLE
[IMP] web : added shortcuts to jump between views

### PR DESCRIPTION
**Pull request by tivisse**
TASK : https://www.odoo.com/web#id=19614&view_type=form&model=project.task&action=333&active_id=248
PAD : https://pad.odoo.com/p/r.tRfoVgK6h2KiIpgq

### CODE REVIEW

**Comment by Yenthe666** [comment]
@tivisse quick question. Does this literally mean that you will be able to switch from Kanban (or another view) to List by hitting the "L" button? :smile:

**Comment by tivisse** [comment]
@Yenthe666 , yes, by pressing ALT + SHIFT + L, you will jump on the list view from any view.

**Comment by Yenthe666** [comment]
@tivisse great extra addition, good job! :smile: 
I'm just wondering why a combination of three keys and not just two? Two keys would avoid switching by mistake and would be more than enough I'd assume?

**Comment by antonylesuisse** [comment]
@tivisse I want to enable jquery hotkeys to enable the access from CTRL + access keys instead of ALT SHIFT so make sure you dont collide with common ctrl shortcut (such a C copy, V paste, T tab, maybe L location...)

**Comment by tivisse** [comment]
Landed in master at https://github.com/odoo/odoo/commit/63567e2b5a82b02cf8acc6d0676d29602111a382

**Pull request merged**
