### PR TITLE
[FIX] mail: prevents frozen video elements

### PR DESCRIPTION
**Pull request by ThanhDodeurOdoo**
Before this commit, when a video track ended unexpectedly, the peers
were not notified that the remote track ended, which made it so that
inactive video elements remained on screen.

This commit fixes this issue.

While it could have been fixed by just sending a 'trackChange' peer
event when the track was 'ended', this fix is a slight refactor that
uses the 'onmute' event on the remote track, which is the proper way
of achieving the expected behavior since webRtc "unified plan".

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ThanhDodeurOdoo** [comment]
@seb-odoo @alexkuhn Can you have a look at this change? It's for the " [SEB] RTC: start video -> allow in browser -> then later remove rights in browser -> video becomes frozen for other peers" bug in the pad, I haven't tested it yet. It's also a better way of handling when the remote transceiver stops sending data overall.

**Comment by ThanhDodeurOdoo** [comment]
I think that the event may be triggered when we restrict the transceivers when focusing one video, if it does, maybe we can just send a trackchange event when the local track ends

**Comment by ThanhDodeurOdoo** [comment]
It seems that it also removes the (intentionally) frozen videos of people that are not focused since we block the receiver. This is an alternative PR: https://github.com/odoo/odoo/pull/77215 which should fix the bug.

**Review by alexkuhn — APPROVED** [review]
LGTM, will wait for @seb-odoo just in case. Runbot's red but looks like race condition completely unrelated to this PR.

**Comment by ThanhDodeurOdoo** [comment]
@alexkuhn as I wrote on my last comment this change also removes videos when we block the receiver (filterIncomingTraffic() iirc) of non focused videos (eg: visible in sidebar mode, when focusing a video it will remove the video of the other peers in the sidebar). I don't think it's desirable, the other commit I linked should do the fix without this side effect, it's a different approach with less changed, but I haven't tested it.

**Comment by seb-odoo** [comment]
From the description you made alone the other PR looks better indeed. But I have yet to check the implications of the diff in more details.

**Pull request closed without merging**
