### PR TITLE
[I18N] base: don't translate variables

### PR DESCRIPTION
**Pull request by oomsveta**
%%(field)s is a placeholder used by the code, it shouldn't be translated.

This commit corrects the faulty translations.

Task-3621197

### CODE REVIEW

**Comment by oomsveta** [comment]
robodoo r+

**Comment by Yenthe666** [comment]
I don't get why this isn't done on Transifex? :-) Cc @mart-e

**Comment by oomsveta** [comment]
> I don't get why this isn't done on Transifex? :-)
@Yenthe666 

You're right, since Russian and Ukrainian are available for translation on Transifex, this can (and should) be done directly there. I was just told to fix the problem, and assumed I was asked to do so because the languages weren't available on Transifex, and neglected to double-check before opening the pull request. My bad 🙏

**Comment by Yenthe666** [comment]
No worries, I just wanted to make sure you are aware and knew :) I hope this helps you in the future. Thanks for your feedback!

**Pull request closed without merging**
