### PR TITLE
[12.0] [FIX] Default payment communication on invoice

### LINKED ISSUE #29735: [12.0] Can't unset default payment communication on customer invoices
Impacted versions:
12.0

Steps to reproduce:
- Install Invoicing app.
- Go to Invoicing→Configuration→Settings
- In Customer Payments → Communication select the default payment communication on customer invoice from the dropdown menu.
There are 3 choices available, 
"None" (blank)
"Based on Invoice Number"
"Based on Customer".

Current behavior:

If you select Based on Invoice Number and then create a New customer invoice, when you validate the invoice you correctly get the "Payment Reference" filled in with "Invoice Number" (Other info→Payment Ref.) and it will be shown in the PDF too.

If you select Based on Customer and then create a New customer invoice, when you validate the invoice you correctly get the "Payment Reference" filled in with "Customer Number" (Other info→Payment Ref.) and it will be shown in the PDF too.

If you select the blank choice (None) and then create a New customer invoice, when you validate the invoice you incorrectly get the "Payment Reference" filled in with "Customer Number" (Other info→Payment Ref.) and it will be shown in the PDF too.

Expected behavior:

Other info→Payment Ref. should not be filled in with Customer number and you shouldn't see payment reference in PDF too.

### PR DESCRIPTION
**Pull request by primes2h**
Fix #29735 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Ping @william-andre (Based on https://github.com/odoo/odoo/pull/29858#issuecomment-455233254)

**Comment by william-andre** [comment]
@sswapnesh Did I miss something ? The work on #29858 was done in master for saas-12.3. The implementation is completely different.

**Comment by sswapnesh** [comment]
Hello,
I thought you will review this as you mentioned this on comment.

**Comment by primes2h** [comment]
It would be a "nice to have" fix for 12.0 version. Right now it doesn't work, see https://github.com/odoo/odoo/issues/29735.

**Comment by pedrobaeza** [comment]
@william-andre is there any change you give your opinion on this?

**Comment by william-andre** [comment]
Sorry, I did't mean I was going to review this, but I was taking a note to not forget taking this into account while refactoring it.

Regarding the fix, it seems good to me. You could improve the commit message with something like
```
[FIX] account: empty payment communication on invoices

Before this fix, if the communication method was set on neither partner
neither invoice number, the communication was considered as based on 
partner.
After this fix, if we didn't choose a communication method, the 
communication stays empty.

closes #29735
```

Maybe @smetl can merge it?

**Comment by smetl** [comment]
@william-andre I don't have access to this repository :x

**Comment by primes2h** [comment]
> Sorry, I did't mean I was going to review this, but I was taking a note to not forget taking this into account while refactoring it.
> 
> Regarding the fix, it seems good to me. You could improve the commit message with something like
> 
> ```
> [FIX] account: empty payment communication on invoices
> 
> Before this fix, if the communication method was set on neither partner
> neither invoice number, the communication was considered as based on 
> partner.
> After this fix, if we didn't choose a communication method, the 
> communication stays empty.
> 
> closes #29735
> ```

Done! Thank you.

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
