### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by rrahir**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/dcff0890 [IMP] Error: Lookup module's functions  now return NA Errors
https://github.com/odoo/o-spreadsheet/commit/e154817f [FIX] collaborative: Ensure full payload of `UPDATE_CHART`
https://github.com/odoo/o-spreadsheet/commit/1829d0f0 [FIX] functions, find & replace: escape regex special characters
https://github.com/odoo/o-spreadsheet/commit/273c38ca [FIX] figure: Change component structure to leverage navigator native behaviour
https://github.com/odoo/o-spreadsheet/commit/bf97a1e4 [IMP] registries: always populate chart/figure registries
https://github.com/odoo/o-spreadsheet/commit/1178bbec [IMP] components: prevent mouse event defaults on drag-and-drop

### CODE REVIEW

**Comment by rrahir** [comment]
fw-bot ignore

**Comment by pro-odoo** [comment]
@robodoo override=ci/style
Override because the terms which trigger the warnings are used for custom class names or directly in inlined css.

**Comment by rrahir** [comment]
@robodoo retry

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
@robodoo retry

**Pull request closed without merging**
