### PR TITLE
[8.0][FIX] Avoid trying to translate AbstractModel's fields

### PR DESCRIPTION
**Pull request by yajo**
If you declare in your module an `AbstractModel` such as:

```
class A(openerp.models.AbstractModel):
    name = openerp.fields.Char(translate=True)
```

And then you try to export a translation for that module from _Settings > Technical > Translations > Import / Export > Export Translation_, you will get an error similar to this one:

```
2016-01-29 12:05:04,482 17 ERROR demo openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/extra-addons/core-addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/extra-addons/core-addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/wizard/base_export_language.py", line 65, in act_getfile
    tools.trans_export(lang, mods, buf, this.format, cr)
  File "/usr/lib/python2.7/site-packages/openerp/tools/translate.py", line 524, in trans_export
    translations = trans_generate(lang, modules, cr)
  File "/usr/lib/python2.7/site-packages/openerp/tools/translate.py", line 757, in trans_generate
    ids = objmodel.search(cr, uid, [])
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 1647, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4692, in _search
    cr.execute(query_str, where_clause_params)
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "l10n_es_tgss_number_name" does not exist
LINE 1: SELECT "l10n_es_tgss_number_name".id FROM "l10n_es_tgss_numb...
```

Which means that no database object is found. And that is expected because `AbstractModel` subclasses do not create DB tables.

To avoid the failure, we simply skip translation of fields from models that did not create a table.

### CODE REVIEW

**Comment by xmo-odoo** [comment]
The test seems to have little to no relation to the desired effect, `_auto` only denotes whether a backing table is automatically created in the background. That doesn't mean there is no backing table (or view, which is common for reporting models)

**Comment by Yajo** [comment]
Better?

**Comment by xmo-odoo** [comment]
Don't think so, now it's going to exclude any model in which you used a mixin (since mixins descend from AbstractModel). I think you need `not isinstance(objmodel, (Model, TransientModel))`

**Comment by Yajo** [comment]
I think you were wrong with `not`. Updated, please check. Not sure why runbot fails OTOH.

**Comment by xmo-odoo** [comment]
> I think you were wrong with not. Updated, please check. Not sure why runbot fails OTOH.

Ah yes, I didn't re-read the code before the suggestion and was thinking of the other way around (test to skip translation rather than test to allow/perform it)

**Comment by xmo-odoo** [comment]
> Not sure why runbot fails OTOH.

Attempting to run it locally, there are two issues: `trans_generate` [already has a `Model` local variable](https://github.com/grupoesoc/odoo/blob/translate-no-abstract/openerp/tools/translate.py#L717) so there's a bit of a conflict, and more importantly the import from `openerp.models` generates a circular dependency: importing `openerp.tools` imports `openerp.tools.translate` which imports `openerp.models` which imports `openerp.api` which imports `openerp.api`. The latter completely blows up launching odoo which apparently isn't really supported by runbot.

So either the import itself should be moved to inside the function, or the query should be moved to a BaseModel method (e.g. `is_abstract()`). I'd tend towards the latter as it does avoid a worked-around circular import @rco-odoo what do you think?

**Comment by Yajo** [comment]
The latter seems a better option IMHO too.

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
