### PR TITLE
[I18N] Added English translation of Swiss accounting therms.

### PR DESCRIPTION
**Pull request by AntoineZen**
Signed-off-by: Antoine <antoine@riedonetworks.com>

Description of the issue/feature this PR addresses:

This PR adds English translation of the terms used in the Swiss accounting plan.

This is done via a PR and not on Transifex because of Switzerland multiple languages as describe in https://github.com/odoo/odoo/wiki/Translations#how-to-translate-my-chart-of-account-into-multiple-languages.

Current behavior before PR:

Swiss chart of account available in French, Italian and German.

Desired behavior after PR is merged:

Swiss chart of account available in French, Italian, German and ENGLISH.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the proposal but I don't see the point to translate it. The chart of accounts have usually one legal naming, with the exception of multi-lingual countries (like Switzerland) where you should translate it in the official languages. However English is not an official language of Switzerland.
What is your use case justifying the need to have it in English?

**Comment by AntoineZen** [comment]
Hello Martin,

Well, we are a Switzerland based company, but as in today world we could have work-forces from all over the world, we decided to have everything (document, management systems) in English, including accounting. This is why we translated the Swiss chart of accounts into English.  As we did the job, we like to contribute it back to the community, thinking that it can be useful for some other Swiss company that made the same statement than us about English.

Then it's up to you (the odoo community)...

**Comment by mart-e** [comment]
Thanks for the info.
@fclementic2c @grindtildeath @vrenaville @guewen as you have contributed to this CoA in the past, could I have your opinion?
I would be in favour of rejecting this but maybe you see the benefit to add an English translation to the Swiss accounting.

**Comment by mart-e** [comment]
Sorry but no love for this proposal from Swiss users. Let's keep it simple and only the country languages.

**Pull request closed without merging**
