### PR TITLE
Remove unused cli options

### PR DESCRIPTION
**Pull request by xmo-odoo**
As far as I can tell, the `--timezone` XMLRPCs-related options don't have any effect anymore. They just take room in the help text and config file.

### CODE REVIEW

**Comment by odony** [comment]
Looks good, thanks!
Regarding `get_server_timezone()` and the `timezone_get` RPC method, I think we could drop them safely. They've been unused by the client-side for at least 2 stable releases (7.0, 8.0), and even in 6.1 the GTK client only called `timezone_get` out of habit.

**Comment by xmo-odoo** [comment]
Yeah I was thinking more third-party code still calling these for whatever reason. I'll back them out as well. I need to check why runbot fails though, since there's no log at all I expect it's trying to run the instance with xmlrpcs options of some sort.

**Comment by odony** [comment]
Correct, runbot used to hardcode the `--no-xmlrpcs` option when starting servers. Fixed by odoo/odoo-extra@aab04419f2f8a6fafd4265056001362bf2318bc4 and deployed, rebuilding.

**Comment by xmo-odoo** [comment]
Yay, passes now.

**Pull request merged**
