### PR TITLE
[IMP] account_reports & +  : Merge country specific report into the generic EC Sales List report

### PR DESCRIPTION
**Pull request by jbw-odoo**
Adapt EC Sales List report to meet current company country requirements.
User can now choose to display global report (same as previous EC Sales List report)
or display company specific report meeting country specific requirements.

Task: 2217469

### CODE REVIEW

**Comment by qdp-odoo** [comment]
I don't really see how the diff is related to the task/commit description?

**Comment by jbw-odoo** [comment]
> I don't really see how the diff is related to the task/commit description?

Those taxes are needed for lux intrastat. 
image
I will adapt the commit description

**Comment by qdp-odoo** [comment]
thx

**Comment by qdp-odoo** [comment]
commit description isn't yet on point. I'd suggest 

> [IMP] l10n_be, l10n_lu: enable intrastat taxes per default
> 
> Seamless intrastat reporting involve intrastat to be active by default
> 
> Task: 2217469 - Merge country specific report into the generic EC Sales List report

?

**Comment by jbw-odoo** [comment]
> [IMP] l10n_be, l10n_lu: enable intrastat taxes per default
>
>Seamless intrastat reporting involve intrastat to be active by default
>
>Task: 2217469 - Merge country specific report into the generic EC Sales List report

That's not my commit description. Where does it come from ?

**Comment by qdp-odoo** [comment]
that was a suggestion, from me, to replace the commit message you wrote as I don't find it suitable.  :sleeping: ?

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@robodoo r+

**Review by smetl — APPROVED** [review]

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
