### PR TITLE
[FIX] hr_holidays: don't do accrual allocation of time off for archived employees

### PR DESCRIPTION
**Pull request by rim-odoo**
[opw-2071886](https://www.odoo.com/web?debug#id=2071886&action=333&active_id=49&model=project.task&view_type=form&menu_id=4720)

### CODE REVIEW

**Comment by rim-odoo** [comment]
cc @RomainLibert FYI

**Comment by rim-odoo** [comment]
@robodoo r+

**Comment by nim-odoo** [comment]
robodoo r-

**Comment by nim-odoo** [comment]
Email incoming :)

**Comment by rim-odoo** [comment]
@nim-odoo ouaip sorry :s

**Comment by KangOl** [comment]
@robodoo r+

**Pull request closed without merging**
