### PR TITLE
Signing the Odoo CLA

### PR DESCRIPTION
**Pull request by Axl-Lvy**
Description of the issue/feature this PR addresses: Signing the Odoo CLA

### CODE REVIEW

**Review by niyasraphy — COMMENTED** [review]
hi @Axl-Lvy ,
the commit format has to be in this format:  "[CLA] Signing the Odoo CLA"  
thanks

**Review by Axl-Lvy — COMMENTED** [review]
[CLA] signature for Axl-Lvy

**Review by Axl-Lvy — COMMENTED** [review]
[CLA] signature for Axl-Lvy

**Comment by Axl-Lvy** [comment]
Ok sorry ! I will do so, thanks.

**Pull request closed without merging**
