### PR TITLE
[FIX] phone_validation: panamas phone numbers

### PR DESCRIPTION
**Pull request by ande-odoo**
Current behavior:
---
Cannot send SMS to a partner that has a mobile phone number from Panama.

Steps to reproduce:
---
```python
# 6198 5462 is a valid phone number
parsed = phonenumbers.parse('6198 5462', region='PA') 
is_valid = phonenumbers.is_valid_number(parsed)
is_valid == False
```

Cause of the issue:
---
Old versions of phonenumbers (external library) are not updated 
to Panamas mobile phone numbers system change.

Fix:
---
Monkey patched the library
Similar as: https://github.com/odoo/odoo/commit/b21df8797141dac9f2cf0315658a08a238849f5b

opw-3682631

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
It's phonenumbers monkeypatch seasons (third one I've seen this month)

checking the ubuntu (https://packages.ubuntu.com/search?keywords=python3-phonenumbers) and debian (https://packages.debian.org/search?keywords=python3-phonenumbers) versions:

- from ubuntu lunar (23.04) this patch and the Ivory Coast one could be removed
- from debian bookworm (23.06) this patch an the Ivory Coast one could be removed

I checked with moc and I think for 17.0 version we supports debian bullseye (20.08) and Ubuntu 22.04 version.

And the next ubuntu LTS (24.4) will be in april , so possibly for 18.0 if we supports next Ubuntu LTS and debian bookworm these patch could be removed :+1: 

But for now looks good to me :+1:

**Comment by ande-odoo** [comment]
Hi @odoo/rd-sm-phishing Can I get a review ? Thanks !

**Comment by tde-banana-odoo** [comment]
Not much to say, if it works it works ... did you find someone with panama number, e.g. to test whatsapp ?

**Comment by ande-odoo** [comment]
Hi @tde-banana-odoo I fixed both tests, you're right they should both still work independent from the version number, I left the part where we test if the patch is not applied, tell me if you'd like me to remove that part as well.

**Comment by tde-banana-odoo** [comment]
@robodoo r+

It looks ok to me, thanks :) runbot is red due to another thingy, triggered a rebuild and hop.

**Comment by ande-odoo** [comment]
I've rebased the branch

**Pull request closed without merging**
