### PR TITLE
[IMP] Rename type fields to *_type

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**
Follow-up of https://github.com/odoo/odoo/pull/27262.

**Current behavior before PR:**
Many models have the selection field `type`, which overwrites the python method [type](https://docs.python.org/3/library/functions.html#type).

**Desired behavior after PR is merged:**
Some `type` fields of several models have been renamed to _something_type_.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
I genuinely like this one. Thanks a lot @mreficent 
@mart-e can you have a look please?

**Comment by nim-odoo** [comment]
Not sure this will be accepted, but that would be great since it would avoid context key propagation errors (e.g. `default_type`). Still, you should use the `old_name` attribute. And that could be nice to raise a warning in case somebody names a field `type` (or any other reserved Python word).

**Comment by mart-e** [comment]
On the one hand, I like this as it would make a necessary cleaning. On the other hand, I am afraid it would break many things just for the sake of code cleaning (there is some remaining errors by the way).
Impressive work nevertheless !

**Comment by mreficent** [comment]
Finally this PR is green :green_apple: and ready to merge!!! 🎉 

@nim-odoo I have put `oldname` attribute in all the fields affected as you said. But I won't put your warning suggestion because there exist still several models with `type` (and other reserved Python words) and I prefer not to modify them in this PR. Thus, there would be still too many warnings if logged them. I prefer to do that in another PR if you don't mind.

@mart-e I proceeded with an exhaustive and detailed field renaming method just to make sure I don't leave any `type` to change and avoid breaking things. Maybe I left one case or two in some dark place, but I assure you that the the overall code is cleaned. Runbot guarantees this 🧐

**Comment by mreficent** [comment]
@mart-e I updated this PR deleting the merged commits. Willing to see next step 😊

**Comment by mreficent** [comment]
rebased

**Comment by mreficent** [comment]
Closing this old PR because lot of conflicts. If you are interested on merging one of the commits, tell me and I will do a PR for that specific field full updated.

**Pull request closed without merging**
