### PR TITLE
[FIX] website_slides: fix typo

### PR DESCRIPTION
**Pull request by amdi-odoo**
Purpose
=======
Fix typo in the mail template data used for
a completed course.

Specifications
==============
Adding a 's' to 'Congratulation' on the template
subject.

Task-3026717

### CODE REVIEW

**Comment by Odoonan** [comment]
Hello @amdi-odoo , LGTM :)
ps: here it is just a typo, so it is pretty explicit but the commit message could be a little less generic as there are a few 'data templates'.
Cheers!

**Comment by dbeguin** [comment]
@robodoo r+
This one was tough !

**Comment by dbeguin** [comment]
Well, anyway, this would need translations.
You can find a recent example in https://github.com/odoo/odoo/pull/103393/files

**Comment by dbeguin** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
