### PR TITLE
[FIX] point_of_sale/pos_restaurant: load pos data with noupdate

### PR DESCRIPTION
**Pull request by asno-odoo**
When demo data is loaded by user from UI, the same records are created as is done with loading demo data, ideally they should have same attributes but loading through python function doesn't result in same because noupdate flag is not set. And when ORM tries to remove these records it ends up causing an error.
similar:https://github.com/odoo/odoo/pull/162080
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by caburj — APPROVED** [review]

**Comment by caburj** [comment]
Hi @odoo/rd-security team. May we ask for your override in this PR? The line being edited was approved before but we're making changes to prevent error during demo data loading as described in the PR.

**Comment by mart-e** [comment]
> The line being edited was approved before but we're making changes to prevent error during demo data loading as described in the PR.

@caburj this is not an explanation of the line, see https://github.com/odoo/enterprise/wiki/security#why-was-my-code-code-flagged 
For instance, it seems that the first convert_file was not flagged at that time in #117941
The second one was at https://github.com/odoo/odoo/pull/138035#issuecomment-1761107019 however but it’s always worth checking

@robodoo override=ci/security
Reason: convert_file on a static path

**Comment by caburj** [comment]
@mart-e Thank you for the override. I'll be more explicit in explaining next time.

**Comment by caburj** [comment]
robodoo r+

**Comment by caburj** [comment]
robodoo rebase-ff

**Pull request closed without merging**
