### PR TITLE
[FIX] sale: fix race condition on signature tour

### PR DESCRIPTION
**Pull request by rdeodoo**
rebase-ff

### CODE REVIEW

**Comment by rdeodoo** [comment]
Cherry-pick/Accelerated Forward-port of https://github.com/odoo/odoo/pull/34990 which should fix the race condition on sign tour.

**Comment by d-fence** [comment]
robodoo r+

**Comment by rdeodoo** [comment]
The initial fix was correctly removing the race condition, but in master there was another issue related to the new sudo stuff.

Basically the stock code flow was expecting the SO to be in sudo (which it was but not with the superuser UID), so it crash.

Not sure why it does not happen on every build, probably `sale` tests are executed before `sale_stock` is installed most of the time.

**Comment by rdeodoo** [comment]
@rco-odoo Do you mind checking the sudo commit? If looks ok to you, could you please r+ this one?
(The other commit is a cherry-pick from saas-12.2 removing a race condition as the test is going crazy on master, so you can just ignore it)

**Comment by Xavier-Do** [comment]
robodoo r+ this will be good enough as a temporary fix, we'll go back on this once rco is back

**Comment by rdeodoo** [comment]
@robodoo method=rebase-ff

**Comment by Xavier-Do** [comment]
@robodoo method rebase-ff

**Pull request closed without merging**
