### PR TITLE
[IMP] *: use ast.literal_eval

### PR DESCRIPTION
**Pull request by mart-e**
When simply need to parse a domain, it is easier

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@mart-e note that safe_eval does automatically inject a bunch of builtins into the namespaces unconditionally: https://github.com/odoo/odoo/blob/5dc37da885737b547e7320d1f5a1343296bb6e82/odoo/tools/safe_eval.py#L267-L303 https://github.com/odoo/odoo/blob/5dc37da885737b547e7320d1f5a1343296bb6e82/odoo/tools/safe_eval.py#L341-L345

**Comment by mart-e** [comment]
Yes but is it a problem in the one I changed?

**Comment by mart-e** [comment]
@robodoo r+

**Comment by william-andre** [comment]
Just so that I can go to sleep a little bit smarter tonight, what is the difference between the 2 methods? By easier, do you mean for the processor? Because I don't really see a difference in the code.

**Comment by mart-e** [comment]
@william-andre it's more secure also mostly, [literal_eval](https://docs.python.org/3/library/ast.html#ast.literal_eval) is only to parse expressions, while safe_eval executes expression too.

**Pull request closed without merging**
