### PR TITLE
[FIX] mrp: log production State and Material Availability

### PR DESCRIPTION
**Pull request by nim-odoo**
The `state` and `reservation_state` are never tracked on a MO. This is a
limitation in case a tracked field is computed.

A solution is to apply a similar logic than the one for pickings:

https://github.com/odoo/odoo/blob/15ce41cd1ec8a9e80ec59fa4a0d26329fc1225f9/addons/stock/models/stock_move.py#L485-L502

However, in the case of a MO this works only partially. Indeed, the
state of the MO doesn't depend only on the state of the stock moves.
Therefore, not all state changes are tracked.

The solution applied is to perform the tracking in the compute method.

opw-2304897

### CODE REVIEW

**Comment by nim-odoo** [comment]
@sle-odoo @amoyaux I'm not a fan of the solution, because a compute method should not do this. On the other hand, there are many dependencies to the `state` field: therefore, many overrides are necessary to have something working correctly. I added as a comment a partial solution inspired by what is done for pickings. "Partial" because some states are not tracked, e.g. "to_close".

**Comment by amoyaux** [comment]
@nim-odoo I personally prefer the write/create patch. For one version, I would not try to do something generic with stock anyway.

**Comment by nim-odoo** [comment]
Note the result is the following:
Screenshot_2020-07-28 WH MO 00017 - Odoo

I'm a bit worried that if it works partially, people will point it out and it will end up to be a mess of overrides.

**Comment by amoyaux** [comment]
@nim-odoo Since it's only for v13, I'm ok with the compute if it can avoid useless ticket.

**Comment by nim-odoo** [comment]
fw-bot ignore

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
