### PR TITLE
[FIX] project: translate kanban examples

### PR DESCRIPTION
**Pull request by mart-e**
Using a lazy translator as this file is processed when loading the web
client, no during rendering (the translation memory was not ready yet).

Fixes odoo/odoo#36494

### CODE REVIEW

**Comment by mart-e** [comment]
@eLBati could you have a look at this PR and let me know if it fixes your issue?
Thanks

**Comment by eLBati** [comment]
@mart-e Hi, still English:

image

I also tried exporting `it.po` file, checking if `Once a task is specified...` string is translated, updating project module with `--i18n-overwrite`, but still English

**Comment by mart-e** [comment]
Thanks, indeed the titles were translated but not the translations that that contained placeholder as the one you are showing in your screenshot.
I have updated the PR and it should be good now.

@aab-odoo could you have a look please? I have changed the `escFormat` that you have introduced at b96a4f629646d40ad4a2dceb1e6677ab43342545 but to be sure it is the best way to make it lazy.
Thanks

**Comment by aab-odoo** [comment]
robodoo r+

@mart-e Oups, sorry about that

**Pull request closed without merging**
