### PR TITLE
[REF] stock, mrp: remove stock scheduler compute

### PR DESCRIPTION
**Pull request by amoyaux**
The scheduler in past was responsible for:
- Merging quants
- Reserve picking in confirm state
- Trigger the automatic reordering rule (and possible create a lot of objects)

However the situation changer since:
1) Merging quants: It still needed. It's done when the user open the inventory location menu. But it could be slow if there is a lot of work to do. So we merge them in the scheduler each day in order to avoid a big load if the user open it once a year.
2) Reservation is not needed in the most cases. Each time the user validate a picking we check if it's possible to reserve other base on the new available quantity. It still needed for picking with a reservation date in the future.
3) For the RR it's also mainly useless now, since they are trigger each time a picking goes bellow minimum quantity. The scheduler still required when the forecast is in the future and we don't want to trigger the replenish directly.

Also the wizard is often use in order to run a specific action. But it returns directly and the user has no info when the task has ended.

Also all the performances for the cases upper has been improved a lot and it should be fast. So we decide to remove the wizard to have less code to maintain and the user has a direct return once the task is finished.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Whenrow** [comment]
robodoo r+

**Comment by amoyaux** [comment]
robodoo r+

**Comment by KangOl** [comment]
Can you please rebase your branch(es) and fix the conflicts?

**Comment by amoyaux** [comment]
robodoo r+

**Pull request closed without merging**
