### PR TITLE
[FIX] auth_signup: add patch to the test

### PR DESCRIPTION
**Pull request by thle-odoo**
Version:
- 14.0 only

The `test_confirmation_mail_free_signup` test
introduced with commit fe7cb4daa12da2b9bee0db9912e806f04fbc2919 has to be patched for version 14.0.

Without the patch, the mails are deleted if they are sent without errors.
If we run the test on an instance which has a smtp server configured
the mail will be deleted and therefore the test will fail.

opw-3178901

### CODE REVIEW

**Comment by mart-e** [comment]
@robodoo r+

**Comment by thle-odoo** [comment]
@robodoo retry

**Comment by thle-odoo** [comment]
@robodoo r+

**Comment by mart-e** [comment]
robodoo r+

**Pull request closed without merging**
