### PR TITLE
[FIX]: web: update owl to last version

### PR DESCRIPTION
**Pull request by aab-odoo**
This commit updates owl from v1.0.10 to v1.0.12

See [1] and [2] for the list of changes.

[1] https://github.com/odoo/owl/commit/392185ab6740c8872ca6f19cc71e059b36d3a727
[2] https://github.com/odoo/owl/commit/8da68e925b3baf00f671dd0435bc463d234031d7

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by ged-odoo — APPROVED** [review]

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by Yenthe666** [comment]
@ged-odoo you're really not slowing down on Owl uh? 😉

**Comment by ged-odoo** [comment]
@Yenthe666 We don't want no bug! Owl has to be perfect :)

Also, we are using it to rewrite the web client... So, we are very motivated to fix all bugs!

**Pull request closed without merging**
