### PR TITLE
[IMP] web,*: `o_cursor_default` utility-class

### PR DESCRIPTION
**Pull request by stefanorigano**
This commit is part of v16 overall restyle, task#2704984.

Enterprise:
- https://github.com/odoo/enterprise/pull/25365

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @pparidans, ready for tech review 👋

**Review by pparidans — CHANGES_REQUESTED** [review]
LGTM :+1: 

Just the commit should be a "[IMP]" instead of "[ADD]" (cf. https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html#tag-and-module-name).

**Comment by stefanorigano** [comment]
@pparidans , done thanks 👍

**Comment by pparidans** [comment]
@robodoo r+

**Review by pparidans — APPROVED** [review]

**Comment by pparidans** [comment]
@robodoo r+

**Pull request closed without merging**
