### PR TITLE
Master fixindentation jke

### PR DESCRIPTION
**Pull request by JKE-be**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rdeodoo — APPROVED** [review]
Not worth a comment in the code?

**Comment by JKE-be** [comment]
is  it ok for you now ?

**Review by rdeodoo — APPROVED** [review]

**Comment by rdeodoo** [comment]
Why didn't we merge this one?

**Comment by JKE-be** [comment]
forgot in the pipe

is it still usefull ?

if yes you can r+ ;)

@robodoo delegate=rdeodoo

**Comment by rdeodoo** [comment]
@robodoo r+
yes still needed, just tested

**Pull request closed without merging**
