### PR TITLE
[FIX] mail: remove channel name translation

### PR DESCRIPTION
**Pull request by phenix-factory**
task-2818091

### CODE REVIEW

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

Still pending upgrade approval

**Comment by seb-odoo** [comment]
Might want to up version to 1.9 in manifest (or use 1.8 in upgrade, not sure which is best)

**Comment by seb-odoo** [comment]
@robodoo r+

**Comment by seb-odoo** [comment]
@robodoo r+

**Comment by seb-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
Actually you should get back to 1.9 as we are r+'ing a database update with an increase of mail to 1.9 .

**Pull request closed without merging**
