### PR TITLE
[8.0][FIX] Allow good sitemaps behind proxies.

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses:

Use `web.base.url` in robots.txt and sitemaps.

Current behavior before PR:

If you have Odoo behind a proxy, for example to add the HTTPS layer on
it, its requests think the host is `http://example.com`, and this makes
all URLs in your sitemap look like `http://example.com/page/X` instead
of `https://example.com/page/X`.

Desired behavior after PR is merged:

This saves some requests, makes search engine bots go directly to the
right version of the page, and allows the web admin to have a consistent
URL generation depending on what is set in `web.base.url`.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by antonylesuisse** [comment]
What's the value of request.httprequest.url_root if --proxy-mode is enabled ?

**Comment by Yajo** [comment]
It remains as `http://localhost/`, without the HTTPS.

**Comment by Yajo** [comment]
It can be meaningful that my proxy adds the `X-Forwarded-Proto` header only, not the `X-Forwarded-Host` one. But [docs say Odoo should support any `X-Forwarded-*` header](https://www.odoo.com/documentation/8.0/reference/cmdline.html#running-the-server).

**Comment by Yajo** [comment]
Closing in favor of configuring proxy mode properly.

**Pull request closed without merging**
