### PR TITLE
Master iot map drivers actions qle

### PR DESCRIPTION
**Pull request by qle-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qle-odoo** [comment]
@pimodoo r+

**Comment by pimodoo** [comment]
@qle-odoo I am not a bot

**Comment by qle-odoo** [comment]
@pimodoo retry

**Comment by qle-odoo** [comment]
@pimodoo ignore `I am not a bot`

**Comment by pimodoo** [comment]
@robodoo r+

**Pull request closed without merging**
