### PR TITLE
[IMP] l10n_in: added default account for deferred coa

### PR DESCRIPTION
**Pull request by hamo-odoo**
[IMP] l10n_in: added default account for deferred coa

task-3418482

### CODE REVIEW

**Review by rigr-odoo — COMMENTED** [review]
Thanks for the PR :)

Could you add the link to the Enterprise PR in the description of the PR ?

Besides that, looks OK to me. If it's okay for the PO too, I'll forward it to the final reviewer

**Comment by hamo-odoo** [comment]
Sure @rigr-odoo 
Enterprise PR: https://github.com/odoo/enterprise/pull/45684

**Review by jva-odoo — APPROVED** [review]

**Review by RicGR98 — COMMENTED** [review]
Any reason why this isn't done in stable ? Since saas-16.2, loading the CoA will fetch those new accounts too

**Review by RicGR98 — APPROVED** [review]

**Comment by hamo-odoo** [comment]
@RicGR98 can we proceed with this PR?

**Comment by RicGR98** [comment]
> @RicGR98 can we proceed with this PR?

Yes I've already sent it to the final reviewer who'll r+

**Comment by jco-odoo** [comment]
The order of the accounts seems weird.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jva-odoo** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
@hamo-odoo @jva-odoo Thanks!

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
