### PR TITLE
[BUG][13.0] crm: improvements in settings

### PR DESCRIPTION
**Pull request by sang250399**
- [x] Bug: when creating a user with settings permissions and not granting sales. When that user accesses the settings, it will give an error

- [x] Fix bug
image
image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lathuat1997** [comment]
@tde-banana-odoo May you review and merge it? Please!
cc @std-odoo @flch-odoo

**Comment by tde-banana-odoo** [comment]
Isn't it solved with https://github.com/odoo/odoo/pull/86022 ?

**Comment by sang250399** [comment]
> Isn't it solved with #86022 ?

yes, Can you consider the situation I'm in?

**Comment by tde-banana-odoo** [comment]
Should be fixed with https://github.com/odoo/odoo/commit/95da07bd648bc95302f0d96404d94a25f634e471

**Pull request closed without merging**
