### PR TITLE
Make placeholders more readable

### PR DESCRIPTION
**Pull request by thatnerdjosh**
Description of the issue/feature this PR addresses: Placeholders were indistinguishable from the background, this commit attempts to make that clearer. It uses `grey600` such as in the `website_editor` addon.

Current behavior before PR:
Screenshot from 2023-06-30 21-58-45

Desired behavior after PR is merged:

Screenshot from 2023-06-30 21-56-36

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by BastienFafchamps** [comment]
This was indeed not ideal, thanks for the fix!

@robodoo r+

**Comment by mart-e** [comment]
@robodoo r-
@thatnerdjosh could you make your CLA file lowercase? cc @BastienFafchamps

**Comment by thatnerdjosh** [comment]
@mart-e - can do, I wasn't sure on casing conventions as others had mixed casing. I'll update that shortly and ping when done :)

**Comment by mart-e** [comment]
Thanks !
@robodoo r+ rebase-ff

**Comment by Tardo** [comment]
The real fix should be change the opacity in firefox... not make the color darker :/

**Comment by thatnerdjosh** [comment]
> The real fix should be change the opacity in firefox... not make the color darker :/

Hey @Tardo - makes sense - I'm not really adept with front-end best practices, was just trying to make that readable. If there's a better fix probably good to make another PR.

I brought this exact colour that was used for placeholders in the login form, so if the opacity is a better fix, it may be worth addressing this in the login form as well.

Cheers

**Comment by Tardo** [comment]
@thatnerdjosh Don't worry. The problem is that firefox changes the opacity value, I don't know if it follows a standard or skips it. So, in other browsers now it looks darker:

Firefox:
image

Chromium:
image

**Pull request closed without merging**
