### PR TITLE
Master mrp pdf viewer twa

### PR DESCRIPTION
**Pull request by twa-odoo**
Task: https://www.odoo.com/web?#id=1891791&action=333&active_id=1428&model=project.task&view_type=form&menu_id=4720

### CODE REVIEW

**Comment by ged-odoo** [comment]
ok for js commit

**Comment by ged-odoo** [comment]
branch  has conflicts... once this is fixed, it can be r+ed

**Comment by ged-odoo** [comment]
robodoo delegate=twa-odoo

**Comment by twa-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by svs-odoo** [comment]
@ged-odoo runbot and cla are green

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
