### PR TITLE
[REF] rating: remove unnecessary rating_send_request parameters

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Remove unused parameters, trying to keep a simple API. Those are not used, probably coming from old usage of rating module. Subtype, composition mode and email layout XMl ID are never set. Until further requirements better fallback on default values.

We also also clean a context key usage while passing by, as it is not used in standard codebase anymore.

Task-2710804 (Mail: Clean MailThread Posting API)

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@IT-Ideas

**Comment by tde-banana-odoo** [comment]
Sub-PR for https://github.com/odoo/odoo/pull/99482

**Comment by IT-Ideas** [comment]
> @IT-Ideas

Thanks for the ping 🙂 
Would this affect us? I just grep the code and the new signature should be fine for us from what I have seen.

**Comment by tde-banana-odoo** [comment]
@IT-Ideas Not that I know, I grepped also, but as you use it quite often you might have think of "in that upcoming task we want to have that parameter". As it does not seem to be the case, I send it. Not a big deal anyway, just some cleaning while doing some other stuff :) .

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
