### PR TITLE
[CLA] add Deiber to Xoe Corp CCLA

### PR DESCRIPTION
**Pull request by Deiber**
Signed-off-by: David Arnold (dar) dar@xoe.solutions

**Description of the issue/feature this PR addresses:**
- N/A

**Current behavior before PR:**
- N/A

**Desired behavior after PR is merged:**
- N/A

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@xoe-labs
/cc @blaggacao

### CODE REVIEW

**Comment by blaggacao** [comment]
@mart-e would that be you?

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `d...@xoe.solutions`
- you are signing _for_ the address `d...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by Deiber** [comment]
> Hello,
> 
> Thank you for the CLA signature but it seems there is still an issue.
> 
> * you are signing _using_ the address `d...@xoe.solutions`
> * you are signing _for_ the address `d...@gmail.com`
> 
> The email address in the CLA must be the same as for the signature for the verification to succeed.
> You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.
> 
> Thanks

Solved, thanks

**Comment by mart-e** [comment]
Great, thanks

@robodoo r+

**Pull request closed without merging**
