### PR TITLE
[FIX] base: escape comma and ampersand in the email address 'name' sequence

### PR DESCRIPTION
**Pull request by kebeclibre**
Create a user with a name containing non ASCII chars like "Frédéric, le Grand"
(notice the comma in the middle)

Since comma and & are addresses separators
This means that the name above will be interpreted by the mail library
as Addr1: name empty, address "Frédéric"
Addr2: name: "Le grand", address "<whatever@you.chose>"

Before this commit, this case came to be, passing non-ascii characters as email addresses,
which the mail library doesn't like

After this commit, we force the escaping of those characters

OPW 815202

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tbe-odoo** [comment]
Regarding the issue with diacritics (and non ascii characters) I would use [collapse_rfc2231_value](https://docs.python.org/2/library/email.util.html) in the function ```encode_addr``` defined in the function ```encode_rfc2822_address_header```.
I would do something like this.

```python
name = Header(collapse_rfc2231_value('utf-8', '', pycompat.to_text(name))).encode()
```
Here's a small example 
```python
>>> Header(collapse_rfc2231_value(('utf-8', '', 'Frédéric'))).encode()
'=?utf-8?b?RnLDqWTDqXJpYw==?='
```
Weirdly in python 3 if I have to set '' as the charset.

```python
>>> Header(collapse_rfc2231_value(('', None, 'Frédéric'))).encode()
'=?utf-8?b?RnLDqWTDqXJpYw==?='
```
Otherwise I get this

```python
>>> Header(collapse_rfc2231_value(('utf-8', None, 'Frédéric'))).encode()
'=?utf-8?b?RnLvv71k77+9cmlj?='
```

You can decode the results with this website: http://dogmamix.com/MimeHeadersDecoder/

And regarding the issue with the comma, I will let the experts talk :P

**Comment by odony** [comment]
Can't we just make sure that we properly quote the name in `email_from`? This header should have the following format, in order to be valid:
```
  "Frédéric, Le Grand" <fred@legrand.france>
```

Where is the invalid header being generated? It must be somewhere upstream.

**Comment by tde-banana-odoo** [comment]
Hello,

We use format_addr in various mail-related methods. It comes from the standard library. However when I looked on the world wide numeric digital internet 2K I found that correctly putting the name between quotes was not considered as really standard.

My proposal is to have our own format_addr. Without blackjack and whores, but with proper quoting of the name. We could replace all call to format_addr to our own safe_format_addr for example.

**Comment by nim-odoo** [comment]
related to https://github.com/odoo/odoo/issues/23502

**Comment by Elkasitu** [comment]
also kind of related to #23564 and #23527

**Comment by yelizariev** [comment]
Since Odoo 14 mail handling is refacotored:  
https://github.com/odoo/odoo/commit/18299d7e5051cdad29854bc7280db5002a209500
As I understand, such kind of issues are handled by python class ``email.message.EmailMessage`` and we don't need to make escaping manually.

Odoo v13 and v12 are fixed here; https://github.com/odoo/odoo/pull/51985

So, this PR can be closed

**Comment by C3POdoo** [comment]
Dear @kebeclibre,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
