### PR TITLE
[14.0][Fix]mrp: duplicate MO miss move_byproduct_ids

### PR DESCRIPTION
**Pull request by ngochung207**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Steps to reproduce:
	Step 1: make a MO
	Step 2: duplicate the MO
Expected result: tab move_byproduct_ids is cloned
Actual result: tab move_byproduct_ids is empty

Solution: Add `move_byproduct_ids` data to the return of function `copy_data` in Production Order model

https://user-images.githubusercontent.com/11542778/198750920-3e79ca91-54cf-4d57-9fbf-63773dccb8b5.mp4

Desired behavior after PR is merged:

https://user-images.githubusercontent.com/11542778/198750974-a7199986-8e69-44b2-b94b-35844826570e.mp4

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by AnhQuy123** [comment]
@MerlinGuillaume @Whenrow Hi guys, can you help me review PR? I'm happy to learn from my bro
Look forward to the help

**Comment by Whenrow** [comment]
@AnhQuy123 @ngochung207 This issue should IMO be fixed rather here 
https://github.com/odoo/odoo/blob/45e37b2ad7bdcfd9f9f7e1dabbd0a99c9a0b5cdc/addons/mrp/models/mrp_production.py#L778-L782.
I guess we lose byproduct values juste before the creation

**Comment by ngochung207** [comment]
> @AnhQuy123 @ngochung207 This issue should IMO be fixed rather here
> 
> https://github.com/odoo/odoo/blob/45e37b2ad7bdcfd9f9f7e1dabbd0a99c9a0b5cdc/addons/mrp/models/mrp_production.py#L778-L782
> 
> .
> I guess we lose byproduct values juste before the creation

Thank you for your feedback!.
I don't agree with you, Because of field 'move_byproduct_ids' depends field `move_finished_ids` through the function `_compute_move_byproduct_ids`.  The line code `del values['move_byproduct_ids']` is correct.

I hope with this explanation, you will agree with my proposal in this PR.
Have a nice day!

cc: @AnhQuy123 @vietphuong10

**Comment by AnhQuy123** [comment]
> @AnhQuy123 @ngochung207 This issue should IMO be fixed rather here
> 
> https://github.com/odoo/odoo/blob/45e37b2ad7bdcfd9f9f7e1dabbd0a99c9a0b5cdc/addons/mrp/models/mrp_production.py#L778-L782
> 
> .
> I guess we lose byproduct values juste before the creation

I look forward to your help to complete the task
Thanks for your enthusiasm @Whenrow  :heart:

**Comment by ngochung207** [comment]
@Whenrow 
Thank you for your comment, it helped me better understand the problem I'm having.
I come up with a new way to solve the problem according to your instructions.
Please consider this contribution of mine.

Have a nice day! Thanks for watching.
cc: @vietphuong10 @AnhQuy123

**Review by AnhQuy123 — APPROVED** [review]

**Review by AnhQuy123 — APPROVED** [review]

**Comment by ngochung207** [comment]
@Whenrow  @ticodoo Hello Sir, Please review this PR
Have a nice day! Thanks for watching.

**Comment by Whenrow** [comment]
@ngochung207 I was reading your pull request and i'm wondering if the simplest solution would be 
```python
values['move_finished_ids'] = list(set(values.get('move_finished_ids', []) + values.get('move_byproduct_ids', [])))
```
no need to filter, no duplication, we get the byproduct and finished moves. The code is way shorter What do you think ?

**Comment by ngochung207** [comment]
> @ngochung207 I was reading your pull request and i'm wondering if the simplest solution would be
> 
> ```python
> values['move_finished_ids'] = list(set(values.get('move_finished_ids', []) + values.get('move_byproduct_ids', [])))
> ```
> 
> no need to filter, no duplication, we get the byproduct and finished moves. The code is way shorter What do you think ?

@Whenrow 
I think the above code will not give the expected result, because of: 
 - In case of copy MO, we always don't have `move_byproduct_ids` in `values`
 - The second element in the `values.get('move_finished_ids', [])` has a data type of dict, so it will error when using set()

So in my opinion, we can have 2 ways to solve the problem:
1. Generate value `move_byproduct_ids` in function `copy_data` (https://github.com/odoo/odoo/commit/c8474d0b14328637e3d5f9cd1e2ad0feba24e65c)
2. From filter value of `values[move_finished_ids]` (https://github.com/odoo/odoo/commit/63761e65ed50a314fa7a4b872f955952f1702c76, I understand that you comment the code is long)

Please help me find the best way to solve this problem
Have a nice day! Thanks for watching.

**Comment by Whenrow** [comment]
@ngochung207 We have decided to take the simplest solution for this one. We can concat the two lists into `move_finished_ids` without filtering. The unicity is already managed when calling the `create`.

**Comment by ngochung207** [comment]
> @ngochung207 We have decided to take the simplest solution for this one. We can concat the two lists into `move_finished_ids` without filtering. The unicity is already managed when calling the `create`.

@Whenrow Do you accept the plan I gave you at first? commint: https://github.com/odoo/odoo/commit/c8474d0b14328637e3d5f9cd1e2ad0feba24e65c

**Comment by Whenrow** [comment]
> @Whenrow Do you accept the plan I gave you at first? commint: [c8474d0](https://github.com/odoo/odoo/commit/c8474d0b14328637e3d5f9cd1e2ad0feba24e65c)

I prefer merging `move_finished_ids` and `move_byproduct_ids` in the `create` directly. I will fix your case and potential future other calls to create

**Pull request closed without merging**
