### PR TITLE
[FIX] stock_picking_batch: remove create button

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Bug:
- enable wave transfers
- Kanban view should not have a create button

Fix:
removed the button

opw-2978078

### CODE REVIEW

**Review by adwid — CHANGES_REQUESTED** [review]
Because of a too high priority, this new view acts as a substitution of the initial view (`stock_picking_batch_kanban`). Therefore, if now the user opens the kanban view of the batch transfers, the `Create` button is no more present (which is incorrect).
I think you should follow the same idea than the tree view of the wave transfers, so:
- a lower priority (by default it is 16)
https://github.com/odoo/odoo/blob/70a0be9746403239cd43f5abd5aaff27696e3332/addons/stock_picking_batch/views/stock_picking_wave_views.xml#L6
- a link in the window action
https://github.com/odoo/odoo/blob/70a0be9746403239cd43f5abd5aaff27696e3332/addons/stock_picking_batch/views/stock_picking_wave_views.xml#L33-L34 

Also, adding a new view needs an exception (this is the reason why `ci/template` failed). I'm not sure how bad this issue is, so I let the other teams say if this change is required in stable versions or if we redirect it in master

**Comment by HANNICHE-Walid** [comment]
@odoo/rd-logistics

**Comment by Whenrow** [comment]
You are adding a new view in stable version. we usually don't allow that as not everyone will/want update their modules. Instead you could use the context to set `create` to a null value like here: https://github.com/odoo/odoo/blob/fa58938b3e2477f0db22cc31d4f5e6b5024f478b/addons/stock/wizard/stock_inventory_conflict.xml#L28

**Comment by HANNICHE-Walid** [comment]
hi @Whenrow 
it's better indeed to set the `create` attribute depending on the type (batch/wave) instead of using a new view but I am not able to do it

**Comment by d-fence** [comment]
Upgrade exception [#167](https://runbot.odoo.com/web/#id=167&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
view:stock_picking_batch.stock_picking_wave_kanban
```
cc @KangOl @nseinlet

**Comment by adwid** [comment]
robodoo r+

**Pull request closed without merging**
