### PR TITLE
[FIX] [7.0] fetchmail should not set as 'Seen' messages which raised exception

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by eLBati** [comment]
For 8.0: https://github.com/odoo/odoo/pull/5705

**Comment by StefanRijnhart** [comment]
:+1:. One-off errors are easily missed, and this way, a queue of errors remains visible in the logs until resolved.

**Comment by yvaucher** [comment]
:+1:

**Comment by Yenthe666** [comment]
Hi @eLBati,

Thanks a lot for your PR!
Sadly we do not longer support version 7.0, since we only support up to three version back (8.0, 9.0 and 10.0).
If you can still reproduce this on a newer version (8.0, 9.0 or 10.0) then please create a new PR against one of these versions.
Sorry that we didn't handle this PR in time!

Regards,
Yenthe

**Pull request closed without merging**
