### PR TITLE
[FIX] account_asset: compute depreciation button

### PR DESCRIPTION
**Pull request by simongoffin**
It is not allowed to recompute the depreciations when the asset
is confirmed.

opw:672203

### CODE REVIEW

**Comment by oerp-odoo** [comment]
Hello,
this is a wrong change. You changed that button to always be invisible (`invisible="1"`), not just after it is confirmed. Now you can't see the button even when asset is in draft state, though making it impossible to recompute at all.

It should be changed to `attrs={'invisible': [('state', '!=', 'draft')]}`

**Comment by simongoffin** [comment]
@qdp

**Comment by oerp-odoo** [comment]
Hello @simongoffin  will this be changed in 8.0 branch?

**Comment by simongoffin** [comment]
Hello @oerp-odoo 
This modification has been merged with 7f05692cb9d28968ff1b14b7542d24f1de1944b5

**Comment by oerp-odoo** [comment]
Thanks

On 2016.04.21 17:15, Goffin Simon wrote:
>
> Hello @oerp-odoo <https://github.com/oerp-odoo>
> This modification has been merged with 7f05692 
> <https://github.com/odoo/odoo/commit/7f05692cb9d28968ff1b14b7542d24f1de1944b5>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/pull/11382#issuecomment-212937892>
>

-- 

Pagarbiai / Regards

Andrius Laukavičius

Vyriausiasis Programuotojas / Lead Developer

+370 52 032 766

ala@boolit.eu <mailto:ala@boolit.eu>

	

_boolit.eu <http://www.boolit.eu/>

__odoolietuva.lt <http://www.odoolietuva.lt/>

__Odoo Partner 
<https://www.odoo.com/partners/boolit-uab-693973?country_id=128>_

<https://www.linkedin.com/company/boolit><https://www.facebook.com/BoolitBusinessSolutions/?fref=ts><https://twitter.com/boolitsolutions>

**Pull request merged**
