### PR TITLE
[FIX] mrp: force user company when searching for a BOM

### PR DESCRIPTION
**Pull request by paulius-sladkevicius**
In multi-company environment user should search only own BOM's

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

There is already a [multi-companies security rule](https://github.com/odoo/odoo/blob/2e074cb3051f5b439bfc809a81c41a9eb4fe3721/addons/mrp/security/mrp_security.xml#L44) for `mrp.bom` so you should already have the filtering made.
What is your usecase ?

**Comment by komsas** [comment]
Search is made with superuser, so access rules is not used.

**Comment by antonylesuisse** [comment]
Can you explain why this code is called as superuser ?

**Comment by komsas** [comment]
I personally don't know why exactly somebody did like this, but I think because e.g. sales person can not have access to mrp part.

**Comment by antonylesuisse** [comment]
So maybe it's an access right issue. In the mean time I close this PR, if you can provide me a precise use case (a full scenario) where action_explode is called as superuser and the wrong bom is selected. I will reopen it (althought the proper fix would probably be to aavoid sudo).

**Comment by komsas** [comment]
There is no need for a full scenario to show where superuser is called, because if you check addons/mrp/stock.py:41 you will see that SUPERUSER_ID is used for a BOM search.

I agree proper fix should be without superuser, but totally understand why it was used here, because user only with sales rights may not have access to read BOM's.

**Pull request closed without merging**
