### PR TITLE
[ADD] base: exec a start-up file in odoo-bin shell

### PR DESCRIPTION
**Pull request by lordkrandel**
A `--shell-file` option is added to the REPL to be able to "prepare" the CLI environment, giving the user a way to customize it, with every shell_interface Odoo allows.

- add out-of-the-box functions for power users
- enable more REPL driven development
- allow custom imports and prepare variables for REPL use

### CODE REVIEW

**Comment by mart-e** [comment]
What's the difference with?
```
$ python odoo-bin shell -d mydb < myscript.py
```

**Comment by lordkrandel** [comment]
I was trying to use that, but I found two major problems:

1. The interactive shell closes after reading the file from stdin.
immagine
immagine
See: https://github.com/odoo/odoo/blob/777472fad6480b0cd4b3edcaffb5bbe1d05094b2/odoo/cli/shell.py#L75
So, the input from `stdin` and the `shell` do not actually work together.
I guess this is why these flags I use exist for every REPL shell (bpython/ipython...).
immagine

2. You cannot debug
immagine

**Comment by lordkrandel** [comment]
Of course you can load the script "by hand" of course, in a different way for each kind of shell every time you run the shell...

I would personally use this for bug fixing. I generally build a script that replicates the bug and I find it very useful to do that interactively with the client data. Directly building a test would require me to first isolate the bug from the data in the db - and then running it non-interactively at each change - and the debug fails in tests.

We could also have a way to make the support team be able to develop and add a "bug replication script" to the ticket, making it objective and easy then to isolate, translate it to a test and fix it.

I'm also building some tool to bootstrap Odoo environments in a declarative way with configuration files (no docker, ansible or git-worktrees required) and being able to drop directly into the shell with a pre-loaded condition would be awesome - would make me switch from bug fix to bug fix a lot easier, especially when you get interrupted.

We are a whole lot of developers, and growing fast. I think that evolving the tooling for development/debugging would make us scale more.

**Comment by Xavier-Do** [comment]
Small suggestion:

Didn't check other reviews to be honest but I think that you could avoid adding an option in config.py by manyally adding this option to the parser in the `Shell.init()` in shell.py, before parsing the config.

```python
    def init(self, args)
        parser = config.parser
        group = optparse.OptionGroup(parser, "Shell Configuration")
        group.add_option('--shell-file', dest='shell_file', type="string",
                         help="Specify a python script to be run after the start of the shell mode.")
        
        config.parse_config(args)
```

And we could actually do the same with `shell-interface`

This will help to keep --help clean and only display those options when running odoo-bin shell --help

**Comment by lordkrandel** [comment]
> This will help to keep --help clean and only display those options when running `odoo-bin shell --help`

@Xavier-Do  I made the changes you suggested, yet the `odoo-bin <command> --help` thing looks mostly ... broken? Funny?

`odoo-bin start --help` --> Quick start specific help
`odoo-bin server --help` --> All base commandline options
`odoo-bin shell --help` --> All base commandline options + Shell options
`odoo-bin populate --help` --> All base commandline options + Populate options
`odoo-bin tsconfig --help` --> TS config specific help

**Comment by Xavier-Do** [comment]
> @Xavier-Do I made the changes you suggested, yet the `odoo-bin <command> --help` thing looks mostly ... broken? Funny?

What do you consider broken? to have all base command lines for shell and populate?

**Comment by lordkrandel** [comment]
> > @Xavier-Do I made the changes you suggested, yet the `odoo-bin <command> --help` thing looks mostly ... broken? Funny?
> 
> What do you consider broken? to have all base command lines for shell and populate?

There are a lot of funny inconsistences. _(Funny peculiar, not funny "ha-ha")_
I never use `odoo-bin start`, but I guess it accepts all the same base command line options than `odoo-bin server`, or at least some, like `-c`.

But these options are present for server and not for start.
immagine
immagine

**Comment by C3POdoo** [comment]
Dear @lordkrandel,

Thank you for your contribution but we are closing it due to inactivity.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Comment by lordkrandel** [comment]
@tfr-odoo here is an old tentative PR, what do you think?

**Pull request closed without merging**
