### PR TITLE
[FIX] mrp: update MO qty reserves components

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
- Create and confirm an MO with extra components in stock
- Update the quantity to produce

Bug:
the reserved qty is not updated (it actually is but to the previous
value if you update MO quantity multiple times)
since this [commit](https://github.com/odoo/odoo/pull/93712) moves are now assigned during the write
before the new product_uom_qty is written on them

opw-3489226

### CODE REVIEW

**Review by clesgow — COMMENTED** [review]
LGTM, got just a little nitpick. :slightly_smiling_face: 
Also, maybe it might be better to do this fix in `16.1`, since the behavior was changed in that version, and the bug exists there as well.

**Comment by HANNICHE-Walid** [comment]
@clesgow done :+1:

**Comment by clesgow** [comment]
@robodooo r+

**Comment by HANNICHE-Walid** [comment]
@clesgow there's an extra 'O' in robodoo :p

**Review by adwid — COMMENTED** [review]
As far as I know, it is not possible to multi-edit the raw SMs, ok
But still, `self` can be a recordset and in such case, the `write` will fail
It's worth adapting the method so it becomes compatible with recordsets
Something like
```diff
diff --git a/addons/mrp/models/stock_move.py b/addons/mrp/models/stock_move.py
index e9c8884333f1..6885fdbc6d2a 100644
--- a/addons/mrp/models/stock_move.py
+++ b/addons/mrp/models/stock_move.py
@@ -298,26 +298,30 @@ class StockMove(models.Model):
             # so possibly unlink lines
             move_line_vals = vals.pop('move_line_ids')
             super().write({'move_line_ids': move_line_vals})
-        if 'product_uom_qty' in vals and self.raw_material_production_id.state == 'confirmed' and not self.env.context.get('no_procurement', False):
+        old_demand = {move: move.product_uom_qty for move in self}
+        res = super().write(vals)
+        if 'product_uom_qty' in vals and not self.env.context.get('no_procurement', False):
             # when updating consumed qty need to update related pickings
             # context no_procurement means we don't want the qty update to modify stock i.e create new pickings
             # ex. when spliting MO to backorders we don't want to move qty from pre prod to stock in 2/3 step config
-            self._run_procurement(vals['product_uom_qty'], self.product_uom_qty)
-        return super().write(vals)
+            moves_create_proc = self.filtered(lambda m: m.raw_material_production_id.state == 'confirmed')
+            moves_create_proc._run_procurement(old_demand)
+        return res
 
-    def _run_procurement(self, new_qty, old_qty):
+    def _run_procurement(self, old_qties=False):
         procurements = []
+        old_qties = old_qties or {}
         to_assign = self.env['stock.move']
         self._adjust_procure_method()
         for move in self:
-            if new_qty > 0:
+            if float_compare(move.product_uom_qty, 0, precision_rounding=move.product_uom.rounding) > 0:
                 if move._should_bypass_reservation() \
                         or move.picking_type_id.reservation_method == 'at_confirm' \
                         or (move.reservation_date and move.reservation_date <= fields.Date.today()):
                     to_assign |= move
 
             if move.procure_method == 'make_to_order':
-                procurement_qty = new_qty - old_qty
+                procurement_qty = move.product_uom_qty - old_qties.get(move, 0)
                 values = move._prepare_procurement_values()
                 origin = move._prepare_procurement_origin()
                 procurements.append(self.env['procurement.group'].Procurement(
```
And actually, `_run_procurement` could even be moved in `stock`

**Comment by HANNICHE-Walid** [comment]
> As far as I know, it is not possible to multi-edit the raw SMs, ok But still, `self` can be a recordset and in such case, the `write` will fail It's worth adapting the method so it becomes compatible with recordsets Something like
> 
> ```diff
> diff --git a/addons/mrp/models/stock_move.py b/addons/mrp/models/stock_move.py
> index e9c8884333f1..6885fdbc6d2a 100644
> --- a/addons/mrp/models/stock_move.py
> +++ b/addons/mrp/models/stock_move.py
> @@ -298,26 +298,30 @@ class StockMove(models.Model):
>              # so possibly unlink lines
>              move_line_vals = vals.pop('move_line_ids')
>              super().write({'move_line_ids': move_line_vals})
> -        if 'product_uom_qty' in vals and self.raw_material_production_id.state == 'confirmed' and not self.env.context.get('no_procurement', False):
> +        old_demand = {move: move.product_uom_qty for move in self}
> +        res = super().write(vals)
> +        if 'product_uom_qty' in vals and not self.env.context.get('no_procurement', False):
>              # when updating consumed qty need to update related pickings
>              # context no_procurement means we don't want the qty update to modify stock i.e create new pickings
>              # ex. when spliting MO to backorders we don't want to move qty from pre prod to stock in 2/3 step config
> -            self._run_procurement(vals['product_uom_qty'], self.product_uom_qty)
> -        return super().write(vals)
> +            moves_create_proc = self.filtered(lambda m: m.raw_material_production_id.state == 'confirmed')
> +            moves_create_proc._run_procurement(old_demand)
> +        return res
>  
> -    def _run_procurement(self, new_qty, old_qty):
> +    def _run_procurement(self, old_qties=False):
>          procurements = []
> +        old_qties = old_qties or {}
>          to_assign = self.env['stock.move']
>          self._adjust_procure_method()
>          for move in self:
> -            if new_qty > 0:
> +            if float_compare(move.product_uom_qty, 0, precision_rounding=move.product_uom.rounding) > 0:
>                  if move._should_bypass_reservation() \
>                          or move.picking_type_id.reservation_method == 'at_confirm' \
>                          or (move.reservation_date and move.reservation_date <= fields.Date.today()):
>                      to_assign |= move
>  
>              if move.procure_method == 'make_to_order':
> -                procurement_qty = new_qty - old_qty
> +                procurement_qty = move.product_uom_qty - old_qties.get(move, 0)
>                  values = move._prepare_procurement_values()
>                  origin = move._prepare_procurement_origin()
>                  procurements.append(self.env['procurement.group'].Procurement(
> ```
> 
> And actually, `_run_procurement` could even be moved in `stock`

**Comment by adwid** [comment]
robodoo r+

**Pull request closed without merging**
