### PR TITLE
[IMP] social_media, *: add snapchat to the social networks

### PR DESCRIPTION
**Pull request by rahg-odoo**
*: mass_mailing, mass_mailing_themes, website,
website_blog, website_event, website_mass_mailing

This commit introduces support for Snapchat as a new social network
within the application. Users of the Website platform can now link
their Snapchat profiles to their websites. Additionally, this update
includes modifications to templates and the social media section to
seamlessly integrate Snapchat alongside existing networks.

task-422304

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by msh-odoo — COMMENTED** [review]
In tour ```snippet_social_media``` We need to add snapchat icon like we add other icons.

**Comment by rahg-odoo** [comment]
> In tour `snippet_social_media` We need to add snapchat icon like we add other icons.

We will wait till another PR which merges threads in social icons has made similar changes in tours. so whichever PR merges later has to changes again.

**Comment by msh-odoo** [comment]
> > In tour `snippet_social_media` We need to add snapchat icon like we add other icons.
> 
> We will wait till another PR which merges threads in social icons has made similar changes in tours. so whichever PR merges later has to change again.
> 
> Edit: I will add snapchat icon part in tour.

@rahg-odoo I reviewed the existing tour and the modified steps tests the feature we added, so no need to do anything, sorry for the inconvenience.

**Review by tde-banana-odoo — APPROVED** [review]

**Review by bvr-odoo — CHANGES_REQUESTED** [review]
Hello @rahg-odoo 
Thanks for your PR, good work 👍🏼 
Just a few small remarks and questions for the PO.

**Comment by bvr-odoo** [comment]
@rahg-odoo 
At the end, this task will be probably canceled because we decided to change the specs concerning the social media snippet. So you can leave it as it is. Thanks.

**Comment by bvr-odoo** [comment]
the social snippet will change (see task 4297366)

**Pull request closed without merging**
