### PR TITLE
[FIX] sale_timesheet: allow billing user in journal entries

### PR DESCRIPTION
**Pull request by Julien00859**
Wrong permission was set on billing user, they are allowed to read.

opw-2001421

### CODE REVIEW

**Comment by jem-odoo** [comment]
Expand commit message with 
"Since a timesheet is an analytic line, access rights are mixed for timesheet manager and 
billing user, when hr_timesheet is installed. Group mecanism use logical 'OR' between 
none global rules, so timesheet access restrict the one of billing user.
The ir.rule of sale_timesheet tries to restore the access of billing user (which can thus 
modified timesheet. This point is unfixable, unfortunately). 
This commit completely restore (even for 'read' access) the rule for billing user, otherwise 
such user can not validate an invoice if they are timesheet user."
Then, it's ok ;)

**Comment by Julien00859** [comment]
Thank you for the complete explanation :+1: I change that message

**Comment by jem-odoo** [comment]
@robodoo r+

**Comment by Julien00859** [comment]
robodoo retry

**Pull request closed without merging**
