### PR TITLE
11.0

### PR DESCRIPTION
**Pull request by MathAndrews**
…ath when browsing a website in a language other than the default language

**Description of the issue this PR addresses:**
When accessing a custom website page (I don't is this accure with odoo website page or portal page) in a language different than the default website language, the path is encode/decode twice

When you get the path value:  [`path = request.httprequest.path.split('/')`](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py#L358) you call this method in the [werkzeug BaseRequest class](https://github.com/pallets/werkzeug/blob/fef09eb909d1dd2afddb339ff1ceb2ca45df40f8/src/werkzeug/wrappers/base_request.py#L534) :

```py
def path(self):
        """Requested path. This works a bit like the regular path
        info in the WSGI environment but will always include a leading slash,
        even if the URL root is accessed.
        """
        raw_path = _wsgi_decoding_dance(
            self.environ.get("PATH_INFO") or "", self.charset, self.encoding_errors
        )
        return "/" + raw_path.lstrip("/")
```

which is using the [method _wsgi_decoding_dance](https://github.com/pallets/werkzeug/blob/fef09eb909d1dd2afddb339ff1ceb2ca45df40f8/src/werkzeug/_internal.py#L107) : 

```py
def _wsgi_decoding_dance(s, charset="utf-8", errors="replace"):
    return s.encode("latin1").decode(charset, errors)
```

So as you can see there is encoding apply on URL path.

Now, let's look a the values during the process:
1. The first time you enter `_dispatch` the value of `request.httprequest.environ['PATH_INFO']` is `/fr_FR/test/Ã¤`,
2. Then when you get the path (via `request.httprequest.path`), where it apply `encode("latin1").decode("utf-8", "replace")` on `request.httprequest.environ['PATH_INFO']` and you get the value `/fr_FR/test/ä`,
3. Then, as we have a language set in the URL, you go in the method [`reroute`](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py#L404) where you set `request.httprequest.environ['PATH_INFO']` with a the path; without the language; already encoded/decoded (`/test/ä`),
4. Then you go back in  the method `_dispatch` where the value of  `request.httprequest.environ['PATH_INFO']` is now `/test/ä`
5. You get the path (via `request.httprequest.path`) where it apply `encode("latin1").decode("utf-8", "replace")` on `request.httprequest.environ['PATH_INFO']` and you get the value `/test/�`,

So on the final path you have applied `encode("latin1").decode("utf-8", "replace")` twice.

That's why, I think, you have to do the inverse of this `encode("latin1").decode("utf-8", "replace")` when setting the value of `request.httprequest.environ['PATH_INFO']` in the method `reroute` [line 412](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py#L412)

**Current behavior before PR:**
When you access to the page in the default language: /test/ä:
If you display the value in the webpage the value is: `ä`

When you access to the page with a other language than the default: /fr_FR/test/ä
If you display the value in the webpage the value is: `�`

**Desired behavior after PR is merged:**
The value must be the same despite the language used to visite the website

I've create a issue about this issue: https://github.com/odoo/odoo/issues/55621

Best regards,
M.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MathAndrews** [comment]
Hi,

During covid lock down, I use my personnal computer to work from home, and it use the email from the office on the commit, how can I change that, or change the CLA?

Best regards

M.

**Comment by MathAndrews** [comment]
Hi,
Any news? Why is the merging is blocked?

Best regards,
M.

**Comment by xmo-odoo** [comment]
@mart-e CI seems fine, all it needs is somebody to review & approve the PR.

**Comment by xmo-odoo** [comment]
@MathAndrews you linked to the werkzeug master source (I assume), but 11.0 used an older version and IIRC while we intended to run it on P3 we also tried to keep P2 working to ease transition (as it was the first version to even support p3).

Would you mind using the P2/P3 code from [pre-1.0 versions](https://github.com/pallets/werkzeug/blob/0.11.15/werkzeug/_compat.py) and gating them behind a pycompat version flag?

**Comment by C3POdoo** [comment]
Dear @MathAndrews,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
