### PR TITLE
[FIX] delivery_*: handle user-made delivery methods

### PR DESCRIPTION
**Pull request by Elkasitu**
this is hot garbage

### CODE REVIEW

**Comment by jem-odoo** [comment]
Not sure it is a good idea to unlink the carrier, since there are some fields Many2one pointing "delivery.carrier". It may recompute some field and make unconsistent sale.order.line amount, ... Moreover there is a property field on res.partner for the carrier.
I let @rim-odoo and @sle-odoo give their input, since they are the babysitters of this module ;)

**Comment by Elkasitu** [comment]
@jem-odoo it could just reset the delivery_type to the default as a less intrusive measure

**Comment by rim-odoo** [comment]
Yes, I would reset the `delivery_type` of the carrier to `fixed` since it is the only value we will always have.

If people have already validated their SO, the delivery price is already computed and fixed in one SOL.
If not, they probably won't get 0 as delivery price and they will ask themselves why :)

**Comment by pimodoo** [comment]
Hello, I've just tested your branch, and it seems that the carrier is still deleted, even if you just change the delivery_type. Did I missed something?

**Comment by Elkasitu** [comment]
@pimodoo The carriers introduced by delivery_* are supposed to be deleted, it's the current behavior, this fix only targets user-added carriers that use a `delivery_type` introduced by the module to be uninstalled.

i.e., to reproduce: install delivery_fedex, go to delivery methods, create, delivery_type -> fedex, save, uninstall delivery_fedex, go to delivery methods: the one you created should still exist, but its delivery_type should be `fixed`

**Comment by Elkasitu** [comment]
Btw, this should be a solution for stable only... but idk how to fix it in master, maybe make `delivery_type` a m2o? this way we can `ondelete='cascade'` it

**Comment by rim-odoo** [comment]
@Elkasitu for stable, a m2o won't fix the problem but only hiding it... we should check with @rco-odoo what is the desired behaviour for modules that uninstall values from selection fields

**Comment by pimodoo** [comment]
@Elkasitu Ok, perfect for me. If it's ok for @jem-odoo you can merge.

**Comment by Elkasitu** [comment]
After a discussion with @rim-odoo and @rco-odoo we determined that https://github.com/odoo/enterprise/pull/1752 was the best course of action to fix this bug in stable.

**Pull request closed without merging**
