### PR TITLE
[FIX] web_editor: some v13 fixes from task 2115528

### PR DESCRIPTION
**Pull request by Gorash**
opw-2115528

### CODE REVIEW

**Comment by Gorash** [comment]
@sbuhl no, some fixe/improvement. See the picture link in the task.

[FIX] web_editor: color-picker: see selected color below toolbar button
[FIX] web_editor: can change/add an icon/image in a button
[IMP] web_editor: allow the user to choose a custom font size
[FIX] web_editor: add a button/icon to add custom color in colorpicker

**Comment by sbuhl** [comment]
@Gorash Sorry, I'm tired, didn't see the commits... 
For [IMP] web_editor: allow the user to choose a custom font size, I'd rather do in master.

cc: @qsm-odoo @JKE-be

**Comment by dmo-odoo** [comment]
@Gorash:
- "color-picker: see selected color below toolbar button": It works for the font color button, but not for the font background color one. I would expect both buttons to work in the same way.
- "can change/add an icon/image in a button": I don't understand the code this commit introduces because I am not familiar with summernote, so I am unable to review it properly.
- "allow the user to choose a custom font size": I agree with @sbuhl that this should not be done in master.
- "add a button/icon to add custom color in colorpicker": this one is fine by me.

cc @qsm-odoo @JKE-be

**Comment by qsm-odoo** [comment]
@sbuhl I am closing this PR. If necessary you can mention it in a master task, but this would probably be about master work for the editor team in a few months anyway..?

- "Colorpicker selected color": already fixed in 13.0 and working in 14.0 too
- "can change/add an icon/image in a button": seems to already work on my side for changing and for the ability to add, it should be a master task IMO
- "allow the user to choose a custom font size": master for sure
- "add a button/icon to add custom color in colorpicker": the UI is bad in 13.0 but working. Not worth the risk breaking custo while fixing it, especially since it is nice in 14.0.

Anybody feel free to reopen and merge if I am wrong :+1:

**Pull request closed without merging**
