### PR TITLE
[FIX] Accounting dashboard, fixes the awaiting ammount to pay in Payments to do

### PR DESCRIPTION
**Pull request by BeAntares**
**Description of the issue/feature this PR addresses:** This patch fixes issue #18217.
In the Accounting Dashboard, the Vendor Bills Card shows the total amount to pay (including the down payments) from the Vendor Bills still open, but it should only show the total remaining amount to pay.

**Current behavior before PR:** When partial payments are performed on vendor bills, the Accounting dashboard shows the total amount to pay including the quantity already paid instead of the remaining amount to pay.

**Desired behavior after PR is merged:** The dashboard will show the awaiting amount to pay instead of the total amount of the open vendor bills in the section "Payments to do".

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by BeAntares** [comment]
@celm1990 @bfotop

**Comment by celm1990** [comment]
@BeAntares, field must be residual, not residual_signed, because in [this line ](https://github.com/odoo/odoo/pull/19047/files#diff-c5fd30daf92adca0dff096c36d7213a4R193) is multiplicate for signed if is refund. Please correct.

**Comment by danger89** [comment]
@BeAntares, no fix?

**Comment by raycarnes** [comment]
This looks like it is trying to address the same issue that I suggested a PR for at https://github.com/odoo/odoo/pull/25859

**Comment by pedrobaeza** [comment]
Yes, but as stated in it, this is not going to be fixed on stable, as it's a change of behavior, which goes against stability policy, but it's already solved in master, so I'm closing this.

**Pull request closed without merging**
