### PR TITLE
[13.0][IMP] base: Compute context_timestamp when use widget date with datetime...

### PR DESCRIPTION
**Pull request by carlosdauden**
… field to get day correctly.

I know that the problem may be more of a bug in the babel library than an odoo bug, but with this small change we have the problem solved.

@Tecnativa TT35580

--
I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

Forward port https://github.com/odoo/odoo/pull/63559

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Gorash can you please give your opinion on this?

**Comment by Gorash** [comment]
Hello,
Is there a way to add a test?
Did you also look at the `ir.qweb.field.datetime` model?

**Review by Julien00859 — CHANGES_REQUESTED** [review]
There is still no unittest

**Comment by abirslh** [comment]
This commit solve the problem of displaying correct date from datetime field in qweb using date widget.
I have tested it and it works, just waiting for it to be merged. 
Thank you for your understanding.

**Comment by Julien00859** [comment]
Hello @abirslh, our policy is that we only merge critical bug fixes/security fixes into the 13.0 branch. The branch is soon end-of-life and a bad patch would impact too many customers.

I do trust you that you effectively did test your code to ensure that it works. Still, just testing the code manually doesn't meet our standards: there needs to be an automated test. As your fix will be deployed to all newer versions (14, 15, master) the automated test will make sure that we effectively fix the bug in all versions.

The automated test also enriches the diff with precise steps on how to reproduce the bug. As I am not a QWeb expert, I need precise steps on how to reproduce the bug (e.g. in the commit message or better via a test) so that I can learn QWeb thanks to your contribution and provide an useful review. Maybe even validate the fix myself and merge it.

If you do not know how to write such tests, let me know, I'll take care of it. It'll takes me more time than you doing it though.

**Pull request closed without merging**
