### PR TITLE
[IMP] l10n_it_edi: demo data for electronic invoicing works with IT c…

### PR DESCRIPTION
**Pull request by jco-odoo**
…ompany

Before it was only done on MyCompany, but interferes easily
with other demo data.  Better for the Italian localization
to try the demo immediately in IT Company.

We also added an Italian demo partner, so it is clear
which one can work immediately.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
you checked the nightly won't be broken because of this change ?

**Comment by jco-odoo** [comment]
@qdp-odoo I checked and fixed and then checked and there is indeed something else to check (a test in delivery fails...)

**Comment by jco-odoo** [comment]
@qdp-odoo I was talking about the fw-port of DDT.  This one does not give any errors in the l10n builds.

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
