### PR TITLE
[IMP] hr_timesheet: add pivot view in my timesheet

### PR DESCRIPTION
**Pull request by padh-odoo**
Improve added pivot view for my timesheet in the timesheet app.
- Before this commit there was no pivot view for my timseet in timesheet app.
- In this commit pivot view is added or my timseet in timesheet app.

Task-3479322

### CODE REVIEW

**Review by pkyriakou — COMMENTED** [review]
Thank you @padh-odoo for your changes. 
LGTM :100:

**Review by auon-odoo — APPROVED** [review]

**Comment by xavierbol** [comment]
Can you change the task id reference in your commit message? 
```diff
- Task-: 3479322
+ Task-3479322
```

Thanks in advance!

Apart of that, LGTM. 🙂

**Comment by padh-odoo** [comment]
> Can you change the task id reference in your commit message?
> 
> ```diff
> - Task-: 3479322
> + Task-3479322
> ```
> 
> Thanks in advance!
> 
> Apart of that, LGTM. 🙂

**Comment by xavierbol** [comment]
robodoo r+

**Comment by xavierbol** [comment]
I just rebase your branch since it was not up to date.

**Pull request closed without merging**
