### PR TITLE
merge to first matching orderline with cla

### PR DESCRIPTION
**Pull request by johr**
Description of the issue/feature this PR addresses:
more efficient iteration to get the orderline to add the product to

Current behavior before PR:
iterating from orderlines start till the end taking the last matching one

Desired behavior after PR is merged:
iterating starting from the end of the orderlines, taking the first matching

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@johr because you committed via github, the email set on your commit is the "primary email" you've configured there which is <your first name>.<your last name><at>drei<dot>at. The CLA check uses the email of the commit author, so not your gmx address.

To fix that, either CLA to the address on your github account, or retrieve the branch locally and rewrite it with your gmx address at author (e.g. "git commit --amend --reset-author" assuming your local git user uses the gmx address) and possibly update the primary address on github to avoid such future mishaps.

**Comment by mart-e** [comment]
I am not sure to understand the purpose of this issue? It is only to be more efficient? You noticed some downtime? Why not keep the loop and just change the order?

To check with Xaviers comment regarding CLA

**Comment by johr** [comment]
thx for clearfying @xmo-odoo . came accross this issue when working with 10.0 branch. there always the last orderline (if matched) was considered. so i changed to find the last matching orderline with the find() function. 
in the meantime this was changed in master to take a matching orderline (not only checking the last one). Fine. 
But with a full iteration without stopping if a matching orderline was found.
So the change would be to check starting from the end and stopping if found compared to starting from the beginning and not stopping if found.

**Comment by mart-e** [comment]
The merge mechanism was improved at e82a9ae0e1588799cb9bbe9062ef79cf8711b016

**Pull request closed without merging**
