### PR TITLE
[Fix] 10.0 account data not idempotent on repetitive execution

### PR DESCRIPTION
**Pull request by luisiniguezh**
Description of the issue/feature this PR addresses: unlinks the records before inserting the data on `line_ids` related to https://github.com/odoo/odoo/issues/24454

Current behavior before PR: 
On the same database, if I execute tests twice, I get the following trace back: 
```
<<<< odoo.tools.convert.ParseError >>>>
Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 339, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 855, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 925, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 806, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo/tools/convert.py", line 809, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 717, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1190, in _update
    record.write(values)
  File "/opt/odoo/odoo/models.py", line 3570, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3734, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 1087, in _validate_fields
    check(self)
  File "<decorator-gen-146>", line 2, in _check_lines
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/addons/90-odoo-cc/account/models/account_invoice.py", line 1449, in _check_lines
    raise ValidationError(_('A Payment Term should have only one line of type Balance.'))
ParseError: "A Payment Term should have only one line of type Balance.
None" while parsing /opt/odoo/addons/90-odoo-cc/account/data/account_data.xml:28, near
<record id="account_payment_term_15days" model="account.payment.term">
            <field name="name">15 Days</field>
            <field name="note">Payment term: 15 Days</field>
            <field name="line_ids" eval="[(0, 0, {'value': 'balance', 'value_amount': 0.0, 'sequence': 500, 'days': 15, 'option': 'day_after_invoice_date'})]"/>
        </record>
```

Desired behavior after PR is merged: the tests should be capable of running more than once on the same db

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
You could have cherry-picked https://github.com/odoo/odoo/commit/dbe6aa4292dc3190987855f4b59a737503d1f7f6.

**Comment by luisiniguezh** [comment]
@mreficent right, should I close this PR and create a new one with the cherry-pick?

**Comment by mreficent** [comment]
I think you can drop your commit, cherry-pick the other and force push, all in the same branch, if you know how to do it... 😏

**Comment by luisiniguezh** [comment]
@mreficent done, dropped my commit and cherry-picked dbe6aa4292dc3190987855f4b59a737503d1f7f6 it doesn't look so clean because I had to fix conflicts

**Comment by mreficent** [comment]
I would do fetch of odoo v10 and a rebase and a new push to delete that "merge pull" commit. Also, I wouldn't change the field note contents.

**Comment by luisiniguezh** [comment]
I'll close this one and start from scratch on another PR

**Pull request closed without merging**
