### PR TITLE
[FIX] base: don't break search in m2m with an empty right hand side

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
As requested by @rco-odoo in https://github.com/odoo/odoo/pull/30121#pullrequestreview-299446070.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
ping: @mart-e

**Comment by rco-odoo** [comment]
@robodoo r-

**Comment by rco-odoo** [comment]
@mreficent can you squash both commits?
You can use the [co-authorship trick](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) to make @hbrunn and yourself as co-authors.

**Comment by mreficent** [comment]
Ok, I will do that way when v11 branch is green.

**Pull request closed without merging**
