### PR TITLE
[FIX] mrp: prevent MO creation with the same component as product to produce

### PR DESCRIPTION
**Pull request by DjamelTouati**
Steps to reproduce the bug:
- Create a storable product “P1”
   - Add a BOM
   - Try to add the product P1 as a component > save > validation error is triggered
	>  it's not possible to add the same component as the product to produce > correct behavior

- Create a manufacturing order:
    - Select the product “P1” as product to produce
    - Add the product “P1” as component
    - save

Problem:
no validation error is triggered, It's possible to create a MO in which the final product is included in the component > wrong behavior

opw-2796750

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by DjamelTouati** [comment]
@amoyaux when we want to produce “Product A”, we’re not supposed to use “Product A” as a component. A validation error should be raised but is not the case at the moment, so wrong behavior.

What do you think ?

**Comment by wtaferner** [comment]
@amoyaux 
As far as I understand we would have a **hen egg problem** resulting from not being stopped to produce such a configuration manually 😉

**Comment by amoyaux** [comment]
I was thinking about usecase with yeast for example. But it's not working for valuation atm so let block it

**Comment by amoyaux** [comment]
robodoo r+

**Comment by chowbryan** [comment]
@DjamelTouati Hello! I have a customer who has a unique use case where this validation error interrupts their business flow. 
opw-281818 

In summary, they use the same product as a component to relabel an existing lot into a new lot name (per regulations). *The reason for using MOs is because they also use quality checks. 

Could you think of a way to include this use case in another fix? Thanks!

**Comment by wtaferner** [comment]
@chowbryan 
As it is an own and isolated method, it should be easy for you to overwrite and neutralize this constraint, right?

From a logical point of view anything which is processed in a MO will result in a new product...in your case...Product A (unchecked/unlabeled) -> Product A (checked/labeled).

I have customers processing basically the same component multiple times and as you need to know in which stage your product is, you need a product for each stage even if you could simplify as you do with an own lot/serial stem which is IMO not the best recommendation to handle such a use case especially not if you want to automate further at some point.

**Pull request closed without merging**
