### PR TITLE
[FIX] survey: replace fonts with unclear license

### PR DESCRIPTION
**Pull request by d-fence**
In ae4435af, two fonts were added without a clear licensing.
With this commit, they are replaced with more recent and better fonts
with a clear OFL licence.

### CODE REVIEW

**Review by edi-odoo — CHANGES_REQUESTED** [review]
Replace Trueno Extrabold with Bold, otherwise LGTM. Thanks !

**Comment by d-fence** [comment]
robodoo r+

**Comment by awa-odoo** [comment]
Hello @d-fence @edi-odoo 

I was pinged on this PR:
https://github.com/odoo/odoo/pull/99799

Apparently some of the fonts chosen as replacement do not handle Vietnamese characters very well (see attached images in PR description).

They suggested a replacement, can you give it a look?

Thanks!

**Comment by Ngquang** [comment]
@awa-odoo oh my teammate just closed the PR. Can you re-open it? 
Thanks man.

**Pull request closed without merging**
