### PR TITLE
Add support for rcfile folders

### PR DESCRIPTION
**Pull request by blaggacao**
Closes https://github.com/odoo/odoo/issues/22572
I can imagine 1000 better ways to implement this, but it just would do the job for an undocumented feature...

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by blaggacao** [comment]
@odony This way of organizing config files is kind of more suitable (eg. mix and match staging, dev and production) NOt sure if the implementation is perfect, but it suits the use case as an undocumented feature...

**Comment by odony** [comment]
Not for stable, please keep in mind the [suitable target branches](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch) for feature requests ;-)

Might be a thing to consider for @rco-odoo, @Elkasitu and @amigrave while we discuss the revamping of odoo-bin parameters.

**Comment by blaggacao** [comment]
I've tooling in place by now, from now on the automated workflow goes to master ;-) sry, will not happen again. :smile:

**Comment by blaggacao** [comment]
@odony As discussed here with @sbidoul such config API would lead us out of this dead end:
https://github.com/acsone/odoo-bedrock/issues/3

**Comment by nhomar** [comment]
@blaggacao This kind of changes must be done on master.

**Comment by blaggacao** [comment]
@nhmar You're right, would you support it? I might prepare a proper PR in a minute...

**Comment by nhomar** [comment]
make the PR properly first.

**Pull request closed without merging**
