### PR TITLE
WARN on m2m index name truncation

### PR DESCRIPTION
**Pull request by gurneyalex**
As requested by @antonylessuisse on #2780, add a WARNING log message when a
truncation is detected.

### CODE REVIEW

**Comment by gurneyalex** [comment]
So... It seems that there are  number of cases in stable where the warning triggers... I guess this means the patch won't be merged in 8.0 (cc @antonylesuisse @odony @Yenthe666)

**Comment by Yenthe666** [comment]
@gurneyalex hmm that is not a good thing, that probably won't get merged in 8.0 I guess :sob: 
Perhaps it can be added in V9.0 though.

**Comment by odony** [comment]
Indeed, in 8.0 we would get warnings in every build, not a good trade-off for a minor developer-friendly improvement. If you're still interested into having the warning, you could rework the patch to only output it when there is actually a collision.

For example the name of the generated m2m table `export_many2many_export_many2many_other_rel`is long enough to be risky, but the generated columns names (`export_many2many_id` and `export_many2many_other_id`) are "short" enough that the indexes stay unique (by 2 chars):
 - `export_many2many_export_many2many_other_rel_export_many2many_id`
 - `export_many2many_export_many2many_other_rel_export_many2many_ot`

Still looks ugly but no real damage is done until you really cross the 63 limit.
That should get builds green and only output the warning when the system is actually going to crash.

You might also want to make the warning message more specific (columns names do matter) and omit the syntax which differs in old and new API, e.g.:

> Creation of m2m table %s would fail because automatic index names are too long.
> Please specify explicit short names for the m2m table and columns in the m2m field
> declaration (see m2m documentation)

Thanks!

**Comment by gurneyalex** [comment]
@odony I've updated the patch following your advice:

* It now checks if both indices would have the same name and raises an explicit `ValueError` with the message you suggested
* I added an automated test (I had to add a `cr.commit()` in there to avoid a Warning on a missing ACL)

I'll update the master branch patch #7620 with this.

**Comment by tivisse** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards

**Comment by antonylesuisse** [comment]
I think it's still relevant.

**Comment by mart-e** [comment]
If this is still relevant let's create new one targeting master, no need to keep a PR targeting 8.0 open

**Comment by pedrobaeza** [comment]
Yes, this is still happening. See for example https://github.com/OCA/openupgradelib/pull/173

**Pull request closed without merging**
