### PR TITLE
[FIX] web: pivot reset groupBy filter

### PR DESCRIPTION
**Pull request by abla001**
To reproduce
============
- on any app with pivot view
- set a groupBy, then remove it it doesn't bring back the default display

Problem
=======
when removing the groupBy filter, we take last groupBy value instead of the initial ones

Solution
========
use `initialRowGroupBys` when `params.groupBy` is empty

opw-3215313

### CODE REVIEW

**Comment by abla001** [comment]
@aab-odoo can you take a look at this fix please ?

**Comment by abla001** [comment]
@odoo/rd-framework-js

**Comment by ged-odoo** [comment]
@Polymorphe57

**Comment by abla001** [comment]
@Polymorphe57 thank you for the feedback :pray:, I'm closing a ticket and leaving a feedback for RD team to see if they can do anything on master

**Pull request closed without merging**
