### PR TITLE
[FIX] base_vat: Regex need 'br' insted only 'r' now on python3

### PR DESCRIPTION
**Pull request by nhomar**
Description of the issue/feature this PR addresses:

On python3 this feature is failing in Mexico environment check.

Current behavior before PR:

Just installing l10n_mx_reports the error appears.

Desired behavior after PR is merged:

No error installing demo data.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
Please retarget to saas-17.

And since all lines of the RE are being touched, would you mind converting this to a triple-quoted string and using the `re.VERBOSE` flag?

**Comment by nhomar** [comment]
@xmo-odoo This has 7 years serving fine like this.

do you think it add any value change something there?

image

**Comment by nhomar** [comment]
I can, it is just a Question BTW.

**Comment by xmo-odoo** [comment]
Don't really care, just saw the occasion.

**Comment by nhomar** [comment]
can you merge it as it is and you have my word I will celan that up for the next version after saas-18?

**Comment by nhomar** [comment]
@xmo-odoo retargeted here: https://github.com/odoo/odoo/pull/19490

**Pull request closed without merging**
