### PR TITLE
[FIX] crm: fix lead restore

### PR DESCRIPTION
**Pull request by jvnm-dev**
## Issue

- Install CRM
- Open a lead
- Mark as lost
- Restore

Traceback: _compute_probabilities doesn't exists.

## Cause

In 9ac5f42c, we backport toggle_active who uses
_compute_probabilities but we don't have this method in v13.

This commit (9ac5) is a backport of PR #42015 where the
_compute_probabilities is missing too, so the issue is in master too.

## Solution

Manually import the method from [fle PR onchange to recompute](https://github.com/odoo/odoo/pull/38956/files#diff-7554cb87ef8f09ec1851ce35014b2721R218).

OPW-2163251

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
Hello @tde-banana-odoo, what do you think of this?

**Comment by tde-banana-odoo** [comment]
Indeed. However I think we should simply call update_probabilities. Will do another PR.

**Comment by tde-banana-odoo** [comment]
See https://github.com/odoo/odoo/pull/42573

**Comment by jvm-odoo** [comment]
Thanks!

**Pull request closed without merging**
