### PR TITLE
[FIX] requirements.txt: make Odoo installable for Python >= 3.8

### PR DESCRIPTION
**Pull request by dreispt**
# Description of the issue/feature this PR addresses:

Odoo installation in a Python >= 3.8 environment

# Current behavior before PR:

Odoo `pip install -r requirements.txt` errors

# Desired behavior after PR is merged:

Odoo `pip install -r requirements.txt` is successful

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dreispt** [comment]
For Pillow version compatibility, see https://pillow.readthedocs.io/en/latest/installation.html#python-support

**Comment by d-fence** [comment]
I 'm sorry to say that Odoo 11.0 is not supported anymore.
Moreover, Odoo 11.0 was not intended to run with Python 3.9.
A custom requirements.txt can be easily  used as a wrokaround I think.

**Comment by dreispt** [comment]
I'm aware that is is not supported anymore.
But merging this would have no impact whatsoever in existing installations, and would make life easier for anyone still dealing with these versions.

Thank you for considering this.

**Comment by C3POdoo** [comment]
Dear @dreispt,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
