### PR TITLE
[CLA] sign CLA for Okia SPRL

### PR DESCRIPTION
**Pull request by sylvainvh**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Thank you for the signature !

@robodoo r+

**Comment by sylvainvh** [comment]
Hello @mart-e , I made a mistake. I would like to create some PR into the v10. Do I need to recreate a new PR with the CLA for v10 ?

**Comment by mart-e** [comment]
Yes, please, you can backport in 10.0 and make a new PR.

If you are going to target the 10.0, please be sure to carefully read our [stability guidelines](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean). The 10.0 being in end of life (last year of support), we are even more strict about it and accept only critical bug fixes (no view improvement or change of behaviour).

**Comment by sylvainvh** [comment]
Hi @mart-e , thank you for you answer. I created a new MR for the v10 https://github.com/odoo/odoo/pull/28493

**Pull request closed without merging**
