### PR TITLE
13.0 opw 2332763 fix agr

### PR DESCRIPTION
**Pull request by agr-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@simongoffin Hello, could you please review this? I'm not so much familiar with landed costs theory so I don't really want to mess up the accounting

**Review by simongoffin — APPROVED** [review]

**Comment by simongoffin** [comment]
robodoo delegate+

**Comment by agr-odoo** [comment]
@robodoo r+

**Comment by agr-odoo** [comment]
@robodoo rebase-ff

**Comment by agr-odoo** [comment]
@robodoo r+ method=rebase-ff

**Comment by agr-odoo** [comment]
@simongoffin well, at least I tried

**Comment by simongoffin** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
