### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by pro-odoo**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/a4f22e468 [REL] 17.4.0-alpha.6 Task: 0
https://github.com/odoo/o-spreadsheet/commit/6c4a8e756 [IMP] pivot: select pivot cells in composer Task: 3899474
https://github.com/odoo/o-spreadsheet/commit/8a35866fe [REF] pivot: extract building pivot formula Task: 3899474
https://github.com/odoo/o-spreadsheet/commit/ee21f068a [REF] pivot: unify return pivot cell from position Task: 3899474
https://github.com/odoo/o-spreadsheet/commit/ccbb76fa9 [REF] pivot: introduce pivot measure header cell Task: 3899474
https://github.com/odoo/o-spreadsheet/commit/64cd93a46 [FIX] pivot: support empty date Task: 3989717
https://github.com/odoo/o-spreadsheet/commit/786a0f51b [IMP] documentation: improve commands documentation Task: 3989757
https://github.com/odoo/o-spreadsheet/commit/98ecfd485 [IMP] charts: add chart type picker popover Task: 3978202
https://github.com/odoo/o-spreadsheet/commit/679e56a3b [IMP] charts: add doughnut chart Task: 3978202
https://github.com/odoo/o-spreadsheet/commit/1016a5de9 [IMP] charts: introduce population pyramid chart Task: 3978202
https://github.com/odoo/o-spreadsheet/commit/2ae0923f1 [IMP] charts: introduce horizontal bar chart Task: 3978202
https://github.com/odoo/o-spreadsheet/commit/882e4a10b [IMP] tests: charts_component performances Task: 3978202
https://github.com/odoo/o-spreadsheet/commit/d1d753c15 [IMP] charts: decouple model and panel chart type Task: 3978202
https://github.com/odoo/o-spreadsheet/commit/bc98f58d4 [FIX] pivot: don't crash whole pivot if aggregator in error Task: 3977814
https://github.com/odoo/o-spreadsheet/commit/52a38d786 [FIX] evaluation: spill blocked array formula Task: 3986897
https://github.com/odoo/o-spreadsheet/commit/ac1c25b9e [IMP] charts: improve `stacked` checkbox label Task: 3978443
https://github.com/odoo/o-spreadsheet/commit/1d3fe5008 [IMP] tables: add test for header inserted next to table Task: 0
https://github.com/odoo/o-spreadsheet/commit/7a7363073 [FIX] ComposerStore: missing previous range Task: 3972392
https://github.com/odoo/o-spreadsheet/commit/83b74205f [IMP] clipboard: paste conditional format, data validation & merge content when original content is deleted Task: 3597039
https://github.com/odoo/o-spreadsheet/commit/58d3a5c45 [IMP] pivot: add menu item to fix formulas Task: 3987157
https://github.com/odoo/o-spreadsheet/commit/324712899 [MOV] bottom_bar: move bottom bar components to folder Task: 0
https://github.com/odoo/o-spreadsheet/commit/cf142df40 [FIX] formula: fix LOGEST/LINEST descriptions

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by pro-odoo** [comment]
robodoo fw=no

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Comment by rrahir** [comment]
robodoo rebase-ff

**Comment by pro-odoo** [comment]
robodoo rebase-merge

**Comment by rrahir** [comment]
robodoo r+

**Pull request closed without merging**
