### PR TITLE
[I18n] fleet: make fleet state translatable and update source terms

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Make fleet states translatable

Current behavior before PR: The states cannot be translated.

Desired behavior after PR is merged: Stated (and the demo data) can be translated.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@tivisse I think this is another one for you? 
CC @Julien00859 - this one was also reported in 1908220 by Erwin.

**Comment by Yenthe666** [comment]
Thank you @nim-odoo! Do you have any idea when the source terms for all the languages are also updated? So we can translate them in Transifex.

**Comment by nim-odoo** [comment]
As soon as @mart-e is back :)

**Comment by Yenthe666** [comment]
Gotcha, I guess we'll need to wait and sit back three weeks while he's drinking beers 😉 Thanks for the feedback.

**Comment by mart-e** [comment]
> Do you have any idea when the source terms for all the languages are also updated? So we can translate them in Transifex.

If you modify the .pot, Transifex is supposed to watch it and detect the changes. So nothing to do !

**Pull request closed without merging**
