### PR TITLE
[FIX/IMP]mail:Add 'Read Messages' list in 'Discuss' page

### PR DESCRIPTION
**Pull request by cysnake4713**
Read Messages is very important, this one is missing for too long

### CODE REVIEW

**Comment by cysnake4713** [comment]
It will look like this

**Comment by dansanti** [comment]
+1

**Comment by jbofill** [comment]
+1

**Comment by mart-e** [comment]
Hello,

Sorry for the late reply.
While I agree the feature looks nice, this is still a new feature that can not be added in [stable version 
](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch).
Feel free to resubmit a new patch on master (which has changed quite a bit since) and I promise we will take less than two years to review :wink:

**Pull request closed without merging**
