### PR TITLE
[FIX] delivery: only update not yet processed pickings based on the n…

### PR DESCRIPTION
**Pull request by agr-odoo**
…ew carrier

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by wtaferner — APPROVED** [review]
Thx :-)

**Comment by agr-odoo** [comment]
@pimodoo 
Hi, this is the missing commit from https://github.com/odoo/odoo/pull/73479

**Comment by wtaferner** [comment]
@pimodoo 
Would be cool if you have time for the magic words 😉

**Comment by wtaferner** [comment]
@pimodoo 
I think it would be nice if you could give it a go 😉 but I try to tease @robodoo r+

**Pull request closed without merging**
