### PR TITLE
[IMP] l10n_eu_oss: Restore pre covid rates on Luxembourg fpos

### PR DESCRIPTION
**Pull request by Megaaaaaa**
Description of the issue this commit addresses:

Due to the covid's economical impact, Luxembourg's government decided to apply a 1% diminished rate to some taxes to help companies recover from the crisis. Now that this period is over, those rates aren't right anymore and should be brought back to their original value in the OSS mapping.

---

Desired behavior after this commit is merged:

Rates that had been diminished by 1% are back to their original value.
16% -> 17%
7% -> 8%

---

Enteprise PR: https://github.com/odoo/enterprise/pull/75650
task-[4369658](https://www.odoo.com/odoo/project/967/tasks/4369658)

### CODE REVIEW

**Review by lordkrandel — APPROVED** [review]
Hello 👋🏻 
The change LGTM.

Is there any need to adjust existing data?
Like, maybe re-triggering some calculation on drafts ...?
Just asking, probably we will just consider the new rates for new moves.

**Comment by Megaaaaaa** [comment]
> Hello 👋🏻 The change LGTM.
> 
> Is there any need to adjust existing data? Like, maybe re-triggering some calculation on drafts ...? Just asking, probably we will just consider the new rates for new moves.

I think that it's not required. Rates on oss fiscal positions are only updated via a manual refresh in the settings anyway so it's probably best not to apply anything linked to this without the user having manually refreshed the fpos at which point he knows his draft entries might need a refresh too.

**Review by gawa-odoo — COMMENTED** [review]
@robodoo r+

**Comment by Megaaaaaa** [comment]
robodoo retry

**Comment by Megaaaaaa** [comment]
Hello @gawa-odoo :wave:
Staging was failing because of tests in enterprise. I've opened [a PR](https://github.com/odoo/enterprise/pull/75650) there to fix them and pinged you on it. Could you have a look and r+ if it's still okay for you please ? Thank you! :pray:

**Pull request closed without merging**
