### PR TITLE
[FIX] stock : merge and unlink quants fast

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
On large database with product with serial number, when you perform those actions
- on product : action_open_quants()
- on stock.quant.package : unpack()

It take lot of time (12 secondes with database with 1 200 000 stock.quants).

This PR perform merge and unlink zero quant only on current product. And make an daily vacuum

This issue exist in V12 to master.

@nim-odoo
@rco-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW #2428793

**Comment by yelizariev** [comment]
@amoyaux ?

**Comment by ryv-odoo** [comment]
Hello @fmdl , Thank you for the PR. 
Can we have more information: 
- Which one is slowest `_unlink_zero_quants` or `_merge_quants` ?
- Is it the deletion of row that take time or the select query (+filter) ? Because if it is the deletion, your fix will only postpone the computation, right ? Can you analyse both queries to have more details result ?

Also your put `@api.autovacuum` but left the `_quant_tasks` in the scheduler, this means that it will be execute 2 times by day.

**Comment by fmdl** [comment]
@ryv-odoo I think `_merge_quants` is the slowest (because there are an groupby).

some company unactive the scheduler, but it is possible to remove the @api.autovacuum.

regards

**Comment by ryv-odoo** [comment]
Hello @fmdl ,
Thank you for your answer. 
- About the `@api.autovacuum`, I think it is the correct way to do it: Then IMO, you should remove it from the scheduler also and let your `@api.autovacuum`
- About the slowness, the main question is which **part** of the request is slowest? 
     - If it is the deletion of quant rows (I think that it is), then your fix is maybe not relevant because it is faster to postgresql to delete in one time 100 rows than 10 times 10 rows (it needs to check 10 times relational constraint instead of one). Then it is mandatory to have some numbers to see the performance gain of it (I don't see any result about before/after).
     - If it is the read of row quant, then it is clearly worth it. 

IMO, it depends of the performance speed up factor of this. And then you can easily estimate if it is worth it to merge (big diff, and decrease the readability, technical debt, etc).

**Comment by fmdl** [comment]
@ryv-odoo the issue is not the time to delete. It is on read : on large database (with serial number) `select/group by` on **all** quants take lot of time.

**Pull request closed without merging**
