### PR TITLE
[FIX] website_mass_mailing: close popup after successful subscription

### PR DESCRIPTION
**Pull request by kig-odoo**
Close newsletter popup after successful subscription

### CODE REVIEW

**Comment by kig-odoo** [comment]
@qsm-odoo  small fix

Can you look at this one?

Thanks

**Comment by kig-odoo** [comment]
ping @qsm-odoo

**Comment by kig-odoo** [comment]
@qsm-odoo ??

**Comment by kig-odoo** [comment]
I've created PR before more than a month ago. Looks like the team is working on something important. So closing this PR

Thanks :smile:

**Comment by qsm-odoo** [comment]
@kig-odoo You can leave it opened, I'll check it. It is just not urgent right now

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Comment by qsm-odoo** [comment]
@kig-odoo for some reason, the PR did not receive the CI/template label, could you try and rebase the branch?

**Comment by kig-odoo** [comment]
@qsm-odoo  Still some checks are not successful :confused: 

Should I create a new PR for saas-13.5? Any clue what's wrong ??

**Comment by qsm-odoo** [comment]
@kig-odoo I recreated the PR here: https://github.com/odoo/odoo/pull/59140, let's hope it works there :man_shrugging:

**Pull request closed without merging**
