### PR TITLE
[IMP] Add the possibility to register also to a before commit / rollb…

### PR DESCRIPTION
**Pull request by wildi1**
Description of the issue/feature this PR addresses:
We have added a new method to the Cursor class and two events to the _event_handlers dictionary.

Current behavior before PR:
You are not able to register to a "before commit/rollback event", only to a "after commit event" of the cursor

Desired behavior after PR is merged:
With this PR you are able to register to a new "before commit/rollback event" of the cursor.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
This should land in the master version as it introduces new features and as it is in the framework.

**Comment by wildi1** [comment]
Should I then do again a PR to the master branch ?

**Comment by Yenthe666** [comment]
@wildi1 I'd say wait for feedback from Odoo itself (I'm just a contributor). If they don't approve it you don't lose time and if they do approve it they could rebase it theirselves right away pretty much.

**Comment by odony** [comment]
Thanks for the PR. Indeed, please retarget the PR to master, as this [is a feature request](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch). (But you already knew that, because you said you read the PR guidelines, right? ;-))

**Comment by Elkasitu** [comment]
@wildi1 I'll close this for now, if you would like to have this looked at seriously, you should re-target master and provide some use-cases / examples; As a rule of thumb, we don't accept PRs for features that we don't plan on using.

**Pull request closed without merging**
