### PR TITLE
[IMP] product: update the image placeholder

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Prior to this commit, the image placeholder lacked contrast and wasn't readable in small size (eg. in the kanban view).

This commit improves this placeholder.

task-2760590

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hey @stefanorigano 👋 

Could you take a look at this PR? More information in the task :)

**Comment by Brieuc-brd** [comment]
Hello @Feyensv & @AntoineVDV 👋 
I'm not sure who I should ping on this PR, but it is ready for a technical review.
Could you take a look at it? 🙂

**Comment by Brieuc-brd** [comment]
@AntoineVDV 👋
Little reminder ;)

**Comment by Feyensv** [comment]
The delegate+ gives you the right to merge the PR yourself, but I guess nobody taught you that :D.

@robodoo r+

**Pull request closed without merging**
