### PR TITLE
Add notes that onchange() does not work on computed/related fields.

### PR DESCRIPTION
**Pull request by NicolasWebDev**
Everything is said in the title.
One would expect computed fields to trigger onchange as well.

### CODE REVIEW

**Comment by Sathors** [comment]
Well, once more my CLA signature is already present in the patch-4 branch...

**Comment by dreispt** [comment]
Should we go further and raise an error, or at least a warning?

**Comment by Sathors** [comment]
I think also that a warning would be nice.

**Comment by rco-odoo** [comment]
@Sathors I disagree with your proposal.

I think you misunderstand the expected behavior of onchange and saving records.

First, **onchange events are triggered and processed when a user modifies a field in a form**. In that situation, related and computed fields are recomputed if one of their dependencies has been modified by the user or another onchange. If such a field F is recomputed, it will trigger onchange methods on F in cascade.

My colleague @mart-e just checked that behavior by using `@api.onchange` on a related field; when the related field is recomputed, the onchange method is invoked as well. Here is his example:

    event_id = fields.Many2one('event.event')
    event_name = fields.Char(related='event_id.name', string='Event name')

    @api.onchange('event_name')
    def _onchange_event_name(self):
        ...

If the user changes `event_id` on the form, `event_name` is recomputed and the method `_onchange_event_name` is invoked.

Second, **onchange events are never triggered automatically upon saving a record**. Related and computed fields will be recomputed, but onchange method are not invoked, unless you do it explicitly by overriding `create()` or `write()`. In the example above, it is expected that `event_name` is recomputed, but not that `_onchange_event_name` is invoked.

This convention has always been like that in Odoo.

If you have found a case that contradicts the principles above, please reopen the issue and give us a concrete example to reproduce the bug.

Thanks,
Raphael

**Pull request closed without merging**
