### PR TITLE
[FIX] account: Faster read_group for account_abstract_payment._compute_payment_amount

### PR DESCRIPTION
**Pull request by moylop260**
Go to Menu / Accounting / Vendors / Bills
Search a partner with too many opened invoices
 - E.g. 713 opened invoices (709 local currency, 4 foreign currency)
Choose all them
Press Open Action -> Register Payment
Wait to open the view.

Before this patch line_profile result

```bash
Total time: 1141 s
Line #   Hits  Time            Per Hit    % Time   Line Contents
================================================================
   243   2922   1,139,417,018.0  389944.2     99.9    amount_total = sum([MAP_INVOICE_TYPE_PAYMENT_SIGN[i.type] * i.residual_signed for i in payment_invoices])
```

After this patch line_profile result
```bash
Total time: 12 s
Line #   Hits  Time            Per Hit    % Time   Line Contents
================================================================
   243  2862   11,733,108.0        4099.6     98.1    invoice_datas = invoices.read_group([('id', 'in', invoices.ids)], ['currency_id', 'type', 'residual_signed'], ['currency_id', '#
```

It means 20 minutes vs 12 seconds
It is 100x faster

### CODE REVIEW

**Comment by moylop260** [comment]
@nim-odoo 
May you ask for checking this PR?
It is a big read_group improvement performance.
Thanks in advance

**Comment by moylop260** [comment]
FYI @smetl @qdp-odoo @nhomar

**Comment by moylop260** [comment]
Hi @len-odoo 
I just updated the commit message and PR description with line_profile result.

Let me know if I should do something else. (I didn't got you about Lucas comment)

Thanks in advance.

**Comment by moylop260** [comment]
I upload the line_profiler result here:

# Before patch:
 - screen shot 2019-03-08 at 1 19 17 am

# After patch
 - screen shot 2019-03-08 at 1 19 05 am

**Comment by moylop260** [comment]
@kebeclibre 
Let me know if you need something else here.
Thanks in advance

**Comment by len-odoo** [comment]
That's impressive. Good work.
robodoo r+

**Pull request closed without merging**
