### PR TITLE
Master reduce lib chm

### PR DESCRIPTION
**Pull request by Gorash**

### CODE REVIEW

**Comment by xmo-odoo** [comment]
FWIW passing the jquery ui images through a recompressor saves almost 14K (out of 36.4), all images end up being 3771 bytes so 46% saved on 444444, 555555 and 777777, 40% on ffffff and 17% on 777620 and cc0000)

**Comment by jholze** [comment]
:+1:

**Comment by Yenthe666** [comment]
:+1: nice clean-up there guys!

**Comment by ged-odoo** [comment]
merged in master

**Pull request closed without merging**
