### PR TITLE
[FIX] event: Do not mail cancelled attendees

### PR DESCRIPTION
**Pull request by yajo**
Before this patch, emails were sent to everybody, even if they canceled or didn't confirm their attendance.

With this patch, only confirmed attendees get mailed.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa OPW-814459

### CODE REVIEW

**Comment by Yajo** [comment]
@rafaelbn discovered that it still makes sense to mail draft attendees, it's fixed now

**Comment by pedrobaeza** [comment]
Well, that is going to depend on the use case, but as default this one can be a sane one. The ideal is to be able to select that at `event.mail` record level, but that's an extra module or something for master.

**Comment by rafaelbn** [comment]
Dear Odoo, this fix the general case which is: when an attendee has cancelled the registration doesn't want to receive any more emails about the event. 👍 

@Yajo change the subject accord with the final general approach please

**Comment by Yenthe666** [comment]
Thanks a lot for the PR guys! I've labelled it so somebody should look at this quite fast. 😉

**Comment by qsm-odoo** [comment]
Hello,

The behavior was changed in master a while ago with a similar commit (https://github.com/odoo/odoo/commit/cf753a7fdf1739dcf37d2ad74f4c8efb3d4ff3b3). By then, we decided this was not something to change in stable versions as some users may rely on this (for example in hope canceled attendees would change their mind or simply to send more generic emails like suggestions to other events or whatever other content).

I asked our usability team again if this should in fact be considered as a *bug* and worth risking breaking stable behaviors. I will come back here with their decision.

(opw-814459)

**Comment by qsm-odoo** [comment]
Hello,
We finally decided to backport the mentioned commit in 10.0 (https://github.com/odoo/odoo/commit/de62e33618211fd754ad6e372ac93805cce58770).

**Comment by Yajo** [comment]
Nice, thanks! :clap: :clap:

**Pull request closed without merging**
