### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by pro-odoo**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/87a15678d [REL] 18.1.0-alpha.8 Task: 0
https://github.com/odoo/o-spreadsheet/commit/ef27a1552 [IMP] selection: alleviate size of revision on 'move header' Task: 4378896
https://github.com/odoo/o-spreadsheet/commit/ae44c66a5 [FIX] cell: keep non-breaking spaces Task: 4403607
https://github.com/odoo/o-spreadsheet/commit/10a07d449 [IMP] filters: modernize look Task: 4358098
https://github.com/odoo/o-spreadsheet/commit/6aeccfbef [IMP] components: clickable pointer on checkbox label Task: 4358098
https://github.com/odoo/o-spreadsheet/commit/1e87515cb [FIX] sheet view: DELETE_SHEET in initial revisions Task: 4405573
https://github.com/odoo/o-spreadsheet/commit/b5034c5b1 [FIX] SheetPlugin: Fix handling of unbounded zones Task: 4397745
https://github.com/odoo/o-spreadsheet/commit/fd2c93c6e [DOC] hall of fame according to VSC Task: 0
https://github.com/odoo/o-spreadsheet/commit/7dccf2a53 [FIX] table_style_editor_panel: disable "No Color" button Task: 4102704
https://github.com/odoo/o-spreadsheet/commit/f37b9981f [FIX] data_bar_rule_editor: disable "No Color" button Task: 4102704
https://github.com/odoo/o-spreadsheet/commit/c08abe00f [FIX] pivot: apply format on measure only a basic formula Task: 4377411
https://github.com/odoo/o-spreadsheet/commit/162bfa722 [IMP] demo: add demo data for geo charts Task: 3265268
https://github.com/odoo/o-spreadsheet/commit/42dbba510 [IMP] charts: add the geo chart type Task: 3265268
https://github.com/odoo/o-spreadsheet/commit/1fca7607b [REF] color: simplify color scale usage Task: 3265268
https://github.com/odoo/o-spreadsheet/commit/a6bb4c96a [IMP] table: select bottom right on resize Task: 4373825
https://github.com/odoo/o-spreadsheet/commit/f2e4a380b [IMP] standalone_composer: change active border color Task: 4380648
https://github.com/odoo/o-spreadsheet/commit/7448722ae [IMP] pivot: display pivot name in auto complete dropdown Task: 3953742
https://github.com/odoo/o-spreadsheet/commit/432acda35 [IMP] formulas: add irregularity map Task: 4357729
https://github.com/odoo/o-spreadsheet/commit/6bfcd9855 [REF] top_bar: stop hard-coding height Task: 4357729
https://github.com/odoo/o-spreadsheet/commit/88fb11261 [REF] collaborative: use color generator
https://github.com/odoo/o-spreadsheet/commit/3a9d70f8b [IMP] colors: add randomized colors Task: 4357729
https://github.com/odoo/o-spreadsheet/commit/358b8587d [REV] pivot: select pivot cells in composer Task: 4189098
https://github.com/odoo/o-spreadsheet/commit/af6ae5f6a [FIX] figure: crash on deleting dragged figure Task: 4329240
https://github.com/odoo/o-spreadsheet/commit/3fdd729be [FIX] composer: topbar composer z-index Task: 4246966
https://github.com/odoo/o-spreadsheet/commit/41335854b [IMP] pivot: allow to sort the pivot on any column Task: 3989395
https://github.com/odoo/o-spreadsheet/commit/e858997f3 [IMP] sort: homogenize type `SortDirection` Task: 3989395
https://github.com/odoo/o-spreadsheet/commit/0583d6c47 [IMP] package: bump luxon version Task: 4255275

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by pro-odoo** [comment]
robodoo fw=no

**Comment by pro-odoo** [comment]
robodoo rebase-merge

**Comment by rrahir** [comment]
@robodoo rebase-ff

**Comment by rrahir** [comment]
@robodoo r+

**Pull request closed without merging**
