### PR TITLE
[IMP] mail: introduce AttachmentViewer/close

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2579306

### CODE REVIEW

**Comment by phenix-factory** [comment]
Typo in commit title: AttachnentViewerComponent

**Review by phenix-factory — APPROVED** [review]
It's a bit strange to use `delete` inside a "close" action. Might worth considering have an `this.attachmentViewer.close` method that does the delete.
Otherwise LGTM.

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r-

**Comment by seb-odoo** [comment]
obsolete pr

**Pull request closed without merging**
