### PR TITLE
[IMP] base_import: improve the speed of the imports

### PR DESCRIPTION
**Pull request by std-odoo**
Purpose
=======
Improve the general performance of the import.

Specification
=============
Currently, each batch has his own HTTP request.

Because we need to parse the file until the end (we might need to read
more lines in the file if the method load skip some records, possibly
until the end), the file is opened / parsed for each batch which is
very inefficient.

Instead, we want to have only one HTTP request for the entire import,
we want to open / parse the file only once for all the batches.

For this purpose, we use the bus to communicate to the UI the
progression of the import.

Technical
=========
Odoo thread have a maximum lifetime defined by "--limit-time-real".
As we now have only one thread for the entire import, we might exceed
this limit, so we needed a way to bypass it.

Here are some benchmark, we can see that the more batches we have,
bigger is the impact of this improvement. And it's not that huge
because most of the time is already spent by the ORM to create the
records.

Here is a benchmark done on the <product.product> model (time is in
seconds).

```
Records | Batch | v14 | v15 | My branch
---------------------------------------
    30k |  2000 | 293 | 311 |       236
    30k |  1000 | 351 | 437 |       233
     1k |   200 |   9 |   9 |         7
```

Task-2688176

### CODE REVIEW

**Comment by keshrath** [comment]
Limits are in most cases on the webservice as well. So even if Odoo wont kill the thread the webservice will kill the connection.

**Comment by std-odoo** [comment]
> Limits are in most cases on the webservice as well. So even if Odoo wont kill the thread the webservice will kill the connection.

what do you mean with "webservice" ? the web server ? (nginx or other)

**Comment by keshrath** [comment]
> > Limits are in most cases on the webservice as well. So even if Odoo wont kill the thread the webservice will kill the connection.
> 
> what do you mean with "webservice" ? the web server ? (nginx or other)

Yes for example nginx

**Comment by std-odoo** [comment]
@keshrath Normally you can change the limit per endpoint, so you can increase the limit for the rpc route and it should be fine. Thank you for the warning

**Comment by C3POdoo** [comment]
Dear @std-odoo,

Thank you for your contribution but we are closing it due to inactivity.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
