### PR TITLE
[FIX] l10n_pe: avoid sync problems in the addresses by putting street…

### PR DESCRIPTION
**Pull request by jco-odoo**
…2 in the view

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@desdelinux

**Comment by desdelinux** [comment]
> @desdelinux
Hello @jco-odoo , can you add l10n_pe_edi to the runbot?

**Comment by fvz-odoo** [comment]
I just FUN tested this one and LGTM.

Cheers!

@jco-odoo @ren-odoo @luistorresm @desdelinux

**Comment by desdelinux** [comment]
LGTM :)

cc @jco-odoo @ren-odoo @luistorresm @vbe-odoo

**Review by desdelinux — APPROVED** [review]

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
