### PR TITLE
[FIX] board: deduplicate domain of domain and searchQuery

### PR DESCRIPTION
**Pull request by yosa-odoo**
Steps to reproduce:
- in contacts, edit action and define the domain as "[('name','=','Azure Interior')]"
- refresh and in favourite, click on "Add to Dashboard"
- in Home page, search "Customized Views"

Issue:
The domain will be doubled: "['&amp', ['name','=','Azure Interior'], ['name','=','Azure Interior']"

Solution:
Only use the `searchQuery.domain` since this one contains all informations needed:
https://github.com/odoo/odoo/blob/d3f4f99d795af4338e933fb7d31f142a1ec3cc2f/addons/web/static/src/js/views/control_panel/control_panel_model.js#L289-L293

opw-2888477

### CODE REVIEW

**Comment by yosa-odoo** [comment]
The test has been changed to respect the modification of the code.

**Comment by yosa-odoo** [comment]
Hello @KangOl 
How are you doing?

If not you, can you redirect me to someone who can check this PR?

Thank you!

**Comment by aab-odoo** [comment]
Hello @yosa-odoo 

It seems indeed not ideal, but what's the issue with the current behavior? It looks like a master fix to me.

**Comment by yosa-odoo** [comment]
Hello @aab-odoo,

Actually, there is no specific issue shared by the customer. Only a "Which is not the expected behavior, I guess."

That indeed might be a fix for Master. 

Please let me know if you want me to close this PR and create it only for Master.

**Comment by aab-odoo** [comment]
> Please let me know if you want me to close this PR and create it only for Master.

Yep

**Comment by yosa-odoo** [comment]
If I look at the tests in Master, they have made the change.
https://github.com/odoo/odoo/blob/fb5815edfd811e619fc3a08c9021c29768a5d86f/addons/board/static/tests/add_to_dashboard_tests.js#L245

I will just close this PR.

Thank you for the feedback.

**Pull request closed without merging**
