### PR TITLE
Create os-ia's CLA individual file

### PR DESCRIPTION
**Pull request by os-ia**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `75302079+os-ia@users.noreply.github.com`
- you are signing _for_ the address `i...@opensolutions.net`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by os-ia** [comment]
Oh I think the issue is that I committed via the Github interface and I had the option `Keep my email addresses private` enabled in my Github email settings (which I just fixed).

How should I proceed now?

**Comment by os-ia** [comment]
I prefer to use my actual email, so I will just amend the commits.

Thanks!

**Comment by mart-e** [comment]
Thanks for the update however I just noticed another issue, sorry about that.
Your other pull request odoo/enterprise#16106 is targeting 13.0 and this one is for 14.0, so the CLA check will still fail.
We port merged PR to upper versions (but not the other way around). So you need to submit your CLA in 13.0 (or even 12.0 if you wish to contribute to this version later).
By the way, while you are modifying your code, could you change the commit message to follow the [commit message guidelines](https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure). Something like
```
[CLA] signature for os-ia
```
Thanks !

**Comment by os-ia** [comment]
Oh didn't know about that, I'm sorry.

I think I would want to contribute to 12.0 and above, so maybe the best option would be to create a new PR for my CLA, targeting the `12.0` branch (and this time following the commit message guidelines).

**Pull request closed without merging**
