### PR TITLE
[FIX] l10n_cl: Fix cannot post invoice with a contact as a partner

### PR DESCRIPTION
**Pull request by suv-bmya**
Backport from  -> https://github.com/odoo/odoo/pull/73663

### CODE REVIEW

**Review by william-andre — CHANGES_REQUESTED** [review]
This should be dependent on the country of the partner or on the country of the company on which the partner is recorded (or on the environment if no company set)

**Comment by suv-bmya** [comment]
> This should be dependent on the country of the partner or on the country of the company on which the partner is recorded (or on the environment if no company set)

 @william-andre , What do you mean?

**Review by william-andre — APPROVED** [review]
Nothing 
@robodoo r+

**Comment by william-andre** [comment]
@fw-bot disable

**Pull request closed without merging**
