### PR TITLE
Update adhoc.md

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
Please can you check this PR

**Comment by nicomacr** [comment]
I need this PR for this  PR  https://github.com/odoo/odoo/pull/9247 , https://github.com/odoo/odoo/pull/8354

**Comment by jjscarafia** [comment]
Ping... Any news with this? Two PR pending because of this one...

**Comment by nle-odoo** [comment]
Hello, I merged it in https://github.com/odoo/odoo/commit/a69205d561f5cab0691fd9835c9b633fc8597812

**Comment by nle-odoo** [comment]
Hello, I merged it in https://github.com/odoo/odoo/commit/a69205d561f5cab0691fd9835c9b633fc8597812

**Comment by jjscarafia** [comment]
Thanks!

**Comment by jjscarafia** [comment]
Thanks, will ask them to remake the PR

**Pull request closed without merging**
