### PR TITLE
[CLA] sign Odoo CLA

### PR DESCRIPTION
**Pull request by dvlazariev**

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `d...@strikersoft.com`
- you are signing _for_ the address `d...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by dvlazariev** [comment]
@mart-e Thanks for pointing that! It's my personal account. I updated my Git configuration.

Is the `master` a right target for CLA PR? At the moment I have a PR into the `16.0` and I'm waiting for my CLA submission.

**Comment by mart-e** [comment]
No so you need to target it on 16.0 or earlier. Once merged, we will port it to upper versions but not the other way around. You can resubmit in 16.0 or earier if you think you might need it in 14 or 15.0 one day.

**Comment by dvlazariev** [comment]
I don't think I need 15.0 or earlier. So I target the 16.0.

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by dvlazariev** [comment]
@mart-e Thanks for the review! I'll rebase this PR now. And I'll rebase my feature PR as soon as this PR will be integrated into Odoo.

**Comment by mart-e** [comment]
@dvlazariev please don't push in the branch until it's closed, otherwise it cancels the merge process.

@robodoo review+

**Comment by mart-e** [comment]
Oups never mind, you did not push in it :man_facepalming: (need more :coffee: )

**Pull request closed without merging**
