### PR TITLE
[REM] web, project: remove mnmlicons font

### LINKED ISSUE #6382: Fonts without license? (mnmliconsv21-webfont.*)
Please document origin, copyright and the license for fonts `addons/web/static/src/font/mnmliconsv21-webfont.*`. 
I was not able to find an authoritative source of those fonts on web. It seems those font files were developed by Carlos Elías (http://www.carloselias.cl/) but his web site is not in English.
Someone need to contact Carlos to confirm copyright and license of those fonts or they will have to be removed.

### PR DESCRIPTION
**Pull request by d-fence**
The mnmliconsv21 is not used anymore for 7 years (see 660b13bb)

Closes #6382

### CODE REVIEW

**Comment by d-fence** [comment]
@edi-odoo I replaced `Rhesmanisa.ttf`  which is problematic (see #109361) with the [Oooh Baby](https://fonts.google.com/specimen/Oooh+Baby) font. Can you give me your blessing ...

**Review by edi-odoo — APPROVED** [review]
Excellent choice ! 
It has a lot mot characters in it too 👍

**Review by xavierbol — APPROVED** [review]

**Review by arj-odoo — APPROVED** [review]

**Review by fdardenne — COMMENTED** [review]
Shouldn't `debian/copyright` be updated to remove:
```diff
- Files: addons/web/static/src/fonts/mnmliconsv21-webfont.*
- Copyright: Carlos Elas
- License: MIT```
And add the new fonts copyright into this file ?

**Comment by d-fence** [comment]
> Shouldn't `debian/copyright` be updated to remove:
> 
> ```diff
> - Files: addons/web/static/src/fonts/mnmliconsv21-webfont.*
> - Copyright: Carlos Elas
> - License: MIT
> ```
> 
> And add the new fonts copyright into this file ?

You are right, nice catch. Thanks

**Comment by d-fence** [comment]
robodoo override=ci/style
TTF font of 128KiB ... not so huge

**Comment by d-fence** [comment]
robodoo r+ rebase-ff

**Pull request closed without merging**
