### PR TITLE
	[FIX] base: change position of IDR currency

### PR DESCRIPTION
**Pull request by repodevs**
Description of the issue/feature this PR addresses:
Default position of IDR Symbol is before amount, symbol must be before amount
reference: https://en.wikipedia.org/wiki/Indonesian_rupiah

Current behavior before PR:
Symbol position is after amount

Desired behavior after PR is merged:
Symbol position is before amount

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by repodevs** [comment]
@Yenthe666 @xmo-odoo could you look at this PR, this little change help many beginners, when they ask "why the position of the symbol is behind the amount?"

**Comment by Yenthe666** [comment]
More something for @mart-e could you squash / clean up some of the commits too?

**Comment by mart-e** [comment]
Thanks !

**Comment by repodevs** [comment]
@mart-e your welcome

In `11.0`, do I need create a PR again or this is will be forward port?

**Comment by Yenthe666** [comment]
@repodevs this will be forwarded to 11.0, this shouldn't take very long (it happens quite often, somewhere along the lines of once every two weeks)

**Pull request merged**
