### PR TITLE
[IMP] mail: improve label of button to toggle style of email message

### PR DESCRIPTION
**Pull request by alexkuhn**
Before this commit, when a message is of type email, the button to toggle between adjusted content style with webclient theme and the original email style was labelled "Show Original Email" and "Don't show original Email".

This label is confusing, as it gives the impression that this button opens a new screen or removes a UI element. This button only alters the visual of the message, that is the style, so the label should be better worded to tell that.

This commit rename the label to "Show Original/Custom Format", so that it's clearer what this button actually does.

Before
before

After
after

### CODE REVIEW

**Comment by phenix-factory** [comment]
The "style" term look poor, I agree that the hide/show is better, but email was fine. I understand that it's technically correct, but it will create confusion for people who don't know what "css style" is.

**Comment by alexkuhn** [comment]
"Show Original Email" gives the impression that it will open a new screen or UI element to show the original email. Some competitors have a feature equivalently named that shows the raw content of email, metadata included, which is definitely not what this button does. Using "Style" instead of "Email" is clearer on the effect clicking on the button does.

Note that "style" is a broad name, it sure is related to CSS of some sort, but any people understand "style" means "appearance" in this context.

**Review by seb-odoo — APPROVED** [review]
@robodoo r+ delegate+

**Comment by seb-odoo** [comment]
@robodoo r-
It should be re-targeted 17.0

**Pull request closed without merging**
