### PR TITLE
[FIX] account: allow to create new journal to non-admin users

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: Fixes https://github.com/odoo/odoo/issues/34153

Current behavior before PR: Non-admin users doesn't have rights to create new sequence.

Desired behavior after PR is merged:

Cc @qdp-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Ping @qdp-odoo

**Comment by mart-e** [comment]
As explained on #34153 need more context, all the calls to `._create_sequence` seems to already be done with a `sudo`, maybe there is just one missing. But shouldn't add a sudo here

**Comment by sswapnesh** [comment]
I will have a more detailed look and Update here.

**Comment by sswapnesh** [comment]
> I will have a more detailed look and Update here.

@mart-e  I have updated this PR with Proper solution (and added reason at https://github.com/odoo/odoo/issues/34153#issuecomment-537461540)

**Comment by mart-e** [comment]
Thanks for the explanations, I get it now
@robodoo r+

**Pull request closed without merging**
