### PR TITLE
[14.0][FIX] Analytic is not transfered in CABA for taxes

### PR DESCRIPTION
**Pull request by cvinh**
Before this commit, the analytic account and analytic tags are not returned in the tax cash basis journal entries.

Steps to reproduce :
- setup a tax with :

1. analytic = True
2. tax_exigibility to 'on_payment'
3. no account in the repartition lines (we want the tax journal entry to take the account of the invoice line)

- create an invoice with this tax on a line and an analytic account (or tags)
- validate the invoice --> the analytic data appear in the journal entries
- pay the invoice and check the CABA journal entry --> the analytic fields are empty

After this commit, the analytic fields are correctly returned

This bug was fixed in v11.0 but not forwarded... https://github.com/odoo/odoo/pull/33236

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by oco-odoo — CHANGES_REQUESTED** [review]
Well, I'm not surprised the fix you mention has not been forward-ported, since its diff explicitly says "DO NOT FORWARD-PORT!!! ONLY FOR v11" ^^

But anyway, doing this, aren't you afraid that the reports would consider both the analytic data of the invoice and the related cash basis move(s), essentially reporting the same information twice ? To me, that's what will happen (not in the tax report though, since it will ignore the non-eligible move lines ; maybe that's your problem ?). 

Also, could you elaborate a bit more on your use case ?

**Comment by cvinh** [comment]
> "DO NOT FORWARD-PORT!!! ONLY FOR v11" ^^

I saw that but there is no explanation why...

**Comment by cvinh** [comment]
As you pointed out, the amount of the tax goes twice in the analytic account indeed. In the invoice it's not a problem because the general account is a transition account. In the CABA move we need the analytic amount because it's a revenue or expense general account.
That said, it would be better to balance the analytic amount in the counterpart as well in the CABA move.
I will push another commit with comments

**Comment by oco-odoo** [comment]
I discussed it with our product owner. This case is indeed not covered. We won't merge it in 14 and 15, as we are afraid the change of behavior could cause more harm than good. We will, however, fix it in 16, were the analytics refactoring allows more flexibility for modification of already posted entries, leaving people more room to correct things if the new behavior does not fit their needs. I'm creating a task for this in our pipe ; we'll handle it :)

**Pull request closed without merging**
