### PR TITLE
[MERGE] *: rename image fields and use image.mixin

### PR DESCRIPTION
**Pull request by seb-odoo**
Merge commit for PR #34925
Related enterprise PR odoo/enterprise/pull/4865

The goal is to:
- Use `image.mixin` on the models currently storing multiple image sizes.
- Create Image field and use it on models where mixin is overkill.
- Rename the image fields to contain the pixel number in the name.
- Add 512 size.
- Clean up `image.mixin`, zoom field, variant fields.

Note: models that currently store only a single size image will not be changed
in this PR.

### CODE REVIEW

**Comment by seb-odoo** [comment]
Image PR with the spec we decided 3 months ago in https://github.com/odoo/odoo/pull/32814

This is hard to rebase, so I would consider it priority.

**Comment by seb-odoo** [comment]
@JKE-be 

Image PR with the spec we decided 3 months ago in https://github.com/odoo/odoo/pull/32814

This is hard to rebase, so I would consider it priority.

**Comment by blaggacao** [comment]
@seb-odoo Did you hear of `pybolwer`?
- 2 days learning curve (+ 1 weekend)
- possibly 10fold (and more) productivity in refactorings...

**Comment by seb-odoo** [comment]
@blaggacao thank you for the link, never heard of it before

**Comment by JKE-be** [comment]
merge les 7 premiers commits avec meme commit que enterprise

[IMP] *: rename image field on mixin image

image_big => image_1024
image_large => image_256
image_medium => image_128
image_small  => image_64
image_original => image_max  (resized to 1920 max)
image replaced by image_max

+ add new intermediate format:
image_512

PR: #34925
Related to community PR odoo/odoo/pull/4865

Commit 8 7ba8a58de868d4e1874202369cca9ada8ed5bb23:
comme discuté pas utilsié mixin, mais copier code une 3ieme fois pour le moement.
A la 4ieme, on reflechira ;)

commit 9 929a5af1ba3942be83e9d748ca1bf8f5e70ceb6b
add mixin, and use image in frontend when you click on a category if you want, but in all case, keep this standard field.

commit 10 6d35b502c587fd79f0b058cd040da38e128a8b1d
Not sure. We will store 256/512/1920 for something not customizable that nobody will use. It is a personnal choice. But we try to keep pos 'light'

commit 11: 57e9625409640191ac87d698b356146e947ae9ae
idem that pos

comit after, all to rediscuss according each model

about split mixin, to validate again with al once we know wich model, and why/where they uses several size

**Comment by JKE-be** [comment]
please rebase 

Conflicting files
odoo/addons/base/models/res_company.py

after go r+

**Comment by seb-odoo** [comment]
conflict resolved

**Comment by JKE-be** [comment]
@robodoo r+ rebase-merge

**Comment by JKE-be** [comment]
@robodoo retry

**Comment by JKE-be** [comment]
@robodoo r+ retry

**Pull request closed without merging**
