### PR TITLE
Create elgow.md

### PR DESCRIPTION
**Pull request by elgow**
Description of the issue/feature this PR addresses: Add CLA

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

Why do you put the full text? You can use the short version as given in [sign-cla](https://odoo.com/sign-cla)

- you are signing using the address `elgow@users.noreply.github.com`
- you are signing for the address `e.@softhome.net`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by mart-e** [comment]
@elgow Sorry but this is still not correct. In the first commit, you are signing _for_ the address `@softhome.net`.
In your second, you change to sign _for_ the address `@uw.edu`.
However, in both commits, you are signing _with_ your address `@users.noreply.github.com`.

This is probably because you are using the github interface to sign and have made your email address private

**Comment by elgow** [comment]
You've hit exactly on the problem. So it sounds like I just need to use my noreply address to sign. I'll do that now, and thank you very much for your help.

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it has been integrated into Odoo at revision https://github.com/odoo/odoo/commit/e746f64ee439b61cde110342eeb9ba8a4f66578a.
Future pull requests made on odoo will be validated by the runbot.
Regards

**Comment by elgow** [comment]
Thank you for your help

**Pull request merged**
