### PR TITLE
[IMP] base: updated l10n icons

### PR DESCRIPTION
**Pull request by bat-odoo**
Purpose of the task is to update all l10n modules icon with new icon that i have
found in task attachment.

So in this commit, Updated all l10n modules icon with new icon.

Links
PR #65329
TaskID: 2442631

### CODE REVIEW

**Comment by arj-odoo** [comment]
@bat-odoo There are several empty png files. Could you use git rm on them ? Thanks :-)

**Comment by mba-odoo** [comment]
> @bat-odoo There are several empty png files. Could you use git rm on them ? Thanks :-)
>> @arj-odoo , Yes, we removed using the git rm  but we also removed `static/description` folder so may be due to that it was showing the empty. Thanks

**Comment by tivisse** [comment]
@robodoo r+

**Comment by william-andre** [comment]
@robodoo r-

**Comment by william-andre** [comment]
There are already images in the repo, no need to add all this diff
https://github.com/odoo/odoo/tree/14.0/odoo/addons/base/static/img/country_flags

**Comment by william-andre** [comment]
My bad, didn't look at the images referenced.
I find this choice pretty stupid though, but I'll let you continue with it if it is really wanted.

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
