### PR TITLE
remove boolean widget on signature binary field

### PR DESCRIPTION
**Pull request by msh-odoo**
PURPOSE
When writing something in signture field in stock.picking and enable signature field in listview throws traceback.

SPEC
Remove boolean widget on signature field.

TASK 2570929

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
I would rather completely remove it from the view or fix the boolean widget for this case. It's a bit useless to have the size of the image in the list view

**Comment by mcm-odoo** [comment]
@msh-odoo @amoyaux Hello, I was checking it and I don't think having size of the image for a column "Signed" is great
and also the fix should'nt be in the boolean widget/component.
Boolean widget supports only boolean fields so we should better have a computed field `is_signed` and use it instead of the binary field.

**Comment by amoyaux** [comment]
@mcm-odoo Yep seems a good solution

**Comment by llacroix** [comment]
@amoyaux yes, the widget should be likely fixed by using a special validation check instead of the constructor. You can see the comments in my issue.

> Boolean widget must support only boolean fields so we should better have a computed field is_signed and use it instead of the binary field.

That's pretty much how we fixed it in for our client. I kinda agree that the Boolean widget should only work with booleans... but in reality odoo used to have the boolean as True for non false values. So undefined/false/null would be False while anything else would be considered True. It obviously work for any readonly field and can be used for any field. That's why it worked with the binary field in the past as an empty datas would return null/false while a saved data would return a size which is not false. 

But to make it clear, we needed it in the view as a boolean so removing the widget is worthless. is_signed is fine while in my opinion it will require more computation for a boolean field... Seems a bit overkill when the widget can be more flexible.

**Comment by msh-odoo** [comment]
@mcm-odoo @amoyaux Should I add computed field ```is_signed``` in 14.0 as issue is available in 14.0?

**Comment by amoyaux** [comment]
@msh-odoo You can do a PR for master, I will merge this one like that. It's not otimal but it will avoid the traceback and the diff is safe for a stable.

**Comment by amoyaux** [comment]
robodoo r+

**Pull request closed without merging**
