### PR TITLE
[[DONE]] - [FIX] account_voucher: copy product in acc voucher

### PR DESCRIPTION
**Pull request by blaggacao**
- [x] Test failure unrelated
- [x] Manual QA locally, can only be validated on an ee runbot (eg. by group journal entries by product)

Possibly as an oversight, before this commit, product_id was not passed
to the aml on account vouchers.

This caused inexpected behaviour, if products are a relevant dimension in cost
or revenue analysis analysis: Whereas on invoices, this product is copied to aml
on voucher, it is not.

Now products are copied to the amls thereby enabling this reporting dimension.
This is especially usefull for people who use vouchers for minor expenses, but
need some additional visibility to what general or analytic accounts provide.

**Description of the issue/feature this PR addresses:**
- Products are not available on voucher generated amls
- This is a missing analytic dimension as compared to normal invoices

**Current behavior before PR:**
- Products are not copied on vouchers

**Desired behavior after PR is merged:**
- As vouchers permit to choose a product
- Users expects information not to be lost on aml as compared to similar behavior on invoices.

**Note:** Please do not close, even if not immediately accepted (`wishlist` tag). This PR is meant to be carried along and actively maintained, until this semantic will be completed this way or another.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@xoe-labs

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't think the product should be copied in payment entry, as you are not selling nor purchasing a product. Not only that: you can pay more than one product at the same time (a whole invoice, or even more than one invoice), so which product to put?

**Comment by blaggacao** [comment]
@pedrobaeza 
> so which product to put?
Putting a product is not required.

**Comment by pedrobaeza** [comment]
Then it doesn't serve for anything and it's correct as is :wink:

**Comment by blaggacao** [comment]
@pedrobaeza Please,  Pedro... That's a nonsense argument. Don't put me at the edge of despair...

Moreover...
> as you are not selling nor purchasing a product. 

If you choose to put one, you are indeed. So this fix seems pretty correct, unless there are other blocking arguments.

**Comment by blaggacao** [comment]
> Well, as said, I don't see the application, but I'm not closing it waiting for other opinion.

That can be interpreted as an expressed wish to better understand the use case. So here it goes: :wink: 

- User registers voucher and sets product on invoice
- User groups amls by product
- User sees the respective invoice line grouped
- User does the same thing with vouchers
- User doesn't see the grouping
- User doesn't understand why reasonably it works on invoices and not on vouchers
- User might want to register general services (like water, electricity, etc.) quickly by vouchers instead of full blown onerous / complicated invoices.
- Still, user want's to have a reporting dimension which tells what was the distribution (as per service) of his utility spending.
- User might want to know that, for example in order to control or optimize costs.

@pedrobaeza Please kindly give me feedback, if that is intelligible now?

As to closing, please take into consideration this note: (I don't see a abstract reason why to negate such request)
> **Note:** Please do not close, even if not immediately accepted (`wishlist` tag). This PR is meant to be carried along and actively maintained, until this semantic will be completed this way or another.

**Comment by pedrobaeza** [comment]
I still think this is not a good idea, but I let Odoo accounting team to have the last word.

**Comment by blaggacao** [comment]
@pedrobaeza Ah thanks. That's great info, because maybe you have misunderstood something and can be resolved quickly.

> Payments shouldn't have related product.

This PR is about vouchers. Why do you reference payments here?

> There can be more than one product in the origin.

It is not clear to me what you mean or what problem you see. Just as on invoices, I would not choose to use a `product_id` in case I summarize a line containing different products.

> Not homogeneous behavior.

The contrary is the case, as in the PR description says, it is meant to establish homogeneous behaviour with what is known from invoices. Maybe I don't understand what exactly you mean.

Could you please kindly clarify my doubts about your point of view? Remember: if you think my point of view and the one of a majority of my users is wrong, the goal should be to make me aware of this alongside turning down this PR, instead of only turning this down without further detailing your line of thought. Thanks :wink:

**Comment by pedrobaeza** [comment]
> This PR is about vouchers. Why do you reference payments here?

Sorry, my bad. I have been mixing all the time old "vouchers", that means payments, with the current vouchers, that are like invoices. Then you are right about the product.

> instead of only turning this down without further detailing your line of thought

I'm not turning off (it's opened), only letting others to have an opinion. Any way, now I think this may be right, although I'm not myself a user of new "vouchers".

**Comment by blaggacao** [comment]
@pedrobaeza Thanks! It's great to have been able to clarify this for good. I was almost suspecting a misunderstanding... :wink:

**Comment by blaggacao** [comment]
@pedrobaeza Would I have maybe convinced you to give an approval? Maybe it would help to get this improvement shipped more quickly...

**Comment by pedrobaeza** [comment]
Now I'm wondering why the quantity should be 1 instead of the quantity stated on the voucher.

**Comment by blaggacao** [comment]
@pedrobaeza good complement. Will add a commit, it is not akin to my original problem, but if accepted likewise, even better...

**Comment by blaggacao** [comment]
@pedrobaeza It's done. Thanks! Could you channel your powers to approve / recommend?

**Comment by pedrobaeza** [comment]
You haven't remove `'quantity': 1` several lines below.

It should be @qdp-odoo or any of his team who approves this.

**Comment by blaggacao** [comment]
@pedrobaeza Thanks. Not so much that, but I haven't understood your comment in the first place.
You could use githubs Parmalink to communicate on spot. :wink:

**Comment by pedrobaeza** [comment]
Remove this: https://github.com/odoo/odoo/pull/26336/files#diff-462ed93eeff28a97612ab7035edaae48R296

**Comment by blaggacao** [comment]
@pedrobaeza Thanks, fixed and rebased just now.

**Comment by qdp-odoo** [comment]
merged :-) 

Thanks for the contribution guys

**Pull request merged**
