### PR TITLE
Saas 18 - Restore systray chatter v11 design

### PR DESCRIPTION
**Pull request by stefanorigano**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @aab-odoo , 
here there are 2 commits to restore the design prior to 7a91d87.
I also added another commit to adapt the mobile layout to v11

**Comment by stefanorigano** [comment]
wait... actually that commit is impacting other stuffs too :/
I'll push other commits here and I'll ping you once done...

**Comment by stefanorigano** [comment]
Hello @qsm-odoo , the fixes we were talking about.

**Comment by qsm-odoo** [comment]
Merged :tada:

**Pull request closed without merging**
