### PR TITLE
[FIX] web: enable default_focus on html field

### PR DESCRIPTION
**Pull request by nle-odoo**
opw-647578

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Perfect as well :). Thank you !

**Comment by nle-odoo** [comment]
merged in 7.0 with https://github.com/odoo/odoo/commit/411a07a64e6fe048dff2e2d339db4ea260053382

**Comment by atchuthan** [comment]
This fix does not work for firefox.

**Comment by atchuthan** [comment]
Fix works perfectly

**Pull request closed without merging**
