### PR TITLE
[FIX] support readonly attribute on toggle_button widget

### PR DESCRIPTION
**Pull request by msh-odoo**
PURPOSE
readonly attribute does not work on toggle_button widget.

SPEC
make toggle_button readonly if it has readonly attribute or readonly modifiers, it should not be clickable if it has readonly modifiers.

TASK 2339995

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e

**Comment by mart-e** [comment]
@msh-odoo @Yenthe666 thanks for the port but stil this is for the JS team, to check on the task if you can get somebody to review it :)

**Comment by Yenthe666** [comment]
-sigh- @ged-odoo could you save us here? ;)

**Review by aab-odoo — COMMENTED** [review]
Hello @msh-odoo 

V12 is no longer supported. Could you re-target to v13?
Could you also add "web:" in the commit message?

Thanks

**Comment by aab-odoo** [comment]
@msh-odoo could you add "web:" in the commit message?

**Pull request closed without merging**
