### PR TITLE
stock_account: division by zero

### PR DESCRIPTION
**Pull request by lem8r**
when computing average price per unit for moves with returns.

Description of the issue/feature this PR addresses:
In a case when stock move has return move which generates correction SVL with zero qty and correction value
`_compute_average_price()` method of `product.product` fails to ignore SVLs with zero qty.

Current behavior before PR: division by zero

Desired behavior after PR is merged: average price per unit correctly computed

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lem8r** [comment]
Fix commit is yet to come.
Waiting for tests to fail..

**Comment by lem8r** [comment]
@sle-odoo Hi,

Can you please have a look? It is related to  3831649

**Comment by ticodoo** [comment]
Hello @lem8r can you write out the steps to reproduce your bug? It will make it easier to review your PR. Also please combine your commits so your test is in the same commit as the fix that makes the test pass.

**Comment by lem8r** [comment]
Hi @ticodoo 

Here are the steps to reproduce the issue:

- Enable anglo-saxon accounting. (Install generic coa)
- Create storable product with category having AVCO and Automated Valuation.
- Set Product's cost to 10. And invoicing policy to ordered quantities.
- Create SO for 10 units and confirm it.
- Deliver 10 units by forcing done qty. It will create SVL for -100.
- Create PO for 10 units and 20 price per unit.
- Receive 10 units. It will create correction SVL for first delivery so it will be valued by -200.
- Go to first delivery, return at least 1 unit.
- Go to SO, create regular invoice for 10 units while 9 are actually delivered.
- Try to validate invoice it will give you division by zero error.

Main trick is to trigger computation of average price per unit for both delivery move and it's return move having correction SVL.
Correction SVL has zero qty and non-zero value which gives division by zero when computing price per unit.

```
  File "/home/odoo/src/odoo/14.0/addons/sale_stock/models/account_move.py", line 120, in _stock_account_get_anglo_saxon_price_unit
    average_price_unit = self.product_id._compute_average_price(qty_invoiced, qty_to_invoice, so_line.move_ids)
  File "/home/odoo/src/odoo/14.0/addons/mrp_account/models/product.py", line 46, in _compute_average_price
    return super()._compute_average_price(qty_invoiced, qty_to_invoice, stock_moves)
  File "/home/odoo/src/odoo/14.0/addons/stock_account/models/product.py", line 690, in _compute_average_price
    ((candidate.value + sum(candidate.stock_valuation_layer_ids.mapped('value'))) / candidate.quantity)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ZeroDivisionError: float division by zero
```

**Comment by lem8r** [comment]
Not sure if commit message is descriptive enough.

**Pull request closed without merging**
