### PR TITLE
[FIX] website_sale: Update order date on line update

### PR DESCRIPTION
**Pull request by lasley**
**Description of the issue/feature this PR addresses:**

A cart can be held for multiple days, then edited, and eventually checkout completed. 

The order date is never updated past the initial order creation, which results in what looks to be incredibly old sale orders as well as out of date pricing.

**Current behavior before PR:**

Stale orders and pricing. Replication steps:

* Install website_sale
* go to /shop
* add product to cart
* manually edit quote to past date
* add a few more lines to cart, or edit existing
* checkout
* check order date - it's the old date, even though the order was completed today

The old date results in possibly expired pricing due to the [order date being used as part of the product pricing context](https://github.com/LasLabs/odoo/blob/5a4d983ed76a547c53426804d610e16c6ff05972/addons/website_sale/models/sale_order.py#L66)

**Desired behavior after PR is merged:**

This is a stop-gap for a customer until I find a more elegant solution. Please don't merge yet.

_--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr_

### CODE REVIEW

**Comment by rafaelbn** [comment]
Good catch!

**Comment by pedrobaeza** [comment]
Shouldn't this be done on cart checkout?

**Comment by lasley** [comment]
If you just do it in cart checkout, the cart lines can still be stale. This would mean that the cart would be one price, then would change on the confirmation page. 

This definitely isn't the right place for it though, and lines that are already in the cart will be susceptible to the stale price issue (until checkout) as well. 

This did cover the immediate need though, which was mainly for picking up empty and expired carts.

**Comment by pedrobaeza** [comment]
Let's see what @JKE-be thinks

**Comment by JKE-be** [comment]
Hi,

I agree with you that it is strange, but not sure about the way to fix it.

We already remark some strange behaviour in our app store where people add product and pay 6 months later when the price has been increased.

It should probably be an optional feature that set how many time a cart is valid, and if we delete it or recompute each line once expired. In reality that depends on the business.

The problem is that recompute a sale.order.line is not always a good idea. Eg: website_event set manually the price and don't use a product, so no way to recompute it. Other cases, a salesman change the unit price manually in the backend to make the online cart with the good price. We don't want to override the price during checkout.

/cc @fgi-odoo

**Comment by lasley** [comment]
> We already remark some strange behaviour in our app store where people add product and pay 6 months later when the price has been increased.

Yeah this is what we're trying to avoid here. It doesn't do anything about old items, but at least new items getting added to the cart are added at the correct price. Without the changing of the date here, new items are the 6 months ago price if the cart was created then.

> The problem is that recompute a sale.order.line is not always a good idea. Eg: website_event set manually the price and don't use a product, so no way to recompute it. Other cases, a salesman change the unit price manually in the backend to make the online cart with the good price. We don't want to override the price during checkout.

Shouldn't an event line item have an expiration date? Forgive on my naivety here because I don't use the module, but event ticket purchase sessions are typically only valid for a set period of time  - the max possible being the interval between now and the event being held.

But anyways, in the case of a no product situation I think we're good. If there's no product to recalculate the line item against, it could just be not calculated. I think the bigger hitch is the salesperson with custom pricing. In that case, we do have a product to calculate against as well as a pricelist.

I think the solution could possibly be simple here though. What if we simply don't recompute the line if the person that last modified it was an employee? This leaves an edge case of quantity modifications by the user, but I think this would void whatever deal was in place anyways.

**Comment by JKE-be** [comment]
> Desired behavior after PR is merged:
> 
> This is a stop-gap for a customer until I find a more elegant solution. Please don't merge yet.


If nothing to merge, I close.
We are aware of a similar problem with our app store.
So a task in internal should catch it in a future version.

**Pull request closed without merging**
