### PR TITLE
[REM] services: remove deprecated fields

### PR DESCRIPTION
**Pull request by MissingNoShiny**
Task-3631801

### CODE REVIEW

**Review by pkyriakou — COMMENTED** [review]
Thank you @MissingNoShiny for your work :100: 
I have nothing to comment :partying_face: looks good to me :green_circle:

**Review by xavierbol — APPROVED** [review]
Great work! 💪🏼 

LGTM, thanks for your work. 🙂

**Comment by xavierbol** [comment]
I just rebased since the runbot was unhappy. 🙂

**Comment by xavierbol** [comment]
robodoo r+

**Comment by xavierbol** [comment]
robodoo r+

**Pull request closed without merging**
