### PR TITLE
[FIX] base_import: date/datetime format on import

### PR DESCRIPTION
**Pull request by guva-odoo**
Add support for converting moment.js date formats
to strftime format in BaseImportModel

opw-3247615

### CODE REVIEW

**Comment by guva-odoo** [comment]
> So if we want to keep the same type of format used in 16.0 (e.g. YYYYMMDD) we need to remove it.

Done, thanks @MerlinGuillaume for your help

**Review by Iucapad — CHANGES_REQUESTED** [review]
You should add a test for this fix.
Also, you are importing a legacy file to this component, and this should not happen.

What's really the issue that occurs, could you explain more in detail?

**Comment by guva-odoo** [comment]
> Also, you are importing a legacy file to this component, and this should not happen.

I'm open to suggestions about an other way to do

> What's really the issue that occurs, could you explain more in detail?

The issue is, when importing a bank statement, with other date format than '%Y-%m%d', an error is raised because the date format is not converted before being send to the backend, therefore we raise an 'ImportValidationError' here https://github.com/odoo/odoo/blob/0ef930cd7598bd15227ff025d2662d4331f8e45b/addons/base_import/models/base_import.py#L1218
Ticket: https://www.odoo.com/web#view_type=form&model=project.task&id=3247615&cids=1

**Comment by Iucapad** [comment]
Okay, I understand. I'll look if something exists in the newer code to replace _moment_to_strftime_format_
Thank you for the fix

**Comment by Iucapad** [comment]
Hello @Arcasias, we need your help on this subject related to date/datetime formatting.
Here, the user should be able to write any date format in the import action (YYYY-MM-DD, DDMMYY, etc.), but we must send the value in Python strftime for the execute_import call (%Y-%m-%d, %d%m%y, etc.).

It looks like this doesn't exist yet, am I right? And is it something that should be implemented?

Screenshot FYI: 
There is a dropdown now, but in the future, this will be an input and the user should be able to write any format he wants, and the js should translate that to Python strftime:

image

**Review by Iucapad — APPROVED** [review]
Okay let's go with this fix for the moment. I have a task ongoing to improve those date(time) options btw.. I'll check later if it's possible to use another utils than moment_to_strftime_format.

Thank you for the fix!

**Comment by Iucapad** [comment]
@robodoo r+

**Pull request closed without merging**
