### PR TITLE
[FIX] hr_holidays: display consecutive leave date on out of office message

### PR DESCRIPTION
**Pull request by mba-odoo**
Description of the issue/feature this PR addresses:
Task: https://www.odoo.com/web#id=2002525&action=327&model=project.task&view_type=form&menu_id=4720
Pad: https://pad.odoo.com/p/r.8af0c15014b1a6004e4f2456cca069ee
Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mba-odoo** [comment]
@alexkuhn 
Added tests for consecutive leave. Thanks

**Comment by tde-banana-odoo** [comment]
Hello,

It seems to me there are a few issues with this commit. If I understand well, purpose is to aggregate leaves separated by not working days. I have some concerns about it

  * ``partner_info`` has been optimized to compute out of office information with as few impact as possible. With this patch it seems we loose all optimization efforts, as we rely on a not stored computed field doing quite a lot of computation;
  * it seems you forgot to take into account timezones and DST, which is a main point of issues in resource module;
  * python code lacks readability;
  * finally it seems to randomly crash;

As the feature is interesting but seems to require some additional cleaning and testing, I propose to maybe revert the code and work on a better version. Moreover it would allow to unblock runbot and avoid having to quickly merge fixes that would not benefit from some time consuming review. What do you think ?

Regards,

Thibault.

**Comment by alexkuhn** [comment]
The crash is quite easy to fix, the test just needs a small fix:
https://github.com/odoo-dev/odoo/commit/33804d569a516fc93b557d667bf0639019882697

Agree on other points though, so I will revert and merge it again after few other cleanings.

**Comment by alexkuhn** [comment]
Revert PR: https://github.com/odoo/odoo/pull/41123

**Comment by tde-banana-odoo** [comment]
Well if it is easy to fix, maybe you can just push fix and do an improvement PR instead of reverting, as you wish :) . That way new fields are already in, we should just try to merge it soon so that 13.1 can be tested in a few weeks (probably).

**Pull request closed without merging**
