### PR TITLE
[FIX]: traceback after configuring mail servers accurately, creating …

### PR DESCRIPTION
**Pull request by chv-odoo**
…mass mailing and then clicking on settings->automation->scheduled_actions->run_manually has been solved in this branch.

Description of the issue/feature this PR addresses: https://www.odoo.com/web#id=771841&view_type=form&model=project.issue&action=963&active_id=681&menu_id=4720

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hmo-odoo** [comment]
@xmo-odoo , can you look this PR ?

It's related python3. string.letters is not exits in python3. 
use string.ascii_letters

**Comment by xmo-odoo** [comment]
Looks fine but please rebase on saas-17.

@odony maybe this could even be merged in older versions? According to the Python2 docs, `string.letters` is locale-dependent:

> The concatenation of the strings lowercase and uppercase described below. The specific value is locale-dependent, and will be updated when locale.setlocale() is called.

**Comment by mba-odoo** [comment]
new PR for Saas-17 :  https://github.com/odoo/odoo/pull/19489 Thanks

**Comment by odony** [comment]
@mba-odoo you can simply retarget the PR, not sure why a new one was necessary?

@xmo-odoo sure we could do the patch in 10.0, but as it did not cause any trouble in PY2, I'd avoid the noise and only do it in saas-17

**Comment by xmo-odoo** [comment]
> you can simply retarget the PR, not sure why a new one was necessary?

You also need to rebase and push —force since you're going down rather than up (and thus bringing in all the master commits along for the ride if you just retarget the PR).

**Pull request closed without merging**
