### PR TITLE
[FIX] sale: make payment when journal type is not sale

### PR DESCRIPTION
**Pull request by alsh-odoo**
This traceback arises when a user tries to make a payment on the website.

To reproduce this issue:

1) Install `website_sale`
2) open invoicing/configuration/journals
3) Change the journal type if it is `sales` for all journals
4) Install and enable `Wire Transfer` payment provider in `invocing/configuration/Payment Providers`
5) Now open `website/shop` add any product to `Cart` and proceed to checkout 
6) Make a payment with `Wire Transfer`

Error: 
```
ValueError: Expected singleton: account.journal()
  File "odoo/http.py", line 2134, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1710, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1737, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1851, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "addons/website/models/ir_http.py", line 233, in _dispatch
    response = super()._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 191, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 717, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/payment_custom/controllers/main.py", line 17, in custom_process_transaction
    request.env['payment.transaction'].sudo()._handle_notification_data('custom', post)
  File "addons/payment/models/payment_transaction.py", line 669, in _handle_notification_data
    tx._process_notification_data(notification_data)
  File "addons/payment_custom/models/payment_transaction.py", line 71, in _process_notification_data
    self._set_pending()
  File "addons/sale/models/payment_transaction.py", line 53, in _set_pending
    so.reference = tx._compute_sale_order_reference(so)
  File "addons/sale/models/payment_transaction.py", line 27, in _compute_sale_order_reference
    order_reference = invoice_journal._process_reference_for_sale_order(order_reference)
  File "addons/account/models/account_journal.py", line 912, in _process_reference_for_sale_order
    self.ensure_one()
  File "odoo/models.py", line 5420, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
```
On `_compute_sale_order_reference` method, `invoice_journal` variable is getting values with the reference of `type=sale`.
 
See:-
https://github.com/odoo/odoo/blob/ebc4ed6c4fb11b01be28cf417b27de83d5361cef/addons/sale/models/payment_transaction.py#L20-L30

Because of user changed the type of journal, `invoice_journal` value will be empty recordset and it is referenced to call `_process_reference_for_sale_order` method.

In `_process_reference_for_sale_order` method `ensure_one()` is used, which leads to above traceback.

sentry-4392496618

### CODE REVIEW

**Comment by alsh-odoo** [comment]
Hello @odoo/sentry_reviewers 

Please review this PR

Thank You!!

**Comment by Feyensv** [comment]
Is it really expected for a correctly configured database to have no sale journal ? :thinking:

cc: @yosa-odoo & @oco-odoo ( #124331)

**Comment by oco-odoo** [comment]
@Feyensv Indeed, it doesn't. But here, the fix is just one more line and makes the code a little more robust, so it's alright with me.

**Review by oco-odoo — APPROVED** [review]
@robodoo r+

**Comment by abz-odoo** [comment]
@alsh-odoo

**Pull request closed without merging**
