### PR TITLE
[FIX] account: send and print invoice without attachments

### PR DESCRIPTION
**Pull request by alsh-odoo**
This traceback raises when user tries to send an invoice without attachments.

To reproduce this issue:

1) Install `Accounting`
2) Open any existing `Invoice`
   Note:- Invoice should not be in `Draft`
3) Click `Send & Print`  button an wizard will be opened. 
4) Click on `Send & Print` button of wizard.
5) Now repeat the `Step 3`
6) This time delete the Invoice Attachment and click on `Send & Print` button
   of wizard.

Error: 
```
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/odoo/http.py", line 2126, in __call__
    response = request._serve_db()
  File "/home/odoo/odoo/odoo/odoo/http.py", line 1699, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/odoo/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/odoo/odoo/odoo/http.py", line 1726, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/odoo/odoo/odoo/http.py", line 1930, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/odoo/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/odoo/odoo/odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/odoo/odoo/addons/web/controllers/dataset.py", line 32, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo/odoo/addons/web/controllers/dataset.py", line 24, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/odoo/addons/account/wizard/account_move_send.py", line 568, in action_send_and_print
    self._hook_if_success(success, from_cron=from_cron, allow_fallback_pdf=allow_fallback_pdf)
  File "/home/odoo/odoo/odoo/addons/snailmail_account/wizard/account_move_send.py", line 59, in _hook_if_success
    super()._hook_if_success(moves_data, from_cron=from_cron, allow_fallback_pdf=allow_fallback_pdf)
  File "/home/odoo/odoo/odoo/addons/account/wizard/account_move_send.py", line 411, in _hook_if_success
    self._send_mails(moves_data)
  File "/home/odoo/odoo/odoo/addons/account/wizard/account_move_send.py", line 476, in _send_mails
    mail_params = self._get_mail_params(move)
  File "/home/odoo/odoo/odoo/addons/account/wizard/account_move_send.py", line 450, in _get_mail_params
    self.mail_attachments_widget + self._get_invoice_extra_attachments_data(self.move_ids)
TypeError: unsupported operand type(s) for +: 'bool' and 'list'

```
Note:- This traceback also appears when cron job (`model._cron_account_move_send(job_count=20)`) runs.

On `_get_mail_params` method `attachment_ids` is getting values by concatenating  `mail_attachments_widget` and `invoice_extra_attachments_data`.

See:-
https://github.com/odoo/odoo/blob/27c1384e1209339158f56c82bebf99a5b64811f4/addons/account/wizard/account_move_send.py#L434-L448

Because of user delete the `Invoice attachment` in wizard, the `mail_attachments_widget` will return `False` and 
it leads to above traceback.

Sentry-4305060652

### CODE REVIEW

**Comment by alsh-odoo** [comment]
Hello @odoo/sentry_reviewers 
Please Check this PR.
Thank You!!

**Review by ushyme — CHANGES_REQUESTED** [review]
Thanks for looking into it. Just a small remark:
```py
self.mail_attachments_widget + self._get_invoice_extra_attachments_data(self.move_ids)
```
Based on how that line is written, to me it looks like whatever attachment `self._get_invoice_extra_attachments_data(self.move_ids)` returns should always be sent.
Therefore, I think a fix like this would make more sense:
```py
            attachment_ids = list(set(self._get_email_attachment_ids_from_attachment_data(
                (self.mail_attachments_widget or []) + self._get_invoice_extra_attachments_data(self.move_ids)
            )))
```

**Review by ushyme — APPROVED** [review]
LGTM 👍🏾

**Comment by bit-odoo** [comment]
Hello, @qdp-odoo can you review this PR.

**Pull request closed without merging**
