### PR TITLE
[FIX] account.journal.dashboard.kanban: Replace amount.total by sum residual field

### PR DESCRIPTION
**Pull request by Joaco1980**
Description of the issue/feature this PR addresses:
The accounting control panel is to see in a quick and graphic way the accounting data and the situation of the expenses and income of the company

Current behavior before PR:
In the account control panel, the data of the total balance of the invoices receivable or payable is total amount.

Desired behavior after PR is merged:

The total data of the open invoices should be obtained from the residual field

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@qdp-odoo can you check this one?

**Comment by pedrobaeza** [comment]
@Joaco1980 can you please clean the PR with only one commit?

**Comment by Joaco1980** [comment]
@pedrobaeza Sorry! I'm a newbie in Github!

**Comment by qdp-odoo** [comment]
that's a behavior change in a stable version, which is against our stable policy.

Sorry about that but I have to reject that proposal. The good thing is that we already improved that in-between.

**Comment by pedrobaeza** [comment]
Quentin, but it's a behavior change, because previous one is incorrect!

**Comment by qdp-odoo** [comment]
that's subject to interpretation...

**Comment by pedrobaeza** [comment]
OK, when I read about this in the Spanish mailing lists, it made sense to me, and invite this user to propose the PR, but maybe I didn't read enough. Can you please tell me how did you improve this (I suppose in master)?

**Comment by qdp-odoo** [comment]
no entirely sure when we did it, but it seems it is already there in v12

**Comment by pedrobaeza** [comment]
OK, thanks. I will check out of curiosity. Go to sleep that it's time! :smiley:

**Comment by qdp-odoo** [comment]
https://github.com/odoo/odoo/commit/52a0395040300d1aff09a96c5c732c0ca8528397
but strangely it doesn't seem to touch the computation of 'total'

It is also referenced here https://github.com/odoo/odoo/pull/25859 and there https://github.com/odoo/odoo/pull/19047

and there's that PR https://github.com/odoo/odoo/pull/25880 from Ray, I don't know if we fixed that o_O I'll be checking

**Comment by pedrobaeza** [comment]
Thanks again for your extensive followup of the problem. Waiting then for your final check.

**Comment by qdp-odoo** [comment]
already did it: I closed #25880 since it was already the case

**Comment by pedrobaeza** [comment]
OK, thanks.

**Comment by Joaco1980** [comment]
@pedrobaeza  Thanks for your interets!

**Pull request closed without merging**
