### PR TITLE
[FIX] calendar: multi-day all day recurrent event

### PR DESCRIPTION
**Pull request by jpp-odoo**
- Create a multi-day all day event (for example a 3 days all day event
  3, 4 and 5 November 2020);
- Edit this event to become a recurrent event ( repeat 1x week, 10
  number of repetitions and  check Tuesday);
- Save the event.

Before this commit, the dates of the initial event are modified, and
transform to a single day event (only the 3 November), and all the
repetitions events are also a single day event. This behaviour is also
found when synchronizing a multi-day all day recurrent event from
Google.

Now, the dates of the initial event stay the same, and the recurrent
event are 3 days event, as expected.

opw-2342138

### CODE REVIEW

**Review by nim-odoo — COMMENTED** [review]
```
Also, compute the duration for not allday meeting ; otherwise the duration is set to zero, since the meeting last all the day.
```
That's a weird assumption... If the meeting lasts all the day, then its duration should be 24 hours.

**Comment by nim-odoo** [comment]
fw-bot up to saas-13.3

**Comment by nim-odoo** [comment]
robodoo delegate+

**Comment by jpp-odoo** [comment]
robodoo r+

**Pull request closed without merging**
