### PR TITLE
[FIX] ir_sequence: Fix creating date_range_seq with range_month and range_day

### PR DESCRIPTION
**Pull request by moylop260**
Using range_day the range of the dates for new date_range_sequence
record should be only one day

Using range_month the range of the dates for new date_range_sequence
record should be only one month

Before of this fix the date created was a range of many days or months

It fixes the range of new sequences

Add new unittests

### CODE REVIEW

**Comment by moylop260** [comment]
Hi @mart-e 

Who could help us to review it?

Thanks in advance!

**Comment by frahikLV** [comment]
Hey @moylop260 !

Include the refactor on this PR too

**Comment by legalsylvain** [comment]
hi @mart-e, what is the state of this PR ?

**Comment by qdp-odoo** [comment]
@william-andre I suppose this ain't a problem anymore. Maybe it's just worth checking the tests to see if it is indeed fixed, and see if this is tested or not.

**Comment by william-andre** [comment]
@qdp-odoo This PR is about `ir.sequence`, if you are not confusing it with `sequence.mixin`, so I'm pretty sure nothing has changed regarding this.
Note that the mixin doesn't allow for a range based on days.


I can take a closer look later, but I believe it would be a good idea to go further with this PR. (probably in 15.0 as 14.0 has been deprecated)

**Comment by qdp-odoo** [comment]
> @qdp-odoo This PR is about `ir.sequence`, if you are not confusing it with `sequence.mixin`, so I'm pretty sure nothing has changed regarding this. Note that the mixin doesn't allow for a range based on days.
> 
> I can take a closer look later, but I believe it would be a good idea to go further with this PR. (probably in 15.0 as 14.0 has been deprecated)

I, indeed, asked you without even reading the diff and got confused :see_no_evil: Sorry 'bout that.

I don't understand the commit message, let's assume this either isn't important or is fixed, @moylop260 feel free to reopen and better explain if you think it's still needed.

thanks for the contribution, anyway

**Pull request closed without merging**
