### PR TITLE
[IMP] mail: make portal mixin extend mail thread

### PR DESCRIPTION
**Pull request by xmo-odoo**
The portal mixin overrides _notify_get_groups which comes from mail.thread despite not extending it. It's not a huge issue as that's
a mail.thread hook so nothing untowards would happen, but looking at the various users of mail.thread and discussing with tde:

* more or less every model which uses portal mixin also uses   mail.thread
* the only model which doesn't do so is `sign.request.item` which doesn't have a specific reason *not* to use mail.thread
* according to tde: "pour le bien portal devrait imposer mail thread"

### CODE REVIEW

**Comment by xmo-odoo** [comment]
(sadly trying to handle this in the mixin class or even a base override doesn't work because they don't get invoked when building models)

**Comment by tivisse** [comment]
@xmo-odoo Your second commit is named correctly. Seems hacky.

Otherwise, I agree on the mail.thread inherit thing. 

Thanks.

**Comment by tde-banana-odoo** [comment]
We had to force some ordering in inherit order in some addons, indeed we already had issues with MRO. Are you sure it is effectively working as intended (aka going in portal then mail thread then base (if defined)) ?

I agree with the global scope, I let smart people review the hack itself :D .

**Comment by xmo-odoo** [comment]
ping @rco-odoo do you have an idea for a good solution to this issue?

**Comment by tde-banana-odoo** [comment]
Bloup ?

**Pull request closed without merging**
