### PR TITLE
[IMP] assetsbundle: add filter by res_model field

### PR DESCRIPTION
**Pull request by avkhozov**
get_attachments is slower than you would like, when the odoo system has a large number of attachments. Using a filter on the res_model field (we already have an index on this field) we avoid sequential scanning of a large table and can achieve several times the performance gain.

### CODE REVIEW

**Comment by avkhozov** [comment]
Is there any information about this PR? Should I do something else for merge?

**Comment by sle-odoo** [comment]
Hi,
Out of curiosity, could you share the numbers of records you have in your ir.attachment table and the kind of improvements you're getting with this patch?
Regards

**Comment by avkhozov** [comment]
We have about 2.5M records in ir_attachment:

```
select res_model, count(*) from ir_attachment group by res_model order by 2 desc limit 10;
       res_model       |  count  
-----------------------+---------
 res.partner           | 2277752
 project.task          |   93706
 account.invoice       |   19693
 crm.lead              |    8639
 hr.employee           |    5848
 hr.applicant          |    1703
 ir.ui.view            |     730
 maintenance.equipment |     551
 res.country           |     235
 pos.config            |     203
(10 rows)
```

Without index on `res_model` request execution time about 250ms, but with index about 1ms.

**Comment by avkhozov** [comment]
@sle-odoo Hi, is there enough information now?

**Comment by sle-odoo** [comment]
Hello, you're right but it is even faster on our side if 1) we apply you patch 2) we add a composite index on res_model and create_uid

in base/models/ir_attachment.py you could complete _auto_init
``` python
    def _auto_init(self):
        res = super(IrAttachment, self)._auto_init()
        tools.create_index(self._cr, 'ir_attachment_res_idx',
                           self._table, ['res_model', 'res_id'])
        tools.create_index(self._cr, 'ir_attachment_res_model_create_uid_idx',
                           self._table, ['res_model', 'create_uid'])
        return res
```

can you add this index and share you results? If it's also faster on your side, could you update your pr with these suggested changes?

thanks a lot for your contribution

cc @mart-e

**Comment by avkhozov** [comment]
In our case almost all entries with `res_model = res.partner` was created with `create_id = 1`, so we didn't get any growth performance from the compound index on `res_model` and `create_uid` fields.

Output from the same environment after creating index on `(res_model, create_uid)`:

```
# explain analyze
SELECT max(id)
FROM ir_attachment
WHERE create_uid = 1
  AND url like '/web/content/%-029bdf8/web.assets_frontend.%.css'
GROUP BY name
ORDER BY name;
                                                         QUERY PLAN                                                          
-----------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=121604.63..121604.65 rows=1 width=15) (actual time=522.917..522.917 rows=0 loops=1)
   Group Key: name
   ->  Sort  (cost=121604.63..121604.64 rows=1 width=15) (actual time=522.915..522.915 rows=0 loops=1)
         Sort Key: name
         Sort Method: quicksort  Memory: 25kB
         ->  Seq Scan on ir_attachment  (cost=0.00..121604.62 rows=1 width=15) (actual time=522.910..522.910 rows=0 loops=1)
               Filter: (((url)::text ~~ '/web/content/%-029bdf8/web.assets_frontend.%.css'::text) AND (create_uid = 1))
               Rows Removed by Filter: 2278375
 Planning time: 0.228 ms
 Execution time: 522.941 ms
(10 rows)

Time: 523.648 ms
```

```
# explain analyze
SELECT max(id)
FROM ir_attachment
WHERE create_uid = 1
  AND url like '/web/content/%-029bdf8/web.assets_frontend.%.css'
  AND res_model = 'ir.ui.view'
GROUP BY name
ORDER BY name;
                                                                         QUERY PLAN                                                                          
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=2459.59..2459.61 rows=1 width=15) (actual time=3.593..3.593 rows=0 loops=1)
   Group Key: name
   ->  Sort  (cost=2459.59..2459.59 rows=1 width=15) (actual time=3.592..3.592 rows=0 loops=1)
         Sort Key: name
         Sort Method: quicksort  Memory: 25kB
         ->  Index Scan using ir_attachment_res_model_index on ir_attachment  (cost=0.43..2459.58 rows=1 width=15) (actual time=3.586..3.586 rows=0 loops=1)
               Index Cond: ((res_model)::text = 'ir.ui.view'::text)
               Filter: (((url)::text ~~ '/web/content/%-029bdf8/web.assets_frontend.%.css'::text) AND (create_uid = 1))
               Rows Removed by Filter: 724
 Planning time: 0.275 ms
 Execution time: 3.619 ms
(11 rows)

Time: 4.302 ms
```

**Comment by mart-e** [comment]
> In our case almost all entries with `res_model = res.partner` was created with `create_id = 1`, so we didn't get any growth performance from the compound index on `res_model` and `create_uid` fields.

This is a bit of an uncommon scenario. I guess your attachments were imported or created  through an external system?
The indexes are always a bit case by case and should be tweaked based on one's usage but I still believe that the index Simon gave you is a good default for "average db".

If you modify your PR to add it, I can merge it.

Thanks

**Comment by avkhozov** [comment]
For me it is very consistent to have a filter on `res_model = ir.ui.view` in the `get_attachments`, because we only insert such values in `save_attachment` method. Moreover, we already have an index on `res_model` field, so such modification of the query becomes even more optimal and not just logical.

Adding a new index is not exactly related to the original pr, so you may close it if you don't plan to merge it in the current form.

Thank you for your time anyway!

**Pull request closed without merging**
