### PR TITLE
Integration of JS docstrings to Sphinx doc

### PR DESCRIPTION
**Pull request by xmo-odoo**
## Main purpose

* extracts information from JS sources and provides a Sphinx plugin for integration
  - also provides a CLI tool to dump module dependencies (may not be complete anymore)
* automatic structural inference based on Odoo codebase structures
  - automatically infers modules, their name and their dependencies based on the  `odoo.define(<name>, function ([<requirefunc>])` pattern, the first parameter of the callback is assumed to be the require function (but is optional for modules with no dependencies)
  - automatically infers classes using the standard odoo pattern (`Subclass = Superclass.extend({})`)
  - automatically infers constructors (a method called `init` in a class)
  - resolves and cross-links module dependencies, class mixins and superclasses
  - parses and cross-links types in other contexts (return values, param types)
* supports `@class`, `@mixin`, `@namespace`, `@type` to override incorrect inferences (object literals are usually inferred as namespaces)
* supports `@private`, `@param`, `@returns` annotations
* provides `js:automodule`, `js:autoclass`, `js:autofunction`, `js:autonamespace`, `js:automixin` directives with ~similar semantics to autodoc's which can be used for fine-grained organisation and additional documentation
  - supports relevant autodoc options:
    + `:members:` to document all/specific members by default
    + `:undoc-members` to document members which don't have any documentation
    + `:private-members` to document members marked as private)
  - `automodule` further supports globbing module names (e.g. `*` will match all modules `web.*` will match all modules starting with `web.`). In case of globbing, only modules with documentation and/or an export are documented. This can be overriden with `:undoc-matches:` (which documents all matching modules period)
  - [untested] use `js:data` and `js:attribute` when manually documenting those
* extracts `@typedef`/`@property` comment blocks (the entire block is considered part of the typedef), and automatically generates typedefs from "compound" parameter names (e.g. `@param bar.baz` on a function foo will extract a typedef for `FooBar` with a property `baz`)

### Todo
Not strictly necessary (?) but could be neat future additions
- [ ] linkcode_resolve (link symbols to github source as is done in Python)
    🚫 requires source location of AST nodes, pyjsparser does not add them, would require esprima-python and copying locations (at least start line) from AST node to doc
    linkcode on JS only transfers the "object" and "fullname" attributes of `desc_signature`, so either put the actual location straight into these *or* share modules map between extensions (put on app? may also obviate the need for the `auto*_bound` intermediate functions)
- [ ] fix some duplication issues between module body symbols and exports?
- [ ] annotate and possibly filter (out) include-ed members of classes
    * maybe UI to do that easily e.g. be able to "deselect" a module hiding its documentation, all of its dependents and all the symbols they add elsewhere?

### Notes
* built specifically for the Odoo JS codebase and its structure/patterns, not a general-purpose JS documentation tool
* `@typedef` blocks are only checked at the module toplevel (callback body)
* cross-linking tries to get the source module right, this may not always work
* JS parsing is lazy, aside from full documentation rebuild, JS files will be parsed only if a JS file or a document invoking an autojs directive were edited since the last build

## Also
* fixes or removes a bunch of incorrect JS docstrings, though there probably are many which still aren't quite correct (e.g. typo in jsdoc tags, leading to them being ignored)
* removes the existing (most likely outdated) javascript prose doc, and just dumps all modules doc there. Would probably need to be improved.
* much of the added LOCs are because I had to vendor pyjsparser to add comments support to it, an alternative would be rebuilding on top of [pyesprima](https://github.com/Kronuz/esprima-python) which I believe supports comments OOTB and furthermore fully supports JSX and ES2017 (pyjsparser only supports parts of ES6), to check

### CODE REVIEW

**Comment by ged-odoo** [comment]
merged in saas-18 (squashed, slightly edited, ...)

**Comment by Yajo** [comment]
So do we have js docs now? Where?

**Comment by xmo-odoo** [comment]
> So do we have js docs now? Where?

Not exactly/only on your machine.

There is no "running" documentation for master, only for "full" versions (/cc @KangOl). Furthermore the web team will need to craft its documents to set things up appropriately (e.g. only document relevant modules, possibly add further information, ...), currently it just drops the docstrings for every module in an undefined order.

**Comment by ged-odoo** [comment]
@Yajo  We will have some documentation auto-generated from JS docstring in https://www.odoo.com/documentation/11.0/

This documentation will be generated every night or so, and will be uptodate in theory.  The good thing is that it gives a reference to point to, and will allow us to see various overrides in one place. But this basically does not bring much more than the doc that you can see in the code.

I hoped that I could take a week to work on writing 'generic' documentation.  Some documentation to give a nice overview of how the code is organized, how it is structured, ... But this will be for after Odoo Experience.

**Comment by Yajo** [comment]
OK thanks, a big step forwards anyway 😉

**Pull request closed without merging**
