### PR TITLE
[9.0] fix use symbol c in sql create

### PR DESCRIPTION
**Pull request by yvaucher**
Same as https://github.com/odoo/odoo/pull/5620 for 9.0 with solving merge conflict to patch Odoo in order to be able to use geoengine.

### CODE REVIEW

**Comment by rco-odoo** [comment]
@yvaucher the request #5620 has just been merged in 8.0, and will soon be forward-ported in 9.0.

**Comment by yvaucher** [comment]
@rco-odoo Ok thanks

**Comment by rco-odoo** [comment]
The issue has been fixed by forward-porting the fix from 8.0.

**Comment by yvaucher** [comment]
Thanks

**Pull request closed without merging**
