### PR TITLE
[BUG] core: add tests to compare search with filtered_domain on x2m subqueries

### PR DESCRIPTION
**Pull request by ivantodorovich**
This PR adds unit tests that reproduces an existing bug with `filtered_domain`.
~It targets `14.0` but the same issue still exists in `master`.~

I might try to propose a fix later, but it's not clear to me how it should be fixed. I'm not sure what the desired behaviour is (SQL vs filtered_domain). More about this below..

It involves domains that filter records through a `x2m` relation field, and a negative operator.
For example, take the following domain, to be applied on `res.partner` records:

```py
[("child_ids.state_id", "!=", 1)]
```

Using this domain on `search` will get you records having at least one children with a `state_id != 1`.
- The records have to have children. Recods without children won't satisfy the condition.
- The records could have children with `state_id = 1`, they are returned because they have at least 1 other children with `state_id != 1`.

However, `filtered_domain` will get you records that don't have any children with `state_id = 1`.
- The records without children will satisfy the condition
- The records having any child with `state_id = 1` won't satisfy the condition

You see, both statements are similar, and maybe confusing, but they're definitely not the same.

Which one is the correct one? Difficult to say.
For sure, though, the SQL expressions were created first, so maybe we should consider that one as the correct one.

---

Although, if we consider the SQL expression to be the correct one, I'd like to point out another issue with it:

What if you want to `search` partners **not** having any children with `state_id = 1` ? (the current `filtered_domain` result). Knowing how it's interpreted, you might be tempted to write this:

```py
["!", ("child_ids.state_id", "=", 1)]
```

However, the "not" is distributed and the effective resulting domain goes back to:

```py
[("child_ids.state_id", "!=", 1)]
```

Which, then again, is not the same thing. It would give you partners having at least one children with `state_id != 1`.

In this regard, the current result of `filtered_domain` is coherent with the `distribute_not` behaviour. It's also the most intuitive result, IMO.. and the one that really counterparts/negates its opposite expression `[("child_ids.state_id", "=", 1)]`.

ping @rco-odoo @ryv-odoo 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Julien00859** [comment]
up @odoo/rd-framework-py

**Comment by ryv-odoo** [comment]
Hello @ivantodorovich , Thank you for the bug report and the clear test to show the issue. 

This PR fixes the issue (and it introduce any/all operator to remove the confusion) : https://github.com/odoo/odoo/pull/92181
We should continue to work on it and if we cannot add the new feature, we will at minimum fix the issue.

However, I am not sure if we can fix it in stable, because some ir.rule behavior will change (by example, `helpdesk_stage_company_rule` or `hr_appraisal_rule_base_user`, ...).

**Comment by ivantodorovich** [comment]
Thanks for your response @ryv-odoo ;)
That PR definitely looks promising

**Comment by ivantodorovich** [comment]
Rebased & re-targetted `master`

**Comment by ivantodorovich** [comment]
I've just rebased on top of master to check if the issue still exists. Unfortunately it still does 😞

**Comment by kmagusiak** [comment]
Hello,

I have a bunch of tests on expressions in #171291, can I add yours to that pile?
We have already fixed some bugs recently in expression.py, not all, but maybe this one is fixed.

Best regards!

**Comment by ivantodorovich** [comment]
Hello @kmagusiak !

Thanks for taking care of this ! ❤️ 
Certainly, feel free to add this unit test to your PR :)

**Comment by kmagusiak** [comment]
Test taken over.

**Pull request closed without merging**
