### PR TITLE
[IMP] fields.py: meaningful error for incomplete computed field

### PR DESCRIPTION
**Pull request by beledouxdenis**
Raise a meaningful message for the developer when
a compute field does not set a value for all records passed in self
and raise a mysterious `CacheMiss` (or `AccessError` in for a stored computed field).

### CODE REVIEW

**Comment by beledouxdenis** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
Oops though this PR had failed because of the corruption of runbot17 but that wasn't the case.

@robodoo r-

**Comment by mreficent** [comment]
@xmo-odoo @beledouxdenis will this get merged someday?

**Comment by beledouxdenis** [comment]
Yea

**Comment by MiquelRForgeFlow** [comment]
any news on this, buddies? 😆

**Comment by beledouxdenis** [comment]
Closed with #56269

**Pull request closed without merging**
