### PR TITLE
Update __manifest__.py

### PR DESCRIPTION
**Pull request by bumanit**
Add Author param on manifest

"author" : "BumanIT LLC, Odoo S.A",

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@jco-odoo do you agree? I see from 3d755262e54881d1ca7b6f9535b23d0cdd309c8e that BumanIT LLC helped a lot.

@bumanit Thank you for you patch but it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by jco-odoo** [comment]
@mart-e Indeed, so no problem for me, but of course better to have the CLA too. (other PRs might follow)

**Comment by bumanit** [comment]
Hello Dears,


We already added our CLA on

odoo<https://github.com/odoo/odoo>/doc<https://github.com/odoo/odoo/tree/12.0/doc>/cla<https://github.com/odoo/odoo/tree/12.0/doc/cla>/corporate<https://github.com/odoo/odoo/tree/12.0/doc/cla/corporate>/bumanit.md​

12.0 branch.




Regards



[Baskhuu-Angli.jpg (800Ã—182)]



________________________________

**Comment by mart-e** [comment]
Indeed, the CLA has been signed but with a different email

- you are signing _using_ the address `b...@bumanit.mn`
- the CLA was signed _for_ the address `b...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or add the second email in the CLA signature.

Thanks

**Comment by mart-e** [comment]
I have modified your PR to match the author of your CLA, now it should be validated !

Thanks

@robodoo r+

**Comment by mart-e** [comment]
Oups, forgot to rebase, now it should be good

@robodoo r+

**Comment by mart-e** [comment]
robodoo retry

**Pull request closed without merging**
