### PR TITLE
Fixes the error ERROR: couldn't create the logfile directory. Logging…

### PR DESCRIPTION
**Pull request by MagnusKriel**
see issue: https://github.com/odoo/odoo/issues/26447

**Description of the issue/feature this PR addresses:**
Fixes the error: "ERROR: couldn't create the logfile directory. Logging to the standard output."
when log rotate is enabled and workers = None

**Current behavior before PR:**
When having log rotate enabled but workers set to None/False or 0 (Will default to None) an exception is raised saying: "ERROR: couldn't create the logfile directory. Logging to the standard output." after which Odoo reveres to logging to stdout instead.

**Desired behavior after PR is merged:**
Should be able to enable log rotate whilst workers are set to 0/False/None and successfully log to files.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@xmo-odoo could you have a look please?

**Comment by xmo-odoo** [comment]
@MagnusKriel you're on Windows correct?

Could you try an alternative change of moving the "workers" string from "posix_keys" to "keys" in config.py (around line 435)?

**Comment by xmo-odoo** [comment]
@MagnusKriel you're on Windows correct?

**Comment by xmo-odoo** [comment]
@MagnusKriel if yes could you try the following alternative fix: in config.py, move `workers` from `posix_keys` to `keys` (around like 435) then add `'workers': 0` in the `self.options` map (around line 75)?

**Comment by MagnusKriel** [comment]
@xmo-odoo This is on Windows yes. I will try out your recommendation but and if it works, must I create a new pull request for that?

**Comment by xmo-odoo** [comment]
@MagnusKriel nah it's fine I'll just fix it.

**Comment by MagnusKriel** [comment]
@xmo-odoo I tried your suggested fix (moving the 'workers' around) but get this exception:

` File "C:\Program Files (x86)\Odoo 11.0\server\odoo-bin", line 5, in <module>
    import odoo
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\__init__.py", line 84, in <module>
    from . import modules
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\graph.py", line 10, in <module>
    import odoo.tools as tools
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\__init__.py", line 8, in <module>
    from .config import config
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\config.py", line 649, in <module>
    config = configmanager()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\config.py", line 317, in __init__
    self._parse_config()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\config.py", line 448, in _parse_config
    if getattr(opt, arg) is not None:
AttributeError: 'Values' object has no attribute 'workers'`

**Pull request merged**
