### PR TITLE
[IMP] project: add task dependencies in demo data

### PR DESCRIPTION
**Pull request by IT-Ideas**
This commit adds task dependencies data in the demo data.

task-2647340
Related PR: odoo/enterprise#21391

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
LGTM, thanks 🙂

**Comment by xavierbol** [comment]
Don't forget to retarget this PR. 🙂

**Comment by IT-Ideas** [comment]
@robodoo r+

**Review by xavierbol — APPROVED** [review]
LGTM, thanks 🙂

**Pull request closed without merging**
