### PR TITLE
[FIX] web: fix and adapt select2 for dark mode

### PR DESCRIPTION
**Pull request by Brieuc-brd**
This PR fixes and adapts several issues on the `select2` component for the dark mode.

Requires:
- https://github.com/odoo/enterprise/pull/32694

task-2710677

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
@stefanorigano 👋

**Comment by stefanorigano** [comment]
Hello @adr-odoo and @aab-odoo , here a fix for the select2 "component" on dark-mode.
Complex scenario, we need to customize the design while keeping the lib untouched.

We propose to move the base customization code in a dedicated webclient folder... the same in [enterprise](https://github.com/odoo/enterprise/pull/32694) to handle dark-mode.

Please note that currently the component's design is kind of broken, especially in dark-mode, since it has not  been merged correctly during https://github.com/odoo/odoo/pull/99755

**Comment by Brieuc-brd** [comment]
Hello @adr-odoo and @aab-odoo, little reminder :)

**Review by adr-odoo — APPROVED** [review]
@robodoo rebase-ff r+

**Pull request closed without merging**
