### PR TITLE
[fix] models: it will check the relation model authority when type of…

### PR DESCRIPTION
**Pull request by roganw**
… _rec_name field is many2one, while computing the display name of current record.

Description of the issue/feature this PR addresses:  fix _compute_display_name error.

Current behavior before PR: it will raise an error when current user has no access to relation model of _rec_name, whick is a many2one field.

Desired behavior after PR is merged: won't raise error when execute _compute_display_name method.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the PR but I am not sure to get the issue.
You are talking about many2one but the field is [already read with sudo](https://github.com/odoo/odoo/blob/79519ce40096b64d447c293c241c1ef9c05c99e3/odoo/fields.py#L1922)
If it is an issue in the name_get of a model, it is this override that should check the access rights.
Please give a way to reproduce the bug.

**Comment by RoganW** [comment]
When you get the display_name of model A (step 1), whick _rec_name is a many2one field related to model B, 
methods call path:  
Step 1:
``` python
    @api.depends(lambda self: (self._rec_name,) if self._rec_name else ())
    def _compute_display_name(self):
        names = dict(self.name_get())   ### call step 2
        for record in self:
            record.display_name = names.get(record.id, False)
```
Step 2:
``` python
    @api.multi
    def name_get(self):
        """ name_get() -> [(id, name), ...]

        Returns a textual representation for the records in ``self``.
        By default this is the value of the ``display_name`` field.

        :return: list of pairs ``(id, text_repr)`` for each records
        :rtype: list(tuple)
        """
        result = []
        name = self._rec_name
        if name in self._fields:
            convert = self._fields[name].convert_to_display_name   ### call step 3
            for record in self:
                result.append((record.id, convert(record[name], record)))
        else:
            for record in self:
                result.append((record.id, "%s,%s" % (record._name, record.id)))

        return result
```
Step 3 in **class Many2one(_Relational)**:
``` python
    def convert_to_display_name(self, value, record):
        return ustr(value.display_name)  ### call step 4
```
Step 4,  (_rec_name).display_name will **Call Step 1 and Step 2 of model B**, (such as the _rec_name of model B is 'note'), which will check the authority or model B:   
``` python
    B._compute_display_name()
    B.name_get()
```

**Comment by mart-e** [comment]
Thank you for the details. However making all name_get be executed as `sudo` is a bit too risky. Some may be broken.

For instance, with your patch, the [display_name](https://github.com/odoo/odoo/blob/7413b2624c6554bf641c2426c45c70fd59bc7490/addons/hr_holidays/models/hr_holidays.py#L115) of hr.holidays.status would not work as [using the current user](https://github.com/odoo/odoo/blob/7413b2624c6554bf641c2426c45c70fd59bc7490/addons/hr_holidays/models/hr_holidays.py#L102) to display the number of remaining leavers.

Instead, what do you think of adding the sudo only in the `convert_to_display_name` method?

**Comment by RoganW** [comment]
When _rec_name of model A is a many2one field related to `hr.holidays.status` , sudo() used in `convert_to_display_name` still change the uid. 
It's aways conflict with getting info of current user in `name_get`.  

I think there are lots of other methods `related to current user`,  and sudo is prohibition to use in these context, why not odoo adopt an universal solution to fix these problems?  
Like [suspend_security](https://github.com/OCA/server-tools/tree/10.0/base_suspend_security)

**Comment by tde-banana-odoo** [comment]
I think there was a discussion with @rco-odoo in order to somehow alwas be able to have access to the display_name of a related may2one.

However this could break names based on uid, which indicates we could want to keep the current user id somehow. I bet @rco-odoo will probably have a lot of things to say about that topic.

**Comment by RoganW** [comment]
@tde-banana-odoo 
There is a solution not only keep the current uid, but also skip the permission check like `sudo`, see [suspend_security](https://github.com/OCA/server-tools/tree/10.0/base_suspend_security).

**Comment by C3POdoo** [comment]
Dear @roganw,

Thank you for your contribution but the version 10.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
