### PR TITLE
[FIX] website_sale: don't  translate CSS classes

### PR DESCRIPTION
**Pull request by sindhav**
Before this commit:
- Pagination layout on the ecommerce page is mess-up

After this commit:
- Pagination layout on the ecommerce page will remain same in all language

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sindhav** [comment]
Issue Before this PR:

fix-language

**Comment by xmo-odoo** [comment]
Seems rather more like an issue with the term being translatable at all, it should probably use a `<t t-set t-value/>` instead of a `<t t-set>content</t>`

**Comment by sindhav** [comment]
I tried your suggestion @xmo-odoo but getting error while parsing the template.
Tranceback log as as under:

 
Traceback (most recent call last):
  File "/home/bista/workspace/10.0/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/home/bista/workspace/10.0/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/home/bista/workspace/10.0/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/home/bista/workspace/10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/bista/workspace/10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/bista/workspace/10.0/odoo/http.py", line 329, in checked_call
    result.flatten()
  File "/home/bista/workspace/10.0/odoo/http.py", line 1259, in flatten
    self.response.append(self.render())
  File "/home/bista/workspace/10.0/odoo/http.py", line 1252, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_ui_view.py", line 1039, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/bista/workspace/10.0/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/home/bista/workspace/10.0/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_ui_view.py", line 1059, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-19>", line 2, in compile
  File "/home/bista/workspace/10.0/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 73, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 287, in compile
    raise QWebException("Error when compiling AST", e, path, etree.tostring(node[0]), name)
QWebException: invalid syntax (<unknown>, line 1)
Traceback (most recent call last):
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 277, in compile
    body = self._compile_node(element, _options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 632, in _compile_node
    return body + self._compile_directives(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 653, in _compile_directives
    return compile_handler(el, options)
  File "/home/bista/workspace/10.0/addons/web_editor/models/ir_qweb.py", line 55, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 876, in _compile_directive_tag
    content = self._compile_directives(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 653, in _compile_directives
    return compile_handler(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 937, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 632, in _compile_node
    return body + self._compile_directives(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 653, in _compile_directives
    return compile_handler(el, options)
  File "/home/bista/workspace/10.0/addons/web_editor/models/ir_qweb.py", line 55, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 876, in _compile_directive_tag
    content = self._compile_directives(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 653, in _compile_directives
    return compile_handler(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 1259, in _compile_directive_call
    body = self._compile_directive_content(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 937, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 623, in _compile_node
    return self._compile_static_node(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 703, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 937, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 623, in _compile_node
    return self._compile_static_node(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 703, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 937, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 623, in _compile_node
    return self._compile_static_node(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 703, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 937, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 623, in _compile_node
    return self._compile_static_node(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 703, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 937, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 632, in _compile_node
    return body + self._compile_directives(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 653, in _compile_directives
    return compile_handler(el, options)
  File "/home/bista/workspace/10.0/addons/web_editor/models/ir_qweb.py", line 55, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 876, in _compile_directive_tag
    content = self._compile_directives(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 653, in _compile_directives
    return compile_handler(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 1259, in _compile_directive_call
    body = self._compile_directive_content(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 937, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 632, in _compile_node
    return body + self._compile_directives(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 653, in _compile_directives
    return compile_handler(el, options)
  File "/home/bista/workspace/10.0/addons/web_editor/models/ir_qweb.py", line 55, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 876, in _compile_directive_tag
    content = self._compile_directives(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 653, in _compile_directives
    return compile_handler(el, options)
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 885, in _compile_directive_set
    value = self._compile_expr(el.attrib.pop('t-value'))
  File "/home/bista/workspace/10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 300, in _compile_expr
    st = ast.parse(expr.strip(), mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    pagination form-inline o_website_sale_search
                  ^
SyntaxError: invalid syntax

Error when compiling AST
SyntaxError: invalid syntax (<unknown>, line 1)
Template: 679
Path: /templates/t/t/div/div[2]/div[1]/div/t[1]/t
Node: <t t-content="True"/>

**Comment by xmo-odoo** [comment]
the content of the t-value attribute is a Python expression, so you need to add quotes inside the quotes which I'm guessing you forgot aka `t-value="'pagination form-inline o_website_sale_search'"`

**Comment by sindhav** [comment]
@xmo-odoo I checked with both the way with quote and without the quote.

**Comment by mart-e** [comment]
@sindhav if you gave us the code, it would probably help us to tell you what is wrong

**Comment by sindhav** [comment]
Oppss, I did a mistake while testing. Working fine as per the xmo suggestion. I have update PR accordingly.
Thank you @xmo-odoo and @mart-e

**Comment by mart-e** [comment]
Thanks, merged

6d7648e9f0c [FIX] website_sale: don't translate CSS classes
f0c9275e35f [CLA] Signature for sindhav

**Pull request closed without merging**
