### PR TITLE
[11.0] improve support for odoo.addons namespace package

### PR DESCRIPTION
**Pull request by sbidoul**
This fixes #15718 for python 3 in a much more reliable way.

More information here:
https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages

@odony I really hope this is acceptable for you.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by d-fence** [comment]
@KangOl As discussed at the coffee machine, this PR make sense to me as it solves some packaging issues. Can you have an eye on it to evaluate possible other implications in Odoo ?

**Comment by d-fence** [comment]
@odony may I ask you to put your two-cents in too ? Thanks

**Comment by odony** [comment]
@sbidoul thanks for your efforts, this looks like a much better and longer-lasting fix :-)

Merged in saas-17 at 8bf06adc8d78c1bff8dc80ce53d6646e3ad22fff, will be ported to saas-18 and master soon (and eventually 11.0)

**Comment by sbidoul** [comment]
Thanks! This explanation (https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages) is fairly recent and made things much more obvious :)

**Pull request closed without merging**
