### PR TITLE
[FIX] l10n_cl: add l10n_cl_activity_description field to community

### PR DESCRIPTION
**Pull request by Danisan**
since this value is used as a required field in website sale

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fvz-odoo** [comment]
Hello @Danisan 

Both PRs look good to me, this one and the enterprise (https://github.com/odoo/enterprise/pull/29462). Ready for your technical review @jco-odoo.

Cheers!

Fernando

@ren-odoo @vbe-odoo @hea-bmya

**Comment by jco-odoo** [comment]
@Danisan It might be a good thing to move it for the res_company as well.

**Comment by jco-odoo** [comment]
Not sure for the settings however.

**Comment by Danisan** [comment]
@jco-odoo @fvz-odoo Please check. This is ready and paired with https://github.com/odoo/enterprise/pull/29462

**Comment by fvz-odoo** [comment]
Hello @Danisan 

I'm not sure if I'm checking the correct thing, but I don't see the change for the res.company. For contacts, I see the activity description below the taxpayer type which I think is ok. But for the company I don't see it... Let me know please.

Fernando

**Comment by fvz-odoo** [comment]
Thanks @Danisan 

I just checked and it is now working. Ready for final technical review from @jco-odoo 

Cheers!

Fernando

**Comment by fvz-odoo** [comment]
Hi @jco-odoo 

Remember to add the migration script here and to check why the ci/upgrade_enterprise check failed. Let me know if there's anything to do from my side.

Cheers!

Fernando

**Comment by fvz-odoo** [comment]
Hi @jco-odoo 

I see you added a commit here, is there anything to do here on my side? Or can we merge already? (I tested it and LGTM).

Cheers,

Fernando

@Danisan

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
