### PR TITLE
[IMP] im_livechat: move the chatbox

### PR DESCRIPTION
**Pull request by sga-odoo**
**PURPOSE**
https://tinyurl.com/y4lt79t5

**LINKS**
TaskID: 2369225
Closes: https://github.com/odoo/odoo/pull/61649

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@sga-odoo I tweaked your PR to:
- target 14.0 instead of master
- not adding a CSS rule in im_livechat which uses an editor variable. As a fix I would prefer the opposite hack: adding a rule in website which would be useless if livechat is not installed.

However, I am not sure if there is not a better alternative file in website_livechat... @seb-odoo could you help me gain time? I see you created bugfixes scss file in website_livechat, should I use that? -> where is the ideal way to add scss to style the livechat popups in website edit mode only in 14.0 and master ? :)

**Comment by seb-odoo** [comment]
`website_livechat` would be a good place, as it depends on both modules you want to target and it is `auto_install`.
Of course it would be nice if the fix was present even if `website_livechat` is removed (it's possible to have just `website` + `im_livechat`), but that implies breaking module structure and having to reference either `website` in `im_livechat` or vice-versa.

Bugfile files are made to not "pollute" other files with crap (or when "other files" don't even exist, as is the case here), so if you can't find a better file to put a fix that's a good place.
Fortunately we do have one inside `assets_frontend` for `website_livechat` that is ready: `addons/website_livechat/static/src/bugfix/public_bugfix.scss`
If we didn't mess up the assets, it should be ready to go and working from the start, without requiring a -u on the server.

The fix inside `im_livechat` is fine as it is in `public_livechat.scss` as it already exists and the legacy folder is to be cleaned up anyway.

**Comment by seb-odoo** [comment]
I guess in master the ideal file would be in assets `assets_editor_inherit_website_livechat`? But we don't have any css in there in v14 so that's not going to work, unless you consider acceptable to get the fix only with -u.

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

@seb-odoo I guess the bug is not critical at all but since we can fix it for all users, I guess it does not hurt to do so; I used the public_bugfix file of website_livechat. Note: `assets_editor_inherit_website_livechat` would not be entirely correct to use either since it's the asset which is loaded for users with editor access rights but not when they are in edit mode (for that there is assets_wysiwyg... at least in 14.0...).

**Pull request closed without merging**
