### PR TITLE
impossible to create a uom

### PR DESCRIPTION
**Pull request by romaric-oci**
Description of the problem / characteristic addressed by this PR:
impossible to create a uom

Current behavior before PR:
the form only allows to create a uom reference - which is not possible

Desired behavior after PR fusion:
be able to create a bigger / smaller uom

### CODE REVIEW

**Comment by romaric-oci** [comment]
hi @mart-e , what should i do here?

**Comment by mart-e** [comment]
@romaric-oci I have rebased your branch but you should check to update your source tree for future pull requests.
I let the inventory team check this as it seem they have introduced it on purpose at 6f182eeeab082b094563836a7a3dc2f4e56375f0

**Comment by romaric-oci** [comment]
> @romaric-oci I have rebased your branch but you should check to update your source tree for future pull requests. I let the inventory team check this as it seem they have introduced it on purpose at [6f182ee](https://github.com/odoo/odoo/commit/6f182eeeab082b094563836a7a3dc2f4e56375f0)

I suggest this as it is the view opened from the link in the view res.config.settings
nota bene: but it is possible to create uom from the tab's lines on the item "category uom" accessible via Stock / Configuration / uom.category

**Comment by ajf-odoo** [comment]
@mart-e @romaric-oci 
Same question a few days ago,
https://github.com/odoo/odoo/pull/80659

**Comment by mart-e** [comment]
Closing as fixed at #80659 let us know if there is still an issue

**Pull request closed without merging**
