### PR TITLE
[REM] l10n_mx: remove module_l10n_mx_edi setting field

### PR DESCRIPTION
**Pull request by yosuanicolaus**
Remove the setting that allows user to install/uninstall l10n_mx_edi.

When a MX database is created, l10n_mx_edi is automatically installed, which means the checkbox doesn't add a lot of value now.

Previously the main reason for the option was for companies that were using accounting in Odoo but EDI outside Odoo, but this case is less common now.

task-id: 3800648

### CODE REVIEW

**Review by smetl — APPROVED** [review]

**Comment by smetl** [comment]
@yosuanicolaus You also need a migration script to remove both the view and the field :)

**Comment by smetl** [comment]
@robodoo r+

**Comment by yosuanicolaus** [comment]
@smetl need r+ again. I just rebased

**Comment by smetl** [comment]
@robodoo r+

**Pull request closed without merging**
