### PR TITLE
[IMP] pos_mercury: Use correct xml_id

### PR DESCRIPTION
**Pull request by sswapnesh**
Follow up on https://github.com/odoo/odoo/pull/35471#discussion_r311180117

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

Cc: @jorenvo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
I would say that it's better to wait the other commit gets forward ported to `master`, then do you do a rebase of this PR and do the full cleanup.

**Comment by jorenvo** [comment]
As @mreficent said indeed you should wait until it hits master. Also I see that now @switch87 has already done this in 12.0 at https://github.com/odoo/odoo/commit/cb70c8078128aed370d7566971e2c4979cb4708d. So now both xml ids have been renamed in stable. I think that's enough renaming for now.

**Comment by sswapnesh** [comment]
@jorenvo Yes, This is not needed  since it is already handled on https://github.com/odoo/odoo/commit/cb70c8078128aed370d7566971e2c4979cb4708d

(@mreficent  You are right, I forgot about this fact)

**Comment by sswapnesh** [comment]
@jorenvo  Would be great to remove https://github.com/odoo/odoo/commit/48b3893b84cbd51f880548b38d036db5ebc1e256#diff-c79d9a6f9348953cbce7c8c9919ce616R3 comment about changing xml_id (along with_2 on xml_id) in master.

(Maybe in future when someone is touching that)

**Comment by switch87** [comment]
@jorenvo Sorry, we where totally unaware of this pr in the PoS team and found this bug true another pr of @sswapnesh 😅

**Comment by jorenvo** [comment]
Yeah no worrries :). Yours is the more correct fix, but we decided against it because chances are higher someone inherited it with the old xml id. That being said, it's not a commonly used module so overall the chances are low.

**Pull request closed without merging**
