### PR TITLE
[IMP] clean up image mixin

### PR DESCRIPTION
**Pull request by seb-odoo**
part of task-1949729

### CODE REVIEW

**Comment by seb-odoo** [comment]
Still waiting on runbot status and a bit more testing actually.

**Comment by seb-odoo** [comment]
@JKE-be I'm ok with this one one, I tested what I wanted and fixed all problems I saw, and added tests for them.

**Comment by JKE-be** [comment]
@robodoo r+

thks @KangOl for review

thks @seb-odoo for dev

**Comment by KangOl** [comment]
@robodoo retry

**Pull request closed without merging**
