### PR TITLE
[FIX] project, sale_project: side panel layout

### PR DESCRIPTION
**Pull request by Brieuc-brd**
This commit adapts the spaces and table layouts to maintain concistency with Milk design.

Requires: 
- https://github.com/odoo/enterprise/pull/43596

task-3382174
Part of task-3326263

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hey @edi-odoo 👋 could you check these PRs ? (COM and ENT)

**Review by edi-odoo — CHANGES_REQUESTED** [review]
Just wondering if these should be `text-danger`/`-warning` if they're `0` though.
Screenshot 2023-07-05 at 13 47 50

Small detail: the spaces aren't the same, could you check ? 
Screenshot 2023-07-05 at 13 52 20

Last thing just to annoy you: on mobile, clicking on the arrow has no effect
Screenshot 2023-07-05 at 13 54 36

**Comment by Brieuc-brd** [comment]
Hey @edi-odoo 👋 

> Just wondering if these should be text-danger/-warning if they're 0 though

Following https://github.com/odoo/enterprise/blob/master/project_account_budget/static/src/components/project_right_side_panel/project_right_side_panel.xml#L70 , I think this was done on purpose.

> Small detail: the spaces aren't the same, could you check ?

Fixed ✅ 

> Last thing just to annoy you: on mobile, clicking on the arrow has no effect

Fixed ✅ 


Can you check the PR again ? :)

**Review by edi-odoo — APPROVED** [review]

**Comment by edi-odoo** [comment]
👍 LGTM! Thanks for your work ;)

**Comment by Brieuc-brd** [comment]
Hello @pparidans 👋 These PRs (Com. and Ent.) are ready for tech review :)

**Review by pparidans — CHANGES_REQUESTED** [review]
Looks good. Two simple remarks, though.

**Comment by Brieuc-brd** [comment]
Hey @pparidans, thanks for your review 👍 
I fixed issues in both PR :)

**Review by pparidans — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
