### PR TITLE
[IMP] *: remove "French spacing" 👺

### PR DESCRIPTION
**Pull request by oomsveta**
According to Wiktionary, *French spacing* is "the archaic practice (though still current in French) of inserting a space around colons, semicolons, question marks, and exclamation marks". This is not standard practice in English and most languages of the world.

The purpose of this commit is to start purging the code from this typo, as it may reflect poorly on the software for some people.

Enterprise: https://github.com/odoo/enterprise/pull/37853

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]
LGTM
@mart-e Do you have any objection with these changes?

**Comment by mart-e** [comment]
Our English dictator is @fhe-odoo ! But sure, fine with me.

**Comment by tde-banana-odoo** [comment]
Could you limit this PR to real sentences user will face, not tests or stuff like that ? Notably in crm / mail I regularly add new tests in stable, I don't want my fwd-ports to crash because of a test sentence ^^ . In tests this is mainly noisy to change strings, real users won't face them.

**Comment by oomsveta** [comment]
> Could you limit this PR to real sentences user will face, not tests or stuff like that ? Notably in crm / mail I regularly add new tests in stable, I don't want my fwd-ports to crash because of a test sentence ^^ . In tests this is mainly noisy to change strings, real users won't face them.

Hello Thibault, as a developer and not an end user, I would definitely prefer to have clean English throughout the entire codebase, but ultimately I don't really have a strong opinion on the test files. I feel like the few forward ports should not pose any particular difficulty, but I may be underestimating the problem. I'll leave it to you to decide whether or not I should revert the changes to the test files 👍️

**Review by alexkuhn — APPROVED** [review]

**Review by seb-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
