### PR TITLE
[IMP] point_of_sale: link to pos general settings

### PR DESCRIPTION
**Pull request by caburj**
For additional convenience, this adds a quick link to the pos'
general settings from the pos.config edit modal.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dama-odoo** [comment]
Hi @caburj, only one thing; non-admin users shouldn't see the link, since they don't have access to the general settings.  Other than that, all good.

**Comment by caburj** [comment]
@pimodoo This contains a simple improvement and the fix to the misaligned "New Shop" button.

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Comment by pimodoo** [comment]
@robodoo retry

**Pull request closed without merging**
