### PR TITLE
[IMP] odoo: avoid useless error in logs

### PR DESCRIPTION
**Pull request by bouvyd**
Avoid logging an error in the logs for an operation that is not an
error: if the extension already exists, this is a success.

### CODE REVIEW

**Comment by dbo-odoo** [comment]
@mart-e 
since you r+'d #46534, can i have your opinion on this?
I'd like to avoid
 ```
2020-04-03 07:03:08,220 27907 ERROR ? odoo.sql_db: bad query: CREATE EXTENSION unaccent
ERROR: ERREUR:  l'extension « unaccent » existe déjà
```

**Comment by mart-e** [comment]
Sure but I am curious, how did you get this error? Because the unaccent is activated on the template?
Shouldn't it target saas-13.3 btw ?

**Comment by dbo-odoo** [comment]
Yes, i've enabled it on my template indeed.

It's not critical so I targeted master by default, but sure I can retarget.

**Comment by dbo-odoo** [comment]
superseeded by #48933

**Pull request closed without merging**
