### PR TITLE
[FIX] purchase_stock : issue with pivot pivot_view

### PR DESCRIPTION
**Pull request by guva-odoo**
Step to reproduce

- Purchase >> reporting
- Filters > choose a Vendor
- Filters > Effective Date Last Year
- Toggle Studio
- Add Pivot View and close
- Measures > On-Time Delivery Rate

Got a traceback, the read_group method didn't take into account
the fields :sum relative to the pivot view.

opw-2600230

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
It would be great if it could work with all aggregation functions

**Comment by guva-odoo** [comment]
> It would be great if it could work with all aggregation functions

Not 100% sure about what I did here, it seems fine to you?

**Comment by amoyaux** [comment]
Nope, you need to return the result with the correct aggregate function

**Comment by guva-odoo** [comment]
> Nope, you need to return the result with the correct aggregate function

Done

**Comment by guva-odoo** [comment]
> Nope, you need to return the result with the correct aggregate function

Done, thanks

**Review by Whenrow — APPROVED** [review]

**Comment by kitan191** [comment]
@robodoo r+

**Pull request closed without merging**
