### PR TITLE
[FIX] web_editor: Properly compute scss files

### PR DESCRIPTION
**Pull request by kig-odoo**
Properly compute scss files

### CODE REVIEW

**Comment by kig-odoo** [comment]
Hello @qsm-odoo ,

Can you look at this PR?

Thanks

**Comment by qsm-odoo** [comment]
Seems good but you should target the first saas for a bug fix I suppose (saas-11.4 I think ?)

**Comment by kig-odoo** [comment]
Oops I just forgot about freeze
saas-11.4 FIX is here : #25233

**Comment by kig-odoo** [comment]
Done at #25233

**Pull request closed without merging**
