### PR TITLE
[FIX] sale_timesheet: fix multiple issues in project profitability

### PR DESCRIPTION
**Pull request by tlibioulle**
This commit fixes issues with downpayment and credit notes in project
profitability report.

Steps to reproduce opw-2596224:
- Go to sale
- Make a RFQ for a service product with service_policy set at
delivered_timesheet (Timesheets on tasks), set quantity as 10
- Confirm order and create two invoices for 15%, confirm the two
invoices
- Create a credit note for one of the invoice and confirm it
- Go back to the Sale Order and click on Project Overview
=> Inconsistencies (Downpayment reported twice)
- Add an expense
=> Inconsistencies in expense amount untaxed invoiced

This issue is fixed by :
- Excluding downpayments which are linked to a reversed invoice line
- Use expense amount to invoice and expense amount invoiced separetely
in the project overview.
- Do not report not invoiced SOLs in the expense amount invoiced.
- Exclude negative amounts in analytic account which are linked to
credit notes.

opw-2596224

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by xavierbol — COMMENTED** [review]
Nice work ! 🙂

**Comment by tlibioulle** [comment]
@fw-bot ignore

**Review by IT-Ideas — COMMENTED** [review]
I know this represents quite a headache!
Thanks for this fix and the associated tests 🙏🏼

**Comment by tlibioulle** [comment]
Hi @guva-odoo ,

You can close your PR #78076 and tell on opw-2596224 that it should be fixed early next week.

Thanks for your patience !

**Pull request closed without merging**
