### PR TITLE
[FIX] Mail: Fixed the issue of default filter not applying after reloadi...

### PR DESCRIPTION
**Pull request by nja-odoo**
...ng the page
- Task: https://www.odoo.com/web#id=11346&view_type=form&model=project.task&menu_id=3942&action=327
- Pad: https://pad.odoo.com/p/r.y10nhtKmwQwMV5Pd

### CODE REVIEW

**Comment by rim-odoo** [comment]
@nja-odoo Is this PR still valid?

**Comment by rim-odoo** [comment]
Also see #4664

**Comment by ged-odoo** [comment]
see my comment above.  This PR should not be merged in its actual state.  As soon as @nja-odoo update it to take my comments into account, i'll review and merge it.  If the task is cancelled, then this PR should be closed.

**Comment by rim-odoo** [comment]
Seems it has already been merged in saas-6 at 2c1e81a4a03d55e47edb1f77485188d4969cefe5

**Pull request closed without merging**
