### PR TITLE
[IMP] core: module loading consistency

### PR DESCRIPTION
**Pull request by ypapouin**
**Description of the issue/feature this PR addresses:**

_Note that the existing `sequence` manifest attribute/`ir.module`'s field is only used for the kanban view to display applications in a specific order and is not relevent to loading order_

Module list is fetched from database in `odoo/odoo/modules/loading.py::load_marked_modules` with this query
```
cr.execute("SELECT name from ir_module_module WHERE state IN %s" ,(tuple(states),))
```
So, the module loading order actually depends on 4 params:

1. PostgreSQL database collation
2. Module name
3. Datetime of the creation of the `ir_module_module` row (since no ORDER BY is defined in the query)
4. The dependencies

That's a terrible loading implementation as the parameter 3 is based on an internal PostgreSQL data, it also depends on the list order of your `addons_path` and also depends on when `odoo/addons/base/models/ir_module.py::update_list` is called.

**Current behavior before PR:**

Example for this last assertion:

- On the development database:
  - You add the module `account_extra`, that depends on account and override method `update_something`, in your main addons path
  - `update_list()`
  - Two weeks later, you add the module `account_best` , that also depends on account and also override the method `update_something`, in your main addons path
  - `update_list()`
  - Module `account_extra` will be loaded before `account_best`

- Three weeks later, on the production database:
  - You add modules `account_extra` and `account_best` in your main addons path
  - `update_list()`
  - Module `account_best` will be loaded before `account_extra`

And there I'm not talking about other cases like:
- Multiple `addons_path`
- Manual module deletion from odoo module list followed by a module list update
- Manual module installation from UI whereas the server is already started with loaded modules

**Desired behavior after PR is merged:**

Operate a sort on module list based on their name when loading to ensure consistency regardless of:
- database collation
- addons_path order
- ir_module_module filling order

On top of this, a new manifest attribute `loading_priority` is added to enforce loading order:
- default value is 0
- priority > 0 means loaded before
- priority < 0 means loaded after

A second attribute `soft_depends` is also added to control loading order, but contrary to `depends`, it does not require that a module in this list be installed or even exists.

For references:

- https://odoo-community.org/groups/contributors-15/contributors-244927
- https://www.odoo.com/fr_FR/forum/aide-1/modules-order-of-dependencies-159563
- https://www.odoo.com/fr_FR/forum/aide-1/how-openerp-decides-loading-order-of-modules-36392
- https://www.odoo.com/fr_FR/forum/aide-1/how-to-define-priority-of-independent-modules-to-ensure-one-is-loaded-before-the-second-one-21105

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ypapouin** [comment]
Hi @rco-odoo , could you take a look on this PR as it would be a good improvement on the core framework ?

**Comment by ypapouin** [comment]
This new commit iteration removes the `depth` logic in module graph management. Instead, a module can exists multiple times as a child for all its dependencies.

I've also added a simple test to « print » the loading order from the Graph state, a sample output can be previewed below:

```
================================================
Case 1:
- no priority


Node hierarchy:
------------------------
root
`-> node_a
   `-> node_a1
   `-> node_a2
      `-> node_c
         `-> node_c1
         `-> node_c2
         `-> node_c3
   `-> node_a3
`-> node_b
   `-> node_b1
   `-> node_b2
   `-> node_b3
      `-> node_d
         `-> node_d1
         `-> node_d2
         `-> node_d3

Final loading order is:
------------------------
Index  Priority   Name                                                         Dependencies
0                 root                                                         []
1                 node_a                                                       ['root']
2                 node_a1                                                      ['node_a']
3                 node_a2                                                      ['node_a']
4                 node_c                                                       ['node_a2']
5                 node_c1                                                      ['node_c']
6                 node_c2                                                      ['node_c']
7                 node_c3                                                      ['node_c']
8                 node_a3                                                      ['node_a']
9                 node_b                                                       ['root']
10                node_b1                                                      ['node_b']
11                node_b2                                                      ['node_b']
12                node_b3                                                      ['node_b']
13                node_d                                                       ['node_b3']
14                node_d1                                                      ['node_d']
15                node_d2                                                      ['node_d']
16                node_d3                                                      ['node_d']

================================================
Case 2:
- priority 10 set to Node C2


Node hierarchy:
------------------------
root (priority: 10)
`-> node_a (priority: 10)
   `-> node_a2 (priority: 10)
      `-> node_c (priority: 10)
         `-> node_c2 (priority: 10)
         `-> node_c1
         `-> node_c3
   `-> node_a1
   `-> node_a3
`-> node_b
   `-> node_b1
   `-> node_b2
   `-> node_b3
      `-> node_d
         `-> node_d1
         `-> node_d2
         `-> node_d3

Final loading order is:
------------------------
Index  Priority   Name                                                         Dependencies
0      10         root                                                         []
1      10         node_a                                                       ['root']
2      10         node_a2                                                      ['node_a']
3      10         node_c                                                       ['node_a2']
4      10         node_c2                                                      ['node_c']
5                 node_c1                                                      ['node_c']
6                 node_c3                                                      ['node_c']
7                 node_a1                                                      ['node_a']
8                 node_a3                                                      ['node_a']
9                 node_b                                                       ['root']
10                node_b1                                                      ['node_b']
11                node_b2                                                      ['node_b']
12                node_b3                                                      ['node_b']
13                node_d                                                       ['node_b3']
14                node_d1                                                      ['node_d']
15                node_d2                                                      ['node_d']
16                node_d3                                                      ['node_d']

================================================
Case 3:
- priority 10 set to Node C2
- priority 11 set to Node D2


Node hierarchy:
------------------------
root (priority: 21)
`-> node_a (priority: 10)
   `-> node_a2 (priority: 10)
      `-> node_c (priority: 10)
         `-> node_c2 (priority: 10)
         `-> node_c1
         `-> node_c3
   `-> node_a1
   `-> node_a3
`-> node_b (priority: 11)
   `-> node_b1
   `-> node_b2
   `-> node_b3 (priority: 11)
      `-> node_d (priority: 11)
         `-> node_d2 (priority: 11)
         `-> node_d1
         `-> node_d3

Final loading order is:
------------------------
Index  Priority   Name                                                         Dependencies
0      21         root                                                         []
1      10         node_a                                                       ['root']
2      10         node_a2                                                      ['node_a']
3      10         node_c                                                       ['node_a2']
4      10         node_c2                                                      ['node_c']
5                 node_c1                                                      ['node_c']
6                 node_c3                                                      ['node_c']
7                 node_a1                                                      ['node_a']
8                 node_a3                                                      ['node_a']
9      11         node_b                                                       ['root']
10                node_b1                                                      ['node_b']
11                node_b2                                                      ['node_b']
12     11         node_b3                                                      ['node_b']
13     11         node_d                                                       ['node_b3']
14     11         node_d2                                                      ['node_d']
15                node_d1                                                      ['node_d']
16                node_d3                                                      ['node_d']

================================================
Case 4:
- priority 10 set to Node C2
- priority 8  set to Node D2
- priority 4  set to Node D


Node hierarchy:
------------------------
root (priority: 22)
`-> node_a (priority: 10)
   `-> node_a2 (priority: 10)
      `-> node_c (priority: 10)
         `-> node_c2 (priority: 10)
         `-> node_c1
         `-> node_c3
   `-> node_a1
   `-> node_a3
`-> node_b (priority: 12)
   `-> node_b1
   `-> node_b2
   `-> node_b3 (priority: 12)
      `-> node_d (priority: 12)
         `-> node_d2 (priority: 8)
         `-> node_d1
         `-> node_d3

Final loading order is:
------------------------
Index  Priority   Name                                                         Dependencies
0      22         root                                                         []
1      10         node_a                                                       ['root']
2      10         node_a2                                                      ['node_a']
3      10         node_c                                                       ['node_a2']
4      10         node_c2                                                      ['node_c']
5                 node_c1                                                      ['node_c']
6                 node_c3                                                      ['node_c']
7                 node_a1                                                      ['node_a']
8                 node_a3                                                      ['node_a']
9      12         node_b                                                       ['root']
10                node_b1                                                      ['node_b']
11                node_b2                                                      ['node_b']
12     12         node_b3                                                      ['node_b']
13     12         node_d                                                       ['node_b3']
14     8          node_d2                                                      ['node_d']
15                node_d1                                                      ['node_d']
16                node_d3                                                      ['node_d']

================================================
Case 5:
- priority 10 set to product


Node hierarchy:
------------------------
base (priority: 60)
`-> product (priority: 10)
   `-> stock
`-> mail (priority: 10)
   `-> product (priority: 10)
      `-> stock
   `-> auth_signup
      `-> portal
         `-> auth_totp_portal
         `-> digest
            `-> stock
   `-> digest
      `-> stock
   `-> portal
      `-> auth_totp_portal
      `-> digest
         `-> stock
`-> uom (priority: 10)
   `-> product (priority: 10)
      `-> stock
`-> web (priority: 30)
   `-> auth_signup
      `-> portal
         `-> auth_totp_portal
         `-> digest
            `-> stock
   `-> auth_totp
      `-> auth_totp_portal
   `-> barcodes
      `-> stock
   `-> base_import
   `-> base_setup (priority: 10)
      `-> auth_signup
         `-> portal
            `-> auth_totp_portal
            `-> digest
               `-> stock
      `-> mail (priority: 10)
         `-> product (priority: 10)
            `-> stock
         `-> auth_signup
            `-> portal
               `-> auth_totp_portal
               `-> digest
                  `-> stock
         `-> digest
            `-> stock
         `-> portal
            `-> auth_totp_portal
            `-> digest
               `-> stock
      `-> web_unsplash
   `-> bus (priority: 10)
      `-> mail (priority: 10)
         `-> product (priority: 10)
            `-> stock
         `-> auth_signup
            `-> portal
               `-> auth_totp_portal
               `-> digest
                  `-> stock
         `-> digest
            `-> stock
         `-> portal
            `-> auth_totp_portal
            `-> digest
               `-> stock
   `-> http_routing
      `-> portal
         `-> auth_totp_portal
         `-> digest
            `-> stock
   `-> portal
      `-> auth_totp_portal
      `-> digest
         `-> stock
   `-> resource
      `-> digest
         `-> stock
   `-> web_editor
      `-> portal
         `-> auth_totp_portal
         `-> digest
            `-> stock
      `-> web_unsplash
   `-> web_kanban_gauge
   `-> web_tour (priority: 10)
      `-> mail (priority: 10)
         `-> product (priority: 10)
            `-> stock
         `-> auth_signup
            `-> portal
               `-> auth_totp_portal
               `-> digest
                  `-> stock
         `-> digest
            `-> stock
         `-> portal
            `-> auth_totp_portal
            `-> digest
               `-> stock

Final loading order is:
------------------------
Index  Priority   Name                                                         Dependencies
0      60         base                                                         []
1      10         uom                                                          ['base']
2      30         web                                                          ['base']
3                 auth_totp                                                    ['web']
4                 barcodes                                                     ['web']
5                 base_import                                                  ['web']
6      10         base_setup                                                   ['web']
7      10         bus                                                          ['web']
8                 http_routing                                                 ['web']
9                 resource                                                     ['web']
10                web_editor                                                   ['web']
11                web_unsplash                                                 ['base_setup', 'web_editor']
12                web_kanban_gauge                                             ['web']
13     10         web_tour                                                     ['web']
14     10         mail                                                         ['base', 'base_setup', 'bus', 'web_tour']
15     10         product                                                      ['base', 'mail', 'uom']
16                auth_signup                                                  ['base_setup', 'mail', 'web']
17                portal                                                       ['web', 'web_editor', 'http_routing', 'mail', 'auth_signup']
18                auth_totp_portal                                             ['portal', 'auth_totp']
19                digest                                                       ['mail', 'portal', 'resource']
20                stock                                                        ['product', 'barcodes', 'digest']
```

**Comment by Xavier-Do** [comment]
> Module list is fetched from database in odoo/odoo/modules/loading.py::load_marked_modules with this query
> cr.execute("SELECT name from ir_module_module WHERE state IN %s" ,(tuple(states),))
> So, the module loading order actually depends on 4 params:
> PostgreSQL database collation
> Module name
> Datetime of the creation of the ir_module_module row (since no ORDER BY is defined in the query)
> The dependencies
> That's a terrible loading implementation as the parameter 3 is based on an internal PostgreSQL data, it also depends on the list order of your addons_path and also depends on when odoo/addons/base/models/ir_module.py::update_list is called.

I was expecting that only the dependencies and module name has an impact, it shouldn't be the case of database collation or record creation order. Module name should be enough since module are supposed to have unique names.

If account_extra and account_best have the same dependencies, I would expect account_best to be loaded first in all cases.

> Multiple addons_path
> Manual module deletion from odoo module list followed by a module list update
> Manual module installation from UI whereas the server is already started with loaded modules

This shouldn't have an impact if module are sorted by name
 
> Desired behavior after PR is merged:
> Operate a sort on module list based on their name when loading to ensure consistency regardless of:
> database collation
> addons_path order
> ir_module_module filling order

Looks simple and makes sense to me, I was convinced it was the case. 
- the sql query is not sorted but result is only used to `add_modules`
- add_modules does not really take care of module names but __iter__ kinda does
- loading is based on iteration on graph
I'm not 100% that the graph iter is 100% defined by modules names order and depends, it would be interesting to check, and it would maybe be a good idea to add an order to the `cr.execute` to make it more obvious. 

> On top of this, a new manifest attribute loading_priority is added to enforce loading order:
> default value is 0
> priority > 0 means loaded before
> priority < 0 means loaded after
> A second attribute soft_depends is also added to control loading order, but contrary to depends, it does not require that a > module in this list be installed or even exists.

I'm not fan of this idea. It is a good idea to have a fully defined loading order but IMHO, depends should be enough. 
Talking about override, if you override update_something, update_something is called first the code should be resilient to that. I would be curious to have a good counter example if it is not the case.

**Comment by voronind** [comment]
depends is not enough

**Comment by Xavier-Do** [comment]
> depends is not enough

Ok

**Comment by rco-odoo** [comment]
Your explanation on the loading order of modules is not correct. Let me clarify it.

First, let's consider a database with a given set of installed modules, and nothing to install or uninstall.  The loading order of modules is determined by the class `Graph`, and is determined by a module's _depth_ and _name_.  The depth of a module is the length of the longest dependency path from that module to `base`.  If you lay out modules graphically, you will start with `base` on top (depth 0), then put all modules that only depend on `base` (depth 1), then all modules that depend on modules of depth 0 or 1, and so on.  In that layout, the depth is the row number of the module, starting at 0.  The loading order of installed modules is given by the key _(depth, name)_, where _depth_ ensures that a module's dependencies are loaded before that module, and _name_ makes it deterministic.

Anyway, the loading order does not depend on what the query `SELECT name from ir_module_module WHERE ...` returns, because all those names are eventually ordered according to the `Graph`.  The loading order only depends on the module names and dependencies.  In any case, the loading order is totally independent from the following factors:
- PostgreSQL database collation,
- datetime of the creation of the ir_module_module row,
- ir_module_module filling order,
- addons_path order.

Second, you confuse the _loading_ order with the _installation_ order.  When you install a module on a database, the registry **first loads all the modules that are already installed**, and then loads the modules to install.  Once the installation is done, the next time the registry will be loaded, the order will be the one given by the `Graph` for all installed modules.  What _may be_ problematic is that the registry that performed the installation (and loaded `account_best` after `account_extra`) is not reloaded, and keeps its method overrides in an order which is different from a registry that would be loaded after the installation.  However, if `account_best` and `account_extra` do not depend on each other, their overrides should not depend on each other either...  Our own production database is quite large and has many modules, and we never experienced such problems with the existing system for ordering modules.

We don't want to change the criteria that determine the loading order, because it will break existing code.  I have the feeling that you are trying to fix bad business code by tweaking the underlying framework to _your_ needs.

**Pull request closed without merging**
