### PR TITLE
16.0 fix keyboard navigation background jcb

### PR DESCRIPTION
**Pull request by caburj**
As per request in the wowl pad

> * [NGR] restore the v15 design of editable listviews https://www.awesomescreenshot.com/image/33055833?key=3d307067d11d22f974a5a18cbf5a6fd5
>   * i.e. remove green outline, and fix bug that turns the rest of the row grey when navigating with the keyboard (see bug here > https://www.awesomescreenshot.com/image/33055887?key=333099c1bce38f60a375613a9c1083c0 )

**Before:**

Screenshot 2022-10-05 at 14 14 57

**After:**

Screenshot 2022-10-05 at 14 12 29

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by stefanorigano — CHANGES_REQUESTED** [review]
Hello @caburj ,

> [NGR] restore the v15 design of editable listviews https://www.awesomescreenshot.com/image/33055833?key=3d307067d11d22f974a5a18cbf5a6fd5
i.e. remove green outline

This is the expected behaviour as part of v16 redesign. 

>  and fix bug that turns the rest of the row grey when navigating with the keyboard (see bug here > https://www.awesomescreenshot.com/image/33055887?key=333099c1bce38f60a375613a9c1083c0 )

It's an intentional recent fix https://github.com/odoo-dev/odoo/commit/277fbfadd03133187b6d015f996e5197db5da5b1, I don't agree on the chosen bg-color, but the behaviour makes sense to me.

I'd suggest to re-check with NGR

**Comment by rfr-odoo** [comment]
> > and fix bug that turns the rest of the row grey when navigating with the keyboard (see bug here > https://www.awesomescreenshot.com/image/33055887?key=333099c1bce38f60a375613a9c1083c0 )
> 
> It's an intentional recent fix [odoo-dev@277fbfa](https://github.com/odoo-dev/odoo/commit/277fbfadd03133187b6d015f996e5197db5da5b1), I don't agree on the chosen bg-color, but the behaviour makes sense to me.
> 

I was asked to restore the keyboard navigation. I don't have check any spec for the color, so i have used the old one.

> I'd suggest to re-check with NGR

Yep, it seems the better solution.

**Comment by bouvyd** [comment]
hi all :)

i'm afraid we're past the time for bikeshedding => both ngr and myself are on a crusade commandeered by our commander-in-chief, and what we need is to be quick; in this case we already know that the summit of the food chain pyramid wants it that way

@stefanorigano i understand that you're annoyed (I really do) - it's one step forward, two steps back - i know, i kind of agree, and clearly we have to go to the bottom of these design back and forth right after OXP, because it's clearly annoying for everyone (you when you try to push changes and we come for a revert, us when things are changing under our feet without a clear chain of decision); but in the mean time i don't want to have a summit meeting for  a highlight color and fp was super clear

we move forward with @caburj 's code

**Comment by stefanorigano** [comment]
@bouvyd , I'm not interested on bikeshedding neither, I've been asked to review and I did that with the information I had.
The specs changed? Ok 

> you when you try to push changes and we come for a revert....

Well, I don't "_try to push changes_" by myself 😂, we refer to a mockup approved since December. Don't tell me that you guys were not aware...

> ...us when things are changing under our feet without a clear chain of decision

Weird because we don't have "secret projects", actually we try to get feedbacks from your team but we get mostly emoji 😂.
Honestly this is what annoy me a bit, but it's ok,  let's fix all the bugs, please go ahead ;)

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by bouvyd** [comment]
@stefanorigano I think this a clear example of chain failure in communication + in timing; stuff was approved a long time ago, POs have been hired or changed scopes and we know that management sometimes say yes and forgets about it (esp. after a few months :p).

What's becoming clear is that we need more tight communication between design and POs (but i was told pretty specifically "mobile and design are working to clean the scss, there's nothing to test for that tasks", since it was not supposed to impact design... and the chain of decision has been more or less lost to (oral?) history)

As discussed in other channels: let's meet right after OXP and try to understand the failure in the process and take (pbly very simple) steps to avoid/reduce situations like these - looking forward to it :)

**Pull request closed without merging**
