### PR TITLE
[CLA] signature for Zahra Badzohreh

### PR DESCRIPTION
**Pull request by ZahraBadzohreh**
signature for Zahra Badzohreh

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `108659318+ZahraBadzohreh@users.noreply.github.com`
- you are signing _for_ the address `z...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by ZahraBadzohreh** [comment]
> 

Hello,

Thank you for review, I changed my email address in [configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/).

**Review by ZahraBadzohreh — COMMENTED** [review]
Change email in configuration

**Comment by mart-e** [comment]
Thanks but the changes need to be in this PR. You can see the commit used at
https://github.com/odoo/odoo/pull/113531.patch
You need to amend your commit and push force in command line. Not sure how to do it from the github interface though.

**Comment by ZahraBadzohreh** [comment]
Sorry, because I can not directly push to odoo, creating a fork, and just work on it. Now I can see my email correctly in the PR.

**Pull request closed without merging**
