### PR TITLE
[FIX] point_of_sale : text are not translated

### PR DESCRIPTION
**Pull request by fmdl**
Before this commit those strings are not translated.

@pimodoo @rhe-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@caburj

**Comment by caburj** [comment]
Hi @mart-e. I agree with this change. However, I'm not quite sure if the change in the `.pot` file is necessary. Can you take over on the review?

**Comment by mart-e** [comment]
Thanks for the review. The changes are necessary but were not correct. I have regenerated the .pot file, it should be good now.
@fmdl thanks for the fix but please don't create manual entries in pot files, use the "Export translation" wizard to get the file.

@robodoo r+

**Comment by fmdl** [comment]
@mart-e I will do that next time.

**Pull request closed without merging**
