### PR TITLE
[FIX] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by rrahir**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/52753da68 [REL] 17.1.29 Task: 0
https://github.com/odoo/o-spreadsheet/commit/85deedddc [FIX] github: typo in PR template
https://github.com/odoo/o-spreadsheet/commit/5fc78cc4d [FIX] header_size: JS sparse array problem Task: 4074438

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by rrahir** [comment]
robodoo fw=no

**Review by LucasLefevre — COMMENTED** [review]
robodoo r+

**Review by LucasLefevre — COMMENTED** [review]
robodoo r+

**Comment by LucasLefevre** [comment]
robodoo retry

**Pull request closed without merging**
