### PR TITLE
[REV] web_editor: handle grid columns with video only

### PR DESCRIPTION
**Pull request by robinlej**
This reverts commit 2ce96dce7894231b3bfa7203887ad6954820114a.
The fix was wrong and introduced other issues.

### CODE REVIEW

**Comment by bso-odoo** [comment]
@qsm-odoo LGTM

**Comment by robinlej** [comment]
NB: only needed in 16.0 and 17.0 (I'll revert the right commit)

**Comment by qsm-odoo** [comment]
@robodoo delegate=bso-odoo,sobo-odoo 
@bso-odoo @sobo-odoo

**Review by sobo-odoo — APPROVED** [review]
@robodoo r+
@fw-bot up to 17.0

**Pull request closed without merging**
