### PR TITLE
[REV] lunch: Revert changes introduced in f727b8f0b57aad49f2ea8c54600ab73bbd02570f

### PR DESCRIPTION
**Pull request by tivisse**
YOLO

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
image

**Comment by tivisse** [comment]
@robodoo merge

**Comment by tivisse** [comment]
@robodoo retry r+

**Comment by tivisse** [comment]
@robodoo r+

**Pull request merged**
