### PR TITLE
 [IMP] models: new records return default values

### PR DESCRIPTION
**Pull request by rco-odoo**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Really? That's awesome! Can you point me the commit where that happened?

**Comment by rco-odoo** [comment]
@pedrobaeza the first commit implements the feature. The second one fixes the creation of users with given groups, which uses new records.

**Comment by rco-odoo** [comment]
@robodoo rebase-ff r+

**Comment by pedrobaeza** [comment]
Ah, great. This was a flaw in `new` operator in previous versions. I tweeted about that in the past:

https://twitter.com/PedroMBaeza/status/1067086018879397890

**Comment by rco-odoo** [comment]
@robodoo r-

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
