### PR TITLE
l10n_xx: use country_code field

### PR DESCRIPTION
**Pull request by rgo-odoo**
Task: <a href="https://www.odoo.com/web#action=333&active_id=1691&cids=2&id=2228210&menu_id=4720&model=project.task&view_type=form">2228210</a>

### CODE REVIEW

**Comment by jco-odoo** [comment]
@rgo-odoo Why is the second commit necessary?  Also in l10n_cl l10n_latam_country_code is used.  You are certainly not having them all.  We can do faster, but at least install l10n_ar and l10n_cl yourself.

**Comment by rgo-odoo** [comment]
@jco-odoo `account.journal` object is having `l10n_latam_country_code` field as well, so I think you mistook it as `account.move`'s. Can you recheck ?

**Comment by rgo-odoo** [comment]
> Why is the second commit necessary?

I thought it is better to keep country_code in main view so that we don't have to define it when we use it in attrs from various l10n modules.

**Comment by jco-odoo** [comment]
@rgo-odoo Has not that already been done somewhere?

**Comment by rgo-odoo** [comment]
nope, the <a href="https://github.com/odoo/odoo/commit/7edb5c111d0e3722831b02fd43670c8305eadfd9">commit<a/> that introduced the field did not put it in the view and we still don't have it in <a href="https://github.com/odoo/odoo/blob/master/addons/account/views/account_move_views.xml">account_move_views.xml</a>

**Comment by jco-odoo** [comment]
@rgo-odoo I will indeed have mistaken with that one of the journal.    And for the view, you can remove the one in l10n_cn then.  (<field name="country_code"    I thought the Indian localization had a field too.  (but as proven before, my memories can be mistaken)

**Comment by rgo-odoo** [comment]
@jco-odoo your memories hasn't mistaken this time regarding Indian localization, but it's there for `res.partner` object though, see https://github.com/odoo/odoo/blob/master/addons/l10n_in/models/res_partner.py#L12

**Comment by jco-odoo** [comment]
@rgo-odoo Thanks!

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
