### PR TITLE
[FIX] l10n_do: Change CoA to XML for noupdate

### PR DESCRIPTION
**Pull request by gustavovalverde**
**Description of the issue/feature this PR addresses:**
Odoo update will try to remove/change existing accounts (I also can't understand why, as accounts were not removed on the CoA update)

**Current behavior before PR:**
CRITICAL on update, by trying to unlink accounts already assigned to partners.

**Desired behavior after PR is merged:**
The noupdate feature should keep the actual installed CoA untouched.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gustavovalverde** [comment]
@tivisse, please check this out as this is fixing commit https://github.com/odoo/odoo/commit/7bda65e90eaa40386f32716955f18c178ab727b1

@qdp-odoo If you could please check this out, this change is to keep stability, but I'm not sure if just with the *noupdate* will be enough.

**Comment by mart-e** [comment]
Hello,

I am not sure to understand what you are trying to do.
The `noupdate` flag will not modify exiting records during an upgrade. It will have no effect to remove records.

Your code modifies `account.account.template` records which are only used for the creation of `account.account`. So it should have no impact on the current accounts assigned to partners.

**Comment by gustavovalverde** [comment]
Hi @mart-e, today we had another incident as the CSV is trying to overwrite a modified CoA. And if when it does it it removes all the previously modified accounts and the ones that were added. I'm made this PR so clients that have made modifications to their CoA don't have problem updating.

**Comment by gustavovalverde** [comment]
Oh well, it's happening anyways:
It's unlinking all previous records and replacing with the new ones

```
2017-07-04 03:17:47,577 564 INFO client odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [25024]
2017-07-04 03:17:47,577 564 INFO client odoo.models.unlink: User #1 deleted account.account records with IDs: [675]
2017-07-04 03:17:47,577 564 INFO client odoo.addons.base.ir.ir_model: Deleting 674@account.account (l10n_do.1_do_niif_51020101)
2017-07-04 03:17:47,588 564 INFO client odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [25023]
2017-07-04 03:17:47,588 564 INFO client odoo.models.unlink: User #1 deleted account.account records with IDs: [674]
2017-07-04 03:17:47,589 564 INFO client odoo.addons.base.ir.ir_model: Deleting 673@account.account (l10n_do.1_do_niif_42040400)
2017-07-04 03:17:47,599 564 INFO client odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [25022]
2017-07-04 03:17:47,600 564 INFO client odoo.models.unlink: User #1 deleted account.account records with IDs: [673]
2017-07-04 03:17:47,600 564 INFO client odoo.addons.base.ir.ir_model: Deleting 672@account.account (l10n_do.1_do_niif_21030405)
2017-07-04 03:17:47,604 564 INFO client odoo.sql_db: bad query: DELETE FROM account_account WHERE id IN (672)
2017-07-04 03:17:47,605 564 ERROR client odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 371, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/ir/ir_model.py", line 1384, in _process_end
    record.unlink()
  File "/odoo/odoo-server/src/odoo/addons/account/models/account.py", line 199, in unlink
    return super(AccountAccount, self).unlink()
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3409, in unlink
    cr.execute(query, (sub_ids,))
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "account_account" violates foreign key constraint "account_tax_account_id_fkey" on table "account_tax"
DETAIL:  Key (id)=(672) is still referenced from table "account_tax".
```

**Pull request closed without merging**
