### PR TITLE
[FIX] handle transitive field dependencies for invalidation/recomputation

### PR DESCRIPTION
**Pull request by rco-odoo**
Consider a computed field C that depends on a computed field B, which itself depends on field A. Before this fix, whenever A is modified, only B is invalidated/recomputed, and C may stay in cache, possibly with an inconsistent value.

The patch reimplements the setting of field triggers, such that the triggers cover the transitive closure of field dependencies. This adds around 40% more triggers on fields. The patch also validates the dependencies of stored computed fields, which must be searchable (in order to determine the records to recompute.)

### CODE REVIEW

**Comment by rco-odoo** [comment]
@xmo-odoo @KangOl @odony review is welcome.

**Comment by dreispt** [comment]
Does this deserve a backport?

**Comment by sbidoul** [comment]
:clap: I would love to see this backported to v9.

**Comment by odony** [comment]
- verify/log the number of recomputation of the dependencies of each field (i.e. the recursion overhead)
- verify/log the distribution of lengths of the dependency trees
- based on previous results, possibly compute the dependencies globally at once to reduce the registry load cost (currently 10%?) ?
- as the problematic field definitions addressed by 00c31f3 seem uncommon, consider switching to raising exceptions (adding test would be nice, but testing registry loading seems impractical)
- verify the memory overhead of the 40% extra triggers (expected negligible)

**Comment by rco-odoo** [comment]
@odony here are some results:
- recursion overhead looks reasonable: on average, 2.57 calls to `_resolve_deps` per field
- recursion depth follows more or less an inverse exponential distribution, the maximum depth I observed is 5 (initial call having depth 0)
- I gave a try to a global graph algorithm to compute the transitive closure of the dependencies, and I could not get better performance...

**Comment by odony** [comment]
@rco-odoo thanks for those results! Do we have any measure of the memory overhead, and some real-life numbers on the registry load time with/without the patch?

@antonylesuisse is particularly keen on having zero negative impact on cold clicks and registry load times, even if we identify important bugs that would be solved by this (which we did not?)

I understand his concerns, we've been working very hard since v8 to speed up the framework and registry load times, and it would be a shame to lose ground there.

If we find no way to speed this up, he suggests trying to find an intermediate solution, such as only activating the recursion in "--dev" mode, for the purpose of turning on the warning/errors, or something similar.

**Comment by rco-odoo** [comment]
@odony timing `RegistryManager.new()` on my computer:
- master: 1.109s
- this: 1.199s (+8%)

**Comment by rco-odoo** [comment]
@odony I measured the memory overhead on a database with 52 modules, 311 models and 5150 fields.
- master: 3365 triggers
- this: 4991 triggers
- difference: 1626 triggers (+48%), 126344 bytes

The memory overhead is around 78 bytes per field trigger. Note that a trigger is a pair `(field, path)`, and the pair itself takes 72 bytes in memory.

**Comment by antonylesuisse** [comment]
Can we do the test with all modules installed ? I m'not conviced 10% speed decrease and memory usage is worth a warning (as those compute are not used in our addons).

**Comment by rco-odoo** [comment]
We block this patch, and see whether some other performance improvements can compensate for its performance cost.

**Comment by Yenthe666** [comment]
@rco-odoo any update on this one?

**Comment by rco-odoo** [comment]
Partially taken over by #22018, which has a negligible performance overhead.

**Pull request closed without merging**
