### PR TITLE
[l10n_sa] 14.0 sarelax jco: Improvements for the SA invoice

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
To be checked functionally still.

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo rebase-ff

**Comment by jco-odoo** [comment]
@FlorianGilbert

**Comment by FlorianGilbert** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
