### PR TITLE
[13.0] mrp: when consuming different component lots you cannot select existing lots.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
The company_id is filtering the lot_id, but when you add extra component lines the
company is not set, which makes the expected lots unavailable. this is fixed by adding
a context with the default company in mrp.product.produce.line's in the produce
wizard form view

Current behavior before PR:
missing-lots

Desired behavior after PR is merged:
Peek 2020-01-08 11-45

(NOTE: the company_id field is added in the view for clearer description of the issue in the above gifs)

cc @ForgeFlow

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Could you keep the old CLA? As there is multiple commits (85 last time I counted!) made by eficient, we have to keep the file. You can modify it to add a mention "up to ..." or something like this to mention it is no longer valid.

**Comment by Whenrow** [comment]
Hello, we fixed this issue in the master branch but not like this (see https://github.com/odoo/odoo/commit/644663eb4a356b06f4a135bfaf60bce98aa7ee63#diff-23a0970256e36352f87cbb4d0cd9eea8R327)

Could you please use this fix instead in your branch in order to keep same fix accross versions ? 
Thanks a lot

**Comment by LoisRForgeFlow** [comment]
@mart-e Eficent CLA is kept now.

@Whenrow That looks good too, are you planning to backport it? I can even do it myself here in this PR.

**Comment by Whenrow** [comment]
@LoisRForgeFlow I can do it myself for sure if you prefer. But as you already write the PR and commit it will be quicker :)

**Comment by mart-e** [comment]
Also, could you try to keep to keep the [git commit structure](https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure) ?
For the cla, to have a message like `[CLA] ForgeFlow signs Odoo CCLA` and for the mrp commit, `[FIX] mrp: ...`

Thanks

**Comment by LoisRForgeFlow** [comment]
Everything updated as per your suggestions. Thanks you for your quick responses here.

**Comment by mart-e** [comment]
@robodoo r+ rebase-ff
Thanks

**Pull request closed without merging**
