### PR TITLE
[CLA] Cédric Krier

### PR DESCRIPTION
**Pull request by cedk**

### CODE REVIEW

**Comment by odony** [comment]
Sorry for not processing your CLA signature yet, the reason the check doesn't pass is that your commit is done with `ced@b2...` while your CLA signature  contains `cedric.krier@b2...`
You can either rebase the commit with the correct github `user.email` or add the second email to your signature.
I've [updated the CLA page](https://github.com/odoo/odoo/commit/49be541) to make more explicit that the email should be the git committer email - this is a common mistake. Thanks.

**Comment by cedk** [comment]
But I don't want to be emailed with my user name email address but with my public address that's why I have two emails address on my GitHub profile one public (used for signing) and one for login.

**Comment by odony** [comment]
If your goal is to avoid broadcasting your login email, why don't you also set your `user.email` git config param to your public email? That would avoid leaking the login one in public github pages, such as [patch pages](https://github.com/odoo/odoo/pull/8460.patch). Github will still be able to match your commits, and external tools such as our CLA check will only see the public one.

**Comment by cedk** [comment]
There is a difference between the email I use to sign a contract and the pseudo-email I use for tools like git. Your tool makes wrong check, it should check that my Github account is the right one (making the pull request) and that my email signature is one of my public email address on the Github account (which have been verified). Otherwise, I could put a fake email in the commit and CLA signature and so you could never contact me.

**Comment by cedk** [comment]
See now I have the CLA signed and validated with a fake email address.

**Comment by odony** [comment]
Unfortunately we have no visibility/traceability on secondary GitHub emails, and we need a valid, offline, permanent record of CLA signatures that we can match against commit author emails, even if we leave GitHub tomorrow, or it goes down, or if you change your emails just after signing. That's why the CLA check only matches the list of emails in the CLA signatures that are in the repository itself - and accepting CLA signatures is done manually after double-checking.

If you add the second email to your CLA signature you'll establish a permanent record of signing the CLA with both emails, which seems ok with your intended use of email addresses.

PS: GitHub's email validation is kind of overkill/useless for our purpose, and would only raise the technical barrier for signing the CLA (not to mention that it's trivial to forge commit authorship [for validated github accounts too](https://github.com/odoo-dev/odoo/commit/4660b2409c5b142e1c58e3148c52b66740c52e56) in the absence of GPG-signed commits).
That's not a problem because the goal of the CLA is still reached - every external contribution matches an explicit CLA signature that defines the terms under which the contribution was done, even if the author becomes unreachable at some point.

**Comment by odony** [comment]
We could use the PR author for verification purposes, but again, it does not constitute a permanent, offline record for archiving purposes. The signature/commit ought to be self-contained.

**Comment by cedk** [comment]
So you just pointed with the forged commit that the all CLA process is flawed and unreliable as anyone will be able to submit a PR using a forged email of someone who has signed the CLA.
Also if you don't want to rely on Github why asking all those Github information in the signature process.
Anyway I will use the private email address that Github offers.

**Comment by odony** [comment]
Exactly, the CLA is not meant to authenticate commits but to link each contribution to a CLA signature. Masquerading as someone else to contribute is possible with or without CLA, and we don't care much about it because there is little incentive to do so. Contributions are reviewed in the same manner regardless of who submits them.
GitHub info is useful but not actually required. Some people sign a paper-based CLA for old contributions without providing github info.

Using the github private email is fine, thanks for the update!

**Pull request closed without merging**
