### PR TITLE
[FIX] payment_stripe: regression 98fe5054c2


### PR DESCRIPTION
**Pull request by nle-odoo**
opw-1939323

### CODE REVIEW

**Comment by nle-odoo** [comment]
Test after regression fix: https://www.youtube.com/watch?v=c-7uKp509dU

robodoo r+

**Comment by wtaferner** [comment]
@nle-odoo
https://github.com/odoo/odoo/pull/32025

Hmm, your fix is different, may I ask you to explain? My fix is working and already deployed and tested.

**Comment by wtaferner** [comment]
Got it, probably to be backwards compatible?
Anyway, can you please fix the test too in terms of testing a whole Stripe payment?

**Comment by nle-odoo** [comment]
Hi Wolfgang,

Thanks for the quick response, this PR and sorry for the issue.

> Hmm, your fix is different, may I ask you to explain? My fix is working and already deployed and tested.

The result is exactly the same.

In the original PR I renamed `handler` to `stripeHandler` because this is now a global variable (to the module closure)  so I was afraid that in a future change someone using a variable "handler" could have an issue => but the created issue has no comparison.

In my version we have a local variable `handler` so even if someone changed stripeHandler stripe would still have the correct variable. 

In any case this is just for non-existing future code so your PR was as correct.

Regards.

**Comment by nle-odoo** [comment]
> Anyway, can you please fix the test too in terms of testing a whole Stripe payment?

The current test we have are only python and are only run at most daily (because stripe would block us because of the number of request) with the number of runbot. But in this instance these test would not catch an issue.

For testing the whole scenario a customer do with e.g. a tour:

- it would also not be possible to do it on every runbot because we would get the same rate limitation issue

- in this instance a test on the whole scenario does not seem possible since Stripe adds its payment wizard in an iframe over Odoo. Thanks to browser security a tour in odoo code has no way to set a card number inside the iframe.

**Comment by wtaferner** [comment]
@nle-odoo
Alright, then there are only manual tests which can avoid such culprits in the future on your side and I am pretty sure you won't merge payment changes in the future without thoroughly testing in all the browsers a whole payment manually before, right?  :laughing: 
This should actually anyway always be the case for these sensible modules, as long there is no 100% test coverage and test framework for all perspectives.

**Pull request closed without merging**
