### PR TITLE
Signing CLA Ark74

### PR DESCRIPTION
**Pull request by Ark74**
Added ark74.md
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Ark74** [comment]
This file is UTF-8, could it be about the line break?
It is set to LF (Unix like).

**Comment by mart-e** [comment]
Rebase your branch with the current master and it should work.
Your branch is from 2016, greatly outdated.
Also #28102 is for 10.0 but you are signing the CLA for master. Don't you want to get it merged in 10.0 instead ?

**Comment by Ark74** [comment]
Oh, I see, so every branch should be signed.
I'm not why I thought that master was a pool of CLA signature.

I'll fix this thanks.

**Comment by Ark74** [comment]
Closing in favor of  #28126 
Thanks.

**Comment by mart-e** [comment]
> Oh, I see, so every branch should be signed

Not exactly. We forward port the patches from lowest version to the most recent. So if you merge your CLA in 10.0, it will be ported to 11, 12 and master branch.

**Pull request closed without merging**
