### PR TITLE
[IMP] mail: avoid log on invalid field name

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Gateway processing creates values from incoming emails. However we have to pop those that are not going to populate real fields, like x_odoo_message_id.

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by jado95** [comment]
@micheledic Sorry, but you solved problem with this commit? 
I still have error with this change.

**Comment by micheledic** [comment]
> @micheledic Sorry, but you solved problem with this commit? I still have error with this change.

When do you have this issue?
If you have this issue on l10n_it_fatturapa_pec, there is a fix committed last week
https://github.com/OCA/l10n-italy/commit/4fb4219e54ddbc13e9305b4fc3d499cee900271a

**Comment by jado95** [comment]
> > @micheledic Sorry, but you solved problem with this commit? I still have error with this change.
> 
> When do you have this issue? If you have this issue on l10n_it_fatturapa_pec, there is a fix committed last week [OCA/l10n-italy@4fb4219](https://github.com/OCA/l10n-italy/commit/4fb4219e54ddbc13e9305b4fc3d499cee900271a)

Thanks, It was what I needed

**Pull request closed without merging**
