### PR TITLE
[IMP] base: allow to archive res.partner.bank

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
If partner change bank account, it is impossible to archive him.

@nim-odoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW 2262683

cc @alexis-via

**Comment by qdp-odoo** [comment]
looks fair enough, I suppose we don't need a filter to get all the archived ones in list view nor be able to see those records in the partner view...

So let's @robodoo r+

Thanks!

**Comment by fmdl** [comment]
this filter is not automatic now ?

**Comment by qdp-odoo** [comment]
No, the filtering is automatic (active=True is implicitly added by the ORM) but if you want a filter in a search view to see the archived records you need to add it manually, but I don't think we need it. ;-)

**Comment by fmdl** [comment]
@pedrobaeza the idea is to 'avoid send money in old bank account'.

**Comment by pedrobaeza** [comment]
I totally agree on that idea, but this should be refined. I would propose:

1. Add `active_test=False` on context of the partner bank account list view, for seeing both inactive and active accounts, with decoration for showing in grey the inactive ones.
2. Add toggle button in that list for enabling/disabling them.

**Comment by qdp-odoo** [comment]
@pedrobaeza yes you can: add the custom filter on active=False and in the form view, click  'action > unarchive'

**Comment by qdp-odoo** [comment]
@robodoo r+

I said!

**Comment by pedrobaeza** [comment]
@qdp-odoo I mean here it's not user friendly/UX/call it whatever:

Selección_006

and imagine this flow:

- Someone archive (by accident or by a misinformation) one bank account.
- Later, they ask to the customer/vendor for the same account not having it, and it's the same.
- You try to add that bank account, and Odoo doesn't allow saying there's a duplicate!

In that flow, you have to:

- Know that archiving bank accounts they are kept but hidden.
- Know where to go for having all bank accounts.
- Know how to show archive bank accounts.

That's why I think the flow should be improved this way or allowing to reactive the bank account "magically", which is not the best option I think.

**Comment by qdp-odoo** [comment]
@pedrobaeza I approved this one already as it already a nice improvement, but feel free to propose another PR to improve the usability if you'd like. ;-)

**Pull request closed without merging**
