### PR TITLE
[FIX] product: Add products without 'combination_indices' to cart.

### PR DESCRIPTION
**Pull request by arbaes**
Sometimes when we try to buy a product that doesn't have any variants,
it would result in an error saying there isn't any valid combination
for that product.

This was happening because `_get_variant_id_for_combination` was
considering that the field `combination_indices` would always be
equal to `''` (empty string) in such a case.

This isn't true as `combination_indices` isn't a required field
thus allowing `null` \ `None` to be valid values for that field.

This fix will simply include products with no values set for their
`combination_indices` when searching a corresponding variant from
the `product_template`.

### CODE REVIEW

**Comment by arbaes** [comment]
@seb-odoo after discussion with @tbe-odoo , we came to the conclusion it would probably better to make a better fix in master, by either setting `combination_indices` as required or using a Many2many field.

**Comment by seb-odoo** [comment]
The issue happens only after a migration I think ? So I believe the best fix is to ensure the migration is setting the empty string instead of null.

Then the field should indeed be required, it is the only way to make sure the unique index `product_product_combination_unique` works as expected too. We do not want the same product_template to have one variant with empty string and one variant with null at the same time.

The many2many field exists already (`product_template_attribute_value_ids`), it's just too inefficient to search.

**Comment by tbe-odoo** [comment]
> The issue happens only after a migration I think ? So I believe the best fix is to ensure the migration is setting the empty string instead of null.
> 
> Then the field should indeed be required, it is the only way to make sure the unique index `product_product_combination_unique` works as expected too. We do not want the same product_template to have one variant with empty string and one variant with null at the same time.
> 
> The many2many field exists already (`product_template_attribute_value_ids`), it's just too inefficient to search.

Hello, this should be handled by the code instead of the migration scripts.
Some of our customers have hundred of thousand `product.product` and I know for sure that the migration team wouldn't like the idea to slow down their migration scripts.
Plus this could cause issues in the future with customers doing SQL "INSERT" that doesn't set the value of `combination_indices`.
Since the field isn't required we must take in consideration that there will be NULL values.

**Comment by seb-odoo** [comment]
We will still need to handle that in migration at some point if we make it required in master, which it should have been in the first place (my bad).

As for v13, I'm ok with the diff here, but I'm letting you know it is hiding a bigger problem.
Strange bugs will happen if we let an active template have one variant with null and one with empty string at the same time.
So ideally the sql constraint should be adapted accordingly too.

Another solution, if we want to allow NULL for migration reasons, is to adapt the code of `_compute_combination_indices` (or of `_ids2str`) to never save the empty string, but set NULL instead in that case (+ have matching constraint to ensure it).

**Comment by tbe-odoo** [comment]
> We will still need to handle that in migration at some point if we make it required in master, which it should have been in the first place (my bad).
> 
> As for v13, I'm ok with the diff here, but I'm letting you know it is hiding a bigger problem.
> Strange bugs will happen if we let an active template have one variant with null and one with empty string at the same time.
> So ideally the sql constraint should be adapted accordingly too.
> 
> Another solution, if we want to allow NULL for migration reasons, is to adapt the code of `_compute_combination_indices` (or of `_ids2str`) to never save the empty string, but set NULL instead in that case (+ have matching constraint to ensure it).

Hello, the only way (in stable) to fix the duplicates would be to create a Python constraint since we are not allowed to change the database scheme (it includes the SQL constraints). I'll add that in the commit :)

**Comment by tbe-odoo** [comment]
> > We will still need to handle that in migration at some point if we make it required in master, which it should have been in the first place (my bad).
> > As for v13, I'm ok with the diff here, but I'm letting you know it is hiding a bigger problem.
> > Strange bugs will happen if we let an active template have one variant with null and one with empty string at the same time.
> > So ideally the sql constraint should be adapted accordingly too.
> > Another solution, if we want to allow NULL for migration reasons, is to adapt the code of `_compute_combination_indices` (or of `_ids2str`) to never save the empty string, but set NULL instead in that case (+ have matching constraint to ensure it).
> 
> Hello, the only way (in stable) to fix the duplicates would be to create a Python constraint since we are not allowed to change the database scheme (it includes the SQL constraints). I'll add that in the commit :)

After thinking about how we can fix this issue on stable branches, the only viable solution was to handle the fact that we create a new column on migration without setting an empty string as the value for the ones that weren't computed.

This issue still need to be fixed in master, so I'll merge this commit to handle the cases where the column is NULL but I suggest to set the field as required in master.

Can I let you do the change in master?

Thanks :+1:

**Comment by tbe-odoo** [comment]
@robodoo r+

**Comment by seb-odoo** [comment]
Hello @tbe-odoo 

Thank you for the fix here! Please review the change in master at #44266

**Pull request closed without merging**
