### PR TITLE
[CLA] add new member to Adhoc CLA

### PR DESCRIPTION
**Pull request by PabloPaezSheridan**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nicomacr — APPROVED** [review]

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `p...@gmail.com`
- you are signing _for_ the address `p...@adhoc.com.ar`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by PabloPaezSheridan** [comment]
@mart-e Thanks martin, i have just change my signature email and force push the same commit. It is okay now? or a new PR is needed?

**Comment by mart-e** [comment]
@PabloPaezSheridan sorry but it's still the same issue. The source email is still gmail.
You can check your commiter information at https://github.com/odoo/odoo/pull/74720.patch

**Comment by PabloPaezSheridan** [comment]
supersede #74975

**Pull request closed without merging**
