### PR TITLE
[FIX] Compatibility with psutil 3.0. The replacing method has been

### PR DESCRIPTION
**Pull request by StefanRijnhart**
available since psutil 2.0. See http://grodola.blogspot.com/2014/01/psutil-20-porting.html

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Failing runbot seems unrelated. Same Phantomjs errors in other PRs, such as https://github.com/odoo/odoo/pull/7051

**Comment by antonylesuisse** [comment]
Move it  to a function at the top and do it backward compatible getattr(p,'memory_info',getattr(p,'getmemeory_info'))()

**Comment by StefanRijnhart** [comment]
You are right, no need to drop compatibility with psutils < 2.0. Latest commit tested with 1.2.1, 2.2.1 and 3.0.0

**Comment by antonylesuisse** [comment]
thanks @mart-e please merge it.

**Comment by mart-e** [comment]
Thanks for the patch, merged at 3940a096b2f0c5cf9815f9abac43a6df920a15d7

**Pull request closed without merging**
