### PR TITLE
[IMP] mrp, purchase, stock: demo data

### PR DESCRIPTION
**Pull request by svs-odoo**
A few changes in the demo data to makes things more practical and/or more constant.
Also, don't forget... Demo Data is love, Demo Data is life.

### CODE REVIEW

**Comment by ticodoo** [comment]
Looks good to me. Just 2 minor comments:

1. Your fix for WH/OUT/00005, I think the same problem exists for some of the "Done" delivery examples where there are done moves but no corresponding done move lines shown (e.g. WH/OUT/00002 ,00006, and 00007). Not sure if it matters since they're already done.

2. I would just point out in `[IMP] stock: increase acoustic bloc screens qty.` commit that you're really just fixing the id name (to not be an already used one). I got a little confused looking at it out of context.

**Comment by svs-odoo** [comment]
@ticodoo 
1. Indeed, I didn't fix them because they are done like you said, but also it cost nothing to fix them either so I'll do it too. Thanks :) 
2. As it used the same id than a later one, the inventory line was erased. The purpose of this commit was to increase the Acoustic Screens qty. and I figured out I can do that just by renaming this record id. So, the purpose is a [IMP] but it's factually a [FIX], and to be honest, I didn't know which one is better for the commit name. But I guess rename it for [FIX] with a little explanation will be less confusing :sweat_smile:

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
robodoo rebase-ff

**Comment by amoyaux** [comment]
robodoo r+ rebase-ff

**Pull request closed without merging**
