### PR TITLE
[FIX] base: give has_group access to internal user


### PR DESCRIPTION
**Pull request by nle-odoo**
The code comment says non-internal users should not have access to
has_group if it's not for themselves. But the code checked the group
of the targetted user, not the current user.

Added test failed without fix failed because an AssertError was not
raised, and an AssertError was raised when it should not have.

note: found when reviewing 18.0 forward-port of d0828eecf60f7c8622d6875b

opw-4096073

### CODE REVIEW

**Review by kmagusiak — APPROVED** [review]

**Comment by nle-odoo** [comment]
thanks

robodoo r+

**Comment by nle-odoo** [comment]
robodoo r-

I see that @odoo/rd-security was assigned so could be good to get input. The change should be safe because it was the original intent.

For stability, this could break code that relied of the wrong implementation but it would be correct. And in majority of use case, we should be sudoed (eg. through access env.user) or an internal user when doing the has_group case.

**Review by xmo-odoo — APPROVED** [review]
Fix makes sense given the comment.

**Comment by nle-odoo** [comment]
thanks

robodoo r+

**Pull request closed without merging**
