### PR TITLE
16.0

### PR DESCRIPTION
**Pull request by optesis-ibg**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by optesis-ibg** [comment]
Update tax account

**Review by Levizar — CHANGES_REQUESTED** [review]
Hello @optesis-ibg ,

Could you squas the commits (except the CLA one) and make the commit message compliant with the [guidelines](https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#commit-message-structure) ?

**Comment by optesis-ibg** [comment]
[FIX] correct the accounts used in tax configuration to comply with the current COA

**Comment by Levizar** [comment]
Hello @optesis-ibg ,

I'm not sure to understand: Are you going to squash your commits or do you expect me to do it ?

**Comment by optesis-ibg** [comment]
Hello @Levizar could you do it for me please

**Comment by Levizar** [comment]
@mart-e The person removes doesn't appear as an author in any commit.
I checked with the following commands:
`git log --oneline --author="khalifa" | wc -l` and `git log --author="optesis"`
The last one has 4 commits made by someone else.

Let me know if it's ok

**Comment by Levizar** [comment]
@robodoo r+

**Comment by Levizar** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
