### PR TITLE
[FIX] mail,web: Change command palette shortcut

### PR DESCRIPTION
**Pull request by sebgeelen**
Change the command palette shortcut from CTRL+K to CTRL+M,
in order to avoid conflict with link creation shortcut in editor.

task-2635043

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sebgeelen** [comment]
@brboi is this ok for you ?

**Review by brboi — APPROVED** [review]

**Comment by sdegueldre** [comment]
@robodoo delegate=brboi

**Comment by brboi** [comment]
robodoo r+

**Comment by sebgeelen** [comment]
> robodoo r+

I think you did not called robodoo properly, you missed the @.

**Comment by sdegueldre** [comment]
@sebgeelen no, works fine without the @, you can see on the PR dashboard that review is checked, we're just waiting for CI

**Pull request closed without merging**
