### PR TITLE
Master account improvements kme

### PR DESCRIPTION
**Pull request by kme-odoo**
Task : https://www.odoo.com/web?debug#id=48064&view_type=form&model=project.task&action=327&menu_id=4720
Pad : https://pad.odoo.com/p/r.944550e8ea3992b82dbd101788f8882c

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rgo-odoo** [comment]
LGTM

**Comment by smetl** [comment]
@kme-odoo Can you plz rebase this branch on the latest version?

**Comment by rgo-odoo** [comment]
@smetl task has been canceled, do you still want it to be rebased ?

**Comment by smetl** [comment]
@rgo-odoo If the task is canceled, no need to rebase :)

**Pull request closed without merging**
