### PR TITLE
Add country 'Kosovo' to odoo/odoo/addons/base/res/res_country_data.xml

### PR DESCRIPTION
**Pull request by jvOrsouw**
@lap-odoo 
Description of the issue/feature this PR addresses:
Kosovo is recognized as a country by the majority of the EU and around the world. However it is not in the countries-list of Odoo
Current behavior before PR:
Kosovo is not a country
Desired behavior after PR is merged:
Kosovo can be selected as country on a partner

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hmo-odoo** [comment]
Hello @jvOrsouw ,

PR is not good. can you resubmit again base on our guidelines ?

https://github.com/odoo/odoo/wiki/Contributing#making-pull-requests

Thanks

**Comment by jvOrsouw** [comment]
wow, not helpful at all. it's really frustrating to be told to make a PR
but not being offered any help.


[image: Odoo Experts] <https://www.odooexperts.nl/>


Met vriendelijke groet,

Julia van Orsouw
06 - 28 43 20 82

Odoo Experts
088 - 377 40 00
Vredeweg 1s1505 HH Zaandam
https://www.odooexperts.nl

[image: Twitter] <https://twitter.com/odooexperts> [image: Facebook]
<https://www.facebook.com/Odooexperts> [image: Google +]
<https://plus.google.com/+OdooexpertsNl> [image: LinkedIn]
<https://www.linkedin.com/company/odoo-experts> [image: Youtube]
<https://www.youtube.com/c/OdooexpertsNl>

Klik hier voor het laatste blog van onze Odoo Experts
<https://www.odooexperts.nl/blog/alle-blogs-3/?utm_source=email&utm_medium=handtekening&utm_campaign=email%20banner>



2017-11-16 14:29 GMT+01:00 Harshad Modi <notifications@github.com>:

**Comment by Yenthe666** [comment]
Hi @jvOrsouw,

I believe you've chosen the wrong branch when you made this PR.
You're trying to merge changes from the master version of Odoo into the 11.0 version of Odoo.
It is quite hard to explain you what you've did wrong but let me try to 'guess' a bit 😉 
If I am not mistaking you have a local repository (something in the lines of jvOrsouw/Odoo somewhere) with the changes for the country in. You then made a pull request to Odoo but didn't change the remote repository (which by default links to odoo/odoo) to jvOrsouw/Odoo.
Due to this you've made a PR from the Odoo master version to the Odoo 11.0 version. 
Anyways, if you paste the code here that you want to added in I'll make a PR for you. I'll explain it to you in real when I'm at Odoo Experts if you'd like. 😉

**Comment by Yenthe666** [comment]
@hmo-odoo no offense but your message was quite short too. Atleast try to help new contributors, they might actually bring a lot to the table in the future. It would be nice to have more contributors that help Odoo.

**Comment by jvOrsouw** [comment]
@Yenthe666 thank you for your quick response and kind words. I'll do something in my repository and send it to you. I'll also reread the guidelines, who knows, maybe they'll start making sense somewhere to a non-developer like me.

**Comment by Yenthe666** [comment]
@jvOrsouw you're welcome. About the guidelines: not the best place to learn about PR's / adding features though. Perhaps this can help you? https://help.github.com/articles/creating-a-pull-request/
This might be of interest for you: https://help.github.com/articles/creating-a-pull-request/#changing-the-branch-range-and-destination-repository

**Pull request closed without merging**
