### PR TITLE
[IMP] base: add kuwait states

### PR DESCRIPTION
**Pull request by niyasraphy**
before this commit, Kuwait states are not added
in res.country.state model.

after this commit, kuwaiti states are added
to the res.country.state model.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
hi @jco-odoo ,
it is not mandatory to have, from the city name itself the states/governorates can be identified easily.

as of now, we add this states from the data files, for the customers, so thought of nice to have this list in the odoo core itself.

**Comment by jco-odoo** [comment]
@niyasraphy Normally, we do not add them if they are not required.

**Comment by niyasraphy** [comment]
thanks for letting me know @jco-odoo ,
even same in master also ?

**Comment by jco-odoo** [comment]
@niyasraphy Normally, yes.

**Pull request closed without merging**
