### PR TITLE
[IMP] orm/all: Make _name or _inherit mandatory

### PR DESCRIPTION
**Pull request by Gorash**
This is a request following the revert of the use of class names (concerning the python inheritance and typing project)

see: https://github.com/odoo/odoo/pull/178200
see: https://github.com/odoo/odoo/pull/186906

### CODE REVIEW

**Review by rco-odoo — APPROVED** [review]
@robodoo r+

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo r-
(sorry but it makes staging [fails and split](https://runbot.odoo.com/runbot/build/72248737), seems that an _name is missing in enterprise `whatsapp_account_followup/models/account_followup.py`)

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
