### PR TITLE
[IMP] mail: lateral join for perf improve

### PR DESCRIPTION
**Pull request by nseinlet**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nseinlet** [comment]
Does this improve perf ?

**Comment by tde-banana-odoo** [comment]
@nseinlet Don't know, seems to be framework / platform job (see https://github.com/odoo/odoo/pull/67004 ).

**Comment by nseinlet** [comment]
From 22s to 1 ms

Prior this change:
https://explain.dalibo.com/plan/2Cn
After this change:
https://explain.dalibo.com/plan/QpZ

I'll ask @rco-odoo to deeper test this.

**Comment by C3POdoo** [comment]
Dear @nseinlet,

Thank you for your contribution but the version saas-15.3 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
