### PR TITLE
[FIX] mail: show file links when notifying a record by mail

### PR DESCRIPTION
**Pull request by kitan191**
- Go to any record with a chatter (i.e. a SO)
- Use full composer to send a message
- In editor, use "File/Image" option to upload a document to the body of the message
- Upload any document (i.e. a PDF file)
- PDF icon will appear in the message
- Send the message
In the chatter, PDF icon appear in the message, allowing to download the file.
But in the sent mail, the link is present but it is not visible.

It is due to fact that links to documents generated by editor don't have any
text as the icon is used instead.

When notifying a record by mail, the body will be parsed to add a label to these links.
As the editor used file name to set the title attribute of the link, the title can be
used as label.

opw-2558602

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kitan191** [comment]
@fw-bot ignore

**Comment by kitan191** [comment]
@fw-bot up to master

**Comment by tde-banana-odoo** [comment]
Strange code, and probably not for stable... not sure what you are trying to do.

**Comment by kitan191** [comment]
> not sure what you are trying to do.

Adding a document with web editor will generate a link like this:
```html
<a class="o_image" title="my_file.pdf" style="xxx"></a>
```
This fix will add a label to the link to have this:
```html
<a class="o_image" title="my_file.pdf" style="xxx;width:100%">my_file.pdf</a>
```

**Comment by tde-banana-odoo** [comment]
Then maybe fix the editor itself, if really necessary.

**Comment by kitan191** [comment]
> Then maybe fix the editor itself, if really necessary.

In the editor, there is no label because a file icon is displayed instead via css.
https://github.com/odoo/odoo/blob/13.0/addons/web/static/src/scss/mimetypes.scss

Not sure what can be done.

**Pull request closed without merging**
