### PR TITLE
[FIX] mail: Don't use body in access link

### PR DESCRIPTION
**Pull request by macadelic80**
Issue

    - Install "project"
    - Create a log note and tag marc demo

    The mail sent to marc demo contain the message body in the link access

Cause

    The body message is present on kwargs

Solution

    Delete 'body' key

opw-2377002
Fix of my previous commit: #60998

### CODE REVIEW

**Comment by nboulif** [comment]
LGTM. The only possible place where `body` can be present in the kwargs is here : https://github.com/odoo/odoo/blob/fbd30f4266d86b53aa4b13b72a93bccee0d7eb69/addons/mail/models/mail_thread.py#L2590
So I guess it is safe to pop body from params in `_notify_get_action_link` func.
@nim-odoo

**Comment by abz-odoo** [comment]
> So I guess it is safe to pop body from params in `_notify_get_action_link` func or even before the call.


I also asked myself the question, but since there were already several instructions where we removed keys in `_notify_get_action_link` I thought I might as well do it here too

**Comment by nim-odoo** [comment]
Looks ok, but you need to detail why it causes an issue. In this case, URI too large (see https://discord.com/channels/@me/762694727437910036/775359501460832286)

@tde-banana-odoo FYI

**Comment by tde-banana-odoo** [comment]
Ouch, did not see this one coming. I think we should whitelist kwargs we give to local_params, not blacklist entries. Otherwise you may end up with funny results, like subject or author in a link (or worse ... ) .

Grepping the code, I see we use: controller, res_id, model, all signup parameters (portal), access_token . Should probably be safer.

**Comment by abz-odoo** [comment]
@tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
As this fix is still not correct, I reverted the original commit in 13, see https://github.com/odoo/odoo/pull/61591

We will make a complete fix with a task and a real testing phase this time.

**Pull request closed without merging**
