### PR TITLE
[FIX] odoo: Previous date in datetime field if use date widget with …

### PR DESCRIPTION
**Pull request by carlosdauden**
…GMT+X zone and time 00:00:00

Description of the issue/feature this PR addresses:
User with zone GMT+1
Save datetime field with 16/05/2018 00:00:00 value
In custom report shows only date with options widget
`<span t-field="o.datetime_field" t-options="{'widget': 'date'}"/>`
Report shows previous day 15/05/2018

Current behavior before PR:
Report shows 15/05/2018

Desired behavior after PR is merged:
Report shows 16/05/2018

@Tecnativa

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why not doing directly only `value = fields.Datetime.context_timestamp(self, value)`?

**Comment by carlosdauden** [comment]
Because https://github.com/odoo/odoo/blob/23431389c36e57bfce99afb97abfca6a062cfc74/odoo/fields.py#L1569

**Comment by carlosdauden** [comment]
@pedrobaeza I understand you now
I put the condition because this case will be given a few times and I do not want to dismiss the PR for "overload"

**Comment by pedrobaeza** [comment]
Check runbot status. I'm going to dismiss my review, as I'm not sure about the possible side effects. I let an expert on this area to decide.

**Comment by carlosdauden** [comment]
@pedrobaeza runbot green

**Comment by JKE-be** [comment]
wip c18b4a1bb6a8157cfdd2c583787ef61a30ef819a

**Comment by JKE-be** [comment]
Thanks for the PR
I have updated a little bit the code, seems to work with new tests 51acdeba4f9f8ed00ee85271e7da24574ab8dfbb

**Pull request closed without merging**
