### PR TITLE
[FIX] website_sale: fix broken ecommerce mobile layout

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses:

screenshot-2021-01-14T10-46-44

screenshot-2021-01-14T10-47-33

Current behavior before PR:

screenshot-2021-01-14T10-48-08

Desired behavior after PR is merged:

screenshot-2021-01-14T10-55-46

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@Tecnativa TT27738

### CODE REVIEW

**Comment by JKE-be** [comment]
In my memory it was by design to only support a max height and hidden the overflow. To avoid exactly what you suggest and the side effect if you have a very very long description... It is a preview, you can click on it to see the full website description. 8d6f89fd442747abedcd719d2988a3664be424cc
 
About the publish/unpublish, yes we could try to fix it. 
Let see what @bvr-odoo think about it

**Comment by bvr-odoo** [comment]
> In my memory it was by design to only support a max height and hidden the overflow. To avoid exactly what you suggest and the side effect if you have a very very long description... It is a preview, you can click on it to see the full website description. [8d6f89f](https://github.com/odoo/odoo/commit/8d6f89fd442747abedcd719d2988a3664be424cc)
> 
> About the publish/unpublish, yes we could try to fix it.
> Let see what @bvr-odoo think about it

FireShot Capture 459 - Shop - My Website - 5745909-12-0 runbot52 odoo com
There is still a max-height of 200px in mobile, so for me that fixes the problem for the moment .. even if it is not yet the ideal solution because we cut a line horizontally . This should be avoided

**Comment by bvr-odoo** [comment]
Finally we are not going to keep this because it does not solve the main problem (how to display only a few lines without cutting them) but just change the display.
And as anyway the problem does not exist anymore in V13, it is not really worrying ...

**Comment by Yajo** [comment]
Why do we really need to have a max height in mobiles? 🤔  It doesn't make much sense IMHO because there's no need to do vertical alignment with other elements in the grid, so having that max height is the cause of the problem after all.

> as anyway the problem does not exist anymore in V13, it is not really worrying ...

This doesn't show much empathy for v12 users. It's worrying if you see your ecommerce formatted like that. You'll think you will scare your buyers instead of encouraging them to buy, and you'll be probably right.

The fact you won't have to fw-port the fix actually is a +1 for merging it, IMHO.

**Comment by bvr-odoo** [comment]
> Why do we really need to have a max height in mobiles?
Because if descriptions are very long users will have to scroll too much between each product in the list. And because it was always like that, and we cannot change the layout (and especially if it's an imp and not a fix, the real issue is not fixed ;))

**Comment by Yajo** [comment]
I guess we diverge in the definition of "the real issue", but nevermind. I uploaded a patch that fixes it:

imagen

At least, it's usable, and ellipsizes descriptions after 3 lines of text.

It applies [this example](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp#truncating_a_paragraph), which according to the table below is supported in all major browsers today.

**Comment by Yajo** [comment]
So, could this be merged?

**Comment by JKE-be** [comment]
Hello
I know that you will hate me even more...
But as you said: I guess we diverge in the definition of "the real issue"

It has been designed like that in v12 and we prefer to not change it in stable version and risk to break old production database for a change that is not 'required' to make the page readable. 

It is more a change to do in your own theme if you need it.

In master we already implemented a similar patch imm.

**Pull request closed without merging**
