### PR TITLE
[FIX] miscellaneous fixes and improvements on Japanese CoA

### PR DESCRIPTION
**Pull request by yostashiro**
- Fixes incorrect user type assignments on some accounts
- Fixes incorrect account assignments on taxes
- Adds a few accounts that Japanese companies would typically need
- Changes some account codes to make the structure more consistent
- Updates descriptions of some taxes to make them appear more natural on PDF reports

@qrtl

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e could you ask the person responsible for accounting in Japan to check this PR please? Not sure who it is.

**Comment by mart-e** [comment]
@jco-odoo only some chart of accounts as Belgium or Switzerland are in multi-language and where the account translation really matters. For most l10n modules, we don't really care.

**Comment by yostashiro** [comment]
@jco-odoo It's been a while. Do you need any info from me to proceed with the merge?

**Comment by jco-odoo** [comment]
That got out of my sight, but it looks ok.  I will check next week together with @nim-odoo

**Comment by jco-odoo** [comment]
@nim-odoo It is ok for merging to me.  I installed also myself, but maybe in 10.0-fixjp-jco the commit message is a bit better.

**Comment by KangOl** [comment]
Due to conflicts, I had to ignore changed made into `addons/l10n_jp/data/account.tax.template.csv` in version 11.0 forward-port.

Can you verify and update 11.0 in a new PR?

**Comment by jco-odoo** [comment]
@KangOl it is probably just the tax group that was added.

**Comment by KangOl** [comment]
No, it's not just that. Some other fields have also be changed.

**Pull request closed without merging**
