### PR TITLE
[FIX] point_of_sale: Using variable 'balance' before assignment

### PR DESCRIPTION
**Pull request by davidtranhp**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by trj-odoo** [comment]
What does this fix? The `balance` is still being properly used in the catching part.

**Comment by davidtranhp** [comment]
> What does this fix? The `balance` is still being properly used in the catching part.

No, it is not. And it get complained when running in debug mode (--log-level=debug)

Let's try this simple example
```python
try:
    balance = 2 + ""
except Exception:
    print(balance)
```
Then you will get NameError: name 'balance' is not defined
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
NameError: name 'balance' is not defined
```

**Comment by trj-odoo** [comment]
The try/except was not meant for the `balance`, so I don't see how the `balance` would be buggy there.
It's not a game breaking bug and was anyway changed here https://github.com/odoo/odoo/pull/107968

**Comment by davidtranhp** [comment]
Tks @trj-odoo 
So, I'm closing this now.

**Pull request closed without merging**
