### PR TITLE
[FIX] point_of_sale: bring translation changes

### PR DESCRIPTION
**Pull request by arva-odoo**
This commit contains remaining changes which need to added in this https://github.com/odoo/odoo/pull/112394.

sentry-3824163568

### CODE REVIEW

**Comment by arva-odoo** [comment]
Hello, @abz-odoo  @adwid  @yelizariev 

Can you please check this PR?

Thanks!

**Comment by arva-odoo** [comment]
Hey @trj-odoo, @abz-odoo 
Translation still remains in this PR [112394](https://github.com/odoo/odoo/pull/112394), so a new PR is created for it.
Could you please take a look at this?
Thanks a lot

**Review by yelizariev — APPROVED** [review]
LGTM

**Review by abz-odoo — APPROVED** [review]

**Comment by adwid** [comment]
fw-bot ignore
robodoo r+

**Pull request closed without merging**
