### PR TITLE
[IMP] tooltip payment term

### PR DESCRIPTION
**Pull request by fhe-odoo**

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you but it seems that the tooltip is too long now.
tooltip

**Comment by fhe-odoo** [comment]
That's what I was worried about. Can we then maybe add the examples in grey text in the wizard below the field? Or just keep the second example. Up to you.

**Comment by mart-e** [comment]
Well actually I was wondering if we really need to put several examples. Do you think the current one is not clear enough?

**Comment by mart-e** [comment]
We have removed this field at 6e5db46626f23846ba671d39ee74001aa5803b77 to make something a bit less magic

**Pull request closed without merging**
