### PR TITLE
[FIX][V14] Marshall frozendict in XMLRPC

### LINKED ISSUE #75412: [V14]XMLRPC cannot unmarshal frozendict
### Impacted  versions:
v14
tested with demo 

### Steps to reproduce:

call the context_get method on res.users

### Current behavior:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/controllers/rpc.py", line 69, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/controllers/rpc.py", line 50, in _xmlrpc
    return dumps((result,), methodresponse=1, allow_none=False)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 968, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 501, in dumps
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 519, in __dump
    raise TypeError("cannot marshal %s objects" % type(value))
TypeError: cannot marshal <class 'odoo.tools.misc.frozendict'> objects
```

this is mainly caused by this part https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/res_users.py#L649

### Expected behavior:

As for v12 and v13, the context values has to be returned.

### PR DESCRIPTION
**Pull request by flotho**
FIX: https://github.com/odoo/odoo/issues/75412

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Makes sense ! Thanks.

**Comment by flotho** [comment]
Hi @Elkasitu @xmo-odoo any review here would be appreciated

**Review by saxomanu — APPROVED** [review]
Good job

**Review by Elkasitu — APPROVED** [review]
Thanks! Could you amend your commit message to comply with [our guidelines](https://www.odoo.com/documentation/14.0/developer/misc/other/guidelines.html#commit-message-structure) ?

i.e. no `[v14]` in the message head and the reasoning behind your patch

**Comment by flotho** [comment]
Hi @Elkasitu ,

Is it better ?

Regards

**Comment by flotho** [comment]
@Elkasitu , thanks for your commit, it's easier  to understand your convention

**Comment by Elkasitu** [comment]
Thank you for your contribution!

@robodoo r+

**Comment by flotho** [comment]
> Thank you for your contribution!
> 
> @robodoo r+

so it will be merged ? Am I correct ?

**Comment by Elkasitu** [comment]
> > Thank you for your contribution!
> > @robodoo r+
> 
> so it will be merged ? Am I correct ?

Yes, it is being merged as we speak

**Comment by Yenthe666** [comment]
Good idea @flotho 😄 thanks!

**Comment by flotho** [comment]
thanks, really proud of this contribution.
I'll be able to merge this one : https://github.com/odoo-java/odoo-java-api/pull/15

Regards

**Pull request closed without merging**
