### PR TITLE
[FIX] website_sale: existing transaction

### PR DESCRIPTION
**Pull request by simongoffin**
If the transaction already exists, the amount total of the transaction must
be updated.

opw:634119

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Can you explain (in the commit) when this issue occurs ?

**Comment by simongoffin** [comment]
Alright! I asked to @tde-banana-odoo  before making my fix.

**Comment by beledouxdenis** [comment]
Fine then :+1:

**Comment by tde-banana-odoo** [comment]
LGTM.

**Comment by beledouxdenis** [comment]
Closed with d3711f2cab4dc708d3ce23e9e93920600925b8fe.

**Pull request closed without merging**
