### PR TITLE
[FIX] maintenance: add widget upgrade boolean to enterprise module

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
* Module maintenance worksheet is from enterprise, we should add widget upgrade_boolean for it to avoid misunderstanding from customer

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duong77476-viindoo** [comment]
Hello @clesgow @ajf-odoo Can you take a look, i think module `maintenance_worksheet` is from enterprise so can i add widget `upgrade_boolean` sir ?

**Comment by clesgow** [comment]
Good catch! :+1: 
Thank you for the PR! Since this is unintended behavior, would you mind changing the tag of your commit title to `[FIX]` instead of `[IMP]`? :slightly_smiling_face:

**Comment by duong77476-viindoo** [comment]
@clesgow Done sir, pr both title and commit . I discovered it when checking is there any res config view in maintenance module or not keke :v

**Comment by clesgow** [comment]
Thanks!
@robodoo r+

**Pull request closed without merging**
