### PR TITLE
[FIX] website_sale_stock: changed '_get_combination_info' signature

### PR DESCRIPTION
**Pull request by Tardo**
Description of the issue/feature this PR addresses:
Fix method signature to avoid inheritance problems.

Current behavior before PR:
Can't inherit properly

Desired behavior after PR is merged:
Avoid inheritance problems

Cc @tecnativa

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@JKE-be this change of signature is dangerous. Not sure why CI is failing.

**Comment by seb-odoo** [comment]
I think we specifically didn't change it in v12 back then to avoid risks. Do you have an actual issue with that, or it is just for cleaning?

If it's just cleaning, target should be master (or saas-12.5 in this case). If there is an issue, it should be described so we can assess if it's work the risk.


Small remark, commit message should start with a verb as per guideline https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-header

**Comment by pedrobaeza** [comment]
We detected the problem with this overriding:

https://github.com/OCA/apps-store/blob/485c510f55629b81eaadbc41983e3b9473795d3a/website_apps_store/models/product_template.py#L29

Which is legitimate according to main method signature:

https://github.com/odoo/odoo/blob/1a9393c8d7cef5f06e47ef1c657d3cb6fe037d25/addons/sale/models/product_template.py#L169

but `website_sale_stock` module alters with no reason one of the keyword arguments, provoking an error about `parent_combination` argument not valid.

**Comment by seb-odoo** [comment]
The issue can be avoided by using args instead of kwargs when calling `super` in this case.

**Comment by pedrobaeza** [comment]
@seb-odoo we are not using neither of them... we are directly using full signature. This is not the same case as with `message_post` (that we have got already some issues with that). And even using `args` and `kwargs`, the problem is the same: a kwarg is renamed to other name, so in the dictionary mapping at the top-parent method, the error would be the same of a non existing kwarg.

**Comment by seb-odoo** [comment]
`vals = super()._get_combination_info(combination, product_id, add_qty, pricelist, parent_combination, only_template)`
This doesn't work?

**Comment by pedrobaeza** [comment]
Strictly speaking, yes, it can work, but you are converting keyword arguments to positional arguments, which is a source of problems like it's happening with `message_post` using it without putting `body=...`. As this is clearly a misuse of Python stuff, I think it qualifies for this easy bugfixing, and there's no possibility of breaking anything as the proper argument name is the other (and use in `sale` and `website_sale` module).

**Comment by seb-odoo** [comment]
@mart-e I would like your opinion on this, acceptable risk/reward?

**Comment by mart-e** [comment]
Yes it looks fine, the method signature in `website_sale_stock` does not match the one of the other methods.
The branch needs to be rebased to avoid the `test_17_css_bundle_date_invalidation` error.
@seb-odoo see https://github.com/odoo/odoo/wiki/Mergebot#merge-a-communitys-contribution for merging community contributions, including rewriting commit messages

**Comment by Tardo** [comment]
Rebased and changed commit message

**Comment by seb-odoo** [comment]
Thank you

@robodoo r+

**Comment by pedrobaeza** [comment]
Thanks to you! :smiley:

**Comment by mart-e** [comment]
@seb-odoo @seb-elico  the important information in the commit message is the _why_ (not the _what_). It does not need to be long but it should be present.
https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure

@robodoo r+

**Comment by Tardo** [comment]
@mart-e I hope it's right now

**Comment by mart-e** [comment]
@Tardo yes, thanks

@robodoo r+

**Comment by mart-e** [comment]
robodoo retry

**Comment by mart-e** [comment]
@robodoo I am getting tired, retry

**Comment by mart-e** [comment]
@d-fence r+ as @robodoo does not want

**Comment by d-fence** [comment]
pfff f*** rte_translator
robodoo retry

**Comment by JKE-be** [comment]
@d-fence where is the screenshot ?

**Comment by d-fence** [comment]
> @d-fence where is the screenshot ?

Only available in saas-12.5 and master, sorry.
https://github.com/odoo/odoo/commit/0dc4a63e2dec57f3187501129f2670a3f4463e79

**Comment by JKE-be** [comment]
ha ok, c bon a savoir... ca veut donc dire que rte translator n'est pas peter que en saas-12.5 / master comme on pensait... 
Ou en tout cas que a chaque fix que on va fair en 12.0, va falloir une varian en 12.2, et en 12.5

**Comment by d-fence** [comment]
C'est pas le même step. Est-ce le même bug ?

**Pull request closed without merging**
