### PR TITLE
[FIX] stock_landed_costs: Adjust the last line's value for currencies with decimal_places as 0

### LINKED ISSUE #56433: [BUG][13.0] stock_landed_costs: Adjust the last line's value for currencies with decimal_places as 0
**Impacted versions:** v13 (but probably others as well)

**Steps to reproduce:**
1. Create a purchase order with 3 products:
- [DESK0004] Customizable Desk (CONFIG) (Aluminium, Black)
- [E-COM06] Corner Desk Right Sit, 
- [E-COM07] Large Cabinet
2. Confirm Order -> Receive Products -> Validate
3. Create a Landed Costs for the PO above with 1 product:
- Product `Shipping cost`, `Cost` as 10 VND, `Split Method` as Equal 
4. Click on `Compute` button

**Current behavior:**
- After the allocation, the new value is added with 1 VND due to rounding.

**Expected behavior:**
- Adjust the value of the last line for currencies with decimal_places as 0

**Video/Screenshot link (optional):**
Brush-#1

### PR DESCRIPTION
**Pull request by royle-vietnam**
**Impacted versions:** v13 (but probably others as well)

**Steps to reproduce:**
1. Create a purchase order with 3 products:
- [DESK0004] Customizable Desk (CONFIG) (Aluminium, Black)
- [E-COM06] Corner Desk Right Sit, 
- [E-COM07] Large Cabinet
2. Confirm Order -> Receive Products -> Validate
3. Create a Landed Costs for the PO above with 1 product:
- Product `Shipping cost`, `Cost` as 10 VND, `Split Method` as Equal 
4. Click on `Compute` button

**Current behavior:**

- After the allocation, the new value is added with 1 VND due to rounding.
Brush-#1

**Desired behavior after PR is merged:**
- Adjust the value of the last line for currencies with decimal_places as 0

Closes #56433 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@amoyaux @sle-odoo can you take a look to this?

**Comment by lathama** [comment]
@royle-viindoo knowing that 13 is no longer updated, is this PR still needed?

**Comment by royle-viindoo** [comment]
> @royle-viindoo knowing that 13 is no longer updated, is this PR still needed?

Hi @lathama , We used version 17.0. I think it's still needed for the community. You can close it if you think you don't need it.

**Comment by C3POdoo** [comment]
Dear @royle-viindoo,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
