### PR TITLE
[FIX] hw_drivers: Don't terminate Manager thread on exception

### PR DESCRIPTION
**Pull request by raf-odoo**
If you unplug the iot box and wait 15 seconds or so, and then plug it
back in, it's possible to get an exception from helpers.get_ip, because
neither the wired nor the wireless interface has an IP. In that case,
the exception would kill the Manager thread, since it was uncaught.

This fix adds a catch-all to the Manager thread that logs any uncaught
exceptions and continues its main loop.

### CODE REVIEW

**Comment by raf-odoo** [comment]
Example traceback:

```
2021-09-13 13:09:58,591 10417 ERROR ? odoo.addons.hw_drivers.controllers.driver: Traceback (most recent call last):
  File "/home/pi/odoo/addons/hw_drivers/tools/helpers.py", line 136, in get_ip
    return netifaces.ifaddresses('eth0')[netifaces.AF_INET][0]['addr']
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/odoo/addons/hw_drivers/controllers/driver.py", line 548, in run
    self.send_alldevices()
  File "/home/pi/odoo/addons/hw_drivers/controllers/driver.py", line 368, in send_alldevices
    domain = helpers.get_ip()
  File "/home/pi/odoo/addons/hw_drivers/tools/helpers.py", line 138, in get_ip
    return netifaces.ifaddresses('wlan0')[netifaces.AF_INET][0]['addr']
KeyError: 2
 
```

**Comment by raf-odoo** [comment]
Potential cause for 2357144, where a deadlock was observed, but no hard confirmation yet that it's the same issue because there was no data captured during the time of the event.

**Comment by raf-odoo** [comment]
@qle-odoo Could you review this one?

**Comment by raf-odoo** [comment]
> Potential cause for 2357144, where a deadlock was observed, but no hard confirmation yet that it's the same issue because there was no data captured during the time of the event.

While I haven't been able to capture data yet during the event, I have been able to capture network data afterwards. There were two scenarios: one where there was no communication at all, and one where the terminal and box were in a loop connecting and disconnecting. That'll look like this in the network traffic:

Screenshot from 2021-09-20 13-18-23

Both of these can be reproduced by killing the Manager thread. Which one you get depends on the timing of when the Manager is gone.

If the Manager dies very early, when no socket devices exist yet, the SocketManager will accept a connection from the terminal and will create a new socket device. Because the Manager is dead, no driver thread is created to read from it. The terminal will send a HelloRequest and will block indefinitely. This corresponds with the scenario where there is no network traffic after the initial connection and HelloRequest.

If the Manager dies at a moment where a socket device was already created in the past, but no corresponding driver thread exists (either because the driver thread terminated itself due to an exception or due to unfortunate timing when the Manager terminates) and the terminal attempts a new connection (because a lost network connection was restored, or the terminal restarted, or its 5 second keepalive timeout expired during an ongoing conversation where the initial HelloRequest got a reponse from the box), the SocketManager will immediately close the connection after accepting it. That's because it will attempt to replace the old connection but detect there's no corresponding driver thread, which shouldn't happen. There isn't a way to recover from that situation, so it closes the new connection. After which the terminal tries again. That results in the loop of three-way handshake + FIN in the screenshot. It's a bit odd that the terminal still sends a HelloRequest (the line with the S101 protocol) after the connection has closed, resulting in the RST, but this isn't strictly related to the rest of the issue, and doesn't have a significant impact.

Both cases are prevented by making sure the Manager thread keeps running. They could also happen if something causes the Manager thread to block indefinitely, but I'm currently not aware of a situation in which that's possible.

I've observed situations where the network connection temporarily dropped in 2357144, which would trigger the above issues. The longest such period was around 2 hours of no connectivity.

**Comment by raf-odoo** [comment]
The above issue can be triggered on a network with a slow DHCP response by unplugging the network cable on the IoT box, waiting a bit and plugging it back in again. When that has happened and the Manager has terminated, you'll get an error in the POS about the terminal not being connected (that's normal) when attempting a payment. If you press the back button in the UI, you'll get a traceback (that's not normal). I'll do a separate PR for that.

https://user-images.githubusercontent.com/68840520/134010336-f3ec25b3-29ef-49f6-b58d-c74c7cbcf754.mp4

**Comment by raf-odoo** [comment]
PR for the UI issue: https://github.com/odoo/enterprise/pull/21020

**Review by qle-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
