### PR TITLE
[15.0][IMP]-l10n_es Add taxes Retenciones IRPF 19% y 35% Consejeros y administradores

### PR DESCRIPTION
**Pull request by EmilioPascual**
Backport: https://github.com/odoo/odoo/pull/130728

Add taxes in l10n_es:

- Retenciones IRPF 19% Consejeros y administradores
- Retenciones IRPF 35% Consejeros y administradores

Current behavior before PR:

Update taxes list with 2 new taxes.

Issue : https://github.com/OCA/l10n-spain/issues/3174

All the legal documentation that @rafaelbn posted in https://github.com/OCA/l10n-spain/issues/3174#issue-1833315892

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lordkrandel** [comment]
@jco-odoo you have r+ed the main PR

@EmilioPascual CLA check says "Email not found in cla file andrea@moduon.team", see: https://www.odoo.com/sign-cla

**Comment by rafaelbn** [comment]
@lordkrandel both, Emilio an Andrea are under a corporate CLA: https://github.com/odoo/odoo/blob/17.0/doc/cla/corporate/moduon.md

**Comment by yajo** [comment]
You'll have to cherry-pick https://github.com/odoo/odoo/commit/712bcc6d25d2929ba44f0c9c091f80bc5e49517e for the 15.0 branch.

@moduon MT-3705

**Comment by jco-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
