### PR TITLE
remove unnecessary account type constraint

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@beledouxdenis 
Close without any explanation whereas this PR fixes a real problem.
Please reopen and merge.

**Comment by beledouxdenis** [comment]
@luc-demeyer 
PR opened without any explanation whereas no issue is associated to this proposal.
Please provide an explanation of the issue solved by this PR.

**Comment by luc-demeyer** [comment]
@beledouxdenis 
The description I gave was "remove unnecessary account type constraint" which is exactly what this PR fixes.
Some more (functional) explanation:

Accounts of type "receivable/payable" are used for open invoices from customers/suppliers.
When creating the opening entries of a new fiscal year, you don't want to have (potentially thousands) of useless opening entries since reconcile doesn't happens on the ("auto-reconciled") opening entry but on the account move lines of the original invoice.
Therefor it's you should be able to configure the payable/receivable account type as deferral balance and hence this unnecessary (wrong) constraint must be removed.

**Comment by beledouxdenis** [comment]
Well, claiming a constraint "unnecessary" without any explanation isn't a sufficient description to judge if this pull request is right or not.

Constraints are rarely done for nothing.

@qdp-odoo, can you confirm Luc's thoughts
>When creating the opening entries of a new fiscal year, you don't want to have (potentially thousands) of useless opening entries since reconcile doesn't happens on the ("auto-reconciled") opening entry but on the account move lines of the original invoice.
Therefor it's you should be able to configure the payable/receivable account type as deferral balance and hence this unnecessary (wrong) constraint must be removed.

Thank you :)

**Comment by qdp-odoo** [comment]
we must keep the constraint because that's the only way you can work in a context of fiscal year correctly: if you just bring forward the balance of payable/receivable accounts then all the reporting you'll do for the new fiscal year will only show the balance and you won't have the detail per partner. 

Hence all your reporting on partner entries for the new fiscal year will be wrong.

**Comment by luc-demeyer** [comment]
@qdp-odoo 
Quentin,
Incorrect answer.
We run with correct accounting reports without this constraints for six years now.
Our localisation module removes this constraint since the beginning (it's just a matter of using the correct partner accounting reports). The approach you take in the standard account module is not appreciated by customer's who understand accounting and doesn't scale for real life customers (I am not talking about the small company with a few outstanding open invoices at year end but for real companies this goes into the thousands or hundred thousands).

Have a look to the community partner reports (e.g. account_financial_report_webkit or account_open_payables_receivables.xls) on apps.odoo.com and you'll see that the accounting reports work correctly with clean opening entries based on "balance" settgins for all balance accounts as expected by accountants.

**Comment by qdp-odoo** [comment]
anyway, this is a behavior change and our policy regarding stable version disallow such changes.

And in v9, the constraint has already been removed... so there's no need to argue more.

**Pull request closed without merging**
