### PR TITLE
[IMP] website: add new `s_motto` snippet

### PR DESCRIPTION
**Pull request by anso-odoo**
This commit introduces the new `s_motto` intro snippet.

Part of task-4077427
task-4077607

requires: https://github.com/odoo/design-themes/pull/851

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by stefanorigano — APPROVED** [review]
LGTM, thanks 👍

**Review by SergeBayet — APPROVED** [review]
Great snippet! LGTM.

**Comment by sobo-odoo** [comment]
@robodoo delegate=SergeBayet

**Comment by SergeBayet** [comment]
@anso-odoo runbot is red (error already known). I'll wait the merge of the other PRs to avoid conflicts. When the pipe is clean I'll r+ this one.

**Review by SergeBayet — APPROVED** [review]

**Comment by SergeBayet** [comment]
@anso-odoo Could you resolve the conflicts? This PR is the next one to be merged. Thanks

**Comment by stefanorigano** [comment]
@SergeBayet , anso is off today. I'll handle that 👍

**Comment by stefanorigano** [comment]
@SergeBayet , ready 😉

**Comment by SergeBayet** [comment]
> @SergeBayet , ready 😉

@stefanorigano you have to rebase the design-theme as well. The two PRs are unsync.

**Comment by stefanorigano** [comment]
@SergeBayet , done. Thanks

**Comment by SergeBayet** [comment]
@robodoo r+

**Pull request closed without merging**
