### PR TITLE
[IMP] mail: chat window, thread, message slight style improvements

### PR DESCRIPTION
**Pull request by alexkuhn**
- chat window header commands: compacter, less visible
- message actions: less visible when not hovered, no border on click
- new message banner slightly smaller and warning style, text bolder
- HH:mm on non-squashed message for datetime
- slightly smaller and less visible datetime on message
- horizontal padding on date section and new message separator
- date section has shorter month name
- chat window is rounder, bottom is rounded too
- jump to present button reduced border opacity + shadow-sm added

Before
Screenshot 2024-11-26 at 15 23 38
After
Screenshot 2024-11-26 at 15 26 42

### CODE REVIEW

**Review by tsm-odoo — APPROVED** [review]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo retry

**Pull request closed without merging**
