### PR TITLE
[IMP][14.0] account: Restructure code to create payment

### PR DESCRIPTION
**Pull request by tranngocson1996**
This PR
-------
With the old code, the method to create payment is quite large (approximately 100 lines). So that leads to hard to read and customize. I want to refactor the code so as to improve code without altering functionality. Break down methods into smaller methods that do specific tasks

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tranngocson1996** [comment]
@FlorianGilbert long time no see bro. Can you review this PR for me? Thank bro

**Comment by tranngocson1996** [comment]
@FlorianGilbert Does anyone help me ?
cc: @qdp-odoo @Yenthe666

**Comment by tranngocson1996** [comment]
@FlorianGilbert don't forget me. plz :(
cc: @qdp-odoo

**Comment by FlorianGilbert** [comment]
Hello @tranngocson1996 

Sorry, I was on holiday.
I understand why you want to make this change, do you need it specifically in 14?
If not, can you do this change in master instead? Thank you!

**Comment by tranngocson1996** [comment]
> Hello @tranngocson1996
> 
> Sorry, I was on holiday. I understand why you want to make this change, do you need it specifically in 14? If not, can you do this change in master instead? Thank you!

@FlorianGilbert oh happy new year bro.
I see this function has been disassembled. It's so good. but before it was really bad because it was too long. So i will close this pr. thank you

**Pull request closed without merging**
