### PR TITLE
[FIX] calendar: include recurrent event to read_group result

### PR DESCRIPTION
**Pull request by adwid**
In list view, when using the "Group By" functionality, if some events
are recurrent, the numbers of grouped events are incorrect: the
repetitions of the recurrent events are not counted.

To reproduce the error:
(Let "Mitchell Admin" be the current user's name)
1. Create an event E
	- Must be recurrent with 3 repetitions
2. Go to list view
3. Group by Responsible

Error: The number of events associated to Mitchell Admin is incorrect.
If the user clicks on the line (so he can see all Mitchell Admin's
event), the incorrect number will change and count all recurrences of
the events. (In this case: "Mitchell Admin (X)" becomes "Mitchell Admin
(X+2)", the repetitions of E-event have been added). The user should not
have to click on the line in order to get the correct number of events.

Note: This fix should be applied up to version 13. Afterwards, the
structure of the module has changed and the problem no longer occurs.

OPW-2455705

### CODE REVIEW

**Comment by adwid** [comment]
@simongoffin

**Comment by adwid** [comment]
@tivisse Could you give me your opinion on this ?

**Comment by tivisse** [comment]
@arj-odoo Could you have a look ? 

The 12.0 version is nearly out of life, and the old virtual events management in kind of a nightmare.

I'm not sure the added value is worth the change.

**Comment by arj-odoo** [comment]
@adwid Thanks for your proposition. I agree with @tivisse on this one. The old implementation of google calendar was quite difficult to maintain and not reliable. We are currently focusing on improving the new implementation to provide a better experience with recurrent event synchronization with google. So unfortunately, we cannot merge your changes.

**Pull request closed without merging**
