### PR TITLE
[IMP] account_edi_ubl: allow to export generic ubl

### PR DESCRIPTION
**Pull request by bfr-o**
TASK ID: 2361217

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smetl** [comment]
@bfr-o Can't you clear some override in `l10n_be_edi` then? Shouldn't we remove the l10n_be IDE format and "adapt" this EDI when the current company is BE?

**Comment by Yenthe666** [comment]
No UBL 3.0?

**Comment by bfr-o** [comment]
@Yenthe666 What do you mean by UBL 3.0 ? UBL only go up to 2.3. If you're talking about BIS Invoice Billing 3.0 you must look at the EN16931 standard.

**Comment by bfr-o** [comment]
Covered by https://github.com/odoo/odoo/pull/61118

**Pull request closed without merging**
