### PR TITLE
[WIP][10.0][IMP] Banking Round with decimal ROUND_HALF_EVEN

### PR DESCRIPTION
**Pull request by mileo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mileo** [comment]
USA: http://physics.nist.gov/cuu/pdf/sp811.pdf page 55
IEEE: https://en.wikipedia.org/wiki/IEEE_floating_point#Roundings_to_nearest
Germany: DIN-1333: https://de.wikipedia.org/wiki/Rundung#Kaufm.C3.A4nnisches_Runden
France: https://www.economie.gouv.fr/dgfip/arrondis#IA

Python: https://www.python.org/dev/peps/pep-0327/#rounding-algorithms

**Comment by rvalyi** [comment]
cc @sebastienbeau @alexis-via

**Comment by mileo** [comment]
Python3
-----------

```
mileo@lfmileo-XPS-L421X:~$ python3.5
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> round(1.3333, 2)
1.33
>>> round(1.125, 2)
1.12
>>> round(1.128, 2)
1.13
```

Python2
-----------

```
mileo@lfmileo-XPS-L421X:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> round(1.3333, 2)
1.33
>>> round(1.125, 2)
1.13
>>> round(1.128, 2)
1.13
```

**Comment by mileo** [comment]
cc: @aricaldeira

**Comment by odony** [comment]
@mileo Is there a point in all the references you posted apart from showing that rounding to nearest with even tie-breaking is a thing? ;-)

Other remarks:
- I don't mind adding the HALF-EVEN rounding method, but this [should go to master](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch), not 10.0
- implementing the rounding with Decimal is not a good idea. Our other rounding methods are based on float primitives for speed and consistency. In addition, Decimal does not handle rounding factors that aren't powers of 10. This is not obvious but [hinted at by the documentation](https://docs.python.org/2/library/decimal.html#decimal.Decimal.quantize) which only mentions *the exponent* of the second operand. Here is an example:

```python
>>> import decimal
>>> value = 1.345
>>> decimal_value = decimal.Decimal(value)
>>> rounding_factor=0.05
>>> float(decimal_value.quantize(
...     decimal.Decimal(repr(rounding_factor)),
...     rounding=decimal.ROUND_HALF_EVEN))
1.34
``` 
- the minimal tests in `float_utils` do not cover the previous case, but other tests in our testsuite do (I suspect the CI results are green because your new rounding method is not used anywhere

- in Py3 the tie-breaking has changed to HALF-EVEN, and it is quite possible to preserve the HALF-UP rounding without using Decimal (see our WIP: #17114), making the HALF-EVEN implementation trivial, of course.

Thanks :)

**Comment by rvalyi** [comment]
cc @lmignon

**Comment by C3POdoo** [comment]
Dear @mileo,

Thank you for your contribution but the version 10.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
