### PR TITLE
[FIX] l10n_cl avoid warnings on module install

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:
Our nightly runbot installing all the CoAs is yellow at night because of some small warnings.  This should solve it.  

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@Danisan Can you check this?  Should not GBR be base.GBP instead?

**Review by Danisan — APPROVED** [review]

**Comment by Danisan** [comment]
> @Danisan Can you check this? Should not GBR be base.GBP instead?

@jco-odoo reviewing this some minutes ago with @suv-bmya realized that l10n_cl was put also to pounds. Is this ok?

**Comment by pedrobaeza** [comment]
Coming to this through codetriage.com. @jco-odoo is this still relevant?

**Comment by jco-odoo** [comment]
Not relevant anymore as the name was changed for customs abbreviation and if there were still problems with the currency we should have known.

**Pull request closed without merging**
