### PR TITLE
Alter domain for populate_statement in order to avoid a long list of IDs

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to avoid retrieving a long list of payment line IDs, only to use them in a ('id', 'in', [list]).

Also, since the fields_view_get is called when the module is updated, this also avoids getting a MemoryError if too many move lines are present (this will not fix the behavior if the wizard is open, however).

### CODE REVIEW

**Comment by gurneyalex** [comment]
LGTM :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by mdietrichc2c** [comment]
Actually, given that it only add a (now static and clean) domain to the field `lines`, the whole method could be removed and the view edited.

@gurneyalex , @pedrobaeza : what do you think?

**Comment by pedrobaeza** [comment]
Yeah, even better.

**Comment by gurneyalex** [comment]
@mdietrichc2c if this was the OCA code base I'd say "yes". As for stable Odoo, I'm not sure this would be ok with the stable policy rules, and I'd ask @odony for his opinion.

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the branch 7.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards

**Pull request closed without merging**
