### PR TITLE
[FIX] base: Commercial fields not syncing after changing parent_id

### PR DESCRIPTION
**Pull request by simongoffin**
Steps to reproduce the bug:

Here are aliases for the used contacts:
- A: Azure Interior
- B: Gemini Furniture
- C: Gemini Furniture, Edwin Hansen
- D: (delivery address for Edwin Hansen)

1. Login on a runbot.
2. Set VAT of A and B to different values.
3. Open C, and create a delivery address: D
4. Check: VAT of D = VAT of B
5. Change the related company of C from B to A.

Bug:

The VAT of C = VAT of A, however VAT of D did not change.

When syncing the commercial fields of a partner, we also sync his childs.

PS: Due to function _compute_commercial_partner, the commercial partner is always updated for all the childs.
    
So the condition child.commercial_partner_id != self.commercial_partner_id is never satisfied in function _children_sync and the commercial fields were never updated.

opw:3111493

### CODE REVIEW

**Comment by ryv-odoo** [comment]
Hello @simongoffin 

The customer create a other PR about it : https://github.com/odoo/odoo/pull/108662 . 
This PR fixes the same issue? If yes, can you take at least the test of the customer PR to check if it works ? 

Thank you.

**Comment by simongoffin** [comment]
Hello @ryv-odoo 

I add the test and it works

**Review by nle-odoo — APPROVED** [review]
looks good to me

**Comment by simongoffin** [comment]
Hello @ryv-odoo 

Is it ok for you?

**Review by ryv-odoo — APPROVED** [review]

**Comment by kmagusiak** [comment]
Hello @simongoffin 
Can this be merged?

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by jjscarafia** [comment]
thanks @simongoffin for the fix.
If there are plans to improve this logic on master, please consider also this https://github.com/odoo/odoo/pull/55239

**Pull request closed without merging**
