### PR TITLE
[FIX] purchase: Drop shipping with no access to Purchase

### PR DESCRIPTION
**Pull request by simongoffin**
Let's consider a Sales user U with no access to Purhcase

Steps to reproduce the bug:
- Create a SO with one line with the drop shipping route
- Validate the SO

Bug:

 A access error was raised because the user has no access right on
Purchase.

opw:1851301

### CODE REVIEW

**Comment by simongoffin** [comment]
Hello @amoyaux 

What do you think about it?

**Comment by amoyaux** [comment]
Hello @simongoffin it seems good to me. However you could also add it on 'write' call since you will have the same bug if you add these step to your usecase:
- Go back to your SO and add a new line or increment the existing one.

**Comment by gdgellatly** [comment]
Is this multicompany safe?

**Comment by amoyaux** [comment]
The company id is in the values. So the search/create/write should filter on the current company. Perhaps I'm missing something, do not hesitate to correct me if I'm wrong.

**Comment by gdgellatly** [comment]
@amoyaux My concern was not with company_id specifically, but rather defaults that rely on property fields that assume their company from the user.  

Honestly I don't know if it is a problem, I just saw the code with no force_company in sudo and thought it strange not to have in that piece of code.  But its a long time since I worked in this area of codebase.

**Comment by amoyaux** [comment]
@gdgellatly I agree force_company would be better.

**Pull request merged**
