### PR TITLE
13.0 has group perf with indexing flvr

### PR DESCRIPTION
**Pull request by flvr-odoo**
Use the indexing of model in has_group

### CODE REVIEW

**Comment by flvr-odoo** [comment]
@mart-e

**Review by mart-e — APPROVED** [review]
Can you just change your commit message to something like
```
[IMP] base: improve perfomance of has_group

...
```

@robodoo delegate+

**Comment by xmo-odoo** [comment]
Also "improves slightly the perfomance" is not grammatically correct ;)

**Comment by mart-e** [comment]
robodoo retry

**Pull request closed without merging**
