### PR TITLE
Delete recurring invoice lines when their contract is deleted

### PR DESCRIPTION
**Pull request by guewen**
**Delete recurring invoice lines when their contract is deleted**

Impacted versions:
- 8.0

Steps to reproduce:
1. create a new contract
2. add recurring invoices lines to the contract
3. delete the contract

Current behavior:
- The recurring lines remains as orphan records in the database

Expected behavior:
- The recurring lines are deleted as well

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:

**Comment by guewen** [comment]
BTW the field should also be `required=True` to prevent such data integrity problems but I have some doubts it would be accepted in stable.

**Comment by guewen** [comment]
@mart-e is this an acceptable change for stable?

**Comment by yvaucher** [comment]
:+1:

**Comment by mart-e** [comment]
Indeed the `required=True` is not for stable but no problem for the `ondelete=cascade`. We access the recurring invoices only through the contract so it is useless to keep orphan entries (or in worst scenario, we could generate invoices for a contract no longer present).

*I will merge it soon*

**Comment by odony** [comment]
For the record, adding `required=True` seems fine here, even in stable. It will only affect the UI (if at all, as that FK column is not usually shown anywhere), until it can be applied as a NOT NULL constraint via an explicit update.
And during updates it cannot crash even if NULL entries exists : when the ORM cannot apply a NOT NULL constraint it skips it with a warning.
Seems to me it should be part of a proper fix for this issue indeed.

**Pull request closed without merging**
