### PR TITLE
[IMP] sale_(project): improve generic things in project

### PR DESCRIPTION
**Pull request by mitali-willdooit**
The purpose of the commit is to do the generic improvement for the
project:

So in this commit, do the following changes:
- duplicating a project, copy all milestones of the project, and
set is_reached and deadline field as 'False'.
- change the order of the state button in the sale order form view

task-2652943

### CODE REVIEW

**Review by xavierbol — COMMENTED** [review]
Thanks for your work ! 🙂 
I have made some comments and suggestions.

**Review by xavierbol — APPROVED** [review]
LGTM, thanks! 🙂

**Review by IT-Ideas — APPROVED** [review]
LGTM Thanks 🙂

**Comment by IT-Ideas** [comment]
@robodoo r+

**Pull request closed without merging**
