### PR TITLE
[IMP] l10n_mx: add IEPS taxes

### PR DESCRIPTION
**Pull request by JulienVR**
Add IEPS taxes and tax groups. Make sure the IEPS taxes are
`include_base_amount` and have a lower sequence than the IVA taxes.

Unify the names of the taxes and their labels on invoice.

Resequence the taxes to group them by nature.

task-3100679

### CODE REVIEW

**Review by smetl — APPROVED** [review]
Awaiting functional testing

**Review by smetl — APPROVED** [review]
@robodoo r+

**Comment by luistorresm** [comment]
Hello @JulienVR @smetl 

Whit this was changed the default tax to IEPS 8%, which is not common.

Captura de pantalla 2023-09-13 a la(s) 18 15 59


Why not keep 16%?

Regards

**Comment by JulienVR** [comment]
Hello @luistorresm, I just opened a PR to fix the default taxes and use the 16% ones. https://github.com/odoo/odoo/pull/135810

Best regards

**Pull request closed without merging**
