### PR TITLE
[L10N] add l10n_pcgo

### PR DESCRIPTION
**Pull request by optesis-ibg**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@optesis-ibg Could we check this for a next version?  I suppose this is meant for the syscohada countries, so why not try to improve the existing module there?

**Comment by jco-odoo** [comment]
@tsb-odoo

**Comment by optesis-ibg** [comment]
Hello Joss,
The chart of accounts in the syscohada countries have changed since 2018 with new accounts and rules. The current COA in the syscohada module in Odoo is not the correct one.
We use this new module for new setup and obliged to replace the existing module in odoo.com
Regards

**Comment by jco-odoo** [comment]
@optesis-ibg Ok, but then it is better to replace the bad one by a good one, but maybe we can talk about the best approach for this some time.

**Comment by tsb-odoo** [comment]
@optesis-ibg Is there anywhere we can find this new CoA you are referring to ? Can you share it + official documentation about it maybe ?

**Comment by tsb-odoo** [comment]
Hi @optesis-ibg, Is there some official documentations you can share with us about that new CoA since 2018 ?

**Comment by optesis-ibg** [comment]
> Hi @optesis-ibg, Is there some official documentations you can share with us about that new CoA since 2018 ?

[OHADA_Acte-uniforme-relatif-au-droit-comptable-et-à-l’information-financière-AUDCIF.pdf](https://github.com/odoo/odoo/files/5271731/OHADA_Acte-uniforme-relatif-au-droit-comptable-et-a-l.information-financiere-AUDCIF.pdf)

**Comment by optesis-ibg** [comment]
> > Hi @optesis-ibg, Is there some official documentations you can share with us about that new CoA since 2018 ?
> 
> [OHADA_Acte-uniforme-relatif-au-droit-comptable-et-à-l’information-financière-AUDCIF.pdf](https://github.com/odoo/odoo/files/5271731/OHADA_Acte-uniforme-relatif-au-droit-comptable-et-a-l.information-financiere-AUDCIF.pdf)

[AUDCIF-OHADA-fr_COA.pdf](https://github.com/odoo/odoo/files/5272564/AUDCIF-OHADA-fr_COA.pdf)

**Comment by jco-odoo** [comment]
@optesis-art @optesis-ibg We made a PR here https://github.com/odoo/odoo/pull/61717 where we would like to replace the current syscohada with your updated one.  Could you check this one?  If there are any suggestions for a tax report (Maybe this is more defined by country as for syscohada as a whole, I don't know) and P&L/balance sheet, please let us know.  Thanks for your help!  @tsb-odoo

**Comment by mart-e** [comment]
Closing as the 12.0 is no longer supported

**Pull request closed without merging**
