### PR TITLE
[ADD] account: filter reconciliation with check number

### PR DESCRIPTION
**Pull request by william-andre**
Task 1881964
Allow to search for counterparts with a check number

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@william-andre commit message should be a "[IMP]" as "[ADD]" are basically reserved for new modules/files. 

also, are you suer you don't want the operator to be '=like'  ?

**Comment by william-andre** [comment]
@qdp-odoo I'll change the commit message. For the operator, I put = because I thought it might be weird having lines appear that don't have anything in common on the screen. Also, because you don't see the number, better be sure to have the right one and not a list of possible match.
Maybe see with @avw-odoo ?

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by william-andre** [comment]
This was reverted by #31095

**Pull request closed without merging**
