### PR TITLE
[FIX] web: session cookie lost between requests

### PR DESCRIPTION
**Pull request by Julien00859**
Attempt to fix the mighty nightly runbot

### CODE REVIEW

**Comment by Julien00859** [comment]
ping @d-fence fwi @flch-odoo

**Comment by Julien00859** [comment]
We found the problem

	POST /web/login
	cookies: session_id=abcdef...

	HTTP/1.1 200 OK
	set-cookie: session_id=zyxwv...


	POST /web/session/check
	cookies: session_id=abcdef... zyxwv...

requests is sending the session_id cookies in the reverse order, abc before zyx, thus the Odoo server uses the former non-logged one

**Comment by Julien00859** [comment]
In our findings the request comes with 2 cookies: the old one (that has been rotated) and the newer one (which is logged in). Odoo uses the older which is lame.

The thing is, I don't understand how comes two session_id cookies in the same request ? `requests` shenanigans ?

**Comment by Julien00859** [comment]
Werkzeug mini-server:

```py
@route('/werkzeug')
def werkzeug(environ, sr):
    req = Request(environ)
    resp = Response(str(req.cookies))
    resp.set_cookie('session_id', secrets.token_hex(8), httponly=True)
    resp.set_cookie('session_id', secrets.token_hex(8), httponly=True)
    return resp(environ, sr)
```

Python cli:

	>>> import requests
	>>> session = requests.Session()
	>>> def query():
	...     print("=>", [f"{c.name}={c.value}" for c in session.cookies])
	...     res = session.get('http://wsgi.localhost/werkzeug')
	...     print("<=", [f"{c.name}={c.value}" for c in res.cookies])
	... 
	>>> query()
	=> []
	<= ['session_id=e836249c4d393f93']
	>>> query()
	=> ['session_id=e836249c4d393f93']
	<= ['session_id=9aff18738e96e696']
	>>> query()
	=> ['session_id=9aff18738e96e696']
	<= ['session_id=443112c0691ae8ce']
	>>> query()
	=> ['session_id=443112c0691ae8ce']
	<= ['session_id=ec9274edd3e359c0']
	>>>
	>>> # Troubles
	>>>
	>>> session.cookies['session_id'] = 'blabla'
	>>> query()
	=> ['session_id=blabla', 'session_id=ec9274edd3e359c0']
	<= ['session_id=df07600b1f1d2d1c']
	>>> query()
	=> ['session_id=blabla', 'session_id=df07600b1f1d2d1c']
	<= ['session_id=9e33a08ba181a015']
	>>> query()
	=> ['session_id=blabla', 'session_id=9e33a08ba181a015']
	<= ['session_id=d8577fa802722153']

**Comment by d-fence** [comment]
robodoo r+

**Comment by d-fence** [comment]
The other errors on Jammy are not linked to this and will be fixed separately.

**Pull request closed without merging**
