### PR TITLE
Many2one updates with no label

### PR DESCRIPTION
**Pull request by Polymorphe57**

### CODE REVIEW

**Review by brboi — APPROVED** [review]
robodoo r-not-yet-+

**Comment by brboi** [comment]
Please Sir @robodoo r+ this pull request

**Comment by brboi** [comment]
robodoo method=rebase-ff

**Comment by brboi** [comment]
robodoo r+

**Comment by MiquelRForgeFlow** [comment]
conflicts

**Review by aab-odoo — APPROVED** [review]
robodoo rebase-ff r+

**Pull request closed without merging**
