### PR TITLE
[FIX] pos_restaurant: added an example for multi-variant in demo data

### PR DESCRIPTION
**Pull request by maad-odoo**
**Purpose of this commit:**
Added demo data to demonstrate multi-variant of a product where 
each product-variant have a different price.

task-3617006

### CODE REVIEW

**Comment by davidmonnom** [comment]
Hello :)

We try to have a uniform style for product images.

Can you ask the design team if you need a new one ? 

For example pizza image looks like that: 

image

**Comment by maad-odoo** [comment]
@davidmonnom 
Hello, 
I have added a new image as you said. Can you please have a look ?

**Comment by maad-odoo** [comment]
@davidmonnom Added the image that you gave.

**Comment by davidmonnom** [comment]
Isn't better to add like "multiple variant" with attribute of type "multi"  ?

image

**Comment by maad-odoo** [comment]
@davidmonnom It might have been a viable option, but the related task was canceled and merged with some other task elsewhere. Still needed?

**Pull request closed without merging**
