### PR TITLE
[FIX] tools: conversion of %20 into space

### PR DESCRIPTION
**Pull request by yosa-odoo**
Steps to reproduce:
In the chatter write a text containing `%20`.

Issue:
When sent, it is converted into a space ` `

Cause:
The body in https://github.com/odoo/odoo/blob/33764db718282f4e900c9fba00c9a925f0171b49/addons/mail/models/mail_message.py#L88
is has the parameter `sabitize_style` set to True. Therefore it will go through a reliquat of sanitization used to comply with the oldly used Junja/Mako

Solution:
Delete the `%20` from the sanitization step and only in Master.

opw-2747043
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yosa-odoo** [comment]
Whether we should deleted the whole sanitisation process linked to Jinja/Mako would have to be discussed.

**Comment by yosa-odoo** [comment]
Discussed with @tde-banana-odoo

**Comment by yosa-odoo** [comment]
@tde-banana-odoo we already discussed it. But idk if you want to suppress everything or just the bit that interests us for the fix aka %20

**Comment by xmo-odoo** [comment]
Since this is actively related to url-encoded data being posted to the chatter (as in literally URLs) the rest of this processing seems like it could also be an issue, which it might not be as much if this was about people writing percentages weirdly (aka writing %20 where most people would write 20%, though then the `$` one might still be a concern).

**Comment by tde-banana-odoo** [comment]
I think all this belongs to old mako or jinja support and could be cleaned. This require some detailed testing, notably with templates, qweb and links (static / dynamic), ... just to be sure about what we are doing ^^ .

**Pull request closed without merging**
