### PR TITLE
[CLA] Update initos.md

### PR DESCRIPTION
**Pull request by OSevangelist**
Update of the Contributer License Agreement

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by OSevangelist** [comment]
@mart-e this hasn't been merged. Is there any specific reason for that update not being merged so far ?

**Comment by mart-e** [comment]
Sorry, I missed your PR:
Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by OSevangelist** [comment]
no worries thanks for doing it now @mart-e

**Comment by mart-e** [comment]
@OSevangelist you can follow the merge status at https://mergebot.odoo.com/odoo/odoo/pull/184083
you see it’s ready to be merged, waiting for the next slot on the mergebot

**Comment by OSevangelist** [comment]
@mart-e thanks for the update and hint.

**Pull request closed without merging**
