### PR TITLE
in china, should use one line address format.

### PR DESCRIPTION
**Pull request by jeffery9**
in china, we use one line address.

### CODE REVIEW

**Comment by jeffery9** [comment]
@elicoidal  any comment about this.

**Comment by elicoidal** [comment]
@jeffery9 I have a problem with this setup even if I think it is correct (I would put the zip between parenthesis though).
It makes sense for address in Chinese (中文） but many companies in China need to be able to print addresses in English (with normal setup).
So I would go for it as it makes sense but it will not solve the problem, just transfer it...

**Comment by OpenERPJeff** [comment]
I want to support Jeffery for we are mainly provide service for china and this is why the address format customizable.  As for default value when database created, one line address format will more friendly for china companies.

**Comment by yunkuaiji** [comment]
support Jeffery! 支持！

**Comment by carllhw** [comment]
Good job

**Comment by ccdos** [comment]
good idea

**Comment by jaronemo** [comment]
I also agree jeffery view. 
Not only in China, the Taiwan market as well.

**Comment by leangjia** [comment]
I agree jeffery view. 支持Jeffery

**Comment by lonelyleaves** [comment]
support jeffery,the vast majority of which are using one line address

**Comment by elicoidal** [comment]
So I think we all have a agreement here!
:+1:

**Pull request closed without merging**
