### PR TITLE
[IMP] l10n_nz: Localization improvement

### PR DESCRIPTION
**Pull request by vin-odoo**
This commit brings out some more improvement to
the New Zealand localization.
It will mostly be about translating a few terms,
improving tax labels on invoices and mark invoices as "tax invoices".

Task id #3753652

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vin-odoo** [comment]
The translation is for Tax ID => GST on invoice pdf (and VAT => GST where it makes sense)
The new template & code was tested to make sure it won't break if the module isn't updated.

**Review by yosuanicolaus — APPROVED** [review]
Well done, LGTM! :+1:

final review by @gawa-odoo

**Comment by yosuanicolaus** [comment]
one small question: do we not need to add the `l10n_nz.pot` and `en_NZ.pot` here? or do we not need it since it's already in english?

**Comment by vin-odoo** [comment]
@yosuanicolaus The nz doesn't really have anything that should be translated so it wouldn't be useful to add them.
We won't translate to another language, and the terms in the module would already match the local english

**Comment by gawa-odoo** [comment]
Didn't know about the trick for the nz language to change these terms only, without being overriden by Transifex

@robodoo r+

**Pull request closed without merging**
