### PR TITLE
[IMP] lunch: make sure you can write the last location

### PR DESCRIPTION
**Pull request by RomainLibert**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by RomainLibert** [comment]
@tbe-odoo I updated the code

**Comment by tbe-odoo** [comment]
> @tbe-odoo I updated the code

The issue mentioned on my previous review is still present.
On some routes if `user_id` is provided and you are not manager, then the action is done using your user which is not the behavior we expect.

As you have done for the method "set_user_location" this should not do some magic trick and select your user.

I think you should raise an access right issue when needed.

**Comment by RomainLibert** [comment]
I was trying to avoid raising an exception as it will introduce new translations and I'm not sure I can do that in saas-12.2

**Comment by tbe-odoo** [comment]
> I was trying to avoid raising an exception as it will introduce new translations and I'm not sure I can do that in saas-12.2

For saas-12.2 it is ok to introduce "unstable" fixes since no one is using it yet ;)

**Comment by RomainLibert** [comment]
@tbe-odoo 
I now raise an AccessError when you try to impersonate someone else and you don't have the lunch manager access rights

**Comment by tbe-odoo** [comment]
@robodoo r+

Thanks @RomainLibert , this is perfect :+1:

**Pull request closed without merging**
