### PR TITLE
[8.0] Ignore canceled sales order lines

### PR DESCRIPTION
**Pull request by guewen**
**Ignore canceled sales order lines**

The sales order lines have a `canceled` state, but this state is not always considered when some logic is looping over lines. This check is done in some places already and this PR's aim is to do it in the remaining places.

We encountered this issue when developing the module [sale_amendment](https://github.com/guewen/sale-workflow/tree/8.0-sale_amendment/sale_amendment) which allows to amend sales orders and thus, to cancel only a part of the lines in a sales order.

How to reproduce on runbot (only a selection of things that are corrected here):
- Go to `Settings > Technical > User Interface > Menu Items`
- Create a new menu with name : `Sales Order Lines`, parent menu : `Sales/Sales`; action: `ir.actions.act_window`, `Sales Order Lines`.
- Go to `Sales > Sales > Sales Order Lines` 
- Search for the line from `SO005` with the product `[EXT-HDD] External Hard disk`
- Click on `Cancel Line`
- Open `SO005`
- Bug 1: the total amount still includes the amount of the canceled line
- Open the Delivery Order of the SO `SO005` and cancel it; the SO is now in `shipping_except`
- Go to the sales order `SO005` and click on `Recreate Delivery Order`
- Bug 2: the new delivery order has a move for the canceled order line

I am going to propose a similar PR on the purchases orders.

@qdp-odoo @jco-odoo  I would be glad if you could review this

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,


I just want to say that I'm supporting this approach 100%. We do want Odoo to be consistent with SO Lines handling: 

 * Have a same way to treat them in all the code
 * Be sure SO lines in state "cancel" 'aren't taken into account for reporting purpose
 * Ensure a correct behavior when re-creating deliveries
 * Deal correctly with procurement

Today, some places are well handled and other not. Having states on SO Lines is really something valuable for Odoo and it can really bring powerful features if done properly.

Please accept this patch :) Thanks a lot for your consideration on this one.

Regards,

Joël

**Comment by gurneyalex** [comment]
this is  a great patch, which will make writing extensions for customers much easier. The current situation with a state field on SO lines which is not considered is really not nice to extension writers and it breaks the principle of least astonishment.

:+1:

**Comment by guewen** [comment]
Here is the one for the purchase orders: https://github.com/odoo/odoo/pull/6038

**Comment by pedrobaeza** [comment]
What a huge work to identify all places where the behaviour is not consistent. Congratulations!

:+1: 

Can you please make the same PR to OCB meanwhile this PR is accepted (or not)?

**Comment by lepistone** [comment]
thanks! :+1:

**Comment by lmignon** [comment]
:+1:  Thank you @guewen !

**Comment by jco-odoo** [comment]
Normally, a sale order is (like) a contract with your customer and as such you are not supposed to change a sale order once confirmed (in the default behaviour).  It is also indicated in the explanation of the state of the sale order line: "The 'Cancelled' status is set when a user cancel the sales order related.'"

It seems far more logical not to allow for cancelling a sale order line.  (so practically removing the button in the code then)

**Comment by max3903** [comment]
@jco-odoo What do you propose then to match the use case ?

**Comment by guewen** [comment]
@jco-odoo note that I don't modify the behavior of Odoo in any way when only core modules are used.  The description you quoted is still true when solely core modules are used. But then you have the possibility to extend Odoo with additional modules that bring more features, such as amending sale orders. Features that can't be implemented if the state of the lines is not checked, that's why I propose these modifications.

**Comment by bealdav** [comment]
This is a required patch, in Odoo standard, thanks Guewen :+1:

**Comment by jco-odoo** [comment]
Normal procedure would be to cancel the entire sale order and to create a new one.  

@guewen so we would only include to make it easier for extensions then?

**Comment by guewen** [comment]
> @guewen so we would only include to make it easier for extensions then?

Not to make it easier, to make it *possible*.

**Comment by qdp-odoo** [comment]
although i understand the purpose, if there is no existing problem with the existing offical addons, we shouldn't touch the stable code and risk a regression. That's against our stable policy...

I'd gladly accept this pull request on the master branch, though.

**Comment by gurneyalex** [comment]
@jco-odoo cancelling the entire sale order is not always convenient. E.g. you may have done partial shipping already for instance and things get tricky from then on. And cancelling + recreating also means having a new SO reference number, which makes tracking previous conversions difficult and is something that in my experience people don't want. 

@guewen's patch does not change the core behavior. It merely ensures that partners / the OCA can build a solution for these issues by using the SO lines state as a basis for their customers without having erroneous behavior in the core.

**Comment by mylbco** [comment]
:+1:  This is really usefull. @jco-odoo I think you should also consider that the community needs those kind of things to build on ... Should be done at the start of v8 !

**Comment by jgrandguillaume** [comment]
Hi @jco-odoo @qdp-odoo ,

It's a complex topic and related to dealing with the exceptions that occurs in day-to-day business. My points about why we should accept it:

 * In some part of the code, you take care of the SO line state (like when you create an invoice, it skip the canceled SO lines and your invoice is correct), in some other (most of them) you don't. So to be consistent why not accepting this very clean patch ? Stable policy is about changing the model right ? and we don't...

 * @qdp-odoo Today in standard Odoo I have a button on SO lines to cancel them, so there is an existing trouble currently :

 * Doing this will allow the community and partners to bring powerful features to Odoo  in new modules (like amending SO, PO)


Tested in Odoo runbot, when you want to change an existing SO:

A. Create a Sales Order for 10 units
B. Confirm (Delivery Order is created for 10 units).

Option 1 - Customer tells you before you deliver any, that they want 8, not 10:

C. Edit the Delivery Order, change 10 to 8. 
D. Transfer
E. SO shows 100% delivered.
F. Create the Invoice, change 10 to 8.
G. Validate
H. Pay
I. SO shows 100% invoiced.
J. State of SO is set to DONE.

Option 2 - Customer tells you after you have delivered 8, that they only want 8.

C. Edit the Back Order, change 2 to 0.
D. Transfer 0 items (silly UI defect, you have to change the qty transferred also to 0 - this wasn't the case at v7).
E. SO shows 100% delivered.
F. Create the Invoice, change 10 to 8.
G. Validate.
H. Pay.
J. State of SO is set to DONE.

The trouble we have here is that the SO doesn't reflect the final status of the order, making all reports based on sales wrong.

**Comment by Viggor** [comment]
:+1: Thanks!

**Comment by bealdav** [comment]
Hi @jco-odoo @qdp-odoo,
I confirm that all our customers are really in trouble with the state field standard behavior.
This field currently doesn't represent the real situation as said above. 
In big business, they are cancelled/amended lines, and you can't cancel a sale order with 100 lines with partial deliveries, you should amend it with whole consistency.
Thanks to reconsider it

**Comment by qdp-odoo** [comment]
Guys, i understand you may need it but let me say you can't push for such refactoring to land on stable versions and on the other hand complain about regressions. Stable policy isn't just about keepin' the models.

Anyway, i'm not the final decision taker, not the potential merger, not even the one that will fix any future problem related to this patch: i'm just giving my opinion... ;-)

@odony Olivier, can you confirm if this patch may land in v8 or not?

**Comment by lepistone** [comment]
Thanks a lot for your time.

**Comment by petrus-v** [comment]
Looks great job! thanks for cleaning things

That's shame there is no test to show up bugs, until Odoo PR policy is fuzzy about unit tests, I expect that will be merged!

**Comment by michaelkarrer81** [comment]
Thank you very much! Great work!

**Comment by sebastienbeau** [comment]
:+1: great work, the module *_amendment will save us a lot of time and really improve the workflow for our customer. I really hope that this will be merged, if not then we will use OCB

**Comment by mylbco** [comment]
@qdp-odoo stability policy .... :+1: 
selection_297

**Comment by odony** [comment]
@mylbco The stable policy Quentin is talking about is [here](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) if you'd like to read it. It has actually nothing to do with runbot.

**Comment by mylbco** [comment]
@odony thx ...
'"However beautiful the strategy, you should occasionally look at the results. WC"

**Comment by jco-odoo** [comment]
I had a quick look at the module and analysis (out of curiosity) and I wonder if it is not more logical to change the quantities on the sale order itself instead of on the picking.  Maybe it is better to amend the procurements and have something change everything behind it automatically than to amend the sale order afterwards.  Then, the question would also raise whether you split procurements or amend them.  (and where to keep the history)  Maybe this was discussed somewhere, I don't know.  As the sale order is changed, the needs change...

**Comment by jgrandguillaume** [comment]
@jco-odoo Happy to know you're investigating that :) Let me explain you the why (you can read this thread on community mailing named "Cancel done delivery order" ).
 
* Changing everything everywhere is very bad and lead to very complex cases (lots of use case : invoice policy, already shipped, partially shipped, MTS, MTO, Drop shipping, etc...)
* We want to keep historic of changes, so canceling object to create new one is good
 * We want to respect the segregation of the responsibilities, sales manager should not touch picking.. it sounds like it is acceptable for purchase manager as they are in charge of the incoming.

So, our vision for sale_amendment is (quickly):

 * Ask warehouse keeper to cancel picking still not delivered yet => cancel linked procurement
 * SO goes in exception
 * Sales man click "Amend" and chose among the canceled quantities the one you want to amend
 * This will cancel the original SO lines and create new ones with selected quantity to amend, with their own procurement

=> This keep history, it is clean, you see in SO line what has been done. Other solution does it this way, so it seems to be the best practice. You can't increase the quantity, only decrease. If more quantity are needed, make a new SO (this is to keep the procurement & supply chain process clean)

Our vision for purchase_amendment is:

 * Purchase manager click on amend and chose the amended quantity to ship 
 * The system will cancel the proper line and create new ones with the new quantity.
 * It'll generate the pickings again

Here for purchase you can increase or decrease the quantity to amend because we have no impact. Also, the purchase manager will drive the incoming shipment. but here, we don't need the segregation of responsibilities right !

Those 2 processes have been reviewed and tested with a logician and we got the green light.

Regards,

Joël

**Comment by gurneyalex** [comment]
@jgrandguillaume s/logician/logistics specialist/ :smiley_cat:

**Comment by jgrandguillaume** [comment]
@odony Do you think this patch is against the policy ? My understanding:

 * Our patch will then have no impact for everyone, it excludes SO lines with state = cancel from loops. 
  * As stated by @jco-odoo , SO lines with state = cancel only happen if you cancel the whole SO

I conclude that our patch will never be used by a standard usage of Odoo where you can't cancel lines of SO alone right !? What do you say ?

In any case, please accept that patch at least on Master : https://github.com/odoo/odoo/pull/6064

Thanks for your review and time

**Comment by odony** [comment]
@guewen @jgrandguillaume The patch might be acceptable in stable, although it is certainly borderline. And it does impact regular use cases, as the scenario in the PR description shows for a vanilla 8.0.
And it would definitely benefit from clear test cases if you'd like this behavior to survive future versions.

Most of the changes seem acceptable, with these exceptions:

- Updating the total amount of a confirmed/done SO is a very bold move, especially without any obvious reason on the SO. Customers are used to the notion of confirmed documents (SO/Invoice) never updating significantly without explicit cancellation, most particularly the amounts.
Perhaps that recomputation should not happen in the core, as the user is likely to be unaware of the consequences. If they do want to update the SO total, it makes sense for them to work on the SO directly and cancel it explicitly.
Otherwise we'd need the cancellation and the cancelled lines to clearly stand out on the SO.

- The difference in computing the total amount when cancelled vs partially cancelled could be a very surprising behavior too, and at least deserves more comments in the code and tests.

What do you think?

**Comment by jgrandguillaume** [comment]
@odony First of all, thanks for your time on this one ! We do appreciate it a lot.

About your remarks:

 * **For the tests cases :** I completely agree with you. If you might accept this patch, consider it's done. We'll provide tests cases to ensure behavior now and for the future. We'll start working on it.

 * **For the difference in computing the SO total amount with cancel or partially cancel :** Here, the reasons are:
  * A full cancel SO means the agreement with the customer has been entirely canceled. The total amount is then the original total amount "agreed"
  * In case you only have one line out of many canceled, only this part of the agreement with your customer has been canceled. So IMO here, you want to exclude the canceled lines from the total amount, because the total amount of your agreement you had has changed. The user want to have the total amount corresponding to the agreement in front of him, one canceled line should then be excluded, otherwise you see kind of wrong information. With that also, the report based on sales is coherent : summing all lines not canceled in the system will be equal to the Amount total of all SO.
  *  **Last but not least,** creating an invoice from a SO with canceled lines already take care of the canceled lines (whatever the invoice policy is). That means, your invoice total amount will be equal to the SO lines confirm or done (the canceled lines are excluded). My point of view here is that the SO total amount should be consistent with your invoice total amount for controlling purpose. Note that we have a same behavior in other ERP (at least Axapta and Dynamics).

 * **For updating the Total amount of confirmed SO :** Same as above.

Now to move on I suggest:

 * We do start working on the tests
 * You chose if you agree if my arguments above:
  * **If yes**, then fine, we go for the suggested solution, with tests and proper comments to explain why the behavior is made this way (taking back my explanation above)
  * **If not**, I suggest then that we exclude from the patch the behavior in the SO total amount and we'll do it in an OCA module.

What do you prefer ?

Again, thanks a lot to take the time here.

Regards,

**Comment by nbessi** [comment]
:+1: Thanks for this huge work

**Comment by jgrandguillaume** [comment]
@odony @jco-odoo Any new/update on this one ?

**Comment by jco-odoo** [comment]
Main doubts we have is about how to interpret a cancelled state of a sale
order line: should it change the amount of the sale order or not (as it is
weird to have a cancelled sale order with an amount of 0), what is the
difference between a cancelled and a deleted line (if exception, should it
be regenerated?)

**Comment by jgrandguillaume** [comment]
@jco-odoo A SO line with state cancel should IMO not be taken into account in the SO total because:
 * Sale report will not take canceled line into account => You can verify your numbers by summing all SO line total and compare with SO total. So we need SO total to ignore the canceled lines.
 * Creating an invoice from SO ignore canceled SO line, so we should have the same behavior in the SO => so it is easy for controlling purpose to check that invoice total = SO total (in case of invoice based on delivery for example).
 * It is done this way in other tool and it is the best practice to keep track of what has been done. Deletion lose a part of the information, so we prefer to cancel instead.

The difference between cancel and delete is a good question. IMO, deletion of SO line should not be allowed except in draft. If you need to change something after that stage => you cancel them so you keep track of the infos.

If you want, I can add a check that prevent to delete SO line when the SO state is not draft ? Thanks for updating us about this one. We definitely need to know your position to go ahead with this topic !

Cheers,

Joël

**Comment by yvaucher** [comment]
@jco-odoo For a non cancelled order, cancelled lines shouldn't be considered in sums. As if you crossed it out.
However, if the order is cancelled all it's lines should be cancelled too, so in that case maybe we want to sum all cancelled lines in a cancelled order. But I'm not sure this would be intuitive.

**Comment by jgrandguillaume** [comment]
@odony @jco-odoo Any decision on this one ? Sorry to bother you guys, but we make the job, the tests, the comments and PR as requested. I need an answer to know how to deal with the related projects, and of course, I would appreciate a positive one ;) Honestly, I'm sure this is a good and coherent move forward. I've tested it and it really bring values to the sale process.

**Comment by jco-odoo** [comment]
@jgrandguillaume We looked at it together and we have no problem merging the skipping of cancelled lines in loops or the change of the report.  We think however that the amounts on the orders, should not change when cancelling a sale order line (as it is double with cancelling an entire order) and suggest you inherit the field in the module.

**Comment by jgrandguillaume** [comment]
@jco-odoo Thanks for the feedback ! We'll remove that from the PR and move ahead. However, keep in mind that doing this will make the SO total amount different from the invoiced total amount (as invoicing method skip the SO canceled lines). But it's fine for me and can live with that. Thanks a lot.

**Comment by lepistone** [comment]
Hi @jco-odoo @jgrandguillaume. As discussed, we removed the commits that change the total amount, leaving only the others. Thanks!

**Comment by odony** [comment]
Thanks for the update, just merged it. Please keep in mind that the core distribution does not really encourage or endorse this peculiar use of the SO line state, so we cannot promise that this behavior will still be supported in future versions.
For example we might choose to implement a different form of order fulfillment control/tracking, and remove this behavior. No plans yet for this, just mentioning it for the record :-)

**Comment by gurneyalex** [comment]
@odony well noted thank you. For symmetry and completeness, can you consider #6038?

**Comment by guewen** [comment]
Thanks!

**Comment by ZERO20** [comment]
Hi everyone, I know the topic is a bit old but I would like to know how can I exclude sales lines from amounts? I am making an wizard for the user to select the lines to keep and I plan to cancel the ones that I do not select and show them on another page to see the excluded ones, can you help me? use odoo 13 ee

**Pull request closed without merging**
