### PR TITLE
[ADD] base: add Malayalam language

### PR DESCRIPTION
**Pull request by niyasraphy**
**Description of the issue/feature this PR addresses:**
add Malayalam (India)  language to Odoo

**Current behavior before PR:**
Malayalam is not available in Odoo languages

**Desired behavior after PR is merged:**
Malayalam will be available in Odoo

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
hi @mart-e ,
if you have time, can you review this

**Comment by niyasraphy** [comment]
a gentle reminder @d-fence

**Review by VincentSchippefilt — CHANGES_REQUESTED** [review]
this is not a fix, it should be added in master, not in stable.

**Comment by Xavier-Do** [comment]
Sorry I missed this one.
Don't ping d-fence for upgrade exceptions ;) anyway we missed the runbot one. 

> this is not a fix, it should be added in master, not in stable.

As far as I remember adding new languages in stable is not uncommon and since it was asked by @mart-e I would believe that it is not an issue. I guess upgrade team will tell us if I'm wrong

Upgrade exception [#172](https://runbot.odoo.com/web/#id=172&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
xmlid:base.lang_ml
```
cc @KangOl @nseinlet

**Comment by mart-e** [comment]
@niyasraphy just to double check? Are you (or somebody of your team) going to actively translate Odoo in Malayalam? I am ok to add the language here and on Transifex but only if people are going to spend some time to translate it (it does take a considerable amount of work).
If not, we would rather not add them as it may bring wrong expectations to the user activating the new language.

**Comment by niyasraphy** [comment]
hi @mart-e ,
we love to add our language and will translate Odoo to malayalam in transifex.
Thanks

**Comment by Xavier-Do** [comment]
> @mart-e you may want to rebuild or fix this PR as it has failed CI.
You can ignore this message the build was still running

**Pull request closed without merging**
