### PR TITLE
[FIX] membership: infinite recursion in computed fields

### PR DESCRIPTION
**Pull request by sbidoul**
Same as #32349, same as #22568

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Why not just one PR against the lowest version, which is auto forwarded?

**Comment by pedrobaeza** [comment]
@Yenthe666 because we needed for adding the PR in our OCA instance, and for seeing if any gets the change to be merged.

**Comment by tivisse** [comment]
Will be handled at https://github.com/odoo/odoo/pull/22568

Thanks.

**Comment by gurneyalex** [comment]
@tivisse  this was not handled in #22568 can this be reopened please?

**Pull request closed without merging**
