### PR TITLE
[IMP] point_of_sale: add date on in/out cash receipt

### PR DESCRIPTION
**Pull request by caburj**
This is a backport of https://github.com/odoo/odoo/pull/119835.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
@fw-bot up to saas-15.2

**Comment by sdegueldre** [comment]
As discussed in person, while UX improvements can sometimes target the latest stable version, stability expectations for older version than the latest stable are higher and as a matter of internal policy we don't do improvements in stable version that are not the last.

**Comment by janbec** [comment]
@sdegueldre 
I would not consider this to be a UX improvement but meeting general needs and ideas of accounting. Taking money out of a cash register and delivering a receipt without timestamp is bad practice and should be remedied in 15.0 as well. I would kindly ask you to reconsider taking this point into your evaluation. Thanks!

**Comment by sdegueldre** [comment]
This can interfere with existing customizations that xpath on the receipt template or break the layout of existing receipt customizations. It's not appropriate to change this in stable version, if you want this change you can easily add it with a custom module.

**Pull request closed without merging**
