### PR TITLE
[FIX] mrp: avoid blocking MO after post inventory

### PR DESCRIPTION
**Pull request by agr-odoo**
Fine tuning of 074a2c9c9f0415898d099914f023c8f3c320cf8b

The fix was applying to a specific case while we need a generic solution
for a chain of workorder where we don't know how the quantity will be
processed. In a generic case is more effective to consider the workorders
which have not been finished (or canceled) to detect how much quantity
is still left to process
opw-2415073

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@amoyaux 
I'm sorry this needed a refix, could you give a second look on this? Thanks

**Comment by agr-odoo** [comment]
ping @amoyaux

**Comment by amoyaux** [comment]
Ok

**Comment by agr-odoo** [comment]
@jpp-odoo

**Comment by jpp-odoo** [comment]
@robodoo delegate+

**Comment by agr-odoo** [comment]
robodoo r+

**Comment by agr-odoo** [comment]
robodoo r-

**Comment by agr-odoo** [comment]
@amoyaux 
Hello, as https://github.com/odoo/enterprise/blob/25475a6b9b58b4a0fe24c2e6ff0962abfd72247d/mrp_workorder/tests/test_workorder.py#L950
was failing I made a correction and a second test for the specific use case 
https://github.com/odoo/enterprise/pull/16751

Is this still ok?

**Comment by agr-odoo** [comment]
robodoo r+

**Pull request closed without merging**
