### PR TITLE
[ADD] account: when installing a localization, create xml_id for obje…

### PR DESCRIPTION
**Pull request by csnauwaert**
…ct that are created from templates

### CODE REVIEW

**Comment by qdp-odoo** [comment]
you probably should use _update() of ir.model.data in place of the regular creates + your patch.

It seems that for noupdate records it does exactly what we do, even preventing having two records with the same xml_id

**Comment by yvaucher** [comment]
Any plans to have it on 9.0 ?

**Comment by qdp-odoo** [comment]
nope: new feature lands usually on master branch, not on stable ones

**Comment by yvaucher** [comment]
Ok I'll take it in OCB as usual then.

**Pull request merged**
