### PR TITLE
[IMP] core: return defaults in first onchange

### PR DESCRIPTION
**Pull request by rco-odoo**
This fixes the following issue: in a one2many field, a field depends on a field on the parent record. The first call to `onchange()` does not compute the field, as its value has been forced to `False` (because it has no default value) and its dependency is not marked as changed.

We first extend `onchange()` to perform `default_get()` when the changed field parameter is an empty list. So by convention, the client simply calls `onchange()` with almost no value (except the parent field) and no changed field. The server determines defaults, computes the remaining fields, and applies all onchange methods.

This extension of `onchange()` also improves performance, since it costs only one remote call instead of two (and sometimes extra calls to `name_get()`).

### CODE REVIEW

**Comment by kebeclibre** [comment]
@rco-odoo 
alright !, I pushed some commits to fix the fixmes according to our morning's discussion
when you squash, keep the commit messages to ensure good traceability of the changes

**Comment by rco-odoo** [comment]
@robodoo rebase-ff r+

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
As a side note, it could have been interesting to notify teams of that change. We have multiple crash in all apps due to that change, as compute methods are not always taking into account ids. We have to patch a lot of compute on a broken 13.5 ... should have been pre-tested and sent to functional teams beforehand.

**Pull request closed without merging**
