### PR TITLE
[FIX] website_slides: set right text color on sub menu/navbar

### PR DESCRIPTION
**Pull request by nboulif**
Step to reproduce:

  - Install E-learning module
  - Go to any course and set `Display` to `Documentation`
  - Click on `Go to website` and open editor
  - Click on `Theme`, then in `Theme Colors` section, click on the
    palette and select the first custom colors (black-white-gray)

Issue:

  The background of the submenu (just under `Course` tab) is
  transparent (while it should be black, like main menu) and the links
  are not well displayed (white/light text color).
  (Same issue with navbar brand and toggler when reducing screen width)

Cause:

  The background of the submenu is always set to transparent but
  the text color change depending if the top main menu background
  is dark or light.
  Lines that make the issue: https://github.com/odoo/odoo/blob/693092f2c90e36735c6896b6c6e7d795406453e9/addons/website/static/src/scss/website.scss#L240-L252

Solution:

  Set the text color (and the background of the toggler) to
  `light` color if background is dark (determined with
  `color-yiq($body-bg)`), otherwise use `dark` color.

opw-3086750

### CODE REVIEW

**Comment by nboulif** [comment]
ping @odoo/rd-sm

**Comment by nboulif** [comment]
ping @odoo/rd-sm-learn

**Comment by nboulif** [comment]
ping @odoo/rd-sm-learn @odoo/rd-sm :slightly_smiling_face:

**Comment by flch-odoo** [comment]
Hey @nboulif ! Thanks for the PR and sorry for the delay. It seems that the navbar brand and toggler are also not styled properly (seen if we reduce viewports width).

**Comment by nboulif** [comment]
Hello @flch-odoo :slightly_smiling_face: 
I updated the fix like you suggested in MP :wink: 
PS: for the other suggestion (using a string as dynamic variable, e.g `$#{navbar-#{$rightColor}-color}`), it is not possible AFAIK ([more info](https://stackoverflow.com/questions/40005979/sass-scss-interpolate-variable-from-string-name)).

**Review by flch-odoo — APPROVED** [review]
LGTM. Thanks for the fix and patience, @nboulif !

**Comment by kitan191** [comment]
@robodoo delegate+

**Comment by nboulif** [comment]
@flch-odoo Thanks to you! And sorry for back and forth :sweat_smile: 
@robodoo r+

**Pull request closed without merging**
