### PR TITLE
[IMP] Move javascript below the fold

### PR DESCRIPTION
**Pull request by tarteo**
Description of the issue/feature this PR addresses:

When a visitor enters your website the browser will parse the HTML result. Whenever the parser encounters a script, it has to load and execute the script before it can continue parsing. So with render-blocking Javascript (e.g. in the head tag) the time to render the above the fold content increases.
Without render-blocking Javascript (by e.g. loading it below the fold) the page first render occurs faster. This may result in various benefits e.g. lower bounce rate.

https://developers.google.com/speed/docs/insights/BlockingJS
https://en.wikipedia.org/wiki/Above_the_fold

Current behavior before PR:
The javascript is loaded in the head tag of the page.

Desired behavior after PR is merged:
The javascript is loaded at the end of the page.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@tarteo have you signed Odoo CLA?

**Comment by tarteo** [comment]
@pedrobaeza Yes, https://github.com/odoo/odoo/blob/11.0/doc/cla/corporate/onestein.md

**Comment by pedrobaeza** [comment]
But the commit shouldn't be signed with the same e-mail address then. We are talking about the commiter, not the commit author. Can you please check?

**Comment by tarteo** [comment]
I commit with d.sluijk@onestein.nl and the CLA is signed with the same email address.

```
git config --global user.email
d.sluijk@onestein.nl
```

**Comment by pedrobaeza** [comment]
Uhm, strange. @mart-e maybe you can give light to this and tell me how do you check it for me being able to do it next times.

**Comment by mart-e** [comment]
The error is 
> Invalid CLA encoding (must be utf-8)

This is due to https://github.com/odoo/runbot/commit/f5dcb7b371d5c9f8ba44fa17fe3db0d035b41317
If your code base is older than 9cf9938f045d20628fbffc27cd159bdf4a8d256e, you will get an error.

Please rebase your branch and it should be green

**Comment by qsm-odoo** [comment]
One year later, we just merged https://github.com/odoo/odoo/commit/1f5c9e363b6f7cb9a2770e6247536803fd13e3f0 (following https://github.com/odoo/odoo/commit/e9be0bb17842a66445e5cf54fc849c4ac7ca73e5) thanks to which most of the website JS will be **lazy** loaded :tada:

**Comment by JKE-be** [comment]
:postal_horn:

**Pull request closed without merging**
