### PR TITLE
[FIX] l10n_latam_check: existing third party check outgoing payment method.

### PR DESCRIPTION
**Pull request by pablohmontenegro**
**Description of the issue/feature this PR addresses**:
It is necessay not to set "Existing Third Party Checks" outgoing payment method in all argentinean cash journals. It is only needed to be set on "Third Party Checks" and "Rejected Third Party Checks" Argentinean journals that are created when the module is installed or a new argentinean company is created.

**Current behavior before PR**:
"Existing Third Party Checks" outgoing payment method is set in all argentinean cash journals.

**Desired behavior after PR is merged**:
"Existing Third Party Checks" outgoing payment method is set only in "Third Party Checks" and "Rejected Third Party Checks" argentinean journals.

_Ticket Adhoc side_: 83443
_Task Latam side_: 1293

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vbe-odoo** [comment]
@pablohmontenegro thanks for the PR, it LGTM, can you please move the status to "Open", I cannot make that change.
This is ready for technical review.
Thanks!

**Review by antoine162 — APPROVED** [review]
LGTM, thanks so much!
@robodoo r+

**Comment by antoine162** [comment]
@pablohmontenegro I think a rebase is probably needed :smile:

**Comment by antoine162** [comment]
@robodoo r+

**Comment by guva-odoo** [comment]
Hello @pablohmontenegro Do we know if this new behavior is specific to Argentina? If so, Shouldn't this have been done somewhere in l10n_ar?

**Comment by antoine162** [comment]
@pablohmontenegro I think there is an issue where a user mistakenly removed the 'Existing Third Party Checks' payment method from the 'Third Party Checks' journal and wasn't able to add it back. 

So I think we might need to revert this and just leave the 'Existing Third Party Checks' as a selection option.

I wonder what was the reason for this restriction and whether it's needed or whether there are alternatives?

**Comment by vbe-odoo** [comment]
@antoine162 indeed, it seems this is wrong, as even a user can create more than 1 journal to manage Third Party Checks, in that case, they will need to manually add the right payment methods... so if this PR introduced that error, we should revert it, I missed that when tested.

I can check tomorrow with @pablohmontenegro in more detailed.

**Comment by pablohmontenegro** [comment]
@guva-odoo @antoine162 @vbe-odoo thanks for reporting. The goal of this pr was to avoid to include automatically "Existing Third Party Checks" on Outgoing Payment Method on cash journals when a new cash journal is created.

**Pull request closed without merging**
