### PR TITLE
[FIX] l10n_es: Wrong user_type_id for 47... accounts

### PR DESCRIPTION
**Pull request by simongoffin**
opw:696888

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, thanks for the patch. I talked with your colleague yesterday by email that the problem is bigger than this. If you want, we can chat and comment, or if you prefer this way, but it's long... Basically, this template chart doesn't serve, as it's incomplete.

**Comment by simongoffin** [comment]
Hello @pedrobaeza 
Tell me who is the colleague and I will synchronise the informations with him?

**Comment by pedrobaeza** [comment]
It was Martin Geubelle. Anyway, I didn't give him also the full information, inviting the same as to you to explain longer in a later talk/chat.

**Comment by qdp-odoo** [comment]
@simongoffin why is it not closed?

**Pull request closed without merging**
