### PR TITLE
[FIX] hr_recruitment: correct smart button display info

### PR DESCRIPTION
**Pull request by sofiagvaladze**
task - 2695252

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by kbapt — COMMENTED** [review]
LGTM, could you just change the commit message and explain a bit more why you are doing those changes? :innocent: Thanks!

**Comment by kba-odoo** [comment]
@robodoo r+

**Comment by kba-odoo** [comment]
@robodoo r-

**Comment by kba-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
