### PR TITLE
[ADD] l10n_ar: Added a new category of measures with their respective units

### PR DESCRIPTION
**Pull request by mem-adhoc**
Task: 32083

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by zaoral — APPROVED** [review]

**Comment by aliyatastemirova** [comment]
hi, could you please write a more descriptive commit message, e.g. what are these categories and why they are necessary? thanks :pray: 
also, your cla check is failing. Could you please check if everything is correct according to https://github.com/odoo/odoo/blob/master/doc/cla/sign-cla.md

**Comment by aliyatastemirova** [comment]
@mem-adhoc hi, just wanted to ping you again :slightly_smiling_face:

**Comment by zaoral** [comment]
Hi @aliyatastemirova
Hope you are doing well.

This PR was needed because the user want it to send to AFIP invoices with negative lines. AFIP let us to use some unit of measure codes that let us to make this possible only relating the invoice line uon with the defined codes.

We check this with the LATAM Odoo team already and they do not like this approach because they comment that having does generic UoMs could be confusing. We will use a new approach were we are going to deduce if the lines is of type are refering to advances or bonifcation

So this PR will die and we will create a PR with a new approach

Best Regards

**Comment by aliyatastemirova** [comment]
Hi @zaoral thank you for the explanation, I will close this PR then

**Pull request closed without merging**
