### PR TITLE
[FIX][16.0] hr_expense: label convert rate with format currency

### PR DESCRIPTION
**Pull request by ngochung207**
Before commit:
image

After commit:
image

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JulienVR** [comment]
Hello @ngochung207-viindoo,
AFAIK, we don't want to reduce the precision of the conversion rate, sorry.

**Comment by JulienAlardot** [comment]
Hello,
Ca  you explain why the need for the change?
How is that a fix and not an improvement, is there any legal requirement we missed?
Why should we have a different behaviour than the rest of Odoo?

cc @Laura-labe

**Comment by JulienAlardot** [comment]
> Hi @JulienAlardot I think. The information provided is intended to let users know the exchange rate of foreign currency compared to the accounting currency, not to provide information of a certain calculation.
> 
> Let's refer to a bank exchange rate table
> 
> image
> 
> cc: @Laura-labe

Exactly, and you'll see that everywhere in odoo we do use more digits than the currency ones for that matter. As it shows the user a more precise amount.

If we take an extreme case where it does show the other issue.
A lot of people do find it weird to have a currency rate of 1.00₽ = £0.01 for an item costing 100.00₽ translated into 0.87£.
Where 1.00₽ = £0.00871is more helpful without being too much either

Right now I don't see a reason to change that

**Comment by Laura-labe** [comment]
Hello @ngochung207-viindoo. My colleagues explained it well: we wish to keep the precision as it is. In case of high exchange rates, the amount converted might not be in line with the exchange rate displayed. It'll raise unnecessary questions. You say it yourself, this is an information line, so let's give users the accurate information instead of a rounded exchange rate. Thank you for your suggestion anyway.

**Pull request closed without merging**
