### PR TITLE
[IMP] tests: speedup tests by reducing hash rounds

### PR DESCRIPTION
**Pull request by Xavier-Do**
During tests, almost 30 minutes (~15 at install, ~14 post install) are spent to hash password for user creation/authentication.

This is not useful for tests. We can reduce the number of rounds safely in this case.

Before the change, enterprise at install takes ~72 minutes
After the change, enterprise at install takes ~57 minutes
Note: since there is a lot of difference of noise in build times this is only an indication, but it correlates with profiling results.

Other post install build should also be reduced by ~2 minutes in average (40 seconds to 4 minutes) even if it is less visible on the build time.

The hash round is not modified when checking the admin password since it is written in database hashed with 500000 rounds. This commit proposes to remove the check. Another solution may be to update the admin password after install. This represents a few seconds anyway. (16 seconds remaining out of 15 minutes without the last change)

https://runbot102.odoo.com/runbot/static/build/57482701-master/tests/profile/profile_1.html#localProfilePath=1
image

### CODE REVIEW

**Comment by randall-vx** [comment]
@moylop260

**Comment by Xavier-Do** [comment]
> Having profiling info for posterity and stuff would be useful. Especially because
> 
> > Before the change, enterprise at install takes 72 minutes
> > After the change, enterprise at install takes 57 minutes
> 
> seems especially shocking, "at install" should have few to no authenticate call since we should not be able to access the web server. So this would mean we create so many users _with passwords_ (?) during at_install tests it accounts for 15mn of walltime.

Yes I'll add the flamegraph right now.

Actually, it is mainly when we are creating users for tests. We create them with password, being hashed, taking 1 second.

**Comment by Xavier-Do** [comment]
> could we avoid creating passwords at all for users who will never go through an actual web tour flow?

Maybe, but I don't want to check all created users to remove the password, maybe break tests for a strange reason 
The proposed patch is transversal, will still work if a new test creates a user with a pasword, won't need to check all test and maybe break some of them if they try to login using password in a tour, ..... This is just making the creation and check faster.

**Comment by tde-banana-odoo** [comment]
In mail we use the small helper ``mail_new_test_user`` that sets up a default password (and mainly skips sending emails about password reset and stuff like that), and I have to say I don't care about the password itself in tests normally. So that helper could already be simplified (and I try to use it everywhere instead of manually creating users plic ploc).

**Comment by Xavier-Do** [comment]
The first commit is only impacting tests, using one hash round to keep a similar behavior but faster. This will keep assertion checking that the password is hash valid.

The second commit was validated by xmo and fixes a real issue, similar to what is done in totp in some cases when enabling or disabling totp. If the password in saved in database with an unexpected hash rounds and the user goes through check credential, don't log the user out.
This may also solve an issue where the user is logged out after logging in for the first time using a non hashed password.

This change is done in master for testing but may be back-ported to 17.0 or 15.0 after validation

@robodoo r+

**Comment by Xavier-Do** [comment]
@robodoo rebase-ff

**Comment by Xavier-Do** [comment]
@robodoo retry

**Pull request closed without merging**
