### PR TITLE
[FIX] pos_six: Fix the use_strict in the timapi.js library

### PR DESCRIPTION
**Pull request by qle-odoo**
In V16.0 it is currently no longer possible to use the POS if the pos_six module is installed
This bug is a combination of 3 factors

1. the new assets: a single file contains all the JS files, concatenated.

2. one of these files contains the instruction "use strict", which stiffens the code of the function in which this is mentioned, and which prevents certain syntactic approximations (like calling a variable without seeing it declared, this case)

3. We added Sha1, in its file of course, but not in its own function, the use strict then applies to the entire asset file

This reverts commit e08858e5ed02fe74160dabd6a91e1de88640956f.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qle-odoo** [comment]
@rhe-odoo can you test the sha1 with the blackbox ? (V16.0 ?)

**Comment by qle-odoo** [comment]
@kebeclibre r+ ?

**Comment by pimodoo** [comment]
@kebeclibre Is this good for you?

**Comment by qle-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
