### PR TITLE
[UPD] l10n_jp covering new tax rate

### PR DESCRIPTION
**Pull request by yostashiro**
### Description of the issue/feature this PR addresses:

- A new tax rate of 10% which has been in effect since October 2019 is handled.
- Adds a new fiscal position to handle the cases of applying reduced rate.
- A few other fixes (correct assignment of purchase tax account, etc.)

@qrtl

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yostashiro** [comment]
@jco-odoo @nim-odoo @KangOl @lap-odoo 
Can someone please review this PR? Potential users would be discouraged to try Odoo once they see that the new tax rate has yet to be available. ;)

**Comment by jco-odoo** [comment]
@yostashiro I just took a quick look and I see extra tags are created.  There is a tax report in enterprise that uses these.  Are you sure we need extra tags for the report?  (are there lines in the tax report where the new tax needs to be reported differently than their normal counterparts?)

**Comment by yostashiro** [comment]
> Are you sure we need extra tags for the report? (are there lines in the tax report where the new tax needs to be reported differently than their normal counterparts?)

@jco-odoo I'd say yes mainly to be on the safe side, although it also depends on how Odoo defines the coverage of the report. I am not an accountant or a tax lawyer, but I can imagine that they would like to see the breakdown (personally, I am OK either way). The reality in Japan is that there are very few users that seriously use Odoo Accounting at the moment, so it's a bit hard for me to collect input from our customers or the community.

**Comment by jco-odoo** [comment]
@yostashiro  Then we can just check what is legally required.  There is no vat return to report to the government?

**Comment by yostashiro** [comment]
@jco-odoo Yes, the VAT returns need to be reported per tax rate. Here is one of the forms that need to be filled in for your reference. https://www.nta.go.jp/taxes/tetsuzuki/shinsei/shinkoku/shohi/pdf/02.pdf

**Comment by yostashiro** [comment]
@jco-odoo What can I expect on this PR? Anything you'd like me to follow up on?

**Comment by jco-odoo** [comment]
@yostashiro I am afraid I blocked on the fact that merging this, with a new installation, people will not see the results of the 10% tax in the tax report.  This report is defined in enterprise, so I suppose we should just add one line with the tags for the 10%?  And then later, we could check for master if it needs improvement.

**Comment by yostashiro** [comment]
> I suppose we should just add one line with the tags for the 10%?

@jco-odoo Not sure what exactly you mean here. Do you mean that we should rename the existing tags (remove "8%") and use them for both 8% and 10% taxes? I am OK with it if that makes it easier for you. But I'm almost certain that we need to work on the accounting reports anyway, splitting the tags, in the future if Odoo accounting is to penetrate into the market. ;)

**Comment by jco-odoo** [comment]
@yostashiro What I am saying is what you say: that we should update the tax report with an extra line.  (you said it is reported differently)

**Comment by yostashiro** [comment]
@jco-odoo I see.  Yes, it will be good adjust the tax report. Could we process this PR first anyway? I suppose partial solution is better than no solution in this case. I will try and create another PR for the tax report later if you'd like me to.

**Comment by yostashiro** [comment]
@jco-odoo Sorry to nag you but what are the plans for this PR now?

**Comment by jco-odoo** [comment]
@yostashiro Sorry for it to keep stalling.  We just want to be consistent with the tax report.  Maybe we need to just add a line for 10% or add it to the existing line.  Anyways, I will let you know more on Monday.

**Comment by AdrienHorgnies** [comment]
@jco-odoo Four lines from account_financial_report_l10n_jp are currently querying the old 8% tags. Do you think I must add a 10% equivalent line or should I replace them altogether ?

**Comment by AdrienHorgnies** [comment]
@yostashiro Hi.
I've made some changes to your branch. What do you think of them ?

**Comment by yostashiro** [comment]
@AdrienHorgnies I thought @jco-odoo and I agreed that we'd add lines to account_financial_report_l10n_jp instead of having both 8% and 10% taxes point to the same tag. Can you please once again go through above communication and let me know the reason if you need to change the course of action?

**Comment by jco-odoo** [comment]
@yostashiro I think it would have been much simpler, because mostly countries just make the distinction between full and reduced rate and that way they could refer to the same line  but I see it is not that easy.  The thing is that here, the 8% becomes the reduced rate so we should stick the initial plan and add a line in the tax report for 10% as I don't see a reference there to full/reduced rate either.  And as their is no mentioning of full/reduced rate (I guess), we can just keep talking about 8% and 10%.  

Also the current tax report does not look like the pdf you sent, because it is showing the full tax and not the separation between consumption tax and local consumption tax (https://www.avalara.com/vatlive/en/vat-news/japan-raises-consumption-tax-to-10--1st-oct-2019.html)

So, we just probably need to add a line to the current tax report with 10% and that should solve it related to the tag of 10%.

**Comment by AdrienHorgnies** [comment]
@jco-odoo Ok, I removed my commit from @yostashiro branch and I've added the line relative to the 10% tax on the tax report (see https://github.com/odoo/enterprise/pull/7474).

**Comment by jco-odoo** [comment]
@fw-bot up to 12.0

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by yostashiro** [comment]
Thank you for processing this PR, everyone. :D

**Pull request closed without merging**
