### PR TITLE
[IMP] reduce web.webclient_bootstrap template size

### PR DESCRIPTION
**Pull request by pparidans**
This PR modifies the `web.webclient_bootstrap` template in two ways:
- removes conditional comments targetting old IE versions
- rewrite odoo.reloadMenus implementation to take advantage of modern JS syntax.

### CODE REVIEW

**Comment by pparidans** [comment]
@VincentSchippefilt @adr-odoo Thanks for the reviews, guys!
One of you could `r+` this?

**Comment by adr-odoo** [comment]
@robodoo r+

**Comment by pparidans** [comment]
@robodoo rebase-ff

**Comment by adr-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
