### PR TITLE
Modify PO file to match new commit

### PR DESCRIPTION
**Pull request by Ark74**
Fix the po files to match the commit that handles the real problem, should this be for all languages?
https://github.com/odoo/odoo/commit/13010ed992ce370a33d14a4d1caedc6618769537

Description of the issue/feature this PR addresses:
Time zone is not the user's one, it displays wrong on the email template.

Current behavior before PR:
RFQ shows wrong time on user's time zone. It uses UTC.

Desired behavior after PR is merged:
Template date will be fixed by this correction.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thanks for the contribution but please check [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://transifex.com), not Github.

Please submit your changes there and let me know if you have issues.

Thanks

**Comment by Ark74** [comment]
This is the issue, the translation is not up to date to the file it is translating.
Please check [this file](https://github.com/odoo/odoo/blob/8.0/addons/purchase/edi/purchase_order_action_data.xml#L40) and you'll see that is not updated to the string to update on [Transifex](https://www.transifex.com/odoo/odoo-8/translate/#es_MX/$/49579408?q=object.date_order).

Am i wrong? or the po files are not up to date with the code?

I'm looking fo the trigger of bad timezone on mail reports which [this PR](https://github.com/odoo/odoo/commit/13010ed992ce370a33d14a4d1caedc6618769537) fixed but i'm still getting this behaviour so i looked at po files. Thanks for your attention.

**Comment by mart-e** [comment]
Thank you for the update. The correct fix, should be to update the .pot file then. If you change the .po file, your changes will be lost at the next automatic update.
Done at 73b320a3f7aa3bc0eeca7b74c5cbc60216702596

**Comment by Ark74** [comment]
Im affraid it hits RFQ, Invoice, and others.
On [transifex it seems](https://www.actualized.org/insights) to be 5 trings with the same issue.
Cheers.

**Comment by mart-e** [comment]
@Ark74 I have fixed the one you have reported but if you have found other issues in .pot, do not hesitate to submit a PR fixing them.
Thanks

**Pull request closed without merging**
