### PR TITLE
Convert jinja template into qweb

### PR DESCRIPTION
**Pull request by rop-odoo**
Task: https://www.odoo.com/web?#id=27033&view_type=form&model=project.task&action=327&menu_id=4720
Pad: https://pad.odoo.com/p/r.8d2749de4844861078fc36312e573e48
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jholze** [comment]
Just a question. Is the qweb migration of email templates done already in another RP or still mako templates in v11 ?

**Comment by phuongtai** [comment]
Hi all, Can anybody merge it? I think this conversion is necessary

**Comment by tde-banana-odoo** [comment]
It will not be merged as we will keep supporting jinja in templates.

**Comment by tde-banana-odoo** [comment]
Outdated.

**Pull request closed without merging**
