### PR TITLE
[ADD] import your vendor bills from XMLs files

### PR DESCRIPTION
**Pull request by smetl**
https://www.odoo.com/web#id=1823110&view_type=form&model=project.task&action=333&active_id=967&menu_id=4720

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@alexis-via you would be interested in this

**Comment by pedrobaeza** [comment]
UBL is a standard not only for Belgium AFAIK

**Comment by smetl** [comment]
@pedrobaeza UBL has a lot of subsets and customizations for different countries. E.g. in Belgium, this customization is E-FFF.

**Comment by pedrobaeza** [comment]
But isn't better to have the common standard in a module and only includes in l10n_be_* the subset? This way, when adding for example compatibility for UBL in France, you don't need to repeat code. 

You can also check current OCA modules that we have for UBL compatibility (migration to v11 in progress, but similar to this v10 version):

https://github.com/OCA/edi/tree/10.0/base_ubl
https://github.com/OCA/edi/tree/10.0/account_invoice_import_ubl

**Comment by alexis-via** [comment]
@smetl e-fff is just standard UBL 2.0 with a list of required fields. Country-specific stuff in UBL standard are pretty minor and are usually about:
- country-specific identification numbers of companies
- which fields are required, which fields are optional
- exact nomenclature used for taxes (but, at least in EU, taxes are almost only VAT taxes and we can use the rate to find the corresponding taxes instead of the nomenclature)
- the exact version of UBL used (2.0 for e-fff, but it's the same as 2.1 for the usual fields of an invoice)

That's why, in the OCA, 99% of the code for UBL is generic and only 1% is country-specific.

**Comment by smetl** [comment]
@alexis-via I know, I know. At this moment, this stuff is only used in l10n_be but don't worry, the UBL standard will be in a dedicated module when it will be necessary.

**Comment by pedrobaeza** [comment]
@smetl I think it's better to do it the best way from the beginning and avoid headaches later to the migration teams. This also will favor extensible community modules that don't depend on l10n_be* modules and with ugly patches. Can you please consider this?

**Comment by jco-odoo** [comment]
@pedrobaeza @alexis-via I am trying to check the electronic invoicing standards more closely and I wonder if it would not be better to use the PEPPOL standard (based on UBL) instead of UBL, at least for the countries (Belgium, Norway, the Netherlands, France, Denmark, ...) that support it.  

PEPPOL also has an eDelivery network however based on AS2 and if you have any ideas about that, it would be nice to know about it.  It is a little more complicated of course than sending a mail with a pdf+xml as with Factur-X, but that way you know it has been received correctly as well.  (to the government e.g.)

**Comment by pedrobaeza** [comment]
Let me research about this format and tell you back.

**Comment by alexis-via** [comment]
@jco-odoo PEPPOL is a great initiative to have both an e-invoicing standard and an interoperable transmission protocol. PEPPOL uses UBL with it's own CIUS (Core Invoice Usage Specification). Respecting the PEPPOL CIUS is certainly a good thing to do, because these are field-proven CIUS that have a large adoption.
PEPPOL was initially designed as a transmission protocol for B2G (business to governments) but it's now adopted for B2B in some countries. I heard that it's adopted as the interoperability channel for private invoicing operators: instead of setting up private P2P communication channels between invoicing operators, they all connect to PEPPOL and it allows them to exchange invoices directly in a standard and interoperable way.
Currently, PEPPOL has a wide-spread adoption in Norway (B2G and B2B), a small adoption in some countries of northern Europe, and no adoption at all for the moment in France and other countries of southern Europe. That's why I haven't worked on PEPPOL CIUS myself so far, but it is on my roadmap for the OCA/edi stack.

But, what we really need from Odoo in the short term, is a better Factur-X implementation. I'm not talking about the PDF part ; I know that PDF/A-3 is not an easy topic. I'm talking about the XML part: your implementation still lacks the nomenclature. Odoo must implement the nomenclature for unit of measures, taxes and payment methods. Otherwise, the XML file embedded in the PDF will not be complete/valid. The good news is that this nomenclature is common for UBL and CII/Factur-X.

FYI, the OCA implementation for the nomenclature is available in https://github.com/OCA/community-data-files:
- for unit of measures, it is the module "product_uom_unece"
- for taxes, it is the module "account_tax_unece"
- for payment methods, it is the module "account_payment_unece"
These modules are already available for v12 (or have a PR waiting approval).
When you will implement the nomenclature for taxes, it will allow localization to add the nomenclature on the tax templates they provide and will avoid maintaining OCA modules to add nomenclature on taxes (see for example the module l10n_fr_account_tax_unece (https://github.com/OCA/l10n-france/pull/175).

So my advice is: adopting PEEPOL CIUS is great, settings up PEPPOL gateways would be great too, but let's start to fix what is currently broken in the Odoo e-invoicing stack: the XML of your Factur-X invoices that lack the nomenclature.

**Comment by pedrobaeza** [comment]
I don't have anything more to add apart from what Alexis has said, which is the great expert here. Josse, tell us if you want us to make any PR adding these UNECE related stuff.

**Comment by jco-odoo** [comment]
Thanks a lot for your explanation @alexis-via .  The reason unece was not done before in Factur-X, is that the fields themselves are not required and put a lot of extra fields/clutter in the code.  We have branches somewhere where it was added too, but were never merged.  

For the UoMs it would be quite straightforward, but for the taxes and the payment methods it seems a lot more complicated.  For the taxes it would also mean letting depend localizations on a unece/factur-x module so we can set the fields in the tax templates, so there is quite some localizations to adapt then?  And do we need code.list or can we just use selection fields?  

Would it improve for the import of invoices, because in practice most accountants probably still verify it.  Or are you sending factur-X to the government somehow where you get a bad response?

**Comment by alexis-via** [comment]
@jco-odoo About UNECE data on UoM, taxes and payment methods:
1) if you want to generate a Factur-X invoice profile EN 16931 that really comply with EN 16931, these data MUST be provided. If you test the factur-x.xml file generated by Odoo v12 against the official CII schematron of EN 16931 that is available here https://github.com/CenPC434/validation/tree/master/cii you will see that the XML part of Odoo invoice is not compliant for that reason. If you don't want to loose time to install the Java tools for schematron, you can use this Factur-X validator https://services.fnfe-mpe.org/ which uses the schematron to test the XML part.
2) if you add the UNECE fields on taxes, it will *allow* localisations to provide this data on taxes, but it won't oblige localisations to depend on the module account_facturx and it won't oblige localisations to provide the UNECE data on taxes ! And, in the code of the module account_facturx, you can make sure that if these fields stay empty, you would not raise an error but just not set the corresponding XML tag. That way, Odoo users that set the right value for UNECE fields on their taxes (manually or via the localisation) would generate compliant Factur-X invoices ; those who don't set UNECE data on they taxes would generate not-compliant Factur-X invoices, just like in Odoo v12. For me, there is no problem here.
3) Adding the UNECE field on payment.method is easy : no impact on localisations, only 1 new field to set on module that add a payment method (and this field can stay optional).

**Comment by jco-odoo** [comment]
@alexis-via But about the taxes, what is the reason for the type and category to use Many2one instead of selection fields? 

Do you have these only for the French localizations or others as well?  Is it difficult to determine them?

**Comment by jco-odoo** [comment]
@qdp-odoo We should not merge this, but think about a more generic concept instead as there is now a CIUS which allows one core specification for a lot of European countries which gets adaptations by country.

**Comment by qdp-odoo** [comment]
@william-andre the commit message needs to be changed

**Comment by qdp-odoo** [comment]
needs to rebase + remove xsd download and test in decode_ubl (more appropriate to xml creation. Here we'll just assume E-invoice are correctly formatted)

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@william-andre test failed in staging (but passed on the PR). A rebase might be necessary

@robodoo retry maybe

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
