### PR TITLE
[FIX] website_sale: fix add to cart that duplicate line

### PR DESCRIPTION
**Pull request by JKE-be**
Before this commit add several time the same product will duplicate
the sale order line instead to update the quantity.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by awa-odoo** [comment]
Hello @JKE-be 

Looking twice at this I think this line:
https://github.com/odoo/odoo/blob/saas-12.3/addons/website_sale_product_configurator/models/sale_order.py#L13

Should also be `if line_id` instead. Would be nice to include the change in this PR since it concerns the same method.

Also, shouldn't this PR be targeting saas-12.3 ?

Thanks for the fix.

**Comment by rdeodoo** [comment]
What about this one? Still bugged in saas-12.3 and +

**Comment by tde-banana-odoo** [comment]
You are déterring forgotten stuff ?

**Comment by JKE-be** [comment]
this fix is wrong...

But still need to be fixed.

Open internal task

**Comment by JKE-be** [comment]
@tde-banana-odoo 

Yes, we are cleaning open PR concerning website. Seems legit no ?
It was part of the cleaning you asked in one of your last email.

**Comment by tde-banana-odoo** [comment]
Everything is legit when it is done with love.

**Comment by JKE-be** [comment]
We always works in love in website ;) :kiss: :kissing:

**Pull request closed without merging**
