### PR TITLE
[IMP] odoo_referral_portal: remove unneded addon

### PR DESCRIPTION
**Pull request by yajo**
This garbage adds no value and blocks some deployments. See https://github.com/Tecnativa/doodba/issues/485.

@moduon MT-295

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@mart-e, a trivial one

**Review by tfr-odoo — APPROVED** [review]
Thx, indeed it seems a mistake from this commit https://github.com/moduon/odoo/commit/dda0bb499b0964b3a1750431255ecfef6cc9eb46, the file should have been removed

**Comment by tfr-odoo** [comment]
@Yajo You probably need to rebase to pass the upgrade_enterprise ci

**Comment by Yajo** [comment]
OK, rebased.

**Comment by MiquelRForgeFlow** [comment]
@tfr-odoo could somebody r+?

**Comment by tfr-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
