### PR TITLE
Master spread pro

### PR DESCRIPTION
**Pull request by pro-odoo**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Comment by VincentSchippefilt** [comment]
robodoo rebase-ff

**Comment by VincentSchippefilt** [comment]
robodoo delegate=pro-odoo

**Comment by pro-odoo** [comment]
robotoo r+

**Comment by pro-odoo** [comment]
robodoo r+

**Pull request closed without merging**
