### PR TITLE
[FIX] mrp, mrp_workorder_hr: close the correct time tracking

### PR DESCRIPTION
**Pull request by thle-odoo**
Steps to reproduce:
-------------------
- create a workorder that accepts employees;
- with a session for a user X, go to the "tablet view" and use employee A;
- with an other session for a user X, go to the "tablet view" and use employee B;
- leave employee A's tablet view.

Issue:
------
Employee B's time tracking is stopped instead of employee A's.

Cause:
------
The domain for selecting the `mrp.workcenter.productivity` record does not take into account the employee, only the user.

We will therefore update the tracking time for the first record found, i.e. the last record inserted in the database.

Solution:
---------
Override the domain which selects the record to be updated in the `mrp_workorder_hr` module, so that a condition can be added to take account of the employee.

opw-3641703

### CODE REVIEW

**Comment by thle-odoo** [comment]
Enterprise PR: https://github.com/odoo/enterprise/pull/54301

**Review by DjamelTouati — APPROVED** [review]
Hello,

Looks good to me! Thank you for your fix.

**Comment by amoyaux** [comment]
robodoo r+

**Comment by DjamelTouati** [comment]
@fw-bot up to saas-16.3

**Comment by mschulz-asphericon** [comment]
@thle-odoo I found this PR to be cause of an error that raises when trying to cancel an MO (state draft was sufficient) which contains more than 2 workorders at disjoint workcenters. 

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/models.py", line 5174, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 1864, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/enterprise/quality_mrp/models/mrp_production.py", line 76, in action_cancel
    res = super(MrpProduction, self).action_cancel()
  File "/data/build/odoo/addons/mrp/models/mrp_production.py", line 1507, in action_cancel
    self._action_cancel()
  File "/data/build/odoo/addons/mrp/models/mrp_production.py", line 1527, in _action_cancel
    self.workorder_ids.filtered(lambda x: x.state not in ['done', 'cancel']).action_cancel()
  File "/data/build/enterprise/mrp_workorder/models/mrp_workorder.py", line 143, in action_cancel
    return super(MrpProductionWorkcenterLine, self).action_cancel()
  File "/data/build/odoo/addons/mrp_account/models/mrp_workorder.py", line 26, in action_cancel
    return super().action_cancel()
  File "/data/build/odoo/addons/mrp/models/mrp_workorder.py", line 717, in action_cancel
    self.end_all()
  File "/data/build/odoo/addons/mrp/models/mrp_workorder.py", line 704, in end_all
    return self.end_previous(doall=True)
  File "/data/build/odoo/addons/mrp/models/mrp_workorder.py", line 698, in end_previous
    self._domain_mrp_workcenter_productivity(doall),
  File "/data/build/enterprise/mrp_workorder_hr/models/mrp_workorder.py", line 101, in _domain_mrp_workcenter_productivity
    if not self.workcenter_id.allow_employee or not self.employee_id:
  File "/data/build/odoo/odoo/fields.py", line 1154, in __get__
    record.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5177, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: mrp.workcenter(1, 2)

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://58677547-16-0-all.runbot175.odoo.com/web/assets/2543-5749aae/web.assets_backend.min.js:995:274
    makeErrorFromResponse@https://58677547-16-0-all.runbot175.odoo.com/web/assets/2543-5749aae/web.assets_backend.min.js:999:163
    jsonrpc/promise</<@https://58677547-16-0-all.runbot175.odoo.com/web/assets/2543-5749aae/web.assets_backend.min.js:1007:34
```

**Comment by clesgow** [comment]
@mschulz-asphericon Fixed in odoo/enterprise#57321

**Pull request closed without merging**
