### PR TITLE
[FIX] l10n_be: Fix the cash difference expense account used.

### PR DESCRIPTION
**Pull request by assellalou**
This fix is to solve a bug that appears in the demo data of the l10n_be specifically in the cash journal using an income type account for the negative cash difference which should be an expense type. 
current behavior: using income type in a loss account.
desired behavior: expense account instead.
opw-3642586

### CODE REVIEW

**Review by dylankiss — APPROVED** [review]
Looking good from my part, since the accounts will be used for both bank and cash journals to record payment differences.

@tsb-odoo These are the codes and names I suggested, but let me know if you disagree.

**Comment by aliyatastemirova** [comment]
hi, thanks for the fix :slightly_smiling_face: most probably a dumb question - can't we just keep the default cash difference gain & loss accounts created in chart_template.py for this?

**Comment by dylankiss** [comment]
> can't we just keep the default cash difference gain & loss accounts created in chart_template.py for this?

@aliyatastemirova We can't in Belgium, since accounts starting with 9 are not official and are also not included in any reports. Expense accounts must start with a 6 and income accounts with a 7.

**Comment by aliyatastemirova** [comment]
@dylankiss thanks for the clarification :slightly_smiling_face:

**Review by aliyatastemirova — APPROVED** [review]

**Comment by dylankiss** [comment]
> Is it ok for @tsb-odoo ?

@jbw-odoo No idea, I haven't got any feedback yet. I checked with Brice though for the right prefix.

**Pull request closed without merging**
