### PR TITLE
[IMP] l10n_in_edi_ewaybill: Use same end point for all Indian IAP

### PR DESCRIPTION
**Pull request by jva-odoo**
no need to setup a new end point

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jva-odoo** [comment]
@jco-odoo why forward port PR is not created?

**Comment by jco-odoo** [comment]
@jva-odoo 16.1 freeze...

**Comment by jva-odoo** [comment]
okay

**Pull request closed without merging**
