### PR TITLE
[FIX] l10n_it_edi: auto-fattura coming from foreign vendors should be…

### PR DESCRIPTION
**Pull request by jco-odoo**
… imported as vendor bill

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by dbkosky — COMMENTED** [review]
Looks good to me, tested locally and the tests are passing.
This does make me wonder though if the tests don't cover this case since nothing was failing before this change, and nothing is failing after...

**Comment by lordkrandel** [comment]
LGTM

**Review by vin-odoo — APPROVED** [review]
Maybe a test could be added here to be safe but otherwise, ok for me too :)

**Comment by jco-odoo** [comment]
@qdp-odoo @vin-odoo Could this one still be merged?  The customer seems to say it is really sent from the vendor and so, it makes a lot more sense to import it as vendor bill.

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
