### PR TITLE
[ADD] l10n_dz: add Algerian localization

### PR DESCRIPTION
**Pull request by qsb-odoo**
Task: https://www.odoo.com/web#id=1918677&model=project.task&view_type=form&cids=2&menu_id=

### CODE REVIEW

**Comment by jco-odoo** [comment]
@qsb-odoo Can you remove the reference to osis-dz.com as the site does not work?

**Comment by jco-odoo** [comment]
@qsb-odoo Can you also remove the email @osis.dz and ping me when it is done, so we can merge?

**Comment by qsb-odoo** [comment]
> @qsb-odoo Can you also remove the email @osis.dz and ping me when it is done, so we can merge?

@jco-odoo Email removed.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@mart-e , Do you know if we can ask @ouassila ?

**Comment by jco-odoo** [comment]
@qsb-odoo Can you change author in the commit to you?

**Comment by jco-odoo** [comment]
@qsb-odoo I will do it

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
