### PR TITLE
[FIX] account: can't get previous move

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
In case of a user have no access to all account.move (restrict by ir.rules). An exception can raise during move posting.

Add an index to speed up this function in large database.

@oco-odoo @smetl 

- Create User A
- Create User B
- Create ir.rules, user A have only access of account.move with sale TEAM A
- User B create an invoice with TEAM B
- User A create an invoice with TEAM A
--> User A cannot post

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
#3159258

**Review by vin-odoo — CHANGES_REQUESTED** [review]
There is a typo in the commit message title. Also please add the ticket number to the commit message

**Comment by fmdl** [comment]
@vin-odoo the changes have been made.

**Review by vin-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
