### PR TITLE
[FIX] base: fix typo

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Yenthe666 — APPROVED** [review]

**Comment by sswapnesh** [comment]
Ping @odony

**Comment by Yenthe666** [comment]
Really not worth bothering people like Olivier for who are extremely busy honestly.

**Comment by sswapnesh** [comment]
Pinged him as he was the Author

**Comment by lathama** [comment]
@sswapnesh knowing that 14 is no longer updated, is this PR needed?

**Pull request closed without merging**
