### PR TITLE
[FIX] stock: consider internal origin moves reservation for forecast

### PR DESCRIPTION
**Pull request by naja628**
Problem
---
When computing the forecast availability for a move we have a mechanism that tries to match incoming moves with outgoing moves. But this mechanism ignores internal transfers. So moves which are chained after an internal transfers will not take this into account for the forecast.

Use Case
---
* Install mrp
* Enable *2 Step Manufacturing* for the current warehouse 
  (General setting > *Multi Step Routes* > *Set Warehouse Route*)
* Create a storable product P that uses a storable component C in its bom (1:1)
* Adjust inventory so we have 10 C on hand
* Create 2 different MO for 10 P 
  * (=> on the list view the first MO has its components available, but not the second one)
* Unreserve the first `Stock -> Pre-Production` transfer (for MO1)
* Reserve the second 
  * (=> nothing changes; ie the forecast still gives priority to the first MO)

Fix
---
Look at the reservation state of internal transfers into the specific relevant sub-location for outgoing unreserved moves.

Note
---
With this solution we will only ever see one chained move deep, and will have the same problem if we chain more moves

opw-3912442

### CODE REVIEW

**Comment by naja628** [comment]
@robodoo up to 16.0

**Comment by naja628** [comment]
For now choosing to look only one move deep, too avoid introducing complexity and hurting performance.
But we could consider something like this (untested):
```diff
-            ins_per_product[in_.product_id.id].append({
-                'qty': in_.product_qty if in_.location_id not in wh_location.child_ids else in_.reserved_availability,
-                'move_date': in_.date,
-                'move_dests': in_._rollup_move_dests(set())
-            })
+            ins_per_product[in_.product_id.id].append({
+                'move_date': in_.date,
+                'move_dests': in_._rollup_move_dests(set())
+            })
+            if in_.location_id in wh_location:
+                ins_per_product[in_.product_id.id]['qty'] = in_.product_qty
+            elif in_.reserved_availability:
+                ins_per_product[in_.product_id.id]['qty'] = in_.reserved_availability
+            else:
+                narrow_in = in_.with_context(narrow_forecast_location=in_.location_id)
+                ins_per_product[in_.product_id.id].update({
+                    'qty': in_.forecast_availability,
+                    'move_date': in_.forecast_expected_date,
+                })
```

**Comment by ethanrobv** [comment]
I think it makes sense but honestly I could go either way. I think it is definitely a little weird to have both MOs `components_availability == 'Not Available'` when, in fact, there is some on-hand quantity that is available (even if not explicitly reserved). Let's see what logistics says about it.

**Comment by ethanrobv** [comment]
Closing as a wontfix in v16 (system overhauled in 17+)

**Pull request closed without merging**
