### PR TITLE
[FIX] portal: add jSignatureCustom.js file to common assets

### PR DESCRIPTION
**Pull request by dep-odoo**
Issue: https://www.odoo.com/web#id=770513&view_type=form&model=project.issue&action=963&active_id=681&menu_id=4720

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Done at https://github.com/odoo/odoo/commit/e9542e4d24d72170b32a01c8cfa381467fd3caa1 . Thanks !

**Comment by ged-odoo** [comment]
@tde-banana-odoo I think that jSignatureCustom.js should have been lazy loaded.  This is the kind of libs we only use once in a while, and we should try to have a smaller set of bundles

**Comment by tde-banana-odoo** [comment]
Reads like a good idea, indeed. How does that work ?

**Comment by ged-odoo** [comment]
For each widget that need to use a library, you need to declare its dependencies, like this:

https://github.com/odoo/odoo/blob/master/addons/web_editor/static/src/js/widgets/ace.js#L115

And in the willStart method, you need to call loadJS to make sure these files are loaded, like here:

https://github.com/odoo/odoo/blob/master/addons/web_editor/static/src/js/widgets/ace.js#L180

This way, the file will be fetched (exactly once) when the widget is first rendered, and will be fetched before the start method.

**Comment by ged-odoo** [comment]
note that you can also lazyload css (some libraries have css with them).

**Pull request closed without merging**
