### PR TITLE
[FIX] *: Fixes coming from the new read_group refactor

### PR DESCRIPTION
**Pull request by ryv-odoo**
## [FIX] core: fix `name_get` call on duplicate records

The new `_read_group_format_result` could call `name_get` with duplicate
records because the ids are not uniquify. (Coming from https://github.com/odoo/odoo/commit/81a892ac8c4d8f313e4255bc2aedeafc0de4b81b)

Fix it to avoid breaking some `name_get` implementation (example: https://github.com/odoo/odoo/commit/a8e26df3433933f467312dca20d73ba1b5ddcb77)

Co-authored-by: Thomas Lefebvre <thle@odoo.com>

## [FIX] *: fix usages of `_read_group` with NewId

In https://github.com/odoo/odoo/pull/110737, I didn't consider that
compute could be called on NewId record with `_origin`. Some compute
methods are badly refactored with the new signature of `_read_group`.
We use recordsets returning from `_read_group` to assign field value to
`self`. But if `self` contains `NewId` with `origin`, these records
don't represent `self`, it contains real record instead of the one with
NewId + origin. Then the assignations are done on records not in `self`
which may lead to generate traceback or write to other records during
an onchange.

Fix multiple compute to work correctly with NewId (origin set) record.

### CODE REVIEW

**Review by rco-odoo — COMMENTED** [review]
I miss a test for the issue with `name_get()`.

**Comment by Julien00859** [comment]
> @[ryv-odoo](https://github.com/ryv-odoo) ryv-odoo [force-pushed](https://github.com/odoo/odoo/compare/d668e0eef81a02cfba7c2268a74342c4ebc82e9f..5630b6cb35e8548ebb8245bca3033aa127fccab3) the saas-16.3-read-group-fixes-origin-ryv branch from [d668e0e ](https://github.com/odoo/odoo/commit/d668e0eef81a02cfba7c2268a74342c4ebc82e9f)to [5630b6c ](https://github.com/odoo/odoo/commit/5630b6cb35e8548ebb8245bca3033aa127fccab3)
[now](https://github.com/odoo/odoo/pull/130731#event-10109450798)

ce genre de problème est le genre de problème qui me fait dire que notre ORM n'est pas facile

@robodoo r+

**Comment by rco-odoo** [comment]
@robodoo ff

**Comment by rco-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
