### PR TITLE
[FIX] stock: BOM unit in MO roundoff to 2 decimal places

### PR DESCRIPTION
**Pull request by mamatch**
Steps to reproduce the bug:
* Go to Technical > Decimal Accuracy > Set the product unit quantity to 7
* Go to any UOM and set the precision to 7 decimal places
* It turns to 5 decimal places (Why this behavior? Is this a limitation?)
* Set the accuracy as 5 0.00001
* Go to any product, set the quantity as 1.79864 it auto sets to 1.80

Solution:
The number of digits for float fields in xml are by default 2, just increase it
to 10 have more precision.

opw-2942825

### CODE REVIEW

**Review by adwid — COMMENTED** [review]
For the limit on the UoM rounding, I would say that this is not an error but a simple limitation. I guess 5 digits is enough. Also, except if I miss something, there is an easy workaround: the user can create a new UoM smaller than the one he tries to modify, like mL with rounding 0.001 instead of L with rounding 0.000001)

About the issue on the quants, I agree this should be fixed. However, I think you should rather do something like
```diff
diff --git a/addons/stock/models/stock_quant.py b/addons/stock/models/stock_quant.py
index 968c6875673..ccb7e45b604 100644
--- a/addons/stock/models/stock_quant.py
+++ b/addons/stock/models/stock_quant.py
@@ -82,16 +82,18 @@ class StockQuant(models.Model):
         readonly=True)
     inventory_quantity = fields.Float(
         'Inventoried Quantity', compute='_compute_inventory_quantity',
-        inverse='_set_inventory_quantity', groups='stock.group_stock_manager')
+        inverse='_set_inventory_quantity', groups='stock.group_stock_manager',
+        digits='Product Unit of Measure')
     reserved_quantity = fields.Float(
         'Reserved Quantity',
         default=0.0,
         help='Quantity of reserved products in this quant, in the default unit of measure of the product',
-        readonly=True, required=True)
+        readonly=True, required=True, digits='Product Unit of Measure',)
     available_quantity = fields.Float(
         'Available Quantity',
         help="On hand quantity which hasn't been reserved on a transfer, in the default unit of measure of the product",
-        compute='_compute_available_quantity')
+        compute='_compute_available_quantity', digits='Product Unit of Measure',)
     in_date = fields.Datetime('Incoming Date', readonly=True)
     tracking = fields.Selection(related='product_id.tracking', readonly=True)
     on_hand = fields.Boolean('On Hand', store=False, search='_search_on_hand')
```

**Comment by svs-odoo** [comment]
LGTM except the commit's message:
- The title doesn't reflect what the fix does (stock quant quantities instead of MO/BoM)
- I think you can remove the part about 7 decimals / the limitation of 5 decimals
- `For the 'On Hand Quantity' and the 'Available Quantity', extends the number of
digits to the rounding of the 'Product of Measure'` > `Uses the rounding of the 'Product Unit of Measure' for the quant quantity fields`

**Comment by amoyaux** [comment]
It's not a good idea to add digits in stable. Because it will create inconsistencies in the database. Some records will be rounded while others are not.

**Comment by mamatch** [comment]
Hi @amoyaux , I've looked for other ways to resolve the problem another without finding, Will I consider it to be a limitation ?

**Comment by mamatch** [comment]
@robodoo close

**Pull request closed without merging**
