### PR TITLE
[IMP] website_mass_mailing: add `s_newsletter_centered` snippet

### PR DESCRIPTION
**Pull request by mano-odoo**
This commit adds the `s_newsletter_centered` snippet

task-4306853
Part of task-4077427

Requires:
- https://github.com/odoo/odoo/pull/186281

---

image

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lebl-odoo** [comment]
Hi @mano-odoo ,

Just a quick suggestion, what about using the mail icon in the heading to ease the transformation for users? Since they will be able to double-click to change it. What do you think?
image

I see you remove SMS subscription form the template, is there any reason for this?

We have multiple times those options: 
image
(one in "Newsletter Centered" section and the other one in "Newsletter form" section)

We should definitively be able to translate this "Thank you" message once filled in and submitted. Hopefully well work sooner or later on this task: https://www.odoo.com/odoo/project/974/tasks/3645991

**Comment by mano-odoo** [comment]
@lebl-odoo Thank you for being so reactive! 

For the Icon, I liked the idea of using an emoji for one, we don't do this in any snippets yet and it's an option the editor provide, so I think it's cool to highlight that it's "possible" with this snippet. Wdyt?

The SMS template has been raised here https://github.com/odoo/odoo/pull/186281#pullrequestreview-2421397182, I was waiting for @stefanorigano because during the discussion we agreed to not leave the "form" template option when the snippet is designed with an email input. I honestly initially forgot about the SMS template, I agree with you, it makes sense to introduce this option when it's already a snippet designed with the email input (since SMS is very similar). 

The translation would be great indeed!

**Comment by lebl-odoo** [comment]
We had a quick chat with @stefanorigano this morning about this, but I was surprised we only removed one that's the reason I asked about it :) Thx

About the emoji, I find it's hard to understand it is a plaintext element, but I agree with you that it could be nice to see what we can do. Let's ask @stefanorigano's opinion :)

**Comment by Brieuc-brd** [comment]
Since @mano-odoo is currently off, I pushed some changes on the branch :

- Updated the required and cherry picked [commit](https://github.com/odoo/odoo/pull/186490/commits/fd1c7eb6320d85b6568406806b3732e27ef26a49) from https://github.com/odoo/odoo/pull/186281 
- Design & structure adjustments
- Rebased the branch

The diff: 
https://github.com/odoo/odoo/compare/55775ece2336e1649ef774df8630f763e2aab8bd..50fed886913119380de5eb293de709eaf405038e

**Comment by Brieuc-brd** [comment]
Hey @lebl-odoo 👋 

>  Is it simple to be able to change the size of the input field?

As discussed, the form used in this snippet has been improved in https://github.com/odoo/odoo/pull/186281 . A maximum width has been added to the input, which fixes situations where the input is too long. I've updated the cherry picked commit in this PR so that the input works fine. 
We shouldn't need to add a controller now. 👍 

| Before | After |
|--------|--------|
| Capture d’écran 2024-11-18 à 13 42 53 | Capture d’écran 2024-11-18 à 13 42 25 |

**Comment by lebl-odoo** [comment]
Had another look, here is what I found

The Content Width full value is "contained" in a container. Most probably something expected, but I prefer to raise it.
image

I was wondering what is the space between container and the div? 
image

Those two remarks are most probably linked to the way we build the snippet: container with a single row not wrapped by a col?!


Happy Christmas :christmas_tree:

**Comment by mano-odoo** [comment]
Hello @lebl-odoo, the full-width do apply the container-fluid class but we kept a col-lg-6 so above lg the card will be `max-width: 50%;` this is indeed a design choice to avoid super wide card.

The col class is under the row, we use `container > row > col`, no need to add a col elsewhere.
image

The horizontal padding comes from the default col spacing. It's true that it looks a bit off without vertical spacing, I'm adding pt16 pb16 😄 

Happy Holidays 🎄

**Review by qsm-odoo — APPROVED** [review]
Alright, let's go ahead, this seems good :+1: 

I personally have the same doubts that Lionel had about the use of the emoji. I like using emoji myself but I think that in this website builder, all of these will be reported as bugs by users:
- "Can't click on the icon to replace it"
- "If I hit backspace, I have a weird envelop that appears"
- "On this computer, I don't have the same envelop icon as on this computer"

But we'll (re)think about that later.

@robodoo r+

**Pull request closed without merging**
