### PR TITLE
[FIX] payroll_account: proper analytic entry

### PR DESCRIPTION
**Pull request by lem8r**
Allow only expenses to be entered into analytic account.
See https://github.com/odoo/odoo/issues/10758

### CODE REVIEW

**Comment by lem8r** [comment]
At the moment analytic account is taken from salary rule, but it would be better to take it first from contract. For example if we want worker's salary to be in direct costs with analytic entry it is more convenient to provide analytic account on contract rather than modify salary rule and salary structure each time we need new analytic account on salary moves.

There are other bugs not mentioned yet.
For example: partner_id is not always properly set on account moves resulting wrong payable balance. Date comparison is not taking into account local time in some places (UTC is comparing to local time). There is no code variable in hr.holidays.

So, actually I can try to do better PR if it is not going against plans of Odoo team how to improve payroll module.
Or I can do own temporary inheritance module to fix all issues.

**Comment by lem8r** [comment]
poke @qdp-odoo just in case

**Comment by jaredkipe** [comment]
Though this certainly has merits, I feel that the salary rules analytic account should have precedence over the contract's. I can think of several reasons one may want to "override" the contract's analytic account at the rule level...

Though, I can also think of reasons where I might want also want a credit...

**Comment by wtaferner** [comment]
@jaredkipe 
@lem8r 
I have had the same issue and fixed it with these lines...it assumes that only reconcilable accounts do not need analytic entries. At least for my configuration and instances it works quite well, although there could be other use cases. The best would be to define it on the rule line per account

```python
# debit line
'analytic_account_id': analytic_id and analytic_id.id or False if not debit_account.reconcile else False,
# credit line
'analytic_account_id': analytic_id and analytic_id.id or False if not credit_account.reconcile else False,
```

**Comment by tivisse** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards

**Pull request closed without merging**
