### PR TITLE
[FIX] base: wkhtml2pdf multiple documents

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
- set up a header with company logo
- print 20 sale orders in arabic

Bug:
header disapears on most pages

Fix:
allow more time to render the documents according to the number of pages

opw-3217155

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
it's probably more simple to use a ir.config_parameter and default on a sane fixed value.

If the javascript delay is respected, it would mean that you add 75 seconds to print a report of 300 records (that could fit on 1 page I think, if 99 of them are empty).

**Comment by HANNICHE-Walid** [comment]
> it's probably more simple to use a ir.config_parameter and default on a sane fixed value.
> 
> If the javascript delay is respected, it would mean that you add 75 seconds to print a report of 300 records (that could fit on 1 page I think, if 99 of them are empty).

bodies here refers to the number of pages not records 
not sure what you mean by ir.config_parameter ?

**Comment by nle-odoo** [comment]
> @nle-odoo bodies here refers to the number of pages not records

you don't know the number of page, just the number of records: there is one body per record. 1 record could be printed in 0 or 100 pages (eg. a sale.order with thousands of lines).

But generally the number of record to pages would be rather similar (a record usually print in 1 or 2 pages).

> not sure what you mean by ir.config_parameter ?

This would mean changing the code like this:

```diff
+ delay = self.env['ir.config_parameter'].sudo().get_param('report.my_config_parameter', '1000')
   command_args.extend(['--javascript-delay', delay])
-  command_args.extend(['--javascript-delay', '1000'])
```
by default the value would be 1000 in this example, but someone could overwrite it by going to /web?debug=1 > Settings > Technical > System Parameters and creating a new parameter with key="report.my_config_parameter" and the value they want.

**Review by Julien00859 — APPROVED** [review]
this seems to be a nice trade-off, for most users it stays the same
for those who complain, the support makes sure their point is valid before suggesting increasing that ICP value

**Comment by HANNICHE-Walid** [comment]
should I document the new setting somewhere or just on the support ticket?

**Comment by Julien00859** [comment]
Just on the support ticket and spread the word to the tech-support team so they know there is a workaround

**Review by nle-odoo — COMMENTED** [review]
looks good to merge to me

robodoo delegate+ r+

**Pull request closed without merging**
