### PR TITLE
[FIX] account: avoid invoice name reset when we change the name manually

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
I m afraid it is only a half fix

**Comment by jco-odoo** [comment]
@zaoral @jjscarafia fyi

**Comment by jco-odoo** [comment]
@william-andre It should be ready.  (I started l10n staging as well)

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Comment by william-andre** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
