### PR TITLE
[FIX] website_sale: Get the right translation description in the cart

### PR DESCRIPTION
**Pull request by mamatch**
### Steps
- Add a different language
- Go to the website shop
- Change the language to the added one
- Add a product to the cart
- Go to the cart

### Issue
The description of the product is not translated.

opw-3389358

### CODE REVIEW

**Review by Feyensv — COMMENTED** [review]
Well, for me the bug lies in the computation of the description, which probably 
* doesn't receive the right context
* doesn't handle properly the language (and overrides it with the public partner language maybe)

Displaying the product description (and not the line one) here is not the right solution IMHO.  It will hide the root of the problem, and the same problem will probably arise in other places (printed quotation, portal, ...).

**Comment by mamatch** [comment]
The ``_compute_name()`` https://github.com/odoo/odoo/blob/2e5c8b4eb427e580ed22417ff49cf3cb994ba88d/addons/sale/models/sale_order_line.py#L306 which is responsible of the ``SaleOrderLine.name`` does well his job I Iguess, as it uses the ``partner_id.lang`` context to set it. In our case it just a display to meet the browser's language.

I've tried to override it like this 
```python
    def get_description_following_lines(self):
        context = {'lang': self.env.lang}
        description = [_(line) for line in self.name.splitlines()]
        del context
        return description[1:]
```
but it doesn't work. Do you have an idea please ?

**Comment by Feyensv** [comment]
What i mean is that we could consider not using the partner lang to compute the description in e-commerce orders, but the browser lang (if the partner is the public website partner)

**Comment by mamatch** [comment]
It worked as expect, but I think, to be more consistent in the display I should do the same for ``SaleOrderLine.name_short``

**Comment by Feyensv** [comment]
Well, wasn't this already fixed by #112658 ? :thinking:

**Pull request closed without merging**
