### PR TITLE
[IMP] doc: add guidelines about extandability

### PR DESCRIPTION
**Pull request by mart-e**
If the code is well written from the start, won't get so many hook requests.

The context is to avoid commits like 9434f7b64ec5ecb5e0a4 where it removed the hook method that was created before upon request.

Obviously open to suggestions.

cc @tivisse so the new dev not to forget it

cc @jem-odoo as you are the one usually messing up the guidelines

cc @tde-banana-odoo because :cheese:

### CODE REVIEW

**Comment by jem-odoo** [comment]
+1

**Comment by tde-banana-odoo** [comment]
I tend to agree while I don't like having ton of methods used only once to get a domain or stuff like that. It makes code difficult to read. I would therefore add a line to explain that somehow the developer has to make the right choice between extension possibility and code readability. There is no clear definition for those points but I think it is worth mentioning it.

**Comment by tde-banana-odoo** [comment]
I have to add that https://github.com/odoo/odoo/commit/9434f7b64ec5ecb5e0a4036c60998bf599fa2ba4 is a bad choice as it was intended to remove the domain. We now want to use only the access rules domain in the controllers; people should change the portal / public access rights and rules to change the result. So extensions for the sake of extension is not always welcomed.

**Comment by rvalyi** [comment]
in general that would also be cool if Odoo SA could reviews methods of important modules like account which exceed say 50 lines and try to split them. Generally this is where compatibility hurts when we have to override them and copy the entire code to change just a few lines...

**Comment by tde-banana-odoo** [comment]
@rvalyi Well when working on modules we try to clean the code and have a more functional way of programming. However this is limited to modified code. This could be included in guidelines to warn people to not write methods longer than 50 lines without being sure it is necessary.

**Comment by mart-e** [comment]
The idea of putting it in the documentation is stating this as the new official code rules. When refactoring part of the code, it should be applied.

ccing more devs so they can keep that in mind for future devs in their team or give their opinion on this:
cc @sle-odoo @qdp-odoo @JKE-be @ged-odoo @nim-odoo

**Comment by nim-odoo** [comment]
Might be nice to include info on McCabe complexity checker: https://github.com/PyCQA/mccabe

On another topic, I think it would be worth discussing the use of code formatting tools, such as [Black](https://github.com/ambv/black). At least for any new file, it would be great to have a consistent code formatting. But that's probably another story...

**Comment by ged-odoo** [comment]
@nim-odoo using a code formatting tool is awesome. But I don't know how to do that in Odoo. I am thinking about [prettier](https://prettier.io/), but how do we do that in practice? convert the whole codebase at once? at a git prehook to run it? I don't know.  But it sure would be nice.

Now, on topic, note that the same issue arises in JS land.

**Comment by JKE-be** [comment]
Using a code formatting tool is awesome ...or not...
I don't like the idea to have a bot that change code indentation that has been done by design to be more readable by human, just to follow some rule.

It will be a good start to explain at each new developer (or old that don't know about it) how to use a linter on their local computer to start ! And maybe just choose officially the list of PEP that we should _in most case_ respects.

About 9434f7b64ec5ecb5e0a4036c60998bf599fa2ba4, fun...
These domain was there for performance reason ! Remember that not only the portal user will see the portal. So, i'm not sure that the sale manager, or admin want to see the 1000000th of record in his portal and make it slowwwww or just get timeout. => See original commit that re-introduce it again and again...: a2c5fe4a64bcceb56fc7df16391c2acbfec6b178

That show 2 others problems in our process and guidelines:
* 1. We should check our code with more than just 20 records in db. I know that @tde-banana-odoo have some scripts to feed databases, maybe it should be share to all employees (if he is agree) to help guys to test their code with more realistic data.
* 2. We should explain how to blame the code to the developers, because it is not the first time that I see old bug come back, just because a developer decide to remove smthing that he don't understand! But to have blame that work, we should stop to move every month the code from one file to another and loose the history!

**Comment by gdgellatly** [comment]
I've been using black for some time with custom line length to suit OCA. A half reasonable example can be found at https://github.com/odoonz/odoonz-addons/blob/11.0/mrp_dynamic_line/models/mrp_production.py or https://github.com/odoonz/odoonz-addons/blob/11.0/account_central_billing/models/account_invoice.py to give you an idea of pros and cons.  Things like long if statements, domain tuples.  All in all, now I've got used to reading it, I prefer it, but it takes some time.

Some observations.

- For the most part code is more readable, but 
  - OCA short line length is annoying when combined with the way black deals with long functions, but at default 99 its OK
  - Black formats for shortest diffs.  This often means domain tuples in particular go from 1 line to 5 lines e.g. `[('some long field', '=', some_long_var)]` becomes
```python
[
    (
        "some long field", 
        "=",
       some_long_var,
    )
]
```
- It must be used with -S switch for this codebase or you will get massive code diffs (as shown above with double quotes). -S is a fairly new switch as well after months of argument so not everyone has it.  I've got used to the double quotes now.
- trailing commas everywhere (smallest diff possible thing again, shown above) - beware 2.7 backwards compatibility on function signatures.
- I think beyond extensible, one thing I have found lately is beyond the single responsibility piece is that hooks make code more testable.  Albeit this is from the point of developing extensions rather than writing extensible code but for example an idiom of
```python
def some_super_method(self)
   some_pre_super_method(self)
   super(...)
   some_post_super_method(self)
```

**Comment by nim-odoo** [comment]
> I don't like the idea to have a bot that change code indentation that has been done by design to be more readable by human, just to follow some rule.

That's actually the whole idea behind a code formatter :smiley: Let a bot decides of a standardized style instead of one style for each developer. Since it is all about style (and therefore subjective), it is not possible to satisfy everyone, though.

I guess it is also all about changing one's habits. As @gdgellatly mentions, it might take some time before one gets used to the new style. One can also tweak a few things, such as the line length. If you go for a line length of 110, most of the lines will still be < than 100, while you will mostly avoid excessive line breaks.

**Comment by JKE-be** [comment]
robopenerp r+

**Pull request closed without merging**
