### PR TITLE
[FIX] website : fix vertical alignment header lang picker

### PR DESCRIPTION
**Pull request by Louciole**
The language selector in the navbar is not aligned correctly.

Steps to reproduce:
- On a website page click on the header
- Activate Language Selector with dropdown

This commit aligns all items to the center of the picker.

task-3266722

### CODE REVIEW

**Review by rdeodoo — COMMENTED** [review]
Hi, can we have a before / after screenshot comparison ?
Also, I don't think we will merge a visuel alignment fix in 14.0 (or even 15.0), especially playing with flex & co.

**Comment by Louciole** [comment]
> Hi, can we have a before / after screenshot comparison ? Also, I don't think we will merge a visuel alignment fix in 14.0 (or even 15.0), especially playing with flex & co.

Yes you can, (I'll send it to you on discord) I was discussing it with benjamin and it was not clear if the fix was really necessary or not, in facts it's already centered but in a weird way

**Comment by rdeodoo** [comment]
We usually never create a new PR to retarget, we simply change the base target of a PR and push force the branch which is "reset/rebase" on the wanted version, so:
- (minor) We don't create many PRs
- (critical) We keep the history/thread of a PR

Also, bonus: it's quicker to do. You simply `git reset --hard origin/version` -> `git cherry-pick commit` -> `git push --force` -> Change PR target

It's fine for this one, there was almost no exchange on the PR and another has already been created anyway, but so you know for next time :+1:

**Comment by Louciole** [comment]
> We usually never create a new PR to retarget, we simply change the base target of a PR and push force the branch which is "reset/rebase" on the wanted version, so:
> 
>     * (minor) We don't create many PRs
> 
>     * (critical) We keep the history/thread of a PR
> 
> 
> Also, bonus: it's quicker to do. You simply `git reset --hard origin/version` -> `git cherry-pick commit` -> `git push --force` -> Change PR target
> 
> It's fine for this one, there was almost no exchange on the PR and another has already been created anyway, but so you know for next time +1

I'll remember next time !

**Pull request closed without merging**
