### PR TITLE
[REM] hr_timesheet: remove the onchange in analytic line

### PR DESCRIPTION
**Pull request by ppr-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ppr-odoo** [comment]
Hello @kba-odoo , would you have a look at this PR? Thanks!

**Comment by kba-odoo** [comment]
Hi @ppr-odoo ,

The original issue is still present I'm afraid.

You can reproduce by creating a timesheet entry for Project A > Task A.
Then on a task, change the project to Project B, the timesheet entry will no be linked to Task A anymore.

**Comment by kba-odoo** [comment]
Hi @ppr-odoo ,

The original issue is still present I'm afraid.

You can reproduce by creating a timesheet entry for Project A > Task A.
Then on a task, change the project to Project B, the timesheet entry will no be linked to Task A anymore.

**Comment by C3POdoo** [comment]
Dear @ppr-odoo,

Thank you for your contribution but we are closing it due to inactivity.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
