### PR TITLE
[REV] *: Restore the model `_name`

### PR DESCRIPTION
**Pull request by Gorash**
Following internal discussions, the python typing and inheritance task is canceled. The use of the class name instead of '_name' was done to allow notations such as `partner_id = fields.Many2one[base.ResParter](string='Partner')`. Since this notation is canceled, we put `_name` back (although the class name is sufficient).

Partial revert of https://github.com/odoo/odoo/pull/178200 and https://github.com/odoo/enterprise/pull/69762.

See also https://github.com/odoo/enterprise/pull/73643

### CODE REVIEW

**Review by kmagusiak — APPROVED** [review]

**Review by rco-odoo — APPROVED** [review]

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by sbidoul** [comment]
So sad...

**Comment by pedrobaeza** [comment]
Any possible explanation of the reasons to cancel it?

**Comment by pedrobaeza** [comment]
See the explanation in https://github.com/odoo/odoo/pull/178200#issuecomment-2527468122

**Pull request closed without merging**
