### PR TITLE
FIX bug #5329 pricelist_id and currency_id on PO are now always in the company of the PO

### PR DESCRIPTION
**Pull request by alexis-via**
See the bug report #5329 for a detailed scenario of this multi-company bug.

I already use this patch on a production v8 system.

### CODE REVIEW

**Comment by legalsylvain** [comment]
LGTM. :+1:

**Comment by alexis-via** [comment]
In fact, this patch is not prefect yet: the pricelist and currency on the generated PO are OK, but the price of the product in the PO line is 0.

**Comment by alexis-via** [comment]
It is OK now ; the price is also good in the PO line.

**Comment by beledouxdenis** [comment]
Closed with a4e48d4c2848f0c90c9bdd082790dde6823d7557.

I shortened a little bit your patch, and changed  your commit author (from `via.ecp.fr` to `akretion.com`), but basically, your pull request was totally correct.

Thank you for your contribution !

**Comment by alexis-via** [comment]
@beledouxdenis Thanks for your review and merge !

**Pull request closed without merging**
