### PR TITLE
[FIX] website_sale: use correct taxes

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@nim-odoo @JKE-be @sbuhl Can this be considered a bug fix?  (pr needs some finishing touches)

**Comment by jco-odoo** [comment]
@seb-odoo

**Comment by seb-odoo** [comment]
I'm not knowledgeable on taxes, and I lack context to understand what you are trying to do/fix.
What is the related task? How to reproduce?
If the Default Sale Tax is supposed to apply on ecommerce too when no specific product tax is given, then yes I guess that's fine?

This is just a quick response from me to acknowledge your ping, but I think the account or (website)sale team are best to handle this problem.

**Comment by jco-odoo** [comment]
@seb-odoo @smetl @tsb-odoo I see that the logic is the one from sale order/purchase orders and we have a slightly different one in invoices.  

The original problem is that when you install a new company, on the existing products the default sale tax will not be set.  Also, when you create a new product, only the default sale tax will be set according to the company you happen to be in.  (and not the other companies)

In an invoice line, if it can not find any taxes on the product and on the account being used, it will fall back on the default tax on the company, but this is not consistent with sale/purchase/website_sale/... and problematic when you don't want to have a tax on a product. 

But it is also not logical that fiscal positions are only applied if defined on the partner.  (as a lot can be defined automatically depending on the partner)

So, solution 1: change sale/purchase like invoice
solution 2: do nothing and do things properly in master
solution 3: copy default tax on the existing products and make a more intelligent default value (and maybe even don't fall back in invoices)

**Pull request closed without merging**
