### PR TITLE
[15.0][FIX] fix user_id missing bug in this.getSession()

### PR DESCRIPTION
**Pull request by jlzhou**
Description of the issue/feature this PR addresses:
Click 'My Tasks' menu in Project

Current behavior before PR:
Traceback occurred

Desired behavior after PR is merged:
No Traceback

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xavierbol** [comment]
Hello,

Thanks for the fix, can you share us the traceback to understand the bug? Also you should explain the issue and the reason why your work fixes the issue in your commit message.

Thanks in advance!

**Comment by dmo-odoo** [comment]
I'm confused because there are other places in the code where `user_id` is accessed on the object returned by `this.getSession()`. Do those calls fail as well ? If yes then why not fix them as well in this PR ? If no then what makes the two instances at hand here different than the others ?

**Comment by jlzhou** [comment]
`project_kanban.js:344 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Class._readGroup (project_kanban.js:344:1)`

After more investigation, I found the issue was caused by auth_totp module deletion.

Module auth_totp is a auto_install addon, it overrided ir.http to add user_id in session_info.

A new issue still remained: the project and web_editor module should depend auth_totp module since they invoked user_id from session in its js code.

**Comment by dmo-odoo** [comment]
I'm speaking for `web_editor`. I don't think we want to add this dependency, so I guess the `uid` fix is therefore correct. Thanks for clearing things up (and for the fix of course) ! 👍

**Comment by tivisse** [comment]
Thanks @jlzhou for your fix.

Indeed it seems valid. But could you please rewrite the commit message according to our guidelines (See https://www.odoo.com/documentation/15.0/contributing/development/coding_guidelines.html#commit-message-structure ) and by explaining that this is actually the ``auth_totp`` that is bringing the issue if the module is uninstalled ? 

@odony Don't you think that we should add ``user_id`` on the ``session_info`` in ``web/models/ir_http.py`` instead of ``auth_totp``? 

I don't think that it should be done in a stable release (as this fix seems sufficient), but it could be a good thing to do in master no ?

**Comment by odony** [comment]
> @odony Don't you think that we should add `user_id` on the `session_info` in `web/models/ir_http.py` instead of `auth_totp`?

Historically, we had a `session_info['uid']` key in the back-end, and a `session_info['user_id']` in the front-end. So depending on where the JS code is running, it is supposed to use the corresponding key.

As for `auth_totp`, it turns out it had some code that runs in both front-end and back-end, so it aliased the `user_id` for cross-compatibility. But it did so with a typo (trailing comma), so the value is a tuple/array by mistake:
https://github.com/odoo/odoo/blame/master/addons/auth_totp/models/ir_http.py#L12

Then people have started to randomly use it in back-end code that doesn't depend on `auth_totp` -- those are easy to spot: they use `user_id[0]` because of the typo. And it blows up if people every uninstall `auth_totp` for some reason (not very common, fortunately).

Please see #94444 also.

We can't change those keys in stable, but in master it would make sense to unify the keys somehow.

In the mean time, in stable:
- back-end => `getSession().uid` 
- front-end => `getSession().user_id`
- cross-compatible: `getSession().uid || getSession().user_id` or similar

**Comment by rdeodoo** [comment]
_Related (probably not useful but thought it would help gather related stuff since I got notified on the PR)_: We also "recently" faced that issue with the framework method `user_has_group()` and indeed we had to patch the code to be cross compatible and check for both keys, which seems to be the only stable solution (as some users might now relate on that attribute not being set in the frontend context): https://github.com/odoo/odoo/commit/9aafec4ed94b9f7f2af42970dd14142ee5ca70dc

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
