### PR TITLE
[FIX] sale_margin: correct computation of margin in groupby in the SO

### PR DESCRIPTION
**Pull request by Demesmaeker**
For now, the sale margin is incorrectly computed in group by in the sales order 
This was done in the sales order lines in abdb85fb28af097824d7c18b8feb82af508608eb

opw-3180556

### CODE REVIEW

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by Demesmaeker** [comment]
@robodoo r-

**Comment by Feyensv** [comment]
@robodoo delegate+

**Comment by Demesmaeker** [comment]
@robodoo r+ up to 16.0

**Comment by Feyensv** [comment]
maybe you wanted to talk to fw-bot ? :D

**Comment by Demesmaeker** [comment]
... Yes. But I'll just continue to talk to myself in my head, hide in a hole, and ignore the rest for today xD

**Pull request closed without merging**
