### PR TITLE
[FIX] web: allow override of factor in FloatToggleField

### PR DESCRIPTION
**Pull request by ppr-odoo**
Changes made in odoo/odoo#98380 were missing the externalization of the factor
computation although already used.

task-2974145

### CODE REVIEW

**Comment by IT-Ideas** [comment]
The reason is that otherwise [this](https://github.com/odoo/odoo/blob/91678b3cf34be96843aedc900d31ecb4c2b97471/addons/hr_timesheet/static/src/components/timesheet_float_toggle/timesheet_float_toggle.js#L7) is not working

**Comment by ppr-odoo** [comment]
> this

👍

**Comment by IT-Ideas** [comment]
Could you update the commit message into:
```txt
[FIX] web: allow override of factor in FloatToggleField

Changes made in odoo/odoo#98380 were missing the externalization of the factor
computation although already used.

task-2974145

```

**Comment by ppr-odoo** [comment]
@IT-Ideas Done.Thank you

**Comment by IT-Ideas** [comment]
Hello @ppr-odoo I added the tests and by doing that also found another bug to solve.

**Comment by ppr-odoo** [comment]
> Hello @ppr-odoo I added the tests and by doing that also found another bug to solve.

Ok.thanks for the information.

**Comment by IT-Ideas** [comment]
@robodoo r+

**Comment by IT-Ideas** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
