### PR TITLE
[FIX/IMP] Odoo Cross Export/Import data needs a better and unique

### PR DESCRIPTION
**Pull request by wtaferner**
external_id name
## Impacted versions:

8.0 and above
## Steps to reproduce:
- Export user-generated data of the same model and record id in two independent Odoo databases before doing anything else
- Import one or the other in the other database
## Current behavior:
- The import will replace an unrelated record which is bad...
## Expected behavior:
- The data is not replaced but correctly imported even if they are originally from the same model and have the same record id

@beledouxdenis @odony 
Actually it is difficult to say whether it is a bug or a feature request, but as it does not harm the stable policy (at least I think it does not) I open my PR against 8.0

### CODE REVIEW

**Comment by odony** [comment]
This is an important change of behavior, and not a bugfix at all, so that definitely cannot go in 8.0. In addition, the chosen solution (if we decide to change anything) would have to be discussed thoroughly. The db uuid should probably not be leaked in user-facing data, and is a bit longish for purpose of uniqueness. A naive alternative would be to generate semi-random hashes of a few bytes based on the current time, adding enough randomness that you won't be able to trigger a collision for the same id + model...

**Comment by wtaferner** [comment]
Thank you for your comment. I thought the first five chars of the db uuid would be a good identifier where the data originally came from as it is data source related and we can repeat it as often as needed b/c it could happen that someone deletes the external_ids and they should be reproducible anytime. The current approach is unsafe and it actually did harm an instance of mine b/c I did transfer data from one database to the other and have overwritten "sensible" data.

But every other identifier which is more "unique" than the current approach per database should work. 
My 5 cents, but I am looking forward for a discussion on this one to find an awesome solution as it seems important to me...

**Comment by wtaferner** [comment]
About change in behavior: I thought this shortly too, but as soon an external_id exists, it will not be overwritten...so it would only apply to newly created record exports...

**Comment by wtaferner** [comment]
@odony 
May I ask you to explain a little bit further why this PR is dangerous for the core/stable as it resolves an even more dangerous existing issue for export/import (DAU functionality)?

I did a quick "fix" by obfuscating the dbuuid ("secure" sha256 hashing) as you mentioned it as a concern.

As always I appreciate your opinion, explanations and suggestions to fix the issue (update wrong records in one Odoo instance from another is severe anyway)

**Comment by wtaferner** [comment]
@rco-odoo 
As we talked about this yesterday, I ping you...it is already tagged as wishlist and blocked, but the solution is still not available (**since July 2015**) and as it is kind of a cheap success to fix this it would be nice if you can assign yourself to this issue that it resides in the correct team instead nowhere on Github. If we agree on some strategy I would feel honored to do or forward-port with changes the little piece of code myself...of course only if you guys don't want to test it and research it on your own to be super ^^ secure about the outcome ;-)

@odony 
The methodology is IMHO correct in order to have a more reliable import/export Odoo generated ```external_id```. So, I guess it only needs a proper and fast, in terms of performance, implementation to protect the ```dbuuid``` which is backward compatible (although I think it is not a question at all as the ```external_id``` is just a one time shot and database maintained).

**Comment by gdgellatly** [comment]
As a really simple suggestion. What about a user defined prefix per export
or with a default of __export__ or as a system parameter.

**Comment by wtaferner** [comment]
@gdgellatly 
I think the prefix/namespace is not the issue here...it is the possibility of collision between two databases due to short-sighted automatic ```external_id``` creation. Of course giving more responsibility and a configuration option to the user is an additional way, but would make it IMHO more complex (we need to rely on the maintainer to not fuck it up) or hidden as it currently is.

**Comment by wtaferner** [comment]
@Yenthe666 
This could be also tagged for framework and wishlist (maybe also versions) I guess ;-) You are soon in tag hell I guess...but honestly I like it a lot :+1:

**Comment by Yenthe666** [comment]
Haha, tagged. I like the tagging too. It is a suggestion and attempt for me to segment all the bugs/PR's. It'll give us better insight and filtering abilities in a while ehich should improve the processes too.@odony can we get this one moving again?

**Comment by mart-e** [comment]
Closing in favour of #22493 (will not change that in 9.0 anyway)

**Comment by wtaferner** [comment]
@mart-e 
Thx, the issue mentioned here will be resolved with the extra salt added in #22493. Not completely happy with the approach itself (could have been way better, but as it is in latest stable I hope for better times in master). I hope it won't take another 3 years :wink:

**Comment by mart-e** [comment]
> I hope it won't take another 3 years

Me too...  :wink:

**Pull request closed without merging**
