### PR TITLE
[FIX] account: take into account the amount type of second reconciliation line

### PR DESCRIPTION
**Pull request by william-andre**
The field second_amount_type was not taken into account when doing automatic reconciliation and 100% of the remaining amount was always used.

We can now also use a percentage of the remaining amount, or a fixed amount.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by william-andre** [comment]
@csnauwaert You can run but you can't hide!

**Comment by csnauwaert** [comment]
@robodoo r+

**Comment by csnauwaert** [comment]
@william-andre might needs a rebase :)

**Comment by william-andre** [comment]
@csnauwaert Need a rebase on a stable branch? What is this sorcery?

**Comment by csnauwaert** [comment]
@william-andre probably a false positive that might have been resolved with a rebuild but a rebase doesn't hurt ;)

**Comment by william-andre** [comment]
@csnauwaert greened

**Comment by csnauwaert** [comment]
@robodoo r+

**Pull request closed without merging**
