### PR TITLE
[IMP] account: Add index on reversed_entry_id

### PR DESCRIPTION
**Pull request by rousseldenis**
Description of the issue/feature this PR addresses:

Performances improvement

Current behavior before PR:

An unlink on account_move can lose 600 ms

Desired behavior after PR is merged:

Restore 600 ms on unlink

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lordkrandel** [comment]
Hello, can you please give us some context about which part of Odoo you find slow because of this missing index?

**Comment by rousseldenis** [comment]
Tested with one DELETE account_move WHERE id = <id>

Before :

image


After:

image

**Review by sbidoul — APPROVED** [review]

**Comment by lordkrandel** [comment]
I'm sorry, but I have to close this PR with the same reason as https://github.com/odoo/odoo/pull/83472#issuecomment-1024214270 .

**Comment by pedrobaeza** [comment]
@rousseldenis what about going with this index in OCB?

**Pull request closed without merging**
