### PR TITLE
[FIX] website: fix trigger of website_url_chosen

### PR DESCRIPTION
**Pull request by bvr-odoo**
Before this commit, website_url_chosen was triggered when the dropdown
of the input closed instead of when an item was selected in the
list. This caused the following issue: you lost focus in the input
every time the list closed while typing.

After this commit, website_url_chosen is only triggered when an item
is selected in the results list of a urlpicker input.

task-2312878

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo r+

thx

**Comment by JKE-be** [comment]
@robodoo rebase-ff

**Comment by d-fence** [comment]
@JKE-be
Pay attention that the forward-port to saas-14.1 is missing. The bot missed this PR for an unknown reason.

**Comment by JKE-be** [comment]
no problem, saas-14.1 will be dropped in 2 months btw ;)

thx, I will cherry-pick it

**Pull request closed without merging**
