### PR TITLE
[FIX] sale: pricelist should be required

### PR DESCRIPTION
**Pull request by Feyensv**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@tivisse was there any reason for making the pricelist no required anymore ? :D

**Comment by Feyensv** [comment]
Can I leave it to you (since I'm off next week) :pray: ?
We probably can't change that again in stable, so it should probably be replaced by a required in the view and maybe an error at write/create if no pricelist is specified :thinking:

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
