### PR TITLE
[IMP] point_of_sale,pos_reprint: allow reprinting without POSBox

### PR DESCRIPTION
**Pull request by jorenvo**
Closes #16452

### CODE REVIEW

**Comment by wtaferner** [comment]
Certainly more elegant :+1: 
What about [```render_change()```](https://github.com/odoo/odoo/pull/17504/files#diff-8e92af9e8e362cd5240eb339ece8809fR1427)? Shouldn't we overwrite this method in the ```ReprintReceiptScreenWidget``` as well?

I think we should also make a snapshot available in the backend as well for both. What do you think? Based on this we could reprint on demand and it would be always a snapshot of the original and actually mark them as a copy.

Not tested so far.

**Comment by jorenvo** [comment]
> What about render_change()? Shouldn't we overwrite this method in the ReprintReceiptScreenWidget as well?

Good point. It's already hidden in the xml but we may as well make that function a noop.

> I think we should also make a snapshot available in the backend as well for both. What do you think? Based on this we could reprint on demand and it would be always a snapshot of the original and actually mark them as a copy.

I currently don't have the time to do that. If accepted by the powers that be we can do that separately afterwards.

**Comment by wtaferner** [comment]
Ok, thx, I think we could also remove the Button for the Next Order instead of just make the function ineffective on click, right?

> I currently don't have the time to do that. If accepted by the powers that be we can do that separately afterwards.

I see, as long you have it in the back of your mind the time will come where this could be improved ;-)

**Comment by gustavovalverde** [comment]
This should be in 10 😢

**Comment by jorenvo** [comment]
@gustavovalverde I disagree. This is an improvement that introduces a whole new feature, not a bugfix. We purposefully limit functional coverage of stable Odoo releases to ensure stability for customers currently using these releases. Please consult our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) for more details.

**Comment by gustavovalverde** [comment]
I know, I'm just whining :)

**Comment by jorenvo** [comment]
Closed in 4d461cb.

**Comment by wtaferner** [comment]
@jorenvo 
Just tested it on runbot. Thx, for taking the time for refactoring and integrating :-)

**Pull request merged**
