### PR TITLE
[FIX] models: avoid prefetch hell when reading fields

### PR DESCRIPTION
**Pull request by rco-odoo**
The method `read()` may be very slow when reading relational fields and
computed fields, because the computed fields can be computed on a recordset
that is larger than expected.

The issue occurs on model 'res.partner' when reading fields 'child_ids' and
'purchase_order_count', for instance.  Suppose we read those two fields on a
partner with 1000 contacts.  First, the one2many field is read from the
database and stored to the cache; the latter adds the value ids to the
prefetching of 'res.partner'.  Then, the fields are fetched from the cache.
When 'purchase_order_count' is accessed on the partner, the field is computed
on all its children as well...

### CODE REVIEW

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by mart-e** [comment]
robodoo retry :man_dancing: !

**Comment by rco-odoo** [comment]
robodoo retry

**Comment by Yenthe666** [comment]
Robodoo is not very kind today hehe.

**Comment by KangOl** [comment]
robodoo retry ⏭

**Pull request closed without merging**
