### PR TITLE
[CLA] Viindoo updates Odoo's CLA

### PR DESCRIPTION
**Pull request by royle-vietnam**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by royleviindoo** [comment]
Hi @mart-e , could you review this, please?

**Comment by mart-e** [comment]
Hello,

Please don't remove user that have already contributed to the codebase (e.g. transon821996).
Best,

**Comment by royleviindoo** [comment]
> Hello,
> 
> Please don't remove user that have already contributed to the codebase (e.g. transon821996). Best,

@mart-e I edited it, please review, thank you

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
