### PR TITLE
[IMP] im_livechat, *: Refactor JS Public Livechat (step 9)

### PR DESCRIPTION
**Pull request by alexkuhn**
*: website_livechat

This commit is a step towards refactoring the JS of public livechat,
so that it reuses the same architecture as the code of Discuss.
This implies code that uses JS models and OWL components.

Task-2928837

### CODE REVIEW

**Comment by alexkuhn** [comment]
@seb-odoo ci/security failure due to this commit that moves code with `utils.Markup()`:
https://github.com/odoo/odoo/pull/95081/commits/4bb3ca4fc93f3223cc69f4c510c88ec95956ea78

**Comment by seb-odoo** [comment]
@robodoo override=ci/security
Just a code move. Unsafe usage of Markup, but body comes from sanitized field in python.

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
