### PR TITLE
[IMP] base: check that the properties' definition record field is in the view

### PR DESCRIPTION
**Pull request by std-odoo**
Purpose
=======
Check that the definition record of a properties field is in the view instead of crashing at runtime when we open the view.

Task-3850901

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo r-
is `must_have_fields` since #137031

https://runbot.odoo.com/runbot/build/62668164

**Comment by std-odoo** [comment]
@Feyensv Hi, is it ok like that ?

**Comment by Feyensv** [comment]
If it's green and rebased, I suppose it is :D.
It's your PR, I only appeared here because it was causing issues in stagings and the error was very probably caused by this PR ;)

**Comment by tde-banana-odoo** [comment]
Yeah, the PR was ready one month ago, so I r+'ed it but in the mean time there were framework changes :D

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
Not blaming you, since there were no conflicts, it'd have been difficult to spot beforehand :D.

**Pull request closed without merging**
