### PR TITLE
[FIX] Update required version of num2words to have more languages

### PR DESCRIPTION
**Pull request by novawish**
Description of the issue/feature this PR addresses:
Update the version of num2words
Current behavior before PR:
Can not convert num2words with Vietnamese language
Desired behavior after PR is merged:
Can convert number to Vietnamese words

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by novawish** [comment]
@d-fence Thanks for replying, I changed the required version to 0.5.6

**Comment by novawish** [comment]
BTW, should i create another PR to branch `12.0` for version 12.0 and `master` for future versions?

**Comment by d-fence** [comment]
@novawish it's not needed to do a PR for each Odoo version. It will be forward-ported.
By the way, you should change the commit message to follow the [Odoo guidelines](https://www.odoo.com/documentation/12.0/reference/guidelines.html#tag-and-module-name) and change ADD to FIX. Only fixes are forward ported.

**Comment by novawish** [comment]
@d-fence Thank you very much, i updated the commit message to FIX

**Comment by d-fence** [comment]
@robodoo r+

**Pull request closed without merging**
