### PR TITLE
[IMP] web: char field, password shouldn't be trimmed

### PR DESCRIPTION
**Pull request by SimonGenin**

### CODE REVIEW

**Comment by jco-odoo** [comment]
@nhomar @luistorresm Instead of https://github.com/odoo/enterprise/pull/17207#issuecomment-1229837001

**Comment by jco-odoo** [comment]
@jpp-odoo

**Comment by SimonGenin** [comment]
@jco-odoo Don't forget to provide a rationale for the PR here on the comments

**Review by luistorresm — APPROVED** [review]
👍

**Comment by jco-odoo** [comment]
@SimonGenin Rationale:

Passwords are something we know that need to be exact.  So, the regular behaviour where double spaces are changed to single ones and spaces are trimmed at the start and end of the string is not a good idea for passwords in general. Not that a lot of people put double spaces or space in the start or end of their passwords, but it happened and it is possible.  So, if password is True on the field, it does not make any sense to trim it and let's support that in the web client (as the web client does the trimming) instead of putting trim=False on all password fields in the Python, risking to forget it for the next password field.

**Comment by SimonGenin** [comment]
@aab-odoo @mcm-odoo Do you agree on this ?

**Comment by aab-odoo** [comment]
Yep

**Comment by SimonGenin** [comment]
@jco-odoo You may R+ :)

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
Thanks @SimonGenin

**Pull request closed without merging**
