### PR TITLE
[IMP] point_of_sale: catch errors during partner writings or creation 

### PR DESCRIPTION
**Pull request by rolandojduartem**
Currently, point of sale does not show a readable error for user in the
edition of the partners, this change shows the error from the backend to
give more information about the causes.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rolandojduartem** [comment]
Hi, @luisg123v, @desdelinux, @caburj  and @adgu-odoo, please, could you review this PR?

cc @fvz-odoo

**Comment by adgu-odoo** [comment]
The error handler from the point of sale should already be doing this. I will thus close this PR.

**Comment by rolandojduartem** [comment]
Hi, @adgu-odoo,  why? by this commit https://github.com/odoo/odoo/commit/64186386629ae6062f3cbb6ce47d25cfeb650c74?

**Comment by adgu-odoo** [comment]
Hello @rolandojduartem, no it's not this commit (this one is handling the error that might happen at the loading of the pos). Maybe I've been too quick to close this PR but I made some tests manually and there was not an error that the error handler of the pos could not handle correctly but it's possible that I missed something. So if you have a way to generate an error that is poorly handled without your fix please tell me. Have a good day!

**Comment by rolandojduartem** [comment]
Yes, @adgu-odoo, it was so quick. I tested and you are right, now pos handles the errors, so the commit in l10n_pe_pos is required, please, I open a new PR, could you review it? https://github.com/odoo/odoo/pull/160389

**Pull request closed without merging**
