### PR TITLE
[FIX] web: time picker should always be LTR

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
1-set language to an LTR language (arabic / hebrew...)
2-select any field with the date-time range widget (eg: planning>add)
3-the hour and the minute selection is reversed.

Bug:
the hours and minutes order depends on the language orientation where
they should always follow this format HH:MM

Fix:
force the time to be displayed Left To Right regardless of language

opw-2953221

### CODE REVIEW

**Review by nle-odoo — COMMENTED** [review]
solution looks good to me

in general we try not to fix in external library, so it would be better to do equivalent fix in an Odoo CSS file. For example I think we already have some fixes for RTLCSS & Bootstrap in the file:

addons/web/static/src/scss/bootstrap_review.scss

so you could do your fix there targeting the right elements with a selector, and using the css code directly, so I guess:

```css
    unicode-bidi: embed; // ensure element has level of embedding for direction
    /*rtl:ignore*/
    direction: ltr;
```
I'm not sure if the first line is necessary.

**Comment by HANNICHE-Walid** [comment]
done

**Review by nle-odoo — COMMENTED** [review]
looks good

but I think it would be better to have it in:

web/static/src/scss/daterangepicker.scss

because we are still in the external library (everything that is inside /lib/ is usually an external library).

**Comment by HANNICHE-Walid** [comment]
sorry i didn't understand what you meant by external library I'll switch it

**Comment by HANNICHE-Walid** [comment]
done

**Review by nle-odoo — APPROVED** [review]
looks good to me


> sorry i didn't understand what you meant by external library I'll switch it

no worry, yes usually directories in /lib/ are copies from external libraries (not created by odoo) and we sometimes update them, so we try to not do any fix inside them if possible (to not lose them on update and make update more easy).

**Pull request closed without merging**
