### PR TITLE
[FIX] base_import : Add new date formats in import file

### PR DESCRIPTION
**Pull request by Mtaylorr**
When you import a csv file with date format as DD.MM.YY you don't have the option to select that specific date format , it's not in the list.

Steps to reproduce the error :
1-install accounting
2-go to accounting and select import on the Bank card 3-choose the file attached in the ticket
4-select Date in the field Buchungstag
5-you can see that it's date format is DD.MM.YY which doesn't exist in the list of 'Date Format' on the left.

Solution :
Added the required date format to the list.

opw-3425402

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me, maybe for ease of finding, the added formats should be between

```py
'DD-MMM-YYYY',
```
and
```py
'MM/DD/YY',
```
this way the local formats "DD[character]MM*[character]YY*" are grouped together

**Comment by Mtaylorr** [comment]
@rco-odoo , @xmo-odoo can you take a look at this FIX ? thanks

**Comment by Mtaylorr** [comment]
@odoo/rd-framework-py can you take a look at this FIX ?

**Review by Julien00859 — APPROVED** [review]

**Review by nle-odoo — COMMENTED** [review]
thanks

robodoo r+

**Comment by nle-odoo** [comment]
robodoo r-

(didn't see the review were manually asked)

**Comment by Julien00859** [comment]
@robodoo r+

it was to let them know

**Pull request closed without merging**
