### PR TITLE
[IMP] * : rating icons improvement

### PR DESCRIPTION
**Pull request by karlosvalverde**
[IMP] * : rating icons improvement

*{
 project,
 rating
}

Previous rating icons had readability issues, especially when used in
small containers. For this reason, this PR includes the following
improvements:

- New rating icons have been designed and included in PNG and SVG, in
order to increase readability.
- Rating mail template, from the 'project' module, has been improved,
by adding more margin to the top of the icons, which increase its
visibility.
- 'Thank you for rating our services!' template has been revamped, by
removing the old '.card' template and by improving the shadow effect
cast on focus plus a better user interaction. 

--

task-2531541

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by IT-Ideas** [comment]
Hello @karlosvalverde 🙂 
Can you make two separate commits? One only for project and the rating related things into another one?

As per [guidelines](https://www.odoo.com/documentation/14.0/fr/developer/reference/guidelines.html#tag-and-module-name) we tend to avoid touching several modules in one commit, unless the change is really bound (for instance you add a class in a module B that C depends on and you use it in module C in the same PR).

Then also add this at the end of the commits:
```txt
Closes: #[numberOfThisPR]
```

Thanks for your work 🙂

**Review by tde-banana-odoo — APPROVED** [review]
LGTM

**Comment by karlosvalverde** [comment]
> Hello @karlosvalverde 🙂
> Can you make two separate commits? One only for project and the rating related things into another one?
> 
> As per [guidelines](https://www.odoo.com/documentation/14.0/fr/developer/reference/guidelines.html#tag-and-module-name) we tend to avoid touching several modules in one commit, unless the change is really bound (for instance you add a class in a module B that C depends on and you use it in module C in the same PR).
> 
> Then also add this at the end of the commits:
> 
> ```
> Closes: #[numberOfThisPR]
> ```
> 
> Thanks for your work 🙂

Done! :)

**Comment by IT-Ideas** [comment]
@robodoo r+

**Comment by IT-Ideas** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
