### PR TITLE
[IMP] l10n_lu: add account groups

### PR DESCRIPTION
**Pull request by william-andre**
Task [2220128](https://www.odoo.com/web#id=2220128&action=333&active_id=1691&model=project.task&view_type=form&cids=1&menu_id=4720)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by william-andre** [comment]
@jco-odoo This one is now on 13.2 and I think it needs less review than the one for Belgium. Maybe start with this one?

**Comment by jco-odoo** [comment]
@william-andre Can you improve the first commit message?

**Comment by william-andre** [comment]
@jco-odoo Indeed, done.

**Comment by william-andre** [comment]
@jco-odoo `msguniq` is a great utility indeed. If its good for you, I can squash the last 2 commits.

**Comment by william-andre** [comment]
replaced by https://github.com/odoo/odoo/pull/48231

**Pull request closed without merging**
