### PR TITLE
[REF] hr_holidays: refactor js code for time_off_calendar.*.js

### PR DESCRIPTION
**Pull request by phwa-odoo**
task- 2643692 required customizing the calendar view to display a calendar from the employee form via the Time Off smart button.
As the changes took place after the freeze of the saas-14.5 branch, it was not possible to split the time_off_calendar.js file into its different components to have them being re-used in time_off_calendar_employee.js file.
Subsequently, some code duplication exists between the two files and makes it hard to maintain.
This commit is for making the custom calendar components more modular and more maintainable.

task-2661142

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by kbapt — COMMENTED** [review]
Some nitpicking :innocent:

**Review by xavierbol — COMMENTED** [review]
Nice work, I review this PR to mainly learn/show you about the possibilities with the new JS syntax in Odoo. ^^
Don't hesitate if you have any questions or something that you don't understand. 🙂

**Review by xavierbol — COMMENTED** [review]
Thanks for the changes ! 🙂 
I have made my last comments and suggestions. 😇

**Review by kbapt — CHANGES_REQUESTED** [review]
Another round of little nitpicking comments :innocent: 

Don't hate us :grimacing:

**Review by kbapt — CHANGES_REQUESTED** [review]
Last one from me :innocent:

**Pull request closed without merging**
