### PR TITLE
Fix footer slideout effect and option UI

### PR DESCRIPTION
**Pull request by bvr-odoo**

### CODE REVIEW

**Review by qsm-odoo — COMMENTED** [review]
@bvr-odoo 

- I changed your first commit to remove the "margin right on the checkbox" stuff. There was already a space between the checkbox and other elements... it was the checkbox which was cut because its container was allowed to shrink below the checkbox size. I made another commit to solve that

- I found a hacky solution to solve the slideout effect problem on Firefox without breaking it on Chrome.

Seems ok for me, could you check and test all of this on your side then r+ if you are ok? :+1: 

@robodoo rebase-ff deletate=bvr-odoo

**Comment by bvr-odoo** [comment]
> @bvr-odoo
> 
> * I changed your first commit to remove the "margin right on the checkbox" stuff. There was already a space between the checkbox and other elements... it was the checkbox which was cut because its container was allowed to shrink below the checkbox size. I made another commit to solve that
> * I found a hacky solution to solve the slideout effect problem on Firefox without breaking it on Chrome.
> 
> Seems ok for me, could you check and test all of this on your side then r+ if you are ok? 
> 
> @robodoo rebase-ff deletate=bvr-odoo

It works, good find

**Comment by bvr-odoo** [comment]
@robodoo r+

**Comment by bvr-odoo** [comment]
> I'm sorry, @bvr-odoo. You can't review+.

@qsm-odoo because of the typo in "deletate=bvr-odoo"

**Comment by qsm-odoo** [comment]
Oups.

@robodoo r+

**Pull request closed without merging**
