### PR TITLE
[FIX] web, *: adapt `oi-close` and corner arrow icons 

### PR DESCRIPTION
**Pull request by Brieuc-brd**
\*: mail, pos_sale, pos_self_order, website_sale

### 1. `oi-close` adaptation
Prior to this commit, `oi-close` icon was based on the default sans-serif font.
Depending on this, there could be alignment and size inconsistencies with the Odoo UI icon library.
This commit adapts `oi-close` to use a custom icon from the UI icon library to make it more robust and maintain consistency with this library.

### 2. Corner UI icons adaptation
Prior to this commit, directional icons related to the four corners were misaligned.
This commit adapts these four icons so that they are properly aligned.

task-3618046

| 1 | Before | After |
|--------|--------|--------|
|  | Capture d’écran 2023-12-01 à 14 51 59 |  Capture d’écran 2023-12-04 à 17 09 50 |
|  | Capture d’écran 2023-12-01 à 16 57 15 | Capture d’écran 2023-12-01 à 16 58 49 |

| 2 | Before | After |
|--------|--------|--------|
| | Capture d’écran 2023-12-01 à 17 00 04 | Capture d’écran 2023-12-01 à 17 00 34 | 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hey @stefanorigano 👋 
This PR is ready for review, could you take a look at it ? 
For now, I've split this PR into 2 commits, but I think we could squash them, what do you think ?

**Comment by stefanorigano** [comment]
Hello @Brieuc-brd , thanks.
At first glance the visual result `oi-close-large` seems to be the desired result for any close icon. 
Why do we need a "smaller"`oi-close` by default?

**Comment by Brieuc-brd** [comment]
I thought the main purpose of `oi-close` was to get a smaller cross than `fa-times` (e.g. to handle small elements like a tag list). But I was wrong.

In the end, it's better to use `oi-small` when we need a smaller icon.

I'll update the branch.

**Comment by Brieuc-brd** [comment]
branch rebased + prefix changed to `[FIX]`

**Review by stefanorigano — APPROVED** [review]
LGTM, thanks @Brieuc-brd 👍

**Review by AntoineVDV — APPROVED** [review]

**Review by caburj — APPROVED** [review]

**Comment by Brieuc-brd** [comment]
Hey @odoo/rd-framework-js 👋 
This PR is ready for tech. review, could you take a look at it and r+ if it's ok for you ? :)

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
