### PR TITLE
[FIX] sale: set name on control elements for correct xpath expressions

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Allow clean and easy `xpath` expressions on `control` elements
**Note:** Why in 12.0 and not master? I consider this a fix and not an improvement as there is no truly safe way to remove one element from the `control` without removing and rebuilding the above object `control`.

Current behavior before PR: There is no clean and safe way to `xpath` into the `control` elements in V12.
There is, for example, one `create` string which is only shown - and thus in the view - when the user enabled variants:
```
<create name="configure_product_control" string="Configure a product" context="{'open_product_configurator': True}" groups="product.group_product_variant"/>
```
Imagine doing the following `xpath` where you just want to remove one `create` element from within the `control`:
```
<xpath expr="//tree/control/create[2]" position="replace">
```
In this case, the index `[2]` would get a different meaning when enabling or disabling variants, meaning that you can not do a safe index expression (which you really shouldn't ever use anyways). The only single safe way to remove one element from those controls right now is by doing an `xpath` expression on the above element `control` and rebuilding the whole control view. This is less clean, needs more code and is less future proof if there would be a change in this part of code. Example:
```
<xpath expr="//tree/control" position="replace">
    <control>
        <create string="Add a product"/>
        <create string="Configure a product" context="{'open_product_configurator': True}" groups="product.group_product_variant"/>
        <create string="Add a note" context="{'default_display_type': 'line_note'}"/>
    </control>
</xpath>
```

Desired behavior after PR is merged: By setting names on the control elements we can make a much safer, cleaner and more maintainable `xpath` expression:
```
<xpath expr="//tree/control/create[@name='add_section_control']" position="replace"></xpath>
```

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hi @mart-e,

Could you please check this PR and let me know if this is all good? If you approve this and want to merge this into V12 I'll update this PR to do the same on quotation templates. There is a similar behaviour there. Just let me know and I'll handle it.

**Comment by seb-odoo** [comment]
I'm not sure to understand the question. The related commit is: f241441433046c41e4f3edd05d5d69028da1f8a7

But to try to answer, I used context because it's generic. Adding a specific class would mean to write custom code to parse the class and execute an action based on it, when in all the use cases we needed so far, the custom code was actually to pass a context to an action anyway.

It's just what we decided to do with this feature. If it has to be changed or improved, the framework JS team is responsible of it.

**Comment by mart-e** [comment]
@seb-odoo ok I get it, the context is actually to set a field. I was expecting a js widget or something like this.

@Yenthe666 your scenario about the groups is incorrect, the xpath will apply, even on hidden elements. The expression `//field[@name='order_line']/tree/control/create[2]` will always apply on the second element, visible or not.

**Comment by Yenthe666** [comment]
Hmm, odd, I had issues with this last week where it would switch. I retested but it does seem to work now.  Perhaps because I didn't have the same xpath `(<xpath expr="//tree/control/create[2]" position="replace">` versus `//field[@name='order_line']/tree/control/create[2]`)

I still want to hold on to the fact that the elements should have names for clean `xpath` expressions though, especially when they're this deep in the chain. If this is merged I can do `//create[@name='add_section_control']`, which is so much cleaner.

**Comment by mart-e** [comment]
Thanks for the retesting. I would say
- ok to add name on `create` elements
- no need to add a name on the `control` one
- master as nothing is really blocking
- there is 4 in odoo so far, could you add it on the other ones as well so it becomes the standard? ;-)

**Comment by Yenthe666** [comment]
Okay. Done @ https://github.com/odoo/odoo/pull/30711

**Comment by Yenthe666** [comment]
Works like a charm in V13 🏆 Xpath expression for future reference if somebody else lands here:
`<xpath expr="//field[@name='order_line']/tree/control//create[@name='add_section_control']" position="replace"></xpath>`

**Pull request closed without merging**
