### PR TITLE
[IMP] base: new account are lowercased by default

### PR DESCRIPTION
**Pull request by Julien00859**
The account creation and verification was case sensitive on the login
and could cause problems for users to connect (i.e. when a server
administration creates account with random uppercases).

With this commit, newly created accounts will have a lowercase login and
the authentication tests both the user given login (preserving the case)
and lowercase counterpart to ensure backward compatibility with
previously created mixcase accounts plus ease the connection for all new
accounts.

Task: 34047

### CODE REVIEW

**Comment by Julien00859** [comment]
If two account logins convert to the same lowercase value, both are still accessible as it always use the user given login first (without case conversion)

**Comment by mart-e** [comment]
Closing as the branch was created on odoo/odoo to be able to delete the branch (but not against the feature)

**Comment by mart-e** [comment]
If I register an account with `MaRt-E` as login, I will not notice it has been lower cased and will always make 2 verifications uppon login.
Maybe, on the signup page (not the login!), we should force the lowercase version with JS.

**Comment by Julien00859** [comment]
Well actually I'm not entirely sure it is a good idea, the field is labeled email address on the view and we **[MUST](https://tools.ietf.org/html/rfc2821#section-2.4)** preserve the case of the local-part. Even if the *real* email field is correctly set using the given case, it can confuse an admin that the login (which seems to be the email address) gets lower-cased.

**Pull request closed without merging**
