### PR TITLE
[FIX] mail: failing race condition tests

### PR DESCRIPTION
**Pull request by zel-odoo**
missing last_interest_dt of channel member can
lead to unwanted unpinned channel in test due to
race condition.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
https://runbot.odoo.com/web/#id=60638&view_type=form&model=runbot.build.error&menu_id=405&cids=1
https://runbot.odoo.com/web/#id=60640&view_type=form&model=runbot.build.error&menu_id=405&cids=1

**Review by seb-odoo — APPROVED** [review]
@robodoo r+ delegate+

**Review by seb-odoo — COMMENTED** [review]
@robodoo r+

**Review by alexkuhn — COMMENTED** [review]
@robodoo r+ delegate+

**Pull request closed without merging**
