### PR TITLE
* [FIX] stock_account: create account moves and update move cost to balance reconciled negative quants

### PR DESCRIPTION
**Pull request by jmorgannz**
* [FIX] stock_account: create account moves and update stock move cost to balance reconciled negative quants

When using product valuation method = real, a purchase that reconciles negative quants should create accounting entries to adjust the entries previously created by a stock move to match the cost value reconciled.
This was not the case due to an order of execution bug.

Additionally, if product costing method = average, the move that was reconciled should also have it's cost updated to balance, but only if the account moves were created (the accounting period was not locked)

Impacted versions:
 
 - 9.0
 - 10.0
 
Steps to reproduce:

- Create a stockable product
- Set it's costing method to average
- Set it's valuation method to realtime
- Set stock in, out, and valuation accounts
- Create a purchase order for 1 item at $5.00, confirm, validate shipment
- Via the product form, change it's cost price to $5.50
- Sell 3 items via point of sale (or manually create a stock tranfser to customer of 3 and validate)
- Purchase 1 more at $10, and 2 more at $20 each (single purchase order), confirm, validate shipment.
 
Current behavior:
 
 - No additional account_move's created for original outgoing stock move
 - SUM(account_move_line.credit) for product, account_id = valuation acct is $16.5 ($5.5 x 3)
 - stock_move.cost for outgoing move = $5.5

Expected behavior:
 
 - Additional account_move's created for original outgoing stock move
 - SUM(account_move_line.credit) for product, account_id = valuation acct is $45.5 ($5.5 + $20 + $20) 
 - stock_move.cost for outgoing move = ($45.5 / 3) = 16.16667rec

__NOTE__
         Odoo appears to sometimes consume quants during negative reconciliation top-down, sometimes not.
         It's possible Odoo will consume $10 + $20 instead of the above, in which case the result will
         be the following, which is still correct.

 - Additional account_move's created for original outgoing stock move 
 - SUM(account_move_line.credit) for product, account_id = valuation acct is $35.5 ($5.5 + $10 + $20)
 - stock_move.cost for outgoing move = ($35.5 / 3) = 11.83333rec

### CODE REVIEW

**Comment by bba-odoo** [comment]
Nm

**Comment by jmorgannz** [comment]
Nm? 
Guessing you saw I made some edits? :)

**Comment by jmorgannz** [comment]
Oh, it failed CI - that's weird.
Note, this exception is not an exception in any changes I made - it is some pre-existing issue (something triggered by checking account lock date?)
It was not occurring before because of the bug that was preventing the excepting code from running.
Since I fixed that bug, this issue has arisen.

I am somewhat confused with what is causing it, however. I will investigate if I can.
It should be noted that whatever this issue is, it is unrelated to the functionality I fixed - the fix I did works.

**Comment by jmorgannz** [comment]
@bba-odoo Hi mate,
This issue appears to be with the move._check_lock_date function.
It doesn't happen for me - all works correctly.

However I thought that since this function wasn't being called before, perhaps it is out of date and needs an update, so I had a look at Odoo 10.

In Odoo 10, the function is still called in the stock_account module (same as this commit, the bug prevents it from ever actually being called)
However, the actual function appears to have been removed all together!

**Comment by jco-odoo** [comment]
I don't see where you solved the problem with the real price and in average price, I don't think there is a good solution for this, because you would need to do the impact of the average price in the past.

**Comment by jmorgannz** [comment]
Not sure what you mean. Reconciled moves are posted as real price as when
you have no stock in hand the average price _is_ the real price

**Comment by C3POdoo** [comment]
Dear @jmorgannz,

Thank you for your contribution but the version 9.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
