### PR TITLE
[FIX] hr: remove footer buttons on My Profile

### PR DESCRIPTION
**Pull request by kbapt**
The "Save" / "Cancel" buttons were wrongly showing on the "My Profile"
page.

TaskID: 2675313

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by feketemihai** [comment]
@kba-odoo Hi Kevin, we encountered some issues on databases coming from previous version, where this is failing because of the element not found, can you please check https://github.com/odoo/odoo/pull/79224.

**Comment by tau-odoo** [comment]
Hello @kba-odoo 
I have some questions for this commit.
This view inherits res_users_view_form_simple_modif.
And in res_users_view_form_simple_modif, it replaces the footer. https://github.com/odoo/odoo/blob/14.0/addons/hr/views/res_users.xml#L15
So is this part still needed?
Since I encounter an error in a database while trying to install the hr module: "Element '<footer>' cannot be located in parent view", I need to comment out this part of code in order to install the module in my localhost.
Here is a ticket from a issue database: https://www.odoo.com/web#id=2694520&menu_id=4720&cids=5&action=333&active_id=49&model=project.task&view_type=form
Please advise, thank you very much.

**Comment by kba-odoo** [comment]
Hi @tau-odoo,

Do you have steps on how I can reproduce this issue?

Thanks

**Comment by feketemihai** [comment]
@kba-odoo I added in the ticket link to https://github.com/odoo/odoo/pull/79224, where i added an unit test, so in normal situation this is blocking the update.

**Comment by feketemihai** [comment]
@kba-odoo For me it is a migrated database from previous version, like i specified in teh ticket when i created a new db with hr module this is not raised, but probably when you have more modules installed and more inheritances it is raised

**Comment by tau-odoo** [comment]
hello @kba-odoo 
It only happens for this client db: https://droneshield-support-20211116-tau1.odoo.com/ (duplicated from production). If you try to install the employee app, it will give you the error.
Related support ticket: https://www.odoo.com/web#id=2694520&menu_id=4720&cids=5&action=333&active_id=49&model=project.task&view_type=form
Thank you.

**Pull request closed without merging**
