### PR TITLE
Python 3: WIP IO/Strings/Text Model/…

### PR DESCRIPTION
**Pull request by xmo-odoo**
- [x] base64 is a bytes->bytes encoding
- [x] `csv` works on *native* strings (so bytes in P2 and text in P3), inconvenient when using `io.*IO`
- [x] werkzeug's `Response` can take bytes or text, text will be encoded with the response's charset (default UTF-8)
- [x] subprocess is bytes-based: its result(s) are bytestrings, p.stdout and p.stderr (if PIPE) are binary  (byte-based) streams
- [x] pickle.dumps(object) -> bytes, pickle.loads(bytes) -> object
- [x] ~~-> can/should (ir.values).value become a binary field?~~ yeeees
- [x] ~~are view archs text or bytes? Seem mostly manipulated as text…~~
     decided they're text, we'll see how that works out
- [x] ~~convert_xml is whack~~ still whack but removed the random encode/decode calls

### CODE REVIEW

**Comment by xmo-odoo** [comment]
Tiens ya des merdes dans les mails alors je tag @tde-banana-odoo

**Comment by xmo-odoo** [comment]
Nota: as of the round() compatibility shim, base installation and tests work, though it's not yet known whether the result works

**Comment by dreispt** [comment]
@xmo-odoo I'm curious: are all Odoo dependencies py3 compatible?

**Comment by xmo-odoo** [comment]
@dreispt Following previous fixes, yes, so far as I could find: we replaced pypdf by pypdf2, pychart was removed with the old reports and we switched out the vendored html2text for an external one, the rest seems to work, at this point I can access the web client and website running on Python 3.5 (and 3.6 with some additional fixes as there have been bytecode changes).

**Comment by odony** [comment]
@xmo-odoo regarding the safe_eval opcodes, I think `POP_EXCEPT` does belong to `_SAFE_OPCODES`. It's a counterpart to `SETUP_EXCEPT`, which only makes sense in statement contexts.
By the way, it seems `POP_BLOCK` belongs to `_SAFE_OPCODES` too, [for the same reason](https://github.com/VanL/unpyc3/blob/master/unpyc3.py#L48). People [have been adding](https://github.com/odoo/odoo/commit/d11e460296fa5ea76d2520d4d4f2355eab98a0a0) opcodes in the wrong sets.

It may be a good time to cleanup our current opcodes sets:

`_CONST_OPCODES` should only include opcodes used to declare literals: `LOAD_CONST`, `RETURN_VALUE` and `BUILD_*` (of which we currently seem to be missing `BUILD_SET`). 

`_EXPR_OPCODES` includes all opcodes that can be used to operate on literal values: all unary and binary operators, and slicing opcodes: (`UNARY_*`, `BINARY_*`, `INPLACE_*`, `SLICE+*` (py2) and `BUILD_SLICE`(py3), `STORE_MAP` (py2).

`_SAFE_OPCODES` includes the rest of the opcodes that we currently consider safe.

Not sure if you want to do this in this PR, or if we make a separate task for it...

**Comment by xmo-odoo** [comment]
@odony
> Not sure if you want to do this in this PR, or if we make a separate task for it...

Yeah there's a lot of stuff to split out of this one, right now it's only possible to run on P3 using this branch so most fixes were added to it, but there's lots of stuff which is peripheral or unrelated to the text model and I need to move to separate branches and PR, the opcodes changes is one of them.

**Comment by xmo-odoo** [comment]
Nota: split the non-text-model stuff out of this PR, created 4 other PR for broad areas of changes (possibly overly broad but 20 different PRs seems a bit much).

This means as of that update the branch doesn't run on Python 3 anymore, I haven't kept track but I think 5f43625369271bb46eea35321e2debb5131b5744 was the last commit of the pre-cleaning version which should work on 3.5 and 3.6 (modulo extant bugs in the text model & al)

**Comment by rco-odoo** [comment]
@xmo-odoo in my own branch, I adapted `jcconv` to Python 3 at https://github.com/odoo-dev/odoo/commit/60bb7967ab460a43f2b5dace11015741c66b4abf.

**Comment by xmo-odoo** [comment]
🔔

**Comment by sbidoul** [comment]
@xmo-odoo I did some (admittedly superficial) tests and things are looking good. 

The only issue I noticed so far is that the first ctrl-c does not stop the server (need to do it twice for a forced shutdown). Also `requirements.txt` needs updating.

What is the status of this PR? Is it going to be merged for v11? What will be the python version(s) officially supported by v11?

**Comment by xmo-odoo** [comment]
> The only issue I noticed so far is that the first ctrl-c does not stop the server (need to do it twice for a forced shutdown).

Under Python 2, Python 3 or both?

>  Also requirements.txt needs updating.

Which dependencies does this branch require updating?

> What is the status of this PR? Is it going to be merged for v11? What will be the python version(s) officially supported by v11?

Ask @antonylesuisse or @odony, not me.

**Comment by sbidoul** [comment]
@xmo-odoo the CTRL-C issue is with Python 3.5 on Ubuntu 16.04. It works normally with Python 2.

Regarding `requirements.txt`, besides jcconv, there is wsgiref which does not pip install under python 3. `pip install -e .` works fine. Anyway I guess it's a good moment to update `requirements.txt` with the latest stable versions of all dependencies?

**Comment by xmo-odoo** [comment]
> the CTRL-C issue is with Python 3.5 on Ubuntu 16.04. It works normally with Python 2.

OK I'll check it out, that might actually be more of a semantics change (e.g. reshuffle of the exceptions hierarchy and we're catching the wrong one).

> Regarding requirements.txt, besides jcconv, there is wsgiref which does not pip install under python 3.

I'm guessing we'll remove both from requirements, but they're a more general concern not specifically related to the IO model.

**Comment by odony** [comment]
@xmo-odoo thanks for the heavy lifting! :+1: 

I've rebased and merged this on saas-17 (as of 1492670e71d4c5d16a240f3de3be4208aae0122e) after a series of extra fixes: some typos, some new places that needed to be fixed, and a few other P3-preparation requirements (including removing the pycompat helpers for dict.keys/values/items, not useful anymore)

We can consider the huge work by @xmo-odoo completed :tada:
Saas-17 should be the first pseudo-stable branch that fully runs on Python 3.5, and @KangOl should be able to forward-port this to master next week (good luck with that!).

Now there are still quite a few leaks at the seams...
@xmo-odoo @antonylesuisse @julienlegros I expect we'll notice leftover conversion errors in the coming weeks, and the setup of a P3-enabled runbot will be essential to track them down.

In addition, here are things I noticed are still flaky with Python 3.5:
- As @sbidoul reported, shutting down the server with Ctrl-C takes longer than with P2 (it eventually finishes, if you don't force it). I think this comes from the 3.5 changes for [PEP 475](https://www.python.org/dev/peps/pep-0475), which means that workers interrupted by SIGINT silently retry their syscalls (mainly `select.select` for WorkerHTTP or `time.sleep` for WorkerCron), instead of stopping. PEP475 [highlights strategies for our use case]([url](https://www.python.org/dev/peps/pep-0475/#use-case-2-be-notified-of-signals-as-soon-as-possible)). I tried naively raising a `KeyboardInterrupt` or `socket.error(errno.EINTR, 'retry syscall')` in the signal handler, but this requires catching the exception in various places, not just those 2, and may not be the best option. Any ideas?
- Preloading a database with `-d <db>` in multithreaded mode fails unless you're in `shell` mode, at least if you have more than `base` installed. Looks like the registry gets loaded before all classes are imported or something, so registry construction bails with a missing parent model :thinking: No problem if you don't preload, or in multi-process (even w/ preload).
- I still have doubts about parts of bc7dce254dc444a30271458e71c52a317c61d4a9.
The first part of this patch initially crashed trying to mix text (base_url) and bytes (query_string). Using `URL.replace()` only delayed the problem until the reconstruction of the url string. I've tried using `iri_to_uri()` to convert the query_string to text, and it seems to works well in P2 and P3. Maybe we could use that systematically convert `request.query_string` when we need to work with URLs?

FWIW, a lame non-scientific mini-benchmark on my laptop, for a cold start install of new database w/ CRM, best of 3:
- Python 2.7.12: 65.154s
- Python 3.5.2: 66.270s

**Pull request closed without merging**
