### PR TITLE
[IMP] stock: add documentation links in stock settings

### PR DESCRIPTION
**Pull request by niyasraphy**
add documentation link for batch transfers, quality control and expiration dates in stock settings

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Whenrow** [comment]
@thomasdeleval Is it ok for you ?

**Comment by niyasraphy** [comment]
hi @thomasdeleval ,
if you have time, can you review this.
thanks

**Comment by thomasdeleval** [comment]
@Whenrow looks good to me

**Comment by Whenrow** [comment]
@niyasraphy thank you 
robodoo r+

**Pull request closed without merging**
