### PR TITLE
[REM] l10n_do: Remove lines of tax report.

### PR DESCRIPTION
**Pull request by mamcode**
**Description of the issue/feature this PR addresses:**
The current format of tax report is not useful in Dominican Republic.

**Current behavior before PR:**
current tax report

**Desired behavior after PR is merged:**
Only sections for sales and purchases as before in version 12.0
tax report v12

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by andrp92** [comment]
This is very important for Tax reporting in DR. Please consider merging and port-forwarding to newer versions.

**Comment by jco-odoo** [comment]
@mamcode Will you suggest a better tax report then?  Because in this PR, you just delete everything.  And this is the same as what we have in v12.  Maybe you can just select the generic tax report when opening the tax report instead of the specific DO one.

**Comment by mamcode** [comment]
> @mamcode Will you suggest a better tax report then? Because in this PR, you just delete everything. And this is the same as what we have in v12. Maybe you can just select the generic tax report when opening the tax report instead of the specific DO one.

Thanks for your quick answer @jco-odoo Please can you tell me how to generate the report in a generic way?

**Comment by mamcode** [comment]
@jco-odoo I already saw how to solve it functionally, we will discuss it internally in the team to see if this PR makes sense. 
screenshot-localhost_7777-2021 02 25-11_56_00

**Pull request closed without merging**
