### PR TITLE
[FIX] mrp_account: fix reference to a deleted bom line

### PR DESCRIPTION
**Pull request by agr-odoo**
- Enable Margin analysis
- Have a product [TEST] in a category with
  - FIFO and Automated Valuation.
  - Kit BOM with 3 items (A,B,C)
- Create a SO with [TEST] and confirm.
- Modify the BOM and remove C from the kit.
- Back to the SO, cancel it.

Traceback will show, because there no more a bom_line associated with
the move

opw-2541674

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@nle-odoo 
It seems a good way to keep the value consistent as `super()._compute_average_price(qty_invoiced, qty_to_invoice, stock_moves)` would possibly return `0.0`

**Review by nle-odoo — APPROVED** [review]
looks good

so on the new call to _compute_average_price, we will call:

```py
super()._compute_average_price(qty_invoiced, qty_to_invoice, stock_moves)
```

maybe this could be refactored a little more, like:

```diff
diff --git a/addons/mrp_account/models/product.py b/addons/mrp_account/models/product.py
index 40092da8f5b..3c299559d86 100644
--- a/addons/mrp_account/models/product.py
+++ b/addons/mrp_account/models/product.py
@@ -52,9 +52,12 @@ class ProductProduct(models.Model):
         value = 0
         for move in stock_moves:
             bom_line = move.bom_line_id
-            bom_line_data = bom_lines[bom_line]
-            bom_line_qty = bom_line_data['qty']
-            value += bom_line_qty * move.product_id._compute_average_price(qty_invoiced * bom_line_qty, qty_to_invoice * bom_line_qty, move)
+            if bom_line:
+                bom_line_data = bom_lines[bom_line]
+                line_qty = bom_line_data['qty']
+            else:
+                line_qty = move.product_qty
+            value += line_qty * move.product_id._compute_average_price(qty_invoiced * line_qty, qty_to_invoice * line_qty, move)
         return value
```

but maybe it makes more sense to have two calls

it might also be useful to explain when you can not have bom_line in code (from commit message: when bom line is removed after it was used)

robodoo delegate+

**Comment by nle-odoo** [comment]
Hi @Whenrow 


I think you have had comment about a PR on similar code: https://github.com/odoo/odoo/pull/68397

Functionally I have not much idea of what we are expecting here, what do you think about this fix? Thanks.

**Comment by Whenrow** [comment]
@nle LGTM. The PR you are referring to try to fix something else of which I am not convinced of the relevance. Thanks

**Comment by Whenrow** [comment]
@nle-odoo wrong ping

**Review by Whenrow — APPROVED** [review]

**Comment by agr-odoo** [comment]
thanks to for review(s)!
robodoo r+

**Pull request closed without merging**
