### PR TITLE
[FIX] website_event_track: reduce cell height and fix scroll bar

### PR DESCRIPTION
**Pull request by Brieuc-brd**
## Reduce cell height and fix scroll bar 
This PR optimizes the cell height by moving the bell icon next to the tags and reduces the gap between cells.

This PR also allows to have a fixed horizontal scroll bar when an agenda has hidden content. This removes the need to go to the bottom of the agenda to scroll horizontally.

## Add location in track list
This PR adds the missing location for each talk in the track list (/track).

task-4086340

---

### Moving the bell icon and reducing the gap

| Before | After |
|--------|--------|
| Capture d’écran 2024-08-01 à 11 35 52 | Capture d’écran 2024-08-01 à 11 35 36 |

### Fixed scroll bar

| Before | After |
|--------|--------|
| Capture d’écran 2024-08-01 à 11 39 32 Horizontal scroll bar not visible | Capture d’écran 2024-08-01 à 11 40 29 Fixed horizontal scroll bar |

### Add location in track list
| Before | After |
|--------|--------|
| Capture d’écran 2024-08-02 à 14 38 52 | image |

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by awa-odoo** [comment]
Hello @Brieuc-brd 

Heard this was an urgent PR and gave it a quick look.

That seems like a large amount of heavy JS processing to display a few scrollbars.
Is there really no way to adapt the XML / CSS to take advantage of natural scrolling of containers here?

**Comment by Brieuc-brd** [comment]
Hey @awa-odoo 👋 
Thank you for taking care of this PR 🙏 .
Unfortunately, we've spent a lot of time looking for a lighter solution, but this is the best compromise we've found.
Perhaps you could help us optimize the code to make it even lighter?

cc. @stefanorigano

**Comment by awa-odoo** [comment]
Hello @Brieuc-brd 

This one gave me a bit more trouble than expected but I think I got something:
https://github.com/odoo-dev/odoo/commit/9ad8546fb17724be5c5c6f90006fed233d53aaa3

The main differences:
- Only one scroll listener instead of 3
- Only one extra scrollbar element instead of 3
- The listener dynamically assigns the "agenda to scroll"
- No longer attached to "wrapwrap" widget
- (Usage of tooling debounce instead of manually re-implementing it)
- (Globally lighter and more readable code)
- (Usage of XML elements and scss files instead of JS coded elements and styling)

One downside I noticed with this approach is if you scroll all the way down, the extra scrollbar lasts for an extra 50 ms before disappearing and is at the end of the event agendas container instead of at the end of the whole HTML page, so it looks a bit misplaced.
If that is an issue, you can try to place the bar better inside that container.
If that is still an issue, you can manually add the bar to the wrapwrap container instead of the XML with JS (a bit like your current version does), but that's really not pretty.

Can I ask you to test my approach a bit more extensively?
If that's suitable, you can push-force your branch with it and we will proceed :slightly_smiling_face: 

Thanks & cheers!

**Comment by Brieuc-brd** [comment]
@awa-odoo 👋 
I've tested it, thanks a lot for your work! 💪 
I just made some small adjustments: https://github.com/odoo/odoo/compare/26340bf3f7ce8a1b8bfcb18b1b45615e7faffd88..14cdb83937881feb11999152a7f7aa522328775b 
For the rest LGTM 🟢 

Thanks again! 🙏

**Comment by Brieuc-brd** [comment]
As discussed, I've added the missing location into the track list in a new commit.
I'm waiting for 🟢  on runbot before asking a technical review :)

**Comment by awa-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by awa-odoo** [comment]
@robodoo delegate=@Brieuc-brd

**Pull request closed without merging**
