### PR TITLE
[FIX] web: use user timezone instead of browser timezone. 

### PR DESCRIPTION
**Pull request by alpham**
Description of the issue/feature this PR addresses:

Current behavior before PR:
In calendar view the view when you create new event, the `start` and `stop` values of `calendar.event` object are calculated based on web browser timezone and the `timezone` configuration of current logged in user is ignored.  

Desired behavior after PR is merged:
All events should be calculated according to `timezone`  field under `User/Preferences`

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Why is it bad to consider the browser's timezone? It is the one the current user is after all. You don't expect the user to change its timezone in the user profile every time he travels.

Could you describe your changes? You are adding a new library?

**Comment by alpham** [comment]
considering the browser's timezone implicitly is very confusing to user as well as the developer.
the user is usually an employee, the configurations on the screen tells him that time zone is (for example) `US/Eastern` while he's in `Africa/Cairo` timezone, all datetimes will be calculated according to the place he is based in, which is confusing because his preferences is something else.
me myself had this issue when I was working with an American company while I'm in Egypt/Cairo, and tried to configure the timezone of the system to mach the company working times.

**Comment by alpham** [comment]
about the changes, this is not a library, it's extension to `moment.js` to allow converting time to any timezone  https://momentjs.com/timezone/
The change is simple, instead of returning the timezone offset of web browser's timezone I retrieve time zone of current logged in user according to his/her preferences.

**Comment by pedrobaeza** [comment]
@alpham you are including a lot of files (that I suspect they are backup copies) in the PR.

I agree on the principle of respecting user tz preference.

**Comment by alpham** [comment]
@pedrobaeza could you please determine which files you mean?
the javascript files are the same from `npm` package I didn't remove either source files or minified files to allow debugging assets.
which files should I remove ?

**Comment by C3POdoo** [comment]
Dear @alpham,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
