### PR TITLE
[UPD] unnaccent Japanese prefectures

### PR DESCRIPTION
**Pull request by yostashiro**
### Description of the issue/feature this PR addresses:

Very few people in Japan know how to type accented characters, which brings a usability issue when the Japanese prefectures are defined with accented characters.

@qrtl

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yostashiro** [comment]
@mart-e Would you be able to process this?

**Comment by mart-e** [comment]
@yostashiro sure, could you check our commit guidelines for the commit message content?
https://www.odoo.com/documentation/13.0/reference/guidelines.html#commit-message-structure
Thanks

**Comment by yostashiro** [comment]
@mart-e Thank you. Is the commit message OK now?

**Comment by mart-e** [comment]
Thanks for the change, it was almost correct. I just changed to

- add an empty line between the title and description (makes one a long title on several git client otherwise)
- break description lines after 80 characters (don't want to scroll horizontally)

@robodoo r+

**Pull request closed without merging**
