### PR TITLE
update the Social Security ceiling amount

### PR DESCRIPTION
**Pull request by fabienmorin**
the previous amount was for 2011 update it with 2016 value, see https://fr.wikipedia.org/wiki/Plafond_de_la_S%C3%A9curit%C3%A9_sociale#Historique_des_valeurs

### CODE REVIEW

**Comment by mart-e** [comment]
I guess you want to merge that in 8.0 and not 9.0, right ?

**Comment by mart-e** [comment]
Applied the changes to 8.0 at 0f46e6a
Thanks

**Comment by fabienmorin** [comment]
Il like to propose on both if it's possible. I'm working in all versions since OpenERP 6, so maybe I will have proposal for both 8 et 9 in the future (but I'm quite beginner with the contribution procedures, so maybe I didn't did it the right way).

**Comment by mart-e** [comment]
No need to create multiple PR, see [contributing page](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch)

> Fixes made in supported versions (currently 7.0, 8.0, 9.0 + the last saas-x branch) will be forward ported to later versions periodically. No need to create a pull request for master if there is one for 8.0, for example.

**Pull request closed without merging**
