### PR TITLE
[FIX] web: fix alignment issue for feature names

### PR DESCRIPTION
**Pull request by dhrs-odoo**
Issue:
- Before this PR when we see helpdesk team form view some of the features names are not aligned with checkbox

Cause:
- Issue was caused because of the icon size is large and so it features names were not aligned

FIX:
- we have reduced the size of the icon so that text get aligned with the checkbox

task-3463622

### CODE REVIEW

**Review by pkyriakou — COMMENTED** [review]
Thank you @dhrs-odoo for your fix. 
I have nothing to comment on but it will have to be looked at by the framework team before when reviewed because the change affects things outside our scope

**Review by auon-odoo — APPROVED** [review]

**Comment by xavierbol** [comment]
LGTM, I will let @odoo/rd-framework-js doing the final review of that tiny styling changes. 🙂

**Review by pparidans — CHANGES_REQUESTED** [review]
First of all, could you rebase this branch as it is 1000+ commits behind ?

Also, I'm not sure this is the right fix... and, why "0.9rem" ? :thinking:

**Comment by dhrs-odoo** [comment]
Hello @pparidans 
Issue was caused because of the icon size is large compared to previous versions and so because of that features names are not aligned and at 0.9 rem icon size seems good

**Comment by pparidans** [comment]
> Hello @pparidans Issue was caused because of the icon size is large compared to previous versions and so because of that features names are not aligned and at 0.9 rem icon size seems good

And what about removing the `font-size` rule altogether (so it adapts to the current font size) ?

**Comment by dhrs-odoo** [comment]
Hello @pparidans Yaa its adapting the current font size

**Comment by xavierbol** [comment]
Hello @dhrs-odoo ,

The question is if we remove the `font-size` rule, does it fix the issue? If yes, then we can remove it instead of setting a "magic" font-size. 🙂

**Comment by dhrs-odoo** [comment]
> Hello @dhrs-odoo ,
> 
> The question is if we remove the `font-size` rule, does it fix the issue? If yes, then we can remove it instead of setting a "magic" font-size. 🙂

I have removed the font-size rule as it is working fine and fixes the issue 
Thank You :innocent:

**Comment by xavierbol** [comment]
Hello @pparidans ,

I guess now we are good? 🙂

**Review by pparidans — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
