### PR TITLE
[FIX] base: lazy load external files if part of a lazy loaded bundle

### PR DESCRIPTION
**Pull request by qsm-odoo**
In the payment_adyen module, two files of adyen are added as part of the
assets_frontend bundle. That bundle is lazy loaded on the website... but
those two external files, as not added within the bundle itself, were
not. This commit fixes that, properly lazy loading "remaining" files
out of a lazy loaded assets bundle.

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@Arcasias Are you the right one to ping to merge this? :)

**Comment by qsm-odoo** [comment]
Validated by VCR that the payment_adyen module still works properly with this :+1:

**Comment by qsm-odoo** [comment]
Ping @Arcasias

**Review by Arcasias — APPROVED** [review]
Sorry, didn't see the notification for the first ping.
LGTM, but I don't have the rights to merge this

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by d-fence** [comment]
robodoo r-
Wait for freeze please
@Xavier-Do ping retarget

**Comment by qsm-odoo** [comment]
@d-fence Sure, sorry, just though that at worst this would be blocked and I would have re-targeted later by myself :)

**Comment by Xavier-Do** [comment]
> @d-fence Sure, sorry, just though that at worst this would be blocked and I would have re-targeted later by myself :)

Don't worry, it is just a standard message as a reminder for us ;)

**Review by qsm-odoo — COMMENTED** [review]
@robodoo r+

**Review by qsm-odoo — COMMENTED** [review]
@robodoo r+

**Pull request closed without merging**
