### PR TITLE
[FIX] l10n_it_edi_sdicoop: relocate relevant tests

### PR DESCRIPTION
**Pull request by dbkosky**
Tests that were added to l10n_it_edi for price included taxes and
discounted invoices a0a8bdf should actually belong in
l10n_it_edi_sdicoop (partially because of the requirement for the proxy
user when l10n_it_edi_sdicoop is installed). This disctinction will
eventually be irrelevant in master as the two modules should be merged
together eventually.

### CODE REVIEW

**Comment by dbkosky** [comment]
@jco-odoo This PR is specific to 14.0 (Where the tests are already merged). Otherwise there's this PR https://github.com/odoo/odoo/pull/88687, which does the tests as they are needed in 15.0 onwards.

**Comment by dbkosky** [comment]
@jco-odoo .. can we merge this so that I can write tests for https://github.com/odoo/odoo/pull/88816 ?

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by dbkosky** [comment]
@fw-bot ignore

**Pull request closed without merging**
