### PR TITLE
[FIX] translate: inline elements with translatable attributes only

### PR DESCRIPTION
**Pull request by rco-odoo**

### CODE REVIEW

**Comment by rco-odoo** [comment]
@juliendecoster

**Comment by rco-odoo** [comment]
@Julien00859

**Comment by Julien00859** [comment]
I applied your fix on my branch, did a fresh install of the modules and generated a new pot file. The new new pot file doesn't show any new span as msgid, is that normal ?

**Comment by mart-e** [comment]
It looks good. However, I tried rexeporting the translations before and after your patch and had no changes. Is it possible in v11 there is not such strings?

**Comment by Julien00859** [comment]
The bug is mostly due to tooltips on font-awesome images. I did a quick grep/blame on "Values here are company-specific" and all of them are from commits the following commits:

a183a5125a33
9de1bc0eef6f
358f050555b7
9de1bc0eef6f
53cdd68e7cc9
a183a5125a33
9de1bc0eef6f
772bebede53c
83820a898f97
9de1bc0eef6f
710f67ad4b5f
9de1bc0eef6f
e38ed7c780d3
9de1bc0eef6f
2fa469c5e5ec
9de1bc0eef6f
4c31a758cf07
53cdd68e7cc9

All done in 2018

**Comment by mart-e** [comment]
This patch does create the translations as expected but when exporting, I still don't get these parts, to investigate...

**Comment by mart-e** [comment]
So the patch does work for the xml_translation but has no impact on the generations of the translation file.

The reason we need #29398 seems to be linked at 40efdccc3d1e1f070c9d9588b2220c8e38d6432f
There, we wanted to explicitly discard the small words from the translations. However, this should probably be done in the xml_translate method directly, where we verify each node.

I have made a try at d39a5a9bad3, could this be a solution?

**Comment by rco-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
