### PR TITLE
[IMP] update module names 

### PR DESCRIPTION
**Pull request by niyasraphy**
Description of the issue/feature this PR addresses: currently there is some modules still with the name in the manifest as its technical name, updated those module names to generic names

Current behavior before PR: module names with technical name in manifest

Desired behavior after PR is merged: Better module names

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
@epictete Hi, if you have some time, can you look at this PR

**Comment by tivisse** [comment]
Note: This actually breaks the translations

**Comment by niyasraphy** [comment]
@tivisse so let me update the PR with pot files or what you recommend ?

**Review by william-andre — COMMENTED** [review]
> so let me update the PR with pot files or what you recommend ?

Cosmetic changes like this should only be done in `master`, no need to update the translation files there

**Comment by niyasraphy** [comment]
@william-andre thanks for the feedback, 
So i will close this and will create PR for the master.
Thanks

**Comment by niyasraphy** [comment]
closing this pr, as new pr is create targeting the master.

**Pull request closed without merging**
