### PR TITLE
[12.0][FIX] stock: act_product_location_open

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Description of the issue/feature this PR addresses:
This PR is intended to fix an issue when opening the Product list from inside a Stock Location.

Current behavior before PR:
Accessing list of Products show all products even if they have no quantity on hand or forecasted quantity in that specific location.
image

This is due to search view not being correctly chosen since there are two search views for the model product.product and both have same sequence.
image

Desired behavior after PR is merged:
Only products that have quantity on hand and forecasted quantity greater than 0.0 are shown.
image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
ping @sle-odoo

**Comment by sle-odoo** [comment]
why does replacing act_window by a record fixes the issue?

**Comment by AdriaGForgeFlow** [comment]
> why does replacing act_window by a record fixes the issue?

Because you can specify the search view to use in the record.

**Comment by C3POdoo** [comment]
Dear @AdriaGForgeFlow,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
