### PR TITLE
[FIX] test_new_api: use a proper patch

### PR DESCRIPTION
**Pull request by Xavier-Do**
The tour test_01_admin_widget_x2many was failing because of a missing discussion. This discussion was in fact coming from a patch during at install tests

This wasn't detected on runbot during merge since at_install and post_install are executed in different builds. This was detected during the nightly "all no auto tag" build.

Simply use a proper patch to avoid keeping the default value at the end of the test.

Prefer diff without whitespace:
https://github.com/odoo/odoo/pull/100491/files?w=1

### CODE REVIEW

**Review by std-odoo — APPROVED** [review]
Sorry, thanks for the fix :)

**Review by xmo-odoo — COMMENTED** [review]
Maybe use the "manual" form of the API to avoid having to reindent everything, which adds a lot of noise ot the default display? By manual I mean `patcher.start()` and `addCleanup(patcher.stop)`.

Also keeping the lambda (rather than converting it to a named function) seems fine.

**Comment by Xavier-Do** [comment]
> Maybe use the "manual" form of the API to avoid having to reindent everything, which adds a lot of noise ot the default display? By manual I mean `patcher.start()` and `addCleanup(patcher.stop)`.

Yes I had the same idea to avoid blaming some code but using a context manager is IMHO cleaner and less error prone.
I prefer add the tabulation and give a correct example rather than a hack.  With the manual way, lets rework/copy this test and forgot the addCleanup and it's broken again. Its is impossible to forgot the __exit__ of a context manager.
 
> Also keeping the lambda (rather than converting it to a named function) seems fine.

I  prefer the def version. And it also suites the unnecessary-lambda-assignment pylint rule.

**Comment by xmo-odoo** [comment]
> Yes I had the same idea to avoid blaming some code

It's less about blame and more about the patch being 99% chaff.

> but using a context manager is IMHO cleaner and less error prone.

In new code? 100%. When fixing old code? Less so.

> I prefer the def version. And it also suites the unnecessary-lambda-assignment pylint rule.

That makes no sense, there's no assignment, the lambda is being passed to `patch.object`.

**Comment by Xavier-Do** [comment]
> That makes no sense, there's no assignment, the lambda is being passed to `patch.object`.
Line would be slightly too long. I personally prefer this code structure.

> It's less about blame and more about the patch being 99% chaff.
> In new code? 100%. When fixing old code? Less so.

chaff?
Just opinions here, it is just a test and I personally prefer the current solution.

**Comment by d-fence** [comment]
robodoo r+
at least this annoying bug is fixed
Let's move on

**Pull request closed without merging**
