### PR TITLE
[FIX] web: remove duplicated entry in field_registry

### PR DESCRIPTION
**Pull request by aab-odoo**
Commit 4960453d added the field signature in field_registry.js and
in signature.js.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo retry

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
fuck you robodoo

**Comment by ged-odoo** [comment]
robodoo retry retry+ r+ do your job

**Comment by ged-odoo** [comment]
robodoo please

**Comment by ged-odoo** [comment]
thank you robodoo. you are the best

**Pull request closed without merging**
