### PR TITLE
[CLA] signature for SMART Outsourcing & Business Consulting

### PR DESCRIPTION
**Pull request by smartobc-stephen**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr.

### CODE REVIEW

**Comment by smartobc-stephen** [comment]
The changes I want to deliver a PR for, is in the enterprise edition and to my knowledge, the enterprise repo does not have a /doc/cla folder. This CLA will cover contributions in there too correct?

**Comment by mart-e** [comment]
@smartobc-stephen your enterprise PR is for 17, right? In doubts, you can make the PR for the lowest version (15.0 and we will port it to upperversions)

**Comment by smartobc-stephen** [comment]
@mart-e Yes, that is correct. I just send in the pr, it's odoo/enterprise#64862. It's my first (ever). To my knowledge, this issue affects 17, 16 and 15 partially. It seems my pr is blocked for now. Do I have to do something else for the cla signature to be accepted?

**Comment by mart-e** [comment]
@smartobc-stephen if the issue is present before 17.0, you can target the lowest supported version where the issue occures and we will port it to upper versions.

**Comment by smartobc-stephen** [comment]
@mart-e Also, will the pr review continue automatically after this is done or how can I rerun the status checks in the pr from my side? I had the same issue in here, that is why there are 2 commits. I had my email set to private and one of the status checks failed because the private email did not match the one git uses for merges etc.

Are you saying that I **must** target the lower versions or it is optional?

**Comment by mart-e** [comment]
> Are you saying that I must target the lower versions or it is optional?

Our process is that when a PR is merged into Odoo, the commit is applied to every version _above_, until master. So if you make your PR in 17.0, it will be included in 17.0 and master but not in 15.0 and 16.0. So if you need the patch in those versions as well, yes, you must do it in the lowest version.

> will the pr review continue automatically after this is done or how can I rerun the status checks in the pr from my side

I let @odoo/rd-hr review odoo/enterprise#64862 but, once your CLA pr will be merged, the ci/cla will pass. It’s automatic and you can’t really re-run it (or your need to rebase your branch if you want to recompute it).

**Comment by smartobc-stephen** [comment]
@mart-e  Ok, I will close that pr and adjust the fix for odoo 16 so it can be forward-ported to odoo 17.

**Comment by smartobc-stephen** [comment]
I will link the pr #64951 here to see if it helps.

**Comment by mart-e** [comment]
@smartobc-stephen so you need to sign the CLA for 16.0 if you want to merge odoo/enterprise#64951

**Comment by smartobc-stephen** [comment]
@mart-e  Can I close this pull request then? I would like to get the CLA for odoo 17.0 signed now and not go through this process again. However I have mistakenly merged the upstream branch of 17.0 with my branch of 17.0. Do I revert and then rebase? Won't the ci/minimal status check still fail?

**Comment by mart-e** [comment]
Replaced by #172203

**Pull request closed without merging**
