### PR TITLE
14 booking app available court

### PR DESCRIPTION
**Pull request by panzerhong**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
I guess you didn't want to make this here?

**Comment by rco-odoo** [comment]
@yinmazatin I guess you clicked the wrong button :wink:

**Comment by pedrobaeza** [comment]
You can however contribute that modules to OCA: https://odoo-community.org/page/Contribute

**Comment by yinmazatin** [comment]
Yes pardon , for clicking the wrong button.
I would like to be the contributor of odoo. Please guide me

**Comment by pedrobaeza** [comment]
Odoo doesn't accept such contributions at new apps level. OCA does.

**Comment by yinmazatin** [comment]
May you guide how i can be the contributor of odoo community

**Pull request closed without merging**
