### PR TITLE
[FIX] stock: Prevent deletion of Lot Serial if exists moves

### PR DESCRIPTION
**Pull request by rda-odoo**
If moves exist then we can't delete serial number

### CODE REVIEW

**Comment by rha-odoo** [comment]
LGTM

**Comment by moylop260** [comment]
:+1:

**Comment by moylop260** [comment]
Fix https://github.com/odoo/odoo/issues/4458

**Comment by mart-e** [comment]
Merged at cb3034b.
Thanks for the patch and the review

**Pull request closed without merging**
