### PR TITLE
[FIX] tools: XSD: handle ZIP files with URL not ending in .zip

### PR DESCRIPTION
**Pull request by antoine162**
In the case of the Basque country EDI, the ZIP archive containing the XSD files is located at
https://www.gipuzkoa.eus/documents/2456431/13761107/Esquemas+de+archivos+XSD+de+env%C3%ADo+y+anulaci%C3%B3n+de+factura_1_2.zip/2d116f8e-4d3a-bff0-7b03-df1cbb07ec52 which does not end in .zip due to the hash at the end.

The current mechanism for detecting whether the file is an XSD or a ZIP does not handle this, so the ZIP can't be downloaded.

This is the only case we have encountered where the URL does not end in .xsd or .zip.
We therefore prefer to just slightly adjust the mechanism for detecting the file type, rather than complicate things more.

If this happens in many more cases, we might consider adding a parameter to `load_xsd_files_from_url` that explicitly indicates the file type.

### CODE REVIEW

**Comment by antoine162** [comment]
hi @odoostan this should address the issue you mentioned in https://github.com/odoo/odoo/pull/115720

**Comment by jco-odoo** [comment]
@xmo-odoo Something like: 

```
try:
    archive = zipfile.ZipFile(BytesIO(content))
except zipfile.BadZipFile:
    _logger.info("ZIP archive could not be read")
    return False
```?

**Comment by antoine162** [comment]
@xmo-odoo If it was a common problem, I would definitely implement your suggestion, or simply pass the type explicitly as a parameter (which is feasible since the programmer knows what kind of file to expect). 

But this is just a single case. I was thinking we can just not complicate things, and leave the extra development for the day when it actually becomes necessary.

**Comment by antoine162** [comment]
@xmo-odoo thanks so much, I do agree with your point that the extension heuristic doesn't make sense :+1:

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
