### PR TITLE
Correct the zipcode data in China City Data

### PR DESCRIPTION
**Pull request by wllbll**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

Description of the issue/feature this PR addresses:
Found un-acceptable mistakes in current zip code in res_city_data.xml , which will frustrate user when editing address in China.

Current behavior before PR:
Zip code data was wrong in some province , eg Sichuan Province, Guangdong Province, etc

Desired behavior after PR is merged:

Correct the data, event that zip code in this pull request is not precise, whereas they are not wrong(after random check)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@jco-odoo can you handle that?

@wllbll thanks for the contribution. Would you mind reworking the commit history to have one commit with your CLA and one with the actual change (no merge commits) ?

**Comment by jco-odoo** [comment]
@mart-e @wllbll Is there a way to reduce the diff by keeping the same order in the file?

**Comment by qdp-odoo** [comment]
let's face it: there was some delay on this PR already, and I think we can stop waiting for anyone to confirm the content. I did, very quickly: seems ok.

@robodoo r+

@wllbll thanks for the contribution!

**Comment by qdp-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
