### PR TITLE
[IMP] Project: enhance rating labels 

### PR DESCRIPTION
**Pull request by rari-odoo**
This task involves improving the labels to better
distinguish their functionality based on their use.

task-3513873

### CODE REVIEW

**Review by MissingNoShiny — APPROVED** [review]
LGTM, thanks :slightly_smiling_face:

**Review by auon-odoo — APPROVED** [review]

**Review by xavierbol — COMMENTED** [review]
robodoo r+

**Review by xavierbol — COMMENTED** [review]
robodoo r+ 

I just rebased your branch.

**Comment by xavierbol** [comment]
robodoo r-

**Review by xavierbol — COMMENTED** [review]
Thanks. 🙂 

robodoo r+

**Pull request closed without merging**
