### PR TITLE
Doc-building error

### PR DESCRIPTION
**Pull request by xmo-odoo**
758382b3a73da024d6e1dc04a474d2868223767a missed a few P2 constructs when it removed compatibility.

### CODE REVIEW

**Comment by xmo-odoo** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
robodoo retry

**Comment by xmo-odoo** [comment]
@mreficent that's true

**Comment by xmo-odoo** [comment]
robodoo retry

**Pull request closed without merging**
