### PR TITLE
[REF] account: Faster read_group for _compute_matched_percentage method

### PR DESCRIPTION
**Pull request by moylop260**
Running a process to create too many account.move records is spent too much time.

I just get pyflame file and the SVG result is:
https://gist.github.com/moylop260/89e7703cd004485c044959f029af8423

One of most consumed method is
https://github.com/odoo/odoo/blob/9553240adc4a29d7b61d63708a53cbb612c0e123/addons/account/models/account_move.py#L44-L62

Using the following line for all move_lines is too slow compared with a faster domain:
https://github.com/odoo/odoo/blob/9553240adc4a29d7b61d63708a53cbb612c0e123/addons/account/models/account_move.py#L53

it PR is using read_group to improve the performance.

Related issue:
 - https://github.com/odoo/odoo/issues/30934

OPW: 1938216

# NORMAL
```bash
Wrote profile results to odoo-bin.lprof
Timer unit: 1e-06 s

Total time: 18.0225 s
File: /home/odoo/odoo-12.0/addons/account/models/account_move.py
Function: _compute_matched_percentage at line 45

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    45                                               @api.depends('line_ids.debit', 'line_ids.credit', 'line_ids.matched_debit_ids.amount', 'line_ids.matched_credit_ids.amount', 'line_ids.account_id.user_type_id.type')
    46                                               @profile
    47                                               def _compute_matched_percentage(self):
    48                                                   """Compute the percentage to apply for cash basis method. This value is relevant only for moves that
    49                                                   involve journal items on receivable or payable accounts.
    50                                                   """
    51      1000      14962.0     15.0      0.1          for move in self:
    52       500       4456.0      8.9      0.0              total_amount = 0.0
    53       500       4362.0      8.7      0.0              total_reconciled = 0.0
    54      3288     581960.0    177.0      3.2              for line in move.line_ids:
    55      2788    9528924.0   3417.8     52.9                  if line.account_id.user_type_id.type in ('receivable', 'payable'):
    56       500      17792.0     35.6      0.1                      amount = abs(line.debit - line.credit)
    57       500       4796.0      9.6      0.0                      total_amount += amount
    58       627    7181040.0  11453.0     39.8                      for partial_line in (line.matched_debit_ids + line.matched_credit_ids):
    59       127     246676.0   1942.3      1.4                          total_reconciled += partial_line.amount
    60       500     433018.0    866.0      2.4              precision_currency = move.currency_id or move.company_id.currency_id
    61       500       4477.0      9.0      0.0              continue
    62                                                       if float_is_zero(total_amount, precision_rounding=precision_currency.rounding):
    63                                                           move.matched_percentage = 1.0
    64                                                       else:
    65                                                           move.matched_percentage = total_reconciled / total_amount
```

# OPTIMIZED
```bash
Timer unit: 1e-06 s

Total time: 12.4594 s
File: /home/odoo/odoo-12.0/addons/account/models/account_move.py
Function: _compute_matched_percentage at line 45

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    45                                               @api.depends('line_ids.debit', 'line_ids.credit', 'line_ids.matched_debit_ids.amount', 'line_ids.matched_credit_ids.amount', 'line_ids.account_id.user_type_id.type')
    46                                               @profile
    47                                               def _compute_matched_percentage(self):
    48                                                   """Compute the percentage to apply for cash basis method. This value is relevant only for moves that
    49                                                   involve journal items on receivable or payable accounts.
    50                                                   """
    51      1000      17226.0     17.2      0.1          for move in self:
    52       500      12069.0     24.1      0.1              aml_rec_pay = self.env['account.move.line'].search([
    53       500       7699.0     15.4      0.1                  ('move_id', '=', move.id),
    54                                                           ('account_id.user_type_id.type', 'in', ('receivable',
    55       500    8424557.0  16849.1     67.6                                                          'payable'))])
    56       500       8446.0     16.9      0.1              if not aml_rec_pay:
    57                                                           continue
    58       500       5606.0     11.2      0.0              aml_rec_pay_res = aml_rec_pay.read_group(
    59       500       8265.0     16.5      0.1                  [('id', 'in', aml_rec_pay.ids)],
    60       500    2367477.0   4735.0     19.0                  ['debit', 'credit'], [])[0]
    61       500       6195.0     12.4      0.0              total_amount = abs(
    62       500       6369.0     12.7      0.1                  (aml_rec_pay_res.get('debit') or 0) -
    63       500       6788.0     13.6      0.1                  (aml_rec_pay_res.get('credit') or 0))
    64
    65       500       8080.0     16.2      0.1              domain = ['|', ('credit_move_id', 'in', aml_rec_pay.ids),
    66       500       7347.0     14.7      0.1                        ('debit_move_id', 'in', aml_rec_pay.ids)]
    67       500      15813.0     31.6      0.1              total_reconciled = self.env['account.partial.reconcile'].read_group(
    68       500    1085314.0   2170.6      8.7                  domain, ['amount'], [])[0]['amount'] or 0
    69       500     466781.0    933.6      3.7              precision_currency = move.currency_id or move.company_id.currency_id
    70       500       5366.0     10.7      0.0              continue
    71                                                       if float_is_zero(total_amount, precision_rounding=precision_currency.rounding):
    72                                                           move.matched_percentage = 1.0
    73                                                       else:
    74                                                           move.matched_percentage = total_reconciled / total_amount
```

### CODE REVIEW

**Comment by moylop260** [comment]
@jev-odoo
Here there is another performance issue with the same process from https://github.com/odoo/odoo/pull/31014


If you will test it maybe you like take a look for this one too.
Regards!

**Comment by moylop260** [comment]
In order to test this patch I just ran the following script:
 - `env['account.move'].search([])._compute_matched_percentage()`
 - Since that it is a computed field `store=True` then I just saw `UPDATE account_move SET matched_percentage ...` sentences.

I got the result before & after this patch running:
`psql MY_DATABASE -c "SELECT id, matched_percentage FROM account_move ORDER BY id ASC" > ~/matched_percentage`

Then I compared them and the diff is zero for all records in the field matched_percentage.
Database with 202,103 account_move_lines

**Comment by moylop260** [comment]
The real and depth fix is:
 - https://github.com/odoo/odoo/pull/31014

**Comment by pedrobaeza** [comment]
Are you sure this is not a real improvement? I had a lot of troubles with this method when computing a large amount of data.

**Comment by moylop260** [comment]
For my case, main issue is another process calling too much times this method

After fixed it I saw reduced 2 seconds to compute in my test

I will back to check this patch if I find a case of use with a big improvement to compute this method.
If you have a case of use I can test it.

**Comment by pedrobaeza** [comment]
My use case is while migrating a v11 database, where this field is computed being a new one, and it takes hours for being completed.

**Pull request closed without merging**
