### PR TITLE
[I18N] *: Update translation terms from Transifex

### PR DESCRIPTION
**Pull request by mart-e**
Except Spanish, waiting for cleanup

### CODE REVIEW

**Comment by mart-e** [comment]
@robodoo r+
@fw-ignore

**Comment by pedrobaeza** [comment]
We are always the excluded ones :stuck_out_tongue_closed_eyes:

**Comment by mart-e** [comment]
@pedrobaeza still waiting for the cleanup from Transifex support team ;-)

I mean
@fw-bot ignore

**Comment by pedrobaeza** [comment]
Yeah, it was a quick joke, don't worry.

**Pull request closed without merging**
