### PR TITLE
[FIX] website_sale: remove redundant order definition

### PR DESCRIPTION
**Pull request by wtaferner**
As the order on the product itself is destroying the functional sequence
in the backend of the module product (handle widget is ineffective on
the view) and is individually set since 4dce861 for its original
purpose, it should not be of any risk to remove the redefinition of
product order for website sale.

**Description of the issue/feature this PR addresses:**
Product ```sequence``` is not working as expected as soon you install the ```website_sale``` module, as ```website_sequence``` will always overrule

**Current behavior before PR:**
Trying to resequence is useless as nothing will change the template list order

**Desired behavior after PR is merged:**
Everything works as expected (frontend and backend)

@JKE-be @nim-odoo 
May I ask you to review this one? I hope I did not forgot any place to look at, but I really think this is a bug and should be fixed in stable as functionality in the backend is confusing users (handle widget)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
but LGTM me to remove it in master, for v12

**Comment by wtaferner** [comment]
Ok, can you cherry-pick for master?

Thx for the quick review and feedback.

**Comment by wtaferner** [comment]
@JKE-be 
Now it has ugly commits, but changed to master branch ;-)

**Comment by wtaferner** [comment]
@JKE-be 
Please, it is straight-forward and really not a big deal and actually a bug, but I accepted b/c I know about your pains ;-)

**Comment by wtaferner** [comment]
Merged in d14e9e6

**Pull request closed without merging**
