### PR TITLE
Update default values for limit_memory_soft and limit_memory_hard

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Update default values according what the code really provides as default. Providing the default memory from older versions in multi-worker environment leads to problems compiling the bundle 'web.assets_backend'.

The fix should be pushed also to 9.0, 10.0, 11.0.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jbeficent** [comment]
Providing wrong memory defaults can ruin your weekend! see https://github.com/OCA/ansible-odoo/issues/72

**Comment by blaggacao** [comment]
A no-brainer! @mart-e

**Comment by Yenthe666** [comment]
@jbeficent please rebase it to 9.0 as 8.0 is no longer supported & PR's wont be accepted/merged for 8.0 anymore.

**Comment by xmo-odoo** [comment]
@jbeficent maybe update the CLI information as well? As you noted in OCA/ansible-odoo#72 it also gives outdated information. Either remove it entirely, or replace by `%default` (which will be replaced by the actual default value).

**Comment by jbeficent** [comment]
I see that you have already added it here https://github.com/odoo/odoo/commit/5404b8b4e728c61af4c764b8d3867ed9b13cab3a#diff-ed421baa082ec6847b96735b80f71127

**Pull request closed without merging**
