### PR TITLE
[FIX] requirements: add back requirement

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Oversight of e554ce345fb1ffcf41c571f461b680e1e7199a1d

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by mreficent** [comment]
Shouldn't this PR target to v11? because https://github.com/odoo/odoo/commit/e554ce345fb1ffcf41c571f461b680e1e7199a1d was merged in v11 🤔

**Comment by tde-banana-odoo** [comment]
Original commit: https://github.com/odoo/odoo/commit/6cbecced3d9ade705f7002bbca14477dcccd9297 (or https://github.com/odoo/odoo/commit/78ba90d54826c2ba11626e9a89b142964db25e2f) . This seems like a rebase issue.

**Comment by mreficent** [comment]
Oh, right :+1:

**Pull request closed without merging**
