### PR TITLE
[ADD] Cla for kdmwangi

### PR DESCRIPTION
**Pull request by kdmwangi**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
I think you should have pointed to v16 instead, as the other PR you proposed pointed to v16.

Also the email you put in the cla is not the same:
Selection_3346

**Comment by kdmwangi** [comment]
> I think you should have pointed to v16 instead, as the other PR you proposed pointed to v16.
> 
> Also the email you put in the cla is not the same: Selection_3346

are you suggesting i open another PR on V16 ?

**Comment by mart-e** [comment]
Hello,

Thank you for the signature but do you need this CLA for a specific contribution? You can add your CLA directly in the PR when you make your first contribution instead.

**Comment by MiquelRForgeFlow** [comment]
> Thank you for the signature but do you need this CLA for a specific contribution?

https://github.com/odoo/odoo/pull/167153

**Pull request closed without merging**
