### PR TITLE
[FIX] odoo: decode wkhtmltopdf errors

### PR DESCRIPTION
**Pull request by lade-odoo**

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

checking similar case, we either use equivalent .decode('utf-8') or misc.ustr (which also use decode('utf-8') but fallback on possibly another encoding). Maybe misc.ustr is better to be on safe side.

**Review by VincentSchippefilt — CHANGES_REQUESTED** [review]
Hi, could you update the commit message to  something like "[FIX] *base*: decode wkhtmltopdf errors" then describe the bug you are trying to fix in the commit message.
Also, if possible, create a test that exposes the problem you are fixing.

**Comment by lade-odoo** [comment]
@VincentSchippefilt There is a more appropriate commit message :)

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Pull request closed without merging**
