### PR TITLE
Redirect /longpolling urls to longpolling_port

### PR DESCRIPTION
**Pull request by leorochael**
Description of the issue/feature this PR addresses:
===

Odoo 10.0, out of the box, if you install anything that depends on the `mail` module, will install the live message notification support.

This means that if you are running with workers > 0 and access directly port 8086 on the server (instead of using a front-end webserver that redirects `/longpolling` urls to port 8072), you will be spammed with `bus.Bus unavailable` errors on the server console, since the workers refuse to handle `/longpolling/poll` requests.

Current behavior before PR:
===

We can't serve longpolling from a worker because that would tie up the worker, but previously we simply raised an exception when workers are enabled:

 * `bus.Bus unavailable`

But this exception is very cryptic, and for someone who is just running locally, the Google provided answers about configuring nginx or Apache to redirect `/longpolling` seem overkill.

Desired behavior after PR is merged:
===

Now we redirect the browser (with a 307 status code) to the longpolling port instead. The worker responds immediately and is free to handle other requests, while the browser contacts the longpolling port for the actual long polling.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by leorochael** [comment]
@gde-odoo, @aab-odoo, @jem-odoo, copying you since this is related to the web client and IM LiveChat.

@odony, copying you since this PR involves browser related security things (e.g. CORS).

I suggest evaluating this PR one commit at a time, instead of seeing all changes at once.

Some possible variations on this PR:

 - Do we need to redirect on `/longpolling/send`, or is `/longpolling/poll` enough? From the code it looks like `/poll` is sufficient.

 - Should we throw a warning in the log when this redirection happens so that the user knows to configure a web server in front of the `/longpolling` URL? The previous error was pretty cryptic and annoying so I  consider the current situation a direct improvement, but people might be tempted to go into production without realising they need to redirect `/longpolling` in their front end web server.

**Comment by gustavovalverde** [comment]
What do you mean with
> the Google provided answers about configuring nginx or Apache to redirect /longpolling seem overkill.

Why are those options an overkill?

**Comment by leorochael** [comment]
@gustavovalverde, because when you're developing locally, and you keep being spammed with `bus.Bus unavailable` errors, you don't want to drop into root, install a web server and configure redirection just so the error messages go away.

Specially if you are running two Odoo instances at the same time.

You just want to point your browser to localhost:8069 and hack away.

**Comment by leorochael** [comment]
Another alternative would be to make the last commit be a separate module that could be installed only when needed (i.e. not in production), but the previous commits need to be accepted into the core, so that redirection of JsonRpc requests through a 307 code can work.

Any thoughts?

**Comment by leorochael** [comment]
Edited the description to clarify why this PR is needed.

**Comment by leorochael** [comment]
A possible alternative to commit ce29273:

Instead of having a query string variable to force the `Content-Type` which might not be fowarded, is to have a query string variable to force method [`odoo.http:Root.get_request`](https://github.com/odoo/odoo/pull/14086/files#diff-03542f2676ca18278ea62cb40f5a2261R1408) to interpret a request as `JsonRequest` instead of `HttpRequest`.

Any thoughts?

**Comment by odony** [comment]
@leorochael Your patch looks nice and well structured, but unfortunately also quite invasive. It requires adding multiple utility methods for the purpose of making the 307 redirect trick work, that's a lot of code for a single minor purpose. Especially if you're aiming for a merge [in a stable branch](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean), but even for master.

It seems that your initial goal is to stop being annoyed by the `bus.bus unavailable` messages, not to actually get the `bus` to work in a very partial deployment environment. Indeed, `workers > 0` is really meant for a real deployment with a reverse proxy, correct limits, etc., typically not a dev setup. In that case, why not fix the client-side Javascript code instead? When presented with this specific error, it could entirely stop polling. It should not be very difficult to distinguish this error from the other transient errors returned by a working bus connection. (disclaimer: I haven't investigated in the JS code yet :pensive:)
Also, it seems acceptable as a trade-off that users would have to press F5 in order to start polling the bus if it was not available when they initially loaded it.

Any thoughts?

**Comment by leorochael** [comment]
@odony, I concede this PR as a whole is kind of invasive, which is why I proposed some alternatives to some commits.

Other commits, on the other hand, I consider they are fixes actually needed by the code base:

 - ef9a6c5b4aa84f2503ea6b16166dcf5a1370c589: JsonResponse: allow Response results
 - 809788a: Allow CORS from xmlrpc_port to longpolling_port
   - This one would be needed for any fix done in the JS side.

As for fixing this in the JS. It's quite possible, but I couldn't think of a way to do it other than the redirection: There is no way that I know to tell the client side that there is a second way of contacting the server.

As for my motivations: I do want the bus to work in this configuration (not only to make the message go away). Activating workers on a development setup (i.e. without a front-end) is interesting for one particular use case: To test parallel execution of tasks with the [Odoo Job Queue](https://github.com/OCA/queue/pull/1) (formerly from inside the Odoo Connector).

**Comment by leorochael** [comment]
@odony, would you like me to pull out commits ef9a6c5 and 809788a into their own PRs?

ef9a6c5 is useful for being able to reply redirects or other response codes from JsonRequests and I think it's an important missing functionality.

809788a will be required by any attempt to fix the "bus error" from the javascript end, otherwise no browser will accept to contact the longpolling_port if the original URL comes from the xmlrpc_port.

**Comment by C3POdoo** [comment]
Dear @leorochael,

Thank you for your contribution but the version 10.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
