### PR TITLE
[REF] website: convert dashboards to owl 

### PR DESCRIPTION
**Pull request by detrouxdev**
This commit converts the Website Dashboard to OWL.
The main goal of the Website Dashboard is to display the Plausible
Dashboard inside an iframe. Most of the code from the legacy widget was
actually used by website_sale and not website. Since Website Sale
dashboard is to be re-done in the dashboard app (by task-3222991), a lot
of the logic could be removed and simplified.

enterprise: https://github.com/odoo/enterprise/pull/44087

task-3164163

### CODE REVIEW

**Comment by aab-odoo** [comment]
Hello @detrouxdev 

What's the status of this PR? Do you think you'll be able to finalize this soon?

**Comment by detrouxdev** [comment]
@aab-odoo Hello, it's close to being done, probably sometimes next week. However, I think @pierre-pde wanted the website_sale part of the dashboard to be done in the Dashboard App. That was to be handled by another team (spreadsheet team?), and need to be done before merging this one.

**Comment by pierre-pde** [comment]
cc @paju-odoo who will coordinate the Website_sale dashboard migration

**Comment by aab-odoo** [comment]
@qsm-odoo do you have an eta for this one?

**Comment by aab-odoo** [comment]
Task 3222991 has been merged :D Any chance to see this one finalized for the upcoming freeze?

cc @qsm-odoo

**Comment by detrouxdev** [comment]
I'll rebase and adapt this PR ASAP

**Review by rdeodoo — CHANGES_REQUESTED** [review]
Checked out of curiosity the Website > Reporting > Analytics and the screen is broken: empty screen with scroll bar :grimacing: 
image
There should be plausible and if plausible is not setup there should be something displayed (If I remember right, at least to screen to set up credentials)

**Review by qsm-odoo — APPROVED** [review]
- Adapted the first commit which moved a file without adapting the manifest
- Took the opportunity to re-indent the XML file in the last commit as most of it was rewritten anyway

Tested, looks good :+1: 

@robodoo rebase-ff r+

**Pull request closed without merging**
