### PR TITLE
[FIX] calendar: round duration

### PR DESCRIPTION
**Pull request by nim-odoo**
When a calendar event is created with a duration of for example 20
minutes, the end time appears as the start time + 19 minutes.

Because of the rounding of the duration (20 minutes = 0.333... hours),
the end time is incorrectly set (xx:19:59.998...) then displayed. Since
the duration can only be set by the minute, we round it before computing
the end time.

opw-2122853

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by pedrobaeza** [comment]
Without wanting to be impertinent, I beg you to update also the translations, not only the POT, when doing this kind of change, as the whole translation is lost:

https://github.com/odoo/odoo/commit/d2bfb956a429f0e23ecb1acd64b67553a3b27300#diff-5386afdee85ad8f348821707360849a5L249-L316

and it's very difficult to find the previous one to start from it for adding the `round` word, so it ends up needing to be fully retranslated.

Thanks.

@mart-e I suppose a linter for this is difficult, but maybe an internal guideline?

**Comment by mart-e** [comment]
@pedrobaeza it is an internal guidelines not to update translatable content in stable (or at least to update the .pot) but some still manage to get through from time to time (still I like to think we have made progress in comparison of a few years ago).

**Comment by pedrobaeza** [comment]
Yeah, I know you are constantly improving and I thank for that.

I wonder if this kind of change can be programmatically propagated to all .po files, not only the .pot one, by the reasons stated above.

**Pull request closed without merging**
