### PR TITLE
[FIX] Fixed non possible translation for english frontend pages when …

### LINKED ISSUE #10095: The Frontend translation is limited (or buggy) when the website default language is not english
Hi all,
#### Impacted Versions:
- 9.0
#### Steps to reproduce
1. Open a runbot v9 instance
2. Install a second language
3. Go to Website Admin -> Configuration
4. Change the default language from english to the second language
5. Open any frontend page, change the language to englisch and click on translate:
   - the green markers are missing
   - the main navigation labels can’t be translated
   - if you are on a blog post page the blog title and subtitle can’t be translated
6. The points above work when english is the website default language
#### Expected behavior

The translation should work the same way for a non english default language like it works for the english default language.

### PR DESCRIPTION
**Pull request by rruebner**
…the website default language is not english.

This will fix #10095.

### CODE REVIEW

**Comment by rruebner** [comment]
Hi @Gorash, please have a look at it. You extracted / refactored code parts for the new web_editor module in commit https://github.com/odoo/odoo/commit/8c559044a5e1be111dcb577ad7e5ab462c1002a0.
In ir_http.py https://github.com/odoo/odoo/commit/8c559044a5e1be111dcb577ad7e5ab462c1002a0#diff-441aa73d1199ca506ed1cd18711b541e you add a translatable flag when the current language is not english (en_US). Unfortunately this means that english frontend pages can't be translated when the website default language is not english.
I updated the condition that it works in a similar way like it works in odoo 8.0. Do you agree?

**Comment by Yajo** [comment]
I think you messed it up with the rebase, please try again.

**Comment by rafaelbn** [comment]
:open_mouth: 
@rruebner I think this is already solved in v9 but not in v8

**Comment by rdeodoo** [comment]
Closing, see last message on https://github.com/odoo/odoo/issues/10095
Thank you for your PR

**Pull request closed without merging**
