### PR TITLE
[IMP] Doc: update 8.0 reference to 11.0

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: The documentation still mentioned V8 in the V11 branch

Current behavior before PR: The documentation still mentioned V8 in the V11 branch

Desired behavior after PR is merged: The documentation mentions V11 in the 11.0 branch

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e something like this?

**Comment by mart-e** [comment]
@Yenthe666 as we are fixing the doc, let's really do it 😉 
There is still some references a few lines below. Also remove the example of old style class name.

**Comment by Yenthe666** [comment]
I believe I've removed everything that you liked (plus I corrected a few sentences/typo's too).
I was a bit lazy in the initial PR as I was busy, you're right let us do better. 😉

**Comment by mart-e** [comment]
Thanks for the update, better like this :)

**Pull request closed without merging**
