### PR TITLE
[IMP] mail: typing icon for channel chat window header

### PR DESCRIPTION
**Pull request by xdu-odoo**
task-2282361

### CODE REVIEW

**Comment by xdu-odoo** [comment]
Tests adaptations and new tests will follow

**Comment by xdu-odoo** [comment]
@alexkuhn Problem here : `ThreadIcon` template is used in `messaging_notification_handler` by a `renderToString` which do not work on a component tree. So as now `ThreadIcon` uses `RecordStatusIcon`, it bugs... So what do you think we could do ?

**Comment by xdu-odoo** [comment]
> @alexkuhn Problem here : `ThreadIcon` template is used in `messaging_notification_handler` by a `renderToString` which do not work on a component tree. So as now `ThreadIcon` uses `RecordStatusIcon`, it bugs... So what do you think we could do ?

After discussion : we decided to remove the use of the icon for now, could be reintroduced later if we find a way to do it without renderToString, see https://www.odoo.com/web#id=2293245&action=3206&active_id=1519&model=project.task&view_type=form&cids=1&menu_id=4720

**Comment by alexkuhn** [comment]
Also outer background of IM status icon should match the color of background, not just being white.
This may be harder to fix than it looks... Maybe need to manage color in template, so that it's a prop? Seems more appropriate to make a task for that...

**Comment by xdu-odoo** [comment]
Scrap all this

**Pull request closed without merging**
