### PR TITLE
[FIX] l10n_fr_pos_cert: do not allow to delete last line

### PR DESCRIPTION
**Pull request by agr-odoo**
Have a POS
Add a product (quantity 1)
Hit the remove product (quantity goes to 0)
Hit the remove product (product is canceled from the order)

We should not be able to remove the product once added to the order,
just freely edit the quantity of the last line

Fine tuning of 716f33ccb92de65380c15d153d60e90721833e42

opw-2419592

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@simongoffin 
Functional check of l10n_fr_pos_cert
When we add a line in POS we should:
* be able to Set quantity to 1.x
* be able to Reset the quantity to 0 and edit it further (i.e. 0.5)
* **not** be able to delete the line
All of this apply to the last line, all other lines shall not be modified

**Comment by agr-odoo** [comment]
Added second commit to take into account the return-in-POS flow

```
Open POS
Add a product you want to return
Press delete key (quantity reset to 0)
Press delete key once again (Quantity widget popup show)
Insert 1 or the quantity you want to return
Confirm
The line will update with the negative quantity
This only works with the last line
```

**Comment by simongoffin** [comment]
Hello @pimodoo 

What do you think about it?

**Comment by pimodoo** [comment]
I've just tested it and it seems to correctly work

**Comment by simongoffin** [comment]
robodoo delegate+

**Comment by agr-odoo** [comment]
Thanks for the review!
@robodoo r+

**Comment by agr-odoo** [comment]
@robodoo rebase-ff

**Comment by d-fence** [comment]
robodoo rebase-ff

**Pull request closed without merging**
