### PR TITLE
[IMP] (website_)stock_delivery: rework the dependency tree

### PR DESCRIPTION
**Pull request by vava-odoo**
- `stock_delivery`: remove dependency to `sale_management` as it is not needed if `website_sale` is installed. Now, Sales app is installed only if e-commerce app is not;
- `website_sale_stock`: force dependency to `stock_delivery`. This reinforces the dependency tree: as delivery is needed with `website_sale`, `stock_delivery` is expected to be installed when `website_sale_stock` is installed. This also prevent the deletion of this dependency module.

### CODE REVIEW

**Review by Feyensv — APPROVED** [review]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo rebase-ff

**Comment by Feyensv** [comment]
@robodoo r-
(giving some time for logistics team review).

**Comment by ticodoo** [comment]
> @robodoo r- (giving some time for logistics team review).

:shrug: doesn't make a difference for us

**Comment by vava-odoo** [comment]
@amoyaux is it ok for you with this post_init_hook? (Install Sales if no e-commerce)

**Comment by amoyaux** [comment]
Ok for me

**Comment by vava-odoo** [comment]
Thanks @amoyaux. @Feyensv, r+ then?

**Review by Feyensv — APPROVED** [review]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo delegate+
upgrade seems to be failing, either a rebase is needed or something needs to be handled in upgrade scripts :thinking:

**Comment by vava-odoo** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
