### PR TITLE
[FIX] web: use the correct inputmode for fields

### PR DESCRIPTION
**Pull request by hubvd**
Steps to reproduce
==================

- Use an IOS device
- Open a view with a float field
- Try to edit it

The virtual keyboard displayed is missing a dot, so you can only input
integers

Cause of the issue
==================

For fields that should accept a float value, the inputmode attribute
should be decimal.
Also, specifically on IOS, even with the inputmode set to decimal, it
isn't possible to enter a negative value.

> decimal:
> Fractional numeric input keyboard containing the digits and decimal separator
> Devices may or may not show a minus key (-)

Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

Solution
========

For IOS, remove the inputmode attribute so that the default keyboard
shows. For other devices, use the decimal/numeric value depending on
whether a float should be accepted.

opw-3269275

### CODE REVIEW

**Comment by hubvd** [comment]
Note that this still doesn't display a minus symbol, so we can't input negative numbers..

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

> decimal:
> Fractional numeric input keyboard containing the digits and decimal separator
> Devices may or may not show a minus key (-)

Should we just not set the inputmode for ios ?

**Comment by bouvyd** [comment]
I wouldn't try to guess what can be negative or not - nothing prevents a user from setting a percentage field to -20% in some flow (including custom modules). I agree with @aab-odoo : just remove the inputmode if ios.

**Review by aab-odoo — COMMENTED** [review]
Instead of applying the condition on each numeric field where we define the inputmode, what about doing the hack in a single place, in the useNumpadDecimal hook? You could simply unset the inputmode attribute if isIOS in the useEffect (with a comment explaining why, maybe in the docstring)

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
