### PR TITLE
Set Vendor currency in the pricelist from product form

### PR DESCRIPTION
**Pull request by nla-odoo**
- if the currency is set on a vendor and set that particular vendor to the product, the currency will not be being changed by vendor's currency.
-  after this commit currency in pricelist will be changed by the currency of the vendor

Task : https://www.odoo.com/web#id=1826166&view_type=form&model=project.task&action=327&menu_id=4720

Pad: https://pad.odoo.com/p/r.3f58fdd172e409fecc382face887968c

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by LemonAndroid** [comment]
@atp-odoo Is there a reason this wasn't merged yet?

**Comment by LemonAndroid** [comment]
@tivisse

**Comment by LemonAndroid** [comment]
@nla-odoo

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
