### PR TITLE
add python_requires to setup.py

### PR DESCRIPTION
**Pull request by sbidoul**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@sle-odoo can these checks be added in?

**Comment by sle-odoo** [comment]
As we don't package saas-17 these changes are not necessary, and if they're forward-ported there'll be an issue as saas-18 and later v11 will only run on python 3.5 onwards if i'm not mistaken? @odony

**Comment by d-fence** [comment]
I can do something like  "python_requires='>=3.5" in my packaging branch for saas-18.
But from my POV, it 's not necessary ?!

**Comment by odony** [comment]
@sle-odoo @d-fence AFAIU this line will only prevent pip 9+ from installing odoo on Python 3 before 3.5, and Python 2 before 2.7. For 11.0 we won't _officially_ support 2.7, and I guess the `python_requires` argument also serves to indicate official support, so we might want to go for `>=3.5` indeed.
It's not strictly necessary for our packaging purposes, but I guess it doesn't hurt and makes the supported versions more explicit.

**Comment by d-fence** [comment]
@odony I agree, It probably doesn't hurt. I'm going to add it right now in the packaging branch.

**Comment by sbidoul** [comment]
@sle-odoo @odony AFAIU `>=3.5' would *break* installs on python 2. So better not.

**Comment by odony** [comment]
@sbidoul you mean it would break installs of Odoo 11 on P2 via pip? Isn't that the purpose of this argument, to [show what versions are officially supported](https://packaging.python.org/tutorials/distributing-packages/#python-requires)?
 
What was your initial goal? Just preventing installation on Python 3.0 to 3.4? That's nice, but I'm concerned that keeping `>=2.7` for Odoo 11 will look like we officially recommend 2.7 for v11, which is really not the case (it may even break after a while)

Also, since this is not an "official" way of installing Odoo, and only works with pip9+, it would not break for many users, would it?

We could also entirely omit it, leaving it to the user to decide, pretty much like when they explicitly call `pythonX odoo-bin` to run with P2...

**Comment by sbidoul** [comment]
> you mean it would break installs of Odoo 11 on P2 via pip

Yes.

My main goal was preventing to run on never ever tested python 3 versions, while not actively breaking python 2.

But you are right, it should not break for many people.

So indeed, `>=3.5` or leave it out. As you prefer.

**Pull request closed without merging**
