### PR TITLE
[IMP] doc: minor fixes/improvements

### PR DESCRIPTION
**Pull request by Feyensv**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
It looks like this ;).
image

**Comment by Feyensv** [comment]
@robodoo r+ rebase-ff

**Comment by seb-odoo** [comment]
It actually looks pretty good.

Seeing the render made me realize the default value for max_width/max_height is currently missing from the doc, including the tricky part that 0 acts as "ignore" and not of course the size being 0px.
Should also probably explicit that the size is expected in pixels.

**Comment by seb-odoo** [comment]
Also max_width/max_height acts as "resize to limit if currently above" not as "prevent if above", which is an important difference to know.

**Comment by Feyensv** [comment]
@robodoo r-

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
