### PR TITLE
[10.0][FIX] stock: Putaway strategy should not apply if result is not…

### PR DESCRIPTION
**Pull request by rousseldenis**
… a child of

Description of the issue/feature this PR addresses:

Stock : Putaway strategies

Current behavior before PR:

Create a Putaway Strategy that concern Dispatch Zone and All Products category.
Create a fixed putaway entry for product Ipad and destination location as Gate A

Create a Receipt Picking To Dispatch Zone/Gate B with Product Ipad.
Confirm It
Reserve it.

Pack operation points to Gate A and not Gate B.

The picking Zone is defined to Gate B. This is incoherent as Gate A is not a child of Gate B.

Desired behavior after PR is merged:

Create a Putaway Strategy that concern Dispatch Zone and All Products category.
Create a fixed putaway entry for product Ipad and destination location as Gate A

Create a Receipt Picking To Dispatch Zone/Gate B with Product Ipad.
Confirm It
Reserve it.

Pack operation points to Gate B (Putaway Strategy was not applied)

This process is shown in tests.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
A constraint would be more logical in this case.

**Comment by rousseldenis** [comment]
OPW-1844615

**Comment by rousseldenis** [comment]
@jco-odoo On what do you want to put a constraint ?

**Comment by rousseldenis** [comment]
@tde-banana-odoo @jco-odoo

**Comment by jco-odoo** [comment]
Makes sense to restrict putaway to child locations somehow.  @nim-odoo   But I wonder how we handle in later versions and there is no need for putaway locations to check parent locations in the first place.  Just checking for putaway strategies with as base location the location of the picking should be sufficient.   @sle-odoo

**Comment by pedrobaeza** [comment]
This being 10.0, is till applying or should be moved to later versions?

**Comment by jco-odoo** [comment]
@pedrobaeza It is a lot more logical to put the constraint in the putaway method itself than here where you apply the putaway.  Need to ask @sle-odoo if they added a domain in later versions.  By the way, I wonder if a lot of different modules already exist with different putaway/removal strategies.

**Comment by pedrobaeza** [comment]
Perfect, let's see the answer. I came to this from codetriage.com, so there's no direct interest for me, except the my usual cleaning self-task :)

**Comment by sle-odoo** [comment]
Closing as the linked ticket is closed.

**Pull request closed without merging**
