### PR TITLE
[IMP] l10n_ar: add available document types 80 and 83

### PR DESCRIPTION
**Pull request by pablohmontenegro**
**Description of the issue/feature this PR addresses**:
It is necessary to be able to select document types "80 INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES" and "83 TIQUE" in an invoice if the journal of the invoice has "Online Invoice" set on field "AFIP POS System".

**Current behavior before PR**:
User is not able to select document types "80 INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES" and "83 TIQUE" in an invoice if the journal of the invoice has "Online Invoice" set on the field "AFIP POS System".

**Desired behavior after PR is merged**:
User is able to select document types "80 INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES" and "83 TIQUE" in an invoice if the journal of the invoice has "Online Invoice" set on the field "AFIP POS System".

Task Adhoc side: 34790
Task latam: 1167

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vbe-odoo** [comment]
@pablohmontenegro should we close this PR?

**Comment by pablohmontenegro** [comment]
@vbe-odoo no Valen, sorry for the delay in my answe, can we change the state to Open?. It is necessary to be able to select document types "80 INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES" and "83 TIQUE" in an invoice if the journal of the invoice has "Online Invoice" set on field "AFIP POS System".

**Comment by vbe-odoo** [comment]
> @vbe-odoo no Valen, sorry for the delay with my answer, can we change the state to Open?. It is necessary to be able to select document types "80 INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES" and "83 TIQUE" in an invoice if the journal of the invoice has "Online Invoice" set on the field "AFIP POS System".

Hey @pablohmontenegro thanks for the ping and the explanation I will be testing it.
Yes, please move it to "Open".
Thanks!
cc' @ren-odoo @fvz-odoo

**Comment by vbe-odoo** [comment]
Thanks for the PR @pablohmontenegro 
@jco-odoo I've tested and it LGTM, ready for tech review.
Thanks!

**Comment by jco-odoo** [comment]
@pablohmontenegro Looks good to me, but we would need a rebase to get runbot green.  Please check as well that it does not break any test.

**Comment by pablohmontenegro** [comment]
@vbe-odoo yes Valen, thanks!

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
