### PR TITLE
[MERGE] forward port branch saas-12.3 up to 50e571acf7c

### PR DESCRIPTION
**Pull request by KangOl**

### CODE REVIEW

**Comment by KangOl** [comment]
robodoo merge review+ priority=0

**Comment by KangOl** [comment]
robodoo merge review+ priority=0

**Comment by KangOl** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Comment by KangOl** [comment]
robodoo merge review+ priority=0

**Comment by KangOl** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo p=0

**Comment by KangOl** [comment]
robodoo merge review+ priority=0

**Comment by sle-odoo** [comment]
@KangOl https://github.com/odoo/odoo/pull/35898 should not be forwarported 😰

**Comment by KangOl** [comment]
> @KangOl #35898 should not be forwarported 😰

in saas-12.4 or saas-12.5?

**Comment by KangOl** [comment]
> @KangOl #35898 should not be forwarported 😰
9b6a5398dfbd943fc34da1314e35440f78f2f609 is only in saas-12.5

**Comment by KangOl** [comment]
robodoo merge review+ priority=0

**Pull request closed without merging**
