### PR TITLE
[FIX] self.o2m = self.o2m deletes kept records

### PR DESCRIPTION
**Pull request by coleste**
Description of the issue/feature this PR addresses:
self.o2m = self.o2m will unlink() all delete='cascade' before they can be added back.

Current behavior before PR:
self.o2m = self.o2m is converted into a command list [(5,), (4, id), (4, id)]. The first command (5,) will unlinks all elements, including those added back by (4, id) commands in the same list.

Desired behavior after PR is merged:
self.o2m = self.o2m does not delete anything.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by odony** [comment]
I think the current behavior of the sequence of `[(5,), (4,id), ...]` sequence of commands is correct and should not be modified. The commands are ordered for a reason and changing this could cause random surprises down the line, especially in a stable branch.

For instance you patch would break the valid but surprising sequence `[(4, id), (5,), ...]`.

Now perhaps the translation of `self.o2m = self.o2m` should use a `[(6, [id, ...])]` command instead, to workaround this problem, as the `6` only deletes the extra rows *after* adding everything. This also begs the question as to whether it should also `unlink()` rows when `ondelete=cascade`...
@rco-odoo what do you think?

@coleste could you provide more info about the use case where you encounter the bug? Is this with an official module, or a custom one? How did you end up with the unusual `self.o2m = self.o2m` pattern?

By the way, this pitfall looks minor enough that it does not seem worth the risk of changing the behavior in stable. I would vote for targeting `master` instead for any change (no need for another PR though).

**Comment by coleste** [comment]
The sequence ```[(5,), (4,id), ...]``` will crash and rollback for cascade. It doesn't happen in stable so it's not an issue. You are right, it should only keep those after the last [(5,)]. I should improve the patch.


It's a custom module modifying view_account_payment_form. We have a table with extra information for every unreconciled moves (each payment term of invoices + previous payments). It's not ```self.o2m = self.o2m```, but more updating the list to:
- add new invoices
- remove reconciled invoices/payments

As it stands, ```Field.__set__()``` simply does not work with cascade, as it calls ```_RelationalMulti.convert_to_write()``` which will create a command list starting with [(5,)]. And command lists are not passed straight but mangled by the ```convert_to_cache()``` / ```convert_to_write()``` pair.

Correcting ```convert_to_write()``` to use (6, []) would solve my issue. Would this be safe enough for stable?

**Comment by odony** [comment]
@coleste thanks for the extra info! It it works I would prefer to use `(6, [])` to fix this issue, but I think the change might still be too much for a stable branch. I'd like to wait for @rco-odoo's opinion on the matter: the implementation of `convert_to_write()` used to generate `(6, [])` but was changed in 9f81c6d651cc3f66e50681a7e13433b2e89257ef for good reasons.

**Comment by rco-odoo** [comment]
The request #13082 provides a better fix. It avoids the command `(5,)` when converting the recordset to the `write()` format, and uses a command `(6, ...)` instead.

**Comment by odony** [comment]
#13082 implements what I discussed in previous comments, so if @coleste doesn't mind I'd like to close the current PR and follow it up on #13082.

**Pull request closed without merging**
