### PR TITLE
fix active filter not working in activity view

### PR DESCRIPTION
**Pull request by msh-odoo**
PURPOSE
When applying active filter using progressbar in activity view, records are not displayed based on active filter, row was not getting highlighted based on active filter, row should be highlighted based on active filter and records should be sorted based on active filter.

SPEC
When applying active filter in activity view using progressbar, highlight row and sort records based on active filter.

TASK 2550959

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by seb-odoo** [comment]
@kebeclibre I've never worked in the activity view, we never got time/priority to take responsibility of the full activity scope.

I think it was @mcm-odoo who originally created these views? Or the OWL version of it at least?

**Comment by SimonGenin** [comment]
@msh-odoo Some rebase needed

**Comment by msh-odoo** [comment]
@SimonGenin Branch rebased and greem now.

**Comment by SimonGenin** [comment]
@robodoo r+

**Pull request closed without merging**
