### PR TITLE
8.0-pos-child-taxes-fva

### PR DESCRIPTION
**Pull request by fvdsn**
This is a forward port for 8.0 of the 7.0 point_of_sale child tax support patch

https://bugs.launchpad.net/openobject-addons/+bug/1231574

### CODE REVIEW

**Comment by gurneyalex** [comment]
@fvdsn would you like to propose the branch for merge to https://github.com/OCA/OCB? or would you object my doing so on your behalf?

**Comment by gurneyalex** [comment]
this should close https://github.com/odoo/odoo/issues/1515

**Comment by gurneyalex** [comment]
@antonylesuisse any update on this issue?

**Comment by jnbrunet** [comment]
There is a bug when the pos generate the invoice. Here is what I've done to fix it.

    diff --git a/addons/point_of_sale/static/src/js/models.js b/addons/point_of_sale/static/src/js/models.js
    index 131e6501..22b5bbc 100644
    --- a/addons/point_of_sale/static/src/js/models.js
    +++ b/addons/point_of_sale/static/src/js/models.js
    @@ -168,7 +168,7 @@ function openerp_pos_models(instance, module){ //module is instance.point_of_sal
             },{
                 model:  'pos.order',
                 call:   'get_all_taxes',
    -            args:   function(self){ return [['amount','price_include','type','child_ids','child_depend','include_base_amount'], new instance.web.CompoundContext()]; },
    +            args:   function(self){ return [['name','amount','price_include','type','child_ids','child_depend','include_base_amount'], new instance.web.CompoundContext()]; },
                 loaded: function(self,taxes){ self.taxes = taxes; },
             },{
                 model:  'pos.session',
    @@ -1033,11 +1033,18 @@ function openerp_pos_models(instance, module){ //module is instance.point_of_sal
                 var details = {};
                 var fulldetails = [];
                 var taxes_by_id = {};
    -            
    -            for(var i = 0; i < this.pos.taxes.length; i++){
    -                taxes_by_id[this.pos.taxes[i].id] = this.pos.taxes[i];
    -            }
     
    +            var get_all_taxes_by_id = function(taxes) {
    +                if (! taxes || ! taxes.length) 
    +                    return;
    +
    +                for (var i = 0; i < taxes.length; i++) {
    +                    taxes_by_id[taxes[i].id] = taxes[i];
    +                    get_all_taxes_by_id(taxes[i].child_ids);
    +                }
    +            }
    +            get_all_taxes_by_id(this.pos.taxes);
    +            
                 this.get('orderLines').each(function(line){
                     var ldetails = line.get_tax_details();
                     for(var id in ldetails){

**Comment by gbard** [comment]
Give me your Paypal address. I swear to god that I'll send you money if it works when I try this tomorrow morning.

**Comment by mart-e** [comment]
closing as outdated branch, updated at #5873

**Pull request closed without merging**
