### PR TITLE
[PERF] pos_sale: memoize `_compute_currency_rate` of `pos.order`

### PR DESCRIPTION
**Pull request by pivi-odoo**
## Description
Saving a new `res.config.settings` (for ex: checking "Use QR code on ticket") can be extremely slow on database with a large number of `pos.order`.

## Analysis
Saving a new `res.config.settings` creates a new instance of the config. This will invoke a check on the python constraints calling eventually `_check_currencies` of `pos.config`, which will invoke the compute of `currency_id` setting the field as dirty. The `_compute_currency_rate` of `pos.order` depends on the `currency_id` of the current `pos.config` (via a related).
This means the compute will be called with *all* `pos.order` ever made. As the compute itself makes a few calls to `_get_conversion_rate`, which makes a query, it can become slow when the method is called frequently.

## Solution
Memoize the call to `_get_conversion_rate`, as similarly done in `account.move.line` from d8d47f9ff8554f4b39487fd2f13c153c7d6f958d to reduce the number queries necessary.

## Benchmark
The `create` request to `res.config.settings` on a database with over 240k `pos.order` took

|             | Before    | After    |
|-------------|-----------|----------|
| Timing      | 36.9 secs | 4.3 secs |
| Query count | 47k       | 627      |

## Reference
opw-3632273

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pivi-odoo** [comment]
As discussed in private with @caburj , it's probably unnecessary to compute the currency rate of `pos.order` that are in another state than 'draft' (in all other states, the order has been either paid / posted, so there is no point in recomputing the currency rate).
But in the end I've determined that making such a change in stable might be too risky, as I don't know how it may impact different reports, so it's better to explore this solution in master.

I've benched with a filter of the style:
```py
self.filtered(lambda o: not o.currency_rate or o.state == 'draft')
```
on the database I have, I just shave off 1 second more, which doesn't warrant a possible risky change in stable.

**Review by caburj — APPROVED** [review]
robodoo r+

**Comment by nim-odoo** [comment]
Not sure `lru_cache` was the best approach. If the problematic computation is a `search` within the loop `for order in self:`, a simple dict was probably enough.
If a more robust cache was needed, `ormcache` on a regular method seems less error-prone than a `lru_cache` on an inner function. I'm not sure what is going to happen if the `lru_cache` function is ever moved outside the method :thinking:

**Comment by pivi-odoo** [comment]
Thanks for letting me know @julienlegros, I wasn't aware that work had been done for 17.0 to remove all these local caching solutions.
I've opened a PR for 17 and up to adapt to those new changes. https://github.com/odoo/odoo/pull/148825

**Pull request closed without merging**
