### PR TITLE
[FIX] Redirection to confirmation page at the end of the checkout pro…

### PR DESCRIPTION
**Pull request by reinka**
…cess in case of a previous cart reset by the user.

Description of the issue/feature this PR addresses:
- See confirmed issue: https://github.com/odoo/odoo/issues/15903

Current behavior before PR:
- See github issue above

Desired behavior after PR is merged:
- See github issue above

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hugho-ad** [comment]
@JKE-be what is the status of this ? do have any news ?

**Comment by JKE-be** [comment]
Hi @reinka,

Thanks for the patch.

Why do you want to remove your 2 colleague form the CLA ? 

Best regards

**Comment by reinka** [comment]
@JKE-be They no longer work at bloopark.

**Comment by tde-banana-odoo** [comment]
Hello,

Instead of removing your colleagues from the CLA, please add a comment telling they are not covered by the CLA anymore with the date. Thanks !

**Comment by JKE-be** [comment]
As it has been already merged in 9.0 withtout the delete line.

Could  you make a new pull request with the rename in cla according to @tde-banana-odoo specifications. Thanks

**Comment by hugho-ad** [comment]
@JKE-be can you share us the commit where this has been merged please

**Comment by JKE-be** [comment]
@hugho-ad 

Landed in 9.0: https://github.com/odoo/odoo/commit/859a77ca8bd6602d7fc1c426f6dead4a9ec3dcf1

**Comment by hugho-ad** [comment]
@JKE-be Thanks!

This patch will be forward  to v10.0 ?

**Comment by JKE-be** [comment]
@hugho-ad

Of course... in the next days !

**Pull request closed without merging**
