### PR TITLE
[IMP] crm_iap_enrich,iap_mail,snailmail: improve IAP notification system

### PR DESCRIPTION
**Pull request by lobaudoux**
The old implementation had some inconsistencies and didn't allow to have general error notifications, it was only meant for credit error notifications.

The notification/log messages of lead enrichment were also improved as some of them were unclear.

Enterprise PR: odoo/enterprise/pull/44488

### CODE REVIEW

**Comment by lobaudoux** [comment]
Hello @odoo/rd-security ,

This PR got flagged for usages of `_sendone` and `Markup`, these are not new usages, they've only been moved.
Could you have a look at it ?

**Comment by lobaudoux** [comment]
Hello @odoo/rd-security , quick reminder that I'm waiting for your input on this PR.

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: sendone message on current user only, not possible to craft messages on other users/channels

**Review by fda-odoo — APPROVED** [review]

**Comment by fda-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
