### PR TITLE
[FIX] hr_work_entry_holidays: move _get_number_of_days codes to _get_number_of_days_batch in hr_leave

### LINKED ISSUE #135964: [15.0][16.0] Time off duration days compute issue
Impacted versions:
V15.0 V16.0

Steps to reproduce:
1. install hr_holidays_public from OCA (https://github.com/OCA/hr-holidays)
2. When just install time off module, the time off duration days computed is right
3. After install Payroll module (it installed depends module hr_work_entry_holidays), the time off duration compute is wrong.

Video/Screenshot link (optional):
1. set public holidays
255052910-0325042b-2406-476f-b0ad-09e4a4c339c7

2. request a new time off (the fresh db just install time off and hr_holidays_public modules)，the duration days is right
255053384-ef1b4fb3-a6e8-49a2-92bc-1fe0061597d3

3. install hr_work_entry_holidays
255054273-dd4290b7-7f34-46a1-b40e-72cffc565618

4. request another new time off after install hr_work_entry_holidays, the duration days is not the same as step2
255054480-bfed7f59-bd3d-459f-b8af-3f7d0131763c

I debug into hr_work_entry_holidays module, the function _get_number_of_days is override duration days directly.
If the compute function move to _get_number_of_days_batch function can also consider employee's contact and have flexible for inherit.

Support ticket number submitted via odoo.com/help (optional):

### PR DESCRIPTION
**Pull request by stanleykao72**
Description of the issue/feature this PR addresses:
Would resolve #135964 , but not sure if this is the correct fix.

Current behavior before PR:
1. install time off and hr_holidays_public from OCA
2. set holiday public in 10/9, 10/10
3. request a new time off, start from: 10/6, end: 10/11, duration day is 2
4. install hr_work_entry_holidays
5. request another new time off, start from: 10/6, end: 10/11, duration day is 4
 
Desired behavior after PR is merged:
1. install time off and hr_holidays_public from OCA
2. set holiday public in 10/9, 10/10
3. request a new time off, start from: 10/6, end: 10/11, duration day is 2
4. install hr_work_entry_holidays
5. request another new time off, start from: 10/6, end: 10/11, duration day is 2

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by robcoekaerts** [comment]
@stanleykao72 It seems to me that the part of this PR that fixes the issue is having added the domain ``('time_type', '=', 'leave')``, not the batching of the method. Could you remove the other changes and restrict this PR  to the part that fixes the described behaviour? Also, can you squash your commits?

**Comment by stanleykao72** [comment]
> @stanleykao72 It seems to me that the part of this PR that fixes the issue is having added the domain `('time_type', '=', 'leave')`, not the batching of the method. Could you remove the other changes and restrict this PR to the part that fixes the described behaviour? Also, can you squash your commits?

Thanks for pointing out the problem
1. the domain `('time_type', '=', 'leave')` move out the result is still right, so move the time_type in domain out.
2. it seems squash is not successful ?

**Comment by robcoekaerts** [comment]
@stanleykao72 Yes your commits are indeed not squashed. Also, on a second look I can't seem to reproduce your issue with standard community modules installed. If you simply use standard community 'public holidays' do you also experience this issue? 

At this time I don't really understand how turning this method into a batched method would solve any issue, as the functionality is still very much the same. Also as a rule, we can't change method signatures in stable community releases such as 16.0, as this could cause other customizations to start failing. So you either have to provide a fix that doesn't change the method signature or you can make a PR for the OCA module itself, if that's where the issues lies.

Can you explain to me precisely why this change fixes the behaviour of the OCA module, or is this just something you tried and works?

**Comment by stanleykao72** [comment]
@robcoekaerts Thanks for you give some advices.
1. on a second look I can't seem to reproduce your issue with standard community modules installed: Yes, it is impact on both installed Payroll and Holiday Public from OCA.
2. standard community 'public holidays': it is working fine in my case.
3. I don't really understand how turning this method into a batched method would solve any issue, as the functionality is still very much the same: After I realize the standard community 'public holidays' is working, I follow the rule to customize the code in OCA, but it's still produce the issue. I debug into the code step by step, the reason case the issue is passing context "exclude_public_holidays=True"(as below picture). The context can be passing and extending the rule and compute number_of_days.
 
截圖 2023-10-04 上午9 04 30

截圖 2023-10-04 上午9 11 34

But, when the code running to hr_work_entry_holidays, the context of exclude_public_holidays is gone and override the result of number_of_days,

截圖 2023-10-04 上午9 17 14

Therefore, I make a small change move the code from _get_number_of_days to _get_number_of_days_batch, I think it's more advantage to follow the same rule from hr_holidays and add the check employee contract. And have some space to inherit some special rules.

截圖 2023-10-04 上午9 28 55

4. we can't change method signatures in stable community releases such as 16.0, as this could cause other customizations to start failing: I can't understand "method signatures", if I can know about it I can do more.
5. So you either have to provide a fix that doesn't change the method signature or you can make a PR for the OCA module itself, if that's where the issues lies: I have opened a issue https://github.com/OCA/hr-holidays/issues/84 on OCA, and I can't bypassed the rule in hr_work_entry_holidays so I can't make a PR in OCA. So I make a PR for Odoo.

**Comment by robcoekaerts** [comment]
Hi, the fundamental issue is that you're moving code around to different methods in order to suit your particular situation. And while those changes may or may not be generally beneficial, the problem with them is that they are likely to break other people's customizations as they expect that code to be where it is right now. This is why we don't do these kinds of changes in stable versions such as 16.0.

[Method signatures](https://python-forge.readthedocs.io/en/latest/signature.html)

While I sympathise with your situation, this is not a bug in Odoo community. It's a bug in the OCA module, which you're trying to fix by refactoring Odoo community. However we can't refactor code in stable versions.

It seems like in this case, the flow is broken because hr_work_entry_holidays is installed after the public holidays OCA module. I think you can work around the issue by installing the OCA module after hr_work_entry_holidays instead.

**Pull request closed without merging**
