### PR TITLE
[FIX] web: remove a check that replaces empty field values by false.

### PR DESCRIPTION
**Pull request by Jerther**
**Description of the issue/feature this PR addresses:**
When a text field has an empty value, it is converted to false in the view so attrs does not work.

**Current behavior before PR:**
- Have Text() field, and put it in a view with attrs="{'invisible': ('text_field', '=', '')}"
- The field is always shown, be it empty or not

**Desired behavior after PR is merged:**
The field is shown only when it contains some text.

**Additional details:**
Is there any reason for "|| false"? Removing it makes the above case work but this PR could be improved if there are cases I missed.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ged-odoo** [comment]
@Jerther 
this will probably blow up when trying to evaluate a domain with some undefined/null values.  This is actually quite tricky.  I believe we solved your particular issue in saas-16, when we rewrote all the JS views, and to do that, we had many many problems with the evaluation context.

See getRecordEvalContext (https://github.com/odoo/odoo/blob/saas-16/addons/web/static/src/js/views/basic/basic_model.js#L2490) and getEvalContext https://github.com/odoo/odoo/blob/saas-16/addons/web/static/src/js/views/basic/basic_model.js#L2438

In that case, we need to be more fine grained. And we had to do some special code for evaluating context (which is not the same as getting values ready to be sent to the server)

**Comment by Jerther** [comment]
I added some check so a null or undefined value would stay false. This covers some limit cases which seem to be covered in the new basic_model.js.

Otherwise, since it should be fixed in saas, will it be merged anyway in 10 someday?

**Comment by tivisse** [comment]
Ping @ged-odoo 

You've participated on the discussion an the PR has been updated, could you check please ? 

Thanks.

**Comment by ged-odoo** [comment]
This is a bug fix, in 10.0. It may work, or not, hard to say, we have no decent test suite in 10.0. I'll let the bug fix team decide.

**Comment by tivisse** [comment]
Hi @Jerther 

We have an internal process to manage bug fixes. I'm gonna close this PR. Could you please open a ticket on /help and reference this PR on it ? 

Thanks again,

Yannick.

**Comment by Jerther** [comment]
Sure.
Ticket # 1858689

**Comment by aab-odoo** [comment]
As answered on the ticket, we'll fix it in v11.
Workaround for v10: attrs="{'invisible': ('text_field', '=', False)}"

**Pull request closed without merging**
