### PR TITLE
[FIX] web_editor: convert bootstrap grid offsets to individual cells

### PR DESCRIPTION
**Pull request by Zynton**
When a column has an offset, the size of the column was computed by adding the column's value and the offset value. This breaks the expected position of the column. This creates a separate, empty column for the offset instead.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@Zinston This PR will conflict with https://github.com/odoo/odoo/pull/91623 so I guess the best course of action considering this one is red is to wait for the forward port of the other.

**Comment by Zinston** [comment]
@dmo-odoo Ok for me. FYI this is actually part of a branch by @edi-odoo, she still has to reference her enterprise side once there's a PR for it.

**Comment by dmo-odoo** [comment]
@Zinston FYI the fwport of https://github.com/odoo/odoo/pull/91623 has been done.

**Comment by C3POdoo** [comment]
Dear @Zynton,

Thank you for your contribution but the version saas-15.3 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
