### PR TITLE
[FIX] web: open dropdown in dashboard correctly

### PR DESCRIPTION
**Pull request by yelizariev**
STEPS:
* install Dashboards app
* add few pivots to Dashboard (e.g. Sales >> Pivot view >> Favorites >> Add to
my dashboard)
* open Dashboards app
* Click "Change Layout" and select any multicolumn
* place pivots on different colums
* click "+" in pivots columns

BEFORE: dropdown menu is shifted

AFTER: dropdown menu is in proper place

WHY: the bug is appeared after #37385

---

opw-2371927

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
@tivisse

**Comment by kebeclibre** [comment]
I think I approve, it is anyway more correct than before.
Make sure to test some other configuration (mobile, smaller viewport).
I'd check the behavior of other dropdown in similar circumstances.

**Comment by yelizariev** [comment]
# Tested on different dashboards
 <details>

screenshot-devel 13 localhost_13069-2020 11 13-09_10_14 (5)
screenshot-devel 13 localhost_13069-2020 11 13-09_10_14 (4)
screenshot-devel 13 localhost_13069-2020 11 13-09_10_14 (3)
screenshot-devel 13 localhost_13069-2020 11 13-09_10_14 (2)
screenshot-devel 13 localhost_13069-2020 11 13-09_10_14 (1)
screenshot-devel 13 localhost_13069-2020 11 13-09_10_14
</details>

# On small screens
(this ugly look is another issue -- current 13 version shows the same without this PR)
<details>

screenshot-devel 13 localhost_13069-2020 11 13-09_17_58 (2)
screenshot-devel 13 localhost_13069-2020 11 13-09_17_58 (1)
screenshot-devel 13 localhost_13069-2020 11 13-09_17_58
</details>

# On mobile
<details>

image
image
image

</details>

**Comment by yelizariev** [comment]
@nle-odoo please review

**Review by nle-odoo — COMMENTED** [review]
looks good for the issue, but this reintroduce right-to-left issue that was the reason we used the mouse position instead of left value: https://github.com/odoo/odoo/commit/d021f4257c87863b75f148c4809f5e2797a1e99f

> 
2020-11-13-095354_902x474_scrot

but if we want to keep the positioning introduced by 989df08fd8bbfa4a1f05784b599b1657a9b28fe5 I think this is the right direction (but right-to-left should be handled as well)

**Comment by yelizariev** [comment]
Thank you, I'll check what could be a solution
css

**Comment by yelizariev** [comment]
Done!
I'm sorry for making French language RTL :laughing: I feel strange when I see it :nauseated_face: 
screenshot-devel 13 localhost_13069-2020 11 13-13_30_27
screenshot-devel 13 localhost_13069-2020 11 13-13_30_27 (1)
screenshot-devel 13 localhost_13069-2020 11 13-13_30_51
screenshot-devel 13 localhost_13069-2020 11 13-13_31_00

**Review by nle-odoo — APPROVED** [review]
looks nearly ready to merge

in RTL, the horizontal value will be:

```
right: this.$el.width() - ev.clientX + $container.position().left - $pivot.width()
```

it seems that `this.$el.width()` and `$pivot.width()` are the same, so maybe you can simplify this by having RTL condition only on one side:

```diff
- a/addons/web/static/src/js/views/pivot/pivot_controller.js
+++ b/addons/web/static/src/js/views/pivot/pivot_controller.js
@@ -174,7 +174,7 @@ var PivotController = AbstractController.extend({
 
         var cssProps = {top: top};
         var isRTL = _t.database.parameters.direction === 'rtl';
-        cssProps[isRTL ? 'right' : 'left'] = isRTL ? this.$el.width() - left : left;
+        cssProps[isRTL ? 'right' : 'left'] = isRTL ? -left : left;
         this.$groupBySelection.find('.dropdown-menu').first().css(cssProps).addClass('show');
     },
     /**
@@ -302,10 +302,6 @@ var PivotController = AbstractController.extend({
             // in rtl mode, position().left is distance of the right side to the left part of screen
             // while the rest values have the same meaning
             var container_left = $container.position().left;
-            if (_t.database.parameters.direction === 'rtl'){
-                // convert position.left to a usual meaning
-                container_left -= $pivot.width();
-            }
```

when you are ready to merge:

robodoo delegate+

**Comment by yelizariev** [comment]
@robodoo r+ пора

**Pull request closed without merging**
