### PR TITLE
Master l10n fiscal positions sig

### PR DESCRIPTION
**Pull request by simongoffin**
add missing columns in account.fiscal.position.template to match account.fiscal.position

configure EU fiscal positions in l10n_\* modules of EU countries

### CODE REVIEW

**Comment by antonylesuisse** [comment]
@qdp-odoo Still missing in v9 ?

**Comment by qdp-odoo** [comment]
err...yes

even more fields are missing since we added new ones.

**Comment by qdp-odoo** [comment]
heu??? I don't think it has been merged, why do you close it?

**Comment by qdp-odoo** [comment]
@nim-odoo Couldn't you act even more mysteriously?

**Pull request closed without merging**
