### PR TITLE
Show AMOUNT DUE (not AMOUNT TOTAL) on Dashboard

### PR DESCRIPTION
**Pull request by raycarnes**
Description of the issue/feature this PR addresses:

If there are payments made on Invoices and Bills, then the dashboard really shows an incorrect amount - it still shows the AMOUNT TOTAL of the Invoices and Bills. 

Current behavior before PR:

Given the following Invoices and Bills, with respective AMOUNT TOTAL and AMOUNT DUE:

image

image

**Note that 16,763.99 above is the Total of Validated and Draft Bills, and the dashboard before the changes (shown below) shows a total of $16,749.99 which doesn't include the $14.**

The AMOUNT TOTAL is shown on the Accounting Dashboard:

image

Desired behavior after PR is merged:

The AMOUNT DUE is shown on the Accounting Dashboard:

image

Testing:

I exported the Kanban Dashboard JSON field of the Journal and checked that both sum_waiting and sum_late were correctly calculating:

CUSTOMER INVOICES JOURNAL: {"number_to_reconcile":   0, "account_balance": "$ 0.00", "last_balance":   "$ 0.00", "difference": false, "number_draft":   0, "number_waiting": 4, "number_late": 4, "sum_draft":   "$ 0.00", "sum_waiting": "$ 7,785.00",   "sum_late": "$ 7,785.00", "currency_id": 3,   "bank_statements_source": "undefined", "title":   "Invoices owed to you", "num_checks_to_print": 0}

VENDOR BILLS JOURNAL: 

{"number_to_reconcile":   0, "account_balance": "$ 0.00", "last_balance":   "$ 0.00", "difference": false, "number_draft":   1, "number_waiting": 3, "number_late": 3, "sum_draft":   "$ 14.00", "sum_waiting": "$ 14,000.00",   "sum_late": "$ 14,000.00", "currency_id": 3,   "bank_statements_source": "undefined", "title":   "Bills to pay", "num_checks_to_print": 0}

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@qdp-odoo what do you think about this?

**Comment by avw-odoo** [comment]
Hello @pedrobaeza you can look at this https://github.com/odoo/odoo/pull/25344 (master)

**Comment by qdp-odoo** [comment]
ha! you're too slow, @avw-odoo

**Comment by pedrobaeza** [comment]
Thanks both for the info. Then closing this one as solved in master, but not suitable for stable.

**Comment by qdp-odoo** [comment]
No, it's not really the same: in master we changed the graph of sales/purchase journals to show the residual amount, but the figure given in the spot shown in Ray's screenshots are untouched.

That's why I propose to keep this PR, but simply re-target master

**Comment by pedrobaeza** [comment]
Ah, OK, sorry for the misunderstanding.

**Comment by raycarnes** [comment]
Closing - I don't know how to simply re-target master so I'll create a new PR.

**Pull request closed without merging**
