### PR TITLE
[FIX] stock_account: inventory in multi-company

### PR DESCRIPTION
**Pull request by nim-odoo**
opw-1943384

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
kept for reference, but should not be merged

**Comment by nim-odoo** [comment]
@sle-odoo did you have time to check? Thanks

**Comment by sle-odoo** [comment]
@nim-odoo looks good but i would go one step further and handle the company_id on the production location. i juste encountered the bug and the scenario is reproducible in v11.

**Comment by sle-odoo** [comment]
``` diff
diff --git a/addons/stock_account/models/stock.py b/addons/stock_account/models/stock.py
index 20775a8289c..9c663166a2d 100644
--- a/addons/stock_account/models/stock.py
+++ b/addons/stock_account/models/stock.py
@@ -166,7 +166,9 @@ class StockMove(models.Model):
                 '|',
                     ('location_id.company_id', '=', False),
                     '&',
-                        ('location_id.usage', '=', 'inventory'),
+                        '|',
+                            ('location_id.usage', '=', 'inventory'),
+                            ('location_id.usage', '=', 'production'),
                         ('location_id.company_id', '=', company_id or self.env.user.company_id.id),
                 ('location_dest_id.company_id', '=', company_id or self.env.user.company_id.id),
         ]
@@ -190,7 +192,9 @@ class StockMove(models.Model):
                     '|',
                         ('location_id.company_id', '=', False),
                         '&',
-                            ('location_id.usage', '=', 'inventory'),
+                            '|',
+                                ('location_id.usage', '=', 'inventory'),
+                                ('location_id.usage', '=', 'production'),
                             ('location_id.company_id', '=', company_id or self.env.user.company_id.id),
                     ('location_dest_id.company_id', '=', company_id or self.env.user.company_id.id),
                 '&',
```

**Comment by nim-odoo** [comment]
`('location_id.usage', 'in', ['inventory', 'production'])` should work as well, right?

**Comment by sle-odoo** [comment]
yep

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
