### PR TITLE
[FIX] purchase: pricelist and related currency mismatch on purchase orde...

### LINKED ISSUE #4598: [8.0] pricelist and related currency mismatch on purchase order (Bid received)
To reproduce:
- activate Purchases -> `Manage pricelist per supplier` and `Accounting -> Allow multi currencies `
- Create a second pricelist with another currency
- Open a Request for Quotation
- Pass it to Bid received

Pricelist is editable and currency is readonly
- Try to change pricelist

Result:
pricelist and currency doesn't match

Expected:
Disallow change of pricelist in state Bid received?

### PR DESCRIPTION
**Pull request by simongoffin**
...r (Bid received).

pricelist must be readonly when currency is readonly because there 's an onchange on currency which depends
on the pricelist.

opw:627009
Fixed #4598

### CODE REVIEW

**Comment by beledouxdenis** [comment]
I'm not sure that reversing the readonly logic is a good idea in stable releases (such as 8.0):
Modules could have overrode this field and based their readonly logic according to the present logic. This is unlikely, but this is a possibility.

It makes sense to not allow the change of pricelist in your case, in Bid received state, but what happens if a module added a new state to the purchase order, that should allow the change of pricelist ? Your change will prevent this.

Is it not possible to change this behavior in the bid module itself ?

I would gladly welcome @yvaucher or @lepistone opinions :).

In master it would have make sense.

**Comment by yvaucher** [comment]
@simongoffin @beledouxdenis Most important thing here is to ensure pricelist and currency field are synced. It makes more sense to have them in the exact same logic and make it simple.

In any case, if someone added a state, he would have had 2 options:
- redefine the logic on one of those 2 fields and override states and readonly
- or define 2 opposed logics.

First option is the simplest as @lepistone did it in https://github.com/lepistone/purchase-workflow/commit/10a7c755eb5e3e848f5ba5c1ed3553edc7d8c43b
(thought we were only fixing the bug without adding new state)
So if someone did a change it is more likely that way. This fix won't have a bad impact on it as states and readonly are overriden.

Nevertheless, even if someone if someone was aware of this issue (not reporting it) and went for the second option, he could change the logic of `pricelist_id`, taking logic from `currency_id`. It should be an easy fix.

:+1: for this fix in 8.0 and thanks for that

**Comment by beledouxdenis** [comment]
I agree with you on the fact the readonly states of currency_id and pricelist_id should be synced.

Nevertheless, since the currency_id has been introduced recently (9b31288c14613f62bd339dd29050e570100c088e), so its states attribute, I believe it would be safer to do the opposite of what @lepistone did: I would list the states in which the fields should be readonly=True instead of listing the fields where the readonly should be False.

Indeed, 
 - The dict ```{'confirmed':[('readonly',True)], 'approved':[('readonly',True)],'done':[('readonly',True)]}``` is repeated in 4 fields (partner_id, dest_address_id, location_id, pricelist_id)
 - At the moment, if a module add a new state in the field "state", by default, if the module does not override the states attribute of the above fields, these fields will be not readonly. If we do what proposes @lepistone, the above fields will be readonly by default for new states. It would therefore change the behavior, which is not accepted in a stable release such as 8.0.

I would therefore recommend to make a global dict above the fields definition:
```
READONLY_STATES = {
    'confirmed':[('readonly',True)], 
    'approved':[('readonly',True)],
    'done':[('readonly',True)]
}
```

And set ```states=READONLY_STATES``` on the 5 following fields:
 - partner_id
 - dest_address_id
 - location_id
 - pricelist_id
 - currency_id

Do we all agree on this ?

**Comment by yvaucher** [comment]
@beledouxdenis I have no strong opinion on this. Having `READONLY_STATES` could be clearer without the `readme=True`. (and using same logic on all fields is even better) So, I agree.

**Comment by beledouxdenis** [comment]
@simongoffin I believe you can proceed to the new fix according to my comment https://github.com/odoo/odoo/pull/5505#issuecomment-76388150.

**Comment by lepistone** [comment]
@beledouxdenis I don't have a preference on which way we go as soon as all those fields are defined the same way. A dict is the way to go (maybe member of the class instead of global, but that's a detail).

So I agree with your proposition @beledouxdenis, thanks!

**Comment by beledouxdenis** [comment]
@simongoffin 
The new commit is perfect to me. Add 'Courtesy of @lepistone' in the commit message and you can merge in stable release. Thanks !

**Comment by beledouxdenis** [comment]
Well, did not see it was already merged.

Issue closed with rev. 631d2f71461eda852b41a429c782772c5d97f2fe.

**Pull request closed without merging**
