### PR TITLE
[IMP] pos_order : add pivot view

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
pos_order : add pivot view

@switch87

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by switch87** [comment]
@fmdl can you change the commit message to "[IMP] point_of_sale: add pos_order pivot view"?

@mart-e @pimodoo

**Comment by switch87** [comment]
@fmdl I did the rewording for you ;) Thank you for the pr.

**Comment by mart-e** [comment]
Thanks for the PR. There is no pivot table defined at the moment, shouldn't we add one?
As this is an improvement, it should target the master (or still ok for saas-12.5)

**Comment by pimodoo** [comment]
@mart-e @fmdl Can you rebase and target saas-12.5

**Comment by mart-e** [comment]
Thanks for the update
@robodoo r+

**Pull request closed without merging**
