### PR TITLE
[IMP] l10n_pe: Completed data for Peruvian banks

### PR DESCRIPTION
**Pull request by desdelinux**
Provides data on Peruvian Banks extracted from the Central Reserve Bank of Peru https://www.bcrp.gob.pe/sitios-de-interes/entidades-financieras.html

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by desdelinux** [comment]
cc @vbe-odoo @jco-odoo

**Comment by jco-odoo** [comment]
@desdelinux @vbe-odoo I am a bit concerned that people might have configured banks themselves.  So, they would upgrade the module and they would see the banks twice.  We can do this for master of course.

**Comment by desdelinux** [comment]
> @desdelinux @vbe-odoo I am a bit concerned that people might have configured banks themselves. So, they would upgrade the module and they would see the banks twice. We can do this for master of course.

@jco-odoo I agree with you, this should go to maste

cc @vbe-odoo

**Comment by vbe-odoo** [comment]
@desdelinux agree that should target master. Can you @desdelinux change the target version? Thanks!
cc' @jco-odoo

**Pull request closed without merging**
