### PR TITLE
[ADD] add function to convert amount to Chinese word

### PR DESCRIPTION
**Pull request by jeffery9**
Description of the issue/feature this PR addresses:

add amount to Chinese word

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by OpenERPJeff** [comment]
Good work

**Comment by cialuo** [comment]
顶

**Comment by zhangshunrao** [comment]
praise

**Comment by EvanWang2016** [comment]
Good

**Comment by 39181819** [comment]
强贴留名。

**Comment by mart-e** [comment]
Hello,

Sorry but we already had this (long) discussion on #12542 and we are in favor of adding a new library instead. It will be done internally.

**Pull request closed without merging**
