### PR TITLE
Avoid task work lines to be created twice (fixes #7391)

### LINKED ISSUE #7391: New task work line was created twice
Occasionally users report that Task Work lines are created twice: the user adds a line, saves the Task and finds that two lines were saved. 

I was not able to reproduce the issue, but here is an example:
snap 2015-07-01 at 09 55 15

Checking on the database records I can see that the creation timestamp of theduplicate lines is 5 seconds apart:
snap 2015-07-01 at 09 52 12

I'm clueless of what might be the cause, and I'm curious if someone else was bitten by the same issue. 
Any help is appreciated.

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by mart-e** [comment]
Any idea why we can reproduce that only on project.task.work?
Looks like fixing the symptoms (duplicated lines) instead of the cause (preventing making two write calls). Also the user double clicking on save would get a duplication error while we would like the second one to just be ignored.

**Comment by dreispt** [comment]
On #7391 there are reports of similar issues on other models. I just tested and easily reproduced the problem on Sales Orders. My guess is that it is related to the `mail` features.

Yes this acts on the symptoms and not on the underlying cause, but I suspect it won't be simple to fix (could even be on the Javascript side).
But it does prevents the user from introducing wrong data that could cause, for example, to wrongly invoicing in double the actual work done.

**Comment by mart-e** [comment]
I tired on several models and could only reproduce it on project tasks but if you say you can do it on sale.order it means the unique constrain is not the right way to fix it (I would tend to a JS fix).
I will set this PR as blocked until somebody can shed some more light on the cause of the issue.

**Comment by dreispt** [comment]
That's blocking a temporary workaround because you don't have the definitive solution.
In the meanwhile the bug is uncontrolled and causes wrong data to be recorded in the system.

**Comment by dreispt** [comment]
Updating this: can anyone add some insight on what might be the root cause?

**Comment by dreispt** [comment]
Ping!

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards

**Pull request closed without merging**
