### PR TITLE
[FIX] web_editor: support youtube-nocookie.com

### PR DESCRIPTION
**Pull request by qsm-odoo**

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
robodoo retry

**Comment by KangOl** [comment]
robodoo retry

**Comment by KangOl** [comment]
robodoo retry

**Pull request closed without merging**
