### PR TITLE
[IMP] core: support customized code translation

### PR DESCRIPTION
**Pull request by HydrionBurst**
## UI:
image

1. open `Customized Code Translations` in the `Settings`
2. create translation in the list view
or
1. import po files with customized code translations
2. customized translations will be in the `Customized Code Translations`

## Technical:
image

native code translations:
1. statically defined in the po file of the code directory
2. and cached in the python memory per worker as a dict

customized code translations:
1. dynamically defined in the records of model `ir.customized.code.translation`
2. and cached in the ormcache per registry in each worker

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hi there! Your solution seems like a possible feasible solution for a lot of the problems we run into on V16. What is the timeline for this idea and will it also get a backport into V16?

**Comment by Yenthe666** [comment]
Well that could be easily solved by just making it an extra app which lands in V16 & can be manually installed? :)

**Comment by sum1201** [comment]
How long will it take to get approved? It won't be exclusive to odoo 17, will it? If so, it would be so disappointing...

**Comment by HydrionBurst** [comment]
extra module in stable version, and merge it to base increse the complexity of database upgrade. So we try to avoid it.
 
This PR should be merged before Odoo 17

**Comment by Yenthe666** [comment]
Just an idea, perhaps in the core the function could be split in a few subfunctions so you can hook into it with the new app? That way it is easy manageable and will be supported by default in V17.
Best of both worlds? We're really looking for solutions here, it is hurting us in multiple projects.

**Comment by sum1201** [comment]
I believe that many people are abandoning it because of translation problems. Either pick 15 or wait for 17. If the translation problem is not resolved, odoo 16 will be a very embarrassing existence, and it will hurt all users.

**Comment by Yenthe666** [comment]
We as a partner have put multiple migrations on hold waiting for how V17 looks. Companies that run multi-language and use subscriptions go a step back if they move to V16 coming from V14 or V15 in my feeling.

**Comment by Ranamiu** [comment]
Hi all, 

We are experimenting the same, have to block update to 16 because of this issue.

Kindly, any chance to have this fix running on Odoo 16 ?

Please. let us know.

Appreciate

**Comment by david-fleischmann** [comment]
Hi all, came from this issue here: https://github.com/odoo/odoo/issues/115876 touching the same problem.
We're facing the same and have a lot of trouble explaining this to customers we've recently migrated to V16. This is a real issue! Please take care and also release a patch for v16, otherwise we really have some customers loosing faith in odoo.

My use case:
V15 was easily to translate: 
image

In V16 csv nor po file import are working for code type terms.

Best 
David
Zebroo GmbH
zebroo.de

**Comment by Ranamiu** [comment]
Hi @david-fleischmann 

Greetings !!

Agree 100%: such a issue is making our customers, and Odoo partners, deeply rethink  about Odoo core values.

I have always said Odoo 16 is such a magnificent machine.

That being said, translations are a crucial core item that cannot be executed as on current way.

As you said, that is a real big issue that needs to be fixed ASAP.

Not only on Odoo 17, also on current stable Odoo 16.

Appreciate your attention

Greetings

**Comment by Yenthe666** [comment]
@HydrionBurst so what is the idea/plan here? As you can see a lot of partners/customers are impacted. We need a solution for V16..

**Comment by HydrionBurst** [comment]
After some discussions, we decide to close this task to avoid increasing the complexity of code translations.
The code translations should keep static and the same for all workers.
If the code translation is wrong, you can only modiy it by
1. updating the xx.po file directly
2. customizing in the i18n_extra/xx.po

**Comment by Yenthe666** [comment]
Okay so what about functionals/end customers using Odoo who cannot (don't know) how to update translations in po files? :) 
In previous versions they could go through translated terms or export/import a po file. Both do not work anymore in V16..

**Comment by HydrionBurst** [comment]
It think it should be maintained by service provider but not the functionals/end customers. If there is a wrong/missing translation, contribute using Transifex. If you want to customize for your customers, change the po yourself.

**Comment by Ranamiu** [comment]
That way, what about multi database instances?

Modifying core PO files will hurt Odoo as multi database systen because we will be not able, even as providers,  to use different core translations depending on each database.

How to fix this Fürther issue?

Appreciate

**Comment by HydrionBurst** [comment]
> Modifying core PO files will hurt Odoo as multi database systen because we will be not able, even as providers, to use different core translations depending on each database.

We believe it an acceptable use case. Customers don't really need different translations in different companies/database. They can share/accept the same translation.

**Comment by Ranamiu** [comment]
Hi @HydrionBurst 

Thanks for your answer.

Not so easy in real world, dear. It deeply depends from business segments, from individual clients, from clients that are clients of our clients, etc.

Software should be always clients oriented, doing this way Odoo 16 is hurting user experience.

That Is not really good.

Sad to hear this, Odoo 16 back to the past.

We have a great machine damnaged by a translation.

Sad.

Thanks for your attention

**Comment by pedrobaeza** [comment]
For me, needing to modify the terms per database means that you are trying to implement a business case using the translations as the tool to do it, or trying to continue with old terminology. Example: a lot of customers ask us to rename products to articles, because their old software calls this way, or their industry usually calls it that way. Adaptation to the new terminology takes one week.

**Comment by Ranamiu** [comment]
Hi all @HydrionBurst @pedrobaeza @Yenthe666 :

Greetings of the day!!

A new critical case, showing up we urgently need translations to be fully customizable, and per single database.

We will probably loose our client because of this.

Client requires us a correct and gramatically compliant translations. We cannot offer this on a multi database server.

How many Odoo clients are we going to loose because of this ?

Please @fpodoo, have a check on this issue.

The following, important, end user communication from POS recepit, cannot be traanslated  through  export-import of PO file.

PO database import does not work.

¿Which seriuos client of us  would accept this poor text?

```
/usr/lib/python3/dist-packages/odoo/addons/point_of_sale/i18n

#. module: point_of_sale
#. odoo-python
#: code:addons/point_of_sale/models/pos_order.py:0
#, python-format
msgid "<p>Dear %s,<br/>Here is your electronic ticket for the %s. </p>"
```

I hope you understand the severity of this issue

Appreciate your attention all guys

BR

**Comment by pedrobaeza** [comment]
If you don't agree with the text in English, please propose a better wording doing a pull request:

https://github.com/odoo/odoo/wiki/Contributing

If a translation to any language is not correct, please translate it correctly:

https://github.com/odoo/odoo/wiki/Translations

If you lose your customer, it's just because you haven't dedicated enough time to know how is the ecosystem where you have decided to do business, not because the impossibility of doing translations.

**Comment by Ranamiu** [comment]
I would avoid to get into "you" personal arguments.

That way,  let me think there are no arguments from your side.

You probably have not really got the issue @pedrobaeza 

Please, read it carefully.

And apologies me, in case I am wrong.

It is not a translation issue.

Our client wants a customised message in order to send out any receipt from post.

Explain us, here  and everyone, please:

How to get it, on a multi database, of course ?

Appreciate 

Greetings

**Comment by HydrionBurst** [comment]
I would say don't hack a technic tool for a feature it is not designed for, no matter how easy it is.
The code trasnaltion is for translation, but not for template placeholder identifier
If you need the content to be customizable, maybe you should contact the POS team and ask them to provide the feature

**Comment by pedrobaeza** [comment]
Or develop a custom extension to customize that message... This is not a no-extensible system like other fully-closed software packages where the only chance for you to do what you want is to ask the manufacturer to develop it.

Of course every feature included already in core is desired, but there are so many possibilities for features that may benefit individual interests, that it's impossible to satisfy all of them, or not compromising other paradigms (usability, performance, etc). For those, you have the modular extension system that allows you to do it.

Said that, it's true that the commercial approach that Odoo S. A. has taken, leads to these complaints, as they are stating that no developer is needed for implementer companies, just reselling and consulting activities, which I strongly disagree.

**Comment by Ranamiu** [comment]
Thank you all guys here @pedrobaeza  and @HydrionBurst  because of mantaining our conversation on a calm and "nonviolent" side.

I appreciate your answer.

And I appreciate your work, we know (and deeply appreciate) how much each of you e.g. Pedro @pedrobaeza works on local OCA.

Our goal and motivation is just one: improving Odoo.

It seems Odoo 17 overcomes this issue, a great news for all us.

It would have been great getting also an official Odoo S.A. fix for Odoo 16.

I am just giving feedback from clients side.

Thank you for your attention.

Greetings of the day!

**Pull request closed without merging**
