### PR TITLE
[MERGE] api.py: remove calls to @api.multi and deprecate its explicit usage

### PR DESCRIPTION
**Pull request by Elkasitu**
depends on https://github.com/odoo/odoo/pull/34556

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+ merge

**Comment by tivisse** [comment]
@robodoo r-

**Comment by tivisse** [comment]
@robodoo r+

I would prefer to log a warning during one version instead of simply crashing, but apparently this is a fp request. So let it be.

**Comment by Yenthe666** [comment]
So, where is the documentation update / info about this? Does this mean that by default there won't be `api.one` and `api.multi` on the functions anymore and that every function without a decorator is automatically handled by the system?

**Comment by d-fence** [comment]
@robodoo r+ merge p=0

**Comment by Elkasitu** [comment]
@Yenthe666 Proper documentation updates will come in due time, but in both this and the `api.one` PRs I managed to edit some of the relevant doc, but the bare minimums.

In V13:
`api.one` has ben deprecated since V9 for a number of reasons, we just finally pulled the plug on it
`api.multi` is the default policy (self is a recordset), so using the decorator literally changes nothing, this has been the case since V10 I think?

**Comment by d-fence** [comment]
robodoo delegate=Elkasitu

**Comment by Elkasitu** [comment]
robodoo r+ merge p=0

**Comment by d-fence** [comment]
robodoo r+ merge p=0

**Comment by Yenthe666** [comment]
Thanks a lot for the clarification @Elkasitu :)

**Pull request merged**
