### PR TITLE
[FIX] web_tour: make manual tours work again 

### PR DESCRIPTION
**Pull request by pipu-odoo**
From 7edefbf140d68f7dd4d5238428b7a95509e6e081, manual tour no longer work. This commit fixes this error.

### CODE REVIEW

**Comment by pipu-odoo** [comment]
@kebeclibre I've force-push a new correction => Could you r+ :angel:

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo r-

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Comment by aab-odoo** [comment]
@pipu-odoo if it doesn't get merged by Monday, you should rebase it. You're still before jum's fix in hoot (memory leaks), so the suite fails (a lot)

**Pull request closed without merging**
