### PR TITLE
[FIX] uom : hard to edit factor

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
In some screen it is very hard to edit the factor.

**Current behavior before PR:**
image

**Desired behavior after PR is merged:**
image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@simongoffin

**Comment by fmdl** [comment]
OPW #2463945

**Comment by fmdl** [comment]
cc @mart-e

**Comment by fmdl** [comment]
ping @amoyaux

**Comment by abz-odoo** [comment]
@odoo/rd-logistics

**Comment by Whenrow** [comment]
@fmdl This field is set to 1 by default. You should not have this small input field anymore

**Comment by fmdl** [comment]
@Whenrow  it is a pure graphique issue, on some size screen it is not possible to modify the field, see the video

https://user-images.githubusercontent.com/16716992/122369767-c7bf2380-cf5e-11eb-88c3-718ef0ab65a3.mov

**Comment by Whenrow** [comment]
@fmdl Ok I now understand the issue. Thank you
robodoo r+

**Pull request closed without merging**
