### PR TITLE
Added CLA for Bringsvor Consulting AS.

### PR DESCRIPTION
**Pull request by bringsvor**
CLA for Bringsvor Consulting AS.

### CODE REVIEW

**Comment by mart-e** [comment]
@bringsvor you are committing with an email `torvald@` but your CLA is for an email `bringsvor@`.
Which one is correct ? You can also have several contributors.

**Comment by bringsvor** [comment]
Hi

I read both, but bringsvor@bringsvor.com is the one I try to use for
company correspondence. Also it is the one tide to my github account. Sorry
for the confusion.

Torvald Baade Bringsvor
Bringsvor Consulting AS - Odoo (formerly OpenERP) implementation partner

2015-04-14 9:40 GMT+02:00 Martin Trigaux <notifications@github.com>:

**Comment by mart-e** [comment]
No problem, but you need to either add both emails in CLA signature, either to configure your local git to use bringsvor@ for this repository (and repush the commits with the correct email).

**Comment by bringsvor** [comment]
I have updated the CLA now, is that OK?

-Torvald

Torvald Baade Bringsvor
Bringsvor Consulting AS - Odoo (formerly OpenERP) implementation partner

2015-04-14 9:58 GMT+02:00 Martin Trigaux <notifications@github.com>:

**Comment by mart-e** [comment]
Great, thanks, I have merged it at 4a11cce93d952c30ffac8e055647f0b3f0227438 (and put the emails on one line, should work as well)

**Pull request closed without merging**
