### PR TITLE
[FIX] *: fix domain definition (not) in operator

### PR DESCRIPTION
**Pull request by vava-odoo**
*account, account_peppol, purchase_requisition, stock_delivery, base

There are some conditions in xml that uses `in` or `not in` for a check with a string. These are replace by `==` or `!=` operators, respectively.

### CODE REVIEW

**Comment by ticodoo** [comment]
Looks like this is leftover from some old old old way of writing domains. Doing a search for `not in '` in .xml files pops up a few domains using it. Not sure if you prefer to fix them all in one PR (all 7 of the ENT ones are also valid to be fixed)
image

Seems like the domain still works correctly anyways though, it probably doesn't really matter except for code cleanup.

**Review by ticodoo — APPROVED** [review]

**Comment by vava-odoo** [comment]
Enterprise PR: https://github.com/odoo/enterprise/pull/46199

**Comment by ryv-odoo** [comment]
Hello @vava-odoo , 
LGTM.
Can you change the tag of the commit please into `[FIX]` (it still works but the semantic isn't correct)?
Thank you for your work.
Issue coming from: https://github.com/odoo/odoo/pull/104741

**Comment by vava-odoo** [comment]
> Can you change the tag of the commit please into `[FIX]` (it still works but the semantic isn't correct)? 

Hi @ryv-odoo, thanks for reviewing. Change has been applied :+1:

**Comment by ryv-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
