### PR TITLE
[IMP] web,web_settings_dashboard: Move 'About' menu to settings dashb…

### PR DESCRIPTION
**Pull request by tivisse**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

…oard

Fp request: In the user preferences menu, remove "About Us" and put the version
number in the Settings dashboard somewhere, as well as the link to switch to
developer mode. Odoo is not a desktop application anymore.

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
+ missing task link, please do not forget to put them

**Comment by dreispt** [comment]
Isn't this merged into master? Why can I still see the "About" box option on Runbot?

**Comment by tde-banana-odoo** [comment]
It has been reverted due to some discussion about the layout and the dev mode. It has been merged a bit quickly.

**Comment by dreispt** [comment]
Ah! Thanks!

**Pull request merged**
