### PR TITLE
[saas-12.5] base_vat, l10n_pe: fixes to allow installation and use of l10n_pe

### PR DESCRIPTION
**Pull request by umiphos**
Description of the issue/feature this PR addresses:

base_vat does not need to check the structure and letters of the VAT because we are already adding a field for the type of document in l10n_latam_base(l10n_latam_identification_type_id), this field does what the logic in the module did before. 

Now, all the future developments should only use the VAT and l10n_latam_identification_type_id and not split_vat, that method is no longer useful is we use the latam modules. This module will be left only to validate the structure and checksum of the VAT document type.

FIX 2: Adding a field to the data we have in l10n_pe to avoid a traceback when installing the module

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by umiphos** [comment]
@jco-odoo we need this 2 fixes in order to allow l10n_pe to be installed and to allow l10n_pe_edi to work as expected. Can you review pls?

**Comment by jco-odoo** [comment]
@umiphos I will change for using the offset balance account created in the account module instead, see #36432

**Comment by umiphos** [comment]
@jco-odoo do you agree to the change in base_vat? if yes to make that change in another PR and wait for the PR you mentioned earlier #36432.

**Comment by umiphos** [comment]
Closing this merge because we are going to make a cleaner option once #36432 is merged

**Pull request closed without merging**
