### PR TITLE
[12.0] [FIX] product: apply fixed price digits in pricelist item form view

### PR DESCRIPTION
**Pull request by FFernandez-PlanetaTIC**
**Description of the issue/feature this PR addresses:**

Apply fixed price / product price digits in pricelist item form view.

**Current behavior before PR:**

Currency digits applies.

**Desired behavior after PR is merged:**

Fixed price / product price digits applies.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@dbo-odoo what do you think about this?

**Comment by dbo-odoo** [comment]
I don't understand why you'd want this, I expect the currency rounding to be applied here. Can you explain your reasoning?

**Comment by FFernandez-PlanetaTIC** [comment]
Hi @dbo-odoo ,

I expect the _Product Price_ decimal precision (4 digits in this example):

https://github.com/PlanetaTIC/odoo/blob/12.0-fix-product-pricelist_item_form_view_fixed_price_digits/addons/product/models/product_pricelist.py#L455

image

As in _Sales price_ of producte templates:

https://github.com/PlanetaTIC/odoo/blob/12.0-fix-product-pricelist_item_form_view_fixed_price_digits/addons/product/models/product_template.py#L69

https://github.com/PlanetaTIC/odoo/blob/12.0-fix-product-pricelist_item_form_view_fixed_price_digits/addons/product/views/product_views.xml#L52

image

And _Unit price_ of sale orders:

https://github.com/PlanetaTIC/odoo/blob/12.0-fix-product-pricelist_item_form_view_fixed_price_digits/addons/sale/models/sale.py#L1144

image

**This is very common in bulk products with low price such as screws.**

Regards

**Comment by dbo-odoo** [comment]
Indeed, when comparing that to these other fields it makes sense - and your use case for small fixed prices of bulk items adds to it.

Could you modifiy the commit message to reflect that?

e.g.
```
[FIX] product: apply fixed price digits in pricelist item form view

Since unit prices in sales order lines and list prices in the product form
view also use the same decimal precision (`Product Price`), it makes sense
to show all the precision digits when dealing with fixed prices in a pricelist rule.

While the precision on the field's declaration was correct, its widget used the
decimal precision of the currency by default. This commit forces the monetary
widget to use the field's precision instead.
```

thx!

**Comment by FFernandez-PlanetaTIC** [comment]
Done, thanks!

**Comment by dbo-odoo** [comment]
Thx for your contribution!

@robodoo r+

**Pull request closed without merging**
