### PR TITLE
[IMP] wording

### PR DESCRIPTION
**Pull request by fhe-odoo**
en_US police reporting in

### CODE REVIEW

**Comment by Yenthe666** [comment]
@fhe-odoo can you also please change `Quantity per Package` to `Quantity per package`?
Package is with a capital while it is in the middle of a sentence, thats not logical. I see this in Odoo all the time. :frowning:

**Comment by fhe-odoo** [comment]
@Yenthe666 Well, it's not a sentence, it's a label. And Odoo adopts the capital letters on main words of labels. That's the case (pun intended) all across the application. So I cannot change this. This is a very widespread UX practice.

**Comment by Yenthe666** [comment]
@fhe-odoo I actually didn't even know this.. Thanks for pointing this out though!

**Comment by mart-e** [comment]
merged at 520c42b, thanks

**Pull request closed without merging**
