### PR TITLE
[I18N] *: re-export 18.0 pot files

### PR DESCRIPTION
**Pull request by ticodoo**
Some were missing, some terms were added after the original pot push due to delayed freeze time.

ENT PR: https://github.com/odoo/enterprise/pull/70779

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by dylankiss — APPROVED** [review]

**Comment by ticodoo** [comment]
@robodoo r+

please no conflcits :pray:

**Comment by ticodoo** [comment]
@robodoo r+

**Comment by ticodoo** [comment]
@robodoo r+

**Comment by ticodoo** [comment]
@robodoo r+

please work :pray:

**Pull request closed without merging**
