### PR TITLE
[FIX] web: update owl to last version

### PR DESCRIPTION
**Pull request by aab-odoo**
This commit updates owl from v1.2.0 to v1.2.1

See [1] for the list of changes.

[1] https://github.com/odoo/owl/commit/25738a1bf08ff47b2d8cb7b7c57d3bf4a7e1caa7

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r-

**Comment by seb-odoo** [comment]
I'll check the problematic test and add a commit here.

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by seb-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
