### PR TITLE
[FIX] don't recompute old fields if recompute=False

### PR DESCRIPTION
**Pull request by hbrunn**
This changes make `_write()` behave like `_create()` in respect of `context['recompute']` and `env.recompute`: https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L4266

### CODE REVIEW

**Comment by pedrobaeza** [comment]
runbot errors seems unrelated.

**Comment by gurneyalex** [comment]
OCA runbot is green on the corresponding OCB PR.

**Comment by clonedagain** [comment]
Is this really a fix or rather an optimization?
Are we currently at risk of getting inconsistent data without this patch?

**Comment by hbrunn** [comment]
For as much as I oversee it, it's an optimization - but one that can really hurt if it's not there.

I *think* you should be able to produce an infinite loop if you have two old style function fields that trigger a store on each other.

**Comment by mdietrichc2c** [comment]
I found an error case without this PR, which is fixed by using it:
1) create an object with a field belonging to `recompute_old` but not recomputing (in my case, it was `account.journal.period`, and the `company_id` related field),
2) rollback the object, but don't raise the exception (`recompute_old` is not emptied),
3) write something else entirely: the `recompute_old` will only be tried there, and fail, since the `account.journal.period` does not exist anymore.

Using this PR, the field will not be added at creation time, fixing the behavior.

:+1: as a fix rather than an optimization.

**Comment by lepistone** [comment]
The code affected by this has changed. @mdietrichc2c made two updated PRs: https://github.com/OCA/OCB/pull/342 and
https://github.com/odoo/odoo/pull/8919.

This one can be closed.

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
