### PR TITLE
[CLA] New cla contributors for Trescloud

### PR DESCRIPTION
**Pull request by JuanDanielAlvarez**

### CODE REVIEW

**Comment by vbe-odoo** [comment]
We need to include only Jose as is the one remaining.
We included the other 2 in this PR https://github.com/odoo/odoo/pull/103687
cc' @jco-odoo @JuanDanielAlvarez @pepetreshere

**Comment by JuanDanielAlvarez** [comment]
> We need to include only Jose as is the one remaining. We included the other 2 in this PR #103687 cc' @jco-odoo @JuanDanielAlvarez @pepetreshere

@vbe-odoo Thanks for your response, I will make a separate pr for Jose, but keep in mind this PR is for branch 14.0. Should I still close this PR?

**Comment by jco-odoo** [comment]
@JuanDanielAlvarez We can do this one in 14 and not fw-port and then just add Jose in 15 if you want.

**Comment by vbe-odoo** [comment]
@jco-odoo well V14 is an NTH, so we can go ahead and merge this one, we won't do much for EC in V14 anyways, but again it doesn't hurt to have it.
So let's merge it we don't FW-P this one.

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by jco-odoo** [comment]
@fw-bot ignore

**Comment by jco-odoo** [comment]
@mart-e We had already merged 2 of the 3 lines in 15.0.  (sorry, not much confidence in git handling conflicts automatically)
@JuanDanielAlvarez Could you still provide a PR with an adaptation for 15.0 then?

**Pull request closed without merging**
