### PR TITLE
[CLA] Patrik Lermon (kler) signing Individual Contributor License Agreement

### PR DESCRIPTION
**Pull request by kler**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

…eement

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e duplicate of https://github.com/odoo/odoo/pull/12347 but against another version.

**Comment by mart-e** [comment]
Indeed, please only submit for the lowest version

https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch

**Comment by kler** [comment]
Ok, should I consider a CLA a:
- Bug fix
- Localization
- Payment provider
- Shipping provider or
- Unstable change

i.e. what is considered the lowest version for a CLA?

**Comment by mart-e** [comment]
No the important part was just below the table :)

> Important: Please do NOT create pull requests with the same patch on multiple target branches. Fixes made in LTS versions (currently 7.0, 8.0, 9.0) will be forward ported to later versions periodically.

**Comment by kler** [comment]
I see, so it really doesn't matter then which branch the CLA is committed
to?

**Comment by mart-e** [comment]
No it does matter, you need to have signed the CLA in the targeted branch. What we do is we port the commits to upper version periodically, so all commits (CLA included) in 8.0 will end up in 9 and master in a few days/week.

**Pull request closed without merging**
