### PR TITLE
[FIX] mail: improve speed of portal

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
A portal user with lot of order (+10k) should wait lot of time  to see order in portal.
This field `message_partner_ids` is used in portail domain of `ir.rules`.

Before : 100s, after 10s. (in db with 120k orders of this portal user).

It also improve a lot this filter `<filter string="Followed Tasks" name="my_followed_tasks" domain="[('message_is_follower', '=', True)]" />`.

@rco-odoo 
@tivisse

Note `[('message_follower_ids.partner_id', operator, operand)]` doesn't work for security reasons.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW #3198605

**Comment by tde-banana-odoo** [comment]
@tivisse no need to send explicit review requests, we use teams ^^ .

**Comment by thiryr** [comment]
Hey :wave:
(Just passing notes, tde will surely review this ^^)

Just wondering, is the second commit in any way necessary for the first commit or are they just 2 different perf improvements? And if so, can you estimate how much each is? Maybe give some more indication in the commit message

First one seems legit to me, second one I can't really assess (not overly familiar with 'low-level' ORM code) but I feel like there should be a better way to improve whatever we're trying to improve than changing the default selected column. Maybe it's obvious to some, but since it's a fairly technical change it might be nice if you can detail a bit why it improves performance in this case. I'd say it's probably not obvious even for people familiar with the code.

Some notes
- Testing your change to the query model would be necessary
- `test_field_message_is_follower` is failing right now, check the runbot :)
- A performance test on what we're trying to improve would be the great
- (Not sure we'll want to merge that in an old stable release, but I guess it's arguable since it could be a pretty annoying issue. Not up to me though)

**Comment by tde-banana-odoo** [comment]
@rco-odoo

**Comment by fmdl** [comment]
It also improve the speed when add a product in sale.order (when project is installed)
image

@rco-odoo

**Comment by fmdl** [comment]
@rco-odoo can you help me to understand why tests fails ?

**Pull request closed without merging**
