### PR TITLE
[FIX] Search calendar event

### PR DESCRIPTION
**Pull request by rimbendhaou**
Description of the issue/feature this PR addresses:

Current behavior before PR:
the search didnt display the recurrent events (the virtual one) if their main event (the non virtual) is not in the domain.
Exemple: if we have one recurrent event starting from d1 repeated 10 times each day
if the domain is (start datetime is after d1+1 day ) It will not display any of the recurrent events because the main event is not included in the domain.
Desired behavior after PR is merged:

To display all the events (recurrent and not recurrent) between 2 dates even id the main event is not included in this period

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nle-odoo** [comment]
As said in ticket opw-2002176 this does not seem to be something we would do as a bug fix in a stable version.

The current behavior works with finding events withing a period (if `virtual_id` has been set in context):

```py
[('start', '<=', {end of period}), ('stop', '>=', {start of period})]
```

this PR may solve an odd/weird behavior that allow to get events completely contained inside a period:

```py
[('start', '>=', {start of period}), ('stop', '<=', {end of period})]
```

but this change a behavior that was there in stable at least from 8.0 up to 12.0, possibly breaking existing customizations / expectations / performances of the code (for example in the actual code we will loop over all recurring event even if none of them could match a period).

I think the way things are now seems enough for stable, the behavior is odd / weird but we already need a `virtual_id` in context to get event recursions, so when at this point this is already rather technical.

In my opinion if something is improved it should be in master.

**Comment by rimbendhaou** [comment]
@nle-odoo I added a test case that check events withing a period (if virtual_id has been set in context):

[('start', '<=', {end of period}), ('stop', '>=', {start of period})].
Is it the missing test case that you mentioned?

**Comment by rimbendhaou** [comment]
@nle-odoo any new comment? Any suggestion to fix this issue?

**Comment by rimbendhaou** [comment]
@nle-odoo thank you for your feedback, i agree that it is not optimized and it will take time to loop over events if we have many events. But how can we detect the recurrent (virtual events) within a period? The search method before this fix doesnt work correctly with recurrent events and it doesnt satisfy the final odoo users.

**Comment by C3POdoo** [comment]
Dear @rimbendhaou,

Thank you for your contribution but the version 11.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
