### PR TITLE
[FIX] mrp: set default product on unbuild order

### LINKED ISSUE #70216: [14.0] mrp: Wrong bom on Unbuild order
Impacted versions: 14.0

Steps to reproduce:

- Create Multiple BOM for same Product
- Create MO using different Boms and Mark them as Done
- Create Unbuild order from MO using Unbuild Button

Screenshot(12)

Current behavior:
Wrong BoM on Unbuild order
Screenshot(13)

This happening as  _onchange_product_id is resetting  bom
https://github.com/odoo/odoo/blob/a7060b686e6888da9dd3fb9c46c5e037393a6844/addons/mrp/models/mrp_unbuild.py#L120

Expected behavior: Same Bom as MO

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): 2521788

### PR DESCRIPTION
**Pull request by sswapnesh**
Before this commit, Creating Unbuild order using
 Unbuild Button was resetting Bom as it was calling
`_onchange_product_id` after setting `mo_id` which was
resetting Bom on Unbuild order.

To Fix Issue, We setting `default_product_id` so It would not
reset `bom_id` when `_onchange_product_id` is called.

Fixes: #70216
Odoo Ticket: 2521788

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ryv-odoo** [comment]
Hi @sswapnesh ,
Nice fix, LGTM. Thank you.

@robodoo r+

**Comment by sswapnesh** [comment]
Thanks for Quick review.

> Odoo Ticket: 2521788

I think you can also close this one.

**Comment by ryv-odoo** [comment]
@robodoo r+

**Comment by ryv-odoo** [comment]
@robodoo retry

**Comment by sswapnesh** [comment]
Unknowingly We also fixed issue for different uom on Unbuild order

**Pull request closed without merging**
