### PR TITLE
[FIX] website_crm: fix random website_crm_pre_tour bug

### PR DESCRIPTION
**Pull request by mish-odoo**
PURPOSE

The purpose of this commit is to fix the random bug of 
'TestWebsiteCrm.test_catch_logged_partner_info_tour' on runbot.

SPECIFICATIONS

Currently, The 'TestWebsiteCrm.test_catch_logged_partner_info_tour' is
randomly failing on runbot. The tour is trigger on the contact us page.
This tour is linked with selectors. So, This updates the selectors and
adds the extra triggers.

This is the goal of this commit.

LINKS

PR #78512
Task-2649723

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rdeodoo — APPROVED** [review]
Hello,

The fix here is LGTM, it will indeed prevent the click from the first step to go through if the editor is not loaded yet.
According to the [logs](http://runbot40.odoo.com/runbot/static/build/10048485-saas-14-5/logs/test_post.txt) that's what happened on the failing build:

```
step 'Select contact form (trigger: section.s_website_form)' succeeded 
[...still loading the editor]
"GET /website/static/src/img/snippets_thumbs/s_twitter_scroll.svg HTTP/1.1" 200 - - - -
"GET /website/static/src/img/snippets_thumbs/s_donation.svg HTTP/1.1" 200 - - - -
"GET /website/static/src/img/snippets_thumbs/s_embed_code.svg HTTP/1.1" 200 - - - -
"GET /website/static/src/img/snippets_thumbs/s_rating.svg HTTP/1.1" 200 - - - -
"GET /website/static/src/img/snippets_thumbs/s_share.svg HTTP/1.1" 200 - - - -
"GET /website/static/src/img/snippets_thumbs/s_card.svg HTTP/1.1" 200 - - - -
[...]
failed at step Open action select (trigger: we-select:has(we-button:contains('Create an Opportunity')) we-toggler)
```

Maybe asked for a multi build if you want to be sure but I think this is not needed in this case

**Comment by tde-banana-odoo** [comment]
Multibuild was already performed :)

@mish could you update commit message ? indeed it could be great to add explanation about editor not being loaded, which is why we add new steps and triggers.

Thanks !

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
Many thanks !

**Pull request closed without merging**
