### PR TITLE
[REF] mrp: is_planned and is_partially_planned

### PR DESCRIPTION
**Pull request by sle-odoo**
the `planned` state was removed but still used in a bunch of places
make `is_planned` and `is_partially_planned` stored and use them instead

### CODE REVIEW

**Comment by sle-odoo** [comment]
@amoyaux do we need `is_partially_planned` ?

**Comment by amoyaux** [comment]
For me, we can remove is_partially_planned

**Comment by Whenrow** [comment]
@amoyaux 13.5 or master ?

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
robodoo r+

**Pull request closed without merging**
