### PR TITLE
[9.0][test] Fix multidatabase phantomjs tests

### PR DESCRIPTION
**Pull request by yajo**
Fix https://github.com/odoo/odoo/issues/12927
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by sle-odoo** [comment]
@antonylesuisse

**Comment by Yajo** [comment]
Notice that this happens too in v8, and the fix is almost identical, but not 100% (it uses `localhost` instead of `HOST`). It would be nice if you backport it.

**Comment by rafaelbn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sle-odoo** [comment]
is this patch needed if you run your server with a db filter?

**Comment by Yajo** [comment]
I don't think you run tests on your server, but in localhost, where you develop. Anyway, I guess it's still needed.

**Comment by sle-odoo** [comment]
i develop in localhost and use the db-filter almost every time and actually i'm not sure your the patch is still needed when using it, but i didn't managed to reproduce this issue a single time on my machine at the moment

**Comment by Yajo** [comment]
I imagine you have your reasons to use dbfilters in localhost, but honestly it certainly does not fit all development environments. Developing Odoo is complex enough as to have to set up several hosts.

I can develop a Docker-based test case so you can reproduce the bug if you consider it's needed.

Anyway let me check what's happening with runbot too.

**Comment by Yajo** [comment]
Runbot should be fixed now, let me create an environment to reproduce this.

**Comment by sle-odoo** [comment]
that'll be helpful, thanks

**Comment by Yajo** [comment]
OK, this bug is quite tricky to trigger, but let's see if I can make it for you.

First of all, install Docker and Docker Compose in your computer, and create a folder called `test` with these 3 files:

## step1.yml

```
version: "2"

services:
    odoo:
        build: .
        tty: true
        environment:
            DB_PORT_5432_TCP_ADDR: db
            DB_PORT_5432_TCP_PORT: 5432
            DB_ENV_POSTGRES_USER: odoo
            DB_ENV_POSTGRES_PASSWORD: odoo
        links:
            - db
        ports:
            - "80:8069"

    db:
        image: postgres:9.4
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
```

## step2.yml

```
version: "2"

services:
    odoo:
        build: .
        tty: true
        environment:
            DB_PORT_5432_TCP_ADDR: db
            DB_PORT_5432_TCP_PORT: 5432
            DB_ENV_POSTGRES_USER: odoo
            DB_ENV_POSTGRES_PASSWORD: odoo
        links:
            - db
        ports:
            - "80:8069"
        command: odoo.py -d demo1 -i website_blog --test-enable --config /etc/odoo/openerp-server.conf

    db:
        image: postgres:9.4
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
```

## Dockerfile

```
FROM odoo:9.0
USER root
RUN apt-get update
RUN apt-get install -y npm
RUN ln -s /usr/bin/nodejs /usr/local/bin/node
RUN npm install -g phantomjs-prebuilt
USER odoo
```

## STR

1. Open a terminal in the `test` folder.
2. Execute `docker-compose -f step1.yml up`.
2. Enter http://localhost/web/database/manager when logs tell you Odoo is listening.
3. Create database with following data: captura de pantalla de 2016-08-05 13-14-07
4. Install `website_blog` module when finished.
5. Return to http://localhost/web/database/manager when finished.
6. Duplicate database `demo1` to `demo2`.
7. Press Ctrl+C in the terminal.
0. Execute `docker-compose -f step2.yml up`. This starts phantomjs-testing `website_blog` module.
0. While the test is running, try to log into `demo2`.
0. Stare at the logs, they should blow out when phantomjs test finishes.
0. Press Ctrl+C in the terminal to kill it when you are tired of the logs.

## Testing with the fix

Now if you want to check this fix works:

0. Download https://raw.githubusercontent.com/Tecnativa/odoo/9.0-test-fix_multidatabase/openerp/tests/common.py and put it in the `test` folder, named `common.py`.
0. Add this line to your `Dockerfile`: `COPY common.py /usr/lib/python2.7/dist-packages/openerp/tests/common.py`
0. Make sure you stopped the containers before, and then run `docker-compose -f step2.yml up --build`.
0. While the test is running, try to log into demo2.

In my case, I still got this:

```
odoo_1  | 2016-08-05 12:05:09,880 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: ERROR
odoo_1  | 2016-08-05 12:05:09,885 1 INFO demo1 openerp.addons.website_blog.tests.test_ui: ======================================================
================
odoo_1  | 2016-08-05 12:05:09,885 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: ERROR: test_admin (openerp.addons.website_blog.tests.
test_ui.TestUi)
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: Traceback (most recent call last):
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `   File "/usr/lib/python2.7/dist-packages/openerp/ad
dons/website_blog/tests/test_ui.py", line 7, in test_admin
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `     self.phantom_js("/", "odoo.__DEBUG__.services['
web.Tour'].run('blog', 'test')", "odoo.__DEBUG__.services['web.Tour'].tours.blog", login='admin')
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `   File "/usr/lib/python2.7/dist-packages/openerp/te
sts/common.py", line 439, in phantom_js
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `     self.phantom_run(cmd, timeout)
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `   File "/usr/lib/python2.7/dist-packages/openerp/te
sts/common.py", line 386, in phantom_run
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `     self._wait_remaining_requests()
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `   File "/usr/lib/python2.7/dist-packages/openerp/te
sts/common.py", line 401, in _wait_remaining_requests
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `     thread.join(0.05)
odoo_1  | 2016-08-05 12:05:09,886 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `   File "/usr/lib/python2.7/threading.py", line 940,
 in join
odoo_1  | 2016-08-05 12:05:09,887 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: `     raise RuntimeError("cannot join current thread"
)
odoo_1  | 2016-08-05 12:05:09,887 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: ` RuntimeError: cannot join current thread
odoo_1  | 2016-08-05 12:05:09,887 1 INFO demo1 openerp.addons.website_blog.tests.test_ui: Ran 1 test in 11.862s
odoo_1  | 2016-08-05 12:05:09,887 1 ERROR demo1 openerp.addons.website_blog.tests.test_ui: FAILED
odoo_1  | 2016-08-05 12:05:09,887 1 INFO demo1 openerp.addons.website_blog.tests.test_ui:  (errors=1)
odoo_1  | 2016-08-05 12:05:09,887 1 INFO demo1 openerp.modules.module: openerp.addons.website_blog.tests.test_ui tested in 11.87s, 1606 queries
odoo_1  | 2016-08-05 12:05:09,887 1 ERROR demo1 openerp.modules.module: Module website_blog: 0 failures, 1 errors
```

But at least it is not an endless loop.

I pushed a different commit to get some logs on failed hits.

Let me know if you get to it please, thanks!

**Comment by Yajo** [comment]
Today [I noticed this same bug in Travis](https://travis-ci.org/OCA/website/jobs/168885610#L1406-L3276), maybe somebody could instruct us on how to use travis2docker to reproduce it more easily.

**Comment by rafaelbn** [comment]
@yajo is this PR in the same situation?

**Comment by Yajo** [comment]
Which situation?

**Comment by rafaelbn** [comment]
I asked because I thought that Odoo would have improved. But OK, still pending review from Odoo.

**Comment by Yenthe666** [comment]
@sle-odoo and @odony could one of you look at this please? 💎

**Comment by anothingguy** [comment]
i faced same problem in my docker-based local when try to run test for module `sale`. I don't want to define `db_filter` in my config because testing database is already declared when starting Odoo server.
It's fixed with @Yajo 's patch.
Could Odoo team can look at this PR faster :D. still pending.
Ping @sle-odoo @odony again :D.

**Comment by pedrobaeza** [comment]
Any news about this? @Yajo is still applying in v10 or v11?

**Comment by Yajo** [comment]
I guess yes, but we don't hit it recently since we test in single-database instances without worker mode, which is currently the only workarond for this, and wouldn't be damaged by the merge.

**Comment by pedrobaeza** [comment]
@Yajo as now PhantomJS is deprecated for new version, I think you can close this.

**Comment by mreficent** [comment]
@pedrobaeza Don't close, because at least the existing stable versions could benefit from this fix.

**Comment by pedrobaeza** [comment]
Yeah, but is this is not going to be integrated, better to don't keep it opened. This can be put on OCB if you need it.

**Comment by Yajo** [comment]
Indeed.

**Pull request closed without merging**
