### PR TITLE
[FIX] website_sale_delivery: fix unstable tour

### PR DESCRIPTION
**Pull request by robinengels**
This PR adds some trigger to make sure that all python request
is correctly finished. This is needed because an unfinished python request
makes a traceback appears on runbot.

opw-28835921
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

I corrected opw-28835921 to opw-2883592 in commit message

robodoo r+

**Comment by Williambraecky** [comment]
robodoo r-

**Comment by Williambraecky** [comment]
I didn't realise it at the time but the test is in the wrong module, and could actually fail completely.
it should be in a module linking website_sale_delivery and gift_card instead 😬.

**Comment by nle-odoo** [comment]
> it should be in a module linking website_sale_delivery and gift_card instead grimacing.

indeed, it's probably ok on runbot since this is post_install test but would not work if only website_sale_taxcloud_delivery or website_sale_delivery are installed =/

> also it's modifying some things in base which look completely unrelated.

my bad, I had pushed a local WIP for another issue, fixed

**Comment by nle-odoo** [comment]
maybe the tour should be skipped if gift card is not installed, because otherwise we need to create two modules =/

**Comment by xmo-odoo** [comment]
Please add a specific `run() {}` member to the last two steps, to show that they are intended as "check" steps.

**Comment by robinengels** [comment]
@nle-odoo @Williambraecky This should be better, also website_sale_taxcloud_delivery is not necessary for this test

**Review by Williambraecky — APPROVED** [review]
LGTM thanks :)
Note that you will need to modify this in 15.3 (loyalty merge)

I think this will need an exception however due to the new module.

**Comment by d-fence** [comment]
Upgrade exception [#133](https://runbot.odoo.com/web/#id=133&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
module:website_sale_delivery_giftcard

```
cc @KangOl @nseinlet

**Comment by Williambraecky** [comment]
> Upgrade exception [#133](https://runbot.odoo.com/web/#id=133&view_type=form&model=runbot.upgrade.exception) added.
> 
> Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations. **Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.
> 
> If you need to apply any change before it reaches master, please notify runbot team.
> 
> Details:
> 
> ```
> module:website_sale_delivery_giftcard
> ```
> 
> cc @KangOl @nseinlet

The module will need to be renamed and its dependencies changed in 15.3 cf https://github.com/odoo/odoo/pull/82250 
Will it need an upgrade script?

**Comment by KangOl** [comment]
> Will it need an upgrade script?

Yes, it will.

**Pull request closed without merging**
