### PR TITLE
[IMP] website: do not use a default name for visitors

### PR DESCRIPTION
**Pull request by mart-e**
@tde-banana-odoo never r+ on a Saturday

@dbeguin [bisous](https://66.media.tumblr.com/483bf78012336ca6cce2ec85f54dd32f/tumblr_o0jayaDJuA1v4946xo2_500.gif)

I changed from the id to a datetime as you could get something a bit weird like `Website Visitor #<New Id>` in create/onchange context (and anyway and id is technical).

### CODE REVIEW

**Comment by dbeguin** [comment]
This seems ok in the idea but I think this makes the name quite longer and less readable (this was mainly to identify the visitor easily).

**Comment by mart-e** [comment]
Just the time?

**Comment by mart-e** [comment]
robodoo r+ rebase-ff

**Comment by tde-banana-odoo** [comment]
"never r+ on a Saturday" that's not what our chief commander says.

**Pull request closed without merging**
