### PR TITLE
[CLA] signature for repodevs

### PR DESCRIPTION
**Pull request by repodevs**
Sign the individual CLA, so I can contribute later

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by repodevs** [comment]
@Yenthe666 @KangOl I found a bug in hw_proxy mode, it's will raise an error when try accessing hw_proxy status in debug mode.

it's happening because in debug mode hw_proxy  will access get a list of USB using `subprocess` module. but the `subprocess` module deleted in the previous commit. 

https://github.com/odoo/odoo/blob/10.0/addons/hw_proxy/controllers/main.py#L125

**Comment by Yenthe666** [comment]
@jorenvo this might be of interest for you.

**Comment by mart-e** [comment]
Hello,

The posbox runs on Odoo 8.0, not 10.0. In 8.0, the code import are fine

https://github.com/odoo/odoo/blob/eaa95bd0a6139389826416306ba3d7154e88bbce/addons/hw_proxy/controllers/main.py#L8-L12

I am not sure why it was not present in the 10.0 branch, probably missed during a forward port (cc @KangOl )

If you want to contribute to the posbox, please use the 8.0 branch but in this case, you will need to sign the CLA on the 8.0 branch (I can cherry-pick it if you wish, no need to create a new PR).
Or do you want me to merge it in 10.0 anyway?

For future contributions, please do not make cosmetic changes (removing EOL spaces,...), keep the diff minimal.

**Comment by mart-e** [comment]
Oh I see, the bug was introduced at rev 56456359499963511dadd9e1a4c13ab530fc7812, so it does concern the 10.0 after all, my bad.

I have merged both commits

8102698dfdc [FIX] hw_proxy: error when check status in debug mode
0004b0e8c45 [CLA] signature for repodevs

**Pull request closed without merging**
