### PR TITLE
[IMP] No Update informations on Metadata View in debug mode

### PR DESCRIPTION
**Pull request by jlaloux**
This is not a bug but i think this could be a good idea to have the "NoUpdate" field into the Metadata view when we are on debug mode like this:

image

### CODE REVIEW

**Comment by antonylesuisse** [comment]
Ok, update function docstring, then this could be merged in master.

**Comment by jlaloux** [comment]
Docstring updated ^^

**Comment by jlaloux** [comment]
CLA signature has been added in an other pull request merged yesteray ^^ (Eezee-it CLA)

**Comment by ged-odoo** [comment]
merged in commit a20545a936d5934835c8d425f3f62cee9377b280.  Thank you for your contribution.

**Pull request closed without merging**
