### PR TITLE
[IMP] point_of_sale: handle products tracked as lots

### PR DESCRIPTION
**Pull request by jorenvo**
As discussed a long time ago, the implemented serial/lot number support in the POS was mainly geared towards serial numbers. Although you could kind of use it for lots as well, it was tedious because it required the user to specify the same lot number for each (=1) quantity in a POS order line. This doesn't work for non-integer quantities (as described in issue #15325). The system assumes that there should be 1 serial/lot number per 1 quantity. This assumption makes some sense for serial numbers but not for lot numbers.

This commit makes the POS handle lots more like the stock module. When a product tracked in lots is bought in the POS you can only specify one lot number with any quantity you want. This lot number is assumed to apply to the full quantity on the line. If a product is sold from multiple lots then multiple order lines would have to be specified.

Not sure if this should be targeting 10.0 or master. It does change behavior obviously, but the previous behavior isn't that great. If you prefer I can integrate jco's work surrounding auto-validating pickings into this PR as well (https://github.com/odoo/odoo/pull/15026).

### CODE REVIEW

**Comment by jco-odoo** [comment]
I don't think change the behaviour in stable would be bad, but you might get errors when half of the data is still in the old and the other in the new.  Would be good to bring it together with my PR too.

**Comment by mart-e** [comment]
The patch LGTM. I tested selling a lot but I got the picking in "picking errors" state. I wonder if it is not due to the [`_force_picking_done` condition](https://github.com/odoo/odoo/blob/76b724294aa21c83edd3409d4664e041dd70cd00/addons/point_of_sale/models/pos_order.py#L625) that will never set the picking as done, even if the quantity as done is the one todo

**Comment by jorenvo** [comment]
> but you might get errors when half of the data is still in the old and the other in the new.

Good point, there is one slightly weird situation I can think of which would occur when the Python code is updated, Odoo is restarted and the POS is not refreshed. For order lines with multiple different lots the backend will assign the full quantity to the first lot, thus losing the other lot numbers the user specified. That's the only case I can think of where data would get lost.

> Would be good to bring it together with my PR too.

I agree, since they're somewhat related so it makes sense to handle them together. I merged your PR with this one.

> I wonder if it is not due to the _force_picking_done condition that will never set the picking as done, even if the quantity as done is the one todo

You're right, that was done at 3cb337945628ffc243072c93a47f6fc55d0f03fd. It is improved by https://github.com/odoo/odoo/pull/15026, which will auto-validate a picking if all lot/serial numbers are valid. I just integrated it in this PR.

@mart-e what's your opinion on merging this in stable?

**Comment by nim-odoo** [comment]
@mart-e ping

**Comment by mart-e** [comment]
Sorry for the late reply. After discussion with @jco-odoo, was not so keen to merge it in stable.
I think there was some other patches to include with it too?

**Comment by jorenvo** [comment]
@mart-e okay, let me know what you think would be best. I integrated all patches that I know of:

1. my stuff regarding making it work better with lot numbers
2. jco's PR to autovalidate pickings containing only valid serial/lot numbers

If there are other ones that should be integrated let me know. Perhaps we could merge 1) in master and 2) in 10.0?

/cc @nim-odoo @jco-odoo

**Comment by nim-odoo** [comment]
Any news here?

**Comment by jorenvo** [comment]
merged in saas-16 at 025d9432a1dfc1db484e9e65d2748ed91d67ca26, 99deebe0154311a254141c54a8336b4a3f4add26, 283f8df95bf5d63dbbf5b8c109c996bbb7ed0f42 and d5908083b4c4cdfb34bbdd8e381c1e419c094702.

**Pull request closed without merging**
