### PR TITLE
[MERGE] web: bootstrap: remove source files and AIO bundle file

### PR DESCRIPTION
**Pull request by adr-odoo**
Sources files (boostrap/js/src/) are not used in Odoo.
We actually use:
- All at once compiled code (bootstrap/dist/)
  -> only for /hw_drivers (POS) and /web (database_manager)
- Individually compiled Bootstrap (bootstrap/js/dist/)

But we can go further by also deleting the AIO bundle file and
have a common way to import Bootstrap.
At the end, only /js/dist files are kept.

REF:
https://github.com/odoo/odoo/pull/95450
https://getbootstrap.com/docs/5.1/getting-started/contents/
https://getbootstrap.com/docs/5.1/getting-started/javascript/

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rfr-odoo — APPROVED** [review]

**Comment by pimodoo** [comment]
This is good for us

**Comment by rfr-odoo** [comment]
@robodoo rebase-merge r+

**Comment by adr-odoo** [comment]
@robodoo delegate=rfr-odoo

**Comment by rfr-odoo** [comment]
@robodoo rebase-merge r+

**Review by pimodoo — APPROVED** [review]

**Pull request closed without merging**
