### PR TITLE
Stock: add a log in chatter when a user forces the availability on a picking

### PR DESCRIPTION
**Pull request by alexis-via**
This is very usefully when you want to explain some strange things on availability.

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1:

**Comment by yvaucher** [comment]
A log message here makes sense. :+1:

**Comment by antonylesuisse** [comment]
Seems ok what about the CLA ?

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
