### PR TITLE
[IMP] l10n_lu: various improvements

### PR DESCRIPTION
**Pull request by rgo-odoo**
task: https://www.odoo.com/web#id=1917932&action=327&model=project.task&view_type=form&menu_id=4720
pad: https://pad.odoo.com/p/r.4f260a7a801af1febfbc4be53bdeb974

### CODE REVIEW

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@robodoo r-

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by mart-e** [comment]
Hi,

How did you generate these translation files? They are invalid, you have some sources that are duplicated, making it unporcessable by translation tools.

**Comment by jco-odoo** [comment]
Because we can still not use Transifex, sometimes things are probably changed by hand.  @rgo-odoo can you do a check on the files and see what went wrong?

**Comment by mart-e** [comment]
There was some duplicated source and at least one invalid term
```po
#. module: l10n_lu
#: model:account.tax.report.line,name:l10n_lu.account_tax_report_line_2d_2_base_8
#: model:account.tax.report.line,tag_name:l10n_lu.account_tax_report_line_2d_2_base_8
msgid "II.D.2. for non-business purposes: base 8% (735)
msgstr "II.D.2. für unternehmensfremde Zwecke: base 8% (735)"
```
(see the missing `"` at the end of the msgid)

I am fixing it at #53288

Check Gettext when manipulation po, it allows to merge po files, remove duplicates,... and other usefull operations.
 https://www.gnu.org/software/gettext/manual/html_node/index.html

**Pull request closed without merging**
