### PR TITLE
Saas 6 empty title forum nle

### PR DESCRIPTION
**Pull request by nle-odoo**
In a first commit I solved the appearance issue : 

>    [FIX] website_forum: css in case of empty title
> 
>    If the title of a thread was empty, some floating used in the post list
>     caused an appearance issue.
> 
>    opw-634687

in a second one, I made it harder to post an empty title : 

> ```
> [FIX] website_forum: trim title before sending
> ```
> 
>    Making an empty question title should not happend issue, and moreover in
>     several locations the question title is used as a link (so the link is removed).
> 
>    opw-634687

currently we can't post with a totaly empty title, but if the title contains only some spaces, we can post.

since the title itself is often a link, it seems good to do this.

and the first commit could still be needed since there may be unicode white space sequence which still allow to post an empty title.

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Ok for the css part.

Regarding the part where you make harder to post an empty question: If I `inspect element` in Chrome, and remove the `required=True` part from the HTML sources, I will be able to post my question without title, even with your patch :).

Besides, altering the input value on submit doesn't seems to be a good practice to me.

Instead, in the controller creating the question, prevent the creation of the question if the trimmed value of the title is empty :).

**Comment by nle-odoo** [comment]
but then if someone has 2000 lines in the message (and inadvertently posted an empty title) he will lose it.

I think there is two  solutions (if we really need to disallow it on the python side) : 

##### 1) quick solution of a mix of javascript and python

- disallow it with javascript (maybe not change the title content but find another way),
- send an error in python when a title is still sended emtpy (or a sequence of space), that would only impact :  
    - people fiddling with curl or the developper tools
    - people desactivating javascript

##### 2) in full python

if we want to do it in python I think I should : 

- change controller so the form on [`'/forum/<model("forum.forum"):forum>/ask'`](https://github.com/odoo/odoo/blob/saas-6/addons/website_forum/controllers/main.py#L278-L288) is POSTED to `'/forum/<model("forum.forum"):forum>/ask'` instead of [`'/forum/<model("forum.forum"):forum>/new'`](https://github.com/odoo/odoo/blob/saas-6/addons/website_forum/controllers/main.py#L290-L306) (and in the `/ask` controller we treat the POST method accordingly)

- if there is an error, display the template `new_question` filled with the POST values, and display an error in this template.

- if it is ok, redirect to `"/forum/%s/question/%s"` like done currently.

**Comment by beledouxdenis** [comment]
There is no problem to do the validation in Javascript, as long as the user is not able to post an empty/wrong title by bypassing the Javascript validation.

So, the Javascript should help the user, the controller should prevent him to try to mess around. It's not a problem if he looses it's content that way, since he bypassed (on purpose), the JS validation.

You can therefore leave the `required` attribute on the input, and to prevent to only enter a space, you can probably use the `pattern` attribute, along with a right regex, the browser will then handle the validation :).
http://www.w3schools.com/tags/att_input_pattern.asp

**Comment by nle-odoo** [comment]
done in this commit: https://github.com/odoo-dev/odoo/commit/199fdca5bc5

**Comment by beledouxdenis** [comment]
I believe both the `Bad Request`  and the `Title should not be empty.` strings from the controller requires a call to `_t` for the translations : ).

Other than that, it seems pretty good :+1:

**Comment by nle-odoo** [comment]
merged with commits : 
- https://github.com/odoo/odoo/commit/ef34e5827e4988f249c64c3aa9871a64583cf199
- https://github.com/odoo/odoo/commit/f3f49ad6564ea3ae2162958c7a54432c57c64786

**Pull request closed without merging**
