### PR TITLE
[FIX] models: performance of `mapped` is now in O(n) instead of O(n²)

### LINKED ISSUE #5542: Performance issues using recordset.mapped()
I have discovered the mapped() method not so long ago, and I really find it helpful to reduce code lines.

But in some use cases, it really shows performance problems.

My models
--------------
Here are my custom models:
- model_a 150 000 records
- model_b 150 000 records

```python
class model_a(models.Model):
    model_b_id = fields.Many2one('model_b')
```

Goal
------
Get all the model_b records that are related to a model_a.

Timings
-----------
```python
model_bs = self.env['model.a'].search([]).mapped('model_b_id')
```
takes 35 minutes to complete, whereas

```python
model_b_ids = [record.model_b_id.id
               for record in self.env['model.a'].search([])]
model_bs = self.env['model.b'].browse(model_b_ids)
```
takes less than a minute.

Expected
------------
I would expect the two different ways to complete in the same time.
The first solution is much clearer and much nicer than the second one, at least to me.

### PR DESCRIPTION
**Pull request by rco-odoo**
Fixes #5542

### CODE REVIEW

**Comment by KangOl** [comment]
If you are about performance, use a iterator instead of a list-comprehension.

**Comment by wtaferner** [comment]
@rco-odoo 
Thank you for this improvement. Unfortunately, I was just testing my use case and it seems not to have solved the issue...every onchange it creates a completely new environment and therefore needs to read the database once to be in cache...so it takes minimum 5.8 seconds locally to respond to a simple change (unlinking a one2many record) which slows down the UI massively. Can't we just skip the retrieval of all records or the onchange when unlinking which actually should only have consequences to the parent model and not all the other 3999 one2many records?

**Comment by Sathors** [comment]
Thanks for the fix @rco-odoo.
Passing the complexity to O(n) is paramount for big implementations !

**Comment by rco-odoo** [comment]
@wtaferner your issue is due to a limitation of the current implementation: when evaluating the onchange methods, fields may be modified and marked as "dirty" in cache. That relatively simple implementation has a major gap: if the onchange reads stuff from the database, that stuff is put in cache and marked dirty as well. Consequently, the cache was full of false dirty entries. In order to fix this, I had the idea to read the data from the database before applying any actual change...

**Comment by wtaferner** [comment]
@rco-odoo 
jep, this is what I have thought of soo far and I already tried to do some prefetching, but I guess my effort was only a minor and not soo efficient try (so I hope you can resolve it more efficiently)...

In sql debug mode I figured out that every depending/onchange field is fetched with its own query/queries in case of splitting the IN clause and I was wondering if we could just skip/reduce the amount of queries somehow or fill up the cache more efficiently before using mapped...

What I have successfully achieved  to reduce my load in my own code was to steer my compute functions (checking the environment of my depends if they are in_onchange) to skip and minimize the time consumed which is of course not the best way but serves the users as the fields are computed and saved anyway on save (of course only for non-critical computes).

**Pull request merged**
