### PR TITLE
WARNING Invalid field stock.config.settings new_security_lead/new_po_lead/new_propagation_minimum_delta

### PR DESCRIPTION
**Pull request by zaoral**
**Description of the issue/feature this PR addresses:**

When I run a saas-15 instance and try to run the stock.config.settings wizard the odoo server log give me 3 WARNINGS about fields that does not exists.

**Current behavior before PR:**

```bash
WARNING openerp_test odoo.addons.base.ir.ir_values: Invalid field stock.config.settings.new_security_lead
WARNING openerp_test odoo.addons.base.ir.ir_values: Invalid field stock.config.settings.new_po_lead
WARNING openerp_test odoo.addons.base.ir.ir_values: Invalid field stock.config.settings.new_propagation_minimum_delta
```

**Desired behavior after PR is merged:**

That this warnings does not appears at all, This warnings also means that the fields in the stock.config.settings are not properly set as default values in the res.company model.

I review that the 3 fields that give us WARNING messages were added by @mag-odoo
in PR https://github.com/odoo/odoo/pull/14782.  The `new_security_lead` field does not exist, but the `security_lead` does exist. This apply for the 3 fields with WARNING.

image

Does `default_new_ prefix` was set on purpose (it will have some special behavior?) or this is an error and should be replaced with `default_name_field`?

If the answer is yes this PR does the required change replacing the `default_new_` with `default_` to correctly refers to the existing fields.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by zaoral** [comment]
cc @nhomar

**Comment by zaoral** [comment]
This is the logs of the last build in odoo.runbot for the branch saas-15+e when I try to run the the stock configuration wizard

image

Here is a video demonstration what happens before/after the new fix https://youtu.be/SWRPmTe4b4I

**Comment by zaoral** [comment]
This PR is related to opw-742480

**Comment by nim-odoo** [comment]
This will be solved for v11.

cc @rco-odoo

**Comment by nhomar** [comment]
Why did not you accept the PR? it is a clear bug that stop completelly a feature (it is  not just the warning)

**Comment by nhomar** [comment]
@qdp-odoo can you give a short check on this, I think this should be fixed on saas-14, -15, -16 it is a totally broken feature (even with a workaround).

Regards. 

PS: Our unit tests are failing because this problem is bringing a WARNING and nothing is happening on the wizard.

**Comment by nim-odoo** [comment]
@nhomar I didn't accept the PR since it implies a change in the DB structure. All persons I pinged before ( @tivisse @rco-odoo ) are aware of the problem.

**Comment by nhomar** [comment]
@nim-odoo but one thing is the stable policy, but then remove the option from the view, it is a bug men , a completely stopped functionality....

**Comment by nim-odoo** [comment]
@nhomar : I understand your point of view. As part of the bug fix team, I share your concern since we will have to deal with this problem for the upcoming months (and I'm not happy with it, believe me). It was decided (ping again @tivisse @rco-odoo ) that the solution would come ASAP, but for the existing versions... no solution :(

**Comment by nhomar** [comment]
@nim-odoo Roger that! then let's wait then.

**Pull request closed without merging**
