### PR TITLE
Master inv creation cleanup qdp

### PR DESCRIPTION
**Pull request by qdp-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@robodoo rebase-ff

**Comment by d-fence** [comment]
robodoo r-
enterprise is red. May I ask you to fix please.
Something overrides post method in account_move or something like that: http://runbot.odoo.com/runbot/build/411633

**Comment by qdp-odoo** [comment]
@robodoo r+

@d-fence strangely the checks were written as 'passed'. I just pushed a branch in enterprise to fix the traceback

**Comment by d-fence** [comment]
@qdp-odoo thanks.

**Comment by d-fence** [comment]
@robodoo retry

**Comment by qdp-odoo** [comment]
merci st nicolaaaaas

**Pull request closed without merging**
