### PR TITLE
[FIX] stock: location name are not translated

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
Default location created during company creation, are not translated.

@amoyaux 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Add the new terms to the `.pot` file too then :)

**Comment by tde-banana-odoo** [comment]
2M LOC, that's quite a huge diff to translate locations.

**Comment by fmdl** [comment]
close by https://github.com/odoo/odoo/pull/70075

**Comment by fmdl** [comment]
@tde-banana-odoo I have made a wrong rebase... please see.

**Pull request closed without merging**
