### PR TITLE
[IMP] use bold font for sections in issue/PR templates

### PR DESCRIPTION
**Pull request by yelizariev**
Compare:

* with bold font: https://github.com/odoo/odoo/pull/24234
* without bold font (the first PR I found): https://github.com/odoo/odoo/pull/24400

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e I summon you!

**Comment by mart-e** [comment]
Actually the first draft of document was with rich text but I believe @odony preferred something very simple.

**Comment by yelizariev** [comment]
There is no security hole in this PR, I promise :bomb:

**Comment by odony** [comment]
Simpler is better than better ;-)
For some reason, many people have trouble with markdown and make a mess when inserting text in templates, so the result is worse than plain text (everything bold, and whatnot)

**Comment by odony** [comment]
Oh, and these are just default templates, you could script it (e.g. tampermonkey) if you want prettier templates for your own posts ;-)

**Comment by yelizariev** [comment]
I understand the reasoning.
From my experience, people will break rendering anyway. For example by copy-pasting logs without proper formatting.
From my point of view, it's better to have 9 good rendering and 1 bad rendering of 10, that 10 middle quality of 10.

> Simpler is better than better ;-)

People in Russia say *The road to hell is paved with good intentions*, but I don't really share it

**Comment by blaggacao** [comment]
Please find a suggestion on #26326 & #26325 which make use of (ultimately invisible) `<!-- -->` to give some instructions. To me, personally, bad rendering is a nuisance and an indication of little care / respect towards the reader. I sometimes spent up to 30 min optimizing it to my liking.

Maybe, at least for PRs, such could be considered. It's relatively likely that someone doing a PR is aware of markdown rendering.

Style matters. :dancer:

**Comment by odony** [comment]
I tend to agree that people creating PRs are more likely to know markdown. But we have to keep in mind that not everyone values style as much as we do, and not everyone has a lot of time to dedicate to formatting. To each his own ;-)

As a step forward, how about we begin with just the PR template, and instead of bold marks (which require closing and are error-prone) we use h3 prefixes ### for the titles? Same benefit, less risk of a mess?
I think it will be even more annoying to see bold titles on all those PR with just the default description, but we will see..

**Comment by blaggacao** [comment]
@odony at hand: https://github.com/odoo/odoo/compare/11.0...blaggacao:patch-1
We need to make feel ourselves comfortable, at home :wink:

**Comment by yelizariev** [comment]
Actually, I don't think that header prefixes is a good idea after years of using colon in templates. It may lead to following results: 

### Description of the issue/feature this PR addresses: 11.0

### Current behavior before PR: When I do something I get this

### Desired behavior after PR is merged: I want to get that




--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

**Comment by yelizariev** [comment]
@blaggacao "pull request preview" links cannot be reviewed line by line. It's better to avoid them

**Comment by blaggacao** [comment]
@yelizariev I just updated and added bullet points to avoid the problem you exposed...

**Comment by yelizariev** [comment]
Well, it may help

**Pull request closed without merging**
