### PR TITLE
[FIX] account: rounding at 0.05

### PR DESCRIPTION
**Pull request by nim-odoo**

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo rebase-ff

**Review by yelizariev — APPROVED** [review]
All looks good except to commit titles :) 

Both commits don't follow this requirement of the guidelines:

image

I spend time on my every commit to make header start with a verb


Also, second commit title missed some words, I guess.

**Comment by yelizariev** [comment]
And a side note: I'd prefer to split unit tests and fixes for them in different commits -- this way we can check (manually or via runbot\other ci tool) that an error exist before update and disappeared after

**Comment by nim-odoo** [comment]
> And a side note: I'd prefer to split unit tests and fixes for them in different commits -- this way we can check (manually for now, but potentially automatically in future via runbot or another ci tool ) that an error exist before update and disappeared after

Indeed, that's a good point. Although at the moment we are used to have the fix and the test in the same commit.

And indeed, the commit titles are not very good :)

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by nim-odoo** [comment]
robodoo r+

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
