### PR TITLE
[FIX] iap: fixing access rights for non amin users

### PR DESCRIPTION
**Pull request by rrahir**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dmo-odoo** [comment]
Can't you give proper create access rather than bypass that using sudo then revert to user rights for the rest ?

**Comment by rrahir** [comment]
@dmo-odoo I discussed this with @rco-odoo  But the thing is that I am not sure that we are supposed to ... also this wouldn't require to update their iap module even if in this case, the impact is really small ...

**Comment by rrahir** [comment]
robodoo r+

**Comment by xmo-odoo** [comment]
@dmo-odoo we've disabled "github reviews" as robodoo commands (you can still send robodoo messages via them, but they're not implicit r+ anymore) as it was inconvenient for informal reviews

@rrahir you've been configured as reviewer, I guess moc had forgotten

@robodoo: r+

**Pull request closed without merging**
