### PR TITLE
[master] add "starts with" and "ends with" when searching on char field

### PR DESCRIPTION
**Pull request by alexis-via**
sshot_startswith

This is very useful when you search on a char field!

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by GSLabIt — APPROVED** [review]

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Review by ivantodorovich — APPROVED** [review]
Nice feature !

**Review by yassinelachgar — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Comment by jcdrubay** [comment]
That would be useful.

**Comment by Yenthe666** [comment]
@mart-e and @odony can I please ask you two to check and consider this PR? :)

**Comment by alexis-via** [comment]
For those of you who would like to have this feature on their current odoo, here are patches for:

- v14 : https://people.via.ecp.fr/~alexis/odoo-v14-advanced_search_startswith.diff
- v10 : https://people.via.ecp.fr/~alexis/odoo-v10-advanced_search_startswith.diff

**Review by acalmett — APPROVED** [review]
Used in production, no code review

**Comment by Yenthe666** [comment]
@mart-e I summon you!

**Comment by mart-e** [comment]
> @mart-e I summon you!

Ok but it's still not my call ^^ this would be for @odoo/rd-framework-js team

**Comment by Yenthe666** [comment]
Then I summon @ged-odoo ;-)

**Comment by odony** [comment]
I think you need to ask nicely @antonylesuisse's opinion, because this runs against the fundamental principle of reducing UI options to the minimum by default. Anything that falls under the category "for advanced users" needs to make a very strong case to survive ;-)
For instance, it may need to be hidden outside of the dev mode.

**Comment by Yenthe666** [comment]
> I think you need to ask nicely @antonylesuisse's opinion, because this runs against the fundamental principle of reducing UI options to the minimum by default. Anything that falls under the category "for advanced users" needs to make a very strong case to survive ;-) For instance, it may need to be hidden outside of the dev mode.

Just my five cents: I've had multiple people ask for extra search options like these before and every once in a while it would be very handy to search for things starting with some chars or ending with them. For example: all orders with a reference that starts with "RS" which filters orders coming from another platform :)

**Review by wtaferner — APPROVED** [review]
So, let's make it a "strong" case as I back this one too. Simple UI does not mean feature-less or hidden feature software ;-)

**Review by Yenthe666 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
One option is to have a "hidden" feature like the use of `%` as wildcard (and this time served by Postgres itself). Maybe we can put `^` at the beginning of the input search (like regexp), and this can be interpreted in the ORM to not add `%` to the expression, and thus, leading to search matches that start with such string, and similar with the end. This way, we have the option, and advanced users may know it, but no extra options are added to the combo.

**Comment by odony** [comment]
> One option is to have a "hidden" feature like the use of `%` as wildcard (and this time served by Postgres itself). Maybe we can put `^` at the beginning of the input search (like regexp), and this can be interpreted in the ORM to not add `%` to the expression, and thus, leading to search matches that start with such string, and similar with the end. This way, we have the option, and advanced users may know it, but no extra options are added to the combo.

That sounds like an interesting alternative, making the "undocumented wildcards" slightly more powerful. But rather than doing it on the server side, that substitution should be done exclusively in the search panel of the web client (like @alexis-via was doing in this PR: `ilike` -> `=ilike`). This way there is no impact to any business logic where `^` could be part of existing data flows. The extra magic is only useful for the web client anyway, as in other contexts (RPC, Python code, ...) you can already use `=ilike` freely.

There's also the question of having only 1 special char (`^`) or 2 (`^`/`$`) to trigger it. Either works, and having 2 chars makes "ends with" more intuitive to use, but `$` comes with a much greater risk of accidental triggering.

Note that this would also cause a divergence of behavior between the pure `search()` API and the search panel. And contrary to the `%` and `_` special chars which work as wildcards for their own literal version, the `^` / `$` would need to be explicitly escaped if you want to deactivate the feature:  e.g. you'd need to search for `%^hello` instead of `^hello` if you want the default `ilike` behavior.

What do you think about this idea @aab-odoo @antonylesuisse @bouvyd?
Is this too crazy/overkill?

**Comment by ivantodorovich** [comment]
I think the current proposal is technically simple and more elegant than dealing with special characters.

IMO it shuoldn't be hidden, as these options would only be shown under the "Add custom filter" menu, which is deep enough not to spam the ui. But if you really want to hide it, why not simply showing these options only in debug mode?

**Comment by wtaferner** [comment]
@odony 
No hidden features please...then I vote and think it is better to have an explicit regex mode to do all the dirty magic in one special operator besides the current kindergarten operators.

**Comment by bouvyd** [comment]
I believe the 'hidden feature' is a bad idea:
- difficult/impossible to discover
- easy to break in other devs
- supporting 'some' regex syntax but not all is gonna be frustrating for those who tries to do it
- having such a feature divergence between the search panel and the search API is not optimal
- character escaping will elude most normal users, possibly causing misbehaviours

I'm not saying this is not useful, but I believe this is not a must-have. The 'ends with' in particular seems even less useful (I'd tend to assume that prefixes are way more common than suffixes).

In addition to this rather limited impact, this happens at a bad time where all views are being converted to OWL🦉, meaning that we are clearly avoiding new features that would changes the underlying spec during development (yes, I include simple stuff as this as well, as it would require tests to avoid regression, etc.).

I keep this in mind for potential search panel improvements (and believe me, I have quite a few in mind already) - I have a list of things to improve which already includes quite a few things (e.g. relative dates, etc.).

Thank you for the feedback and code suggestion, however at this point I will postpone this to a future version.

@odony can you close the PR (I can't)?

**Comment by odony** [comment]
> @odony can you close the PR (I can't)?

Now you can ;-)

**Comment by bouvyd** [comment]
See my [above message ](#issuecomment-1096339894)regarding the reasons behind my closing this PR.

**Pull request closed without merging**
