### PR TITLE
[REV] mail: get current company activities

### PR DESCRIPTION
**Pull request by adwid**
This reverts commit c071f0255fba3b8340182607fe4ef70321691341 (See PR https://github.com/odoo/odoo/pull/64201)

Reason: the fix is incorrect, it creates another issue: https://github.com/odoo/odoo/issues/64548

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]
@robodoo r+

**Comment by alexkuhn** [comment]
@fw-bot ignore

**Comment by adwid** [comment]
@alexkuhn The change must be applied on 12.3 too (https://github.com/odoo/odoo/pull/64224)

**Comment by jpp-odoo** [comment]
@fw-bot up to saas-12.3

**Comment by alexkuhn** [comment]
> @alexkuhn The change must be applied on 12.3 too (#64224)

Ok, I thought it was just merged in v12.

**Comment by tde-banana-odoo** [comment]
Thanks for the followup !

**Pull request closed without merging**
