### PR TITLE
[IMP] account: add test for fiscal positions with delivery address

### PR DESCRIPTION
**Pull request by epictete**
The goal is to add a test that covers the basic use cases of fiscal positions,
and in particular when using a delivery address.

The use cases are as follows:

- Case : 1
Billing (VAT/country) : BE/BE
Delivery (VAT/country) : NL/NL
Expected FP : Régime National

- Case : 2
Billing (VAT/country) : NL/NL
Delivery (VAT/country) : BE/BE
Expected FP : Régime National

- Case : 3
Billing (VAT/country) : BE/BE
Delivery (VAT/country) : None/NL
Expected FP : Régime National

- Case : 4
Billing (VAT/country) : NL/NL
Delivery (VAT/country) : NL/NL
Expected FP : Régime Intra-Communautaire

- Case : 5
Billing (VAT/country) : None/NL
Delivery (VAT/country) : None/NL
Expected FP : EU privé

- Case : 6
Billing (VAT/country) : None/US
Delivery (VAT/country) : None/US
Expected FP : Régime Extra-Communautaire

Related PR : https://github.com/odoo/odoo/pull/75033

task-2729813

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@epictete 
Awesome. Just to understand correctly...the sending country is Belgium (warehouse) and the company VAT number is Belgium for all 6 use cases, right?

**Comment by epictete** [comment]
@wtaferner 
Yes indeed, that's correct.
Currently (and if I'm not mistaken), the warehouse address is not taken into account in the computation of the fiscal positions (i.e. both are one and the same).
It is something we are investigating, to see if there are cases where a company in country A with a warehouse in country B could actually do the billing from country A, or if it has to be done from country B.
And if so, there will certainly be a task to update our fiscal position's logic to take that into account.

**Comment by wtaferner** [comment]
@epictete 
Well, you can always ask me as I have experienced and implemented as good as possible in inheritance almost every use case you can imagine 😉 
And yeah, a customer of mine is in Austria, having a Hungarian VAT to ship from a contractor from Hungary to other EU countries also from other countries like Germany (warehouse) to even customers in Austria with a German VAT (Intra Community). Also we need to tackle the delivery of own goods from one country to another country (needs to be reported in Intrastat and in the VAT report)

Soo, a lot to improve Odoo Core 🤣

**Comment by william-andre** [comment]
> Soo, a lot to improve Odoo Core :rofl: 

You are welcome to propose a PR. Even more so if you already "have experienced and implemented as good as possible in inheritance almost every use case you can imagine".

**Comment by qdp-odoo** [comment]
@epictete variable names are a bit sloppy, if you ask me but .. hey, nothing preventing the merge
@robodoo r+, robot-dude!

**Comment by qdp-odoo** [comment]
@robodoo r+ 
?

**Pull request closed without merging**
