### PR TITLE
[FIX]stock_account: stock manager group not inherit account bill group

### PR DESCRIPTION
**Pull request by yhu-odoo**
The inheritance of account billing group gives stock managers the access
to account module.
This commit is to remove this inheritance. When we need to access
account.move model, check if the user is a stock manager. If so, use
sudo() to get the access.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sle-odoo** [comment]
maybe we could replace the has_group by a create check on valuation layer? @amoyaux what do you think

**Comment by amoyaux** [comment]
same as create an ACL for account_move for stock manager in this case. The specific sudo are probably better since the stock manager is only able to create an account move during specific flow. Make it in the create would made it generic

**Comment by sle-odoo** [comment]
nah adding a new acl for account move is a bad idea (not enough: we need account account account tag aacount analyitc tax and all that crap + duplicate the ir rules from account)

adding it in AM create is also a bad idea (inventory manager should not be able to create any account move he wants, only the ones related to the stock valuation)

what i suggested was going sudo by duck typing the read access on stock valuation layer (``` check_access_rule('read') ```), which only the inventory manager has at the moment, instead of checking the inventory manager group

**Comment by sle-odoo** [comment]
robodoo r+ rebase-ff

**Pull request closed without merging**
