### PR TITLE
[FIX] *: retarget documentation links to saas-15.3

### PR DESCRIPTION
**Pull request by AntoineVDV**
See also:
- https://github.com/odoo/enterprise/pull/26238

### CODE REVIEW

**Comment by AntoineVDV** [comment]
@fw-bot ignore

**Review by Julien00859 — APPROVED** [review]
Maybe be should make the various stings in the source-code smarter?

**Comment by mart-e** [comment]
> Maybe be should make the various stings in the source-code smarter?

We already thought about it but it was a bit overkill. We don't have qweb for backend views, we don't want to use javascript to generate a simple link. A global search and replace once every two months for a few files seemed to be the most efficient (KISS) way to do so. But suggestions accepted if you have another idea :)

**Comment by Julien00859** [comment]
IMO if it is simple to make it smart then we should do it.

We could add a variable inside of `release.py` e.g. `doc_version = 'saas-15.3'` and then use that variable in the URLs e.g. 
```py
f"""
Odoo URLs are CSRF-protected by default (when accessed with unsafe
HTTP methods). See
https://www.odoo.com/documentation/master/developer/reference/{doc_version}/http.html#csrf
for more details.
"""
```
Maybe make that string available to the web client `def session_info()` and qweb `def prepare_qcontext()`.

What do you think ?

**Comment by mart-e** [comment]
And how would you handle the changes in config form views? Via a JS widget? This would add a new complexity, a new widget to maintain,.. IMHO, this is not worth it, it's only to generate a simple html link.
And I am not sure avoiding to spam Odoo devs is a reason to add code :)

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
