### PR TITLE
[FIX] account: correct entry tax sign using tags

### PR DESCRIPTION
**Pull request by agr-odoo**
With BE accounting installed
Create a Journal Entry as follows:

Tax Grids
|Account|Debit |Credit|Tax Grids|
|-------|------|------|---------|
| 400000|121.00|  0.00|         |
| 700200|  0.00|100.00|      +03|
| 451000|  0.00| 21.00|      +54|

Save and post

Open Tax report
On line "03 - Opérations avec TVA à 21%"
there will be an amount of -100,
while the tags used are relative to a sales tax, so the amount should be
positive.

opw-2774049

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@oco-odoo 
Not sure this is something we want (or that this is the correct way of implementing it)

**Review by william-andre — COMMENTED** [review]
> while the tags used are relative to a sales tax, so the amount should be positive.

I really don't get all those signs shenanigans. The tag is positive, the balance is negative -> the amount reported is negative.

**Comment by agr-odoo** [comment]
> The tag is positive, the balance is negative -> the amount reported is negative.

The problem here is that using the same tag, same account, same balance:
* no tax specified -> amount reported is negative.
* sale tax specified -> amount reported is positive

So using the tax grids alone will produce unexpected results.
Perhaps this is expected, do users have to specify the tax even for misc operation?

**Comment by william-andre** [comment]
> The problem here is that using the same tag, same account, same balance:
> 
>     * no tax specified -> amount reported is negative.
> 
>     * sale tax specified -> amount reported is positive

That is what is stupid. Taxes on journal entries don't make sense. Tags do.
It would simplify this "logic" of finding the right sign based on 10¹⁵⁶⁴²³⁴⁵ different criterion.

**Comment by oco-odoo** [comment]
> That is what is stupid. Taxes on journal entries don't make sense. Tags do. It would simplify this "logic" of finding the right sign based on 10¹⁵⁶⁴²³⁴⁵ different criterion.

In a prefect world, maybe, but people asked for this. We want to keep support for taxes on journal entries, there is no question about that (adjustment, cash basis entries, bank reconciliation with taxes directly from the widget also use this exact case).


That being said, using the tag alone on a move line should not apply any "magic" to the sign in the report. As @agr-odoo noticed, adding a tax changes the sign, and it's precisely what we want. The tax carries business information, and is hence used to infer the sign. The tag is only a means to impact a report line. In short, we won't change that, and I'm closing the PR. If someone wants to impact a tag like that, he has to use a tax.

**Pull request closed without merging**
