### PR TITLE
[REVERT] account: unbalanced entry with price_unit 0"

### PR DESCRIPTION
**Pull request by pimodoo**
This fix will try to write a new amount value on the tax when an
invoice is created from POS, that will raise a user error preventing the
creation of the order.

This reverts commit e9262bfc8c775953ebe150f36ce0ab8dcb04d4bd.

OPW-2855694

### CODE REVIEW

**Comment by pimodoo** [comment]
@guva-odoo Hello, we have to revert one of your recent fix, as causes trouble when you want to create an invoice from the POS. It'll try to write a new amount on the account.tax (what will trigger an error) when we are using a tax with fixed amount included. 

There is also a PR in 14.0 https://github.com/odoo/odoo/pull/91625

It seems that it doesn't causes trouble in 13.0, need to check one last time

**Comment by pimodoo** [comment]
@fvb-odoo here is the PR that revert the commit

**Comment by william-andre** [comment]
I think you meant @poma-odoo

**Comment by william-andre** [comment]
Isn't the commit you want to revert https://github.com/odoo/odoo/commit/5f39f8c1533502be52ea9d3ef114430b5b8cd9a6 ?

**Comment by fvb-odoo** [comment]
Hi guys,
I am still investigating this issue (on v14) and the issue is any update of the cache for the taxes during the creation of an account move. (a simple read of the taxes amount triggers the bug) 
It is quite hard to explain this by message. Is there a way to organise a call with the person in charge ?
Kind regards,
Fvb

**Comment by poma-odoo** [comment]
No, it is not, there is nothing wrong with that commit, it looks like  the issue was because of https://github.com/odoo/odoo/commit/bd621fd456811e7f3ce646e3ecade5e9e4a826e8

> Isn't the commit you want to revert [5f39f8c](https://github.com/odoo/odoo/commit/5f39f8c1533502be52ea9d3ef114430b5b8cd9a6) ?

**Comment by poma-odoo** [comment]
Actually things sometimes got crazy with tax and pos, for example if you do the same steps as the video in V13, because there are no account defined for the BAT and REC taxes, the moves from POS cannot be posted so the pos session cannot be closed. But one cannot edit taxes and add the account because there are open pos sessions, dead lock

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Comment by fvb-odoo** [comment]
Hi guys,
After further investigation, the root issue is the wrong amount computed when creating a NewId for the taxes and accessing the amount on these NewId.
Indeed, the read updates the cache with a wrong value for these taxes (0.06000000005 instead of 0.06) which is then transform into a (1, OriginId, {'amount': 0.06000000005}) when creating the account move line.
In this PR, for example, accessing the _origin taxes instead of the NewId taxes does not trigger the bug.
```python
tax_included_division_is_zero = any(tax._origin.price_include and tax._origin.amount == 100 and tax._origin.amount_type == 'division' for tax in taxes) and amount_currency == 0
```

**Comment by pimodoo** [comment]
The root of the root issue, is that this code is called like if there is newIds or if we are in an onchange, but we are not.

**Pull request closed without merging**
