### PR TITLE
[IMP] add Support ticket field

### PR DESCRIPTION
**Pull request by yelizariev**
This should avoid situations when customer reported the same issue via two
channels (github and odoo.com/help), which makes two group of people work in
parallel on the same issue

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
@Yenthe666 @pedrobaeza  @odony

**Comment by Yenthe666** [comment]
Ah yes, I'm all for. +1. Too many people don't cross-reference :) 
Maybe some rephrasing would be nice such as "Official Odoo ticket number" or something.

**Comment by yelizariev** [comment]
e.g.

> Support ticket number submitted via odoo.com/help (optional):

**Review by Yenthe666 — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Good idea, although I always encourage to not submit an enterprise ticket as regular GitHub issue.

**Comment by odony** [comment]
I don't mind either way, so why not? ;-)

It would be nice to fix the commit headline though. e.g. `[IMP] .github: add ticket number to issue template`
As always, the goal of a commit headline is to let other people know at a glance what it is about and whether they want to read further. Thanks!

**Comment by yelizariev** [comment]
It's ready to merge

**Review by odony — APPROVED** [review]
@yelizariev Thanks!

@robodoo r+

**Pull request closed without merging**
