### PR TITLE
Fix a quants proposal so that it respect the rounding of UOM availabl…

### PR DESCRIPTION
**Pull request by mga-odoo**
…e on move

### CODE REVIEW

**Comment by spadae22** [comment]
Need to add import math, otherwise love it!

**Comment by spadae22** [comment]
@odony @mga-odoo Any reason this is not merged. It was done as bug fix for me, tested for months, works perfect!

**Comment by odony** [comment]
@spadae22 because it was never reviewed, seems like a tricky/complex change (+ adds quite a bunch of lines of code), and I can't see any reference or explanation to any bug report. So as far as I can tell it might have been a custom patch developed just for you.

**Comment by spadae22** [comment]
Well it is a huge issue, repeated in v8 and v9 runbot. Dharh dsh-Odoo made it happen. I I'll post the comments from my the case on my enterprise account.

**Comment by spadae22** [comment]
@odony Here is the case https://www.odoo.com/web#id=643312&view_type=form&model=project.issue
video. Anyone who sells unit and case of 6 etc, This is a clear bug fix. https://www.youtube.com/watch?v=t2o1YOZwA90&index=5&list=TLO3k0cKdC8tsyNDEwMjAxNQ

**Pull request closed without merging**
