### PR TITLE
[FIX] account: fix mass mail wizard

### PR DESCRIPTION
**Pull request by jvnm-dev**
- In the sales or accounting module, create some invoices.
- Select them then click on `action > send & print`
- The wizard opens but not in the mass mail mode.

It creates some inconsistency and if you click on send,
the invoices are sent to the wrong customer.

Sometimes, the invoices are not sent at all.

I think the problem comes from the `_compute_composition_mode` method
who set the value of `composition_mode` on the wizard instead of
on the composer.

OPW-2085837

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jasonvanmalder** [comment]
@nim-odoo

**Comment by jpp-odoo** [comment]
robodoo rebase-ff

**Comment by nim-odoo** [comment]
robodoo rebase-ff

**Comment by sswapnesh** [comment]
@jvm-odoo 
> This bug is caused by a change in the account module, there is no more
reference, they are replaced by the name of the invoice.


The reference field is there on v13. https://github.com/odoo/odoo/blob/ed459c1bcfa8104c4116da2d5767d5ea4457463d/addons/account/models/account_move.py#L201
image

**Comment by jvm-odoo** [comment]
Thanks. I will check this

**Pull request closed without merging**
