### PR TITLE
[FIX] account: do not force users on B2B group on update

### PR DESCRIPTION
**Pull request by KangOl**
Followup of 552da8dc8d55962c69dcdfec6fc4509f61cb27f1 (#32200)

opw 1950833

### CODE REVIEW

**Comment by seb-odoo** [comment]
What issue do you solve here?

Because for me nothing works in the other PR, I can still check both on the user at the same time, and I can do it in this PR too.

**Comment by seb-odoo** [comment]
See https://screenshots.firefox.com/plpikK86YM9qkClE/494397-12-0-fix-552da8dc-chs-12b74e.runbot11.odoo.com

**Comment by seb-odoo** [comment]
I think I can do it only on a user that is not the current user or something like that (must be tested on demo and not admin).

**Comment by JKE-be** [comment]
see commit on related pr

as discuss yesterday, not critical to pull, not critical to revert. 
Just need to be fixed

**Pull request closed without merging**
