### PR TITLE
[FIX] website: handle RequestUID case in slug

### PR DESCRIPTION
**Pull request by nboulif**
Before this commit, a 308 on a route with a modelconverter for a model
that have a seo_name field will crash with an exception:
Cannot iterate on RequestUID

Another simplest solution was to use a with_user(SUPERUSER_ID) but in this case
it bypass the security set and display the name of the record even if not yet
published.

How to reproduce:

Create a 308 from /shop/<product> to /mag/<product>
Unpublish product 10
Try to access /shop/product-10

You have an unmanaged '500 internal error"
because slug_matching -> build -> to_url -> slug with a record with Requestuid
as env._uid.

X-original-commit: https://github.com/odoo/odoo/commit/4ac2cab96655a3c5e673b0a04be5599dba507850

cherry-pick: https://github.com/odoo/odoo/commit/2ecc538d516ea30254b8152e8e48c912c0c86695

opw-2749686

Backport of https://github.com/odoo/odoo/pull/64889

### CODE REVIEW

**Comment by nboulif** [comment]
Hello @JKE-be , may I ask a review please? It's a cherry-pick of one of yours fix in v15.0 .
Thanks in advance!

**Comment by nboulif** [comment]
@fw-bot up to 13.0

**Comment by rdeodoo** [comment]
Backport of https://github.com/odoo/odoo/pull/64889 (no pr on original commit msg so easier to find)
Did you test? Runbot is red

**Review by rdeodoo — CHANGES_REQUESTED** [review]
Backport of https://github.com/odoo/odoo/pull/64889 (no pr on original commit msg so easier to find)
Did you test? Runbot is red

**Review by rdeodoo — CHANGES_REQUESTED** [review]
It is not
> Backport partial of https://github.com/odoo/odoo/pull/64889

But
> Backport of https://github.com/odoo/odoo/commit/62ee506a94b9fc4a6198c87cb8a2f186ed8bc6d3

Also, AFAIC, I'd not copy paste the whole commit message but just mention this is a backport.


About the diff itself, I just quickly tested your runbot and faced a few weird behavior, I don't know if this is related to your diff or already buggy in standard, but I don't have all those odd behavior in 14.0.

Could you check the following video? https://watch.screencastify.com/v/IvRKwHtccb920zIUSVFo

Sometimes I have 404 pages :thinking: sometimes the URL changes to mag, sometimes not.

**Comment by rdeodoo** [comment]
I just tested again and I have a lot of very odd behavior, regardless if I am in debug or not and if I am logged in or not.
Randomly:
- 1/3 of time I land on the product page with the correct redirect :heavy_check_mark: 
- 1/3 of time I land on the product page without the redirect :x:
- 1/3 of time I land on a 404 :shrug: :x:

What's even more random is that if you go back to the /shop page and click again on the same products, it will randomly lead to one of the mentioned flow.

As this is a backport of 14.0 where this behavior is not happening, it is not worth spending time on 13.0 to figure what's going on. There also might be other misbehavior I did not find.
The risk/reward here is not worth.

**Pull request closed without merging**
