### PR TITLE
[IMP] l10n_co: update module description and icon

### PR DESCRIPTION
**Pull request by nla-odoo**
Task: https://www.odoo.com/web#id=2316486&action=4043&model=project.task&view_type=form&cids=2&menu_id=4720

### CODE REVIEW

**Comment by jco-odoo** [comment]
@nla-odoo What is the difference between the old and new flag?

**Comment by nla-odoo** [comment]
@jco-odoo , The new flag has a size different.

**Comment by jco-odoo** [comment]
@nla-odoo So what?

**Comment by nla-odoo** [comment]
@jco-odoo  Updated!

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
