### PR TITLE
[FIX] website: typo in toastr 'Congratulations'

### PR DESCRIPTION
**Pull request by rdeodoo**
Missing a `s`. Congratulation > Congratulations (fdba9a878f4b02).

task-2144335

### CODE REVIEW

**Comment by rdeodoo** [comment]
@qsm-odoo @JKE-be, @sbuhl was pinged since https://github.com/odoo/odoo/commit/d92f76592c1929e4cf876c615e3be03621b17abd was missing a `s` at `Congratulations`.

He was not sure if we should just revert that commit. I think it was a neutral operation as the added value wasn't that big and why would the publish action show a toaster while others don't.
At the same time, why not, it's not an invasive toaster as it disappear quickly, and publishing is not something you do often..

**Comment by sbuhl** [comment]
Copy a link: https://github.com/odoo/odoo/commit/d92f76592c1929e4cf876c615e3be03621b17abd

**Comment by rdeodoo** [comment]
?

**Comment by rdeodoo** [comment]
Ah, got it, you think there is a type on `Toastr`?
I always wrote it like that, every lib refering to those popup are named `Toastr` and always use `toastr` to name the popup..
You can google both [`Toastr`](https://www.google.com/search?q=toastr+library&sxsrf=ALeKk01fDBTBxylcXUxjd7MXVI907EbbXw:1582726832874&ei=sH5WXuX8NKXjkgWyka_oAg&start=10&sa=N&ved=2ahUKEwjllJn1tO_nAhWlsaQKHbLICy0Q8tMDegQIDBAx&biw=1853&bih=949) and [`Toaster`](https://www.google.com/search?biw=1853&bih=949&sxsrf=ALeKk02xmxtuzVxJmI7-IY8qaECIMrx5Bw%3A1582726836739&ei=tH5WXr3XLILosAfIya64Dg&q=toaster+library&oq=toaster+library&gs_l=psy-ab.3..0i71l8.11195.11195..11284...0.2..0.0.0.......0....1..gws-wiz.9P_wCAqL2sE&ved=0ahUKEwi9gYX3tO_nAhUCNOwKHcikC-c4ChDh1QMICw&uact=5) :+1:

**Comment by rdeodoo** [comment]
GUEST_8cbce1ab-9e22-4e87-8828-397ec97fc2e6

**Pull request closed without merging**
