### PR TITLE
[FIX] web: typo in _mockSearchRead

### PR DESCRIPTION
**Pull request by jhk-odoo**
https://github.com/odoo/enterprise/pull/7407#discussion_r362451701

opw-2128922

### CODE REVIEW

**Comment by jhk-odoo** [comment]
@aab-odoo 
https://github.com/odoo/enterprise/pull/7407#discussion_r362451701

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
