### PR TITLE
[IMP] make many2many tags inline block without wrapping

### PR DESCRIPTION
**Pull request by hbrunn**
For long lables in a constrained space, it looks like this:
screenshot_2015-06-05_10-03-52

and with this change, like this:
screenshot_2015-06-05_10-03-09

### CODE REVIEW

**Comment by jholze** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Good visual improvement :+1:

**Comment by lmignon** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
This change now conflict with https://github.com/odoo/odoo/commit/4fbecc35e1d37253ef9470208cafd0d2739f57f4. Looks like a different issue, though. I'll resolve the commit by keeping both changes.

**Comment by StefanRijnhart** [comment]
I'm trying to reproduce the behaviour to check if there is any undesirable interaction between the two changes, but I don't know what widget is used to demonstrate the problem in the screenshots above. One thing I notice is that the search box overflows out of my screen with a couple of large group names in an 'or' query. I find that a bit odd. @hbrunn, can you test with the scenario that incited the change from this PR? See https://github.com/OCA/OCB/wiki/8.0-2015-06-18

**Comment by StefanRijnhart** [comment]
Example of the overflow: http://pasteboard.co/1jGXy64n.png

**Comment by hbrunn** [comment]
@StefanRijnhart thanks for your screenshot, I didn't consider this possibility. I think we're better off with only `display: inline-block`, I dropped the whitespace part.

This is how long labels looked originally:
screenshot_2015-06-25_08-54-52
this with commit 4fbecc3:
screenshot_2015-06-25_08-55-17
and this with my initial proposal:
screenshot_2015-06-25_08-55-34
Now with the updated PR we are at
screenshot_2015-06-25_08-55-58

**Comment by StefanRijnhart** [comment]
Thanks for the update! :+1:

**Pull request closed without merging**
