### PR TITLE
[FIX] bus: do not miss notifications

### PR DESCRIPTION
**Pull request by tsm-odoo**
backport of https://github.com/odoo/odoo/pull/176340
enterprise: https://github.com/odoo/enterprise/pull/69045

### CODE REVIEW

**Review by seb-odoo — APPROVED** [review]
@robodoo delegate+ override=ci/security

Looking good, exact same diff as 17.4 PR.

- using `_sendone` in `_sendmany`, and in tests

**Comment by tsm-odoo** [comment]
@robodoo r+

**Comment by tsm-odoo** [comment]
@robodoo rebase-ff

**Comment by tsm-odoo** [comment]
@robodoo r+

**Comment by hwangh95** [comment]
@tsm-odoo The test for this breaks on odoo.sh. I don't know exactly what is the issue but the channels are not populated on the odoo.sh environment and the last assertion fails

**Comment by tsm-odoo** [comment]
@hwangh95 Can you confirm this fixing commit was applied on odoo.sh? https://github.com/odoo/odoo/pull/178767

**Comment by hwangh95** [comment]
@tsm-odoo Yes this is with the commit

**Comment by hwangh95** [comment]
@tsm-odoo Could you get in touch with the Odoo.sh team? I think the issue comes from #140089 where the notify function defined in `ODOO_NOTIFY_FUNCTION`, channel_notify in this case, is not sending a NOTIFY payload that the test is expecting. Running the test in my local environment works fine since it uses the standard pg_notify function.

**Comment by tsm-odoo** [comment]
Hello @hwangh95, this test will be disabled for SH. Indeed, the issue comes from the custom notify function. See this PR: https://github.com/odoo/odoo/pull/178986.

**Comment by hwangh95** [comment]
Alright sounds good!

**Comment by davidlegran** [comment]
> Hello @hwangh95, this test will be disabled for SH. Indeed, the issue comes from the custom notify function. See this PR: #178986.

Great to hear it ! :)
Thanks !

**Pull request closed without merging**
