### PR TITLE
[FIX] account: Changed zip_from and zip_to fields into type char as 0…

### PR DESCRIPTION
**Pull request by mja-odoo**
… was passed by default

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@robodoo r+

@mja-odoo thanks

**Comment by sswapnesh** [comment]
@robodoo retry 😉

**Comment by qdp-odoo** [comment]
wtf?

@robodoo r-

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@d-fence wtf?

mergebot set the r+ 5 days ago and it's stuck in that state ever since... now it targets the wrong branch (saas-12.5 has been released in the meantime)  -_-

**Comment by d-fence** [comment]
@qdp-odoo I see that unfortunately the runbot [build](http://runbot.odoo.com/runbot/build/597357) happened  during a github [outage](https://www.githubstatus.com/incidents/nt6n1hs8bk3v).

It means that the runbot was not able to transfer the status to github and thus mergebot is still waiting for it to do something.

You can re-target your PR against saas-12.5 and it should work.

**Pull request closed without merging**
