### PR TITLE
[FIX] l10n_vn: missing/incorrect account name translations

### PR DESCRIPTION
**Pull request by ngochung207**
Fixed some missing / incorrect translations of account names in the chart template.

### CODE REVIEW

**Comment by lordkrandel** [comment]
Sorry, didn't (and don't) have much of free time lately.

Anyway this PR is correct and straightforward, good job! 👍🏻 

Can you just please copy the edited PR description to the commit message, and change the title to: `[FIX] l10n_vn: missing/incorrect account name translations` please?

Thank you!

**Review by lordkrandel — APPROVED** [review]
LGTM :+1:

@smetl for final review.

**Review by smetl — COMMENTED** [review]
@robodoo r+

**Comment by ngochung207** [comment]
@smetl Please

**Comment by duong77476-viindoo** [comment]
@smetl Maybe robodo retry pls
Runbot was sleeping i guest

**Comment by smetl** [comment]
@robodoo retry
@duong77476-viindoo Sorry, I missed the ping :/

**Pull request closed without merging**
