### PR TITLE
V10 Dropshipping data must be in no update

### PR DESCRIPTION
**Pull request by bealdav**
## Description of the issue/feature this PR addresses:

Prevent dropshipping settings erasable by code update
## Current behavior before PR:

Dropshipping config can be modified by UI but will be reinitialized by an update -u all
## Desired behavior after PR is merged:

Settings must not be erasable by updates
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by florian-dacosta** [comment]
:+1:

**Comment by alexis-via** [comment]
:+1:

**Comment by bealdav** [comment]
Hi @tde-banana-odoo @jco-odoo @JKE-be, 
Could you consider this small fix.

Thanks

**Comment by mFlayyan** [comment]
:+1:

**Comment by Yenthe666** [comment]
@bealdav you forgot to ping another guy that usually looks at these. 😉 
@mart-e I agree that this is a good idea, can we merge it please?

**Comment by jco-odoo** [comment]
Logical to me too @mart-e

**Comment by JKE-be** [comment]
noupdate already missing in 9.0

**Pull request closed without merging**
