### PR TITLE
[IMP] l10n_in*: remove l10n_in_shipping_gstin

### PR DESCRIPTION
**Pull request by jva-odoo**
Deprecate the implementation of multiple GSTN units using journal id on sales, purchase and warehouse. Use multi-company incase you need the multiple GSTN.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@jva-odoo It would be good to verify if we need the shipping address somewhere else still as the field was moved from sale to account.  It would be good however to refer to the legal information about this e.g.  as the commit message is rather short.  What was the idea then to use the shipping gstin?  Was it because we thought we could have tax credit for it or because we thought it was legally required, ...

**Comment by jva-odoo** [comment]
@jco-odoo it because we thought we could have a tax credit for it. but that is not true

**Comment by jva-odoo** [comment]
@jco-odoo plz look here again

**Comment by jco-odoo** [comment]
@jva-odoo Where is the part with purchase and warehouse?

**Comment by jva-odoo** [comment]
> @jva-odoo Where is the part with purchase and warehouse?

let me check.

**Comment by jva-odoo** [comment]
The shipping address is only for sale. So it's only for sale.
there is no code exist for purchase and warehouse.

**Comment by jva-odoo** [comment]
@jco-odoo check my last msg in this PR

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
