### PR TITLE
Master base update currency dip

### PR DESCRIPTION
**Pull request by rgo-odoo**
Task: https://www.odoo.com/web#id=1823998&view_type=form&model=project.task&action=327&menu_id=4720
pad: https://pad.odoo.com/p/r.c2476dead91ed75db5b2adaceec24e41

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rgo-odoo** [comment]
LGTM

**Comment by mart-e** [comment]
Thanks!

Before merging, just a quick question to @KangOl @nseinlet : is it ok to remove currencies for migration of users that may be using it in the past?

**Comment by KangOl** [comment]
We will only remove them if they haven't been used.

Used ones will be deactivated.

**Comment by mart-e** [comment]
Ok perfect

@robodoo r+ then

**Pull request closed without merging**
