### PR TITLE
[FIX] website_sale_delivery: Avoid collect sale orders confirmed in backend

### PR DESCRIPTION
**Pull request by miguelcb2003**
[FIX] website_sale: Avoid collect sale orders confirmed in backend

This happens when, during a payment process, when the order is confirmed from the backend and in Website the cart icon is clicked.  What causes the error is that the request is still pinned in the session, so it identifies that certain values ​​should not be loaded and deletes them.

The cart() method identifies if it's not a draft order, and in that case it clears the session order to continue with a new one.  That causes undesired modifications in modules that inherit cart() and execute before calling super(), such as website_sale_delivery, that removes carrier from order. With this motification the method sale_get_order() will now discriminate the orders that are completed and clear ir from the session, avoiding losses of information.

Description of the issue/feature this PR addresses:

This error was detected because the carrier_id was eliminated when following the aforementioned flow. The problem is that clicking on the cart retrieves the order that is in the session, but if it has been confirmed from the backend it should not collect it since at that moment it is not a "cart".

A way to see this clearly is with the 'delivery_auto_refresh' module. This module shows the carrier_id field in sale order view (that exists but is not visible), which is collected at website. The flow that exists nowadays remove this value when we follow this steps:

[Grabación de pantalla desde 16-08-24 10:41:50.webm](https://github.com/user-attachments/assets/9ec82b67-3e73-4083-b65b-be8d59db6a5a)

In this video:
1. Customer starts an order
2. An user confirms the order at backend
3. Customer acceses to /shop/cart
4. Some fields of the sale order can be deleted, such as the delivery carrier

If we confirm the order at backend and then follow the flow shown, the value of this field will dissapear. This happens because, as I said before, clicking the cart icon recovers the confirmed sale order (which is no longer a 'cart') and deletes many values of it.

Current behavior before PR:

If you confirm an order in process from website at backend and then click on the cart icon, certain fields are eliminated.

Desired behavior after PR is merged:

The cart button identifies whether the order is in confirmed status (or quote sent), and if so removes it from the session before the fields are cleared, thus starting a new order.

FL-650-982
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by danielduqma** [comment]
Thanks @miguelcb2003! Makes sense, great job finding it!

**Comment by Feyensv** [comment]
`sale_get_order` is a method too central in the ecommerce logic that I don't want to touch it in stable.
I believe the problem should be fixed locally. E.g. the cart state could be checked too in the `cart` route overrides, like the delivery one.

**Comment by Feyensv** [comment]
> Is there any case `sale_get_order` should return a confirmed order? In our opinion, it is an error in this method that should be fixed globally, and not patched on every call.

I agree with that opinion, and we have improvements planned for this method (which includes not returning non draft orders), but it's not safe to change that behavior in stable.  Even if some existing code might be bad and rely on this when it shouldn't, we shouldn't break it out of nowhere in a stable version.

**Comment by miguelcb2003** [comment]
Hi @Feyensv ! The modifications you suggest were applied succesfully. Now it checks before carrier_id will be deleted, at website_sale_deliery module, avoiding that to delete te carrier_id values in non draft orders.
Thanks for the review!

**Comment by Feyensv** [comment]
I believe the same fix could be applied on the `cart` override in `website_sale_loyalty` too to make sure promotions and rewards are not modified either :eyes:

**Comment by miguelcb2003** [comment]
Hi @Feyensv , you were right! I applied this modification at website_sale_loyalty too to make sure the rewards and promotions are not beeing modified. 
Check the newest commits please to make sure if it's okay. 
Thanks for the appreciation!

**Review by Feyensv — APPROVED** [review]
@robodoo r+ rebase-ff

Perfect, thanks for the changes :+1:

**Pull request closed without merging**
