### PR TITLE
[FIX] stock_picking_batch: use lots id/name depending on picking type

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
- Create a Batch transfer and create two reciept in it each with a serial tracked product in them
- Confirm the batch transfer

Bug:
in the detailed operation tab of the batch transfer (use existing lots/ create lots) options of the picking type are not respected and lot id is displayed instead of lot name (many2one instead of char field)

Fix:
keep the same batch transfer as in the pickings that constitute it

opw-3541324

### CODE REVIEW

**Review by DjamelTouati — CHANGES_REQUESTED** [review]
Hello, thank you for the fix. Unfortunately, it's not ideal to add a new compute field, as it will require requesting a bypass from the runbot team. I believe it's better to use the "picking_type_id" field in this case: https://github.com/odoo/odoo/blob/15.0/addons/stock_picking_batch/models/stock_picking_batch.py#L54

**Comment by DjamelTouati** [comment]
LGTM, thank you for the fix

**Comment by Whenrow** [comment]
robodoo delegate=@DjamelTouati

**Comment by d-fence** [comment]
Upgrade exception [#279](https://runbot.odoo.com/web/#id=279&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
field:stock.picking.batch.show_lots_text
```
cc @KangOl @nseinlet

**Comment by DjamelTouati** [comment]
robodoo r+

**Comment by pedrobaeza** [comment]
Hi, @HANNICHE-Walid @DjamelTouati this PR provokes a problem opening any batch picking. Look this error from a 15.0 runbot:

Selección_011


I haven't dug enough yet, but it seems the parent view doesn't have `show_lots_text` added in the view. I see also risky to have an isolated view for `stock.move.line` having a dependency on `parent.<field>`.

**Comment by DjamelTouati** [comment]
@pedrobaeza  thank you for reporting this issue to us, we are working on it to fix it ASAP
have a nice day!

**Comment by DjamelTouati** [comment]
@pedrobaeza We apologize for this inconvenience, the bug was fixed in this PR: https://github.com/odoo/odoo/pull/144046

the view should only be used embedded from `stock.picking.batch` and already uses fields from the parent view
(for domain="[('id', 'in', parent.picking_ids)]")

**Comment by pedrobaeza** [comment]
Thanks for the quick reaction.

**Pull request closed without merging**
