### PR TITLE
Saas 12.3 opw 2410666 fix agr

### PR DESCRIPTION
**Pull request by agr-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@nle-odoo Just backporting old commits

**Comment by agr-odoo** [comment]
@fw-bot ignore

**Review by nle-odoo — APPROVED** [review]
robodoo r+ delegate+

**Comment by agr-odoo** [comment]
robodoo rebase-ff

**Comment by nle-odoo** [comment]
why is there 4 commits here and 1 in 12.0 and 1 in 13.0 ? if it's okay you can r+
 
robodoo rebase-ff r-

**Comment by nle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
