### PR TITLE
[9.0][purchas] create only invoice lines when needed

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Description of the issue/feature this PR addresses:
Testing this PR:
https://github.com/OCA/account-invoicing/pull/230

I'm facing this error, only in OCB (not testing with odoo):
https://travis-ci.org/OCA/account-invoicing/jobs/202337862#L1043

Looks like the error here: https://travis-ci.org/OCA/account-invoicing/jobs/202337862#L1008
is caused because new_lines is blank?
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please clean your branch. No need to close, but just force push the proper branch

**Comment by jbeficent** [comment]
Once the PR is created I can swith to another branch of the same repo only.

**Comment by pedrobaeza** [comment]
It's not about changing the target. I repeat my sentence: "force push the proper branch". What does mean? On local, you create a branch with the same name (9.0-Eficent-purchase-fix), properly rebase on current origin/9.0, and with the commit you want to add, and then just do `git push eficent -f` (being eficent the name of your remote), and you will have this PR amended.

**Comment by jbeficent** [comment]
Hmm. The

**Pull request closed without merging**
