### PR TITLE
[ADD] web: bs5 utility-classes, add positions

### PR DESCRIPTION
**Pull request by stefanorigano**
Add "BTS5 ready" position utility classes.
https://getbootstrap.com/docs/5.1/utilities/position/#arrange-elements

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by adr-odoo** [comment]
@stefanorigano Feel free to undraft it when you're ready!

**Comment by stefanorigano** [comment]
@adr-odoo , un-drafted  👍

**Review by adr-odoo — APPROVED** [review]
@robodoo t+

**Comment by adr-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
