### PR TITLE
[10.0][FIX] prevent calling costful methods on empty recordset

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
Some methods are called on empty recordset causing lacking of performance.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
OPW-769720

**Comment by Yenthe666** [comment]
I like this one - good improvement @Cedric-Pigeon!

**Comment by Yenthe666** [comment]
@jco-odoo could you merge this PR in? Since you're the stock & MRP guy 😄

**Comment by simongoffin** [comment]
Closed with 5adb77c00f55b41b9b7a195f2d5121446d72f0b0

**Pull request closed without merging**
