### PR TITLE
[ADD] l10n_be: add states for Belgium

### PR DESCRIPTION
**Pull request by Yenthe666**
Current behavior before PR: The Belgian states are not listed/shown in Odoo.

Desired behavior after PR is merged: The Belgian states are shown in Odoo.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e last localization that I'm doing - enjoy 😉

**Comment by jeffery9** [comment]
> I highly doubt this will be accepted. First of all it adds new data so it should be done against the master version and not 11.0

???

**Comment by elicoidal** [comment]
@jeffery9 that's the point: this PR is against master, not 11.0

**Comment by Yenthe666** [comment]
Yep, the difference is that this PR is against master and yours is against 11.0
Plus yours are cities, mine are states, which is way less data.

**Comment by mart-e** [comment]
Thanks!

**Comment by adekock11** [comment]
@Yenthe666 and @mart-e quick question. Why are some of the states in `l10n_*` modules and some in `odoo/addons/base/res/res_country_state.csv`? What is the preferred way?

I am thinking of writing a `l10n_za` module, but the states are already in `base`, however should they be in `base` or was the reason for putting it in base that there is no `l10n_za`?

**Comment by Yenthe666** [comment]
@adekock11 ideally is to have the states in the country specific module (so `l10n_*`).
If the data is already in base then I think we should consider moving them from base to `l10n_za` in the master version of Odoo.
Final call is up to @mart-e about moving from base to `l10n_za` though.

**Comment by mart-e** [comment]
@adekock11 should always be in the l10n_* modules.
We are not moving the existing one to avoid breaking things for the sake of cleaning the code.

**Comment by Yenthe666** [comment]
@mart-e not even in master?

**Comment by mart-e** [comment]
@Yenthe666 nope, moving records will break things (changing the XMLID) and if we have no real reason to do so, we won't do it.

We plan to move the country-specific data outside of the l10n modules (which forces you to install `account`), and at that time, we will move all the states at that time but this is not started yet (maybe for v12 or v13).

**Comment by Yenthe666** [comment]
Gotcha, thanks for the feedback.

**Comment by adekock11** [comment]
Understood. Thanks for the answer guys!

**Comment by JKE-be** [comment]
image

Why add states for a country that doesn't use it in address format or accouting ???

**Comment by Yenthe666** [comment]
@JKE-be actually we had quite some customers who wanted to fill in the states in Belgium (even if they're not on the default reports). For example for grouping, filtering, searching.

**Pull request merged**
