### PR TITLE
[FIX] product: constrain on attribute values

### PR DESCRIPTION
**Pull request by nim-odoo**
Add a constrains to prevent the selection of more than one value of the
same attribute, as it was the case in v8.

opw-653125

### CODE REVIEW

**Comment by xmo-odoo** [comment]
Wouldn't an SQL UNIQUE constraint make more sense?

**Comment by nim-odoo** [comment]
@xmo-odoo : is it possible to do so in such a case? I don't find any example that would add a unique constrain on a Many2many.

Moreover a sql constrain in V9 would imply a -u on product, which might not be the best idea on a stable release.

**Comment by xmo-odoo** [comment]
>  is it possible to do so in such a case? I don't find any example that would add a unique constrain through a Many2many.

Sure, just add a unique constraint on the M2M link table (you may want to name it explicitly or even set it up as a genuine model).

> Moreover a sql constrain in V9 would imply a -u on product, which might not be the best idea on a stable release.

Good point /cc @odony your thoughts?

Either way I'd recommend that attributes be a set, or that you use a collections.Counter and check if any item has a count > 1 (using `most_common(1)`)

**Comment by nle-odoo** [comment]
@xmo-odoo 

> Sure, just add a unique constraint on the M2M link table (you may want to name it explicitly or even set it up as a genuine model).

I think in this instance, we need two table since we want unicity over product.product and product.attribute but there is no direct link, it is like this:

__`product_product`__.(many2many [`product_attribute_value`]).__(many2one [`product_attribute`])__

and there is no direct link between `product.attribute` and `product.product`

**Comment by xmo-odoo** [comment]
Oh I see, you're right I had missed a level of indirection.

**Pull request merged**
