### PR TITLE
[FIX] account: amount by group adapt to repartition

### PR DESCRIPTION
**Pull request by kebeclibre**
Before this commit, when printing an invoice that has at least
one tax which is part of a tax group and some repartition lines

On the invoice pdf the group of tax contained twice the base amount for that
tax

After this commit, the tax group contains the base only once

OPW 2073989

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by oco-odoo** [comment]
@robodoo r+

**Comment by kebeclibre** [comment]
yo @oco-odoo 
That fix is wrong.
with 3936d655c4bfd845b6ead724cecdc8e7c62816eb
we compute all for each line of the invoice, so, there is a tax line for every invoice line
just realized that now

**Comment by oco-odoo** [comment]
@kebeclibre There is a tax line for each repartition line, rather; right ? So, for each tax, we only add its base amount once. I did not check in detail now, but are you sure there is still an issue here? Still seems ok to me.

**Comment by kebeclibre** [comment]
@oco-odoo 
Yes, there is still an issue
It is because of the get_grouping_key, overriden in l10n_in
@jco-odoo 

I think the only viable solution is to not display the base in the invoice pdf, as I already did back in 12.0 for standard invoice

**Pull request closed without merging**
