### PR TITLE
Saas 14.5 fix padding controls buttons bvr

### PR DESCRIPTION
**Pull request by bvr-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qsm-odoo** [comment]
Merged this https://github.com/odoo/odoo/commit/4de5d51948a121bb6df716f1b99cd86511b9cba9 to fix the bug but keeping this PR opened for now until the onFocus/onBlur problem is investigated.

**Comment by bvr-odoo** [comment]
> Merged this [4de5d51](https://github.com/odoo/odoo/commit/4de5d51948a121bb6df716f1b99cd86511b9cba9) to fix the bug but keeping this PR opened for now until the onFocus/onBlur problem is investigated.

@qsm-odoo Do we still neeed this PR to be open ?

**Comment by qsm-odoo** [comment]
@bvr-odoo I fixed this with https://github.com/odoo/odoo/commit/0acc5e784b15d9c963660da3781763448503f33e so this can be closed. Maybe check that the feature you were trying to fix here has properly been fixed by my commit :scream:

**Comment by bvr-odoo** [comment]
> @bvr-odoo I fixed this with [0acc5e7](https://github.com/odoo/odoo/commit/0acc5e784b15d9c963660da3781763448503f33e) so this can be closed. Maybe check that the feature you were trying to fix here has properly been fixed by my commit scream

@qsm-odoo yes it's properly fixed so I close this PR ;)

**Pull request closed without merging**
