### PR TITLE
[FIX] portal: ensure only one "grant access" action

### PR DESCRIPTION
**Pull request by nseinlet**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by std-odoo** [comment]
What does it change from a functional POV ?

**Comment by nseinlet** [comment]
> What does it change from a functional POV ?

Without this fix, you have twice "Grant portal access" in partner form view for a migrated db, one will fill the partner in the wizard, the other will launch the wizard without any pre-selected partner.

**Comment by std-odoo** [comment]
> > What does it change from a functional POV ?
> 
> Without this fix, you have twice "Grant portal access" in partner form view for a migrated db, one will fill the partner in the wizard, the other will launch the wizard without any pre-selected partner.

Oh :O Good catch :) good to know

**Comment by tde-banana-odoo** [comment]
Could be great to include that explanation in commit message :)

**Comment by tde-banana-odoo** [comment]
Thanks !

@robodoo r+

**Pull request closed without merging**
