### PR TITLE
[IMP] hr_contract : rename the label Contract Type to Employee Category in Groupby filter

### PR DESCRIPTION
**Pull request by nje-odoo**
Task : https://www.odoo.com/web#id=1871507&action=327&model=project.task&view_type=form&menu_id=4720

pad : https://pad.odoo.com/p/r.2663c14086c9292b63983e37aabd68c2

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by KangOl** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo retry again

**Comment by tivisse** [comment]
@robodoo retry

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo retry and merge or I'll find you and steal your cat.

**Pull request closed without merging**
