### PR TITLE
[FIX] auth_ldap: LDAP login fails if it creates a new user

### PR DESCRIPTION
**Pull request by lightapp24**
See issue #41060

### CODE REVIEW

**Review by rco-odoo — COMMENTED** [review]
You may not change the serialization level of **all** requests to fix your problem.
The problem is in the business code, fix it in the business code.
Following your explanation in https://github.com/odoo/odoo/issues/41060#issuecomment-778223732, it seems that the user creation should either not be done in another transaction, or maybe should commit the first transaction to make it "see" what's in the other one.

**Comment by odony** [comment]
That's a terrible idea ;)

We cannot compromise the serializable properties of our transactions - those are critical in an enterprise management system. And here you're making non-serialized cursor the default for all request cursors, which would cause tons of subtle transaction isolation inconsistencies everywhere.

The fix must be done [here](https://github.com/odoo/odoo/blob/4205cb2/addons/auth_ldap/models/res_users.py#L17), by using the request cursor instead of making a new one (when `request` is available). It will also save a useless connection in many cases.

**Comment by xmo-odoo** [comment]
@odony this may be something we need to fix in the totp though, I apparently completely forgot that the login process was historically not assuming any cursor, now there's a hard dependency on one, but that means any third-party auth which is done in the "normal" style and assumes it has to create a cursor to do its thing may break.

**Comment by odony** [comment]
> Thinking about it, the 2FA should probably create its own cursor to do the check in `authenticate` instead of assuming / using the request cursor. This way it would see anything which has been committed inside authenticate, including new user records aka

Isn't that making the problem worse? To me, each extra cursor we use is an increased chance of causing inconsistencies and errors. And you'll still need to force commits in all auth-related cursor just to make it work.

I much prefer trying to reuse the main request cursor everywhere, as soon as it is available. If it's not available, then it cannot be outdated. That also saves extra cursor allocations/db backend connections.

**Comment by xmo-odoo** [comment]
> Isn't that making the problem worse? To me, each extra cursor we use is an increased chance of causing inconsistencies and errors.

In the context of the auth specifically, it should not: `_login` overrides create and commit their own cursors (inside `authenticate`), so creating a cursor outside of it should ensure all the `authenticate` work is visible.

>  And you'll still need to force commits in all auth-related cursor just to make it work.

That's already the case otherwise they plain don't work.

> I much prefer trying to reuse the main request cursor everywhere, as soon as it is available. If it's not available, then it cannot be outdated. That also saves extra cursor allocations/db backend connections.

That is only feasible by rewriting the entire auth stack to use the request cursor, but this may break any override to `_login`. Not to mention since the `_login` protocol is currently predicated entirely on raising exception and each attempt being siloed (by virtue of having to create its own connection), changing the protocol to rely on the one global request means each override now has to ensure it cleans up the transaction on failure.

**Comment by lightapp24** [comment]
Maybe then, instead of the BD name, send the cursor to res.users->authenticate ?

**Comment by odony** [comment]
> That is only feasible by rewriting the entire auth stack to use the request cursor, but this may break any override to `_login`. Not to mention since the `_login` protocol is currently predicated entirely on raising exception and each attempt being siloed (by virtue of having to create its own connection), changing the protocol to rely on the one global request means each override now has to ensure it cleans up the transaction on failure.

Alright then, but I don't think that patch will completely fix the problem. For example, `finalize()` will still access the request cursor and fail to compute the session token, on the very next line. I guess issue #41060 was reported in 13.0 because the problem already existed there, so it would have to be fixed in older series too.

And before we jump into allocating new cursors for every step, let me point out that we used to do it, and it _was_ creating problems: c8243e71c6da37547a19f61c58f25d5d03e13d38.

A simpler fix could be to just `commit()` the request cursor at the beginning of `session.authenticate()`, considering that it needs to see whatever the siloed auth layers have been doing before calling it?

It also means that the request cursor will now be able to "see" the current user, even when it is an auto-magically created one. That seems an important property, because otherwise we'll keep seeing similar errors at every step of the way - the current user is kind of a central concept during request processing.

**Comment by lightapp24** [comment]
> > That is only feasible by rewriting the entire auth stack to use the request cursor, but this may break any override to `_login`. Not to mention since the `_login` protocol is currently predicated entirely on raising exception and each attempt being siloed (by virtue of having to create its own connection), changing the protocol to rely on the one global request means each override now has to ensure it cleans up the transaction on failure.
> 
> Alright then, but I don't think that patch will completely fix the problem. For example, `finalize()` will still access the request cursor and fail to compute the session token, on the very next line. I guess issue #41060 was reported in 13.0 because the problem already existed there, so it would have to be fixed in older series too.
> 
> And before we jump into allocating new cursors for every step, let me point out that we used to do it, and it _was_ creating problems: [c8243e7](https://github.com/odoo/odoo/commit/c8243e71c6da37547a19f61c58f25d5d03e13d38).
> 
> A simpler fix could be to just `commit()` the request cursor at the beginning of `session.authenticate()`, considering that it needs to see whatever the siloed auth layers have been doing before calling it (or whatever `res.users.authenticate()` did)?
> 
> ```diff
> diff --git odoo/http.py odoo/http.py
> index d4475b2936ca..f75ad7df9cd0 100644
> --- odoo/http.py
> +++ odoo/http.py
> @@ -1000,6 +1000,10 @@ class OpenERPSession(sessions.Session):
>              REMOTE_ADDR=wsgienv['REMOTE_ADDR'],
>          )
>          uid = odoo.registry(db)['res.users'].authenticate(db, login, password, env)
> +
> +        # request env needs to be able to access the latest changes from the auth layers
> +        request.env.cr.commit()
> +
>          self.pre_uid = uid
>  
>          self.rotate = True
> ```
> 
> It also means that the request cursor will now be able to "see" the current user, even when it is an auto-magically created one. That seems an important property, because otherwise we'll keep seeing similar errors at every step of the way - the current user is kind of a central concept during request processing.

This is a simple way, but if an error occurs during execution, then the database, I think, will be rolled back to this commit and not to the very beginning.

**Comment by lightapp24** [comment]
> ```diff
> diff --git odoo/http.py odoo/http.py
> index d4475b2936ca..f75ad7df9cd0 100644
> --- odoo/http.py
> +++ odoo/http.py
> @@ -1000,6 +1000,10 @@ class OpenERPSession(sessions.Session):
>              REMOTE_ADDR=wsgienv['REMOTE_ADDR'],
>          )
>          uid = odoo.registry(db)['res.users'].authenticate(db, login, password, env)
> +
> +        # request env needs to be able to access the latest changes from the auth layers
> +        request.env.cr.commit()
> +
>          self.pre_uid = uid
>  
>          self.rotate = True
> ```


This is an easy way and, I think, this is not very elegant than 
https://github.com/odoo/odoo/pull/66177/commits/73f5bd6cd0f2b445773ba34f92a30f29f17322bf , because there use only one cursor.  But at the moment, your way is the only way to solve the problem.

**Comment by denilson020898** [comment]
It is cleaner to do it with context

Override the login

```
            ctx = (request.context.copy())
            ctx.update(res_users_patch=True)
            request.context = ctx
            return super().web_login()

```

Patch the http controller
```
        if request.env.context.get('res_users_patch', False):
            breakpoint()
            request.env.cr.commit()
```

**Comment by eLBati** [comment]
Proposing fix for v16 with https://github.com/odoo/odoo/pull/162456

**Pull request closed without merging**
