### PR TITLE
[IMP] document: improved PDF text extraction

### PR DESCRIPTION
**Pull request by len-foss**
PyPDF performs badly on many types of PDF documents.
We add an optional text extraction using pdfminer that is designed for this task

opw 1889825

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Elkasitu** [comment]
FWIW pdfminer [doesn't officially support python 3](https://github.com/euske/pdfminer/#how-to-install), however there is a [fork](https://github.com/pdfminer/pdfminer.six) that does.

pdfminer also looks unmaintained (latest commit dating from Sept 2016...).

Perhaps this should be closely discussed with @fda-odoo and @ThanhDodeurOdoo

**Comment by len-odoo** [comment]
This is a matter of install, solved with pip install pdfminer.six
(the import is still pdfminer)
Last commits on https://github.com/pdfminer/pdfminer.six/commits are 4 days old.

**Comment by ThanhDodeurOdoo** [comment]
@len-odoo @antonylesuisse est ok pour ajouter cette librairie

le nouveau fichier où l'ajouter est
https://github.com/odoo/odoo/blob/master/addons/attachment_indexation/models/ir_attachment.py

**Comment by len-odoo** [comment]
@ThanhDodeurOdoo "add the library" as add it in the requirements? So in 12.5?

**Comment by ThanhDodeurOdoo** [comment]
@len-odoo no add the support, so basically just your commit adapted to master

**Comment by len-odoo** [comment]
Is it useful? 
For now either you can install the library on your server and put the local diff, or you can't put the diff (because you're on our SaaS for instance), but then you can't install the library either. 
So I don't see what it would solve.

**Comment by ThanhDodeurOdoo** [comment]
I guess it's just for the diff; I'll ask if we can add it to requirements

**Comment by ThanhDodeurOdoo** [comment]
@len-odoo Antony est ok pour l'ajouter aux requirements ( https://packages.ubuntu.com/disco/python3-pdfminer ) et merger ce commit sur master

**Comment by len-odoo** [comment]
All right: then should be replaced by https://github.com/odoo/odoo/pull/38508

**Pull request closed without merging**
