### PR TITLE
[IMP] mass_mailing: use m2o_reference on mailing.trace

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Description of the issue/feature this PR addresses:

Let's make use of Many2oneReference as a better tool to link the model and the id.

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for the proposal! Seems interesting indeed :) . By the way, while cleaning this model, shouldn't we make res_id / model fields required ? I don't think we have valid use cases implying traces on "not a model", what do you think ?

Cheers,

**Comment by MiquelRForgeFlow** [comment]
@tde-banana-odoo done :)

**Comment by MiquelRForgeFlow** [comment]
@tde-banana-odoo it's breaking tests with the required attribute

**Comment by tde-banana-odoo** [comment]
@MiquelRForgeFlow yeah, and you would have to write a migration script and I suppose you do not have access to it. I will make a separate task for that, just keep the m2o reference then :) .

**Comment by MiquelRForgeFlow** [comment]
@tde-banana-odoo revert done :)

**Pull request closed without merging**
