### PR TITLE
[IMP] core: prettify sql queries in logs and tests

### PR DESCRIPTION
**Pull request by Julien00859**
sqlparse is a python library that can be used to pretty-format SQL
queries. We use it to pretty-print queries for `--log-sql` and in
tests for `AssertQueries`. The library is optional and will emit a
warning upon being used but not installed (as a way to advertize its
existence to our fellow developers).

It can be installed via apt `python3-sqlparse` or via pip `sqlparse`.

As an example, the following query logged on a single line:

    SELECT "ir_module_module"."id" FROM "ir_module_module" WHERE ("ir_module_module"."state" = 'installed') ORDER BY  "ir_module_module"."name"

becomes:

    SELECT "ir_module_module"."id"
    FROM "ir_module_module"
    WHERE ("ir_module_module"."state" = 'installed')
    ORDER BY "ir_module_module"."name"

### CODE REVIEW

**Comment by d-fence** [comment]
As sqlparse is only used here in debug mode or for the assertions in tests, I would prefer to not add it in the `requirements.txt` file.

But, as it's a very nice to have feature, I propose that we add the [package](https://packages.ubuntu.com/jammy/python3-sqlparse) in the Docker image of the runbot once your PR is merged.

Before that, I propose that you modify your code to make it optional. Odoo should work without the package installed.

Also, to test your feature on runbot, you could add a temporary commit that adds the 
`sqlparse==0.4.1` line in the requirements.txt. That way you will be able to test it on runbot.
Before merging, we will remove the commit to ensure it works also without this package.

**Comment by Julien00859** [comment]
> Also, to test your feature on runbot, you could add a temporary commit that adds the
sqlparse==0.4.1 line in the requirements.txt.

We are going to need the (upcoming) version 0.4.4 of the library, the library is not yet compatible with postgres JSON operators (planned for 0.4.4) see https://github.com/andialbrecht/sqlparse/issues/682#issuecomment-1463926820. I suggest we put this PR on hold until then...

As it would be an optional lib only installed in dev and on runbot I don't know whether we need to wait for an official debian/ubuntu package too?

**Comment by Julien00859** [comment]
I tried replacing reindent=True by reindent_aligned=True, it works when it comes to using upgrade's style SQL but it doesn't respect the wrap_after:

reindent:

    SELECT name, id, state, demo AS dbdemo, latest_version AS installed_version
    FROM ir_module_module
    WHERE name IN ('base', 'web', 'web_kanban_gauge', 'web_gantt', 'web_grid', 'base_import',
                   'base_setup', 'web_cohort', 'auth_totp', 'bus', 'web_tour', 'web_enterprise',
                   'iap', 'web_map', 'web_editor', 'web_unsplash', 'web_mobile')



reindent_aligned:

    SELECT name,
           id,
           state,
           demo AS dbdemo,
           latest_version AS installed_version
      FROM ir_module_module
     WHERE name IN ('base', 'web', 'web_kanban_gauge', 'web_gantt', 'web_grid', 'base_import', 'base_setup', 'web_cohort', 'auth_totp', 'bus', 'web_tour', 'web_enterprise', 'iap', 'web_map', 'web_editor', 'web_unsplash', 'web_mobile')

 
So I'll stick with reindent

**Comment by william-andre** [comment]
> but it doesn't respect the wrap_after

The example you gave proves that we don't really care about `wrap_after`. 
Either the list is short: you don't need to wrap.
Either it is long: wrapping doesn't make it more readable, you need to use a search tool to find what you are looking for since it is not even ordered.

I would even argue that it makes it less readable because it kind of breaks the logic of the query by putting a big blob in the middle of it.

**Comment by Julien00859** [comment]
Sure, you read very well the end of the query

image

**Comment by william-andre** [comment]
> Sure, you read very well the end of the query

That is my point: I don't care about the end of the query. It is just a list of values.
What matters is the query structure: the tables the fields, the conditions

**Comment by Julien00859** [comment]
In the terminal you still have that big blob, no matter `wrap_after`

**Comment by Julien00859** [comment]
It turns out the lib is too slow

**Pull request closed without merging**
