### PR TITLE
[FIX][15.0] mail: prevent bad query

### PR DESCRIPTION
**Pull request by royle-vietnam**
In database with front end, there are lot of bad query like this:
UPDATE "mail_channel_partner" SET "fetched_message_id"=?,"write_date"=?,"write_uid"=?WHERE id IN (?)

Because method channel_fetched may be called multiple times and we don't care having small errors in last fetched compared to performance issues.

Solution:
Using try...except to avoid concurrent updates error (instead of raising
an exception, wait for a moment and retry)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by royleviindoo** [comment]
@tde-banana-odoo @seb-odoo  ping, please

**Comment by tde-banana-odoo** [comment]
This is more for @seb-odoo as far as I see.

**Comment by seb-odoo** [comment]
Hello, when the issue happens does it show an error in the client UI or is it just a server log about concurrency issue?

Because it does not really look like a "bug" to fix in stable, more an improvement.
Also while I agree that it is fine if some fetched message information are actually lost, ideally the last one should take priority, not the first one, which is the opposite of what is done here.

If the issue is coming from the same client sending too many of them in quick succession, the proper fix is probably to throttle this RPC client side. Also if multiple tabs are open, it should only be sent from the main tab, not all others.

**Comment by royleviindoo** [comment]
> Hello, when the issue happens does it show an error in the client UI or is it just a server log about concurrency issue?
> 
> Because it does not really look like a "bug" to fix in stable, more an improvement. Also while I agree that it is fine if some fetched message information are actually lost, ideally the last one should take priority, not the first one, which is the opposite of what is done here.
> 
> If the issue is coming from the same client sending too many of them in quick succession, the proper fix is probably to throttle this RPC client side. Also if multiple tabs are open, it should only be sent from the main tab, not all others.

It is just a server log about concurrency issue, it doesn't show an error in the client UI
I close this PR. Thank you for response.

**Pull request closed without merging**
