### PR TITLE
[FIX] account: bold styling applied to the element

### PR DESCRIPTION
**Pull request by PallaviSrivastavaa**
Description of the issue/feature this PR addresses: Attribute style has two apostrophes (') at the beginning and end which is preventing the style from being applied to the element.

Current behavior before PR:Attribute 'style' has two apostrophes (') at the beginning and end in '/Desktop/odoo/addons/account/static/src/components/tax_totals'/tax_totals.xml'

Desired behavior after PR is merged: The  apostrophe was removed from the XML file, correcting the style of the element while making sure other elements are unaffected.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by gawa-odoo — COMMENTED** [review]
Hello, and thanks for your contribution.
Changing this does change a functionality. 
You can see it as the bold is not put previously, and your change does fix it.
Can you change your commit and the PR message to imply that we now apply the style that is described?

**Comment by PallaviSrivastavaa** [comment]
@gawa-odoo oh I missed it! thank you I'll fix the message and the commit.

**Review by gawa-odoo — APPROVED** [review]
LGTM

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+ rebase-ff

**Pull request closed without merging**
