### PR TITLE
fix QUnit context in js tests

### PR DESCRIPTION
**Pull request by leorochael**
Description of the issue/feature this PR addresses:

It's currently possible to pass `hook` methods to QUnit, the existing hooks are: `before()`, `beforeEach(assert)`, `afterEach(assert)`, `after()`.

The context (`this`) bound to these methods is the QUnit test execution context, which QUnit documents as places where you can do common initializations before and among test functions.

However, Odoo currently creates a completely different context (`this`) for in the test wrapping function for running these test functions, making it impossible to use the hooks for what they were designed.

Furthermore, the initialization of odoo services and helpers for javascript happens inside this wrapper, which keeps them from being used by `beforeEach()`

Current behavior before PR:

The `this` of hook functions, like `beforeEach()` (equivalent to `def setUp(self)` on Python unittests) is not the same `this` that the tests run against, and it's not possible to use the Odoo js infrastructure from these methods.

Desired behavior after PR is merged:

`beforeEach()` and `afterEach()` can be used to create infrastructure that can then be employed by code inside the tests, and have access to the odoo js infrastructure.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by leorochael** [comment]
@ged-odoo, Thank you for your attention to #14865.

Would you mind taking a look at this as well? Or pointing out who else should take a look?

**Comment by ged-odoo** [comment]
I had a quick look on this yesterday.  My first impression is that it is a nice work, and that you are one of the rare person bold enough to look at our QUnit system.

However, I think that I should mention that we are in the process of completely rewriting our JS views (and will do the same with the rest of the web client as soon as we can).  One of our design goal is to make it easy to test (almost) everything in web client, you can have a look at
https://github.com/odoo-dev/odoo/tree/master-web-views/addons/web/static/test/views
to have a taste of what is coming.

We did change a lot of stuff in the code and in the test.  One of the noteworthy changes in the tests is that we no longer have our weird QUnit integration and use vanilla QUnit.  Also, our tests are started after all other JS modules have been started, instead of just after the dependencies.

In practice, this means that
1) it is much easier to write tests
2) tests actually test that all the code in the addons did not break the basic functionality of the web client
3) tests are slightly less independant.  They can work with no addon installed, but break when a specific addon is installed.  This is a tradeoff that we consider ok, given the benefits of 1 and 2.

This work will be merged in master, not in 10.0.  So, I suppose that we can merge this PR now, but it will not be used (except the extra tests, thanks for those) when master-web-views is merged later.

**Comment by ged-odoo** [comment]
I'll come back to this PR as soon as I can, I have some more urgent work right now

**Comment by leorochael** [comment]
@ged-odoo, any updates on this?

**Comment by ged-odoo** [comment]
merged in 10.0, slightly reworded (I added the 'web:' prefix to the commit message)

Thank you for your contribution, sorry for the delay

**Pull request closed without merging**
