### PR TITLE
New automatic import in server actions 

### PR DESCRIPTION
**Pull request by Whenrow**
This PR aims to add Odoo tools available in server actions.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Whenrow** [comment]
@odoo/rd-security Hello, 
we sometimes need to fix stock issues on production database. Having the possibility to use float_compare, float_round, ... would be nice in order to reuse existing code into the server actions directly. 
I set float_utils, but I guess others tools classes could also be added.

**Comment by xmo-odoo** [comment]
> I set `float_utils`

That's illegal. Modules should not be provided to evaluation contexts, only functions.

**Comment by mart-e** [comment]
:+1: for this second version.
If you need something else than `float_compare`, we could also use the `wrap_module` (not sure in which version it's available) around `float_utils` to whitelist only the methods you need.
If only `float_compare` is needed, this should be fine.

**Comment by Whenrow** [comment]
@mart-e good to know but I'm good with this one. Thanks

**Comment by xmo-odoo** [comment]
> If you need something else than `float_compare`, we could also use the `wrap_module` (not sure in which version it's available) around `float_utils` to whitelist only the methods you need.

TBF I'd recommend against that, `wrap_module` is mostly a compatibility bandaid. If we know we want to provide a bunch of items and want to keep them under the same namespace, hand-rolling a wrapper of some sort is likely a better idea.

**Comment by Whenrow** [comment]
I guess I can @robodoo r+ 
Thanks

**Comment by xmo-odoo** [comment]
@robodoo r+ must be at the start of the line.

**Comment by Whenrow** [comment]
> @robodoo r+ must be at the start of the line.

**Pull request closed without merging**
