### PR TITLE
[IMP] website: add mega menu feature

### PR DESCRIPTION
**Pull request by kea14**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kea14** [comment]
Hey @qsm-odoo,

The mega menu feature is back but I've an issue when opening/closing the dropdown mega menu (only when in editor). I get this js error `Cannot read property 'disabled' of null` from there `web/static/lib/bootstrap/js/dropdown.js:167`.

Maybe do you have an idea where this problem comes from ?
Thx

**Comment by kea14** [comment]
@qsm-odoo By chance have you had sometime for the issue I'm facing with `dropdown.js` ? I'll re-take a look now but in fact I wish to know if at least you ever heard about this, thanks :smile:

**Comment by qsm-odoo** [comment]
@kea14 No I don't know... you can have a look

**Comment by qsm-odoo** [comment]
@kea14 You can rebase on top of saas-12.5 now, my branch for the editor has been merged

**Comment by kea14** [comment]
@qsm-odoo I took some time yesterday trying to figure out but I don't really understand what is causing this issue but it has something to do with `.dropdown()`. This issue is in editor mode and only happens on the first click (when opening the mega menu).

**Comment by qsm-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
Damn you @robodoo, r+ !

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@robodoo r+ !

**Pull request closed without merging**
