### PR TITLE
[IMP] survey: Fix Vietnamese font errors on survey_reports

### PR DESCRIPTION
**Pull request by phamthuha0970**
Description of the issue/feature this PR addresses:

Current behavior before PR:
Vietnamese font error on survey module. I choose Monsterrat font because Trueno is a folked version of Monsterrat
(https://user-images.githubusercontent.com/25703866/189086006-2a7263ff-17e3-41ea-b4f9-c24451f39d89.png)

Desired behavior after PR is merged:
Vietnamese font isn't error
(https://user-images.githubusercontent.com/25703866/189085425-3e5773b8-10b0-434a-b16c-f4d12e05a532.png)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Ngquang — APPROVED** [review]

**Comment by Ngquang** [comment]
Mornings @awa-odoo , can you take a look on this?
Thanks man.
cc @maan-odoo

**Comment by Ngquang** [comment]
@awa-odoo According to https://fontlibrary.org/en/font/trueno, `Trueno` is folked from `Montserrat` so it's basically same type. But `Montserrat` support a huge languages and i think you should considering about this changes

**Comment by Ngquang** [comment]
Hi @awa-odoo, any news about this Pr? 
cc @edi-odoo @d-fence

**Comment by awa-odoo** [comment]
> Hi @awa-odoo, any news about this Pr? cc @edi-odoo @d-fence

Hello @Ngquang 

Can't really help you as I'm not the one who changed the fonts.
Waiting from an answer from @d-fence and @edi-odoo still.

Cheers!

**Comment by Ngquang** [comment]
@d-fence hi, can you review this changes? thanks man.

**Comment by d-fence** [comment]
I have no objections against this change.
But if we go this way, you have to remove the old font (and its license file) too as it's not used anywhere else.
Now the last word goes to @edi-odoo

**Comment by Ngquang** [comment]
@d-fence AFAIK this font only using in Surveys. Thanks man.
@edi-odoo Hi, can you give opinions about this? Thanks man.

**Comment by phamthuha0970** [comment]
@edi-odoo Hi, can you give opinions about this? Thanks man.

**Comment by phamthuha0970** [comment]
@edi-odoo can you give opinions about this? Thanks man.

**Comment by phamthuha0970** [comment]
@d-fence AFAIK this font only using in Surveys. Thanks man.

**Comment by phamthuha0970** [comment]
@d-fence AFAIK this font only using in Surveys. Thanks man.

**Review by d-fence — CHANGES_REQUESTED** [review]
As asked in a previous comment, can you also remove the old unused files:
* `addons/survey/static/src/fonts/Trueno-ofl.txt`
* `addons/survey/static/src/fonts/Trueno-wml2.otf`
* `addons/survey/static/src/fonts/TruenoBd.otf`
Thanks

**Comment by edi-odoo** [comment]
Hi there, 
I was off sick for 3 months, for future reference you can contact @stefanorigano when you don't get a reply in the next couple of days.

Otherwise LGTM 👍
cc @d-fence @awa-odoo

**Comment by Ngquang** [comment]
@d-fence @edi-odoo Thanks everyone
Ping @phamthuha0970

**Comment by phamthuha0970** [comment]
@d-fence @edi-odoo I have changed as your wish. You can check my request. Thank you

**Comment by Ngquang** [comment]
cc @stefanorigano

**Comment by phamthuha0970** [comment]
@stefanorigano Can you give opinions about this? Thanks man.

**Comment by stefanorigano** [comment]
Hello @phamthuha0970  and @Ngquang ,

I don't have remarks on the visual result, the two fonts are very similar indeed.
Moreover `Montserrat`is included in the bundle already... beside solving the issue, this PR will reduce the footprint too.

@d-fence , LGTM 👍 

Thanks for the fix and the patience 😄

note: out of scope for this PR, but we should review the default font-stack.
Launched task-3076489,  I'm sure that a lot of fonts files are not needed at all.

**Review by stefanorigano — APPROVED** [review]

**Review by d-fence — CHANGES_REQUESTED** [review]
I'm sorry.
After discussing with someone that prefer to stay in the shadow :sunglasses: ...
It seems preferable to keep the old  font files in the stable versions and remove them in master.

The explanation is that if someone pull the code but does not update its instance, the css will still point to the old fonts that does not exists anymore.

That's true, I was wrong, I apologize 🧎🏻‍♂️ for that

**Comment by Ngquang** [comment]
@d-fence Okay. Thanks for the information. @phamthuha0970 Will process this in master. 
@phamthuha0970 ping.

**Pull request closed without merging**
