### PR TITLE
[IMP] sale: improvement in payment reference

### PR DESCRIPTION
**Pull request by sza-odoo**
Task id: 1946656
Pad link : https://pad.odoo.com/p/r.bd5dea5d7936420481a575c627ddf8f8

### CODE REVIEW

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo r-

**Comment by JKE-be** [comment]
Please, amend your commit:

> `[XXX] <module>: <Description>`

**Comment by sza-odoo** [comment]
@JKE-be Commit message updated. Thanks

**Comment by JKE-be** [comment]
@robodoo r+

**Pull request closed without merging**
