### PR TITLE
[IMP] web: various small improvements to form view

### PR DESCRIPTION
**Pull request by ged-odoo**
This commit is a few small improvement/fixes to the web framework:

- allow placeholder attribute on input tags in form view
- only bind click event handler to buttons managed by the framework, not
  custom ones
- _onExecuteAction method in action manager properly fails if event
  cannot be properly handled

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
@qle-odoo in case you are interested

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo retry

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo do what i mean

**Comment by ged-odoo** [comment]
robodoo you suck

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
