### PR TITLE
Signed CLA

### PR DESCRIPTION
**Pull request by remi-filament**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `remi-filament@users.noreply.github.com`
- you are signing _for_ the address `r...@le-filament.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by remi-filament** [comment]
@mart-e 
Thank you for your feedback, it was a problem in my GitHub account, I have fixed it, but am not sure whether I need to make a new commit to have the checks to be run again against my public e-mail address ?

**Comment by mart-e** [comment]
You can just make another commit (e.g. adding a space) in the same branch `patch-2` if you don't want to use the command line.

**Comment by mart-e** [comment]
Thank you for the signature, it has been integrated into Odoo at revision 2904192ad660a633586dfe6e3c45c9c07afe09a5.
Future pull requests made on odoo will be validated by the runbot.
Regards

**Pull request closed without merging**
