### PR TITLE
[14.0][FIX] mrp: Set the state of the production correctly.

### PR DESCRIPTION
**Pull request by victoralmau**
**Description of the issue/feature this PR addresses**:

If the components of the manufacturing order are in done or cancel state you should NOT define the status of the manufacturing order as done.
It should only be set as done if components and finished moves are done/cancel.

**Impacted versions**:
- 14.0
- 15.0
 - master

Ping  @pedrobaeza 

cc @Tecnativa TT38551

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think they should be both as done: raw and finished moves.

**Comment by victoralmau** [comment]
> I think they should be both done: raw and finished moves.

Ok, changes done.

**Comment by pedrobaeza** [comment]
@amoyaux @Whenrow what do you think about this?

**Comment by pedrobaeza** [comment]
@amoyaux @Whenrow friendly reminder :pray:

**Comment by pedrobaeza** [comment]
Thank you very much!

**Comment by pedrobaeza** [comment]
There's an unrelated test error in `sale_product_matrix`. Let's wait if it's fixed.

**Comment by pedrobaeza** [comment]
@amoyaux with the last rebase, it's green. Can you r+ again, please?

**Comment by Whenrow** [comment]
robodoo r+

**Comment by pedrobaeza** [comment]
Thank you very much!

**Pull request closed without merging**
