### PR TITLE
[FIX] base: compatible with python 3.9

### PR DESCRIPTION
**Pull request by mart-e**
base64.encodestring is deprecated since python 3.1 and was removed in
python 3.9
Use the alias instead
https://docs.python.org/3.8/library/base64.html#base64.encodestring

Fixes odoo/odoo#80652

### CODE REVIEW

**Review by Julien00859 — APPROVED** [review]
Maybe we should backport https://github.com/odoo/odoo/commit/4f03a5f136ab928ae74322bf1c34a1b6a6baf979 entirely

**Comment by d-fence** [comment]
robodoo r+

**Comment by mart-e** [comment]
@robodoo r-
@d-fence actually it's probably not enough as there are other occurrences, wanted your opinion if we want to backport all the changes, like we did at 4f03a5f136ab928ae74322bf1c34a1b6a6baf979

**Comment by d-fence** [comment]
sorry I did not see any comment about other occurrences.

**Comment by d-fence** [comment]
From my POV,  4f03a5f can be backported as it should work in 3.5 (Debian Strech).

**Comment by d-fence** [comment]
robodoo r+

**Comment by d-fence** [comment]
robodoo rebase-ff

**Comment by d-fence** [comment]
@fw-bot up to 14.0

**Pull request closed without merging**
