### PR TITLE
Move purchase_ok from purchase module to product module

### PR DESCRIPTION
**Pull request by renatonlima**
Description of the issue/feature this PR addresses:

This PR fix the bug in this issues:
- https://github.com/odoo/odoo/issues/13268
- https://github.com/odoo/odoo/issues/315

### CODE REVIEW

**Comment by rvalyi** [comment]
I don't know why @renatonlima CLA check failed but he is part of Akretion and signed the CLA here: https://github.com/odoo/odoo/blob/9.0/doc/cla/corporate/akretion.md so tell us if we need to do something special.

**Comment by JKE-be** [comment]
@rvalyi 
The CLA trusts only `.com` email and not `.com.br`
So, or you will need to update your CLA or re-commit with renato.lima@akretion.com~~.br~~ 

thanks

**Comment by rvalyi** [comment]
@JKE-be all right, new push coming in a minute... BTW I approve my co-worker fix.

**Comment by JKE-be** [comment]
Thanks again for the PR, we decide to merge it in saas-12 finally... so I have back-ported your commit.
(I know that it changes the model, but because only our own DB is testing saas-12 and that it  will not impact the migration... It has been accepted)
https://github.com/odoo/odoo/commit/7a8516f

**Comment by renatonlima** [comment]
@JKE-be Done, I fix the problem in Odoo-cla

**Pull request closed without merging**
