### PR TITLE
[FIX] mail: do not fetch attachment style in QUnit tests

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2339931

### CODE REVIEW

**Review by xdu-odoo — COMMENTED** [review]
Kind of sad to add something explicit about testing in production code but I suppose we don't have the choice. By the way I see we use `env.disableAnimation` which I think is only set to false in tests so shouldn't we use `isQunitTests` for all those or use a more specific key to "disable" the attachment style ? (I prefer the second by the way)

**Comment by alexkuhn** [comment]
I'm pretty sure @seb-odoo doesn't like having a `env` prop that is explicitly set for test, that's why we have `disableAnimation` and `loadingBaseDelayDuration` (which are good, because more meaningful in name and their impact).

Here we make a server fetch from style, which is hardly mockable. Even more when style is added dynamically in JS.
It's sad to have to manage this in prod, but I don't think of a better solution that is very short and quickly deployable, while not being too ugly IMO.

**Comment by xdu-odoo** [comment]
Okay, fine for me then

**Review by xdu-odoo — APPROVED** [review]

**Comment by alexkuhn** [comment]
@robodoo r+

**Pull request closed without merging**
