### PR TITLE
[CLA] signed CLA for jasonribble

### PR DESCRIPTION
**Pull request by jasonribble**
Desired behavior after PR is merged: Sign the CLA to make more contribution 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jasonribble** [comment]
Howdy y'all! Looks like I didn't name my branch right. Is the target branch correct?

I tried to follow [CONTRIBUTING.md](https://github.com/odoo/odoo/blob/16.0/CONTRIBUTING.md) but later learned the more updated guide is on [odoo.com/documentation](https://www.odoo.com/documentation/16.0/contributing/development.html)

Looks like I'll make another commit updating CONTRIBUTING, if it is welcomed!

**Comment by mart-e** [comment]
Hello,

> Howdy y'all! Looks like I didn't name my branch right. Is the target branch correct?

Oh no that's fine, the branch naming guidelines [explained here](https://www.odoo.com/documentation/16.0/contributing/development.html#make-your-first-contribution) is mostly for our developpers. It helps for some CI magic and clarity but it's not mandatory.

> Looks like I'll make another commit updating CONTRIBUTING, if it is welcomed!

Right, maybe we need to update it to point to the documentation that is the official source of info.

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by jasonribble** [comment]
@mart-e Thank you so much for the clarification! As you can see I'm new to the Odoo code base, so seeing all of these closed PRs confused me.

It's not clear to me if my commit will be integrated into the source code. Will it be forwarded until it's accepted?

My apologizes for putting my other commit on a different PR

**Comment by jasonribble** [comment]
🥳 it is a good day. Thank you and you in the next PR!

**Pull request closed without merging**
