### PR TITLE
[FIX] web_editor: various shapes fixes

### PR DESCRIPTION
**Pull request by sdegueldre**
This commit fixes a number of shapes, usually the problems were with
imperfect joints between connecting shapes, shapes being cut not close
enough to the edge, or shapes using embedded PNGs for shadows instead of
using SVG filters.

### CODE REVIEW

**Comment by sdegueldre** [comment]
@qsm-odoo can you take a look when you have some time?

**Comment by qsm-odoo** [comment]
@sdegueldre I spoke with @JKE-be and @sbuhl, in fact we have to consider the 14.0 stable now, especially for this kind of change: the customer won't see an update for a year while its customers do. Let's do this:
- For pure fixes or very small change: ok to change the shape
- For shapes which are clearly not the same as before: duplicate it (add a version number in the name like we spoke about with AL), leave the old one in the repo and change the snippet option to use the new one
- For shapes which clearly change... but contained a fix too: ideally make the fix in the original shape and the change in a duplicated one.

Ideally two commits, one for fixes, one for imp.

**Comment by qsm-odoo** [comment]
Note: I know this was done before the release but it was just forgotten in the flood of fixes to merge, sorry :|

**Comment by sdegueldre** [comment]
@qsm-odoo made the requested changes. All changes in the first commit should have no major visual impact aside from fixing the transitions between sections, the second commit adds a copy of the two shapes where the visual impact is obvious and adds them to the shape selector instead of the originals. The originals appear unchanged and their color can still be configured if they were already in the page but you can no longer select them in the shape selector.

**Review by qsm-odoo — APPROVED** [review]
@robodoo rebase-ff r+

**Pull request closed without merging**
