### PR TITLE
[IMP] l10n_ar: Add the codes of the ND for FCE invoices that is necessary to show the bank account in the report.

### PR DESCRIPTION
**Pull request by nicomacr**
This way we show in the invoice and debit note FCE documents the bank account in the invoice report.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by jjscarafia — APPROVED** [review]
LGTM

**Comment by nicomacr** [comment]
@Bruno-Zanotti could you review this PR please?

**Comment by Bruno-Zanotti** [comment]
> @Bruno-Zanotti could you review this PR please?

@nicomacr this change was merge in Odoo a few days ago, here is the pr: https://github.com/odoo/odoo/pull/72708

**Comment by nicomacr** [comment]
> > @Bruno-Zanotti could you review this PR please?
> 
> @nicomacr this change was merge in Odoo a few days ago, here is the pr: #72708
Thanks @Bruno-Zanotti

**Pull request closed without merging**
