### PR TITLE
[FIX] resource: computation should be in UTC, representation in TZ aware

### PR DESCRIPTION
**Pull request by kebeclibre**
Berfore this commit, the number of hr.holidays days was incorrect when being in the timezone Asia/Jakarta.
This was because, the working limits of a workday were **hardcoded** as:
from midnight to noon in UTC
Whereas the hr.holidays were **converted** to UTC

Thus, we got:
holidays between 06:00 to 10:00 in UTC (which is 13:00 to 17:00 in Asia/Jakarta)
which falls within the *morning* interval, and was counted as non-working time

After this commit, the limit of workdays is converted to UTC before computing.
For our case:
Midnight in UTC **is** 17:00 the day before
etc...

OPW 788426

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by RomainLibert** [comment]
Yes it is done differently in master, basically when the leave is taken we keep the timezone of the employee directly on the resource.calendar.leave; which allows for conversions later on. Otherwise we use the same kind of conversion as in your function "from_tz_to_utc".

**Comment by kebeclibre** [comment]
@tde-banana-odoo 
@nim-odoo 
@RomainLibert 
My fix is on the right tracks, but tests on resource break.
Unless things have changed too much, backporting ff32384b8ffd1abc3ab4ba12114feddc32ba1bf9 seems a better solution than monkey patching

**Comment by RomainLibert** [comment]
The reason the tests fail is because in the fix you change the function 'get_working_intervals_of_day' so that it takes into account the timezones. And it seems that function is called in '_schedule_hours'. 
The solution may simply be to change the test so that it conforms to the bugfix (no sure if that's allowed in bugfixing, but would have to be done if backporting anyways)

**Comment by nim-odoo** [comment]
The resource calendar is known to struggle when handling timezones up to v10, and @tde-banana-odoo refactoring was necessary to get something clean:
> Currently timezones were not or incorrectly taken into account in resource computation.

To me, we shouldn't change this is in stable. This is a known limitation that is handled correctly in v11.

**Pull request closed without merging**
