### PR TITLE
[FIX] stock: use float comparison to assign moves

### LINKED ISSUE #32707: Some kind of rounding error causing Check Availability to fail
Impacted versions: 12.0

Steps to reproduce:
OK this took some time to replicate on runbot. Simple configs worked, so had to build out fully.
http://500789-12-0-77a241.runbot20.odoo.com/web?#id=389&action=392&active_id=135&model=stock.picking&view_type=form&menu_id=555 is the example picking

Create a product with a UoM precision of 0.001, MTO, Manufacture, Tracking Lots.
Create a Bill of Materials for it.
Create an SO for 22.400 of the product.
Manufacture the created manufacturing.
Go to the delivery and press check availability

Note while these seem very specific it was a direct replication of a single example. We have hundreds of these with different numbers and precisions failing. 

Current behavior:
Check availability never works because of a .000000000000000000002 difference. You can see this if opening the reserved move lines

Expected behavior:
Product reserves correctly.

Video/Screenshot link (optional):
image

OPW to follow

### LINKED ISSUE #32745: [12.0] Wrong float comparation when assign stock.move state
Impacted versions:
12.0

Steps to reproduce:
- Do a intenal move with [this lines](https://drive.google.com/file/d/1dz2bTj93GuhpbdGuJJstzJzgWgXXPgNW/view), all quantities is the same

Current behavior:
- The Stock Move has an state 'Partially available' when is completly reserved, caused by a wrong float comparation (e.g. 358.59 == 358.5900000000001).
 - code to fix:
https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move.py#L933

Expected behavior:
- [This line](https://drive.google.com/file/d/12xez6VNFaHHD2URRJKMGGUdZlJVdZtZ9/view) should be in state assigned

Video/Screenshot link (optional):
img 1: https://drive.google.com/file/d/12xez6VNFaHHD2URRJKMGGUdZlJVdZtZ9/view
img 2: https://drive.google.com/file/d/1dz2bTj93GuhpbdGuJJstzJzgWgXXPgNW/view

### PR DESCRIPTION
**Pull request by len-foss**
We remove the remaining comparisons to use the precision rounding of the UoM.

opw 1969888
closes #32707
closes #32745

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gdgellatly** [comment]
@len-odoo

It seems strange, because the line of code that seems to cause the issue is untouched in the PR.

This is our temporary fix

```python
class StockMove(models.Model):
    _inherit = "stock.move"

    def _update_reserved_quantity(self, *args, **kwargs):
        return float_round(
            super()._update_reserved_quantity(*args, **kwargs),
            precision_rounding=self.product_uom.rounding,
        )
```

**Comment by len-odoo** [comment]
@gdgellatly AFAICT, the `_update_reserved_quantity` method of `'stock.move'` is only called in `_action_assign`. Since then this fix makes all comparisons on the return value go by `float_compare` with the right rounding, this should have essentially the same effect as your temporary fix (except we don't modify the value).

I wonder though, is it mostly unrelated to the code and only a display issue? 
Because in the view there is 
`decoration-danger="not is_done and reserved_availability &lt; product_uom_qty`
which is obviously never gonna work _unless_ we change the value. Which your fix does.

**Comment by gdgellatly** [comment]
@len-odoo to be honest I never looked at the screen (except when it was wrong). The reserved qty always displayed right on the stock move, wrong on the stock_move_line

I just deployed the fix then ran a shell script something like
```
p = env['stock.picking'].search(<some state clause, confirmed/waiting I think>).filtered(lambda s: all(s.move_ids.mapped('reserved_qty'))
len(p) # say 410
p.do_unreserve()
p.action_assign()
env.cr.commit()
p = env['stock.picking'].search(<some state clause>).filtered(lambda s: all(s.move_ids.mapped('reserved_qty'))
len(p) # 3
```

and moved on to the next problem. Never looked back.

**Comment by len-odoo** [comment]
Thank you Simon.
robodoo r+

**Pull request closed without merging**
