### PR TITLE
[REF] sql_db: User parse_dsn from psycopg

### PR DESCRIPTION
**Pull request by moylop260**
Description of the issue/feature this PR addresses:
Version 8.0 supports dsn with:
`my_database_name options="my_option"`

But version >=9.0 don't supports dsn, because is pre-processed manually.
More info about: https://github.com/odoo/odoo/commit/26a8b438b6cc94241354af9fe218d8c592e17cfa

Current behavior before PR:
If I want use allow_uri=True and send valid uri "dbname options='my_option'" so the method returns:
```python
{
    'dbname': "dbname options=my_option",
}
```

Desired behavior after PR is merged:
```python
{
    'dbname': "dbname",
    'options': "my_option",
}
```

The new version of psycopg library supports [parse_dsn method](http://initd.org/psycopg/docs/extensions.html#psycopg2.extensions.parse_dsn)

You can see a example working:

 - screen shot 2017-07-06 at 01 01 10

Some times is require use `options` a practical example is to enable psql logger in order to parser pgbadger using the module profiler: https://github.com/OCA/server-tools/blob/8.0/profiler/controllers/main.py#L30-L37

### CODE REVIEW

**Comment by moylop260** [comment]
@xmo-odoo @mart-e @odony What do you think use psycopg library to parse dsn?

**Comment by moylop260** [comment]
FYI the red runbot result is because requires use the current psycopg>=2.7 defined recently by @odony from requirements commit: https://github.com/odoo/odoo/commit/6f8efea28cd29fd973ac6a50d7b93f0d73a725c6

**Comment by odony** [comment]
It's not a bad idea, unfortunately this feature requires psycopg2 and Debian 9 only includes 2.6.2, so we can't put a hard dependency on it yet. It's OK in `requirements.txt` for pip-based install, but not for .deb packages. We'd have to wait until Debian 10 to support this.

**Comment by xmo-odoo** [comment]
That seems like a trashy hack to reintroduce something which worked by coincidence previously?

If we want to support arbitrary pg options, wouldn't it make more sense to e.g. add all `pg_` configuration options to the info map? Or we can basically reintroduce the old crap by passing "dbname" (with old prefix) positionally/as `dsn` and still passing the rest by keyword:

> The connection parameters can be specified as a libpq connection string using the dsn parameter or using a set of keyword arguments or using a mix of both: if the same parameter name is specified in both sources, the kwargs value will have precedence over the dsn value.

**Comment by moylop260** [comment]
Thanks for reply

For odoo v8 we have a feature to enable psql logging from `options` psycopg client parameters to get a pgbadger report plus python profiler report:

 - [IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=oPFpLjTFWZs)

This worked fine and is helpful to catch a performance issue.

But I'm a little lost for >=v9 because I can't use `dsn` 😢

**Pull request closed without merging**
