### PR TITLE
[REF] Change the check_indexes function by adding a new index method brin, added multi-column indexes (where clauses). Added  re-index function.

### PR DESCRIPTION
**Pull request by rosenvladimirov**
Description of the issue/feature this PR addresses: Change the check_indexes function by adding a new index method, brin. brin is a low-cost index suitable for large databases. It is effective for update, delete, and cascade operations. Added auto create for brin indexes for many2one fields. Include additional indexes for the translated field to optimize search for the currently used language only. Define index_keys in the field for creating multi-column indexes to enhance the speed of clauses. 

Current behavior before PR: Missing engine for create more types of indexes.

Desired behavior after PR is merged: To speed database operation in very large bases.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kmagusiak** [comment]
Hello

I'm not ok with this design. You declare a multi-column index on a single field.
In the coming months, I had in mind to rework `_sql_constrains` to be able to specify easily multi-column and where-constrained indexes.
Also, this will not be done in the stable release.

**Comment by rosenvladimirov** [comment]
Hello @kmagusiak ,
The idea is: where you construct the where clause in sql query, all the time you use searching in the first field, like base, and after you add other fields (product_id, location_id;product_id, lot_id, location_id), in fact, all the time you start from a single field. For _sql_constrains this is a bad idea; the constraint is used for creating special indexes. I prepare an example in stock_query. I install [Powa](https://powa.readthedocs.io/en/latest/) on a very big database to annalist sql queries in odoo 11.0 (base not difference in queries, only 17.0 start to work with multi records, this is correct way, but not very big profit without indexing) and constructor for where clause every time starts with base field (example product_id). The new engine in 17.0 for batch queries is linked directly with indexing the speed (update and drop); there is a configuration to use 1000 per batch, My experience with big queries in odoo is that 15 records per query is the best solution. For the multi-server solution, when you start many parallel (not multi-threaded) background processes, PostgreSQL crashes with memory leak. The current engine is ok for small batches below 1000, but this does not work with MOMP with more from 10k records. At moment the odoo very slow, with big databases with more than 1 million records, missing indexes for many where clauses, and the need to prepare manuals. 
P.S. need to prepare multi-indeses by any way and engine, this code is my solution, maybe has other better

**Comment by rosenvladimirov** [comment]
On the first part, when you start to populate records in stock_quant with sql query, there are fields with relation to other tables, for example, stock_lot where for connection, use ID field (for the integer field, it is better to use the brin index). The company produces a lot of devices with unique serial numbers, more than 1 million for 2-3 years; in this case, you have 1 million+ records in stock.lot. When you start to update the stock_quant you have cascade dropping or searching in related tables. When you analyze this query in PostgreSQL, I see time losses in this part of the execution of the query. When i add the multi-index product_id,lot_id,location_id, the query executes faster. If all is packaged, the situation stays very critical.
On second, not all processes in manufacturing are used by people; some processes use machines, for example, PnP when a manufacturing order for a machine has many components for consumption, and the process for closing a single final product goes to background. The machine is very faster and produces one final product for 5-10 seconds and consumes more 10k components. In this situation, it is impossible to use the current basic way of installing one server on a single machine. To work on-line need more servers on different machines to free servers for the front-end. When start multi-tread queries need to free PostgreSQL for other processes, for example, when execute 2 queries with 1000+ records from 2 PnP machines every 5-10 seconds, the server blocks totally and breaks with a memory leak.
About your code: We have two sides to the problem: one indexing for searching and the other for related tables, This solution is not coverage relation tables; there needs to be automatic creation of indexes (I prefer the brin indexes) for fields for relations.
Other you mix conception one side use field name base creating indexes and now add manual part of construction of clauses for index. In this case, it is possible to mix conception, but it is not very clear.

**Comment by rosenvladimirov** [comment]
Current code and my offer. My idea at moment do not add configuration for index_key in code, only filed index_keys in ir.model.fields and with small [module](https://github.com/rosenvladimirov/server-tools/tree/17.0/module_reindex) to re-create index and add learning part linked with [Powa](https://powa.readthedocs.io/en/latest/)
To hard to in all models `create_index(self._cr, 'sale_order_date_order_id_idx', 'sale_order', ["date_order desc", "id desc"])`

**Comment by kmagusiak** [comment]
I'll check with a colleague about the performance on huge numbers of records in serial numbers.
As for the indexes, the framework should provide tools to manage them and we should improve the management of indexes (already in our backlog). As a software vendor, we try to find the best compromise for creating indexes (too few and selects are slow, too much and updates are slow). There were more indexes created in the past, but that resulted in other performance issues. If you have a huge database, you can create additional indexes (even manually in the database) if you have specific queries on big tables.

**Comment by rosenvladimirov** [comment]
For framework, I follow the same rules. In this fix, I offer minimal correction for backporting and open the door to create manual indexes by program. The changes in stock_quant.py are only an example of hardcore included changes with indexes.
Base in fix with new arraignment of code for index create; and added re-index function; and new field index_keys in ir.model.fields.
I will make a monkey patch to fix this problem in my instances, but I found a lot of problems in other modules like accounting and stock, and this is not a good idea from my side to prepare for every version of the new monkey patch.
Thanks for the discussion from your side, i will be very happy if code move in this side optimization of multi-indexes.

**Pull request closed without merging**
