### PR TITLE
[FIX] l10n_nz: made GST taxes more user friendly

### PR DESCRIPTION
**Pull request by ArnaudVerlaine**
Makes the tax more intuitive for the user

Backport of PR #103648
Task-2993525

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gdgellatly** [comment]
@ArnaudVerlaine are you really sure about this? It look like it will break NZ taxes. The reason the number is so high as that we need to make the price_unit diminish to 0.0 and have 100% of the line value go to GST. In the past setting at 100% would only have 50% go. It would be nice to see a test proving that, otherwise this just looks like breaking what worked well.

**Comment by jco-odoo** [comment]
@gdgellatly We also change the type to division.

**Comment by gdgellatly** [comment]
@jco-odoo Thanks for the fast reply. Guess we'll find out soon enough. Easy to change anyway, but if it works, I agree it will be much nicer than current workaround.

**Comment by jco-odoo** [comment]
@ArnaudVerlaine It is a bit tricky to change the xml_id of the tax group in stable, because maybe people have already installed a localization. Would you mind just keeping the old one here and change it in master?  (should not take long)

**Comment by ArnaudVerlaine** [comment]
Sure! The change is already in master

**Comment by jco-odoo** [comment]
@fw-bot ignore

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
