### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by AurelienPillevesse**
Fix some translations

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thanks for the contribution but please check [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://transifex.com/odoo), not Github.

Please submit your changes there and let me know if you have issues.

Thanks

**Comment by AurelienPillevesse** [comment]
@mart-e I didn't see it so thanks, but on your software we can't see if a space is missing on french language for example instead of in .po file. Can you do something?
If spaces are missing, titles on french are not great...

**Comment by mart-e** [comment]
On our software, you mean Odoo or Transifex ?
On Transifex, you can enable an option to display spaces (on the "Editor Preferences" in the top right menu)
Screenshot_2019-07-26 Odoo 12 0 Transifex Editor

I just corrected the " and " translation to show you
https://www.transifex.com/odoo/odoo-12/translate/#fr/web/151516804?q=text%3Aand

Or am I misunderstanding the problem?

**Comment by AurelienPillevesse** [comment]
That's perfect thanks, if i want that the change goes to all branches, 11/12/master, i have to the change to each one or just master?

**Comment by mart-e** [comment]
Changing in all branches would be perfect :+1: 
If a term has never been translated, the translation will propagate to the different resources and versions but not if a translation already exists.

**Comment by mart-e** [comment]
If you are comfortable with the command line and git, you can use the Transifex Client to pull and push changes without accessing the web interface (if not the web interface will work just fine too)
https://github.com/odoo/odoo/wiki/Translations#can-i-use-my-own-translation-software

**Pull request closed without merging**
