### PR TITLE
[FIX] portal: show emails in portal chatter

### PR DESCRIPTION
**Pull request by Julien00859**
Create a quotation and send an email to the customer, let the customer
reply by email, as a portal user go on the portal view of that
quotation, he does not see the emails.

### CODE REVIEW

**Comment by jem-odoo** [comment]
\cc @tde-banana-odoo Whydid we allow only comment to be displayed on portal in the first place ? ^^"

**Comment by tde-banana-odoo** [comment]
Why not ?

**Comment by Julien00859** [comment]
@jem-odoo ping :stuck_out_tongue:

**Comment by jem-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
