### PR TITLE
[FIX] base: rename res.partner.vat uppercased index

### PR DESCRIPTION
**Pull request by yajo**
This custom index name matches the name that Odoo uses for automatic indexes (when a field has `index=True`): https://github.com/odoo/odoo/blob/836ff55dc9f473a61f0c50c15fb5468d75959a83/odoo/fields.py#L978

The `vat` field itself is created with `index=False`: https://github.com/odoo/odoo/blob/836ff55dc9f473a61f0c50c15fb5468d75959a83/odoo/addons/base/models/res_partner.py#L164

This means that Odoo will execute a `DROP INDEX IF EXISTS res_partner_vat_index` when updating any addon that touches the `res.partner` model: https://github.com/odoo/odoo/blob/836ff55dc9f473a61f0c50c15fb5468d75959a83/odoo/fields.py#L979-L986

Since this model is so ubiquitous, this results in a ton of unnecessary `DROP INDEX` + `CREATE INDEX` queries when updating any database.

What's even worse is that dropping or creating an index needs a complete semaphore lock of the whole table, so if you're updating a hihg-traffic HA production instance while it is running, you have a very high rate of concurrency failures, because almost everybody is going to be using the `res.partner` model in some way almost all the time. In our case, the database has 24000 partners, which complicates things.

Just to prove this point, if you just install `stock` in an empty demo database and then run `-u base`:

- Before this patch, you drop and recreate this index 12 times (which, remember, means locking the whole `res_partner` table 12 times).
- After this patch, the 1st time you update, you run `DROP INDEX IF EXISTS "res_partner_vat_index"` 12 times also, although only the 1st time you actually drop the index (next times the index won't exist, so the statement will do nothing). Also, you only run `CREATE INDEX res_partner_vat__upper_index` once. This means 2 table locks.
- After this patch, the next time you update, no indexes will be dropped nor created. No table locks.

The new index name finishes with `index_`, so it's impossible to collide with any automated index preexisting in the database (even if somebody added a `vat_uppercase` field downstream with `index=True`).

@Tecnativa TT26303

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@odony can you please check this?

**Comment by odony** [comment]
Nice catch! Those repeated index creations/deletions are useless and can definitely cause issues during updates 👍

Besides, it seems the index itself is useless. It was added in a6e1eb9f0ad285fac7d0ca0b9f89f046d78ec9c7 and apparently meant to be used for optimizing `name_search()`. But the only way for PosgtreSQL to use it would be if a query had an equivalent `regexp_replace(vat)` clause. And even though a6e1eb9f0ad285fac7d0ca0b9f89f046d78ec9c7 modified `name_search()`, it did the substitution in Python: https://github.com/odoo/odoo/blob/a6e1eb9f0ad285fac7d0ca0b9f89f046d78ec9c7/odoo/addons/base/models/res_partner.py#L710

So the database can't know about it and cannot use the index, even when the _operator_ is compatible:
```sql
12j=# explain select * from res_partner where vat = 'foo';
                          QUERY PLAN                          
--------------------------------------------------------------
 Seq Scan on res_partner  (cost=0.00..10.50 rows=1 width=643)
   Filter: ((vat)::text = 'foo'::text)
(2 rows)

12j=# explain select * from res_partner where regexp_replace(upper(vat), '[^A-Z0-9]+', '', 'g') = 'foo';
                                                QUERY PLAN                                                 
-----------------------------------------------------------------------------------------------------------
 Index Scan using res_partner_vat_index on res_partner  (cost=0.14..8.16 rows=1 width=643)
   Index Cond: (regexp_replace(upper((vat)::text), '[^A-Z0-9]+'::text, ''::text, 'g'::text) = 'foo'::text)
(2 rows)
```

I can't seem to find any piece of standard code that would use the index, so I suggest we drop the entire `init()` override, and don't bother trying to fix the original thing.

We could even consider switching `index=True` on the `vat` field instead, as that would provide a good generic fallback. The VAT field is a pretty common thing to search on, so it's worth it, independently of the `name_search()` itself (which would benefit most from a composite index - probably out of scope here).


PS: you can check how often indexes are used using the following query. The stats for the problematic index will be reset each time it's dropped, but having 0 idx_scan on an active production database is a significant clue that an index is unused:
```sql
SELECT indexrelid::regclass as index, idx_scan
  FROM pg_stat_user_indexes JOIN pg_index USING (indexrelid)
 WHERE relid::regclass::text = 'res_partner';
```

**Comment by Yajo** [comment]
Thanks for the good investigation and explanation @odony. Indeed that's a better solution, it's uploaded already.

**Comment by odony** [comment]
Thanks for the upate! I wanted to test the upgrade script and ended up rebasing, squashing and updating the commit message, so it's ready to merge. But it doesn't look like I can push on your PR branch (cfr [the option](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)). So I pushed that a separate PR, with same authorship: #60476

**Comment by Yajo** [comment]
Humm sorry I don't have that option, I don't know why... :confused: 

Anyways thank you very much :heart: . Closing this one.

**Pull request closed without merging**
