### PR TITLE
[IMP] im_livechat,*: introduce LivechatButtonView/isWebsiteLivechatChatbotFlow

### PR DESCRIPTION
**Pull request by alexkuhn**
*: website_livechat

Task-2888374

### CODE REVIEW

**Review by oomsveta — COMMENTED** [review]
where does `isWebsiteLivechatChatbotFlow` come from and where is it used?

**Comment by alexkuhn** [comment]
> where does `isWebsiteLivechatChatbotFlow` come from and where is it used?

This is a new concept to cover this precise overwrite, in this precise file.
This is useful for this PR:
https://github.com/odoo/odoo/pull/94037
Which introduced a field that can become declarative with `isWebsiteLivechatChatbotFlow` here.

**Review by oomsveta — APPROVED** [review]
need rebase

**Comment by alexkuhn** [comment]
Merged in grouped PR: https://github.com/odoo/odoo/pull/94190

**Pull request closed without merging**
