### PR TITLE
[FIX] point_of_sale: account.tax write permission #3632037

### PR DESCRIPTION
**Pull request by acsonefho**
Support ticket number: #3632037

On Odoo v14.0

**Description of the issue/feature this PR addresses:**
When a user try to import (to edit) some `account.tax`, some verification are done on `pos.order.line`.
The search is done in `sudo` but the read is executed with the current logged user. So `pos.order.line` from others companies are check with a user who don't have access to these companies. And the `AccessError` exception is triggered.
This PR aims to fix the permission issue by adding a `sudo()` for the read on `pos.order.line`.

**How to reproduce:**
- Multi-company environment (2 is enough);
- POS available on at least 2 companies;
- Open a session and do some POS (with lines of course) on company 1 (do not close the session);
- Open a session and do some POS (with lines of course) on company 2 (do not close the session);
- Then do an import of some account.tax (to maybe rename them);
- You should have the AccessError exception (about multi-company).

**Current behavior before PR:**
During the import (update) on `account.tax`, some verification are done to ensure no open session are related.
In case of multi-company, we have an `AccessError`.

**Desired behavior after PR is merged:**
The verification should be done in `sudo()` as the search is `done` in `sudo()`.

This bug has been introduced by: https://github.com/odoo/odoo/commit/0d220a7b42c8675b53a59779496953e2a70343a4

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
Kindly fix the commit title so that ci/style will pass. Based on your commit title, it should be:

```
[FIX] point_of_sale: account.tax write permission
```

**Comment by caburj** [comment]
Hi @acsonefho. You'll need to change the title in the commit itself, not of the PR. The CI/style is looking at it that's why it's red.

**Review by caburj — APPROVED** [review]
robodoo r+

**Comment by william-andre** [comment]
@robodoo retry

**Pull request closed without merging**
