### PR TITLE
[FIX] Method get_access_action should not be executed as sudo

### PR DESCRIPTION
**Pull request by SimoRubi**
Method get_access_action should be executed as the user in the request, otherwise it could lead to error pages (such as Access denied), or produce the behaviour described below.
 
I made this change because in module website_project_issue, the overridden method `get_access_action` checks if the current user is in the `share` group (i.e. is not an employee). 
Since `get_access_action` was executed as sudo, and Administrator was an employee, the customer is redirected to backend instead of website.

Description of the issue/feature this PR addresses:

Current behavior before PR:
Customers receiving emails with button 'View issue' (link to /mail/view/message_id=) are redirected to backend instead of website

Desired behavior after PR is merged:
Customers receiving emails with button 'View issue' (link to /mail/view/message_id=) are redirected to website

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by SimoRubi** [comment]
@tde-banana-odoo any news on this?

**Comment by tde-banana-odoo** [comment]
Hello,

I know this method causes issues in 10. It has been changed since then and it is better implemented in current 11.0 and master versions, separating user executing the action and the target user. @nim-odoo fixed the issue with tasks and issues in 10 at https://github.com/odoo/odoo/commit/4c692f1bb31766840ca3eca6a8e0faebd34cda1a . I think it solves the failing use cases. In my opinion it is better not to change that code in stable version. What do you think about that ?

Best regards,

**Comment by SimoRubi** [comment]
Hi @tde-banana-odoo, I'm glad to know the implementation has been improved in v11.

In my humble opinion, I think the behaviour here should be changed a little: executing `get_access_action` as `sudo` is confusing for models overriding `get_access_action` method.
With the change I proposed, the fix in https://github.com/odoo/odoo/commit/4c692f1bb31766840ca3eca6a8e0faebd34cda1a isn't required, but I can't think to other use cases where it would break something so if you have anything in mind please let me know.
Little summary of what happens in this method: a **user** wants to access a record, so we do the following steps:
1. Look for the record: since **user** is looking for the record, why should we look for the record as sudo? From the **user**'s point of view, nothing should change if the record exists but can't be accessed or doesn't exist at all;
2. Decide what happens when **user** looks for the record (method `get_access_action`): I would do this with that same **user**;
3. Check if **user** can read the record, and execute the action found in 2.

If the overriding `get_access_action` methods then want to use `sudo`, they can do that in their own implementation.

This is what I think of this right now, let me know if you have any advice.
Thanks

**Comment by yelizariev** [comment]
Time to close it :)
v10,v11 are not supported and apparently newer versions don't have this problem
https://github.com/odoo/odoo/commit/7dd6225f0bbee29f4a138633edd0c16298743518

**Comment by SimoRubi** [comment]
> Time to close it :)
> v10,v11 are not supported anymore and apparently newer versions don't have this problem
> [7dd6225](https://github.com/odoo/odoo/commit/7dd6225f0bbee29f4a138633edd0c16298743518)

Thanks I just tried in v12 and the issue is fixed

**Pull request closed without merging**
