### PR TITLE
[IMP] account, analytic: various analytic accounting improvements

### PR DESCRIPTION
**Pull request by jorenvo**
Apart from various small analytic accounting improvements the main 3 features this provides are:

- Analytic account hierarchies
This can be used to organize accounts. A visualization of this hierarchy will be implemented in a financial report.

- Analytic distributions
These allow multiple analytic entries to be generated for a single cost based on a percentage.

- Grid view on analytic entries

Internal task: https://pad.odoo.com/p/r.44b9fdb7001d84fa646c061df4e7680e
Task: https://www.odoo.com/web?debug#id=32386&action=333&active_id=967&model=project.task&view_type=form&cids=3&menu_id=4720

### CODE REVIEW

**Comment by danger89** [comment]
Ow Ow run Bot fails..

**Comment by qdp-odoo** [comment]
@Gorash unfortunately, the m2m tags widget in stand alone does have some issues:
- impossible to delete one item once added to the field
- if a record is created from the widget, it appears as an empty tag (no visible name)

can you check?

**Comment by Gorash** [comment]
@qdp-odoo I add a fix in your branch

**Comment by qdp-odoo** [comment]
landed in master, for saas11.2, at revision https://github.com/odoo/odoo/commit/079a13a349c942ab69ca704263bc5cb52c391d92

**Comment by jeffery9** [comment]
the amount seemed wrong. #27300

**Pull request closed without merging**
