### PR TITLE
[IMP] *: introduce data-hotkey

### PR DESCRIPTION
**Pull request by kbapt**
Define `data-hotkey` on most used action buttons.

TaskID: 2588233

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kba-odoo** [comment]
@JKE-be Alt+Z is dedicated for the `cancel` buttons and Alt+Q for the first primary action across modals :-)

**Comment by kba-odoo** [comment]
@robodoo r+

**Comment by william-andre** [comment]
Is there a guide somewhere for how to assign/choose keybinds to new buttons?
Like the rationale between the choices made here?

**Comment by kba-odoo** [comment]
You can check this google spreadsheet: https://docs.google.com/spreadsheets/d/1QIPwUiEDv37H1P_FjN-WctzPey2Niu6K5dCL157Z8BY/edit#gid=323054012

Otherwise I think it would be best to check with NGR :-)

**Pull request closed without merging**
