### PR TITLE
[FIX] stock_landed_costs: do not prorate

### PR DESCRIPTION
**Pull request by nim-odoo**
opw-1878229

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
ping @sle-odoo thanks

**Comment by nim-odoo** [comment]
I don't think so. First, be aware that I am only changing the amount which was prorated based on the remaining quantity. If the issue you mention appears, I don't think the fix would change anything about it. Before the fix, we would add a prorated amount multiple times; after the fix, we would add the full amount multiple times.

Then, the action is only called once at landed cost validation. So it only applies to the landed cost being validated. The previous validated landed costs are already included in `value` and `price_unit`.

The use case described specifically uses two landed costs.

Or maybe do you have another specific use case in mind?

**Comment by AlHafez** [comment]
Good morning, nimo,
I am the one who posted the ticket as a bug.
First , I noted that you corrected line 105 :
cost_to_add = (line.move_id.remaining_qty / line.move_id.product_qty) * line.additional_landed_cost
Thenafter some days, you brought back the original code line 105, and instead you corrected code lines 110&112.
since am pre-junior at github,( & i want to test the corrections at my server) please clarify to me:
1* whether there will be a correction at line 105, or not ?
2* correction will only touch lines 110 & 112 ?
& when would you normally expect those changes to be at distributed Odoo Enterprise code, version 12? or till v13?
thanks for attention

PS: your corrections seems fine, and you corrected field 'value' too which used to wrong too in case of late landed cost i.e. receive goods, sell, then validate a landed cost .

**Comment by nim-odoo** [comment]
@AlHafez The change which should be applied is the current one, on lines 110 and 112. It will be merged in v11 (and v12) as soon as @sle-odoo can review it.

**Comment by Arvinman** [comment]
Nevermind, look like I can use account_move_ids in stock_move to get more accurate amount.

Regards,

**Pull request merged**
