### PR TITLE
[FIX] base: avoid useless logging during every registry reload

### LINKED ISSUE #36851: [core] Over spammig of a log for non-stored depends
**Impacted versions:** v11 and above. **Detected in** v12.

**Steps to reproduce/Current behavior:**

By seeing the travis-ci compilation in OCA, the logging shows:

when loading `stock`:
Selection_078

later, when loading or recomputing in following modules:
Selection_079
Selection_080
Selection_081
Selection_082
Selection_083

And so on. Finally, travis-ci shows:
`The job exceeded the maximum log length, and has been terminated.`

**Expected behavior:** The previous lines are not repeated _in crescendo_.

**CAUSE OF THE ERROR:** The https://github.com/odoo/odoo/commit/96266bfe547834e98f933e156c7e96a66b182095 + https://github.com/odoo/odoo/commit/32ca79940b1608495cb08c2272add5216685af71 commits caused the error.

### PR DESCRIPTION
**Pull request by Elkasitu**
Fixes #36851

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But the inner problem is there, isn't it? The logging is useful for catching it, so I think it should be preserved (maybe in other level where it only outputs once), and the real problem is in the fields that trigger this.

**Comment by Icallhimtest** [comment]
@pedrobaeza There are valid cases where a field depends on a non-stored field, I don't immediately see when this could cause a problem. Should there be one, the logging should be fine-tuned to those cases and perhaps be of a higher level of logging (warning/error). But this log is clearly too generic, and spams the logs upon module installation/upgrade.

**Comment by gdgellatly** [comment]
Lol this commit alone will reduce my travis output 90 percent. Stock modules massively depend on this behavior. The only suitable alternative level is lower not higher. E.g debug

**Comment by pedrobaeza** [comment]
OK, this seems better to have it as debug. Thanks.

**Comment by Icallhimtest** [comment]
I can't say I agree.

To me, we should either just log the particular cases where this behaviour is problematic (probably with higher level) or log nothing at all.

I don't see why we'd want to spam the people using Odoo in debug with tons of needless logs for a behaviour that is accepted (and in the standard stock module).

Nevertheless, either solution solves my problem so you won't be hearing me complain.

**Comment by pedrobaeza** [comment]
Can be frequency of the message be changed for not being logged each time the registry is reloaded and be only shown once? If so, better to leave it as info, but not spamming.

**Pull request closed without merging**
