### PR TITLE
[IMP] web: reduce jquery-ui lib (remove useless modules)

### PR DESCRIPTION
**Pull request by pparidans**
Includes: widget.js, position.js, data.js, keycode.js, scroll-parent.js,
unique-id.js, widgets/draggable.js, widgets/droppable.js,
widgets/sortable.js, widgets/autocomplete.js, widgets/menu.js,
widgets/mouse.js

task-3439226

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by adr-odoo — APPROVED** [review]
@robodoo r+

**Comment by pparidans** [comment]
@robodoo rebase-ff

**Comment by pparidans** [comment]
@adr-odoo rebase-ff

**Comment by rfr-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
