### PR TITLE
[FIX] models: avoid error in _check_company if record doesn't have a company

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

Sometimes the `company_id` in a model is not `required`. Thus, you may have/want records with `company_id = False`. But `_check_company` method always require the record to have a company.

**Current behavior before PR:**

- The '`if not company`' is to avoid this error (see added test).

- The '`corecord._name != self._name`' part is (as an example) to still force the company in a sublocation if the parent location has company.

**Desired behavior after PR is merged:**

Avoid error explained above.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sle-odoo** [comment]
> But _check_company method always require the record to have a company.

It doesn't because ```corecord.company_id <= company``` handles this properly, an empty recordset at the left will make the expression truthy

```
In [1]: self.env['res.company'] <= self.env['res.company'].browse(1)
Out[1]: True
```

So i really don't get the issue here? we have lots of cases in standard where company_id is not required (eg product.product) and afaik it is working properly.

**Comment by MiquelRForgeFlow** [comment]
I think your example and mine are different. The comparison in https://github.com/odoo/odoo/blob/13.0/odoo/models.py#L3160 is `elif not (corecord.company_id <= company):`, which in my example is  `self.env['res.company'].browse(1) <= self.env['res.company']`, which is False.

**Comment by sle-odoo** [comment]
can you show me a problematic usecase in standard?

**Comment by MiquelRForgeFlow** [comment]
Well, a bit difficult to give you several examples because there are so few models with `_check_company_auto = True`.

But let's put an easy one:
(Suppose the field `company_id` of `product.pricelist.item` is `readonly=False`)
1- Begin with creating a `product.template` P with company_id = C.
2- Create a pricelist with company_id = C.
3- Create a pricelist item with company_id = C, with Apply on product, and product_id = P.
4- Save, but then edit the pricelist and go to the pricelist item and put company_id = False.
The error is shown.

Obviously you may say that's wrong because `company_id` of `product.pricelist.item` is `readonly=True`, and yes, it's just a way to showcase the error I am trying to explain. Also note that in this example (and using `readonly=True`), I could still say that then you still could edit the company of the pricelist, doing `company_id = False`, and you still will have a pricelist item without company and product_id with a company (just happens that doing this way the `_check_company` method is not executed, because two reasons: `product.pricelist` doesn't have `_check_company_auto = True` and also because the `_check_company` doesn't execute yet on company related records, so it won't trigger on `product.pricelist.item` model).

**Comment by sle-odoo** [comment]
thanks for the explanation but still i'm not sure i get the idea yet
maybe you could add the failing usecase [here](https://github.com/odoo/odoo/commit/504b5fe5a9613bb836bd865475c4b17713b78864#diff-51be8c45df7b2ef0976509f90a12bf3eR663) ( read test_company_check_xxx) and then we'll review the fix

**Comment by MiquelRForgeFlow** [comment]
@sle-odoo haha, with the added test, I think it's more easy to understand the issue. Too much explanation wasted 🤦‍♂️

**Comment by sle-odoo** [comment]
The `product.pricelist` use case doesn't work by the way, since `company_id` on the item is related to its parent price list.

``` python
    company_id = fields.Many2one(
        'res.company', 'Company',
        readonly=True, related='pricelist_id.company_id', store=True)
```

But let's say it works for the sake of the argument (or let's talk about your testcase): don't you think it's a bad design to have children records not belonging to the company of the parent, if indeed the parent has one? I can imagine the other way around, a parent shared across companies (so no company set) and children records specific to companies (so having a company_id set)[0]. 

What would be a practical use case to share a child record across companies, but not its parent?

[0] It's actually the case with some stock.location.route and stock.rule record (mto route without company, one rule per company)

**Comment by MiquelRForgeFlow** [comment]
> don't you think it's a bad design to have children records not belonging to the company of the parent, if indeed the parent has one?

Well, the test is naming them child and parent, but they technically are not parent and child. They are different models, not a same model. Just the existence of a many2one relation between them doesn't mean that they are model parent and model child 🤔 Odoo has a lot of weird many2one relations between different models.

But in case both are the same model, then it's okay all you said, they are both parent and child, and thus that's why I added the `corecord._name != self._name` in the fix.

**Comment by sle-odoo** [comment]
yeah well i really don't get what you're trying to accomplish, you want to link recA compA with recB companyB, both in different companies but you still want the check_company to work on the m2o and do something useful?

ping @rco-odoo @Feyensv

**Comment by C3POdoo** [comment]
Dear @MiquelRForgeFlow,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
