### PR TITLE
[FIX] account: payment (domestic) of invoice (foreign) currency

### PR DESCRIPTION
**Pull request by kebeclibre**
Make an invoice in a foreign currency
Add a tax on a line
eg: line price = 500; tax: 5%; invoice total = 525
Have a exchange rate of 19 between the domestic and foreign currencies
Push on register a payment, and change the currency of the payment
to the domestic currency

Due to the rounding of the different parts of that price
We end up with
525/19 = 27.63
If we take the invoice residual amount in its currency
BUT
500/19 = 26.32 + 25/19 = 1.32 = 27.64
If we take what is computed in the journal entry

Before this commit, the payment wizard computed 27.63
for the amount, signaling there were no difference
hence, that the invoice will be fully paid
However, when validating, the payment, the 0.01 difference
was actually computed as residual

After this commit, when a payment takes place in
the invoice's company's currency, we take the relevant
residual_company_signed field for the computation
which takes those -- justified -- rounding errors
into account

OPW 2053301
related to #35334

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Hello @kebeclibre  
I tried your fix on http://592006-12-0-pay-currencies-lpe-b3785d.runbot19.odoo.com/web?debug=1#id=203&action=508&model=account.invoice&view_type=form&menu_id=327 and it seems working well for the Issue However,

When Paying 27.64 in Foreign currency 
screenshot-592006-12-0-pay-currencies-lpe-b3785d runbot19 odoo com-2019 08 17-18-13-15





Adding Manually JE with the Same values still generates same rounding Issue. (Not sure If we can do something about that)

**Comment by kebeclibre** [comment]
@sswapnesh 
Well.... I think my fix is wrong anyways. Why ?
Because the only amount that is contractually correct is the one on the invoice, no matter how it translated at **one point** in some other currency, be it the currency of the company.
What should be done to make it correct is, in our case:
- take residual_company_signed
- convert it to the invoice currency at the date of the invoice
- re-convert it to the payment currency at the date of the payment
@qdp-odoo , @smetl and/or @lap-odoo are welcome to drop some knowledge here though

I think the case is not solvable at all because:
- computation is correct every step of the way
- currency rates are so far apart that, without adapting the rounding of the relevant currency, errors of that sort are inevitable

**Comment by nim-odoo** [comment]
As mentioned by @kebeclibre , there will be a rounding issue anyway.
27.63 * 19 = 524.97
27.64 * 19 = 525.16

Not sure we can book the difference as an exchange difference entry since it would have an amount currency different from zero but a debit/credit equal to zero.

**Comment by qdp-odoo** [comment]
guys, I can't track if my input is needed in here or not. 
If no, then... well good bye :-)
If yes, then can you state a clear question?

thanks

**Comment by smetl** [comment]
@kebeclibre I'm not sure it's something fixable... In my opinion, the correct fix is far more complex and implies a lot of refactoring... Nothing enough easy & efficient came to my mind...

**Comment by sswapnesh** [comment]
@kebeclibre  If this is not fixable within the limitations we have then you can go ahead and close OPW/Issue. I don't think we should waste our time on something which requires lots of change as @smetl  said

cc @rohitramnani1994 (As you were the Author of the Issue)

**Comment by kebeclibre** [comment]
@sswapnesh 
Thanks :D
what a relief :D

**Pull request closed without merging**
