### PR TITLE
[FIX] web: template inheritance from dotted name

### PR DESCRIPTION
**Pull request by kebeclibre**
A good practice is to always prefix the name of a template by
the name of the module it is defined in.

So in the case where a template
```xml
<t t-name="module.template" />
```
was inherited by another

Before this commit, one should have written
```xml
<t t-name="other" t-inherit="module.module.template" />
```

After this commit, it becomes more natural, and one should only write
```xml
<t t-name="other" t-inherit="module.template"/>

### CODE REVIEW

**Comment by kebeclibre** [comment]
@seb-odoo 
@caburj 
Heads up :D

**Comment by kebeclibre** [comment]
robodoo r+

**Comment by MiquelRForgeFlow** [comment]
runbot is red

**Comment by kebeclibre** [comment]
robodoo r+

**Comment by kebeclibre** [comment]
robodoo rebase-ff

**Pull request closed without merging**
