### PR TITLE
[IMP] Allow buttons with tabindex

### PR DESCRIPTION
**Pull request by yajo**
Adding `tabindex="-1"` is the only way a button could be set to not have a hotkey when user presses <kbd>Alt</kbd>, so we need to enable it.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa TT19205 https://github.com/OCA/timesheet/pull/278

### CODE REVIEW

**Comment by rafaelbn** [comment]
[Here you can see how the patch works](https://github.com/odoo/odoo/blob/2ccf05940681cfdb783cd42c5627c65a80076f60/addons/web/static/src/js/chrome/keyboard_navigation_mixin.js#L135).

**Comment by rafaelbn** [comment]
Ping @mart-e

**Comment by Yajo** [comment]
> [Here you can see how the patch works](https://github.com/odoo/odoo/blob/2ccf05940681cfdb783cd42c5627c65a80076f60/addons/web/static/src/js/chrome/keyboard_navigation_mixin.js#L135).

Yes. [`tabindex` is used to tell the browser the order in which it has to jump from one control to the next when hitting <kbd>TAB</kbd>](https://developer.mozilla.org/es/docs/Web/HTML/Atributos_Globales/tabindex), and it's used by the keyboard navigation mixin where @rafaelbn linked to skip adding acces keys for buttons that shouldn't be keyboard-navigated.

We have some modules that add buttons to a tree/kanban view, and those buttons are very unlikely to be used from the keyboard. Since we have a limited amount of possible access keys, adding them to the buttons in the list view *steals* available keys for other buttons that are actually useful. So I need to disable the automatic access keys for them.

Another option would be to add a class such as `o_access_key_disabled` or similar, which also could be ignored by the keyboard navigation mixin; but TBH adding `tabindex` to the `.rng` seems much more helpful because it already works and can have more normal tabindex use cases. However I wouldn't mind to change this to a class if you prefer it.

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Comment by mart-e** [comment]
@fw-bot sssshhh, you are drunk !

**Comment by mart-e** [comment]
@xmo-odoo if an action is still needed, it is not clear enough

**Comment by xmo-odoo** [comment]
@mart-e looks apparently #37825 was not actually updated to closed in the backend (there might be an issue / bug when closing a PR in error there, [I'll check that](odoo/runbot#227)), so the forwardbot "helpfully" reminded that there was an "active" child PR to act upon.

I should also add which PRs are not closed to the message, probably.

**Comment by VincentSchippefilt** [comment]
thanks fw-bot, I'll be sure to do the action you mention.
@xmo-odoo @mart-e fw-bot told me to do something. I consider writing this message as doing something 😉

**Comment by xmo-odoo** [comment]
@VincentSchippefilt thanks, apparently while I noticed #37825 had not been correctly closed in the backend & created a bunch of tasks related to that I forgot to actually close it...

**Pull request closed without merging**
