### PR TITLE
[IMP] web: update owl from 2.0.0-beta-8 to 2.0.0-beta-10

### PR DESCRIPTION
**Pull request by ged-odoo**
Release notes:
https://github.com/odoo/owl/releases/tag/v2.0.0-beta-9
https://github.com/odoo/owl/releases/tag/v2.0.0-beta-10

Details:

fix: event: no crash when using t-on + modifier on slots/components
fix: component: fix props comparison code
fix: component: fix wrong behaviour when using t-on on t-component
fix: component: props values are own property of props object
fix: t-out: allow expressions evaluating as number
fix: compiler: add support for #{...} in string interpolation
imp: slots: add support for t-props on slots props
imp: tooling: add another d.ts file
ref: compiler: remove useless ; in compiled output
ref: move some code around
imp: app: small scale perf improvement
imp: app: add fast path for when component has no prop
imp: validation: add support for value types
fix: compiler: escape backticks in attributes

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by odony** [comment]
> rollup (the build system) bundled the files in a different order, which explains the large diff

Any chance it could be configured to produce more stable results? ;-)


@robodoo override=ci/security
F: https://runbot.odoo.com/runbot/build/16774266
R: declaration of markup utils, false positive

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
thanks for the quick reaction. @odony 
builds are usually stable, but rollup is configured to output one iife function that contains everything. So, when moving some functions from a file to another, the dependency graph may change, and rollup has to reorder files in a different order. Maybe there is a way to configure rollup to bundle each files in the same order by wrapping them in a function or something. I'll see if I can do something about that

**Comment by aab-odoo** [comment]
@xmo-odoo fwbot believes #94419 isn't merged nor closed, but he's wrong (?)

**Comment by xmo-odoo** [comment]
> fwbot believes #94419 isn't merged nor closed, but he's wrong (?)

Apparently updating the parent PR and closing this PR at the same time caused a race condition in the webhook, so the closing signal was lost. I closed the PR by hand in the backend, I'll have to have a think on how to handle this situations (though it's probably not critical as it's possible to handle it like this).

Possibly finally add an intake queue for the webhook events, which would have tons of other advantages.

**Pull request closed without merging**
