### PR TITLE
[FIX]google_calendar, microsoft_calendar: attendee behavior

### PR DESCRIPTION
**Pull request by arj-odoo**
Before this PR, following an invitation, when multiple partner would have the same email address, the chosen partner may not be the one we wanted (the one with an internal user).

Attendee answer would not be taken into account on microsoft.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by arj-odoo** [comment]
@tde-banana-odoo This the PR where I replace `self.env['res.partner'].find_or_create(...)` by `_mail_find_partner_from_emails`.
First I did the _mail_find_partner_from_emails in the loop for each attendee mail but as `_mail_find_partner_from_emails` accepts list of mails, I modified it to work in batch. I have to use zip on emails, partners and data sent from the sync service. Which version do you prefer? I am open to suggestions if you have any :-).

**Comment by arj-odoo** [comment]
After discussion with @tivisse it looks good to him.

**Comment by arj-odoo** [comment]
@robodoo r+

**Comment by arj-odoo** [comment]
@robodoo rebase-ff

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
