### PR TITLE
xavier-bouquiaux : I've learned and signed the CLA for acsone SA

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]
Confirming that @xavier-bouquiaux is an Acsone employee.

**Comment by mart-e** [comment]
Hi,

Could you change the commit message to follow the [commit message guidelines](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#commit-message-structure) ? Something like
```
[CLA] add xavier-bouquiaux to Acsone's CLA
```

**Comment by xavier-bouquiaux** [comment]
> Hi,
> 
> Could you change the commit message to follow the [commit message guidelines](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#commit-message-structure) ? Something like
> 
> ```
> [CLA] add xavier-bouquiaux to Acsone's CLA
> ```

Done

**Comment by mart-e** [comment]
Hello,

Thank you for the updat, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
