### PR TITLE
[IMP] web: new eslint rule for arrow functions

### PR DESCRIPTION
**Pull request by vlst-odoo**
In this commit we add the `"arrow-body-style": ["error", "as-needed"]` eslint rule to the `_eslintrc.json` file in order to enforce that lambda functions with a single return statement are written in a concise form
(i.e., without the curly braces and return keyword).

```js
//before
const myFunction = (myargs) => {
  return 3;
};
//after
const myFunction = (myargs) => 3;
```

https://github.com/odoo/enterprise/pull/74764

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vlst-odoo** [comment]
Hello, @aab-odoo , Do you agree with this change ?

**Review by aab-odoo — APPROVED** [review]
I don't have a strong opinion. I don't think I would have done that, but I'm not against, so...

robodoo delegate+

**Comment by vlst-odoo** [comment]
robodoo r+

**Comment by vlst-odoo** [comment]
Thanks @aab-odoo !

**Comment by gawa-odoo** [comment]
@robodoo r-
https://github.com/odoo/odoo/commit/d1b1a942a8b0b0aadb9013d8e44596ffded3dae2 got merged yesterday and conflicts with this rule

**Comment by caburj** [comment]
robodoo r+

maybe it's okay now

**Pull request closed without merging**
