### PR TITLE
[FIX] hr_attendance: change the user group check for Kiosk

### PR DESCRIPTION
**Pull request by Jinjiu96**
Reproduction:
1. Install Attendance app
2. Create a new internal user “kiosk”, with only access right “Kiosk
Attendance” for app “Employee”, other places as blank
3. Make sure the Settings for Attendance app, Employee PIN is unchecked
4. In an incognito tab, log in as kiosk, go to Attendance, click “kiosk
mode”, then “identify manually”
5. Choose an employee, with a warning message “Wrong pin”

Reason: A recent update refined the user group check for the
attendance_manual function. Checking if the user is an officer in the
Attendance app can be over strict. However, after discussing with yti,
we decided to pop up a warning message for security reasons when the
user would like to use Kiosk mode without pin code.

Fix: Add a warning message for higher access right requirement

opw-2898452

Related fix in V15: https://github.com/odoo-dev/odoo/commit/2975c0539d8c2781ff56a9f8be8e302d45b7d80b

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

note that hr_attendance_kiosk is implied by hr_attendance_user:

- `hr_attendance.group_hr_attendance_user` implies `hr.group_hr_user`
- `hr.group_hr_user` implies `hr_attendance.group_hr_attendance_kiosk`

**Comment by Jinjiu96** [comment]
@robodoo retry

**Comment by Jinjiu96** [comment]
@tivisse Could you have a look at the new fix? I added a warning message instead of changing the group check based on our discussion :smile: Thanks!

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
