### PR TITLE
[IMP] Update l10n_hn Autor Information

### PR DESCRIPTION
**Pull request by salvatoretrimarchi**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

FIX Autor Information
Salvatore Josué Trimarchi Pinto
Email contact

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by salvatoretrimarchi** [comment]
I add me to "cla individual" as salvatoretrimarchi github user (You can change Kinalem user check to salvatoretrimarchi?)

https://github.com/odoo/odoo/pull/14659

**Comment by mart-e** [comment]
Hello,

Could you explain the change? Was it a previous company now renamed?

**Comment by salvatoretrimarchi** [comment]
Yes, because I Changed my email and company.

Trigluu don't exist anymore since 2014 and trimarchi@trigluu.com email dosent work.

My actual email is trimarchi@bacgroup.net

**Comment by mart-e** [comment]
Thank you for the information, merged at https://github.com/odoo/odoo/commit/8ac66701280f9f54cebba870085c9c2cb86bbc2c

**Pull request closed without merging**
