### PR TITLE
[IMP] l10n_dk: improve current package

### PR DESCRIPTION
**Pull request by malb-odoo**
Cash journal profit and loss account remove domain to have the same account for
both

task: 4341375

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by proose — APPROVED** [review]
LGTM, too bad t-if doesn't work for that kind of inheritance :/

**Comment by malb-odoo** [comment]
eghhhh there is a conflict on the branch, will solve that soon

**Review by gawa-odoo — COMMENTED** [review]
Hello!
If I'm not mistaken, the try_loading does not work for these values (only `tag_ids` on accounts or `repartition_line_ids` for taxes if I'm not mistaken).
I don't know if we **really** want to update these, but if we do, it should be a SQL query (or a bit of code) for it in the migration script, I guess.

Second question, why not in 18? (maybe not the journal view but the accounts and taxes are something new users should probably directly get)

**Comment by gawa-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
