### PR TITLE
[FIX] *: retarget documentation links to saas-15.4

### PR DESCRIPTION
**Pull request by AntoineVDV**
See [task 2880678](https://www.odoo.com/web#model=project.task&id=2880678) for the discussion about an eventual "current version" widget.

See also:
- https://github.com/odoo/enterprise/pull/28227

### CODE REVIEW

**Comment by mart-e** [comment]
Wait that https://www.odoo.com/documentation/saas-15.4 is available before merging maybe :)

**Comment by AntoineVDV** [comment]
> Wait that https://www.odoo.com/documentation/saas-15.4 is available before merging maybe :)

Well, get to it then! :zany_face: But TBH I don't think it wouldn't be a big deal if documentation links were broken for a short while in a super fresh saas.

**Comment by AntoineVDV** [comment]
@fw-bot ignore

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
