### PR TITLE
[17.0] Fix fullcalendar TypeError: offsetTracker is undefined

### PR DESCRIPTION
**Pull request by bobslee**
In very rare occasions, when dragging (moving an event) in the calendar view, the following TypeError can occur. This could be related to custom computations (fields, other actions) when the ORM is updating a the related record. Perhaps this slows down the UI/frontend and triggers the error.

The change just adds a JS undefined check, to addres the error below. It seems really cumbersome to add unittest and even reproduction isn't repeatable.

TypeError: offsetTracker is undefined
    HitDragging.prototype.queryHitForOffset@https://.../web/static/lib/fullcalendar/interaction/main.js:1074:21
    HitDragging.prototype.handleMove@https://.../web/static/lib/fullcalendar/interaction/main.js:1049:28
    HitDragging/this.handleDragMove@https://.../web/static/lib/fullcalendar/interaction/main.js:1000:23
    applyAll@https://.../web/static/lib/fullcalendar/core/main.js:988:36
    EmitterMixin.prototype.triggerWith@https://.../web/static/lib/fullcalendar/core/main.js:3582:25
    EmitterMixin.prototype.trigger@https://.../web/static/lib/fullcalendar/core/main.js:3577:18
    FeaturefulElementDragging/_this.onPointerMove@https://.../web/static/lib/fullcalendar/interaction/main.js:809:39
    applyAll@https://.../web/static/lib/fullcalendar/core/main.js:988:36
    EmitterMixin.prototype.triggerWith@https://.../web/static/lib/fullcalendar/core/main.js:3582:25
    EmitterMixin.prototype.trigger@https://.../web/static/lib/fullcalendar/core/main.js:3577:18
    PointerDragging/this.handleMouseMove@https://.../web/static/lib/fullcalendar/interaction/main.js:102:31

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Read Odoo commit [guidelines](https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html#tag-and-module-name).

**Comment by bobslee** [comment]
@MiquelRForgeFlow Just pushed changes. Is it ok now ?

**Comment by bobslee** [comment]
Please, can this be merged?

**Comment by rfr-odoo** [comment]
@bobslee 
Hi, thanks for the fix.
The fix is ok, it's already in upstream git repo of FullCalendar since v5+ (c.f.: [the commit of the fix](https://github.com/fullcalendar/fullcalendar/commit/daf01c8dc6967de5b94bda6832429dd45eff0d1e#diff-e1a56b2d1284b2cd2cffc0d4a21d0a7cf3a1ff813e2bfe0afecd715961162c1bR168) ).

Can I ask to do some changes in your PR:
* do the same fix as in the upstream git repo
* add the comment `// Odoo patch` at the end of the fix line in the commit
* put in the commit message the link to the upstream [fix](https://github.com/fullcalendar/fullcalendar/commit/daf01c8dc6967de5b94bda6832429dd45eff0d1e#diff-e1a56b2d1284b2cd2cffc0d4a21d0a7cf3a1ff813e2bfe0afecd715961162c1bR168)

e.g.:
```patch
Index: addons/web/static/lib/fullcalendar/interaction/main.js
===================================================================
diff --git a/addons/web/static/lib/fullcalendar/interaction/main.js b/addons/web/static/lib/fullcalendar/interaction/main.js
--- a/addons/web/static/lib/fullcalendar/interaction/main.js	(revision c54ed734a9350971e9b95b301a1163cf1c44a07d)
+++ b/addons/web/static/lib/fullcalendar/interaction/main.js	(date 1728284449621)
@@ -1071,7 +1071,10 @@
             for (var id in droppableStore) {
                 var component = droppableStore[id].component;
                 var offsetTracker = offsetTrackers[id];
-                if (offsetTracker.isWithinClipping(offsetLeft, offsetTop)) {
+                if (
+                    offsetTracker && // Odoo patch - backport fix
+                    offsetTracker.isWithinClipping(offsetLeft, offsetTop)
+                ) {
                     var originLeft = offsetTracker.computeLeft();
                     var originTop = offsetTracker.computeTop();
                     var positionLeft = offsetLeft - originLeft;

```

Thanks.

**Comment by bobslee** [comment]
@rfr-odoo Thanks for your review and suggestions.
Hereby I (force) pushed the changes.
Awaiting on your follow up.

**Comment by rfr-odoo** [comment]
Hi, thanks for the change but I did not express myself quite correctly.
I wanted you to only take the fix for the `HitDragging` like your first commit but without the ` != undefined`.

```javascript
// Your first fix
      if (offsetTracker != undefined && offsetTracker.isWithinClipping(offsetLeft, offsetTop)) {

// The upstream fix
      if (
        offsetTracker && // wasn't destroyed mid-drag
        offsetTracker.isWithinClipping(offsetLeft, offsetTop)
      ) {
```
Can you make the change like in your first commit but without the `!= undefined` and the comment `// Odoo patch` and remove the other fixes.

Thanks

**Comment by bobslee** [comment]
@rfr-odoo Hereby I (force) pushed your requested changes.
Thanks!

**Review by rfr-odoo — APPROVED** [review]
@robodoo r+

**Comment by rfr-odoo** [comment]
@robodoo rebase-ff

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by rfr-odoo** [comment]
@robodoo fw=no

This fix is not needed in saas-17.2+ as fix already present since FC v5+ and in saas-17.2+ there FC v6

**Comment by rfr-odoo** [comment]
@robodoo up to 17.0

**Pull request closed without merging**
