### PR TITLE
 [FIX] Remove duplicates from mrp_repair security

### PR DESCRIPTION
**Pull request by sa3m**
User and manager access were overwritten few lines after being set up

Description of the issue/feature this PR addresses:
ID Duplicates in security lines

Current behavior before PR:
Manager has only read access whereas simple user has manager access

Desired behavior after PR is merged:
Manager should have manager access and simple user simple read access

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sa3m** [comment]
I agree with you, my solution makes sense but breaks tests (!).
I'll correct the CLA signature.

**Comment by mart-e** [comment]
After discussion with @lap-odoo we agreed, in master, to keep only one rule for user, giving access to everything for the stock user.
Could you please update the PR and I will merge it in master?
Thanks

**Comment by sa3m** [comment]
I did what you ask. Do you need the PR for Odoo 10 ?

**Comment by mart-e** [comment]
Thank you for the update, I have merged it in master and applied the same logic to all the other models:

2884f76488c [FIX] repair: remove useless rules
08cd80a315b [CLA] signature for Sa3m

Do not make a PR for odoo 10 as we can not remove a rule in stable version (and it is only cleaning, no real bug)

**Pull request closed without merging**
