### PR TITLE
[FIX] account: add a constraint to prevent the change of the reconcil…

### PR DESCRIPTION
**Pull request by csnauwaert**
…iation flag on account when there are already account_move_line existing

### CODE REVIEW

**Comment by blaggacao** [comment]
@csnauwaert @qdp-odoo Do you happen to remember, why you stated this:
>all aml should be recomputed for that account and this is very costly

I hit regularly this restriction if a customer decides: "oh, it would be better to be able to reconcile this", but he tells me so afterwards. 

As a potential reason for this statement, I only have identified:
```
@api.depends('debit', 'credit', 'amount_currency', 'currency_id', 'matched_debit_ids', 'matched_credit_ids', 'matched_debit_ids.amount', 'matched_credit_ids.amount', 'account_id.currency_id', 'move_id.state')
    def _amount_residual(self):
```

But actually this method would not be costly if we made a non-reconcilable account reconcilable, see:
```
        for line in self:
            if not line.account_id.reconcile:
                line.reconciled = False
                line.amount_residual = 0
                line.amount_residual_currency = 0
                continue
```

Everything is set up correctly. The other way round, it is a different story, but as a compromise, probably it would be possible to allow setting an account from non-reconcilable to reconcilable, but not the other way round.

Not being able to change this account config to reconcilable after some initial learning curve is a pretty strong limitation of usability.

What do you think?

**Comment by csnauwaert** [comment]
@blaggacao You are right the reason behind this constraint is that we had not set a dependency on the method '_amount_residual' in case the account_id.reconciled was changed. (which means that before this constraint, if a user changed his account type, he still would not be able to reconcile previous created entries). Adding this constraints could potentially leads to problem in case user has huge database with lot of entries and as you said, there is also a problem in case he decides to change a reconciled account to a not reconciled one (which means impacting moves that have potentially been reconciled, invoices, and so on..). 
The correct solution is as you state to allows to change the account reconciled flag in case we are moving from a non reconciled account to a reconciled one. I'm pretty sure we've set a task to do exactly what you said, I event think it has been merged (perhaps not in v9) @qdp-odoo can you confirm?

**Comment by qdp-odoo** [comment]
task under process... will be for next saas : https://github.com/odoo/odoo/pull/19204

**Comment by blaggacao** [comment]
Great, so I know what I have to do on my end. Thank you, Gentlemen!

**Comment by fmdl** [comment]
I think there are an issue :
It is write : 
```
# If user change the reconcile flag, all aml should be recomputed for that account and this is very costly.
# So to prevent some bugs we add a constraint saying that you cannot change the reconcile field if there is any aml existing
# for that account.
```

And after you have  `if vals.get('reconcile'):`

But to do that `If user change the reconcile flag` your replace `if vals.get('reconcile'):` by `if 'reconcile' in vals.keys()`

If not you can switch True to False.

**Comment by blaggacao** [comment]
@fmdl Indeed, you are right! I also saw this when backporting #19204.

**Pull request merged**
