### PR TITLE
Mj abuz patch 5

### PR DESCRIPTION
**Pull request by MjAbuz**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MjAbuz** [comment]
I did not submit this translation yet, however I guess its because I have Mediajockey user name in my translation  account at https://www.transifex.com/... but still I did not submit translation for this module.

**Comment by Yenthe666** [comment]
Hi @MjAbuz,

Thanks a lot for your PR. Translations are no longer managed through PR's but through the translation platform Transifex though.
Please see https://github.com/odoo/odoo/wiki/Translations for more information.

Regards,
Yenthe

**Comment by MjAbuz** [comment]
@Yenthe666 I know that, I am in the translation  team, This two i didn't even finish translating there... how come those are here ... !!

**Comment by Yenthe666** [comment]
Don't really get your question? You translate on Transifex, Odoo auto-syncs the translations from Transifex to Odoo every 1- weeks.

**Comment by MjAbuz** [comment]
Its being deleted a long ago https://github.com/MjAbuz/Odoo/tree/MjAbuz-patch-5

**Comment by MjAbuz** [comment]
@Yenthe666 yes.

**Pull request closed without merging**
