### PR TITLE
[FIX] mrp : open google slides display

### PR DESCRIPTION
**Pull request by Mtaylorr**
backport of : https://github.com/odoo/odoo/commit/895dd1aee22885cd9d98957be32b7916f77009d0
related enterprise fix : https://github.com/odoo/enterprise/pull/48635

opw-3523557

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

as far as I can tell, the difference in this backport is removing unnecessary code

note: the reference in the commit message should be changed to the merged commit hash: 895dd1aee22885cd9d98957be32b7916f77009d0 (in current commit message this is a dangling commit)

**Comment by Whenrow** [comment]
robodoo r+
fw-bot up-to saas-16.4

**Comment by Mtaylorr** [comment]
robodoo r+
fw-bot up-to saas-16.4

**Comment by Mtaylorr** [comment]
@robodoo  retry

**Comment by Mtaylorr** [comment]
@fw-bot close

**Pull request closed without merging**
