### PR TITLE
[FIX] microsoft_calendar: avoid deadlock at token refresh

### PR DESCRIPTION
**Pull request by alt-odoo**
We should rollback manually first to avoid concurrent access errors/deadlocks when
trying to refresh microsoft calendar token.

Description of the issue/feature this PR addresses:
op-2630601

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
At first sight this looks ok, as it is similar to what is done in 
https://github.com/odoo/odoo/blob/da862a45a8707e3795c5e0e88329f241164fdee2/addons/microsoft_calendar/models/microsoft_sync.py#L50-L60

Although, on closer inspection it seems that `_refresh_microsoft_calendar_token` is called only in `_get_microsoft_calendar_token` which, in turn, is called only by `microsoft_calendar_token`
So when we have a `requests.HTTPError` exception, it is managed by `_refresh_microsoft_calendar_token` that will raise a UserError anyway
https://github.com/odoo/odoo/blob/da862a45a8707e3795c5e0e88329f241164fdee2/addons/microsoft_calendar/models/res_users.py#L59-L66
so we never actually execute the former `except` block (the one in `microsoft_calendar_token`)

Everything was implemented recently in https://github.com/odoo/odoo/commit/9dc3057e8eb82d9237457167641585655f249c3e
Maybe I'm missing something, but this might need a bigger fix. Perhaps we could ask some help to @arj-odoo

**Comment by arj-odoo** [comment]
@agr-odoo @alt-odoo Hello ! @tfr-odoo made some modifications in 14.1 to improve the resilience of these syncs. We observed issues when more users activated the google calendar sync on odoo.com and the fixes improved the situation. 
https://github.com/odoo/odoo/commit/30f4be4889968e89ce4c81e454b7de1758c03491
I also ported some improvements from Google to Microsoft sync in master and more are planned (mostly with recurrent events)
https://github.com/odoo/odoo/commit/f7d16b4599d90e13bc1ecacf52e9d0000c1fc128
Is there a related ticket for this issue?

**Comment by alt-odoo** [comment]
@arj-odoo 
The support ticket is 2630601

**Comment by tfr-odoo** [comment]
@arj-odoo The idea of of the rollback was the possibility to use the same cursor so you should also remove the with cursor.

**Comment by alt-odoo** [comment]
@arj-odoo 
The customer is still facing a deadlock when trying to validate his leaves due to synch with microsoft calendar.

Can we backport your fixes in master or do you think we should just do a minimal fix in 14.0 instead (like the one I propose in this PR or not)?

Can you handle it please as you know more about this topic than me ?

**Comment by arj-odoo** [comment]
> @arj-odoo The customer is still facing a deadlock when trying to validate his leaves due to synch with microsoft calendar.
> 
> Can we backport your fixes in master or do you think we should just do a minimal fix in 14.0 instead (like the one I propose in this PR or not)?
> 
> Can you handle it please as you know more about this topic than me ?

I think i's possible to do a small fix. 

The solution is literally here and in the message of TFR (he confused our trigrams):
https://github.com/odoo/odoo/commit/30f4be4889968e89ce4c81e454b7de1758c03491#diff-adea592786f6eb7dc0dd69be2e9bb492579347e3cb932a87e687c7e4a75da5f6R87-R94

You rollback and you reset the token with the same cursor, then you commit.

**Comment by alt-odoo** [comment]
@arj-odoo 
Sorry I was confused too with this last message ^^
Is it OK this way ?

**Comment by arj-odoo** [comment]
> @arj-odoo Sorry I was confused too with this last message ^^ Is it OK this way ?

Maybe set microsoft_calendar_sync_token to False too? It will force a full sync at next sync but It's like when we restart the sync in 14.3 and later.

**Comment by alt-odoo** [comment]
@arj-odoo @agr-odoo 

Can you check and validate this PR please ?

**Comment by arj-odoo** [comment]
> @arj-odoo @agr-odoo
> 
> Can you check and validate this PR please ?

It looks good to me but the ticket number is not in the commit message.

**Comment by alt-odoo** [comment]
I have adapted the commit message, thanks !

**Comment by arj-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
