### PR TITLE
[FIX] payment(_stripe): fix issues with the SEPA Direct Debit method

### PR DESCRIPTION
**Pull request by AntoineVDV**
**[FIX] payment(_stripe): adapt validation currency to payment method**

When payment details are tokenized through a validation operation, the currency to use was usually (except overrides) chosen as that of the payment provider's company. This sometimes caused compatibility issues if the selected payment method did not support the company's main currency. For example, the SEPA Direct Debit payment method only supports the EUR currency.

This commit allows passing a payment method when getting the validation currency so that only supported currencies can be returned.

---

**[FIX] payment_(buckaroo, stripe): updated the PM based on provider codes**

When processing a transaction, the payment method was searched based on the received code (e.g., 'sepa_debit') that was compared with the `payment` module's generic codes (e.g., 'sepa_direct_debit'). This commit ensures that we now compare with provider-specific codes for Buckaroo and Stripe.

In practice, this mistake had little to no impact as most provider codes match the generic ones, and we fall back onto the payment method selected by the user if we can not find a more accurate one based on the code.

### CODE REVIEW

**Review by vchu-odoo — APPROVED** [review]
LGTM :+1:

**Comment by AntoineVDV** [comment]
@vchu-odoo I updated the second commit to adapt Buckaroo too.

Also, what's your take on also filtering validation currencies based on those supported by the provider?

**Comment by AntoineVDV** [comment]
@robodoo r+ rebase-ff

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
