### PR TITLE
[FIX] web, project : fix various issues

### PR DESCRIPTION
**Pull request by ppr-odoo**
web-
-  If time off is for today then the calendar cell appears on white background. But it should be gray.

project-
- project.project form view: remove the border under the 'description' notebook

- project.task gantt view: the progress bar should start on the very left of the pill

closes odoo#76647
Task-ID: 2648148

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
LGTM, thanks ! 🙂

**Review by IT-Ideas — COMMENTED** [review]
Thanks for the fix 🙂 

I would rename the second commit into [FIX] rather than [REM] as [REM] is about features that are removed. I would also point out that the issue is in the project form (as it is already fixed for the task form)

One last thing, it is best to write `task-2648148` instead of `taskID: 2648148`. The reason is that 2648148 could match a commit hash and then will be displayed as a shortcut to that commit, which we do not want.

Thanks for your work!

**Comment by IT-Ideas** [comment]
Hello @ppr-odoo , thanks for the work 🙂 
I had the feedback that we should no more display the yellow color on the today cell when today is not in an unavailability.

I ended up this this css diff (for the whole file):
```diff
diff --git a/addons/web/static/src/legacy/scss/web_calendar.scss b/addons/web/static/src/legacy/scss/web_calendar.scss
index 1f46eb48927..eecef0a97df 100644
--- a/addons/web/static/src/legacy/scss/web_calendar.scss
+++ b/addons/web/static/src/legacy/scss/web_calendar.scss
@@ -126,7 +126,6 @@ $o-cw-filter-avatar-size: 20px;

         .o_calendar_disabled {
             background-color: $gray-200;
-            border-color: white !important;
         }

         // ======  Specific agenda types ======
@@ -305,10 +304,13 @@ $o-cw-filter-avatar-size: 20px;
             }

             .fc-bg .fc-today {
-                background: $o-view-background-color;
                 border-color: gray('300');
             }

+            .fc-bg .fc-today:not(.o_calendar_disabled) {
+                background: $o-view-background-color;
+            }
+
             .fc-content-skeleton .fc-today .fc-day-number {
                 margin-top: 3px;
                 padding: 0.4em 0.4em 0.35em;

```

What do you think? Did I miss anything? Can you check?

Thanks and sorry for the back and forth on the PR.

**Comment by IT-Ideas** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
