### PR TITLE
[IMP] web_editor: make iframe assets smaller

### PR DESCRIPTION
**Pull request by Zynton**
Not all assets loaded into the wysiwyg iframe are used, and some of them are quite big. This commit removes the unused ones.

task-3323894

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@Zinston You might want to rebase this.

**Comment by dmo-odoo** [comment]
@Zinston It's not entirely clear to me, but I think that PR might have an impact on what you are doing here: https://github.com/odoo/odoo/pull/132190

**Comment by pparidans** [comment]
Just a quick comment to let you know that we are currently cleaning up some libraries and legacy files (and of course the common assets bundle mentioned above)... So the rebase will be... well... interesting :grin:

**Comment by dmo-odoo** [comment]
@pparidans As long as we can blame ~~the mobile team~~ ~~the framework-js-mobile team~~ you for the bugs that might be created because of it, we'll be fine. 👌

**Comment by pparidans** [comment]
> @pparidans As long as we can blame ~the mobile team~ ~the framework-js-mobile team~ you for the bugs that might be created because of it, we'll be fine. 👌

tell-me-more-salem

**Comment by Zinston** [comment]
@dmo-odoo I'm a bit concerned that this PR would now be too old because so many things have changed since. I think this should basically be redone from scratch to be sure to do the right thing...

**Comment by dmo-odoo** [comment]
@Zinston I think so too.

**Comment by pparidans** [comment]
FYI, the (biggest) changes have been merged, so... :military_helmet:

**Comment by Zinston** [comment]
This will have to be redone.

**Pull request closed without merging**
