### PR TITLE
[IMP] Improve performance of mass reconciliations

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Consider the case of a payment order when reconciling the invoices
with the amounts that are transferred to a clearing account. Every
time a move line is reconciled, the creation of the reconciliation
clears the cache of account.move.line's reconcile_id and
reconcile_partial_id which leads to a new prefetching of the growing
amount of move lines in the env's prefetch dictionary. This change
only clears the cache of the records that are actually referred to
in the new record's relation fields.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
@yelizariev a new tests in this version of Odoo revealed that my earlier approach triggered a prefetch during the cache invalidation in `Model.create()`. That meant that there was a trade off to my optimization at the cost of extra database queries. In a new version of this patch I invalidate the cache based on the values with which the new record was created instead of querying the newly created record directly, preventing the additional database queries to determine the records to invalidate.

Very cool that there was a test that made me realize this, using this `assertQueryCount` method that I was not aware of.

**Comment by yelizariev** [comment]
Caching mechanism is a bit black box for me as I haven't dived deep there. I understand the idea of PR, but don't really can review it now

**Comment by wtaferner** [comment]
@StefanRijnhart @yelizariev 
Hmm, this one looks promising...caching and prefetching (especially as you need to skip it in certain situations) is indeed a big black hole, but it is probably b/c you normally do not care about it as you expect that it is just working up to the moment you are forced to think about your own implementation due to performance lacks and find out that you should care every second (although it makes sense to optimize afterwards to not get lost) and it could be worth to actually get some more feedback from the system without knowing every corner in the hole ;-) Odoo internal profile decorator is great and should be extended and used massively :-)

@StefanRijnhart 
Did you do any benchmarks and tests with data to see and demonstrate the impact? ;-)

@rco-odoo 
What do you think about this?

**Comment by StefanRijnhart** [comment]
@wtaferner in our 8.0 port of this patch, reconciling 20000 pairs of receivable move line with SEPA debit order move line is approx. 10 times as fast. But I have now taken to insert those move lines in SQL because at least in 8.0 account.move.line's get_default insists on firing an expensive method to retrieve default values for several fields even if they are passed in the values dictionary in the first place.

**Comment by pedrobaeza** [comment]
Coming to this through codetriage.com

@StefanRijnhart it seems this is not going to be accepted, so should you close it or are you going to give it another shot?

**Comment by StefanRijnhart** [comment]
OK, I'll probably revisit this when we migrate this setup to some later version of Odoo.

**Pull request closed without merging**
