### PR TITLE
[MERGE] mass_mailing, web(site,_editor): restore website snippets independance

### PR DESCRIPTION
**Pull request by Zynton**
Commit [1] copied a lot of website snippet options into mass mailing. Some were moved to web_editor and xpathed to be used in both without duplicating code. Sadly that is not without side effects and it was therefore decided to duplicate them instead so they can live separate lives in the future.

The css of some website snippets conflicted with their mass_mailing equivalents. A quick, non-intrusive solution had been to contain that css so it wouldn't conflict. This replaces that solution with the more neighborly renaming of said snippets in mass_mailing. This way there is no added awareness of mass_mailing within the code of website.

[1] 4f7cd33

Enterprise PR: https://github.com/odoo/enterprise/pull/21364

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Zinston** [comment]
@Xavier-Do A follow-up to the mass mailing snippets task, I'm restoring a couple of snippets and options that were moved to be xpathed into mass_mailing and website rather than duplicated into mass_mailing. This should not cause any problems since the only reason for the ci/templates error is that the "new" templates are not yet in master, which they will be when we forward port the other branch (forward port hasn't happened yet) and this one together. Thanks for your understanding.

**Comment by Xavier-Do** [comment]
Don't merge this before everything is forwardported and most important, exception are removed. Upgrade is green only because of active exception, you will need an upgrade script for that.

**Comment by dmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by Zinston** [comment]
@fw-bot ignore

**Pull request closed without merging**
