### PR TITLE
[FIX] mass_mailing: use the right field for domain

### PR DESCRIPTION
**Pull request by RomainLibert**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by RomainLibert** [comment]
@tde-banana-odoo ping

**Comment by RomainLibert** [comment]
@tde-banana-odoo pong?

**Comment by tde-banana-odoo** [comment]
@RomainLibert Come back to the team if you want an answer.

**Comment by tde-banana-odoo** [comment]
Apart from that ... what about is_blacklisted = False in mass_mailing, and is_blacklsited + customer rank in the sale override ?

**Comment by RomainLibert** [comment]
@xmo-odoo

**Pull request closed without merging**
