### PR TITLE
PRHOOT 26

### PR DESCRIPTION
**Pull request by jum-odoo**
## Pull Request HOOT (PRHOOT) - part 26

Part 1: https://github.com/odoo/odoo/pull/152930
Part 2: https://github.com/odoo/odoo/pull/153018
Part 3: https://github.com/odoo/odoo/pull/153023
Part 4: https://github.com/odoo/odoo/pull/153203
Part 5: https://github.com/odoo/odoo/pull/153425
Part 6: https://github.com/odoo/odoo/pull/153700
Part 7: https://github.com/odoo/odoo/pull/154054
Part 8: https://github.com/odoo/odoo/pull/154579
Part 9: https://github.com/odoo/odoo/pull/155073
Part 10: https://github.com/odoo/odoo/pull/155639
Part 11: https://github.com/odoo/odoo/pull/156255 / https://github.com/odoo/enterprise/pull/58135
Part 12: https://github.com/odoo/odoo/pull/156869
Part 13: https://github.com/odoo/odoo/pull/158384 / https://github.com/odoo/enterprise/pull/59019
Part 14: https://github.com/odoo/odoo/pull/158916
Part 15: https://github.com/odoo/odoo/pull/160292 / https://github.com/odoo/enterprise/pull/59971
Part 15.5: https://github.com/odoo/odoo/pull/166463
Part 16: https://github.com/odoo/odoo/pull/166311
Part 17: https://github.com/odoo/odoo/pull/168328
Part 18: https://github.com/odoo/odoo/pull/171004 / https://github.com/odoo/enterprise/pull/65657
Part 19: https://github.com/odoo/odoo/pull/171242 / https://github.com/odoo/enterprise/pull/65767
Part 20: https://github.com/odoo/odoo/pull/173332 / https://github.com/odoo/enterprise/pull/66895
Part 21: https://github.com/odoo/odoo/pull/174337
Part 22: https://github.com/odoo/odoo/pull/176777 / https://github.com/odoo/enterprise/pull/68721
Part 23: https://github.com/odoo/odoo/pull/179660 / https://github.com/odoo/enterprise/pull/69728
Part 24: https://github.com/odoo/odoo/pull/181971
Part 25: https://github.com/odoo/odoo/pull/183358

Enterprise: https://github.com/odoo/enterprise/pull/73361

This pull requests brings various improvements and fixes to Hoot and the Odoo unit test ecosystem. See the different commit messages for more details.

Note: these changes are made in stable to avoid having to support multiple versions of the HOOT API. As such, these changes are intended to be strictly limited to unit tests as to not put the rest of the code base at risk.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jum-odoo** [comment]
Link to conversation about additional indent for tests with long names: https://github.com/odoo/odoo/pull/183921#discussion_r1827618012

**Comment by seb-odoo** [comment]
> Link to conversation about additional indent for tests with long names: [#183921 (comment)](https://github.com/odoo/odoo/pull/183921#discussion_r1827618012)

Do we continue the discussion here?

I don't know where the rule comes from and I don't know what it is matching, but it is already the case for long test title, max length is ignored.
I'm guessing it matches `test(` at the start of a line.

If whatever is the default ignore doesn't work for us with tags, maybe we can use ignore pattern?

https://eslint.org/docs/latest/rules/max-len#ignorepattern

**Comment by jum-odoo** [comment]
> I don't know where the rule comes from and I don't know what it is matching, but it is already the case for long test title, max length is ignored. I'm guessing it matches `test(` at the start of a line.

Ok so after a bit of investigation it looks like it's a built-in behavior of Prettier: https://github.com/prettier/prettier/issues/12575. The issue mentioned here requested the pattern to be configurable but instead they just extended the built-in pattern to a list of accepted strings related to the PlayWright syntax, and since it doesn't meet our tagging syntax it doesn't work.

I tried playing a bit with `max-len` but the issue is that it's a rule affecting *ESLint* and not *Prettier*, so it will just add warning in the IDE but it won't affect the formatting (and since Prettier has the final word you will just end up with the same result, but with VSCode blinking red like a Christmas tree).

I think the most realistic solution would be to change the tagging syntax, but without function decorators we're very limited in our options for both an elegant and functional solution.

**Comment by seb-odoo** [comment]
I don't know how it works, but yes it's good enough, and I find it even more clear to see the tags above rather than on the same line actually.

As for the prettier issue, I'm not sure how it comes into play for us, as we only use  `eslint --fix` in our tooling no?

**Comment by jum-odoo** [comment]
The prettier issue is unrelated, I just linked it as a reference to the built-in Prettier ignore pattern for test functions.

For future reference, the full list of ignored line starters can be found [here](<https://github.com/prettier/prettier/pull/12779/files#diff-f133b42c48e9e8ab9cd11d9c1a9094b51b68b6f9b683da486764d795aa521e21R462>).

Note that it includes `test.only` and `test.skip`, but not `test.todo` nor `test.debug`, so these 2 may still trigger line returns

**Comment by mcm-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
