### PR TITLE
[FIX] web_editor: keep span with pseudo-elements on sanitization

### PR DESCRIPTION
**Pull request by robinlej**
Commit [1] made sure `span`s without attributes are removed, as they're useless. However, it did not take pseudo-elements into account. This commit ensures that if there is no attribute but a pseudo-element can be detected, the tag is not removed.

[1]: https://github.com/odoo/odoo/commit/a26e27c85e6a0685b6cf4d2dbab90453899df34c

opw-3881401

### CODE REVIEW

**Comment by robinlej** [comment]
Hi @odoo/rd-framework-editor , could you give me your opinion on this fix? Is it ok for you to call `getComputedStyle` in this context?

**Comment by Zynton** [comment]
Hi @robinlej ! It looks fine to me, thanks for asking!
I would say though, if you're going to introduce that function anyway, might as well also you use it [here](https://github.com/odoo/odoo/pull/163392/commits/d5baf281c24bc6409cefa213d15b9b1ceedd7bf6#diff-bc2a69e8fb849cbdfe90e279df1856b167187f401df4ef7b1a1bd1ade27c23c3R59). Unless @dmo-odoo wants to be more careful about that sort of changes in stable?

**Comment by dmo-odoo** [comment]
Well I'd rather not add code if we don't have a bug with it. Especially considering we will remove the removal of empty span at some point in the near future. I have no ETA for that though, which is why I think we can merge this PR so that the issue is already fixed while waiting for the bigger change.

**Comment by dmo-odoo** [comment]
@robinlej Thanks for the fix! It's good for me. Any reason you might want to keep this in draft or can I merge it?

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
