### PR TITLE
[FIX] product: if not EAN13 use Code128 for codebar

### PR DESCRIPTION
**Pull request by nle-odoo**
If codebar is 13 digits: use EAN13, else use Code128.

opw-668309
task: 22361

**PR NOTE:** I'm not sure if we want this or if we always want Code128

### CODE REVIEW

**Comment by mart-e** [comment]
Sorry but detecting EAN13 is not as simple as "length of 13" (by the way length of < 13 is also a valid EAN13).
I can have a Code128 code bar that contains '1234567890123' and the next product being '12345678901234' (free text zone). I don't want my product barcode to change from one report to another, the rendering should be constant.
If you want to authorise more than one type and dynamically adapt (not sure we do), should be in a barcode_type field

**Comment by mart-e** [comment]
@nle-odoo ok, after discussion, we ca' implement the following:
If only digits -> ean13 (no changes for existing)
If char -> coda128 (was crashing anyway)

**Comment by mart-e** [comment]
LGTM :+1: 
By the way, as we probably don't want to apply this patch everywhere, we should probably create a new type 'dynamic' that will do the same in master (RD task).

**Comment by nle-odoo** [comment]
yes thanks

I have to wait some answers from the reporter of the original issue before going further (since he may have been in another situation than the one described in the task).

**Pull request closed without merging**
