### PR TITLE
[IMP] sale_quotation_builder: uniformize back button

### PR DESCRIPTION
**Pull request by mitali-willdooit**
Description of the issue/feature this PR addresses:
<b> Task:</b> https://www.odoo.com/web?#id=1943427&action=333&active_id=131&model=project.task&view_type=form&menu_id=4720
<b> Pad:</b> https://pad.odoo.com/p/r.fc939a056d38348e75818e75bbeff2e0
Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rdeodoo** [comment]
Thanks, I just rebased and did some small changes so we can merge this one:
1. use autoclosing `<i/>` tag
2. set return url in a variable so the `<a>` tag is more readable and the line is shorter
3. edited commit message to fit commit message guidelines

**Comment by rdeodoo** [comment]
Actually using the already existing `portal_back_in_edit_mode` was probably the best idea but that template needed a bit of change.

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo retry

**Pull request closed without merging**
