### PR TITLE
[FIX] web: fix bolder label in properties field

### PR DESCRIPTION
**Pull request by chgo-odoo**
This commit fixes a visual issue with a label of the properties modal that has a bolder font-weight than the other.

This issue comes from the fact we recently changed the behavior of our `bold` and `bolder` variants.

To avoid this issue, we simply remove the label to render the text directly inside the `label`.

task-3580556

image

### CODE REVIEW

**Review by stefanorigano — APPROVED** [review]
LGTM, thanks @chgo-odoo 👍

**Comment by chgo-odoo** [comment]
Hello @std-odoo 👋

I remember LNA calling you _master of the properties_ so I wanted to summon you here to review this small PR and eventually R+ it if you have some time to review it \o/

Thanks !

**Review by std-odoo — APPROVED** [review]
Thanks for the fix, LGTM :)

**Comment by std-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
