### PR TITLE
[FIX] mail: does not auto-subscribe people to a group which is "Followers only"

### PR DESCRIPTION
**Pull request by nim-odoo**
This could happen if a partner which was not in the followers was added as cc
to a group message.

opw-633988

### CODE REVIEW

**Comment by beledouxdenis** [comment]
To me it looks ok but I would appreciate @tde-banana-odoo opinion to make sure of the functional perspective on the condition. Maybe there are other value for `alias_contact` for which this should be applied as well. 

In addition, change this `self.pool.get()` to `self.pool[]`: It provides a better traceback when the model is not in the pool, and both `self.pool[].browse` and `self.pool.get().browse` will crash anyway in case the model is not in the pool.

**Comment by tde-banana-odoo** [comment]
What is the issue precisely ? Actually someone can send an email to a 'followers' alias if he is in the document followers. So the message's author should already be in the followers. If this is not the case there is an issue.

About the CC, what is the issue precisely ? Recipients are added in the partner_ids, but not in the followers, unless the 'mail_post_autofollow' key is in context.

Could you then explain more the issue ? Maybe provide a test case (for example in existing mailgateway tests in test_mail_gateway.py).

**Comment by nim-odoo** [comment]
From the OPW:

FOR ISSUE : 633988

- Set alias domain : Settings > General Settings 
- Create a group ( Test Group )
- give alias to the group (test@odoo.com)
- send a mail from a group (Test Group) to any third person which does exist in system. ( Anyway, you would must be required to create a partner in system in manner to send a mail )
- send a mail and check the followers list. Partner will be added automatically ( This is ok, you can remove partner from followers list once you sent the mail )
- now when partner replies to the mail again he will get automatically added to followers list.


Customer's Problem : Partner gets added to followers list, when  even if the group is set as private.bye!

My opinion : When you add partner in system and when you mail from using private group mail id that means you are indirectly authorizing a partner to being added to the private group.

Customer's feedback : The partner should not get added in any circumstances as group is private.

You can check the video, I have added in last internal note.

**Comment by tde-banana-odoo** [comment]
If the alias is public, indeed anyone can write to the group. If the alias is followers only, only already existing followers can write to the group. Partners added as recipients of a message are added as followers, because that's the standard behavior. So, what is the issue ?

If I understand well, the only issue is that when you create a private group, the alias should be private by default (maybe add an onchange ?).

**Comment by nim-odoo** [comment]
> Partners added as recipients of a message are added as followers, because that's the standard behavior

This is ok. The problem is that if you *manually* remove the partner from the recipients, he will be added again automatically if he replies to the mail (that is a weird use case, I agree).

**Comment by tde-banana-odoo** [comment]
It should not if the alias is private. Do you have a test case ?

**Comment by nim-odoo** [comment]
@tde-banana-odoo : could you have a look again? Thanks!

**Comment by nim-odoo** [comment]
Coucou, y'a quelqu'un ? :heart:

**Comment by tde-banana-odoo** [comment]
Well I don't like using a context key ... but I suppose this is due to avoid having parameters to add in a stable version.

For the (none, none, none) thing, it is weird. Couldn't you return False when the check is failed and add an 'elif route is False' ? Which is different from a void list in python.

Small note: no need to set False as default value in a dict.get(), as it returns None by default.

**Comment by nim-odoo** [comment]
Indeed, the context key is to avoid adding a parameter.

Regarding the (none, none...), I just did it so the method always return the same object type. If you don't see any problem with that, I will change to False.

**Pull request merged**
