### PR TITLE
[MERGE] (various): adapt tours to always edit

### PR DESCRIPTION
**Pull request by bouvyd**
Always edit mode comes with several layout and behavioral changes that may necessitate changes in tours (both in terms of selectors for the tips and in terms of content, e.g. since "Save" steps are now kind of redundant).

### CODE REVIEW

**Comment by bouvyd** [comment]
@odoo/rd-security `Markup` in tours

**Comment by bouvyd** [comment]
@robodoo r+ when security will approve

**Comment by xmo-odoo** [comment]
@robodoo override=ci/security

**Comment by bouvyd** [comment]
@robodoo r+ rebase-merge

**Pull request closed without merging**
