### PR TITLE
[FIX] base_automation: recursive computed field cause too many calls to flush

### PR DESCRIPTION
**Pull request by rco-odoo**
The use-case that motivated this fix is the deletion of a project task with many subtasks.  The field `project_id` on tasks is recursively computed, and some automated action must be executed when its value corresponds to a given project.

The issue occurs when the domain of automated actions is evaluated by method `search()`, because the latter flushes the fields to search on, which are also the ones being recomputed.  Combined with the fact that recursive fields are not computed in batch, this leads to a huge amount of recursive calls between the automated action and `flush()`.

The execution of `task.unlink()` looks like this:
- mark `project_id` to compute on subtasks
- delete task
- `flush()`
  - recompute `project_id` on subtask1
    - call compute on subtask1
    - in action, `search([('id', 'in', subtask1.ids), ('project_id', '=', pid)])`
      - `flush(['id', 'project_id'])`
        - recompute `project_id` on subtask2
          - call compute on subtask2
          - in action, `search([('id', 'in', subtask2.ids), ('project_id', '=', pid)])`
            - `flush(['id', 'project_id'])`
              - recompute `project_id` on subtask3
                - call compute on subtask3
                - in action, `search([('id', 'in', subtask3.ids), ('project_id', '=', pid)])`
                  - `flush(['id', 'project_id'])`
                    - recompute `project_id` on subtask4
                         ...

### CODE REVIEW

**Review by madprog — APPROVED** [review]
:star_struck:

**Review by odony — APPROVED** [review]
Nice :+1: That looks on par with #67147 indeed, and the extra test is a great addition.
Do you think we should target 13.0, as for #67147?

**Comment by rco-odoo** [comment]
> Nice +1 That looks on par with #67147 indeed, and the extra test is a great addition.

Indeed, I found out that PR.

> Do you think we should target 13.0, as for #67147?

Yes, I have a branch for version 13.0, but without the test (the test module was introduced in 14.0).

**Comment by rco-odoo** [comment]
@robodoo override=ci/security r+

**Pull request closed without merging**
