### PR TITLE
sale_order_line

### PR DESCRIPTION
**Pull request by sumitmishra72925**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why are you making this pull requests?

**Comment by sswapnesh** [comment]
@pedrobaeza  As I thought in his First PR, This was just to complete hacktoberfest challenge.
https://hacktoberfest.digitalocean.com/stats/sumitmishra72925
screenshot 58

**Comment by pedrobaeza** [comment]
That's very ugly... Can we report this abuse to Hacktoberfest?

**Comment by sswapnesh** [comment]
I think we should not spend our time for such silly thing.
However we can mail  to `hacktoberfest@digitalocean.com` if PR like this are High.

**Comment by sumitmishra72925** [comment]
I'm extremely sorry for my silly mistakes.

**Pull request closed without merging**
