### PR TITLE
add search function to fields dropdown list of search view

### PR DESCRIPTION
**Pull request by roganw**
Description of the issue/feature this PR addresses:
add search function to fields dropdown list of search view

Current behavior before PR:
can not search fields in the custom filter

Desired behavior after PR is merged:
Users can search the fields in the dropdown list of custom filter.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hooray, thanks for resubmitting against master! @ged-odoo and @aab-odoo thia is for you guys.

**Comment by ged-odoo** [comment]
@Yenthe666 this is more a usability question now... we just need approval from usability before merging this

**Comment by gustavovalverde** [comment]
Oh, this is nice! 👍

**Comment by ged-odoo** [comment]
@bst-odoo what do you think of this? should this be merged in master?

**Comment by bst-odoo** [comment]
It is smooth. And we already had the request. I like it. 
Is the search field necessary ? I mean, it should be hidden until you enter the first letter of your search.

**Comment by bst-odoo** [comment]
I've discussed with EST. According to her, we can leave it like this. So OK to merge it :)

**Comment by C3POdoo** [comment]
Dear @roganw,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
