### PR TITLE
[FIX] sale_product_matrix: compute purchase_price for SOLines generated by matrix

### PR DESCRIPTION
**Pull request by Feyensv**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@dbo-odoo First or second solution ? :D

**Comment by dbo-odoo** [comment]
lgtm @robodoo r+
ooprah

**Comment by dbo-odoo** [comment]
@robodoo r+ please, could you at least acknowledge me with a tag? 💔

**Comment by dbo-odoo** [comment]
@robodoo rebase-ff

**Comment by Feyensv** [comment]
@robodoo retry

**Comment by Xavier-Do** [comment]
robodoo retry

**Pull request closed without merging**
