### PR TITLE
[IMP] mail: introduce ComposerView/onClickSuggestion

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2579306

### CODE REVIEW

**Review by phenix-factory — APPROVED** [review]
I guess you still need to make the PR that move the `onClick` even?
otherwise LGTM

**Comment by alexkuhn** [comment]
> I guess you still need to make the PR that move the `onClick` even?
> otherwise LGTM

Yes, I did most `AttachmentViewer` moves of handler methods, and it should continue alphabetically, model by model.
This PR I made it much sooner because one of getter's PR require this move of handler:
https://github.com/odoo/odoo/pull/87741

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r-

**Comment by seb-odoo** [comment]
obsolete pr

**Pull request closed without merging**
