### PR TITLE
[11.0] hw_escpos pyusb>=1.0.0b2 support

### LINKED ISSUE #19017: odoo.addons.hw_escpos.controllers.main: write() got multiple values for keyword argument 'timeout'
Impacted versions:

10.0

Steps to reproduce:

Connect usb printer, enable hw_escpos.

Current behavior:

Odoo fails with error.

Log:

```
2017-08-23 14:37:18,903 11242 INFO ? odoo.addons.hw_escpos.controllers.main: connected : Connected to Љ Љ (in=0x82,out=0x01)
2017-08-23 14:37:18,927 11242 INFO ? odoo.addons.hw_escpos.controllers.main: error : write() got multiple values for keyword argument 'timeou
t'
2017-08-23 14:37:18,927 11242 ERROR ? odoo.addons.hw_escpos.controllers.main: ESC/POS Error: write() got multiple values for keyword argument
 'timeout'
2017-08-23 14:37:18,927 11242 ERROR ? odoo.addons.hw_escpos.controllers.main: write() got multiple values for keyword argument 'timeout'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ata/Softwares/odoo/addons/hw_escpos/controllers/main.py", line 167, in run
    self.print_status(printer)
  File "/home/ata/Softwares/odoo/addons/hw_escpos/controllers/main.py", line 201, in print_status
    eprint.text('\n\n')
  File "/home/ata/Softwares/odoo/addons/hw_escpos/escpos/escpos.py", line 824, in text
    self._raw(txt)
  File "/home/ata/Softwares/odoo/addons/hw_escpos/escpos/printer.py", line 85, in _raw
    if len(msg) != self.device.write(self.out_ep, msg, self.interface, timeout=5000):
TypeError: write() got multiple values for keyword argument 'timeout'
------------------------------------------------------------
```

Expected behavior:

Odoo successfully connects to the printer and prints status message.

---------------------------------------------------------------------------------------------------------

The pyusb API has changed in 1.0.0b2. `write()` dropped the `interface` argument.

A workaround was to change the version number of pyusb to 1.0.0b1 in the requirements.txt. (currently it is 1.0.0)

### PR DESCRIPTION
**Pull request by azmeuk**
## Description of the issue/feature this PR addresses:

The posbox installation documentation [advises to install pyusb 1.0.0b1](https://www.odoo.com/documentation/user/11.0/point_of_sale/overview/setup.html#extra-dependencies) with pip. However, on certain posboxless environments, there is no possibility to install pyusb with pip, because some other programs on the system needs the pyusb version packaged by the system. This pull requests brings the support for pre and post 1.0.0b1 pyusb versions. 

Since pyusb 1.0.0b2, [(released in october 2014)](https://pypi.org/project/pyusb/1.0.0b2/), the `usb.Device.write` `interface` parameter [has been deleted](https://github.com/pyusb/pyusb/commit/20cd8c1f79b24082ec999c022b56c3febedc0964#diff-b5a4f98a864952f0f55d569dd14695b7L293). This pull request keeps the previous behavior for versions prior to 1.0.0b2 and skips the faulty parameter for 1.0.0b2 and later versions.

This fixes #19017. 

I know that 9.0 and 10.0 versions are not supported anymore, but I would strongly bring this patch back to those versions. Can we also discuss the subject?

## Current behavior before PR:
This should fix #19017, where it is described that `hw_escpos` did not work with `pyusb` >= 1.0.0b2.

## Desired behavior after PR is merged:
`hw_escpos` works with any version of `pyusb`.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by janpjens** [comment]
Thank you for that PR @azmeuk ! I hope it will be reviewed and merged soon, given that the requirements.txt file only specifies `pyusb==1.0.0` which will not work. Replacing it with `pyusb==1.0.0b1` will, as is also stated in the 10.0 issue you linked.

For what it's worth, in case anyone else get the "RuntimeError: cannot set daemon status of active thread" scenario I had:

With hw_escpos under 11.0 you may not get the `TypeError: write() got multiple values for keyword argument 'timeout'` error until you manually modify hw_escpos source to make it more verbose. Initially the log only gave me a complaint of an unknown printer (even thought it's `Epson TM-T20II`), then the following thread exception that sent me into hw_escpos:

```Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo11/src/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo11/src/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo11/src/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo11/src/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo11/src/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo11/src/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo11/src/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo11/src/odoo/http.py", line 939, in call
    return self.method(*args, **kw)
  File "/home/odoo11/src/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo11/src/addons/hw_proxy/controllers/main.py", line 141, in status_json
    return self.get_status()
  File "/home/odoo11/src/addons/hw_proxy/controllers/main.py", line 43, in get_status
    statuses[driver] = drivers[driver].get_status()
  File "/home/odoo11/src/addons/hw_escpos/controllers/main.py", line 119, in get_status
    self.push_task('status')
  File "/home/odoo11/src/addons/hw_escpos/controllers/main.py", line 195, in push_task
    self.lockedstart()
  File "/home/odoo11/src/addons/hw_escpos/controllers/main.py", line 101, in lockedstart
    self.daemon = True
  File "/usr/lib/python3.6/threading.py", line 1141, in daemon
    raise RuntimeError("cannot set daemon status of active thread")
RuntimeError: cannot set daemon status of active thread

**Comment by azmeuk** [comment]
@janpjens Would you consider reviewing this PR with the github review feature?

**Comment by azmeuk** [comment]
@aprieels also, can you please review this patch?

**Comment by azmeuk** [comment]
@ata2001 @Yenthe666 @lem8r @nick2474 Would you consider reviewing this patch (with the github review feature)?

**Review by aprieels — APPROVED** [review]

**Comment by Yenthe666** [comment]
@rhe-odoo or @pimodoo could one of you have a look at this PR please?

**Review by qle-odoo — APPROVED** [review]
@robodoo r+ rebase-ff

**Comment by Yenthe666** [comment]
Ehh you probably wanted a nicer commit message & a squash before merging that in 😄

**Comment by qle-odoo** [comment]
@robodoo r-

**Comment by qle-odoo** [comment]
@azmeuk can you rewrite the commit messages by following the Odoo guidelines please

https://github.com/odoo/odoo/wiki/Contributing

**Comment by azmeuk** [comment]
@qle-odoo Done.

**Comment by qle-odoo** [comment]
@azmeuk your commit messages ?

**Comment by azmeuk** [comment]
Ok I did not understood that I needed a full description of the patch in the commit message.
The documentation you pointed me actually does not mention explicitly the commit message policy, but I could find it here: https://www.odoo.com/documentation/13.0/reference/guidelines.html#commit-message-full-description

**Comment by qle-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by seb-odoo** [comment]
PR has no CI, merging didn't start.

**Comment by azmeuk** [comment]
Is there something I can do with this?

**Comment by seb-odoo** [comment]
I have actually no idea why it didn't work in this case, I was just highlighting the issue.
cc @Xavier-Do

**Comment by Xavier-Do** [comment]
> I have actually no idea why it didn't work in this case, I was just highlighting the issue.
> cc @Xavier-Do

It is an old external pr and runbot add some trouble defining version during migration to 5.0. Has you can see on the [last batch](https://runbot.odoo.com/runbot/batch/484877):
`PR odoo/odoo:38390 targeting wrong version: 11.0 (expecting master)`

This is actually not exactly the right solution but the version of the bundle should be 11.0, it is now fixed.

The [new batch](https://runbot.odoo.com/runbot/batch/485126) Should be ok since now runbot will use the correct tests for this version.

**Pull request closed without merging**
