### PR TITLE
[IMP] base: various helpers for documents' sharepocalypse

### PR DESCRIPTION
**Pull request by Julien00859**

### CODE REVIEW

**Comment by Julien00859** [comment]
@robodoo rebase-ff

**Comment by Julien00859** [comment]
cc @flvr-odoo should be ok according to our discussions

**Comment by Julien00859** [comment]
Go fast break things he said...

*Alea iacta est*

@robodoo r+

**Comment by tde-banana-odoo** [comment]
You know what they say about self r+ :D ...

**Pull request closed without merging**
