### PR TITLE
[FIX] odoo_referral_portal: Remove portal link to Odoo Referral

### PR DESCRIPTION
**Pull request by tivisse**
Purpose
=======

Twitter spec are always the best.

https://twitter.com/fpodoo/status/1247234043177041920?s=08

TaskID: 2222759

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by KangOl** [comment]
Also remove the `auto_install` flag.

**Comment by tivisse** [comment]
@KangOl Thanks ;)

@robodoo r+

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo r+

**Comment by ray-odoo** [comment]
@tivisse made my day - "requirements via Twitter"!

**Pull request closed without merging**
