### PR TITLE
[FIX] hr_holidays: add string for filter department child

### PR DESCRIPTION
**Pull request by locdang8**
image
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by locdang8** [comment]
@fdamhaut  pls review for me

**Comment by fdamhaut** [comment]
@phwa-odoo

**Comment by phwa-odoo** [comment]
@Geoffrey-GMF since it is more functional

**Comment by phwa-odoo** [comment]
@Geoffrey-GMF approves. Please add the new string in the .pot file.

**Comment by locdang8** [comment]
@phwa-odoo @Geoffrey-GMF I added to the pot file

**Review by phwa-odoo — APPROVED** [review]

**Comment by locdang8** [comment]
@kba-odoo pls review for me

**Comment by locdang8** [comment]
@kba-odoo

**Comment by phwa-odoo** [comment]
@tivisse

**Comment by locdang8** [comment]
@tivisse pls review for me

**Comment by tivisse** [comment]
@locdang8 Thanks for the feedback.

On the other hand, no need to be so hasty. This is not a critical bug, this is actually a functional improvement. Nobody's house is currently burning ^^

@robodoo r+

**Comment by tivisse** [comment]
@robodoo r- 

@locdang8 There a typo actually (a whitespace on the label), breaking the translation. 

Could you adapt and re-target the master branch ? 

Thanks.

**Comment by locdang8** [comment]
@tivisse i fixed it, i only want fix for odoo 15 so i will still target for odoo15 branch

**Comment by locdang8** [comment]
ping @tivisse

**Comment by locdang8** [comment]
@tivisse in the master branch, i don't see this view field 
```<field name="department_id" operator="child_of"/>```

**Comment by tivisse** [comment]
Yes, you can :)

**Pull request closed without merging**
