### PR TITLE
[IMP] account: create hook to override searchbar sortings/filters

### PR DESCRIPTION
**Pull request by Yenthe666**
With this commit we can now call a hook when we want to modify the code for this route.
Before this commit the only way to modify/extend this would be by taking over a big part of the code.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@smetl could I ask you to review it? :)

**Review by jbw-odoo — APPROVED** [review]
Lgtm. But I can't r+...

**Comment by smetl** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
Thanks a lot :)

**Pull request closed without merging**
