### PR TITLE
[IMP] account: make it possible to hand over communication

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
This was a bit static and hardcoded and very odd to inherit, so I made this little changes in my branch.
Hmm, probably it would be better to extract the payment vals here instead, but I suggest this as a discussion base.

**Current behavior before PR:**
No very flexible tools to set the communication...

**Desired behavior after PR is merged:**
Communication can be handed over

@qdp-odoo @nim-odoo 
May I ask you for an opinion or suggestion how to fix this in stable? As written above taking a look now at the code the payment_vals would be the better and more consistent way to improve the inheritability

info @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
You cannot change the signature of a public method in stable. Since it is an improvement, I would suggest to target master.

**Comment by wtaferner** [comment]
@nim-odoo 
You are right, even though it is kwargs which is not dangerous at all IMHO, would you think it would be better to increase inherit-ability and flexibility through the suggested change or the extraction of the payment_vals which would be probably acceptable even with stable policy?

**Comment by wtaferner** [comment]
@qdp-odoo 
I cherry-picked this for master and changed the base. What do you think?
By now it is not possible to cover the use case for payment where you (the caller) decide what exactly you want to put into the communication (important if you are not the one who is deciding or helping the customer what to put into place...I do not remember exactly the use case, but as this is a public method based on this it would be more flexible, right?

**Comment by gdgellatly** [comment]
@wtaferner Why not just insert a `def _prepare_payment_vals` . That way rather than a narrow use case, all cases can be handled.

**Comment by wtaferner** [comment]
@gdgellatly 
Well, of course, any improvement which is improving the inheritability is better than now and I prefer your suggestion and currently wonder why I did not fix it like that. I guess this PR was just the quick fix for my issue...time was short back then and still is, but let's wait for the lead and direction of Quentin and I will follow up that we can finally close this PR/issue.

**Comment by wtaferner** [comment]
@qdp-odoo 
Any opinion on that? Would be nice to have the possiblity in v12 to be able to inherit and control the communcation.

**Comment by qdp-odoo** [comment]
bof... don't you preferably want to define a new function _get_communication() that you would be able to inherit in your custom modules?

This would be acceptable in stable

**Comment by wtaferner** [comment]
@qdp-odoo 
Thank you for your input and I adapted the PR in a way to have the maximum positive impact (inheritable, but logically unchanged) and also merge-able in stable as you said.
I would be happy that this could finally find its way into Odoo core.

**Comment by wtaferner** [comment]
@nim-odoo 
OPW-1884421

**Comment by qdp-odoo** [comment]
merged. Thanks Wolfgang!

**Pull request merged**
