### PR TITLE
[FIX] sale: fix pill variant styling

### PR DESCRIPTION
**Pull request by stcc-odoo**
Enterprise PR: https://github.com/odoo/enterprise/pull/42551

Steps to reproduce:

1. Install website_sale
2. Create product P
	- Go to Attributes & Variants tab
	- Add a line
	- Create and edit attribute "PILL"
		- Display Type = Pills
		- Add some attribute values
		- Save & Close
	- Add the attribute values in the list view
	- Save the product
3. Go to website product page

Issue:

The pills have a visible radio button inside, requiring users to click
on the radio button to change the variant. In V15, there was no radio
button, and users could click anywhere on the variant container to
change the variant.

The change in behaviour happened because the jquery code for handling
button clicks has changed. In V15 jquery, clicking a button would
trigger a change event, which would then be captured by the owl event
selector `change [data-attribute_exclusions]`, and the
`onChangeVariant` method was called.

In version 16, jQuery no longer triggers a change event when clicking
a button.

Solution:

Hide the radio input visually, then convert the variant text to a
label. When clicking on the label, the corresponding radio input
is checked.

This means that the whole button is not clickable anymore, only the
text.

opw-3185147

### CODE REVIEW

**Review by chevalierv — CHANGES_REQUESTED** [review]
Hello @stcc-odoo 

Thanks for your deep investigation on this! Kudos for the test :tada: 

FYI, you'll need to adapt your changes in saas~16.3 and higher because the product configurator was refactored in the backend. In short, no need to change anything in Sale, the new product configurator supports pills the same way. The files you changed are now in website_sale_*, you'll need to find them and apply the same diff. See https://github.com/odoo/odoo/pull/106511.

Regarding your fix, I find it a bit weird to fix a "styling" issue in javascript :/ I've taken the liberty of making a fixup in your branch to show you a different way of doing it without javascript. The only downside of my method is that customers have to click on the label (so basically any letters) but it won't work if they click on the corner of the box. IMO, I find that acceptable.

Don't hesitate to contact me if you have any questions!

Have a nice day :sun_with_face:

**Comment by stcc-odoo** [comment]
@chevalierv, I have applied the suggested changes. What do you think?

**Review by chevalierv — CHANGES_REQUESTED** [review]
Hello @stcc-odoo 

Thanks for your work on this. I quickly checked and it looks like it doesn't work in the Sales app. Can you fix that?

Have a nice day :sun_with_face:

**Comment by stcc-odoo** [comment]
Hi @chevalierv! I have just checked the Sales app. When selecting a different variant for a product, the variant is changed correctly, but the UI doesn't update with the correct classes. In website_sale, the UI update is accomplished by the `_changeAttribute` method.

The Sales app behaviour was not modified by my fix, this was the case before too. I will look into a way to solve it, but this seems like a different issue, and could be solved in a different PR.

**Review by chevalierv — APPROVED** [review]
LGTM :+1: 

Thanks for you work on this :)

Have a nice day :sun_with_face:

**Comment by Feyensv** [comment]
@robodoo delegate=chevalierv

**Comment by chevalierv** [comment]
@robodoo r+

**Pull request closed without merging**
