### PR TITLE
[IMP] project,sale_{project,timesheet}: rename "canceled" to "cancelled"

### PR DESCRIPTION
**Pull request by MissingNoShiny**
This PR renames the remaining occurrences of "canceled" to "cancelled".

Task-3713873

### CODE REVIEW

**Comment by damrOdoo** [comment]
looks good to me, didn't find any occurence left :mag_right:

**Comment by MissingNoShiny** [comment]
Indeed, I missed it somehow, thanks!

**Review by xavierbol — COMMENTED** [review]
LGTM, thanks for your work. 🙂 

robodoo r+

**Comment by xavierbol** [comment]
robodoo r+

**Pull request closed without merging**
