### PR TITLE
Update badges in README.md for v9.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tvibliani** [comment]
Why cla check has been unsuccessful?

**Comment by xmo-odoo** [comment]
@tvibliani because you created this change via the github web interface, which sets the `committer` with an address `@users.noreply.github.com` rather than the one in the Delta Comm CLA which you use for your local commits. And thus the committer field fails the CLA check.

**Comment by tvibliani** [comment]
@xmo-odoo thanks for clarification

**Comment by tvibliani** [comment]
CLA issue fixed in #10904

**Pull request closed without merging**
