### PR TITLE
[FIX] account: invoice_payments_widget company_name returns cannot marshal None unless allow_none is enabled

### PR DESCRIPTION
**Pull request by fernandoslim**
…arshal None unless allow_none is enabled

Description of the issue/feature this PR addresses:
When uses External API to fetch an invoice, if this invoice it's paid and the 'partner' hasn't 'company' return None instead False

Current behavior before PR:
TypeError: cannot marshal None unless allow_none is enabled

Desired behavior after PR is merged:
Should return an object with invoice_payments_widget as attribute.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rugo-odoo** [comment]
Thank you for you contribution.

I am not sure I see the problem that this pr solves, can you please explain in more details ? What are you trying to do and why ?

**Comment by fernandoslim** [comment]
Hi, sure, I am implementing Odoo in our organization. one part of our workflow is that our app that it is use for sales our products must create a sale on odoo using the external api, after invoice got paid, when I try to fetch that invoice through External API I faced "TypeError: cannot marshal None unless allow_none is enabled", after digging in odoo code I realized that this line "'company_name': counterpart_line.journal_id.company_id.name if counterpart_line.journal_id.company_id != move.company_id else None," has the bug, after change None to False, fetch invoice works as expected.

**Comment by rugo-odoo** [comment]
I'm sorry but it seems that the error comes from your code. You will have to adapt it to take `None` instead of `False`. You have to understand that I can't change it as it will create errors on others people implementations.

I will close this PR, feel free to re-open it if I misunderstood something.

**Comment by fernandoslim** [comment]
@rugo-odoo it is odoo issue not my code, I'm connecting to external api using xmlrpc node and this is the full error ?'m facing from my odoo 17 instance on odoo.sh:
{
    "code": 1,
    "faultCode": 1,
    "faultString": "Traceback (most recent call last):\n  File \"/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py\", line 147, in xmlrpc_2\n    response = self._xmlrpc(service)\n  File \"/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py\", line 128, in _xmlrpc\n    return xmlrpc.client.dumps((result,), methodresponse=1, allow_none=False)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 981, in dumps\n    data = m.dumps(params)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 514, in dumps\n    dump(v, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 536, in __dump\n    f(self, value, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 589, in dump_array\n    dump(v, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 536, in __dump\n    f(self, value, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 607, in dump_struct\n    dump(v, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 536, in __dump\n    f(self, value, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 607, in dump_struct\n    dump(v, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 536, in __dump\n    f(self, value, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 589, in dump_array\n    dump(v, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 536, in __dump\n    f(self, value, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 607, in dump_struct\n    dump(v, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 536, in __dump\n    f(self, value, write)\n  File \"/usr/lib/python3.10/xmlrpc/client.py\", line 540, in dump_nil\n    raise TypeError(\"cannot marshal None unless allow_none is enabled\")\nTypeError: cannot marshal None unless allow_none is enabled\n"
}

**Comment by rugo-odoo** [comment]
Alright, I did misunderstood something :smiley:. Can you please squash your commits and make sure they respect our guidelines so the runbot is green ?

Other than that, LGTM (cc @william-andre)

**Review by william-andre — COMMENTED** [review]
Hello,

Can you squash your commits? One for the CLA and one for the actual diff.
Check for the CI [`ci/style`](https://runbot.odoo.com/runbot/build/58029509) in the checks at the bottom of the PR's conversation.
It needs to follow our [commit message guidelines](https://www.odoo.com/documentation/17.0/contributing/development/git_guidelines.html#commit-message-structure)

While this fix is valid, note that it is better to specify the fields that you actually need to avoid computing useless information.
Less network traffic, less server CPU, less database locks, everyone happier :wink: 

Unless you really need this one field, but I would seriously doubt it

**Comment by fernandoslim** [comment]
like this?

**Comment by william-andre** [comment]
You have 7 commits now :grimacing: 

Maybe try this
```
git fetch origin 17.0
git reset --hard origin/17.0
git cherry-pick 06064f314d6df47c5e5c6493b4c6dabb753a198b
git cherry-pick 580a7917715a6abc60cd6f356a345a9552d15591
git push dev --force
```

You might have to adapt some of these to your configuration, mainly the remotes.
You might also want to use `rebase` instead of `merge` in the future when working on Odoo :wink:  

If you still don't get it, I can cherry pick your commit myself.

**Comment by fernandoslim** [comment]
Thank you! I've just learned that 'cherry-pick' command, hahaha. I really believe I am a very good programmer, but I am pretty bad at using git 😅.

**Review by william-andre — APPROVED** [review]
You can also use a range of commits if you have to cherry pick multiple commits in one command

Thanks for the patch!
The CI is currently failing but I believe it is non deterministic and not linked to this so I just rebuilt it (there will be a warning, don't worry)
@robodoo r+

**Comment by william-andre** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
