### PR TITLE
[FIX] mail: unblacklist with mass mailing


### PR DESCRIPTION
**Pull request by nle-odoo**
The optimization 2ccf0bd0dc does not take into account that to
"unblacklist" a user, you have the archive the mail.blacklist record so
only mail.blacklist active records need to be taken into account.

opw-2536304

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Note that original commit was done in 13 (I think). And don't forget tests :D  #thatguy

**Review by nle-odoo — COMMENTED** [review]
robodoo r+

**Comment by tde-banana-odoo** [comment]
Hello,

Tests are quite low-level and actually don't ensure much ... Could you improve them to use available tools ?

**Comment by tde-banana-odoo** [comment]
@robodoo r-

**Comment by tde-banana-odoo** [comment]
I think we could at least test generated traces state, should already be higher level. Not completely sure what are available tools in 13, but at least checking traces should be quite easy to do .

Thanks !

**Comment by nle-odoo** [comment]
done, it was already done for blacklist but I had not seen the test in test_mass_mailing

robodoo r+

**Pull request closed without merging**
