### PR TITLE
[13.0][FIX] mrp_subcontracting: Consume after producing

### PR DESCRIPTION
**Pull request by pedrobaeza**
With previous code, the call to super is done before doing all the producing stuff, so the consumption takes place before the stock is available. This is not a problem if you don't have any kind of negative stock levels control, as first a negative quant is created, and when the production is done, the negative quant is neutralized.

But if you start using the OCA module `stock_no_negative`, then the negative stock exception raises, and you are not able to finish the subcontracting reception.

Swapping the super call order, means another thing: the backorder is created after the producing code, so we need to filter out the lines that are not being received.
    
A new test has been included for checking the partial reception flow.

@Tecnativa TT31389

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@amoyaux Can you please take a look to this?

Another fix coming soon.

**Comment by pedrobaeza** [comment]
It turns out that this has a side effect, as the picking hasn't extracted the non received lines, so we have to exclude them in the code that processes the production orders, but a test has been included for checking the situation.

**Comment by kos94ok-3D** [comment]
Try to remove this part of the code:
image

**Comment by pedrobaeza** [comment]
Thanks for the tip. Aren't we causing a problem with that? Why it should be removed?

**Comment by kos94ok-3D** [comment]
As I understand, when we do overprocess for subcontract receipt and then close subcontract MO it is needed in order to set new qty to produce in Subcontract MO.
But when we first close subcontract MO and then close subcontract receipt it is already done and not needed.
So this part duplicate overprocessed quantity.

**Comment by pedrobaeza** [comment]
@kos94ok-3D your reasoning seems correct. Thanks.

@amoyaux this one is ready.

**Comment by C3POdoo** [comment]
Dear @pedrobaeza,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
