### PR TITLE
[FIX] purchase: remove price from RFQ mail

### PR DESCRIPTION
**Pull request by abla001**
To Reporduce
=============
- Create RFQ and send it by mail

Problem
=======
The received mail contains the amount which we don't want to show when it's just a RFQ

Solution
=========
to solve the issue a condition was added to show the amount only on Purchase Order

opw-2955758

### CODE REVIEW

**Comment by abla001** [comment]
@adwid

**Review by adwid — COMMENTED** [review]
I'm not sure I understand why we don't want the price. Besides that, if the user clicks on `Confirm` (in the mail), he will be redirected to the portal view of the RfQ and this view also displays the price. I guess that either we cancel this PR, or the portal view needs to be updated too
I let you check this with the logistic team

**Comment by abla001** [comment]
@adwid I discussed with the Product Owner, not all Vendors have the access to the portal so it's Ok to have the price on the portal, but not on the email. He confirms to remove it from the email

**Comment by abla001** [comment]
@amoyaux @Whenrow @svb-odoo can you review this PR, thnak you :pray:

**Comment by Whenrow** [comment]
robodoo r+

**Pull request closed without merging**
