### PR TITLE
[FIX] account: Fix update of taxes from templates method

### PR DESCRIPTION
**Pull request by clbr-odoo**
We were only looking for active templates while we also want to update inactives ones (we often set them inactive to avoid confusing the user with too many taxes but they're still relevant.)
We are now also checking and updating inactive account.tax.template.

Related: #108571

### CODE REVIEW

**Comment by jco-odoo** [comment]
@fw-bot up to saas-15.3

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by clbr-odoo** [comment]
@robodoo retry

**Comment by d-fence** [comment]
robodoo retry

**Pull request closed without merging**
