### PR TITLE
[FIX] website_sale: fix contrast in color select for not available red

### PR DESCRIPTION
**Pull request by ap-wtioit**
Description of the issue/feature this PR addresses:
In website_sale shop if a product color variant is not available it is marked with a red cross. This is barley or not at all visible for colors in the red spectrum.

Current behavior before PR:
All unavailable color variants are marked with a red cross.
screenshot from 2019-01-22 08-27-26

Desired behavior after PR is merged:
We make sure that we the cross is visible by using black border for the red cross.
screenshot from 2019-01-24 08-34-38

This pull request is a simpler solution for https://github.com/odoo/odoo/pull/30419 as discussed with  @seb-odoo , if this one is accepted https://github.com/odoo/odoo/pull/30419 can be closed.

Info @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@pedrobaeza 
Feel free to do a PR, but don't forget to mention why we ended up in this change. Because of a non-thought contrast issue. 
Personally I think the methods to compute the luminance and the contrast should go into `odoo.tools` or similar and should be (re)used. It is like the dependency tree algorithm which is often forgotten. Of course for demo and standard they may not be used yet, but could be used for debug or design information.

It is all about handicapped people basically and yes, red on red was just too obivious for us and black borders are probably having the better contrast as white is the rest of the standard page background.

@JKE-be @qsm-odoo 
What do you think about reusing the methods (slightly rewritten) to provide debug information for the admin users or any user taking advantage of the web editor without a sense for contrast and luminance? :smile: 
But, yeah, not 100% sure how to embed this usefully (if we do resolve issues like this PR simplification suggests, but at least we should remember later that this might be helpful at some point.

**Comment by qsm-odoo** [comment]
I closed PR https://github.com/odoo/odoo/pull/30419 but the work may still be considered for master.
I'd say this PR with black borders is a nice enough stable fix. I'll get the opinion of @seb-odoo and @JKE-be and come back with decision.

**Comment by JKE-be** [comment]
ok for me in 10.
And to improve in master with better image/contrast

**Comment by JKE-be** [comment]
we are monday ;) @Cocographique

**Comment by wtaferner** [comment]
We are Thursday ;-) @Cocographique @JKE-be

**Comment by JKE-be** [comment]
we are monday ;) @Cocographique

**Comment by rdeodoo** [comment]
What should we do with this one?
Everyone seemed happy with this fix for stable?

In master we will have a new design that should fix this, but that's another debate.

**Comment by rdeodoo** [comment]
@Cocographique @JKE-be told me you might have a branch in stable for this?

If yes, let's merge either your PR or this one or none.
Of no, let's merge this one, or close it and leave the behavior like that for stable.

**Comment by rdeodoo** [comment]
Sorry for the multiple messages.
After further discussion, we decided to not fix it in stable as we don't want to impact existing ecommerce just to fix this red use case.
Note that in master, this is going to be fixed with an incoming improvement regarding the shop design.

**Pull request closed without merging**
