### PR TITLE
 [FIX] point_of_sale: global discount taxes 

### PR DESCRIPTION
**Pull request by hugho-ad**
In this commit we fix the tax calculation
when applying a global discount in PoS.

Before this commit, when applying a discount
tax was calculated properly only in the use
case where in one order we had:
- products with a single one tax

After this commit, the calculation of discount
and taxes is extendeted to include these additonal use cases:
- products with more than one tax applied to them ex. Product A -> 10% + 20%
- products with different taxes in the same order ex. Product A -> 10%
      Product B -> 20%
- products with taxes that are included in prices ex. Product A -> 10% (included in price) + 20%

Overall, we tried to follow a general approach
that will include as many use cases as possible
and every combination between them.

task-2421429

closes odoo/odoo#90505

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JVegaB** [comment]
Code reviewed, this one LGTM +1

**Comment by trj-odoo** [comment]
After discussing, it's ok to backport this fix into 15.0
@fw-bot up to saas-15.2

@hugho-ad runbot is red tho

**Comment by hugho-ad** [comment]
@trj-odoo 

Done!

**Comment by trj-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
