### PR TITLE
[FIX] iap: add club-internet.fr to generic emails

### PR DESCRIPTION
**Pull request by kawkb**
same as: https://github.com/odoo/odoo/pull/159321

opw-3786308

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kawkb** [comment]
Hello @lobaudoux can you please check this, it is the same as the one you r+ here https://github.com/odoo/odoo/pull/159321

**Comment by lobaudoux** [comment]
Hello @kawkb ,
The commit message should be updated to match this diff.

**Comment by kawkb** [comment]
Hello @lobaudoux thank you for your QUICK review, is it better now?

**Review by lobaudoux — APPROVED** [review]
LGTM
@robodoo r+

**Comment by lobaudoux** [comment]
@robodoo retry

**Comment by tde-banana-odoo** [comment]
Haha, club internet :D

**Comment by tde-banana-odoo** [comment]
Bring back caramail !

No offense for club internet. Well.

**Comment by kitan191** [comment]
@robodoo delegate+

**Comment by kawkb** [comment]
@robodoo r+

**Comment by kawkb** [comment]
@robodoo retry

**Pull request closed without merging**
