### PR TITLE
l10n_fr: add missing accounts + add reconcile models

### PR DESCRIPTION
**Pull request by alexis-via**
These accounts were present in odoo 8 as view accounts without children, but were removed in 9. This PR re-create these accounts.

If you want to make sure that these accounts exists, you can check https://fr.wikipedia.org/wiki/Plan_comptable_g%C3%A9n%C3%A9ral_(France)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bealdav** [comment]
:+1: 
thanks to add this, I need it for my next project

**Comment by hparfr** [comment]
👍

**Comment by mart-e** [comment]
Hello,

Thanks for the PR and the reviews.
You say it was removed in 9.0 (any idea why?) but your PR is for version 10. Is that correct?

**Comment by fpodoo** [comment]
Martin, we reviewed CoA of most countries to keep only most frequent
accounts. Our goal with default CoA is not to provide all accounts but a
minimum set. Since most companies import their own CoA, it's easier to add,
rather than removing accounts.

**Comment by alexis-via** [comment]
@mart-e It was removed during v8 -> v9 because these accounts were "view" accounts and didn't have any children. I just propose to re-create those accounts to have a full French chart of accounts.
This PR should later be backported to v9. I never worked on accounting on v9, but I now work on accounting on v10, that's why I find this issue only now and that's why I propose this PR for v10 for the moment.

@fpodoo l10n_fr has always provided all the accounts of the official French chart of accounts. This PR only creates 5 missing accounts on a total of 717 accounts, so it's a really minor addition to have a complete chart of accounts.

**Comment by fclementic2c** [comment]
We had this approach for Switzerland since the Chart is not mandatory but for France let's put the whole chart as we always did. No one has ever complained as far as I know.
:+1:

**Comment by qdp-odoo** [comment]
although I agree with fp on the principle, I think it won't hurt to put 5 more accounts.

the part with account.reconcile.template is nice! but I wonder about the utility of 
* customers/suppliers buttons: since if there's a partner the default is the receivable/payable accounts if no line is selected in case of debit/credit.
* internal transfer button: since there's a dedicated feature embedded in V9 that handles the internal transfers so that you should select a blue line (and thus not use a button that would create a new entry).

**Comment by alexis-via** [comment]
@qdp-odoo I took into account your remarks ; I was not aware of these features (I'm still pretty new on accounting on v9/10).
About the button for "internal transfer", it exists on l10n_be, cf https://github.com/odoo/odoo/blob/10.0/addons/l10n_be/data/account_reconcile_model_template.xml#L25

**Comment by qdp-odoo** [comment]
ha yes... indeed :-p

well well, I might remove that from the belgian localization then ^^

**Comment by alexis-via** [comment]
@qdp-odoo I think we are ready-to-merge now, no ?

**Comment by alexis-via** [comment]
This has been merged in v10, so I close this PR.

**Comment by qdp-odoo** [comment]
ha yes, thank you for being cleaner than I am ^^

**Pull request closed without merging**
