### PR TITLE
[FIX] doc: theme tutorial

### PR DESCRIPTION
**Pull request by ggros**
Description of the issue/feature this PR addresses:
Theme tutorial updated to work in odoo 12

Current behavior before PR: 
2 blocking errors documented in:
https://stackoverflow.com/questions/53160591/extending-default-template-odoo-12/53162439#53162439
https://stackoverflow.com/questions/41061604/odoo-10-how-to-create-snippets-javascript-option#41062045

Desired behavior after PR is merged:
Tutorial works in odoo 12

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@Feyensv

**Comment by Feyensv** [comment]
At first glance, the content update looks good to me.  I'll take a second look soon (and maybe ask the responsible team to confirm).

Could you please update your commit messages according to our [contribution guidelines](http://www.odoo.com/documentation/master/reference/guidelines.html#git) ?  Thanks.

**Comment by ggros** [comment]
> 
> 
> At first glance, the content update looks good to me. I'll take a second look soon (and maybe ask the responsible team to confirm).
> 
> Could you please update your commit messages according to our [contribution guidelines](http://www.odoo.com/documentation/master/reference/guidelines.html#git) ? Thanks.

I updated the commit messages. Let me know if that works

**Comment by ggros** [comment]
> > At first glance, the content update looks good to me. I'll take a second look soon (and maybe ask the responsible team to confirm).
> > Could you please update your commit messages according to our [contribution guidelines](http://www.odoo.com/documentation/master/reference/guidelines.html#git) ? Thanks.
> 
> I updated the commit messages. Let me know if that works

@Feyensv  Any news ?

**Comment by Feyensv** [comment]
Thanks for the reminder :+1:
I just retested and everything works fine.
Waiting for a last input from a colleague and I'll merge this PR (this week ;)).

**Comment by Feyensv** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
