### PR TITLE
replace fa-spinner with fa-circle-o-notch

### PR DESCRIPTION
**Pull request by msh-odoo**
PURPOSE
Slightly improve the overall UI of Odoo with a more modern feel by updating the current 'loading' icons that look quite old school.

SPEC
Across all modules: update fa-spin fa-spinner into fa-spin fa-circle-o-notch

TASK 2346142

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by aab-odoo — APPROVED** [review]
You can squash commits in both PRs.

**Comment by msh-odoo** [comment]
> You can squash commits in both PRs.

@aab-odoo Done, Thanks.

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
@msh-odoo CI failed on this one

**Comment by msh-odoo** [comment]
@aab-odoo Branches are green now.

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
