### PR TITLE
[9.0]Fix move operation link creation

### PR DESCRIPTION
**Pull request by florian-dacosta**
Description of the issue/feature this PR addresses:

In a picking, when we have several lines with the same product but a different restrict_lot_id, the stock.move.operation.link are not correct in case of partial delivery.
The problem is that we modify a list here : https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L1382
On which we are looping here : https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L1462
The consequence is that the list decrease and not all the move are treated.

Current behavior before PR:

If we make a partial delivery of a picking with several lines of the same product but restrict_lot_id differents, the moved quants may have a different lot than the stock.move restrict lot id.
The problem is that if we have a chained picking with the restrict lot id, it will be stuck at state 'waiting for another move' for ever. Indeed, the history of the quant and its lot don't correspond to the chained move.

Desired behavior after PR is merged:

If we make a partial delivery of a picking with several lines of the same product but restrict_lot_id differents, the moved quants have the same lot that the move restrict lot id.

In order to easily reproduce the bug, I have added a test in the community module sale_order_lot_selection.
You can find the branch with the new test here : https://github.com/akretion/sale-workflow/tree/9-sale_lot_selection-add-test.
Just play the test of the module sale_order_lot_selection of this branch to reproduce the bug.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Hi Florian,

I guess the point of your `[:]` is to create a new instance of the array.

If this is indeed what you were looking for, then wrapping the array with `list` is cleaner / easier to understand:

`list(prod2move_ids.get(ops.product_id.id, []))`

Do you agree ? I can then proceed with the merge of your proposal.

Regards,

**Comment by florian-dacosta** [comment]
@beledouxdenis 
Sorry I did not see your reply...

I agree and I made the change. thanks!

**Comment by florian-dacosta** [comment]
Hello @beledouxdenis 
Is it possible to merge it now? Indeed, it would be nice to see this fix in next versions!
Thank you

**Comment by florian-dacosta** [comment]
I'll just close as it won't ever be merged since the version 9 is not maintained anymore and this object has been removed in version 11 anyway.

**Pull request closed without merging**
