### PR TITLE
[13.0][IMP] stock: add hook to control lot creation on incoming shipments

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Nothing changes functionally with this PR, it is just a hook to improve extensibility of the code and control the lot creation from stock move lines.

@ForgeFlow

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
ping: @ryv-odoo @sle-odoo

**Comment by LoisRForgeFlow** [comment]
Hi @ryv-odoo and @sle-odoo,

Is it possible that you consider the addition of this hook?

Thanks!

**Comment by amoyaux** [comment]
Hello. Sorry, we only allow this kind of hook for master version.

**Comment by LoisRForgeFlow** [comment]
> Hello. Sorry, we only allow this kind of hook for master version.

Thanks for you answer, I have created the master version: https://github.com/odoo/odoo/pull/80314.

**Comment by ticodoo** [comment]
Merged in https://github.com/odoo/odoo/pull/80314

**Pull request closed without merging**
