### PR TITLE
[FIX] project: open the Tasks Analysis and customer rating report in project burger menu

### PR DESCRIPTION
**Pull request by ppr-odoo**
task-3345839

### CODE REVIEW

**Review by MissingNoShiny — COMMENTED** [review]
LGTM, thanks for the fix :slightly_smiling_face:

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work. 🙂 

robodoo r+

**Comment by xavierbol** [comment]
robodoo r-

**Comment by xavierbol** [comment]
Can you backport your fix in 16? Since the comma you removed is there from 16.

Thanks in advance! 🙂

**Comment by ppr-odoo** [comment]
> Can you backport your fix in 16? Since the comma you removed is there from 16.
> 
> Thanks in advance! slightly_smiling_face


Done. Sorry for the delay. Thanks

**Comment by xavierbol** [comment]
Thanks 🙂 

robodoo r+

**Pull request closed without merging**
