### PR TITLE
14.0 czsk jco

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by oco-odoo — CHANGES_REQUESTED** [review]
Very minor style things in XMLs.
More importantly, please split the commit between l10n_sk and l10n_cz, and respect the guidelines for the CLA ([CLA] ....)

**Comment by jco-odoo** [comment]
@oco-odoo Changes appied

**Comment by jco-odoo** [comment]
@oco-odoo

**Review by oco-odoo — APPROVED** [review]
@robodoo r+

**Comment by oco-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
