### PR TITLE
[FIX] web: proper display of pages headers for companies view form

### PR DESCRIPTION
**Pull request by Ephoniz**
Steps to reproduce:

1. Activate Dev mode
2. Settings > Technical > User Interface > Views
3. res.company.form
4. In the architecture add more pages `<page name="test1" string="This is a test ABC DEF"/> <page name="test2" string="This is a test ABC DEF"/> <page name="test3" string="This is a test ABC DEF"/> <page name="test4" string="This is a test ABC DEF"/> <page name="test5" string="This is a test ABC DEF"/> <page name="test6" string="This is a test ABC DEF"/> <page name="test7" string="This is a test ABC DEF"/>`
Save manually
5. Settings > Users & Companies > Companies
6. Open any company.

Issue:

Tabs go off the screen instead of moving down a row like in previous versions.

Solution:

Removing the class `flex-nowrap` from the notebook views will make the tabs to have good behavior and responsiveness.

FW-port: master

opw-3079492

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

after the change:
> 2022-12-01-164656_1187x294_scrot

before the change:
> 2022-12-01-164713_1187x290_scrot

**Comment by sdegueldre** [comment]
@bouvyd I expect you'll have a functional opinion on the topic. I think we obviously want people to have access to all the pages that are defined but the current solution definitely looks broken (even though it's more usable) and I expect we're going to get bug reports because of it.

**Comment by Ephoniz** [comment]
@bouvyd 🙏🏽 😄

**Comment by Ephoniz** [comment]
This is another possibility as an easy fix:

**Comment by bouvyd** [comment]
current solution degrades the UX in mobile (where scrolling the tabs horizontally works fine), so no
image


second suggestion seems better, though i'd advise to check the result in mobile (Contact form view is a good quick test)

**Comment by Ephoniz** [comment]
After the fix in PC:

image

After the fix in Mobile:

image

**Comment by sdegueldre** [comment]
Current implementation breaks the fact that the selected tab looks continuous with the notebook content. Maybe some of our css experts can take a look at how to fix this while preserving that? cc @pparidans

**Comment by sdegueldre** [comment]
@pparidans did you get time to take a look?

**Comment by dipak-shah** [comment]
@pparidans @sdegueldre @Ephoniz @nka-odoo when this going to deploy/merge in production ? its been long since this raised and no update i see from last 2 weeks.

**Comment by Ephoniz** [comment]
@sdegueldre @pparidans I think we can finally close this 🥲 The behavior with the current changes will keep the UX in mobile and will also fix desktop.

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo r-

@Ephoniz I'm not sure to know which solution has been decided, but the current implementation doesn't seem to fix anything. I just tried on [this runbot](https://30512211-16-0-all.runbot153.odoo.com/web?debug=assets#id=65&cids=1&menu_id=135&action=178&model=res.partner&view_type=form) and trailing tabs aren't accessible. What am I missing?

**Comment by Ephoniz** [comment]
@aab-odoo 🙂

**Comment by outmanadev** [comment]
Not sure if I can contribute here, but I reported this bug (probably with others too :-)).  For what it's worth, I think the horizontal scrollbars are more annoying than seeing a few lines of tabs stacked below each other.  I don't like horizontal scrollbars and find it very old-fashioned design and not user friendly.   At least on desktop.  On mobile, scrolling through tabs is maybe ok.  On desktop I would prefer the stacked lines of tabs rather than horizontal scrollbars.

**Comment by aab-odoo** [comment]
I have to say I agree with @outmanadev 

I didn't understand I could scroll, even though I know the shift-scroll feature. But I believe that a lot of people using Odoo have no clue how to do that. @bouvyd sorry to bother you again with this, but I'd like you to reconsider. I won't fight, so if you say go for it I can r+, but please give it a second thought.

**Comment by outmanadev** [comment]
Hi all, when will this be available please ?
thanks,
Seppe

**Comment by dipak-shah** [comment]
it's been 5+ months since this issue was raised. please help by resolving and concluding something here. appreciated all of your efforts here.

**Comment by hubvd** [comment]
@aab-odoo I discussed with @bouvyd yesterday and the conclusion is that we want to go with an horizontal scrollbar as it wouldn't be ideal on mobile devices to have stacked tabs.

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
