### PR TITLE
[FIX] website_crm_partner_assign: fix the random weighted choice algorithm

### PR DESCRIPTION
**Pull request by std-odoo**
Bug
===
If 2 partners have the same weight, the first partner will
have 2 times more chance to be chosen.

Task 2246367

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@tfr-odoo Any thoughts ?

**Comment by tfr-odoo** [comment]
@tde-banana-odoo Seems fine, I thought this issue was solve for months. 
Why not use random.choices instead of this homemade implementation ?

**Comment by std-odoo** [comment]
> @tde-banana-odoo Seems fine, I thought this issue was solve for months.
> Why not use random.choices instead of this homemade implementation ?

`random.choices` only exists since python 3.6, I think it was one of the reason

**Comment by tfr-odoo** [comment]
The fix is for the master, I think we do not support python < 3.6, it's seems the perfect time to make the change, isn't it ?

**Comment by std-odoo** [comment]
@tfr-odoo Indeed, so we can use it :) Done & pushed :)

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
