### PR TITLE
[REF] *: utility classes

### PR DESCRIPTION
**Pull request by stefanorigano**
Refine and adapt BS default utility classes.

These modifications/addition have been made in consideration of the SCSS that was not possible to remove during the optimization/restyle, task-2704984.

task-2918463

enterprise:
- https://github.com/odoo/enterprise/pull/30066

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @pparidans , I have still to clean the branch, but you can already have a look ;)

**Review by pparidans — COMMENTED** [review]
Looks good :sunglasses: 

I let you cleanup, just ping me when you're ready

**Comment by stefanorigano** [comment]
> Looks good 😎
> 
> I let you cleanup, just ping me when you're ready

@pparidans , PING!
Thanks

**Comment by stefanorigano** [comment]
@brc-odoo , FYI

**Comment by pparidans** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
