### PR TITLE
[FIX] l10n_es: We change the reconciliation of accounts

### PR DESCRIPTION
**Pull request by mem-adhoc**
Adhoc-ticket-side: 80347

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This change is not correct. They should be reconciliable for finding existing open balances in the reconciliation screen

**Review by rafaelbn — COMMENTED** [review]
This change is not correct.

The description is completely empty with no explanation.

**Review by yosuanicolaus — COMMENTED** [review]
Hello, can you explain more what you are doing in this PR?

**Comment by yosuanicolaus** [comment]
Need more explanation and reasoning. Unless more discussion, we'll close the PR for now.

**Pull request closed without merging**
