### PR TITLE
[FIX] point_of_sale: computation of included fiscal pos

### PR DESCRIPTION
**Pull request by pimodoo**
When you hava a fiscal position that that map one tax included into the
price to another, the new amount is wrong.

I we have a fiscal position that map a tax of 10% included to 20%
included, and a product at 110$ having 10% included. When we map the tax
from 10% to 20%, the new price is 100$ but should be 120$.

This is because for now, the price is fixed to get the amount without
tax, which perfectly works when destination tax is tax excluded. But
when you call compute_all from a price with a tax included (20%) it keep
the price and compute the tax amount out of this price.

So to fix this issue, whent the origin tax and destination tax are
included, we are computing the base amount (like before) and then we
compute the new tax amount wihtout trying to find the tax amount out of
the price.

This will lead to have the same behavior between accounting and POS
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pimodoo** [comment]
@nim-odoo @smetl Could you have a look

**Comment by nim-odoo** [comment]
Up to now, we were considering this use case not supported (map an included tax on another included tax), except in the case of a destination tax of zero. For example, your use case fails in a SO.

AFAIK, we are considering making the tax computation uniform in all models (SO, PO, Subscriptions, Invoices...), but the target is 15.0. The other advantage would be to have a consistent computation of tax grouping in round globally.

**Comment by pimodoo** [comment]
@nim-odoo Ok, but as this behavior is the same (and the correct one) in accounting, and that the mixin to unify computation through sale,subscription,... will never be applied in POS as it is a javascript implementation. Can I merge it here and forward-port it to master.

P.S. if you want I can have a look at Sales, to fix it there too (if it's possible)

**Comment by nim-odoo** [comment]
ok for me if you want to apply to the PoS. However, I'd leave the other apps as they are.

**Comment by pimodoo** [comment]
@nim-odoo ok, thank you

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
