### PR TITLE
[IMP] Anonymization improvement

### PR DESCRIPTION
**Pull request by leblanc-simon**
Description of the issue/feature this PR addresses: 
- allow to anonymize HTML fields
- improve default field to anonymize

Current behavior before PR: add a HTML fields to the list of fields to anonymize throw an exception

Desired behavior after PR is merged: HTML fields are allowed
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

The improvements are supposed to be for master, however here I can consider the changes for HTML fields and res_users.name as fixes as the export will not with default data (and it's quite safe).
By the way we also probably remove the outdated models like all the `training...` or `res.partner.contact`.

However, not sure to add the emails. It is already a very slow process and adding something as huge as emails will make it quite unusable. I don't think it's a good idea.

**Comment by Yenthe666** [comment]
@mart-e any update on this one? If it is added we can also close my issue. :+1:

**Comment by mart-e** [comment]
Thanks, I have merged the changes at
ec005af [FIX] anonymization: default anonymization fields - Simon Leblanc
45483b9 [FIX] anonymization: allow anonymization on HTML fields - Simon Leblanc
42aa79d [CLA] Sign CLA of leblanc-simon - Simon Leblanc

As said above the emails is too big to be by default. Anyway it is configurable.

**Comment by leblanc-simon** [comment]
Thanks for your commit.
Could I expect this pull request will be backported into 8.0 branch ?
Must i create a new pull request ?

**Comment by mart-e** [comment]
@leblanc-simon we do not backport the commits automatically to previous versions (we actually [do the opposite](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch)), as your PR was for 9.0 this is were I merged it.
I will backport it but for the next PR try to submit in the lowest first.

**Comment by leblanc-simon** [comment]
OK.  Thank you very much

**Pull request closed without merging**
