### PR TITLE
[IMP][l10n_ec]:modificando la moneda de la empresa

### PR DESCRIPTION
**Pull request by LeonhardCoder**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

Could you give a bit of context for this change?
I understand the Ecuador is no longer using its own currency but USD?
@jco-odoo is this a safe change for 12.0?
Maybe we should deactivate the currency in master too

**Comment by mart-e** [comment]
Also, it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by jco-odoo** [comment]
@mart-e It should not affect stable as it is in the chart template.  If this is the reality, then we should change it.

**Comment by celm1990** [comment]
@mart-e  Is complementary to PR #27398

**Comment by mart-e** [comment]
Ok, if @victor016 agrees to sign the CLA, it is fine with me to merge it

**Comment by OsirisRoman** [comment]
@mart-e the merge was blocked because of the CLA signature was not well done?

**Comment by mart-e** [comment]
@OsirisRoman indeed, it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by jco-odoo** [comment]
It is USD in master now, so I suppose this is ok

**Pull request closed without merging**
