### PR TITLE
[IMP][14.0] account: Add hook method for

### PR DESCRIPTION
**Pull request by tranngocson1996**
This PR
-------
After paying the expense report, the lines are reconciled right away but with this old code I can't inherit the custom reconciliation lines. So I provide a hook method to be able to inherit and customize the lines that want to be reconciled.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tranngocson1996** [comment]
@kba-odoo I did this PR related PR #81267 in expense module. What do you think?
@qdp-odoo @FlorianGilbert I know you are in charge of the accounting module. Can you review it?
Thank you bro !!!

**Comment by william-andre** [comment]
What kind of customization would you like to do in that hook?

**Comment by tranngocson1996** [comment]
@william-andre As described I would like to be able to customize the lines to reconcile for my purposes. But with this code I can't do it. So I want to add a hook method and I know it won't affect the business

**Comment by william-andre** [comment]
@tranngocson1996 As asked: What kind of customization would you like to do in that hook?

Adding hooks everywhere makes the code harder to read/refactor. I would really like to avoid it if possible.

**Comment by tranngocson1996** [comment]
> Adding hooks everywhere makes the code harder to read/refactor. I would really like to avoid it if possible.

@william-andre I know so. But if the code is like this, the custom people cannot inherit it.
In my opinion, the hook method should still be added, because in many cases I don't want to reconcile immediately after the payment or partially reconcile. That's why I did this PR

**Comment by tranngocson1996** [comment]
@william-andre Moreover, this method `_create_payments` is quite large, when you want to customize anything inside, it is very difficult to do

**Comment by william-andre** [comment]
> But if the code is like this, the custom people cannot inherit it.

Again. What kind of customization would you like to do in that hook?

**Comment by davidtranhp** [comment]
> > But if the code is like this, the custom people cannot inherit it.
> 
> Again. What kind of customization would you like to do in that hook?

I think there would be some situations that one does not want to reconcile the payment with all the payable lines of the related expense. For example, a payable line that will be reimbursed with payslip (in Payroll app) and the rest get done with `account.payment`.

**Comment by william-andre** [comment]
> For example, a payable line that will be reimbursed with payslip (in Payroll app) and the rest get done with `account.payment`.

That is just a partial payment/reconciliation, isn't it? I really feel like you don't know what you are trying to do, and it should not be done the way you want to do it.

**Comment by davidtranhp** [comment]
> > For example, a payable line that will be reimbursed with payslip (in Payroll app) and the rest get done with `account.payment`.
> 
> That is just a partial payment/reconciliation, isn't it? I really feel like you don't know what you are trying to do, and it should not be done the way you want to do it.

Following this https://github.com/odoo/odoo/pull/81267, I thought he did it in `hr_expense`. I'm sorry.

**Comment by tranngocson1996** [comment]
@william-andre ok thank bro. I understood the problem

**Pull request closed without merging**
