### PR TITLE
[FIX] web_editor: create attachment on hover effect modification

### PR DESCRIPTION
**Pull request by loco-odoo**
[FIX] web_editor, *: create attachment on hover effect modification

*: website

Steps to reproduce:
- Add an image on the website.
- Add an "On Hover" animation.
- Save and edit.
- Change the animation effect (i.e. from "Overlay" to "Outline").
- Save.

-> Problem: although the image options have been modified, there is no
new attachment created for this modified image and its src is still the
raw data.

The problem appears since [1] as the `_reapplyCurrentShape()` method
replaces `_applyOptions()`. Due to this, the `o_modified_image_to_save`
class is not added anymore on the image when changing hover effect
options such as "effect", "color", "intensity", and "stroke width". To
solve the problem, the class is added back on the image when changing
such options. Thanks to it, the system creates a new attachment linked
to the modified image at the editor save.

[1]: https://github.com/odoo/odoo/commit/5d83672e0aac40d3484ee45f348dfca5de8f186a

task-3820127

--------------------------------------------------------------------------------------------------------------------------------------------------------------

[FIX] website: reapply original source on hovered image in edit mode

Steps to reproduce the bug:
- Add an image on the website and add an animation of type "On Hover" on
it.
- Save and edit.
- Click on the image to load its options.
- Save.

-> Problem, the image src is the raw data.

When the user clicks on the image, the `ImageHandlerOption` snippet
option is started. Because the image has an hover effect, the
`_refreshPublicWidgets()` method is called. Due to it, the
`ImageShapeHoverEffet` public widget is restarted. The problem is that
because the src of the image has been modified in the `_applyOptions()`
method of the `ImageHandlerOption`, the src of the image will not be
replaced by the original one at the `destroy()` of the
`ImageShapeHoverEffet` public widget. At the re start of this public
widget, `this.originalImgSrc` will be set to a base 64 source. At the
save of the editor, the public widget is destroyed and the image source
is set to those raw data. Because the image has not been modified, it
keeps it as a src after the save of the editor. To solve the problem,
the `destroy()` method of the `ImageShapeHoverEffet` has been adapted to
correctly set the source of the image when it has not been modified. To
do so, the `originalSrcBeforeHover` attribute is used to keep track of
the original image src. It is needed for example if a user applies a
filter on the animated image and then clicks on 'undo'; at the filter
application, `ImageShapeHoverEffet` is destroyed. Because the image has
been modified, the src of the image will not be replaced by the original
one. Without the `originalSrcBeforeHover` attribute, the original src
would be lost and it would not be possible to reset the src to the
original if the user clicks on 'undo' and then save.

task-3820127

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo delegate=bso-odoo 
@bso-odoo 

/!\ The two commits have different task-XXX... normal?

**Comment by loco-odoo** [comment]
> /!\ The two commits have different task-XXX... normal?

Ouie, no, my bad, it is mistake, I has now been corrected

**Comment by bso-odoo** [comment]
@robodoo r+

**Comment by bso-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
