### PR TITLE
[FIX] website_mail: better support for broken outlook

### PR DESCRIPTION
**Pull request by nle-odoo**
This fix is about three issue of office oulook:
- a fixed table width must be in pixel, using 100% of parent div width
  doesn't work,
- a background-color on a div is not used, the background color should
  be on the table inside this div using the attribute "bgcolor",
- the only way to center a table is to have a `<center>` tag arround it,
  or have an element arround it with "text-align: center".

The two first are straightforward, but for the third, given this property:
- in non-outlook: all the snippet are centered (since there is always `"margin:auto"`),
- in outlook: only a small part of the snippet with text-align:center or `<center>`
  arround them are centered.

So to choose the lesser refactoring, this commit unify the outlook
behaviour by having all of them left aligned.

opw-650217

**PR NOTE**:

to test, i used this code in the mass mailing editor iframe:

``` javascript
$('.note-air-editor').addClass("oe_drop_zone");
var sleepTime = 0;
$('.oe_snippet').each(function(){
  $('<h2 />').text($(this).attr('class').replace(/ .*/,'') + " >>> " + $(".oe_snippet_thumbnail", this).text()).prependTo($('.oe_snippet_body', this));
  sleepTime += 600;
  setTimeout(function() {
    openerp.Tour.autoDragAndDropSnippet($('.oe_snippet_thumbnail', this));
  }.bind(this), sleepTime);
});
setTimeout(function(){ $('.note-air-editor').removeClass("oe_drop_zone"); console.log('the end'); }, sleepTime + 100);
```

to click on every snippet.

### CODE REVIEW

**Comment by beledouxdenis** [comment]
da fuck xD

**Comment by wtaferner** [comment]
Contenance, Denis ;-)

**Comment by beledouxdenis** [comment]
Well, at first sight, it seems ok to me.

I guess you have tested this for Outlook, as well as for other clients ? GMail ? Thunderbird ?

Specifically, is `width="600"` instead of style="width: 600px;" compliant with these other clients ?

If so, to me, you can merge :).

**Comment by nle-odoo** [comment]
I mainly tested in `gmail`/`office outlook` but I have now tested it further in thunderbird and outlook.com

when doing so, I stumbled uppon another issue:

for the widget background image with a code like this:

```html
 <div name="Background Image" class="cleave o_mail_block_text_on_img">
     <div class="snippet_row bg-color" style=" padding:0px;width:600px;margin:auto;background: url('/website_mail/static/src/img/theme_imgs/skyline_bg.gif') top /cover;background-repeat:no-repeat;color:#fff">
        <table cellspacing="0" cellpadding="0" style="border-collapse:collapse;color:inherit" width="600">
```

the image was only shown for thunderbird.

* not shown on gmail: since is like `url('/relative_url.gif')`,
* not shown in office outlook: I tried multiple way but didn't manage to display a background image in any of those way,
* not shown in outlook.com: from my test, a background image is only showed if it is in an attribute `background="http://absolute_image_url.jpg"`

I added a commit ([link](https://github.com/odoo-dev/odoo/commit/ed1b08d91b6d035f6934e379235b7930cbc50e02)) so it works on gmail and thunderbird and on:

- outlook.com: we get a background color (taken from the image),
- office outlook: we get a background color,

**Comment by beledouxdenis** [comment]
> and I hesitate if the change in addons/mass_mailing/models/mail_mail.py is too much if not present we would also get a background color instead of the background image in gmail.

I do not believe this is too much:
 - This is good to do it in post-processing, so if you change of domains (from abc.com to def.com), it will still works without having to change each mailing/pages.
 - Replacing the background by a color is not enough to me: It's likely that users will want to be able to display photos as background, to be able to write text on their images. It won't be good to not support such a thing on GMail, one of the most used email client.

To me, both your commits are correct. I let you choose wether it's better to squash your commits or not  when you will merge in stable :).

Good work !

**Comment by beledouxdenis** [comment]
Olivier just had a look to your regex, and he suggests to change it for
```
(<[^>]+\bstyle="[^"]+\burl\(\'?)(/[^/\'][^\'")]+)
```
It's a bit more efficient, as well as a bit easier to understand.

**Comment by nle-odoo** [comment]
merged with https://github.com/odoo/odoo/commit/a14f89c86

**Pull request closed without merging**
