### PR TITLE
[IMP] hr: remove administrator employee

### PR DESCRIPTION
**Pull request by jorenvo**
Task: https://www.odoo.com/web#id=19616&view_type=form&model=project.task&action=327
Pad: https://pad.odoo.com/p/r.aSQyULesdtZ6QttD

### CODE REVIEW

**Comment by mart-e** [comment]
Why? Please, always specify a link (public and readonly) to the related task or at least describe your fix.

**Comment by jorenvo** [comment]
Sorry about that, fixed.

**Comment by mart-e** [comment]
No problem, but I meant the public url to the pad (I have added it), only Odoo employees have access to tasks

**Comment by jorenvo** [comment]
Oh, ok didn't know about that. Also added pad links to my other PR's. Thanks!

**Pull request closed without merging**
