### PR TITLE
17.0 - l10n il 18 percent tax rate - Backward-Port-Of V18

### PR DESCRIPTION
**Pull request by hedshefer**
Israel is raising VAT rate from 17% to 18% on 1/1/2025.

Changes:

Added new taxes (17% -> 18%)
Archived 17% taxes
Added tax group (VAT 18%)
Modified fiscal position to match those taxes
Modified VAT report to include VAT Inputs 18%
Updated default tax ids for IL res.company

Backward-Port-Of: https://github.com/odoo/odoo/pull/191209

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hedshefer** [comment]
@william-andre 
Backward port of https://github.com/odoo/odoo/pull/191209

**Comment by william-andre** [comment]
@robodoo r+ fw=saas-17.4

**Comment by william-andre** [comment]
@robodoo r+ up to saas-17.4

**Comment by hedshefer** [comment]
@william-andre merged for 17.0?

**Comment by william-andre** [comment]
Yes, with the commit referenced by robodoo just above
https://github.com/odoo/odoo/commit/3ae60373fdb306f8a5e85721fb284de3561c63ce

**Pull request closed without merging**
