### PR TITLE
[FIX] sale_timesheet: show upsell activity mutiple times

### PR DESCRIPTION
**Pull request by kcv-odoo**
opw-4147106

### CODE REVIEW

**Comment by kcv-odoo** [comment]
Hello @xavierbol @deneuvillem 

Can you check this? backport of PR: https://github.com/odoo/odoo/pull/147552 as it seems there is no issue doing this in a 17.0 I think
 Just in case [Alternative of above solution](https://github.com/odoo-dev/odoo/commit/bd7c1cc0ad7192e5d0642400fbc5542f77557949)

Have a nice day!

**Comment by kcv-odoo** [comment]
FW-port disabled

**Comment by xavierbol** [comment]
LGTM, however, can you change the tag since it is more a bug fix. 🙂 

Thanks in advance and thanks for your work! 🙂

**Comment by xavierbol** [comment]
@kcv-odoo ping 🙂

**Comment by kcv-odoo** [comment]
Hello @xavierbol 

Done. Thank you!
Have a nice day

**Review by xavierbol — COMMENTED** [review]
robodoo r+

**Pull request closed without merging**
