### PR TITLE
[ADD] l10n_co_pos_report: extend PoS Sales Details Report for Colombia

### PR DESCRIPTION
**Pull request by bat-odoo**
TaskID - 2226101

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ren-odoo** [comment]
HI @bat-odoo 
I did te funtional testing but I'm getting this error on the module installation, can you take a look please:
image

cc. @vbe-odoo @fvz-odoo

**Comment by bat-odoo** [comment]
Hi @ren-odoo module installation error is solved you can check now.
Thanks.

**Comment by ren-odoo** [comment]
Hi @bat-odoo 

Thank you for the changes I tested it and it's working correctly. There are just some minor changes to be made on the spanish translation of the wizard, but besides of that all goog. 

@jco-odoo this PR is ready for your review.

**Comment by bat-odoo** [comment]
Move to #114154

**Pull request closed without merging**
