### PR TITLE
[FIX] account: action_invoice_paid never called on invoices

### PR DESCRIPTION
**Pull request by qdp-odoo**
This function used to be called on invoices rights after they get paid, but since the refactoring of account.invoices and account.move, it wasn't the case anymore, resulting in broken workflow/use cases (sale, event_sale...).

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@pko-odoo 
@JKE-be 

this patch is related to a problem we discussed

**Comment by smetl** [comment]
@qdp-odoo `saas-12.4`? Really? :smile: Are you stuck inside a temporal rift in which `saas-12.4` is still alive?

**Review by nim-odoo — CHANGES_REQUESTED** [review]
I don't know what is the root cause of the issue, but calling `action_invoice_paid` inside a compute method doesn't seem to be a good idea.

It is not uncommon that a compute method is called more than once during a transaction, so will be `action_invoice_paid`. And among other things, this method post messages [1] or does requests to TaxCloud [2].

[1] https://github.com/odoo/odoo/blob/adb2186a8cb2c411d5fc04bc4dfb1998424909fa/addons/sale/models/account_invoice.py#L99
[2] https://github.com/odoo/enterprise/blob/243d69bfdee5641b72f49d62960bb3ed3af44956/account_taxcloud/models/account_invoice.py#L152

**Comment by smetl** [comment]
@nim-odoo That's the purpose of checking the previous value of `invoice_payment_state`. I agree it's not very sexy but since `write` is not called with the newly computed value... which choice do we have?

**Comment by nim-odoo** [comment]
Maybe `_write` is called at some point?

If we start having compute method calling public methods, it's going to be a mess. It's the onchange problem all over again: you call a method, and you have no idea what is going to be modified. Moreover, security-wise, compute methods can be called with `sudo`, so not good.

**Comment by qdp-odoo** [comment]
> Do you have a step-by-step scenario to reproduce the problem?

make a SO, create its invoice, register the payment, look back at the SO: there's no message logged to say the invoice has been paid although the code of action_invoice_paid is doing it and should have been called at some point.

I agree that it's super weird to call that function there, but I've tried overwriting _write and it doesn't work

**Comment by smetl** [comment]
This seems to work in 13.0:

```
    def _write(self, vals):
        # OVERRIDE
        paid_invoices = None
        if vals.get('invoice_payment_state') in ('in_payment', 'paid'):
            old_payment_state_map = dict((res['id'], res['invoice_payment_state']) for res in self.read(fields=['invoice_payment_state']))
            paid_invoices = self.filtered(lambda move: move.is_invoice(include_receipts=True) and move.id in old_payment_state_map)

        res = super()._write(vals)

        if paid_invoices:
            paid_invoices.action_invoice_paid()

        return res
```

However, it forces you to make an explicit `read`.

**Comment by qdp-odoo** [comment]
target changed to 13.0 in new PR https://github.com/odoo/odoo/pull/44005

**Pull request closed without merging**
