### PR TITLE
[FIX] Adding __init__.py that addons are detected via rootpath and might be ...

### PR DESCRIPTION
**Pull request by wtaferner**
...imported without using the virtual openerp.addons path directly

Maybe someone can explain why addons tree is not already moved/merged with openerp/addons, but temporarily this might help people who like physical links...

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Hello Wolfgang, 

I am not able to understand what solves this issue. Can you be more specific about the issue ?

Regards,

**Comment by wtaferner** [comment]
Hi Denis,
I am not an expert about path in python but as we have a natural path of ```addons/module``` the __init__.py does help to recognize all directories under addons as python modules.

I know that there is the virtual path where all the modules are added and registered, but it is very helpful for example using Eclipse pydev to have also a pythonic way to find packages like the modules (subdirectories) without running the Odoo logic itself. 

Maybe you can talk to your Python experts if this kinda makes sense for them...at least it does not hurt and this is why I suggested it a long time ago and actually used it since then without troubles ;-)

Regards,
Wolfgang

**Comment by beledouxdenis** [comment]
The addons path isn't a python module, the folders in the addons folder are.

This is similar to the dist-package folder of Python (/usr/lib/python2.7/dist-packages).

Indeed, IDEs may not like this, but we won't make that change for an IDE.

Thank you for your contribution anyway :).

**Comment by wtaferner** [comment]
Ok, thank you for taking this to a decision on your side...I will keep it for making use of its advantages even just for IDE reasons ;-)

**Pull request closed without merging**
