### PR TITLE
DB Restore via XMLRPC Error Fix!!

### PR DESCRIPTION
**Pull request by manishbisht94**
Description of the issue/feature this PR addresses: #26893

Current behavior before PR:Backing up is fine. But restoration gives error as the temporary file's name(being used to store the given backup path) is passed instead of passing it's content The function doesn't read the real file name passed in request correctly and ends with error.

Desired behavior after PR is merged:The content of the temporary file(i.e the absolute path of the backup file given via "restore" rpc command) should be passed.That is what happens when backup is restored via console. 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Elkasitu I think you are the proper one for checking this

**Comment by manishbisht94** [comment]
Thanks for the update.

I do agree that `restore_db ` function expects a string as its dump_file arg which should/is the absolute file path of backup. `restore_db` function works perfectly as this is called also when backup is restored via browser interface.  But my concern is about `exp_restore(db_name, data, copy=False)`  which further calls `restore_db` for restoration when xmlrpc is used instead of web interface. 

`exp_restore` function breaks the input absolute file path(encoded) into chunks & decodes the chunks. Then it writes them to a temporary file, then it passes this temporary file path to `restore_db` function as the backup file path. Rather it should pass the content of temporary file to `'restore_db`. Afterwards, the `restore_db` processes the temporary file as backup file & ends with error. 
The same can be observed in logs too.

**Comment by Elkasitu** [comment]
Actually, that is not the case and I've just realized why that does not work, it's partly due to the poor documentation of restoring via xmlrpc.

the `data` parameter of the `exp_restore` function expects **the base64-encoded contents of the dump** and not the path to it, the contents are stored in a temporary file which will then be used in restore_db like any other normal dump.

**Comment by manishbisht94** [comment]
I had this in mind. 
But then i thought sending a large db dump over via xmlrpc should not be a good practice.
Anyway, doing my trick will let you restore the database via xmlrpc if backup is kept locally.

Thanks!!

**Pull request closed without merging**
