### PR TITLE
[IMP] core: use option type as default metavar

### PR DESCRIPTION
**Pull request by Julien00859**
People don't understand how to read the --help message, we had a case where someone reported that "--without-demo is broken" because they literally used "--without-demo=WITHOUT-DEMO" in their CLI and got the warning "'WITHOUT-DEMO' is not a boolean value, assume True".
    
In this work, the opton type is now used as the default metavar, i.e. for without_demo it now prints `--without-demo=BOOL` in --help.

### CODE REVIEW

**Comment by Julien00859** [comment]
@robodoo rebase-ff

**Review by lordkrandel — COMMENTED** [review]
I've had a look at the thing and this is what comes to mind, feel free to disagree.

I see that we have several types of options that allow for CSV fields, but it's only clear when you read the description (and not in 100% of cases)
immagine

So why don't we have "{type.upper()}_CSV" as a default metavar for those, without having to manually write it?
Also, we could check whether MODULES and FEATURES are valid already.

immagine

**Comment by Julien00859** [comment]
What's about

```
-i MODULE,MODULE,...
```

**Comment by Julien00859** [comment]
@robodoo r+

**Review by lordkrandel — APPROVED** [review]

**Pull request closed without merging**
