### PR TITLE
[FIX] website: fix wrong string interpolation

### PR DESCRIPTION
**Pull request by rdeodoo**
Without this, the website selector was not working

### CODE REVIEW

**Comment by rdeodoo** [comment]
@JKE-be Small typo making the website selector not working with the new string interpolation :eyes: 
Also, I'd like to revert the change about the selected view highlight, I think yellow was more useful. Blue is more beautiful but you can barely see it, not practical IMO.
But I can live without it :) I can revert that part if you want let me know, the important part is the typo.

Also for next iteration: not only bulk delete but also select correct website not always website 1 (eg you come from a view from website 2 (or maybe generic ?))

**Comment by qsm-odoo** [comment]
@robodoo r+

At least it is fixed, if we want to re-change the design, we can do it later again

**Comment by JKE-be** [comment]
@robodoo retry

**Comment by JKE-be** [comment]
@robodoo r-

need to be done in 14.3

**Comment by JKE-be** [comment]
@robodoo r+

**Pull request closed without merging**
