### PR TITLE
[FIX] l10n_es: add more logic to l10n_es_is_simplified compute

### PR DESCRIPTION
**Pull request by Arnaud-Sibille**
If you don't have enough information about your customer, the invoice should be made simplified.

opw-3679325

### CODE REVIEW

**Comment by Arnaud-Sibille** [comment]
Hello @jco-odoo :)

This is the logic I think we could implement to make an invoice simplified automatically

**Comment by Arnaud-Sibille** [comment]
@jco-odoo

I understand, but I still think something needs to be done, because if the user post an invoice for a spanish customer without vat, he is stuck with that error msg from the SII:
`[1168] El valor del CodigoPais solo puede ser ES cuando el IDType sea 07 o 03. Si IDType es 07 el CodigoPais debe ser ES`
which is not really helpful.

Here what the user has to do is to reset his invoice to draft (this will cancel his reconciliation), activate the "Simplified Invoice" and re-post.  It is not ideal and he must understands this.

What do you think about it?

Maybe we could at least make a hint in case of sii failure that he can switch to simplified invoice?  and make the field readonly if the invoice has been accepted by the edi (for the moment is readonly if the `state != 'draft'` (in the form view))?

**Comment by chklop** [comment]
@Arnaud-Sibille @jco-odoo 
On a functional level, the "is simplified invoice" should not be editable on posted invoices. This is a significant change on the invoice as you change the way that invoice is declared to the government, so it's normal to reset your invoice if you need to change that.

Now, there might be another issue is how those invoices are created. Because they probably should have been created as Simplified directly. I guess from the ticket this comes from "Amazon" ? What does that mean, from the eCommerce, or Sales app ? 

Those apps should have a way to trigger the creation of simplified invoices, if tagged as such.

**Comment by Arnaud-Sibille** [comment]
@chklop 

Yes they are created from sale orders created from Amazon.
Do you mean create a bridge module between amazon and the spain localization?  like it was one with pos with `l10n_es_pos`?

**Comment by chklop** [comment]
@Arnaud-Sibille Yes, if a module needs to automatically create invoices in countries where specific requirements needs to be implement, then yes a bridge module is needed. We have done something almost exactly the same for l10n_mx who has bridge modules for sales and pos to handle a very similar requirement (named "CFDI invoice to public").

**Pull request closed without merging**
