### PR TITLE
[FIX] web_editor: various shape fixes (hide on mobile, bad joint, ...)

### PR DESCRIPTION
**Pull request by sdegueldre**
This commit fixes various things with the shapes: shapes are now hidden
on mobile by default, the shapes "blobs 02" and "blobs 03" now connect
properly, and the shape pager now shows the name of the current page.

task-2319484

### CODE REVIEW

**Comment by sdegueldre** [comment]
@JKE-be since qsm is on holiday for two weeks it's probably best if you take a look instead :)

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo retry

**Pull request closed without merging**
