### PR TITLE
[IMP] requirements: adapt to debian bullseye

### PR DESCRIPTION
**Pull request by d-fence**
With the release of Debian Bullseye and as the Odoo policy is to stick
as close as possible to python3-* Debian packages versions, the time as
come to adapt the requirements.

### CODE REVIEW

**Review by xmo-odoo — APPROVED** [review]
:+1: maybe re-sort the file while at it? Since some of the dependencies got added at the end instead of where they belong.

**Comment by d-fence** [comment]
> +1 maybe re-sort the file while at it? Since some of the dependencies got added at the end instead of where they belong.

Yes, I was thinking about that too, but it will add a bit of noise when blaming ...

**Review by odony — APPROVED** [review]
Thanks, that works for me :+1: 

@robodoo override=ci/security  (`sys.version_info` is a false positive)

**Comment by d-fence** [comment]
robodoo retry

**Comment by d-fence** [comment]
The staging failed for a good reason. The branch odoo-dev:master-reqs-bullseye-hirsute-moc was configured to test with a Hirsute Dockerfile (Python 3.9). The good news is that the tests were green.
But the staging tests against the current Ubuntu LTS (Python 3.8) and Pillow fails.

**Pull request closed without merging**
