### PR TITLE
[IMP] hr_expense: Add dashboard for My Expenses

### PR DESCRIPTION
**Pull request by jbm-odoo**
taskID: 2198487

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Hello @jbm-odoo 

I believe these numbers should be updated on Removing filters.

image

**Comment by jbm-odoo** [comment]
Hello @sswapnesh ,

This box is a summary of all your expenses (for which you are waiting to be reimbursed), like a personal dashboard. It isn't impacted by the filters of the view.

**Comment by sswapnesh** [comment]
>It isn't impacted by the filters of the view.

Yes but it can Create confusion 

Eg, like this one where values are Updated based on Filters

image

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
