### PR TITLE
[FIX] web_editor: prevent media selection during search

### PR DESCRIPTION
**Pull request by dmo-odoo**
~~When changing media sources filter (All, Illustrations, ...), the~~
~~list of media is regenerated since the results may be different. If~~
~~the user clicks on one media at the right time after changing the~~
~~sources filter (not too fast but not too slow either) it is possible~~
~~to select a media which id is out of sync with the new state of the~~
~~widget, thus prompting `_onAttachmentClick` to provide `undefined`~~
~~to `_selectAttachment`, which ultimately leads to a traceback in~~
~~`_highlightSelected` when accessing `media.id`.~~

~~This commit fixes the traceback by avoiding to call `_selectAttachment`~~
~~when the attachment or media was out of sync with the state of the~~
~~widget and therefore could not be found.~~

When updating the results following a change in the search filter or the
source sources filter (All, Illustrations, ...), the list of media is
regenerated to match the new results. If the user clicks on one media at
the right time after the search is triggered (not too fast but not too
slow either) it is possible to select a media which id is out of sync
with the new state of the widget, thus prompting `_onAttachmentClick` to
provide `undefined` to `_selectAttachment`, which ultimately leads to a
traceback in `_highlightSelected` when accessing either `media.id` or
`attachment.id` depending on the case.

This commit fixes the issue by disabling pointer interactions with
the attachments during the search and rendering update process.

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@rdeodoo I investigated for a few minutes and found a quick fix for the traceback. It might not be the best fix, however. Basically I'm ignoring the selection of a media if it is done while rendering the new results as the media that was being selected is not part of the widget internal state anymore. A better fix IMO would have been to validate the modal with the selected media, regardless of the fact that we decided to change the sources filter a few milliseconds ago. However, doing that would have required me to allocate more resources to investigate this bug further. I let you decide if you think the fix in this PR is enough or if you prefer to have someone from your team actually solve the internal state inconsistency issue.

**Comment by dmo-odoo** [comment]
@rdeodoo I investigated for a few minutes and found a quick fix for the traceback. It might not be the best fix, however. Basically I'm ignoring the selection of a media if it is done while rendering the new results as the media that was being selected is not part of the widget internal state anymore. A better fix IMO would have been to validate the modal with the selected media, regardless of the fact that we decided to change the sources filter a few milliseconds ago. However, doing that would have required me to allocate more resources to investigate this bug further. I let you decide if you think the fix in this PR is enough or if you prefer to have someone from your team actually solve the internal state inconsistency issue.

**Review by rdeodoo — COMMENTED** [review]
Thanks :+1: 

I could only reproduce the error once out of 30+ tries. The flow required to face the error seems like it needs to be hard stress testing the feature, and not at all a legit end user flow.

So I think your fix is fine in that regard.

Since the issue occurs when `_renderThumbnails()` is being processed and the user clicks on an element (`_onAttachmentClick()`) in the meantime.
I guess we could have either:
- Added a loading during `_renderThumbnails()` (bad ux)
- Added a `pointer-events: none;` on those attachment during `_renderThumbnails()`

If I am getting this right, it should work?

I think it would be more clear and explicit that those `if ()` condition (that will need to be commented IMHO if they were to be kept).
It would also be fixing the root cause instead of the consequence.

Let me know if you agree and if you do, if you want us to finish it if you don't have time

**Comment by dmo-odoo** [comment]
Following our discussion on Discord, we chose to disable all user interactions with attachments during the rendering process by setting `pointer-event: none` on the attachments container.

**Review by rdeodoo — APPROVED** [review]
@robodoo r+
Thanks for the changes and having investigated

**Pull request closed without merging**
