### PR TITLE
[IMP] sale_timesheet: Add non billable task

### PR DESCRIPTION
**Pull request by jbm-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by KangOl** [comment]
I don't understand this PR.
Why adding a new field, if it is unused and not fillable (no view defined)

And the commit message don't explain the rational being the addition of this field.

**Comment by jbm-odoo** [comment]
Hello @KangOl, this PR was initially made to insert a stored field before the freeze. Now all the rest of the code is also present in this PR.

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo +

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
