### PR TITLE
Master website multi sig

### PR DESCRIPTION
**Pull request by antonylesuisse**

### CODE REVIEW

**Comment by Xpiva** [comment]
Where can I download this addon?

**Comment by Xpiva** [comment]
I would like to have 1 database with multiple companies each with their own websites. Each website would have its own look and feel along with its own products. Some companies and websites would share products. I have tried to test this in version 9, however I don't see how it switches between the domains. In Settings > Websites > Create and Edit I have created the different domain names and pointed them to the appropriate company
ex: Company A => Website A, Company B => Website B, and Company C => Website C. however when I try to load the different domain names, they all seem to go to the 1st website view. What have I done wrong? seems pretty simple, however just not working for me yet.

**Comment by jholze** [comment]
Also look under marketing-->website domains. This settings section looks much better.

**Comment by Xpiva** [comment]
I'm confused, how does Marketing --> website domains work?
How does it automatically switch between the different domain names, and how do you customize the look and feel for the different domain names

**Comment by lukebranch** [comment]
@jholze ,

Have you noticed any changes that would allow different theme modules to be used for different websites?

I've had a good look around, but I can't seem to find any functionality that accomplishes this yet in master.

**Comment by Xpiva** [comment]
seems simple but yet not so much, looks like you create a static database, then different websites in the marketing --> website and it should point to it automatically when reading the url to that database, however not working, not showing the different website.

Am I doing something wrong? the functionality seems to be there but I cant get it to work

**Comment by jholze** [comment]
@lukebranch i didn't know if you can run different themes per website. The setup for multi websites is already working and we are currently implementing it in a portal project. I will ask our odoo dev robert, because as i know, he wrote an article about the new themes. coming back soon ...

**Comment by lukebranch** [comment]
@jholze ,

Thanks. I have a feeling the architectural challenges of assigning certain modules to certain domains requires some heavy restructuring, but i'd be interested to take a look at how it's done in master if some work has been done already on this.

**Comment by jholze** [comment]
@lukebranch i think you're right :-) but at the end odoo can delimit from other ecommerce systems like magento or oxid with such features. Also the Versioning works really well, but just for normal pages. Product pages, for example, are not supported at the moment. 

I asked @simongoffin if there are already plans to implement the versioning for dynamic views like website_sale or blog.

**Comment by lukebranch** [comment]
@jholze ,

I haven't tested out the versioning yet, but it looks very useful. Hopefully some of those versioning features will also be able to be used in mass mailing for A/B split testing for newsletters as well.

I'll be creating a dev instance of Master and SaaS 6 next week so that I can take a look at some of the new features in more detail.

Unrelated; have you heard of any developments on a revision history module for static, or dynamic pages (eg. similar to the functionality of post revision history in Wordpress 4+)? 

I was thinking of getting a project started on this if no one else is working on it, as this feature in wordpress is a useful tool for publishers and could definitely come in handy for Odoo CMS.

**Comment by Xpiva** [comment]
I do not understand the point of having multiple websites under marketing if you can not have a different look and feel for each one including a different logo and products.

ex: website A sells Pet food, and website B sells Computer Products.

Also is there clear instructions of exactly how this should be set up?

Thank you in advance

Xpiva

**Comment by Xpiva** [comment]
does anyone have any clear instructions on setting this up so that I can have multiple companies with multiple websites in 1 database?

**Comment by Xpiva** [comment]
can any one help with this feature please?

**Comment by jholze** [comment]
Hi @Xpiva i ask our developer Christoph to write a small blog post on our bloopark blog bloopark.de/blog

Regards,

Holze Jens

**Comment by lapagept** [comment]
I'm also really interested by this for my odoo 8.

**Comment by Xpiva** [comment]
the website is down for the link you provided, can you please update the link

**Comment by jholze** [comment]
@Xpiva link should work now :-)

**Comment by Xpiva** [comment]
I was looking for the blog post, but I cant find this one. Do you have a direct link?

Thank You :)

**Comment by francesco-carrella** [comment]
Hello!
Any news for that topic?

**Pull request merged**
