### PR TITLE
[FIX] copy_menu_hierarchy method should be api multi.

### PR DESCRIPTION
**Pull request by atp-odoo**
Description of the issue/feature this PR addresses:

**copy_menu_hierarchy** method called from private method **_bootstrap_homepage** (which is private method) by default api multi and method **copy_menu_hierarchy** also use recordset(self). so it should be api multi decorator instead of model and as it is not an orm function(defined only on website) no need to explicitly declare api multi. 

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
And I'd personally add `@api.multi` instead of the `@api.model` for transparency, even if it is used by default.

**Comment by dbo-odoo** [comment]
@Yenthe666 
no; if it's the default, it would not add it... `api.one` is going the way of the dodo anyway, the loop is explicit enough

**Comment by Yenthe666** [comment]
@dbo-odoo https://www.python.org/dev/peps/pep-0020/#id3
"Explicit is better than implicit." + "Readability counts."
Just my five cents 😄

**Comment by dbo-odoo** [comment]
@Yenthe666 
5¢ duly noted

i stick to my point though, end of discussion for me otherwise it's gonna be a bikeshedding discussion :)

happy holidays!🎄

**Comment by Yenthe666** [comment]
@dbo-odoo no worries, we both made our point right? 😉 I just wanted to share it. Thanks for the feedback.
Enjoy your holidays too & keep up the good work! 🎄

**Comment by dbo-odoo** [comment]
robodoo r+

**Comment by dbo-odoo** [comment]
@rdeodoo could you merge this plz? I'm not a mergebot reviewer it would seem

**Comment by dbo-odoo** [comment]
@robodoo your commitment to access rights is commenbale

**Comment by rdeodoo** [comment]
@dbo-odoo I cant summon robodoo either
I am still trying to make him listen to me but it takes time

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by dbo-odoo** [comment]
@rdeodoo 
strange, you're marked as a reviewer (and self reviewer) on runbot...

**Comment by mart-e** [comment]
f92cddcf1c52cde9e1bc954fed8bdddea3970bfc fixed the runbot so you need to rebase to get a green runbut and get robodoo to merge your patch

**Comment by atp-odoo** [comment]
rebase done!!

**Comment by mart-e** [comment]
robodoo r+

**Comment by dbo-odoo** [comment]
merge!

**Comment by mart-e** [comment]
robodoo r+

**Comment by dbo-odoo** [comment]
well that was easy

**Comment by mart-e** [comment]
Before the mergebot, I lost so much time clicking on the merge button, but that in the past now :+1:

**Comment by dbo-odoo** [comment]
so easy

**Pull request closed without merging**
