### PR TITLE
[REF] web_tour,*: use the registry in collecting the tours

### PR DESCRIPTION
**Pull request by caburj**
This is a step closer to a goal of avoiding dependence on asynchronous
modules. Starting from this commit, new tour definition should be
registered to `registry.category("web_tour.tours")` registry.

So, instead of the following:

```js
import tour from "web_tour.tour";
tour.register(name, options, steps);
```

We now do:

```js
import { registry } from "@web/core/registry";
registry.category("web_tour.tours").add(name, optionsWithSteps);
```

Notice the `options` and `steps` params are merged when registering
the tour definition. It should look something like so:

```js
registry.category("web_tour.tours").add("account_tour", {
  test: true,
  steps: [ ... ],
});
```

And if the `TourManager` instance is needed, one can get it from the
registry like so `registry.get("tourManager")`. Note however that
this instance is only available when the `TourManager` has been
instantiated -- so it's not available at top level of the module.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
@robodoo override=ci/security
All CI checks are triggered by a reindentation of a line with markup.

**Comment by tde-banana-odoo** [comment]
@robodoo r-

Most likely breaking the mergebot (all tours are failing due to an issue in timeoff). Sorry if it is a false positive, just trying to dépatouille a bissect frenzy ^^ .

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
