### PR TITLE
v10 [FIX] allow to unlink resource.calendar.attendance from …

### PR DESCRIPTION
**Pull request by bealdav**
... resource.calendar
## Description of the issue/feature this PR addresses:

Make 'resource calendar' and 'resource calendar attendance' consistent
Attendance are only attached to resource.calendar, then it makes sense.
## Current behavior before PR:

When I remove a resource calendar, linked resource calendar attendance **are not** removed
## Desired behavior after PR is merged:

When I remove a resource calendar, linked resource calendar attendance **are** also removed
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

Thanks to study it.

### CODE REVIEW

**Comment by bealdav** [comment]
replace https://github.com/odoo/odoo/pull/10310

**Comment by hparfr** [comment]
👍

**Comment by rvalyi** [comment]
:+1:  cc @Yenthe666

**Comment by mourad-ehm** [comment]
+1

**Comment by bealdav** [comment]
Hi @rco-odoo @mag-odoo,

Could you consider this really small fix.

Thanks

**Comment by bealdav** [comment]
ping @rco-odoo @mag-odoo, PR move from master to v10.

Thanks to review this really small fix

**Comment by bealdav** [comment]
ping @rco-odoo please just a small review

**Comment by bealdav** [comment]
ping @rco-odoo we are thursday and it's the day of my PR, thanks

**Comment by bealdav** [comment]
@rco-odoo any news about it, 
I have pushed this PR in v9. 
https://github.com/odoo/odoo/pull/10310

Fabien asked me to push in master. Nobody to review in master or v10.

Could you make a review ?

Thanks

**Comment by bealdav** [comment]
@odony please could you have a look on this.
Thanks

**Pull request closed without merging**
