### PR TITLE
[FIX] web: avoid most problems with quotes in search

### PR DESCRIPTION
**Pull request by Polymorphe57**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
The main problem is clearly that the tokenization of strings does not handle backslash escapes and this should really be fixed if we're going to have those as input: py.js matches single-quoted strings as `'([^']*)'` but Python's own tokenizer matches `'[^\n'\\]*(?:\\.[^\n'\\]*)*'`, so handles `\'` properly. However that means the parser then needs to "de-escape" the string according to Python's escaping rules:


Escape Sequence | Meaning
-- | --
`\\` | Backslash (`\`) 
`\'` | Single quote (`'`) 
`\"` | Double quote (`"`)
`\a` | ASCII Bell (BEL)
`\b` | ASCII Backspace (BS)
`\f` | ASCII Formfeed (FF) 
`\n` | ASCII Linefeed (LF)
`\r` | ASCII Carriage Return (CR) 
`\t` | ASCII Horizontal Tab (TAB)
`\v` | ASCII Vertical Tab (VT)
`\ooo` | Character with octal value ooo
`\xhh` | Character with hex value hh
`\N{name}` | Character named name in the Unicode database
`\uxxxx` | Character with 16-bit hex value xxxx
`\Uxxxxxxxx` | Character with 32-bit hex value xxxxxxxx

The first three should definitely be supported, the others should either be supported or trigger a proper error.

According to json.org's description, it *should* work for serializing strings back, though the specifics of what it picks might vary between implementation (and its quoting is the reverse from Python's default: Python's `repr` uses single quotes while JSON mandates double quotes). Either way, JSON's escapes seem to be a strict subset of Python's:
```
character
    '0020' . '10ffff' - '"' - '\'
    '\' escape
escape
    '"'
    '\'
    '/'
    'b'
    'n'
    'r'
    't'
    'u' hex hex hex hex
```

**Comment by aab-odoo** [comment]
As far as i understand, this is ok.

@xmo-odoo What do you think?

**Comment by xmo-odoo** [comment]
@aab-odoo I think the "de-escaping" should happen during proper parsing / tokenisation, and should ideally be the proper interpretation of escape sequences. It should not be a hack / workaround in _formatAST.

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
