### PR TITLE
[FIX] website: prevent loop if auth=user route used  as homepage url

### PR DESCRIPTION
**Pull request by rdeodoo**
One can very well select a "auth=user route" as homepage for his website, like /my.

There would then be an issue with such an URL being set as homepage:
- As the user landed in the homepage controller which is auth=public, the system will add the public user as env user (see `_auth_method_public()`).
```
@http.route('/', type='http', auth="public", website=True, sitemap=True)
def index(self, **kw):
```
- Then, that controller will reroute to the homepage url (/my). The request.httprequest.path will now be /my
- Then, that controller will recall the dispatcher stack: `request._serve_ir_http()`
- From there, this call won't fail as it should because the user is considered as logged in as it went already through the `_auth_method_public()`, adding the public user as env.user. `_auth_method_user()` won't raise its error.
- The /my page will be rendered despite not being logged in.

Once the user land on that page, the system will actually detect him as logged out on a page supposed to be accessed when logged in. It will then:
1. Show a toaster to inform the user
2. Auto reload the page

As the current URL is still `/` (due to the reroute and not a redirect), the same flow will happen again, and again, looping forever.

--------

Note that accessing /my directly won't be an issue, as it won't go through the homepage controller (which is auth=public), so there won't be a user_id set on the env (the public user), meaning that the dispatch layer will reject the access and raise an access error (through `_auth_method_user()`.
Also note that the same behavior will occur when going through the first menu fallback mechanism:
- if the user didn't setup any homepage_url
- and deleted his / website.page
- and his first website menu is /my

In that case, it will go through the first menu redirect fallback, which will be working fine (as it's a redirect and not a reroute). With both those 2 flows (going through redirect), the user will correctly land on the login page (which will redirect to /my once logged in).

------

Finally, the other solution would be to prevent such a configuration (/my as homepage_url) but it was not easily doable (if doable at all), see https://github.com/odoo/odoo/pull/99100#discussion_r963055251

------

TODO: A test will be added later in this commit for this complexe case
      that should cover it all:
      - With /my as homepage_url
      - With the / website.page deleted
      - With /my as first menu URL
      -> Accessing / as public user should:
      1. Reroute to /my (because of the homepage_url set to it) which
         should fail now thanks to this commit
      2. Since the reroute / re-serve failed, it should reach the
         "first menu fallback" mechanism, which is also /my
      3. That fallback should be a redirect, not a reroute, so the user
         should actually land on the login page
      4. Once logged in on that page, it should properly redirect to /my

opw-3077339

### CODE REVIEW

**Comment by rdeodoo** [comment]
Hello @Julien00859 may I have your opinion here?
That's just an idea to start discussing it if you think there is a better way.
I summarized everything I could in the commit message, it should gives a clear understanding of what's going on and why + why we didn't/don't prevent the misconfiguration upfront.

**Comment by Julien00859** [comment]
Thank you for the complete rational, it is crystal clear. That's a very interesting problem indeed.

Reading your message I had the following in mind, maybe `auth_method_user()` should not let a public user go through.
```diff
     @classmethod
     def _auth_method_user(cls):
-        if request.env.uid is None:
+        if request.env.uid in (None, request.env.ref('base.public_user').uid):
             raise http.SessionExpiredException("Session expired")
```

After some reconsiderations, maybe that's a `reroute` duty to reset `request.uid` to `request.session.uid`. We are changing the path so considering this PR's problem, we should force a new authentication using the new path.
```diff
     @classmethod
     def reroute(cls, path, query_string=None):
         """
         Rewrite the current request URL using the new path and query
         string. This act as a light redirection, it does not return a
         3xx responses to the browser but still change the current URL.
         """
+        request.env = api.Environment(request.env.cr, request.session.uid, request.env.context)
```

Alternatively, we could just add this `request.env = api.Environment(request.env.cr, request.session.uid, request.env.context)` inside of the homepage controller just after the call to `reroute`.

Writing this message I have been wondering if that was ok to reset the request's environment this late in the process. The problem is that in the case of a non-logged-in user, we would update the env with uid=None. Meaning we cannot use that environment to access any concrete (non-abstract) model until we re-authenticate. I think this consideration rules out resetting the environment inside of `reroute` as this would be a surprising side-effect. Also resetting the environment is only useful when we call `reroute` after `_authenticate` (e.g. in a controller). It's perfectly fine to leave the environment as-is when we call `reroute` before `_authenticate` (e.g. in `_match` for the lang).

**Comment by rdeodoo** [comment]
Thanks for your detailed opinion :+1: 
You can have a look at the current state of the PR, I initially went with the "the caller should take care of it by resetting the env", see https://github.com/odoo/odoo/compare/885e8aff7cad0883b08237028f12f232f25c2a6a..1ae45d6c35c350f93f632676b3a4a6581793dd4d
But finally adapted to go with the stronger `_get_public_users` solution.

I guess the local solution in website `/` controller was also covering the case of a custom auth as it was resetting everything (good), but at the same time it was not a global fix that would prevent the issue in other controllers/custo (bad).

Would have been ideal if the dispatcher was able to at least log a warning when the request was rerouted from route with a auth method different than the auth method it already went through. Probably overkill / not straightforward anyway as the `reroute` method would need to somehow retrieve the used auth method (if any) and keep that on the request somewhere while the next call to `_authenticate` in the stack would need to track if there was already a "used auth method" and check if different than the current one about to be called.
Just some thinking tho, I'll leave that up to you for later (as it wouldn't fix anything but just help detecting those point of failure)

**Comment by Julien00859** [comment]
I would had been +1 for such warning if it was common to `reroute` + `http._serve_ir_http` from within a controller. The way `reroute` is implemented makes it is *easy* to call it inside of `_match` (you match the final controller endpoint immediately and authenticate once)  and *hard* anywhere else (you have to serve again via `request._serve_ir_http` authenticating twice in total).

The website homepage is kinda an exception in this regard as it reroutes from within its controller. I am not aware of any other controller that does something similar.

> I guess the local solution in website / controller was also covering the case of a custom auth as it was resetting everything (good), but at the same time it was not a global fix that would prevent the issue in other controllers/custo (bad).

+1

Btw, it looks like that test keep failing `test_compare_list_price_price_list_display`

**Comment by rdeodoo** [comment]
> Btw, it looks like that test keep failing test_compare_list_price_price_list_display

Indeed, somehow because of this user env change in [account/tests/common.py](https://github.com/odoo/odoo/blame/a1147d91729a5eb75565f04ec10b52ed28d93c42/addons/account/tests/common.py#L58-L59) which is then used to [start](https://github.com/odoo/odoo/blame/a1147d91729a5eb75565f04ec10b52ed28d93c42/addons/website_sale/tests/test_website_sale_show_compare_list_price.py#L116) that tour.

Replacing the custom user env change/auth by `self.authenticate()` would fix the issue but is a no go since it's also used by non `HttpCase` tests. I'll check what can be done.

**Comment by rdeodoo** [comment]
If anyone wants to review and/or merge this one, appreciated

**Review by Julien00859 — APPROVED** [review]
@robodoo r+

**Comment by rdeodoo** [comment]
@robodoo rebase-ff

**Comment by rdeodoo** [comment]
@Julien00859 The knowledge perf tests were failing (eg: 16 > 15 in `test_article_tree_panel`)

I pushed [this](https://github.com/odoo/odoo/compare/cc65552625c02bc9b38f8bb2f176c91e85ae462d..d4176d12ba8be9656299b593b5e6e244e43ae271) so it's actually not doing any more request. I don't think there is a real difference between that or calling `ref()` in this case as we raise if not found, the `exists()` check in `ref()` doesn't change anything here, but it's what was causing the sql request increase.
Also, as it's quite a low level/core method, seems not that bad to avoid the extra query.

I'll let you decide, tell me if you have a better idea or if this seems not acceptable.

**Comment by Julien00859** [comment]
I was worried about the possible extra query indeed, `_xmlid_to_res_model_res_id` is fine to me

@robodoo r+

**Pull request closed without merging**
