### PR TITLE
12.0 dk jco

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@fw-bot ignore

**Comment by jco-odoo** [comment]
@oco-odoo Can you r+ or delegate?  I am already merging for 12.3 and 13.0

**Comment by jco-odoo** [comment]
@oco-odoo

**Comment by oco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
