### PR TITLE
[16.0] [FIX] point_of_sale: sudo in _check_active if stock.picking.type

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
This seems to be a [FIX] not a refactor. Can you give more info as to how this is an issue?

**Comment by caburj** [comment]
I'm okay with this change. Can you put that reason in the commit message? Also, kindly change the tag of the commit title from `[REF]` to `[FIX]`.

**Comment by ThomasBinsfeld** [comment]
> I'm okay with this change. Can you put that reason in the commit message? Also, kindly change the tag of the commit title from `[REF]` to `[FIX]`.

Thanks, done.

**Review by caburj — APPROVED** [review]
robodoo r+

**Comment by caburj** [comment]
robodoo retry

**Pull request closed without merging**
