### PR TITLE
[FIX] BBA structured communication : Wrong value in vals['reference'] in case of multiple ids in write ...

### PR DESCRIPTION
**Pull request by adrienpeiffer**
...method

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
Fix for #4700

**Comment by beledouxdenis** [comment]
Hello Adrien, 

I reviewed this PR and it looks okay. I will accept this PR as soon as:
 - You applied this same fix to the create method, just above the write method you fixed.
 - You signed the Odoo CLA: https://github.com/odoo/odoo/blob/8.0/doc/cla/sign-cla.md

Regards,

**Comment by odony** [comment]
For the record, the CLA check is OK for Adrien Peiffer, so that part is fine.

**Comment by sbidoul** [comment]
@beledouxdenis IMO the create() does not suffer the same issue because there is no loop (the problem occurs only when multiple ids are passed to write).

cc/ @adrienpeiffer

**Comment by beledouxdenis** [comment]
Closed by aac5c4798018e17fcd2d21cc56be381a1cd219b6.

**Pull request closed without merging**
