### PR TITLE
[IMP] add china city data

### PR DESCRIPTION
**Pull request by jeffery9**
add all china city data

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
I highly doubt this will be accepted. First of all it adds new data so it should be done against the master version and not 11.0
Secondly I don't even think it will make it there as it is simply way too big and too much data. Imagine if Odoo would have this for every single country, it would become a very long and heavy set of data. 

CC @mart-e as it is his final call.

**Comment by elicoidal** [comment]
@jeffery9 If not possible in Odoo directly, I suggest you open a PR in https://github.com/oca/l10n-china as a separate module with the data

**Comment by pedrobaeza** [comment]
And instead of hardcoding data, isn't better to use https://github.com/OCA/partner-contact/tree/11.0/base_location_geonames_import?

**Comment by elicoidal** [comment]
@pedrobaeza it seems that China is not available in the list of countries.
I agree it would be a better/cleaner alternative but that means to prepare/propose the China data to the project `geonames` which looks maybe not short term

**Comment by pedrobaeza** [comment]
It's a pity then. But a module in localization then it's the way to go.

**Comment by mart-e** [comment]
Thank you for the big addition!
However, we can not indeed, modify the manifest in stable version.
For master version, is it a good idea to force to use the list of cities? Is this some legal requirements?

**Pull request closed without merging**
