### PR TITLE
8.0 l10n_fr: remove old tax codes + some cleanup

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
@legalsylvain In order to be able to easily add taxes with a lower sequence (ecotax for example). If all the taxes created by default have a sequence of 1, you need to update the sequence of all the existing VAT taxes first and then you can create your ecotax...

I know it's a small detail, but it's a good practise.

**Comment by legalsylvain** [comment]
thanks for your answer and for your PR.

:+1:

**Comment by sebastienbeau** [comment]
it's ok for me :+1: (code review, no test)

**Comment by cdubuit** [comment]
:+1:  merci !

**Comment by alexis-via** [comment]
@qdp-odoo Could you merge it ?

**Comment by qdp-odoo** [comment]
merged in revision ccd2897

**Pull request closed without merging**
