### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version 

### PR DESCRIPTION
**Pull request by pro-odoo**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/a99db9a4c [REL] 17.4.0-alpha.7 Task: 0
https://github.com/odoo/o-spreadsheet/commit/d5c36cb27 [REF] dist: export o_spreadsheet as ESModule Task: 3995327
https://github.com/odoo/o-spreadsheet/commit/52fa572ef [MOV] f&r: move find & replace plugin to store Task: 3994472
https://github.com/odoo/o-spreadsheet/commit/17ba4e52f [FIX] pivot: do not allow date dimension without granularity Task: 0

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by pro-odoo** [comment]
@robodoo override=ci/style
Override because the terms which trigger the warnings are used for custom class names or directly in inlined css.

**Comment by LucasLefevre** [comment]
robodoo r+

**Comment by LucasLefevre** [comment]
robodoo rebase-merge

**Comment by pro-odoo** [comment]
robodoo retry

**Pull request closed without merging**
