### PR TITLE
[FIX] l10n_ar, l10n_cl, l10n_pe: only change invoice demo data when t…

### PR DESCRIPTION
**Pull request by jco-odoo**
…he company has the right country

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Comment by jco-odoo** [comment]
Tested this time...

**Comment by william-andre** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@william-andre I installed all 4 modules locally with demo data and it did not give any problem, so would you have the courage to do r+ again?

**Comment by william-andre** [comment]
@robodoo r+

**Pull request closed without merging**
