### PR TITLE
[FIX] hr_holidays: use Spanish translations for Spanish (Costa Rican)

### PR DESCRIPTION
**Pull request by andreagidaltig**
Remove the translation file for Spanish (Costa Rican) since there are no
specific translations for this language and some terms do not match the
 English term and when changing the language from English to Spanish
(Costa Rican) that terms aren't translated.

Description of the issue/feature this PR addresses:
- Error in term translation "Paid Time Off" for Spanish (CR).
image

image

Desired behavior after PR is merged:
- Show "Vacaciones" from Spanish translation instead of "Legal leaves" for Spanish (CR).

image

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by luistorresm** [comment]
Hello @mart-e 

Do you know what is the process for updating these files? This file was updated manually and has many changes.

Regards

**Comment by mart-e** [comment]
@luistorresm isn’t it easier to just remove the file and use the es.po ?

**Comment by luistorresm** [comment]
> @luistorresm isn’t it easier to just remove the file and use the es.po ?

Yes @mart-e 

We have removed the file, could you help me to approve or merge it if possible for you?

Regards

**Comment by mart-e** [comment]
Thanks for the change
@robodoo r+

**Pull request closed without merging**
