### PR TITLE
[I18N] calendar: correct bad email template translation

### PR DESCRIPTION
**Pull request by Julien00859**
Complement 4558ca95cd088

opw-1891825

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't this be done on Transifex?

**Comment by nim-odoo** [comment]
@pedrobaeza No, it was not propagated on v11.3 by Transifex.

**Comment by pedrobaeza** [comment]
OK, I see, intermediate saas versions are not handled by Transifex. @mart-e do you see problems in this flow?

**Comment by pedrobaeza** [comment]
OK, thanks for clarifying this.

**Pull request merged**
