### PR TITLE
[FIX] web: fix typo in menu "My Odoo.com account"

### PR DESCRIPTION
**Pull request by yelizariev**
It was introduced on js refactoring in v15

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
robodoo r+

**Comment by kebeclibre** [comment]
robodoo r-

**Comment by kebeclibre** [comment]
@yelizariev Ouuupssss
It's fine, but I think the pot files must be updated along with the PR :)

**Comment by yelizariev** [comment]
Indeed, I forgot about the translations. (Shouldn't we add a runbot test for it, btw?)
Should be fine now

**Pull request closed without merging**
