### PR TITLE
11.0 Removed HR Salary Rule Categories Hierarchy menu and action

### LINKED ISSUE #22304: [11.0] Hierarchy view is not working.
Impacted versions:11.0

Steps to reproduce: Go to Payroll >> Configuration >>   Salary Rule Categories Hierarchy

Current behavior: It shows New Form View

Expected behavior: It should show Hierarchy view 

Video/Screenshot link (optional): http://294612-11-0-ca2060.runbot9.odoo.com/web?debug#id=&view_type=form&model=hr.salary.rule.category&menu_id=450&action=626

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: The tree views were removed from the new web client. Removed Salary Rule Categories Hierarchy menu and action.

Current behavior before PR: Salary Rule Categories Hierarchy will open new form view.

Desired behavior after PR is merged: Fixes #22304 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Sorry but  no do not delete records in a stable version 👎

**Comment by Yenthe666** [comment]
@mart-e you can rebase & merge it against the master though?

**Comment by sswapnesh** [comment]
Than How should we stop this behavior which leads to opening new form view
each time?

**Comment by Yenthe666** [comment]
@sswapnesh custom development or removing it from your own db. @mart-e doesn't want to delete the record as it is against the stable policy. If some partner/customer would have an extend or xpath on this view it would break after this commit.

**Comment by sswapnesh** [comment]
@mart-e Same Issue in Employee --> Subordinate Hierarchy
Not sure if it relates to This Issue #20203

**Comment by anassahmed** [comment]
Issues like #22304 and #20108 makes me wonder how come you release a stable version `11.0` after introducing some aggressive change like hierarchy trees removal without revising and checking your code for any reference to it?!!

It's really astonishing too how you plan to keep a *very wrong and broken* behavior because you're now afraid to break a stable release! ☹️

**Pull request closed without merging**
