### PR TITLE
[IMP] web: allow to group by integer

### PR DESCRIPTION
**Pull request by mart-e**
No technical reason to forbid it

Fixes odoo/odoo#31684

@ged-odoo any reason to forbid the integer? It can makes sense on some models (e.g. on fleet, group vehicles by number of doors)
It seems there is also some other `GROUPABLE_TYPES` in different view types (like pivot). Do you want me to add it everywhere?

### CODE REVIEW

**Comment by aab-odoo** [comment]
@Polymorphe57 Maybe it's time to use the same variable in Pivot and Graph? Any reason why the list of groupable types is re-defined in those views?

**Comment by ged-odoo** [comment]
@mart-e not really a good reason, but the general idea is that numeric values may in some cases return many many groups.  And grouping a pivot view with 10k groups will probably kill your browser.

I think we should have a limit on the number of groups (something like 1000? maybe more?), use that limit for the read_group, and if there are more groups, then display the pivot view with the fetched groups, and a warning, something like 'too many groups, please confirm that this is what you want (in which case we drop the limit) or change the filters to reduce the number of groups

**Comment by mart-e** [comment]
@ged-odoo I agree with you, (or prefetch only the first x records) but I think this is outside of the scope of this PR, you can already kill your browser easily if you try grouping by "name" on your invoices/quotations when you get several years of records.

**Comment by ged-odoo** [comment]
@mart-e yeah, i was just saying the reason why integer fields were not in the list. I am ok with this PR (except for the lack of tests)

**Comment by mart-e** [comment]
@robodoo r+ rebase-ff

**Comment by xmo-odoo** [comment]
@mart-e 

> No technical reason to forbid it

Are you sure? IIRC the groupby output format didn't namespace separately the grouping and aggregated values and would always aggregate numeric fields, summing them by default. So if you grouped an integer field the group for the value `3` with 3 records inside it would show the label `9` instead (the sum of the values of the records), something like that.

**Comment by mart-e** [comment]
Screenshot_2019-05-29 Vehicles - Odoo
Looks like working fine. Or are you talking about somewhere else?

**Comment by xmo-odoo** [comment]
> Screenshot_2019-05-29 Vehicles - Odoo
> Looks like working fine. Or are you talking about somewhere else?

I think that's the one, so it seems to be working now.

**Comment by mart-e** [comment]
@robodoo retry then

**Comment by mart-e** [comment]
@robodoo retry then

**Comment by xmo-odoo** [comment]
> Screenshot_2019-05-29 Vehicles - Odoo
> Looks like working fine. Or are you talking about somewhere else?

Looks like @rco-odoo special-cased / fixed the issue in 5f0692609332fba1c32b0967f98172655a437b5f

**Comment by tde-banana-odoo** [comment]
:love_hotel:

**Pull request closed without merging**
