### PR TITLE
[IMP] hr_expense:replace demo expense products

### PR DESCRIPTION
**Pull request by kcv-odoo**
Currently, in the expense module, demo expense products are more specific to
the expenses and  label tooltip of the cost field doesn't convey proper
difference between fixed and variable cost of expense products.

So in this commit, replace old expense products with new expense products and
recreate expenses and reports using these categories(products). it will provide
better experience on demo. overwrite label tooltip of cost field in expense app
to convey proper difference between fixed and variable cost of expense products.

Task-id: 2491238

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by kbapt — CHANGES_REQUESTED** [review]
Changes LGTM, however as the demo data are in noupdate=1, you need to force their update through a migration script I'm afraid.

**Comment by mba-odoo** [comment]
> Changes LGTM, however as the demo data are in noupdate=1, you need to force their update through a migration script I'm afraid.

@kba-odoo , I am not sure, does we really required migration script for demo data? is there database going to upgraded with demo data?

Thanks

**Comment by kba-odoo** [comment]
@mba-odoo indeed :sweat_smile: it's only demo data so not really needed; my bad

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
