### PR TITLE
[FIX] stock: rename routes on warehouses' name change

### PR DESCRIPTION
**Pull request by myhy-odoo**
Description of the issue/feature this PR addresses:
- Routes renaming
When a warehouse is renamed, associated route's name aren't renamed accordingly.
As previously, the call to 'route.write()' in method '_update_name_and_code' was done
after the 'super().write()', there was no way to remember the old name of the warehouse,
and the 'replace' was so uneffective.The effectivenes of the replace is reestablished by
doing the 'super().write' after the call to '_update_name_and_code'. However, it breaks
the method '_get_sequence_values' because it expects the name and code to be already written.
- Backport of commits:
https://github.com/odoo/odoo/pull/102456/commits
https://github.com/odoo/odoo/pull/103146/commits

- Operations rename
When renaming a warehouse, the sequence prefix of the operation types
gets overwritten and not all of the operation types gets renamed.
Handle the creation of the sequence values in another private method,
_create_sequence_values, to avoid redundancy.

- Return operation type created with the wrong sequence_code
When creating a new warehouse, the return operation type is
created with the wrong sequence_code which will lead to a
unique sequence error when creating stock related records

Current behavior before PR:
- When a warehouse is renamed, route's name doesn't change
- When a warehouse is renamed and the user changed the
sequence prefix of an operation type, the sequence prefix
of the operation type gets overwritten
- When a warehouse is created, the return operation type
is created with the wrong sequence_code

Desired behavior after PR is merged:
- When a warehouse is renamed, route's name change accordingly
- When a warehouse is renamed and the user changed the sequence
prefix of an operation type, the sequence prefix of the operation
type should not get overwritten unless the warehouse code or the
operation type code has been modified.
- When a warehouse is created, the return operation type's
sequence_code should be 'RET'

opw-2985735, opw- 3963840

### CODE REVIEW

**Comment by myhy-odoo** [comment]
@fw-bot up to 16.0

**Comment by myhy-odoo** [comment]
@robodoo up to 16.0

**Comment by myhy-odoo** [comment]
@robodoo ignore

**Comment by myhy-odoo** [comment]
Hello @amoyaux  ! Can you review this PR when available? It is a backport of this PR: https://github.com/odoo/odoo/pull/102456 and I need this to be approved before I can work on a bug that is related to this module. Thanks in advance!

**Comment by amoyaux** [comment]
Changing method signature in stable is forbidden. Use the context instead and clean it in master (if needed)

**Comment by myhy-odoo** [comment]
Hello @amoyaux! Since the 15.0 fix will be different from the 16.0+ fix, can I also include the fix for this bug: https://www.odoo.com/odoo/project/49/tasks/3963840 in this PR? Or would you prefer the PRs be separated. Both bugs are related to warehouse naming. This ticket highlights more bug that Task : 2985735 missed

**Comment by amoyaux** [comment]
Hey do we really need to fix it 15.0? It seems not that important

**Comment by amoyaux** [comment]
It's not from a ticket, so just don't fix it since it's already good in master

**Comment by myhy-odoo** [comment]
> Hey do we really need to fix it 15.0? It seems not that important

@amoyaux This bug I am working on is from a ticket: https://www.odoo.com/odoo/project/49/tasks/3963840?cids=3  and they are on 15.0. The client is complaining that when they rename a warehouse, their custom sequence prefix for an operation type gets overwritten. I think it's still a bug that needs to be fixed because renaming a warehouse shouldn't trigger an overwrite on the sequence prefix unless the warehouse code was explicitly changed. Unless you think it's better to not fix it on 15.0 and only fix it 16.0+ and tell the client it's a limitation and they should upgrade to 16?

**Comment by myhy-odoo** [comment]
@amoyaux Can you review the updated commit? This PR will only fix 15.0 and then I will open another PR to fix 16+ for this bug: https://www.odoo.com/odoo/project/49/tasks/3963840?cids=3.

**Comment by myhy-odoo** [comment]
Closing PR due to 15 not being supported soon

**Pull request closed without merging**
