### PR TITLE
12.0 opw1959679 uom len

### PR DESCRIPTION
**Pull request by len-foss**
Really make the check that the UoM category has a reference defined.

### CODE REVIEW

**Comment by sle-odoo** [comment]
@len-odoo i don't get the message of the stock related commit
> However the check that the operation is risky is too broad, and even includes
the case where an UoM that has just been created cannot be modified.

It implies that the check should be modified, however you only change the error message?

**Comment by len-odoo** [comment]
> It implies that the check should be modified, however you only change the error message?

Since the check was added as a safeguard to forbid screwing up your stock values, I don't want to take the risk to incorrectly relax the condition.
Basically my take is that I don't know enough about the use-case to do so, especially if the most knowledgeable about this extra-safe.

Assuming the checks are sufficiently strict on delete, we could also do the following: try to delete the record. If an exception is raised we raised the same error message, and otherwise we rollback and perform the write. (that's somewhat horrible but does reduce the problem to the other.)

**Comment by len-odoo** [comment]
Also: opw 1970692
See also opw 1970699; import does not work correctly because of Odoo limitations, so people are likely to want to create UoM via import then edit them directly after.

I'm more inclined to think that we should go for the savepoint/unlink/rollback solution, or similar to check if we can edit the UoM.

**Comment by sle-odoo** [comment]
@Whenrow we should see if it's possible do lessen the constraints of [this](https://github.com/odoo/odoo/blob/12.0/addons/stock/models/product.py#L643)

**Comment by len-odoo** [comment]
Given how it went, the check will stay like this for v12; SIG is going to make the "can be edited <=> can be deleted" for master. So only the fix on the UOM constraint is left on the PR.

robodoo r+

**Comment by fmdl** [comment]
Hi @len-odoo and @sle-odoo this SQL query can be remplaced by a `read_group`.

https://github.com/odoo/odoo/pull/33776

**Pull request closed without merging**
