### PR TITLE
[IMP] base: improve model description

### PR DESCRIPTION
**Pull request by niyasraphy**
Description of the issue/feature this PR addresses: model description for 3 models

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Could you update the base.pot file as well to include these new models description?
Thanks

**Comment by niyasraphy** [comment]
Hi @mart-e,
Updated base.pot file with the new model description.

Thanks

**Comment by mart-e** [comment]
Thank you for the quick action, looks good now :+1: 
@robodoo r+

**Comment by niyasraphy** [comment]
@mart-e should i rebase the branch as some test is getting failed ?

**Comment by ryv-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
