### PR TITLE
[ADD] Contributor licence added

### PR DESCRIPTION
**Pull request by mikolodz**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `m...@hcseurope.pl`
- you are signing _for_ the address `m...@icloud.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by mikolodz** [comment]
> Hello,
> 
> Thank you for the CLA signature but it seems there is still an issue.
> 
> * you are signing _using_ the address `m...@hcseurope.pl`
> * you are signing _for_ the address `m...@icloud.com`
> 
> The email address in the CLA must be the same as for the signature for the verification to succeed. You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.
> 
> Thanks

Hello,

Thank you for letting me know. I've fixed the email address as you described and committed again.

Best regards

**Comment by mart-e** [comment]
Thanks ! Could you just squash your commits and change change the commit message to `[CLA] signature for mikolodz` ?
I can push in your branch if you are not sure.

**Comment by mikolodz** [comment]
> Thanks ! Could you just squash your commits and change change the commit message to `[CLA] signature for mikolodz`? I can push in your branch if you are not sure.

Thank you, I've squashed the commits and replaced the commit message accordingly.

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
