### PR TITLE
[14.0][FIX] account: add date in JSON data for payment widget on account.move

### PR DESCRIPTION
**Pull request by alexis-via**
With this PR, the date pop-up works on the outstanding payment widget of invoice form view:

bug_payment_widget_odoo14

Without this PR, the date pop-up doesn't show up.

Here is the corresponding XML code that shows the date pop-up: https://github.com/odoo/odoo/blob/14.0/addons/account/static/src/xml/account_payment.xml#L20

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by clementmbr — APPROVED** [review]
Very Useful!

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by jco-odoo** [comment]
@alexis-via It is weird that we are passing the date through 2 different keys in 2 different ways as payment_date is already there.  Maybe there is a way to improve on the javascript side.  @FlorianGilbert might know more.

**Comment by alexis-via** [comment]
@jco-odoo I didn't even notice that we had a payment_date key in the JSON !!!
So we can consider that the error is in the XML of the outstanding payment widget, not in the python code.
As we have to modify the XML of the widget, I propose a better implementation that shows the date directly, not in a pop-up which is not convenient. You can see the result in this screenshot:

widget_payment_v2

**Comment by jco-odoo** [comment]
@tsb-odoo This would already be quite a change in stable, but maybe you like it.

**Comment by jco-odoo** [comment]
For stable policy, if we change to a formatted date, then another key would be better.

**Comment by alexis-via** [comment]
@jco-odoo OK, I can understand that. So I updated the code to keep the payment_date key unchanged (I used another key).

**Review by fmdl — APPROVED** [review]

**Comment by fmdl** [comment]
#2761242

**Review by jco-odoo — CHANGES_REQUESTED** [review]

**Comment by fmdl** [comment]
@jco-odoo if you have lot payment with the same amount (like phone billing each month), it is very hard to match the good payment with the good invoice.

**Comment by C3POdoo** [comment]
Dear @alexis-via,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
