### PR TITLE
[CLA] Signature for anothingguy

### PR DESCRIPTION
**Pull request by anothingguy**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for your CLA signature but do you intend to make other contributions?
We usually merge the CLA at the same time as the first contribution.
When you make your first request, give the link to this pull request so that we can merge both.

**Comment by anothingguy** [comment]
so it's fine for me.
Thanks.

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it has been integrated into Odoo at revision https://github.com/odoo/odoo/commit/2cf3381b23d85add47a1ef044f77af727fde372f.
If you rebase your other pull request #15190, it will be validated by the runbot now.
Regards

**Comment by anothingguy** [comment]
hello @mart-e 

i have rebased #15190 on branch 9.0, but it seems that CLA is not validated.
i notice that my CLA has been integrated into branch 10, but i want to contribute #15191 into branch 9.0. Will CLA be validated even different branch ? 

sorry if i'm wrong something.  

Regards.

**Comment by mart-e** [comment]
Hello,

Indeed, the CLA needs to be signed in the branch you want to contribute. We forwardport codes so your signature is valid for 10 and master (future v11).
As you have made a PR for v9, I have backported your signature there at b4c3ac8d48df798cb4bf633dcc7175399604d02c

**Comment by anothingguy** [comment]
it works now, thanks so much :)

**Pull request merged**
