### PR TITLE
[FIX] auth_ldap: LDAP login fails if it creates a new user.

### PR DESCRIPTION
**Pull request by eLBati**
Steps:

 - Set up LDAP authentication with Create User enabled and a Template User set
 - Log in with an LDAP identity that doesn't have an account yet

Get

odoo.exceptions.MissingError: Record does not exist or has been deleted

See https://github.com/odoo/odoo/issues/41060

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by eLBati** [comment]
Does anybody know why this https://runbot.odoo.com/runbot/build/61479601 is failing? Thanks

**Comment by Julien00859** [comment]
@odoo/rd-framework-py Task ID 3879911

**Comment by eLBati** [comment]
@Julien00859 changed, thanks!

**Comment by JakubSs** [comment]
Hello,
the same issue is on v17. Is there any way fix will be deployed in following days/weeks?
Thanks

**Comment by JakubSs** [comment]
@Julien00859 Hi, thanks for reaching out. All right. I will wait

**Comment by Julien00859** [comment]
Hello @eLBati with further investigation we confirm that your proposal is the right solution. We pushed a test on-top of your fix, hopefully you don't mind. We are going to merge it soon.

Hello @odoo/rd-security 

> import requests

We use requests in a test file only to request the current database, like `url_open` would do. We are in a situation where we cannot use `TransactionCase` or `HttpCase` because the code commits. This explicit `commit()` would break the savepoint of `TransactionCase` and using a test-cursor would make the test useless because this really is about testing that the system works fine even if the user is created in another transaction. Hence we used `BaseCase` and we had to import requests ourself.

The test is flagged as "-standard", "database-breaking" because it does create and commit a new user. We remove that user in a cleanup but there is a chance that user isn't removed if we ctrl-c at the right time.

**Review by Julien00859 — APPROVED** [review]

**Review by Julien00859 — COMMENTED** [review]
Thank you everyone involved in this one :) A bot is gonna open a PR with this fix in all successive versions too. Hopefully Monday next week all versions will be fixed. Hopefully this extra commit() doesn't break anything in future versions.

@robodoo r+

**Comment by Julien00859** [comment]
@robodoo rebase-ff

**Comment by Julien00859** [comment]
Indeed :)

**Comment by Julien00859** [comment]
Sorry for the spam, we address those forward-ports today

**Pull request closed without merging**
