### PR TITLE
[FIX] hr_expenses: account move for expenses with more than 1 tax bug

### PR DESCRIPTION
**Pull request by imekinox**
Description of the issue/feature this PR addresses:
When trying to create journal entries for an expense with more than 1 tax type an error occurs.

Current behavior before PR:
When trying to create journal entries for an expense with more than 1 tax type, a python singleton exception was rised.

Desired behavior after PR is merged:
When trying to create journal entries for an expense with more than 1 tax type, the correct account moves are created.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
we could use `.ids` as well but actually I wonder if the line `account_move[-1]['tax_ids'] = ...` is not useless.

@qdp-odoo opinion?

**Comment by imekinox** [comment]
Hello, do I change it to .ids?

**Comment by qdp-odoo** [comment]
err... @mart-e actually it seems indeed that the key 'tax_ids' is not used at all in _prepare_move_line(), but it is another bug. So the correct patch would be

```python
l. 291 -            account_move[-1]['tax_ids'] = expense.tax_ids.id
l. 291 +           account_move[-1]['tax_ids'] = expense.tax_ids

l. 162 +       'tax_ids': line.get('tax_ids'),
```

**Comment by imekinox** [comment]
Hello @mart-e, I made and commited the changes as @qdp-odoo suggests

**Comment by mart-e** [comment]
Thanks, merged at 3ea89580148bbcf8f9cbda47f8e636aa8795d196

**Pull request merged**
