### PR TITLE
[12.0] Use version 2.8.3 of psycopg2 when installing on Python 3.8

### PR DESCRIPTION
**Pull request by LuqueDaniel**
### Description of the issue/feature this PR addresses:

Run Odoo on Ubuntu 20.04 + Python 3.8

### Current behavior before PR:

Psycopg2 package doesn't install, command `python -m pip install -r requirements.txt`. Error:

```
    default:     psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
    default:     psycopg/psycopgmodule.c:685:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
    default:       685 |     while (interp->next)
    default:           |                  ^~
    default:     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    default:     ----------------------------------------
    default: ERROR: Command errored out with exit status 1
```

### Desired behavior after PR is merged:

Install psycopg2 2.8.3 instead of 2.7.3.1 if Python >= 3.8

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
ping: @d-fence

**Review by d-fence — APPROVED** [review]
Looks good to me.
2.8.3 was the chosen version for Odoo 13.0 so no need to fw-port.

**Comment by d-fence** [comment]
@fw-bot ignore
robodoo r+

**Comment by d-fence** [comment]
robodoo r-

**Comment by d-fence** [comment]
Sorry, I forgot to verify the commit message.

@LuqueDaniel may I ask you to split the CLA signature in a separate commit and follow those [guidelines](https://www.odoo.com/documentation/12.0/reference/guidelines.html#commit-message-structure) for the commit messages.
Basicaly, the CLA signing commit message should be:
`[CLA] Sign CLA for Daniel Luque`
and the commit message for the requirements should start with
`[FIX] requirements: use psycopg2 2.8.3 with Python 3.8`
followed by a small explanation why this fix is required.

Thanks for your contribution.

**Comment by LuqueDaniel** [comment]
@d-fence Done! I'm sorry I didn't read that section of the docs.

**Comment by d-fence** [comment]
@fw-bot ignore
robodoo r+

**Comment by d-fence** [comment]
robodoo rebase-ff

**Pull request closed without merging**
