### PR TITLE
[FIX] website_sale : make checkout flow working with wrong coupon code

### PR DESCRIPTION
**Pull request by jvnm-dev**
Cherry pick of e04b6253748ca03763204d293a48d2a03cfcab1a with a small addition to keep the url of /payment/checkout too. It must be merged in all upper versions if we want this thing to work correctly in upper versions too.

-------------------------

eCommerce checkout flow was moving forward on wrong coupon code, now it
stay on same page if promocode is wrong.

OPW-2290188

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
@nim-odoo

**Comment by nim-odoo** [comment]
note that it might make sense to keep the separate commits for clarity

**Comment by agr-odoo** [comment]
ok
Since you are integrating changes in the workflow It would be nice to add also https://github.com/odoo/odoo/commit/960c8baf3439cfebc9e309e0819d81db04570f9d
to avoid user losing form info upon entering coupon

**Comment by jvm-odoo** [comment]
Indeed, I added your commit and tested it in 12. Everything seems ok!

**Comment by agr-odoo** [comment]
@nim-odoo Everything looks ok

**Comment by nim-odoo** [comment]
robodoo rebase-ff

**Pull request closed without merging**
