### PR TITLE
[FIX] product,sale: put product price when applying Quotation Template

### PR DESCRIPTION
**Pull request by Dj0ulo**
__Current behavior before PR:__
When setting a Quotation Template on a new quotation without customer, product in the order lines are set to a price of 0.

__Description of the fix:__
As it was done [in this commit](https://github.com/odoo/odoo/commit/83c52575d0ce3d7deb1737c622c6ce366db8c31b#diff-5a563f36ffd028b0d8510c6d1339b097a5067a2247cc35c0f9bdd1fd0b5a0b05), a price is set even when there is no pricelist. The currency of the company is used in that case.

opw-3340506

### CODE REVIEW

**Comment by Dj0ulo** [comment]
NB: The issue is also present in `saas-15.2` (not in `15.0`) but it is not supported anymore right ?

**Comment by Demesmaeker** [comment]
Hello @Dj0ulo 
Thanks for your work, however, before the mentioned commit, it's perfectly normal and intended for the prices to be set as 0 when there is no pricelist set. _(So when there is no partner, there isn't any pricelist set)_. Indeed, in these previous versions, the whole computation of prices need an existing pricelist, even if the user doesn't create one or doesn't see the pricelist, the `list0` pricelist in the data is applied as the default pricelist for a partner. That was quite bothersome and the reason we made it works without this logic. But these changes were too dangerous to be allowed in a stable version, and we don't want part of it to hack the game in previous versions, as this will create a lot of unexpected problems. So, if there isn't a partner, there isn't a pricelist, and the price stays as 0. =]
Have a nice day!

**Comment by Demesmaeker** [comment]
I close this PR as this isn't a bug =]

**Comment by Dj0ulo** [comment]
@Demesmaeker Ok, thanks for your quick answer. It still seems weird to me that only 15.2, 16.0 and 16.1 have this "issue".. 
Why 15.0 didn't have this behavior then ?

**Comment by Demesmaeker** [comment]
I'd need to verify, but I *guess* at the time the list0 was applied even without a customer, I don't know why it was decided to change that though. Probably to make it clearer and avoid some "magic prices". An honest 0 is more obvious.

**Pull request closed without merging**
