### PR TITLE
v12 website ecommerce comparison + coupon  UI dbh

### PR DESCRIPTION
**Pull request by dbh-odoo**
Issues: 
https://drive.google.com/file/d/1DD_DPmiUWr-8_3vqnzGoIQQmHOMaGqck/view?usp=drivesdk
https://drive.google.com/file/d/1MZcidtl0fUzmkhJP0ONz89CUFTAHMaWl/view
https://drive.google.com/file/d/1Rz07zhY3g9s8EXyPnt_T1H9l5xXRINzj/view?usp=drivesdk

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dbh-odoo** [comment]
Hello @JKE-be 
Here is a small fix for layout issue of eCommerce checkout process.
can you please review it?
Thanks.

**Comment by JKE-be** [comment]
Hello

+ / - fix is expected behaviour to 'modernize' the checkout
OK for redirect fix with coupon
OK for comparison fix

**About fix layout responsive**
You fix to make right column responsive make it ugly.
I suggest to keep the o_table_column_fit, but instead tory to replace layout col-6/col-6, by col-5/col-7 ?
Can you try this ?

Thanks for your PR

**Comment by dbh-odoo** [comment]
Hello @JKE-be 
>   I suggest to keep the o_table_column_fit, but instead try to replace layout col-6/col-6, by col-5/col-7 ?

I have replace layout with col-4/col-8 like it was in Bootstrap 3
can you please check?
thanks.

**Comment by JKE-be** [comment]
Ok, we will keep auto size, and fix mobile here in website team.

Thanks for you 2 other commits that will be merged asap

**Comment by JKE-be** [comment]
Thanks, most of these bug (from what I see in your screenshot) has been fixed meanwhile.

If I miss one, don't hesitate to re-propose a fix

**Comment by JKE-be** [comment]
reditect coupon and 'add to cart' on mobile for comparison not yet merged so I keep it open

for the xl-8 we prefer to keep auto size at this moment

**Comment by rdeodoo** [comment]
I remove the RD tag so we can handle this someday during a github day

**Comment by C3POdoo** [comment]
Dear @dbh-odoo,

Thank you for your contribution but the version 12.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
