### PR TITLE
[FIX] mail: Add missing HTML attributes aria-*

### PR DESCRIPTION
**Pull request by luisg123v**
Some HTML attributes were missing, and are required to ensure good
compatibility with screen readers.

The following attributes are included:
- `aria-label`: this should be present in all links and buttons which
  don't show text, but icons or images, e.g. the bell icon and the
  followers button.
- `aria-pressed`: Used in buttons whose function is toggled when
  pressed. In this case, it's used on the button to follow a record.
- `role`: used to improve given information about what elements are for.
  For example, buttons to filter conversations are tagged as "tab".

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by luisg123v** [comment]
@kujiu 
Hi. Do you agree with these changes?

**Comment by kujiu** [comment]
Hello,

We do the freeze of next version this week. I have to see all impacts of your
code next week.

As you can see in these PR, we have worked on accessibility for future versions.
https://github.com/odoo/odoo/pull/24574/commits
https://github.com/odoo/enterprise/pull/2146

Have a good day.

**Comment by luisg123v** [comment]
Thanks @kujiu, I didn't know about that freeze planification. Then, from now on, I'll target master instead.

Yes, yesterday I took a look to those PRs, and I must say I'm very glad that kind of features are being improved.

**Comment by tde-banana-odoo** [comment]
Hello,

Indeed this kind of changes is not a real bugfix and belongs more to improvement of Odoo. It should therefore targets master. @kujiu as you are working on this topic could be keep an eye on this one ?

Many thanks,

**Comment by luisg123v** [comment]
@kujiu 
Hi,

Since those PRs you referenced are now merged and most of the code here is still useful, I'm now targeting  master and I left only the relevant parts, removing `aria-label` improvements since they're not required anymore thanks to you. I also edited PR/commit's description accordingly.

What do you think? Would you consider re-opening this PR?

**Comment by luisg123v** [comment]
Thinking about it better, since the change for master is not just the same, I decided to open a new one (https://github.com/odoo/odoo/pull/25667) and leave this one as it was.

**Pull request closed without merging**
