### PR TITLE
[IMP] base: add hasattfclass utils method to apply view xpath

### PR DESCRIPTION
**Pull request by Tardo**
Description of the issue/feature this PR addresses:
This util can check if a class is used in the 't-attf-class' attribute

Current behavior before PR:
Can't use "hasclass" with 't-attf-class' attribute and a lot of nodes in Odoo uses t-attf-class.

Desired behavior after PR is merged:
hasattfclass can check the classes in the 't-attf-class' attribute.
For example:
 - t-attf-class: `text-right {{ 'd-none d-md-table-cell' if report_type == 'html' else '' }} test-#{!selection_mode ? 'text-center' : ''}-this mb-0`
 - Splitted: `["text-right", "{{ 'd-none d-md-table-cell' if report_type == 'html' else '' }}", "test-#{!selection_mode ? 'text-center' : ''}-this", "mb-0"]`

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Gorash — CHANGES_REQUESTED** [review]
Please add at least one test with an example of use.
This will keep this behavior during any refactoring and not consider this code as dead code.

Thanks.

**Comment by Tardo** [comment]
@Gorash Test added :)

**Review by Gorash — APPROVED** [review]
It's good for me.
@qsm-odoo could watch, I think it will be useful for you.

**Comment by Gorash** [comment]
@Tardo Could you put an explanation such as the message of your pr as the message of your commit and change the title of the commit: `[IMP] base: add hasattfclass utils method to apply view xpath` ?

**Comment by Tardo** [comment]
@Gorash done!

**Comment by qsm-odoo** [comment]
Mmh, I am not sure I would be in favor of doing this in stable. Some arguments:
- Making xpath on the computed value (as your test seems to allow via `tree.xpath('//node[hasattfclass("{{ \'foobar\' }}")]')`) is not something we need IMO, you would be better off xpathing the exact path to reach the element rather than xpathing on such a strange thing IMO
- Could not be done in stable of course but why not improving `hasclass` to target t-attf-class too if we judge having the possibility to xpath based on `t-attf-class` is a need?

Although, I guess this could be nice for people in stable versions... I'll let @odoo/rd-framework-py  / @odoo/rd-security decide anyway.

In master, I would be in favor of:

1. Attribute `X`, `t-att-X` and `t-attf-X` on the same node should result in X being a concatenation of all 3 results. So
```xml
<section class="hello world" t-att-class="'foo' if condition 'bar'">
```
would lead to
```xml
<section class="hello world foo"> (if condition)
<section class="hello world bar"> (if not condition)
```
This is a need we often have when module A defines something with a `class` attribute (no computation) but another module B later needs to add something computed in that class. In that case we need to change module A (to have a strange `t-attf-class` with no computation in it but that we can xpath) or duplicate the class value in module B.

2. Given (1.), I think it would be natural that `hasclass` in xpaths would check the concatenation of `class`, `t-att-class` and `t-attf-class`. I probably would exclude the computed parts entirely from the check TBH :shrug: 

Anyways, anything fine by me, I'll the framework team(s) decide :+1:

**Comment by Tardo** [comment]
Thanks for the comments @qsm-odoo 

The test case you mention is intended to verify that the split is done correctly. Perhaps an exception could be added in case someone tries to use this tool with the variable part and not with the static part.

I did not want to extend `hasclass` in order not to have uncontrolled behaviors with the current views.

What you propose is interesting...
It would also remain to be seen how to work with these attributes and `position=attributes` (easily add and delete classes as with the 'class' attribute).

**Pull request closed without merging**
