### PR TITLE
Highlight domain attribute doesn't work as expected

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
To reproduce:

- Open a form doing create on a model that has a many2one field with a domain.
- In the many2one field box, you cannot select records that don't pass the domain. OK.
- In the many2one field box, you click on "create and edit", and appears a second form, then you fill any option expressly in order to don't pass the domain. Click on create, and then the created record appears filling the many2one field box of the first form. Wrong!
- And if you finally click on create on the first form, then a record is created although there is a contradiction between the field domain and the record in the field. Wrong!

So, there is at least two errors, although I don't know if the later is intended or not.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
I did this draft to highlight errors. @mart-e could you label, please? maybe @xmo-odoo can check it?

**Comment by xmo-odoo** [comment]
@mreficent I don't think the domain has ever been considered a *constraint*, it's just a UI-level guideline, so it being ignored in various cases (including when you're creating a record from the m2o dropdown) is expected.

**Comment by mreficent** [comment]
@xmo-odoo But I think that "when you're creating a record from the m2o dropdown" should not be one of those ignored cases. It should not be that easy to ignore the domain. When someone puts a domain in the many2one, it's because you don't want people putting unwanted records in the many2one. If it's that easy to ignore the domain, then the domain attribute is incoherent.

**Comment by lathama** [comment]
@MiquelRForgeFlow knowing that 13 is no longer updated, is this PR still needed?

**Comment by MiquelRForgeFlow** [comment]
Oh, the test didn't fail, so it means what the test was trying to highlight was fixed at some point in time (I don't know in which version). Then this PR is not needed anymore.

**Pull request closed without merging**
