### PR TITLE
[IMP] cli: propose HTTPS website URL by default

### PR DESCRIPTION
**Pull request by Yenthe666**
As by now pretty much all of the internet runs on HTTPS & it is recommended everywhere let's do so our in our manifest do.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e for you :) I've made small changes to the `manifest` from the theme template so it is more in line with the template from the default app too.

**Comment by Yenthe666** [comment]
@mart-e gentle reminder :-D

**Comment by mart-e** [comment]
Hi !

Ok for the HTTPS but why the change of version ?

**Comment by mart-e** [comment]
Ok makes sense. Thanks for the PR :)
@robodoo r+

**Pull request closed without merging**
