### PR TITLE
update tour sequence

### PR DESCRIPTION
**Pull request by msh-odoo**
PURPOSE
Update sequence of onboarding tours

SPEC
Update sequence of onboarding tours

TASK 2444153

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
Hello @msh-odoo 

Small spec change coming from @odoongr :

point_of_sale_tour -> 45
hr_expense_extract_tour -> 42

Could you quickly do the change? Thanks

**Comment by msh-odoo** [comment]
@aab-odoo Done changes, Thanks

**Comment by aab-odoo** [comment]
@msh-odoo No [IMP] in stable, so if we want this in v14, let's tag it [FIX] (which is true actually)

**Comment by msh-odoo** [comment]
@aab-odoo Done I changed tag to FIX instead of IMP

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
