### PR TITLE
[IMP] mail: introduce AttachmentViewer/onClickHeader

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2579306

### CODE REVIEW

**Review by phenix-factory — APPROVED** [review]
That is sad code.
LGTM

**Comment by alexkuhn** [comment]
Indeed, when most code is in model, will be time to remove/replace these `stopPropagation`.

@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r-

**Comment by seb-odoo** [comment]
obsolete pr

**Pull request closed without merging**
