### PR TITLE
[FIX] lunch: fix lunch product report

### PR DESCRIPTION
**Pull request by RomainLibert**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by RomainLibert** [comment]
@robodoo r+

**Comment by mart-e** [comment]
again ?

**Comment by RomainLibert** [comment]
@mart-e Yes not the first I fix something in lunch, didn't want to collide the name with another branch

**Comment by RomainLibert** [comment]
@robodoo retry

**Pull request closed without merging**
