### PR TITLE
[IMP] website: add o_default_snippet_text to mega menu snippets

### PR DESCRIPTION
**Pull request by yajo**
This makes the act of replacing the dummy text easier.

@Tecnativa

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@qsm-odoo would you consider this improvement in 13.0 branch?

**Comment by JKE-be** [comment]
For master in theory ;) 

@robodoo r+

thanks again for all yours contributions

**Comment by JKE-be** [comment]
@robodoo r-

**Comment by rdeodoo** [comment]
:boom:

**Comment by Yajo** [comment]
Oh sorry I understood that you wanted it for master, isn't it?

**Comment by JKE-be** [comment]
for the next time ;) 

@robodoo r+

ty

**Comment by Yajo** [comment]
Ah ok thanks! Haha sorry for the rebase :sweat_smile:

**Pull request closed without merging**
