### PR TITLE
[FIX] base: Correct state in res_partner template

### PR DESCRIPTION
**Pull request by Abridbus**
State from the template was 'CA' for California - not recognized on import
Changed it to 'California' to match with the db state

opw 1943904

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Abridbus** [comment]
@rim-odoo Can you review this?

**Comment by Abridbus** [comment]
Closing to backport to v11

**Comment by Abridbus** [comment]
Non blocking issue, import template needs to be changed but not with those values; avoid duplicate as it trigger the warning and confused the user.

**Comment by Abridbus** [comment]
fixed in 31599

**Comment by rim-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
