### PR TITLE
[CLA] add CLA for Mainframe Monkey

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Add a company CLA :)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e :)

**Comment by mart-e** [comment]
ouuuh, new project !
Could you just rename the file to be lowercase?

**Comment by Yenthe666** [comment]
@mart-e do you mean `MainframeMonkey.md` to `mainframemonkey.md`?
Sure, we can do it but I noticed a lot have it now :) See https://github.com/odoo/odoo/tree/14.0/doc/cla/corporate for example `BeOpen`, `SerpentCS` etc.

**Comment by mart-e** [comment]
@Yenthe666 yes but we try to avoid having even more of them ;-)

**Comment by Yenthe666** [comment]
@mart-e done ;)

**Comment by mart-e** [comment]
Thanks for the update, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

@robodoo review+

**Comment by Yenthe666** [comment]
Thanks! :)

**Pull request closed without merging**
