### PR TITLE
[FIX] analytic: can't create plan with access.

### PR DESCRIPTION
**Pull request by gawa-odoo**
You should be able to create analytic plans with analytic group. 
But currently, you need Access Right's group.
We should put a sudo there.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gawa-odoo** [comment]
@h4818 Small up :)

**Comment by h4818** [comment]
LGTM do we have an OPW?

**Comment by gawa-odoo** [comment]
No, but I'm re-writing tests in another PR, where I only add the groups that we need, and so, noticed it.

**Comment by h4818** [comment]
@robodoo r+

**Pull request closed without merging**
