### PR TITLE
[FIX] survey: fix on javascript with check if selectedAnswers exists

### PR DESCRIPTION
**Pull request by salvorapi**
**Description of the issue/feature this PR addresses:**

Issue described on #136673 

Current behavior before PR:

(see issue description) 

Desired behavior after PR is merged:

Bug resolved.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by salvorapi** [comment]
@robodoo r+

**Review by nboulif — APPROVED** [review]
Hello @salvorapi , LGTM, thanks for the fix :+1: 

Just some little notes:
- May I ask you to update the commit title and body message to match the guidelines : https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html (You already did it in the issue message :wink: https://github.com/odoo/odoo/issues/136673 )
- Can you explain the issue and your fix? (the reason why we try to add multiple times the same answer ID and why we should not)

Thanks in advance!

**Comment by salvorapi** [comment]
> Hello @salvorapi , LGTM, thanks for the fix 👍
> 
> Just some little notes:
> 
> * May I ask you to update the commit title and body message to match the guidelines : https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html (You already did it in the issue message 😉 [[16.0] survey: Cannot complete survey with a particular configuration #136673](https://github.com/odoo/odoo/issues/136673) )
> * Can you explain the issue and your fix? (the reason why we try to add multiple times the same answer ID and why we should not)
> 
> Thanks in advance!


Hello @nboulif, nice to meet you! :)

I think I wrote the commit following the odoo guidelines.

In #136673, I tried to enter details to reproduce the bug. I don't want to ask multiple times the same answer ID.
What I need is that in one section survey, a user chooses between A or B option. If users choose B, then it must insert name and surname. If users choose A then can continue with next section.

If you try to reproduce with runbot the same condition that is described in #136673 you can see by yourself the bug. :relaxed:


Salvo.

**Comment by nboulif** [comment]
ping @odoo/rd-sm-learn

**Comment by abd-msyukyu-odoo** [comment]
@flch-odoo Hello! I think this one was lost somewhere, maybe you missed it ?

**Comment by nboulif** [comment]
Closing since the issue has been merged here https://github.com/odoo/odoo/commit/34b6a7abada50273ab0b1c8750a042d858238512
Thank you for reporting the issue!

**Comment by salvorapi** [comment]
> Closing since the issue has been merged here [34b6a7a](https://github.com/odoo/odoo/commit/34b6a7abada50273ab0b1c8750a042d858238512) Thank you for reporting the issue!

Hello,

but when will merge on 16.0 branch ?

**Comment by nboulif** [comment]
> > Closing since the issue has been merged here [34b6a7a](https://github.com/odoo/odoo/commit/34b6a7abada50273ab0b1c8750a042d858238512) Thank you for reporting the issue!
> 
> Hello,
> 
> but when will merge on 16.0 branch ?

Hello, the fix has been already merged in 16.0 but will be deployed on clients DB early next week.

**Comment by salvorapi** [comment]
> > > Closing since the issue has been merged here [34b6a7a](https://github.com/odoo/odoo/commit/34b6a7abada50273ab0b1c8750a042d858238512) Thank you for reporting the issue!
> > 
> > 
> > Hello,
> > but when will merge on 16.0 branch ?
> 
> Hello, the fix has been already merged in 16.0 but will be deployed on clients DB early next week.

Ops. Sorry, my mistake.  Thank you. 😊

**Pull request closed without merging**
