### PR TITLE
[FIX] l10n_ar: remove constraint depends on readonly field

### PR DESCRIPTION
**Pull request by KangOl**
Avoid warning during install.

### CODE REVIEW

**Comment by KangOl** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@KangOl The field is used in the constraint, so I am not too sure why you want to remove it.

**Comment by jco-odoo** [comment]
@KangOl Should we put 'journal_id.latam_use_documents' then?

**Comment by KangOl** [comment]
> @KangOl The field is used in the constraint, so I am not too sure why you want to remove it.

Due to warning output by the ORM: https://runbot.odoo.com/runbot/build/2994209

> @KangOl Should we put 'journal_id.latam_use_documents' then?

Maybe. Isn't the dependency on `journal_id` enough?

**Comment by jco-odoo** [comment]
@KangOl Yeah, you are right.  There is only a small chance that would happen.

**Pull request closed without merging**
