### PR TITLE
[FIX][email_template] Generate report with relevant partner id only

### PR DESCRIPTION
**Pull request by kenvac**
Fix for issue #9505

### CODE REVIEW

**Comment by janetrp** [comment]
still happening @pedrobaeza

**Comment by pedrobaeza** [comment]
@kenvac, the problem is still there. I think the solution should be to put the correct active_ids on each call to the sending.

**Comment by kenvac** [comment]
@pedrobaeza 
I tested on runbot and it worked as excepted. When active_ids are removed from context it forces report to use resource ids which is equivalent of setting resource id in active_ids on each call. 

http://112397-9506-393a14.runbot6.odoo.com/web

**Comment by pedrobaeza** [comment]
@janetrp, can you please check it again?

**Comment by janetrp** [comment]
it works indeed :) :+1:

**Comment by pedrobaeza** [comment]
OK then :+1:

**Comment by kenvac** [comment]
Thanks for testing and looking into this. Appreciated.

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
