### PR TITLE
[10.0] Fix l10n_nl author name

### PR DESCRIPTION
**Pull request by astirpe**
Description of the issue/feature this PR addresses:
The author in localization module l10n_nl should be updated, according with the Company branding.

Current behavior before PR:
Author is wrongly written.

Desired behavior after PR is merged:
Author correct.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thanks for the patch. Shouldn't [Onestein's CLA](https://github.com/odoo/odoo/blob/10.0/doc/cla/corporate/onestein.md) be updated too?

**Comment by astirpe** [comment]
@mart-e the Onestein's CLA is correct as it is.

**Comment by mart-e** [comment]
I assumed the modification was that the 'BV' was incorrect in the company name but it just the case ?

**Comment by astirpe** [comment]
Well, good point. We distinguish between company name (Onestein BV) and brand (Onestein).
In our case, as the Author of the module, it must be the brand (Onestein).

About the CLA instead, it is a formal agreement between two companies, so it's correct to leave it as it is.

**Comment by mart-e** [comment]
Thanks for the clarification, merged at https://github.com/odoo/odoo/commit/85fe21f19ba474f134dcc8a3d15e6136122243d7

**Pull request merged**
