### PR TITLE
[FIX] account: ignore exception error in sentry

### PR DESCRIPTION
**Pull request by reka-odoo**
When we upload the PDF file in the invoice and if it does not have xref table then error will be generated.

See Trace back:
```PdfReadError: Could not find xref table at specified location
  File "addons/account/models/ir_attachment.py", line 49, in _decode_edi_pdf
    pdf_reader = OdooPdfFileReader(buffer, strict=False)
  File "odoo/tools/pdf.py", line 189, in <lambda>
    old_init(self, stream=stream, strict=strict, warndest=None, overwriteWarnings=False)
  File "PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "PyPDF2/pdf.py", line 1901, in read
    raise utils.PdfReadError("Could not find xref table at specified location")
```

we stop catching exception in sentry.

sentry - 4114889780

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by reka-odoo** [comment]
@odoo/sentry_reviewers 
Please check this PR.
Thanks!

**Review by yelizariev — CHANGES_REQUESTED** [review]
you should replace logger to `warning("...", e, exc_info=True)`

Idea is to avoid `sentry_ignored` key whenever it's possible

**Comment by reka-odoo** [comment]
@yelizariev 
Changes have been done.
Thanks!

**Review by yelizariev — APPROVED** [review]

**Comment by abz-odoo** [comment]
This log is easily ignorable inside internal sentry code. I will ignore it here.
Thank you

**Pull request closed without merging**
