### PR TITLE
[IMP] point_of_sale: handle products tracked as lots

### PR DESCRIPTION
**Pull request by chienandalu**
This patch for `11.0` is functional in `10.0` and drastically improves the usuability of lots in the Point of Sale frontend.

cc @Tecnativa
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
(y)

**Comment by chienandalu** [comment]
OPW 1833368

**Comment by rafaelbn** [comment]
@pedrobaeza @chienandalu don't you think is time to make this PR to OCB and continue? I don't think Odoo will go ahead with this PR...

**Comment by rafaelbn** [comment]
@legalsylvain what do you think about this one please? Thanks!

**Comment by rafaelbn** [comment]
Hi @mreficent , yes I read the ticked and they closed the ticket so... I don't expect to much here event this is obvious. We can put this in OCB and continue the work in OCA

**Comment by rafaelbn** [comment]
Hi @chienandalu ,

Odoo answers that your issue has already been fixed in 10.0 with the the following commit:

https://github.com/odoo/odoo/commit/8f39c652c65c81d87503d64eeef0da3e0048ffc9

By the line `qty = pack_lot_names.count(lot_name)`

Please confirm and close PR if so

**Comment by rousseldenis** [comment]
@chienandalu Is this can be closed ?

**Comment by chienandalu** [comment]
Sure

**Pull request closed without merging**
