### PR TITLE
[FIX] packaging: refresh requirements.txt

### PR DESCRIPTION
**Pull request by sle-odoo**

### CODE REVIEW

**Comment by yvaucher** [comment]
Don't you want to use PyPDF2 instead of deprecated PyPDF by the way?

http://pybrary.net/pyPdf/

**Comment by sle-odoo** [comment]
Yes, we plan to replace it.

**Comment by yvaucher** [comment]
@sle-odoo Ok great to read that!

**Comment by sle-odoo** [comment]
merged at 5b3812d84b0eb9f272518738498b44292671be1e

**Pull request closed without merging**
