### PR TITLE
[FIX] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by pro-odoo**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/4ea7656d [IMP] link: translate label
https://github.com/odoo/o-spreadsheet/commit/b3bc7907 [IMP] function: allow function name with underscore
https://github.com/odoo/o-spreadsheet/commit/db9cf898 [IMP] chart: translate title and baselineDescr
https://github.com/odoo/o-spreadsheet/commit/ca002cd4 [FIX] selection: do not reset selection on sheet deletion
https://github.com/odoo/o-spreadsheet/commit/3ad60073 [FIX] Selection: do not set current sheet selection to other sheets

### CODE REVIEW

**Comment by pro-odoo** [comment]
fw-bot ignore

**Review by LucasLefevre — COMMENTED** [review]
robodoo r+

**Comment by william-andre** [comment]
I'm checking something related to translations and came across this file.

How does the translation of dynamic strings work? :thinking:

**Comment by LucasLefevre** [comment]
> I'm checking something related to translations and came across this file.
> 
> How does the translation of dynamic strings work? thinking

sources terms are extracted separatly from spreadsheet json files in data. (It doesn't do anything for user created spreadsheets of course).
See https://github.com/odoo/odoo/commit/d210a55f48b316fdf38fcbe5ae5a70cf0e2c3814

**Comment by william-andre** [comment]
Hmmmm, not sure I understand but ok
I still have this warning when extracting the translations though (i.e. `odoo-bin --i18n-export spreadsheet.pot --modules spreadsheet`)
```
/home/odoo/git/odoo/odoo/addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js:8190: warning: Empty msgid.  It is reserved by GNU gettext: gettext("") returns the header entry with meta information, not the empty string.
```

**Comment by LucasLefevre** [comment]
> Hmmmm, not sure I understand but ok

I understand :smile:  it's a bit capilo-tracté. It's a hackish way to translate spreadsheet based dashboards.
We extract terms statically from the json file (which allows them to be translated), then *at runtime*, when the string is given to `_t`, it's translated because the translation exists

> I still have this warning when extracting the translations though (i.e. odoo-bin --i18n-export spreadsheet.pot --modules spreadsheet)

We have a task in our pipe to investiguate this :wink:  Didn't have the time to check though.
Thanks for the reminder
https://www.odoo.com/web#id=2998303&cids=1&menu_id=4720&action=333&active_id=2328&model=project.task&view_type=form

**Pull request closed without merging**
