### PR TITLE
[IMP] mail: introduce ComposerSuggestion/composerViewOwner

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2793280

### CODE REVIEW

**Comment by phenix-factory** [comment]
I go when trying to select an user inside discuss.
Just @ in composer then type => Trace:
```
 RecordDeletedError: 
    RecordDeletedError@http://localhost:8069/web/assets/debug/web.assets_backend.js:109675:9 (/mail/static/src/model/model_errors.js:11)
    async/</<@http://localhost:8069/web/assets/debug/web.assets_backend.js:126082:32 (/mail/static/src/models/record.js:181)
```

**Review by phenix-factory — APPROVED** [review]
LGTM.

**Comment by alexkuhn** [comment]
Will be r-plus later, either on this PR or in a grouped PR of the day

**Comment by seb-odoo** [comment]
obsolete pr

**Pull request closed without merging**
