### PR TITLE
[FIX] stock_landed_costs: fix `MemoryError` on m2m compute

### PR DESCRIPTION
**Pull request by aj-fuentes**
Backport of f329de26.

When there are millions of records in stock_picking table the compute of
alowed_picking_ids may fail with `MemoryError`. This field is only used
on the view view_stock_landed_cost_form thus after this patch it will be
useless. We keep it, but also fix its compute, to not touch the
interface of a stable version.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aj-fuentes** [comment]
Hello @Whenrow I've back-ported the fix as discussed.

I'm not sure what to do with the field and its compute. Currently I've left it untouched (since this is a stable version) and kept my original patch on the compute to avoid the MemoryError (but still populate the m2m table in case some code relies on that).

PS: The referenced fix also deals with a similar issue for `allowed_mrp_production_ids`. I didn't touch this part since I don't have an actual failing case for it. 

cc: @KangOl

**Comment by aj-fuentes** [comment]
Hello @odoo/rd-logistics 
Would you review this backport please?

**Comment by amoyaux** [comment]
robodoo r+

**Comment by chadt63** [comment]
Not sure if this is the right forum to post this, but I have an issue in my current v13 and v14 builds for two of my Odoo customers that seem directly related to this commit. When they generate a landed cost entry and try to choose the transfers to associate it to, they get a hard error that seems directly related to changing this domain filter. I've attached a text file with the error here. I will also open a ticket with Odoo support in case that is the proper place to post this. Thanks in advance. 

[LandedCostError.txt](https://github.com/odoo/odoo/files/8050083/LandedCostError.txt)

**Comment by aj-fuentes** [comment]
@chadt63 @sugapablo
I think I've found the issue: should be a list not a tuple. PR coming soon.
cc @amoyaux

**Comment by aj-fuentes** [comment]
@chadt63 
>  I will also open a ticket with Odoo support in case that is the proper place to post this

Please put a reference to #84466 on the ticket to expedite its solution.

**Pull request closed without merging**
