### PR TITLE
[IMP] import handler

### PR DESCRIPTION
**Pull request by joanna350**
some refactoring (retained the original style of writing per descriptions) + bugfix

appreciate your thoughts @xmo-odoo who authored this portion @mart-e, if you don't mind checking why cla errors when it seems to be in the branch 13.0

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by joanna350** [comment]
I was looking into the code as the error was returned from reading csv file > 10MB.. as in the attachment. It turns out it just required a separator as an input. Sorry it took a while, hope you did not mind as it is only an idea

Screenshot from 2022-10-29 19-58-44

**Comment by mart-e** [comment]
Hello,

> if you don't mind checking why cla errors when it seems to be in the branch 13.0

It's because it's not in **your** 13.0 branch. It's in https://github.com/odoo/odoo/blob/13.0/doc/cla/individual/joanna350.md but not in https://github.com/joanna350/odoo/blob/13.0-refactor-import-handler/doc/cla/individual/joanna350.md
If you rebase your branch, it should be good.

**Comment by xmo-odoo** [comment]
> some refactoring (retained the original style of writing per descriptions)

Not happening

> bugfix

It is not entirely clear what the bug fix is, you have files for which chardet either blows up or returns an encoding not supported by the standard library (preventing transcoding), but which is still compatible with UTF-8 such that the CSV reader manages to decode it properly?

**Comment by joanna350** [comment]
@mart-e Thank you! Are the tests only triggered at force-push btw?

@xmo-odoo Amazing your memory is intact! I used two equal type of csv files, (both readable by utf-8) just different sizes. For a file > 10 MB, **AttributeError: 'NoneType' object has no attribute 'lower'** was emitted from line 329, `encoding = options['encoding'] = chardet.detect(csv_data)['encoding'].lower()`. 
It was not the case if it read from a smaller file first though. Wondering if the correct file type is saved in the process. What did you mean by 'user-provided' mimetype in the docstring btw?

**Comment by joanna350** [comment]
@mart-e I un-did the merge and rebase as requested just fyr. If you agree with @xmo-odoo that refactoring doesn't add value (even in light of [added commit](https://github.com/odoo/odoo/commit/8b6eecc8f162a667b5cc853138272b202dcc893a) to [16.0](https://github.com/odoo/odoo/blame/16.0/addons/base_import/models/base_import.py?plain=1#L343-L380)) I can close this

**Pull request closed without merging**
