### PR TITLE
[FIX] spreadsheet: remove debug log

### PR DESCRIPTION
**Pull request by LucasLefevre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
@robodoo r- en fait c'est en 16.0 oO

**Comment by rrahir** [comment]
@robodoo r+

**Comment by LucasLefevre** [comment]
robodoo check mon gars
ça a été retarget et t'as pas pigé je pense

**Comment by LucasLefevre** [comment]
robodoo r+

**Pull request closed without merging**
