### PR TITLE
[CLA] Anand Kansagra

### PR DESCRIPTION
**Pull request by anandkansagra**
CLA Signature for Anand Kansagra

@mart-e  This will work now, earlier was signing with GitHub-provided reply email address, thanks!

Supersedes PR #29093

### CODE REVIEW

**Comment by sswapnesh** [comment]
@mart-e 
Why CLA test is passed here ? 
(Even CLA for @anandkansagra  is not here https://github.com/odoo/odoo/tree/11.0/doc/cla/individual)

Ps: @anandkansagra  mart-e wont get ping as you edited message

**Comment by anandkansagra** [comment]
> Ps: @anandkansagra mart-e wont get ping as you edited message

@sswapnesh , This message will help for notification😀
Thanks.

**Comment by mart-e** [comment]
Thanks for the updated PR !

@robodoo r+

**Comment by mart-e** [comment]
@sswapnesh it is not in the standard 11.0 but it is the goal of the PR, to add it. I am not sure not get your question

See https://github.com/odoo/runbot/blob/master/runbot_cla/runbot.py#L16 for the CLA code

**Pull request closed without merging**
