### PR TITLE
[FIX] point_of_sale: float format

### PR DESCRIPTION
**Pull request by simongoffin**
The POS must adapt the float format according to
the language of the user.

opw:639567

### CODE REVIEW

**Comment by simongoffin** [comment]
I checked in the html in the place where we insert the number and I noticed that:
<input class="paymentline-input" step="0.01" type="number" value="0.00">
The "," and the "." are taken into account but if you want to change the decimal separator in the language
by something like "%" it 's not taken.

**Comment by simongoffin** [comment]
Alright!

**Comment by beledouxdenis** [comment]
There is a little issue when I type a letter in the amount paid input :p, and it did not happen before the patch.

**Comment by simongoffin** [comment]
Alright now :-)

**Comment by beledouxdenis** [comment]
If we take inspiration from almost everywhere in the webclient (`view_form.js`, `search.js`), you should actually do:
```
+                    var amount;
+                    try {
+                        amount = instance.web.parse_value(this.value, {type: "float"})
+                    } catch(e) { 
+                        amount = 0
+                    }
+                    node.line.set_amount(amount);
```
https://github.com/odoo/odoo/blob/8.0/addons/web/static/src/js/search.js#L1466-L1470

**Comment by beledouxdenis** [comment]
Closed with 5a10903e9b3b3f8143a8f8d3703632e3243efead.

**Pull request closed without merging**
