### PR TITLE
[FIX] website: fix page properties auto save

### PR DESCRIPTION
**Pull request by xO-Tx**
1- Go to page properties > change the URL of a page.
2- A list of dependencies appears on a popover.
3- Click on a dependency > you are redirected to the related object
but the URL change for your page was "saved".

The changes on form views are automatically saved when the view is left
using a "beforeunload" handler.

The goal of this PR is to fix this behaviour by making the form view
dialog auto save optional.

task-2687506

### CODE REVIEW

**Comment by sdegueldre** [comment]
Shouldn't the dependency links simply be in target="_blank" so that they don't close the current page?

**Comment by rdeodoo** [comment]
@sdegueldre :+1: 
That part (blank link) could even be added in stable as a fix one day (not a priority now imo), this is bad UX.
Never noticed that, I think I never clicked on one of those links.

**Comment by qsm-odoo** [comment]
I personally think that all _blank links leads to bad UX (I can't remember being happy about someone deciding for me to open something in a new tab without me asking it), so in this case a _blank link from the backend to the backend... seems even uglier. But indeed, if this can avoid "complex" changes about the form auto-save and as it is a micro-feature, I'd say let's not bother @xO-Tx : let's use _blank links instead :wink: (but in master only, not worth a change in stable IMO)

**Comment by xO-Tx** [comment]
> Shouldn't the dependency links simply be in target="_blank" so that they don't close/replace the current page/tag?

@sdegueldre @rdeodoo @qsm-odoo Yes! this works for links but I just added the option to be able to prevent all `beforeunload` triggers (page reload will urgentsave the dialog too...) so I think this depends on if we want to prevent dialog save **when page is left** or only **left by clicking on dialog links** ? if it's just for link, I think target="_blank" is OK too...

**Comment by rdeodoo** [comment]
> when page is left

I believe this is another debate -> Should we save or not when user is for instance manually reloading his page.
Clearly not IMO, he didn't want to save, so I'd keep your diff.

But on top of that, I'd still add the `_blank` links, I'd never want those links to open in the current page in the middle of my page properties edition. And this is clearly something I forgot when developing the "feature" :grimacing: 
Not adding the `_blank` would be choosing between wiping the user change (with or without confirmation box) or auto saving it, both are terrible over opening the page in a new tab IMO.

**Comment by qsm-odoo** [comment]
> Not adding the _blank would be choosing between wiping the user change (with or without confirmation box) or auto saving it, both are terrible over opening the page in a new tab IMO.

For the record, IMO, using _blank is more terrible than a confirmation box if it is well implemented. You open a new tab, you'll lose some lambda user who won't see it and probably even more that won't know they have to close the tab to come back to their previous edition of the page properties. Even more so in mobile which is clearly not made to encourage new tab uses. That's also probably bad for accessibility but don't know much about it, so just a guess (and in this case, the multi popup + popover is probably very bad for accessibility anyway).

But again, it's a detail and, for this micro-feature, I don't care. So as you all prefer _blank links, let's do it. And as @rdeodoo said, you can keep the optional autosave diff in a separated commit @xO-Tx, we'll discuss with the framework team about it I guess :grimacing: I doubt we are the only one who will find cases of autosave being very bad.

**Comment by qsm-odoo** [comment]
The auto-save stuff will be left unchanged and we will only use _blank links. This PR have 4 commits, 3 are work from the PR at https://github.com/odoo/odoo/pull/97343. That PR was split into two, thanks to https://github.com/odoo/odoo/pull/98180. The only commit of this current PR (_blank links) will be moved into this split (at https://github.com/odoo/odoo/pull/98180). Closing this.

**Pull request closed without merging**
