### PR TITLE
[IMP] website_event: add ongoing option to snippet

### PR DESCRIPTION
**Pull request by Odoonan**
Add a filter 'Upcoming and Ongoing Events' to allow the user to have ongoing events selected by the dynamic snippet.

Task-3628185

### CODE REVIEW

**Review by std-odoo — APPROVED** [review]
LGTM :)

**Review by awa-odoo — COMMENTED** [review]
Hello @Odoonan 

A couple minor comments otherwise looking good.

Thanks & cheers!

**Comment by Odoonan** [comment]
Hello @awa-odoo ,

I've done the changes :) 

Cheers!

**Comment by awa-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
