### PR TITLE
[CLA] *: Add twio.tech CLA

### PR DESCRIPTION
**Pull request by TwioTech**
--
I confirm I have signed the CLA and read the PR guidelines at [www.odoo.com/submit-pr](http://www.odoo.com/submit-pr)

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by hwangh95** [comment]
Hello and thank you for the quick merge! Just a small question, we made the PR from 16.0, but we would eventually like to work from 15.0 as well.

Will this backport the CLA as well or only forwardport?

**Comment by mart-e** [comment]
Hmm indeed, it would have been better to merge the CLA in 15.0 then .
But don't worry, that's still possible, simply, when you make your contribution in 15.0, you can add the CLA file alongside your code in the same PR :)

**Comment by hwangh95** [comment]
Ahh alright. Thank you!

**Pull request closed without merging**
