### PR TITLE
[FIX] No Analytic accounts in invoice lines when invoicing based on incoming shipments on purchase order

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
#1820

**Comment by adrienpeiffer** [comment]
https://github.com/odoo/odoo/pull/5127

**Comment by antonylesuisse** [comment]
LGTM, could you accept the CLA by following the procedure. I would like to test the new CLA runbot intergration ?

**Comment by adrienpeiffer** [comment]
@antonylesuisse Thanks ! I create the PR for CLA: https://github.com/odoo/odoo/pull/5136

**Comment by odony** [comment]
@adrienpeiffer If you'd like to have the CLA check green you should now rebase your branch on 8.0 so your CLA signature will be included (your CLA branch was merged). Alternatively you could have simply added the CLA signature in this existing PR branch, but it's fine this way too. Thanks!

**Comment by adrienpeiffer** [comment]
Thanks @odony ! Rebased on 8.0

**Comment by antonylesuisse** [comment]
Hourrah first green CLA !

**Comment by sbidoul** [comment]
'hope a prompt merge will ensue :wink:

**Comment by odony** [comment]
Thanks!

**Comment by adrienpeiffer** [comment]
Thanks @odony

**Pull request closed without merging**
