### PR TITLE
[FIX] Return picking moves do not match the return picking type

### PR DESCRIPTION
**Pull request by wtaferner**
and also do not have a warehouse set (which can be retrieved based on the picking_type in use)
## Impacted versions:

8.0 and above
## Steps to reproduce:
- Create a stock picking and add some moves to this stock picking (use a picking type which does not have itself as return picking type)
- Confirm and complete the picking and moves
## Current behavior:
- In case you do a return on this picking the same picking type is used as the original picking
## Expected behavior:
- The return picking type is respected

Additionally, this fix does also add the correct warehouse on the return picking which might be lost as well.

Linked to OPW-639452
@mart-e 
I did this quite some time ago and it seems to be an easy and quite valuable fix.

### CODE REVIEW

**Comment by jco-odoo** [comment]
This PR looks ok, but I am curious if there are other reasons than for the sake of consistency, because putting a warehouse_id there could have consequences for the routes (but normally, you don't put push on output).

**Comment by wtaferner** [comment]
Hmm, in my use case the warehouse was added for additional information on the picking and therefore enriching automatically info on stock moves, etc. whereas I was not aware that this isolated additional info on a picking (for grouping, filtering and other information retrieval and representation) could have (negative?) consequences. Just let me know if I should remove it for the PR in case it does not suit a common interest.

**Comment by jco-odoo** [comment]
I think we can merge as it is now.

On Tue, May 26, 2015 at 4:31 PM, Wolfgang Taferner <notifications@github.com

**Comment by nim-odoo** [comment]
Closed with e5a8d21a6094593ea598f22352189013fec11bfd

**Pull request closed without merging**
