### PR TITLE
[BACKPORT] [IMP] stock: better link between SO/PO/MO

### PR DESCRIPTION
**Pull request by Rad0van**
Description of the issue/feature this PR addresses: This is an attempt to backport (as suggested in #52402) from #40573, #41046, #43366 and #45800. The main PR should be #43366 the rest seemed necessary for it to work. Any suggestions are welcome.
,
Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Rad0van** [comment]
@pedrobaeza, @Yenthe666 and @sle-odoo would you be so kind please and provide some feedback / guidance? Thank you.

**Comment by sle-odoo** [comment]
@Rad0van we don't plan to backport this feature in v13

**Comment by Rad0van** [comment]
> @Rad0van we don't plan to backport this feature in v13

@sle-odoo I'm a bit confused. In #52402 backport was suggested as a way to achive this functionality and it was you who even pointed to the main PR responsible for this to start the backport. So I was under the impression that if someone did it, it could/would be included in 13.0 As we really need this here I gave it a try.

**Comment by pedrobaeza** [comment]
@Rad0van sorry if I was not clear enough: for me backporting that is to have a module in previous version doing that. Examples:

- https://github.com/OCA/manufacture/tree/12.0/mrp_subcontracting as a backport of the v13 module (this one was easy, as it was already a module).
- https://github.com/OCA/web/tree/10.0/web_widget_domain_v11: extraction of the widget from v11 `web` module.
- https://github.com/OCA/stock-logistics-warehouse/tree/12.0/sale_stock_info_popup: extraction of v13 feature for showing the stock information in a popup in the sales order line.
- etc

**Comment by sle-odoo** [comment]
Sorry if we misunderstood each other, but the backport was for you to have this feature on your instance. :/

**Comment by Rad0van** [comment]
> @Rad0van sorry if I was not clear enough: for me backporting that is to have a module in previous version doing that. Examples:
> 
> * https://github.com/OCA/manufacture/tree/12.0/mrp_subcontracting as a backport of the v13 module (this one was easy, as it was already a module).
> * https://github.com/OCA/web/tree/10.0/web_widget_domain_v11: extraction of the widget from v11 `web` module.
> * https://github.com/OCA/stock-logistics-warehouse/tree/12.0/sale_stock_info_popup: extraction of v13 feature for showing the stock information in a popup in the sales order line.
> * etc

@pedrobaeza sorry, I do not seem to follow. Do you mean to create modules that will hold the required functionality on top of stock Odoo? Looking at all the changes to the code I feel it is not really possible in this case. Or did I misunderstand you?

**Comment by pedrobaeza** [comment]
Yes, I suggest that as maintainability choice, but indeed it requires more knowledge and inheritance tricks. Doing the backport in your fork is another option as suggested by @sle-odoo, but I don't recommend that for the same maintainability question.

**Comment by Rad0van** [comment]
> Sorry if we misunderstood each other, but the backport was for you to have this feature on your instance. :/

@sle-odoo that would fine if we were not going to use Enterprise version hosted on Odoo.com :-( As we really need this functionality I took upon creating the backport in hoping it would enter the mainline code and appear there. Can you suggest some alternative approach?

**Comment by Rad0van** [comment]
> Yes, I suggest that as maintainability choice, but indeed it requires more knowledge and inheritance tricks. Doing the backport in your fork is another option as suggested by @sle-odoo, but I don't recommend that for the same maintainability question.

@pedrobaeza as I wrote to @sle-odoo : we are in the last stages of the project with local partner here to deploy Enterprise version on Odoo.com I assess the inheritance trickery and all the stuff would be enormous and I am not sure I know enough to pull this out in reasonable time. Nor the local partner here.

**Comment by pedrobaeza** [comment]
@Rad0van for now I'm afraid the only options are the suggested ones. As soon as v14 is out and migration is ready, Odoo will be able to migrate your DB to that version (excluding third-party modules or paying the third-party modules maintenance fee).

**Comment by Yenthe666** [comment]
Yep. So to conclude you have two options:
- Wait for V14 to have the features that are now in the master version
- Backport this code to V13 in a custom module and move from odoo.com to your own Odoo instance (hosted on your own).

This is for sure not going to land in the current stable V13. It breaks a lot of stable database rules.

**Comment by Rad0van** [comment]
I got it a bit wrong: we're going to use odoo.sh for hosting so I guess custom modules are a way.

However waiting for v14 is a no-go as we're currently trying to get some required modules to v13 (I am doing my best to migrate them) and AFAIK v14 is few months away and even few more before migrations are available...

So will have to think if the custom module would not be an option after all, maybe just a bit of limited functionality as we for example do not need MO at all.

**Comment by Rad0van** [comment]
> Yep. So to conclude you have two options:
> 
> * Wait for V14 to have the features that are now in the master version
> * Backport this code to V13 in a custom module and move from odoo.com to your own Odoo instance (hosted on your own).
> 
> This is for sure not going to land in the current stable V13. It breaks a lot of stable database rules.

@Yenthe666 to be able to better assess possibilities and limitations; can you please elaborate a bit on the breaking a lot of stable database rules? What does that mean?

**Comment by pedrobaeza** [comment]
@Rad0van yes, with odoo.sh, there's no need of going to custom hosting for having extra third-party modules. @Yenthe666 has confused it with Odoo online.

These are the stability guidelines: https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

**Comment by Rad0van** [comment]
> Yes, I suggest that as maintainability choice, but indeed it requires more knowledge and inheritance tricks. Doing the backport in your fork is another option as suggested by @sle-odoo, but I don't recommend that for the same maintainability question.

@pedrobaeza I initially thought this to be above my skills but I gave it a try and it seems to work fine. Limited to sale, purchase and stock (left out mrp as we do not really need it). Managed to squeeze all the changes to a module without needing to change any database structures besides this:

```
addons/stock/models/stock_rule.py
+     stock_move_ids = fields.One2many('stock.move', 'group_id', string="Related Stock Moves")

```
Do you think it's worth trying to submit this module here? Or into OCA?

**Comment by pedrobaeza** [comment]
A new module is also not accepted here, so you can go with OCA option if you want. About the new field, you can include it in the module (with no name collapsing).

**Comment by Rad0van** [comment]
> A new module is also not accepted here, so you can go with OCA option if you want. About the new field, you can include it in the module (with no name collapsing).

@pedrobaeza thanx for reply. Will do that although not sure in which repository to propose as this concerns sale, purchase and stock. What does "no name collapsing" mean?

**Comment by pedrobaeza** [comment]
OCA/stock-logistics-workflow is a good candidate. Name collapsing means that you chose a field name that is not the same than existing ones.

**Comment by Rad0van** [comment]
> OCA/stock-logistics-workflow is a good candidate. No name collapsing means that you chose a field name that is not the same than existing ones.

@pedrobaeza thanx for the tip. The field name does not technically exist yet - it only exists in the same form and place in master (future version). As far as I understand it, it only gives access to the opposite side of this relation defined in StockMove:
`group_id = fields.Many2one('procurement.group', 'Procurement Group', default=_default_group_id)
`
I guess there should be no issue renaming it but it seemed to me it would be good to keep it this way. But I will follow your advice on this.

**Comment by pedrobaeza** [comment]
Yes, if no name collapsing, keep it with the same name.

**Pull request closed without merging**
