### PR TITLE
[FIX] point_of_sale: handle singleton exception for PoS config

### PR DESCRIPTION
**Pull request by ghost**
Before this commit a singleton error is raised when writing to several
PoS configs at the same time.
    
After this commit, it is possible to write on multiple records at the
same time.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by LuisMzz** [comment]
@luisg123v Please review

cc @desdelinux

**Review by luisg123v — COMMENTED** [review]
Commit description:

I'd just say it's triggered when writing to several PoS configs at the same time, because this is probably not functionally reproducible.

**Comment by LuisMzz** [comment]
@luisg123v I already updated the description

**Review by desdelinux — COMMENTED** [review]
LGTM

cc @rhe-odoo

**Review by caburj — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
