### PR TITLE
[FIX] stock: pack operations take into account the destination location

### PR DESCRIPTION
**Pull request by nim-odoo**
When a picking contains several stock moves for the same product but different
location_dest_id, the pack.operation created merge these two stock moves.
This leads to quants wrongly calculated.

opw-640414

### CODE REVIEW

**Comment by jco-odoo** [comment]
I don't know how this issue still got through, as the stock moves in a picking should all have the same destination location.  Otherwise, afterwards, the algorithm for matching the picking's moves and the operations should also take into account which move has which destination locations and the situation where one picking can move products from one location to another, is ugly and we want to avoid it in the future.  In v9, the location destination will be chosen on the picking for that reason.  We had a branch to put a constraint on the moves to warn users for this.  In fact putting a raise in this function would even make more sense.  "Moves in the same picking should have the same source/location (unless they are scrapped)"

**Comment by nim-odoo** [comment]
Code adapted

**Comment by Parahexen** [comment]
If "Moves in the same picking should have the same source/location (unless they are scrapped)",
what if we produced a sale order, but it required to pick part of goods from warehouse A location 1, and part of goods from warehouse A location 2, even part of goods from warehouse B?
So we have to create three different SO to satisfy the requirement? Or we have to internal transfer A2 and B to A1 then pick all from A1?
Is there any dignity way to do that?

**Comment by jco-odoo** [comment]
That should be done with the routes.  You can put a route on a sale order line to override the default warehouse routes given in the sale order.  (or put it on the config of the product e.g.)  That way, you can create one SO with different pickings behind it.

**Comment by pedrobaeza** [comment]
I see reasonable to block different destination locations if that provokes a problem in quants, but why source location? Defining routes is very tedious. And also if the problem comes when having same product on multiple lines, why not simply check that (if there are some moves for the same product with incompatible location). This will solve half of the current problems. May I do the patch?

**Comment by jco-odoo** [comment]
No, I can not agree with this.  You can have different locations in source and destination, they should only be child of the same parent location.  If you are going to pick from different warehouses, you should use different pickings.  And in most cases, the warehouse form allows you to configure the routes.

**Comment by pedrobaeza** [comment]
Yeah, I'm talking about different locations inside same warehouse. Imagine this warehouse distribution:

* WH
  * Rack 1
  * Rack 2

I have "Product 1" stock in "Rack 1" and in "Rack 2". For an specific delivery order, I want to take the stock from "Rack 2", but "Check availability" button always takes the stock from "Rack 1". The only solution is to change source location from "WH" to "Rack 2", and then press "Check availability". I know that you can change the location, press the button, and then change again the source location to "WH", but if this is also allowed, what is the sense of putting this check and make things harder for this case? I think we should restrict the constraint at least to the same product from different locations (and I think that also only in the operations that generates quants, not the ones that move them).

**Comment by jco-odoo** [comment]
No, it is better to make the pack operations visible again. Check in v9 how
it is done there.  (you could change the views in v8)

**Comment by pedrobaeza** [comment]
Then you are proposing to leave the standard as is? Would you accept a PR that restricts the locations for the same product only instead generally?

**Comment by santiago1976** [comment]
This topic is why Odoo will never be able to compete with other ERPs such as NAV, SAP, etc. This is a basic operation in any warehouses, the power to distribute different products between different locations in the same PO... it seems incredible that Odoo does not support it in the standard .

If the algorithm for matching the picking's is not correct, it should fix it, but do not remove a basic functionality in whatever warehouse.

**Comment by pedrobaeza** [comment]
@santiago1976 this thread is quite old (v8) and this is not happening anymore in new versions, so please avoid that judgment sentences about what can compete with what.

**Comment by catleya79** [comment]
Hello, can anyone tell me how to pick different source location with barcode scanner in pick operation? im using odoo enterprise v.11
Many thanks,
Cat

**Pull request merged**
