### PR TITLE
[FIX] stock: it is possible to modify a done stock.move

### PR DESCRIPTION
**Pull request by fmdl**
present in V10

@jco-odoo 

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

The fact that tests are failing is probably a good indication it is not a good idea to change that in a stable version.

**Comment by fmdl** [comment]
with only the state in frozen field, it works.

what do you think ? (if ok, I will rewrite the commit).

I have made this commit, because we don't know why a stock.move have change state 'done' to 'waiting' on a customer database.

**Comment by jco-odoo** [comment]
The state is readonly True and that was sufficient so far.  You talk about
v10, but the commit is in v11.  And in the chatter of the Picking it does
not say it changed?

**Comment by fmdl** [comment]
it is only readonly in UI.

I say that in V10, some field are block when the state is 'done', this blocking doesn't exist in V11.

There are no hard blocking function for the state field.

Yes the chatter on the picking say this strange change :
image

**Pull request closed without merging**
