### PR TITLE
[FIX] l10n: use account types from account module

### PR DESCRIPTION
**Pull request by RomainLibert**
l10n modules should avoid creating their own account.account.type
and instead use the standard account.types defined in the account module

### CODE REVIEW

**Comment by RomainLibert** [comment]
We still have to fix those occurences
```
addons/l10n_pl/data/l10n_pl_chart_data.xml
6:    <record model="account.account.type" id="account_type_tax">
7-      <field name="name">Podatki</field>
8-    </record>
9-
10:    <record model="account.account.type" id="account_type_settlement">
11-      <field name="name">Rozrachunki</field>
12-    </record>

addons/l10n_syscohada/data/l10n_syscohada_chart_data.xml
3:    <record model="account.account.type" id="account_type_special">
4-        <field name="name">Comptes spéciaux</field>
5-    </record>
6-
7-    <!-- Chart Template -->
8-    <record id="syscohada_chart_template" model="account.chart.template">

addons/l10n_th/data/l10n_th_chart_data.xml
6:<record id="acc_type_reconciled" model="account.account.type">
7-    <field name="name">Reconciled</field>
8-</record>
9-
10-<!-- CHART OF Template -->
11-
```

**Comment by RomainLibert** [comment]
@d-fence This PR should fix the l10n runbot

**Comment by jco-odoo** [comment]
@RomainLibert Are we sure for the Greek one?

**Comment by jco-odoo** [comment]
@jcr-odoo Can you ask for the Polish account types?  Not sure the Greek ones are really off balance and maybe we can set an internal group (equity, asset, liability, income, expense, off_balance) for the comptes spéciaux of syscohada?

**Comment by RomainLibert** [comment]
@jco-odoo I don't know, the Greek one is called "other", I suppose it is ok to use the off balance in this case.

**Comment by jco-odoo** [comment]
@RomainLibert It is just that the name of the accounts related don't really seem off-balance, so I would keep their account type.  However, this made me think: the accounts were off-balance before, because if you created your own account type, it won't appear on the balance anyways.  So, for the remaining for Greece, syscohada, the other Polish, we could change the internal group to off balance and just keep it as we are not sure if it is really meant as off balance.  It won't change anything to the current behaviour.

**Comment by RomainLibert** [comment]
@jco-odoo Can this be r+?

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
Thanks a lot!

**Pull request closed without merging**
