### PR TITLE
[CLA] Studio73 signature

### PR DESCRIPTION
**Pull request by fuentes73**
Add Studio73 CLA v1.0 signature

### CODE REVIEW

**Comment by hildickethan** [comment]
Can we get some love here? So https://github.com/odoo/odoo/pull/68255 can be merged? Sorry to ping @bfr-o but since you approved my PR, is there anything you can do to help push this along?

**Comment by bfr-o** [comment]
@hildickethan I don't have the rights to r+ myself, but @oco-odoo will take care of https://github.com/odoo/odoo/pull/68255 and maybe @mart-e can take care of this PR.

**Comment by hildickethan** [comment]
Thanks!

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
