### PR TITLE
[IMP] l10n_ua,l10n_in_schedule6: adapt tax templates

### PR DESCRIPTION
**Pull request by RomainLibert**
Oversight of
https://github.com/odoo/odoo/commit/3936d655c4bfd845b6ead724cecdc8e7c62816eb#diff-0c17fe17beaac1a04b7c4a7944789d08

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rgo-odoo** [comment]
@RomainLibert may be you can see PRs #33927 (task 2005876) #33926 (task 2005878)

**Comment by RomainLibert** [comment]
@oco-odoo What do we do with this PR finally?

**Comment by oco-odoo** [comment]
@RomainLibert I'm cherry-picking it into my own branch containing all the fixes to be done on l10n modules, here https://github.com/odoo-dev/odoo/tree/saas-12.3-fix-l10n-taxes-oco . This way, I'll merge everything at once (and test it before with the verificator implemented withing the migration script). Thanks for your help, anyway!

**Comment by RomainLibert** [comment]
@oco-odoo 
Ok perfect then

**Pull request closed without merging**
