### PR TITLE
Create KomarovAlea.md

### PR DESCRIPTION
**Pull request by KomarovAlea**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by KomarovAlea** [comment]
What's wrong with my PR?

**Comment by pedrobaeza** [comment]
Until CLA is not merged, you will get that red flag.

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `34191760+KomarovAlea@users.noreply.github.com`
- you are signing _for_ the address `Ko...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by KomarovAlea** [comment]
I removed the private mode from my mail box in the github settings.
Can you accept my PR now?

**Comment by mart-e** [comment]
@KomarovAlea you need to make a new commit using the new email address (e.g. modify the CLA file, or recreate this PR in a new branch if you are unsure). The idea is that the commits must be made with the same email address as the one signing.
Changing the privacy will impact new commits but not the previous one.

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it has been integrated into Odoo at revision https://github.com/odoo/odoo/commit/1f971ce252815df5ff316cd553ac9f771981d155.
Future pull requests made on odoo will be validated by the runbot.
Regards

**Pull request closed without merging**
