### PR TITLE
[FIX] l10n_ch: fix header merging when printing multi invoices

### PR DESCRIPTION
**Pull request by sonhd91**
Currently, there is an issue with merging the header when printing multiple invoices with QR codes,  I suspect it is related to [wkhtmltopdf](https://github.com/odoo/odoo/blob/16.0/odoo/addons/base/models/ir_actions_report.py#L682). Therefore, I have implemented a temporary fix for now.

Steps to reproduce:

1. Install l10n_ch.
2. Switch the company to CH Company.
3. Go to Settings > Accounting > Customer Payments (enable QR Codes).
4. Go to Accounting > Customers > Invoices. Change the country of some customer invoices to Switzerland.

Select multiple invoices in tree view and print them.

image

image

### CODE REVIEW

**Comment by nilshamerlinck** [comment]
hello @casp-odoo we have a connex question: 
- we noticed that the Follow-up report [includes the Invoices](https://github.com/odoo/enterprise/blob/16.0/account_followup/views/report_followup.xml#L48)
- but it won't include their QR-codes because of [this](https://github.com/odoo/odoo/blob/16.0/addons/l10n_ch/models/ir_actions_report.py#L36) even when the QR-codes are enabled/available for these invoices
- is it on purpose?

**Comment by casp-odoo** [comment]
hello @nilshamerlinck , 
This is indeed a nice catch, as this is not the intended behavior. A task has been created to fox this. 
Thanks for bringing this to our attention :)

**Comment by nilshamerlinck** [comment]
Hello @casp-odoo 
- sorry to ping you as you might have a lot on your plate already with the new version coming...
- I just wondered if an ETA was defined on the task you mentioned to fix the QR-codes absence?
- fyi I was told that opw-3382034 has been created at some point to report this issue, if it can help
- thanks!

**Comment by casp-odoo** [comment]
Hello @nilshamerlinck, 
The task has yet to be approved, so I can't give you any ETA at the moment. The task pipe is indeed pretty full with the major improvements for the new version, so I don't know when we'll have a chance to get to this. 

Thanks for the ticket link :)

**Pull request closed without merging**
