### PR TITLE
[FIX] native notification error on android chrome

### PR DESCRIPTION
**Pull request by leorochael**
Description of the issue/feature this PR addresses:

Android Chrome blocks direct instantiation of `window.Notification`.

Notifications should be done using `ServiceWorkers` on that platform.

See: https://bugs.chromium.org/p/chromium/issues/detail?id=481856#c3

Since we don't use `ServiceWorkers` for notifications, don't attempt to request notification permission if instantiating `new Notification()` is forbidden.

Current behavior before PR:

User is prompted to allow notifications using the `o_mail_annoying_notification_bar`, but when the user grants the notification permission, it's going to be even more annoyed with an error like:

chrome-android-notification-error

The error message and traceback in the screenshot above, (using `debug=assets`) is:

```
Uncaught TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.

http://192.168.105.219:9069/mail/static/src/js/utils.js:22
Traceback:
TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
 at _send_native_notification (http://192.168.105.219:9069/mail/static/src/js/utils.js:22:24)
 at Object.send_notification (http://192.168.105.219:9069/mail/static/src/js/utils.js:12:13)
 at notify_incoming_message (http://192.168.105.219:9069/mail/static/src/js/chat_manager.js:70:11)
 at http://192.168.105.219:9069/mail/static/src/js/chat_manager.js:107:25
 at Function._.each._.forEach (http://192.168.105.219:9069/web/static/lib/underscore/underscore.js:145:9)
 at add_message (http://192.168.105.219:9069/mail/static/src/js/chat_manager.js:85:11)
 at http://192.168.105.219:9069/mail/static/src/js/chat_manager.js:505:9
 at http://192.168.105.219:9069/web/static/lib/jquery/jquery.js:3276:89
 at fire (http://192.168.105.219:9069/web/static/lib/jquery/jquery.js:3119:58)
 at Object.add [as done] (http://192.168.105.219:9069/web/static/lib/jquery/jquery.js:3165:49)
```

Desired behavior after PR is merged:

Don't attempt to request notification permission on browers that require `ServiceWorkers` for native notifications (i.e. Android Chrome).

---

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@ged-odoo Could you have a look please ? Thanks !

**Comment by ged-odoo** [comment]
I'll take care of this asap (so, not so soon, but someday)

**Comment by leorochael** [comment]
By the way, I didn't make it clear on the description of this PR, but the error with the traceback above is not raised when the user requests and accepts notification permission, which looks like it worked correctly, but later when receiving notifications for messages.

This is extremely annoying as the tracebacks happen completely out of control of the user.

**Comment by C3POdoo** [comment]
Dear @leorochael,

Thank you for your contribution but the version 10.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
