### PR TITLE
[FIX] hr_recruitment: realign kanban footer items

### PR DESCRIPTION
**Pull request by edi-odoo**
The kanban's footer elements were misaligned vertically, specifically the status icon.

task-3473010

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by morm-odoo** [comment]
LGTM 👍

**Review by morm-odoo — APPROVED** [review]

**Comment by edi-odoo** [comment]
@pparidans could you check this one too please ? Thank you !

**Review by sofiagvaladze — APPROVED** [review]

**Review by pparidans — CHANGES_REQUESTED** [review]
Should actually be a `[FIX]`.
But for the rest, it's all good! Thx :+1:

**Comment by edi-odoo** [comment]
> Should actually be a `[FIX]`. But for the rest, it's all good! Thx 👍

Thanks @pparidans !

**Review by pparidans — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
