### PR TITLE
[IMP] web: remove unused legacy_dialog_mapping

### PR DESCRIPTION
**Pull request by pparidans**
task-3439226

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by adr-odoo — APPROVED** [review]
@robodoo r+

**Comment by pparidans** [comment]
@robodoo retry

**Comment by pparidans** [comment]
> @robodoo r-
> 
> Seems to have broken the `planning_test_tour` of enterprise: https://runbot.odoo.com/runbot/build/50465913
> 
> this failed two stagings.

That's... weird. Actually, this commit comes from another branch where the enterprise build was successful... :shrug: 

Will dig a bit more about this...

**Review by adr-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
