### PR TITLE
[FIX] Fiscal positon - Recompute taxes for draft invoices.

### PR DESCRIPTION
**Pull request by simongoffin**
opw-625688

Inspired by the [invoice_fiscal_position_update module](https://github.com/OCA/account-invoicing/tree/8.0/invoice_fiscal_position_update)

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi,
Thanks for this patch !
:question: : l622 + l632 you take in account only taxes_id (customer taxes). This code is ok for sale invoices. But for purchase invoices, don't you have to use supplier_taxes_id ?

Regards.

**Comment by beledouxdenis** [comment]
I believe Sylvain has a point here :). Good catch.

**Comment by alexis-via** [comment]
First, the  file account_invoice.py uses the new API, so it's surprising to see code with the old API inside a file written with the new API.

Instead of re-inventing the wheel, you could take the code from OCA/account-invoicing/invoice_fiscal_position_update, it would avoid many mistakes: the issue pointed by Sylvain Le Gal, and also the fact that you need to update the account_id on account.invoice.line.

:-1:

**Comment by beledouxdenis** [comment]
Hello Alexis, 

We sure will have a look to your code from OCA/account-invoicing/invoice_fiscal_position_update.

Nevertheless, you should understand that the Odoo world is big and we do not have eyes everywhere. We couldn't have find this fix by our own. You cannot really blame Simon of not having had a look in the OCA to check if, by chance, you already fixed this issue. Besides, you were probably aware of this fix because you contributed to it.

@simongoffin :https://github.com/OCA/account-invoicing/blob/8.0/invoice_fiscal_position_update/account_invoice.py

Regards,

**Comment by alexis-via** [comment]
Now that it is my code, I can't disapprove :) :+1:

**Comment by legalsylvain** [comment]
Hi, again !

:question: Why don't you manage the case 'lines_without_product', that was managed in 'invoice_fiscal_position_update' module ?
* It's a good test and a good information for end users;
* It makes the module 'invoice_fiscal_position_update' fully useless;

:question: I'm not copyright expert, but when people copy / paste code from other project, they have to copy / paste author name in the corresponding section ?

Otherwise :+1: 

Regard.

**Comment by mart-e** [comment]
@simongoffin I agree with @legalsylvain, when copy-pasting code, please try to keep original author (with `--author=".."` option) In your commit. Not sure of the legal aspect but it's at least more polite :)
Thanks.

**Comment by simongoffin** [comment]
Ok I think that writing 'Inspired by ...' in the message of the commit was enough

**Comment by mart-e** [comment]
@simongoffin oh yes it's another way to do it (I missed the commit message). In launchpad time, we used often "courtesy of <author>" during merge.

**Comment by odony** [comment]
@simongoffin @mart-e Actually I suggested Simon use "Inspired by" because he partially rewrote the patch (and of course there aren't 50 different ways to write procedural code like this in the new API). Regarding the warning, it's outside of the scope here, and the point was not really to replicate what `invoice_fiscal_position_update` does.

On a side note, I'm quite surprised by the rudeness shown by some people here. It seems we are a bit too quick in forgetting the number of mistakes and subpar code we wrote in our early days...

**Comment by antonylesuisse** [comment]
We wont merge it anyway, it's too error prone as we are never sure of the reverse fiscal position mapping. Insead we will update data with the correct res.coutntry group so that it happens less frequently.

**Comment by odony** [comment]
Yes on second thought we probably don't want to do any of this at all, it's touchy for invoices.
Imagine you have manually set the taxes on the lines when recording the invoice, and you later change the fiscal position. Chances are you already did the right (or perhaps custom) mapping, and you're gonna lose everything without noticing it, because the default mapping doesn't match.
Forcing users to do those changes explicitly is much safer. In the context of sales orders it is relatively fine because the invoice will still be reviewed later and taxes can be corrected, but not for invoices.

@antonylesuisse Rather than closing the issue, shouldn't we instead add a simple `onchange` that warns the user that taxes may need to be updated, if there are existing lines in the invoice?

**Comment by antonylesuisse** [comment]
Yes @simongoffin add a warning

And set the correct country/ountry group for fiscal position defined in l10n_xx, 8.0 or master ?

**Pull request closed without merging**
