### PR TITLE
[IMP] mail: rename 'MediaPreview' to 'CallDemoView' 

### PR DESCRIPTION
**Pull request by alexkuhn**
Task-2871939

### CODE REVIEW

**Review by phenix-factory — COMMENTED** [review]
I agree that `media_preview` isn't a great name, but `call_test_view` is looking worst to me.

First there is the `_view` used for a component, that should be reserved for model view. `test` suggest that this component is related to the test suite ?
Could be better to go with something like `guest_call_preview` ?

**Comment by alexkuhn** [comment]
It's a model view, so I think it's fine to have "view" in its name.
It's not easy to find a good name for it. Current suggestion comes from stating that this is a "view to test call".

- I'm not fond with "guest" in name, because while I get it's currently only used with guests, it's conceptually not exclusively related to guests.
- "Preview" does not fit that well IMO. For me, "preview" is a small view before an official view. I get that some users will do this before actually make a call, and it's even enforced with the guest feature... But again, conceptually this should not reduced to a "before" step of a call. On Discord for example, I can skip this step altogether and just be in a call. Also, I can test call with myself at any time in the settings.

So I understand my suggestion "CallTestView" is not great, but I struggle to find something much better.

**Comment by phenix-factory** [comment]
@alexkuhn Here is some suggestion based on what you seams to look after:

- `call_sample_view`
- `call_demo_view`
- `call_example_view`
- `call_staging_view` or `call_stage_view`

**Comment by alexkuhn** [comment]
Ok for `call_demo_view`

**Comment by alexkuhn** [comment]
Changes done

**Review by phenix-factory — APPROVED** [review]
LGTM

**Pull request closed without merging**
