### PR TITLE
[FIX] web_editor: restore ace style

### PR DESCRIPTION
**Pull request by mgeubelle**
The recent refactoring odoo/odoo@f296992 wrongly moved the ace editor
style from `web_editor` to `website`, even though ace is in `«eb_editor`.

The editor is also used in Studio (which does not depend on website) so
the style was missing in this case.

Task 1951290

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo-delegate=Gorash

**Comment by aab-odoo** [comment]
robodoo delegate=Gorash

**Comment by Gorash** [comment]
robodoo r+

**Comment by mge-odoo** [comment]
robodoo retry

**Pull request closed without merging**
