### PR TITLE
[ADD] activate suds library for Python (SOAP client)

### PR DESCRIPTION
**Pull request by rim-odoo**
Dependency for future delivery providers integration
- Task: https://www.odoo.com/web/#id=19552&view_type=form&model=project.task&menu_id=3942&action=327

### CODE REVIEW

**Comment by guewen** [comment]
You may want to use `suds-jurko` which is a maintained fork of `suds`. `suds` is abandoned since years (last release on 2010-09-15)

**Comment by wtaferner** [comment]
@guewen :+1: I have already an Odoo implementation based on suds-jurko b/c of the exact same reason.

**Comment by antonylesuisse** [comment]
If the api is the same for debian/control keep suds because it's packaged. For pip install you may use the maintained version.

**Comment by guewen** [comment]
According to this post: https://lists.debian.org/debian-python/2014/07/msg00001.html the API is the same except the removal of 2 unused methods:

> According to the maintainer suds-jurko is almost fully API-compatible with
original suds, where almost means the removal of two apparently obviusly unused
methods (for the full message see below [1]). In case this should be a
substantial obstacle, the maintainer offers to re-include those methods.

**Comment by rim-odoo** [comment]
No objection on my side to use the maintained version :)

**Pull request merged**
