### PR TITLE
[FIX] stock_account: bill price change fix

### PR DESCRIPTION
**Pull request by AhmedAmirK**
Before this commit, if a user creates a bill from a PO and confirms it. A stock valuation is created. if the user sets the bill to drafts and changes the product price. a new layer corrects the difference. if the user does it again, the new layer ignores the previous correction layers, resulting in wrong valuation.

This commit removes previous correction layers created when the user does this action.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by amoyaux** [comment]
robodoo r+

**Comment by yostashiro** [comment]
Comparing the opening message of this PR https://github.com/odoo/odoo/pull/103068#issue-1404632070 and the commit message, it looks like the fix approach has been changed from

> This commit removes previous correction layers created when the user does this action.

to

> This commit hides the 'Reset to Draft' button when there are correction layers found.

@AhmedAmirK May I know what the reason was for this change?  I imagine that the original approach would have come with the complexity of considering the issued inventory, however the implemented approach looks to me a bit absurd - what should the user do to correct the vendor bill then?

**Comment by yostashiro** [comment]
> The original solution would have been too complicated and we figured the user could just recreate the vendor bill with the correct amount.

@AhmedAmirK Thanks for your reply but that's oversimplifying the issue I must say (stock accounting is totally left out here). I hope that the issue is looked into more seriously at Odoo behind the scene than it appears in your comment, since I believe it is a deal breaker to many businesses. We opened an OPW ticket (3224622) over this and asked for the design rationale but it looks like it's going to be closed with no useful information from the support staff.  I wish product managers at Odoo would openly discuss this kind of issue with the community instead of just silencing it down, as I haven't witnessed any communication where Odoo even acknowledges the isseue although some accounting-savvy members of the community have raised strong concerns about the new design.

**Comment by dipak-shah** [comment]
@AhmedAmirK you should do something here. you can't leave this as open issue. and major. what are the workaround here?

@yostashiro

**Pull request closed without merging**
