### PR TITLE
[FIX]  _get_current_rate to include complete date

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
#9414

**Comment by nicomacr** [comment]
The error is that having the same day several exchange rates , is not taking corretamente last. It happens that only looks at the date regardless of time .

**Comment by nicomacr** [comment]
@odony can you take a look at this one? Please, find out that I' ve update the description and steps to reproduce on runbot

**Comment by antonylesuisse** [comment]
New version of

https://github.com/odoo/odoo/pull/9247
https://github.com/odoo/odoo/pull/9414

With a more complete explanation this time.

**Comment by jjscarafia** [comment]
@odony any more needed for this PR?
Thanks!

**Pull request closed without merging**
