### PR TITLE
Required Text field should not be highlighted in non-edit form view

### PR DESCRIPTION
**Pull request by auyeung112002**
Fix: https://github.com/odoo/odoo/issues/17510

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

I let the web team decide for the content but regarding the CLA warning:
You signed it for 11.0 at #21281 but this PR is for 10.0.
Do you want me to backport your CLA in 10.0 too or is this PR for 11?

**Comment by auyeung112002** [comment]
Please backport the cla to version 10. Thanks

**Comment by mart-e** [comment]
Thanks, backported at bde7030c598386afa9f9dd78b4d139fe1a90e6a7. If you rebase your branch, the CLA check should succeed.

**Comment by Yenthe666** [comment]
@mart-e can we pick this up again? It is still relevant.

**Comment by mart-e** [comment]
Maybe, but as said above, I let the web team decide. I am not expert on the subject. Maybe @qsm-odoo is :)

**Comment by qsm-odoo** [comment]
That's in my todo list :wink:

**Comment by qsm-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/3a13eada0ee522b8ac919bbac424519dcf639ac1

**Pull request closed without merging**
