### PR TITLE
[FIX] website: don't translate exemple of rule

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
- Install website and set in French
- in the robot wizard you see:
Exemple de règle :
Refuser : /web/login
Autoriser : *

@nim-odoo

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rdeodoo — APPROVED** [review]
@mart-e LGTM, even tho I am not sure why the bug is not happening in 15.1.
Well, I know, this is because the translation was removed from the .po file, but I am not sure why since the source is still in the .pot file and that part of the XML template didn't change.

**Comment by fmdl** [comment]
@ping @mart-e

**Comment by fmdl** [comment]
ping @rdeodoo

**Review by rdeodoo — CHANGES_REQUESTED** [review]
Shouldn't you modify the `.pot` source term and all the `.po` translated terms too?
Otherwise, it's also breaking the translation for `Example of rule:`

**Comment by rdeodoo** [comment]
Don't hesitate to ping again sooner, it's sad to leave PRs die for almost a year

**Comment by fmdl** [comment]
@rdeodoo it is done and move in master.

**Comment by rdeodoo** [comment]
Great, but you can keep targeting the 14.0 please (same diff).

**Review by rdeodoo — APPROVED** [review]
@robodoo r+
It will break the translation (while translated again) for everyone, which we try to avoid as much as possible but in this case it is worth it / important to do it as otherwise the code snippet we hint to the client is translated. In case of copy paste of the sample we provide it will not work in the robots.txt.
I already saw french translated version of this in actual robots.txt in `opw`, I guess they copy pasted this.

**Pull request closed without merging**
