### PR TITLE
[FIX] i18n: missing Slovenian translation

### PR DESCRIPTION
**Pull request by jpp-odoo**
Slovenian language, as many others languages, is not present in the
beta/master projects in Transifex.

For some reason, Transiflex removed all current translations, this was
already fixed in 12, but as there are not automatic forward-port for
translations, this is a manual forward-port.

opw-2060055

### CODE REVIEW

**Comment by jpp-odoo** [comment]
robodoo retry

**Comment by nim-odoo** [comment]
robodoo delegate+

**Comment by KangOl** [comment]
@robodoo r+

**Comment by KangOl** [comment]
@robodoo retry

**Pull request closed without merging**
