### PR TITLE
[FIX] website: review modal scrolling behaviors

### PR DESCRIPTION
**Pull request by qsm-odoo**
Review commit https://github.com/odoo/odoo/commit/8f1dd6d6087ad8252d6e7b22d13aad2c4a3f19c6

### CODE REVIEW

**Comment by rdeodoo** [comment]
I still have multiple issues regarding cookies bar & modals (both in 14.0 and with your branch).
That's probably not related and something to fix on top of that in another PR.
Definitely something to check alongside @bso-odoo PR https://github.com/odoo/odoo/pull/83258/files

**Bug 1**
- Activate cookies and set popup layout
- Drag & drop snippet in cookies popup so it scrolls
- Add a popup snippet
- Drag & drop snippet to it so it scrolls
- Save
- The cookies bar is correctly scrollable :heavy_check_mark: 
- Once you click on "I agree", the popup which is beneath the cookies popup won't be scrollable :x:
- F5, the same popup is now scrollable :heavy_check_mark: 
It was the cookie close that led to that error

**Bug 2**
- Activate cookies and set popup layout
- Drag & drop snippet in cookies popup so it scrolls
- Save
- The cookies bar is correctly scrollable
- Open page properties dialog
- Scroll bar is gone :heavy_check_mark: 
- Close page properties dialog
- Scroll bar is not appearing back, the cookies popup can't be scroll :x:

Note that for both bugs, the same issue can be reproduced with 2 regular popup snippet, no need of the cookies bar.
Both bugs are probably the same bug?

Both issues here https://watch.screencastify.com/v/OcFGOjsg5DdiM8iD9oWF second one starts at 22 sec

**Comment by qsm-odoo** [comment]
@rdeodoo Indeed, the code is `updateScrollbar` is not good enough yet... it removes the modal-open class without considering other opened modals... not sure how to fix that without duplicating the code in dialog.js :grimacing: I'd suggest to r+ this critical bug fix and I'll investigate that other problem later.

**Comment by rdeodoo** [comment]
@robodoo r+
Yep, I agree. Modals/Cookies and scrollbars seems really annoying :o

**Comment by rdeodoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
