### PR TITLE
[CLA] Update my email

### PR DESCRIPTION
**Pull request by tanghulu0608**
Description of the issue/feature this PR addresses:
Update my email

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Actually, as you have already used this email to validate e1d4b48d8e6ccb7214a3ae5039a62171f5009345, could you add the new email on a second line instead?
If you no longer use the first one, you could just add a "(up to 2019-07-25)" or something
Thanks

**Comment by tanghulu0608** [comment]
hello,
I add the new email on a second line.

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo r+

**Comment by tanghulu0608** [comment]
thanks!

**Pull request closed without merging**
