### PR TITLE
Fix calendar sort

### PR DESCRIPTION
**Pull request by manhg**
Description of the issue/feature this PR addresses:
In `calendar` module
Fetch events include reoccurrence and normal one will result in error:
```
File "odoo/addons/calendar/models/calendar.py", line 1131, in get_recurrent_ids
    return [r['id'] for r in sorted(result_data, key=key)]
  File "odoo/odoo/tools/misc.py", line 1039, in __lt__
    def __lt__(self, other): return self.val > other.val
```

Current behavior before PR:
Compare id is by mixed str/int

Desired behavior after PR is merged:
Compare id will always coerced into str

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for you patch but it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by manhg** [comment]
@mart-e I signed

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `manhg@users.noreply.github.com`
- you are signing for the address `m...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by manhg** [comment]
Sorry I made correct one.
Thanks!

**Comment by xmo-odoo** [comment]
Thanks @manhg. I merged a modified version of your patch as just converting real ids to strings led to incorrect sorting (the list view would ignore "desc" criteria for ids, and would show ids 1, 10, 11, 2, 3 rather than 1, 2, 3, 4… 10, 11)

**Comment by manhg** [comment]
Thanks!

**Pull request closed without merging**
