### PR TITLE
[FIX] stock: correct date format in forecast report

### PR DESCRIPTION
**Pull request by sswapnesh**
Before this fix, Default date format `medium` was used in Forecast report,
Which doesn't respect Date/Time format from Language.

Now, we are not passing any dt_format which will use Date/Time format
from Language.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
@ryv-odoo Can you please check this ?

**Comment by ryv-odoo** [comment]
Hello @sswapnesh , 
LGTM. It is seems perfect, thank you.
@robodoo r+

**Comment by ryv-odoo** [comment]
@robodoo r-

**Comment by ryv-odoo** [comment]
Well the 'medium' was used to not show the hours/minutes/seconds

**Comment by ryv-odoo** [comment]
@fw-bot ignore
@robodoo r+
My bad, I was confused with master branch. I desactivated the forward-bot. because it was fixed in next version (https://github.com/odoo/odoo/commit/c6847d9110c571f41029d03d036c44d70a9abbaa).

**Pull request closed without merging**
