### PR TITLE
[IMP] l10n_ar: data of perceptions by jurisdiction

### PR DESCRIPTION
**Pull request by bruno-zanotti**
**Description of the issue/feature this PR addresses:**
We add all the data related to the Argentinean
perceptions for each jurisdiction.

For each jurisdiction (xx) we have a new:
 * Tax: Percepción IIBB xx Sufrida
 * Tax: Percepción IIBB Catamarca Aplicada
 * Tax group: Perc IIBB xx
 * Account: Saldo a favor IIBB xx
 * Account: Retención IIBB xx sufrida
 * Account: Percepción IIBB xx sufrida
 * Account: Retención IIBB xx aplicada
 * Account: Percepción IIBB xx aplicada
 * Account: IIBB xx

Also, we activate some perceptions to work with demo data

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vbe-odoo** [comment]
Hi @Bruno-Zanotti @jjscarafia good morning!
Thanks for the update, LGTM!
Ready for technical review @jco-odoo 
Bests.
cc' @ren-odoo

**Comment by jco-odoo** [comment]
I would prefer to only have this in later versions...  But could you just squash the commits @Bruno-Zanotti ?

**Comment by Bruno-Zanotti** [comment]
@jco-odoo I've done the squash, and tried to summarise all the changes in the commit comment, please tell me if it's okay or if you would change something.

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
