### PR TITLE
[14.0][fix] ambiguous error due to missing column prefix

### PR DESCRIPTION
**Pull request by dnplkndll**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by wlin-kencove — COMMENTED** [review]
Alias on the table names are there to help prevent situations where a new module adds a field that has the same name of another field. Certainly helpful on queries that require a table join.

**Review by FlorianGilbert — CHANGES_REQUESTED** [review]
Hello thank you for your contribution, could you please fix the runbot and sign the cla ? 
Thank you :)

**Comment by FlorianGilbert** [comment]
Hello, runbot is still red, can you fix it please ?

**Comment by dnplkndll** [comment]
> 
can you assist in this? seems unrelated? but if you point me in the right direction will look. 

[odoo.addons.base.maintenance.migrations.base.pre-models-ir_ui_view:300](https://github.com/odoo/odoo/blob/3f31b0ace29ffbf3c1004efe12c5015b80c13fff/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-ir_ui_view.py#L300) It looks like you forgot to call `util.remove_view(cr, 'account_edi_facturx.account_invoice_pdfa_3_facturx_metadata')`

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by FlorianGilbert** [comment]
Hello, your branch is still not up to date.
Please fetch the most recent source from the V14.0 and rebase on it. After that, you can force push on this branch.
Thank you

**Comment by dnplkndll** [comment]
@FlorianGilbert can we get this merged, rebased again.

**Comment by FlorianGilbert** [comment]
@robodoo r+

**Comment by FlorianGilbert** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
