### PR TITLE
Fix validation of buttons with @icon

### PR DESCRIPTION
**Pull request by xmo-odoo**
The conditionals were not correct leading to `button[@icon]` only being validated if the button isn't `@special` and doesn't have an `@type`, which... doesn't really make any sense as that's only possible for straight HTML buttons (submit), and then `@icon` doesn't make sense because that's not an HTML attribute.

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@robodoo rebase-ff

**Review by Xavier-Do — APPROVED** [review]

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo r-

at_install seems to have shot up in duration, which may not be nonsense but seems bad to do as-is.

**Comment by xmo-odoo** [comment]
@robodoo r+

False alarm, there's apparently a fair bit of variability and this branch might just be unlucky.

**Pull request closed without merging**
