### PR TITLE
[IMP] Add an optional dedicated watchdog timeout for CRON workers

### PR DESCRIPTION
**Pull request by cmorisse**
**Description of the issue/feature this PR addresses:**
In Prefork mode (odoo launched with --workers=x params), all workers are killed by PreforkServer.process_timeout() after --limit-time-real seconds.
Problem is the behaviour is the same for Web Server Client request (handled by WorkerHTTP)  and CRON Jobs (handled by WorkerCRON).
So if you want to implement a long process in a Job, you must increase limit-time-real param value to the max duration of the Job and thus this timeout value will be used for HTTP client requests too.

So you can't enforce that client requests must be processed under a few seconds while CRON Jobs will be able to handle long duration processing.

This decrease the ability of multicorn PreforkServer to properly manage / "heal" the workers based on their processing time.

**Current behavior before PR:**
All Workers (WorkerHTTP and WorkerCRON) are killed by PreforkServer.process_timeout() after "time-limit-real" seconds.

**Desired behavior after PR is merged:**
This PR adds a new parameter: --limit-time-real-cron
If not set, behaviour is strictly the same as before.
If set to 0, then WorkerCRON workers will never be timed out.
If set with a value > 0, the value will be used as the WorkerCRON watchdog timeout .

https://github.com/cmorisse/dedicated_worker_timeout_test contains an Odoo 9 addon to play with the parameters above and test Odoo behaviour with and without this pull request.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
But I'm not sure which branch I should push this PR.

### CODE REVIEW

**Comment by wtaferner** [comment]
Uhh, imho this one seems very valuable. Thank you @cmorisse for providing this PR.

@antonylesuisse @KangOl 
What do you think?

**Comment by antonylesuisse** [comment]
Yes cron timeout and http request timeout should be different. I think we will merge this one.

**Comment by spadae22** [comment]
Love this, since in v8 we have large crons that work at night, backport to v8?

**Comment by wtaferner** [comment]
I backported it already to v8 and it is running in production since Monday ;-)

**Comment by spadae22** [comment]
@wtaferner Nice, do you a patch for v8?

**Comment by wtaferner** [comment]
@spadae22 
Here we go, just pushed a current v8 branch with a cherry pick of the backport

**Comment by spadae22** [comment]
@wtaferner +1

**Comment by odony** [comment]
@cmorisse Thanks for the excellent patch!
I've merged it in master at e2234e0389053ae4eb87e5679a32a4176e0102f8 according to our [guidelines](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch), with a few small changes (coding style preferences + removed `pid=` prefix in logging for brevity and consistency with the other Worker-related messages).

And thanks to @wtaferner the patch is also available for 8.0 at #11528 if anyone needs it.

Nice work :+1:

**Comment by cmorisse** [comment]
@odony @wtaferner You're welcome !!

**Pull request closed without merging**
