### PR TITLE
[10.0] Add currency_id in tree view (invisible) to make the 'monetary' widget work

### PR DESCRIPTION
**Pull request by alexis-via**
With this PR, you will be the symbol of the currency on the amount field in the tree view... a must have !

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It shouldn't be invisible but with the multi-currency group associated.

**Comment by alexis-via** [comment]
No, we don't want it visible even when you belong to multi-currency group ; we just want the currency symbol next to the amount inside the monetary widget.

**Comment by mart-e** [comment]
Hello,

I agree, it makes sense to add the currency symbol on monetary fields, it is already the case on the form view.
Merged at https://github.com/odoo/odoo/commit/0df9a6cc2a39e86f4e12f6da9c38ef128a5a2497

**Comment by purnendu03** [comment]
the currency_id must be there in tree view for two reasons
1) to make the monetary widget work
2) And to have a proper decimal places in order lines.

Check below link for further details. It was discovered in odoo9 enterprise as well.

https://github.com/odoo/odoo/issues/13617

**Pull request merged**
