### PR TITLE
[REF] website: temporarily disable problematic test step

### PR DESCRIPTION
**Pull request by qsm-odoo**
runbot-57204

### CODE REVIEW

**Review by qsm-odoo — COMMENTED** [review]
@robodoo rebase-ff r+

**Comment by rdeodoo** [comment]
@robodoo retry

**Comment by rdeodoo** [comment]
Louche, same error, but that `runbot.build.error` is actually quite frequent so.. let's just retry, especially since there is no queue at this time on runbot.

@robodoo retry

**Review by qsm-odoo — COMMENTED** [review]
@robodoo rebase-ff r+

**Pull request closed without merging**
