### PR TITLE
[FIX] web,web_tour: execute the qunit test suite integrally

### PR DESCRIPTION
**Pull request by aab-odoo**
Python tests that run chrome headless wait for "test successful"
to be printed in the console to end the test with green status.
Tours and qunit suites logs that message when their work is done.

Commit [1] reworked the tour system and introduced some qunit
tests of the tour engine. However, running fake tours in qunit
tests  produced the "test successful" message, which caused the end
of the suite. As a consequence, only a small part of the WebSuite
test suite was really executed.

This PR makes the test suite executed integrally again, and fixes an
issue in tests introduced by [1] which was hidden due to the above
described problem.

[1] odoo/odoo@3a798039d6f200f8e28448ddb6a2d3c46654a203

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Comment by aab-odoo** [comment]
robodoo p=0

**Comment by d-fence** [comment]
robodoo retry

**Pull request closed without merging**
