### PR TITLE
13.0 fix forum post image bvr

### PR DESCRIPTION
**Pull request by bvr-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bvr-odoo** [comment]
@qsm-odoo here is the new PR in 13.0 for the remaining o_we_selected_image class in forum post

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
Two commits, need mention of the PR in both

**Comment by bvr-odoo** [comment]
> Two commits, need mention of the PR in both

@qsm-odoo yes sorry, done :+1:

**Review by qsm-odoo — APPROVED** [review]
@robodoo rebase-ff r+

**Pull request closed without merging**
