### PR TITLE
[FIX] mass_mailing: alert margin issue

### PR DESCRIPTION
**Pull request by xlu-odoo**
Before this commit, in a Email Marketing form sheet, there was a margin-left spacing on alerts and unnecessary old CSS rules.

This commit addresses and corrects that spacing issue.

task-3488229

<table>
<tr>
 <td>Before</td>
 <td> After</td>
<tr>
 <td>
 Capture d’écran 2023-08-29 à 09 05 01
</td>
 <td>Capture d’écran 2023-08-29 à 09 05 07
 </td>
</table>

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by stefanorigano** [comment]
Hello @xlu-odoo 👋 Just flying-by this... If the rules to be removed are "old", why we're targeting 16.4 rather than 16.3?

**Comment by xlu-odoo** [comment]
> Hello @xlu-odoo 👋 Just flying-by this... If the rules to be removed are "old", why we're targeting 16.4 rather than 16.3?

Semantics ^^ 16.3 is "fine", (alerts on 16.4 changed a little bit, those lines are thus not necessary anymore)

**Comment by xlu-odoo** [comment]
@odoo/rd-design can you check this old PR please?
(I just rebased it)

**Review by Brieuc-brd — APPROVED** [review]

**Comment by xlu-odoo** [comment]
Hello @tde-banana-odoo , can you tech review this pr and eventually merge it please? Thanks

**Comment by tde-banana-odoo** [comment]
@robodoo delegate=@xlu-odoo 

Don't have much time, seems to be only removing css, so LGTM, if all cases are tested fine for me

**Comment by xlu-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
