### PR TITLE
[IMP] Searchs by Custumer now returns all task related to it and it's customers

### PR DESCRIPTION
**Pull request by hugho-ad**
Description of the issue/feature this PR addresses:
Now searches by Customer returns all tasks related to it and it's customers

Current behavior before PR:
Searching by the customer only returns task registered with the current customer
Desired behavior after PR is merged:
Now searching by customer returns all tasks related to it and it contacts like accounting app when searching invoices by a partner.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the PR but this should target the master branch instead.
Could you please rebase and retarget or [allow us](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) to change the content of your PR so we can do it ourself?

**Comment by hugho-ad** [comment]
@mart-e Done

**Comment by mart-e** [comment]
Thanks, merged at https://github.com/odoo/odoo/commit/c46baf4c8de7fbff0a22303a1136070297da4975 ! For your information, it is easier for us if you allow us to push in your branch as we can let [the mergebot](https://github.com/odoo/odoo/wiki/Mergebot/) do the merge after making this kind of modifications (or code and commit message cleanup).
But it is not mandatory if you do not wish.

**Comment by hugho-ad** [comment]
I allowed editions but when refreshing the page, the changes seem didn't work

**Comment by mart-e** [comment]
Really? Stranged I got an authorization error when trying to push. I will double check my config in the next PR...

**Comment by blaggacao** [comment]
@hugho-ad @mart-e Does this also work for group-by? Or do we still need thisÑ https://github.com/odoo/odoo/pull/26506 ?

**Comment by hugho-ad** [comment]
No, this only allows search task by customers and customer's contacts

**Pull request merged**
