### PR TITLE
[FIX] fields: Weaknesses of onchange on x2many

### PR DESCRIPTION
**Pull request by lmignon**
The convert_to_onchange method on _RelationalMulti generates unlink
all command (5,) followed by update or link commands for items already
present into the list IOW unlink all and relink. This behvior has undesirable
side effect if the unlinked items are declared with delete 'cascade'.
This changes replace the unlink all "([5])" with a specific list of item to
links"([6,,[...])". This way we avoid deleting a record that we are
reappending later.

This PR supersedes and follows #15566

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this going to be followed? I think this is still happening on all versions.

**Comment by Yenthe666** [comment]
Gotcha. Labelled it framework for now, so it atleast has a good tag. We'll see for the response.

**Comment by lmignon** [comment]
@Yenthe666 This PR didn't have any conflicts when proposed... I don't plan to fix these  conflicts...

**Comment by pedrobaeza** [comment]
@lmignon well, it's a pity if you have solved this problem, to not fix it because of some conflicts, but OK, it's your call. Any way, it's better to know if there's going to be any feedback from Odoo before working on anything.

**Comment by lmignon** [comment]
@pedrobaeza The problem is that I've spent time to write the fix, make a first PR #15566, integrate the remarks  https://github.com/odoo/odoo/pull/15566#issuecomment-321278073 form @odony and create a new PR on master that hasn't been reviewed in a year. If Odoo is not interested by this fix, I can't afford to invest extra time in this PR.

**Comment by pedrobaeza** [comment]
Yeah, I understand, that's why I'm asking if this is going to be attend, but I have choked with this in https://github.com/OCA/commission/pull/151 and it's hard.

**Comment by Yenthe666** [comment]
@lmignon I understand your frustration and I had my fair share of these kind of things too.
If you do decide to fix the conflicts I'll do my very best for you to get this looked into and merged if it works fine. Sadly I can't promise you more.

**Comment by C3POdoo** [comment]
Dear @lmignon,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
