### PR TITLE
[IMP] core: remove non existing modules from test

### PR DESCRIPTION
**Pull request by niyasraphy**
document_ftp, website_instantclick, pad, pad_project, note_pad, pos_cache is not currently existing in the addons, removing the non existing modules from the BLACKLIST dictionary.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by niyasraphy** [comment]
hi @xmo-odoo ,
as suggested here: https://github.com/odoo/odoo/pull/107185 , created pr targeting the master.
thanks

**Review by Julien00859 — COMMENTED** [review]
So the six modules that are removed from the list have been removed from the code base in:

* e58f289aebff 2014 [REM] move document_ftp to openerp-extra
* 92975297fc50 2014 [IMP] remove instant click
* a082b6bf0ab9 2021 [REM] (note_)pad(_project): Drop etherpad integration
* d2afca280be0 2022 [IMP] pos_cache: remove module pos_cache

At the time this install/uninstall test script was developed, so in late 2019, `document_ftp` and `website_instantclick` were removed already. Question: why those removed modules were included in the blacklist? Following question: three years later, now in late 2022, is it ok to remove those modules from the list?

@Feyensv do you know by any chance?

**Comment by niyasraphy** [comment]
hi @bouvyd ,
if you have time, can you review this.
thanks

**Comment by Julien00859** [comment]
Hello @niyasraphy I had a chat with the runbot team, they agree we merge this PR :) They had a small suggestion though, to list the still-blacklisted modules one per line so that the next time we modify the list, the git blame looks better.

**Comment by niyasraphy** [comment]
thanks @Julien00859 , updated at the pr

**Comment by Julien00859** [comment]
Thank you :)
@robodoo r+

**Comment by Xavier-Do** [comment]
LGTM
Note that AFAIR this test is not run on runbot. We don't use the test_full and chose the module we uninstall during the nightly.
(test_uninstall)

@robodoo r+

**Pull request closed without merging**
