### PR TITLE
[FIX] account: render draft invoice without early payment

### PR DESCRIPTION
**Pull request by lase-odoo**
Description of the issue this PR addresses:
---

On obtains a 500: Internal Server Error when creating an invoice with a 2 lines payment term.
Error while rendering the template "account.report_invoice_document".

Steps to reproduce:
---

- Accounting > Configuration > invoicing > Payment Terms 
- New > Create and save a payment term with 2 lines:
  - name 80/20 test
  - line_1 : 80% after 0 days
  - line_2 : 20% after 30 days
- Sales > Orders > Quotations
- Chose any > use payment terms 80/20 test
- Save and create associated invoice > chose regular invoice
- Create draft invoice > preview > 500: Internal Server Error

Cause of the issue:
---

The method "_get_amount_due_after_discount" called during the rendering of the template does not return a value in case self.early_discount is False.

Fix:
---

Return total_amount by default since no discount is applied.

opw-3683708

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
seems good to me, the issue happen because we call method _get_amount_due_after_discount expecting a number here:

https://github.com/odoo/odoo/blob/a404fd7a2f90c334e10ed5fdc3aa4f88e44dba38/addons/account/views/report_invoice.xml#L233-L236

with no `early_discount` if there is no reference date:

https://github.com/odoo/odoo/blob/a404fd7a2f90c334e10ed5fdc3aa4f88e44dba38/addons/account/models/account_move.py#L1912-L1915

so we either needs to have a float if there is no early_discount, or to change the template or `_is_eligible_for_early_payment_discount`.

there should probably be a small test that render the invoice (eg. calling `_render_qweb_html` of the invoice) that failed before the fix

**Comment by lase-odoo** [comment]
Hello @nle-odoo,

Concerning the test I have written, I was told that doing a "_render_qweb_html" is somewhat a heavy operation and it is therefore probably best to not make a test for this use case.

**Comment by lase-odoo** [comment]
Hey @qdp-odoo Tell me when you'll have time to review this PR ;)

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
