### PR TITLE
CLA sign

### PR DESCRIPTION
**Pull request by ispiders**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by mart-e** [comment]
@ispiders why did you push in the branch? It interrupted the process so it was not merged.

**Comment by ispiders** [comment]
@mart-e Sorry, I don't know that. How do I make it work again?

**Comment by mart-e** [comment]
I have rebased and changed the commit message, should be good now.
@robodoo r+
@ispiders just wait, it will be merged and the PR closed in a few hours

**Pull request closed without merging**
