### PR TITLE
[MERGE] (crm_)iap(_*): move API to IAP modules, cleanup code

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
PURPOSE

Perform a global renaming / cleaning of IAP features often added or merged
with minimal review. Time to cleanup !

SPECIFICATIONS

LINKS

Task ID-2600047 (IAP(_*): move API to use services in IAP modules, cleanup code)

### CODE REVIEW

**Comment by JKE-be** [comment]
hello

what's the purpose of this split ? 

We are moving into the opposite sense... We are currently merging website_form in website ...

//cc @qsm-odoo

**Comment by qsm-odoo** [comment]
Aouch :worried: Yes, could you work on top of https://github.com/odoo/odoo/pull/69888 and wait for its merge please? :fearful: Our PR comes with a complex upgrade script but should be merged this week (cc @rdeodoo).

**Comment by tde-banana-odoo** [comment]
@JKE-be Did not know, well I suppose I can ditch my commits :D .

**Comment by rdeodoo** [comment]
> Aouch worried Yes, could you work on top of #69888 and wait for its merge please? fearful Our PR comes with a complex upgrade script but should be merged this week (cc @rdeodoo).

@tde-banana-odoo Hello, just to let you know that https://github.com/odoo/odoo/pull/69888 just got merged

**Comment by tde-banana-odoo** [comment]
Happy conflicts to me !

**Comment by C3POdoo** [comment]
Dear @tde-banana-odoo,

Thank you for your contribution but we are closing it due to inactivity.

We apology if we could not look at your request in time.
If the contribution still makes sense, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
