### PR TITLE
[MERGE] mail: improve jinja markers use

### PR DESCRIPTION
**Pull request by tde-banana-odoo**

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@mart-e Zizisse what we talked about. First commit adds tests for current behavior (+ some docstrings), second commit updates markers.

Interesting stuff: we do not use the block markers in standard odoo, meaning our templates are compliant. Improving them to use more block oriented jinja and less line-oriented could be done one step at a time.

Followup of https://github.com/odoo/odoo/issues/45611, cc @Yajo

**Comment by xmo-odoo** [comment]
So this... removes support for Mako-style templates and replaces it with regular Jinja (except not quite)?

1. Why leave non-qweb templates in at all.
2. If we're switching to jinja text templates, why not just remove all the `_string` and `_prefix` stuff? it's only there to make Jinja look like Mako. It seems like a terrible idea to end up with a half-jinja half-mako template language like some sort of catdog monstrosity.
3. This is going to break all the existing templates yes?

**Comment by tde-banana-odoo** [comment]
Hello,

It does not seem to break any standard template as no-one is currently using the block-based markers (except a python test). I did not install all addon, still waiting for runbot testing. Using block statement currently leads to easily broken templates when using editor. That is why we mainly always use line statements or sometimes variable statements. But lines statement are easily broken using the editor as it messes with whitespaces. We hope using blocks will lead to a bit less issues with editor, while keeping in mind it is still not easy to use.

Concerning your other remarks I don't fully understand them. Block and comment markers will be standard according to https://jinja.palletsprojects.com/en/2.10.x/api/. The customized one are variables and line statements. But as it is the one we use in all templates we could customize that one to keep our templates compatible. I don't see why you consider it as "half mako halk jinja"; my point is more trying to get rid of "</>" noise that are not tags. I don't care being jinja-crystal-clear.

Cheers,

**Comment by tde-banana-odoo** [comment]
cc @pedrobaeza First attempt to get rids of old tags-like markers. This changes allow to be backward compatible with all existing templates, and probably gradually use block markers more often in templates (first attempts in calendar templates who are quite easy to break). As you have quite a lot of experience with templates along with @Yajo would that help ? If you have a list of "easily broken templates" we could also have a look to try to make them a bit more robust: either with markers better supported by editor, either with better-written jinja statements.

We all hope that a nice QWeb editor lands someday for templates, but that's currently out of my hands.

Cheers,

**Comment by pedrobaeza** [comment]
Thanks for this! We will check and tell you back.

**Comment by Yenthe666** [comment]
> > It does not seem to break any standard template as no-one is currently using the block-based markers (except a python test).
> 
> Well no but how many people are using them in their own non-standard templates?

**Raises hand**, we sometimes do it as it seems to work better & less glitchy then the Odoo implementation. :)
However that being said, if it can be improved in a new version why not? You need to migrate and test code anyways.

**Comment by Yajo** [comment]
First of all: **thank you very much!** From the ❤️. This problem has been a big PITA over the years.

We currently have 3 problems with Odoo's Jinja:

1. Old block markers (`<% if condition %>`) are escaped in the WYSIWYG template body editor (into `&lt;% if condition %&gt;`).

   This PR fixes this problem because makes the switch to standard jinja markers, which won't be escaped by the WYSIWYG editor. 👍🏼 

2. Line statements are broken by the WYSIWYG editor, because in the moment you change a character, it collapses whitespaces (it's logical: this is HTML) and thus line statements break.

   This PR doesn't fix this problem because it still allows line statements. 👎🏼 

   > Improving them to use more block oriented jinja and less line-oriented could be done one step at a time.

   I wish you were right, but being realistic I think this won't happen as you say. Most chances is that you'll close the task, everybody'll forget about this, odoo 15 will get released, translations will be frozen and... 💣  another year with the same problem.

   We _need_ to flip the switch and _disable_ line statements. That means replacing a lot of templates? Yes. But I did it in the past with a couple of regexps, it wasn't that hard: https://github.com/odoo/odoo/pull/45633 🤷🏼‍♂️ 

3. Mako & Jinja syntax mixture. a.k.a `${ ... }` for variables instead of `{{ ... }}`.

   It would be nice to use full Jinja standards and switch to `{{ ... }}`, but honestly, `${ ... }` does not introduce any problems.

   My advice is that, if anyway Jinja is fading away, we could just leave this as it was to reduce friction. But really I don't have a strong opinion on this subject.

So, IMHO you need to at least fix point 2 if you *really* want to fix the problem.

**Comment by Yajo** [comment]
> 2. Line statements are broken by the WYSIWYG editor, because in the moment you change a character, it collapses whitespaces (it's logical: this is HTML) and thus line statements break.

Look how it still happens. This was recorded on this PR's runbot, while editing the sale order mail template (possibly the most edited one):


https://user-images.githubusercontent.com/973709/111277110-f9f37900-862f-11eb-92e3-dc3067c90f6e.mp4

See? The "Hello" part disappeared, instead of being replaced by "Hi". Also, "Your order" changed to "Your (Undefined,)".

**Comment by xmo-odoo** [comment]
TBF odds are rather high the WYSIWIG editor will always break many templates regardless, just differently: at best it treats template tags as text, meaning it will "fix" the markup around them in such a way that they're in valid areas for text e.g. you can't have text in table/tbody directly, so if you try to put a loop around a tr, I'm pretty sure the editor will always break it one way or another.

**Comment by Yajo** [comment]
Yes, but as it is right now it breaks always everything. At least we'll be much less worse if you remove line statements.

**Comment by tde-banana-odoo** [comment]
Hello,

Seems we are finally going to have a complete QWeb support for v15. Raw edition of QWeb should be available, meaning templates will be converted into QWeb and editable directly using the editor + tools to ease fields and conditions management.

This mean two things
  * converting jinja markers has no utility in master as normally they will be converted into QWeb before v15;
  * it will be way easier to edit templates without breaking the dom and code-based expressions;
 
I think this PR is therefore on hold, waiting for green or red flag from editor team.

Cheers,

**Comment by pedrobaeza** [comment]
I can't believe you!! Yoo-hoo! :tada:

**Comment by Yenthe666** [comment]
@tde-banana-odoo did it land in another PR in V15?

**Comment by tde-banana-odoo** [comment]
> @tde-banana-odoo did it land in another PR in V15?

Editor team is still working on QWeb for templates. I am unsure whether this will fit in the release or not, depending on it this one could be opened again. A bit windy currently in the R&D :)

Cheers,

**Comment by Yenthe666** [comment]
Sending good vibes your way! Good luck on the hectic weeks 😉

**Comment by tde-banana-odoo** [comment]
I will forward your good vibes to editor team, I think they need it :D .

**Comment by tde-banana-odoo** [comment]
I hereby link https://github.com/odoo/odoo/commit/0a180d04b0e02d8210a62a9c63e4091d96ee411d which landed in 14.5 (a bit late, but hey).

**Comment by Yenthe666** [comment]
You all get a 🏆

**Pull request closed without merging**
