### PR TITLE
[11.0][FIX] sale, sale_timesheet

### PR DESCRIPTION
**Pull request by mep-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mep-odoo** [comment]
@jem-odoo 
[FIX] sale_timesheet: when project found then link to project into s
I have fixed this point.plz, check it.

[FIX] sale: add force_save to make SO is correct
--> when SO confirm and add new line in tree view face warning https://youtu.be/w9EiJh5XXHY
    same issue when adding a new line of wizard work well  https://youtu.be/DebDPHszij0 
because @ged-odoo  fixed in a wizard.here is commit https://github.com/odoo/odoo/commit/a5ca63c83beafd9a060ac58d3b4c6a9a987b28df

**Comment by hmo-odoo** [comment]
Hello @jem-odoo ,

[FIX] sale: add force_save to make SO is correct
-------------------------------------
-> ged is fixed issue in inner form view of sale order line but issue still occur in inner tree (list) view of sale order line. so we should fix it.

[FIX] sale_timesheet: when project found then link to project into
-> actually issue is that **when analytical account is created, project is also created automatically**
see code:  https://github.com/odoo/odoo/blob/11.0/addons/project/models/project.py#L908 [*]

so we should restrict it with passing context False value : **project_creation_in_progress**
see code: https://github.com/odoo/odoo/blob/11.0/addons/project/models/project.py#L897

PS
* why project is created automatically when analytical account is created ? 
-> Before we use "Use Task" Boolean field in analytical account for automatically creation of project. but now this field is removed in this commit: https://github.com/odoo/odoo/commit/eb4ad335137de7831902e760e3fc375eeb81f326#diff-83441f41e1e80d372d7ce22c07e6900fL895

**Comment by hmo-odoo** [comment]
Hello @jem-odoo ,
can you review again ?
Thanks

**Comment by jejemaes** [comment]
Landed in 11.0 at 
https://github.com/odoo/odoo/commit/bf6894c5b133f9e50458b4c70a37db2a2edd3734
https://github.com/odoo/odoo/commit/3680e099a69cbefad7c5afb5b4e049f6f0b3fc39
Thanks

**Comment by jem-odoo** [comment]
Landed in 11.0 at 
https://github.com/odoo/odoo/commit/bf6894c5b133f9e50458b4c70a37db2a2edd3734
https://github.com/odoo/odoo/commit/3680e099a69cbefad7c5afb5b4e049f6f0b3fc39
Thanks

**Pull request closed without merging**
