### PR TITLE
[IMP] setup/install: improves readability, corrects spelling errors, …

### PR DESCRIPTION
**Pull request by tesserB**
Description of the issue/feature this PR addresses:
This pull request aims to improve upon the structure, readability*, and completeness of the installation guide.
-  It is overly explicit and assumes nothing about the users level of experience
-  The Demo and SaaS sections are more sales slanted
-  Removes references to limitations, where they are unhelpful
-  It's conversational and inviting: "we're helpful and friendly.. Call us and we wont talk over your head.."
-  It makes a point to avoid contractions and confusing idioms, where possible in order to aid translation/readability (i.e., you're to you are; je m'appelle to je me apelle).
-  Strips some industry jargon/acronyms

Is Your Business Writing Too Smart for Its Own Good?
http://www.printwand.com/blog/is-your-business-writing-too-smart-for-its-own-good

How to Write for an Eighth-Grade Reading Level
http://www.proedit.com/how-to-write-for-an-eighth-grade-reading-level/

Current behavior before PR:
Flesch-Kincaid Grade Level, SMOG, Coleman Liau Avg: 12th Grade

Desired behavior after PR is merged:
It's not ready to be merged. Just looking for guidance:

Flesch Kincaid Grade Level: 9th Grade
Flesch Kincaid Reading Ease: +11 points

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
Cody Kitterman

### CODE REVIEW

**Comment by tesserB** [comment]
@Yenthe666 As promised... I'll add some more this evening...

**Comment by Yenthe666** [comment]
@mart-e we should be looking at this, the amount of work done is amazing. :+1:

**Comment by mart-e** [comment]
Could you rebase? The diff is all messed up.

**Comment by tesserB** [comment]
@mart-e Not sure what happened there, sorry: sometimes... I... just... get carried away...
allworknoplay

@Yenthe666 
https://www.youtube.com/watch?v=jeOevu4zC5o
Marty reviewing my PR's...

**Comment by Yenthe666** [comment]
@KangOl I think some things went wrong here. There is nothing in the commit that relates to the docs from @tesserB and it isn't relevant either. A mistake perhaps?
@mart-e now that we're here again, perhaps we can pick this up again?

**Comment by mart-e** [comment]
Not really applying anymore since 8670f62e3c1d57371e34836b84a0f5079b2ad0e6
Sorry

**Pull request closed without merging**
