### PR TITLE
[IMP] survey: Fetch the last  'Date of Certification' in survey certification

### PR DESCRIPTION
**Pull request by RachidAlassir**
Description of the issue/feature this PR addresses:
In case survey retake is enabled the default "Date of certification" is the `create_date` of the first certification not the last.
This could happen in the "E learning" module, after a user (student) leaves the course and rejoin it so he/she can retake the certification.
Here is a screenshot:

image

Current behavior before PR:
If the user took the survey several times "Date of certification" isn't right.
Desired behavior after PR is merged:
"Date of certification" should be the "create date" of the last survey (not the first).

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by RachidAlassir** [comment]
@mart-e FYI

**Comment by awa-odoo** [comment]
@RachidAlassir @mart-e 

I'm not sure how this can happen in a real use case.
Yes, you can leave and re-join but we look for **succeeded attempts**.
Meaning that you have to succeed, then leave, then join, then succeed once again, which does not make much sense.

I guess the extra ordering doesn't hurt in anyway, but:
- Commit message needs to be improved
- This "issue" is already existing in saas-12.3, so target needs to be changed

**Comment by RachidAlassir** [comment]
@awa-odoo 
Yes, While printing the certification the system will fetch the first succeeded attempt (This could be a month or a year ego) not the last attempt (Which could be just a moment ago).

**Comment by awa-odoo** [comment]
@RachidAlassir Yes I very much understand that, what I don't understand is why you would need to succeed the exact same certification multiple times?
You will just get the same printed certificate (but with a different printed date if we use your "fix", which doesn't change much).

Seems like a very edge case to me.

**Comment by RachidAlassir** [comment]
@awa-odoo , Yes It's an edge case, but it's possible in the E learning module, Example: the student is allowed to retake the certification if he/she leaves the course and rejoin it later.

**Comment by awa-odoo** [comment]
> @awa-odoo , Yes It's an edge case, but it's possible in the E learning module, Example: the student is allowed to retake the certification if he/she leaves the course and rejoin it later.

This is only a problem if said student has already succeeded the module before, meaning he already has said certification.

**Comment by RachidAlassir** [comment]
@awa-odoo , Yes, But It's not extensible, for example: "me" as a developer I need to also check the score of the current certification which can change dramatically (e.g from 50% to 100%).
Probably it's not a "[FIX]", It's an [IMP] -> "improve" ?

**Comment by RachidAlassir** [comment]
@awa-odoo , There are major difference between odoo 13 and saas-12.3. 
Exemple odoo 13: the student can leave the course and rejoin it so then so they can retake the certificate.
In saas12.0: the student can't leave the course (from the portal) even if an admin remove them the back-end and they rejoin later they can't retake the certification (Only "Download certification" will appear).

**Comment by mart-e** [comment]
@RachidAlassir why do you want to target saas-12.3, it's just an internal version, not an officially one. This kind of corner cases is typically improvement for master (but only if @awa-odoo accepts it obviously).

**Comment by RachidAlassir** [comment]
> @RachidAlassir why do you want to target saas-12.3 ? It's just an internal version, not an officially supported one. This kind of corner cases is typically improvement for master (but only if @awa-odoo accepts it obviously).

@awa-odoo  
`This "issue" is already existing in saas-12.3, so target needs to be changed` 
The function `survey_get_certification` doesn't exist in master.

**Comment by RachidAlassir** [comment]
@awa-odoo  Also function `survey_get_certification` doesn't exist  branch 12.0,  Should i change it to 13.0 as an LTS version as described here https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch

**Comment by awa-odoo** [comment]
@RachidAlassir As suggested by @mart-e , this could be considered as an improvement for master but I don't think it can be described as a bug in the version 13.0.

> Also The function `survey_get_certification` doesn't exist in master.

I can see it here: https://github.com/odoo/odoo/blob/master/addons/survey/controllers/main.py#L595

So I suggest you submit a PR for master and we will consider the improvement there.

Thanks.

(And forget I said anything about saas-12.3, I got my branches confused).

**Comment by RachidAlassir** [comment]
> @RachidAlassir As suggested by @mart-e , this could be considered as an improvement for master but I don't think it can be described as a bug in the version 13.0.
> 
> > Also The function `survey_get_certification` doesn't exist in master.
> 
> I can see it here: https://github.com/odoo/odoo/blob/master/addons/survey/controllers/main.py#L595
> 
> So I suggest you submit a PR for master and we will consider the improvement there.
> 
> Thanks.
> 
> (And forget I said anything about saas-12.3, I got my branches confused).

@awa-odoo Done, thanks.

**Comment by RachidAlassir** [comment]
@awa-odoo  Any updates for this PR, can you give it the r+, please?

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for the proposal! I moved the order on model itself directly. It makes sense to display last one first when considering several attempts on a given survey.

@robodoo r+ rebase-ff

**Pull request closed without merging**
