### PR TITLE
[FIX] hr_timesheet: remove the `Awesome Timesheet` in res setting

### PR DESCRIPTION
**Pull request by kais-odoo**
This commit removes all links to the `Awesome Timesheet` app since 
this app has been recently removed.

### CODE REVIEW

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work. 🙂 

robodoo r+

**Review by xavierbol — COMMENTED** [review]
robodoo r-

Can you reword the commit message like this:
```txt
[FIX] hr_timesheet: remove the `Awesome Timesheet` in res setting

This commit removes all links to the `Awesome Timesheet` app since 
this app has been recently removed.
```

Thanks in advance! 🙂

**Comment by ppr-odoo** [comment]
> robodoo r-
> 
> Can you reword the commit message like this:
> 
> ```
> [FIX] hr_timesheet: remove the `Awesome Timesheet` in res setting
> 
> This commit removes all links to the `Awesome Timesheet` app since 
> this app has been recently removed.
> ```
> 
> Thanks in advance! slightly_smiling_face

Done

**Review by xavierbol — APPROVED** [review]
LGTM, thanks again for your work! 🙂 

robodoo r+

**Pull request closed without merging**
