### PR TITLE
[WIP][IMP] web: allow imperfect fit for usePosition

### PR DESCRIPTION
**Pull request by reth-odoo**
Before this PR usePosition only allows the pop-up item to be placed in 4 x 3 positions around its anchor element.
If none of these positions is deemed valid, the pop-up defaults to whichever position was selected at the start,
usually resulting the pop-up being cut off.

In many cases the pop-up might be able to fit the visible screen, but only at a position that is not currently considered valid. A common example would be a pop-up anchored to an element near an edge of the window with an element almost the width of the window.

The element fits the window but "top right of the pop-up under the anchor" puts it too much to the left. And "middle of the pop-up under the anchor" puts it too much to the right.

Video examples:
- Bad: https://watch.screencastify.com/v/7d4y9HvSrja8FLJvgA72
- A bit better: https://watch.screencastify.com/v/B8V5If6AkaMfMig0fEcu
- Ideally: The pop-up would keep hugging the screen to the left so that most of it is visible.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by thiryr** [comment]
@brboi hey there, for this I guess it's fine if we have both systems right? Just use the 'smooth' popper-js-like movement when necessary and keep the current behaviour for the 99% of the time where it isn't an issue?

The core idea is that we don't just send everything to nowhereland just because it doesn't quite fit perfectly. So I made it stick to the 'max' side of the screen (right or top) and stop when it reaches the 'min' of the screen. (We might want to invert that for different languages, not sure how easy it is to get the reading direction).

I didn't plan on adding something similar for to correct for 'direction', simply because there's almost no situation where the screen would both be too short and too slim for a pop-up to fit, and it wouldn't be usable either way. (We could add a scroll bar to every pop-up and resize them dynamically but.. seems a bit much).

No super-urgent as the issue for the task this emanated from is only with very slim phones but would be nice to have something for the next freeze nontheless if possible :)

**Comment by brboi** [comment]
@thiryr this looks like it is heading towards the right direction, but I need some time to analyze further.

For now we are working on the gantt view conversion, which has a higher priority for the next freeze.

Not sure if I will have enough time to dig this PR for the same saas version, but I will certainly for the next one.

Thanks again for your investigation here ;-)

**Comment by brboi** [comment]
Hello @thiryr 

I close this PR.

The usePosition hook has certainly room for improvement, but IMO this use case and the way you propose to solve it does not really convince me.

An alternative to solve the issue you raised is to implement a proper mobile friendly emoji panel.

**Comment by thiryr** [comment]
@brboi ok, thanks for having a look anyway.

So, for reference, do you dislike the idea of floating positionining? Or just the way it's implemented here because it jumps around?

**Comment by brboi** [comment]
I like the idea of preventing the overflow of a popper outside of its clipping container, if possible.

For now I just don't think this particular use case is worth investing time in this, that's it.

usePosition should be carefully improved, as it is used at many places and on many situations ;-)

We should have stronger reasons to add complexity in this piece of code.

**Pull request closed without merging**
