### PR TITLE
[FIX] l10n_cl: refine csv and add new currencies through xml

### PR DESCRIPTION
**Pull request by qsb-odoo**
Task: https://www.odoo.com/web#id=2212790&action=327&model=project.task&view_type=form&cids=2&menu_id=4720

### CODE REVIEW

**Comment by qsb-odoo** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@Danisan fyi

**Comment by Danisan** [comment]
Thanks! this change is now merged in our own.

**Pull request closed without merging**
