### PR TITLE
[IMP] web_editor: improve summernote editor

### PR DESCRIPTION
**Pull request by ans-odoo**
Task: https://www.odoo.com/web#id=1852817&action=327&model=project.task&view_type=form&menu_id=4720
Pad: https://pad.odoo.com/p/r.0cb27818c12b310b2a583ab7dcd1ea71
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lukebranch** [comment]
@ans-odoo ,

Is there any internal task for improving the support of nested <ul> and <ol> options in summernote in Odoo? The current options are not suitable for creating any kind of multi-level nested <ol> in particular.

Here's one example where Summernote (out of the box) doesn't provide proper support of nested lists:

https://github.com/summernote/summernote/issues/2647#issue-288528031

The key points here to improve the behaviour are allowing for the use of list-style-type, which has been achieved with a summernote plugin here:

https://github.com/tylerecouture/summernote-list-styles

From this list of summernote extensions:

https://github.com/summernote/awesome-summernote#contents

This is based on the w3c spec for list-style-type which can be found here:

https://www.w3schools.com/CSSref/pr_list-style-type.asp

and the support of proper nested lists with css counters, of which an example can be found here:
https://stackoverflow.com/questions/4098195/can-ordered-list-produce-result-that-looks-like-1-1-1-2-1-3-instead-of-just-1

based on this w3c spec:
https://www.w3.org/TR/CSS2/syndata.html#counter

This would be most useful when applied to ordered lists, and it would be far better if it worked as expected out of the box with Odoo's core summernote implementation.

If you'd like me to open a separate issue for this wishlist item please let me know, i'd just like to check first if you have an internal task open for this before doing so.

**Comment by lukebranch** [comment]
@Yenthe666 @pedrobaeza ,

Should I create a separate issue as a wishlist item for this request?

**Comment by Yenthe666** [comment]
Hmm I don't think that Odoo would like to add in an extra dependency though.

**Comment by lukebranch** [comment]
@Yenthe666 ,

What i'd suggest is just implementing a custom Odoo Summernote plugin into the core Odoo summernote implementation.

I understand that Odoo does not like to introduce new dependencies, however I believe this one is a key  usability issue. I've had a number of complaints from end-users that the core Odoo WYSIWYG editor (ie. summernote) doesn't work as expected (Tab + Shift issues, nested ordered list issues, etc.).

Is this something that must be handled upstream (ie. in Summernote itself), or could this be handled in Odoo's core Summernote implementation do you think?

**Comment by Yenthe666** [comment]
Sorry for the late response @lukebranch  I was on holiday. I'm not completely sure, I think @mart-e can answer this best.

**Comment by mart-e** [comment]
@lukebranch if you wish to make a feedback on summernote, please report it [upstream](https://github.com/summernote/summernote). We only ship the standard library and do not plan to implement new features ourself, sorry

**Comment by lukebranch** [comment]
@mart-e ,

Ok, thanks. I'll discuss with Summernote directly.

**Comment by lukebranch** [comment]
FWIW there is a PR waiting to be approved and merged in Summernote upstream for this nested ordered lists feature here:

https://github.com/summernote/summernote/pull/2986

**Comment by rdeodoo** [comment]
Cancelled, issues were fixed on another task

**Pull request closed without merging**
