### PR TITLE
[ADD] l10n_ke: Create localization for Kenya

### PR DESCRIPTION
**Pull request by gawa-odoo**
Added CoA and account groups for Kenya.
Added taxes for Kenya

task-2809108

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vin-odoo** [comment]
Don't forget to put the task id in the commit message (see the [guidelines](https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html#commit-message-structure))

**Comment by gawa-odoo** [comment]
Indeed, I forgot, thanks!

**Review by FlorianGilbert — CHANGES_REQUESTED** [review]
Hello

Please don't forget the task id in the commit message according to the [guidelines](https://www.odoo.com/documentation/master/developer/misc/other/guidelines.html#commit-message-structure).

**Review by FlorianGilbert — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
