### PR TITLE
Update Kanban Exercise code snippet

### PR DESCRIPTION
**Pull request by JoeyCodinja**
Field name was incorrecty spelt. Replaced ,'openacad.session.kanban' with 'openacademy.session.kanban'

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for you patch but it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by mart-e** [comment]
Hi,

Do you still wish to integrate this? Please don't forgot about the CLA if yes

**Comment by JoeyCodinja** [comment]
@mart-e Updated the CLA as requested

**Comment by mart-e** [comment]
Thanks for the update, looks good now

@robodoo r+ rebase-ff

**Comment by mart-e** [comment]
robodoo retry ?

**Pull request closed without merging**
