### PR TITLE
[REF] account: Add test for issue#30972 - Cash Basis Foreign Currency Reconcile error using low values like 0.01

### PR DESCRIPTION
**Pull request by moylop260**
I have reproduced the following issue https://github.com/odoo/odoo/issues/30972 with unittest

Cash Basis Foreign Currency Reconcile error using low values like `0.01`

OPW#1953027

### CODE REVIEW

**Comment by moylop260** [comment]
FYI I just apply the following change for the tests:

```diff
diff --git a/addons/account/tests/test_reconciliation.py b/addons/account/tests/test_reconciliation.py
index d19a1be6991..854c28272ee 100644
--- a/addons/account/tests/test_reconciliation.py
+++ b/addons/account/tests/test_reconciliation.py
@@ -1822,6 +1822,7 @@ class TestReconciliation(AccountingTestCase):
             'currency_id': self.currency_usd_id,
         })
         usd = self.env['res.currency'].browse(self.currency_usd_id)
+        usd.rounding = 0.0001
         usd.rate_ids.unlink()
         self.env['res.currency.rate'].create({
             'name': time.strftime('%Y-01-01'),
```

And the error is not reproduced anymore.

**Comment by moylop260** [comment]
@nim-odoo 
May I can ask you about this matter and let us know your opinion, please?

**Comment by kebeclibre** [comment]
@moylop260 
I'm sure this has nothing to do with reverting cash basis entries. There is no revert at all in your test

Also, your test does fail, and it is not surprising at all that changing the rounding on the currency solves the problem.
But, I tried to do it manually by (all with the same values for currencies and rates)
- issuing and validating an invoice
- creating the first bank statement and statement line
- reconciling partially the invoice, letting it open with a residual of 0.01 in invoice currency
- doing a second statement and line
- reconciling fully with the first two.

That way I'm not able to reproduce.

Maybe you have another practical use case ?

**Comment by moylop260** [comment]
> @kebeclibre
Also, your test does fail

Hi Lucas,
Yes, it test does fail because of this is the unittest to reproduce the issue where a fail is raised.

You can see the following video (from issue) where the same unittest is reproduced manually using runbot:
 - https://drive.google.com/file/d/1MCoRr_OfNSMM_b0A8rytSJuwAD5gkWTv

**Comment by moylop260** [comment]
Another way to reproduce it is adding a `self.env.cr.commit()` from the unittest method that makes the case.

**Comment by yaniaular** [comment]
@kebeclibre @nim-odoo Any new about this?

**Comment by kebeclibre** [comment]
@yaniaular
yep
#32023

**Pull request closed without merging**
