### PR TITLE
[8.0] : Fix stock warehouse column on purchase report , we need to join ...

### PR DESCRIPTION
**Pull request by AdilHoumadi**
...stock_picking_type and stock_warehouse tables in order to have the warehouse itself.

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Hello @ah-taktik ,

I believe this pull request is partially correct.

Indeed, `picking_type_id` of the model `purchase.order` is a `stock.picking.type` and not a `stock.warehouse`. Taking the `warehouse_id` from the `stock.picking.type` with a join on `stock_picking_type` is therefore indeed the thing to do.

Nevertheless, I believe the join on `stock_picking_type` is enough, the additional join on `stock_warehouse` is useless. You can totaly on do the following join:
`left join stock_picking_type spt on (spt.id=s.picking_type_id)'
and then replace
`s.picking_type_id as picking_type_id,` by `spt.warehouse_id as picking_type_id,`
and
`s.picking_type_id,` by `spt.warehouse_id,`

Dont you think ?

**Comment by ah-taktik** [comment]
Hello @beledouxdenis,

Thanks for you review, you totally right.
I removed the second left join.
I squash the two commits, you can check now.

Thanks.

**Comment by beledouxdenis** [comment]
As I rejected your other PR with your CLA, shouldn't you add your CLA signature to this PR, or create another PR with only your CLA signature ?

If you already signed the CLA, in another PR already merged, just tell me :).

**Comment by ah-taktik** [comment]
I will add it in this PR.

Thanks :)

**Comment by ah-taktik** [comment]
@beledouxdenis, It's done.

**Comment by lepistone** [comment]
Hi, I am a bit lost here. The fact that `picking_type_id` is a warehouse is intentional, or is it a mistake it's too late to revert? Thanks!

**Comment by beledouxdenis** [comment]
Hello @lepistone,

As you can see, the `picking_type_id` field is set as a many2one on `stock.warehouse`.

I have no idea of what was intended in this report, to actually display the warehouse or the stock picking type.

Anyway, changing either the name of the field from `picking_type_id` to `stock_warehouse` or either the relational field of the `many2one` from `stock.warehouse` to `stock.picking.type` is strictly forbidden in stable releases, as it will change the database structure, which is against our stable policy:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

The change of @ah-taktik was there the best thing to do, at least in stable 8.0.

Regards,

**Comment by lepistone** [comment]
@beledouxdenis I understand, thanks for the response. Still, since the mistake is indeed very surprising, and that caused the very bug that is fixed here, and my confusion, it probably deserves commentaries on the two affected lines.

Thanks!

**Comment by yvaucher** [comment]
+1 for a comment that won't hurt

**Comment by beledouxdenis** [comment]
There is git blame for that.

**Pull request closed without merging**
