### PR TITLE
[FIX] web_editor: space not working in firefox

### PR DESCRIPTION
**Pull request by deso-odoo**
Description of the issue this PR addresses:

Commit [1] changed removed trailing `<br>` in firefox when inserting text to address a issue in commit [2], where a table couldn't be removed if a `<br>` was its `lastLeaf`. However, it turns out that `<br>` element is necessary in Firefox to make text ending with a collapsed white-space visible. This commit reverts [1] and provides an alternative solution to the original problem.

[1]: https://github.com/odoo/odoo/commit/0cb260454e31473f4dcdfc48a80deecd0fcf05e5
[2]: https://github.com/odoo/odoo/commit/c41487c5ff365b3b34ed7fdcd12b3dba14154b9e

task-4045305
issue-[172562](https://github.com/odoo/odoo/issues/172562)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by deso-odoo** [comment]
@robodoo up to 15.0

**Comment by dmo-odoo** [comment]
@robodoo r+

**Comment by deso-odoo** [comment]
@robodoo retry

**Comment by sebgeelen** [comment]
@robodoo retry

**Pull request closed without merging**
