### PR TITLE
[IMP] fields: detect double definition of field

### PR DESCRIPTION
**Pull request by mart-e**
if one module does
```python
foo = fields.Char(string="Foo")
```
and another module inherit of the same model and does
```python
foo = fields.Char(string="Bar")
```
The field can not properly be translated as the source term will
change based on the installed module (and the information of which
module specify an attribute is not kept on the ir.model.fields)

### CODE REVIEW

**Comment by mart-e** [comment]
@rco-odoo not sure if a good addition to the ORM but will at least allow to detect bad practice (once the runbot is fixed)

**Comment by Yenthe666** [comment]
I'm happy with a warning for this but don't enforce that it is not allowed please :) Maybe a tiny bit better  description saying why is not a good idea is neat too.

**Comment by mart-e** [comment]
@Yenthe666 do you have any good reason to do so? Often it means you are changing the meaning of a field based on the module used, which is not a good idea

@dbo-odoo is this override mandatory? It is not properly translated if you only have sale.
https://github.com/odoo/odoo/blob/76723b98c1fe11380be8b10f833b74c021f2e5ab/addons/sale_stock/models/sale_order.py#L40-L43

**Comment by Yenthe666** [comment]
A good reason not very much but I've seen it in quite some third party apps in the past. Blocking this behaviour would be an extra annoyance in migrations I guess.

**Comment by dbo-odoo** [comment]
@mart-e 
well, since `sale_stock` changes how the expected date is computed and that this field does not have an entirely obvious behaviour, it is necessary imho.

The traduction is an issue. Perhaps a workaround (but an ugly one) would be to add a new field that would take the place of the old one instead (e.g a related on itself? would that work) - the new field's translation would then work...

**Comment by dbo-odoo** [comment]
but it is functionally needed indeed

**Comment by mart-e** [comment]
robodoo r+

**Pull request closed without merging**
