### PR TITLE
[IMP] web: fix typo in datepicker

### PR DESCRIPTION
**Pull request by Yenthe666**
Before this commit the sentence was a bit weird as a date is not on the future but in the future. This commit resolves this.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e small improvement :)

**Comment by mart-e** [comment]
@Yenthe666 if you modify the .pot file too, I can even accept it in saas-13.1 (as not deployed yet)

**Comment by Yenthe666** [comment]
Added the `.pot` change. I assumed a simple Github frontend base branch change would work but doesn't seem to be the case. Do you want me to make a new PR or how do you usually handle this?

**Comment by mart-e** [comment]
@Yenthe666 you have to modify the content of your branch `master-web-date-typo`
```
$ git reset odoo/saas-13.1 --hard
$ git cherry-pick 419ce9fa2b8e049856440a57f1cbda8c5a70313d
$ git push -f
```
where 419ce9fa2b8e049856440a57f1cbda8c5a70313d is the commit containing the diff (or use 7ed2f2c0e4fc57c1735e if the diff does not apply in the .pot)

**Comment by Yenthe666** [comment]
Okay TIL :) It does seem to screw up the runbot instantly

**Comment by mart-e** [comment]
@xmo-odoo @Xavier-Do seems like the migration bot does not consider retarget?

**Comment by xmo-odoo** [comment]
@mart-e I've no idea, you probably want to ping @d-fence more than me when it comes to runbot branch-matching.

**Comment by Xavier-Do** [comment]
I updated the branch manually in runbot (new feature incoming to do that automatically)

**Comment by Yenthe666** [comment]
@mart-e looks good now.

**Comment by mart-e** [comment]
robodoo r+
Hopefully won't conflict in saas-13.2 :crossed_fingers:

**Pull request closed without merging**
