### PR TITLE
[FIX] website_sale : check mandatory fields during confirm order

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
Go to runbot
- create a public user (complete all fields)
- add a first delivery address (complete all fields, phone, email, street, zip, country, ...)
- add a second delivery address (keep blank fields)
- connect with this partner, go to shop
- buy a product (not a service)
- in the cart press checkout
- you arrive in payment page
- now go back in the address step
- select the secondary delivery address
- then confirm order
--> Issue the order have no shipping address

Current behavior before PR:
If a partner have two delivery address, one full filled, an other with missing fields. During the shopping (the first delivery address is auto selected), if the partner go back in shop/address to select the second address. Then go to /shop/confirm_order, there are no checks.

@JKE-be 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
OPW #2513848

**Comment by fmdl** [comment]
@JKE-be Maybe put 
```python
        billing_fields_required = self._get_mandatory_fields_billing(order.partner_id.country_id.id)
        if not all(order.partner_id.read(billing_fields_required)[0].values()):
            return request.redirect('/shop/address?partner_id=%d' % order.partner_id.id)

        shipping_fields_required = self._get_mandatory_fields_shipping(order.partner_shipping_id.country_id.id)
        if not all(order.partner_shipping_id.read(shipping_fields_required)[0].values()):
            return request.redirect('/shop/address?partner_id=%d' % order.partner_shipping_id.id)
```
in `checkout_redirection`

**Comment by rdeodoo** [comment]
The same issue occurs when accessing /shop/payment so this will fix a second controller while a third is still allowing that issue. (and maybe extra_step too, but less critical)

Moving this code in `checkout_redirection()` seems indeed a better solution

**Comment by fmdl** [comment]
@rdeodoo moved

**Comment by fmdl** [comment]
@JKE-be fixed !

**Comment by JKE-be** [comment]
What do you thing about rename `checkout_check_partner` to `checkout_check_address`


And
```py
        redirection = self.checkout_redirection(order)
        if redirection:
            return redirection

        redirection = self.checkout_check_partner(order)
        if redirection:
            return redirection
```

=>
```py
        redirection = self.checkout_redirection(order) or self.checkout_check_partner(order)
        if redirection:
            return redirection
```

?

LGTM btw, with or without this last change

**Comment by JKE-be** [comment]
Thank you...
Just need to squash your 2 commits ;)

**Comment by JKE-be** [comment]
@fw-bot up to saas-14.3

**Comment by fmdl** [comment]
@JKE-be done

**Comment by JKE-be** [comment]
I still have an wrong commit 'f' :/

**Comment by fmdl** [comment]
@JKE-be et voila !

**Pull request closed without merging**
