### PR TITLE
[CLA] add Digital Domus

### PR DESCRIPTION
**Pull request by alessandro-fiorino**

### CODE REVIEW

**Comment by alessandro-fiorino** [comment]
@mart-e is it ok ?

**Comment by mart-e** [comment]
@alessandro-fiorino thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `56083608+alessandro-fiorino@users.noreply.github.com`
- you are signing _for_ the address `a...@digitaldomus.it`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Also, could you rename the file from `DigitalDomus.md` to `digitaldomus.md`?

Thanks

**Comment by alessandro-fiorino** [comment]
I've changed my configuration and file name is it ok now ?

**Comment by mart-e** [comment]
Hello,

Thank you for the update, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
