### PR TITLE
Saas 12.1 fix ged

### PR DESCRIPTION
**Pull request by ged-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mge-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
@d-fence

**Comment by d-fence** [comment]
runbot build is red so Rob odoo will not even try to stage it

**Comment by ged-odoo** [comment]
robodoo r+

oh, and also fuck you

**Comment by ged-odoo** [comment]
forgive me robodoo. I was angry, but I did not mean it. It was because of my poor impulse control. I just have a hard time accepting my failures.

**Comment by ged-odoo** [comment]
i know that @d-fence 
The issue is that there is no message telling me that it will not be merged.  I r+ed before the build was complete.  I think that the robodoo should work in 'fire and forget' mode.  If I have to wait for my build to complete if I want some meaningful message, then a lot of the advantage of the robodoo does away

**Pull request closed without merging**
