### PR TITLE
[IMP] delivery: add _auto_init for computed weight fields

### PR DESCRIPTION
**Pull request by dasa-odoo**
When installing the delivery module, the weight fields will be computed for every stock_picking and stock_move, which will be held in memory. For big databases, this leads to MemoryError.

Adding _auto_init for these fields permits us to compute them directly through psql, without filling up the memory.

This should solve https://www.odoo.com/web#id=2729173&cids=1&model=project.task&view_type=form and similar tickets.

### CODE REVIEW

**Comment by pimodoo** [comment]
Maybe we should rather ask to @amoyaux for this PR.

**Comment by amoyaux** [comment]
It's not possible to fix the compute performance instead of doing this hack?

**Comment by dasa-odoo** [comment]
The problem is that it has to keep 1.7 mil stock moves in cache to compute those. In the linked ticket, dafr mentions that he tried using search instead of filtered (to not fill up the cache) and that it didn't work. I don't know how otherwise to fix the compute, especially in stable. 

The thing is - we don't really need all of the cached information after the module's installation anyway.

I'll attach a speedscope, but the issue is almost certainly with the weight compute.
no_auto_init

**Comment by dasa-odoo** [comment]
I'm not sure why the svg doesn't load :-?

image

**Comment by amoyaux** [comment]
@dasa-odoo could you send me the dump in private

**Comment by C3POdoo** [comment]
Dear @dasa-odoo,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
