### PR TITLE
FIX: safe_eval’ing large strings gives illegal opcode.

### PR DESCRIPTION
**Pull request by jaredkipe**
Description of the issue/feature this PR addresses:
Using `safe_eval(x, y, mode='exec', nocopy=True)` where x is a relatively long string, will give 'illegal opcode'.

Desired behavior after PR is merged:
Be able to run large safe_evals after ( https://gist.github.com/jaredkipe/420f49bcfa49a5e1fa74f76f21696c83 )

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by xmo-odoo** [comment]
FWIW that doesn't seem related to "long strings", if you compile() the code and look at the disassembly it's rather the "long" `POP_JUMP_IF_FALSE` in Python 3.6 specifically.

I'm guessing that's due to the 3.6 wordcode change: in the 2.7~3.5 bytecode, POP_JUMP_IF_FALSE had a 16 bits argument and only needed EXTENDED_ARGS for jumps beyond the 65kth opcode, in 3.6 EXTENDED_ARGS becomes necessary for any jump with an offset of more than 256 which can happen very early (the test case compiles to 2084 bytes of code in Python 3.6 — though that compares favourably with 2527 in Python 2 — and jumps currently use byte offsets rather than opcode/word).

I'm fine with the change, but I'd like the comment fixed to denote that it's specifically for Python 3.6 and issues related to long *jumps*, the amount of code is not necessarily relevant.

**Comment by jaredkipe** [comment]
How can you have a long jump without a lot of code to jump to?

**Comment by xmo-odoo** [comment]
I am impressed by your ability to completely miss the point.

**Comment by jaredkipe** [comment]
Wow. I submitted the original pull request (with the original comment)  while in an airport on my way to Odoo Experience.  I certainly don't think the original comment is out of character with vagueness or specificness of other commits in Odoo.

I have updated the comment to be more specific and hopefully meet your approval.

**Pull request merged**
