### PR TITLE
[IMP] pos*: start tours in debug mode

### PR DESCRIPTION
**Pull request by vlst-odoo**
In this commit we remove the startOwl function from pos and replace it's
uses with the mountComponent from web. This has the advantage that we
repeat code less.

In addition, the `mountComponent` function also makes it such that the
prop declarations of the components are checked during tours.
This provides great benefits in terms of type checking.

In order to be able to make this change, all the prop declarations that
were wrong had to be corrected.

In addition, we also implement a generic mechanism for starting pos
tours. This allows for less code repetition.

Task 3756376
https://github.com/odoo/enterprise/pull/55609

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by h4818** [comment]
Not sure why I was pinged on this, but since the title caught my attention...
why would we run tours in debug mode? should we not be testing the USER experience which should not normally be in debug mode

**Comment by vlst-odoo** [comment]
> Not sure why I was pinged on this, but since the title caught my attention... why would we run tours in debug mode? should we not be testing the USER experience which should not normally be in debug mode

Hello @h4818 , You might be right. The intention was to have owl validate the prop definitions ( which, to my knowledge, it only does while in debug mode ). What do you think would be the best way to do this?

**Comment by h4818** [comment]
> Hello @h4818 , You might be right. The intention was to have owl validate the prop definitions ( which, to my knowledge, it only does while in debug mode ). What do you think would be the best way to do this?

🤔 I'm not quite sure... How about just adding one tour that uses the debug URL and does a few of the main flows using the most important POS components? it won't test all the props but it should prevent most stacktraces - it might even reuse the steps of an existing tour, keeping the diff minimal... just an idea 🤷‍♂️

**Comment by vlst-odoo** [comment]
> > Hello @h4818 , You might be right. The intention was to have owl validate the prop definitions ( which, to my knowledge, it only does while in debug mode ). What do you think would be the best way to do this?
> 
> 🤔 I'm not quite sure... How about just adding one tour that uses the debug URL and does a few of the main flows using the most important POS components? it won't test all the props but it should prevent most stacktraces - it might even reuse the steps of an existing tour, keeping the diff minimal... just an idea 🤷‍♂️

That would indeed work! But if the concern is about user experience, what's the difference between running in debug mode and normal mode? If the difference is not so great, having all tours in debug mode by default would be advantageous because if we only have the one, we would have to be very diligent about including new tour steps in it for the new features.

**Comment by h4818** [comment]
> That would indeed work! But if the concern is about user experience, what's the difference between running in debug mode and normal mode? If the difference is not so great, having all tours in debug mode by default would be advantageous because if we only have the one, we would have to be very diligent about including new tour steps in it for the new features.

In debug mode, the UI changes right? for example in POS, there used to be a debug menu...
either way, it's up to the POS team - so I leave it to you.

**Pull request closed without merging**
