### PR TITLE
[FIX] hr_attendance: fix attendance report

### PR DESCRIPTION
**Pull request by Williambraecky**
This commit contains two fixes.
The first fixes the absence of a multi company rule for the attendance
report model.
The second fixes the wrong widget being used in the pivot view of the
attendance report.

TaskId-2765671

### CODE REVIEW

**Comment by Williambraecky** [comment]
In master, apply commit e0a1c5023c615a1213b0a803997a7bb8a6c3a207 instead

**Comment by Williambraecky** [comment]
@fw-bot up to 15.2

**Comment by Williambraecky** [comment]
@fw-bot up to saas~15.2

**Comment by Williambraecky** [comment]
@fw-bot up to saas-15.2

**Comment by kba-odoo** [comment]
@robodoo r+

**Comment by kba-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
