### PR TITLE
Add new option in kanban gauge widget to inverse the coloration (full=red, empty=green)

### PR DESCRIPTION
**Pull request by Creamaster**
Current behavior before PR:
Impossibility to change the widget gauge color sheme 

Desired behavior after PR is merged:
Add an option to inverse the gauge coloration 

 ```python
widget="better_gauge"  options="{'inverse_color':true}"
```
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Creamaster** [comment]
New option demo :
demo widget gauge inverse color

**Comment by mart-e** [comment]
Hello,

Thanks for the proposal but I disagree with it.
- this is a new feature (bot a fix) so [should target the master branch](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch), not the stable version
- instead of adding the inverse, it would be better to make the colours configurable and specify the first and the last

Feel free to resubmit if you agree with these

**Comment by Creamaster** [comment]
> this is a new feature (not a fix) so should target the master branch, not the stable version

Regarding the targeted branch, I couldn’t agree more.


But I have some concerns with the proposed color configuration: 

> instead of adding the inverse, it would be better to make the colours configurable and specify the first and the last

currently the widget use the [HSL color model](https://www.w3schools.com/colors/colors_hsl.asp) and if the full/empty could be set, the intermediate colors cannot. This is the reason why I choose to limit the settings to a simple inversion.

Example of current limitation (by design):
- impossible to use blue and red without using pink in between
- impossible to use red and blue without a rainbow in between

To allow a total configuration of the displayed color, the widget should be redesigned, it's something I could do, but it feel unnecessary at the time.

Is the limitation to only choose the first and last colors, and not the others a requirement for this PR to be re-submitted ? 

PS: another design limitation is the widget structure, currently all the code is in a single function, such implementation forbids to alter the widget by inheritance

**Comment by mart-e** [comment]
@Gorash any suggestion? Some colours presets maybe?

**Pull request closed without merging**
