### PR TITLE
[REF] website: adapt code to new kanban view

### PR DESCRIPTION
**Pull request by jpp-odoo**
This commit makes some adaptation in the scss of the website visitors
kanban view with respect to the introduction of the owl kanban view.

### CODE REVIEW

**Review by rdeodoo — APPROVED** [review]
Thanks, visually as expected, maybe just missing some spaces between the buttons as before 
image

**Comment by jpp-odoo** [comment]
> 

Thanks for the review, I didn't see the missing space, I'm going to check it.

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by rdeodoo** [comment]
Thanks :)

**Pull request closed without merging**
