### PR TITLE
[FIX] sale_timesheet: fix typo

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Yenthe666 — APPROVED** [review]

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
You are on a roll today @Feyensv 😉

**Comment by Feyensv** [comment]
Yep, I wanted to clean a bit the backlog of `Sales` PR :).

**Comment by sswapnesh** [comment]
> Yep, I wanted to clean a bit the backlog of `Sales` PR :).

https://github.com/odoo/odoo/pulls?q=is%3Aopen+is%3Apr+label%3ASales+author%3Asswapnesh 😉

**Pull request closed without merging**
