### PR TITLE
[IMP] web: /json, a jsonified /odoo controller

### PR DESCRIPTION
**Pull request by Julien00859**
Change /odoo/ for /json/ in any backend URL to get the same information
as the current view you are sitting on, but as json. The controller
supports 3 extra query arguments: view_type, offset, and limit.

Task-3987268

### CODE REVIEW

**Review by kmagusiak — APPROVED** [review]

**Review by kmagusiak — APPROVED** [review]

**Comment by Julien00859** [comment]
@robodoo rebase-ff

**Comment by Julien00859** [comment]
Hello friends at @odoo/rd-security 

There are multiple `safe_eval` calls inside this PR. All of them are done to evaluate the domain and context stored in `ir.act_window` records. We should not be calling `safe_eval` with any user data. Likewise the two calls to `_get_eval_context` are done with those actions that can only be coming from the database, not user-defined data.

The call to `html.unescape` is done inside the unittest, the html is never evaluated, we merely verify that the error message is the right one. I believe this is genuine.

**Review by mart-e — CHANGES_REQUESTED** [review]
@robodoo override=ci/security
Reason: safe_eval on existing action to evaluate domains with user,…

To change before merging:
- ensure `action.run()` is not in sudo
- add a failing test that somebody with no access to the model can not run it (done in [`run`](https://github.com/odoo/odoo/blob/e0a088ce8f43f34cee58d12d941c0bd801ec8f89/odoo/addons/base/models/ir_actions.py#L975))

**Comment by jpp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
