### PR TITLE
[IMP] l10n_ar,l10n_es,l10n_se: remove unnecessary same inherited tax …

### PR DESCRIPTION
**Pull request by jco-odoo**
…groups

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@william-andre

**Review by william-andre — COMMENTED** [review]
You told me that "it doesn't work", but it does, right?

**Comment by jco-odoo** [comment]
@william-andre From the tests I did myself, it does work.

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
