### PR TITLE
[FIX] sale: fix two slashed prices bug in product page

### PR DESCRIPTION
**Pull request by jeep-odoo**
Steps to Reproduce:
- Configure a pricelist to lower the price of any product, and set the Discount
  Policy to `Show public price & discount to the customer`.
- Activate the `Comparison Price` setting in the website app.
- Set the `Compare to Price` of the product to an amount higher than the price
  in the webshop.
- Go to the product in the webshop: there are two struck-through prices.

Cause:
In the `_onChangeCombination` function, the `d-none` class was removed if
`has_discounted_price` was true. However, it should also check if
`compare_list_price` is set or not, which causes both struckthrough prices to
become visible.

Fix:
I added an extra condition to the if statement that will remove the `d-none`
class only if `has_discounted_price` is set and `compare_list_price` is not set.

opw-3864087

### CODE REVIEW

**Review by ltinel — CHANGES_REQUESTED** [review]
Thanks for the fix! :)

Actually, the `t-attf-class` did correctly add the `d-none` class, but it was incorrectly removed in the JS (see [1]). This was fixed in version 16.1 by adding an extra check before removing the `d-none` class [2]. Maybe we should apply the same fix to avoid having to forward-port? WDYT?

[1] https://github.com/odoo/odoo/blob/01ac404e0dd4bc343dde3c80ccbf0f33c2007f3f/addons/sale/static/src/js/variant_mixin.js#L559
[2] https://github.com/odoo/odoo/blob/f6c1609f17eae8c55e2985c0396828d94798a111/addons/sale/static/src/js/variant_mixin.js#L551

**Comment by jeep-odoo** [comment]
Hey @ltinel 

Thanks for pointing this out. I misunderstood and thought the `d-none` class was never applied, so I resorted to using `t-if`. You're right; applying the same fix as in version 16.1 makes sense. I'll make the necessary changes and push them shortly.

**Review by ltinel — APPROVED** [review]
LGTM :)

**Review by Feyensv — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
