### PR TITLE
[REF] website, *: remove 'website.context' module

### PR DESCRIPTION
**Pull request by qsm-odoo**
* website_forum, website_gengo, website_mail_channel, website_sale

Retrieving the global context is now the root's job, this will prevent
problems when trying to extend the values the context has.

See upcoming improvements with https://github.com/odoo/odoo/pull/29442

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@robodoo p=0 master is red without this

**Comment by qsm-odoo** [comment]
@robodoo retry rebase-ff

**Comment by qsm-odoo** [comment]
@robodoo p=0 ? :)

**Comment by qsm-odoo** [comment]
@robodoo retry who knows ?
@KangOl hr_contract_salary fails in enterprise, so I cannot merge this. In local I have different errors with this app... I guess we will see tomorrow (cc @rdeodoo)

**Comment by seb-odoo** [comment]
@qsm-odoo just by a quick look I'm pretty sure `o_sign_mode` has been renamed in my PR so that commit (I guess made in 12?) fails https://github.com/odoo/enterprise/commit/5db14872113e418109141234cc268f6e2b39f2f8#diff-67dbf23d56f1e061d52c09a6b80f376b

**Comment by seb-odoo** [comment]
-> `.o_portal_sign_auto_button:contains("Auto")`

**Comment by seb-odoo** [comment]
Also the `run` he's using on that commit is not necessary anymore since my commit d68b373de66f7e279160f1f867e2115063f91489

**Comment by qsm-odoo** [comment]
@robodoo retry p=0

**Comment by KangOl** [comment]
Please stop.
The original purpose of this PR is not related to the current failure of runbot.
A cleaner patch to skip the culprit tests is in the run: http://runbot.odoo.com/runbot/build/442091

**Comment by qsm-odoo** [comment]
@robodoo r-

**Comment by rdeodoo** [comment]
@KangOl Without this PR runbot is not going to be green anytime soon.
The `ace.js` file that require `web_editor.context` will still make the tours that use the frontend navbar to crash, like test_01_admin_shop_sale_coupon_tour and test_01_admin_shop_customize_tour.

**Comment by KangOl** [comment]
I just push 99499589eafb9c05236eb47553c1d723573c1b70 that change the import.

**Comment by KangOl** [comment]
Now that master is green, you can rebase (and ignore rde patch)

**Comment by qsm-odoo** [comment]
@robodoo retry p=2 and let me forget about this :expressionless:

**Comment by xmo-odoo** [comment]
robodoo p=1

**Pull request closed without merging**
