### PR TITLE
8.0 membership paid end nle

### PR DESCRIPTION
**Pull request by nle-odoo**
the first commit is doing what sve wanted for now, setting the membership_state to `free` when `free_member` is set and the `paid membership` is expired. but it has to be triggered by the `store=[...]` compound. 

**Edit :** first commit pushed in 8.0 with https://github.com/odoo/odoo/commit/c3464e958e05ba3c1ab821961a4310848e4c1f6c

then the second one is for what should be done so paid membership lose their status when it is expired. I have looked but didn't saw another way it was done currently.

I tested the cron by setting first all `res.partner` `membership_state` to `paid` : 

```
 membership_state | free_member | membership_stop | id  
------------------+-------------+-----------------+----
 paid             |             |                 |  1
 paid             |             |                 |  3
 paid             |             |                 |  4
 paid             |             |                 |  5
 paid             |             | 2015-12-31      |  6
 paid             |             |                 |  7
 paid             |             |                 |  8
 paid             |             |                 |  9
 paid             |             | 2015-12-31      | 10
 paid             |             | 2015-12-31      | 11
 paid             | t           |                 | 12
 paid             |             | 2015-12-31      | 13
```

then I triggered the cron and data became : 

 membership_state | free_member | membership_stop | id  
------------------+-------------+-----------------+----
 none             |             |                 |  1
 none             |             |                 |  3
 paid             |             |                 |  4
 none             |             |                 |  5
 invoiced         |             | 2015-12-31      |  6
 waiting          |             |                 |  7
 waiting          |             |                 |  8
 waiting          |             |                 |  9
 invoiced         |             | 2015-12-31      | 10
 paid             |             | 2015-12-31      | 11
 free             | t           |                 | 12
 waiting          |             | 2015-12-31      | 13

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Ok for the first commit 3e0b161bcc77b4bae14fb88044bee83c3b9888b4.

The second commit however is probably wrong: `membership_state` is a stored function fields, with triggers defined to know when to recompute the field value:
https://github.com/odoo/odoo/blob/8.0/addons/membership/membership.py#L327-L330

If the partner lose his paid status and the `membership_state` is not reflected correctly, it's then a trigger which is missing in this store dict.

**Comment by nle-odoo** [comment]
if I understand correctly:

#### `membership_state` of `res.partner` is recomputed :

* for partner and their `associate_member` when an associated `account.invoice` state (`open`, `paid`, `draft`) changes.

* for partner and their `associate_member` when an associated `membership.membership_line` state (none, canceled, old, waiting, invoiced, free, paid) changes.

* for their `associate_member` when a `res.partner` has a change for fields `free_member`, `membership_state`,  `associate_member`.

#### `state` of `membership.membership_line` is recomputed :

* for membership_line in the invoice line of an `account.invoice` whose `state` changes.

* for membership_line of `res.partner` whose `membership_state` has changed.


so when a membership should be expired (because the date of the day has changed), it is to my knowledge not repercuted. so I only see how it could be done with a cron, or a field which would be updated everyday (but to do this we would still need a cron then).

**Comment by beledouxdenis** [comment]
Well, indeed, I did not thought about the change of day case. In such case, you are right, there is no trigger.

Would be maybe good some day to be able to define a trigger on the day, that like you access a record for which the function stored field hasn't been recomputed for a while, it recomputes the field at read.

Nevertheless, this is of course not for Odoo 8.0 :). Nevertheless, adding a new cron is something that should be avoided the most possible. I would like @antonylesuisse's approval before commiting this.

**Comment by beledouxdenis** [comment]
@antonylesuisse we are still waiting for some feedback here :).

**Comment by beledouxdenis** [comment]
@antonylesuisse we are still waiting for some feedback here :).

**Comment by beledouxdenis** [comment]
Antony agreed that there is no other choice, and this isn't that bad since this is not a module which is massively installed, and most databases will therefore not have this cron task.

Let's go for it then :).

**Comment by nle-odoo** [comment]
ok :]


I've pushed the second commit  (and I had pushed the [first one](https://github.com/odoo-dev/odoo/commit/c3464e958e05) some times ago)

**Pull request closed without merging**
