### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by OmeGak**
Just fixing a few irresponsible typos.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

As you are not fixing a bug but making improvements in the code, could you please submit for master instead?
Hello,
Also, it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by OmeGak** [comment]
It should be fine now @mart-e.

**Comment by mart-e** [comment]
Thanks !
@robodoo rebase-ff review+

**Comment by mreficent** [comment]
@mart-e this contradicts with https://github.com/odoo/odoo/pull/36984#issuecomment-532679432 and https://github.com/odoo/odoo/pull/37086#discussion_r330448028 😒

**Comment by Yenthe666** [comment]
I honestly don't see why this one has been accepted either. Multiple PR's like this have been denied in the past and now all of a sudden a random PR is accepted. Not amusing.

**Comment by mart-e** [comment]
@OmeGak thank you for your contribution, we do not usually merge this kind of PR so you can see this one as an exception. Please make sure to check our [contribution guidelines](https://github.com/odoo/odoo/wiki/Contributing) to understand how we work for your future contributions.

@mreficent @Yenthe666 how about be nice with the new contributors with easy PR? You are experienced contributors, we can expect better PRs from you but I see this as an entry point to contribute to Odoo. We do try to avoid changes like mass code-cleaning PRs but the rules are also meant to be bent from time to time.

**Pull request closed without merging**
