### PR TITLE
[IMP] Make anglo saxon accounting true for nl

### PR DESCRIPTION
**Pull request by ploegvde**
Description of the issue/feature this PR addresses: Improvement of the Dutch localization. In the Netherlands, we use Anglo Saxon accounting!

Current behavior before PR: Setting Anglo-Saxon accounting is default False

Desired behavior after PR is merged: Setting Anglo-Saxon accounting is default True

Also saves Odoo SA a lot of issues on implementing Dutch companies :) It is now by default correct.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi Erwin,

I let @oco-odoo review the content but regarding the CLA check:
The CLA failed because the commit is made with a `@bizzappdev.com` email address (odd, was it cherry picked?).
You have to use your `e...@odooexperts.nl` email address for it to succeed.

**Comment by chklop** [comment]
Hello @ploegvde, to my knowledge anglo-saxon accounting is not a requirement in Netherlands. Though it can be used, we would rather have a situation where the user is not forced to use that type of accounting by default when installing the Dutch localisation.

If you have any source that would confirm that using that anglo-saxon accounting in the Netherlands should be done by default, please provide it to us and I'll gladly change my mind.

**Comment by ploegvde** [comment]
@chklop Hi, in the Netherlands it is not explicit required, but the way Odoo works in Anglo Saxon is the required way of doing accounting. The Dutch Tax Authorities (Belastingdienst) say we have to use 'Goed koopmansgebruik' [1].

'Goed koopmansgebruik' means several things, see [2]. Importnat in that is the 'Het realiteitsbeginsel'. and the 'Overeenstemmingsprincipe'. In this is stated that "the matching principle instructs that an expense should be reported in the same period in which the corresponding revenue is earned'. So, that means that the cost of recvenue should be taken when products are sold, and that is exactly what Odoo does in with the Anglo Saxon setting on true.

If we set anglo saxon to false the expenses of stock are taken when goods arrived in the warehouse and that is not allowed. It goes against the principle.

FYI: We have done 100+ implementations in the Netherlands and, non excluded, use anglo saxon = true. We even have fixed multiple databases that were implemented by Odoo direct that have the option to false and were messing up the revenue. 

[1] https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/inkomstenbelasting/inkomstenbelasting_voor_ondernemers/goed_koopmansgebruik#:~:text=Goed%20koopmansgebruik%20betekent%20zoiets%20als,past%20bij%20het%20type%20onderneming.

[2] https://nl.wikipedia.org/wiki/Goed_koopmansgebruik
https://en.wikipedia.org/wiki/Matching_principle

[3] https://nl.wikipedia.org/wiki/Overeenstemmingsprincipe

**Comment by chklop** [comment]
@oco-odoo After investigation on the subject, I think @ploegvde is right. While Netherlands does not "per se" implement Anglo-saxon accounting, the requirements from the Tax Authorities in Netherlands impose that Costs of Goods Sold need to be registered when the products are sold (in the same period). Using the anglo-saxon accounting module in Odoo allows them to do that by default.

**Comment by oco-odoo** [comment]
16.0 is now frozen, so I made a new PR in order to target it :) https://github.com/odoo/odoo/pull/102058

**Pull request closed without merging**
