### PR TITLE
[FIX] mail:tests: restore unintentionally remove test

### PR DESCRIPTION
**Pull request by alexkuhn**
Revision on https://github.com/odoo/odoo/commit/ff7ea6b654175e3138f5f36d2e5b4214cebef499

Due to some git conflicts, it duplicated history tests and removed
the previous test 'input not cleared on unresolved message_post rpc'.

### CODE REVIEW

**Comment by Xavier-Do** [comment]
robodoo r+

**Comment by Xavier-Do** [comment]
robodoo r-
Actually i think that you removed the wrong duplicates, you changed var to let and const if I remember well those are the one you are removing.

**Comment by Xavier-Do** [comment]
@robodoo delagate

**Comment by Xavier-Do** [comment]
@robodoo delegate

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by Xavier-Do** [comment]
robodoo r+

**Pull request closed without merging**
