### PR TITLE
l10n_ro: improved Romanian localization

### PR DESCRIPTION
**Pull request by rgo-odoo**
basically adaptation of https://github.com/odoo/odoo/pull/39577 having cleaner diff
Task: https://www.odoo.com/web#id=48668&model=project.task&view_type=form&menu_id=

### CODE REVIEW

**Comment by feketemihai** [comment]
@rgo-odoo Can we merge this in 13.0? Would be good even if it's not as complete as the master. Thanks

**Comment by rgo-odoo** [comment]
@feketemihai yes, few improvements can be merged in V13 as well. I am going to update this PR with such changes and will get back to you.
Thanks.

**Comment by lathama** [comment]
@rgo-odoo knowing that 13 is no longer updated, is this PR still needed?

**Comment by C3POdoo** [comment]
Dear @rgo-odoo,

Thank you for your contribution but the version 13.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
