### PR TITLE
[MERGE] *: create records in batch

### PR DESCRIPTION
**Pull request by Feyensv**
Ensure main Odoo models supports batch record creation.

* `purchase.order.line` supports multi creation in `purchase`, but not anymore when `purchase_stock` is installed.
* `sale.order.line` supports multi creation in `sale`, but not anymore when `sale_purchase` is installed.
* `crm.lead` doesn't support batch creation atm, but it doesn't cost anything to support it.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
@mart-e For sale & purchase order lines, could it be backported in stable :grey_question:

**Comment by Feyensv** [comment]
For the leads, I'll only merge it in master, no need for stable versions.
I was just asking for purchase/sales because those models are frequently created in batch (it is supported in the base modules but not in those bridge modules, thus disabling the batch creation).

**Comment by mart-e** [comment]
I see, I don't have strong feeling for neither so up to you :)

**Comment by Feyensv** [comment]
@robodoo r+ rebase-merge

**Pull request closed without merging**
