### PR TITLE
[ADD][12.0] l10n_fi_company_information / Finnish localization

### PR DESCRIPTION
**Pull request by elmeriniemela**
Description of the issue/feature this PR addresses:

Adds fields for Company Registry, eInvoice, and eInvoice Operator
Standard for Finnish companies.
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by thecodebasesite** [comment]
Related CLA is in separate pull-request:
https://github.com/odoo/odoo/pull/31728

**Comment by jco-odoo** [comment]
I think there is already a company registry field and I don't know what the einvoice_addresses purpose can be.

**Comment by rnurmi** [comment]
> I think there is already a company registry field and I don't know what the einvoice_addresses purpose can be.

There is company_registry field on res.company, but not on res.partner. This is however information we need to collect from invoiced customers and invoicing suppliers (which are companies of course), so this information should be on res.partner. Just like e.g. vat number, which is already there. Company registry is also needed i e-invoicing process, which is the next part.

Einvoice address is related to electronic invoicing. Finlands is the worlds leading country in electronic invoicing. Over 90% of all invoices between companies are sent in electronic format, instead of paper or email. Also significant amount of consumer invoices are send as e-invoice. E-invoice address is as much part of company information as street address or email. You cannot use an erp or financial system in finland without it, and as this is quite specific to Finland, it is one of the first localizations anyone will check if this system is localized or not.

**Comment by jco-odoo** [comment]
@rnurmi It is a bit weird to create a module with the fields without the functionality.  

Exporting/importing the invoice in the latest European PEPPOL format (CIUS), we can, but I wonder which are the ways to send the invoice to the government?  Peppol network or others?

**Comment by rnurmi** [comment]
In Finland companies and Government use almost exclusively Finnish Finvoice standard. Some Finvoice operators support PEPPOL some how, but usually so the PEPPOL invoices are simply converted to Finvoice, which is the nationally accepted standard.

The reason why we have put these to separate module is that this way it is easier to build additional finvoice modules for different purposes, when the basic fields used everywhere are named in the same way. For example, most companies publish this information on their websites, in contact information, whereas it is useful to have these available even without any Finvoice processor (in case when Finvoices are actually processed in some other system). 

I sort of agree that it would be cleaner if these fields would be introduced in the modules that actually use them, but then we would need to add these to 10 different places, instead of having them in single localization module. If this cannot be part of Odoo std localization, we will still have it our own module for convenience, but then again, our idea of localization is to try to make Odoo as good as possible for all Finnish customers, not just our customers.

If it is cleaner, these fields could as well be introduced with the standard COA, for which we have another pull request. Then we would need only one module instead of two. The only need here is to standardize the field names for commonly used information instead of having these duplicated in each addon module that needs this information.

About company_registry, I would be very glad if this kind of company basic information would be readily made available in res.partner model, which is the proper place for it, just like vat code. However, as it is stored only in res.company in std, we have had to move it to proper model ourselves, for Finnish purposes.

**Comment by jco-odoo** [comment]
It could e.g. go in the base l10n_fi module if the field is e.g. also on the PDF of the invoice.  (or is not it required there?)

Whatever format, how do you send the invoice to the government?  Mail/web service/ftp/...?

**Comment by rnurmi** [comment]
> It could e.g. go in the base l10n_fi module if the field is e.g. also on the PDF of the invoice. (or is not it required there?)

Normally we won't print the PDF at all, but we create Finvoice material, which as the address in it. Semantically same as printing PDF, end result is Finvoice XML.
 
> Whatever format, how do you send the invoice to the government? Mail/web service/ftp/...?

Using Finvoice operator. Physical transfer mechanism is operator dependent, usually operator API (e.g. web services API), or some times even just (S)FTP. We do not send invoices directly anywhere, government or other entities, but we need the einvoice address (string) and recipients operator (string) to be able to create the invoice and send it to a operator.

**Comment by mlaitinen** [comment]
This same discussion was held in #12931.

FYI, these modules are already available in Odoo Apps and here: https://github.com/OCA/l10n-finland/tree/12.0 (`l10n_fi_business_code` for the `company_registry` field and `l10n_fi_edicode` for the `einvoice_*` fields).

**Comment by jco-odoo** [comment]
@mlaitinen Does it make sense to at least export in FInvoice format, so you can upload it or send it e.g. in the pdf? Or to be able to import it somehow?  Or do you need to pass through the api of the 3rd party and there is no way to directly link to the government?

**Comment by mlaitinen** [comment]
It kind of would make sense, but then again, I don't think anyone would export a Finvoice XML file from Odoo and send it to an operator manually, let alone importing a Finvoice file manually.

The only way it makes sense is that it's built-in in Odoo and custom integration modules use it to generate the XML. It would also have to be quite extensible, because some software vendors use their own "flavor" of the standard.

We probably have as many Finvoice modules in Finland than Odoo companies. I'm aware of 4 different implementations. None of them are publicly available at the moment.

**Comment by rnurmi** [comment]
I agree with @mlaitinen . There are several implementations. Maybe some day we could have single reference implementation, even we could perhaps publish some, but one problem is that Finvoice specification is complex and quite flexible also, and is used in many different scenarios depending what you are invoicing. Even we have at least four different implementations for different use cases (normal sales invoice, expense invoice, invoices from deliveries, factoring invoice), so it is quite hard to make single version that would suit all use cases. But all of these require the basic address settings on partner to be able to implement these. 

What I am a bit surprised here is that all you are talking is about "directly link to the government". This is NOT a company to government issue. About 99% of Finnish companies uses e-invoicing bot for sending and receiving invoices, and it has nothing to do with government. Unless of course you invoice the government, which is only one of millions of e-invoice recipients. This is why you have to have these basic features to be able to use odoo in Finland at all. It is more or less a question are you interested of supporting Finnish localization or not?

**Comment by rnurmi** [comment]
Just to emphasize this, please check e.g. contact page of Sprintit Ltd. The website has nothing to do with actually sending invoices, but still we need to have the information stored in the system so that it is easy to publish along with other contact information. It is as necessary basic information as street address or email:

https://www.sprintit.fi/contactus

**Comment by jco-odoo** [comment]
It depends.  Import/export of Finvoice XML should not be a problem.  It is the complexity of the API by the FInvoice operator and the costs associated with using it.

**Comment by jarmokortetjarvi** [comment]
I would suggest using a Many2one -relation with einvoice operators.
For reference:
https://github.com/OCA/l10n-finland/blob/10.0/l10n_fi_edicode/models/res_partner.py

Unless there is a reason for allowing users to manually type the operator and operator code?

Including all operators and their codes in the module could be feasible, as there are limited number of einvoice operators in Finland
https://oma.tieke.fi/pages/viewpage.action?pageId=53870835
See:
https://github.com/OCA/l10n-finland/blob/10.0/l10n_fi_edicode/data/res_partner_operator_einvoice.xml

This approach has the advantage of forcing correct operator name and operator code, which will guarantee consistency. It will also help mirroring changes in operators and their codes (like the recent change with OpusCapita)

**Comment by lathama** [comment]
@elmeriniemela knowing that 12 is no longer updated, is this PR still needed?

**Pull request closed without merging**
