### PR TITLE
[FIX] account: fix model reconciliation recognized as refund

### PR DESCRIPTION
**Pull request by agr-odoo**
- Belgian accounting installed and active in currenct company
- Create a bank statement with a negative amount.
- Post it and reconcile using model "Frais bancaires TVA21"

Back to the bank statement, under Journal entries, the tax grids are
wrong: it reports "+82", "-85" and "-63" but it should be
"+82" and "+59"
This occur because the system interpret the move as a refund.

opw-2646291

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@Levizar 
Fix to match what is done in 
https://github.com/odoo/odoo/blob/038816725a988a0ada3d6f8518a436ea46a81eba/addons/account/models/account_move.py#L627
https://github.com/odoo/odoo/blob/038816725a988a0ada3d6f8518a436ea46a81eba/addons/account/models/account_tax.py#L298

**Review by oco-odoo — APPROVED** [review]
Big one ! Nice catch :) 

@robodoo r+

**Comment by oco-odoo** [comment]
@robodoo r-

Actually, I think the original fix was totally wrong. I'm investigating.

**Comment by oco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
