### PR TITLE
[ADD] misc.py: Dump current execution stack

### PR DESCRIPTION
**Pull request by lse-odoo**
This commit is primarily meant for support purpose.
For instance in cases in which data change without being able to determine the reason. With this commit we can create an automated actions on the model update trigger to dump the current stack that will lead us on the action that did trigger it.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by odony** [comment]
Some quick comments:
- as a debugging tool, I find it both invasive and not very convenient. What are you going to do with the trace? You'll need to insert it somewhere in the database, without impacting the current transaction, which may not always be trivial/cheap.
- how about we instead expose the `log()` method of a dedicated logger instance. You could then use `log(50, "this is the trace", stack_info=True)` in any server action to generate a detailed stacktrace in the server logs, where you expect debugging traces to be put.
- it's not a bugfix, so it should not be targeting stable versions ;)

**Comment by rco-odoo** [comment]
I totally agree with Olivier's remarks.

**Comment by lse-odoo** [comment]
> Some quick comments:
> 
> * as a debugging tool, I find it both invasive and not very convenient. What are you going to do with the trace? You'll need to insert it somewhere in the database, without impacting the current transaction, which may not always be trivial/cheap.
> * how about we instead expose the `log()` method of a dedicated logger instance. You could then use `log(50, "this is the trace", stack_info=True)` in any server action to generate a detailed stacktrace in the server logs, where you expect debugging traces to be put.
> * it's not a bugfix, so it should not be targeting stable versions ;)

I think the current version does respond to both of the first points.

I am aware that this PR should not be pushed in stable as it does not respect the first 2 points of:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean
At the same time, it would ease for us the support process in some specific cases (see an example in the original message). It would be a pity to have it only on version >= 15 while version 14 is supported for the next 3 years. 
Beside, the changes that I have made are very minor in my opinion, the only possible issue that is could cause is that the method `logger_log` would be already present (assuming it wouldn't be overrode by inheritance in a custom app/module). 

@oco-odoo @rco-odoo

**Comment by lse-odoo** [comment]
let's push it first to the future version 15 and we will see afterward for earlier versions :) 
https://github.com/odoo/odoo/pull/75320

**Pull request closed without merging**
