### PR TITLE
[FIX] website_slides: build a correct form in Courses

### PR DESCRIPTION
**Pull request by proose**
How to reproduce the problem:
- Install the website_slides modules
- Go to the website -> Courses -> choose a course -> Add Content (Webpage)
- In the new Webpage -> Edit -> Drag and drop a Form Builder -> Save
The form is unusable: you can't write in the form's fields.

Cause of the problem : usefull attributes and values of the form were
removed due to the sanitizing of the HTML component.

Solution : the HTML components in slide are not sanitized anymore,
in order to keep valuable information for building forms.

Huuuge thanks to @abz-odoo for his great help on finding the bug <3

opw-2588089

### CODE REVIEW

**Comment by proose** [comment]
Hi @odoo/rd-security,
Would it be ok to r+ this, or is there some other techniques to keep the form complete ?

**Comment by abz-odoo** [comment]
looking at how it's done for another similar field `gamification.description_motivational`

https://github.com/odoo/odoo/blob/b8a2f494607030bc50b85ba041cf2f14bfdcfed8/addons/gamification/models/gamification_karma_rank.py#L14-L15

we can see that they use odoo.tools.translate.html_translate and sanitize_attributes = False in 13.0
It should be able to work for 13.0 to master

**Comment by mart-e** [comment]
Indeed, if you can limit to `sanitize_attributes=False`, that would be better. In 14.0, we have a `sanitize_form=False` which is worth testing for the forward port.

@odoo/rd-security in 13.0 only "Restricted Editor" can modify slides. In 14.0, it's a new group "eLearning Officer".
Not sure about the level of trust with these.

**Comment by proose** [comment]
Unfortunately, just putting `sanitize_attributes=False` is not enough in 13.0 (it is in 14.0). I found out, in my tests, that if I force sanitize_form to be False, in the mail.py file, then, with `sanitize_attributes=False`, the form is correctly set up. But I'm aware I can't do that, so I'll try to find something else.

**Comment by xmo-odoo** [comment]
> Unfortunately, just putting `sanitize_attributes=False` is not enough in 13.0 (it is in 14.0). 

How come? Surely if the form tag is being stripped it's stripped in both versions? Or is it an issue with the version lf lxml specified for that version of odoo?

> I found out, in my tests, that if I force sanitize_form to be False, in the mail.py file, then, with `sanitize_attributes=False`, the form is correctly set up. But I'm aware I can't do that, so I'll try to find something else.

If the lxml used for 13.0 is compatible we could certainly backport `sanitize_form`.

**Comment by proose** [comment]
> How come? Surely if the form tag is being stripped it's stripped in both versions? Or is it an issue with the version lf lxml specified for that version of odoo?
I need to correct myself: in 14.0, the `sanitize_form` attribute of the html field is already used and set to False. That is why, in 14.0, just adding the attribute `sanitize_attributes=False` is enough. But that attribute doesn't exist in 13.0. If you say I can backport, then I'll try that.

**Comment by xmo-odoo** [comment]
> > How come? Surely if the form tag is being stripped it's stripped in both versions? Or is it an issue with the version lf lxml specified for that version of odoo?
> 
> I need to correct myself: in 14.0, the `sanitize_form` attribute of the html field is already used and set to False. That is why, in 14.0, just adding the attribute `sanitize_attributes=False` is enough. But that attribute doesn't exist in 13.0. If you say I can backport, then I'll try that.

Yeah but do check in which version of lxml `sanitize_form` was added, and if that matches the version specified in 13.0's requirements file / debian package.

**Pull request closed without merging**
