### PR TITLE
[FIX] l10n_dk: Update taxes and CoA

### PR DESCRIPTION
**Pull request by kenneth-vkd**
# In General
The localization has been redefined as per the standardized chart of accounts from the Danish Government (Erhversstyrelsen): https://erhvervsstyrelsen.dk/sites/default/files/2023-02/2023-01-31-Standardkontoplan.xlsx

This is unfortunately only defined in Danish so in order to keep features of Odoo where the various parts of the localization are defined in English, I have translated the various Danish text into English and provided as the source and then provided the Danish text as a translation in the CSV-files.

Below is an overview of the individual areas with changes as well as some points of consideration in terms of the requirements from the government and how things work in Odoo

This PR is a joint operation between us and Odoo S.A. as agreed with Olivier Maessen in order to be compliant with the new Danish Bookkeeping Act

## Chart of Accounts
In general the CoA only required some minor adjustments
The CoA was reviewed based on the above file using hte sheet named `II) Kontoplan`, where all entries with value in column `B` (`Overskrift`) have been ignored. In most existing Danish Accounting software, the chart of accounts
is also what defines the formula for how to P&L report and balance sheet are rendered. This is different in Odoo, since the reports are defined spearately within `odoo/enterprise`.
Some accounts have been removed, since the `code` conflicted with some of the above

The below shows what accounts are used, but now under different numbers/names

Before:

```
5960 - Accounts receivable
5961 - Accounts receivable (PoS)
```

After:

```
6190 - Trade and other receivables
```

Before:

```
7180 - Creditor
```

After:

```
7440 - Suppliers of goods and services
```

Before:

```
7681 - Reverse chargeable business tax
```

After:

```
7680 - Sales tax
```

The internal transfer account is currently set to the prefix of `683`, so this needs to find a new home. A good suggestion would be to have it be `6479` or `6489`, but since we define a prefix and not a specific account,
it is hard to lock it to a specific number and there is no gap in the numbering sequence within bank + cash.

## Taxes
For taxes there are 69 tax codes that must be possible to handle. While some of the are straight forward, others are more dynamically computed, for which changes in other parts of Odoo might be required first

All taxes are defined in the previously linked file on the sheet named `III) Momskoder Bruttoliste`.

The following rules have been applied to map the sheet to Odoo:

- `Overskrift` -> `description@da_DK` (The english translation is put in )
- `Momskode betegnelse` -> `name`
- `Salg/køb` -> `type_tax_use`
- `Momskode` -> `id` (Prefixed with `tax_` and the lowercase value of this field)
- `Momssats` -> `amount` (The `amount_type` field is set accourding the value here as well as the information from the column `Vejledning`)

The column `price_include` is explicitly set to `False` or `True` so that a fallback/default is not used and causing issues in future versions of Odoo in case the default value of the field changes

The column `active` is explicitly set to `False` or `True` so that a fallback/default is not used and causing issues in future versions of Odoo in case the default value of the field changes. Here the rule is that if the code is marked with `x` in the column `5. Særkoder` of the above Excel sheet, then the value will be `False`, as the code is then there, but should not be usable out of the box. Customers needing these codes can enable them in relevant companies on their Odoo instance. Codes not marked with `x` in the column `5. Særkoder` will have `True` by default, since they are expected to used by most companies.

Upon processing the rules, we found the following tax codes where a challenge is found and that needs handling:
`S-DK-25` handles within Denmark regardless of whether we sell products or services. This is fine in terms of taxes and tax reporting, since there are no rules that state a requirement to split these on the tax reporting for the government.
It does however give a challenge when handling international sales, since `S-DK-25` has to be mapped to `S-EU-V-0` for products and mapped to `S-EU-Y-0` for services.
Odoo has a field called `tax_scope`, which allows us to restrict the usage of taxes based on the product type, but it does not help with the above.
To handle this, we create a variation of `S-DK-25` for products and services and then have it use the same account and tax grids.
The above also applies for purchases in relation to `K-DK-Fradrag`, where we have done the same variation for `K-EU-V-Fradrag` for products and `K-EU-Y-Fradrag` for services.

`S-DK-Brugtmoms` is a special code, as noted by the column `5. Særkoder`. The computation of the tax amount here is based on the following official explanation (translated to English):

```
This code is used for the sale of goods that can be covered by the rules for calculating VAT on used goods and where VAT must therefore be settled on the difference between the selling price and the purchase price.
```

The above means that if purchase a used Meeting table for DKK 1000 and sell it for DKK 2000 a week later, then the taxes are calculated based on what I have earned on this sale.
Compute the difference between my purchase and my sale:
```
2000 - 1000 = 1000
```
Compute the tax based on the above difference
```
1000 * 0.25 = 250
```

When using Odoo inventory management, the above is quite simple when running manual inventory valuation and with standard price. If we however use automated valuation with FIFO, then we need to track each item and these do not always use lot/serial numbers.
A way is needed to handle this code in Odoo

`S-DK-Marginmoms` is quite similar to `S-DK-Brugtmoms` and has the following official explanation (translated to English):

```
This code is used by travel agencies etc. that have to settle VAT on the profit margin.
```

`S-DK-brugtbil` is also a bit special, as it computes similar to `S-DK-Brugtmoms`. Here is the official explanation (translated to English):

```
This code is used for the sale of used cars, where the seller can make a deduction from the calculated sales tax, on the basis of a calculation based on the purchase price of the used vehicle.
```

`S-Lokalmoms` is quite strange and needs to be handled, but should not go in the tax report. I have set the tax rate to 0, but realistically it must be dynanmic and it is needed to find a way for handling this in Odoo.
Here is the official explanation (translated to English):

```
This code is used for sales made in or to customers in other countries where sales are carried out with local VAT.
```

There is also some challenges around `OSS` or One-Stop-Shop taxes in Europe, since special codes are given. I have not defined these as Odoo already has a method of mapping the various taxes from the localization of each country.
There are however some requirements for the reporting, which might need to be handled by Odoo.
If required we can add the codes, just to ensure that they are there. It is however quite a challenge to get usable responses from the Danish government on how these are supposed to be handled

On the purchase side there are also a series of quite special codes, which we do not often see used, but the government does not list these as special codes, so we need a way to handle these in Odoo.
`K-DK-SkønsmæssigFradrag` is a special code that needs to reported the same as `K-DK-Fradrag`, but the percentage to be deducted is variable. So the tax rate is still 25 %, but how much of the 25 % can be deducted on our VAT statement is dynamic, based on the following official explanation (translated to English):

```
This code is used for the purchase of goods or services that are used both in connection with the activities subject to VAT and for purposes beyond the company's control and where the right to deduction must be calculated based on an estimate of the actual use. This can, for example, be the acquisition and use of mobile phones, internet access at employees' private addresses and the like.
```

The following taxes are not required to go in the tax report, but it should be possible to find them later for audit:
- S-DK-U
- S-DK-MF
- S-LokalMoms
- S-EU-MF
- S-%EU-MF
- K-DK-IngenFradrag
- K-DK-Brugtmoms
- K-DK-Marginmoms
- K-DK-brugtbil
- K-DK-leasingbiler mm
- K-EU-Momsfritaget

A written guide must be provided for how to find these journal entries or they must somehow be tagged.

This PR is a new iteration of #141989 with a few of the previously requested changes from @FlorianGilbert and @RicGR98 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kenneth-vkd** [comment]
@FlorianGilbert regarding the balance sheet as well as PnL, it will need some adapting in `odoo/enterprise` since some of the accounts now have different numbers.
Accounts 5960 + 5961 are now 6190
Account 7180 is now 7440

A choice does also need to be made on the internal transfer account

**Review by FlorianGilbert — COMMENTED** [review]
Hello

It looks good to me.
The problem is that I can't merge your pull request if it breaks stuff in enterprise (like Balance Sheet / Profit and Loss).
Do you agree that I cherry-pick your commit into my pull request where I'm using tags in BS/PnL?
I will keep your commit as it.

Here are the pull requests:
https://github.com/odoo/odoo/pull/143820
https://github.com/odoo/enterprise/pull/50676

**Comment by kenneth-vkd** [comment]
@FlorianGilbert no problem from my end.
we all need these sets of changes to get Odoo approved as a bookkeeping system for Denmark

**Review by FlorianGilbert — COMMENTED** [review]
Hello @kenneth-vkd 

Thank you again for your contribution, I'm closing this pull request as I cherry-pick your commit.

**Comment by malb-odoo** [comment]
Hello @kenneth-vkd ! Hope you are well :smile: 
We currently have a ticket complaining on some taxes configuration that you made in this PR. 
A client is telling us that a tax grid is wrong or missing here is the screenshot provided by the client:
V17: (wrong ?)
https://drive.google.com/file/d/1Qk-kCbWYY3c3P1EKNcE7V53xNU8AoK1U/view?usp=sharing

V16: (correct) 
https://drive.google.com/file/d/1TOVfoqlip-Dhd0bY47gVayuvggWMUpXc/view?usp=sharing

He is telling us the following:
"There has not been any changes in the rules for these particular two tax codes I refer to in my video. If you follow the link below and open the last paragraph you will see that in the bottom it is clearly stated that we have to report the value of the total sales of goods and services in Field C in the tax report. But the current tax code setting in v17 does not do that.

If you look at the same tax code in v16 then it is correct.

Link:
https://skat.dk/erhverv/moms/moms-ved-handel-med-udlandet/moms-ved-handel-med-virksomheder/moms-ved-handel-med-lande-uden-for-eu/moms-ved-salg-af-varer-og-ydelser-i-lande-uden-for-eu"

**Comment by kenneth-vkd** [comment]
@malb-odoo That is indeed correct.
The issue comes when odoo attempts to compute the taxes and assign the tax grids, as there is technically no tax to be computed when the tax amount is 0.
So the solution would be to revert the specific implementation of that tax code into what was there in v16.

Are you able to perform a new PR on this yourself or would you like my assistance in making it and what can be done to fix it for databases already running with the incorrect configuration for this tax?

**Comment by malb-odoo** [comment]
@kenneth-vkd What should be the tax then ? Just add the +R-CUR tax grid to the base ? Or do we need to remove the other tax grids (MVU, FM) from it aswell ?
I think we have a reload tax kind of thing for databases already running with the incorrect configuration for this tax :smile:

**Comment by kenneth-vkd** [comment]
@malb-odoo we need to remove MVU and KM from the repartition lines, since they do nothing when the tax amount is 0
And then add +R-C-UR to the base as we need to report the value of the goods sold.

So fixing the issue will be a manual task for affected databases or is it possible to automate this when databases get a new build of Odoo 17.0?

**Comment by malb-odoo** [comment]
@kenneth-vkd i will do a PR to fix that thanks ! And i think it can only be a manual thing :grimacing:, either upgrading the module or the reload tax thing

**Pull request closed without merging**
