### PR TITLE
[FIX] pos_hr: quick fix for the 'TypeError: HrEmployeePublic.read() got an unexpected keyword argument 'load'' traceback

### PR DESCRIPTION
**Pull request by shyamgohil2000**
Description of the issue/feature this PR addresses:
Fixed the odoo traceback which arises while opening a pos session.
image_2024_04_02T04_30_44_686Z

Current behavior before PR:
Traceback is showing to user who does not have any groups assigned for employees model in Human Resource.

Desired behavior after PR is merged:
It'll solve the traceback arises due to missing keyword argument!

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nfl-odoo** [comment]
Duplicate of: https://github.com/odoo/odoo/pull/160089

**Comment by shyamgohil-envertis** [comment]
#160087

**Comment by shyamgohil2000** [comment]
#160087

**Comment by shyamgohil2000** [comment]
#160087

**Pull request closed without merging**
