### PR TITLE
[FIX] website_blog: display the first post correctly on the blogs page

### PR DESCRIPTION
**Pull request by SergeBayet**
Prior to [1], when the "Name / Latest post" option was active and "Full-width" was disabled, the blogs page displayed the first blog post as a cover. However, [1] replaced this dynamic cover with a static one titled "Our latest posts," inadvertently omitting the first blog post from the page.

Steps to reproduce the issue:

- Navigate to the "Blog" menu.
- Enable "Edit" mode.
- In the "Customize" panel, disable the "Full-width" option.
- The latest blog post no longer appears in the list.

This commit resolves the issue by ensuring the first blog post is displayed correctly.

[1]: https://github.com/odoo/odoo/commit/05ef95d3f13ac42713bb8d8a3002f149345cc08b

opw-4289735

### CODE REVIEW

**Comment by bvr-odoo** [comment]
@SergeBayet Do we still need the "Full-Width" option on the "/blog" page ? It really seems unnecessary now... It only adds a separator below the title.

**Comment by SergeBayet** [comment]
> @SergeBayet Do we still need the "Full-Width" option on the "/blog" page ? It really seems unnecessary now... It only adds a separator below the title.

@bvr-odoo 
I would definitely agree with you, but that's not my call. And probably something to do in master. What do you think @lebl-odoo ?

**Comment by lebl-odoo** [comment]
I had in mind @stefanorigano shared me about this recently, but I can't remember the output. Can you confirm the option is still relevant over here?

**Comment by stefanorigano** [comment]
Hello 👋

> I had in mind @stefanorigano talked me about this recently, but I can't remember the output. Can you confirm the option is still relevant over here?

@lebl-odoo, I don’t think that discussion is relevant for this PR **specifically**, but I think that you're referring to the possibility of removing the "Full-width" option, right? 
Let's keep in mind that it has a purpose for the blog "categories"...
| Full-width: ON | Full-width: OFF |
|--------|--------|
| image | image | 

... but having said that:
- The current "Full-width: OFF" visual result it's not great and it should be eventually improved
- The option doesn't provide value for the index (/blog) page... besides ensuring consistency with category pages (... and that's already enough? 🤔). Honestly I don't know what was the plan we it has been decided to replaced the "promoted post"with a static title -> thus making this feature "useless" here...  I really miss that feature btw 🥲

**Comment by lebl-odoo** [comment]
To sum up, let's keep the option. We'll see how we can improve it later.

**Comment by qsm-odoo** [comment]
@robodoo delegate=bvr-odoo 
@bvr-odoo

**Comment by SergeBayet** [comment]
@robodoo r+

**Review by bvr-odoo — APPROVED** [review]
LGTM 👍🏼

**Comment by bvr-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
