### PR TITLE
[IMP] project: populate

### PR DESCRIPTION
**Pull request by Feyensv**
New populate feature (#48479) now allows to define model generation methods to populate the database with model records for performance testing.

This PR aims to implement database population for the `project` App.  
Furthermore, to reduce population time, a first performance improvement is applied to create `project.task` records in batch.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
Hi @Feyensv ! 

Thanks for the feedback. Could you please create a task in our project, so that I don't forget to review this ? 

Thanks.

**Comment by Feyensv** [comment]
I'll update some things to follow Xdo review on another PR and then I'll move the task in your project ;).

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo rebase-ff

**Comment by tivisse** [comment]
@robodoo merge

**Pull request merged**
