### PR TITLE
[FIX] tools: add SQL comparaison to fix module translation

### PR DESCRIPTION
**Pull request by ghost**
When installing both documents and fleet and then, add a translation to the database. Both fleet and document will be translated the same way. This is due to the fact that both of them share a lot of similar value inside of the PSQL database.

opw-3120320

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to  me

opw is missing from commit message if there is one

note: to be more precise, the conflict in this case was between `ir.ui.menu` with xmlIDs `fleet.menu_root` and `documents.menu_root`, translation of one would override the translation of the other since we only matched on `model` and `ir.model.data().name`.

checking on 16.0 runbot, this could be happening to more than these case: https://gist.github.com/nle-odoo/eacbc8f666be3a175bc53af0f8ce4e80

**Comment by joda-odoo** [comment]
My bad it's fixed :)

**Review by HydrionBurst — APPROVED** [review]
you are right, thanks for the fix 👍

**Review by rco-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
