### PR TITLE
[IMP] spreadsheet: update o_spreadsheet to latest version

### PR DESCRIPTION
**Pull request by pro-odoo**
### Contains the following commits:

https://github.com/odoo/o-spreadsheet/commit/7cfe14ab4 [REL] 17.4.0-alpha.12 Task: 0
https://github.com/odoo/o-spreadsheet/commit/c93e3b327 [FIX] border: bottom sheet borders removed on DELETE_ROWS Task: 3911695
https://github.com/odoo/o-spreadsheet/commit/ce5cb3862 [IMP] FindAndReplace: warning when replacing formula Task: 3942592
https://github.com/odoo/o-spreadsheet/commit/830ad0377 [IMP] tests: add typing for window Task: 4037352
https://github.com/odoo/o-spreadsheet/commit/5ecec6e19 [IMP] top_bar: allow to change the order of the top bar components Task: 4000864
https://github.com/odoo/o-spreadsheet/commit/7306b17e0 [IMP] pivot: format quarter_number Task: 3899604
https://github.com/odoo/o-spreadsheet/commit/d152751c5 [IMP] pivot: correctly name periods in pivot table Task: 3899604
https://github.com/odoo/o-spreadsheet/commit/64e5180b2 [FIX] locale: handle undefined thousands separator Task: 0
https://github.com/odoo/o-spreadsheet/commit/1b181bac6 [FIX] chart: cumulative not working for linear charts Task: 4028957
https://github.com/odoo/o-spreadsheet/commit/92cf087bf [DOC] improve plugin documentation Task: 0
https://github.com/odoo/o-spreadsheet/commit/d1aa82791 [IMP] doc: Add documentation for translations Task: 0
https://github.com/odoo/o-spreadsheet/commit/c348ed127 [FIX] demo: demo server was watching the wrong file Task: 0
https://github.com/odoo/o-spreadsheet/commit/4d81df4be [FIX] clipboard: Fixed pivot formula keep their reference Task: 4023453
https://github.com/odoo/o-spreadsheet/commit/9e976c596 [FIX] grid: prevent paste default Task: 3949903
https://github.com/odoo/o-spreadsheet/commit/bca9b6835 [FIX] parser: `parse` should handle unbounded references Task: 4010920

Co-authored-by: Anthony Hendrickx (anhe) <anhe@odoo.com>
Co-authored-by: Alexis Lacroix (laa) <laa@odoo.com>
Co-authored-by: Lucas Lefèvre (lul) <lul@odoo.com>
Co-authored-by: Dhrutik Patel (dhrp) <dhrp@odoo.com>
Co-authored-by: Adrien Minne (adrm) <adrm@odoo.com>
Co-authored-by: Mehdi Rachico (mera) <mera@odoo.com>
Co-authored-by: Rémi Rahir (rar) <rar@odoo.com>
Co-authored-by: Pierre Rousseau (pro) <pro@odoo.com>
Co-authored-by: Vincent Schippefilt (vsc) <vsc@odoo.com>

### CODE REVIEW

**Comment by pro-odoo** [comment]
robodoo fw=no

**Comment by pro-odoo** [comment]
robodoo rebase-merge

**Review by aab-odoo — APPROVED** [review]
for the commit in web

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Pull request closed without merging**
