### PR TITLE
New multi-lang l10n_sa CoA - PR2

### PR DESCRIPTION
**Pull request by mohamedhagag**
New clean PR instead of the old one at #7693

### CODE REVIEW

**Comment by mohamedhagag** [comment]
Hi @mart-e , this is the new PR.

Regards,

**Comment by mohamedhagag** [comment]
@antonylesuisse @mart-e

**Comment by mohamedhagag** [comment]
@mart-e Hi martin, would you please confirm this bug and merge the commit related to anglo-saxon module.
@alhashash  @simongoffin did we get any testing on this bug ?

Regards,

**Comment by mart-e** [comment]
Hello,

The translation file can probably be moved to a `i18n_extra` folder as `i18n` would be for terms translated in any language.

For anglo-saxon, could you check #8457 ? The issue with your fix is that you always fall in the condition making the if useless.

**Comment by mart-e** [comment]
Also we can not accept the python part of the CoA for the generation of sequences. This is duplication of code and it applies to every company of the instance, not only the one using the Saudi accounting

**Comment by mart-e** [comment]
and (finally) merged the CoA at 9069f29efa4e430b6f48cecf390252e99febbf33, thanks !

**Comment by mohamedhagag** [comment]
Thanks @mart-e appreciate your great efforts, and thanks for all Odoo SA. staff adding this huge project as addition to FOSS world ;) .

**Pull request closed without merging**
