### PR TITLE
[FIX] stock: product search by location or warehous

### PR DESCRIPTION
**Pull request by ppr-odoo**
Task:https://www.odoo.com/web#id=1816798&view_type=form&model=project.task&action=333&active_id=1278&menu_id=4720
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by celm1990** [comment]
This commit can be backported to V11????

**Comment by mart-e** [comment]
Definitely not adding a `store=False` in stable.
Can be discussed on #23261 for master

**Comment by sle-odoo** [comment]
@mart-e let's talk about this one tomorrow

**Comment by jco-odoo** [comment]
Inverse search method is mandatory, but without it will still throw an error.  (a non-stored field can not be searched) So even with just store = False, it would work.  These fields are not used, so we can perfectly do this in stable.  (in the ultra-exotic case where they would use the field, they could still copy it into another field)

What it does is changing the context within the _compute_quantities_dict method.
{'lang': 'en_US', 'tz': 'Europe/Brussels', 'uid': 1, 'params': {'action': 170, 'view_type': 'kanban', 'model': 'product.template', 'menu_id': 114, '_push_me': False}, 'search_default_consumable': 1, 'default_type': 'product', **'location': 'Chic/Stock'}**

In this case I selected Chic/Stock from the search view and e.g. the qty on hands became 0 because we did not have any stock in this location.  (same is possible with the warehouse)

**Comment by sle-odoo** [comment]
After discussion with @odony 
- write a proper commit message + comments in the code, the goal of the change is not to be able to search a location_id/warehouse_id but to properly make these fields "dummy": only used to put some keys in context from the search view in order to influence computed field, etc.
- merge in 11
- make sure that a read on the now unstored field is working properly (ie a compute method is not needed)
- check it doesn't break anything else

**Comment by jco-odoo** [comment]
It is as well a bug in v10...

**Comment by simongoffin** [comment]
Closed with https://github.com/odoo/odoo/commit/7c7b0992734ded9e72a04e4a412582763cff9a79

**Comment by manrif** [comment]
Hi, 

Is there an update on this ticket? I have the same problem in V10, I'm not able to filter products by warehouse. I tried using the warehouse and the location, neither work.

**Comment by sle-odoo** [comment]
@manrif the issue is fixed in v11 but won't be backported in v10 sadly, as we need to change the models.

**Pull request closed without merging**
