### PR TITLE
[FIX] website: fix incorrectly bound click event

### PR DESCRIPTION
**Pull request by divy-odoo**
This commit adds an alias variable to ensure that the same events are bound and removed.

task-3370847

### CODE REVIEW

**Comment by robinlej** [comment]
It this ready for review? (I don't see why it wouldn't be.) If so, mark the PR as such please :)

**Comment by divy-odoo** [comment]
@robinlej ready to go now!!
waited for the runbot to be green.

Thanks : )

**Comment by robinlej** [comment]
Can you mention in the message the commit that introduced the issue please?

**Comment by bso-odoo** [comment]
@robodoo delegate=robinlej

**Comment by robinlej** [comment]
I pushed with the link to the merged commit rather than the PR. I'll r+ when it's green :)

**Comment by robinlej** [comment]
@robodoo up to 16.0 r+

**Pull request closed without merging**
