### PR TITLE
[IMP] cleanup of help messages in all modules

### PR DESCRIPTION
**Pull request by fpodoo**
[IMP] cleanup of help messages in all modules
    
This commit aims at removing unuseful help message to:
1/ reduce translators work, to focus on more useful translations
2/ not sending unuseful information in load_views
3/ reduce help message to useful messages, so that we can mark
   fields having a tooltip in the future UI.
4/ some cleanup of existing messages too
   
The main use cases:
- REMOVED: help redundant with the field name, providing no extra info
- MOVED TO COMMENT: technical help messages, that should not be in UX
- IMPROVED help messages

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fpodoo** [comment]
@robodoo r+

**Comment by william-andre** [comment]
Thanks for all the conflicts and the un-reviewed commit.

Being the CEO doesn't make that ok.

**Comment by fpodoo** [comment]
> Thanks for all the conflicts and the un-reviewed commit.
> Being the CEO doesn't make that ok.
> Maybe this looks fast and efficient to you, but it is making lose time to a lot of devs and possibly support too because we always need to clean those self "reviewed" changes. We are not in a rodeo.

With, or without reviews, such a PR will always do conflicts. It is ok, there is no other way.

Asking 0, 1 or multiple people to review is a matter of common sense, based on the PR, and assessment of risk of PR / value of review. And good judgment is always better than blindly following processes. (BTW, I don't think our process forces every commit to have at least one review?)

It's a trade-off; will a developer's time contribute more to Odoo if he develops / reviews his tasks, or if he waste a few hours reading this PR. In this case, it's obvious; the risk of the PR is close to 0, and people will better contribute to Odoo doing their regular tasks rather than wasting 2 hours reading this.

Summary: no, you or the support should not waste time reviewing this; your time will be more valuable on other tasks.

**Comment by william-andre** [comment]
> Asking 0, 1 or multiple people to review is a matter of common sense, based on the PR, and assessment of risk of PR / value of review. And good judgment is always better than blindly following processes. (BTW, I don't think our process forces every commit to have at least one review?)

* You missed some
* You removed some that you shouldn't have removed
* Functional teams would have been able to review and change the tooltips with a better understanding and better though message.

> Summary: no, you or the support should not waste time reviewing this; your time will be more valuable on other tasks.

I lost time this morning and I really do not have time for this. You delayed my time off. I shouldn't have to do over time because of a self r+

> the risk of the PR is close to 0, and people will better contribute to Odoo doing their regular tasks rather than wasting 2 hours reading this

The risk of having bugs is *low*, but having to fix your commits with some more commits and conflicts is a technical debt that could be avoided.

I hope you have better things to do with your time than this, in my opinion you really should have delegated this to functional teams.
This way, it also makes them aware of this change, reducing the risk of them re-introducing the same "issues" in the future.


> It's not rodeo

Then why am I aware of every single one of your commits in less than 24h, should it be touching the code that I work with or not?

**Pull request closed without merging**
