### PR TITLE
[FIX] account: group by payment date

### PR DESCRIPTION
**Pull request by william-andre**
Reproduce:
* Accounting > Vendor > Amounts to Settle
* Group By: Due Date (any)

There is an error because `payment_date` is not stored.

We also allow more operators in `_search_payment_date` because the `read_group` will use `<=` and `>=` to open the groups. We still transform `=` to `<=` to enable the quick search.

### CODE REVIEW

**Comment by smetl** [comment]
@robodoo r-

**Comment by smetl** [comment]
@robodoo delegate+

**Comment by william-andre** [comment]
@robodoo override=ci/style r+

**Comment by Xavier-Do** [comment]
@robodoo override=ci/style

**Comment by william-andre** [comment]
@robodoo rebase-ff

**Comment by william-andre** [comment]
@robodoo r-

Will add a new commit for a new kind of related feedback...

**Comment by william-andre** [comment]
@robodoo r+

**Pull request closed without merging**
