### PR TITLE
Odoo Portal In Bengali

### PR DESCRIPTION
**Pull request by MjAbuz**
Description of the issue/feature this PR addresses: 

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@MjAbuz are you trying to add the Bengali language into Odoo here? This should be done in Transifex (see https://github.com/odoo/odoo/wiki/Translations)
@mart-e can you followup please?

**Comment by MjAbuz** [comment]
> @MjAbuz are you trying to add the Bengali language into Odoo here? This should be done in Transifex (see https://github.com/odoo/odoo/wiki/Translations)
> @mart-e can you followup please?

Thanks 

> @MjAbuz are you trying to add the Bengali language into Odoo here? This should be done in Transifex (see https://github.com/odoo/odoo/wiki/Translations)
> @mart-e can you followup please?

Thank you so much for the update however i did try to add the language there twice and tried adding myself to the team but for the first time when i requested to add bangali i did not get any response and then second time the request being declined and not sure why?? Should i go ahead and request once again to add bangali??

**Comment by MjAbuz** [comment]
@mart-e could you please help me with adding bangali in Transifex here is my id in Transifex https://www.transifex.com/mediajockey/

**Comment by mart-e** [comment]
@MjAbuz please be patient, I have added Bengali in the Transifex Odoo 12 project and added the language in Odoo at #28640.

You will now be able to start translating the latest version (lets start with this one only as it is a lot of work if you are alone).

**Comment by MjAbuz** [comment]
> @MjAbuz please be patient, I have added Bengali in the Transifex Odoo 12 project and added the language in Odoo at #28640.
> 
> You will now be able to start translating the latest version (lets start with this one only as it is a lot of work if you are alone).

i still dont find Bengali there https://www.transifex.com/odoo/odoo-com/ to join the team

**Comment by mart-e** [comment]
Because it is the project to translate odoo.com (only a few selected language).
As said above, I have added it for https://www.transifex.com/odoo/odoo-12/

**Pull request closed without merging**
