### PR TITLE
[FIX] account: Wrong entries for account voucher transaction with VAT

### PR DESCRIPTION
**Pull request by simongoffin**
Steps to reproduce the bug:
- Create a vendor receipt with taxes in a journal with a foreign currency
- Validate it

Bug:
- The amount currency on the aml with taxes was not set.

opw:2007760

### CODE REVIEW

**Comment by simongoffin** [comment]
Hello @qdp-odoo 

What do you think about it?

**Comment by simongoffin** [comment]
Hello @csnauwaert 

I also had to fix the 10.0 for this issue.
As you reviewed the PR: https://github.com/odoo/odoo/pull/34203
I thought about you ;)

**Comment by simongoffin** [comment]
Hello @qdp-odoo 

What do you think about it?

**Comment by yelizariev** [comment]
Fixed in v12, so can be closed https://github.com/odoo/odoo/pull/34203

**Pull request closed without merging**
