### PR TITLE
[CLA] Signature for nguyenductamlhp

### PR DESCRIPTION
**Pull request by nguyenductamlhp**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
That is not your email you are using for the CLA signature 😉

**Comment by mart-e** [comment]
Hello,

Still not the correct email address

- you are signing _using_ the address `t...@trobz.com`
- you are signing _for_ the address `n...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by nguyenductamlhp** [comment]
I have commit with git global user.email same as signing email in .md file. Is it correctly?

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it has been integrated into Odoo at revision https://github.com/odoo/odoo/commit/094c735f005f183b5a2b6ec7d803bba4516e9bd9.
Future pull requests made on odoo will be validated by the runbot.
Regards

**Pull request closed without merging**
