### PR TITLE
[FIX] stock: din A/B paper format

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
- Install l10n_de and Barcode
- Go to default company (San Francisco)
- Change default paper format to External Layout Din 5008 Type A or B
- Print Barcode commands

Bug:
Inventory Commands prints off the screen

Fix:
hardcode DPI value similar to other paperformats on that report

opw-3452344

### CODE REVIEW

**Comment by HANNICHE-Walid** [comment]
before:
image

after:
image

**Comment by HANNICHE-Walid** [comment]
note: to test the change you can change DPI in settings paperfomat

**Review by nle-odoo — APPROVED** [review]
as we discussed, would probably be safer with `<t t-set="data_report_dpi">...</t>` on the specific reports

like that it would looks good to me

**Review by DjamelTouati — APPROVED** [review]
LGTM, thank you for the fix! But I think it's better to change the paperformat than to change the dpi of the report, have you tested this solution?

**Pull request closed without merging**
