### PR TITLE
[IMP] project: Improve onboarding tour

### PR DESCRIPTION
**Pull request by dmonzonis**
The onboarding tour of the project app has been improved by changing
some messages and changing the flow to show users how to use the chatter
features within tasks.

Task ID: 2238624

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@dmonzonis Please don't force push the branch after I've r+ it.

**Comment by tivisse** [comment]
@robodoo r+

**Comment by dmonzonis** [comment]
@tivisse Sorry, but I still had one change to do so that the tests would pass (was waiting on another task to be merged)

**Pull request closed without merging**
