### PR TITLE
[FIX] hr_expense: default_expense_line_ids can be used multi time

### PR DESCRIPTION
**Pull request by agr-odoo**
backport of https://github.com/odoo/odoo/pull/52457 for v13

Create an expense
Click "Create report"
Save the report A (you can also submit, post inventory, ...)
Now click on Create (a new report B)

The expense in A are copied in B because default_expense_line_ids
are not cleared

opw-2271851

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@fw-bot ignore

**Comment by agr-odoo** [comment]
@nim-odoo

**Comment by nim-odoo** [comment]
fw-bot up to master

**Comment by nim-odoo** [comment]
robodoo r+

**Pull request closed without merging**
