### PR TITLE
[IMP] l10n_{it,es}_*: add the preferred edi format for E…

### PR DESCRIPTION
**Pull request by clbr-odoo**
…S/IT

Add FatturaPA as the preferred EDI format set by default on Italian partners. Fix the preffered EDI format of Spanish partners to be correctly computed to Facturae.

task-no

### CODE REVIEW

**Review by smetl — APPROVED** [review]
@robodoo r+

**Comment by clbr-odoo** [comment]
@robodoo r- failing test

**Comment by clbr-odoo** [comment]
@robodoo r-

**Comment by smetl** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
