### PR TITLE
CLA

### PR DESCRIPTION
**Pull request by benoit-bertholon**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
I let th @odoo/rd-logistics team review the second commit but for the CLA, the issue is that you need to add your `b...@bertholon.info` email address into the CLA file, this how it will be validated.

**Comment by benoit-bertholon** [comment]
> I let th @odoo/rd-logistics team review the second commit but for the CLA, the issue is that you need to add your `b...@bertholon.info` email address into the CLA file, this how it will be validated.

Sorry I read git login instead of git email ....

**Comment by benoit-bertholon** [comment]
> > I let th @odoo/rd-logistics team review the second commit but for the CLA, the issue is that you need to add your `b...@bertholon.info` email address into the CLA file, this how it will be validated.
> 
> Sorry I read git login instead of git email ....

and I removed the other commit

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
