### PR TITLE
[IMP] PurchaseOrderLine: Allow inheritance…

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
to modify base_price and quantity.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
This PR reintroduce https://github.com/odoo/odoo/pull/1468 into v9 and add possiblity to https://github.com/OCA/purchase-workflow/pull/214 to work

**Comment by sbidoul** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@odony, if you remember, I did a PR for adding some hooks on purchase module that allows to make customizations like the module _purchase_discount_: https://github.com/odoo/odoo/pull/1468, but on https://github.com/odoo/odoo/commit/cb01be235e73cf948418e41642d4906ff84906a6, they were removed in the adaptation to new purchase module.

Can you please accept this PR for adding them again?

By my part, :+1:

**Comment by JonathanNEMRY** [comment]
OPW 671969

**Comment by odony** [comment]
@pedrobaeza I understand your point of view, but now we start to see the problem with "empty" hooks like the ones introduced in #1468: they look kind of useless so they tend to be removed quickly.
What you really want here (e.g. for `purchase_discount`) is to alter the subtotal of the line, not really to modify the unit price or quantity of the line. And the most logical way to do it is to override the `_compute_amount` function that does the calculation, really.
You can still call `super` and reuse the result to avoid bypassing other overrides, even though it is difficult to imagine that 2 independently written extensions would be able to override the calculation of the line subtotal without breaking each other (with or without hooks).

BTW, in v9 the number of lines that you would need to duplicate has become smaller than the number of diff lines in this PR...

**Comment by pedrobaeza** [comment]
At least on v8, the problem was with the taxes computation, but let me check now if this is not a problem. Please don't close this until I check it.

**Comment by JonathanNEMRY** [comment]
@odony @pedrobaeza 
For me this modification always makes sense in v9.
Of course we can overwrite `_compute_amount` which is really more little to overwrite than the previous concerned code.
But here if we interest to the content then calling the super and do another computation means that we will compute/update twice the same thing by possibly knowing that this will not be the final result. (useless lost of performance and not very a best practice)
Here is the possibility to have a proper way to do it without modifying the current code.
Please reconsider to accept this one into the 9.0

regards

Jonathan

**Comment by odony** [comment]
@JonathanNEMRY Here is the bad practice: adding pointless accessors/hooks that serve no apparent purpose except for a single case of overriding. This is what makes them likely target of removal.

Performance is not an issue here, unless you have numbers to back up this claim. In fact, it  makes sense to override a *compute* function without calling `super` when you make significant changes to the algorithm computing it - which seems to be the case here. It's like changing an Excel formula.

**Comment by JonathanNEMRY** [comment]
@odony I never heard before than adding flexibility into code is something we can call "pointless", even more when we're talking about programming into a modular environment.
About the performance there will be no magic in numbers like it is simply `TimeOfSuper*2+TimeOfAddedValue` (so if super is long current will be too...)
Not calling the super definitively breaks the inheritance chain and nobody else will be able to change the behavior without breaking mine. For example: what about two modules: one that plays on prices and another that changes quantity?
So Improvements into the flexibility of the application like this current one are truly not a bad practice into a modular environement

**Comment by sbidoul** [comment]
@odony  In the past, you (I mean Odoo, nothing personal) were accepting simple refactorings that improved extensibility provided that did not create risks for the stability of the code base. I see a clear trend to have these rejected now (this one is only a last example). It's a pity and really regret this trend.

@JonathanNEMRY, override _compute_all, calling super and dumping the result. We'll reopen in case this creates a performance issue in practice.

@pedrobaeza do you agree?

**Comment by pedrobaeza** [comment]
@odony @sbidoul @JonathanNEMRY Indeed it's a pity to need to do this kind of hacks:
```
@api.depends('discount')
def _compute_amount(self):
    prices = {}
    for line in self:
        if line.discount:
            prices[line.id] = line.price_unit
            line.price_unit *= (1 - line.discount / 100.0)
    super(PurchaseOrderLine, self)._compute_amount()
    # restore prices
    for line in self:
        if self.discount:
            line.price_unit = prices[line.id]
```
for getting a similar behavior without breaking inheritance chain, so please reconsider to reintroduce the hook. This is not only a single case nor pointless hook. It serves for all the customizations that modifies purchase order line final price.

Another option can be to have a non stored "price_unit_final" field that is used in the computation of the amounts, and that we can modify overriding its compute method.

**Comment by tivisse** [comment]
Hello @JonathanNEMRY 

Thank you for the report but I will have to reject this, sorry.

You should probably use computed fields instead of introducing hooks with only one line to return the price and the quantity.

The 9.0 is now in end of life cycle and will soon be unsupported. We are only patching critical or security issues. The risk of regressions or introducing side effects is too high.

Regards

**Comment by tivisse** [comment]
Dear All, 

After a discussion with @pedrobaeza we agree that the discount mechanism should be implemented in the purchase module in the same way it has been done in the sales module.

Finally I've introduced a hook method in master (See: https://github.com/odoo/odoo/commit/ce1f1b69e75e8ab77083010a8487bfc35bbbb903)

The goal is tro create an internal task to implement the mechanism in master and remove the hook method when it's done. While waiting the development you can still do what you wish by overriding it. 

I hope that this trade-off makes you happy. For your information I'm still in Sevilla till Wednesday and I like cookies (@tde-banana-odoo too).

Have a nice day,

Yannick.

**Comment by pedrobaeza** [comment]
tenor

**Comment by pedrobaeza** [comment]
giphy

**Pull request closed without merging**
