### PR TITLE
[PERF] account: speedup `_count_results_and_sum_amounts` in dashboard

### PR DESCRIPTION
**Pull request by pivi-odoo**
## Description
After importing a large quantity of pending bills with no `invoice_date`, the dashboard can be significantly slow.
The bottleneck comes primarily from the hot loop in `_count_results_and_sum_amounts`, as it's iterating over a potentially enormous list of dictionary of query results.
This patch improvement consists mostly of hoisting invariants out of this hot loop, most impactful is the call to `context_today`, which does a lot of computation/conversions to apply the proper timezone and localize the date.

## Benchmark

| len(results_dict) | Before | After | Speedup |
|-------------------|--------|-------|---------|
| Timings (10k)     | 250ms  | 50ms  | 5x      |
| Timings (50k)     | 1.2s   | 300ms | 4x      |
| Timings (100k)    | 2.7s   | 820ms | 3.3x    |
| Timings (250k)    | 6.7s   | 1.7s  | 3.9x    |
| Timings (~600k)   | 13s    | 4s    | 3.25x   |

## Reference
opw-4235252

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by svfu-odoo — COMMENTED** [review]
Nice catch on the `context_today`. :+1: 
Since you basically change the whole function anyway have you tried moving the `document_currency` and `date` into the `else` branch? (not sure it makes a difference)
Or maybe the diff could be reduced a bit? (I get that performant code is not necessarily "nice" and it is fine for me generally speaking)

**Comment by pivi-odoo** [comment]
> Nice catch on the `context_today`. 👍 Since you basically change the whole function anyway have you tried moving the `document_currency` and `date` into the `else` branch? (not sure it makes a difference) Or maybe the diff could be reduced a bit? (I get that performant code is not necessarily "nice" and it is fine for me generally speaking)

Hmm, I've just tried your suggestion, as it seemed a good idea to move them to the else branch, but after re-benching, for the last case (the largest), and funnily enough, it's *consistently* slower (by around 400~500ms). As for the reason, I have no idea why, probably a question of cache locality 🤷🏼.
As for the diff size, it's pretty reasonable IMHO, I just took the opportunity to remove a left-over comment when `curr_cache` was still a thing and remove redundant `()` for the return tuple.

**Review by svfu-odoo — APPROVED** [review]
Thank you for testing my ideas. LGTM
@JulienVR for final review

**Review by JulienVR — APPROVED** [review]
thank you @svfu-odoo and @pivi-odoo :)
@robodoo r+

**Pull request closed without merging**
