### PR TITLE
[FIX] sale : get correct button title invoice email

### PR DESCRIPTION
**Pull request by Mtaylorr**
When we have automatic invoicing enabled , the email sent to the user when he confirms his payment online will contain a button 'View Journal Entry'

To reproduce the error :
1- Install accounting, website, ecommerce, sales apps 
2- Go to website settings and activate automatic invoice 
3- Install test payment method and activate it
4- Log out of the current account
5- Make a purchase of any item and confirm the payment 
6- You will receive 2 emails , the second one will have the invoice and it will contain a button View journal entry

The origin of the problem is not providing model_description when sending the invoice so it will take the display_name of the model 'account.move' by default which is Journal entry.

opw-3271345

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
fixing it there looks good to me

the current version is not translated so it's an issue, checking other sending of invoice, we should probably rather do:

```py
invoice.with_context(model_description=invoice.with_context(lang=lang).type_name)...
```
and the lang should be correctly set, in the other sending of invoice it is set like this:

```py
lang = template._render_lang(self.ids)[self.id]
```
(template being a mail template, and self being an account move record)

**Review by Feyensv — COMMENTED** [review]
1) AFAICS, you want to do the translation of the model_description with the current user (and not the SUPERUSER one).

IMHO, we should strive to avoid as much as possible to manage language in the business code, and move the `with_user` instead (cf my suggestion).

2) This method is mostly called by a cron, which means in most cases, the current user will be the superuser anyway (and the language will fall back on the superuser language).
I believe we want to send the right model_description in those case as well, maybe it could be fixed with the `_render_lang` NLE was speaking of.

3) Seems that `type_name` doesn't depend on the lang in the context, which means (if 2 is considered) that the prefetch will compute the type_name in the same lang for all the invoices and it might cause problems if invoices have to be sent in different languages (at once).

**Comment by nle-odoo** [comment]
> AFAICS, you want to do the translation of the model_description with the current user (and not the SUPERUSER one).

Checking the other invoice sending, the lang should be (if possible) from the used mail.template, otherwise from get_lang.

Checking it in the code for sending invoice:

https://github.com/odoo/odoo/blob/f242cad9a27fb0e58e1b9c726573b316534f6be8/addons/account/models/account_move.py#L3266-L3270
https://github.com/odoo/odoo/blob/f242cad9a27fb0e58e1b9c726573b316534f6be8/addons/account/models/account_move.py#L3284

I think we could get the right lang with:

```
lang = default_template._render_lang(invoice.ids)[invoice.id] or get_lang(self.env).code
```

**Comment by Mtaylorr** [comment]
@nle-odoo  so do I change it to include the lang here ?

**Comment by nle-odoo** [comment]
yes, to match what we do in account.move().action_invoice_sent

**Comment by Mtaylorr** [comment]
In our section of code , default_template is a string so it doesn't have _render_lang method , should I just use get_lang ?

**Comment by Mtaylorr** [comment]
@nle-odoo  I matched `account.move().action_invoice_sent` but I only used get_lang since the `default_template` in this function is a string and not a template object.

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
