### PR TITLE
[15.0][FIX] hr_expense: Apply rule to account moves to prevent Expense Team Approver user can access to all moves

### PR DESCRIPTION
**Pull request by victoralmau**
Related to https://github.com/odoo/odoo/commit/b6fc5ef468f47c109b2d007f211e02ca5f3fe093

Apply rule to account moves to prevent Expense Team Approver user can access to all moves

**Description of the issue/feature this PR addresses**:
User with Expenses: Team Approver group should not see all moves.

**Example use case**:
- Create a user with Expenses: Team Approver group.
- Login with the created user to /my
- The user will only see invoices linked to expenses.

**Current behavior before PR**:
User with Expenses: Team Approver group will **only** be able to see invoices linked to expenses.

Ping @pedrobaeza 

@Tecnativa TT48242

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by victoralmau** [comment]
Is it necessary to add a test to check this behavior?

**Review by dbkosky — COMMENTED** [review]
@victoralmau 
Hello! Thanks for the submission.

I'm just trying to replicate the issue that the PR solves and I'm having trouble doing so. 

In principle I agree with what you're adding, but can you describe a case whereby an `expense_team_approver` user can access invoices that they shouldn't be seeing?

**Comment by victoralmau** [comment]
Example use case (created in runbot 15.0).
- Create an internal user only with Expenses: Team Approver permission.
- In a new window, access with that user to **/my**

example

User can see all invoices.

Do you want to add a test?

**Review by dbkosky — COMMENTED** [review]
So after doing a bit more digging, I've come to suspect that there is no situation in which the `expense_team_approver` should get to see an invoice (even those linked to the invoices for expenses that they've approved), unless they have accounting access rights. I've spoken to the PO for hr_expense, and she agrees.

However this being stable, we prefer not to delete existing access rules, so adding this extra rule is actually a very good idea in my opinion. Nice catch!

Can we adapt the commit message to something like:
```
[FIX] hr_expense: restrict account move domain for Expense Team Approver

There is a ir.model.access rule that allows `hr_expense_team_approver`
group members to read account moves and account move lines. Another
existing rule forces the domain to only read account move lines that
have an associated expense_id. This rule however is not repeated for
account moves, and thus an `hr_expense_team_approver` group user is able
to access unrelated Customer Invoices / Vendor Bills on the portal at
`/my`.

To fix this, this commit adds a rule to prevent the
hr_expense_team_approver from reading any move that does not have at
least one line with an associated expense_id.
```

**Comment by dbkosky** [comment]
@victoralmau Thanks for adapting the commit message. Please could you fetch from `15.0`, rebase on it, and push again? It's just so that the `ci/runbot` test passes.

**Comment by victoralmau** [comment]
> @victoralmau Thanks for adapting the commit message. Please could you fetch from `15.0`, rebase on it, and push again? It's just so that the `ci/runbot` test passes.

Done!

**Review by JulienAlardot — APPROVED** [review]
@FlorianGilbert

**Review by FlorianGilbert — APPROVED** [review]
Thanks to all of you 
@robodoo r+

**Pull request closed without merging**
