### PR TITLE
[FIX] l10n_cl: fixed wrong domain getting document types 

### PR DESCRIPTION
**Pull request by suv-bmya**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@suv-bmya Can you target 13.0?  (saas-12.5 does not exist anymore)

**Comment by suv-bmya** [comment]
Done!

**Comment by jco-odoo** [comment]
Could you also change the commit message to [FIX] l10n_cl: fixed wrong domain...  ?  (I know these are details)

**Comment by suv-bmya** [comment]
@jco-odoo , done!

**Comment by jco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
