### PR TITLE
[DOC] Little clarification

### PR DESCRIPTION
**Pull request by blaggacao**
I PR this as I'm not even sure about, but I hope you will tell us ...

### CODE REVIEW

**Comment by blaggacao** [comment]
@odony Sorry for bothering you that much lately... (I havn't had the chance to come to an Odoo Experience, yet :disappointed: ) --- Is there any special reasons why the connection pool could not be shared across workers? pgbouncer is nice and all, but 1. it's an extra point of failure and 2. not sharing those resources seems just giving them away lightheartedly.

Without real pain (or at least I don't see it in my naive point of view) the connection number grows linearly but steeply with the number of workers forcing to use bgbouncer, where it's probably just an unnecessary extra layer of code...

@yelizariev I know you are interested  :smile: le:

**Comment by Yenthe666** [comment]
@blaggacao I think this wiki page will help you a lot: https://github.com/odoo/odoo/wiki/BugManagement#issues
It tells you for which subject who you should - or better said, can - ping. As you can see there documentation is for (@)mart-e 😉

**Comment by blaggacao** [comment]
@Yenthe666 Wow, thank you! TI didn't know. It will help me quite some.

However, it's not only documentation, but documenting the actual behavior I'm also asking a question about the implementation details and weather there could be a better way... So this would be, then (according to the list): @rco-odoo

**Comment by mart-e** [comment]
This one is not really doc but more deployment information. @nseinlet will probably be able to tell us about this :)

**Comment by nseinlet** [comment]
It's a per-worker limit when using workers.
Easier to explain here https://github.com/odoo/odoo/blob/11.0/doc/reference/cmdline.rst#database with way more space to do so.

**Comment by blaggacao** [comment]
@nseinlet I have come to realize that this limit, being per worker, effectively means that we are giving away the possibility of re-using database connection effectively across the server. There is such an elegant code to db-recycling in the `sql_db.py` but in a multi-worker setup with sufficient workers it's usefulness becomes very limited.
This forces the DevOp to introduce a connection pooler as another infrastructure component (which is to maintain and represents a SPOF).
I have read across serverfault and others, that a "sane" application is considered to gracefully manage it's own database connection avoiding the need of a middleware of some kind.
This argument seems pretty obvious to me and I would ask, wouldn't it possible to move towards a shared connection pool across the main process?
Are there any hard arguments against such a design?

**Pull request closed without merging**
