### PR TITLE
[FIX] delivery: assure stock user can validate pickings

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

Steps to reproduce (tested in v14, but I suppose also happens in v13 because the code is the same):
- Delivery module is installed.
- User_1 is stock_manager and sale_manager.
- User_1 creates sale_order and confirms it. Automatically is created a picking P.
- User_2 is stock user/manager but doesn't have sale rights.
- User_2 open picking P and validates it.
 => Error: cannot validate due to access rules.
Selection_417

The problem is due because at some point, it tries to read the linked sale order.

See the debug process:

- at the end of button_validate() of stock.picking (module stock):
Selection_418
-at the end of _action_done() of stock.picking (module stock):
Selection_419
- in _send_confirmation_email() method of stock.picking (module delivery):
Selection_420
- in send_to_shipper() of stock.picking (module delivery):
Selection_421
- in _compute_amount_total_without_delivery() of sale.order (module delivery):
Selection_422
It's in that place, when doing `self.order_line`, that a read access error is produced.

**Current behavior before PR:** Stock user without sale rights cannot validate a picking coming from a sale order.

**Desired behavior after PR is merged:** Stock user without sale rights can validate a picking coming from a sale order.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
ping: @rim-odoo @simongoffin @Whenrow @amoyaux

**Comment by MiquelRForgeFlow** [comment]
@amoyaux Sorry if I didn't give all the conditional details for the case, but I tried. By the way, I think there is a little confusion seeing your answer. One think are the ACL and other thing are the ir.rules. The error I got is for the rule and you can see in the image above. And the check of the ACL (`check_access_rights`) and the check for the rules (`check_access_rule`) are two distinct checks :S

Could you please check again, please?

**Comment by amoyaux** [comment]
"User_2 is stock user/manager but doesn't have sale rights." I tested it that way and not with sale document only

Please complete the usecase with all the conditional details. I tested and got the issue. I'm ok with the PR.

**Comment by MiquelRForgeFlow** [comment]
Commit edited :)

**Comment by amoyaux** [comment]
robodoo r+
Thanks

**Pull request closed without merging**
