### PR TITLE
[FIX] stock: document print problem

### PR DESCRIPTION
**Pull request by mamatch**
Steps:
- Set the language to Catalan
- Go to inventory -> operations -> Transfers
- Try to print a picking operation or a delivery slip, you get an error

solution:
Just a bad translation of expression to evaluate when trying to generate template

opw-2951985

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
Usually we should not update .po, but here it is necessary since catalan is not available yet in 15.2 on transifex.

So change looks good to me, but I think we should rather copy the 15.0 translations ( where there was the same issue but fixed on transifex). For first string: 

https://www.transifex.com/odoo/odoo-15/translate/#ca/stock/333330548
> 'Albarà d'entrega  - %s - %s' % (object.partner_id.name or '', object.name)

For second string:

https://www.transifex.com/odoo/odoo-15/translate/#ca/stock/333330037
> 'Albarà d'operacions - %s - %s' % (object.partner_id.name or '', object.name)

**Comment by mamatch** [comment]
@nle-odoo need approbation please

**Review by nle-odoo — APPROVED** [review]
robodoo r+

**Comment by nle-odoo** [comment]
robodoo r+

**Comment by nle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
