### PR TITLE
[FIX] l10n_fr: add migration to version 2.1 of the module

### PR DESCRIPTION
**Pull request by clbr-odoo**
This will allow to get the latest taxes updated.

Task: 3111528.
Related: #84918, #107158

### CODE REVIEW

**Review by Pirols — APPROVED** [review]
lgtm

**Comment by william-andre** [comment]
Can you add in your commit message the commit that changed the taxes?

**Comment by clbr-odoo** [comment]
@william-andre Done :+1:

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
