### PR TITLE
[MERGE][REF] various: rename columns "type" to be more business oriented

### PR DESCRIPTION
**Pull request by mart-e**
Purpose of this commit is to rename type column to something matching the
the real business use of the field. That way it is easier to find and grep
in the code. It also lessens potential conflicts with type build-in python
function. It also lessens conflicts when using the field in JS as type
is a build-in attribute.

Renaming type column is a long-living issue. We choose to do it at the
beginning of the v13 development to catch errors as soon as possible.

This commit is linked to task ID 1896245. It is also a subpart of community
PR #27599.

### CODE REVIEW

**Comment by mart-e** [comment]
@mreficent I have cherry picked some of your commits we can already merge with @tde-banana-odoo review. The other should be checked with the appropriate teams.

**Comment by mreficent** [comment]
Ok, I understand, you picked just the easier ones hehe also, it's logic to do it by step by step, no problem.

Whenever you merge this PR, then I will update mine 😉

**Comment by mart-e** [comment]
>  you picked just the easier ones hehe also

I picked the general ones or only impacting the apps of @tde-banana-odoo.
I will try to encourage each app-responsible to take the part impacting his modules but I don't want to force one to merge this (as it will impact all its devs)

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
You are cassing my noix dear @robodoo  .

**Pull request closed without merging**
