### PR TITLE
Master website site tde

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Task: https://www.odoo.com/web#id=30850&view_type=form&model=project.task&action=333&active_id=965&menu_id=4720

Purpose: Customer portal will be available for sale, account and project modules. Payment will be available if payment acquirers are installed. Having website installed still offers interesting opportunities: customization, header / footer customization, custom pages, front page for your enterprise, ... website module will be used for customization independently of having access to a customer portal. eCommerce and Online Quote will still depend on website as those are advanced website feature.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Interesting work you are doing here! I suppose this means that you don't need anymore website for having a customer portal and that you will remove the portal_* modules, isn't it?

**Comment by tde-banana-odoo** [comment]
Hello,

Exactly. Customer portal will be available for sale, account and project modules. Payment will be available if payment acquirers are installed. Having website installed still offers interesting opportunities: customization, header / footer customization, custom pages, front page for your enterprise, ... website module will be used for customization independently of having access to a customer portal. eCommerce and Online Quote will still depend on website as those are advanced website feature.

**Comment by pedrobaeza** [comment]
Cool! I'll review it when you'll change label RD or when you consider that is out of beta.

**Comment by tde-banana-odoo** [comment]
Hello,

Actually it seems to be a working WIP. I tried to make the minimal diff to have a working website feature with language support without website module installed. You can test and/or comment if you want, except last commits (moving website_portal_sale to sale and sale_payment which is still under development-.

**Comment by pedrobaeza** [comment]
I'll review it then and tell you back.

**Comment by pedrobaeza** [comment]
I have tried to test the PR, with the following steps:

1. Uninstall all website.
2. Enable sign up.
3. Sign up creating one user.
4. Login with the new created user.
5. I find this error "Only employee can access this database. Please contact the administrator."

Putting the user in the "Employee" group, I'm able to login, but accessing the backend. Forcing the URL with `<host>/my` I see now the portal, but only accessing sales orders, without invoices, nor project issues, and so on. I suppose that is planned to be done later.

**Comment by tde-banana-odoo** [comment]
Indeed. I will try to figure out that soon :) .

**Comment by tde-banana-odoo** [comment]
Ping @KangOl

**Comment by tde-banana-odoo** [comment]
Ping @xmo-odoo

**Pull request merged**
