### PR TITLE
[CLA] *: Add latus GmbH CLA

### PR DESCRIPTION
**Pull request by jmutsaerts**
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by jmutsaerts** [comment]
@mart-e would you mind checking again, why this one does not progress into 17.0 ? thanks!

**Comment by mart-e** [comment]
Ok let’s try again after a rebase :crossed_fingers: 
@robodoo r+

**Comment by jmutsaerts** [comment]
@mart-e thank you! To me it seems like ci/minimal was not succesful. Thanks again for having a look. Cheers

**Comment by mart-e** [comment]
@jmutsaerts oh I see, it was strangely considered as a master branch. Should be good now.

**Pull request closed without merging**
