### PR TITLE
[IMP] mail: add field for reply-to feature

### PR DESCRIPTION
**Pull request by seb-odoo**
Add the field in the freeze for next version, the interface is not fully ready
to merge yet but it will be added in https://github.com/odoo/odoo/pull/75849

Part of task-2362251

### CODE REVIEW

**Comment by seb-odoo** [comment]
@tde-banana-odoo I assume you would want a say in this?

**Comment by tde-banana-odoo** [comment]
Yeah, we don't want it indeed.

**Comment by seb-odoo** [comment]
Thank you for the answer, but it doesn't really help. What is the issue? What is the alternative?

Make a separate table for handling reply relations with both message ids on it?

**Comment by tde-banana-odoo** [comment]
Hello,

Indeed it was a short answer to be sure you don't merge it too soon, was just browsing my notifications :D . In short: we already have parent_id field. Previously (v7 until v... ? 9 ?) it was holding the "answered to", allowing to make real threads inside documents. Since v10 (?) Fabien asked to remove thread management and now parent_id is generally "first message posted on document", except some specific models, notably mail.channel (tadaaaa).

I think you could therefore think of using parent_id, and maybe explore if there are things to change in the way it is currently implemented. But normally it should do the trick. Example: previously to the split we had mailing lists based on mail.channel displayed on frontend and threading was working (messages replying to other messages with more than one level).

Cheers,

**Comment by seb-odoo** [comment]
Closed as we used `parent_id` for now.

**Pull request closed without merging**
