### PR TITLE
rewrite description for l10n_cn 

### PR DESCRIPTION
**Pull request by jeffery9**
Description of the issue/feature this PR addresses:

rewrite description for l10n_cn to avoid confusion, as this module is the base for the another two modules which is the actully addons for chart of account

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jeffery9** [comment]
@mart-e  this improvement should been merge into master.

**Comment by Yenthe666** [comment]
@jeffery9 why don't you make a PR against the master then? 😉

**Comment by jeffery9** [comment]
ok, I should create another one too.

**Comment by mart-e** [comment]
Hello,

Could you specify the title and description in English and Chinese ? This way it is understandable for non-Chinese speakers.
Do not create another one, we will move it when merging

**Pull request closed without merging**
