### PR TITLE
Move img and fonts folders

### PR DESCRIPTION
**Pull request by SimonGenin**
Entreprise: https://github.com/odoo/enterprise/pull/17855

For the new web client, we are moving folders for a better architecture. It seemed better to make the change of the img and fonts in master first to ease the transition and avoid a possible big rebase. 

Also remove unused images

### CODE REVIEW

**Comment by SimonGenin** [comment]
@odoo/rd-security Could one of you pass the security check ? (https://runbot.odoo.com/runbot/batch/571380) 
I actually didn't change anything touchy, I just changed a couple path in a method triggering the check.

**Comment by SimonGenin** [comment]
@aab-odoo Check if everything is ok for you.

**Comment by ged-odoo** [comment]
rd-security, no need to validate this PR yet, we need to remove first some images

**Comment by Yenthe666** [comment]
so
- `/static/src/img` would become `/static/img`?
- `static/src/fonts` would become `/static/fonts?`

**Comment by ged-odoo** [comment]
@Yenthe666 yes. (well, only the static images and fonts for `web`), very few of which are in use

**Comment by ged-odoo** [comment]
looks good to me

**Comment by SimonGenin** [comment]
@odoo/rd-security You can check, it is ready for merge

**Comment by ged-odoo** [comment]
@odoo/rd-security Hello guys! Could one of you override the security check for this PR? thank you

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by KangOl** [comment]
Missing upgrade script to update custom views

**Comment by antonylesuisse** [comment]
We reviews the moved image and none of the are in them can be inserted in ir.ui.view. Image concerned:

Logo:

/img/favicon.ico
/img/logo.png
/img/logo2.png
/img/logo_inverse_white_206px.png
/img/odoo_logo_tiny.png
/img/nologo.png

Placeholders:

/img/transparent.png
/img/spin.png
/img/sep-a.gif
/img/placeholder.png
/img/empty_folder.svg
/img/user_placeholder.jpg

Backend:

/img/graph_background.png
/img/user_menu_avatar.png
/img/form_sheetbg.png
/img/enterprise_upgrade.jpg
/img/smile.svg
/img/smiling_face.svg
/img/neutral_face.svg

Mimetypes:

/img/mimetypes/addresses.svg
/img/mimetypes/archive.svg
/img/mimetypes/audio.svg
/img/mimetypes/binary.svg
/img/mimetypes/calendar.svg
/img/mimetypes/certificate.svg
/img/mimetypes/disk.svg
/img/mimetypes/document.svg
/img/mimetypes/font.svg
/img/mimetypes/image.svg
/img/mimetypes/javascript.svg
/img/mimetypes/pdf.svg
/img/mimetypes/presentation.svg
/img/mimetypes/print.svg
/img/mimetypes/script.svg
/img/mimetypes/spreadsheet.svg
/img/mimetypes/text.svg
/img/mimetypes/unknown.svg
/img/mimetypes/vector.svg
/img/mimetypes/video.svg
/img/mimetypes/web_code.svg
/img/mimetypes/web_style.svg

**Comment by KangOl** [comment]
> We reviews the moved image and none of the are in them can be inserted in ir.ui.view. Image concerned:


Why can't they? Never underestimate what users can do.

**Comment by antonylesuisse** [comment]
@KangOl I mean that there is no ui to do it. Except with the html editor / ir.ui.view form or in the database.

**Comment by odony** [comment]
@robodoo override=ci/security
Rationale: the path manipulations in `odoo/addons/web/controllers/main.py` have been rewritten to use the safer form introduced more recently.

**Comment by odony** [comment]
@robodoo rebase-ff

**Comment by SimonGenin** [comment]
By the way, there's the enterprise PR https://github.com/odoo/enterprise/pull/17855 
I don't remember if it needs to be R+ as well for the mergebot to proceed
@ged-odoo @antonylesuisse

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
