### PR TITLE
[IMP] l10n_cr: switch account templates to csv from xml

### PR DESCRIPTION
**Pull request by hch-odoo**
task: https://www.odoo.com/web?debug#id=1909961&action=327&model=project.task&view_type=form&menu_id=4720

pad: https://pad.odoo.com/p/r.3bb795404d1e38ccc7cde9c4f6f3c9cd

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@hch-odoo are you guys sure you want to do this in the stable version? Shouldn't these kind of changes go to master? Improvements = master, fixes = stable
CC @jco-odoo @oco-odoo

**Comment by jco-odoo** [comment]
Has to do with perf (import in batch) and it won't break anything.

**Comment by tivisse** [comment]
@robodo r+

**Comment by tivisse** [comment]
@robodoo r+

**Pull request closed without merging**
