### PR TITLE
[FIX] product: cost alignment in product form is improper

### PR DESCRIPTION
**Pull request by smo-odoo**
Task : https://www.odoo.com/web?#id=2025782&action=327&model=project.task&view_type=form&menu_id=4720

Pad : https://pad.odoo.com/p/r.2ba30ac34c453e165848586c52c1fba3

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by sle-odoo** [comment]
robodoo r-

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by sle-odoo** [comment]
robodoo retry

**Comment by rdeodoo** [comment]
Dev branch is red, stuck in r+ till green, probably 'false positive', see [here](http://runbot.odoo.com/runbot/build/548996)

**Comment by sle-odoo** [comment]
@rdeodoo thanks
@smo-odoo please retarget to master and rebase

**Pull request closed without merging**
