### PR TITLE
[IMP] sale: split populate for usage in sale_subscription

### PR DESCRIPTION
**Pull request by fdamhaut**
This commit split the function confirming SO in populate with
the purpose of adding populate method for subscription SO,
recurrent product, recurrence and pricing in https://github.com/odoo/enterprise/pull/33305

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Feyensv** [comment]
I didn't know `sale_subscription` existed in odoo/odoo :eyes:
(please adapt your commit to match & explain your changes in community :P)

**Comment by fdamhaut** [comment]
> I didn't know `sale_subscription` existed in odoo/odoo eyes (please adapt your commit to match & explain your changes in community pray)

Ooops will do :D It's still in the dev process so I'll do that later but keeping it in mind TY

**Review by leonardopavanrocha — COMMENTED** [review]
Just one comment. Thanks for your work :)

**Review by arj-odoo — APPROVED** [review]

**Review by Feyensv — APPROVED** [review]

**Comment by arj-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
