### PR TITLE
[FIX] mrp: fix gantt unavailability

### PR DESCRIPTION
**Pull request by ryv-odoo**
_get_unavailability_intervals didn't return the correct
dict (describe in the docstring). Then the override in
maintenance module was wrong.

### CODE REVIEW

**Comment by ryv-odoo** [comment]
@sle-odoo My beautiful fix

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by sle-odoo** [comment]
robodoo retry

**Comment by sle-odoo** [comment]
robodoo retry

**Pull request closed without merging**
