### PR TITLE
[IMP] website_sale: reorganize python files

### PR DESCRIPTION
**Pull request by Feyensv**
Split and reorder a bit website_sale python files before future work in this module :)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff override=ci/security
Reason: False positive: Just splitting files with code triggering security alerts

cc @mart-e

**Comment by tivisse** [comment]
@robodoo r+ rebase-ff override=ci/security

**Comment by Feyensv** [comment]
robodoo retry

**Comment by Xavier-Do** [comment]
@robodoo retry

**Pull request closed without merging**
