### PR TITLE
[FIX] l10n_cl: missing translation and fields

### PR DESCRIPTION
**Pull request by jpp-odoo**
[FIX] l10n_cl: missing invoice date on report

Before this commit, the invoice date wasn't shown on the invoice report.

opw-2424608

------------------------------------------------------

[FIX] l10n_cl: missing translation for the invoice report

opw-2424608

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
The code change should give the same result.

I'm not sure why the current code is not working since report_name is already the invoice date:

https://github.com/odoo/odoo/blob/2891f9e24f10f42fd997e2f42aee80a53bc6acaa/addons/l10n_cl/views/report_invoice.xml#L5-L7

For translation it looks alright, I think manual change in .po files are deleted every sunday so it doesn't seem useful to have it.

robodoo delegate+

**Comment by jpp-odoo** [comment]
@robodoo r+

**Comment by nle-odoo** [comment]
As a side note, after discussion:

> For translation it looks alright, I think manual change in .po files are deleted every sunday so it doesn't seem useful to have it.

I did not notice, but it is i18n not l10n so changing the .po file make sense.

> I'm not sure why the current code is not working since report_name is already the invoice date:

t-call of informations is t-called before custom_header, so this is why this doesn't work

**Comment by nle-odoo** [comment]
robodoo rebase-ff

**Pull request closed without merging**
