### PR TITLE
[WIP] import wizard UX improvements

### PR DESCRIPTION
**Pull request by xmo-odoo**
Task 2059448:

* batch imports to avoid timeouts on big imports / expensive objects
* this means imports are not necessarily *atomic* anymore
  - add warning about that
  - add UI to resume an ongoing import (after fixing the file)
* add debug UI to skip rows & configure batch size (default: 2000 rows)

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@robodoo rebase-ff r+

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
robodoo r+

**Comment by Yenthe666** [comment]
@xmo-odoo why was the option to configure batching introduced to be available only for users that have debug mode disabled (through `oe_import_debug_option`)? I don't really get why it was limited to debug mode? Is there some specific reason?
I've had multiple customers ask to have this available by default so I'm curious if I'm not missing a good reason why this was done.

P.S: Sorry for the hijack here.

**Comment by xmo-odoo** [comment]
@Yenthe666 UI complexity, which was considered unnecessary by default, and a misuse risk.

**Pull request closed without merging**
