### PR TITLE
Fix typo on shell command; some style improvements

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by antonylesuisse** [comment]
Please dont waste your time on PR about style improvement as we will refuse them, it bloats the blame and the history, anyway time is more wisely spent on real bugs

FYI about the style 
- we are targeting python27 i dont want to see import from future unless absolutly necessary
- likewise limit needed dependencies to a minimum (except importerror is ok for optional libs)
- we allow 99 char per line
- no need to import from when a symbol is used only a few time

**Comment by dreispt** [comment]
OK. But please take note on the [typo](https://github.com/dreispt/odoo/commit/b5e22a61f4150831372ee536ece954aec59f4c46).

Since we're at it: do you have any stance on PEP8 you could share?

**Comment by antonylesuisse** [comment]
We try to follow PEP8 on new code or when we refactor but we wont change code for the sake of style only.

I will ask @xmo-odoo to add coding style section to the official documentation here https://www.odoo.com/documentation/8.0/reference.html it will be PEP8 (maybe relaxed about a few items) + more policy specific to odoo.

I will let the odoo developers voice their opinion and choose their policy as my opinion doesn't always reflect those of the team and i'm probably wrong about many style choice :) I'm only sure about dependencies they should stay minimal and be available in debian stable.

Documentation is now a priority and @xmo-odoo has been working full time on it for the last month.

**Comment by tde-banana-odoo** [comment]
Hello,

I fixed the typo, thanks for pointing it out (see commit 6d54b0690746ebfca9452f51c8525029c0761440). For the guidelines, we will create a section in the doc and work on it to be sure our guidelines are clear enough.

Thanks !

**Comment by bealdav** [comment]
@antonylesuisse, It's good to know you will go towards ~ PEP8. Thank you
Please consider 79 limit chars, not for the rule itself, but it's just a convenient way to display 2 scripts in the same screen. Very useful. 99 chars are too large for mostly screens

**Comment by tde-banana-odoo** [comment]
Honestly, I agree on most PEP8 guidelines, but not the 80 characters limit; I can already tell you it won't be a rule we will enforce. I personally advise people to use rulers at 80, 100 and 120 characters and see how their code fit in those rulers.

**Comment by bealdav** [comment]
thanks @tde-banana-odoo, but don't you need to display 2 scripts in the same time on your screen ? How to do with 99 chars ?

**Comment by bealdav** [comment]
@tde-banana-odoo @antonylesuisse 
As you can see github does not support correctly more than 79 chars
123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 
and we can't change github

seem to a good post on this matter
https://wrongsideofmemphis.wordpress.com/2013/03/25/80-chars-per-line-is-great/

**Comment by antonylesuisse** [comment]
See #4596 first we will make a proposition then we will welcome input from everyone.

My first computer had a 32 wide char screen, side by side diff is probably not recommended on that hardware. Happy new year, we live in 2015 on a standard 1080p screen using the 16x8 vga rom font you get 238 colums. My screen here is 3200x1800. Git hub diff viewer has a lot of limitation, and totally fails on large diff, i personnaly use git qdiff https://github.com/amigrave/git-qdiff i miss qbzr, all graphical git interfaces sucks, and i tested all of them.

**Comment by bealdav** [comment]
Happy new year to you @antonylesuisse, then.
I hope all your wishes will happen and you'll have a yet larger screen for next christmas  ;-)

**Pull request closed without merging**
