### PR TITLE
[FIX] parent store honour _parent_order

### PR DESCRIPTION
**Pull request by StefanRijnhart**
On a model with _parent_store = True and a _parent_order, the order is not updated when expected upon a change in the values of one of the fields in the _parent_order definition.

For instance, in product categories, create categories 'B' and 'A' in that order under the same parent. You will find that 'A' comes before 'B' in the list view. Then (with language set to en_US), change the name of 'A' to 'Z'. The order remains the same ('Z', 'B') and is now incorrect.

This change attempts to fix this by triggering a recompute of the affected nodes.

### CODE REVIEW

**Comment by clonedagain** [comment]
@lbellier maybe you'll want to test this, to fix the display ordre of the stock locations

**Comment by StefanRijnhart** [comment]
@clonedagain To be completely clear about this, this one does not deal with sorting order by translated terms if that is what you were hoping. I believe this was fixed in 9.0 in most cases but for models with parent store it is hard to solve because the sorting order is stored globally in the parent store columns.

**Comment by StefanRijnhart** [comment]
For the Odoo developers: on a database with a lot of product categories, the log regularly shows a serialization failure during the first couple of tries because of concurrent access. Is there anything I can do to prevent this from happening?

**Comment by antonylesuisse** [comment]
@rco-odoo but we need to discuss this first. @odony

**Comment by tivisse** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards

**Pull request closed without merging**
