### PR TITLE
Saas 12.5 l10n generic coa al

### PR DESCRIPTION
**Pull request by antonylesuisse**
Renamed xml ids of the main accounts (in prepartion for a future multi l10n demo system). Change account numbering to match quickbook and other US GAAP convention and recommendations.

### CODE REVIEW

**Comment by antonylesuisse** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@oco-odoo pingx2

**Comment by oco-odoo** [comment]
@antonylesuisse You force-pushed on my fix :p

**Comment by oco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
