### PR TITLE
[FIX] analytic: display correct analytic when using arrows

### PR DESCRIPTION
**Pull request by yosa-odoo**
Steps to reproduce:
- activate analytic
- Create two assets with different analytic distribution
- Open the first asset
- Navigate to the second asset via the arrow

Issue:
The analytic account will not be displayed correctly

Cause:
In `jsonToData` the record used is the previous one.

Solution:
Use the record that will efectively be displayed

opw-3698383

### CODE REVIEW

**Review by gawa-odoo — COMMENTED** [review]
Hello!
I will have to ask @h4818 for his opinion.
It does fix this particular issue, but I'm not sure that's the right way.

What I also noticed here, is that if you define a plan to be mandatory based on Miscellaneous and account's prefix 60000 (for example), if you create 2 assets, one with the account 600000 and the other with account 610000 for example, then, you open the form view of the asset 2, you see both plans (expected), then switch to the first one with the arrow, you will still see both plans which you shouldn't (so `fetchAllPlans` and `fetchPlansArgs` are also concerned atleast, I suppose)

**Comment by h4818** [comment]
@yosa-odoo the fix is good, but as @gawa-odoo pointed out, the new record should be used in `fetchAllPlans` and `fetchPlanArgs`...
it was done this way before the relationalModel change https://github.com/odoo/odoo/commit/218ad8456a06503dd508e7216edcffdc90b35cac

good catch @gawa-odoo!

**Review by gawa-odoo — APPROVED** [review]
LGTM
(not sure about the arguments of the methods we prefer, but it seems to work indeed)
@h4818

**Review by h4818 — COMMENTED** [review]
Small thing

**Comment by yosa-odoo** [comment]
Top, thanks to you two !

**Comment by h4818** [comment]
@robodoo r+

**Pull request closed without merging**
