### PR TITLE
Updated requirements.txt

### PR DESCRIPTION
**Pull request by danielhasan1**
Description of the issue/feature this PR addresses:
ModuleNotFound error was showing while installing any module
Current behavior before PR:
ModuleNotFound stdnum.
Desired behavior after PR is merged:
No issues.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@smetl `python-stdnum` was a non mandatory dependency, with fallbacks in `base_vat`.
However, I see it that it is now expected in account.
Should we add it in the requirements or add the needed fallbacks in account (it is only used once).

@danielhasan1 Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `31930248+danielhasan1@users.noreply.github.com`
- you are signing _for_ the address `d...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

**Comment by smetl** [comment]
@mart-e @william-andre I think we can add this dependency in the requirements because we use it to compute the European structured communication.

**Comment by mart-e** [comment]
If I am not mistaken, we only use it for this small `calc_check_digits` method in account.

https://github.com/arthurdejong/python-stdnum/blob/831c66990ab8fb3040e5b7fc74668836a1d4ef64/stdnum/iso7064/mod_97_10.py#L54-L57

This mean, we could simply extract this method and we don't need `stdnum` anymore (except for `base_vat` but there is the right checks there).

**Comment by smetl** [comment]
@mart-e Indeed. I let you decide the way you think the best: adding the dependency or copy-pasting the method.

**Comment by mart-e** [comment]
Fixed at  #40253

**Comment by danielhasan1** [comment]
@mart-e Hello,
could you please tell me what's the correct way for signing odoo cla? I saw the last commit and it's formatted as this - 
`India, 2019-11-08

I hereby agree to the terms of the Odoo Individual Contributor License Agreement v1.0.

I declare that I am authorized and able to make this agreement and sign this declaration.

Signed,

Niyas Raphy niyasraphyk@gmail.com https://github.com/niyasraphy`
I have also used the correct email and GitHub account.
Thanks,

**Comment by mart-e** [comment]
@danielhasan1 the commits made to sign the CLA must match the email inside the CLA file.
You can check the commits content by adding `.patch` at the end of the URL of your PR (e.g. https://github.com/odoo/odoo/pull/40067.patch).
As you can see on your PR, you are not using your email, this is probably because you have marked your email as private.

**Pull request closed without merging**
