### PR TITLE
[FIX] Fixing issue #5233

### PR DESCRIPTION
**Pull request by hbto**

### CODE REVIEW

**Comment by hbto** [comment]
This is the expected result

https://docs.google.com/a/vauxoo.com/file/d/0B1w9gokcJL9hdXhnUWFkeDJTNGc/edit?usp=drivesdk

**Comment by hbto** [comment]
This PR fixes #5233

**Comment by antonylesuisse** [comment]
Please dont open an issue and a PR, only open a PR and explain the problem and give the patch

**Comment by scigghia** [comment]
:+1:

**Comment by antonylesuisse** [comment]
I close this PR the referenced issue has been closed and 'No description provided.'

**Comment by nhomar** [comment]
@hbto is this PR ready to check, can you reopenit following guidelines please in order to validate if it is necesary yet.

Thanks.

**Comment by hbto** [comment]
@nhomar could you ask @yaniaular one module of her was the one needing this patch.

Best Regards.

**Pull request closed without merging**
