### PR TITLE
[MERGE] mail: several discuss/chatter fixes

### LINKED ISSUE #37994: [13.0] Tracbak on 'Unstar all' on Discuss screen
Impacted versions: 13.0

Steps to reproduce:
Screenshot (4)

Current behavior: 
Screenshot (5)

Expected behavior: Button should be Invisible (When no starred messages) / No traceback

Video/Screenshot link (optional):

### LINKED ISSUE #38003: [13.0] No option to removing Attachment after adding.
Impacted versions:
odoo 13
**Current behaviour:**
1) By Mistake Added wrong  attachment no option to remove.
Selection_026

**Expected behaviour:**
1) There need such option to remove attachment.
Selection_025

**Video/Screenshot link (optional):**
Attach

### PR DESCRIPTION
**Pull request by alexkuhn**
[FIX] mail: deletable attachments in attachment box
Task-Id 2081987
closes #38003

[FIX] mail: discuss unstar all
closes #37994

### CODE REVIEW

**Comment by Feyensv** [comment]
:+1: Thanks (should have pinged you after investigation as I just found it was an easy fix :man_facepalming: )

**Comment by alexkuhn** [comment]
@len-odoo

**Comment by alexkuhn** [comment]
The issue was already there with `editable`, and this parameter is misleading because this doesn't really mean whether attachment is editable or not (this param makes only sense with composer), so it's a non-issue for this PR.

The solution of 12.0 that uses `isNotEditable` helps keeping original behaviour when `undefined` (falsy), but at the same time this is not intuitive to reason with the negation.

Ideally, the param should be called `isEditable` and the default value should be `true`.
We need to define that in JS, but attachment qweb template is not linked to a widget, hence the problem of relying on `undefined` and `t-set`...

That's why I'm good with both solutions, but I tend to prefer this on in 13.0 because it forces us to document when we need `isEditable`. With OWL, we will know that the component `AttachmentPreview` should have `isEditable` as props.

**Comment by alexkuhn** [comment]
@robodoo r+ rebase-ff

**Comment by alexkuhn** [comment]
@robodoo retry

**Pull request closed without merging**
