### PR TITLE
**Austrian country states are missing so far**

### PR DESCRIPTION
**Pull request by nikiwaibel**
Impacted versions:

 - 11.0 12.0 13.0 14.0/master

Steps to reproduce:

 1. add a new contact
 2. select 'Austria' in Address/Country
 3. choose State

Current behavior before PR:

 - no predefined states appear

Desired behavior after PR is merged:

 - list all 9 Austrian states

Description of the issue/feature this PR addresses:

States are missing for country Austria. This PR adds the 9 states to odoo/addons/base/data/res.country.state.csv.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
Hi @nikiwaibel 
Great to have some new contributors from Austria here. No idea what the current state is, but it was not accepted several times (my last try in master https://github.com/odoo/odoo/pull/13069) and as the state name field is translatable the names should be in English and translated later.

But to be sure I'll ping @mart-e 
Any update on this? Still the same rules in place?

**Comment by mart-e** [comment]
H
i,
The idea is to add the states in base only if the state is required in the address format. For instance, it is required in USA but not in Belgium. If Austria is like the second, it's better to add it in the chart of account only.

**Comment by wtaferner** [comment]
@mart-e 
So, you would currently accept it for l10n_at? As I did a big refactoring in 13.0, I think this could go easily there to have the complete picture, right? Let me know and I will provide you with a PR :wink:

**Comment by nikiwaibel** [comment]
i am new here, so i don't want to throw any flames. anyway my opinions:
* in case res_country:address_format includes state_code or state_name, then those country states should be available in res_country_state.
* the address format for austria given in res_country:address_format is wrong by the way (i may create another PR to fix that).
* customers just say: "other ERP software know the states! what else is missing in odoo?"
* states _really_ do not change often in austria and it is just nine of them.
* having it in l10n_at, as @wtaferner mentions may be fine as well, but:
* res_country_state can be very well used for other things then just the addresses on letters/official documents. i am thinking of mapping IoT devices. the country may be not specific enough, the city already to exact (GDPR issues).

**Comment by wtaferner** [comment]
@nikiwaibel 
I always added them in a seperate module until now, but as @mart-e is going to accept them in the `l10n_at` module I guess no customer can complain anymore even out of the box in the future IMO.

I addtionally fixed the address format for Austria as we normally do not use the `state_code` in the address.

**Comment by nikiwaibel** [comment]
@wtaferner the austrian state names are officially defined for german only, actually. the english names exist, but see note-1 at https://en.wikipedia.org/wiki/ISO_3166-2:AT.

also, look at other countries in odoo/addons/base/data/res.country.state.csv - the local name should be used … (if someone needs to translate it to english - fine).

**Comment by nikiwaibel** [comment]
@wtaferner cool. but pls use the german and not the english names. the address_format (in res_country) should read
```
%(street)s
%(zip)s %(city)s
%(country_name)s
```
instead of:
```
%(street)s
%(street2)s
%(city)s %(state_code)s %(zip)s
%(country_name)s
```
not sure if %(street2)s needs to be included …

**Comment by wtaferner** [comment]
@nikiwaibel 
Jep, you are right, it was changed that the name is not translateable anymore, so I provided the proper names. The address format is correct as provided correctly in my PR (we need the `street2`)

**Comment by nikiwaibel** [comment]
all done in #50664. kudos to @wtaferner!

@wtaferner: mal schauen. eher odoo anfänger (seit einer woche etwas intensiver damit beschäftigt - ich denk ich hab das kleine odoo-1x1 verstanden), allerdings ist python ist nicht so mein ding (ich mag das stark typisierte 😉).

**Pull request closed without merging**
