### PR TITLE
[FIX] base: invisible="context.get(...)" takes priority only if True

### PR DESCRIPTION
**Pull request by beledouxdenis**
This is an oversight in odoo/odoo#100130

A modifier set with `context.get('...')`,
for instance
`invisible="context.get('sign_directly_without_mail',False)"` takes priority on attrs
only if the result of `context.get('...')` isn't falsy

e.g.
https://github.com/odoo/enterprise/blob/1a4e4fafe4fc78dab0aad7ab6241a6f4a7be317a/sign/wizard/sign_send_request_views.xml#L64

should return
- `modifiers="{'invisible': [['is_user_signer', '=', false]]}"` with `context.get('sign_directly_without_mail') == False`
- `modifiers="{'invisible': true}"` with `context.get('sign_directly_without_mail') == True`

### CODE REVIEW

**Comment by beledouxdenis** [comment]
robodoo override=ci/security
The `safe_eval` is just re-indented, it is left as it is.

**Comment by xmo-odoo** [comment]
@robodoo override=ci/security

**Review by bouvyd — APPROVED** [review]
Lgtm

**Comment by beledouxdenis** [comment]
robodoo r+

**Pull request closed without merging**
