### PR TITLE
[IMP] l10n_ch: switch account templates to csv from xml

### PR DESCRIPTION
**Pull request by hch-odoo**
task: https://www.odoo.com/web?debug#id=1909961&action=327&model=project.task&view_type=form&menu_id=4720

pad: https://pad.odoo.com/p/r.3bb795404d1e38ccc7cde9c4f6f3c9cd

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by fclementic2c** [comment]
@hch-odoo
 What is the purpose of this change please ?

**Comment by tivisse** [comment]
Hi @fclementic2c 

The import via a csv file could be quicker than via xml because as the model is the same for all the lines, the record creation can be batched.

When importing the record from a xml file, the records are created one by one, and all the required preprocessing is re-executed at each record creation. And no optimization is easily possible for this kind of import. 

Have a nice day,

Yannick.

**Comment by fclementic2c** [comment]
@tivisse Ok. many thanks for your explanation. :+1:

**Pull request closed without merging**
