### PR TITLE
[FIX][16.0] point_of_sale: correctly translate some UI elements

### PR DESCRIPTION
**Pull request by tranngocson1996**
Description of the issue/feature this PR addresses:
Multi-language support

Current behavior before PR:

Desired behavior after PR is merged:
https://user-images.githubusercontent.com/26604325/233535703-083e3981-b76f-46f6-8ab6-b6765009e96f.mp4

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
The terms you try to target here are translatable, they exist in the `point_of_sale.pot` file. It's just that in `addons/point_of_sale/i18n/th.po`, the terms are not translated.

**Comment by caburj** [comment]
If you want, you can directly contribute to the translation in odoo's transifex account.

Resources:
- In this [forum question](https://www.odoo.com/forum/help-1/how-can-i-translate-terms-in-odoo-own-database-or-all-odoo-standard-v15-204525), look for "You want to update translations for all Odoo standard".
- Here's an official link that can point you how to contribute in the translation: https://www.odoo.com/documentation/16.0/contributing.html?highlight=transifex

**Comment by caburj** [comment]
Pardon may ignorance in the two languages. I got them mixed up. I'll have a look again.

**Comment by davidmonnom** [comment]
We have reworked the commit and the commit message, is it possible to replace yours with this one and we will merge it:

https://github.com/odoo-dev/odoo/commit/bafaedaaf09f41694b3e4065dbae11a6fa29ac00

**Comment by davidmonnom** [comment]
@caburj Looks good for me!

**Review by caburj — APPROVED** [review]
@tranngocson1996, thank you so much for this contribution. Very much appreciated.

@robodoo r+

**Pull request closed without merging**
