### PR TITLE
[FIX] point_of_sale: "Autopost Created Moves" does not work with POS

### PR DESCRIPTION
**Pull request by andrius-preimantas**
**Account Moves are not autoposted**

Impacted versions:
- 8.0

Steps to reproduce:
1. Mark "Autopost Created Moves" on your POS sales journal
2. Open POS, make some sales
3. Close session, hit Validate Closing & Post Entries

Current behavior:
- Account Move is created but still in Draft state

Expected behavior:
- Account Move is created but still in Posted state

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the patch but I would prefer a generic fix (in account probably) than manually posting the entries in point of sale.
I will be looking into another patch to fix the POS issue.
I have already merged your CLA (2bc7536) in the meantime, thanks for that.

**Comment by andrius-preimantas** [comment]
Hi,

Ok, looking forward to your generic fix :-)

Cheers
Andrius

**Comment by mart-e** [comment]
@andrius-preimantas probably something like #5531

**Comment by andrius-preimantas** [comment]
Fantastic! Thanks Martin for informing me about your PR

Cheers,
Andrius

**Comment by mart-e** [comment]
Hello,

As discussed on #5531, the current behaviour of account is correct.
So I agree that the fix should be done in pos module but actually I don't think you should check the value of `entry_posted` on the journal.
When you generate an entry in from an automated process such as the point of sale, the entries should always be posted, whatever the value of `entry_posted` (which is an addition for manually created entries).

**Comment by andrius-preimantas** [comment]
Hello, Martin

Yes, I agree with your opinion it should be automatically posted from automatic creation. All in all "Autopost Created Moves" is quite a questionable feature to have as it is inconsistent depending on how moves were created. But that's I guess is a different issue.

Probably there's no point of updating this PR as it was focused on different idea so it could be closed.

Thanks for your time,
Cheers
Andrius

**Comment by mart-e** [comment]
Ok, thank you for the reply.

**Comment by lapagept** [comment]
I have applied the fix above. It works. But the sequence always increase when the account move line is posted. Each account move line doesn't have the same POS sequence than the pos order. For example, the pos order has the sequence POS000100 but the posted account move line has the sequence POS000102 in his number field. How could we have the same number in the posted account move line than the pos order?

**Pull request closed without merging**
