### PR TITLE
[FIX] l10n_cl: add country configuration to taxes' tags

### PR DESCRIPTION
**Pull request by qsb-odoo**
Task: https://www.odoo.com/web#id=2212790&action=327&model=project.task&view_type=form&cids=2&menu_id=4720

### CODE REVIEW

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by MiquelRForgeFlow** [comment]
@jco-odoo A similar PR for l10n_mn must be done.

**Comment by jco-odoo** [comment]
@MiquelRForgeFlow It is merged or on its way to be.  Will check nightly anyways.

**Comment by MiquelRForgeFlow** [comment]
Ok, thanks. Also `l10n_za` 😅

**Comment by rgo-odoo** [comment]
@jco-odoo Could you please process the forward-port chain ? Thanks.

**Comment by jco-odoo** [comment]
@rgo-odoo Thanks.

**Pull request closed without merging**
