### PR TITLE
[IMP] l10n_ke: 2% Withholding VAT

### PR DESCRIPTION
**Pull request by AllePilli**
In Kenya, some customers are assigned to withhold the VAT on vendor bills. To avoid penalties the WH Report is created, this report provides a clear view on the total VAT withheld in a period and when it should be paid. The withheld VAT information is also used to complete the calculation of the VAT due in the Tax report.
The report depends on some new taxes:
- 2% WH based on payment (for purchase and sale) (added `tax_exigibility` and `cash_basis_transition_account_id` columns in csv)
- Import VAT (16%) (added `tax_scope` column in csv)

task: 3703440

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by malb-odoo — COMMENTED** [review]
Some questions or tiny nitpicking :smile: Maybe we could ask if it would not be nice to use sections instead of a new variant for the WH tax report

**Comment by malb-odoo** [comment]
i see that you forced push on the branch but didn't reply to the review, don't forget to check the different messages :smile:

**Review by malb-odoo — COMMENTED** [review]
Just wondering about the translation otherwise it looks good ! Can you confirm that Kenya don't need to be translated in swahili ? :smile: Also runbot is red, i rebuild it but may need a rebase if that's still red

Other point of question, we only want the information of the withholding in the move and not the pdf ?

**Review by malb-odoo — APPROVED** [review]
LGTM :smile: 
William is in holiday so we will have to wait for him to come back or try to get the r+ from someone else :smile: 

I see that runbot is red, let's see if the rebuild is enough

**Review by qdp-odoo — CHANGES_REQUESTED** [review]
few things to change, looking pretty much OK :)

**Comment by qdp-odoo** [comment]
oh, the chart template can't be installed... 

  File "/home/odoo/dev/odoo/addons/account/models/res_config_settings.py", line 250, in set_values
    self.env['account.chart.template'].try_loading(self.chart_template, company=self.company_id)
  File "/home/odoo/dev/odoo/addons/account/models/chart_template.py", line 156, in try_loading
    return self._load(template_code, company, install_demo)
  File "/home/odoo/dev/odoo/addons/account/models/chart_template.py", line 204, in _load
    data = self._get_chart_template_data(template_code)
  File "/home/odoo/dev/enterprise/account_accountant/models/account_chart_template.py", line 30, in _get_chart_template_data
    data = super()._get_chart_template_data(chart_template)
  File "/home/odoo/dev/odoo/addons/account/models/chart_template.py", line 685, in _get_chart_template_data
    data = func(self, template_code)
  File "/home/odoo/dev/odoo/addons/account/models/chart_template.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/odoo/dev/odoo/addons/account/models/chart_template.py", line 959, in _get_account_tax
    tax_data = self._parse_csv(template_code, 'account.tax')
  File "/home/odoo/dev/odoo/addons/account/models/chart_template.py", line 1148, in _parse_csv
    res[row['id']] = {
  File "/home/odoo/dev/odoo/addons/account/models/chart_template.py", line 1149, in <dictcomp>
    key.split('/')[0]: evaluate(key, value, model_fields)
  File "/home/odoo/dev/odoo/addons/account/models/chart_template.py", line 1138, in evaluate
    return ast.literal_eval(value) if value else False
  File "/home/odoo/dev/odoo/odoo/_monkeypatches/literal_eval.py", line 28, in literal_eval
    return orig_literal_eval(expr)
  File "/usr/lib/python3.10/ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    0"
     ^

**Comment by qdp-odoo** [comment]
=> in tax csv, PWT5 line has wrong value for `active` field ("0""" instead of "0")

But then it's failing somewhere else later.

Long story short: needs a rebase and some fixing :)

**Review by qdp-odoo — APPROVED** [review]
:+1

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
