### PR TITLE
[FIX] sale: allow deleting notes/sections on confirmed order

### PR DESCRIPTION
**Pull request by yelizariev**
Lines cannot be deleted if the order is confirmed. However, notes/sections lines
still might be changed. So, let delete such lines too.

STEPS:

1. Create SO, add product and add note
2. Confirm SO
3. Remove note

---

opw-2852676

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Feyensv — APPROVED** [review]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo r-
ongoing debate with PO/team

**Comment by yelizariev** [comment]
> @yelizariev why do you consider that notes and sections might be changed ? In which cases is it a problem not being able to ?

I'm not a PO and the ticket doesn't  have information about it. The user workflow may vary. Maybe they use note to gives some information about delivery (e.g. late delivery), which might be obsolete after order confirmation.

But anyway, if we let change the note, why shouldn't we let to delete the note.

**Comment by Feyensv** [comment]
@robodoo r+

**Pull request closed without merging**
