### PR TITLE
[CLA] BeOpen

### PR DESCRIPTION
**Pull request by huysmki**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

BeOpen is a company in startup phase (under Cronos-groep)

### CODE REVIEW

**Comment by Yenthe666** [comment]
@mart-e quick and easy merge.

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using an address `@github.noreply.com`
- you are signing for an address `@telenet.be`

You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by huysmki** [comment]
Hi,

I changed my git configuration.
Can you please reevaluate?

Thx.

**Comment by mart-e** [comment]
@huysmki the issue is that you have made the pull request from your github profile and not using your local git client. As you have forbidden to display your email address on your profile the commits are made with the `@users.noreply.github.com` email address. So changing your local configuration will not affect the already published code.

What you are supposed to do is to locally amend your CLA to remake a commit in your branch `patch-1` using the correct address and make a push force to resubmit using the correct address.

**Comment by huysmki** [comment]
Hi mart-e,

I did what you asked. I was using the wrong email address anyway.
 
Can you please reevaluate?

Thx.

**Comment by mart-e** [comment]
Thank you for the correction, it has been integrated into Odoo at revision b868ae51b6838685eca60c5ed1ee34d5b071c768.
Regards

**Pull request closed without merging**
