### PR TITLE
[IMP] project: reduce column width in task list view

### PR DESCRIPTION
**Pull request by kusi-web**
**Improvement**

This PR reduces the width of columns in the task list view for better space utilization.

task-4034478

### CODE REVIEW

**Review by pkyriakou — COMMENTED** [review]
Thank you @kusi-odoo :100: I have nothing to comment, LGTM :heavy_check_mark:

**Review by xavierbol — COMMENTED** [review]
robodoo r+

**Comment by xavierbol** [comment]
robodoo r+

**Comment by xavierbol** [comment]
robodoo r+

**Pull request closed without merging**
