### PR TITLE
[IMP] base, *: allow html fields not to sanitize forms

### PR DESCRIPTION
**Pull request by proose**
\* = website_slides

The option to sanitize or not the forms was not available, this will
allow better flexibility on whether forms should be sanitized or not on
an HTML field.
Also we use this new param to allow forms to be added on an already
existing html field where the form was sanitized out.

This is a backport of 388c222c6c4bb7e2fe3e67009b248359ae0fd3db
adapted to the needs in 13.0

### CODE REVIEW

**Comment by proose** [comment]
@fw-bot ignore

**Comment by JKE-be** [comment]
@proose 

13.0 is a stable version ... 
We avoid/don t change API of function...

**Comment by proose** [comment]
Hello @JKE-be 
I know it should be avoided, but I'd need this change for fixing the issue depicted in this PR: https://github.com/odoo/odoo/pull/77128 (if this backport is accepted, the fixing PR would only use `sanitize_attributes=False` and `sanitize_form=False`, instead of a full `sanitize=False`).

I saw that it was mentioned to maybe add this change into 13.0, and it looks quite innocent, so I created this PR in hope it could be merged...

**Comment by xmo-odoo** [comment]
> @proose
> 
> 13.0 is a stable version ...
> We avoid/don t change API of function...

This is a backport of a backward-compatible API improvement which allows fixing an other bug, I suggested backporting it to implement the fix properly instead of having to `sanitize=False` the entire field.

**Comment by proose** [comment]
@JKE-be 
Do I close this, or would you agree on backporting this commit ?

**Comment by JKE-be** [comment]
See with @xmo-odoo he seems agree with it.

Imo, since you can call a method without named the params, I don't consider really it as 100% stable, but acceptable. 
And in this case the change can be louch, you will start to strip_classes e.g. if you call previously html_sanitize(..., True, True). 

But if you want already reduce the risk, move at least sanitize_form as last param imo... 

After all, it is a question of 'gain of the bugfix'  vs  'risk to break existing custo/code'...

**Pull request closed without merging**
