### PR TITLE
[FIX] stock: impossible to update show_operations

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
On large database with millions of stock move and picking, 
if you try to update show_operations on picking type, 
a CPU Time limit can appear.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@amoyaux

**Comment by fmdl** [comment]
OPW #2643725

**Comment by ryv-odoo** [comment]
Hello @fmdl , can we have more information (nb of picking, nb of move, pyflam, ...). Also

**Comment by fmdl** [comment]
It is the same issue of https://github.com/odoo/odoo/pull/70780

It is an db with 600 000 pickings, it take 5-10 minutes.

@rco-odoo

**Comment by ryv-odoo** [comment]
> It is the same issue of #70780, the ORM compute alls triggers, and on large database it take lot of time. It is not an SQL issue.
> 
> With a db with 600 000 pickings, it take 5-10 minutes. (With 6 000 000, ...)
> 
> @rco-odoo

And with the index on picking_type_id? It will be always slow but it shouldn't be a daily operation (change the configuration of your picking type).

**Comment by rco-odoo** [comment]
> With a db with 600 000 pickings, it take 5-10 minutes. (With 6 000 000, ...)

Please don't get me wrong, but changing `show_operations` on a picking type, *knowing that 600K pickings are impacted*, simply looks like a stupid idea to me...  I may be wrong, but IMHO this flag on picking type is *clearly* not made for users to change their mind on its value.

This reminds me about a company using Odoo for a full year before realizing that they installed the wrong chart of accounts.  Their accounting entries were *of course* incorrect.  But that's not a programming bug, you know.  Making management software like Odoo idiot-proof is really a challenge, if not some fantasy...

**Comment by jeffery9** [comment]
#108405

**Pull request closed without merging**
