### PR TITLE
[MERGE] digest, various: add or improve digest tips and digest layout

### PR DESCRIPTION
**Pull request by aph-odoo**
PURPOSE

Review the tips and digest layout design to make sure they have a WOW effect
and increase trial conversion/retention.

SPECIFICATIONS: LAYOUT

Besides changing the tips, a cleaning of digest layout was performed. Emails
were reported to look not neat in Outlook and somewhat random in mail.com or
gmail.com.

Most recent HTML CSS cannot be used to make HTML emails because each email
provider renders emails its own way. This means a given email may renders
differently in gmail.com and outlook.

The layout of the email was composed of several levels of embedded tables
which means huge maintenance effort. So it was totally rewritten with divs
and CSS, but some properties are not taken into account.

A lot of page component improvements were done. It consisted in replacing most
of the style attribute in tags with CSS classes and ids. This step is
especially useful for tip formatting because before, if a style modification
was needed, it had to be performed on each tip individually.

SPECIFICATIONS: TIPS

Add / Improve tips in cmr, purchase, hr_recruitment, website, hr_expense, project,
digest, sale_management, im_livechat, stock, mrp, account.

LINKS

COM PR: odoo/odoo#53580
ENT PR: odoo/enterprise#11394

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-merge

**Comment by qsm-odoo** [comment]
@aph-odoo @tde-banana-odoo Since the merge of this branch, I cannot build a database with website, could you please check as soon as possible? Thanks

**Comment by tde-banana-odoo** [comment]
Will look. What issue do you get ?

**Comment by sdegueldre** [comment]
@tde-banana-odoo https://pastebin.com/1jv8RyXL

**Comment by tde-banana-odoo** [comment]
Ok, missing dependency. Fix incoming.

**Comment by tde-banana-odoo** [comment]
Actually there were tips before this commit, but not imported ... it should have been crashing since a while.

**Pull request closed without merging**
