### PR TITLE
[FIX] payment: No error logged if no real error in transaction

### PR DESCRIPTION
**Pull request by jvh83**
Copy behaviour of `_set_transaction_cancel()`.
Only log processed transactions.

OPW-2575711

### CODE REVIEW

**Review by AntoineVDV — APPROVED** [review]
@jev-odoo Could you please change your commit message to "[FIX] **payment**: ..."?

Works for me otherwise, as discussed earlier :+1:

**Comment by AntoineVDV** [comment]
@fw-bot ignore

**Comment by jev-odoo** [comment]
@AntoineVDV Done ;)

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
