### PR TITLE
[[DROPPED]] - [IMP] account: don't show tax groups @ 0.0

### PR DESCRIPTION
**Pull request by blaggacao**
In some cases, a tax can be applied as a calculatory group, where two child
elements zero out each other. In such case, where the total group amount
would result in 0.0, we don't want to display this group.

Doing so would be confusing to the spectator. After this commit, this confusion
is relieved.

**Description of the issue/feature this PR addresses:**
- 0.0 results of tax groups generate confusing UI on printed invoice

**Current behavior before PR:**
- (Calculatory) Tax groups resulting in 0.0 total are printed on inovices

**Desired behavior after PR is merged:**
- (Calculatory) Tax groups on invoices, resulting in 0.0, are not printed in invoices as they are not relevant to the recipient (after all they don't have any effect on the transaction sum).

**Note:** Please do not close, even if not immediately accepted (`wishlist` tag). This PR is meant to be carried along and actively maintained, until this semantic will be completed this way or another.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

@xoe-labs

### CODE REVIEW

**Comment by blaggacao** [comment]
This would conflict with #26331 - If one of those should be accepted, please ping me for a quick refactor of the respective other.

**Comment by blaggacao** [comment]
@qdp-odoo This one's just right to finish off the day... :stuck_out_tongue_winking_eye: Ok, I'm beeing abusive now..

**Comment by qdp-odoo** [comment]
mmh I'm not as certain as you are: there might be use cases where you want to see the tax groups where the total tax amount is 0€...

Let's ask more opinions here....

@Yenthe666 (for once, I'm the one pinging you!):  I think in Belgium at least this patch would be considered as a bug ^^ What do you think?

**Comment by pedrobaeza** [comment]
Are we talking about the base or the amount? For the amount, we have in Spain several tax groups which total amount is 0 (intra-community VATs).

**Comment by qdp-odoo** [comment]
@pedrobaeza yes, that's the topic. I think that even if the tax group will be 0, we have to show it on the invoice report. Is it right?

**Comment by blaggacao** [comment]
@pedrobaeza amount!
@qdp-odoo Valid. To expand: A group only appears if the tax is present on the invoice. This invalidates the trivial use case: "I want to see a tax even if it doesn't apply only to underpin it's NOT applying".

The effects, therefore, are limited to the use case:
- "I have a tax group, which sums to 0, and I wan to to have on the invoice `Tax group name: 0.0`"
- Semantically, this is a little awkward no matter from what angle you look at it.
- The motivation is too close to "I want to see a tax even if it doesn't apply only to underpin it's NOT applying"
- Yet, that's not supported anyway, right now.

**Comment by pedrobaeza** [comment]
@blaggacao what you are missing is that the report put in case of multiple taxes this text (thanks to a recent merged PR :wink: ): `<Tax group name> on <base amount> €: 0.0`. The important part there is the base amount, not the tax amount.

**Comment by qdp-odoo** [comment]
but even if the amount total is 0, it doesn't mean the base amount isn't important...

**Comment by blaggacao** [comment]
@pedrobaeza Very good. Yet, my "fix" only targets the len>1 case, where your objection is not correct.

**Comment by blaggacao** [comment]
To me, it would be intelligible to expose the base amount also for `len>1`, rather than accepting this commit. @qdp-odoo What do you think?

**Comment by pedrobaeza** [comment]
@blaggacao check the recently merged #25341 fixing the layout for this.

**Pull request closed without merging**
