### PR TITLE
[ADD] archetipo CLA

### PR DESCRIPTION
**Pull request by archetipo**

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature but I think you miss-[configured your git](https://help.github.com/articles/setting-your-email-in-git/), you are signing with `archetipo@localhost` email address.

**Comment by archetipo** [comment]
thanks @mart-e.. 
updated should be right now. tnx.

**Comment by mart-e** [comment]
Well once you have configured your git locally you need to re-push your CLA with the new signature

**Comment by archetipo** [comment]
@mart-e.. re-pushed thanks

**Comment by mart-e** [comment]
Thanks, merged at fc2d7f7945bdf3d667e16b55ed96852ce6a56074

**Pull request closed without merging**
