### PR TITLE
[ADD] core: automatically validate overrides on registry load

### PR DESCRIPTION
**Pull request by xmo-odoo**
Problem: methods can be removed or renamed, and their overrides can be missed in the meantime, generating dead code and possibly losing features / adding bugs which can be hard to track.

On registry load, looks for `super` in methods, tries to find out what they're looking for in a superclass and checks if that thing exists. Has some impact on registry loading (on my machine, with 500 modules loaded the check costs 1.5s to ~10s, it also shouldn't cost that much on re-check e.g. module installations as the classes are "cached").

TODO: probably remove the jump handler for 3.5? I don't think we support that in master.
TODO: check the 15 methods it's currently finding to see what's to fix e.g. remove outdated method or rename an override of a renamed method

From a request of @fmdl in #53450, this solution is more CPU-expensive than an explicit `@overrides` but generates far less code churn to produce results: methods don't need to be annotated to be checked, meaning we can't forget annotating methods (unless we make the annotation a requirement à la C# I guess, but that would be *a lot* of code churn).

### CODE REVIEW

**Comment by odony** [comment]
I consider the possibility of having "floating" overrides an important feature of the framework. It allows developing creative and flexible modules, that can support multiple versions of the software for example. It is used a lot on the SaaS platform.

Moreover, fixing any function renaming is part of the work of upgrading modules, we should not waste CPU cycles on this at runtime.

**Comment by xmo-odoo** [comment]
> I consider the possibility of having "floating" overrides an important feature of the framework. It allows developing creative and flexible modules, that can support multiple versions of the software for example. It is used a lot on the SaaS platform.

Seems like *that* should be an opt-in.

> Moreover, fixing any function renaming is part of the work of upgrading modules, we should not waste CPU cycles on this at runtime.

Detecting this issue "at rest" seems posible but quite significantly more complicated.

**Comment by fmdl** [comment]
@xmo-odoo good work !

Some méthode are override (in custom module for customer, especially, in odoo also ) without use super. (In this case @overide is useful). 

Idea : @oberride(exludeversion=“12.0”)

**Comment by rco-odoo** [comment]
Cancelled.

**Pull request closed without merging**
