### PR TITLE
[FIX] website_forum: error when converting answer/comment

### PR DESCRIPTION
**Pull request by jpp-odoo**
- Create 2 companies (A and B for instance);
- Create 2 users with password, one on each company (user 'a' in
  company A and user 'b' in company B);
- Add enough karma on both users;
- Add a valid email address to both users;
- As user 'b' :
  - open any forum topic and validate the email address;
  - post an answer or comment to a forum post;
- As user 'a' :
  - open the forum and find the answer/comment made by user 'b';
  - convert the answer as comment or convert a comment as answer;

Before this commit, an error was raised : 'Access to unauthorized or
invalid companies'.

opw-2296470

### CODE REVIEW

**Comment by jpp-odoo** [comment]
Related to https://github.com/odoo/odoo/commit/b7fd679a6c41dbb694c6fb2ce4911798de0424b1

**Comment by jpp-odoo** [comment]
robooo r+

**Comment by nim-odoo** [comment]
robodoo delegate+

**Comment by jpp-odoo** [comment]
robodoo r+

**Pull request closed without merging**
