### PR TITLE
[IMP] mail: invite link redirect internal users to the backend

### PR DESCRIPTION
**Pull request by phenix-factory**

### CODE REVIEW

**Comment by seb-odoo** [comment]
This is not desirable, where is this task coming from?

It's going to be very confusing when testing the invitation link for internal users.

On top of that, we have different URL for different purpose, it looks like people don't use or share the correct URL if they need the other one.

What we can do is to add buttons to easily go from backend to standalone view and the other way around, similar to what is done in portal documents.

**Comment by seb-odoo** [comment]
We might have a special redirect URL if we want, but we don't want to redirect existing URL like that.

**Comment by alexkuhn** [comment]
> This is not desirable, where is this task coming from?

I asked for it, because there's a need to provide a link and internal users access the channel with all excepted backend/`/odoo` features they are used to.

> It's going to be very confusing when testing the invitation link for internal users.

It's very easy to test as a non-internal user: just log in anonymously, or logged-in as an external user. And it's more important to make things more convenient.

> On top of that, we have different URL for different purpose, it looks like people don't use or share the correct URL if they need the other one.

The invitation link was made at the same time we enabled non-user people to chat. AFAIK there's no hard intent for the invitation link to always show the public page, even with internal users, with limited features. There more and more shared discuss features with `/odoo`, but at the same time you don't have access to rest of `/odoo`. This limitation simply exists because we assume the invitation link is essentially used only by guests, and we just went with simplest code.

> What we can do is to add buttons to easily go from backend to standalone view and the other way around, similar to what is done in portal documents.

Why not just simply open in `/odoo`? What's the motivation for not going to `/odoo` for internal user?

**Comment by seb-odoo** [comment]
If we're replacing discord by odoo I don't want to clutter my always-open chat page with backend stuff.

Same for people that just want to do a quick call (meet), same for event integration (they are specifically working on using our page now), etc.

Testing as logged in user is necessary too, we don't want to have a logged out only page.

If the page is not good enough that we don't want to use it, it should be improved instead.

As I said I'm fine with having a smart redirect link (which can be a param on the url, a different url, or an option on the page itself, which can be remembered for a user), but I'm not fine for using the standard public page url and preventing to use it completely.

**Pull request closed without merging**
