### PR TITLE
[IMP] crm: improved copywriting

### PR DESCRIPTION
**Pull request by fpodoo**
Terms improvement for the tour

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fpodoo** [comment]
@robodoo r+

**Comment by fpodoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r-

I will improve commit messages and push something clean. Thanks for the PR !

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
