### PR TITLE
[IMP] l10n_be_hr_payroll_fleet, fleet: Adapt CO2 Tax up to 2019

### PR DESCRIPTION
**Pull request by tivisse**
Specification
=============

- Adapt the formula used in the code with the current legal value.
- Add the LPG fuel type in standard fleet module.
- Adapt the atn formula in the code with the current legal value.

Documentation:
https://finances.belgium.be/sites/default/files/downloads/121-faq-voitures-de-societe-2019-version17.pdf
https://www.socialsecurity.be/employer/instructions/dmfa/fr/latest/instructions/special_contributions/companycar.html

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tivisse** [comment]
@robodoo r+

**Comment by tivisse** [comment]
@robodoo retry merge please.

**Comment by KangOl** [comment]
Note that I have kept the master version during forward-port.

**Comment by tivisse** [comment]
Thanks for the feedback @KangOl 

We're gonna clean this !

**Comment by sed-odoo** [comment]
1. Since the tax fee formula was updated, the value in the test needed to be changed in order to match the computation result.

2 & 3. The difference has been cleaned in this PR : https://github.com/odoo/odoo/pull/30841

**Comment by RomainLibert** [comment]
Basically the date on the contract doesn't matter as those values work like the _indexation des salaires_ and is therefore not decided on the contract.
The only case where the date matters is if you want to generate a new payslip in 2018, in which case you will have to manually check the payslip computation and update it by hand.

The big change is that we now compute the CO2 fee based on the fuel type whereas the old code was only computing it based on diesel.
This has an impact on the CO2 fee of people having a company car which does not use diesel as fuel.
Maybe in this case a new contract should be signed (I'm not even sure)

**Pull request merged**
