### PR TITLE
[FIX] website_event_sale: don't publish event products

### PR DESCRIPTION
**Pull request by lipiraux**
Description of the issue/feature this PR addresses:
The product page of event products (e.g., product templates with variants used as registration products in a published event) is accessible to public/portal users.

Current behavior before PR:
Public/Portal users can access the event's products, product page by knowing the url, even if the product is not published.

Desired behavior after PR is merged:
Public/Portal users cannot access the event's products, product page. Instead, they need to use the event page to buy tickets.

task-4220260

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by vchu-odoo — APPROVED** [review]
Thank you for your work on this task!

LGTM :+1:

**Review by reth-odoo — APPROVED** [review]
I'm sure it must have been useful 12 years ago

**Review by Feyensv — COMMENTED** [review]
Could you rebase your branch so that the upgrade runbot is green ? :pray: 

Also, could you update your commit message as well to
1) remove the "Closes #...", it's automatically added by the mergebot on the merged commit.  No need to add it manually in your PRs because it creates a loooot of noise if you have to push frequently during the task progress (or even reviews).
2) remove the reference to the community PR too, it was a good information on the task to have the debate and origin of the task, but it doesn't really add much to the commit itself, explaining that the products were accessible on the website even though they are not meant to be sold (except through event flows) is enough.

**Comment by Feyensv** [comment]
Seems like you missed my second point :eyes:
Also, I should have noticed earlier, but the commit title could also be modified to be shorter (if github crops it with `...` it means it's too long) and to explain more the functional fix (stop giving access to the product page of event products) than the technical change (removing the rule).

[Our commit guidelines](https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html) could also help (though there are some parts that should be updated/improved).

**Comment by lipiraux** [comment]
My bad ! For whatever reason I changed the commit for the first point, and the PR description for the second :sweat_smile:. Now both are equivalent, and hopefully good to go.

**Review by Feyensv — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
