### PR TITLE
Adds support for PDF417 barcode type generation

### PR DESCRIPTION
**Pull request by Danisan**
Description of the issue/feature this PR addresses:
For electronic invoicing in some countries, there is a need to generate barcode type PDF417, which is a self-contained barcode.

Current behavior before PR:
The barcode is not generated natively in Odoo. This type of barcode is a requirement of authorities in Chile.

Desired behavior after PR is merged:
When you use the native controller /report/barcode you can include the type "pdf417" to your call.

As we are using the library https://pypi.org/project/pdf417gen/ to generate the code, this one does not base the barcode image in height and width. Instead uses other parameters we made the most approximated conversion of these to height and width so that if you don't pass them, you will have the same default width that is already used (600px).

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Danisan** [comment]
@jco-odoo Here is the pdf417 controller we need for invoices.

**Comment by Danisan** [comment]
@jco-odoo I have added the try/except to this. Please need to know if this is ok to enjoy the functionality in the following code for the invoice template. TKS!

**Comment by jco-odoo** [comment]
@Danisan I don't like the error log.  It should still be seen as an optional module.  (you just leave the barcode empty then)

@julienlegros Does it look ok for you to add it like this?

**Comment by Danisan** [comment]
Why don't add pdf417gen to requirements directly? 
@jco-odoo

**Comment by jco-odoo** [comment]
@suv-bmya @Danisan  I think it is better to do it only in l10n_cl_edi as we will still bother people in stable with the installation of pdf417.  I don't see any problem in simply inheriting the barcode method in l10n_cl_edi and loading the library over there.  When you do try..except, please use except ImportError.  It would also be good that if the library is not there and you want a pdf417 that it does not just traceback, but just gives an empty image e.g.  (you can do if pdf417gen: or something)

**Comment by Danisan** [comment]
deprecated. Replaced by #55596

**Pull request closed without merging**
