### PR TITLE
[FIX] base: Fix cron KeyError when interval_number is not defined

### PR DESCRIPTION
**Pull request by moylop260**
# Steps to reproduce

1. Create a `ir_cron` record defining `interval_type=False`
2. Run the cron

# Current behavior

All the crons get stuck (not only the corrupted one)

Notice does not matter how many cron_workers you had configured

since that the available workers took the corrupted one all the time

# Expected behavior

Raise error if you try to create a corrupted ir_cron record with interval_type=False

In order to avoid getting stuck all the crons

Credits @hbto

### CODE REVIEW

**Comment by moylop260** [comment]
@Julien00859 

What do you think?

**Comment by Julien00859** [comment]
imo it is a good idea but the runbot the red like a christmas tree :(

**Comment by moylop260** [comment]
@Julien00859 

I reproduced this same issue for v16.0

I just remember that I had a opened PR to fix it

I just rebased it

**Comment by Julien00859** [comment]
Does #144717 fixes the problem?

**Comment by moylop260** [comment]
Hi @Julien00859 

Using the following instance (build 61799472) from latest `master` branch:
 - Screenshot 2024-04-24 at 8 39 14 p m

It can reproduce the same traceback:
 - https://runbot205.odoo.com/runbot/static/build/61799472-master/logs/run.txt
   - Screenshot 2024-04-24 at 8 41 05 p m

**Comment by moylop260** [comment]
The steps to reproduce it from latest runbot master:
 - [IMAGE ALT TEXT](http://www.youtube.com/watch?v=UVtM6fL3jYo "Video issue cron")

**Comment by Julien00859** [comment]
image
On my side it is not possible to select "nothing", on both chrome and firefox.

Changing the interval_type via code is forbidden too:

```
37:15.128 INFO odoo.modules.registry: Registry loaded in 0.200s 
env: <odoo.api.Environment object at 0x7ff462f3f280>
odoo: <module 'odoo' from '/home/julien/Odoo/community/odoo/__init__.py'>
openerp: <module 'odoo' from '/home/julien/Odoo/community/odoo/__init__.py'>
self: res.users(1,)
Python 3.10.6 (main, May 20 2023, 03:47:42) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(Console)
>>> c=env["ir.cron"].search([], limit=1)
>>> c
ir.cron(1,)
>>> c.interval_type = False
>>> c.flush_model()
37:45.894 ERROR odoo.sql_db: bad query:  UPDATE "ir_cron"
                    SET "interval_type" = "__tmp"."interval_type"::VARCHAR, "write_date" = "__tmp"."write_date"::timestamp, "write_uid" = "__tmp"."write_uid"::int4
                    FROM (VALUES (1, NULL, '2024-04-29 08:37:15.129568', 1)) AS "__tmp"("id", "interval_type", "write_date", "write_uid")
                    WHERE "ir_cron"."id" = "__tmp"."id"
                
ERROR: null value in column "interval_type" of relation "ir_cron" violates not-null constraint
DETAIL:  Failing row contains (1, 34, 1, 1, -1, 3, 1, 1, Base: Auto-vacuum internal data, null, t, null, 2024-04-29 08:36:52, null, 2024-04-29 08:36:42.349334, 2024-04-29 08:37:15.129568).
 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/julien/Odoo/community/odoo/models.py", line 6303, in flush_model
    self._flush(fnames)
  File "/home/julien/Odoo/community/odoo/models.py", line 6350, in _flush
    model.browse(id_vals)._write_multi(id_vals.values())
  File "/home/julien/Odoo/community/odoo/models.py", line 4559, in _write_multi
    self.env.execute_query(SQL(
  File "/home/julien/Odoo/community/odoo/api.py", line 865, in execute_query
    self.cr.execute(query)
  File "/home/julien/Odoo/community/odoo/sql_db.py", line 346, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "interval_type" of relation "ir_cron" violates not-null constraint
DETAIL:  Failing row contains (1, 34, 1, 1, -1, 3, 1, 1, Base: Auto-vacuum internal data, null, t, null, 2024-04-29 08:36:52, null, 2024-04-29 08:36:42.349334, 2024-04-29 08:37:15.129568).
```

**Comment by Julien00859** [comment]
I am such a n00b ahah, thank you for the fix! I'm gonna need a bit of time because it needs an upgrade script that I'll have to write on our private repository. Thank you! Sorry for the last message :sweat_smile:

**Comment by moylop260** [comment]
@Julien00859 

No problem, thank you for your reply, and thank you for taking care of this issue

> it needs an upgrade script

Be aware of something I just realized when I was generating this fix.

The `ir_cron.interval_type` field has defined `months` as default here:
 - https://github.com/odoo/odoo/blob/06b0421e4f5edde98494436071bed079687559a1/odoo/addons/base/models/ir_cron.py#L66

But the computed field `crm_auto_assignment_interval_type` based on `ir_cron.interval_type` doesn't have `months` in its options:
 - https://github.com/odoo/odoo/blob/50ac53990bc064f6cc16a54ac9a7d802c4f09339/addons/crm/models/res_config_settings.py#L25-L28

So, it could get a new error if you set the default value to `months` for all the records in the database

Raising the following error: `ValueError: Wrong value for res.config.settings.crm_auto_assignment_interval_type: 'months'`

Regards!

**Comment by Julien00859** [comment]
@moylop260 can you also add `required=True` on the `interval_number` field? I tried pushing on top of your branch but I am afraid you didn't allow maintainers from pushing :/

**Comment by moylop260** [comment]
@Julien00859 

I'm not sure what commit message to use for this new change.

Be aware using `required=True` for `Integer` fields even allows to use the value `0` in the UI, in fact, you can not store a `Null` value
 - Screenshot 2024-04-30 at 12 03 55 p m

That is the reason IDK what commit to use here or should be used the same commit?

(BTW I don't have the button "allow maintainers from pushing" :/)

**Comment by Julien00859** [comment]
@moylop260  The commit message is fine, about 0 on the UI, you cannot save the form thanks to the constraint defined a bit below
```
    _sql_constraints = [
        (
            'check_strictly_positive_interval',
            'CHECK(interval_number > 0)',
            'The interval number must be a strictly positive number.'
        ),
    ]```

**Comment by moylop260** [comment]
I got it

Thank you!

If you need something else let me know

Regards!

**Comment by Julien00859** [comment]
@robodoo r+ thanks!

**Comment by Julien00859** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
