### PR TITLE
m

### PR DESCRIPTION
**Pull request by pimodoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fvz-odoo** [comment]
Hello @jco-odoo 

I set up the database, but it is not allowing me to enter the session in the PoS, is there something I'm missing? 🤔

Let me know.

Cheers!

Fernando

@ren-odoo @vbe-odoo

**Comment by pimodoo** [comment]
@fvz-odoo It should work now, it was missing the payment methods, but due to a framework js issue that'll be resolved, the validation errors are not displayed

**Comment by fvz-odoo** [comment]
Hi @pimodoo 

Thanks a lot, I was now able to log in the session. Some comments already:

1. When I use the customer Blanco Martin y Asociados, it gets me the error of him not being from Chile or being international, which is not the case, he is set to Chile (both when I try with invoice and no invoice).
Screen Shot 2022-08-10 at 10 15 53 AM
2. When I use Azure Interior as customer (from the US), I now get an error about using taxes in a type of document that does not require taxes (Factura de Exportación Exenta 110 = Exempt Exportation Invoice 110). This means the sistem is actually getting that this is a foreign customer and would not require taxes, but the spec states that when there are no taxes it should be an Exempt Invoice 34 (Factura exenta 34). I dont't think we will cover foreign sales in the PoS yet, as we do not cover exportation of good yet. Same goes to Boleta and Boleta Exenta (39 and 41). 

This happens with or without invoice. In the spec is (for all chilean customers): 
- if invoice and taxes -> Invoice type 33
- if invoice and no taxes -> Invoice type 34
- if no invoice and taxes -> Boleta type 39
- if no invoice and no taxes -> Boleta type 41

Let me know when you can correct this issues so I can test further.

Cheers!

Fernando

@ren-odoo @Danisan @hea-bmya @jco-odoo

**Comment by jco-odoo** [comment]
@fvz-odoo Maybe @Danisan Can take this branch and do the fixes.

**Comment by Danisan** [comment]
> @fvz-odoo Maybe @Danisan Can take this branch and do the fixes.

I am testing it.

**Comment by fvz-odoo** [comment]
Hello @pimodoo 

We were checking with @jco-odoo about the new fields needed in the PoS in Chile, were you able to take a look? 

Let us know please!

Fernando

@Danisan @vbe-odoo @ren-odoo

**Comment by pimodoo** [comment]
> Hello @pimodoo
> 
> We were checking with @jco-odoo about the new fields needed in the PoS in Chile, were you able to take a look?
> 
> Let us know please!
> 
> Fernando
> 
> @Danisan @vbe-odoo @ren-odoo

Hello @fvz-odoo doesn't the PR localisation team is working on is this one? https://github.com/odoo/odoo/pull/99196

What do you mean by 'the new fields' ?

**Comment by fvz-odoo** [comment]
Hi @pimodoo 

Yes, we are working on that one... Sorry, not new fields, existing fields for the localization that are needed for electronic invoicing like taxpayer type, activity description, etc... We would need those fields to be editable in the PoS contact creation part...

You could make those changes in the other PR.

For reference, the fields needed are:

1. Taxpayer type: l10n_cl_sii_taxpayer_type
2. Activity Description: l10n_cl_activity_description
3. DTE Email: l10n_cl_dte_email
4. Identification Type: l10n_latam_identification_type_id

Thanks a lot!

Fernando

@ren-odoo @vbe-odoo @jco-odoo @Danisan

**Comment by pimodoo** [comment]
@fvz-odoo As we are near to the odoo experiences, and lot of stuff have been merged, we have a lot of stuff to do to bugfix the POS.

Maybe localization team should handle this.

**Pull request closed without merging**
