### PR TITLE
[FIX] website_slides: make url multi website compliant

### LINKED ISSUE #32348: [12.0] website_slides: sharing link with multi-website use web.base.url domain
Impacted versions: [12]

Multi-website with multiple domains
Sharing Links point to web.base.url instead of original domain

### PR DESCRIPTION
**Pull request by rdeodoo**
Before this commit, all url of channel were using `web.base.url` instead of the
current website domain.

Fixes #32348

The override of `get_base_url` method should not be forward ported after
saas-12.4 as since saas-12.5 it is now a model method (f727cd2645d).

### CODE REVIEW

**Comment by rdeodoo** [comment]
Should be good now, we should not forget to remove the `get_base_url` method override on saas-12.5 as it is on model.

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@robodoo r+
@JKE-be Forced-pushed to take care of the fact the compute could occur on multiple records. Also fixed the dependencies for the second one.

**Comment by qsm-odoo** [comment]
Note: if the icp changes, the compute method is not called again... (but that was already like that before)

**Pull request closed without merging**
