### PR TITLE
[FIX] *: typos in comments

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:** Fix typos everywhere.

They were provided by @sswapnesh in https://github.com/odoo/odoo/pull/35356#issuecomment-516966339.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
ping: @naglis @mart-e

**Comment by sswapnesh** [comment]
Thanks for PR @mreficent  

Sorry for little more work :wink: (If you wish to correct those too)

```
ourselve
webiste
differents
acount
globaly
fronted
preferrably
ICENSE
cusor
```

**Comment by mreficent** [comment]
thanks to you @sswapnesh

**Comment by sswapnesh** [comment]
```
globlist
dictonary

```
That's all I found till the date. :tired_face: 
Hopefully I will start creating list again and Create PR if there are lot like this. :muscle:

**Comment by mreficent** [comment]
but `globlist` is not a typo. It is formed by `glob` + `list`. a few lines after that appears glob.glob

**Comment by sswapnesh** [comment]
You are right.(And also that's code Cleaning not typos in the comments,My bad)

**Comment by mart-e** [comment]
Thanks for the mass correction :+1: 

@robodoo r+

**Pull request closed without merging**
