### PR TITLE
[IMP] web: adapts the UserMenu Shortcuts Table

### PR DESCRIPTION
**Pull request by FrancoisGe**
In UserMenu Shortcuts Table, we correct the shortcuts for MacOs and
we add the shortcut to open the command palette.

In this PR, we will correct the shortcuts in the UserMenu Shortcuts Table and we will reuse the command+k shortcut to open the command palette.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by brboi — APPROVED** [review]

**Review by aab-odoo — COMMENTED** [review]
explain why in revert commit message

**Comment by aab-odoo** [comment]
robodoo rebase-ff r+

**Comment by dmo-odoo** [comment]
@aab-odoo I just got notified of this PR. It reverted https://github.com/odoo/odoo/commit/2623b4591d25aeb2c5b58af92d6e8bcfa2341b31 but did not provide an alternative fix for the original bug, so the original bug has returned.

**Comment by dmo-odoo** [comment]
cc @JKE-be @qsm-odoo Since you were on the side of keeping CTRL+K for link if I recall correctly.

**Comment by aab-odoo** [comment]
Hello @dmo-odoo There have been discussions with the website's PO, AL... We were simply asked to switch back to ctrl+K, and "they" will deal with the link case (probably catch the event before the command palette). So I don't know what/if something has been done yet.

**Pull request closed without merging**
