### PR TITLE
[FIX] web: mockServer should return original reason on reject

### PR DESCRIPTION
**Pull request by rrahir**
For consistency, the reason of rejection should be propagated and not
partially stringified.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ged-odoo** [comment]
what's the problem you are trying to solve? The reason for the json.stringify is to simulate a network call: the mock server is not on the same process as the browser, so we need to serialize data. 

If you need to get the error directly, it seems like you are using the mock server in a real non test situation?

**Comment by rrahir** [comment]
> what's the problem you are trying to solve? The reason for the json.stringify is to simulate a network call: the mock server is not on the same process as the browser, so we need to serialize data.
> 
> If you need to get the error directly, it seems like you are using the mock server in a real non test situation?

You can have a look here : https://github.com/odoo/enterprise/pull/20834/files#diff-653c4c2edd9d7d3997504112e45115ce7567e5ea03eb9921e683816ec5080c23R68-R88  I'm trying to catch the error "destined" to  the crash manager. It seemed reasonable to expect to receive the actual reason provided to the reject here : https://github.com/odoo/enterprise/pull/20834/files#diff-0b4eaf64250ecbffa0d3e5605d9480e4f14cc2143cf91d804468323b8d033b88R791-R808

**Comment by sdegueldre** [comment]
@rrahir you should reject with an RPCError and the error should be formatted for the "crash manager" (it's now called the error service) by our legacy compatibility layer, see `mapLegacyEnvToWowlEnv` in `web/static/src/legacy/utils.js`. This will let you access the event and call `preventDefault()` on it (I think that's the problem you're trying to solve, correct me if I'm wrong)

**Comment by rrahir** [comment]
> `mapLegacyEnvToWowlEnv`

Isn't it essentially what I did  (at least from a formatting pov ) ? Note that I'm working on a 14.0 fix so not wowlEnv/error_service here ^^

**Review by sdegueldre — APPROVED** [review]
@rrahir sorry, missed that. Indeed, looks like the error returned from the mock server don't match the structure of real errors (ie the message is an object, not a JSON string). I'm fine with the latest version of your change: I think it's a good idea to stringify and reparse the error (as you did) to avoid any funny business with propagating the same object. I'm surprised that no code under test would break because of the current behaviour.

**Comment by C3POdoo** [comment]
Dear @rrahir,

Thank you for your contribution but the version 14.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
