### PR TITLE
[FIX] website_event: allow editing of short description on Events page

### PR DESCRIPTION
**Pull request by panv-odoo**
Steps to reproduce the issue:

1. Navigate to the Events page.
2. Activate the Web Editor.
3. Attempt to edit the Event's short description.

Issue: The short description of the event was previously not editable directly from the Events page. the reason behind that is they have used `t-out` instead of `t-field` in template. `t-out` lacks the necessary attributes to enable field updates.

Solution: This PR adds the necessary attributes to the short description element, making it editable from the Events page.

Updated the tour functionality to test the latest changes of Event's short description.

task-4014153

### CODE REVIEW

**Review by SergeBayet — CHANGES_REQUESTED** [review]
Thanks for this PR! :+1:  Just two little remarks. In the commit description, it should be Event**s** page, not Event. Also, you mention : "Updated the tour functionality to test the latest changes of Event's short description." ... I don't see anything about it.

**Comment by panv-odoo** [comment]
Hello @SergeBayet,

I'm not sure how this happened, but no worries—I’ve added the tour and implemented the required changes.

Thanks 😃

**Review by SergeBayet — APPROVED** [review]
:+1:

**Review by reth-odoo — APPROVED** [review]
Ouch, great fix thanks

**Comment by SergeBayet** [comment]
@robodoo r+

**Comment by SergeBayet** [comment]
@panv-odoo Don't forget to adapt in master.

**Pull request closed without merging**
