### PR TITLE
[FIX] product: Fixed product's main supplier for multi-company scenario....

### PR DESCRIPTION
**Pull request by rgo-odoo**
...(maintenance: 618809)

Currently in multi-company environment, there is possibility that the procurement may generate the PO with the supplier of other company(which is not accessible by the users of current company and even if the product has a supplier from the current company).

Detailed steps are available at #3833 

This branch fixes this issue, kindly review it.

Thanks.

### CODE REVIEW

**Comment by mart-e** [comment]
closing cf opw 622067

**Comment by PeterA-OpusVL** [comment]
Hi, This still has not been pushed upstream - will this happen any time soon?
Thanks
Peter

**Comment by mart-e** [comment]
Hello,

You have explicitly told us on the support ticket to close it so no, we weren't going to merge it. Moreover this patch does not work as the scheduler runs as the administrator.

**Comment by mart-e** [comment]
alternative fix merged at 20e3f33

**Pull request closed without merging**
