### PR TITLE
[FIX] base: update minifier regexp to rjsmin (1.1.0) 

### PR DESCRIPTION
**Pull request by alexkuhn**
This version adds full support of string templates.
Before this version, rjsmin may produce wrong code with string
templates. For example:

```js
const url = `https://odoo.com`;
console.log(url);
```

was minified to:

```js
const url=`https:console.log(url);
```

Because `//` was wrongly handled as a comment inside the string
template.

### CODE REVIEW

**Comment by VincentSchippefilt** [comment]
why though ?

**Comment by alexkuhn** [comment]
@ged-odoo @VincentSchippefilt Updated commit message.
Without this commit, the minifier produces syntactically incorrect JS when code contains some ES6+ features.

**Comment by ged-odoo** [comment]
Which features? And how did you came up with the regexp?

I suppose that it is an updated version of rjsmin. But then, you should say that.  "Update minifier regexp to rjsmin latest regexp version (1.1.0). This adds support for :

 *) Add support for unnested template literals (ECMA-6). Fixes #8. Kind of.
*) ...

Or something...

**Comment by alexkuhn** [comment]
@ged-odoo Commit message has been updated.

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
