### PR TITLE
crm: sales team graph disappearing issue when the color is changed

### PR DESCRIPTION
**Pull request by jso-odoo**
Description of the issue/feature this PR addresses:
 - Task - https://www.odoo.com/web#id=2036256&action=327&model=project.task&view_type=form&menu_id=4720
- Pad - https://pad.odoo.com/p/r.8f71839be27a82e92926c5bb400ca216

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
@jso-odoo @msh-odoo I slightly changed the fix. Could you take a look, and if it is ok for you, squash commits and retarget to the correct branch? I don't know when the bug appeared, but it works in 12.0.

**Comment by msh-odoo** [comment]
@aab-odoo changes looks good to me as isInDOM will be true until kanban record is not detached, thanks for the changes

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by KangOl** [comment]
@robodoo retry

**Pull request closed without merging**
