### PR TITLE
[FIX] html_editor: dynamic field added at next line

### PR DESCRIPTION
**Pull request by dhba-odoo**
**Current behavior before PR:**

- When adding a dynamic field next to text nodes, the dynamic field would be inserted on the following line.

**Desired behavior after PR is merged:**

- The dynamic field is now added on the same line as the text.

task:4220919

### CODE REVIEW

**Comment by dmo-odoo** [comment]
Are there tests for the dynamic placeholder? If yes then I think this should add a test.

**Comment by dhba-odoo** [comment]
@dmo-odoo I have checked, and there are some test cases available for dynamic placeholders on the web. However, they will not work in our case because they open using **#**, whereas in html_editor, it is not possible to open a dynamic placeholder with **#**.

**Comment by dmo-odoo** [comment]
@dhba-odoo Can't we write one specific for the editor that would open using the powerbox? I mean we already have tests for the powerbox, and there exists some tests for the dynamic placeholder, so we could very well write a new editor test that uses both.

**Comment by dhba-odoo** [comment]
@dmo-odoo added a test case for the dynamic placeholder.

**Comment by dmo-odoo** [comment]
@dhba-odoo Thank you, but unless I'm mistaken, the test does not test against the issue that the fix meant to solve? I did not see a line testing that the dynamic placeholder was inserted at the right place. Did I miss something? The test should be red when ran without the fix.

**Comment by dhba-odoo** [comment]
@dmo-odoo Before my changes, the `data-oe-t-inline` attribute was not applied to the `<t>` element, which caused it to appear on the next line. After the fix, the `<t>` element now includes the `data-oe-t-inline` attribute. Therefore, in the test case, I am verifying that the `data-oe-t-inline` attribute is correctly applied to the <t> element or not.

**Comment by dmo-odoo** [comment]
@dhba-odoo Oh alright, thanks for the explanation and the fix!
@robodoo r+

**Pull request closed without merging**
