### PR TITLE
[IMP] stock: Add group by Destination Location in stock rule search view

### PR DESCRIPTION
**Pull request by tanghulu0608**
Desired behavior after PR is merged:
image

I think this is very useful 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pfertyk** [comment]
Hi @tanghulu0608 and thank you for contributing! I think the code looks good, let me just double-check with my colleagues ;) Meanwhile, could you please shorten the commit title a bit, as described in our guideline?

https://www.odoo.com/documentation/master/contributing/development/git_guidelines.html#commit-message-header

Also, could you please rebase your branch to see if the CI checks are now passing?

**Comment by tanghulu0608** [comment]
@pfertyk Hi, I have changed to title, and rebase to the latest master and force pushed .

**Comment by pfertyk** [comment]
Thank you! I believe, however, that you've changed the title of this PR ;) What I meant is changing the title of the commit itself, using e.g. `git commit --amend` ;) Could you please do this?

Also, I've noticed that your bundle in runbot has a forced base: 15.0. That is probably the reason why tests are not passing ... Did you, by any chance, start this PR with version 15.0 as a target?

I think that the fastest solution is to create a new PR, targeting master, with the same code as here (and with a shortened commit message :P ). Then runbot should pick it up correctly. If you do that, please add a reference to this original PR in the new one.

**Comment by tanghulu0608** [comment]
I have created a new PR #157505

**Pull request closed without merging**
