### PR TITLE
[FIX] sale_service: Allow a project user to close a task which has assigned. Fixes #9286

### LINKED ISSUE #9286: [8.0][BUG] A project user cannot close a task which has assigned
[8.0][BUG] A project user cannot close a task which has assigned

**Impacted versions:**

- 8.0

**Steps to reproduce**

- Login in runbot as Admin
- Go to sales – product and create a product with:
   - Name: service work for imac
   - with product type “Service”
   - go to tab procurements and activate checkbox option “Create task automatically”
   - Select the proyect “Research & development” (for example)
   - Save
- Create a sales order with:
   - Customer  Axelor (for example)
   - Add 2 order lines:
      - First with [A1090] iMac
      - Second with service work for imac
   - Confirm sales order
- Go to setting – users, create a user for example “projectuser@odoo.com” and give permissions only for Project- User, set a password for this user
- Go to Projects task and seach for task that contains text “imac” you will find a task with name SOxxx:services work for imac
- Edit the task and assign it to the user you have created
- Log out as admin
- Log in as the new user you created
- Go to project – task and search again for the same task, go inside the task
- change stage to done
- You will get this error
```
Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Sales/See Own Leads
- Accounting & Finance/Accountant
- Portal
- Warehouse/User
- Manufacturing/User

(Document model: sale.order.line)
```

**Current behavior**

- A project user cannot finish with stage done a task which has been assigned

**Expected behavior**

- Project user with a task assigned must be able to close his/her task

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Comment by rafaelbn** [comment]
In my opinion this is a bug and must be fixed :+1:

**Comment by sergio-incaser** [comment]
Yes... this is a bug, I tested in runbot and all ok. :+1:

**Comment by rafaelbn** [comment]
Please @sergio-incaser check https://github.com/OCA/OCB/pull/364 same PR in OCB Thanks

**Comment by beledouxdenis** [comment]
Thank you for your contribution :).

**Pull request closed without merging**
