### PR TITLE
Extract a method for preparing invoice lines

### PR DESCRIPTION
**Pull request by guewen**
In recurring invoices from contracts.
It allows to inherit and modify the prepared values for the lines.

### CODE REVIEW

**Comment by nim-odoo** [comment]
Hello,
Thanks for the PR. However, we don't really see any added value to extract 20 lines from a method which contains 26 lines... That should not be a problem to override the original method.
Regards

**Comment by guewen** [comment]
Hi @nim-odoo,

I think you miss the value of the `_prepare_*` methods inside a `for` loop.
 
> That should not be a problem to override the original method.

This is a problem actually.

Imagine this use case:
I have a sequence field on the contract lines.
I want to transfer the value of the sequence from the contract lines to the invoice lines.

With the current method, if I would like to add the sequence of each line to the result of `_prepare_invoice_lines`, I can't because I don't have anymore the link between a contract's line and a line of values in the result.

The options you propose are not options actually:
* Overriding the full method means that we can't call `super` so we introduce incompatibilities. 2 modules couldn't override the same method without being incompatible, it is the worst situation.
* Using `super` to get the result, and iterate on the lines to update the values means that we iterate two times on the loop (or 3 times if a third module does that etc.) but also that we are fucked up if any override in the dependency chain adds or remove lines from the values, which is a totally valid use case.

The only option is to extract the inner loop in its own method. Generally, loops and overrides are not best friends and it is IMO a good practice to extract the inner loop as a method.

That being said, could you reconsider this pull request please?

**Comment by rvalyi** [comment]
:+1: I agree with @guewen

**Comment by guewen** [comment]
Just a remark:
The ideal solution would have been to move the loop in `_prepare_invoice` and call `_prepare_invoice_line` directly from there, removing the intermediate `_prepare_invoice_lines`. This is what should have be done at the first place BTW.
I couldn't do that in stable though, that's why I put a new method. If you want, I can add a comment on `_prepare_invoice_lines` saying that it should be moved into `_prepare_invoice`.

**Comment by nim-odoo** [comment]
@beledouxdenis : what is your opinion about it?

**Comment by beledouxdenis** [comment]
I have no problem with this PR, in master.

In a stable release, such as 8.0, changes must be kept to a minimum.
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

We accept proposals that actually solve blocking issues.

We accept time-to-time such kind of refactor in stable, making the overrides easier for the developer, but only if there is no other way to do it.

In this specific case, I believe there is always a way to do it otherwise.

Guewen mentions:
>With the current method, if I would like to add the sequence of each line to the result of _prepare_invoice_lines, I can't because I don't have anymore the link between a contract's line and a line of values in the result.

The number of lines returned by this method is always the number of `recurring_invoice_line_ids`. In addition, the order of the lines is kept. You therefore know that the invoice line at index 2 in the array returned by this method is the contract line at index 2 of `recurring_invoice_line_ids`, and you therefore have a way to make the connection between the result of this method and the contract recurring line.

I strongly agree that this is not ideal, that your way to put it is cleaner, but we simply cannot accept such refactors in stable releases. That would be tons of it. In addition, by doing it in master, you can take the opportunity to make your ideal solution.

Regards,

**Comment by guewen** [comment]
Thanks for reconsidering this and thanks @beledouxdenis for your answer.

My change is kept to a minimum, it doesn't change anything to the logic, it is only a method extraction which has no impact on the stable API. I understand your reasons not to merge when there are other ways to do it, and I insist on the fact that I don't have any safe way to do what I describe.

> The number of lines returned by this method is always the number of recurring_invoice_line_ids. In addition, the order of the lines is kept. You therefore know that the invoice line at index 2 in the array returned by this method is the contract line at index 2 of recurring_invoice_line_ids, and you therefore have a way to make the connection between the result of this method and the contract recurring line.

True, but only when no other module is in between my module and the core module. What if a third module change the order of the lines or add a new line such as for instance a line for interests or whatever. This is the second solution I described above and already explained why I don't want to rely on this uncertain hack relying on the index.

> I strongly agree that this is not ideal, that your way to put it is cleaner, but we simply cannot accept such refactors in stable releases. That would be tons of it. In addition, by doing it in master, you can take the opportunity to make your ideal solution.

True, but my customer are not in master. I am going to propose it on master, still you would make me very happy by accepting this less ideal solution in 8.0, which will have no impact on the stability and won't add any technical debt (due to the 2 methods) as I will do the PR for master ensuring the 2 methods are only on 8.0.

**Comment by beledouxdenis** [comment]
>What if a third module changes the order of the lines or add a new line such as for instance a line for interests or whatever.

You have a point. 

>My change is kept to a minimum, it doesn't change anything to the logic, it is only a method extraction which has no impact on the stable API
Indeed as well.

We are just not fan to merge a proposal that doesn't solve an issue in the standard product. But well, there are examples of useless commits done in stable releases all the time (fc58529616ab7e5ed08de688cab8cf2eb8cb1bde), and you made your points.

@nim-odoo, can you take this from here and merge Guewen's proposal ? Thank you :).

**Comment by nim-odoo** [comment]
ok, I take care of it

**Comment by guewen** [comment]
Thanks a lot! :heart:
I am working on the branch for master right now.

**Comment by guewen** [comment]
Here is the version for master: https://github.com/odoo/odoo/pull/7516

**Comment by guewen** [comment]
Thanks for the merge @nim-odoo

**Pull request closed without merging**
