### PR TITLE
[FIX] l10n_be: add translations in Dutch for tax groups

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
related to opw-1915126

**Comment by pedrobaeza** [comment]
Coming to this from codetriage.com.

@jco-odoo is this going to be continued?

**Comment by mart-e** [comment]
@robodoo r+ I guess

**Comment by mart-e** [comment]
@robodoo rebased r+ please

**Pull request closed without merging**
