### PR TITLE
[FIX] stock: avoid recomputing qty_to_order when not in scheduler

### PR DESCRIPTION
**Pull request by agr-odoo**
Configure a reorder rule and a restock route for a product A
Go to Inventory / Operations / Replenishment
Remove all filters, find product A and under column 'To Order' input a
quantity, then hit the button 'Order Once'

The user quantity will be overwritten by the '_compute_qty_to_order'.
This is a fine tuning of f505444655544379f94a9c8c6a47f358b4880b94

opw-2375317

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@amoyaux 
As the scheduler run with sudo() 
https://github.com/odoo/odoo/blob/55bcd2e96e162a6869b282bf5674e3baed50bf35/addons/stock/models/stock_rule.py#L500
this should be just fine.

On a side note, I don't get if the 'To Order' column has a functional meaning beside the 'Order once' button.

init

Before the [faulty patch](https://github.com/odoo/odoo/commit/f505444655544379f94a9c8c6a47f358b4880b94) that value was actually used by the scheduler.
After this patch, when the scheduler run, that value is overwritten.
Are we ok with this?
Imho yes, because it doesn't seem a good idea to order the quantity each time the scheduler run, but perhaps do we need some advanced logic to keep the user input for some specific case?

cc @nim-odoo

**Comment by amoyaux** [comment]
@agr-odoo The to order column could be informative in other case. But it's mainly useful in this report in order to choose the quantity to order once.

It's quite logical to compute the quantity to order each days. Since it's based on lead time and you need to know the quantity at today + lead days + security days. If your supplier requires 4 days to deliver you need to check 4 days in the future to be on time for delivery.

Personally I would rather move the _compute_qty_to_order to _run_scheduler_task.

**Review by nim-odoo — COMMENTED** [review]
robodoo delegate+

**Comment by agr-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
