### PR TITLE
[WIP][IMP] mass_mailing, web_editor: use bootstrap grids in templates

### PR DESCRIPTION
**Pull request by Zynton**
This brings a series of improvements to the mechanism in place to convert the output html of mass mailing into html that is more compliant with the main mail clients' requirements.

The biggest change is the automatic conversion of Bootstrap grids into table structures. Currently all templates in `mass_mailing` are designed with tables so they work in mailings as is. That has limitations though as it makes it less easy to edit with snippets such as those used in the website builder. This new automatic conversion from Bootstrap grid will allow us to adapt the mailing and snippet templates and be more free within `mass_mailing`.

Note: Because of the limited support of media queries in emails, this doesn't support the mixing and matching of column options (e.g., `"col-4 col-sm-6"` and `"col col-4"` aren't supported).

Other changes include:
- The conversion of Bootstrap cards to table structures
- The conversion of Bootstrap list-groups to table structures
- The conversion of snippets (.o_mail_snippet_general) and mailings
    (.o_layout) into table structures
- The conversion of all rgb colors to hexadecimal
- The conversion of all "rem" sizes to "px"
- Various small corrections to the output styles

The new automatic conversion from Bootstrap grid to tables allows us to convert `mass_mailing` templates from their old table structures to Bootstrap grid (as the reverse conversion will now be applied on save).

General heuristic for the conversion of templates:

|      **Table**      |                **Bootstrap**               |
|:-------------------:|:------------------------------------------:|
|      `<table>`      |          `<div class="container">`         |
|      `<thead>`      |                 _(removed)_                |
|      `<tbody>`      |                 _(removed)_                |
|      `<tfoot>`      |                 _(removed)_                |
|        `<tr>`       |             `<div class="row">`            |
|        `<th>`       |       `<div class="col o_col_head">`       |
|        `<td>`       |             `<div class="col">`            |
| `<td width="_n_%">` | `<div class="col-_o_">` where o ~= 12n/100 |
|    `cellspacing`    | _(removed but always added back to table)_ |
|    `cellpadding`    | _(removed but always added back to table)_ |
|       `border`      | _(removed but always added back to table)_ |

Some styles had to be changed to account for the difference in the HTML.

Mailings were limited to 600px width by default. This removes that limit in order to give snippets control over the margins.

The following snippets (and their relevant options) were added to `mass_mailing`, mostly duplicated from the website builder:

- s_cover
- s_title
- s_text_block
- s_comparisons
- s_color_blocks_2
- s_three_columns
- s_image_text
- s_text_image
- s_picture
- s_features
- s_numbers
- s_masonry_block
- s_media_list
- s_showcase
- s_company_team
- s_call_to_action
- s_references
- s_product_list
- s_features_grid
- s_alert
- s_rating
- s_blockquote
- s_hr
- s_text_highlight

The following snippets were removed to make way for the new:

- s_mail_block_banner
- s_mail_block_title_sub
- s_mail_block_paragraph
- s_mail_block_comparison_table
- s_mail_block_two_cols
- s_mail_block_three_cols
- s_mail_block_image_text
- s_mail_block_text_image
- s_mail_block_image
- s_mail_block_footer_separator
- s_mail_block_footer_tag_line
- s_mail_block_steps

The following standalone snippet options were added, mostly duplicated from the website builder:

- Box
- layout_column
- SnippetMove
- snippet_options_text_align (via web_editor)
- snippet_options_width (via web_editor)
- snippet_options_block_align (via web_editor)
- BodyWidth (based on ContainerWidth but only for the mailing's body)
- minHeight
- so_snippet_addition
- so_content_addition
- sizing_x
- vAlignment

Styles and selectors were adapted to the specifics of `mass_mailing`.

`mass_mailing_table_item` was charged with ensuring proper cloning and removing of table elements precisely because `mass_mailing` relied so heavily on them. Since it doesn't anymore, there is no need for that option. This removes it.

Prior to this PR, it was possible to drop snippets out of the confines of the mailing's body and into its editable parent instead. This makes that impossible.

The feature to drop snippets to the nearest allowed position was broken in iframes because of a reference to a JQuery contained in a different document than the editable area. This restores the feature in all cases.

`we-button`s, `we-toggler`s and `we-select-items` with no text content don't properly take up their full height in iframes. This solves that issue by ensuring a text content at all time, albeit an invisible one. This is a bit of hacky solution perhaps but one that consistently works across browsers.

Transparency is not supported in several leading mail clients. This adds the option to completely remove transparent colors from the palette, and uses that option in `mass_mailing`.

A new, empty template to `mass_mailing` was created, in which snippets can be dropped, to start an HTML mailing from scratch.

A default background color is applied to all HTML mailings in order to emphasize the separation between the mailing itself and its body.

A series of CSS styles were added to the `<head>` of mailings in order to ensure better mail client compatibility.

task-2554899
Enterprise PR: https://github.com/odoo/enterprise/pull/18815

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by edi-odoo** [comment]
Just FYI: 
Media-queries are supported in a quite a few email clients. There has been talk (for a couple of years now) that Outlook is looking into supporting mediaqueries in the near future but they're not there yet. So we can use mediaqueries, we just need a workaround for (mainly) outlook. Gmail on mobile can also be tricky. This is why it's important to test on Litmus ;) 

Webmail | AOL | ❌
Webmail | Gmail | ✔️
Webmail | G Suite | ✔️
Webmail | Yahoo! Mail | ✔️
Webmail | Outlook.com | ❌ 
Webmail | Office 365 | ❌
Desktop | Apple Mail | ✔️
Desktop | Lotus Notes (IMB Notes) | ❌
Desktop | Outlook 2000-2019 | ❌
Desktop | Outlook 2011 (Mac) | ✔️
Desktop | Thunderbird | ✔️
Mobile | iOS Mail | ✔️
Mobile | Gmail App (Android) | ✔️
Mobile | Gmail Android IMAP | ❌
Mobile | Gmail App (iOS) | ✔️
Mobile | Yahoo Android | ✔️
Mobile | Yahoo! iOS | ✔️
Mobile | Outlook iOS | ✔️
Mobile | Outlook Android | ✔️
Mobile | Windows Mail | ✔️

**Comment by Zinston** [comment]
Yes I saw that but figured that Outlook webmail not supporting them, and GMail Android not supporting them with IMAP were deal breakers. That's only 58% of the market that fully supports media queries. https://www.caniemail.com/search/?s=media

**Comment by Zinston** [comment]
Closed in favor of https://github.com/odoo/odoo/pull/77312 to target saas-14.5.

**Comment by kig-odoo** [comment]
Hello @Zinston,

Really nice PR and good improvement.
I've found that nested `row` is not converted to a table correctly. 
I know that the nested `row` structure is not used in default Odoo mailing snippets anywhere. 

I've created a custom snippet with nested `row` and it's looks broken when it converts to the table.
image

Do you have any plan to improve it or do I need to handle it myself?

**Comment by Zinston** [comment]
Hi @kig-odoo,

I just tested and everything worked fine. I believe this must have been one of the fixes brought about with https://github.com/odoo/odoo/pull/80628
Is your database up to date on 15.0 or master? If so please tell me what the original html was so I can reproduce the issue. Thanks.

**Comment by kig-odoo** [comment]
Hello @Zinston ,

I've started exploring the code and found that the row must need to be wrapped by "container". Right now, I'm following nesting structure as per bootstrap https://getbootstrap.com/docs/4.0/layout/grid/#nesting I just wrapped my inner "row" with "container" and now it's working as expected.

I also found a few things. I've tested everything on the fresh runbot build. 

1. Small buttons become large while converting to inline. 
see: https://watch.screencastify.com/v/EX7u9PTZxR5LI3J3ENYV

2. When we design the mail template in full-screen mode the dialogs (media dialog)are opened backside of the screen. It's because the model is appended in the body, not in the iframe.

3. The editor throws the error when you save the record without focusing out the link node
See for points 2&3 https://watch.screencastify.com/v/ir2hBS973az3dlmbryaE

I think the last 2 points are not related to this PR.

Let me know if you need anything from my side. 

BTW, kudos to you and your team for such a huge improvement to make the mailing snippet system more developer-friendly.

**Comment by Zinston** [comment]
Hey @kig-odoo,

> now it's working as expected

Great then! :-)

> 1. Small buttons become large while converting to inline.

I'll take a look but you should know that the Mail Debug tab should actually come with a disclaimer. It's really just for checking the html and that there's no real massive difference, because in fact it doesn't totally make sense: it's a rendering in the browser of html that was specially formatted to render well in email clients. So sometimes you have things that render a bit differently in the browser but are actually correct in the mail client (and, sadly, vice versa).

> 2. When we design the mail template in full-screen mode the dialogs (media dialog)are opened backside of the screen. It's because the model is appended in the body, not in the iframe.

I'll make a task, thanks for reporting this! Damn you iframe... :-)

> 3. The editor throws the error when you save the record without focusing out the link node

That's a separate issue related to the editor, I'll create a task for it.

> BTW, kudos to you and your team for such a huge improvement to make the mailing snippet system more developer-friendly.

Thanks I appreciate it :-)

**Pull request closed without merging**
