### PR TITLE
[FIX] im_livechat: missing user identity after reload 

### PR DESCRIPTION
**Pull request by tsm-odoo**
Since [1], `self` is not returned from `init_messaging` anymore but
added to the backend session infos.

Since the live chat cannot access them, `self` is also returned after
a chat is created. However, this information is missing when reloading
the page.

We cannot add this information in the session because the guest cookie
is not available when loading the page from a different origin: it is
not possible to determine which guest is connected at that time.

This PR fixes this issue by adding this information as part of the
live chat init request.

Steps to reproduce this issue:
- Start a live chat
- Send a message
- Reload the page
- Notice that the message you posted is displayed as if authored by
another user (on the left)

[1]: https://github.com/odoo/odoo/pull/149561

### CODE REVIEW

**Review by seb-odoo — APPROVED** [review]
@robodoo r+ delegate+

**Comment by seb-odoo** [comment]
@robodoo override=ci/security
cors route protected with guest token/downgrade

**Comment by tsm-odoo** [comment]
@robodoo r+, test failing due to incorrect `/im_livechat/init` mocked response (missing `available_for_me` key which is always passed outside of test environment).

**Comment by tsm-odoo** [comment]
@robodoo r+

**Comment by tsm-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
