### PR TITLE
[14.0][FIX] hr_holidays: Add `res_id` to meetings of leaves to be able to archive them when refusing leaves

### PR DESCRIPTION
**Pull request by RachidAlassir**
Description of the issue/feature this PR addresses:
Add `res_id` to meetings of leaves to be able to archive them when refusing leaves

Please check this  [line](https://github.com/odoo/odoo/blob/14.0/addons/hr_holidays/models/hr_leave.py#L898) this is how Odoo uses `res_id` of meetings to fetch the corresponding leaves

[Here](https://github.com/odoo/odoo/blob/14.0/addons/hr_holidays/models/hr_leave.py#L1116) is where Odoo archive meetings
 
Current behavior before PR:
Because meetings of leaves don't have `res_id`, they always exist and are `active` and they keep increasing once refusing and validating several times.
Desired behavior after PR is merged:
Add `res_id` to leaves meetings

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by RachidAlassir** [comment]
@auon-odoo and @mart-e
Please check this PR, I wrote an explanation with links to code lines. Thanks in advance.

**Comment by kba-odoo** [comment]
Hi @RachidAlassir 

Thanks, I'm ok for the fix!
Could you please reword the commit message to be in-line with our [guidelines]? :-) 

[guidelines]: https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#commit-message-header

**Comment by kba-odoo** [comment]
robodoo r+

**Comment by RachidAlassir** [comment]
@kba-odoo Please add `rebase-ff` this PR has a CLA commit that I cherry picked from Odoo v 13.0  (I already have few commits there)

**Comment by RachidAlassir** [comment]
Fixed [here](https://github.com/odoo/odoo/pull/108925)

**Pull request closed without merging**
