### PR TITLE
[FIX] keep the lots when returning a picking

### PR DESCRIPTION
**Pull request by clonedagain**
When users make a return picking, the information about which lot they are returning is already in the database (it's stored in the stock quant) but we didn't pre-record it in the wizard.
As a consequence users had to record the lot by themselves, which is error-prone.
On the other hand the goods could in some cases be returned with another lot, but that seems rather unlikely/abnormal.

This commit splits the wizard in one line per lot and pre-records the lot numbers.

### CODE REVIEW

**Comment by clonedagain** [comment]
@jco-odoo do you think this change is acceptable for 8.0?
It's a small regression with respect to v7 (lots were pre-recorded in the return wizard in v7) and I'm not changing the models.

**Comment by clonedagain** [comment]
@lbellier for your information

**Comment by jco-odoo** [comment]
The lots in the return wizard is simply better not to use and to specify them in the transfer wizard later on.

**Comment by clonedagain** [comment]
I don't see how? If we use FIFO or FEFO, probably the quants that will get reserved won't match the ones we are returning, will they?

**Comment by clonedagain** [comment]
Humm the lots are propagated up to the transfer wizard because the return is a linked move, is that so?

But even then, I think the proposal remains useful: if we send 2 lots of the same product and we want to return 1, at the moment Odoo can't decide which one it will be if we only set the quantity: we must enter the lot, and that's easier if it's pre-recorded.

**Comment by clonedagain** [comment]
Sorry I had closed this PR by accident. I still think it's useful but if you disagree please close it.

**Comment by clonedagain** [comment]
So, did I just fail to convince you? If so, please close this PR.

**Comment by C3POdoo** [comment]
Hello,

This is an automatic message.

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards,

**Pull request closed without merging**
