### PR TITLE
[FIX] base: load translation files in correct dependency order

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Load a translation does load the translation files in an unspecific order unlike the loading in case the modules are installed/upgraded.

**Current behavior before PR:**
No dependency between modules is respected

**Desired behavior after PR is merged:**
Dependency is respected

@mart-e @nim-odoo 
May I ask you to review and merge this?

@Yenthe666 @odony @rco-odoo 
Any thoughts and opinions?

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hi @wtaferner,

Thanks for the PR & suggestion. I'm wondering one thing: should they really be respected? What does it matter that `nl` is loaded before `fr` and not the other way around for example?

**Comment by wtaferner** [comment]
@Yenthe666 
Well, your question is wrong as this PR is not about the loading of a language A before language B, it is about loading language A in module A before module B whereas module A is depending on module B and should be loaded afterwards.

But you are right about the question in general...does it really matter? I was asking myself that question as well, but if I overwrite (i.e. via external_id) for example a record of another module I am not able to overwrite the original translation even though my module is depending and therefore upgraded normally after the other module. So, if I do a base update it does exactly the same thing with the only difference that each language file is loaded after the upgrade of the module and loading the translation files isolated for this module in the "correct" and natural order.

IMHO it is only consistent to do the same on manual request (wizard) to load a translation for overwriting translations or initially loading it in their "correct" order.

I do even see a possible feature for translation improvement here b/c by now it is really difficult to maintain translations by inheritance outside the database. Anyway, as I needed this mechanism I implemented this solution to have control of the correct order how translations will be written in the database and which module will have the last word for a certain term even if it is a term of another module :-)

**Comment by xmo-odoo** [comment]
Why not just use the existing topological sort?

**Comment by Yenthe666** [comment]
Hi @wtaferner,

Reading back my response it was not clear enough. I was meaning the same thing as you explained though.
Yes, this does make sense to me to add then. XMO & RCO will handle this and/or give feedback. 😄

**Comment by wtaferner** [comment]
@xmo-odoo 
Thank you for the pointer, did provide it as you asked for...

**Comment by wtaferner** [comment]
OPW-776928

**Comment by mart-e** [comment]
merged at 088f1e3fdce, thanks

**Pull request closed without merging**
