### PR TITLE
[Fix] Use Bearer Authorization header instead of the URI query-string parameter for Oauth2 Access Tokens

### PR DESCRIPTION
**Pull request by ghost**
Description of the issue/feature this PR addresses:

fixes issue odoo/odoo#63963
closes PR #63970

Current behavior before PR:
- Access Tokens are logged
- URI query-string parameter is used as a placement for the Access Tokens sent to the Oauth2 provider API endpoints

Desired behavior after PR is merged:
- Access Tokens NOT logged
- Bearer Authorization header used instead of the URI query-string parameter

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tvibliani** [comment]
Rebased on merged CLA

**Comment by AdamBark** [comment]
Thanks a lot for doing this @tvibliani! I hope the security team can get it merged soon.

**Comment by designbybeck** [comment]
We're trying to setup OAuth in Odoo v14 as well. @tvibliani does this look like it will be released for v14 or not until v15. We're new to Odoo operations and not sure how Odoo pushes fixes like this. Do they do dot releases? If this doesn't make it into v14 anytime soon we might have to figure out some other authentication. Thank You.

**Comment by tvibliani** [comment]
I would like to answer your question, but unfortunately without any human feedback from Odoo I cannot say anything about that @designbybeck, the only feedback from Odoo I see here is a feedback from the automated bot which blocked the PR. The automated bot may possibly have some bugs, including for example sending messages to a wrong person or failing to notify relevant team or making false positive blocks or some other bugs, which might explain why Odoo is silent in this PR. So I would wait for some human feedback from Odoo before concluding anything. Anyway, I submitted this PR more than a month ago and I did not expected it to take so long. Technically it can be merged into v14, but I have no idea if and when it might be merged by Odoo.

**Comment by tvibliani** [comment]
@fpodoo in cases when PR fails any of automated bot checks, as is a case for this PR, does any human representative from Odoo stuff look into such a PR?

**Review by AdamBark — APPROVED** [review]
This fixes the problem for me

**Pull request closed without merging**
