### PR TITLE
[FIX] website: allow inner form to change background

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Prior to this commit, the inner form snippet had a predefined `o_cc2` color, which could not be changed. This could create layout issues depending on which parent snippet the user dragged this inner snippet onto.

This commit allows to change or remove the background color of this inner form snippet.

task-4206683

| Before | After |
|--------|--------|
| Capture d’écran 2024-09-24 à 11 26 00 | Capture d’écran 2024-09-24 à 11 26 31 |
 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
Hey @stefanorigano 👋 
This small fix is ready to be reviewed, could you have a look ?
Thanks in advance!

**Review by stefanorigano — CHANGES_REQUESTED** [review]
Thanks for your work, @Brieuc-brd! 👍

The proposed implementation partially addresses the problem because, although the inline snippet background color is now editable, its default value should be “transparent.”

Feel free to remove `o_cc2` from the default snippet (the one in the modal) if it’s blocking you from achieving the desired result. Removing the background from that version of the snippet was planned anyway. 😉

**Comment by Brieuc-brd** [comment]
@stefanorigano I removed the color preset, what do you think ?

**Comment by Brieuc-brd** [comment]
Everything seems 🟢 , can we move to tech. review @stefanorigano ?

**Review by stefanorigano — APPROVED** [review]
LGTM 👍

**Comment by Brieuc-brd** [comment]
Hello @odoo/rd-website 👋 
Here's a little fix, could you have a look at it ?
Thanks in advance !

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
@Brieuc-brd This is not enough. I spoke with @stefanorigano about this problem ~2 weeks ago I think, and we agreed on the solution. Maybe there is another PR somewhere about it? If not could someone implement that instead? :pray: 

FYI, here:
1. Your fix does not change the inner form only but the main form snippet too
2. It is still buggy: you cannot make the inner form full width for example:
image
as you could before:
image

3. ...


Solution discussed with @stefanorigano :
- The `s_website_form` snippet (which is the one we had since forever and can be dropped as a main snippet from the snippet dialog or as an inner snippet):
   1. Remove it from the snippet dialog, it will now only handle the inner snippet use case (although, it will still be used as a main one in old databases)
   2. Remove the background color (as you did here)
   3. Make it full-width (as before), so that it fit the area where it is dropped as inner snippet
   4. Remove the included title
- Then, create a new `s_website_form_SOMETHING` to replace the snippet you removed from the snippet dialog. It should:
   - **Contain** an inner `s_website_form`
   - Have a title (as the one you removed earlier :point_up: ) **above** the inner form snippet (not inside)
   - Have a background color (as the one you removed earlier :point_up: )
   - ...

So:
- If something was already done about it, tell me where I'll merge asap :pray: 
- If nothing was done yet, we can do it here :pray: 

Thank you :pray:

**Comment by stefanorigano** [comment]
Hello @qsm-odoo ,

> If something was already done about it, tell me where I'll merge asap 🙏

No time. Our whole team had to shift to themes and priorities were reassigned (as you probably know 😅).
Still, we’re trying to help out with bugfixes when we can.
This PR addresses the most prominent issue and it's an easy/fast one...  though we all agree it’s not a complete fix.

> If nothing was done yet, we can do it here 🙏

I was still planning to fix it "for real" but, as mentioned, time.

If you prefer to don't "touch the snippet" until the new implementation is in place understand that.
It's up to you—either we merge this, and I’ll handle the rest in a future PR as explained in your comment, or we close this without merging, and I’ll take care of everything in the next PR.

For sure BRD will not work on this anymore, he has too much on his place ATM (unless you have just minor suggestions, of course). I will find the time.

Thanks 🙏

**Comment by qsm-odoo** [comment]
@stefanorigano I can do it now if you are ok with it ?

**Comment by stefanorigano** [comment]
@qsm-odoo , ok, thanks for handling this 👍

**Pull request closed without merging**
