### PR TITLE
[IMP] mail: move "isAddingItem" logic from Discuss to DiscussView

### PR DESCRIPTION
**Pull request by oomsveta**
This move will remove the need of the adjustment compute and therefore will avoid writing on computed fields.

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]
squash then good

**Review by alexkuhn — APPROVED** [review]
@robodoo r+

**Review by zel-odoo — COMMENTED** [review]
LGTM for the move. There is one thing for the `clearIsAddingItem()`. It is called by `handleAddChannelAutocompleteSelect()` and `handleAddChatAutocompleteSelect`, which is not only used by the `Discuss` but also `DiscussSidebarCategory`. In that model, there is a field called `isAddingItem` which should also be set to `clear()` logically when calling `clearIsAddingItem()`. But maybe it's not the scope of this PR.

**Comment by alexkuhn** [comment]
> LGTM for the move. There is one thing for the `clearIsAddingItem()`. It is called by `handleAddChannelAutocompleteSelect()` and `handleAddChatAutocompleteSelect`, which is not only used by the `Discuss` but also `DiscussSidebarCategory`. In that model, there is a field called `isAddingItem` which should also be set to `clear()` logically when calling `clearIsAddingItem()`. But maybe it's not the scope of this PR.

`DiscussSidebarCategory/isAddingItem` is equivalent to `DiscussView/isAddingChat` or `DiscussView/isAddingChat`, when in non-mobile (= existence of these category bars).
Would be best to just rely on `DiscussView/isAdding` fields and turn `DiscussSidebarCategory/isAddingItem` into a computed field.

**Pull request closed without merging**
