### PR TITLE
[FIX] purchase: allow to archive cron

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
After an update the cron became active.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@yhu-odoo

**Review by ryv-odoo — COMMENTED** [review]
Hello @fmdl ,
IMO, the cron record shouldn't be update at the upgrade (not only for the `active` field).
Then maybe it is more appropriate by adding `noupdate="1"` (in `<odoo`) instead.
What do you think ?

**Comment by fmdl** [comment]
@ryv-odoo done

**Review by ryv-odoo — APPROVED** [review]

**Comment by ryv-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
