### PR TITLE
Patch for Blind SSRF Vulnerability

### PR DESCRIPTION
**Pull request by aims-khan**
Description of the issue/feature this PR addresses:
I traced blind SSRF Vulnerability in which we can change the host and redirect to any desired host by providing the host IP and port

Current behavior before PR:
We can redirect our url to any host other than the server that the Odoo service is run on

Desired behavior after PR is merged:
Now invalid headers will be stopped from changing the direction of the url and hence the Blink SSRF Vul is patched

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@odony

**Comment by xmo-odoo** [comment]
Would you mind actually explaining what you are talking about, and what your reproduction is?

There should be nothing in Odoo itself which cares for x-host, or x-forwarded-server, and the only thing which cares about x-forwarded-host should be the proxy mode which you seem to be breaking.

**Comment by xmo-odoo** [comment]
> @xmo-odoo sir,
> The current version and previous versions of Odoo is vulnerable to the SSRF Attacks. Anyone can abuse redirection rather than redirecting to /web/login from /web, we can forward the connection to our own local machine or any other

That sounds like an open redirect rather than an SSRF? I still don't understand what you're talking about, or how the hosts are involved.

**Comment by aims-khan** [comment]
@xmo-odoo sir, I'll send a video on your email. If I'm not wrong your email is xmo@odoo.com?

**Comment by xmo-odoo** [comment]
> @xmo-odoo sir, I'll send a video on your email. If I'm not wrong your email is [xmo@odoo.com](mailto:xmo@odoo.com)?

Don't bother sending it to me personally, instead please send a report to security@odoo.com, that is the proper avenue for reporting security issues. I'll close this in the meantime.

**Pull request closed without merging**
