### PR TITLE
Master write back lul

### PR DESCRIPTION
**Pull request by LucasLefevre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pro-odoo — APPROVED** [review]

**Comment by VincentSchippefilt** [comment]
robodoo r+ rebase-ff

**Comment by rrahir** [comment]
@robodoo r+

**Comment by rrahir** [comment]
@robodoo rebase-ff

**Comment by LucasLefevre** [comment]
robodoo help

**Pull request closed without merging**
