### PR TITLE
[12] IMP: translate terms on search view(Group by options for fields date …

### PR DESCRIPTION
**Pull request by celm1990**
…and datetime)

Description of the issue/feature this PR addresses:

**Current behavior before PR:**
image

**Desired behavior after PR is merged:**
image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
and also modify .pot file

**Comment by celm1990** [comment]
@nhomar it is new feature of V12 see commit e1aac71769c8d07a358b2d8717efa28248e18a34

**Comment by celm1990** [comment]
@mreficent translations terms update.
@mart-e you is man here, can please merge this PR?

**Comment by mart-e** [comment]
LGTM, thanks for the patch and changes in the .pot file :+1: 

@robodoo r+

**Comment by mart-e** [comment]
robodoo :robot: r+

@xmo-odoo you broke my editinsteadofposting flow, you monster :disappointed:

**Comment by xmo-odoo** [comment]
> @xmo-odoo you broke my editinsteadofposting flow, you monster 😞

HAHAHAHAHAHAHA

HA

robodoo retry

**Pull request closed without merging**
