### PR TITLE
[FIX] odoo_referral_portal: remove referral portal

### PR DESCRIPTION
**Pull request by alt-odoo**
Small fixup of https://github.com/odoo/odoo/commit/6304c6d0c430f3e02ee84587f18ed5dde5241ecd

Since we removed odoo_referral, we need to remove odoo_referral_portal too.

Description of the issue/feature this PR addresses:
opw-2365878

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo delegate+

**Comment by alt-odoo** [comment]
@robodoo r+

**Comment by alt-odoo** [comment]
@fw-bot disable

**Comment by alt-odoo** [comment]
@fw-bot ignore

**Pull request closed without merging**
