### PR TITLE
[IMP] hr_holidays: align legend labels in calendar view

### PR DESCRIPTION
**Pull request by kpt-odoo**
In this PR we aligned legend labels to the corresponding icon.

task-2784839

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by xavierbol — COMMENTED** [review]
Thanks for your work, I have made a comment. 🙂

**Review by xavierbol — APPROVED** [review]
LGTM, thanks for your work. 🙂

**Review by IT-Ideas — APPROVED** [review]
Thanks 🙂

**Comment by IT-Ideas** [comment]
Hello @kba-odoo 👋🏼 
Are you ok with the changes?
Thanks 🙂

**Comment by kba-odoo** [comment]
LGTM!

Thanks :-)

**Comment by IT-Ideas** [comment]
@robodoo r+

**Pull request closed without merging**
