### PR TITLE
[IMP] New NL chart of accounts (l10n_nl)

### PR DESCRIPTION
**Pull request by astirpe**
Description of the issue/feature this PR addresses:
- replacement of the NL chart of accounts
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Could you please explain your changes? Was the previous one outdated?

cc @StefanRijnhart @ploegvde @NL66278 could you please take a look?

**Comment by ploegvde** [comment]
Hi, This is something we have to test.

@astirpe Can you tell us what the goal of this new COA is? Maybe some background information would be nice.

When i find some time i will give it a test.

**Comment by astirpe** [comment]
This module is meant to replace the actual chart of accounts present in module l10n_nl, that was written by someone who is not available anymore.

It provides a more generic and complete chart of accounts, in conjunction with a overall review of the module. New taxes for service (diensten) are added in the tax template.
The compatibility with the actual NL Vat Statements report is kept.

This new module was written upon explicit request by Odoo SA.

**Comment by StefanRijnhart** [comment]
Is this based on the new reference chart of accounts for the Netherlands (http://www.referentiegrootboekschema.nl/home)?

**Comment by ploegvde** [comment]
@StefanRijnhart As i can see gladly not. It is a project what is going on for years now, but not widely used. Or do you have other experiences? And for that we can better make a separate module, don't you think?

**Comment by ploegvde** [comment]
@astirpe Hi, can you point out to me the use of the new taxes for services. Is this required by the Dutch Tax authorities?

**Comment by StefanRijnhart** [comment]
@ploegvde Chicken/egg situation? I believe it is the way forward.

**Comment by ploegvde** [comment]
@StefanRijnhart It is only forward if people value the solution.

**Comment by StefanRijnhart** [comment]
IMHO the value is that it reflects the required reporting structure in SBR. Declaring annual reports in SBR is obligatory for larger companies in the Netherlands as of 2017 (http://www.sbr-nl.nl/werken-met-sbr/nieuwe-rapportages/kamer-van-koophandel/).

**Comment by ploegvde** [comment]
@StefanRijnhart Ok,l but this is another discussion. I think if someone needs it, we can propose a separate module for this COA. This PR is about improving the existing COA. I think it is we should not choose, but in future the Odoo user can choose what he wants to use.

I'm curious what your opinion is about the improvements.

**Comment by StefanRijnhart** [comment]
I'd have to test. I think the discussion is very much relevant to this change. If the chart is refactored to be more modern and generic as @astirpe states, I would be very interested to follow the new reference COA instead of one party's opinion on this.

**Comment by NL66278** [comment]
I agree that if we adopt a brand new chart of accounts, it would me most logical to follow the reference implementation.

As the reference scheme has both a code and a number, it might be an idea to use the reference code as an xml_id, so we have at least that information.

So account 0101010.02 "Investeringen kosten van oprichting en van uitgifte van aandelen" could be added through xml_id BIvaKouVvpInv (but then all lowercase).

Then we still miss the levels and hierarchy, making the chart of accounts not really a chart anymore - a very unfortunate "feature" of 9.0 I think. But maybe that could be part of a community module.

Anyway, it would be confusing to propose two chart of accounts for the Netherlands, with only one of them based on standards.

**Comment by ploegvde** [comment]
I do not agree. I prefer a one step at a time. Let us first test and see if the improvements made in this PR are useful and if needed a second one. Then people can choice whatever the like.

I do prefer 2 separate chart of accounts. It is not confusing it is a choice you make (most of the time with your accountant). Why forcing users to a system like the reference implementation. In the Netherlands it is still a free choice how you set up you accounting. So please let them.

**Comment by mart-e** [comment]
Sorry, we are not going to change this yet. Need more discussion before doing so.

**Comment by NL66278** [comment]
It is not about taking away choice. It is what you offer by default. It does not take away the possibility to define your own chart of accounts. And if people have one that they think is very usefull and want to share, they can offer it as a community module or just on their own repo' s.

**Comment by astirpe** [comment]
Given he healthy discussion which is aligned with our plans to put this also on OCA. Let's take the discussion from there (OCA). The module is planned to be shared on OCA by the end of the day. You are all invited to continue the discussion over there. Thanks!

**Comment by qdp-odoo** [comment]
wait.. what?

**Comment by NL66278** [comment]
Well just closing the PR means we also miss out on the good things I certainly see, like the more complete tax definition.

**Comment by qdp-odoo** [comment]
yeah, it wasn't meant to be closed...

**Comment by astirpe** [comment]
However, I just opened a PR on OCA:
https://github.com/OCA/l10n-netherlands/pull/47

**Comment by antonylesuisse** [comment]
Is that normal that rubriek 2 is missing, we would like to merge this before v10. Why are all code the diffreent from the v9 one ?

**Comment by ploegvde** [comment]
This PR is not relevant anymore. The new type (it is completely different than the current COA) is moved to OCA. The current OCA is IMHO good enough and needs improvements, but no replacement.

**Comment by astirpe** [comment]
This PR is still relevant, as it's meant to be a replacement of the standard COA of Odoo.
@antonylesuisse Shall I open a new PR to the master branch?

**Comment by ploegvde** [comment]
That is my complain. There are 2 ways of setting up your COA. The current way, that is used by a lot (and i mean a lot) of companies and the new way, but that is not widely adopted.

I agree for a second COA so that you can choose. But a replacement is useless for our company.

Half way trough version 9 we finally had the tax reporting ok. It is now correct.

Don't want to go trough that again.

**Comment by antonylesuisse** [comment]
No need to open a new PR but we plan to merge it in master. @astirpe Is that normal that rubriek 2 is missing, we would like to merge this before v10. Why are all code the diffreent from the v9 one ?

**Comment by ploegvde** [comment]
I think it is not Ok that Rubriek 2 is missing.

Btw: I talked to some people and i'm ok with this proposal.

**Comment by astirpe** [comment]
@antonylesuisse
In the previous COA, the so called 'Rubriek' was the group of accounts, grouped by their code prefix.
So rubriek 2 is missing just because the new COA does not contain any account having a code starting with '2'.

Most of the codes and names of the accounts are different because the account template is completely reviewed.

**Comment by antonylesuisse** [comment]
In belgium the first 2 digits are set by the financial authorities, i.e. all expense account must starts with 6 and all income account must start with 7. Is any numbering allowed in nl ?

**Comment by NL66278** [comment]
In the Netherlands organisations are completely free in how they setup their chart of accounts. However there is a voluntary standardization in the works called the "Reference Chart of Accounts" (Or in Dutch Referentie Grootboek Schema). 

I created a PR to put this RGS in the dutch localization for 8.0. Have to rework this somewhat for 9.0:
https://github.com/OCA/l10n-netherlands/pull/48

**Comment by qdp-odoo** [comment]
landed in revision https://github.com/odoo/odoo/commit/2eecf81a0e1c5b0dac224125abe9d1c8f0164ff9

**Pull request closed without merging**
