### PR TITLE
[FIX] website_sale_digital: get list of digital purchases by a user

### PR DESCRIPTION
**Pull request by kaso-odoo**
The issue occurs when a user tries to download an attachment for a SO.

```
AccessError: Sorry, you are not allowed to access this document.
  File "addons/website_sale_digital/controllers/main.py", line 55, in download_attachment
    request.env['ir.attachment'].browse(attachment_id).check('read')
  File "odoo/addons/base/models/ir_attachment.py", line 446, in check
    raise AccessError(_("Sorry, you are not allowed to access this document."))
AttributeError: 'account.move.line' object has no attribute 'get_digital_purchases'
  File "odoo/http.py", line 2123, in __call__
    response = request._serve_db()
  File "odoo/http.py", line 1699, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "odoo/service/model.py", line 133, in retrying
    result = func()
  File "odoo/http.py", line 1726, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "odoo/http.py", line 1840, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "addons/website/models/ir_http.py", line 234, in _dispatch
    response = super()._dispatch(endpoint)
  File "odoo/addons/base/models/ir_http.py", line 190, in _dispatch
    result = endpoint(**request.params)
  File "odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "addons/website_sale_digital/controllers/main.py", line 60, in download_attachment
    digital_purchases = request.env['account.move.line'].get_digital_purchases()
```

So, when trying to retrieve digital purchases from the `account.move.line` object in  `download_attachment` method because there is a difference in the method call and method definition. see: https://github.com/odoo/odoo/blob/7cd397b81f68ecac2fda5119cae1e1ce4dbfa8cf/addons/website_sale_digital/models/account_move_line.py#L9-L10

https://github.com/odoo/odoo/blob/7cd397b81f68ecac2fda5119cae1e1ce4dbfa8cf/addons/website_sale_digital/controllers/main.py#L60

sentry-4267581957

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kaso-odoo** [comment]
@odoo/sentry_reviewers,
Kindly review this PR,
Thanks!

**Review by yelizariev — APPROVED** [review]
The underscore disappeared  in this commit https://github.com/odoo/odoo/commit/031999ad3443a202ad7c8c722183236db9e9c390

:grimacing:

**Comment by yelizariev** [comment]
cc @Demesmaeker

**Review by Feyensv — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
