### PR TITLE
Master fixes misc 4 tde

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by d-fence** [comment]
robodoo retry please, the Thank you problem is fixed in 12.2

**Comment by tde-banana-odoo** [comment]
robodoo I thought we decided to clean the past and move on with our relationship. It seems you are already back to fighting ...

**Comment by d-fence** [comment]
Cleaning the past is always difficult and a very long road. Did you think about a couple therapy ?

**Comment by d-fence** [comment]
As you see, robodoo seems ready to make a step forward, he shows its good will. I think you should make a step too.

**Comment by tde-banana-odoo** [comment]
I think he is a bit afraid of you... that's why he is less prone to say "sorry tde I won't merge your PR and I hope you will rot in hell " when you are around.

**Pull request closed without merging**
