### PR TITLE
[FIX] account: psycopg2 errors class missing 

### PR DESCRIPTION
**Pull request by agr-odoo**
Traceback when starting odoo server
ImportError: cannot import name 'errors' from 'psycopg2'

Exception management update in commit
https://github.com/odoo-dev/odoo/commit/4b430f8e30efb15f06982e4673cd73531a2119b3
would require psycopg2 version 2.8 minimum but version in
requirements is 2.7.7

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by agr-odoo** [comment]
@william-andre

**Comment by william-andre** [comment]
I don't think we can change the dependencies in stable.
We should just check the `pgcode` I guess :disappointed: 

https://github.com/psycopg/psycopg2/issues/682

**Comment by agr-odoo** [comment]
> I don't think we can change the dependencies in stable.

Indeed, I should have known better

> We should just check the `pgcode` I guess

I adapted the code to check pgcode, it should be good now

**Review by william-andre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
