### PR TITLE
[I18N] *: fix bad placeholder in translations

### PR DESCRIPTION
**Pull request by mart-e**
Some test of cleaning up bad translations, to be propagated on Transifex when the language is available
cc @yelizariev

### CODE REVIEW

**Comment by yelizariev** [comment]
Is it like a demonstration of changes you push to transifex via tx tool?

**Comment by mart-e** [comment]
Hacking around with `polib` to see if we can programatically fix those. The languages that are not on Transifex will be commited, the others will need to be pushed with `tx`.

**Comment by yelizariev** [comment]
You can take some ideas here :wink: 
https://gist.github.com/yelizariev/5cc80c634cce9271132fb141971fe23a#file-fix-translation-py

**Comment by mart-e** [comment]
@robodoo r+

**Pull request closed without merging**
