### PR TITLE
[FIX] stock_account: Use the same decimal precision as the wizard when trying to change the standard price

### PR DESCRIPTION
**Pull request by ysantiago**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hbto** [comment]
👍 

@carlosrve @JulioSerna @nhomar @moylop260 could you give your impressions here.

**Comment by carlosrve** [comment]
@ysantiago @hbto the method do_change_standard_price is only called in the wizard to change standard_price. Why is the wizard not supposed to change the standard price even if the available quantity is zero?

**Comment by hbto** [comment]
@carlosrve good catch.

The that if statement should go with an AND condition:
`if **qty_available and** float_is_zero(diff*qty_available, precision_rounding=product.currency_id.rounding):`


be aware @ysantiago make corrections.

**Comment by ysantiago** [comment]
Ready the change @hbto @carlosrve

**Comment by hbto** [comment]
:+1: This is better fix,

Thanks.

cc/ @carlosrve

**Comment by hbto** [comment]
@carlosrve 

This PR has already been cherry-picked and merged into commit: https://github.com/odoo/odoo/commit/3fed7ff68c27431b482adcaa3b71a692ab99b33b

This PR is not longer valid.

Regards

**Comment by carlosrve** [comment]
@hbto thanks. @ysantiago can you close it then please?

**Pull request closed without merging**
