### PR TITLE
[FIX] website: allow use of custom templates for the website search

### PR DESCRIPTION
**Pull request by pga-odoo**
With commit [1], `qweb.has_template` was replaced with its owl
equivalent. Later, commit [2] further refactored this and consequently
broke the possibility to use custom templates based on search type for
website search.

[1]: https://github.com/odoo/odoo/commit/123ba4ffccd6fc3895a18f3503690ba1593e3023
[2]: https://github.com/odoo/odoo/commit/21ecc7400f2211773713781c619f066a5fb37963

### CODE REVIEW

**Comment by pga-odoo** [comment]
@sdegueldre @jpp-odoo 

With commit https://github.com/odoo/odoo/commit/123ba4ffccd6fc3895a18f3503690ba1593e3023 qweb.has_template get replaced with its owl equivalent. But right now the solution is not working and you can not use custom templates for website search.

I fixed the code by using `getRawTemplate` introduced in the OWL 2.2.9 

Can you please check?

**Comment by jpp-odoo** [comment]
Hello,

Thank you for your fix,

Just with the commit message, I wasn't able to reproduce the issue, could you please send a step by step to reproduce the issue (or better, send a runbot video with the steps).

Thanks

**Comment by pga-odoo** [comment]
@jpp-odoo thank for the quick reply

If you review given code, it used render template with name `website.s_searchbar.autocomplete` + `this.searchType` . If there is no template available it will fall back to rendering `website.s_searchbar.autocomplete`

https://github.com/odoo/odoo/blob/18.0/addons/website/static/src/snippets/s_searchbar/000.js#L148-L153

```js
  let template = 'website.s_searchbar.autocomplete';
  const candidate = template + '.' + this.searchType;
  if (candidate in renderToString.app.rawTemplates) {
      template = candidate;
  }
  this.$menu = $(renderToElement(template, { .....
```

Meaning when you use given option
image

It enables you use templates like 
- `website.s_searchbar.autocomplete.products`
- `website.s_searchbar.autocomplete.blogs`
- `website.s_searchbar.autocomplete.events`
- `website.s_searchbar.autocomplete.jobs`
- `website.s_searchbar.autocomplete.pages`
and more ...

But right now  `candidate in renderToString.app.rawTemplates` always returns False even if templates exist. So we can not use these search teamplates,

So the updated condition will fix the issue and allow custom templates as expected.  See given screenshot 
image

At the moment the it is not possible on runbot as default only use fallback template everywhere, but it will break all customisation from custom module where these templates are added.

**Comment by ged-odoo** [comment]
change looks good to me. question is: should not this be done in 17.0? i guess it is broken as well?
pinging @qsm-odoo on this.

**Comment by qsm-odoo** [comment]
Hello @pga-odoo :wave: 
Could you retarget in the version where the problem first occurs? Thank you for the fix :pray:

**Comment by pga-odoo** [comment]
Hi, @qsm-odoo  

Thanks for the update.
 
I have checked it is working fine until `saas-17.1` and breaks from `saas-17.2`.  
So i have applied a fix targeted to `saas-17.2`.

**Comment by qsm-odoo** [comment]
I investigated a bit more as the commit you mentioned was made in 17.0 so if the bug was only from 17.2, it did not make sense. Found out the issue is actually because of https://github.com/odoo/odoo/commit/21ecc7400f2211773713781c619f066a5fb37963 

I updated the PR description to reflect that for the merge:

@robodoo squash r+

Thanks for the fix :+1:

**Pull request closed without merging**
