### PR TITLE
[IMP] tools convert: add filename in error message of bad schema

### LINKED ISSUE #15869: Error "Document does not comply with schema" should name the faulty XML file.
Impacted versions: 10

Steps to reproduce: Create a module with at least one view XML file that has a non compliant schema

Current behavior: Produces error with Traceback (limited) showing at the end "AssertionError: Document does not comply with schema"

Expected behavior: It should indicate the document which caused the AssertionError, for example: "
AssertionError: Document does not comply with schema: `<path-to-add-on>/views/foo.xml`"

### PR DESCRIPTION
**Pull request by Jerther**
Fixes #15869

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
I really like this PR. It is a new feature so it should probably target master though (cc @mart-e)

**Comment by mart-e** [comment]
As said on #15869, I am not convinced, the name of the file is already logged

**Comment by Jerther** [comment]
No I think you're right. The problematic file is mentioned just above the error but it's not obvious on first sight that the two messages are linked. Having the error and the file on the same line would make the message whole and obvious.

Now that I know, it is indeed obvious but a week ago it wasn't. I even went as far as to make a PR before I noticed ;)

Anyways, to me it's a minor thing.

**Comment by mart-e** [comment]
Ok for a simple improvement. Done at 3553c555e03a6828a1d58b5ef7096e747e5b7f72 (with using the format from logging)

**Pull request closed without merging**
