### PR TITLE
[FIX] mail: avoid using psycopg2 errors submodule (2.8+)

### PR DESCRIPTION
**Pull request by sdegueldre**
We currently support both psycopg2 v2.7.8 and v2.8.5, but the errors
submodule is only available in v2.8+, attempting to import errors from
this module causes crash when running psycopg2 v2.7.8

This commit fixes that by using error checking that is compatible with
v2.7 (catching a more generic exception class and checking the postgres
error code on the caught exception)

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo delegate+

**Comment by sdegueldre** [comment]
@fw-bot ignore

Commit was squashed into the commit introducing the bug during forward port

**Comment by xmo-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
