### PR TITLE
[FIX] pos_restaurant: fix table edition after jQuery 3 update

### PR DESCRIPTION
**Pull request by dmo-odoo**
[FIX] pos_restaurant: fix table editing broken after jQuery update

The table edition feature of pos_restaurant was using an old lib
that was never updated to newer versions of jQuery by its author.

For unknown reason, this library went unnoticed when we updated our
codebase to jQuery 3.

Since this library is impossible to update per se, I decided to
remove it entirely and replace it by calls to jQuery.ui.

However, the point of this lib was to handle touch events, which
jQuery.ui does not. For this, this commit introduces a new
library which translates touch events to their click counterparts.

Tested on:
- Chrome (Windows, MacOS, Linux, Android, iOS)
- Firefox (Windows, MacOS, Linux, Android, iOS)
- Safari (MacOS, iOS)
- Edge (Windows, iOS)
- IE11 (Windows)
- Samsung Internet (Android)

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@aab-odoo It seems to work on desktop. Now we need to test it on a touchscreen device, since this is the reason why another lib was used in the first place... :/

**Comment by dmo-odoo** [comment]
Cross referencing https://github.com/odoo/odoo/pull/31536

**Comment by dmo-odoo** [comment]
@aab-odoo @VincentSchippefilt Shall we merge this then ?

**Comment by VincentSchippefilt** [comment]
robodoo r+

**Pull request closed without merging**
