### PR TITLE
[FIX] core: typo after deprecation of recompute() in 32bc28a 

### PR DESCRIPTION
**Pull request by dzungtran89**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by dzungtran89** [comment]
@rco-odoo  Could you please take a look into this?

Thanks in advance,

**Review by ryv-odoo — APPROVED** [review]
Nice catch! Thank you @dzungtran89

**Review by rco-odoo — APPROVED** [review]
@robodoo rebase-ff r+

**Comment by rco-odoo** [comment]
@dzungtran89 the CLA does not match your email address.  See https://runbot.odoo.com/runbot/build/21508716.

**Comment by dzungtran89** [comment]
> @dzungtran89 the CLA does not match your email address. See https://runbot.odoo.com/runbot/build/21508716.

Hi @rco-odoo , thank you. I fixed the commit author's email

**Comment by ryv-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
