### PR TITLE
[fix] running odoo on Cygwin under Windows 7 - fixes #18944

### LINKED ISSUE #18944: [10.0] when running on Windows on Cygwin ImportError is raised
Impacted versions:
10.0
Steps to reproduce:
Run `odoo-bin` on Cygwin on Windows 7
Current behavior:
Raises ImportError from block at line 23 file: odoo/service/server.py
Expected behavior:
on errors

### PR DESCRIPTION
**Pull request by alpham**
`os.name` = `posix` on Cygwin under windows 7 so this raises errors when trying to import `psutil` which is not supported on Cygwin

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@sle-odoo since you're pretty much the package / requirements guy. Can you have a look?

**Comment by sle-odoo** [comment]
looks harmless, @KangOl ok with that?

**Comment by KangOl** [comment]
I'm not sure it will be enough.
Does the multi-worker works?

on a side note, use `!=` instead of `not ==`

**Comment by alpham** [comment]
@pedrobaeza Changes are done.

**Comment by d-fence** [comment]
Hello in #18944 you mention that this fix is needed to build Odoo as an exe file.
If it's the case, I think that this fix is not needed.
That's the way Odoo 10 for windows in built, without that fix.

**Comment by alpham** [comment]
@d-fence could you please refer to documentation where this way is documented ?

**Comment by d-fence** [comment]
Not needed as Odoo 10 is built as an exe

**Pull request closed without merging**
