### PR TITLE
[IMP] stock_move: do_not_propagate context

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
Description of the issue/feature this PR addresses:

In previous versions of odoo, the write method of stock_move had do_not_propagate context, for handling the propagation of `date` and `date_expected`. 

We have modules relying on this context to work, it could be great if you could add this feature again. 

The changes proposed here, don't change the current standard behavior in any way

Thank you

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @sle-odoo could you have a look here?

Thanks!

**Comment by sle-odoo** [comment]
why not just adapting your rules and set `propagate_date` to false ?

**Comment by LoisRForgeFlow** [comment]
@sle-odoo thanks for pointing that out to us. We have checked and we are still not satisfied.

The specific issue we have is that we are actually rescheduling dates but from downstream to upstream. For instance, in a MTO chain, we reschedule based on the Sales Order delivery and propagate that to upstream related MO's and/or PO's.

As default Odoo reschedules upstream to downstream, we are entering a infinite loop. So the change we are proposing here is more to "disable" default rescheduling for technical reasons. IMO to rely on  "Propagate Rescheduling" (`propagate_date`) for our module is both weak technically speaking and misleading from the functional side (A user would not expect any date change in the chain if propagate_date is unchecked).

**Comment by LoisRForgeFlow** [comment]
@sle-odoo another kind reminder here

**Comment by sle-odoo** [comment]
I'm still not convinced. Why not adding a `downstream to upstream` field on the rule and disable the core propagate_date field?

**Pull request closed without merging**
