### PR TITLE
[IMP] mail: follower ACL followup

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Commit of still-relevant post-merge comments on:
https://github.com/odoo/odoo/pull/70575

task-2804781

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@seb-odoo Zboing !

**Comment by seb-odoo** [comment]
Not wrong but does not really add much value, @alexkuhn do we still want this?

**Comment by alexkuhn** [comment]
Not much value, the introduced related fields do provide any value over just using `followedThread.has[Read/Write]Access`.

**Comment by tde-banana-odoo** [comment]
Ok, I close then ^^ .

**Pull request closed without merging**
