### PR TITLE
[FIX] pos_loyalty: install issue when gift card email template not set

### PR DESCRIPTION
**Pull request by paso-odoo**
When the user removes the Email Template from the 'Gift Cards' program and tries to install the pos_loyalty module, they will encounter a ParseError with the message: `You must set 'Email template' before setting 'Print Report'.` As a result, the installation process will be aborted.

Steps to produce:
- Install the 'Sales' and 'Coupons & Loyalty' modules.
- Sales > Products > Gift cards & eWallet.
- Open the 'Gift Cards' program and remove the Email template from the field.
- Apps > 'Point of Sale - Coupons & Loyalty' > Activate.
- ParseError and stops the installation process.

When the `post_init_hook` method is called during installation, it should check whether the 'Gift Card' program has an Email Template configured.

Traceback:
```
UserError: You must set 'Email template' before setting 'Print Report'.
  File "odoo/tools/convert.py", line 550, in _tag_root
    f(rec)
  File "odoo/tools/convert.py", line 451, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "odoo/models.py", line 4644, in _load_records
    data['record']._load_records_write(data['values'])
  File "odoo/models.py", line 4575, in _load_records_write
    self.write(values)
  File "addons/loyalty/models/loyalty_program.py", line 405, in write
    return super().write(vals)
  File "odoo/models.py", line 4046, in write
    fields[0].determine_inverse(real_recs)
  File "odoo/fields.py", line 1396, in determine_inverse
    determine(self.inverse, records)
  File "odoo/fields.py", line 99, in determine
    return needle(*args)
  File "addons/pos_loyalty/models/loyalty_program.py", line 33, in _inverse_pos_report_print_id
    raise UserError(_("You must set '%s' before setting '%s'.", mail_template_label, pos_report_print_label))
ParseError: while parsing /home/odoo/src/odoo/saas-16.3/addons/pos_loyalty/data/gift_card_data.xml:12, somewhere inside
<record id="loyalty.gift_card_program" model="loyalty.program">
        <field name="pos_report_print_id" ref="loyalty.report_gift_card"/>
    </record>
  File "odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "odoo/modules/loading.py", line 482, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "odoo/modules/loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
  File "odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "odoo/tools/convert.py", line 613, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "odoo/tools/convert.py", line 599, in parse
    self._tag_root(de)
  File "odoo/tools/convert.py", line 563, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
```

Sentry-4356842814

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by paso-odoo** [comment]
@odoo/sentry_reviewers 

Please check this PR. 

Thanks!

**Review by yelizariev — CHANGES_REQUESTED** [review]
I think you should update xml instead and use `<function ... name="write">`. 
Check examples here: https://search.odooism.com/?q=function.*write&i=nope&files=xml%24&excludeFiles=po%24%7Cpot%24%7Cyml%24%7Cyaml%24%7Ccss%24%7C%2Fstatic%2Flib%2F%7C%2Ftests%2F&repos=master

**Comment by paso-odoo** [comment]
@yelizariev 
I have added another commit as per your suggestions.

Thank you!

**Comment by abz-odoo** [comment]
You should put your diff into one commit

**Comment by paso-odoo** [comment]
@abz-odoo 
The requested changes are done!

**Comment by abz-odoo** [comment]
> @abz-odoo The requested changes are done!

why have you removed the first commit ? https://github.com/odoo/odoo/compare/24956b845ea8f21bcfa8b771057017b92501db67..edb8660e555a487dd8d4a06402667120a9be0df2
You didnt want to keep it ?

**Comment by paso-odoo** [comment]
@abz-odoo 
No need for now!

**Comment by abz-odoo** [comment]
hi @rhe-odoo can I have your feedback for this one ? Thanks

**Pull request closed without merging**
