### PR TITLE
[FIX] base: do not load translations twice

### PR DESCRIPTION
**Pull request by rco-odoo**
This fixes former pull request odoo/odoo#78287.

The language installation wizard was invoking `toggle_active()` on the target languages, which loads translations for those languages (with `overwrite=False`), and then loading translations again (with expected parameter `overwrite`).

Simply don't use `toggle_active()`, and directly set the `active` field instead, in order to load translations once with the expected parameter `overwrite`.

### CODE REVIEW

**Comment by VincentSchippefilt** [comment]
we *could* do a test that verifies that there is exactly 3 inserts into `ir_translations` (1 for each type of translations) when calling `lang_install`

**Review by mart-e — APPROVED** [review]

**Comment by tde-banana-odoo** [comment]
> we _could_ do a test that verifies that there is exactly 3 inserts into `ir_translations` (1 for each type of translations) when calling `lang_install`

Indeed this could be a good idea, as it seems some people want to cleanup translations, it would allow to see a bit how it evolves.

Otherwise LGTM :)

**Comment by rco-odoo** [comment]
> we _could_ do a test that verifies that there is exactly 3 inserts into `ir_translations` (1 for each type of translations) when calling `lang_install`

That's incredibly difficult, in fact, because
* the regex that matches the table in INSERT queries is broken;
* there are 4 INSERTs per language per module;
* some modules don't have translations and therefore don't count above.

I will try to monkey-patch the opening of PO files instead, to make sure every PO file is read at most once.

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
