### PR TITLE
[FIX] website: Form editor addon is enterprise

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses: Its badge is missing!

Current behavior before PR: Its badge is missing!

Desired behavior after PR is merged: Its badge is not missing.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa @rafaelbn

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hehe, @Yenthe666 this is just a missing badge for Odoo users to show that this functionality is enterprise . Who could just fix it? Thanks

**Comment by Yenthe666** [comment]
Usually it is @mart-e that merges these things in 😄

**Comment by mart-e** [comment]
Thanks, merged at 055bac5fccd

cc @Icallhimtest https://github.com/odoo/odoo/commit/f90290d1c290c91056306900bdafc6dc418bee65#diff-d7bbfe979a2a7fd8f8a424571aaf73d2R109 😉

**Comment by Icallhimtest** [comment]
Thanks!

**Pull request closed without merging**
