### PR TITLE
[FIX] remove "-->"

### PR DESCRIPTION
**Pull request by elhamdaoui**
**Can you review that please ?**

Description of the issue/feature this PR addresses:
We find "-->" without ""
Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lathama** [comment]
@elhamdaoui knowing that 14 is no longer updated, is this PR still needed?

**Comment by elhamdaoui** [comment]
> @elhamdaoui knowing that 14 is no longer updated, is this PR still needed?

image

Yes because if someone use till today odoo 14.0, he will have this error

**Comment by lathama** [comment]
I just checked and you are correct it is still there. @mart-e would it be impossible to update 14 with this obvious typo?

**Comment by mart-e** [comment]
No sorry, we have deactivated our CI tools for this version, we no longer make changes in it.
We strongly recommend user to upgrade as you won’t benefit by new fixes (including security fixes).

**Pull request closed without merging**
