### PR TITLE
[FIX] website: carousel in snippets auto slide in edit mode

### PR DESCRIPTION
**Pull request by agau-odoo**
task-4134307
opw-4166843
opw-4204546

:warning: this PR requires https://github.com/odoo/odoo/pull/181449 and https://github.com/odoo/odoo/pull/178434 which are not yet merged (18.0 and master, 17.4 is good though).

### CODE REVIEW

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
@agau-odoo I did not check the code but just tested: it seems that you inverted the wanted behavior.

Before the bootstrap update:
- image gallery auto-slide started immediately for the visitor
- carousel & quotes auto-slide started only once the visitor hovered it once (and then stopped hovering)

After your fix here: it's the exact opposite (gallery starts once hovered, the other two start immediately).

Could you restore the way it was before? Thanks :pray:

**Comment by qsm-odoo** [comment]
@agau-odoo (this can probably wait for theme merges first)

**Comment by agau-odoo** [comment]
> @agau-odoo I did not check the code but just tested: it seems that you inverted the wanted behavior.
> 
> Before the bootstrap update:
> 
>     * image gallery auto-slide started immediately for the visitor
> 
>     * carousel & quotes auto-slide started only once the visitor hovered it once (and then stopped hovering)
> 
> 
> After your fix here: it's the exact opposite (gallery starts once hovered, the other two start immediately).
> 
> Could you restore the way it was before? Thanks 🙏

@qsm-odoo  On these runbots, it works as expected https://68319473-saas-17-4-all.runbot159.odoo.com/ https://68319474-saas-17-4-all.runbot159.odoo.com/ (checked on firefox, and it works locally on chromium)

Could you provide exact steps to reproduce?

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
> Could you provide exact steps to reproduce?

There are basically 3 cases:
1. Someone that started in a version before the breaking commit (e.g. someone from 17.0)
2. Someone that started in a version after the breaking commit (e.g. someone from current saas-17.4)
3. Someone that will start after your fix

I initially tested case n°2, which has the problem: I start a current saas-17.4, I add the problematic snippets: their behavior is that they do not auto-slide ever, except gallery after hover => I then apply your fix, and the behavior is the opposite of the normal one. Now... they had broken snippets and suddenly, they kinda work. So it could be ok... but would be better if they get the behavior we wanted for each snippet.

Case n°3 seems indeed fixed but remember that case n°3 is something that no-one will get until they upgrade to the next version (18.0), because most people won't receive the xml updates until then. Ideally, you could patch the snippets in JS (maybe not even touching the XML) so everyone gets the fix.

Case n°1... did not tested. Should an upgrade script be made? What's the plan for `__carouselBootstrapUpgradeFix__`? Your code could use more comments, especially to explain the purpose of the new classes :pray:

**Comment by agau-odoo** [comment]
> Should an upgrade script be made? What's the plan for `__carouselBootstrapUpgradeFix__`?

@qsm-odoo My intuition is that making an upgrade script for 18.1 (for instance) would allow getting rid of this class, and would mean less code to maintain. However, we could also consider keeping this class around until we get rid of bootstrap carousel and just make our own (if that's even something we want to do). I'm not sure how to proceed tbh

I also fixed the 2 upgrade cases (17.2 or less -> fix, 17.4 without fix -> fix).

**Comment by bvr-odoo** [comment]
other opw with the same issue (opw 4242416)
@qsm-odoo Maybe someone else could take that PR.

**Comment by robinlej** [comment]
I found a bug with this fix (using the PR runbot):
- Drop an Image Gallery
- Set a speed
- Add an image
- Click on a carousel indicator
=> Traceback: `TypeError: Illegal invocation`

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
Many comments. I made the adaptations, I'll push-force tomorrow and merge.

**Review by qsm-odoo — APPROVED** [review]
Alright, it's still technically far from perfect with the adaptations I made but it seems ok functionally at least.

> There are basically 3 cases:
> 1. Someone that started in a version before the breaking commit (e.g. someone from 17.0)
> 2. Someone that started in a version after the breaking commit (e.g. someone from current saas-17.4)
> 3. Someone that will start after your fix

I first focused on the first case:
image

Of course, tested case n°3 and works as expected too.

I did not test case n°2 thoroughly. I figured anything is good for that case either way: the customer started in a version where nothing works regarding carousel speed. But I think the result is good anyway.

There are hacks to make it work, and it's probably not robust at all. I am sure there are race conditions etc. We have to:
- In master, properly upgrade broken usecases and remove the JS-upgrade-fix we are making here
- Review the "slider" widget
- Review the dynamic snippet carousel trigger (should simply rely on the "slider" widget if still there)
- Unify the edit mode behavior of gallery and carousel snippets (one blocks options while sliding, the other does not)
- Remove the big hack(s?) made here
- Add tests about all of this to avoid another team breaking all those behaviors again

I'll add that in the current task. We'll close the tickets but keep that one opened.

Let's go with this for now.

@robodoo r+

**Pull request closed without merging**
