### PR TITLE
[FIX] doc: add information about index attribute

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
index have no effect on some fields, it is missing in the doc.

@rco-odoo 
@Yenthe666 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
@Yenthe666 can you add also Documentation label on this PR :
https://github.com/odoo/odoo/pull/32560
https://github.com/odoo/odoo/pull/32559
https://github.com/odoo/odoo/pull/32558

**Comment by Yenthe666** [comment]
Done. :)

**Comment by mart-e** [comment]
Thanks

@robodoo r+

**Comment by mart-e** [comment]
@robodoo retry :pray:

**Pull request closed without merging**
