### PR TITLE
[FIX] web_tour: rainbow_man_message not markup'ed

### PR DESCRIPTION
**Pull request by bastien-ipb**
The markup was done before writing the rainbow_man_message in the localStorage. When getting it back, the markup was lost. Now the markup is done after getting it from the localStorage. And a DOMPurify is used to sanitize the rainbow_message that we got.

TASK-ID: 4206377

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by bastien-ipb** [comment]
@odoo/rd-security Could you re-override this PR (has to re-target to 18.0, see: https://github.com/odoo/odoo/pull/181168)

**Review by jum-odoo — APPROVED** [review]
@robodoo r+

**Comment by mart-e** [comment]
@robodoo override=ci/security

**Review by jum-odoo — COMMENTED** [review]
@robodoo r+

**Pull request closed without merging**
