### PR TITLE
[FIX] base: define fields and templates in any order

### PR DESCRIPTION
**Pull request by jat-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by jat-odoo** [comment]
Oops!

**Comment by dmo-odoo** [comment]
@jat-odoo I think what @aab-odoo meant is that the *branch* names have to be different, not just the PR names.

**Comment by jat-odoo** [comment]
@dmo-odoo @aab-odoo PR having new branch https://github.com/odoo/odoo/pull/33826

**Pull request closed without merging**
