### PR TITLE
index full_reconcile_id

### PR DESCRIPTION
**Pull request by nseinlet**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by qdp-odoo** [comment]
@nseinlet sorry dude, can you rework your commit message to include the model your adding the index on?

[IMP] account: index full_reconcile_id on account.move.line

**Comment by nseinlet** [comment]
@qdp-odoo Done

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by nilshamerlinck** [comment]
Hi @nseinlet 

I stumbled upon this PR while adding the same index on a 12.0.

Looking at its date, it was probably a bit too late to land in 12.0, but worth a backport no?

Regards,

**Comment by qdp-odoo** [comment]
won't do.

**Pull request closed without merging**
