### PR TITLE
[IMP] l10n_es: IRPF fiscal positions

### PR DESCRIPTION
**Pull request by HaraldPanten**
Due to Spanish fiscal positions tax mapping, this improvement includes in IRPF 7%, IRPF 15%, IRPF 18%, IRPF 19% and IRPF 20% both tax mapping (IVA Exento Repercutido & IVA Soportado exento) as it is in IRPF 1%, IRPF 2%, IRPF 9% and IRPF 21%.

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This is missing the new `account_tax_template_s_iva0_ns` and `account_tax_template_p_iva0_ns` taxes

**Comment by HaraldPanten** [comment]
> This is missing the new `account_tax_template_s_iva0_ns` and `account_tax_template_p_iva0_ns` taxes

I'll add them to all the IRPF fiscal positions, then.

I should add `account_tax_template_p_iva0_ns_b` as well, as que have `account_tax_template_p_iva0_ns`(servicios) // `account_tax_template_p_iva0_ns_b`(bienes). Right?

**Comment by pedrobaeza** [comment]
Yes, please

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@oco-odoo can you please check?

**Comment by pedrobaeza** [comment]
Original issue: https://github.com/OCA/l10n-spain/issues/982

**Comment by HaraldPanten** [comment]
Let me recheck tomorrow. I realised I have to change some mapped taxes and I forgot to add these IVA in IRPF 21 fp. Enough for today 👍

**Review by oco-odoo — APPROVED** [review]
Nothing technically wrong with that, and I trust you for the functional side :) 

@HaraldPanten Your last comment seems to mean you still need to check something. Can I merge?

**Comment by HaraldPanten** [comment]
> Nothing technically wrong with that, and I trust you for the functional side :)
> 
> @HaraldPanten Your last comment seems to mean you still need to check something. Can I merge?

I'm still working, sorry. Once I started checking it, I realised that I made some small mistakes. On the other hand, I will improve the order of my last contribution to keep the tax mapping well organised sales//purchases.

I'll try to finish that this week

**Comment by oco-odoo** [comment]
@HaraldPanten No problem, ping me when it's ready :)

**Comment by HaraldPanten** [comment]
> @HaraldPanten No problem, ping me when it's ready :)

Sure!

**Comment by pedrobaeza** [comment]
@HaraldPanten any progress in this?

**Comment by HaraldPanten** [comment]
Hi Pedro,

No news yet. I have the structure "written in my mind" but I couldn't make time to finish this[IMP]. I'll try to finish that this week.

**Comment by HaraldPanten** [comment]
I'll open a new PR for this. I made some mistakes that I prefer to solve in a clean PR @pedrobaeza @oco-odoo 

I'll ping you once it's open

**Comment by pedrobaeza** [comment]
There's no need of new PR if you don't want. You can amend current branch with some git commands.

**Comment by HaraldPanten** [comment]
> There's no need of new PR if you don't want. You can amend current branch with some git commands.

Thanks for your encouraging, I finally solved the git problems 👍

What I did:

- [x] Added "IVA Exento Repercutido & IVA Soportado exento" tax mapping in IRPF positions where it was not mapped before.

- [x] Added account_tax_template_s_iva0_ns, account_tax_template_p_iva0_ns and
account_tax_template_p_iva0_ns_b, in all IRPF fiscal positions. These taxes were not included before.

- [x] Put each mapping in order. Sales taxes with other sales taxes mapping and purchase taxes with other purchase taxes mapping. In my penultimate commit, I didn't realize that mappings were well organized in Sales/Purchase taxes.

Now it's ready to review/merge @pedrobaeza @oco-odoo

**Review by ValentinVinagre — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Hi, @oco-odoo, now this is complete and you can merge it, thanks.

**Comment by oco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
