### PR TITLE
[FIX] mail: impossible to send an email

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
- Create an automated action, send email with a pdf
- Launch action by an user with no access with data made in the pdf
--> Error

### CODE REVIEW

**Comment by fmdl** [comment]
@odony

**Comment by MiquelRForgeFlow** [comment]
A similar case is https://github.com/odoo/odoo/pull/82977.

**Comment by odony** [comment]
Hmm it is sometimes OK to replace a `sudo()` with a `with_user(1)`, but here you're adding one in a place where there was none, so that's not the right place to do it, I think.

**Comment by fmdl** [comment]
@odony what is your solution ?
Serveur action of base.automation are executed with `sudo` but not with `uid=1`.
https://github.com/odoo/odoo/blob/14.0/addons/base_automation/models/base_automation.py#L271

**Comment by mart-e** [comment]
> what is your solution ? It is a regression.

Actually it did not worked in 13.0 (before the changes in report), you had to add a sudo within the report when accessing an object you don't have access to. I think the change needs to be done in the report itself.

**Comment by fmdl** [comment]
@mart-e before the patch of december send email with pdf in auto-action works. Now it doesn't work.

**Pull request closed without merging**
