### PR TITLE
Add NextERP Romania CLA.

### PR DESCRIPTION
**Pull request by feketemihai**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi there,

As I see you are Learning Partner, I take this opportunity to remind you the use of the "Odoo" mark in the company name is forbidden as explained in [the partnership agreement](https://www.odoo.com/documentation/user/13.0/legal/terms/partnership.html#brand-image).
Could you see with your account manager about this to clarify the matter?
Thanks

**Comment by feketemihai** [comment]
@mart-e I agree, i asked about it some months ago with no response, but still they are a lot of visible partners with this issue, so if it's a rule then all should follow it.

**Comment by feketemihai** [comment]
@mart-e please leave it open and i will update after i will change company name. Thanks

**Comment by feketemihai** [comment]
@mart-e I changed the company name and updated the CLA. Thanks.

**Comment by mart-e** [comment]
@feketemihai great, thanks ! Please don't forget to change your git configuration too, you are still making commits with your previous email address

**Comment by feketemihai** [comment]
@mart-e Updated. Thanks

**Comment by mart-e** [comment]
Hello,

Thank you for the update, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Pull request closed without merging**
