### PR TITLE
[CLA] Update Contributors List

### PR DESCRIPTION
**Pull request by leodipasquale**
Cesar Rodriguez is not part of BACG Organization

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by leodipasquale** [comment]
The user "leodipasquale" is already bacgroup CLA.

**Comment by salvatoretrimarchi** [comment]
Please review

**Comment by salvatoretrimarchi** [comment]
Also (Osvaldo Jorge Gentile) Added to Bacgroup CLA

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing using the address `leodipasquale@users.noreply.github.com` and `salvatore...@gmail.com` (belonging to a different CLA)
- you are signing for the address `og...@bacgroup.net`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-email-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by salvatoretrimarchi** [comment]
salvatoretrimarchi update principal email address to trimarchi@bacgroup.net

**Comment by leodipasquale** [comment]
sorry, my email was not public, now it is. dipasquale@bacgroup.net

**Comment by mart-e** [comment]
@leodipasquale @salvatoretrimarchi to update your CLA, you must make commits with the emails signing the CLA.

**Comment by salvatoretrimarchi** [comment]
To update CLA, you need new commits in this pull request or do them in new pull request?

**Comment by mart-e** [comment]
Either you rebase & squash all commits with the correct email in this PR or you create a new one with only one commit, as you wish

**Comment by mart-e** [comment]
This PR is a mix of many unrelated commits.
I think you better create a new one with only one commit if you have issues to squash all commits.

**Comment by salvatoretrimarchi** [comment]
Understood, no problem we going to create new pull request for this update.

**Pull request closed without merging**
