### PR TITLE
[FIX] website: avoid crashing when no last_connection_date

### PR DESCRIPTION
**Pull request by RomainLibert**

### CODE REVIEW

**Comment by RomainLibert** [comment]
@dbeguin ping

**Comment by dbeguin** [comment]
@fja-odoo : I think we should use create_date instead if no last_connection_date.
But I would instead check why there would be no last_connection_date has it should always be filled in.
last_connection_date = create_date the first time the user connect and is updated at each action.
So for me, this crash should never happen.
what do you think ?

**Comment by dbeguin** [comment]
@std-odoo : FYI

**Comment by fja-odoo** [comment]
It should never happend since there is a default on it and the only place we update it is in `_update_visitor_last_visit`.
How can we reproduce this bug ? There is a lack of info in the commit message/PR description.
I would thake the last track's visit_datetime if there is no last_connection_datetime but this should never happend.

**Comment by std-odoo** [comment]
@dbeguin @fja-odoo 
You can install social+website, go to website and click on "create visitor"

I've read a little the code and,

When clicking on "create"
- self.ids is empty
- so, when we try to create ``mapped_data``, the dict is empty
- visitor.id is set to the object ``<NewId 0xblablabla>``, but this key doesn't exist in the dict

Maybe can we just replace
```python
for visitor in self:
    last_connection_date = mapped_data[visitor.id]
```

by
```python
for visitor in self:
            last_connection_date = visitor.last_connection_datetime
```
?

**Comment by fja-odoo** [comment]
@std-odoo Ok I see the issue. Previously we had last_connection_datetime in a separate table and needed to do the read_group to get it. I forgot to remove it... You can just remove the read_group and take the data from visitor.
```
@api.depends('last_connection_datetime')
    def _compute_time_statistics(self):
        for visitor in self:
            last_connection_date = visitor.last_connection_datetime
            visitor.time_since_last_action = _format_time_ago(self.env, (datetime.now() - last_connection_date))
            visitor.is_connected = (datetime.now() - last_connection_date) < timedelta(minutes=5)
```

**Comment by lathama** [comment]
@RomainLibert knowing that 13 is no longer updated, is this PR still needed?

**Pull request closed without merging**
