### PR TITLE
[IMP] stock, mrp, repair: locations per company

### PR DESCRIPTION
**Pull request by pimodoo**
Each company should have their own inventory loss, production, scrap and transit locations in order to apply specific accounting configurations.

TASK 1882269

### CODE REVIEW

**Comment by sle-odoo** [comment]
robodoo r+

**Comment by sle-odoo** [comment]
robodoo retry

**Comment by pimodoo** [comment]
@sle-odoo we need to merge the enterprise commit first https://github.com/odoo/enterprise/pull/3071

**Comment by xmo-odoo** [comment]
robodoo retry

**Comment by xmo-odoo** [comment]
@sle-odoo @d-fence apparently robodoo never saw/received the cla check for odoo/odoo (staging 688, still visible on the dashboard). Checking the log I can't find any CLA mention but I don't know if runbot logs anything when checking/sending CLA info.

**Comment by sle-odoo** [comment]
finally

**Pull request closed without merging**
