### PR TITLE
[ADD] ramiadavid CLA

### PR DESCRIPTION
**Pull request by ramiadavid**

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by ramiadavid** [comment]
@mart-e 
Hello, is there a problem with the signature? It has been 24 days and it has not been integrated, I do not know if I have to do something else or if I just have to wait

**Comment by mart-e** [comment]
@ramiadavid thanks for the message, it was indeed blocked. I have restarted it and it's now merged.
Thanks

**Comment by ramiadavid** [comment]
Tanks! This signature also works for odoo enterprise, or do I also have to sign in the other repository?

**Comment by mart-e** [comment]
No it will work there as well, as long as you use the same email address as in the CLA to make your commits

**Comment by ramiadavid** [comment]
If I already have a PR in enterprise, do I have to do something to detect the signature or is it automatic? Is this signature only for v14 or does it also work for v15, I'm sorry for so many questions, but I don't know how it works,

**Pull request closed without merging**
