### PR TITLE
[FIX] *: typos, wording

### PR DESCRIPTION
**Pull request by mart-e**
Courtesy of translators

### CODE REVIEW

**Comment by Swapnesh-SerpentCS** [comment]
@mart-e  
Adding Few more (Not sure If this has been handled or not)

```
checkings
certifiacte
Currenly
dictionnary
abling
successfuly
Recursivity
emploee_id
```

**Comment by mart-e** [comment]
@Swapnesh-SerpentCS but these are not in translatable content. Some like `certifiacte` are in code comment which is not a big deal.

**Comment by mart-e** [comment]
robodoo r+

**Comment by Swapnesh-SerpentCS** [comment]
Yes True, But still they are typos maybe @mreficent  would like to Fix those too

**Comment by mreficent** [comment]
hahaha of course 🍺

**Comment by mart-e** [comment]
I prefer if we avoid mass replace for the sake of code comments cleaning. This does not bring much and increase noise (which creates conflicts during forward port,...)

**Comment by Swapnesh-SerpentCS** [comment]
> I prefer if we avoid mass replace for the sake of code comments cleaning. This does not bring much and increase noise (which creates conflicts during forward port,...)

Then how do we fix those?
Comment on PR when someone is touching this ?

**Comment by mart-e** [comment]
>  Comment on PR when someone is touching this ?
Yes, usually it is a good time to remove them.

> Then how do we fix those?
But why do you want to fix them in the first place? It is something only some developers will see, it does not cause any issue (while changing it may)

**Pull request closed without merging**
