### PR TITLE
[FIX] web: use full width for the onboarding banner

### PR DESCRIPTION
**Pull request by smottet**
Screenshot from 2021-10-11 14-36-41
The owl OnboardingBanner component should be full width.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by smottet** [comment]
@kebeclibre

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
Note for self: the new banner wraps the html returned by the banner route call in a `div`, which doesn't take full width by default. The older banner doesn't wrap the content in a div, that's the difference.

**Comment by aab-odoo** [comment]
robodoo retry

**Comment by qsm-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
