### PR TITLE
[FIX] account: speedup invoice posting

### PR DESCRIPTION
**Pull request by Aurelienvd**
Given the following testing database configuration:
   - Installed modules: stock,stock_account,purchase,sale_management, account,account_accountant,l10n_generic_coa
   - Anglo-saxon accounting turned on
   - All product categories' property_valuation set to real_time

The following steps:
 - Create 80 storable products
 - Purchase each product to have enough in stock
 - Create and Confirm an SO with one SOL by product
 - Deliver products
 - Create Invoice (should have one line by SOL)
 - Post Invoice

lead to a significant slowdown. Up-to 5min30 to post the whole invoice.

A possible way to speed that up, at least in some cases, is to group the lines in `account_move_line._sync_invoice` by amount_currency and currency_fields. And then call `__set__` on all the lines with the same key at the same time, instead of one by one in the for loop.

In the best cases, this can lead to a speed up of factor 10-20.

#### Speedup
Timing of posting the invoice w.r.t. the number of unique amount currency, with constant currency fields.

| Number of Lines | Unique amount currency | Before PR | After PR |
|:----------------------:|:--------------------------------:|:--------------:|:-----------:|
| 80 | 80 | 5min30s | 5min36s |
| 80 | 40 | 5min36s | 3min |
| 80 | 20 | 5min36s | 1min30s |
| 80 | 5 | 5 min 30s | 32.76s |
| 80 | 1 | 5 min 30s| 16.82s |

Check for perf regression for small invoices with different amount currency:
- invoice with `|line_ids| = 1`: 271ms -> 293ms
- invoice with `|line_ids| = 3`: 469ms -> 372ms
- invoice with `|line_ids| = 5`: 526ms -> 608ms

The customer database linked to this ticket has on average 83 lines by invoice and 4 unique amount currency
so their expected speed up factor should be around 10.

opw-3135002

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Aurelienvd** [comment]
@odoo/rd-accounting Hello, could someone have a look at this PR when they have the time ? Thank you !

**Review by william-andre — COMMENTED** [review]
> A possible way to speed that up, at least in some cases, is to group the lines in `account_move_line._sync_invoice` by amount_currency and currency_fields. And then call `__set__` on all the lines with the same key at the same time, instead of one by one in the for loop.

This seems like a very specific fix for a specific use case.
I would not expect many databases to have multiple lines with the same price and currency...

It would be nice to know what is slow.
I ran this test after installing all the modules you mentioned
```python
    def test_invoice_perf(self):
        import time
        start = time.time()
        move = self.env['account.move'].create({
            'move_type': 'out_invoice',
            'partner_id': self.partner_a.id,
            'currency_id': self.company_data['currency'].id,
            'invoice_date': '2020-02-02',
            'invoice_line_ids': [
                Command.create({
                    'price_unit': i,
                    'name': f"{i}",
                })
                for i in range(400)
            ]
        })
        move.action_post()
        print(time.time() - start)
```

It prints `4.5630` (for 400 lines with different amounts).
The time is doubled (because there is twice the amount of lines) if I run it inside of `TestAccountMoveStockCommon`, by setting `self.product_A` on all the lines.

Isn't this an issue in the client's code?

**Comment by Aurelienvd** [comment]
@william-andre 

Actually the commit that you made and was merged yesterday https://github.com/odoo/odoo/commit/b3d60185 gave
a huge performance boost to this issue. I'm not really sure why but it's now faster than with this PR's fix so I guess I can close it 😅 
> 
> ```python
>     def test_invoice_perf(self):
>         import time
>         start = time.time()
>         move = self.env['account.move'].create({
>             'move_type': 'out_invoice',
>             'partner_id': self.partner_a.id,
>             'currency_id': self.company_data['currency'].id,
>             'invoice_date': '2020-02-02',
>             'invoice_line_ids': [
>                 Command.create({
>                     'price_unit': i,
>                     'name': f"{i}",
>                 })
>                 for i in range(400)
>             ]
>         })
>         move.action_post()
>         print(time.time() - start)
> ```
> 
> It prints `4.5630` (for 400 lines with different amounts)
> 
> Isn't this an issue in the client's code?

For an invoice with 200 lines, it still takes around 1min40s to post in a testing v16 database with standard modules. Is the method `_stock_account_anglo_saxon_reconcile_valuation` called in your example here ? 

Here is a flamegraph for this invoice posting in case you see something obvious that I don't: 

16 0_invoice_post

**Comment by william-andre** [comment]
I had a suspicion that that commit might have had an impact when seeing that you were setting the env `skip_invoice_line_sync` everywhere indeed, but I wasn't sure since it is not obvious that it prevents the recursion of that part of the code.

**Comment by Levizar** [comment]
Just passed by and saw the flame graph.
I saw that one of the longest function triggered was the creation of the full_reconcile_id.
Wouldn't that be faster if those creations were batched instead of being done each time in the for loop?

**Comment by william-andre** [comment]
@Levizar Yes, @smetl has a wip branch to do that

**Pull request closed without merging**
