### PR TITLE
[CLA] Savoir-faire Linux Update

### PR DESCRIPTION
**Pull request by jbchouinard**
Update list of contributors at Savoir-faire Linux.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jbchouinard** [comment]
@joaoalf looks ok?

**Comment by mart-e** [comment]
Hello,

Thank you for the update but could you:
- commit with the same email address as the one you are signing for (explaining the failing test)
- do not remove old employees. You can mark them as outdated (e.g. "up to 2017-05-11") but you must keep them to show that, at the time of their contribution, they had signed the CLA

Thanks

**Comment by jbchouinard** [comment]
@mart-e I think it's ok now? I'd like to merge so we can merge #16959

**Comment by mart-e** [comment]
Yes looks good now. Maybe you want to set the previous employees at the end of the CLA if the list grows over time.

Before merging, this PR targets master but  #16959 targets 10.0. Which one is correct?

**Comment by jbchouinard** [comment]
@mart-e good point about ordering.

for now I need to do a PR on 10.0, but our contributors are the same for all versions of odoo, do I have to make a PR for each major branch?

**Comment by mart-e** [comment]
We forward port the code and CLA. So if you sign for 9.0, it will apply for 9, 10 and master. Let me know in which version do you want me to merge the CLA

**Comment by jbchouinard** [comment]
@mart-e if I target 8.0 it will be forwarded to 9.0 and 10.0?

**Comment by mart-e** [comment]
yes

**Comment by mart-e** [comment]
Thanks, merged at https://github.com/odoo/odoo/commit/43be0c1ab2357045b3f4872b4db80ac66d14606c
Will be in 10.0 in a few days

**Pull request merged**
