### PR TITLE
Replaced intersect() with a faster set intersection

### PR DESCRIPTION
**Pull request by ccomb**
While doing some profiling on a unittest, I noticed a lambda function executed 100.000 times, and taking a total of 1.2s on a total of 18s.
Just by replacing the intersect() function with a list comprehension and no function call, the processing time is more than 50% lower.

Here is a sample script to show the difference with different implementations:

```
import time


def intersect(la, lb):
    return filter(lambda x: x in lb, la)


def intersect2(la, lb):
    return [i for i in la if i in lb]

a = time.time()

for i in xrange(10**6):
    intersect([1, 2, 3], [3, 4, 5])

print time.time() - a 

a = time.time()
for i in xrange(10**6):
    filter(lambda x: x in [1, 2, 3], [3, 4, 5])
print time.time() - a 

a = time.time()
for i in xrange(10**6):
    list(set([1, 2, 3]) & set([3, 4, 5]))
print time.time() - a 

a = time.time()
for i in xrange(10**6):
    [i for i in [1, 2, 3] if i in [3, 4, 5]]
print time.time() - a 

a = time.time()
for i in xrange(10**6):
    intersect2([1, 2, 3], [3, 4, 5])
print time.time() - a 
```

0.893498182297
0.649670124054
0.908890008926
0.427963018417
0.490713119507

### CODE REVIEW

**Comment by ccomb** [comment]
Real data show that la is larger than lb, so I've done other tests 

```
import time
import sys
u = range(int(sys.argv[1]))
v = range(int(sys.argv[2]))
loops = 10**5


def intersect(la, lb):
    return filter(lambda x: x in la, lb)


def intersect2(la, lb):
    return [i for i in lb if i in la]


def intersect3(la, lb):
    return list(set(la) & set(lb))


def intersect4(la, lb):
    return list(set(lb).intersection(la))


def intersect5(la, lb):
    sla = set(la)
    return [i for i in lb if i in sla]


t = time.time()
for i in xrange(loops):
    intersect(u, v)
print time.time() - t

t = time.time()
for i in xrange(loops):
    intersect2(u, v)
print time.time() - t

t = time.time()
for i in xrange(loops):
    intersect3(u, v)
print time.time() - t

t = time.time()
for i in xrange(loops):
    intersect4(u, v)
print time.time() - t

t = time.time()
for i in xrange(loops):
    intersect5(u, v)
print time.time() - t
```
Results:
```
ccomb@ccomb:buildout$ python ../intersect.py 106 2
0.0672559738159
0.0312399864197
0.324390172958
0.161643028259
0.278992891312
ccomb@ccomb:buildout$ python ../intersect.py 106 66
2.18014097214
1.96366095543
0.652776956558
0.434652090073
0.631084918976
ccomb@ccomb:buildout$ python ../intersect.py 75 2
0.0708208084106
0.0311758518219
0.224468946457
0.144014835358
0.186643123627
ccomb@ccomb:buildout$ python ../intersect.py 8 41
0.60001707077
0.362504005432
0.218513965607
0.193431138992
0.212734937668
ccomb@ccomb:buildout$ python ../intersect.py 170 70
2.39776802063
2.1326649189
0.775053024292
0.529557943344
0.788856983185
ccomb@ccomb:buildout$ python ../intersect.py 106 1
0.0613000392914
0.0269470214844
0.330909967422
0.149574041367
0.288604974747
```

As a result, the most balanced and uniform implementation seems to be the number 4.
I found cases where we fall on the 170-70 example, and the difference is noticeable.
The unordered sets are no problem here since the intersect function is run on dict.keys() anyway...
I'm pushing a new commit with the implementation 4.

**Comment by yvaucher** [comment]
:+1:

**Comment by xmo-odoo** [comment]
As far as I can see, most of the `list()` calls aren't necessary, the output is either just tested for emptiness or iterated on, indexability seems irrelevant.

**Comment by ccomb** [comment]
You're right, but I took a conservative approach, and kept the same type, because I don't know if other parts of the code works with any iterable object, or expect a real list through an isinstance() call.
Just grep ``isinstance(*, list)`` in the server code and you'll see what I'm talking about...

I've seen the same problem with ids everywhere in the beginning of the model methods, through a call to isinstance() being int or long.

**Comment by ccomb** [comment]
If you're 100% sure there is no problem removing the list() call in those places, that would be even better.  We must just check that the set cannot not go out to custom code.

**Comment by ccomb** [comment]
We would gain a raw additional local improvement 2 to 5% (30 to 100ms less on a total of 1.5s for 100k calls with 700-3 and 700-70 fields), which corresponds to a real life gain of 0.2 to 0.5% on my 15s unittest. That's small but not totally negligeable IMO.

**Pull request closed without merging**
