### PR TITLE
mrp module: Replace 'self.production_id.product_qty' with 'self.qty_production'

### PR DESCRIPTION
**Pull request by Loney-Cao**
Description of the issue/feature this PR addresses:
Replace 'self.production_id.product_qty' with 'self.qty_production'
Current behavior before PR:

```
qty_production = fields.Float('Original Production Quantity', readonly=True, related='production_id.product_qty')
...   

if float_compare(self.qty_produced, self.production_id.product_qty, precision_rounding=rounding) >= 0:
```

    
Desired behavior after PR is merged:

Why not use 'self.qty_production' instead of ‘self.production_id.product_qty’ ?
```
if float_compare(self.qty_produced, self.qty_production, precision_rounding=rounding) >= 0:
```
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hi,

> Why not use ...

You are right, these are equivalent. We could have use them but it does not cause any issue to use the full path.
Please check our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean), in stable versions (like 12.0), we only accept bug fixes, not code cleaning.

If there is no bug found by using this version, let's not change it.

Regarding the CLA, it is still failing because you are making commits with your inspur email address, this is the one you should use in your CLA signature.
Inspur already have [a CLA file](https://github.com/odoo/odoo/tree/12.0/doc/cla/corporate/inspur.md), you can simply add an entry in this file instead.

**Comment by Alone-Tree** [comment]
Hello, sir. 
        I am very happy to receive your reply.  I am sorry to take up your precious time.  For some reason, this need to be modified. Please read the content


Before:





Set a qty producing






After:






When I modify the field, I have to re-create a new method.This is too redundant, not a good design.


like this :



For secondary development, this is not friendly。


Thank you very much for reading, and finally I wish you a happy life.






------------------ 原始邮件 ------------------
发件人: "Martin Trigaux"<notifications@github.com>;
发送时间: 2019年9月18日(星期三) 晚上9:41
收件人: "odoo/odoo"<odoo@noreply.github.com>;
抄送: "磨刀嚯嚯向MM"<897728638@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [odoo/odoo] mrp module: Replace 'self.production_id.product_qty'with 'self.qty_production' (#37042)




Hi,
  
Why not use ...
  
You are right, these are equivalent. We could have use them but it does not cause any issue to use the full path.
 Please check our stable policy, in stable versions (like 12.0), we only accept bug fixes, not code cleaning.
 
If there is no bug found by using this version, let's not change it.
 
Regarding the CLA, it is still failing because you are making commits with your inspur email address, this is the one you should use in your CLA signature.
 Inspur already have a CLA file, you can simply add an entry in this file instead.

**Comment by mart-e** [comment]
@Alone-Tree could you please check you message, it seems there is content missing. I don't recommend you to use the email to reply with code, it got stripped. Use github interface instead.

**Comment by Alone-Tree** [comment]
> @Alone-Tree could you please check you message, it seems there is content missing. I don't recommend you to use the email to reply with code, it got stripped. Use github interface instead.

**Before:**

**_Set a qty producing_** 

```
class MrpWorkorder(models.Model):
    _name = 'mrp.workorder'
    _description = 'Work Order'
    _inherit = ['mail.thread']
    ... 
    ...

    qty_production = fields.Float('Original Production Quantity', readonly=True, related='production_id.product_qty') 

    @api.multi
    def record_production(self):
        ....
        ....
        # Set a qty producing
        rounding = self.production_id.product_uom_id.rounding
        if float_compare(self.qty_produced, self.production_id.product_qty, precision_rounding=rounding) >= 0:
            self.qty_producing = 0

        ...

```

========================================

**After:**
**_Set a qty producing_**
When I modify the field, I have to re-create a new method.This is too redundant, not a good design.

like this :

```
class PsMrpWorkOrder(models.Model):
    _inherit = 'mrp.workorder'

    qty_production = fields.Float('Original Production Quantity', related=False)

    @api.multi
    def record_production(self):
       ....
       ....
        # Set a qty producing
        rounding = self.production_id.product_uom_id.rounding
        if float_compare(self.qty_produced, self.qty_production, precision_rounding=rounding) >= 0:
            self.qty_producing = 0
        ...
```
For secondary development, this is not friendly。

**Comment by mart-e** [comment]
Thanks for the information, I see your point but there is still no bug in the standard code so should not target the 12.0.
If you retarget to saas-12.5 (which will be the future 13.0), I can accept it there.

For the CLA, you are still making commits with your inspur email address, this is with this one that you have to sign the CLA.

**Pull request closed without merging**
