### PR TITLE
[FIX] link_tracker: Do not die if statistic was unlinked

### PR DESCRIPTION
**Pull request by yajo**
[There's a chance mail statistics disappear](https://github.com/odoo/odoo/blob/b3b8a471cc3e02488dcc0da991fd1d828978220d/addons/mass_mailing/models/mass_mailing.py#L519), which is probably not a very good decision, but there it is.

Then, `add_click()` produces a 500 error when a user clicks on the mass mailing if the email comes from an old attempt.

<details>

<summary>500 error logs</summary>

``` 2018-01-23 09:49:50,217 350 INFO prod odoo.sql_db: bad query: INSERT
INTO "link_tracker_click" ("id", "ip", "mail_stat_id", "country_id",
"link_id", "create_uid", "write_uid", "create_date", "write_date")
VALUES(nextval('link_tracker_click_id_seq'), '10.63.200.15', 494477, NULL,
974, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC' ))
RETURNING id 2018-01-23 09:49:50,224 350 INFO prod werkzeug: 192.168.2.10
- - [23/Jan/2018 09:49:50] "GET /r/wne/m/494477 HTTP/1.0" 500 - 2018-01-23
09:49:50,233 350 ERROR prod werkzeug: Error on request: Traceback (most
recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line
193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line
181, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 184,
in application
    return
werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ,
start_response)
  File
"/usr/local/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line
152, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 172,
in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1308, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1282, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line
599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1481, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/custom/src/odoo/addons/website_sale/models/ir_http.py",
line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/custom/src/odoo/addons/website/models/ir_http.py", line
218, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/opt/odoo/custom/src/odoo/addons/web_editor/models/ir_http.py",
line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/custom/src/odoo/addons/utm/models/ir_http.py", line 20,
in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/ir/ir_http.py", line
199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/custom/src/odoo/addons/website/models/ir_http.py", line
270, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/ir/ir_http.py", line
169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 768, in
_handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/ir/ir_http.py", line
195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 333, in
_call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 143, in
wrapper
    raise ValidationError(msg) ValidationError: (u'No puede completarse la
operaci\xf3n, probablemente debido a lo siguiente:\n- eliminaci\xf3n: es
posible que est\xe9 intentando eliminar un registro mientras que otros
registros todav\xeda tengan referencias a \xe9l\n-
creaci\xf3n/actualizaci\xf3n: un campo obligatorio no se ha introducido
correctamente\n\n[objeto con referencia: Email Statistics - mail.mail.statistics]', None)
```

</details>

With this fix, we check mail statistics existence before saving it. BTW, I fixed the wrong `creation_date` usage, which should have been using `click_date` in the first place. Possibly `click_date` is unnecessary, but it's there, so let's use it properly.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Yenthe666 who can attend this PR?

**Comment by Yenthe666** [comment]
Hmm most likely @tde-banana-odoo or @JKE-be - could one of you have a look guys? It looks quite serious.

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by tde-banana-odoo** [comment]
Hello,

I don't fully understand. How does it crash if a m2o is set to False ? It is if you add a click while at the same time the record is removed ? Shouldn't we use exists in that case to ensure everything is ok ?

Moreover I wonder if we should not backport 7accd77999ebcd4ce16388f2a23ee296093fecbc . Indeed we are adding values for fields that do not exist in link tracker.

**Comment by pedrobaeza** [comment]
It crashes because of a required constraint on any of the tables. I don't have right now the details, but if you need them, I can check it.

My colleague @Yajo can also confirm if the backport would serve. Jairo, would you?

**Comment by Yajo** [comment]
> I don't fully understand. How does it crash if a m2o is set to False ? It is if you add a click while at the same time the record is removed ? 

Yep, the problem is when a user clicks on any link in any email after the statistic has been removed from database. It's not that it's getting a `False` value, but a missing id instead.

> Shouldn't we use exists in that case to ensure everything is ok ?

It's another option, yes.

> Moreover I wonder if we should not backport 7accd77 . Indeed we are adding values for fields that do not exist in link tracker.

Certainly that was a weird design, but I decided not to change it in the patch, to keep a minimal diff. The backport would be welcomed, although I fear it would still get the same failure due to [also adding `mail_stat_id` without checking existence](https://github.com/odoo/odoo/commit/7accd77999ebcd4ce16388f2a23ee296093fecbc#diff-ea4e3cf9ff8860034b2e7725a8a5c246R25).

**Comment by tde-banana-odoo** [comment]
Hello,

Sorry for the delay to answer. Indeed we should keep diff minimal for stable, let us forget the backport. Concerning the issue itself I would add an exists then, it is more explicit. Having a small comment about why we add it would also be welcomed.

Could you also separate the click_data change in another commit ? So that both fixes land in separate commits. It is easier for explanations and if we want to revert part of the fix for some reason, it is easier if fixes are separated.

Does that sound ok for you ?

**Comment by Yajo** [comment]
Yep, done :wink:

**Comment by tde-banana-odoo** [comment]
Hello,

Just a small note. Looking at link tracker fields, it seems create date is displayed in tree view and could therefore be used. It looks like a behavior change to me for a stable. I understand your patch is correct; however in current code click_date is actually never used anywhere.

If you look in website_links JS code actually group clicks by create_date (clicks_by_day). As I don't want to go through website_links, especially in stable, I actually think changing create_date to click_date is not a safe change.

For stable version we could consider merging both fields, keeping maybe only create date if click_date is not used anywhere.

What do you think about that ?

**Comment by Yajo** [comment]
OK, at least I remove it from the field due to saving a wrong value type.

**Comment by rafaelbn** [comment]
Please @tde-banana-odoo could you please take another look into this FIX? Thanks!

**Comment by tde-banana-odoo** [comment]
Hello,

With much love, finally landed in 10 at https://github.com/odoo/odoo/commit/228df6a29f76d9e4d61740987f41744960b127ca and https://github.com/odoo/odoo/commit/8357e7395e0533d5436b7e45311a81daa29caa48 .

I slightly rewrote part of the fix to ensure other values linked to the statistics are set if the statistics exists also.

Thanks,

**Pull request closed without merging**
