### PR TITLE
[FIX] account: remove duplicate company name systray item

### PR DESCRIPTION
**Pull request by Yoann-bary**
Steps to reproduce:
- Archive all but 1 company
- Settings > Quick encoding to 'Customer invoices'

An extra systray item displays the company name, this is redundant with the SwitchCompanyMenu which is always displayed as of this commit dc844df86958d2e31c4e758f600b9c37a8818ca1.

opw-4100655

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

this seems unlikely, so might not be necessary but maybe it would be better to just remove the line:

```py
registry.category("systray").add("AccountSystrayItem", systrayItem, { sequence: 1 });
```
in stable, and to remove everything in master. In the unlikely case (it's more rare that something in JS is customized, and saas-17.4 is recent and only a saas version) that someone was eg. overriding it.

**Comment by Yoann-bary** [comment]
That's a good point, I think in this case it's so niche that complete removal should be fine but I'll keep that in mind in the future

**Review by clbr-odoo — CHANGES_REQUESTED** [review]
The fix is legit but then you need to revert the the whole commit https://github.com/odoo/odoo/commit/776d28b539c3db6154c9d49c55e583e5be5de02f, including the override of `IrHttp`.

**Comment by Yoann-bary** [comment]
I've removed the extra parts

**Review by clbr-odoo — APPROVED** [review]
Thank you !
@robodoo r+

**Pull request closed without merging**
