### PR TITLE
[FIX] website: allow theme customizations by multiple users

### PR DESCRIPTION
**Pull request by tdecaluwe**
When customizing the theme, a customized scss containing the customized variables file is saved as an attachment. This poses a problem when a second user tries to modify the same asset file, having neither read or write access to the attachment. The problem is resolved by allowing superuser access to the attachment for all users having website designer rights.

opw-2722459

### CODE REVIEW

**Review by rdeodoo — CHANGES_REQUESTED** [review]
Do you need to make the sudo that early in the stack?
Isn't patching `_get_custom_attachment()` enough?
Can you check if https://github.com/odoo/odoo/pull/88211 solve the issue?

**Comment by tdecaluwe** [comment]
@rdeodoo I wasn't sure if `sudo` was fine for all flows through `_get_custom_attachment`. But I agree, it does make sense. Adding the `sudo` solves both the opw flow and the flow from the linked PR. The linked PR doesn't work though, because of the assignment on `self`.

**Comment by rdeodoo** [comment]
> The linked PR doesn't work though, because of the assignment on self.

What exactly is not working? Not sure to understand what you mean.
I confirm, the flow trying to be fixed here is fixed there too

**Comment by tdecaluwe** [comment]
@rdeodoo I got a traceback because the `web_editor.toolbar` template cold not be loaded, when trying to open the editor. Removing the `self = self.sudo()` line resolved the problem, so I assumed that was the cause.

**Comment by rdeodoo** [comment]
You just had a cache issue.. `web_editor.toolbar` is a static template.
Following our discussion, you probably switched from 15.0 to 13.0 (and changed the PR target also) and faced that cache issue.

I am not sure how adding rights in python (sudo()) would have anything to do with a static template not loading?

Anyway, your branch is red, can you make it green so we can cherry-pick your test in the other branch? I saw that you copied the fix here but we will merge it in the original PR.

**Comment by tdecaluwe** [comment]
@rdeodoo Ok, I see.

Apparently in 13.0 whitespace doesn't get trimmed (`[(6, 0, [env.ref(g).id for g in groups.split(',')])]`) from the group xml ids in the `new_test_user` method. Should be good on the next build.

**Pull request closed without merging**
