### PR TITLE
FEC show rightful information

### PR DESCRIPTION
**Pull request by kebeclibre**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kebeclibre** [comment]
@smetl 
I think that this is pretty much what you suggested
- all account are present
- the balance is not computed on each line
- the delimiter is protected against

**Comment by qdp-odoo** [comment]
geez.. are you sure you want to include all accounts, even the untouched ones? what about the accounts that are set as 'deprecated'?

the changes with
* protection against pipes in ref field
* kwargs in query formatting
 are welcome
* the balance in debit/credit columns replaced with the total of debit and total of credit
is fine for me too


but for the rest... I'm not sure at all! @alexis-via might have some good insight on this one

**Comment by smetl** [comment]
The protection against pipes in ref field must be done. About the debit/credit columns and including all the accounts, it was confusing for the client but I'm not sure it's really mandatory.

**Comment by C3POdoo** [comment]
Closing as version saas-11 is no longer a supported version.

**Pull request closed without merging**
