### PR TITLE
Fix image error when res.partner avatar is False

### PR DESCRIPTION
**Pull request by antespi**
Description of the issue/feature this PR addresses:

When a portal user goes to any object with chatter (for example, project.issue) and his partner has no avatar defined, then an error image is displayed on every message written by him.

Versions: runbot v9c, runbot v10c

Current behavior before PR:

In v9c, a browser error image
In v10c, a 1x1 pixel image

Desired behavior after PR is merged:

A placeholder image displayed, like web addon does in `content_image` controller.
In this PR, web addon logic is reused.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@JKE-be perhaps you can look at this? I like it.

**Comment by JKE-be** [comment]
Personally, I prefer one white pixel that the placeholder.png...
Maybe we should have a default (or random) avatar (placeholder with an head) like in res_partner view from backend...

In any case, the behavior from v10c could be backported in v9c

**Comment by pedrobaeza** [comment]
@antespi, can you take a look to the 10c behavior?

**Comment by antespi** [comment]
@pedrobaeza  v10c renders a 1x1 pixel image

**Comment by pedrobaeza** [comment]
But isn't that 1x1 pixel looks weird and not consistent across messages in the final result?

**Comment by C3POdoo** [comment]
Dear @antespi,

Thank you for your contribution but the version 9.0 is no longer supported.
We only support the last 3 stable versions so no longer accepts patches into this branch.

We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

_This is an automated message._

**Pull request closed without merging**
