### PR TITLE
[IMP] mail, mass_mailing, sms, mass_mailing_sms, im_livechat: port emoji char/text fields to OWL 

### PR DESCRIPTION
**Pull request by Zynton**
This ports the `text_emojis`, `char_emojis` and `sms_widget` fields to OWL.

Enterprise PR: https://github.com/odoo/enterprise/pull/31716

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Zinston** [comment]
@odoo/rd-security The `innerHTML` call was already there, I just adapted to OWL. Its contents are escaped in `emojis_mixin.js`:

image

**Comment by mart-e** [comment]
@robodoo override=ci/security
Reason: content is escaped in `_formatText` method

**Comment by xmo-odoo** [comment]
> The innerHTML call was already there

As we repeat every time, that's not actually a justification, the existing code can be wrong, and even when it's not the way the surrounding code changes can make it wrong when it was not before.

Also since this is being owlified, it could (should?) use a new routine which generates vdom or whatever it is owl uses internally, rather than mess about with raw HTML text.

**Comment by Zinston** [comment]
> As we repeat every time, that's not actually a justification, the existing code can be wrong, and even when it's not the way the surrounding code changes can make it wrong when it was not before.

I know that, that's why I gave the explanation anyway as to why it's safe. I specified it was already there for context only.

> Also since this is being owlified, it could (should?) use a new routine which generates vdom or whatever it is owl uses internally, rather than mess about with raw HTML text.

I did that wherever I could but changing this would have implied a lot more refactoring in `mail` than this conversion. This seems out of scope to me, and more something for a future refactoring by the `mail` team who knows the inner workings of their module better than I do...

**Comment by antonylesuisse** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
We will have a look next week, thanks @Zinston for your work. As there is no task I suppose it has not been tested (if it has been done, please always link a task to be able to do some followup). We will play a bit with it then send the code.

Cheers !

**Comment by tde-banana-odoo** [comment]
@robodoo r-

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by tde-banana-odoo** [comment]
Thanks @Zinston for the various fixes / try-and-die for the display :) .

**Pull request closed without merging**
