### PR TITLE
Create kab.js

### PR DESCRIPTION
**Pull request by MohammedBelkacem**
Add a globalization for Kabyle Language.

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

`datejs` is a library we are using to represent dates. I don't think adding this file will have any effect as the language does not exist in odoo.
Are you trying to add support for the Kabyle language ? This should be done server side then.

**Comment by mart-e** [comment]
Hello,

We have added the kab_DZ language at d377f5690e62237317c8909a9d9d1814cef60c6d and I have merged your datejs file at 72cc8b99a9961f088dbbee15cc5d6f18befff0be.
Thank you very much for these additions.

**Comment by belkacem77** [comment]
Hello mart-e,
The js file name syntax should be kab-DZ not kab_DZ. There is an error when loading Kabyle translation.

**Comment by mart-e** [comment]
right, my bad, fixed at 916525fbf3cec60f3bb8e365d58fe09850c5ab34

**Pull request closed without merging**
