### PR TITLE
[FIX] all: wrong python expression in modifiers ('in' instead of '==')

### PR DESCRIPTION
**Pull request by Gorash**
There are some conditions in xml that uses in or not in for a check with a string. These are replace by == or != operators, respectively.

Issue from #104741 (wrong conversion/rebase)

### CODE REVIEW

**Review by Julien00859 — APPROVED** [review]
@robodoo r+

**Comment by ticodoo** [comment]
This fix should already be merged? :confused: https://github.com/odoo/odoo/pull/132798

**Comment by william-andre** [comment]
Go home Github, you're drunk
https://github.com/odoo/odoo/blob/89c93aba75a9c4d7e304c4decd4d5d3673d4df08/addons/account/views/account_move_views.xml#L440
(current master)

**Comment by Gorash** [comment]
I will reset my github. Even with the sweater I have no change.

**Pull request closed without merging**
