### PR TITLE
[I18N] Add translation files for l10n_sa_edi

### PR DESCRIPTION
**Pull request by akr-odoo**
Adding base translation files for l10n_sa_edi as well as arabic translation

Description of the issue/feature this PR addresses:
Adding arabic translation to the l10n_sa_edi
Current behavior before PR:
No translations
Desired behavior after PR is merged:
Adding arabic translation to the l10n_sa_edi

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by akr-odoo** [comment]
cc @jco-odoo

**Comment by jco-odoo** [comment]
I only changed the i18n_extra folder name to i18n

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by d-fence** [comment]
@robodoo retry
Failing tests were disabled for now

**Comment by d-fence** [comment]
@robodoo retry
seems that I forgot one test (disabled now)

**Pull request closed without merging**
