### PR TITLE
[FIX] project: fix field translate

### PR DESCRIPTION
**Pull request by praw-odoo**
1)
Before this commit, Project >  '# of tasks' from the burndown chart was not
translatable to any language

So in this commit, Project >  '# of tasks' from the burndown chart will be
translatable to any language

2)
Before this commit, Task form view > timesheets notebook > the remaining hours
field is not correctly aligned due to extra span inside the view.

So in this commit, span will be only added if total_hours_spent
is visible on the view.

3)
Before this commit, project sharing form view: the name field was long

After this commit, name field will be aligned

task-3010685

### CODE REVIEW

**Review by MissingNoShiny — COMMENTED** [review]
LGTM, thanks for your work :slightly_smiling_face: 
Could you update your PR description so that it describes all of your changes?

**Comment by praw-odoo** [comment]
> LGTM, thanks for your work slightly_smiling_face Could you update your PR description so that it describes all of your changes?

updated description

**Comment by xavierbol** [comment]
robodoo r+

**Comment by xavierbol** [comment]
robodoo rebase-ff

**Pull request closed without merging**
