### PR TITLE
[FIX] base: fix name for country state of Buenos Aires

### PR DESCRIPTION
**Pull request by zaoral**
Description of the issue/feature this PR addresses:

* Fix the name that show the Buenos Aires state to the proper one.

Current behavior before PR:

* Buenos Aires state is named as Buenos Aires City, 

Desired behavior after PR is merged:

* Buenos Aires state is named Cuidad Autónoma de Buenos Aires (CABA) which is the proper name for identify and inform about operations in this state.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by zaoral** [comment]
FYI opw-1908978

**Comment by jjscarafia** [comment]
:+1: 
FYI, from [this file](http://www.afip.gob.ar/fe/documentos/TABLA%20PROVINCIAS%20V.0%20%2025082010.xls) from the government you can check that "Ciudad Autónoma de Buenos Aires" is the proper name
(the link to this file is on this site http://afip.gob.ar/fe/ayuda.asp under "Códigos de Provincia" link)

**Comment by qdp-odoo** [comment]
Hello @zaoral 

thanks for the contribution! Can you nevertheless amend your commit message to respect our standard (https://www.odoo.com/documentation/9.0/reference/guidelines.html#commit-message): you are just missing the module name, and the first line should be if possible shortened to summarize the commit purpose.

Here's what I would write:
```
[FIX] base: fix name for country state of Buenos Aires

Change "Buenos Aires City" to "Cuidad Autónoma de Buenos Aires" accordingly to http://www.afip.gob.ar/fe/documentos/TABLA%20PROVINCIAS%20V.0%20%2025082010.xls
```

**Comment by moylop260** [comment]
Please, Fix typo "Cuidad" to "Ciudad" in the commit message and pr
description.

**Comment by zaoral** [comment]
@qdp-odoo Ready! I updated the PR and commit messages
@moylop260 Thank's for notice, I also fixed the typo

**Comment by qdp-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
