### PR TITLE
update file stock.py

### PR DESCRIPTION
**Pull request by mossaabboudchicha**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

to fix issue one of the documents you are trying to access has been deleted in mrp.production

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

> to fix issue one of the documents you are trying to access has been deleted in mrp.production

Sorry but a try/except is not an appropriate solution. We should first determine why there is an error and correct at the source.

> I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

It does not look like it is the case.

Closing as missing information and the patch is not ideal.

**Comment by mossaabboudchicha** [comment]
hello,can you tell me what was the problem?

**Comment by mart-e** [comment]
Not really, you opened a pull request without explaining the issue.
Please check the [contributing guidelines](https://github.com/odoo/odoo/wiki/Contributing) and if you still have an issue, do not hesitate to open a new one pull request.
However putting a try/except is very unlikely to be a good solution.

**Comment by mossaabboudchicha** [comment]
thank you very much


________________________________

**Pull request closed without merging**
