### PR TITLE
[FIX] web: update owl to last version

### PR DESCRIPTION
**Pull request by aab-odoo**
This commit updates owl from v1.2.1 to v1.2.2

See [1] for the list of changes.

[1] https://github.com/odoo/owl/commit/71f545058bc9cdc326003bf8573cef1bb4c903d4

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by seb-odoo** [comment]
?
@robodoo retry

**Comment by seb-odoo** [comment]
@robodoo r-
probably a bad idea, some of the errors are like " Cannot mount a destroyed component"

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r-

**Comment by ged-odoo** [comment]
fw-bot help

**Comment by ged-odoo** [comment]
@fw-bot ignore

**Comment by ged-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
