### PR TITLE
[REF] web, pos, website_slides: Remove totally underscoreJS

### PR DESCRIPTION
**Pull request by pipu-odoo**
After this commit, underscore library is totally removed. 
Library calls has been removed from manifests.
Library files has been deleted.
This commit closed the task below. 

task-3246238

### CODE REVIEW

**Comment by rdeodoo** [comment]
> pipu-odoo requested a review from rdeodoo 6 hours ago

I am not sure I can be of any help here?
Note that it's `task-3246238` and not `taskId : 3246238`, as per our guidelines, otherwise it just creates wrong links to commits having the same hash.

**Comment by sdegueldre** [comment]
change in pos seems fine, can you also remove _ from the globals defined in the test_eslint config? `/test_lint/tests/eslintrc`, this will make the runbot red if they try to use _ even if their code is not tested.

**Comment by sdegueldre** [comment]
Design-themes PR: https://github.com/odoo/design-themes/pull/662

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by sdegueldre** [comment]
@robodoo retry

**Pull request closed without merging**
