### PR TITLE
[FIX] base: update Spanish address format

### PR DESCRIPTION
**Pull request by dylankiss**
Currently the Spanish address format does not include the province/state.

This change adds the province between parentheses after the zip code and city.

task-3147965

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The usual postal address format is:

```
ZIP City (Province)
```

Example: `03008 Alicante (Alicante)`

instead of putting it in a new line and between parenthesis.

**Comment by dylankiss** [comment]
@chklop

**Comment by dylankiss** [comment]
> The usual postal address format is:
> 
> ```
> ZIP City (Province)
> ```
> 
> Example: `03008 Alicante (Alicante)`
> 
> instead of putting it in a new line and between parenthesis.

@pedrobaeza Is the parenthesis format the most used in Spain? Since the references of the UPU indicate it on a new line and the Wikipedia article says that the parenthesis format is an older one.

- https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/espEn.pdf
- https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/s42/espEn.pdf
- https://es.wikipedia.org/wiki/Direcci%C3%B3n_postal#Espa.C3.B1a

**Comment by pedrobaeza** [comment]
I see. Maybe I'm outdated, hehe. Anyway, Wikipedia is not totally coherent, as it says about a new line, but then put an example with comma instead:

Selección_007

I still see using a line only for the province seems a waste of space, and more now that everything goes more digital than physical (UPU references are for physical letters), so I would go for the comma if the parenthesis one is outdated.

**Comment by chklop** [comment]
@pedrobaeza @dylankiss Actually putting it in parenthesis was my first idea, but when searching for it I stumbled on the "new line format. I also think that in parenthesis and on the same line wastes less space ; let's do that instead.
Thanks for the feedback @pedrobaeza.

**Review by vin-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
