### PR TITLE
[FIX] base, tools: properly distribute branding around removed elements

### PR DESCRIPTION
**Pull request by qsm-odoo**
[FIX] base, tools: properly distribute branding around removed elements
    
    When branding was added on items which follow an element that is removed
    by an inheriting view, the branding was incorrect. Indeed, it supposed
    the removed element does not exist in the original view. E.g.:
    
    Parent view:
    ```
    <hello>
        <world></world>
        <world></world>
        <t t-esc="foo"/>
    </hello>
    ```
    
    Child view:
    ```
    <data>
        <xpath expr="/hello/world[1]" position="replace"/>
    </data>
    ```
    
    => There are two <world/> in the original view, the first one is removed
       by a child view. The data-oe-xpath set on the remaining <world/>
       should still be /hello/world[2] and not /hello/world[1] to target the
       right element in the parent view.
    
    This of course induced edition problems where a saved area was not saved
    inside the right element of the parent view or, more likely in normally
    complex arch, just crashed on save. As an example, with 14.0 enterprise:
    
    - Install website_appointment
    - Go to a page with a calendar to schedule an appointment
    - Enter edit mode, try to add something in the area *below* the calendar
    - Save => crash
    
    Commit [1] already fixed similar problems when an element was *replaced*
    by something (especially, when replaced by an element with the same tag
    name). This commit actually reviews what was done to fix both problems
    (replacement and removal) at the same time. It also makes it so the xml
    that `apply_inheritance_specs` produces has no "Element" part impacted
    when used with "inherit_branding=True", which seems better... although
    the notion of inheriting branding should probably be independant from
    this function (maybe something to do in master).
    
    [1]: https://github.com/odoo/odoo/commit/c077ef05575d9677bce284195683f96c68386788

[FIX] base: remove branding on nodes whose inner content is removed
    
    Parent view:
    ```
    <hello>
        <world></world>
        <world></world>
    </hello>
    ```
    
    Child view:
    ```
    <data>
        <xpath expr="/hello/world[1]" position="replace"/>
    </data>
    ```
    
    => There are two <world/> in the original view, the first one is removed
       by a child view.
    
    In that case, the branding was still distributed on the <hello> element.
    This is a problem as it meant that in edit mode you were able to edit
    the whole content of that <hello/> element... breaking the xpath made by
    the child view.
    After this commit, in that case, the branding is rightfully distributed
    on the remaining <world/> element (just like it would have been if the
    inheriting view had added an element instead of just removing one).
    
opw-2811674

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo rebase-ff

**Review by rdeodoo — APPROVED** [review]
The output is the expected one.
The code seems fine to me. I played a bit with some views and everything seems to behaves correctly.

I am probably not the best suited to have a final review here, but the codeowner requested a review from the @odoo/rd-security anyway, let's wait to see if everything looks fine on their end too.

**Comment by qsm-odoo** [comment]
Hello @odoo/rd-security :wave: 

Just making sure this is in your pipeline :+1: As this is related to a ticket from a customer who just cannot edit the main area of its app page, the sooner we merge this, the better :+1:

**Comment by mart-e** [comment]
> but the codeowner requested a review from the rd-security

This is probably because you modified something in tools (which contains "dangerous zone" methods). In this case, nothing related to security so feel free to ignore the review request :)

**Comment by qsm-odoo** [comment]
The r+ is in your hands @rdeodoo :smile:

**Review by rdeodoo — APPROVED** [review]
@robodoo r+

**Comment by sysi-odoo** [comment]
Hey @qsm-odoo 
Apparently, the issue has been fixed but only on one of the pages of her website.. Do you think it would be possible to replicate the solution on the other services? 
Don't hesitate to contact me if needed :)

**Comment by qsm-odoo** [comment]
@sysi-odoo This fix is generic so I doubt this is the same problem... do you have steps to reproduce / more information so I can check what this is about ?

**Comment by sysi-odoo** [comment]
@qsm-odoo Sure! 
There is no flow per se, but you can compare 2 different pages. If you go on her website on the production database (cleaningheroes.odoo.com), you go to the "Make an appointment" section, you can see she's offering several services to her client. 
If you click on the 1st one being "Cleaning for individuals", you can see the calendar at the top of the page and some notes below. 
This is not the case when you check other services, such as the 2nd one for example "Customize your cleaning" where the calendar is at the bottom.

Let me know if you prefer discussing this over a call, it might be easier :) Thanks again for helping me!!

**Comment by qsm-odoo** [comment]
@sysi-odoo I don't think there is an issue, this is the way the app was designed:
- The message you can edit on top of the calendar is specific to the appointment type (one for "Cleaning for individuals" and one for "Customize your cleaning")
- The message you can edit at the bottom of the calendar is shared for all appointment types

I guess it's worth signaling this could be improved (at least with editor messages explaining it during edition just like for some eCommerce / events areas). But in stable versions, there is no bug per se.

**Pull request closed without merging**
