### PR TITLE
[REF][website_mass_mailing] Inheritable/extensible subscription manager.

### PR DESCRIPTION
**Pull request by yajo**
Description of the issue/feature this PR addresses:
Refactor subscription manager JS to make it workable.

Current behavior before PR:
Prior to this patch, if anyone tried to extend the subscription management
form, it became almost impossible, due to its JS design. This affected https://github.com/OCA/social/pull/129 for instance.

Besides, result strings always were in English.

Desired behavior after PR is merged:
UX will be mostly the same, but now, devs will be able to extend the form, include it in other views and
translate the result strings.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by Yajo** [comment]
Hi @ged-odoo, I see most of what I'm replacing here was yours... Could you please review it? This would help a lot downstream. Thanks! :blush: 

Also... would you accept this for v9? It changes no models, and the behaviour it is changing was already in an unreachable namespace before, so I see no chances for it to introduce any incompatibilities...

**Comment by Yajo** [comment]
Any chances on getting this merged? Not sure what happens with CLA bot but it's signed...

**Comment by JKE-be** [comment]
Thanks for the PR

Could you rebuild on master and check cla.

Commits signed with:  yajo.sk8@gmail.com and Yajo@users.noreply.github.com

**Comment by Yajo** [comment]
I think it should be OK now.

**Comment by pedrobaeza** [comment]
@Yajo is this still applicable? Runbot is red.

**Comment by qsm-odoo** [comment]
I have a branch based on this but it is waiting for some other fixes related to the unsubscription page :)

**Comment by qsm-odoo** [comment]
(https://github.com/odoo-dev/odoo/commit/0f38b9ca5bf89ffe9ad86c33071a7bfb8d76a560, untested and as I said waiting for other fixes)

**Comment by pedrobaeza** [comment]
Very good, Quentin! As you can see, I'm checking all our old PRs to give them a kick or discard them. @Yajo please review that one and I think you can close this PR.

**Comment by Yajo** [comment]
Yeah, closing, your patch is more up to date with new JS thingies.

**Comment by Yajo** [comment]
I'm worried it still didn't land in master, is there any problem?

**Comment by JKE-be** [comment]
sorry @Yajo 

It is in the todolist...

But before, we have another task that is to clean our security email form mailing list that you subscribed yesterday!  Thanks for your help.

**Pull request closed without merging**
