### PR TITLE
[MERGE] forward port branch saas-11.5 up to 197119a37d1

### PR DESCRIPTION
**Pull request by KangOl**

### CODE REVIEW

**Comment by KangOl** [comment]
robodoo rebase- review+ priority=0

**Comment by KangOl** [comment]
@robodoo review+

**Comment by xmo-odoo** [comment]
robodoo retry 💫

**Comment by KangOl** [comment]
robodoo retry

**Comment by xmo-odoo** [comment]
robodoo retry 😠

**Comment by xmo-odoo** [comment]
robodoo retry ❤️

**Comment by KangOl** [comment]
robodoo retry again please :innocent:

**Comment by xmo-odoo** [comment]
@KangOl did that actually work? Was the previous forward port really the head of master before merging this?

**Comment by KangOl** [comment]
Yes, it was.

**Comment by xmo-odoo** [comment]
jpjfeyv

**Pull request closed without merging**
