### PR TITLE
[IMP] Improve Vietnamese COA to follow Circular No. 200/2014/TT-BTC

### PR DESCRIPTION
**Pull request by tungocbui**
Description of the issue/feature this PR addresses:
Update the Vietnamese chart of account to follow Circular No. 200/2014/TT-BTC

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

…n branch 10.0

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for you patch but it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by tungocbui** [comment]
@mart-e our CLA was merged in [this commit](https://github.com/odoo/odoo/commit/71edb4fc4c99c981646f0acd569f4e9f852727b3) some days ago.

Please let me know if you need anything else. Thank you.

**Comment by tungocbui** [comment]
FYI: [here](https://github.com/odoo/odoo/pull/13680) is the pull request for the CLA.

**Comment by tungocbui** [comment]
@mart-e could you please spend some time to check this PR? Let me know if you need anything else.

**Comment by mart-e** [comment]
Hello,

Thanks for the update. As it was removing some account types (which is not stable), I have merged it in master at 6dd921fb76a106d9ba4055a92025581e1e0486bd
Regards

**Comment by tungocbui** [comment]
@mart-e thks for merging this pull request. 

Btw, we only removed 1 "account type" which is not used anymore. This Circular No 200 was released in 2014, we needed to create a new module to update the COA for all of the projects with Odoo v8, Odoo v9. 
Odoo v10 was just released 1 or 2 months ago, i believe that there are not much projects using Odoo 10 in Vietnam and adding this fix in v10 will help a lot of ppl when they want to use Odoo v10 with Vietnamese COA. Could you please consider to merge this fix also in Odoo v10?

Again, thks for your time and support.

**Comment by mart-e** [comment]
I have backported to 10.0 at 0ad4faffebaf7cb0b0c88cea07fb30b9018850d2 without the account type removal (just not used).
This way it will not break for existing deployments.

**Comment by davidtranhp** [comment]
I have reviewed the recent merge but found that chart is not accurate. Here is the correct one (with English translations for those who does not know Vietnamese): [https://www.erponline.vn/en/blog/446-vietnam-chart-of-accounts-under-the-vietnamese-accounting-system](url)

**Comment by tungocbui** [comment]
@mart-e thank you very much.

@davidtranhp can you specify incorrect points? Then we will check and propose another pull request if needed.

**Comment by davidtranhp** [comment]
@tungocbui please look through the article on the erponline site. There are many accounts missing, some are incorrect, e.g. Bảo hiểm thất nghiệp.
In master branch, should consider to add account tags to group accounts of same code prefix, otherwise we will no be able create legal reports in compliance with the requirements by the state.
I can send you our custom module that fixes the default COA for you to make a PR.

**Comment by tungocbui** [comment]
@davidtranhp it's better that you propose the PR if you already have the module. In case you want me to do the PR, i would be happy to do also. Let me know. 

Have a nice day!

**Pull request closed without merging**
