### PR TITLE
[FIX] mail: do not show im_status for inactive users

### PR DESCRIPTION
**Pull request by xdu-odoo**
task-2417875

### CODE REVIEW

**Review by alexkuhn — CHANGES_REQUESTED** [review]
I don't like how `im_partner` is a sentinel value in `im_status` that means the partner is archived...

But if we have to keep this stuff in server-side logic, at least client-side logic should be smarter than use the same trick. Seems more reasonable to turn `active` to `false` when `im_partner` is obtained from server as `im_status` (and we keep `im_status` to `undefined`).

**Comment by xdu-odoo** [comment]
> I don't like how `im_partner` is a sentinel value in `im_status` that means the partner is archived...
> 
> But if we have to keep this stuff in server-side logic, at least client-side logic should be smarter than use the same trick. Seems more reasonable to turn `active` to `false` when `im_partner` is obtained from server as `im_status` (and we keep `im_status` to `undefined`).

@alexkuhn It's problematic as `im_partner` value is also used to prevent fetching of im_status for those partner as we know they won't have any status. We still check for status of inactive partners. Also, active is used to determine what is archived, here the partner is not archived, it just has no user which is different. I'm afraid there will be some misunderstanding later on and probably some misuse of this flag. For example if we need to show an "ARCHIVED" tag in message from archived partners.

**Comment by alexkuhn** [comment]
> > I don't like how `im_partner` is a sentinel value in `im_status` that means the partner is archived...
> > But if we have to keep this stuff in server-side logic, at least client-side logic should be smarter than use the same trick. Seems more reasonable to turn `active` to `false` when `im_partner` is obtained from server as `im_status` (and we keep `im_status` to `undefined`).
> 
> @alexkuhn It's problematic as `im_partner` value is also used to prevent fetching of im_status for those partner as we know they won't have any status. We still check for status of inactive partners. Also, active is used to determine what is archived, here the partner is not archived, it just has no user which is different. I'm afraid there will be some misunderstanding later on and probably some misuse of this flag. For example if we need to show an "ARCHIVED" tag in message from archived partners.

What about using im status value `n/a` in JS? Much more meaningful than `im_partner` at least. It makes sense to keep `undefined` for when we don't know the im status, and use another sentinel value for stating the partner has no im status.

I thought the `im_partner` value was only used for archived partners, so that's why I suggested to rely on active because the im status value is N/A due to active... But that's apparently not the case, and it seems there is a class of partners that have N/A im status due to being either archived, has no user, etc. It would still be good to somehow understand why im status has value `n/a` (because this value is deduced from another characteristic of the partner), but at least it clearly states that the is no im status for this partner.

What do you think of this idea?

**Comment by xdu-odoo** [comment]
I don't really care of the value you want to use but I think it's nonsense to use a different one from the server as it's only used there. So, IMO, we should use `im_partner` or `n/a` or `nutella` or anything else, but use it everywhere.

**Comment by alexkuhn** [comment]
I really don't like `im_partner`, because it's not clear what it means. "The im status of user is im status of partner" makes absolutely no sense... Maybe it is meant to be understood as "The im status of a partner (without any active user)" but then it's too technically specific and if in the end it's just a way to say "no im status", then just tell "no im status"... The context can be deduced in some other ways, such as just checking whether the partner has an active user or not.

I prefer something more meaningful like `n/a`. I suggested having this naming only in JS because we have more control/expertise/confidence in JS, and much less in python. If we change in python, could possibly introduce some annoyances like migration script, change of meaning of value that other teams do not agree with, etc... But if we are confident that it's the right change, then it's good to also use value `n/a` in python (or something with a very close meaning).

**Comment by xdu-odoo** [comment]
The value is computed so no migrations needed and it's only used in mail-related things, so I think it's safe to change also in python

**Comment by alexkuhn** [comment]
> The value is computed so no migrations needed and it's only used in mail-related things, so I think it's safe to change also in python

Great, so I'm all for change in python in that case. Let's go with `'n/a'` value in both JS and python. Thanks! :)

**Comment by seb-odoo** [comment]
Use `not_applicable` in full then, abbreviation is not good (especially with a / on it).

**Comment by alexkuhn** [comment]
> Use `not_applicable` in full then, abbreviation is not good (especially with a / on it).

The abbrevation is `n/a` is universally understood and used. I see no reason not to use it that form.
Full text is too long to read, and I really don't like some special format in such values, like the underscore as separation for the 2 words. All in all I still choose `n/a`.

**Comment by seb-odoo** [comment]
This name is not good for code maintenance.

When I look for `im_partner` in the code, I see 2 occurrences, and they are related, this is perfect.

When I look for `n/a` I got all sorts of random crap that are totally unrelated.

I think technical strings need to be long and as unique as possible. I would even argue prefixing them all by their context would be the best.

**Comment by alexkuhn** [comment]
> This name is not good for code maintenance.
> 
> When I look for `im_partner` in the code, I see 2 occurrences, and they are related, this is perfect.
> 
> When I look for `n/a` I got all sorts of random crap that are totally unrelated.
> 
> I think technical strings need to be long and as unique as possible. I would even argue prefixing them all by their context would be the best.

`n/a` means "not applicable". There's no reason that only the 2 occurrences in the whole code of Odoo have to strictly match this concept. It totally makes sense that many other things need `n/a`.

There's no reason to namespace the values. If you feel the need to check every places that makes use of this value in the context of im status, it's stupid to expecting to just grep value and call a day to have exact match. That's not how you do it.

**Comment by xdu-odoo** [comment]
I went with `nutella`, the winner gains the right to change the name :p

**Comment by alexkuhn** [comment]
Suggestion: `'im_status.n/a'`. @seb-odoo?

**Comment by seb-odoo** [comment]
Ok for me. I wish we could agree to make it a guideline and rename others too, but we can try just this one for now and see how it goes.

**Comment by alexkuhn** [comment]
I suggest same value whether it's partner with no user or never logged user, at least for this PR.

**Comment by xdu-odoo** [comment]
> I suggest same value whether it's partner with no user or never logged user, at least for this PR.

Bad idea, no user means they won't connect so we don't want to poll their im_status, never logged means they didn't logged yet but maybe they will someday so we want to poll them

**Comment by alexkuhn** [comment]
> > I suggest same value whether it's partner with no user or never logged user, at least for this PR.
> 
> Bad idea, no user means they won't connect so we don't want to poll their im_status, never logged means they didn't logged yet but maybe they will someday so we want to poll them

But then when they become logged for 1st time, we get that info in the longpolling no? Or it's just a subset of employees that receive that notification?

Honestly, it might be easier/safer to keep them 'offline' as it was before PR. The suggestion to not display im status of never logged user is quite debatable... Offline is offline... Why is never logged user illegible to displaying im status?

I'm not okay with having a different sentinel value for the never logged user. As a matter of principle, im status should be set or unset (`undefined`). Even the suggestion to have `n/a` is off because it's deduced by another info, therefore the code shouldn't just rely on im status value. Doing the "right" thing may be too much effort, requiring change of API of some python controllers and also adding more knowledge in JS (i.e. actually modeling/awareness of "never logged" user or "partner without user"). I don't feel confident in doing this change, especially when we already raised some modeling issues in discuss like having to handle partner/user/employee when we basically when a single concept instead.

So for me, it's both `im_status.n/a` and unset this value from longpolling notification "newly logged", or we just use `offline` for never logged like before. Let's ignore the frequent im status fetch considering these never logged users... We do this inefficient check for all other users so by including these never logged users it's not as if it would have perceived worst performance...

**Comment by seb-odoo** [comment]
Since this is master and the issue is really not critical, I think we should either go all the way, or do very minimal diff. I don't like this hybrid solution were we do some changes but not all of them.

**Comment by xdu-odoo** [comment]
Just did what AJU asked. So if you think it's debatable, you may have a word with her about it ?

**Comment by alexkuhn** [comment]
> Since this is master and the issue is really not critical, I think we should either go all the way, or do very minimal diff. I don't like this hybrid solution were we do some changes but not all of them.

Diff is very small, and it adds some JS tests which is good too. Much better foundations for implementation the right solution.

As I said, quite some effort to do the right solution, I don't want to increase scope of PR too much, otherwise we will give up to improve good.

**Comment by seb-odoo** [comment]
@xdu-odoo I think it's best if you just focus on other tasks for the remaining time, it's pretty clear we will not find an agreement here by discussing about it, so I guess I'll just need to try and refactor the whole thing and see if we can be more happy with the result.

**Comment by xdu-odoo** [comment]
I think the same, I'll leave it to you @seb-odoo

**Comment by seb-odoo** [comment]
obsolete

**Pull request closed without merging**
