### PR TITLE
[FIX] mass_mailing_sms: use column_invisible instead of invisible in tree

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
-Probably miss by script since
https://github.com/odoo/odoo/commit/332c117f60a36f723c450f61ce2e0e7181d66c21

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by reth-odoo — APPROVED** [review]
@tde-banana-odoo :wave: likewise, woops :smile:

**Comment by tde-banana-odoo** [comment]
@robodoo r+

thanks for the fix !

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Comment by duong77476-viindoo** [comment]
@tde-banana-odoo Runbot need to take a nap i guess, already encounter this problem sir :disappointed:

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
