### PR TITLE
[I18N] account_edi_ubl_cii_tax_extension: add new stable module

### PR DESCRIPTION
**Pull request by guva-odoo**
Add `account_edi_ubl_cii_tax_extension` module to transifex.
Pot file already added in original PR that adds in new module into stable.

Orig PR: https://github.com/odoo/odoo/pull/176221
opw-4061329

### CODE REVIEW

**Comment by guva-odoo** [comment]
> Hello! Ok for me, can you just fix your commit:
> 
> ```
> [I18N] account_edi_ubl_cii_tax_extension: add new stable module
> 
> Add `account_edi_ubl_cii_tax_extension` module to transifex. Pot file already added in original
> PR that adds in new module into stable.
> 
> Orig PR: odoo/odoo#176221
> opw-4061329
> ```
> 
> Don't forget to update the values for every fw-port

Done, thanks!

**Comment by ticodoo** [comment]
Thanks! I'll leave it to you to r+ it after the orig PR is merged, just in case something blocks it in the end.

@robodoo delegate guva-odoo

**Comment by ticodoo** [comment]
erghh 

@robodoo delegate=guva-odoo

**Comment by guva-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
