### PR TITLE
[FIX] website: Unlink several website.page records

### LINKED ISSUE #26823: [11.0] Website: Singleton error when we trying to unlink multiple pages.
Impacted versions: 11.0

Steps to reproduce:

1 > Go to Website > Configuration > Pages tree view.
2 > Select more than one record of pages in list view.
3 > Click on Delete.

Current behavior:
Getting singleton error.
page

Expected behavior:
Should allow to delete multiple pages.

Video/Screenshot link (optional):

### PR DESCRIPTION
**Pull request by pedrobaeza**
Avoid singleton error

Closes #26823 

cc @Tecnativa

### CODE REVIEW

**Comment by JKE-be** [comment]
Replace self by page is probably the correct fix ;) 

already done in master, need to be backported ...

**Comment by pedrobaeza** [comment]
You're right :sob: 

I didn't see that it was inside a loop. Are you backporting it or may I?

**Comment by pedrobaeza** [comment]
I have improved the PR checking more deeply.

**Comment by JKE-be** [comment]
I prefer to merge yours, because in master, it has been fixed during multi website feature, so the diff is lost in the mass

**Comment by JKE-be** [comment]
thx for the reporting and the PR ;)

**Comment by pedrobaeza** [comment]
You're welcome! :smile: 

See you in less than a month!

**Pull request closed without merging**
