### PR TITLE
 Revert "Cherry pick of 673a66f failed" commit 161eb51.

### PR DESCRIPTION
**Pull request by jbw-odoo**
FWD commit was made with wrong message and 2 commits squashed in one.
Revert commit & reapply in 2 next commits with ok messages.

Task: 2687215

### CODE REVIEW

**Comment by jbw-odoo** [comment]
@oco-odoo

**Comment by oco-odoo** [comment]
@robodoo r+

I thought the mergebot prevented merging those, now ~~

**Comment by oco-odoo** [comment]
@robodoo rebase-ff

**Comment by oco-odoo** [comment]
@fw-bot ignore

**Pull request closed without merging**
