### PR TITLE
[IMP] Separate data retrieval and html render to allow override

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
I suggest this small refactoring to all override and complete values before passing it to renderer.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
OPW-715681

**Comment by mge-odoo** [comment]
Hi Cédric,

This pull request is about adding a feature, adding the possibility for developers to override the method.

We have a strict policy regarding stable policy: we do not add new features. Only bug fixes are accepted in stable releases, to avoid introducing new regressions by attempting to add new features in stable releases.

To know more about our policy, you can read the below documentation:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

This pull request can nevertheless definitely target the development branch, master, and can be considered by our R&D department.

I hope you will understand.

Regards,

Martin

**Comment by Cedric-Pigeon** [comment]
@mge-odoo Hello,

sorry but I don't add any feature, I just split an existing method.

I already did it in the past and it was merged so I don't understand why you refuse this one.

For example, the last one was: https://github.com/odoo/odoo/pull/15179

**Comment by mart-e** [comment]
Hi,

The PR you mention was the exception. We rarely accept adding hooks methods in stable version.
See the recent discussion about it on #15091

99f365523bcdfb10e48d87d4f047c2504fb25872 is a recent example of a hook method that introduced a regression fixed at c1b603e81c873213d69f7a4b9ce059a47dda1dba
Merging in 10 is acceptable in some usecase, in a 3 years old version is not.

**Comment by Cedric-Pigeon** [comment]
@mge-odoo Would you accept it on master ?

**Pull request closed without merging**
