### PR TITLE
add azeri language to base module

### PR DESCRIPTION
**Pull request by nurlanf**
Add Azerbaijani language to base language list

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Thanks !
@robodoo r+ rebase-ff

**Comment by mart-e** [comment]
I see, the CLA commit was with the right email address but the res.lang commit was made with the `noreply.github.com` email address. Assuming it was an issue, I have corrected to use the same as the CLA.
@robodoo r+

**Comment by nurlanf** [comment]
@mart-e , why this PR was closed? Is there anything that I can do?

**Comment by mart-e** [comment]
@nurlanf sorry, reopening. the remaining issue is for the CLA

- you are signing _using_ the address `n...@yggdrasilgaming.co`
- you are signing _for_ the address `c...@gmail.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by nurlanf** [comment]
@mart-e I created another PR https://github.com/odoo/odoo/pull/105944

Can you check if it is ok?

**Comment by mart-e** [comment]
Replaced by #105944

**Pull request closed without merging**
