### PR TITLE
[IMP] website_sale: product tags - list view

### PR DESCRIPTION
**Pull request by alpa-odoo**
This PR adds the possibility to change the product tag color on a product and also to edit those tags from a submenu of the eCommerce.

Task: `2904805`

### CODE REVIEW

**Review by Williambraecky — APPROVED** [review]
Thanks for your work
robodoo r+

**Comment by Williambraecky** [comment]
robodoo r+

**Comment by Williambraecky** [comment]
@alpa-odoo I assume you rebased to fix the red runbot. In this case you can use the automatic rebase function on the runbot and the r+ will stay active :) as there was no push.

**Comment by Williambraecky** [comment]
robodoo r+

**Comment by alpa-odoo** [comment]
> @alpa-odoo I assume you rebased to fix the red runbot. In this case you can use the automatic rebase function on the runbot and the r+ will stay active :) as there was no push.

Good to know thanks.

**Pull request closed without merging**
