### PR TITLE
Loyal Sign the Odoo CLA

### PR DESCRIPTION
**Pull request by kevin3274**

### CODE REVIEW

**Comment by odony** [comment]
Hi,

Thanks for the CLA signature. The CLA check does not pass because your git `user.email` uses your 163.com email rather than the one you used in the CLA signature.
You can add an extra email in the CLA signature if you want, or you can change your git user.email and re-commit to have it pass.
Thanks!

**Comment by kevin3274** [comment]
I was changed user.email and recommited

**Comment by odony** [comment]
Hi, did you push the new commit? The current commit is 85381b0f809e39864d113cdb88ad2570dec0d20a and still has your 163.com email address..
Thanks!

**Comment by kevin3274** [comment]
OK, I was pushed again. Thanks.

**Comment by odony** [comment]
Hi,

Still not fixed, the new commit dc2ce0bb0bb31bb17813ddb897dabd66197dd585 is still commited with your 163.com email, sorry :-( You can see it if you look at the patch corresponding to your PR: https://github.com/odoo/odoo/pull/5743.patch

Maybe the easiest is to modify you CLA signature to also include your 163.com email?

Thanks,

**Comment by mart-e** [comment]
Thanks for the update, it has been merged at bbcc6a8

**Pull request closed without merging**
