### PR TITLE
[FIX] minor style issues

### PR DESCRIPTION
**Pull request by Iucapad**
This commit adds some spacing between the text and the
button in the DomainField.

### CODE REVIEW

**Comment by sdegueldre** [comment]
@robodoo rebase-ff

**Comment by sdegueldre** [comment]
commit conventions: imperative verb + brief description of why the change is needed and why it was broken.

**Comment by Iucapad** [comment]
@sdegueldre I've updated the commits titles and descriptions

**Comment by Iucapad** [comment]
Hey, I've also fixed issues in the settings of website and point_of_sale.

Before: 
image
After: 
image
Legacy: 
image

**Review by sdegueldre — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
