### PR TITLE
[CLA] Update Vauxoo's CLA adding rolandojduartem

### PR DESCRIPTION
**Pull request by rolandojduartem**
Incorporate Rolando Duarte (rolandojduartem) as Vauxoo's contributor.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rolandojduartem** [comment]
Hi, @luisg123v and @mart-e, please, could you review this PR?

cc @desdelinux

**Review by luisg123v — CHANGES_REQUESTED** [review]
Hi @rolandojduartem,

Please target branch 14.0, which is the oldest supported version. Once the change is merged, it will be forward-ported automatically to newer versions.

**Comment by rolandojduartem** [comment]
@luisg123v I think it is ready

**Review by luisg123v — APPROVED** [review]
LGTM :+1: 

Hi @mart-e


Could you review, please

**Comment by mart-e** [comment]
@rolandojduartem @luisg123v no need to ping for each Vauxoo CLA, we have activated codeowners and I am already notified automatically :)
Screenshot 2023-04-04 at 08-05-07 CLA Update Vauxoo's CLA adding rolandojduartem by rolandojduartem · Pull Request #117545 · odoo_odoo

@robodoo r+

**Pull request closed without merging**
