### PR TITLE
[FIX] web_editor: allow to paste images in the editor

### PR DESCRIPTION
**Pull request by Goaman**
task-2734733

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by gaikaz** [comment]
Just migrated our own Odoo Enterprise to v15 and apparently this is a very missed feature!

**Comment by ploegvde** [comment]
@Goaman Think this will be merged soon. We just migrated from V14 to V15 and really miss the pasting of images.

**Comment by Goaman** [comment]
@gaikaz @ploegvde I will try make it merged soon.

@odoo/rd-security Could you have a look?

**Comment by mart-e** [comment]
> rd-security Could you have a look?

@Goaman please explain why you think it's safe code instead :)

**Comment by Goaman** [comment]
@mart-e 

> > rd-security Could you have a look?
> 
> @Goaman please explain why you think it's safe code instead :)

The line and logic that trigger the security flag (`insertHTML`) is the same as before (except for the variable name) and a security review of the method `_prepareClipboardData` has already been done.

**Comment by mart-e** [comment]
"is the same as before" is not really a justification, it's always a good idea to double check if the `_prepareClipboardData` has not changed in the meantime. The goal of my question was to encourage developers have a critical look at their code during review :)

@robodoo override=ci/security
Reason: the content goes through `_cleanForPaste` to prevent inserting unauthorized content.

**Comment by dmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
