### PR TITLE
[7.0][IMP] persist values in constext - tree_but_open

### PR DESCRIPTION
**Pull request by ghost**
On action "tree_but_open" (double-click on a row in the list or tree)
current behavior is to throw out all values of old context. This patch
makes it possible to persist some values of context by putting a list of
keys to be persited with a key "persist_values" in the context itself.
Thereby it solves the problem:
https://www.odoo.com/forum/help-1/question/how-to-preserve-context-across-multiple-actions-wizards-64377
-in addition it may introduce new possibilities in usage of tree_but_open.
This changes are very safe and they don't affect any existing functionality,
please merge it into the main branch

On branch 7.0
Changes to be committed:

modified:   addons/web/controllers/main.py

### CODE REVIEW

**Comment by odony** [comment]
Hi,
Thanks for proposing a patch!
Unfortunately your change cannot be merged, and here are some of the reasons:
- it introduces a new API feature (`persist_values`), and new features are for the `master` branch, not 7.0 (and we don't want this feature anyhow ;-))
- it's not the correct way to fix a bug, if there is a bug it should not require the developer to know about magical keys to put in the context
- the code is way too specific (lots of code for a very minor use case)
- the fix/change is not in the right location (You should not modify this web controller, it's not in charge of dealing with context propagation - this is done for example by the action manager and views in the JS code)
- the code is extremely brittle: all this business with `find`ing and `rfind`ing curly braces inside the context will easily break and corrupt the context. We usually don't want to parse the context string on the server-side , but if we did, we'd have to `safe_eval` it somehow into a dict and take it from there.

Now regarding your problem of context propagation for `tree_but_open` actions, are you sure the problem is still present right now in 8.0? It seems it should have been fixed by commit 8c3d71ccb88950ecc5741c76e7217e478e2f2988. If that fixes the problem we can simply backport the fix in `view_tree.js` to 7.0.

Thanks,

**Comment by tvibliani** [comment]
Hello,

On 10/02/15 16:23, Olivier Dony wrote:
>
> Hi,
> Thanks for proposing a patch!
> Unfortunately your change cannot be merged, and here are some of the 
> reasons:
>
>   * it introduces a new API feature (|persist_values|), and new
>     features are for the |master| branch, not 7.0 (and we don't want
>     this feature anyhow ;-))
>
My intention initially were not to introduce new feature but find 
workaround for the problem I faced.
>
>   * it's not the correct way to fix a bug, if there is a bug it should
>     not require the developer to know about magical keys to put in the
>     context
>
I could not identify this problem as a BUG before. On the event 
"tree_but_open" (click on the row in a list or in a tree) I get 
"active_id" -the id of record clicked, but not the context... Yes, I 
expected to get same context and yes, I was surprised because of context 
reset... but I thought you've designed it this way, that's why I've 
proceed to solution that introduces "feature", and this solution works 
fine for me. Anyway, as you qualify this as bug, I'll open corresponding 
issue for it and I expect that you'll be attentive to the problem.
>
>   * the code is way too specific (lots of code for a very minor use case)
>
  To be precise we are talking about so-called "click on the row" event, 
and its implementation in odoo leaves something to be desired. In terms 
of OOP, if we consider that rows are objects, than "click on the row" 
event (tree_but_open in case of odoo) should provide a way to access the 
state of the object (the row) clicked (to access value of any field of 
the object). Ok then, I hope it's legitimate to have computed fields ( 
fields.function or compute="_foo") which are not saved in the database 
(store=False) and have to compute own value depending on context(some 
value/s from context) of the row clicked?
It should be great and general solution to have context propagated on 
this event, but it isn't and only active_id is not suffice to get values 
of those computed fields, it allows only get fields stored in database. 
Yes, this code is too specific but it completely resolves the problem 
and also it has some advantages, for example it allows to avoid turn 
around unwanted entries in the context upon context propagation, and 
preserve only required ones. (for code size it may be considered that 
this "lot of code" resides under one IF statement and will never execute 
without explicit usage).
>
>   * the fix/change is not in the right location (You should not modify
>     this web controller, it's not in charge of dealing with context
>     propagation - this is done for example by the action manager and
>     views in the JS code)
>
It's honor that you expect me to know where should applied this or that 
change in the base code of Odoo and thanks for the tip about correct 
location, but I was required to develop custom module through broken 
"click on the row" event handler and in the limited time, so I made it 
according my requirements.
>
>   * the code is extremely brittle: all this business with |find|ing
>     and |rfind|ing curly braces inside the context will easily break
>     and corrupt the context. We usually don't want to parse the
>     context string on the server-side , but if we did, we'd have to
>     |safe_eval| it somehow into a dict and take it from there.
>
As you can see in the first commit of this pr, I started work by the way 
you suggest and used 'eval', but finally I preferred string 
concatenation (and I'm persuaded it can't corrupt the context if the old 
one is not already corrupt). Thanks for tip for safe_eval, I see you've 
implemented openerp.tools.safe_eval.safe_eval, seemingly it's just 
wrapper of 'eval' but I'll check if it makes magics.
>
> Now regarding your problem of context propagation for |tree_but_open| 
> actions, are you sure the problem is still present right now in 8.0? 
> It seems it should have been fixed by commit 8c3d71c 
> <https://github.com/odoo/odoo/commit/8c3d71ccb88950ecc5741c76e7217e478e2f2988>. 
> If that fixes the problem we can simply backport the fix in 
> |view_tree.js| to 7.0.
>
Unfortunately I can't confirm this fix. it seems issue still exists, as 
I've updated server and it should be already working properly, but it 
does not. I'll check it again and I'll report back shortly.
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/pull/5191#issuecomment-73690851>.
>

Thank you for your valuable feedback and tips.

With best regards,

**Comment by odony** [comment]
@tvibliani Please don't take my reviews personally. I'm just trying to help you find a solution and/or get your contribution in a shape that we could merge, without having the time to explain in details all my comments. You can freely ignore my comments too ;-)
BTW, please do not open an extra issue, a PR is a kind of issue, and creating an extra issue simply duplicates the information. We also give a much higher priority to PRs than issues anyway. Thank you.

**Comment by tvibliani** [comment]
HI,

Nothing personal of course, but I've already opened the issue #5248 before I've read your comment, sorry about that. It's not just duplicate, there is steps to reproduce and link to example module that can be used as test case, hope this will help. And time I spent by me because of this bug is not comparable with time to write few comments here. Hope all this effort will save time of someone else. As I promised I checked current state of problem with updated v8 server (latest commit 33a8989d77f44b093214550b8f23cb386a990981) which is surely contains the commit you've mentioned as a fix (8c3d71ccb88950ecc5741c76e7217e478e2f2988) and not, it does not fixes [the problem I've posted a few months ago](https://www.odoo.com/forum/help-1/question/how-to-preserve-context-across-multiple-actions-wizards-64377), because as I constated in the above mentioned fix commit, the code is way too specific (problem is seen in terms of "persist fiscal year in context for the chart of accounts" not in terms of "propagate context on tree_but_open actions to have correct implementation of click on the row event", that's why it leaves out some gapes, as I guess "view_list.js" and so on.) are you sure you've same standards for internal work as for prs? ;-) What it concerns to your help, I really appreciate the feedback you provide, thank you again.

Regards,

**Comment by antonylesuisse** [comment]
I close this PR we dont use parent_id on account_account anymore in v9 so the use case doesnt apply anymore.

**Pull request closed without merging**
