### PR TITLE
[IMP] website_sale: allow drag & drop on extra product media

### PR DESCRIPTION
**Pull request by seb-odoo**
This makes the media easier to sort than manually manipulating their sequence.

task-2029597

### CODE REVIEW

**Comment by seb-odoo** [comment]
@JKE-be framework task as been merged in 12.4 so we can use this now.

Not sure about the usability of what they have done, but here is PR so we can test.

**Comment by JKE-be** [comment]
@robodoo r+

**Comment by JKE-be** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Pull request closed without merging**
