### PR TITLE
[REM] l10n_in_schedule6: Remove this module

### PR DESCRIPTION
**Pull request by jva-odoo**
task: https://www.odoo.com/web#view_type=form&model=project.task&id=2039748&active_id=2039748
pad: https://pad.odoo.com/p/r.830a5dede73614d793eeb62e88db4bd1

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@jva-odoo Is there a better explanation than "just no more useful" in the commit message?  Maybe there is a reason why this chart is not used anymore.

**Comment by jva-odoo** [comment]
@jco-odoo ok I try to find the reason. because it's more functional.

**Comment by jva-odoo** [comment]
@jco-odoo I update commit message.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
robodoo rebase-ff

**Comment by KangOl** [comment]
@robodoo retry

**Comment by KangOl** [comment]
@robodoo retry

**Pull request closed without merging**
