### PR TITLE
[FIX] sale_mrp{,_margin}: fix dependency break on purchase_price

### PR DESCRIPTION
**Pull request by tli-asl**
This commit fixes premature usage of `purchase_price` field on
sale.order.line model, before its definition in sale_margin module.

Since this test requires both sale_mrp and sale_stock_margin to pass,
this commit adds an auto-install bridge module that solely address this
issue.

Steps to reproduce:
- Install sale_mrp module
- Run tests (at least .test_kit_cost_calculation)

Problem:
Traceback:
AttributeError: 'sale.order.line' object has no attribute 'purchase_price'

See odoo/odoo#100126

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tli-asl** [comment]
Hi @amoyaux, @DjamelTouati,

I noticed it in odoo/odoo#100126 . As written in commit message, it makes test fail with given configuration (sale_mrp without sale_stock_margin).
Since sale_mrp isn't installed in the Single app Test build during the Nightly batch, it's difficult for you to notice it. On our odoo.sh project, it always fails since we don't need sale_margin module.

I found no other solution than add a new module, but it will require the help of the Runbot team or (IIRC) add a line in the base migration, on the odoo/upgrade repo and I don't have access to it.

I hope you're doing well, have a nice day !

**Review by Whenrow — APPROVED** [review]

**Comment by d-fence** [comment]
Upgrade exception [#164](https://runbot.odoo.com/web/#id=164&view_type=form&model=runbot.upgrade.exception) added.

Waiting the forward-port of this pr, the exception will be applied on all builds, and create an inconsistent state for migrations.
**Please forward port this asap up to master without change.** Exception should be forward-ported before the end of the week.

If you need to apply any change before it reaches master, please notify runbot team.

Details:
```
module:sale_mrp_margin
```
cc @KangOl @nseinlet

**Comment by tli-asl** [comment]
Thanks a lot @d-fence ! :)

Hi @Whenrow ,

Is it possible to r+ then ? Thanks ! :)

Have a nice day !

**Comment by adwid** [comment]
robodoo delegate=DjamelTouati

**Comment by DjamelTouati** [comment]
Thank you for the fix @tli-asl 
@robodoo r+

**Comment by DjamelTouati** [comment]
robodoo r+ rebase-ff

**Pull request closed without merging**
