### PR TITLE
[FIX] web: X2Many read propagates field context


### LINKED ISSUE #29203: [BUG] web: field context is not passed to the record context
Note: I think this one is for @ged-odoo. It assume in-depth knowledge of the web refactoring.

A field context `{'user_preference': True}` defined like this
```python

class Users(models.Model):
    _inherit = ['res.users']
    reporting_standard_ids = fields.Many2many('account.reporting.standard', string='Available Reporting Standards', context={'user_preference': True})
```
or (equivalently) like this
```xml

<field name="reporting_standard_ids" widget="many2many_tags" options="{'no_create': True}" context="{'user_preference': True}"/>
```
**is not passed down to the record context in the js model**, therefore

```js
    _applyChange: function (recordID, changes, options) {
        var self = this;
        var record = this.localData[recordID];
        var field;
        var defs = [];
        options = options || {};
        record._changes = record._changes || {};
        if (!options.doNotSetDirty) {
            record._isDirty = true;
        }
        var initialData = {};
        this._visitChildren(record, function (elem) {
            initialData[elem.id] = $.extend(true, {}, _.pick(elem, 'data', '_changes'));
        });

        // apply changes to local data
        for (var fieldName in changes) {
            field = record.fields[fieldName];
            if (field.type === 'one2many' || field.type === 'many2many') {
                defs.push(this._applyX2ManyChange(record, fieldName, changes[fieldName], options.viewType, options.allowWarning));
            } else if (field.type === 'many2one' || field.type === 'reference') {
                defs.push(this._applyX2OneChange(record, fieldName, changes[fieldName]));
            } else {
                record._changes[fieldName] = changes[fieldName];
            }
        }
   ...
```
fails. Specifically the `rpc read` in
```js
_applyX2ManyChange
```

when there exists a security rule
```xml
  <record id="account_mickey_mouse_rule" model="ir.rule">
      <field name="name">Mickey Mouse Reporting Standard</field>
      <field name="model_id" ref="model_account_reporting_standard"/>
      <field name="global" eval="True"/>
      <field name="domain_force">[('id','in',user.reporting_standard_ids.ids)]</field>
  </record>
```
and the `read` method has been specifically prepared like so:
```python
    @api.multi
    def read(self, fields=None, load='_classic_read'):
        context = dict(self.env.context)
        newself = self
        if context.get('user_preference', None):
            newself = newself.sudo()
        return super(AccountReportingStandard, newself.with_context(context)).read(fields=fields, load=load)
```

### PR DESCRIPTION
**Pull request by nle-odoo**
Most operations on X2Many widget possibly propagates a field context
(name_create, name_search, ...) but the original read or read on an
onchange does not.

With this changeset, the field context is used in these instances.

The assertions added in the added test failed with missing context:
  expected "cruel", result: undefined

fixes #29203
opw-1914466

### CODE REVIEW

**Comment by nle-odoo** [comment]
@aab-odoo 

Here is the fix we spoke about. In our first version it was `record.getContext({fieldName: fieldName})` but that broke a number of tests:

- because the view context was not propagated anymore
- because there was sometimes context like:

```xml
<field name="foo"/>
<field name="o2m_ids" context="{'bar': parent.foo}">
  <tree><field nalme="hello"/></field></tree>
</field>
```
and the xml attribute `context` would already be managed in `rawContext`, but with `record.getContext` it would be evaluated over the record (that had no parent) and not over the list.

**Comment by nle-odoo** [comment]
thanks, done and done (and I intended to add it to many2many section at first but must have lost myself)

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by blaggacao** [comment]
Thanks!

**Pull request closed without merging**
