### PR TITLE
[FIX] web: update pot for many2one translations

### PR DESCRIPTION
**Pull request by juliusc2066**
This commit adds the newly created string from https://github.com/odoo/odoo/pull/135294 into the web pot file.

### CODE REVIEW

**Comment by juliusc2066** [comment]
Does this solve the issue? @oomsveta

**Comment by oomsveta** [comment]
Have you manually updated the `.pot` file? Just re-export it and drop the diff on the date (to limit problems with forward ports), normally it should not only add the new terms, but also remove the previous, now obsolete ones

**Comment by juliusc2066** [comment]
Hello @oomsveta, I guess this solves the issue. How should the forward port be managed on this?

**Review by aab-odoo — APPROVED** [review]
robodoo r+

**Pull request closed without merging**
