### PR TITLE
[FIX] website: Multiple field visibility not working with Multiple Checkbox 16.0 #120631

### PR DESCRIPTION
**Pull request by R55555**
Description of the issue/feature this PR addresses:
There was an issue 'Only one of the multiple fields with conditional visibility become visible upon fulfilling the criteria #120631'

I found the source of the issue inside ./addons/website/static/src/snippets/s_website/form/000.js

Inside the `_buildVisibilityFunction()`
- `formData.get` was used to get the currentValueOfDependency

the `formData.get` will only fetch the first value. In multiple checkbox there are multiple values but `formData.get` was only fetching the first value.

**Changes**
Replaced `const currentValueOfDependency = formData.get(dependencyName);`
with the following

- `const formValid = formData.getAll(dependencyName);`
- `const currentValueOfDependency = formValid[formValid.indexOf(visibilityCondition)];`

`formData.get` was replaced with `formData.getAll` to get all the values. 
First the values are written to `formValid`.
The `currentValueOfDependency` is set as the `visibleCondition` if it is found in the `formValid` which contains all the values selected.

Current behavior before PR:

Created the contact page as given in the issue #120631 and verified the changes. 
Screenshots are attached.
image

When one option is selected
image

When two options are selected
image

When three options are selected
image

Desired behavior after PR is merged:

The fields become visible based on the selection from multiple choices.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by niyasraphy — COMMENTED** [review]
hi @R55555 ,
you have to update the commit message as per the guidelines: https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html

[FIX] website: short description 

detailed description

thanks

**Comment by rdeodoo** [comment]
We will have a look, it might take a few days at least, as it's not a top priority at the moment and will be reviewed between more important internal tasks, as usual.
But this is in our pipe.

Thanks already for the contribution and the apparently fully detailed PR :+1:

**Review by rdeodoo — CHANGES_REQUESTED** [review]
Hello,

Thank you for the contribution, it's really appreciated.

@pierre-pde (cc @qsm-odoo ) this is actually a fair point and something we could improve, but I'd not consider it a bug, and if I did, I'd not fix it and consider it "bug as a feature" for stable version.
People are used to it working like that, the risk/reward is too low IMHO.

It's not even really wrong, being "equal to" means "equal to" not "contains".

What we could actually maybe do is make the (already existing for other fields) "contains" option appear for multiple checkbox.
That would not change the spec and maybe it could even land in 15.0 if judged necessary and if the code is small?

Also, for the commit and the PR itself:
1. You should target 15.0 when you face/fix such a flow: it's where the issue appear, fix it there.
2. No need of uppercase to start your commit title..
3. .. because it should, as per our guidelines, fit the sentence "if applied, your commit will <COMMIT_TITLE>", so ideally start by a verb
4. Your commit message should not overflow 72 char per line, see https://github.com/odoo/odoo/pull/83508#discussion_r796442104

**Comment by pierre-pde** [comment]
@rdeodoo , good idea to make the "contain" available for multiple checkboxes.
Because, I agree with you, let's not change the current behavior.

**Comment by rdeodoo** [comment]
@pierre-pde Great.
@R55555 Do you want to try to implement the "contains" for the multiple checkbox? Otherwise I will create a task internally so someone can work on it.

**Comment by R55555** [comment]
I am closing this pull request now. Will create a new pull request to odoo branch 15.0 after implementing the "contains" for checkbox.

**Pull request closed without merging**
