### PR TITLE
Address format in Poland

### PR DESCRIPTION
**Pull request by zbik2607**
Address format in Poland looks like:

Legionów 93 
91-072 Lodz
Poland

see: http://en.wikipedia.org/wiki/Address_%28geography%29#Poland

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Dear,

I would gladly merge this proposal.

However, since you suggested this proposal, Odoo changed its license, and you are now asked to sign our CLA, in order to contribute.

https://github.com/odoo/odoo/blob/8.0/doc/cla/sign-cla.md

Therefore, either:
 - You sign the CLA, and I merge this proposal keeping you as author of the commit.
 - You do not sign the CLA, and I merge this proposal with me as author, mentioning you in the commit message ("Courtesy of").

Regards,

**Comment by zbik2607** [comment]
I sign the CLA: https://github.com/odoo/odoo/pull/2416
but why failed runbot check I don't know.

Regards,
Dariusz Żbikowski

W dniu 2015-07-09 o 16:58, Denis Ledoux pisze:

**Comment by beledouxdenis** [comment]
Dear, 

It simply because you committed as root <root[at]zefir.krokus.com.pl> while you signed your CLA  as Dariusz Żbikowski <darek[at]krokus.com.pl>.

You can read this documentation to change the email with which you commit:
https://help.github.com/articles/setting-your-email-in-git/

In the mean time, I already merged your proposal in 0f4399bb7b9ed811ebb85f65b47c4a3161283412, taking care to commit your changes as darek[at]krokus.com.pl.

Regards,

**Comment by zbik2607** [comment]
Thank you for your reply and information

Darek

W dniu 2015-07-10 o 11:50, Denis Ledoux pisze:

**Pull request closed without merging**
