### PR TITLE
[ADD] stock: onchange on wizard stock_change_product_qty

### PR DESCRIPTION
**Pull request by nim-odoo**
The proposed value for the new quantity on hand is calculated for the chosen
warehouse.

opw-639641

### CODE REVIEW

**Comment by beledouxdenis** [comment]
Browsing the quants of this product in this location is the way to get the current stock level (I have no idea how it works :p) ? By chance, Is there no existing methods to return you this information on the `product.product` model, or something like that ?

**Comment by nim-odoo** [comment]
To calculate the available quantity, a read_group is performed:
https://github.com/odoo/odoo/blob/8.0/addons/stock/product.py#L210-L212

I adapted the code to do something similar ;)

**Comment by nim-odoo** [comment]
Well, actually I can use '_product_available'

**Comment by beledouxdenis** [comment]
Just one remark: in the specific case of passing a kwargs to a method, PEP8 specify to not put spaces around the =, so in your case:
Replace:
`dict(context or {}, location = location_id)`
by
`dict(context or {}, location=location_id)`

Then it looks fine :).

**Pull request merged**
