### PR TITLE
[FIX][l10n_lu] Change the sign for VP-IC-EX

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Description of the issue/feature this PR addresses:

This PR changes the sign of VP-IC-EX tax

Current behavior before PR:

Currently, the sign on VP-IC-EX tax isn't correct

Desired behavior after PR is merged:

Correct sign on VP-IC-EX.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
OPW 677605

**Comment by adrienpeiffer** [comment]
@sbidoul Can you review this one ?

**Comment by sbidoul** [comment]
:+1: 

This is comparable to VP-IC-0, and has been confirmed by a professional accountant.

**Comment by qdp-odoo** [comment]
merged at https://github.com/odoo/odoo/commit/2779d463e80eaf903e789c29991a1faef8d07445

thanks for the contribution

**Pull request closed without merging**
