### PR TITLE
Convert xmlrpc/api Python to Python 3

### PR DESCRIPTION
**Pull request by xmo-odoo**
No big changes, but replaces the "Python 2" tabs by "Python 3" and uses the proper import/package (`xmlrpclib` was moved to `xmlrpc.client`)

### CODE REVIEW

**Comment by amigrave** [comment]
@xmo-odoo quelle vengeance !

**Comment by pedrobaeza** [comment]
I don't think you should remove Python 2 tab, but add the Python 3 one. Although you run a Python 3 >=v11 Odoo, you still can connect through XML-RPC with a Python 2 script.

**Comment by mart-e** [comment]
In v11, it was unclear which version of python we should use. Now it has been migrated to py3 since over a year, we can make python 3 the reference IMHO.
Obviously it still works to call it in python 2 as it works for many different languages that we do not document here. The python 2 way is still documented in the v11 documentation so it is fine to me.

robodoo delegate=amigrave (because vengeance I guess...)

**Comment by mart-e** [comment]
robodoo retry

**Comment by xmo-odoo** [comment]
robodoo r-

**Comment by xmo-odoo** [comment]
robodoo r+

**Pull request closed without merging**
