### PR TITLE
[FIX] stock: fix lot when updating move line & unable to reserve quants

### PR DESCRIPTION
**Pull request by kitan191**
- Install stock
- Go to Inventory > Configuration > Settings and enable "Lots" and "Storage Locations"
- Create a Product tracked By Lots (i.e. Product X)
- Go to Inventory > Operations > Inventory Adjustments
- Create an Inventory Adjustment for Product X:

     Product   |   Location   |   Lot/SN   |   Real Quantity
    Product X  |   WH/Stock   |   LOT 01   |       20
    Product X  |   WH/Stock   |   False      |       10

- Validate Inventory
- Go to Inventory > Operations > Transfers and create one:
  * Source Location: WH/Stock
  * Destination Location: WH/Stock/Shelf1
  * Operation Type: Internal Transfers
  * Operations:
    [Product: Product X, Initial Demand: 25]
- Save Transfer, Mark As Todo and Check availability
- Click on list icon of Operation line for Product X to display Detailed Operations
- 20 units of LOT 01 and 5 units without lot have been reserved
- Set LOT 01 for the 5 reserved units without lot and confirm
- Open Detailed Operations again
- There are now 20 units of LOT 01 and 5 units of LOT 01
- Remove the row with 5 units and confirm
- Check availability and open Detailed Operation
- There is now only a row with 25 reserved units of LOT 01
- Unreserve
The following errror is raised:
"It is not possible to unreserve more products of P than you have in stock."

This is due to a mismatch between Lot and Quant.
When updating lot_id of the 5 units without lot with LOT 01, it tries to reserve 5 Quants
of LOT 01. As there is no more Quant available for LOT 01, it reserves 5 untracked Quants
instead.
However it still updates lot_id of move line to LOT 01, which is incorrect.
So when the move line with the 5 units is removed, it unreserves 5 units of LOT 01, although
it was untracked units that were reserved.
This is leading to incorrect data in "stock.quant" table:
* There are 15 reserved units of LOT 01, instead of 20.
* There are 5 reserved untracked units, instead of 0.

To prevent this to happen, lot_id of move line has to be set to False if untracked quants
have been reserved as a fallback.

opw-2419444

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kitan191** [comment]
Hi @amoyaux 

Could I get your opinion on this ?
Thanks.

**Comment by kitan191** [comment]
Hmmm... From the failing tests, it seems that the lot_id has to be set to the move line.
The untracked units become tracked with the desired lot, am I correct ?
Should I update `stock.quant` accordingly instead ?

**Comment by amoyaux** [comment]
@kitan191 I checked and it's not a trivial fix. I will do it. It needs to modify some stock basics

**Comment by kitan191** [comment]
> @kitan191 I checked and it's not a trivial fix. I will do it. It needs to modify some stock basics

Effectively. I've also tried to edit the Quants when untracked units were used, but several tests were failing too.

Thanks.

**Comment by gfcapalbo** [comment]
> 
However it still updates lot_id of move line to LOT 01, which is incorrect.
So when the move line with the 5 units is removed, it unreserves 5 units of LOT 01, although
it was untracked units that were reserved.
This is leading to incorrect data in "stock.quant" table:

There are 15 reserved units of LOT 01, instead of 20.
There are 5 reserved untracked units, instead of 0.



We can confirm we have the same behaviour on a client instance.

**Pull request closed without merging**
