### PR TITLE
[FIX] mail: mention suggestion overflowing

### PR DESCRIPTION
**Pull request by seb-odoo**
task-2275828

### CODE REVIEW

**Comment by alexkuhn** [comment]
Overflow management looks good in all thread view.

Something is weird with click on extra suggestion: the 1st click is not registered and instead scroll to top:
extra-suggestion-1st-click-issue

The 2nd click on the same extra suggestion works fine, but click on another extra suggestion and it does the same thing.
For some reasons, main suggestions are not affected by this bug. Also in chatter the bug also happens but 2nd click on another extra suggestion works fine (so slightly less buggy?).

**Comment by seb-odoo** [comment]
Ok I'll check, I suspect this is because of the `_update` that does not use hint, so it's scrolling more than necessary at some random render. I'll add a hint I guess.

**Comment by seb-odoo** [comment]
Hopefully this should be good now with a hint, please confirm on your OS/browser.

Also noticed and fixed an issue with modifier keys resetting suggestion state, in particular shift+tab was just not working correctly (triggering RPC every time + resetting active item to the first one).

**Review by alexkuhn — APPROVED** [review]
@robodoo r+

**Comment by seb-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
