### PR TITLE
[FIX] point_of_sale: issue in POS when decimal separator is not "."

### PR DESCRIPTION
**Pull request by kirca**
https://github.com/odoo/odoo/issues/9395

### CODE REVIEW

**Comment by jorenvo** [comment]
Why would you like this change? As far as I can tell `get_amount_str` is only used when setting the default value on the paymentline input element. What is the exact bug your trying to correct?

**Comment by kirca** [comment]
Did you check the related issue https://github.com/odoo/odoo/issues/9395?

The bug is that if the decimal separator for the used language is different than "." it will mess up the calculation since default value always has "."

pos_decimal_separator_bug

**Comment by jorenvo** [comment]
Alright, just to confirm, that only happens if you change the value, right? When you click on a bank journal to register payment the change should be correct (=0). Only when you update the payment field (15.90 in your screenshot) and everything gets recalculated it'll be wrong right?

**Comment by thomasklosinsky** [comment]
I may have got your question wrong...
... in most translations the autofilled decimal separator is right, but in german or spanish etc. the autofill is wrong and even without manual value change it looks like that. The change value reloads when clicking somewhere in the window or in pamynet amount and shows something like in the picture...

**Comment by jorenvo** [comment]
Fixed in dda904c13392473c0e213078cbb6fc73374a96a0.

**Pull request closed without merging**
