### PR TITLE
[FIX] base: guess img placeholder size from field name

### PR DESCRIPTION
**Pull request by Dj0ulo**
__Current behavior before PR:__
When no width and height is set to resize an image, the dimensions are guessed using the field name. For instance, an image field with `field_name = "XXXX_123"` is resized to 123 pixels when fetched. However this guess should be done only to know the size of the placeholder to display if there is no actual image. When there is an image stored in the field, there is no need to guess size.

__Description of the fix:__
Move the call to the method `image_guess_size_from_field_name` in the condition where the `stream` is not set and therefore a placeholder is displayed instead.

Related: https://github.com/odoo/odoo/pull/117343

### CODE REVIEW

**Review by Julien00859 — APPROVED** [review]
Usually I would had asked for a test but since the related PR suggested to remove `image_guess_size_from_field_name`, I guess we'll be fine without

@fw-bot ignore
@robodoo r+

**Comment by seb-odoo** [comment]
Why disabling the forward-port for this one? The fix looks applicable in saas versions too and in master until further refactoring to remove it?

**Comment by Julien00859** [comment]
@Dj0ulo can you do another PR for saas-16.1 removing the function?

**Comment by Dj0ulo** [comment]
Sure ! Will do that on tuesday

**Comment by lse-odoo** [comment]
@Dj0ulo up

**Pull request closed without merging**
