### PR TITLE
[FIX] point_of_sale: translate text used to generate account move lines description.

### PR DESCRIPTION
**Pull request by legalsylvain**
closes: #174647

Forward port of #174511 (Original PR in V16)

CC : @vlst-odoo

Note : i only cherry-picked the change of the .py file. I think that it was not a good idea to change the pot / po files in the original PR because when we forward-port the PR it generates conflicts on each version. This one should be OK against 17.0 (+ saas + master versions)

### CODE REVIEW

**Review by vlst-odoo — APPROVED** [review]
robodoo r+

**Comment by legalsylvain** [comment]
> @legalsylvain sorry for the confusion with the r+/r-. I've moved your changes to the branch on odoo-dev and r+ed there

I'm pretty lost in all that robodoo options ! but let me know if I have something to do ! 

Thanks for your time.

Side question (nothing to do with the current topic) : 

- is it robodoo documented ? 
- is it robodoo code open source ? It can be interesting for the OCA to have similar options to port easely patches in https://github.com/OCA/oca-github-bot/. CC : @sbidoul, @pedrobaeza

**Comment by pedrobaeza** [comment]
robodoo can't be used for OCA, as it's very tighted to runbot and works with a different approach having migrations and enterprise links.

**Comment by legalsylvain** [comment]
> robodoo can't be used for OCA, as it's very tighted to runbot and works with a different approach having migrations and enterprise links.

Yes, I guess a lot of think should be refactored. It was just about "having inspiration" about features.

**Comment by legalsylvain** [comment]
robodoo help

**Comment by pedrobaeza** [comment]
I don't think it serves. The main feature, which is the automatic forward-ports, can't be used, as OCA contributors don't have write access to the generated branch if they need to do any change, so most of the times we will have a lot of useless PRs that have to be closed, on contrary than Odoo, that all the employees are allowed on odoo-dev fork. And I think we shouldn't hijack this thread with this off-topic.

**Comment by vlst-odoo** [comment]
> robodoo help

this is the wiki https://github.com/odoo/odoo/wiki/Mergebot @legalsylvain

**Pull request closed without merging**
