### PR TITLE
[IMP] stock: use optimization on searching by qty_available

### PR DESCRIPTION
**Pull request by yelizariev**
Such requests could be done via Products list and there is no reason to don't
use optimization

---

opw-2452728
https://github.com/odoo/odoo/commit/9daf3f85a8a3b012a79226fe13d3cde2293fcce0

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
Explained here: https://github.com/odoo/odoo/pull/65604#discussion_r572712001

**Comment by amoyaux** [comment]
robodoo r+

**Comment by nda-odoo** [comment]
@yelizariev @amoyaux https://www.awesomescreenshot.com/video/3089506?key=b2cecafe9e00b604452fc410cba20099

It seems that the search is not working correctly anymore, I guess there was a reason to not use it after all ;-)

**Comment by amoyaux** [comment]
@nda-odoo It's a kit?

**Comment by yelizariev** [comment]
I guess we need extend this part of code with cases when there are no records found

https://github.com/odoo/odoo/blob/1efece5e44c2a69435184b98cb7a984acc881e90/addons/stock/models/product.py#L343-L346

**Comment by yelizariev** [comment]
@nda-odoo could you test my patch https://github.com/odoo/odoo/pull/68028

**Pull request closed without merging**
