### PR TITLE
[FIX] l10n_latam_invoice_document: you should not be able to change t…

### PR DESCRIPTION
**Pull request by jco-odoo**
…he document type and number in the first place

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@jjscarafia The extra verification seems like some extra fail-safe, but the onchange/inverse is not a place where this should be checked.  It should have been avoided to change the document type/id in the first place.  And here for Chile we want to extend the conditions and then we would need to inherit this method again, but this really seems overkill.  Could you agree on this PR?

**Comment by jjscarafia** [comment]
hi @jco-odoo 
Not sure why but this PR seems to be broken the behavior of setting the first number on new invoices.
Check this video https://drive.google.com/file/d/13fAtn3dehvMUJrlwQKsMbK1H3w4ZA_DA/view

cc @zaoral

**Comment by jco-odoo** [comment]
@jjscarafia For the or not highest_name of course. (which allowed more possibilities...)  So the idea would be to remove the l10n_latam_manual_document_number as well.  Let me adjust the code...

**Comment by jco-odoo** [comment]
@vbe-odoo

**Comment by ren-odoo** [comment]
Hi @jco-odoo I did the test with a new journal for AR using several document types and it works correctly, same case for Chile.  But I'm having an issue when trying to validate diferent document types over the default Journal in AR:

image

@jjscarafia @zaoral  any idea of why is this happening?

cc. @vbe-odoo

**Comment by zaoral** [comment]
HI @ren-odoo 

I have made a quick review, and I think that the problem is related to the Preprinted journal that shares the sequence between all the document types.

image

The last FA-B is 1-5 and is trying to create the 1-6, but actually, the FA-A 1-6 already exists and I suppose that is the reason that you get the error message. I think that the number of this invoice should be 1-17. because the last number used is 1-16

image

I will make local test to review why this is happening and how to avoid it

cc @jco-odoo @jjscarafia

**Comment by jco-odoo** [comment]
@zaoral @ren-odoo @vbe-odoo Maybe this pre-printed error is totally unrelated to what we are trying to do here.

**Comment by vbe-odoo** [comment]
Hi @zaoral @jco-odoo @ren-odoo I can see this is also happening in a general runbot DB, without the changes from this PR.
Is happening only when using pre-printed with demo data, and with the pre-printed Journal that is created, and document Types that are B (FACTURAS B, RECIBOS B, NOTAS DE DEBITO B).
If I create a new pre-printed Journal, and I assigned the sequence for FA-A and FA-B this error doesn't pop up.

So maybe is related to the demo data, or something else... because I couldn't replicate it with the new pre-printed Journal. The weird behavior with the already created pre-printed Journal is that is trying to use the prefix FA-A instead of the FA-B...

Bests!

**Comment by jco-odoo** [comment]
@william-andre Can you review this change?

**Comment by ren-odoo** [comment]
> hi @jco-odoo
> Not sure why but this PR seems to be broken the behavior of setting the first number on new invoices.
> Check this video https://drive.google.com/file/d/13fAtn3dehvMUJrlwQKsMbK1H3w4ZA_DA/view
> 
> cc @zaoral

Hi @jjscarafia I did a functional test of this PR an it seems to work correctly but if possible can you also take a look in you side in case I missed something in my test. 

Thank you . 

cc. @vbe-odoo

**Review by jjscarafia — APPROVED** [review]
LGTM
The previous error mentioned on the video is there not anymore.

**Comment by jco-odoo** [comment]
@william-andre Could you give ok here?

**Comment by ren-odoo** [comment]
Hi @william-andre have you had any chance to take a look at this PR?

Thank you.

**Review by william-andre — COMMENTED** [review]
@robodoo r+

Doesn't seem to break anything and you all seem to know the implications of this :see_no_evil: 
I don't seen anything obvious at least

**Pull request closed without merging**
