### PR TITLE
[FIX] web: Unblocking for self target

### PR DESCRIPTION
**Pull request by har-odoo**
Description of the issue/feature this PR addresses:
The screen continues to load even after the report is downloaded as the unblock function is not called after redirection.
https://github.com/odoo/odoo/blob/saas-16.1/addons/l10n_fr_fec/wizard/account_fr_fec.py#L403-L408
https://github.com/odoo/odoo/pull/107830/files
[OPW-3268315](https://www.odoo.com/web#id=3268315&cids=2&menu_id=4720&action=4043&model=project.task&view_type=form)

Current behavior before PR:
After the FEC report is downloaded, the screen continues to load.
The report is returned with the type 'ir.actions.act_url' and target 'self' where the unblock function wasn't called.

Desired behavior after PR is merged:
After the FEC report is downloaded, the screen doesn't keep loading and the wizard is editable again.
The report is returned with the type 'ir.actions.act_url' and target 'self' where the unblock function is called.

Co-authored by: @kbs-odoo 
 
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kbs-odoo** [comment]
Hello @brboi , @BastienFafchamps ,

Can you give it a look?

**Comment by har-odoo** [comment]
Hello @brboi,
I see that you were looking into this.
Is there any update on the status or does the fix need to be changed?

**Comment by brboi** [comment]
Hello @har-odoo 

Sorry did not take time yet to analyze this.

But it seems false as it kind of reverse the intent behind the PR that introduced this line https://github.com/odoo/odoo/pull/107830 

cc @aab-odoo

**Comment by har-odoo** [comment]
> Hello @har-odoo
> 
> Sorry did not take time yet to analyze this.
> 
> But it seems false as it kind of reverse the intent behind the PR that originally introduced this line #107830
> 
> cc @aab-odoo

Yes, that is understood but it is either this fix or will have to interchange the value of willUnload.
The reason is unblock function is not being called which will be called by either of the above changes only.

**Comment by har-odoo** [comment]
Hello @brboi,
Did you have time to look over this according to your previous comment?
cc: @aab-odoo

**Comment by Levizar** [comment]
It is solved here: https://github.com/odoo/odoo/pull/129564

**Pull request closed without merging**
