### PR TITLE
[FIX] l10n_pe: adapt account group

### PR DESCRIPTION
**Pull request by william-andre**
The account.group model has been refactored in https://github.com/odoo/odoo/commit/a124050511d508f6f1f8a4d4f9dfb2fa1507ad98

Although the filename was correct (.template) and one field was changed
(code_prefix -> code_prefix_start), we don't accept a parent anymore and
we have to provide the chart of account id.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by william-andre** [comment]
@jco-odoo I forgot to migrate l10n_pe while refactoring `account.group`. Better late than never...

**Comment by william-andre** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by jco-odoo** [comment]
@nhomar fyi

**Pull request closed without merging**
