### PR TITLE
[IMP] website_sale: access rights for portal user to access account t…

### PR DESCRIPTION
**Pull request by hch-odoo**
…ax has been added

Description of the issue/feature this PR addresses:

Issue - https://www.odoo.com/web?#id=776347&view_type=form&model=project.issue&action=609&menu_id=4720

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by nhomar** [comment]
instead open all the taxes, the correct solution should not be fix with sudo when those must be read?

**Comment by JKE-be** [comment]
@nhomar 

I discuss with @qdp-odoo some weeks ago, and it doesn't seem to find it critical to make it visible.

https://github.com/odoo/odoo/commit/42c8da4edcae6ed9c6da9b647b36a63a94875ce9#diff-eece21a94897b9442a4ac137a65ac84dR18 already add access for public user. (To support this commit: https://github.com/odoo/odoo/commit/0e562c8a7d825cd6c162093422fb023c643ec3df#diff-d28c0a9be1296e0b51d2810df4f97f5c)


Anyway, fwd port of this fix (https://github.com/odoo/odoo/commit/ee7cfba9175fb697d018f3c1e3608e16ea8521c0#diff-d28c0a9be1296e0b51d2810df4f97f5c) from v10 to v11 add the sudo() making these access right maybe useless. 

But IMO, except if tax is a secret, I prefer to give a read access on it that use sudo()

**Comment by nhomar** [comment]
let me see a critical option.

IF you open all the taxes, I can simply look for all of them and retreive the company an all the taxes (the company name).

With that information I can know how much companies are available on that odoo instance and it can be a free information that should not be given.

I know it is a little bit paranoic, but I do not like open 100% of a table if it is not MANDATORY, but I actually understand your point, I just hope I made mine more clear.

**Comment by hch-odoo** [comment]
already fixed at https://github.com/odoo/odoo/commit/42c8da4edcae6ed9c6da9b647b36a63a94875ce9

**Pull request closed without merging**
