### PR TITLE
[FIX] stock: Fixed typo

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: Fixed typo

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sswapnesh** [comment]
Ping @sle-odoo 
https://github.com/odoo/odoo/blob/4b8689b86b2393b7ead48adbf081ea722aa75d31/addons/stock/wizard/stock_picking_return.py#L2

**Comment by Yenthe666** [comment]
Haha this is about the smallest 'fix' I have ever seen. 😂

**Comment by sswapnesh** [comment]
and most _ineffective_ typo.

**Comment by sswapnesh** [comment]
and most _ineffective_ typo.

**Pull request closed without merging**
