### PR TITLE
12.0 customer display snippets nje

### PR DESCRIPTION
**Pull request by nje-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR: https://drive.google.com/file/d/194FxqlvkU8ufgWP6ZLL2GYR2hy8_yR7K/view

Desired behavior after PR is merged: https://www.awesomescreenshot.com/image/3632599/1d003efbbe540752bd3200fbe6fdae3b

### CODE REVIEW

**Comment by nje-odoo** [comment]
Hello @rdeodoo 
Re-target this branch saas-11.5-customer-display-snippets-nje to 12.0-customer-display-snippets-nje

**Comment by rdeodoo** [comment]
@pimodoo Could you r+ this one if good for you? Coming from forgotten https://github.com/odoo/odoo/pull/27272
Had a quick look it indeed fixes the behavior shown in screen shot. BS4 migration issue.

**Comment by pimodoo** [comment]
@lap-odoo You talked about this feature earlier, could you tell me if this fix is functionnaly ok in 12.0, and if you still need to delete the feature in master or not depending on this fix?

**Comment by rdeodoo** [comment]
@pimodoo From what we talked yesterday with @lap-odoo she created a task to remove it in master and is ok to fix the behavior in 12.0

**Comment by lap-odoo** [comment]
@pimodoo The fix is ok for V12 and for master, we can still discuss it but the feature is not that useful implemented as it is.

**Comment by pimodoo** [comment]
robodoo r+ rebase-ff

**Comment by mart-e** [comment]
robodoo retry

**Pull request closed without merging**
