### PR TITLE
get_memory_info was depricated and now it was removed from psutil

### PR DESCRIPTION
**Pull request by Assem**
If odoo starts with worker, you will get AttributeError: 'Process' object has no attribute 'get_memory_info'
Because the depricated function get_memory_info doesn't exists anymore in the new version of psutil

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

You should keep both method in a wrapper for compatibility.
It was already done in 8.0 at 3940a096b2f0c5cf9815f9abac43a6df920a15d7 but not backported to 7.0.

**Comment by Assem** [comment]
Hello,

Done ;)

**Comment by mart-e** [comment]
Thanks for the update however this still doesn't work because of an import loop (the failed test was not really helpful as too early and did not log anything).
I have put the method in netsvc.py instead of workers.py and merged the backport at 1c0bc7cc1619ffde52e5bc92afb954052883d4a5
Thanks for raising the issue in 7.0

**Comment by Assem** [comment]
Welcome ;)

**Pull request closed without merging**
