### PR TITLE
[CLA] signature for leogavidia

### PR DESCRIPTION
**Pull request by leogavidia**
[CLA] signature for leogavidia

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `l...@ruby.ec`
- you are signing _for_ the address `l...@gaheos.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by mart-e** [comment]
Thanks for the review.
I can not modify your branch so could you squash your commits and change the commit message to something like `[CLA] signature for leogavidia`?

Thanks

**Comment by leogavidia** [comment]
Thanks for your feedback. I have made the requested change.

**Comment by mart-e** [comment]
Hi,
Thanks but this isn't the case. See https://github.com/odoo/odoo/pull/68183/commits you can see you have 4 commits while it should only have one left.
If you are not sure on how to proceed to squash them, the easiest is to create a new pull request from a new branch containing only one commit.
Best,

**Comment by leogavidia** [comment]
Hi,  I have posted a new pull request #68842.

**Pull request closed without merging**
