### PR TITLE
[IMP] web_editor: add support for youtube shorts video and live stream

### PR DESCRIPTION
**Pull request by SergeBayet**
Before this PR, embedding a YouTube Shorts video and Live Stream on a website was not possible, resulting in an error message indicating that the provided URL was invalid.
This PR introduces support for embedding YouTube Shorts videos and Live Stream into website content.

task-3818315

Co-authored-by: Keval Bhatt <ksbh@odoo.com>

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo delegate=bvr-odoo 
@bvr-odoo

**Comment by bvr-odoo** [comment]
@ksbh-odoo please check why the runbot is not green, thanks

**Comment by ksbh-odoo** [comment]
> @ksbh-odoo please check why the runbot is not green, thanks

> @bvr-odoo runbot is green

**Comment by bvr-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
