### PR TITLE
[FIX] sale_management: (revert) handle temp recs

### PR DESCRIPTION
**Pull request by ethanrobv**
This PR reverts the commit
https://github.com/odoo/odoo/commit/c6842f1

opw-3754297

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me, wouldn't this be equivalent of `new_sol.order_id = False` (which I would expect to update the order_line one2many linked to order_id) that was before the original commit? Here it seems a little complex to understand what we are doing to me (why not fetch `order_line` instead for example)

robodoo delegate+

**Comment by nle-odoo** [comment]
yes, it's a little hard to understand, I've also tried this change (get back to original code):

```diff
diff --git a/addons/sale_management/models/sale_order_option.py b/addons/sale_management/models/sale_order_option.py
index bc9ea344d1a6..2d8d4f8db5dc 100644
--- a/addons/sale_management/models/sale_order_option.py
+++ b/addons/sale_management/models/sale_order_option.py
@@ -90,8 +90,7 @@ class SaleOrderOption(models.Model):
             new_sol._compute_price_unit()
             option.price_unit = new_sol.price_unit
             # Drop the temporary record from the cache
-            new_sol.invalidate_recordset(flush=False)
-            option.order_id.order_line.fetch(['id'])
+            new_sol.order_id = False
 
     @api.depends('product_id', 'uom_id', 'quantity')
     def _compute_discount(self):
@@ -104,8 +103,7 @@ class SaleOrderOption(models.Model):
             new_sol._compute_discount()
             option.discount = new_sol.discount
             # Drop the temporary record from the cache
-            new_sol.invalidate_recordset(flush=False)
-            option.order_id.order_line.fetch(['id'])
+            new_sol.order_id = False
 
     def _get_values_to_add_to_order(self):
         self.ensure_one()
```
and the test works

also with this change:

```py
diff --git a/addons/sale_management/models/sale_order_option.py b/addons/sale_management/models/sale_order_option.py
index bc9ea344d1a6..d5adee90864b 100644
--- a/addons/sale_management/models/sale_order_option.py
+++ b/addons/sale_management/models/sale_order_option.py
@@ -89,9 +89,6 @@ class SaleOrderOption(models.Model):
             new_sol = self.env['sale.order.line'].new(values)
             new_sol._compute_price_unit()
             option.price_unit = new_sol.price_unit
-            # Drop the temporary record from the cache
-            new_sol.invalidate_recordset(flush=False)
-            option.order_id.order_line.fetch(['id'])
 
     @api.depends('product_id', 'uom_id', 'quantity')
     def _compute_discount(self):
@@ -103,9 +100,6 @@ class SaleOrderOption(models.Model):
             new_sol = self.env['sale.order.line'].new(values)
             new_sol._compute_discount()
             option.discount = new_sol.discount
-            # Drop the temporary record from the cache
-            new_sol.invalidate_recordset(flush=False)
-            option.order_id.order_line.fetch(['id'])
 
     def _get_values_to_add_to_order(self):
         self.ensure_one()
```
the test also works.

But if there is the invalidated_recordset (only from 17.0, it works in 16.0 up to saas-16.4) it doesn't work.

So is the original issue happening in 17.0?  maybe we could just keep the current code (so revert the fix) if the issue from a change in ORM (or in business code) did not happen in 17.

**Comment by ethanrobv** [comment]
@robodoo r+

**Comment by ethanrobv** [comment]
@fw-bot ignore

**Comment by Feyensv** [comment]
robodoo delegate+ too

**Pull request closed without merging**
