### PR TITLE
[ADD] base: quick-open/navigate to model

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Have quick access and insights into the model/fields data

Current behavior before PR: Before this commit you can only see the name of the model. If you however want to quick view details about the model/fields you will need to do so in another tab.

Desired behavior after PR is merged: By adding a button which returns the model in an action we can quick view the model/fields. This should make it easier for devs to quickly check model details & speedup the development/testing

Sample screenshot:
image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Comment by Yenthe666** [comment]
@mart-e I _think_ you are the best guy here? :)

**Comment by mart-e** [comment]
You can use the `_get` method but to check with our rather technical product owner @bouvyd for the feature.

**Comment by Yenthe666** [comment]
@bouvyd could you give me a feedback on this please? 🙏

**Review by VincentSchippefilt — CHANGES_REQUESTED** [review]
Model is not required on `ir_ui_view` so this widget doesn't behave well.
The real question is, why isn't model a many2one to ir.model and we could just use the many to one widget

**Comment by Yenthe666** [comment]
> Model is not required on `ir_ui_view` so this widget doesn't behave well. 

I know it isn't but I did a check on the views. Every single Form/Tree/Kanban/Gantt/.. has a `model` set. 
The only exception is the view type `QWeb` actually. Sample on latest runbot:
image

Possible options could be to hide the action/text when there is no `model` set or raise a `Warning` when no `model` is set?

> The real question is, why isn't model a many2one to ir.model and we could just use the many to one widget
Don't know, I guess it was some technical choice years ago by the devs? My thought was there was no way it would be accepted to change it to `Many2one` (especially not so close to V16) and this was the most minimal diff in code :)

Let me know what you'd like or want from me and let's make it happen 🤞

**Comment by Yenthe666** [comment]
@VincentSchippefilt I hope you don't mind me reminding you about this one 🤞 Could you let me know how you would like to continue please?

**Comment by VincentSchippefilt** [comment]
As this will be a change in model, it will be for master. I have created a task (id : 3007619) to make the correct change, that is to remove the duplication of the model.model inside ir_ui_view, and replace it with a one2Many

**Comment by Yenthe666** [comment]
@VincentSchippefilt I don't really get why you'd kill/close this off though. My PR has zero changes on models/fields, works out of the box and could be an ideal in-between solution for V16? You guys can then make the 'finale' solutions changing it to a `One2many` and do the clean-up for the next V17?

**Comment by VincentSchippefilt** [comment]
Adding custom code to replicate a standard feature of Odoo is not a good idea: it increases the way we can break things in the next versions.
Here we "just" want a navigable relation between 2 tables, that's a standard many2one. We are already looking into the design of this relation - nothing is ever as easy as we (at least I) think - and will create a new PR with a valid design.

I'm closing this PR because I disagree with the implementation and need some time to come up with a better one. I'll ping you on the PR (post OXP) so you can follow it up.

**Pull request closed without merging**
