### PR TITLE
16.0 pos paytm add pos payment method paytm habh

### PR DESCRIPTION
**Pull request by jva-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by caburj** [comment]
May I know why we switched branch?

**Comment by AntoineVDV** [comment]
Converted to draft as it doesn't seem to be the final version.

**Comment by qle-odoo** [comment]
@habh-odoo as Antoine told you, we are not going to create a payment provider (a lot of discussion on this subject)
So first we will keep the credentials in the payment method model.
In the future we will create a `pos.payment.provider`
make this modification then I will look again at your PR
cc @AntoineVDV @dama-odoo

**Comment by hamo-odoo** [comment]
Move to - https://github.com/odoo/odoo/pull/133334
Targeted to saas-16.4
cc: @jva-odoo @qle-odoo @AntoineVDV

**Comment by qle-odoo** [comment]
https://github.com/odoo/odoo/pull/133334#issuecomment-1696962242

**Pull request closed without merging**
