### PR TITLE
[IMP] l10n_vn: anglo-saxon accounting set default as true

### PR DESCRIPTION
**Pull request by hpr-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by anothingguy** [comment]
hi @jco-odoo, @hpr-odoo
Use `use_anglo_saxon` as default is not suitable for Viet Nam accounting System. Could you tell me some reasons for this commit ?

**Comment by davidtranhp** [comment]
> hi @jco-odoo, @hpr-odoo
> Use `use_anglo_saxon` as default is not suitable for Viet Nam accounting System. Could you tell me some reasons for this commit ?

I have proposed a PR here https://github.com/odoo/odoo/pull/63288

**Comment by jco-odoo** [comment]
@davidtranhp We would be in favour to not use anglo-saxon where it is not needed, but the question was asked here explicitly internally, so I want to check the origins a bit further first.  @pfa-odoo @tsb-odoo

**Pull request closed without merging**
