### PR TITLE
[IMP] l10n_nl: Improved accounting data related to taxes, the fiscal …

### PR DESCRIPTION
**Pull request by smetl**
…position, tax group

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by epictete** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
@smetl @epictete seems to be failing on enterprise:
https://runbot.odoo.com/runbot/build/23922563

**Comment by smetl** [comment]
@robodoo retry

**Comment by epictete** [comment]
@robodoo r+

**Comment by epictete** [comment]
@robodoo r+

**Pull request closed without merging**
