### PR TITLE
[REM] base,web: delete menu Apps Store, Updates

### LINKED ISSUE #72902: [14.0] server error when trying to update module from the updates menu.
Impacted versions: 14.0

Steps to reproduce: enter apps, updates and try to update any module

Current behavior: system error

Expected behavior: module update

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: button_immediate_upgrade() takes 1 positional argument but 2 were given

### PR DESCRIPTION
**Pull request by yelizariev**
Those menus are supposed to be integrations with apps.odoo.com, but it doens't
work and not maintained.

Existing menus that open apps store links should be enough:

* Apps >> Apps >> Theme Store --> https://apps.odoo.com/apps/themes
* Apps >> Apps >> Third-Part Apps --> https://apps.odoo.com/apps/modules

---

close #72902

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
screenshot-9218443-master-all runbot35 odoo com-2021 08 03-10_19_48

**Comment by JKE-be** [comment]
Why remove instead to fix... ? not sure...

Updates is the easy way to check that your module are up to date. 
And it works as expected to compare your version with the appstore ...
image

**Comment by bouvyd** [comment]
@yelizariev can you retarget master? but yes, i agree that it should go

@JKE-be why kill it and not fix it:
- requires a setting in .odoorc
- apps.odoo.com answer with a 404 for the sep-a.gif, therefore the client never loads (are  you running your own app store?)
- this mechanism has not been in use for years, is referenced nowhere on apps.odoo.com or in our documentation

**Comment by bouvyd** [comment]
> why??

My bad, it's not a CLI option but the permissions of a folder - cfr #15225 (disabled by default)

> So if we prefer remove feature instead to fix and promote it,... Feel Free

Alright, let us feel free then :)

@reviewers:
Emporor Palpatine saying "DO IT" with an aggressive expression

**Comment by madprog** [comment]
> > apps.odoo.com answer with a 404 for the sep-a.gif
> 
> It is probably the case recently, since the upgrade of appstore in 10/22. Before this date, it was working.
> 
> Probably not used a lot, else we should have support ticket. So if we prefer remove feature instead to fix and promote it,... Feel Free... Btw, you will have what you want at the end so I will not fight about it.

Will be fixed with odoo/saas-automation#392, already deployed on the production server.
(adding a nginx rewrite from `/web/static/src/img/sep-a.gif` to `/web/static/img/sep-a.gif`)

**Comment by yelizariev** [comment]
New PRs:
https://github.com/odoo/odoo/pull/106379
https://github.com/odoo/enterprise/pull/34324

(rebased and with a proper branch name)

**Comment by CasVissers-360ERP** [comment]
Can we please get an alternative here? How can I easily check for updates of 3rd-party modules?

**Pull request closed without merging**
