### PR TITLE
[FIX] base_geolocalize: Handle IndexError

### PR DESCRIPTION
**Pull request by sswapnesh**
Description of the issue/feature this PR addresses: Fixes https://github.com/odoo/odoo/issues/35940

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hmm I am not sure. Instead, have you investigated why there was no result? Isn't it an error not catched?

**Comment by sswapnesh** [comment]
I am also not sure but this should prevent the error ( Or one has to dig more to investigate)

**Comment by mart-e** [comment]
This error seems odd (the `KeyError` too by the way). I tried to reproduce but did not get the same problem. I prefer not to hide the error, maybe there is a good reason for it...

**Comment by sswapnesh** [comment]
Maybe @bb39700 can add more detail on the same with some Proper example

**Comment by bb39700** [comment]
hello,
in fact, that comes from the integration of the swiss cities from swiss post.
At the end, i add a geolocalize request to be able to have it on map.
When i create the issue, that happened. It seems that now it works.
I don't know if it was an issue with the city (fixed now 1304 Allens, CH) or an issue with google.
the "{'results': [], 'status': 'ZERO_RESULTS'}" is in fact the print of the result var.

**Comment by sswapnesh** [comment]
@mart-e  Then we can close the PR and related Issue

**Comment by mart-e** [comment]
Not really, see https://developers.google.com/maps/documentation/geocoding/intro#StatusCodes

> Error Messages
> When the geocoder returns a status code other than OK, there may be an additional error_message field within the Geocoding response object. This field contains more detailed information about the reasons behind the given status code.
> **Note: This field is not guaranteed to be always present**, and its content is subject to change.

So it is possible to have different than ok but no error message (like with `ZERO_RESULTS`).
Wondering which is best to raise an error or to silently dismiss it.

**Comment by bb39700** [comment]
Perhaps a parameter in the function forvsilent mode or not...

Le ven. 20 sept. 2019 à 08:49, Martin Trigaux <notifications@github.com> a
écrit :

**Comment by sswapnesh** [comment]
> silently dismiss it.

IMO this will be good for now.

**Comment by mart-e** [comment]
> Perhaps a parameter in the function forvsilent mode or not...

Adding a parameter is rarely a good idea, it is best to chose one behaviour.

For the consistency, I kept the same behaviour as for the other errors. Even if I don't like hiding errors, in case of no result, it makes sense.

@robodoo r+

**Pull request closed without merging**
