### PR TITLE
[FIX] event, website_event: bay02.outlook.live is not up anymore

### PR DESCRIPTION
**Pull request by jhk-odoo**
Steps to reproduce:
- install events
- create an event in the future and save
- add an attendee > confirm > send by email
- send the 'event: registration' template to the attendee
- go to the chatter and click the '+ Outlook' button in the sent email

Previous behavior:
the link is no longer valid

Current behavior:
cherry-picked a03faab03fdf8a164c2f1298cc138b3fa83b0bea to be able
to export ics files (behavior from 13.0)

opw-2257062

### CODE REVIEW

**Comment by jhk-odoo** [comment]
@nle-odoo

**Comment by jhk-odoo** [comment]
@nle-odoo

**Comment by mart-e** [comment]
Well, as the link just doesn't work, I guess we can fix it. Don't forget to update the .pot file though

**Comment by nle-odoo** [comment]
fw-bot up to saas-12.3

**Comment by jhk-odoo** [comment]
robodoo r+

**Comment by jhk-odoo** [comment]
robodoo r+

**Pull request closed without merging**
