### PR TITLE
[FIX] l10n_in_edi: set false in production_env when neutralize DB

### PR DESCRIPTION
**Pull request by jva-odoo**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jva-odoo** [comment]
@odoo/rd-accounting this is a simple fix plz look at this

CC: @mao-odoo

**Comment by qdp-odoo** [comment]
@robodoo r+

**Review by william-andre — COMMENTED** [review]
What I understood:
* this will the use `DEFAULT_IAP_TEST_ENDPOINT = "https://l10n-in-edi-demo.api.odoo.com"` instead of `DEFAULT_IAP_ENDPOINT = "https://l10n-in-edi.api.odoo.com"`
* this will not provide an url for buying IAP credits? What will the `RedirectWarning` point to then? To a default route? Doesn't this feel wrong? And what is the difference with the default behavior?
https://github.com/odoo/odoo/blob/4fc7b9e32962d942fcc4d6e9a04b48d4016701a2/addons/iap/models/iap_account.py#L63-L66
https://github.com/odoo/odoo/blob/aa43799ed9e03d473f48c34ee470330e027ae462/addons/l10n_in_edi/models/account_edi_format.py#L81

I'm not 100% sure about this, but doesn't neutering the database mean that you don't want to send any requests, not even to a test server?

**Comment by qdp-odoo** [comment]
@robodoo r-

**Comment by mao-odoo** [comment]
> I'm not 100% sure about this, but doesn't neutering the database mean that you don't want to send any requests, not even to a test server?


If we base our reflection on what has existed for years in the neutralisation scripts for the SaaS and PaaS, the goal is not to contact no server at all but to not call production servers.

The cases where effort was made to not contact anything was :
1. when no sandbox/testing environment exist
2. when the sandbox/testing environment is so broken that it could result in production like behaviour. 

In those cases, we can also simply "dummify" the credentials to ensure that the end customer does not get billed or does not send testing data to their governments

**Comment by jva-odoo** [comment]
@william-andre in the test server we do not use IAP credits.
check server code here https://github.com/odoo/iap-apps/blob/master/iap_services/l10n_in_edi_proxy/models/einvoice_service.py#L94

so IAP credit error was never raised for the test env.

**Comment by william-andre** [comment]
@mao-odoo Is it something that has been well thought?
We need more documentation on what to do in here then
https://github.com/odoo/odoo/blob/3155c3e425581b71491844e7f9a3dd76a9f245a4/odoo/models.py#L6672-L6676

Because this hints that no calls to external servers are made.
This will also spam the servers when testing things (for local tests by the support for instance), that may lead to duplicate errors; not because the external sandbox is broken but because it doesn't allow for duplicate IDs (for instance an invoice number that will always be the same when testing)

@jva-odoo Ok but then why would you redirect to the page for buying credits on the test IAP server? What does that do?

**Comment by jva-odoo** [comment]
@william-andre for worst-case if this happens then we need to handle this using iap-sandbox endpoint.
and base_url is sent from the server and we know that if the server test then the IAP test server is iap-sandbox.odoo.com

**Comment by mao-odoo** [comment]
> @mao-odoo Is it something that has been well thought? We need more documentation on what to do in here then
> 
> https://github.com/odoo/odoo/blob/3155c3e425581b71491844e7f9a3dd76a9f245a4/odoo/models.py#L6672-L6676
> 
> Because this hints that no calls to external servers are made. This will also spam the servers when testing things (for local tests by the support for instance), that may lead to duplicate errors; not because the external sandbox is broken but because it doesn't allow for duplicate IDs (for instance an invoice number that will always be the same when testing)



Let's ask the authoritative source on the matter then : the person that wrote the docstring

@d-fence   is the goal of goal of the `_neutralize` to prevent any and all calls to external services (including testing environment) or is it meant to not impact production environment (and thus reaching testing environments is fine, and so is "dummy" credentials when a testing environment is not availlable)

**Comment by jva-odoo** [comment]
bug-fix-fixing-bugs-in-your-code

**Comment by william-andre** [comment]
@jva-odoo "Funny", because I am literally fixing pipes at home these days, and it does be exactly like that :upside_down_face:

**Comment by jva-odoo** [comment]
@william-andre today you fix it both 😉  😃

**Comment by jco-odoo** [comment]
@qdp-odoo @d-fence @william-andre @mao-odoo The goal of neutralize is what the duplicate scripts did before for support: make sure that when the db is copied, it does not risk sending an invoice to the production environment and to be able to check where the problem could have been, which is easier to solve if you also have an external test service.  That docstring just needs changing.

**Comment by jco-odoo** [comment]
@robodoo r+

**Comment by william-andre** [comment]
@jco-odoo I'm not sure why you r+ without anything changed an no explanation why nothing is to be changed when it had been r+ed then r-ed.

**Comment by jco-odoo** [comment]
@william-andre I know one thing for sure: false is better than true (why I don't like it pending).  Otherwise, it is good to discuss, but it is also an extension of what we have been doing for years.  You are right that the user and password can change between the two as well. @jva-odoo

**Comment by jva-odoo** [comment]
@jco-odoo okay, I will do it and create new PR

**Pull request closed without merging**
