### PR TITLE
Added the possibility to set a field's default from the context.

### PR DESCRIPTION
**Pull request by NicolasWebDev**
I have just discovered the possibility of setting an object field using the context.

I think that it should be in the documentation, because in some cases it can really be a life-saver.

I did not really know where to add, but I guess its best there, because the context could come from the view, or an action, etc.
So I decided to put it in the model directly.

For reference [here](https://www.odoo.com/forum/help-1/question/how-to-do-pre-data-population-on-a-one2many-field-75939) is the Odoo forums post thanks to which I have discovered this.

### CODE REVIEW

**Comment by Sathors** [comment]
Will I have to sign the CLA everytime I will want to make a pull request?

**Comment by xmo-odoo** [comment]
> Will I have to sign the CLA everytime I will want to make a pull request?

The problem is you're making pull requests from the github UI and it uses a different email address than the one you put in your individual CLA, so there's a mismatch and the CLA checker doesn't validate the CLA.

/cc @odony we might want to check for `GithubUser@users.noreply.github.com` as well as the email address the CLA provides in case the contributor is using the Github web interface and set their primary email address to private.

**Comment by odony** [comment]
> /cc @odony <https://github.com/odony> we might want to check for
> |GithubUser@users.noreply.github.com| as well as the email address the CLA
> provides in case the contributor is using the Github web interface and set
> their primary email address to private.

Sure, though in the short term users can simply add their github email to their 
CLA signature, and the check will pass (or we can do it for them).

**Comment by xmo-odoo** [comment]
@Sathors looking into where that was added, I don't think it makes much sense there: fields definition is but one place where default values can be defined, and close to the last one. The complete explanation should probably be in the docstring for `default_get` (which is already published, it just documents the actual places where default values come from), with a short version explaining how default values are filled in the `create` section of the guide.

**Comment by Sathors** [comment]
The thing is that not so many people know about the default_get() I think, so they won't never think to look there.
Additionally for me the default_get() is principally a way to overwrite the default values directly, so I won't think of looking there neither for alternative ways to define defaults.

Maybe we should instead define a whole section about defaults to make it easy to find?
With all the different ways to fill the default values?

What do you think?

**Comment by xmo-odoo** [comment]
> The thing is that not so many people know about the default_get() I think, so they won't never think to look there.

Sure which is why I suggested also putting a short explanation in the [create section of the guide](https://www.odoo.com/documentation/8.0/reference/orm.html#common-orm-methods). Explaining what happens for fields which are not explicitly provided seems to fit there.

> Maybe we should instead define a whole section about defaults to make it easy to find?

The default_get docstring would be the canonical section for that, and with luck we'd actually remember to update it if/when default_get changes.

**Pull request closed without merging**
