### PR TITLE
[CLA] ADD: Updated team members

### PR DESCRIPTION
**Pull request by wardm95**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wardm95** [comment]
https://github.com/odoo/odoo/pull/22841

for CLG signature check

**Comment by mart-e** [comment]
Hello,

You actually need to sign the signature with your `@vanroey.be` email address, not with your personal address.

**Comment by mart-e** [comment]
@wardm95 I believe is @Yenthe666 is no longer working with VanRoey so could you please make the changes so we can close this one. 
If you are unsure how to set a different email, check [this page](https://help.github.com/articles/setting-your-email-in-git/) on how to do so.

Thanks

**Comment by Yenthe666** [comment]
@mart-e for the no longer working with Van Roey: that is correct, he has added `(up to 2018-01-26)` for this. That should be enough, no?

**Comment by mart-e** [comment]
@Yenthe666 CLA signature modifications must be by the authorized people.
@wardm95 if you are unsure how to do so technically, you can also contact us on https://www.odoo.com/help and sent us a signed document with the changes.

**Pull request closed without merging**
