### PR TITLE
[I18N] *: export terms

### PR DESCRIPTION
**Pull request by mart-e**
- correct `.tx/config` file
- do not export `attribute` content
- export 16.0 source terms

### CODE REVIEW

**Comment by mart-e** [comment]
@robodoo r+ rebase-ff

**Comment by VincentSchippefilt** [comment]
shouldn't we wait for https://github.com/odoo/odoo/pull/100809 or should we re-export after merge ?

**Comment by mart-e** [comment]
@VincentSchippefilt I can wait if it's merged today :) (so the translation cron can run this weekend)
@robodoo r-

**Comment by mart-e** [comment]
robodoo r+
(will export spreadsheet again)

**Pull request closed without merging**
