### PR TITLE
[FIX] point_of_sale: skip receipt screen blinking

### PR DESCRIPTION
**Pull request by davidmonnom**
Currently when the pos.config is set to "Skip Preview", when printing a receipt, the receipt or bill screen shows very quickly and disappears. This is not good UX.

Now, the receipt is printed from the payment screen itself. We don't need to show the receipt screen at all.

taskId: 3441238

### CODE REVIEW

**Review by caburj — COMMENTED** [review]
Can you try "renderToElement" (or "renderToString")? Maybe we don't need to render the OrderReceipt in the PaymentScreen template.

**Comment by davidmonnom** [comment]
> renderToElement

Isnt

> Can you try "renderToElement" (or "renderToString")? Maybe we don't need to render the OrderReceipt in the PaymentScreen template.

Isn't working because there is another components to render inside the receipt. I can't just pass it in the context.

**Comment by rhe-odoo** [comment]
@robodoo r+

**Comment by adgu-odoo** [comment]
@robodoo r+

**Comment by adgu-odoo** [comment]
@robodoo r-

**Comment by caburj** [comment]
robodoo r+

**Pull request closed without merging**
