### PR TITLE
[REV] project: re-allow recurring sub tasks

### PR DESCRIPTION
**Pull request by tlibioulle**
With the modification introducted in the PR #62577, create recurring
subtask was no more allowed.

This commits reverts this limitation and adds tests to verify this
behaviour.

task-2522076

See #71211

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tlibioulle** [comment]
@IT-Ideas May I ask you to have a look ?

I updated the PR references in the commits since it referred the PR on saas-14.3 ( #71211 ).

Thanks for your help ! :)

**Review by IT-Ideas — APPROVED** [review]
LGTM 🙂 
Thanks !

**Comment by IT-Ideas** [comment]
@robodoo rebase-ff r+

**Comment by xavierbol** [comment]
@robodoo r-

**Comment by IT-Ideas** [comment]
@robodoo r-

**Comment by tlibioulle** [comment]
See #77126

**Pull request closed without merging**
