### PR TITLE
 [IMP] Delete unused code

### PR DESCRIPTION
**Pull request by Kontrolix**
Simply delete unused code

### CODE REVIEW

**Comment by mart-e** [comment]
@jem-odoo you were the author of the code at 6ea10114160c9f2f61347f3a54e3ff07a6d79b40
Didn't you intended to use the `name` in the `return` ?

**Comment by mart-e** [comment]
Hello,

Thank you for you patch but it seems you have not [signed the CLA](https://www.odoo.com/sign-cla).
Could you add it so we can integrate your patch?
Regards

**Comment by Kontrolix** [comment]
Hello,

I just done it, here: https://github.com/odoo/odoo/pull/40851

**Comment by Feyensv** [comment]
Please rebase your branch so that the mergebot can recognize your CLA signature ;).

**Comment by Kontrolix** [comment]
I tried but there is an incredible amount of conflict. I don't understand...

**Comment by mart-e** [comment]
@Kontrolix don't worry, I got it

@robodoo r+

@Feyensv see https://github.com/odoo/odoo/wiki/Mergebot#merge-a-communitys-contribution to get the branch and do it yourself

**Pull request closed without merging**
