### PR TITLE
[IMP][16.0] (sale_)loyalty: use free product display name

### PR DESCRIPTION
**Pull request by Hung-Elsh**
Description of the issue/feature this PR addresses:

Current behavior before PR:

- When create a free product reward, reward and sale order line description use product's name so if many reward are variants of others, the description will be the same. It make portal user confusing when they chose reward in portal

Image before commit:

image

image

Desired behavior after PR is merged:

- the description will include display of product so that will contain name of variants's attributes

Image after commit:

image

image

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by Demesmaeker — APPROVED** [review]

**Review by Feyensv — COMMENTED** [review]
You should specify add the key `display_default_code` set to `False` in the context to avoid having the `DESK0005` code visible on the cart ;)

**Comment by Hung-Elsh** [comment]
> You should add the key `display_default_code` set to `False` in the context to avoid having the `DESK0005` code visible on the cart ;)

Thanks sir, i will adjust it

**Review by Feyensv — APPROVED** [review]
@robodoo r+

**Comment by Feyensv** [comment]
Thanks for the quick update :+1:

**Pull request closed without merging**
