### PR TITLE
[I18N] website: remove ads (?) from the Vietnamese translation

### PR DESCRIPTION
**Pull request by oomsveta**

### CODE REVIEW

**Comment by oomsveta** [comment]
robodoo r+

**Comment by duong77476-viindoo** [comment]
Hello @oomsveta Some version <= 17.0 also have this at some places, can i make PR remove that or we can only remove `msgstr` in master only

**Comment by oomsveta** [comment]
Hello @duong77476-viindoo, thank you for your interest! The translation fixes are usually handled through Transifex. Every Sunday, the content on Transifex is synchronized with the content on Github. The only exceptions are master and languages that we don't have on Transifex for the given version.

If you see more "ads" on master that I missed, feel free to make a PR to remove them and mention me in the conversation. For older versions, however, there is no need to go through Github

**Comment by duong77476-viindoo** [comment]
> Hello @duong77476-viindoo, thank you for your interest! The translation fixes are usually handled through Transifex. Every Sunday, the content on Transifex is synchronized with the content on Github. The only exceptions are master and languages that we don't have on Transifex for the given version.
> 
> If you see more "ads" on master that I missed, feel free to make a PR to remove them and mention me in the conversation. For older versions, however, there is no need to go through Github

Got it, thanks

**Pull request closed without merging**
