### PR TITLE
[IMP] <document> Add menu to access documents in knowledge

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Comment by anajuaristi** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Seems reasonable to add this menu to see all the documents in one place.

:+1:

**Comment by esthermm** [comment]
:+1:

**Comment by tivisse** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards

**Pull request closed without merging**
