### PR TITLE
[FIX] l10n_pe: invoice label

### PR DESCRIPTION
**Pull request by malb-odoo**
The taxes on Peru localization no not have the percentage added by default on the invoice_label field. Currently, the tax name is simply IGV (for the 18% tax) which makes the invoice PDF feel incomplete.
This Pr adds the percentage on the invoice label.

task: 4114767

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fvz-odoo** [comment]
Hello @malb-odoo 

Checked this functionally and LGTM. Just in case.

Cheers!

Fernando

**Review by dbkosky — APPROVED** [review]

**Review by epictete — COMMENTED** [review]
LGTM, but shouldn't we update the translations?

**Comment by malb-odoo** [comment]
@epictete The translation for the invoice_label are not there but i think it will be pretty much the same as the one we have now, so i don't think it's necessary ?

**Review by epictete — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
