### PR TITLE
[IMP] l10n_*: remove icon.png and use country_fla from base

### PR DESCRIPTION
**Pull request by william-andre**
* We are gaining ~1.2MB by doing this
* The flags are unified with the same looks.
* Some flags were missing

Before:
Screenshot_2020-08-24 Apps - Odoo(1)

After:
Screenshot_2020-08-24 Apps - Odoo(2)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by william-andre** [comment]
By using
```css
.oe_module_desc {
    padding-left: 10px;
    width: 77%;
}
.oe_module_icon {
    max-width: 23%;
    max-height: 70px;
}
.o_kanban_record {
    align-items: center;
    display: flex;
}
```
Screenshot_2020-08-24 Apps - Odoo(3)

**Comment by william-andre** [comment]
Should we add the OHADA logo as well?

**Comment by william-andre** [comment]
@jco-odoo Can you have a look at this?

**Comment by jco-odoo** [comment]
@william-andre It is a bit on the low-priority side, but not bad to do.  Having another look at the changed flags, I wonder if the flags can have a smaller width as well.  And if you change the css, it will be applied on other modules as well?

**Comment by william-andre** [comment]
I changed the css so that it is the closest to how it was before; basically I just changed the paradigm by using `display: flex`, which is what we should do in **all** kanban views IMO.
So yes, it affects all the apps/modules, but it _should_ not be visible (if the icons were already squared)

> I wonder if the flags can have a smaller width as well
what do you mean?

**Comment by jco-odoo** [comment]
They are a bit wide to be a flag.

**Comment by william-andre** [comment]
> They are a bit wide to be a flag.

**Comment by william-andre** [comment]
@jco-odoo I have looked at all the views using the css classes we use and nothing is broken with this version.

**Comment by qdp-odoo** [comment]
@robodoo r+ rebase-ff

**Pull request closed without merging**
