### PR TITLE
[FIX] website_slides: fix unability to delete a course

### PR DESCRIPTION
**Pull request by jvnm-dev**
### Issue

	- Install eLearning
	- Delete a course with question & answers

	Error (foreign key issue)

### Cause

	The course depending data is not deleted

### Solution

	Add `ondelete='cascade'`

**OPW-2210096**

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jvm-odoo** [comment]
@nim-odoo

**Comment by tde-banana-odoo** [comment]
I would say we should prevent unlink if there are members and/or slides and/or some activity. Archiving seems a better idea.

Anyway seems like a functional change that should target master and a proper task.

**Comment by sbuhl** [comment]
@jvm-odoo 
I'd rather not do that. It's a bit too extreme. 
We'll do something close from that in master.
There is nothing blocking for the user in my opinion.

**Comment by jvm-odoo** [comment]
Fixed in master according to sbu

**Pull request closed without merging**
