### PR TITLE
[FIX] base: Allow empty thousands separator in reports

### PR DESCRIPTION
**Pull request by hubvd**
Steps to follow

- Set the thousands_sep of the current lang to an empty string or null
- Create a report
-> The thousand separator from the system locale will be used instead to format numbers

opw-2507441

### CODE REVIEW

**Comment by hubvd** [comment]
@Elkasitu Can you review this PR ?

**Comment by xmo-odoo** [comment]
That's certainly a no for me:

* either the fallback is correct and the ticket should be rejected
* or the fallback is *not* correct and it should be fixed or removed everywhere

Either way I don't see the point of adding a flag, it just introduces incoherence in formatting.

It looks like the web client doesn't rely on any sort of fallback (at least for the js / backend), and the fallback code is outright ancient and as is oft the case for such old code not really documented, but it looks like a remnant of the days before res.lang was used for localisation information (and thus may have been left in for compatibility with incorrectly or incompletely setup lang records) as it dates from [the same commit which introduced the non-translation l10n fields](f500ecff15296379a6970e6b1eab6c67c3c21dd3). As such I'd suggest that the fallback can just be dropped, possibly replaced by `or ''` for the odd `NULL` field.

**Review by rco-odoo — APPROVED** [review]

**Review by xmo-odoo — APPROVED** [review]
Works for me, rco wondered if it might be worth merging in 11 or 12 even though the complaint was on (I assume) 13, I'll let @nle-odoo judge I guess?

**Review by nle-odoo — APPROVED** [review]
looks good to me

> rco wondered if it might be worth merging in 11 or 12 even though the complaint was on (I assume) 13

the complaint was for 14.0. 12.0 is no longer supported and I don't think this fix is needed enough to make an exception.

robodoo r+

**Pull request closed without merging**
