### PR TITLE
[FIX] qweb: use cdn for asset files

### PR DESCRIPTION
**Pull request by Gorash**
Refactoring of qweb to call _post_processing_att for each nodes. This
change remove the crappy ovewrite in website module. The website overwrite
only the _post_processing_att to add the cdn parameters.

The static node (without t- attributes) can stay static (remove overwrite
of _is_static_node), the cdn is applied at the compile time for this
nodes instead of at the running time like the dynamic node.

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@Gorash if I'm understanding this correctly it will mean that all assets, including all those big JavaScript files, could be available from the CDN after this PR? Will this still end up in V11 too?

**Comment by Gorash** [comment]
@Yenthe666 It worked but not very well, sometimes there was not the cdn (connected users did not use the cdn, case met or only half of the assets used the cdn, image without cdn on some pages ...). With this fix and refactoring, the code is cleaner, and the overwrite in website is much more understandable (I try to avoid that people have to do the ast).

**Comment by Yenthe666** [comment]
@Gorash I was actually facing these issues. Both that some images where sometimes not used with the CDN and that some content was not loaded through CDN.
I'll ask the boss if I can test & review this PR, I like it.

**Comment by Gorash** [comment]
@JKE-be any news ?

**Comment by Gorash** [comment]
Si mais je n'ai pas eu d'erreur dans les pages testée ici tu m'a indiqué le blog

**Comment by Gorash** [comment]
Donc après test, les snippet sont avec des attributs de style baground-url... en effet, le cdn ne gérait pas les styles. Je ne savais pas qu'on avait fait des snippets de la sorte.
Je fais un commit pour que cela marche, avec le refactoring c'est facile.

**Comment by JKE-be** [comment]
Tu parles des covers toi. Moi je te parlais des img Classic dans un blog que tu aurais ajouté via l’éditeur.

Bat

Jeremy Kersten

**Comment by Gorash** [comment]
Dans blog ce sont des fields html et non pas des ir.ui.view.
Je modifie et fix, maintenant les widget qweb html seront compilé par le qweb (donc toutes les features qweb y seront disponibles)

**Comment by nim-odoo** [comment]
small note: this should target v11, not saas-16

**Comment by Yenthe666** [comment]
Or V10? 🙏

**Comment by Gorash** [comment]
rebase on 11.0 => https://github.com/odoo/odoo/pull/23745

**Pull request closed without merging**
