### PR TITLE
[IMP] event: Send mails and SMS to multiples attendees at once

### PR DESCRIPTION
**Pull request by ivantodorovich**
**Description of the issue/feature this PR addresses:**
Allow to send mails and SMS to multiple attendees at once

image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ivantodorovich** [comment]
ping @tde-banana-odoo , as I know you worked on this :)

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks for the feedback ! Actually you can do the same using a mail.template (add to context menu or something like that, don't know the exact naming in master). It is linked to a template but you can change it in "template" selection box. Not sure we should add it directly into the UI by default. Is there anything not covered by using templates ?

Cheers !

**Comment by ivantodorovich** [comment]
Hello ! 

Thanks for the suggestion :)

Actually this is to give users the ability to send unplanned notifications to the attendees, either by mail or sms. These are often communications related to cancelations, delays, urgent notices, etc..

`mail.templates`, to my understanding, are better for planned or regular comunications.

Also you can find similar actions in order apps:
- https://github.com/odoo/odoo/blob/e90d32dc852700551c28d7e9816990f4d990f894/addons/crm/views/crm_lead_views.xml#L731-L742
- https://github.com/odoo/odoo/blob/e90d32dc852700551c28d7e9816990f4d990f894/addons/crm_sms/views/crm_lead_views.xml#L3-L28

- https://github.com/odoo/odoo/blob/e90d32dc852700551c28d7e9816990f4d990f894/addons/stock/views/stock_picking_views.xml#L560-L571

**Comment by tde-banana-odoo** [comment]
Hello,

I discussed with our Events product owner. Currently we already have several communication means in event

- automated emails / SMS sending with event.mail (configured on event itself);
- bridge with mass mailing ('contact attendees' on event, then maybe tweak the domain);
- use mail.template "add to menu" action, using maybe a blank mail.template or sms.template if you do not want a predefined content;

We think that adding yet another action in More menu make the interface more complex for few use cases that are not covered buy previous solutions.


CRM hass actions because it is a communicationn-oriented model. CHances are high you will have to send a lot of emails to your customerss in CRTM. Registrations are a bit more standard and possibilities are sufficient in ourr opinion.

I hope this clarifiers our position :)

Cheers !

**Comment by ivantodorovich** [comment]
Understood :) thanks for taking the time to consider it

**Pull request closed without merging**
