### PR TITLE
[IMP] report: pass pdfreport_path to postprocess_pdf_report method

### PR DESCRIPTION
**Pull request by lmignon**
This simple change improve the modularity by allowing for exemple the enrichment of the content generated into the postprocess hook.
If the method recieve only the content of the generated report, changes done into the report are not part of the final result.
This change restore the behaviour from SHA: b3b371558674afe9df7f4043d69e7f5a0ec4d4ad and lost into the refactoring SHA: e80238042c9d93d492ea8b06b0041aced0d81dcd

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lmignon** [comment]
ping @smetl Can you restore a functionality lost in your refactoring please?

Thanks in advance!

**Comment by smetl** [comment]
@lmignon It will be restored with https://github.com/odoo/odoo/compare/master...odoo-dev:master-fix-dep-report-las

**Comment by lmignon** [comment]
@smetl Great! Thank you very much!

**Comment by smetl** [comment]
landed at master at https://github.com/odoo/odoo/commit/259c5d9145aee8a9d24e36792385f86cbaa0bb8c

**Pull request closed without merging**
