### PR TITLE
[FIX] web_editor: update image gallery miniatures

### PR DESCRIPTION
**Pull request by younn-o**
When changing an image in the image gallery snippet, its miniature was not updated.

task-2438556
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by sdegueldre — APPROVED** [review]
@younn-o code is good, might be nice to mention in the commit message how this fixes the problem since it's not obvious from the code. Usually I put the diagnostics I ran inside the commit message rather than the description of the task and behaviour before/after. I think the before/after should be easy to infer from the commit title.

Something like:

Previously, when changing an image in the media dialog, the image gallery widget would not update the corresponding image thumbnail in the carousel controls. This was caused by the event that the carousel listened for (save) no longer being triggered on the new image by the image media widget since 12.3.

This commit fixes that by triggering this save event once more. Unfortunately, it can no longer be trigger from the image media widget because in 12.3 only, the image media widget operates on an out-of-DOM clone of the media, as such, the event is now triggered from the media-dialog instead

task-...

Also when the commit isn't exactly the same between versions, make sure the commit message agrees with the code (mentions an 'image_changed' event but that's only in 14+)

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
@younn-o The commit message is to be reviewed:

- The website app is unmodified, it should not be mentioned
- You mention the 'image_changed' event but I don't see it anywhere in your work, which is confusing. You should not mention implementation details in general anyway.
- Really no need for such long commit message for such small commits, just "When changing an image in the image gallery snippet, its miniature was not updated." would be enough here and would avoid mistakes and quicker reviews :wink:

**Comment by qsm-odoo** [comment]
Oh, @sdegueldre did a review at the same time saying more or less the same stuff :) @sdegueldre When you review task, move it right away to RD validation, otherwise this happens :wink:

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
Commit message convention:
- The title should complete the sentence "When applied, this commit will ...". So here "When applied, this commit will image gallery miniatures are not updated" is not perfect :wink: 
- Depending on who you ask, max 72 or 80 characters per line. I use 72, I am fine with both. For the title, 72 is the hard limit ;)

**Review by qsm-odoo — COMMENTED** [review]
@fw-bot ignore

@younn-o Note: we not supposed to do manual forward-port (you made a PR with the same fix for 13.0 here: https://github.com/odoo/odoo/pull/65461). We are supposed to merge in the oldest version then let it forward-port to upper version. If the fix is different, it's the same: we solve conflict on forward-port to be able to keep references to oldest version fixes... but let's not waste time for this one, we'll merge both PR and we'll not forward-port this one :wink:

**Comment by sdegueldre** [comment]
> If the fix is different, it's the same: we solve conflict on forward-port to be able to keep references to oldest version fixes

@qsm-odoo that's my bad then.

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Comment by qsm-odoo** [comment]
@younn-o Can you rebase and re-push-force this branch to make robodoo happy? :wink:

**Review by qsm-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
