### PR TITLE
[FIX] event: correct computation of seats_* fields

### PR DESCRIPTION
**Pull request by yelizariev**
It's a backport of following commits to v13:

a6acb077e4c2f53d48b80397246ed5961bfa354c
456f8a7e70fe709eb75d6f648dcf163266a9dc60

STEPS:
* Open an event that already have some attendees
* Click edit, change **Category** field, click save

BEFORE: seats_expected is increased
AFTER:  seats_expected is computed correctly

---

opw-2805944

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by yelizariev** [comment]
@tde-banana-odoo

**Comment by yelizariev** [comment]
@fw-bot ignore

**Review by tde-banana-odoo — COMMENTED** [review]
Did not test, but as this is a backport, LGTM :)

**Comment by simongoffin** [comment]
robodoo delegate+

**Comment by yelizariev** [comment]
robodoo r+

I've just made the function test again (before/after)

**Pull request closed without merging**
