### PR TITLE
[FIX] account: Validation Error Traceback

### PR DESCRIPTION
**Pull request by wtaferner**
**Description of the issue/feature this PR addresses:**
Traceback 👷🏼 ⛑️ 

**Current behavior before PR:**
```python
File "addons/account/models/account_move.py", line 1536, in _check_duplicate_supplier_reference
    duplicated_moves.mapped(lambda m: "%(partner)s - %(ref)s - %(date)s" % {'ref': m.ref, 'partner': m.partner_id.display_name, 'date': format_date(self.env, m.date)})
TypeError: not all arguments converted during string formatting
```
**Desired behavior after PR is merged:**
No traceback 😃 

Info: @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by wtaferner** [comment]
@oco-odoo @nim-odoo @smetl 
May I ask you to merge this no brainer for me? Some accountants might be happy about this fix 😉

**Comment by wtaferner** [comment]
@mart-e 
How could we tackle such a pitfall in a stable version?
Basically I guess I would need to change the pot and all translations, right? 
Is there a way to push those *.po changes to Transifex on your side or is it still a f***** manual process?

**Comment by william-andre** [comment]
I don't get the issue. Is the translation wrong, removing or adding placeholders?

**Comment by wtaferner** [comment]
> I don't get the issue. Is the translation wrong, removing or adding placeholders?

Sorry for the additional noise about the translation. It is as simple as that: 
```python
TypeError: not all arguments converted during string formatting
```

**Comment by william-andre** [comment]
I must be really blind because I see one string with one positional placeholder interpolated by one parameter, and one string with 3 named placeholders interpolated by the correct dict too.

**Comment by william-andre** [comment]
I just tried it on runbot 13.0 (in english...), works like a charm.

**Comment by wtaferner** [comment]
> I just tried it on runbot 13.0 (in english...), works like a charm.
Haha, great, then it is just a shitty translation 🤦🏼‍♂️ besides the root of the issue that anyone should try to not encode placeholders into any translation as it is keen to error...maybe we should do better error handling and communication on such pitfalls. Thx, for taking the time, I guess I close it for a stable version as it can be solved better by fixing the translation.

@mart-e 
Maybe you can initiate some effort to get this finally right or less breakable?

**Comment by mart-e** [comment]
Hi,

The error was corrected in 14.0 but not in 13.0.
It's now fixed https://www.transifex.com/odoo/odoo-13/translate/#de/account/182678724?q=text%3A'Duplicated+vendor+reference+detected'

**Comment by william-andre** [comment]
> Hi,
> 
> The error was corrected in 14.0 but not in 13.0.
> It's now fixed https://www.transifex.com/odoo/odoo-13/translate/#de/account/182678724?q=text%3A'Duplicated+vendor+reference+detected'

Don't we have; wouldn't it be a good idea to have a nightly test checking that the placeholders are matching in all translations?

**Pull request closed without merging**
