### PR TITLE
[FIX] sale_management: (revert) handle temp recs

### PR DESCRIPTION
**Pull request by ethanrobv**
This PR reverts the commit
https://github.com/odoo/odoo/commit/b79377c

opw-3754297

### CODE REVIEW

**Comment by ethanrobv** [comment]
@Feyensv Master-port for https://github.com/odoo/odoo/pull/161868

**Comment by Feyensv** [comment]
Why did you disable the fw-port if it was also necessary in master ?
What about 17.1 and 17.2 ? :thinking:

**Comment by ethanrobv** [comment]
> Why did you disable the fw-port if it was also necessary in master ? What about 17.1 and 17.2 ? 🤔

It was never merged in those versions due to the community/enterprise branches getting out of sync due to some rebases during the forward: https://mergebot.odoo.com/odoo/enterprise/pull/58264

**Comment by Feyensv** [comment]
Mhm, ok then.
@robodoo delegate+

**Comment by ethanrobv** [comment]
@robodoo r+

**Pull request closed without merging**
