### PR TITLE
[IMP] core: update tests loader to correctly report syntax errors

### LINKED ISSUE #80198: False positives in test suite when a test module raises at import time
Impacted versions: 13.0, 14.0, 15.0

Steps to reproduce:

Create an addon containing a test module that raises an error at import time (such as a syntax error).
Run tests with `odoo -d db -i module --test-enable --stop-after-init`.

Current behavior:

The error is logged, but the exit code of the process is 0.

This is particularly annoying as it leads to false positives in CI systems.
The problem originates in `tests/loader.py`, function `_get_tests_modules` which ignores all exceptions.

Expected behavior:

A non-zero exit code.

Support ticket number submitted via odoo.com/help (optional):

### PR DESCRIPTION
**Pull request by xmo-odoo**
Currently e.g. syntax errors during the import are logged as exceptions but they don't fail the loading / testing.

Update the loading using more modern loading APIs, in order to not catch them at all (let them bubble up normally), and instead just find *IF* a module has a tests submodule before trying to load in (LBYL).

Fixes #80198

### CODE REVIEW

**Comment by xmo-odoo** [comment]
Only real question is whether this should be backported as the issue was reported against every version.

**Comment by pedrobaeza** [comment]
Thank you very much for this! It would be interesting to have it on current stable versions for avoiding more similar problems, but not sure if this accepted in the stability policy:

https://xkcd.com/1172/

**Comment by xmo-odoo** [comment]
> Thank you very much for this! It would be interesting to have it on current stable versions for avoiding more similar problems, but not sure if this accepted in the stability policy:
> 
> [xkcd.com/1172](https://xkcd.com/1172/)

I'm not too sure there, on the one hand it's just tests, and it should report currently-broken tests at most. On the other hand it might break CI / build which currently passes, which would impact workflow.

As-is the change also hard-crashes the entire system if one of the test modules is broken, it doesn't report it as a test suite failure or anything, which might be a tad brutal as I'm not sure we do that for syntax errors in regular module code.

**Comment by xmo-odoo** [comment]
After testing there seems to be no special handling of syntax errors in modules, so doing nothing special and failing normally in test modules seems fine. Especially as it should only affect tests (if the test module is mistakenly imported from the module itself, then it already fails).

**Comment by xmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
