### PR TITLE
do not depend on existance of static subdirectory

### PR DESCRIPTION
**Pull request by funbaker**
make it optional by moving isdir check below

### CODE REVIEW

**Comment by antonylesuisse** [comment]
Why ? It speed up loading. There very few modules with auth=none controllers and if you may also use --load= option to load them even if they dont have a static directory.

**Comment by funbaker** [comment]
Hello,

thing ist, modules without a static directory get installed but dont get loaded automatically on server restart.
so the models and views are in the DB, but the model class is not imported, which leads to "model not found" errors and such.

Since its not possible to pull an empty directory from git, theres no clean way to work around this :)

**Comment by antonylesuisse** [comment]
Nope modules are imported they are imported lazily only at registry loading. The static 'hack' is only used for non registry dependant module (those that have auth='none' controller).

**Comment by antonylesuisse** [comment]
If you get such an error then it's probably a bug and it's not related to static module preloading.

**Pull request closed without merging**
