### PR TITLE
[IMP] Avoid setup manual models if not last package loaded

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
**Description of the issue/feature this PR addresses:**

When you update a module, it is calculated a graph of packages of all dependent modules. The updating process (`load_module_graph` of `loading.py`) does a loop through all the packages. In each loop, the models of that package are setup in the registry. But also all the manual models are setup. So in each loop, the manual models are setup, cleaned up and setup again. This it's a bit odd performance-wise. Suppose you have a lot of manual models and a lot of packages, then this process it's horrible.

This PR solves this problem of performance by just adding the manual models at the last iteration of the loop.

**Current behavior before PR:**

If you have a lot of manual models and a lot of modules, the performance of updating `base` it's horrible.

**Desired behavior after PR is merged:**

The setup of manual models in the registry can be avoided in some cases to optimize the processes.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mreficent** [comment]
Maybe it's ok for v11?

**Comment by Elkasitu** [comment]
Before looking at the code itself, could you provide benchmarks on the difference pre and post patch?

**Comment by mreficent** [comment]
I am bad getting benchmarks, sorry :(

**Comment by mreficent** [comment]
ok, thanks for your answer

**Pull request closed without merging**
