### PR TITLE
[FIX] stock: Correct group for Warehouse Management menu

### PR DESCRIPTION
**Pull request by pedrobaeza**
A Warehouse Manager cannot change for example locations with current group.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@jco-odoo, can you please check?

**Comment by pedrobaeza** [comment]
cc @Tecnativa

**Comment by bealdav** [comment]
:+1:

**Comment by mart-e** [comment]
Hello,

I think that change makes sense but it seems that @tivisse added this group intentionnaly (at 23ac1b5422fb058a464cc366d1d9d08db8d01ddf and 114d8f1).
Yannick, no issue to replace "System Configuration" group by "Warehouse Manager"?

**Comment by tivisse** [comment]
@mart-e This group is removed in v10. I won't cry if you do this. 

Removed at commit https://github.com/odoo/odoo/commit/fdb3ad7082a572d71182b9460b274b94c6bd7560

**Comment by jco-odoo** [comment]
Thx, @mart-e, @ytivisse

**Comment by mart-e** [comment]
merged at ba5646f8b9129528d252c718fc3771de7c110804, thanks

**Pull request closed without merging**
