### PR TITLE
[FIX] point_of_sale : company is already filter

### PR DESCRIPTION
**Pull request by fmdl**
Description of the issue/feature this PR addresses:
From this PR https://github.com/odoo/odoo/pull/76393, this domain is not needed.

@pimodoo 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pimodoo** [comment]
@fmdl Is there an issue with this? I don't really see how it could cause trouble.

**Comment by fmdl** [comment]
In case where stock.production.lot is shared between company.

**Comment by pimodoo** [comment]
@fmdl Sorry, but it is not possible, the lot is always linked to a company: https://github.com/odoo/odoo/blob/14.0/addons/stock/models/stock_production_lot.py#L28

**Comment by fmdl** [comment]
In custom company.
Can be move in master ?

**Comment by pimodoo** [comment]
@fmdl company still required in master. I don't really see why it should be changed and how "sharing" lot could be useful.

**Comment by fmdl** [comment]
To track correctly lot between company and see all history. (I don't understand why lot are company dependent, for me and my customer it doesn't make sens, and it is useless during transfert between company).
For exemple, a company based in France with a production line in Portugal. The company in Portugal produce and send products in France, in France you should re-create lots, and if after you send that in an other company in GB for exemple, you loose the traceability.

**Comment by Whenrow** [comment]
@fmdl We made the lots and SNs company dependent precisely for the multi-company flows and the serial number uniqueness constrains. If company A sells serial number SN1 to company B and both company are on the same database, we want to have two separate serial numbers to be able to track them aside.

**Comment by fmdl** [comment]
In multi-company with large logistique system, the loose of traceability between company it is incomprehensible for my customer.

**Comment by fmdl** [comment]
An option to choose should be good.

**Pull request closed without merging**
