### PR TITLE
[IMP] account: improve invoicing tour

### PR DESCRIPTION
**Pull request by yosuanicolaus**
improve the flow of invoicing tour by:
- moving some bubble to a more clear position
- rewrite some text content
- delete some and add new tour step

task-id: 3468585

### CODE REVIEW

**Review by malb-odoo — APPROVED** [review]
Look fine for me, nice job ! We will have to ask security to give the permission for the markup

**Comment by yosuanicolaus** [comment]
Hello @odoo/rd-security team, can I get exception for this PR's security check? :)

**Review by xmo-odoo — COMMENTED** [review]
FWIW to make for faster review you should explain why the security-sensitive change is necessary *and* safe.

@robodoo override=ci/security

**Comment by qdp-odoo** [comment]
runbot is red

**Comment by yosuanicolaus** [comment]
@qdp-odoo it's green now (finally) :partying_face:

**Comment by qdp-odoo** [comment]
@robodoo r+

**Comment by qdp-odoo** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
