### PR TITLE
Master fix website multi rde

### PR DESCRIPTION
**Pull request by rdeodoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rdeodoo** [comment]
@JKE-be Should the commit about website session be in lower stable version?

**Comment by JKE-be** [comment]
@robodoo r+


// merged in v12 as discuss

**Comment by rdeodoo** [comment]
perfect :+1:

**Comment by JKE-be** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
