### PR TITLE
[FIX] web: fix rendering of all day events

### PR DESCRIPTION
**Pull request by jdoutreloux**
Description of the issue/feature this PR addresses:
All day events that only last one day don't have a background color in the calendar view.
This is because of a typo in the renderer. 

Desired behavior after PR is merged:
Once the typo is fixed one day events have a background too.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by sbidoul** [comment]
OPW 2968130

**Review by nboulif — CHANGES_REQUESTED** [review]
Hello @jdoutreloux Not sure about your fix, at least no typo... I just tried on runbot and it seems working :
image
Am I missing something?

**Comment by jdoutreloux** [comment]
Hi @nboulif 
the fix was indeed wrong, thanks for your catch. I've fixed it.
I think that we shouldn't check on event.record.allday here but on event.allDay to use the attribute set on the view and not a field on the record. This only works if the record has an allday field and in my opinion this defeat the purpose of the attribute on the view.

**Review by nboulif — COMMENTED** [review]
Indeed, your fix make more sense now :slightly_smiling_face: I see that in some case we use `eventData.allDay`, and in others `eventData.record.allday`, agreed that we should use the same attribute everywhere.
ps: may I ask you meanwhile to update the commit to fit Odoo guidelines? Thanks in advance!
https://www.odoo.com/documentation/15.0/contributing/development/coding_guidelines.html#commit-message-structure

@odoo/rd-framework-js Hello team! May I ask for an input on this one? Thanks in advance!

**Comment by brboi** [comment]
Hello @jdoutreloux 
Is it still an issue for you ?

If yes can you share the steps to reproduce the issue ?

Thanks!

**Comment by jdoutreloux** [comment]
Hi @brboi 
The steps to reproduce are : 
- Go on the calendar view of a model that doesn't have a field called "allday" 
- Set the "all_day" parameter of the calendar view to any boolean from the model
- Events background aren't rendering properly when that boolean is True.
This is because the renderer uses event.record.allday and not event.allDay and as such doesn't use the attribute set on the view. If the model doesn't have a field called allday this can't work.

**Comment by brboi** [comment]
Hello @jdoutreloux 

Thank you ;-)

I close this PR in favor of a new one targetting 14.0 branch.
13.0 is no more under support.

**Pull request closed without merging**
