### PR TITLE
[FIX] sale_stock{_margin}: enforce implicit dependency

### PR DESCRIPTION
**Pull request by Elkasitu**
Strap yourself in, we're in for a ride:

The module sale_stock_margin overrides
`SaleOrderLine._compute_purchase_price` and adds some extra dependencies,
the key dependency here is 'move_ids'.

The field `move_ids` is defined in sale_stock's override of
sale.order.line, however sale_stock is **not** a dependency of
sale_stock_margin, but since they implicitly share the same dependencies
and are both `auto_install=True` it is impossible to install
sale_stock_margin without having sale_stock be automatically installed.

However, since sale_stock_margin does not **explicitly** depend on
sale_stock, if one were to uninstall sale_stock without uninstalling
sale_stock_margin first, the registry would crash because
sale_stock_margin's override of `_compute_purchase_price` would depend
on a field that no longer exists (`move_ids`).

This commit fixes this in an odd way, because of the following reasons:

- We cannot change a dependency in a stable branch.
- An uninstall_hook cannot inject an uninstall dependency because the
  hook step is too late into the process (we'd need a
  pre_uninstall_hook)
- A post_install_hook could create a dependency between
  sale_stock_margin and sale_stock, however this would only apply to
  **new** installs of sale_stock_margin and the bug would persist for
  existing users

Thus the only solution left is to extend ir.module.module and override
the downstream_dependencies to inject sale_stock_margin as a sale_stock
dependant if sale_stock is one of the modules for which we're
calculating the downstream dependencies.

### CODE REVIEW

**Review by rco-odoo — APPROVED** [review]
LGTM, it's clever.

**Comment by pedrobaeza** [comment]
I'm having a problem due to the missing module dependency in `sale_stock_margin`:

https://github.com/OCA/OpenUpgrade/runs/5710011319?check_suite_focus=true#step:13:5281

and I think it's due to the loading order of the modules, being loaded `sale_stock_margin` before `sale_stock`.

Is it so bad to add the missing dependency in stable? As you have told, both are auto-installed, so the chances of having `sale_stock` if `sale_stock_margin` are very high, but if not, a `base` update would solve the problem.

Anyways, if that's not reasonable, I think the problem I have may be solved specifying a sequence in the modules. Would you accept this as a viable patch?

**Comment by pedrobaeza** [comment]
cc @rco-odoo @Elkasitu

**Comment by rco-odoo** [comment]
@pedrobaeza 
> I'm having a problem due to the missing module dependency in `sale_stock_margin`:
> 
> https://github.com/OCA/OpenUpgrade/runs/5710011319?check_suite_focus=true#step:13:5281
> 
> and I think it's due to the loading order of the modules, being loaded `sale_stock_margin` before `sale_stock`.

That's really weird.  If modules have the same dependencies, their relative loading order should be the order of the module names.  Hence, `sale_stock_margin` should be loaded _after_ `sale_stock`...

> Is it so bad to add the missing dependency in stable? As you have told, both are auto-installed, so the chances of having `sale_stock` if `sale_stock_margin` are very high, but if not, a `base` update would solve the problem.
> 
> Anyways, if that's not reasonable, I think the problem I have may be solved specifying a sequence in the modules. Would you accept this as a viable patch?

I don't understand.  How would you specify a sequence on modules, and how would it solve the problem?  There is a `sequence` field on modules, but it has nothing to do with _loading_ order: it's only a _display_ order.

**Comment by pedrobaeza** [comment]
Thank you very much for answering. I thought that the sequence field on ir.module.module was affecting on the loading order. I was digging more on this, and in this case, it's not something on your side (except for the missing dependency declaration), but due to the process we follow for tricking which modules are installed in the demo DB we use in the CI. I was about to write you to say it. Sorry for not being so hurry on this.

Let's keep it this way for not breaking DBs that don't update and don't have the dependency installed.

**Pull request closed without merging**
