### PR TITLE
[REF] website: restore skipped test

### PR DESCRIPTION
**Pull request by qsm-odoo**
This reverts commit ba0fe3437f79577d9934eeee151f67c1bfaf3a8d, as this
should be ok with recent forward-port.

### CODE REVIEW

**Comment by qsm-odoo** [comment]
@robodoo r+

**Comment by rdeodoo** [comment]
:+1:

**Comment by qsm-odoo** [comment]
@robodoo r- waiting for new fix by @rdeodoo

**Comment by JKE-be** [comment]
@robodoo r+ retry and thank you

**Comment by JKE-be** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
