### PR TITLE
[FIX] sms: do not display popover for void notification

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
PURPOSE

Improve SMS UX integration

SPECIFICATION

Fix recent SMS merge: do not display tooltip / popover about SMS information
in chatter if there was no recipients linked to the SMS message.

LINKS

Task 1922187

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by tde-banana-odoo** [comment]
@robodoo retry then

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by tde-banana-odoo** [comment]
@robodoo retry

**Comment by tde-banana-odoo** [comment]
@robodoo I hate you so much @d-fence @Xavier-Do

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff

**Comment by dbo-odoo** [comment]
en toute solidarité...
368o43

**Comment by tde-banana-odoo** [comment]
@robodoo It is rebased so please merge it r+ rebase-ff . I love you. Kiss.

**Comment by tde-banana-odoo** [comment]
@robodoo r+ rebase-ff 

This is the last time.

**Comment by mart-e** [comment]
@robodoo you can do it !

**Comment by rdeodoo** [comment]
@tde-banana-odoo This should be good now.
Initially fixed on saas-12.2 with https://github.com/odoo/odoo/commit/e80caa4d3ef8beff8b46275008706d94e8ca596d
But it is not yet forward ported in master.

In the meantime given the lot of fail in master, I cherry-picked it on https://github.com/odoo/odoo/pull/35030 which was merged this night, including https://github.com/odoo/odoo/commit/a55fb7ad0c0223b42ab647035621ce8fba58522d

Seeing your last rebase push force on this PR 2 hours ago, you now have the commit.

**Comment by tde-banana-odoo** [comment]
@robodoo p=1

**Comment by mart-e** [comment]
@tde-banana-odoo I was thinking all the p=1 PRs are in a batch but actually it is mixed with lousy p=2 This way you get one more chance it will fail because of another PR !
Blame @Xavier-Do

**Comment by rdeodoo** [comment]
:tada:

**Comment by tde-banana-odoo** [comment]
@robodoo I still hate you, don't worry.

**Comment by mart-e** [comment]
@robodoo blacklist=tde-banana-odoo

**Pull request closed without merging**
