### PR TITLE
[IMP] account: make recompute dynamic lines multi

### PR DESCRIPTION
**Pull request by jco-odoo**
Description of the issue/feature this PR addresses:

Current behavior before PR:
You can only recompute one invoice at a time (through xml e.g.)

Desired behavior after PR is merged:
You can recompute multiple at the same time

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jco-odoo** [comment]
@jjscarafia Could this help for the demo data?

**Comment by jco-odoo** [comment]
@smetl

**Comment by jjscarafia** [comment]
@jco-odoo yes. With this we would be able to call "_recompute_dynamic_lines" with all invoices at once. Not a huge win but we can reduce some code.

Thanks!

**Comment by jco-odoo** [comment]
@smetl

**Pull request closed without merging**
