### PR TITLE
[IMP] mail: reduce size of mention suggestion

### PR DESCRIPTION
**Pull request by alexkuhn**
Spacing was too big, and also size of suggestion list items were as big as any other content. As a result, this was too distracting compared to actual content like message list.

This commit make suggestion items smaller and also reduces spacing around suggestion items. This make suggestion less likely to truncate, so more content of suggestion is visible.

Also suggestion list takes whole width of composer, instead of just the inner textarea.

Screenshot 2024-09-23 at 13 52 45

### CODE REVIEW

**Comment by tsm-odoo** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@tsm-odoo Made the change less significant, looks better overall and keeps it practical in mobile

**Comment by tsm-odoo** [comment]
@alexkuhn can't we make the suggestion list the same width than the composer in mobile? It would be even better/easier to read.

**Comment by alexkuhn** [comment]
@tsm-odoo done

**Comment by alexkuhn** [comment]
@robodoo r+

**Comment by alexkuhn** [comment]
@robodoo r-

**Comment by alexkuhn** [comment]
Re-target 18.0: https://github.com/odoo/odoo/pull/181480

**Pull request closed without merging**
