### PR TITLE
[FIX] tests: reap chrome process early

### LINKED ISSUE #57403: Lots of zombie chromium/chrome processes left after a test session
Impacted versions: 12.0, 13.0

Steps to reproduce:

1. Run tests that include tours.

Current behavior:

- Chromium processes are left in zombie status until odoo's parent PID exits: 

- Possibly related to https://github.com/odoo/odoo/pull/45347?

Expected behavior:

- Chromium processes should get reaped immediately after they end.

@Tecnativa TT24972 @d-fence

### PR DESCRIPTION
**Pull request by d-fence**
During the tests with an HttpCase using ChromeBrowser, the Chrome
process becomes a zombie at the end of test because the main Odoo
process does not wait for its status.
It does not cause much trouble as those zombies are reaped at the end of
the Odoo process by itself.

With this commit, the Chrome process is gently asked to kill itself, if
it does not obey within 5 seconds, the process is terminated and reaped.

Fixes #57403

### CODE REVIEW

**Comment by odony** [comment]
Is there really a point? Do those processes cause any issue?

Additionally, how long does it take for chromium to stop? If it really takes up to 5 seconds, blocking for 5 seconds after each Http test class is going to delay our test suite, isn't it? If it worked in 500ms rather than 5s it would be less of a concern. Otherwise you could fork a daemon thread that does the wait().

**Comment by Yajo** [comment]
Leaving zombie processes around is never good. The question should be IMHO the contrary: is there really any benefit in creating zombie processes? If the answer is no, then this PR is good.

**Comment by Xavier-Do** [comment]
> Leaving zombie processes around is never good. The question should be IMHO the contrary: is there really any benefit in creating zombie processes?

odo's concern here is that this pr may slow down the tests if we need to wait each time. But I don't like the idea of having zombie either. The double fork solution was actually proposed by @d-fence initially so it is maybe an idea but it will introduce even more complexity.
First of all we have to define the price of this wait. Chrome is killed 80-90 times on all tests in enterprise.  (between 30 and 15 per split. In the worst case waiting 5 second*90 means ~7.5 minutes (over ~160 for all post tests). It's quite a lot. But actually most of the time we don't even wait 1 second. The cost is usually 0 or 1 second from what I saw in community, so it look like it is more around the 500ms in average, even less I guess. I would suggest to change the sleep to a lower value, something like 0.1 second and check if chrome is killed sometimes. 
I also wonder if there isn't a better way to wait for the process end without looping (maybe psutil.wait_procs?)

**Comment by xmo-odoo** [comment]
> But I don't like the idea of having zombie either.

Zombies are a normal function of unix processes. Keeping zombies around indefinitely is a problem but if we know we'll reap them at the end there really is no reason to care.

If we kinda sorta want to reclaim what little resource is being "wasted" just in case, we can just use wait3 to reap one of the previous chrome zombies without waiting, but waiting for chrome to be completely shut down & reaped seems completely unnecessary unless it actually causes problems, which it doesn't since this PR only implements some effort to reap it but doesn't actually care and carries on its merry way if chrome is still shutting down by the time a few seconds have passed.

> I also wonder if there isn't a better way to wait for the process end without looping (maybe psutil.wait_procs?)

That's just a way to wait in a loop under 3 levels of indirection. None of the wait primitives takes a timeout, so either you wait and use some sort of signal to interrupt the wait (which is risky because signals) or you don't wait and then you have to poll.

**Comment by xmo-odoo** [comment]
Alternatively, I'm told setting the `SIGCHLD` handler to `SA_NOCLDWAIT` or `SIG_IGN` (explicitly, which is different than the default `SIG_IGN` handler) will lead to children being automatically reaped and never becoming zombies. This might have problematic side-effects on other child processes though.

**Comment by xmo-odoo** [comment]
Alternatively, I'm told setting the `SIGCHLD` handler to `SA_NOCLDWAIT` or `SIG_IGN` (explicitly, which is different than the default `SIG_IGN` handler) will lead to children being automatically reaped and never becoming zombies. This might have problematic side-effects on other child processes though.

**Comment by d-fence** [comment]
As this fix will wastes more resources that the problem it tries to fix, I prefer to close it.

**Pull request closed without merging**
