### PR TITLE
[FIX] point_of_sale: serialnumber returns

### PR DESCRIPTION
**Pull request by switch87**
[FIX] point_of_sale: return products with serial numbers
   
* Do a product return of a product with serial number required.
* Open the dialogue to enter the serial numbers.
    
Current behaviour before PR:
* A modal without any input fields will be displayed.
    
Desired behaviour after PR is merged:
* The modal has as many input fields as there are products to be returned.
    
The modal is populated by the value of `lots_required`. To get the right
value this variable should have the absolute value of the amount of
products.
    
After closing the modal there will be a check on the amount of serial
numbers given. This will automatically update the amount of the product.
Because this value is always positive we have to do a check on the
product quantity first to know the sign of the new value.
    
[FIX] point_of_sale: quantity of lot return
    
* Do a product return of a product with a lot number required.
* pay the order.
* Close and finalise the PoS session.
    
Current behaviour before PR:
* A product move is generated with a negative value with destination stock.
* Odoo will ask if you want to make a backorder.
    
Desired behaviour after PR is merged:
* A product move is generated with a positive value and can be set done without any issues.
    
To fix this problem the quantity of the picking has to be set to the
absolute value of the order line quantity.

closes: #33512

### CODE REVIEW

**Comment by switch87** [comment]
@len-odoo Is it ok I kept it in one pr with two commits?

**Comment by len-odoo** [comment]
Of course. Separation of commits is mostly to make sure that the messages describe each issue, and in cases where a revert/modification is needed with have a cleaner history.

**Comment by len-odoo** [comment]
Okay that's much better. 

I don't know why you keep using serialnumbers, inputfields of serialnr; it's better have correct English for everything that is not code. For the title, we try to keep it as short as possible but it is preferred to go over the character limit rather than butcher the sentence. 

Another small detail: you lost the closes #something when rewriting the messages. It's best to keep these.

**Comment by switch87** [comment]
> Okay that's much better.
> 
> I don't know why you keep using serialnumbers, inputfields of serialnr; it's better have correct English for everything that is not code. For the title, we try to keep it as short as possible but it is preferred to go over the character limit rather than butcher the sentence.
> 
> Another small detail: you lost the closes #something when rewriting the messages. It's best to keep these.

Sorry, its a bad influence from Dutch, we glue everything together if it doesn't change the pronunciation.

**Comment by len-odoo** [comment]
robodoo retry

**Pull request closed without merging**
