### PR TITLE
[IMP] hr_holidays: change responsible_id from many2one to many2many

### PR DESCRIPTION
**Pull request by kbapt**
task - 3060720

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kba-odoo** [comment]
robodoo r+

**Comment by kba-odoo** [comment]
robodoo r+

**Comment by kba-odoo** [comment]
robodoo r+

**Comment by hwangh95** [comment]
@kbapt @sofiagvaladze Was there a reason why the activities were changed from activity_schedule to directly creating using a vals_list and create? Now you can't prevent activities using the `mail_activity_automation_skip` context anymore, it always creates activities

**Pull request closed without merging**
