### PR TITLE
Brand (some) PDFs as created/produced by Odoo

### PR DESCRIPTION
**Pull request by xmo-odoo**
Implement by monkey-patching PyPDF2 with a pre-configured subclass rather than modify half a dozen instantiations, also avoids having to chase future ones.

Task 1902919

### CODE REVIEW

**Comment by Elkasitu** [comment]
@xmo-odoo I checked this before, there seem to be some files where PdfFileWriter is called and used directly, shouldn't we patch those too? Or replace them by the patched class?

```
odoo/addons/base/models/ir_actions_report.py
25:from PyPDF2 import PdfFileWriter, PdfFileReader
563:                            attachment_writer = PdfFileWriter()
594:        # We have to close the streams after PdfFileWriter's call to write()
599:        writer = PdfFileWriter()

addons/account_facturx/models/ir_actions_report.py
5:from PyPDF2 import PdfFileWriter, PdfFileReader
24:                writer = PdfFileWriter()

addons/hr_fleet/controllers/main.py
10:from PyPDF2 import  PdfFileReader, PdfFileWriter
31:        writer = PdfFileWriter()
```

**Comment by xmo-odoo** [comment]
@Elkasitu the PR is patching PyPDF2.PdfFileWriter directly. All the addons should be imported (and thus their imports executed) after that happens and get the proper (patched) class.

**Comment by nilshamerlinck** [comment]
@lukebranch Add Odoo branding in metadatas, see commit ;-)

**Comment by xmo-odoo** [comment]
@robodoo r+

**Comment by xmo-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
