### PR TITLE
[master] Brazilian Chart of Account

### PR DESCRIPTION
**Pull request by renatonlima**
Hi guys,

Today we can't use l10n_br chart of account since 9.0 when there were many changes in account, I think the module has been migrated automatically and some information does not represent the configuration of the data in Brazil, for example the creation of account.tax.tag is not correct (it is not necessary to create tags for each percentage of taxes) Also the account.tag is not correct (account.group should be created to create the accounting account hierarchy), now we are migrating Brazilian localization OCA/l10n-brazil to 13.0 and I updated l10n_br including:

Removed creating fields in core objects account.tax.template and account.tax and its views;
Update tax group;
Update tax template (Need to update tax percentages);
Update account.group to implement hierarchy in accounting reports;
Update chart of account according Brazilian Federal Accounting Council Resolution No. 1.418/12

I did one PR into 12.0 branch to current stable version

### CODE REVIEW

**Comment by mart-e** [comment]
@jco-odoo to check on tomorrow during the merge sprint and check with Akretion if questions
@renatonlima could you rebase your branch please?

**Comment by william-andre** [comment]
@jco-odoo Regarding the brazilian coa, there is still this PR.
I will amend it regarding the `account.group` changes, but I think it should be good after a short glance.

Can you confirm it is a good idea?

**Comment by lathama** [comment]
@renatonlima can you update your PR to address the conflicts?

**Comment by jco-odoo** [comment]
Things might have evolved in the meantime.

**Pull request closed without merging**
