### PR TITLE
[IMP] calendar: create hooks for calendar invites

### PR DESCRIPTION
**Pull request by Yenthe666**
Description of the issue/feature this PR addresses: Allow to further customize and inherit the behaviour of sending calendar events emails

Current behavior before PR: There is no easy nor clean way to modify the behaviour of sending out the emails to attendees.
If you want to modify colors, content in the attachment values or who to email.

Desired behavior after PR is merged: Clean and easy overrides. You can now easily:
- Modify the default colors (and add colors for other states if you want to add custom states),
- Modify content of the attachments,
- Modify who gets emailed (e.g by doing a `super()` on the function with a filtered

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@tde-banana-odoo does this fall under your umbrella too? :)

**Comment by tde-banana-odoo** [comment]
Hello,

Can't colors be tweaked directly in the template itself ? I think I tried to remove some unnecessary stuff in 15+, so not sure all those hooks are necessary in 14 ...

**Comment by Yenthe666** [comment]
> Hello,
> 
> Can't colors be tweaked directly in the template itself ? I think I tried to remove some unnecessary stuff in 15+, so not sure all those hooks are necessary in 14 ...

Well then it could be merged only in V14 or partial merge for V15? :) E.g that for loop is still not easily inheritable in V15.
You did cleanup & improve the rest in V15 indeed. I personally ran stuck on these methods for a project where we send travel programmes out to customers and have to individualize who does or does not get those invites along with multiple emails depending on our custom app :) I have no clean way to do it now.

**Comment by Yenthe666** [comment]
@tde-banana-odoo friendly reminder 🤞

**Comment by tde-banana-odoo** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
Thanks a lot :)

**Pull request closed without merging**
