### PR TITLE
[FIX] website_sale: discount_policy field value not depends on sale.g…

### PR DESCRIPTION
**Pull request by eantones**
…roup_discount_per_so_line check

Whether check "sale.group_discount_per_so_line" is selected or not, the option "with_discount" of the field discount_policy is always selected by default in the pricelist form.

In case the sale.group_discount_per_so_line check is False the discount_policy field is hidden in the pricelist form and the user does not know what discount policy is being applied and he/she are not able to change it.

I understand that there's a third state here that has to be dealt with, when the sale.group_discount_per_so_line check is False and no matter what value discount_policy has, the original strikethrough price has to remain hidden but the discount has to be applied anyway.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by JKE-be** [comment]
@fgi-odoo 

Can I have your PoV...

I'm ok with the issue, but because this feature can be set on a user and not all, that will be strange to see that because public user have 'dicount on line' he see triked price, but once logged not

**Comment by JKE-be** [comment]
ping @fgi-odoo

**Comment by JKE-be** [comment]
last ping @fgi-odoo

**Comment by JKE-be** [comment]
Since it required change in xml file, it should target the new master (v12).

@fgi-odoo has no opinion on this apparently, so I suggest to do it, it is more consistent with the feature group_discount_per_so_line

Thanks for PR

**Comment by eantones** [comment]
Thank you @JKE-be :+1:

**Comment by rdeodoo** [comment]
Handled with 27825cbf1340bd6b280a494bcb26297cb3cb973e

**Pull request closed without merging**
