### PR TITLE
[15.0][FIX] purchase_stock: Use hook method

### PR DESCRIPTION
**Pull request by pedrobaeza**
This uses the hook method introduced in
https://github.com/odoo/odoo/commit/ce1f1b69e75e8ab77083010a8487bfc35bbbb903 for consistency when used on modules that modify this behavior.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi @amoyaux, I hope your comeback from Tenerife was good. As we talked in the Spanish OCA Days, here is the patch of #136616 rebased over 15.0 branch, which is the oldest supported branch. Let's hope this can be merged for at least avoiding the ugly patch downstream in this version.

**Comment by pedrobaeza** [comment]
@amoyaux any news about this?

**Comment by amoyaux** [comment]
@pedrobaeza We are a bit busy on the freeze. I check that next week, just after

**Comment by pedrobaeza** [comment]
@amoyaux friendly reminder

**Comment by amoyaux** [comment]
robodoo r+

**Comment by amoyaux** [comment]
I truly apologize for the delay

**Comment by pedrobaeza** [comment]
Thank you very much. This finally happens!

**Pull request closed without merging**
