### PR TITLE
[IMP] pos_cache with new or changed products

### PR DESCRIPTION
**Pull request by wardm95**
Description of the issue/feature this PR addresses:

Current behavior before PR:
* Open a POS session
  * All products from cache are loaded into POS session
* Create a new product or change an existing product.
* Reload POS session (with F5 or Close/Resume)
  * All products from cache are loaded into POS session again
  * New or changed products are **not** available in POS session

Desired behavior after PR is merged:
* Open a POS session
  * All products from cache are loaded into POS session
* Create a new product or change an existing product.
* Reload POS session (with F5 or Close/Resume)
  * All new or changed products are loaded in the cache
  * All products from cache are loaded into POS session again
  * New or changed products are **now** available in POS session

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hey @jorenvo could you look at this PR when you've got time? One of my team members tried to improve the pos cache module. :-)

**Comment by Yenthe666** [comment]
As for the CLA that is failing in the Runbot.. this is handled with PR https://github.com/odoo/odoo/pull/17774
The e-mail was incorrect on the company CLA.

**Comment by jorenvo** [comment]
@mart-e I'm not sure what to do with this. I think the idea is ok, but I'm not sure worth the risk merging this in stable. What do you think?

**Comment by Yenthe666** [comment]
I think technically it doesn't break any stable guides but I was wondering the same. Perhaps it also cleaner to change the api.one to an api.multi with a self.ensure_one?

**Comment by mart-e** [comment]
Sorry but indeed, this is a change of behaviour that is not without risk and I would rather not see an improvement in 10.0.
Doesn't this patch risks to put the modified products in duplicate in the cache?
If you want to add new products, you should use the `create_date`. If you want to update modified products, you should check to avoid duplicates.

**Comment by Yenthe666** [comment]
@wardm95 let us make a new one against master with the suggestiona from Martin.

**Comment by wardm95** [comment]
@Yenthe666 great idea :)

**Pull request closed without merging**
