### PR TITLE
[IMP] account_budget: support view and consolidation children in budget ...

### PR DESCRIPTION
**Pull request by sbidoul**
fixes issue #372
fixes https://bugs.launchpad.net/openobject-addons/+bug/1070418

### CODE REVIEW

**Comment by malonsopraxya** [comment]
hi, stéphane.

your fix works well with accounts. is there any function to calculate the analytic account tree?
when using view type analytic accounts in budgets, practical amount shows nothing :/

thanks, kind regards

**Comment by sbidoul** [comment]
I kind of remember having seen another PR for that but I can't find it right now.

**Comment by malonsopraxya** [comment]
this one? https://github.com/odoo/odoo/issues/372

ps. good morning! :)

**Comment by sbidoul** [comment]
It must be that one indeed

**Comment by beledouxdenis** [comment]
Closed with da9d1a8c4594835217a7af78fe66f188e3260b63.

**Comment by beledouxdenis** [comment]
Thank you for your contribution ! Of course :).

**Comment by sbidoul** [comment]
Eh eh, so some things don't get lost forever after all.

Thanks for merging.

**Pull request closed without merging**
