### PR TITLE
[FIX] account: tax's widget error

### PR DESCRIPTION
**Pull request by jpp-odoo**
[FIX] account: tax's widget error

- Create a new purchase tax with 0 as amount (Tax 0%);
- Create a new Bill, add a new line with the new Tax 0%;
- Use the tax's widget to modify the tax amount.

Before this commit, an error message was shown.

Now, only taxes values bigger than zero can be modified with the widget.

opw-2307761

---------------------------------------------------------------

[FIX] account: show taxes when they are zero on invoices print

Before this commit, the taxes with amount of zero are not shown on
invoice print. For instance, the 15% tax of a product with value of
€0.01 will not be show on invoice print.

This previous commit 37a0f7acae8aebef35577b178f8aeefed11c9105 allows
showing zero percent taxes on invoice print. This commit, will
fine-tuning the previous commit to also show taxes with zero amount.

opw-2307761

### CODE REVIEW

**Comment by nim-odoo** [comment]
robodoo delegate+

**Comment by jpp-odoo** [comment]
robodoo +

**Comment by jpp-odoo** [comment]
robodoo r+

**Comment by jpp-odoo** [comment]
@robodoo rebase-ff

**Comment by simongoffin** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
