### PR TITLE
microcom corporate CLA

### PR DESCRIPTION
**Pull request by mmalorni**
Description of the issue/feature this PR addresses:
Addition of CLA for partner Microcom

Current behavior before PR:
No CLA
Desired behavior after PR is merged:
Have CLA and we can push some fixes.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mmalorni** [comment]
@odony  @mart-e 
I followed the procedure for the CLA submission. When will the CLA be merged and when can we send bug fixes? We have 3 issues that we have resolved in the code but we are waiting to do PRs for them until the CLA has been merged.

**Comment by Yenthe666** [comment]
@mmalorni making a PR for the lowest version is enough, you shouldn't make a PR against two versions.
The concept from Odoo is that when a PR is merged in 9.0 it'll be forwarded to the master every once in a while.

**Comment by mart-e** [comment]
Hi @mmalorni ,

Thanks for the patch, as said Yenthe, submit for the [lowest version only](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch). So if you intend to commit in 8.0, should be submitted there (no need to create a new PR, I can rebase it).

However, in your signature, you use links `https://github.com/orgs/microcom/people/<user>` but the organisation is private so we can not access these links.
Could you modify the signature to get direct links to the users?

**Comment by coleste** [comment]
@mart-e Is this better?

**Comment by odony** [comment]
@coleste Yes, that's what @mart-e meant, thank you! Merged in 9.0 at ff95ea976d47e0b9a1283250c92ff066648fc830

Very nice to see Microcom starting to officially contribute to Odoo, by the way! :-)

**Pull request closed without merging**
