### PR TITLE
[website_sale_delivery] load carrier price async

### PR DESCRIPTION
**Pull request by rdeodoo**
Before this commit:
User landing on checkout payment step had to select a carrier.
These carriers only showed 'Select to compute price'. This was done to
prevent the page to take seconds to load, since it would compute all the
carrier price by querying these carrier API then display the page.
The users would still click on every carrier anyway to check all the prices and
select the cheapest one.

Now:
Once the page is loaded, we will asynchronously retrieve every carrier prices
without really modifying the order (preview param on the route rollbacking the
transaction).
That way, the page rendering page will not be affected and the user will be
able to see the price of every carrier after a few seconds without having to do
anything.

task-1867265

### CODE REVIEW

**Comment by rdeodoo** [comment]
THe python part to retrieve delivery cost will need a deeper implementation, not a workaround like this.
Probably a method in generic payment code to simulate delivery cost without modifying current order.
@JKE-be Is this needed for V12? If yes, for release or after?

**Comment by JKE-be** [comment]
target v12.1

**Comment by rdeodoo** [comment]
The python part to retrieve delivery cost will need a deeper implementation, not a workaround like this.
Probably a method in generic payment code to simulate delivery cost without modifying current order.
Anyway while there is no Product Owner task this is useless

**Comment by JKE-be** [comment]
HEre the task: 1867265

Need to be refactord for v12.x, requied a refctoring of delivery modules

**Pull request closed without merging**
