### PR TITLE
Typo fix.

### PR DESCRIPTION
**Pull request by konard**
Description of the issue/feature this PR addresses:

The translation contains a typo.

Current behavior before PR:

The translation contains a typo.

Desired behavior after PR is merged:

The typo will be removed from the translation.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thanks for the contribution but please check [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://transifex.com/odoo), not Github.

Please submit your changes there and let me know if you have issues.

Thanks

**Comment by Konard** [comment]
The link to transifex ends up with 404 error.

**Comment by mart-e** [comment]
@Konard if you do not have an account yet, try https://transifex.com/odoo/public

**Comment by Konard** [comment]
Which project should I choose for this particular change?

**Comment by mart-e** [comment]
If you have found the error in version 12.0, the odoo-12 is the one to start with. As you have found the issue in website, this is the resource too. So :
https://www.transifex.com/odoo/odoo-12/translate/#ru/website/151517956?q=text%3A'A+CDN+helps+you+serve+your+website'

While you are fixing a typo, you can also check in the other projects if the wrong term is not used there too.
You can use the tab "Suggestions" in the translation interface to see if there is other 100% matches to easily detect remaining use of the wrong terms.

If you have trouble to find your term from your odoo instance, please check the following section of the doc
https://github.com/odoo/odoo/wiki/Translations#how-to-determine-where-a-term-comes-from-when-in-odoo

**Comment by Konard** [comment]
So what is next? When the change will arrive to this repository?

**Comment by mart-e** [comment]
[When will my translations appear in the software (or in GitHub)?](https://github.com/odoo/odoo/wiki/Translations#when-will-my-translations-appear-in-the-software-or-in-github)
Next Sunday
Thanks for the fix

**Comment by Konard** [comment]
Ok, thank you for explanations.

**Pull request closed without merging**
