### PR TITLE
[FIX] point_of_sale: allow overriding mail values

### PR DESCRIPTION
**Pull request by Yenthe666**
Before this commit

Description of the issue/feature this PR addresses: allow overriding/adding values for the mail message easily and clean.

Current behavior before PR:  the only way to modify/extend the mail values is by taking over the whole function which is dirty and can cause missing updates or changes (e.g fixes)

Desired behavior after PR is merged:
By splitting the mail_values up in a subfunction we can do a clean and small super() to modify or inject values

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Yenthe666** [comment]
@pimodoo @mart-e could I ask one of you to check this PR? We need to override these values in order to modify the content being sent to the customer :) Right now we need to copy an ugly big part of code and after this PR we could do a clean super.

**Comment by pimodoo** [comment]
@robodoo r+ rebase-ff

**Comment by pimodoo** [comment]
@fw-bot up to 14.0

**Comment by Yenthe666** [comment]
Yay, thanks a lot! 🙏

**Pull request closed without merging**
