### PR TITLE
[IMP] stock: update product directly from _compute_quantities_dict

### PR DESCRIPTION
**Pull request by ivantodorovich**
By updating all the fields/keys retrieved by `_compute_quantities_dict`, rather than just a group of hardcoded ones, it makes it possible to efficiently extend the model to add extra fields to compute by it.

ping @yelizariev 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by jcoux — APPROVED** [review]

**Comment by yelizariev** [comment]
I'm not sure that it could be merged in stable branch, because it's not a fix, but improvement...

**Comment by ivantodorovich** [comment]
Yeap, it's not adding fields nor changing methods signatures, but you're probably right. Should I target master instead?

**Comment by yelizariev** [comment]
@ivantodorovich yes please target to master. It could be backported later if we find it safe

**Comment by ivantodorovich** [comment]
@yelizariev done, retargetted master
thanks !

**Comment by amoyaux** [comment]
robodoo r+
Thanks @ivantodorovich

**Pull request closed without merging**
