### PR TITLE
[FIX] stock: cache is not clear after merge quants

### PR DESCRIPTION
**Pull request by fmdl**
**Description of the issue/feature this PR addresses:**
Merge quant can delete some quant by direct SQL (without using unlink()).
The cache is not cleared.

@nim-odoo
@jco-odoo 

Note : can be merged in master.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fmdl** [comment]
cc @sla-subteno-it

**Comment by fmdl** [comment]
@amoyaux

**Comment by amoyaux** [comment]
Ok for master

**Comment by fmdl** [comment]
@amoyaux ready for master

**Comment by fmdl** [comment]
Close by https://github.com/odoo/odoo/pull/57236

**Pull request closed without merging**
