### PR TITLE
[FIX] Read measures from context

### LINKED ISSUE #2835: [8.0] Reporting - Chart, Filter, Dashboard - selected Measures, Chart Type not saved
Hello,

(I know it's possible to set the chart type and the measures in a graph view and an action)

Although you can save a Filter, share it with others and add it to a dashboard, the selected Measures, and Chart Type, (stacked, etc.) are not saved.
Especially for financial analysis, (e.g. entries analysis) it can become quite misleading if the measures are not saved (credit, debit, balance).
So the feature is sadly quite limited for pure endusers without access rights and knowledge of views and actions. 
Would you consider to not only save filters but also graph view options through the gui?

with kind regards,
Sven

### PR DESCRIPTION
**Pull request by mistotebe**
Fixes #2835

### CODE REVIEW

**Comment by mistotebe** [comment]
I runbot broken?

**Comment by mistotebe** [comment]
This is a one liner, can it be reviewed?

Steps to reproduce:
1. Create a dashboard with custom measures
2. Open said dashboard
3. Without fix: the default measures will show. With: saved measures

**Comment by Yenthe666** [comment]
@mart-e can you have a look at this one? Looks neat.

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards

**Pull request closed without merging**
