### PR TITLE
[FIX] kanban: propagate context of many2many field

### LINKED ISSUE #5623: Can't use the short partner category name in kanban view
In v8 I'm trying to inherit the partner views to display only the short name of the partner categories instead of the long name.
It works for form views using `context` and the option `always_reload`, but it does not work in the kanban view.

In my custom module (https://github.com/numerigraphe/community-data-files/tree/8.0-remove-l10n-fr/l10n_eu_nace), I have added this view and it works, the form view does display the short name :
```
  	<record model="ir.ui.view" id="view_partner_form">
            <field name="name">Partner form : short category name</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_partner_form" />
            <field name="arch" type="xml">
                <field name="category_id" position="attributes">
                    <attribute name="context">{'partner_category_display': 'short'}</attribute>
                    <attribute name="options">{"always_reload": True}</attribute>
                </field>
            </field>
        </record>
```
form

But when I do it with on the kanban vie it does not work, the view still displays the long category name.
```
        <record model="ir.ui.view" id="res_partner_kanban_view">
            <field name="name">Partner kanban : short category name</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.res_partner_kanban_view" />
            <field name="arch" type="xml">
                <field name="category_id" position="attributes">
                    <attribute name="context">{'partner_category_display': 'short'}</attribute>
                    <attribute name="options">{"always_reload": True}</attribute>
                </field>
            </field>
        </record>
```
kanban

### PR DESCRIPTION
**Pull request by nle-odoo**
Propagate the context in kanban view when displaying a many2many field.

fixes #5623

opw-629698

### CODE REVIEW

**Comment by beledouxdenis** [comment]
To me, this is globally correct.

Nevertheless:
 - Can't you apply this in 7.0 ?
 - I would have preferred to avoid passing by the new variable m2m_context, to find a way to directly access the field context without having to introduce a new variable in the kanban view, but I can't find a way, I guess it was the same for you ?

**Comment by nle-odoo** [comment]
for 7.0 : yes.

otherway :

with my first attempt ( odoo-dev@981f7213eebe2c6a23c5a3b84c3b31313b661ed0 ) and a kanban view :

```xml
<field name="test" context="{'hello': 'world'}" />
<templates>
  <field name="test" context="{'hello': 'monde'}" />
  <field name="test" context="{'hello2': 'cruel'}" />
</templates>
```

* the context propagated in the `name_get` would be `{'hello': 'monde', 'hello2': 'cruel'}`,
* it seems in phase with the [kanban docs](https://www.odoo.com/documentation/master/reference/views.html#kanban), the only attributes of a field outside `<templates>` should be `name`, `sum`, `avg`, `min`, `max`, `count` ( so no context ),
* and in this case, many2manys could be transformed in an object mapping many2many name and context : `{ 'm2m_field_a': contexta, 'm2m_field_b': contextb}`.

but since only one `name_get` is called it seemed more intuitive (maybe wrongly) to do it like this and with the given example only have a context of `{'hello': 'world'}`.

if the first way I did ( and which would allow to remove the m2m_context ) was preferred, the issue submitter would need to override the `category_id` with an xpath ( to add attributes to the second occurence of  `<field name="category_id" />` and not the first one like it's done currently ).

**Comment by beledouxdenis** [comment]
After having reviewed with @KangOl :
 - It could happen that you would have several many2many fields with a same relation. This is a bit a border case, but this is possible. The key for the dict m2m_context should therefore probably be the field name instead of the relation name, if possible.

Besides that, we are ok with that :).

**Comment by KangOl** [comment]
I'm not even sure it works when in this case. The `relations` var already use the destination model as key.

**Comment by nle-odoo** [comment]
i've added a commit for using the field name instead of the relation, and i've cherry-picked and tested it in 7.0 ([compare](https://github.com/odoo/odoo/compare/7.0...odoo-dev:7.0-fix-field-context-kanban-nle))

as @KangOl said, as the code is right now, using relations or field name as key to a `m2m_context` object gives the same result.

**Comment by KangOl** [comment]
Mustn't this patch be made in 7.0?

**Comment by nle-odoo** [comment]
yes, i have a [branch](https://github.com/odoo-dev/odoo/tree/7.0-fix-field-context-kanban-nle) in 7.0 with these two commits.

**Comment by KangOl** [comment]
pushed in 7.0 at e1daaff
Will be forward-ported to 8.0 later.

**Pull request closed without merging**
