### PR TITLE
[FIX] sale: sale_tour selector fix

### PR DESCRIPTION
**Pull request by jhk-odoo**
Steps to reproduce:
- install sales
- go into debug mode
- dev tools > start tour > sale_tour

Previous behavior:
tour would fail to see that the product has been selected
and time out

Current behavior:
the tour finishes properly

opw-2187218

### CODE REVIEW

**Comment by jhk-odoo** [comment]
@nim-odoo 
@corentindelacroix

**Comment by jhk-odoo** [comment]
@nle-odoo 
this fix is not related to the feature request we discussed this morning (execute tours multiple times)
it is to be implemented with this task:
https://www.odoo.com/web?#id=2187222&action=2965&active_id=1544407&model=project.task&view_type=form&menu_id=4720

**Comment by nle-odoo** [comment]
I think the tour work one time or runbot would be red

the issue is that the tour create a product "DESK0001" but this only work one time because the next time you can't create the "DESK0001" that is already created. So thanks to your fix, the first time the tour is ran "DESK0001" is created and the following times the tour is ran we use the existing "DESK0001"

in the selector:

```css
.ui-menu.ui-widget.ui-item-menu
```

.ui-menu.ui-widget is parent of .ui-item-menu so this should one of the following instead:

```css
.ui-item-menu
// or
.ui-menu .ui-item-menu
// or
.ui-menu.ui-widget .ui-item-menu
```

**Comment by jhk-odoo** [comment]
updated

**Comment by nim-odoo** [comment]
runbot is red

**Comment by nle-odoo** [comment]
sorry it's `ui-menu-item` not `ui-item-menu` I retyped it wrong in my comment

**Comment by jhk-odoo** [comment]
runbot is green :+1:

**Comment by nle-odoo** [comment]
robodoo r+

**Pull request closed without merging**
