### PR TITLE
[FW][15.0][FIX] mail: _search_message_partner_ids performance

### PR DESCRIPTION
**Pull request by chienandalu**
Backporting #121561 to v15

cc @Tecnativa TT43572

@tde-banana-odoo would it be possible to merge into v15 as well?

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@chienandalu Yep, maybe add in commit message this is a manual backport and link the commit ? That way we can track history. 

Maybe backport https://github.com/odoo/odoo/pull/132306 also ? No need to make two PRs, just cherry-pick the two commits in this PR and we merge both commits at once :)

**Comment by chienandalu** [comment]
> @chienandalu Yep, maybe add in commit message this is a manual backport and link the commit ? That way we can track history.

Well, look that I already targeted this branch for that PR :wink:

**Comment by tde-banana-odoo** [comment]
> > @chienandalu Yep, maybe add in commit message this is a manual backport and link the commit ? That way we can track history.
> 
> Well, look that I already targeted this branch for that PR 😉

Yep, removed the part about the test ^^ just link the fix in 16 in commit message to know it is a backport :)

**Comment by chienandalu** [comment]
> Yep, removed the part about the test ^^ just link the fix in 16 in commit message to know it is a backport :)

Done! :smile:

**Comment by pedrobaeza** [comment]
Thibault, thanks for the merge wave you are doing! :heart:

**Pull request closed without merging**
