### PR TITLE
[IMP] portal: enable portal-bg edition

### PR DESCRIPTION
**Pull request by imanie383**
Before this commit, users could not change the portal background. To change the portal background, the only workaround was overwriting existing portal bg with SCSS.

Now, we can change the portal background with $o-portal-bg-color, centralizing color management

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by imanie383** [comment]
@rdeodoo

**Comment by imanie383** [comment]
@chevalierv

**Comment by reth-odoo** [comment]
Hello, does this actually allow to do things that couldn't be done before with `!important`, or is it just a convenience fix?

As this is a stable release (and the oldest supported one, at that), it's best if we can avoid changing the behavior of CSS. Especially broad variables like this one.

-----------------------

Side note
Normally there's a github team pinged on every new PR so no need to ping people right off the bat :)
(or at least you can ping the same team again ^^)

**Comment by imanie383** [comment]
> Hello, does this actually allow to do things that couldn't be done before with `!important`, or is it just a convenience fix?
> 
> As this is a stable release (and the oldest supported one, at that), it's best if we can avoid changing the behavior of CSS. Especially broad variables like this one.
> 
> Side note Normally there's a github team pinged on every new PR so no need to ping people right off the bat :) (or at least you can ping the same team again ^^)

We didn't need !important,

but we need to repeat this odoo code in my app, because $o-portal-bg-color is harcoded

#wrapwrap.o_portal {
      @include o-bg-color($o-portal-bg-color, $with-extras: false);
  }

**Comment by reth-odoo** [comment]
It doesn't seem like this really impacts end users, and the side effects are too broad for too little upside. If you can use a work around please use that.

If you have a similar issue in master feel free to open a PR as an improvement there.
Thanks

**Pull request closed without merging**
