### PR TITLE
modif inspur ccla to add Jack and Jerry

### PR DESCRIPTION
**Pull request by JackSunI**
modif inspur ccla to add Jack and Jerry , Sorry , i push the commit again to add Jerry's  correct email @lap-odoo @mart-e

### CODE REVIEW

**Comment by mart-e** [comment]
Hello,

Thank you for the CLA signature but it seems there is still an issue.

- you are signing _using_ the address `...7@163.com`
- you are signing _for_ the address `...@inspur.com`

The email address in the CLA must be the same as for the signature for the verification to succeed.
You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.

Thanks

**Comment by JackSunI** [comment]
> Hello,
> 
> Thank you for the CLA signature but it seems there is still an issue.
> 
> * you are signing _using_ the address `...7@163.com`
> * you are signing _for_ the address `...@inspur.com`
> 
> The email address in the CLA must be the same as for the signature for the verification to succeed.
> You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.
> 
> Thanks

Sorry


> Hello,
> 
> Thank you for the CLA signature but it seems there is still an issue.
> 
> * you are signing _using_ the address `...7@163.com`
> * you are signing _for_ the address `...@inspur.com`
> 
> The email address in the CLA must be the same as for the signature for the verification to succeed.
> You can either change the your [git configuration](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or modify the email in the CLA signature.
> 
> Thanks

Sorry ,
   i change the emial and push the commit again 
  Thanks

**Comment by mart-e** [comment]
Hello,

Thank you for the signature, it will soon be integrated into Odoo.
Future pull requests made on odoo will be validated by the runbot.
If you have existing PRs that are awaiting for CLA validation, don't forget to rebase your code as soon as this is merged.

Regards

@robodoo review+

**Comment by sle-odoo** [comment]
robodoo retry

**Comment by sle-odoo** [comment]
robodoo retry

**Pull request closed without merging**
