### PR TITLE
[FIX] purchase_stock: fix unexpected access right issue

### PR DESCRIPTION
**Pull request by adda-odoo**
Prerequisites -->

1) Login with a user with just Inventory/User access rights 
2) Product A with purchase policy set to `on ordered quantities`
3) Product category of A set to `AVCO` costing method

Steps -->

1) Create+confirm a PO with product A and create and confirm vendor bill 
2) Switch to Inventory/User user
3) Try to validate picking
4) Access right error

This occurs due to the fact that `Inventory/User` does not have access to `stock.valuation.layer` or `account.move.line`.

Solution -->

Add sudo to the lines where accesses to SVL and invoice lines are made.

opw-3357028

### CODE REVIEW

**Review by DjamelTouati — APPROVED** [review]
LGTM, thank you for the fix!

**Review by DjamelTouati — CHANGES_REQUESTED** [review]
Could you add a small test please @adda-odoo 
Thanks!

**Comment by adda-odoo** [comment]
Hi @DjamelTouati test case added!

**Comment by DjamelTouati** [comment]
Hello @adda-odoo 
the test does not crash without your fix, so it is useless

**Comment by adda-odoo** [comment]
Hey @DjamelTouati, you're right. It's interesting because if I try to access `stock.valuation.layer` with the inventory user like `self.env['stock.valuation.layer].with_user(self.res_users_stock_user).search([]), I run into the access right issue, that the sudo is supposed to solve. Any ideas?

**Comment by DjamelTouati** [comment]
Hello @adda-odoo ,
Before using the `with_user()` function, always make sure to invalidate the cache to trigger access checks. This is because if the ORM has the information "line.move_ids.stock_valuation_layer_ids" in the cache, it will not fetch it and therefore will not perform the access checks.

I have also cleaned up the test to optimize it.


It is always important to run the test without your fix first (it should raise an error). After applying your fix, the test should pass. Otherwise, the test is futile, and there is no advantage in adding it.

Thank you for your work and have a nice day !

**Comment by amoyaux** [comment]
robodoo r+

**Pull request closed without merging**
