### PR TITLE
REM update china city data follow standard published in 2019

### PR DESCRIPTION
**Pull request by jeffery9**
Description of the issue/feature this PR addresses:
update city data of China to the latest follow the standard ref. to  ref to. http://xzqh.mca.gov.cn/

Current behavior before PR:
out of date city data

Desired behavior after PR is merged:
use the latest city data

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by mart-e** [comment]
@jeffery9 you are making commits with your address `j...@outlook.com` but you have signed the CLA with `j..@gmail.com`

**Comment by mart-e** [comment]
Thanks !
robodoo r+

**Comment by pedrobaeza** [comment]
@mart-e this seems that got stalled in robodoo stack

**Comment by mart-e** [comment]
It is because @jeffery9 pushed commits in the branch before it got merged.
Is there new changes you want to include?

**Comment by pedrobaeza** [comment]
No, it was only because I got to this through codetriage.com. Then should it be closed?

**Comment by mart-e** [comment]
My question was to @jeffery9 ;-)
@jeffery9 was the push force an error or do you wish to include more content?

**Comment by jeffery9** [comment]
I think this should been closed. thanks,

**Pull request closed without merging**
