### PR TITLE
[FIX] packaging: adapt packaging to pep-0420

### PR DESCRIPTION
**Pull request by d-fence**
Since a0f9ef56, a _vendor module was added without `__init__.py` file,
following the pep-0420 specifications.

Unfortunately, the `_vendor` directory is not packaged without the init
file, leading to an import error when running Odoo from the src,deb and
rpm packages.

### CODE REVIEW

**Comment by d-fence** [comment]
@xmo-odoo this modification in setup.py seems to work too:

```
diff --git a/setup.py b/setup.py
index cdcf6aa03b5..200516df103 100644
--- a/setup.py
+++ b/setup.py
@@ -19,7 +19,7 @@ setup(
     classifiers=[c for c in classifiers.split('\n') if c],
     license=license,
     scripts=['setup/odoo'],
-    packages=find_packages(),
+    packages=find_packages() + ['odoo/tools/_vendor'],
     package_dir={'%s' % lib_name: 'odoo'},
     include_package_data=True,
     install_requires=[
```

**Comment by d-fence** [comment]
@xmo-odoo it seems to work with [find-namespace-packages](https://setuptools.readthedocs.io/en/latest/setuptools.html#find-namespace-packages)

**Comment by xmo-odoo** [comment]
@d-fence possible nit for find-namespace-packages: looks like the current Ubuntu LTS (Bionic Beaver, until ~today) only has setuptools 39, which doesn't have this function. I don't know how much that matters for *running* packaging though.

**Comment by d-fence** [comment]
@xmo-odoo I finally switched back to the first solution even if the package.py is using a Debian Buster Docker image, the `find_namespace_packages` function could cause problem to people that wants to build a source package with setuptools only.

**Comment by d-fence** [comment]
robodoo r+

**Pull request closed without merging**
