### PR TITLE
[FIX] base: display white-space before the t-if when display a content

### PR DESCRIPTION
**Pull request by Gorash**
Issue: when use t-if to display text and use mutli line, the white-space are removed.
```
<div>
    <t t-out="nb"/>
    <t t-if="nb == 0 or nb == 1">product</t>
    <t t-else="">products</t>
</div>
```
is rendered:
```
<div>
    3products
</div>
```

### CODE REVIEW

**Comment by Gorash** [comment]
@rdeodoo  Partly yes. There are less lines than before because if the if is False then the empty lines are not there. There is no miracle solution, it would be difficult to differentiate a case where you have to keep the spaces because you would have to introspect the content (in addition to the css for some cases) or to say that if it only contains link/script then we delete, which is contrary to the rendering method of qweb.
It is better to render correctly than less attractive debugging for Fabien.

**Comment by rdeodoo** [comment]
Seems like you found the magical solution after all?
For tracking purpose: 14.0 and 15.0 were working well with both flows (no "useless" blank lines and space kept with `<t t-if`) without being miracle.

Tracking purpose: just copy paste this to test
```xml
0
<t>1</t>
<t t-if="True">2</t>
<t>3</t>
4
```
Should result in `0 1 2 3 4`

**Comment by Gorash** [comment]
indeed, the regular expression to remove the spaces was done after generating the document, now the change is made when creating the function that generates the document.

**Review by rdeodoo — APPROVED** [review]
Working as expected for the website part (outputted DOM).
Seems to also be fixing the initial reported issue about the space not being preserved between conditional `<t/>` elements.
Let us know if this need to be approved and/or r+ by someone from framework/internal as it is low level or if we can take care or a deeper review and merge.

**Comment by rdeodoo** [comment]
@robodoo r+ let's have this fixed so people won't open PR to locally add spaces anymore

DOM remains optimized: no extra useless lines :+1: 
image

**Pull request closed without merging**
